### ISSUE TITLE
[plugin] HP iLO

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#10]
We have no plugin for taht kind of checks at the moment.

One request from a potential client :

I'm looking for templates (including reading server hardware status via HP's ILO (i 've got that working on ilo2, but it fails on ilo 3 and 4) and reading apc smart-ups capacity and temperature.
=> Not urgent, but would be nice to enhance our plugin list

**Comment by davidmasson** [comment]
interested as well
+1

**Comment by matthieu-robin** [comment]
+1 needed too
this one works fine with ilo 3/4 👍
https://exchange.nagios.org/directory/Plugins/Hardware/Server-Hardware/HP-(Compaq)/check_ilo2_health/details

**Comment by kadrika** [comment]
+1 also :)

**Comment by garnier-quentin** [comment]
It's coming ;)

**Comment by garnier-quentin** [comment]
Could you test it please ?

An example:
perl centreon_plugins.pl --plugin=hardware/server/hp/ilo/xmlapi/plugin.pm --mode=hardware --hostname=ilo_ip --username=user  --password="pass" --verbose

If you have a problem, give me result with --debug option please

**Comment by Tetsumaki** [comment]
+1 problem here.

```
/usr/lib/centreon/plugins/centreon_hp_ilo_xmlapi.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX'
```

**Ok with ILO 2 :**

`OK: All 12 components are ok [1/1 fans, 9/9 temperatures, 2/2 vrm]. | 'fan_Virtual Fan'=25%;;;0; 'temp_Temp 1'=40C;;;; 'temp_Temp 2'=28C;;;; 'temp_Temp 3'=30C;;;; 'temp_Temp 4'=30C;;;; 'temp_Temp 5'=28C;;;; 'temp_Temp 8'=46C;;;; 'temp_Temp 9'=20C;;;;`

**KO with ILO 3 :**

`UNKNOWN: Cannot get data: HTTP::Response=HASH(0x2114bb0)->status_line`

**KO with ILO 4 :**

`UNKNOWN: Cannot get data: HTTP::Response=HASH(0x1739090)->status_line`

With `--verbose` argument, the ouput is the same.

**Comment by garnier-quentin** [comment]
You cannot give the result with --debug option please ?

**Comment by Tetsumaki** [comment]
The output is the same (fresh install with CentOS 7) :

```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_hp_ilo_xmlapi.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX'
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x186b140)->status_line
-bash-4.2$ /usr/lib/centreon/plugins/centreon_hp_ilo_xmlapi.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX' --verbose
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x3396300)->status_line
-bash-4.2$ /usr/lib/centreon/plugins/centreon_hp_ilo_xmlapi.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX' --debug
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x1b66520)->status_line
-bash-4.2$ /usr/lib/centreon/plugins/centreon_hp_ilo_xmlapi.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX' --verbose --debug
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x3095170)->status_line
```

**Comment by garnier-quentin** [comment]
Could you use the last version from github please ? Maybe it's not the last version.

**Comment by Tetsumaki** [comment]
Installed version is the last with yum from repository plugin-packs and not from github :

```
[root@xxx ~]# yum info centreon-plugin-Hardware-Servers-Hp-Ilo-Xmlapi
Paquets installés
Nom                 : centreon-plugin-Hardware-Servers-Hp-Ilo-Xmlapi
Architecture        : noarch
Version             : 20161212
Révision            : 1.el7
Taille              : 280 k
Dépôt               : installed
Depuis le dépôt     : centreon-stable-noarch
Résumé              : Centreon plugin
URL                 : https://www.centreon.com/
Licence             : ASL 2.0
Description         :
```

**Comment by garnier-quentin** [comment]
I don't manage plugin-packs ;) Could you try with the last github master ? And if there is still a problem, we could do a session.

**Comment by Tetsumaki** [comment]
Tested from with fresh git clone in /tmp for try :

```
-bash-4.2$ pwd
/tmp/centreon-plugins-master
-bash-4.2$ ./centreon_plugins.pl --version
Global Version: 20170613
-bash-4.2$ ./centreon_plugins.pl --plugin=hardware/server/hp/ilo/xmlapi/plugin.pm --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX'
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x2728a10)->status_line
-bash-4.2$ ./centreon_plugins.pl --plugin=hardware/server/hp/ilo/xmlapi/plugin.pm --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX' --verbose
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x2979ba0)->status_line
-bash-4.2$ ./centreon_plugins.pl --plugin=hardware/server/hp/ilo/xmlapi/plugin.pm --mode=hardware --username='XXX' --password='XXX' --component='.*' --hostname='XXX' --debug
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x2452ba0)->status_line
```

**Comment by Sims24** [comment]
Hi, 

Maybe print few things could help. Could you add lines below to make your api.pm check_ilo_error functon looks like below and send us the output ? 

```
sub check_ilo_error {
    my ($self, %options) = @_;
    use Data::Dumper;
   print Dumper($self->{content});
    # Looking for:
    #    <RESPONSE
    #        STATUS="0x005F"
    #         MESSAGE='Login credentials rejected.'
    #        />
    while ($self->{content} =~ /<response[^>]*?status="0x(.*?)"[^>]*?message='(.*?)'/msig) {
        my ($status_code, $message) = ($1, $2);
        if ($status_code !~ /^0+$/) {
            $self->{output}->add_option_msg(short_msg => "Cannot get data: $2");
            $self->{output}->option_exit();
        }
    }
}
```

**Comment by Tetsumaki** [comment]
Same output.

**Comment by c0c00n** [comment]
Running in to the same problem

./centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname='IP' --username='' --password='' --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --verbose --debug

`UNKNOWN: Cannot get data: HTTP::Response=HASH(0x23f8768)->status_line`

curl -k https://ILOIP/xmldata?item=All

```
<SPN>ProLiant DL380 Gen10</SPN>
<PN>Integrated Lights-Out 5 (iLO 5)</PN>
<FWRI>1.15</FWRI>
<HWRI>ASIC: 21</HWRI>

```
