### ISSUE TITLE
Supervise website

### ISSUE THREAD

**Issue by Giacomoni-GRF** [centreon/centreon-plugins#1002]
Dear all,

We want to supervise a web page via authent and to put back data on a web page (zombie Processses, kernel ...) (see page in PJ and in yellow the zones that one wishes to go up)
How to proceed ?

Regards,

Thanks

![page web](https://user-images.githubusercontent.com/39804149/40791775-944f71ea-64f8-11e8-8b24-a3e02d8747f9.jpg)

Jonathan

**Comment by Sims24** [comment]
Hi @Giacomoni-GRF 

You probably have to developp a dedicated plugin for this. No chance to catch several xml nodes with existing http / soap plugin.

**Comment by Sims24** [comment]
This will be adresses more globally and we'll let you know as soon as a acceptable solution has been found to check this.
