### ISSUE TITLE
Event 2006: PerfNet

### ISSUE THREAD

**Issue by Bettisboy** [centreon/centreon-plugins#1004]
Everytime the poller is polling a Windows Server 2016 64 Bit for Disk, Memory, CPU,..a specific event appears in the Server's Application Event Log.
The Event specifies:
'Unable to read Server Queue performance data from the Server Service. The first four bytes (DWORD) of the Data section contains the status code, the second four bytes contains the IOSB.Status and the next four bytes contains the IOSB.Information'
Although we have installed the 64 BIT NSClient it appears that some 32 bit code is trying to access the wmi performance queue, causing this error.

NSClient: centreon-nsclient-051-1.0-2-x64
Centreon: 2.8.17

We have tried to get the counters via the Check_nt and SNMP, and although both provide accurate info, they both cause the even in the application log to appear.
Result of both checks below:

Check_nt
[root@XXXXX ~]# /usr/lib/nagios/plugins/check_nt -H XX.XX.XX.XX -p 12489 -s 'XXXXXX’-v USEDDISKSPACE  -l C -w 95 -c 98 -t 60
C:\ - total: 63.51 Gb - used: 19.04 Gb (30%) - free 44.46 Gb (70%) | 'C:\ Used Space'=19.04Gb;60.33;62.24;0.00;63.51

SNMP Disk Check
[root@XXXXX ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=XX.XX.XX.XX --snmp-version='1' --snmp-community='XXXXX'  --storage='1' --display-transform-src='' --display-transform-dst='' --warning='90' --critical='95'
OK: Storage 'C:\ Label:  Serial Number e8b7e40f' Total: 63.51 GB Used: 19.04 GB (29.99%) Free: 44.46 GB (70.01%) | 'used'=20449177600B;0:61373778739;0:64783433113;0;68193087488

**Comment by Sims24** [comment]
Hi @Bettisboy 

This is rather a windows issues and we didn't get this kind of feedbacks previously. 

Think we cannot help here :/

**Comment by Bettisboy** [comment]
Hi @Sims24 

Thanks for the feedback.
We have multiple Windows 2016 servers and all appear to be showing the same behavior. Strange thing is that when we stop the NSClient and thus when there is no polling, these errors do not occur anymore.

**Comment by Sims24** [comment]
@Bettisboy think that you should use check_nrpe instead of check_nt, and using new nsclient command like check_drivesize, might fix this. 

Also, feel free to ask on /mickem/nscp repository he is far more competent than me on Windows internals
