### ISSUE TITLE
[network::h3c::snmp::plugin] mode hardware

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1005]
Hello,

I report 2 bugs here :

1/ option --absent-problem does not work :
# /usr/lib/centreon/plugins/centreon_h3c.pl --plugin=network::h3c::snmp::plugin --mode=hardware --hostname=XX.XX.XX.XX --snmp-version='2c' --snmp-community='YYYYYYYY' --snmp-timeout=45 --snmp-retries=1 --component='chassis' --reload-cache-time='0' --absent-problem=chassis#2# --verbose
OK: All 1 components are ok [1/1 chassis]. |
Checking chassis
chassis 'HPE > HPE 5130-48G-PoE+-4SFP+ (370W) EI JG937A Software Version 7.1.045' status is 'normal' [instance = 3]

2/ option --reload-cache-time='0' does not work : it always generate a cache file :
# ls -l /var/lib/centreon/centplugins/*XX.XX.XX.XX*
-rw-rw-r-- 1 centreon-engine centreon-engine 99845  4 juin  10:28 /var/lib/centreon/centplugins/cache_h3c_entity_XX.XX.XX.XX_161
# date
lun. juin  4 10:31:17 CEST 2018
# /usr/lib/centreon/plugins/centreon_h3c.pl --plugin=network::h3c::snmp::plugin --mode=hardware --hostname=XX.XX.XX.XX --snmp-version='2c' --snmp-community='YYYYYYYY' --snmp-timeout=45 --snmp-retries=1 --component='chassis' --reload-cache-time='0' --absent-problem=chassis#2# --verbose
OK: All 1 components are ok [1/1 chassis]. |
Checking chassis
chassis 'HPE > HPE 5130-48G-PoE+-4SFP+ (370W) EI JG937A Software Version 7.1.045' status is 'normal' [instance = 3]
# ls -l /var/lib/centreon/centplugins/*XX.XX.XX.XX*
-rw-rw-r-- 1 centreon-engine centreon-engine 99845  4 juin  10:32 /var/lib/centreon/centplugins/cache_h3c_entity_XX.XX.XX.XX_161

Thanks

**Comment by Sims24** [comment]
Hi, 

We should better handle the cache file for h3c equipments. We'll work on it asap.

**Comment by ritouret** [comment]
Thank you Simon,

Actually, it can takes around 6 minutes to be executed !

What about the 1/ reported bug about the option --absent-problem does not work ?
