### ISSUE TITLE
[storage::netapp::snmp::plugin] Firmware Version of NetApp Server

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon-plugins#1007]
Hello,

I want to monitor my NetApp server using the centreon-plugins NetApp. SNMP is activated on the server but when I want to monitor a component it returned a SNMP error : "Can't get a single value !".

I have tried to get all the informations I can on the NetApp server via a SNMP Walk command and none of the OIDs configured into the centreon plugins appeared.

So did you develop the NetApp centreon plugins for a specific firmware version ? And if yes what version  do I need to have to make the NetApp centreon plugins work ?

**Comment by Sims24** [comment]
Hi @Crash-Fox,

NetAPP now uses a dedicated VM to expose metrics through a rest api. Maybe that could be the better solution depending on which NetApp model you're using. I think this is the point here. 

When using SNMP you directly ask to the metrocluster and this is now deprecated.

**Comment by Crash-Fox** [comment]
Okay and thanks for your response.

But when I tried the NetApp Rest API, it returned **UNKNOWN: 501 Not Implemented** for any components.

Does it mean that I have to activate the REST API on the NetApp server ?
Or is it a functionnality for which I need to upgrade the firmware version ?

**Comment by Sims24** [comment]
Which version/firmware/model of NetApp do you have ?

**Comment by Crash-Fox** [comment]
Model : **E-Series E2724**
Firmware Version: **08.40.00.01** 
NVSRAM Version: **N280X-840834-D03**

**Comment by garnier-quentin** [comment]
That's the same issue: https://github.com/centreon/centreon-plugins/issues/910
```
it s a netapp e-series (hybrid flash). It seems you need santricity web proxy to monitor your storage with the rest api. Right now, we don t have a plugin for that
```
