### ISSUE TITLE
[storage::qnap::snmp::plugin] mode hardware

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1008]
Hello,

The following option for smartdisk does not work :
 --threshold-overload='smartdisk,CRITICAL,^(?!(ready|normal)$)'

It answers :
UNKNOWN: Wrong threshold-overload section 'smartdisk,CRITICAL,^(?!(ready|normal)$)'

How can i have status NORMAL when smartdisk is Ready or Normal ?
$ /usr/lib/centreon/plugins/centreon_qnap.pl --plugin=storage::qnap::snmp::plugin --mode=hardware --hostname=XX.XX.XX.XX --snmp-version='2c' --snmp-community='YYYYYYYY' --snmp-timeout=15 --snmp-retries=1 --component='.*' --filter-perfdata=temp_system --threshold-overload='disk,CRITICAL,^(?!(ready|normal)$)' --verbose
WARNING: Disk 'HDD1' smart status is Normal. | 'temp_system'=32C;;;;
Checking temperatures
System Temperature is '32' degree centigrade
Checking disks
Disk 'HDD1' [instance: 1, temperature: 32 C/89 F, smart status: Normal] status is ready.
Disk 'HDD2' [instance: 2, temperature: 33 C/91 F, smart status: GOOD] status is ready.

Thanks.

**Comment by Sims24** [comment]
Hello @ritouret , 

This is a bug, we'll work on it and provide a fix soon. 

Thanks for your feedback
