### ISSUE TITLE
Unknown option: warning-memory at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 141

### ISSUE THREAD

**Issue by SistemasEnergy** [centreon/centreon-plugins#1010]
Hi all,

I have this issue with the last update of Nagios Centreon to version 2.8.22. I have read the issue #893 but noone is answering again and I would need help on this. Sorry but I'm very noob with Centreon and Linux, so my knowns are very little on these.

Anyone could help me please?

Thanks in advance and regards

**Comment by Sims24** [comment]
Hi @SistemasEnergy 

Can you confirm that your plugin is in the following version :

**Comment by SistemasEnergy** [comment]
Hi @Sims24 

Thank you for reply. This is the version i have:

centreon-plugin-Operatingsystems-Windows-Snmp-20161212-1.el6.noarch

Thanks and regards

**Comment by Sims24** [comment]
Last version is 20180427-1 so your is outdated, please udpate ;)

**Comment by SistemasEnergy** [comment]
Hi @Sims24 

How can I update that plugin?

Thanks

**Comment by Sims24** [comment]
`yum update centreon-plugin-Operatingsystems-Windows-Snmp`

**Comment by SistemasEnergy** [comment]
Ok, plugin updated, now is necessary to restart any service or the poller?

Regards

**Comment by SistemasEnergy** [comment]
Sorry, poller updated and now is working ok again,

Thank you so much @Sims24 !!!

Kind regards

**Comment by Sims24** [comment]
You're welcome
