### ISSUE TITLE
graph-monitoring dissapeared

### ISSUE THREAD

**Issue by SistemasEnergy** [centreon/centreon-plugins#1011]
Hi all,

First of all give all of you my sincere congratulations for your work with this great monitoring solution.

After last update to Centreon 2.8.22 the graph-monitoring widget on custom views is not painting any graph. However if I go to any cpu service for example, the graph is showing correctly.

How could I fix this?

Thanks in advance and regards

**Comment by Sims24** [comment]
Hi, 

This is the wrong github, use centreon dedicated one please. 

Probably that you should update your centreon-widget* package with yum and also in "Administration > extension Menu". 

Close as it's not directly related to the plugins.
