### ISSUE TITLE
[snmp_standard] mode interfaces

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1013]
Hello,

Would it be possible to add an option to find the index through the interface ip address ?

The correspondance can be find here :
IP-MIB::ipAdEntIfIndex
.1.3.6.1.2.1.4.20.1.2

It has be done here :
https://exchange.nagios.org/directory/Plugins/Network-Connections%2C-Stats-and-Bandwidth/check_iftraffic3/details

Thanks

**Comment by ritouret** [comment]
it should be used with this existing option :
    --oid-filter
            Choose OID used to filter interface (default: ifName) (values:
            ifDesc, ifAlias, ifName).

The added value in this option would be ipAdEntIfIndex ...

**Comment by cgagnaire** [comment]
Already opened here https://github.com/centreon/centreon-plugins/issues/553.
Will use the other one for the follow up.
