### ISSUE TITLE
network::cisco::standard::snmp::plugin check vlan? 

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#1014]
Hello,

is there a way to give a Vlan and the plugin gives the state of the Ports where the VLAN is mapped and it STP status? Furthermore, is there a way to check if the given host is the route bridge?

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
