### ISSUE TITLE
Dell IDRAC v9

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#1016]
[idrac.txt](https://github.com/centreon/centreon-plugins/files/2094820/idrac.txt)
Hi,

I got last week some Dell PowerEdge R440 with IDRAC9 (see snmpwalk dump).

The current plugin (hardware/server/dell/idrac/snmp/plugin) doesn't seem to work with this version of IDRAC.

Does anybody have such a hardware ?

jfr

**Comment by Sims24** [comment]
Hi @jframeau 

Looks like globalhealth should work but cannot find hardware informations in the MIB. 

Might be an Idrac or SNMP Configuration issue because walk is really poor, do you have any error message popping when snmpwalk through command line ?

**Comment by boscorelly** [comment]
check that openmanage show you all informations about server.

**Comment by garnier-quentin** [comment]
Could you provide us the snmp mib of your idrac ? Otherwise it seems there is a rest api on idrac9. Could you test it ?

**Comment by garnier-quentin** [comment]
With snmp v3, it should provide more information. You can open it if you still have an issue.
