### ISSUE TITLE
network/arista/snmp/plugin.pm memory output bug

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1018]
Hi,

When checking memory usage on an Arista device, the output shows OK: All storages are ok.
But is should say OK: Memory is ok. or OK:Memory usage is x% etc.
Thanks in advance!

**Comment by Sims24** [comment]
Hi @kadrika 

Is this really important for you ? We use snmp standard storage mode, allowing us to save a lot of code .. 

If you are not comfortable we will try to find a solution for you.

Thanks

**Comment by kadrika** [comment]
Problem is just that the output shows storage, but we are checking actually memory, so our customer thinks we have mis-configured the service.

**Comment by cgagnaire** [comment]
Hi @kadrika,
Just fixed it.
