### ISSUE TITLE
[apps::vmware::connector::plugin] disco-format - error on macro available in rule

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1019]
Hi,

I've been create a rule for vmware list-clusters
in command line, it's ok
/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=list-clusters --connector-hostname='localhost' --disco-format
<?xml version="1.0" encoding="utf-8"?>
<data>
  <element>name</element>
</data>

 but over the rule, it can't retrieve macro's
![image](https://user-images.githubusercontent.com/8720203/41465034-b0a53e4c-709c-11e8-8880-d53ff5fc53ad.png)

Despite this, the rule is functionnal.

Have I make a mistake in the command?
Thanks,

**Comment by Sims24** [comment]
Hi Cedric, 

Does this script "/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl " actually exist on the central server ?

**Comment by cmeschin** [comment]
Hi Simon,

Sorry I'm confused. It's not installed. :(
It's ok now.
Thanks
