### ISSUE TITLE
Monitoring Cisco devices (plugin network::cisco::standard::snmp::plugin)

### ISSUE THREAD

**Issue by dgoudet** [centreon/centreon-plugins#1021]
Hello,

To monitor Cisco devices we are using service template "Environment / Net-Cisco-Standard-Environment-SNMP-custom".

On our switch and router devices some interfaces are in "Administratively down" status (corresponding to our choice to disable the interface).
On these devices the check is in "Critical state" due to signal quality check (dBm) on these interfaces because the values are out of thresholds. Carry out signal quality check on shutdown interface has no sense, is it possible to exclude these interface during the check (status will be OK)? If yes what is the best way to proceed?

Otherwise is it possible to disable signal quality check on each interfaces related to the service (and continue to monitor everything else: Volt, Ampere, ...)

Thank you,

Regards,

**Comment by dgoudet** [comment]
Hello,

any ideas?

**Comment by Sims24** [comment]
Hello @dgoudet 

Looks like you're in the following case https://github.com/centreon/centreon-plugins/issues/267 and https://github.com/centreon/centreon-plugins/issues/256 do you confirm ? 

You have to use the options provided in in #256 at the end of the thread to avoid such issue. 

Thanks

**Comment by dgoudet** [comment]
Hello,

I found solution by using --filter parameter as following:

sudo -u centreon-engine /usr/lib64/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=environment --hostname=xxx --snmp-version='3' ... --filter=sensor,1147

We have to precise "instance id" which correspond to interface id, here 1147 (interface id is shown in STDOUT description).

WARNING: Sensor 'subslot 0/0 transceiver 4 Rx Power Sensor/1147' is -2.8 dBm

**Comment by dgoudet** [comment]
Hello,

I found solution by using --filter parameter as following:

sudo -u centreon-engine /usr/lib64/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=environment --hostname=xxx --snmp-version='3' ... --filter=sensor,1147

We have to precise "instance id" which correspond to interface id, here 1147 (interface id is shown in STDOUT description).

WARNING: Sensor 'subslot 0/0 transceiver 4 Rx Power Sensor/1147' is -2.8 dBm

**Comment by garnier-quentin** [comment]
I have done some fix. It should be ok except port down (0 dBm for example).
