### ISSUE TITLE
[apps::protocols::x509::plugin] certificate monitoring impossible because of user certificate

### ISSUE THREAD

**Issue by ant0nwax** [centreon/centreon-plugins#1022]
Hi Quentin

There is a certificate monitor included in centreon (x509)

So i tried now half a day to solve this and finally found the issue with debugging using s_client

centreon shows this: (it is working with other certificates)

```
/usr/bin/perl /usr/lib64/nagios/centreon-plugins/centreon_plugins.pl --plugin apps::protocols::x509::plugin --mode validity --validity-mode expiration --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --critical-date '30:' --warning-date '60:' --hostname hostname.tld --port 443
CRITICAL: failed to accept or ssl handshake: ,IO::Socket::INET configuration failederror:00000000:lib(0):func(0):reason(0) |
```

s_client shows this:

```
openssl s_client -tls1 -connect 'hostname.tld:443' -showcerts
CONNECTED(00000003)
depth=1 C = CC, L = CITY-EXAMPLE, O = ORG-EXAMPLE, CN = CA-EXAMPLE
verify error:num=19:self signed certificate in certificate chain
verify return:0
139961056823112:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:s3_pkt.c:1275:**SSL alert number 40**
139961056823112:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:s3_pkt.c:598:
---
Certificate chain
(...)
```

Note as well the line

SSL alert number 40

That indicates the server won't accept the connection because no user certificate was presented (complete the command line).

You can use OpenSSL to check a user certificate is presented to a server that need it. You then have to specify the user certificate and the private ke with the -cert et -key parameters.

so in this case the --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" is not usable, do you have any idea how we could get this certificate monitored? I searched already one hour in the net, and did not really find software for simulating a user certificate, maybe it would not be needed if you could tweak the code?

Thanks a lot and have a great day

**Comment by ant0nwax** [comment]
A suggestion for monitoring certificate expiry in bash

command used: bc, date, echo, openssl, sed

`echo "("$(date +%s -d "`echo | openssl s_client -connect [hostname.tld]:[port] 2>/dev/null | openssl x509 -noout -enddate | sed 's/.*notAfter=\(.*\)$/\1/g'`")"-"$(date +%s)")/86400" | bc`

**Comment by cgagnaire** [comment]
Hi @ant0nwax,
What's your OS, Net-SSLeay and IO-Socket-SSL versions  ?
Thank you.

**Comment by garnier-quentin** [comment]
Do you have a website to test it ?

**Comment by ant0nwax** [comment]
I am back to that project only in July, I will update this message here, in july

**Comment by ant0nwax** [comment]
i found this

https://stackoverflow.com/questions/38095559/https-test-server-that-checks-client-certificates

and i could test in our environment if you send me an updated script

Sent from my P9 tard-phone running Oreo.  Random auto-corrects and typos
are my special gift to you.

**Comment by garnier-quentin** [comment]
I don't reproduce your errors with test website from the thread 'stackoverflow'.

**Comment by ant0nwax** [comment]
it is working yes, because the certificate you check is on https:// and the current script cannot check https:// /secure I assume ?

**Comment by ant0nwax** [comment]
cannot edit last post for unknown reason, so I post again:

root@magicaltestserver ~ # /usr/bin/perl /usr/lib64/nagios/centreon-plugins/centreon_plugins.pl --plugin apps::protocols::x509::plugin --mode validity --validity-mode expiration --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --critical-date '30:' --warning-date '60:' --hostname server.cryptomix.com/secure --port 443
CRITICAL: failed to accept or ssl handshake: Invalid argument,IO::Socket::INET6 configuration failederror:00000000:lib(0):func(0):reason(0)

**Comment by garnier-quentin** [comment]
There is an issue with your hostname here:
```
--hostname='server.cryptomix.com'
```
