### ISSUE TITLE
[enhancement] hp 3par - use checkhealth node command 

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#1025]
Need to use a mode checkhealth to spot when a controller has been lost. 

We may add it to existing mode (https://github.com/centreon/centreon-plugins/blob/master/storage/hp/3par/7000/mode/node.pm) or create a dedicated one. 

Sample output : 

```
3PAR-XXX cli% checkhealth node
Checking node
Component -------Description------- Qty
Node   Nodes that are not online  1
```

**Comment by garnier-quentin** [comment]
With the new 3par ssh and components mode: --critical-count-node=2:
