### ISSUE TITLE
ERROR value for TEMPERATURE in plugin dell 6200

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#1026]
ERROR value for TEMPERATURE in plugin dell 6200 

# /usr/lib/nagios/centreon-plugins/centreon_plugins.pl --plugin network::dell::6200::plugin --mode environment --hostname A.B.C.D --snmp-community *******--exclude='' --no-component='' --warning-temperature='40' --critical-temperature='50' --component='all'

OK: All 5 components are ok [1/1 psus, 4/4 temperature sensors]. | 'Temperature_0'=2c;;;; 'Temperature_0'=1c;;;; 'Temperature_0'=2c;;;; 'Temperature_0'=1c;;;;

# snmpwalk -v2c -c ******* -O n A.B.C.D .1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.4
.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.4.1.0 = INTEGER: 2
.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.4.2.0 = INTEGER: 1
# snmpwalk -v2c -c ******* -O n A.B.C.D .1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.5
.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.5.1.0 = INTEGER: 36
.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.5.2.0 = INTEGER: 34

Thanks in advance!

**Comment by cgagnaire** [comment]
Hi @Jordan91,
It looks like you are not using the lastest version as this is already handled.
Perfdata looks strange.

**Comment by cgagnaire** [comment]
Confirmed with walk.
Please update to last version.

Command line should be : 
`perl centreon_plugins.pl --plugin=network::dell::6200::snmp::plugin.pm --mode=environment --hostname=<hostname> --warning='temperature,.*,40' --critical='temperature,.*,50'`
