### ISSUE TITLE
issue in second header option in apps::protocols::http::plugin

### ISSUE THREAD

**Issue by benoitbass974** [centreon/centreon-plugins#1027]
Hello,

I want to report you a bug in the centreon plugin http ( apps::protocols::http::plugin). When I use two header option, the plugin send the second header with an uppercase in the first letter. 

Thank you.

**Comment by Sims24** [comment]
Hi @benoitbass974 

We will check this thanks for the feedback

**Comment by Sims24** [comment]
After further research header are case-insensitive and we are never changing what is passed from cli options.
