### ISSUE TITLE
Add plugin check of Veeam Backup jobs

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#103]
Hello,

Is it possible to create a Plugin for Veeam backups jobs?
http://www.veeam.com/kb1040

Thanks a lot

**Comment by Shini31** [comment]
Hello,

This article speaks only of SNMP traps .
Apparently the SNMP polling is not possible.
The only way to monitor the backup and jobs is to develop a script that will run locally on the server Veeam.

Regards.

**Comment by matthieu-robin** [comment]
OK Shini

Thanks a lot for your investigation  :-)
