### ISSUE TITLE
[plugin=apps::pacemaker::local::plugin] Three modes doesn't work.

### ISSUE THREAD

**Issue by cryptonirvanabobxi** [centreon/centreon-plugins#1032]
Hello guys,

Need some help.

I was testing your pacemaker plugins but I couldn't make it work in the web UI. I am using 2 Centos 7.5 VMs in Active-Passive Failover mode. Also I'm using SNMP v2c and other plugins are working fine for me.

**Here is my `pcs status` output**
Cluster name: CentCluster
Stack: corosync
Current DC: monitor2 (version 1.1.18-11.el7_5.2-2b07d5c5a9) - partition with quorum
Last updated: Tue Jul  3 22:04:52 2018
Last change: Tue Jul  3 22:04:49 2018 by root via cibadmin on monitor1

2 nodes configured
4 resources configured

Online: [ monitor1 monitor2 ]

Full list of resources:

 clusterip      (ocf::heartbeat:IPaddr2):       Started monitor1
 Resource Group: ClusterCentreon
     cbd        (systemd:cbd):  Started monitor1
     centcore   (systemd:centcore):     Started monitor1
     centengine (systemd:centengine):   Started monitor1

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/disabled

Here are my output in both CLI and Centreon web UI.

Shell
`perl centreon_plugins.pl --plugin=apps::pacemaker::local::plugin --mode=crm`
OK: Cluster is OK |

`perl centreon_plugins.pl --plugin=apps::pacemaker::local::plugin --mode=constraints --resource=clusterip`
OK: Resource 'clusterip' constraint location is OK |

WebUI
`perl centreon_plugins.pl --plugin=apps::pacemaker::local::plugin --mode=crm`
UNKNOWN: Command error: - Connection to cluster failed: Transport endpoint is not connected

`perl centreon_plugins.pl --plugin=apps::pacemaker::local::plugin --mode=constraints --resource=clusterip`
UNKNOWN: Command error: Error signing on to the CIB service: Transport endpoint is not connected - Error performing operation: Transport endpoint is not connected

![image](https://user-images.githubusercontent.com/40128726/42225712-c6cf8016-7f0f-11e8-9030-f0e50dfdd356.png)

**Comment by cryptonirvanabobxi** [comment]
I found out that when Im in the shell, I am running as root user and not as centreon. When I try to su using centreon, The same error appears as the webgui. I guess this has something to do with centreon's permissions to run pcs crm and other commands related to pacemaker.

**Comment by cryptonirvanabobxi** [comment]
I figured it out now. You must add the user centreon, centreon-broker and centreon-engine as a administrator ACL of Pacemaker. You must configure administrator ACL first then add the users. You can access the web gui of pacemaker to make the configuration easier.

**Comment by cgagnaire** [comment]
Hi @cryptonirvanabobxi,
Thanks for the follow up, and glad you managed to debug it yourself.
