### ISSUE TITLE
Traffic check plugins with --name: do not use regexes by default

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon-plugins#1033]
Hi, it looks like all traffic plugins currently use regexes by default, which isn't really intuitive, leading to the following behaviour:
```
centreon_fortinet_fortigate.pl --plugin network::fortinet::fortigate::plugin --mode interfaces --hostname xxx --snmp-community xxx --snmp-version='2c' --add-traffic --interface='port1' --name  --verbose
OK: All interfaces are ok |
Interface 'port10' Traffic In : skipped, Traffic Out : skipped
Interface 'port11' Traffic In : skipped, Traffic Out : skipped
Interface 'port12' Traffic In : skipped, Traffic Out : skipped
Interface 'port13' Traffic In : skipped, Traffic Out : skipped
Interface 'port14' Traffic In : skipped, Traffic Out : skipped
Interface 'port15' Traffic In : skipped, Traffic Out : skipped
Interface 'port16' Traffic In : skipped, Traffic Out : skipped
Interface 'port1' Traffic In : skipped, Traffic Out : skipped
```
Adding `^` and `$` delimiters will fix the issue in that case but it is still counter-intuitive and shoulnd't be necessary.
IMO the plugin should behave like the disk checks and only treat the interface name as a regex if `--regexp` is passed.

**Comment by cgagnaire** [comment]
Hi @sbraz,
I understand what you're saying but we won't change this behaviour.
As you said, you just have to add those 2 delimiters to king of disable regexp lookup.
