### ISSUE TITLE
Use of uninitialized value in split at /centreon.com/centreon/plugins/dbi.pm line 180

### ISSUE THREAD

**Issue by jmpalomares** [centreon/centreon-plugins#1038]
Hello,

I'm receiving the following from centron script:

`Use of uninitialized value in split at /centreon.com/centreon/plugins/dbi.pm line 180`

Is this something that you already fixed in new versions?

Kind regards,

**Comment by Sims24** [comment]
Hello, 

Could you give us some context about the error ? Is this about an MSSQL or Oracle Check ? Which version of the SGBD is it ? 

Thanks

**Comment by jmpalomares** [comment]
Hi there @Sims24 

This error appears when doing an uptime check of the mysql service. 

Plugin = "database::mysql::plugin"
mode = "uptime"

The check still works correctly but I see that error message in the status.

Kind regards,

**Comment by garnier-quentin** [comment]
Could you connect on your mssql server and execute following request:
```
select @@version
```

**Comment by lolo54000** [comment]
Hi 
I have this if i execute this command
Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64)   Aug 15 2017 10:23:29   Copyright (c) Microsoft Corporation  Business Intelligence Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by garnier-quentin** [comment]
With the same user used in centreon plugins command line ?

**Comment by lolo54000** [comment]
I don't understand your question I have 3 Mssql instance  and i have this error on all mssql instance 1 is in mssql 2012 and the other are in mssql 2016 
If i execute the command (/usr/lib/centreon/plugins/centreon_plugins.pl.....) in linux shell it work fine but if i execute the same command in centreon on the  same server i have the error. the username and password in command line and centreon are the same.

**Comment by garnier-quentin** [comment]
Could you execute select @@version on a mssql server without that error (if you have)
```
Use of uninitialized value in split at /centreon.com/centreon/plugins/dbi.pm line 180 #
```

**Comment by lolo54000** [comment]
I dont have :(

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test it with the following version ?
https://github.com/garnier-quentin/centreon-plugins/archive/bug-mssql-version.zip

**Comment by lolo54000** [comment]
I test with this version (if i do centreon_plugins.pl --version i have (dev) 
But i have the same problem in shell my command line work perfectly but in centreon i have  i have UNKNOWN: Cannot connect: (no error string)

**Comment by garnier-quentin** [comment]
It's an issue with centreon. It comes from the backslash character. Try to backslash twice. 
You don't have the following error anymore ?
```
Use of uninitialized value in split at /centreon.com/centreon/plugins/dbi.pm line 180 #
```

**Comment by lolo54000** [comment]
I test with 4 backslash in centreon to obtain backslash twice in command and now it's work fine :) 
in shell command i still have the error  use of uninitialized...
![capture](https://user-images.githubusercontent.com/14163451/50293865-dbb06a00-0474-11e9-847b-72e672c5f6e7.JPG)

**Comment by lolo54000** [comment]
I test with 4 backslash in centreon to obtain backslash twice in command and now it's work fine :)

in shell command I do not have the error anymore

thanks for your help

**Comment by garnier-quentin** [comment]
Thanks for the feedback

**Comment by rmorandell-pgum** [comment]
Hi,

I have downloaded the last plugins after your fix but unfortunately my backup-age and my connected-users are not working anymore. The warning is still there, but unfortunately the statement is no longer valid. If I replace in the FUNCTION query in file centreon \ plugins \ dbi.pm with the old one again it runs again. It's show me a warning but the result is valid.

This is the statement and the result without your fix:

 ./centreon_plugins.pl --plugin=database::mssql::plugin --mode=backup-age --hostname=10.170.37.22 --port=1433 --username='PGUM\roman' --password=xxx --warning=10000 --critical=100000 --filter=Northwind

Use of uninitialized value in split at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 180.
OK: All backups are ok. | 'db_Northwind_backup_age'=3950s;0:10000;0:100000;0; 'db_Northwind_backup_duration'=1s;;;0;

This is the result after updating the plugins:

ct_describe() failed at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 274.
Use of uninitialized value in split at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 180.
Segmentation fault

Any idea ?

Thank you for your help

Roman

**Comment by garnier-quentin** [comment]
You talk about which fix ? Could you try that sql command with tsql command:
select SERVERPROPERTY('productversion') as product_version

**Comment by rmorandell-pgum** [comment]
Hi,

i'm talking about this: Fix bug mssql version (#1038) #1285 on Dec 2018

https://github.com/centreon/centreon-plugins/pull/1285/files

My SQL Server is a 2017 Express (for test now)

Version: 14.0.1000.169

**Comment by garnier-quentin** [comment]
The sql request provides a response ?

**Comment by rmorandell-pgum** [comment]
Yes ..

1> select SERVERPROPERTY('productversion') as product_version
2> GO
product_version
14.0.1000.169
(1 row affected)

I tested it with an SQL2008, too

1> select SERVERPROPERTY('productversion') as product_version;
2> GO
product_version
10.50.6560.0
(1 row affected)

**Comment by rmorandell-pgum** [comment]
--mode=connection-time is working 

OK: Connection established in 0.045s. | 'connection_time'=45ms;0:100;0:300;0;

**Comment by garnier-quentin** [comment]
that's weird. I ll need an access to look.

**Comment by rmorandell-pgum** [comment]
--backup-age

./centreon_plugins.pl --plugin=database::mssql::plugin --mode=backup-age --hostname=10.170.37.22 --port=1433 --username='PGUM\roman'--password=xxx --warning=10000 --critical=100000 --filter=Northwind

===select SERVERPROPERTY('productversion') as product_version===
$VAR1 = bless( {}, 'DBI::st' );
ct_describe() failed at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 279.
Use of uninitialized value in split at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 180.
===SELECT D.name AS [database_name], D.recovery_model, BS1.last_backup, BS1.last_duration
                 FROM sys.databases D
                 LEFT JOIN (
                    SELECT BS.[database_name],
                    DATEDIFF(SS,MAX(BS.[backup_finish_date]),GETDATE()) AS last_backup,
                    DATEDIFF(SS,MAX(BS.[backup_start_date]),MAX(BS.[backup_finish_date])) AS last_duration
                    FROM msdb.dbo.backupset BS
                    WHERE BS.type = 'D'
                    GROUP BY BS.[database_name]
                ) BS1 ON D.name = BS1.[database_name]
                ORDER BY D.[name]===
Segmentation fault

--connected-users

./centreon_plugins.pl --plugin=database::mssql::plugin --mode=connected-users --hostname=10.170.37.22 --port=1433 --username='PGUM\roman' --password=xxx--warning=100 --critical=300
===select SERVERPROPERTY('productversion') as product_version===
$VAR1 = bless( {}, 'DBI::st' );
ct_describe() failed at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 279.
===SELECT count(*) FROM master..sysprocesses WHERE spid >= '51'===
Segmentation fault

**Comment by garnier-quentin** [comment]
There is an issue. And i don't catch the error it seems.

**Comment by rmorandell-pgum** [comment]
In the version before i had always the warning "Use of uninitialized value in split at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 180" but i've got always a result. Could be this warning the issue ?

**Comment by garnier-quentin** [comment]
Not really. In your case, there is an issue to execute 'select SERVERPROPERTY('productversion') as product_version'. And after, it segfault.

**Comment by garnier-quentin** [comment]
Could you give the output (with the same debug) when it was ok with previous code ?

**Comment by rmorandell-pgum** [comment]
./centreon_plugins.pl --plugin=database::mssql::plugin --mode=backup-age --hostname=10.170.37.22 --port=1433 --username='PGUM\roman' --password=xxx--warning=10000 --critical=100000 --filter=Northwind
Use of uninitialized value in split at /usr/lib/centreon/plugins/centreon/plugins/dbi.pm line 180.
===SELECT D.name AS [database_name], D.recovery_model, BS1.last_backup, BS1.last_duration
                 FROM sys.databases D
                 LEFT JOIN (
                    SELECT BS.[database_name],
                    DATEDIFF(SS,MAX(BS.[backup_finish_date]),GETDATE()) AS last_backup,
                    DATEDIFF(SS,MAX(BS.[backup_start_date]),MAX(BS.[backup_finish_date])) AS last_duration
                    FROM msdb.dbo.backupset BS
                    WHERE BS.type = 'D'
                    GROUP BY BS.[database_name]
                ) BS1 ON D.name = BS1.[database_name]
                ORDER BY D.[name]===
$VAR1 = bless( {}, 'DBI::st' );
WARNING: DB 'Northwind' backup age: 65027s [Duration : 1s] | 'db_Northwind_backup_age'=65027s;0:10000;0:100000;0; 'db_Northwind_backup_duration'=1s;;;0;

**Comment by garnier-quentin** [comment]
maybe it doesn't like transact-sql. Which freetds version do you have ?

**Comment by rmorandell-pgum** [comment]
Version: freetds v1.00.98
 tds version = 8.0

perl -e 'use DBI; print $DBI::VERSION,"\n";'
1.627

CPAN: Module::CoreList loaded ok (v5.20180820)
DBD::Sybase is up to date (1.16).

**Comment by garnier-quentin** [comment]
Could you try with 'tds version = 7.0' ?

**Comment by rmorandell-pgum** [comment]
ok with tds version = 7.0 is working

**Comment by garnier-quentin** [comment]
Great. tds version 8.0 shouldn't be used.
```
For compatibility reasons version 8.0 is still handled by FreeTDS but you should avoid using it as it could be removed in a future version of FreeTDS or it could clash with a future SQL server version.
```

http://www.freetds.org/userguide/choosingtdsprotocol.htm

**Comment by rmorandell-pgum** [comment]
I tried now with 7.4 - 7.1, too. It's working only with 7.0

So for MSSQLServer2008 or MSSQLServer2017 we must use always 7.0 ?

**Comment by garnier-quentin** [comment]
That's weird. Maybe i can enhance the request. Maybe it doesn't like serverproperty function.

**Comment by garnier-quentin** [comment]
I have done a fix. Could you tried now ? It should work now (even for 8.0)

**Comment by rmorandell-pgum** [comment]
Great! Thank you. It is now running with 8.0

**Comment by garnier-quentin** [comment]
Great :) Thanks for the quick feedback!
