### ISSUE TITLE
os::linux::snmp::plugin --mode=storage cache management

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#1041]
Hello,

When we use the option --space-reservation, the perfdata are sometimes not updated:

[root@centreon34 centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=10.30.2.113 --snmp-version='2c' --snmp-community='public' --storage 31
OK: Storage '/' Usage Total: 17.11 GB Used: 3.75 GB (21.91%) Free: 13.36 GB (78.09%) | 'used'=**4024999936B**;;;0;18369396736
[root@centreon34 centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=10.30.2.113 --snmp-version='2c' --snmp-community='public' --storage 31 --space-reservation=5
OK: Storage '/' Usage Total: 17.11 GB Used: 3.75 GB (23.06%) Free: 12.50 GB (76.94%) | 'used'=**4025008128B**;;;0;18369396736
[root@centreon34 centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=10.30.2.113 --snmp-version='2c' --snmp-community='public' --storage 31
OK: Storage '/' Usage Total: 17.11 GB Used: 3.75 GB (21.91%) Free: 13.36 GB (78.09%) | 'used'=**4025016320B**;;;0;18369396736
[root@centreon34 centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=10.30.2.113 --snmp-version='2c' --snmp-community='public' --storage 31 --space-reservation=5
OK: Storage '/' Usage Total: 17.11 GB Used: 3.75 GB (23.06%) Free: 12.50 GB (76.94%) | 'used'=### **4025016320B**;;;0;18369396736

One solution is to delete the cache present in /var/lib/centreon/centplugins. The right informations are displaid the 2 or 3 first times the problem comes back a few check after.

Would it be possible to add an option like "--skip-cache" ?

**Comment by cgagnaire** [comment]
Hi @tseegers,
I don't understand your problem. The performance data are not related to cache file.
And the used metric will always be the same whatever space reservation you set. This option only change used percentage, and free space and percentage.

**Comment by tseegers** [comment]
Ok thx cgagnaire :)
