### ISSUE TITLE
file system mode w|r for storage plugins

### ISSUE THREAD

**Issue by moix** [centreon/centreon-plugins#1042]
## additional information for file system modes

hey there, due to our virtualization infrastructure we have servers that in some cases and after a crash and automatic-reboot, some file systems are mounted in read only mode.

I see there exists an oid (hrFSAccess = .1.3.6.1.2.1.25.3.8.1.5) that gives that information so was wondering if adding it as an extra perf data to snmp storage and liststorages modes will be possible and valuable?

Thanks!

**Comment by cgagnaire** [comment]
Hi @moix,
Yes we'll look at it and how to implement it.
An issue was already open about that (https://github.com/centreon/centreon-plugins/issues/314).
I'll close it and keep yours.

**Comment by garnier-quentin** [comment]
There is a new option:
```
--add-access
```

The cache must be reloaded.

**Comment by moix** [comment]
wonderfull! many thanks @garnier-quentin !! I implemented a custom check using that oid but will replace with that new option :+1: 
cheers
