### ISSUE TITLE
Monitoring Office 365 services

### ISSUE THREAD

**Issue by 69bodbod69** [centreon/centreon-plugins#1044]
Hi everybody!

I'm looking for a solution to get office 365 service status (exchange, skype,...)

If somebody has his own solution or can advice me, it would be nice. I know it is possible with a PS script but it will be so difficult for me...

Thx

Romain

**Comment by Sims24** [comment]
Hi, 

We may do something with powershell, do you have any script exemple or PS Snapin to recommend ?

**Comment by 69bodbod69** [comment]
Hi and thanks for your reponse.
Yeah I found that during my search. This is a PS script from PRTG and I don't know how to adapt it for Centreon.





#>
[CmdletBinding()] param(
    [Parameter(Mandatory = $true)][ValidateNotNullOrEmpty()][string] $ClientID,
    [Parameter(Mandatory = $true)][ValidateNotNullOrEmpty()][string] $ClientSecret,
    [Parameter(Mandatory = $true)][ValidateNotNullOrEmpty()][string] $TenantIdentifier
)

$Resource = "https://manage.office.com"
$LoginURL = "https://login.windows.net"

$IsAuthenticated = $false
$DataRetrieved = $false

$ReturnCodes = @{
    ServiceOperational = 0;
    Canceled = 1;
    Completed= 2;
    InProgress = 3;
    Scheduled = 4;
    ExtendedRecovery = 5;
    ServiceInterruption = 6;
    ServiceDegradation = 7;
    PostIncidentReviewPublished = 8;
    ServiceRestored = 9;
    VerifyingService = 10;
    RestoringService = 11;
    Investigating = 12
}

<# Function Invoke-RestMethod requires Power Shell v3 or higher #>
if ($PSVersionTable.PSVersion.Major -ge 3) {

    <# Authenticate against Azure AD and retrieve OAuth token #>
    $OauthBody = @{
        grant_type = "client_credentials";
        resource = $Resource;
        client_id = $ClientID;
        client_secret = $ClientSecret
    }

    $OauthUri = "{0}/{1}/oauth2/token?api-version=1.0" -f $LoginURL,$TenantIdentifier

    try {
        $Oauth = Invoke-RestMethod -Method Post -Uri $OauthUri -Body $OauthBody
        $IsAuthenticated = $true
    } catch {
        $MyError = "Error authenticating"
    }

    <# Get service status via REST API #>
    $Operation = "CurrentStatus"

    $ServiceUri = "https://manage.office.com/api/v1.0/{0}/ServiceComms/{1}" -f $TenantIdentifier,$Operation
    $headerParams  = @{
        Authorization = "{0} {1}" -f $oauth.token_type,$oauth.access_token
    }

    if ($IsAuthenticated) {
        try {
            $Data = Invoke-WebRequest -Headers $headerParams -Uri $ServiceUri -UseBasicParsing | ConvertFrom-Json
            $DataRetrieved = $true
        } catch {
            $MyError = "Error retrieving data"
        }
    }
} else {
    $MyError = "PowerShell Version 3.0 or higher required on probe"
}

<# Create output for PRTG #>
$XmlDocument = New-Object System.XML.XMLDocument
$XmlRoot = $XmlDocument.CreateElement("prtg")
$XmlDocument.appendChild($XmlRoot) | Out-Null

if ($DataRetrieved) {
    foreach ($Item in $Data.value) {
        $XmlResult = $XmlRoot.appendChild($XmlDocument.CreateElement("result"))

        $XmlKey = $XmlDocument.CreateElement("channel")
        $XmlResult.AppendChild($XmlKey) | Out-Null

        $XmlValue = $XmlDocument.CreateTextNode($Item.WorkloadDisplayName)
        $XmlKey.AppendChild($XmlValue) | Out-Null

        $XmlKey = $XmlDocument.CreateElement("value")
        $XmlResult.AppendChild($XmlKey) | Out-Null

        $XmlValue = $XmlDocument.CreateTextNode($ReturnCodes.($Item.Status))
        $XmlKey.AppendChild($XmlValue) | Out-Null

        $XmlKey = $XmlDocument.CreateElement("ValueLookup")
        $XmlResult.AppendChild($XmlKey) | Out-Null

        $XmlValue = $XmlDocument.CreateTextNode("custom.office365.state")
        $XmlKey.AppendChild($XmlValue) | Out-Null
    }
} else {
    $XmlError = $XmlDocument.CreateElement("error")
    $XmlRoot.AppendChild($XmlError) | Out-Null

    $XmlErrorValue = $XmlDocument.CreateTextNode(1)
    $XmlError.AppendChild($XmlErrorValue) | Out-Null

    $XmlText = $XmlDocument.CreateElement("Text")
    $XmlRoot.AppendChild($XmlText) | Out-Null

    $XmlTextValue = $XmlDocument.CreateTextNode($MyError)
    $XmlText.AppendChild($XmlTextValue) | Out-Null
}

<# Format XML output #>
$StringWriter = New-Object System.IO.StringWriter 
$XmlWriter = New-Object System.XMl.XmlTextWriter $StringWriter 
$XmlWriter.Formatting = “indented” 
$XmlWriter.Indentation = 1
$XmlWriter.IndentChar = "`t" 
$XmlDocument.WriteContentTo($XmlWriter) 
$XmlWriter.Flush() 
$StringWriter.Flush() 

Return $StringWriter.ToString()

**Comment by cgagnaire** [comment]
Done here https://github.com/centreon/centreon-plugins/tree/master/cloud/microsoft/office365 :)
