### ISSUE TITLE
SAP monitoring

### ISSUE THREAD

**Issue by afriqs** [centreon/centreon-plugins#105]
Hi,

Any chance we can have someday a plugin to monitor [SAP ERP](https://en.wikipedia.org/wiki/SAP_ERP) using CCMS ?

I found some stuff with [nagios](http://sourceforge.net/projects/nagios-sap-ccms/) but not with centreon-engine...

**Comment by afriqs** [comment]
I think [this one](https://exchange.nagios.org/directory/Plugins/Business-Management-and-Logic/SAP/check_sap_health/details) may be easier to integrate for a Perl guru ;)

**Comment by garnier-quentin** [comment]
It's not a priority. You have SAP Hana DB. I'll need more informations about SAP to do it.
