### ISSUE TITLE
database::mssql::mode::transactions on a case sensitive server

### ISSUE THREAD

**Issue by BiGOUDx** [centreon/centreon-plugins#1059]
Hello,

I have a SQL Server 2008 R2 SP3 configured with the collation Latin1_General_BIN.

The mode transactions (plugin database::mssql) is not working : no information is gathered.
After investigation, I found the value requested is "transactions/sec" with a lower T. On servers, the value is with a upper T. As my server is case sensitive, the request doesn't work.
On my other server (same version) with collation French_CI_AS, the request works fine.

To correct it, you can :
- put the letter T in upper case : i don't know the impact on early/later version of SQL Server
- change the request to UPPER the selection 
line 65: $self->{sql}->query(query => q{SELECT cntr_value FROM sys.dm_os_performance_counters WHERE **UPPER(**counter_name**)** = **UPPER(**'transactions/sec'**)** AND instance_name = '_Total'});

The second one works fine with SQL Server 2008R2SP3 and SQL Server 2016SP1.

Matthieu

**Comment by cgagnaire** [comment]
Thanks for the feedback !
