### ISSUE TITLE
database::mssql::mode::blocked-processes  trim is not a recognized built-in function name

### ISSUE THREAD

**Issue by Toyin123** [centreon/centreon-plugins#1062]
## Bug/Question

Hello Everyone.

I get a problem on monitoring Mssqlserver  2008 servers.On Blocked-processes, i get the following error : 
Cannot execute query: Server message number=195 severity=15 state=10 line=1 server=XXXX text='trim' is not a recognized built-in function name.

To Fix it: 

In centreon-plugins/database/mssql/mode/blockedprocesses.pm at line 119

`options{sql}->query(query => q{SELECT spid, blocked, waittime, status, RTrim(program_name) as program, Rtrim(cmd) as cmd FROM master.dbo.sysprocesses});`

I change trim by Rtrim.

Best Regards

**Comment by cgagnaire** [comment]
Thanks for the feedback.
I removed the trim command on the request as we do it after.
And I forgot the where clause to only retreive bocked processes :palmface:
