### ISSUE TITLE
HP network/hp/procurve/snmp/plugin filter option not working

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1065]
Hi,

I am trying to exclude psu 3 from checks, but how ever I write it, it still gives me error:

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network/hp/procurve/snmp/plugin.pm --mode=environment --hostname=1.2.3.4 --snmp-community='xxx' --snmp-version=2c --verbose --filter=psu.3
WARNING: power supply sensor 'power supply.3' state is not present |
Checking sensors
fan sensor 'fan.1' state is good [instance: fan.1].
power supply sensor 'power supply.2' state is good [instance: power supply.2].
power supply sensor 'power supply.3' state is not present [instance: power supply.3].
temperature sensor 'temperature.4' state is good [instance: temperature.4].
Checking power supply
Checking fans

**Comment by cgagnaire** [comment]
Hi @kadrika,
Can you try with option --filter='sensor,power supply.3'

**Comment by kadrika** [comment]
Yes, that worked, thanks!
I totally missed the word sensor after power supply. :(
You can close this case.

**Comment by cgagnaire** [comment]
No worries ;)
