### ISSUE TITLE
Watchguard cpu usage incorrect

### ISSUE THREAD

**Issue by LucFauvel** [centreon/centreon-plugins#1078]
Using the watchguard plugin, we noticed that the CPU usage % was always over 100. After diagnostics, the problem seems to be that watchguard appliances send their CPU usage as whole values. In the watchguard wiki it states that the values are whole and need to be divided for the decimals. Ex: 200 = 2.00% 
[Details](https://www.watchguard.com/help/docs/fireware/12/en-US/Content/en-US/basicadmin/snmp_mibs_details_c.html)

We corrected the issue by dividing the the snmp results by 100. If you wish we can submit a pull request with that change.

**Comment by Sims24** [comment]
Hello, 

Yes please do a dedicated PR referring to this issue. 

Thansk
