### ISSUE TITLE
NRPE file size

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1082]
Hi,

I am trying to test check_centreon_nrpe command and I have run into a problem.
The command works fine from the cli:
/usr/lib/nagios/plugins/check_centreon_nrpe -H 1.2.3.4 -p 5666 -t 30 -u -m 8192 -c check_files -a "paths=C:\Users\mike\Videos" "pattern=test2.rtf" "warning=size>23k" "critical=size>29k" show-all
WARNING: 1/1 files (warning(test2.rtf))|'test2.rtf size'=23.89843KB;23;29

But when I add the same command to GUI I get error that No files found. 
What am I missing?

(the test command is a exact copy from the service: Executed Check Command Line)

**Comment by Sims24** [comment]
Hi @kadrika 

Probably that the backslash get escaped through the web ui. Use / instead of \ or double the \. Engine debug will probably show you the real command engine has executed. 

But not really a plugin issue here, more an encoding and web form things I guess :)
