### ISSUE TITLE
New plugin HP switch

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1083]
Hi, we got brand new switch at work : HPE OfficeConnect Switch1820 48G J9981A
[sw-hp.txt](https://github.com/centreon/centreon-plugins/files/2236133/sw-hp.txt)
Thanks for your work

**Comment by omercier** [comment]
Hi @oasisck this snmpwalk only contains OIDs from standard MIBs, nothing that is specific to HP or any of its entities. Can you perform another snmpwalk -ObentU with the 'enterprise' OID (.1.3.6.1.4.1) please?

**Comment by oasisck** [comment]
Hi @omercier my bad sry
[sw-hpv2.txt](https://github.com/centreon/centreon-plugins/files/2352961/sw-hpv2.txt)

**Comment by VMTS** [comment]
Hi,

Any progress on this plugins ?

Thank you.

**Comment by omercier** [comment]
Hi,
Not yet, sorry. 
By the way thank you @oasisck for your input. I hope we'll find some time soon for this.
Until then, you should be able to monitor all its interfaces with standard Traffic mode from any 'network' plugin.
Regards,
Olivier

**Comment by garnier-quentin** [comment]
I have looked. With the following switch in snmp, we can get interfaces datas only.
Could you tell us if there is a rest api, ssh command line to get other informations (hardware, cpu, memory,...) ?

**Comment by oasisck** [comment]
There aren't RestAPI or SSH. Only HTTP.
I guess there is problem with theirs OIDs.
As u can see on my screenshot from GUI, it mention system OID : .1.3.6.1.4.1.11.2.3.7.11.169
![hpe](https://user-images.githubusercontent.com/30388990/50604163-525e5600-0ebe-11e9-9ee6-fa1546405858.JPG)
No luck on both switches
```
snmpwalk -c public -v 2c 172.21.221.31 .1.3.6.1.4.1.11.2.3.7.11.169
SNMPv2-SMI::enterprises.11.2.3.7.11.169 = No Such Object available on this agent at this OID
```
Only poor system values from this OID
```
snmpwalk -c public -v 2c 172.21.221.31 .1.3.6.1.4.1.11.2
SNMPv2-SMI::enterprises.11.2.36.1.1.2.6.0 = STRING: "PT.02.01"
SNMPv2-SMI::enterprises.11.2.36.1.1.2.8.0 = STRING: "U-Boot 2012.10-00116-g3ab515c (Jul 30 2014 - 10:52:01)"
SNMPv2-SMI::enterprises.11.2.36.1.1.2.9.0 = STRING: "CN7BGMX3CF"
```
I contact HPE. I keep you in touch
Cheers

**Comment by oasisck** [comment]
OK they reply very fast 👍 
So OID isn't accessible by common way. To read more OID, it is necessary to have their property supervision solution : HPE IMC
Maybe there is a way to supervise the switch by this server.
I ll install it when I ll have time and energy. If anyone is faster than me, he could reopen issue.

**Comment by DalfoCentreon** [comment]
By official HP documentation ([link](https://support.hpe.com/hpesc/public/docDisplay?docId=c04622710)) the HP 1820 Switches (J9979A, J9982A, J9980A, J9983A, J9981A, J9984A) supports the following MIBs:

- BRIDGE-MIB (IEEE 802.1Q)
- LLDP-MIB (IEEE 802.3AB)
- EtherLike-MIB
- IF-MIB
- RFC1213-MIB
- RMON-MIB (RMON History as in v1)
- Power Ethernet MIB (RFC3621), only on switches that support PoE+. (No SNMP information is available on configured PoE schedules.) 

So you can use `snmp_standard::mode`.
