### ISSUE TITLE
Plugin dell Powerconnect

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1084]
Hi again, we got Dell iSCSI switches : PowerConnect 5524 and N4032.
The plugin for Dell N4000 is perfect but not compatible for 5524
[dell-5524.txt](https://github.com/centreon/centreon-plugins/files/2236238/dell-5524.txt)
Thanks guys, have a nice week-end (holyday)

Edit : snmpwalk -Obentu .1.3.6.1.4.1 => https://we.tl/t-Vr5osrJJOF (54mb)

**Comment by rk4an** [comment]
Hi,

I don't know if it's the same, but for me network::dell::6200::snmp::plugin is not working for my Dell PowerConnect 5548.

./centreon_plugins.pl --plugin=network::dell::6200::snmp::plugin --hostname=192.168.1.1 --snmp-community=public --mode=global-status
OK: Overall global status is 'ok' [Product: PowerConnect 5548] [Version: 10] [Service Tag: AAAAA]

./centreon_plugins.pl --plugin=network::dell::6200::snmp::plugin --hostname=192.168.1.1 --snmp-community=public --mode=environment
OK: All 0 components are ok []. |

I found an other script with this check: 
my $oid_unitdesc    = ".1.3.6.1.4.1.674.10895.3000.1.2.100.1.0";
my $oid_unitstate   = ".1.3.6.1.4.1.674.10895.3000.1.2.110.1.0";
my $oid_tempstatus      = ".1.3.6.1.4.1.89.53.15.1.9.1";
my $oid_fanname     = ".1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2";
my $oid_fanstate    = ".1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3";
my $oid_psuname     = ".1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2";
my $oid_psustate    = ".1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3";

.1.3.6.1.4.1.674.10895.3000.1.2.100.1.0 = STRING: "PowerConnect 5548"
.1.3.6.1.4.1.674.10895.3000.1.2.110.1.0 = INTEGER: 3
.1.3.6.1.4.1.89.53.15.1.9.1 = INTEGER: 44
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.67109249 = STRING: "fan1_unit1"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.67109250 = STRING: "fan2_unit1"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.134218113 = STRING: "fan1_unit2"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.134218114 = STRING: "fan2_unit2"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.201326977 = STRING: "fan1_unit3"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.201326978 = STRING: "fan2_unit3"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.268435841 = STRING: "fan1_unit4"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2.268435842 = STRING: "fan2_unit4"


.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.67109249 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.67109250 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.134218113 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.134218114 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.201326977 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.201326978 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.268435841 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3.268435842 = INTEGER: 1

.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.67109185 = STRING: "ps1_unit1"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.67109186 = STRING: "ps2_unit1"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.134218049 = STRING: "ps1_unit2"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.134218050 = STRING: "ps2_unit2"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.201326913 = STRING: "ps1_unit3"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.201326914 = STRING: "ps2_unit3"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.268435777 = STRING: "ps1_unit4"
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2.268435778 = STRING: "ps2_unit4"

.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.67109185 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.67109186 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.134218049 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.134218050 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.201326913 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.201326914 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.268435777 = INTEGER: 1
.1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3.268435778 = INTEGER: 1

The MIB: http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?module=Dell-Vendor-MIB&fournisseur=DELL

Thanks,

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk ?

**Comment by rk4an** [comment]
Yes of course, I just send you a email

Thanks,

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md)).

Thank you for your understanding.
