### ISSUE TITLE
Hardware template doesn't allow thresholds for lower than value

### ISSUE THREAD

**Issue by LucFauvel** [centreon/centreon-plugins#1085]
Since using the hardware template, I can no longer use the nagios threshold annotations. Ex: warning if voltage is < 23.5 and critical if < 23. In order to do this we used to set the thresholds like this: 
`--warning=23.5: --critical=23:` 
Using the hadware template we can no longer do so. We tried this:
`--warning='voltage,.*,23.5:' --critical='voltage,.*,23:'` 
 but this does not work.

Assistance on this would be appreciated since I do not want to ruin anything in an already functioning template. 

Thank you.

**Comment by Sims24** [comment]
Hello

Could you provide the command_line and plugin that you are using please ?

**Comment by LucFauvel** [comment]
Upon further testing we have resolved the problem. The issue was with the device itself.
