### ISSUE TITLE
hardware::server::hp::ilo::xmlapi SSL error

### ISSUE THREAD

**Issue by ThomasSo01** [centreon/centreon-plugins#1086]
I have a problem with this module.

My command in Centreon is : 
$CENTREONPLUGINS$/centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname=$HOSTNAME$ --username=$_HOSTILO_USERNAME$ --password=$_HOSTILO_PASSWORD$ --component=fan

If i try in cli, no error, module return Ok, but in centreon, i have : 
UNKNOWN: Failed to establish SSL connection: Invalid argument, ssl_error=IO::Socket::IP configuration failed
I check the module, by default, if no ssl-opt is set, 'SSL_verify_mode => SSL_VERIFY_NONE' is set.

I check other issues with same problem, but solution don't work.

Thank you,

**Comment by Sims24** [comment]
Hi, 

Are you sure you are the poller that check this host is the same as the one you are checking ? 

Did you use centreon-engine user to test through command_line ? That might be a perl dependency issue, how did you install it ? 

Rgds,

**Comment by ThomasSo01** [comment]
Hi,
Yes my centreon is in vm and all service are in.
How can i check in command line with the centreon-engine user ?
Perhaps a dependency issue but how check it ?
I synchronize the git and copy in the directory.
I have install dependency give in the readme on this git.
Thanks you,

**Comment by Sims24** [comment]
```
root-shell> su - centreon-engine
centreon-engine-shelll> execute-your-command-line
```

**Comment by ThomasSo01** [comment]
I try with centreon-engine : command is ok, no ssl error

[root@centreon-central plugins]# su -l centreon-engine
-bash-4.2$ perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname=XX.XX.XX.XX --username=XXXX --password=XXXXX --component=fan
OK: All 8 components are ok [8/8 fans]. | 'fan_Fan 1'=27%;;;0; 'fan_Fan 2'=18%;;;0; 'fan_Fan 3'=23%;;;0; 'fan_Fan 4'=23%;;;0; 'fan_Fan 5'=27%;;;0; 'fan_Fan 6'=27%;;;0; 'fan_Fan 7'=27%;;;0; 'fan_Fan 8'=23%;;;0;

**Comment by Sims24** [comment]
ok, probably you have some special char in your password nope ? like @ or backslash ?

**Comment by ThomasSo01** [comment]
no only lower and upper car and number and username is admin :)

**Comment by ThomasSo01** [comment]
I just try to install IO::Socket::SSL with cpan IO::Socket::SSL after comment perl setting in ./bashrc
I now have a new error : 
UNKNOWN: Failed to establish SSL connection: Invalid argument, ssl_error=IO::Socket::INET6 configuration failed

**Comment by ThomasSo01** [comment]
i have install XML::Simple et LWP::UserAgent with cpan.
Same error
If i force use IO::Socket::SSL 'inet4'; (use ipv4 only) : 
UNKNOWN: Failed to establish SSL connection: Invalid argument, ssl_error=IO::Socket::INET configuration failed

**Comment by ThomasSo01** [comment]
after install IO::Socket::IP now it's : 
UNKNOWN: Failed to establish SSL connection: Invalid argument, ssl_error=IO::Socket::IP configuration failed
Centreon make me crazzy

**Comment by Sims24** [comment]
are you using a rpm based distribution ?

**Comment by ThomasSo01** [comment]
cpan seems to compile each time in automode

**Comment by Sims24** [comment]
cpan is clearly not user friendly and might get you in serious trouble :(. 

Yyou should rather use your official distribution packet manager I guess

**Comment by ThomasSo01** [comment]
I make a clean install of centreon using iso, update using yum, install dependencies for centreon-plugins using yum.
I restore my centreon backup ( database and config file).
Install perl-XML-Simple using yum.
and : 
UNKNOWN: Failed to establish SSL connection: Invalid argument, ssl_error=IO::Socket::IP configuration failed

**Comment by ThomasSo01** [comment]
I test with iol2, ilo3 and ilo4, same problem
Thx

**Comment by ThomasSo01** [comment]
up, any ideas ?

**Comment by ThomasSo01** [comment]
I have another issue with another plugins.
For Oracle, i must specify oracle_home in the queries. If i try in shell, no problem but Centreon don't find the driver.
My command is: 
/usr/bin/env ORACLE_HOME=/usr/lib/oracle/12.1/client64/lib LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib $CENTREONPLUGINS$/centreon_plugins.pl --plugin=database::oracle::plugin --hostname=$HOSTADDRESS$ --sid $_HOSTSID_ORACLE$ --port $_HOSTPORT_ORACLE$ --username=$_HOSTUTILISATEUR$ --password=$_HOSTMOT_DE_PASSE$ --mode=$_SERVICEMODE$
and it's work

**Comment by Sims24** [comment]
Please open a separate issue to discuss about Oracle.

**Comment by Sims24** [comment]
Regarding ilo it's strange as we do not face this problem on our side ... See https://github.com/centreon/centreon-plugins/issues/1087 maybe @ArnoMLT can help here

**Comment by ThomasSo01** [comment]
$_HOSTILO_USERNAME$ is admin
$_HOSTILO_PASSWORD$ is tj4rlh90a1
$HOSTNAME$ is the ILO IP
My command works in cli with root login or centreon login but not in centreon.
I don't understand how nagios launch command, because it's perhaps a dependency error like Oracle who need to be overloaded.
Thx, i really appreciate your help.
