### ISSUE TITLE
No more perfdata on module network::cisco::asa::plugin mode CPU

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#109]
Hello,

since some upgraded (can't say which one sadly), I don't have any perfdata for CPU information on my ASA firewalls.

./centreon_plugins.pl --plugin=network::cisco::asa::plugin --mode=cpu --hostname=192.168.1.1  --snmp-version=3 --snmp-username=username --authpassphrase=password--authprotocol=SHA --privpassphrase=password --privprotocol=AES -w 30 -c 50 --subsetleef=15 --verbose
OK: All CPUs are ok. |
CPU '2': not defined (5sec), not defined (1min), not defined (5min)
CPU '3': not defined (5sec), not defined (1min), not defined (5min)
CPU '1': not defined (5sec), not defined (1min), not defined (5min)

Any idea on what is wrong ?

Best regards

**Comment by garnier-quentin** [comment]
Could you give a walk of following OIDs please:
.1.3.6.1.4.1.9.9.109.1.1.1.1
.1.3.6.1.4.1.9.2.1

Thanks

**Comment by hdep** [comment]
.1.3.6.1.4.1.9.2.1 
.1.3.6.1.4.1.9.2.1 = No Such Object available on this agent at this OID


 .1.3.6.1.4.1.9.9.109.1.1.1.1
.1.3.6.1.4.1.9.9.109.1.1.1.1.2.1 = INTEGER: 1
.1.3.6.1.4.1.9.9.109.1.1.1.1.2.2 = INTEGER: 1
.1.3.6.1.4.1.9.9.109.1.1.1.1.2.3 = INTEGER: 1
.1.3.6.1.4.1.9.9.109.1.1.1.1.3.1 = Gauge32: 22
.1.3.6.1.4.1.9.9.109.1.1.1.1.3.2 = Gauge32: 22
.1.3.6.1.4.1.9.9.109.1.1.1.1.3.3 = Gauge32: 22
.1.3.6.1.4.1.9.9.109.1.1.1.1.4.1 = Gauge32: 12
.1.3.6.1.4.1.9.9.109.1.1.1.1.4.2 = Gauge32: 12
.1.3.6.1.4.1.9.9.109.1.1.1.1.4.3 = Gauge32: 12
.1.3.6.1.4.1.9.9.109.1.1.1.1.5.1 = Gauge32: 11
.1.3.6.1.4.1.9.9.109.1.1.1.1.5.2 = Gauge32: 11
.1.3.6.1.4.1.9.9.109.1.1.1.1.5.3 = Gauge32: 11
.1.3.6.1.4.1.9.9.109.1.1.1.1.9.1 = Gauge32: 5
.1.3.6.1.4.1.9.9.109.1.1.1.1.9.2 = Gauge32: 5
.1.3.6.1.4.1.9.9.109.1.1.1.1.9.3 = Gauge32: 5
.1.3.6.1.4.1.9.9.109.1.1.1.1.10.1 = Gauge32: 22
.1.3.6.1.4.1.9.9.109.1.1.1.1.10.2 = Gauge32: 22
.1.3.6.1.4.1.9.9.109.1.1.1.1.10.3 = Gauge32: 22
.1.3.6.1.4.1.9.9.109.1.1.1.1.11.1 = Gauge32: 0
.1.3.6.1.4.1.9.9.109.1.1.1.1.11.2 = Gauge32: 0
.1.3.6.1.4.1.9.9.109.1.1.1.1.11.3 = Gauge32: 0

**Comment by garnier-quentin** [comment]
Thanks. Could you test with the last version ? Should work i think.
