### ISSUE TITLE
Mode to monitor BGP Prefixes

### ISSUE THREAD

**Issue by poppsy** [centreon/centreon-plugins#1095]
Hello
I want to supervise the number of BGP prefixes learned by a PEER and of course make a graph.
I would need help to develop a plugin mode, using this OID: BgpPeerAcceptedPrefixes = "1.3.6.1.4.1.9.9.187.1.2.4.1.1"

I can not translate my needs for lack of development skills could someone help me?

I want to duplicate the bgppeerstate mode of the APP :: PROTOCOLS :: BGP :: 4 :: PLUGIN plugin and add a bgppeerprefix mode or instead of having the last update, I would have the number of prefixes.

Thank's

**Comment by Sims24** [comment]
Hi @poppsy 

We have to separate it from the BGP mode because this is a Cisco extension  (https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/15-s/irg-15-s-book/irg-mibv2.pdf) and not from the RFC protocol standard. 

If you could mail us a snmpwalk of the SNMP table that would be great.

Thanks

**Comment by poppsy** [comment]
when you do a snmpwalk you have this output

`SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP>.1.1 = Counter32: 4`
`SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP>.1.1 = Counter32: 5`
`SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP>.1.1 = Counter32: 4`
`SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP>.1.1 = Counter32: 19`

**Comment by poppsy** [comment]
I have find the structure on this [website ](http://www.mibdepot.com/cgi-bin/getmib3.cgi?win=mib_a&i=1&n=CISCO-BGP4-MIB&r=cisco&f=CISCO-BGP4-MIB.my&v=v2&t=tree),  i think is this do you want ? 

>cbgpPeerAddrFamilyPrefixTable 1.3.6.1.4.1.9.9.187.1.2.4
-->cbgpPeerAddrFamilyPrefixEntry 1.3.6.1.4.1.9.9.187.1.2.4.1
--->cbgpPeerAcceptedPrefixes	 Counter32 1.3.6.1.4.1.9.9.187.1.2.4.1.1
--->cbgpPeerDeniedPrefixes	 Gauge32	1.3.6.1.4.1.9.9.187.1.2.4.1.2
--->cbgpPeerPrefixAdminLimit	Unsigned32 ( 1..4294967295 ) 1.3.6.1.4.1.9.9.187.1.2.4.1.3
--->cbgpPeerPrefixThreshold	Unsigned32 ( 1..100 ) 1.3.6.1.4.1.9.9.187.1.2.4.1.4
--->cbgpPeerPrefixClearThreshold	 Unsigned32 ( 1..100 ) 1.3.6.1.4.1.9.9.187.1.2.4.1.5
--->cbgpPeerAdvertisedPrefixes  Gauge32	1.3.6.1.4.1.9.9.187.1.2.4.1.6
--->cbgpPeerSuppressedPrefixes  Gauge32	1.3.6.1.4.1.9.9.187.1.2.4.1.7
--->cbgpPeerWithdrawnPrefixes  Gauge32	1.3.6.1.4.1.9.9.187.1.2.4.1.8

**Comment by Sims24** [comment]
Yes please, a complete walk of 1.3.6.1.4.1.9.9.187.1.2.4 

As it probably contains some sensitive information, feel free to send it to sbomm@centreon.com and cgagnaire@centreon.com

thanks

**Comment by poppsy** [comment]
When i do a walk  on 1.3.6.1.4.1.9.9.187.1.2.4, i have this output

`SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP_1>.1.1= Counter32: 4` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP_2>.1.1 = Counter32: 5` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP_3>.1.1 = Counter32: 4` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.<peer@IP_4>.1.1 = Counter32: 19` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.3.<peer@IP_1>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.3.<peer@IP_2>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.3.<peer@IP_3>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.3.<peer@IP_4>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.4.<peer@IP_1>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.4.<peer@IP_2>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.4.<peer@IP_3>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.4.<peer@IP_4>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.5.<peer@IP_1>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.5.<peer@IP_2>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.5.<peer@IP_3>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.5.<peer@IP_4>.1.1 = Gauge32: 0` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.6.<peer@IP_1>.1.1 = Gauge32: 2` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.6.<peer@IP_2>.1.1 = Gauge32: 2` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.6.<peer@IP_3>.1.1 = Gauge32: 2` 
` SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.6.<peer@IP_4>.1.1 = Gauge32: 3`

**Comment by Sims24** [comment]
Great thx, is any other OID seems relevant from the ones you listed previously ?

**Comment by poppsy** [comment]
The most important for me is cbgpPeerAcceptedPrefixes, if it is possible to add cbgpPeerAcceptedPrefixes in the same graph and output.

It would be great

**Comment by Sims24** [comment]
What's the difference between cbgpPeerAcceptedPrefixes and cbgpPeerAcceptedPrefixes =)

**Comment by poppsy** [comment]
oups 
I wanted to say cbgpPeerDeniedPrefixes 
sorry

**Comment by Sims24** [comment]
don't worry this is not, just need to find some time to do it ;)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3841
