### ISSUE TITLE
[network-cisco-snmp] new mode configuration status

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1102]
It would by great if you can add a new mode to check on cisco switches if running configuration is saved on startup configuration. This information can be read through SNMP (you can find this functionality on check_nwc_health for example).

**Comment by Sims24** [comment]
sure, imagine that is standard to all cisco devices ? could you give us the oid and expected value please ?

**Comment by joschi99** [comment]
Cisco Switches (not Cisco SMB) returns via SNMP the following values as timeticks:
* RunningLastChanged => '1.3.6.1.4.1.9.9.43.1.1.1.0'
* RunningLastSaved => '1.3.6.1.4.1.9.9.43.1.1.2.0'
* StartupLastChanged => '1.3.6.1.4.1.9.9.43.1.1.3.0'
You can calucate the difference between Startup and Running config. If Running config is newer then Startup config then we can get an alarm. It would be nice to indicate with a parameter how many time (seconds or minutes) running config can be ahead startup config without alarm.

**Comment by rk4an** [comment]
Great idea! I test it on:

- Catalyst 2960S 12.2(55)SE5
- Catalyst 2960G 12.2(55)SE11
- Catalyst 3750 12.2(50)SE3
- Catalyst 9300 16.6.3

Last Running Changed:   321137265
Last Running Saved:        321137496
Last Startup Changed:     321137496

Description here: http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?module=CISCO-CONFIG-MAN-MIB

**Comment by rk4an** [comment]
#1217
