### ISSUE TITLE
Plugin: Barracuda CloudGen Firewall

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1103]
Hello guys,

I'm not really good in coding so I will give it a shot in this community. We are starting to implement the Barracuda CloudGen Firewalls at our customers and want to monitor the appliances.
Is it possible that these firewalls will be added to the centreon plugins repository? I can give you everything you need.
Meanwhile we are checking specific OIDs through SNMP directly.

I think about something like:

- CPU
- Memory
- Hardware (Fan, Temp, etc.)
- VPN
- Interface Status
.
.
.

If there is more to get, It would be nice.

Thank you very much.
Best regards, Michael

**Comment by Sims24** [comment]
Hi @MikeW83 

Sure we can and even we would be glad to help you achieving this. Please email me sbomm@centreon.com and we'll talk about required informations to add this to our repository. 

Thanks

**Comment by Sims24** [comment]
Done here https://github.com/centreon/centreon-plugins/pull/1109
