### ISSUE TITLE
plugin network::cisco::standard::snmp::plugin mode interfaces 

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#111]
Hello,

since the upgrade to the lastest version of the plugin I have a different behaviour on interface monitoring : 
Old command was : 

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=traffic --hostname=192.168.1.1  --snmp-version=3 --snmp-username=user --authpassphrase=password --authprotocol=MD5 --privpassphrase=password --privprotocol=DES --name --interface=eth3  --verbose
OK: Interface 'eth3' Traffic In : 15.26Kb/s (0.00 %), Out : 4.97Kb/s (0.00 %)  | 'traffic_in'=15255.99b/s;;;0;1000000000 'traffic_out'=4972.41b/s;;;0;1000000000
Interface 'eth3' Traffic In : 15.26Kb/s (0.00 %), Out : 4.97Kb/s (0.00 %)

New plugin output :+1: 

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=192.168.1.1 --snmp-version=3 --snmp-username=user --authpassphrase=password --authprotocol=MD5 --privpassphrase=password --privprotocol=DES --name --interface=eth3  --verbose --nagvis-perfdata --add-traffic

OK: All interfaces are ok | 'in_eth3.300'=1550.69;;;0;125000000 'out_eth3.300'=613.84;;;0;125000000 'in_eth3'=1884.03;;;0;125000000 'out_eth3'=613.84;;;0;125000000
Interface 'eth3.300' Traffic In : 12.41Kb/s (0.00%), Traffic Out : 4.91Kb/s (0.00%)
Interface 'eth3' Traffic In : 15.07Kb/s (0.00%), Traffic Out : 4.91Kb/s (0.00%)

New plugin is reporting trafic for eth3 and eth3.300, but I specified proper name on --interface 
So is this expected behaviour from the plugin ?  If yes how can I only monitor eth3 interface without eth3.300 ? I already have a service for eth3.300 

Regards,

**Comment by garnier-quentin** [comment]
Yes exactly. You have to do like that (a regexp):
./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=192.168.1.1 --snmp-version=3 --snmp-username=user --authpassphrase=password --authprotocol=MD5 --privpassphrase=password --privprotocol=DES --name --interface='^eth3$' --verbose --nagvis-perfdata --add-traffic

**Comment by hdep** [comment]
It works ! 
thank you.
