### ISSUE TITLE
[cpu (counter related ?)] duplicate output (cosmetic)

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1110]
Hi,

This is a rather cosmetic report.

I don't know whether it is related to the new CPU plugin (#1107) or to the `counter` template itself.
But :

![cos](https://user-images.githubusercontent.com/40244829/44555525-d9900600-a735-11e8-8ff3-19d5772229c9.png)

Any way to remove the core info which is added when there is only one core (2 examples above) ?
This additional output is as a result let's say exactly the same as the average before.

Thank you very much 👍

**Comment by cgagnaire** [comment]
Hi @CPbN,
Its indeed linked to the counter template.
We'll let it like it is.
