### ISSUE TITLE
UNKNOWN: SNMP GET Request : Cant get a single value.

### ISSUE THREAD

**Issue by Nalkhael** [centreon/centreon-plugins#1111]
Hello,

I have an issue to monitor a Virtual Center Server Appliance (VMware) with centreon_linux_snmp.pl

When i check the CPU :
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=myip --snmp-version='2c' --snmp-community='public'  --warning='80'  --critical='90'
I got : OK: 4 CPU(s) average usage is: 6.25% | 'cpu0'=8.00%;;;0;100 'cpu1'=5.00%;;;0;100 'cpu2'=8.00%;;;0;100 'cpu3'=4.00%;;;0;100 'total_cpu_avg'=6.25%;0:80;0:90;0;100

But when i want to check memory, load or swap : 
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=myip --snmp-version='2c' --snmp-community='public' --warning='4,3,2' --critical='6,5,4'
I got : UNKNOWN: SNMP GET Request : Cant get a single value.

When i try --debug or --verbose, i don't have any other informations :(

I'm using the host service template "OS-Linux-SNMP-custom" with Centreon 2.8.25 and centreon-plugins last version.

I know that the VCSA is not a standard Linux, but i cannot manage to find how reduce the data output for being interpretable by the plugin.

I hope i miss nothing, thanks in advance :)

Nal

**Comment by Sims24** [comment]
Hi @Nalkhael ,

Can't get a single value means that the plugin didn't find the OID needed to display the result.

Guess that is a too strict SNMP configuration in your case. Please check https://kb.vmware.com/s/article/2145018 and be sure you can reach all oids from the HOST-RESOURCE MIB

**Comment by Nalkhael** [comment]
I understand, the plugin want to check the OID '1.3.6.1.4.1.2021.4.6.0' for the free memory and it don't get any result when i do a snmpwalk on the VCSA.

I have found the OID '.1.3.6.1.2.1.25.2.3.1.6.18' to check the memory usage, can I specify the OID in parameter to the plugin ?

I have check the VMware KB but i cannot find any strict configuration.

Nal

**Comment by Sims24** [comment]
Sounds strange ... could you provide a full snmpwalk starting from 1.3.6.1.2.1.25.2.3.1.6 ?

**Comment by Nalkhael** [comment]
I have this output :

snmpwalk -v 2c -c public myhost 1.3.6.1.2.1.25.2.3.1.6
HOST-RESOURCES-MIB::hrStorageUsed.1 = INTEGER: 0
HOST-RESOURCES-MIB::hrStorageUsed.2 = INTEGER: 6
HOST-RESOURCES-MIB::hrStorageUsed.3 = INTEGER: 170
HOST-RESOURCES-MIB::hrStorageUsed.4 = INTEGER: 0
HOST-RESOURCES-MIB::hrStorageUsed.5 = INTEGER: 1351413
HOST-RESOURCES-MIB::hrStorageUsed.6 = INTEGER: 351
HOST-RESOURCES-MIB::hrStorageUsed.7 = INTEGER: 326
HOST-RESOURCES-MIB::hrStorageUsed.8 = INTEGER: 5793
HOST-RESOURCES-MIB::hrStorageUsed.9 = INTEGER: 803517
HOST-RESOURCES-MIB::hrStorageUsed.10 = INTEGER: 335803
HOST-RESOURCES-MIB::hrStorageUsed.11 = INTEGER: 27948
HOST-RESOURCES-MIB::hrStorageUsed.12 = INTEGER: 544177
HOST-RESOURCES-MIB::hrStorageUsed.13 = INTEGER: 13301
HOST-RESOURCES-MIB::hrStorageUsed.14 = INTEGER: 350850
HOST-RESOURCES-MIB::hrStorageUsed.15 = INTEGER: 8281
HOST-RESOURCES-MIB::hrStorageUsed.16 = INTEGER: 136763
HOST-RESOURCES-MIB::hrStorageUsed.17 = INTEGER: 0
HOST-RESOURCES-MIB::hrStorageUsed.18 = INTEGER: 16225996

**Comment by Sims24** [comment]
Please test the storage mode, you can filter by storage-type and probably make different check for flash / hdd storage, 

Look at https://github.com/centreon/centreon-plugins/blob/09ef4626053e4c14966a02de9ef02cf963eec73b/snmp_standard/mode/storage.pm#L38 you'll see all filter you can use.

**Comment by Nalkhael** [comment]
Nice ! I have a result with 'hrStorageRam' !
Sadly, nothing with 'hrStorageVirtualMemory' or any other type : (UNKNOWN: No storage found. Can be: filters, cache file.)

But i think this is the memory, how can i monitor the swap and the load ?

**Comment by Sims24** [comment]
Could you provide a full snmpwalk resulting from the following command please : 

- snmpwalk -Cc -v2c -c public -ObentU __IP_VCSA__ .1 > vcsa.snmpwalk

**Comment by Nalkhael** [comment]
Sorry, I had to removed some informations (IP/Name/etc.), tel me if something is missing.

[vcsa.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/2331366/vcsa.snmpwalk.txt)

**Comment by Sims24** [comment]
I'll check it asap

**Comment by romsworld** [comment]
Hi,

I have the same problem. VCSA is not an ordinary ditribution.
Perhaps, check need to be done by api ?

**Comment by romsworld** [comment]
Hi,
Any news ?

Thanks

**Comment by romsworld** [comment]
Both, I will just search a solution to check VSCA.

**Comment by Nalkhael** [comment]
The plugin can only check a VM memory state, and I want the guest memory state.
And I'm not very good at coding, but I have found this : https://www.virtuallyghetto.com/2017/01/exploring-new-vcsa-vami-api-wpowercli-part-1.html
Maybe with a probe in PowerShell ...

**Comment by romsworld** [comment]
Nalkhael, i understand, but what is the position about Centreon. Perhaps, some customers would like to check VSCA.

**Comment by Nalkhael** [comment]
I don't know, I'm not a Centreon employee :)

**Comment by romsworld** [comment]
Hi Sims24,

Any news for us ?

Thanks,

**Comment by romsworld** [comment]
J'ai trouvé ca... https://github.com/vranystepan/nagios-go-vcsa-health

**Comment by Sims24** [comment]
Seems good. We will try to developp something similar I guess. API will be better than SNMP.

I'll ping you in another ticket as this one is not relevant anymore.

**Comment by romsworld** [comment]
Thanks,
Other website : https://paulgrevink.wordpress.com/2016/08/22/check_mk-and-vsphere-vcenter-server/
