### ISSUE TITLE
[os::linux::snmp] Check inodes with disk-usage

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1115]
Hi,

Using `os::linux::snmp::plugin`, with mode `memory`, we can also check swap at the same time thanks to the `--swap option`, even if there is a "standalone" `swap` mode.

Would be nice to have the same thing for `disk-usage`, to be able to check for inodes at the same time, adding a `--inodes` option.

Thank you very much 👍

**Comment by Sims24** [comment]
Main change, we will try to think about it

**Comment by CPbN** [comment]
What do you mean by "main change" @Sims24 ?
You mean a rather important modification needed to achieve this ?

**Comment by Sims24** [comment]
Yes, that what I meant :)

**Comment by CPbN** [comment]
OK :)

After having a quick look, we are in the same OID substree, so should help by a little.

```
my $oid_dskPath = '.1.3.6.1.4.1.2021.9.1.2';
my $oid_dskTotalLow = '.1.3.6.1.4.1.2021.9.1.11'; # in kB
my $oid_dskTotalHigh = '.1.3.6.1.4.1.2021.9.1.12'; # in kB
my $oid_dskUsedLow = '.1.3.6.1.4.1.2021.9.1.15'; # in kB
my $oid_dskUsedHigh = '.1.3.6.1.4.1.2021.9.1.16'; # in kB

dskPercentNode => { oid => '.1.3.6.1.4.1.2021.9.1.10' },
```

**Comment by garnier-quentin** [comment]
It could be. We ll add it.

**Comment by CPbN** [comment]
Many thanks @garnier-quentin 👍
