### ISSUE TITLE
[snmp_standard::plugin] Does not exist anymore ?

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1116]
Hi,

I was trying to follow [this guideline](https://documentation.centreon.com/docs/centreon-plugins/en/latest/user/guide.html#how-can-i-check-a-generic-snmp-oid-value) :

**How can i check a generic SNMP OID value ?**
There is a generic SNMP plugin to check it. An example to get ‘SysUptime’ SNMP OID:
`$ perl centreon_plugins.pl --plugin=snmp_standard::plugin --mode=numeric-value ...`

But `snmp_standard/plugin.pm` does not exist anymore, removed with `20171208`.
Any reason why ?

I was planning to configure my `snmpd.conf` files with some `extend` /  `extend-sh` extension commands.
Which then feeds `NET-SNMP-EXTEND-MIB`.
And to poll then using above trick.
To check for system updates, NTP synchronization... well various system tasks.
Is this method perhaps discouraged, and why ?

Thank you very much 👍

**Comment by Sims24** [comment]
Hi, 

Not fan of using NET SNMP EXTEND MIB, but to be honnest didn't use it so much .. 

I guess that your first tought about it should be to study security and performances impacts of using such feature.

Regards,

**Comment by CPbN** [comment]
Thank you @Sims24 for your feedback.
Yes I do not expect so much performance, but that would be for a few hourly / daily calls.
I'll then try and find out.
Thank you :+1:

**Comment by Sims24** [comment]
Cool, feel free to share your experience here afterwards

**Comment by CPbN** [comment]
Here is a working example to check for Debian system updates.
Daily schedule the following (using cron for example) :
```
{ chmod 644 /var/log/sysupd.log ; apt-get update && apt-get -s upgrade ; } >/var/log/sysupd.log 2>&1
```

Add the following to `/etc/snmp/snmpd.conf` :
```
extend-sh sysupd grep -E "[0-9]+ upgraded, [0-9]+ newly installed, [0-9]+ to remove and [0-9]+ not upgraded." "$(find /var/log/sysupd.log ! -mtime 1)" 2>/dev/null || echo "Expected test pattern not found."
```

And use the following Centreon Plugins command :
```
apps-protocols-snmp.pl --mode=string-value --oid=1.3.6.1.4.1.8072.1.3.2.3.1.1.6.115.121.115.117.112.100 --warning-regexp='^(?!(0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.)$)' --format-ok=%{details_ok} --format-warning=%{details_warning}
```

Rather simple to deploy, and no security concern 👍
