### ISSUE TITLE
[database::mssql::mode::failedjobs] Thresholds works strictly upper/lower

### ISSUE THREAD

**Issue by jaltmeyer** [centreon/centreon-plugins#1118]
Hello,

Warning and critical thresholds for this mode on this plugin works strictly upper/lower, while in other modes/plugins, the thresholds work superior or equal / inferior or equal.

So, to trigger the alert, threshold must be exceeded, not just reached like in other plugins.

Thanks.

**Comment by Sims24** [comment]
Hi @jaltmeyer 

Could you provide cli example on this please ?

**Comment by jaltmeyer** [comment]
Hi @Sims24 
Look at this : 

/usr/lib/centreon/plugins/centreon_mssql.pl --plugin database::mssql::plugin --hostname ip.ad.dr.es.s --port 1433 --username 'XXXX\xxxx' --password 'V3rYs3cR3T'  --mode='failed-jobs' **--warning='1'** --critical='5' --warning-duration='' --critical-duration='' --lookback='1440' --skip --verbose

OK: All jobs are ok. | 'failed_jobs'=1;;;0;5

Job 'Integrity Checks Job for DB Maintenance Plan '...'' status success [Runtime : 20180910 204502] [Duration : 130 minutes]
Job 'DB Backup Job for DB Maintenance Plan '...'' status success [Runtime : 20180910 205000] [Duration : 25 minutes]
Job 'DB Backup Job for DB Maintenance Plan '...'' status failed [Runtime : 20180910 212500] [Duration : 112 minutes]
Job 'Optimizations Job for DB Maintenance Plan '...'' status success [Runtime : 20180910 210000] [Duration : 11237 minutes]
Job 'Integrity Checks Job for DB Maintenance Plan '...'' status success [Runtime : 20180910 211500] [Duration : 10009 minutes]

In the plugin, the warning threshold is at 1, but here the third job have a failed status, but the plugin return OK.

Another thing, perfdatas seems not OK : threshold are not here, only min-max.

Thanks for your time.
Regards.

**Comment by garnier-quentin** [comment]
I don t see the problem. For all modes, it s always strictly:
https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
