### ISSUE TITLE
Disk space threshold issue

### ISSUE THREAD

**Issue by Thibaut-ids** [centreon/centreon-plugins#1119]
Hi,
First of all sorry for my english level.
I use the storage plugin of linux, configure by default on Centreon.
The thresholds used are 80% for the warning and 95% for the critical.
However, as can be seen below, the threshold set for the critical alert exceeds the size of the disk.
The disk can be full without us being warned.

![status detaille](https://user-images.githubusercontent.com/23074308/44988164-093adb80-af8a-11e8-8bdf-89dba486494a.PNG)
![graphique](https://user-images.githubusercontent.com/23074308/44988168-0b9d3580-af8a-11e8-85e3-9a7b7fbc95ad.png)

**Comment by Sims24** [comment]
Hi @Thibaut-ids, 

Guess that's something you do not get correctly here. used(b) is the curve of the used space, not the total size of the disk. 

Recommend you to add --explode-perfdata-max='used,size' to your comman_line, then on your graph you'll see a curve up to the warning and critical one representing the siez of your disk. 

Give a try and tell me if it's OK for you, 
Thanks !

**Comment by Thibaut-ids** [comment]
Hi @Sims24,

First of all thank you for your help.

However the solution that you propose to me does not answer to my problem. Here is the curve that I get after adding the option that you advised me.

![courbeapresaide](https://user-images.githubusercontent.com/23074308/45043266-006f0600-b06d-11e8-8957-f406ced26ed9.PNG)

I misspoke. The curve and its values are not my real problem, it just serves me to explain it.
My problem is that I set a critical alert threshold when I reach 95% disk space usage. Disk space in this case is 1.91GB so the alert should be at 1.81GB, or here it is at 1.94GB. So even if you spend 1.81GB the alert will not be triggered.
I have the impression that the percentages are not correctly calculated.

Thank you in advance.
Thibaut

**Comment by Thibaut-ids** [comment]
Hi,

Do you have any idea where the problem may come from? Sorry for the raise but I can not find if I made a mistake.

Regards,
Thibaut

**Comment by Sims24** [comment]
Sorry, we do not have so much time to check this. But threshold and percent calculation are common to all plugins, a bug in this is simply not possible. 

May you check you're root space reservation and --space-reservation option but values are OK without any doubt.

**Comment by garnier-quentin** [comment]
Do you still have the issue ?

**Comment by garnier-quentin** [comment]
You can re-open it if you still have the issue.
