### ISSUE TITLE
[plugin] Cisco interfaces traffic

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon-plugins#112]
Hi,

With the most recent version, traffic plugin has many anomaly.

1- With "--interface=port-channel1 --name" parameter, traffic from all interfaces starting with "port-channel1" is displayed.
2- With parameter --oid-filter, we have this error : UNKNOWN: Method 'get_multiple_table': Wrong OID ''.
3- With all check, perl error is displayed :
Use of uninitialized value in pattern match (m//) at /usr/local/plugins/libexec/centreon/plugins/snmp.pm line 310.
Use of uninitialized value in concatenation (.) or string at /usr/local/plugins/libexec/centreon/plugins/snmp.pm line 315.

Thanks.

**Comment by garnier-quentin** [comment]
Hi,

Thanks for using. My response:
- 1: It's a regexp now. So you have to used like that: --interface='^port-channel1$' --name
- 2: what have you used in parameter --oid-filter ? --oid-filter=ifalias ?
- 3: the third error comes from the 2 i think.

**Comment by garnier-quentin** [comment]
Could you give me your command line please ?

**Comment by tcheval** [comment]
Hi,

Thanks for the kick reply.

With the regex it's ok for interface, but whit errors :

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=<name> --snmp-version=2 --snmp-community=<com> --add-traffic --interface='^port-channel1$' --name --warning-in-traffic=50 --warning-out-traffic=50 --critical-in-traffic=70 --critical-out-traffic=70 --speed=20000
Use of uninitialized value in numeric eq (==) at /usr/local/plugins/libexec/snmp_standard/mode/interfaces.pm line 862.
Use of uninitialized value in numeric eq (==) at /usr/local/plugins/libexec/snmp_standard/mode/interfaces.pm line 867.
Use of uninitialized value in numeric eq (==) at /usr/local/plugins/libexec/snmp_standard/mode/interfaces.pm line 950.
WARNING: Inteface 'port-channel1' Traffic In : 229.36Mb/s (1.15%) | 'traffic_in_port-channel1'=229358800.00b/s;0:200000000;0:1400000000;0;20000000000 'traffic_out_port-channel1'=18465424.00b/s;0:200000000;0:1400000000;0;20000000000

For the filter :+1: 

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=<name> --snmp-version=2 --snmp-community=<com> --add-traffic --interface='^port-channel1$' --name --warning-in-traffic=50 --warning-out-traffic=50 --critical-in-traffic=70 --critical-out-traffic=70 --speed=20000 --oid-filter=ifAlias
Use of uninitialized value in pattern match (m//) at /usr/local/plugins/libexec/centreon/plugins/snmp.pm line 310.
Use of uninitialized value in concatenation (.) or string at /usr/local/plugins/libexec/centreon/plugins/snmp.pm line 315.
UNKNOWN: Method 'get_multiple_table': Wrong OID ''. 

Thanks.

**Comment by garnier-quentin** [comment]
Thanks for your feeback. I think it should be for the 2 bugs.

**Comment by kadrika** [comment]
I get the same kind of error when using oid-filter , but with Juniper srx plugin.

**Comment by garnier-quentin** [comment]
kadrika. Test with the last version. it should be ok now.

**Comment by tcheval** [comment]
Thanks for the fix.
But I'm sorry, I  have another error now :
I have cleared the cache, but still the same error

/usr/local/plugins/libexec/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=<name> --snmp-version=2 --snmp-community=<com> --add-traffic --interface='^port-channel1$' --name --warning-in-traffic=50 --warning-out-traffic=50 --critical-in-traffic=70 --critical-out-traffic=70 --warning-in-error=4 --warning-out-error=4 --critical-in-error=5 --speed=20000 --oid-filter=ifAlias 
UNKNOWN: No entry found (maybe you should reload cache file)

/usr/local/plugins/libexec/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=<name> --snmp-version=2 --snmp-community=<com> --add-traffic --interface='^'port-channel1'$' --name --warning-in-traffic=50 --warning-out-traffic=50 --critical-in-traffic=70 --critical-out-traffic=70 --warning-in-error=4 --warning-out-error=4 --critical-in-error=5 --speed=20000
OK: All interfaces are ok | 'traffic_in_port-channel1'=50928035.48b/s;0:10000000000;0:14000000000;0;20000000000 'traffic_out_port-channel1'=7436329.46b/s;0:10000000000;0:14000000000;0;20000000000

**Comment by garnier-quentin** [comment]
The error is ok. I think there is no matching in ifalias for '^port-channel1$' ;)

**Comment by tcheval** [comment]
With the regex syntax ?

I just checked with a snmpwalk

snmpwalk -c <com> -v 2c <name> ifname | grep port-channel1
IF-MIB::ifName.369098752 = STRING: port-channel1

snmpwalk -c njh_iafl -v 2c altagr2 IF-MIB::ifAlias.369098752
IF-MIB::ifAlias.369098752 = STRING: altagr1

it's ok. And in the cache file entry is présent :

'ifname_369098752' => 'port-channel1',
'ifalias_369098752' => 'altagr1',

I make an error somewhere?
Anyway thank you for the support :)

**Comment by garnier-quentin** [comment]
--oid-filter is used to check for the filter (with --interface option). And you have --oid-display. Maybe you want to use --oid-display=ifalias

**Comment by tcheval** [comment]
Oh, I'm sorry. I'm bad ...

It's work. :)

**Comment by kadrika** [comment]
One more thing, when I check it from command line it also works, but in Frontend even if I am checking only one interface I still get output to be: 	OK: All interfaces are ok
My command is like this: ./centreon_plugins.pl --plugin=network::juniper::srx::plugin --snmp-community=xxx --snmp-version=2c --hostname=1.2.3.4 --mode=interfaces --interface='^fe-0/0/4$' --name --add-traffic --oid-display=ifAlias

I get this returned:
OK: Interface 'Local internet, ## ISP ##, ##Circuit ID##' Traffic In : 10.74Kb/s (0.01%), Traffic Out : 10.36Kb/s (0.01%) | 'traffic_in'=10736.00b/s;;;0;100000000 'traffic_out'=10360.00b/s;;;0;100000000

From time to time I get IN and OUT returned as skipped - does it mean that there is no traffic or what?
Like this: OK: Interface 'Local internet, ## ISP ##, ##Circuit ID##' Traffic In : skipped, Traffic Out : skipped

And in Frontend I am using command:
$USER1$/centreon_plugins.pl --plugin=network::juniper::srx::plugin --hostname=$HOSTADDRESS$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --mode=interfaces --interface='^$ARG1$' --name --add-traffic --oid-display=ifAlias

**Comment by garnier-quentin** [comment]
"skipped" means: counters are the same. No new values.

**Comment by kadrika** [comment]
But if I use the argument in the command like: --interface='^$ARG1$' I still see several interfaces in frontend when looking the graphs, but the output is still All interfaces are ok. How do I need to conjure the command so that it will show interface name or description and traffic in output?

**Comment by garnier-quentin** [comment]
I think you haven't use the last version. I have done a fix about that yesterday.

**Comment by kadrika** [comment]
I updated the plugins few hours ago. In the command line --interface='^$ARG1$' works nicely for one interface but how should I configure the command in Frontend?

**Comment by garnier-quentin** [comment]
Like that i think:  --interface='^$ARG1$\$'
But it's a centreon problem. Not a plugin ;)

**Comment by kadrika** [comment]
if I use ^$ARG1$\$' in command I get error: 	UNKNOWN: Need to specify '--plugin' option.

**Comment by garnier-quentin** [comment]
Give me the command please (with all arguments)

**Comment by kadrika** [comment]
$USER1$/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --hostname=$HOSTADDRESS$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --mode=interfaces --interface='^$ARG1$\$' --name --add-traffic

**Comment by garnier-quentin** [comment]
It seems ok. Could go in the detailled service with the error and give me the long ouput ?

**Comment by kadrika** [comment]
In the frontend I have command: $USER1$/centreon_plugins.pl --plugin=network::network::juniper::srx::plugin --hostname=$HOSTADDRESS$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --mode=interfaces --interface='^$ARG1$\$' --name --add-traffic --oid-display=ifDesc

So when I create a new service I write in the argument field: fe-0/0/4

When I upload the configuration I get error: UNKNOWN: Need to specify --plugin option.

in Commandline when I write: ./centreon_plugins.pl --plugin=network::juniper::srx::plugin --snmp-community=xxx --snmp-version=2c --hostname=12.3.4 --mode=interfaces --interface='^fe-0/0/4$' --name --add-traffic --oid-display=ifDesc

I get this:
OK: Interface 'fe-0/0/4' Traffic In : 28.56Kb/s (0.03%), Traffic Out : 29.40Kb/s (0.03%) | 'traffic_in'=28562.95b/s;;;0;100000000 'traffic_out'=29403.14b/s;;;0;100000000


So I think there  is some kind of mistake in my fronted command, but I do not know what it is.


Because if I use command  $USER1$/centreon_plugins.pl --plugin=network::network::juniper::srx::plugin --hostname=$HOSTADDRESS$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --mode=interfaces --interface=$ARG1$ --name --add-traffic --oid-display=ifDesc

And fill argument in service: fe-0/0/4
Then that works in fronted, but it shows all sub interfaces also and output in Frontend in All interfaces are ok.

**Comment by garnier-quentin** [comment]
Could you give me the result: select command_line from services where command_line like '%network::juniper::srx::plugin%interfaces%';

**Comment by kadrika** [comment]
I am littlebit confused - I should run this line from where?

**Comment by tcheval** [comment]
Hi,
I have the same problem. I solved by this method :

In resources add the following variable : $USER2$ = $

And modifiy the command in centreon GUI like that :  --interface='^$ARG1$$USER2$'

It seems that centreon / centreon-engine dislikes $ :)

**Comment by garnier-quentin** [comment]
Maybe you need to use like that: $$ (to have only one '$' ).

**Comment by tcheval** [comment]
I also tried, it returns an empty result of the plugin

**Comment by kadrika** [comment]
I really need to get this working, because we have some interfaces that have like 50 sub-interfaces, and we don't want to see all of them under one service. We need to see them separately, because we need to group them for reporting.

**Comment by kadrika** [comment]
And even if I am using it to check version with sub-interfaces, then dhow do I get it to show interface ifAlias or ifDesc to be shown in output in frontend and not only that All interfaces are ok, I need to see what interface is checked and what is the traffic?

**Comment by garnier-quentin** [comment]
I have tested and it works for me with the following:
$USER1$/centreon_plugins.pl --plugin=network::network::juniper::srx::plugin --hostname=$HOSTADDRESS$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --mode=interfaces --interface='^$ARG1$$$' --name --add-traffic --oid-display=ifDesc

**Comment by kadrika** [comment]
Yes, with that many $ it is working!!
Thanks!!

**Comment by kadrika** [comment]
one more thing, is it possible to add interface signal strength option also in the future?

**Comment by garnier-quentin** [comment]
I think that another mode for that. What are the OIDs ?

**Comment by kadrika** [comment]
It uses Entity-MIB. Here is quite good information:
https://supportforums.cisco.com/document/11934401/how-retrieve-and-interpret-sensor-power-voltage-current-slotport-snmp

**Comment by garnier-quentin** [comment]
Ok. that's another MIB. More for fiber channel.

**Comment by kadrika** [comment]
I need that too :)
