### ISSUE TITLE
[cloud::docker::restapi::plugin]CPU load average question

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon-plugins#1120]
Hello,

I would like to know if the CPU % usage for each docker returned by the container-usage mode is real time (like docker stats) or if it's based on an amount of time like "classic" Load average ? 

If not, maybe this can be a future improvement ? 

We would like to graph something similar than load average (1min,5min,15min) but only for specific dockers (or cgroup I think). The value returned by docker stats seems to be real time value so with a check every 5 minutes from Centreon, the informations will be irrelevant. 

If you have some ideas .. 

Thank You 

Anthony

**Comment by Sims24** [comment]
Hi @anthoc 

CPU is in "cpu_time", so we get the diff on the counter between to check and compute the average usage depending the check interval. So it's always relevant if you interpret it as an average value.

Today, adding 3 services with a different check_interval for each of them (1m, 5m, 15m) will give you the information you want on CPU. 

Load average is slightly different and Linux specific, doesn't concerns oly the cpu but didn't see anything like this on docker API so I assume we are not able to provide a better way to achieve this than duplicate some services ..

Hope this help,

**Comment by garnier-quentin** [comment]
I m agree it s not very relevant. We have opened an issue here : https://github.com/moby/moby/issues/28881

Unfortunately, they don t want to change it.
