### ISSUE TITLE
database::mssql::plugin : doesn't work in Web Interface

### ISSUE THREAD

**Issue by MBarrague** [centreon/centreon-plugins#1121]
First, I tried centreon-plugins.pl with database::mssql:plugin and after some mistakes I found the good syntax to work in CLI.

After, I put the same command line in Web Interface but it doesn't work. I think it's a syntax issue with quotes or something like that.

Error message : UNKNOWN: Cannot connect: (no error string) -> I accountered this message in CLI too.

So, Is there someone that can help me out ?

Thanks

**Comment by Sims24** [comment]
Hi @MBarrague , 

Most probable cause of this would be a special character deleted by Centreon when you saved your macros.

Could you please make sure that the command_line in the service details page is really what you expects ? 

e.g you need to double the \\ to ensure that it will be correctly executed.

**Comment by MBarrague** [comment]
Hi @Sims24 ,

Thank you for your answer.

Yes, I've already checked in the service details and everything seems to be ok. I can copy and paste to Linux shell and it works.

This is what I see in service details 

/usr/lib/centreon/plugins/centreon_plugins.pl
	--plugin=database::mssql::plugin
	--hostname='******\*****'
	--port='1433'
	--username='*******\********'
	--password='********'
	--mode=databases-size 
	--warning-database='75'
	--critical-database='90'

This command works in CLI but not in Web Interface.

**Comment by Sims24** [comment]
@MBarrague , are you executing your command line through centreon-engine user or root ? That's probably the point. guess that dbd sybase libraries might not be fully available for applicative user.

**Comment by MBarrague** [comment]
I'm executing the command from root user. 
Do I have to change sudoers file or is there another way ?

**Comment by Sims24** [comment]
Sure that you're actually testing from CLI on the server/poller the host belongs in Centreon ?

**Comment by MBarrague** [comment]
To summarize 

I've got one central :  CENTREON

I've done this tests from CENTREON cli and web interface for the same host with the same command_line.

So, the only thing that changed is Web Interface VS CLI/Shell.

**Comment by MBarrague** [comment]
I've done another test in Web interface and it works. I wrote \ in double in my command but i thought quote was the only thing needed for special character.

Is there a way to write only one \. Because I don't want to think of double \ when I write à command in web interface.

Thank you,

**Comment by Sims24** [comment]
Please enable debug on centreon-engine and send by private mail the centengine.debug file containing one command execution

**Comment by Sims24** [comment]
sorry, please ignore my last statement I will delete the message as I didn't catch your messages about double quote and solved isssue.

\ is an special char, so can't be sure there is a solution to your problem. feel free to open a case on centreon or centreon-engine github if you want further informations
