### ISSUE TITLE
perf graph cpu2 doesn't display

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1125]
I just noticed that on all cpu graph, with 4 cores or more, windows or linux plugin, there aren't cpu2 perf graph.
![cpu2](https://user-images.githubusercontent.com/30388990/45100625-11318180-b12a-11e8-99ef-51fe235cf2f4.JPG)

**Comment by Sims24** [comment]
Hi @oasisck, 

Please open this on centreon github. As far I see the perfdata from the plugins are OK, probably related to something else ;)

Thanks
