### ISSUE TITLE
[apps::vmware::connector::plugin] datastore name filter issue

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1126]
`perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=172.20.91.204 --container=DC2 --mode=datastore-vm --datastore-name=MD3820i_DC2_LUN10`
return tones of VM while there is only 4 on this LUN with or without --filter-datastore
--vm-hostname works fine

thanks for your fabulous work

**Comment by oasisck** [comment]
hi, do you need more info ?

**Comment by garnier-quentin** [comment]
Can we do a session together (2pm for example) to show me ?

**Comment by garnier-quentin** [comment]
Work as expected. It doesn't filter vm with that datastore. The mode doesn't work like that.

**Comment by oasisck** [comment]
Got it, I'll have to manage my deployment script to include that per VM
Thanks for your time ;-)
