### ISSUE TITLE
[hardware::server::dell::idrac::snmp::plugin] hardware SD redundancy

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1128]
Can you add SD card redundancy check please ?
[idrac8.txt](https://github.com/centreon/centreon-plugins/files/2356479/idrac8.txt)

**Comment by garnier-quentin** [comment]
There is nothing about redundancy (except trap notification). But maybe following oid could be ok ?
systemStateSDCardUnitStatusCombined
systemStateSDCardDeviceStatusCombined

**Comment by oasisck** [comment]
Yes it could be OK

**Comment by garnier-quentin** [comment]
A new component health: https://github.com/centreon/centreon-plugins/pull/3430
