### ISSUE TITLE
fortigate signature: warning and critical thresholds are in seconds and not in hours

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1132]
Centreon Plugins: 20180821
network::fortinet::fortigate::plugin --mode=signatures

The help message from the plugin indicates that the warning and critical threshold in in hours, but it works only if we configure it in seconds.

**Comment by Sims24** [comment]
Hi, 

Could you push a PR to fix this please ? 

Thanks

**Comment by cgagnaire** [comment]
Fixed https://github.com/centreon/centreon-plugins/commit/f70e29f4bc056909c43e2a1b8089ca89233119c6
