### ISSUE TITLE
[snmp_standard/processcount] Add a duration / elapsed option

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1134]
Hi,

Would be nice to add a `duration` / `elapsed` option to `snmp_standard/processcount`.
We would then be able to filter processes based on time they were running (perhaps rather based on time plugin first saw them).

Think about `os::linux::snmp::plugin --mode=processcount --process-status=invalid`, used to monitor zombie processes.
From time to time, a Linux process can move to a zombie state, just before it dies.
This is the case for example with Apache children.
_centreon-plugins_ may then unfortunately sporadically catch these processes, and trigger a notification.

To avoid this, a `duration` (or `elapsed` etc...) option could help.
We would then be able to catch processes which are in a zombie state since at least 300s for example.
And this is generally what we want with zombie processes.

Unfortunately `HOST-RESOURCES-MIB` does not provide elapsed time for processes.
Perhaps _centreon-plugins_, when used with the new option, could keep track of elapsed time though a temporary buffer. This is why I talked above about "time plugin first saw them".

Thank you very much :+1:

**Comment by Sims24** [comment]
Hi, 

> From time to time, a Linux process can move to a zombie state, just before it dies.
This is the case for example with Apache children.
centreon-plugins may then unfortunately sporadically catch these processes, and trigger a notification.

On this I prefer to use retry/max check attempt scheduler functions. This is tough to handle that on the perfdata and check perspective. 

Will not implement that for now.

**Comment by CPbN** [comment]
Thank you @Sims24 for your feedback.

> On this I prefer to use retry/max check attempt scheduler functions.

This could lead to false positives, as perhaps I did not give enough details in my first post.

Let's assume retry is set to 3, and :
- check 1 : PID 372 is zombie (but exits a few seconds after)
- check 2 : PID 432 is zombie (but exits a few seconds after)
- check 3 : PID 724 is zombie (but exits a few seconds after)

Service state will then switch to `CRITICAL`, whereas it should not, as no process is stuck in zombie state.

This is why a `duration`  / `elapsed` option could help.
