### ISSUE TITLE
Add a plugin for checking a domain name expiration date.

### ISSUE THREAD

**Issue by boubou** [centreon/centreon-plugins#1135]
Add a plugin for checking a domain name expiration date.
The plugin check_domain do that job but it cans be better.

https://github.com/glensc/monitoring-plugin-check_domain

Thanks a lot.

**Comment by moix** [comment]
Hi, @boubou wondering if you managed to get a solution for this? I'm looking for the same check and we use centreon so will be nice to have it in the list of supported plugins. @garnier-quentin any chance of having this in centreon soon? ;) thanks!

**Comment by garnier-quentin** [comment]
To be honest i have take a look and whois is quite a mess. there is no standard about the data.

**Comment by PedroMSantosD** [comment]
Created pull request https://github.com/centreon/centreon-plugins/pull/2794
feedback appreciated.

Given the nature of the expiry date string, and the limitation of the whois tool, it has to be customised per domain.

But my localtests do work:
```
$ perl centreon_plugins.pl --plugin  apps::whois::plugin --mode whois  --timeout 10 --domain google.com
OK: Expire date for google.com is 2028-09-14T04:00:00. | 'remaining_days'=2680;30:;10:;0;

```

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3717
