### ISSUE TITLE
[snmp_stardard::plugin] output format

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1137]
Hi,
I'm trying to customize output with snmp_standard command

This is OIDs I'm interesting
```
.1.3.6.1.4.1.674.10892.5.1.1.1.0 = STRING: "Integrated Dell Remote Access Controller 8"
.1.3.6.1.4.1.674.10892.5.1.1.2.0 = STRING: "iDRAC8"
.1.3.6.1.4.1.674.10892.5.1.1.3.0 = STRING: "This system component provides a complete set of remote management functions for Dell PowerEdge Servers"
.1.3.6.1.4.1.674.10892.5.1.1.4.0 = STRING: "Dell Inc."
.1.3.6.1.4.1.674.10892.5.1.1.5.0 = STRING: "2.52.52.52"
.1.3.6.1.4.1.674.10892.5.1.1.6.0 = STRING: "https://1.2.3.4:443"
.1.3.6.1.4.1.674.10892.5.1.1.7.0 = INTEGER: 32
.1.3.6.1.4.1.674.10892.5.1.1.8.0 = STRING: "2.52.52.52"
```
I want to output format like this
`OK : iDRAC8, 2.52.52.52`
I use this command
`perl centreon_plugins.pl --plugin=snmp_standard::plugin --mode=string-value --oid-table=.1.3.6.1.4.1.674.10892.5.1.1 --snmp-version=2c --snmp-community=public --hostname=1.2.3.4 --format-ok='%{details_ok}'`
and this command
`perl centreon_plugins.pl --plugin=snmp_standard::plugin --mode=string-value --oid=.1.3.6.1.4.1.674.10892.2.1.1.2.0 --oid=.1.3.6.1.4.1.674.10892.2.1.1.5.0 --snmp-version=2c --snmp-community=public --hostname=1.2.3.4 --format-ok='%{details_ok}'`
I saw in help I can used those format output but none seems working for what I want
`Can used: %{rows}, %{filter_rows}, %{details_warning}, %{details_ok}, %{details_critical}, %{details_unknown}`

Your advice ?
Thanks for your amazing works

**Comment by garnier-quentin** [comment]
Thank you. You use the mode to display information only ? It s not the purpose of that mode. We can add a mode to display snmp information.

**Comment by oasisck** [comment]
Indeed, it's for display.
Or maybe add this information in IDRAC plugin -> health option ? More usefull than 3 output OK information ;-)
![idrac](https://user-images.githubusercontent.com/30388990/50075998-bacfe680-01e0-11e9-92d8-cdd78314d9c2.JPG)

**Comment by garnier-quentin** [comment]
Yes we ll do that

**Comment by garnier-quentin** [comment]
Could you test it with the last version ?

**Comment by oasisck** [comment]
Perfect as usual 👍 
![image](https://user-images.githubusercontent.com/30388990/54939758-add23a00-4f29-11e9-9e9f-d02738bdadb2.png)

**Comment by garnier-quentin** [comment]
Thanks!
