### ISSUE TITLE
[storage::qnap::snmp::plugin] Cannot check CPU of QNAP storage

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1138]
Hello guys,

I have a problem to check a QNAP storage of a customer:
```
root@tl-mon01:~# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --mode=cpu --hostname=xxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='public'  --warning='80' --critical='90'
Unknown option: warning at /usr/lib/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 67.
```
Model:	TS-EC1280U
Firmware-Version:	4.3.4.0695 Build 20180830

It's he latest firmware from QNAP. All other checks are working fine.
Thank you!

Kind regards, Michael

**Comment by Sims24** [comment]
Hi, 

Could you please try to use --warning-average and --critical-average instead please ?

**Comment by MikeW83** [comment]
Thak you! That's it. Sorry for bothering you with such an easy thing.
