### ISSUE TITLE
fortigate signature: plugin return sometime negative values

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1139]
Centreon Plugins: 20180821
network::fortinet::fortigate::plugin --mode=signatures

The plugin return sometimes negative values

![fortigate-signatures](https://user-images.githubusercontent.com/6400595/45540917-e6bc8400-b80d-11e8-917b-57c025f65840.png)
[FortiGate_Signatures.txt](https://github.com/centreon/centreon-plugins/files/2382661/FortiGate_Signatures.txt)

**Comment by Sims24** [comment]
Hi, 

Think that it's probably a bug on Fortinet side. How do you think we may handle this specific case ? use the value from the cache ? Set 0 ? 

Nevertheless not a huge fan of such solution on this as Fortinet should be able to explain why this happens (wether it's a bug or specific case). 

Any chance you could get an answer from them on this one ?

**Comment by joschi99** [comment]
The problem seem's related to the Fortigate. We have this problem every day exactly at the same time between 09:30 and 10:30.
```
snmpwalk .1.3.6.1.4.1.12356.101.4.2.1.0
SNMPv2-SMI::enterprises.12356.101.4.2.1.0 = STRING: "62.00312(2018-09-19 23:15)"

date
Wed Sep 19 09:42:34 CEST 2018
```
As you can see the value returned from the firewall is in the future. We opened a case for this on Fortigate. I will close this ticket because is not related on centreon plugins.

Thanks

**Comment by Sims24** [comment]
Thanks for your investigations, will help.

**Comment by joschi99** [comment]
Hi @Sims24,
are there any news about this issue? I can confirm that the problem is still there also using latest centreon plugins 20190221

**Comment by garnier-quentin** [comment]
It's not an issue related to fortigate ?

**Comment by Sims24** [comment]
Hi, 

Did Fortigate give you an answer ?

 I'll check with @garnier-quentin and @cgagnaire but usually we do not like to code something to avoid a manufacturer bug :/

**Comment by joschi99** [comment]
You are right, I agree with you.

Thanks,
Jochen
