### ISSUE TITLE
[hardware::server::dell::idrac::snmp::plugin] DELL VRTX is warning

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1140]
Hello guys,

today we noticed an error with a hard disk in our DELL VRTX. In Centreon I'm using the iDRAC plugin and the error is showing up as warning. But I think it should be critical. The volume is RAID5 so it is definitly critical. If it's RAID6 then it could be warning.

Does anyone also expect this or am I using the wrong plugin?
Thank you!

Kind regards, Michael

**Comment by Sims24** [comment]
Hi, 

Could you paste the output please as it will help up to spot the code part we should enhance. 

regrds

**Comment by MikeW83** [comment]
Hello Simon,

my collegue hast replaced the disk yesterday. I only have the screenshot from the event logs in Centreon:
![grafik](https://user-images.githubusercontent.com/35097389/45675766-601ae600-bb30-11e8-80ca-06d8226045dc.png)
When I execute the command everything is OK now. :-(

**Comment by garnier-quentin** [comment]
I think the warning is right. But you can update the mode. You could override thresholds.

**Comment by MikeW83** [comment]
Sorry for the late response. After a time the global status switched to green (OK). But there was a bug within the firmware. We have also updated the firmware and everything is OK now.
