### ISSUE TITLE
[database::postgres::plugin] idle in transaction

### ISSUE THREAD

**Issue by jaltmeyer** [centreon/centreon-plugins#1142]
Hello,

In the querytime mode, it exclude the idle in pg_stat_activity : 

_FROM pg_stat_activity WHERE (query_start IS NOT NULL AND current_query NOT LIKE '<IDLE>%')_

But it can be nice to check the idle_in_transaction which can alert on a problem (waiting for client inside a BEGIN block) : https://www.postgresql.org/docs/current/static/monitoring-ps.html

Like idle_xact on this Nagios plugin : https://github.com/OPMDG/check_pgactivity

Thanks.
Regards.

**Comment by garnier-quentin** [comment]
Add option ```--idle```

https://github.com/centreon/centreon-plugins/pull/3771
