### ISSUE TITLE
[apps::protocols::jmx::plugin] plugin not smart enough

### ISSUE THREAD

**Issue by jcduss59** [centreon/centreon-plugins#1144]
Hello, 

Using this plugin for checking memory (and maybe others queries) is not smart in large non uniform env.
The plugin is only able to retrieve numeric values, and not percentile (with such a double query to jolokia for max and used which calculate a ratio).

ex : 
_/usr/lib/centreon/plugins/centreon_protocol_jmx.pl --plugin=apps::protocols::jmx::plugin --custommode=jolokia --url='https://server:8080/jolokia/' --username='centreon' --password='password' --mode=numeric-value --mbean-pattern='java.lang:type=Memory' --attribute='HeapMemoryUsage' --lookup-path='used' --warning='100' --format='HeapMemory Usage used blabla: %s'_
### WARNING: HeapMemory Usage used blabla: 207353640 | 'value1'=207353640;0:100;;;

It retrieves only total memory used as bytes. And with another check (lookup-path=max) the max amount allocated.

A percentile mode would be great not to have to store dedicated macro thresold for each envs or 
servers.

Be carefull, there should be problem when max is set to "-1"  ;)

Could you help to develop this ASAP ?

Thanks in advance.

**Comment by Sims24** [comment]
Hi, 

Recommend to take a look at existing mode and use https://github.com/centreon/centreon-plugins/blob/88c012f8a70feb44c5f6d12b40e10434c225627c/apps/tomcat/jmx/plugin.pm

**Comment by jcduss59** [comment]
Nice, thank you ! 


_/usr/lib/centreon/plugins/centreon_tomcat_jmx.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --url='https://server:8080/jolokia/' --username='centreon' --password='password' --mode=memory_

_OK: HeapMemory Total: 1.78 GB Used: 212.59 MB (11.68%) Free: 1.57 GB (88.32%) - NonHeapMemoryUsage Used: 197.29 MB | 'HeapMemory'=222919352B;;;0;1908932608 'NonHeapMemoryUsage'=206873880B;;;0;_


Totally KISS Compliant !
Official support was not able to advise this ;)  📦

**Comment by Sims24** [comment]
Ok, send me the case number by mail please.

**Comment by Sims24** [comment]
Works with prelly all jvm, which one are you using ?

**Comment by jcduss59** [comment]
It's a closed app from IBM.. running java daemon.

If works with pretty all jvm, should not be named "tomcat" and replace the "standard" jmx value plugin. :)
