### ISSUE TITLE
Cisco Telemetry plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1145]
Hi,
Is Centreon also planning to develop new plugin to use Cisco Telemetry?

What is Cisco Telemetry:
https://www.cisco.com/c/en/us/td/docs/iosxr/ncs5500/telemetry/b-telemetry-cg-ncs5500-62x/b-telemetry-cg-ncs5500-62x_chapter_01.html#concept_6D56EE5347EB43B48BD4FE7019F2571C

Cisco has its own plugin, but I have not tested it yet, if it works with Centreon also or not:
https://github.com/cisco/bigmuddy-network-telemetry-collector

**Comment by garnier-quentin** [comment]
It won't be done in centreon-plugins. We need a daemon. Maybe in gorgone. But the easiest way, we can use the cisco receiver and put in elasticsearch for example. And after that, we can use a centreon-plugins to read it.
https://developer.cisco.com/docs/nx-os/#!telemetry/streaming-telemetry
