### ISSUE TITLE
[bug] network::cisco::standard::snmp::plugin - Nexus 5000 no temperature

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#1148]
Hi all,
centreon-plugins/centreon_plugins.pl --version
Global Version: 20180821

using the centreon standard plugin for cisco to check all of our devices.
I just noticed, that for the Nexus 5000 Series, the temperature sensors are not registered and the checks ends in OK - All 0 components are ok.

```
centreon-plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --snmp-version 3 --snmp-username xxx --authprotocol md5 --authpassphrase xxx --hostname x.x.x.x --mode environment --component temperature --debug
OK: All 0 components are ok []. |
Environment type: unknown
Checking temperatures
```

Other plugins like "check_nwc_health" register this sensors correctly:
```
./check_nwc_health --authpassword x --authprotocol md5 --hostname x.x.x.x --mode hardware-health --multiline --protocol 3 --username xxx
OK - environmental hardware working fine | 'sens_celsius_21592'=56;100;125;; 'sens_celsius_21593'=66;100;125;; 'sens_celsius_21594'=52;100;125;; 'sens_celsius_21595'=66;100;125;; 'sens_celsius_21596'=59;100;125;; 'sens_celsius_21597'=50;100;125;; 'sens_celsius_21598'=41;67;72;; 'sens_celsius_21599'=29;90;100;; 'sens_celsius_21600'=53;90;100;; 'sens_celsius_21601'=30;90;100;; 'sens_celsius_21602'=27;90;100;; 'sens_voltsAC_26328'=3306;;;; 'sens_amperes_26330'=2;;;; 'sens_celsius_26333'=44828;;;; 'sens_dBm_26339'=0;;;; 'sens_dBm_26340'=0;;;; 'sens_voltsAC_26552'=3269;;;; 'sens_amperes_26554'=6246;;;; 'sens_celsius_26557'=40859;;;; 'sens_dBm_26563'=-3124;;;; 'sens_dBm_26564'=-2487;;;; 'sens_voltsAC_26568'=3309;;;; 'sens_amperes_26570'=8380;;;; 'sens_celsius_26573'=42246;;;; 'sens_dBm_26579'=-1924;;;; 'sens_dBm_26580'=-1844;;;;
```

As nwc_health takes too muck ressources, I would stay with centreon. Can you please fix this? 
Thanks in advance

**Comment by Sims24** [comment]
Hi, 

Could you pease copy/paste the command result without the component filter please ?

**Comment by MarcusCaepio** [comment]
Sure

centreon-plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --snmp-version 3 --snmp-username xxx --authprotocol md5 --authpassphrase xxx --hostname x.x.x.x --mode environment --debug
OK: All 135 components are ok [8/8 fans, 2/2 modules, 95/95 physical, 4/4 psus, 26/26 sensors]. | 'sensor.celsius_Module-1, Carmel-1'=56C;0:99;0:124;; 'sensor.celsius_Module-1, Carmel-2'=67C;0:99;0:124;; 'sensor.celsius_Module-1, Carmel-3'=52C;0:99;0:124;; 'sensor.celsius_Module-1, Carmel-4'=67C;0:99;0:124;; 'sensor.celsius_Module-1, Carmel-5'=59C;0:99;0:124;; 'sensor.celsius_Module-1, Carmel-6'=49C;0:99;0:124;; 'sensor.celsius_Module-1, Control'=40C;0:66;0:71;; 'sensor.celsius_Module-1, Fan Side'=29C;0:89;0:99;; 'sensor.celsius_Module-1, Port Side'=52C;0:89;0:99;; 'sensor.celsius_PowerSupply-1 Sensor-1'=30C;0:89;0:99;; 'sensor.celsius_PowerSupply-2 Sensor-1'=27C;0:89;0:99;; 'sensor.voltsAC_Ethernet1/33(volt)'=3.306V;;;; 'sensor.amperes_Ethernet1/33(ampere)'=0.002A;;;; 'sensor.celsius_Ethernet1/33(celsius)'=44.828C;;;; 'sensor.dBm_Ethernet1/33(Rx-dBm)'=0dBm;;-9.913:;; 'sensor.dBm_Ethernet1/33(Tx-dBm)'=0dBm;;;; 'sensor.voltsAC_Ethernet1/47(volt)'=3.265V;;;; 'sensor.amperes_Ethernet1/47(ampere)'=6.258A;;;; 'sensor.celsius_Ethernet1/47(celsius)'=40.691C;;;; 'sensor.dBm_Ethernet1/47(Rx-dBm)'=-3.124dBm;;;; 'sensor.dBm_Ethernet1/47(Tx-dBm)'=-2.502dBm;;;; 'sensor.voltsAC_Ethernet1/48(volt)'=3.309V;;;; 'sensor.amperes_Ethernet1/48(ampere)'=8.38A;;;; 'sensor.celsius_Ethernet1/48(celsius)'=42.195C;;;; 'sensor.dBm_Ethernet1/48(Rx-dBm)'=-1.924dBm;;;; 'sensor.dBm_Ethernet1/48(Tx-dBm)'=-1.824dBm;;;; 'count_fan'=8;;;; 'count_module'=2;;;; 'count_physical'=95;;;; 'count_psu'=4;;;; 'count_sensor'=26;;;;
Environment type: unknown
Checking fans
Fan 'FanModule-1' status is up [instance: 534]
Fan 'FanModule-2' status is up [instance: 535]
Fan 'FanModule-3' status is up [instance: 536]
Fan 'FanModule-4' status is up [instance: 537]
Fan 'PowerSupply-1 Fan-1' status is up [instance: 538]
Fan 'PowerSupply-1 Fan-2' status is up [instance: 539]
Fan 'PowerSupply-2 Fan-1' status is up [instance: 540]
Fan 'PowerSupply-2 Fan-2' status is up [instance: 541]
Checking power supplies
Power supply '32X10GBase-T + 16X10GE/Modular Supervisor in Fixed Module-1' status is on [instance: 22]
Power supply '12 port 10GBase-T' status is on [instance: 23]
Power supply 'Nexus PSU module, 100-240VAC 1100W' status is on [instance: 470]
Power supply 'Nexus PSU module, 100-240VAC 1100W' status is on [instance: 471]
**Checking temperatures
Checking voltages
Checking modules**
Module '32X10GBase-T + 16X10GE/Modular Supervisor in Fixed Module-1' status is ok [instance: 22]
Module '12 port 10GBase-T' status is ok [instance: 23]
Checking physicals
Physical 'Fabric [VPC domain:13]' status is supported [instance: 10]
Physical '32X10GBase-T + 16X10GE/Modular Supervisor in Fixed Module-1' status is supported [instance: 22]
Physical '12 port 10GBase-T' status is supported [instance: 23]
Physical 'Nexus 5596 Chassis' status is supported [instance: 149]
Physical 'Fixed Slot-1' status is supported [instance: 214]
Physical 'Module Slot-2' status is supported [instance: 215]
Physical 'Module Slot-3' status is supported [instance: 216]
Physical 'Module Slot-4' status is supported [instance: 217]
Physical 'PowerSupplyBay-1' status is supported [instance: 278]
Physical 'PowerSupplyBay-2' status is supported [instance: 279]
Physical 'FanBay-1' status is supported [instance: 342]
Physical 'FanBay-2' status is supported [instance: 343]
Physical 'FanBay-3' status is supported [instance: 344]
Physical 'FanBay-4' status is supported [instance: 345]
Physical 'Nexus PSU module, 100-240VAC 1100W' status is supported [instance: 470]
Physical 'Nexus PSU module, 100-240VAC 1100W' status is supported [instance: 471]
Physical 'FanModule-1' status is supported [instance: 534]
Physical 'FanModule-2' status is supported [instance: 535]
Physical 'FanModule-3' status is supported [instance: 536]
Physical 'FanModule-4' status is supported [instance: 537]
Physical 'PowerSupply-1 Fan-1' status is supported [instance: 538]
Physical 'PowerSupply-1 Fan-2' status is supported [instance: 539]
Physical 'PowerSupply-2 Fan-1' status is supported [instance: 540]
Physical 'PowerSupply-2 Fan-2' status is supported [instance: 541]
Physical 'FixedModule-1 Port-1' status is supported [instance: 4950]
Physical 'FixedModule-1 Port-2' status is supported [instance: 4951]
Physical 'FixedModule-1 Port-3' status is supported [instance: 4952]
Physical 'FixedModule-1 Port-4' status is supported [instance: 4953]
Physical 'FixedModule-1 Port-5' status is supported [instance: 4954]
Physical 'FixedModule-1 Port-6' status is supported [instance: 4955]
Physical 'FixedModule-1 Port-7' status is supported [instance: 4956]
Physical 'FixedModule-1 Port-8' status is supported [instance: 4957]
Physical 'FixedModule-1 Port-9' status is supported [instance: 4958]
Physical 'FixedModule-1 Port-10' status is supported [instance: 4959]
Physical 'FixedModule-1 Port-11' status is supported [instance: 4960]
Physical 'FixedModule-1 Port-12' status is supported [instance: 4961]
Physical 'FixedModule-1 Port-13' status is supported [instance: 4962]
Physical 'FixedModule-1 Port-14' status is supported [instance: 4963]
Physical 'FixedModule-1 Port-15' status is supported [instance: 4964]
Physical 'FixedModule-1 Port-16' status is supported [instance: 4965]
Physical 'FixedModule-1 Port-17' status is supported [instance: 4966]
Physical 'FixedModule-1 Port-18' status is supported [instance: 4967]
Physical 'FixedModule-1 Port-19' status is supported [instance: 4968]
Physical 'FixedModule-1 Port-20' status is supported [instance: 4969]
Physical 'FixedModule-1 Port-21' status is supported [instance: 4970]
Physical 'FixedModule-1 Port-22' status is supported [instance: 4971]
Physical 'FixedModule-1 Port-23' status is supported [instance: 4972]
Physical 'FixedModule-1 Port-24' status is supported [instance: 4973]
Physical 'FixedModule-1 Port-25' status is supported [instance: 4974]
Physical 'FixedModule-1 Port-26' status is supported [instance: 4975]
Physical 'FixedModule-1 Port-27' status is supported [instance: 4976]
Physical 'FixedModule-1 Port-28' status is supported [instance: 4977]
Physical 'FixedModule-1 Port-29' status is supported [instance: 4978]
Physical 'FixedModule-1 Port-30' status is supported [instance: 4979]
Physical 'FixedModule-1 Port-31' status is supported [instance: 4980]
Physical 'FixedModule-1 Port-32' status is supported [instance: 4981]
Physical 'FixedModule-1 Port-33' status is supported [instance: 4982]
Physical 'FixedModule-1 Port-34' status is supported [instance: 4983]
Physical 'FixedModule-1 Port-35' status is supported [instance: 4984]
Physical 'FixedModule-1 Port-36' status is supported [instance: 4985]
Physical 'FixedModule-1 Port-37' status is supported [instance: 4986]
Physical 'FixedModule-1 Port-38' status is supported [instance: 4987]
Physical 'FixedModule-1 Port-39' status is supported [instance: 4988]
Physical 'FixedModule-1 Port-40' status is supported [instance: 4989]
Physical 'FixedModule-1 Port-41' status is supported [instance: 4990]
Physical 'FixedModule-1 Port-42' status is supported [instance: 4991]
Physical 'FixedModule-1 Port-43' status is supported [instance: 4992]
Physical 'FixedModule-1 Port-44' status is supported [instance: 4993]
Physical 'FixedModule-1 Port-45' status is supported [instance: 4994]
Physical 'FixedModule-1 Port-46' status is supported [instance: 4995]
Physical 'FixedModule-1 Port-47' status is supported [instance: 4996]
Physical 'FixedModule-1 Port-48' status is supported [instance: 4997]
Physical 'Module-2 Port-1' status is supported [instance: 5206]
Physical 'Module-2 Port-2' status is supported [instance: 5207]
Physical 'Module-2 Port-3' status is supported [instance: 5208]
Physical 'Module-2 Port-4' status is supported [instance: 5209]
Physical 'Module-2 Port-5' status is supported [instance: 5210]
Physical 'Module-2 Port-6' status is supported [instance: 5211]
Physical 'Module-2 Port-7' status is supported [instance: 5212]
Physical 'Module-2 Port-8' status is supported [instance: 5213]
Physical 'Module-2 Port-9' status is supported [instance: 5214]
Physical 'Module-2 Port-10' status is supported [instance: 5215]
Physical 'Module-2 Port-11' status is supported [instance: 5216]
Physical 'Module-2 Port-12' status is supported [instance: 5217]
Physical 'Module-1, Carmel-1' status is supported [instance: 21592]
Physical 'Module-1, Carmel-2' status is supported [instance: 21593]
Physical 'Module-1, Carmel-3' status is supported [instance: 21594]
Physical 'Module-1, Carmel-4' status is supported [instance: 21595]
Physical 'Module-1, Carmel-5' status is supported [instance: 21596]
Physical 'Module-1, Carmel-6' status is supported [instance: 21597]
Physical 'Module-1, Control' status is supported [instance: 21598]
Physical 'Module-1, Fan Side' status is supported [instance: 21599]
Physical 'Module-1, Port Side' status is supported [instance: 21600]
Physical 'PowerSupply-1 Sensor-1' status is supported [instance: 21601]
Physical 'PowerSupply-2 Sensor-1' status is supported [instance: 21602]
skipped instance '25813': no description
Checking sensors
Sensor 'Module-1, Carmel-1' status is 'ok' [instance: 21592] [value: 56 celsius]
Sensor 'Module-1, Carmel-2' status is 'ok' [instance: 21593] [value: 67 celsius]
Sensor 'Module-1, Carmel-3' status is 'ok' [instance: 21594] [value: 52 celsius]
Sensor 'Module-1, Carmel-4' status is 'ok' [instance: 21595] [value: 67 celsius]
Sensor 'Module-1, Carmel-5' status is 'ok' [instance: 21596] [value: 59 celsius]
Sensor 'Module-1, Carmel-6' status is 'ok' [instance: 21597] [value: 49 celsius]
Sensor 'Module-1, Control' status is 'ok' [instance: 21598] [value: 40 celsius]
Sensor 'Module-1, Fan Side' status is 'ok' [instance: 21599] [value: 29 celsius]
Sensor 'Module-1, Port Side' status is 'ok' [instance: 21600] [value: 52 celsius]
Sensor 'PowerSupply-1 Sensor-1' status is 'ok' [instance: 21601] [value: 30 celsius]
Sensor 'PowerSupply-2 Sensor-1' status is 'ok' [instance: 21602] [value: 27 celsius]
Sensor 'Ethernet1/33(volt)' status is 'ok' [instance: 26328] [value: 3.306 voltsAC]
Sensor 'Ethernet1/33(ampere)' status is 'ok' [instance: 26330] [value: 0.002 amperes]
Sensor 'Ethernet1/33(celsius)' status is 'ok' [instance: 26333] [value: 44.828 celsius]
Sensor 'Ethernet1/33(Rx-dBm)' status is 'ok' [instance: 26339] [value: 0 dBm]
Sensor 'Ethernet1/33(Tx-dBm)' status is 'ok' [instance: 26340] [value: 0 dBm]
Sensor 'Ethernet1/47(volt)' status is 'ok' [instance: 26552] [value: 3.265 voltsAC]
Sensor 'Ethernet1/47(ampere)' status is 'ok' [instance: 26554] [value: 6.258 amperes]
Sensor 'Ethernet1/47(celsius)' status is 'ok' [instance: 26557] [value: 40.691 celsius]
Sensor 'Ethernet1/47(Rx-dBm)' status is 'ok' [instance: 26563] [value: -3.124 dBm]
Sensor 'Ethernet1/47(Tx-dBm)' status is 'ok' [instance: 26564] [value: -2.502 dBm]
Sensor 'Ethernet1/48(volt)' status is 'ok' [instance: 26568] [value: 3.309 voltsAC]
Sensor 'Ethernet1/48(ampere)' status is 'ok' [instance: 26570] [value: 8.38 amperes]
Sensor 'Ethernet1/48(celsius)' status is 'ok' [instance: 26573] [value: 42.195 celsius]
Sensor 'Ethernet1/48(Rx-dBm)' status is 'ok' [instance: 26579] [value: -1.924 dBm]
Sensor 'Ethernet1/48(Tx-dBm)' status is 'ok' [instance: 26580] [value: -1.824 dBm]

**Comment by cgagnaire** [comment]
Hi @MarcusCaepio,
As you can see, the plugin see those as sensors:
```
Checking sensors
Sensor 'Module-1, Carmel-1' status is 'ok' [instance: 21592] [value: 56 celsius]
Sensor 'Module-1, Carmel-2' status is 'ok' [instance: 21593] [value: 67 celsius]
Sensor 'Module-1, Carmel-3' status is 'ok' [instance: 21594] [value: 52 celsius]
Sensor 'Module-1, Carmel-4' status is 'ok' [instance: 21595] [value: 67 celsius]
Sensor 'Module-1, Carmel-5' status is 'ok' [instance: 21596] [value: 59 celsius]
Sensor 'Module-1, Carmel-6' status is 'ok' [instance: 21597] [value: 49 celsius]
```
Can you provide a `snmpwalk -Cc -ObentU <ip> .1` where ip is the ip address of your equipment to our private email addresses ?

**Comment by MarcusCaepio** [comment]
There are way too much OIDs. When I start the walk, I end up in an "timeout: no response from <ip>"
Can you adjust the snmpwalk command ?

**Comment by Sims24** [comment]
@MarcusCaepio please try : 

```snmpwalk -Cc -ObentU <ip> .1.3.6.1.4.1.9```

**Comment by MarcusCaepio** [comment]
@Sims24 Still too much OIDs.....

**Comment by garnier-quentin** [comment]
We can add the sensor type in option --filter. Like that:
```
--filter=sensor.celsius
```

**Comment by garnier-quentin** [comment]
You can use following option in the last version:
```
--filter="sensor,^(?!(celsius))"
```
