### ISSUE TITLE
[plugin] Cisco interfaces cast and error

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon-plugins#115]
Hi,

Also on the new plugin interfaces for Cisco we have two anomalies :

1- In mode cast, the speed in "--speed" is not taken into account in the check :

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=name --snmp-version=2 --snmp-community=com --speed=10000 --name --interface='^Ethernet1/2$' --add-cast
OK: All interfaces are ok | 'in-ucast_Ethernet1/2'=97.73%;;;0;100 'in-bcast_Ethernet1/2'=0.13%;;;0;100 'in-mcast_Ethernet1/2'=2.14%;;;0;100 'out-ucast_Ethernet1/2'=81.97%;;;0;100 'out-bcast_Ethernet1/2'=0.11%;;;0;100 'out-mcast_Ethernet1/2'=0.13%;;;0;100

2- I may be wrong, but I can not find how to display the errors of the interface. No parameter --add-error, and --add-traffic or --add-cast do not display discard or error packet.

Thanks.

**Comment by garnier-quentin** [comment]
Do you have the last plugin ? I have done a fix about that. --speed is only for traffic. Not for cast.

**Comment by tcheval** [comment]
Yes, I have the last version (yesterday)

For the cast, if the speed parameter is not relevant, how indicate the interface throughput?
the output of plugin indicate, we have 72% of Unicast on interface.
But this interface is 10G, is not correct with reality :)
OK: All interfaces are ok | 'in-ucast_Ethernet1/2'=97.29%;;;0;100 'in-bcast_Ethernet1/2'=0.17%;;;0;100 'in-mcast_Ethernet1/2'=2.54%;;;0;100 'out-ucast_Ethernet1/2'=71.57%;;;0;100 'out-bcast_Ethernet1/2'=0.11%;;;0;100 'out-mcast_Ethernet1/2'=0.17%;;;0;100

For the error counter nothing new :(

Thanks.

**Comment by garnier-quentin** [comment]
You don't have the last version. Because if you have only 1 interface checked, the output is not like that.
Moreover, 'cast' is calculted on number of packets. It's percent of all packets.

**Comment by tcheval** [comment]
Ok, I have upgraded now. The ouput for the ucast is different :

OK: Interface 'Ethernet1/2' Traffic In : Buffer creation, Traffic Out : Buffer creation, In Ucast : Buffer creation, In Bcast : Buffer creation, In Mcast : Buffer creation, Out Ucast : Buffer creation, Out Bcast : Buffer creation, In Bcast : Buffer creation |

Thank you for the clarification. For the correlation, so use whole cast and traffic is same check.
It's perfect. Many thanks.

For the error counter, I still make a mistake somewhere?

**Comment by garnier-quentin** [comment]
For the error, you have to add the following option: --add-errors

**Comment by tcheval** [comment]
Ok thanks.
Is not in the help menu :)

**Comment by garnier-quentin** [comment]
It is now :)

**Comment by tcheval** [comment]
Me again :)

The option --skip it no longer exists with the new plugin :(

**Comment by garnier-quentin** [comment]
Not need anymore. Use following option to have the same behavior: --critical-status=''

**Comment by tcheval** [comment]
Ok it seems to work :)
Many thanks again.

For your information I have an error in the plugin return in shell :

^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE $/ at /usr/local/plugins/libexec/snmp_standard/mode/interfaces.pm line 844.


./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=name --snmp-version=2 --snmp-community=com --warning-in-discard=5 --warning-out-discard=5 --warning-in-error=5 --warning-out-error=5 --critical-in-discard=10 --critical-out-discard=10 --critical-in-error=10 --critical-out-error=10 --oid-display=ifname --snmp-timeout=15 --critical-status='%{admstatus} ne "up" and %{opstatus} ne "down"' 
^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE $/ at /usr/local/plugins/libexec/snmp_standard/mode/interfaces.pm line 844.
OK: All interfaces are ok |

**Comment by garnier-quentin** [comment]
I don't have the error. Could you show your cache file content please ?

**Comment by tcheval** [comment]
I send you files by email
