### ISSUE TITLE
[database::mysql::plugin] not compatible with mariadb for replication mode

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#1151]
Hi,

We use --mode=replication-master-slave to check replication.
Your script need to have respons of query : 
MariaDB [mysql]> SHOW SLAVE STATUS;

But, with last version of mariadb, we need to specify name of connection.
SHOW SLAVE ["connection_name"] STATUS
ou 
SHOW ALL SLAVES STATUS

https://mariadb.com/kb/en/library/show-slave-status/

Could you fix your script, or perhaps, create a [database::mariadb::plugin] ?

Thanks for your help

**Comment by romsworld** [comment]
Hi,

Any news ?

Thanks,

**Comment by romsworld** [comment]
Nobody have same problem :-( ?

**Comment by romsworld** [comment]
This version : MariaDB-server-10.2.18-1.el7.centos.x86_64

**Comment by romsworld** [comment]
Hi Sims24, did you test and compare your version ?

**Comment by Sims24** [comment]
Didn't face it yet unfortunately, do not have such recent MariaDB cluster around here :)

**Comment by cgagnaire** [comment]
Hi @romsworld,
Based on the link you provided, it should be safe to replace "SHOW SLAVE STATUS" by "SHOW ALL SLAVES STATUS". Can you try to do so on your plateform ?
Thanks!

**Comment by romsworld** [comment]
Hi,

I confirm that SHOW ALL SLAVES STATUS return status.
Do you add an option for this?

**Comment by cgagnaire** [comment]
No I was asking if you can make the change in the plugin on your platform.
Copy it before as a backup, and then edit it with vi by doing a sed : %s/SHOW SLAVE STATUS/SHOW ALL SLAVES STATUS/g

**Comment by romsworld** [comment]
See fix to mariadb 👍 
For file : replicationmasterslave.pm 


>     
105c101
<             SHOW ALL SLAVES STATUS
---
>             SHOW SLAVE STATUS
107d102
< 
113c108
<         if (defined($slave_io_running) && $slave_io_running =~ /^Yes$/i) {
---
>         if (defined($slave_io_running) && $slave_io_running =~ /^yes$/i) {
118c113
<         if (defined($slave_sql_running) && $slave_sql_running =~ /^Yes$/i) {
---
>         if (defined($slave_sql_running) && $slave_sql_running =~ /^yes$/i) {
131,132c126,127
<         SHOW ALL SLAVES STATUS
<         });
---
>             SHOW SLAVE STATUS
>         });
138c133
<         if (defined($slave_io_running) && $slave_io_running =~ /^Yes$/i) {
---
>         if (defined($slave_io_running) && $slave_io_running =~ /^yes$/i) {
143c138
<         if (defined($slave_sql_running) && $slave_sql_running =~ /^Yes$/i) {
---
>         if (defined($slave_sql_running) && $slave_sql_running =~ /^yes$/i) {
232c227
<                 SHOW ALL SLAVES STATUS
---
>                 SHOW SLAVE STATUS
330d324
<

**Comment by garnier-quentin** [comment]
I have done a cleaner mode (mode=replication). Could you test it ? It's integrated your change. And also to check replication master-slave, use that option: ```--critical-slaves-running=1:1```
