### ISSUE TITLE
[network::fortinet::fortigate::plugin] - add new mode to show AP status

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1155]
With Fortigate Firewall you are able to manage directly Access Points. Can you add a new mode to check the status of the AP and maybe some performance data?

Attached you will find a snmpwalk and the MIB-file
[Fortigate.zip](https://github.com/centreon/centreon-plugins/files/2423019/Fortigate.zip)

**Comment by Sims24** [comment]
Hi, 

Thanks, we'll take a look asap

**Comment by benoitb21** [comment]
+1

**Comment by garnier-quentin** [comment]
I need some information about the fortigate.

There are Wtp. What is it exactly ? How are they linked with 'fgWcWlanSsid' ? It seems clients are connected to Wtp and Ssid also. 
```
Wtp name:
.1.3.6.1.4.1.12356.101.14.4.3.1.3.1.16.80.85.51.50.51.69.53.69.49.56.48.48.51.53.54.49 = STRING: "AP_SalaRiunioni"
.1.3.6.1.4.1.12356.101.14.4.3.1.3.1.16.80.85.52.50.51.69.51.88.49.54.48.48.52.50.51.51 = STRING: "AP_Uffici"

Ssid:
.1.3.6.1.4.1.12356.101.14.3.1.1.1.27 = STRING: "Barozzi"
.1.3.6.1.4.1.12356.101.14.3.1.1.1.34 = STRING: "Barozzi Mobile"
.1.3.6.1.4.1.12356.101.14.3.1.1.1.37 = STRING: "Barozzi Guest"
```

**Comment by benoitb21** [comment]
Hello,

The Wtp corresponds at each Access Point managed by the Fortigate.
And, the SSID can be publish or not on each different AP. So it's the raison that is possible to link a SSID to a AP.

So, yes, a client can connect to a specific SSID on a specific AP.

I don't know if it's clear.

![2019-03-20 16_08_50-FortiGate](https://user-images.githubusercontent.com/19145945/54695940-2fd9f180-4b2b-11e9-8b9e-5ea2031454a3.jpg)

**Comment by garnier-quentin** [comment]
I can provide:
- ap-usage: status (fgWcWtpSessionConnectionState. Don't really know what it means), station connected (fgWcWtpSessionWtpStationCount), traffic_in (fgWcWtpSessionWtpByteRxCount), traffic_out (fgWcWtpSessionWtpByteTxCount), cpu usage (fgWcWtpSessionWtpCpuUsage), memory usage (fgWcWtpSessionWtpMemoryUsage).

I can get client by SSID. But i can't find how to get client by SSID by WTP.

**Comment by benoitb21** [comment]
OK,
For the status, I know the possible states (I you want)  : Online ,Disconneted, Rejected, Connecting, Wainting for Authorizing or Image Downloading
Station connected, I don't know really what is it.

The Client by SSID is interresting.
You just see once each SSID, not for each AP?

**Comment by garnier-quentin** [comment]
I don't see SSID by AP. Only global. I can give clients by SSID.

**Comment by benoitb21** [comment]
Better than nothing

**Comment by garnier-quentin** [comment]
Could you test with the last version ?
