### ISSUE TITLE
new notifcation channel MS Teams

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1156]
It would be great to add Microsoft Teams as notification channel. On Teams you can configure a Incoming Webhook similar to Slack.

**Comment by garnier-quentin** [comment]
Do you have the link for the API ?

**Comment by joschi99** [comment]
I have done some test with curl following this documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using

**Comment by garnier-quentin** [comment]
You can test it with plugin: notification::microsoft::office365::teams::plugin

**Comment by joschi99** [comment]
Just done, it works perfekt :-)
