### ISSUE TITLE
JMX monitoring lack of flexibility

### ISSUE THREAD

**Issue by spiralemystik** [centreon/centreon-plugins#1160]
## Bug/Question
Hi Quentin, 
I have noticed that all the JEE plugins you are offering unfortunately requires jolokia agent.
However, in my case jolokia has been removed for security purposes.
Hence, none of your plugins are useful for me.
I, then, have to use the old known jmx_query to fetch the mbean directly.
Could you please provide an alternative of your plugins or at leat a generic jmx query plugin as an alternative of Jboss, Tomcat, Solr, Zookeeper, Kafka, Cassandra and else.
I can provide the mbeans if you wich to go further

Thank you.

**Comment by Sims24** [comment]
Hi, 

Jolokia has been targeted by several CVE but they did the job to enable a minimal protection by user/pwd when deploying agent and they also fixed some vulnerabilities in the webserver. 

We are not convinced that Jolokia is less secure than a JMX request (with what it implies on firewall/port config management). 

We will think about it about the generic jmx plugin but we do not have a lot of time to handle this for now.

**Comment by garnier-quentin** [comment]
You can use jolokia in reverse proxy mode. So you don t need to deploy jolokia on your servers.

**Comment by garnier-quentin** [comment]
I don't find cpan module to attack JMX directly. I recommend to use jolokia in reverse proxy.
