### ISSUE TITLE
[apps::protocols::http::plugin] - Mode SAOP-Content: how to use a key-file with password

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1161]
Hi,

I try to check a WebService with SOAP-content. This WS nedd a keystore (jks) with password.
How can I set the password argument for this jks file? It appear no password argument for key-file; or i did'nt see it :)
I use this command:
`/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=soap-content --service-soap='https://ip-address:8443/path/ws/mandate/get' --header='Content-Type: text/xml;charset=UTF-8' --data='/supervision/webservices/soap_get.xml' --hostname='myhost-name' --urlpath='/path/ws/mandate/get' --username='myUserName' --password='MyPassword' --port=8443 --proto=https --key-file='/path/of/tomcat.jks' --credentials`

I tried with --cert-pwd argument but it not works.

thanks for your help.

**Comment by cmeschin** [comment]
Hi,
I was able to advance a bit on my side.

Via SoapUI, the password of the Keystore file is not transmitted in the header of the request or in the XML content.

It is entered when importing the Keystore file into the project.
I have not found where it is stored yet.

I am trying to find out if it is possible to transcribe the SoapUI project into a script by including this management of the keystore file.

If you have tracks, I'm interested.

Thanks,

**Comment by cmeschin** [comment]
Hi,
I can't find any solution to solve this problem easily. I will do this by our internal development with a specific program.

regards.

**Comment by cgagnaire** [comment]
Hi @cmeschin,
Sorry if we didn't answer this request. 
We’re trying our best to satisfy anyone. 
But I’m sure it’s possible. We just miss some time to go further in so generic plugins.
Some times will go back on those and find a solution.

**Comment by cmeschin** [comment]
Hi @cgagnaire 
Ok don't worry. You can reopen it if you think a solution is possible.
On my side, if development can be shared, it will be. But I think it not be in perl, certainly in java :(
I send news about this when I have a result.
Regards.
