### ISSUE TITLE
[storage::hp::storeonce::restapi::plugin] Improve cluster-usage mode for StoreOnce 5100 version 3.18.4

### ISSUE THREAD

**Issue by jaltmeyer** [centreon/centreon-plugins#1162]
Hello,

We have some issues with this plugin and the cluster-usage mode for 3.18.4 versions :  

![storeonce_error](https://user-images.githubusercontent.com/38248555/46289973-d84ec600-c58a-11e8-8015-0f7e86512b95.png)

Here is a data dump of the content retrived on the API :
_$VAR1 = {
          'cluster' => [
                       {
                         'servicesets' => {
                                          'item' => {
                                                    'summaryHealthLevel' => '1',
                                                    'detailUrl' => '/cluster/servicesets/1',
                                                    'ssid' => '1'
                                                  }
                                        },
                         'properties' => {
                                         'sizeOnDisk' => '45915.886731566',
                                         'combinedUserBytes' => '486551867104329',
                                         'combinedFreeBytes' => '18575798976512',
                                         'status' => 'Running',
                                         'userDataStored' => '486551.86710433',
                                         'repStatus' => 'Running',
                                         'uptimeSeconds' => '3087090',
                                         'localFreeBytes' => '18575798976512',
                                         'cloudUserBytes' => '0',
                                         'combinedCapacityBytes' => '68360696004608',
                                         'sysLocation' => 'CI1',
                                         'isMixedCluster' => 'false',
                                         'dedupeRatio' => '10.596590891270711',
                                         'healthLevel' => '1',
                                         'combinedDiskBytes' => '45915886731566',
                                         'localCapacityBytes' => '68360696004608',
                                         'applianceName' => 'HPCZ3813TJ01',
                                         'softwareVersion' => '3.18.4-1820.3',
                                         'health' => 'OK',
                                         'serialNumber' => 'DY3813GU01',
                                         'cloudDiskBytes' => '0',
                                         'cloudCapacityBytes' => '0',
                                         'localUserBytes' => '486551867104329',
                                         'productClass' => 'HPE StoreOnce 5100 System',
                                         'repHealthLevel' => '1',
                                         'localDiskBytes' => '45915886731566',
                                         'cloudReadWriteLicensedDiskBytes' => '0',
                                         'cloudFreeBytes' => '0',
                                         'networkName' => 'X.X.X.X',
                                         'repHealth' => 'OK'
                                       }
                       }
                     ]
        };_

But the probe try to obtain values that are 0 here. With these replace it's OK :
capacity => localCapacityBytes
freeSpace => localFreeBytes
diskBytes => localDiskBytes

Regards,

**Comment by Cpallez** [comment]
bonjour, 

problème identique chez moi :

Use of uninitialized value in multiplication (*) at /usr/lib/centreon/plugins/centreon_hp_storeonce_restapi.pl line 4966.
Use of uninitialized value in subtraction (-) at /usr/lib/centreon/plugins/centreon_hp_storeonce_restapi.pl line 4966.
Use of uninitialized value in subtraction (-) at /usr/lib/centreon/plugins/centreon_hp_storeonce_restapi.pl line 4966.
UNKNOWN: Illegal division by zero at /usr/lib/centreon/plugins/centreon_hp_storeonce_restapi.pl line 4860.

**Comment by cgagnaire** [comment]
Hi @Cpallez,
If we look at the documentation (page 31, https://support.hpe.com/hpsc/doc/public/display?docId=c04608993), we should have those values since version 3.12.
Would it be possible for you to compare used and capacity values return by a CLI or any UI provided by the equipement, and the values return by the API.
This way, we will be able to determine which values to use.
Thank you.

**Comment by cgagnaire** [comment]
Can you test this branch cgagnaire:1162-enh-hp-storeonce-cluster-usage ?
Thanks!

**Comment by Cpallez** [comment]
it does not work 
so I did two separate script
one for version 3.16 and the other higher
3.18
my $total = $entry->{properties}->{localCapacityBytes};
my $used = $entry->{properties}->{localFreeBytes};
3.16
no change
