### ISSUE TITLE
[snmp_stardard::plugin] - option to convert hexadecimal values into decimal values

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1163]
Hi,

In some cases, snmp returns hexadecimal values.
Is there an option in snmp_standard mode to convert those values? or a new argument could be added in this mode like this "--hex-to-dec" or "--hex-to-string"
In my case, it is on Brocade fiber switch's on counter of errors (er_bad_os, er_crc, etc...).

I'll send you more examples tomorrow with real OID's and real values.

Thanks,

**Comment by cgagnaire** [comment]
Hi @cmeschin,
There is none, but from time to time we convert hexa to string for some plugins so...
We may add this.

**Comment by garnier-quentin** [comment]
Could you show the entry source result ? And the result wanted ?

**Comment by garnier-quentin** [comment]
If you use string-value mode. You can use --convert-custom-values option. For example:
```
--convert-custom-values='hex($value)'
```
