### ISSUE TITLE
New plugin : storage::netgear::readynas::snmp

### ISSUE THREAD

**Issue by ArnoMLT** [centreon/centreon-plugins#1164]
Hi !

I've just finished my first plugin to check Netgear ReadyNas in snmp mode.
It works with Raidiator v4.x and ReadyNAS OS (v6.x).
If interested I can publish it here

**Comment by cgagnaire** [comment]
Hi @ArnoMLT,
Of course you can!
Thanks!

**Comment by cgagnaire** [comment]
Thanks, we're looking at it!
