### ISSUE TITLE
network::cisco::wlc::snmp::plugin HA check

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#117]
Hi,

Can you please add HA check to Cisco controller plugin?
Thanks!

If you need snmpwalk or tests to be made, let me know.

**Comment by kadrika** [comment]
Any update?

**Comment by garnier-quentin** [comment]
Could you give me snmpwalk result about the good OIDs ?

**Comment by kadrika** [comment]
Hi,

The correct MIB seems to be CISCO-RF-MIB. OID is 1.3.6.1.4.1.9.9.176.
I will send the snmpwalk to your email.

**Comment by kadrika** [comment]
Hi again,

I tested today and it seems that it would be enough if you can add 2 modes: PeerUnitState 1.3.6.1.4.1.9.9.176.1.1.4.0 and StatusPrimaryMode 1.3.6.1.4.1.9.9.176.1.1.5.

First one has these values:notKnown(1), disabled(2), initialization(3), negotiation(4), standbyCold(5), standbyColdConfig(6), standbyColdFileSys(7), standbyColdBulk(8), standbyHot(9), activeFast(10), activeDrain(11), activePreconfig(12), activePostconfig(13), active(14), activeExtraload(15), activeHandback(16). Mode is ok if the status is 9.

Second one has value:  	true(1), false(2). Mode is ok, if the status is 1.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
