### ISSUE TITLE
storage::netapp::snmp::plugin wrong total space -> negative disk usage

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#1171]
./centreon_plugins.pl --plugin storage::netapp::snmp::plugin --hostname x.x.x.x --snmp-community abcd --mode filesys --filter-name /vol/testvolume --warning-usage 90 --critical-usage 95
CRITICAL: Filesys '/vol/testvolume' Total: 1.00 TB Used: -766237798400.00 B (-69.69%) Free: 1.70 TB (169.69%) | 

Real values:
Total Space: 9TB, Available 1,7 TB

So there is a bug in reading the total space

**Comment by Sims24** [comment]
Hi @MarcusCaepio 

This is a known limit from SNMP counter size. Please prefer to use a dedicated VM to install OnCommand API and use the newest netapp plugins. 

Regards
