### ISSUE TITLE
[new] [plugin] check vcsa through RestAPI

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#1176]
As requested by @romsworld, would be great to have a plugin to check VSCA through its web API. 

Is there anybody that could provides sample output from API : 

"mgmt", path: "/rest/appliance/health/applmgmt"
"database", path: "/rest/appliance/health/database-storage"
"load", path: "/rest/appliance/health/load"
"storage", path: "/rest/appliance/health/storage"
"swap", path: "/rest/appliance/health/swap"
"system", path: "/rest/appliance/health/system"

Thanks

**Comment by romsworld** [comment]
Hi,

Anybody ? :)

**Comment by Sims24** [comment]
Hi @romsworld 

Could you provide in private from your architecture please? 

Thx

**Comment by garnier-quentin** [comment]
Could you provide us the curl call result @romsworld ? (of your virtual center server appliance)

**Comment by garnier-quentin** [comment]
Could you test it @romsworld ?
