### ISSUE TITLE
network::cisco::wlc::snmp::plugin AP-status mode issue

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#118]
Hi,

I need the plugin to return Critical status, if the AP is not associated to controller, right now I get unknown status. How do I need to change the command line?

My command is:
./centreon_plugins.pl --plugin=network::cisco::wlc::snmp::plugin --hostname=1.2.3.4 --snmp-community=xxx --snmp-version=2c --mode=ap-status --filter-name=AP02

with that I get response:
UNKNOWN: No entry found. 
Skipping  'AP13': no matching filter.
Skipping  'AP14': no matching filter.

**Comment by kadrika** [comment]
Also, is it possible to add possibility to get AP status and users connected to that AP returned in the same command and output, so that I can use --filter-name as only argument?
So to be more clear I need the output to be like: OK: AP 'EE_AP01' Status : associated. Connected clients: 12
And if the AP is not associated, then the output would be:Critical: AP' EE_AP01' Status : disassociated

**Comment by garnier-quentin** [comment]
Maybe i can add also status in the other mode. I'll think about it.

**Comment by kadrika** [comment]
Thanks!

**Comment by kadrika** [comment]
But can you fix at least that, if the AP is disassociated then the output will be critical. Right now I get unknown and that does not generate alarm.

**Comment by garnier-quentin** [comment]
Right now, it could work with following option: --opt-exit=critical

**Comment by kadrika** [comment]
Thanks! Super help!

**Comment by garnier-quentin** [comment]
In last version, you can use --critical-total option to check the number of AP connected.

**Comment by kadrika** [comment]
Thanks!
