### ISSUE TITLE
[apps::vmware::connector::plugin] - unable to monitor IOPS, IO and latency on VSAN

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1184]
On VMWare 6.5/6.7 we are not able to monitor datastore IOPS, IO and latency:

- IO: returns always values 0
'read_rate'=0B/s;0:100000000;0:200000000;0;
'write_rate'=0B/s;0:100000000;0:200000000;0;
- IOPS: UNKNOWN: No Vmfs datastore(s) checked. Cannot get iops from Nas datastore(s)
- Latency: UNKNOWN: Can't get a single datastore.

Anyone has an idea how to resolve this issue?

Thanks

**Comment by cgagnaire** [comment]
Hi @joschi99,
Which version of the VMware perl SDK are you using ?

**Comment by joschi99** [comment]
Hi @cgagnaire,
we have installed VMware-vSphere-Perl-SDK-6.5.0-7397310.

**Comment by joschi99** [comment]
Hi @cgagnaire, do you have some idea about this issue?

**Comment by garnier-quentin** [comment]
It's an extension API for vsan. Maybe in new release centreon-vmware (3.0.0)

**Comment by sbraz** [comment]
Hi @garnier-quentin. If I correctly interpreted what is said [here](http://www.lucd.info/2011/04/22/get-the-maximum-iops/), there is indeed a way to get IOPS for NFS datastores.

Does this mean that you could use the value of `virtualdisk.numberreadaveraged.average` instead of `disk.numberRead.summation`?

**Comment by garnier-quentin** [comment]
I will test and try to add that.

**Comment by sbraz** [comment]
@garnier-quentin Hi, have you had a chance to look into that?

**Comment by garnier-quentin** [comment]
Yes i could look for it soon.

**Comment by lolokai** [comment]
Hello @garnier-quentin,
Are you already working to this feature ?
Regards,

**Comment by garnier-quentin** [comment]
No because i don't have access to test.

**Comment by joschi99** [comment]
Hi @garnier-quentin,
I have access to a system. If you let me know what you need I can provide datas.

**Comment by garnier-quentin** [comment]
I have done an update of centreon-vmware connector. now, there is 2 new modes:
- status-cluster
- vsan-cluster-usage

And the mode 'datastore-iops' provides IOPs on Vsan datastore also.

**Comment by joschi99** [comment]
Thank you very much

**Comment by Crowley14** [comment]
Hello @garnier-quentin ,

I just updated my centreon-vmware plugin and try to use "vsan-cluster-usage" mode but I'm facing that issue UNKNOWN: Vsan is not enabled in vmware connector

Thanks

**Comment by garnier-quentin** [comment]
You need to install vsan perl sdk (choose the good version): https://code.vmware.com/web/sdk/6.7U3/vsan-perl

**Comment by Crowley14** [comment]
Sounds obvious now :) Thanks for your quick answer !

**Comment by garnier-quentin** [comment]
And you need to put the 2 pm files in right directory (with vmware sdk files)

**Comment by Erawor** [comment]
Hello,
can you help me please @garnier-quentin 

The plugin works like this :
```
cp /tmp/vsan-sdk-perl/bindings/* /tmp/vsan-sdk-perl/samplecode/

./vsanapisample.pl --url https://serv-vcsa/sdk/vimService --username uservcsa --password pwd --cluster_name DMZ
loading ./VIM25VsanmgmtStub.pm
loading ./VIM25VsanmgmtRuntime.pm

Connection Successful
cluster name: DMZ
Do you want to fetch the cluster health from cache if exists?(y/n): 

y
Fetching cluster health from cached state: true
cluster DMZ status: green
Task updated with progress(1%)
Repairing task completed.
```
but not working from centreon plugin
```
perl centreon_plugins.pl --plugin apps::vmware::connector::plugin --custommode connector --connector-hostname localhost --container default --mode vsan-cluster-usage --cluster-name DMZ
UNKNOWN: Vsan is not enabled in vmware connector |
```
the 2 pm files in several directories of vmware-viperl (and vmware-vcli directory) but I still have the same problem. 

vmware sdk files (i think ?) :
```
cp /tmp/vsan-sdk-perl/samplecode/* /usr/lib/vmware-viperl/apps/AppUtil/
cp /tmp/vsan-sdk-perl/samplecode/* /usr/lib/vmware-viperl/apps/general/
cp /tmp/vsan-sdk-perl/samplecode/* /usr/lib/vmware-viperl/apps/host/
cp /tmp/vsan-sdk-perl/samplecode/* /usr/lib/vmware-viperl/apps/vm/
```
thanks for help
happy new year :)

**Comment by sbraz** [comment]
@garnier-quentin I've tried centreon-vmware v3.1.0 and I still don't see IOPS for my NFS datastores with `--mode=datastore-iops`.
With mode `vsan-cluster-usage`, I get an empty `OK:  |` reply and the debug shows `"data":{}`.

If anybody else has trouble installing the vsan SDK: you need to copy `VIM25VsanmgmtRuntime.pm` and `VIM25VsanmgmtStub.pm`into `/usr/local/share/perl5/VMware` and add this line to `/etc/centreon/centreon_vmware.pm` if you're using the vSphere SDK from Centreon's RPMs (see https://github.com/centreon/centreon-vmware/pull/85)
```perl
vsan_sdk_path => '/usr/local/share/perl5/VMware',
```
