### ISSUE TITLE
Linux storage plugin by free B/MB/GB

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1187]
Hi,

I need to monitor one partition using linux storage command.
I need it to alert, when there is only 100GB free space left.

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=storage --hostname=1.2.3.4 --snmp-community=abc --snmp-version=2c --warning-usage=100000000000 --units=B --name --storage='/var/log' --free

Is this correct?

Is there any way to change the plugin to use MB or GB instead of B?

**Comment by cgagnaire** [comment]
Hi @kadrika,
Yes, that's correct.
We'll have to think about it :)

**Comment by garnier-quentin** [comment]
You can use unit in threshold. An example: --warning=10MB:100GB
