### ISSUE TITLE
[storage::netapp::snmp::plugin] mode qtree-usage No alert for WARNING CRITICAL threshold 

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#1193]
Hello la Team!

J'ai l'impression que dans ma perfdata la valeur  warning et critique ne sont pas mises.

Si besoin je peux fournir le snmpwalk des OID présent dans la sonde

/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl 
--plugin=storage::netapp::snmp::plugin 
--mode=qtree-usage --hostname X.X.X.X --snmp-version='2c' --snmp-community='public' --snmp-timeout=15 --snmp-retries=1 

--filter-qtree='(^?(SHQGR)$)' 

--filter-volume='.*' 
--warning-usage='80' 
--critical-usage='90' 
--units='%'     => Testé aussi avec 'B'
--verbose

OK: Qtree 'uvi060117/vol_Trevoux/SHQGR' Total: 45.00 TB Used: 39.95 TB (88.77%) Free: 5.05 TB (11.23%) | 'used'=43920167796736B;;;0;49478023249920

Qtree 'uvi060117/vol_Trevoux/SHQGR' Total: 45.00 TB Used: 39.95 TB (88.77%) Free: 5.05 TB (11.23%)

**Comment by cgagnaire** [comment]
Hi @Jordan91,
Indeed, fixed right here -> https://github.com/centreon/centreon-plugins/pull/1195
