### ISSUE TITLE
Plugin veeam --mode=job-status  Argument "1540674786,083" isn't numeric in numeric lt (<) at ... jobstatus.pm line 257

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#1202]
Bonjour,

Le plugin est à jour dans sa dernière version , mais il y a toujours une erreur de ce type pour le mode job-status :

C:\Program Files\centreon-nsclient\NSClient++\scripts\centreon>centreon_plugins.exe 
--plugin=apps::backup::veeam::local::plugin --mode=job-status

Argument "1540674786,083" isn't numeric in numeric lt (<) at C:\Users\XXXXX\AppData\Local\Temp\2\par2636f61717565747465\cache555e56d520432b5534dd558116fb4d09e12bb9c2\inc\lib/apps/backup/veeam/local/mode/jobstatus.pm line 257

Erreur similaire à : 
https://github.com/centreon/centreon-plugins/issues/863

Merci d'avance !

**Comment by Sims24** [comment]
Hello @Jordan91 

Are you sure that centreon_plugins.exe actually contains the fix ? Do you use the lst version ?

**Comment by Jordan91** [comment]
Hi @Sims24  

The version installed is that one  :

![vers_nsclient](https://user-images.githubusercontent.com/16045498/47663119-8d7d9980-db9c-11e8-941f-9c65efe0cf99.png)

It is not the last version?

**Comment by Sims24** [comment]
Nope, you should update the exe on the server I guess it will do the tricks ;)

Thanks
