### ISSUE TITLE
question : plugin=os::linux::snmp::plugin --mode=storage

### ISSUE THREAD

**Issue by phillebr** [centreon/centreon-plugins#1203]
hello,

**The 'free' options with units '%' does'nt work .**

without the free option the resul is :

 perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=192.168.10.6 --snmp-version=2c --statefile-dir=/tmp --name --storage='/var/www/miq/vmdb/log' --warning-usage=90 --critical-usage=95
_OK: Storage '/var/www/miq/vmdb/log' Usage Total: 9.99 GB Used: 209.25 MB (2.05%) Free: 9.79 GB (97.95%) | 'used'=219410432B;0:9654239232;0:10190585856;0;10726932480_

when i use the free option the result is:

perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=192.168.10.6 --snmp-version=2c --statefile-dir=/tmp --name --storage='/var/www/miq/vmdb/log' --warning-usage=10 --critical-usage=5 --free
_CRITICAL: Storage '/var/www/miq/vmdb/log' Usage Total: 9.99 GB Used: 211.09 MB (2.06%) Free: 9.78 GB (97.94%) | 'free'=10505588736B;0:1072693248;0:536346624;0;10726932480_

my question is : with the 'free' option, are critical and warning usage correct ?
Thanks
Philippe

**Comment by Sims24** [comment]
Hi, 

You have to use monitoring plugins standard syntax like this : 

`--warning=10: --critical=5: 
`
Regards

**Comment by phillebr** [comment]
with this options it does'nt work : 
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=192.168.10.6 --snmp-version=2c --statefile-dir=/tmp --name --storage='/var/www/miq/vmdb/log' --warning=10 --critical=5 --free
Unknown option: warning at /savliv/centreon-plugins-master/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by Sims24** [comment]
Because it is incorrect. append -usage. See --help

**Comment by phillebr** [comment]
when i use warning-usage or critical-usage with --free the result is incorrect.
look at my first message.
My storage /var/www/miq/vmdb/log is used at 2%.

**Comment by Sims24** [comment]
Look at my first answer. otherwise copy/paste your command line and I'll do the job for you.
