### ISSUE TITLE
Problem os::windows::snmp::plugin --mode=processcount

### ISSUE THREAD

**Issue by rodrigobiagi** [centreon/centreon-plugins#1204]
## os::windows::snmp::plugin --mode=processcount with process-path set

Hello, I am testing latest version 2.8.26 of Centreon with CentOS 7  in the company and I encountered the following problem.
by command line the plugin works.

./centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=10.150.31.101 --snmp-community='centreon' --snmp-version='2c' --memory --process-name='AppServer.exe' --regexp-name --process-path='F:\workdir\protheus\bin\appserver\' --warning 1 --critical 1: --verbose
OK: Number of current processes running: 1 - Total memory usage: 108.68 MB - Average memory usage: 108.68 MB | 'nbproc'=1;0:1;1:;0; 'mem_total'=113958912B;;;0; 'mem_avg'=113958912.00B;;;0;
Process '15096' [memory: 108.68 MB] [status: running] [name: AppServer.exe] [path: F:\workdir\protheus\bin\appserver\]

for web interface has problem
Does not display metrics and even process availability
Possibly due to the process-path field,
--process-path = 'F: \ workdir \ protheus \ bin \ appserver_CRITICAL 1:'

i set fields:
PROCESSNAME - AppServer.exe
PROCESSPATH - F:\workdir\protheus\bin\appserver\
CRITICAL - 1:

After save and reload Poller 
Monitoring --> Status Details --> Services 
and select service configured show this:

/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=10.171.67.101 --snmp-version='2c' --snmp-community='centreon'  --process-name='AppServer.exe' --process-path='F:\workdir\protheus\bin\appserver_CRITICAL                      1:' --process-args='' --regexp-name --regexp-path --regexp-args --warning='' --critical=''

**Comment by cmeschin** [comment]
Hi,
Have you tested with this path "--process-path='F:/workdir/protheus/bin/appserver" ?
Windows allow to use "/" instead of "\"

regards,

**Comment by rodrigobiagi** [comment]
Hi, i tried with the new centreon version v18.10.0 ando have other problem with process-count

in comand line i try it an perfect result. remembering that I copied this command from the "Centreon" web

/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=10.12.25.101 --snmp-version='2c' --snmp-community='centreon' --process-name='wrapper.exe' --process-path='F:\\sonarqube-7.0_QAS_Main\\bin\\windows-x86-64' --regexp-name --regexp-path --warning='' --critical='1:' --verbose
OK: Number of current processes running: 1 | 'nbproc'=1;;1:;0;
Process '9620' [status: running] [name: wrapper.exe] [path: F:\sonarqube-7.0_QAS_Main\bin\windows-x86-64\]

but in centreon web show it with process running:
Status information | CRITICAL: Number of current processes running: 0

**Comment by garnier-quentin** [comment]
I think there is a problem with backslash. You can trick it with the dot character: replace backslashs by dots.

**Comment by rodrigobiagi** [comment]
> I think there is a problem with backslash. You can trick it with the dot character: replace backslashs by dots.

Hey... now running perfect.. tks

**Comment by gustavoandreotti** [comment]
Hello all,

I have the same issue. But in case my folder path have a namspace. How can I do for working the commando? Below you can see my command:

/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=x.x.x.x --snmp-version='2c' --snmp-community='grtbr_snmp' --process-name='jabra-direct.exe' --process-path="C:/Program Files (x86)/Jabra/Direct4" --process-args='' --regexp-name --regexp-path --regexp-args --warning='1' --critical='1'


If you check my process-path, have namespace...

Regards,

Gustavo
