### ISSUE TITLE
Add utilization mode to network::cisco::wlc::snmp::plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1210]
Hi,

The network::cisco::wlc::snmp::plugin has already noise and interference mode, but could you please add also AP utilization mode?
The OID that gives that output is:
bash-4.1$ snmpwalk 1.2.3.4 -v2c -c public -Ou 1.3.6.1.4.1.14179.2.2.13.1.3
enterprises.14179.2.2.13.1.3.0.162.238.225.83.0.0 = INTEGER: 53
enterprises.14179.2.2.13.1.3.0.162.238.225.83.0.1 = INTEGER: 1
enterprises.14179.2.2.13.1.3.0.162.238.241.162.224.0 = INTEGER: 58
enterprises.14179.2.2.13.1.3.0.162.238.241.162.224.1 = INTEGER: 1
enterprises.14179.2.2.13.1.3.0.215.143.21.89.128.0 = INTEGER: 36
enterprises.14179.2.2.13.1.3.0.215.143.21.89.128.1 = INTEGER: 2
enterprises.14179.2.2.13.1.3.0.215.143.21.97.64.0 = INTEGER: 43
enterprises.14179.2.2.13.1.3.0.215.143.21.97.64.1 = INTEGER: 1
enterprises.14179.2.2.13.1.3.0.215.143.22.223.160.0 = INTEGER: 65
enterprises.14179.2.2.13.1.3.0.215.143.22.223.160.1 = INTEGER: 3
enterprises.14179.2.2.13.1.3.0.215.143.26.193.32.0 = INTEGER: 77
enterprises.14179.2.2.13.1.3.0.215.143.26.193.32.1 = INTEGER: 1
enterprises.14179.2.2.13.1.3.0.215.143.26.202.192.0 = INTEGER: 12
enterprises.14179.2.2.13.1.3.0.215.143.26.202.192.1 = INTEGER: 1
enterprises.14179.2.2.13.1.3.0.215.143.26.203.128.0 = INTEGER: 59
enterprises.14179.2.2.13.1.3.0.215.143.26.203.128.1 = INTEGER: 2
enterprises.14179.2.2.13.1.3.0.215.143.26.213.0.0 = INTEGER: 38
enterprises.14179.2.2.13.1.3.0.215.143.26.213.0.1 = INTEGER: 2
enterprises.14179.2.2.13.1.3.0.215.143.30.6.224.0 = INTEGER: 40
enterprises.14179.2.2.13.1.3.0.215.143.30.6.224.1 = INTEGER: 5
enterprises.14179.2.2.13.1.3.0.215.143.30.8.128.0 = INTEGER: 13
enterprises.14179.2.2.13.1.3.0.215.143.30.8.128.1 = INTEGER: 1
enterprises.14179.2.2.13.1.3.0.215.143.194.19.64.0 = INTEGER: 40
enterprises.14179.2.2.13.1.3.0.215.143.194.19.64.1 = INTEGER: 2
enterprises.14179.2.2.13.1.3.0.215.143.230.62.0.0 = INTEGER: 28
enterprises.14179.2.2.13.1.3.0.215.143.230.62.0.1 = INTEGER: 1

**Comment by Sims24** [comment]
Hi @kadrika 

Could you provide some details about the OID definition, an extract from the mib would be great. 

Regards

**Comment by landregen** [comment]
[huawei.zip](https://github.com/centreon/centreon-plugins/files/3290491/huawei.zip)

**Comment by garnier-quentin** [comment]
In mode 'ap-status', you can add options: ```--add-radio-interfaces```
