### ISSUE TITLE
[apps/protocols/http] Thresholds on captured value in --expected-string

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1211]
Hi,

In `apps::protocols::http::plugin`, when looking for content using `--mode=expected-content`, would be nice to be able define thresholds on a capture value in the expected string.

Let's assume a web page contains the following :
`Node: 1, Status: OK, Ping: 10, Connections: 34, Load: 100`

And we want less than 100 connections.

The following would do what we want :
`--expected-string=",Connections: ([0-9]*)," --captured-warning=80 --captured-critical=100`
_Note the captured value in the regexp._

Of course the captured value would go in performance data.

Thank you very much :+1:

**Comment by Sims24** [comment]
Hi, 

Thanks I like the idea but there is some additional work about the code implementation, e.g threshold added to the perfdata is mandatory. Not sure how to prioritize alerts also, get_most_critical does not sound as an options here I guess as for every old modes a wider refactoring might worst the case.

What do you think about this @cgagnaire ?

**Comment by CPbN** [comment]
Thank you for your feedback @Sims24.
You're right I forgot the perfdata thresholds, I just pushed a commit adding them.

**Comment by CPbN** [comment]
Thank you for your feedback @Sims24.
You're right I forgot the perfdata thresholds, I just pushed a commit adding them.
I also performed some code refactor, however I'm not sure why we would need `get_most_critical`, as we want all `WARNING` / `CRITICAL` items to be displayed in the output ?

**Comment by Sims24** [comment]
Yes that why it does not sound as an option, we should rather use counter class :)

**Comment by CPbN** [comment]
What I meant is that all `WARNING` / `CRITICAL` items are already displayed.
For example, with `--warning-extracted=1 --critical=0.001 --critical-size=10`, output is :
`CRITICAL: Response time : 0.089s - Content size : 2283 WARNING: Extracted value : 5`
Is that not OK ?
_(cosmetic thing, I think we need a separator just before `WARNING` in this example)_

**Comment by CPbN** [comment]
Closing this as it has been implemented.
