### ISSUE TITLE
[hardware::server::hp::ilo::xmlapi::plugin] - execution output shows duplicate instance names

### ISSUE THREAD

**Issue by gouldchu** [centreon/centreon-plugins#1213]
Hi All,

I use "hardware::server::hp::ilo::xmlapi::plugin" to monitor HP hardware via iLO 4. Physical network adapters include "Adapter 1 - iLO" and "Adapter 2 - HP Ethernet 1Gb 4-port 366FLR Adapter".

When iLO4 Firmware is upgraded from 2.00 to 2.61, NIC monitoring shows "CRITICAL: NIC 'Port 2' status is 'Disabled'".

The new iLO (ver. 2.61) puts shared network port to ILO adapter. The default status “Disabled” of shared port is detected and triggers “critical” alert. 

**My original command:**
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname=$_HOSTILO_IP$ --username=$_HOSTILO_ID$ --password=$_HOSTILO_PW$ --component=nic --timeout=30 --verbose

**Execution result:**
CRITICAL: NIC 'Port 2' status is 'Disabled' | 'count_nic'=6;;;;
Checking nic
nic 'Port 1' status is 'OK' [instance = Port 1]
nic 'Port 2' status is 'Disabled' [instance = Port 2]
nic 'Port 1' status is 'OK' [instance = Port 1]
nic 'Port 2' status is 'OK' [instance = Port 2]
nic 'Port 3' status is 'OK' [instance = Port 3]
nic 'Port 4' status is 'OK' [instance = Port 4]

Thanks to Simon's help, I modify the command.

**My current command:**
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname=$_HOSTILO_IP$ --username=$_HOSTILO_ID$ --password=$_HOSTILO_PW$ --component=nic --timeout=30 --verbose --threshold-overload='nic,Port 2,OK,Disabled'

**Execution result:**
OK: All 6 components are ok [6/6 nic]. | 'count_nic'=6;;;;
Checking nic
nic 'Port 1' status is 'OK' [instance = Port 1]
nic 'Port 2' status is 'Disabled' [instance = Port 2]
nic 'Port 1' status is 'OK' [instance = Port 1]
nic 'Port 2' status is 'OK' [instance = Port 2]
nic 'Port 3' status is 'OK' [instance = Port 3]
nic 'Port 4' status is 'OK' [instance = Port 4]

With this option, "--threshold-overload", we can change the "Disabled" status to OK. That's great. However, this seems to cause another problem. "Port 2 of Adapter 2" monitoring is influenced by this option too. We can't set up option only for "Port 2 on Adapter 1" or "Port 2 on Adapter 2". 

In brief, execution output shows duplicate instance names. If new version can solve this issue, this plugin will be much more flexible and powerful.

Thank you all very much for your understanding and great effort on such an awesome masterpiece. Your tremendous works really help a lot of people all over the world.

**Comment by garnier-quentin** [comment]
Could you provide us the result with --debug option ?
