### ISSUE TITLE
Problem with CPU metrics after last update 

### ISSUE THREAD

**Issue by rodrigobiagi** [centreon/centreon-plugins#1214]
Hi 

After last update of the plugins presented error in the CPU metrics. Linux and Windows

Status information - Unknown option: warning at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 142.

Updates applied 

Updated:
  centreon-plugin-Applications-Databases-Mysql.noarch 0:20181019-1.el7                                                  
  centreon-plugin-Applications-Monitoring-Centreon-Database.noarch 0:20181019-1.el7                                     
  centreon-plugin-Applications-Monitoring-Centreon-Poller.noarch 0:20181019-1.el7                                       
  centreon-plugin-Applications-Protocol-Ftp.noarch 0:20181019-1.el7                                                     
  centreon-plugin-Applications-Protocol-Ldap.noarch 0:20181019-1.el7                                                    
  centreon-plugin-Hardware-Printers-Generic-Snmp.noarch 0:20181019-1.el7                                                
  centreon-plugin-Network-Cisco-Standard-Snmp.noarch 0:20181019-1.el7                                                   
  centreon-plugin-Applications-Monitoring-Centreon-Central.noarch 0:20181019-1.el7
  centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx.noarch 0:20181019-1.el7
  centreon-plugin-Applications-Protocol-Dns.noarch 0:20181019-1.el7
  centreon-plugin-Applications-Protocol-Http.noarch 0:20181019-1.el7
  centreon-plugin-Generic-Snmp.noarch 0:20181019-1.el7
  centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp.noarch 0:20181019-1.el7
  centreon-plugin-Operatingsystems-Linux-Snmp.noarch 0:20181019-1.el7

**Comment by cgagnaire** [comment]
Hi @rodrigobiagi,
Please refer to the https://github.com/centreon/centreon-plugins/releases/tag/20180928 release note, and the break change about those thresholds.
If you are using the Plugin Packs, make sure to update Linux pack to 3.1.0 and Windows pack to 3.2.0.
Thank you.
