### ISSUE TITLE
Check raid Qnap TS-832XU

### ISSUE THREAD

**Issue by benjamin68** [centreon/centreon-plugins#1216]
Hello everyone, I would like to check the status of my QNAP raid but no plugin allows it. Could you create an extension of the hardware plugin that would allow it? The model of my qnap is TS-832XU

**Comment by rk4an** [comment]
Hi,

And here the MIB of this model, and the OID to get the RAID status :
[NAS.mib.txt](https://github.com/centreon/centreon-plugins/files/2562347/NAS.mib.txt)

```
enterprises.24681.1.4.1.1.1.2.1.2.1.1.1 = INTEGER: 1
enterprises.24681.1.4.1.1.1.2.1.2.1.2.1 = INTEGER: 1
enterprises.24681.1.4.1.1.1.2.1.2.1.3.1 = Counter64: 69934465941504
enterprises.24681.1.4.1.1.1.2.1.2.1.4.1 = Counter64: 0
enterprises.24681.1.4.1.1.1.2.1.2.1.5.1 = STRING: "Degraded"
enterprises.24681.1.4.1.1.1.2.1.2.1.6.1 = INTEGER: 0
enterprises.24681.1.4.1.1.1.2.1.2.1.7.1 = STRING: "5"
```

**Comment by cgagnaire** [comment]
Hi @rk4an,
Would you mind provide a full snmpwalk sended to my email.
`snmpwalk -ObentU -Cc <ip> .1`
Thank you!

**Comment by garnier-quentin** [comment]
Do you have the status list also ?
