### ISSUE TITLE
[database::oracle::plugin] Long Queries weird output

### ISSUE THREAD

**Issue by Nalkhael** [centreon/centreon-plugins#1218]
Hello,

I have an issue to monitor a Oracle DB with centreon_plugin.pl, I have no particular error with other check mode, but when i want to check long queries :

/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=database::oracle::plugin --mode=long-queries --hostname=myhost --datasource=Oracle:myhost/mydb --username=user --password=***

I got many lines (+50) with : "Argument "1541985283,999999999999999999999999999996" isn't numeric in localtime at /usr/lib/centreon/plugins/database/oracle/mode/longqueries.pm line 174."

It's end with : OK: 0 problem(s) detected | 'alerts'=0;;;0;

I'm using Oracle client 12.2 with Centreon 2.8.25 and centreon-plugins last version.

Thanks in advance :)

Nal

**Comment by Sims24** [comment]
Hi, 

Maybe Oracle 12.2 manage very accurate timestamps ...  We will dig around this and let you know

**Comment by garnier-quentin** [comment]
It seems like a french database configuration ?

**Comment by Nalkhael** [comment]
Hi, what configuration in particular ?

**Comment by garnier-quentin** [comment]
What is the configuration of NLS_NUMERIC_CHARACTER ?

**Comment by garnier-quentin** [comment]
Nervermind. We manage it :)
