### ISSUE TITLE
os::windows::snmp::plugin OS-Windows-Disk-Generic-Name-SNMP-custom

### ISSUE THREAD

**Issue by rodrigobiagi** [centreon/centreon-plugins#1220]
Problem with default macro

If you configure OS-Windows-Disk-Generic-Name-SNMP-custom with default macro return UNKNOWN Stats
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=10.171.67.119 --snmp-version='2c' --snmp-community='centreon'  --storage='E:' --name --display-transform-src='^(..).*' --display-transform-dst='$1' --warning-usage='80' --critical-usage='90'
i set only DISKNAME 'E:'

But if set EXTRAOPTIONS with '--regexp' be run ok

**Comment by cgagnaire** [comment]
Hi @rodrigobiagi,
This is a Plugin Pack thing, and the "Generic-Name" service template is supposed to be used with exact drive name match.
If you want to use regexp, please use the "Global" service template and set the FILTER macro.
Thanks.
