### ISSUE TITLE
Plugin for Ubiquiti EdgeSwitch router

### ISSUE THREAD

**Issue by fudcompliance** [centreon/centreon-plugins#1223]
Kindly add a plugin to monitor Ubiquiti EdgeSwitch routers . Attached is the  equipment.snmpwalk generated using snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk . We can provide additional information if needed , we have access to a EdgeSwitch 16-Port 10G router with firmware 1.4.0.4868411, Linux 3.6.5 . 
Thank you

[equipment.snmpwalk.zip](https://github.com/centreon/centreon-plugins/files/2584924/equipment.snmpwalk.zip)

**Comment by cgagnaire** [comment]
Hi @fudcompliance,
We already have an Ubiquiti plugin (https://github.com/centreon/centreon-plugins/tree/master/network/ubiquiti/edge/snmp).
Feel free to test and come back to us if needed.
