### ISSUE TITLE
[apps::vmware::connector::plugin] option to filter VM OS name

### ISSUE THREAD

**Issue by gmicas** [centreon/centreon-plugins#1229]
Hello,

I've added an option to the `apps::vmware::connector::plugin --mode=vm-tools` for it to be able to filter VM OS name (config.guestFullName) and not just "description" like option `--filter-description`, which is already used for another purpose.

I already added it to my test server and it worked, but i would like to put this option in an offical way into this plugin (no upgrade and version issues).

Please find the attached files bellow (cmdtoolsvm.pm & toolsvm.pm).

Thank you very much

[toolsvm_with_os_filter.zip](https://github.com/centreon/centreon-plugins/files/2597067/toolsvm_with_os_filter.zip)

**Comment by Sims24** [comment]
Hello, 

Thanks ! Great to get some contributions on this. 

Could you submit this as a PR please ? It will be easier for us to review the change. 

We'll try to take a look soon as theses plugins and modes become old and need some code update :)

**Comment by garnier-quentin** [comment]
Will be add in centreon-vmware 3.0.0
