### ISSUE TITLE
[apps::vmware::connector::plugin] - Add a list-hosts mode

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1234]
Hi,

like as list-datacenters or list-datastores, can you add a mode list-hosts and implement disco-show and disco-format for integration in auto-disco rules?

thanks,

**Comment by cgagnaire** [comment]
Hi @cmeschin,
We are working on something that goes beyond that and will look like a host discovery.
It will answer this exact need.
So we will not do such a mode for now.
