### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by spiralemystik** [centreon/centreon-plugins#1235]
https://github.com/centreon/centreon-plugins/blob/f70e29f4bc056909c43e2a1b8089ca89233119c6/hardware/server/huawei/ibmc/snmp/mode/hardware.pm#L102
components instead of compenents

**Comment by cgagnaire** [comment]
Fixed by https://github.com/centreon/centreon-plugins/commit/277a4937625334695e465125ce08875f14eee373
