### ISSUE TITLE
[apps::protocols::dhcp::plugin] No DHCPOFFERs were received as user centreon-engine

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon-plugins#1239]
Hello,

When I used the plugin as the root user the plugin returns an OK state: **OK: DHCP Server found with free lease | 'time'=1.002ms;;;;**

But when I switched to the user centreon-engine, it doesn't work: **CRITICAL: No DHCPOFFERs were received |**

**Comment by Sims24** [comment]
Hi @Crash-Fox 

Not sure but could you try to set sticky bit on the plugin binary please. 

Thansk

**Comment by Crash-Fox** [comment]
Hi @Sims24 

How can I set the sticky bit on the plugin ? Did I have to set it on the command or the source code ?

**Comment by garnier-quentin** [comment]
You need to setuid the file. But you shouldn t do it if you don t use fatpack system. Otherwise to setuid:
```
# chown root:root file.pl
# chmod 4755 file.pl
```

**Comment by garnier-quentin** [comment]
You can open it if you still have the issue.
