### ISSUE TITLE
Net-Stormshield-SNMP-custom - Templates de services Netasq - :(

### ISSUE THREAD

**Issue by DidierDASE** [centreon/centreon-plugins#1245]
Le template d'hôte "Net-Stormshield-SNMP-custom" installé par le plugin-pack Stormshiel-SNMP contient des relations avec des templates de services Netasq (cf. copie d'écran).

![image](https://user-images.githubusercontent.com/45428210/49157210-84a8f080-f31f-11e8-9775-023edee48929.png)

Est-ce volontaire ou une erreur ?

Cordialement,

Didier MOUSSEAU

**Comment by Sims24** [comment]
Bonjour Didier, 

Merci de la remontée. Nous allons ouvrir ce ticket sur la bonne forge en interne car elle concerne les plugin-packs. 

Tu peux ouvrir un ticket au support, nous te ferons parvenir les instructions pour corriger par ce biais.

Merci,
Simon
