### ISSUE TITLE
[database::oracle::plugin] Check Oracle Tablespace-usage

### ISSUE THREAD

**Issue by Erawor** [centreon/centreon-plugins#1247]
Hello,
Can you help me, please. I can't check the TableSpace usage from the Centreon web interface.

Works from centreon server : 
```
[root@centreon plugins]# ./centreon_plugins.pl --plugin=database::oracle::plugin --mode=tablespace-usage --hostname=AIX_SERVER --port=1521 --sid=SID --username=USER --password=PWD
OK: All tablespaces are OK | ....
```
But from Centreon interface 

 **UNKNOWN:  Cannot connect: ERROR OCIEnvNlsCreate. Check ORACLE_HOME (Linux) env  var  or PATH (Windows) and or NLS settings, permissions, etc.**

```
[root@centreon plugins]# echo $ORACLE_HOME
/home/oracle/12.2/client64
```
.bash_profile for root and oracle user)

export LD_LIBRARY_PATH=/home/oracle/12.2/client64/lib:$LD_LIBRARY_PATH
export TNS_ADMIN=/home/oracle/12.2/client64/network/admin
export ORACLE_HOME=/home/oracle/12.2/client64
export NLS_LANG=FRENCH_FRANCE.WE8ISO8859P1
PATH=$PATH:$HOME/bin:$ORACLE_HOME/bin

export PATH

Command line :
/usr/lib/centreon/plugins/centreon_plugins.pl
	--plugin=database::oracle::plugin
	--mode=tablespace-usage
	--hostname=AIX_SERVER
	--sid=SID
	--port=1521
	--sqlmode=dbi
	--username=USER
	--password=PWD
	--warning-tablespace=90
	--critical-tablespace=95

an idea please ? thanks

**Comment by CPbN** [comment]
`centreon_plugins.pl` will be fired by `centreon-engine` user, not `root` or `oracle`.
I then guess `centreon-engine` must have Oracle env properly declared.

**Comment by Erawor** [comment]
Thanks you for help @CPbN 
it's done too 

```
root@centreon>su - centreon-engine
centreon-engine@centreon> echo $ORACLE_HOME
/home/oracle/12.2/client64
centreon-engine@centreon>

```
same oracle bash_profile for user centreon-engine (/var/lib/centreon-engine)

I still have the same problem from centreon web (same result with Nagios plugins too check_oracle_tbs).

any other adea please ?
