### ISSUE TITLE
Cisco DNAC API plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1251]
Hi,

Can you please create a plugin for Cisco DNAC API?
It is completely new solution from Cisco, so there are no good plugins for it.
As I have test environment up and running then I can help with testing.

We are specially interested in getting the device status info/interfaces etc from the Network Device part.

More info from:
https://developer.cisco.com/docs/dna-center-api-1-2/
https://developer.cisco.com/docs/dna-center-api-1-0/
https://developer.cisco.com/docs/dna-center/#!cisco-dna-center-platform-overview/intent-api

If you have any questions, let me know.

**Comment by garnier-quentin** [comment]
What do you want to monitor (api method and values in return) ? Do you know how to paginate ? (don't find information about it)
