### ISSUE TITLE
[network::riverbed::steelhead::snmp::plugin mode::load-average]

### ISSUE THREAD

**Issue by Altagot** [centreon/centreon-plugins#1256]
Hi,

There is a bug concerning the load average.
It seems in the MIB that :
cpuLoad1 is .1.3.6.1.4.1.17163.1.1.5.1.1.0
cpuLoad5 is .1.3.6.1.4.1.17163.1.1.5.1.2.0
cpuLoad15 is .1.3.6.1.4.1.17163.1.1.5.1.3.0
and cpuUtil1 is .1.3.6.1.4.1.17163.1.1.5.1.4.0

In the script,
cpuUtil is .1.3.6.1.4.1.17163.1.1.5.1.1.0
cpuLoad1 is .1.3.6.1.4.1.17163.1.1.5.1.2.0
cpuLoad5 is .1.3.6.1.4.1.17163.1.1.5.1.3.0
cpuLoad15 is .1.3.6.1.4.1.17163.1.1.5.1.4.0

I didn't check about the ex_Oid it seems to have in the script as I only have new Riverbed.
There is one more thing about cpuLoad1, cpuLoad5 and cpuLoad15 : the value are in hundreths.
So it need to be divided by 100 to have a value as usual.
With the actual script, we have value as 125 instead of 1.25.

Thanks

**Comment by Sims24** [comment]
Hi @Altagot 

We will fix this. Thanks for your contribution.
