### ISSUE TITLE
Incorrect use of get_params in centreon::plugins:http

### ISSUE THREAD

**Issue by ypilpre** [centreon/centreon-plugins#1260]
Hello 

In centreon/plugins/http.pm, in request sub, the use of get_params cannot be set by $request_options because it is defined by the class, and not forwarded trough request options : 

line 204
`my $uri = URI->new($url);
    if (defined($self->{get_params})) {
        $uri->query_form($self->{get_params});
    }`

I replaced it by 

`    my $uri = URI->new($url);
    if (defined($request_options->{get_params})) {
        $uri->query_form($request_options->{get_params});
    }`

Do you confirm this ?

Regards, 

Yann.

**Comment by Sims24** [comment]
Hi @ypilpre , 

As we worked together on this. Closing this issue. 

Regds
