### ISSUE TITLE
Broker-retension plugin 

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1271]
Hi,

After last update my Broker-retension service broke.
I get error:
UNKNOWN: '': not a file or cannot be read - '': not a file or cannot be read

Command itself is : /usr/lib/centreon/plugins/centreon_centreon_central.pl
	--plugin=apps::centreon::local::plugin
	--mode=retention-broker
	--broker-config=''
	--broker-config=''
	--verbose

And I see that the broker-config should come from Host configuration:
$CENTREONPLUGINS$/centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --mode=retention-broker --broker-config='$_HOSTRRDCFGFILE$' --broker-config='$_HOSTSQLCFGFILE$' $_SERVICEEXTRAOPTIONS$

So what is the correct paths, that I need to configure as HOSTRRDCFGFILE and HOSTSQLCFGFILE?

**Comment by Sims24** [comment]
Hello Kadrika,

This mode is deprecated now. Please use broker-stats instead. 

Thanks

**Comment by cgagnaire** [comment]
Hi @kadrika,
As @Sims24 said, you must use broker-stats mode for Broker > 2.x
