### ISSUE TITLE
[os::linux::snmp::plugin] How to calculate traffic bandwidth?

### ISSUE THREAD

**Issue by alexander-naumov** [centreon/centreon-plugins#1274]
Hello,

it's a very general question actually, but I use centreon plugins and maybe developers (or something else) can help me here.

I try to figure out how linux script calculate traffic bandwidth. It looks like snmpd provides ifInOctets and ifOutOctets values, but these values are growing all the time... so, to be able to calculate traffic, say, in the last 5 mins, I need "to save" old value and use it by the next check time (delta calculation, like described, for example, here https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/8141-calculate-bandwidth-snmp.html). During the first run linux_check returns something like "Buffer caching" in output and not the values itself.

So, my question is - what is the best way to do it by using some check script? Do I really need to save these values all the time? Maybe snmpd provides some more intelligent way for traffic bandwidth calculating?

Thank you very much for any details and info,
Alex

**Comment by Sims24** [comment]
Hi @alexander-naumov 

Not sure I totally understand what you try to achieve here. 

Actually you're right, the OIDs are counter type so increasing over the time until they reach their maximum value and loop to 0. (Or when you reboot the equipment).

You are using measured value + last value at each check, as you do not have the last value during the fist check, you can't avoid the buffer creation message.

Hope this help,

**Comment by alexander-naumov** [comment]
Thanks @Sims24!

But maybe you can provide a bit more technical details, please? This script is about 10.000 lines of Perl code... Where is cache will be saved? Or maybe there is somewhere developer documentation for this script?

**Comment by Sims24** [comment]
Sure, 

You have some options to manage the cache, all cache related things like reading/writing from the disk is handle by the statefile library => https://github.com/centreon/centreon-plugins/blob/master/centreon/plugins/statefile.pm 

As you can see, there is some options all modes inherit from it, like the cache directory and an optionnal suffix (you can display these options through --help) : 

```=item B<--statefile-dir>
Directory for statefile (Default: '/var/lib/centreon/centplugins').
=item B<--statefile-suffix>
Add a suffix for the statefile name (Default: '').``` 

Cache name is generated from an md5 of several informations (host IP, plugin options, mode name ..).

Regarding the interfaces.pm mode, it relies on the standard MIB specifications (all system mibs and network devices use this same code base for bandwidth monitoring). As described in the RFC 1155 and as mentionned previously, ifInOctets and ifOutOctets values are counters : 

> 3.2.3.3.  Counter
> 
>    This application-wide type represents a non-negative integer which
>    monotonically increases until it reaches a maximum value, when it
>    wraps around and starts increasing again from zero.  This memo
>    specifies a maximum value of 2^32-1 (4294967295 decimal) for
>    counters.

You can now often see some ifHCInOctets, ifHCOutOctets with a maximum value of 2^64-1, so-called 64-bits counters. 

The logic in the interfaces.pm mode is : 

1. Getting counter value (store in memory)
   > Trying to catch the actual counter value from ifHCInOctets, ifHCOutOctets, if not available it failbacks to ifInOctets and ifOutOctets. 

2. Getting the associated timestamp (store in memory) 

3. Try to read the cache file (r/w on disk,  but can also be a redis or memcached server for performance purpose) : 
   > if it exists, compute the bandwidth as described in the link you provided (delta between last and running execution vs time)
   > if it does not exist, create it and store timestamp + counter value for each interface checked 

4. Display the bandwith usage in uom/s and percentage if a speed is defined for the port or through specific option (`--speed-in --speed-out`) 

Not sure the answer is enough accurate for you, especially if your wish is to enhance the mode. We can go deeper in the code if needed, but clearly this is 10 000 lines of perl and as no very precise documentation exists at this stage this is the quick n' dirty explanation I can provide for now.

**Comment by alexander-naumov** [comment]
Thanks a lot!
