### ISSUE TITLE
[network::f5::bigip:snmp::plugin] Adding a new OID to monitor in connections mode

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon-plugins#1275]
## New OID to monitor in the connections mode

Is it possible to add the monitoring of the OID Active Sessions on the mode connections of the F5-BigIP plugin ? It could help to have a more detailed view about the current users that are really connected through the F5 server.

Here is the snmpget command that I use to have this value:
`snmpget -v2c -cpublic <F5-Server> 1.3.6.1.4.1.3375.2.6.1.4.3.0 `

The OID to query is on the same MIB branch (**1.3.6.1.4.1.3375**) as the other OID in the mode connections:

my $oid_sysStatClientCurConns = '.1.3.6.1.4.1.**3375**.2.1.1.2.1.8.0';
my $oid_sysStatServerCurConns = '.1.3.6.1.4.1.**3375**.2.1.1.2.1.15.0';
my $oid_sysClientsslStatCurConns = '.1.3.6.1.4.1.**3375**.2.1.1.2.9.2.0';
my $oid_sysServersslStatCurConns = '.1.3.6.1.4.1.**3375**.2.1.1.2.10.2.0';
my $oid_sysClientsslStatTotNativeConns = '.1.3.6.1.4.1.**3375**.2.1.1.2.9.6.0';
my $oid_sysClientsslStatTotCompatConns = '.1.3.6.1.4.1.**3375**.2.1.1.2.9.9.0';
**my $oid_sysActiveSessions = '.1.3.6.1.4.1.3375.2.6.1.4.3.0';**

**Comment by garnier-quentin** [comment]
Sorry but that OID is for BigIpApm product (Access Policy Manager). It's not the same meaning. 
We can add plugin for that product. Do you have a snmpwalk ?

**Comment by Crash-Fox** [comment]
Hello @garnier-quentin,

A snmpwalk on which tree:

- **1.3.6.1.4.1.3375.***

**Comment by garnier-quentin** [comment]
Everything: .1

**Comment by Crash-Fox** [comment]
Here is the file containing the output of the snmpwalk command of a F5 equipment on the .1 OID
[outputSnmpwalkF5.txt](https://github.com/centreon/centreon-plugins/files/3012496/outputSnmpwalkF5.txt)

**Comment by Crash-Fox** [comment]
Hello @garnier-quentin 

Do you have any news on this issue.

**Comment by garnier-quentin** [comment]
Sorry for the delay. Do you have a snmpwalk with some usage ? Because all counters = 0 in your walk.

**Comment by Crash-Fox** [comment]
Hello,

Thanks for answering my issue even after so long :)

What do you mean all counters = 0. I admit there are some at 0 but there are a lots that aren't equal to 0 :

- **SNMPv2-SMI::enterprises.3375.2.1.1.1.1.7.0 = Gauge32: 95**
- **SNMPv2-SMI::enterprises.3375.2.1.1.1.1.8.0 = Gauge32: 85**
- **SNMPv2-SMI::enterprises.3375.2.1.1.1.1.9.0 = INTEGER: 1**
- **SNMPv2-SMI::enterprises.3375.2.1.1.1.1.10.0 = INTEGER: 0**
- **SNMPv2-SMI::enterprises.3375.2.1.1.1.1.11.0 = INTEGER: 0**

Do you want me to provide a snmpwalk made on a different F5 machine ? Or a snmpwalk on a different OID path ?

**Comment by garnier-quentin** [comment]
Could you send me a new complete snmpwalk (on my email) ?

**Comment by Crash-Fox** [comment]
Hello,

I've send you the complete output (_TXT file_) of a snmpwalk command on one of my F5 equipment.

**Comment by garnier-quentin** [comment]
You can test with last version (--mode=apm). Tell me if it's ok for you.

**Comment by Crash-Fox** [comment]
It's all good for me.

Thank you 👍

**Comment by garnier-quentin** [comment]
thanks for the feedback!
