### ISSUE TITLE
[database::mysql::plugin] --mode=threads-connected

### ISSUE THREAD

**Issue by jdidierpichat** [centreon/centreon-plugins#1278]
Hi,

I propose an evolution of threads-connected mode using by plugin [database::mysql::plugin]
It will be fine to add a ratio instead of a number.

for this, it's necessary to modify the request 
SHOW /*!50000 global */ STATUS LIKE 'Threads_connected'

by

SELECT @@GLOBAL.max_connections INTO @maxcon;
SELECT VARIABLE_VALUE FROM performance_schema.session_status WHERE VARIABLE_NAME='Threads_connected' INTO @threadcon;
SELECT @threadcon*100/@maxcon;

**Example:**  

> mysql> SELECT @@GLOBAL.max_connections INTO @maxcon;
> Query OK, 1 row affected (0.00 sec)
 
> mysql> SELECT VARIABLE_VALUE FROM performance_schema.session_status WHERE VARIABLE_NAME='Threads_connected' INTO @threadcon;
> Query OK, 1 row affected (0.00 sec)
>  
> mysql> SELECT @threadcon*100/@maxcon;
> +------------------------+
> | @threadcon*100/@maxcon |
> +------------------------+
> |     0.6622516556291391 |
> +------------------------+
> 1 row in set (0.00 sec)

**Comment by jdidierpichat** [comment]
Hello,

Any news ? I'm trying to code the new plugins without success.... :(

**Comment by garnier-quentin** [comment]
I have done a fix. Could you test it ?
