### ISSUE TITLE
[network::fortinet::fortigate::plugin] admin status

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon-plugins#1279]
Hello,
I use the fortigate plugin in order to automatically add the interfaces of my Fortigates with the autodiscovery.

It's ok, but know you if it's possible to insert the admin-status in the "list-interfaces" mode (disco-show)?
That permit to filter by the admin status in the autodiscover rule.

The interfaces with a down admin status, are not necessary to be added.

Thanks

**Comment by garnier-quentin** [comment]
You can use that option to get admin status:
```
--add-extra-oid=adminstatus,.1.3.6.1.2.1.2.2.1.7
```

If you want to display interface with admin status up:
```
--use-adminstatus
```
