### ISSUE TITLE
HP Storevirtual VSA check

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1287]
It should be fine to monitor HP StoreVirtual VSA through the Web Rest API:

- https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-c04581876
- https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-a00004048en_us

**Comment by garnier-quentin** [comment]
Already open here: #1176

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md)).

Thank you for your understanding.
