### ISSUE TITLE
[network::barracuda::cloudgen::snmp::plugin] Global symbol requires explicit package name

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1319]
Hello guys,

I have cloned the plugins repository to my system and now I get the following error when I try to check my Barracuda Firewall.

> centreon_plugins.pl --plugin=network::barracuda::cloudgen::snmp::plugin --mode=server-service --hostname=xxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='public' --verbose

```
Global symbol "$msg" requires explicit package name at /usr/lib/nagios/plugins/centreon/plugins/snmp.pm line 336.
Compilation failed in require at /usr/lib/nagios/plugins/centreon/plugins/script_snmp.pm line 25.
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins/centreon/plugins/script_snmp.pm line 25.
Compilation failed in require at /usr/share/perl/5.20/base.pm line 135.
        ...propagated at /usr/share/perl/5.20/base.pm line 157.
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins/network/barracuda/cloudgen/snmp/plugin.pm line 25.
Compilation failed in require at /usr/lib/nagios/plugins/centreon/plugins/misc.pm line 221.

```
I have aleso tried other checks and also checking other systems. For example a QNAP storage. It's always the same error. Does anyone know how to solve it? I have other poller which are working fine with the same configuration. What's the diefference here?

Thank you very much.

Best regards, Michael

**Comment by garnier-quentin** [comment]
I have done a mistake in a commit. Please update and it should be ok ;). my bad.

**Comment by MikeW83** [comment]
Perfect. It's working now.
