### ISSUE TITLE
SahiPro End-2-End monitoring

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1321]
Hi,

Could you please create a Centreon plugin for SahiPro End2End monitoring scenarios?
Selenium is very hard to configure and most importantly - very unreliable and has lot of issues, but SahiPro is very easy to configure and maintain.

**Comment by garnier-quentin** [comment]
Why not kadrika. But we don't have a license.

**Comment by kadrika** [comment]
You can ask them for demo license.

**Comment by garnier-quentin** [comment]
It seems there is no perl binding.
```
Sahi Script, Java, Ruby Sahi Script has the syntax of javascript but can interoperate with any Java code directly from script. The Java/Ruby drivers are available since Sahi V3
```

So i can't add it.

**Comment by kadrika** [comment]
https://sahipro.com/docs/sahi-apis/rest-apis.html

**Comment by kadrika** [comment]
https://crm.sahipro.com/pay/index.php/registration/register Free trial can be downloaded from here. And if you want we have test server up and running and we can demonstrate it to you @garnier-quentin

**Comment by garnier-quentin** [comment]
Can be interesting to show me directly.

**Comment by kadrika** [comment]
I will send you meeting link. Do yo have time right now?
