### ISSUE TITLE
Automatically fill --plugin= with Fatpack plugins

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1323]
Hi,

When using Fatpack plugins, we still must use `--plugin=`, as without, it may produce errors.
For example :
`os-linux-snmp.pl --plugin=os::linux::snmp::plugin --mode=...`
`--plugin` is quite redundant / useless here.
Could it then be possible, when Fatpack plugins are used, to automatically / internally force `--plugin` option ?

Thank you :+1:

**Comment by pkriko** [comment]
Hello :)

If you are using fatpack plugin, you are not forced to precise the path of the plugin :

`[centreon@pkr-central ~]$ /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin --mode cpu --hostname=127.0.0.1
OK: 1 CPU(s) average usage is 7.00 % - CPU '0' usage : 7.00 % | 'total_cpu_avg'=7.00%;;;0;100 'cpu'=7.00%;;;0;100
`

**Comment by CPbN** [comment]
Here is an example :
```
$ ./os-linux-snmp.pl --mode=cpu --help

Usage:
    centreon_plugins.pl [options]

Options:
    --plugin
            Specify the path to the plugin.

    --list-plugin
            Print available plugins.

    --version
            Print global version.

    --help  Print a brief help message and exits.

    --ignore-warn-msg
            Perl warn messages are ignored (not displayed).

    --runas Run the script as a different user (prefer to use directly the
            good user).

    --environment
            Set environment variables for the script (prefer to set it
            before running it for better performance).

    --convert-args
            Change strings of arguments. Useful to use '!' in nrpe protocol.
            Example: --convert-args='##,\x21'
```

Without `--plugin=os::linux::snmp::plugin`, plugin's help is not given.
I think I've faced other cases where `--plugin` was required, but I would have to find them back :)

**Comment by garnier-quentin** [comment]
I cannot solve that issue. It's by design. The help is contextual. I cannot guess which help to display.
In script.pm
```
    if (defined($self->{help}) && !defined($self->{plugin})) {
        $self->display_local_help();
        $self->{output}->option_exit();
    }
```

**Comment by CPbN** [comment]
Thank you for your answer @garnier-quentin.
I would have thought we could have done the following :
if FatPack is detected, and if `--plugin` option is empty, then automatically set `--plugin` to the only available plugin.

**Comment by garnier-quentin** [comment]
It's done. But the problem is the help message without --plugin. 
In your fatpack, you should set following variable
```
$alternative_fatpacker = 1
```

**Comment by CPbN** [comment]
Understood, thank you :+1:
