### ISSUE TITLE
Improve --filter efficiency ?

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1332]
Hi,

As an example, let's take  :
`--plugin=storage::netapp::snmp::plugin --mode=filesys --filter-name='^/vol/test/$'`

Sounds like plugin :
- get the list of filesystems from the device ;
- get the info from the device for every filesystem of the list ;
- filters out requested filesystem(s) info.

Think about a device with dozens (even hundreds !) of filesystems.
Could it be more effective in terms of traffic, workload... to perform the following ?
- get the list of filesystems from the device ;
- filters out requested filesystem(s) from the list ;
- get the info from the device for every filtered-out filesystem.

Would it be worth it ?

I think about devices where I have to set one Centreon service per filesystem (to be sure to get a specific alert for every filesystem independently).
For every filesystem, all info is collected from the device, which seems painful.

Of course I think this is true for almost every plugin where `--filter*` is available...

Many thanks !

**Comment by garnier-quentin** [comment]
It depends of the mode. Some modes are old and cannot use new methods from SNMP. It can depend of the context also.
