### ISSUE TITLE
[apps::elasticsearch::restapi::mode::nodes] Node roles naming

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#1341]
The node roles in plugin are searched with names master_only, data_only , master_data but ES' doc states that this roles have been removed in favor of master, data, ingest and coordinating_only after 5.1 release.

See https://www.elastic.co/guide/en/elasticsearch/reference/5.1/breaking_50_rest_api_changes.html#_revised_node_roles_aggregate_returned_by_literal__cluster_stats_literal

jfr

**Comment by cgagnaire** [comment]
Hi @jframeau,
The plugin has been refactored and move to the database tree.
It shoud work for version 5, 6 and 7.
