### ISSUE TITLE
Add possibility to check RAID  on firewall CheckPoint

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#1346]
Hi,

It's possible to add possibility to check RAID  on firewall check point ?

MIB available here 

 MIB available on CheckPoint where informations about RAID are : 

https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk90470

Best regards,

**Comment by garnier-quentin** [comment]
We already check raid for checkpoint.

**Comment by garnier-quentin** [comment]
Need more information.
