### ISSUE TITLE
[network::fortinet::fortigate::plugin] cluster-status syntax

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#1349]
Hi,

I have a problem creating a [network::fortinet::fortigate::plugin] cluster-status critical-status command.
I have host FW1 and host FW2 
I need to check that host FW1 has role master and host named FW2 has role slave. 

I tried like this:
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network/fortinet/fortigate/plugin.pm --mode=cluster-status --hostname=1.1.1.1 --snmp-community=newyear --snmp-version=2c --verbose --critical-status='%{sync_status} !~ /synchronized/' --critical-status='%{role} !~ /master/','%{hostname} =~ /FW1' --critical-status='%{role} !~ /slave/','%{hostname} !~ /FW2'
But I get error:
OK: HA mode: activePassive - All cluster nodes status are ok |
filter status issue: Search pattern not terminated at (eval 12) line 1.

**Comment by garnier-quentin** [comment]
Something like that:
```
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network/fortinet/fortigate/plugin.pm --mode=cluster-status --hostname=1.1.1.1 --snmp-community=newyear --snmp-version=2c --verbose --critical-status='%{sync_status} !~ /synchronized/' --critical-status='(%{role} !~ /master/ and %{hostname} =~ /FW1/) or (%{role} !~ /slave/ and %{hostname} =~ /FW2/)'
```

**Comment by kadrika** [comment]
Thanks!
Perfectly working as always!

**Comment by garnier-quentin** [comment]
Thanks. You're welcome.
