### ISSUE TITLE
os::linux::snmp::plugin mode storage : Threshold on % and/or B

### ISSUE THREAD

**Issue by guillaumewatteeux** [centreon/centreon-plugins#135]
Hi,

It's possible to add a possibility to check a storage with percents and Bites (free)? 

For example: 
Warning on 80% (used) and <15go free space
Critical on 90% (used) and < 8go free space

For large storage, it's difficult to adjust threshold after resizing disk

Thanks

**Comment by garnier-quentin** [comment]
Hi Guillaume,

Right now, it won't be. Need a big refactoring to do that. Already done it for interfaces and http. We wait a little ;)

**Comment by garnier-quentin** [comment]
I add it in the following ticket:  https://github.com/centreon/centreon-plugins/issues/79
