### ISSUE TITLE
Unsuitable usage for plugins windows, mysql, linux

### ISSUE THREAD

**Issue by OpensourceMonitoringRepository** [centreon/centreon-plugins#1350]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
Centreon 2.8 AND centreon 18.10
**Centreon Engine version**: 
Centreon Engine 1.8.1 AND Centreon Engine 18.10.0
**Centreon Broker version**: 
Centreon Broker 3.0.16 AND Centreon Broker 18.10.0
**OS**: 
Centos 7
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWARE
**Steps to reproduce the issue:**
1./usr/lib/centreon/plugins/**centreon_windows_snmp.pl** --mode=interfaces --help
**Describe the results you received:**
Usage:
    **centreon_plugins.pl [options]**

Options:
    --plugin
            Specify the path to the plugin.

    --list-plugin
            Print available plugins.

    --version
            Print global version.

    --help  Print a brief help message and exits.

    --ignore-warn-msg
            Perl warn messages are ignored (not displayed).

    --runas Run the script as a different user (prefer to use directly the
            good user).

    --environment
            Set environment variables for the script (prefer to set it
            before running it for better performance).

    --convert-args
            Change strings of arguments. Useful to use '!' in nrpe protocol.
            Example: --convert-args='##,\x21'

**Describe the results you expected:**
Usage of this mode

**Additional information you think important (e.g. issue happens only occasionally):**
same usage for all mode

**Comment by cgagnaire** [comment]
Hi @OpensourceMonitoringRepository,
Please add --plugin option on your command lines.
Thanks.
