### ISSUE TITLE
[database::oracle::plugin]  environnement variable

### ISSUE THREAD

**Issue by LLFT** [centreon/centreon-plugins#1351]
Hello,

I have a problem with the following command:

`/usr/lib64/nagios/plugins/centreon_plugins.pl.bak --plugin=database::oracle::plugin --dyn-mode=database::oracle::mode::tablespaceusage --hostname=10.61.11.2 --port=1521 --sid=PCTD --username=totot --password=toto --filter-tablespace=RECIDX --warning-tablespace=90 --critical-tablespace=93`

When I run it in command line with root and centreon-engine no problem.

But as soon as I launch it from Centreon I get:

> UNKNOWN: install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntsh.so.18.1: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type at /usr/lib64/perl5/DynaLoader.pm line 190. at (eval 10) line 3.Compilation failed in require at (eval 10) line 3.Perhaps a required shared library or dll isn't installed where expectedat /usr/lib64/nagios/plugins/centreon/plugins/dbi.pm line 210.

I know the problem is that centreon-engine from centreon does not access the variable ** $ ORACLE_HOME ** and ** $ LD_LIBRARY_PATH **.

However, I declared the variables in all the files that seemed to allow me to load the variables nothing made.

 cat /etc/environment
```
LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib/
ORACLE_HOME=/usr/lib/oracle/18.3/client64/
```

cat /var/lib/centreon-engine/.bash_profile
```
# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export ORACLE_HOME='/usr/lib/oracle/18.3/client64/'
export LD_LIBRARY_PATH='/usr/lib/oracle/18.3/client64/lib/'
export PATH
```

Do you have another idea?

Thank you in advance.
==================================

Bonjour,

J'ai un problème avec la commande suivante : 

`/usr/lib64/nagios/plugins/centreon_plugins.pl.bak --plugin=database::oracle::plugin --dyn-mode=database::oracle::mode::tablespaceusage --hostname=10.61.11.2 --port=1521 --sid=PCTD --username=toto --password=totot --filter-tablespace=RECIDX --warning-tablespace=90 --critical-tablespace=93`

Lorsque je l’exécute en ligne de commande avec root et centreon-engine aucun problème.

Mais dès que je la lance depuis Centreon j'obtiens : 

> UNKNOWN: install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntsh.so.18.1: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type at /usr/lib64/perl5/DynaLoader.pm line 190. at (eval 10) line 3.Compilation failed in require at (eval 10) line 3.Perhaps a required shared library or dll isn't installed where expectedat /usr/lib64/nagios/plugins/centreon/plugins/dbi.pm line 210.

Je sais que le problème vient du fait que centreon-engine depuis centreon n'accède pas à la variable **$ORACLE_HOME** et **$LD_LIBRARY_PATH**.

J'ai pourtant déclaré les variables dans tout les fichiers qui me semblait permettre de charge les variables riens n'y fait.

 cat /etc/environment
```
LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib/
ORACLE_HOME=/usr/lib/oracle/18.3/client64/
```

cat /var/lib/centreon-engine/.bash_profile
```
# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export ORACLE_HOME='/usr/lib/oracle/18.3/client64/'
export LD_LIBRARY_PATH='/usr/lib/oracle/18.3/client64/lib/'
export PATH
```

Auriez vous une autre idée ?

Merci d'avance.

**Comment by garnier-quentin** [comment]
You can add the library in your ld.so.conf.d. Otherwise, you can use following options:
```
--environment="ORACLE_HOME=/usr/lib/oracle/18.3/client64/" --environment="LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib/"
```

**Comment by LLFT** [comment]
Great, I added the path of the library in / etc / ld.so.conf.d / oracle.conf then delete my variables in / etc / envirronement and it works.

Yet I get the message (service check did not exit properly) in the center and the following return from the command:

`Statut détaillé | OK: Tablespace 'recdat' Total: 29.30 GB Used: 13.14 GB (44.86%) Free: 16.15 GB (55.14%) \| 'tbs_recdat_usage'=14112784384B;0:28311552000;0:29255270400;0;31457280000`
`Statut | INCONNU`


an idea ?

-------------------------------------


Génial, J'ai rajouté le chemin de la bibliothèque dans  /etc/ ld.so.conf.d/oracle.conf puis supprimer mes variables dans /etc/envirronement et cela fonctionne. 

Pourtant j'obtiens le message 	(Service check did not exit properly) sous centreon et le retour suivant depuis la commande :

`Statut détaillé | OK: Tablespace 'recdat' Total: 29.30 GB Used: 13.14 GB (44.86%) Free: 16.15 GB (55.14%) \| 'tbs_recdat_usage'=14112784384B;0:28311552000;0:29255270400;0;31457280000`
`Statut | INCONNU`

Une idée ?

**Comment by garnier-quentin** [comment]
I don't understand the output. Could you give us the command and the output from a shell ?

**Comment by LLFT** [comment]
With only  **/etc/ld.so.conf.d/oracle.conf** 

Ligne de commande :
`/usr/lib64/nagios/plugins/centreon_plugins.pl.bak --plugin=database::oracle::plugin --dyn-mode=database::oracle::mode::tablespaceusage --hostname=10.61.11.2 --port=1521 --sid=PCTD --username=totot --password=toto --filter-tablespace=RECIDX --warning-tablespace=90 --critical-tablespace=93
`
Statut détaillé :
` OK: Tablespace 'recdat' Total: 29.30 GB Used: 13.14 GB (44.86%) Free: 16.15 GB (55.14%) \| 'tbs_recdat_usage'=14112784384B;0:28311552000;0:29255270400;0;31457280000
`
Statut :
` INCONNU`

---

With **/etc/ ld.so.conf.d/oracle.conf** and parameters **--environment=**

Ligne de commande :
`/usr/lib64/nagios/plugins/centreon_plugins.pl.bak --plugin=database::oracle::plugin --dyn-mode=database::oracle::mode::tablespaceusage --hostname=10.61.11.2 --port=1521 --sid=PCTD --username=totot --password=toto --filter-tablespace=RECIDX --warning-tablespace=90 --critical-tablespace=93  --environment="ORACLE_HOME=/usr/lib/oracle/18.3/client64/" --environment="LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib/"
`
Statut détaillé :
` OK: Tablespace 'recdat' Total: 29.30 GB Used: 13.14 GB (44.86%) Free: 16.15 GB (55.14%) \| 'tbs_recdat_usage'=14112784384B;0:28311552000;0:29255270400;0;31457280000
`
Statut:
` Ok
`

---

cat /etc/ld.so.conf.d/oracle.conf

`/usr/lib/oracle/18.3/client64/lib/`

**Comment by garnier-quentin** [comment]
I see status OK. You get the status with '$?' variable or from centreon interface ?

**Comment by LLFT** [comment]
Both statuses are obtained with the centreon interface, only the environment parameter differs them.

More precisely from the menu: main.php?P=60801&type=2

**Comment by garnier-quentin** [comment]
What do you have with command line in a shell ?

**Comment by LLFT** [comment]
Thank you for your investment

So under the Shell we get the 2 status to OK:

`/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=database::oracle::plugin --dyn-mode=database::oracle::mode::tablespaceusage --hostname=10.61.11.2 --port=1521 --sid=PCTD --username=totot --password=toto --filter-tablespace=RECIDX --warning-tablespace=90 --critical-tablespace=93 --environment="ORACLE_HOME=/usr/lib/oracle/18.3/client64/" `

`OK: Tablespace 'recidx' Total: 20.00 GB Used: 8.08 GB (40.40%) Free: 11.92 GB (59.60%) | 'tbs_recidx_usage'=8674869248B;0:19327352832;0:19971597926;0;21474836480`


`/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=database::oracle::plugin --dyn-mode=database::oracle::mode::tablespaceusage --hostname=10.61.11.2 --port=1521 --sid=PCTD --username=totot --password=toto --filter-tablespace=RECIDX --warning-tablespace=90 --critical-tablespace=93 `

`OK: Tablespace 'recidx' Total: 20.00 GB Used: 8.08 GB (40.40%) Free: 11.92 GB (59.60%) | 'tbs_recidx_usage'=8674869248B;0:19327352832;0:19971597926;0;21474836480`

**Comment by garnier-quentin** [comment]
Have you tried with centreon-engine user ?

**Comment by jeremyit** [comment]
Same issue, ok in CLI with centreon-engine but failed in Web UI, I've done same thing wih environnement variables path ...
`UNKNOWN: install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntsh.so.11.1: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type at /usr/lib64/perl5/DynaLoader.pm line 190.`

**Comment by garnier-quentin** [comment]
Is it working with centreon-engine user ?

**Comment by jeremyit** [comment]
yes, it is.

**Comment by garnier-quentin** [comment]
there is something in ENV i think.

**Comment by jeremyit** [comment]
I fixed ENV everywhere, .bash_profile, /etc/environment, plugin with --environment, ld.so.conf.d , double check all path ... Not Working only in Webui. I've tried nagios plugin check_oracle_health which worked...

**Comment by garnier-quentin** [comment]
Do you use the perl connector ? Have you checked command option 'Enable shell' ?

**Comment by jeremyit** [comment]
With perl connector or not, with enable shell or not, Web ui give error

**Comment by jeremyit** [comment]
Ok it's fixed... After a reboot server... I don't really how...

**Comment by jeremyit** [comment]
ok found how to fix. Use in command 
--environment="ORACLE_HOME=
and
--environment="LD_LIBRARY_PATH=

If Removed; error is back
