### ISSUE TITLE
database::postgres mode replication-master-slave

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#1353]
Hi,

Is it possible to add replication mode on postgres chreck ?

Thanks,

**Comment by garnier-quentin** [comment]
What do you use ? Slony ?

**Comment by romsworld** [comment]
this method : https://wiki.postgresql.org/wiki/Streaming_Replicationql.org/wiki/Streaming_Replication

attention in version 9 and version 10 they are not the same tables to check

**Comment by romsworld** [comment]
Hi Quentin,

Could you add replication mode as explain in this script ?
https://public.dalibo.com/exports/formation/manuels/modules/h1/h1.handout.html

Thanks,
