### ISSUE TITLE
apps::protocols::http::plugin — do not add the port to the Host header when standard ports are used

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon-plugins#1354]
Hi,
I recently found that some misconfigured IIS servers seem to dislike `Host` headers which contain the server port.
The following command: `perl centreon_plugins.pl  --plugin apps::protocols::http::plugin --mode response --hostname xxxx --port 443 --proto https --warning 5 --critical 10 --urlpath / --debug ` sends `Host: xxxx:443` and causes a timeout on the server I was checking:

On the other hand, curl, even if I pass it an explicit port, for instance`https://xxxx:443`, strips the port number from the host header. This has apparently been part of the codebase for ages: https://github.com/curl/curl/commit/c44b10de41ffca204acf11f36093c24521119239

Since it took me a long time to find where curl and the plugin's behaviours differ, I think that it would be nice to strip the port from the URL if we use http on port 80 or https on port 443:
https://github.com/centreon/centreon-plugins/blob/e8291c754f4570a33a671d3ea8fed9a21638b275/centreon/plugins/http.pm#L234

I can make a PR if required.

I guess I could also file a LWP bug but I'm not sure they would be willing to change such an important package.

**Comment by cgagnaire** [comment]
Hi @sbraz,
Have you tried to not set port option in command line, which will not set port in URL ?
Thanks.

**Comment by sbraz** [comment]
I think that I tried and that it worked but when centreon executes the plugin, the port is set by a macro so I can't leave it out.
My point was that curl, even if I force ":443" in the URL, will remove it from the Host header.

**Comment by cgagnaire** [comment]
Yea I know, curl does lots of things we don't :)
@garnier-quentin what do you think ?
From my point, I don't see any Host header in LWP requests if not explicitly defined.
@sbraz this is a test you can do, add --header='Host:<your host>'

**Comment by sbraz** [comment]
@cgagnaire that's what I did as a workaround. Feels pretty ugly though.

**Comment by sbraz** [comment]
> Yea I know, curl does lots of things we don't :)

I agree that a monitoring plugin shouldn't aim at replacing curl :smile:. It just took me so long to find out why curl was working and not the monitoring plugin that I thought it might be worth trying to make it more intuitive for users.

**Comment by cgagnaire** [comment]
Yes sure, I'll wait for @garnier-quentin to pop up here.
Thanks.

**Comment by garnier-quentin** [comment]
Please set empty your macro in Centreon. And it will work.

**Comment by sbraz** [comment]
I didn't expect the argument parser to accept that. Maybe it's not worth changing the code. I'll let you close the issue in that case.
