### ISSUE TITLE
apps::protocols::http::plugin: --get-param does not work any more

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon-plugins#1355]
Hello @ypilpre @Sims24,
`--get-param` has been broken for all HTTP plugins since 204a77d1f2f6796280d66c4c1da014d28e7bbbd2 (PR #1263). GitHub plugins and everything that uses `get_param` are broken too.

I've looked at the code and I don't really understand how a `centreon::plugins::http` object's `get_param` (singular) is later turned into a hash and can be accessed via `$self->{get_params}` (plural) but that is the way it was supposed to be used.

For now, the easiest course of action is probably to revert the changes from a2cbadd73a590f1037dfe0bc23c3473e215ab5ae and make the OVH plugin use an array instead of a hash for `sms_arg` here:
https://github.com/centreon/centreon-plugins/blob/824d5ed5d10ab3c8c79ff66618441b1c2650cffb/notification/ovhsms/mode/alert.pm#L105

**Comment by garnier-quentin** [comment]
I have fixed it. Could you test it ?

**Comment by sbraz** [comment]
@garnier-quentin I can't test the OVH SMS thingy but this fixes the HTTP plugins.

**Comment by garnier-quentin** [comment]
Thank you :)

**Comment by sbraz** [comment]
@cgagnaire @garnier-quentin Out of curiosity can you tell me how `get_param` is turned into a hash and renamed to `get_params`?

**Comment by garnier-quentin** [comment]
It's in function 'check_options' from 'centreon::plugins::http'.

**Comment by sbraz** [comment]
Thanks, couldn't figure it out by grepping the source.
