### ISSUE TITLE
centreon_hp_ilo_xmlapi.pl NIC issue

### ISSUE THREAD

**Issue by BlackstormFirst** [centreon/centreon-plugins#1358]
Hi,

I'm using the latest Centreon release (18-10-5 from ovf) and the latest update for all plugins.

I have an issue with the plugin centreon_hp_ilo_xmlapi.pl and the NIC.

Actually my serveur have ethernet (4ports), fiber (2ports) and ILO (2ports) interfaces, that means, i currently have 8 available ports.

When i am using the plugin without filter i can see my 8 NIC to the result, but if i add a filter i cannot target a specific interface.

So when i add a filter like: --filter="nic,Port 1", that clear the result for all interface port 1 and only 5 ports are reported instead of 7 (probably because the key 'nic' target all interfaces).

I think the plugin should manage the interface id (or should add one) to filter correctly what we need.

Thanks for your next updates.

**Comment by garnier-quentin** [comment]
Could you give us the result with --debug option please ? (xml result)

**Comment by BlackstormFirst** [comment]
[export_ilo_plug.log](https://github.com/centreon/centreon-plugins/files/2791054/export_ilo_plug.log)

Hello,
Thanks for your reply,

Into the linked file, you have 2 exported command lines.
The first one is without filter, the second one have the filter.

You can clearly see with the 2nd, the filter skip all NIC with a port named "Port 1".
I just would like to exclude the fiber interface from the test, but actually all interfaces are only named 'nic'

I.e: "nic", should match all interfaces, "nic1" or "nic_1" shoudl match only the first interface id.

Thanks for your help.

**Comment by garnier-quentin** [comment]
Thank you. We are going to look soon.

**Comment by garnier-quentin** [comment]
Could you test it with the github version ?

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
