### ISSUE TITLE
nimble_snmp_plugin returns UNKNOWN: SNMP Table Request : Timeout

### ISSUE THREAD

**Issue by rob-ball** [centreon/centreon-plugins#1361]
I'm experiencing an issue with centreon_plugins.pl where some of my nimble storage arrays are returning UNKNOWN: SNMP Table Request : Timeout when requesting the volume_usage mode. global_stats mode works correctly, so we think it's not related to the SNMP credentials. 

One thing we noticed is that there are over 100 Volumes on this Nimble, All the others in our environment have less than 60.  

Is there a limit to the amount of volumes this will return in that mode?

Works: ./centreon_plugins.pl --plugin storage::nimble::snmp::plugin --mode global-stats --hostname ******** --snmp-version=2c --snmp-community=*********

Doesn't Work ./centreon_plugins.pl --plugin storage::nimble::snmp::plugin --mode volume-usage --hostname ******** --snmp-version=2c --snmp-community=*********

**Comment by garnier-quentin** [comment]
Could you try with the option --snmp-autoreduce ?

**Comment by rob-ball** [comment]
It appears that resolved the issue.  Thank you!

**Comment by garnier-quentin** [comment]
Thank you for the feedback
