### ISSUE TITLE
Plugin for HPE Synergy 

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon-plugins#1363]
Is there a plan to provide a plugin for HPE Synergy - may be using Oneview?
(HPE Synergy is the replacement of C7000 Bladecenter)
There exists a SDK for Python to the HPE OneView REST APIs:
https://github.com/HewlettPackard/python-hpOneView

Plugin would be appreciated as we have more and more customers migrating to Synergy...

Thanks a lot!

**Comment by garnier-quentin** [comment]
Indeed, there is a rest api for HPE OneView. We can get monitor hardware status and other stuffs:
http://h17007.www1.hpe.com/docs/enterprise/servers/oneviewhelp/oneviewRESTAPI/content/images/api/index.html#rest/server-hardware

Do you know if we can monitor synergy chassis directly ? With SNMP for example

**Comment by garnier-quentin** [comment]
Can you provide us curl commands and results (for server-hardware for example). And you need other informations, you can provide also.
