### ISSUE TITLE
Juniper MX5 plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#137]
Can you please add plugin for Juniper MX5.

**Comment by kadrika** [comment]
Any update on this?

**Comment by garnier-quentin** [comment]
I need a complete snmpwalk from the equipment:
snmpwalk -Cc -v2c -c public -ObentU __IP_DEVICE__ .1 > myagent.snmpwalk

**Comment by garnier-quentin** [comment]
The plugin 'network/juniper/mseries/plugin.pm' should be used (same for that equipment).
