### ISSUE TITLE
VMware Photon OS

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#1370]
Hi, Is there a plan to monitor Photon-based OS from VMware?
It is not similar to Linux system, it appears to be different and i can not use SNMP standard commands

Thank you
https://vmware.github.io/photon

**Comment by garnier-quentin** [comment]
Do you know if Photon OS gets a Rest API or cli ? Maybe you can use local linux ?

**Comment by garnier-quentin** [comment]
You can use os::linux::local::snmp. It should work for interfaces, storage (maybe other command like memory, swap, load)
Could you give me the result of the command: top -bn 1

**Comment by garnier-quentin** [comment]
Here the procedure to make it work. On the photonOS
```
# yum install net-snmp
# systemctl stop snmpd
# /usr/bin/net-snmp-create-v3-user -ro -A 'authpass' -X 'privpass' -a 'SHA' -x 'AES' monitoring
# systemct start snmpd
# systemctl stop iptables
```

With centreon-plugins:
```
perl centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=cpu --hostname=10.30.2.153 --snmp-version=3 --privprotocol=AES --privpassphrase=privpass --authprotocol=SHA --authpassphrase=authpass --snmp-username=monitoring
OK: 1 CPU(s) average usage is 1.00 % - CPU '0' usage : 1.00 % | 'total_cpu_avg'=1.00%;;;0;100 'cpu'=1.00%;;;0;100
```
