### ISSUE TITLE
[storage::netapp::snmp::plugin] mode filesys et list-filesys

### ISSUE THREAD

**Issue by iroll007** [centreon/centreon-plugins#1373]
On new storages netapp, there are SVM layer for cluster modes and every volumes are linked to a SVM
So there are possibility to encounter same volume name.

So in snmp, there is a oid who stores SVM name (Vserver) for the volume (1.3.6.1.4.1.789.1.5.4.1.34 | dfVserver | 0 | 0 | Name of the vserver to which the volume belongs.For aggregate and aggregate snapshot it will bean empty string.This field is ...) ==> (http://oidref.com/1.3.6.1.4.1.789.1.5.4.1)

To resolve this problem of duplicate volume name, it's possible for list-filesys mode to add the Vserver name in the name of the volume (like /vol/Vservername/Volumename) and/or add parameter to specify the Vserver of a volume ?

**Comment by garnier-quentin** [comment]
Could you provide us a snmpwalk result ?
$ snmpwalk -ObentU -v 2c -c public netappaddress .1.3.6.1.4.1 > netapp.snmpwalk

**Comment by iroll007** [comment]
We are an OIV (opérateur d'importance vitale) so by security I can't give you all content of our netapp.
It's possible to give all informations (I will change some names for security) about one volume ? or it's really necessary to give you all informations of the netapp ?

**Comment by garnier-quentin** [comment]
Yes you change name of volumes (but keep the logic :). You can sent it on our email also.

**Comment by garnier-quentin** [comment]
Have you send the snmpwalk ? Thanks

**Comment by iroll007** [comment]
Sorry I'm very busy this time. I don't forget to send you that as soon as possible.

**Comment by iroll007** [comment]
I sent you an email with snmpwalk information.

**Comment by iroll007** [comment]
hi quentin, 
have you added the feature ?

**Comment by garnier-quentin** [comment]
Not yet. I put it in my todo. But i can't give you a release date.

**Comment by garnier-quentin** [comment]
Could you test with the last version ?

**Comment by iroll007** [comment]
The last version permits to obtain vserver information in the list of filesys and display the vserver when we use mode filesys. Good job :)

But for mode filesys, I don't think that the option --filter-vserver works fine. If I use only this option, every vserver and volume is returned. If I filter with a name of volume and a filter vserver with the wrong vserver that works. So what is the purpose of this option?

And could you include the verification of the state of the vserver [vserverState] (1.3.6.1.4.1.789.1.27.1.1 http://www.mibdepot.com/cgi-bin/getmib3.cgi?win=mib_a&i=1&n=NETAPP-MIB&r=netapp&f=netapp_2_2_2.mib&v=v2&t=tbl&o=vserverTable#vserverEntry) because if a vserver isn’t running so the volume isn’t available. So I think this verification is important.

**Comment by garnier-quentin** [comment]
Indeed --filter-vserver doesn't work. Now it should be ok.

**Comment by iroll007** [comment]
--filter-vserver works when it used alone, we have only vserver volumes displayed. 
But when you mix --filter-name and --filter-vserver where the volume doesn't match the vserver, the output is "OK: |". Normally this case shouldn't have happened but I go back the information.

And about the check of the state of the vserver ?

**Comment by garnier-quentin** [comment]
Could you provide your filter arguments ? Because i don't understand.

**Comment by iroll007** [comment]
./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname x.x.x.x --snmp-version='2c' --snmp-community='test'  --filter-name='/vol/test_test$'  --warning-usage='80' --critical-usage='90'  --warning-inodes='80' --critical-inodes='90' --units='%' --verbose --filter-perfdata='used|inodes' --filter-vserver='NOTCORRECT'
OK:  |

**Comment by iroll007** [comment]
./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname x.x.x.x --snmp-version='2c' --snmp-community='test'  --filter-name='/vol/test_test$'  --warning-usage='80' --critical-usage='90'  --warning-inodes='80' --critical-inodes='90' --units='%' --verbose --filter-perfdata='used|inodes' --filter-vserver='TEST'
OK: Filesys 'TEST:/vol/test_test' Total: 972.80 MB Used: 1.68 MB (0.17%) Free: 971.12 MB (99.83%), Inodes Used : 0 %, Compress Saved : 0 %, Dedupe Saved : 0 % | 'used'=1757184B;0:816044441;0:918049996;0;1020055552 'inodes'=0%;0:80;0:90;0;100
Filesys 'TEST:/vol/test_test' Total: 972.80 MB Used: 1.68 MB (0.17%) Free: 971.12 MB (99.83%), Inodes Used : 0 %, Compress Saved : 0 %, Dedupe Saved : 0 %

**Comment by garnier-quentin** [comment]
Ok i understand. It's a 'AND' for filters. So it s by design.

**Comment by iroll007** [comment]
And about the check of the state of the vserver ? It could be include ?
It's a really important option for us

**Comment by garnier-quentin** [comment]
I can add an option for that.

**Comment by garnier-quentin** [comment]
Could you test the option --filter-vserver-state=running (an example)

**Comment by iroll007** [comment]
./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname x.x.x.x --snmp-version='2c' --snmp-community='test'  --filter-name='/vol/test_test$'  --warning-usage='80' --critical-usage='90'  --warning-inodes='80' --critical-inodes='90' --units='%' --snmp-timeout=20  --snmp-retries=0 --filter-perfdata='used|inodes' --filter-vserver='TEST' --filter-vserver-state='running'
UNKNOWN: Can't call method "get_multiple_table" on an undefined value at /usr/lib/centreon/plugins/centreon-plugins/storage/netapp/snmp/mode/filesys.pm line 213.

**Comment by garnier-quentin** [comment]
It should be ok

**Comment by iroll007** [comment]
The display is weird seems like nothing is return

./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname x.x.x.x --snmp-version='2c' --snmp-community='test'  --filter-name='/vol/test_test$'  --warning-usage='80' --critical-usage='90'  --warning-inodes='80' --critical-inodes='90' --units='%' --snmp-timeout=20  --snmp-retries=0 --filter-perfdata='used|inodes' --filter-vserver='TEST' --filter-vserver-state='running'
OK: |

**Comment by garnier-quentin** [comment]
Please add line 227 and give the me result:
```
   foreach (keys %$snmp_result) {
        next if (! /^$mapping3->{vserverName}->{oid}\.(.*)/);
        my $result = $options{snmp}->map_instance(mapping => $mapping3, results => $snmp_result, instance => $1);
        $self->{vserver}->{$result->{vserverName}} = $result->{vserverState};
    }
    use Data::Dumper; print Data::Dumper::Dumper($self->{vserver});
```

**Comment by iroll007** [comment]
I see something and my TEST is running

$VAR1 = {
          'qqqqqqq' => 'running',
          'ttttt' => 'unknown',
          'TEST' => 'stopped',
          'rrrrr' => 'running'
        };

**Comment by garnier-quentin** [comment]
TEST is stopped. So that's why you don't have result.

**Comment by iroll007** [comment]
How do I have to do when I want a critical return when it's stopped ?
I would like to have the service critical when it's different of running for example

**Comment by garnier-quentin** [comment]
You cannot.

**Comment by iroll007** [comment]
It's not possible to do like that ?
The important way is to be alerted when a vserver isn't running for a volume.

**Comment by garnier-quentin** [comment]
Need to do more change to manage that.

**Comment by iroll007** [comment]
I can wait about it 
thanks in advance

**Comment by iroll007** [comment]
can you at least give me a deadline ?

Really thanks for you work quentin. I really appreciate :)

**Comment by garnier-quentin** [comment]
Maybe before next friday.

**Comment by iroll007** [comment]
hello quentin

Did you have time to make the change?

**Comment by garnier-quentin** [comment]
Sorry. It will be done soon (but i can't give you a date)

**Comment by garnier-quentin** [comment]
Sorry for the delay. I added the option:
```
--critical-vserver-status='%{vserver_status} !~ /running|starting/'
```
