### ISSUE TITLE
(Add an option to) replace pipe in plugin output

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1374]
Hello,

Some plugins may put a pipe in their output, leading to some issues.
Details are given in this ticket :
https://github.com/centreon/centreon-engine/issues/115

Waiting for a fix to be given there, could we think about replacing pipes in plugins output ?
For example by a `¦` character ?
Perhaps an additional option could be added to enable/disable this behavior.

Thank you very much :+1:

**Comment by garnier-quentin** [comment]
I see the issue. We can add a global option to change the short output.

**Comment by garnier-quentin** [comment]
It's not that easy. I don't want to change that code. However we can manage it directly in the mode.

**Comment by CPbN** [comment]
There are many plugins and modes where we could face this issue I think ?
(almost each time a regexp to be caught is given ?)

**Comment by CPbN** [comment]
If a global solution is not that easy, perhaps we could simply wait for the root-cause (https://github.com/centreon/centreon-engine/issues/115) to be fixed.

**Comment by garnier-quentin** [comment]
centreon-engine cannot solve that. I have add an option. For example:
```
--change-short-output='\|~~g'
```

**Comment by CPbN** [comment]
Thank you very much Quentin, perfect solution :+1: 
I think centreon-engine could solve that splitting between output and perfdata at the last available pipe character. But we can continue this discussion later on [there](https://github.com/centreon/centreon-engine/issues/115).

**Comment by CPbN** [comment]
Starting with Centreon 19.10.1, we can now have pipes in plugins' output, thanks to the new broker version 👍
https://github.com/centreon/centreon-engine/issues/115
Thank you again @bouda1 !
