### ISSUE TITLE
[apps::protocols::http::plugin] Negative --expected-string

### ISSUE THREAD

**Issue by morganegzh** [centreon/centreon-plugins#1376]
Hi, 

By using expected-contents mode we would like to check that a word is not present on a webpage. 
Can we do that with a regex by using --expected-string command ? 

Thank you for your help,

**Comment by garnier-quentin** [comment]
We cannot do that. Because we don't use modifier regexp 's' (only 'm').

**Comment by CPbN** [comment]
Then user could prefix his regex with `(?s)` to enforce the `s` flag ?

**Comment by garnier-quentin** [comment]
Yes you can use following syntax:
```
--expected-string='(?s)^(?!.*(toto).*)$'
```

**Comment by romsworld** [comment]
Hi,

Yes, it would be a good idea to be able to reverse the expected string.
