### ISSUE TITLE
[network::f5::bigip::snmp::plugin] pool-status timing out

### ISSUE THREAD

**Issue by moix** [centreon/centreon-plugins#1377]
Hi there,

I've been trying the last couple of days to figure out why the pool-status plugin of f5 times out for me. I can query the bigip via snmpwalk and even running other modes of same plugin but for pool-status it raise a time out after 2 mins trying.

I've tried to run it in debug and verbose mode but it doesn't give more information about where it fails, can anyone indicate how can I debug at what point it fails?

`moix@/tmp ~$ time 'perl' centreon_plugins.pl '--snmp-community' '****' '--snmp-retries' '3' '--snmp-timeout' '30' '--snmp-version' '2c' '--plugin' network::f5::bigip::snmp::plugin --mode pool-status --hostname mybigip
UNKNOWN: SNMP Table Request : Timeout 

real    2m0.227s
user    0m0.142s
sys     0m0.023s`

thanks in advance! /moix

**Comment by garnier-quentin** [comment]
Could you try with the option --snmp-autoreduce ? (and remove --snmp-timeout option)

**Comment by moix** [comment]
cool! oh the version I was using was older and didn't include that option. I just downloaded and works like a charm!
Thanks @garnier-quentin for your help! really appreciate
