### ISSUE TITLE
Plugin database informix

### ISSUE THREAD

**Issue by Yosh28** [centreon/centreon-plugins#1379]
## Bug/Question

Hello, I try to set up the supervision on an informix basis with the Centreon plugin, but I have an error during the live test.

[root@localhost centreon-plugins]# ./centreon_plugins.pl --plugin=database::informix::plugin --mode=connection-time --host=10.35.4.218 --port=1524 --instance=mil
UNKNOWN: install_driver(Informix) failed: Can't locate DBD/Informix.pm in @INC (@INC contains: /usr/lib64/nagios/plugins/centreon-plugins /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 18) line 3.
Perhaps the DBD::Informix perl module hasn't been fully installed,
or perhaps the capitalisation of 'Informix' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Mem, Multiplex, Pg, Proxy, SQLite, Sponge, mysql.
 at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/dbi.pm line 216.

last version Centreon

**Comment by garnier-quentin** [comment]
Have you installed https://metacpan.org/pod/DBD::Informix and the driver ?

**Comment by garnier-quentin** [comment]
Good news. We are going to add a SNMP version. it will be easier.
