### ISSUE TITLE
[database::mssql::mode::failedjobs] bad duration time

### ISSUE THREAD

**Issue by FreshardF** [centreon/centreon-plugins#1382]
the flied run_duration on dbo.sysjobhistory have format HHMMSS.
but in plugin, you display the field as a number of minutes.

information source :
https://docs.microsoft.com/fr-fr/sql/relational-databases/system-tables/dbo-sysjobhistory-transact-sql?view=sql-server-2017

**Comment by garnier-quentin** [comment]
Thanks. Could you test with the last version ? It should be ok.

**Comment by FreshardF** [comment]
we have a other issue in last version.

return of plugin : 
/usr/lib/centreon/plugins/centreon_mssql.pl --plugin database::mssql::plugin --hostname *** --port *** --username '****' --password '*****'  --mode='failed-jobs' --warning='' --critical='0' --warning-duration='' --critical-duration='' --lookback='1440' --filter='^MPX_MaintenancePlan_.*' --lookback='1440' --change-perfdata "failed_jobs,maintenance_plan_KO" --verbose
Use of uninitialized value $hour in concatenation (.) or string at /usr/lib/centreon/plugins/centreon_mssql.pl line 6634.
Use of uninitialized value $minute in concatenation (.) or string at /usr/lib/centreon/plugins/centreon_mssql.pl line 6634.
Use of uninitialized value $second in concatenation (.) or string at /usr/lib/centreon/plugins/centreon_mssql.pl line 6634.
OK: All jobs are ok. | 'maintenance_plan_KO'=0;;;0;2
Job 'MPX_MaintenancePlan_STM.Rebuild_index' status success [Runtime : 2019-03-05 ::] [Duration : 0 minutes]
Job 'MPX_MaintenancePlan_STM.Reorg_index_and_stats' status success [Runtime : 2019-03-05 2:15:00] [Duration : 1 minutes]

return of sql statement :
[https://drive.google.com/open?id=1Ly9jsxyMZ8UMi0RbT5fJAB69sCWNfpAR](url)

can you update this plugin for display for duration < 1 minutes and concatenation issue ?

**Comment by garnier-quentin** [comment]
Could you test it with the last version ?

**Comment by FreshardF** [comment]
now is good for lastruntime.
Job 'MPX_MaintenancePlan_STM.Rebuild_index' status success [Runtime : 2019-03-06 00:45:00] [Duration : 0 minutes]
Job 'MPX_MaintenancePlan_STM.Reorg_index_and_stats' status success [Runtime : 2019-03-06 02:15:00] [Duration : 1 minutes]

but, the display duration time is alway confused for durations lower one minute.

**Comment by garnier-quentin** [comment]
Could you test it ? Ok for you ? :)

**Comment by FreshardF** [comment]
ahve you commit a newer file ?

**Comment by garnier-quentin** [comment]
Yes i have.

**Comment by FreshardF** [comment]
i can't see your laster commit on file "failedjobs.pm". for me your laster commit it is at 2 days ago

**Comment by garnier-quentin** [comment]
I see it: https://github.com/centreon/centreon-plugins/commit/42c5ba7df97d499fb9f3afa778a7a545866625f2

**Comment by FreshardF** [comment]
thank you, it's very good now . have a good day
Job 'MPX_MaintenancePlan_STM.Rebuild_index' status success [Runtime : 2019-03-07 00:45:00] [Duration : 46s]
Job 'MPX_MaintenancePlan_STM.Reorg_index_and_stats' status success [Runtime : 2019-03-07 02:15:00] [Duration : 1m 51s]

**Comment by FreshardF** [comment]
this update will be available on the centreon repo in how many days ?

**Comment by garnier-quentin** [comment]
You can already update the plugin with the unstable repository.
