### ISSUE TITLE
[apps::protocols::http::plugin] Mode response - Fail since update system (same as #428)

### ISSUE THREAD

**Issue by nicoden81** [centreon/centreon-plugins#1384]
Hi,

we have updated our poller to Centos 7.4. Since then, the plugin  [apps::protocols::http::plugin] Mode response is failing for some url in https whereas it was working before the OS migration.
The command line we are using is :
centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=test.example.com --urlpath / --proto https --port 8181 --filter-perfdata=time --timeout 15 --warning=3 --critical=5 --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"

CRITICAL: 500 Can't connect to  <fqdn>:<port>

I have tried with --ssl=sslv3 and --ssl=tlsv1 but no success.
Debug and verbose option doesn't show anything.

I saw the thread #428 with a similar issue and I am wondering wether it is related to the perl library IO::Socket::SSL.

Centreon-plugins global version is 20180528. I have tried with the latest version, but same issue.

perl-IO-Socket-SSL : v1.94

Thank you.

**Comment by Sims24** [comment]
Hi @nicoden81 , 

Your port option doesn't have any value. Is this normal ? please try to remove it completely. 

Also, do you use a proxy ?

**Comment by nicoden81** [comment]
Hi @Sims24 ,

thank you for your feedback.
It's just an error in the description of my issue, as I wanted to remove the hostname and the port. 
The port is set in the command in Centreon.

No, I don't use any proxy.

centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=response --hostname= --urlpath / --proto https --port 8181 --filter-perfdata=time --timeout 15 --warning=3 --critical=5 --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"

Thank you.

**Comment by nicoden81** [comment]
Hi,

I have found out the problem. The version of ssl is too old.
I close this issue.

Thanks.
