### ISSUE TITLE
apps::protocols::snmp::plugin - OID - Cant get a single value.

### ISSUE THREAD

**Issue by jithinpbenjamin** [centreon/centreon-plugins#1388]
Dear Team,

I am having an issue with SNMP plugin, as its unable to get the OID value from a device. I have an equipment which has OID configured to provide the GPS coordinates. When using the SNMP walk from Centreon server the value of the OID is displayed(See the First command output), but when using the Plugin it throws me an error "Cant get a single value."

SNMP Walk Result
------------------
[root@cent-poller ~]# snmpwalk -On -v 2c -c  public 192.168.2.1 .1.3.6.1.4.1.13745.100.1.1.5                                                                                                .1.3.6.1.4.1.13745.100.1.1.5.0 = STRING: "55.087650 E"

Plugin CLI Output
------------------

[root@cent-poller ~]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::snmp::plugin --mode=string-value --hostname=192.168.2.1 --snmp-community=public --snmp-version=2c --oid=.1.3.6.1.4.1.13745.100.1.1.5
UNKNOWN: SNMP GET Request : Cant get a single value.

Let me know if you need any more details.

**Comment by garnier-quentin** [comment]
Please use following OID option:
```
--oid=.1.3.6.1.4.1.13745.100.1.1.5.0
```

**Comment by jithinpbenjamin** [comment]
@garnier-quentin Thanks Buddy, it worked 👍 

But just one slight glitch, when I use the "String-value" mode the value is not what I expected but on the "Numeric-value" mode seems to be giving the correct output. So I hope I can continue to use the plugin in Numeric-value mode. Please see both result for your reference;

String-value output
--------------------
[root@cent-poller plugins]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::snmp::plugin --mode=string-value --hostname=192.168.2.1 --snmp-community=public --snmp-version=2c --oid=.1.3.6.1.4.1.13745.100.1.1.5.0
OK: 1 value(s) |

Numeric Value Output
-------------------------
[root@cent-poller plugins]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=192.168.2.1 --snmp-community=public --snmp-version=2c --oid=.1.3.6.1.4.1.13745.100.1.1.5.0
OK: current value is 55.087608 E | 'value'=55.087608 E;;;;

**Comment by garnier-quentin** [comment]
You shouldn't use 'numeric-value' with '55.087650 E' right now. The 'numeric-value' doesn't have an regexp option to search the numeric value. Maybe we can add it ;)

**Comment by jithinpbenjamin** [comment]
Sorry bit confused with your last comment. If I am not suppose to use the numeric-value, which mode I should use?
Based on the above result, only the numeric-value mode seems to be giving the correct result(Longitude Value) from the Equipment.

**Comment by garnier-quentin** [comment]
The value ' '55.087650 E' is not "numeric" (there is the E). And so, the perfdata is not valid: 'value'=55.087608 E;;;; 

You shouldn't have a space between the 'E' and the value. 

 The numeric-value is the right mode. But right now, the mode can't manage it well. Need to add an option like:
```
--filter-value='(\d+\.\d+)'
```

**Comment by jithinpbenjamin** [comment]
@garnier-quentin : Is the filter-value option is already added to the latest Github version.

I was getting the value from one of the device using the below script, so i maintained it, but today I added another device which is not responding correctly to the script. 

Device responding Correctly with the script:
 /usr/lib/centreon/plugins//iec_plugins/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=192.168.1.2 --snmp-community=public --snmp-version=2c --oid=.1.3.6.1.4.1.13745.100.1.1.4.0
OK: current value is 31.966572 N | 'value'=31.966572 N;;;;

Device not responding correctly:

/usr/lib/centreon/plugins//iec_plugins/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=192.168.1.3 --snmp-community=public --snmp-version=2c --oid=.1.3.6.1.4.1.13745.100.1.1.5.0
UNKNOWN: oid value is not numeric (4.030696 W) |

So only option available for me is to use the filter-value option but doesn't seems to be added to the version. Throwing error "Unknown option: filter-value" when trying to use it.

Regards,
Jithin

**Comment by garnier-quentin** [comment]
The option is added in last version.

**Comment by jithinpbenjamin** [comment]
I am having the latest version, any idea why its throwing 

Unknown option: filter-value

Please suggest.

**Comment by garnier-quentin** [comment]
because the option is: --extracted-pattern='(\d+\.\d+)'
