### ISSUE TITLE
plugin=hardware::pdu::eaton::plugin - Cant get a single value

### ISSUE THREAD

**Issue by ccoupeau** [centreon/centreon-plugins#1389]
Hi,
I'm trying to add some checks for news PDU but in using your plugin "hardware::pdu::eaton::plugin", i always have this message:

" UNKNOWN: SNMP Table Request: Cant get a single value."

My command:
./centreon_plugins.pl --plugin=hardware::pdu::eaton::plugin --mode outlet --hostname XXXXX --snmp-community XXXXX --snmp-version v2

I don't understand what i'm missing :( .
I'm used to never have problem with your developped plugins.

**Comment by garnier-quentin** [comment]
Could you provide us a full snmpwalk (snmpwalk -ObentU -v 2c -c public ip .1 > pdu.snmpwalk) and mib files ?

**Comment by ccoupeau** [comment]
Hey,

In attached,

Thanks you,
[pdu.zip](https://github.com/centreon/centreon-plugins/files/2860471/pdu.zip)

**Comment by garnier-quentin** [comment]
There is nothing in your snmpwalk.

**Comment by ccoupeau** [comment]
Oh.... Thanks to your comment, i understood what happened... !
Our PDU doesnt accept snmp version v2c ... only v1 or v3 :( ... First time, faced withthis situation ^^...
I have some results when i switch of snmp version.

Thanks,

You can close it,

**Comment by garnier-quentin** [comment]
Great :)
