### ISSUE TITLE
Global symbol "$name" requires explicit package name

### ISSUE THREAD

**Issue by dajones70** [centreon/centreon-plugins#1390]
Bug in network::fortinet::fortigate::plugin

./centreon_plugins.pl --plugin network::fortinet::fortigate::plugin --mode vdom-memory --hostname 10.137.0.11 --snmp-version 2c --snmp-community [redacted]

UNKNOWN: Cannot load module --mode. 
Global symbol "$name" requires explicit package name at /usr/lib64/nagios/plugins/centreon-plugins/centreon/common/fortinet/fortigate/mode/vdommemory.pm line 92.
Compilation failed in require at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/misc.pm line 209.

The fix is to change $name on line 92 to $self->{option_results}->{filter_name}.

This needs to be done for all .pm files in that directory.

**Comment by garnier-quentin** [comment]
Thank you for the feedback!
