### ISSUE TITLE
[apps::openvpn::omi::plugin] Adding Critical state when OpenVPN down

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon-plugins#1391]
Hello team,

We just discovered the openvpn plugin recently added to the plugin list which is exactly what we currently need in order to monitor some openvpn servers. 

However, do you think that a non-reachable OpenVPN Management Interface can return a "CRITICAL" status instead of "UNKNOWN" status ? 

Indeed I know that the OMI port is not the actual OpenVPN service port (default 1194) but after performing some tests, I discovered that 1194 and 7505 ports are "attached" to the same process. So 7505 can't be reachable if 1194 is down. I tried starting the service with a voluntary mistake (removing the openvpn certificate file set in the configuration file), and the process is not starting, so none of 1194 or 7505 ports are exposed. 

From this facts, I think we can consider that an unreachable OMI (7505) port means that OpenVPN service (1194) is down, so "CRITICAL" status is expected. 

It's just a proposal, maybe I'm totally wrong but this can potentially help us is some production situations.

Kind regards

Anthony

**Comment by garnier-quentin** [comment]
You can use following option:
```
--opt-exit=critical
```

Is it ok with the following option ?

**Comment by anthoc** [comment]
I didn't known this option. That did the trick ! Thank You

**Comment by garnier-quentin** [comment]
Great :)
