### ISSUE TITLE
--plugin=database::oracle::plugin mode=data-files-status

### ISSUE THREAD

**Issue by liam1337** [centreon/centreon-plugins#1394]
Hello,

You should replace this line (105) in the file database/oracle/mode/datafilesstatus.pm :

$self->change_macros(macros => ['warning_status', 'critical_status', 'warning_online_status', 'critical_online_status')]);

by this line :

$self->change_macros(macros => ['warning_status', 'critical_status', 'warning_online_status', 'critical_online_status']);

For now, there is this error message :
syntax error at /usr/lib/nagios/plugins/centreon-plugins/database/oracle/mode/datafilesstatus.pm line 105, near "'critical_online_status')"
Compilation failed in require at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/misc.pm line 209.

Thanks.

**Comment by garnier-quentin** [comment]
Thank you for the feedback!
