### ISSUE TITLE
hardware::printers::standard::rfc3805::plugin - Command not correct

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1395]
Hello guys,

I have seen that in the predefined command for the printer checks the $_SERVICEEXTRAOPTIONS$ variable is within ' '. But when I want to define some additional switches they are also between ' ' and are not recognized by the check command.

The command looks like this:
`/usr/lib/centreon/plugins/centreon_printers_generic_snmp.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=0.0.0.0 --snmp-community='public' --snmp-version='2c'  --warning '30:' --critical '20:' '--verbose --filter-tray='Tray ''`

and this should be the right command:
`/usr/lib/centreon/plugins/centreon_printers_generic_snmp.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=0.0.0.0 --snmp-community='public' --snmp-version='2c'  --warning '30:' --critical '20:' --verbose --filter-tray='Tray '`

Please correct this within the template.

Thank you and best regards,
Michael

**Comment by garnier-quentin** [comment]
You can set it like that in your macro:
```
--verbose --filter-tray="Tray "
```

**Comment by MikeW83** [comment]
Ok, I have tested it:
`/usr/lib/centreon/plugins/centreon_printers_generic_snmp.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=0.0.0.0 --snmp-community='public' --snmp-version='2c'  --warning '30:' --critical '20:' '--verbose --filter-tray="Tray "'`

That's the result:
`Unknown option: verbose --filter-tray at /usr/lib/centreon/plugins/centreon_printers_generic_snmp.pl line 141.`

**Comment by garnier-quentin** [comment]
The problem is in the command of the plugin-pack. Need to be corrected.
Should be:
```
$CENTREONPLUGINS$/centreon_printers_generic_snmp.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=$HOSTADDRESS$ --snmp-community='$_HOSTSNMPCOMMUNITY$' --snmp-version='$_HOSTSNMPVERSION$' $_HOSTSNMPEXTRAOPTIONS$ --warning '$_SERVICEWARNING$' --critical '$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$
```

**Comment by MikeW83** [comment]
Will this be corrected with the next update? Because I have no access to edit the pre-defined templates.

Thank you very much!

**Comment by garnier-quentin** [comment]
Yes i correct it!
