### ISSUE TITLE
apps::vmware::connector::plugin Unknown option

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1398]
Hello guys,

I have updated today my plugins and saw that the command line parameter changed. But when I try to check my datastore I only get:
`Unknown option: warning-total at /usr/lib/centreon/plugins/centreon_vmware_connector_client.pl line 8768.`

I have checked with --help and saw that the warning for privisioned usage has been removed:

> Mode:
>     Check datastore usage.
> 
>     --datastore-name
>             datastore name to list.
> 
>     --filter
>             Datastore name is a regexp.
> 
>     --scope-datacenter
>             Search in following datacenter(s) (can be a regexp).
> 
>     --units Units of thresholds (Default: '%') ('%', 'B').
> 
>     --free  Thresholds are on free space left.
> 
>     --unknown-status
>             Set warning threshold for status (Default: '%{accessible} !~
>             /^true|1$/i'). Can used special variables like: %{accessible}
> 
>     --warning-status
>             Set warning threshold for status (Default: ''). Can used special
>             variables like: %{accessible}
> 
>     --critical-status
>             Set critical threshold for status (Default: ''). Can used
>             special variables like: %{accessible}
> 
>     --warning-*
>             Threshold warning. Can be: 'total', 'snapshot'.
> 
>     --critical-*
>             Threshold critical. Can be: 'total', 'snapshot'.

There is only 'total' and 'snapshot' But when I change my command to
`/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --mode=datastore-usage --datastore-name='VMFS01_R1' --filter --warning-total=90 --critical-total='95' --warning-snapshot='' --critical-snapshot=''`

I get the error I described at the beginning.

Best regards, Michael

**Comment by garnier-quentin** [comment]
sorry for the wrong help: --warning-usage=90 --critical-usage='95'

**Comment by sbraz** [comment]
Would be nice to have that fixed in the RPM. Took me a solid 10 minutes to find out what was wrong.
