### ISSUE TITLE
network::fortinet::fortigate::plugin - Filter specific interface

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1399]
Hello guys,

it's me again :-)

Is it possible to filter one specific interface that it is not showing up? Because in my case the Management Interface is Enabled but nothing is connected. So it is showing up as critical. I want to exclude this interface from the checks.
If yes, how do I do it?
The help of the plugin is no help (for me).

Thank you very much.

Best regards,
Michael

**Comment by garnier-quentin** [comment]
Hello,

Yes you can. You need to change 'totointerface' by the display name of your interface.
```
--critical-status='%{admstatus} eq "up" and %{opstatus} ne "up" and %{display} !~ /totointerface/'
```

**Comment by garnier-quentin** [comment]
You can also remove the interface from the check directly:
```
--interface='^(?!(totointerface)$)' --name
```

**Comment by MikeW83** [comment]
> 
> 
> You can also remove the interface from the check directly:
> 
> ```
> --interface='^(?!(totointerface)$)' --name
> ```

Thank you very much. This is what I was searching for.

Best regards, Michael
