### ISSUE TITLE
Cisco CE500 memory not working with network::cisco::standard::snmp::plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#140]
Hi,

Memory mode is not working with network::cisco::standard::snmp::plugin, when the device is Cisco CE500.  CPU and Environment work just fine.

**Comment by garnier-quentin** [comment]
Could you give me snmpwalk of following OIDs:
.1.3.6.1.4.1.9.9.48.1.1.1
.1.3.6.1.4.1.9.9.305.1.1

Thanks

**Comment by kadrika** [comment]
both give: No Such Object available on this agent at this OID

**Comment by garnier-quentin** [comment]
So that's the problem. Could you look if you find memory OIDs for your equipment ?

**Comment by kadrika** [comment]
I will try to find it tomorrow.

**Comment by garnier-quentin** [comment]
I have looked and for the catalyst 500, there is no memory in SNMP:
ftp://ftp.cisco.com/pub/mibs/supportlists/ce500/ce500-supportlist.html

**Comment by kadrika** [comment]
Thanks for the update!
