### ISSUE TITLE
network::fortinet::fortigate::plugin Cluster status does not report a failed node

### ISSUE THREAD

**Issue by acelor** [centreon/centreon-plugins#1401]
I have checked the operation of the plugin, and it reports sync/async status OK, but if one node is shut down for wahetver reason the plugin still reports ok. I did not find any code that handles "Cluster configured, but only one node online". I suggest adding the following lines in the end of clusterstatus.pm, sub manage_selection():

if ((scalar(keys %{$self->{nodes}}) <2) && ($mode->{$oid_fgHaSystemMode} >1)) {
    $self->{output}->add_option_msg(short_msg => 'Cluster configured, but less than 2 nodes');
    $self->{output}->option_exit();
}

I don't know if it is a good solution, but at least it works for me (tm)

**Comment by garnier-quentin** [comment]
What do you have in the sync_status with only one node online ?

**Comment by acelor** [comment]
Yes, the sync status is 'synchronized'. We're qusing the RPMs, but the result would be he same with the current Master branch. Here are the outputs:

Output from working cluster:

```
# /usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=cluster-status --hostname=firewall --snmp-version='2c' --snmp-community='public'  --warning-status='%{role} !~ /master|slave/' --critical-status='%{sync_status} !~ /^synchronized/' --opt-exit warning --verbose
OK: All cluster nodes status are ok |
Node 'FGT5HXXXXXXXXX' status is 'synchronized' [Hostname: FIREWALL-N1] [Role: master]
Node 'FGT5HYYYYYYYYY' status is 'synchronized' [Hostname: FIREWALL-N2] [Role: slave]
```
Output from failed cluster:
```
/usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=cluster-status --hostname=10.63.8.1 --snmp-version='2c' --snmp-community='public'  --warning-status='%{role} !~ /master|slave/' --critical-status='%{sync_status} !~ /^synchronized/' --opt-exit warning --verbose
OK: Node 'FGT60DXXXXXXXX' status is 'synchronized' [Hostname: FIREWALL2_N1] [Role: master] |
Node 'FGT60DXXXXXXXX' status is 'synchronized' [Hostname: FIREWALL2_N1] [Role: master]

```

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test with the following command option:
```
--critical-total-nodes=2:
```

**Comment by acelor** [comment]
Quentin,

I can confirm that your patch works as expected. Everybody around me is still blazed by your speed. 21 minutes from issue to patch, WOW!

Thanks a lot

**Comment by garnier-quentin** [comment]
Thanks for the quick feedback. We don't like bugs ;)

**Comment by cgagnaire** [comment]
Well, it's not a bug as you could have use --critical-synchronized=2:
<3
