### ISSUE TITLE
hardware::server::cisco::ucs::plugin::mode::equipment- unknow and missing components on warning

### ISSUE THREAD

**Issue by loic60600** [centreon/centreon-plugins#1402]
Hi,

I have a mistake. I have to add monitor for cisco UCS server. This server have 8/24 memories and 2/8 local disk and 1/2 cpu. 

The plugin give me an error for missing & unknown component and a warning status.

> WARNING: cpu 'sys/rack-unit-1/board/cpu-2' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-3' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-6' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-9' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-12' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-13' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-14' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-15' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-16' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-17' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-18' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-19' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-20' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-21' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-22' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-23' presence is: 'missing' - memory 'sys/rack-unit-1/board/memarray-1/mem-24' presence is: 'missing' - local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-3' presence is: 'missing' - local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-4' presence is: 'missing' - local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-5' presence is: 'missing' - local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-6' presence is: 'missing' - local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-7' presence is: 'missing' - local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-8' presence is: 'missing' |

The verbose : 

> UNKNOWN: memory 'sys/rack-unit-1/board/memarray-1/mem-3' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-6' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-9' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-12' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-13' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-14' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-15' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-16' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-17' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-18' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-19' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-20' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-21' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-22' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-23' state is 'unknown' - memory 'sys/rack-unit-1/board/memarray-1/mem-24' state is 'unknown' |
Checking fans
fan 'sys/rack-unit-1/fan-module-1-1/fan-1' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-1/fan-2' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-2/fan-1' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-2/fan-2' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-3/fan-1' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-3/fan-2' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-4/fan-1' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-4/fan-2' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-5/fan-1' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-5/fan-2' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-6/fan-1' state is 'operable' [presence: equipped].
fan 'sys/rack-unit-1/fan-module-1-6/fan-2' state is 'operable' [presence: equipped].
Checking power supplies
power supply 'sys/rack-unit-1/psu-1' state is 'operable' [presence: equipped].
power supply 'sys/rack-unit-1/psu-2' state is 'operable' [presence: equipped].
Checking chassis
Checking io cards
Checking blades
Checking fabric extenders
Checking cpus
cpu 'sys/rack-unit-1/board/cpu-1' state is 'operable' [presence: equipped].
cpu 'sys/rack-unit-1/board/cpu-2' state is 'inoperable' [presence: missing].
Checking memories
memory 'sys/rack-unit-1/board/memarray-1/mem-1' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-2' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-3' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-4' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-5' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-6' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-7' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-8' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-9' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-10' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-11' state is 'operable' [presence: equipped].
memory 'sys/rack-unit-1/board/memarray-1/mem-12' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-13' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-14' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-15' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-16' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-17' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-18' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-19' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-20' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-21' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-22' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-23' state is 'unknown' [presence: missing].
memory 'sys/rack-unit-1/board/memarray-1/mem-24' state is 'unknown' [presence: missing].
Checking local disks
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-1' state is 'operable' [presence: equipped].
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-2' state is 'operable' [presence: equipped].
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-3' state is 'removed' [presence: missing].
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-4' state is 'removed' [presence: missing].
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-5' state is 'removed' [presence: missing].
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-6' state is 'removed' [presence: missing].
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-7' state is 'removed' [presence: missing].
local disk 'sys/rack-unit-1/board/storage-SAS-SLOT-HBA/pd-8' state is 'removed' [presence: missing].

My command : 

> centreon_plugins.pl --plugin=hardware::server::cisco::ucs::plugin --snmp-username=centreon --authpassphrase=**** --authprotocol=MD5 --privpassphrase=***** --privprotocol=AES --snmp-version=3 --mode=equipment  --hostname=x.x.x.x

I had edit the ressouces.pm file to Replace "warning" by "OK" to 

- Default.presence > missing
- default.operability > unknown
- default.operability > removed
- default.overall_status > removed 

 And i have a good message now : 

OK: All 48 components are ok [2/2 cpus, 12/12 fans, 8/8 local disks, 24/24 memories, 2/2 psus]. | 

Can you help me please ? 
Thanks

**Comment by garnier-quentin** [comment]
You could use following options:
```
--threshold-overload='memory.presence,OK,missing' --threshold-overload='memory.operability,OK,unknown'
```

Could you test it ?

**Comment by loic60600** [comment]
Thanks ! 

It is ok with : 

> centreon_plugins.pl --plugin=hardware::server::cisco::ucs::plugin --snmp-username=centreon --authpassphrase=xxxx --authprotocol=MD5 --privpassphrase=xxxx --privprotocol=AES --snmp-version=3 --mode=equipment  --hostname=x.x.x.x --threshold-overload='memory.presence,OK,missing' --threshold-overload='memory.operability,OK,unknown' --threshold-overload='cpu.presence,OK,missing' --threshold-overload='localdisk.presence,OK,missing' --threshold-overload='localdisk.operability,OK,removed'
