### ISSUE TITLE
[network::checkpoint::snmp::mode] VPN status is not working on latest SMB firmwares

### ISSUE THREAD

**Issue by sikado** [centreon/centreon-plugins#1403]
Since a few firmware releases of the Check Point "Gaïa Embeded" OS (for Small Business firewalls), the VPN-Status check is not working anymore (but it's still working on the "Gaïa" OS, for classique firewalls )

Here is the snmpwalk on the Gaïa Embeded OS (with the MIB, IP have been changed for obvious privacy reason):

```
snmpwalk -v 3 .1.3.6.1.4.1.2620.500.9002.1 -m ./chkpnt.mib
CHECKPOINT-MIB::tunnelPeerObjName.192.168.12.12.0 = STRING: fwcluster
CHECKPOINT-MIB::tunnelState.192.168.12.12.0 = Wrong Type (should be INTEGER): Counter32: 3
CHECKPOINT-MIB::tunnelCommunity.192.168.12.12.0 = STRING: GLOBAL
CHECKPOINT-MIB::tunnelNextHop.192.168.12.12.0 = IpAddress: 0.0.0.0
CHECKPOINT-MIB::tunnelInterface.192.168.12.12.0 = STRING:
CHECKPOINT-MIB::tunnelSourceIpAddr.192.168.12.12.0 = Wrong Type (should be IpAddress): STRING: "1.1.1.1"
CHECKPOINT-MIB::tunnelLinkPriority.192.168.12.12.0 = Wrong Type (should be INTEGER): Counter32: 0
CHECKPOINT-MIB::tunnelProbState.192.168.12.12.0 = Wrong Type (should be INTEGER): Counter32: 0
CHECKPOINT-MIB::tunnelPeerType.192.168.12.12.0 = Wrong Type (should be INTEGER): Counter32: 1
CHECKPOINT-MIB::tunnelType.192.168.12.12.0 = Wrong Type (should be INTEGER): Counter32: 2
```
And without:
```
snmpwalk -v 3 .1.3.6.1.4.1.2620.500.9002.1
iso.3.6.1.4.1.2620.500.9002.1.2.192.168.12.12.0 = STRING: "fwcluster"
iso.3.6.1.4.1.2620.500.9002.1.3.192.168.12.12.0 = Counter32: 3
iso.3.6.1.4.1.2620.500.9002.1.4.192.168.12.12.0 = STRING: "GLOBAL"
iso.3.6.1.4.1.2620.500.9002.1.5.192.168.12.12.0 = IpAddress: 0.0.0.0
iso.3.6.1.4.1.2620.500.9002.1.6.192.168.12.12.0 = ""
iso.3.6.1.4.1.2620.500.9002.1.7.192.168.12.12.0 = STRING: "1.1.1.1"
iso.3.6.1.4.1.2620.500.9002.1.8.192.168.12.12.0 = Counter32: 0
iso.3.6.1.4.1.2620.500.9002.1.9.192.168.12.12.0 = Counter32: 0
iso.3.6.1.4.1.2620.500.9002.1.10.192.168.12.12.0 = Counter32: 1
iso.3.6.1.4.1.2620.500.9002.1.11.192.168.12.12.0 = Counter32: 2
```

Thanks,

**Comment by garnier-quentin** [comment]
Could you provide us the MIB files for the new OS and a full snmpwalk ? Thanks

**Comment by sikado** [comment]
Do you need specific parameters for the snmpwalk ? Can I send you that by email ? Thanks

**Comment by garnier-quentin** [comment]
You can send me by email yes. You can use following options:
```
snmpwalk -ObentU
```

**Comment by garnier-quentin** [comment]
Do you know where i can find vpn information now ? It should be the same table. Could you ask to your checkpoint support ?

**Comment by sikado** [comment]
In the first comment of the ticket, I gave you the VPN informations for an establishment VPN, isn't what you are looking for ?

**Comment by garnier-quentin** [comment]
Yes it is. But it's not in your snmpwalk. The current vpn mode needs it. If it's no more populate with the last version, i need to know where to look for.

**Comment by garnier-quentin** [comment]
It seems like a bug from Checkpoint SNMP agent. It cannot provide information when we want to snmpwalk .1.3.6.1.4.1.2620.500.9002.1.2 for example.
