### ISSUE TITLE
issue with broker-retention in centreon 2.8.26 (After upgrade)

### ISSUE THREAD

**Issue by crocoolivier** [centreon/centreon-plugins#1404]
After an update in v. 2.8.26,
I have little problem with this service : Broker-Retention

Here command executed by centreon 
/usr/lib/centreon/plugins/centreon_centreon_central.pl
	--plugin=apps::centreon::local::plugin
	--mode=retention-broker
	--broker-config=''
	--broker-config=''
	--verbose

Output 

UNKNOWN: '': not a file or cannot be read - '': not a file or cannot be read
--

Where can i update macros _HOSTRRDCFGFILE and _HOSTSQLCFGFILE.
$_HOSTSQLCFGFILE$=/var/lib/centreon-broker/central-broker-master-stats.json
$_HOSTRRDCFGFILE$=/var/lib/centreon-broker/central-rrd-master-stats.json

I tried directly on the service 
![image](https://user-images.githubusercontent.com/866852/53744710-d40e3800-3e9d-11e9-9366-f7cbc96d9236.png)

and in resources 

![image](https://user-images.githubusercontent.com/866852/53744757-ef794300-3e9d-11e9-91ee-2a95195d9397.png)

But the problem still here. 
If you have an idea ;)
Thx in advance,

**Comment by garnier-quentin** [comment]
Hi,

Host macro should be set in 'App-Monitoring-Centreon-Central-Custom' template. It's not a centreon-plugins issue directly.

**Comment by cgagnaire** [comment]
Hi,
With the version of broker shipped with your version of Centreon, you must use Broker-Stats check instead.

**Comment by crocoolivier** [comment]
hi,
Yes macros are in App-Monitoring-Centreon-Central-Custom and the path is good...
![image](https://user-images.githubusercontent.com/866852/53792259-85a77a80-3f2b-11e9-85ff-9d2e8a9e9300.png)
But macros are empty in the centreon command. 
That's works wither Broker-stats.
Thank a lot quentin and cgagniaire.
