### ISSUE TITLE
[hardware::ats::apc::snmp::plugin => --filter option not working

### ISSUE THREAD

**Issue by amitsamy** [centreon/centreon-plugins#1407]
Hello,

I have an APC module which I have just put on Centreon using the plugin [hardware::ats::apc::snmp::plugin.

For the mode "Device-Status",  I am getting the following output and I want to skip PhaseSyncStatus:
CRITICAL: Entity 'PhaseSyncStatus' status is 'outOfSync' | 'count_entity'=14;;;;
Checking entities
entity '24VPowerSupply' status is 'atsPowerSupplyOK' [instance = 24VPowerSupply]
entity '24VSourceBPowerSupply' status is 'atsPowerSupplyOK' [instance = 24VSourceBPowerSupply]
entity '5VPowerSupply' status is 'atsPowerSupplyOK' [instance = 5VPowerSupply]
entity 'CommStatus' status is 'atsCommEstablished' [instance = CommStatus]
entity 'HardwareStatus' status is 'ok' [instance = HardwareStatus]
entity 'Minus12VPowerSupply' status is 'atsPowerSupplyOK' [instance = Minus12VPowerSupply]
entity 'OverCurrentState' status is 'atsCurrentOK' [instance = OverCurrentState]
entity 'PhaseSyncStatus' status is 'outOfSync' [instance = PhaseSyncStatus]
entity 'Plus12VPowerSupply' status is 'atsPowerSupplyOK' [instance = Plus12VPowerSupply]
entity 'RedundancyState' status is 'atsFullyRedundant' [instance = RedundancyState]
entity 'SourceAStatus' status is 'ok' [instance = SourceAStatus]
entity 'SourceBStatus' status is 'ok' [instance = SourceBStatus]
entity 'SwitchStatus' status is 'ok' [instance = SwitchStatus]
entity 'VoltageOutStatus' status is 'ok' [instance = VoltageOutStatus]

In the --help section, for filter it says:
Mode:
    Check device status.

    --component
            Which component to check (Default: '.*'). Can be: 'entity'.

    --filter
            Exclude some parts (comma seperated list) (Example:
            --filter=entity) Can also exclude specific instance:
            --filter=entity,CommStatus

I have tried to use the following format: --filter='PhaseSyncStatus' but it's not working.

Same if I want to have the status of one entity, I use --component='PhaseSyncStatus' and I get UNKNOWN: Wrong option. Cannot find component 'PhaseSyncStatus'.

Can you help me with this issue?

Regards,
Amit

**Comment by garnier-quentin** [comment]
You can try that option:
```
--filter=entity,PhaseSyncStatus
```

**Comment by amitsamy** [comment]
Hello Quentin,

Thanks for the help. It worked.

One last question, how to get the status of only one component/entity?

**Comment by garnier-quentin** [comment]
Could you try negative regexp ?
```
--filter='entity,^(?!(PhaseSyncStatus)$)'
```
