### ISSUE TITLE
Azure: Cannot load module 'DateTime::Format::Duration::ISO8601' Centos7

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#1409]
Hi,

I´ve installed the latest centreon plugins release and I installed the perl-DateTime-Format-ISO8601-0.08-4.el7.noarch.rpm on my CentOS 7 system, but the following command doesn´t work and throws a Cannot load module 'DateTime::Format::Duration::ISO8601' error:

`./centreon_plugins.pl --plugin=cloud::azure::management::recovery::plugin --custommode=api --mode=backup-jobs-status --subscription='xx' --tenant='xx' --client-id='xx' --client-secret='xx' --resource-group=test_rsg --vault-name='test' --filter-counters='^total-failed$' --critical-total-failed='0' --range-perfdata=1`

Has anyone a hint, what I can do? Or is another version / wrong naming referenced at the azure check pm?

Regards,

**Comment by garnier-quentin** [comment]
If you are on centos:
```
yum install epel-release
yum install perl-DateTime-Format-ISO8601
```

**Comment by benhartwich** [comment]
Thanks! I had installed both packages already:

```
[root@mon]# yum install epel-release
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.nextlayer.at
 * epel: mirror.karneval.cz
 * extras: mirror.nextlayer.at
 * remi-safe: remi.mirror.karneval.cz
 * updates: mirror.nextlayer.at
Package epel-release-7-11.noarch already installed and latest version
Nothing to do
[root@mon plugins]# yum install perl-DateTime-Format-ISO8601
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.nextlayer.at
 * epel: mirror.karneval.cz
 * extras: mirror.nextlayer.at
 * remi-safe: remi.mirror.karneval.cz
 * updates: mirror.nextlayer.at
Package perl-DateTime-Format-ISO8601-0.08-4.el7.noarch already installed and latest version
Nothing to do
```

**Comment by garnier-quentin** [comment]
It will be in centreon standard repository.
https://share.centreon.com/public/414d98
