### ISSUE TITLE
[network::cisco::ironport::snmp::plugin] hardware

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#141]
Hello,

This mode does nothing for raid control even if the last line in verbose mode say "Checking raids".

Here is the result of this mode for an ironport with raid status degraded :
OK: All 7 components are ok [4/4 fans, 2/2 power supplies, 1/1 temperatures]. | 'fan_FAN 1'=5250rpm;;;0; 'fan_FAN 2'=5250rpm;;;0; 'fan_FAN 3'=5400rpm;;;0; 'fan_FAN 4'=5325rpm;;;0; 'temp_Ambient'=19C;;;;
Checking fans
Fan 'FAN 1' is '5250' rpm [instance = 1]
Fan 'FAN 2' is '5250' rpm [instance = 2]
Fan 'FAN 3' is '5400' rpm [instance = 3]
Fan 'FAN 4' is '5325' rpm [instance = 4]
Checking temperatures
Temperature 'Ambient' is '19' degree centigrade [instance = 1]
Checking power supplies
Power supply 'PS 1' status is 'powerSupplyHealthy' [instance = 1]
Power supply 'PS 2' status is 'powerSupplyHealthy' [instance = 2]
Checking raids

Here the snmpwalk result :
ASYNCOS-MAIL-MIB::raidEvents.0 = Counter32: 4
ASYNCOS-MAIL-MIB::raidIndex.1 = INTEGER: 1
ASYNCOS-MAIL-MIB::raidIndex.2 = INTEGER: 2
ASYNCOS-MAIL-MIB::raidIndex.3 = INTEGER: 3
ASYNCOS-MAIL-MIB::raidIndex.4 = INTEGER: 4
ASYNCOS-MAIL-MIB::raidStatus.1 = INTEGER: driveHealthy(1)
ASYNCOS-MAIL-MIB::raidStatus.2 = INTEGER: driveHealthy(1)
ASYNCOS-MAIL-MIB::raidStatus.3 = INTEGER: driveFailure(2)
ASYNCOS-MAIL-MIB::raidStatus.4 = INTEGER: driveHealthy(1)
ASYNCOS-MAIL-MIB::raidID.1 = STRING: Drive 0
ASYNCOS-MAIL-MIB::raidID.2 = STRING: Drive 1
ASYNCOS-MAIL-MIB::raidID.3 = STRING: Drive 2
ASYNCOS-MAIL-MIB::raidID.4 = STRING: Drive 3
ASYNCOS-MAIL-MIB::raidLastError.1 = STRING: No Errors
ASYNCOS-MAIL-MIB::raidLastError.2 = STRING: No Errors
ASYNCOS-MAIL-MIB::raidLastError.3 = STRING: State change
ASYNCOS-MAIL-MIB::raidLastError.4 = STRING: No Errors

**Comment by garnier-quentin** [comment]
Thanks. Should be fixed. Could you test it please ?

**Comment by ritouret** [comment]
Thanks Quentin : it's fixed :

CRITICAL: Raid 'Drive 2' status is 'driveFailure' | 'fan_FAN 1'=5325rpm;;;0; 'fan_FAN 2'=5325rpm;;;0; 'fan_FAN 3'=5325rpm;;;0; 'fan_FAN 4'=5250rpm;;;0; 'temp_Ambient'=16C;;;;
Checking fans
Fan 'FAN 1' is '5325' rpm [instance = 1]
Fan 'FAN 2' is '5325' rpm [instance = 2]
Fan 'FAN 3' is '5325' rpm [instance = 3]
Fan 'FAN 4' is '5250' rpm [instance = 4]
Checking temperatures
Temperature 'Ambient' is '16' degree centigrade [instance = 1]
Checking power supplies
Power supply 'PS 1' status is 'powerSupplyHealthy' [instance = 1]
Power supply 'PS 2' status is 'powerSupplyHealthy' [instance = 2]
Checking raids
Raid 'Drive 0' status is 'driveHealthy' [instance = 1]
Raid 'Drive 1' status is 'driveHealthy' [instance = 2]
Raid 'Drive 2' status is 'driveFailure' [instance = 3]
Raid 'Drive 3' status is 'driveHealthy' [instance = 4]

Should you also update ces-plugins-Network-Cisco-Ironport-Snmp-2.0-1 ?

**Comment by garnier-quentin** [comment]
Great! Not a question to be ask here ;)

**Comment by ritouret** [comment]
Sorry, it's done at the right place ...
