### ISSUE TITLE
Incorrect Speed Network Interface

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#1410]
Global Version: **(dev)**
Plugin name: **os::mac::snmp::plugin**
Mode: **interfaces**

Error in command result for interface speed
`centreon_plugins.pl --plugin os::mac::snmp::plugin --mode interfaces --name --interface en0 --hostname sm031703 --add-speed`

Result
`OK: Interface 'en0' Status : up (admin: up), Speed : 1.00Gb/s | 'speed'=1000000000b/s;;;0;`

But the interface is a 10GbaseT

> en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
> 	options=167<RXCSUM,TXCSUM,VLAN_MTU,TSO4,TSO6,AV>
> 	ether xx:xx:xx:xx:xx:xx 
> 	inet6 fe80::ea:e061:6ba3:b5b4%en0 prefixlen 64 secured scopeid 0x8 
> 	inet 192.168.4.123 netmask 0xffffff00 broadcast 192.168.4.255
> 	nd6 options=201<PERFORMNUD,DAD>
> 	media: autoselect (10GbaseT <full-duplex,flow-control>)
> 	status: active

**Comment by garnier-quentin** [comment]
You can override it if SNMP provides a wrong information: --speed=10000

**Comment by stefanotoro** [comment]
Yes thank you, but this is not a resolution if i have many different interfaces and many different devices.

Can you improve the check of the plugin?

**Comment by garnier-quentin** [comment]
We get it from SNMP. It seems like a bug from the agent.
