### ISSUE TITLE
Azure: UNKNOWN: No metrics at some checks

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#1411]
Hi,

I´ve integrated different azure checks at icinga2 by calling:

`./centreon_plugins.pl --plugin=cloud::azure::storage::storageaccount::plugin --custommode=api --mode=transactions-latency --subscription='xx' --tenant='xx' --client-id='xx' --client-secret='xx' --resource=xxtorageacc --resource-group=Hosting_xx_rsg --range-perfdata=1`

I check this once an hour. Sometimes it works, sometimes I get: UNKNOWN: No metrics. Check your options or use --zeroed option to set 0 on undefined values

I don´t know, why this happens. I´ve asked the azure support and they told me that there is no rate limiting etc. Can you please tell me, when this error occurs? Is this a timeout which I have to set higher?

Thanks and regards,

**Comment by cgagnaire** [comment]
Hi @benhartwich,
Thanks for using the project, even with icinga ;)
Well, to get metrics, we use Azure Monitor. And for each metrics, we need to provide a timeframe and an interval (sampling period) to get a dataset. Sometimes, Monitor doesn't have data in this timeframe or with this sampling period. By default, the timeframe is the last 15 minutes, and the interval is 5 minutes.
So, for your example, you must try to play with the --timeframe and --interval options, like --timeframe=3600 (1 hour) and --interval=PT15M (15 minutes).

**Comment by benhartwich** [comment]
Hi,
thanks, there are fewer problems with setting timeframe and interval. 
Perhaps you can add this to the example commands?
