### ISSUE TITLE
apps::vmware::connector::plugin: mode=net-host - Illegal division by zero

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1413]
Centreon 18.10
Plugins: 20190221

/usr/lib/centreon/plugins/centreon_plugins --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=net-host --esx-hostname='hostname' --filter --scope-cluster='' --scope-datacenter='.*' --nic-name='' --warning-host-traffic-in= --warning-host-traffic-out= --warning-vswitch-traffic-in= --warning-vswitch-traffic-out= --warning-link-traffic-in= --warning-link-traffic-out= --warning-link-dropped-in= --warning-link-dropped-out= --critical-host-traffic-in= --critical-host-traffic-out= --critical-vswitch-traffic-in= --critical-vswitch-traffic-out= --critical-link-traffic-in= --critical-link-traffic-out= --critical-link-dropped-in= --critical-link-dropped-out= --warning-status= --critical-status=

CRITICAL: Host 'hostname' : physical interface 'vmnic4' status down - physical interface 'vmnic5' status down UNKNOWN: Illegal division by zero at /usr/lib/centreon/plugins/apps/vmware/connector/mode/nethost.pm line 95

**Comment by garnier-quentin** [comment]
It's fixed in the last version. You can try with the github version.

**Comment by joschi99** [comment]
Hi @garnier-quentin,
thanks, fix is working.

**Comment by garnier-quentin** [comment]
thanks for the quick feedback!

**Comment by joschi99** [comment]
thank you for the quick solution
