### ISSUE TITLE
Package last IO::Socket::SSL

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1414]
Hi,

As required by https://github.com/centreon/centreon-plugins/pull/1035, and as @cgagnaire proposed, could you please package last version of `IO::Socket::SSL` for Centos 7 ?

Thank you very much :+1:

**Comment by CPbN** [comment]
> I've just added it ([3ece41a](https://github.com/centreon/centreon-plugins/commit/3ece41a4245936ad8773c5ac68c62f7fcb1e3987)).
> Note that this option will work only with IO::Socket::SSL >= 1.984.
> The mode itself will work only with Net::SSLeay >= 1.42.
> I've tested latest version of IO::Socket::SSL and Net::SSLeay on both CentOS 6 and 7 and it works well.
> We will push those versions on our repos.

**Comment by garnier-quentin** [comment]
Sorry but we can't. It can break other modules.

**Comment by CPbN** [comment]
By default Centos 7 has IO::Socket::SSL 1.94.
Do you really think that installing the first required version (1.984 as per @cgagnaire said) will break other things ?
Also, as stated in #1035, I had to update the built-in 1.94 version which returns SSL errors.

**Comment by CPbN** [comment]
Note that it affects `apps::protocols::x509` but also any plugin using HTTPS, where `timeout` option then does not work.
