### ISSUE TITLE
[18.10.3] apps::vmware::connector::plugin doesn't work, Cannot get response (timeout received)

### ISSUE THREAD

**Issue by wackou72** [centreon/centreon-plugins#1416]
Hello,
Just updated my Centreon system to the last version.
Everything is working fine, except the plugin apps::vmware::connector::plugin
When running, `/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --mode=alarm-datacenter`
I have the following result :
`UNKNOWN: Cannot get response (timeout received)`

When verifying the daemon status, I have this error :
```
systemctl status centreon_vmware
● centreon_vmware.service - Centreon VMWare
   Loaded: loaded (/etc/systemd/system/centreon_vmware.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-03-13 11:42:55 CET; 948ms ago
  Process: 15058 ExecStart=/usr/bin/perl /usr/bin/centreon_vmware.pl --logfile=/var/log/centreon/centreon_vmware.log --severity=error (code=exited, status=1/FAILURE)
 Main PID: 15058 (code=exited, status=1/FAILURE)

Mar 13 11:42:54 CENTREONSRV systemd[1]: Started Centreon VMWare.
Mar 13 11:42:55 CENTREONSRV systemd[1]: centreon_vmware.service: main process exited, code=exited, status=1/FAILURE
Mar 13 11:42:55 CENTREONSRV systemd[1]: Unit centreon_vmware.service entered failed state.
Mar 13 11:42:55 CENTREONSRV systemd[1]: centreon_vmware.service failed.
```

I can provide more information
Have a nice day

**Comment by wackou72** [comment]
Sorry for bothering, solution is here :
https://github.com/centreon/centreon-vmware/issues/75

**Comment by zale221** [comment]
Can you help me please, I have the same issue but it's not a problem with the rights.

I get get this :
/opt/nagios/libexec/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --mode=getmap --connector-hostname=localhost --container=My_Container

UNKNOWN: Cannot get response (timeout received)


He is my conf : 

vSphere SDK for Perl version: 5.1.0
Script 'vmware-cmd' version: 5.1.0
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20170807-2.el7.noarch
centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Esx-Wsman-20170807-1.el7.noarch
centreon-plugin-Virtualization-Nutanix-Snmp-20170807-1.el7.noarch
perl-VMware-vSphere.x86_64           5.1.0-780721.1.el7.centos
perl 5, version 16, subversion 3 (v5.16.3) 
LWP Version: 5.837
Crypt::SSLeay Version: 0.64
Centreon web 2.8.21

When I do test :
#/usr/bin/perl /usr/bin/centreon_vmware.pl --config=/etc/centreon/centreon_vmware.pm
[...]
2020-05-26 13:47:41 - 'My_Container' Vsphere connection ok
2020-05-26 13:47:41 - 'My_Container' Create perf counters cache in progress
2020-05-26 13:47:42 - 'My_Container' Create perf counters cache done

When i execute in another tab like :

 /opt/nagios/libexec/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --mode=getmap --connector-hostname=localhost --container=My_Container

I have this in the first one:

2020-05-26 13:47:42 - vpshere 'VCENTER-SVA' handler asking: {"vm_no":null,"scope_cluster":null,"vsphere_username":null,"scope_datacenter":null,"case_insensitive":null,"timeout":null,"vsphere_password":null,"warning_connector_status":null,"command":"getmap","connector_port":"5700","filter":null,"sampling_period":null,"esx_hostname":null,"container":"VCENTER-SVA","unknown_connector_status":null,"vsphere_address":null,"time_shift":0,"identity":"client-f440f3975d3d4256","connector_hostname":"localhost","critical_connector_status":null}

And get in the second tab:

/opt/nagios/libexec/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --mode=getmap --connector-hostname=localhost --container=My_Container
UNKNOWN: Cannot get response (timeout received)


The rights : 

# ll /var/log/centreon/centreon_vmware.log
-rwxrwxr-x 1 centreon centreon 21923184 May 26 11:21 /var/log/centreon/centreon_vmware.log
drwxrwxr-x 5 centreon     centreon         4096 May 26 14:06 centreon_vmware
srwxr-xr-x 1 centreon     centreon         0 May 26 14:06 routing.ipc

The logs : 

#tailf /var/log/centreon/centreon_vmware.log
`[...]</label><summary>Système</summary><key>sys</key></groupInfo><unitInfo><label>%</label><summary>Pourcentage</summary><key>percent</key></unitInfo><rollupType>latest</rollupType><statsType>absolute</statsType><level>3</level><perDeviceLevel>3</perDeviceLevel></PerfCounterInfo><PerfCounterInfo xsi:type="PerfCounterInfo"><key>447</key><nameInfo><label>Utilisation de ressources CPU (Aucun)</label><summary>Quantité de CPU utilisée par la console de service et par d&apos;autres applications lors de l&apos;intervalle</summary><key>resourceCpuUsage</key></nameInfo><groupInfo><label>Système</label><summary>Système</summary><key>sys</key></groupInfo><unitInfo><label>MHz</label><summary>Mégahertz</summary><key>megaHertz</key></unitInfo><rollupType>none</rollupType><statsType>rate</statsType><level>4</level><perDeviceLevel>4</perDeviceLevel></PerfCounterInfo><PerfCounterInfo xsi:type="PerfCounterInfo"><key>448</key><nameInfo><label>Utilisation de ressources CPU (Moyen)</label><summary>Quantité de CPU utilisée par la console de service et par d&apos;autres applications lors de l&apos;intervalle</summary><key>resourceCpuUsage</key></nameInfo><groupInfo><label>Système</label><summary>Système</summary><key>sys</key></groupInfo><unitInfo><label>MHz</label><summary>Mégahertz</summary><key>megaHertz</key></unitInfo><rollupType>average</rollupType><statsType>rate</statsType><level>3</level><perDeviceLevel>3</perDeviceL
`
