### ISSUE TITLE
[snmp_standard::mode::memory] Total RAM included in the graph

### ISSUE THREAD

**Issue by stephanemarianne** [centreon/centreon-plugins#1417]
## New plugins and modes (argument)

Can you add a new option argument to get the physical memory capacity included in the graph.
the interest is to have a visual reference in the graph of the Mb used compared to the potential Mb / a reference equivalent to the percentage of use...

### the argument to be added......
$options{options}->add_options(arguments =>
                                { 
                                  ...                     
                                  "graph-total-ram"         => { name => 'graph_total_ram' },

 ### the processing of the output...........                                 
     if ( $self->{option_results}->{graph_total_ram} ) {
        $self->{output}->perfdata_add(label => "total", unit => 'B',
                                      value => $total_size,
                                      min => 0);
### the help command
=item B<--graph-total-ram>
Output total ram available in perfdata.

[memory.zip](https://github.com/centreon/centreon-plugins/files/2963044/memory.zip)

**Comment by garnier-quentin** [comment]
You can already do it with following option:
```
--explode-perfdata-max='used,total'
```
