### ISSUE TITLE
SNMP Table Request: Cant get a single value.

### ISSUE THREAD

**Issue by ir3kc4h** [centreon/centreon-plugins#1418]
i have an issue with printer with marker supply usage and cover status thats show me cant get a single value only with Sharp printer with others ones it's ok any help thank y

**Comment by garnier-quentin** [comment]
Could you give us a snmpwalk of your equipment please ?
```
snmpwalk -ObentU -v 2c -c public IPaddress .1 > printer.snmpwalk
```

Thank you

**Comment by ir3kc4h** [comment]
i don't understand your command bro so what i have to do to write 
snmpwalk -ObentU -v 2c -c public 172.31.17.5 > printer.snmpwalk for exemple ?
172.31.17.5 theip of the printer?

**Comment by garnier-quentin** [comment]
```
snmpwalk -ObentU -v 2c -c public 172.31.17.5 .1 > printer.snmpwalk
```

**Comment by ir3kc4h** [comment]
no return 
![image](https://user-images.githubusercontent.com/48556728/54363308-015fa080-466b-11e9-9504-c501fe99cafd.png)

**Comment by garnier-quentin** [comment]
That's the problem. If you have no results, it cannot work. The community is ok ?

**Comment by ir3kc4h** [comment]
.1.3.6.1.2.1.1.1.0 = STRING: SHARP AR-5623N
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.2385.3.1.86.1.3
.1.3.6.1.2.1.1.3.0 = 2598937
.1.3.6.1.2.1.1.4.0 = STRING:
.1.3.6.1.2.1.1.5.0 = STRING:
.1.3.6.1.2.1.1.6.0 = STRING:
.1.3.6.1.2.1.1.7.0 = INTEGER: 64
.1.3.6.1.2.1.2.1.0 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.2.1 = STRING: Ethernet
.1.3.6.1.2.1.2.2.1.3.1 = INTEGER: 6
.1.3.6.1.2.1.2.2.1.4.1 = INTEGER: 1500
.1.3.6.1.2.1.2.2.1.5.1 = Gauge32: 100000000
.1.3.6.1.2.1.2.2.1.6.1 = STRING: 34:f6:2d:8f:f:a8
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.8.1 = INTEGER: 1
.1.3.6.1.2.1.2.2.1.9.1 = 0
.1.3.6.1.2.1.2.2.1.10.1 = Counter32: 20663455
.1.3.6.1.2.1.2.2.1.11.1 = Counter32: 6725
.1.3.6.1.2.1.2.2.1.12.1 = Counter32: 159139
.1.3.6.1.2.1.2.2.1.13.1 = Counter32: 39093
.1.3.6.1.2.1.2.2.1.14.1 = Counter32: 39075
.1.3.6.1.2.1.2.2.1.15.1 = Counter32: 24
.1.3.6.1.2.1.2.2.1.16.1 = Counter32: 2959836
.1.3.6.1.2.1.2.2.1.17.1 = Counter32: 11167
.1.3.6.1.2.1.2.2.1.18.1 = Counter32: 386
.1.3.6.1.2.1.2.2.1.19.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.20.1 = Counter32: 0
.1.3.6.1.2.1.2.2.1.21.1 = Gauge32: 1
.1.3.6.1.2.1.2.2.1.22.1 = OID: .0.0
.1.3.6.1.2.1.3.1.1.1.1.0.0.0.0 = INTEGER: 1
.1.3.6.1.2.1.3.1.1.2.1.0.0.0.0 = Hex-STRING: 3C 52 82 52 D4 E0
.1.3.6.1.2.1.3.1.1.3.1.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.4.1.0 = INTEGER: 2
.1.3.6.1.2.1.4.2.0 = INTEGER: 255
.1.3.6.1.2.1.4.3.0 = Counter32: 118113
.1.3.6.1.2.1.4.4.0 = Counter32: 0
.1.3.6.1.2.1.4.5.0 = Counter32: 260
.1.3.6.1.2.1.4.6.0 = Counter32: 0
.1.3.6.1.2.1.4.7.0 = Counter32: 0
.1.3.6.1.2.1.4.8.0 = Counter32: 0
.1.3.6.1.2.1.4.9.0 = Counter32: 117856
.1.3.6.1.2.1.4.10.0 = Counter32: 554
.1.3.6.1.2.1.4.11.0 = Counter32: 0
.1.3.6.1.2.1.4.12.0 = Counter32: 0
.1.3.6.1.2.1.4.13.0 = INTEGER: 60
.1.3.6.1.2.1.4.14.0 = Counter32: 0
.1.3.6.1.2.1.4.15.0 = Counter32: 0
.1.3.6.1.2.1.4.16.0 = Counter32: 0
.1.3.6.1.2.1.4.17.0 = Counter32: 0
.1.3.6.1.2.1.4.18.0 = Counter32: 0
.1.3.6.1.2.1.4.19.0 = Counter32: 0
.1.3.6.1.2.1.4.20.1.1.172.31.18.162 = IpAddress: 172.31.18.162
.1.3.6.1.2.1.4.20.1.2.172.31.18.162 = INTEGER: 1
.1.3.6.1.2.1.4.20.1.3.172.31.18.162 = IpAddress: 255.255.255.0
.1.3.6.1.2.1.4.20.1.4.172.31.18.162 = INTEGER: 1
.1.3.6.1.2.1.4.20.1.5.172.31.18.162 = INTEGER: 48000
.1.3.6.1.2.1.4.21.1.1.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.4.21.1.2.0.0.0.0 = INTEGER: 1
.1.3.6.1.2.1.4.21.1.3.0.0.0.0 = INTEGER: 1
.1.3.6.1.2.1.4.21.1.4.0.0.0.0 = INTEGER: -1
.1.3.6.1.2.1.4.21.1.5.0.0.0.0 = INTEGER: -1
.1.3.6.1.2.1.4.21.1.6.0.0.0.0 = INTEGER: -1
.1.3.6.1.2.1.4.21.1.7.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.4.21.1.8.0.0.0.0 = INTEGER: 4
.1.3.6.1.2.1.4.21.1.9.0.0.0.0 = INTEGER: 3
.1.3.6.1.2.1.4.21.1.10.0.0.0.0 = INTEGER: 25931
.1.3.6.1.2.1.4.21.1.11.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.4.21.1.12.0.0.0.0 = INTEGER: -1
.1.3.6.1.2.1.4.21.1.13.0.0.0.0 = OID: .0.0
.1.3.6.1.2.1.4.22.1.2.1.0.0.0.0 = STRING: 3c:52:82:52:d4:e0
.1.3.6.1.2.1.4.22.1.3.1.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.4.22.1.4.1.0.0.0.0 = INTEGER: 3
.1.3.6.1.2.1.5.1.0 = Counter32: 66
.1.3.6.1.2.1.5.2.0 = Counter32: 0
.1.3.6.1.2.1.5.3.0 = Counter32: 0
.1.3.6.1.2.1.5.4.0 = Counter32: 0
.1.3.6.1.2.1.5.5.0 = Counter32: 0
.1.3.6.1.2.1.5.6.0 = Counter32: 0
.1.3.6.1.2.1.5.7.0 = Counter32: 0
.1.3.6.1.2.1.5.8.0 = Counter32: 66
.1.3.6.1.2.1.5.9.0 = Counter32: 0
.1.3.6.1.2.1.5.10.0 = Counter32: 0
.1.3.6.1.2.1.5.11.0 = Counter32: 0
.1.3.6.1.2.1.5.12.0 = Counter32: 0
.1.3.6.1.2.1.5.13.0 = Counter32: 0
.1.3.6.1.2.1.5.14.0 = Counter32: 66
.1.3.6.1.2.1.5.15.0 = Counter32: 0
.1.3.6.1.2.1.5.16.0 = Counter32: 0
.1.3.6.1.2.1.5.17.0 = Counter32: 0
.1.3.6.1.2.1.5.18.0 = Counter32: 0
.1.3.6.1.2.1.5.19.0 = Counter32: 0
.1.3.6.1.2.1.5.20.0 = Counter32: 0
.1.3.6.1.2.1.5.21.0 = Counter32: 0
.1.3.6.1.2.1.5.22.0 = Counter32: 66
.1.3.6.1.2.1.5.23.0 = Counter32: 0
.1.3.6.1.2.1.5.24.0 = Counter32: 0
.1.3.6.1.2.1.5.25.0 = Counter32: 0
.1.3.6.1.2.1.5.26.0 = Counter32: 0
.1.3.6.1.2.1.6.1.0 = INTEGER: 4
.1.3.6.1.2.1.6.2.0 = INTEGER: 2
.1.3.6.1.2.1.6.3.0 = INTEGER: 600
.1.3.6.1.2.1.6.4.0 = INTEGER: 32
.1.3.6.1.2.1.6.5.0 = Counter32: 1489
.1.3.6.1.2.1.6.6.0 = Counter32: 39
.1.3.6.1.2.1.6.7.0 = Counter32: 1
.1.3.6.1.2.1.6.8.0 = Counter32: 0
.1.3.6.1.2.1.6.9.0 = Gauge32: 1
.1.3.6.1.2.1.6.10.0 = Counter32: 6297
.1.3.6.1.2.1.6.11.0 = Counter32: 12231
.1.3.6.1.2.1.6.12.0 = Counter32: 16
.1.3.6.1.2.1.6.13.1.1.0.0.0.0.80.0.0.0.0.0 = INTEGER: 2
.1.3.6.1.2.1.6.13.1.1.0.0.0.0.515.0.0.0.0.0 = INTEGER: 2
.1.3.6.1.2.1.6.13.1.1.0.0.0.0.631.0.0.0.0.0 = INTEGER: 2
.1.3.6.1.2.1.6.13.1.1.0.0.0.0.9100.0.0.0.0.0 = INTEGER: 2
.1.3.6.1.2.1.6.13.1.1.0.0.0.0.19540.0.0.0.0.0 = INTEGER: 2
.1.3.6.1.2.1.6.13.1.2.0.0.0.0.80.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.2.0.0.0.0.515.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.2.0.0.0.0.631.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.2.0.0.0.0.9100.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.2.0.0.0.0.19540.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.3.0.0.0.0.80.0.0.0.0.0 = INTEGER: 80
.1.3.6.1.2.1.6.13.1.3.0.0.0.0.515.0.0.0.0.0 = INTEGER: 515
.1.3.6.1.2.1.6.13.1.3.0.0.0.0.631.0.0.0.0.0 = INTEGER: 631
.1.3.6.1.2.1.6.13.1.3.0.0.0.0.9100.0.0.0.0.0 = INTEGER: 9100
.1.3.6.1.2.1.6.13.1.3.0.0.0.0.19540.0.0.0.0.0 = INTEGER: 19540
.1.3.6.1.2.1.6.13.1.4.0.0.0.0.80.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.4.0.0.0.0.515.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.4.0.0.0.0.631.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.4.0.0.0.0.9100.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.4.0.0.0.0.19540.0.0.0.0.0 = IpAddress: 0.0.0.0
.1.3.6.1.2.1.6.13.1.5.0.0.0.0.80.0.0.0.0.0 = INTEGER: 0
.1.3.6.1.2.1.6.13.1.5.0.0.0.0.515.0.0.0.0.0 = INTEGER: 0
.1.3.6.1.2.1.6.13.1.5.0.0.0.0.631.0.0.0.0.0 = INTEGER: 0
.1.3.6.1.2.1.6.13.1.5.0.0.0.0.9100.0.0.0.0.0 = INTEGER: 0
.1.3.6.1.2.1.6.13.1.5.0.0.0.0.19540.0.0.0.0.0 = INTEGER: 0
.1.3.6.1.2.1.6.14.0 = Counter32: 0
.1.3.6.1.2.1.6.15.0 = Counter32: 3
.1.3.6.1.2.1.7.1.0 = Counter32: 119203
.1.3.6.1.2.1.7.2.0 = Counter32: 46927
.1.3.6.1.2.1.7.3.0 = Counter32: 0
.1.3.6.1.2.1.7.4.0 = Counter32: 677
.1.3.6.1.2.1.11.1.0 = Counter32: 0
.1.3.6.1.2.1.11.2.0 = Counter32: 352
.1.3.6.1.2.1.11.3.0 = Counter32: 0
.1.3.6.1.2.1.11.4.0 = Counter32: 0
.1.3.6.1.2.1.11.5.0 = Counter32: 0
.1.3.6.1.2.1.11.6.0 = Counter32: 0
.1.3.6.1.2.1.11.8.0 = Counter32: 0
.1.3.6.1.2.1.11.9.0 = Counter32: 0
.1.3.6.1.2.1.11.10.0 = Counter32: 0
.1.3.6.1.2.1.11.11.0 = Counter32: 0
.1.3.6.1.2.1.11.12.0 = Counter32: 0
.1.3.6.1.2.1.11.13.0 = Counter32: 1629
.1.3.6.1.2.1.11.14.0 = Counter32: 0
.1.3.6.1.2.1.11.15.0 = Counter32: 0
.1.3.6.1.2.1.11.16.0 = Counter32: 340
.1.3.6.1.2.1.11.17.0 = Counter32: 0
.1.3.6.1.2.1.11.18.0 = Counter32: 0
.1.3.6.1.2.1.11.19.0 = Counter32: 0
.1.3.6.1.2.1.11.20.0 = Counter32: 0
.1.3.6.1.2.1.11.21.0 = Counter32: 7
.1.3.6.1.2.1.11.22.0 = Counter32: 0
.1.3.6.1.2.1.11.24.0 = Counter32: 0
.1.3.6.1.2.1.11.25.0 = Counter32: 0
.1.3.6.1.2.1.11.26.0 = Counter32: 0
.1.3.6.1.2.1.11.27.0 = Counter32: 0
.1.3.6.1.2.1.11.28.0 = Counter32: 376
.1.3.6.1.2.1.11.29.0 = Counter32: 0
.1.3.6.1.2.1.11.30.0 = INTEGER: 2
.1.3.6.1.2.1.25.3.2.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.25.3.2.1.2.1 = OID: .1.3.6.1.2.1.25.3.1.5
.1.3.6.1.2.1.25.3.2.1.3.1 = STRING: AR-5623N
.1.3.6.1.2.1.25.3.2.1.4.1 = OID: .1.3.6.1.2.1.25.3.1.5
.1.3.6.1.2.1.25.3.2.1.5.1 = INTEGER: 2
.1.3.6.1.2.1.25.3.2.1.6.1 = Counter32: 0
.1.3.6.1.2.1.25.3.5.1.1.1 = INTEGER: 3
.1.3.6.1.2.1.25.3.5.1.2.1 = Hex-STRING: 00
.1.3.6.1.2.1.25.3.5.1.2.1 = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by ir3kc4h** [comment]
any help mr @garnier-quentin

**Comment by garnier-quentin** [comment]
Your printer doesn't manage rfc standard snmp for printers. Maybe there is an other way to monitor it (rest api, ssh command,...)

**Comment by ir3kc4h** [comment]
thank u very much , and one more question please , when i get this message with other hosts or services that mean the same problem ? like Qos Usage with Net-Cisco-Standar-SNMP plugin

**Comment by garnier-quentin** [comment]
Most of time it's that yes.
