### ISSUE TITLE
database::oracle::mode::datacachehitratio > 100%

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1419]
Centreon 18.10
Centreon Plugins 20190221

./centreon_plugins --plugin=database::oracle::plugin --hostname=x.x.x.x --port=1521 --sid=SID --username=user --password=*** --mode=datacache-hitratio --warning=90: --critical=80:

OK: Buffer cache hit ratio is 100.26%

**Comment by joschi99** [comment]
The result of the SQL from the plugin:

SQL> SELECT SUM(DECODE(name, 'physical reads', value, 0)),
  2              SUM(DECODE(name, 'physical reads direct', value, 0)),
  3              SUM(DECODE(name, 'physical reads direct (lob)', value, 0)),
  4              SUM(DECODE(name, 'session logical reads', value, 0))
  5          FROM sys.v_$sysstat;

SUM(DECODE(NAME,'PHYSICALREADS',VALUE,0))
-----------------------------------------
SUM(DECODE(NAME,'PHYSICALREADSDIRECT',VALUE,0))
-----------------------------------------------
SUM(DECODE(NAME,'PHYSICALREADSDIRECT(LOB)',VALUE,0))
----------------------------------------------------
SUM(DECODE(NAME,'SESSIONLOGICALREADS',VALUE,0))
-----------------------------------------------
                               1762968691
                                     1375886869
                                           950372352
                                     2.1795E+11

**Comment by garnier-quentin** [comment]
Could you test with the last version please ?

**Comment by joschi99** [comment]
Hi @garnier-quentin,
some seem's wrong:
```
[root@rvvmive01pl plugins]# ./centreon_plugins.pl --plugin=database::oracle::plugin --hostname=x.x.x.x --port=1521 --sid=XXX --username=xxx --password=xxx --mode=datacache-hitratio --warning=90: --critical=80:
Unknown option: warning at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.
```

**Comment by garnier-quentin** [comment]
I changed arguments:
```
--warning-usage='' --critical-usage=''
```

**Comment by joschi99** [comment]
Oups, you are right.

But values are still over 100%

```
[root@rvvmive01pl plugins]# ./centreon_plugins.pl --plugin=database::oracle::plugin --hostname=x.x.x.x --port=1521 --sid=XXX --username=xxx --password=xxx --mode=datacache-hitratio
OK: Buffer cache hit ratio is 100.98% | 'sga_data_buffer_hit_ratio'=100.98%;;;0;100
Segmentation fault
```

**Comment by garnier-quentin** [comment]
I could set 100% if it's over 100.

**Comment by joschi99** [comment]
Normally a Hit Ratio cannot be > 100%. If the problem is related to Oracle (maybe a bug) it could be a good idea to set maximum 100. Otherwise maybe we have to check if the calculation is done in the right way.

Hit Ratio = Logical Reads - Physical Reads / Logical Reads
```
SQL> SELECT 1-(a.value / (b.value + c.value))
 "Hit Ratio"
 FROM v$sysstat a, v$sysstat b, v$sysstat c
 WHERE a.name = 'physical reads'
 AND b.name = 'db block gets'
 AND c.name = 'consistent gets'; 

 Hit Ratio
----------
.990255964
```
With this approach we have a Buffer Hit Ration about 99,03% (http://www.dba-oracle.com/t_oracle_net_calculate_buffer_cache.htm).

**Comment by garnier-quentin** [comment]
I use following request. 
```
SELECT SUM(DECODE(name, 'physical reads', value, 0)),
            SUM(DECODE(name, 'physical reads direct', value, 0)),
            SUM(DECODE(name, 'physical reads direct (lob)', value, 0)),
            SUM(DECODE(name, 'session logical reads', value, 0))
        FROM sys.v_$sysstat
```

**Comment by joschi99** [comment]
I found this official Oracle doc about calculating the Buffer Cache Hit Ratio: https://docs.oracle.com/database/121/TGDBA/tune_buffer_cache.htm#TGDBA533

```
SELECT name, value
FROM V$SYSSTAT
WHERE name IN ('db block gets from cache', 'consistent gets from cache', 
'physical reads cache');

1 - (('physical reads cache') / ('consistent gets from cache' + 
'db block gets from cache'))
```

As you can see the calculation is the same as in my example above, but different from your calculation. Maybe the calculation in the plugin is wrong.

**Comment by garnier-quentin** [comment]
Could you test with the last version please ?

**Comment by joschi99** [comment]
Hi @garnier-quentin,
test is failed:

```
./centreon_plugins.pl --plugin=database::oracle::plugin --hostname=x.x.x.x --port=1521 --sid=SID --username=xxx --password=xxx --mode=datacache-hitratio --warning-usage=90: --critical-usage=80:
UNKNOWN: Cannot execute query: ORA-00936: missing expression (DBD ERROR: error possibly near <*> indicator at char 189 in '
        SELECT SUM(DECODE(name, 'physical reads', value, 0)),
            SUM(DECODE(name, 'db block gets', value, 0)),
            SUM(DECODE(name, 'consistent gets', value, 0)),
        <*>FROM sys.v_$sysstat
    ')
```

**Comment by garnier-quentin** [comment]
It's fixed. It should work.

**Comment by joschi99** [comment]
Seem's working:
`OK: Buffer cache hit ratio is 97.92% | 'sga_data_buffer_hit_ratio'=97.92%;90:;80:;0;100`
