### ISSUE TITLE
Plugin OS-Windows-NSClient05-NRPE-Disks

### ISSUE THREAD

**Issue by enumanc** [centreon/centreon-plugins#1420]
Hello,

I would like to share an enhancement of the following controle: OS-Windows-NSClient05-NRPE-Disks:
Is it possible to improve the output of the plugin when a threshhold is reached, the output is:
WARNING warning(C:\: 74.959GB/185.232GB used)

is it possible to add the FREE space like in the SNMP version ?
Ok: Storage 'C:' Usage Total: 135.48 GB Used: 27.28 GB (20.13%) Free: 108.20 GB (79.87%)
ou comme sur un ancien controle:
Disk OK - C: TOTAL: 59.655GB USED: 49.088GB (82%) FREE: 10.567GB (18%)

And why not format the output similar to SNMP version:
OK: <Partition>: TOTAL: xxx GB USED: yyy GB (YY%) FREE: zzz GB (ZZ%)

Commande:
/usr/lib/nagios/plugins/check_centreon_nrpe
	-H xxxxxxxxx
	-p 5666
	-t 30
	-u
	-m 8192 
	-c check_drivesize
	-a "drive=*" "perf-config=used(unit:B)used %(ignored:true)" "filter=type = 'fixed' and name not regexp '.*yst.*'" "warning=total_used>80%" "critical=total_used>90%" show-all

Regards,
Emmanuel

**Comment by garnier-quentin** [comment]
You can configure the output with nsclient options.

**Comment by garnier-quentin** [comment]
I close it. It's not a issue with centreon-plugins.
