### ISSUE TITLE
Setup redis check replication 

### ISSUE THREAD

**Issue by hoanpv3993** [centreon/centreon-plugins#1421]
Hi all,
I use command to check slave connet to master in Redis
I have 1 master and 2 slave, but when i test with below command:

```bash
./centreon_plugins.pl --plugin=apps::redis::cli::plugin --mode=replication --hostname=192.168.10.10 --port=6379 --warning-connected-slaves=1 --critical-connected-slaves=0 --critical-status='%{link_status} =~ /down/i'
CRITICAL: Number of connected slaves: 2 | 'connected_slaves'=2;0:1;0:0;0; 'master_repl_offset'=1756860230310s;;;0;
```
Master Node is 192.168.10.10
I think with up result it is OK not CRITICAL
In mycase, i want to set `warning` if it has 1 slave and `critical` if not has any slave

I also see similar case in other plugins
I search code to fix , but not found any line relative to compare this value.
Anyone can help me.
Thanks all

**Comment by garnier-quentin** [comment]
You can use following options so:
```
--warning-connected-slaves=2: --critical-connected-slaves=1:
```

**Comment by hoanpv3993** [comment]
Hi garnier-quentin,

I tests but script not repone warning or critical

```bash
./centreon_plugins.pl --plugin=apps::redis::cli::plugin --mode=replication --hostname=192.168.10.10  --port=6379 --warning-connected-slaves=2: --critical-connected-slaves=2:
OK: Node role is 'master' [cluster: disabled], Number of connected slaves: 2 - Master replication offset: 1759174722543 s | 'connected_slaves'=2;2:;2:;0; 'master_repl_offset'=1759174722543s;;;0;
```

**Comment by garnier-quentin** [comment]
You have 2 slaves connected. Threshold critical is slaves connected < 2.

**Comment by hoanpv3993** [comment]
Thanks for your help, Garnier-quentin.
