### ISSUE TITLE
Issue with os::linux::snmp::plugin --mode=cpu

### ISSUE THREAD

**Issue by plpicard** [centreon/centreon-plugins#1422]
Hi,

When I want to use this plugin, it is preconfigured in commands like : $CENTREONPLUGINS$/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning-average='$_SERVICEWARNING$' --critical-average='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$ 

But the result is : Unknown option: warning-average at centreon_linux_snmp.pl line 142.
And thats right because if I check available options : 
Mode:
    Check system CPUs (HOST-RESOURCES-MIB) (The average, over the last
    minute, of the percentage of time that this processor was not idle)
    --warning
            Threshold warning in percent.
    --critical
            Threshold critical in percent.

Not average at all for this plugin.

And if I ran this command : perl centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=IPof MyServer --snmp-version=2c --snmp-community=MyCommunity --warning=90 --critical=95
The result is : 
OK: 2 CPU(s) average usage is: 1.00% | 'cpu0'=1.00%;;;0;100 'cpu1'=1.00%;;;0;100 'total_cpu_avg'=1.00%;0:90;0:95;0;100

If you have any information about that, I'm glad to read your answer.

Thanks,
Pierre-Laurent

**Comment by garnier-quentin** [comment]
Please update the rpm plugin also.

**Comment by plpicard** [comment]
How can I update the rpm of the plugin ? 
I installed it with this git repository.

**Comment by garnier-quentin** [comment]
So you should update your repository.
```
git pull origin master
```

**Comment by plpicard** [comment]
Ok right, thank you because ran command yum update centreon-plugins returns "No package marked for update".
I'll keep you inform

**Comment by plpicard** [comment]
In fact, I installed Centreon Plugins with yum ... sorry :) But he find no updates for it...

**Comment by garnier-quentin** [comment]
The package is centreon-plugin-Operatingsystems-Linux-Snmp

**Comment by plpicard** [comment]
After updated the package, my commands of linux snmp plugin is already : 
![image](https://user-images.githubusercontent.com/48358659/54439168-91b7e700-4738-11e9-83a0-b39b412a0794.png)
I restarted centengine and i update centreon_plugins by a new git clone

**Comment by plpicard** [comment]
Ok it works now :)
Thanl you for yoru help, your quickly reply was very appreciate. :)

**Comment by garnier-quentin** [comment]
You're welcome. Thanks for using centreon-plugins!
