### ISSUE TITLE
network::cisco::asa::snmp::plugin --mode failover sync of dap.xml?

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#1423]
Hi all,
ist it possible to check the sync of the dap.xml for 2 ASAs in a failover grouping? 

Cheers,
Marcus

**Comment by garnier-quentin** [comment]
Could you explain it ?

**Comment by MarcusCaepio** [comment]
Sure. When you got 2 ASAs in a failover cluster, the dap.xml should be synced between them. the dap.xml includes all user, devices and permissions of VPN. 

> DAP complements AAA services. It provides a limited set of authorization attributes that can override those AAA provides. ... You can specify AAA attributes from the Cisco AAA attribute hierarchy, or from the full set of response attributes that the ASA receives from a RADIUS or LDAP server.
https://www.cisco.com/c/en/us/td/docs/security/asa/asa91/asdm71/vpn/asdm_71_vpn_config/vpn_asdm_dap.pdf

So it is necessary to have this file in sync in case of a failover. Otherwise, it could happen that users and/ or permissions of VPN are gone. The dap.xml is saved directly in the root directory of the asa and could be checked via a checksum.

**Comment by garnier-quentin** [comment]
Where do you get that information in SNMP ?

**Comment by MarcusCaepio** [comment]
I'm afraid there is no way to get this via snmp, but via SSH. At least I cannot find sth. right now to get it via SNMP.

**Comment by garnier-quentin** [comment]
Could you give us cli commands and returns ?

**Comment by MarcusCaepio** [comment]
Currently we are copying both dap.xml to the monitoring local server, create a md5 checksum and compare them, because there are no CLI commands to get this info. Maybe you guys have a smarter idea to solve this? :)

**Comment by garnier-quentin** [comment]
So that's too specific. You can use linux local plugin with command-return mode.
