### ISSUE TITLE
Unable to ask for memory usage or load with os::linux::snmp::plugin

### ISSUE THREAD

**Issue by plpicard** [centreon/centreon-plugins#1424]
Hi,

I tried to check my linux servers memory with plugin os::linux::snmp::plugin through centreon_linux_snmp.pl without success. I get the following return : 
command : perl centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --snmp-version=2c --snmp-community=mycommunity--hostname=IPserver --mode=memory
return : UNKNOWN: SNMP GET Request : Cant get a single value.

I already saw this related issue https://github.com/centreon/centreon-plugins/issues/1111 and doesn't help me more. I checked the MIBs for storage, I have this : 
HOST-RESOURCES-MIB::hrStorageIndex.1 = INTEGER: 1
HOST-RESOURCES-MIB::hrStorageIndex.3 = INTEGER: 3
HOST-RESOURCES-MIB::hrStorageIndex.6 = INTEGER: 6
HOST-RESOURCES-MIB::hrStorageIndex.7 = INTEGER: 7
HOST-RESOURCES-MIB::hrStorageIndex.8 = INTEGER: 8
HOST-RESOURCES-MIB::hrStorageIndex.10 = INTEGER: 10
HOST-RESOURCES-MIB::hrStorageIndex.31 = INTEGER: 31
HOST-RESOURCES-MIB::hrStorageIndex.32 = INTEGER: 32
HOST-RESOURCES-MIB::hrStorageIndex.37 = INTEGER: 37
HOST-RESOURCES-MIB::hrStorageIndex.39 = INTEGER: 39
HOST-RESOURCES-MIB::hrStorageIndex.40 = INTEGER: 40
HOST-RESOURCES-MIB::hrStorageIndex.41 = INTEGER: 41
HOST-RESOURCES-MIB::hrStorageIndex.55 = INTEGER: 55
HOST-RESOURCES-MIB::hrStorageType.1 = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageType.3 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.6 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.7 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.8 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.10 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.31 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.32 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.37 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.39 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.40 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.41 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.55 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageDescr.1 = STRING: Physical memory
HOST-RESOURCES-MIB::hrStorageDescr.3 = STRING: Virtual memory
HOST-RESOURCES-MIB::hrStorageDescr.6 = STRING: Memory buffers
HOST-RESOURCES-MIB::hrStorageDescr.7 = STRING: Cached memory
HOST-RESOURCES-MIB::hrStorageDescr.8 = STRING: Shared memory
HOST-RESOURCES-MIB::hrStorageDescr.10 = STRING: Swap space
HOST-RESOURCES-MIB::hrStorageDescr.31 = STRING: /
HOST-RESOURCES-MIB::hrStorageDescr.32 = STRING: /var
HOST-RESOURCES-MIB::hrStorageDescr.37 = STRING: /run
HOST-RESOURCES-MIB::hrStorageDescr.39 = STRING: /dev/shm
HOST-RESOURCES-MIB::hrStorageDescr.40 = STRING: /run/lock
HOST-RESOURCES-MIB::hrStorageDescr.41 = STRING: /sys/fs/cgroup
HOST-RESOURCES-MIB::hrStorageDescr.55 = STRING: /home

And if I check somes MIBs, this don't work...
[root@xxxxxxxxxxxx]# snmpwalk -c mycommunity -v 2c IPserverf hrStorageVirtualMemory
HOST-RESOURCES-TYPES::hrStorageVirtualMemory = No Such Object available on this agent at this OID

The same problem withe load mode, or cpu-detailed, 
I can have values with, CPU, storage, list-storages... :)

So I'm asking for help :) :)
I don't know how can I manage my memory usage on my linux servers with this plugin.
Plugins are up-to-date.

Best regards,
Pierre-Laurent front France.

**Comment by garnier-quentin** [comment]
The mode check following branch: .1.3.6.1.4.1.2021.4
You can try to snmpwalk that branch. If you cannot get it: configure snmp agent.

**Comment by plpicard** [comment]
In meantime, how can I get value in this form 1.3.6.1.4.1.2021.4 ? I would like to know how to :)
I'm going to check :)

**Comment by garnier-quentin** [comment]
In your snmpd.conf file, you can set branch allowed.

**Comment by plpicard** [comment]
Yep, I know this is in the snmpd.conf file ;) 
The result is : UCD-SNMP-MIB::memory = No more variables left in this MIB View (It is past the end of the MIB tree)

By the way, what I need to modify in this section ?
###############################################################################
#
#  ACCESS CONTROL
#

                                                 #  system + hrSystem groups only
view   systemonly  included   .1.3.6.1.2.1
view   systemonly  included   .1.3.6.1.2.1.25.1

**Comment by garnier-quentin** [comment]
Need to add:
```
view systemonly included .1.3.6.1.4.1.2021
```

**Comment by plpicard** [comment]
You're awsome, it works very well 🥇  !!
So, for others mode didn't work, mentionned in my first post, how can get the value like for memory ?
Or, how can I open more the systemview to get my values ?

**Comment by garnier-quentin** [comment]
Mode like 'load', 'cpu-detailed' will work now (same branch).

**Comment by plpicard** [comment]
You're perfect man !! 
And for my last question : how can get the value like for memory in this format .1.3.6.1.4.1.2021 ?

**Comment by plpicard** [comment]
Quentin ?

**Comment by garnier-quentin** [comment]
Memory is also in that branch. I don't understand your question.

**Comment by plpicard** [comment]
My question is : How can you get this branch .1.3.6.1.4.1.2021 ? How do you find this reference ? I would like to know to learn more ;)

**Comment by garnier-quentin** [comment]
It's in the code source.

**Comment by plpicard** [comment]
Ok, code source of Linux I guess :)
Many thanks to you.
