### ISSUE TITLE
ZFS system monitoring  : UNKNOWN: SNMP Table Request: Cant get a single value.

### ISSUE THREAD

**Issue by nakasix** [centreon/centreon-plugins#1425]
Hello,

I am currently configuring the ZFS system monitoring with the "**storage::oracle::zs::snmp::plugin**" plugin. However, I am confronted with some worries.

**First**, when I execute the following command : 
```
./centreon_plugins.pl --plugin=storage::oracle::zs::snmp::plugin --mode=**hardware** --hostname=[hostname] --snmp-community=[snmp-community] --snmp-version=2 --verbose
```
I get the following result : 
```
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
OK: All 0 components are ok []. |
Checking modules
```
So, after a search, I add the following line in my snmpd.conf : 
```
echo "includeAllDisks 10%" >> /etc/net-snmp/snmp/snmpd.conf
```
**Secondly**, when I execute the following command : 
```
./centreon_plugins.pl --plugin=storage::oracle::zs::snmp::plugin --mode=**hardware** --hostname=[hostname] --snmp-community=[snmp-community] --snmp-version=2 --verbose
```
I get the following fail result : 
```
OK: All 0 components are ok []. |
Checking modules
```
Moreover with the following command : 
```
./centreon_plugins.pl --plugin=storage::oracle::zs::snmp::plugin --mode=**share-usage** --hostname=[hostname] --snmp-community=[snmp-community] --snmp-version=2 --verbose
```
I get the following result : 
```
UNKNOWN: SNMP Table Request: Cant get a single value.
```

**The systems are :** 
ZFS on OmniOS v11 r151022at and the content of "snmpd.conf" is : 
```
rocommunity [snmp-community] [ip]
includeAllDisks 10%
```
Centreon 18.10.3 with centreon plugins from clone git (today).

Thanks for your help 😄

**Comment by garnier-quentin** [comment]
We check following branch: .1.3.6.1.4.1.42.2.225
If you have nothing with snmpwalk it cannot work. Could you get a full snmpwalk ?

**Comment by nakasix** [comment]
Hello,

A snmpwalk since my poller on .1.3.6.1.4.1.42.2.225 gives me : 
```
SNMPv2-SMI::enterprises.42.2.225 = No Such Object available on this agent at this OID
```

if you wish, I can send you by email the full snmpwalk (it works).

Thanks,

**Comment by garnier-quentin** [comment]
You can sent me to qgarnier@centreon.com

**Comment by garnier-quentin** [comment]
I don't have response. I think it doesn't poll the good IP.
