### ISSUE TITLE
would it be possible to add an option to change the unit by one metric.

### ISSUE THREAD

**Issue by stephanemarianne** [centreon/centreon-plugins#1426]
## Bug/Question

would it be possible to add an option to change the unit by one metric.

For example, the Linux memory is delivered in unit='B'.
It would be a question of being able to replace if necessary by unit='bytes' to maximize the usability of the RRds from Centreon. 
Perhaps the possibility already exists?

**Comment by garnier-quentin** [comment]
I don't understand. 'B' means 'bytes'. You have option to:
```
--change-perfdata
--extend-perfdata
```

There is an article of Eric Coquard which used above options:
https://www.sugarbug.fr/atelier/techniques/ihmweb/cartographie_supervision/nagvis/nagvis_weathermap/

**Comment by stephanemarianne** [comment]
I don't need to rename the metric.  I would like to change the unit ...
from this:
 'cached'=1184501760B;;;0; 'buffer'=328732672B;;;0; 'used'=2056396800B;;;0;4143575040
to this 👍
'cached'=1184550912bytes;;;0; 'buffer'=328732672bytes;;;0; 'used'=2055856128bytes;;;0;4143575040

tio feed the RRd file with this unit in 'bytes'  in some cases

**Comment by garnier-quentin** [comment]
You can use following option:
```
--change-perfdata='B,,,bytes'
```

**Comment by stephanemarianne** [comment]
it doesn't fit my need.... this --change-perfdata='B,,,bytes'  only change the label .

i  need to change the unit . 
from 👎  'used'=2055856128B;
to 👍:      'used'=2055856128bytes;

**Comment by garnier-quentin** [comment]
'B' and 'bytes' are the same. I don't understand.

**Comment by stephanemarianne** [comment]
yes B and bytes are indeed the same notion.
But We have a product that makes queries on the database of Centreon in table "metrics" and unfortunately with a unit_name in "bytes" our tools correctly convert the values in B, MB, GB and TB but with a "unit_name" in 'B' our tools performs a poor scaling...
On our side, modifying the unit from the plugins is the easiest way to get a perfect scaling

**Comment by garnier-quentin** [comment]
Could you show me: the default plugin output, output with change-perfdata above and output you want.

**Comment by stephanemarianne** [comment]
default perfdata output (only the metric part here)
'cached'=1184501760B;;;0; 'buffer'=328732672B;;;0; 'used'=2056396800B;;;0;4143575040

What we want with custom memory.pm
'cached'=1184550912bytes;;;0; 'buffer'=328732672bytes;;;0; 'used'=2055856128bytes;;;0;4143575040

**Comment by garnier-quentin** [comment]
Add that option: --change-perfdata='B,,,bytes'
You'll get what you want.

**Comment by stephanemarianne** [comment]
Doesn't work .  it only works for change the label. I try it with a fresh git clone ...

**Comment by garnier-quentin** [comment]
It should change the UOM only with:  --change-perfdata='cached|used|buffer,,,bytes'

**Comment by stephanemarianne** [comment]
It doesn't work for me...

 /usr/lib/nagios/plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --mode=memory --hostname=******* --snmp-community=public --snmp-version=2c --change-perfdata='cached|used|buffer,,,bytes'  

OK: Ram Total: 5.70 GB Used (-buffers/cache): 593.74 MB (10.17%), Buffer: 279.43 MB, Cached: 4.70 GB, Shared: 0.00 B | ',,bytes'=622583808B;;;0;6120390656 ',,bytes'=293007360B;;;0; ',,bytes'=5045923840B;;;0; 'shared'=0B;;;0;

**Comment by garnier-quentin** [comment]
It's working for me:
```
perl centreon_plugins.pl --plugin os::linux::snmp::plugin --mode=memory --hostname=127.0.0.1 --snmp-community=public --snmp-version=2c --change-perfdata='cached|used|buffer,,,bytes'
OK: Ram Total: 1.80 GB, Used (-buffers/cache): 445.32 MB (24.22%), Buffer: 2.06 MB, Cached: 248.48 MB, Shared: 8.91 MB | 'cached'=260546560bytes;;;0; 'buffer'=2158592bytes;;;0; 'used'=466948096bytes;;;0;1927806976
```

**Comment by Sims24** [comment]
Hi @stephanemarianne 

Sorry I was AFK during my PTO. I think you do not have the last plugin version on your poller that's the only thing I can add to Quentin's answers. 

Will contact you next week,
