### ISSUE TITLE
[templates::counter] Compute max value

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1427]
Hi,

Would be nice to compute max value for counter template.

Here's an example :
`--plugin=os::linux::snmp::plugin --mode=cpu` currently gives as perfdata :
`'total_cpu_avg'=5.00%;;;0;100 'cpu_0'=9.00%;;;0;100 'cpu_1'=1.00%;;;0;100`

Would be nice to add in perfdata :
`'total_cpu_max'=9.00%;;;0;100`

We would then be able to graph the highest used CPU, whatever it is.

Thank you 👍

**Comment by garnier-quentin** [comment]
I see but i'm think it should be done by your monitoring software.

**Comment by CPbN** [comment]
So directly by Centreon itself you mean ?

**Comment by garnier-quentin** [comment]
Centreon or icinga or other systems :)
