### ISSUE TITLE
[network::mikrotik] Missing Centos package

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1428]
Hi,

`network::mikrotik` plugin is not available through Centos packages.
Perhaps you forgot to add it ?

Thank you very much :+1:

**Comment by garnier-quentin** [comment]
It's not an issue with centreon-plugins ;)

**Comment by CPbN** [comment]
OK :)
Which repo is reponsible for packages build ? :)

**Comment by garnier-quentin** [comment]
None :) You can call the support.

**Comment by CPbN** [comment]
Any support mail address perhaps ? Thank you again.
