### ISSUE TITLE
HP5900CP -  h3c / snmp / mode / hardware.pm - Status is "not supported" port 

### ISSUE THREAD

**Issue by Stephano31** [centreon/centreon-plugins#1430]
Hello everybody,

I have an issue using the h3c hardware plugin for my **HP5900CP**. 
Everything is working fine for all the others modes but for hardware mode, Centreon is returning a "Warning" status with that kind of status information: 

WARNING: port 'HP > HP FF 5900CP-48XG-4QSFP+ Switch Software Version 7.1.045 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ten-GigabitEthernet1/0/1' status is 'notSupported' - port 'HP > HP FF 5900CP-48XG-4QSFP+ Switch Software Version 7.1.045 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ten-GigabitEthernet1/0/2' status is 'notSupported' - port 'HP > HP FF 5900CP-48XG-4QSFP+ Switch Software Version 7.1.045 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ten-GigabitEthernet1/0/3' status is 'notSupported' .........

And :

container 'HP > HP FF 5900CP-48XG-4QSFP+ Switch Software Version 7.1.045 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2' status is 'normal' [instance = 374]
container 'HP > HP FF 5900CP-48XG-4QSFP+ Switch Software Version 7.1.045 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2' status is 'normal' [instance = 375] ........

I have this issue ONLY with the **5900CP**, indeed, I have the same plugin used for **5130** and everything works fine. Centreon returns : 
OK: All 56 components are ok [1/1 chassis, 19/19 container ...........]

I searched on the Internet and ask Centreon support for some help but they could not find the solution saying that the problem could comes from the plugin and needs to be improved. 

What do you think about that ?  It might be a well known problem but I'm not a professional with plugins and Centreon :) 

Thanks you in advance. 
Stephan

**Comment by garnier-quentin** [comment]
You can use following option if it's not an error for you:
```
--threshold-overload='port,OK,notSupported'
```

**Comment by Stephano31** [comment]
Thanks for your answer, Centreon Support already gave me this solution, I tried it and it works. 

But the problem is that the commands just replaces the result and show what we want to see even if it's wrong. Tell me if I am wrong please.
What if the port is really broken ? What would be the result in Centreon ? Critical ? 
I know that ports are ok because others mode returns good status about them, so it is not an error.

**Comment by garnier-quentin** [comment]
So you can filter the instance. 
```
--filter=port,INSTANCENUMBER
```
