### ISSUE TITLE
Interrogating a new OID

### ISSUE THREAD

**Issue by maffeltranger** [centreon/centreon-plugins#1431]
Hello everyone !

I'm trying to interrogate one specific OID (dskPercent.1 -> .1.3.6.1.4.1.2021.9.1.9.1)
It's working fine with snmpwalk, I got the integer I expect.

Is there a way to check this OID in a service ? Right now, I use os::linux::snmp::plugin but I can't get the values in % since it's not the same OID (Used space on the disk: .1.3.6.1.4.1.2021.9.1.8.1)

Thanks for you help !

Regards

**Comment by garnier-quentin** [comment]
There is a mode. Could you test: --plugin=os/linux/snmp/plugin.pm --mode=disk-usage

**Comment by garnier-quentin** [comment]
If you need the perfdata in percent, you can use --change-perfdata option:
```
perl centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=disk-usage --snmp-community=public --snmp-version=2c --hostname=127.0.0.1 --change-perfdata='used,,percent()'
```
