### ISSUE TITLE
plugin=database::mssql::plugin

### ISSUE THREAD

**Issue by dchitre1** [centreon/centreon-plugins#1433]
Hello ! 

I'm setting up a new centreon platform, I 'm used to configure and manage centreon but I got a problem with the mssql plugin only : plugin=database::mssql::plugin
In command line everything is ok : 
./centreon_plugins.pl --plugin=database::mssql::plugin --mode=cache-hitratio --datasource='Sybase:server=MYSQLSERVER' --username="MYDOMAIN\ \MYUSER" --password="MYPASSWORD" --critical=90:

Answer 👍  OK: Buffer cache hit ratio is 100.00% | 'cache_hitratio'=100%;;90:;0;100
The same line in my centreon web command : 
UNKNOWN: Cannot connect: OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (34)
I know the problem is  the \\ of my username but I created a resource $MysqlUser$ witch Contains 2 \ \ MYDOMAIN\ \ MYUSER

If I trie to change the \ \ by something else, I got the good answer from my sql server : 
Login failed for user 

My centreon version was installed by the ISO, other centreon plugins are well working (disk, services, process, etc...) 
My version : Centreon 18.10.3 (commit f91d652f0)
freetds v1.1.1 in TDS 8.0
My centreon plugin are updated, Someone got an idea? Regards 

David

**Comment by garnier-quentin** [comment]
Could you use the login with @ domain format ?

**Comment by dchitre1** [comment]
Unfortunately, sql says it's unknown domain when I try with @, he wants the syntax DOMAIN\USERNAME

**Comment by garnier-quentin** [comment]
You need to add backslash in centreon command or macro configuration. But it's not an issue with centreon-plugins.

**Comment by dchitre1** [comment]
Yes it works in command line but not in php7.1 with centreon web 18
