### ISSUE TITLE
Warning value in % apps::vmware::connector::plugin

### ISSUE THREAD

**Issue by maffeltranger** [centreon/centreon-plugins#1437]
Hello,

I can't manage to get my thresholds as %, could you please help me ?

Here is my command :

> perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=cpu-host --connector-hostname=127.0.0.1 --container=esxi1 --warning-cpu-total --warning-status=70 --critical-cpu-total --critical-status=90

I get a critical alert directly because my value is set as MHz and not as %
How can I change it ? I tried with --warning-status=70% but nothing changed..

Thanks by advance !

Regards

**Comment by garnier-quentin** [comment]
I can give you an example. 'total-cpu' and 'cpu' is in '%' (--warning-status and --critical-status check your ESX status. not the cpu).
```
 --critical-status='%{status} !~ /^connected$/i' --warning-cpu-total=80 --critical-cpu-total=90 
```

**Comment by maffeltranger** [comment]
Oh I see ! I will try this out right now ! 

Thanks a lot !
