### ISSUE TITLE
os::linux::local::plugin process

### ISSUE THREAD

**Issue by markeur** [centreon/centreon-plugins#1438]
I tried to use the os::linux::local plugin when I use it directly from my poller bash I obtain the correct return. But after my import in centreon I obtain a false return 

My bash command
 /usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=os::linux::local::plugin --mode='process' --hostname='@IP' --ssh-command=plink --ssh-option='-l=myuser' --ssh-option='-pw=mypass'  --filter-command
='my_command' --remote

The correct return
OK: Number of current processes: 1 | 'nbproc'=1;;;0;

My centreon command
/usr/lib64/nagios/plugins/centreon_plugins.pl
	--plugin=os::linux::local::plugin
	--mode=process
	--hostname='@IP'
	--ssh-command='plink'
	--ssh-option='-l=myuser'
	--ssh-option='-pw=mypass'
	--filter-command='my_command'
	--remote

his return : 

  | 'nbproc'=0;;;0;

It's like if my command is execute by the poller and not by the device I want to connect by ssh.
Please can you help me.

Thanks

**Comment by garnier-quentin** [comment]
Have you tested the command with centreon-engine user ? Is it work ?

**Comment by markeur** [comment]
Hello,
I just try as you ask the command with centreon-engine user the results is : 

substr outside of string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 109.
substr outside of string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 110.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 316.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 317.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 318.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 316.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 317.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 318.
Use of uninitialized value in pattern match (m//) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 152.

OK: Number of current processes: 0 | 'nbproc'=0;;;0;

Thanks for your help.

**Comment by garnier-quentin** [comment]
Could you execute command plink directly (with command: 'ps -e -o etime,pid,ppid,state,comm,args -w 2>&1') and show me the result ?

**Comment by markeur** [comment]
results of the command : 
substr outside of string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 109.
substr outside of string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 110.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 316.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 317.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 318.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 316.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 317.
Use of uninitialized value $value in substitution (s///) at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 318.
Use of uninitialized value in concatenation (.) or string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 161.
Use of uninitialized value $min in multiplication (*) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
Argument "that" isn't numeric in addition (+) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
Use of uninitialized value in concatenation (.) or string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 161.
Use of uninitialized value $min in multiplication (*) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
Argument "ssh-rsa" isn't numeric in addition (+) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
Use of uninitialized value in concatenation (.) or string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 161.
Use of uninitialized value in concatenation (.) or string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 161.
Use of uninitialized value in concatenation (.) or string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 161.
Use of uninitialized value $min in multiplication (*) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
Argument "Connection" isn't numeric in addition (+) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
Use of uninitialized value in concatenation (.) or string at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 161.
Use of uninitialized value $min in multiplication (*) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
Argument "The" isn't numeric in addition (+) at /usr/lib64/nagios/plugins/os/linux/local/mode/process.pm line 127.
OK: Number of current processes: 4 | 'nbproc'=4;;;0;

**Comment by garnier-quentin** [comment]
I don't want the result of centreon-plugins. I want the result of the following command launched with centreon-engine user:
```
plink -l=myuser -pw=mypass IP 'ps -e -o etime,pid,ppid,state,comm,args -w 2>&1'
```

**Comment by markeur** [comment]
Sorry this the good one:

  ELAPSED    PID   PPID S COMMAND         COMMAND
51-21:05:51      1      0 S systemd         /usr/lib/systemd/systemd --switched-root --system --deserialize 22
51-21:05:51      2      0 S kthreadd        [kthreadd]
51-21:05:51      3      2 S ksoftirqd/0     [ksoftirqd/0]
51-21:05:51      5      2 S kworker/0:0H    [kworker/0:0H]
51-21:05:51      7      2 S migration/0     [migration/0]
51-21:05:51      8      2 S rcu_bh          [rcu_bh]
51-21:05:51      9      2 R rcu_sched       [rcu_sched]
51-21:05:51     10      2 S lru-add-drain   [lru-add-drain]
51-21:05:51     11      2 S watchdog/0      [watchdog/0]
51-21:05:51     13      2 S kdevtmpfs       [kdevtmpfs]
51-21:05:51     14      2 S netns           [netns]
51-21:05:51     15      2 S khungtaskd      [khungtaskd]
51-21:05:51     16      2 S writeback       [writeback]
51-21:05:51     17      2 S kintegrityd     [kintegrityd]
51-21:05:51     18      2 S bioset          [bioset]
51-21:05:51     19      2 S bioset          [bioset]
51-21:05:51     20      2 S bioset          [bioset]
51-21:05:51     21      2 S kblockd         [kblockd]
51-21:05:51     22      2 S md              [md]
51-21:05:51     23      2 S edac-poller     [edac-poller]
51-21:05:51     29      2 S kswapd0         [kswapd0]
51-21:05:51     30      2 S ksmd            [ksmd]
51-21:05:51     31      2 S khugepaged      [khugepaged]
51-21:05:51     32      2 S crypto          [crypto]
51-21:05:51     40      2 S kthrotld        [kthrotld]
51-21:05:51     42      2 S kmpath_rdacd    [kmpath_rdacd]
51-21:05:51     43      2 S kaluad          [kaluad]
51-21:05:51     44      2 S kpsmoused       [kpsmoused]
51-21:05:51     46      2 S ipv6_addrconf   [ipv6_addrconf]
51-21:05:51     59      2 S deferwq         [deferwq]
51-21:05:51     89      2 S kauditd         [kauditd]
51-21:05:51    258      2 S hv_vmbus_con    [hv_vmbus_con]
51-21:05:51    274      2 S ata_sff         [ata_sff]
51-21:05:50    280      2 S scsi_eh_0       [scsi_eh_0]
51-21:05:50    281      2 S scsi_tmf_0      [scsi_tmf_0]
51-21:05:50    283      2 S scsi_eh_1       [scsi_eh_1]
51-21:05:50    284      2 S scsi_eh_2       [scsi_eh_2]
51-21:05:50    285      2 S scsi_tmf_1      [scsi_tmf_1]
51-21:05:50    286      2 S scsi_tmf_2      [scsi_tmf_2]
51-21:05:50    288      2 S storvsc_error_w [storvsc_error_w]
51-21:05:50    289      2 S scsi_eh_3       [scsi_eh_3]
51-21:05:50    290      2 S scsi_tmf_3      [scsi_tmf_3]
51-21:05:50    292      2 S storvsc_error_w [storvsc_error_w]
51-21:05:50    301      2 S kworker/0:1H    [kworker/0:1H]
51-21:05:46    363      2 S kdmflush        [kdmflush]
51-21:05:46    364      2 S bioset          [bioset]
51-21:05:44    374      2 S kdmflush        [kdmflush]
51-21:05:44    375      2 S bioset          [bioset]
51-21:05:41    387      2 S bioset          [bioset]
51-21:05:41    388      2 S xfsalloc        [xfsalloc]
51-21:05:41    389      2 S xfs_mru_cache   [xfs_mru_cache]
51-21:05:41    390      2 S xfs-buf/dm-0    [xfs-buf/dm-0]
51-21:05:41    391      2 S xfs-data/dm-0   [xfs-data/dm-0]
51-21:05:41    392      2 S xfs-conv/dm-0   [xfs-conv/dm-0]
51-21:05:41    393      2 S xfs-cil/dm-0    [xfs-cil/dm-0]
51-21:05:41    394      2 S xfs-reclaim/dm- [xfs-reclaim/dm-]
51-21:05:41    395      2 S xfs-log/dm-0    [xfs-log/dm-0]
51-21:05:41    396      2 S xfs-eofblocks/d [xfs-eofblocks/d]
51-21:05:41    397      2 S xfsaild/dm-0    [xfsaild/dm-0]
51-21:05:04    464      1 S systemd-journal /usr/lib/systemd/systemd-journald
51-21:05:00    488      1 S lvmetad         /usr/sbin/lvmetad -f
51-21:04:58    498      1 S systemd-udevd   /usr/lib/systemd/systemd-udevd
51-21:04:50    511      2 S hv_balloon      [hv_balloon]
51-21:04:46    571      2 S xfs-buf/sda1    [xfs-buf/sda1]
51-21:04:46    572      2 S xfs-data/sda1   [xfs-data/sda1]
51-21:04:46    573      2 S xfs-conv/sda1   [xfs-conv/sda1]
51-21:04:46    574      2 S xfs-cil/sda1    [xfs-cil/sda1]
51-21:04:46    575      2 S xfs-reclaim/sda [xfs-reclaim/sda]
51-21:04:46    576      2 S xfs-log/sda1    [xfs-log/sda1]
51-21:04:46    577      2 S xfs-eofblocks/s [xfs-eofblocks/s]
51-21:04:46    578      2 S xfsaild/sda1    [xfsaild/sda1]
51-21:04:40    606      1 S auditd          /sbin/auditd
51-21:04:38    629      1 S polkitd         /usr/lib/polkit-1/polkitd --no-debug
51-21:04:38    631      1 S systemd-logind  /usr/lib/systemd/systemd-logind
51-21:04:38    635      1 S dbus-daemon     /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
51-21:04:34    641      1 S NetworkManager  /usr/sbin/NetworkManager --no-daemon
51-21:04:31    659      1 S crond           /usr/sbin/crond -n
51-21:04:30    661      1 S login           login -- root
51-21:04:30    663      1 S chronyd         /usr/sbin/chronyd
51-21:04:17    893      1 S sshd            /usr/sbin/sshd -D
51-21:04:17    895      1 S tuned           /usr/bin/python -Es /usr/sbin/tuned -l -P
51-21:04:17    899      1 S rsyslogd        /usr/sbin/rsyslogd -n
51-21:04:05    988      1 S master          /usr/libexec/postfix/master -w
51-21:04:05    990    988 S qmgr            qmgr -l -t unix -u
51-21:03:58    994      1 S nginx           nginx: master process /usr/sbin/nginx
51-21:03:58    995    994 S nginx           nginx: worker process
51-10:19:45   1473    661 S bash            -bash
51-10:19:29   1564   1473 S su              su - oxidized
51-10:19:27   1565   1564 S bash            -bash
43-21:51:38  12838      2 S kworker/u256:2  [kworker/u256:2]
19-14:49:10  54632      2 S kworker/u256:1  [kworker/u256:1]
 4-02:19:33  68575   1565 S ssh             ssh root@10.147.52.131
   01:25:24  70890    988 S pickup          pickup -l -t unix -u
      22:32  70914      2 S kworker/0:1     [kworker/0:1]
      12:30  70915      2 S kworker/0:2     [kworker/0:2]
      02:28  70916      2 S kworker/0:0     [kworker/0:0]
      00:09  70917    893 S sshd            sshd: root@notty
      00:01  70922  70917 S bash            bash -c ps -e -o etime,pid,ppid,state,comm,args -w 2>&1
      00:00  71003  70922 R ps              ps -e -o etime,pid,ppid,state,comm,args -w

**Comment by garnier-quentin** [comment]
That's the result on the linux poller no ? I need the result of that command on your AIX.

**Comment by garnier-quentin** [comment]
I have changed the command. Could you test with the last version please ?

**Comment by markeur** [comment]
Thank you, it is working

**Comment by garnier-quentin** [comment]
Thanks for the feedback!!
