### ISSUE TITLE
Aruba Controller - UNKNOWN: SNMP Table Request: Cant get a single value.

### ISSUE THREAD

**Issue by williamsanmartin** [centreon/centreon-plugins#1439]
Hi,

I am configuring the Aruba monitoring with the `network::aruba::standard::snmp::plugin`.
I am identify this errors:

./centreon_plugins.pl --plugin network::aruba::standard::snmp::plugin --mode ap-users --hostname 10.10.10.10 --snmp-version 3 --snmp-username admin --authprotocol SHA --authpassphrase password --privpassphrase password --privprotocol AES
UNKNOWN: SNMP Table Request: Cant get a single value.

./centreon_plugins.pl --plugin network::aruba::standard::snmp::plugin --mode cpu --hostname 10.10.10.10 --snmp-version 3 --snmp-username admin --authprotocol SHA --authpassphrase password --privpassphrase password --privprotocol AES
UNKNOWN: SNMP Table Request: Cant get a single value.

My system:
Nagios 4.4.3
Aruba Controller 6.5.4.9
SNMP V3

 Tks

**Comment by garnier-quentin** [comment]
Could you provide us a snmpwalk of your equipment ? 
snmpwalk -ObentU -v 2c -c public IP_ADDRESS .1 > aruba.snmpwalk

**Comment by williamsanmartin** [comment]
I prefer to send by e-mail, ok?

**Comment by garnier-quentin** [comment]
No problem: qgarnier@centreon.com

**Comment by garnier-quentin** [comment]
That's an aruba instant. Need to develop a plugin for it. Same issue:
https://github.com/centreon/centreon-plugins/issues/685

Your aruba instant doesn't have virtual controller enabled.

**Comment by igorcortes** [comment]
Hi,

I am new monitoring Aruba hardware and I have the same problem.

./centreon_plugins.pl --plugin network::aruba::standard::snmp::plugin --mode cpu --hostname 10.136.64.225 --snmp-version="2c" --snmp-community="public" 
UNKNOWN: SNMP Table Request: Cant get a single value.

But if I monitor the uptime it works.

./centreon_plugins.pl --plugin network::aruba::standard::snmp::plugin --mode uptime --hostname 10.136.64.225 --snmp-version="2c" --snmp-community="public" 
OK: System uptime is: 124d 1h 7m 58s | 'uptime'=10717678s;;;0;

I am using ArubaOS version 6.5.4.3

Some one can help me please?

Thanks.

**Comment by igorcortes** [comment]
Hi,

I am new monitoring Aruba hardware and I have the same problem.

./centreon_plugins.pl --plugin network:🇦🇼:standard::snmp::plugin --mode cpu --hostname 10.136.64.225 --snmp-version="2c" --snmp-community="public"
UNKNOWN: SNMP Table Request: Cant get a single value.

I am using ArubaOS version 6.5.4.3

Some one can help me please?

Thanks.
