### ISSUE TITLE
[network::mikrotik] enh power supply verification

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1440]
Hi,

In `network::mikrotik::snmp`, environment mode, power component.
We should verify powser supply status, in addition to watts consumption.

Current OID verified :
```
 mtxrHlPower / .1.3.6.1.4.1.14988.1.1.3.12 / Watts
```

New OIDs to verify :
```
 mtxrHlPowerSupplyState       / .1.3.6.1.4.1.14988.1.1.3.15 / BoolValue (INTEGER) {false(0), true(1) }
 mtxrHlBackupPowerSupplyState / .1.3.6.1.4.1.14988.1.1.3.16 / BoolValue (INTEGER) {false(0), true(1) }
```

So that we get an alert when a power supply fails.

Thank you very much :+1:

**Comment by CPbN** [comment]
Of course, as with mtxrHlPower, these 2 new OIDs may not be available on some Mikrotik devices, which is expected. Only some Mikrotik devices have them available.

**Comment by garnier-quentin** [comment]
Could you provide us a full snmpwalk please ?

**Comment by CPbN** [comment]
Yep I should get hand on such powered devices today :+1:

**Comment by garnier-quentin** [comment]
Could you test it with the last version please ?

**Comment by CPbN** [comment]
Perfect @garnier-quentin, works as expected (well I did not break a power to trigger a critical status, but I'm rather confident :)
Thank you again !!
