### ISSUE TITLE
Mode interfaces: merge error counters all together

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1442]
Hi,

In mode interfaces, would be nice to have an option to merge (add all together) the 4 existing error counters into a single one :
```
  Packets In Discard
+ Packets In Error
+ Packets Out Discard
+ Packets Out Error
---------------------
= Wrong Packets

```
This would limit number of series to graph, still being alerted in case of errors.

Very useful monitoring lots of routers with several interfaces.

Thank you 👍

**Comment by CPbN** [comment]
Or at least :
`Packets In Discard + Packets Out Discard = Packets Discard`
and :
`Packets In Error + Packets Out Error = Packets Error`

**Comment by garnier-quentin** [comment]
I think, we can add an extra option. But we cannot get a threshold of perfdatas. We could add a total wrong packets however.
```
--extend-perfdata-group=searchlabel,newlabel,method[,newuom]
```

If searchlabel is empty, it's done one time. 

Examples:
```
--extend-perfdata-group=packets_discard_in_(.*),packet_discard_$1,sum(packet_discard_(in|out)_$1)
--extend-perfdata-group=,packets_wrong,sum(packet_(discard|error)_(in|out))
```

Available methods: min, max, average, sum

**Comment by CPbN** [comment]
Nice idea yes, it would also answer #1432.

> But we cannot get a threshold of perfdatas.

I not sure it's a drawback, as we can still set thresholds on original series ?
Do you see any benefit setting thresholds on such computed perfdata series ?

**Comment by garnier-quentin** [comment]
Yes you can add on original series.

**Comment by garnier-quentin** [comment]
Yo can add following options now:
```
--units-errors=absolute
--extend-perfdata-group=',packets_wrong,sum(packet_(discard|error)_(in|out))'
```

**Comment by CPbN** [comment]
Excellent, really nice generic feature :)
Thank you very much @garnier-quentin 👍
