### ISSUE TITLE
[apps::protocols:http] Choose expected-content severity

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1443]
Hi,

In `apps::protocols:http` plugin, `expected-content` mode, would be nice to be able to choose severity for `--expected-string` option.
Currently, `CRITICAL` severity is enforced, would be nice to be able to set `WARNING` severity.

Thank you very much :+1:

**Comment by CPbN** [comment]
See PR #1335.

**Comment by garnier-quentin** [comment]
You have new option now: --extracted-pattern, --critical-content, --warning-content, --unknown-content.
For example:
```
--warning-content='%{content} =~ /test/mi'
```

**Comment by CPbN** [comment]
Thank you very much @garnier-quentin :+1:

**Comment by pierrebourget** [comment]
Hi, sorry but I did not find out how to replace my hold check :

`./centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=jenkins.example.com --proto='http' --port='8080' --urlpath='/login' --expected-string='Welcome to Jenkins!'`

`=> CRITICAL: content test [filter: '%{content} =~ /Welcome to Jenkins!/mi'] | 'size'=1876B;;;0; 'time'=0.082s;;;0;`

I just want an OK response if the expected string is returned...

I have just upgraded to 18.10.4 yesterday.

Thanks for your help !

**Comment by CPbN** [comment]
`--critical-content='%{content} !~ /Welcome to Jenkins!/'` is the new way and should work for you 👍

**Comment by garnier-quentin** [comment]
Sorry. I have fixed the mode to be compatible.

**Comment by pierrebourget** [comment]
Ok thanks a lot !
