### ISSUE TITLE
Plugin for VNXe 3200

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon-plugins#1447]
HI,
most VNXe's can be monitored using the naviCLI / navisecCLI Software.
Not so the VNXe3200: 
To connect, you have to use  UnisphereCLI.

Example to get Hardware infos:
./uemcli.sh -d 10.0.0.1 -u user -p password  /env/ --help
+- /env/
       +- [iomodule]
       +- [fan]
       +- [disk]
       +- [ps]
       +- [mm]
       +- [lcc]
       +- [dae]
       +- [ssd]
       +- [bat]
       +- [ccard]
       +- [dpe]
       +- [sp]

Example:
./uemcli.sh -d 10.0.0.1 -u user -p password  /env/disk show -filter "ID, Enclosure, Slot, Health state"
Storage system address: 10.0.0.1
Storage system port: 443
HTTPS connection

1:    ID           = dpe_disk_1
      Enclosure    = dpe
      Slot         = 1
      Health state = OK (5)

2:    ID           = dpe_disk_2
      Enclosure    = dpe
      Slot         = 2
      Health state = OK (5)

other usefull commands:
/stor/prov/vmware/vmfs show -filter "Name, Size, Current allocation"
/stor/config/pool show
/sys/general show -detail

->output states:
- Unknown (0) — Status is unknown.  
- OK (5) — Working correctly.  
- OK BUT (7) — Working correctly, but there could be a problem.  
- Degraded/Warning (10) — Working  and performing all functions, but the  performance may not be optimum.  
- Minor failure (15) — Working and  performing all functions but overall performance is degraded. This condition has a minor impact on the system and  should be remedied at some point, but  does not have to be fixed immediately.  
- Major failure (20) — Failing and some or all functions may be degraded or not working. This condition has a significant impact on the system and should be remedied immediately.  
-Critical failure (25) — Failed and recovery may not be possible. This condition has resulted in data loss and should be remedied immediately.  
- Non-recoverable error (30) —  Completely failed and cannot be recovered.

Can you add unispherecli to the plugins (may be storage::emc::clariion::plugin)?

If so, I could deliver further details in the short term!

Thanks a lot,
Peter

**Comment by garnier-quentin** [comment]
Thanks. Commands seems very different. Need a emc unisphere plugin. You could provide me commands in a file with: the command and the result. Also a return code when you have an error. 
Could you get all env data with only one command ?

**Comment by Cancom-Monitoring** [comment]
ok, I'll do so.
unfortunatelly /env/ show results in an error....

**Comment by Cancom-Monitoring** [comment]
[UnisphereCLI_commands.txt](https://github.com/centreon/centreon-plugins/files/3009033/UnisphereCLI_commands.txt)
voila le fichier...

**Comment by garnier-quentin** [comment]
How do you execute the command ? Like that for example:
```
$ /opt/emc/uemcli/bin/uemcli.sh -d 10.0.0.1 -u user -p passwd /env/disk show -filter "ID, Enclosure, Slot, Health state"


1:    ID           = dpe_disk_1
      Enclosure    = dpe
      Slot         = 1
      Health state = OK (5)

2:    ID           = dpe_disk_2
      Enclosure    = dpe
      Slot         = 2
      Health state = OK (5)

3:    ID           = dpe_disk_3
      Enclosure    = dpe
      Slot         = 3
```

**Comment by Cancom-Monitoring** [comment]
thats exactly the way! (with or w/o the switch for filtering...)

**Comment by Sims24** [comment]
Not yet ... A lot of things to do, we will try to work on this asap ! We'll ping you ; )

**Comment by Cancom-Monitoring** [comment]
Ping.... :-)

**Comment by garnier-quentin** [comment]
Sorry but could you provide commands (for all) with "-output csv" option ? Could you also provide commands results (and the exit command code) with wrong password for example ?

It seems uemcli cannot execute for example two show in the same command. Right ?

**Comment by garnier-quentin** [comment]
Ping :)
