### ISSUE TITLE
database::mssql::plugin - connection-time: timeout 

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1451]
Centreon Plugins: 20190221(latest)
freetds: 1.1.2 (latest)
DBD::Sybase: 1.16 (latest)

we are not able to make service checks on MS SQL. The plugin is going in timeout after 10 seconds.
```
./centreon_plugins.pl --plugin=database::mssql::plugin --mode=connection-time --hostname=x.x.x.x --port=1433 --username='xxx' --password=xxx
UNKNOWN: Timeout |
```

We tried out also check_mssql_health:
```
./check_mssql_health --hostname=x.x.x.x --port=1433 --username='xxx' --password=xxx --mode=connection-time
CRITICAL - 10.03 seconds to connect as VENEZIA\IVERTIX | 'connection_time'=10.03;1;5;;
```
we have the same situation, only the timeout setting is higher and we have a response after 10 seconds.

If we use check_mssql_health with server option instead hostname the execution is very fast:
```
./check_mssql_health --server=10.4.60.176 --port=1433 --username='VENEZIA\IVERTIX' --password=5j4bzNG8Fr --mode=connection-time
OK - 0.01 seconds to connect as VENEZIA\IVERTIX | 'connection_time'=0.01;1;5;;
```

So we changed on centreon/plugins/database/mssql/plugin.pm line 72
`$self->{sqldefault}->{dbi}[$i] = { data_source => 'Sybase:host=' . $options_result->{hostname}[$i] };`
to
`$self->{sqldefault}->{dbi}[$i] = { data_source => 'Sybase:server=' . $options_result->{hostname}[$i] };`
and now also centreon plugins have a fast execution.

Any idea? Could be a bug?

**Comment by garnier-quentin** [comment]
For me, it's ok for the connection-time (it's timeout in my case). 
For the second, i should take a look deeper.

**Comment by joschi99** [comment]
Please consider that the real connection time is not 10.03 seconds but 0.01 seconds.

**Comment by rmorandell-pgum** [comment]
I have now dealt more with DBI: Sybase and see that in most examples "server" is used and not "host" in the DBI-> connect.
With "server" works in all our MSSQLServer environments. With host it works with several only after a 10 seconds timeout although also the port is indicated.
Is there a reason why the plugin used "host" instead of "server"?

regards

Roman

**Comment by garnier-quentin** [comment]
Could you test connection with a timeout of 20 seconds ?

With the server option, it looks in freetds.conf (could you show use the configuration ?) I could add an option --server

**Comment by garnier-quentin** [comment]
It seems you have a DNS issue for the connection time.

**Comment by garnier-quentin** [comment]
You can use --server option now.

**Comment by rmorandell-pgum** [comment]
We don't set the servers in the freetds.conf. When the server isn't found in the config it tries directly. We use always the IP so it woks fine with server.

Thank You for the fast new option  ! 

Regards

Roman
