### ISSUE TITLE
[apps::protocols::http::plugin] Negociate authentification expected

### ISSUE THREAD

**Issue by q-lng** [centreon/centreon-plugins#1452]
Hi,

I want to verify HTTP response of a server using the HTTP plugin. This is my command : 

`
/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=srv45 --port=80 --proto=http --urlpath='/Acroweb2017' --credentials  --username=user --password=pass`

The response : 

`CRITICAL: 401 Unauthorized (Negotiate authentication expected) |`

I tried with --basic argument, without success.
I cannot use --ntlmv2 arg : 

```
UNKNOWN: Cannot load module 'Authen::NTLM'.
Can't locate Authen/NTLM.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::26217352=HASH(0x1900b88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /lib/centreon/plugins/centreon_protocol_http.pl line 2354.
```

I think i understand the problem but can't find how to fix it.

Regards.

**Comment by Sims24** [comment]
Hi, 

Please install Authen/NTLM.pm perl module. 

`yum whatprovides 'perl(Authen::NTLM)' 
`
Command above will return the righet package

**Comment by q-lng** [comment]
thanks, now the argument --ntlmv2 works, but didn't resolve my issue unfortunately, still have a 401 error.

**Comment by garnier-quentin** [comment]
Could you use the curl backend (need to install perl net curl package also) ? --http-backend=curl

**Comment by q-lng** [comment]
I have installed perl-WWW-curl package, is that correct ? Because --http-backend=curl doesn't work.

`Unknown option: http-backend at /lib/centreon/plugins/centreon_protocol_http.pl line 1745.`

**Comment by garnier-quentin** [comment]
It's perl-Net-Curl

**Comment by cgagnaire** [comment]
Hi @q-lng,
Even though it might be better handled by curl as @garnier-quentin said, can you try to install https://metacpan.org/release/LWP-Authen-Negotiate as it is what LWP needs to provide credentials.

**Comment by q-lng** [comment]
@garnier-quentin done, but same result : 

`Unknown option: http-backend at /lib/centreon/plugins/centreon_protocol_http.pl line 1745.`

do i need to put that somewhere else?

@cgagnaire I will try that is the 1st solution doesn't work, thanks !

(Maybe ce serait plus simple en français ?)

**Comment by garnier-quentin** [comment]
You need to update plugin protocol http from unstable repository. 
http://yum.centreon.com/standard/18.10/el7/unstable/noarch/plugins/centreon-plugins-20190327-151501/centreon-plugin-Applications-Protocol-Http-20190327-151501.el7.centos.noarch.rpm

**Comment by q-lng** [comment]
Après l'update du plugin : 

`/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=srv45 --port=80 --proto=http --urlpath='/Acroweb2017' --credentials  --username=qlelong --password=cmmvgpn --http-backend=curl`

`CRITICAL: 401 Unauthorized |`

Plus de '(Negotiate authentication expected)' dans la réponse.

**Comment by garnier-quentin** [comment]
There is a space missing between --username and --password option ?

**Comment by q-lng** [comment]
ahh no, that's because i've modified my post

**Comment by garnier-quentin** [comment]
Can you test (and make it work) with curl command directly ?

**Comment by q-lng** [comment]
so with : 

`curl http://srv45/acroweb2017 --user qlelong:cmmvgpn --negotiate`

got this GET response : 

```
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Non autorisé : accès refusé en raison d'informations d'identification non valides.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Erreur de serveur</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Non autorisé : accès refusé en raison d'informations d'identification non valides.</h2>
  <h3>Vous n'avez pas l'autorisation d'afficher ce répertoire ou cette page à l'aide des informations d'identification que vous avez fournies.</h3>
 </fieldset></div>
</div>
</body>
</html>`

```

That's the page shown when the auth doesn't work basically.

**Comment by q-lng** [comment]
trying to connect directly to the website with Lynx : 

`lynx -auth=qlelong:cmmvgpn http://srv45/acroweb2017
`

I got : 

`Alert!: Invalid header 'WWW-Authenticate: Negotiate'
`

`Alert!: Invalid header 'WWW-Authenticate: NTLM'`

Does it means that i need to add --header option to my original command ? with an argument like "WWW-Authenticate: Negotiate"

**Comment by garnier-quentin** [comment]
Could you test with curl command ?

**Comment by q-lng** [comment]
isn't what i've done with :
`curl http://srv45/acroweb2017 --user qlelong:cmmvgpn --negotiate`

?

**Comment by garnier-quentin** [comment]
And it's working with that command ?

**Comment by q-lng** [comment]
No, got this : 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Non autorisé : accès refusé en raison d'informations d'identification non valides.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Erreur de serveur</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Non autorisé : accès refusé en raison d'informations d'identification non valides.</h2>
  <h3>Vous n'avez pas l'autorisation d'afficher ce répertoire ou cette page à l'aide des informations d'identification que vous avez fournies.</h3>
 </fieldset></div>
</div>
</body>
</html>

```

It's just the page when you cancel authentification.

**Comment by garnier-quentin** [comment]
If it's not working with curl, the plugin cannot work (the plugin uses that library).

**Comment by q-lng** [comment]
Ok, I will look for more infos from Curl then.
Thank you for your time :)

**Comment by q-lng** [comment]
More feedback for my case :
It seems that the server uses is an SSO auth which is not supported by the plugin. This is why it doesn't work i guess.

**Comment by garnier-quentin** [comment]
Like a kerberos auth ?

**Comment by q-lng** [comment]
Yes i guess

**Comment by fabien493** [comment]
try : kinit qlelong
after the plugin it's work
