### ISSUE TITLE
[Hardware template] Allow to set thresholds by name

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1456]
Hi,

In hardware template :
```
    --critical
            Set critical threshold for 'temperature', 'fan', 'voltage'
            (syntax: type,regexp,threshold) Example:
            --critical='temperature,.*,50'
```

Let's take these Mikrotik examples :
`OK: All 1 components are ok | 'temperature_processor'=39C;;;;`
`OK: All 2 components are ok | 'temperature'=49C;;;; 'temperature_processor'=34C;;;;`

There's not way here to monitor these 2 routers CPU temperature using the same command.
As the first one would require : `--critical='temperature,1,90'`
And second one would require : `--critical='temperature,2,90'`

The following trick would then be nice :
`--critical='temperature,processor,90'` `--critical='temperature,^temperature$,60'`

Being able to filter by name :)

Thank you very much 👍

**Comment by garnier-quentin** [comment]
Yo can use following option no ? --critical='temperature,.*,90'

**Comment by CPbN** [comment]
I'm then not able to alert for a board temperature raising over 60°C for example.

**Comment by garnier-quentin** [comment]
I don't understand the issue.

**Comment by garnier-quentin** [comment]
Following options also work: --critical='temperature,1,90' --critical='temperature,2,60'

**Comment by CPbN** [comment]
Yes, but it will then not work for the first router example, which does not return a board temperature, but only a CPU temperature.
`--critical='temperature,1,90' --critical='temperature,2,60'` would then not work as a monitoring template / as a generic command.

**Comment by garnier-quentin** [comment]
You can use the same command. No problem to set option --critical twice.

**Comment by CPbN** [comment]
Look again at my examples :
Router 1 : `OK: All 1 components are ok | 'temperature_processor'=39C;;;;`
Router 2 : `OK: All 2 components are ok | 'temperature'=49C;;;; 'temperature_processor'=34C;;;;`

Router 1 temperature 1 is CPU, it does not have / does not return board temperature.
Router 2 temperature 1 is board.

So I can't use same command for both, as the first one would have a board threshold to monitor CPU...

**Comment by garnier-quentin** [comment]
Instance is the same in the code:
```
        ($exit, $warn, $crit, $checked) = $self->get_severity_numeric(section => 'temperature', instance => '1', value => $result->{mtxrHlTemperature} / 10);
....
        ($exit, $warn, $crit, $checked) = $self->get_severity_numeric(section => 'temperature', instance => '2', value => $result->{mtxrHlProcessorTemperature} / 10);
```

**Comment by CPbN** [comment]
Oh, I missed that point, sorry.
Let me then test, report, and close this :) Thx !

**Comment by CPbN** [comment]
OK, works as you mentioned, thank you @garnier-quentin 👍
