### ISSUE TITLE
[database::oracle::plugin]

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#1457]
Hello,

Any mode does never timeout when database is not available ...

Using command line we never get back prompt, using Centreon there's only UNKNOWN status.

Thanks

**Comment by ritouret** [comment]
Oups, sorry for wrong user, i've just disconnect you and reconnect with my account.

**Comment by garnier-quentin** [comment]
There is not a global timeout indeed.

**Comment by garnier-quentin** [comment]
You should have a timeout (10 seconds by default). but only at connect (not in query). What do you want ?

**Comment by ritouret** [comment]
I have the timeout in my command :
/usr/lib/centreon/plugins/centreon_oracle.pl --plugin=database::oracle::plugin --mode=connection-time --warning=5000 --critical=7000 --hostname=10.10.10.10 --port=1521 --sid=TOTO --username=toto --password=toto --timeout=10

Using command line i never get back prompt, using Centreon there's only UNKNOWN status.
It should be CRITICAL status in Centreon and i should get back the prompt when using this in command line ...

**Comment by garnier-quentin** [comment]
You should have a timeout from command line.

**Comment by ritouret** [comment]
... and CRITICAL status in Centreon but it's not happening.

**Comment by garnier-quentin** [comment]
It was a known issue with alarm and dbd oracle:
https://metacpan.org/pod/DBI
