### ISSUE TITLE
[apps::vmware::connector::plugin] mode=alarm-host - Host alway OK even a critical alarm is raised

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1459]
Centreon Plugins 20190221
```
./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=alarm-host --esx-hostname='esx' --filter --scope-cluster='' --scope-datacenter='.*'--warning-total-alarm-warning=1 --warning-total-alarm-critical=1 --critical-total-alarm-warning=1 --critical-total-alarm-critical=1 --warning-status= --critical-status=
OK: 0 warning alarm(s) found(s), 1 critical alarm(s) found(s) - Host 'esx' 0 problem(s) detected | 'total_alarm_warning'=0;0:1;0:1;0; 'total_alarm_critical'=1;0:1;0:1;0; 'alarm_warning'=0;;;0; 'alarm_critical'=0;;;0;
checking host 'esx'
```

**Comment by garnier-quentin** [comment]
Could you give me the result with --debug please ?

**Comment by joschi99** [comment]
`./centreon_plugins --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=alarm-host --esx-hostname='esx' --filter --scope-cluster='' --scope-datacenter='.*' --warning-total-alarm-warning=1 --warning-total-alarm-critical=1 --critical-total-alarm-warning=1 --critical-total-alarm-critical=1 --warning-status= --critical-status= --debug
OK: 0 warning alarm(s) found(s), 1 critical alarm(s) found(s) - Host 'esx' 0 problem(s) detected | 'total_alarm_warning'=0;0:1;0:1;0; 'total_alarm_critical'=1;0:1;0:1;0; 'alarm_warning'=0;;;0; 'alarm_critical'=0;;;0;
checking host 'esx'
ok: alarm [red] [HostSystem] [esx] [2019-03-19T12:13:11.820023Z] Host memory usage/Default alarm to monitor host memory usage
ok: ,
`

**Comment by garnier-quentin** [comment]
There is no error: 'total_alarm_critical'=1;0:1;0:1;0;
You have one critical alarm in vmware. But your threshold critical is on if greater than 1

**Comment by joschi99** [comment]
Ooops, sorry. My fault.
