### ISSUE TITLE
network::juniper::ex::plugin stack check

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#146]
Hi,

Could you please add stack check to network::juniper::ex::plugin?
Thanks!

Kadri

**Comment by garnier-quentin** [comment]
Hi,

stack mode from ?

**Comment by kadrika** [comment]
I have several Juniper EX series switches, that are stacked together. Most are 2 or 3 member stacks.
And it would be good to see in the output stack member serial numbers.

**Comment by kadrika** [comment]
Any update on this?

**Comment by garnier-quentin** [comment]
COuld you give me OID result about it ?

**Comment by kadrika** [comment]
I will send snmpwalk to your email.
But the MIB used is https://www.juniper.net/documentation/en_US/junos12.3/topics/reference/general/jnx-ex-virtual-chassis-member-nm-mib.html

**Comment by lboue** [comment]
Hi,

I would do the same with a mixed mode VCF. We have 2 QFX5100 as spines and 4 EX4300 as leaves. This is an exemple for jnxVirtualChassisMemberMIB table

<pre>
snmpwalk  -c <private> -v 2c a.b.c.d 1.3.6.1.4.1.2636.3.40.1.4.1
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSerialnumber.0 = STRING: VFxxxxxxxxxx
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSerialnumber.1 = STRING: VFxxxxxxxxxx
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSerialnumber.2 = STRING: PExxxxxxxxxx
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSerialnumber.3 = STRING: PExxxxxxxxxx
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSerialnumber.4 = STRING: PExxxxxxxxxx
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSerialnumber.5 = STRING: PExxxxxxxxxx
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberRole.0 = INTEGER: backup(2)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberRole.1 = INTEGER: master(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberRole.2 = INTEGER: linecard(3)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberRole.3 = INTEGER: linecard(3)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberRole.4 = INTEGER: linecard(3)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberRole.5 = INTEGER: linecard(3)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberMacAddBase.0 = STRING: 30:7c:5e:xx:xx:0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberMacAddBase.1 = STRING: 54:1e:56:xx:xx:c0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberMacAddBase.2 = STRING: c:86:10:xx:xx:0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberMacAddBase.3 = STRING: c:86:10:xx:xx:80
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberMacAddBase.4 = STRING: c:86:10:xx:xx:e0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberMacAddBase.5 = STRING: c:86:10:xx:xx:0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSWVersion.0 = STRING: 13.2X51-D35.3
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSWVersion.1 = STRING: 13.2X51-D35.3
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSWVersion.2 = STRING: 13.2X51-D35.3
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSWVersion.3 = STRING: 13.2X51-D35.3
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSWVersion.4 = STRING: 13.2X51-D35.3
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberSWVersion.5 = STRING: 13.2X51-D35.3
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberPriority.0 = INTEGER: 129
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberPriority.1 = INTEGER: 129
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberPriority.2 = INTEGER: 0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberPriority.3 = INTEGER: 0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberPriority.4 = INTEGER: 0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberPriority.5 = INTEGER: 0
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberUptime.0 = INTEGER: 1984328
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberUptime.1 = INTEGER: 1987488
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberUptime.2 = INTEGER: 1997001
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberUptime.3 = INTEGER: 1996993
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberUptime.4 = INTEGER: 1996998
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberUptime.5 = INTEGER: 1996981
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberModel.0 = STRING: qfx5100-48s-6q
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberModel.1 = STRING: qfx5100-48s-6q
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberModel.2 = STRING: ex4300-48t
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberModel.3 = STRING: ex4300-48t
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberModel.4 = STRING: ex4300-48t
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberModel.5 = STRING: ex4300-48t
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberLocation.0 = STRING: 
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberLocation.1 = STRING: 
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberLocation.2 = STRING: 
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberLocation.3 = STRING: 
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberLocation.4 = STRING: 
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisMemberLocation.5 = STRING: 
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.0."vcp-255/0/48.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.0."vcp-255/0/49.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.0."vcp-255/0/50.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.0."vcp-255/0/51.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.1."vcp-255/0/48.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.1."vcp-255/0/49.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.1."vcp-255/0/50.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.1."vcp-255/0/51.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.2."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.2."vcp-255/1/1.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.3."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.3."vcp-255/1/1.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.4."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.4."vcp-255/1/1.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.5."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortAdminStatus.5."vcp-255/1/1.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.0."vcp-255/0/48.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.0."vcp-255/0/49.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.0."vcp-255/0/50.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.0."vcp-255/0/51.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.1."vcp-255/0/48.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.1."vcp-255/0/49.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.1."vcp-255/0/50.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.1."vcp-255/0/51.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.2."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.2."vcp-255/1/1.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.3."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.3."vcp-255/1/1.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.4."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.4."vcp-255/1/1.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.5."vcp-255/1/0.32768" = INTEGER: up(1)
JUNIPER-VIRTUALCHASSIS-MIB::jnxVirtualChassisPortOperStatus.5."vcp-255/1/1.32768" = INTEGER: up(1)
</pre>

Regards

**Comment by garnier-quentin** [comment]
Thanks. I'll look.

**Comment by kadrika** [comment]
Any update on this?

**Comment by garnier-quentin** [comment]
Not worked on it (yet).

**Comment by garnier-quentin** [comment]
What do you want to check on it ? I have only some roles. But there is no errors.

**Comment by lboue** [comment]
Hello Quentin,

I would like to check few status:
-Each member is running in his expected role (jnxVirtualChassisMemberRole) to detect a switchover
-VirtualChassisPort status (jnxVirtualChassisPortOperStatus) to kwow if all VC ports are UP 

See Juniper MIB doc: https://www.juniper.net/documentation/en_US/junos12.3/topics/reference/general/jnx-ex-virtual-chassis-member-nm-mib.html

Regards
