### ISSUE TITLE
network::bluecoat::snmp::plugin --mode cpu

### ISSUE THREAD

**Issue by jdidierpichat** [centreon/centreon-plugins#1463]
Hi,

I think there is a mistake in oid use for --cpu-mode. 

Package RPM use : 
centreon-plugin-Network-Generic-Bluecoat-Snmp-20190221-145606.el7.centos.noarch Mon 25 Mar 2019 05:03:36 PM CET

[root@poller ~]# /usr/lib/centreon/plugins//centreon_bluecoat.pl --version
Global Version: 20190221 (e1ce2d73)

oid found in centreon_bluecoat.pl plugin : 

>       sgProxyCpuCoreBusyTime  => { oid => '.1.3.6.1.4.1.3417.2.11.2.4.1.3' },
>       sgProxyCpuCoreIdleTime  => { oid => '.1.3.6.1.4.1.3417.2.11.2.4.1.4' },

These OIDs isn't a percentage but a millesecond. 

http://www.circitor.fr/Mibs/Html/B/BLUECOAT-SG-PROXY-MIB.php#sgProxyCpuCoreBusyTime

Think, these OIDs are OK. 

> sgProxyCpuCoreBusyPerCent => { oid => '.1.3.6.1.4.1.3417.2.11.2.4.1.8' },
> sgProxyCpuCoreIdlePerCent => { oid => '.1.3.6.1.4.1.3417.2.11.2.4.1.9' },

**Comment by garnier-quentin** [comment]
I know that's time. But we don't use it directly. We change it:
```
$self->{result_values}->{display} = $options{new_datas}->{$self->{instance} . '_display'};
    my $delta_busy = $options{new_datas}->{$self->{instance} . '_busy'} - $options{old_datas}->{$self->{instance} . '_busy'};
    my $delta_idle = $options{new_datas}->{$self->{instance} . '_idle'} - $options{old_datas}->{$self->{instance} . '_idle'};
    my $total = $delta_busy + $delta_idle;
    $self->{result_values}->{used_prct} = 0;
    if ($total > 0) {
        $self->{result_values}->{used_prct} = ($delta_busy) * 100 / $total;
    }
    return 0;
```
