### ISSUE TITLE
Add total IOPS in plugin : storage::emc::xtremio::restapi::plugin

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-plugins#1464]
Hi guys,

I'm using the last centreon-plugins package (20190221), and monitor EMC XtremIO. With mode "ssds-iops", plugin read each SSD and display for each "Global", "Read" and "Write".
Is it possible to add a flag that SUM all components ?

- Global-IOPS
- Global-Read-IOPS
- Global-Write-IOPS

And add warning (total) and critical (total)? 

Thanks in advance :)

**Comment by CPbN** [comment]
Is `Global-IOPS` different than `Global-Read-IOPS + Global-Write-IOPS` ?
If so, what does it represent ?
Thx for the info !

**Comment by Hellnino18** [comment]
Nope, Global-IPOS = Global-Read-IOPS + Global-Write-IOPS

**Comment by garnier-quentin** [comment]
Could you test the last version ?

**Comment by Hellnino18** [comment]
Pfiouuuuu sorry for the time to make an answer @garnier-quentin !! It works like I wanted to !

I only made upgrade of my centreon-plugins today with the latest version !

**Comment by garnier-quentin** [comment]
Thanks for the feedback! :)
