### ISSUE TITLE
Problem with plugin storage::emc::DataDomain::plugin and mode replication (centreon-plugins 20190221)

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-plugins#1465]
Hi,

Since I have upgraded from centreon-plugins 20180528 to 20190221, there is a problem with mode replication from plugin storage::emc::DataDomain::plugin. The error is : 

UNKNOWN: Undefined subroutine &storage::emc::DataDomain::lib::functions::get_version called at /usr/lib/nagios/plugins/centreon-plugins-20190221/storage/emc/DataDomain/mode/replication.pm line 108.

If I use the old one, no problem : 

OK: Replication status is 'normal', last time peer sync : 111 seconds ago | 'offset'=111;;;;

Thanks for your help.

**Comment by garnier-quentin** [comment]
I don't have that error with last git version. Could you provide a full snmpalk of your equipment ?

**Comment by garnier-quentin** [comment]
Already fixed the 27 february. You need to update with last version.
