### ISSUE TITLE
[storage::hp::storeonce::restapi::plugin] - cluster-usage - uninitialized value in multiplication

### ISSUE THREAD

**Issue by ginjan** [centreon/centreon-plugins#1467]
Hello,

I think there is a small bug in storage::hp::storeonce::restapi::plugin with cluster-usage mode.
I use a StoreOnce VSA Software Version: 3.18.7-1841.1.

I execute this command :
./centreon_plugins.pl --plugin=storage::hp::storeonce::restapi::plugin --mode=cluster-usage --username=XXXX --password=YYYYYYYY --hostname=AAA.BBB.CCC.DDD

Return :
Use of uninitialized value in multiplication (*) at /pathTo/centreon_plugins/storage/hp/storeonce/restapi/mode/clusterusage.pm line 198.

Thank you for your help.
Best regards

**Comment by garnier-quentin** [comment]
Could you provide the result of following command on your equipment (replace USERNAME, PASSWORD and IP) ?
```
curl -k -H 'Accept: text/xml' -u USERNAME:PASSWORD https://IP/storeonceservices/cluster 
```

**Comment by ginjan** [comment]
` <localCapacityBytes>10437740171264</localCapacityBytes> `
 ` <localDiskBytes>5123342106903</localDiskBytes>`
 ` <localFreeBytes>4877382508544</localFreeBytes>`
 `<localUserBytes>52189872717385</localUserBytes>`
` <combinedCapacityBytes>10437740171264</combinedCapacityBytes>`
`<combinedDiskBytes>5123342106903</combinedDiskBytes>`
`<combinedFreeBytes>4877382508544</combinedFreeBytes>`
`<combinedUserBytes>52189872717385</combinedUserBytes>`

Do you need other information?
Thank you for your help.

**Comment by garnier-quentin** [comment]
That's not a valid xml. I think there are some information missing. You can attach the result in a file maybe

**Comment by ginjan** [comment]
[storeOnce.txt](https://github.com/centreon/centreon-plugins/files/3047267/storeOnce.txt)

**Comment by ginjan** [comment]
Hi,

Could you reproduce/replicate the problem ? Have you seen the problem?

Thank you for your help,

Bests regards,

**Comment by garnier-quentin** [comment]
Yes! You can test with the last version

**Comment by ginjan** [comment]
It works.
Thanks for your help.
