### ISSUE TITLE
timeout on selenium plugin

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#1469]
Hi,

I have a strange behavior with the selenium plugin. If I do not set a timeout so the default 50 is used, the scenario always runs through in about 21-22 seconds. But if I give a timeout of 30 seconds then he always goes in timeout.

![selenium_plugin_timout](https://user-images.githubusercontent.com/46994680/55736546-ceb78680-5a23-11e9-9f28-c71145af5b09.png)

Any idea ?

Thanks for help

**Comment by garnier-quentin** [comment]
Coud you send your command with time option ? By default, it's 50 seconds. Your navigator take times to run.

**Comment by rmorandell-pgum** [comment]
Here is the command

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::selenium::plugin --mode=scenario --selenium-hostname=localhost --selenium-port=4444 --directory=/var/lib/centreon_waa --scenario=rve_509_rvvmtiv02pw_bibico --timeout=50 --warning=20 --critical=25

**Comment by rmorandell-pgum** [comment]
with 50 is working ..

perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::selenium::plugin --mode=scenario --selenium-hostname=localhost --selenium-port=4444 --directory=/var/lib/centreon_waa --scenario=rve_509_rvvmtiv02pw_bibico --timeout=30 --warning=20 --critical=25

**Comment by garnier-quentin** [comment]
So it's not a bug. There is the time to launch your browser.

**Comment by rmorandell-pgum** [comment]
you're right. I had not thought of that

Thank you

**Comment by garnier-quentin** [comment]
If you use firefox, you should add a profile with autoupdate off i think. It can explain the time to execute.
