### ISSUE TITLE
[plugin] apps::protocols::http --proxyurl not work

### ISSUE THREAD

**Issue by wilfriedcomte** [centreon/centreon-plugins#147]
Hi, 
I try to use the option --proxyurl but whatever the value that pass in DIRECT not through the Proxy.

perl centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=response --proxyurl sqsq --hostname=google.fr
OK: Response time 0.402s | 'time'=0.402s;;;0; 'size'=18922B;;;0;

perl centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=response --proxyurl=10.xxx.xxx.xxx:8080 --hostname=google.fr
OK: Response time 0.175s | 'time'=0.175s;;;0; 'size'=18827B;;;0;

perl centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=response --proxyurl=justforfun:8080 --hostname=google.fr
OK: Response time 0.144s | 'time'=0.144s;;;0; 'size'=18859B;;;0;

That cool I win every time :)

With pac file  option that work fine but more complicated to implemented on each poller.

Give me if the syntax is correct and if you want more test?

Regards

**Comment by garnier-quentin** [comment]
Maybe the option only works with a correct syntax like: --proxyurl=http://10.0.0.1:8080/

**Comment by garnier-quentin** [comment]
There was a bug. Thanks for the report.

**Comment by wilfriedcomte** [comment]
perfect that work :)
tx
