### ISSUE TITLE
[os::windows::wsman] No username. Authorization canceled

### ISSUE THREAD

**Issue by Gspaz** [centreon/centreon-plugins#1470]
Hello,

I don't know whether I'm facing an issue or I'm wrong when attempting to use WinRM call via **os::windows::wsman**.

Whatever I try I get  "_**No username. Authorization canceled**_", even though the <**domain**>, the  <**user**>, and <**pwd**> are correct because already validated by testing same winRM call between 2 windows server hosts :

```
./centreon_plugins.pl  --plugin=os::windows::wsman::plugin --mode list-services --host <myhost> --wsman-auth-method gssnegotiate --wsman-username <domain>\<user> --wsman-password <pwd> --wsman-debug

Apr  8 17:53:58 [20036] Endpoint: http://*****************:5985/wsman
Apr  8 17:53:58 [20036] cl->authentication.verify_peer: 1
Apr  8 17:53:58 [20036] *****set post buf len = 1121******
Apr  8 17:53:58 [20036] GSS-Negotiate authentication is used
Apr  8 17:53:58 [20036] GSS-Negotiate authentication is used
Apr  8 17:53:58 [20036] Invoking Auth request callback
Apr  8 17:53:58 [20036] No username. Authorization canceled
Apr  8 17:53:58 [20036] Error = 67 (Login denied); user/password wrong or empty.
Apr  8 17:53:58 [20036] curl error code: 67.
Apr  8 17:53:58 [20036] cl->response_code: 401.
Apr  8 17:53:58 [20036] cl->last_error code: 26.
UNKNOWN: Could not enumerate instances: Login denied
```

I also tried several auth mode but no success.

That's like **--wsman-username** is never taken into account, so I tried lots of tests as adding double/simple quotes, or using 2 \\ between _domain_ and _user_, etc...  but no more idea...

Thanks in advance to those who would have any idea or advise regarding the usage of this plugin
Guillaume

**Comment by garnier-quentin** [comment]
I don't think 'gssnegotiate' works. Only basic: https://github.com/Openwsman/openwsman/wiki/https-communication-between-winrm-service-and-wsman-terminal-client
Maybe we could do https now.

**Comment by Gspaz** [comment]
Thank you for your reply, unfortunately , same behaviour using basic mode.
And using https seems to require change on all windows target, what I would prefer to avoid, otherwise we prefer install Nsclient.

**Comment by garnier-quentin** [comment]
If you use basic mode, you can not use user from the domain. Only local user. Could you show me your command line for basic mode ?

**Comment by Gspaz** [comment]
Yes it works using local account and basic mode, thank you
Unfortunately, probably I won't be allowed to use this method within my organisation, I have to check that...

**Comment by garnier-quentin** [comment]
Thanks for the feedback. I close it.
