### ISSUE TITLE
[apps::protocols::http::plugin] negate expression in threshold values

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon-plugins#1473]
Hi

I have a JSON page which contains the following value : {"status":"UP"}

I would like to generate a critical state when the "status" value is different than "UP"

How can I achieve this ? 

I tried with some regex in --critical-string option, but can't get it to work... 

 perl centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=json-content --hostname=xxxxx --port=xxxx --urlpath=/xxx/yyyy --lookup="status" --critical-string=???

Anyone have an idea ?

Thanks !

Norbert

**Comment by garnier-quentin** [comment]
You can use negative regexp.
```
--critical-string='^(?!(UP)$)'
```
