### ISSUE TITLE
Checking haproxy frontends/backends

### ISSUE THREAD

**Issue by morganegzh** [centreon/centreon-plugins#1475]
Hello,

Is there a way to check haproxy frontends and backends state ? 

Please find below documentation regarding script we are using on server side : 
https://www.haproxy.org/download/contrib/netsnmp-perl/README

Thank you, 
Best regards,

**Comment by garnier-quentin** [comment]
You can use --warning-status and --critical-status with mode: frontend-usage and backend-usage for example

**Comment by morganegzh** [comment]
In fact the OID's here don't match haproxy plugin centreon checks. 

Would it be possible to add the corresponding check for the mentionned oid, as for the following request :  https://github.com/centreon/centreon-plugins/issues/327 ? 

Thank you

**Comment by garnier-quentin** [comment]
I don't see what is missing. Could you give OIDs exactly ? For the frontend, we check that:
```
alFrontendName          => { oid => '.1.3.6.1.4.1.23263.4.2.1.3.2.1.3' },
    alFrontendSessionCur    => { oid => '.1.3.6.1.4.1.23263.4.2.1.3.2.1.4' },
    alFrontendSessionTotal  => { oid => '.1.3.6.1.4.1.23263.4.2.1.3.2.1.7' },
    alFrontendBytesIN       => { oid => '.1.3.6.1.4.1.23263.4.2.1.3.2.1.8' },
    alFrontendBytesOUT      => { oid => '.1.3.6.1.4.1.23263.4.2.1.3.2.1.9' },
    alFrontendStatus        => { oid => '.1.3.6.1.4.1.23263.4.2.1.3.2.1.13' },
```

**Comment by morganegzh** [comment]
The root OID is 1.3.6.1.4.1.29385.106 
You can find all OIDs here :  https://www.haproxy.org/download/contrib/netsnmp-perl/README

**Comment by garnier-quentin** [comment]
I use following branch: .1.3.6.1.4.1.23263 (MIB ALOHA)
it's only on ha-proxy appliance ?

There is a mib describing that branch: 1.3.6.1.4.1.29385.106 ?

**Comment by romsworld** [comment]
Hi Quentin,
It's not an appliance, we have haproxy on linux, and perl script to push information in snmp.
We used perl script give in tar gz of ha proxy.

I thinks, it was an equivalent of ALOHA, check here : https://fossies.org/linux/haproxy/contrib/netsnmp-perl/haproxy_frontend.xml

Perhaps, we will test by replacing 23263 by 29385 in centreon script.

**Comment by garnier-quentin** [comment]
There is a mib file ? Could you give us a snmpwalk result:
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.29385 > haproxy.snmpwalk

**Comment by morganegzh** [comment]
Hi,
No there is no MIB file, you can find attached the snmpwalk result.

[haproxy.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/3079027/haproxy.snmpwalk.txt)

**Comment by morganegzh** [comment]
Hi, 
Does the provided file helped you ? 

Thank you.

**Comment by romsworld** [comment]
Hi Quentin,

Do you think you can adapt the script?

**Comment by garnier-quentin** [comment]
Maybe. I need to take a deeper look.

**Comment by garnier-quentin** [comment]
Done. Could you test backend-usage and frontend-usage modes please ?

**Comment by romsworld** [comment]
It works, but there are one error for each test : 

./centreon_plugins.pl --plugin=apps::haproxy::snmp::plugin --mode=frontend-usage --hostname=xxxxx --snmp-version=2 
Argument "5/8" isn't numeric in numeric gt (>) at /tmp/test/centreon-plugins/apps/haproxy/snmp/mode/frontendusage.pm line 163.
OK: All frontends are ok | 'current_sessions_stats'=0;;;0; 'total_connections_stats'=0;;;0; 'traffic_in_stats'=0.00b/s;;;0; 'traffic_out_stats'=0.00b/s;;;0; 'current_sessions_frontend-swift-http'=18;;;0; 'total_connections_frontend-swift-http'=46;;;0; 'traffic_in_frontend-swift-http'=872013.00b/s;;;0; 'traffic_out_frontend-swift-http'=4282088.33b/s;;;0; 'current_sessions_frontend-keystone-https-internal'=0;;;0; 'total_connections_frontend-keystone-https-internal'=0;;;0; 'traffic_in_frontend-keystone-https-internal'=0.00b/s;;;0; 'traffic_out_frontend-keystone-https-internal'=0.00b/s;;;0; 'current_sessions_frontend-keystone-https-admin'=32;;;0; 'total_connections_frontend-keystone-https-admin'=15;;;0; 'traffic_in_frontend-keystone-https-admin'=8391.33b/s;;;0; 'traffic_out_frontend-keystone-https-admin'=34139.33b/s;;;0; 'current_sessions_frontend-mariadb-localnode'=12;;;0; 'total_connections_frontend-mariadb-localnode'=38;;;0; 'traffic_in_frontend-mariadb-localnode'=0.00b/s;;;0; 'traffic_out_frontend-mariadb-localnode'=1116.00b/s;;;0; 'current_sessions_frontend-mariadb'=30;;;0; 'total_connections_frontend-mariadb'=6;;;0; 'traffic_in_frontend-mariadb'=165909.00b/s;;;0; 'traffic_out_frontend-mariadb'=222379.00b/s;;;0; 'current_sessions_frontend-keystone-https-public'=8;;;0; 'total_connections_frontend-keystone-https-public'=29;;;0; 'traffic_in_frontend-keystone-https-public'=6805.33b/s;;;0; 'traffic_out_frontend-keystone-https-public'=24195.67b/s;;;0;


./centreon_plugins.pl --plugin=apps::haproxy::snmp::plugin --mode=backend-usage --hostname=xxxxxx --snmp-version=2 
Argument "6/8" isn't numeric in numeric gt (>) at /tmp/test/centreon-plugins/apps/haproxy/snmp/mode/backendusage.pm line 174.
OK: All backends are ok | 'current_queue_backend-swift'=0;;;0; 'current_sessions_backend-swift'=0;;;0; 'total_connections_backend-swift'=122;;;0; 'traffic_in_backend-swift'=252480.34b/s;;;0; 'traffic_out_backend-swift'=1888619.63b/s;;;0; 'current_queue_backend-keystone-internal'=0;;;0; 'current_sessions_backend-keystone-internal'=0;;;0; 'total_connections_backend-keystone-internal'=0;;;0; 'traffic_in_backend-keystone-internal'=0.00b/s;;;0; 'traffic_out_backend-keystone-internal'=0.00b/s;;;0; 'current_queue_backend-mariadb'=0;;;0; 'current_sessions_backend-mariadb'=26;;;0; 'total_connections_backend-mariadb'=14;;;0; 'traffic_in_backend-mariadb'=206210.55b/s;;;0; 'traffic_out_backend-mariadb'=268438.99b/s;;;0; 'current_queue_backend-keystone-admin'=0;;;0; 'current_sessions_backend-keystone-admin'=0;;;0; 'total_connections_backend-keystone-admin'=113;;;0; 'traffic_in_backend-keystone-admin'=4664.34b/s;;;0; 'traffic_out_backend-keystone-admin'=18976.40b/s;;;0; 'current_queue_backend-keystone-public'=0;;;0; 'current_sessions_backend-keystone-public'=0;;;0; 'total_connections_backend-keystone-public'=72;;;0; 'traffic_in_backend-keystone-public'=3407.60b/s;;;0; 'traffic_out_backend-keystone-public'=12115.36b/s;;;0; 'current_queue_stats'=0;;;0; 'current_sessions_stats'=0;;;0; 'total_connections_stats'=0;;;0; 'traffic_in_stats'=0.00b/s;;;0; 'traffic_out_stats'=0.00b/s;;;0; 'current_queue_backend-mariadb-localnode'=0;;;0; 'current_sessions_backend-mariadb-localnode'=9;;;0; 'total_connections_backend-mariadb-localnode'=183;;;0; 'traffic_in_backend-mariadb-localnode'=52134.12b/s;;;0; 'traffic_out_backend-mariadb-localnode'=70000.47b/s;;;0;

**Comment by garnier-quentin** [comment]
My bad. It should be ok now. Could you test it ?

**Comment by romsworld** [comment]
:D ! Very good, Thanks a lot.
