### ISSUE TITLE
[perfdata] Separate item name from perfdata label

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1476]
Hi,

Let's take the `interfaces` mode as an example.

When there is only one grabbed interface, here's how perfdata looks like :

```'traffic_in'=399008.00b/s;;;0;10000000000
'traffic_out'=226480.00b/s;;;0;10000000000
'packets_discard_in'=0;;;0;293
'packets_error_in'=0;;;0;293
'packets_discard_out'=0;;;0;275
'packets_error_out'=0;;;0;275
```

When there are several interfaces, the interface `_name` is added to the perfdata labels :

```'traffic_in_sfp-sfpplus1'=905808.00b/s;;;0;10000000000
'traffic_out_sfp-sfpplus1'=669016.00b/s;;;0;10000000000
'packets_discard_in_sfp-sfpplus1'=0;;;0;235
'packets_error_in_sfp-sfpplus1'=0;;;0;235
'packets_discard_out_sfp-sfpplus1'=0;;;0;253
'packets_error_out_sfp-sfpplus1'=0;;;0;253
```

I'm sending perfdata from Centreon to InfluxDB, using the [Stream connector script](https://github.com/centreon/centreon-stream-connector-scripts/tree/master/influxdb).
And I would like to be able to automatically detect that an item name has been appended to the perfdata label, so that instead of pushing the following InfluxDB series :
`traffic_in_sfp-sfpplus1=905808`
I would push :
`traffic_in=905808 item=sfp-sfpplus1`

Unfortunately, I don't see how to do this easily.
Cutting at last `_` character encountered is not a solution : as in the first example, if we don't have an item name appended to the perfdata label, it will lead to strange results. Same thing if item name contains some `_`.

Among all the various plugins, character `_` is used in perfdata labels, but sounds like `-` is not.
Perhaps we could use `-` character instead of `_` to separate perfdata label from item name ?
We would then be able to cut at the first `-` encountered to reveal the item name, if it exists.

Perhaps there are other ways.

Thank you very much for your help 👍

**Comment by garnier-quentin** [comment]
I could add an option to append the instance maybe ?

**Comment by CPbN** [comment]
Thank you for your response.
How would this work ?
As the item name is already automatically appended by the various plugins.

**Comment by garnier-quentin** [comment]
I'll add an option like: --perfdata-instance-separator='.'

**Comment by CPbN** [comment]
Ah yes sounds good :+1:
Defaulting to another character than `_` would also be nice, but would certainly break already deployed graphs etc...
Many thanks !

**Comment by garnier-quentin** [comment]
But we need to think about it. If we want to add a newformat metrics.

**Comment by CPbN** [comment]
No problem for me if you default to a different separator than `_`, such as `-` or `.`.
On the contrary, would be a nice improvement, without having to use `--perfdata-instance-separator` everywhere.
Would be sort of breaking change for the existing graphs, but well they could be regenerated.
Sounds like a great benefit ;)

**Comment by garnier-quentin** [comment]
Don't use it in production. Still experimental ;)

**Comment by CPbN** [comment]
OK ! Glad to see you managed to find a solution, looks promising !
Feel free to ping me anytime if you need some testing from me :+1:

**Comment by CPbN** [comment]
Perhaps that once feature will be ready, `--use-old-perfdata` would be better than `--use-new-perfdata`, so that we won't have to use `--use-new-perfdata` everywhere :)
Only ones who want to stick with old format would have to use `--use-old-perfdata`.

**Comment by garnier-quentin** [comment]
We can't. it will break everything ;)

**Comment by CPbN** [comment]
Yep, would be a breaking change, but with its workaround for users who want to stick with "old" format (there have been some other breaking changes in the past, well, generally limited to one plugin  at a time).
I suspect only a limited number of users would use the "new" format, if its not the default one.
In several months (years ? ^^), we will still be referencing it as the "new" format, whereas you would have perhaps wanted to make it the default / current one, so that users adopt it.
Without the breaking impact in mind, at user level, it's more user-friendly to have to use `--use-old-perfdata` instead of having to add `--use-new-perfdata` everywhere :)

**Comment by garnier-quentin** [comment]
Yes but no. You can add it in a generic template.

**Comment by CPbN** [comment]
Sure, that's the way to do use it :+1:

**Comment by CPbN** [comment]
From my understanding, sounds like plugins must inherit from the counter template to provide the `--use-new-perfdata` feature, right ?
Certainly why the interfaces plugin does not properly show-up it yet.

**Comment by garnier-quentin** [comment]
Because we need to update it. It will take times.

**Comment by CPbN** [comment]
Of course, thank you for confirming this.

**Comment by CPbN** [comment]
With `--use-new-perfdata`, in addition to the already discussed instance separator (`#` as you chose), you also rename every metric name to what looks like a standardized format.
You already had this change in mind before we discussed the separator ?
What are the needs behind this ? Are there specific ones ?
Thank you :+1:

**Comment by CPbN** [comment]
First test with Mikrotik temperature, perfdata is correctly split into InfluxDB, perfect :+1:
```
> select * from "hw-temperature"
name: hw-temperature
time                hardware.temperature.celsius host           inst
----                ---------------------------- ----           ----
1555533720000000000 38                           fw-dc-intern   processor
1555533721000000000 41                           fw-cust-ntbf   system
1555533722000000000 25                           fw-diff-parb   system
1555533900000000000 39                           fw-dc-intern   processor
1555533901000000000 41                           fw-cust-ntbf   system
1555533902000000000 25                           fw-diff-parb   system
```

Thank you again :)
