### ISSUE TITLE
[storage::qnap::snmp::plugin] Cannot see any disk

### ISSUE THREAD

**Issue by m4gn3to** [centreon/centreon-plugins#1477]
Hi.

I have a pair of Qnaps:
- TS-1263U-RP (Firmware version 4.3.6.0895)
- TS-1279U-RP (Firmware version 4.3.4.0695)

With the plugin I can check everything correctly but the disks. When I use:
$ centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --mode=hardware --component=disk --verbose --hostname=xxx.xxx.xxx.xxx --snmp-community=xxxxx --snmp-version=2c --snmp-timeout=30 --debug

I only see:

OK: All 0 components are ok []. |
Checking disks
$

And no info about the disks.

I've checked the oids manually and all are OK, I can get the HD descriptions, state, SMART, temps... but the plugin returns no info.

What I'm doing wrong?

Thanks.

**Comment by garnier-quentin** [comment]
Could you provide the result of following command ?
```
snmpwalk -ObentU -v 2c -c public IP .1 > qnap.snmpwalk
```

**Comment by m4gn3to** [comment]
Of course.

Here you have...
[qnap.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/3077662/qnap.snmpwalk.txt)

Thank you.

**Comment by garnier-quentin** [comment]
Do you also have the mib file ?

**Comment by m4gn3to** [comment]
Yes.
[NAS.mib.txt](https://github.com/centreon/centreon-plugins/files/3085443/NAS.mib.txt)

**Comment by garnier-quentin** [comment]
I have tested and it's working:
```
perl centreon_plugins.pl --plugin=storage/qnap/snmp/plugin.pm --hostname=xxxxx --snmp-port=161 --snmp-community=qnap --snmp-version=2c  --mode=hardware --verbose --component=disk
OK: All 12 components are ok [12/12 disks]. | 'temp_disk_1'=39C;;;; 'temp_disk_2'=38C;;;; 'temp_disk_3'=36C;;;; 'temp_disk_4'=34C;;;; 'temp_disk_5'=40C;;;; 'temp_disk_6'=39C;;;; 'temp_disk_7'=35C;;;; 'temp_disk_8'=32C;;;; 'temp_disk_9'=33C;;;; 'temp_disk_10'=34C;;;; 'temp_disk_11'=32C;;;; 'temp_disk_12'=31C;;;; 'count_disk'=12;;;;
Checking disks
Disk 'HDD1' [instance: 1, temperature: 39 C/102 F, smart status: GOOD] status is ready.
Disk 'HDD2' [instance: 2, temperature: 38 C/100 F, smart status: GOOD] status is ready.
Disk 'HDD3' [instance: 3, temperature: 36 C/96 F, smart status: GOOD] status is ready.
Disk 'HDD4' [instance: 4, temperature: 34 C/93 F, smart status: GOOD] status is ready.
Disk 'HDD5' [instance: 5, temperature: 40 C/104 F, smart status: GOOD] status is ready.
Disk 'HDD6' [instance: 6, temperature: 39 C/102 F, smart status: GOOD] status is ready.
Disk 'HDD7' [instance: 7, temperature: 35 C/95 F, smart status: GOOD] status is ready.
Disk 'HDD8' [instance: 8, temperature: 32 C/89 F, smart status: GOOD] status is ready.
Disk 'HDD9' [instance: 9, temperature: 33 C/91 F, smart status: GOOD] status is ready.
Disk 'HDD10' [instance: 10, temperature: 34 C/93 F, smart status: GOOD] status is ready.
Disk 'HDD11' [instance: 11, temperature: 32 C/89 F, smart status: GOOD] status is ready.
Disk 'HDD12' [instance: 12, temperature: 31 C/87 F, smart status: GOOD] status is ready.
```

**Comment by m4gn3to** [comment]
What a strange... I've copied and pasted your command and get the same empty answer:

-bash-4.1$ perl centreon_plugins.pl --plugin=storage/qnap/snmp/plugin.pm --hostname=xxxxxxx --snmp-port=161 --snmp-community=qnap --snmp-version=2c  --mode=hardware --verbose --component=disk
OK: All 0 components are ok []. |
Checking disks
-bash-4.1$ perl centreon_plugins.pl --plugin=storage/qnap/snmp/plugin.pm --hostname=xxxxxxxx --snmp-port=161 --snmp-community=qnap --snmp-version=2c  --mode=hardware --verbose --component=disk
OK: All 0 components are ok []. |
Checking disks
-bash-4.1$

**Comment by garnier-quentin** [comment]
That's weird. Are you available tomorrow for a distant session ? You can send me an email.

**Comment by m4gn3to** [comment]
Mistery resolved. My centreon server is corrupted, I've checked it from another poller and it works correctly....

Sorry :(

**Comment by garnier-quentin** [comment]
Thanks for the feedback
