### ISSUE TITLE
network::cisco::standard::snmp::plugin - not possible to use OID's designed for 64-bit architecture

### ISSUE THREAD

**Issue by qladriere** [centreon/centreon-plugins#1480]
Dears,

Via plugin network::cisco::standard::snmp::plugin, we can't use OID's designed for 64-bit architecture. Indeed, on the Cisco ASR 1000, for example, you need to use the OIDs designed for 64-bit architecture platforms in order to monitor memory usage (see below). Due to that, we can't monitor memory on Cisco ASR devices. 

Processor Pool Free Memory | 1.3.6.1.4.1.9.9.221.1.1.1.1.20.7000.1 | (MIB-cempMemPoolHCFree)
Processor Pool Largest Memory | 1.3.6.1.4.1.9.9.221.1.1.1.1.22.7000.1 | (MIB-cempMemPoolHCLargestFree)
Processor Pool Used Memory | 1.3.6.1.4.1.9.9.221.1.1.1.1.18.7000.1 | (MIB-cempMemPoolHCUsed)
Processor Pool Lowest Memory | 1.3.6.1.4.1.9.9.221.1.1.1.1.24.7000.1 | (MIB-cempMemPoolHCLowestFree)

Source : https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/118901-technote-snmp-00.html#anc6

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk ?
snmpwalk -ObentU -v 2c -c public IP_CISCO .1.3.6.1.4.1.9.9.221.1.1.1.1 > cisco_asr.snmpwalk

**Comment by qladriere** [comment]
Hello,
Here is the output of different OID's. I've also attached the screenshot where you can see the values on the Cisco device.
Remark : you will see values of OID's 64-bits & values on Cisco device are not exactly the same but it's just due to the fact that command has not been executed at the same moment (memory usage is not something static ;-) ).

![image](https://user-images.githubusercontent.com/30145868/56199452-3a5dad00-603d-11e9-9aff-9d5b1f360f0a.png)

[cisco_asr.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/3084128/cisco_asr.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
I would like to get the name also: .1.3.6.1.4.1.9.9.221.1.1.1.1.3

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test with the last version please ?

**Comment by qladriere** [comment]
Hello,
Sorry didn't saw directly your previous comments. I've tested but got following error :
UNKNOWN: Can't call method "map_instance" on an undefined value at /tmp/test/centreon-plugins-master/centreon/common/cisco/standard/snmp/mode/memory.pm line 154.

**Comment by garnier-quentin** [comment]
Thanks for the feedback. You can test it with the last version.

**Comment by qladriere** [comment]
Hello,
Sorry for late answer. Now I don't get the "unknown" anymore but it returns again the value 32-bits :
OK: Memory 'Processor' Usage Total: 2.61 GB Used: 2.51 GB (96.23%) Free: 100.96 MB (3.77%) | 'used'=2699620960B;;;0;2805479976

**Comment by garnier-quentin** [comment]
You can test it again with last version. Now, i check enhanced-mempool first

**Comment by qladriere** [comment]
I made some tests and it looks ok now. Thanks a lot for quick reaction. I'll now apply the latest version of plugins for all services and see if there is no other issue.
