### ISSUE TITLE
Expand the functionality of monitoring f5 pools

### ISSUE THREAD

**Issue by troja89** [centreon/centreon-plugins#1481]
Would it be possible to expand the functionality of monitoring f5 pools?
Could please you add 2 additional modes to the plugin or expand the mode "pool-status"?
Here are the OIDs and explanations - 
1.3.6.1.4.1.3375.2.2.5.1.2.1.8 - Shows the number of the current active members in the specified pool.
1.3.6.1.4.1.3375.2.2.5.1.2.1.23 - The total number of members in the specified pool.

Thank you!

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk please ? (you can send it by email)
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.3375 > bigip.snmpwalk

**Comment by troja89** [comment]
I sent the snmpwalk via e-mail.

**Comment by garnier-quentin** [comment]
I have refactor that mode. It would be better :)
