### ISSUE TITLE
[extend-perfdata-group] Must escape $ sign

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1482]
Hi,

I use the following option :
```
--extend-perfdata-group=',max.core.cpu.utilization.percentage,max(^[0-9]+#core.cpu.utilization.percentage\$),%'
```

As you notice, I have to escape `$` sign using `\`.
Without escaping, Perl fails, as this user input is read using `eval`.

Just one question then, did you know we would have to escape characters here / is it expected ?
Or would you prefer to escape them in the code before using `eval` ?

Thank you :+1:

**Comment by garnier-quentin** [comment]
I think, you don't need '$' ;)

**Comment by CPbN** [comment]
Of course, it's not absolutely needed here.
No problem for me to escape if needed, I just opened this ticket to notify you the behavior.
We must certainly find the same behavior in other options in which we can use `$1` ... `$n` references.
Feel free then to close this if it works as expected :)

**Comment by garnier-quentin** [comment]
thanks for the issue. Could be useful.
