### ISSUE TITLE
New Ceph support

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1484]
Hi,
it would be nice to have a plugin to monitor Ceph Object Storages and Ceph Block Storages (https://ceph.com/)

**Comment by garnier-quentin** [comment]
It seems there is a Rest API. If you could provide curl commands, it would be great.

**Comment by joschi99** [comment]
I have found the following documentation: http://docs.ceph.com/docs/master/mgr/restful/

**Comment by ypilpre** [comment]
I will start a plugin for Ceph. I expect a release within two months (but no guarantee...)

**Comment by Gregesp** [comment]
Hello,
This plugin is always under development ?
Regards,
Greg

**Comment by garnier-quentin** [comment]
Not yet. But we are going to take a look.

**Comment by garnier-quentin** [comment]
It's merged. 
```
$ perl centreon_plugins.pl --plugin=apps::ceph::restapi::plugin --mode=osd  --hostname=10.25.8.10  --api-username=admin --api-password=pass --insecure
OK: Number of osd detected: 3, online 100.00% (3 on 3), participating 100.00% (3 on 3) | 'osd.detected.count'=3;;;0; 'osd.online.count'=3;;;0;3 'osd.online.percentage'=100.00%;;;0;100 'osd.participating.count'=3;;;0;3 'osd.participating.percentage'=100.00%;;;0;100
```
