### ISSUE TITLE
[apps::protocols::telnet::mode::scenario] A helping hand needed

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1486]
Hello guys,

I have the problem, that with the integrated help I don't know how to check my service through Telnet protocol.
I can connect to the server and when I write "STATUS" I receive a Information in this format:
**WORKING <timestamp>** or **IDLE <timestamp>**
This is an example how it looks:

```
telnet SERVER PORT
Trying xxx.xxx.xxx.xxx...
Connected to SERVER.
Escape character is '^]'.
STATUS
IDLE (09:28:07)
QUIT
Connection closed by foreign host.
```

I know, that here are only issues noted, but with as described above, with the integrated help it's not possible to check my service. It's always responding with

> UNKNOWN: Cannot decode json scenario

I need to check if the "timestamp" is matching the actual time or if it's not. is it possible to do this with this plugin?

Thank you very much for helping.

**Comment by garnier-quentin** [comment]
Hi,

WIth that mode, you can check if you get  IDLE with a time. But you can't check if it's the actual time.
An example of scenario file:
```
 # Example of a scenario file:
    # [
    #  {"cmd": "open", "options": { "Host": "10.0.0.1", "Port": "23", "Timeout": "30" } },
    #  {"cmd": "login", "options": { "Name": "admin", "Password": "pass", "Timeout": "5" } },
    #  {"cmd": "waitfor", "options": { "Match": "/string/", "Timeout": "5" } },
    #  {"cmd": "put", "options": { "String": "/mystring/", "Timeout": "5" } },
    #  {"cmd": "close" }
    #]
```

I think you'll need to develop a dedicated mode.

**Comment by MikeW83** [comment]
Hi,

I have already tried to use this example. I found it in the repository of the plugin. I have changed the file like this:

```
[
        {"cmd": "open", "options": { "Host": "SERVER", "Port": "PORT", "Timeout": "30" } },
        {"cmd": "put", "options": { "String": "/STATUS/", "Timeout": "5" } },
        {"cmd": "waitfor", "options": { "Match": "/IDLE/", "Timeout": "5" } },
        {"cmd": "close" }
]
```

I don't need username and password for connecting to the server. And this is the command in Centreon:
`./centreon_protocol_telnet.pl --plugin=apps::protocols::telnet::plugin --mode=scenario --hostname=SERVER --port PORT --scenario=/root/SERVER.scn --verbose --debug`

I get this:

> UNKNOWN: Cannot decode json scenario

What I'm doing wrong? Thank you very much.

**Comment by garnier-quentin** [comment]
I think, it cannot read the file '/root/SERVER.scn'. So it tries it directly to use it like a json string.

**Comment by MikeW83** [comment]
> 
> 
> I think, it cannot read the file '/root/SERVER.scn'. So it tries it directly to use it like a json string.

Are there any recommendations or permission settings I have to use for such a file?

**Comment by garnier-quentin** [comment]
The user centreon-engine should be able to read the file.

**Comment by MikeW83** [comment]
> 
> 
> The user centreon-engine should be able to read the file.

I'm trying it as root user directly via SSH on the server. If it's working I would move the file to another location where I put another configurations for other servers where I need such a check.

**Comment by garnier-quentin** [comment]
thanks for the feedback. Is it ok for you ?

**Comment by MikeW83** [comment]
> 
> 
> thanks for the feedback. Is it ok for you ?

No, it's also not working as root user on the server. :-(

**Comment by garnier-quentin** [comment]
What do you have with root user ?

**Comment by MikeW83** [comment]
I have tried all commands above with the root user. Is there anything wrong with the command line or anything else? I'm not able to get this check working.

**Comment by garnier-quentin** [comment]
Could you get me the output with the root user ?

**Comment by MikeW83** [comment]
All above is done with the root user. Before I implement a new check I try the checks manually and the I add it as command for service checks.

**Comment by garnier-quentin** [comment]
Weird. For me it's working (i don't have the issue with json decode):
```
perl centreon_plugins.pl --plugin=apps::protocols::telnet::plugin --mode=scenario --hostname=SERVER --port PORT --scenario=/tmp/scenario.txt --verbose
CRITICAL: cannot open session: unknown remote host: SERVER |
```

**Comment by MikeW83** [comment]
I think I have found the issue. It's the syntax of the command line. I have not tried
--scenario=/root/SERVER.txt
instead of
--scenario="/root/SERVER.txt" or with --scenario='/root/SERVER.txt'

No I get this error:

> errmsg: pattern match timed-out

When I do this manually I receive

> Escape character is '^]'.
> STATUS
> IDLE (11:42:10)
> QUIT
> Connection closed by foreign host.

What do I have forgotten within the file? Is it possible to check the match with OR to check if one of two strings are in the output?

**Comment by garnier-quentin** [comment]
Sorry, it should be like that:
```
[
        {"cmd": "open", "options": { "Host": "SERVER", "Port": "PORT", "Timeout": "30" } },
        {"cmd": "put", "options": { "String": "STATUS\n", "Timeout": "5" } },
        {"cmd": "waitfor", "options": { "Match": "/IDLE/", "Timeout": "5" } },
        {"cmd": "close" }
]
```

**Comment by MikeW83** [comment]
> 
> 
> Sorry, it should be like that:
> 
> ```
> [
>         {"cmd": "open", "options": { "Host": "SERVER", "Port": "PORT", "Timeout": "30" } },
>         {"cmd": "put", "options": { "String": "STATUS\n", "Timeout": "5" } },
>         {"cmd": "waitfor", "options": { "Match": "/IDLE/", "Timeout": "5" } },
>         {"cmd": "close" }
> ]
> ```

No, sorry. Same error. After IDLE is a timestamp when I check it with telnet directly. Does this matter?

**Comment by MikeW83** [comment]
Strange... I have nothing changed... Now the check is working.

**Comment by garnier-quentin** [comment]
It's reliable ?
