### ISSUE TITLE
centreon_windows_snmp.pl mode=storage --free

### ISSUE THREAD

**Issue by Openema** [centreon/centreon-plugins#1490]
Hello, 

I have a problem to check the storage using --free option.
I read this doc : 
https://documentation-fr.centreon.com/docs/centreon-plugins/fr/latest/user/guide.html#windows

But the command not work

When do this command with the same values and arguments :

/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=xxxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='public'  --storage='E:' --name --display-transform-src='^(..).*' --display-transform-dst='$1' --free --units="B" --warning-usage='5497558138880' --critical-usage='2199023255552' --regexp

The result is : 
OK : Storage 'E:' Usage total: 100.00 GB Used: 95.86 GB (95.86%) Free: 4.13 GB (4.14%) | 'free'=4439793664B;0:5497558138880;0:2199023255552;0;107371032576

I am on the last version of Centreon (19.04.0) and all plugins are up to date.

Tell me if any informations missing.

Thank you for regard and sorry for my English

**Comment by Openema** [comment]
An another information, it was not a fresh install from 19.04 directly

It was an install on 18.10.0 from centreon ISO, updated in 18.10.3 and then updated in 19.04

Thanks

**Comment by Openema** [comment]
Hello, 

with several tests, I think the option --free is not taken into account

Someone can help me, please

**Comment by pkriko** [comment]
Hello,

Can you try this : 
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=xxxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='public' --storage='E:' --name --display-transform-src='^(..).*' --display-transform-dst='$1' --free --units="B" --warning-usage='5497558138880:' --critical-usage='2199023255552:' --regexp

Is it normal that you want to check if there is less than 5TB of free space ?

For 5GB, it must be 5368709120 and not 5497558138880.

Regards.

**Comment by Openema** [comment]
Hello,

Thank you fot you return.

Ok for the value, i just copy that from the doc but i d'on't verify this.

So, my command was good but missing ":" in warning-usage and goods values.
Why if need to put ":" in warning-usage value ? I don't see anything about this in help of command ?

Thank you for your help

Regards

**Comment by pkriko** [comment]
We develop our threshold following the nagios thresholds.

You can take a look here http://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT to have more informations about the format.

Maybe we need to improve our help message.

Regards,

**Comment by Openema** [comment]
Ok, thanks for the explications

Yes, maybe in help message you can indicate the format if using free space alert (--free option) or using space.

a last question, today, is not possible to put value in MB or GB rather B ?

I suppose you know this but I don't know if it's possible.
With an old version of centreon (2.7.0) i used this script :
https://nagios.fandom.com/wiki/Plugin:check_centreon_snmp_remote_storage

When thresholds are single value (ex: 60, 80 ,...) it was considered in % of used but when you put a value with GB, MB... It work with free space.
Maybe it is was easier to use like this ?

**Comment by pkriko** [comment]
Hello Openema,

Unfortunately no.

You can change the unit of the perfdata by using the ```--change-perfdata``` option, but you won't have the possibility to have different units other than % or Bytes in the threshold.

```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin --mode storage --hostname=127.0.0.1 --storage / --name --change-perfdata='used,,scale(MB),MB'
OK: Storage '/' Usage Total: 11.69 GB Used: 2.78 GB (23.77%) Free: 8.91 GB (76.23%) | 'used'=2844.64MB;;;0;11967.13
```

Maybe @garnier-quentin will explain better than me why we have change this behavior.

Regards,

**Comment by Openema** [comment]
Hello,

Thank you for your return.

I have all the information now.

I can close this issue now

Thanks for your help

Goodbye
