### ISSUE TITLE
[Atto Fiber channel switch] plugin request

### ISSUE THREAD

**Issue by und3ath** [centreon/centreon-plugins#1493]
Hi it is possible to dev  a plugin to monitor ATTO Fiber channel switch ? 
The target device is a 7500N btw the mib file name is 6500N . 

Here the required informations  :  

The mib file : http://www.circitor.fr/Mibs/Html/A/ATTO6500N-MIB.php 

For the full snmp walk of the entreprise branch it is possible to send it in private ? As it contain address ip and other sensibles informations . 

Let me know if u need some other informations . 

Cheers .

**Comment by Sims24** [comment]
Hi @und3ath ,

Thanks, yes you can send it to 

cgagnaire@centreon.com
qgarnier@centreon.com
sbomm@centreon.com 

;)

**Comment by und3ath** [comment]
Thx, informations sent to cgagnaire and qgarnier .

**Comment by garnier-quentin** [comment]
I have looked the snmpwalk and the mib. We can monitor:
- hardware: chassisTemperature, chassisTemperatureStatus and chassisThroughputStatus
- fcport-usage: port state (adminstate, operstate), tx/rx word trasmitted, invalidCRC, signalloss
- sasport-usage: port state (adminstate, operstate), invalidCRC, lossofsync

It seems ok for you ? You provide the entreprise snmpwalk. Your Atto Fiberbridge manages some standard SNMP MIBS ? (like UCD: .1.3.6.1.4.1.2021. CPU: .1.3.6.1.2.1.25)

**Comment by und3ath** [comment]
Hi, sorry for the late response, i was in vacations . 
The atto bridge support standards mibs too . 
Do you want a snmpwalk dump ?
