### ISSUE TITLE
Netapp SnapCenter plugin

### ISSUE THREAD

**Issue by und3ath** [centreon/centreon-plugins#1495]
Hi, i would like to monitor Netapp SnapCenter backups jobs trought SnapCenter REST API . 
It is possible to dev a plugin for that ? 
It's a rest api similar to the API used for Netapp OnCommand API Services . 

Here is the link to the documentation . 
http://docs.netapp.com/ocsc-30/index.jsp?topic=%2Fcom.netapp.doc.ocsc-ag%2FGUID-F2F08997-953E-4C60-B572-F435A5BD77F5.html

If it's possible,  and need more info or testing lsomething let me know . 

Thx in advance . 
Benjamin .

**Comment by garnier-quentin** [comment]
Could you provide curl commands ? (authentification+api call you need to be on the plugin. Like jobs results for example maybe)

**Comment by und3ath** [comment]
Hi, i sent you the requested informations trough mail as there are some private informations in .
