### ISSUE TITLE
dns dig check

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#15]
Add dns dig check
save ip from domain in cache, alert on change

Discussion: If an SOA entry is changing, you send a alert ?
You can already do it if you specify the IP it should be. But if you don't specify and only want to alert if there is a change, it can be done (with a cache file to save data).

:D i really dont want to specify the ips for our 300 customers websites.
so a cache file use whould be really nice.

**Comment by florian-asche** [comment]
my request
