### ISSUE TITLE
network::juniper::ex::plugin hardware mode problem

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#150]
Hi,

I have strange problem. When I check hardware with network::juniper::ex::plugin from EX3300 device it gives me error: UNKNOWN: Fru 'Routing Engine 1' state is unknown [offline reason: unknown]
My command is: ./centreon_plugins.pl --plugin=network::juniper::ex::plugin --snmp-version=2c --snmp-community=xxx --hostname=xxx --mode=hardware
With --verbose I see this:
UNKNOWN: Fru 'Routing Engine 1' state is unknown [offline reason: unknown] | 'temp_FPC: EX3300 24-Port POE+ @ 0/*/*'=38C;;;; 'temp_Routing Engine 0'=38C;;;;
Environment type: Juniper EX3300-24P Ethernet Switch
Checking frus
Fru 'Power Supply 0' state is online [instance: 2.1.1.0, type: powerEntryModule, offline reason: none]
Fru 'Fan 1' state is online [instance: 4.1.1.1, type: fan, offline reason: none]
Fru 'Fan 2' state is online [instance: 4.1.1.2, type: fan, offline reason: none]
Fru 'FPC: EX3300 24-Port POE+ @ 0/*/*' state is online [instance: 7.1.0.0, type: flexiblePicConcentrator, offline reason: none]
Fru 'PIC: 24x 10/100/1000 Base-T @ 0/0/*' state is online [instance: 8.1.1.0, type: portInterfaceCard, offline reason: none]
Fru 'PIC: 4x GE/XE SFP+ @ 0/1/*' state is online [instance: 8.1.2.0, type: portInterfaceCard, offline reason: none]
Fru 'Routing Engine 0' state is online [instance: 9.1.0.0, type: routingEngine, offline reason: none]
Fru 'Routing Engine 1' state is unknown [instance: 9.2.0.0, type: routingEngine, offline reason: unknown]
Checking operatings
Operating '' state is running [instance: 1.1.0.0]
Operating 'Power Supply 0' state is running [instance: 2.1.1.0]
Operating 'Fan 1' state is running [instance: 4.1.1.1]
Operating 'Fan 2' state is running [instance: 4.1.1.2]
Operating 'FPC: EX3300 24-Port POE+ @ 0/*/*' state is running [instance: 7.1.0.0]
Operating 'PIC: 24x 10/100/1000 Base-T @ 0/0/*' state is running [instance: 8.1.1.0]
Operating 'PIC: 4x GE/XE SFP+ @ 0/1/*' state is running [instance: 8.1.2.0]
Operating 'Routing Engine 0' state is running [instance: 9.1.0.0

With this command my graphs show temperature nicely, although I service says it is in unknown state.

But when I use --exclude=fru #9.2.0.0# it turns service to green and says OK: All 8 components are ok [8/8 operatings] but Graphs STOP. So with the exclusion the temperature graphs are not drawn.

Am I doing something wrong?

**Comment by garnier-quentin** [comment]
Hi,

I think your have an space in your option. Try like that:
--exclude='fru#9.2.0.0#'

**Comment by kadrika** [comment]
Thanks!!!!
I didn't notice the space :(

**Comment by garnier-quentin** [comment]
You're welcome!
