### ISSUE TITLE
Plugin for TCP retransmit (snmp)

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#1500]
Hi,

is there a plugin to measure the tcp retransmits? I´ven´t found anything at the snmp interface oder tcp checks of centreon, but perhaps it is called similar? Has anyone a hint, if I could handle this by centreon?

There would be a possibility at tcpcon module of snmp, but it doesn´t seem to implemented. The regarding Net-oid is: .1.3.6.1.2.1.6.12 (tcpRetransSegs)

**Comment by Sims24** [comment]
Hi @benhartwich 

No, but we would love to have a dedicated plugin for tcp segments monitoring. 

Could you provide a snmpwalk of .1.3.6.1.2.1.6 from one of your equipement please ? 

In the meantime you can of course give a try to CPbN workaround it should work but as it's a counter so be warned that without cache mechanism it will be hard to put accurate threshold on it. 

Thanks

**Comment by benhartwich** [comment]
Hi,
I get the following result on linux:
```
[root@emea ~]# snmpwalk -v 2c -c public -O e test.xy.de  .1.3.6.1.2.1.6.12
TCP-MIB::tcpRetransSegs.0 = Counter32: 1346640
```

**Comment by benhartwich** [comment]
@CPbN Thanks for your workaround, but I didn´t get it working:

```
[root@emea]# ./centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=test.xy.de -snmp-version=2c --snmp-community=public --config-json='[ { "oid": ".1.3.6.1.2.1.6.12","perfdata_name": "oid1", "format": "current oid1 value is %s"} ]'
UNKNOWN: SNMP GET Request : Cant get a single value.
```
I´ve tried it without config json and --oid= but both didn´t get any value. As snmpwalk works, there can´t be problem with the host. Am I doing anything wrong?

**Comment by CPbN** [comment]
Try with the following OID : `.1.3.6.1.2.1.6.12.0`
You can also use `--oid-type=counter` so that you will get the diff with the previous value :+1:

**Comment by benhartwich** [comment]
@CPbN thanks, the workaround is working!

**Comment by Sims24** [comment]
>You can also use --oid-type=counter so that you will get the diff with the previous value

Hey, didn't know it has been implemented so cool ^-^
