### ISSUE TITLE
os::linux::snmp::plugin --mode=memory : Incorrect used size

### ISSUE THREAD

**Issue by johnbritto1** [centreon/centreon-plugins#1501]
Hello,

On the VM, its showing as,
              total        used        free      shared  buff/cache   available
Mem:      3951        1128         206          17        2616        2497
Swap:      1906           2        1904

But using the plugin,
/usr/lib/centreon/plugins/centreon_plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=xxx --snmp-version='3' --snmp-community='' --snmp-port=xxx --snmp-username=xxx --authprotocol=MD5 --privprotocol=AES --authpassphrase=xxxx --privpassphrase=xxx --warning-usage='80' --critical-usage='90'

WARNING: Ram Total: 3.86 GB Used (-buffers/cache): 3.28 GB (84.98%) | 'used'=3520737280B;0:3314565120;0:3728885760;0;4143206400 'buffer'=144642048B;;;0; 'cached'=262660096B;;;0; 'shared'=18382848B;;;0;

As you can see that the plugin doesn't do (-buffers/cache) to show the actual memory being used. 

Shall we have a --mode to check actual memory usage subtracting the buffer/cache ?

Thanks,

**Comment by Sims24** [comment]
Hi @johnbritto1 ,

Actually it does, that's why we get two different value in the output :) But I imagine that you would like to set the threshold on the value in bold below right ? 

WARNING: Ram Total: 3.86 GB Used **(-buffers/cache): 3.28 GB** (84.98%) 

For now it's not possible we need to think about it on how we can achieve this, need to see with other maintainer what is the best way to address it

**Comment by johnbritto1** [comment]
Can we add a --mode  like  --real which calculate the Used RAM as
Used RAM = (Total RAM - (Buffers + cached))

Thanks

**Comment by garnier-quentin** [comment]
That's the formula used. So i don't understand the issue. Could you provide the snmpwalk of following branch '.1.3.6.1.4.1.2021.4' and the free -m result also.

**Comment by johnbritto1** [comment]
@garnier-quentin 

free -m of the monitored server.
free -m
              total        used        free      shared  buff/cache   available
Mem:           3951        1155         200          19        2595        2467
Swap:          1906           4        1902

snmpwalk for the MIB '.1.3.6.1.4.1.2021.4'
[root@monitoring centreon_plugins]# snmpwalk -v3  -l authPriv -u test -a MD5 -A XXXX -x AES -X XXX 192.XX.1XX.9X:6XXX .1.3.6.1.4.1.2021.4
UCD-SNMP-MIB::memIndex.0 = INTEGER: 0
UCD-SNMP-MIB::memErrorName.0 = STRING: swap
UCD-SNMP-MIB::memTotalSwap.0 = INTEGER: 1952764 kB
UCD-SNMP-MIB::memAvailSwap.0 = INTEGER: 1947864 kB
UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 4046100 kB
UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 204756 kB
UCD-SNMP-MIB::memTotalFree.0 = INTEGER: 2152620 kB
UCD-SNMP-MIB::memMinimumSwap.0 = INTEGER: 16000 kB
UCD-SNMP-MIB::memShared.0 = INTEGER: 20284 kB
UCD-SNMP-MIB::memBuffer.0 = INTEGER: 171880 kB
UCD-SNMP-MIB::memCached.0 = INTEGER: 365524 kB
UCD-SNMP-MIB::memSwapError.0 = INTEGER: noError(0)
UCD-SNMP-MIB::memSwapErrorMsg.0 = STRING:

[root@monitoring centreon_plugins]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=192.XX.1XX.9X --snmp-versmp-username=test --authprotocol=MD5 --privprotocol=AES --authpassphrase=XXX --privpassphrase=XXX --warning-usage='80' --critical-usage='90'
WARNING: Ram Total: 3.86 GB **Used (-buffers/cache): 3.15 GB (81.61%)** | 'used'=3381198848B;0:3314565120;0:3728885760;0;4143206400 'buffer'=176070816B;;;0;

**Comment by garnier-quentin** [comment]
It's a linux server ? Which version of net-snmp ?
Because the memCached and memBuffer values seems wrong (not the same value than free -m)

**Comment by johnbritto1** [comment]
@garnier-quentin 

Here is the detail of monitored server.
root@hens:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

root@hen:~# snmpd -v
NET-SNMP version:  5.7.3
Web:               http://www.net-snmp.org/
Email:             net-snmp-coders@lists.sourceforge.net

**Comment by garnier-quentin** [comment]
I'm sorry but i can't help it. free calculate the cache value like that:
```
kb_main_cached = kb_page_cache + kb_slab_reclaimable;
```
But with net-snmp, i don't have 'slab'. Good article: https://www.logicmonitor.com/blog/right-way-to-monitor-linux-memory-again/

**Comment by garnier-quentin** [comment]
There is a patch: https://sourceforge.net/p/net-snmp/patches/1338/
But the patch is not merged

**Comment by garnier-quentin** [comment]
Red-hat has merged the patch it seems: https://bugzilla.redhat.com/show_bug.cgi?id=1250060

**Comment by fabricmate** [comment]
Hello,

I removed the snmpd and used the github merged patch : https://github.com/net-snmp/net-snmp/commit/8d5cdf8aeb6b3521e09b2f2a921ed5061da221e9
to compile and install on the client OS.

But Still, the Centreon gives wrong free memory?
What I am missing here?

Thanks

**Comment by johnbritto1** [comment]
Hello,

I removed the snmpd and used the github merged patch : net-snmp/net-snmp@8d5cdf8
to compile and install on the client OS.

But Still, the Centreon gives wrong free memory?
What I am missing here?

Thanks

**Comment by garnier-quentin** [comment]
It should work. Or the patch is wrong

**Comment by johnbritto1** [comment]
Please excuse me if I am wrong. I couldn't see that the plugin code has the Sreclaimable calculation.  https://github.com/centreon/centreon-plugins/blob/master/snmp_standard/mode/memory.pm

FYI:
Client after compiled net-snmp with Sreclaimable patch.
root@xxx:~# snmpget --version
NET-SNMP version: 5.8

/usr/lib/centreon/plugins/centreon_plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=192.XX.XXXX --snmp-version='3' --snmp-community='' --snmp-port=6600 --snmp-username=hxx --authprotocol=MD5 --privprotocol=AES --authpassphrase=1234 --privpassphrase=asdasda --warning-usage='80' --critical-usage='90'
OK: Ram Total: 3.86 GB Used (-buffers/cache): 2.86 GB (74.06%) Free: 1.00 GB (25.94%), Buffer: 102.58 MB, Cached: 670.41 MB, Shared: 23.62 MB | 'used'=3068575744B;;;0;4143206400 'free'=1074630656B;;;0;4143206400 'used_prct'=74.06%;0:80;0:90;0;100 'buffer'=107565056B;;;0; 'cached'=702971904B;;;0; 'shared'=24772608B;;;0;


snmpwalk from monitoring server:

[root@monitoring ~]# snmpwalk -v3 -l authPriv -u xx -a MD5 -A 1232 -x AES -X habc 192.XX.XX.X:6033 .1.3.6.1.4.1.2021.4
UCD-SNMP-MIB::memIndex.0 = INTEGER: 0
UCD-SNMP-MIB::memErrorName.0 = STRING: swap
UCD-SNMP-MIB::memTotalSwap.0 = INTEGER: 1952764 kB
UCD-SNMP-MIB::memAvailSwap.0 = INTEGER: 1951772 kB
UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 4046100 kB
UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 255264 kB
UCD-SNMP-MIB::memTotalFree.0 = INTEGER: 2207036 kB
UCD-SNMP-MIB::memMinimumSwap.0 = INTEGER: 16000 kB
UCD-SNMP-MIB::memShared.0 = INTEGER: 24192 kB
UCD-SNMP-MIB::memBuffer.0 = INTEGER: 105792 kB
UCD-SNMP-MIB::memCached.0 = INTEGER: 686516 kB
UCD-SNMP-MIB::memSwapError.0 = INTEGER: noError(0)
UCD-SNMP-MIB::memSwapErrorMsg.0 = STRING:

In the client server.

cat /proc/meminfo 
MemTotal:        4046100 kB
MemFree:          255576 kB
MemAvailable:    2682608 kB
Buffers:          105780 kB
Cached:           686516 kB
SwapCached:          100 kB
Active:          1365572 kB
Inactive:         364728 kB
Active(anon):     881968 kB
Inactive(anon):    80228 kB
Active(file):     483604 kB
Inactive(file):   284500 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1952764 kB
SwapFree:        1951772 kB
Dirty:                24 kB
Writeback:             0 kB
AnonPages:        937924 kB
Mapped:            58596 kB
Shmem:             24192 kB
Slab:            1973900 kB
SReclaimable:    1948564 kB
SUnreclaim:        25336 kB
KernelStack:        4368 kB
PageTables:        13924 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3975812 kB
Committed_AS:    1761488 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      102336 kB
DirectMap2M:     4091904 kB
DirectMap1G:     2097152 kB
