### ISSUE TITLE
[cloud::microsoft::office365::management::plugin] - Critical on Service restored

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1504]
Plugins 20190412

Checking the different services on O365 the plugin show's with standard options a critical error if a service is in status "Service restored"
![image](https://user-images.githubusercontent.com/6400595/57464947-edf14000-727d-11e9-90af-ee40f3cd78bd.png)

Microsoft documentation says:
Service restored: We've confirmed that corrective action has resolved the underlying problem and the service has been restored to a healthy state. To find out what went wrong, view the issue details.

https://docs.microsoft.com/en-us/office365/enterprise/view-service-health

**Comment by joschi99** [comment]
Same behaviour for status "Post-incident report published"

**Comment by Sims24** [comment]
Hi @joschi99 

In the meantime you can bypass with :  

`--critical-status='%{status} !~ /Normal|Service Restored/i'`

I update the default threshold. 

Thanks

**Comment by garnier-quentin** [comment]
It's done. Could you test it ?

**Comment by joschi99** [comment]
problem solved, thanks

**Comment by joschi99** [comment]
Hi Sims,
found another status "False positive" which is not described on the Microsoft Document but exists. As I understand the service is also healthy on "False positive":

False positive: 
![image](https://user-images.githubusercontent.com/6400595/58539331-67ce7680-81f7-11e9-9a96-c0d84b52359d.png)
