### ISSUE TITLE
hardware::sensors::hwgste::snmp::plugin - No device Discover 

### ISSUE THREAD

**Issue by cpelichet** [centreon/centreon-plugins#1509]
Hello, 

As discussed with Simon on slack , the OID for our device is not avaiable in your plugin.

Can you add it please ?

Device : [https://www.hw-group.com/device/hwg-ste]

[HWg-STE.mib.txt](https://github.com/centreon/centreon-plugins/files/3181743/HWg-STE.mib.txt)

[HWg-STE.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/3181741/HWg-STE.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
It was a bug (it comes when i have added hwgste2 compatibility) It should be ok now.
