### ISSUE TITLE
network::juniper::ssg mode=hardware --exclude=fans

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#151]
Hello,

The exclude option does work for temperatures but does not work for fans :
perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::juniper::ssg::plugin --mode=hardware --component=all --exclude=fans,temperatures ...
OK: All 2 components [1 modules, 1 psus] are ok. |
Checking temperatures
Skipping temperatures section.
Checking fans
Checking modules
Module 'MGT Board' status is active [instance: 1].
Checking power supplies
Power Supply '1' status is active.

**Comment by garnier-quentin** [comment]
Ok i see. I'll update completely the mode hardware. Thanks

**Comment by ritouret** [comment]
I don't know why but for one equipment, this mode does not work even if it works on 67 others equipments and even if snmpwalk is good for this one :

# perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::juniper::ssg::plugin --mode=hardware --component=all --exclude=fans,temperatures --hostname=host --snmp-version=2c --snmp-community=community --snmp-timeout=45 --snmp-retries=1 --verbose
UNKNOWN: SNMP Table Request : Timeout
Checking temperatures
Skipping temperatures section.
Checking fans


# snmpwalk -m ALL -M /usr/share/snmp/mibs -v2c -c community host .1.3.6.1.4.1.3224.21
NETSCREEN-CHASSIS-MIB::nsPowerId.1 = INTEGER: 1
NETSCREEN-CHASSIS-MIB::nsPowerStatus.1 = INTEGER: 1
NETSCREEN-CHASSIS-MIB::nsPowerDesc.1 = STRING: Power
NETSCREEN-CHASSIS-MIB::nsSlotId.1 = INTEGER: 1
NETSCREEN-CHASSIS-MIB::nsSlotType.1 = STRING: MGT Board
NETSCREEN-CHASSIS-MIB::nsSlotStatus.1 = INTEGER: 1
NETSCREEN-CHASSIS-MIB::nsSlotSN.1 = STRING: 0162042011007199

**Comment by garnier-quentin** [comment]
Could you test Dominique please ?
Option is not --exclude now but --filter (easier)

**Comment by ritouret** [comment]
Thanks Quentin. It works for all equipment now.

Should it indicates when a component is skipped ?

Here the result with --mode=hardware --component='.*' --filter=fans :
OK: All 2 components are ok [1/1 module, 1/1 psus]. |
Checking power supplies
Power supply '1' status is 'active' [instance: 1]
Checking fans
Checking temperatures
Checking modules
Module 'MGT Board' status is 'active' [instance: 1]

**Comment by garnier-quentin** [comment]
It's because your option is wrong. Should be: --filter=fan

**Comment by ritouret** [comment]
Thank you Quentin.

Be carefull in the --help : it's module and not modules.
    --filter
            Exclude some parts (comma seperated list) (Example: --filter=psu
            --filter=modules) Can also exclude specific instance:
            --filter=fan,1

It works with one filter but not with comma separated filter :
--filter=temperature :
OK: All 2 components are ok [1/1 module, 1/1 psus]. |
Checking power supplies
Power supply '1' status is 'active' [instance: 1]
Checking fans
Checking temperatures
Skipping temperature section.
Checking modules
Module 'MGT Board' status is 'active' [instance: 1]

--filter=fan
OK: All 2 components are ok [1/1 module, 1/1 psus]. |
Checking power supplies
Power supply '1' status is 'active' [instance: 1]
Checking fans
Skipping fan section.
Checking temperatures
Checking modules
Module 'MGT Board' status is 'active' [instance: 1]

--filter=fan,temperature
OK: All 2 components are ok [1/1 module, 1/1 psus]. |
Checking power supplies
Power supply '1' status is 'active' [instance: 1]
Checking fans
Checking temperatures
Checking modules
Module 'MGT Board' status is 'active' [instance: 1]

**Comment by garnier-quentin** [comment]
Thanks i have fixed the help. It's like that: --filter=fan --filter=temperature

**Comment by ritouret** [comment]
It's better through this way :
--filter=fan --filter=temperature 
OK: All 2 components are ok [1/1 module, 1/1 psus]. |
Checking power supplies
Power supply '1' status is 'active' [instance: 1]
Checking fans
Skipping fan section.
Checking temperatures
Skipping temperature section.
Checking modules
Module 'MGT Board' status is 'active' [instance: 1]

You should also remove " (comma seperated list) " in the help section for --filter ...

**Comment by LaurentV9** [comment]
Hi Guys,

sorry but I have a strange issue when filter with psu.
I have 4 psu !

When I just filter with --filter=psu
I have:
Checking power supplies
skipping psu section.

but when I try to filter on 1 specific instance to exclude, like --filter=psu,3
it skips ALL psu section:
Checking power supplies
skipping psu section 18.80.111.119.101.114.83.117.112.112.108.121.49.83.116.97.116.117.115 instance.
skipping psu section 18.80.111.119.101.114.83.117.112.112.108.121.50.83.116.97.116.117.115 instance.
skipping psu section 18.80.111.119.101.114.83.117.112.112.108.121.51.83.116.97.116.117.115 instance.
skipping psu section 18.80.111.119.101.114.83.117.112.112.108.121.52.83.116.97.116.117.115 instance.

do you have seen this before?

Laurent
