### ISSUE TITLE
os::windows::snmp::plugin --mode=swap / memory

### ISSUE THREAD

**Issue by stephanemarianne** [centreon/centreon-plugins#1511]
os::windows::snmp::plugin --mode=swap / memory

## New plugins and modes

Need to get the metric unit in 'bytes' instead of '%' or 'B'

for swap and memory measurement

**Comment by garnier-quentin** [comment]
B means bytes. But you want to get bytes written ?

**Comment by stephanemarianne** [comment]
Yes I need bytes to be written  (as an option if possible)

**Comment by garnier-quentin** [comment]
You can use following option:
```
--change-perfdata=used,used,,bytes
```

**Comment by stephanemarianne** [comment]
That's perfect now !
 =>  'used'=1521876992bytes; 

Thank you very much
