### ISSUE TITLE
Graph with total size and free space

### ISSUE THREAD

**Issue by Openema** [centreon/centreon-plugins#1512]
Hello,

I use this command to check my disk :

/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=xxx.xxx.xxx.xxx--snmp-version='2c' --snmp-community='xxxxxx'  --storage='C:' --name --display-transform-src='^(..).*' --display-transform-dst='$1' --warning-usage='10737418240:' --critical-usage='5368709120:' --regexp --free --units="B" --snmp-force-getnext --change-perfdata=free,used,invert()

And the result graph is 
![Capture](https://user-images.githubusercontent.com/50147714/57790609-643ce900-773b-11e9-96ae-91e96e517106.PNG)

How it is possible to delete the free value and add the total size value of the disk ?

Thanks

**Comment by garnier-quentin** [comment]
You need to delete the free curve. Go to administration menu. There is a page to manage perfdata.
For the total:
```
--explode-perfdata-max='used,total'
```

**Comment by Openema** [comment]
Thank you, it works
