### ISSUE TITLE
Mode inodes, partition missing

### ISSUE THREAD

**Issue by SebastienLegrand** [centreon/centreon-plugins#1517]
I try to use the plugin with the mode inodes to retrieve all partitions.

It works but some partitions are missing, I try to use --diskpath and the result is 
UNKNOWN: No entry found.

But when I use the mode storage for example the partition is not missing.

The partition missing is the nfs mount

df -hi | grep public                                                                                                                             
22.22.22.22:/vol/public   21M  17M  4.3M  80% /var/www/example/vas/public

**Comment by garnier-quentin** [comment]
Could you do a snmpwalk on oid .1.3.6.1.4.1.2021.9.1.2 ? If you don t have the partition in the result, the mode cannot.
Can we get inodes information on nfs client side ? Ç

**Comment by SebastienLegrand** [comment]
Ok, I run the command, and the partition doesn't come up.
I don't know why it's comming up for mode storage and not inodes.

Can we add manually the partition ?
1- To the plugin
2- Or, can we edit the oid to add manually the partition ?

**Comment by garnier-quentin** [comment]
I think you cant. You can use the local mode inodes (if the df commands shows inode usage with df command line).

**Comment by SebastienLegrand** [comment]
Thank you for your quick response.
Great plugin.

**Comment by garnier-quentin** [comment]
Thanks! You're welcome
