### ISSUE TITLE
hardware::server::hp::ilo::xmlapi::plugin

### ISSUE THREAD

**Issue by c0c00n** [centreon/centreon-plugins#1519]
Hi 
running in to the same problem as reportet in #10

`./centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname='IP' --username='' --password='' --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --verbose --debug`

`UNKNOWN: Cannot get data: HTTP::Response=HASH(0x23f8768)->status_line`

curl -k https://ILOIP/xmldata?item=All

```
<SPN>ProLiant DL380 Gen10</SPN>
<PN>Integrated Lights-Out 5 (iLO 5)</PN>
<FWRI>1.15</FWRI>
<HWRI>ASIC: 21</HWRI>
```

**Comment by garnier-quentin** [comment]
Could you try with following option ? --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE'

**Comment by c0c00n** [comment]
`./centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname='IP' --username='' --password='' -ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE' --verbose --debug`

UNKNOWN: Cannot get data: HTTP::Response=HASH(0x1a406d0)->status_line

**Comment by c0c00n** [comment]
`./centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname='IP' --username='' --password='' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE' --verbose --debug`
```
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 possibly with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
```
```
  at /tmp/centreon-plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 116.
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x16491f8)->status_line
```
***********
Tryed variation of
`--ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'`
at /tmp/centreon-plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 116.
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x23b41f8)->status_line

`--ssl-opt='SSL_verify_mode=>SSL_VERIFY_NONE'`
at /tmp/centreon-plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 116.
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x1e361a8)->status_line

`--ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"`
  at /tmp/centreon-plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 116.
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x20041f8)->status_line

`--ssl-opt="SSL_verify_mode=>SSL_VERIFY_NONE"`
  at /tmp/centreon-plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 116.
UNKNOWN: Cannot get data: HTTP::Response=HASH(0x25051a8)->status_line

**Comment by garnier-quentin** [comment]
Could you test with curl http backend ?

**Comment by garnier-quentin** [comment]
I take a look and it seems the api changed with ilo 5. Now it s redfish api. So that plugin won t work.

**Comment by c0c00n** [comment]
You are right [https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/](url), any plans to add it?

**Comment by garnier-quentin** [comment]
I need to look the api in details and get curl results (if you can provide good curl, it will save time). But i can't give you a release date. There are many plugins/mode waiting (as you can see).

**Comment by garnier-quentin** [comment]
I have done a first release. need to test it
