### ISSUE TITLE
[hardware/telephony/avaya/mediagateway/snmp] mode hardware

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1522]
Hello,

The decoding bytes have been inverted.

Here what we have via snmpget :
MediaGateway M : SNMPv2-SMI::enterprises.6889.2.9.1.1.10.12.0 = Hex-STRING: 00 00 80
MediaGateway P : SNMPv2-SMI::enterprises.6889.2.9.1.1.10.12.0 = Hex-STRING: 80 00 80

Here what we have through centreon_plugins :
MediaGateway M : CRITICAL: Alarm 'at least two fans have been operating at less than 90% of their nominal speed for 5 minutes or more' status is 'enabled'
MediaGateway P : CRITICAL: Alarm 'at least two fans have been operating at less than 90% of their nominal speed for 5 minutes or more' status is 'enabled' - Alarm 'Clock synchronization signal is lost' status is 'enabled'

The reality is the following :
Fan Alarm for both MediaGateway
Clock alarm only for MediaGateway M but not for MediaGateway P

Here the documented MIB :
Cajun numbering continues across octets, so that octet 1 bit 0 is called bit 8 in the Cajun scheme.  That number is also shown below, with the octet value for each single bit set.
Octet 0 high-order 4 bits show fan status.
Octet 0 low-order 4 bits show temperature status.
Octet 1 shows power supply status.
Octet 2 shows other alarms.
Cajun  Octet Octet bit#   /bit# value Meaning -----  ----- ----- ------- 0     
 0/0   0x80 Multiple fan warning: at least two fans have been operating at less than 90% of their nominal speed for 5 minutes or more.  This may be an early warning of overheating. 1    
 0/1   0x40 PSU fan brief failure warning: the power supply fan has been operating at less than 90% of its nominal speed for 10 minutes or more, but less than 15 minutes.  This may be an early warning of overheating. 2     
 0/2   0x20 PSU fan prolonged failure warning: the power supply fan has been operating at less than 90% of its nominal speed for 15 minutes or more.  This may be an early warning of overheating. 3     
 0/3        Unused. 4     
 0/4   0x08 Temperature warning: cmgCpuTemp has exceeded its warning threshold. 5      
 0/5   0x04 Temperature warning: cmgDspTemp has exceeded its warning threshold. 6     
 0/6 Unused. 7     
 0/7   Power On Status Test failure -NCE, QUICC test failures on power up 8     
 1/0   0x80 The +5.1 v power supply to the MG processor is out of range. 9     
 1/1   0x40 The -48 v power supply to the media modules is out of range. 10     
 1/2   0x20 The +3.3 v power supply to the VoIP complexes is out of range. 11     
 1/3   0x10 The +1.58 v power supply to the DSP units is out of range. 12    
 1/4   0x08 The +2.5 v power supply to the 8260 processor is out of range. 13     
 1/5   0x04 The -48 v auxiliary power supply to the endpoints is out of range. 14     
 1/6   0x02 The +12 v power supply to the fans is out of range. 15     
 1/7  Unused. 16    
 2/0   0x80 Clock synchronization signal is lost. 17    
 2/1   0x40 Clock synchronization signal warning. Only one clock syncronization signal source remains. 18     
 2/2   0x20   Clock synchronization signal excessive switching. 19     
 2/3   0x10   TDM Test Expansion Box 1 Failure 20    
 2/4   0x08   TDM Test Expansion Box 2 Failure 21    
 2/5   0x04   PoE Power Supply Base Box Failure 22    
 2/6   0x02   PoE Power Supply Expansion Box 1 Failure 23    
 2/7   0x01   PoE Power Supply Expansion Box 2 Failure

Thanks

**Comment by ritouret** [comment]
Sorry, it's my bad.

**Comment by ritouret** [comment]
Ok, they've been inverted :

The reality is the following :
Fan Alarm only for MediaGateway P but not for MediaGateway M
Clock alarm for both MediaGateway

**Comment by ritouret** [comment]
Octet 2 is on left, octet 0 is on right.

**Comment by garnier-quentin** [comment]
I have changed the order. Could you test it ?

**Comment by ritouret** [comment]
Hello,

Here what it answer now :
MediaGateway P : CRITICAL: Alarm 'PoE Power Supply Expansion Box 2 Failure' status is 'enabled' - Alarm 'Power On Status Test failure -NCE, QUICC test failures on power up' status is 'enabled'
MediaGateway M : CRITICAL: Alarm 'PoE Power Supply Expansion Box 2 Failure' status is 'enabled'

It should be :
MediaGateway P : CRITICAL: Alarm 'at least two fans have been operating at less than 90% of their nominal speed for 5 minutes or more' status is 'enabled' - Alarm 'Clock synchronization signal is lost' status is 'enabled'
MediaGateway M : CRITICAL: Alarm 'Clock synchronization signal is lost' status is 'enabled'

**Comment by garnier-quentin** [comment]
It should be ok now. Could you test it ?

**Comment by ritouret** [comment]
Yes, Thank you Quentin.
