### ISSUE TITLE
[apps::sccm::local::plugin] mode site-status

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1525]
Hello,

In the help i understand that we can not specify the path for ConfigurationManager.psd1.
Did i misunderstood the help ? Is it possible to specify this ?

Here the answer for now :
UNKNOWN: Command error: System.IO.FileNotFoundException: The specified module 'C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin\ConfigurationManager.psd1' was not loaded because no valid module file was found in any module directory.

ConfigurationManager.psd1 has been installed in another directory.

Thanks

**Comment by garnier-quentin** [comment]
It seems not. Where the file is located ?

**Comment by ritouret** [comment]
D:\Program Files\Microsoft Configuration Manager\AdminConsole\bin

**Comment by cgagnaire** [comment]
Hi @ritouret,
Can you please provide us the values for the "program" paths in the environment variables (ie _set Program_ command) ?
Thank you!

**Comment by ritouret** [comment]
Hi Colin,

Here is the result for set Program Command :

ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files

**Comment by cgagnaire** [comment]
Fixed
