### ISSUE TITLE
[database::mysql::plugin] --mode=queries // bad command

### ISSUE THREAD

**Issue by Anasme** [centreon/centreon-plugins#1526]
Hello,

Seem to be an error in the command from the pack mysql/mariadb for App-DB-MySQL-Queries: 

root@*** plugins]# ./centreon_mysql.pl --plugin=database::mysql::plugin --host=ip --username='private' --password='pwd' --port='3306' --mode=queries --warning-total='20' --critical-total='30'
**Unknown option: warning-total at ./centreon_mysql.pl line 398.**

correction:
root@*** plugins]# ./centreon_mysql.pl --plugin=database::mysql::plugin --host=ip --username='private' --password='pwd' --port='3306' --mode=queries **--warning**='20' **--critical**='30'
OK: Total requests = 0 | 'Com_delete_requests'=0;;;0; 'Com_insert_requests'=0;;;0; 'Com_select_requests'=0;;;0; 'Com_truncate_requests'=0;;;0; 'Com_update_requests'=0;;;0; 'total_requests'=0;0:20;0:30;0;

I can't edit the command it's locked. Can you update this please :) ?

Command line in centreon:

` $CENTREONPLUGINS$/centreon_mysql.pl --plugin=database::mysql::plugin --host=$HOSTADDRESS$ --username='$_HOSTMYSQLUSERNAME$' --password='$_HOSTMYSQLPASSWORD$' --port='$_HOSTMYSQLPORT$' --mode=queries --warning-total='$_SERVICEWARNING$' --critical-total='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$`

Thanks for your help

**Comment by Anasme** [comment]
forgot the version of the plugin:
MySQL/MariaDB: 3.1.2

**Comment by garnier-quentin** [comment]
Please update your centreon-pack rpm on your central server, update the pack configuration (in pp manager page) and push the configuration.
