### ISSUE TITLE
Netscaler ha-state mode not correct

### ISSUE THREAD

**Issue by guipe** [centreon/centreon-plugins#1527]
Hi,

in file network/citrix/netscaler/snmp/mode/hastate.pm, it seems map peerstate status is not correct:

my %map_peerstate_status = (
    0 => 'standalone',
    1 => 'primary',
    2 => 'secondary',
    3 => 'unknown',
);

The correct one will be:

my %map_peerstate_status = (
    0 => 'standalone',
    1 => 'secondary',
    2 => 'primary',
    3 => 'unknown',
);

Secondary and primary is inverted.

**Comment by garnier-quentin** [comment]
Could you provide the mib file ?

**Comment by guipe** [comment]
Here, you can find mib description:
https://developer-docs.citrix.com/projects/netscaler-snmp-oid-reference/en/12.0/

I didn't find the different status explicitly.

**Comment by garnier-quentin** [comment]
When you look the mib file (for example): https://github.com/CumulusNetworks/cldemo-archive/blob/master/cldemo-wbench-librenms-base/debian/var/www/librenms/mibs/NS-MIB

For 'HAMode', '1' = primary. There is a "bug" in mib file ? Could you ask to Citrix ?

**Comment by jben94** [comment]
Hi @garnier-quentin,

I am in the same situation.
This oid gives us the status of the Peer and not the current equipment.

```
# snmpwalk -c **** -v 2c ****.17 1.3.6.1.4.1.5951.4.1.1.23
SNMPv2-SMI::enterprises.5951.4.1.1.23.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5951.4.1.1.23.2.0 = IpAddress: ****.18
SNMPv2-SMI::enterprises.5951.4.1.1.23.3.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5951.4.1.1.23.4.0 = Counter64: 1
SNMPv2-SMI::enterprises.5951.4.1.1.23.5.0 = Timeticks: (319822500) 37 days, 0:23:45.00
SNMPv2-SMI::enterprises.5951.4.1.1.23.6.0 = Counter64: 1
SNMPv2-SMI::enterprises.5951.4.1.1.23.7.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.8.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.9.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.10.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.11.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.12.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.14.0 = ""
SNMPv2-SMI::enterprises.5951.4.1.1.23.15.0 = STRING: "self node ****.17: (INACTIVE, UP), remote node ****.18: (ACTIVE, UP)"
SNMPv2-SMI::enterprises.5951.4.1.1.23.17.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.18.0 = Counter32: 18223
SNMPv2-SMI::enterprises.5951.4.1.1.23.19.0 = Counter32: 18221
SNMPv2-SMI::enterprises.5951.4.1.1.23.20.0 = Counter64: 0
SNMPv2-SMI::enterprises.5951.4.1.1.23.21.0 = Counter64: 15991129
SNMPv2-SMI::enterprises.5951.4.1.1.23.22.0 = Counter64: 15990619
SNMPv2-SMI::enterprises.5951.4.1.1.23.23.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5951.4.1.1.23.24.0 = INTEGER: 3
SNMPv2-SMI::enterprises.5951.4.1.1.23.25.0 = INTEGER: 1
SNMPv2-SMI::enterprises.5951.4.1.1.23.26.0 = Hex-STRING: ****
```

To know the status of the current equipment, it should be used here: 1.3.6.1.4.1.5951.4.1.1.6

```
# snmpwalk -c **** -v 2c ****.17 1.3.6.1.4.1.5951.4.1.1.6
SNMPv2-SMI::enterprises.5951.4.1.1.6.0 = INTEGER: 2
```

> sysHighAvailabilityMode  OBJECT-TYPE
> 	SYNTAX  HAMode
> 	MAX-ACCESS  read-only
> 	STATUS  current
> 	DESCRIPTION
> 		"This shows whether NetScaler is in standalone mode or whether it is primary or secondary in case of failover mode."
> 	::= { nsSysGroup 6 }

Regards

**Comment by garnier-quentin** [comment]
I could add that OID yes. But it's not the same problem.

**Comment by jben94** [comment]
Hi,

For me yes, because @guipe asked to reverse the status ("primary" / "secondary")

**Comment by garnier-quentin** [comment]
I have done a patch. Now you can use %{ha_mode}
