### ISSUE TITLE
[cloud::prometheus::exporters::nodeexporter::plugin] --mode=cpu-detailed: thresholds are wrong

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1531]
Centreon Plugins 20190412

If you show the help
`./cloud-prometheus-exporters-nodeexporter.pl --plugin=cloud::prometheus::exporters::nodeexporter::plugin --mode=cpu-detailed --help`
you can see
```
    --warning-*
            Threshold warning. Can be: 'node-idle', 'node-wait', 'node-irq',
            'node-nice', 'node-softirq', 'node-steal', 'node-system',
            'node-user', 'cpu-idle', 'cpu-wait', 'cpu-irq', 'cpu-nice',
            'cpu-softirq', 'cpu-steal', 'cpu-system', 'cpu-user'.

    --critical-*
            Threshold critical. Can be: 'node-idle', 'node-wait',
            'node-irq', 'node-nice', 'node-softirq', 'node-steal',
            'node-system', 'node-user', 'cpu-idle', 'cpu-wait', 'cpu-irq',
            'cpu-nice', 'cpu-softirq', 'cpu-steal', 'cpu-system',
            'cpu-user'.
```
But there are some thresholds described like **node-irq** that are not working, because they are not defined under this name.

**Comment by garnier-quentin** [comment]
Thanks for the feedback. We are going to fix it next week

**Comment by cgagnaire** [comment]
Fixed by https://github.com/centreon/centreon-plugins/commit/4714685f558edb0782fa29269539bc5c6fdbb7aa
