### ISSUE TITLE
Error some command for Buffalo 

### ISSUE THREAD

**Issue by Dream91300** [centreon/centreon-plugins#1533]
Hi,

I have a terastation TS3410R and some mode don't work. I have a return "UNKNOWN: SNMP Table Request : Timeout". 

- array-usage : Error
- cpu-detailed : Ok
- hardware : Error
- interfaces : Ok
- list-interfaces : Ok
- load : Ok
- memory : Ok

Could you explain me how to test hardware, array and disk?

Thank you

**Comment by garnier-quentin** [comment]
Could you try with option --snmp-autoreduce ?

**Comment by Dream91300** [comment]
Same Error. I don't know if it's not an error of this buffalo. SNMP request make load CPU. It's not normal, this buffalo is in business category.

If you have any response...

**Comment by garnier-quentin** [comment]
That's weird. Could you provide a full snmpwalk of your buffalo ?
snmpwalk -ObentU -v 2c -c public IP .1 > buffalo.snmpwalk

**Comment by Dream91300** [comment]
Yes you can regards file attached. 

I have open an issue with support. Not normal that CPU load. 

[buffalo.zip](https://github.com/centreon/centreon-plugins/files/3252210/buffalo.zip)

**Comment by garnier-quentin** [comment]
your snmpwalk is incomplete. Could you walk following branch directly ?
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.5227.27 > buffalo_entreprise.snmpwalk

It seems like a buffalo "bug".

**Comment by Dream91300** [comment]
I can't collect all branch. I have a timeout just after firmware version. For me, Buffalo does'nt have business product. And this is confirmed.

I follow my case with Buffalo Support and I will keep you inform. 
Thank's

**Comment by garnier-quentin** [comment]
Thank you. You can post it if you have a reponse from your buffalo support

**Comment by Dream91300** [comment]
Hi,

Buffalo support not support 😄 SNMP. They support their software...

I have search why I have this return. For disk its Ok. For psu I have the same error, but I have read your script for psu and found psu OID (.1.3.6.1.4.1.5227.27.1.8.1.2). There seems to be a problem with this OID because snmpwalk return " No Such Object available on this agent at this OID". 
I contine my search

**Comment by garnier-quentin** [comment]
Nice :) Maybe there is a rest api ? Something else (supported :)

**Comment by Dream91300** [comment]
Hi,

Plugins for array-usage, is on error. I have tested without and with "--snmp-autoreduce, it's the same error :
`[root@SRV-CENTREON centreon-plugins]# ./centreon_plugins.pl --hostname=192.168.8.9 --snmp-community=public --snmp-version=2c --plugin=storage::buffalo::terastation::snmp::plugin --mode=array-usage --snmp-autoreduce
UNKNOWN: SNMP Table Request : Timeout`

But if I checked separately the 3 OID wich are used and It's Ok. 

ArrayCapacity :
`[root@SRV-CENTREON centreon-plugins]#  snmpwalk -v 2c -c public 192.168.8.9 .1.3.6.1.4.1.5227.27.1.3.1.3.1
SNMPv2-SMI::enterprises.5227.27.1.3.1.3.1 = INTEGER: 11896`

ArrayUsed : 
`[root@SRV-CENTREON centreon-plugins]#  snmpwalk -v 2c -c public 192.168.8.9 .1.3.6.1.4.1.5227.27.1.3.1.4.1
SNMPv2-SMI::enterprises.5227.27.1.3.1.4.1 = INTEGER: 52`

ArrayEntyr : 
`[root@SRV-CENTREON centreon-plugins]# snmpwalk -v 2c -c public 192.168.8.9 .1.3.6.1.4.1.5227.27.1.3.1
SNMPv2-SMI::enterprises.5227.27.1.3.1.2.1 = INTEGER: 4
SNMPv2-SMI::enterprises.5227.27.1.3.1.2.2 = INTEGER: 1
SNMPv2-SMI::enterprises.5227.27.1.3.1.3.1 = INTEGER: 11896
SNMPv2-SMI::enterprises.5227.27.1.3.1.3.2 = INTEGER: -1
SNMPv2-SMI::enterprises.5227.27.1.3.1.4.1 = INTEGER: 52
SNMPv2-SMI::enterprises.5227.27.1.3.1.4.2 = INTEGER: -1
SNMPv2-SMI::enterprises.5227.27.1.3.1.5.1 = INTEGER: 11079
SNMPv2-SMI::enterprises.5227.27.1.3.1.5.2 = INTEGER: -1
SNMPv2-SMI::enterprises.5227.27.1.3.1.6.1 = Gauge32: 3886022656
SNMPv2-SMI::enterprises.5227.27.1.3.1.6.2 = Gauge32: 0
SNMPv2-SMI::enterprises.5227.27.1.3.1.7.1 = Gauge32: 2769
SNMPv2-SMI::enterprises.5227.27.1.3.1.7.2 = Gauge32: 0
SNMPv2-SMI::enterprises.5227.27.1.3.1.8.1 = INTEGER: 5783
SNMPv2-SMI::enterprises.5227.27.1.3.1.8.2 = INTEGER: -1
SNMPv2-SMI::enterprises.5227.27.1.3.1.9.1 = Gauge32: 3602542592
SNMPv2-SMI::enterprises.5227.27.1.3.1.9.2 = Gauge32: 0
SNMPv2-SMI::enterprises.5227.27.1.3.1.10.1 = Gauge32: 1445
SNMPv2-SMI::enterprises.5227.27.1.3.1.10.2 = Gauge32: 0`

I don't know perl language. Can you help me ? 
Thank you

**Comment by garnier-quentin** [comment]
I have done a fix. Try the last version. If it's still not working, try following option: --snmp-force-getnext

**Comment by Dream91300** [comment]
Thank you that's good with --snmp-force-getnext. 

Can you explain briefly where was the problem?

**Comment by garnier-quentin** [comment]
The problem is that the buffalo snmp agent is shitty :) 
In SNMP v2, i use bulk request (by default). And it doesn't like bulk (it seems).

**Comment by Dream91300** [comment]
> 
buffalo snmp agent is shitty :)
> 
Not even surprised. Buffalo is not for use in business. 

Next project : change buffalo NAS to a Synology. 

Thank you for your time.
