### ISSUE TITLE
network::cisco::standard::snmp::plugin --mode=cpu --critical threshold error/bug after update

### ISSUE THREAD

**Issue by troja89** [centreon/centreon-plugins#1535]
I updated plugins in my poller to the latest version and after the update the plugin  network::cisco::standard::snmp::plugin --mode=cpu is giving me an error "Unknown option: critical at /usr/lib/nagios/plugins//centreon/plugins/alternative/Getopt.pm line 67."
But when I look at the /centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --mode=cpu --help it says "Mode:
    Check cpu usage (CISCO-PROCESS-MIB and CISCO-SYSTEM-EXT-MIB).

    --warning
            Threshold warning in percent (5s,1min,5min). Used 5min threshold
            when you have only 'cpu' metric.

    --critical
            Threshold critical in percent (5s,1min,5min). Used 5min
            threshold when you have only 'cpu' metric.
"

The command i'm using is: /usr/lib/nagios/plugins/centreon_plugins.pl
	--plugin network::cisco::standard::snmp::plugin
	--mode=cpu
	--hostname=X.X.X.X
	--snmp-community=XXXXX
	--snmp-version=2c
	--critical=,90,90
	--warning=,85,85
	--verbose

I also tried using "--critical-usage" but that also returned an error.

**Comment by garnier-quentin** [comment]
Sorry i have fixed the help. You need following options:
--warning-core-1m=85 --critical-core-1m=90  --warning-core-5m=85 --critical-core-5m=90
