### ISSUE TITLE
[Question] network::cisco::standard::snmp::plugin --mode configuration

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#1538]
Hi all,
I want to use this plugin to check, if the config of our cisco devices is saved or not. on our switches and routers it works. But on our ASAs the Running Last Changed is always 1s greater than Running Last Saved. Must be a ASA "feature". Is it possible to set the tresholds to a "greater than x minutes/seconds" ? 

Cheers,
Marcus

**Comment by garnier-quentin** [comment]
Could you provide the command ?

**Comment by MarcusCaepio** [comment]
sure
```

./centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --mode configuration --hostname x.x.x.x --snmp-version 3 --snmp-username xxx --authpassphrase xxx --authprotocol md5 --critical-status '%{running_last_changed} > %{running_last_saved}'
```
Result:
```
CRITICAL: Configuration Running Last Changed: 3M 30m, Running Last Saved: 3M 29m 59s, Startup Last Changed: 3M 23m 15s | 'running_last_changed'=7891029s;;;0; 'running_last_saved'=7891028s;;;0; 'startup_last_changed'=7890624s;;;0;

```
As you can see, even after a save, the Running last changed is always 1 second after Running last Saved.

**Comment by garnier-quentin** [comment]
You can use following threshold:
```
--critical-status '%{running_last_changed} > (%{running_last_saved} + 300)'
```

**Comment by MarcusCaepio** [comment]
This works, thanks a lot!
