### ISSUE TITLE
HOST SNMPv3 Macros

### ISSUE THREAD

**Issue by nikitito** [centreon/centreon-plugins#1540]
Hi,
Is it possible to add HOST Macros for snmpv3, such as --privprotocol --authprotocol --privpassphrase --authpassphrase, and --snmp-username instead of --snmp-community...
The thing at this time is that you need to modify all your OS_Linux-SNMP commands to add that...

Have a nice day ;)

PS : I just closed a topic, because I created a pull request instead of creating a new issue, sorry

https://github.com/centreon/centreon-plugins/pull/1539

**Comment by garnier-quentin** [comment]
It's not a plugin enhancement. It's a centreon-web enhancement. You can use SNMPEXTRAOPTIONS macro in your host configuration to set snmp v3 options.
