### ISSUE TITLE
Snapmirrorlag not working

### ISSUE THREAD

**Issue by bernah4** [centreon/centreon-plugins#1541]
Hello,

I am using two netapp storage in two diffrent location and i want to check if the snapmiror replication is working well; when i run the snapmirorlag mode while the replication is enable i get: UNKNOWN: Snapmirror is not turned on.

I tried different options but some are not working (ex: Unknown option: name at centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67)

I thought it was MIB's problem but could not find anything that way.

Best Regards

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk of your equipment please ?
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.789 > netapp.snmpwalk

**Comment by bernah4** [comment]
hi,
i get snmpwalk: Unknown host (.1.3.6.1.4.1.789)

**Comment by garnier-quentin** [comment]
You need to set the 'IP' address of your netapp

**Comment by bernah4** [comment]
Sorry i forgot to translate in snmp v3 i disable oldest version ! The cmd is still runing ...

**Comment by garnier-quentin** [comment]
I have looked in the snmpwalk and i find nothing about snapmirror (.1.3.6.1.4.1.789.1.9). 
That's why the plugin returns that message.
