### ISSUE TITLE
[storage::hp::storeonce::ssh::plugin] Cannot load module --plugin

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1542]
Hello guys,

I have a problem with the plugin for HP StoreOnce storage systems. I want to use centreon_hp_storeonce_restapi.pl but when I try to load the plugin I receive following error:

```
/usr/lib/centreon/plugins/centreon_hp_storeonce_restapi.pl --plugin=storage::hp::storeonce::ssh::plugin --help
UNKNOWN: Cannot load module --plugin.
Can't locate storage/hp/storeonce/ssh/plugin.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::21822344=HASH(0x14cfb88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/centreon_hp_storeonce_restapi.pl line 1523.
```
What I'm doing wrong?

Best regards, Michael

**Comment by garnier-quentin** [comment]
It's not a plugin issue. It's an issue with plugin-packs product. But i will fix ;)

**Comment by MikeW83** [comment]
But with the RestAPI there is no possibility to check the hardware. Within the SSH plugin you can choose the mode to check components. Or is it the same?

**Comment by garnier-quentin** [comment]
Yes indeed. For the hardware, you need to use the ssh.
Process:
```
# yum install centreon-plugin-Hardware-Storage-Hp-Storeonce-Ssh
# /usr/lib/centreon/plugins/centreon_hp_storeonce_ssh.pl --plugin
```

**Comment by MikeW83** [comment]
Ouch, my mistake... I have corrected the command line but not the used plugin. Sorry, my fail. :-(
