### ISSUE TITLE
SUN-ILOM monitoring

### ISSUE THREAD

**Issue by jerebernard** [centreon/centreon-plugins#1543]
Hello all,

I'm trying to monitor SUN-ILOM (version 4.0.2.20.b) but I got an error :
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::sun::mgmt_cards::plugin --hostname=x.x.x.x --username=admin--password=password--mode=show-faulty

Use of uninitialized value $long_msg in substitution (s///) at /usr/lib/nagios/plugins/centreon-plugins/hardware/server/sun/mgmt_cards/mode/showfaulty.pm line 104.
UNKNOWN: Command 'show -o table -level all /SP/faultmgmt' problems (see additional info). 

Thanks for your help.|

**Comment by garnier-quentin** [comment]
Could you test the command directly ?
```
echo 'show -o table -level all /SP/faultmgmt' | plink -T -l 'username' -batch -pw 'password' x.x.x.x 2>&1
```

**Comment by jerebernard** [comment]
I got this : 
The server's host key is not cached. You have no guarantee
that the server is the computer you think it is.
The server's rsa2 key fingerprint is:
ssh-rsa 1024 fe:ee:0b:2b:ef:36:98:c3:5d:95:90:13:e7:fc:11:e7
Connection abandoned.

**Comment by garnier-quentin** [comment]
You need to validate the key. And after, you can launch the command

**Comment by jerebernard** [comment]
Thanks it works.
I had to do this if someone got the same issue : 
plink -l username -ssh x.x.x.x

**Comment by garnier-quentin** [comment]
thanks for the feedback
