### ISSUE TITLE
[database::mongodb::plugin] - parameters wrong

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1546]
I have tested the new MongoDB plugin. I have seen that on different modes we have wrong parameter descriptions.
Example:
```
 /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=database::mongodb::plugin --hostname=*** --hostname=***--port=27017 --username=***--password='***' --mode=connection-time  --help

Mode:
    Check database connection time.

    --warning-database-connection-time-milliseconds
            Threshold warning in milliseconds.

    --critical-database-connection-time-milliseconds>
            Threshold critical in milliseconds.

```

When we launch the command we have this error:
```
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=database::mongodb::plugin --hostname=*** --hostname=*** --port=27017 --username=*** --password=*** --mode=connection-time --warning-database-connection-time-milliseconds=200 --critical-database-connection-time-milliseconds=500
Unknown option: warning-database-connection-time-milliseconds at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.
```

**Comment by joschi99** [comment]
![image](https://user-images.githubusercontent.com/6400595/59101571-ac5dbe80-8929-11e9-9450-e4e3f910e31f.png)

**Comment by cgagnaire** [comment]
Hi @joschi99,
I just adjusted some counters, but, except for replication status mode, all others work.
You must now modify the ones I touched.

**Comment by joschi99** [comment]
Very strange, I don't know what I'm doing wrong, but I have still same problem with arguments list:

- downloaded master from github (today)
```
./centreon_plugins.pl --plugin=database::mongodb::plugin --hostname=10.10.10.10 --port=27017 --username=user --password=password --mode=connection-time --warning-database-connection-time-milliseconds=200 --critical-database-connection-time-milliseconds=500
Unknown option: warning-database-connection-time-milliseconds at /tmp/test/centreon-plugins-master/centreon/plugins/alternative/Getopt.pm line 67.
```

**Comment by cgagnaire** [comment]
Hi,
This one is part of the ones I did change, try --warning-connection-time-milliseconds and --critical-connection-time-milliseconds

**Comment by joschi99** [comment]
Excuse me, my fault. You are completely right.

Thanks

**Comment by joschi99** [comment]
Found another issue with mode=replication-status:
`Unknown option: warning-instance-lag-seconds at ./database-mongodb.pl line 141`
`Unknown option: critical-instance-lag-seconds at ./database-mongodb.pl line 141`

**Comment by cgagnaire** [comment]
No worries!
Just fixed the helper https://github.com/centreon/centreon-plugins/commit/4efce54a3adc5e1f86cd5125af241877b8c3a491
You can also use --warning-replication-lag (shorter version)/

**Comment by joschi99** [comment]
great, works fine

**Comment by kylonkzn** [comment]
hello,
can you please help with mode=connection-time?
I use this command:
centreon_plugins.pl --plugin=database::mongodb::plugin --hostname=*** --username='***' --password='***' --mode=connection-time --warning-connection-time-milliseconds=200 --critical-connection-time-milliseconds=500
---
  and get an "OK" status, but the warning threshold is exceeded.
----
OK: Connection established in 231 ms | 'connection.time.milliseconds'=231ms;;;0;

**Comment by Sims24** [comment]
Hi @kylonkzn, 

That would help if you open a separate issue. This one is closed. 

Could you try with the following options and give us a feedback: 

--warning-connection-time & --warning-connection-time

Regards
