### ISSUE TITLE
Plugin Cisco Standard temperature

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#1548]
Problème de prise en compte de seuil dans le mode environnement pour les sensors :

--warning='sensor,.*,0:30' =>

WARNING: Sensor 'Switch 1 - WS-C3650-24TD - Temp Inlet Sensor 0/1011' is 23 C - Sensor 'Switch 1 - WS-C3650-24TD - Temp Outlet Sensor 1/1012' is 30 C - Sensor 'Switch 1 - WS-C3650-24TD - Temp HotSpot Sensor 2/1013' is 48 C

 
'sensor.celsius_Switch 1 - WS-C3650-24TD - Temp Inlet Sensor 0'=23C;32:40;-9:55;;
'sensor.celsius_Switch 1 - WS-C3650-24TD - Temp Outlet Sensor 1'=30C;106:104;-9:124;;
'sensor.celsius_Switch 1 - WS-C3650-24TD - Temp HotSpot Sensor 2'=48C;106:104;-9:124;;

**Comment by garnier-quentin** [comment]
Could you test ?
```
--warning='sensor.celsius,.*,0:30' 
```

**Comment by Jordan91** [comment]
Le problème est toujours présent.
