### ISSUE TITLE
network::huawei::snmp::plugin Temperature and Fan Status

### ISSUE THREAD

**Issue by landregen** [centreon/centreon-plugins#1550]
Hi,
is-it possible to add temperature and fan status for Huawei network SNMP ?

SNMPv2-SMI::enterprises.2011.5.25.31.1.1.10.1.7.0.0 = INTEGER: 1
Fan1 1.3.6.1.4.1.2011.5.25.31.1.1.10.1.7.0.0
Fan2 1.3.6.1.4.1.2011.5.25.31.1.1.10.1.7.0.1
Fan3 1.3.6.1.4.1.2011.5.25.31.1.1.10.1.7.0.2

SNMPv2-SMI::enterprises.2011.5.25.31.1.1.1.1.11.67108873 = INTEGER: 48
Temperature 1.3.6.1.4.1.2011.5.25.31.1.1.1.1.11.67108873

Thx

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk please and mib files ?
```
snmpwalk -ObentU -c public -v 2c IP .1.3.6.1.4.1.2011 > huawei.snmpwalk
```

**Comment by landregen** [comment]
[huawei.zip](https://github.com/centreon/centreon-plugins/files/3290496/huawei.zip)

**Comment by garnier-quentin** [comment]
Thanks. I also need following branch:
```
snmpwalk -ObentU -c public -v 2c IP .1.3.6.1.2.1.47 > huawei_entity.snmpwalk
```

**Comment by landregen** [comment]
[huawei_entity.zip](https://github.com/centreon/centreon-plugins/files/3295702/huawei_entity.zip)

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test it ?

**Comment by landregen** [comment]
It's OK. thx a lot.

**Comment by garnier-quentin** [comment]
Thanks for the feedback
