### ISSUE TITLE
McAfee Antivirus

### ISSUE THREAD

**Issue by JulienC99** [centreon/centreon-plugins#1551]
Hello,

I'm trying to use the McAfee plugin.

I would to use versions and detection mode.

I have created this commands for detection:

`perl centreon_plugins.pl --plugin=app::antivirus::mcafee::webgateway::snmp::plugin --mode=detections --host="XXXXXX" --snmp-version=2c --snmp-community=xxxxxxx --warning-malware-detected==? --critical-malware-detected==?`

I have some questions:

1) Am I using the right syntax?

2) What is the information i need to place in the Warning and Critical? I have try few information but the command return always 'Unknown: Wrong Warning'. It's the same issue for the commands for the versions.

For your information, I'm trying to monitor McAfee Total Protection.
I'm using CentOS 7 and Centreon 19.04. 

Thanks for your answers,

Sincerely,

Julien CHAUVET

**Comment by garnier-quentin** [comment]
You have two equals! 
```
--warning-malware-detected=? --critical-malware-detected=?
```

**Comment by JulienC99** [comment]
Thanks! 
I have correct this and I tried again with:
`--critical-malware-detected=1`
But now i have this message: 
'Unknown: SNMP GET Request : Cant get single value.'
I think it's because I don't understand what i need to put after the equals.
Do you have any idea what i'm suppose to put in?

Sincerely,

Julien Chauvet.

**Comment by garnier-quentin** [comment]
Could you do a snmpwalk of following OID:
```
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.1230 > macaffee.snmpwalk
```

**Comment by JulienC99** [comment]
Ok this command return me this:

'.1.3.6.1.4.1.1230 = No more variables left in this MIB view (It is past the end of the MIB tree)

**Comment by garnier-quentin** [comment]
That's not the good plugin. Could you provide a full snmpwalk ?
```
snmpwalk -ObentU -v 2c -c public IP .1 > mcaffee.snmpwalk
```

**Comment by JulienC99** [comment]
This command return this:

'Error in packet.
Reason : (genError) A general failure occured
Failed object: .1.3.6.1.4.1.77.1.1.3.0'

**Comment by garnier-quentin** [comment]
Do you have mib files ?

**Comment by JulienC99** [comment]
I don't have the MIB files of McAfee because i don't find it.
I have research the OID find in the plugin : .1.3.6.1.4.1.1230.2.7.2.1.2.0 but in McAfee i just found the OID begin by .1.3.6.1.4.1.1230.2.4

Did you know were i can find the good MIB files?

**Comment by garnier-quentin** [comment]
In mcafee documentation or ask to your support.

**Comment by JulienC99** [comment]
Thanks for your answers,

I search this files, I test with it and I return you the result.

Sincerely,

Julien Chauvet.

**Comment by JulienC99** [comment]
Hi 
I found the coresponding MIB for mcafee EPO (TVD/NAI/EPO.mib). 
But when i try the command you gave me : 
`snmpwalk -ObentU -v 2c -c xxxxx 'ip_host' .1 >mcafee.snmpwalk` 
i get the folowing result :
`Error in packet`
`Reason: (genError) a general failure occured`
`Failed object .1.3.6.1.4.1.77.1.1.3.0`
this OID refers to the "LanMgr-Mib-II-MIB", so i added it manualy in centreon using pscp.exe.
But i get the same result.

Do you have any idea to help me?

**Comment by garnier-quentin** [comment]
Could you provide me the EPO.mib please ?

**Comment by JulienC99** [comment]
Ok here they are.
I modified the TDV-MIB.mib because it used special character : "_", so i removed them.
[MIB.zip](https://github.com/centreon/centreon-plugins/files/3310110/MIB.zip)

**Comment by garnier-quentin** [comment]
Could you launch snmpwalk of following branch:
```
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.3401 > epo.snmpwalk
```

**Comment by JulienC99** [comment]
That command returns nothing. 
Is it suppose to?

**Comment by garnier-quentin** [comment]
maybe not. So there is nothing in snmp.

**Comment by garnier-quentin** [comment]
McAfee total protection seems to be a solution with no central service (agent on servers). I dont know if we can monitor it.

**Comment by JulienC99** [comment]
Ok I have installed this to test the plugin because I'm currently on a test network. But we have an EPO server installed on the main network. I will do some test on it to see if it work, i'll tell you the result in a bit.
Again, tanks for your help. 
Sincerely, 
Julien Chauvet.

**Comment by garnier-quentin** [comment]
With Epo, i think we can monitor.
