### ISSUE TITLE
apps::tomcat::jmx::plugin: high load

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#1552]
Hi,

I´m executing up to 50 jmx checks via centreon in icinga for different remote hosts every 15 minutes, which causes a very high cpu load on a 4 core virtual machine. I don´t know, what exactly is causing the high cpu load as I´m using round about 400 other centreon checks, which are executed every 5 minutes (6 snmp checks) and doesn´t result such a high cpu load.

This is the command implementation in icinga2:

```
object CheckCommand "jolokia-gc" {
   import "plugin-check-command"
   command = [ CustomPluginDir + "/centreon-plugins/centreon_plugins.pl"]
   arguments = {
        "--plugin" = "apps::tomcat::jmx::plugin"
        "--custommode" = "jolokia"
        "--mode" = "gc-usage"
        "--url" = "$jolokia_url$"
        "--username" = "jolokia"
        "--password" = "xy123_"
        "--range-perfdata" = "1"
        }
}
```

Can anybody tell me how to debug this?

**Comment by garnier-quentin** [comment]
If you remove jmx checks, the load is ok ?

**Comment by benhartwich** [comment]
Yes. The high load occurs when I´ve configured all prod servers to use the jmx checks also.

**Comment by garnier-quentin** [comment]
Could you execute a command directly in the shell with time (and provide the result) ? I think you should do a session

**Comment by benhartwich** [comment]
The single checks lasts between 0.5 to 1.5 seconds. These checks are executed together:

```
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=gc-usage --url=http://xy:8882/jolokia --username=jolokia  --password=xy
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=fd-usage --url=http://xy:8882/jolokia --username=jolokia  --password=xy
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=cpu-load --url=http://xy:8882/jolokia --username=jolokia  --password=xy
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=threads --url=http://xy:8882/jolokia --username=jolokia  --password=xy_
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=memory --url=http://xy:8882/jolokia --username=jolokia  --password=xy
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=memory-detailed --url=http://xy:8882/jolokia --username=jolokia  --password=xy
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=memory-detailed --url=http://xy:8882/jolokia --username=jolokia  --password=xy
```

**Comment by garnier-quentin** [comment]
Could you provide the result with time please ?
```
time perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=memory-detailed --url=http://xy:8882/jolokia --username=jolokia  --password=xy
```

You can send me an email for a session.

**Comment by benhartwich** [comment]
real    0m1.084s
user    0m0.845s
sys     0m0.090s

**Comment by garnier-quentin** [comment]
For me, it seems ok. We need to do a session i think

**Comment by garnier-quentin** [comment]
I have done some profiling (launched 10 000 checks). And the result seems ok.
![profiling_jmx_plugins](https://user-images.githubusercontent.com/9079781/59778151-3efd4680-92b6-11e9-8a90-beb8f97b51ab.png)

**Comment by garnier-quentin** [comment]
Maybe you can use fatpack plugins: https://download.centreon.com/index.php?product=centreon-plugins-20190412&action=download&id=4883

You need to go at the end of the pl file:
```
# Not perl embedded compliant at all (need to comment)
use FindBin;
use lib "$FindBin::Bin";
```

And you can activate embedded perl with your icinga. Tell me if it saves performance.

**Comment by garnier-quentin** [comment]
Do you have some news about it ?

**Comment by benhartwich** [comment]
I´ve raisen the cpu cores at the moment. I don´t know what the fatpack really is as it seems to be same as the centreon plugins release zip? Also embedded perl for icinga seems to be the current state of the art as I´m not finding any infos regarding the current icinga2 release.

**Comment by garnier-quentin** [comment]
That's the same code base. But we use fatpack to create standalone perl file.
