### ISSUE TITLE
apps::vmware::connector::plugin - Storage Adapter

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#1554]
Hi,

I search the best way to check fiber channel on storage adapter.
I don't find mode to do that.

Thanks,

https://blogs.vmware.com/vsphere/2011/12/vmwares-software-fcoe-adapter.html

**Comment by garnier-quentin** [comment]
Could you provide perfmetrics ? I don't have that kind of adapter. It will be hard to develop it without access.

**Comment by romsworld** [comment]
We would just check is link is up, active and the numer of paths. 4 in my screen.
Perhaps can i check result of api webpage to help you ? Could you give me url ?

Thanks,

![image001](https://user-images.githubusercontent.com/12545407/60210172-82c6f180-985c-11e9-81aa-811579f29c94.png)

**Comment by romsworld** [comment]
Hi quentin,

Do you have all information ?
Thanks

**Comment by garnier-quentin** [comment]
I need an access to test it. Maybe it's in following object:
https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.host.StorageDeviceInfo.html

**Comment by oasisck** [comment]
I'm interesting too
and I can give you access ;-)

**Comment by romsworld** [comment]
I will try with hp ilo card on xmlapi, but this information was not present in xml, only on web interface.

**Comment by romsworld** [comment]
Hi Quentin,

What do you need for development?
Do you want us to make a webex?

Thanks,

**Comment by garnier-quentin** [comment]
Yes i need an access to test.

**Comment by garnier-quentin** [comment]
Need the vmware connector 3.2.2 and last centreon-plugins version for the mode 'storage-host'.
