### ISSUE TITLE
cloud::aws::ebs::plugin missing mode folder

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#1555]
.

./centreon_plugins.pl --plugin=cloud::aws::ebs::plugin --mode=volume-time --custommode=awscli
UNKNOWN: Cannot load module --mode.
Can't locate cloud/aws/ebs/mode/volumetime.pm in @INC (@INC contains: /usr/lib64/nagios/centreon-plugins /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib64/nagios/centreon-plugins/centreon/plugins/misc.pm line 221.

./centreon_plugins.pl --plugin=cloud::aws::ebs::plugin --mode=volume-iops --custommode=awscli
UNKNOWN: Cannot load module --mode.
Can't locate cloud/aws/ebs/mode/volumeiops.pm in @INC (@INC contains: /usr/lib64/nagios/centreon-plugins /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib64/nagios/centreon-plugins/centreon/plugins/misc.pm line 221.

Seems there are missing mode in ebs module plugin

**Comment by garnier-quentin** [comment]
You re right. We ll fix it soon

**Comment by R00T88** [comment]
Hi @garnier-quentin 
thanks! 
Do you have an eta for this?

Regards

**Comment by garnier-quentin** [comment]
That week or next week

**Comment by R00T88** [comment]
Hi @garnier-quentin 
do you have an update on this?

Thanks

**Comment by garnier-quentin** [comment]
Eventually, we don't know yet when we'll implement it.

**Comment by R00T88** [comment]
Hello @garnier-quentin and @Sims24 ,
any updates on this?

Thanks

**Comment by R00T88** [comment]
Hello @garnier-quentin  and @Sims24 ,
any updates on this?

Thanks

**Comment by garnier-quentin** [comment]
It's in the roadmap.

**Comment by Sims24** [comment]
@R00T88 , it has been added to our next sprint. Will be available before the May 15th. 

Sorry for the delay

**Comment by garnier-quentin** [comment]
Sorry for the delay. it's done. you can test it!
