### ISSUE TITLE
network::cisco::callmanager::snmp::plugin add modes

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon-plugins#1556]
Can you please add following modes to the plugin:
- cti-usage

   ccmCtiName      => { oid => '.1.3.6.1.4.1.9.9.156.1.8.1.1.2' },
    ccmCtiStatus    => { oid => '.1.3.6.1.4.1.9.9.156.1.8.1.1.5', map => \%mapping_status }

- voicemail-usage

    ccmVMailDevDescription => { oid => '.1.3.6.1.4.1.9.9.156.1.12.1.1.4' },
    ccmVMailDevName      => { oid => '.1.3.6.1.4.1.9.9.156.1.12.1.1.2' },
    ccmVMailDevStatus    => { oid => '.1.3.6.1.4.1.9.9.156.1.12.1.1.5', map => \%mapping_status }

let me know, if you require further information

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk and mib file ?
```
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4 > cisco_cm.snmpwalk
```

**Comment by Cancom-Monitoring** [comment]
[voicemailusage_pm.txt](https://github.com/centreon/centreon-plugins/files/3325406/voicemailusage_pm.txt)
[ctiusage_pm.txt](https://github.com/centreon/centreon-plugins/files/3325407/ctiusage_pm.txt)
[plugin_pm.txt](https://github.com/centreon/centreon-plugins/files/3325408/plugin_pm.txt)

**Comment by garnier-quentin** [comment]
thanks for the code!! but i still need the walk and mib :)

**Comment by Cancom-Monitoring** [comment]
yes saw it right now, i'll deliver :)

**Comment by Cancom-Monitoring** [comment]
hope it helps...
[CISCO-CCM-MIB.txt](https://github.com/centreon/centreon-plugins/files/3330356/CISCO-CCM-MIB.txt)

**Comment by Cancom-Monitoring** [comment]
Hi, can you go on with the informations provided?

**Comment by garnier-quentin** [comment]
Yes, i think so.

**Comment by garnier-quentin** [comment]
I have applied your patch. Could you test it ?
