### ISSUE TITLE
os::linux::local::plugin: new mode open-files

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1557]
It could be nice feature to add the possibility to monitor the open files:

- filter per user
- filter per pid/application

**Comment by garnier-quentin** [comment]
Why not. with lsof command.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by joschi99** [comment]
Done some test, looks good. It very useful monitoring some processes like logstash which can reach open file limits.
Thank you very much.

When you have planed to release new plugin version?

**Comment by garnier-quentin** [comment]
I think next week.
