### ISSUE TITLE
Ruckus AP filters not working

### ISSUE THREAD

**Issue by ffejtable** [centreon/centreon-plugins#1564]
plugin network::ruckus::ap::snmp::plugin
mode users

options 
--filter-counters
and
--filter-ssid

When trying to filter results using either of the above options, it does not appear to work as expected.

For --filter-counters it seems that every counter label other than total is labeled 'ssid'.
For --filter-ssid I can't seem to get it to include/exclude much of anything

This should be an easy fix.  I will look into it myself, but I don't use Perl often, and its been a while so I need to get back up to speed.

**Comment by garnier-quentin** [comment]
filter-ssid should work now.

**Comment by ffejtable** [comment]
thank you for such a quick response.  i confirmed that filter-ssid is now working and added a note to the commit.

no changes were made to --filter-counters.. not sure if this option is really needed.  perhaps commenting it out to avoid confusion?

**Comment by garnier-quentin** [comment]
Thanks for the feedback. filter-counters is used to only check counter status for example.
