### ISSUE TITLE
hardware::server::dell::openmanage::snmp::plugin --> Error

### ISSUE THREAD

**Issue by cmiscloni** [centreon/centreon-plugins#1565]
Bug with dellopenmanage plugin since last commit this morning.

All services configured on the plugin return this:

UNKNOWN: physical disk Physical Disk 0:1:0 has received a predictive failure  alert - physical disk Physical Disk 0:1:1 has received a predictive failure  alert - physical disk Physical Disk 0:1:2 has received a predictive failure  alert - physical disk Physical Disk 0:1:3 has received a predictive failure  alert - physical disk Physical Disk 0:1:4 has received a predictive failure  alert
--

Thanks

**Comment by garnier-quentin** [comment]
Sorry. Could you test it ? It should be fixed

**Comment by cmiscloni** [comment]
Yes it works, Thanks
