### ISSUE TITLE
[apps::wsus::local::plugin] mode synchronisation-status has wrong threshold parameters

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1567]
Plugins 20190412

The threshold parameters are not recognized:

    --warning-*
            Warning thresholds. Can be: 'progress' (%), 'duration' (s).

    --critical-*
            Critical thresholds. Can be: 'progress' (%), 'duration' (s).

**Comment by garnier-quentin** [comment]
Thanks. It should be fixed.
