### ISSUE TITLE
[Request] hardware::ups::standard::rfc1628::snmp::plugin battery-status temperature

### ISSUE THREAD

**Issue by Obito93** [centreon/centreon-plugins#1568]
Please follow information shown below according your issue. For all issues, thank you to describe it in English.
If some informations are confidentials, please send it directly by email to qgarnier@centreon.com and sbomm@centreon.com

## Bug/Question

Related to: https://github.com/centreon/centreon-plugins/issues/626

Using hardware::ups::standard::rfc1628::snmp::plugin mode=battery-status, we are currently unable to set the warning and critical values for any result with the exception being the remaining charge. It would be great to have the same options (--warning-*, --critical-*) for the battery-status as the other UPS plugins already have.

>$ perl centreon_plugins.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin -->mode=battery-status --help
>
>Plugin Description:
>    Check ups compatible RFC1628 in SNMP.
>
> ...
>
>Global Options:
>    --mode  Choose a mode.
>
>Mode:
>    Check Battery Status and battery charge remaining.
>
>    --warning
>            Threshold warning in percent of charge remaining.
>
>    --critical
>            Threshold critical in percent of charge remaining.

**Comment by garnier-quentin** [comment]
I will do that.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by Obito93** [comment]
I can confirm that the fix is working as intended. Thank you very much!

Just a minor thing:

perl centreon_plugins.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --mode=output-lines --help

returns

>--warning-\* --critical-\*
>            Thresholds. Can be: 'charge-remaining' (%), 'current' (A),
>            'voltage' (V), 'temperature' (C).

this should be changed to 

>--warning-\*
>            Thresholds. Can be: 'charge-remaining' (%), 'current' (A),
>            'voltage' (V), 'temperature' (C)
>
> --critical-\*
>            Thresholds. Can be: 'charge-remaining' (%), 'current' (A),
>            'voltage' (V), 'temperature' (C)

this would be more consistent with the other help outputs.
Once again, thank you for your quick support!
