### ISSUE TITLE
[Hardware] No component does not return correct criticity

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1569]
Hi,

In hardware modes (Mikrotik, Checkpoint...), we have :
```
    --no-component
            Return an error if no compenents are checked. If total (with
            skipped) is 0. (Default: 'critical' returns).
```

Unfortunately, CRITICAL does not return by default, but OK.
Doc issue ?
Hardware mode issue ?

Thank you :+1:

**Comment by garnier-quentin** [comment]
It's a doc issue. ok by default.

**Comment by CPbN** [comment]
OK, thank you Quentin !
