### ISSUE TITLE
ibm imm plugin

### ISSUE THREAD

**Issue by slc23** [centreon/centreon-plugins#1570]
Hi, 
I'm trying to monitor ibm server System x3550 M5 - Type 5463  using the environment plugin :
'centreon-plugins/hardware/server/ibm/mgmt_cards/imm/snmp/'

I downloaded the github, found and uploaded the ibm MIB, i configured an snmp v1 community on my centreon server, and i configured the snmp on my imm.

When i type the following on my central server :
`perl centreon_plugins.pl --plugin=hardware::server::ibm::mgnt_cards::imm::snmp::plugin --mode=environment --hostname=imm_ip --snmp-version='v1' --snmp-community='community' --snmp-timeout 20 --component=fan --debug --snmp-force-getnext`

I always get different results.

sometime i get :
`OK: All 0 components are ok [ ]. |`
`Checking fans`
other time i get :
`UNKNOWN: SNMP Table Request : Timeout`

or :
`UNKNOWN: SNMP Table Request : Timeout : (genError) A general failure occured`

and sometime i get the right information.

when i put the same command throught the web interface the service status says 'unknown' whithout a detail status.

when i type :
`snmpwalk -ObentU -v 1 -c 'community' 'imm_ip' .1`
it start to list OID but at some random point it stop and return this :
`Timeout : No Response from 'imm_ip'` 

I tried it all again on a second imm with the same configuration but i get the same result, i'm unsure from where the problem is.

Thanks for your help.

Slc23.

**Comment by garnier-quentin** [comment]
Could you try with --snmp-autoreduce option ?

**Comment by slc23** [comment]
Thanks for the quick reponse !
I replace `snmp-force-getnext` by `snmp-autoreduce` but i still got 3 different response from my 2 imm.

**Comment by garnier-quentin** [comment]
It seems like an issue from imm snmp agent.

**Comment by slc23** [comment]
i'll look it up with ibm support and i'll get back to if i find a solution, but do you have any idea why i dont get any information from the imm on the web interface while i get it sometime on the central server ?

**Comment by garnier-quentin** [comment]
I don't understand. Which central server ? imm central server ?

**Comment by slc23** [comment]
When i type the command in centos i get the result i talked about before : (these are 2 of the 4 possible result)
![Error1](https://user-images.githubusercontent.com/45031809/60670635-7a307580-9e71-11e9-8864-bc5b68c4ec8c.PNG)
![Result](https://user-images.githubusercontent.com/45031809/60670647-7ef52980-9e71-11e9-9c9c-4f664f9c104f.PNG)

but on the web interface of centreon when i configure a check command : 
![Command](https://user-images.githubusercontent.com/45031809/60671214-e9f33000-9e72-11e9-86c4-305e3a5129c3.PNG)

a service :
![ServiceFan](https://user-images.githubusercontent.com/45031809/60671226-f2e40180-9e72-11e9-900e-c341be0e31ab.PNG)

when i connect it the host and after exporting the configuration the status of the service stays the same : (i had to change the name of the host for security reasons so the timer is off)
![StateService](https://user-images.githubusercontent.com/45031809/60671356-33dc1600-9e73-11e9-9aea-bd9ae2184660.PNG)

Do you know why i don't get any result on the web interface ?

**Comment by garnier-quentin** [comment]
Are you sure that the first one is an imm ? (the imm with no results)

**Comment by slc23** [comment]
yes i can connect to both with their ip and configure them, they are both imm, but what do you mean the one with no result, both aren't working on the web interface and are working, sometime, when i type the command on centos.

**Comment by garnier-quentin** [comment]
So that's weird. Need to ask to your ibm support
