### ISSUE TITLE
plugin=hardware::server::hp::bladechassis::snmp::plugin  -> Unknown 

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon-plugins#1572]
Hi,

check generates Unknown reply since update:

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::bladechassis::snmp::plugin --hostname 10.10.10.10 --snmp-community=public --snmp-version=2c --mode=hardware --component enclosure --snmp-timeout=60 --snmp-retries=0 --verbose
UNKNOWN: Not a SCALAR reference at /usr/lib/nagios/plugins/centreon-plugins/hardware/server/hp/bladechassis/snmp/mode/components/enclosure.pm line 79. 

Solution:
 
**Old:**
        my $exit = $self->get_severity(label => 'default', section => 'enclosure', value => **$**$result->{cpqRackCommonEnclosureCondition});

**New:** 
        my $exit = $self->get_severity(label => 'default', section => 'enclosure', value => $result->{cpqRackCommonEnclosureCondition});

Thanks!

**Comment by garnier-quentin** [comment]
Sorry for the bug
