### ISSUE TITLE
[network::juniper::ssg::plugin] mode sessions

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#158]
Hello,

Should you add sessions failed on this mode with warning and critical thresholds ?
NETSCREEN-RESOURCE-MIB::nsResSessFailed

Thanks

**Comment by Sims24** [comment]
Hello Dominique, 

You can probably test now, modified few things and Quentin either.

Please let us now, 

Thanks

**Comment by ritouret** [comment]
Hello Simon,

Thank you for your work.

These information has disapear from --help :

Mode:
    Check Juniper sessions usage (NETSCREEN-RESOURCE-MIB).

    --warning
            Threshold warning in percent.

    --critical
            Threshold critical in percent.

And nothing more in the --list-mode :
Modes Available:
   cpu
   hardware
   interfaces
   list-interfaces
   memory
   sessions

So, if it's available, i don't now how to test it !

**Comment by ritouret** [comment]
Here is the result with just option "--mode=sessions "

Use of uninitialized value in multiplication (*) at /logiciel/nagios/plugins/centreon-plugins/network/juniper/common/screenos/mode/sessions.pm line 83.
Use of uninitialized value in sprintf at /logiciel/nagios/plugins/centreon-plugins/network/juniper/common/screenos/mode/sessions.pm line 94.
OK: 2.47% of the sessions limit reached (199 of max. 8064) - 0.00% of failed sessions (0 of max. 8064) | 'sessions'=199;;;0;8064 'sessions_failed'=;;;0;8064

**Comment by Sims24** [comment]
Hi Dominique, 

Thanks for testing, my bad, little typo. Just commit a fix if you could try again ... 

For the help I'll throw a look tomorrow and give you an answer.

Regards

**Comment by ritouret** [comment]
No more uninitialized value now.
Waiting tomorrow for --help.

Thank you simon.

**Comment by Sims24** [comment]
Hi, 

Works correctly for me ... 

If I perform : 

./centreon_plugins.pl --plugin network::juniper::ssg::plugin --mode sessions --help

I see the full help message. 

Could you try again ? 

Thanks

**Comment by ritouret** [comment]
Not for me : warning and critical thresholds still missing at the end.
Should have thresholds for sessions and for sessions_failed.

Here the complete action :

# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl  --plugin=network::juniper::ssg::plugin --mode=sessions --help      
Plugin Description:
    Check Juniper SSG in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

    --sanity-options
            Check unknown options (for debug purpose).

Output Options:
    --verbose
            Display long output.

    --debug Display also debug messages.

    --filter-perfdata
            Filter perfdata that match the regexp.

    --explode-perfdata-max
            Put max perfdata (if it exist) in a specific perfdata (without
            values: same with '_max' suffix) (Multiple options)

    --change-perfdata
            Change perfdata name (Multiple option) Syntax:
            regexp_matching,regexp_substitute

    --range-perfdata
            Change perfdata range thresholds display: 1 = start value equals
            to '0' is removed, 2 = threshold range is not display.

    --opt-exit
            Exit code for an option error, usage (default: unknown).

    --output-xml
            Display output in XML Format.

    --output-json
            Display output in JSON Format.

    --disco-format
            Display discovery arguments (if the mode manages it).

    --disco-show
            Display discovery values (if the mode manages it).

Snmp Options:
    --hostname
            Hostname to query (required).

    --snmp-community
            Read community (defaults to public).

    --snmp-version
            Version: 1 for SNMP v1 (default), 2 for SNMP v2c, 3 for SNMP v3.

    --snmp-port
            Port (default: 161).

    --snmp-timeout
            Timeout in secondes (default: 1) before retries.

    --snmp-retries
            Set the number of retries (default: 5) before failure.

    --maxrepetitions
            Max repetitions value (default: 50) (only for SNMP v2 and v3).

    --subsetleef
            How many oid values per SNMP request (default: 50) (for get_leef
            method. Be cautious whe you set it. Prefer to let the default
            value).

    --snmp-username
            Security name (only for SNMP v3).

    --authpassphrase
            Authentication protocol pass phrase.

    --authprotocol
            Authentication protocol (MD5|SHA)

    --privpassphrase
            Privacy protocol pass phrase

    --privprotocol
            Privacy protocol (DES|AES)

    --contextname
            Context name

    --contextengineid
            Context engine ID

    --securityengineid
            Security engine ID

    --snmp-errors-exit
            Exit code for SNMP Errors (default: unknown)

**Comment by ritouret** [comment]
line 121, you miss this :
=head1 MODE

**Comment by ritouret** [comment]
Another thing :
There is no maximum for sessions_failed.
One of our equipment have a maximum of 128064 sessions and this summer we had 8709204 sessions failed for it !
So, i'm not sure that percentage is adequate for --warning-failed and --critical-failed.

**Comment by Sims24** [comment]
Hum, 

Think that's my bad, sorry @ritouret @garnier-quentin , need to be sure that is a current value and not a counter, if so, then I'll put a cache file for threshold and count sessions failed / seconds ... 

Sorry for that !

Will check this point friday afternoon

**Comment by Sims24** [comment]
Sorry Dominique I was so busy and totally forgot to fix this one. Just commit something, waiting Quentin merge it but if you want you can take it on juniper-session branch on my centroen-plugins fork. 

Thanks

**Comment by ritouret** [comment]
Hello Simon,
I don't know how to test it on your centreon-plugins fork ...

**Comment by Sims24** [comment]
Hello  Dominique, 

Just browse http://github.com/Sims24/centreon-plugins as you do for the master and get the plugin and sessions.pm file and try with these. 

Thanks,

**Comment by garnier-quentin** [comment]
I have done the commit on master. Could you test it Dominique ?

**Comment by ritouret** [comment]
Just tested, it works perfectly. Many thanks.
Both in production ;-)
