### ISSUE TITLE
Office365 plugin error

### ISSUE THREAD

**Issue by markeur** [centreon/centreon-plugins#1580]
Hello,

I am trying to configure office365 plugin to monitor some service but when I want to check for help with --help with a mode configure like mailbox-usage I get the following error message : UNKNOWN: Cannot load module --custommode (I don't use --custommode) Can't locate JSON/XS.pm in @INC. (@INC contains ...)
BEGIN failed--compilation aborted at /usr/lib64/nagios/plugins/cloud/microsoft/office365/custom/graphapi.pm line 28. 
Compilation failed in require at /usr/lib64/nagios/plugins/centreon/plugins/misc.pm line 217.

could you help me please? 

Thank you

**Comment by garnier-quentin** [comment]
Please install JSON::XS. 
```
yum install 'perl(JSON::XS)'
```
