### ISSUE TITLE
apps::tomcat::web::plugin Question

### ISSUE THREAD

**Issue by cmiscloni** [centreon/centreon-plugins#1582]
Hello,

i'm facing at much difficulties to monitor few Tomcat servers ( version 9, 7 )
Access to manager/html works with a browser but with the plugin, the server returns me this message :

`UNKNOWN: Application 'h1 {font-family' state: Tahoma,Arial,sans-serif;color | 'h1 {font-family#application.sessions.active.count'=white;background-color;;;0;
`

The command i used is:

`centreon_plugins.pl --plugin=apps::tomcat::web::plugin --mode=applications --hostname=server.domain --credentials --username=XXX --password=XXXX --port=8080 --urlpath='/manager/html'`

If i don't use --urlpath, the server tell me : **UNKNOWN: 403 Forbidden |**

I have already tried with option --basic

Any ideas ?

Thanks

**Comment by cmiscloni** [comment]
Same problem with --urlpath='/manager/text/list' **UNKNOWN: 403 Forbidden |**

**Comment by garnier-quentin** [comment]
Is it ok with your webbrowser ?

**Comment by cmiscloni** [comment]
Yes with browser it work

**Comment by garnier-quentin** [comment]
Does it work with curl from the server ? because of ip filtering maybe

**Comment by cmiscloni** [comment]
Ok with curl:

` curl -v -u login:password 'http://IP:8080/manager/html/'`

* About to connect() to IP port 8080 (#0)
*   Trying IP...
* Connected to IP (IP) port 8080 (#0)
* Server auth using Basic with user 'xxxxxx'
> GET /manager/html/ HTTP/1.1
> Authorization: Basic YWRtaW46amFwb25pY3Vt
> User-Agent: curl/7.29.0
> Host: IP:8080
> Accept: */*

**Comment by cmiscloni** [comment]
It return the html code only with this url but there is no 403 return code with curl

**Comment by cmiscloni** [comment]
Mybe the urlpath is different with TomCat 9 ?

**Comment by cmiscloni** [comment]
![image](https://user-images.githubusercontent.com/4446733/61035169-f7567000-a3c6-11e9-8127-85718f83ac8a.png)

When I connect with plugin or curl, there is no Guessed User name but session exist on server
With browser Guessed User name is ok

**Comment by garnier-quentin** [comment]
So i have tested and it's working. You need to have an user with following roles:
```
<user username="admin" password="adminadmin" roles="manager-gui,manager-script"/>
```

And you need to edit the './webapps/manager/META-INF/context.xml' to modify the IP filtering:
```
<Context antiResourceLocking="false" privileged="true" >
<Valve className="org.apache.catalina.valves.RemoteAddrValve"
	 allow="\d+\.\d+\.\d+\.\d+" />  
  <Manager sessionAttributeValueClassNameFilter="java\.lang\.(?:Boolean|Integer|Long|Number|String)|org\.apache\.catalina\.filters\.CsrfPreventionFilter\$LruCache(?:\$1)?|java\.util\.(?:Linked)?HashMap"/>
</Context>
```
