### ISSUE TITLE
[database::mssql::plugin]: how to set .env variable for dbi:driver on centos?

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#1583]
Hi,

how should I set the .env variable DBI_DRIVER for using

./centreon_plugins.pl --plugin=database::mssql::plugin --mode=backup-age

I´ve installed the package perl-dbd-odbc on Centos 7, but I don´t know, how and where this variable has to be set as there is no documentation available.

Thanks and regards,

**Comment by garnier-quentin** [comment]
I didn't test with ODBC driver. I use perl-DBD-Sybase and freetds.

**Comment by benhartwich** [comment]
OK, but there seems no installation candidate for centos7? But I think the main problem is, how and where has the .env variable to be placed?

**Comment by garnier-quentin** [comment]
The package:
```
yum info perl-DBD-Sybase
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.crazyfrogs.org
 * centos-sclo-rh: centos.crazyfrogs.org
 * centos-sclo-sclo: centos.crazyfrogs.org
 * epel: epel.besthosting.ua
 * extras: centos.mirrors.ovh.net
 * updates: centos.mirrors.ovh.net
Installed Packages
Name        : perl-DBD-Sybase
Arch        : x86_64
Version     : 1.15
Release     : 2.el7.centos
Size        : 238 k
Repo        : installed
From repo   : centreon-stable
Summary     : Perl module named DBD-Sybase
URL         : http://search.cpan.org/~mewp/DBD-Sybase-1.15/Sybase.pm
License     : GPL or Artistic
Description : perl-DBD-Sybase is a Perl module.
```

**Comment by benhartwich** [comment]
```
[root@emea-mon02 ~]# yum info perl-DBD-Sybase
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.nextlayer.at
 * centos-sclo-rh: mirror.nextlayer.at
 * centos-sclo-sclo: mirror.nextlayer.at
 * epel: mirror.nextlayer.at
 * extras: mirror.nextlayer.at
 * remi-safe: remi.mirror.karneval.cz
 * updates: mirror.nextlayer.at
Error: No matching Packages to list
```
Is there any specific mirror / repo?

**Comment by garnier-quentin** [comment]
The repository: http://yum.centreon.com/standard/19.04/el7/stable/x86_64/RPMS/

**Comment by benhartwich** [comment]
Thanks, the package is installed now. How has the env so to be set?

**Comment by garnier-quentin** [comment]
No need to set environment. Only use parameters. (you should the default version in freetds.conf)

**Comment by benhartwich** [comment]
Can you please give me an example with this command:
`./centreon_plugins.pl --plugin=database::mssql::plugin --mode=backup-age --hostname=db01.azure --port=1433 --username=xy --password='123' --datasource=test --skip-no-backup`

**Comment by garnier-quentin** [comment]
Please modify line tds 'version = 4.2' to 'tds version = 8.0' in '/etc/freetds.conf'. Your command seems ok

**Comment by benhartwich** [comment]
OK, thanks. I´ve updated the line version = 8.0 at [global], but the command gives the same error:

`UNKNOWN: Can't connect to data source 'DBI:test' because I can't work out what driver to use (it doesn't seem to contain a 'dbi:driver:' prefix and the DBI_DRIVER env var is not set) at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/dbi.pm line 229.`

**Comment by garnier-quentin** [comment]
Please remove your option --datasource

**Comment by benhartwich** [comment]
Ah thanks, it works. Is datasource not for selecting a single database?

**Comment by garnier-quentin** [comment]
datasource is used to override other connect options and create your own dbi dsn string

**Comment by benhartwich** [comment]
And how are specific databases selected?

**Comment by garnier-quentin** [comment]
You have the option --database (it's not in the help...)

**Comment by benhartwich** [comment]
Thanks, this option doesn´t seem to be recognized, because the error says, that he is trying to get view server state permision on the database master.

**Comment by garnier-quentin** [comment]
Most of checks access master database

**Comment by benhartwich** [comment]
Thanks, solved.

To wrap up all findings:
1) install freetds and perl-dbd-sybase
If you can´t install sybase package use this repo definition for centos:
```
# Centreon CentOS repository list
# http://yum.centreon.com/standard/19.04
[centreon]
name = Centreon
baseurl = http://yum.centreon.com/standard/19.04/el7/stable/x86_64/
gpgkey=http://yum.centreon.com/standard/19.04/RPM-GPG-KEY-CES
gpgcheck=1
```
2) Freetds Version
uncomment and update the version of freetds at [global] to 8.0

3) Don´t use --datasource attribute, but --database attribute, if you want to select a single database. Keep in mind, that most checks belong to the master db.
To check the master create a monitoring user and select at user properties => securables grant View server state

What would be a possible addition to this little tutorial: how to use windows authentification for a connection.

**Comment by garnier-quentin** [comment]
You can test to add 'use ntlmv2 = yes' in freetds.conf.

**Comment by benhartwich** [comment]
Now I´ve configured the checks at icinga2, but it seems that datasource is required at all:
Plugin Output: UNKNOWN: Need to specify data_source arguments.

Is there any empty possibility for datasource?

**Comment by garnier-quentin** [comment]
datasource is not needed if you set hostname option for example (you have tested in command line also and it's working)

**Comment by benhartwich** [comment]
Sorry, missed the hostname variable.
