### ISSUE TITLE
UNKNOWN: Failed to establish SSL connection: , ssl_error=SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by ahmed-soria** [centreon/centreon-plugins#1585]
Dears,
I have been using centreon-plugin Global Version: 20171013 on old linux. 
then i upgraded the OS version to the latest on and also started using the latest version of centreon-plugin. then the above error appeared for monitoring ILO3 and there is no issue for monitoring ilo4
here is the command that am using
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin hardware::server::hp::ilo::xmlapi::plugin --mode hardware --hostname 192.168.1.1 --username username --password password

**Comment by garnier-quentin** [comment]
Could you try with following options ?
```
--ssl-opt="SSL_version=SSLv3"  --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE"
```

**Comment by ahmed-soria** [comment]
Dear @garnier-quentin 
here is the output
UNKNOWN: Failed to establish SSL connection: , ssl_error=SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by garnier-quentin** [comment]
Could you try with option --force-ilo3 ?

**Comment by ahmed-soria** [comment]
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin hardware::server::hp::ilo::xmlapi::plugin --mode hardware --hostname 192.168.1.1 --username username --password password --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --force-ilo3 
i have used the above command
and also without  ' --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" '
I have got the same error as below 
**UNKNOWN: Cannot get data: HTTP::Response=HASH(0x27a82d0)->status_line**

**Comment by garnier-quentin** [comment]
And with that command ?
```
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin hardware::server::hp::ilo::xmlapi::plugin --mode hardware --hostname 192.168.1.1 --username username --password password --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --ssl-opt="SSL_version=TLSv1" --force-ilo3
```

**Comment by ahmed-soria** [comment]
i got the below error

UNKNOWN: Cannot get data: HTTP::Response=HASH(0x24a5438)->status_line

**Comment by garnier-quentin** [comment]
Which ilo version do you try to monitor ?

**Comment by ahmed-soria** [comment]
Integrated Lights-Out 3 , Firmware Version 1.80

**Comment by garnier-quentin** [comment]
Could you test with the last git version ? 

Install the package curl:
```
yum install perl-Net-Curl
```

And try following command line:
```
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin hardware::server::hp::ilo::xmlapi::plugin --mode hardware --hostname 192.168.1.1 --username username --password password --http-backend=curl --force-ilo3
```

**Comment by ahmed-soria** [comment]
Dear @garnier-quentin 
it shows the below error 

Unknown option: http-backend at /usr/lib/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by garnier-quentin** [comment]
You need to update your version

**Comment by ahmed-soria** [comment]
I have downloaded   centreon-plugins-20190111 &  centreon-plugins-20190412 
and stile the same error "Unknown option: http-backend at /usr/lib/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 67 "
both of the plugins version is  Global Version: (dev)

**Comment by garnier-quentin** [comment]
The last version: https://github.com/centreon/centreon-plugins/archive/master.zip

**Comment by ahmed-soria** [comment]
Dear here is the output :

Argument "URLOPT_SSL_VERIFYPEER" isn't numeric in subroutine entry at /home/sysadm/centreon-plugins-master/centreon/plugins/backend/http/curl.pm line 143.
UNKNOWN: curl setopt error: 'An unknown option was passed in to libcurl'.

**Comment by garnier-quentin** [comment]
You can download it again: https://github.com/centreon/centreon-plugins/archive/master.zip
And please restest. It should be fixed.

**Comment by ahmed-soria** [comment]
Dear @garnier-quentin ,
after i run the command using the new master plugin with those options "--http-backend curl --force-ilo3
"
it showed this error " UNKNOWN: Cannot get data: Error: Line #0: syntax error near ">" "

**Comment by garnier-quentin** [comment]
Could you provide the result with --debug option ?

**Comment by ahmed-soria** [comment]
Dear please find the below 

UNKNOWN: Cannot get data: Error: Line #0: syntax error near ">".
== Info: About to connect() to 192.168.1.1 port 443 (#0)
== Info:   Trying 192.168.1.1...
== Info: Connected to 192.168.1.1 (192.168.1.1) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info: warning: ignoring value of ssl.verifyhost
== Info: skipping SSL peer certificate verification
== Info: SSL connection using TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
== Info: Server certificate:
== Info:        subject: C=US,ST=Texas,L=Houston,O=Hewlett-Packard Company,OU=ISS,CN=Ilo Name (DNS)
== Info:        start date: Mar 22 11:11:38 2013 GMT
== Info:        expire date: Feb 15 05:43:22 2002 GMT
== Info:        common name: Ilo Name (DNS)
== Info:        issuer: CN=iLO Default Issuer (Do not trust),OU=ISS,O=Hewlett-Packard Company,L=Houston,ST=TX,C=US
=> Send header: POST /ribcl HTTP/1.1
Host: 192.168.1.1
Accept: */*
Connection:Close
TE:chunked
Content-Length: -1
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

=> Recv header: HTTP/1.1 200 OK
=> Recv header: Content-Type: text/xml
=> Recv header: Date: Mon, 15 Jul 2019 16:03:36 GMT
=> Recv header: Cache-Control: no-cache
=> Recv header: Expires: Thu, 26 Oct 1995 00:00:00 GMT
=> Recv header: Transfer-Encoding: chunked
=> Recv header: Server: Allegro-Software-RomPager/4.62
=> Recv header: Connection: close
=> Recv header:
=> Recv data: 091
<?xml version="1.0"?>
<RIBCL VERSION="2.22">
<RESPONSE
    STATUS="0x0001"
    MESSAGE='Error: Line #0: syntax error near ">".'
    />
</RIBCL>

0

== Info: Closing connection 0
<?xml version="1.0"?>
<RIBCL VERSION="2.22">
<RESPONSE
    STATUS="0x0001"
    MESSAGE='Error: Line #0: syntax error near ">".'
    />
</RIBCL>

**Comment by garnier-quentin** [comment]
Could you download it again and retest it ?

**Comment by ahmed-soria** [comment]
Dear @garnier-quentin,
please find the below erro : 
UNKNOWN: 500 Can't connect to 192.168.1.1:443 (SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure) |

**Comment by garnier-quentin** [comment]
Could you show me your command ?

**Comment by ahmed-soria** [comment]
perl centreon_plugins.pl --plugin hardware::server::hp::ilo::xmlapi::plugin --mode hardware --hostname 192.168.1.1 --username username--password password --force-ilo3

**Comment by garnier-quentin** [comment]
Try with that command please:
```
perl centreon_plugins.pl --plugin hardware::server::hp::ilo::xmlapi::plugin --mode hardware --hostname 192.168.1.1 --username username --password password --force-ilo3 --http-backend=curl
```

**Comment by ahmed-soria** [comment]
Dear @garnier-quentin ,
here is the result 
OK: All 31 components are ok [1/1 fans, 4/4 pdrive, 24/24 temperatures, 2/2 vrm]. | 'fan_Virtual Fan'=30%;;;0; 'temp_01-Inlet Ambient'=17C;;;; 'temp_03-CPU 1'=52C;;;; 'temp_04-CPU 2'=40C;;;; 'temp_07-HDD Max'=35C;;;; 'temp_09-DIMMs 1 1-4'=56C;;;; 'temp_10-DIMMs 1 5-8'=57C;;;; 'temp_11-DIMMs 1 9-12'=48C;;;; 'temp_12-DIMMs 1 13-16'=39C;;;; 'temp_13-DIMMs 2 1-4'=53C;;;; 'temp_14-DIMMs 2 5-8'=57C;;;; 'temp_15-DIMMs 2 9-12'=47C;;;; 'temp_16-DIMMs 2 13-16'=38C;;;; 'temp_25-Memory 1 1-8'=54C;;;; 'temp_26-Memory 1 9-16'=49C;;;; 'temp_27-Memory 2 1-8'=51C;;;; 'temp_28-Memory 2 9-16'=46C;;;; 'temp_49-IOH'=85C;;;; 'temp_51-Mezz Zone 1'=52C;;;; 'temp_52-Mezz Zone 2'=56C;;;; 'temp_55-Sys Exhaust 1'=49C;;;; 'temp_56-Sys Exhaust 2'=56C;;;; 'temp_57-Sys Exhaust 3'=50C;;;; 'temp_61-System Board'=27C;;;; 'temp_63-System Board'=57C;;;; 'count_fan'=1;;;; 'count_pdrive'=4;;;; 'count_temperature'=24;;;; 'count_vrm'=2;;;;
Thank you for your support 
would you please explain the root cause .
BR

**Comment by garnier-quentin** [comment]
it comes from the ssl perl module issue. With the curl backend, we have less issue about that.

**Comment by noxxi** [comment]
From the various comments:

> ... then i upgraded the OS version to the latest on ...

The first one suggests that a newer version of OpenSSL is used as the ultimate backend for IO::Socket::SSL (which is used in the code by default). These new versions usually have since years no longer support for  SSL 3.0 compiled in and for some time also don't support 3DES  as cipher any longer.

> ... SSL connection using TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA

This suggest that the server is that old that the best it can do is 3DES. But as I said newer OpenSSL versions no longer have support for 3DES compiled in since this is a weak cipher. This then results in

> ... sslv3 alert handshake failure

since no common cipher can be found: the server only supports weak ones and the client refuses to use weak ones.
