### ISSUE TITLE
[database::oracle::plugin] CRITICAL: Cannot connect: (no error string)

### ISSUE THREAD

**Issue by VincentPu67** [centreon/centreon-plugins#1587]
Hi,

I create a service on centreon to monitor a oracle database (tnsping) but I get the error :
 `Critical : Cannot Connect :(no error string)..`

If I run this command from putty with account root or centreon-engine or oracle it works 👍 

`./centreon_plugins.pl --plugin=database::oracle::plugin --mode=tnsping --hostname=10.80.1.3 --sid=PUMAORA --port=1521`

result : 
`OK: Connection established to listener 'PUMAORA'. |`

I follow this topics to setup oracle client & centreon services but we use oracle client 12 instead 19 due to our oracle db version.
[https://pixelabs.fr/oracle-client-19c-installation-sous-centos7-centreon/](url)
[https://pixelabs.fr/supervision-oracle-database-avec-centreon/](url)

Regards,
Vincent

**Comment by garnier-quentin** [comment]
What do you have in '/etc/ld.so.conf.d' ?

**Comment by VincentPu67** [comment]
Hi,

here is the content of /etc/ld.so.conf.d

kernel-3.10.0-862.14.4.el7.x86_64.conf  kernel-3.10.0-957.5.1.el7.x86_64.conf
kernel-3.10.0-957.10.1.el7.x86_64.conf  oracle-instantclient.conf
kernel-3.10.0-957.12.1.el7.x86_64.conf  qt-x86_64.conf
kernel-3.10.0-957.21.3.el7.x86_64.conf

**Comment by garnier-quentin** [comment]
If it works with centengine account, it should work with centengine daemon.

**Comment by VincentPu67** [comment]
ok I open the oracle-instantclient.conf and I see that the path of oracle is wrong

I correct it and i'm now testing

**Comment by VincentPu67** [comment]
I got the same error after correct oracle-instantclient.conf :(

**Comment by garnier-quentin** [comment]
Could you provide the environment of centengine (when it works) ?

**Comment by garnier-quentin** [comment]
you have some environment variables (LD_LIBRRARY_PATH, ORACLE_HOME). Maybe that's the issue.

**Comment by garnier-quentin** [comment]
I think it's the same issue: https://github.com/centreon/centreon-plugins/issues/1637
The module DBD::Oracle is in your /root directory. You need to reinstall it.
