### ISSUE TITLE
network::fortinet::fortigate Cluster-status warning when Master changes to predefined slave

### ISSUE THREAD

**Issue by harbourlad** [centreon/centreon-plugins#1588]
Hi there,
I'm new here and so I have to apologize if this request is placed at the wrong place. 
I just would like to know if there is  a possibility to get a warning when the master-role of a Fortigate Cluster changes to another Node (as the predefined one)? Actually I just find the possibility for a warning if the Cluster is not in sync or if not all nodes are available. But I would like to get a warning when the Clustermaster-role changes to another Clustermember than the predefined Master.

**Comment by garnier-quentin** [comment]
You want an alert when the role change ? (master -> slave or slave -> master)

**Comment by harbourlad** [comment]
Yes - this would be enough. 
But ideally it would be, if I could get an alarm, as long as the node actually configured as master does not have the master role

**Comment by garnier-quentin** [comment]
You can already do it.
```
--critical-status=' %{hostname} eq "toto" and %{role} eq "slave" '
```

**Comment by harbourlad** [comment]
Uuups - I will test this immediately

**Comment by harbourlad** [comment]
Great - it works perfectly! Thank you very much!

**Comment by garnier-quentin** [comment]
Thanks for the feedback

**Comment by harbourlad** [comment]
HI all,
since we updated the Plugin-Set this check doesn't work anymore.
The status is always "OK" - regardless of which of the two nodes is master. Has anything changed within this plugin?

I tried this:
`/usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=cluster-status --hostname=1.1.1.1 --snmp-version='2c' --snmp-community='public' --warning-synchronized='2' --critical-synchronized='' --warning-not-synchronized='' --critical-not-synchronized='' --warning-status='%{hostname} eq "FW01-N1" and %{role} eq "slave"' --critical-status='' --verbose`

And I get this:
```
OK: HA mode: activePassive - Nodes Synchronized: 2, Not Synchronized: 0 - All cluster nodes status are ok | 'total_nodes'=2;;;0; 'synchronized_nodes'=2;0:2;;0; 'not_synchronized_nodes'=0;;;0; 'total_checksums'=1;;;0;
Node 'FGTxxxxxxxxxxxxx' status is 'synchronized' [Hostname: FW01-N2] [Role: master] [Checksum: X1X2X3X4X5X6X7]
Node 'FGTxxxxxxxxxxxxx' status is 'synchronized' [Hostname: FW01-N1] [Role: slave] [Checksum: X1X2X3X4X5X6X7]
```

As you can see the Node FW01-N1 is slave and the Plugin should reply a Warning state - but it doesn't

**Comment by garnier-quentin** [comment]
It should be ok now

**Comment by harbourlad** [comment]
Thank you very much - I am always enthusiastic about the extremely fast troubleshooting

**Comment by garnier-quentin** [comment]
You're welcome. thanks also for the quick feedback
