### ISSUE TITLE
[plugin] bgppeerstate with cisco vrf

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon-plugins#159]
Hi,

With the plugin bgppeerstate when a BGP Peer is up inside a VRF the plugin output is wrong :

./centreon_plugins.pl --plugin=apps::protocols::bgp::4::plugin --mode=bgppeerstate --hostname=rtrname --snmp-version=2 --snmp-community=com --bgppeer=PeerIP
CRITICAL: Peer IP AdminState=start Connection=idle [Remote Addr:RemoteIP:0 AS:asnum] [Last Update 0 s]  |

The peer is in state Established, but with a vrf the OID is not the same and the output is Idle.

With the old version the output is OK :

./centreon_plugins.pl --plugin=apps::protocols::bgp::4::plugin --mode=bgppeerstate --hostname=rtrname --snmp-version=2 --snmp-community=com --bgppeer=peerIP
OK: Peer are in an established state since 68 days and 17 hours |

It's possible to send a mail with the snmpwalk if you want.

Thanks.

**Comment by garnier-quentin** [comment]
I don't really understand. Could you send me the walk and also the command ? (good option for bgppeer)

**Comment by tcheval** [comment]
Hi, sorry i have missed the notification.
I have updated plugin pack, it's seems good now.

Thanks very much.
