### ISSUE TITLE
IBM TS3500 Tape Library

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#1591]
Hi,

I tried the  storage::ibm::ts3500::snmp::plugin plugin but didn't works with TS3584. So I tried this plugin:
https://www.bityard.org/blog/2013/04/15/nagios_monitoring_ts3500_tape_library

Maybe we can update the Centreon plugin to support it?

Thanks,

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of your TS 3584 and mib files ?
```
snmpwalk -ObentU -v 2c -c public IP .1 > ts3584.snmpwalk
```

**Comment by garnier-quentin** [comment]
Could you provide me the snmpwalk and the mib please ?

**Comment by rk4an** [comment]
Sorry I don't have access to the device for the moment.

The script that I link in my first post call OID .1.3.6.1.4.1.14851  I found this MIB:

[SNIA-SML-MIB.mib.txt](https://github.com/centreon/centreon-plugins/files/3478099/SNIA-SML-MIB.mib.txt)

In the script they call this OID:
[oid.txt](https://github.com/centreon/centreon-plugins/files/3478112/oid.txt)

Hope this help for the moment

**Comment by garnier-quentin** [comment]
I can wait for the snmpwalk

**Comment by garnier-quentin** [comment]
Do you have some news ?

**Comment by garnier-quentin** [comment]
I think we can close it. If you have the snmpwalk (or someone else), please post it here.
