### ISSUE TITLE
common::cisco::standard::snmp::mode::memory  Illegal division by zero on cisco WS-C6513-E (R7000)

### ISSUE THREAD

**Issue by troja89** [centreon/centreon-plugins#1593]
I am trying to monitor memory on cisco WS-C6513-E (R7000) Version 12.2(17r)SX7 with the plugin common::cisco::standard::snmp::mode::memory but I am getting the following error:

UNKNOWN: could not run '/usr/lib/nagios/plugins/centreon_plugins.pl': Illegal division by zero at /usr/lib/nagios/plugins//centreon/common/cisco/standard/snmp/mode/memory.pm line 87. at /tmp/centreon_connector_perl.ExVDi5 line 86.

When I monitor memory cisco WS-C6509-E (R7000) Version 12.2(17r)SX7, the plugin works perfectly, so the issue seems to only affect WS-C6513-E.

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk of following OID ?
```
.1.3.6.1.4.1.9.9.109.1.1.1.1
.1.3.6.1.4.1.9.9.221.1.1.1.1
.1.3.6.1.4.1.9.9.305.1.1.2
.1.3.6.1.4.1.9.9.48.1.1.1
``

**Comment by troja89** [comment]
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/3421882/snmpwalk.txt)
Thank you for your quick reply!
I have added the snmpwalk output as an attachement to this comment.

**Comment by garnier-quentin** [comment]
Could you also provide me snmpwalk of following branch ?
```
.1.3.6.1.2.1.47.1.1.1.1
```

**Comment by troja89** [comment]
[snmpwalk_additional.txt](https://github.com/centreon/centreon-plugins/files/3421944/snmpwalk_additional.txt)
Here is the additional snmpwalk

**Comment by garnier-quentin** [comment]
Could you test it with the last version ?

**Comment by troja89** [comment]
Thank you! It works perfectly now!
