### ISSUE TITLE
Office365 refuse connection

### ISSUE THREAD

**Issue by markeur** [centreon/centreon-plugins#1594]
##Question.
Hi,
I want to use the office365 management plugin but the connection is always refuse.
I have added centreon and generated a client_id and secret_id for it. Moreover I added those permissions on office365: 

* Reports.Read.All
* User.Read
* ServiceHealth.Read
* ActivityFeed.Read

Have I miss a permisson or somethink else?

Thank for your help

**Comment by wackou72** [comment]
Hello @markeur 
I just manage to have the plugin work on my side.
I follow this guide : 
https://www.lee-ford.co.uk/get-latest-office-365-service-status-with-flow-or-powershell/

About the API permission, its configured as the following : 

Microsoft Graph : 
- Reports.Read.All (Type : Application)
- User.Read (Type : Delegated)

Office 365 Management APIs :
- ServiceHealth.Read  (Type : Application)
- ActivityFeed.Read (Type : Application)

**Comment by markeur** [comment]
Hello @wackou72 , 
Thank you for your help I will take a look on that.

**Comment by cgagnaire** [comment]
Hi @markeur,
Did you manage to resolve your problem?
Thanks.

**Comment by markeur** [comment]
Hello @cgagnaire, 
Definitely not

**Comment by UrBnW** [comment]
Also see #2075.

**Comment by garnier-quentin** [comment]
Tell us if you still have the issue.
