### ISSUE TITLE
Zscaler GRE Tunnel monitoring

### ISSUE THREAD

**Issue by markeur** [centreon/centreon-plugins#1595]
Hi, 
is it possible for centreon to monitor Zscaler GRE Tunnel.

Thanks

**Comment by garnier-quentin** [comment]
Maybe. There is an API ? HTTP Rest for example to test the status ?

**Comment by markeur** [comment]
Thank you for your fast answer, it seems that an API is existing (https://help.zscaler.com/zia/api)  but seems not usefull  for that. I also find that in the the zscaler documentation : https://help.zscaler.com/zia/sd-wan-api-integration

**Comment by garnier-quentin** [comment]
Maybe you could ask to your zscaler support.

**Comment by garnier-quentin** [comment]
I found nothing useful in API. You can add a comment and will open it if you have some news of zscaler support.
