### ISSUE TITLE
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.

### ISSUE THREAD

**Issue by viaDomitia** [centreon/centreon-plugins#1597]
Hello,

Trying to use printer-error mode on hardware::printers::standard::rfc3805::plugin but having "Use of uninitialized value" 

./centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=printer-error --hostname=xxx.22.18.xxx --snmp-community=XXXXXX_RO --snmp-version=v2c --verbose
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
Use of uninitialized value $value in bitwise and (&) at /usr/lib/centreon/plugins/snmp_standard/mode/printererror.pm line 128.
OK: Printer '1' status is 'ok' |
checking printer '1'
    status is 'ok'

No more information with --debug
N.B. : No problem with other modes though (cover-status, markersupply-usage....)

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk ?
```
snmpwalk -ObentU -v 2c -c public IP .1 > printer.snmpwalk
```

**Comment by viaDomitia** [comment]
Hello,

File printer.snmpwalk attached (some datas have been anonymized).
Thanks.

[printer.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/3440620/printer.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
Could you test it with the last version ?

**Comment by viaDomitia** [comment]
Test is successful 👍 
./centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=printer-error --hostname=xxx.22.18.xxx --snmp-community=XXXXXX_RO --snmp-version=v2c --verbose

OK: Printer '1' status is 'ok' |
checking printer '1'
    status is 'ok'

Thank you !

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
