### ISSUE TITLE
[database::mysql::plugin] Can't call method "errstr"

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#1598]
Hi, 

I have an error with sql mode on mysql plugin. I don' understand why. Could you help me ?

Thanks,

 /usr/local/nagios/libexec/centreon-plugins/centreon_plugins.pl --plugin=database::mysql::plugin --mode=sql --host=192.168.x.x --port=3306 --username=LOGIN --password=MYPASS --warning= --critical= --sql-statement="SELECT count(*) FROM news"

UNKNOWN: Can't call method "errstr" on an undefined value at /usr/local/nagios/libexec/centreon-plugins/centreon/plugins/dbi.pm line 289.

**Comment by garnier-quentin** [comment]
Have you tested with the last git ?

**Comment by romsworld** [comment]
Hi

In fact i forgot database parameters.

Thanks

Télécharger Outlook pour Android<https://aka.ms/ghei36>




On Thu, Aug 1, 2019 at 4:03 PM +0200, "qgarnier" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1598<https://github.com/centreon/centreon-plugins/issues/1598>.
