### ISSUE TITLE
[plugin] Cisco environment with nexus

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon-plugins#160]
Hi,

The plugin environment check perfectly temperature for Catalyst but for the nexus platform the counter is not monitored by this plugin.

is it possible to add this option?

Many thanks.

**Comment by garnier-quentin** [comment]
Hi,

It should. I think snmp oids are not set. Could you do a walk ?
.1.3.6.1.4.1.9.9.13.1.3.1

You don't have same for catalyst and nexus.

**Comment by tcheval** [comment]
Hi,

The OID .1.3.6.1.4.1.9.9.13.1.3.1 do not exist on Nexus platform ;(

Nexus use CISCO-ENTITY-SENSOR-MIB only for this counter.

Exemple on a Nexus 5000 with Nexus 2000 :

snmpwalk -c njh_iafl -v 2c name .1.3.6.1.4.1.9.9.91.1.1.1.1.4
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.21590 = INTEGER: 30
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.101021590 = INTEGER: 35
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.101021591 = INTEGER: 38
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.101021592 = INTEGER: 38
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.101021593 = INTEGER: 44
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.102021590 = INTEGER: 34
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.102021591 = INTEGER: 36
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.102021592 = INTEGER: 36
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.102021593 = INTEGER: 43
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.103021590 = INTEGER: 35
SNMPv2-SMI::enterprises.9.9.91.1.1.1.1.4.103021591 = INTEGER: 39

And the entPhysicalDescr for the name of module :

snmpwalk -c njh_iafl -v 2c name .1.3.6.1.2.1.47.1.1.1.1.2.21590
SNMPv2-SMI::mib-2.47.1.1.1.1.2.21590 = STRING: "Module-1, Outlet"
snmpwalk -c njh_iafl -v 2c name .1.3.6.1.2.1.47.1.1.1.1.2.101021590
SNMPv2-SMI::mib-2.47.1.1.1.1.2.101021590 = STRING: "Fex-101 Module-1 Outlet-1"
snmpwalk -c njh_iafl -v 2c name .1.3.6.1.2.1.47.1.1.1.1.2.101021591
SNMPv2-SMI::mib-2.47.1.1.1.1.2.101021591 = STRING: "Fex-101 Module-1 Outlet-2"
snmpwalk -c njh_iafl -v 2c name .1.3.6.1.2.1.47.1.1.1.1.2.101021592
SNMPv2-SMI::mib-2.47.1.1.1.1.2.101021592 = STRING: "Fex-101 Module-1 Inlet-1"
snmpwalk -c njh_iafl -v 2c name .1.3.6.1.2.1.47.1.1.1.1.2.101021593
SNMPv2-SMI::mib-2.47.1.1.1.1.2.101021593 = STRING: "Fex-101 Module-1 Die-1"

Do you want a walk extraction for both tables?
Cisco simplicity... :(

Thanks.

**Comment by garnier-quentin** [comment]
Yes. Could be useful. I'll add sensors component

**Comment by tcheval** [comment]
I sent the file by mail.

Thanks.
