### ISSUE TITLE
[apps::protocols::http::plugin] - critical-status don't work or syntax error

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1600]
Hi,

I try to check response of webservice.
basically, if my webservice return http_code=405 I consider it works.

I try to check with the syntax below  but don't work. anything http_code define return OK
like this: `--critical-status='%{http_code} <> 405'`

`/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=domain-name --proto='https' --port='443' --urlpath='/path' --proxyurl=''  --username='' --password='' --warning='3' --critical='10'  --critical-status='%{http_code} <> 405' --debug --verbose`

but whatever the value entered (200, 403, 404, etc...) the answer is every time the same:

> OK: Response time 0.098s
> {"timestamp":1564497242345,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'GET' not supported","path":"/telecollect/ca"}

If I try without "--critical-status" option, the plugin return a critical state because it's over the default range

> CRITICAL: 405 Method Not Allowed |
> {"timestamp":1564498221328,"status":405,"error":"Method Not Allowed","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'GET' not supported","path":"/telecollect/ca"}

So it seems don't work correctly with option "--critical-status".
It's a bug or I make a mistake in the syntax?

regards

**Comment by CPbN** [comment]
You should write :
`--critical-status='%{http_code} != 405'`

**Comment by cmeschin** [comment]
Hi, @CPbN 
it works thank you.
