### ISSUE TITLE
[network::citrix::netscaler::snmp::plugin] - Wrong threshold-overload option

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1604]
Plugins 20190704

Citrix Netscaler mode ha-state, vserver-status are not working using --threshold-overload option:
`UNKNOWN: Wrong threshold-overload option ''.`

**Comment by garnier-quentin** [comment]
We need to refactor it.

**Comment by garnier-quentin** [comment]
Could you test with last version ?
