### ISSUE TITLE
[centreon_linux_snmp.pl] Unknown option mode swap

### ISSUE THREAD

**Issue by tibodf** [centreon/centreon-plugins#1605]
## Bug
Hi,
Yesterday, I upgraded Centreon from 3.4.0 (CentOS 6) to 19.04.0 (CentOS 7).
For the moment, all is working well except one command.

With the script "centreon_linux_snmp.pl" and the mode "swap" I got the following error:
- Unknown option: warning-usage-prct at /usr/lib/centreon/plugins/centreon_linux_snmp.pl line 141.

The full command used by centreon (from the plugin pack):
 - centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=swap --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning-usage-prct='$_SERVICEWARNING$' --critical-usage-prct='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$

I can't find if it's a known issue.

**Comment by garnier-quentin** [comment]
Please upgrade the plugin also.

**Comment by LLFT** [comment]
Hello,
the same for me, these settings are no longer supported by the script /usr/lib/centreon/plugins/centreon_linux_snmp.pl
But the "OS-Linux-SNMP-SWAP" verification command always uses these parameters:

`$CENTREONPLUGINS$/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=swap --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning-usage-prct='$_SERVICEWARNING$' --critical-usage-prct='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$`

and as it is a command delivered with centreon it is not editable.
