### ISSUE TITLE
[database::oracle::plugin] Password expiration issue

### ISSUE THREAD

**Issue by Psych0meter** [centreon/centreon-plugins#1606]
Hi,

I've just tried the password-expiration mode, and it seems that there is a DB disconnection problem.
When I run the plugin, I have the following error :

```
/usr/lib/centreon/plugins/centreon_oracle.pl --plugin=database::oracle::plugin --hostname=HOST --port=PORT --servicename=SERVICE --username=USERNAME--password=PASSWORD --mode=password-expiration --warning-status "%{expire} < (86400 * 21)"
UNKNOWN: Can't call method "disconnect" on an undefined value at /usr/lib/centreon/plugins/centreon_oracle.pl line 8284.
```

Line 8284 :  `$self->{sql}->disconnect();`
I've commented the line, and it works
I've also tries to replace the line with `$options{sql}->disconnect(); `and it also works.

Regards,

**Comment by garnier-quentin** [comment]
Thanks for the feedback. It should be fixed
