### ISSUE TITLE
os::linux::snmp::plugin how to ignore remote filesystems

### ISSUE THREAD

**Issue by cemir** [centreon/centreon-plugins#161]
Hi,

how can one ignore remote filesystems using this plugin ?

I'm trying to monitor inodes on all my servers but some filesystems (including but not limited to home directories) are mounted via nfs on a Solaris machine (wich uses ZFS, so no inode limit)

So monitoring only the local filesystems will do the trick, but there is no options like that we can specify when calling the plugin.

Any ideas ?

Regards,
Cemir

**Comment by garnier-quentin** [comment]
Hi,

Which mode do you use ? You can use negative regexp like that: --name='^(?!(/home)$)'

Best regards,

**Comment by cemir** [comment]
Hi,

thanks for your answer,

That's what I did as a temporary workaround but some others filesystems could also have the same issue. As I have 300+ linux server to monitor, I should deploy a global solution. I know there is such an option for os:linux:local but not for os:linux:snmp.

Will this ever be possible or should I implement something based on "df" command ?

here is the full command I use :

$USER3$/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=inodes --hostname=$HOSTNAME$ --snmp-version=2c --snmp-community=specOPOCE --warning 80 --critical 90 --name --regexp --diskpath='^(?!(/proc.*|/sys|/dev/pts|/var/lib/nfs/rpc_pipefs|/sys/kernel/debug|/net/.*|/sys/kernel/config|/dev/.*|/home/.*)$$)' --verbose


Regards,

**Comment by garnier-quentin** [comment]
I don't think i can have the type of the partition for the mode 'inodes'. There is no information for that in 'dskTable'.

**Comment by garnier-quentin** [comment]
If you find the information in snmp mib. Please re-open it.
