### ISSUE TITLE
[hardware::server::dell::idrac::snmp::mode::components::amperage] Wrong unit  on  'amperage_System Board Pwr Consumption'

### ISSUE THREAD

**Issue by stephanemarianne** [centreon/centreon-plugins#1611]
[hardware::server::dell::idrac::snmp::mode::components::amperage] 
Wrong unit W or incorrect value calculation for  'amperage_System Board Pwr Consumption'
In the exemple below the 'amperage_System Board Pwr Consumption' is returned by Centreon with 0.396W when in reality it is announced by our ESX tools as 396W.
can you please check this?

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --hostname=XXXXXXX --mode=hardware
OK: All 150 components are ok [3/3 amperages, 16/16 cooling devices, 1/1 cooling units, 32/32 fru, 24/24 memories, 4/4 networks, 15/15 pci, 2/2 physical disks, 2/2 processors, 2/2 power supplies, 1/1 power units, 2/2 slots, 1/1 storage batteries, 1/1 storage controllers, 2/2 system batteries, 4/4 temperatures, 1/1 virtual disks, 37/37 voltages]. | 'temp_CPU1 Temp'=59C;0:;3:95;; 'temp_CPU2 Temp'=65C;0:;3:95;; 'temp_System Board Inlet Temp'=20C;3:43;-7:47;; 'temp_System Board Exhaust Temp'=45C;8:75;3:80;; 'voltage_PS1 Voltage 1'=232V;0:;0:;; 'voltage_PS2 Voltage 2'=232V;0:;0:;; 'amperage_PS1 Current 1'=1A;0:;0:;; 'amperage_PS2 Current 2'=0.8A;0:;0:;; '**amperage_System Board Pwr Consumption'=0.396W;0:1.166;0:1.298;**; 'fan_System Board Fan1A'=7200rpm;0:;60:;; 'fan_System Board Fan1B'=5760rpm;0:;60:;;

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk of following branch ?
```
.1.3.6.1.4.1.674.10892.5.4.600.30.1
```

**Comment by garnier-quentin** [comment]
Ok i have fixed it. Could you test ?

**Comment by stephanemarianne** [comment]
I tested the patch and the value is now correct.

But I note that the establishment of an alert threshold is limited to "Pwr Consumption (W)" because it applies equally to the values "amperage PS1-2 (A)" and "Pwr Consumption (W)".
In this case the alert will be relevant (in the case of a 430Watts threshold)
 If I want to set an alert threshold of 2Amps on PS amperage, there will be an alert directly on the Power Consumption....

Can you tell me how to proceed in this case?

exemple: 
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --hostname=XXXXXXX --mode=hardware --component=amperage --critical='amperage,.*,**430**' --warning='amperage,.*,**420**'
OK: All 3 components are ok [3/3 amperages]. | 'amperage_PS1 Current 1'=1.8A;0:420;0:430;; 'amperage_PS2 Current 2'=0.2A;**0:420;0:430**;; 'amperage_System Board Pwr Consumption'=374W;**0:420;0:430**;;

**Comment by garnier-quentin** [comment]
You can use the instance value. You can get the instance value with --verbose value
```
--critical='amperage,10,430' 
```

**Comment by stephanemarianne** [comment]
Thank you for your help
it works well.

**Comment by garnier-quentin** [comment]
You're welcome @stephanemarianne . Thanks for the feedback
