### ISSUE TITLE
PineApp SecureMail

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#1613]
Hi, I just discover this appliance today: PineApp SecureMail : http://www.cybonet.com/en/products/mail-secure

Here a existing script in Perl: https://github.com/ranl/monitor-utils/blob/master/nagios/check-pineapp.pl

And here the MIB: [PINEAPP.MIB.txt](https://github.com/centreon/centreon-plugins/files/3478383/PINEAPP.MIB.txt)

Interesting OID:

Services: 
smtpservicestatus   .1.3.6.1.4.1.19801.2.1.1.0 = INTEGER: 1
pop3servicestatus   .1.3.6.1.4.1.19801.2.1.2.0 = INTEGER: 1
imap4servicestatus  .1.3.6.1.4.1.19801.2.1.3.0 = INTEGER: 1
antivirusservicestatus  .1.3.6.1.4.1.19801.2.5.1.0 = INTEGER: 1

Disk:
storage  .1.3.6.1.4.1.19801.1.4.0 = STRING: "OK"

Queue
mailsysteminboundqueue  .1.3.6.1.4.1.19801.2.1.10.1.0 = INTEGER: 0
mailsystemoutboundqueue  .1.3.6.1.4.1.19801.2.1.10.2.0 = INTEGER: 1
mailQueueHigh .1.3.6.1.4.1.19801.2.1.10.3.1.0 = INTEGER: 0
mailQueueNormal .1.3.6.1.4.1.19801.2.1.10.3.2.0 = INTEGER: 0
mailQueueLow .1.3.6.1.4.1.19801.2.1.10.3.3.0 = INTEGER: 0
mailQueueTotal .1.3.6.1.4.1.19801.2.1.10.3.4.0 = INTEGER: 0

CPU 
cpuload1minavg .1.3.6.1.4.1.19801.1.1.3.1.0 = STRING: "0.08"
cpuload5minavg .1.3.6.1.4.1.19801.1.1.3.2.0 = STRING: "0.05"
cpuload15minavg .1.3.6.1.4.1.19801.1.1.3.3.0 = STRING: "0.05"

I will try to convert it into Centreon-plugin (if I can)
https://github.com/rk4an/centreon-plugins/blob/master/apps/pineapp/securemail/

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by rk4an** [comment]
Yes it's works!

Thanks :)
