### ISSUE TITLE
[apps::java::jboss::jmx::plugin] - mode datasources not working

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1614]
Plugins 20190420
Java 7
JBoss 7.1.1
Jolokia 1.6.2

```
./centreon_plugins.pl   --plugin=apps::java::jboss::jmx::plugin --mode=list-datasources --url='http://x.x.x.x:9000/jolokia/' --debug
List data sources:
```

```
./centreon_plugins.pl   --plugin=apps::java::jboss::jmx::plugin --mode=datasource-usage --url='http://x.x.x.x:9000/jolokia/' --debug
UNKNOWN: JMX Request: Cant get a single value.
```

Jolokia seem's working correctly, other JMX checks are working. Any idea about them?

**Comment by garnier-quentin** [comment]
I need the result of list-attributes (apps::protocols::jmx)

**Comment by joschi99** [comment]
Here you will find the zip file containing the complete output. File is password protected. I send you the PWD by mail.
[jboss.zip](https://github.com/centreon/centreon-plugins/files/3481686/jboss.zip)

**Comment by garnier-quentin** [comment]
I have looked and there is no statistics:
```
jboss.as:data-source=LiferayPool,subsystem=datasources -- reauthPluginProperties = undef
jboss.as:data-source=LiferayPool,subsystem=datasources -- exceptionSorterClassName = undef
jboss.as:data-source=LiferayPool,subsystem=datasources -- statistics = ERROR: JBAS014640: 'statistics' is a registered child of resource ([
    ("subsystem" => "datasources"),
    ("data-source" => "LiferayPool")
]) (class javax.management.AttributeNotFoundException)
jboss.as:data-source=LiferayPool,subsystem=datasources -- blockingTimeoutWaitMillis = 1000
```

It seems we need to use the management API: https://developer.jboss.org/thread/250438
If you can get the data with the HTTP API, i could develop a new plugin: https://docs.jboss.org/author/display/AS71/The+HTTP+management+API

**Comment by garnier-quentin** [comment]
I close it without news.
