### ISSUE TITLE
apps::iis::local::plugin mode webservice-statistics fail with cnetreon-plugin.exe

### ISSUE THREAD

**Issue by bernah4** [centreon/centreon-plugins#1616]
Hi,

I have made the centreon plugin.exe from the doc for checking my windows iis.
All check are ok execpt the webservice-statistics that return 

![image](https://user-images.githubusercontent.com/46378129/62782910-7cfb3780-babb-11e9-8530-1fb17273c667.png)

It is local check and i do not think that windows get some unix folder, but i could be wrong.
Is anybody get that problem before?

Thanks :)

ps: same results on win2008 server/2012/2016

**Comment by garnier-quentin** [comment]
Please set the option --statefile-dir option. For example --statefile-dir=C:/Temp/

**Comment by bernah4** [comment]
Thanks it works far better with a correct path !
