### ISSUE TITLE
[os:windows:snmp:mode:service] - Question: only display name?

### ISSUE THREAD

**Issue by harbourlad** [centreon/centreon-plugins#1617]
Hi all,
i wonder if I really can only search for the display name of services within the Windows SNMP plugin. Because the differ between different languages or Versions of the OS. For Example: The Printer Spooler Service: It's Original name is just "Spooler" - It#s Display name differs: In German it is "Druckerwarteschlange", In Englich sometimes "Print Spooler" or "Printer Spooler" or just "Spooler" (depends of the OS version). So it is hard to define one template for all of this possibilities if I only can match against the Display name. Is there a possipility to match against the original Servicename? 
![grafik](https://user-images.githubusercontent.com/53009252/62931206-36108900-bdbe-11e9-92e0-9816a72f8319.png)

**Comment by garnier-quentin** [comment]
SNMP provides only that name (http://oidref.com/1.3.6.1.4.1.77.1.2.3.1). You need to use nsclient maybe.
