### ISSUE TITLE
[os::windows::snmp::plugin] Windows Server 2019: Cannot check services

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1618]
Hello guys,

I have some new Windows Serer 2019 installed and now I wanted to check some services on the servers. But when I run following command:
`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=SERVER --snmp-version='2c' --snmp-community='public'  --service='Sap' --warning= --critical=2:2 --state='' --regexp`

I get this error:
> UNKNOWN: SNMP Table Request : (genError) A general failure occured

I need these checks. Does anyone know what's the problem? Is it the plugin or the SNMP service on my Windows Server?

Thank you!
Best regards, Michael

EDIT: All other checks are working.

**Comment by garnier-quentin** [comment]
Could you try option --snmp-autoreduce ?

**Comment by MikeW83** [comment]
Doesn't help... Same message:
` /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=SERVER --snmp-version='2c' --snmp-community='public'  --service='Sap' --warning= --critical=2:2 --state='' --regexp --verbose --snmp-autoreduce`

> UNKNOWN: SNMP Table Request : (genError) A general failure occured

**Comment by garnier-quentin** [comment]
That's a bug of snmp windows agent. You should try to use nsclient.

**Comment by MikeW83** [comment]
> 
> 
> That's a bug of snmp windows agent. You should try to use nsclient.

That's not the best solution for us but thank you for your research. Do you know if the bug will be resolved by Microsoft?

**Comment by garnier-quentin** [comment]
Windows SNMP Agent is deprecated by Microsoft since Windows 2012... I think they don't care
