### ISSUE TITLE
os::linux::snmp::plugin --mode=memory issue on RHEL7

### ISSUE THREAD

**Issue by fredmarchal** [centreon/centreon-plugins#1620]
Hi,

There is a strange behaviour running the SNMP memory check to a RHEL7 server.
The "memory used" value is negative.

It seems that the value of "memory available" retrieved by net-snmp doesn't represent the same on RHEL6 and RHEL7. If it's the case, these value should not be used in the same way in the calculation of the used memory.

Please see bellow some details.

disclaimer : in the following information, the servers are running without swap space by design.

### RHEL6

**From centreon server**

```
$ /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=RHEL6 --snmp-version='3' --snmp-community='' --snmp-username=***** --authprotocol=*** --authpassphrase='******' --privprotocol=*** --privpassphrase='***********' --warning-usage='80' --critical-usage='90'
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
OK: Ram Total: 7.69 GB Used (-buffers/cache): 656.92 MB (8.34%) Free: 7.05 GB (91.66%), Buffer: 466.31 MB, Cached: 4.41 GB, Shared: 0.00 B | 'used'=688832512B;;;0;8254689280 'free'=7565856768B;;;0;8254689280 'used_prct'=8.34%;0:80;0:90;0;100 'buffer'=488964096B;;;0; 'cached'=4739432448B;;;0; 'shared'=0B;;;0;
```
```
$ snmpwalk -v3 -l authPriv -u ****** -a *** -A '*******' -x *** -X '******' -O S RHEL6 .1.3.6.1.4.1.2021.4
UCD-SNMP-MIB::memIndex.0 = INTEGER: 0
UCD-SNMP-MIB::memErrorName.0 = STRING: swap
UCD-SNMP-MIB::memTotalSwap.0 = INTEGER: 0 kB
UCD-SNMP-MIB::memAvailSwap.0 = INTEGER: 0 kB
UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 8061220 kB
UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 2279572 kB
UCD-SNMP-MIB::memTotalFree.0 = INTEGER: 2279572 kB
UCD-SNMP-MIB::memMinimumSwap.0 = INTEGER: 16000 kB
UCD-SNMP-MIB::memBuffer.0 = INTEGER: 478164 kB
UCD-SNMP-MIB::memCached.0 = INTEGER: 4628372 kB
UCD-SNMP-MIB::memSwapError.0 = INTEGER: error(1)
UCD-SNMP-MIB::memSwapErrorMsg.0 = STRING: Running out of swap space (0)
```

**On RHEL6 server**
```
$ free -m
             total       used       free     shared    buffers     cached
Mem:          7872       5646       2226         22        466       4519
-/+ buffers/cache:        659       7212
Swap:            0          0          0
```
check /proc/meminfo here : [RHEL6_proc_meminfo.txt](https://github.com/centreon/centreon-plugins/files/3524271/RHEL6_proc_meminfo.txt)

net-snmp version 5.5-60.el6

### RHEL7

**From centreon server**

Result : Used : **-69.48 % | 'used'=-5698752512B;;;0;8201641984**

```
$ /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=RHEL7 --snmp-version='3' --snmp-community='' --snmp-username=***** --authprotocol=*** --authpassphrase='********' --privprotocol=*** --privpassphrase='******' --warning-usage='80' --critical-usage='90'
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
CRITICAL: Used : -69.48 % | 'used'=-5698752512B;;;0;8201641984 'free'=13900394496B;;;0;8201641984 'used_prct'=-69.48%;0:80;0:90;0;100 'buffer'=153985024B;;;0; 'cached'=5779050496B;;;0; 'shared'=11087872B;;;0;
```

```
$ snmpwalk -v3 -l authPriv -u ***** -a *** -A '*******' -x *** -X '******' -O S RHEL7 .1.3.6.1.4.1.2021.4
UCD-SNMP-MIB::memIndex.0 = INTEGER: 0
UCD-SNMP-MIB::memErrorName.0 = STRING: swap
UCD-SNMP-MIB::memTotalSwap.0 = INTEGER: 0 kB
UCD-SNMP-MIB::memAvailSwap.0 = INTEGER: 0 kB
UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 8009416 kB
UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 7780456 kB
UCD-SNMP-MIB::memTotalFree.0 = INTEGER: 7780456 kB
UCD-SNMP-MIB::memMinimumSwap.0 = INTEGER: 16000 kB
UCD-SNMP-MIB::memShared.0 = INTEGER: 10828 kB
UCD-SNMP-MIB::memBuffer.0 = INTEGER: 150732 kB
UCD-SNMP-MIB::memCached.0 = INTEGER: 5643660 kB
UCD-SNMP-MIB::memSwapError.0 = INTEGER: error(1)
UCD-SNMP-MIB::memSwapErrorMsg.0 = STRING: Running out of swap space (0)
```

**On RHEL7 server**

```
$ free -k
              total        used        free      shared  buff/cache   available
Mem:        8009416      234912     1980336       10892     5794168     7457696
Swap:             0           0           0
```
check /proc/meminfo here : [RHEL7_proc_meminfo.txt](https://github.com/centreon/centreon-plugins/files/3524265/RHEL7_proc_meminfo.txt)

net-snmp version 5.7.2-43.el7

### Centreon server

Centreon 3.4 on RHEL6, up to date (Centreon Engine 1.8.1, Centreon 2.8.28)
Plugins : centreon-plugin-Operatingsystems-Linux-Snmp-20190704-123459.el6.noarch

**Comment by garnier-quentin** [comment]
We are working on it. For the warn message, you can use following option: 
--ignore-warn-msg

For the negative value, in red-hat 7.7, redhat team integrated a patch that changed ucd snmp values...

**Comment by cgagnaire** [comment]
Hi @fredmarchal,
Thanks for opening this issue.
We've been aware of this behaviour recently from different inputs.
We're handling it now by providing a --redhat option (see https://github.com/centreon/centreon-plugins/commit/c015f186fd0dafb01908fca124bc3add0e0ff391).

**Comment by gbloquel** [comment]
Hi @cgagnaire @garnier-quentin 

I have the trouble as @fredmarchal 
Thanks for your fix but it seems difficult to set up.

Before your plugin os::linux::snmp::plugin  was generic for all os familly(Debian, Redhat,..) and generic for all versions of net-snmp
With your fix 
- you added the notion of os family in the implementation 
- we must identify all hosts with net-snmp >= 5.7.2-43.el7 and the os familly "Redhat", if this case then added the flag "--redhat" otherwise lease as currently. 

Did  I understand your fix and its implementation ?

@garnier-quentin Are you working in an other fix ?

**Comment by garnier-quentin** [comment]
Yes you understand. I'd like to do something. But it seems i cannot. Maybe with the sysdesc. that patch is a mess. red-hat broke the compatibility.

**Comment by garnier-quentin** [comment]
I added an option --autodetect-redhat. You can set it. It can help to detect. But it's not 100% safe.

**Comment by gbloquel** [comment]
Hi @garnier-quentin,

Thanks for your new reply.
I've studied your fix [--autodectect-redhat](https://github.com/centreon/centreon-plugins/commit/a2b2495c837ced030e9834f94e406709e649ff02).
If I understand you get the kernel version to conclude that is a Redhat 7.7. I agree but it solve only a part of problem.

But I my case a part of my hosts Centos 7.x have updated the RPM net-snmp to 5.7.2-43.el7 because the repository Centos Base is the same.

**Comment by garnier-quentin** [comment]
It's not a perfect fix. But usually you update the whole system (most of the time). I know you can update only net-snmp. But i can't get the net-snmp version :(

**Comment by fredo1988** [comment]
Hi there,
one matter with this option, the result is different with --redhat : 

-bash-4.2$ /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=xx.xx.xx.xx --snmp-version='xx' --snmp-community='xxxxxxxxxxxx-'  --warning-usage='80' --critical-usage='90'
OK: Ram Total: 7.08 GB Used (-buffers/cache): 794.04 MB (10.95%) **Free: 6.31 GB (89.05%)**, Buffer: 116.11 MB, Cached: 363.91 MB, Shared: 240.00 KB | 'used'=832606208B;;;0;7603716096 'free'=6771109888B;;;0;7603716096 'used_prct'=10.95%;0:80;0:90;0;100 'buffer'=121749504B;;;0; 'cached'=381583360B;;;0; 'shared'=245760B;;;0;


-bash-4.2$ /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=xx.xx.xx.xx  --snmp-version='xx' --snmp-community='xxxxxxxxxxxx-'  --warning-usage='80' --critical-usage='90' **--redhat**
OK: Ram Total: 7.08 GB Used (-buffers/cache): 1.24 GB (17.57%) **Free: 5.84 GB (82.43%)**, Buffer: 116.12 MB, Cached: 363.91 MB, Shared: 240.00 KB | 'used'=1335947264B;;;0;7603716096 'free'=6267768832B;;;0;7603716096 'used_prct'=17.57%;0:80;0:90;0;100 'buffer'=121757696B;;;0; 'cached'=381583360B;;;0; 'shared'=245760B;;;0;

Why?

**Comment by cgagnaire** [comment]
Hi,

That's the all point of this option : 
```
--redhat

    If using RedHat distribution with net-snmp >= 5.7.2-43.

    This version: used = memTotalReal - memAvailReal // free = memAvailReal

    Others versions: used = memTotalReal - memAvailReal - memBuffer - memCached // free = total - used

    (grep for '##' in this mode for more informations)
```

**Comment by lesijac** [comment]
yes but is it possible to forced the same result with no option --redhat when we use --redhat option?
