### ISSUE TITLE
[database::mysql::plugin] - --mode=threads-connected - compatibility mysql 5.6

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1621]
Hi,
Yesterday, I've updated centreon-plugins and I've got this error on hosts with mysql 5.7.x

> UNKNOWN: Cannot execute query: The 'INFORMATION_SCHEMA.GLOBAL_STATUS' feature is disabled: see the documentation for 'show_compatibility_56'

The plugin works fine on mysql servers release 5.6.x
I can fix it by add this option in mysql conf:
`show_compatibility_56 = On;`
The problem is I must change mysql configuration on all running servers. Its a little bit heavy :)
And on all new mysql servers who migrate on newer release

There is a possibility to manage that directly in the plugin?
thanks for your help.

**Comment by garnier-quentin** [comment]
Could you test with last git version ? It's fixed.

**Comment by cmeschin** [comment]
Ok, it works.
