### ISSUE TITLE
network::dell::sseries::snmp::plugin --> Hardware & CPU Unknow

### ISSUE THREAD

**Issue by houstek** [centreon/centreon-plugins#1623]
Hi,
it seems to me that the mib switch Dell SSeries has evolved.
Attached an SNMPWALK from a Dell S3048 Switch
[dell_sseries.zip](https://github.com/centreon/centreon-plugins/files/3530287/dell_sseries.zip)

**Comment by garnier-quentin** [comment]
I have take a look but some parts are missing. I need following branch:
.1.3.6.1.4.1.6027.3.26.1

**Comment by garnier-quentin** [comment]
I think it's maybe an os10 operating system. You can test with: --plugin=network/dell/os10/snmp/plugin.pm
