### ISSUE TITLE
network::fortinet::fortigate - only check regular IPS-Signatures are checked

### ISSUE THREAD

**Issue by harbourlad** [centreon/centreon-plugins#1624]
network::fortinet::fortigate::plugin --mode=signatures

Hi All,
I noticed  that the plugin seems to check only the regular IPS-Signatures, not the extended ones. 
Since Fortigate only updates the extended signatures if this feature is enabled, the plugin produces warnings and alarms even though the signatures are up-to-date. 
![grafik](https://user-images.githubusercontent.com/53009252/63671536-014dfa00-c7e0-11e9-8e24-18060993b8aa.png)

**Comment by harbourlad** [comment]
This is the according output by the plugin:
![grafik](https://user-images.githubusercontent.com/53009252/63672238-d2d11e80-c7e1-11e9-9787-c639d645780e.png)

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk ? (you can sent it by email) 
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4 > fortigate.snmpwalk

**Comment by harbourlad** [comment]
It's on the way - I used "**network::fortinet::fortigate - only check regular IPS-Signatures are checked #1624**" as mail-subject

**Comment by harbourlad** [comment]
I think I found some matching entries:
![grafik](https://user-images.githubusercontent.com/53009252/63673280-3fe5b380-c7e4-11e9-8100-665545b9ac6f.png)

**Comment by garnier-quentin** [comment]
Have you tested with last version ? https://github.com/centreon/centreon-plugins/commit/7c7037861f339d2ea2c95db5b7361e51b7ba4f82#diff-600e0ab92a5694a6506bdf45271c127e

Because we test extended now. Maybe we test the extended only if it exists ?

**Comment by garnier-quentin** [comment]
Maybe i can add an option to check only the extended value if it exists (not: "0.00000(2001-...").

**Comment by harbourlad** [comment]
I will test the new version. In the meantime I just changed the line 1761 from 
`my $oid_fgSysVersionIps = '.1.3.6.1.4.1.12356.101.4.2.2.0';`
to 
`my $oid_fgSysVersionIps = '.1.3.6.1.4.1.12356.101.4.2.4.0';`
and it works fine for us.

I think both entries exist at all times. But only one signature set is updated - depending on the configuration within the fortigate

**Comment by harbourlad** [comment]
The Update works fine. 
However - the new possibilities should be mentioned within the possible settings:
`=item B<--critical-*>

Threshold critical (in seconds).
Can be: 'av', 'avet' 'ips', 'ipset' `

**Comment by garnier-quentin** [comment]
Thank you for the feedback!!
