### ISSUE TITLE
[cisco::standard] Environment with c9300 series

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon-plugins#1625]
Better manage sensors vs. components in c9300 switches series.

Refs: https://github.com/centreon/centreon/issues/7718

**Comment by Jassj89** [comment]
[9300-24T.txt](https://github.com/centreon/centreon-plugins/files/3541225/9300-24T.txt)
Added full output of SNMPWALK.

**Comment by garnier-quentin** [comment]
I think it's fixed. We check the following OID now: entSensorValueUpdateRate

**Comment by garnier-quentin** [comment]
You should test with the last version and see if it's ok now
