### ISSUE TITLE
[apps::citrix::local::plugin] mode=license - fail if there are more then 1 license

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1626]
Centreon Plugins 20190704

Checking Citrix license usage using apps::citrix::local::plugin with mode=license is failing if there are more then 1 license on the system:

```
    my $query = "Select InUseCount,Count from Citrix_GT_License_Pool";
    my $resultset = $wmi->ExecQuery($query);
    foreach my $obj (in $resultset) {
        $inUseCount = $obj->{InUseCount};
        $count = $obj->{Count};
        $percentUsed = ($inUseCount / $count) * 100;

        my $exit = $self->{perfdata}->threshold_check(value => $percentUsed, threshold => [ { label => 'critical', 'exit_litteral' => 'critical' }, { label => 'warning', exit_litteral => 'warning' } ]);
        $self->{output}->output_add(severity => $exit,
                                    short_msg => $percentUsed . "% licenses are used (" . $inUseCount . "/" . $count . ")");
        $self->{output}->perfdata_add(label => 'licenses_used',
                                      value => $inUseCount,
                                      warning => $self->{perfdata}->get_perfdata_for_output(label => 'warning', total => $count),
                                      critical => $self->{perfdata}->get_perfdata_for_output(label => 'critical', total => $count),
                                      min => 0, max => $count);
    }
```

You need sum the licenses and user licenses before you can check, otherwise you will output that 1 license is used maybe for 100%, but there is a second license which is not used completely.

**Comment by garnier-quentin** [comment]
Could you provides Data::Dumper of $obj ?
```
print Data::Dumper::Dumper($obj);
```

**Comment by joschi99** [comment]
Hi @garnier-quentin,
here you can see the requested output:

`CRITICAL: 100% licenses are used (66/66) | 'licenses_used'=0;0.00:27.00;0.00:28.50;0;30 'licenses_used'=0;0.00:27.00;0.00:28.50;0;30 'licenses_used'=0;0.00:27.00;0.00:28.50;0;30 'licenses_used'=0;0.00:56.70;0.00:59.85;0;63 'licenses_used'=0;0.00:113.40;0.00:119.70;0;126 'licenses_used'=0;0.00:29.70;0.00:31.35;0;33 'licenses_used'=0;0.00:59.40;0.00:62.70;0;66 'licenses_used'=0;0.00:29.70;0.00:31.35;0;33 'licenses_used'=0;0.00:59.40;0.00:62.70;0;66 'licenses_used'=0;0.00:29.70;0.00:31.35;0;33 'licenses_used'=0;0.00:59.40;0.00:62.70;0;66 'licenses_used'=0;0.00:29.70;0.00:31.35;0;33 'licenses_used'=0;0.00:59.40;0.00:62.70;0;66 'licenses_used'=17;0.00:29.70;0.00:31.35;0;33 'licenses_used'=66;0.00:59.40;0.00:62.70;0;66 'licenses_used'=0;0.00:29.70;0.00:31.35;0;33 'licenses_used'=0;0.00:59.40;0.00:62.70;0;66 'licenses_used'=0;0.00:9000.00;0.00:9500.00;0;10000`

**Comment by garnier-quentin** [comment]
But could you add Data::Dumper and provide the result ?

**Comment by garnier-quentin** [comment]
Maybe we can do a total usage ? (sum all licenses)

**Comment by joschi99** [comment]
Probably do a sum is the right way.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by joschi99** [comment]
Hi @garnier-quentin,
if have done some test, but we have some issue:

```
centreon_plugins.exe --plugin=apps::citrix::local::plugin --mode=license
OK: Licenses Total: 10.62 KB Used: 80.00 B (0.74%) Free: 10.54 KB (99.26%) | 'licenses.usage.count'=80B;;;0;10873 'licenses.free.count'=10793;;;0;10873 'licenses.usage.percentage'=0.74%;;;0;100
```
As you can see on the image belove we have a license usage of 80 and 90 license in total:
![image](https://user-images.githubusercontent.com/6400595/64700089-8571d400-d4a6-11e9-8311-7bb4cadd0815.png)

As you can see the license usage seem's correct, but the available licenses are not ok. Even output format is wrong (B).

**Comment by joschi99** [comment]
The output seem's know formated better, but still wrong free license count:
```
centreon_plugins.exe --plugin=apps::citrix::local::plugin --mode=license
OK: Licenses Total: 10873 Used: 80 (0.74%) Free: 10793 (99.26%) | 'licenses.usage.count'=80;;;0;10873 'licenses.free.count'=10793;;;0;10873 'licenses.usage.percentage'=0.74%;;;0;100
```

As you can see in the last post customer has 90 licenses and not 10873

**Comment by garnier-quentin** [comment]
But i add all licenses. that why i need a debug to get all pool in table 'Citrix_GT_License_Pool'.
Can you replace by that and provide me the result ?
```
sub manage_selection {
    my ($self, %options) = @_;

    my $wmi = Win32::OLE->GetObject('winmgmts:root\CitrixLicensing');
    if (!defined($wmi)) {
        $self->{output}->add_option_msg(short_msg => 'Cant create server object:' . Win32::OLE->LastError());
        $self->{output}->option_exit();
    }

    $self->{global} = { total => 0, used => 0 };
    my $query = "Select * from Citrix_GT_License_Pool";
    my $resultset = $wmi->ExecQuery($query);
    foreach my $obj (in $resultset) {
       use Data::Dumper; print Data::Dumper::Dumper($obj);
        $self->{global}->{used} += $obj->{InUseCount};
        $self->{global}->{total} += $obj->{Count};
    }

    if ($self->{global}->{total} == 0) {
        $self->{output}->add_option_msg(short_msg => 'Cant get licenses count');
        $self->{output}->option_exit();
    }

    $self->{global}->{prct_used} = $self->{global}->{used} * 100 / $self->{global}->{total};
    $self->{global}->{prct_free} = 100 - $self->{global}->{prct_used};
    $self->{global}->{free} = $self->{global}->{total} - $self->{global}->{used};
}
```

**Comment by joschi99** [comment]
Hi @garnier-quentin,
attached yoc can find the data from WMI-Query "Select * from Citrix_GT_License_Pool" for the same system where you have just the screenshot:
[Citrix_License_Query.zip](https://github.com/centreon/centreon-plugins/files/3670813/Citrix_License_Query.zip)

**Comment by joschi99** [comment]
Maybe this can help for better understanding: 
https://myxenapp.com/2018/04/27/ps-script-to-get-license-count/
https://support.citrix.com/article/CTX123762
http://www.itpointofview.com/323/check-citrix-licencing-server-with-centreonnagios/

**Comment by garnier-quentin** [comment]
I have take a look. It seems you look a specific 'SubscriptionDate'. I take all SubscriptionDate. Links doesn't provide the way to group licences.
