### ISSUE TITLE
[apps::vmware::connector::plugin] datastore-iops (UNKNOWN: Cannot get value for counters)

### ISSUE THREAD

**Issue by Xound22** [centreon/centreon-plugins#1630]
Bonjour à tous,

Je viens ici en espérant trouver de l'aide à mon problème.

Sur des ESX 6.7, j'ai l'erreur suivantes:
`/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=datastore-iops --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='wb-esxi1-virt'
UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...) |`
 
Cependant sur un ESX identique ou aucune VM n'est présente j'ai ceci:
`/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=datastore-iops --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='wb-esxi3-virt'
OK: No virtual machines on the datastore - All datastores are ok |`

Cette erreur est présente seulement avec le mode datastore-iops, les autres modes fonctionnent correctement.

Les datastores sont des volumes NETAPP montés en NFS.

D'après ce que j'ai pu trouvé comme information sur internet, j'ai vérifié le serveur NTP et  j'ai essayé de changer le niveau des statistiques (Level 2,3,4) sur le vcenter sans aucun effet.

D'autres part, sur des ESX 6.0 avec des volumes NETAPP montés en ISCSI, le mode datastore-iops fonctionne correctement.

Si quelqu'un à déjà recontré ce problème ou aurait une piste pour le résoudre, je vous en remercie par avance.

-----------------------------------------------------------------------------------------------------------------

Good morning, everyone,

I come here hoping to find help for my problem.

On ESX 6.7, I have the following error:
`/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=datastore-iops --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='wb-esxi1-virt'.
UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...) |`
 
However on an identical ESX where no VM is present I have this:
`/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=datastore-iops --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='wb-esxi3-virt'.
OK: No virtual machines on the datastore - All datastores are ok |`

This error is only present with mode datastore-iops, the other mode work correctly.

Datastores are NETAPP volumes mounted in NFS.

From what I could find as information on the internet, I checked the NTP server and tried to change the level of statistics (Level 2,3,4) on the vcenter without any effect.

On the other hand, on ESX 6.0 with NETAPP volumes mounted in ISCSI, the datastore-iops mode works correctly.

If someone has already identified this problem or has a way to solve it, I thank you in advance.

**Comment by garnier-quentin** [comment]
It should work if a check like 'cpu-host' is working. Neverthless, the connector doesn't manage NFS datastore (yet). I need an access to test it.

**Comment by joschi99** [comment]
I have same problem with VMWare 6.7 and plugin version 20191016. Checking IOPS on a datastore and ESXi Host, where NO vm is on fails with:
`UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...) |`

**Comment by garnier-quentin** [comment]
You should have that message "No virtual machines on the datastore" if you don't have virtual machines on the datastore.

**Comment by joschi99** [comment]
But we get the error "UNKNOWN" ...
![image](https://user-images.githubusercontent.com/6400595/73173518-d60c6580-4105-11ea-941c-7e9eb1a7e6be.png)

**Comment by garnier-quentin** [comment]
Could you give me the status of your vm ? (disconnected,...) Other modes are working ? like 'cpu-host' ?

**Comment by joschi99** [comment]
the vm is powered off

**Comment by joschi99** [comment]
all other VMWare host-checks are working

**Comment by garnier-quentin** [comment]
it's fixed for joschi99. it was an issue with mode datastore-vm and no vm running.

**Comment by garnier-quentin** [comment]
@Xound22 are you available for a zoom session ?

**Comment by gagzou** [comment]
Hello,
Same problem :
UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...)

I have several clusters (vsan or not) and only the datastore-iops monitor on vsan does not work.
All other monitors are working (cpu / time / ...).
This only concerns the hyperconverged datastore.
The iops monitor works on the host datastore but not on the vsan datastore.

**Comment by garnier-quentin** [comment]
You can comment it if you still have the issue.
