### ISSUE TITLE
[apps::elasticsearch::restapi::mode::nodes] - filter-name is not working correctly

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1631]
Plugins 20190704

The option filter-name is not working with the node names, but only with internal elastic id's

`/usr/lib/centreon/plugins/fatpack/database-elasticsearch-restapi.pl --hostname=172.27.18.9 --port=9200 --proto=http --plugin=database::elasticsearch::restapi::plugin --mode=node-statistics --filter-name='tVNiDuaIRWKfjh6NlXi4oQ'`

**Comment by Sims24** [comment]
Hi @joschi99 

Could you try to replace : 

`$node
`by
`$node->{name}`

here => https://github.com/centreon/centreon-plugins/blob/b842ec970e5b96008ae42ef3728b3d89750376fc/database/elasticsearch/restapi/mode/nodestatistics.pm#L118  

Tell me if it does what you except after the substitution. 

Regards,
Simon

**Comment by joschi99** [comment]
Hi @Sims24 

after replacing line 118 I got this error:
`UNKNOWN: Can't use string ("XLk-0pXITVGlMbQaDwFXHA") as a HASH ref while "strict refs" in use at /usr/lib/centreon/plugins/database/elasticsearch/restapi/mode/nodestatistics.pm line 117.
`

**Comment by Sims24** [comment]
@joschi99 thanks my bad. 

$nodes_stats->{nodes}->{$node}->{name} should work better than $node->{name} ... 

Do you confirm that the name displayed in output and perfdata parts is OK ?

**Comment by joschi99** [comment]
@Sims24 filter is now working, output and perfdata seem's correct:

```
./centreon_plugins.pl --hostname=x.x.x.x --port=9200 --proto=http --plugin=database::elasticsearch::restapi::plugin --mode=node-statistics --filter-name='Node 1'
OK: Node 'i-Vertix Node 1' JVM Heap: 26%, Free Disk Space: 1.56TB, Documents: 4362761044, Data: 1.26TB | 'i-Vertix Node 1#node.jvm.heap.usage.percentage'=26%;;;0;100 'i-Vertix Node 1#node.jvm.heap.usage.bytes'=36380302240B;;;0;137151119360 'i-Vertix Node 1#node.disk.free.bytes'=1710072680448B;;;0;3113589145600 'i-Vertix Node 1#node.documents.total.count'=4362761044;;;0; 'i-Vertix Node 1#node.data.size.bytes'=1386278479651B;;;0;
```

Thanks
