### ISSUE TITLE
[os::linux::snmp::plugin] mode=storage returns "total size is <= 0 (-4924169519104)" 

### ISSUE THREAD

**Issue by zubur** [centreon/centreon-plugins#1634]
Using this plugin against 12T partition it returns an error:
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --storage=31  --hostname=x.x.x.x --snmp-version=3 --snmp-community=xxx --snmp-username=xxx --authprotocol=MD5 --authpassphrase=xxx --privprotocol=AES --privpassphrase=xxx  --warning-usage='75' --critical-usage='85'
OK: Storage '/' Usage Total: 199.90 GB Used: 31.52 GB (15.77%) Free: 168.38 GB (84.23%) | 'used'=33843331072B;0:160982630400;0:182446981120;0;214643507200

./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --storage=33  --hostname=x.x.x.x --snmp-version=3 --snmp-community=xxx --snmp-username=xxx --authprotocol=MD5 --authpassphrase=xxx --privprotocol=AES --privpassphrase=xxx  --warning-usage='75' --critical-usage='85'
UNKNOWN: Issue with storage information (see details)
skipping storage '/var/log': total size is <= 0 (-4924169519104)

snmpwalk x.x.x.x -v 3 -a MD5 -u xxx -A xxx -l authPriv -x AES -X xxx   1.3.6.1.4.1.2620.1.6.7.6.1.3                                                     
SNMPv2-SMI::enterprises.2620.1.6.7.6.1.3.1.0 = STRING: "214643507200"
SNMPv2-SMI::enterprises.2620.1.6.7.6.1.3.2.0 = STRING: "304624640"
SNMPv2-SMI::enterprises.2620.1.6.7.6.1.3.3.0 = STRING: "12668016525312"

centreon_plugins.pl --plugin=os::linux::snmp::plugin --version
Plugin Version: 0.1
centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=storage --version
Mode Version: 1.0

**Comment by zubur** [comment]
snmpwalk x.x.x.x -v 3 -a MD5 -u xxx -A xxx -l authPriv -x AES -X xxx 1.3.6.1.4.1.2620.1.6.7.6.1.3
SNMPv2-SMI::enterprises.2620.1.6.7.6.1.3.1.0 = STRING: "214643507200"
SNMPv2-SMI::enterprises.2620.1.6.7.6.1.3.2.0 = STRING: "304624640"
SNMPv2-SMI::enterprises.2620.1.6.7.6.1.3.3.0 = STRING: "12668016525312"

Yes it is a checkpoint firewall

**Comment by garnier-quentin** [comment]
Ok. Sorry, it's that OID:
```
SNMPv2-SMI::enterprises.2620.1.6.7.6.1
```

**Comment by garnier-quentin** [comment]
Ping :)

**Comment by lolo54000** [comment]
Hi 
I have the same problem with the windows version of this plugin

I have an Hdd with a partition of 32To when i run command 
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=x.x.x.x --storage='(^D)' --warning-usage=80 --critical-usage=90 --regexp --name

UNKNOWN: Issue with storage information (see details)
skipping storage 'D:\ Label:   Serial Number 1ee6c5e0': total size is <= 0 (-34368384942080)

how can I resolve this problem?
thanks for your help

**Comment by garnier-quentin** [comment]
It's a known issue. You need to use nsclient for big disks.

**Comment by lolo54000** [comment]
ok thank you

**Comment by garnier-quentin** [comment]
Have you provided the snmpwalk for the checkpoint ? SNMPv2-SMI::enterprises.2620.1.6.7.6.1

**Comment by lolo54000** [comment]
Hi 
I test with this new version (I check my file in my computeur and I have the good file with this commit)

but with this command line on my 32To hdd
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=x.x.x.x --storage='(^D)' --warning-usage=80 --critical-usage=90 --regexp --name

I have the same error 
UNKNOWN: Issue with storage information (see details)

what is the problem? 

thanks for your help :)
