### ISSUE TITLE
replication mode on postgres chreck 

### ISSUE THREAD

**Issue by AssemAyadi** [centreon/centreon-plugins#1635]
Hi,

Is it possible to add replication mode on postgres chreck ?

Thanks,

**Comment by garnier-quentin** [comment]
Yes but i need request type and result.

**Comment by AssemAyadi** [comment]
/usr/lib/nagios/plugins/check_centreon_snmp_process -H$ip$ -C public -p$process$ -w  -c

**Comment by garnier-quentin** [comment]
You can use os::linux::snmp::plugin to check processes.
