### ISSUE TITLE
network::juniper::mseries::plugin - Juniper Plugin Issue for CPU and Memmory - Request Timed out

### ISSUE THREAD

**Issue by jithinpbenjamin** [centreon/centreon-plugins#1636]
Dear Team,

I am having an issue with Juniper plugin. 1 week back i replaced my router from Juniper M7i to MX104. After replacing the router the plugin is unable to provide me the CPU and memory information from the router. However UP Time, interface traffics are being monitored fine without any issues.

Plugin Output from CLI: (If you refer the CLI output you will notice during my 5 immediate retries, only once the router responded with the value, remaining tries were failed with "UNKNOWN: SNMP Table Request : Timeout"

[root@centreon ~]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90
UNKNOWN: SNMP Table Request : Timeout

[root@centreon ~]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90
UNKNOWN: SNMP Table Request : Timeout

[root@centreon ~]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90
OK: Memory 'Routing Engine 0' Total: 3.88 GB Used: 674.56 MB (17.00%) Free: 3.22 GB (83.00%) | 'used'=707327426.56B;0.00:3328599654.40;0.00:3744674611.20;0;4160749568

[root@centreon ~]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90
UNKNOWN: SNMP Table Request : Timeout

[root@centreon ~]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90
UNKNOWN: SNMP Table Request : Timeout

I am facing same behavior with the CPU of the router.

Can you please help me find out if am doing something wrong with the parameters or is this a bug with the Plugin.

Let me know if you need any other details from me.

Regards,
Jithin

**Comment by garnier-quentin** [comment]
Could you try with --snmp-autoreduce option please ?

**Comment by jithinpbenjamin** [comment]
Hi

I am getting an error "Unknown option" when using --snmp-autoreduce

[root@centreon ~]# /usr/lib/centreon/plugins/iec_plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90 --snmp-autoreduce
Unknown option: snmp-autoreduce at /usr/lib/centreon/plugins/iec_plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by garnier-quentin** [comment]
You have an old version. Could you get last github version and test it ?

**Comment by jithinpbenjamin** [comment]
Hi,

Yes, after the github refresh the --snmp-autoreduce option is working.
Also the plugin returning the correct value when using this. --snmp-autoreduce, however the plugin takes little longer to retunr the value, is that normal?

Finally, Does this means that i need to update my "check command" with the --snmp-autoreduce option?

[root@centreon centreon-plugins]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90 --snmp-autoreduce

OK: Memory 'Routing Engine 0' Total: 3.88 GB Used: 674.56 MB (17.00%) Free: 3.22 GB (83.00%) | 'used'=707327426.56B;0.00:3328599654.40;0.00:3744674611.20;0;4160749568
[root@centreon centreon-plugins]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90 --snmp-autoreduce

OK: Memory 'Routing Engine 0' Total: 3.88 GB Used: 674.56 MB (17.00%) Free: 3.22 GB (83.00%) | 'used'=707327426.56B;0.00:3328599654.40;0.00:3744674611.20;0;4160749568

[root@centreon centreon-plugins]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90 --snmp-autoreduce

OK: Memory 'Routing Engine 0' Total: 3.88 GB Used: 674.56 MB (17.00%) Free: 3.22 GB (83.00%) | 'used'=707327426.56B;0.00:3328599654.40;0.00:3744674611.20;0;4160749568

[root@centreon centreon-plugins]# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::juniper::mseries::plugin --mode=memory-routing  --hostname=x.x.x.x --snmp-community=pubsnmp --snmp-version=2c --warning=80 --critical=90 --snmp-autoreduce
OK: Memory 'Routing Engine 0' Total: 3.88 GB Used: 674.56 MB (17.00%) Free: 3.22 GB (83.00%) | 'used'=707327426.56B;0.00:3328599654.40;0.00:3744674611.20;0;4160749568

**Comment by garnier-quentin** [comment]
Yes it's normal. You can remove --snmp-autoreduce and use: --subsetleef=1 --maxrepetitions=5
