### ISSUE TITLE
[os::linux::snmp::plugin] UNKNOWN: Can't construct cache...

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1640]
Hello guys,

I have a problem that I get this message sinc 6 days:

> UNKNOWN: Can't construct cache...

Other Linux machines are working correct. The machines where this error is returned are configured in the same way: Ubuntu 18.04.3 LTS with LVM configured.

The command to check the storage hasn't changed:
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=xxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='public'  --storage '/' --name --display-transform-src='' --display-transform-dst='' --warning-usage='80' --critical-usage='90' --verbose`

Can anyonehelp me?
Thank you very much!

Best regards, Michael

EDIT: If I use the mode "list-storages" it returns: UNKNOWN: No storage found.

**Comment by Blubster** [comment]
Hi,
I also have the same issue on my Ubuntu machines, they are no longer reporting the storage.
It looks like it is an issue that is on Ubuntu's side :
https://bugs.launchpad.net/ubuntu/+source/net-snmp/+bug/1843036
A fix is imminent ! :)

**Comment by garnier-quentin** [comment]
It would be great :)
