### ISSUE TITLE
hardware::server::hp::proliant::snmp::plugin - da controller accelerator '0' [status: invalid, battery status: ok] condition is other

### ISSUE THREAD

**Issue by mihaiste** [centreon/centreon-plugins#1641]
Hello,

I have a HP ProLiant DL360 Gen10 with iLO 5 and I am using Centreon 2.4.1.

I want to check the iLO health by running:
centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --hostname x.x.x.x --mode=hardware --snmp-community myCom --snmp-version 1 --exclude=pnic --snmp-force-getnext --debug

I am getting the following output:
UNKNOWN: da controller accelerator '0' is other | 'psu_power_0.1'=90W;;500;; 'psu_voltage0.1'=118V;;;; 'psu_power_0.2'=107W;;500;; 'psu_voltage0.2'=117V;;;; 'temp_0.1_ambient'=20C;;0:42;; 'temp_0.2_cpu'=40C;;0:70;; 'temp_0.3_cpu'=40C;;0:70;; 'temp_0.4_memory'=42C;;0:90;; 'temp_0.6_memory'=42C;;0:90;; 'temp_0.8_memory'=50C;;0:90;; 'temp_0.10_memory'=49C;;0:90;; 'temp_0.12_system'=35C;;0:60;; 'temp_0.14_system'=27C;;0:60;; 'temp_0.15_ambient'=28C;;0:60;; 'temp_0.16_system'=42C;;0:115;; 'temp_0.17_system'=48C;;0:115;; 'temp_0.18_system'=32C;;0:115;; 'temp_0.19_system'=33C;;0:115;; 'temp_0.20_system'=37C;;0:115;; 'temp_0.21_system'=42C;;0:115;; 'temp_0.22_system'=52C;;0:100;; 'temp_0.23_system'=88C;;0:110;; 'temp_0.24_system'=56C;;0:90;; 'temp_0.25_system'=72C;;0:100;; 'temp_0.26_system'=49C;;0:85;; 'temp_0.27_system'=68C;;0:100;; 'temp_0.28_ioBoard'=68C;;0:100;; 'temp_0.29_system'=43C;;0:90;; 'temp_0.31_ioBoard'=47C;;0:90;; 'temp_0.33_ioBoard'=46C;;0:90;; 'temp_0.37_system'=50C;;0:75;; 'temp_0.38_powerSupply'=49C;;0:0;; 'temp_0.39_powerSupply'=53C;;0:0;; 'temp_0.40_powerSupply'=56C;;0:0;; 'temp_0.41_powerSupply'=67C;;0:0;; 'temp_0.42_powerSupply'=45C;;0:100;; 'temp_0.43_powerSupply'=51C;;0:75;;
Product Name: ProLiant DL360 Gen10, Serial: XXX, Rom Version: U32 v2.04 (04/18/2019)
Checking cpu
cpu '0' [slot: 0, unit: 0, name: Intel Xeon, socket: 1] status is ok.
cpu '1' [slot: 0, unit: 0, name: Intel Xeon, socket: 2] status is ok.
Checking ide controllers
Checking ide logical drives
Checking ide physical drives
Checking power converters
Checking power supplies
powersupply '0.1' status is ok [redundance: 3, redundant partner: 0] (status noError).
powersupply '0.2' status is ok [redundance: 3, redundant partner: 0] (status noError).
Checking sas controllers
Checking sas logical drives
Checking sas physical drives
Checking scsi controllers
Checking scsi logical drives
Checking scsi physical drives
Checking fca host controller
Checking fca external controller
Checking fca external accelerator boards
Checking fca logical drives
Checking fca physical drives
Checking da controller
da controller '0' [slot: 0, model: unknown] status is ok.
Checking da accelerator boards
da controller accelerator '0' [status: invalid, battery status: ok] condition is other.
Checking da logical drives
da logical drive '0.1' [fault tolerance: mirroring, condition: ok] status is ok.
Checking da physical drives
da physical drive '0.0' [status: ok] condition is ok.
da physical drive '0.1' [status: ok] condition is ok.
da physical drive '0.2' [status: ok] condition is ok.
da physical drive '0.3' [status: ok] condition is ok.
Checking fans
fan '0.1' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 2].
fan '0.2' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 3].
fan '0.3' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 4].
fan '0.4' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 5].
fan '0.5' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 6].
fan '0.6' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 7].
fan '0.7' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 1].
Checking physical nics
Skipping pnic section.
Checking logical nics
Checking temperatures
'0.1' ambient temperature is 20C (42 max) (status is ok).
'0.2' cpu temperature is 40C (70 max) (status is ok).
'0.3' cpu temperature is 40C (70 max) (status is ok).
'0.4' memory temperature is 42C (90 max) (status is ok).
'0.6' memory temperature is 42C (90 max) (status is ok).
'0.8' memory temperature is 50C (90 max) (status is ok).
'0.10' memory temperature is 49C (90 max) (status is ok).
'0.12' system temperature is 35C (60 max) (status is ok).
'0.14' system temperature is 27C (60 max) (status is ok).
'0.15' ambient temperature is 28C (60 max) (status is ok).
'0.16' system temperature is 42C (115 max) (status is ok).
'0.17' system temperature is 48C (115 max) (status is ok).
'0.18' system temperature is 32C (115 max) (status is ok).
'0.19' system temperature is 33C (115 max) (status is ok).
'0.20' system temperature is 37C (115 max) (status is ok).
'0.21' system temperature is 42C (115 max) (status is ok).
'0.22' system temperature is 52C (100 max) (status is ok).
'0.23' system temperature is 88C (110 max) (status is ok).
'0.24' system temperature is 56C (90 max) (status is ok).
'0.25' system temperature is 72C (100 max) (status is ok).
'0.26' system temperature is 49C (85 max) (status is ok).
'0.27' system temperature is 68C (100 max) (status is ok).
'0.28' ioBoard temperature is 68C (100 max) (status is ok).
'0.29' system temperature is 43C (90 max) (status is ok).
'0.31' ioBoard temperature is 47C (90 max) (status is ok).
'0.33' ioBoard temperature is 46C (90 max) (status is ok).
'0.37' system temperature is 50C (75 max) (status is ok).
'0.38' powerSupply temperature is 49C (0 max) (status is ok).
'0.39' powerSupply temperature is 53C (0 max) (status is ok).
'0.40' powerSupply temperature is 56C (0 max) (status is ok).
'0.41' powerSupply temperature is 67C (0 max) (status is ok).
'0.42' powerSupply temperature is 45C (100 max) (status is ok).
'0.43' powerSupply temperature is 51C (75 max) (status is ok).
Checking ilo
ilo status is ok [message = ].

What is the message "UNKNOWN: da controller accelerator '0' is other" related to?
I also don't understand what the following message means:
Checking da controller
da controller '0' [slot: 0, model: unknown] status is ok.
Checking da accelerator boards
da controller accelerator '0' [status: invalid, battery status: ok] condition is other.

I have to mention that the same check works on ProLiant DL360 Gen9 with iLO 4.

Thanks,
Mihai

**Comment by garnier-quentin** [comment]
You can use following option: --threshold-overload='daacc,OK,other'

**Comment by mihaiste** [comment]
True, thank you. Tried it and it works.
Just found another workaround by excluding it with --exclude=daacc and it just skips the step that provides the error message.

These 2 are workarounds. Is there any way to troubleshoot this issue?

**Comment by garnier-quentin** [comment]
Maybe it's not an error. You could ask to hp support why we have an other status. Not sure you'll have a response ;)

**Comment by mihaiste** [comment]
Will do, thank you very much!
