### ISSUE TITLE
[os::windows::snmp::plugin] UNKNOWN: SNMP Table Request : (genError) A general failure occured

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1642]
Hey guys,

another problem occured. When I try to check some services I receive following error:

> UNKNOWN: SNMP Table Request : (genError) A general failure occured

On other machines there is no problem to check servies. The only difference is that this one server is not a domain member. All other checks for cpu, memory etc. is working perfect.
This is the command for checking the services:
`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=xxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='public'  --service='Sap' --warning= --critical=1:1 --state='' --regexp`

Thanks, Michael

**Comment by garnier-quentin** [comment]
It's an issue of windows snmp agent. I could optimize the check. And maybe i could avoid that error.

**Comment by MikeW83** [comment]
The mysterious thing is, that this only happens with one server. All other server don't have such an issue.

**Comment by joschi99** [comment]
This is a Microsoft bug. We have seen this issue on different OS version, from W2K12 until W2K19. We do not have any solution how to fix this issue.
You need to monitor through WMI or using a client like nsclient++ as workaround.

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test with last version ? Maybe it solved the genError

**Comment by MikeW83** [comment]
There is no change... I have updated Centreon via
`yum upgrade -y`
to receive all updates. Or do I need to do update files manually? When I check the status of my plugins there are only versions from July 2019

> # ls -la
> total 8772
> drwxr-xr-x. 2 root root   4096 Jul  8 11:37 .
> drwxr-xr-x. 3 root root     21 Feb 11  2019 ..
> -rwxrwxr-x  1 root root 255079 Jul  4 14:38 centreon_centreon_central.pl
> -rwxrwxr-x  1 root root 421093 Jul  4 14:38 centreon_centreon_database.pl
> -rwxrwxr-x  1 root root 238272 Jul  4 14:38 centreon_centreon_map.pl
> -rwxrwxr-x  1 root root 255079 Jul  4 14:38 centreon_centreon_poller.pl
> -rwxrwxr-x  1 root root 259061 Jul  4 14:38 centreon_cisco_meraki_snmp.pl
> -rwxrwxr-x  1 root root 566335 Jul  4 14:38 centreon_cisco_standard_snmp.pl
> -rwxrwxr-x  1 root root 456098 Jul  4 14:38 centreon_fortinet_fortigate.pl
> -rwxrwxr-x  1 root root 194341 Jul  4 14:38 centreon_hp_3par_7000.pl
> -rwxrwxr-x  1 root root 307395 Jul  4 14:38 centreon_hp_ilo_xmlapi.pl
> -rwxrwxr-x  1 root root 294294 Jul  4 14:38 centreon_hp_lefthand.pl
> -rwxrwxr-x  1 root root 351969 Jul  4 14:38 centreon_hp_procurve.pl
> -rwxrwxr-x  1 root root 362542 Jul  4 14:38 centreon_hp_proliant.pl
> -rwxrwxr-x  1 root root 284841 Jul  4 14:38 centreon_hp_storeonce_restapi.pl
> -rwxrwxr-x  1 root root 216267 Jul  4 14:38 centreon_hp_storeonce_ssh.pl
> -rwxrwxr-x  1 root root 515331 Jul  4 14:38 centreon_linux_snmp.pl
> -rwxrwxr-x  1 root root 297071 Jul  4 14:38 centreon_mssql.pl
> -rwxrwxr-x  1 root root 338374 Jul  4 14:38 centreon_mysql.pl
> -rwxrwxr-x  1 root root 280992 Jul  4 14:38 centreon_office365_teams_api.pl
> -rwxrwxr-x  1 root root 273496 Jul  4 14:38 centreon_printers_generic_snmp.pl
> -rwxrwxr-x  1 root root 206849 Jul  4 14:38 centreon_protocol_dns.pl
> -rwxrwxr-x  1 root root 229575 Jul  4 14:38 centreon_protocol_ftp.pl
> -rwxrwxr-x  1 root root 299268 Jul  4 14:38 centreon_protocol_http.pl
> -rwxrwxr-x  1 root root 215386 Jul  4 14:38 centreon_protocol_ldap.pl
> -rwxrwxr-x  1 root root 203408 Jul  4 14:38 centreon_protocol_telnet.pl
> -rwxrwxr-x  1 root root 387218 Jul  4 14:38 centreon_synology.pl
> -rwxrwxr-x  1 root root 261311 Jul  4 14:38 centreon_ups_standard_rfc1628_snmp.pl
> -rwxrwxr-x  1 root root 522681 Jul  4 14:38 centreon_vmware_connector_client.pl
> -rwxrwxr-x  1 root root 430066 Jul  4 14:38 centreon_windows_snmp.pl

Best regards, Michael

**Comment by garnier-quentin** [comment]
You need to use unstable repository.
```
yum --enablerepo=centreon-unstable-noarch update centreon-plugin-Operatingsystems-Windows-Snmp
```

**Comment by MikeW83** [comment]
Perfect, thank you. Now it's working. I get correct information from the plugin.

Best regards, Michael

**Comment by garnier-quentin** [comment]
Great!

**Comment by buchetiglia** [comment]
Hello  i've got the same problem on Windows Server 2019.

I've update plugin with the unstable-repository but i allways have the same error :

> UNKNOWN: SNMP Table Request : (genError) A general failure occured

**Comment by garnier-quentin** [comment]
I have done my best. You should use nsclient.

**Comment by buchetiglia** [comment]
ok thanks, il will going to try to use nsclient.
