### ISSUE TITLE
Desactivate perfdata "|" characters

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon-plugins#1645]
Hello,

Is it possible to add an option to desactivate perfdata characters on Centreon Plugins output ? Sometimes when we use special script is usefull to be able to delete this character :)

The option can be : --no-perfdata :)

Regards,

**Comment by lolokai** [comment]
I saw on centreon-plugins/centreon/plugins/output.pm that the options force_ignore_perfdata is defined but this option looks like not exist on  $options{options}->add_options(arguments => { line 36

**Comment by Sims24** [comment]
Hi @lolokai 

This options is only for internal purposes ;) You can use --filter-perfdata and a regexp I guess this is the closest thing we can offer right now. 

Discarding all perfdata is not as simple as it seems right now.

**Comment by lolokai** [comment]
Hi @Sims24 : can you give me an exampl of --filter-perfdata ?

**Comment by Sims24** [comment]
Please provide the perfdata you want to filter :)

**Comment by lolokai** [comment]
@Sims24  👍 
OK - Domain CPU : 11.7% 

;)

**Comment by Sims24** [comment]
Is this from an official centreon_plugins ? Looks like an output and not a perfdata. 

--filter-perfdata='ignoreall' should work (except if one of your perfdata label is ignoreall ;))

**Comment by lolokai** [comment]
Sorry :)
OK - Domain CPU : 19.8% |cpu_0=19.8%;75;90;0;100

**Comment by Sims24** [comment]
` --filter-perfdata='^(?!(cpu))' `

This should be ok
