### ISSUE TITLE
[os::linux::snmp::plugin] mode=memory returns "Used (-buffers/cache): -436965376.00 B (-11.00%)"

### ISSUE THREAD

**Issue by iv-dess** [centreon/centreon-plugins#1646]
Hello,

after updating net-snmp package on rhel 7.7, I get negative Used Memory when buffers/cache is higher than Used Memory. I think it's because the calculation in snmp has changed : https://bugzilla.redhat.com/show_bug.cgi?id=1250060

### net-snmp.x86_64 1:5.7.2-38.el7_6.2  :

**Plugin Output** :
 
OK: Ram Total: 3.70 GB, Used (-buffers/cache): 415.93 MB (10.97%), Buffer: 7.12 MB, Cached: 425.52 MB, Shared: 64.28 MB

**snmpwalk -v 2c -c Lire_L_Info localhost 1.3.6.1.4.1.2021.4** :

UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 3880640 kB
UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 3327648 kB
UCD-SNMP-MIB::memTotalFree.0 = INTEGER: 5375644 kB

**/proc/meminfo** :

MemTotal:        3880640 kB
MemFree:         3329200 kB
MemAvailable:    3387356 kB

### net-snmp.x86_64 1:5.7.2-43.el7  (latest available for rhel 7):

**Plugin Output** :

CRITICAL: Ram Total: 3.70 GB, Used (-buffers/cache): -435888128.00 B (-10.97%), Buffer: 3.07 MB, Cached: 679.30 MB, Shared: 8.86 MB

snmpwalk -v 2c -c Lire_L_Info localhost 1.3.6.1.4.1.2021.4 :

UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 3880640 kB
UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 3605332 kB
UCD-SNMP-MIB::memTotalFree.0 = INTEGER: 5653328 kB

/proc/meminfo :

MemTotal:        3880640 kB
MemFree:         2907576 kB
MemAvailable:    3371860 kB

_*Values are not exact since commands were not executed simultaneously. It's just to try to explain the issue in general_

**Comment by thibaults-centreon** [comment]
Hello @iv-dess, have a look at #1620 and let us know if it solves the issue ;)
