### ISSUE TITLE
[os::linux::snmp::plugin] UNKNOWN: Can't construct cache...

### ISSUE THREAD

**Issue by lolo54000** [centreon/centreon-plugins#1647]
Hi 

I want to monitor my network interfaces of my router (Overthebox from ovh) witch run on openwrt .
On openwrt I enable mini-snmpd
I configure mini-snmpd
I can read load from my centreon but when I want to read my network interface it's don't work I have an error :  Can't construct cache.

If I test to do an snmp walk from my centreon poller to my router I can view my 5 interfaces that i want to monitor.

![Capture](https://user-images.githubusercontent.com/14163451/65021058-adda5200-d92e-11e9-89da-3e5a08b3856e.JPG)

What is the problem ?

Thanks for your help.

**Comment by garnier-quentin** [comment]
Please try with following option:
```
--oid-display=ifdesc --oid-filter=ifdesc
```

**Comment by lolo54000** [comment]
It's work fine thank you :)

**Comment by garnier-quentin** [comment]
Thanks for the feedback
