### ISSUE TITLE
Radius Plugin - "Dictionary issue"

### ISSUE THREAD

**Issue by watchix** [centreon/centreon-plugins#1648]
Hi, i'm having an issue with the Radius (protocol) plugin.

[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::radius::plugin --mode=login --hostname=my.radius.com --port=1812 --secret=supervision --username=supervision_secret --password=user_password --radius-attribute="NAS-Identifier=SUPERVISION-NAS" --radius-dictionary=/usr/lib/centreon/plugins/dictionary_freeradius.txt
UNKNOWN: Issue with dictionary and attributes

[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::radius::plugin --mode=login --hostname=my.radius.com --port=1812 --secret=supervision --username=supervision_secret --password=user_password --radius-attribute="NAS-Identifier=SUPERVISION-NAS" --radius-dictionary=/usr/lib/centreon/plugins/dictionary_freeradius.txt
UNKNOWN: Issue with dictionary and attributes

I tried to move the dictionary file into diferent folders but same problem.
Do i need to install FreeRadius libraries from YUM ?

Regards,

**Comment by garnier-quentin** [comment]
Could you provide your dictionary file ?

**Comment by watchix** [comment]
Hi Quentin,

Thanks for your reply.
Your question put me on the right track :)

The dictionary file was not correct.
I've tested to use the "dictionary.rfc2865" and it's now ok :)

[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::radius::plugin --mode=login --hostname=my.radius.com --port=1812 --secret=supervision_secret --radius-attribute='User-Name=supervision_user' --radius-attribute='User-Password=user_password' --radius-attribute='NAS-Identifier=SUPERVISION-NAS' --radius-dictionary=/usr/lib/centreon/plugins/dictionary.rfc2865
OK: Radius Access Request Status: accepted [error msg: none] - Response time : 0.015 second(s) | 'time'=0.015s;;;0;

Regards,
