### ISSUE TITLE
Monitoring PDU once it lose a power supply on an enclosure

### ISSUE THREAD

**Issue by chamepicart** [centreon/centreon-plugins#1649]
Is it possible to monitor once a PDU device loses a power supply on an enclosure?

We've tried using different OIDs but to no avail.

rPDUOutlet | 1.3.6.1.4.1.318.1.1.12.3
rPDUOutletDevice | 1.3.6.1.4.1.318.1.1.12.3.1
rPDUOutletPhase | 1.3.6.1.4.1.318.1.1.12.3.2
rPDUStatus | 1.3.6.1.4.1.318.1.1.12.5
rPDUPowerSupply | 1.3.6.1.4.1.318.1.1.12.4
rPDUPowerSupplyAlarm | 1.3.6.1.4.1.318.1.1.12.4.1.3
rPDUOutletConfigPowerOnTime | 1.3.6.1.4.1.318.1.1.12.3.4.1.1.4
rPDUOutletConfigPowerOffTime | 1.3.6.1.4.1.318.1.1.12.3.4.1.1.5

But to no avail, and getting the below message output:

SNMP OK - No Such Instance currently exists at this OID |

Is there another way to monitor the aforementioned parameters?

**Comment by garnier-quentin** [comment]
Could you provide the command ?

**Comment by garnier-quentin** [comment]
Because that message doesn't look like a centreon-plugins error message

**Comment by garnier-quentin** [comment]
you can re-open it if you have some news.
