### ISSUE TITLE
Incorrect performance data of container memory usage causes weird chart

### ISSUE THREAD

**Issue by gouldchu** [centreon/centreon-plugins#1650]
When I use the follwing command to check the memory usage of container:
./centreon_plugins.pl --plugin=cloud::docker::restapi::plugin --mode=container-usage --hostname=[host ip] --port=2375 --filter-name='cadvisor' --filter-counters=memory --warning-memory=80 --critical-memory=90

I get the result as below:
OK: Container '1932fa000b4b1cb5132e82327c4404bba6753ea582c8409ee805e270c97f364a' Memory Total: 7.64 GB Used: 58.38 MB (0.75%) Free: 7.58 GB (99.25%) - Container '1932fa000b4b1cb5132e82327c4404bba6753ea582c8409ee805e270c97f364a.eth0'  | 'memory_used'=61218816B;0:6559960268;0:7379955302;0;8199950336

However, the performance data can't make curve on chart. If I use "--filter-counters=cpu", the chart can be made correctly with the following output: 

OK: Container '1932fa000b4b1cb5132e82327c4404bba6753ea582c8409ee805e270c97f364a' CPU Usage : 7.04 % - Container '1932fa000b4b1cb5132e82327c4404bba6753ea582c8409ee805e270c97f364a.eth0'  | 'cpu'=7.04%;0:80;0:90;0;100

Am I wrong with the command? How can I fix this issue?

This plugin "--plugin=cloud::docker::restapi::plugin" is really great. If more detailed examples can be written in Centreon document, that would help a lot of users. Thank you very much for your attention and great efforts.

I'm afraid these is a problem about the performance data of container memory usage. The status information looks fine, but performance data looks incorrect. This causes weird chart.

Thank you all very much for your great efforts on this tremendous masterpiece.

**Comment by Sims24** [comment]
Hello @gouldchu 

Thanks, we really appreciate your feedback ;) 

About the perfdata, it seems ok for both provided output. What's the issue exactly ? 

From what I see in the output, you are probably not using the last versions of the plugins libraries. Are you up to date with the github ? 

Regards,

**Comment by gouldchu** [comment]
Hi @Sims24

Thank you very much for your prompt reply. You are right. The performance data output is ok. When I check the version I get "Global Version: (dev)". Then I check my command and service configuration. I select the improper graph template and the chart looks weird. Now the chart looks normal.

Thank you once again.

**Comment by Sims24** [comment]
you're welcome 👌
