### ISSUE TITLE
Negative value disk : skipping storage 'E:': total size is <= 0 (-1591421702144)

### ISSUE THREAD

**Issue by kevin-m87** [centreon/centreon-plugins#1651]
Hello, i'm facing this problem of negative value on my HDD with 15To :
skipping storage 'E:': total size is <= 0 (-1591421702144)

I know its a problem with integer32.

I'm using centreon_windows_snmp.pl we can add some some code for resolve this or do something ?

Thanks for your help.

**Comment by Sims24** [comment]
Hello Kevin, 

Thanks for your message but infortunately no we do not have any solution here ..
