### ISSUE TITLE
Install Plugins

### ISSUE THREAD

**Issue by JGGantunes** [centreon/centreon-plugins#1654]
Good morning, I apologize already for my ignorance on the subject, but already looked in several places and could not understand, how I install this pack of plugins in centreon? Since I do not have the license and via the plugin package I have limitations to certain number of plugins ... sorry and thanks in advance for any help

**Comment by garnier-quentin** [comment]
There is no limit for centreon-plugins. You can install centreon-plugin-* rpm. It's in centreon stable repository.

**Comment by JGGantunes** [comment]
Thank you my friend, I will try to find this .rpm package

**Comment by JGGantunes** [comment]
I can not find the package .rpm for installation, to better understand my doubt, I want to monitor Mac hosts via SNMP, I am using centreon version for VM 19.04, my windows and linux machines was easy to configure, but when trying to monitor Mac machines, I can't find the .rpm plugin package for installation, in Plugin Packs Manager I find the package but I don't have the option to install it

**Comment by garnier-quentin** [comment]
The plugin-packs rpm is not free. You need a license. The plugin-pack provides the centreon configuration (commands, service template, host template). the plugin rpm provides the command line (it's free).
