### ISSUE TITLE
[apps::protocols::dns::plugin --expected-answer] - Not exact

### ISSUE THREAD

**Issue by watchix** [centreon/centreon-plugins#1655]
Hello,

The --expected-answer returns alway OK when a digit,dot,string expected is present in the answer, as exemple :
Answer : 1.2.3.4
--expected : 1.2.3.9 => OK 
--expected : 5 => CRITICAL  (because there is not 5 in the answer)
--expected : 1 => OK
--expected : . => OK  (dot is present in the answer)

Is it possible to have the exact answer ?

[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request --nameservers=my-dns-server.com --search=mytest.com --search-type=A --expected-answer=test
CRITICAL: No result values match expected answer (answer: 52.209.170.167) | 'time'=0.060s;;;;
[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request --nameservers=my-dns-server.com --search=mytest.com --search-type=A --expected-answer=1
OK: Response time 0.014 second(s) (answer: 52.209.170.167) | 'time'=0.014s;;;;
[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request --nameservers=my-dns-server.com --search=mytest.com --search-type=A --expected-answer=5.3.2.1
CRITICAL: No result values match expected answer (answer: 52.209.170.167) | 'time'=0.016s;;;;
[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request --nameservers=my-dns-server.com --search=mytest.com --search-type=A --expected-answer=1
OK: Response time 0.191 second(s) (answer: 52.209.170.167) | 'time'=0.191s;;;;
[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request --nameservers=my-dns-server.com --search=mytest.com --search-type=A --expected-answer=9
OK: Response time 0.020 second(s) (answer: 52.209.170.167) | 'time'=0.020s;;;;
[root@centreon ~]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request --nameservers=my-dns-server.com --search=mytest.com --search-type=A --expected-answer=8
CRITICAL: No result values match expected answer (answer: 52.209.170.167) | 'time'=0.021s;;;;

Regards,

**Comment by garnier-quentin** [comment]
It's a regexp. You can use special characters.

**Comment by watchix** [comment]
Thanks Quentin,

Just for another people :
The right syntax is : --expected-answer=$_SERVICEEXPECTED$$
(With two $)

Command example :
perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request --nameservers=your.dns.server.com --search=domain.com --search-type=A --expected-answer=1.2.3.4$

Regards,
