### ISSUE TITLE
MSA 1050 storage::hp::p2000::xmlapi::plugin --mode=health

### ISSUE THREAD

**Issue by afavre-intersed** [centreon/centreon-plugins#1656]
Hi,

I use this plugin to check health on MSA 1050. I have the same issue than [#1061](https://github.com/centreon/centreon-plugins/issues/1061).

In my side the repository is up to date.

I was able to get around the problem by following the advice of cgagnaire in the following answer [https://github.com/centreon/centreon-plugins/issues/1061#issuecomment-407317344](https://github.com/centreon/centreon-plugins/issues/1061#issuecomment-407317344) 

```perl
61     my ($results, $code) = $self->{custom}->get_infos(
62         #cmd => 'show vdisks',
63         cmd => 'show disk-groups',
64         base_type => 'disk-groups',
65         #base_type => 'virtual-disks',
66         key => 'name',
67         properties_name => '^health-numeric$',
68         no_quit => 1,
69     );
```
I thought the problem was the function get_infos (custom.pl), but after a few tests it seems the http request function in `centreon::plugins::http`

Below some information from debug.

I receive error 400 bad request.

```html
======> request send
GET https://<host>/api/show/vdisks
User-Agent: centreon::plugins::backend::http::useragent
Cookie:  wbisessionkey=f6329b8f18654aa733dc7bff8662150a; wbiusername=centreon
DataType:  api
SessionKey:  f6329b8f18654aa733dc7bff8662150a

======> response done
HTTP/1.1 400 Bad Request
Cache-Control: no-store
Connection: keep-alive
Content-Type: text/html; charset="utf-8"
Client-Date: Wed, 25 Sep 2019 14:35:03 GMT
Client-Peer: 192.1.1.238:443
Client-Response-Num: 2
Client-SSL-Cert-Issuer: /C=US/ST=CO/O=HPE/OU=MSA-Storage/CN=192.1.1.238
Client-SSL-Cert-Subject: /C=US/ST=CO/O=HPE/OU=MSA-Storage/CN=192.1.1.238
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
Client-Transfer-Encoding: chunked
Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * 'self' data:; base-uri 'self'; object-src 'self'
Strict-Transport-Security: max-age=31536000;
Title: 400 Bad Request
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>400 Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
</BODY></HTML>
UNKNOWN: 400 Bad Request - 500 Server closed connection without sending any data back |
Checking vdisks
======> request send
GET https://<host>/api/login/3777d4e5ce3060a2e3601f3e73c84cc2
User-Agent: centreon::plugins::backend::http::useragent

======> response done
```

I think it's easier to duplicate this plugin and manage the few commands that cause problems and maybe the naming of components.

I'm not comfortable enough with git to try to do a merge request and especially not really able to do quality programming.

If you are interseted about this I could help you by making test on this model.

Thank you for your work and involvement in this great project.

Thanks
Aurélien

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by afavre-intersed** [comment]
Hi Quentin,

Sorry I have the same error. I had the full debug in attachment.

command :
`/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::hp::p2000::xmlapi::plugin --hostname <host-ip> --username <username> --password $pass --mode health --proto https --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --ssl=TLSv1 --debug

[p2000-health-debug.txt](https://github.com/centreon/centreon-plugins/files/3656420/p2000-health-debug.txt)

If you would like me to do some modifications for testing, do not hesitate.

Thanks

**Comment by garnier-quentin** [comment]
I have done a new patch. Could you test it ?

**Comment by afavre-intersed** [comment]
Thank you Quentin your changes have fixed the error.

Have a good day.
