### ISSUE TITLE
New plugin GEIST (WatchDog) sensor

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon-plugins#1657]
Hi guys,

New plugin request:

MIB Watchdog 1.2.5: [watchdog-1.2.5.zip](https://github.com/centreon/centreon-plugins/files/3654923/watchdog-1.2.5.zip)
MIB Watchdog 1.5.5: [watchdog-1.5.5.zip](https://github.com/centreon/centreon-plugins/files/3654924/watchdog-1.5.5.zip)

snmpwalk watchdog 1.2.5: [snmpwalk-watchdog_1250.zip](https://github.com/centreon/centreon-plugins/files/3654931/snmpwalk-watchdog_1250.zip)
snmpwalk watchdog 1.5: [snmpwalk-watchdog_wd15.zip](https://github.com/centreon/centreon-plugins/files/3654932/snmpwalk-watchdog_wd15.zip)

**Comment by garnier-quentin** [comment]
You can test it ;)

**Comment by Tpo76** [comment]
Thank you very much! 
All work well 👍
