### ISSUE TITLE
storage-purestorage-restapi-mode-pgroupreplication : undefined value in multiplication

### ISSUE THREAD

**Issue by Schirrms** [centreon/centreon-plugins#1658]
Hi,

First of all, I discovered all your work yesterday, it's fantastic !

We have PureStorage arrays to monitor in Centreon, and this is just  piece of cake with your plugin.

However, we have got  in an 'Unitialized value in multiplication' Error in line 143 of pgroupreplication.pm

I solved it easely (but maybe not wisely ;)), this bug tracker is just for tracking :

```
progress => $entry->{progress} * 100,
--
progress => ($entry->{progress} || 0) * 100,
```

Thanks,

Pascal

**Comment by Sims24** [comment]
Hi @Schirrms , 

Thanks for your help and feedback ! We will fix this

Could you send me an email I think it would be interesting to discuss about iTop and Centreon ;)

Regards
