### ISSUE TITLE
network::f5::bigip::plugin interface check

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#166]
Can you please add interface check to F5 plugin also?
Thanks!

**Comment by garnier-quentin** [comment]
F5 BigIP is a linux. Please use os::linux::snmp::plugin ;)

**Comment by kadrika** [comment]
It does not work, at least not for me, that is why I opened a issue ticket. I get UNKNOWN: Can't construct cache.... And if I want to see interface-list I get UNKNOWN: Can't get interfaces... 
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname=xxx --snmp-version=2c --snmp-community=xxx --mode=list-interfaces.
But the uptime command works.

**Comment by garnier-quentin** [comment]
Maybe you have to choose another oid for --oid-filter and --oid-display.

**Comment by kadrika** [comment]
But shouldn't it show me at least the interface list without --oid-filter or --oid-dispaly?

**Comment by garnier-quentin** [comment]
You need to choose.

**Comment by kadrika** [comment]
I tried, but I still can't get it to work. it works fine with common linux hosts, but for F5 I can't get it to work:

bash-3.2$ ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=interfaces --oid-filter=ifAlias --verbose
UNKNOWN: Can't construct cache... 
bash-3.2$ ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=interfaces --oid-filter=ifName --verbose
UNKNOWN: No entry found (maybe you should reload cache file) 
bash-3.2$ ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=interfaces --oid-filter=ifDesc --verbose
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 878.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 878.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 878.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 878.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 878.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 878.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 878.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/snmp_standard/mode/interfaces.pm line 875.
CRITICAL: Interface '' Status : down (admin: up) - Interface '' Status : down (admin: up) - Interface '' Status : down (admin: up) - Interface '' Status : down (admin: up) - Interface '' Status : down (admin: up) - Interface '' Status : down (admin: up) - Interface '' Status : down (admin: up) |
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : down (admin: up)
Interface '' Status : down (admin: up)
Interface '' Status : down (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : down (admin: up)
Interface '' Status : down (admin: up)
Interface '' Status : down (admin: up)
Interface '' Status : down (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)
Interface '' Status : up (admin: up)

**Comment by garnier-quentin** [comment]
Could you send me a snmpwalk of following oids ?
.1.3.6.1.2.1.2.2
.1.3.6.1.2.1.31

**Comment by garnier-quentin** [comment]
You should use the following options: --oid-filter=ifDescr --oid-display=ifDescr

**Comment by garnier-quentin** [comment]
could you test with following options ?
 --oid-filter=ifDesc --oid-display=ifDesc

**Comment by CFRR** [comment]
garnier-quentin, kadrika answered your request?
i can provide you this information. I'm having my problem.

**Comment by kadrika** [comment]
Hi, I got it to work like this: $USER1$/centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --mode=interfaces --oid-filter=ifDesc --oid-display=ifDesc --interface='^$ARG1$' --name --add-status --critical-status='%{admstatus} ne "up"','%{opstatus} ne "up"' --add-traffic --add-status

**Comment by CFRR** [comment]
kadrika, thanks for the suggestion.
i discover that this problem occurs on version 11.2.0, but in version 11.5.3 works without no errors.
