### ISSUE TITLE
[pfSense] 2 issues + 1 FR

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1660]
Hey fellow dev,
We acquire a brand new router with pfSense to replace Sonicwall
Hardware information : 1 CPU, 1 disk mSATA (pfSense ZFS), 6 ethernet Gbit/s (igb0 -> igb5)
I noticed some issues and I would like some new features
Here the snmpwalk [pfsense.txt](https://github.com/centreon/centreon-plugins/files/3676236/pfsense.txt)

# [os::freebsd::snmp::plugin] 
### ZFS
Can't monitor the space. It was install with ZFS file system. (I have same issue at my home with FreeNAS)
![image](https://user-images.githubusercontent.com/30388990/65969468-1b28cf80-e465-11e9-9090-65014c6b538c.png)

```
-bash-4.2$ ./centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --hostname=IP --snmp-community=public --snmp-version=2c --mode=list-diskspath
List disk path:
'/' [id = 1]
'/dev' [id = 2]
'/tmp' [id = 3]
'/var' [id = 4]
'/zroot' [id = 5]
'/var/run' [id = 6]
'/var/dhcpd/dev' [id = 7]
-bash-4.2$ ./centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --hostname=IP --snmp-community=public --snmp-version=2c --mode=storage --storage=1
UNKNOWN: No storage found. Can be: filters, cache file.
-bash-4.2$ ./centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --hostname=IP --snmp-community=public --snmp-version=2c --mode=storage
OK: Storage '/var/run, type: ufs, dev: /dev/md0' Usage Total: 3.40 MB Used: 112.00 KB (3.21%) Free: 3.29 MB (96.79%) | 'used'=114688B;;;0;3567616
-bash-4.2$ ./centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --hostname=IP --snmp-community=public --snmp-version=2c --mode=list-storages
List storage:
Skipping storage 'Real Memory Metrics': no type or no matching filter type
Skipping storage '/var/dhcpd/dev, type: devfs, dev: devfs': no type or no matching filter type
Skipping storage 'UMA: zio_buf_1024': no type or no matching filter type
Skipping storage 'UMA: zio_data_buf_1024': no type or no matching filter type
Skipping storage 'UMA: zio_buf_1536': no type or no matching filter type
Skipping storage 'UMA: zio_data_buf_1536': no type or no matching filter type
Skipping storage 'UMA: zio_buf_2048': no type or no matching filter type
Skipping storage 'UMA: zio_data_buf_2048': no type or no matching filter type
Skipping storage 'UMA: zio_buf_2560': no type or no matching filter type
Skipping storage 'UMA: zio_data_buf_2560': no type or no matching filter type
Skipping storage 'UMA: zio_buf_3072': no type or no matching filter type
Skipping storage 'UMA: zio_data_buf_3072': no type or no matching filter type
Skipping storage 'UMA: UMA Kegs': no type or no matching filter type
[...]
```
### TCPcon
Like sonicwall I would like to monitor tcp connection
![image](https://user-images.githubusercontent.com/30388990/65962583-502f2500-e459-11e9-8074-5953fdaa8402.png)
There is a mode tcpcon but it seems to be not I want
```
-bash-4.2$ ./centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --hostname=IP --snmp-community=public --snmp-version=2c --mode=tcpcon
OK: Total connections: 1 | 'total'=1;;;0; 'con_closed'=0;;;0; 'con_closeWait'=0;;;0; 'con_synSent'=0;;;0; 'con_established'=1;;;0; 'con_timeWait'=0;;;0; 'con_lastAck'=0;;;0; 'con_listen'=4;;;0; 'con_synReceived'=0;;;0; 'con_finWait1'=0;;;0; 'con_finWait2'=0;;;0; 'con_closing'=0;;;0;
```
# [apps::pfsense::snmp::plugin]
## Feature Request
We switch from sonicwall to pfSense. With Sonicwall I could monitor IPSec VPN by SNMP (status and traffic). Is it possible to have the same thing on ?

# Bonus
There is a REST API (called FauxAPI) for pfSense : https://github.com/ndejong/pfsense_fauxapi
Get gateway status could be great too :-)
![image](https://user-images.githubusercontent.com/30388990/65969070-75756080-e464-11e9-9e1b-5a23d1e613e2.png)

**Comment by garnier-quentin** [comment]
For zfs storage, you can change '--filter-storage-type' option. But we need to known the type. Could you do a snmpwalk on following OID: .1.3.6.1.2.1.25.2.3.1.2 ?
For tcpcon, you can use the freebsd plugin. It will work. But we can add it on pfsense also.

For the 'fauxapi', it's an official api ?

**Comment by oasisck** [comment]
Here the snmpwalk
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/3680114/snmpwalk.txt)

I saw tcpcon mode in FreeBSD but I think this isn't the good result
ATM we're in prod (10 users)
```
-bash-4.2$ ./centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --hostname=IP --snmp-community=public --snmp-version=2c --mode=tcpcon
OK: Total connections: 0 | 'total'=0;;;0; 'con_closed'=0;;;0; 'con_closeWait'=0;;;0; 'con_synSent'=0;;;0; 'con_established'=0;;;0; 'con_timeWait'=0;;;0; 'con_lastAck'=0;;;0; 'con_listen'=4;;;0; 'con_synReceived'=0;;;0; 'con_finWait1'=0;;;0; 'con_finWait2'=0;;;0; 'con_closing'=0;;;0;
```

There isn't official API in pfSense documentation. I guess this is the only and most popular one according to google. It needs an installation in CLI.

**Comment by garnier-quentin** [comment]
I cannot get the snmpwalk. Could you send it to my email ?

**Comment by garnier-quentin** [comment]
For the api, i need the curl commands. And i could develop it.

**Comment by oasisck** [comment]
From the github
The <auth-value> is a ini file in pfsense

# Gateway_status
- Returns gateway status data.
- HTTP: GET
- Params: none
### Example Request
```

curl \
    -X GET \
    --silent \
    --insecure \
    --header "fauxapi-auth: <auth-value>" \
    "https://<host-address>/fauxapi/v1/?action=gateway_status"
```
### Example Response
```

{
  "callid": "598ecf3e7011e",
  "action": "gateway_status",
  "message": "ok",
  "data": {
    "gateway_status": {
      "10.22.33.1": {
        "monitorip": "8.8.8.8",
        "srcip": "10.22.33.100",
        "name": "GW_WAN",
        "delay": "4.415ms",
        "stddev": "3.239ms",
        "loss": "0.0%",
        "status": "none"
      }
    }
  }
}
```

**Comment by garnier-quentin** [comment]
How do you get the fauxapi-auth token ?

**Comment by oasisck** [comment]
https://github.com/ndejong/pfsense_fauxapi#api-authentication

### API Authentication
A deliberate design decision to decouple FauxAPI authentication from both the pfSense user authentication and the pfSense config.xml system. This was done to limit the possibility of an accidental API change that removes access to the host. It also seems more prudent to only establish API user(s) manually via the FauxAPI /etc/fauxapi/credentials.ini file - happy to receive feedback about this approach.

The two sample FauxAPI keys (PFFAexample01 and PFFAexample02) and their associated secrets in the sample credentials.sample.ini file are hard-coded to be inoperative, you must create entirely new values before your client scripts will be able to issue commands to FauxAPI.

You can start your own /etc/fauxapi/credentials.ini file by copying the sample file provided in credentials.sample.ini

API authentication itself is performed on a per-call basis with the auth value inserted as an additional fauxapi-auth HTTP request header, it can be calculated as such:-

`fauxapi-auth: <apikey>:<timestamp>:<nonce>:<hash>`

For example:-
`fauxapi-auth: PFFA4797d073:20161119Z144328:833a45d8:9c4f96ab042f5140386178618be1ae40adc68dd9fd6b158fb82c99f3aaa2bb55`
Where the <hash> value is calculated like so:-

`<hash> = sha256(<apisecret><timestamp><nonce>)`
NB: that the timestamp value is internally passed to the PHP strtotime function which can interpret a wide variety of timestamp formats together with a timezone. A nice tidy timestamp format that the strtotime PHP function is able to process can be obtained using bash command date --utc +%Y%m%dZ%H%M%S where the Z date-time seperator hence also specifies the UTC timezone.

This is all handled in the client libraries provided, but as can be seen it is relatively easy to implement even in a Bash shell script.

Getting the API credentials right seems to be a common source of confusion in getting started with FauxAPI because the rules about valid API keys and secret values are pedantic to help make ensure poor choices are not made.

The API key + API secret values that you will need to create in /etc/fauxapi/credentials.ini have the following rules:-

<apikey_value> and <apisecret_value> may have alphanumeric chars ONLY!
<apikey_value> MUST start with the prefix PFFA (pfSense Faux API)
<apikey_value> MUST be >= 12 chars AND <= 40 chars in total length
<apisecret_value> MUST be >= 40 chars AND <= 128 chars in length
you must not use the sample key/secret in the credentials.ini since they are hard coded to fail.
To make things easier consider using the following shell commands to generate valid values:-

apikey_value
`echo PFFA`head /dev/urandom | base64 -w0 | tr -d /+= | head -c 20``
apisecret_value
`echo `head /dev/urandom | base64 -w0 | tr -d /+= | head -c 60``
NB: Make sure the client side clock is within 60 seconds of the pfSense host clock else the auth token values calculated by the client will not be valid - 60 seconds seems tight, however, provided you are using NTP to look after your system time it's quite unlikely to cause issues - happy to receive feedback about this.

Shout Out: Seeking feedback on the API authentication, many developers seem to stumble here - if you feel something could be improved without compromising security then submit an Issue ticket via Github.

### API Authorization
The file /etc/fauxapi/credentials.ini additionally provides a method to restrict the API actions available to the API key using the permit configuration parameter. Permits are comma delimited and may contain * wildcards to match more than one rule as shown in the example below.

```
[PFFAexample01]
secret = abcdefghijklmnopqrstuvwxyz0123456789abcd
permit = alias_*, config_*, gateway_*, rule_*, send_*, system_*, function_*
comment = example key PFFAexample01 - hardcoded to be inoperative
```

**Comment by garnier-quentin** [comment]
For storage, could you try with following option ?
```
--filter-storage-type='^(hrStorageFixedDisk|hrStorageNetworkDisk|hrFSBerkeleyFFS|hrFSOther)$'
```

Could you provide the snmpwalk for following OIDS: 
.1.3.6.1.2.1.6.13.1.1
.1.3.6.1.2.1.6.19.1.7
.1.3.6.1.2.1.6.20.1.4

**Comment by garnier-quentin** [comment]
I don't understand the auth token.
```
For example:-
fauxapi-auth: PFFA4797d073:20161119Z144328:833a45d8:9c4f96ab042f5140386178618be1ae40adc68dd9fd6b158fb82c99f3aaa2bb55
Where the value is calculated like so:-

<hash> = sha256(<apisecret><timestamp><nonce>)
```

It's a hash with a timestamp ???!!  How the api can validate the authentification ? The time (seconds) will be different when i call and when the api received. And what is 'nonce' ?

**Comment by oasisck** [comment]
Nice !
```
-bash-4.2$ ./centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --hostname=IP --snmp-community=public --snmp-version=2c --mode=storage --filter-storage-type='^(hrStorageFixedDisk|hrStorageNetworkDisk|hrFSBerkeleyFFS|hrFSOther)$' --storage=4
OK: Storage '/, type: zfs, dev: zroot/ROOT/default' Usage Total: 113.33 GB Used: 432.99 MB (0.37%) Free: 112.91 GB (99.63%) | 'used'=454025216B;;;0;121688961024
```
I'm creating a pfSense VM to test API, I'll come back later

**Comment by oasisck** [comment]
timestamp is used for auth (60s delay autorize between client/server)
nonce = unique arbitrary number
here a custom little script (inspiring from https://github.com/ndejong/pfsense_fauxapi_client_bash)
```
#!/bin/bash
# echo PFFA`head /dev/urandom | base64 -w0 | tr -d /+= | head -c 20`
fauxapi_apikey='PFFAgRrsU1liDmccvzglN90S'
# echo `head /dev/urandom | base64 -w0 | tr -d /+= | head -c 60`
fauxapi_apisecret='xlpTl7K60CDi0dxW0YyFTpo7df6pkmVFWmSVVsPLeYmlD45w1HZNJ7DU4rc9'
fauxapi_timestamp=$(date -u +%Y%m%dZ%H%M%S)
fauxapi_nonce=$(head -c 40 /dev/urandom | md5sum | head -c 8)
fauxapi_hash=$(echo -n ${fauxapi_apisecret}${fauxapi_timestamp}${fauxapi_nonce} | sha256sum | cut -d' ' -f1)
fauxapi_auth=${fauxapi_apikey}:${fauxapi_timestamp}:${fauxapi_nonce}:${fauxapi_hash}
curl \
    -X GET \
    --silent \
    --insecure \
    --header "fauxapi-auth: ${fauxapi_auth}" \
    "https://192.168.10.123/fauxapi/v1/?action=gateway_status"

root@centreon:~ # ./fauxapi.sh
{"callid":"5d95b93076839","action":"gateway_status","message":"ok","data":{"gateway_status":{"192.168.10.1":{"monitorip":"192.168.10.1","srcip":"192.168.10.123","name":"WAN_DHCP","delay":"0.663ms","stddev":"0.165ms","loss":"0.0%","status":"none"}}}}
```
needed parameters
- fauxapi_apikey
- fauxapi_secret
- https (default) or http

actions interesting to monitor (http GET)
- gateway_status
- system_stats
- config_backup_list (last one with timestamp)
- rule_get
- system_stats (CPU, mem, temp, uptime, pfstate, pfstatepercent, datetime, mbuf, load_average)
- config_get (maybe IPsec VPN but I have to test it in prod so maybe later)

**Comment by garnier-quentin** [comment]
Have you provided snmpwalk for following OID ?
```
.1.3.6.1.2.1.6.13.1.1
.1.3.6.1.2.1.6.19.1.7
.1.3.6.1.2.1.6.20.1.4
```

**Comment by oasisck** [comment]
Sorry for delay, here it is

.1.3.6.1.2.1.6.13.1.1 => [13.1.1.snmpwalk.zip](https://github.com/centreon/centreon-plugins/files/3874286/13.1.1.snmpwalk.zip)
.1.3.6.1.2.1.6.19.1.7 => tcp.tcpConnectionTable.tcpConnectionEntry.tcpConnectionState = No Such Object available on this agent at this OID
.1.3.6.1.2.1.6.20.1.4 => tcp.tcpListenerTable.tcpListenerEntry.tcpListenerProcess = No Such Object available on this agent at this OID
