### ISSUE TITLE
[os::linux::local::plugin] pending-updates returns uninitialized value

### ISSUE THREAD

**Issue by Psych0meter** [centreon/centreon-plugins#1662]
Maybe I'm not using the plugin correctly, but the mode pending-updates of os::linux::local::plugin returns `Use of uninitialized value $options{"value"} in pattern match (m//) at /root/centreon/centreon-plugins/centreon/plugins/perfdata.pm line 110. `when launched:

```
[root@localhost centreon-plugins]# ./centreon_plugins.pl --plugin "os::linux::local::plugin" --mode pending-updates
Use of uninitialized value $options{"value"} in pattern match (m//) at /root/centreon/centreon-plugins/centreon/plugins/perfdata.pm line 110.
Use of uninitialized value $options{"value"} in pattern match (m//) at /root/centreon/centreon-plugins/centreon/plugins/perfdata.pm line 110.
Use of uninitialized value $options{"value"} in pattern match (m//) at /root/centreon/centreon-plugins/centreon/plugins/perfdata.pm line 110.
OK: Number of pending updates : 3 | 'total'=3;;;0;
```

I've patched the perfdata.pm script line 110 : 

**Original** : `if ($options{value} =~ /[.,]/) {`
**New** :  `if (($options{value}) && ($options{value} =~ /[.,]/)) {`

```
[root@localhost centreon-plugins]# ./centreon_plugins.pl --plugin "os::linux::local::plugin" --mode pending-updates
OK: Number of pending updates : 3 | 'total'=3;;;0;
```

**Comment by garnier-quentin** [comment]
Could you execute following command 'yum check-update 2>&1' and provide me the output result ?

**Comment by Psych0meter** [comment]
[root@localhost centreon]# yum check-update 2>&1
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.dclux.com
 * extras: mirror.dclux.com
 * updates: centos.mirrors.psw.services

azure-cli.x86_64                                                                                 2.0.74-1.el7                                                                               azure-cli
tzdata.noarch                                                                                    2019c-1.el7                                                                                updates
tzdata-java.noarch                                                                               2019c-1.el7                                                                                updates

**Comment by garnier-quentin** [comment]
You can test it. It should be fixed
