### ISSUE TITLE
New plugin Vertiv Liebert PDU 

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon-plugins#1663]
Request for new plugin

Here the snmpwalk: [vertivPDU.zip](https://github.com/centreon/centreon-plugins/files/3682793/vertivPDU.zip)

Here the MIB from what I see you need to use the "LIEBERT-GP-PDU-MIB" file, but I provide you with all I got just in case:
[LGPMIB-WIN_Rev10.zip](https://github.com/centreon/centreon-plugins/files/3682796/LGPMIB-WIN_Rev10.zip)

I downloaded the MIB thru this link:
https://www.vertiv.com/en-us/support/software-download/monitoring/management-information-bases-mibs-for-liebert-products/

**Comment by garnier-quentin** [comment]
You can test it
