### ISSUE TITLE
[network::juniper::ex::plugin] - get members status

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1664]
Hi,
I try to get status of members.
Actually, I have a member down but the modes "interfaces" or "stack" don't provide this information
Here is the information I try to get:
![image](https://user-images.githubusercontent.com/8720203/66142405-a3de7180-e605-11e9-96bf-225e87367290.png)

I don't find in snmpwalk where this information is set
I can send you a full snmpwalk if needed.

Thanks for your help.

**Comment by garnier-quentin** [comment]
A full snmpwalk will help

**Comment by cmeschin** [comment]
I send you in MP.

**Comment by garnier-quentin** [comment]
Could you test with the last version ?

**Comment by cmeschin** [comment]
Thanks. It's OK.
On a Juniper where a member is down:
   CRITICAL: Stack member 'TA3718040402' port 'vcp-255/0/53.32768' operational status: down [admin status: up]

and on another Juniper where all members are ok:
   OK: All stack members are ok

Regards
