### ISSUE TITLE
[os::linux::local::plugin] check_icmp

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1665]
Hello,

Is it possible from poller to execute a check_icmp command through a distant linux server to a target IP address ?
The problem with the cmd-return is that there is no perf data ...

/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl  --plugin=os::linux::local::plugin --mode=cmd-return --hostname=@IP_distant_linux_server --remote --ssh-command=plink  --ssh-option='-l=login' --ssh-option='-pw=password' --command='/usr/lib64/nagios/plugins/check_icmp -H @IP_targetted -n 20 -w 4000,40% -c 5000,70%' --manage-returns='0,OK,Ping#1,WARNING,Ping#2,CRITICAL,Ping#,#3,UNKNOWN,Ping#,UNKNOWN,Command problem'
OK: Ping | 'code'=0;;;;

Thanks

**Comment by garnier-quentin** [comment]
That's not the purpose of cmd-return. You can use nrpe or check_by_ssh.

**Comment by ritouret** [comment]
Thank you Quentin,

But i don't want to use Nagios (Remote Plugin Exchange).
Would it be a new mode in os::linux::local::plugin ?

**Comment by garnier-quentin** [comment]
It's not planned to develop check_icmp. Mabe we can do a check_by_ssh.

**Comment by garnier-quentin** [comment]
add a plugin to execute plugin cmd in ssh/nrpe.

**Comment by garnier-quentin** [comment]
maybe we could test that mode: https://perldoc.perl.org/Net/Ping.html

**Comment by garnier-quentin** [comment]
You can use the mode 'check-plugin'.
