### ISSUE TITLE
apps::protocols::nrpe::plugin Error: (!log_opts) Could not complete SSL handshake with xxxxxxx: 1

### ISSUE THREAD

**Issue by kroem** [centreon/centreon-plugins#1666]
So, recenlty installed a new Centreon instance and not getting NRPE to work. Likely I'm missing something easy (I htink I've seen seen this issue before...) 

How can I pass specific SSL commands to apps::protocols::nrpe::plugin ? 

Centreon end: 
[root@centreon02 ~]# /opt/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --mode=query --hostname=xxxx --custommode=nrpe --command='check_nrpe'
UNKNOWN: No response from remote host.

On the other side: 
Oct 07 15:33:01 cat nrpe[1052885]: Error: (!log_opts) Could not complete SSL handshake with XXXXXXXXXXXXX: 1

**Comment by garnier-quentin** [comment]
Which version of nrpe server ?

**Comment by kroem** [comment]
Forgot that... 
NRPE - Nagios Remote Plugin Executor
Version: 3.2.1

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test with the last version and use following parameters ?
```
--ssl-opt="SSL_version => 'TLSv1'" --ssl-opt="SSL_verify_mode => 0"  --nrpe-version=3
```

You also need to configure your nrpe server (add /etc/nrpe.d/nrpe.cfg):
```
allowed_hosts=YOURIPCLIENT
dont_blame_nrpe=1
ssl_version=TLSv1+
ssl_cipher_list=ALL:!aNULL:!eNULL:!SSLv2:!LOW:!EXP:!RC4:!MD5:@STRENGTH
ssl_cert_file=/etc/ssl/certs/nrpe-selfsigned.crt
ssl_privatekey_file=/etc/ssl/private/nrpe-selfsigned.key
```

**Comment by kroem** [comment]
> 
> 
> I have done a patch. Could you test with the last version and use following parameters ?
> 
> ```
> --ssl-opt="SSL_version => 'TLSv1'" --ssl-opt="SSL_verify_mode => 0"  --nrpe-version=3
> ```
> 
> You also need to configure your nrpe server (add /etc/nrpe.d/nrpe.cfg):
> 
> ```
> allowed_hosts=YOURIPCLIENT
> dont_blame_nrpe=1
> ssl_version=TLSv1+
> ssl_cipher_list=ALL:!aNULL:!eNULL:!SSLv2:!LOW:!EXP:!RC4:!MD5:@STRENGTH
> ssl_cert_file=/etc/ssl/certs/nrpe-selfsigned.crt
> ssl_privatekey_file=/etc/ssl/private/nrpe-selfsigned.key
> ```

Doesn't work?


[root@centreon02 nagios-centreon-check]# /opt/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --mode=query --hostname=xxxxxxxxxxx --custommode=nrpe --command='check_nrpe' --ssl-opt="SSL_version => 'TLSv1'" --ssl-opt="SSL_verify_mode => 0"  --nrpe-version=3
UNKNOWN: Can't use string ("SSL_version => 'TLSv1', SSL_veri"...) as a HASH ref while "strict refs" in use at /opt/centreon-plugins/centreon/plugins/nrpe.pm line 105. 


something wrong in the added code maybe, because I cant run the old query either: 
[root@centreon02 nagios-centreon-check]# /opt/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --mode=query --hostname=xxxxxxxxxxx --custommode=nrpe --command='check_nrpe -n'
UNKNOWN: Can't use string ("") as a HASH ref while "strict refs" in use at /opt/centreon-plugins/centreon/plugins/nrpe.pm line 105.

**Comment by garnier-quentin** [comment]
Sorry it's fixed. Could you test it again ?

**Comment by kroem** [comment]
> 
> 
> Sorry it's fixed. Could you test it again ?

Seems to be working! Thanks!

**Comment by garnier-quentin** [comment]
Great. Thanks for the feedback
