### ISSUE TITLE
Prevent --explode-perfdata-max from creating several identically named metrics

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon-plugins#1667]
Hi,
As discussed with @garnier-quentin on IRC, in some cases,` --explode-perfdata-max` with two arguments will create several metrics when the first argument matches several metrics.

For instance in the following case where `used` matches `used` and `used_prct`, two `total` metrics are created:
```
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory … --warning-usage-prct='90' --critical-usage-prct='95' --explode-perfdata-max='used,total' 
OK: Ram Total: 3.86 GB Used (-buffers/cache): 883.09 MB (22.32%) Free: 3.00 GB (77.68%), Buffer: 320.54 MB, Cached: 510.73 MB, Shared: 45.76 MB | 'used'=925986816B;;;0;4148207616 'free'=3222220800B;;;0;4148207616 'used_prct'=22.32%;0:90;0:95;0;100 'buffer'=336105472B;;;0; 'cached'=535539712B;;;0; 'shared'=47980544B;;;0; 'total'=4148207616;;;; 'total'=100;;;;
```

In such cases, the plugin should exit with an error to prevent the `total` metric to be overridden by a useless metric whose value is always 100.

This is especially problematic because previous versions of the memory plugin only had one metric matching `used` so the `total` metric was fine before the change and I don't think the documentation mentions the fact that the option accepts regexes and doesn't expect exact string matches.

**Comment by garnier-quentin** [comment]
You can use following options now:
```
--explode-perfdata-max='memory.usage.bytes,memory.total.bytes'  --use-new-perfdata
```
