### ISSUE TITLE
Problème avec centreon_windows_snmp.pl depuis mis à jour d'hier

### ISSUE THREAD

**Issue by LLFT** [centreon/centreon-plugins#1668]
## Bug/Question

Bonjour,

J'ai effectué une mise à jour de mon environnement hier début d'après midi, opération que je mène assez souvent. 
Et depuis hier j'obtiens "UNKNOWN: SNMP Table Request : Timeout" à la commande suivante :
`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=cpu --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'  --warning-core='80' --critical-core='90' 
`
Alors que si j'effectue la même commande en ligne de commande sous l'utilisateur centreon j'obtiens bien mon résultat 
`OK: 6 CPU(s) average usage is 5.33 % | 'total_cpu_avg'=5.33%;;;0;100 'cpu_0'=7.00%;0:80;0:90;0;100 'cpu_1'=8.00%;0:80;0:90;0;100 'cpu_2'=4.00%;0:80;0:90;0;100 'cpu_3'=5.00%;0:80;0:90;0;100 'cpu_4'=4.00%;0:80;0:90;0;100 'cpu_5'=4.00%;0:80;0:90;0;100
`

J'ai lu plusieurs issue indiquant ce phénomène comme quoi windows ne gérait plus le snmp, les gros espaces,...

Je veux bien l'entendre mais je ne m'explique pas pourquoi cela fonctionnait depuis plusieurs mois et que maintenant c'est le bazard.

![Annotation 2019-10-09 135722](https://user-images.githubusercontent.com/1227418/66479986-ea1c5080-ea9d-11e9-83a6-b4c615222ee6.png)

**Comment by garnier-quentin** [comment]
I think you execute the wrong command line (because it's a cpu output). Could you try with the memory mode ?

**Comment by LLFT** [comment]
effectivement mauvaise capture d'écran. mais le problème reste le même que ce soit pour la mémoire, le cpu, le swap

![Annotation 2019-10-09 144430](https://user-images.githubusercontent.com/1227418/66482484-53eb2900-eaa3-11e9-9891-8d145a0dde44.png)

![Annotation 2019-10-09 144312](https://user-images.githubusercontent.com/1227418/66482395-24d4b780-eaa3-11e9-8c0a-7aaaf915fbc3.png)

**Comment by garnier-quentin** [comment]
Could you launch the command in a shell ? And try also a snmpwalk on sysdesc OID ? There is something else (if nothing work).

**Comment by LLFT** [comment]
L'ensemble des commandes :

```
[root@centreon-prim plugins]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=cpu --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'
OK: 6 CPU(s) average usage is 12.50 % | 'total_cpu_avg'=12.50%;;;0;100 'cpu_0'=13.00%;;;0;100 'cpu_1'=20.00%;;;0;100 'cpu_2'=10.00%;;;0;100 'cpu_3'=8.00%;;;0;100 'cpu_4'=8.00%;;;0;100 'cpu_5'=16.00%;;;0;100
```
```
[root@centreon-prim plugins]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'
UNKNOWN: SNMP GET Request : Timeout
```
```
[root@centreon-prim plugins]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=swap --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'
UNKNOWN: SNMP Table Request : Timeout
```

```
[root@centreon-prim plugins]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --version
Plugin Version: 0.1

```

**Comment by garnier-quentin** [comment]
Could you try that command ?
```
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public' --snmp-autoreduce
```

**Comment by LLFT** [comment]
Pas mieux, j'ai l'impression d'être revenu sur des versions de script datant d'une autre époque : 

`[root@centreon-prim ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public' --snmp-autoreduce
Unknown option: snmp-autoreduce at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.
`

**Comment by garnier-quentin** [comment]
It's a old version if you don't have that option

**Comment by LLFT** [comment]
J'ai juste mis à jour mon système via "yum update" comme chaque trimestre environ.

**Comment by garnier-quentin** [comment]
Could you show the full package name of centreon-plugin%Windows% ?

**Comment by LLFT** [comment]
how to do ?

**Comment by garnier-quentin** [comment]
You can use that command:
```
rpm -qa | grep centreon-plugin
```

**Comment by LLFT** [comment]
`[root@centreon-prim ~]# rpm -qa | grep centreon-plugin
centreon-plugin-Network-Cisco-Standard-Snmp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191008-132839.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20191002-125310.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191002-125310.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191002-125310.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20191002-125310.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191008-132839.el7.centos.noarch
`

**Comment by garnier-quentin** [comment]
I understand the issue. You have some directory in that directory '/usr/lib/centreon/plugins/' ?
remove it:
```
rm -rf /usr/lib/centreon/plugins/centreon/ /usr/lib/centreon/plugins/os/  /usr/lib/centreon/plugins/storage/  /usr/lib/centreon/plugins/apps/  /usr/lib/centreon/plugins/database/  /usr/lib/centreon/plugins/cloud/  /usr/lib/centreon/plugins/network/  /usr/lib/centreon/plugins/hardware/  /usr/lib/centreon/plugins/snmp_standard/
```

**Comment by LLFT** [comment]
c'est un peu radical ! Je devrais faire quoi ensuite ?

**Comment by garnier-quentin** [comment]
test again the commands after. It should be ok.

**Comment by LLFT** [comment]
Pas de chance

```
[root@centreon-prim ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=cpu --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'
OK: 6 CPU(s) average usage is 5.17 % | 'total_cpu_avg'=5.17%;;;0;100 'cpu_0'=8.00%;;;0;100 'cpu_1'=7.00%;;;0;100 'cpu_2'=4.00%;;;0;100 'cpu_3'=4.00%;;;0;100 'cpu_4'=4.00%;;;0;100 'cpu_5'=4.00%;;;0;100

```
```

[root@centreon-prim ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'
UNKNOWN: SNMP Table Request : Timeout
```
```
[root@centreon-prim ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=swap --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'
UNKNOWN: SNMP Table Request : Timeout

```

**Comment by garnier-quentin** [comment]
Do you have the snmp-autoreduce option ?

**Comment by LLFT** [comment]
la même chose avec l'option.


```
[root@centreon-prim ~]# ls -lha /usr/lib/centreon/plugins/

total 5,1M
drwxr-xr-x. 6 root root 4,0K  9 oct.  15:16 .
drwxr-xr-x. 3 root root   21 14 janv.  2019 ..
-rwxrwxr-x  1 root root 252K  2 oct.  14:57 centreon_centreon_central.pl
-rwxrwxr-x  1 root root 421K  2 oct.  14:57 centreon_centreon_database.pl
-rwxrwxr-x  1 root root 236K  2 oct.  14:57 centreon_centreon_map.pl
-rwxrwxr-x  1 root root 253K  8 oct.  15:33 centreon_centreon_poller.pl
-rwxrwxr-x  1 root root 250K  4 juil. 14:38 centreon_centreon_poller.pl.bak
-rwxrwxr-x  1 root root 574K  2 oct.  14:57 centreon_cisco_standard_snmp.pl
-rwxrwxr-x  1 root root 512K  2 oct.  14:57 centreon_linux_snmp.pl
-rwxrwxr-x  1 root root 340K  2 oct.  14:57 centreon_mysql.pl
-rwxrwxr-x  1 root root 334K 11 janv.  2019 centreon_oracle.pl
-rwxr-xr-x  1 root root  989 21 sept.  2018 centreon_plugins.pl
-rwxrwxr-x  1 root root 270K  2 oct.  14:57 centreon_printers_generic_snmp.pl
-rwxrwxr-x  1 root root 205K  2 oct.  14:57 centreon_protocol_dns.pl
-rwxrwxr-x  1 root root 227K  2 oct.  14:57 centreon_protocol_ftp.pl
-rwxrwxr-x  1 root root 295K  2 oct.  14:57 centreon_protocol_http.pl
-rwxrwxr-x  1 root root 213K  2 oct.  14:57 centreon_protocol_ldap.pl
-rwxrwxr-x  1 root root 258K  2 oct.  14:57 centreon_ups_standard_rfc1628_snmp.pl
-rwxrwxr-x  1 root root 431K  8 oct.  15:33 centreon_windows_snmp.pl
-rw-r--r--  1 root root  18K 21 sept.  2018 changelog
-rwx--x--x  1 root root  59K 25 août   2017 check_centreon_nrpe3
drwxr-xr-x  2 root root   46 21 sept.  2018 contrib
drwxr-xr-x  4 root root   26 21 sept.  2018 docs
drwxr-xr-x  4 root root  107 21 sept.  2018 example
-rw-r--r--  1 root root  12K 21 sept.  2018 LICENSE.txt
drwxr-xr-x  5 root root   48 21 sept.  2018 notification
-rw-r--r--  1 root root 3,2K 21 sept.  2018 README.md

```

**Comment by garnier-quentin** [comment]
Could you do a snmpwalk on following OID ? .1.3.6.1.2.1.25.2.3.1.3

**Comment by LLFT** [comment]
```
[root@centreon-prim ~]# snmpwalk -v 2c -c public  172.19.16.10 .1.3.6.1.2.1.25.2.3.1.3
HOST-RESOURCES-MIB::hrStorageDescr.1 = STRING: C:\\ Label:  Serial Number 4b87ae55
HOST-RESOURCES-MIB::hrStorageDescr.2 = STRING: D:\\ Label:Nouveau nom  Serial Number 78e14fe6
HOST-RESOURCES-MIB::hrStorageDescr.3 = STRING: Virtual Memory
HOST-RESOURCES-MIB::hrStorageDescr.4 = STRING: Physical Memory
```

**Comment by garnier-quentin** [comment]
That's weird. it should work with --snmp-autoreduce option.

**Comment by LLFT** [comment]
J'ai retrouvé dans l'history de le machine ces 2 commandes là :

```
yum --enablerepo=centreon-unstable-noarch update centreon-plugin-Applications-Monitoring-Centreon-Poller
yum --enablerepo=centreon-unstable-noarch update centreon-plugin-Operatingsystems-Windows-Snmp
```

pourrait-elle avoir eu une incidence ?

**Comment by LLFT** [comment]
Bon ! J'ai attaqué le problème sous un autre angle. J'ai redémarré les enregistreurs (les hôtes) puis effectué 2 downgrade

`yum downgrade centreon-plugin-Operatingsystems-Windows-Snmp`

pour obtenir : 
```
[root@centreon-prim ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'  --snmp-autoreduce
OK: Ram Total: 15.87GB Used: 1.03GB (6.47%) Free: 14.85GB (93.53%) | 'used'=1103560704B;;;0;17045192704
[root@centreon-prim ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=swap --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'  --snmp-autoreduce
OK: Swap Total: 18.25 GB Used: 1.12 GB (6.15%) Free: 17.13 GB (93.85%) | 'used'=1204748288B;;;0;19595329536
[root@centreon-prim ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=cpu --hostname=172.19.16.10 --snmp-version='2c' --snmp-community='public'  --snmp-autoreduce
OK: 6 CPU(s) average usage is 5.50 % | 'total_cpu_avg'=5.50%;;;0;100 'cpu_0'=7.00%;;;0;100 'cpu_1'=8.00%;;;0;100 'cpu_2'=4.00%;;;0;100 'cpu_3'=6.00%;;;0;100 'cpu_4'=4.00%;;;0;100 'cpu_5'=4.00%;;;0;100
```
La pile SNMP du serveur était peut-être saturée.

Il me faut maintenant modifier la commande pour inclure  le petit "--snmp-autoreduce"

**Comment by garnier-quentin** [comment]
Great! But it should work the same with last version.

**Comment by LLFT** [comment]
Je viens de faire l'upgrade et cela fonctionne également.

Mais j'ai toujours mon problème à savoir : cela fonctionne en ligne de commande, mais il continu d'afficher "UNKNOWN: SNMP Table Request : Timeout" sous l'interface Web.

**Comment by LLFT** [comment]
Arf ! c'est normal j'ai mis à jour le Prim mais pas les autres pollers.
