### ISSUE TITLE
[cloud::aws::cloudwatch::plugin] Profile option

### ISSUE THREAD

**Issue by Psych0meter** [centreon/centreon-plugins#1669]
Helo,

Is it possible to add a --profile option to use different profile accounts on the same poller ?

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

Credentials are stored in  ~/.aws/credentials (/var/lib/centreon-engine/.aws.credentials)

Regards,

**Comment by garnier-quentin** [comment]
It's only managed by awscli (not paws yet): https://github.com/pplu/aws-sdk-perl/issues/32

**Comment by garnier-quentin** [comment]
it's done. you can test it (--aws-profile=toto)
