### ISSUE TITLE
Feature: check CPU Load on Cisco Catalyst stack.

### ISSUE THREAD

**Issue by PedroMSantosD** [centreon/centreon-plugins#1670]
Hi, I'm trying to monitor  the cpu-load a  Cisco catalist stacked switch, reporting the individual cpuload in 1m, 5m, 15m of each stacked member.

I have been able to extract the temperature from said catalyst and each member, using existing plugin: 
'--plugin' 'network::cisco::standard::snmp::plugin' --mode environment  --component temperature,

I can get cpu time % utilization using the 
centreon::common::cisco::standard::snmp::mode::cpu

but not CPU load.

For the switch, I'm attaching the relevant OIDs via SNMP walk:

[relevant_walks.zip](https://github.com/centreon/centreon-plugins/files/3716395/relevant_walks.zip)

requires values arefor each switch are reported on cpmCPULoadAvg(1|5|15)m OIDs, the entries (list of stacked devices) are on the cpmEntreis and the names for said devices could be extracted for the EntPysicalEntries one.

Thanks in advance.

**Comment by PedroMSantosD** [comment]
Hi, I'm trying to write the plugin myself, but I need advise on the $self->{snmp}->get_table: as per [documentation](https://documentation.centreon.com/docs/centreon-plugins/en/latest/developer/guide.html#libraries-reference), I should receive a hash;

> get_table
Description
Return hash table of SNMP values for SNMP table.

yet, when I assign it on my code

`my $ciscocata_cpmEntries = ".1.3.6.1.4.1.9.9.109.1.1.1.1.2"; # List of Physical devices
my %cpm_entries = $self->{snmp}->get_table(oid => $ciscocata_cpmEntries, nothing_quit=>1) ;
  	#use Data::Dumper;
  	#print Dumper($cpm_entries);
  	#$VAR1 = 'HASH(0xff4eb0)';
        #$VAR2 = undef;`

the execution errs  as follows:

> Reference found where even-sized list expected at ~/centreon-plugins/network/cisco/catalyst/snmp/mode/cpu_load.pm line 87.
UNKNOWN: SNMP Table Request: Cant get a single value.

Can you advise what the snmp->get_table actually returns? is it a reference to hash? a  list maybe? 

Full code (hopefully will do a pull request once it works) [here](https://github.com/PedroMSantosD/centreon-plugins/commit/d4bd280314999ba7a9c19059453e9e12fef85c63#diff-364a92f9739a16ba842b0733368dcff1)

Thanks in advance.

**Comment by garnier-quentin** [comment]
it returns a reference to a hash.

**Comment by PedroMSantosD** [comment]
Thanks @garnier-quentin , I have fixed my code, as reflected on last [push](https://github.com/PedroMSantosD/centreon-plugins/blob/master/network/cisco/catalyst/snmp/mode/cpu_load.pm). 
now I have a big issue with the mapping of options to thresholds, as it seems I cant initialize / refer  to them in a proper manner, that is, although default values are defined, perf_data and threshold comparision fail:

> $ perl centreon_plugins.pl --plugin network::cisco::catalyst::snmp::plugin --mode cpu_load '--hostname' somehost '--snmp-community' 'some_secret'
> OK: CPU Load on all stack members within threshold. | 'C9300-48U_21_load1m'=27;;;; 'C9300-48U_21_load5m'=7;;;; 'C9300-48U_21_load15m'=2;;;; 'C9300-48U_20_load1m'=5;;;; 'C9300-48U_20_load5m'=8;;;; 'C9300-48U_20_load15m'=4;;;; 'C9300-48U_22_load1m'=5;;;; 'C9300-48U_22_load5m'=4;;;; 'C9300-48U_22_load15m'=0;;;; 'C9300-48U_19_load1m'=12;;;; 'C9300-48U_19_load5m'=15;;;; 'C9300-48U_19_load15m'=11;;;;

Is it possible for you to help me find a proper example on how to match options from command line, initialise them with the $self->{perfdata}->threshold_validate, and manipulate them with both, get_perfdata_for_output and threshold_check ?

I have raised this [pull request ](https://github.com/centreon/centreon-plugins/pull/1701 )to help discuss the issue.

Thanks in advance.


Fromthe code:

I have defined my options on the new method:
 ```
   $options{options}->add_options(arguments =>
                                {
                                "warning_1m:i"  	=> { name => 'w_1m', default => 6 },
                                "warning_5m:i"  	=> { name => 'w_5m', default => 4 },
                                "warning_15m:i"		=> { name => 'w_15m', default => 2 },
                                "critical_1m:i"  	=> { name => 'c_1m', default => 8 },
                                "critical_5m:i"  	=> { name => 'c_5m', default => 6 },
                                "critical_15m:i"	=> { name => 'c_15m', default => 4 }
                                });
```
I have added the check_options:

```
    	my @warning_names=('w_1m','w_5m','w_15m');
    	foreach my $option_label (@warning_names) {
	  	 	if (($self->{perfdata}->threshold_validate(label => $option_label, value => $self->{option_results}->{warning})) == 0) {
	  		     $self->{output}->add_option_msg(short_msg => "Wrong $option_label threshold '" . $self->{option_results}->{warning} . "'.");
	  		     $self->{output}->option_exit();
	  		} 		
    	}
    	my @critical_names=('c_1m','c_5m','c_15m');
    	foreach my $option_label (@critical_names) {
	  	 	if (($self->{perfdata}->threshold_validate(label => $option_label, value => $self->{option_results}->{critical})) == 0) {
	  		     $self->{output}->add_option_msg(short_msg => "Wrong $option_label threshold '" . $self->{option_results}->{critical} . "'.");
	  		     $self->{output}->option_exit();
	  		} 		
    	}
```

But from the outcome, this code is unable to match it:
```
		$self->{output}->perfdata_add(
			label => $device_label . $current_device . "_load1m", 
			unit => undef,
			value => $$cpu_load_values{$ciscocata_cpmCPULoadAvg1min}{$load_1m_oid},
            warning => $self->{perfdata}->get_perfdata_for_output(label => 'w_1m'),
            critical => $self->{perfdata}->get_perfdata_for_output(label => 'c_1m'),
            min => undef, 
            max => undef
        );
		$self->{output}->perfdata_add(
			label => $device_label . $current_device . "_load5m", 
			unit => undef,
			value => $$cpu_load_values{$ciscocata_cpmCPULoadAvg5min}{$load_5m_oid},
            warning => $self->{perfdata}->get_perfdata_for_output(label => 'w_5m'),
            critical => $self->{perfdata}->get_perfdata_for_output(label => 'c_5m'),
            min => undef, 
            max => undef
        ); 
		$self->{output}->perfdata_add(
			label => $device_label . $current_device . "_load15m", 
			unit => undef,
			value => $$cpu_load_values{$ciscocata_cpmCPULoadAvg15min}{$load_15m_oid},
            warning => $self->{perfdata}->get_perfdata_for_output(label => 'w_15m'),
            critical => $self->{perfdata}->get_perfdata_for_output(label => 'c_15m'),
            min => undef, 
            max => undef
        ); 
        #	Compare the value with the thresholds.  
        #	and set exit_status accordingly
        if (($exit_status eq 'ok') || ($exit_status eq 'warning')) {
        	my $check1m 	= $self -> {perfdata} -> threshold_check(value => $$cpu_load_values{$ciscocata_cpmCPULoadAvg1min}{$load_1m_oid}, threshold => [ { label => 'c_1m', 'exit_litteral' => 'critical' },{ label => 'w_1m', 'exit_litteral' => 'warning' }]);
        	my $check5m 	= $self -> {perfdata} -> threshold_check(value => $$cpu_load_values{$ciscocata_cpmCPULoadAvg5min}{$load_5m_oid}, threshold => [ { label => 'c_5m', 'exit_litteral' => 'critical' },{ label => 'w_5m', 'exit_litteral' => 'warning' }]);
        	my $check15m 	= $self -> {perfdata} -> threshold_check(value => $$cpu_load_values{$ciscocata_cpmCPULoadAvg15min}{$load_15m_oid}, threshold => [ { label => 'c_15m', 'exit_litteral' => 'critical' },{ label => 'w_15m', 'exit_litteral' => 'warning' }]);
        	my $plaintext 	= join('@', $check1m,$check5m,$check15m);
        	if ($plaintext =~ /critical/) {
        		$exit_status='critical';
        	} elsif (($exit_status eq 'ok')  && ($plaintext =~ /warning/ )) {
        		$exit_status='warning';
        	}
        } 
```

My execution, outcomes like this



And adding single argument helps not:

> $ perl centreon_plugins.pl --plugin network::cisco::catalyst::snmp::plugin --mode cpu_load '--hostname' somehost '--snmp-community' 'some_secret' --warning_1m 1
> OK: CPU Load on all stack members within threshold. | 'C9300-48U_21_load1m'=0;;;; 'C9300-48U_21_load5m'=4;;;; 'C9300-48U_21_load15m'=0;;;; 'C9300-48U_20_load1m'=9;;;; 'C9300-48U_20_load5m'=7;;;; 'C9300-48U_20_load15m'=3;;;; 'C9300-48U_22_load1m'=4;;;; 'C9300-48U_22_load5m'=4;;;; 'C9300-48U_22_load15m'=0;;;; 'C9300-48U_19_load1m'=20;;;; 'C9300-48U_19_load5m'=14;;;; 'C9300-48U_19_load15m'=10;;;;

Adding another arguments, crashes the script:
> $ perl centreon_plugins.pl --plugin network::cisco::catalyst::snmp::plugin --mode cpu_load '--hostname' somehost '--snmp-community' 'some_secret' --warning_1m 1 --warning_5m 2
> argument 2 alone at /home/pesantos/TEST/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 93.

**Comment by PedroMSantosD** [comment]
Hi @garnier-quentin , I have fixed my code and now it works. Is it mandatory to use the template "counters class" to have it merged?

**Comment by garnier-quentin** [comment]
Yes it s

**Comment by PedroMSantosD** [comment]
Hi @garnier-quentin  Class implemeted. Code updated. Kindly check. Best regards,

**Comment by garnier-quentin** [comment]
Could you validate the mode ?
