### ISSUE TITLE
[apps::protocols::snmp::plugin] - mode=string-value  - Treshold don't work correctly

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1673]
Hi,

I use old version of centreon_plugins (2016-01-22) and the string-value mode works correctly with --warning-regexp

If I test with last release of centreon-plugins, it doesn't work.

Here is result of the two version of plugins:
Old version:
`/usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=snmp_standard::plugin --mode=string-value --hostname=X.X.X.X --snmp-community='public' --snmp-version='2c' --snmp-timeout= --oid='1.3.6.1.4.1.2636.3.1.13.1.6.9.2.0.0' --format="le chassis est %s" --map-values='1=>ETAT INCONNU,2=>UP (master),3=>EN ATTENTE (pret),4=>EN ATTENTE (reset),6=>DOWN,7=>UP (backup)' --unknown-regexp='1' --warning-regexp='7' --critical-regexp='[3456]'`

> WARNING: le chassis est UP (backup)

Latest release:
`/usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=string-value --hostname=X.X.X.X --snmp-community='public' --snmp-version=2c --oid='1.3.6.1.4.1.2636.3.1.13.1.6.9.2.0.0' --format-ok='le chassis est %{details_ok}.' --format-warning='le chassis est %{details_warning}' --format-critical='le chassis est %{details_critical}' --format-unknown='le chassis est %{details_unknown}' --warning-regexp='7' --critical-regexp='[3456]' --map-values='1=>ETAT INCONNU,2=>UP (master),3=>EN ATTENTE (pret),4=>EN ATTENTE (reset),6=>DOWN,7=>UP (backup)'`

> OK: le chassis est UP (backup).

Is it a syntax problem or a bug?
regards

**Comment by garnier-quentin** [comment]
In warning-regexp and critical-regexp, you need to use map values.
```
--warning-regexp='UP.*backup' --critical-regexp='EN ATTENTE|DOWN|5'
```

**Comment by cmeschin** [comment]
Ok, it works.
'5' could work because it isn't in map value. it's correct?

Can you update help message to avoid confusion.
the actual help message is:
`--warning-regexp
            Return Warning if an oid value match the regexp.`
`--critical-regexp
            Return Critical if an oid value match the regexp.`
regards

**Comment by garnier-quentin** [comment]
it's correct
