### ISSUE TITLE
--filter-perfdata and --environment

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1676]
Hi,

On master.
Strangely enough, `--filter-perfdata` has no effect with plugin `database::oracle`.
Option is accepted, but nothing is filtered-out.
Any reason why ?

Thank you :+1:

**Comment by CPbN** [comment]
Mmmh more investigation, the fact is that it is incompatible with `--environment=`.
At least using `--environment=` leads to the behavior above.

**Comment by CPbN** [comment]
In addition, using `--environment=` does not seem to be compatible with Perl Connector, am I right ?

**Comment by CPbN** [comment]
Declaring environment variables in `.profile` file of the engine user did the trick.
I then close this issue.

**Comment by garnier-quentin** [comment]
Yes you're right
