### ISSUE TITLE
Huawei iBMC fans - harddisk - cpu timeout

### ISSUE THREAD

**Issue by Vidark-Wyrd** [centreon/centreon-plugins#1678]
Hi,

First, thank you very much for centreon-plugins it's a really good tool.

I open this issue cause I have a Timeout problem with Huawei iBMC.

I check it with snmp v3 SHA et AES.

Ths has worked until the 10 september 2019.

The check command like memory, psu and temperature works great. 

I'm a the latest version of centreon (14.04.04) and centreon-plugin.

Thank you for your help.

Have a nice day.

Vidark

**Comment by Vidark-Wyrd** [comment]
Oh Wouah !
It's work !
Thank you very much.

**Comment by garnier-quentin** [comment]
I would do a patch to optimize OID checking ;)

**Comment by Vidark-Wyrd** [comment]
It will e very cool.

Thank you !

**Comment by garnier-quentin** [comment]
I have done the patch. Could you test with last version ? It should be faster also

**Comment by Vidark-Wyrd** [comment]
I just try and it works like a charm and really faster for harddisk.

But still timeout for cpu and fan without --snmp-autoreduce.

Thanks a lot.

**Comment by garnier-quentin** [comment]
I can't do more. You'll need to use snmp-autoreduce option.

**Comment by Vidark-Wyrd** [comment]
No problem ;)
The most important is that's work !
Thank you.
