### ISSUE TITLE
ESXi monitoring : apps::vmware::connector::plugin mode=net-host

### ISSUE THREAD

**Issue by afrho** [centreon/centreon-plugins#1681]
Hello,

i use centreon_plugins.pl with the vmware connector who works fine.
I have just a question about the monitoring of network cards of ESXi host.

To do this, i use this command :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --mode=net-host --esx-hostname=esxi-hostname --verbose --sampling-period=20

The return is good, with : 

CRITICAL: Host 'esxi-hostname' : physical interface 'vmnic0' status down - physical interface 'vmnic1' status down - physical interface 'vmnic2' status down - physical interface 'vmnic3' status down | 'host_traffic_in'=204800b/s;;;0; 'host_traffic_out'=172032b/s;;;0; 'traffic_in_vmnic4'=73728b/s;;;0;10485760000 'traffic_out_vmnic4'=40960b/s;;;0;10485760000 'packets_dropped_in_vmnic4'=0%;;;0;100 'packets_dropped_out_vmnic4'=0%;;;0;100 'traffic_in_vmnic5'=131072b/s;;;0;10485760000 'traffic_out_vmnic5'=131072b/s;;;0;10485760000 'packets_dropped_in_vmnic5'=0%;;;0;100 'packets_dropped_out_vmnic5'=0%;;;0;100 'vswitch_traffic_in'=204800b/s;;;0; 'vswitch_traffic_out'=172032b/s;;;0;
checking host 'esxi-hostname'
    status connected
    host traffic in : 204.80 Kb/s, host traffic out : 172.03 Kb/s
    physical interface 'vmnic0' status down
    physical interface 'vmnic1' status down
    physical interface 'vmnic2' status down
    physical interface 'vmnic3' status down
    physical interface 'vmnic4' status up, traffic in : 73.73Kb/s (0.00 %), traffic out : 40.96Kb/s (0.00 %), packets in dropped : 0.00 % (0/761 packets), packets out dropped : 0.00 % (0/222 packets)
    physical interface 'vmnic5' status up, traffic in : 131.07Kb/s (0.00 %), traffic out : 131.07Kb/s (0.00 %), packets in dropped : 0.00 % (0/1437 packets), packets out dropped : 0.00 % (0/880 packets)
    vswitch 'vSwitch0' traffic in : 204.80 Kb/s, traffic out : 172.03 Kb/s

Now, my question is : 

how to monitor/output only the vswitch, or the line : host traffic in : 204.80 Kb/s, host traffic out : 172.03 Kb/s

I have many NIC non connected on my esxi and centreon give me CRITICAL status.
I have just need a summary of total bandwidth used by the ESXI.

Someone can help me ?

thank you

**Comment by garnier-quentin** [comment]
You can add following options:
```
--critical-link-status=''
```

**Comment by afrho** [comment]
Works good
Thank you Quentin
