### ISSUE TITLE
New cisco software added 'NOT FUNCTIONING' interface temperatures to temperature oid

### ISSUE THREAD

**Issue by Jassj89** [centreon/centreon-plugins#1682]
Hi

With Cisco 16.11.1c software version they have included Fo ports to SNMP tree for temperatures, example:

SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1086 = STRING: "Fo1/0/1 Module Temperature Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1087 = STRING: "Fo1/0/1 Supply Voltage Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1088 = STRING: "Fo1/0/1 Bias Current Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1089 = STRING: "Fo1/0/1 Transmit Power Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1090 = STRING: "Fo1/0/1 Receive Power Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1092 = STRING: "Fo1/0/2 Module Temperature Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1093 = STRING: "Fo1/0/2 Supply Voltage Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1094 = STRING: "Fo1/0/2 Bias Current Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1095 = STRING: "Fo1/0/2 Transmit Power Sensor, NOT FUNCTIONING "
SNMPv2-SMI::enterprises.9.9.13.1.3.1.2.1096 = STRING: "Fo1/0/2 Receive Power Sensor, NOT FUNCTIONING "

But this messes with the plugin centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --mode=environment that we get 5 instance alerts per port.

Command used in our case:
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --mode=environment --filter=sensor --hostname=x.x.x.x --snmp-version=2c --snmp-community='Something' --verbose --snmp-timeout=10

Is there any easy way to exclude 'NOT FUNCTIONING' from going to warning or make a ranged filter or maybe you have some other idea?
I tried some variants to filter but only way currently found to add all instances to filter, but the list gets very long (Over 50 instances per 4 switch stack)

I have also asked cisco for comments.

**Comment by garnier-quentin** [comment]
You can try with last version:
```
--add-name-instance --filter='temperature,NOT FUNCTIONING'
```
