### ISSUE TITLE
Feature: check Dataguard status for Oracle Databases

### ISSUE THREAD

**Issue by BenPls** [centreon/centreon-plugins#1684]
Hi,

I would like to be able to monitor the Dataguard status for an Oracle database.
I think it can be done with a new mode of "database/oracle" plugin.

There's a table `V$DATAGUARD_STATUS` where we can find the messages and error codes.
For example: 
`SELECT ERROR_CODE, MESSAGE FROM V$DATAGUARD_STATUS WHERE MESSAGE_NUM = (SELECT MAX(MESSAGE_NUM) FROM V$DATAGUARD_STATUS)`

Thanks !

**Comment by garnier-quentin** [comment]
I don't really like that request. We can improve it i think. I prefer requests from check_oracle_health.

For the lag:
```
SELECT
              TO_CHAR(MAX(first_time),'YYYYMMDDHH24MISS'),
              CEIL((SYSDATE - MAX(first_time)) * 24 * 60)
          FROM
              v$archived_log
          WHERE
              applied NOT IN ('NO') AND registrar = 'RFS'
        }
```

For the log transport and mrp status:
```
SELECT
              DECODE(COUNT(*),0,'ARCH','LGWR') AS log_transport
          FROM
              v$managed_standby
          WHERE
              client_process = 'LGWR';

 SELECT
              process, status
          FROM
              v$managed_standby
          WHERE
              process LIKE 'MR%'
```

**Comment by BenPls** [comment]
With 2d00a8d, there is a way to monitor the status.
Thanks!
