### ISSUE TITLE
[apps::centreon::local::mode::metaservice] Sort is not numerical

### ISSUE THREAD

**Issue by BenPls** [centreon/centreon-plugins#1685]
Hi,

I recently found an issue where the MIN and MAX type in metaservices, where the values were sorted alphabetically and not numeracally.

**Comment by garnier-quentin** [comment]
Could you show me an example ?

**Comment by BenPls** [comment]
Sure !

I have 3 services on 3 hosts, with the same metric name ("db_backup_age").
I've create a metaservice, selecting those 3 metrics, and keeping the minimum value.

I've added some "print" and find the following:

The `select` query in the MariaDB returns:
+-----------+--------------------------------+---------------+
| metric_id | metric_name                    | current_value |
+-----------+--------------------------------+---------------+
|      1907 | db_backup_age      |       1900790 |
|      1913 | db_backup_age      |       1900800 |
|      5583 | db_backup_age      |         34431 |
+-----------+--------------------------------+---------------+

Inside the "calculate" function, if the calculation type is "Minimum", after the sort, we have the array:
1900790 
1900800 
34431 

if the calculation type is "Maximum", after the sort, we have the array:
34431 
1900800 
1900790 

I tried changing the code `sort { $a <=> $b }` (instead of `sort`).
With the "Minimum": 
34431 
1900790 
1900800 

With the "Maximum": 
1900800 
1900790 
34431

**Comment by garnier-quentin** [comment]
Thanks. It should be fixed
