### ISSUE TITLE
Arcserve Plugin ? 

### ISSUE THREAD

**Issue by djedje6821** [centreon/centreon-plugins#1687]
Hi,

I am using the last version of your centreon-plugins.
I see in changelog that you add a new plugin :

> 2019-07-04 Quentin Garnier <qgarnier@centreon.com>
>  * Plugin added: Arcseve UDP MSSQL
> 

But I am not able to use it : 
`./centreon_plugins.pl --list-plugin | grep -i arcserve
`
give no result.

I am doing something wrong ? Or it's a bug ?

Thanks,

**Comment by garnier-quentin** [comment]
The plugin is in: apps/backup/

**Comment by garnier-quentin** [comment]
You cannot find it with list plugins. It's a dynamic mode. 
--plugin=database::mssql::plugin --dyn-mode=apps::backup::arcserve::udp::mssql::mode::jobstatus

**Comment by djedje6821** [comment]
Oki, thanks ! 
I have never use dynamic mode, i will try ! Thanks a lot Quentin for all your works ! 
Very very very great jobs
