### ISSUE TITLE
[database::oracle::mode::asmdiskgroupusage] Meaning of "Disk Failure Used"

### ISSUE THREAD

**Issue by BenPls** [centreon/centreon-plugins#1689]
Hi,

What is the meaning of "Disk Failure Used" ('used_failure' perf data)?
Is it "amount of data that can be used safely even with a disk failure"?

If it is, and if the total size of the diskgroup doesn't change, this value should not change either, right?

If the answer is still 'yes', then we have an issue :)

I currently have a diskgroup with redundancy type 'NORMAL' (which means that the total and free sizes are twice the "real" sizes) and the "Disk Failure Used" value changes when the "Disk Used" value changes.

Example 1: 
1 diskgroup with 2 100MB disks, and 40MB of actual data 
In the v$ view ==> Total = 200MB, Free = 120MB and Usable = 60MB.
In the perf data ==> Total = 200MB, Used = 80MB, Free = 120MB, Failure Used = **140MB**

Which is not correct. IMHO, it should be **100MB**.

Now, let's suppose, my actual data is 70MB.
Example 2:
In the v$ view ==> Total = 200MB, Free = 60MB and Usable = 30MB.
In the perf data ==> Total = 200MB, Used = 140MB, Free = 60MB, Failure Used = **170MB**

IMHO, it still should be **100MB**.

Now, comes another problem. 
In the last example, the used size is 140, and the "failure safe" size is 100. One can think the data is at risk! Which is not, since the actual data size is only 70.

Am I correct so far?

**Comment by garnier-quentin** [comment]
used_failure = 'total' - 'USABLE_FILE_MB'.

USABLE_FILE_MB indicates the amount of free space, adjusted for mirroring, that is available for new files to restore redundancy after a disk failure. USABLE_FILE_MB is computed by subtracting REQUIRED_MIRROR_FREE_MB from the total free space in the disk group and then adjusting the value for mirroring. For example, in a normal redundancy disk group where by default the mirrored files use disk space equal to twice their size, if 4 GB of actual usable file space remains, then USABLE_FILE_MB equals roughly 2 GB. You can then add a file that is up to 2 GB. For information about negative values of USABLE_FILE_MB, refer to "Negative Values of USABLE_FILE_MB".

That value changes: https://prutser.wordpress.com/2013/01/03/demystifying-asm-required_mirror_free_mb-and-usable_file_mb/

**Comment by BenPls** [comment]
Thanks for the link.
I think I get what's described in this post.

But I still don't get the meaning of 'used_failure', what does it represent?

**Comment by garnier-quentin** [comment]
It represent used_failure = 'TOTAL' - 'USABLE_FILE_MB'.
So that value should be at the minimum. If you have 100% and you loose a disk, you loose datas.
