### ISSUE TITLE
Performance issue on oracle tablespaceusage on large number of tablespaces

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#1692]
Using the latest version of plugin on a Oracle DB with over 250 tablespaces the plugin runs in timeout. Submitting the new query to the database also creates a heavy load on the DB and puts the DB in distress because sessions remain open. In the version 2019-07-04 before merged modes temp-tablespace and undo-tablespace into tablespace-usage the plugin is working fine.

**Comment by garnier-quentin** [comment]
Could you test with last version ?
