### ISSUE TITLE
Feature: Check UDP connections via SNMP

### ISSUE THREAD

**Issue by BenPls** [centreon/centreon-plugins#1694]
Hi,

I would like to add a new mode to `snmp_standard`, that allows to check for listening connections on a host, via SNMP, based on `snmp_standard::mode::tcpcon`.

Is it possible?
Thanks

**Comment by garnier-quentin** [comment]
tpcon can do that. I don't understand.

**Comment by BenPls** [comment]
It's not the same OIDs.
'.1.3.6.1.2.1.6.*' is for TCP and '.1.3.6.1.2.1.7.*' is for UDP.
The UDP listening ports don't show up with '.1.3.6.1.2.1.6.*'.

**Comment by garnier-quentin** [comment]
For udp ok.
