### ISSUE TITLE
[plugin] MongoDB

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#17]
A link to get an idea of what's possible : https://blog.serverdensity.com/mongodb-monitoring/

**Comment by florian-asche** [comment]
+1

**Comment by garnier-quentin** [comment]
I need NoSQL requests. But i think the following plugin will come in near future.

**Comment by joschi99** [comment]
are there any news about a MongoDB plugin?

**Comment by garnier-quentin** [comment]
It's in the roadmap ;) So it will develop soon

**Comment by joschi99** [comment]
gret news, thanks

**Comment by Sims24** [comment]
@joschi99 just released by @cgagnaire in  database/mongodb/ ;)
