### ISSUE TITLE
Cisco Nexus CPU

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#170]
Hi,
I noticed that the nexus CPU plugin does not work for Nexus6000. Also tested with standard cisco plugin, and have the same problem. 
UNKNOWN: SNMP Table Request: Cant get a single value.

**Comment by garnier-quentin** [comment]
Hi Kadrika,

Could you check the OID manually with snmpwalk please ?

**Comment by kadrika** [comment]
If you mean this OID: 1.3.6.1.4.1.9.9.109.1.1.1.x
then I get No Such Object available on this agent at this OID

**Comment by kadrika** [comment]
Maybe this is the right one: 1.3.6.1.4.1.9.9.305.1.1.1?

**Comment by garnier-quentin** [comment]
Could you walk following OIDs:
.1.3.6.1.4.1.9.9.109.1.1.1.1
.1.3.6.1.4.1.9.2.1

Following oid 1.3.6.1.4.1.9.9.305.1.1.1 has a value ?

Thanks

**Comment by kadrika** [comment]
Hi
[poller ~]$ snmpwalk 1.2.3.4 -v2c -c xxx 1.3.6.1.4.1.9.9.109.1.1.1.1
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1 = No Such Object available on this agent at this OID
[spoller~]$ snmpwalk 1.2.3.4 -v2c -c xxx 1.3.6.1.4.1.9.2.1
SNMPv2-SMI::enterprises.9.2.1 = No Such Object available on this agent at this OID
[poller~]$ snmpwalk 1.2.3.4 -v2c -c xxx 1.3.6.1.4.1.9.9.305.1.1.1
SNMPv2-SMI::enterprises.9.9.305.1.1.1.0 = Gauge32: 5

**Comment by garnier-quentin** [comment]
Thanks. Could you test ?

**Comment by kadrika** [comment]
Yes, it is working! Thanks!!!!!!!
