### ISSUE TITLE
[os::linux::local::plugin] Memory

### ISSUE THREAD

**Issue by Psych0meter** [centreon/centreon-plugins#1709]
Hello,

Is it possible to add MemAvailable in the memory calculation, or as an extra option ?

I have a critical alert on some servers, because a high percentage of the memory is in available. 

e.g. :

```
free -h
total used free shared buff/cache available
Mem: 251G 10G 2.6G 6.9M 238G 227G
```

`CRITICAL: Ram used (-buffers/cache) 233.09 GB (92.59%), Buffer: 11.28 MB, Cached: 16.25 GB |'cached'=17446707200B;;;0 'buffer'=11825152B;;;0 'used'=250282590208B;0;0;0;27030877798`

Regards,

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3240
