### ISSUE TITLE
[Plugin] Sonicwall Email Security

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon-plugins#171]
Hello,

Can you create a plugin for Sonicwall Email Security ?
Here is the OIDs to use : https://thwack.solarwinds.com/thread/25494
snmp_standard mode (cpu/memory/interfaces/storage) should also run.

Regards.

**Comment by garnier-quentin** [comment]
I need snmpwalk and mibs.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
