### ISSUE TITLE
Performance issue on oracle list-tablespaces on large number of tablespaces

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#1713]
Same issue as bug https://github.com/centreon/centreon-plugins/issues/1692

...

Using the latest version of plugin on a Oracle DB with over 250 tablespaces the plugin runs in timeout. 

Is there a reason why in list-tablespaces the display value is returned in lowerCase ? The filter is working only with UpperCase

![image](https://user-images.githubusercontent.com/46994680/68469063-a68e4100-0219-11ea-8e8e-93737ea537a0.png)

![image](https://user-images.githubusercontent.com/46994680/68469073-abeb8b80-0219-11ea-9830-3d68ed71d77b.png)

![image](https://user-images.githubusercontent.com/46994680/68469078-b148d600-0219-11ea-8731-9c6208fc4ac1.png)

**Comment by rmorandell-pgum** [comment]
Thanks, for the lower case change. 

Can you implement the changes from bug #1692 to the list-tablespaces, too ? The tablespaceusages.pm is working fine now. For list-tablespaces i'm using still the old one because the current version goes in timeout like the tablespaceusages before your fix

**Comment by garnier-quentin** [comment]
You can try it.

**Comment by rmorandell-pgum** [comment]
Sorry I do not quite understand. I only see changes to the LoweCase problem in your commit but no changes regarding the performance issue.
Unfortunately, I can not test the fix because the plugin is still going into the timeout.

**Comment by garnier-quentin** [comment]
I have done a new patch with the last version.

**Comment by rmorandell-pgum** [comment]
I'im using the latest version downloaded a few minutes ago. The list-tablespaces plugin goes still in timeout. The tablespaces-usage.pm works fine we the latest patch

**Comment by garnier-quentin** [comment]
That's weird. Because i use the same request.

**Comment by rmorandell-pgum** [comment]
Is there perhaps a commit missing?

the patch for performance issue you made 24.10

![image](https://user-images.githubusercontent.com/46994680/68477553-13133b00-022e-11ea-98b3-3b52013add59.png)

but the list-tablespaces last change was 02.10

![image](https://user-images.githubusercontent.com/46994680/68477608-2f16dc80-022e-11ea-8be9-135ec819ca7e.png)
