### ISSUE TITLE
Switch 3Com SuperStack 3 4250T - UNKNOWN: SNMP Table Request: Cant get a single value

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1716]
Hello.

We have several legacy 48-port switches in production : **Switch 3Com SuperStack 3 4250T (3C17302A)**
They support the **SNMPv1** protocol.
I tried using the plugin **network :: 3com :: snmp :: plugin**, but it does not give a result with any module.

```
# ./centreon_plugins.pl --plugin=network::3com::snmp::plugin --mode=cpu --verbose  
--snmp-version=1 --snmp-community=public --hostname=SoSwitch18                      

UNKNOWN: SNMP Table Request: Cant get a single value.
```

```
# ./centreon_plugins.pl --plugin=network::3com::snmp::plugin --mode=hardware --verbose 
--snmp-version=1 --snmp-community=public --hostname=SoSwitch18

OK: All 0 components are ok []. |
Checking power supplies
Checking fans
```

I tried using another plugin **network :: h3c :: snmp :: plugin**, but it also does not give a result with any module

```
# ./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=cpu --verbose 
--snmp-version=1 --snmp-community=public --hostname=SoSwitch18

UNKNOWN: SNMP Table Request: Cant get a single value.
```

Please tell me how to resolve the issue in this situation.

**Comment by Aleksey-Maksimov** [comment]
Perhaps the **snmpwalk** utility log will give more information : [snmpwalk-3Com4250.log.zip](https://github.com/centreon/centreon-plugins/files/3832582/snmpwalk-3Com4250.log.zip)

**Comment by garnier-quentin** [comment]
That model uses specific mib files. I don't find many informations: 
- stackUnitState (.1.3.6.1.4.1.43.10.27.1.1.1.7): a3com0025
- maybe the fan device state: in that mib 3COM0463.MIB.txt (but i don't find it)
- nothing about cpu/memory

Do you have mibs files ?

**Comment by Aleksey-Maksimov** [comment]
Maybe this information will help us?
[MIBs for HP, H3C and 3Com products Version 4.0 Release Notes (emr_na-c03343049-6.pdf)](https://github.com/centreon/centreon-plugins/files/3835648/Download_emr_na-c03343049-6.pdf)

**Comment by garnier-quentin** [comment]
Not really. For your 3com, OIDs in pdf are not present.

**Comment by Aleksey-Maksimov** [comment]
There are many mib files here:
https://github.com/pgmillon/observium/tree/master/mibs/a3com

**Comment by garnier-quentin** [comment]
I won't find more informations i think.

**Comment by garnier-quentin** [comment]
Could you try the linux snmp plugin ? Maybe some standard snmp modes are working.

**Comment by Aleksey-Maksimov** [comment]
I try to use the **os::linux::snmp::plugin**
No processor information:

```
# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin 
--mode=cpu --verbose 
--snmp-version=1 --snmp-community=public --hostname=SoSwitch04

UNKNOWN: SNMP Table Request: Cant get a single value.
```

No memory information:

```
# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin 
--mode=memory --verbose 
--snmp-version=1 --snmp-community=public --hostname=SoSwitch04

OK: Ram Total: 0.00 B Used (-buffers/cache): 0.00 B (0.00%) 
Free: 0.00 B (0.00%), Buffer: 0.00 B, Cached: 0.00 B, Shared: 0.00 B | 
'used'=0B;;;0;0 
'free'=0B;;;0;0 
'used_prct'=0.00%;;;0;100 
'buffer'=0B;;;0; 
'cached'=0B;;;0; 
'shared'=0B;;;0;
```

Interface names are not displayed:

```
# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin 
--mode=list-interfaces --verbose 
--snmp-version=1 --snmp-community=public --hostname=SoSwitch04

List interfaces:
'' [speed = 100, status = down, id = 101]
'' [speed = 100, status = down, id = 102]
'' [speed = 100, status = down, id = 103]
'' [speed = 100, status = down, id = 104]
'' [speed = 100, status = down, id = 105]
'' [speed = 100, status = down, id = 106]
'' [speed = 100, status = down, id = 107]
'' [speed = 100, status = down, id = 108]
'' [speed = 100, status = up, id = 109]
'' [speed = 100, status = up, id = 110]
'' [speed = 100, status = down, id = 111]
'' [speed = 100, status = up, id = 112]
'' [speed = 100, status = up, id = 113]
'' [speed = 100, status = up, id = 114]
'' [speed = 100, status = up, id = 115]
'' [speed = 100, status = up, id = 116]
'' [speed = 100, status = down, id = 117]
'' [speed = 100, status = up, id = 118]
'' [speed = 100, status = up, id = 119]
'' [speed = 100, status = up, id = 120]
'' [speed = 100, status = up, id = 121]
'' [speed = 100, status = down, id = 122]
'' [speed = 100, status = down, id = 123]
'' [speed = 100, status = down, id = 124]
'' [speed = 100, status = down, id = 125]
'' [speed = 100, status = down, id = 126]
'' [speed = 100, status = down, id = 127]
'' [speed = 100, status = down, id = 128]
'' [speed = 100, status = down, id = 129]
'' [speed = 100, status = down, id = 130]
'' [speed = 100, status = down, id = 131]
'' [speed = 100, status = down, id = 132]
'' [speed = 100, status = up, id = 133]
'' [speed = 100, status = up, id = 134]
'' [speed = 100, status = up, id = 135]
'' [speed = 100, status = up, id = 136]
'' [speed = 100, status = down, id = 137]
'' [speed = 100, status = down, id = 138]
'' [speed = 100, status = up, id = 139]
'' [speed = 100, status = up, id = 140]
'' [speed = 100, status = down, id = 141]
'' [speed = 100, status = up, id = 142]
'' [speed = 100, status = up, id = 143]
'' [speed = 100, status = up, id = 144]
'' [speed = 100, status = up, id = 145]
'' [speed = 100, status = down, id = 146]
'' [speed = 100, status = down, id = 147]
'' [speed = 100, status = down, id = 148]
'' [speed = 1000, status = up, id = 149]
'' [speed = 1000, status = up, id = 150]
'' [speed = , status = up, id = 15000]
'' [speed = , status = up, id = 15001]
'' [speed = , status = down, id = 15512]
'' [speed = , status = down, id = 15513]
'' [speed = , status = down, id = 15514]
'' [speed = , status = down, id = 15515]
'' [speed = 0.0192, status = up, id = 198]
'' [speed = 10, status = up, id = 199]

```

**Comment by Aleksey-Maksimov** [comment]
I found an archive with the **3Com Device Manager** program, which used its SNMP base for monitoring 3Com 4200 series switches and other series. 
I will pack all files that look like mibs: [3Com Device Manager_mib.zip](https://github.com/centreon/centreon-plugins/files/3836014/3Com.Device.Manager_mib.zip) 
Maybe this will help.

**Comment by Aleksey-Maksimov** [comment]
Hello.

I found some information from A3COM0017-STACK-CONFIG.MIB

**Unit Uptime**

From OID stackUnitLastReset.1	in	TimeTicks
The data here matches the standard OID .1.3.6.1.2.1.1.3.0

**Unit Interfaces**

Information about interfaces can be read in the same way as for Linux:

```
/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces 
--add-traffic --warning-in-traffic=98 --warning-out-traffic=98 --units-traffic='%' 
--add-errors --warning-in-error=1 --warning-in-discard=1 --warning-out-error=1 --warning-out-discard=1 
--filter-uom='%'  --snmp-version=1 --snmp-community=X --hostname=X 
--oid-filter=ifDesc --oid-display=ifDesc 
--change-perfdata='_RMON ','_' 
--interface='(unit 2)' --name

```
There is only one problem here. 
Each switch stack displays information about all interfaces in the stack. We need to be able to select a unit on the stack, like --stackunit = 1,3
I solved it with the options  "--interface = '(unit 2)' --name". But this is somehow ugly.

**Unit State**

Other interesting parameters of the unit state. 

stackUnitState.1	unitOperational  (3)	Integer
stackUnitAttention.1	noAttention  (1)	Integer

For example, you can combine these parameters into a new mode ::unitstate

Thanks in advance.

[3com-mibs.zip](https://github.com/centreon/centreon-plugins/files/5388223/3com-mibs.zip)
[A3COM0017-STACK-CONFIG.zip](https://github.com/centreon/centreon-plugins/files/5388225/A3COM0017-STACK-CONFIG.zip)
[A3Com-products-MIB.zip](https://github.com/centreon/centreon-plugins/files/5388226/A3Com-products-MIB.zip)

**Comment by Aleksey-Maksimov** [comment]
Hello, @garnier-quentin 

Is there not enough information in my last message?
Is there a chance to resolve the issue?

**Comment by garnier-quentin** [comment]
yes i think. i could do something. I'm missing time. There are many other issues.

**Comment by Aleksey-Maksimov** [comment]
Hello @garnier-quentin.

I found a large set of MIB files. There is also a file 3Com0025.mib about which you mentioned earlier. 
[3ComMIBS.zip](https://github.com/centreon/centreon-plugins/files/6366283/3ComMIBS.zip)

**Comment by garnier-quentin** [comment]
Nice, i will take a look soon.

**Comment by garnier-quentin** [comment]
It seems we should get informations in following branch:
.1.3.6.1.2.1.47

But it's not in your snmpwalk. Also i need the sysdesc: .1.3.6.1.2.1.1.1

Otherwise you re right. For superstack, we can get only information stackConfigTable (stackUnitState). 
I don't know if we create a mode 'stack' for superstack or a plugin...

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin. 
Not quite sure what I should do to help

**Comment by Aleksey-Maksimov** [comment]
.1.3.6.1.2.1.1.1.0	sysDescr.0	"3Com SuperStack 3"

**Comment by Aleksey-Maksimov** [comment]
It's been a long time. We have few such switches left in a productive environment. 
Therefore, for us, the solution of the issue is no longer relevant and I close the issue. 
Thank you.
