### ISSUE TITLE
[network::digi::anywhereusb::snmp::plugin] interfaces modes won't work for Digi AnywhereUSB/14

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1717]
Hello

We have several devices **Digi AnywhereUSB/14 G2** and we are trying to use the plugin **network::digi::anywhereusb::snmp::plugin** to monitor these devices.

Modes **cpu** and **memory** are working well.

But the **interfaces** and **list-interfaces** modes do not work.

```
# ./centreon_plugins.pl --plugin=network::digi::anywhereusb::snmp::plugin 
--mode=list-interfaces 
--snmp-version=2 --snmp-community=public --hostname=DigiAU001

UNKNOWN: Can't get interfaces...
```

```
# ./centreon_plugins.pl --plugin=network::digi::anywhereusb::snmp::plugin 
--mode=interfaces 
--snmp-version=2 --snmp-community=public --hostname=DigiAU001

UNKNOWN: Can't construct cache...
```

Can you tell me what could be the problem?

In the attachment, the **snmpwalk** utility log : [snmpwalk-Digi-AnywhereUSB14-snmpv2c.log](https://github.com/centreon/centreon-plugins/files/3832511/snmpwalk-Digi-AnywhereUSB14-snmpv2c.log)

**Comment by garnier-quentin** [comment]
Please try following options: --oid-display=ifdesc --oid-filter=ifdesc

**Comment by Aleksey-Maksimov** [comment]
```
# ./centreon_plugins.pl --plugin=network::digi::anywhereusb::snmp::plugin 
--mode=interfaces 
--snmp-version=2 --snmp-community=public --hostname=DigiAU001 
--verbose --oid-display=ifdesc --oid-filter=ifdesc

OK: All interfaces are ok |
Interface 'LOOPBACK' Status : up (admin: up)
Interface 'eth0' Status : up (admin: up)
```

Now we see the interface information.
But unfortunately such information is useless.

Therefore, several questions arise:

1) The **AnywhereUSB/14** device has 2 physical Ethernet ports. One active, the second in standby mode.
How can I monitor **network failover state**?
In the web console, this status looks like this:

![DigiAU14_01](https://user-images.githubusercontent.com/17614847/68662366-b9708080-054d-11ea-808d-d32498f7a537.png)

2) How can we get the **eth0 interface performance**?
For example, it would be interesting to know if there are any errors on the interface and how much the interface bandwidth is utilized.
On the web console, this performance data looks like this:

![DigiAU14_02](https://user-images.githubusercontent.com/17614847/68662393-c2615200-054d-11ea-817d-89a7bd4d2e98.png)

3) Maybe there is some way to get data on the quality of the connection of **USB ports** from remote hosts?

![DigiAU14_03](https://user-images.githubusercontent.com/17614847/68662402-c7be9c80-054d-11ea-94bc-c66d7a33a9a7.png)

If we could solve these issues, then the benefit of the AnywhereUSB monitoring plugin would be really good. What do you think, @garnier-quentin ?

**Comment by garnier-quentin** [comment]
Maybe that information is in SNMP. Could you provide MIB files and full snmpwalk ?

**Comment by Aleksey-Maksimov** [comment]
Cool. We can assume that question 2 has been resolved :)
```
# ,/centreon_plugins.pl --plugin=network::digi::anywhereusb::snmp::plugin 
--mode=interfaces 
--snmp-version=2 --snmp-community=public --hostname=DigiAU001 
--verbose --oid-display=ifdesc --oid-filter=ifdesc --add-errors --add-traffic

OK: All interfaces are ok | 
'traffic_in_eth0'=7052.00b/s;;;0;100000000 
'traffic_out_eth0'=4662.50b/s;;;0;100000000 
'packets_discard_in_eth0'=0.00%;;;0;100 
'packets_error_in_eth0'=0.00%;;;0;100 
'packets_discard_out_eth0'=0.00%;;;0;100 
'packets_error_out_eth0'=0.00%;;;0;100

Interface 'LOOPBACK' Traffic In : skipped, Traffic Out : skipped, 
Packets In Discard : skipped, Packets In Error : skipped, 
Packets Out Discard : skipped, Packets Out Error : skipped
Interface 'eth0' Traffic In : 7.05Kb/s (0.01%), Traffic Out : 4.66Kb/s (0.00%), 
Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), 
Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0)
```

The output of "snmpwalk -ObentU -v 2c -c public DigiAU001 .1" I posted earlier in the file snmpwalk-Digi-AnywhereUSB14-snmpv2c.log

MIB file for Digi so far I could only find such: [DIGI-DEVICE-INFO-MIB (40002410_a.mib).txt](https://github.com/centreon/centreon-plugins/files/3835744/DIGI-DEVICE-INFO-MIB.40002410_a.mib.txt)

**Comment by garnier-quentin** [comment]
In SNMP, there is nothing more. Maybe a ssh cli or rest api available ?

**Comment by Aleksey-Maksimov** [comment]
There is an SSH CLI.
I will open a separate discussion thread for SSH.
I suggest closing this thread of discussion.
