### ISSUE TITLE
AWS : check spot instance number

### ISSUE THREAD

**Issue by julienmathis** [centreon/centreon-plugins#172]
Hello Guys ! 

Is it possible to have the current number of spot instance for a specific region ? possible also to have the number instance by type ? 

exemple : instances=4 m3.medium=3 t2.micro=1

I need it in order to check that all compilation job are well finished :) 

Thanks in advance !

**Comment by garnier-quentin** [comment]
Need to rewrite the plugin with paws: https://github.com/pplu/aws-sdk-perl
