### ISSUE TITLE
[database::oracle::mode::tablespaceusage] Oracle 12c

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#1721]
To monitor tablespace usage on Oracle 12c, we have enhanced the tablespaceusage.pm file like this:

sub manage_selection {
    my ($self, %options) = @_;
    # $options{sql} = sqlmode object
    $self->{sql} = $options{sql};
    $self->{sql}->connect();

    my $query;
    if ($self->{sql}->is_version_minimum(version => '12')) {
		$query = q{
			SELECT
				distinct(cp.PDB)||'_'||tum.tablespace_name "Tablespace",
				t.status "Status",
				t.contents "Type",
				t.extent_management "Extent Mgmt",
				tum.used_space*t.block_size bytes,
				tum.tablespace_size*t.block_size bytes_max,
				tum.tablespace_size
					FROM
					CDB_TABLESPACE_USAGE_METRICS tum
					INNER JOIN
					cdb_tablespaces t on tum.tablespace_name=t.tablespace_name
					INNER JOIN
					v$services cp on cp.CON_ID=tum.CON_ID
					WHERE
					t.contents<>'UNDO'
					OR (t.contents='UNDO' AND t.tablespace_name =(SELECT value FROM v$parameter WHERE name='undo
_tablespace'))
		};
    } elsif ($self->{sql}->is_version_minimum(version => '11')) {
        $query = q{

We would like to hear other people with Oracle 12c instances to validate this code or some DBA with Oracle 12c skills.

jfr

**Comment by garnier-quentin** [comment]
It's for containers ?

**Comment by jframeau** [comment]
Hi Quentin,

yes, it is relative to containers.

**Comment by garnier-quentin** [comment]
i have done a patch for containers
