### ISSUE TITLE
[network::dlink::standard::snmp::plugin] D-Link DES-1210-28 switch

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1723]
Hello.

It looks like the **D-Link DES-1210-28** switch cannot be monitored by any of the plug-in modes

```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin 
--mode=cpu 
--snmp-version=2c --snmp-community=public --hostname=UhSW005

UNKNOWN: SNMP GET Request : Cant get a single value.

```

```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin 
--mode=hardware 
--snmp-version=2c --snmp-community=public --hostname=UhSW005

OK: All 0 components are ok []. |
```

```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin 
--mode=interfaces 
--snmp-version=2c --snmp-community=public --hostname=UhSW005

UNKNOWN: SNMP GET Request : Timeout
```

```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin 
--mode=list-interfaces 
--snmp-version=2c --snmp-community=public --hostname=UhSW005

UNKNOWN: SNMP GET Request : Timeout
```

**Comment by garnier-quentin** [comment]
I need a full snmpwalk to check it.

**Comment by Aleksey-Maksimov** [comment]
[snmpwalk-D-Link-DES-1210-28-SNMPv2c.zip](https://github.com/centreon/centreon-plugins/files/3846122/snmpwalk-D-Link-DES-1210-28-SNMPv2c.zip)

**Comment by Aleksey-Maksimov** [comment]
Hello @garnier-quentin, 
Can I help you with anything else?

**Comment by garnier-quentin** [comment]
Could you try with that plugin ? network/dlink/dgs3100/snmp

**Comment by Aleksey-Maksimov** [comment]
Yes, I tried. The result is the same.

**Comment by garnier-quentin** [comment]
I don't have the same result:
```
# for cpu
UNKNOWN: CPU measurement is not enabled. 

# for hardware
OK: All 0 components are ok []. |
Checking fans
Checking power supplies
```

However there is no information i think. Do you have mibs ?

**Comment by Aleksey-Maksimov** [comment]
http://ftp.dlink.ru/pub/Switch/DES-1210%20Series/SNMP/

**Comment by garnier-quentin** [comment]
I have looked mibs files of your link. I didn't find the mib file with branch:
.1.3.6.1.4.1.171.10.75.18

**Comment by Aleksey-Maksimov** [comment]
Maybe this is the right MIB?
http://ftp.dlink.ru/pub/Switch/DES-1210-28/SNMP/

**Comment by garnier-quentin** [comment]
Yes it's that MIB: http://ftp.dlink.ru/pub/Switch/DES-1210-28/SNMP/DES-1210-28-CX-4-10-002.mib
But i don't find anything useful in it.

**Comment by Aleksey-Maksimov** [comment]
**Uptime**

Name	 sysUpTime
OID	 .1.3.6.1.2.1.1.3.0
MIB	SNMPv2-MIB

------------------------------------------------------
**Time** (status of sync fron NTP Server)

Name	 sysSNTPTimeSeconds.0	
OID	 .1.3.6.1.4.1.171.10.75.18.1.20.17.1.0
Value	 1574438767	
Type	 Integer
MIB	 DES-1210-28_CX

**Comment by Aleksey-Maksimov** [comment]
All interface information available via IF-MIB

**Comment by garnier-quentin** [comment]
You can use dlink standard for interfaces and uptime.

**Comment by Aleksey-Maksimov** [comment]
```
--plugin=network::dlink::standard::snmp::plugin --list-mode
...
Modes Available:
   cpu
   hardware
   interfaces
   list-interfaces
```
no uptime mode and no time mode

**Comment by Aleksey-Maksimov** [comment]
```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin 
--mode=interfaces  
--snmp-version='2c' --snmp-community='public' --hostname=UHWS12         

UNKNOWN: SNMP Table Request : Timeout
```

What am I doing wrong?

**Comment by garnier-quentin** [comment]
Please try with --snmp-autoreduce option

**Comment by Aleksey-Maksimov** [comment]
Yes. With --snmp-autoreduce option, interface information has appeared. It's good.
How about time and uptime modes?

**Comment by garnier-quentin** [comment]
I added uptimes mode.

**Comment by Aleksey-Maksimov** [comment]
Many thanks. The "**uptime**" mode works successfully for all of our D-Link switch models.

What about the "**time**" mode? 
I think that OID will be unique for different models. 
I will try to give you the OIDs from the models that we have. 
Earlier, I already specified OID ".1.3.6.1.4.1.171.10.75.18.1.20.17.1.0" for D-Link DES-1210-28.
What do you think?

**Comment by garnier-quentin** [comment]
I don't know for the time. Maybe it needs to create a specific plugin. But there are so many D-Link MIBS...

**Comment by garnier-quentin** [comment]
Have you tried with last plugin update ?

**Comment by Aleksey-Maksimov** [comment]
Of course. I am constantly updating plugins. The "time" mode for D-Link did not appear. It took a long time, so I thought that there was no point in waiting further, and so I closed the issue. Thanks.

**Comment by garnier-quentin** [comment]
I was thinking cpu, memory, hardware should work now. I didn't look for time issue. That OID '.1.3.6.1.2.1.25.1.2.0' is not present ?

**Comment by Aleksey-Maksimov** [comment]
No chance

```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin --mode=hardware 
--snmp-version=2c --snmp-community=public --hostname=UhSW005 --verbose

OK: All 0 components are ok []. |
checking fans
checking power supplies
checking temperatures
```

```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin --mode=cpu 
--snmp-version=2c --snmp-community=public --hostname=UhSW005 --verbose

UNKNOWN: Cannot find CPU informations
```

```
# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin --mode=memory 
--snmp-version=2c --snmp-community=public --hostname=UhSW005 --verbose

UNKNOWN: SNMP Table Request: Cant get a single value.
```

```
# snmpwalk -ObentU -v 2c -c public UhSW005 .1.3.6.1.2.1.25.1.2.0

.1.3.6.1.2.1.25.1.2.0 = No Such Object available on this agent at this OID

```
I must admit that D-Link has one of the most disgusting SNMP implementations

**Comment by garnier-quentin** [comment]
Maybe there are no informations in MIB for that model. I have done tests on: ```DGS-1510, DGS 3130, DGS-3630```

**Comment by Cool34000** [comment]
Hi,

I'm testing the new plugin version on a DGS-3420-52P...

I'm using this to query hardware:
`/usr/lib/centreon/plugins//centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin --mode=hardware --host=x.x.x.x --snmp-version=2c --snmp-community=public --snmp-autoreduce  --filter=psu,1.2 --threshold-overload='fan,OK,^((speed-.*))' --verbose`
And I'm getting a few errors (Use of uninitialized value):

> Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/network/dlink/standard/snmp/mode/components/fan.pm line 77.
> Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/network/dlink/standard/snmp/mode/components/fan.pm line 77.
> Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/network/dlink/standard/snmp/mode/components/fan.pm line 77.
> OK: All 5 components are ok [3/3 fans, 1/1 psu, 1/1 temperatures]. | '1#hardware.temperature.celsius'=36C;;;; 'hardware.fan.count'=3;;;; 'hardware.psu.count'=1;;;; 'hardware.temperature.count'=1;;;;
> checking fans
> fan 'unit1:fan7' status is speed-low [instance: 1.7, speed: ]
> fan 'unit1:fan8' status is speed-high [instance: 1.8, speed: ]
> fan 'unit1:fan9' status is speed-low [instance: 1.9, speed: ]
> checking power supplies
> power supply 'unit1:psu1' status is 'working' [instance: 1.1, description: -]
> skipping psu section 1.2 instance.
> checking temperatures
> temperature '1' is 36C.
>

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk for following oid: .1.3.6.1.4.1.171.12.11.1.7.1 ?

**Comment by Cool34000** [comment]
Here's the output:
```
# snmpwalk -ObentU -v 2c -c public 192.168.28.253 .1.3.6.1.4.1.171.12.11.1.7.1
.1.3.6.1.4.1.171.12.11.1.7.1.1.1.7 = INTEGER: 1
.1.3.6.1.4.1.171.12.11.1.7.1.1.1.8 = INTEGER: 1
.1.3.6.1.4.1.171.12.11.1.7.1.1.1.9 = INTEGER: 1
.1.3.6.1.4.1.171.12.11.1.7.1.1.1.10 = INTEGER: 1
.1.3.6.1.4.1.171.12.11.1.7.1.2.1.7 = INTEGER: 7
.1.3.6.1.4.1.171.12.11.1.7.1.2.1.8 = INTEGER: 8
.1.3.6.1.4.1.171.12.11.1.7.1.2.1.9 = INTEGER: 9
.1.3.6.1.4.1.171.12.11.1.7.1.2.1.10 = INTEGER: 10
.1.3.6.1.4.1.171.12.11.1.7.1.3.1.7 = INTEGER: 4
.1.3.6.1.4.1.171.12.11.1.7.1.3.1.8 = INTEGER: 4
.1.3.6.1.4.1.171.12.11.1.7.1.3.1.9 = INTEGER: 4
.1.3.6.1.4.1.171.12.11.1.7.1.3.1.10 = INTEGER: 4
.1.3.6.1.4.1.171.12.11.1.7.1.4.1.7 = INTEGER: 3
.1.3.6.1.4.1.171.12.11.1.7.1.4.1.8 = INTEGER: 3
.1.3.6.1.4.1.171.12.11.1.7.1.4.1.9 = INTEGER: 3
.1.3.6.1.4.1.171.12.11.1.7.1.4.1.10 = INTEGER: 3
.1.3.6.1.4.1.171.12.11.1.7.1.5.1.7 = INTEGER: 1
.1.3.6.1.4.1.171.12.11.1.7.1.5.1.8 = INTEGER: 2
.1.3.6.1.4.1.171.12.11.1.7.1.5.1.9 = INTEGER: 3
.1.3.6.1.4.1.171.12.11.1.7.1.5.1.10 = INTEGER: 4
.1.3.6.1.4.1.171.12.11.1.7.1.6.1.7 = INTEGER: 3000
.1.3.6.1.4.1.171.12.11.1.7.1.6.1.8 = INTEGER: 3000
.1.3.6.1.4.1.171.12.11.1.7.1.6.1.9 = INTEGER: 3000
.1.3.6.1.4.1.171.12.11.1.7.1.6.1.10 = INTEGER: 3000

```

**Comment by garnier-quentin** [comment]
Some values are missing. Could you remove the --snmp-autoreduce and use --snmp-force-getnext ?

**Comment by Cool34000** [comment]
Working!
It's also working with both --snmp-autoreduce and --snmp-force-getnext

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
