### ISSUE TITLE
Cant get a single value on snmp v1 only devices while old plugins work

### ISSUE THREAD

**Issue by eLvErDe** [centreon/centreon-plugins#1725]
Hello Centreon,

I have some old devices supporting SNMP v1 only and they use to work just fine with the previous centreon-plugins (the legacy ones):

```
/usr/lib/nagios/plugins/check_centreon_snmp_uptime \
  --hostname  1.2.3.4 \
  --snmp-version 1 \
  --community public --day
OK - Uptime (in day): 33|uptime=33day(s)
```

But they are not working with current centreon plugins:
```
/usr/lib/nagios/plugins/centreon_plugins.pl \
  --plugin snmp_standard::plugin --mode uptime \
  --hostname  1.2.3.4 \
  --snmp-version 1 \
  --snmp-community public
UNKNOWN: SNMP GET Request : Cant get a single value. 
```

If you have any idea I'd be happy to help by providing more information on request.

Best regards

**Comment by garnier-quentin** [comment]
You use a very old version of centreon-plugins. Could you test with the last version ?

**Comment by eLvErDe** [comment]
Hi Quentin, why are you saying that ? It's a Centreon installed using packages, currently at 19.04

**Comment by garnier-quentin** [comment]
it seems like an old one. could you test with last version:
https://github.com/centreon/centreon-plugins/archive/master.zip

**Comment by eLvErDe** [comment]
Well I can but it's not supposed to as it's coming from your yum repo... I'll try

**Comment by garnier-quentin** [comment]
Yes. But that github is not about centreon-packaging ;)

**Comment by eLvErDe** [comment]
Just tried with 20191016 from tags, same error.

**Comment by garnier-quentin** [comment]
I need the result with following command: 
snmpwalk -ObentU -v 2c -c public .1 > uptime.snmpwalk

**Comment by eLvErDe** [comment]
Sent on slack !

**Comment by eLvErDe** [comment]
So Quentin found a way to get these picky devices working correctly.

For uptime:
Add --subsetleef=1 to avoid requesting multiple OIDs at once, which seems unsupported by the target devices

For network interfaces:
Adding --oid-display=ifdesc --oid-filter=ifdesc fixed it

Thanks
