### ISSUE TITLE
AWS : check number of instances for an auto scaling group

### ISSUE THREAD

**Issue by julienmathis** [centreon/centreon-plugins#173]
Hello beautiful guys ! 

I need to check how many instances I have in my auto scaling group. It's very important because my ASG create automaticaly instance when the CPU average is >= to 30 %. And after I have to check that the CPU is not to lower that my 30 % in order to reduce instance number.

I'm sur it's available in the AWS API :)

++

**Comment by garnier-quentin** [comment]
Need to rewrite the plugin with paws: https://github.com/pplu/aws-sdk-perl

**Comment by Sims24** [comment]
https://github.com/cgagnaire/centreon-plugins/commit/a39be73f2e4c3f4666f7b332da419fe6851f30a4
