### ISSUE TITLE
[network::mikrotik::snmp::plugin] --mode=memory --storage

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1730]
Hello

I am trying to use the "memory" mode with the "--storage" option to get information about the used space on the drive.
But for some reason it doesn’t work.

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory --storage 
--snmp-version=2c --snmp-community=public --hostname=UhAP001

UNKNOWN: No storage found. Can be: filters, cache file.
```

Although if we look at the web console, we will see this information. 
And even see the information about bad blocks %.

![MikroTikHDD](https://user-images.githubusercontent.com/17614847/68953558-3a8c7980-07d3-11ea-8096-d69645df3a2b.png)

**Comment by CPbN** [comment]
To monitor memory, simply use :
`--mode=memory --filter-storage-type='^hrStorageRam$'`
And to monitor disk, simply use :
`--mode=memory --filter-storage-type='^(?!(hrStorageRam$))'`
You can also add `--change-short-output=': RAM ~: Disk '` for better short output :+1:

**Comment by Aleksey-Maksimov** [comment]
I tried these options. The result is the same.

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory --storage --filter-storage-type='^hrStorageRam$' 
--warning-usage=90 --critical-usage=98 
--snmp-version=2c --snmp-community=public --hostname=UhAP001

UNKNOWN: No storage found. Can be: filters, cache file.
```

**Comment by CPbN** [comment]
Don't use `--storage`.
Only use the 2 options `--mode` and `--filter-storage-type` as I gave you above.
I monitor dozens of various MikroTik routers like this, should then work on yours ?

**Comment by Aleksey-Maksimov** [comment]
With this combination of options, we get only information about RAM. 
No HDD information here

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory --filter-storage-type='^hrStorageRam$' 
--warning-usage=90 --critical-usage=98 
--snmp-version=2c --snmp-community=public --hostname=UhAP001

OK: RAM 'main memory' Usage Total: 128.00 MB 
Used: 28.61 MB (22.35%) Free: 99.39 MB (77.65%) | 
'used'=29995008B;0:120795955;0:131533373;0;134217728

```
I am interested in information about the drive. 
And so I use the --storage option. But that does not work.

**Comment by CPbN** [comment]
As proposed above, for disks, use :
`--mode=memory --filter-storage-type='^(?!(hrStorageRam$))'`

**Comment by Aleksey-Maksimov** [comment]
Yes. It works with such options. 

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory --filter-storage-type='^(?!(hrStorageRam$))' 
--change-short-output=': RAM ~: Disk ' 
--warning-usage=90 --critical-usage=98 
--snmp-version=2c --snmp-community=public --hostname=UhAP001

OK: Disk 'system disk' Usage Total: 128.00 MB 
Used: 17.22 MB (13.45%) Free: 110.78 MB (86.55%) | 
'used'=18055168B;0:120795955;0:131533373;0;134217728
```

Thanks for your help!

**Comment by Aleksey-Maksimov** [comment]
Hello. 

I already asked a question earlier about getting output from a plugin in memory mode.
And now I ask for help again.

I have many devices : **Wireless Router MikroTik RB951G-2HnD**
I have successfully configured separate monitoring of **RAM** and **DiskDrive** for these devices.


First: "**MikroTik Memory Usage**"

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory 
--critical-usage=98 --warning-usage=90
--snmp-community=public --snmp-version=2c --hostname=UhAP001

OK: RAM 'main memory' Usage Total: 128.00 MB 
Used: 28.30 MB (22.11%) Free: 99.70 MB (77.89%) | 
'used'=29679616B;0:120795955;0:131533373;0;134217728
```

As you can see, everything is fine here. 
And the plugin only returns RAM information

----

Second: "**MikroTik Flash Usage**"

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory --filter-storage-type='^(?!(hrStorageRam))' 
--change-short-output=': RAM ~: Disk ' 
--warning-usage=90 --critical-usage=98 
--snmp-version=2c --snmp-community=public --hostname=UhAP001

OK: Disk 'system disk' Usage Total: 128.00 MB 
Used: 17.25 MB (13.47%) Free: 110.75 MB (86.53%) | 
'used'=18083840B;0:120795955;0:131533373;0;134217728
```

And here, too, everything is as expected. 
We see only disk information.


------
But now I'm trying to connect several devices of another model to the monitoring system: 
**Wireless Router MikroTik RB951Ui-2nD**

And here my whole beautiful story becomes sad :)

My "**MikroTik Memory Usage**" service gives no result

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin
--mode=memory
--critical-usage=98 --warning-usage=90
--snmp-community=public --snmp-version=2c --hostname=EsAP015

UNKNOWN: No storage found. Can be: filters, cache file.
```

And my second service "**MikroTik Flash Usage**" shows information immediately about both memory and disk. 
But it is necessary that there is information only about the disk.

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory --filter-storage-type='^(?!(hrStorageRam))' 
--change-short-output=': RAM ~: Disk ' 
--warning-usage=90 --critical-usage=98 
--snmp-community=public --snmp-version=2c --hostname=EsAP015 
--verbose

OK: All storages are ok | 
'used_system disk'=12038144B;0:15099494;0:16441671;0;16777216 
'used_main memory'=27684864B;0:60397977;0:65766686;0;67108864
RAM 'system disk' Usage Total: 16.00 MB 
Used: 11.48 MB (71.75%) Free: 4.52 MB (28.25%)
RAM 'main memory' Usage Total: 64.00 MB 
Used: 26.40 MB (41.25%) Free: 37.60 MB (58.75%)
```

Please tell me what can be done in this situation. 
How can I configure two **separate services** for **RAM** and **Disk** so that they work for different models of routers.

**Comment by CPbN** [comment]
Add `--show-cache` to your last command and give result ?

**Comment by Aleksey-Maksimov** [comment]
```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin 
--mode=memory 
--filter-storage-type='^(?!(hrStorageRam))' 
--change-short-output=': RAM ~: Disk ' 
--warning-usage=90 --critical-usage=98 
--snmp-community=public --snmp-version=2c --hostname=EsAP015 
--verbose --show-cache

$VAR1 = {
          'relation_storageindex_fsstorageindex' => {},
          'hrstoragedescr_131072' => 'system disk',
          'oid_display' => 'hrstoragedescr',
          'hrstoragedescr_65536' => 'main memory',
          'hrstoragetype_65536' => '.1.3.6.1.2.1.25.2.1.1',
          'hrstoragetype_131072' => '.1.3.6.1.2.1.25.2.1.4',
          'last_timestamp' => 1574176649,
          'oid_filter' => 'hrstoragedescr',
          'all_ids' => [
                         '65536',
                         '131072'
                       ]
        };
```

**Comment by CPbN** [comment]
Strangely, main memory type is `.1.3.6.1.2.1.25.2.1.1`, `hrStorageOther`, not `hrStorageRam` or any other RAM related type...
Simply use `hrStorageOther` in your rules, or open a MikroTik issue so that they use the correct storage type on this device.
Or better first, update RouterOS to the last version, they sometimes make SNMP fixes 😉

**Comment by Aleksey-Maksimov** [comment]
Thanks for the advice. First, we will try to update the firmware version.

**Comment by garnier-quentin** [comment]
Please give us a feedback (if the firmware version fix your issue).

**Comment by Aleksey-Maksimov** [comment]
Oh sure. I will inform you of the result as soon as our network specialist updates the firmware.

**Comment by Aleksey-Maksimov** [comment]
Firmware update on devices with RB951* board solved the problem. 
Thanks for the help.
