### ISSUE TITLE
[hardware::server::dell::idrac::snmp::plugin] iDrac 9 support

### ISSUE THREAD

**Issue by Zoddo** [centreon/centreon-plugins#1732]
Hi,

Looks like the plugin doesn't support iDrac 9 yet.

It currently returns an UNKNOWN state with the following information:
```
UNKNOWN: Power supply 'PS1 Status' status is 'unknown' - Power supply 'PS2 Status' status is 'unknown' - Power unit 'System Board PS Redundancy' state is 'unknown' - Voltage 'PS1 Voltage 1' state is 'unknown' - Voltage 'PS2 Voltage 2' state is 'unknown' - Amperage 'PS1 Current 1' state is 'unknown' - Amperage 'PS2 Current 2' state is 'unknown'
```

If you need a `snmpwalk`, could you tell me which OIDs are needed? Because the whole `1.3.6.1.4.1.674.10892` OID contains too many information; While redacting private information, I can easily miss one.

**Comment by garnier-quentin** [comment]
Please send me by email the full snmpwalk with following command:
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1 > dell_idrac.snmpwalk

**Comment by garnier-quentin** [comment]
Nothing works ? Maybe you can exclude unknown part.

**Comment by Zoddo** [comment]
Hi,

Sorry for the delay, I had to handle other things, and I ended up to forget this issue.
I'll send you the result of this command shortly.

**Comment by garnier-quentin** [comment]
There is an issue with the idrac i think. The status is unknown:
.1.3.6.1.4.1.674.10892.5.4.600.12.1.5.1.1 = INTEGER: 2
.1.3.6.1.4.1.674.10892.5.4.600.12.1.5.1.2 = INTEGER: 2

 ObjectStatusEnum (INTEGER) {other(1), unknown(2), ok(3), nonCritical(4), critical(5), nonRecoverable(6) }

And when i look that oid powerSupplyStateSettingsUnique:
.1.3.6.1.4.1.674.10892.5.4.600.12.1.4.1.1 = INTEGER: 0
.1.3.6.1.4.1.674.10892.5.4.600.12.1.4.1.2 = INTEGER: 0

0 doesn't exist: 
 PowerSupplyStateSettingsUniqueFlags (INTEGER) {unknown(1), onLine(2), notReady(4), fanFailure(8), onlineAndFanFailure(10),
powerSupplyIsON(16), powerSupplyIsOK(32), acSwitchIsON(64), onlineandAcSwitchIsON(66),
acPowerIsON(128), onlineAndAcPowerIsON(130),
onlineAndPredictiveFailure(210),
acPowerAndSwitchAreOnPowerSupplyIsOnIsOkAndOnline(242)
}

You should ask to dell support.
