### ISSUE TITLE
[apps::protocols::ssh::plugin] mode login

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1733]
Hello,

After last update linux server i have this error message :
CRITICAL: connect failed: Received SSH_MSG_DISCONNECT: 3:invalid DH value | 'time'=0.345s;;;0;

Manual login with sftp is working fine.

Here is the last rpm version :
  libssh.x86_64 0:0.9.0-1.el7
  perl-Libssh-Session.x86_64 0:0.6-1.el7

Do you have an idea what's going wrong ?

Thanks

**Comment by garnier-quentin** [comment]
Like that, i don't know

**Comment by ritouret** [comment]
Thank you Quentin.
Do i have to ask Centreon Support to know more than like that ?

**Comment by ritouret** [comment]
Hello,

While waiting to known more, i've downgrade these RPM :
Removed:
  libssh.x86_64 0:0.9.0-1.el7                            perl-Libssh-Session.x86_64 0:0.6-1.el7
Installed:
  libssh.x86_64 0:0.7.5-1.el7.centos                     perl-Libssh-Session.x86_64 0:0.4-1.el7.centos

With these old RPM, plugin is working fine.

**Comment by garnier-quentin** [comment]
I will package the version 0.9.2. Maybe it will fixed it.

**Comment by garnier-quentin** [comment]
You have last rpm here: https://github.com/garnier-quentin/perl-libssh/tree/master/contrib/RPMS
