### ISSUE TITLE
[apps::centreon::local::plugin] mode retention-broker

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1734]
Hello,

Should you add a --remote option to this mode ?
In a Master / Slave architecture, both server could be monitored with this plugin / mode.

Thanks.

**Comment by garnier-quentin** [comment]
You can use broker-stats to check it in SSH.

**Comment by garnier-quentin** [comment]
retention-broker cannot be done in ssh (too complex)
