### ISSUE TITLE
Bug: os::linux::snmp::plugin --mode memory 

### ISSUE THREAD

**Issue by PedroMSantosD** [centreon/centreon-plugins#1735]
## Bug/Question

Hi, i'm using snmp memory plugin to monitor node memory as follows:
```
perl centreon_plugins.pl --critical-usage-prct 100 --hostname some-fqdn-1.test.internal --mode memory --plugin os::linux::snmp::plugin --snmp-autoreduce --snmp-community my-secret-pass --snmp-retries 2 --snmp-version 2c --warning-usage-prct 90
OK: Ram Total: 3.70 GB Used (-buffers/cache): 511.32 MB (13.51%) Free: 3.20 GB (86.49%), Buffer: 302.18 MB, Cached: 1.21 GB, Shared: 190.09 MB | 'used'=536154112B;;;0;3968724992 'free'=3432570880B;;;0;3968724992 'used_prct'=13.51%;0:90;0:100;0;100 'buffer'=316858368B;;;0; 'cached'=1303339008B;;;0; 'shared'=199323648B;;;0;
``` 

The plugin is NOT providing thresholds for the used counter
used'=536154112B**;;;**0

althought it should be able to calculate it based on the threshold precentage that was setted on it:
'used_prct'=13.51%;**0:90;0:100;0;100**

I'm under the impresion that the plugin should automatically calculate the "used" thresholds if used_prct threshold is supplied, which is the way the former version worked.

Best Regards,

**Comment by PedroMSantosD** [comment]
taking it back.
```
--warning-usage 90 --critical-usage 100 --units '%' 
```
fixes my issue

```
| 'used'=2224009216B;;;0;3973603328 'free'=1749594112B;;;0;3973603328 'used_prct'=55.97%;0:90;0:100;0;100 'buffer'=165081088B;;;0; 'cached'=574930944B;;;0; 'shared'=185589760B;;;0;
```

Thanks

**Comment by garnier-quentin** [comment]
I see the issue. I can enhance options to put thresholds on bytes perfdata (with --change-perfdata).

**Comment by PedroMSantosD** [comment]
Hi , thanks @garnier-quentin ; I closed this issue and should have not
the units dont report threshold.
Appreciate is you can reopen, / publish a fix.
Thanks

**Comment by PedroMSantosD** [comment]
Hi @garnier-quentin  any suggestion/example on how to use the --change-perfdata I could copy from ?

**Comment by garnier-quentin** [comment]
I need to do a patch. You cannot add/change warning/critical threshold standalone.

**Comment by moix** [comment]
Interesting, I was dealing with apparently same issue while working on upgrading to latest centreon and I realized that disk-usage thresholds were not any longer present in perf data. I'm afraid is a blocker to me not having it because all my grafana dashboards will not work as expected and miss warning and critical values :(

+1 ;) will be happy to test it as soon as you have a patch for this. Thanks!!

**Comment by garnier-quentin** [comment]
Sorry for the time. You can set it like that for memory:
```--change-perfdata='used$,,,,,,80%,90%' --change-perfdata='free$,,,,,,20%:,10%:'```
