### ISSUE TITLE
Hikvision IP Camera DS-2CD2643G0-IZS monitoring through SNMP

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1736]
Hello

Please add the monitoring implementation of **Hikvision IP cameras** via **SNMP**.
I will attach the MIB files available on the manufacturer’s website.
I will also try to show OIDs that may be useful.
In my example, the device is used - **Hikvision IP Camera DS-2CD2643G0-IZS**

**CPU Usage**:

.1.3.6.1.4.1.39165.1.7.0	cpuPercent.0	= '62 PERCENT'  OctetString	

**Storage Usage**:

.1.3.6.1.4.1.39165.1.8.0	diskSize.0	       = '117.8 GB'  OctetString
.1.3.6.1.4.1.39165.1.9.0	diskPercent.0	= '95 PERCENT'  OctetString

**Memory Usage**:

.1.3.6.1.4.1.39165.1.10.0	memSize.0	= '512 MB'  OctetString
.1.3.6.1.4.1.39165.1.11.0	memUsed.0	= '98 PERCENT'  OctetString

**Current Time**:

.1.3.6.1.4.1.39165.1.19.0	sysTime.0	 = '2019-11-18 19:57:25'  OctetString

[Hikvision-MIB.zip](https://github.com/centreon/centreon-plugins/files/3859857/Hikvision-MIB.zip)
[snmpwalk-Hikvision-DS-2CD2643G0-IZS-SNMPv2c.log](https://github.com/centreon/centreon-plugins/files/3859858/snmpwalk-Hikvision-DS-2CD2643G0-IZS-SNMPv2c.log)

Thanks in advance.

**Comment by garnier-quentin** [comment]
You can test it

**Comment by Aleksey-Maksimov** [comment]
Thanks for your work.

I tested all modes.

---

The "**cpu**" mode works fine:

```
# ./centreon_plugins.pl --plugin=hardware::devices::camera::hikvision::snmp::plugin 
--mode=cpu --warning-usage=90 --critical-usage=99 
--snmp-version=2c --snmp-community=public --hostname=Vcam001

OK: CPU Usage: 62.00 % | 
'cpu.utilization.percentage'=62.00%;0:90;0:99;0;100
```
---

The "**memory**" mode works fine:

```
# ./centreon_plugins.pl --plugin=hardware::devices::camera::hikvision::snmp::plugin 
--mode=memory --warning-usage-prct=90 --critical-usage-prct=98 
--filter-perfdata='(usage.bytes|usage.percentage)' 
--snmp-version=2c --snmp-community=public --hostname=Vcam001

WARNING: Memory Used : 98.00 % | 
'memory.usage.bytes'=526133493B;;;0;536870912 
'memory.usage.percentage'=98.00%;0:90;0:98;0;100
```
If you can, please add more information to the plugin output.
Like this: "WARNING: Memory Total: 512 MB Used: 95.00%"

---

The "**disk**" mode has a problem. 
The full disk capacity is not displayed correctly.

```
# ./centreon_plugins.pl --plugin=hardware::devices::camera::hikvision::snmp::plugin 
--mode=disk --warning-usage-prct=95 --critical-usage-prct=98 
--filter-perfdata='(usage.bytes|usage.percentage)' 
--snmp-version=2c --snmp-community=public --hostname=Vcam001 --verbose

OK: Disk Total: 8.00 GB Used: 7.60 GB (95.00%) Free: 409.60 MB (5.00%) |
'disk.usage.bytes'=8160437862B;;;0;8589934592 
'disk.usage.percentage'=95.00%;0:95;0:98;0;100
```
In our example, the actual disk capacity is 117.8 GB, but it displays as 8GB

```
# snmpwalk -ObentU -v 2c -c public Vcam001 .1.3.6.1.4.1.39165.1.8
.1.3.6.1.4.1.39165.1.8.0 = STRING: "117.8 GB"
```

```
# snmpwalk -ObentU -v 2c -c public Vcam001 .1.3.6.1.4.1.39165.1.9
.1.3.6.1.4.1.39165.1.9.0 = STRING: "95 PERCENT"
```
---

There is no "**time**" mode. 
Can you add it please?

**Comment by garnier-quentin** [comment]
It's fixed. For the time, please string-value from apps::protocols::snmp::plugin

**Comment by Aleksey-Maksimov** [comment]
Thank you @garnier-quentin. 
Now the "**disk**" mode works well.

However, I do not understand what you are suggesting for the "**time**" mode.

I understand that we can use the plugin "**apps :: protocols :: snmp :: plugin**" in order to get some OID from the camera via SNMP. But I do not understand how here we can use the logic of comparing the received time with an NTP server.

```
# ./centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::snmp::plugin 
--mode=string-value --oid '.1.3.6.1.4.1.39165.1.19.0' 
--snmp-version='2c' --snmp-community='public' --hostname=Vcam001 --verbose

OK: 1 value(s) |

```
I do not understand how the proposed plugin can be useful in this case.

**Comment by garnier-quentin** [comment]
Ok. i will do something.

**Comment by garnier-quentin** [comment]
I have done an enhancement of ntp standard mode. You have a time mode. You can test it.

**Comment by Aleksey-Maksimov** [comment]
Hello.

A strange thing happens with the **time** mode.
If we use a monitoring server as a time source, then the plugin does not determine the server timezone (UTC +03:00).

```
# ./centreon_plugins.pl --plugin=hardware::devices::camera::hikvision::snmp::plugin
--mode=time --critical-offset='-180:180' --warning-offset='-60:60'
--hostname=Vcam001 --snmp-community=public --snmp-version=2c 

CRITICAL: Time offset 10800 second(s): Local Time : 2019-11-29T13:08:30 (UTC) | 
'offset'=10800s;-60:60;-180:180;;
```


At the same time, a similar plugin for monitoring **Mikrotik** works successfully in this mode.

```
# ./centreon_plugins.pl --plugin=network::mikrotik::snmp::plugin -
--mode=time --critical-offset='-180:180' --warning-offset='-60:60'
--hostname=UhAP006 --snmp-community=public --snmp-version=2c

OK: Time offset 0 second(s): Local Time : 2019-11-29T13:07:52 (+0300) | 
'offset'=0s;-60:60;-180:180;;
```

**Comment by garnier-quentin** [comment]
Because hikvision doesn't provide the timezone. But you have an option to set it ;)

**Comment by Aleksey-Maksimov** [comment]
I get it. Thank you very much for the plugin. Everything works!
