### ISSUE TITLE
[apps::tomcat::jmx::plugin] - new mode to monitor "connection pool"

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1740]
It should be useful to add a new mode to monitor the connection pool through Jolokia.

**Comment by garnier-quentin** [comment]
I need the list-attributes results and mbean to check.

**Comment by joschi99** [comment]
Hi @garnier-quentin,
excuse me, I misunderstand something. It is not related to Jolokia, but to Oracle DB. Should I open a new ticket for them?

**Comment by garnier-quentin** [comment]
Yes. But i get datas from Jolokia

**Comment by joschi99** [comment]
I did not understand very well your answer. As I know the Oracle Connection Pool can be monitored on Oracle (https://oracle-base.com/articles/11g/database-resident-connection-pool-11gr1). I'm not sure if Jolokia has also information about this.
We have the problem that on a Oracle Database Connection Pool is configured, the application which is requesting the connection are under Tomcat/Weblogic. So we need to monitor the usage of the "Oracle Connection Pool" filtering optionally for different Oracle users.

**Comment by joschi99** [comment]
On the other site seem's that also on Tomcat are connection pools (http://www.jcgonzalez.com/java-monitor-jdbc-connection-pool-servlet)

**Comment by garnier-quentin** [comment]
So that's why i need all JMX attributes. Maybe informations are in mbeans.

**Comment by joschi99** [comment]
Ok, I understand. I will update you as soon as possible. Thanks

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
