### ISSUE TITLE
[storage::dell::me4::SNMP::plugin] missing

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#1742]
Got a new bad boy at work => Dell ME4024
API works great but it lacks some informations like traffic on 8 interfaces.
Here a full (a .1 not a traditional .1.3.6.1.4.1 because this path doesn't exist) snmpwalk => [dell_ME4.zip](https://github.com/centreon/centreon-plugins/files/3874263/dell_ME4.zip)

Thanks

**Comment by garnier-quentin** [comment]
Maybe we can have that information with the Rest API. Could you provide me the curl commands of following api endpoint ?
/api/show/host-port-statistics
/api/show/host-phy-statistics

**Comment by oasisck** [comment]
Sure, just emailed you
