### ISSUE TITLE
Snmp linux mode memory negative buffers/cache

### ISSUE THREAD

**Issue by apiovh** [centreon/centreon-plugins#1744]
Hello,

we have trouble with one server out of 200 in total, all us server have the same command to check memory but for one of them it return a negative output for buffers/cache, it's the only Centos (ver 7.7.1908) we have.

The command we use is this:

`centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=***.***.***.*** --snmp-community=*** --snmp-version=*** --swap --warning-usage=80 --critical-usage=90 --warning-swap=80 --critical-swap=90`

And the output is the following:
`CRITICAL: Ram Total: 5.83 GB Used (-buffers/cache): -3.02 GB (-51.77%) | 'total'=6256230400B;;;0; 'used'=-3238608896B;0:5004984320;0:5630607360;0;6256230400 'buffer'=0B;;;0; 'cached'=4051623936B;;;0; 'shared'=328278016B;;;0; 'swap'=105906176B;0:4294964019;0:4831834521;0;5368705024`

The "used" return is negative and buffers/cache too.

Do not hesitate if you need additional information.

Regards,

**Comment by garnier-quentin** [comment]
It's a known issue. Please try --autodetect-redhat option.

**Comment by apiovh** [comment]
Oh thanks, I hadn't seen it, sorry

But it works well, thanks you. I close th request.

Regards,
