### ISSUE TITLE
database::mssql::plugin --mode=sql-string

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon-plugins#1745]
Hello

I'm trying to execute a stored procedure in a MSSQL server and it doesnt work.
I have the latest centreon-plugins version.

Tried a simplest request and it's the same.

./centreon_plugins.pl --plugin=database::mssql::plugin --mode=sql-string --hostname XXXX --username YYYYY --password "ZZZZZ" --sql-statement "select 1" --port 1433

Use of uninitialized value in hash element at /tmp/centreon-plugins/centreon/common/protocols/sql/mode/sqlstring.pm line 151.
Use of uninitialized value in hash element at /tmp/centreon-plugins/centreon/common/protocols/sql/mode/sqlstring.pm line 151.
Use of uninitialized value in concatenation (.) or string at /tmp/centreon-plugins/centreon/common/protocols/sql/mode/sqlstring.pm line 151.
OK: string : skipped (no value(s)) |

Any ideas ?

Kind regards

Bruno

**Comment by CPbN** [comment]
I think you missed this in the help :
```
    --value-column
            Value column (must be one of the selected field). MANDATORY
```

**Comment by gerpion** [comment]
Of course :D

Thanks it's working
