### ISSUE TITLE
MikroTik --absent-problem

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1746]
Hi,

In plugin `network::mikrotik::snmp`, mode `environment`.
There is the option `--absent-problem` in help.
However I see no component calling `absent_problem` function (from hardware template).
Perhaps then `--absent-problem` is not used here ?
Or perhaps I missed something ?
Could you confirm please ?
If not used, perhaps it's better to remove it from the help section ?

Thank you very much 👍

**Comment by garnier-quentin** [comment]
thanks!
