### ISSUE TITLE
[network::checkpoint::snmp::plugin] mode cpu - Add detail by cpu

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1748]
Hi,

Is it possible to add perfdata detailled by cpu?
Currently, we have the average for cpuUser, cpuSys and cpuIdle
It would be usefull having those values by cpu, like this:
cpuUser_0, cpuSys_0, cpuIdle_0, cpuUser_1, cpuSys_1, cpuIdle_1, etc...
and always global metrics like currently.

It's can be activated by adding an option like --detailled for example.

Regards.

**Comment by garnier-quentin** [comment]
We don't have the details by cpu. Only global.
