### ISSUE TITLE
[network::hp::procurve::snmp::plugin] mode=environment. Why option "--filter" does not work

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1749]
Hello

I am trying to use the "**environment**" mode to get the state of the components of the **HP ProCurve 2824** switch. 
The switch has only one power supply. 
The second power supply is not installed in the switch.
I'm trying to filter out this second power supply, but it doesn’t work for me.

```
# ./centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin 
--mode=environment --no-component --verbose
--filter='psu,3' 
--filter-perfdata='^(?!count_)'
--snmp-version=2c --snmp-community=public --hostname=Vsw002


WARNING: power supply sensor 'power supply.3' state is not present |
Checking sensors
fan sensor 'fan.1' state is good [instance: fan.1].
power supply sensor 'power supply.2' state is good [instance: power supply.2].
power supply sensor 'power supply.3' state is not present [instance: power supply.3].
temperature sensor 'temperature.4' state is good [instance: temperature.4].
Checking power supply
Checking fans
```

I also tried to use --filter='psu,power supply.3'
But this is also unsuccessful.

Please tell me what I'm doing wrong.

**Comment by garnier-quentin** [comment]
You can use following option: --filter='sensor,power supply.3' ?

**Comment by Aleksey-Maksimov** [comment]
Yes. It works now. 
Thank you so much.
