### ISSUE TITLE
[network::ruckus::scg::snmp::plugin] Ap-status on VsZ

### ISSUE THREAD

**Issue by jeremyit** [centreon/centreon-plugins#1751]
Hi,
Does Ruckus plugins work with Virtual smartzone product ?
I've tried with different mode, but only uptime is ok. Unfortunately Ap-status give me:'UNKNOWN: SNMP Table Request: Cant get a single value.

**Comment by garnier-quentin** [comment]
Maybe not. Could you provide mibs files and snmpwalk ?
snmpwalk -ObentU -v 2c -c public IP .1 > ruckus.snmpwalk

**Comment by jeremyit** [comment]
Mib files here, 

[Ruckus_SZ_5_1_2_Mib_20190530.zip](https://github.com/centreon/centreon-plugins/files/3898622/Ruckus_SZ_5_1_2_Mib_20190530.zip)

**Comment by garnier-quentin** [comment]
I need the snmpwalk also

**Comment by jeremyit** [comment]
Ok, this is it. Anonymized
[snmpwalkruckus.zip](https://github.com/centreon/centreon-plugins/files/3902420/snmpwalkruckus.zip)

**Comment by garnier-quentin** [comment]
Thanks. Could you test the plugin ?

**Comment by jeremyit** [comment]
I have tested, it's OK for all mode.

**Comment by garnier-quentin** [comment]
thanks for the feedback!

**Comment by steaksauce-** [comment]
We have a use for this and by coincidence it was recently added. Thanks for the hard work! I'll let you know how it goes after we test it.

**Comment by steaksauce-** [comment]
@jeremyit are you guys using virtualSmatZones or "normal" ones?

**Comment by jeremyit** [comment]
Tested and working on VsZ 5.1.2.0.302

**Comment by steaksauce-** [comment]
`vSZ Version: 5.2.0.0.699` here.

Also worth noting that I am looking at the mibs from Ruckus' website, and there there are differences between `vSZ-e` (which we do NOT use), and the `vSZ-h` which we are using.

Even so, the documentation states that their documentation for `vSZ-h` states that `ruckusSCGCPUPerc` is at `.1.3.6.1.4.1.25053.2.10.2.17`. If I try to `snmpget` this:

>SNMPv2-SMI::enterprises.25053.2.10.2.17 = No Such Object available on this agent at this OID
