### ISSUE TITLE
Bug in hardware template (and in many other places ?)

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1753]
Hi,

I faced the following bug.
In `network::juniper::common::junos::mode::hardware.pm`, component `operating`.
I have a fan _runningAtFullSpeed_, which should then lead to a `WARNING` status.
But `OK` is returned.
This is due to the fact that _running_ status returns `OK` (updating it changes the returned status).
A non-anchored regex matching must then be done, instead of an anchored or literal one.
I'm afraid this could also be the case with `fru` component, see _online*_ / _offline*_ status.
I'm also afraid this could more globally occur in other templates / plugins / modes, where this code structure / writing could be used 😕

Thank you 👍

**Comment by garnier-quentin** [comment]
Thanks. it's fixed. fru doesn't have that problem. I know that constraint. I have done a mistake here. It shouldn't be on other modes

**Comment by CPbN** [comment]
Thank you Quentin, it now works as expected.
I initially thought the problem could have been bigger.
Good news then.
Thx for the patch 👍
