### ISSUE TITLE
[database::influxdb] --<criticity>-status declared 2 times

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-plugins#1755]
Hi,

In `database::influxdb`, mode `query`.
We have in help :
```
    --warning-status
            Set warning threshold for status (Default: '').

            Can use special variables like %{instance} and any other labels
            you set through --query.

    --critical-status
            Set critical threshold for status (Default: '').

            Can use special variables like %{instance} and any other labels
            you set through --query.
```

However, we also have in the same mode's help :
```
    --unknown-status
            Threshold warning for http response code. (Default:
            '%{http_code} < 200 or %{http_code} >= 300')

    --warning-status
            Threshold warning for http response code.

    --critical-status
            Threshold critical for http response code.
```

Note that `--unknown-status` is simply not recognized as an option.

I see 2 options :
- the HTTPlib options are simply enforced, not user-configurable, so should be removed from the help section ;
- the HTTPlib options can be user-configurable, so mode options should have their name changed, and HTTPlib options should be set as tunable.

Many thanks 👍

**Comment by garnier-quentin** [comment]
It should be ok now

**Comment by CPbN** [comment]
I confirm it works perfectly !
Many thanks Quentin 👍
