### ISSUE TITLE
[database::oracle::mode::tablespaceusage] Service Status not conform

### ISSUE THREAD

**Issue by jeremyit** [centreon/centreon-plugins#1756]
Tablespaceusage check command give always 'OK' status

`Statut du service | OK  | 
Statut détaillé | WARNING: Tablespace 'tbs_blob' Total: 160.00 GB Used: 149.10 GB (93.18%) Free: 10.90 GB (6.82%)`

There is no notification sent

**Comment by garnier-quentin** [comment]
Could you execute in command line and provide the return code ?

**Comment by jeremyit** [comment]
`./centreon_plugins.pl  --environment=/usr/lib/oracle/19.5/client64/  --plugin=database::oracle::plugin --mode=tablespace-usage --hostname=mydb --port=1521 --sid=MySID --username=centreon --password=password --warning-tablespace=90 --critical-tablespace=95 --filter-tablespace=TBS_BLOB
WARNING: Tablespace 'tbs_blob' Total: 160.00 GB Used: 149.10 GB (93.18%) Free: 10.90 GB (6.82%) | 'tbs_tbs_blob_usage'=160089686016B;0:154618748928;0:163208679424;0;171798609920
`

**Comment by garnier-quentin** [comment]
And the return code is 1?

**Comment by jeremyit** [comment]
I don't see it in shell.

**Comment by jeremyit** [comment]
Ok sorry,

So return code is 127 with  --filter-tablespace  and 1 whitout

**Comment by garnier-quentin** [comment]
So it's not an issue with centreon-plugins. you are in the wrong github (you should be on centreon-broker maybe).

**Comment by jeremyit** [comment]
News about my research... Not a centreon Issue but about plugin or environnement.
When I gave you return code I was as root user. Cli as centre-engine user : return code 139 "erreur de segmentation".
I had same problem with a nagios check_oracle_health plugin, I add a parameter to the command : --method sqlplus. It's now fixed for the nagios plugin but centreon plugin has not sqlplus method in list-mode

**Comment by garnier-quentin** [comment]
do you use the last version of oracle plugin ? I have fixed that.

**Comment by jeremyit** [comment]
I installed plugin 25th november.
Just updated plugin, now it's works!
Fixed.
