### ISSUE TITLE
Get broker-stats: Host key verification failed.

### ISSUE THREAD

**Issue by Meistercoach83** [centreon/centreon-plugins#1757]
Hey! I try to get the broker-stats from a remote poller. Calling it directly in the shell:
`/usr/lib/centreon/plugins//centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --hostname=***** --mode=broker-stats --broker-stats-file='/var/lib/centreon-engine/*-module-stats.json' --filter-name='' --warning-speed-events='' --critical-speed-events='' --warning-queued-events='' --critical-queued-events='' --warning-unacknowledged-events='' --critical-unacknowledged-events='' --warning-status='' --critical-status='%{type} eq "output" and %{queue_file_enabled} =~ /yes/i' --verbose --remote --ssh-option='-l=centreon'`

works fine - but in the web interface i get an 

> UNKNOWN: Command error: Host key verification failed.

A connection via ssh centreon@***** is working as expected.
What can I do to solve this?

**Comment by garnier-quentin** [comment]
You need to test the command with centreon-engine user.

**Comment by Meistercoach83** [comment]
isn´t that the user "centreon"? i installed from iso...

**Comment by garnier-quentin** [comment]
Plugins are executed by centengine process. And the user of centengine process is 'centreon-engine'.

**Comment by Meistercoach83** [comment]
Sorry to ask again.. but I didn´t get that running. Do I have to add a passwd for centreon-engine on the poller and add the autologin for ssh like I did for the user centreon?

**Comment by garnier-quentin** [comment]
You need to test the ssh connection with centreon-engine user on your poller. If it's working, try with the plugin (still with the user centreon-engine). Maybe you'll need that option: ```--ssh-option='-l=centreon-engine'```

**Comment by bgamer972** [comment]
try
https://docs.centreon.com/pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central/#ssh-key-exchange
