### ISSUE TITLE
[os::linux::snmp::plugin] --mode=storage - Use of uninitialized value

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1758]
Hi,

Since few days I use --add-access option to check ReadWrite is enable on disks.
`
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=X.X.X.X --snmp-version='2c' --snmp-community='XXXXXX' --snmp-timeout=5 --storage '/tmp' --name --space-reservation='5' --display-transform-src='' --display-transform-dst='' --warning-usage='85' --critical-usage='90' --units='%' --add-access --critical-access=@2:2 --filter-perfdata='(used|size)'`

The result is:

> Use of uninitialized value $1 in concatenation (.) or string at /usr/lib/centreon/plugins/centreon_linux_snmp.pl line 3302.
> OK: Storage '/tmp' Usage Total: 4.81 GB Used: 137.93 MB (2.95%) Free: 4.43 GB (97.05%), Access : readWrite | 'used'=144633856B;0:4386481766;0:4644510105;0;5160566784

If I not use args "--add-access --critical-access=@2:2", the error message disappear
I have the same error with Windows plugin but I think "mode=storage" is the same standard plugin for both.

I have the same issue with those release:
centreon-plugin-Operatingsystems-Linux-Snmp-20190704-123459.el6.noarch
and 
centreon-plugin-Operatingsystems-Linux-Snmp-20191016-111959.el6.noarch
In this last release the error is at line 3372

> Use of uninitialized value $1 in concatenation (.) or string at /usr/lib/centreon/plugins/centreon_linux_snmp.pl line 3372.

Is this a known issue?
Thanks.

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk please ?

**Comment by cmeschin** [comment]
I sended you in MP.

**Comment by garnier-quentin** [comment]
It should be fixed. thanks for the feedback
