### ISSUE TITLE
Negative offset gives critical in apps::protocols::ntp::mode::offset

### ISSUE THREAD

**Issue by Tech-Magnus** [centreon/centreon-plugins#1761]
A negative time offset returns critical state to the service even if the offset is within warn/critical boundary 

Line 82 adding abs() function solved the isue.

    +++ my $exit = $self->{perfdata}->threshold_check(value => abs($offset),
                                                  threshold => [ { label => 'critical', exit_litteral => 'critical' }, { label => 'warning', exit_litteral => 'warning' } ]);_
    --- my $exit = $self->{perfdata}->threshold_check(value => $offset,
                                                  threshold => [ { label => 'critical', exit_litteral => 'critical' }, { label => 'warning', exit_litteral => 'warning' } ]);_

**Comment by garnier-quentin** [comment]
Please use nagios syntax for thresholds. http://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
For example: --critical-offset=-2:2
