### ISSUE TITLE
[os::linux::snmp::plugin] Memory negative value

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1762]
Hello guys,

I have a problem, that the value for the memory check of my Centreon appliance in VMware is returning a negative value:
![image](https://user-images.githubusercontent.com/35097389/70610164-639dff80-1c03-11ea-9d66-8a0ad628418f.png)

This is the check command:
`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=127.0.0.1 --snmp-version='2c' --snmp-community='public'  --warning-usage='80' --critical-usage='90'`

The settings for this check are default and I have used the predefined template.
Thank you!

Best regards, Michael

**Comment by garnier-quentin** [comment]
i think it's a redhat like distro. Could you use --autodetect-redhat ?

**Comment by MikeW83** [comment]
Yes, I'm using the ISO-Version of Centreon.

`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=127.0.0.1 --snmp-version='2c' --snmp-community='public' --warning-usage='80' --critical-usage='90' --autodetect-redhat`

> OK: Ram Total: 3.70 GB Used (-buffers/cache): 989.02 MB (26.10%) Free: 2.74 GB (73.90%), Buffer: 2.06 MB, Cached: 1.36 GB, Shared: 96.89 MB | 'used'=1037066240B;;;0;3973763072 'free'=2936696832B;;;0;3973763072 'used_prct'=26.10%;0:80;0:90;0;100 'buffer'=2158592B;;;0; 'cached'=1458896896B;;;0; 'shared'=101601280B;;;0;

Now it's working with using --autodetect-redhat

**Comment by hecko** [comment]
We are still experiencing this issue with the latest centreon-plugin-Operatingsystems-Linux-Snmp-20200803-072952.el6.noarch as such:

```
[root@xxx marcel.hecko]# /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=xxx  --snmp-version='2c' --snmp-community='xxx'  --warning-usage='80' --critical-usage='90' --swap  --explode-perfdata-max='used,size' --autodetect-redhat
CRITICAL: Ram Used : -36.07 % | 'used'=-695312384B;;;0;1927806976 'free'=2623119360B;;;0;1927806976 'used_prct'=-36.07%;0:80;0:90;0;100 'buffer'=479232B;;;0; 'cached'=1182740480B;;;0; 'shared'=9236480B;;;0; 'swap'=2621440B;;;0;2147479552 'swap_free'=2144858112B;;;0;2147479552 'swap_prct'=0.12%;;;0;100 'size'=1927806976B;;;; 'size'=100%;;;;
[root@xxx marcel.hecko]# /usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=xxx  --snmp-version='2c' --snmp-community='xxx'  --warning-usage='80' --critical-usage='90' --swap  --explode-perfdata-max='used,size'
CRITICAL: Ram Used : -36.07 % | 'used'=-695312384B;;;0;1927806976 'free'=2623119360B;;;0;1927806976 'used_prct'=-36.07%;0:80;0:90;0;100 'buffer'=479232B;;;0; 'cached'=1182740480B;;;0; 'shared'=9236480B;;;0; 'swap'=2621440B;;;0;2147479552 'swap_free'=2144858112B;;;0;2147479552 'swap_prct'=0.12%;;;0;100 'size'=1927806976B;;;; 'size'=100%;;;;

```

The OS is CentOS Linux release 7.6.1810 (Core) with net-snmp-5.7.2-43.el7.x86_64


Sincerely, 
Marcel

**Comment by garnier-quentin** [comment]
With the last version and if you are between net-snmp version, use option ```--patch-redhat ```:
```
rhel patch introduced: net-snmp-5.7.2-43.el7 (https://bugzilla.redhat.com/show_bug.cgi?id=1250060)
rhel patch reverted:   net-snmp-5.7.2-47.el7 (https://bugzilla.redhat.com/show_bug.cgi?id=1779609)
```

**Comment by hecko** [comment]
Sure thing! Updating the net-snmp package fixed the issue. I was not able to use the --patch-redhat option as that was an unknown option in out centreon-packages installation. 
Thanks!
