### ISSUE TITLE
[apps::protocols::ldap::plugin] mode login

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1763]
Hello,

How can we set the port if it's not the default 389 used ?

I've tried different things :
- hostname=10.10.10.10:1389
- --ldap-connect-options='port=1389'

but each time :
CRITICAL: Bind operation error: Unexpected EOF |

Thanks.

**Comment by garnier-quentin** [comment]
It should be work. Have you the ldapsearch command example ?

**Comment by ritouret** [comment]
just sent you by email.

Thanks.

**Comment by garnier-quentin** [comment]
It's working with  --ldap-connect-options='scheme=ldaps' option
