### ISSUE TITLE
[hardware::ups::apc::snmp::plugin] input-lines mode - upsAdvConfigHightransferVolt and upsAdvConfigLowTransferVolt as automatic warn/crit thresholds for upsAdvInputLineVoltage

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1764]
Hello

**PowerNet-MIB** has the following OIDs:

**1.3.6.1.4.1.318.1.1.1.3.2.1.0**	upsAdvInputLineVoltage
**1.3.6.1.4.1.318.1.1.1.5.2.2.0**	upsAdvConfigHightransferVolt
**1.3.6.1.4.1.318.1.1.1.5.2.3.0**	upsAdvConfigLowTransferVolt

These values store the current input voltage and its normal limits (upper and lower)

For example, 

for **APC Smart-UPS 3000 XLM** default allowed range: 

upsAdvConfigHightransferVolt - 208 VAC
upsAdvConfigLowTransferVolt  - 253 VAC

for **APC Smart-UPS SRT 10000** default allowed range: 

upsAdvConfigHightransferVolt - 198 VAC
upsAdvConfigLowTransferVolt  - 242 VAC

and so on.

These ranges depend on the specific model and are already embedded in the configuration of each device. These High/Low values are configurable and can be changed at any time by the UPS maintenance engineer. And this should automatically reflect on changing the thresholds of monitoring.

I ask you to implement the ability to use the upsAdvConfigHightransferVolt and upsAdvConfigLowTransferVolt values obtained from the UPS as limits for upsAdvConfigHightransferVolt

I guess you can make additional logic for the "--warning-voltage" and "--critical-voltage" options.

Such an approach would greatly enhance the capabilities of the plugin.

**Comment by garnier-quentin** [comment]
Please provide me the snmpwalk with following command:
snmpwalk -ObentU -v 2c -c public IP .1 > apc.snmpwalk

**Comment by Aleksey-Maksimov** [comment]
[UPS_APC_Smart_UPS_SURT6000XLI_NMC-gen1.zip](https://github.com/centreon/centreon-plugins/files/3966842/UPS_APC_Smart_UPS_SURT6000XLI_NMC-gen1.zip)

**Comment by garnier-quentin** [comment]
Thanks you can test it.

**Comment by Aleksey-Maksimov** [comment]
Fine. It works. Many thanks.
