### ISSUE TITLE
[hardware::ups::powerware::snmp::plugin] input-lines mode - upsConfigHighVoltageTransferPoint and upsConfigLowVoltageTransferPoint as automatic warn/crit thresholds for xupsInputVoltage

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1765]
Hello

With **Eaton Powerware UPS**, the situation is similar to that described in [issue 1764](https://github.com/centreon/centreon-plugins/issues/1764)

**1.3.6.1.4.1.534.1.3.4.1.2.1**    XUPS-MIB : xupsInputVoltage
**1.3.6.1.2.1.33.1.9.10.0**    UPS-MIB : upsConfigHighVoltageTransferPoint
**1.3.6.1.2.1.33.1.9.9.0**	  UPS-MIB : upsConfigLowVoltageTransferPoint

I ask you to implement the ability to use the upsConfigHighVoltageTransferPoint and upsConfigLowVoltageTransferPoint values obtained from the Powerware UPS as automatic limits for xupsInputVoltage

I guess you can make additional logic for the "--warning-voltage" and "--critical-voltage" options.

**Comment by garnier-quentin** [comment]
Please provide me the snmpwalk with following command:
snmpwalk -ObentU -v 2c -c public IP .1 > powerware.snmpwalk

**Comment by Aleksey-Maksimov** [comment]
[UPS_Eaton_Powerware_PW9125_6000.zip](https://github.com/centreon/centreon-plugins/files/3966739/UPS_Eaton_Powerware_PW9125_6000.zip)

**Comment by garnier-quentin** [comment]
You can test it

**Comment by Aleksey-Maksimov** [comment]
Hello.

On one of our UPSs, the plugin displays a message about type mismatch:

```
# /centreon_plugins.pl --plugin=hardware::ups::powerware::snmp::plugin 
--mode=input-lines 
--critical-frequence='49:51'
--filter-uom='%' 
--hostname='tv2Up004' --snmp-community=public --snmp-version=1

Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 162.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 223.
OK: frequence: 50.00 Hz - Input Line '1' current: 0.00 A, voltage: 233.00 V | 'frequence'=50.00;;49:51;; 'current'=0.00;;;0; 'voltage'=233.00;;160:276;;
```

**Comment by Aleksey-Maksimov** [comment]
snmpwalk utility log: [UPS_Eaton_Powerware_PW9120_3000.zip](https://github.com/centreon/centreon-plugins/files/3987288/UPS_Eaton_Powerware_PW9120_3000.zip)

**Comment by Aleksey-Maksimov** [comment]
Maybe the problem is that the value "current" is not returned

**Comment by garnier-quentin** [comment]
I didn't get that error if i test with your snmpwalk. the current value is weird. because there is no current value in your snmpwalk '.1.3.6.1.4.1.534.1.3.4.1.3'. Could you add a debug on $snmp_result variable ?
```
use Data::Dumper;
print Data::Dumper::Dumper($snmp_result);
```

**Comment by Aleksey-Maksimov** [comment]
Sorry, I don’t quite understand what I have to do.

**Comment by garnier-quentin** [comment]
Please add following lines in the file '/home/qgarnier/plugins/master/centreon-plugins/hardware/ups/powerware/snmp/mode/inputlines.pm':
```
my $snmp_result = $options{snmp}->get_multiple_table(
        oids => [
            { oid => $mapping2->{xupsInputFrequency}->{oid} },
            { oid => $oid_xupsInputEntry },
            { oid => $oid_upsConfig, start => $mapping3->{upsConfigLowVoltageTransferPoint}->{oid}, end => $mapping3->{upsConfigHighVoltageTransferPoint}->{oid} },
        ],
        return_type => 1,
        nothing_quit => 1
    );

# following lines
use Data::Dumper;
print Data::Dumper::Dumper($snmp_result);
```

**Comment by Aleksey-Maksimov** [comment]
```
$VAR1 = {
          '.1.3.6.1.2.1.33.1.9.10.0' => '276',
          '.1.3.6.1.4.1.534.1.3.4.1.1.1' => '1',
          '.1.3.6.1.4.1.534.1.3.1.0' => '500',
          '.1.3.6.1.4.1.534.1.3.4.1.2.1' => '233',
          '.1.3.6.1.4.1.534.1.3.4.1.3.1' => '',
          '.1.3.6.1.2.1.33.1.9.9.0' => '160'
        };
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 162.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 223.
OK: frequence: 50.00 Hz - Input Line '1' current: 0.00 A, voltage: 233.00 V | 'frequence'=50.00;;49:51;; 'current'=0.00;;;0; 'voltage'=233.00;;160:276;;
```

**Comment by garnier-quentin** [comment]
I have done a fix. could you test it ?

**Comment by Aleksey-Maksimov** [comment]
It is resolved. Thanks.
