### ISSUE TITLE
Plugin for wireless access points Cisco Aironet (SNMP)

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1767]
Hello.

We ask you to implement the ability to monitor wireless access points **Cisco Aironet**.

I have the opportunity to receive SNMP data from access points of the model **AIR-AP1242AG-A-K9**. 
**snmpwalk** log in the attachment:
[Cisco_Aironet_AIR-AP1242AG-A-K9.zip](https://github.com/centreon/centreon-plugins/files/3977450/Cisco_Aironet_AIR-AP1242AG-A-K9.zip)

The same modes would be useful as in the **network::cisco::wlc::snmp::plugin**:

* ap-channel-interference
* ap-channel-noise
* ap-status
* ap-users
* cpu
* hardware
* interfaces
* list-interfaces
* memory

Additionally, it would be nice to have such modes:

* uptime
* time

Thanks in advance

**Comment by garnier-quentin** [comment]
Could you provide mib files with "business" information ? (ap users, ssid,...)

**Comment by Aleksey-Maksimov** [comment]
I think all the MIB files are here: ftp://ftp.cisco.com/pub/mibs/supportlists/c1240/c1240-supportlist.html

**Comment by garnier-quentin** [comment]
I can't find a mib about access point datas (users, ssid)

**Comment by Aleksey-Maksimov** [comment]
Maybe CISCO-DOT11-MIB* files will help? 
[CISCO-DOT11-MIBs.zip](https://github.com/centreon/centreon-plugins/files/3982812/CISCO-DOT11-MIBs.zip)

**Comment by Aleksey-Maksimov** [comment]
Can I help you with anything else?

**Comment by garnier-quentin** [comment]
I think it's the same ticket: https://github.com/centreon/centreon-plugins/issues/2227
I will develop a plugin soon!
