### ISSUE TITLE
centreon-plugins/network/extreme/snmp/mode/components/fan.pm not reading fan speed

### ISSUE THREAD

**Issue by troja89** [centreon/centreon-plugins#1768]
I am trying to monitor the hardware on Extreme Summit X250e, but I am running into issues with displaying the fan speed.
bash-4.2$ /usr/lib/centreon/plugins/centreon_extreme.pl --plugin=network::extreme::snmp::plugin --mode=hardware --hostname=xxxx --snmp-version=3 --snmp-username=xxxx --authpassphrase=xxxx --authprotocol=SHA --privpassphrase=xxxx --privprotocol=AES --verbose
OK: All 7 components are ok [4/4 fans, 1/1 power supplies, 1/1 slots, 1/1 temperatures]. | 'fan_101'=rpm;;;0; 'fan_102'=rpm;;;0; 'fan_103'=rpm;;;0; 'fan_104'=rpm;;;0; 'temp'=31C;;;; 'count_fan'=4;;;; 'count_psu'=1;;;; 'count_slot'=1;;;; 'count_temperature'=1;;;;
Checking fans
Fan '101' status is 'operational' [instance = 101, speed = unknown]
Fan '102' status is 'operational' [instance = 102, speed = unknown]
Fan '103' status is 'operational' [instance = 103, speed = unknown]
Fan '104' status is 'operational' [instance = 104, speed = unknown]
Checking power supplies
Power supply '1' status is 'presentOK' [instance = 1, fan1speed = -1, fan2speed = -1, power = 0]
Checking slots
Slot 'Switch' status is 'operational' [instance = 1]
Checking temperatures
temperature is 31C [instance: 0].
Checking poes

If I check the fanspeed oid (1.3.6.1.4.1.1916.1.1.1.9.1.4) with snmpwalk I get  the result:
snmpwalk -v3 -l authPriv -u xxxx -a SHA -A xxxx -x AES -X xxxx xxxx .1.3.6.1.4.1.1916.1.1.1.9.1.4
SNMPv2-SMI::enterprises.1916.1.1.1.9.1.4.101 = INTEGER: 1000
SNMPv2-SMI::enterprises.1916.1.1.1.9.1.4.102 = INTEGER: 1000
SNMPv2-SMI::enterprises.1916.1.1.1.9.1.4.103 = INTEGER: 1000
SNMPv2-SMI::enterprises.1916.1.1.1.9.1.4.104 = INTEGER: 1000

If i try the same oid with snmpget i get:
 snmpget -v3 -l authPriv -u xxxx -a SHA -A xxxx -x AES -X xxxx xxxx .1.3.6.1.4.1.1916.1.1.1.9.1.4
SNMPv2-SMI::enterprises.1916.1.1.1.9.1.4 = No Such Instance currently exists at this OID

BUT if i try the specific fan instance, I get a result:
snmpget -v3 -l authPriv -u xxxx -a SHA -A xxxx -x AES -X xxxx xxxx .1.3.6.1.4.1.1916.1.1.1.9.1.4.101
SNMPv2-SMI::enterprises.1916.1.1.1.9.1.4.101 = INTEGER: 1000

Any help would be greatly appreciated!

**Comment by garnier-quentin** [comment]
I have done a fix. Could you test it ?

**Comment by troja89** [comment]
Thank you! It works now :)
