### ISSUE TITLE
[apps::nsclient::restapi::plugin] Trying to understand what is the right syntax to use WQL query for disk I/O on W2K16

### ISSUE THREAD

**Issue by Supervisor999** [centreon/centreon-plugins#1769]
Hi, 

I’m trying to use this plugin to monitor some Windows servers 2016, especially for getting disks’ I/O (via wql request), I found all informations that I wanted to get them, but now I need to understand which syntax I have to use according to the plugin. I checked nsclient's official website, and the REST API web interface on my local lab machine, but I don't really understand how to proceed with parameters. 

By using Powershell, I can get informations, especially the query by this command : 

get-wmiobject -computername localhost -namespace root\CIMV2 **-Query “select * from Win32_perfrawdata_perfdisk_physicaldisk”** 

I could filter what I want next, but the thing is how to integrate it in the plugin's syntax ? 

I tried different things with different kind of commands without success : 

Command n°1 : 

./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname=192.168.1.86 --port=8443 --proto='https' --command=**check_pdh** --legacy-password='centreon' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'

I got : 
**No counters specified: add counter=<name of counter>**

Command n°2 : 

./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname=192.168.1.86 --port=8443 --proto='https' --command=**check_pdh add counter=diskbytespersec**  --legacy-password='centreon' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'

I got : 

**argument counter=diskbytespersec alone at /root/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 93.**

Command n°3 : 

./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname=192.168.1.86 --port=8443 --proto='https' --command=**check_wmi**  --legacy-password='centreon' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'

I got: 

**No query specified**

I'm pretty sure that I have to use "check_wmi" command, and maybe --arg=[something] but how to handle this...I also tried : 

Command n°4 : 

./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname=192.168.1.86 --port=8443 --proto='https' --command=**check_wmi query="select * from Win32_perfrawdata_perfdisk_physicaldisk" namespace=root\cimv2**  --legacy-password='centreon' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'

I got : 

**argument namespace=rootcimv2 alone at /root/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 93.**

Command n°5 : 

./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname=192.168.1.86 --port=8443 --proto='https' --command=**check_wmi arg=query="select * from Win32_perfrawdata_perfdisk_physicaldisk" arg=namespace=root\cimv2**  --legacy-password='centreon' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'

I got : 

**argument arg=namespace=rootcimv2 alone at /root/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 93.**

As you can see, i'm definitely not sure about the proper syntax to use.. 

Any idea by here ? 

Don't hesitate to ask any other details if needed

**Comment by garnier-quentin** [comment]
Could you try following command ?
```
./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname=192.168.1.86 --port=8443 --proto='https' --command=check_pdh --arg="counter=diskbytespersec" --legacy-password='centreon' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'
```

**Comment by Supervisor999** [comment]
Ok, the second one works, I haven't thought about adding simple quotes between the arg, thank you for helping me in that case !

**Comment by garnier-quentin** [comment]
Thanks for the feedback
