### ISSUE TITLE
Feature request: Query statements on Elastic

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#1770]
A very, very cool and powerful feature would be the possibility to launch sql-statements on Elastic like Oracle or MSSQL with --mode=sql and --sql-statement.

This should open no possibilities to check values from indices.

https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-cli.html

https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest-overview.html

**Comment by Sims24** [comment]
Hey @rmorandell-pgum , 

Yeah definitely! We will think about it soon !

**Comment by joschi99** [comment]
Hi @Sims24 
are there any news about this request? It should be very useful to have a plugin which allows to interrogate elasticsearch datas.

Thanks,
Jochen

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
