### ISSUE TITLE
[network::riverbed::steelhead::snmp::plugin] --mode=bandwidth-passthrough

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1773]
Hello,

There's a bug in this mode : output contains good values but not perf data ...

OK: Passthrough Traffic In (Wan2Lan): 227.45 KB/s, Traffic Out (Lan2Wan): 19.20 KB/s | 'traffic_in'=49843274B/s;;;0; 'traffic_out'=4207221B/s;;;0;

**Comment by garnier-quentin** [comment]
it's fixed

**Comment by ritouret** [comment]
Thanks Quentin, It works :
OK: Passthrough Traffic In (Wan2Lan): 238.88 KB/s, Traffic Out (Lan2Wan): 20.74 KB/s | 'traffic_in'=244609.962406015B/s;;;0; 'traffic_out'=21233.2706766917B/s;;;0;
