### ISSUE TITLE
[hardware::ups::apc::snmp::plugin] --mode=output-lines

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1774]
Hello,

I think this mode should change the requested OID :

Here is the actual output without perfdata :
OK: Output status is 'onLine', Load : 16 %, Current : 1 A, Voltage : 242 V, Frequence : 50 Hz

Here is the correspondant OID with these description :
PowerNet-MIB::upsAdvOutputVoltage.0 = Gauge32: 242 -> "The output voltage of the UPS system in VAC."
PowerNet-MIB::upsAdvOutputFrequency.0 = Gauge32: 50 -> "The current output frequency of the UPS system in Hz."
PowerNet-MIB::upsAdvOutputLoad.0 = Gauge32: 16 -> "The current UPS load expressed in percent of rated capacity."
PowerNet-MIB::upsAdvOutputCurrent.0 = Gauge32: 1 -> "The current in amperes drawn by the load on the UPS."

And here is the same values but with high precision calculation :
PowerNet-MIB::upsHighPrecOutputVoltage.0 = Gauge32: 2418 -> "The output voltage of the UPS system in tenths of VAC."
PowerNet-MIB::upsHighPrecOutputFrequency.0 = Gauge32: 499 -> "The current output frequency of the UPS system in tenths of Hz."
PowerNet-MIB::upsHighPrecOutputLoad.0 = Gauge32: 156 -> "The current UPS load expressed in tenths of percent of rated capacity."
PowerNet-MIB::upsHighPrecOutputCurrent.0 = Gauge32: 14 -> "The current in tenths of amperes drawn by the load on the UPS."

The output should be :
OK: Output status is 'onLine', Load : 15,6 %, Current : 1,4 A, Voltage : 241,8 V, Frequence : 49,9 Hz

Which is pretty different from actual output (mostly on "Current" value) :
OK: Output status is 'onLine', Load : 16 %, Current : 1 A, Voltage : 242 V, Frequence : 50 Hz

**Comment by garnier-quentin** [comment]
Please could you provide the full snmpwalk of that equipment ?
snmpwal -ObentU -v 2c -c public IP .1 > ups.snmpwalk

**Comment by ritouret** [comment]
Just sent you by email.

Thanks.

**Comment by garnier-quentin** [comment]
You can test it
