### ISSUE TITLE
[hardware::ups::powerware::snmp::plugin] battery-status mode problems

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1775]
Hello

It looks like **battery-status** mode has a couple of problems

First problem:
The value "voltage" is displayed as 25.9... 

```
# ./centreon_plugins.pl --plugin=hardware::ups::powerware::snmp::plugin 
--mode=battery-status 
--warning=50:100 --critical=25:100 --filter-uom='%'
--snmp-version=1 --snmp-community=public --hostname=t2Up05 

OK: Battery status is batteryResting - Charge remaining: 100% (101 minutes remaining) 
| 'load'=100%;50:100;25:100;0;100 'voltage'=25.9;;;;
```
But if we look at the NMC web interface, then there we will see the value 10 times greater:

![изображение](https://user-images.githubusercontent.com/17614847/71243061-75c51f80-2320-11ea-850d-ef983ef67ecf.png)

One more problem: The value of **load_time** is not displayed in the perfdate (101 minutes in our example)
Please add this information by analogy with how it is done in the **hardware::ups::apc::snmp::plugin**

**Comment by garnier-quentin** [comment]
You can test it

**Comment by Aleksey-Maksimov** [comment]
Hello. 
Yes, now the voltage is displayed correctly. 
Thanks.
