### ISSUE TITLE
[hardware::ups::powerware::snmp::plugin] environment mode

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1776]
Hello

It seems to me that the **environment** mode needs a little fix.

```
# ./centreon_plugins.pl --plugin=hardware::ups::powerware::snmp::plugin 
--mode=environment 
--critical-humidity=6:59 --critical-temperature=11:39 --verbose --filter-uom='%'
--snmp-version=1 --snmp-community=public --hostname=tv2Up05 

OK: Ambiant Temperature: 28.00 C, Humidity: 43.00 % | 
'temperature'=28.00;;11:39;0; 'humidity'=43.00%;;6:59;0;100
```

What is labeled as "Ambiant Temperature" (28C) is actually the temperature inside the UPS, which is measured by the built-in sensor.
This is the internal temperature of the UPS.

**xupsEnvAmbientTemp** 	**1.3.6.1.4.1.534.1.6.1.0** = 28С (UPS Internal Temperature)

I don’t know why Eaton named this OID as Ambient, although in fact it is an internal sensor.

If we connect an external sensor to the UPS, we will get 2 more additional values:
	
**xupsEnvRemoteTemp** 	**1.3.6.1.4.1.534.1.6.5.0** = 21С (UPS Environment Temperature)
**xupsEnvRemoteHumidity** 	**1.3.6.1.4.1.534.1.6.6.0** = 43С (UPS Environment Humidity)

![изображение](https://user-images.githubusercontent.com/17614847/71245428-b7a49480-2325-11ea-9dfd-69a7dda199b1.png)

That is, for good, we need the plug-in to return all three values for the UPS connected with an external sensor:

- temperature
- temperature_env
- humidity_env

And for a UPS without an external sensor connected, the value should be only one:

- temperature

Thank you in advance

**Comment by garnier-quentin** [comment]
could you provide the full snmpwalk ?

**Comment by Aleksey-Maksimov** [comment]
[UPS_Eaton_Powerware_PW9125_6000_with_external_sensors.zip](https://github.com/centreon/centreon-plugins/files/3989189/UPS_Eaton_Powerware_PW9125_6000_with_external_sensors.zip)

**Comment by Aleksey-Maksimov** [comment]
[UPS_Eaton_Powerware_PW9125_6000_with_external_sensors.zip](https://github.com/centreon/centreon-plugins/files/3989200/UPS_Eaton_Powerware_PW9125_6000_with_external_sensors.zip)

**Comment by garnier-quentin** [comment]
Have done the patch. you can test it

**Comment by Aleksey-Maksimov** [comment]
Hello.

The temperature data is now all right. 
But there is still a problem. It looks like the plugin is not returning information about air humidity

```
# ./centreon_plugins.pl --plugin=hardware::ups::powerware::snmp::plugin 
--mode=environment 
--snmp-version=1 --snmp-community=public --hostname=tv2Up05
--critical-remote-humidity=6:59 --critical-remote-temperature=11:34 
--critical-internal-humidity=6:59 --critical-internal-temperature=11:39 
--verbose 
--filter-uom='%'

OK: internal temperature: 32.00 C, remote temperature: 25.00 C | 
'internal_temperature'=32.00;;11:39;0; 'remote_temperature'=25.00;;11:34;0;
```
![изображение](https://user-images.githubusercontent.com/17614847/72162896-d3a2cf80-33d3-11ea-865e-4de703f620ed.png)

**Comment by garnier-quentin** [comment]
It should be ok!

**Comment by Aleksey-Maksimov** [comment]
Yes, now everything is fine. Thanks.
