### ISSUE TITLE
apps::protocols::http::plugin: Add an option to support NTLM proxies

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon-plugins#1778]
Hi,
As discussed with @garnier-quentin, NTLM proxies can work with `apps::protocols::http::plugin` but it requires adding `--curl-opt="CURLOPT_PROXYAUTH => CURLAUTH_NTLM"` to the command-line.
Something like this works:
```
./centreon_plugins.pl --plugin apps::protocols::http::plugin --mode response --proxyurl user:pass@a.b.c.d:8080 --http-backend=curl --hostname example.com --urlpath / --debug --curl-opt="CURLOPT_PROXYAUTH => CURLAUTH_NTLM"
```

Could you please add a parameter for this? Maybe name it `--proxy-ntlm` like curl's parameter?

**Comment by garnier-quentin** [comment]
I cannot map all parameters. That's why i let an open args.

**Comment by sbraz** [comment]
Proxies with NTLM auth are quite common for large companies though, aren't they?

But you can close this if you don't think it's worth it. At least people will find this example command when they attempt to monitor their proxies :)

**Comment by garnier-quentin** [comment]
I think i let it like that.
