### ISSUE TITLE
HP UPS monitoring through SNMP

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1780]
Hello.

Could you please implement the new plugin for monitoring **HP UPS**?

We have several devices of the following model:
**UPS HP R5500 XR** with **HP UPS Management Module**

**Snmpwalk** utility report and **MIB** files in attachments:

[HP_MIBs.zip](https://github.com/centreon/centreon-plugins/files/3989676/HP_MIBs.zip)
[UPS_HP_R5500_XR.zip](https://github.com/centreon/centreon-plugins/files/3989677/UPS_HP_R5500_XR.zip)

We think you can try the following modes for the plugin:
* uptime
* time
* battery-status
* input-lines
* output-lines
* output-source
* environment

The following OIDs may be useful:

**mode uptime**

.1.3.6.1.2.1.1.3.0	sysUpTime.0; Value (TimeTicks)

**mode time**

.1.3.6.1.4.1.232.165.3.9.5.0	upsConfigDateAndTime.0
its return current time on device in string format "12/20/2019 20:09:05"
this time can be compared with local time on the monitoring server or with another exact time source (NTP server)

**mode battery-status**

.1.3.6.1.4.1.232.165.3.2.1.0	upsBatTimeRemaining.0
.1.3.6.1.4.1.232.165.3.2.2.0	upsBatVoltage.0
.1.3.6.1.4.1.232.165.3.2.4.0	upsBatCapacity.0

**mode input-lines**

.1.3.6.1.4.1.232.165.3.3.4.1.2.1	upsInputVoltage.1 (volts)
.1.3.6.1.4.1.232.165.3.3.4.1.3.1	upsInputCurrent.1 (apms)

default thresholds for upsInputVoltage from here:

.1.3.6.1.4.1.232.165.3.9.6.0	upsConfigLowOutputVoltageLimit.0
.1.3.6.1.4.1.232.165.3.9.7.0	upsConfigHighOutputVoltageLimit.0

**mode output-lines**

.1.3.6.1.4.1.232.165.3.4.1.0	upsOutputLoad.0 (%)
.1.3.6.1.4.1.232.165.3.4.2.0	upsOutputFrequency.0 (Hz)
.1.3.6.1.4.1.232.165.3.4.4.1.2.1	upsOutputVoltage.1 (volts)
.1.3.6.1.4.1.232.165.3.4.4.1.3.1	upsOutputCurrent.1 (amps)
.1.3.6.1.4.1.232.165.3.4.4.1.4.1	upsOutputWatts.1 (watts)

**mode output-source**

.1.3.6.1.4.1.232.165.3.4.5.0	upsOutputSource.0

The present source of output power.  The enumeration none(2) indicates that there is no source of output power (and therefore no output power), for example, the system has opened the output breaker.
INTEGER {other(1),none(2),normal(3), bypass(4), battery(5),booster(6), reducer(7), parallelCapacity(8), parallelRedundant(9), highEfficiencyMode(10) }

**mode environment**

.1.3.6.1.4.1.232.165.3.6.1.0	upsEnvAmbientTemp.0
.1.3.6.1.4.1.232.165.3.6.4.0	upsEnvAmbientHumidity.0
.1.3.6.1.4.1.232.165.3.6.5.0	upsEnvRemoteTemp.0
.1.3.6.1.4.1.232.165.3.6.6.0	upsEnvRemoteHumidity.0

Thanks in advance.

**Comment by garnier-quentin** [comment]
Could you test it ? I have merge output-lines and output-source.

**Comment by Aleksey-Maksimov** [comment]
Hello.

Thanks for the plugin.

It looks like the **battery-status** mode has problems.

```
# ./centreon_plugins.pl --plugin=hardware::ups::hp::snmp::plugin 
--mode=battery-status  
--snmp-version='2c' --snmp-community='public' --hostname='UhUPS01'

WARNING: battery status is 'batteryDischarging' | 
'battery.charge.remaining.percent'=100%;;;0;100 
'battery.charge.remaining.minutes'=75m;;;0; 
'battery.voltage.volt'=264V;;;;
```

But on the web interface of the HP UPS Management Module, we see that the battery status is "Normal"

![изображение](https://user-images.githubusercontent.com/17614847/71476483-63eaed00-27f6-11ea-88a0-77ebae07e51e.png)

**Comment by garnier-quentin** [comment]
I take that value from snmp:
```
.1.3.6.1.4.1.232.165.3.2.5.0 = INTEGER: 2
```

It means:
```
batteryCharging(1),
batteryDischarging(2),
batteryFloating(3),
batteryResting(4),
unknown(5)
```

**Comment by Aleksey-Maksimov** [comment]
These modes look like working:

- **uptime**
- **input-lines**
- **output-lines**
- **output-source**
- **environment**

There is no **time** mode for checking the current time on UPS Management Module

**Comment by Aleksey-Maksimov** [comment]
**time** mode is important on all network devices.
Violation of the current time can lead to various problems. For example, information in the device log may be distorted. There may also be issues with secure access via HTTPS

**Comment by garnier-quentin** [comment]
I added the mode time.

**Comment by Aleksey-Maksimov** [comment]
> 
> 
> I take that value from snmp:
> 
> ```
> .1.3.6.1.4.1.232.165.3.2.5.0 = INTEGER: 2
> ```
> 
> It means:
> 
> ```
> batteryCharging(1),
> batteryDischarging(2),
> batteryFloating(3),
> batteryResting(4),
> unknown(5)
> ```

It is very strange that on all 4 UPSs that we have, the status is always "batteryDischarging". At the same time, the web interface of UPS Management Module says that everything is fine. Perhaps the “BatteryDischarging” state is not a problem, but a normal state for these UPSs. I think we can get around this by specifying --warning-status="". Do you think this is the right approach?

**Comment by garnier-quentin** [comment]
I don't know. Maybe you can ask to hp support.

**Comment by Aleksey-Maksimov** [comment]
Hello.

I contacted HP tech support and this is what they answered me:

Normal Battery Conditions 1-4 (ABM Status - Advanced Battery Management Status):

• **batteryCharging** (1), - battery charge, periodically due to natural self-discharge or after transferring the load to the batteries
• **batteryDischarging** (2), battery discharge, when the UPS trips (drawdown, voltage drop), transferring the load to the inverter-batteries
• **batteryFloating** (3), buffer mode, at the same time charging batteries and mains operation
• **batteryResting** (4), the batteries are fully charged, “rest”

That is, only state 5 is a problem. 

• **unknown** (5), possibly a battery error, unknown combination of parameters, it may be necessary to reset, restart the UPS or the control module.

Therefore, could you please change the behavior of the script?

**Comment by garnier-quentin** [comment]
thanks for the feedback. it's fixed

**Comment by Aleksey-Maksimov** [comment]
Thank you
