### ISSUE TITLE
[database::mysql::mode::openfiles] Type int for percentage calculation

### ISSUE THREAD

**Issue by jumakasy** [centreon/centreon-plugins#1781]
Hi everybody,

I know this question is a "little squeamish", but I'm wondering why the line 81(see the code below) use a casting to int to calculate the percentage, and then the value is printed with two decimals points. Also, it's possible that occurs some little problem with the thresholds limits.

Wouldn't it be "more correct" to use the type float for the percentage?  

Regards.
JumaKasY

https://github.com/centreon/centreon-plugins/blob/99c6d8de8abd43f2bebf2aedfe7bf753f820c146/database/mysql/mode/openfiles.pm#L81-L86

**Comment by garnier-quentin** [comment]
Yes you're right. I fix it.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by jumakasy** [comment]
Hey thanks! Yes, I will test it and let you know.

Regards.
JumaKasY

**Comment by jumakasy** [comment]
Hi,

I have tested the modification, and its working. The percentage now shows two real decimals.

Regards.
JumaKasY

**Comment by garnier-quentin** [comment]
tahnks for the feedback
