### ISSUE TITLE
OVH email2SMS not working from UI

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#1782]
Hi, 
I try to use OVH email2sms functionality to send sms notifications, using smtp-cli command.
I wrote the code and test it on cli where it is working fine (i receive the sms).
But when configuring the command on UI, i can see in events that notification is sent but i do not receive any sms. 
i can't find any error and i checked command rights that seems OK as i can use the same command for email notifications.

My code is: 

$CENTREONPLUGINS$/smtp-cli --missing-modules-ok --host smtp.office365.com --port 587 --auth --user mysource@email.com --pass Password --from mysource@email.com --to email2sms@ovh.net --subject "Account=sms-mx0000-1;Login=mylogin;Password=mypassword;From=CENTREON;To=+phonenumber;NoStop=1" --body-html "*CENTREON*<BR>Notification Type: $NOTIFICATIONTYPE$<BR>Service: $SERVICEDESC$<BR>Host: $HOSTALIAS$<BR>Address: $HOSTADDRESS$<BR>State: $SERVICESTATE$<BR>Date/Time: $DATE$<BR>Additional Info : $SERVICEOUTPUT$"

Can anyone please help debug why sms is not sent with UI command ?

Thank you

**Comment by garnier-quentin** [comment]
smtp-cli is not a centreon-plugins i think. It's not the good github

**Comment by saharawolf** [comment]
Hi, 

Thank you for your reply.
Yes you are right , smtp-cli is not centreon plugin. but the git of the command is no more active. 

Can you just point me on how to check on centreon logs (what file) and what command is executed ? 
This might help.

thank you

**Comment by garnier-quentin** [comment]
Try it like that:
```
$CENTREONPLUGINS$/smtp-cli --missing-modules-ok --host smtp.office365.com --port 587 --auth --user mysource@email.com --pass Password --from mysource@email.com --to email2sms@ovh.net --subject "Account=sms-mx0000-1;Login=mylogin;Password=mypassword;From=CENTREON;To=+phonenumber;NoStop=1" --body-html "CENTREON\nNotification Type: $NOTIFICATIONTYPE$\nService: $SERVICEDESC$\nHost: $HOSTALIAS$\nAddress:\n$HOSTADDRESS$\nState: $SERVICESTATE$\nDate/Time: $DATE$\nAdditional Info : $SERVICEOUTPUT$"
```
