### ISSUE TITLE
Feature request: PaloAlto GlobalProtect gateway stats : network::paloalto::snmp::plugin gateway mode

### ISSUE THREAD

**Issue by moix** [centreon/centreon-plugins#1783]
Hi, we are using paloalto plugin and its checks for memory, clusterstatus and sessions. So far it's been great because provides us many useful information.

We would like to add more metrics to it such as GlobalProtect gateway stats, which are specified in OIDs:

Item | Name | OID
------------ | ------------- | -------------
GlobalProtect gateway utilization | panGPGatewayUtilization | 1.3.6.1.4.1.25461.2.1.2.5.1
GlobalProtect gateway % utilization | panGPGWUtilizationPct.0 | 1.3.6.1.4.1.25461.2.1.2.5.1.1
GlobalProtect gateway max tunnels | panGPGWUtilizationMaxTunnels.0 | 1.3.6.1.4.1.25461.2.1.2.5.1.2
GlobalProtect gateway active tunnels | panGPGWUtilizationActiveTunnels.0 | 1.3.6.1.4.1.25461.2.1.2.5.1.3

Could you please help with that implementation?

Thanks!

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk please (can be by email).
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.25461 > palo.snmpwalk

**Comment by moix** [comment]
Hi @garnier-quentin  sure following is a real output:

```
moix@nagios-checker ~$ snmpwalk -ObentU -v2c -c public paloalto.host 1.3.6.1.4.1.25461.2.1.2.5.1
.1.3.6.1.4.1.25461.2.1.2.5.1.1.0 = INTEGER: 0
.1.3.6.1.4.1.25461.2.1.2.5.1.2.0 = INTEGER: 5000
.1.3.6.1.4.1.25461.2.1.2.5.1.3.0 = INTEGER: 0
moix@nagios-checker ~$ snmpwalk -ObentU -v2c -c public paloalto.host 1.3.6.1.4.1.25461.2.1.2.5.1.1
.1.3.6.1.4.1.25461.2.1.2.5.1.1.0 = INTEGER: 0
moix@nagios-checker ~$ snmpwalk -ObentU -v2c -c public paloalto.host 1.3.6.1.4.1.25461.2.1.2.5.1.3
.1.3.6.1.4.1.25461.2.1.2.5.1.3.0 = INTEGER: 0
```

**Comment by garnier-quentin** [comment]
I have done the mode gp-usage. Could you test it ?
