### ISSUE TITLE
Unknown Option NTP Windows

### ISSUE THREAD

**Issue by djedje6821** [centreon/centreon-plugins#1786]
Bonjour,

Je rencontre un problème avec le centreon-plugins, je ne sais pas si c'est un bug ou une erreur de ma part :

Pour tous mes services NTP Windows je reçois le message suivant : 

> Unknown option: warning at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.

La commande exécutée est la suivante : 
`/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=time --hostname=192.168.xx.xx --snmp-version='2c' --snmp-community='xx'  --ntp-hostname='' --ntp-port='' --warning='-1:1' --critical='-2:2' --timezone='Europe/Paris' `

En utilisant l'aide j'ai bien vu qu'il fallait utiliser "-offset" pour le warning et pour le critical mais vu que j'utilise le modèle "OS-Windows-Ntp-SNMP-custom" qui est basé sur un autre modèle "OS-Windows-Ntp-SNMP" qui n'est pas modifiable...  Je ne vois pas ou modifier mes "checks"

```
rpm -qa | grep centreon-plugin
centreon-plugin-Operatingsystems-Linux-Snmp-20191219-152203.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20191219-152203.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20191219-152203.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20191219-152203.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20191219-152203.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20191219-152203.el7.centos.noarch
```

Merci

**Comment by garnier-quentin** [comment]
Please do following procude:
- update centreon-pack windows snmp on your central server
- update the pack windows snmp with the centreon-ui (Configuration > Plugin Packs)
- generate the configuration and reload the poller
