### ISSUE TITLE
plugin=database::oracle::plugin work on shell as centreon-engine but not on web

### ISSUE THREAD

**Issue by bastiencha** [centreon/centreon-plugins#1787]
Hi

When I try 

/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=database::oracle::plugin --hostname='****' --port='1521' --sid='***' --username='***' --password='****'  --mode='connected-users' --warning='120' --critical='130'

In shell, with centreon-engine, it's work, I have : 
WARNING: 124 Connected user(s). | 'connected_users'=124;0:120;0:130;0;

In root, it's work too.

My problem is in centreon web, I have : 

  | UNKNOWN: Cannot connect: (no error string)
-- | --

Can you help me ?

Thank's

**Comment by garnier-quentin** [comment]
Could you provide the shell environment of centreon-engine user ?

**Comment by bastiencha** [comment]
[centreon-engine@------- root]$ printenv
XDG_SESSION_ID=42
HOSTNAME=--------
SHELL=/bin/bash
TERM=xterm
HISTSIZE=1000
SSH_CLIENT=------
PERL5LIB=/lib/perl5/lib/perl5:/root/perl5/lib/perl5
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
PERL_MB_OPT=--install_base "/lib/perl5"
SSH_TTY=/dev/pts/1
QT_GRAPHICSSYSTEM_CHECKED=1
USER=centreon-engine
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/lib/perl5/bin:/root/perl5/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
MAIL=/var/spool/mail/root
PWD=/root
LANG=fr_FR.UTF-8
HISTCONTROL=ignoredups
HOME=/var/lib/centreon-engine
SHLVL=2
PERL_LOCAL_LIB_ROOT=/lib/perl5:/root/perl5
LOGNAME=centreon-engine
QTLIB=/usr/lib64/qt-3.3/lib
SSH_CONNECTION=-------- 
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/0
PERL_MM_OPT=INSTALL_BASE=/lib/perl5
_=/usr/bin/printenv

**Comment by garnier-quentin** [comment]
I think you have installed perl DBD oracle dependency in 'PERL5LIB=/lib/perl5/lib/perl5:/root/perl5/lib/perl5'.
You need to compile it without following environment variables: 
PERL_MM_OPT
PERL_LOCAL_LIB_ROOT
PERL_MB_OPT
PERL5LIB

**Comment by bastiencha** [comment]
I eddit /var/lib/centreon-engine/.bashrc

and now I have 

```
# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

PATH="/lib/perl5/bin${PATH:+:${PATH}}"; export PATH;
#PERL5LIB="/lib/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
#PERL_LOCAL_LIB_ROOT="/lib/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
#PERL_MB_OPT="--install_base \"/lib/perl5\""; export PERL_MB_OPT;
#PERL_MM_OPT="INSTALL_BASE=/lib/perl5"; export PERL_MM_OPT;
```

I reboot the server

Now I have 

[centreon-engine@evx-sup1 root]$ printenv
XDG_SESSION_ID=6
HOSTNAME=----
SHELL=/bin/bash
TERM=xterm
HISTSIZE=1000
SSH_CLIENT=----
PERL5LIB=/root/perl5/lib/perl5
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
PERL_MB_OPT=--install_base "/root/perl5"
SSH_TTY=/dev/pts/0
QT_GRAPHICSSYSTEM_CHECKED=1
USER=centreon-engine
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/lib/perl5/bin:/root/perl5/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
MAIL=/var/spool/mail/root
PWD=/root
LANG=fr_FR.UTF-8
HISTCONTROL=ignoredups
HOME=/var/lib/centreon-engine
SHLVL=2
PERL_LOCAL_LIB_ROOT=/root/perl5
LOGNAME=centreon-engine
QTLIB=/usr/lib64/qt-3.3/lib
SSH_CONNECTION=----
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/0
PERL_MM_OPT=INSTALL_BASE=/root/perl5
_=/usr/bin/printenv

and when I test in shell with centreon-engine, now I have

UNKNOWN: Cannot connect: (no error string)

Same in centreon web

**Comment by garnier-quentin** [comment]
Yes. Please compile perl DBD Oracle module without PERL environement variable.

**Comment by bastiencha** [comment]
Must I do in /root/.cpan/build/DBD-Oracle-1.80-2PpnBn

(in root)

perl Makefile-instantclient.PL
make

?

**Comment by garnier-quentin** [comment]
Please don't use CPAN command. Use command manually.

**Comment by bastiencha** [comment]
[root@-- DBD-Oracle-1.80-2PpnBn]# make
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Oracle.bs blib/arch/auto/DBD/Oracle/Oracle.bs 644
Manifying 13 pod documents
[root@-- DBD-Oracle-1.80-2PpnBn]#

?

**Comment by garnier-quentin** [comment]
https://metacpan.org/source/MJEVANS/DBD-Oracle-1.80/INSTALL

**Comment by bastiencha** [comment]
Thanks

I did the manual installation

[root@--- tmp]# tar xvf DBD-Oracle-1.80.tar.gz

[root@--- DBD-Oracle-1.80]# pwd
/tmp/DBD-Oracle-1.80

[root@---DBD-Oracle-1.80]# perl Makefile.PL

..............

All tests successful.
Files=41, Tests=21, 10 wallclock secs ( 0.18 usr  0.06 sys +  7.14 cusr  1.04 csys =  8.42 CPU)
Result: PASS

[root@--- DBD-Oracle-1.80]# make install

"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Oracle.bs blib/arch/auto/DBD/Oracle/Oracle.bs 644
Manifying 13 pod documents
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /root/perl5/lib/perl5/x86_64-linux-thread-multi/auto/DBD/Oracle/Oracle.so
Appending installation info to /root/perl5/lib/perl5/x86_64-linux-thread-multi/perllocal.pod


After I tried my command in centreon-engine but still UNKNOWN: Cannot connect: (no error string)

**Comment by garnier-quentin** [comment]
Here the issue:
 Installing /root/perl5/lib/perl5/x86_64-linux-thread-multi/auto/DBD/Oracle/Oracle.so

Please unset your environment variable related to Perl (and redo the install)

**Comment by bastiencha** [comment]
[root@--- ~]# printenv

XDG_SESSION_ID=7
HOSTNAME=evx-sup1
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=---
QTDIR=/usr/lib64/qt-3.3
QTINC=/usr/lib64/qt-3.3/include
SSH_TTY=/dev/pts/0
QT_GRAPHICSSYSTEM_CHECKED=1
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/root
PATH=/root/perl5/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
PWD=/root
LANG=fr_FR.UTF-8
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
LOGNAME=root
QTLIB=/usr/lib64/qt-3.3/lib
SSH_CONNECTION=---
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/0
_=/usr/bin/printenv

[root@--- DBD-Oracle-1.80]# perl Makefile.PL

> 
> Using DBI 1.627 (for perl 5.016003 on x86_64-linux-thread-multi) installed in /usr/lib64/perl5/vendor_perl/auto/DBI/
> Configuring DBD::Oracle for perl 5.016003 on linux (x86_64-linux-thread-multi)
> 
> If you encounter any problem, a collection of troubleshooting
> guides are available under lib/DBD/Oracle/Troubleshooting.
> 'DBD::Oracle::Troubleshooting' is the general troubleshooting
> guide, while platform-specific troubleshooting hints
> live in their labelled sub-document (e.g., Win32
> hints are gathered in 'lib/DBD/Oracle/Troubleshooting/Win32.pod').
> 
> Trying to find an ORACLE_HOME
> Your LD_LIBRARY_PATH env var is set to ''
> Found /usr/lib/oracle/19.5/client64
> 
> WARNING: Setting ORACLE_HOME env var to /usr/lib/oracle/19.5/client64 for you.
> WARNING: If these tests fail you may have to set ORACLE_HOME yourself!
> Installing on a linux, Ver#3.10
> Using Oracle in /usr/lib/oracle/19.5/client64
> DEFINE _SQLPLUS_RELEASE = "1905000000" (CHAR)
> Oracle Version 19.5.0.0 (19.5)
> Found direct-link candidates: libclntsh.so
> Oracle sysliblist:
> Found header files in /usr/include/oracle/19.5/client64.
> Your LD_LIBRARY_PATH env var is set to ''
> WARNING: Your LD_LIBRARY_PATH env var doesn't include '/usr/lib/oracle/19.5/client64/lib' but probably needs to.
> 
> client_version=19.5
> 
> 
> DEFINE= -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\"19.5.0.0\" -DORA_OCI_102 -DORA_OCI_112
> 
> 
> Checking for functioning wait.ph
> 
> 
> System: perl5.016003 linux x86-01.bsys.centos.org 3.10.0-693.17.1.el7.x86_64 #1 smp thu jan 25 20:13:58 utc 2018 x86_64 x86_64 x86_64 gnulinux
> Compiler:   gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
> Linker:     /usr/bin/ld
> Sysliblist:
> Linking with -lclntsh.
> 
> LD_RUN_PATH=/usr/lib/oracle/19.5/client64/lib
> Using DBD::Oracle 1.80.
> Using DBD::Oracle 1.80.
> Using DBI 1.627 (for perl 5.016003 on x86_64-linux-thread-multi) installed in /usr/lib64/perl5/vendor_perl/auto/DBI/
> Writing Makefile for DBD::Oracle
> Writing MYMETA.yml and MYMETA.json

[root@--- DBD-Oracle-1.80]# make && make test

Skip blib/lib/DBD/Oracle/Troubleshooting/Cygwin.pod (unchanged)
Skip blib/lib/DBD/Oracle.pm (unchanged)
Skip blib/arch/auto/DBD/Oracle/Oracle.h (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Vms.pod (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Hpux.pod (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Linux.pod (unchanged)
Skip blib/lib/DBD/Oracle/GetInfo.pm (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting.pod (unchanged)
Skip blib/arch/auto/DBD/Oracle/dbdimp.h (unchanged)
Skip blib/arch/auto/DBD/Oracle/ocitrace.h (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Sun.pod (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Macos.pod (unchanged)
Skip blib/lib/DBD/Oracle/Object.pm (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Aix.pod (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Win64.pod (unchanged)
Skip blib/lib/DBD/Oracle/Troubleshooting/Win32.pod (unchanged)
cp mk.pm blib/arch/auto/DBD/Oracle/mk.pm
gcc -c  -I/usr/include/oracle/19.5/client64 -I/usr/lib64/perl5/vendor_perl/auto/DBI -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"1.80\" -DXS_VERSION=\"1.80\" -fPIC "-I/usr/lib64/perl5/CORE"  -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\"19.5.0.0\" -DORA_OCI_102 -DORA_OCI_112 Oracle.c
gcc -c  -I/usr/include/oracle/19.5/client64 -I/usr/lib64/perl5/vendor_perl/auto/DBI -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"1.80\" -DXS_VERSION=\"1.80\" -fPIC "-I/usr/lib64/perl5/CORE"  -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\"19.5.0.0\" -DORA_OCI_102 -DORA_OCI_112 dbdimp.c
gcc -c  -I/usr/include/oracle/19.5/client64 -I/usr/lib64/perl5/vendor_perl/auto/DBI -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"1.80\" -DXS_VERSION=\"1.80\" -fPIC "-I/usr/lib64/perl5/CORE"  -Wall -Wno-comment -DUTF8_SUPPORT -DORA_OCI_VERSION=\"19.5.0.0\" -DORA_OCI_102 -DORA_OCI_112 oci8.c
Running Mkbootstrap for DBD::Oracle ()
chmod 644 Oracle.bs
rm -f blib/arch/auto/DBD/Oracle/Oracle.so
gcc  -shared -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wl,-z,relro  Oracle.o dbdimp.o oci8.o  -o blib/arch/auto/DBD/Oracle/Oracle.so     \
   -L/usr/lib/oracle/19.5/client64/lib -lclntsh         \

chmod 755 blib/arch/auto/DBD/Oracle/Oracle.so
cp Oracle.bs blib/arch/auto/DBD/Oracle/Oracle.bs
chmod 644 blib/arch/auto/DBD/Oracle/Oracle.bs
Manifying blib/man3/DBD::Oracle::Troubleshooting.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Cygwin.3pm
Manifying blib/man3/DBD::Oracle.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Sun.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Vms.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Hpux.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Macos.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Aix.3pm
Manifying blib/man3/DBD::Oracle::Object.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Linux.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Win64.3pm
Manifying blib/man3/DBD::Oracle::Troubleshooting::Win32.3pm
Manifying blib/man3/DBD::Oracle::GetInfo.3pm
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ............ ok
t/00-report-prereqs.t ..... #
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module               Want    Have
#     ------------------- ----- -------
#     Config                any   undef
#     DBI                 1.623   1.627
#     Data::Dumper          any   2.145
#     Devel::Peek           any    1.08
#     Encode                any    2.51
#     ExtUtils::MakeMaker   any    6.68
#     Math::BigInt          any   1.998
#     Test::More            any    0.98
#     Test::NoWarnings      any missing
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 6.68
#
# === Test Requires ===
#
#     Module              Want    Have
#     ------------------- ---- -------
#     B                    any    1.35
#     Carp                 any    1.26
#     Data::Dumper         any   2.145
#     Devel::Peek          any    1.08
#     Encode               any    2.51
#     ExtUtils::MakeMaker  any    6.68
#     File::Spec           any    3.40
#     IO::Handle           any    1.33
#     IPC::Open3           any    1.12
#     Math::BigInt         any   1.998
#     Symbol               any    1.07
#     Test::More           any    0.98
#     Test::NoWarnings     any missing
#     Thread::Semaphore    any    2.12
#     lib                  any    0.63
#     utf8                 any    1.09
#     vars                 any    1.02
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
#
# === Runtime Requires ===
#
#     Module      Want  Have
#     ---------- ----- -----
#     DBI        1.623 1.627
#     DynaLoader   any  1.14
#     Exporter     any  5.68
#     strict       any  1.07
#     warnings     any  1.13
#
#
# *** WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ***
#
# The following REQUIRED prerequisites were not satisfied:
#
# Test::NoWarnings is not installed (any version required)
# Test::NoWarnings is not installed (any version required)
#
t/00-report-prereqs.t ..... ok
t/00dbdoracletestlib.t .... ok
t/01base.t ................ ok
t/02versions.t ............ # OCI client library version: 19.5.0.0
t/02versions.t ............ ok
t/05base.t ................ ok
t/10general.t ............. skipped: Unable to connect to Oracle
t/12impdata.t ............. skipped: Unable to connect to Oracle
t/14threads.t ............. skipped: Unable to connect to Oracle
t/15nls.t ................. skipped: Unable to connect to Oracle
t/20select.t .............. skipped: Unable to connect to oracle
t/21nchar.t ............... skipped: Unable to connect to Oracle
t/22nchar_al32utf8.t ...... skipped: Unable to connect to Oracle
t/22nchar_utf8.t .......... skipped: Unable to connect to Oracle
t/23wide_db.t ............. skipped: Unable to connect to Oracle
t/23wide_db_8bit.t ........ skipped: Unable to connect to Oracle
t/23wide_db_al32utf8.t .... skipped: Unable to connect to Oracle
t/24implicit_utf8.t ....... skipped: Unable to connect to Oracle
t/25plsql.t ............... skipped: Unable to connect to Oracle
t/26exe_array.t ........... Can't locate Test/NoWarnings.pm in @INC (@INC contains: t/lib /tmp/DBD-Oracle-1.80/blib/lib /tmp/DBD-Oracle-1.80/blib/arch /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at t/26exe_array.t line 15.
t/26exe_array.t ........... Dubious, test returned 2 (wstat 512, 0x200)
No subtests run
t/28array_bind.t .......... skipped: Unable to connect to Oracle
t/30long.t ................ skipped: Unable to connect to Oracle
t/31lob.t ................. skipped: Unable to connect to Oracle
t/31lob_extended.t ........ skipped: Unable to connect to Oracle
t/32xmltype.t ............. skipped: Unable to connect to Oracle
t/34pres_lobs.t ........... skipped: Unable to connect to Oracle
t/36lob_leak.t ............ skipped: Unable to connect to Oracle
t/38taf.t ................. skipped: Unable to connect to Oracle
t/39attr.t ................ skipped: Unable to connect to Oracle
t/40ph_type.t ............. skipped: Unable to connect to Oracle
t/50cursor.t .............. skipped: Unable to connect to Oracle
t/51scroll.t .............. skipped: Unable to connect to Oracle
t/55nested.t .............. skipped: Unable to connect to Oracle
t/56embbeded.t ............ skipped: Unable to connect to Oracle
t/58object.t .............. skipped: Unable to connect to Oracle
t/60reauth.t .............. skipped: ORACLE_USERID_2 not defined.
t/70meta.t ................ skipped: Unable to connect to Oracle
t/80ora_charset.t ......... skipped: Unable to connect to Oracle
t/rt13865.t ............... skipped: Can't connect to database
t/rt74753-utf8-encoded.t .. skipped: Unable to connect to Oracle database
t/rt85886.t ............... skipped: Unable to connect to Oracle database

Test Summary Report
-------------------
t/26exe_array.t         (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=41, Tests=21,  6 wallclock secs ( 0.19 usr  0.06 sys +  4.36 cusr  0.73 csys =  5.34 CPU)
Result: FAIL
Failed 1/41 test programs. 0/21 subtests failed.
make: *** [test_dynamic] Erreur 255

**Comment by garnier-quentin** [comment]
Have you tried the command centreon_plugins after ?

**Comment by bastiencha** [comment]
yes and still 

UNKNOWN: Cannot connect: (no error string)

I didn't do "make install" because the last error in " make && make test" 

Now I do make install

Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.h
Installing /usr/local/lib64/perl5/auto/DBD/Oracle/dbdimp.h
Installing /usr/local/lib64/perl5/auto/DBD/Oracle/ocitrace.h
Installing /usr/local/lib64/perl5/auto/DBD/Oracle/mk.pm
Installing /usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so
Installing /usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.bs
Installing /usr/local/lib64/perl5/DBD/Oracle.pm
Installing /usr/local/lib64/perl5/DBD/Oracle/GetInfo.pm
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Object.pm
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Cygwin.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Vms.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Hpux.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Linux.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Sun.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Macos.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Aix.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Win64.pod
Installing /usr/local/lib64/perl5/DBD/Oracle/Troubleshooting/Win32.pod
Installing /usr/local/share/man/man3/DBD::Oracle.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::GetInfo.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Object.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Aix.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Cygwin.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Hpux.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Linux.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Macos.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Sun.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Vms.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Win32.3pm
Installing /usr/local/share/man/man3/DBD::Oracle::Troubleshooting::Win64.3pm
Appending installation info to /usr/lib64/perl5/perllocal.pod

And now, the command in shell in centreon-engine work

And in centreon web, that's work

Thank you very much 👍
