### ISSUE TITLE
network::cisco::standard::snmp::plugin --mode configuration False Alerts

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#1788]
Hi All,
Happy new year!
Unfortunately there are again many false alerts in our config checks and I don't know why.
I just downloaded the latest centreon plugins release, but it is still present. I just saved the config on the devices both wr "wr mem" and "copy run start" but it seems, the timestamp is not set correctly on the devices or a wrong oid is called by the plugin. The time on the devices is correct.
The CLI command and output is:
```
./centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --hostname xxx --snmp-username xxx --authpassphrase xxx --snmp-version 3 --authprotocol md5  --mode configuration --critical-status '%{running_last_changed} > (%{running_last_saved} + 300)'
CRITICAL: Configuration Running Last Changed: 1y 4M 4d 13h 47m 25s, Running Last Saved: 1M 1w 6d 3h 22m 28s, Startup Last Changed: 1M 1w 6d 2h 5m 24s | 'running_last_changed'=42471143s;;;0; 'running_last_saved'=3765091s;;;0; 'startup_last_changed'=3760467s;;;0;
```
Anybody an idea how to solve this? Happens both on switches and asas.

Cheers,
Marcus

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of following OID: .1.3.6.1.4.1.9.9.43.1.1 ?

**Comment by MarcusCaepio** [comment]
Sure. but only in a shortened version, because the whole walk shows ip addresses and usernames. I think this are the OIDs you are looking for?

IOS:
```
iso.3.6.1.4.1.9.9.43.1.1.1.0 = Timeticks: (4247114334) 491 days, 13:32:23.34
iso.3.6.1.4.1.9.9.43.1.1.2.0 = Timeticks: (376975579) 43 days, 15:09:15.79
iso.3.6.1.4.1.9.9.43.1.1.3.0 = Timeticks: (376975579) 43 days, 15:09:15.79
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2608 = Timeticks: (372184843) 43 days, 1:50:48.43
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2609 = Timeticks: (373265937) 43 days, 4:50:59.37
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2610 = Timeticks: (374347022) 43 days, 7:51:10.22
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2611 = Timeticks: (375428133) 43 days, 10:51:21.33
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2612 = Timeticks: (376043916) 43 days, 12:33:59.16
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2613 = Timeticks: (376046067) 43 days, 12:34:20.67
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2614 = Timeticks: (376046718) 43 days, 12:34:27.18
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2615 = Timeticks: (376509163) 43 days, 13:51:31.63
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2616 = Timeticks: (376974975) 43 days, 15:09:09.75
iso.3.6.1.4.1.9.9.43.1.1.6.1.2.2617 = Timeticks: (376975579) 43 days, 15:09:15.79
```

**Comment by garnier-quentin** [comment]
it seems ok.
ccmHistoryRunningLastChanged: The value of sysUpTime when the running configuration was last changed.

In your case:
iso.3.6.1.4.1.9.9.43.1.1.1.0 = Timeticks: (4247114334) 491 days, 13:32:23.34

**Comment by MarcusCaepio** [comment]
But has "running_last_saved" to be smaller or greater than "running_last_changed"? Because the default check is:
```
--critical-status
            Set critical threshold for status (Default:
            '%{running_last_changed} > %{running_last_saved}'). Can used
            special variables like: %{running_last_changed},
            %{running_last_saved}, %{startup_last_changed}

```

And If so, why is "running_last_saved" not changing, when I save the config?

**Comment by garnier-quentin** [comment]
The issue seems: cisco doesn't update OID values.

**Comment by MarcusCaepio** [comment]
Ok thanks, we will have a look at it on the firmware
