### ISSUE TITLE
[network::fortinet::fortigate::plugin] cluster status buggy?

### ISSUE THREAD

**Issue by harbourlad** [centreon/centreon-plugins#1790]
Hi all,
i have a problem with the named plugin: I want to get a warning when there is only one node in the cluster or when there is only one node synchronized. So I used the following syntax:
`/usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=cluster-status --hostname=10.11.12.13 --snmp-version='2c' --snmp-community='public'  --warning-total-nodes='2' --warning-synchronized='2' --warning-not-synchronized='' --critical-not-synchronized='' --warning-status='' --critical-status='' --verbose `

In fact there is only one active node within the requested Cluster, but I don't get an according warning - this is the output:
`OK: HA mode: activePassive - Nodes Synchronized: 1, Not Synchronized: 0 - Node 'FGTxxxxxxxxxxxxx' status is 'synchronized' [Hostname: FW01_N2] [Role: master] [Checksum: xxxxxxxxxxxxxxxxxxxxx] | 'total_nodes'=1;0:2;;0; 'synchronized_nodes'=1;0:2;;0; 'not_synchronized_nodes'=0;;;0; 'total_checksums'=1;;;0; Node 'FGTxxxxxxxxxxxxx' status is 'synchronized' [Hostname: FW01_N2] [Role: master] [Checksum: xxxxxxxxxxxxxxxxxxxxx]` 

Then I did some tests and found out that the warning only comes up if the number of available or  synchronized nodes is higher then the requested ones - like this:
`/usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=cluster-status --hostname=10.11.12.13 --snmp-version='2c' --snmp-community='public'  --warning-total-nodes='0' --warning-synchronized='0' --warning-not-synchronized='' --critical-not-synchronized='' --warning-status='' --critical-status='' --verbose`

In that case I get this:
`WARNING: Nodes Total nodes: 1, Synchronized: 1 | 'total_nodes'=1;0:0;;0; 'synchronized_nodes'=1;0:0;;0; 'not_synchronized_nodes'=0;;;0; 'total_checksums'=1;;;0;  Node 'FGTxxxxxxxxxxxxx' status is 'synchronized' [Hostname: FW01_N2] [Role: master] [Checksum: xxxxxxxxxxxxxxxxxxxxx]                         
You have new mail in /var/spool/mail/root`

Could this be a bug or do I just use it in a wrong way?

**Comment by harbourlad** [comment]
OK - forget this question. I just found out that I just have to use **2:** instead of **2** within the request - this works fine:
`/usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=cluster-status --hostname=10.11.12.13 --snmp-version='2c' --snmp-community='public' --warning-total-nodes='2:' --warning-synchronized='2:' --warning-not-synchronized='' --critical-not-synchronized='' --warning-status='' --critical-status='' --verbose`

**Comment by FiliMila** [comment]
Hi.
It's changed anything about this plugin mode ?
I can see from help that:
 --warning-* --critical-*
            Set thresholds. Can be: 'total-nodes', 'synchronized',
            '**unsynchronized**', 'total-checksums', 'cpu-utilization',
            'memory-usage'.
I'm asking because I'm receiving as output from it:
Unknown option: critical-not-synchronized at /neteye/shared/monitoring/plugins/centreon-plugin/centreon/plugins/alternative/Getopt.pm line 67.
Please let me know.
Thanks a lot.

**Comment by garnier-quentin** [comment]
You need to update your plugin.

**Comment by FiliMila** [comment]
2022-01-13 Quentin Garnier <qgarnier@centreon.com>
 * Plugin added: AWS FSx
 * Plugin added: Azure Virtual Machine Scale Sets
 * Plugin added: Barracuda Message Archiver SNMP
 * Plugin added: Dell OME-M SNMP
 * Plugin added: Fortinet FortiSwitch SNMP
 * Plugin added: Hikvision NVR ISAPI
 * Plugin added: Hikvision NVR SNMP
 * Plugin added: HPE Simplivity Rest API
 * Plugin added: Lenovo RackSwitch SNMP
 * Plugin added: Microsens G6 SNMP
 * Plugin added: Redis Sentinel
 * Break: [mssql] 'backup-age'

**Comment by garnier-quentin** [comment]
Sorry. Yes you need to update plugin invocation.

**Comment by FiliMila** [comment]
Hi after a better check I can say that something doesn't work...
Please let me explain: with same plugin (latest version) it reports previous unknown message, if firmware is v.6.xx
Indeed it works perfectly if firmware is v.5.xx
So I don't want to risk to let it works with newer fw release (changing its invocation) , but let it don't work with previous ones.
Can You please check more about it?
Thanks a lot.

**Comment by garnier-quentin** [comment]
I don't understand your issue @FiliMila

**Comment by FiliMila** [comment]
Thanks, with Your suggestions I've solved all
