### ISSUE TITLE
Issue with network::cisco::standard::snmp::plugin --mode=environment --component=temperature metrics

### ISSUE THREAD

**Issue by der-huhu** [centreon/centreon-plugins#1791]
Hello,

i have a feeling that, on some network devices, the metric name is created faulty. 

On Cisco Catalyst 3650, if we monitor the temperature, the metrics get put as follows:

'temp_Switch 1 - Temp Sensor 0, GREEN '=30C;0:34;0:39;; 'temp_Switch 1 - Temp Sensor 1, GREEN '=35C;0:34;0:39;; 'temp_Switch 1 - Temp Sensor 2, GREEN '=42C;0:34;0:39;; 'count_temperature'=3;;;;

Now, from what i gather, this "metic name" contains the following information:
'temp_Switch 1 - Temp Sensor 0, GREEN ' with "temp_Switch 1" being the number of the switch in a stacked scenario, "Temp Sensor 0" being the name of the sensor and "GREEN" being the (vendor defined) state that value is in.

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --hostname hostname --snmp-community=community --snmp-version=2c --mode=environment --component=temperature

So, i have multiple questions:
a) Shouldn't the metric be named differently, something like: "switch1_sensor1" followed by the value? So if the (vendor defined) state Changes, no new metric gets created?
b) Shouldn't there be a switch to make it alarm on the (vendor defined) threshold, i.e. GREEN, since that should be changing?

Thank you in advance!

**Comment by garnier-quentin** [comment]
could you provide me the snmpwalk of following OID:
snmpwalk -ObentU -v 2c -c public IP_CISCO .1.3.6.1.4.1.9.9.13.1.3.1 > temp_cisco.snmpwalk

**Comment by der-huhu** [comment]
.1.3.6.1.4.1.9.9.13.1.3.1.2.1010 = STRING: "Switch 1 - Temp Sensor 0, GREEN "
.1.3.6.1.4.1.9.9.13.1.3.1.2.1011 = STRING: "Switch 1 - Temp Sensor 1, GREEN "
.1.3.6.1.4.1.9.9.13.1.3.1.2.1012 = STRING: "Switch 1 - Temp Sensor 2, GREEN "
.1.3.6.1.4.1.9.9.13.1.3.1.3.1010 = Gauge32: 30
.1.3.6.1.4.1.9.9.13.1.3.1.3.1011 = Gauge32: 35
.1.3.6.1.4.1.9.9.13.1.3.1.3.1012 = Gauge32: 41
.1.3.6.1.4.1.9.9.13.1.3.1.4.1010 = INTEGER: 60
.1.3.6.1.4.1.9.9.13.1.3.1.4.1011 = INTEGER: 125
.1.3.6.1.4.1.9.9.13.1.3.1.4.1012 = INTEGER: 125
.1.3.6.1.4.1.9.9.13.1.3.1.5.1010 = INTEGER: 0
.1.3.6.1.4.1.9.9.13.1.3.1.5.1011 = INTEGER: 0
.1.3.6.1.4.1.9.9.13.1.3.1.5.1012 = INTEGER: 0
.1.3.6.1.4.1.9.9.13.1.3.1.6.1010 = INTEGER: 1
.1.3.6.1.4.1.9.9.13.1.3.1.6.1011 = INTEGER: 1
.1.3.6.1.4.1.9.9.13.1.3.1.6.1012 = INTEGER: 1

I see, cisco violated MIB best practices again, but still:
.1.3.6.1.4.1.9.9.13.1.3.1.3 is the value and .4 is the threshold, .5 the state. 
So maybe parse the .2?

**Comment by garnier-quentin** [comment]
So the description can become: 'Switch 1 - Temp Sensor 0, RED' for example ? I could remove GREEN/YELLOW/RED/...

**Comment by der-huhu** [comment]
Yes, from what i gather it will change to descriptions like that.
Is the default state change already depending on the internal thresholds?

**Comment by Aleksey-Maksimov** [comment]
Hello, @der-huhu 
You can use the "--change-perfdata" option to remove the excess from the metric name. The option can be used several times. For example, like this:

`--filter-perfdata='(^temp_SW*|^sensor*)' --change-perfdata=' RED ','_' --change-perfdata=' YELLOW ','_' --change-perfdata=' GREEN ','_'`

**Comment by garnier-quentin** [comment]
I think it's the best solution.
