### ISSUE TITLE
new plugin to check Libra ESVA

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1792]
Libraesva (https://www.libraesva.com/) could be monitored through SNMP. It should be nice to have a Plugin to monitor:
- mail bounced
- mail rejected
- spam
- virus
- total mailq
- incoming mailq
- outgoing mailq
- cluster status
ecc.

Mail Sent (OID: 1.3.6.1.4.1.41091.1.1.1.0)
Mail Received (OID: 1.3.6.1.4.1.41091.1.1.2.0)
Mail Rejected (OID: 1.3.6.1.4.1.41091.1.1.3.0)
Mail Bounced (OID: 1.3.6.1.4.1.41091.1.1.4.0)
Spam Messages (OID: 1.3.6.1.4.1.41091.1.1.5.0)
Infected Messages (OID: 1.3.6.1.4.1.41091.1.1.6.0)
Total Mail Queue (OID: 1.3.6.1.4.1.41091.1.1.7.0)
Incoming Mail Queue (OID: 1.3.6.1.4.1.41091.1.1.8.0)
Outgoing Mail Queue (OID: 1.3.6.1.4.1.41091.1.1.9.0)
Cluster Status (OID: 1.3.6.1.4.1.41091.1.1.10.0)
Version (OID: 1.3.6.1.4.1.41091.1.2.1.0)

You can find the mib file attached.
[libraesva_mib.txt](https://github.com/centreon/centreon-plugins/files/4040462/libraesva_mib.txt)

**Comment by garnier-quentin** [comment]
You mib file seems very small ;) And could you provide the snmpwalk please ?

**Comment by joschi99** [comment]
Hi @garnier-quentin,
here you will find the snmpwalk, but the walk is not complete. For example the OID's above are not present. If I try to launch a walk only for the tree .1.3.6.1.4.1.41091 the system returns "No Such Object available on this agent at this OID". But if I query the exact OID the system will respond correctly

```
snmpwalk -On -cpublic -v2c x.x.x.x 1.3.6.1.4.1.41091.1.2.1.0
.1.3.6.1.4.1.41091.1.2.1.0 = STRING: "4.7.1"
```

[snmpwalk.zip](https://github.com/centreon/centreon-plugins/files/4059262/snmpwalk.zip)

**Comment by garnier-quentin** [comment]
Do you have the last mib ? And could get one by one directly OIDS ?

**Comment by garnier-quentin** [comment]
OK i have a mode. But i need the cluster status value.

**Comment by joschi99** [comment]
Values for cluster status:
-1 --> no cluster
0 --> Cluster Ok
1 --> Cluster Error

**Comment by garnier-quentin** [comment]
thanks. it's done :)

**Comment by joschi99** [comment]
Great. I will provide you feedback next week.
wish you a nice weekend
