### ISSUE TITLE
Forti plugins - Detected virus values are wrong

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#1793]
Operation below will always result in '0'.  

https://github.com/centreon/centreon-plugins/blob/923cc8e27bc7da40835b2fbaf3a1a8158de05ae0/centreon/common/fortinet/fortigate/mode/virus.pm#L153

We should substract $old_* values instead. 

Simon

**Comment by garnier-quentin** [comment]
counters migration we have to!

**Comment by Sims24** [comment]
Right, you are.
