### ISSUE TITLE
database::mongodb::plugin::connectiontime | thresholds issue

### ISSUE THREAD

**Issue by kylonkzn** [centreon/centreon-plugins#1794]
Hello all,
i'm trying to monitor my mongodb and I have a problem with thresholds in connection-time mode
my command is
centreon_plugins.pl --plugin=database::mongodb::plugin --hostname=*** --username='***' --password='***' --mode=connection-time --warning-connection-time-milliseconds=200 --critical-connection-time-milliseconds=500
OK: Connection established in 273 ms | 'connection.time.milliseconds'=273ms;;;0;

i can't understand why i receive OK state if value is bigger than warning threshold
If I set a lower value i receive OK state also

Thank you in advance

**Comment by garnier-quentin** [comment]
Please use following options:
```
-warning-connection-time=200 --critical-connection-time=500
```

**Comment by kylonkzn** [comment]
Thanks for answer, 
but it isn't work also
in this case i receive issue:
argument -warning-connection-time=200 alone at /root/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 93.

if i use "--" nothing changed
centreon_plugins.pl --plugin=database::mongodb::plugin --mode=connection-time --hostname=*** --username='***' --password='***' --warning-connection-time=200 --critical-connection-time=500
OK: Connection established in 270 ms | 'connection.time.milliseconds'=270ms;;;0;

**Comment by kylonkzn** [comment]
@garnier-quentin 
can you please re-open this issue.

**Comment by garnier-quentin** [comment]
It should be ok now

**Comment by kylonkzn** [comment]
Thanks a lot. It works now.
and it works fine in both of cases
--warning-connection-time=*** --critical-connection-time=*** 
and
--warning-connection-time-milliseconds=*** --critical-connection-time-milliseconds=***
