### ISSUE TITLE
[storage] - size perfdata unit not set

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1795]
Hi @garnier-quentin 
In reference of issue #560, have you set the perfdata unit from used, because it seems not set yet.
the size metric haven't any unit, see below

`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=X.X.X.X --snmp-version='2c' --snmp-community='public'  --storage '/mnt/data' --name --display-transform-src='' --display-transform-dst='' --warning-usage='80' --critical-usage='90' --explode-perfdata-max='used,size'`

> OK: Storage '/mnt/data' Usage Total: 19.56 GB Used: 7.44 GB (38.06%) Free: 12.11 GB (61.94%) | 'used'=7993184256B;0:16799547392;0:18899490816;0;20999434240 'size'=20999434240;;;;

Thanks.

**Comment by garnier-quentin** [comment]
It's working for me. Please update your plugin

**Comment by cmeschin** [comment]
ok, thanks.
It's work with the latest release of December 19.
I'm using the October 16 release in production environment.
Regards.
