### ISSUE TITLE
[hardware::ups::apc::snmp::plugin] mode "sensors" and APC NMC AP9619 with Sensor AP9512TBLK

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1798]
Hello.

We have several UPSs with a module "APC Network Management Card AP9619" + "APC Temperature External Sensor AP9512TBLK"
The plugin does not show information from an external sensor.

```
# ./centreon_plugins.pl --plugin=hardware::ups::apc::snmp::plugin 
--mode=sensors 
--snmp-version=2c --snmp-community=public --hostname=UP001 --verbose 
--critical='temperature,.*,11:39' --critical='humidity,.*,6:59' 
--filter-perfdata='^(?!count_sensor)' --filter-uom='%'

OK: All 0 components are ok []. |
Checking sensors
```

![изображение](https://user-images.githubusercontent.com/17614847/72324012-10fcab00-36bb-11ea-9783-334829a1dc49.png)

[UPS_APC_Smart_UPS_SURT6000XLI_with_NMC_AP9619.zip](https://github.com/centreon/centreon-plugins/files/4057916/UPS_APC_Smart_UPS_SURT6000XLI_with_NMC_AP9619.zip)

Name/OID: iemStatusProbesNumProbes.0; Value (Integer): 1
Name/OID: iemStatusProbeNumber.1; Value (Integer): 1
Name/OID: iemStatusProbeName.1; Value (OctetString): Int Sensor
Name/OID: iemStatusProbeStatus.1; Value (Integer): connected (2)
Name/OID: iemStatusProbeCurrentTemp.1; Value (Integer): 24
Name/OID: iemStatusProbeTempUnits.1; Value (Integer): celsius (1)
Name/OID: iemStatusProbeCurrentHumid.1; Value (Integer): -1

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk with following command ?
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1 > apc.snmpwalk

**Comment by Aleksey-Maksimov** [comment]
The file is attached to the first message under the screenshot

**Comment by garnier-quentin** [comment]
You can test it!

**Comment by Aleksey-Maksimov** [comment]
For **NMC Gen1** modules, like AP9619, its OK:
```

OK: All 1 components are ok [1/1 sensors]. | 'temp_Int Sensor'=24;;11:39;;
checking sensors
sensor 'Int Sensor' status is 'connected' 
[instance = 1] [temperature = 24 celsius] [humidity = - %]
```
But for **NMC2 Gen2** modules, like AP9631, now we get an error:

```
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/snmp.pm line 897.
Use of uninitialized value in hash element at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/snmp.pm line 900.
Use of uninitialized value in concatenation (.) or string at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/snmp.pm line 897.
Use of uninitialized value in hash element at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/snmp.pm line 900.
OK: All 2 components are ok [2/2 sensors]. | 'temp_Port 1 Temp 1'=26;;11:39;; 'humidity_Port 1 Temp 1'=10%;;6:59;0;100 'temp_Port 1 Temp 1'=26;;11:39;; 'humidity_Port 1 Temp 1'=10%;;6:59;0;100
checking sensors
sensor 'Port 1 Temp 1' status is 'uioNormal' [instance = 1.1] [temperature = 26 C] [humidity = 10 %]
sensor 'Port 1 Temp 1' status is 'connected' [instance = 1] [temperature = 26 celsius] [humidity = 10 %]
```

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk of the equipment with the problem ?

**Comment by Aleksey-Maksimov** [comment]
[UPS_APC_Smart_UPS_NMC_gen2.zip](https://github.com/centreon/centreon-plugins/files/4060000/UPS_APC_Smart_UPS_NMC_gen2.zip)

**Comment by garnier-quentin** [comment]
Sorry  i have done the fix. I have migrate to new perfdata.

**Comment by Aleksey-Maksimov** [comment]
Hello.

APC UPS control modules have two types of external sensors. 
* The first type is sensors that measure temperature and humidity. 
* The second type is sensors that measure only temperature.

The plugin works successfully with the first type of sensors, but for some reason it shows information twice about humidity and temperature under different names ("universal" and "integrated"):

```
# ./centreon_plugins.pl --plugin=hardware::ups::apc::snmp::plugin 
--mode=sensors 
--snmp-version=2c --snmp-community=public --hostname=UP33 --verbose 
--critical='temperature,.*,11:39' --critical='humidity,.*,6:59' 
--filter-perfdata='^(?!hardware.sensor.count) --filter-uom='%'

OK: All 2 components are ok [2/2 sensors]. | 
'Port 1 Temp 1#sensor.universal.temperature.celsius'=22;;11:39;; 
'Port 1 Temp 1#sensor.universal.humidity.percentage'=23%;;6:59;0;100 
'Port 1 Temp 1#sensor.integrated.temperature.celsius'=22;;11:39;; 
'Port 1 Temp 1#sensor.integrated.humidity.percentage'=23%;;6:59;0;100
checking sensors
universal sensor 'Port 1 Temp 1' status is 'uioNormal' 
[instance = 1.1] [temperature = 22 C] [humidity = 23 %]
integrated sensor 'Port 1 Temp 1' status is 'connected' 
[instance = 1] [temperature = 22 celsius] [humidity = 23 %]
```



And there is still a problem with the second type of sensors (only a temperature sensor without humidity). The plugin shows CRITICAL, although there is no problem, since the plugin in the control module humidity information is simply not available.

![изображение](https://user-images.githubusercontent.com/17614847/72665825-222c1b80-3a1d-11ea-95ba-34ff5af53fb6.png)


```
# /centreon_plugins.pl --plugin=hardware::ups::apc::snmp::plugin 
--mode=sensors 
--snmp-version=2c --snmp-community=public --hostname=UP16 --verbose 
--critical='temperature,.*,11:39'--critical='humidity,.*,6:59'
--filter-perfdata='^(?!hardware.sensor.count)' --filter-uom='%'

CRITICAL: integrated sensor humidity 'Port 1 Temp 1' is 0 % | 
'Port 1 Temp 1#sensor.universal.temperature.celsius'=20;;11:39;; 
'Port 1 Temp 1#sensor.integrated.temperature.celsius'=20;;11:39;; 
'Port 1 Temp 1#sensor.integrated.humidity.percentage'=0%;;6:59;0;100
checking sensors
universal sensor 'Port 1 Temp 1' status is 'uioNormal' 
[instance = 1.1] [temperature = 20 C] [humidity = - %]
integrated sensor 'Port 1 Temp 1' status is 'connected' 
[instance = 1] [temperature = 20 celsius] [humidity = 0 %]
```

**Comment by garnier-quentin** [comment]
I don't have the 'Not available' status in the mib file. So i added a prefix to the instance. You can filter your humidity threshold.

**Comment by Aleksey-Maksimov** [comment]
Hello. 
I did not quite understand how to use it. 
Could you please give an example?

**Comment by Aleksey-Maksimov** [comment]
Hello

This does not seem to solve the problem. The method you proposed only changes the output status of the plugin, as it allows us to use CRIT-limits only for sensor.universal.humidity.percentage. But in this case, we lose the CRIT-limit control for sensor.integrated.humidity.percentage where this indicator has a non-zero value.

**Comment by Aleksey-Maksimov** [comment]
How can we make the plugin process only sensor.integrated.* ?

**Comment by Aleksey-Maksimov** [comment]
![изображение](https://user-images.githubusercontent.com/17614847/73122927-34690500-3f9b-11ea-9993-b8de6b39005a.png)

However, even if we can only filter sensors of type sensor.integrated. *, There still remains a problem with the control modules in which the external sensor can only measure temperature. In this case, the humidity returns as a zero value and the plug-in will change the status to critical.

**Comment by Aleksey-Maksimov** [comment]
Hello.
What about the last two questions?

**Comment by garnier-quentin** [comment]
You can filter with that option:
```
--filter=sensor,universal --filter=sensor,integrated
```

**Comment by garnier-quentin** [comment]
For the threshold, you can filter the specific instance (and you can do a negative regexp):
```
--warning='humidity,universal.1,40'
```

**Comment by Aleksey-Maksimov** [comment]
Hello.
I think the problem is not resolved and we won’t achieve anything with filters.

I analyzed the behavior of APC NMC Gen1 and Gen2 modules with a temperature and humidity sensor connected and with a temperature-only sensor connected.
As I understand it, the problem is, the plugin returns the value "Port 1 Temp 1 # sensor.integrated.humidity.percentage" = 0% for those NMC Gen2 modules that only have a temperature sensor (no humidity)
To solve this problem, we can try to additionally check another OID, which can show the state of the disabled humidity sensor.

> Name	 .iso.org.dod.internet.private.enterprises.apc.products.hardware.universalInputOutput.uioSensor.uioSensorStatusTable.uioSensorStatusEntry.uioSensorStatusHumidity
> OID	 .1.3.6.1.4.1.318.1.1.25.1.2.1.7
> MIB	 PowerNet-MIB
> Syntax	 INTEGER
> Access	 read-only
> Status	 mandatory
> DefVal	
> Indexes	 uioSensorStatusPortID, uioSensorStatusSensorID
> Descr	 The sensor's current humidity reading in percent relative humidity. -1 indicates an invalid reading due to either a sensor that doesn't read humidity or lost communications.

That is, if we get the value "uioSensorStatusHumidity.1.1; Value (Integer): -1", then we need to ignore the integrated.humidity moisture indicator and not display information on it.

For example, a NMC Gen2 module without a humidity sensor will return -1, and with a humidity sensor it will return an integer in percent:

- APC NMC Gen2 (AP9631) with Temperature Only Sensor:  
uioSensorStatusHumidity.1.1; Value (Integer): -1

- APC NMC Gen2 (AP9631/AP9537SUM) with Temperature + Humidity Sensor: 
uioSensorStatusHumidity.1.1; Value (Integer): 11

In addition, it is important to consider that the MNC Gen1 module does not have an OID uioSensorStatusHumidity

**Comment by Aleksey-Maksimov** [comment]
Hello.
What about last question?

**Comment by Aleksey-Maksimov** [comment]
Hello, @garnier-quentin.

Any news?

**Comment by garnier-quentin** [comment]
i was in holidays. sorry for the delay. i will try to look it soon.

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin,
Can I help you with something else to solve this problem?

**Comment by UrBnW** [comment]
You should be able to use `--filter` to exclude the whole parts you're not interested into (`humidity` here), you can even be precise on the instances themselves.

**Comment by Aleksey-Maksimov** [comment]
Hello UrBnW, 
Please read the discussion above carefully. The `--filter` option has already been discussed. And this option will not help.

**Comment by UrBnW** [comment]
I did not catch `--filter` in the discussion above. Anyway, glad to help, and good luck then 👍

**Comment by garnier-quentin** [comment]
I don't see the logic. You have an issue with integrated sensor humidity (Following table: .1.3.6.1.4.1.318.1.1.10.2.3.2).
And you want to check the table universal sensor (uioSensorStatusTable) ? I don't see the link.
