### ISSUE TITLE
Os::linux::snmp::plugin storage problem

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#180]
Hi,

It seems that the linux plugin does not understand correctly the storage size when the partition/disk is more than 8TB (It could be even with less, I just have partition that is more than 8TB).
The output is:
Storage '/images/images' Total: 44.70 GB Used: 8.39TB (100.0%) Free: 0.00B (0.00%)

**Comment by garnier-quentin** [comment]
Could you do a walk of the OIDs ? Surely a problem with net-snmp.

**Comment by garnier-quentin** [comment]
You should use 'disk-usage' mode.

**Comment by kadrika** [comment]
Disk-usage mode gives me: Can't construct cache. I will try to find the OID's and walk them.

**Comment by garnier-quentin** [comment]
For 'disk-usage', you need to configure your net-snmp daemon (see the mode help).

**Comment by kadrika** [comment]
Ok, I will try to get that working.
