### ISSUE TITLE
Put two values in one variable

### ISSUE THREAD

**Issue by XomaFR** [centreon/centreon-plugins#1804]
Hello,

I need to check several process. For this I wish to do it in one order.
But I can't figure out how to put 2 values in a variable.

perl /usr/lib/centreon/plugins_github/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=x.x.x.x --snmp-community=X --snmp-version=X --process-name=**_Example1.exe,Example2.exe_**

Thank you!

**Comment by garnier-quentin** [comment]
you can use a regexp:
```
--process-name='Example1.exe|Example2.exe' --regexp-name

**Comment by XomaFR** [comment]
Oh okey it's fantastic !! Thank you
do you have a description for the utility of --"regexp-name" ?

**Comment by garnier-quentin** [comment]
In the help ;)
