### ISSUE TITLE
[network::riverbed::interceptor::snmp::plugin] - Disco-Show doesn't work on EL7

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1805]
Hi,
It seems this plugin doesn't work with discovery mode on EL7. The returned value is empty.
The plugin has been updated on latest release on each OS.

> Mise à jour:
>  centreon-plugin-Network-Riverbed-Interceptor-Snmp                          noarch                          20191219-152203.el6                          centreon-stable-noarch                           61 k
> 

and 

> Mise à jour :
>  centreon-plugin-Network-Riverbed-Interceptor-Snmp                        noarch                        20191219-152203.el7.centos                         centreon-stable-noarch                         60 k

This issue is present on previous release of centreon-plugin (20190704-123459) too.

on poller with CentOS7
`/usr/lib/centreon/plugins/centreon_riverbed_interceptor.pl --plugin=network::riverbed::interceptor::snmp::plugin --mode=list-storages --hostname=1.3.2.1 --snmp-version='2c' --snmp-community='public'  --disco-show`

```
 <?xml version="1.0" encoding="utf-8"?>
 <data/>
```

On poller with CentOS6
`/usr/lib/centreon/plugins/centreon_riverbed_interceptor.pl --plugin=network::riverbed::interceptor::snmp::plugin --mode=list-storages --hostname=1.3.2.1 --snmp-version='2c' --snmp-community='public' --disco-show`
```
<?xml version="1.0" encoding="utf-8"?>
<data>
  <label name="/" total="25062338560" storageid="31"/>
  <label name="/mnt/cdumps" total="31494885376" storageid="32"/>
  <label name="/mnt/clogs" total="9944129536" storageid="33"/>
  <label name="/mnt/database" total="151053033472" storageid="34"/>
  <label name="/mnt/data" total="698358464512" storageid="35"/>
  <label name="/dev/shm" total="16712810496" storageid="39"/>
  <label name="/boot" total="990961664" storageid="40"/>
  <label name="/mnt/spare" total="25062338560" storageid="41"/>
  <label name="/mnt/tmp" total="9944129536" storageid="42"/>
  <label name="/usr/mazu/tmp" total="16712810496" storageid="43"/>
</data>
```

Thanks for your help.
Regards.

**Comment by garnier-quentin** [comment]
It should work. nothing changes.

**Comment by cmeschin** [comment]
Hi,
I tried with --debug and --verbose options but that's don't help anymore.
How can I test with a "debug++" mode :)

**Comment by garnier-quentin** [comment]
snmpwalk doesn't get host storage information also. SNMP agent seems to have a specific configuration (according the IP source).
