### ISSUE TITLE
[network::cisco::standard::snmp::plugin] Monitoring switches on the stack (cpu, memory, uptime)

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#1808]
Hello.

In the **Cisco stack**, all switches work as a single unit and have one IP address for management and monitoring. 
We connected a monitoring stack of 4 **Cisco 2960X** switches. 
And now it is not clear how to interpret information in some modes in the plugin.

For example, some plug-in modes (**environment**, **memory-flash**, **interfaces**) correctly display information on all switches in the stack.

```
# /centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin 
--mode=environment --no-component --verbose
--change-perfdata='( RED | YELLOW | GREEN ),_' 
--change-perfdata='\.,_'
--filter-perfdata='^(?!count_)' --filter-uom='%' 
--hostname='SW40' --snmp-community='public' --snmp-version='2c'

OK: All 16 components are ok [4/4 fans, 4/4 modules, 4/4 psus, 4/4 temperatures]. | 
'temp_SW#1, Sensor#1,_'=34;;~:68;; 
'temp_SW#2, Sensor#1,_'=34;;~:68;; 
'temp_SW#3, Sensor#1,_'=34;;~:68;; 
'temp_SW#4, Sensor#1,_'=36;;~:68;;
Environment type: c37xx
Checking fans
fan 'Switch#1, Fan#1' status is normal [instance: 1007].
fan 'Switch#2, Fan#1' status is normal [instance: 2007].
fan 'Switch#3, Fan#1' status is normal [instance: 3007].
fan 'Switch#4, Fan#1' status is normal [instance: 4007].
Checking power supplies
Power supply 'Sw1, PS1 Normal, 
RPS Normal' status is normal [instance: 1006] [source: ac]
Power supply 'Sw2, PS1 Normal, 
RPS Normal' status is normal [instance: 2006] [source: ac]
Power supply 'Sw3, PS1 Normal, 
RPS Normal' status is normal [instance: 3006] [source: ac]
Power supply 'Sw4, PS1 Normal, 
RPS Normal' status is normal [instance: 4006] [source: ac]
Checking temperatures
Temperature 'SW#1, Sensor#1, 
GREEN ' status is normal [instance: 1008] [value: 34 C]
Temperature 'SW#2, Sensor#1, 
GREEN ' status is normal [instance: 2008] [value: 34 C]
Temperature 'SW#3, Sensor#1, 
GREEN ' status is normal [instance: 3008] [value: 34 C]
Temperature 'SW#4, Sensor#1, 
GREEN ' status is normal [instance: 4008] [value: 36 C]
Checking voltages
Checking modules
Module 'Stacking Module' status is ok [instance: 1063]
Module 'Stacking Module' status is ok [instance: 2067]
Module 'Stacking Module' status is ok [instance: 3063]
Module 'Stacking Module' status is ok [instance: 4063]
Checking physicals
Checking sensors
```

But there are plugin modes (**cpu**, **memory**, **uptime**) where information is only shown from the MASTER switch (?), but there is no information about the status of other switches in the stack.

```
# ./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin 
--mode=cpu 
--snmp-version='2c' --snmp-community='public' --hostname='SW40' 
--warning-average-5m=90 --critical-average-5m=98

OK: 1 CPU(s) average usage is 34.00 % (5s) 34.00 % (1m) 35.00 % (5m) 
- CPU '1' usage 34.00 % (5s) 34.00 % (1m) 35.00 % (5m) | 
'total_cpu_5s_avg'=34.00%;;;0;100 
'total_cpu_1m_avg'=34.00%;;;0;100 
'total_cpu_5m_avg'=35.00%;0:90;0:98;0;100 
'cpu_5s'=34.00%;;;0;100 
'cpu_1m'=34.00%;;;0;100 
'cpu_5m'=35.00%;;;0;100
```

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk ? I will try to find OIDs about cpu stack (if it exists)

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk for following OIDS ?
.1.3.6.1.2.1.47.1.1.1
.1.3.6.1.4.1.9.9.109.1.1.1

**Comment by garnier-quentin** [comment]
For old catalyst, seems there is a specific community syntax:
https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/40367-camsnmp40367.html

**Comment by Aleksey-Maksimov** [comment]
> 
> 
> For old catalyst, seems there is a specific community syntax:
> https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/40367-camsnmp40367.html

I do not quite understand what this means.

**Comment by garnier-quentin** [comment]
Maybe it's not relevant for stack. I could look with your snmpwalk

**Comment by Aleksey-Maksimov** [comment]
> 
> 
> Could you provide a snmpwalk for following OIDS ?
> .1.3.6.1.2.1.47.1.1.1
> .1.3.6.1.4.1.9.9.109.1.1.1

Just sent you an email

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin,
Can I help you with something else to solve this problem?

**Comment by garnier-quentin** [comment]
It should be maybe:
cpmCPUTotalPhysicalIndex = .1.3.6.1.4.1.9.9.109.1.1.1.1.2

But in your snmpwalk, you have only one entry:
.1.3.6.1.4.1.9.9.109.1.1.1.1.2.1 = INTEGER: 1001

It's a stacked switch ?

**Comment by Aleksey-Maksimov** [comment]
Yes, stacked (stack of 4 Cisco 2960X switches)
If necessary, I can try to unload snmpwalk again

**Comment by garnier-quentin** [comment]
You can try to get  .1.3.6.1.4.1.9.9.109.1.1.1.1.2. Could you ask to Cisco support ?

**Comment by Aleksey-Maksimov** [comment]
Hello @garnier-quentin 

Unfortunately, we do not have a service contract to support these switches, so cisco technical support will not help us here. 
My colleague found a link to more information:

https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15215-collect-cpu-util-snmp.html#multiple

Maybe this will help us somehow?

**Comment by garnier-quentin** [comment]
I already check OIDs from your link.
