### ISSUE TITLE
centreon_plugins.exe --plugin=apps::activedirectory::local::plugin --mode=dcdiag --config=????

### ISSUE THREAD

**Issue by prisme666** [centreon/centreon-plugins#1810]
Hello,
I want to implement the plugin apps::activedirectory::local::plugin, but I don't know the syntax of the config file.
Do you have a procedure or an example to make the config file
Best regard
Thank,

**Comment by garnier-quentin** [comment]
You get it here:
https://github.com/centreon/centreon-plugins/blob/master/apps/activedirectory/local/conf/dcdiag.xml

**Comment by iMeed** [comment]
> You get it here:
> https://github.com/centreon/centreon-plugins/blob/master/apps/activedirectory/local/conf/dcdiag.xml

The page is not found.

**Comment by garnier-quentin** [comment]
Now the link: https://github.com/centreon/centreon-plugins/blob/master/apps/microsoft/activedirectory/local/conf/dcdiag.xml
