### ISSUE TITLE
network::ucopia::wlc::snmp::plugin illegal division by zero

### ISSUE THREAD

**Issue by cmiscloni** [centreon/centreon-plugins#1811]
Hi,

Illegal division by zero with the latest version (master)

`UNKNOWN: Illegal division by zero at /usr/lib/centreon/plugins/centreon_plugins/network/ucopia/wlc/snmp/mode/system.pm line 193.`

Thanks

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk of following OID please ?
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.31218.3 > ucopia.snmpwalk

**Comment by cmiscloni** [comment]
Yes, see below,

`.1.3.6.1.4.1.31218.3.1.0 = Gauge32: 11
.1.3.6.1.4.1.31218.3.2.0 = INTEGER: 5
.1.3.6.1.4.1.31218.3.3.0 = INTEGER: 47
.1.3.6.1.4.1.31218.3.4.0 = INTEGER: 32
.1.3.6.1.4.1.31218.3.5.0 = INTEGER: 0
.1.3.6.1.4.1.31218.3.6.0 = STRING: "Ucopia Controller"
.1.3.6.1.4.1.31218.3.7.0 = INTEGER: 0
`

**Comment by garnier-quentin** [comment]
It should be ok. Could you test it ?

**Comment by cmiscloni** [comment]
Thanks, it's ok

**Comment by garnier-quentin** [comment]
thanks for the feedback
