### ISSUE TITLE
Support of Aruba 5412R zl2 switches

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#1813]
hi,
I want to check the Hardware health of HPE Aruba 5412 zl2 Switches (https://www.arubanetworks.com/fr/produits/produits-reseaux/commutateurs/serie-5400r/).
Unfortunately,I didn't find a way to do it (not kind of pro-curve switch).

Some hints: https://community.hpe.com/t5/Aruba-ProVision-based/Aruba-5406R-zl2-Switch-SNMP-Values/m-p/6990720#M12945.

But maybe i missed the right plugin to monitor. Btw, I didn't find anything in Nagios Exchange speaking about these switches ...

Mibs: https://h10145.www1.hpe.com/downloads/SoftwareReleases.aspx?ProductNumber=J9821A

If you need snmpwalk output, tell me.

jfr

**Comment by garnier-quentin** [comment]
It's an arubaOS-switch. There is an rest api: https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-a00021940en_us&docLocale=en_US

I need the curl commands to develop a plugin

**Comment by garnier-quentin** [comment]
You can choose how to monitor it:
* network/aruba/aoscx/restapi
* network/aruba/aoscx/snmp
