### ISSUE TITLE
Centreon Poller last update date check?

### ISSUE THREAD

**Issue by Jassj89** [centreon/centreon-plugins#1814]
##Question

I searched for plugin, that would check for last update from specific 'Poller' and check that 'last update' from it would be at-least within certain time frame (in last X min).
Did I miss it or there is no such plugin?

Reason for this is that is we have 50 Pollers and lots of hosts services, regular users do not see configuration or check actively what is unreachable, they act only on services that are critical.
In the night one pollers Hard drive crashed for little time so that poller itself was running, all services where up, according to it, but it stopped sending updates and needed Centengine restart.
But we found out that the poller was not monitoring 6h later with all monitoring on it green, (Only on graphs I could see CPU,load getting lower then usual).

## New plugins and modes

If there is no, Would relay like to have one?

**Comment by Sims24** [comment]
Hi @Jassj89 

Actually it does already exist here: 
https://github.com/centreon/centreon-plugins/blob/master/apps/centreon/sql/mode/pollerdelay.pm

Sample use: 

`centreon_plugins.pl --plugin=database::mysql::plugin --dyn-mode=apps::centreon::sql::mode::pollerdelay` 

Enjoy !
