### ISSUE TITLE
Paloalto Panorama check --exclude connection option

### ISSUE THREAD

**Issue by Jassj89** [centreon/centreon-plugins#1815]
Hi

In the last update to centreon-plugins/network/paloalto/snmp/mode/panorama.pm on 2 January 
--exclude option was lost as I see from history.
I do not see another option to exclude checking of a redundant Panorama connection and now always get:
'
CRITICAL: panorama '2' connection status is 'Not-Connected' |
panorama '1' connection status is 'Connected'
panorama '2' connection status is 'Not-Connected'
'

Is there another option to exclude checking of secondary Panorama connection or Can the option be restored?

**Comment by Sims24** [comment]
Hi @Jassj89 

The syntax has changed. You can I thing achieve what you want by orverriding the default --critical-status option value. 

Give a try to: 

'%{status} =~ /not-connected/i && %{display} !~ /^2$/'

Does this work for you ?

**Comment by Jassj89** [comment]
Yes that works with the new one.
Ty

**Comment by Sims24** [comment]
you're welcome!
