### ISSUE TITLE
[os::windows::snmp::plugin] NTP warning and critical not correct

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#1816]
Hello guys,

after the last update the command line for checking NTP offsets has changed. But there was no correction within the databse for the command.

Actual
`$CENTREONPLUGINS$/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=time --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --ntp-hostname='$_SERVICENTPADDR$' --ntp-port='$_SERVICENTPPORT$' --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' --timezone='$_SERVICETIMEZONE$' $_SERVICEEXTRAOPTIONS$`

Needed:
```
    --warning-offset
            Time offset warning threshold (in seconds).

    --critical-offset
            Time offset critical Threshold (in seconds).
```

How can I update the command within the built in version?

Best regards, Michael

**Comment by Sims24** [comment]
Hi @MikeW83 , 

Actually you also need to update the pack to update the command definition. 

Make sure you are using version below: 

![image](https://user-images.githubusercontent.com/12429463/72978784-5b76d980-3dd7-11ea-99f2-52a728a94e98.png)

`Updated :
  centreon-pack-operatingsystems-windows-snmp.noarch 0:3.2.3-1.el7.centos
`

Thanks for using Centreon ;)

**Comment by MikeW83** [comment]
Thank you for the feedback.

But Centreon doesn't show up the possibility to upgrade:
![image](https://user-images.githubusercontent.com/35097389/72983750-59fede80-3de2-11ea-8d26-eaa936054b2a.png)

And via SSH I don't have any updates:
```
# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.anexia.at
 * centos-sclo-rh: centos.anexia.at
 * centos-sclo-sclo: centos.anexia.at
 * extras: centos.anexia.at
 * updates: centos.anexia.at
No packages marked for update
```

**Comment by Sims24** [comment]
Hum weird, @lpinsivy could you check this on the middleware please ? Think we have some kind of failure in online/offline sync.

**Comment by lpinsivy** [comment]
Should be OK now
