### ISSUE TITLE
[database::mongodb::plugin] mode=collection-statistics: to much performance datas

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1817]
Plugin version: 20191016

MongoDB collection status returns to much performance datas. On a MongoDB with 9 databases but many tables the check returns more then 1.000 different performance datas, ~40GB of RRD files generated only for this service.
Maybe it should be a good idea to rework on performance datas for this mode.

**Comment by garnier-quentin** [comment]
Maybe i can add also a filter for collections ? 
I don't know how to get 40GB because: rrd file with 180 days retention = 440KB. 440 * 9 * 1000 = 3,8GB

**Comment by joschi99** [comment]
Hi @garnier-quentin,
after a first analysis this service has created not 1.000 rrd files as I mentioned before, but 49.893 rrd files with a total space occupation around 41,7GB.
At the moment the service is disabled, but we have the rrd files and the records on database on the system.

**Comment by joschi99** [comment]
Checking out the metrics table on centreon_storage there are two index_id's with a hughe number of metrics:
![image](https://user-images.githubusercontent.com/6400595/73106444-bdc8fa80-3efb-11ea-9618-961c43b50333.png)

As you can see, both are related to MongoDB collection statistics:
![image](https://user-images.githubusercontent.com/6400595/73106501-db965f80-3efb-11ea-988c-7a9624886ae8.png)
![image](https://user-images.githubusercontent.com/6400595/73106560-fb2d8800-3efb-11ea-9f0f-2dfc107cb687.png)

**Comment by garnier-quentin** [comment]
Could you show me the metrics name created ? (by email) And a mode output also

**Comment by garnier-quentin** [comment]
Your software creates collection dynamically. You should use database-statistics only (in your case).
