### ISSUE TITLE
[apps::java::jboss::jmx::plugin] Using security Mode

### ISSUE THREAD

**Issue by Cazsc** [centreon/centreon-plugins#1818]
I need to know how i use the login and password to log on wildfly on plugin below, i tried using "--pass-manager jolokia" but don´t work.

Command: **perl centreon_plugins.pl --plugin=apps::java::jboss::jmx::plugin --mode=threads --url='http://192.168.20.62:8080/monitoramento/' --pass-manager jolokia**
Error: **UNKNOWN: Can't locate object method "new" via package "centreon::plugins::passwordmgr::jolokia" (perhaps you forgot to load "centreon::plugins::passwordmgr::jolokia"?) at /usr/share/centreon-plugins/centreon/plugins/script_custom.pm line 172.**

Command:  **perl centreon_plugins.pl --plugin=apps::java::jboss::jmx::plugin --mode=threads --url='http://192.168.20.62:8080/monitoramento/'**

When try normal plugin without "--pass-manager" this is the error, but i need use Jolokia with password. I created a user jolokia and password to test, but don't find to work with it.
Error:
UNKNOWN: protocol issue: Error while fetching http://192.168.20.62:8080/monitoramento/ :

401 Unauthorized

**Comment by garnier-quentin** [comment]
Password manager is not for that. You have --username and --password option.

**Comment by Cazsc** [comment]
Need to change on Help or documentation, because i don't found it's work with security on.
Thanks for the help!!!
perl centreon_plugins.pl --help

Usage:
    centreon_plugins.pl [options]

Options:
    --plugin
            Specify the path to the plugin.

    --list-plugin
            Print available plugins.

    --version
            Print global version.

    --help  Print a brief help message and exits.

    --ignore-warn-msg
            Perl warn messages are ignored (not displayed).

    --runas Run the script as a different user (prefer to use directly the
            good user).

    --global-timeout
            Set script timeout.

    --environment
            Set environment variables for the script (prefer to set it
            before running it for better performance).

    --convert-args
            Change strings of arguments. Useful to use '!' in nrpe protocol.
            Example: --convert-args='##,\x21'

**Comment by garnier-quentin** [comment]
Add the option --plugin

**Comment by Cazsc** [comment]
[root@srvmon001p centreon-plugins]# perl centreon_plugins.pl --plugin=apps::java::jboss::jmx::plugin --help

Plugin Description:
    Check Jboss in JMX. Need Jolokia agent.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

    --custommode
            Choose a custom mode.

    --list-custommode
            List available custom modes.

    --multiple
            Multiple custom mode objects (some mode needs it).

    --pass-manager
            Use a password manager.

**Comment by garnier-quentin** [comment]
Select the mode and you'll get all options.

**Comment by Cazsc** [comment]
I see the user and password option as being primary to the plugin, without it I can't get in any mode.
Now with you guidence i founded the option work with --password --username!
thanks for the help and clarification, now i see all option.

[root@srvmon001p centreon-plugins]# perl centreon_plugins.pl --plugin=apps::java::jboss::jmx::plugin --mode=threads --help

Plugin Description:
    Check Jboss in JMX. Need Jolokia agent.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

    --custommode
            Choose a custom mode.

    --list-custommode
            List available custom modes.

    --multiple
            Multiple custom mode objects (some mode needs it).

    --pass-manager
            Use a password manager.

Output Options:
    --verbose
            Display long output.

    --debug Display also debug messages.

    --filter-perfdata
            Filter perfdata that match the regexp.

    --explode-perfdata-max
            Put max perfdata (if it exist) in a specific perfdata (without
            values: same with '_max' suffix) (Multiple options)

    --change-perfdata --extend-perfdata
            Change or extend perfdata. Syntax:
            --extend-perfdata=searchlabel,newlabel,target[,[newuom],[min],[m
            ax]]

            Common examples:

                Change storage free perfdata in used:
                --change-perfdata=free,used,invert()

                Change storage free perfdata in used:
                --change-perfdata=used,free,invert()

                Scale traffic values automaticaly:
                --change-perfdata=traffic,,scale(auto)

                Scale traffic values in Mbps:
                --change-perfdata=traffic_in,,scale(Mbps),mbps

                Change traffic values in percent:
                --change-perfdata=traffic_in,,percent()

    --extend-perfdata-group
            Extend perfdata from multiple perfdatas (methods in target are:
            min, max, average, sum) Syntax:
            --extend-perfdata-group=searchlabel,newlabel,target[,[newuom],[m
            in],[max]]

            Common examples:

                Sum wrong packets from all interfaces (with interface need
                --units-errors=absolute):
                --extend-perfdata-group=',packets_wrong,sum(packets_(discard
                |error)_(in|out))'

                Sum traffic by interface:
                --extend-perfdata-group='traffic_in_(.*),traffic_$1,sum(traf
                fic_(in|out)_$1)'

    --change-short-output
            Change short output display.
            --change-short-output=pattern~replace~modifier

    --range-perfdata
            Change perfdata range thresholds display: 1 = start value equals
            to '0' is removed, 2 = threshold range is not display.

    --filter-uom
            Filter UOM that match the regexp.

    --opt-exit
            Optional exit code for an execution error (i.e. wrong option
            provided, SSH connection refused, timeout, etc) (Default:
            unknown).

    --output-xml
            Display output in XML format.

    --output-json
            Display output in JSON format.

    --output-openmetrics
            Display metrics in OpenMetrics format.

    --output-file
            Write output in file (can be used with json and xml options)

    --disco-format
            Display discovery arguments (if the mode manages it).

    --disco-show
            Display discovery values (if the mode manages it).

    --float-precision
            Set the float precision for thresholds (Default: 8).

Jolokia Options:
    --url   Url where the jolokia agent is deployed (required). Example:
            http://localhost:8080/jolokia

    --timeout
            Timeout in seconds for HTTP requests (Defaults: 30 seconds)

    --username
            Credentials to use for the HTTP request

    --password
            Credentials to use for the HTTP request

    --proxy-url
            Optional HTTP proxy to use.

    --proxy-username
            Credentials to use for the proxy

    --proxy-password
            Credentials to use for the proxy

    --target-url
            Target to use (if you use jolokia agent as a proxy in --url
            option).

    --target-username
            Credentials to use for the target

    --target-password
            Credentials to use for the target

Retention Options:
    --memcached
            Memcached server to use (only one server).

    --redis-server
            Redis server to use (only one server).

    --redis-attribute
            Set Redis Options (--redis-attribute="cnx_timeout=5").

    --redis-db
            Set Redis database index.

    --memexpiration
            Time to keep data in seconds (Default: 86400).

    --statefile-dir
            Directory for statefile (Default:
            '/var/lib/centreon/centplugins').

    --statefile-suffix
            Add a suffix for the statefile name (Default: '').

    --statefile-concat-cwd
            Concat current working directory with option '--statefile-dir'.
            Useful on Windows when plugin is compiled.

    --statefile-storable
            Use Perl Module 'Storable' (instead Data::Dumper) to store
            datas.

Mode:
    Check threads.

    --warning-*
            Threshold warning. Can be: 'active', 'started', 'daemon'.

    --critical-*
            Threshold critical. Can be: 'active', 'started', 'daemon'.

[root@srvmon001p centreon-plugins]#
[root@srvmon001p centreon-plugins]# perl centreon_plugins.pl --plugin=apps::java::jboss::jmx::plugin --mode=threads --help

Plugin Description:
    Check Jboss in JMX. Need Jolokia agent.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

    --custommode
            Choose a custom mode.

    --list-custommode
            List available custom modes.

    --multiple
            Multiple custom mode objects (some mode needs it).

    --pass-manager
            Use a password manager.

Output Options:
    --verbose
            Display long output.

    --debug Display also debug messages.

    --filter-perfdata
            Filter perfdata that match the regexp.

    --explode-perfdata-max
            Put max perfdata (if it exist) in a specific perfdata (without
            values: same with '_max' suffix) (Multiple options)

    --change-perfdata --extend-perfdata
            Change or extend perfdata. Syntax:
            --extend-perfdata=searchlabel,newlabel,target[,[newuom],[min],[m
            ax]]

            Common examples:

                Change storage free perfdata in used:
                --change-perfdata=free,used,invert()

                Change storage free perfdata in used:
                --change-perfdata=used,free,invert()

                Scale traffic values automaticaly:
                --change-perfdata=traffic,,scale(auto)

                Scale traffic values in Mbps:
                --change-perfdata=traffic_in,,scale(Mbps),mbps

                Change traffic values in percent:
                --change-perfdata=traffic_in,,percent()

    --extend-perfdata-group
            Extend perfdata from multiple perfdatas (methods in target are:
            min, max, average, sum) Syntax:
            --extend-perfdata-group=searchlabel,newlabel,target[,[newuom],[m
            in],[max]]

            Common examples:

                Sum wrong packets from all interfaces (with interface need
                --units-errors=absolute):
                --extend-perfdata-group=',packets_wrong,sum(packets_(discard
                |error)_(in|out))'

                Sum traffic by interface:
                --extend-perfdata-group='traffic_in_(.*),traffic_$1,sum(traf
                fic_(in|out)_$1)'

    --change-short-output
            Change short output display.
            --change-short-output=pattern~replace~modifier

    --range-perfdata
            Change perfdata range thresholds display: 1 = start value equals
            to '0' is removed, 2 = threshold range is not display.

    --filter-uom
            Filter UOM that match the regexp.

    --opt-exit
            Optional exit code for an execution error (i.e. wrong option
            provided, SSH connection refused, timeout, etc) (Default:
            unknown).

    --output-xml
            Display output in XML format.

    --output-json
            Display output in JSON format.

    --output-openmetrics
            Display metrics in OpenMetrics format.

    --output-file
            Write output in file (can be used with json and xml options)

    --disco-format
            Display discovery arguments (if the mode manages it).

    --disco-show
            Display discovery values (if the mode manages it).

    --float-precision
            Set the float precision for thresholds (Default: 8).

Jolokia Options:
    --url   Url where the jolokia agent is deployed (required). Example:
            http://localhost:8080/jolokia

    --timeout
            Timeout in seconds for HTTP requests (Defaults: 30 seconds)

    --username
            Credentials to use for the HTTP request

    --password
            Credentials to use for the HTTP request

    --proxy-url
            Optional HTTP proxy to use.

    --proxy-username
            Credentials to use for the proxy

    --proxy-password
            Credentials to use for the proxy

    --target-url
            Target to use (if you use jolokia agent as a proxy in --url
            option).

    --target-username
            Credentials to use for the target

    --target-password
            Credentials to use for the target

Retention Options:
    --memcached
            Memcached server to use (only one server).

    --redis-server
            Redis server to use (only one server).

    --redis-attribute
            Set Redis Options (--redis-attribute="cnx_timeout=5").

    --redis-db
            Set Redis database index.

    --memexpiration
            Time to keep data in seconds (Default: 86400).

    --statefile-dir
            Directory for statefile (Default:
            '/var/lib/centreon/centplugins').

    --statefile-suffix
            Add a suffix for the statefile name (Default: '').

    --statefile-concat-cwd
            Concat current working directory with option '--statefile-dir'.
            Useful on Windows when plugin is compiled.

    --statefile-storable
            Use Perl Module 'Storable' (instead Data::Dumper) to store
            datas.

Mode:
    Check threads.

    --warning-*
            Threshold warning. Can be: 'active', 'started', 'daemon'.

    --critical-*
            Threshold critical. Can be: 'active', 'started', 'daemon'.
