### ISSUE TITLE
centreon-plugins/os/windows/local/mode

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#182]
Hi team,
Is it possible to have the WMI data for windows?
- Disk IO
- Event Log
- Smart info
- ...

I'm sorry, I would like to help you, but I'm not a dev :-)

Thanks

**Comment by garnier-quentin** [comment]
Hi,

WIth a distant wmi plugin ? I'm not a fan of wmi. You should use NSClient++.

**Comment by garnier-quentin** [comment]
It's in local wmi. We can do that.

**Comment by matthieu-robin** [comment]
For my point of view, it's better to don't install client on monitored server. Distant WMI is really cool, like done with the plugin check_wmi_plus. NSClient is invasive, and in a small enterprise, it' s not simple to maintain it.

**Comment by garnier-quentin** [comment]
For me, wmi protocol is too heavy and really bad with port communication. Otherwise the configuration is not easy. I prefer NSClient. No doubt.

**Comment by matthieu-robin** [comment]
So, no chance to get WMI plugin from Centreon? I'll go with the check_wmi_plus :-1:

**Comment by garnier-quentin** [comment]
Not the priority. But maybe some day.

**Comment by matthieu-robin** [comment]
no problemo :-) Thanks
