### ISSUE TITLE
new plugin to check free IP addresses for Windows DHCP Server

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1821]
Using Powershell command "Get-DhcpServerv4FreeIPAddress" (https://docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4freeipaddress?view=win10-ps) it should be possible to check if DHCP server has free IP leases.

Usefull parameters:
- scopeid
- from ip
- to ip
- warning-free-ip
- critical-free-ip

This plugin could be very useful for DHCP servers with a wide range of different scopes and it can be done without configuring a VLAN for every scope which is necessary using apps::protocols::dhcp::plugin

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This feature request seems particularly old so let me close it. If the feature request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
