### ISSUE TITLE
how to use iis:plugin 

### ISSUE THREAD

**Issue by malekkhelifi** [centreon/centreon-plugins#1826]
how can i use plugin apps::iis::wsman::plugin  or apps::iis::local::plugin can any one help me here please

**Comment by garnier-quentin** [comment]
For that plugin 'apps::iis::local::plugin', you need to execute it on your IIS windows server.

**Comment by garnier-quentin** [comment]
You have some github issue about it: https://github.com/centreon/centreon-plugins/issues/1797

**Comment by malekkhelifi** [comment]
For that plugin 'apps::iis::local::plugin' i have done it and it works fine when  i type (c:\Strawberry\centreon_plugins.exe --plugin=apps::iis::local::plugin --mode=list-applicationpools)   and i but i dont how i'm gone see this in centreon  this is as far as i reache withis this plugin i don't know what to do next

**Comment by garnier-quentin** [comment]
It's not an issue with centreon-plugins. You should read documentation.centreon.com. You'll find information about it
