### ISSUE TITLE
os::linux::local: DiskIO Problem 

### ISSUE THREAD

**Issue by Meistercoach83** [centreon/centreon-plugins#1829]
Hey! I´m trying to use the plugin os::linux::local::plugin diskio

But when the service is generated I get the following error 

> Unknown option: warning-usage

The executed command: `/usr/lib64/nagios/plugins/check_centreon_nrpe -H 172.16.123.129 -p 5666 -t 30 -u -m 8192 -c check_centreon_plugins -a 'os::linux::local::plugin' 'diskio'  " --name='.*'  --regexp --warning-usage='' --critical-usage=''  "`

**Comment by garnier-quentin** [comment]
That option doesn't exist. See the help.

**Comment by Meistercoach83** [comment]
Yes - I know. But it is set in the OS-Linux-Disk-IO-Global-NRPE-custom Template

**Comment by garnier-quentin** [comment]
the plugin-packs is ok.
