### ISSUE TITLE
cloud::azure UNKNOWN: Cannot decode response 

### ISSUE THREAD

**Issue by mbaruchello77** [centreon/centreon-plugins#1831]
Hi
I'm trying to use cloud::azure checks, but not one seems work.

 

> $ perl centreon_plugins.pl --plugin cloud::azure::management::recovery::plugin --custommode api --mode discovery
--subscription 'xxxxx-xxxxx-xxxx-xxxxx-xxxxxxxxxxx' --tenant 'xxxx-xxxxx-xxxx-xxxxx-xxxxx' --client-id 'xxxxxxxxxxxxxxx-xxxx-xxx-xxx' --client-secret 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' --resource-group XXXXXXX --debug
UNKNOWN: Cannot decode response (add --debug option to display returned content)
======> request send
POST https://login.microsoftonline.com/xxxxx-xxxx-xxxx-xxxx-xxxxx/oauth2/token
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded
>
> grant_type=client_credentials&client_id=xxxx-xxxxxx&client_secret=xxxxxxxxxxxxxxxxxxxxxxxx&resource=https%3A%2F%2Fmanagement.azure.com
======> response done
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Date: Wed, 05 Feb 2020 15:08:33 GMT
Pragma: no-cache
Content-Length: 1335
Content-Type: application/json; charset=utf-8
Expires: -1
Client-Date: Wed, 05 Feb 2020 15:08:33 GMT
Client-Peer: 40.126.1.130:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT TLS CA 1
Client-SSL-Cert-Subject: /CN=stamp2.login.microsoftonline.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: fpc=AnSbI3NaFadGlmEivQUv8NotwQ34AQAAAHHRzNUOAAAA; expires=Fri, 06-Mar-2020 15:08:33 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=prod; path=/; SameSite=None; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; SameSite=None; secure; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Ests-Server: 2.1.9987.10 - DUB2 ProdSlices
X-Ms-Request-Id: 3c9aaf89-e7e3-4ce1-8eb5-41a5df2d5c00
>
>{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"3599","expires_on":"1580918913","not_before":"1580915013","resource":"https://management.azure.com","access_token":"eyJ0eXAi...."}
{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"3599","expires_on":"1580918913","not_before":"1580915013","resource":"https://management.azure.com","access_token":"eyJ0e...."}

I get the same error for all cloud::azure* checks
Any idea about this behavior?

Thanks
Matteo

**Comment by garnier-quentin** [comment]
That's weird. Could you test with the last version and provide me the debug ?
It cannot load the json. maybe a character in the access_token (i don't see it all the debug)

**Comment by mbaruchello77** [comment]
Thanks!
it seems work with this latest version

**Comment by garnier-quentin** [comment]
i change nothing about it... it shouldn't work. if you have the issue again, you can provide me the debug
