### ISSUE TITLE
apps::iis::local::plugin  check_webservice-statistics

### ISSUE THREAD

**Issue by malekkhelifi** [centreon/centreon-plugins#1832]
Please follow information shown below according your issue. For all issues, thank you to describe it in English.
If some informations are confidentials, please send it directly by email to qgarnier@centreon.com and sbomm@centreon.com

## Bug/Question

If you are reporting a bug/question, make sure that we do not have any duplicates already open. You 
can ensure this by searching the issue list for this repository. If there is a duplicate, please 
close your issue and add a comment to the existing issue instead.

Otherwise, open your issue and provide all informations you can.

## New plugins and modes

To develop a plugin/mode, we need following informations:
* SNMP: MIBs files and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk)
* HTTP API (SOAP, Rest/Json, XML-RPC): the documentation and some curls examples
* CLI: command line examples
* SQL: requests
* JMX: mbean names and attributes

If you can't provide informations, we'll close the ticket. The issue can be reopened if informations are provided.
All developments are open-source. We can't give a date for the development. If it's a priority, send us an email about it (qgarnier@centreon.com and sbomm@centreon.com) 
and we'll put you in touch with our company. 

Thanks for using centreon-plugins!

**Comment by garnier-quentin** [comment]
Thanks to you :)

**Comment by malekkhelifi** [comment]
when i want to  check_webservice-statistics  and i type on terminale /usr/lib/nagios/plugins/check_centreon_nrpe3 -H 10.80.1.105  -c check_webservice-statistics it give me this error message 
( UNKNOWN: Cannot write statefile '/var/lib/centreon/centplugins/iis_webservice-statistics_a181a603769c1f98ad927e7367c7aa51'. Need write/exec permissions on directory.) 
 So  i give him all the rights he need by typing ( chmod -R 777 /var/lib/centreon/centplugins/) and still have the same problem

**Comment by garnier-quentin** [comment]
please add that option: --statefile-dir=C:/Windows/Temp/

**Comment by malekkhelifi** [comment]
thankyou for your help man :) it is working
