### ISSUE TITLE
[NSClient++] Support v1 API (to replace Legacy API)

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#1833]
Hi,

Do you plan to support NSClient++ v1 API ?
https://docs.nsclient.org/api/rest/

For now only the Legacy one is supported in the `apps::nsclient::restapi` plugin.
https://docs.nsclient.org/api/rest/legacy/

At least seems that this is the [best way](https://docs.nsclient.org/#talking-to-nsclient) to interact with NSclient++ :
_REST is the native NSClient++ protocol (still under development) which allows you to interact with NSClient++ over the http(s) protocol._

Many thanks 👍

**Comment by UrBnW** [comment]
One related question, what's the best way, in your opinion, to monitor a Windows server ?
SNMP support seems rather limited, and almost [deprecated](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831568(v=ws.11)#snmp) by Microsoft...
Sounds then like it's NSclient++ through its API, but would like "to be sure" about the best supported way.
Thank you again !

**Comment by garnier-quentin** [comment]
Yes it can be

**Comment by cgagnaire** [comment]
You should try the protocol NRPE plugin that brings a NSClient custommode that handles new API (https://github.com/centreon/centreon-plugins/tree/master/apps/protocols/nrpe)

**Comment by UrBnW** [comment]
Yes you're right @cgagnaire, sounds like this is somehow hidden in `apps::protocols::nrpe` :)
As it is a NSClient++ specific API, I would have expected to find it in `apps::nsclient::restapi`.

I'll then test this ASAP and report.
Thx 👍

**Comment by UrBnW** [comment]
Works perfectly, many thanks @cgagnaire 👍
No further dev needed then.

Just one thing, perhaps that the `nsclient` custommode should rather be in a dedicated plugin such as `apps::monitoring::nsclient::restapi::plugin` ?
As it's a specific NSClient++ API, "nothing" related to NRPE.
Up to you :)

Thank you !

**Comment by cgagnaire** [comment]
Hi,
Well not really. Its more of a backend kind of custom mode, as people basically use NSClient++ to do NRPE or NRPE-like commands.
Here you can only execute _commands_ with _arguments_, whether you use NRPE or NSClient++, that's what the https://docs.nsclient.org/api/rest/queries/#command-execute endpoint in made for.

**Comment by UrBnW** [comment]
You're right these are "NRPE-like" things, it then also makes sense...
Feel free then to close this ticket if we're done with it.
Thanks again !
