### ISSUE TITLE
[apps::protocols::imap::plugin] add --ssl-opt option

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-plugins#1834]
Hi,
Can you add "--ssl-opt" in IMAP plugin please ?

**Plugin :** 
apps::protocols::imap::plugin  /  centreon_protocol_imap.pl

**Option :** 
--ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" 

Best Regards

**Comment by garnier-quentin** [comment]
Can use that options:
```
--ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --ssl-opt="SSL_version => 'TLSv1'"
```
