### ISSUE TITLE
new plugin Mobotix camera

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1835]
It should be nice to have a plugin to monitor Mobotix cameras.

https://www.mobotix.com/
[MOBOTIX-MIB.txt](https://github.com/centreon/centreon-plugins/files/4169905/MOBOTIX-MIB.txt)

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk ?

**Comment by joschi99** [comment]
here is a complete snmp walk:
[mobotix-snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/4170137/mobotix-snmpwalk.txt)

**Comment by garnier-quentin** [comment]
thanks!

**Comment by garnier-quentin** [comment]
Could you test it ? --plugin=hardware::devices::camera::mobotix::snmp::plugin

**Comment by joschi99** [comment]
Seem's working correctly, thanks.

**Comment by garnier-quentin** [comment]
thanks for the feedback
