### ISSUE TITLE
[os::linux::snmp::plugin] mode storage

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#184]
Hello,

whatever the value i set for --space-reservation option, i have always the same result :
OK: Storage '/donnees' Total: 491.17 GB Used: 132.99 GB (28.50%) Free: 333.62 GB (71.50%)

And always the same value if i don't use this option.

Here is the way i use it :
/usr/lib/nagios/plugins/centreon_plugins.pl  --plugin=os::linux::snmp::plugin --mode=storage --space-reservation=5 --storage='/donnees' --name --regexp ...

Does something goes wrong with this option ?

**Comment by garnier-quentin** [comment]
It should be. Can it get the complete command line ?

**Comment by ritouret** [comment]
/usr/lib/nagios/plugins/centreon_plugins.pl  --plugin=os::linux::snmp::plugin --mode=storage --space-reservation=5 --storage='/donnees' --name --regexp --hostname=xx --snmp-version=2c --snmp-community=xx --snmp-timeout=15 --snmp-retries=1

**Comment by garnier-quentin** [comment]
I see a diff in used/free values.

**Comment by ritouret** [comment]
Should be for total and free, used is always the same whatever space reserved.
It's good for free (diff value) and used (same value) but not for total (same value against diff value).

Goal was to get results like 'df' command like --help describe it.

**Comment by ritouret** [comment]
Sorry Quentin, it's my bad. I think i did not watch until the end of the line to see the free value change.
Values returned from plugin correspond to the df 'command'.

Just another question, i'd seen a long time ago in a help command an url to follow for regex used in centreon-plugins but i can't find it now. Would you remind me which perl regex must be used ?
Many thanks.

**Comment by garnier-quentin** [comment]
I have never put suck link in help command. I don't see.
