### ISSUE TITLE
[os::linux::local::plugin] Negative CPU values

### ISSUE THREAD

**Issue by myOmikron** [centreon/centreon-plugins#1840]
# Bug/Question

Hi I'm using the plugin os::linux::local::plugin and I'm recveiving negative cpu values from time to time. As you can see, I'm running the plugin remotly on a CentOS machine (centreon poller) which is virtualized as container in a proxmox.
If you need additional information, don't hesitate to contact me.
```
-bash-4.2$ /var/lib/plugins/centreon_plugins/./centreon_plugins.pl --plugin os::linux::local::plugin --mode cpu --remote --hostname HOSTNAME --warning 75 --critical 85 --ssh-option='-p=7009'  

CRITICAL: CPU(s) average usage is: -4.25% | 'cpu0'=-4.25%;;;0;100 'total_cpu_avg'=-4.25%;0:75;0:85;0;100
```

**Comment by garnier-quentin** [comment]
Do you have X checks cpu on the same hostname address ? (like you have different ports)

**Comment by myOmikron** [comment]
Yes, I have a cpu check on the hypervisor and one on the centos vm. The centos vm check is the only one, which returns negative cpu values

**Comment by garnier-quentin** [comment]
That's the issue. i'll fix it

**Comment by garnier-quentin** [comment]
I have done a update. Could you test with the last version please ?

**Comment by myOmikron** [comment]
Seems good so far. I'm letting do the check its work for some hours and give a update after that

**Comment by garnier-quentin** [comment]
i close it. and you can open it if you have still the issue

**Comment by myOmikron** [comment]
Okay, thanks for the fast fix!
