### ISSUE TITLE
[os::windows::local::plugin] mode=sessions cannot decode xml response XML::Parser::Expat

### ISSUE THREAD

**Issue by philipraets** [centreon/centreon-plugins#1841]
## Question
When I try to get the sessions on windows computers I get the following message:

> UNKNOWN: Cannot decode xml response: Can't load 'C:\WINDOWS\TEMP\par-50424c45595324\cache-c76700147738cd1ebe2cff42e09b23913f000347\9d4d8540.xs.dll' for module XML::Parser::Expat: load_file:The specified module could not be found at /loader/HASH(0x142d040)/DynaLoader.pm line 193.

my command is: 
`centreon_protocol_nrpe.pl --plugin=apps::protocols::nrpe::plugin --mode=query --custommode=nrpe --hostname=10.10.255.73  --mode=query --custommode=nrpe --command=centreon_plugins --arg="--plugin=os::windows::local::plugin --mode=sessions --config=scripts/centreon/conf/qwinsta.xml --statefile-dir=C:\\Windows\\Temp"`

I have the same message if I execute this from centreon on the cli and when I try to execute the plugin on the windows pc locally.

I have built the centreon_plugins with the attached build-file (renamed to .txt)
[build.txt](https://github.com/centreon/centreon-plugins/files/4191013/build.txt)

Am I missing some dependency?

All this is for 64-bit and built with strawberry-perl-5.30.1.1

Thanks,

Philip

**Comment by garnier-quentin** [comment]
How do you get the centreon_plugins.exe ?

**Comment by philipraets** [comment]
I have nsclient++ running on the hosts which has the centreon_plugins.exe as external_script

I've built the exe like in the documentation with the build script.

**Comment by garnier-quentin** [comment]
You should install following dependency: https://metacpan.org/release/XML-Parser

**Comment by philipraets** [comment]
Do I have to install this on the build-server and add it to the script or do I have to install perl on the hosts? Because the other plugins in the exe are working.

**Comment by garnier-quentin** [comment]
Yes you need to add it on your build server.

**Comment by philipraets** [comment]
It's working, I forgot to add `--link=%PERL_INSTALL_DIR%\c\bin\libexpat-1__.dll ^` to my build script.

Thanks

**Comment by garnier-quentin** [comment]
thanks for the feedback
