### ISSUE TITLE
[network::cisco::aci::apic::restapi::plugin] UNKNOWN: Cannot get token from API

### ISSUE THREAD

**Issue by jumah35** [centreon/centreon-plugins#1843]
Hello,

I'm tryning to use the apic plugin with the following command:
./centreon_plugins.pl --plugin=network::cisco::aci::apic::restapi::plugin --hostname=apic.mydomain.fr --username=myuser --password=mypassword --mode=fabric --debug

**Result without debug option**: 
UNKNOWN: Cannot get token from API

**Result with debug option**;
======> request send
POST https://apic.mydomain.fr:443/api/aaaLogin.json
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/json

{"aaaUser":{"attributes":{"pwd":"mypassword","name":"myuser"}}}
======> response done
500 Can't connect to apic.mydomain.fr:443
Content-Type: text/plain
Client-Date: Wed, 12 Feb 2020 16:15:46 GMT
Client-Warning: Internal response
Can't connect to apic.mydomain.fr:443

It works as expected directly with curl :
curl -X POST -k https://apic.mydomain.fr/api/aaaLogin.xml -d '<aaaUser name="myuser" pwd="mypassword"/>'

Any ideas ? 

Thank you 
Ju

**Comment by garnier-quentin** [comment]
Please try with curl backend: --http-backend=curl

**Comment by jumah35** [comment]
Super fast and it works great. Thank you Quentin :-)

**Comment by garnier-quentin** [comment]
you're welcome! thanks for the feedback and using centreon-plugins.
