### ISSUE TITLE
Uptime of 0 leads to empty output

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#1846]
Hi,

Uptime mode leads to following output :
`WARNING: System uptime is:  | 'uptime'=0s;1800:;;0;`

When :
```
#  snmpwalk (...) .1.3.6.1.2.1.25.1.1.0
.1.3.6.1.2.1.25.1.1.0 = Timeticks: (0) 0:00:00.00
```

I face issues on some devices with SNMP hanging and returning this, this is why I had time to investigate this.

I wonder `centreon::plugins::misc::change_seconds` could be the culprit ?
I verified, `$value` is not empty, it's equal to `0`.
https://github.com/centreon/centreon-plugins/blob/9bed462fdd6dd238f1cbad094b2745c03cfc1f37/snmp_standard/mode/uptime.pm#L140

Thx 👍

**Comment by garnier-quentin** [comment]
It's fixed!

**Comment by UrBnW** [comment]
And it works, many thx 👍

**Comment by UrBnW** [comment]
Do you think it could be relevant to return `UNKNOWN` when uptime is 0 ?
Would help to have this return code on such devices where SNMP agent hangs.
Thx !

**Comment by garnier-quentin** [comment]
Maybe a warning you can raise.

**Comment by UrBnW** [comment]
Mmmh I already raise WARNING for values < 1800 seconds.
In terms of threshold options we have :
```
    --warning
            Threshold warning in seconds.
    --critical
            Threshold critical in seconds.
```
I'm not sure a `--unknown` option would make sense.

**Comment by UrBnW** [comment]
Same issue when `$disant_time` returns 0 in time (ntp) mode on such devices :
https://github.com/centreon/centreon-plugins/blob/dc74f419888a2bddf67ca5572a81942bb05e6a94/snmp_standard/mode/ntp.pm#L116

**Comment by UrBnW** [comment]
Same issue when `$disant_time` returns 0 in time (ntp) mode on such devices :
https://github.com/centreon/centreon-plugins/blob/dc74f419888a2bddf67ca5572a81942bb05e6a94/snmp_standard/mode/ntp.pm#L116

It then produces such output :
`CRITICAL: Time offset -1581603667 second(s): Local Time : 1970-01-01T00:00:00 (+0000)`

`UNKNOWN` may perhaps be more relevant here.

**Comment by garnier-quentin** [comment]
you can't have unknown for threshold metrics.
