### ISSUE TITLE
[network::paloalto::snmp::plugin] - new mode vsys sessions: add the possibility to monitor sessions for vsys

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1849]
It should be nice if on Palo Alto firewalls to have the possibility to monitor the session informations not only globally, but for vsys:
http://www.circitor.fr/Mibs/Html/P/PAN-COMMON-MIB.php

SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.5 = INTEGER: 5
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.6 = INTEGER: 6
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.7 = INTEGER: 7
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.8 = INTEGER: 8
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.1.9 = INTEGER: 9
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.1 = STRING: "vsys1"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.2 = STRING: "vsys2"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.3 = STRING: "vsys3"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.4 = STRING: "vsys4"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.5 = STRING: "vsys5"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.6 = STRING: "vsys6"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.7 = STRING: "vsys7"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.8 = STRING: "vsys8"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.2.9 = STRING: "vsys9"
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.1 = INTEGER: 2
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.2 = INTEGER: 4
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.3 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.4 = INTEGER: 6
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.5 = INTEGER: 20
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.6 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.7 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.8 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.3.9 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.1 = INTEGER: 25439
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.2 = INTEGER: 6822
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.3 = INTEGER: 3646
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.4 = INTEGER: 6519
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.5 = INTEGER: 12205
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.6 = INTEGER: 422
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.7 = INTEGER: 991
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.8 = INTEGER: 464
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.4.9 = INTEGER: 92
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.1 = INTEGER: 1000000
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.2 = INTEGER: 150000
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.3 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.4 = INTEGER: 100000
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.5 = INTEGER: 60000
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.6 = INTEGER: 200000
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.7 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.8 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.5.9 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.1 = INTEGER: 687
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.2 = INTEGER: 279
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.3 = INTEGER: 47
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.4 = INTEGER: 90
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.5 = INTEGER: 270
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.6 = INTEGER: 1
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.7 = INTEGER: 1
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.8 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.6.9 = INTEGER: 1
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.1 = INTEGER: 100
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.2 = INTEGER: 63
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.3 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.4 = INTEGER: 12
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.5 = INTEGER: 17
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.6 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.7 = INTEGER: 13
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.8 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7.9 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.1 = INTEGER: 15
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.2 = INTEGER: 4
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.3 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.4 = INTEGER: 32
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.5 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.6 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.7 = INTEGER: 1
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.8 = INTEGER: 0
SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.8.9 = INTEGER: 0

**Comment by Sims24** [comment]
Hi @joschi99 

You can give a try to this branch https://github.com/centreon/centreon-plugins/tree/(enh)plugin-Palo-Alto-SNMP . 

Actually pending validation but evertyhing's ok I guess.

**Comment by joschi99** [comment]
Hi @Sims24,
I have done some test and the new mode seem's working fine. Maybe you can add a filter for vsys?
