### ISSUE TITLE
[os::windows::snmp::plugin] --mode=cpu : return cores or logical processors

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1854]
Hi,
I have several physical hosts on Windows 2016 Standard OS
Some of them are CPU "Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz" like this:
![centreon_host2](https://user-images.githubusercontent.com/8720203/74677673-42383180-51b9-11ea-809a-08be33325515.png)
=> Host1 :  OK: **64 CPU**(s) average usage is 0.02 %

Others are CPU "Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz" like this:
![centreon_host1](https://user-images.githubusercontent.com/8720203/74677597-13ba5680-51b9-11ea-815e-d35728a799a5.png)
=> Host2 :  OK: **36 CPU**(s) average usage is 3.11 %

I use this command for all of them:
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=cpu --hostname=X.X.X.X --snmp-version='2c' --snmp-community='public' --snmp-timeout=10 --warning-average='97' --critical-average='99' 

release of plugin: centreon-plugin-Operatingsystems-Windows-Snmp-20190704-123459
I can send you a full snmpwalk of each host in MP if needed.

Have you got any idea aobout this difference?
PS: a centreon-pack update is available but I need doing somes tests before upgrade pack to avoid errors in monitoring.

Thanks.

**Comment by garnier-quentin** [comment]
You can send me the snmpwalk.

**Comment by cmeschin** [comment]
Done.

**Comment by garnier-quentin** [comment]
I don't know. But the plugin returns good values for: HOST-RESOURCES-MIB::hrProcessorLoad

**Comment by cmeschin** [comment]
Hi,
Hosts are finally very different on hardware and software.
Windows OS templated by Dell on hosts who returns cores cpu instead of logical processors.

I don't search more.
Thanks for your time.
Kind regards.
