### ISSUE TITLE
plugin=database::oracle::plugin work on shell as centreon-engine but not on web

### ISSUE THREAD

**Issue by lg-infocom94** [centreon/centreon-plugins#1855]
Hi, 

I have the same issue as https://github.com/centreon/centreon-plugins/issues/1787
I follow all indications and it's still doesn't working on web.
Anyone have an idea ?

Thank's a lot in advance

**Comment by garnier-quentin** [comment]
I think your dbd oracle is installed in root directory. Have you tried with centreon-engine user on your poller ?

**Comment by lg-infocom94** [comment]
When i type this command with the user centreon-engine, i get this result

-bash-4.2$ /usr/lib/centreon/centreon-plugins/centreon_plugins.pl** --plugin=database::oracle::plugin --mode=tnsping --hostname=A.B.C.D --sid=SISXXX --port=1521
OK: Connection established to listener 'SISXXX' | 

For me it's working in commande line, but in the web interface i get this message
**CRITICAL: Cannot connect: (no error string)**

What do you mean by saying "I think your dbd oracle is installed in root directory", do you mean DBD::Oracle ?

**Comment by garnier-quentin** [comment]
Yes i mean DBD Oracle.

**Comment by jcvd94** [comment]
Hello,
i encounter a similar problem, at the difference that this command works under root, but not under centreon-engine :

bash-4.2$ /usr/lib/centreon/plugins/centreon_plugins.pl --plugin database::oracle::plugin --mode=tnsping --hostname=XXX --port=1548 --sid=XXX
CRITICAL: Cannot connect: (no error string) |

i followed this tutorial for Oracle client setup : https://pixelabs.fr/oracle-client-19c-installation-sous-centos7-centreon/

And the same, not working better under WUI.

if garnier-quentin could help :)
remote contreol session possible 👍 

Thanks by advance !
