### ISSUE TITLE
Bug in plugin templates for NetApp SSH module

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-plugins#1858]
Commands for this plugin have bugs as following: 

Original in rpm plugins: 

`$CENTREONPLUGINS$/centreon_paloalto_ssh.pl --plugin=network::paloalto::ssh::plugin --mode=environment --hostname='$HOSTADDRESS$' --ssh-option='-l=$_HOSTSSHUSERNAME$' $_HOSTSSHEXTRAOPTIONS$ --component='$_SERVICECOMPONENT$' $_SERVICEEXTRAOPTIONS$ 
`

Must be changed to: 

`$CENTREONPLUGINS$/centreon_paloalto_ssh.pl --plugin=network::paloalto::ssh::plugin --mode=environment --hostname='$HOSTADDRESS$' --ssh-option='-l $_HOSTSSHUSERNAME$ $_HOSTSSHEXTRAOPTIONS$' --component='$_SERVICECOMPONENT$' $_SERVICEEXTRAOPTIONS$
 `

Changes are: 
  * remove = sign from front of the $_HOSTSSHUSERNAME$
  * move the "'" from after $_HOSTSSHUSERNAME$ to after $_HOSTSSHEXTRAOPTIONS$

This is present in all PaloAlto-SSH command definition at least in centreon-plugin-Network-Firewalls-Paloalto-Standard-Ssh-20200204-093915.el6.noarch

**Comment by garnier-quentin** [comment]
That syntax should work:
```
$CENTREONPLUGINS$/centreon_paloalto_ssh.pl --plugin=network::paloalto::ssh::plugin --mode=environment --hostname='$HOSTADDRESS$' --ssh-option='-l=$_HOSTSSHUSERNAME$' $_HOSTSSHEXTRAOPTIONS$ --component='$_SERVICECOMPONENT$' $_SERVICEEXTRAOPTIONS$
```

**Comment by garnier-quentin** [comment]
I have updated the plugin with new ssh backend.
