### ISSUE TITLE
Problem monitoring PaloAlto using SSH

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-plugins#1859]
The following occurs in centreon-plugin-Network-Firewalls-Paloalto-Standard-Ssh-20200204-093915.el6.noarch

`UNKNOWN: Undefined subroutine &network::paloalto::ssh::mode::system::md5_hex called at /usr/lib/centreon/plugins/centreon_paloalto_ssh.pl line 6590.`

With the following call:

`/usr/lib/centreon/plugins/centreon_paloalto_ssh.pl --plugin=network::paloalto::ssh::plugin --mode=system --hostname='10.170.240.10' --ssh-option='-l centreon -i /var/lib/centreon-engine/.ssh/paloalto_monitoring -o StrictHostKeyChecking\\=no' --warning-status='' --critical-status='%{oper_mode} !~ /normal/i' --warning-av-update='' --critical-av-update='' --warning-threat-update='' --critical-threat-update=''`

**Comment by garnier-quentin** [comment]
thanks. it's fixed. last package will available in unstable
