### ISSUE TITLE
[apps::protocols::ldap::plugin] mode search - invalid perfdata

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#186]
Hi,
the perfdata of this mode return only metric time and not number of results.
The search mode return the number matching criterias.
an exemple of plugin return:
perl /usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::ldap::plugin --mode=search --hostname='x.x.x.x' --username='xxx' --password='xxx' --search-base='dc=domain,dc=fr' --search-filter='(&(samAccountName=test)(lockoutTime=0))' --critical=1:
CRITICAL: Number of results returned: 0 | 'time'=0.013s;;1:;;

regards,
Cedric Meschin

**Comment by garnier-quentin** [comment]
If i understand, you want the number of rows in perfdata ?

**Comment by cmeschin** [comment]
Yes because the metric time (in seconds) makes no sense with thresholds in number of recordings.

**Comment by garnier-quentin** [comment]
I'm dumb :) Could you test it ?

**Comment by cmeschin** [comment]
it's ok.
CRITICAL: Number of results returned: 0 | 'time'=0.013s;;;0; 'entries'=0;;1:;0;
thank you.

**Comment by garnier-quentin** [comment]
Thanks for your feedback.
