### ISSUE TITLE
[apps::vmware::connector::plugin] - Unknown method name 'statuscluster'

### ISSUE THREAD

**Issue by soulearth** [centreon/centreon-plugins#1860]
Hi,

I would use the Vmware check status-cluster mode but I have a error.

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=192.168.YYY.XXX --mode=status-cluster --cluster-name=myNameCluster
UNKNOWN: Unknown method name 'statuscluster' |

The other mode of apps::vmware::connector::plugin work very well.

I use the last stable version.
Thank you for your help.
Bests regards.

**Comment by garnier-quentin** [comment]
That mode doesn't exist. you can list it with --list-mode option.

**Comment by soulearth** [comment]
I know.

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=192.168.YYY.XX --list-mode 

I have in the list:
 stat-connectors
   **status-cluster**
   status-host
   status-vm

**Comment by garnier-quentin** [comment]
My bad :) You need to update your centreon vmware with last version.

**Comment by soulearth** [comment]
I run : 
> git pull
> ./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=192.168.YYY.XX --list-mode

I have always : 
stat-connectors
   **status-cluster**
   status-host
   status-vm
   swap-host

Bests regards

**Comment by garnier-quentin** [comment]
I mean the vmware daemon (not the plugin).

**Comment by soulearth** [comment]
OK. The update add or remove the function ?

**Comment by garnier-quentin** [comment]
Yes. it should (but i don't remember if the last version is packaged).

**Comment by soulearth** [comment]
I use a recent version : 
centreon-plugin-Virtualization-VMWare-daemon.noarch  3.0.3-20190704131142.el7.centos 

What version is required?

**Comment by garnier-quentin** [comment]
version 3.1.x

**Comment by soulearth** [comment]
Ok. thank you.

**Comment by soulearth** [comment]
centreon-plugin-Virtualization-VMWare-daemon.noarch 3.0.3-20190704131142.el7.centos     @centreon-standard-noarch

Just one remark.
We should put version 3.1 on centreon repositories, because it's update is very difficult without.

Bests regards
