### ISSUE TITLE
PaloAlto IPSEC check not correct

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-plugins#1861]
https://github.com/centreon/centreon-plugins/blob/2e23c7e72a669e9ccabed9b742f64762f3abfa89/network/paloalto/ssh/mode/vpn.pm#L106

This command call should be changed to as such:

```
cli command: show vpn ike-sa
```
successfull expectation - all tunnels within status="success" stanza are OK

```
admin.xxx@HOSTNAME(active)> show vpn ike-sa

<response status="success"><result>

  <entry>

    <name>Proxy-Cloud-GW</name>

    <created>Feb.18 15:03:01</created>

    <expires>Feb.19 04:23:01</expires>

    <gwid>1</gwid>

    <role>Init</role>

    <mode>Main</mode>

    <algo>PSK/ DH5/ AES/ MD5</algo>

  </entry>
  <entry>
....
 </entry>
 </response>
```

unsuccessfull expected output - these tunnels are in NO OK state - tunnel(s) are configured, but not connected.

```
admin.xxx@HOSTNAME(passive)> show vpn ike-sa

There is no IKEv1 phase-1 SA found.

There is no IKEv1 phase-2 SA found.

There is no IKEv2 SA found. 
```

**Comment by garnier-quentin** [comment]
I have done a mode ipsec that should do it well.
