### ISSUE TITLE
[apps::protocols::http::plugin] - mode=response: Doesn't work on CentOS7

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1865]
Hi,
I use this command below to check simply URL's responding:
`/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=X.X.X.X --proto='https' --port='443' --urlpath='' --proxyurl=''  --username='' --password='' --warning='5' --critical='12'  --filter-perfdata='time' --timeout='30' --debug --verbose`

> CRITICAL: 500 Can't connect to X.X.X.X:443 |
> ======> request send
> GET https://X.X.X.X:443
> User-Agent: centreon::plugins::backend::http::useragent
> 
> ======> response done
> 500 Can't connect to X.X.X.X:443
> Content-Type: text/plain
> Client-Date: Wed, 19 Feb 2020 15:05:02 GMT
> Client-Warning: Internal response
> 
> Can't connect to X.X.X.X:443
> 

Release used is the last centreon-plugin-Applications-Protocol-Http.noarch 0:20200204-093915.el7.centos.
The same command on same release on CentOS6 works correctly.
> OK: Response time 0.503s

For more information it's on HP Blade Chassis.
to workarround, I use now the centreon_hp_bladechassis.pl with hardware mode :)

If you have an idea.
Kind regards

**Comment by garnier-quentin** [comment]
Have you tried with the curl backend ?
Install:
```
yum instalm perl-Net-Curl
```

Options:
```
--http-backend=curl --curl-opt="CURLOPT_SSL_VERIFYPEER => 0"
```

**Comment by cmeschin** [comment]
Hi Quentin.
Thanks. It works.

King regards.
