### ISSUE TITLE
os::linux:snmp::plugin --mode memory show negative value

### ISSUE THREAD

**Issue by kbruno89** [centreon/centreon-plugins#1867]
Hi,

After update SNMP package on CentOS7, my Nagios show alert with memory issue.

CRITICAL: Ram Total: 1.95 GB, Used (-buffers/cache): -421429248.00 B (-20.11%), Buffer: 2.03 MB, Cached: 647.32 MB, Shared: 25.71 MB

**Comment by garnier-quentin** [comment]
Please use --autodetect-redhat or --redhat option

**Comment by kbruno89** [comment]
Return:

Unknown option: redhat at /usr/local/nagios/libexec/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.

Unknown option: autodetect-redhat at /usr/local/nagios/libexec/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by garnier-quentin** [comment]
please get the last version
