### ISSUE TITLE
Azure plugin over https proxy

### ISSUE THREAD

**Issue by laltroale** [centreon/centreon-plugins#1868]
Hi all,
does the Azure plugin work over https proxy?
We have tryed to set the proxy via env properties and command property but we received this error message:

 ./centreon_plugins.pl --plugin cloud::azure::management::monitor::plugin --custommode api --mode discovery --subscription **** --tenant *** --client-id *** --client-secret *** --proxyurl https://proxyhost:8080
UNKNOWN: 501 Protocol scheme 'connect' is not supported

**Comment by garnier-quentin** [comment]
please install: 
```
# yum install perl-Net-Curl
```

And use option:
```
--http-backend=curl
```
