### ISSUE TITLE
Supermicro IPMI monitoring

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1869]
It should be very nice to monitor Supermicro Server IPMI

Some additional information could be here:
https://www.supermicro.com/en/solutions/management-software/bmc-resources

SNMP walk (incomplete, always fails with error "Error in packet."
[supermicro.zip](https://github.com/centreon/centreon-plugins/files/4252195/supermicro.zip)

MIB
[SMT_MIB.zip](https://github.com/centreon/centreon-plugins/files/4252204/SMT_MIB.zip)

For any further information please let me know. Thanks

**Comment by garnier-quentin** [comment]
In fact, i will do a plugin for ATEN BMC controller. Supermicro uses that card. I can do a mode for sensors.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by joschi99** [comment]
Seem's working, thanks

![image](https://user-images.githubusercontent.com/6400595/75552080-cd28ef80-5a35-11ea-9390-c15808dde41d.png)

**Comment by garnier-quentin** [comment]
thanks for the feedback
