### ISSUE TITLE
[apps::protocols::ldap::plugin] mode search - Sizelimit exceeded

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#187]
Hi,
I want to know how many account locked in my domain.
I use this syntax:
perl /usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::ldap::plugin --mode=search --hostname='X.X.X.X' --username='xxx' --password='xxx' --search-base='dc=domain,dc=fr' --search-filter='(&(samAccountName=*)(!(lockoutTime=0)))'
The result is:
UNKNOWN: Search operation error: Sizelimit exceeded

if I test with this filter:
 --search-filter='(&(samAccountName=Cpt*)(!(lockoutTime=0)))'
the result is:
OK: Number of results returned: 35 | 'time'=0.065s;;;0; 'entries'=35;;;0;

What is exactly the "Sizelimit exceeded" error? The plugin execution during less than 5 seconds; it's not a timeout.
Options --verbose and --debug don't display more informations :(

regards,

**Comment by garnier-quentin** [comment]
There is a limit in search for ldap. I think you need to limit the browsing. Maybe i need to add an option to add the limit. Don't really know.

**Comment by cmeschin** [comment]
OK. 
with filter on spécific "OU", it's work.
It's only for test. I have a similar script in powershell directly execute on the AD server with nsclient.
Thanks.

**Comment by garnier-quentin** [comment]
Otherwise, you could also use following option: --ldap-search-options='sizelimit=100'

**Comment by george-vieira** [comment]
For the sake of monitoring, you can write limit rules so your monitoring is allowed but all other requests are limited. I do this on our master:

limits dn.exact="uid=nagios,ou=people,ou=company=,dc=net" size=unlimited time=unlimited

works fo rme
