### ISSUE TITLE
Plugin storage::netapp::restapi::plugin output

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#1870]
Hello, 

I am using the plugin storage::netapp::restapi::plugin to check a netapp server and it is working fine. but the check output is a little messy when there is many volumes on critical. 
Is it possible to edit the output so that we get status on by line ?

This is an example of what i got now: 
![image](https://user-images.githubusercontent.com/28105870/75339475-e7759880-5890-11ea-8b57-954e098fd7bc.png)

What i need is to have results like :
CRITICAL: 
Volume 'veeamProxies_243' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.45 GB (5.13%)
Volume 'veeamProxies_239' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.43 GB (5.13%)
Volume 'veeamProxies_247' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.43 GB (5.13%)
Volume 'veeamProxies_245' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.35 GB (5.13%)

Thank you for your help.

Regards

**Comment by garnier-quentin** [comment]
You can check volume by volume. Or fix some alerts ;)
You cannot get short output on mulitple lines.

**Comment by saharawolf** [comment]
Hi Garnier thanks for you reply. 

Yes the alerts are not permanents. 
The option --change-short-output can not help ? 

regards

**Comment by garnier-quentin** [comment]
You can change the output for critical yes. And you'll have information in verbose mode.

**Comment by saharawolf** [comment]
yes i did that : --change-short-output='- ~ br/'
But br/ is juste replacing ' - ' not getting back to line and it is replaced only on the first result 

CRITICAL: Volume 'veeamProxies_243' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.45 GB (5.13%)  **br/**Volume 'veeamProxies_239' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.43 GB (5.13%) - Volume 'veeamProxies_247' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.43 GB (5.13%) - Volume 'veeamProxies_245' Total: 14.82 TB Used: 14.06 TB (94.87%) Free: 778.35 GB (5.13%) -

**Comment by garnier-quentin** [comment]
you need to use modifier 'g'.

**Comment by saharawolf** [comment]
Sorry Quentin, i just do not get how to use it.

**Comment by saharawolf** [comment]
ok got it to be replaced on all results with
--change-short-output='- ~br/~g'
but still not returning to line

**Comment by saharawolf** [comment]
replaced br/ with \n , it works on cli but not on UI.

**Comment by garnier-quentin** [comment]
That's why i have tried with br. But maybe the interface strip html tags. So we can't do more.
