### ISSUE TITLE
check_centreon_snmp_remote_storage + maxMsgSize of 10000

### ISSUE THREAD

**Issue by MiStErLu** [centreon/centreon-plugins#1873]
Hi,

    I got a bug with this plugins : check_centreon_snmp_remote_storage, the output return failed, i got this message : SNMP TABLE ERROR : The message size exceeded the buffer maxMsgSize of 10000.

    I can modify the line 202 
         $session->max_msg_size(10000); => $session->max_msg_size(50000); and it's work.

    It is possible to add an option to set de max_msg_size ? I don't want to modify this settings after an upgrade ?

Best regards,
MiStErLu.

**Comment by garnier-quentin** [comment]
It's a deprecated plugin. Please use the master branch of centreon-plugins.
