### ISSUE TITLE
[apps::protocols::http::plugin] mode json-content - how displays somes values

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1876]
Hi,
I try to use this plugin to catch errors returned by http request in json format.
this is my json file:
![centreon_json_return](https://user-images.githubusercontent.com/8720203/75690709-9b1cc500-5ca3-11ea-87ac-6ba29b4723d1.png)

I want catch last:status values which are different of "success" and return only critical data with name, ip and last:end values.

I test this command:
`/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=json-content --hostname=myHostName --proto='https' --port=443 --urlpath='/nodes.json' --header='Content-Type: application/json' --data='' --lookup='$..last..status' --threshold-value='count' --format-ok='Toutes les sauvegardes sont OK.' --format-warning='Certaines sauvegardes sont incorrectes %{count}: %{values}' --format-critical='Certaines sauvegardes sont en erreur: %{values_critical}' --warning-numeric='' --critical-numeric='1' --warning-string='' --critical-string='^(?!(success)$)' --filter-perfdata= --critical-time=1 --critical-status='%{http_code} >= 500'`

> CRITICAL: Certaines sauvegardes sont en erreur: 563

How can I do this and is it possible with this plugin?
It seems to be apparently same of issue #636
Kind regards.

**Comment by garnier-quentin** [comment]
It's the same issue yes. the mode cannot do that.
