### ISSUE TITLE
[network::paloalto::ssh::plugin] - new mode to monitor licenses

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1879]
Paloalto firewalls has different licenses on board. It should be great to monitor the different licenses to know if some license i expired o will be expire soon.

Using the CLI license can be shown:
```
user@PA-5020-Primary(active)> request license info

Current GMT Date: March 05, 2020

License entry:
Feature: WildFire License
Description: WildFire signature feed, integrated WildFire logs, WildFire API
Serial: 0011C10XXXX
Issued: May 16, 2019
Expires: May 20, 2020
Expired?: no

License entry:
Feature: Standard
Description: 10 x 5 phone support; repair and replace hardware service
Serial: 0011C10XXXX
Issued: May 16, 2019
Expires: May 20, 2020
Expired?: no

License entry:
Feature: Threat Prevention
Description: Threat Prevention
Serial: 0011C10XXXX
Issued: May 16, 2019
Expires: May 20, 2020
Expired?: no

License entry:
Feature: GlobalProtect Gateway
Description: GlobalProtect Gateway License
Serial: 0011C10XXXX
Issued: May 16, 2019
Expires: May 20, 2020
Expired?: no

License entry:
Feature: GlobalProtect Portal
Description: GlobalProtect Portal License
Serial: 0011C10XXXX
Issued: May 20, 2015
Expires: Never
Expired?: no

License entry:
Feature: PAN-DB URL Filtering
Description: Palo Alto Networks URL Filtering License
Serial: 0011C10XXXX
Issued: May 16, 2019
Expires: May 20, 2020
Expired?: no

```

**Comment by garnier-quentin** [comment]
could you provide that output in XML ?
```
set cli op-command-xml-output on
```

**Comment by joschi99** [comment]
`<response status=';success';><result><licenses><entry><feature>Logging Service</feature><description>Device Logging Service</description><serial>0011C104XXX</serial><issued>April 24, 2020</issued><expires>January 30, 2022</expires><expired>no</expired><custom><_Log_Storage_TB>1</_Log_Storage_TB></custom><authcode></authcode></entry><entry><feature>WildFire License</feature><description>WildFire signature feed, integrated WildFire logs, WildFire API</description><serial>0011C104XXX</serial><issued>May 16, 2019</issued><expires>May 20, 2020</expires><expired>no</expired><authcode></authcode></entry><entry><feature>Standard</feature><description>10 x 5 phone support; repair and replace hardware service</description><serial>0011C104XXX</serial><issued>May 16, 2019</issued><expires>May 20, 2020</expires><expired>no</expired><authcode></authcode></entry><entry><feature>Threat Prevention</feature><description>Threat Prevention</description><serial>0011C104XXX</serial><issued>May 16, 2019</issued><expires>May 20, 2020</expires><expired>no</expired><authcode></authcode></entry><entry><feature>GlobalProtect Gateway</feature><description>GlobalProtect Gateway License</description><serial>0011C104XXX</serial><issued>May 16, 2019</issued><expires>May 20, 2020</expires><expired>no</expired><authcode></authcode></entry><entry><feature>GlobalProtect Portal</feature><description>GlobalProtect Portal License</description><serial>0011C104XXX</serial><issued>May 20, 2015</issued><expires>Never</expires><expired>no</expired><authcode></authcode></entry><entry><feature>PAN-DB URL Filtering</feature><description>Palo Alto Networks URL Filtering License</description><serial>0011C104XXX</serial><issued>May 16, 2019</issued><expires>May 20, 2020</expires><expired>no</expired><authcode></authcode></entry></licenses></result></response>`

**Comment by garnier-quentin** [comment]
You can test it.
