### ISSUE TITLE
[Plugin] network::cisco::asa::plugin Uptime

### ISSUE THREAD

**Issue by wilfriedcomte** [centreon/centreon-plugins#188]
Hi,

Its possible to add uptime check?
for ASA and for all in general :)

Regards

**Comment by Sims24** [comment]
Hi Wilfried, 

Could you walk these OIDs :

**Comment by wilfriedcomte** [comment]
Hi,

for .1.3.6.1.2.1.25.1.1.0
HOST-RESOURCES-MIB::hrSystemUptime.0 = No Such Object available on this agent at this OID

for .1.3.6.1.2.1.1.3.0
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (357444700) 41 days, 8:54:07.00
