### ISSUE TITLE
[os::linux::snmp::plugin] - --mode memory | add the possibility options to change perfadata bytes for gb or mb

### ISSUE THREAD

**Issue by hupefranz** [centreon/centreon-plugins#1881]
Hi guys, i'm using centreon plugin to monitor my servers Centos/Debian with protocol SNMP.
```
[root@nagios01 libexec]# ./centreon_plugins.pl --plugin os::linux::snmp::plugin --mode memory --hostname 10.10.10.123 --snmp-community public --snmp-version v2c --warning-usage='90' --critical-usage='95'
```
I don't like theshoold in bytes. Would it be possible to add an option to convert them to GB or MB?

OK: Ram Total: 1.96 GB Used (-buffers/cache): 979.38 MB (48.82%) Free: 1.00 GB (51.18%), Buffer: 62.98 MB, Cached: 245.67 MB, Shared: 0.00 B | '**used'=1026953216B**;;;0;2103459840 '**free'=1076506624B;;**;0;2103459840 'used_prct'=48.82%;0:90;0:95;0;100 **'buffer'=66035712B;;;0;** **'cached'=257605632B;;;0;** '**shared'=0B;;;0**

**Comment by Sims24** [comment]
Hell @hupefranz 

Yeah, of course :) 

Use the change-perfdata option, example: 

`--change-perfdata='(used|free|buffer|cached|shared),,scale(MB)`

You have several example in the help of the plugin:

    --change-perfdata --extend-perfdata
            Change or extend perfdata. Syntax:
            --extend-perfdata=searchlabel,newlabel,target[,[newuom],[min],[m
            ax]]

```
            Common examples:

                Change storage free perfdata in used:
                --change-perfdata=free,used,invert()

                Change storage free perfdata in used:
                --change-perfdata=used,free,invert()

                Scale traffic values automaticaly:
                --change-perfdata=traffic,,scale(auto)

                Scale traffic values in Mbps:
                --change-perfdata=traffic_in,,scale(Mbps),mbps

                Change traffic values in percent:
                --change-perfdata=traffic_in,,percent()

```

**Comment by hupefranz** [comment]
Thank you!  It work for me.
