### ISSUE TITLE
[network::paloalto::ssh::mode::system] Invalid offset

### ISSUE THREAD

**Issue by thibaults-centreon** [centreon/centreon-plugins#1885]
In https://github.com/centreon/centreon-plugins/blob/5cd0e80f407996a1ebc886d6f43e9a2b568f7eba/network/paloalto/ssh/mode/system.pm#L138
(lines 138 to 142)

The timezone parsing mechanism does not cover all cases. For a PA device configured with the CST (Central America Time) timezone, the plugin would return an "Invalid offset" error.

**Comment by garnier-quentin** [comment]
When i read datetime documentation:
```
short_name_for_datetime( $dt )
Given a DateTime object, this method returns the ``short name'' for the current observance and rule this datetime is in. These are names like ``EST'', ``GMT'', etc.

It is strongly recommended that you do not rely on these names for anything other than display. These names are not official, and many of them are simply the invention of the Olson database maintainers. Moreover, these names are not unique. For example, there is an ``EST'' at both -0500 and +1000/+1100.
```

It will be an issue. I cannot use that. I add a timezone option.
