### ISSUE TITLE
[storage::emc::vplex::restapi::plugin] mode=cluster-devices - HTTP 404 Not found

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#1887]
Hi,
I try to use plugin in subject but not work with a 404 result.

Here is the command line:
`/usr/lib/centreon/plugins/centreon_emc_vplex.pl --plugin=storage::emc::vplex::restapi::plugin --mode=cluster-devices --hostname='IP' --vplex-username='username' --vplex-password='Password'   --cluster='' --verbose --debug`

and the result:

> UNKNOWN: 404 Not Found |
======> request send
GET https://IPHost:443/vplex/clusters/*/devices/*
User-Agent: centreon::plugins::backend::http::useragent
Password: Password
Username: Username
======> response done
HTTP/1.1 404 Not Found
Date: Wed, 18 Mar 2020 10:11:08 GMT
Server: Apache-Coyote/1.1
Content-Type: application/json
Client-Date: Wed, 18 Mar 2020 10:11:08 GMT
Client-Peer: 10.33.2.171:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/ST=Massachusetts/L=Hopkinton/O=EMC/OU=EMC/CN=CKM00161701405/emailAddress=support@emc.com
Client-SSL-Cert-Subject: /C=US/ST=Massachusetts/O=EMC/OU=EMC/CN=VPlex Web Server: CKM00161701390/emailAddress=support@emc.com
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Warning: Peer certificate not verified
Client-Transfer-Encoding: chunked
Set-Cookie: JSESSIONID=D06FED651E38C36013F48DC7E5938077; Path=/vplex; Secure; HttpOnly
{
    "response": {
        "context": null,
        "message": null,
        "exception": "Invalid URI in GET request. Not one among context,command or attribute.",
        "custom-data": null
    }
}

And the result on browser
![centreon_vplex_clusters_devices](https://user-images.githubusercontent.com/8720203/76956441-5a17e800-6914-11ea-8134-f525404c7feb.png)

What kind of thing should be returned by this plugin?

Thanks.
Kind regards.

**Comment by garnier-quentin** [comment]
There is an star at the end of the request. Maybe you should provide the API doc of your vplex version.

**Comment by cmeschin** [comment]
I'm in vplex 6.1.
Here is the doc i've found: https://www.dellemc.com/en-us/collaterals/unauth/technical-guides-support-information/products/storage-3/docu43070.pdf.
in fact, I think this branch is simply empty in this version because haven't any children under "devices"

**Comment by garnier-quentin** [comment]
there is no devices. maybe you are right :)

**Comment by cmeschin** [comment]
ok. I don't try anymore for instant. Many other things to do right now.
Thanks.
