### ISSUE TITLE
[cloud::azure::management::recovery::plugin] Filter by id (or other fields other than friendlyName)

### ISSUE THREAD

**Issue by vmonegatto** [centreon/centreon-plugins#1890]
The plugin [cloud::azure::management::recovery::plugin] can only filter by name (In Azure, **friendlyName**) using the option `--filter-name` when the  `--mode=backup-items-status` is used.
It'd be useful if we could add additional filter capabilities to this plugin/mode. Example: `--mode=backup-items-status` could accept filtering by **id**, **containerName** or maybe **sourceResourceId**. The idea is to enable filtering out resources that have the same **friendlyName** but are in different **resourceGroups**, for example.

Example:
```
/usr/lib/centreon/plugins/centreon_azure_management_recovery_api.pl \
--plugin=cloud::azure::management::recovery::plugin \
--mode=backup-items-status \
--custommode='api' \
--vault-name='<omitted>' \
--resource-group='<omitted>' \
--subscription='<omitted>' \
--tenant='<omitted>' \
--client-id='<omitted>' \
--client-secret='<omitted>' 
--client-secret='<omitted>' 
--filter-id='<regexp>'  <---- New suggested filtering capability
```

**Comment by Sims24** [comment]
Yeah! Thanks, we will take a look and let you know :)
