### ISSUE TITLE
centreon_mongodb.pl : don't set port for "mongodb+srv" protocol

### ISSUE THREAD

**Issue by lkco** [centreon/centreon-plugins#1894]
Hi,
to check a mongodb cluster, there is a bug for "mongodb+srv" protocol. The port must not be specified 
could you fix this issue ?
La patch 
[mongo.txt](https://github.com/centreon/centreon-plugins/files/4369278/mongo.txt)

**Comment by garnier-quentin** [comment]
you can test it ?

**Comment by lkco** [comment]
it's OK for me. Thanks Quentin

**Comment by garnier-quentin** [comment]
thanks for the feedback!!
