### ISSUE TITLE
[database::mssql::plugin] mode sql-string

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#1896]
Hello,

I have this kind of result with an SQL request :

OK: '801' |

How can i use the parameters (printf-format, printf-value, other) to have this result :
OK: 'Nombre de sessions SKYPE : 801' | 'nb.sessions.skype'=801;;;0;

Thanks.

**Comment by Sims24** [comment]
Hi,

You have tu use the --format option. Like that I guess: 

--format="Nombre de sessions SKYPE: %s'

**Comment by ritouret** [comment]
Thank you Simon for your answer.

I have to use sql mode and not sql-string mode to get what i want.
