### ISSUE TITLE
Create NGINX Plus plugin

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon-plugins#1897]
## New plugins and modes
Get more statistic from NGINX Plus
https://docs.nginx.com/nginx/admin-guide/monitoring/live-activity-monitoring/

Relevant information:
HTTP Upstrem statistics: https://demo.nginx.com/#upstreams
- curl https://demo.nginx.com/api/6/http/upstreams

TCP/UDP Upstream statistics: https://demo.nginx.com/#tcp_upstreams
- curl https://demo.nginx.com/api/6/stream/upstreams

HTTP Zones statistics: https://demo.nginx.com/#server_zones
- curl https://demo.nginx.com/api/6/http/server_zones

TCP/UDP Zones statistics:
- curl https://demo.nginx.com/api/6/stream/server_zones

It's possible to get them with the "App-Protocol-HTTP-Json-Content", but is not the most user friendly.

**Comment by garnier-quentin** [comment]
A first version. We could add some stuffs in time.
