### ISSUE TITLE
[network] Interfaces unit issue ?

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#1900]
Hi,

With `network::juniper::srx`, `interfaces` mode, here's how perfdata looks like :
```
'packets_discard_in_ge-0/0/3'=0.00%;;;0;100
'packets_error_in_ge-0/0/3'=0.00%;;;0;100
'packets_discard_out_ge-0/0/3'=0.00%;;;0;100
'packets_error_out_ge-0/0/3'=0.00%;;;0;100
'fcs-errors_ge-0/0/3'=0;;;;
'packets_discard_in_ge-0/0/4'=0.00%;;;0;100
'packets_error_in_ge-0/0/4'=0.00%;;;0;100
'packets_discard_out_ge-0/0/4'=0.00%;;;0;100
'packets_error_out_ge-0/0/4'=0.00%;;;0;100
'fcs-errors_ge-0/0/4'=0;;;;
```

I'm concerned by `fcs-errors`, which does not have any unit.
Using `--use-new-perfdata`, we see that the counter is absolute : `interface.fcs.errors.count`.
Whereas then a percentage would have been expected.

With [MikroTik interfaces mode](https://github.com/centreon/centreon-plugins/blob/20200204/network/mikrotik/snmp/mode/interfaces.pm), all error counters have the `%` unit, or absolute with `--units-errors=absolute`.
The [Juniper SRX interfaces mode](https://github.com/centreon/centreon-plugins/blob/20200204/network/juniper/common/junos/mode/interfaces.pm) does not seem to apply the exact same method to compute the additional error counters, so I wonder...

While here, perhaps that the `fcs-errors` label could be renamed to something like  `packets_fcserror_in` / `interface.packets.in.fcserror.(count|percentage)`.

Many thx 👍

**Comment by garnier-quentin** [comment]
i don't understand. right now, for fcserrors it's only absolute. no %. You want to have '%' also ?

**Comment by UrBnW** [comment]
IMO, should be `%` by default.
As by default, `--units-errors` is `%`
The counter should be absolute only if we use `--units-errors=absolute`.
As for the other error types.

**Comment by garnier-quentin** [comment]
Ok i understand. But do you think frames and packets are the same ? (A count of frames received on a particular interface that are an integral number of octets in length but do not pass the FCS check).
Because if not, i don't have the total number of frames.

**Comment by UrBnW** [comment]
> Ok i understand. But do you think frames and packets are the same ?

Yes : https://stackoverflow.com/questions/31446777/difference-between-packets-and-frames
