### ISSUE TITLE
CENTREON STORMSHIELD SNMP PLUGIN

### ISSUE THREAD

**Issue by kevin06700** [centreon/centreon-plugins#1903]
HI !

When I use stormshield plugin command with file plugin.pm I have this error

UNKNOWN: Can't call method "new" without a package or object reference at /usr/lib/centreon/plugins/centreon/plugins/script.pm line 419.

Command 
/usr/lib/centreon/plugins/centreon_stormshield_snmp.pl --plugin=/usr/lib/centreon/plugins/network/stormshield/snmp/plugin.pm --hostname=$HOSTADRESS$ --snmp-version=v2c --snmp-community=public --mode=/usr/lib/centreon/plugins/network/stormshield/snmp/mode/vpnstatus.pm

Can you help me please ?

Thks

**Comment by garnier-quentin** [comment]
Please try that command:
```
/usr/lib/centreon/plugins/centreon_stormshield_snmp.pl --plugin=network::stormshield::snmp::plugin  --hostname=$HOSTADRESS$ --snmp-version=v2c --snmp-community=public --mode=vpn-status
```
