### ISSUE TITLE
netapp::snmp mode cache age et global status

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#1905]
Ces deux modes ne fonctionnent pas  pour les contrôles NetApp SNMP
SNMPWALK disponible sur demande

Version ONTAP 9.2

Options testées 

--snmp-force-getnext --subsetleef=1 --maxrepetitions=10 

# rpm -qa | grep -i netapp

centreon-plugin-Hardware-Storage-Netapp-Snmp-20200310-123131.el7.centos.noarch
centreon-plugin-Hardware-Storage-Netapp-Restapi-20200310-123131.el7.centos.noarch
centreon-pack-hardware-storage-netapp-snmp-3.1.14-1.el7.centos.noarch
centreon-pack-hardware-storage-netapp-restapi-3.1.1-1.el7.centos.noarch

 
CACHE AGE

 # snmpwalk -Cc -Obentu -v 2c -c xxxxxx X.X.XX. .3.6.1.4.1.789.1.2.2.23.0                              
snmp_build: unknown failuresnmpwalk: Error building ASN.1 representation (Can't build OID for variable)
 

GLOBAL STATUS

# snmpwalk -Cc -Obentu -v 2c -c xxxxxx X.X.XX. .1.3.6.1.4.1.789.1.5.7.1.0
enterprises.789.1.5.7.1.0 = No Such Object available on this agent at this OID

# snmpwalk -Cc -Obentu -v 2c -c xxxxxx X.X.XX. .1.3.6.1.4.1.789.1.5.7.2.0
enterprises.789.1.5.7.2.0 = No Such Object available on this agent at this OID

# snmpwalk -Cc -Obentu -v 2c -c xxxxxx X.X.XX. .1.3.6.1.4.1.789.1.2.2.4.0
enterprises.789.1.2.2.4.0 = No Such Object available on this agent at this OID

**Comment by Sims24** [comment]
Thanks, might be because you are monitoring a NetApp cluster. 

Please prefer RestAPI monitoring when targetting Ontap clusters.
