### ISSUE TITLE
centreon_oracle.pl − mode "sql" − Unknown: argument A alone at (eval 15) line 646

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon-plugins#1910]
Hi,

I have a service which use the "sql" mode of this plugin. It usually works fine (OK status) but today I had an alert, an UNKNOWN status with the message “argument A alone at (eval 15) line 646”. It then went back to OK :

![error_check_oracle](https://user-images.githubusercontent.com/38944475/77923237-70be2780-72a2-11ea-9220-7771ee29001b.png)

I asked the DBAs if there were anything which could explain this behavior but I’m still waiting their answer.

Anyway, do anybody already had this message or have any idea of what could’ve happened? 

I’ll tell you if I’m able to reproduce it but now I’ve absolutely no clue and I prefer to ask there first before eventually looking myself at the source.

Plugin version is from the package : "centreon-plugin-Applications-Databases-Oracle-20200204-093915" and Centreon version from the package : "centreon-web-19.04.10-2"

Please let me know if more information is needed.

Have a nice day.

**Comment by garnier-quentin** [comment]
Could you provide your command line please ?

**Comment by StefThomas** [comment]
I have "Unable to hide passwords in command" where I should find the command line… I need to reconstruct it manually (or temporarily leak the password). Don’t have much time now but I’ll try to do that within a few days.

**Comment by Sims24** [comment]
Timeout reached. 

@StefThomas , if you mange to provide the CLI, we could reopen the case. 

FYI, you can get the CLI from the database with the following query: 

- SELECT command_line FROM services WHERE command_line LIKE "%::oracle::%" AND enabled='1'; 

Thanks
