### ISSUE TITLE
Script centreon_stormshield_snmp.pl doesn't exist after install plugin in centreon 19.10.10

### ISSUE THREAD

**Issue by Stubing01** [centreon/centreon-plugins#1914]
Hello,

I recently installed Centreon 19.10.10 and it works well!
However, I've an issue with the stormshield plugin. After I've installed it, the script doesn't appear in /usr/lib/centreon/plugins/ like her commands has showed it and like each other plugins too.
I tryed to delete the plugin and reinstalled it, but it is still not working.
Can you help me please ?

**Comment by Sims24** [comment]
Hi @Stubing01 

could you please give us the output 

rpm -ql centreon-plugin-Network-Stormshield-Snmp 

Thanks

**Comment by Stubing01** [comment]
Hello Sims24,

Thanks for your interest.
This is the result of the command:

![2020-04-01 10_45_39-Centreon - IT   Network Monitoring](https://user-images.githubusercontent.com/62987004/78117861-746abf00-7406-11ea-80ed-a1925e8671bb.png)

**Comment by Sims24** [comment]
Please install it, the web UI installation only triggers the pack/template deployment. 

You have to install the plugin on your system. 

Tell me if everything is ok ;)

**Comment by Sims24** [comment]
Note: you can get the command to execute by clicking on the (?) icon here: 

![image](https://user-images.githubusercontent.com/12429463/78121983-6455de00-740c-11ea-9c7a-45338c784c6e.png)

**Comment by Stubing01** [comment]
outch! I'm sorry for that...
It is so easy to resolve. I Was probably not awaked. I thought the only information I had, was this below:
![2020-04-01 11_44_46-Centreon - IT   Network Monitoring](https://user-images.githubusercontent.com/62987004/78124201-a59bbd00-740f-11ea-9aba-4b9dc12b1db4.png)

It works! I thank you for your help
