### ISSUE TITLE
Oracle - Rmanbackup mode - Seems to not support Level 0 in the backup

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon-plugins#1916]
## Bug/Question

Hello Team.

It's seems that we do not consider backup Level 0 as FULL.
There are 2 kinds of "Full" on Rman. There is a FULL strictly speaking which can do that and Level 0 which is full but which supports incrementals.

And when we tried to monitor a Level 0 backup the plugin return the following things :
`Critical: Rman "My backup" backup never executed.
`
I follow you information by mail. thanks.

**Comment by garnier-quentin** [comment]
```
=item B<--incremental-level>

Please use the following option if your using incremental level 0 for full backup.
```
