### ISSUE TITLE
SNMP plugin OS Linux Monitoring Process

### ISSUE THREAD

**Issue by pianogen** [centreon/centreon-plugins#1918]
Hello

I stuck atm on a problem.

I want to monitor through the plugin if a process is running or not. 
I thought I can do that with the mode processcount.

With this mode I can query the process successfully and it returns me the count of the running process.
But I cannot set the warning or critical threshold to a minimal count that have to run.
I only can set the maximum count but not the minimal.

Do you plan to implement this feature in a next release?

Best Regards

**Comment by Sims24** [comment]
HI @pianogen , 

Actually you can, just you the standard syntax, e.g --critical=1: and it shoud be ok ;)  This way, you will get an alert when 0 process are running. 

Thanks
