### ISSUE TITLE
[apps::vmware::connector::plugin] memory-vm, vm powered off , problem UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...) |

### ISSUE THREAD

**Issue by bastiencha** [centreon/centreon-plugins#1919]
Hi,

I want to check memory vm. I have vm powered on and vm powered off in my esx. 

I do 
`/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container='***' --mode='memory-vm' --vm-hostname='***' --warning-consumed=90 --critical-consumed=95`

And I have

`UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...) |`

How can I do ?

Thanks

**Comment by garnier-quentin** [comment]
You can provide the result of the mode 'time-host' ?

**Comment by bastiencha** [comment]
`UNKNOWN: Host '***' : status disconnected | 'offset_esxs1'=2939.46s;;;; 'offset_esxs2'=2456.16s;;;;`

**Comment by garnier-quentin** [comment]
As you can see, you have a issue of time sync with your esx.

**Comment by bastiencha** [comment]
When I try for a vm powered on in the same esx : 

`/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container='***' --mode='memory-vm' --vm-hostname='***'`

I have : 

`OK: Virtual machine '****' : [connection state connected][power state poweredOn] - Memory consumed Usage Total: 6.00 GB Used: 6.00 GB (99.99%) Free: 524.00 KB (0.01%) - Memory active Usage Total: 6.00 GB Used: 266.24 MB (4.33%) Free: 5.74 GB (95.67%) - Memory overhead: 59.24 MB - Memory ballooning: 0.00 B - Memory shared: 536.00 KB | 'used'=6441914368B;;;0;6442450944 'used'=279171072B;;;0;6442450944 'overhead'=62117888B;;;0; 'ballooning'=0B;;;0; 'shared'=548864B;;;0;`

So I don't understand problem of time sync in the esx

**Comment by garnier-quentin** [comment]
Maybe for vm memory, it uses vcenter time (not from the ESX).

**Comment by Cool34000** [comment]
> So I don't understand problem of time sync in the esx

Some counters just need an accurate date/time.
I have some servers without vCenter and it's the same issue...

To fix the problem, you just need to start the NTP service on all your hosts and configure it with your prefered time server (I use pool.ntp.org with success)
Use this [KB](https://kb.vmware.com/s/article/2012069) if you don't know how to do this.

**Comment by garnier-quentin** [comment]
No news. You can close it if you still have the issue.
