### ISSUE TITLE
[network::juniper::sa::plugin] mode users

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#192]
Hello,

Should it be possible to add a new option "filter" to choose which users we want to count ?

Here is the result for two equipments :

OK: Current concurrent signed-in web users connections: 96 - Current concurrent meeting users connections: unknown - Current concurrent node logged users connections: 0 - Current concurrent cluster logged users connections: 96 | 'web'=96;;;0; 'meeting'=;;;0; 'node'=0;;;0; 'cluster'=96;;;0;

OK: Current concurrent signed-in web users connections: 101 - Current concurrent meeting users connections: unknown - Current concurrent node logged users connections: 101 - Current concurrent cluster logged users connections: 101 | 'web'=101;;;0; 'meeting'=;;;0; 'node'=101;;;0; 'cluster'=101;;;0;

- meeting users is unknown for both
- web and cluster users are same value
- node users is redondant with above values for the last one and is equal to zero for the first one
- and the output message is very very very very long !
- filter-perfdata option does not shorten the output message, only for perfdata, that's why a new "filter" option would be great !

Thanks.

**Comment by garnier-quentin** [comment]
Not so easy. You can't manage everything. I don't really want to create a new langage in command line :)
If you want to check only one value, you can use the snmp_standard::plugin no ?

**Comment by ritouret** [comment]
It's already done. I just wanted to use all your network::juniper::sa::plugin mode instead of.

I thought about your hardware mode mechanism with --component option for one value or --filter option to choose what we want.

Just forget it if you think it's not relevant.

Thanks Quentin.

**Comment by garnier-quentin** [comment]
Mmm. Need to think about it. Can be relevant.

**Comment by ritouret** [comment]
Just tested, it works perfectly. Many thanks.
