### ISSUE TITLE
[apps::protocols::http::plugin] mode json-content

### ISSUE THREAD

**Issue by hupefranz** [centreon/centreon-plugins#1921]
Hi

I have a JSON page which contains the following value : {"total":value}
```
dell3340@hupefranz:~$ curl -X GET "https://10.10.10.80l/api/v1/lab/test" -H "accept: application/json"
{"total":0}
```

I would like to generate a warning state when the value > 50 and value < 100, critical state when the value > 100
How can I achieve this ?

`[root@nagios centreon]# ./centreon_plugins.pl --plugin apps::protocols::http::plugin --mode json-content --hostname 10.10.10.80 --urlpath='/api/v1/lab/test' --lookup='total' --threshold-value='values' --format-ok='Return: %{values}' --format-warning='Return: %{values_warning}' --format-critical='Return: %{values_critical}'  --warning-numeric='%{values} > 50 or %{values} < 100' --critical-numeric='%{values} > 100' 
UNKNOWN: Wrong warning-numeric threshold '%{values} > 50 or %{values} < 100'.`

Anyone have an idea ?

**Comment by garnier-quentin** [comment]
Could you try that ?
```
centreon_plugins.pl --plugin apps::protocols::http::plugin --mode json-content --hostname 10.10.10.80 --urlpath='/api/v1/lab/test' --lookup='total' --threshold-value='values' --format-ok='Return: %{values}' --format-warning='Return: %{values_warning}' --format-critical='Return: %{values_critical}' --warning-numeric='50:100' --critical-numeric='100'
```

**Comment by hupefranz** [comment]
Hi Garnier.
Thank you for your help

returns 1 - warning
But between 0 and 49 it has to stay ok
```
[root@nagios centreon]# ./centreon_plugins.pl --plugin apps::protocols::http::plugin --mode json-content --hostname 10.10.10.80 --urlpath='/api/v1/lab/test' --lookup='total' --threshold-value='values' --format-ok='Return: %{values}' --format-warning='Return: %{values_warning}' --format-critical='Return: %{values_critical}' --warning-numeric='50:100' --critical-numeric='100' 
WARNING: Return: 1 | 'count'=1;;;0; 'element_1'=1;50:100;0:100;; 'time'=0.236s;;;0;
```

you have another idea?

**Comment by garnier-quentin** [comment]
Ok. Try that:
```
centreon_plugins.pl --plugin apps::protocols::http::plugin --mode json-content --hostname 10.10.10.80 --urlpath='/api/v1/lab/test' --lookup='total' --threshold-value='values' --format-ok='Return: %{values}' --format-warning='Return: %{values_warning}' --format-critical='Return: %{values_critical}' --warning-numeric='@50:100' --critical-numeric='100'

**Comment by hupefranz** [comment]
It worked!
thanks you Garnier :+1:
