### ISSUE TITLE
Azure monitor alerts integration

### ISSUE THREAD

**Issue by laltroale** [centreon/centreon-plugins#1923]
Hi Team,
i'd like to know if it's possible to capture the alerts configured with Azure alert monitor.
We noted there is an alert mode in cloud::azure::management::monitor::plugin but when we list modes we get only the following modes available  **discovery get-metrics health**.
We tested this with api on version  '2018-08-01-rc' .

Do you have any example to setup this check?

Thanks a lot,
A.

**Comment by garnier-quentin** [comment]
I see the alert mode. Could you test with the last github version ?

**Comment by drapiti** [comment]
Hi, we tested with the latest github version. The alert mode returns the alert summary ie the count but not the alerts themselves. Is it possible to view/return the specific open alerts as well as the count?
Thank you
D.

**Comment by garnier-quentin** [comment]
Could you provide the result with --debug option ?

**Comment by mbaruchello77** [comment]
./centreon_plugins.pl --plugin cloud::azure::management::monitor::plugin --custommode api --mode alert --subscription  XXXXX-XXX-XXXX-XXXXX-XXXXXXXXXXXXXX  --tenant XXXXX-XXXX-XXXX-XXXXXXXXXX --client-id XXXXX-XXXX-XXXX-XXXXXXXXXX --client-secret XXXXX-XXXX-XXXX-XXXXXXXXXX --proxyurl https://myhost.com:9090 --http-backend=curl --resource-group rsghclo0p001 --resource LAWHCLO0P02 '--api-version' '2019-05-05-preview' --debug
Use of uninitialized value in concatenation (.) or string at /opt/monitoring/plugins/centreon-plugins-master/cloud/azure/management/monitor/mode/alert.pm line 41.
Use of uninitialized value in concatenation (.) or string at /opt/monitoring/plugins/centreon-plugins-master/cloud/azure/management/monitor/mode/alert.pm line 41.
Use of uninitialized value in concatenation (.) or string at /opt/monitoring/plugins/centreon-plugins-master/cloud/azure/management/monitor/mode/alert.pm line 41.
Use of uninitialized value in concatenation (.) or string at /opt/monitoring/plugins/centreon-plugins-master/cloud/azure/management/monitor/mode/alert.pm line 41.
Use of uninitialized value in concatenation (.) or string at /opt/monitoring/plugins/centreon-plugins-master/cloud/azure/management/monitor/mode/alert.pm line 41.
OK: All alerts are ok | 'alerts..count'=0;;;; 'alerts..count'=0;;;; 'alerts..count'=0;;;; 'alerts..count'=0;;;; 'alerts..count'=0;;;;
== Info: About to connect() to proxy myhost.com port 9090 (#0)
== Info:   Trying 10.244.128.20...
== Info: Connected tomyhost.com (XXXXXXX) port 9090 (#0)
== Info: Establish HTTP proxy tunnel to management.azure.com:443
=> Send header: CONNECT management.azure.com:443 HTTP/1.1
Host: management.azure.com:443
Proxy-Connection: Keep-Alive
Accept:application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvY2M0YmFmMDAtMTVjOS00OGRkLTlmNTktODhjOThiZGUyYmU3LyIsImlhdCI6MTU4Njg1ODY3OCwibmJmIjoxNTg2ODU4Njc4LCJleHAiOjE1ODY4NjI1NzgsImFpbyI6IjQyZGdZTkExRi9ULzlvZ3orLzJmODRxU05jc2lBQT09IiwiYXBwaWQiOiJhYjY5Yzg0NS0wOTJhLTRjZWItOGFmMy1lOGFkNDY0YTI3NzgiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9jYzRiYWYwMC0xNWZAM5LTQ4ZGQtOWY1OS04OGM5OGJkZTJiZTcvIiwib2lkIjoiMmMxMjYyZTItZGJjZS00ZDkwLWE0NzItYTI3NGYzZWMwMzNkIiwic3ViIjoiMmMxMjYyZTItZGJjZS00ZDkwLWE0NzItYTI3NGYzZWMwMzNkIiwidGlkIjoiY2M0YmFmMDAtMTVjOS00OGRkLTlmNTktODhjOThiZGUyYmU3IiwidXRpIjoiMC1nQ0x4UTRsMDJJZjZOYzJLUS1BQSIsInZlciI6IjEuMCJ9.hOOWyyI_ftQTebra7ilkQts_0iK-TRxgi7QEsheYC3TyBYdggZ3U3axKwgN5wcE0bhvwHV8JJDqE5zNkRQ-p2Jpzi0P3PcbUMTkCbBLi-qS3exZM7wjZIYwoP6dIe32I-muQmIe-q7mLq3LANXTyf5h_pXJ_Mh2Z4Qvz9I7H6QVk6ryOqSeKP7XPP2-ou7l9LZdJXo3LapA3sQBG5dph2z8hjr4vAg4kSd6bNwuepnXAd7Y2_-mTQUbvqNnANtEs59Uaez05o2MQuYFdHvPyHUb8MV7gUYZMKmdvTJ1Q7zP75ZcEH-OyQ7JyGAZOSGFLilUN9rTx4wnN6vcMkmmQlg

=> Recv header: HTTP/1.0 200 Connection established
=> Recv header:
== Info: Proxy replied OK to CONNECT request
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
== Info: Server certificate:
== Info:        subject: CN=management.azure.com
== Info:        start date: Jul 03 22:48:10 2019 GMT
== Info:        expire date: Jul 03 22:48:10 2021 GMT
== Info:        common name: management.azure.com
== Info:        issuer: CN=Microsoft IT TLS CA 4,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
=> Send header: GET /subscriptions/78abd756-63a3-45cf-b362-8b377a730765/providers/Microsoft.AlertsManagement/alertsSummary?api-version=2019-05-05-preview&groupby=severity&targetResourceGroup=rsghclo0p001&targetResourceName=LAWHCLO0P02&timeRange=1h HTTP/1.1
Host: management.azure.com
Accept:application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvY2M0YmFmMDAtMTVjOS00OGRkLTlmNTktODhjOThiZGUyYmU3LyIsImlhdCI6MTU4Njg1ODY3OCwibmJmIjoxNTg2ODU4Njc4LCJleHAiOjE1ODY4NjI1NzgsImFpbyI6IjQyZGdZTkExRi9ULzlvZ3orLzJmODRxU05jc2lBQT09IiwiYXBwaWQiOiJhYjY5Yzg0NS0wOTJhLTRjZWItOGFmMy1lOGFZSWkNDY0YTI3NzgiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9jYzRiYWYwMC0xNWM5LTQ4ZGQtOWY1OS04OGM5OGJkZTJiZTcvIiwib2lkIjoiMmMxMjYyZTItZGJjZS00ZDkwLWE0NzItYTI3NGYzZWMwMzNkIiwic3ViIjoiMmMxMjYyZTItZGJjZS00ZDkwLWE0NzItYTI3NGYzZWMwMzNkIiwidGlkIjoiY2M0YmFmMDAtMTVjOS00OGRkLTlmNTktODhjOThiZGUyYmU3IiwidXRpIjoiMC1nQ0x4UTRsMDJJZjZOYzJLUS1BQSIsInZlciI6IjEuMCJ9.hOOWyyI_ftQTebra7ilkQts_0iK-TRxgi7QEsheYC3TyBYdggZ3U3axKwgN5wcE0bhvwHV8JJDqE5zNkRQ-p2Jpzi0P3PcbUMTkCbBLi-qS3exZM7wjZIYwoP6dIe32I-muQmIe-q7mLq3LANXTyf5h_pXJ_Mh2Z4Qvz9I7H6QVk6ryOqSeKP7XPP2-ou7l9LZdJXo3LapA3sQBG5dph2z8hjr4vAg4kSd6bNwuepnXAd7Y2_-mTQUbvqNnANtEs59Uaez05o2MQuYFdHvPyHUb8MV7gUYZMKmdvTJ1Q7zP75ZcEH-OyQ7JyGAZOSGFLilUN9rTx4wnN6vcMkmmQlg

=> Recv header: HTTP/1.1 200 OK
=> Recv header: Cache-Control: no-store, no-cache
=> Recv header: Pragma: no-cache
=> Recv header: Content-Length: 375
=> Recv header: Content-Type: application/json; charset=utf-8
=> Recv header: Expires: -1
=> Recv header: x-ms-request-id: c91abc15-72b4-4520-a82f-9636ecb4c72a
=> Recv header: X-Content-Type-Options: nosniff
=> Recv header: X-XSS-Protection: 1; mode=block
=> Recv header: Content-Security-Policy: script-src 'self'
=> Recv header: Strict-Transport-Security: max-age=31536000; includeSubDomains
=> Recv header: x-ms-ratelimit-remaining-subscription-resource-requests: 999
=> Recv header: x-ms-correlation-request-id: 99cc3437-4380-4df4-94ed-5fe5b35f2a6a
=> Recv header: x-ms-routing-request-id: GERMANYWESTCENTRAL:20200414T100952Z:99cc3437-4380-4df4-94ed-5fe5b35f2a6a
=> Recv header: Date: Tue, 14 Apr 2020 10:09:51 GMT
=> Recv header:
=> Recv data: {"properties":{"groupedby":"severity","total":0,"values":[{"name":"Sev0","count":0},{"name":"Sev1","count":0},{"name":"Sev2","count":0},{"name":"Sev3","count":0},{"name":"Sev4","count":0}]},"id":"/subscriptions/XXXXXXXXX-XXXXX-XXXXX/providers/Microsoft.AlertsManagement/alertsSummary/current","type":"Microsoft.AlertsManagement/alertsSummary","name":"current"}
== Info: Connection #0 to host inet1.gtm.corp.sanpaoloimi.com left intact
alert severity: 'Sev0', Count: '0'
alert severity: 'Sev1', Count: '0'
alert severity: 'Sev2', Count: '0'
alert severity: 'Sev3', Count: '0'
alert severity: 'Sev4', Count: '0'

**Comment by laltroale** [comment]
Hi, we are proceding to install last github version to check if the issue is still present.
Could you please clarify what is the output of the control? the count of alerts on Azure console?
Is it possible to return the content of open alerts from Azure Monitor?

**Comment by garnier-quentin** [comment]
Could you execute again with last version with --debug and provide the result ?

**Comment by garnier-quentin** [comment]
It should be fixed. Without news i close it
