### ISSUE TITLE
[hardware::pdu::eaton::plugin] filter outlet and group

### ISSUE THREAD

**Issue by squema** [centreon/centreon-plugins#1926]
When you use the plugin hardware::pdu::eaton::plugin in both group and outlet mode you get information about all groups or all outlets.

**for example**
`OK: All groups are ok | 'Section A strapping 0#group.current.ampere'=0.34A;;;0; 'Section A strapping 0#group.voltage.volt'=229.62V;;;; 'Section A strapping 0#group.power.watt'=12.00W;;;; 'Section B strapping 0#group.current.ampere'=0.54A;;;0; 'Section B strapping 0#group.voltage.volt'=229.69V;;;; 'Section B strapping 0#group.power.watt'=101.00W;;;; 'Section C strapping 0#group.current.ampere'=0.43A;;;0; 'Section C strapping 0#group.voltage.volt'=229.59V;;;; 'Section C strapping 0#group.power.watt'=59.00W;;;; 'Section D strapping 0#group.current.ampere'=0.83A;;;0; 'Section D strapping 0#group.voltage.volt'=229.63V;;;; 'Section D strapping 0#group.power.watt'=151.00W;;;; 'Section E strapping 0#group.current.ampere'=0.91A;;;0; 'Section E strapping 0#group.voltage.volt'=228.89V;;;; 'Section E strapping 0#group.power.watt'=162.00W;;;; 'Section F strapping 0#group.current.ampere'=2.42A;;;0; 'Section F strapping 0#group.voltage.volt'=228.57V;;;; 'Section F strapping 0#group.power.watt'=509.00W;;;; 'Section A strapping 1#group.current.ampere'=0.44A;;;0; 'Section A strapping 1#group.voltage.volt'=238.57V;;;; 'Section A strapping 1#group.power.watt'=76.00W;;;; 'Section B strapping 1#group.current.ampere'=0.30A;;;0; 'Section B strapping 1#group.voltage.volt'=238.61V;;;; 'Section B strapping 1#group.power.watt'=10.00W;;;; 'Section C strapping 1#group.current.ampere'=0.42A;;;0; 'Section C strapping 1#group.voltage.volt'=239.86V;;;; 'Section C strapping 1#group.power.watt'=67.00W;;;; 'Section D strapping 1#group.current.ampere'=0.88A;;;0; 'Section D strapping 1#group.voltage.volt'=239.86V;;;; 'Section D strapping 1#group.power.watt'=168.00W;;;; 'Section E strapping 1#group.current.ampere'=0.92A;;;0; 'Section E strapping 1#group.voltage.volt'=238.50V;;;; 'Section E strapping 1#group.power.watt'=176.00W;;;; 'Section F strapping 1#group.current.ampere'=2.49A;;;0; 'Section F strapping 1#group.voltage.volt'=238.25V;;;; 'Section F strapping 1#group.power.watt'=534.00W;;;;`

or 

`OK: All outlets are ok | 'Outlet C3 strapping 0#outlet.current.ampere'=0.38A;;;0; 'Outlet C3 strapping 0#outlet.power.watt'=58.00W;;;; 'Outlet D2 strapping 0#outlet.current.ampere'=0.37A;;;0; 'Outlet D2 strapping 0#outlet.power.watt'=58.00W;;;; 'Outlet D3 strapping 0#outlet.current.ampere'=0.46A;;;0; 'Outlet D3 strapping 0#outlet.power.watt'=90.00W;;;; 'Outlet E2 strapping 0#outlet.current.ampere'=0.36A;;;0; 'Outlet E2 strapping 0#outlet.power.watt'=64.00W;;;; 'Outlet E3 strapping 0#outlet.current.ampere'=0.53A;;;0; 'Outlet E3 strapping 0#outlet.power.watt'=97.00W;;;; 'Outlet F1 strapping 0#outlet.current.ampere'=1.24A;;;0; 'Outlet F1 strapping 0#outlet.power.watt'=264.00W;;;; 'Outlet F2 strapping 0#outlet.current.ampere'=0.48A;;;0; 'Outlet F2 strapping 0#outlet.power.watt'=105.00W;;;; 'Outlet F3 strapping 0#outlet.current.ampere'=0.73A;;;0; 'Outlet F3 strapping 0#outlet.power.watt'=136.00W;;;; 'Outlet A3 strapping 0#outlet.current.ampere'=0.29A;;;0; 'Outlet A3 strapping 0#outlet.power.watt'=11.00W;;;; 'Outlet B3 strapping 0#outlet.current.ampere'=0.52A;;;0; 'Outlet B3 strapping 0#outlet.power.watt'=100.00W;;;; 'Outlet C3 strapping 1#outlet.current.ampere'=0.39A;;;0; 'Outlet C3 strapping 1#outlet.power.watt'=67.00W;;;; 'Outlet D2 strapping 1#outlet.current.ampere'=0.36A;;;0; 'Outlet D2 strapping 1#outlet.power.watt'=59.00W;;;; 'Outlet D3 strapping 1#outlet.current.ampere'=0.49A;;;0; 'Outlet D3 strapping 1#outlet.power.watt'=101.00W;;;; 'Outlet E2 strapping 1#outlet.current.ampere'=0.35A;;;0; 'Outlet E2 strapping 1#outlet.power.watt'=61.00W;;;; 'Outlet E3 strapping 1#outlet.current.ampere'=0.56A;;;0; 'Outlet E3 strapping 1#outlet.power.watt'=114.00W;;;; 'Outlet F1 strapping 1#outlet.current.ampere'=1.17A;;;0; 'Outlet F1 strapping 1#outlet.power.watt'=254.00W;;;; 'Outlet F2 strapping 1#outlet.current.ampere'=0.58A;;;0; 'Outlet F2 strapping 1#outlet.power.watt'=129.00W;;;; 'Outlet F3 strapping 1#outlet.current.ampere'=0.78A;;;0; 'Outlet F3 strapping 1#outlet.power.watt'=147.00W;;;; 'Outlet A3 strapping 1#outlet.current.ampere'=0.41A;;;0; 'Outlet A3 strapping 1#outlet.power.watt'=76.00W;;;; 'Outlet B3 strapping 1#outlet.current.ampere'=0.27A;;;0; 'Outlet B3 strapping 1#outlet.power.watt'=10.00W;;;;`

You can filter only the performance data but not the groups or outlets?

Any improvement on this would be surely appreciate

Regards

**Comment by garnier-quentin** [comment]
I added filter-name options.
