### ISSUE TITLE
Ruckus ICX switches not supported

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1927]
Ruckus ICX series switches are not very well supported. Could you provide support to monitor CPU, environment ecc. for this switches?

[fastiron-08092-mibref.pdf](https://github.com/centreon/centreon-plugins/files/4442310/fastiron-08092-mibref.pdf)
[ruckus-icx-switch.mib.txt](https://github.com/centreon/centreon-plugins/files/4442313/ruckus-icx-switch.mib.txt)

**Comment by garnier-quentin** [comment]
Could you provide the mib files ?
https://support.ruckuswireless.com/software/1780-ruckus-icx-fastiron-08-0-80-snmp-mibs-for-icx-7150-and-7250-series-switches-spr-sps

**Comment by garnier-quentin** [comment]
I have the mib files. It's a foundry system (brocade). I can develop a plugin. I found cpu, memory and hardware stuffs.

**Comment by joschi99** [comment]
Hi @garnier-quentin, I will send you the mib from ruckus as soon as possible to avoid some difference.

Happy Easter

**Comment by joschi99** [comment]
Here you can find the mibs: 
[ICX7150-7250-08080-MIBs.zip](https://github.com/centreon/centreon-plugins/files/4462646/ICX7150-7250-08080-MIBs.zip)

**Comment by garnier-quentin** [comment]
could you test it ?
