### ISSUE TITLE
[cloud::ovh::restapi::plugin] --custommode use

### ISSUE THREAD

**Issue by FrdricMalard** [centreon/centreon-plugins#1928]
Hello

We don't understand the use of cloud::ovh::restapi::plugin --custommode.
When do you init the parameter "path" in api.pm ?

[root@poclappmkp01:/usr/lib/centreon/centreon-plugins]# ./centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin --dyn-mode=cloud::ovh::restapi::custom::api --custommode=api --ovh-application-key=xxx --ovh-application-secret=xxx--ovh-consumer-key=xxx--timeout=10

Response : UNKNOWN: Need to specify --ovh-application-key option.

as you can see the --ovh-application-key exists in the command.

Thanks

**Comment by Sims24** [comment]
Hi, 

Could you please try like that : 

[root@poclappmkp01:/usr/lib/centreon/centreon-plugins]# ./centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin --custommode=api --ovh-application-key=xxx --ovh-application-secret=xxx--ovh-consumer-key=xxx--timeout=10

**Comment by Sims24** [comment]
and specify a mode also eg:

[root@poclappmkp01:/usr/lib/centreon/centreon-plugins]# ./centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin --custommode=api **--mode=quota-usage** --ovh-application-key=xxx --ovh-application-secret=xxx--ovh-consumer-key=xxx--timeout=10

**Comment by FrdricMalard** [comment]
Hi

[root@poclappmkp01:/usr/lib/centreon/centreon-plugins]# ./
centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin --custommode=api
--ovh-application-key=xxx--ovh-application-secret=xxx--ovh-consumer-key=xxx
--timeout=10
UNKNOWN: Need to specify '--mode' or '--dyn-mode' option.

[root@poclappmkp01:/usr/lib/centreon/centreon-plugins]# ./
centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin --custommode=api
--mode=quota-usage --ovh-application-key=xxx --ovh-application-secret=xxx
--ovh-consumer-key=xxx--timeout=10
UNKNOWN: 403 Forbidden |

**Comment by Sims24** [comment]
Ok, the second one works. You have to specify the mode you want to use. But here it looks like your credentials are not authorized.

You can list available mode with: 
/usr/lib/centreon/centreon-plugins]# ./
centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin --list-mode

**Comment by Sims24** [comment]
@FrdricMalard by the way there is a missing space in you command that might explain the authentication issue

/usr/lib/centreon/centreon-plugins]# ./
centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin --custommode=api
--mode=quota-usage --ovh-application-key=xxx --ovh-application-secret=xxx
**--ovh-consumer-key=xxx--timeout=10**

**Comment by FrdricMalard** [comment]
Hi

Yes but we want to use custom api and not quota usage.

Regards

**Comment by Sims24** [comment]
Custom API is not a mode. It's just a boiler plate.

**Comment by Sims24** [comment]
Maybe you could describe a little bit more what you're trying to achieve ?

**Comment by FrdricMalard** [comment]
Ok thanks
Have you an example to use this bollerplate ?

**Comment by Sims24** [comment]
Yes quotausage.pm and sms.pm

https://github.com/centreon/centreon-plugins/tree/master/cloud/ovh/restapi/mode

**Comment by FrdricMalard** [comment]
Hello

To describe a little bit more what you're trying to achieve :

With a curl and signature calculation shell :

curl -H 'X-Ovh-Application:xxx -H 'X-Ovh-Timestamp:1585837037' -H
'X-Ovh-Signature:$1$xxx' -H 'X-Ovh-Consumer:xxx'
https://eu.api.ovh.com/1.0/service/14926710

{"plan":{"code":null,"product":{"name":null}},"resource":{"displayName":"BDD),"state":"ok","name":"pcc-178-33-10xxx"},"renew":null,"quantity":1,"details":[],"expirationDate":"2020-04-30","creationDate":"2017-10-11","engagementDate":null,"state":"ok","nextBillingDate":"2020-05-01","route":{"url":"/dedicatedCloud/pcc-178-33-10xxx","path":"/dedicatedCloud/{serviceName}","vars":[{"key":"serviceName","value":"pcc-178-33-10xx"}]}}[

How to create a custom perl api ? like this ?
Add a line in custom api paragraph of plugin.pm and run my perl api with
centreon_plugins.pl ?

plugin.pm
    $self->{custom_modes}{api} = 'cloud::ovh::restapi::custom::api';
    $self->{custom_modes}{api2ovh} = 'cloud::ovh::restapi::custom::api2ovh';
        return $self;


 api2ovh.pm
use cloud::ovh::restapi::custom::api;
my $applicationKey = "xxx";
my $applicationSecret = "xxx";
my $consumer_key = "xxx";
my $Api    = cloud::ovh::restapi::custom::api->new(ovh-application-key =>
$applicationKey, ovh-application-secret => $applicationSecret,
ovh-consumer-key => $consumer_key);
my $Answer = $Api->get(path => '/service/14926710');
if ($Answer)
{
my $content = $Answer->content;
print "$content";
}
else
{
my $error = $Answer->error;
print "$error";
}


[root@poclappmkp01:/usr/lib/centreon/centreon-plugins]# ./
centreon_plugins.pl --plugin=cloud::ovh::restapi::plugin
--dyn-mode=cloud::ovh::restapi::custom::api2ovh --custommode=api2ovh
Class Custom: Need to specify 'output' argument.

In this case, what is the default value of output  YYY ?
  my $Api    = cloud::ovh::restapi::custom::api->new(output =>
YYY,ovh-application-key => $applicationKey, ovh-application-secret =>
$applicationSecret, ovh-consumer-key => $consumer_key);

**Comment by Sims24** [comment]
Thanks for these informations, I better understand what you want to do. 

You must always use the template counter, it will manage for you the output, thresholds, options and so on. 

A good start it's to simply copy/paste the quotausegae.pm mode. Start with changing https://github.com/centreon/centreon-plugins/blob/506ff1c9e1ab9b6e5696693a13f3c17bea30da2b/cloud/ovh/restapi/mode/quotausage.pm#L21 replacing quotausage by service. 

You now have a service.pm and it would be awesome let the user sepcify it's own serviceId as a parameter. 

In this sub https://github.com/centreon/centreon-plugins/blob/506ff1c9e1ab9b6e5696693a13f3c17bea30da2b/cloud/ovh/restapi/mode/quotausage.pm#L93 specify what matters within API response (https://api.ovh.com/console/#/service/%7BserviceId%7D#GET) 

Then in this sub https://github.com/centreon/centreon-plugins/blob/506ff1c9e1ab9b6e5696693a13f3c17bea30da2b/cloud/ovh/restapi/mode/quotausage.pm#L132  do your api request through the boiler plate and assign value to counters set in the previous mentionned sub https://github.com/centreon/centreon-plugins/blob/506ff1c9e1ab9b6e5696693a13f3c17bea30da2b/cloud/ovh/restapi/mode/quotausage.pm#L147

That's the more I can help here. 
But feel free to send curl, answers and so on in private, we can do a first part of the job for you as soon as we get some time. 

thx,
Simon

**Comment by Sims24** [comment]
Note that we would be very interested in extending our ovh monitoring capabilities. 

If you want some advanced help from us, just contact me by mail we will define how  we can work on this together.

Simon
