### ISSUE TITLE
apps::vmware::connector::plugin Error in perl-UUID 

### ISSUE THREAD

**Issue by hupefranz** [centreon/centreon-plugins#1929]
Hi
When running the centreon_plugin.pl with mode apps::vmware::connector::plugin, I get the following output.
My system is CentOS 6.10 64-bit,
Packages:
 - perl-libwww-perl-5.833-5.el6.noarch
 - perl-XML-LibXML-1.70-5.el6.x86_64
 - perl-Class-MethodMaker-2.16-6.el6.x86_64
 - perl-Crypt-SSLeay-0.57-17.el6.x86_64
 - perl-SOAP-Lite-0.710.10-4.el6.noarch
 - [perl-Data-UUID](https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Data-UUID-1.224.tar.gz) 
```
[root@build centreon-plugins-20200204]# ./centreon_plugins.pl --plugin apps::vmware::connector::plugin --mode net-host  --connector-hostname='10.10.90.1' --vsphere-username='test' --vsphere-password=''
UNKNOWN: Undefined subroutine &UUID::generate called at /root/centreon-plugins-20200204/apps/vmware/connector/custom/connector.pm line 263.
```
```
[root@build centreon-plugins-20200204]# find / -iname UUID.pm
/usr/local/lib64/perl5/Data/UUID.pm
/usr/lib64/perl5/UUID.pm
/root/Data-UUID-1.224/blib/lib/Data/UUID.pm
/root/Data-UUID-1.224/UUID.pm
/opt/vmware-vsphere-cli-distrib/lib/5.10/UUID-0.03/lib/UUID.pm
/opt/vmware-vsphere-cli-distrib/lib/UUID-0.03/lib/UUID.pm
```
Anyone have an idea ?

**Comment by garnier-quentin** [comment]
You use the wrong module. The good one is: https://metacpan.org/pod/UUID
