### ISSUE TITLE
network::cisco::standard::snmp::plugin stack long output

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#193]
Hi,

Can you please add to network::cisco::standard::snmp::plugin stack mode option, that it will show how many members there are.
Right now I only see the stack size when adding --verbose when checking from commandline, but I need to see it in frontend also.
Thanks!

**Comment by garnier-quentin** [comment]
You need to have a perfdata 'size' ?

**Comment by kadrika** [comment]
No, I need to see in the output how many devices are stacked together. For example, if there are 3 switches stacked together it will show output as: OK: Stack ring is redundant. Member count 3 (FOC123456, FOC11223344, FOC244882). Those FOCxxxxx are member serial numbers.

**Comment by garnier-quentin** [comment]
Not sure i'll do that. Can be really to verbose for the short output.

**Comment by garnier-quentin** [comment]
You can develop your own mode and use it with option --dyn-mode.

**Comment by kadrika** [comment]
ok :(
The serial numbers are not so important, but the member count is, because this is the only way to know how many switches our clients have. I will try some other way then.

**Comment by garnier-quentin** [comment]
I can display the number in the stack.

**Comment by kadrika** [comment]
That would be great!

**Comment by garnier-quentin** [comment]
Which role i count ? Or states ? 
Because i can have 'notMember' for role and for state: 'removed'. Or does i count all entries ? I can also add a custom expression.

**Comment by kadrika** [comment]
I think member that have to be connected need to be counted, so count members that are in ready state. For example switch shows with verbose:
 OK: Stack ring is redundant |
Member '2' state is ready [Role is 'member']
Member '1' state is ready [Role is 'master']

So this service should shouw in out put that: Stack ring is redundant | Number of members 2

**Comment by cgagnaire** [comment]
Hi @kadrika,
Can you test the mode ?
Thanks!

**Comment by cgagnaire** [comment]
Tested and OK!
