### ISSUE TITLE
[ cloud::azure::management::monitor::plugin] Cannot decode response

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#1932]
Hello,

After installing azcli in version 2.3.1 I have this error:

UNKNOWN: Cannot decode response (add --debug option to display returned content)

This is my debug line :

`bash-4.2$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::management::monitor::plugin --custommode='azcli' --mode='get-metrics' --tenant='xxxxxxxx' --resource='/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Web/sites/xxxxxxxxxx' --metric 'Http5xx' --warning-metric 20 --critical-metric 30 --timeout 45 --debug
UNKNOWN: Cannot decode response (add --debug option to display returned content)
Command line: 'az monitor metrics list --metrics 'Http5xx' --start-time 2020-04-09T06:36:40Z --end-time 2020-04-09T06:46:40Z --interval PT1M --aggregation 'Average' --output json --resource '/subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxx/providers/Microsoft.Web/sites/xxxxxxxxxxxxx' --resource-group '' --resource-type '' --resource-namespace '''
Command group 'monitor' is in preview. It may be changed/removed in a future release.
{
  "cost": 0.0,
  "interval": "0:01:00",
  "namespace": "Microsoft.Web/sites",
  "resourceregion": "francecentral",
  "timespan": "2020-04-09T06:36:40Z/2020-04-09T06:46:40Z",
  "value": [
    {
      "displayDescription": "Http Server Errors",
      "errorCode": "Success",
      "id": "/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Web/sites/clients-elciaonline-paas-ael-pp/providers/Microsoft.Insights/metrics/Http5xx",
      "name": {
        "localizedValue": "Http Server Errors",
        "value": "Http5xx"
      },
      "resourceGroup": "xxxxxxxxxxxx",
      "timeseries": [
        {
          "data": [
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:36:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:37:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:38:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:39:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:40:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:41:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:42:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:43:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:44:00+00:00",
              "total": null
            },
            {
              "average": 0.0,
              "count": null,
              "maximum": null,
              "minimum": null,
              "timeStamp": "2020-04-09T06:45:00+00:00",
              "total": null
            }
          ],
          "metadatavalues": []
        }
      ],
      "type": "Microsoft.Insights/metrics",
      "unit": "Count"
    }
  ]
}`

**Comment by Sims24** [comment]
Hi, 

Could you try to specify add these options to the command: 

	--timeframe='900' --interval='PT5M' --aggregation='Total'

Not sure it will does the job but let's try

**Comment by prohand** [comment]
Hello,

Thank you for your response.

I can try and the problem is same :(

**Comment by Sims24** [comment]
And with --aggregation=average –-interval=PT1M --timeframe=600

**Comment by prohand** [comment]
Same problem

**Comment by Sims24** [comment]
Are you using a proxy ?

**Comment by prohand** [comment]
no not a proxy

**Comment by garnier-quentin** [comment]
It's because of that message:
Command group 'monitor' is in preview. It may be changed/removed in a future release.

Maybe we need to add option:  --only-show-errors

**Comment by prohand** [comment]
Ok thank you but : 
Unknown option: only-show-errors at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67

**Comment by garnier-quentin** [comment]
That option is not implemented ;) it's for az cli.

**Comment by prohand** [comment]
How to do it?

**Comment by prohand** [comment]
I have the answer.

export AZURE_CORE_ONLY_SHOW_ERRORS="True"

**Comment by garnier-quentin** [comment]
That's ok so. need to add directly that option

**Comment by prohand** [comment]
It's OK with option : --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True"

Thank you

**Comment by Sims24** [comment]
Thanks for the tips !
