### ISSUE TITLE
storage::qnap::snmp::plugin problem can't select storage

### ISSUE THREAD

**Issue by bastiencha** [centreon/centreon-plugins#1935]
Hello, 

When I list storages, I have : 

`/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --hostname=*** --snmp-community=*** --snmp-version=2c --snmp-port=*** --mode=list-storages`

> List storage:
> Skipping storage 'Physical memory': no type or no matching filter type
> Skipping storage 'Swap space': no type or no matching filter type
> Skipping storage 'Virtual memory': no type or no matching filter type
> '/mnt/HDA_ROOT' [size = 517427200B] [id = 31]
> '/sys/fs/cgroup/memory' [size = 0B] [id = 32]
> '/share/CACHEDEV1_DATA' [size = 7777213669376B] [id = 33]
> '/mnt/ext' [size = 372228096B] [id = 34]
> Skipping storage 'Memory buffers': no type or no matching filter type
> Skipping storage 'Cached memory': no type or no matching filter type
> Skipping storage 'Shared memory': no type or no matching filter type

I want check storage /share/CACHEDEV1_DATA, I do : 

`/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --hostname=*** --snmp-community=*** --snmp-version=2c --snmp-port=*** --mode=storage -warning-usage='80' --critical-usage='90' --verbose --storage=/share/CACHEDEV1_DATA`

But I have : 

> UNKNOWN: No storage found. Can be: filters, cache file.

Can you help me please ?

**Comment by garnier-quentin** [comment]
Please add option --name
