### ISSUE TITLE
Ruckus zonedirector not supported

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1937]
Ruckus zonedirector (WLC) is not supported

[ZoneDirector-10.2-SNMPReferenceGuide-RevB-20190430.pdf](https://github.com/centreon/centreon-plugins/files/4475256/ZoneDirector-10.2-SNMPReferenceGuide-RevB-20190430.pdf)

**Comment by garnier-quentin** [comment]
Need snmpwalk and mib files

**Comment by joschi99** [comment]
snmpwalk and mib files:

[ZD-10.2.1.0.159-MIBs.zip](https://github.com/centreon/centreon-plugins/files/4523188/ZD-10.2.1.0.159-MIBs.zip)
[ruckus_zd3000-walk.zip](https://github.com/centreon/centreon-plugins/files/4523190/ruckus_zd3000-walk.zip)

**Comment by garnier-quentin** [comment]
It's still ruckus smartzone. So no ;)

**Comment by garnier-quentin** [comment]
could you test the zonedirector plugin ? Could you provide for the smartzone mibs and snmpwalk ?

**Comment by joschi99** [comment]
Have done some test, seem's working, thanks.

Smartzone: i will send you the mib by email

**Comment by joschi99** [comment]
Hi @garnier-quentin,
I have seen that mode=list-access-points and mode=access-points reads the ap description and not the ap name. The ap description is a optional value, so it should be better that both modes are query the ap name

**Comment by garnier-quentin** [comment]
If the ap description is empty, i use the ap serial number.
