### ISSUE TITLE
MSSQL - Add possibility to set thresold on reserved 

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#1939]
Est-il possible pour la sonde MSSQL de superviser l'espace maximum que pourra prendre une base de données dans le cadre d une base en auto extend ?

Je ne souhaite pas l occupation par rapport a taille actuelle de la partition mais bien par rapport a la taille maximum reservable pour la base de données
Dans la sonde, la commande sp-spaceused est utilisée.

Cela correspondrait au champ resérvé.

Merci d'avance pour votre retour

**Comment by Sims24** [comment]
Duplicate of https://github.com/centreon/centreon-plugins/issues/723
