### ISSUE TITLE
Cisco Meraki Device usage SNMP critical output bug

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#1944]
Hi,

I´m using the latest centreon plugin release. I think at the critical status reporting output of cisco meraki SNMP module device usage there is a little bug, because icinga tells me every time the following status: 

`Use of uninitialized value in concatenation (.) or string at /home/nagios/centreon-plugins/network/cisco/meraki/cloudcontroller/snmp/mode/deviceusage.pm line 213.`

My icinga command call looks like:

```
object CheckCommand "centreon-meraki-device-usage" {
   import "plugin-check-command"

   command = [ "/home/nagios/centreon-plugins/centreon_plugins.pl"]
   arguments = {
        "--plugin" = "network::cisco::meraki::cloudcontroller::snmp::plugin"
        "--mode" = "device-usage"
        "--hostname" = "$address$"
        "--snmp-version" = "$snmp_version$"
        "--snmp-port" = "$snmp_port$"
        "--snmp-community" = "$snmp_community$"
        "--warning-clients" = "$snmp_warn$"
        "--critical-clients" = "$snmp_crit$"
        "--range-perfdata" = "1"
        }
}
```
What can the cause for this error output?

**Comment by garnier-quentin** [comment]
Meraki SNMP is very buggy. Could you try to launch the command with following options ?
--snmp-force-getnext --subsettable=0 --subsetleef=0

Also you can try the plugin meraki with the rest api.

**Comment by benhartwich** [comment]
Thanks, then I get: argument 0 alone at /home/nagios/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 93.

**Comment by garnier-quentin** [comment]
Could you show me the command line ?

**Comment by benhartwich** [comment]
Ah, a little mistake - the icinga implementation should look like: 

```
object CheckCommand "centreon-meraki-device-usage" {
   import "plugin-check-command"

   command = [ "/home/nagios/centreon-plugins/centreon_plugins.pl"]
   arguments = {
        "--plugin" = "network::cisco::meraki::cloudcontroller::snmp::plugin"
        "--mode" = "device-usage"
        "--hostname" = "$address$"
        "--snmp-version" = "$snmp_version$"
        "--snmp-port" = "$snmp_port$"
        "--snmp-community" = "$snmp_community$"
        "--warning-clients" = "$snmp_warn$"
        "--critical-clients" = "$snmp_crit$"
        "--range-perfdata" = "1"
        "--snmp-force-getnext" = ""
        "--subsettable=0" = ""
        "--subsetleef=0" = ""
        }
}
```

**Comment by garnier-quentin** [comment]
It's working with that options ?

**Comment by benhartwich** [comment]
Yes

**Comment by garnier-quentin** [comment]
Perfect. Thanks for the feedback
