### ISSUE TITLE
Omniswitch spanning tree modes

### ISSUE THREAD

**Issue by trentasis** [centreon/centreon-plugins#1946]
Hi,

We are using latest version centreon-pluign to monitor omniswitch and is working great to monitor cpu, mem, hardware,.. https://github.com/centreon/centreon-plugins/blob/dccdc34b0a97949526aa1b73174287f04fa19f3c/network/alcatel/omniswitch/snmp/plugin.pm

But we have problems with two modes related with spanning tree:
1.- mode: list-spanning-trees

 perl centreon_plugins.pl --hostname=192.168.2.230 --plugin=network::alcatel::omniswitch::snmp::plugin --snmp-version=2c --snmp-community=community --mode=list-spanning-trees
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 121.
Use of uninitialized value in sprintf at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 136.
Use of uninitialized value in sprintf at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 136.
Use of uninitialized value in sprintf at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/listspanningtrees.pm line 136.
List ports with Spanning Tree Protocol:
[port = unknown] [state = forwarding] [op_status = ] [admin_status = ] [index = ]
[port = Alcatel-Lucent 1/1 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1001]
[port = Alcatel-Lucent 1/3 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 1003]
[port = Alcatel-Lucent 1/4 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 1004]
[port = Alcatel-Lucent 1/5 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1005]
[port = Alcatel-Lucent 1/6 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1006]
[port = Alcatel-Lucent 1/7 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 1007]
[port = Alcatel-Lucent 1/8 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1008]
[port = Alcatel-Lucent 1/9 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1009]
[port = Alcatel-Lucent 1/10 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 1010]
[port = Alcatel-Lucent 1/13 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1013]
[port = Alcatel-Lucent 1/14 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1014]
[port = Alcatel-Lucent 1/15 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1015]
[port = Alcatel-Lucent 1/16 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1016]
[port = Alcatel-Lucent 1/17 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1017]
[port = Alcatel-Lucent 1/18 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1018]
[port = Alcatel-Lucent 1/19 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1019]
[port = Alcatel-Lucent 1/20 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1020]
[port = Alcatel-Lucent 1/21 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1021]
[port = Alcatel-Lucent 1/22 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1022]
[port = Alcatel-Lucent 1/23 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1023]
[port = Alcatel-Lucent 1/24 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 1024]
[port = Alcatel-Lucent 2/5 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 2005]
[port = Alcatel-Lucent 2/6 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2006]
[port = Alcatel-Lucent 2/7 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 2007]
[port = Alcatel-Lucent 2/9 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 2009]
[port = Alcatel-Lucent 2/10 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2010]
[port = Alcatel-Lucent 2/11 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 2011]
[port = Alcatel-Lucent 2/12 6.4.2.807.S01] [state = forwarding] [op_status = up] [admin_status = up] [index = 2012]
[port = Alcatel-Lucent 2/14 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2014]
[port = Alcatel-Lucent 2/15 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2015]
[port = Alcatel-Lucent 2/16 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2016]
[port = Alcatel-Lucent 2/17 6.4.2.807.S01] [state = disabled] [op_status = down] [admin_status = up] [index = 2017]
[port = Alcatel-Lucent 2/18 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2018]
[port = Alcatel-Lucent 2/19 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2019]
[port = Alcatel-Lucent 2/20 6.4.2.807.S01] [state = forwarding] [op_status = down] [admin_status = up] [index = 2020]

2.- mode spanning-tree
 perl centreon_plugins.pl --hostname=192.168.2.230 --plugin=network::alcatel::omniswitch::snmp::plugin --snmp-version=2c --snmp-community=community --mode=spanning-tree
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
Use of uninitialized value in hash element at /usr/local/nagios/libexec/centreon-plugins/snmp_standard/mode/spanningtree.pm line 171.
OK: All spanning trees are ok |

switch has firmware  6.4.2.807.S01 GA

why this two modes related with spanning tree are not working?

thanks!

**Comment by garnier-quentin** [comment]
I need a snmpwalk of following branch:
snmpwalk -ObentU -v 2c -c public IP_ADDR .1.3.6.1.2.1.17 > spanning_tree.snmpwalk

**Comment by trentasis** [comment]
Hi,

first of all thanks for your answer.

Attached output, 
 snmpwalk -ObentU -v 2c -c community IP .1.3.6.1.2.1.17   > /tmp/spanning_tree.snmpwalk
Error in packet.
Reason: (genError) A general failure occured
Failed object: .1.3.6.1.2.1.17.7.1.4.5.1.4.152

Attached file, but see that has returned an error

both errors spanning tree are from same equipment, this attached snmpwalk

**Comment by garnier-quentin** [comment]
No problem for the error. I don't go to that branch. Sorry but i also need following branch:
.1.3.6.1.2.1.2.2.1

**Comment by trentasis** [comment]
hi,

No problem, attached a second output.
One question, can you give details about features of this two spanning tree modes, I liek to understand real usage and I like to know if only is information or also allow to show any warning, critical or cahnge on topology

thanks

[spanning_tree2.zip](https://github.com/centreon/centreon-plugins/files/4498519/spanning_tree2.zip)

**Comment by garnier-quentin** [comment]
you could try it. it should be ok now

**Comment by trentasis** [comment]
hi,

Perfect seems that works, no errors are reported! Great!

One last question, now we are receiving this alert with
mode --mode=spanning-tree
CRITICAL: Port 'Alcatel-Lucent 1/23 6.3.4.411.R01' spanning tree state is
'blocking' [op status: 'up'] [admin status: 'up'] [index: '1023']

This alert is received on multiple switches is this right? I'm not sure how
is working this mode/check can you give details if this is a bad usage or
check or I have to make some action to solve this alert on my networking
environment?

thanks

Missatge de qgarnier <notifications@github.com> del dia dj., 23 d’abr. 2020
a les 11:24:
