### ISSUE TITLE
[MSSQL] [database::mssql::mode::*] Possibility to add options to set transaction isolation level

### ISSUE THREAD

**Issue by jumakasy** [centreon/centreon-plugins#1949]
Hi all,

In order to get  the monitoring queries have a less impact in other transactions in terms of locking and blocking, I have been setting the TRANSACTION ISOLATION LEVEL by modifying the centreon's code.

I have been using the code modified successfully, mitigating blocks issues in databases of intensive use.

I think it will be a good enhancement to include this options in the mssql code. For example, in the databasessize.pm I have used this mod:

Original:
https://github.com/centreon/centreon-plugins/blob/7b50b892616b4be9737e728a145a9ff4f2e9322c/database/mssql/mode/databasessize.pm#L151

Mod:
```
$self->{sql}->query(query => "use [" . $$database[0] . "]; SET TRAN ISOLATION LEVEL READ UNCOMMITTED ;exec sp_spaceused;");
```
In this link from Microsoft you can get detailed info: https://docs.microsoft.com/en-us/sql/t-sql/statements/set-transaction-isolation-level-transact-sql?view=sqlallproducts-allversions

From the link:
 > Transactions running at the READ UNCOMMITTED level do not issue shared locks to prevent other transactions from modifying data read by the current transaction. READ UNCOMMITTED transactions are also not blocked by exclusive locks that would prevent the current transaction from reading rows that have been modified but not committed by other transactions. 

I really think it's a "quickwin" to have this option, so if you could consider to add it would be great.

Best regards.

**Comment by garnier-quentin** [comment]
I can add a global option to launch a custom request after the connection. Seems ok for you ?

**Comment by jumakasy** [comment]
Yes, that would be ok.
Thanks!

**Comment by moix** [comment]
Will that be also available for other databases? I was looking similar to introduce custom options while connecting

**Comment by garnier-quentin** [comment]
It could be

**Comment by garnier-quentin** [comment]
Sorry for the delay. There is a new option: ```--connect-query='xxx'```

**Comment by jumakasy** [comment]
Thank you so much @garnier-quentin. I will check it :)
