### ISSUE TITLE
os::linux::snmp::plugin mode processcount  no critical state

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#195]
Hello,

I am trying to monitor my servers, I want to check is the process puppet is running. I am not able to use the critical option to get critical status : 
<code>./centreon_plugins.pl  --plugin=os::linux::snmp::plugin --mode=processcount --hostname=192.168.1.1   --snmp-version=3  --snmp-username=username --authpassphrase=password --authprotocol=SHA --privpassphrase=password --privprotocol=AES --process-name puppet  --critical=1
OK: Number of current processes running: 0 | 'nbproc'=0;;0:1;0;</code>

If I restart the process : 

<code>./centreon_plugins.pl  --plugin=os::linux::snmp::plugin --mode=processcount --hostname=192.168.1.1   --snmp-version=3  --snmp-username=username --authpassphrase=password --authprotocol=SHA --privpassphrase=password --privprotocol=AES --process-name puppet  --critical=1
OK: Number of current processes running: 0 | 'nbproc'=1;;0:1;0;</code>

I want to be in critical state when the process is not running.

Hugo

**Comment by garnier-quentin** [comment]
You were close ;) : --critical=1:

**Comment by hdep** [comment]
Seems to works, I don't really understand why there is a need for ":" character.
Maybe you should add this information in the --help screen. 

Anyway, thank you for your help !

**Comment by garnier-quentin** [comment]
Please read the guidelines: https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
