### ISSUE TITLE
[apps::protocols::dns::plugin] - howto reverse DNS

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1952]
I would like to check a reverse DNS entry with an expected answer like
```
/usr/lib/centreon/plugins/fatpack/apps-protocols-dns.pl --plugin=apps::protocols::dns::plugin --nameservers=8.8.8.8 --mode=request  --search=8.8.8.8 --expected-answer='dns.google'
CRITICAL: No result values match expected answer (answer: 8.8.8.8.in-addr.arpa) | 'time'=0.004s;;;;
```

The problem is that I can only check versus the in-addr.arpa return, but not for the name:
```
nslookup 8.8.8.8
8.8.8.8.in-addr.arpa    name = dns.google.
```

Is there a way to do this?

**Comment by garnier-quentin** [comment]
Could you add that option ? --search-type=PTR

**Comment by joschi99** [comment]
I tried this also with option PTR, but nothing will change (as I know PTR is the default searchtype probably)

./centreon_plugins.pl --plugin=apps::protocols::dns::plugin --nameservers=8.8.8.8 --mode=request  --search=8.8.8.8 --expected-answer='dns.google' --search-type=PTR
CRITICAL: No result values match expected answer (answer: 8.8.8.8.in-addr.arpa) | 'time'=0.004s;;;;

Regards

**Comment by garnier-quentin** [comment]
I have done a patch. Try following option: --use-ptr-fqdn

**Comment by joschi99** [comment]
Have done some test, seem's working
