### ISSUE TITLE
Telegram notification

### ISSUE THREAD

**Issue by ski31** [centreon/centreon-plugins#1955]
Hello, 

I try to config notification plugin with Telegram. So I have tested this command directly on my server : 

`./centreon_plugins.pl --plugin=notification::telegram::plugin --mode=alert`

She return : 

`UNKNOWN: Cannot load module --mode.
Can't locate JSON/XS.pm in @INC (@INC contains: /usr/lib/centreon/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/notification/telegram/mode/alert.pm line 28.
BEGIN failed--compilation aborted at /usr/lib/centreon/plugins/notification/telegram/mode/alert.pm line 28.
Compilation failed in require at /usr/lib/centreon/plugins/centreon/plugins/misc.pm line 222.`

I'm lost about it. I not found doc or notice about this plugin. If someone have a solution, I will be grateful. 

Thanks

**Comment by garnier-quentin** [comment]
You need to install the module Perl. On centos:
```
# yum install 'perl(JSON::XS)'
```

**Comment by ski31** [comment]
Effectively..., thanks !

**Comment by garnier-quentin** [comment]
thanks for the feedback!
