### ISSUE TITLE
network::paloalto::ssh::plugin

### ISSUE THREAD

**Issue by lamerguez** [centreon/centreon-plugins#1957]
Hi,

When centreon_plugins.pl --plugin network::paloalto::ssh::plugin --mode=environment --component=temperature --hostname=XXXXXX --ssh-username=XXXX  --critical='temperature,.*,60'

Message:             
CRITICAL: temperature 'DP0 Core' is 70.4 C UNKNOWN: Not an ARRAY reference at /usr/lib/centreon/plugins/centreon-plugins/network/paloalto/ssh/mode/components/temperature.pm line 34. 

Any idea why this error message about array reference.

It's about a palo alto PA-5220

Thank's

**Comment by garnier-quentin** [comment]
You are lucky i'm working on it right now ;)
Need the result of following command please:
```
set cli op-command-xml-output on
show system environmentals
````

Moreover, could you provide me the result of (can be email):
```
show vpn ike-sa
set cli op-command-xml-output on
show vpn ike-sa
```

**Comment by lamerguez** [comment]
Hi!

Many thank's.

I send you the xml file.


Mathieu.

**Comment by garnier-quentin** [comment]
I didn't received results by email.

**Comment by garnier-quentin** [comment]
Maybe i found the issue. But i still need outputs.

**Comment by lamerguez** [comment]
Oh sorry, maybe filter by  relay..

I send you in a zip file.

**Comment by garnier-quentin** [comment]
Still not get it. That's txt file. Don't understand how it can be filtered.. my address is qgarnier@centreon.com

**Comment by lamerguez** [comment]
Sorry, I was replying to @reply.github.com instead of your adress!  :(

**Comment by lamerguez** [comment]
Thank's

some errors :

Use of uninitialized value in concatenation (.) or string at
/usr/lib/centreon/plugins/centreon-plugins/network/paloalto/ssh/mode/
ipsec.pm line 78.
Use of uninitialized value in concatenation (.) or string at
/usr/lib/centreon/plugins/centreon-plugins/network/paloalto/ssh/mode/
ipsec.pm line 78.
OK: All ipsec tunnels are ok | 'tunnels.ipsec.total.count'=0;;;0;

**Comment by garnier-quentin** [comment]
thanks for the feedback. i have fixed. could you test it again ?

**Comment by lamerguez** [comment]
something's strange:

CRITICAL: Tunnel ipsec 'IKE_GW-EHESS-VPN-EHESS' state: init [monitor
status: off][ike phase1 state: up] | 'tunnels.ipsec.total.count'=2;;;0;

**Comment by garnier-quentin** [comment]
Could you provide me the result of the command:
```
set cli op-command-xml-output on
show vpn ike-sa
show vpn flow
```

Thanks
