### ISSUE TITLE
[snmp_standard::plugin] mode string-value

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#196]
Hello,

Should it be possible to add an "other value" in the --map-values option ?

I have a case where the value returned is 0 if it's OK and any other INTEGER value if it's CRITICAL, the value correspond to an ERROR CODE.

I've tried this but that's not work when value is other than 0 :
--mode=string-value --oid=.1.3.6.1.4.1.6101.1.2.2.2.0 --format="%s" --critical-regexp='^(?!(0)$)' --map-values='0=>File Reputation service is working correctly,^(?!(0)$)=>File Reputation service error code is %s' --regexp-map-values

Thanks

**Comment by garnier-quentin** [comment]
I'll work on it soon. So i'll put your demand.

**Comment by garnier-quentin** [comment]
Ref #228
