### ISSUE TITLE
Critical hardware alert alcatel  OS6450

### ISSUE THREAD

**Issue by trentasis** [centreon/centreon-plugins#1961]
Hi,

We have detected some alerts about hardware mode  with alcatel:
1.- for example with OS6450-48
CRITICAL: fan 'Virtual Chassis/48 10/100/1000 + 2 10G + 2 1/10G STK/UPLINK/569.2' status is notRunning UNKNOWN: fan 'Virtual Chassis/48 10/100/1000 + 2 10G + 2 1/10G STK/UPLINK/569.4' status is noStatus - fan 'Virtual Chassis/48 10/100/1000 + 2 10G + 2 1/10G STK/UPLINK/569.3' status is noStatus 
[os645048.zip](https://github.com/centreon/centreon-plugins/files/4524839/os645048.zip)

2.- for example  OS6450-24
UNKNOWN: fan 'Chassis/Chassis/569.2' status is noStatus - fan 'Chassis/Chassis/569.1' status is noStatus - fan 'Chassis/Chassis/569.4' status is noStatus - fan 'Chassis/Chassis/569.3' status is noStatus 
[os645024.zip](https://github.com/centreon/centreon-plugins/files/4524859/os645024.zip)

3.- for example  OS6450-P24
  | UNKNOWN: fan 'Chassis/Chassis/569.4' status is noStatus
[os6450P24.zip](https://github.com/centreon/centreon-plugins/files/4524878/os6450P24.zip)

Attached snmpwalk

Thanks!

**Comment by garnier-quentin** [comment]
If it's not an issue for you. you can coverload the threshold:
```
--threshold-overload='fan,noStatus,OK'
```

**Comment by trentasis** [comment]
hi,

tryin with this 
--mode=hardware --threshold-overload='fan,OK,noStatus'
UNKNOWN: Wrong threshold-overload section 'fan,OK,noStatus'.
is not woking

What is wrong?

**Comment by trentasis** [comment]
Also tried  this but without success:

# perl centreon_plugins.pl --hostname=192.168.2.215 --plugin=network::alcatel::omniswitch::snmp::plugin --snmp-version=2c --snmp-community=FSE --mode=hardware --threshold-overload='fan.oper,OK,noStatus' --verbose
UNKNOWN: fan 'Chassis/Chassis/569.2' status is noStatus - fan 'Chassis/Chassis/569.1' status is noStatus - fan 'Chassis/Chassis/569.4' status is noStatus - fan 'Chassis/Chassis/569.3' status is noStatus | 'power_569'=40W;;;0; 'power_65'=40W;;;0; 'power_1'=40W;;;0; 'power_97'=65W;;;0; 'count_chassis'=1;;;; 'count_fan'=4;;;; 'count_module'=2;;;; 'count_psu'=1;;;;
Checking backplane
Checking chassis
chassis 'Chassis/Chassis' [instance: 569, admin status: powerOn] operationnal status is up.
Checking container
Checking fan
fan 'Chassis/Chassis' [instance: 569.2] status is noStatus
fan 'Chassis/Chassis' [instance: 569.1] status is noStatus
fan 'Chassis/Chassis' [instance: 569.4] status is noStatus
fan 'Chassis/Chassis' [instance: 569.3] status is noStatus
Checking module
module 'CMM-1/CMM' [instance: 65, admin status: powerOn] operationnal status is up.
module 'NI-1/24 10/100/1000 + 2 10G + 2 1/10G STK/UPLINK' [instance: 1, admin status: powerOn] operationnal status is up.
Checking other
Checking port
Checking power supplies
power supply 'PS-1/OS 65W AC Power Supply' [instance: 97, admin status: powerOn] operationnal status is up.
Checking sensors
Checking stack
Checking unknown

**Comment by trentasis** [comment]
Hi,

Adding this --mode=hardware --filter=fan,569.*

seems to work, but not really sure if this is a the right way to use this hardware check

thanks

**Comment by garnier-quentin** [comment]
Sorry. Could you try:
```
--mode=hardware --threshold-overload='fan.status,OK,noStatus'
```

**Comment by trentasis** [comment]
same output, fails:

 --mode=hardware  --threshold-overload='fan.status,OK,noStatus'
CRITICAL: fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/569.2' status is notRunning | 'power_569'=63W;;;0; 'power_65'=63W;;;0; 'power_1'=63W;;;0; 'power_97'=90W;;;0; 'power_98'=90W;;;0; 'count_chassis'=1;;;; 'count_fan'=4;;;; 'count_module'=2;;;; 'count_port'=2;;;; 'count_psu'=2;;;;

**Comment by garnier-quentin** [comment]
It removes only the 'noStatus'. For the notRunning, you can overload also or filter the instance.

**Comment by trentasis** [comment]
Great, thanks!
