### ISSUE TITLE
storage::ibm::storwize::ssh::plugin --ssh-option no more available

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-plugins#1963]
Hi,

I updated my plugins yesterday and the plugin storage::ibm::storwize::ssh::plugin doesn't work anymore.

My poller connects in SSH with a public key to the SAN.
I used to check this hardware with this command:
`/usr/lib/centreon/plugins//centreon_plugins.pl --plugin=storage::ibm::storwize::ssh::plugin --mode=components --hostname=192.168.x.x --ssh-option='-l=centreon' --verbose`

`Unknown option: ssh-option at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.`

I noticed new options in help so I tested this:
`/usr/lib/centreon/plugins//centreon_plugins.pl --plugin=storage::ibm::storwize::ssh::plugin --mode=components --hostname=192.168.x.x --ssh-username=centreon --ssh-priv-key="/var/lib/centreon-engine/.ssh/id_dsa" --verbose `

`UNKNOWN: Command error: command-line: line 0: Bad configuration option: batchmode yes`

Am I doing it wrong or is this a bug?

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by Cool34000** [comment]
Hi Quentin,

It's fixed but I found another bug!
If I run the command with centreon-engine, the bug if fixed as I have already accepted the SSH fingerprint.
But if I run it as root (so with the need specify the StrictHostKeyChecking option as I never connected with this user), it's still broken:
`/usr/lib/centreon/plugins//centreon_plugins.pl --plugin=storage::ibm::storwize::ssh::plugin --mode=components --hostname=192.168.x.x --ssh-username=centreon --ssh-priv-key="/var/lib/centreon-engine/.ssh/id_dsa" --sshcli-option='-o=StrictHostKeyChecking=no'`

`Unknown option: sshcli-option at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67`

**Comment by garnier-quentin** [comment]
It should be fixed. thanks

**Comment by Cool34000** [comment]
Yes it is fixed...
Many thanks to you: quick and effective as always!

**Comment by garnier-quentin** [comment]
thanks for your feedbacks!
