### ISSUE TITLE
AWS Elb application target Health

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#1968]
Hi all,
im facing some issue configuring elb application target health check

/usr/lib/centreon/plugins/centreon_aws_elb_application_api.pl --plugin=cloud::aws::elb::application::plugin --mode=targets-health --custommode='awscli' --aws-secret-key='***' --aws-access-key='***' --region='***' --name='app/xxxx/dc929ed074af115e' --proxyurl=''  --filter-metric='HealthyHostCount' --statistic='sum' --timeframe='900' --period='60' --warning-unhealthyhostcount='' --critical-unhealthyhostcount='' --warning-healthyhostcount='@0:1' --critical-healthyhostcount='@0:0'

using --debug switch

Command line: 'aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ApplicationELB --metric-name 'HealthyHostCount' --start-time 2020-04-27T22:25:16 --end-time 2020-04-27T22:40:16 --period 60 --statistics Sum --output json --dimensions 'Name=LoadBalancer,Value=app/xxxx/dc929ed074af115e' --debug'

i still receive 

UNKNOWN: No metrics. Check your options or use --zeroed option to set 0 on undefined values

But i notice it's missing targetgroup dimensions to get correct metric result and if i execute same command with cloud watch it works

/usr/lib64/nagios/centreon-plugins/centreon_plugins.pl --plugin=cloud::aws::cloudwatch::plugin --mode=get-metrics --custommode=awscli --region=eu-west-1 --namespace=AWS/ApplicationELB --metric=HealthyHostCount --dimension=TargetGroup=targetgroup/xxxx/677a0402e35fa8ce --dimension=LoadBalancer=app/xxxx/dc929ed074af115e --statistic=average --warning-metric=@0:0 --critical-metric=@0:0

return

OK: Metric 'LoadBalancer.app/xxxx/dc929ed074af115e-TargetGroup.targetgroup/xxxx/677a0402e35fa8ce_HealthyHostCount_average' value is 1

Thanks

**Comment by Sims24** [comment]
Hi @R00T88 , 

Thanks for your feedback. 

Can you confirm that other modes have the same issue please ? 

I will push a fix to add TargetGroupe as a dimension. Just want to know if it is needed on all modes. That what I understand from https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html#load-balancer-metric-dimensions-alb

Simon

**Comment by Sims24** [comment]
@R00T88 you can use ```--target-group``` option. I added it. 

Could you confirm it's OK? 

If you feel like it has to be mandatory with elbv2, just let me know and I will add a check to force option usage.

**Comment by R00T88** [comment]
@Sims24 it's ok now i think should be mandatory only on target health check on other it's not needed

**Comment by Sims24** [comment]
Thanks for your feedback, we will set it at mandatory for this mode.
