### ISSUE TITLE
Aruba Standard Plugin not working with a 2530-48G-PoeP

### ISSUE THREAD

**Issue by ChristophePelichet** [centreon/centreon-plugins#1970]
Dear Teams , 

The last plugin for aruba switch is not working with my aruba 2530-48G-PoeP

the hardware mode respond " OK: All 0 components are ok []"
The other mode respond : "UNKNOW: SNMP Table Request: Cant get a single value.

Firmware to my switch :  YA 16.04.0016
Hp Aruba Firmware and Mibs : 
https://h10145.www1.hpe.com/downloads/SoftwareReleases.aspx?ProductNumber=J9772A

[snmpwalk_aruba.txt](https://github.com/centreon/centreon-plugins/files/4545633/snmpwalk_aruba.txt)

**Comment by garnier-quentin** [comment]
You can use: network::hp::procurve::snmp::plugin
