### ISSUE TITLE
[network::cyberoam::snmp::plugin] Sophos XG - mode interfaces not working

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#1971]
On a Sophos XG Firewall the modes list-interfaces and interfaces is not working
`UNKNOWN: Can't get interfaces...`

All other modes from cyberoam are working correctly

SNMP walk:
[sophos-xg.txt](https://github.com/centreon/centreon-plugins/files/4550812/sophos-xg.txt)

**Comment by Sims24** [comment]
Hi @joschi99 

Did you try modifying --oid-filter and --oid-display options ?

**Comment by joschi99** [comment]
Hi @garnier-quentin,
with options --oid-filter=ifDesc --oid-display=ifDesc --snmp-autoreduce is working.

Thanks
