### ISSUE TITLE
Certificate check fail

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#1972]
Hi all,
im trying to check certificate validity but cannot get it working

./centreon_protocol_x509.pl --mode=certificate --hostname=xxxx --port=443 --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --debug --verbose

Return always 
UNKNOWN: SSL error: SSL wants a read first

if i don't specify --ssl-opt i receive same error + error in line 141

*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 possibly with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at ./centreon_protocol_x509.pl line 141.
UNKNOWN: SSL error: SSL wants a read first

Can you help me?

Thanks

**Comment by garnier-quentin** [comment]
I think it comes from a module bug. Try to test it on a new debian for example.

**Comment by R00T88** [comment]
@garnier-quentin i'm testing it on CentOS Linux release 7.7.1908 (Core)

**Comment by garnier-quentin** [comment]
IO::Socket::SSL is quite old on centos 7.7

**Comment by R00T88** [comment]
@garnier-quentin this is the package installed --> 

Package perl-IO-Socket-SSL-1.94-7.el7.noarch already installed and latest version

**Comment by UrBnW** [comment]
Yes I confirm you need a newer `IO-Socket-SSL` module than the one CentOS 7 brings...
Install your own version (https://metacpan.org/pod/IO::Socket::SSL) and it will run flawlessly :+1:

**Comment by R00T88** [comment]
@garnier-quentin @UrBnW 
upgrading it work perfect!

Thanks

**Comment by garnier-quentin** [comment]
thanks for the feedback
