### ISSUE TITLE
[apps::backup::veeam::local::plugin] Outdated in NSClient Agent

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-plugins#1976]
Hi,

I'm trying VeeamBackup plugin and the plugin returns these strange values:
```
Argument "1588188642,333" isn't numeric in numeric lt (<) at C:\Windows\TEMP\par-5352562d48595045525624\cache-f55e56d520432b5534dd558116fb4d09e12bb9c2\inc\lib/apps/backup/veeam/local/mode/jobstatus.pm line 257.
Argument "1588186817,703" isn't numeric in subtraction (-) at C:\Windows\TEMP\par-5352562d48595045525624\cache-f55e56d520432b5534dd558116fb4d09e12bb9c2\inc\lib/apps/backup/veeam/local/mode/jobstatus.pm line 269.
OK: Total Jobs : 1 - Job 'Sauvegarde des VMs' status : Success [type: Backup] | 'total'=1;;;0;
```
I've downloaded Centreon's NSClient Agent x64 [here](https://download.centreon.com/?action=product&product=agent-nsclient&version=0.51&secKey=59d646114079212e03ec09454456a938) (version 051-1.0-2)
According to #1202, this version has this bug.
Can I download an up to date version elsewhere?

**Comment by garnier-quentin** [comment]
the github is now open and free!! go here: https://github.com/centreon/centreon-nsclient-build

**Comment by Cool34000** [comment]
> 
> 
> the github is now open and free!! go here: https://github.com/centreon/centreon-nsclient-build
> you'll get a centreon_plugins.exe up to date.

I don't see any EXE or MSI... Do I need to compile my self?

**Comment by Sims24** [comment]
@Cool34000 https://github.com/centreon/centreon-nsclient-build/tree/master/resources/scripts/x64/centreon

The complete Centreon-NSClient++ exe will be on download.centreon.com soon.

**Comment by ginjan** [comment]
Hello,
I have the same problem and I cannot find the .exe.
The link is broken, I cannot use it. ( https://github.com/centreon/centreon-nsclient-build/tree/master/resources/scripts/x64/centreon )

Can you help me.
Thank you in advance,

Regards,

**Comment by garnier-quentin** [comment]
The link: https://github.com/centreon/centreon-nsclient-build/releases/tag/20201207190634

**Comment by ginjan** [comment]
Thank you.
