### ISSUE TITLE
apps::tomcat::web::plugin Mode Connectors

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#1978]
Hi all,
im using mode connector of tomcat web plugin and it works fine

/usr/lib64/nagios/centreon-plugins-new/centreon_plugins.pl --plugin=apps::tomcat::web::plugin --mode=connectors --hostname=XXX --port 8080 --username=XXX --password=XXX --basic --credentials --proto http --filter-name=ajp-bio-8009 --warning-threads-current=800 --critical-threads-current=900

Result:

OK: Connector 'ajp-bio-8009' Threads Current : 40, Threads Busy : 40, Traffic In : 0.08b/s (- on -), Traffic Out : 861.81b/s (- on -), Requests Total Processing Time : 159 ms, Requests Errors : 0, Requests Total : 1

It is possibile to filter for metric too?
For example get only Threads or Traffic instead all counters?

Thanks

**Comment by Sims24** [comment]
Hello @R00T88 

Yep, use the filter-counters option. Like this: 

```--filter-counters='^(thread|traffic)'```

Simon
