### ISSUE TITLE
Switch Dell Networking X1000 series

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-plugins#1979]
Hi,

I'm trying to monitor 2 Dell Networking X1000 series switches (a X1054 and a X1026P)
Using a mix of existing Dell Networking plugins, I'm able to monitor:
- Status (network::dell::n4000::snmp::plugin)
- Interfaces (network::dell::n4000::snmp::plugin)
- Uptime (network::dell::os10::snmp::plugin)

I'd love to have hardware, cpu, memory and load working...
I've attached MIBs but the snmpwalk export was taking too much time so I stopped it (30 minutes and 28MB!)
Can you help on which OID I need to export?

[MIBs.zip](https://github.com/centreon/centreon-plugins/files/4564275/MIBs.zip)

**Comment by garnier-quentin** [comment]
Could you tell me which kind of operating system ? (DNOS 9.X, OS10,...) It seems maybe Marvel (and so radlan).

**Comment by garnier-quentin** [comment]
You can provide me that branch:
.1.3.6.1.4.1.89

**Comment by Cool34000** [comment]
I can't find any OS information even in CLI:
```
#show version
SW version    3.0.0.94 ( date  10-Sep-2017 time  22:31:38 )
Boot version    1.0.0.25 ( date  05-Apr-2017 time  09:55:19 )
HW version    00.00.04
```

```
#show system
System Description:                       Dell Networking X1052 1-10Gb Switch
System Type:                              X1052
System Up Time (days,hour:min:sec):       105,02:21:32
System Contact:                           myContact
System Name:                              myName
System Location:                          myLocation
System MAC Address:                       68:4f:64:xx:xx:xx
System Object ID:                         1.3.6.1.4.1.674.10895.3073

Fan 1 Status:                             OK


          Unit            Temperature (Celsius)            Status
------------------------ ------------------------ ------------------------
           1                        37                       OK
```
snmpwalk is running since 1:40 hour... Still running lol (48MB and counting)

**Comment by garnier-quentin** [comment]
What could you monitor with os::linux::snmp::plugin ?

**Comment by Cool34000** [comment]
Fully working modes:
* arp
* interfaces
* list-interfaces
* uptime

Some modes are working but are returning empty values ("0"):
* processcount
* tcpcon
* udpcon

snmpwalk is still running with 60MB...

**Comment by garnier-quentin** [comment]
I think you can stop. it's a radlan.

**Comment by garnier-quentin** [comment]
Could you try the plugin: --plugin=network::dell::xseries::snmp::plugin

**Comment by Cool34000** [comment]
> 
> 
> Could you try the plugin: --plugin=network::dell::xseries::snmp::plugin

All is working fine
Thanks Quentin

**Comment by garnier-quentin** [comment]
nice. thanks for the feedback
