### ISSUE TITLE
[apps::protocols::ldap::plugin] ldap-connect-options > Problem with character "="

### ISSUE THREAD

**Issue by LeDistordu** [centreon/centreon-plugins#198]
Command :

<code>$USER1$/centreon_plugins.pl --hostname $HOSTADDRESS$ --plugin=apps::protocols::ldap::plugin --mode=login --username=$_HOSTLDAPUSERNAME$ --password=$_HOSTLDAPPASSWORD$ --ldap-connect-options=$_HOSTLDAPCONNECT$</code>

In host :

LDAPCONNECT = sheme=ldaps
LDAPUSERNAME = toto
LDAPPASSWORD = hide

my command works perfectly in command line but I have a problem with "sheme=ldaps" in centreon's interface

I try escaping character like that : sheme\=ldaps or sheme\\=ldaps but no way...

I also try quote : --ldap-connect-options='$_HOSTLDAPCONNECT$'

**Comment by garnier-quentin** [comment]
I have done the test and it works. You need to protect it with quote:
$USER1$/centreon_plugins.pl --hostname $HOSTADDRESS$ --plugin=apps::protocols::ldap::plugin --mode=login --username='$_HOSTLDAPUSERNAME$' --password='$_HOSTLDAPPASSWORD$' --ldap-connect-options=$_HOSTLDAPCONNECT$

**Comment by garnier-quentin** [comment]
You should put it in centreon github. If it works well in command line ;)
