### ISSUE TITLE
Centos and redhat 7 only check memory 

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#1980]
#  Question

Hi,

using centreon-plugins-20200410, I got a wrong alerts for MEMORY on Centos / rhl 7.x
They are all in critical state, hence assuming memory usage is more than 90%.

I use the following command : 

```
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=memory --hostname=server --snmp-version=3 --snmp-username=username--authpassphrase=*** --authprotocol=sha --privpassphrase=**** --privprotocol=aes --redhat --warning-usage=80 --critical-usage=90
CRITICAL: Ram Used : 94.12 % | 'used'=7719321600B;;;0;8201334784 'free'=482013184B;;;0;8201334784 'used_prct'=94.12%;0:80;0:90;0;100 'buffer'=53649408B;;;0; 'cached'=6886756352B;;;0; 'shared'=26513408B;;;0;
```

When I remove the redhat flag :  
`OK: Ram Total: 7.64 GB Used (-buffers/cache): 771.54 MB (9.86%) Free: 6.88 GB (90.14%), Buffer: 51.23 MB, Cached: 6.42 GB, Shared: 25.29 MB | 'used'=809021440B;;;0;8201334784 'free'=7392313344B;;;0;8201334784 'used_prct'=9.86%;0:80;0:90;0;100 'buffer'=53723136B;;;0; 'cached'=6888288256B;;;0; 'shared'=26513408B;;;0;`

My system free output is : 
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           7821         721         480          25        6619        6776
Swap:          2047         718        1329

```

I know that if I don't use the redhat flag, at some point output will be wrong. 
For me the usedn here is 721MB.

What do you think ?

**Comment by garnier-quentin** [comment]
I think you didn't look very well ;)
https://github.com/centreon/centreon-plugins/issues?q=is%3Aissue+memory+redhat

**Comment by joschi99** [comment]
Have same problem on CentOS 7.8 with Plugins 20200410:

```
centreon_plugins.pl --hostname=127.0.0.1 --snmp-community=xxx --snmp-version=2c --snmp-username= --authpassphrase=*** --authprotocol= --privpassphrase=*** --privprotocol= --plugin=os::linux::snmp::plugin --mode=memory --swap --ignore-warn-msg --warning-usage=80 --critical-usage=90 --warning-swap=25 --critical-swap=80 --autodetect-redhat
CRITICAL: Ram Used : 95.41 % | 'used'=3789324288B;;;0;3971751936 'free'=182427648B;;;0;3971751936 'used_prct'=95.41%;0:80;0:90;0;100 'buffer'=0B;;;0; 'cached'=2197200896B;;;0; 'shared'=101040128B;;;0; 'swap'=297795584B;;;0;8455712768 'swap_free'=8157917184B;;;0;8455712768 'swap_prct'=3.52%;0:25;0:80;0;100
```

```
 free -m
              total        used        free      shared  buff/cache   available
Mem:           3787        1493         258          96        2036        1918
Swap:          8063         284        7779

```

**Comment by joschi99** [comment]
If I try to use the same command without --redhat or --autodetect-redhat then the results are correct. Could be possibly that with latest RH7.8 or CentOS 7.8 they switched back to old behaviour?

**Comment by hdep** [comment]
Hi @joschi99 

I have the same behaviour. @garnier-quentin do you have any idea on this ?

**Comment by garnier-quentin** [comment]
red-hat had revert the patch. Remove the option --redhat and it should be ok. We are going to remove it from the plugin.
