### ISSUE TITLE
[Network::Digi::Standard::SNMP] Can't get list-interfaces

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-plugins#1982]
Hello everyone,
When I try to monitor several services on my Digi 4G router, I got some errors :
![image](https://user-images.githubusercontent.com/26572075/80965280-8d55fe00-8e12-11ea-85da-24fb6e66919e.png)

For another purpose, I want to know if it's possible to check a network port status.
Thanks in advance

**Comment by garnier-quentin** [comment]
Try to add following options:
```
--oid-display=ifdesc --oid-filter=ifdesc
```

**Comment by alliria98** [comment]
Thanks for the tips ! It's completly working now

For the other purpose, do you have any idea how I can check if TCP port 443 is up on an interface ?

**Comment by garnier-quentin** [comment]
you can try: apps::protocols::tcp::plugin
