### ISSUE TITLE
apps::antivirus::kaspersky::snmp::plugin mode updates

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-plugins#1984]
Hi,

I'm trying to understand how to use Kaspersky plugin with 'updates' mode.
I can't make the "*-last-server-update" work like I would like...

Let's say I want a warning alert if the server was not updated for half a day and a critical alert if the server was not updated for a day. So here's my command:
`/usr/lib/centreon/plugins//centreon_kaspersky_snmp.pl --plugin=apps::antivirus::kaspersky::snmp::plugin --mode=updates --hostname=192.168.x.x --snmp-version='2c' --snmp-community='public'  --warning-status='' --critical-status='' --warning-last-server-update='43200' --critical-last-server-update='86400' --warning-not-updated='0' --critical-not-updated=''`
Which returns:
`CRITICAL: Last server update: -1h 14m 57s [2020-05-05T01:00:52] | 'last_server_update'=-6303s;;;0; 'not_updated'=0;0:0;;0;`
I thought it would return OK but it's not!
I tried with values in seconds, values in seconds with a ending "s" and even with negative values... But no luck!

Is this a bug or am I doing it wrong?

**Comment by Cool34000** [comment]
I just noticed I have negative values on some servers and positive values on other servers...
So I tested this:
`/usr/lib/centreon/plugins//centreon_kaspersky_snmp.pl --plugin=apps::antivirus::kaspersky::snmp::plugin --mode=updates --hostname=192.168.x.x --snmp-version='2c' --snmp-community='public' --warning-status='' --critical-status='' --warning-last-server-update='-43200:43200' --critical-last-server-update='-86400:86400' --warning-not-updated='0' --critical-not-updated=''`
And it seems to work... Not sure if it's the right way...
Can someone confirm?

**Comment by garnier-quentin** [comment]
It comes from the timezone. I hope all values are on the same timezone. You can change the timezone for example: --timezone=Europe/Paris

**Comment by Cool34000** [comment]
Good morning Quentin!

I already tested that option with no luck.
I just checked and the Poller and Kaspersky server are on the same timezone, but still:
```
/usr/lib/centreon/plugins//centreon_kaspersky_snmp.pl --plugin=apps::antivirus::kaspersky::snmp::plugin --mode=updates --hostname=192.168.x.x --snmp-version='2c' --snmp-community='public'  --warning-status='' --critical-status='' --warning-last-server-update='43200' --critical-last-server-update='86400' --warning-not-updated='' --critical-not-updated='' --timezone='Europe/Paris'
CRITICAL: Last server update: -1h 3m 1s [2020-05-05T08:37:46] | 'last_server_update'=-7019s;;;0; 'not_updated'=0;;;0;
```

**Comment by garnier-quentin** [comment]
And without timezone it's the same ?

**Comment by Cool34000** [comment]
Yes, same values!

```
# /usr/lib/centreon/plugins//centreon_kaspersky_snmp.pl --plugin=apps::antivirus::kaspersky::snmp::plugin --mode=updates --hostname=192.168.x.x --snmp-version='2c' --snmp-community='public'  --warning-status='' --critical-status='' --warning-last-server-update='43200' --critical-last-server-update='86400' --warning-not-updated='0' --critical-not-updated=''
CRITICAL: Last server update: -1h 11m 33s [2020-05-05T08:37:46] | 'last_server_update'=-6507s;;;0; 'not_updated'=0;0:0;;0;
```
```
# /usr/lib/centreon/plugins//centreon_kaspersky_snmp.pl --plugin=apps::antivirus::kaspersky::snmp::plugin --mode=updates --hostname=192.168.x.x --snmp-version='2c' --snmp-community='public'  --warning-status='' --critical-status='' --warning-last-server-update='43200' --critical-last-server-update='86400' --warning-not-updated='0' --critical-not-updated='' --timezone='Europe/Paris'
CRITICAL: Last server update: -1h 11m 38s [2020-05-05T08:37:46] | 'last_server_update'=-6502s;;;0; 'not_updated'=0;0:0;;0;

```

**Comment by Cool34000** [comment]
```
# timedatectl
      Local time: mar. 2020-05-05 08:52:19 CEST
  Universal time: mar. 2020-05-05 06:52:19 UTC
        RTC time: mar. 2020-05-05 06:52:19
       Time zone: Europe/Paris (CEST, +0200)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  dim. 2020-03-29 01:59:59 CET
                  dim. 2020-03-29 03:00:00 CEST
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  dim. 2020-10-25 02:59:59 CEST
                  dim. 2020-10-25 02:00:00 CET

```
![image](https://user-images.githubusercontent.com/17827397/81041322-d8711f00-8ead-11ea-8666-096f7af22b60.png)

**Comment by garnier-quentin** [comment]
Could you test now ? it should work better

**Comment by Cool34000** [comment]
It's working as expected now!
Thanks a lot Quentin

**Comment by garnier-quentin** [comment]
you're welcome. thanks for the feedback
