### ISSUE TITLE
[cloud::microsoft::office365::*] add --use-new-perfdata option

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#1986]
Hi,

Could you add the `--use-new-perfdata` option to the various `cloud::microsoft::office365` plugins please ?

Many thanks :+1:

**Comment by garnier-quentin** [comment]
They got it. You mean the new labels ?

**Comment by UrBnW** [comment]
Sorry yes, the new labels, the ones which are dot-separated.

**Comment by UrBnW** [comment]
And with the `instance#` prefix :)

**Comment by UrBnW** [comment]
Replaced by #1989.
