### ISSUE TITLE
Extreme

### ISSUE THREAD

**Issue by trentasis** [centreon/centreon-plugins#1987]
hi,

It seems that centreon support extreme, but when I try to test with a VSP extreme switchs returns error:

  perl centreon_plugins.pl --hostname=10.10.10.11 --plugin=network::extreme::snmp::plugin  --snmp-version=2c --snmp-community=com --mode=cpu --verbose
UNKNOWN: SNMP Table Request: Cant get a single value.

tried with latest version, but not sure where is the issue, for example a snmp query to uptime works, but all modes are failing, only interfaces mode works

Versions:  SysDescr     : VSP-7400-48Y-8C (8.1.1.0)
VSP Operating System Software Build 8.1.1.0

If you need I can get more information

thanks

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk of following branch ?
```
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1 > extreme.snmpwalk
```

**Comment by trentasis** [comment]
Hi,

thanks, sended by email snmpwalk

**Comment by garnier-quentin** [comment]
It doesn't get extreme OIDs. Could you try: --plugin=network::nortel::standard::snmp::plugin ?

**Comment by trentasis** [comment]
hi,
same otuput
perl centreon_plugins.pl --hostname=10.10.10.11 --plugin=network::nortel::standard::snmp::plugin  --snmp-version=2c --snmp-community=com --mode=cpu --verbose
UNKNOWN: SNMP Table Request: Cant get a single value.

**Comment by garnier-quentin** [comment]
Could you get mibs file of that equipment ?

**Comment by trentasis** [comment]
hi, sended mib by private mail

**Comment by trentasis** [comment]
files
[VOSS7400.8.0.8.0_mib.txt](https://github.com/centreon/centreon-plugins/files/4597244/VOSS7400.8.0.8.0_mib.txt)
[VOSS7400.8.0.8.0_mib.zip](https://github.com/centreon/centreon-plugins/files/4597245/VOSS7400.8.0.8.0_mib.zip)

**Comment by garnier-quentin** [comment]
Ok i have found cpu and memory usage. I could add it in nortel standard (because it's rapid-city).
rcKhiSlotCpu5MinAve - .1.3.6.1.4.1.2272.1.85.10.1.1.6
rcKhiSlotMemFree
rcKhiSlotMemUsed

We could also do cli with ssh.

**Comment by garnier-quentin** [comment]
I have enhanced nortel standard plugin. Could you test it ?

**Comment by trentasis** [comment]
Sorry for my later respone, a little busy, I'll try and report the results...
Thanks

**Comment by trentasis** [comment]
hi @garnier-quentin 

Good Job
Results using nortel check:

CPU OK:
 perl centreon_plugins.pl --hostname=10.10.10.10 --plugin=network::nortel::standard::snmp::plugin --snmp-version=2c --snmp-community=com--mode=cpu --warning-5m=80 --critical-5m=90
OK: CPU 'slot_1' usage 7.00 % (5min) | 'cpu_5min'=7.00%;0:80;0:90;0;100

hardware, works but only detects psu, no fans, no temperatures and other components
 perl centreon_plugins.pl --hostname=10.10.10.10 --plugin=network::nortel::standard::snmp::plugin --snmp-version=2c --snmp-community=com--mode=hardware
OK: All 2 components are ok [2/2 psus]. | 'count_psu'=2;;;;

memory mode, not working seems that some valuesare not collected:
perl centreon_plugins.pl --hostname=10.10.10.10 --plugin=network::nortel::standard::snmp::plugin --snmp-version=2c --snmp-community=com--mode=memory --warning-usage=80 --critical-usage=90
CRITICAL: Memory 'slot_1' total: 15.67 GB used: 2.41 GB (0.15%) free: 13.26 GB (0.85%) | 'slot_1#memory.usage.bytes'=2590683136B;0:80;0:90;0;16829505536 'slot_1#memory.free.bytes'=14238822400B;;;0;16829505536 'slot_1#memory.usage.percentage'=0.15%;;;0;100

from cli mem and cpu values are
MemUsed	MemFree	CpuCurrentUtil
2530968	13904096	7

Can you reopen and check this items?

thanks
