### ISSUE TITLE
apps::vmware::connector::plugin - Wrong unit used for critical and warning traffic

### ISSUE THREAD

**Issue by Eli0ttD0NATIEN** [centreon/centreon-plugins#1988]
Centreon : 20.04.0
Plugins : 20190221
Command used : 
/var/lib/centreon/centplugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --mode=net-host --esx-hostname='' --sampling-period=20 --warning-host-traffic-in=85 --critical-host-traffic-in=95 --warning-host-traffic-out=85 --critical-host-traffic-out=95 --warning-vswitch-traffic-in=85 --critical-vswitch-traffic-in=95 --warning-vswitch-traffic-out=85 --critical-vswitch-traffic-out=95 --warning-link-traffic-in=85 --critical-link-traffic-in=95 --warning-link-traffic-out=85 --critical-link-traffic-out=95 --warning-link-dropped-in=50 --critical-link-dropped-out=80 --warning-link-dropped-out=50 --critical-link-dropped-out=80 --verbose

Some of my warning and critical values are using 'b/s' as unit and not percent so i am getting a CRITICAL status

**Comment by garnier-quentin** [comment]
We use percentage for thresholds:
```
--link-traffic-in --link-traffic-out
```

For ```--host-traffic-in```, ```host-traffic-out```, it's in b/s yes. you should change it. you can use that syntax if you want `--host-traffic-in=100Mb```

**Comment by Eli0ttD0NATIEN** [comment]
Thanks,
How do we know what our flow represents in percentage?

**Comment by garnier-quentin** [comment]
I have added it in help

**Comment by Eli0ttD0NATIEN** [comment]
Thanks !
