### ISSUE TITLE
Problem with [apps::vmware::connector::plugin] on active memory

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon-plugins#199]
Hello,
I'm trying to get the active memory of my virtual machine but it doesnt seem to work at all.

The following command will return "0" as active memory for all my VMs :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=memory-vm --connector-hostname=127.0.0.1 --filter-perfdata 'active'

My vSphere is 5.5.

Thanks for your help.

Regards.

**Comment by garnier-quentin** [comment]
Hi,

Could you give me the output ?

**Comment by gerpion** [comment]
Hey,

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=memory-vm --connector-hostname=127.0.0.1 --vm-hostname=cbh171 --filter-perfdata 'active'
OK: 'cbh171' Memory Total: 20.00 GB Used: 15.53 GB (77.64%) Free: 4.47 GB (22.36%) | 'active'=0B;;;0;

**Comment by gerpion** [comment]
And without filter :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=memory-vm --connector-hostname=127.0.0.1 --vm-hostname=cbh171
OK: 'cbh171' Memory Total: 20.00 GB Used: 15.54 GB (77.70%) Free: 4.46 GB (22.30%) | 'used'=16685700096B;;;0;21474836480 'overhead'=172072960B;;;0; 'ballooning'=0B;;;0; 'active'=0B;;;0; 'shared'=7033112576B;;;0;

**Comment by garnier-quentin** [comment]
When you like in virtual center, there is a value (!= 0) for active memory ?

**Comment by gerpion** [comment]
Hi Quentin,
Actually active memory is at 3GB out of 20GB. In virtual environnment Active Memory is the memory really needed by the system and apps. So it's kinda not possible to be at 0.

**Comment by gerpion** [comment]
Hello Quentin,
Any updates on that request ? Did you find something about it ?

**Comment by garnier-quentin** [comment]
Could you send me a email (or get mine: qgarnier@centreon.com) to do a session to see the problem ?

**Comment by garnier-quentin** [comment]
Fixed here: https://github.com/centreon/centreon-vmware/issues/6

**Comment by gerpion** [comment]
Thanks a ton Quentin for the support. Much appreciated.
