### ISSUE TITLE
network::fortinet::fortigate::plugin cluster-status: automatically trigger an alert on master node changes

### ISSUE THREAD

**Issue by sbraz** [centreon/centreon-plugins#1991]
Hi,
I noticed this similar issue (#1588) but it would be easier if this was done automatically using a persistent state file:
* first run: the master node is saved to the state file
* subsequent runs: the master node is compared to that stored in the file
* the state can be reset by running the command with a `--clear-cache` or similar option

**Comment by garnier-quentin** [comment]
I can add the %{roleLast}. And you could compare it.

**Comment by sbraz** [comment]
IMO this should even be the default behaviour. I'm sure every network administrator is interested in knowing when their cluster fails over.

**Comment by garnier-quentin** [comment]
I'm not sure to put it by default.

**Comment by sbraz** [comment]
It will be a useful addition anyway, maybe mentioning it in examples will be enough.

**Comment by UrBnW** [comment]
This is what we already have in `network::juniper::common::junos::mode::stack`, and it works fine. Would be consistent then.
You just have to be sure to set the service `retry` option to `0` 👍

**Comment by sbraz** [comment]
@garnier-quentin do you think you will have the new feature ready by the end of June?

**Comment by garnier-quentin** [comment]
Of course

**Comment by sbraz** [comment]
Hey @garnier-quentin, have you managed to work on this?
