### ISSUE TITLE
question about spanning tree mode

### ISSUE THREAD

**Issue by trentasis** [centreon/centreon-plugins#1992]
Hi,

I'm evaluating spanning tree mode and works great, but I ahve a question, when a port in blocking state appears as critical, but I like to know if it is possible to configure to show blocking as OK and when is different that blocking as Critical to know when a spanning tree topology has reproduces, is this possible?

thanks

**Comment by Sims24** [comment]
Hi @trentasis , 

Yep it is totally possible with the critical-status option. 

Default value is:  '%{op_status} =~ /up/ && %{state} =~ /blocking|broken/'

You can use  '%{op_status} =~ /up/ && %{state} =~ /broken/' to not trigger CRITICAL alarm when port state is blocking

**Comment by trentasis** [comment]
How is configured on command line, can younshow an example, sorry

**Comment by garnier-quentin** [comment]
Like that: ```--critical-status='  %{op_status} =~ /up/ && %{state} =~ /broken/ ' ```

**Comment by trentasis** [comment]
Hi

Sorry, Is was a bad mode, now using correct mode  works (--mode=spanning-tree)

 perl centreon_plugins.pl --hostname=10.10.10.10 --plugin=network::alcatel::omniswitch::snmp::plugin --snmp-version=2c --snmp-community=com --mode=spanning-tree --critical-status=' %{op_status} =~ /up/ && %{state} =~ /broken/ '
OK: All spanning trees are ok |

Good job and Thanks for all
