### ISSUE TITLE
new option --units-cast in [snmp_standard::mode::interfaces]

### ISSUE THREAD

**Issue by dalfo77** [centreon/centreon-plugins#1994]
Ciao, it is possible to add the option `--units-cast` to plugin [snmp_standard::mode::interfaces]?

I see from functions `set_oids_errors` and `set_oids_cast` that the OIDs are both counters.

Having at least the option `--units-cast=absolute` can permit to use options like `--extend-perfdata-group` like in this this example:

> [...]
> Sum wrong packets from all interfaces (with interface need
> --units-errors=absolute):
> --extend-perfdata-group=',packets_wrong,sum(packets_(discard
> |error)_(in|out))'
> [...]

Thanks,
Matteo.

**Comment by garnier-quentin** [comment]
I don't understand. You can group cast counters.

**Comment by dalfo77** [comment]
How to group the cast counter so I can obtain the total of xCast traffic for a single host?
I 've tried `--extend-perfdata-group=',total_multicast,sum((in|out)-mcast_.*)'` but I've obtained `'total_multicast'=2693.03;;;; `

**Comment by garnier-quentin** [comment]
Why do you want to group xCast ? You want total packets in and total packets out ?

**Comment by dalfo77** [comment]
Having the the total traffic divided in ucast, bcast and mcast can be used to see how the traffic is shaped.
The trend of this information can help business to plan future purchase, eg. if my total multicast traffic is growing, I need to buy network switch with better multicast capability

**Comment by garnier-quentin** [comment]
So you want cast counters in absolute value ?

**Comment by dalfo77** [comment]
Yes, option `--units-cast=(absolute|%)` can be useful!

With SNMP is technical possible calculate xCast traffic also in 'b/s'?

Thanks

**Comment by garnier-quentin** [comment]
We cannot in bytes i think. we get only packets.

**Comment by moix** [comment]
Hi @garnier-quentin I think packet count is also interested and is something I was looking for because our network engineers are looking to validate if the packets number match between switch and the VC.

Is this something that could be introduced?

Thanks!

**Comment by garnier-quentin** [comment]
You have a new option: ```--units-cast=[percent_delta|percent|delta|counter]```
