### ISSUE TITLE
ssh command return command-line line 0: missing argument.

### ISSUE THREAD

**Issue by Doudoux2** [centreon/centreon-plugins#1995]
Hello

Context:

ssh -V : OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
PRM: openssh-clients-7.4p1-21.el7.x86_64
/etc/centos-release : CentOS Linux release 7.8.2003 (Core)

When i launch following command
```bash
/usr/lib/centreon/plugins/git/centreon_plugins.pl --plugin=storage::hp::3par::ssh::plugin --mode=disk-usage --hostname=<myip>
```

I have the message
```text
UNKNOWN: Command error: command-line line 0: missing argument. 
````

After debug, there is an issue with ssh command:
````
# actual cmd
ssh  -o BatchMode yes

#return 
command-line line 0: missing argument.

# 2 fixes possible
ssh  -o BatchMode=yes
ssh  -o "BatchMode yes"
````

Patch is in `/centreon/plugins/backend/ssh/sshcli.pm` file

````perl
push @{$self->{ssh_option}}, '-o=BatchMode yes';
````
=>

````perl
push @{$self->{ssh_option}}, '-o="BatchMode yes"';
````

BR,

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by Doudoux2** [comment]
> 
> 
> Could you test it ?

It's ok for me

Thanks.
