### ISSUE TITLE
AWS Kinesis - add new metric

### ISSUE THREAD

**Issue by NicolasBlancoLopez** [centreon/centreon-plugins#1997]
Good morning,
I would need for my project the creation for Centreon of the metric "WriteProvisionedThroughputExceeded", through the command centreon_aws_kinesis_api.pl. since at the moment it does not exist as they tell me from Slack.

Thank you very much in advance.

Best regards.

Nicolás Blanco.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
