### ISSUE TITLE
[plugin] Sonus

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#20]
Add a plugin to monitor Sonus :
- alarm: .1.3.6.1.4.1.177.15.1.3
- cpu: .1.3.6.1.2.1.25.3.3.1.2
- memory and storage: .1.3.6.1.2.1.25.2.3.1.3
- global temperature: .1.3.6.1.4.1.177.15.1.12.2.0
- hardware: psu, fan, card
- dsp usage: cpu and number of channel in use in it
- channel status: count per oper states and connected time in seconds of the channel.

**Comment by Sims24** [comment]
Hi,

Closing it as PR has been merged for first checks. 

We'll wait for hardware equipment to add : 

- temperature
- hardware

Alarm is not relevant as it's too verbose.

Thanks
