### ISSUE TITLE
[network::extreme::snmp::plugin] mode interfaces

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#200]
Hello,

Traffic does not work for big switch :

perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl  --plugin=network::extreme::snmp::plugin --mode=interfaces --interface=5001 --add-traffic --warning-total=95 --critical-total=99 --hostname=myhost --snmp-version=2c --snmp-community=mycom --snmp-timeout=15 --snmp-retries=1

UNKNOWN: SNMP Table Request : (tooBig) Response message would have been too large.

**Comment by garnier-quentin** [comment]
You need to use --subsetleef=20 --maxrepetitions=20

**Comment by ritouret** [comment]
Wonderfull options !
Everything is OK now.

You should add this here : https://documentation-fr.centreon.com/docs/centreon-plugins/en/latest/user/guide.html#depannage

Many thanks.

**Comment by garnier-quentin** [comment]
Have you looked the link ? What is the first question ? :)

**Comment by CFRR** [comment]
is possible a graph per interface?
