### ISSUE TITLE
[apps::hyperv::2012::local::plugin] mode node-snapshot

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#2000]
Hello,

Should you add an output when there is no snapshot on Node ?

Here is the Powershell output when there is a snapshot :
PS C:\Windows\system32> Get-VMSnapshot -VMName *

VMName      Name                                  SnapshotType CreationTime        ParentSnapshotName
------      ----                                  ------------ ------------        ------------------
testwin2003 testwin2003 - (14/05/2020 - 15:53:06) Standard     14/05/2020 15:53:07

Here it is when there is no snapshot (nothing) :
PS C:\Windows\system32> Get-VMSnapshot -VMName *

Here is the output from centreon_plugins in this case :
/usr/lib/nagios/plugins/check_centreon_nrpe -H 10.10.10.10 -p 5666 -t 30 -u -m 8192 -c check_centreon_plugins -a 'apps::hyperv::2012::local::plugin' 'node-snapshot' ' --critical-snapshot=864000'
OK:  |

Thanks

**Comment by garnier-quentin** [comment]
I added the message.
