### ISSUE TITLE
[apps::hyperv::2012::local::plugin] mode node-integration-service

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#2001]
Hello,

It seems that the option --filter-vm for this mode does not work (or i don't know how it works !) :

/usr/lib/nagios/plugins/check_centreon_nrpe -H 10.10.10.10 -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::hyperv::2012::local::plugin' 'node-integration-service'  ' --filter-vm="" --filter-note="" --filter-status="" --warning-global-status="%{integration_service_state} =~ /Update required/i" --critical-global-status="" --warning-service-status="" --critical-service-status="not %{primary_status} =~ /Ok/i" --verbose'
CRITICAL: 1 problem(s) detected |
checking virtual machine 'hostname1'
checking virtual machine 'hostname2'
critical: integration service '▒change de paires cl▒-valeur' status : NoContact/

-> let's filter with hostname2 :
/usr/lib/nagios/plugins/check_centreon_nrpe -H 10.10.10.10 -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::hyperv::2012::local::plugin' 'node-integration-service'  ' --filter-vm="hostname2" --filter-note="" --filter-status="" --warning-global-status="%{integration_service_state} =~ /Update required/i" --critical-global-status="" --warning-service-status="" --critical-service-status="not %{primary_status} =~ /Ok/i" --verbose'
CRITICAL: VM 'hostname2' 1 problem(s) detected |
checking virtual machine 'hostname2'
critical: integration service '▒change de paires cl▒-valeur' status : NoContact/

-> now, let's filter without hostname2 :
/usr/lib/nagios/plugins/check_centreon_nrpe -H 10.10.10.10 -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::hyperv::2012::local::plugin' 'node-integration-service'  ' --filter-vm="ne hostname2" --filter-note="" --filter-status="" --warning-global-status="%{integration_service_state} =~ /Update required/i" --critical-global-status="" --warning-service-status="" --critical-service-status="not %{primary_status} =~ /Ok/i" --verbose'
OK:  |

-> it seems good except output, but when the filter is without hostname1, it should be CRITICAL :
/usr/lib/nagios/plugins/check_centreon_nrpe -H 10.10.10.10 -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::hyperv::2012::local::plugin' 'node-integration-service'  ' --filter-vm="ne hostname1" --filter-note="" --filter-status="" --warning-global-status="%{integration_service_state} =~ /Update required/i" --critical-global-status="" --warning-service-status="" --critical-service-status="not %{primary_status} =~ /Ok/i" --verbose'
OK:  |

-> and when the test is good with only one VM, there is an output :
/usr/lib/nagios/plugins/check_centreon_nrpe -H 10.10.10.10 -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::hyperv::2012::local::plugin' 'node-integration-service'  ' --filter-vm="hostname1" --filter-note="" --filter-status="" --warning-global-status="%{integration_service_state} =~ /Update required/i" --critical-global-status="" --warning-service-status="" --critical-service-status="not %{primary_status} =~ /Ok/i" --verbose'
OK: VM 'hostname1' 0 problem(s) detected - VM 'hostname1' 0 problem(s) detected |
checking virtual machine 'hostname1'

What's going wrong ? The used option filter-vm syntax or the mode ?

If it is the used option syntax, how can we define it for 1 vm and for several vm ?

Thanks

**Comment by garnier-quentin** [comment]
It's a regular expression. With ```--filter-vm="ne hostname2"```, you check vm with name: 'toto ne hostname2 plop' (for example). You can use negative regular expression to exclude:
```
`--filter-vm="^(?!(hostname1)$)"
```

**Comment by Cool34000** [comment]
Hi,

Sorry for reopening this issue but I'm getting an error when trying to exclude a VM using what you suggested:
> ```
> `--filter-vm="^(?!(hostname1)$)"
> ```
Here's the full comamnd:
`# /usr/lib64/nagios/plugins/check_centreon_nrpe -H 192.168.101.2 -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::hyperv::2012::local::plugin' 'node-integration-service' ' --filter-vm="" --filter-note="" --filter-status="" --warning-global-status="%{integration_service_state} =~ /Update required/i" --critical-global-status="" --warning-service-status="" --critical-service-status="not %{primary_status} =~ /Ok/i" --verbose --filter-vm="^(?!(hostname1)$)" '`
I'm getting this error:
`UNKNOWN: Sequence (? incomplete in regex; marked by <-- HERE in m/^(? <-- HERE / at C:\Windows\TEMP\par-5352562d48595045525624\cache-d12512ada9ab23474d612e072dcdcd805a3430ef\inc\lib/apps/hyperv/2012/local/mode/nodeintegrationservice.pm line 204.`

**Comment by garnier-quentin** [comment]
In NRPE, you cannot use special characters: !
You can use nsclient rest api with plugin: apps::protocols::nrpe::plugin --custommode=nsclient

Or you can try following options:
```--convert-args="##,\x21" --filter-vm="^(?##(hostname1)$)" ```

**Comment by Cool34000** [comment]
Working!
Thanks Quentin
