### ISSUE TITLE
[apps::vmware::connector::plugin] memory-vm - Exclude powered off VM

### ISSUE THREAD

**Issue by sulian** [centreon/centreon-plugins#2003]
Hello, when I use `memory-vm`, how can I exclude powered off VMs ? I have an unknow status service because of that.

Before it was the `nopoweredoff` filter but now it no longer exists.

Best regards

**Comment by garnier-quentin** [comment]
Use following option: ```--unknown-status=''```

**Comment by sulian** [comment]
You are my God 😍
