### ISSUE TITLE
McAfee webgateway Time to resolve DNS in ms

### ISSUE THREAD

**Issue by antoinelavit** [centreon/centreon-plugins#2006]
Hi,

Can you add a new mode for monitoring McAfee Web Gateway:

1.3.6.1.4.1.1230.2.7.2.5.6.0        Time to resolve DNS in ms

Extract of McAfee MIB:

	stResolveHostViaDNS OBJECT-TYPE
		SYNTAX  Counter64
		MAX-ACCESS read-only
		STATUS current
		DESCRIPTION
		"Time to resolve DNS in ms"
		::= { mwgMiscellaneous 6 } 

[MCAFEE-MWG-MIB.txt](https://github.com/centreon/centreon-plugins/files/4649423/MCAFEE-MWG-MIB.txt)

Regards

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk please of that branch ?
.1.3.6.1.4.1.1230

**Comment by garnier-quentin** [comment]
There is a new mode: system.
You can test it
