### ISSUE TITLE
apps::protocols::nrpe::plugin Illegal division by zero 

### ISSUE THREAD

**Issue by Zhaodongxu77** [centreon/centreon-plugins#2009]
Hi,
**I downloaded the latest centreon-plugins, and run the nrpe custommode, but give me the error as follow**
perl centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --mode=query --custommode=nrpe --hostname=IP --command=alias_up

Use of uninitialized value in concatenation (.) or string at /tmp/centreon-plugins-master/centreon/plugins/nrpe.pm line 188.
Use of uninitialized value in concatenation (.) or string at /tmp/centreon-plugins-master/centreon/plugins/nrpe.pm line 188.
Use of uninitialized value in concatenation (.) or string at /tmp/centreon-plugins-master/centreon/plugins/nrpe.pm line 188.
Use of uninitialized value in pattern match (m//) at /tmp/centreon-plugins-master/centreon/plugins/nrpe.pm line 188.
UNKNOWN: Illegal division by zero at /tmp/centreon-plugins-master/centreon/plugins/nrpe.pm line 188. 

**Is anyone could have a look, am I executed the wrong command or is there anything wrong?
Really appreciate for all help.**

**Comment by garnier-quentin** [comment]
Could you test with the last version ? It seems you use a perl version < 5.10

**Comment by Zhaodongxu77** [comment]
It works now, thanks so much.
