### ISSUE TITLE
[hardware::server::dell::idrac::snmp::plugin] mode hardware

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#201]
Hello,

It seems that you convert only current temperature value but not thresholds values which are also in Fahrenheit.

Here is the result for this mode :
CRITICAL: Temperature 'System Board Inlet Temp' is 20 degree centigrade - Temperature 'System Board Exhaust Temp' is 34 degree centigrade - Temperature 'CPU1 Temp' is 50 degree centigrade - Temperature 'CPU2 Temp' is 46 degree centigrade | 'temp_1.1'=20C;420:470;30:470;; 'temp_1.2'=34C;700:750;80:750;; 'temp_1.3'=50C;790:840;80:840;; 'temp_1.4'=46C;790:840;80:840;;
Checking temperatures
Temperature 'System Board Inlet Temp' status is 'ok' [instance = 1.1] [state = enabled] [value = 20]
Temperature 'System Board Exhaust Temp' status is 'ok' [instance = 1.2] [state = enabled] [value = 34]
Temperature 'CPU1 Temp' status is 'ok' [instance = 1.3] [state = enabled] [value = 50]
Temperature 'CPU2 Temp' status is 'ok' [instance = 1.4] [state = enabled] [value = 46]

Here is the snmpwalk for this branch :
IDRAC-MIB-SMIv2::temperatureProbechassisIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::temperatureProbechassisIndex.1.2 = INTEGER: 1
IDRAC-MIB-SMIv2::temperatureProbechassisIndex.1.3 = INTEGER: 1
IDRAC-MIB-SMIv2::temperatureProbechassisIndex.1.4 = INTEGER: 1
IDRAC-MIB-SMIv2::temperatureProbeIndex.1.1 = INTEGER: 1
IDRAC-MIB-SMIv2::temperatureProbeIndex.1.2 = INTEGER: 2
IDRAC-MIB-SMIv2::temperatureProbeIndex.1.3 = INTEGER: 3
IDRAC-MIB-SMIv2::temperatureProbeIndex.1.4 = INTEGER: 4
IDRAC-MIB-SMIv2::temperatureProbeStateCapabilities.1.1 = INTEGER: 0
IDRAC-MIB-SMIv2::temperatureProbeStateCapabilities.1.2 = INTEGER: 0
IDRAC-MIB-SMIv2::temperatureProbeStateCapabilities.1.3 = INTEGER: 0
IDRAC-MIB-SMIv2::temperatureProbeStateCapabilities.1.4 = INTEGER: 0
IDRAC-MIB-SMIv2::temperatureProbeStateSettings.1.1 = INTEGER: enabled(2)
IDRAC-MIB-SMIv2::temperatureProbeStateSettings.1.2 = INTEGER: enabled(2)
IDRAC-MIB-SMIv2::temperatureProbeStateSettings.1.3 = INTEGER: enabled(2)
IDRAC-MIB-SMIv2::temperatureProbeStateSettings.1.4 = INTEGER: enabled(2)
IDRAC-MIB-SMIv2::temperatureProbeStatus.1.1 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::temperatureProbeStatus.1.2 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::temperatureProbeStatus.1.3 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::temperatureProbeStatus.1.4 = INTEGER: ok(3)
IDRAC-MIB-SMIv2::temperatureProbeReading.1.1 = INTEGER: 200
IDRAC-MIB-SMIv2::temperatureProbeReading.1.2 = INTEGER: 340
IDRAC-MIB-SMIv2::temperatureProbeReading.1.3 = INTEGER: 500
IDRAC-MIB-SMIv2::temperatureProbeReading.1.4 = INTEGER: 460
IDRAC-MIB-SMIv2::temperatureProbeType.1.1 = INTEGER: temperatureProbeTypeIsAmbientESM(3)
IDRAC-MIB-SMIv2::temperatureProbeType.1.2 = INTEGER: temperatureProbeTypeIsAmbientESM(3)
IDRAC-MIB-SMIv2::temperatureProbeType.1.3 = INTEGER: temperatureProbeTypeIsAmbientESM(3)
IDRAC-MIB-SMIv2::temperatureProbeType.1.4 = INTEGER: temperatureProbeTypeIsAmbientESM(3)
IDRAC-MIB-SMIv2::temperatureProbeLocationName.1.1 = STRING: "System Board Inlet Temp"
IDRAC-MIB-SMIv2::temperatureProbeLocationName.1.2 = STRING: "System Board Exhaust Temp"
IDRAC-MIB-SMIv2::temperatureProbeLocationName.1.3 = STRING: "CPU1 Temp"
IDRAC-MIB-SMIv2::temperatureProbeLocationName.1.4 = STRING: "CPU2 Temp"
IDRAC-MIB-SMIv2::temperatureProbeUpperCriticalThreshold.1.1 = INTEGER: 470
IDRAC-MIB-SMIv2::temperatureProbeUpperCriticalThreshold.1.2 = INTEGER: 750
IDRAC-MIB-SMIv2::temperatureProbeUpperCriticalThreshold.1.3 = INTEGER: 840
IDRAC-MIB-SMIv2::temperatureProbeUpperCriticalThreshold.1.4 = INTEGER: 840
IDRAC-MIB-SMIv2::temperatureProbeUpperNonCriticalThreshold.1.1 = INTEGER: 420
IDRAC-MIB-SMIv2::temperatureProbeUpperNonCriticalThreshold.1.2 = INTEGER: 700
IDRAC-MIB-SMIv2::temperatureProbeUpperNonCriticalThreshold.1.3 = INTEGER: 790
IDRAC-MIB-SMIv2::temperatureProbeUpperNonCriticalThreshold.1.4 = INTEGER: 790
IDRAC-MIB-SMIv2::temperatureProbeLowerNonCriticalThreshold.1.1 = INTEGER: 30
IDRAC-MIB-SMIv2::temperatureProbeLowerNonCriticalThreshold.1.2 = INTEGER: 80
IDRAC-MIB-SMIv2::temperatureProbeLowerNonCriticalThreshold.1.3 = INTEGER: 80
IDRAC-MIB-SMIv2::temperatureProbeLowerNonCriticalThreshold.1.4 = INTEGER: 80
IDRAC-MIB-SMIv2::temperatureProbeLowerCriticalThreshold.1.1 = INTEGER: -70
IDRAC-MIB-SMIv2::temperatureProbeLowerCriticalThreshold.1.2 = INTEGER: 30
IDRAC-MIB-SMIv2::temperatureProbeLowerCriticalThreshold.1.3 = INTEGER: 30
IDRAC-MIB-SMIv2::temperatureProbeLowerCriticalThreshold.1.4 = INTEGER: 30
IDRAC-MIB-SMIv2::temperatureProbeProbeCapabilities.1.1 = INTEGER: 15
IDRAC-MIB-SMIv2::temperatureProbeProbeCapabilities.1.2 = INTEGER: 0
IDRAC-MIB-SMIv2::temperatureProbeProbeCapabilities.1.3 = INTEGER: 0
IDRAC-MIB-SMIv2::temperatureProbeProbeCapabilities.1.4 = INTEGER: 0

**Comment by ritouret** [comment]
Threshold also should be :
warning : temperatureProbeLowerNonCriticalThreshold:temperatureProbeUpperNonCriticalThreshold
critical : temperatureProbeLowerCriticalThreshold:temperatureProbeUpperCriticalThreshold

**Comment by garnier-quentin** [comment]
The following check shouldn't be use. I haven't finished it.
