### ISSUE TITLE
New plugin for Citrix Xen Mobile

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2011]
It should be nice to have support for Citrix XenMobile.

Attached you can find MIBS and snmpwalk for version 10.8:
[XenMobile.zip](https://github.com/centreon/centreon-plugins/files/4666518/XenMobile.zip)
[citrix-mobile.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/4666547/citrix-mobile.snmpwalk.txt)

Please note that XenMobile offers only snmp v3

**Comment by garnier-quentin** [comment]
What do you want monitor ? When i look the private entreprise mib, i see:
service connection status like:
```
.1.3.6.1.4.1.3845.5.1.1.8.1.0 = STRING: "gateway.push.apple.com"
.1.3.6.1.4.1.3845.5.1.1.8.2.0 = STRING: "Port 2195/TCP is open."
.1.3.6.1.4.1.3845.5.1.1.8.3.0 = STRING: "Server is reachable."
.1.3.6.1.4.1.3845.5.1.1.8.4.0 = STRING: "UP"
.1.3.6.1.4.1.3845.5.1.1.9.1.0 = STRING: "feedback.push.apple.com"
.1.3.6.1.4.1.3845.5.1.1.9.2.0 = STRING: "Port 2196/TCP is open."
.1.3.6.1.4.1.3845.5.1.1.9.3.0 = STRING: "Server is reachable."
.1.3.6.1.4.1.3845.5.1.1.9.4.0 = STRING: "UP"
...
```

Memory jvm usage (it seems it's a java process).

Nothing more in SNMP. Maybe with the Rest API, we can get more mobility informations:
https://docs.citrix.com/en-us/xenmobile/server/downloads/public-rest-api-xenmobile-10-9.pdf

example: number of devices out of compliance...

**Comment by joschi99** [comment]
Hi @garnier-quentin,
snmp is not offering more then what you have written above unfortunatly. It could be a good idea to use the Rest API which allows to have a lot more informations.
How can I help you?

**Comment by joschi99** [comment]
The hole OS monitoring is based on Linux standards, so no problems through SNMP

**Comment by garnier-quentin** [comment]
I need curl commands and results:
- login connection ok
- login connection error
- listing devices (to get status compliance for example)

**Comment by joschi99** [comment]
Hi @garnier-quentin,

here you can see the requested curls and results. The output for listing devices is in the password protected zip archive.

```
Login

curl --location --request POST 'https://x.x.x.x:4443/xenmobile/api/v1/authentication/login' --header 'Content-Type: application/json' --data '{
"login": "Administrator",
"password": "****"
}' –insecure

Response

{"auth_token":"*******"}


ERROR Login Response
{"message":"Error occured during validating user credentials","status":1002}






Logout

curl --location --request POST 'https://x.x.x.x:4443/xenmobile/api/v1/authentication/logout' \
--header 'auth_token: *******' \
--header 'Content-Type: application/json' \
--data '{
"login": "administrator"
}' –insecure

Response

{"Status":"user administrator logged out successfully."}




Devices

curl --location --request POST 'https://x.x.x.x:4443/xenmobile/api/v1/device/filter' \
--header 'auth_token: *******' \
--header 'Content-Type: application/json' \
--data '{
"sortOrder": "ASC",
"sortColumn": "ID",
"search": "",
"enableCount": "false",
"filterIds": "[]"
}' –insecure
```
[devicelist_without_filter.zip](https://github.com/centreon/centreon-plugins/files/4769385/devicelist_without_filter.zip)

**Comment by garnier-quentin** [comment]
I have looked the result and not so much datas. Maybe the number of jailBroken devices. I don't know.

**Comment by fmattesct** [comment]
Please re-create this request on The Watch if it's still relevant.
Thanks
