### ISSUE TITLE
[snmp_standard::interfaces] print packet received/transmitted

### ISSUE THREAD

**Issue by moix** [centreon/centreon-plugins#2018]
## Question

Hi, I've been asked to include as output of our interfaces monitor not only the traffic in/out of the interface but also the packet counts, e.g. oid_ifInUcastPkts, oid_ifOutUcastPkts

I've been trying to work with all the options but no luck with it, the --add-cast option print it in percentage for transmitted, broadcast and multicast.

Am I missing anything? or if it is not an option available at the moment, could that be considered to be added?

Thanks in advance!

**Comment by garnier-quentin** [comment]
Very similar: https://github.com/centreon/centreon-plugins/issues/1994

**Comment by moix** [comment]
I see, looked for some but didn't realize that one ;) sorry feel free to close if you think both have similar if not same scope.

**Comment by garnier-quentin** [comment]
It should be ok now: --units-cast=[percent_delta|percent|delta|counter]
