### ISSUE TITLE
apps::proxmox::ve::restapi::mode::vmusage VM Output

### ISSUE THREAD

**Issue by calou45200** [centreon/centreon-plugins#2019]
Hello,
I use centreon autodicovery in Centreon IT 20.04 for VM's proxmox monitoring.
I u se
This command work :
/usr/lib/centreon/plugins//centreon_proxmox_ve_restapi.pl --plugin apps::proxmox::ve::restapi::plugin --mode=vm-usage --hostname=xx.xx.xx.xx --api-username='xxxx' --api-password='xxxx' --proto='https' --port='8006' --realm='pve' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --filter-name='centreon-central' --warning-cpu='80' --critical-cpu='90' --warning-memory='80' --critical-memory='90' --warning-traffic-in='' --critical-traffic-in='' --warning-traffic-out='' --critical-traffic-out='' --warning-read-iops='' --critical-read-iops='' --warning-write-iops='' --critical-write-iops='' --filter-counters='traffic'
Retun :
OK: VM 'qemu/110'  - VM 'centreon-central' Traffic In : 216.80 Kb/s, Traffic Out : 153.26 Kb/s | 'traffic_in'=216802.40b/s;;;0; 'traffic_out'=153255.20b/s;;;0;

I don't need to have VM name in centreon, because I have this information on service.
So I try this command :
/usr/lib/centreon/plugins//centreon_proxmox_ve_restapi.pl --plugin apps::proxmox::ve::restapi::plugin --mode=vm-usage --hostname=xxx.xxx.xxx.xxx --api-username='xxx' --api-password='xxx' --proto='https' --port='8006' --realm='pve' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --filter-name='centreon-central' --warning-cpu='80' --critical-cpu='90' --warning-memory='80' --critical-memory='90' --warning-traffic-in='' --critical-traffic-in='' --warning-traffic-out='' --critical-traffic-out='' --warning-read-iops='' --critical-read-iops='' --warning-write-iops='' --critical-write-iops='' --filter-counters='traffic' --change-short-output="- VM 'centreon-central'~~g"
Return :
OK: VM 'qemu/110'   Traffic In : 141.00 Kb/s, Traffic Out : 113.06 Kb/s | 'traffic_in'=140996.38b/s;;;0; 'traffic_out'=113057.79b/s;;;0;

This command Work in command line.
Centreon autodicovery find all VM, but I can't Save discovery.
I think (") is the problem but I need this to work.

I try this :
/usr/lib/centreon/plugins//centreon_proxmox_ve_restapi.pl --plugin apps::proxmox::ve::restapi::plugin --mode=vm-usage --hostname=192.168.122.254 --api-username='monitoring' --api-password='monitoring' --proto='https' --port='8006' --realm='pve' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --filter-name='centreon-central' --warning-cpu='80' --critical-cpu='90' --warning-memory='80' --critical-memory='90' --warning-traffic-in='' --critical-traffic-in='' --warning-traffic-out='' --critical-traffic-out='' --warning-read-iops='' --critical-read-iops='' --warning-write-iops='' --critical-write-iops='' --filter-counters='traffic' --change-short-output='- VM \'centreon-central\''~~g'
This dont Work too.
OK: VM 'qemu/110'  - VM 'centreon-central' Traffic In : 149.31 Kb/s, Traffic Out : 117.42 Kb/s | 'traffic_in'=149313.08b/s;;;0; 'traffic_out'=117418.83b/s;;;0;

May out its better to have output like :
OK: VM : qemu/110  - VM : centreon-central Traffic In : 149.31 Kb/s, Traffic Out : 117.42 Kb/s | 'traffic_in'=149313.08b/s;;;0; 'traffic_out'=117418.83b/s;;;0;
to use filter :
--change-short-output='- VM : $name$'~~g' to centreon autodisovery

Or Have an argument to not  display the VM name
Thank you a lot

**Comment by garnier-quentin** [comment]
try that: --change-short-output='- VM .centreon-central.~~g'
