### ISSUE TITLE
apps::protocols::tcp connections not closed after check

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2020]
Hi all,
im using centreon_protocol_tcp.pl to check if specific tcp ports it's open and responding on servers.
We are facing an issue with this plugin were connection will not be closed after check and after so many check port on server stuck and don't receive anymore connections so goes into critical state --> "Connection refused"

These are all connection in CLOSED_WAIT status made on target server
![image](https://user-images.githubusercontent.com/9050487/83017000-28618280-a023-11ea-8544-9a4608394f86.png)

To be able to receive connection again on server we need restart services 
Maybe adding a closing connection method after check if completed can be avoid this connection in pending state

Thanks

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test it ?

**Comment by R00T88** [comment]
Hi @garnier-quentin 
it works! Thanks

when rpm will be updated for  centreon_protocol_tcp.pl?

Thanks

**Comment by garnier-quentin** [comment]
It's already in unstable repository. you can update that package.
