### ISSUE TITLE
[network::cisco::smallbusiness::standard::snmp::plugin] Cisco SF220-24 CPU - Cant get a single value

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2022]
Hello,

Cannot get processor load information for **Cisco Small Business SF220-24 24-Port 10/100 Smart Switch**

```
./centreon_plugins.pl --plugin=network::cisco::smallbusiness::standard::snmp::plugin 
--mode=cpu --critical=',,98' --warning=',,90' 
--hostname='sw003' --snmp-community='public' --snmp-version='2c'

UNKNOWN: SNMP GET Request : Cant get a single value.
```

**Comment by Aleksey-Maksimov** [comment]
MIBs : [MIBs_Sx220_v1.1.1.2.zip](https://github.com/centreon/centreon-plugins/files/4689174/MIBs_Sx220_v1.1.1.2.zip)

**Comment by garnier-quentin** [comment]
Also need the snmpwalk.

**Comment by garnier-quentin** [comment]
Have you tried with cisco standard plugin ?

**Comment by Aleksey-Maksimov** [comment]
I can not get the full snmpwalk. I get a timeout. Perhaps you will tell me some narrower section than .1?

**Comment by Aleksey-Maksimov** [comment]
The standard plugin is not suitable. This is the Small Business series. I have a similar switch of a slightly different model SF200-24. And with SF200-24 [network::cisco::smallbusiness::standard::snmp::plugin]  works well.

**Comment by garnier-quentin** [comment]
I don't understand the mib. There is maybe: rlCpuCounters (.1.3.6.1.4.1.9.6.1.109.124)
But it don't understand the branch switch009 = .1.3.6.1.4.1.9.6.1.109

**Comment by Aleksey-Maksimov** [comment]
I can only get part of snmpwalk from the device, as some strange error occurs.

```
# snmpwalk -ObentU -v 1 -c 'public' SW003 > ./Switch_Cisco_SF220-24.snmpwalk_V1

Error: OID not increasing: .1.3.6.1.2.1.17.7.1.2.2.1.2.5.0.17.10.252.208.145
 >= .1.3.6.1.2.1.17.7.1.2.2.1.2.1.0.20.194.97.35.72
```


```
# snmpwalk -ObentU -v 2c -c 'public' SW003 > ./Switch_Cisco_SF220-24.snmpwalk_V2

Error: OID not increasing: .1.3.6.1.2.1.17.7.1.2.2.1.2.5.0.17.10.252.208.145
 >= .1.3.6.1.2.1.17.7.1.2.2.1.2.1.0.20.194.97.35.72
```


[Switch_Cisco_SF220-24.zip](https://github.com/centreon/centreon-plugins/files/4689439/Switch_Cisco_SF220-24.zip)

**Comment by garnier-quentin** [comment]
Could you snmpwalk with -Cc option ?

**Comment by Aleksey-Maksimov** [comment]
[Switch_Cisco_SF220-24.zip](https://github.com/centreon/centreon-plugins/files/4691375/Switch_Cisco_SF220-24.zip)

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin, 
Can I help you with something else to solve this problem?

**Comment by garnier-quentin** [comment]
Your file is not complete.

**Comment by Aleksey-Maksimov** [comment]
I can not give more information. This is all the switch gives through snmpwalk. We bought several of these switches and checked only the first of this batch. We will try to turn on and check other switches. I will report the result later.

**Comment by garnier-quentin** [comment]
Maybe we could do it by ssh (if we don't have the information in SNMP).

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin,
We tested several Cisco SF220-24 switches with different firmware versions. And everyone has the same situation. Using SNMP, we cannot see CPU utilization information. It is interesting that in the web interface of the switch there is information about the CPU utilization. I created a case for Cisco Technical Support to clarify the situation. As soon as I have new information I will inform you about it.

**Comment by Aleksey-Maksimov** [comment]
And by the way, according to the SSH protocol, information about CPU utilization is available.
```

SW003#show cpu utilization

CPU utilization service is on.

CPU utilization
---------------
five seconds: 3%; one minute: 7%; five minutes: 7%
```

**Comment by garnier-quentin** [comment]
I'm waiting. You can try the ssh plugin.

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin,
Cisco recognized the bug: https://quickview.cloudapps.cisco.com/quickview/bug/CSCvu70532
We are waiting for a new version of firmware.

**Comment by garnier-quentin** [comment]
Thanks for the feedback. It will help. I close it. You can put some informations (firmware) when cisco fixed the bug.

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin,
Cisco tech support advised that there are no plans to fix this issue. 
Perhaps this problem will never be fixed.
