### ISSUE TITLE
os::windows::snmp::plugin network ID and output

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2023]
Hi all,
im trying to configure network check via SNMP on windows 2012 R2 server with ony one network card attached called "ethernet 3".
To monitor it via ID how can i retrive it? or via name with one should i use?

If i use Traffic Global SNMP check:

/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=interfaces --hostname=xxxx --snmp-version='2c' --snmp-community='public'  --interface='.*' --name --add-status --add-traffic --critical-status='' --warning-in-traffic='80' --critical-in-traffic='90' --warning-out-traffic='80' --critical-out-traffic='90' --verbose --snmp-autoreduce

I receive this output:

Interface 'loopback_0' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_3' Status : notPresent (admin: down)
Interface 'ppp_1' Status : notPresent (admin: down)
Interface 'ethernet_11' Status : notPresent (admin: down)
Interface 'ethernet_10' Status : notPresent (admin: down)
Interface 'ethernet_12' Status : up (admin: up), Traffic In : 2.71Mb/s (0.01%), Traffic Out : 5.71Mb/s (0.02%)
Interface 'ethernet_4' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_5' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_6' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_7' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_8' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'tunnel_0' Status : down (admin: up)
Interface 'ethernet_9' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_13' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_14' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_15' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_16' Status : up (admin: up), Traffic In : 2.71Mb/s (0.01%), Traffic Out : 5.71Mb/s (0.02%)
Interface 'ethernet_17' Status : up (admin: up), Traffic In : 2.71Mb/s (0.01%), Traffic Out : 5.71Mb/s (0.02%)
Interface 'ethernet_18' Status : up (admin: up), Traffic In : 2.71Mb/s (0.01%), Traffic Out : 5.71Mb/s (0.02%)
Interface 'ethernet_19' Status : up (admin: up), Traffic In : 2.71Mb/s (0.01%), Traffic Out : 5.71Mb/s (0.02%)
Interface 'tunnel_1' Status : down (admin: up)
Interface 'tunnel_2' Status : down (admin: up)
Interface 'tunnel_3' Status : down (admin: up)
Interface 'ppp_0' Status : down (admin: up)
Interface 'ethernet_0' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_1' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped
Interface 'ethernet_2' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped

Multiple ethernets with same result and i cannot understand if it's correct or not because i have only on server.

![image](https://user-images.githubusercontent.com/9050487/83168934-8c16a900-a112-11ea-8840-b1a645218c66.png)

I would simply filter only for nic that i have on server
Can someone give me an input?

Thanks

**Comment by garnier-quentin** [comment]
You can filter it like that:
```
 --interface='ethernet_3' --name
```

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
if i filter like you suggested i receive this output


OK: Interface 'ethernet_3' Status : **notPresent** (admin: **down**), Traffic In : Buffer creation, Traffic Out : Buffer creation |
Interface 'ethernet_3' Status : notPresent (admin: down), Traffic In : Buffer creation, Traffic Out : Buffer creation

so i think it not match the right nic on the server
do you have idea?

Thanks

**Comment by Cool34000** [comment]
> Hi @garnier-quentin ,
> if i filter like you suggested i receive this output
> 
> OK: Interface 'ethernet_3' Status : **notPresent** (admin: **down**), Traffic In : Buffer creation, Traffic Out : Buffer creation |
> Interface 'ethernet_3' Status : notPresent (admin: down), Traffic In : Buffer creation, Traffic Out : Buffer creation
> 
> so i think it not match the right nic on the server
> do you have idea?
> 
> i cannot understand why ethernet from 16 till 19 are fulfilled with same data that are not present and ethernet_3 its reported as down
> 
> Thanks

Maybe "ethernet 3" (without the underdcore) ?

**Comment by R00T88** [comment]
Hi @Cool34000,
this is the output:

UNKNOWN: No entry found (maybe you should reload cache file)

**Comment by Cool34000** [comment]
Yes, I just checked on my servers and I have the same problem!
This may be a bug

**Comment by R00T88** [comment]
Hi @Cool34000,
i think only on windows plugin because on linux it works well

**Comment by Cool34000** [comment]
Got it!
Try this:
/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=interfaces --hostname=xxxx --snmp-version='2c' --snmp-community='public' --interface='ethernet_3' --name --add-status --add-traffic --critical-status='' --warning-in-traffic='80' --critical-in-traffic='90' --warning-out-traffic='80' --critical-out-traffic='90' --verbose --snmp-autoreduce  --oid-display='ifDesc' --oid-filter='ifDesc' -name

**Comment by R00T88** [comment]
Thanks @Cool34000 !!!
Got it working with identifieng correct ethernet with name as you suggested (ethernet_12)

Thanks
