### ISSUE TITLE
os::windows::snmp::plugin service mode

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2024]
Hi all,
im trying to check via snmp if a service it's running or not on windows server but i cannot get it working.

Servicename: CHTAgent

![image](https://user-images.githubusercontent.com/9050487/83395434-8ebb1c00-a3fa-11ea-8f87-227c8cac37ab.png)

/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=XXX --snmp-version='2c' --snmp-community='public'  --service='CHTAgent' --regexp --state=''

i always receive this output

OK: All service states are ok |

What im doing wrong?

Thanks

**Comment by garnier-quentin** [comment]
Could you provide the result of ```--mode=list-services``` ?

**Comment by R00T88** [comment]
Hi @garnier-quentin,
thanks for quick response

List services:
[name = Amazon SSM Agent] [operating = active] [installed = installed]
[name = Application Host Helper Service] [operating = active] [installed = installed]
[name = Application Information] [operating = active] [installed = installed]
[name = Background Intelligent Transfer Service] [operating = active] [installed = installed]
[name = Background Tasks Infrastructure Service] [operating = active] [installed = installed]
[name = Base Filtering Engine] [operating = active] [installed = installed]
[name = CNG Key Isolation] [operating = active] [installed = installed]
[name = COM+ Event System] [operating = active] [installed = installed]
[name = CloudHealth Agent] [operating = active] [installed = installed]
[name = Configuration Manager Remote Control] [operating = active] [installed = installed]
[name = Cryptographic Services] [operating = active] [installed = installed]
[name = DCOM Server Process Launcher] [operating = active] [installed = installed]
[name = DHCP Client] [operating = active] [installed = installed]
[name = DNS Client] [operating = active] [installed = installed]
[name = Diagnostic Policy Service] [operating = active] [installed = installed]
[name = Diagnostics Tracking Service] [operating = active] [installed = installed]
[name = Distributed Transaction Coordinator] [operating = active] [installed = installed]
[name = Ec2Config] [operating = active] [installed = installed]
[name = Group Policy Client] [operating = active] [installed = installed]
[name = IKE and AuthIP IPsec Keying Modules] [operating = active] [installed = installed]
[name = IPsec Policy Agent] [operating = active] [installed = installed]
[name = Local Session Manager] [operating = active] [installed = installed]
[name = NSClient++ Monitoring Agent] [operating = active] [installed = installed]
[name = Netlogon] [operating = active] [installed = installed]
[name = Network Connections] [operating = active] [installed = installed]
[name = Network List Service] [operating = active] [installed = installed]
[name = Network Location Awareness] [operating = active] [installed = installed]
[name = Network Store Interface Service] [operating = active] [installed = installed]
[name = Plug and Play] [operating = active] [installed = installed]
[name = Power] [operating = active] [installed = installed]
[name = RPC Endpoint Mapper] [operating = active] [installed = installed]
[name = Redis] [operating = active] [installed = installed]
[name = Remote Desktop Configuration] [operating = active] [installed = installed]
[name = Remote Desktop Services] [operating = active] [installed = installed]
[name = Remote Desktop Services UserMode Port Redirector] [operating = active] [installed = installed]
[name = Remote Procedure Call (RPC)] [operating = active] [installed = installed]
[name = SMS Agent Host] [operating = active] [installed = installed]
[name = SNMP Service] [operating = active] [installed = installed]
[name = Security Accounts Manager] [operating = active] [installed = installed]
[name = Server] [operating = active] [installed = installed]
[name = SplunkForwarder Service] [operating = active] [installed = installed]
[name = System Event Notification Service] [operating = active] [installed = installed]
[name = System Events Broker] [operating = active] [installed = installed]
[name = TCP/IP NetBIOS Helper] [operating = active] [installed = installed]
[name = Task Scheduler] [operating = active] [installed = installed]
[name = Trend Micro Deep Security Agent] [operating = active] [installed = installed]
[name = Trend Micro Deep Security Notifier] [operating = active] [installed = installed]
[name = Trend Micro Monitoraggio di Deep Security] [operating = active] [installed = installed]
[name = User Access Logging Service] [operating = active] [installed = installed]
[name = User Profile Service] [operating = active] [installed = installed]
[name = WMI Performance Adapter] [operating = active] [installed = installed]
[name = WinHTTP Web Proxy Auto-Discovery Service] [operating = active] [installed = installed]
[name = Windows Connection Manager] [operating = active] [installed = installed]
[name = Windows Event Log] [operating = active] [installed = installed]
[name = Windows Firewall] [operating = active] [installed = installed]
[name = Windows Font Cache Service] [operating = active] [installed = installed]
[name = Windows Management Instrumentation] [operating = active] [installed = installed]
[name = Windows Process Activation Service] [operating = active] [installed = installed]
[name = Windows Remote Management (WS-Management)] [operating = active] [installed = installed]
[name = Windows Time] [operating = active] [installed = installed]
[name = Windows Update] [operating = active] [installed = installed]
[name = Workstation] [operating = active] [installed = installed]
[name = World Wide Web Publishing Service] [operating = active] [installed = installed]

**Comment by garnier-quentin** [comment]
It's not started (with your list). You can to get an error it's not started ?

**Comment by R00T88** [comment]
Hi @garnier-quentin,
yes it started --> [name = CloudHealth Agent] [operating = active] [installed = installed]

if i try with this

/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=euitpopb2n003.randstaditaly.it --snmp-version='2c' --snmp-community='public'  --service='CloudHealth Agent' --warning=1: --critical=@0:0

Result:

OK: All service states are ok |

is it correct?

**Comment by garnier-quentin** [comment]
It's quite the same: ```--warning=1: --critical=@0:0```
Use it like that:
```
/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=euitpopb2n003.randstaditaly.it --snmp-version='2c' --snmp-community='public' --service='CloudHealth Agent' --critical=1: --verbose
```

You can see if it matches with --verbose (details).

**Comment by R00T88** [comment]
Working Thanks!
