### ISSUE TITLE
cloud::aws::ebs::plugin bug

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2032]
Hi all,
i'm just testing aws ebs plugin but there is some issue with parameters volumeid and warning-iops-consumed-rw

Exmaple:
/usr/lib/centreon/plugins//centreon_aws_ebs_api.pl --plugin=cloud::aws::ebs::plugin --mode=volumeiops --custommode='awscli' --aws-secret-key='***' --aws-access-key='***' --region='eu-west-1' --volumeid='vol-xxx' --proxyurl=''  --filter-metric='VolumeThroughputPercentage' --warning-iops-throughput='' --critical-iops-throughput='' --warning-iops-consumed-rw='' --critical-iops-consumed-rw='' --warning-iops-queue-length='' --critical-iops-queue-length='' --verbose

Output:
Unknown option: volumeid at /usr/lib/centreon/plugins//centreon_aws_ebs_api.pl line 141.
 Unknown option: warning-iops-consumed-rw at /usr/lib/centreon/plugins//centreon_aws_ebs_api.pl line 141.

if i don't specify --volumeid parameters it report me that was not provided

UNKNOWN: Need to specify --volumeid option.

Thanks

**Comment by thibaults-centreon** [comment]
Hello,
sorry about that, it's a typo in the code.
Please try _--volume-id_  
I'll correct this asap

**Comment by R00T88** [comment]
Hi @thibaults-centreon ,
thanks for quick reply i think same issue for parameters  warning-iops-consumed-rw

Thanks

**Comment by R00T88** [comment]
Hi @thibaults-centreon ,
with --volume-id it works but if i select metric VolumeThroughputPercentage and VolumeConsumedReadWriteOps it return always 0

OK: 'vol-xxx' Statistic 'Average' Metrics IOPS Throughput: 0.00 % | 'vol-xxx~average#ebs.volume.iops.throughput.percentage'=0.00%;;;;
AWS EBS Volume'vol-xxx'
    Statistic 'Average' Metrics IOPS Throughput: 0.00 %

OK: 'vol-xxx' Statistic 'Average' Metrics IOPS Consumed: 0.00  | 'vol-xxx~average#ebs.volume.iops.consumed.count'=0.00;;;;
AWS EBS Volume'vol-xxx'
    Statistic 'Average' Metrics IOPS Consumed: 0.00

but if i filter for VolumeWriteOps and VolumeReadOps it gives me value

OK: 'vol-xxx' Statistic 'Average' Metrics IOPS Write: 1060.70  | 'vol-xxx~average#ebs.volume.iops.write.count'=1060.70;;;;
AWS EBS Volume'vol-xxx'
    Statistic 'Average' Metrics IOPS Write: 1060.70

Thanks

**Comment by thibaults-centreon** [comment]
Hello,
The related PR should fix the issue. The fixed rpm will be available in the unstable repo shortly.
Regarding the 0 metric values however, I don't think this is related to our plugin.
Indeed the metrics you describe are only available for specific EBS configurations, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cloudwatch_ebs.html.
Hence I presume this is why you're getting 0 values for them.

**Comment by R00T88** [comment]
Hi @thibaults-centreon ,
ok thanks!
Do you think it's possible to have a metric that calculate iops like this?

IOPS USED = (READ OPS+ WRITE OPS) / Time (in seconds)

(statistics sum)

for example:

(VolumeReadOps is 3,027,754 + VolumeWriteOps is 12,587) / (60 seconds x 15 minutes (Period))

= 3,040,341/ 900

= 3,378 Total IOPS

**Comment by thibaults-centreon** [comment]
You may wanna use the --extend-perfdata-group option to achieve this. This syntax should do the trick:
--extend-perfdata-group=',total_rw_iops,sum(.*(read|write).count)'

The calculation time can be overridden with --timeframe and --period
