### ISSUE TITLE
apps::protocols::http::plugin - method PATCH / PUT with DATA

### ISSUE THREAD

**Issue by BertrandJO** [centreon/centreon-plugins#2036]
Hi,

I'm trying to monitor a web service with apps::protocols::http::plugin using --method=PATCH and a DATA content (--data=xxxxx).

Reading my Nginx logs, I see that the request is sent with the POST method whenever I set the --data parameter, without the --data, method sent to the web server is the good one PATCH.

I have the same issue using PUT method.

Same request using curl gave me the expected result.

Kind regards,

Bertrand.

**Comment by UrBnW** [comment]
#2038 should help you :)

**Comment by garnier-quentin** [comment]
I have done a patch. could you test it in your case ?

**Comment by BertrandJO** [comment]
Hi,

After patching, my request arrived with the desired method so the change is fine.

I now receive the following error, I need to check if my command is well formatted.

<html><body><h1>Failed to process the request</h1><p>**Error processing POST request** </p><p>javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.</p></body></html><p>null</p></body></html>

**Comment by garnier-quentin** [comment]
Ok that's nice.

**Comment by BertrandJO** [comment]
Hi,

After few tests, I can notice there is still an issue in case of a PATCH request. The command with the PATCH method do not send DATA values ( **--data='{"status": "AVAILABLE"}'  --header='Content-Type:application/json'**).

Here are the two lines from the nginx logs :
 
[08/Jun/2020:09:58:45 +0200] "POST /************/ HTTP/1.1" 202 5 "-" "centreon::plugins::backend::http::useragent" **[{\x22status\x22: \x22AVAILABLE\x22}]**
[08/Jun/2020:09:59:08 +0200] "PATCH /************/ HTTP/1.1" 500 242 "-" "centreon::plugins::backend::http::useragent" **[-]**

**Comment by garnier-quentin** [comment]
I have done a test and it send it:
```
perl centreon_plugins.pl --plugin=apps/protocols/http/plugin.pm --mode=expected-content --method=PATCH --header='Content-Type: application/json' --data='{ "tplop": 1 }' --hostname=127.0.0.1 --debug
UNKNOWN: 500 Can't connect to 127.0.0.1:80 (Connection refused) |
======> request send
PATCH http://127.0.0.1/
User-Agent: centreon::plugins::backend::http::useragent
Content-Type:  application/json

{ "tplop": 1 }
======> response done
500 Can't connect to 127.0.0.1:80 (Connection refused)
Content-Type: text/plain
Client-Date: Mon, 08 Jun 2020 08:06:43 GMT
Client-Warning: Internal response

Can't connect to 127.0.0.1:80 (Connection refused)

Connection refused at /usr/share/perl5/LWP/Protocol/http.pm line 50.
```

Could you provide the --debug result ?

**Comment by BertrandJO** [comment]
Here are the result and the associated command : 

======> request send
PATCH https://xxxxxxxxx/xxxxxxxx/xxxxxxxxxx
Cache-Control: no-cache
Connection: keep-alive
Accept: */*
Accept-Encoding:  deflate
Authorization: Token xxxxxxxxxxxxxxxxxxxxx
User-Agent: centreon::plugins::backend::http::useragent
X-Forwarded-For: xxx.xxx.xxx.xxx

======> response done
HTTP/1.1 500 Internal Server Error

and the command : 

centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=xxxxxxxx --urlpath=/xxxxxxxx/xxxxxxxxxx --proto=https --expected-string='\"status_code\"\: 1000' --header='Accept:*/*'   --header='Accept-Encoding: deflate'   --header='Authorization:Token xxxxxxxxxxxxxxxxxxxxx'   --header='Cache-Control:no-cache'   --header='Connection:keep-alive'   --header='cache-control:no-cache'   --header='X-Forwarded-For:xxx.xxx.xxx.xxx'   --data='{"status": "AVAILABLE"}' --method=PATCH  --header='Content-Type:application/json' --debug

**Comment by garnier-quentin** [comment]
You need to set following option:
```--header='Content-Type: application/json' ```

**Comment by BertrandJO** [comment]
It is set, just before --debug

**Comment by garnier-quentin** [comment]
It's working for me:
```
perl centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=127.0.0.1 --urlpath=/xxxxxxxx/xxxxxxxxxx --proto=https --expected-string='"status_code": 1000' --header='Accept:/' --header='Accept-Encoding: deflate' --header='Authorization:Token xxxxxxxxxxxxxxxxxxxxx' --header='Cache-Control:no-cache' --header='Connection:keep-alive' --header='cache-control:no-cache' --header='X-Forwarded-For:xxx.xxx.xxx.xxx' --data='{"status": "AVAILABLE"}' --method=PATCH --header='Content-Type:application/json' --debug
UNKNOWN: 500 Can't connect to 127.0.0.1:443 (Connection refused) |
======> request send
PATCH https://127.0.0.1/xxxxxxxx/xxxxxxxxxx
Cache-Control: no-cache
Connection: keep-alive
Accept: /
Accept-Encoding:  deflate
Authorization: Token xxxxxxxxxxxxxxxxxxxxx
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/json
X-Forwarded-For: xxx.xxx.xxx.xxx

{"status": "AVAILABLE"}
======> response done
500 Can't connect to 127.0.0.1:443 (Connection refused)
Content-Type: text/plain
Client-Date: Mon, 08 Jun 2020 08:38:45 GMT
Client-Warning: Internal response

Can't connect to 127.0.0.1:443 (Connection refused)

Connection refused at /usr/share/perl5/LWP/Protocol/http.pm line 50.
```
Do you get the last version ?

**Comment by BertrandJO** [comment]
Maybe that's my problem, let me check this point.

Thanks

**Comment by BertrandJO** [comment]
strange thing, without UrBnW change

======> request send
POST https://xxxxxxxxxxxxxxxxxxxxxxxx
Cache-Control: no-cache
Connection: keep-alive
Accept: */*
Accept-Encoding:  deflate
Authorization: Token xxxxxxxxxxxx
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/json
X-Forwarded-For: xxxxxxxxxxxxxxxxxx

**{"status": "AVAILABLE"}**
======> response done

with the change, the data field value does not appear anymore in the output, reading the code, I cannot understand why

**Comment by UrBnW** [comment]
My change was a proposal and has not been merged, the correct patch is https://github.com/centreon/centreon-plugins/commit/fcac48977ba747b5646e374a93c5b0b34d4d5341.
You should then test using the last code version, so the _master_ branch.

**Comment by BertrandJO** [comment]
ok, thanks, I did not see the whole changes, sorry for that.

Thanks once for your help

**Comment by BertrandJO** [comment]
works fine after a full sync, great !
