### ISSUE TITLE
[apps::vmware::connector::plugin] Exclude unused NICs

### ISSUE THREAD

**Issue by ruliane** [centreon/centreon-plugins#2039]
Hi,

Some of my hosts have several unused NIC. They appears as CRITICAL:
`CRITICAL: Host '[redacted]' : physical interface 'vmnic0' status down - physical interface 'vmnic1' status down`

Is there a was to exclude them?

Otherwise, can I submit several NIC to check? I tried `--nic-name='vmnic2,vmnic3,vmnic4'` and `--nic-name='vmnic2' --nic-name='vmnic4'` without success.

**Comment by garnier-quentin** [comment]
You can use following option. By default, it's:
```
--critical-link-status='%{link_status} !~ /up/'
```

You can do:
```
--critical-link-status='%{display} !~ /vmnic[01]/ and %{link_status} !~ /up/'
```

**Comment by ruliane** [comment]
Thank you for this suggestion, it works. I will now find a way to set it in my checkcommand.

Suggestion: Supporting multiple names in `--nic-name` parameter would be wonderful.
