### ISSUE TITLE
Plugin F5 BigIP snmp ; mode pool-status ; issue with thresholds

### ISSUE THREAD

**Issue by qladriere** [centreon/centreon-plugins#2040]
## Bug/Question
Just tested the mode pool-status with warning & critical thresholds and way to report warning or critical event doesn't match with what I expect. Indeed, goal is to be able to get warning or critical event if number of members is less than x. However, when I tried the plugin with this option, it returns a warning or critical event only if number of members is higher than x. In some cases it could be useful (for example, if application is active passive and only one server must be active at a time) but when you have an application using 10 servers, for example, we also expect an alert if less than 5 servers are running.

Should be possible to add this ?

**Comment by Sims24** [comment]
Hi, 

You must follow the plugin threshold guidelines: https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

--warning=10: will trigger a warning where the metric value drops below 10. 

Simon
