### ISSUE TITLE
[apps::vmware::connector::plugin] "Can't get a single datastore" with mode datastore-host

### ISSUE THREAD

**Issue by ruliane** [centreon/centreon-plugins#2041]
Hi,

My datastore is correctly detected at a vCenter level, with `--datastore-usage`:
```
[root@centreon-central vsan-sdk-perl]# /usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --connector-hostname='127.0.0.1' --container 'srv-vcenter' --mode=datastore-usage --datastore-name 'vsanDatastore'
OK: Datastore 'vsanDatastore' accessible 1, Usage Total: 11.64 TB Used: 1.17 TB (10.01%) Free: 10.48 TB (89.99%), Provisioned: 1.67 TB (14.37%) | 'used'=1281168833736B;;;0;12802545188864 'free'=11521376355128B;;;0;12802545188864 'used_prct'=10.01%;;;0;100 'provisioned'=1839301463240B;;;0;12802545188864
```

But when I want to discover it with `--datastore-host`, here is what I get:
```
[root@centreon-central vsan-sdk-perl]# /usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --connector-hostname='127.0.0.1' --container 'srv-vcenter' --mode=datastore-host --esx-hostname='[redacted]'
UNKNOWN: Can't get a single datastore. |
```

I suspect this is related to issue #900, and might be solved in a newer version. I just ran "yum update centreon-plugins-*".

VSAN SDK is installed.

**Comment by garnier-quentin** [comment]
For vsan, you need to use: vsan-cluster-usage

**Comment by ruliane** [comment]
Can I get vSAN usage/iops only for a given host?

**Comment by garnier-quentin** [comment]
I don't think we can get that information from vcenter.

**Comment by ruliane** [comment]
Thanks for your answer.

I'm looking for a way to monitor free space on datastores (vSAN or traditional) *related to a specific host*. `--datastore-host` works for iops, not for used space.
This is visible in vSphere, but probably not easy to fetch through API. :/

**Comment by garnier-quentin** [comment]
The disk is shared with different hosts. Why do you want to check the usage for a specific host on the vsan ?

**Comment by ruliane** [comment]
This is because I have a host-oriented monitoring. Furthermore, datastores are not always shared across all hosts; I don't want a vSAN failure to put all my hosts in a CRITICAL state.

Is there a better approach to monitor storage usage?

**Comment by garnier-quentin** [comment]
If the information is in the vcenter. maybe we could get it. need to look more deeply.

**Comment by garnier-quentin** [comment]
Could you show me that information in your vcenter with a screenshot ? Because i don't find it with the documentation.

**Comment by ruliane** [comment]
In _Hosts and Cluster_ view, I can see datastores attached to my host, including VSAN ones.
![image](https://user-images.githubusercontent.com/5471186/85555563-55a34f80-b626-11ea-96db-b41d7d8ec522.png)

**Comment by garnier-quentin** [comment]
It's not the global vsan usage ? You have 12To of local disks on one host ?

**Comment by ruliane** [comment]
> 
> 
> It's not the global vsan usage ? You have 12To of local disks on one host ?

Yes, it *is* the global VSAN usage !
As for any shared storage (VSAN, iSCSI, NFS), it is displayed in each host view. If it fails, any related host would be impacted.

**Comment by garnier-quentin** [comment]
You have the vsan usage with datastore-usage mode no ?

**Comment by ruliane** [comment]
`datastore-usage` does not display VSAN datastores. That's why I mentioned issue #900 in my first post: this bug was fixed in Jan. 2019.

**Comment by garnier-quentin** [comment]
Have you installed vsan sdk perl for your vmware connector ? https://github.com/centreon/centreon-plugins/issues/1785

**Comment by ruliane** [comment]
Sure, and `vsan-cluster-usage` works perfectly.

What was modified to fix #900? I will check it against my own plugin.

**Comment by garnier-quentin** [comment]
You show me the result i see in the vcenter:
```
OK: Datastore 'vsanDatastore' accessible 1, Usage Total: 11.64 TB Used: 1.17 TB (10.01%) Free: 10.48 TB (89.99%), Provisioned: 1.67 TB (14.37%) | 'used'=1281168833736B;;;0;12802545188864 'free'=11521376355128B;;;0;12802545188864 'used_prct'=10.01%;;;0;100 'provisioned'=1839301463240B;;;0;12802545188864
```

I don't understand what do you want.

**Comment by ruliane** [comment]
I want to check free/used space of all datastores related to a specific host, including VSAN ones.
`datastore-usage` has no capability to filter by host, and `datastore-host` does not detects VSAN datastores when used with `--esx-hostname`.

**Comment by garnier-quentin** [comment]
It's the same value. But you want to get datastores linked to a ESX host ?

**Comment by ruliane** [comment]
> But you want to get datastores linked to a ESX host ?
Exactly!

Considering the following setup:
```
 -----------    -----------    -----------
|   host1   |  |   host2   |  |   host3   |
 -----------    -----------    -----------
 --------------------------    -----------
|           vSAN           |  |   local   |
|          storage         |  |  storage  |
 --------------------------    -----------
```

Should my vSAN fail, I need host1 and host2 to get into a CRITICAL state. However, host3 should stay OK.

**Comment by garnier-quentin** [comment]
Ok i see. I will add it. I have some tickets for the connector vmware. I will do all developments.

**Comment by ruliane** [comment]
> 
> 
> Ok i see. I will add it. I have some tickets for the connector vmware. I will do all developments.

That would be great, thank you !

**Comment by garnier-quentin** [comment]
I added the ```--filter-host``` in ```datastore-usage``` mode. You need also the last version of centreon-vmware connector.

**Comment by ruliane** [comment]
That sounds great, though I cannot try it right now.

Thanks for your work!
