### ISSUE TITLE
AIX fatpack missing mode

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2043]
Hi,

Sounds like there's a missing mode in AIX local plugin, after the recent changes :
```
./centreon_aix_local.pl
UNKNOWN: Cannot load module --custommode. 
Can't locate centreon/plugins/ssh.pm in @INC at ./centreon_aix_local.pl line 5441.
```

Thank you 👍

**Comment by garnier-quentin** [comment]
Could you test ?
http://yum.centreon.com/standard/19.10/el7/unstable/noarch/plugins/centreon-plugins-20200608-115235/centreon-plugin-Operatingsystems-Aix-Local-20200608-115235.el7.centos.noarch.rpm

**Comment by UrBnW** [comment]
Perfect, thank you Quentin 👍
