### ISSUE TITLE
network::paloalto::snmp::plugin skipped interface traffic

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#2044]
Hello, 

I have issue monitoring interfaces on a PaloAlto VM. The check returns skipped for IN/OUT traffic even if i am sure there is traffic. The check works fine with some ipsec tunnels but not on the firewall interface.

this is the syntaxe: 
/usr/lib/centreon/plugins/centreon_paloalto.pl --plugin=network::paloalto::snmp::plugin --mode=interfaces --hostname=10.6.1.254 --snmp-version='2c' --snmp-community='my_commune'  --interface='^ethernet1/2$' --name --add-status --add-traffic --warning-in-traffic='80' --critical-in-traffic='90' --warning-out-traffic='80' --critical-out-traffic='90' --verbose

Thre result 

OK: Interface 'ethernet1/2' Status : up (admin: up), Traffic In : skipped, Traffic Out : skipped |

Am i Missing something please ?

Thank you

**Comment by garnier-quentin** [comment]
Maybe because the traffic is 0. Use that option: --no-skipped-counters
