### ISSUE TITLE
 [apps::vmware::connector::plugin] Extended information lost with --mode=health-host and --warning-problems-yellow

### ISSUE THREAD

**Issue by ruliane** [centreon/centreon-plugins#2045]
Using _apps::vmware::connector::plugin_ with `--mode=health-host` against a unhealthy host gives the following:
> OK: 1 total health issue(s) found - Host '[redacted]' : status connected - 46 health checks are green, 46 total health issue(s) found, 1 yellow health issue(s) found, 0 red health issue(s) found - fan sensor Cooling Unit 1 Fans: Sensor is operating under conditions that are non-critical

A fan is faulty, however status is still "OK". Let's set a threshold with `--warning-problems-yellow=0`. The result is now:
> WARNING: Host '[redacted]' : 1 yellow health issue(s) found

Status is WARNING as expected but I lose information about what is wrong.
Is it possible to add the same extended information in WARNING and CRITICAL states?

Note: I don't know if the same thing happens with `--critical-problems-red`, since I don't have any critical host.

**Comment by garnier-quentin** [comment]
Have you tried with --verbose ?

**Comment by ruliane** [comment]
Indeed, extended state information now contains useful information:

> checking host '[redacted]'
>     status connected
>     46 health checks are green, 46 total health issue(s) found, 1 yellow health issue(s) found, 0 red health issue(s) found
>     fan sensor Cooling Unit 1 Fans: Sensor is operating under conditions that are non-critical

Thanks for tip.
