### ISSUE TITLE
[storage::netgear::readynas::snmp::plugin] --mode=hardware UNKNOWN: SNMP Table Request : Unknown Object Identifier

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2049]
Centreon Plugins: 20200410
ReadyNAS 6.10.3
centreon_plugins.pl --hostname=x.x.x.x --snmp-community=public --snmp-version=2c --plugin=storage::netgear::readynas::snmp::plugin --mode=hardware --component=.* --filter= --warning='' --critical=''
UNKNOWN: SNMP Table Request : Unknown Object Identifier

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by joschi99** [comment]
Done some test, it's working with some error exception:

```
./centreon_plugins.pl --hostname=x.x.x.x --snmp-community=public --snmp-version=2c --plugin=storage::netgear::readynas::snmp::plugin --mode=hardware --component=.* --filter= --warning='' --critical='' --verbose
Argument "v6" isn't numeric in numeric eq (==) at /usr/lib/centreon/plugins/storage/netgear/readynas/snmp/mode/components/disk.pm line 69.
Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/storage/netgear/readynas/snmp/mode/components/temperature.pm line 72.
Use of uninitialized value $options{"value"} in pattern match (m//) at /usr/lib/centreon/plugins/centreon/plugins/templates/hardware.pm line 481.
Use of uninitialized value $options{"value"} in pattern match (m//) at /usr/lib/centreon/plugins/centreon/plugins/templates/hardware.pm line 481.
Use of uninitialized value $options{"value"} in pattern match (m//) at /usr/lib/centreon/plugins/centreon/plugins/templates/hardware.pm line 481.
Use of uninitialized value $options{"value"} in pattern match (m//) at /usr/lib/centreon/plugins/centreon/plugins/templates/hardware.pm line 481.
Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/storage/netgear/readynas/snmp/mode/components/temperature.pm line 76.
UNKNOWN: Temperature '1_armada_thermal-virtual--temp1' status is . | 'temp_1_armada_thermal-virtual--temp1'=46F;;;; 'count_disk'=4;;;; 'count_fan'=3;;;; 'count_temperature'=1;;;; 'count_volume'=1;;;;
checking power supply
checking fan
fan '1' status is ok.
fan '2' status is ok.
fan '3' status is ok.
checking disks
disk '1' status is ONLINE [temperature:  (temperature 32]
disk '2' status is ONLINE [temperature:  (temperature 34]
disk '3' status is ONLINE [temperature:  (temperature 35]
disk '4' status is ONLINE [temperature:  (temperature 33]
checking volume
volume 'DATA' status is REDUNDANT [instance: 1]
checking temperatures
temperature '1_armada_thermal-virtual--temp1' status is  [value = 46F]
```

**Comment by garnier-quentin** [comment]
Could you test it again ?

**Comment by joschi99** [comment]
```
 ./centreon_plugins.pl --hostname=x.x.x.x --snmp-community=public --snmp-version=2c --plugin=storage::netgear::readynas::snmp::plugin --mode=hardware --component=.* --filter= --warning='' --critical='' --verbose
UNKNOWN: Cannot load module 'storage::netgear::readynas::snmp::mode::components::disk'.
Global symbol "$temperature_string" requires explicit package name at /usr/lib/centreon/plugins/storage/netgear/readynas/snmp/mode/components/disk.pm line 69.
Global symbol "$temperature_string" requires explicit package name at /usr/lib/centreon/plugins/storage/netgear/readynas/snmp/mode/components/disk.pm line 70.
Compilation failed in require at /usr/lib/centreon/plugins/centreon/plugins/misc.pm line 222.
```

**Comment by garnier-quentin** [comment]
You can test it again. Sorry....

**Comment by joschi99** [comment]
Hi @garnier-quentin,
seem's ok now:
./centreon_plugins.pl --hostname=x.x.x.x --snmp-community=public --snmp-version=2c --plugin=storage::netgear::readynas::snmp::plugin --mode=hardware --component=.* --filter= --warning='' --critical='' --verbose
OK: All 9 components are ok [4/4 disk, 3/3 fan, 1/1 temperatures, 1/1 volume]. | 'temp_1_armada_thermal-virtual--temp1'=46C;;;; 'count_disk'=4;;;; 'count_fan'=3;;;; 'count_temperature'=1;;;; 'count_volume'=1;;;;
checking power supply
checking fan
fan '1' status is ok.
fan '2' status is ok.
fan '3' status is ok.
checking disks
disk '1' status is ONLINE [temperature: 32C]
disk '2' status is ONLINE [temperature: 34C]
disk '3' status is ONLINE [temperature: 35C]
disk '4' status is ONLINE [temperature: 33C]
checking volume
volume 'DATA' status is REDUNDANT [instance: 1]
checking temperatures
temperature '1_armada_thermal-virtual--temp1' status is n/a [value = 46C]

**Comment by garnier-quentin** [comment]
Thanks for the feedback!

**Comment by joschi99** [comment]
Hi @garnier-quentin,
seem's that we have now some problem on v4:
```
OK: All **0** components are ok []. |
checking power supply
checking fan
checking disks
checking volume
checking temperatures
```

**Comment by garnier-quentin** [comment]
Could you provide the full snmpwalk for v4 ?

**Comment by joschi99** [comment]
As you can see this Readynas has firmware Radiator 4.2.31
![readynas](https://user-images.githubusercontent.com/6400595/84658954-f737ec00-af16-11ea-8aaa-d11237b56012.png)
[netgear-v4-walk.zip](https://github.com/centreon/centreon-plugins/files/4780278/netgear-v4-walk.zip)

**Comment by garnier-quentin** [comment]
Could you do a snmpwalk on .1.3.6.1.4.1.4526.18 ? I don't see OID for that branch.

**Comment by joschi99** [comment]
there is no OID available:
snmpwalk -v2c -cpublic x.x.x.x .1.3.6.1.4.1.4526.18
SNMPv2-SMI::enterprises.4526.18 = No Such Object available on this agent at this OID
