### ISSUE TITLE
Plugin [network::cisco::3750::plugin mode=environment] 

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#205]
Hi!
There are several Cisco routers, the Cisco 3845, 7201, 7206 and 7606.
Performance Data:
'voltage Voltage 4' = 1203V ;; 1080 1320 ;; 'voltage_Voltage 2' = 5153V ;; 4635: 5665 ;; 'voltage_Voltage 1' = 3284V ;; 2970: 3630 ;; 'voltage_Voltage 3' = 2525V ;; 2250 2750 ;;
LUTS
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusDescr.1 = STRING: Voltage 1
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusDescr.2 = STRING: Voltage 2
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusDescr.3 = STRING: Voltage 3
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusDescr.4 = STRING: Voltage 4
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusValue.1 = INTEGER: 3284
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusValue.2 = INTEGER: 5153
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusValue.3 = INTEGER: 2525
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageStatusValue.4 = INTEGER: 1203
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdLow.1 = INTEGER: 2970
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdLow.2 = INTEGER: 4635
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdLow.3 = INTEGER: 2250
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdLow.4 = INTEGER: 1080
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdHigh.1 = INTEGER: 3630
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdHigh.2 = INTEGER: 5665
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdHigh.3 = INTEGER: 2750
CISCO-ENVMON-MIB :: ciscoEnvMonVoltageThresholdHigh.4 = INTEGER: 1320

All in thousands, respectively, on the same charts. The temperature in the ten, the voltage - thousands.
How can I fix it? Cisco standard outputs a voltage in millivolts, i.e. you must divide the result by 1000.
p.s. Use the plugin since 3750 I have not found a specific routers.

With best wishes.

**Comment by maksimatveev** [comment]
Cisco standard outputs a voltage in millivolts, i.e. you must divide the result by 100.

**Comment by maksimatveev** [comment]
To work around this problem change the file environment.pm so:

228: value => $voltage_value/1000,
229: critical => $voltage_low/1000 . ":" . $$voltage_high/1000

Now, the voltage is displayed in volts and the schedule looks readable.

**Comment by garnier-quentin** [comment]
Could you test it please ?
