### ISSUE TITLE
redis silently fails and centreon falls back to writing to statefile instead

### ISSUE THREAD

**Issue by steaksauce-** [centreon/centreon-plugins#2051]
## Bug

When using the `network::fortinet::fortigate::snmp::plugin`  with the `vdom-usage` mode, I want to set `Redis` as my state file. However, when I pass in the flags for Redis, nothing is passed on to Redis, and the plugin is still trying to write to a state file (which it does not have permissions to, and we are using distributed monitoring).

On a development server where the monitoring plugin user has permissions to write to the statefile directory, I pass in the Redis flag which seems to be ignored as it still writes out to the state file and does not pass anything into Redis.

It looks like Redis support was added per #439

### Expected Behavior 
I would expect that the following command would not even attempt to write to a statefile and send the data to `Redis`.
```
/usr/lib64/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin network::fortinet::fortigate::snmp::plugin --mode vdom-usage --hostname somehost.local --snmp-community somecommunity --snmp-port 161 --redis-server db02 --redis-db 3 --warning-cpu-utilization 75 --critical-cpu-utilization 83 --filter-perfdata cpu --filter-vdomain root
```

EDIT 1:
I would also expect that a connection would not fail silently, and it would be useful not to fall back on the statefile so that the statefile is never accidentally used when specifying memcahced or redis.

#### Notes
It's worth noting that I do have `perl-Redis` installed, as the module is needed for the command to run successfully when using `Redis` flags.

**Comment by Sims24** [comment]
Hi @steaksauce- 

We need to take a closer look on this one. Maybe @garnier-quentin could help. If you're available for a remote session that could save us a Redis installation 

If you can add somme debug, like a dumper printing the content of the object the eval initializes it could help.

Let us know ;) 
Simon

**Comment by garnier-quentin** [comment]
I think there is an issue with redis connection. 
Could you add following lines (last 3 lines) ?
```
eval {
            $self->{redis_cnx} = Redis->new(
                server => $options{option_results}->{redis_server},
                eval $self->{redis_attributes}
            );
            if (defined($self->{redis_cnx}) &&
                defined($options{option_results}->{redis_db}) &&
                $options{option_results}->{redis_db} ne ''
                ) {
                $self->{redis_cnx}->select($options{option_results}->{redis_db});
            }
        };
        if ($@) {
           $self->{output}->output_add(long_msg => "redis error: $@", debug => 1);
        }
```

And after: use --debug option to get the result.

**Comment by steaksauce-** [comment]
Here is the output after adding the changes to `centreon/plugins/statefile.pm`

```
UNKNOWN: Cannot write statefile '/var/lib/centreon/centplugins/fortinet_fortigate_96.5.254.13_161_vdom-usage_a181a603769c1f98ad927e7367c7aa51_63a9f0ea7bb98050796b649e85481845'. Need write permissions on file.
redis error: Could not connect to Redis server at 127.0.0.1: Invalid argument at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/statefile.pm line 89.
```

Redis is working, `redis-cli` is working, and a `telnet localhost 6379` is working.

**Comment by steaksauce-** [comment]
> 
> 
> Hi @steaksauce-
> 
> We need to take a closer look on this one. Maybe @garnier-quentin could help. If you're available for a remote session that could save us a Redis installation
> 
> If you can add somme debug, like a dumper printing the content of the object the eval initializes it could help.
> 
> Let us know ;)
> Simon
@Sims24 @garnier-quentin 
I can do a remote session -- I'm currently running redis locally on a dev Icinga box. Just let me know how you guys want to get it setup.

**Comment by garnier-quentin** [comment]
That's weird. Could you try a simple perl script with redis connection only?

**Comment by steaksauce-** [comment]
> 
> 
> That's weird. Could you try a simple perl script with redis connection only?

I am not a perl guy unfortunately :( 

If I use `perl -del` to get a repl-like shell, I can get as far as this:
```
  DB<1> use Redis ();

  DB<2> my $redis = Redis->new;

  DB<3> $redis->get('key')
Can't call method "get" on an undefined value at (eval 16)[/usr/share/perl5/perl5db.pl:646] line 2.

  DB<4> $redis->get('key');
Can't call method "get" on an undefined value at (eval 17)[/usr/share/perl5/perl5db.pl:646] line 2.
```

**Comment by steaksauce-** [comment]
Hardcoding the connection string seems to work.
```
            $self->{redis_cnx} = Redis->new(
                server => '127.0.0.1:6379',
                eval $self->{redis_attributes}
            );
```

**Comment by garnier-quentin** [comment]
You need to set the port maybe

**Comment by steaksauce-** [comment]
Yes, looks like the option doesn't assume a port, which is fine.

Maybe clarification can be added to the `--help` output? It would also be useful to have the debug line from above as well as the option to never fall back to writing out to a statefile. Falling back automatically to a statefile could have consequences in a large distributed monitoring environment where the monitoring user has permissions to the default directory.

**Comment by garnier-quentin** [comment]
Could you try ? I put the port if not set. And also it failed if you don't use --failback-file option.

**Comment by steaksauce-** [comment]
Works as expected! Tried with and without ports, and with the `--failback-file` flag using a bogus redis server.

Thanks!
