### ISSUE TITLE
UNKNOWN: Cannot load module --plugin HP Procurve

### ISSUE THREAD

**Issue by Philippe-M** [centreon/centreon-plugins#2052]
Hello, I try to set up the supervision of my HP Procurve switches but when the command launches from centreon I have this error

```
UNKNOWN: Cannot load module --plugin.

  | Can't locate network/hp/procurve/snmp/plugin.pm  in @INC (@INC contains: /tmp /usr/local/lib64/perl5  /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl  /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at  /usr/share/perl5/vendor_perl/centreon/plugins/misc.pm line 221.
-- | --
```

But if I launch it manually in CLI I have a result

```
# /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --mode=cpu --snmp-community=xxxx --snmp-version=1 --hostname=x.x.x.x --warning=80 --critical=100
OK: CPU Usage: 4.00% | 'cpu_usage'=4%;0:80;0:100;0;100
```

./centreon_plugins.pl --version
Global Version: (dev) 
Centreon 20.04.0 (ovf)

**Comment by Sims24** [comment]
Hi @Philippe-M 

Could you provide the exact command line executed by Centreon please ?

**Comment by Philippe-M** [comment]
Hi @Sims24 

/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --mode=cpu --snmp-community=xxx --snmp-version=1 --hostname=192.168.x.x --warning=80 --critical=100

In commande page

$USER2$/centreon_plugins.pl --plugin=$_SERVICEPLUGIN$ --mode=cpu --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --hostname=$HOSTADDRESS$ --warning=$_SERVICEWARNING$ --critical=$_SERVICECRITICAL$

$USER2$ = /usr/lib/centreon/plugins/centreon-plugins

**Comment by Sims24** [comment]
Hi, 

You cannot git clone centreon-plugins development within /usr/lib/centreon/plugins/, that will lead to some problem. Use another directory for $USER2$ and let me know it the error is gone.

Please also use packaged RPM if you are on rhel/centos system: 

```
[root@cps-demo-central ~]# rpm -ql centreon-plugin-Network-Switchs-Hp-Procurve-Snmp-20200410-101650.el7.centos.noarch
/usr/lib/centreon/plugins/centreon_hp_procurve.pl
```

**Comment by Philippe-M** [comment]
It's ok with rpm plugins.

Thank's
