### ISSUE TITLE
[Oracle plugin | mode=long-queries] | How to setup critical threshold for mixed %{since} and %{status} ?

### ISSUE THREAD

**Issue by JFD01** [centreon/centreon-plugins#2056]
Hi,

I found how to setup --warning-status='%{since}>900' for example for long queries that execute over 900 seconds (15 min).
But how can I mix %{since}>900 with %{status}='EXECUTING' at the same time ?

**Comment by garnier-quentin** [comment]
Like that:
```
--critica-status=' %{since} > 900 and %{status} eq "EXECUTING" '
```
