### ISSUE TITLE
[snmp standard] mode interfaces

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#2058]
Hello,

When using --extend-perfdata-group option with sum operation, it miss some things in obtained perfdata.

Here are all the options used :
--mode=interfaces --interface=1001,1002 --add-traffic --speed-in=20000 --speed-out=20000 --warning-in-traffic=85 --critical-in-traffic=99 --warning-out-traffic=85 --critical-out-traffic=99 --subsetleef=20 --maxrepetitions=20 --add-status --oid-display=ifDesc --oid-extra-display=ifAlias --no-skipped-counters --hostname=10.10.10.10 --snmp-version=2c --snmp-community=public --snmp-timeout=15 --snmp-retries=1 --verbose  --extend-perfdata-group=',traffic_in,sum(traffic_in)' --extend-perfdata-group=',traffic_out,sum(traffic_out)'

And here are the perfdata :
'traffic_in_BD-8810 Port 1:1'=95798855.32b/s;0:17000000000;0:19800000000;0;20000000000
'traffic_out_BD-8810 Port 1:1'=230229847.35b/s;0:17000000000;0:19800000000;0;20000000000
'traffic_in_BD-8810 Port 1:2'=89903979.58b/s;0:17000000000;0:19800000000;0;20000000000
'traffic_out_BD-8810 Port 1:2'=199746035.28b/s;0:17000000000;0:19800000000;0;20000000000
'traffic_in'=185702834.9;;;; 'traffic_out'=429975882.63;;;;

For the two last, it miss unit (b/s), threshold warning, threshold critical, min value and max value.
I add the option --filter-perfdata='^traffic_(in|out)$' to have only these two last.

In Centreon MAP, abscissa value are not auto scaled in graphics when there is no unit ...

Thanks

**Comment by garnier-quentin** [comment]
For the unit, you can use it like that (with also min and max):
```
 --extend-perfdata-group=',traffic_in,sum(traffic_in),b/s,0,10000000' --extend-perfdata-group=',traffic_out,sum(traffic_out),b/s,0,1000000'
```

But you cannot set the threshold.

**Comment by ritouret** [comment]
Thank you Quentin, that's pretty good for unit and min max value.
Never mind for thresholds.
