### ISSUE TITLE
[apps::vmware::connector::plugin] Monitor vm network interface

### ISSUE THREAD

**Issue by LDSNCONSULTING** [centreon/centreon-plugins#2059]
Hi,

Is it possible to monitor network interface of VM machine ?

I tried with net-host mode and i only have esx Vmnics interfaces. I would like to graph network usage for specific VM machines.

Command : 

 /usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --connector-hostname=localhost --mode=net-host --esx-hostname='^(ex01).*' --scope-datacenter='.*' --scope-cluster='' --filter='' --nic-name='.*'  --verbose

Result : 

CRITICAL: Host 'smrfgeneex01.radiofrance.rootad.inetrf' : physical interface 'vmnic2' status down | 'host_traffic_in'=294912b/s;;;0; 'host_traffic_out'=311296b/s;;;0; 'traffic_in_vmnic0'=0b/s;;;0;1048576000 'traffic_out_vmnic0'=8192b/s;;;0;1048576000 'packets_dropped_in_vmnic0'=0%;;;0;100 'packets_dropped_out_vmnic0'=0%;;;0;100 'traffic_in_vmnic1'=0b/s;;;0;1048576000 'traffic_out_vmnic1'=0b/s;;;0;1048576000 'packets_dropped_in_vmnic1'=0%;;;0;100 'packets_dropped_out_vmnic1'=0%;;;0;100 'traffic_in_vmnic3'=294912b/s;;;0;1048576000 'traffic_out_vmnic3'=303104b/s;;;0;1048576000 'packets_dropped_in_vmnic3'=0%;;;0;100 'packets_dropped_out_vmnic3'=0%;;;0;100 'vswitch_traffic_in_vSwitch0'=0b/s;;;0; 'vswitch_traffic_out_vSwitch0'=8192b/s;;;0; 'vswitch_traffic_in_vSwitch1'=294912b/s;;;0; 'vswitch_traffic_out_vSwitch1'=303104b/s;;;0;

Thanks,

Laurent

**Comment by garnier-quentin** [comment]
With that mode no. Need to look if we can get that information.

**Comment by LDSNCONSULTING** [comment]
Thanks,

**Comment by garnier-quentin** [comment]
It exists: 
https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fdisk_counters.html

I will do a mode for that.

**Comment by LDSNCONSULTING** [comment]
Thank you so much.
