### ISSUE TITLE
os::linux::snmp::plugin threshold for cpu-detailed

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#206]
Hi,

I see that in the new version of the plugin package the thresholds command has changed.
Now I have to define warning and critical from the list below:
--warning-*
            Threshold warning in percent. Can be: 'user', 'nice', 'system',
            'idle', 'wait', 'kernel', 'interrupt', 'softirq', 'steal',
            'guest', 'guestnice'.

    --critical-*
            Threshold critical in percent. Can be: 'user', 'nice', 'system',
            'idle', 'wait', 'kernel', 'interrupt', 'softirq', 'steal',
            'guest', 'guestnice' 

But if I need one warning and critical threshold to match all of them, how do I do it? Or the only way is to write them one by one: --warning-system=85 --warning-user=85 --warning-kernel=85 ?

**Comment by garnier-quentin** [comment]
You can use idle like that also: --warning-idle=15:
