### ISSUE TITLE
[Cisco Plugin ] Monitor VSS status

### ISSUE THREAD

**Issue by LDSNCONSULTING** [centreon/centreon-plugins#2060]
Hi,

I modified a plugin to monitor my VSS. It works but doesn't necessarily respect the coding format of centreon plugin.
Could you adapt it and add it to the list of cisco standard modes ?

MIB of Cisco VSS

[CISCO-VIRTUAL-SWITCH-MIB.txt](https://github.com/centreon/centreon-plugins/files/4785884/CISCO-VIRTUAL-SWITCH-MIB.txt)

Command : 

/usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=vss --hostname=xxxxxxx --snmp-version='2c' --snmp-community='xxxxxxxx'

Result :

OK: VSS is OK - Chassis 1 primary Chassis 2 secondary - VSL primary OK - VSL secondary OK

Snmpwalk :

[vss.snmwalk.txt](https://github.com/centreon/centreon-plugins/files/4785929/vss.snmwalk.txt)

Mode file :
[vss.pm.txt](https://github.com/centreon/centreon-plugins/files/4785942/vss.pm.txt)

Thanks,

Laurent

**Comment by garnier-quentin** [comment]
Thanks. we are going to look it soon

**Comment by garnier-quentin** [comment]
I have changed your mode to do more. Could you test it ?
```
perl centreon_plugins.pl --plugin=network/cisco/standard/snmp/plugin.pm --mode=vss
```
