### ISSUE TITLE
[apps::vmware::connector::plugin] - it is possible to check if a VM is powered on?

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2065]
I need to check if a VM is powered on/off, because there is no direct access to the VM for monitoring, but we need to know if the VM is running.
I tried with different modes like "status-vm", but it seem's not possible. The only mode where we can see if a VM is on/off is "getmap", but it cannot be used for our scope.
Anyone has some idea?

**Comment by garnier-quentin** [comment]
Maybe i could add it in vm-status mode (with connection-state).

**Comment by garnier-quentin** [comment]
You can test it with mode ```status-vm```
