### ISSUE TITLE
Centreon Extract hosts and services with specific contact

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#2067]
Hello, 

I would like to extract the list of hosts and services where a contact is used. This is for an audit job. 
I saw that this is not possible using the UI but i heard that it can be done using centreon CLAPI. 

Can any one please give me the correct query to run to get the list ? i just need host names and service names. 

Thanks for the help

**Comment by garnier-quentin** [comment]
It's not a centreon-plugins issue. I think you'll need to develop our own script and use database (because contact can be linked on templates).

**Comment by saharawolf** [comment]
Centreon CLI API is not a centreon plugin or tool ? 
I think that this should be something to add on the UI on future releases.
I would appreciate getting help using the CLAPI instead of closing the case like this  :)

**Comment by garnier-quentin** [comment]
You are in the wrong github. Centreon clapi export and check configuration. But clapi doesn't provide that information directly.
