### ISSUE TITLE
[apps::backup::veeam::local::plugin] decode JSON NSClient Agent

### ISSUE THREAD

**Issue by reawakn** [centreon/centreon-plugins#2068]
from ticket #1976 i have the same issue. 

i change to the new version from  https://github.com/centreon/centreon-nsclient-build/tree/master/resources/scripts/x64/centreon

now, the plugin returns these strange values:
`UNKNOWN: Cannot decode json response: malformed UTF-8 character in JSON string, at character offset 72 (before "\x{fffd}tzlich gel\x{fffd}...") at C:\Windows\TEMP\par-5352562d564545414d303124\cache-e0c3f0e8478beeb94ed4d63d71a9bf6afc5b969b\inc\lib/apps/backup/veeam/local/mode/jobstatus.pm line 173.
`

**Comment by garnier-quentin** [comment]
It's in unicode. Could you try to add following lines in file apps/backup/veeam/local/mode/jobstatus.pm:
```
    use Encode;
    my $decoded;
    eval {
        $decoded = JSON::XS->new->utf8->decode(Encode::encode_utf8($stdout));
    };
```

And tell me if it's working.

**Comment by Cool34000** [comment]
See also this : https://github.com/centreon/centreon-nsclient-build/issues/13

**Comment by garnier-quentin** [comment]
that's the same issue yes. Could you test the second one ? Maybe it's enough
```
my $decoded;
    eval {
        $decoded = JSON::XS->new->decode($stdout);
    };
```

And that time i won't forget to patch it...

**Comment by reawakn** [comment]
i have tested the first one, it's working fine. I have add in the Buildscript -M Encode ^.

**Comment by garnier-quentin** [comment]
And the second is working ?

**Comment by reawakn** [comment]
Now, i have building the package for the second patch and its working, both option are okay.

**Comment by garnier-quentin** [comment]
Thanks. i have done the patch
