### ISSUE TITLE
centreon::common::cisco::standard::snmp::mode::hsrp - Check HSRP by Interface

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#207]
Hello,

Would it be possible to add an by interface option on HSRP check ?

Thanks a lot,
Fix

**Comment by garnier-quentin** [comment]
How could i do the link with the interface ? You mean you want to filter by IP ?

**Comment by fixlair** [comment]
It seems to be good for me to check it by IP (until now I was checking it with an ugly hard coded OID :))

I just try a snmpwalk you could get the HSRP IP for example on 
.1.3.6.1.4.1.9.9.106.1.2.1.1.11.X

Comparing it to the result of .1.3.6.1.4.1.9.9.106.1.2.1.1.15.X as you check in the actual check;

**Comment by garnier-quentin** [comment]
You can use vrid filter option. Mabye it solves it. If not, open it.
