### ISSUE TITLE
[storage::hp::p2000::xmlapi::plugin] MSA 2050 mode=vdisks -> 500 Server closed connection

### ISSUE THREAD

**Issue by gr4ssi** [centreon/centreon-plugins#2072]
When trying to query --mode=vdisks on a MSA 2050, I get "UNKNOWN: 500 Server closed connection without sending any data back" as a result.
The command issued is:
`perl /usr/local/src/centreon-plugins/centreon_plugins.pl --plugin=storage::hp::p2000::xmlapi::plugin --mode=vdisks --hostname=192.168.115.181 --proto=https --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --username='theUser' --password="yyy" --verbose`

It also doesn't work with http instead of https. 
The --mode=health works fine, however.

Plugin version is as of today via git pull.

**Comment by garnier-quentin** [comment]
Could you try with --http-backend=curl ?
```yum install perl-Net-Curl```

**Comment by Aleksey-Maksimov** [comment]
Hello, @gr4ssi,

I think that **storage::hp::p2000::xmlapi::plugin** is not suitable for monitoring the MSA 2050, since this new storage system does not have such an entity as **vdisk**. vdisk is used on legacy storage systems **MSA 2000**/**P2000**. New storage systems use the concept of **disk pool** instead of vdisk.

**Comment by garnier-quentin** [comment]
I think it's the same issue: https://github.com/centreon/centreon-plugins/issues/2466

Please tell us if it's not working.

**Comment by Aleksey-Maksimov** [comment]
Yes, it works with CURL. I am using the following options `--proto=https --http-backend=curl --curl-opt='CURLOPT_SSL_VERIFYPEER => 0'`

**Comment by Aleksey-Maksimov** [comment]
Just one comment. Using **Curl** is accompanied by a call to the **Net::Curl::Easy** Perl module. 
However, there is no package in the **Debian Buster** repositories that contains this module.
We can build and install the package with the required module using the **dh-make-perl** utility. 

```
# apt-get install dh-make-perl libcurl4-openssl-dev
# dh-make-perl --install --cpan Net::Curl::Easy
```
Perhaps it will be useful to someone.
