### ISSUE TITLE
[storage::hp::p2000::xmlapi::plugin] MSA 2000 vdisk show as 100% full but are not

### ISSUE THREAD

**Issue by gr4ssi** [centreon/centreon-plugins#2073]
The query of a MSA2000 with --mode=vdisks shows free: 0.00 B and 100% usage, although there is plenty of free space:

`perl /usr/local/src/centreon-plugins/centreon_plugins.pl --plugin=storage::hp::p2000::xmlapi::plugin --mode=vdisks --hostname=hpmsa1 --proto=https --username='SomeUser' --password="xxyyzz" --verbose --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"`
```
OK: All virtual disks are ok | 'vd01#vdisk.space.usage.bytes'=3597049790464B;;;0;3597049790464 'vd01#vdisk.space.free.bytes'=0B;;;0;3597049790464 'vd01#vdisk.space.usage.percentage'=100.00%;;;0;100 'vd02#vdisk.space.usage.bytes'=3597049790464B;;;0;3597049790464 'vd02#vdisk.space.free.bytes'=0B;;;0;3597049790464 'vd02#vdisk.space.usage.percentage'=100.00%;;;0;100
Virtual disk 'vd01' status : ok, space usage total: 3.27 TB used: 3.27 TB (100.00%) free: 0.00 B (0.00%)
Virtual disk 'vd02' status : ok, space usage total: 3.27 TB used: 3.27 TB (100.00%) free: 0.00 B (0.00%)
```
This is the actual view in vCenter. Value at the right is free space:
![image](https://user-images.githubusercontent.com/19840345/85808820-4de2c880-b756-11ea-9015-31b40260f2bf.png)

The version is as of today via git pull.

**Comment by garnier-quentin** [comment]
I think it's different. From msa point of view, it provides 100% of your disk. But msa doesn't know inside of the volume.

**Comment by Aleksey-Maksimov** [comment]
Hello @gr4ssi,

I assume you are confusing vdisk and volume for P2000. In the context of MSA, a vdisk is created first, then volume is created on it. If the vdisk is directly exported to the hypervisor, then it is 100% busy for the MSA. Therefore, the plugin displays the information correctly. If you want to monitor the free space on the LUN in the hypervisor, then it probably makes sense to look towards monitoring through the hypervisor.

**Comment by garnier-quentin** [comment]
I close it without news.
