### ISSUE TITLE
[network::digi::portserverts::snmp::plugin] Evolution mode interfaces

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#2074]
Bonjour,

Est il possible à partir des modes existants interfaces et list-interfaces de récupérer l’état et le trafic des interfaces séries
la table oid serial .1.3.6.1.2.1.19.2.1.2 au lieu de l'habituel .1.3.6.1.2.1.2.2.1.2.1 pour le réseau ?

SNMPWALK disponible s'il le faut

Merci !

**Comment by garnier-quentin** [comment]
I need the mib and the snmpalk. Maybe we could add a mode.

**Comment by Jordan91** [comment]
Hi,

I'll send you in intern

Thank's

**Comment by squema** [comment]
Hi,
Any update info about this evolution? Are the MIBs OK?
Thanks

**Comment by squema** [comment]
Hi 
is it possible to list serial interfaces with mode=list-interfaces and get serial traffic in mode=interfaces?

Sample hereafter show only one active serial tty01

snmpwalk -vVERSION -c COMMUNITY HOSTADDRESS .1.3.6.1.2.1.19
SNMPv2-SMI::mib-2.19.1.0 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.1.1 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.1.2 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.1.3 = INTEGER: 3
SNMPv2-SMI::mib-2.19.2.1.1.4 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.2.1 = STRING: "tty01"
SNMPv2-SMI::mib-2.19.2.1.2.2 = STRING: "tty02"
SNMPv2-SMI::mib-2.19.2.1.2.3 = STRING: "tty03"
SNMPv2-SMI::mib-2.19.2.1.2.4 = STRING: "tty04"
SNMPv2-SMI::mib-2.19.2.1.3.1 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.3.2 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.3.3 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.3.4 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.4.1 = OID: SNMPv2-SMI::transmission.33.2.1.1.1
SNMPv2-SMI::mib-2.19.2.1.4.2 = OID: SNMPv2-SMI::transmission.33.2.1.1.2
SNMPv2-SMI::mib-2.19.2.1.4.3 = OID: SNMPv2-SMI::transmission.33.2.1.1.3
SNMPv2-SMI::mib-2.19.2.1.4.4 = OID: SNMPv2-SMI::transmission.33.2.1.1.4
SNMPv2-SMI::mib-2.19.2.1.5.1 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.5.2 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.5.3 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.5.4 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.6.1 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.6.2 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.6.3 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.6.4 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.7.1 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.7.2 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.7.3 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.7.4 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.8.1 = Timeticks: (0) 0:00:00.00
SNMPv2-SMI::mib-2.19.2.1.8.2 = Timeticks: (0) 0:00:00.00
SNMPv2-SMI::mib-2.19.2.1.8.3 = Timeticks: (0) 0:00:00.00
SNMPv2-SMI::mib-2.19.2.1.8.4 = Timeticks: (0) 0:00:00.00
SNMPv2-SMI::mib-2.19.2.1.9.1 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.9.2 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.9.3 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.9.4 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.10.1 = INTEGER: 1
SNMPv2-SMI::mib-2.19.2.1.10.2 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.10.3 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.10.4 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.11.1 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.11.2 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.11.3 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.11.4 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.12.1 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.12.2 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.12.3 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.12.4 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.13.1 = Counter32: 80455289
SNMPv2-SMI::mib-2.19.2.1.13.2 = Counter32: 0
SNMPv2-SMI::mib-2.19.2.1.13.3 = Counter32: 0
SNMPv2-SMI::mib-2.19.2.1.13.4 = Counter32: 0
SNMPv2-SMI::mib-2.19.2.1.14.1 = Counter32: 760470
SNMPv2-SMI::mib-2.19.2.1.14.2 = Counter32: 0
SNMPv2-SMI::mib-2.19.2.1.14.3 = Counter32: 0
SNMPv2-SMI::mib-2.19.2.1.14.4 = Counter32: 0
SNMPv2-SMI::mib-2.19.2.1.15.1 = INTEGER: 2
SNMPv2-SMI::mib-2.19.2.1.15.2 = INTEGER: 3
SNMPv2-SMI::mib-2.19.2.1.15.3 = INTEGER: 3
SNMPv2-SMI::mib-2.19.2.1.15.4 = INTEGER: 3
SNMPv2-SMI::mib-2.19.2.1.16.1 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.16.2 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.16.3 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.16.4 = INTEGER: 4
SNMPv2-SMI::mib-2.19.2.1.17.1 = Gauge32: 0
SNMPv2-SMI::mib-2.19.2.1.17.2 = Gauge32: 0
SNMPv2-SMI::mib-2.19.2.1.17.3 = Gauge32: 0
SNMPv2-SMI::mib-2.19.2.1.17.4 = Gauge32: 0
SNMPv2-SMI::mib-2.19.2.1.18.1 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.18.2 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.18.3 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.18.4 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.19.1 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.19.2 = INTEGER: 128
SNMPv2-SMI::mib-2.19.2.1.19.3 = INTEGER: 128
SNMPv2-SMI::mib-2.19.2.1.19.4 = INTEGER: 128
SNMPv2-SMI::mib-2.19.2.1.20.1 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.20.2 = INTEGER: 128
SNMPv2-SMI::mib-2.19.2.1.20.3 = INTEGER: 128
SNMPv2-SMI::mib-2.19.2.1.20.4 = INTEGER: 128
SNMPv2-SMI::mib-2.19.2.1.21.1 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.21.2 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.21.3 = INTEGER: 0
SNMPv2-SMI::mib-2.19.2.1.21.4 = INTEGER: 0

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
