### ISSUE TITLE
[cloud::microsoft::office365::management::plugin] Cannot decode json response: malformed JSON string

### ISSUE THREAD

**Issue by mmarodin** [centreon/centreon-plugins#2075]
Hi.
I'm using office365 plugins with success, except the management one.
When I try to use it I have this error:
`UNKNOWN: Cannot decode json response: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /opt/scripts/centreon-plugins/cloud/microsoft/office365/custom/managementapi.pm line 195.`

Trying the command with the --debug options:
```
UNKNOWN: Cannot decode json response: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /opt/scripts/centreon-plugins/cloud/microsoft/office365/custom/managementapi.pm line 195.
======> request send
GET https://manage.office.com/api/v1.0/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/ServiceComms/Services
Accept: application/json
Authorization: Bearer xxx.....................................................................xxx
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Date: Fri, 26 Jun 2020 15:39:24 GMT
Pragma: no-cache
Server: Microsoft-IIS/10.0
Server: Microsoft-IIS/10.0
WWW-Authenticate: Bearer
Content-Length: 0
Expires: -1
Client-Date: Fri, 26 Jun 2020 15:39:24 GMT
Client-Peer: xxx.xxx.xxx.xxx:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=DigiCert Inc/CN=DigiCert Cloud Services CA-1
Client-SSL-Cert-Subject: /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/CN=manage.office.com
Client-SSL-Cipher: ECDHE-RSA-AES256-SHA384
Client-SSL-Warning: Peer certificate not verified
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
X-Powered-By: ASP.NET
```

Do you have any suggestions? I have already given the access to the Office 365 Management API.

Please let me know, thanks.
Bye, Morgan

**Comment by garnier-quentin** [comment]
It look like a missing privileges.

**Comment by mmarodin** [comment]
This is the command line used:
`/opt/scripts/centreon-plugins/centreon_plugins.pl --plugin cloud::microsoft::office365::management::plugin --tenant 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' --client-id 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy' --client-secret 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz' --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE' --mode list-services`
I tried also with the option _--custommode='managementapi'_ but the issue is the same

**Comment by UrBnW** [comment]
Facing same issue on several o365 accounts, seems like an access level issue.
I've not investigated further yet though.

**Comment by UrBnW** [comment]
Older report here : #1594

**Comment by UrBnW** [comment]
Could help :
https://docs.microsoft.com/en-us/office/office-365-management-api/get-started-with-office-365-management-apis#specify-the-permissions-your-app-requires-to-access-the-office-365-management-apis

**Comment by UrBnW** [comment]
Be sure to add / allow both **Management** APIs (for `management` mode) and **Graph** APIs (for the other modes).
