### ISSUE TITLE
[network::paloalto::ssh::plugin] UNKNOWN: command execution timeout

### ISSUE THREAD

**Issue by gueliljko** [centreon/centreon-plugins#2078]
Hi,

We are trying to use the plugin ssh for PaloAlto and each time we execute the command we receive a timout.
Somebody can help us ?

Regards

**Comment by garnier-quentin** [comment]
Could you provide the command and the output ?

**Comment by gueliljko** [comment]
Sure, we execute the following command

[root@TEST centreon-plugins]# ./centreon_plugins.pl  --plugin=network::paloalto::ssh::plugin --mode=system --hostname='ip_adress' --ssh-backend='libssh' --ssh-username='admin' --ssh-password='password' --ssh-port='22' --verbose
UNKNOWN: command execution timeout

Regards

**Comment by garnier-quentin** [comment]
ok there is an issue with libssh backend and pipe command. I need to update the libssh first.

**Comment by garnier-quentin** [comment]
Could you install that new version ? https://github.com/garnier-quentin/perl-libssh/raw/master/contrib/RPMS/perl-Libssh-Session-0.8-1.el7.x86_64.rpm
```
yum update perl-Libssh-Session-0.8-1.el7.x86_64.rpm
```

Update the last version of centreon-plugins and try it.

**Comment by gueliljko** [comment]
Hi,
Thank for you help, it's working now
Regards
