### ISSUE TITLE
Oracle plugin

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2083]
Hi all,
im trying to use centreon oracle plugin on centreon 20.40 version but im not abl to connect to database in anyway.
I tested credential with sql developer and im able to connect to it and get infos.

Command:
./centreon_oracle.pl --mode=connected-users --hostname=XXX --port=1524 --username=XXX --password=XX --servicename=XXX

Result:
UNKNOWN: Cannot connect: (no error string)

Any info? i need to install some oracle client?

Thanks

**Comment by garnier-quentin** [comment]
Which user do you use ? Have you installed DBD Oracle ? (not in root subdirectory).

**Comment by R00T88** [comment]
Hi @garnier-quentin 
user has sysdba priviledge on sid.
I don't have install any DBD Oracle, should i to get it working?
Can you provide me link where to download?

Thanks

**Comment by garnier-quentin** [comment]
https://docs.centreon.com/current/en/integrations/plugin-packs/procedures/applications-databases-oracle.html#docsNav

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
thanks and installed everything for oracle.
Now getting this error whne using connected-user mode

UNKNOWN: Cannot execute query: ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 21 in 'SELECT COUNT(*) FROM <*>v$session WHERE type = 'USER'')

Thanks

**Comment by R00T88** [comment]
Hi @garnier-quentin 
fixed there was a wrong permission on table

Thanks

**Comment by spawnmack** [comment]
@R00T88 what permission is needed to fix this?  I have a similar issue:

I have a view called monitor_cod01, and I don't know why I need to use " to called it:  Select RESULTS from "monitor_cod01"  

UNKNOWN: Cannot execute query: ORA-00904: "RESULTS": invalid identifier (DBD ERROR: error possibly near <*> indicator at char 7 in 'SELECT <*>RESULTS FROM "monitor_cod01" ')
