### ISSUE TITLE
New Plugin HPE Nimble

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#2084]
Bonjour,

Nimble ayant été racheté par HPE, serait-il possible de faire le plugin correspondant, en passant par les API.
Actuellement le plugin nimble récupère des infos via SNMP, mais c’est trop peu et il n’y a pas le statut Hardware, ce qui l’un des éléments les plus important.

Voici le modèle que nous avons : HPE NS AF40
https://h20195.www2.hpe.com/v2/GetPDF.aspx/a00008273enw.pdf

Merci !

**Comment by garnier-quentin** [comment]
I think it's still a nimble. If you have the api documentation and curl commands and results, yes i can develop a plugin nimble with the new api.

**Comment by romsworld** [comment]
here is the documentation : 
https://infosight.hpe.com/InfoSight/media/cms/active/public/pubs_REST_API_Reference_NOS_51x.whz/htr1449782645359.html

Is that enough ?

**Comment by garnier-quentin** [comment]
Not enough. I need curl commands and results (of what you want to monitor).

**Comment by romsworld** [comment]
I have an malformed json, I don't understand why;

curl -k -i -X 'POST' -d '{"data":{"password":**********,"username":centreon}}' https://X.X.X.X:5392/v1/tokens
HTTP/1.1 400 OK
Connection: Keep-Alive
Content-Type: application/json;charset=utf-8
Date: Thu, 02 Jul 2020 07:56:30 GMT
Transfer-Encoding: chunked

{"messages":[{"code":"SM_http_bad_request","severity":"error","text":"The request could not be understood by the server."},{"code":"SM_malformed_json","severity":"error","text":"Malformed json."}]}

**Comment by garnier-quentin** [comment]
I'm not sure it's protected
```
curl -k -i -X 'POST' -d '{"data":{"password": "xxx","username": "xxx" } }' https://X.X.X.X:5392/v1/tokens
```

**Comment by romsworld** [comment]
It works! Thank you
I'm looking at the useful commands

**Comment by romsworld** [comment]
I think, we need this command. I sent result by mail.

curl -k -X 'GET' -H "X-Auth-Token:xxxxx" https://X.X.X.X:5392/v1/arrays/detail
curl -k -X 'GET' -H "X-Auth-Token:xxxxx" https://X.X.X.X:5392/v1/shelves/detail
curl -k -X 'GET' -H "X-Auth-Token:xxxxx" https://X.X.X.X:5392/v1/disks/detail
curl -k -X 'GET' -H "X-Auth-Token:xxxxx" https://X.X.X.X:5392/v1/volumes/detail
curl -k -X 'GET' -H "X-Auth-Token:xxxxx" https://X.X.X.X:5392/v1/network_interfaces/detail
curl -k -X 'GET' -H "X-Auth-Token:xxxxx" https://X.X.X.X:5392/v1/controllers/detail

Thanks,
