### ISSUE TITLE
[database::mysql::plugin] - [Warning] Aborted connection 8416535 to db (Got an error reading communication packets)

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2086]
Plugins 20191219/20200410

we have on different MariaDB databases on /var/log/messages this warning output:
`Jun 28 03:33:37 i-vertix-mgmt mysqld[16294]: 2020-06-28  3:33:37 140716821321472 [Warning] Aborted connection 8416508 to db: 'unconnected' user: 'xxxx' host: 'localhost' (Got an error reading communication packets)`
Problem seem's related to the monitoring plugins, because the user on the message is used only for monitoring reasons. Connection not closed correctly?

**Comment by garnier-quentin** [comment]
The disconnect should be done by the DESTROY:
https://metacpan.org/pod/DBI#disconnect

**Comment by rmorandell-pgum** [comment]
Hi @garnier-quentin ..

It seems like something is blocking or not calling this disconnect. We have that on different MySQL instances of different versions. Can we force the disconnect? Or could the plugin not call a disconnect at the end?

**Comment by garnier-quentin** [comment]
I have to look it. Maybe the disconnect is not call.

**Comment by garnier-quentin** [comment]
I don't have that kind of problem.
https://www.percona.com/blog/2016/05/16/mysql-got-an-error-reading-communication-packet-errors/

Have you find a specific mysql mode ?

**Comment by rmorandell-pgum** [comment]
Hi .. no we don't have a specific mysql mode

**Comment by garnier-quentin** [comment]
It's not what i mean. You have that issue with all mysql modes ?

**Comment by rmorandell-pgum** [comment]
It's doing this an all modes except connection-type. 

I'm testing this on a local machine were centreon and mysql is running on the same machine. So it should not be a problem of connection or network.

**When i'm forcing the check or running it from the GUI doing Scheduling immediate check (Forced) the error appears in the log in a second.
When i'm running the command in the CLI as root or a centreon user there is no warning in the log.**

Server version: 10.2.32-MariaDB - MariaDB Server.

**Comment by rmorandell-pgum** [comment]
it's definitly the perl connector on the command. Without perl connector there is no warning in log

**Comment by garnier-quentin** [comment]
Ok, i see. I will test with the perl connector

**Comment by garnier-quentin** [comment]
I have found the bug. Could you try it ? (with unstable repository)

**Comment by rmorandell-pgum** [comment]
seems to be going well

Regards

Roman

**Comment by garnier-quentin** [comment]
Thanks for the feeback!
