### ISSUE TITLE
[MSSQL | Transactions] Transactions/sec per database instead of global instance

### ISSUE THREAD

**Issue by JFD01** [centreon/centreon-plugins#2088]
Hi,

Actually transactions/sec works for a global MSSQL instance, there is no way to monitor transactions/sec for a given database.
Is it planned to add a feature or parameter to transactions mode of mssql plugin in a near future ?

**Comment by garnier-quentin** [comment]
If you provide the request (with the response), i could do it.

**Comment by JFD01** [comment]
The idea would be to replace : AND instance_name = '_Total' by AND instance_name = '$DATABASE_NAME'.
$DATABASE_NAME = '_Total' by default but we could setup another value if we want

**Comment by garnier-quentin** [comment]
Could you provide a global request ? with all dimensions.

**Comment by garnier-quentin** [comment]
Could you provide the result of that request ?
```
SELECT * FROM sys.dm_os_performance_counters WHERE UPPER(counter_name) = UPPER('transactions/sec')
```

**Comment by JFD01** [comment]
object_name | counter_name | instance_name | cntr_value | cntr_type
-- | -- | -- | -- | --
MSSQL$INSTANCE:Databases | Transactions/sec | DB1 | 216864426 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | DB2 | 112248901 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | tempdb | 13714729690 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | model | 404750 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | mssqlsystemresource | 60365 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | DB3 | 423373 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | DB4 | 1336479 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | msdb | 835844 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | _Total | 14169679372 | 272696576
MSSQL$INSTANCE:Databases | Transactions/sec | master | 122775544 | 272696576

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by JFD01** [comment]
Hi,

Why did you close this thread ?

**Comment by garnier-quentin** [comment]
Because i have done the patch

**Comment by JFD01** [comment]
I sent the result of the query, did you see it ?

**Comment by JFD01** [comment]
oh :-) I will have a look !
Thanks

**Comment by JFD01** [comment]
I get the same value for each database even if there is no transactions happening at all on some of them ...

**Comment by garnier-quentin** [comment]
It's weird. I use that request:
```SELECT instance_name, cntr_value FROM sys.dm_os_performance_counters WHERE UPPER(counter_name) = UPPER('transactions/sec')```

Could you provide the output please ?

**Comment by JFD01** [comment]
sorry my fault, I needed to create a new service and added --database='DB1' to EXTRAOPTIONS, it seems I need to use --filer-database there, I'm doing some more tests

**Comment by JFD01** [comment]
I get error : Unknow option: filter-database at /usr/lib/centreon/plugins/centreon_mssql.pl line 616.
Maybe I'm missing something ...

/usr/lib/centreon/plugins/centreon_mssql.pl --plugin database::mssql::plugin --hostname 1.2.3.4 --port 54321 --username 'domain\sup' --password 'azerty' --mode='transactions' --warning='' --critical='' --verbose --filter-database='DB1'

**Comment by garnier-quentin** [comment]
The plugin is on unstable repository. So you need to update it:
```yum --enablerepo=centreon-unstable* update centreon-plugin-Applications-Databases-Mssql```

**Comment by JFD01** [comment]
I was using **centreon_mssql.pl** instead of **centreon_plugins.pl** ...

Script results look good although I had to edit _**/etc/freetds.conf**_ to declare MSSQL instance for the script to be able to connect. 

Usually I give _--hostname_ _--port --username_ and _--password_ => database connection is ok with **centreon_mssql.pl** 
but the connection doesn't work using these parameters with **centreon_plugins.pl** I get an error :

**_**Use of uninitialized value in string eq at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/dbi.pm line 118.
UNKNOWN: Need to specify data_source arguments.**_**

Is it something you've already met before ?

**Comment by garnier-quentin** [comment]
It's my fault. Could you test with last version ?

**Comment by JFD01** [comment]
**Connection is ok now ! => Thanks 👍 

I don't know what parameter name to use for warning and critical thresholds, is it supposed to be **_--warning_** and **_--critical_** ? 
When I do so I get the following error :
**Unknown option: warning at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.**

**Comment by garnier-quentin** [comment]
It's in the help file ;)

**Comment by JFD01** [comment]
ok thanks !
can you please explain the difference between --warning-database-transactions and --warning-database**s**-transactions ?

**Comment by garnier-quentin** [comment]
--warning-databases-transactions it's for all databases (_Total we use).

**Comment by JFD01** [comment]
--warning-databases-transactions='10' gives me no warning and should give a warning whereas --warning-databases-transactions='10' gives me a warning

**Comment by garnier-quentin** [comment]
Could you provide the output of the command ?

**Comment by JFD01** [comment]
$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin database::mssql::plugin --mode=transactions --hostname '1.2.3.4' --port 54321 --username 'sup_user' --password 'password' --verbose --warning-databases-transactions='10'
OK: databases-transactions : skipped (no value(s)) - All databases are ok | 'DB1                                                                                                                        #database.transactions.persecond'=0.03/s;;;0; 'DB2                                                                                                                          #database.transactions.persecond'=2.41/s;;;0; 'DB3                                                                                                                 #database.transactions.persecond'=0.03/s;;;0; 'DB4                                                                                                                           #database.transactions.persecond'=51.19/s;;;0; '_Total                                                                                                                          #database.transactions.persecond'=65.01/s;;;0; 'master                                                                                                                          #database.transactions.persecond'=5.26/s;;;0; 'model                                                                                                                           #database.transactions.persecond'=0.03/s;;;0; 'msdb                                                                                                                            #database.transactions.persecond'=0.03/s;;;0; 'mssqlsystemresource                                                                                                             #database.transactions.persecond'=0.00/s;;;0; 'tempdb                                                                                                                          #database.transactions.persecond'=6.02/s;;;0;
Database 'DB1                                                                                                                        ' transactions: 0.03/s
Database 'DB2                                                                                                                          ' transactions: 2.41/s
Database 'DB3                                                                                                                 ' transactions: 0.03/s
Database 'DB4                                                                                                                           ' transactions: 51.19/s
Database '_Total                                                                                                                          ' transactions: 65.01/s
Database 'master                                                                                                                          ' transactions: 5.26/s
Database 'model                                                                                                                           ' transactions: 0.03/s
Database 'msdb                                                                                                                            ' transactions: 0.03/s
Database 'mssqlsystemresource                                                                                                             ' transactions: 0.00/s
Database 'tempdb                                                                                                                          ' transactions: 6.02/s

$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin database::mssql::plugin --mode=transactions --hostname '1.2.3.4' --port 54321 --username 'sup_user' --password 'password' --verbose --warning-database-transactions='10'
WARNING: Database 'DB4                                                                                                                           ' transactions: 33.67/s - Database '_Total                                                                                                                          ' transactions: 46.33/s | 'DB1                                                                                                                        #database.transactions.persecond'=0.00/s;0:10;;0; 'DB2                                                                                                                          #database.transactions.persecond'=2.17/s;0:10;;0; 'DB3                                                                                                                 #database.transactions.persecond'=0.00/s;0:10;;0; 'DB4                                                                                                                           #database.transactions.persecond'=33.67/s;0:10;;0; '_Total                                                                                                                          #database.transactions.persecond'=46.33/s;0:10;;0; 'master                                                                                                                          #database.transactions.persecond'=4.67/s;0:10;;0; 'model                                                                                                                           #database.transactions.persecond'=0.00/s;0:10;;0; 'msdb                                                                                                                            #database.transactions.persecond'=0.00/s;0:10;;0; 'mssqlsystemresource                                                                                                             #database.transactions.persecond'=0.00/s;0:10;;0; 'tempdb                                                                                                                          #database.transactions.persecond'=5.83/s;0:10;;0;
Database 'DB1                                                                                                                        ' transactions: 0.00/s
Database 'DB2                                                                                                                          ' transactions: 2.17/s
Database 'DB3                                                                                                                 ' transactions: 0.00/s
Database 'DB4                                                                                                                           ' transactions: 33.67/s
Database '_Total                                                                                                                          ' transactions: 46.33/s
Database 'master                                                                                                                          ' transactions: 4.67/s
Database 'model                                                                                                                           ' transactions: 0.00/s
Database 'msdb                                                                                                                            ' transactions: 0.00/s
Database 'mssqlsystemresource                                                                                                             ' transactions: 0.00/s
Database 'tempdb                                                                                                                          ' transactions: 5.83/s

**Comment by garnier-quentin** [comment]
I have done a patch. could you test it ?

**Comment by JFD01** [comment]
It's working now I have a warning for both --warning-database-transactions and --warning-databases-transactions
Thanks !

**Comment by JFD01** [comment]
I have the same issue with --critical-database-transactions and --critical-databases-transactions returning OK for both of them instead of CRITICAL

**Comment by garnier-quentin** [comment]
Could you show me the command and result ? Because it should be working for critical also.

**Comment by JFD01** [comment]
$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin database::mssql::plugin --mode=transactions --hostname '1.2.3.4' --port 54321 --username 'sup_user' --password 'password' --verbose -critical-database-transactions='10'
OK: total transactions: 64.09/s - All databases are ok | 'databases.transactions.persecond'=64.09/s;;;0; 'DB1#database.transactions.persecond'=0.03/s;;;0; 'DB2#database.transactions.persecond'=2.35/s;;;0; 'DB3#database.transactions.persecond'=0.03/s;;;0; 'DB4#database.transactions.persecond'=50.50/s;;;0; 'master#database.transactions.persecond'=5.21/s;;;0; 'model#database.transactions.persecond'=0.03/s;;;0; 'msdb#database.transactions.persecond'=0.03/s;;;0; 'mssqlsystemresource#database.transactions.persecond'=0.00/s;;;0; 'tempdb#database.transactions.persecond'=5.93/s;;;0;
Database 'DB1' transactions: 0.03/s
Database 'DB2' transactions: 2.35/s
Database 'DB3' transactions: 0.03/s
Database 'DB4' transactions: 50.50/s
Database 'master' transactions: 5.21/s
Database 'model' transactions: 0.03/s
Database 'msdb' transactions: 0.03/s
Database 'mssqlsystemresource' transactions: 0.00/s
Database 'tempdb' transactions: 5.93/s
$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin database::mssql::plugin --mode=transactions --hostname '1.2.3.4' --port 54321 --username 'sup_user' --password 'password' --verbose -critical-databases-transactions='10'
OK: total transactions: 113.89/s - All databases are ok | 'databases.transactions.persecond'=113.89/s;;;0; 'DB1#database.transactions.persecond'=0.11/s;;;0; 'DB2#database.transactions.persecond'=2.22/s;;;0; 'DB3#database.transactions.persecond'=0.11/s;;;0; 'DB4#database.transactions.persecond'=100.44/s;;;0; 'master#database.transactions.persecond'=5.00/s;;;0; 'model#database.transactions.persecond'=0.11/s;;;0; 'msdb#database.transactions.persecond'=0.11/s;;;0; 'mssqlsystemresource#database.transactions.persecond'=0.00/s;;;0; 'tempdb#database.transactions.persecond'=5.78/s;;;0;
Database 'DB1' transactions: 0.11/s
Database 'DB2' transactions: 2.22/s
Database 'DB3' transactions: 0.11/s
Database 'DB4' transactions: 100.44/s
Database 'master' transactions: 5.00/s
Database 'model' transactions: 0.11/s
Database 'msdb' transactions: 0.11/s
Database 'mssqlsystemresource' transactions: 0.00/s
Database 'tempdb' transactions: 5.78/s

**Comment by garnier-quentin** [comment]
Missing '-': -critical-databases-transactions='10' by --critical-databases-transactions='10'

**Comment by JFD01** [comment]
I'm confused, you're right ! I get the CRITICAL states now.
Thanks for your help ;-)
