### ISSUE TITLE
[snmp_standard::plugin mode=uptime] minimum uptime

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#209]
Hi!
How, using this plugin, specify the minimum uptime?

./centreon_plugins.pl --plugin=snmp_standard::plugin --mode=uptime --hostname=xx.xx.xx.xx --snmp-community=public --snmp-version=2c
OK: System uptime is: 29 days | 'uptime'=2588697s;;;0;

Example of use: there is an equipment that is often reboots. Required to be notified that operation time is less than the specified minimum.
The key --warning/--critical sets the upper range for triggering a notification:
WARNING: System uptime is: 29 days | 'uptime'=2589163s;0:3600;;0;

It also makes sense to use the values in the graphs are not only seconds, but in these days, for example through a separate key.

**Comment by garnier-quentin** [comment]
Hi,

You can set minimum threshold with following syntax: https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

**Comment by maksimatveev** [comment]
Understood thanks!
And about the uptime display on the charts in the days that suggest?

**Comment by garnier-quentin** [comment]
Like adding an --units option ?

**Comment by maksimatveev** [comment]
It is, if it leads to similar:
OK: System uptime is: 36 days | 'uptime'=36,5296180d;3600:;;0;

Threshold can be left in seconds, it is not critical I think. To unify with readings in seconds can be left as is:
--warning=3600:

**Comment by maksimatveev** [comment]
At the direction of your link threshold and ranges as for all the plug-ins in centreon-plugins or any other specific?

**Comment by garnier-quentin** [comment]
Right now, I don't think i'll add an option to change the perfdata in days.
