### ISSUE TITLE
What is considered an RMAN backup problem?

### ISSUE THREAD

**Issue by outon** [centreon/centreon-plugins#2092]
What criteria is used to decide if a RMAN job has finished with problems or not?

After reading Oracle [documentation](https://docs.oracle.com/cd/B19306_01/server.102/b14237/dynviews_2058.htm#REFRN30306)

All possible status of an RMAN job are:
- RUNNING
- RUNNING WITH WARNINGS
- RUNNING WITH ERRORS
- COMPLETED
- COMPLETED WITH WARNINGS
- COMPLETED WITH ERRORS
- FAILED

When I run the plugin, seems that all states except RUNNING and COMPLETED are considered as non correct states and count to Warning and Critical thresholds.

Shouldn't a `* WITH WARNINGS` state be only considered for warning threshold? 

A job that has warning messages is a job finished without errors.

Consider this case:  
```BACKUP DATABASE PLUS ARCHIVELOG DELETE INPUT; ```

Backup of database finish correctly, so do backup of archivelog but when deleting archivelog we receive warning message:
```RMAN-08137: WARNING: archived log not deleted, needed for standby or upstream capture process```

In my opinion, onle `* WITH ERRORS`and `FAILED` should be considered for Critical, the rest for Warning.

**Comment by garnier-quentin** [comment]
We use that request:
```SELECT COUNT(*) FROM v$rman_status WHERE operation = 'BACKUP' AND status != 'COMPLETED' AND status != 'RUNNING'```

We didn't do the difference between status. Maybe i could upgrade the mode.

**Comment by outon** [comment]
I think that differentiating between jobs with "warning" and jobs that have failed or have errors is more appropriate.

But it will completely changes the current concept of metrics. This would have to be explained well to people who are using the current metric.

Right now, any warning or error accumulates in the metric and the warning value is always smaller than the critical value

If it's changed, you'd have two different and independent values, one for warnings and one for critical.Then you could have a warning of 2 (meaning at least 2 jobs with the status of WARNING) and a critical of 1 (meaning at least 1 job has failed or has error).

If you choose to change. 

You could count the "warning" values with:
```sql
SELECT count(*) FROM v$rman_status WHERE operation = 'BACKUP' and status like '%WITH WARNINGS'
```

And counting "critical":
```sql
SELECT count(*) FROM v$rman_status WHERE operation = 'BACKUP' and (status like '%WITH ERRORS' OR status = 'FAILED')
```

**Comment by Trunxsnot** [comment]
A difference between status would be ok. We need it too.

**Comment by outon** [comment]
Any update on this issue?

Is it going to be update to reflect only **true** failed backup problems?

**Comment by garnier-quentin** [comment]
Maybe we can group by status and have a counter by status type:
- COMPLETED
- COMPLETED WITH WARNINGS
- COMPLETED WITH ERRORS
- FAILED

**Comment by garnier-quentin** [comment]
You could test it with last git version: https://github.com/centreon/centreon-plugins/pull/3433
