### ISSUE TITLE
It's possible to add plugin for ASTARO firewall ( SOPHOS)

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#2094]
It's possible to add plugin for ASTARO firewall ( SOPHOS) ?

Please find in attach MIB. 
Thank's in advance

[ASTARO.mib.txt](https://github.com/centreon/centreon-plugins/files/4892074/ASTARO.mib.txt)

**Comment by garnier-quentin** [comment]
It's only a mib with trap definition. Need other mibs and snmpwalk.

**Comment by garnier-quentin** [comment]
It seems there are no specific OIDs (linux snmp should work). Maybe a rest api but i need curl results. I close it. If someones want to put curl commands and results, i could do a plugin
