### ISSUE TITLE
[apps::iis::local::plugin] check mode info

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2095]
Hi all,
im trying to check if iis application pool it's in started state and want to know if this check it's correct

/usr/lib/nagios/plugins//check_centreon_nrpe3 -H XXX -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state' '--pools SmartNetPool=stopped'

If i use --pools SmartNetPool=started i receive as output a critical --> CRITICAL: SmartNetPool is started instead if i use --pools SmartNetPool=stopped return OK

Im trying to use webservice-statistics mode too but it's possible to filter for a specific counter?

/usr/lib/nagios/plugins//check_centreon_nrpe3 -H XXX -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'webservice-statistics' '--name "Default Web Site"'

Output export all counters

'TotalConnectionAttemptsAllInstances'=0.04con/s;;;0; 'TotalAnonymousUsers'=1.11users/s;;;0; 'TotalPostRequests'=1.09requests/s;;;0; 'TotalGetRequests'=0.02requests/s;;;0;

How can i filter only for a specifica counter?

Thanks

**Comment by garnier-quentin** [comment]
Could you use the new plugin IIS Rest API ?
https://docs.centreon.com/current/en/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.html#docsNav

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
using local iis plugin it's deprecated?

i don't want to install more package on server and if i remember IIS Web Manager is deprecated.

Thanks

**Comment by garnier-quentin** [comment]
No, but it's easy with the Rest API. 

The API is not deprecated. Maybe the manager. But you can configure the API with other tools i think. 

I think i will do a refacto on IIS local. You could filter and other stuffs.

**Comment by R00T88** [comment]
hi @garnier-quentin ,
thanks and wait for refacto of IIS local to test it

Thanks

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
do you have an update on refactoring iis local?

Thanks

**Comment by garnier-quentin** [comment]
Soon. Before the end of the month i think.

**Comment by R00T88** [comment]
Thanks @garnier-quentin !

**Comment by garnier-quentin** [comment]
I have done a refactoring. You have the --filter-counters now.
