### ISSUE TITLE
network::cisco::asa::plugin --mode=ipsec-tunnel returns 0

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#2096]
Hello, 
I try to monitor IPSEC tunnels on a CISCO ASA, but the check command returns always 0

Command is :
/usr/lib/centreon/plugins/centreon_cisco_asa.pl --plugin=network::cisco::asa::plugin --mode=ipsec-tunnel --hostname='Cisco-ASA' --snmp-version='2c' --snmp-community='public'  --filter-counters='' --filter-name='' --filter-sa='' --warning-tunnels-total='' --critical-tunnels-total='' --warning-traffic-in='' --critical-traffic-in='' --warning-traffic-out='' --critical-traffic-out='' --warning-drop-in='' --critical-drop-in='' --warning-drop-out='' --critical-drop-out='' --warning-sa-total='' --critical-sa-total='' --verbose

Result is always :  
OK: Total Tunnels : 0 - All tunnels are ok | 'total_tunnels'=0;;;0;

Even if i specify a filter-name. 

is there something i missed ? 

Thank you

**Comment by garnier-quentin** [comment]
Do you have some informations in following SNMP tables ?
.1.3.6.1.4.1.9.9.171.1.2.3.1
.1.3.6.1.4.1.9.9.171.1.3.2.1
.1.3.6.1.4.1.9.9.171.1.3.3.1

**Comment by saharawolf** [comment]
I got information for theses two only with snmpwalk:

.1.3.6.1.4.1.9.9.171.1.3.2.1
.1.3.6.1.4.1.9.9.171.1.3.3.1

**Comment by garnier-quentin** [comment]
Need to send me the walk. But without that table, i don't think i can get it working.

**Comment by saharawolf** [comment]
Hello i attached the two snmpwalk results.

[snmpwalk-171.1.3.2.1.txt](https://github.com/centreon/centreon-plugins/files/4896198/snmpwalk-171.1.3.2.1.txt)
[snmpwalk-171.1.3.3.1.txt](https://github.com/centreon/centreon-plugins/files/4896200/snmpwalk-171.1.3.3.1.txt)

Thank you

**Comment by saharawolf** [comment]
Any update please ?

**Comment by garnier-quentin** [comment]
I have looked. And i check table 'cikeTunnelTable' first. And it's empty. It's weird.

**Comment by MarcusCaepio** [comment]
Hey all, 
we have updated to of our firewalls to Firmware Version 9.14.1.15. Since the update, we also cannot monitor IPsec tunnels anymore. The check takes forever (--debug and --verbose show nothing, so I think it is hanging at the SNMP request) and runs in a timeout.
Also the memory checks runs in a timeout very often. Maybe cisco messed up anything again with the update?

**Comment by garnier-quentin** [comment]
Have you tried with --snmp-autoreduce option ?

**Comment by MarcusCaepio** [comment]
Doesn't help. It seems, that the OIDs are gone:
snmpwalk [......]  .1.3.6.1.4.1.9.9.171.1.2.3.1
iso.3.6.1.4.1.9.9.171.1.2.3.1 = No Such Object available on this agent at this OID
1.3.6.1.4.1.9.9.171.1.3.2.1
iso.3.6.1.4.1.9.9.171.1.3.2.1 = No Such Object available on this agent at this OID
1.3.6.1.4.1.9.9.171.1.3.3.1
iso.3.6.1.4.1.9.9.171.1.3.3.1 = No Such Object available on this agent at this OID

A re-check on an older Firmware still gives me OIDs.

**Comment by garnier-quentin** [comment]
Maybe a firmware bug with snmp

**Comment by MarcusCaepio** [comment]
yes, seems so :(

**Comment by garnier-quentin** [comment]
I close. If you have the cisco support response, you could post it here. It will help.
