### ISSUE TITLE
[hardware::server::dell::idrac::snmp::plugin] does not detect system battery since update

### ISSUE THREAD

**Issue by itsul** [centreon/centreon-plugins#2097]
Current check version: Global Version: 20200602 (d30b7c138) (latest) 

Hi there,
since the latest update the check is not detecting any systembatterys anymore on all iDrac systems. But the SNMP Table still works:

snmpwalk -v 2c -c xxx x.x.x.x .1.3.6.1.4.1.674.10892.5.4.600.50.1
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.2.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.3.1.1 = INTEGER: 0
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.4.1.1 = INTEGER: 2
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.5.1.1 = INTEGER: 3
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.6.1.1 = INTEGER: 4
SNMPv2-SMI::enterprises.674.10892.5.4.600.50.1.7.1.1 = STRING: "System Board CMOS Battery"

The old check version: 20200410 (677c64d3) still detects the battery, so there must be an issue with the new version. I used this command:
/usr/lib/centreon/plugins/centreon_dell_idrac.pl --hostname 'x.x.x.x' --snmp-community 'xxx' --mode hardware --component 'systembattery' --verbose --no-component unknown

Result:
UNKNOWN: No components are checked. |
Checking system batteries

Without the parameter "--component 'systembattery' " the check does also not return any systembattery.

**Comment by garnier-quentin** [comment]
Could you provide the full snmpwalk of your equipment ?

**Comment by garnier-quentin** [comment]
It has been fixed by @UrBnW .
