### ISSUE TITLE
network::cisco::standard::snmp::plugin packet-errors

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#210]
Hi,

Can you please add packet-error mode to network::cisco::standard::snmp::plugin?

**Comment by garnier-quentin** [comment]
It is Kadrika. The new mode 'interfaces' can do it with option: --add-errors option.

**Comment by kadrika** [comment]
Ok, now I found it :) Thanks!
One more question is it possible to add exclusion option?

I have routers where I need to check errors in all ports, but the port where ISP is connected has errors and we cant do anything about it. So I would like to exclude that one port from the packet-error check. Is it doable?

**Comment by garnier-quentin** [comment]
You can select the interfaces you need to check.

**Comment by kadrika** [comment]
So no way to have one service to check all interfaces packet-errors and just exclude one interface?

So right now I need to add packet-error service to all interfaces, for example if I have 48 port switch I need to add each one separately? I instead 1 service I will have 48 services in monitoring?

**Comment by garnier-quentin** [comment]
Yes you can exclude one interface by name. With negative regexp like : '^(?!(toto)$)'

**Comment by kadrika** [comment]
Thank you! Thank you !! :)

**Comment by kadrika** [comment]
But no way to exclude more than one? For example if I need to exclude fa0/13 and fa0/14 ?

**Comment by Sims24** [comment]
Hi,

'^(?!(toto|tata)$)' will exclude toto and tata

**Comment by kadrika** [comment]
And for the critical threshold I right now use --critical-in-error=10 --critical-out-error=10 --critical-in-discard=10 --critical-out-discard=10 . Is there a shorter way to use the critical threshold, if I want all of them to be the same, in this case 10.

**Comment by garnier-quentin** [comment]
Nop. Need to do it for all.

**Comment by kadrika** [comment]
Ok, Thanks!
