### ISSUE TITLE
citrix netscaler snmp plugin

### ISSUE THREAD

**Issue by blodka** [centreon/centreon-plugins#2101]
Good morning,

I just added the citrix netscaller to centreon (20.04.3) I can actually get the datas for the connections, however the CPU, health, storage, are giving me an error UNKNOWN SNMP Table Request : Timeout, the option --snmp-autoreduce doesn't seems to help.

![image](https://user-images.githubusercontent.com/8956405/87136816-4f56d980-c29c-11ea-844c-4ea7be0fe758.png)

Any advice on the matter ? 

Thanks in advance.

**Comment by UrBnW** [comment]
Just for info I used this plugin recently, no issue with the following instances :
`NetScaler Virtual Appliance: NetScaler NS12.0: Build 53.13.nc`

**Comment by blodka** [comment]
I have NS13.0 build 58.30.nc, if that can help.

**Comment by garnier-quentin** [comment]
Do you provide a snmpwalk ? It seems like a firmware issue.

**Comment by blodka** [comment]
hi, 

Sorry for the late answer I was on holidays :) But yes the snmpwalk works, however if I do use the same settings than with snmpwalk (Version 2C) I do no have the TCP connection anymore, I have UNKNOWN: SNMP GET Request : Timeout instead. Same for the memory.


[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/4945906/snmpwalk.txt)

**Comment by garnier-quentin** [comment]
And it doesn't work with --snmp-autoreduce ? Maybe you can try like that: 
```--snmp-force-getnext --subsettable=0 --subsetleef=1```

**Comment by blodka** [comment]
ok that does the trick for the CPU health and storage,  however I do not have the connection and the memory anymore :'(

**Comment by garnier-quentin** [comment]
It's like snmpwalk with that options. So it shouldn t work with snmpwalk or snmpget.

**Comment by blodka** [comment]
I will reconfigure for each service with the extra option and not for the host directly that should do. Thanks for the help :)

**Comment by garnier-quentin** [comment]
Thanks for the feedback
