### ISSUE TITLE
[databse::oracle::plugin] check timeout

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2107]
Hi all,
im experimenting a UNKNOWN: timeout result during oracle checks and i cannot understand the root cause.
Account that i use to connect has all the required permission and we extend concurrent session to 20 for that user.
From Oracle support they suggest to check connection string used to connect to database that should be set to DEDICATED and not SHARED due to bug previously version 12

Our setup:
Centreon 20.04.03
Plugin: Latest
Oracle version: 11.2

How oracle plugin estabilish connection to oracle database?

Thanks

**Comment by R00T88** [comment]
Update from Oracle vendor
//

Please ask CENTREON to use dedicate conenction as below: ( this specifically instructs (SERVER = DEDICATED) to use dedicated connection.
If you ommit (SERVER = DEDICATED) the default will be shared connection.

sqlplus username@'(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = XXX)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = ORAWHITE.INTEMPO)))'

If they are using any tns names please use below connection string:
(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = XXX)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = ORAWHITE.INTEMPO)))

Please use dedicated connection and share the result.
//

**Comment by garnier-quentin** [comment]
There is a timeout if you launch the command directly ? Maybe you can try like that:
```
--datasource='dbi:Oracle:' --username='username@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = XXX)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = XXX)))' --password="xxx"
```

**Comment by R00T88** [comment]
Hi @garnier-quentin,
i try adding parameters that you suggested

/usr/lib/centreon/plugins//centreon_oracle.pl --mode=session-usage --hostname='XXX' --datasource='dbi:Oracle:' --username='XXX@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = XXX)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = XXX)))' --password='oraitdbmon'

i receive this output

UNKNOWN: Cannot connect: (no error string)

**Comment by garnier-quentin** [comment]
Which user do you use ? Where DBD::Oracle is installed ?

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
i use the account with required permission to connect to oracle db.
DBD::Oracle it's installed here:

/usr/lib/oracle/19.6/client64

**Comment by garnier-quentin** [comment]
You can send a email and we could do a session

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
if i remove --datasource as parameters now im getting this result:

UNKNOWN: Cannot connect: ORA-12154: TNS:could not resolve the connect identifier specified (DBD ERROR: OCIServerAttach)

Command:
/usr/lib/centreon/plugins//centreon_oracle.pl --mode=session-usage --hostname='XXX' --username='XXX@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = XXX)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = XXX)))' --password='XXX'

Thanks

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
could be enviroment variable problem?

**Comment by garnier-quentin** [comment]
I don't think so. Could we do a session ?

**Comment by garnier-quentin** [comment]
I cloe it. But you can contact me by email if you still have the issue.
I had the same issue and it was the same with sqlplus command line. We have increased the timeout (like 180 seconds) and eventually it connects. But it seems more like an instantclient/oracle issue.
