### ISSUE TITLE
ASA plugin do not consider "standbt-ready" host active anymore after recent IOS upgrade

### ISSUE THREAD

**Issue by eLvErDe** [centreon/centreon-plugins#2108]
Hello,

Since recent firmware update on our Cisco ASA, centreon-plugins cannot see anymore the backup equipment as active.

Here is the `show failover` command showing both are online is nominal state:

```
fw01# show failover state

               State          Last Failure Reason      Date/Time
This host  -   Secondary
               Active         None
Other host -   Primary
               Standby Ready  Ifc Failure              16:57:10 UTC Jul 14 2020
                              Internet: No Link
                              Management_Net: No Link
```

In `network/cisco/asa/snmp/mode/failover.pm` in `mange_selection` method I added the following code in hope it could help understanding what's going on:

```
use Data::Dumper;  
print(Dumper($result));
```

Which shows:

```
$VAR1 = {
          '.1.3.6.1.4.1.9.9.147.1.2.1.1.1.4.6' => undef,
          '.1.3.6.1.4.1.9.9.147.1.2.1.1.1.3.7' => undef,
          '.1.3.6.1.4.1.9.9.147.1.2.1.1.1.3.6' => '10',
          '.1.3.6.1.4.1.9.9.147.1.2.1.1.1.4.7' => undef
        };
```

I guess the code expects to receive "9" here somewhare for the standby host but it seems recent IOS don't do that anymore.

Don't hesitate to ask me for me debug statement if needed.

Best regards, Adam.

**Comment by eLvErDe** [comment]
Actually now, 9 is for the active host according to code in your comments, so it seems the missing one is the actually active one.

**Comment by garnier-quentin** [comment]
Could you provide snmpalk of following OID: .1.3.6.1.4.1.9.9.147.1.2.1.1.1 ?

**Comment by eLvErDe** [comment]
Sure in half an hour

**Comment by garnier-quentin** [comment]
Maybe the MIB changed also. Could you provide the CISCO-FIREWALL-MIB of your equipment ? 
Because it looks like a cisco issue

**Comment by eLvErDe** [comment]
Here is the SNMP Walk:

```
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.2.4 = STRING: "Failover LAN Interface"
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.2.6 = STRING: "Primary unit"
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.2.7 = STRING: "Secondary unit (this device)"
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.3.4 = INTEGER: 2
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.3.6 = INTEGER: 10
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.3.7 = INTEGER: 9
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.4.4 = STRING: "HA-fw01 GigabitEthernet1/8"
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.4.6 = STRING: "Standby unit"
SNMPv2-SMI::enterprises.9.9.147.1.2.1.1.1.4.7 = STRING: "Active unit
```

Both can be seen here

**Comment by garnier-quentin** [comment]
It seems ok with snmpwalk. Could you try the plugin with the option --subsetleef=1 ?

**Comment by eLvErDe** [comment]
Works...

**Comment by garnier-quentin** [comment]
It looks like a bug of cisco snmp agent. You can open a case maybe. Otherwise i have done options to manage buggy snmp agent.

**Comment by eLvErDe** [comment]
I added the option for the moment, I think I can leave with that but I'm not sure how you could handle this better on your side.
Sadly the firmware is latest STABLE version, so it should somehow be bug-free but well, cisco...

Btw, I have another one for Cisco switch, recent firmware too, I'll open another ticket.

**Comment by garnier-quentin** [comment]
I cannot handle it better. I try to optimize the request to get 4 OIDs at the same time. Thanks for your feedback.

**Comment by eLvErDe** [comment]
Fair enough, at least you're aware of the issue and there's a documented workaround for other users here :-)
