### ISSUE TITLE
[app::protocol::http::plugin] redirect http check

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2110]
Hi all,
im facing issue on web url check with redirect because it always get me 302 moved temporarily

Command:
/usr/lib/centreon/plugins//centreon_protocol_http.pl --mode='expected-content' --hostname=XXX --port='8080' --proto='http' --timeout='20' --urlpath='/Paghe3/servlet/cosa_plogin' --expected-string='sessione' --debug

Result:
UNKNOWN: 302 Moved Temporarily |

Debug:
======> request send
GET http://XXX:8080/Paghe3/servlet/cosa_plogin
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=acxw5oh0ja
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 1
Set-Cookie: JSESSIONID=6C2887AE0F897A3972CBA641E53D26A7.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Amm68suktso;Path=/Paghe3
Set-Cookie: spcookie=bbnhzkmguz;Path=/;HttpOnly
Set-Cookie: sprsc=Ad7bdsxkay7;Path=/Paghe3

======> request send
GET http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=acxw5oh0ja
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=nvcga6w02y
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 2
Set-Cookie: JSESSIONID=1B61056EB7C9EE08FCFFD5E2ACA4436D.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Ab4wq53ay4q;Path=/Paghe3
Set-Cookie: spcookie=fainjoutem;Path=/;HttpOnly
Set-Cookie: sprsc=Ans4folljyd;Path=/Paghe3

======> request send
GET http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=nvcga6w02y
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=emm48y5x28
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 3
Set-Cookie: JSESSIONID=577326E9A6E83B1300D1A5A2534EDC38.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Abmqau4582l;Path=/Paghe3
Set-Cookie: spcookie=rwtloqjwgd;Path=/;HttpOnly
Set-Cookie: sprsc=Amp2patsslg;Path=/Paghe3

======> request send
GET http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=emm48y5x28
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=s83bf25mya
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 4
Set-Cookie: JSESSIONID=0C06B2E7EA562195DED1A4D76991412B.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Axw904q9pkt;Path=/Paghe3
Set-Cookie: spcookie=mkrlezoxze;Path=/;HttpOnly
Set-Cookie: sprsc=Abj1kz5seey;Path=/Paghe3

======> request send
GET http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=s83bf25mya
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=pb28x3f4nt
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 5
Set-Cookie: JSESSIONID=D9FD44D0F7B7AC7E7225DE8044E73639.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Aashszfmkjo;Path=/Paghe3
Set-Cookie: spcookie=eezpqtkere;Path=/;HttpOnly
Set-Cookie: sprsc=Ac94a97v30u;Path=/Paghe3

======> request send
GET http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=pb28x3f4nt
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=j9gcn57q5s
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 6
Set-Cookie: JSESSIONID=3B3973EE02D855880D0E4E0BE9B6257E.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Abn9qkcx7zq;Path=/Paghe3
Set-Cookie: spcookie=vapenoxcxi;Path=/;HttpOnly
Set-Cookie: sprsc=Ajwjhvow90o;Path=/Paghe3

======> request send
GET http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=j9gcn57q5s
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=s75xgu9lvx
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 7
Set-Cookie: JSESSIONID=9C4BE159CE59B3D9EDFF197573748355.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Aux1xarfv2r;Path=/Paghe3
Set-Cookie: spcookie=aofczczhwe;Path=/;HttpOnly
Set-Cookie: sprsc=Ahes1h09ndc;Path=/Paghe3

======> request send
GET http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=s75xgu9lvx
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 302 Moved Temporarily
Cache-Control: no-store
Date: Thu, 16 Jul 2020 15:42:39 GMT
Pragma: no-cache
Location: http://XXX:8080/Paghe3/servlet/../../Paghe3/servlet/cosa_plogin?m_cParameterCache=nd3bu3plh1
Server: Apache-Coyote/1.1
Content-Length: 0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Client-Date: Thu, 16 Jul 2020 15:42:29 GMT
Client-Peer: 172.24.133.15:8080
Client-Response-Num: 8
Set-Cookie: JSESSIONID=54EF3E966CD03E28EE260D43B0E5C92F.tomcat1; Path=/Paghe3/; HttpOnly
Set-Cookie: sprsc=Awy3v79afy6;Path=/Paghe3
Set-Cookie: spcookie=qvrhcvskto;Path=/;HttpOnly
Set-Cookie: sprsc=Azjxtg9davz;Path=/Paghe3

page via web brower its this:

![image](https://user-images.githubusercontent.com/9050487/87692508-1fbc3b80-c78c-11ea-882c-a0ada52a9edc.png)

using check_http from nagios it works

/usr/lib64/nagios/plugins/check_http -H XXX -p 8080 -u /Paghe3/servlet/cosa_plogin -s "Attenzione la sessione è scaduta. E' necessario selezionare nuovamente l'applicazione dal menu Applicativi." -f follow -P RND -t 20

result:
HTTP OK: HTTP/1.1 200 OK - 32893 bytes in 0.176 second response time

Thanks

**Comment by garnier-quentin** [comment]
Could you try with that option ? ```---cokies-files=''```

**Comment by R00T88** [comment]
Hi @garnier-quentin 
with cookies-file parameters it work fine!

OK: HTTP test(s) | 'size'=32318B;;;0; 'time'=0.305s;;;0;

Thanks

**Comment by garnier-quentin** [comment]
Thanks for the feedback.

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
another question when using https it's possibile to skip certificate validation?

UNKNOWN: 500 Can't connect to XXX:443 (certificate verify failed)

Thanks

**Comment by garnier-quentin** [comment]
It depends of the backend (lwp or curl). But you have options in help for that.
```--ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"````
```--curl-opt="CURLOPT_SSL_VERIFYPEER => 0"```

**Comment by R00T88** [comment]
Thanks @garnier-quentin !
