### ISSUE TITLE
WSUS Plugin Timeout

### ISSUE THREAD

**Issue by blodka** [centreon/centreon-plugins#2111]
Hi all,

A new problem encountered with my new install. 
I have a centreon 20.04.3, I did compile the plugin centreon_plugin to integrate the wsus::app however I get a timeout. First with NRPE:
CHECK_NRPE: Socket timeout after 55 seconds

 and if I do update the time, I have it with centreon_plugin :
Command check_centreon_plugins didn't terminate within the timeout period 60s

The command line run is the following:
/usr/lib64/nagios/plugins/check_centreon_nrpe -H XXX.XXX.XXX.XXX -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::wsus::local::plugin' 'updates-status'  ' --wsus-server="XXX.XXX.XXX.XXX" --wsus-port="8531" --filter-counters="" --warning-with-client-errors="" --critical-with-client-errors="" --warning-with-server-errors="" --critical-with-server-errors="" --warning-needing-files="" --critical-needing-files="" --warning-needed-by-computers="" --critical-needed-by-computers="" --warning-up-to-date="" --critical-up-to-date="" --verbose'

I am actually trying to implement that check on a windows 2016 Server, the information such as CPU, disks, memory, are coming up, only the one related to the wsus plugin are not. I have the latest nsclient provided by centreon.

![image](https://user-images.githubusercontent.com/8956405/87939531-885f2d00-ca98-11ea-9a88-5521bb536e23.png)

Attached the build for the plugin.

[build.txt](https://github.com/centreon/centreon-plugins/files/4947782/build.txt)

Any help on the matter would be appreciated.

Regards.

**Comment by garnier-quentin** [comment]
Could you launch it directly on your windows server ? (without nrpe)

**Comment by Cool34000** [comment]
Port 8531 is default port for WSUS and HTTPS.
Have you tried on port 8530 (HTTP) ?

**Comment by blodka** [comment]
8531 because it's WSUS SSL so that is good :) I will try to launch it directly on the windows ASAP I'll let you know.

**Comment by blodka** [comment]
Well I have the following:

Can't locate 'apps/wsus/local/plugin'.pm in @INC (@INC contains: C:/Program Files/centreon-nsclient/NSClient++/scripts/centreon C:\Users\JFADM~1.PRE\AppData\Local\Temp\2\par-6a662e61646d2e7072657374\cache-3094cfd77428de7a6b2d1b0ba2ca63a66c3c0f63\inc\lib C:\Users\JFADM~1.PRE\AppData\Local\Temp\2\par-6a662e61646d2e7072657374\cache-3094cfd77428de7a6b2d1b0ba2ca63a66c3c0f63\inc CODE(0x3814050) CODE(0x3814638)) at C:\Users\JFADM~1.PRE\AppData\Local\Temp\2\par-6a662e61646d2e7072657374\cache-3094cfd77428de7a6b2d1b0ba2ca63a66c3c0f63\inc\lib/centreon/plugins/misc.pm line 222.

However the path C:\Users\JFADM~1.PRE\AppData\Local\Temp\2\par-6a662e61646d2e7072657374\cache-3094cfd77428de7a6b2d1b0ba2ca63a66c3c0f63\inc\lib does exist. The file apps/wsus/local/plugin.pm is there. The only thing bugging me a bit there it's the quotes before the .pm in the name of the file 'apps/wsus/local/plugin'.pm.

**Comment by blodka** [comment]
"C:\Program Files\centreon-nsclient\NSClient++\scripts\centreon\centreon_plugins.exe" --plugin 'apps::wsus::local::plugin' 'updates-status' ' --wsus-server="10.0.30.30" --wsus-port="8531" --filter-counters="" --warning-with-client-errors="" --critical-with-client-errors="" --warning-with-server-errors="" --critical-with-server-errors="" --warning-needing-files="" --critical-needing-files="" --warning-needed-by-computers="" --critical-needed-by-computers="" --warning-up-to-date="" --critical-up-to-date="" --verbose'

**Comment by garnier-quentin** [comment]
Please use double quote (no quote)

**Comment by blodka** [comment]
UNKNOWN: Command too long to execute (timeout)...

**Comment by garnier-quentin** [comment]
Please add option ```--timeout=300```

**Comment by blodka** [comment]
UNKNOWN: Command error: System.Management.Automation.MethodInvocationException: Exception calling "GetUpdateServer" with "3" argument(s): "The underlying connection was closed: An unexpected error occurred on a receive." ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: Une connexion existante a dû être fermée par l'hôte distant. ---> System.Net.Sockets.SocketException: Une connexion existante a dû être fermée par l'hôte distant -    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) -    --- End of inner exception stack trace --- -    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) -    at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size) -    at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead) -    --- End of inner exception stack trace --- -    at Microsoft.UpdateServices.Administration.AdminProxy.CreateUpdateServer(Object[] args) -    at CallSite.Target(Closure , CallSite , Type , Object , Object , Object ) -    --- End of inner exception stack trace --- -    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) -    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame) -    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) -    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by garnier-quentin** [comment]
Try to execute the powershell manually. You get it with --ps-display

**Comment by blodka** [comment]
System.Management.Automation.MethodInvocationException: Exception calling "GetUpdateServer" with "3" argument(s): "The underlying connection was closed: An unexpected error occurred on a rece
ive." ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connect
ion: Une connexion existante a dû être fermée par l’hôte distant. ---> System.Net.Sockets.SocketException: Une connexion existante a dû être fermée par l’hôte distant
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- End of inner exception stack trace ---
   at Microsoft.UpdateServices.Administration.AdminProxy.CreateUpdateServer(Object[] args)
   at CallSite.Target(Closure , CallSite , Type , Object , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by garnier-quentin** [comment]
There is a connection issue. A firewall ?

**Comment by blodka** [comment]
completly disable, so it actually work if I put UseSSL to true, and with the FQDN of the server. How can I change the value of the UseSSL for the plugin ?

**Comment by garnier-quentin** [comment]
That option: ```--use-ssl```

**Comment by blodka** [comment]
Well I added the extra option to every service concerned, that's all good. 
Another good thing done there. Thanks a lot.
