### ISSUE TITLE
Check_Centreon_NRPE : Unknown option: warning at /usr/src/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.

### ISSUE THREAD

**Issue by egl35720** [centreon/centreon-plugins#2112]
Hello to all,

I have an issue using template OS-Linux-NRPE-custom and service OS-Linux-Swap-NRPE-Custom

**The check command returns Unknown option: warning at /usr/src/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.**

The command line sent by poller is \:

**/usr/lib64/nagios/plugins/check_centreon_nrpe -H 10.17.83.12 -p 5666 -t 30 -u -m 8192 -c check_centreon_plugins -a 'os::linux::local::plugin' 'swap'  ' --warning-core=10 --critical=30'**

Thank you for your help

Regards

**Comment by garnier-quentin** [comment]
It's an old pack. Please use NRPE3. Moreover your pack is not in last version.

**Comment by egl35720** [comment]
Thank you Quentin, 

Ok for NRPE3 but I'am not sure I well understood your response "Ask un slack"

**Comment by garnier-quentin** [comment]
You have a slack: centreon.slack.com

**Comment by egl35720** [comment]
Thank You Quentin, Your response is very clear.
This issue in this post can be closed
