### ISSUE TITLE
[apps::citrix::local] Most of the modes not working ?

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2118]
Hi,

`apps::citrix::local`, `license` mode is properly working, but the 3 others (`session`, `zone`,  `folder`)  return :
```
UNKNOWN: Cant create server object:Win32::OLE(0.1712) error 0x80041002
    after character 0 in "winmgmts:root\citrix"
```
And looking at the code, `license` gets `winmgmts:root\CitrixLicensing` object.
While the 3 others get `winmgmts:root\citrix` object.
Certainly the reason.

Any clue ?

Thank you 👍

**Comment by UrBnW** [comment]
@joschi99 seems like you use this plugin (#1626), do you encounter same issue ?
Many thanks !

**Comment by garnier-quentin** [comment]
It exists. Maybe you need to install a module ? Or in new version, it's different. I don't know

**Comment by UrBnW** [comment]
I close this for now, and will report if I get additional details.
At least for now, after having checked through WMI directly, `winmgmts:root\citrix` does not exist on the Citrix servers I'm dealing with...
