### ISSUE TITLE
[Question] network::fortinet::fortigate: Interfaces

### ISSUE THREAD

**Issue by tblondy** [centreon/centreon-plugins#2122]
Hi,

Using the interface mode, I'm trying to set critical & warning states for a traffic drop.
For example : 
if traffic under 10% of interface speed
if between 11 and 20% warning
Above 21% ok

Is there any way of doing so ? 
Setting a --critical-in-traffic=10 --warning-in-traffic=20 only returns critical states (since traffic is above that)

**Comment by garnier-quentin** [comment]
You can do it like that: ```--warning-in-traffic=20: --critical-in-traffic=10: --units-traffic=%```

**Comment by tblondy** [comment]
Excellent, thanks
