### ISSUE TITLE
[network::watchguard::snmp::plugin] - Status Information Help + Request 

### ISSUE THREAD

**Issue by centicent** [centreon/centreon-plugins#2128]
Hello,

i need a bit of help for creating checks for watchguards. 
The plugin is working, but i have some questions. 

**_1. Question, maybe general (How to format the output of centreon-plugins.pl)_**

Command:
`centreon_plugins.pl --plugin=network::watchguard::snmp::plugin --hostname=10.0.xx.xx --snmp-version=2c --snmp-community=public --mode=list-interfaces`

Is there a way to format the output in centreon at "Status Information"? Currently the output ist:

`List interfaces: 'eth0' [speed = 10][status = down][id = 65536][type = ethernetCsmacd]\n'eth1' [speed = 1000][status = up][id = 65537][type = ethernetCsmacd]\n'eth2' [speed = 10][status = down][id = 65538][type = ethernetCsmacd]\n'eth3' [speed = 10][status = down][id = 65539][type = ethernetCsmacd]\n'eth4' [speed = 10][status = down][id = 65540][type = ethernetCsmacd]\n'sw10' [speed = 1000][status = up][id = 65546][type = ethernetCsmacd]\n'sw11' [speed = 1000][status = up][id = 65547][type = ethernetCsmacd]\n`

-----------------

**_2. Question_**
-  Is there a way to monitor set up branch-office tunnels?
- Is there a way to display the current installed Firmware? and warn when below fw xxx

Thank you :+1:

**Comment by garnier-quentin** [comment]
```Is there a way to format the output in centreon at "Status Information"?```
you can use --mode=interfaces. But you can add list-interfaces in centreon also (but you won't have thresholds)

```Is there a way to monitor set up branch-office tunnels?```
Have you tried the mode ```ipsec-tunnel``` ? 

```Is there a way to display the current installed Firmware? and warn when below fw xxx```
you should try the plugin ```apps::protocols::snmp::plugin``` with modes ```numeric-value``` or ```string-value```

**Comment by centicent** [comment]
> `Is there a way to format the output in centreon at "Status Information"?`
> you can use --mode=interfaces. But you can add list-interfaces in centreon also (but you won't have thresholds)
Thank you, will try it.

> `Is there a way to monitor set up branch-office tunnels?`
> Have you tried the mode `ipsec-tunnel` ?
Not yet, but it seems that this is what i am looking for


> `Is there a way to display the current installed Firmware? and warn when below fw xxx`
> you should try the plugin `apps::protocols::snmp::plugin` with modes `numeric-value` or `string-value`
I dont know how to do it like this, but i will try it out. Thank you

**Comment by centicent** [comment]
@garnier-quentin 

Output: 
`OK: Interface 'eth1' Status : up (admin: up)`
--
CODE:
`$CENTREONPLUGINS$/centreon_watchguard_snmp.pl --plugin=$_SERVICEPLUGIN$ --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community= $_HOSTSNMPCOMMUNITY$ --mode=$_SERVICEMODE$  --name --interface=$_SERVICEINTERFACE$ $_SERVICEOPTION$ --critical-status=$_SERVICECRITICALS$ --warning-status=$_SERVICEWARNINGS$`

Can you please tell me how to remove (admin: up) that i have in status:
OK: Interface 'eth1' Status : up

**Comment by garnier-quentin** [comment]
Try that: ``` --change-short-output='\(admin:.*?\)~~'```
