### ISSUE TITLE
os::windows::snmp::plugin Mode Time

### ISSUE THREAD

**Issue by myOmikron** [centreon/centreon-plugins#2129]
## Bug/Question

I'm using the os::windows::snmp::plugin and getting the error:
`UNKNOWN: Couldn't connect to ntp server: decode() needs data. at /usr/share/perl5/vendor_perl/Net/NTP.pm line 413.`

I've running several checks of this type on the same poller and some of them change to UNKNOWN, for a few minutes, than change back to normal.

**Comment by garnier-quentin** [comment]
Could you provide the command used ?

**Comment by myOmikron** [comment]
/usr/lib/plugins/centreon-plugins/./centreon_plugins.pl --plugin os::windows::snmp::plugin --mode time --hostname xxx-xxx-xxx-xxx --snmp-version 2c --snmp-community xxxxxxxxxxx --warning-offset 60 --critical-offset 600 --ntp-hostname 0.de.pool.ntp.org --ntp-port 123 --timezone :Europe/Berlin

**Comment by garnier-quentin** [comment]
I tried and it's working. Which version of 'Net/NTP' do you use ?

**Comment by myOmikron** [comment]
It doesn't happen all the time, so most of the time, the checks work just fine.

NET::NTP is at version 1.5

**Comment by garnier-quentin** [comment]
I have reproduced. It happens when we have a timeout. Try to replace in file Net/NTP.pm:
```
     my $data;
#    eval{
#    local $SIG{ALRM} = sub { warn "Net::NTP timed out geting NTP
packet\n"; exit;};
#    alarm(5);
#    $sock->recv($data,960)
#        or die "recv() failed: $!\n";
#    alarm(0);
#    };
#

    my $rin = '';
    vec($rin,$sock->fileno(),1) = 1 ;

    my $rout = $rin;
    select($rout,undef,undef,$TIMEOUT) ;

    if (vec($rout,$sock->fileno(),1))  {
        $sock->recv($data,960)
            or die "recv() failed: $!";
    }
    else {
        die "Net::NTP timed out geting NTP packet" ;
    }
```

**Comment by myOmikron** [comment]
Looks good, have recognized no changes for the last 1 1/2 hours. Thanks for your help
