### ISSUE TITLE
Plugin Dell S5000 / OS9

### ISSUE THREAD

**Issue by jaltmeyer** [centreon/centreon-plugins#2130]
Hi,

Dell S-series plugin doesn't work for this S5000. Snmpwalk attached, it is possible to create an appropriate plugin or update the S-series plugin ?

Regards,
[Dell_S5000_OS9.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/5008178/Dell_S5000_OS9.snmpwalk.txt)

**Comment by dalfo77** [comment]
Ciao,
I'm asking too a plugin to query switch Dell with OS 9
I attach the snmpwalk of a "Dell Networking S6010-ON switch/router"

[dell-OS9.snmpwalk.gz](https://github.com/centreon/centreon-plugins/files/5181613/dell-OS9.snmpwalk.gz)

Thanks,

**Comment by garnier-quentin** [comment]
Dell uses a new branch (.1.3.6.1.4.1.6027.3.26 - DELL-NETWORKING-CHASSIS-MIB.mib) for os9. The branch still uses force10 entreprise branch (.1.3.6.1.4.1.6027). So i'm going to add it with force10.

**Comment by garnier-quentin** [comment]
Should be ok now with last version!
