### ISSUE TITLE
Alcatel omniswitch 6450

### ISSUE THREAD

**Issue by blodka** [centreon/centreon-plugins#2131]
Hi all,

I added the plugin to monitor the alcatel omniswitch 6450, and I end up with an issue like here :
https://github.com/centreon/centreon-plugins/issues/647
I can still exclude the fan as mentionned, however the issue seemed to be fix then. The plugin is up to date as well as the centreon server.

Here is the command line :

/usr/lib/centreon/plugins/centreon_alcatel_omniswitch_snmp.pl
	--plugin=network::alcatel::omniswitch::snmp::plugin
	--mode=hardware
	--hostname=XXX.XXX.XXX.XXX
	--snmp-version='2c'
	--snmp-community='community'
	--snmp-autoreduce
	--verbose

and here is the result :

UNKNOWN: fan 'Chassis/Chassis/569.2' status is noStatus - fan 'Chassis/Chassis/569.1' status is noStatus - fan 'Chassis/Chassis/569.4' status is noStatus - fan 'Chassis/Chassis/569.3' status is noStatus | 'power_569'=22W;;;0; 'power_65'=22W;;;0; 'power_1'=22W;;;0; 'power_97'=150W;;;0; 'count_chassis'=1;;;; 'count_fan'=4;;;; 'count_module'=2;;;; 'count_psu'=1;;;;
Checking backplane
Checking chassis
chassis 'Chassis/Chassis' [instance: 569, admin status: powerOn] operationnal status is up.
Checking container
Checking fan
fan 'Chassis/Chassis' [instance: 569.2] status is noStatus
fan 'Chassis/Chassis' [instance: 569.1] status is noStatus
fan 'Chassis/Chassis' [instance: 569.4] status is noStatus
fan 'Chassis/Chassis' [instance: 569.3] status is noStatus
Checking module
module 'CMM-1/CMM' [instance: 65, admin status: powerOn] operationnal status is up.
module 'NI-1/8 POE 10/100/1000 + 2 Combo + 2 5G STK/UPLINK' [instance: 1, admin status: powerOn] operationnal status is up.
Checking other
Checking port
Checking power supplies
power supply 'PS-1/OS unknown Power Supply' [instance: 97, admin status: powerOn] operationnal status is up.
Checking sensors
Checking stack
Checking unknown

this is returning a value unknown. The others value are good ( CPU,....) only the service hardware is doing that
I don't know if the versions can be link but here you have 

Version:
   Package           Release       Size     Description
-----------------+---------------+--------+-----------------------------------
KFbase.img        6.7.2.107.R03   17974258 Alcatel-Lucent Enterprise Base Softw
KFos.img          6.7.2.107.R03    3562268 Alcatel-Lucent Enterprise OS
KFeni.img         6.7.2.107.R03    6142104 Alcatel-Lucent Enterprise NI softwar
KFsecu.img        6.7.2.107.R03     647681 Alcatel-Lucent Enterprise Security M
KFdiag.img        6.6.4.288.R01    2329809 Alcatel-Lucent Enterprise Diagnostic

And I have another unknown with the version 6.6.5.63.R02 GA,

I have a few of the same model returning OK, version  6.7.1.76.R04. I didn't check all of them but if needed I can check a few extra.

Thanks in advance for any clue you may have.

Regards.

Edit : It could actually be nice if the firmware version could be shown via the plugin.

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk output of following OIDs ?
.1.3.6.1.4.1.6486.800.1.1.1.3.1.1.11.1.2
.1.3.6.1.4.1.6486.801.1.1.1.3.1.1.11.1.2

**Comment by ManuHry** [comment]
Hi all, I have the same issue with OS6350 model.

You can find below result of asked snmpwalk :

- 1.3.6.1.4.1.6486.800.1.1.1.3.1.1.11.1.2

  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.569.1 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.569.2 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.569.3 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.570.1 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.570.2 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.570.3 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.571.1 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.571.2 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.571.3 = INTEGER: 2

- 1.3.6.1.4.1.6486.801.1.1.1.3.1.1.11.1.2

  > SNMPv2-SMI::enterprises.6486.801.1.1.1.3.1.1.11.1.2 = No Such Object available on this agent at this OID

Same with 2 stacked switches :

- 1.3.6.1.4.1.6486.800.1.1.1.3.1.1.11.1.2

  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.569.1 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.569.2 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.569.3 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.569.4 = INTEGER: 0
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.570.1 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.570.2 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.570.3 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.570.4 = INTEGER: 0
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.571.1 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.571.2 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.571.3 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.571.4 = INTEGER: 0
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.572.1 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.572.2 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.572.3 = INTEGER: 2
  > SNMPv2-SMI::enterprises.6486.800.1.1.1.3.1.1.11.1.2.572.4 = INTEGER: 0

- 1.3.6.1.4.1.6486.801.1.1.1.3.1.1.11.1.2

  > SNMPv2-SMI::enterprises.6486.801.1.1.1.3.1.1.11.1.2 = No Such Object available on this agent at this OID

Thanks and best regards.

**Comment by garnier-quentin** [comment]
Sorry but i will need more. Could you provide the full snmpwalk for the following branches ? (you can sent it to my email directly):
.1.3.6.1.2.1.47.1.1.1.1
.1.3.6.1.4.1.6486.800

**Comment by ManuHry** [comment]
No problem, I stay at your disposal ! I am generating them, but it takes some time for the second one.
I am sending them to your email, thanks.

**Comment by garnier-quentin** [comment]
It's fixed: https://github.com/centreon/centreon-plugins/pull/3393
