### ISSUE TITLE
[apps::iis::local::plugin] little bugs

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2132]
Hi @garnier-quentin ,
im testing iis local refactoring (Ref. https://github.com/centreon/centreon-plugins/issues/2095) and i found 3 bugs:

1. If you filter counters for user.anonymous text details don't get printed in output but only as perfdata

Command:
[root@xxx~]# /usr/lib/nagios/plugins//check_centreon_nrpe3 -H xxx -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'webservice-statistics --statefile-dir=C:/Windows/Temp/ --filter-name="Default Web Site" --filter-counters='^user''

Result:
OK: Site 'Default Web Site'  | 'Default Web Site#site.users.anonymous.persecond'=78/s;;;0;

2. if you filter counters for connection-attempt output it's printed out 2 times

[root@xxx ~]# /usr/lib/nagios/plugins//check_centreon_nrpe3 -H xxx -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'webservice-statistics --statefile-dir=C:/Windows/Temp/ --filter-name="Default Web Site" --filter-counters='^connect''

Result:
OK: Site 'Default Web Site' connections-attempt : Buffer creation, connections-attempt : Buffer creation |

3. if filter for request counters there are to many digit after dot, can we have integer number?
Same append for connection-attempt result

OK: Site 'Default Web Site' requests post: 81.4391534391534/s, requests get: 0.243386243386243/s

thanks

**Comment by garnier-quentin** [comment]
First option: add option ```--display-ok-counters=users-anonymous```
Second: it's a bug. it fixed it

**Comment by R00T88** [comment]
Hi @garnier-quentin 
Thanks and fast!
