### ISSUE TITLE
OS-Linux-Uptime-SNMP warning-uptime/critial-uptime

### ISSUE THREAD

**Issue by wackou72** [centreon/centreon-plugins#2133]
Hello,
It's look like the plugin change warning and critical to 

- warning-uptime
- critical-uptime

`/usr/lib/centreon/plugins/centreon_linux_snmp.pl
	--plugin=os::linux::snmp::plugin
	--mode=uptime
	--hostname=SERVER.DOMAIN.COM
	--snmp-version='2c'
	--snmp-community='secret' 
	--warning=''
	--critical=''`

Unfortunately, we can't change the command as it is locked.

How can we change this ?

Thanks

**Comment by garnier-quentin** [comment]
You need to update your plugin-pack in centreon-web (need also to update the rpm if you use rpm) and push configuration

**Comment by wackou72** [comment]
No update available
![image](https://user-images.githubusercontent.com/21340779/89305607-25ac8a80-d66f-11ea-977d-281c1076b432.png)

**Comment by garnier-quentin** [comment]
You need to update the rpm pack file on your central server.

**Comment by wackou72** [comment]
How ?

**Comment by garnier-quentin** [comment]
```yum install "centreon-pack*"```

**Comment by wackou72** [comment]
![2020-08-04 16_33_50-root@FRGRPCENTREON01P_~](https://user-images.githubusercontent.com/21340779/89306810-a7e97e80-d670-11ea-850e-92b9dd275e16.png)
![2020-08-04 16_36_08-root@FRGRPCENTREON01P_~](https://user-images.githubusercontent.com/21340779/89306829-ac159c00-d670-11ea-8d1e-1bc1657950a1.png)


Did something need to be changed on the source file ?
As you can see, I have updated today the Central, I'm on 20.04

**Comment by garnier-quentin** [comment]
Maybe you use online pack ?

**Comment by wackou72** [comment]
I use both, but the SNMP-Linux is pushed directly from Configuration --> Plugins Packs and I use the standart command
See :
![2020-08-04 16_41_43-Centreon - IT   Network Monitoring](https://user-images.githubusercontent.com/21340779/89307668-a40a2c00-d671-11ea-94e7-1885976809a8.png)
![2020-08-04 16_42_06-Centreon - IT   Network Monitoring](https://user-images.githubusercontent.com/21340779/89307677-a5d3ef80-d671-11ea-9eb2-ef934f126afb.png)
![2020-08-04 16_42_16-Centreon - IT   Network Monitoring](https://user-images.githubusercontent.com/21340779/89307685-a8364980-d671-11ea-841f-802df953466f.png)
![2020-08-04 16_42_37-Centreon - IT   Network Monitoring](https://user-images.githubusercontent.com/21340779/89307700-ac626700-d671-11ea-8c92-ccdd06c2e3bc.png)


Any idea ?

**Comment by Sismic** [comment]
Hi, same issue here with OS-Windows-Uptime-SNMP-custom, i update Windows SNMP  to 3.2.4 and issue appears immediatly 
![image](https://user-images.githubusercontent.com/6815687/89309719-0fed9400-d674-11ea-9558-21c4b6b90309.png)

**Comment by wackou72** [comment]
Hi,
Same version for Linux SNMP, 3.2.4
![image](https://user-images.githubusercontent.com/21340779/89379671-7c10dc00-d6f6-11ea-9890-67736d03f71f.png)

**Comment by MyL0-afk** [comment]
Same for me ...

**Comment by wackou72** [comment]
The plugin help report the right information, just the command template that wasn't updated.
![image](https://user-images.githubusercontent.com/21340779/89405180-711c7280-d71b-11ea-8c6d-bf801c827da4.png)

i've also doubt on the `OS-Linux-Memory-SNMP-custom` even with the extra option `--autodetect-redhat` it still show wrong negative value (don't have this issue before the update)

In the meantime, I set the uptime in ackownledge mode ...

**Comment by garnier-quentin** [comment]
I have revert the patch for --autodetect-redhat because redhat revert the patch on net-snmp. So you need to update net-snmp and it should be ok.

**Comment by wackou72** [comment]
@garnier-quentin thanks for this information, I will wait for the RPM to be updated.
What about the `OS-Linux-Uptime-SNMP`, did we find a bug ?

**Comment by garnier-quentin** [comment]
Not really. Online pack are not sync again. We are going to sync it.

**Comment by wackou72** [comment]
Thanks for the feedback !

**Comment by garnier-quentin** [comment]
i close it. it's not a centreon-plugins issue directly
