### ISSUE TITLE
[apps::protocols::x509] New request

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2139]
Hi all,
it's possibile to have a mode to check local machine certificate expirations installed on a windows server?

Thanks

**Comment by garnier-quentin** [comment]
Could you provide me a certificate example ? The file is in a directory ?

**Comment by garnier-quentin** [comment]
There is a new custommode with x509 plugin. You can test it on windows also: https://github.com/centreon/centreon-nsclient-build/releases/tag/20210218110204
```
$ perl centreon_plugins.pl --plugin=apps/protocols/x509/plugin.pm --custommode=file --mode=certificate --certificate=/etc/ssl/certs/ssl-cert-snakeoil.pem --verbose 
OK: Certificate for 'xubuntu' expires in '2815' days [2029-01-04T12:25:35Z] - Issuer: '/CN=xubuntu' |
Alternative subject names: xubuntu.
```
