### ISSUE TITLE
[os::windows::snmp::plugin] mode=service retourne toujours Ok

### ISSUE THREAD

**Issue by GrinGrin** [centreon/centreon-plugins#214]
Bonjour,

J'ai un soucis avec le mode service du plugin Windows SNMP: quel que soit le nom du service que je donne, qu'il soit démarré, arrêté ou absent, j'ai toujours un retour "OK: All service states are ok |"

Par exemple:
`./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --snmp-community=public --snmp-version=2 --hostname=dc1.domain.local --service=truc`
`OK: All service states are ok |`
alors que le service 'truc' n'existe pas.
L'ajout du paramètre --state ne change rien

Cordialement,
Nicolas.

**Comment by garnier-quentin** [comment]
You need to set a threshold.

**Comment by garnier-quentin** [comment]
The threshold you should use: --critical=1:

**Comment by gerpion** [comment]
Bonjour,
Je me permet de réouvrir cette demande étant donné que j'ai un problème similaire.
Même en mettant un --critical, j'ai toujours le même résultat :

* Service arrêté :

./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode service --hostname pc-001840 --snmp-version 2 --snmp-community public --service vds  --critical 1:
CRITICAL: Service problem 'vds' |


* Service démarré :
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode service --hostname pc-001840 --snmp-version 2 --snmp-community public --service vds  --critical 1:
CRITICAL: Service problem 'vds' |

* Nom de service qui n'existe pas : 
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode service --hostname pc-001840 --snmp-version 2 --snmp-community public --service vdsxwcxwcwcwxcwc  --critical 1:
CRITICAL: Service problem 'vdsxwcxwcwcwxcwc' |

Une idée ?

**Comment by garnier-quentin** [comment]
Be aware. Whe  you stop or start a service, it takes a long time before the snmp update its status.

**Comment by gerpion** [comment]
True.
Just to notice, i had to use the long service name to make it work !
Checking SNMP didnt work well when "Service SNMP" is ok.

The change status in SNMP OIDs seems to be like 60 sec or so.

Thanks for the fast answer.

**Comment by garnier-quentin** [comment]
Thanks for the feedback.
