### ISSUE TITLE
Cisco ASA Connections on multi context ASAs?

### ISSUE THREAD

**Issue by MarcusCaepio** [centreon/centreon-plugins#2143]
Hi all,
we have several ASAs with multiple security contexts. By default, wie contact the admin context via SNMP to get load, mem etc. But with the connections check mode, we don't get the connections of all the contexts, only the connections of the admin context. How do we get the connections of all contexts?
Thanks in advance!

**Comment by garnier-quentin** [comment]
For each security context, you cannot have an specific address and snmp configuration ?

**Comment by MarcusCaepio** [comment]
I guess, we have to go this way. Normaly you don't need it, because you can switch the context from the management IP and from ASDM.

**Comment by garnier-quentin** [comment]
Maybe you can use snmp context ?

**Comment by MarcusCaepio** [comment]
I tried it but it didn't work. Idk if I did sth. wrong or it is just not supported. We decided to configure an IP for every context. Issue can be closed from my side

**Comment by Sims24** [comment]
Hi @MarcusCaepio 

I think snmp-community should be enough. Something similar to https://community.cisco.com/t5/xr-os-and-platforms/monitor-bgp-sessions-on-vrfs-with-xr-4-2-using-snmp/m-p/2254983/highlight/true#M2019
