### ISSUE TITLE
[os::windows::snmp::plugin] FR: Services en automatique

### ISSUE THREAD

**Issue by GrinGrin** [centreon/centreon-plugins#215]
Bonjour,

Un mode pour vérifier que tous les services configurés pour démarrer en automatique soient bien à l'état démarré pourrait être intéressante si on ne souhaite pas déclarer chaque service installé à la main.

Une option pour éventuellement exclure certains noms de services de la vérification pourrait être utile par exemple pour les services comme "sppsvc" (Software Protection) qui sont défini en démarrage automatique mais ne sont démarrés qu'à la demande du système.

Cordialement,
Nicolas.

**Comment by garnier-quentin** [comment]
Hi,

It will be great. But we don't have the information to know if a windows  service is automatic or not in snmp :(
