### ISSUE TITLE
[apps::mq::rabbitmq::restapi::mode::listnodes] Status not working?

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#2150]
On apps::mq::rabbitmq::restapi::mode::listnodes module the status seems to be not working.

We are running RabbitMQ 3.6.15 (/!\ this is not last version of RabbitMQ and i'm not able to test it on 3.8 release) and here what we get with centreon plugin list-node module : 

```
./centreon_plugins.pl --plugin=apps::mq::rabbitmq::restapi::plugin --mode=list-nodes --hostname=XXX.XXX.XXX.XXX--port='15672' --username='XXX' --password='XXX'
List nodes:
[name = rabbit@SERVER01][status = notrunning]
[name = rabbit@SERVER02][status = notrunning]
```

Here is the output of http://XXX.XXX.XXX.XXX:15672/api/nodes?columns=name : 
`[{"name":"rabbit@SERVER01"},{"name":"rabbit@SERVER02"}]`

When adding running in the curl here is the output : 
http://XXX.XXX.XXX.XXX:15672/api/nodes?columns=name,running
`[{"name":"rabbit@SERVER01","running":true},{"name":"rabbit@SERVER02","running":true}]`

**Comment by garnier-quentin** [comment]
thanks! it should be fixed
