### ISSUE TITLE
[network::stonesoft::snmp::mode::clusterstate]

### ISSUE THREAD

**Issue by kabreu** [centreon/centreon-plugins#2157]
Hello,

https://github.com/centreon/centreon-plugins/blob/master/network/stonesoft/snmp/mode/clusterstate.pm

There is no option to change/customize OK/unknown/warning/critical states on this mode.
Could you please add a way to customize the output ?

Thanks.

**Comment by garnier-quentin** [comment]
Coud you test it ?
