### ISSUE TITLE
[apps::vmware::connector::plugin] --filter seem to have a bug

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon-plugins#216]
Hello,

I'm trying to monitor my VMWARE Datastores and to filter some of them.
When i'm using the --filter-perfdata, i'm able to filter the one i want :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname 127.0.0.1 --mode datastore-usage --warning 95 --critical 99 --filter-perfdata '.*DEV-1.*'

WARNING: Datastore 'esx3.bdxdom.mck-ScaleIO_DS-2' Total: 199.75 GB Used: 190.95 GB (95.59%) Free: 8.80 GB (4.41%) Provisioned: 190.95 GB (95.59%) - Datastore 'esx1.bdxdom.mck-ScaleIO_DS-3' Total: 199.75 GB Used: 190.95 GB (95.59%) Free: 8.80 GB (4.41%) Provisioned: 190.95 GB (95.59%) - Datastore 'esx2.bdxdom.mck-ScaleIO_DS-1' Total: 199.75 GB Used: 190.95 GB (95.59%) Free: 8.80 GB (4.41%) Provisioned: 190.95 GB (95.59%) | 'used_SAN-DEV-1'=3601227317248B;0:4177889171865;0:4353800294891;0;4397778075648 'provisioned_SAN-DEV-1'=3673727844992B;;;0;4397778075648

As you can notice, i'm getting some warning in the output not related with the datastores i'm filtering in the perf-data. So i want to filter them with --filter.
But if i'm using the --filter, it doesnt work and i'm getting the whole datastores.

Any clue ?

Regards,

Bruno.

**Comment by garnier-quentin** [comment]
Hi,

If you want to filter a datastore, use following options: 
--datastore-name='DEV-1' --filter

**Comment by gerpion** [comment]
In fact, i want to filter all datastores with the word 'SAN' in it. That's why i want to use --filter (regexp) and not --datastore-name.

**Comment by garnier-quentin** [comment]
filter option is for that: Datastore name is a regexp.
So it should be: --datastore-name='.*SAN.*' --filter

**Comment by gerpion** [comment]
Great, all good. Thanks Quentin. I'm closing the issue.
