### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by Infopromt** [centreon/centreon-plugins#2161]
https://github.com/centreon/centreon-plugins/blob/b224bb5f4a0c927f3c927bf5b1c9116f09896e8a/hardware/devices/video/axis/snmp/mode/environment.pm#L41

May be 
 ['failure', 'CRITICAL'] ,

**Comment by thibaults-centreon** [comment]
Hello,
Thanks for your feedback, issue has been fixed.
