### ISSUE TITLE
plugin database::oracle : working on shell as root but not centreon-engine nor on webUI 

### ISSUE THREAD

**Issue by jcvd94** [centreon/centreon-plugins#2171]
Hello,
i encounter a similar problem as #1587, at the difference that this command works under root, but not under centreon-engine :

bash-4.2$ /usr/lib/centreon/plugins/centreon_plugins.pl --plugin database::oracle::plugin --mode=tnsping --hostname=XXX --port=1548 --sid=XXX
CRITICAL: Cannot connect: (no error string) |

i followed this tutorial for Oracle client setup : https://pixelabs.fr/oracle-client-19c-installation-sous-centos7-centreon/

And the same, not working better under WUI.

if garnier-quentin could help :)

i think its due to DBD::Oracle is installer under /root directory, but don't know how to install it in another path !

Thanks a lot !!

**Comment by thibaults-centreon** [comment]
Have you tried following this documentation: https://docs.centreon.com/current/en/integrations/plugin-packs/procedures/applications-databases-oracle.html
It was for version 12 but it does work with version 19 too

**Comment by garnier-quentin** [comment]
Yes that the issue. To install DBD::Oracle, remove shell environment variable with PERLxxx.

**Comment by garnier-quentin** [comment]
No news. tell use if you still have the issue.
