### ISSUE TITLE
[Pacemaker] Use new SSH backend

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2176]
Hi,

As proposed in #2007, could you please update `apps::pacemaker::local::mode::crm` to use the new SSH backend ?

Thank you very much 👍

**Comment by garnier-quentin** [comment]
You can test it ?

**Comment by UrBnW** [comment]
Sure, many thanks, I come back to you ASAP 👍

**Comment by UrBnW** [comment]
Works perfectly, thank you 👍
