### ISSUE TITLE
[apps::mulesoft::restapi::plugin] mode messages - Bug

### ISSUE THREAD

**Issue by MaxCentreon** [centreon/centreon-plugins#2188]
There is some problems with mode message in new plugin mulesoft

You can see the problem below

/usr/lib/centreon/plugins/centreon_mulesoft_restapi.pl --plugin=apps::mulesoft::restapi::plugin --mode=messages --environment-id='*******************' --organization-id='*********************' --api-username='****' --api-password='************' --region-id='eu-central-1'  --timeframe='' --period='' --filter-name='^*****************$' --warning-total='' --critical-total='' --warning-inflight='' --critical-inflight=''  --warning-received='' --critical-received='' --warning-sent='' --critical-sent='' --warning-visible='' --critical-visible='' --warning-acked='' --critical-acked='' --verbose

Argument "" isn't numeric in subtraction (-) at /usr/lib/centreon/plugins/centreon_mulesoft_restapi.pl line 1148.
UNKNOWN: Can't use string ("Unable to parse the date jeu., 0"...) as an ARRAY ref while "strict refs" in use at /usr/lib/centreon/plugins/centreon_mulesoft_restapi.pl line 1179.

**Comment by garnier-quentin** [comment]
Could you provide the result with --debug option ?

**Comment by MaxCentreon** [comment]
for sure :

Argument "" isn't numeric in subtraction (-) at /usr/lib/centreon/plugins/centreon_mulesoft_restapi.pl line 1148.
UNKNOWN: Can't use string ("Unable to parse the date ven., 0"...) as an ARRAY ref while "strict refs" in use at /usr/lib/centreon/plugins/centreon_mulesoft_restapi.pl line 1179.

thx by advance
