### ISSUE TITLE
Add service tag and link to Dell website for Dell Openmanage plugin

### ISSUE THREAD

**Issue by lune001** [centreon/centreon-plugins#2192]
Hi, i used to have check_openmanage from nagios, with the --htmlinfo option.
Can't find this with centreon openmanage plugin, could you add this very usefull information ?
Also Dell have devloped a new nagios plugin who can grab the warranty date from website. I think it could be really great to have this on our centron openmanage plugin

**Comment by garnier-quentin** [comment]
htmlinfo adds dell link in the long output (it seems). Maybe i can add an option to add custom text in long output ? Because it's too specific. 
For the second, it's the same that the first, but it uses a dynamic field (serial of the server)

**Comment by lune001** [comment]
Hi, IT would be great if you can add this in the long output yes ! (for both)
Thanks !

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
