### ISSUE TITLE
High cpu usage of os::linux::snmp::plugin, tcpconn plugin

### ISSUE THREAD

**Issue by moix** [centreon/centreon-plugins#2196]
## Bug

Hi, I've noticed that the os::linux::snmp::plugin tcpconn plugin (snmp_standard tcpcon) makes that snmpd process in target server has a peak of cpu usage.

I wonder if anyone else has noticed it before and there's anything in configuration of plugin argument that can be tuned to reduce it. Thanks

**Comment by garnier-quentin** [comment]
The plugin try to look for 2 OIDs first:
.1.3.6.1.2.1.6.20.1.4
.1.3.6.1.2.1.6.19.1.7

If there are no values, the plugin try to look for that OID:
.1.3.6.1.2.1.6.13.1.1

It's very few. But maybe you have many connections. So maybe you should use the local plugin.

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk of following branches ?
.1.3.6.1.2.1.6.20.1
.1.3.6.1.2.1.6.13.1.1

Maybe it would be better with --snmp-force-getnext. Could you test it ?
