### ISSUE TITLE
network::citrix::netscaler::snmp::plugin - mode error in command

### ISSUE THREAD

**Issue by ChristophePelichet** [centreon/centreon-plugins#2199]
Hello, 

I think  we have a type error in the cpu command check for the plugin network::citrix::netscaler::snmp::plugin

by default on you locked command you use **warning** and **critical** service variable :

"$CENTREONPLUGINS$/centreon_netscaler.pl --plugin=network::citrix::netscaler::snmp::plugin --mode=cpu --hostname='$HOSTADDRESS$' --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$
"

and we have the error : Unknown option: warning at /usr/lib/centreon/plugins/centreon_netscaler.pl line 141.

But if i check the help , the real mode is mode --warning**-usage** and --critical**-usage** and if i try the command manually with this option the command is  working

bash-4.2$ /usr/lib/centreon/plugins/centreon_netscaler.pl --plugin=network::citrix::netscaler::snmp::plugin --mode=cpu --hostname='10.11.3.32' --snmp-version='1' --snmp-community='snixionmp'  --warning-usage='90' --critical-usage='95'  --verbose
OK: All CPUs are ok | 'cpu_Mgmt CPU'=0.00%;0:90;0:95;0;100 'cpu_Packet CPU 0'=0.00%;0:90;0:95;0;100
CPU 'Mgmt CPU' usage: 0.00 %
CPU 'Packet CPU 0' usage: 0.00 %

my package version :

rpm -qi centreon-plugin-Network-Loadbalancers-Netscaler-Snmp.noarch
Name        : centreon-plugin-Network-Loadbalancers-Netscaler-Snmp
Version     : 20200803
Release     : 072952.el7.centos
Architecture: noarch
Install Date: Mon 07 Sep 2020 04:02:06 PM CEST
Group       : Development/Libraries
Size        : 422932
License     : ASL 2.0
Signature   : DSA/SHA1, Mon 03 Aug 2020 09:35:33 AM CEST, Key ID f6fc4ae38a7652bc
Source RPM  : centreon-plugin-20200803-072952.el7.centos.src.rpm
Build Date  : Mon 03 Aug 2020 09:35:20 AM CEST
Build Host  : 4b28a60af898
Relocations : (not relocatable)
URL         : https://www.centreon.com/
Summary     : Centreon Plugin
Description :
Centreon plugin

**Comment by garnier-quentin** [comment]
Please update your centreon pack (central server) and reload the configuration.
