### ISSUE TITLE
Follow monitoring-plugins guidelines for perfdata

### ISSUE THREAD

**Issue by nichols-356** [centreon/centreon-plugins#220]
While I can understand the idea behind using UOM such as rpm for fan speed and b/s for data rate, these UOM are unsupported by monitoring systems that follow the "Nagios Plugins" format.

It may be a stretch to ask for such a thing since these UOM were most likely implemented as a feature of the Centreon suite, but I think it would be a good idea to have an argument to trigger a "nagios format perfdata" for those that use Nagios or Icinga2 as their monitoring system. Something like --nagios-perfdata, which would essentially strip out any UOM that do not follow the standard.

Please see the (very short) list of "approved" UOM here: https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

**Comment by garnier-quentin** [comment]
I see. i'll add an option to remove uom.
