### ISSUE TITLE
--extend-perfdata-group broken

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2203]
Hi,

With `master` / `dev` version, the following does not work :
```
--extend-perfdata-group='^(.*)#interface.packets.in.error.percentage$,
                         $1#max.interface.packets.err.percentage,
                         max($1#interface.packets..*),%'
```

But the following does :
```
--extend-perfdata-group='^(.*)#interface.packets.in.error.percentage$,
                         $1#max.interface.packets.err.percentage,
                         max(.*#interface.packets..*),%'
```

The `$1` in the operation (last component) seems to be ignored / not proceeded.

Thx for your support 👍

**Comment by UrBnW** [comment]
https://github.com/centreon/centreon-plugins/commit/729dc65edafce993020057e8dcd5767b91ba4018 does not seem to be the culprit.

**Comment by UrBnW** [comment]
https://github.com/centreon/centreon-plugins/commit/391696c54daafff249a6755cc5869ca6fc00006a / https://github.com/centreon/centreon-plugins/commit/729dc65edafce993020057e8dcd5767b91ba4018 seem to be the culprits.

**Comment by garnier-quentin** [comment]
It comes from following case:
https://github.com/centreon/centreon-plugins/issues/1482

I revert it. And you should use '\$' indeed (case 1482)

**Comment by UrBnW** [comment]
Perfect, thank you Quentin 👍
