### ISSUE TITLE
OS-HPUX-Uptime-SNMP warning-uptime/critical-uptime

### ISSUE THREAD

**Issue by ypilpre** [centreon/centreon-plugins#2208]
Hello,
It's look like the plugin change on HP/UX also  :

/usr/lib/centreon/plugins/centreon_hpux_snmp.pl 	--plugin=os::hpux::snmp::plugin --mode=uptime --hostname=HPUXSERVER --snmp-version='2c' --snmp-community='secret' --warning='' --critical=''
Unknown option: warning at /usr/lib/centreon/plugins/centreon_hpux_snmp.pl line 141.

Unfortunately, we can't change the command as it is locked and PluginPack is not up to date.

warning-uptime and critical-uptime are now mandatory args. (Linked with #2133)

Based on Centreon 19.10.6 :+1: 
**RPM Not Working**  : centreon-plugin-Operatingsystems-Hpux-Snmp-20200803-072952.el7.centos.noarch
_RPM  Working_:  centreon-plugin-Operatingsystems-Hpux-Snmp-20200204-093915.el7.centos.noarch

**Comment by garnier-quentin** [comment]
Have you updated your pack ?

**Comment by ypilpre** [comment]
Last version of the pack is 3.0.3 (already installed)

**Comment by garnier-quentin** [comment]
The last pack version is 3.0.17 (unstable) and 3.0.16 (stable)...
