### ISSUE TITLE
cisco_apic_restapi - Filter-node excluded instead of including

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#2210]
L'option filter-node , exclue au lieu d'inclure le résultat 

/usr/lib/centreon/plugins/centreon_cisco_apic_restapi.pl --plugin=network::cisco::aci::apic::restapi::plugin --mode=node --filter-node='^(pod-1.*node-311)$' --hostname=x.x.x.x' --username='USERNAME’ --password=’PASSWORD’ --http-backend=curl --curl-opt="CURLOPT_SSL_VERIFYPEER => 0"

**--filter-node
Regexp filter on the pod / node name**

--filter-node='^(pod-1.*node-311)$'

**Result** 

skipping 'pod-1/node-311': no matching filter node 'HASH(0x2f65048)'

Node 'pod-1/node-1100' health current: 72 %, min: 72 %, average: 72 %
Node 'pod-1/node-1101' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1102' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1103' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1104' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1105' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1106' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1107' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1108' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1109' health current: 98 %, min: 98 %, average: 98 %
Node 'pod-1/node-111' health current: 100 %, min: 100 %, average: 100 %
Node 'pod-1/node-1110' health current: 100 %, min: 100 %, average: 100 %

**Comment by garnier-quentin** [comment]
Thanks. should be ok now
