### ISSUE TITLE
Bug perfdata on graphics

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2211]
Centreon 19.04, 19.10, 20.04
Could be related to issue #996

Problem description
seem's that rrd graphs are not using option -b 1024, so values like disk spaces (windows, linux ecc.) are reporting the performance data in bytes. The command for this checks having the correct graph template where are configured with base value 1024. But values display on rrd graphs are not correct.

Example from public Centreon Demo plattform:
![image](https://user-images.githubusercontent.com/6400595/92753872-950e4c00-f38a-11ea-9da8-4b7ee9987f5f.png)
![image](https://user-images.githubusercontent.com/6400595/92753956-af482a00-f38a-11ea-8ae0-c4dda0c05f41.png)
![image](https://user-images.githubusercontent.com/6400595/92754035-c7b84480-f38a-11ea-8811-36621283008b.png)

From my point of view the configuration seem's ok.

**Comment by joschi99** [comment]
Seem's related to https://github.com/centreon/centreon/issues/8655?

**Comment by Sims24** [comment]
Hi @joschi99 

Yes this is not related to plugins. Please +1 this centreon issue centreon/centreon#8655.
