### ISSUE TITLE
 MIBs to add Power Supply Status to [network::stormshield::snmp::plugin]

### ISSUE THREAD

**Issue by AlexisAnton** [centreon/centreon-plugins#2212]
Hi !

I recently worked on the supervision of stormshield firewalls through SNMP Protocols but I didn't find the Power Supply mode in the plugin [network::stormshield::snmp::plugin].

So there are the MIBs to control the status of a power supply ( Powered (1) or Unpowered (0) ) : 
.1.3.6.1.4.1.11256.1.11.10.1.2

And another to check the state (Ok / Warning / Critic) : 
.1.3.6.1.4.1.11256.1.11.10.1.3

Hope this will be helpful for your development ! 👍 
Alexis

**Comment by garnier-quentin** [comment]
Could you provide the mib file ?

**Comment by AlexisAnton** [comment]
I just sended you a mail that contains the mib file

**Comment by garnier-quentin** [comment]
You can test the mode hardware with last version
