### ISSUE TITLE
Use SSH command output in short output ?

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2214]
Hi,

I use `os::linux::local::plugin`, `cmd-return` mode, to run `check_logfiles` command through SSH.
Is there a way to get the command output into `cmd-return` short-output ?
`check_logfiles` output is well done, some kind of one-line short-output, in a Centreon/Nagios fashion.
I do not manage to get this done.

Perhaps I missed something, do not use the correct plugin/mode...

Thx 👍

**Comment by garnier-quentin** [comment]
You want a check_by_ssh like ?

**Comment by UrBnW** [comment]
Seems like yes.

**Comment by garnier-quentin** [comment]
maybe in protocols ssh plugin

**Comment by UrBnW** [comment]
`cmd-return` is not too far from it, but it could also have its place in `protocols:ssh` yes.
Up to U, thank U 👍

**Comment by garnier-quentin** [comment]
You have a new mode. Eg:
```
$ perl centreon_plugins.pl --plugin=os::linux::local::plugin --mode=check-plugin  --hostname=10.30.2.203 --ssh-username=root  --verbose --command='/usr/lib/centreon/plugins/centreon-centreon_plugins.pl --plugin=os::linux::local::plugin --mode=storage --verbose'
```

**Comment by UrBnW** [comment]
Absolutely perfect, many thanks !
Goodbye `check_by_ssh` :'-)
