### ISSUE TITLE
[hardware::ups::apc::snmp::plugin] mode "battery-status" and external battery packs for Smart-UPS SRT

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2218]
Hello.

Yesterday we found a problem with the **hardware::ups::apc::snmp::plugin** in mode **battery-status**.
One of our UPSs (APC **Smart-UPS SRT 5000**) has a problem with an external battery pack.

![изображение](https://user-images.githubusercontent.com/17614847/93439543-5cfd9080-f8d7-11ea-9cd6-7fbae8685181.png)

However, the monitoring plugin tells us that everything is fine and there is no problem:

```
./centreon_plugins.pl --plugin=hardware::ups::apc::snmp::plugin --mode=battery-status 
--critical-load='25:100' --critical-temperature='6:44' --critical-time='@0:9' 
--filter-counters='^(?!(current))' --filter-uom='%' 
--snmp-version=2 --snmp-community=public --hostname=UP018

OK: battery status is 'batteryNormal' [battery needs replace: no] [last replace date: 21.01.2020], 
remaining capacity: 100 %, remaining time: 309.00 minutes, voltage: 218 V, temperature: 19 C | 
'load'=100%;;25:100;0;100 'load_time'=309.00;;@0:9;0; 'voltage'=218;;;; 'temperature'=19;;6:44;;
```

I looked in the **PowerNet-MIB** and found OIDs associated with the status of battery packs.
This information is in the branch **upsHighPrecBatteryPacks** (**.1.3.6.1.4.1.318.1.1.1.2.3.10**).

In our example, the UPS has 4 BatteryPacks (1 internal + 3 external battery packs).

![изображение](https://user-images.githubusercontent.com/17614847/93439896-c67d9f00-f8d7-11ea-9f28-9978e5d52327.png)

From **upsHighPrecBatteryPackOnlyStatus** (**.1.3.6.1.4.1.318.1.1.1.2.3.10.4.1.5**):

upsHighPrecBatteryPackOnlyStatus.1.1 = 0000000000000000 <- 1st BatteryPack inside the UPS (internal)
upsHighPrecBatteryPackOnlyStatus.2.1 = 0000000000000000 <- 2nd external Battery Pack
upsHighPrecBatteryPackOnlyStatus.3.1 = 0000000000000000 <- 3rd external Battery Pack
upsHighPrecBatteryPackOnlyStatus.4.1 = 1000000000000000 <- 4th external Battery Pack (problem here. bit 0 = Disconnected)

Bit information in **upsHighPrecBatteryPackOnlyStatus** string from **PowerNet-MIB**:

> The battery status for the pack only:
> bit 0 Disconnected
> bit 1 Overvoltage
> bit 2 NeedsReplacement
> bit 3 OvertemperatureCritical
> bit 4 Charger
> bit 5 TemperatureSensor
> bit 6 BusSoftStart
> bit 7 OvertemperatureWarning
> bit 8 GeneralError
> bit 9 Communication
> bit 10 DisconnectedFrame
> bit 11 FirmwareMismatch

Each battery pack contains 2 cartridges.

![изображение](https://user-images.githubusercontent.com/17614847/93441174-5ae80180-f8d8-11ea-868e-3980212d9309.png)

Cartridge status information is available in the branch **upsHighPrecBatteryPackCartridgeStatus** (**.1.3.6.1.4.1.318.1.1.1.2.3.10.2.1.10**):

upsHighPrecBatteryPackCartridgeStatus.1.1.1 = 0000000000000000 <- 1st cartridge inside the UPS
upsHighPrecBatteryPackCartridgeStatus.1.1.2 = 0000000000000000 <- 2nd cartridge inside the UPS
upsHighPrecBatteryPackCartridgeStatus.2.1.1 = 0000000000000000 <- 1st cartridge in external battery pack # 1
upsHighPrecBatteryPackCartridgeStatus.2.1.2 = 0000000000000000 <- 2nd cartridge in external battery pack # 1
upsHighPrecBatteryPackCartridgeStatus.3.1.1 = 0000000000000000 <- 1st cartridge in external battery pack # 2
upsHighPrecBatteryPackCartridgeStatus.3.1.2 = 0000000000000000 <- 2nd cartridge in external battery pack # 2
upsHighPrecBatteryPackCartridgeStatus.4.1.1 = 0000000000000000 <- 1st cartridge in external battery pack # 3
upsHighPrecBatteryPackCartridgeStatus.4.1.2 = 1000000000000000 <- 2nd cartridge in external battery pack # 3 (problem here. bit 0 = Disconnected)

Bit information in **upsHighPrecBatteryPackCartridgeStatus** string from **PowerNet-MIB**:

> The battery cartridge status.
> bit 0 Disconnected
> bit 1 Overvoltage
> bit 2 NeedsReplacement
> bit 3 OvertemperatureCritical
> bit 4 Charger
> bit 5 TemperatureSensor
> bit 6 BusSoftStart
> bit 7 OvertemperatureWarning
> bit 8 GeneralError
> bit 9 Communication
> bit 10 DisconnectedFrame
> bit 11 FirmwareMismatch

Snmpwalk polling for branch **upsBattery** (**.1.3.6.1.4.1.318.1.1.1.2**) in attachment.

[UPS_APC_Smart-UPS_SRT_5000_withExternalBatteryPacks.zip](https://github.com/centreon/centreon-plugins/files/5237461/UPS_APC_Smart-UPS_SRT_5000_withExternalBatteryPacks.zip)

Can you please extend the logic for checking the battery status?

**Comment by garnier-quentin** [comment]
The mib says it's a bit system. But in fact it's a string which describes bits.. That's weird.

**Comment by garnier-quentin** [comment]
With the mib i cannot know which one is internal, external...

**Comment by garnier-quentin** [comment]
Could you try it ?

**Comment by Aleksey-Maksimov** [comment]
Thanks a lot, Quentin. It looks like the information is now available.

![изображение](https://user-images.githubusercontent.com/17614847/94987104-61c77300-056c-11eb-84a0-34674e97db30.png)
