### ISSUE TITLE
[os::linux::snmp::plugin] mode inodes

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#222]
Hello,

I have these errors when i use this mode on a linux server with a lot of filesystem :

Use of uninitialized value in subtraction (-) at /logiciel/nagios/plugins/centreon-plugins/snmp_standard/mode/inodes.pm line 95.
Use of uninitialized value in numeric lt (<) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in numeric gt (>) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in numeric lt (<) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in numeric gt (>) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in sprintf at /logiciel/nagios/plugins/centreon-plugins/snmp_standard/mode/inodes.pm line 99.
Use of uninitialized value in subtraction (-) at /logiciel/nagios/plugins/centreon-plugins/snmp_standard/mode/inodes.pm line 95.
Use of uninitialized value in numeric lt (<) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in numeric gt (>) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in numeric lt (<) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in numeric gt (>) at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/perfdata.pm line 98.
Use of uninitialized value in sprintf at /logiciel/nagios/plugins/centreon-plugins/snmp_standard/mode/inodes.pm line 99.

But result is OK with a lot of perfdata.

Here the options i use for this :
--plugin=os::linux::snmp::plugin --mode=inodes --diskpath='^(?!(/sys|/dev/pts|/proc|/var/lib/nfs/rpc_pipefs|/proc/sys/fs/binfmt_misc)$)' --name --regexp --warning=90 --critical=90

**Comment by cemir** [comment]
had the same issue, thanks for the fix
