### ISSUE TITLE
[configuration] Embed .xml files

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2221]
Hi,

I open this ticket simply not to forget the good idea submitted [there](https://github.com/centreon/centreon-nsclient-build/issues/15#issuecomment-695968065), to put / embed `.xml` configuration files into code itself.
Seems like there are 2 files like this today, `qwinsta.xml` and `dcdiag.xml`.

This would be convenient, as it would simplify Windows plugins deployment (and usage, to a lesser degree).
This would also allow me to slightly simplify the [CI build procedure](https://github.com/centreon/centreon-nsclient-build/pull/21) (as we would not have to distribute them separately anymore).

Thank you 👍

**Comment by garnier-quentin** [comment]
Could you try ? I have switched libXML to XML::Simple

**Comment by UrBnW** [comment]
Wow nice, thank you 👍
Let's build and try :)

**Comment by UrBnW** [comment]
Works perfectly (but some typos in #2223).
Many thanks !
