### ISSUE TITLE
SQL check issue "database::oracle::plugin"

### ISSUE THREAD

**Issue by khalidbounoun** [centreon/centreon-plugins#2225]
## Bug/Question

Hello, 

I'm using a check with SQL code, using the plugin "database::oracle::plugin" and I get the following result "argument from alone at /usr/lib/centreon/plugins/centreon_oracle.pl line 642"

My SQL code : 
select count(*) from dba_autotask_job_history where WINDOW_START_TIME=(select MAX(WINDOW_START_TIME) from dba_autotask_job_history where CLIENT_NAME='auto optimizer stats collection') and CLIENT_NAME='auto optimizer stats collection' and (job_status != 'SUCCEEDED' or job_error != 0);

Here is what I find in line 642 : 
warn "argument $ARGV[$i] alone" if ($warn_message == 1 && $i != 0 && defined($ARGV[$i]));

The command executed : 
/usr/lib/centreon/plugins/centreon_oracle.pl --plugin=database::oracle::plugin --hostname='----' --port='---' --sid='---' --servicename='' --username='----' --password='----'  --mode='sql' --sql-statement='select count(*) from dba_autotask_job_history where WINDOW_START_TIME=(select MAX(WINDOW_START_TIME) from dba_autotask_job_history where CLIENT_NAME='auto optimizer stats collection') and CLIENT_NAME='auto optimizer stats collection' and (job_status != 'SUCCEEDED' or job_error != 0)' --warning='' --critical=''

![centreon unknown](https://user-images.githubusercontent.com/71763233/94011596-e9acc080-fda7-11ea-88ec-e09cf5135dab.JPG)

Could you help please ?

**Comment by garnier-quentin** [comment]
Try that command:
```
/usr/lib/centreon/plugins/centreon_oracle.pl --plugin=database::oracle::plugin --hostname='----' --port='---' --sid='---' --servicename='' --username='----' --password='----' --mode='sql' --sql-statement="select count(*) from dba_autotask_job_history where WINDOW_START_TIME=(select MAX(WINDOW_START_TIME) from dba_autotask_job_history where CLIENT_NAME='auto optimizer stats collection') and CLIENT_NAME='auto optimizer stats collection' and (job_status != 'SUCCEEDED' or job_error != 0)" --warning='' --critical=''
```

**Comment by khalidbounoun** [comment]
Now I have this error : 
UNKNOWN: Cannot execute query: ORA-00942: table or view does not exist (DBD ERROR: error possibly near <*> indicator at char 21 in 'select count(*) from <*>dba_autotask_job_history where WINDOW_START_TIME=(select MAX(WINDOW_START_TIME) from dba_autotask_job_history where CLIENT_NAME='auto optimizer stats collection') and CLIENT_NAME='auto optimizer stats collection' and (job_status != 'SUCCEEDED' or job_error != 0)')

**Comment by garnier-quentin** [comment]
have you tried that request on your oracle server ? The error seems "ok".

**Comment by khalidbounoun** [comment]
@garnier-quentin  Thank you for your help, the second error is because of the rights of the account used.
I replaced (') by (") on the terminal, but the web platform automatically puts ('), how to change it ?

**Comment by garnier-quentin** [comment]
Create your own command and you could set double quote to protect

**Comment by khalidbounoun** [comment]
Thanks a lot, my problem is solved.
