### ISSUE TITLE
New MIB file for Sophos XG v18 (Cyberoam plugins)

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#2226]
Sophos XG v18 was released with a new MIB file here:
https://docs.sophos.com/nsg/sophos-firewall/MIB/SOPHOS-XG-MIB.zip

Plugins concerned:
https://github.com/centreon/centreon-plugins/tree/master/network/cyberoam

I will provide a snmpwalk soon if needed

**Comment by garnier-quentin** [comment]
yes (you can sent it by email)

**Comment by garnier-quentin** [comment]
Ok i have a first patch to manage current modes. Could you test it and tell me if it's working ? 'cpu' won't work. They haven't mapped the cpu OID in v18.
