### ISSUE TITLE
Cisco WAP150 plugin

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-plugins#2227]
Hi,

I'm looking for a plugin to monitor a Cisco WAP150 (WiFi AP) device but I can't find a dedicated one.
With network::cisco::standard::snmp::plugin, these modes are working out of the box:
- arp
- environment (but returning 0 components, so useless)
- interfaces
- list-interfaces
- list-spanning-trees
- spanning-tree
- uptime

That's a good start but it would be great if we can monitor stuffs like CPU, RAM and connected users!

I've attached snmpwalk and MIBs for firmware 1.0.0.16 (I can't find an up to date MIB for actual firmware 1.1.2.4, I hope they are not outdated)

[WAP150.txt](https://github.com/centreon/centreon-plugins/files/5269181/WAP150.txt)
[wap150_wap361-mibs-20151203.zip](https://github.com/centreon/centreon-plugins/files/5269187/wap150_wap361-mibs-20151203.zip)

**Comment by garnier-quentin** [comment]
if there is some dedicated mode, maybe i could create a dedicated plugin yes

**Comment by garnier-quentin** [comment]
the snmpwalk is not good. Could you provide it using that command ?
```
snmpwalk -ObentU -v 2 -c public IP .1 > cisco_wap.snmpwalk
```

**Comment by Cool34000** [comment]
Hi Quentin,

The snmpwalk ended with:
> Timeout: No Response from x.x.x.x

However there is some output.
If you need a specific OID, just ask for it!
[cisco_wap.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/6122920/cisco_wap.snmpwalk.txt)

Thanks.

**Comment by garnier-quentin** [comment]
Could you also provide snmpwalk for following branches ?
.1.3.6.1.4.1.9.6.1.104.1.23
.1.3.6.1.4.1.9.6.1.104.1.31
.1.3.6.1.4.1.9.6.1.104.1.120

I can do following modes:
- cpu
- clients: number of clients associated total (and by radio-interfaces)
- interfaces
- memory
- virtual-access-points: total and status of each VAP

**Comment by Cool34000** [comment]
Hi Quentin,

That's great news!
Here's the OIDs you asked...

.1.3.6.1.4.1.9.6.1.104.1.120 is sending a timeout but with some data.

[OID .1.3.6.1.4.1.9.6.1.104.1.23.txt](https://github.com/centreon/centreon-plugins/files/6131688/OID.1.3.6.1.4.1.9.6.1.104.1.23.txt)
[OID .1.3.6.1.4.1.9.6.1.104.1.31.txt](https://github.com/centreon/centreon-plugins/files/6131689/OID.1.3.6.1.4.1.9.6.1.104.1.31.txt)
[OID .1.3.6.1.4.1.9.6.1.104.1.120.txt](https://github.com/centreon/centreon-plugins/files/6131692/OID.1.3.6.1.4.1.9.6.1.104.1.120.txt)

Thanks for your time

**Comment by garnier-quentin** [comment]
You can test with last version the plugin: ```--plugin=network::cisco::wap::snmp::plugin```
