### ISSUE TITLE
How can I monitor vols usage on eSeries Netapp - Santricity?

### ISSUE THREAD

**Issue by vcegarra** [centreon/centreon-plugins#2228]
Please follow information shown below according your issue. For all issues, thank you to describe it in English.
If some informations are confidentials, please send it directly by email to qgarnier@centreon.com and sbomm@centreon.com

## Question

Hi all,

first of all thanks for developing this script.

I wanted to ask if it is currently possible to monitor the volume usage of a Netapp eSeries storage with Santricity.

It seems that the current script only allows you to monitor four metrics on a volume:

volume.io.read.usage.bytespersecond
volume.io.write.usage.bytespersecond
volume.io.read.usage.iops
volume.io.write.usage.iops

I am using the following script:

centreon-plugins / storage / netapp / santricity / restapi / mode / storagevolumes.pm

Thank you very much to all.
Regards.

**Comment by garnier-quentin** [comment]
Yes we could but there is no such informations (maybe because the netapp doesn't know how the volume is filled ?)
But if you have the curl response and attributes we could add it

**Comment by vcegarra** [comment]
Hello,

Thank you very much for answering.

I've been looking at the Netapp Santrictiy Webproxy documentation.

In this link, the definitions that could be more appropriate appear:

https://library.netapp.com/ecmdocs/ECMLP2839901/html/v2.html#_volume

For example, the label "capacity" appears.

Are we talking about this information being enough to check the free / occupied or total space?

Thanks again!

**Comment by garnier-quentin** [comment]
Capacity is not enough. It's only a total

**Comment by garnier-quentin** [comment]
I think we could have that information for storage pools maybe. Could you provide a json api example result for following endpoint (need to replace) ?
```/devmgr/v2/storage-systems/{system-id}/storage-pools/{id}```

**Comment by vcegarra** [comment]
> I think we could have that information for storage pools maybe. Could you provide a json api example result for following endpoint (need to replace) ?
> `/devmgr/v2/storage-systems/{system-id}/storage-pools/{id}`

Hi!

I am attaching in this message the example output of our SANTRICITY storage.

Thank you!
a greeting.

{
  "sequenceNum": 1,
  "offline": false,
  "raidLevel": "raidDiskPool",
  "worldWideName": "6D039EA0001301770000015F5E4E193F",
  "volumeGroupRef": "040000006D039EA0001301770000015F5E4E193F",
  "reserved1": "000000000000000000000000",
  "reserved2": "",
  "trayLossProtection": false,
  "label": "pool_01",
  "state": "complete",
  "spindleSpeedMatch": true,
  "spindleSpeed": 7200,
  "isInaccessible": false,
  "securityType": "none",
  "drawerLossProtection": true,
  "protectionInformationCapable": false,
  "protectionInformationCapabilities": {
    "protectionInformationCapable": true,
    "protectionType": "type2Protection"
  },
  "volumeGroupData": {
    "type": "diskPool",
    "diskPoolData": {
      "reconstructionReservedDriveCount": 3,
      "reconstructionReservedAmt": "35245038501888",
      "reconstructionReservedDriveCountCurrent": 10,
      "poolUtilizationWarningThreshold": 70,
      "poolUtilizationCriticalThreshold": 85,
      "poolUtilizationState": "utilizationOptimal",
      "unusableCapacity": "0",
      "degradedReconstructPriority": "high",
      "criticalReconstructPriority": "highest",
      "backgroundOperationPriority": "low",
      "allocGranularity": "4294967296",
      "minimumDriveCount": 11
    }
  },
  "usage": "standard",
  "driveBlockFormat": "allEmulated",
  "reservedSpaceAllocated": true,
  "securityLevel": "none",
  "dulbeEnabled": false,
  "usedSpace": "266296562286592",
  "totalRaidedSpace": "533048391106560",
  "extents": [
    {
      "sectorOffset": "0",
      "rawCapacity": "266751828819968",
      "raidLevel": "raidDiskPool",
      "volumeGroupRef": "040000006D039EA0001301770000015F5E4E193F",
      "freeExtentRef": "030100006D039EA0001301770000015F5E4E193F",
      "reserved1": "000000000000000000000000",
      "reserved2": ""
    }
  ],
  "largestFreeExtentSize": "266751828819968",
  "raidStatus": "optimal",
  "freeSpace": "266751828819968",
  "drivePhysicalType": "sas",
  "driveMediaType": "hdd",
  "normalizedSpindleSpeed": "spindleSpeed7200",
  "id": "040000006D039EA0001301770000015F5E4E193F",
  "diskPool": true,
  "name": "pool_01"
}

**Comment by garnier-quentin** [comment]
I think we could use following values:
```
 "usedSpace":"266296562286592",
 "totalRaidedSpace":"533048391106560",
 "freeSpace":"266751828819968",
```

**Comment by vcegarra** [comment]
thanks!

I stay tuned in case you need me to provide you with some additional example information.

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by vcegarra** [comment]
> Could you test with last version ?

Hello,

I have tried after the changes made and in storage-pools mode it works perfectly since I can see the storage value (free, used, percentage).

I attach the output of the query:

_./centreon_plugins.pl --plugin storage::netapp::santricity::restapi::plugin **--mode storage-pools** --hostname xx.xx.xx.xx --api-username= ... --api-password ...
OK: storage system 'santricity' pool 'pool_01' state: complete [raid status: optimal], space usage total: 484.80 TB used: 242.20 TB (49.96%) free: 242.61 TB (50.04%) | 'santricity~pool_01#pool.space.usage.bytes'=266296562286592B;;;0;533048391106560 'santricity~pool_01#pool.space.free.bytes'=266751828819968B;;;0;533048391106560 santricity~pool_01#pool.space.usage.percentage'=49.96%;;;0;100_

Could the same modifications be applied for storage-volumes mode?

The interesting thing about the storage-volumes mode is to control the capacity of each of the defined storage volumes.

If you think it is viable, let me know and I can open another query for improvement and provide you with the data you will need as before.

Thanks and happy new year!

**Comment by garnier-quentin** [comment]
thanks for the feedback! Happy new year!
