### ISSUE TITLE
Let's add a --list-counters option ?

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2229]
Hi,

What about a `--list-counters` option in counters template ?
I always go through code itself to have the proper counters list, which is not really convenient :)

Would also prevent from maintaining the list in the help of the various modes.

Thank you for your feedback 👍

**Comment by garnier-quentin** [comment]
You want to display it with --list-counters option ? and no more in help ? Maybe...

**Comment by UrBnW** [comment]
Yes, simply advising in the help to run `--list-counters` to get the full list.

**Comment by UrBnW** [comment]
Especially given the fact that these counters can be used at several places, `--critical-*` / `--warning-*` / `--unknown-*`, but also in `--filter-counters`...

**Comment by garnier-quentin** [comment]
We should add a description also in the code (can be useful)

**Comment by UrBnW** [comment]
Yes, good idea.
`--list-counters` could also perhaps display the counter type (diff/count, current etc...).

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md)).

Thank you for your understanding.
