### ISSUE TITLE
[network::extreme::snmp::plugin] mode cpu

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#223]
Hello,

Since the last clone i've just done, this mode does not work anymore :
Here the options :
--plugin=network::extreme::snmp::plugin --mode=cpu --warning-total=95 --critical-total=99 --filter-perfdata='^(cpu_total|cpu_1min)$' 

Here the result :
Argument "n/a" isn't numeric in sprintf at /logiciel/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 159.

**Comment by garnier-quentin** [comment]
Could you do a snmpwalk of following oids:
.1.3.6.1.4.1.1916.1.32.1.4.1
.1.3.6.1.4.1.1916.1.32.1.2

Thanks

**Comment by ritouret** [comment]
.1.3.6.1.4.1.1916.1.32.1.4.1 :
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemSlotId.1 = Gauge32: 1
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemSlotId.2 = Gauge32: 2
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization5secs.1 = STRING: "n/a"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization5secs.2 = STRING: "n/a"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization10secs.1 = STRING: "n/a"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization10secs.2 = STRING: "n/a"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization30secs.1 = STRING: "3.1"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization30secs.2 = STRING: "2.8"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization1min.1 = STRING: "2.9"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization1min.2 = STRING: "2.7"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization5mins.1 = STRING: "2.8"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization5mins.2 = STRING: "2.7"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization30mins.1 = STRING: "2.7"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization30mins.2 = STRING: "2.7"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization1hour.1 = STRING: "2.7"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemUtilization1hour.2 = STRING: "2.7"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemMaxUtilization.1 = STRING: "37.7"
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorSystemMaxUtilization.2 = STRING: "17.0"


.1.3.6.1.4.1.1916.1.32.1.2 :
EXTREME-SOFTWARE-MONITOR-MIB::extremeCpuMonitorTotalUtilization.0 = INTEGER: 9

**Comment by garnier-quentin** [comment]
I see the problem. I fix it tomorrow.

**Comment by ritouret** [comment]
Ok, i'll disabled these service in production until tomorrow.
Thanks.

**Comment by garnier-quentin** [comment]
Could you test it please ?

**Comment by ritouret** [comment]
Pretty good. Thank you Quentin.

OK: Total CPU Usage : 15.00 % - All CPU usages are ok | 'cpu_total'=15.00%;0:95;0:99;0;100
CPU '1' Usage 5secs : skipped (no value(s)), 10secs : skipped (no value(s)), 30 seconds : 3.10 %, 1 minute : 3.20 %, 5 minutes : 2.80 %
CPU '2' Usage 5secs : skipped (no value(s)), 10secs : skipped (no value(s)), 30 seconds : 2.00 %, 1 minute : 2.40 %, 5 minutes : 2.70 %
