### ISSUE TITLE
Strange check_icmp behaviour

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-plugins#2230]
Hi,

I'm facing a strange problem with **_check_icmp_** on a network: some network devices are not responding while a simple ping shows that these devices are online.
This is what I get with **_check_icmp_**:
```
[root@poller ~]# /usr/lib64/nagios/plugins/check_icmp -H 10.54.20.129
CRITICAL - 10.54.20.129: rta nan, lost 100%|rta=0,000ms;200,000;500,000;0; pl=100%;40;80;0;100 rtmax=0,000ms;;;; rtmin=0,000ms;;;;
```
And what I get with **_ping_**:
```
[root@poller ~]# ping 10.54.20.129
PING 10.54.20.129 (10.54.20.129) 56(84) bytes of data.
64 bytes from 10.54.20.129: icmp_seq=1 ttl=255 time=0.511 ms
64 bytes from 10.54.20.129: icmp_seq=2 ttl=255 time=0.526 ms
64 bytes from 10.54.20.129: icmp_seq=3 ttl=255 time=0.507 ms
64 bytes from 10.54.20.129: icmp_seq=4 ttl=255 time=0.526 ms
^C
--- 10.54.20.129 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3000ms
rtt min/avg/max/mdev = 0.507/0.517/0.526/0.024 ms

```
All SNMP probes are working: I'm only getting a "DOWN status" on the check_icmp!
![image](https://user-images.githubusercontent.com/17827397/94358206-a3a17680-009f-11eb-949f-d4aa82452873.png)

Any idea on what could be responsible of this behaviour?

**Comment by Cool34000** [comment]
I played with packet size (option -b) and it works better when using lower values:
```
[root@poller ~]# /usr/lib64/nagios/plugins/check_icmp -H 10.54.20.129 -b 52
OK - 10.54.20.129 rta 0,416ms lost 0%|rta=0,416ms;200,000;500,000;0; pl=0%;40;80;0;100 rtmax=0,572ms;;;; rtmin=0,368ms;;;;
```
I'll take a look on the switch to see if there is a reason for that...

**Comment by garnier-quentin** [comment]
check_icmp is a monitoring plugin: https://www.monitoring-plugins.org/. I cannot help you here
