### ISSUE TITLE
[network::nortel::standard::snmp::mode::cpu] - Unknown option: warning

### ISSUE THREAD

**Issue by watchix** [centreon/centreon-plugins#2233]
Hi,

I'm having an issue with de CPU return check, seems warnings return is false.
My Switch is a Nortel 5510-48T 
FW:6.0.0.6   SW:v6.0.0.004

Centreon : v2.8.32

"Unknown option: warning at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67."

Here is the command from CLI :
`/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::nortel::standard::snmp::plugin --mode=cpu --hostname=172.xx.xx.xx`

`OK: All CPU usages are ok | 'cpu_1min_3.10.0'=10.00%;;;0;100 'cpu_10min_3.10.0'=20.00%;;;0;100 'cpu_1h_3.10.0'=16.00%;;;0;100 'cpu_1min_3.20.0'=11.00%;;;0;100 'cpu_10min_3.20.0'=16.00%;;;0;100 'cpu_1h_3.20.0'=16.00%;;;0;100`

Some screens :
[https://i.ibb.co/6DVbpxj/Nortel-CPU-Error.jpg](url)

Regards,

**Comment by garnier-quentin** [comment]
I think there is some options missing. Check the help for the good options.

**Comment by watchix** [comment]
Thx for your reply @garnier-quentin .

`[centreon@xxxx root]$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::nortel::standard::snmp::plugin --mode=cpu --hostname='172.xx.xx.xx' --snmp-port='161' --snmp-community='public' --snmp-version='1' --verbose --warning=''`

`Unknown option: warning at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.`


`[centreon@xxxx root]$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::nortel::standard::snmp::plugin --mode=cpu --hostname='172.xx.xx.xx' --snmp-port='161' --snmp-community='public' --snmp-version='1' --verbose --critical=''`

`Unknown option: critical at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.`

The option "--filter-counters" is working.
But not "--warning" and "--critical"
When i'm looking in the cpu.pm file (line 183) there is "--warning-*" and "--critical-*" options.
What does it means ?

[https://github.com/centreon/centreon-plugins/blob/master/network/nortel/standard/snmp/mode/cpu.pm](url)

Regards,

**Comment by garnier-quentin** [comment]
For example: ```--warning-5m='90' --critical-5m='95' --warning-10m='80' ...```

**Comment by watchix** [comment]
Ohhhhh.. Yes :-)
Sorry for this mistake. I think you can update cpu.pm with your example above.

Regards,
