### ISSUE TITLE
Fortinet FortiWLC - please add support

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2236]
It should be great to have support for Fortinet Wireless Lan Controller.

I could send you a SNMP walk if you need.

**Comment by garnier-quentin** [comment]
I need the mib file and snmpwalk yes.

**Comment by joschi99** [comment]
Attached you will find the mibs and a snmpwalk. Please remove snmpwalk from github because could contain customer datas.

[mibs.tar.gz](https://github.com/centreon/centreon-plugins/files/5327361/mibs.tar.gz)
[FortiWLC-snmpwalk.zip](https://github.com/centreon/centreon-plugins/files/5327363/FortiWLC-snmpwalk.zip)

Thanks

**Comment by garnier-quentin** [comment]
I have looked and we can do a plugin. It's a meru network system. So i will add: network/meru/snmp/plugin.pm with:
* ap
* system (cpu, memory, alarms, traffic)
* interfaces

**Comment by garnier-quentin** [comment]
Add a new plugin: network/meru/snmp/plugin.pm

**Comment by joschi99** [comment]
Have done some test:
- interfaces: UNKNOWN: Can't construct cache...
- list-interfaces: UNKNOWN: Can't get interfaces...

The other modes seems working, but it should be nice to check the master/slave or cluster status. Do you think it's possible?

**Comment by garnier-quentin** [comment]
You need to add following options for interfaces: ```--oid-display=ifdesc --oid-filter=ifdesc```
I don't find information about cluster status (only trap notification).
