### ISSUE TITLE
'storage::netapp::ontap::snmp::plugin' / aggregatestate mode returns uninitialized value statefile

### ISSUE THREAD

**Issue by se-baj** [centreon/centreon-plugins#2237]
Hello,

I got following output when using netapp snmp plugin :

## Bug/Question

> Command line:
>`'/usr/bin/perl' './centreon_plugins.pl' '--hostname' 'xx.xx.xx.xx' '--mode' 'aggregatestate' '--plugin' 'storage::netapp::ontap::snmp::plugin' '--snmp-community' 'xx' '--snmp-version' '2'`

> Output
> ```
>Use of uninitialized value in concatenation (.) or string at .../centreon/plugins/statefile.pm line 263.
>print() on closed filehandle FILE at .../centreon/plugins/statefile.pm line 267.
>OK: All aggregates are ok |
> ```

My question is, do we need statefile-dir and statefile for this mode ? if not, could we set option statefile=>0 (aggregatestate.pm/line92) instead of 1, it seems to fix that issue.

Thanks for your help.
Regards
sebastien.

**Comment by garnier-quentin** [comment]
There are no need of statefile. It's a bug.

**Comment by garnier-quentin** [comment]
It's fixed. thanks for the feedback!

**Comment by se-baj** [comment]
Great, you're welcome. Thanks you
Regards
