### ISSUE TITLE
[os::linux::snmp::plugin] mode inodes - add filter-storage-type option

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#224]
Would you add the --filter-storage-type for the inodes mode like you did for storage mode on os::linux::snmp::plugin ?

Thank you.

**Comment by garnier-quentin** [comment]
I can't add the following option. There is no link between .1.3.6.1.2.1.25.3.9 and .1.3.6.1.4.1.2021.9.1.2.

**Comment by ritouret** [comment]
It should be UCD-SNMP-MIB::dskDevice (.1.3.6.1.4.1.2021.9.1.3) instead of HOST-RESOURCES-MIB::hrFSTypes. Filter would be easier like --filter-disk-device=^(/dev/mapper/rootvg.*)$

**Comment by garnier-quentin** [comment]
So you don't want to filter by type. But add the capabilities to filter by partition name. You're right. I can do that.

**Comment by ritouret** [comment]
Just tested, the associated service template is easier to configure.
Thank you Quentin.

**Comment by garnier-quentin** [comment]
You're welcome ;)
