### ISSUE TITLE
apps::activedirectory::local::plugin, mode backlog: difficult to pass aguments if RG or RF contain spaces 

### ISSUE THREAD

**Issue by acelor** [centreon/centreon-plugins#2242]
Hi Quentin,

would you please add a sanity check for the arguments? I try to use the plugin to monitor the DFSR backlog for the SYSVOL_DFSR replica, but passing the quotes via NRPE is difficult and error prone, i.e if you try to call 
`centreon_plugins.exe" --plugin apps::activedirectory::local::plugin --mode dfsr-backlog   --sending-member="MyDomainCtrlr" --replication-group="Domain System Volume" --replicated-folder="Sysvol Share" --warning-backlog="101" --critical-backlog="131"` will result in an error because it will pass the args to dfsrdiag unquoted:
`dfsrdiag backlog /SendingMember:MyDomainCtrlr /RGName:Domain System Volume /RFName:Sysvol Share`

Workaround is to pass the args like `"\"Domain System Volume\""`, but this adds another set of quotes to the already existing stuff, as usually this is passed using NRPE

Thanks in advance! 

PS: Please also add the optional parameter --receiving_member. Usually, the Centreon NSClient runs as LOCAL SYSTEM account, which in the default configuration does not have access permissions to WMI service on remote DC. Runnig nsclient with other/higher privileged account on a DC is a potential security issue. A better approach would be running it on a Windows monitoring proxy, but in this case you need to provide dfsrdiag both "ends" of the replication

**Comment by UrBnW** [comment]
As a working example, I use the following writing, without problem.
Look at spaces in the last given argument :
```
/usr/lib/centreon/plugins/centreon_protocol_nrpe.pl
--plugin=apps::protocols::nrpe::plugin
--custommode=nsclient
--hostname=192.168.192.1
--port=8443
--username=username
--password=password
--new-api
--ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'
--mode=query
--command=check_centreon_plugins
--arg='--plugin=os::windows::local::plugin'
--arg='--mode=pending-reboot'
--arg='--warning-status="%{WindowsUpdate} !~ /^false$/ || %{PendComputerRename} !~ /^false$/"'
```

**Comment by acelor** [comment]
> As a working example, I use the following writing, without problem.
> Look at spaces in the last given argument :
> 
> ```
> /usr/lib/centreon/plugins/centreon_protocol_nrpe.pl
> --plugin=apps::protocols::nrpe::plugin
> --custommode=nsclient
> --hostname=192.168.192.1
> --port=8443
> --username=username
> --password=password
> --new-api
> --ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'
> --mode=query
> --command=check_centreon_plugins
> --arg='--plugin=os::windows::local::plugin'
> --arg='--mode=pending-reboot'
> --arg='--warning-status="%{WindowsUpdate} !~ /^false$/ || %{PendComputerRename} !~ /^false$/"'
> ```

**Comment by acelor** [comment]
Sorry, accidentally hit the wrong button. @UrBnW : Thanks for your advise. We use centreon-nrpe frequently, it works fine. The trouble is that yu have to quote 3 times: 1x for NRPE, 1x for centreon-plugins.exe (commercial version) and 1x for dfsrdiag in case of this specific plugin. If you do it wrong, you get messed up help output from dfsrdiag and have to use procmon or similar to figure out how it was executed. This is error-prone, therefor the request to the devs.

**Comment by garnier-quentin** [comment]
Ok. I see. I will enhance it

**Comment by garnier-quentin** [comment]
I have done the patch. Could you test it ?
