### ISSUE TITLE
Plugin and pack RPM for Emerson PDU not in sync

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-plugins#2244]
## Bug/Question

Pack RPM centreon-pack-hardware-pdu-emerson-snmp-3.2.0-1.el6.noarch is not in sync with plugin RPM centreon-plugin-Hardware-Pdu-Emerson-Snmp-20201006-142255.el6.noarch

The pack template command is calling **rb-usage** mode which has been deprecated and replaced to **receptacles**

Sincerely, 
Marcel

**Comment by garnier-quentin** [comment]
el6 pack are not built anymore i think. that's why

**Comment by hecko** [comment]
Since I understand the overhead, the issue is that both packages are el6. I would suspect either both not being supported or both being supported. The current situation makes the support of the el6 builds ambiguous. One is, and the other one is not updated.

**Comment by garnier-quentin** [comment]
I understand. But you can update the command on your own.

**Comment by hecko** [comment]
@garnier-quentin probably better remove centreon-plugin-Hardware-Pdu-Emerson-Snmp RPN alltogether then? No point in having the plugin pack installed?! Dont get me wrong, Im simply pointing out that the RPM release process is not synced properly for the RPMs since the packages break the product.

**Comment by garnier-quentin** [comment]
Maybe we should stop plugin rpm release for el6 also. you're right

**Comment by hecko** [comment]
> Maybe we should stop plugin rpm release for el6 also. you're right

In the best-case scenario the pack RPM would be rolled back to the latest working version. Or plugin rpm backported to rh6. 
Thanks for the feedback!
