### ISSUE TITLE
Warning-session-rate and critical-session-rate argument of the fortigate plugin, vdom-usage mode : Unknown option

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#2257]
Hello,

Running vdom-usage mode on the fortinet::fortigate plugin gives me the error :

**Unknown option: critical-session-rate at /usr/lib/centreon/plugins//centreon_fortinet_fortigate.pl line 3154.**

By removing the options:
--warning-session-rate = '' --critical-session-rate = ''
The script works fine.

I got the error while updating from centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp-**20200602-094050**.el7.centos.noarch to centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp- **20201006-142255**.el7.centos.noarch

Complete command line:
/usr/lib/centreon/plugins//centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::snmp::plugin --mode=vdom-usage --hostname=X.X.X.X --snmp-version='3' --snmp-username=User --authprotocol=SHA --authpassphrase='XXXXXXXXXXXXXXXXXXXXXX' --privprotocol=AES --privpassphrase='XXXXXXXXXXXXXXXXXXXXXX' --snmp-autoreduce --filter-vdomain='' --warning-cpu-utilization='80' --critical-cpu-utilization='90' --warning-status='' --critical-status='%{ha_state} !~ /^master|backup$/i' --warning-sessions-active='' --critical-sessions-active='' --warning-traffic-in='' --critical-traffic-in='' --warning-traffic-out='' --critical-traffic-out='' --warning-memory-usage-prct='80' --critical-memory-usage-prct='90' --warning-license-usage='' --critical-license-usage='' --warning-license-free='' --critical-license-free='' --warning-license-usage-prct='' --critical-license-usage-prct='' --verbose --warning-session-rate='' --critical-session-rate=''
**Unknown option: warning-session-rate at /usr/lib/centreon/plugins//centreon_fortinet_fortigate.pl line 3154.**

Centreon 19.10.15 (commit 327ff6d32)

Best Regards.

**Comment by gagzou** [comment]
Sorry, centreon-web is already up to date.

rpm -qa | grep centreon-web
centreon-web-19.10.15-2.el7.centos.noarch

yum update
Modules complémentaires chargés : fastestmirror
Determining fastest mirrors
an-centos7                                                                                                                                                                                                         | 3.6 kB  00:00:00
an-centos7-updates                                                                                                                                                                                                 | 2.9 kB  00:00:00
an-epel7                                                                                                                                                                                                           | 4.7 kB  00:00:00
centreon-plugin-packs-stable                                                                                                                                                                                       | 2.9 kB  00:00:00
centreon-plugin-packs-stable-noarch                                                                                                                                                                                | 2.9 kB  00:00:00
centreon-stable                                                                                                                                                                                                    | 2.9 kB  00:00:00
centreon-stable-noarch                                                                                                                                                                                             | 2.9 kB  00:00:00
(1/10): an-epel7/updateinfo                                                                                                                                                                                        | 1.0 MB  00:00:00
(2/10): an-centos7/group_gz                                                                                                                                                                                        | 165 kB  00:00:00
(3/10): an-epel7/primary_db                                                                                                                                                                                        | 6.9 MB  00:00:00
(4/10): an-centos7/primary_db                                                                                                                                                                                      | 6.0 MB  00:00:00
(5/10): centreon-plugin-packs-stable/x86_64/primary_db                                                                                                                                                             | 1.1 kB  00:00:00
(6/10): an-centos7-updates/primary_db                                                                                                                                                                              | 7.6 MB  00:00:00
(7/10): centreon-stable/x86_64/primary_db                                                                                                                                                                          | 111 kB  00:00:00
(8/10): centreon-stable-noarch/primary_db                                                                                                                                                                          | 771 kB  00:00:00
(9/10): centreon-plugin-packs-stable-noarch/primary_db                                                                                                                                                             | 142 kB  00:00:00
(10/10): an-epel7/group_gz                                                                                                                                                                                         |  95 kB  00:00:01
No packages marked for update

**Comment by garnier-quentin** [comment]
Have you update the pack in centreon web ?

**Comment by gagzou** [comment]
Yes I had already updated the pack in centreon web (3.4.2 for "Fortinet Fortigate").

**Comment by garnier-quentin** [comment]
Indeed the pack had never been released. We have done an update. If you have access to rpm repository, you can update it with unstable repository. Otherwise, it will be available for the next pack release (next month) (you can create a new command, fix it and attach to custom service template in meantime).

**Comment by joschi99** [comment]
Done a test with latest centreon plugins downloaded from github today and still same error:
`Unknown option: warning-session-rate at /tmp/centreon-plugins-master/centreon/plugins/alternative/Getopt.pm line 67.`
