### ISSUE TITLE
Unknown option for App-IIS-ApplicationPools-Auto-NRPE

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#2258]
Hi,

I have the following error :
Unknown option: filter-name at C:\Windows\TEMP\par-575355532d53525624\cache-564d2eb31f38666ed5271a3ff653ec185fb4375a\inc\lib/centreon/plugins/alternative/Getopt.pm line 67.

The error comes from the command of the template service 'App-IIS-ApplicationPools-Auto-NRPE'.
It uses 'App-IIS-NRPE-ApplicationPool-State' instead of 'App-IIS-NRPE-ApplicationPool-State-AUTO'.

Centreon 19.10.15 (up to date)
centreon-web-19.10.15-2.el7.centos.noarch (up to date)
Plugin pack IIS 3.2.4 (up to date)

Error appeared since update 19.10.14 to 19.10.15

Best Regards.

**Comment by garnier-quentin** [comment]
Have you updated your centreon_plugins.exe on your target Windows ?

**Comment by gagzou** [comment]
Same result with the last centreon_plugins.exe on my target Windows.

**Comment by garnier-quentin** [comment]
Where do you download centreon_plugins.exe ?

**Comment by gagzou** [comment]
Directly from centreon web : 
https://download.centreon.com/?action=product&product=agent-nsclient&version=0.51 etc......

**Comment by garnier-quentin** [comment]
Could you try that plugin (built today) ? https://share.centreon.com/public/424beb

**Comment by gagzou** [comment]
Thanks, it's good for me !

**Comment by garnier-quentin** [comment]
Thanks for the feedback. i close it!
