### ISSUE TITLE
Sonde TEMPerHUM

### ISSUE THREAD

**Issue by hdzpeter** [centreon/centreon-plugins#226]
Bonjour

j'utlise des sondes TEMPerHUM afin de prendre la temperature et l'humidité de ma salle serveur, ces sondes sont conecté sur le PC de supervison dans le quel est installé CES.

je voudrait recuperer les resultat de ces sonde a partir de CES les afficher sous forme de graph et envoyer des alertes
`
Aujourd'hui j'ai une tache qui s'execute toutes les 3mn et qui enregistre les valeur dans un fichier TXT

ci desssous la commande et le resultat que cela envoi

/opt/PCsensor/TEMPered/utils/./tempered

/dev/hidraw2 0: temperature 30.10 °C, relative humidity 39.2%, dew point 14.7 °C
/dev/hidraw4 0: temperature 30.46 °C, relative humidity 38.0%, dew point 14.5 °C

Merci d'avance

**Comment by garnier-quentin** [comment]
We cannot get the value directly ? In snmp ?

**Comment by hdzpeter** [comment]
je ne sais pas, comment verifer?

**Comment by garnier-quentin** [comment]
First, could you give the model of your probe ?

**Comment by hdzpeter** [comment]
TEMPERHUM1V1.2

**Comment by hdzpeter** [comment]
Up

**Comment by garnier-quentin** [comment]
I think we can get the value directly like you're doing in the cron each 3 minutes (no need for the cron).

**Comment by hdzpeter** [comment]
Justement actuelement , j'ai crée un tache dans le cron qui s'execute toutes les 3mn et qui enregistre les valeurs dans un fichier txt. Comment recuperer cette information et la transmettre a centreon pour qu'il affiche sous forme de graphique

**Comment by hdzpeter** [comment]
Up

**Comment by Sims24** [comment]
Hi,

There is actually three solutions :

- If you want us to take some time to developp this plugin, we can add the plugin/enhancement label but we do not guarantee this one as a top priority, and we may need to access to your server to test the plugin.

- If you're interested in learning how to developp a plugin answering your needs may be you can start reading https://documentation-fr.centreon.com/docs/centreon-plugins/en/latest/developer/index.html. As Quentin said, your engine will execute the plugin every five minutes then you probably can do it all in one without cron. Informations to handle threshold and mangage perfdata are in the link above. There is some example in the repository actually.

- If you're in hurry (and it seems that you are) may be take a look to already existing projet like https://github.com/ovido/check_temper/wiki to monitor this asap waiting for us to developp a centreon_plugins mode for these sensors.

Thanks for all informations given,

**Comment by hdzpeter** [comment]
Merci a vous  pour ces informations , je vais regarder la 3eme Option 

Bien a vous

**Comment by Sims24** [comment]
Hi @hdzpeter, 

If you want you can test our centreon-plugin version of the check, code is available here : 

https://github.com/Sims24/centreon-plugins/tree/master/hardware/sensors

Please let us know if it works for you and fit your need, find below some sample check execution : 

With drive filter :

perl centreon_plugins.pl --plugin hardware::sensors::temperhum::local::plugin --mode environment --filter-drive raw4 --command-path /opt/PCsensor/TEMPered/utils --command tempered

OK: '/dev/hidraw4' Humidity: 38.00% - '/dev/hidraw4' Temperature: 30.46 C - '/dev/hidraw4' Dew Point : 14.50 C - '/dev/hidraw4' Delta (Temp - Dew) : 15.96 C | 'humidity'=38.00%;;;0; 'temperature'=30.46C;;;0; 'dew_point'=14.50C;;;0; 'delta'=15.96C;;;0;
'/dev/hidraw4' Humidity: 38.00%
'/dev/hidraw4' Temperature: 30.46 C
'/dev/hidraw4' Dew Point : 14.50 C
'/dev/hidraw4' Delta (Temp - Dew) : 15.96 C

or globally :

perl centreon_plugins.pl --plugin hardware::sensors::temperhum::local::plugin --mode environment OK: All measures are OK | 'humidity_/dev/hidraw2'=39.20%;;;0; 'temperature_/dev/hidraw2'=30.10C;;;0; 'dew_point_/dev/hidraw2'=14.70C;;;0; 'delta_/dev/hidraw2'=15.40C;10:;;0; 'humidity_/dev/hidraw4'=38.00%;;;0; 'temperature_/dev/hidraw4'=30.46C;;;0; 'dew_point_/dev/hidraw4'=14.50C;;;0; 'delta_/dev/hidraw4'=15.96C;10:;;0;

Thanks
