### ISSUE TITLE
[network::paloalto::snmp::plugin] --mode=signatures - Odd number of elements in anonymous hash at

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2261]
Plugins 20201008

```
./centreon_plugins.pl  --hostname=x.x.x.x --snmp-community=public --snmp-version=2c --plugin=network::paloalto::snmp::plugin --mode=signatures
Odd number of elements in anonymous hash at /usr/lib/centreon/plugins/network/paloalto/snmp/mode/signatures.pm line 151.
OK:  |
```

snmpwalk
.1.3.6.1.4.1.25461.2.1.2.1.1.0 = STRING: "9.1.5"
.1.3.6.1.4.1.25461.2.1.2.1.2.0 = STRING: "1.0"
.1.3.6.1.4.1.25461.2.1.2.1.3.0 = STRING: "007057000059051"
.1.3.6.1.4.1.25461.2.1.2.1.4.0 = INTEGER: 7200
.1.3.6.1.4.1.25461.2.1.2.1.5.0 = INTEGER: 1
.1.3.6.1.4.1.25461.2.1.2.1.6.0 = STRING: "0.0.0"
.1.3.6.1.4.1.25461.2.1.2.1.7.0 = STRING: "8331-6352"
.1.3.6.1.4.1.25461.2.1.2.1.8.0 = STRING: "3505-4016"
.1.3.6.1.4.1.25461.2.1.2.1.9.0 = STRING: "8331-6352"
.1.3.6.1.4.1.25461.2.1.2.1.10.0 = STRING: "0000.00.00.000"
.1.3.6.1.4.1.25461.2.1.2.1.11.0 = STRING: "disabled"
.1.3.6.1.4.1.25461.2.1.2.1.12.0 = STRING: "unknown"
.1.3.6.1.4.1.25461.2.1.2.1.13.0 = STRING: "disabled"
.1.3.6.1.4.1.25461.2.1.2.1.14.0 = STRING: "paloaltonetworks"
.1.3.6.1.4.1.25461.2.1.2.1.15.0 = STRING: "5.2.2"
.1.3.6.1.4.1.25461.2.1.2.1.16.0 = STRING: "unknown"
.1.3.6.1.4.1.25461.2.1.2.1.17.0 = STRING: "0"
.1.3.6.1.4.1.25461.2.1.2.1.18.0 = STRING: "0"
.1.3.6.1.4.1.25461.2.1.2.1.19.1.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.2.0 = Counter64: 140097236
.1.3.6.1.4.1.25461.2.1.2.1.19.3.0 = Counter64: 962799
.1.3.6.1.4.1.25461.2.1.2.1.19.4.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.5.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.6.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.7.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.1.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.2.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.3.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.4.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.5.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.6.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.7.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.8.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.9.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.10.0 = Counter64: 1451613
.1.3.6.1.4.1.25461.2.1.2.1.19.8.11.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.12.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.13.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.14.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.15.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.16.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.17.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.18.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.19.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.20.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.21.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.22.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.23.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.24.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.25.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.26.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.27.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.28.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.29.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.30.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.31.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.32.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.33.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.34.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.35.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.36.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.37.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.38.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.39.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.40.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.41.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.42.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.43.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.44.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.45.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.46.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.47.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.48.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.49.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.50.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.51.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.52.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.53.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.54.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.55.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.56.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.57.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.58.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.59.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.60.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.61.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.62.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.63.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.64.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.65.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.66.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.67.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.68.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.69.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.70.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.71.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.72.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.73.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.74.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.75.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.8.76.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.9.1.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.9.2.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.9.3.0 = Counter64: 124
.1.3.6.1.4.1.25461.2.1.2.1.19.9.4.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.9.5.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.9.6.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.9.7.0 = Counter64: 2070
.1.3.6.1.4.1.25461.2.1.2.1.19.10.1.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.10.2.0 = Counter64: 9373
.1.3.6.1.4.1.25461.2.1.2.1.19.11.1.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.11.2.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.11.3.0 = Counter64: 1149
.1.3.6.1.4.1.25461.2.1.2.1.19.11.4.0 = Counter64: 9228
.1.3.6.1.4.1.25461.2.1.2.1.19.11.5.0 = Counter64: 2095
.1.3.6.1.4.1.25461.2.1.2.1.19.11.6.0 = Counter64: 17
.1.3.6.1.4.1.25461.2.1.2.1.19.11.7.0 = Counter64: 164431
.1.3.6.1.4.1.25461.2.1.2.1.19.11.8.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.1.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.2.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.3.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.4.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.5.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.6.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.7.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.8.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.19.12.9.0 = Counter64: 0
.1.3.6.1.4.1.25461.2.1.2.1.20.0 = STRING: "2020/10/16 01:05:48"
.1.3.6.1.4.1.25461.2.1.2.1.21.0 = STRING: "2020/10/16 01:05:48"
.1.3.6.1.4.1.25461.2.1.2.1.22.0 = STRING: "2020/10/18 11:03:49"
.1.3.6.1.4.1.25461.2.1.2.1.23.0 = STRING: "unknown"

**Comment by garnier-quentin** [comment]
You can test. It should be fixed

**Comment by joschi99** [comment]
Is working, thanks
