### ISSUE TITLE
[snmp_standard::plugin] mode string-value

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#228]
Hello,

Should you add this mode for string-value[s] in a table ?

Example :
HPVC-MIB::vcPhysicalServerReasonCode.101 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.102 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.103 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.104 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.105 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.106 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.107 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.108 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.109 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.110 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.111 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.112 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.113 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.115 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.116 = INTEGER: vcPhysicalServerOk(500)

Thanks.

**Comment by garnier-quentin** [comment]
I don't understand the demand.

**Comment by ritouret** [comment]
Instead of request a single value, it should request all the values in a table and the return code plugin still depending from --warning-regexp and --critical-regexp and the output still depending from --format and --map-values.

Example : if values are : 
HPVC-MIB::vcPhysicalServerReasonCode.101 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.102 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.103 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.104 = INTEGER: vcPhysicalServerOk(500)
-> Then return code is OK and ouptut is "OK: All 4 entries [4/4 Physical Server] are ok."

if values are : 
HPVC-MIB::vcPhysicalServerReasonCode.101 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.102 = INTEGER: vcPhysicalServerFailed(502)
HPVC-MIB::vcPhysicalServerReasonCode.103 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.104 = INTEGER: vcPhysicalServerOk(500)
-> Then return code is CRITICAL and ouptut is "CRITICAL: Physical Server 102 is failed"

Same thing than you did for many plugins, but for a generic table for this mode !
