### ISSUE TITLE
Plugin storage::dell::equallogic::snmp::plugin --mode array-usage returns Use of uninitialized value in int at /root/scripts/centreon-plugins/centreon/plugins/values.pm line 220 after 1st run

### ISSUE THREAD

**Issue by se-baj** [centreon/centreon-plugins#2285]
## Bug/Question

Hello,

I met the following issue using --plugin storage::dell::equallogic::snmp::plugin --mode array-usage

Command line: 
> `'/bin/perl' './centreon_plugins.pl' '--hostname' '' '--mode' 'array-usage' '--plugin' 'storage::dell::equallogic::snmp::plugin' '--snmp-community' '' --snmp-version v2c --statefile-dir .  --warning-used 90 --critical-used 95`
>
Returns an OK output but also this error:
> `Use of uninitialized value in int at /root/scripts/centreon-plugins/centreon/plugins/values.pm line 220`

When I comment as a test line 225 of centreon/plugins/values.pm file, there is no more error (but obviously some metrics disappear from the perfdata ). 

Also when running the command the first time (buffer creation), no error are displayed, but starting at the second run (tmp file created), error (Use of uninitialized value in int at /root/scripts/centreon-plugins/centreon/plugins/values.pm line 220) is displayed.

It will be great if you could have a look to that.
Thanks for your help.
Regards.
sebastien.

**Comment by garnier-quentin** [comment]
Could you provide following command result ? (can be by email):
```snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.12740.2.1 > dell_equallogic.snmpwalk```

**Comment by se-baj** [comment]
I should check that on my side and come back to you.
Thanks

**Comment by se-baj** [comment]
Hello Quentin,

Here it is.

[dell_equallogic.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/5444513/dell_equallogic.snmpwalk.txt)

Thanks for your help,
Regards
sebastien

**Comment by garnier-quentin** [comment]
Thanks. You can test with last version

**Comment by se-baj** [comment]
It's ok now, thanks for the quick fix.
Regards
