### ISSUE TITLE
UPS Socomec Netvision 7 support

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#2287]
Hi,

I have a MIB of UPS Socomec Netvision 7, can  we add a plugin for it?

Thanks

**Comment by Sims24** [comment]
Hi, 

Could you provide following informations as requested in the issue template 🙃 ? 

## New plugins and modes

To develop a plugin/mode, we need following informations:
*** SNMP: MIBs files and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk)**
* HTTP API (SOAP, Rest/Json, XML-RPC): the documentation and some curls examples
* CLI: command line examples
* SQL: requests
* JMX: mbean names and attributes

If you can't provide informations, we'll close the ticket. The issue can be reopened if informations are provided.
All developments are open-source. We can't give a date for the development. If it's a priority, send us an email about it (qgarnier@centreon.com and sbomm@centreon.com) 
and we'll put you in touch with our company. 

Thanks for using centreon-plugins!

**Comment by Cool34000** [comment]
Hi,

I have 2 SOCOMEC UPS monitored in CENTREON:
- MASTERYS BC+ 15kVA
- NETYS RT 2.2kVA
I'm using the RFC1628 general plugin.
It's working more or less as expected but I'm getting wrong values on the remaining time

Both UPS are using the NetVision 7 network card with firmware 7.2 (MIBs are for 7.3)


MIB file and snmpwalk are attached. Thanks
[NV7-MIB_PRODUCT-SOFTWARE_2020-06_MIB-7.3_EN-GB.zip](https://github.com/centreon/centreon-plugins/files/5595524/NV7-MIB_PRODUCT-SOFTWARE_2020-06_MIB-7.3_EN-GB.zip)
[SOCOMEC_NETYS_RT.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/5595577/SOCOMEC_NETYS_RT.snmpwalk.txt)
[SOCOMEC_MASTERSYS_BC+.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/5595578/SOCOMEC_MASTERSYS_BC%2B.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
Could you test with plugin: hardware::ups::socomec::netvision::snmp::plugin ?

**Comment by Cool34000** [comment]
Very good!
I have a lot more infos in input-lines and output-lines modes!
Remaining time is the same as RFC1628 plugin (0 minutes)

```
# /usr/lib/centreon/plugins//centreon_plugins.pl --plugin=hardware::ups::socomec::netvision::snmp::plugin --hostname=192.168.70.51 --snmp-version='2c' --snmp-community='public' --mode=alarms
OK: current alarms: 0 | 'alarms.current.count'=0;;;0;

```

```
# /usr/lib/centreon/plugins//centreon_plugins.pl --plugin=hardware::ups::socomec::netvision::snmp::plugin --hostname=192.168.70.51 --snmp-version='2c' --snmp-community='public' --mode=battery
OK: battery status is normal - charge remaining: 100% (0 minutes remaining) | 'battery.charge.remaining.percent'=100%;;;0;100 'battery.charge.remaining.minutes'=0;;;0; 'battery.voltage.volt'=338.6V;;;; 'battery.temperature.celsius'=23C;;;;

```
```
# /usr/lib/centreon/plugins//centreon_plugins.pl --plugin=hardware::ups::socomec::netvision::snmp::plugin --hostname=192.168.70.51 --snmp-version='2c' --snmp-community='public' --mode=input-lines
OK: frequence: 49.90 Hz - All input lines are ok | 'lines.input.frequence.hertz'=49.90Hz;;;; '1#line.input.current.ampere'=3.40A;;;0; '1#line.input.voltage.volt'=246.00V;;;; '2#line.input.current.ampere'=3.40A;;;0; '2#line.input.voltage.volt'=246.00V;;;; '3#line.input.current.ampere'=3.30A;;;0; '3#line.input.voltage.volt'=248.00V;;;;

```
```
# /usr/lib/centreon/plugins//centreon_plugins.pl --plugin=hardware::ups::socomec::netvision::snmp::plugin --hostname=192.168.70.51 --snmp-version='2c' --snmp-community='public' --mode=output-lines
OK: Output source status is 'onInverter' - All output lines are ok | '1#line.output.load.percentage'=34.00%;;;0;100 '1#line.output.current.ampere'=5.80A;;;0; '1#line.output.voltage.volt'=230.00V;;;; '2#line.output.load.percentage'=20.00%;;;0;100 '2#line.output.current.ampere'=1.70A;;;0; '2#line.output.voltage.volt'=229.00V;;;; '3#line.output.load.percentage'=30.00%;;;0;100 '3#line.output.current.ampere'=5.30A;;;0; '3#line.output.voltage.volt'=230.00V;;;;

```

Thanks!

**Comment by garnier-quentin** [comment]
That value is:
.1.3.6.1.4.1.4555.1.1.7.1.2.3.0 = 0 (upsEstimatedMinutesRemaining)

Maybe 0 is not implemented

**Comment by Cool34000** [comment]
Yes, it's a mess on these UPS... Look a this one:
```
# /usr/lib/centreon/plugins//centreon_plugins.pl --plugin=hardware::ups::socomec::netvision::snmp::plugin --hostname=192.168.70.50 --snmp-version='2c' --snmp-community='public' --mode=battery
OK: battery status is charging - charge remaining: 100% (65535 minutes remaining) | 'battery.charge.remaining.percent'=100%;;;0;100 'battery.charge.remaining.minutes'=65535;;;0; 'battery.current.ampere'=6553.5A;;;0; 'battery.voltage.volt'=54.5V;;;;
```

**Comment by garnier-quentin** [comment]
Many minutes ;)

**Comment by Cool34000** [comment]
> 
> 
> That a lot of minutes!

It's a big UPS! ;-)
