### ISSUE TITLE
HPVC-MIB and HPVC-MODULE-MIB

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#229]
[vc-domain-mib.txt](https://github.com/centreon/centreon-plugins/files/48354/vc-domain-mib.txt)
[vc-module-mib.txt](https://github.com/centreon/centreon-plugins/files/48355/vc-module-mib.txt)
[vc-qos-mib.txt](https://github.com/centreon/centreon-plugins/files/48353/vc-qos-mib.txt)

Should you add a plugin for these MIBs ?

Here some snmpwalk results and MIB definitions :

HPVC-MIB
-------------
VcManagedStatus
    SYNTAX      INTEGER
    {
        unknown(1),
        normal(2),
        warning(3),
        minor(4),
        major(5),
        critical(6),
        disabled(7),
        info(8)
    }

HPVC-MIB::vcDomainName.0 = STRING: XXXXXXXXXXX_vc_domain
HPVC-MIB::vcDomainManagedStatus.0 = INTEGER: normal(2)
HPVC-MIB::vcDomainPrimaryAddressType.0 = INTEGER: udpIpv4(1)
HPVC-MIB::vcDomainPrimaryAddress.0 = STRING: "XX.XX.XX.XX"
HPVC-MIB::vcDomainCheckpointValid.0 = INTEGER: true(1)
HPVC-MIB::vcDomainLastCheckpointTime.0 = STRING: UTC 07-11-15 09:21:58
HPVC-MIB::vcDomainStackingLinkRedundant.0 = INTEGER: true(1)
HPVC-MIB::vcDomainRootCause.0 = STRING:
HPVC-MIB::vcDomainCause.0 = STRING: All enclosures and profiles are normal in domain
HPVC-MIB::vcDomainReasonCode.0 = INTEGER: vcDomainOk(700)
HPVC-MIB::vcDomainPrimaryAddressIpv6.0 = ""

VcDomainReasonCodeType
    SYNTAX      INTEGER
    {
      vcDomainOk(700),
      vcDomainAbnormalEnclosuresAndProfiles(701),
      vcDomainSomeEnclosuresAbnormal(702),
      vcDomainUnmappedProfileConnections(703),
      vcDomainStackingFailed(706),
      vcDomainStackingNotRedundant(707),
      vcDomainSomeProfilesAbnormal(709),
      vcDomainUnknown(712),
      vcDomainOverProvisioned(713),
      vcDomainSflowIndirectlyDisabled(801),
      vcDomainSflowFailed(802),
      vcDomainSflowDegraded(803),
      vcDomainPortMonitorIndirectlyDisabled(901)
    }

HPVC-MIB::vcEnclosureIndex.1 = INTEGER: 1
HPVC-MIB::vcEnclosureName.1 = STRING: XXXXXXXXXXX
HPVC-MIB::vcEnclosureManagedStatus.1 = INTEGER: normal(2)
HPVC-MIB::vcEnclosureAddressType.1 = INTEGER: udpIpv4(1)
HPVC-MIB::vcEnclosureAddress.1 = STRING: "XX.XX.XX.XX"
HPVC-MIB::vcEnclosureUUID.1 = STRING: 09CZ3334LXH7
HPVC-MIB::vcEnclosureRootCause.1 = STRING:
HPVC-MIB::vcEnclosureCause.1 = STRING: Enclosure enc0 is normal
HPVC-MIB::vcEnclosureReasonCode.1 = INTEGER: vcEnclosureOk(600)
HPVC-MIB::vcEnclosureAddressIpv6.1 = ""

VcEnclosureReasonCodeType
    SYNTAX      INTEGER
    {
      vcEnclosureOk(600),
      vcEnclosureAllEnetModulesFailed(601),
      vcEnclosureSomeEnetModulesAbnormal(602),
      vcEnclosureSomeModulesOrServersIncompatible(603),
      vcEnclosureSomeFcModulesAbnormal(604),
      vcEnclosureSomeServersAbnormal(605),
      vcEnclosureUnknown(606)
    }

HPVC-MIB::vcModuleType.101 = INTEGER: vcModuleEnet(1)
HPVC-MIB::vcModuleType.102 = INTEGER: vcModuleEnet(1)
HPVC-MIB::vcModuleType.103 = INTEGER: vcModuleFC(2)
HPVC-MIB::vcModuleType.104 = INTEGER: vcModuleFC(2)
HPVC-MIB::vcModuleManagedStatus.101 = INTEGER: normal(2)
HPVC-MIB::vcModuleManagedStatus.102 = INTEGER: normal(2)
HPVC-MIB::vcModuleManagedStatus.103 = INTEGER: normal(2)
HPVC-MIB::vcModuleManagedStatus.104 = INTEGER: normal(2)
...
HPVC-MIB::vcModuleReasonCode.101 = INTEGER: vcEnetmoduleOk(400)
HPVC-MIB::vcModuleReasonCode.102 = INTEGER: vcEnetmoduleOk(400)
HPVC-MIB::vcModuleReasonCode.103 = INTEGER: vcFcmoduleOk(408)
HPVC-MIB::vcModuleReasonCode.104 = INTEGER: vcFcmoduleOk(408)

VcModuleReasonCodeType
    SYNTAX      INTEGER
    {
      vcEnetmoduleOk(400),
      vcEnetmoduleEnclosureDown(401),
      vcEnetmoduleModuleMissing(402),
      vcEnetmodulePortprotect(404),
      vcEnetmoduleIncompatible(405),
      vcEnetmoduleHwDegraded(406),
      vcEnetmoduleUnknown(407),
      vcFcmoduleOk(408),
      vcFcmoduleEnclosureDown(409),
      vcFcmoduleModuleMissing(410),
      vcFcmoduleHwDegraded(412),
      vcFcmoduleIncompatible(413),
      vcFcmoduleUnknown(414)
    }

HPVC-MIB::vcPortType.1101 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1102 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1103 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1104 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1105 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1106 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1107 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1108 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1109 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1110 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1111 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1112 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1113 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1114 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1115 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1116 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1117 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1118 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1119 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1120 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1121 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1122 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1123 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1124 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1125 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1126 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1127 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1128 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1129 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1130 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1201 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1202 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1203 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1204 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1205 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1206 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1207 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1208 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1209 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1210 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1211 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1212 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1213 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1214 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1215 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1216 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1217 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1218 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1219 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1220 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1221 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1222 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1223 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1224 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1225 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1226 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1227 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1228 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1229 = INTEGER: vcEnetPhysicalPort(1)
HPVC-MIB::vcPortType.1230 = INTEGER: vcEnetPhysicalPort(1)
...
HPVC-MIB::vcPortManagedStatus.1101 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1102 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1103 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1104 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1105 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1106 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1107 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1108 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1109 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1110 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1111 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1112 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1113 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1114 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1115 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1116 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1117 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1118 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1119 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1120 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1121 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1122 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1123 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1124 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1125 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1126 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1127 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1128 = INTEGER: disabled(7)
HPVC-MIB::vcPortManagedStatus.1129 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1130 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1201 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1202 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1203 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1204 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1205 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1206 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1207 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1208 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1209 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1210 = INTEGER: warning(3)
HPVC-MIB::vcPortManagedStatus.1211 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1212 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1213 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1214 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1215 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1216 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1217 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1218 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1219 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1220 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1221 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1222 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1223 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1224 = INTEGER: normal(2)
HPVC-MIB::vcPortManagedStatus.1225 = INTEGER: normal(2)

VcPortReasonCodeType
    SYNTAX      INTEGER
    {
      vcEnetPortOK(1),
    }

HPVC-MIB::vcPhysicalServerManagedStatus.101 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.102 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.103 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.104 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.105 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.106 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.107 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.108 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.109 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.110 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.111 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.112 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.113 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.115 = INTEGER: normal(2)
HPVC-MIB::vcPhysicalServerManagedStatus.116 = INTEGER: normal(2)
...
HPVC-MIB::vcPhysicalServerReasonCode.101 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.102 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.103 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.104 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.105 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.106 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.107 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.108 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.109 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.110 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.111 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.112 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.113 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.115 = INTEGER: vcPhysicalServerOk(500)
HPVC-MIB::vcPhysicalServerReasonCode.116 = INTEGER: vcPhysicalServerOk(500)

VcPhysicalServerReasonCodeType
    SYNTAX      INTEGER
    {
      vcPhysicalServerOk(500),
      vcPhysicalServerEnclosureDown(501),
      vcPhysicalServerFailed(502),
      vcPhysicalServerDegraded(503),
      vcPhysicalServerUnknown(504)
    }

HPVC-MIB::vcEnetNetworkReasonCode.1 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.2 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.3 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.4 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.5 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.6 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.7 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.8 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.9 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.10 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.11 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.12 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.13 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.14 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.15 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.16 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.17 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.18 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.19 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.20 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.21 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.22 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.23 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.24 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.25 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.26 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.27 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.28 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.29 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.30 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.31 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.32 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.33 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.34 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.35 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.36 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.37 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.38 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.39 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.40 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.41 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.42 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.43 = INTEGER: vcNetworkOk(100)
HPVC-MIB::vcEnetNetworkReasonCode.44 = INTEGER: vcNetworkOk(100)

VcEnetNetworkReasonCodeType
    SYNTAX      INTEGER
    {
      vcNetworkOk(100),
      vcNetworkUnknown(101),
      vcNetworkDisabled(102),
      vcNetworkAbnormal(104),
      vcNetworkFailed(105),
      vcNetworkDegraded(106),
      vcNetworkNoPortsAssignedToPrivateNetwork(109)
    }

HPVC-MIB::vcFcFabricReasonCode.1 = INTEGER: vcFabricOk(200)
HPVC-MIB::vcFcFabricReasonCode.2 = INTEGER: vcFabricOk(200)

VcFcFabricReasonCodeType
    SYNTAX      INTEGER
    {
      vcFabricOk(200),
      vcFabricNoPortsConfigured(202),
      vcFabricSomePortsAbnormal(203),
      vcFabricAllPortsAbnormal(204),
      vcFabricWwnMismatch(205),
      vcFabricUnknown(206)
    }

	
HPVC-MIB::vcProfileReasonCode.2 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.3 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.4 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.5 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.6 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.7 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.8 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.9 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.10 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.11 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.12 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.13 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.14 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.15 = INTEGER: vcProfileOk(300)
HPVC-MIB::vcProfileReasonCode.16 = INTEGER: vcProfileOk(300)

VcProfileReasonCodeType
    SYNTAX      INTEGER
    {
      vcProfileOk(300),
      vcProfileServerAbnormal(301),
      vcProfileAllConnectionsFailed(304),
      vcProfileSomeConnectionsUnmapped(309),
      vcProfileAllConnectionsAbnormal(310),
      vcProfileSomeConnectionsAbnormal(311),
      vcProfileUEFIBootmodeIncompatibleWithServer(312),
      vcProfileUnknown(313)

	
HPVCMODULE-MIB (@IP XX.XX.XX.XX)
--------------
HPVCMODULE-MIB::vcModuleDomainName.0 = STRING: XXXXXXXXXX
HPVCMODULE-MIB::vcModuleRole.0 = INTEGER: standby(4)
HPVCMODULE-MIB::vcModuleDomainPrimaryAddressType.0 = INTEGER: udpIpv4(1)
HPVCMODULE-MIB::vcModuleDomainPrimaryAddress.0 = STRING: "YY.YY.YY.YY"
HPVCMODULE-MIB::vcModuleEnclosureRole.0 = INTEGER: primary(2)

HPVCMODULE-MIB (@IP YY.YY.YY.YY)
--------------
HPVCMODULE-MIB::vcModuleDomainName.0 = STRING: XXXXXXXXXXXX
HPVCMODULE-MIB::vcModuleRole.0 = INTEGER: primaryProtected(2)
HPVCMODULE-MIB::vcModuleDomainPrimaryAddressType.0 = INTEGER: udpIpv4(1)
HPVCMODULE-MIB::vcModuleDomainPrimaryAddress.0 = STRING: "YY.YY.YY.YY"
HPVCMODULE-MIB::vcModuleEnclosureRole.0 = INTEGER: primary(2)

VcModuleRole
    SYNTAX      INTEGER
    {
       unintegrated(1),
       primaryProtected(2),
       primaryUnprotected(3),
       standby(4),
       other(5)
    }

HPVC-MIB::vcModuleReasonCode.101 = INTEGER: vcEnetmoduleOk(400)
HPVC-MIB::vcModuleReasonCode.102 = INTEGER: vcEnetmoduleOk(400)
HPVC-MIB::vcModuleReasonCode.103 = INTEGER: vcFcmoduleOk(408)
HPVC-MIB::vcModuleReasonCode.104 = INTEGER: vcFcmoduleOk(408)

VcModuleReasonCodeType
    SYNTAX      INTEGER
    {
      vcEnetmoduleOk(400),
      vcEnetmoduleEnclosureDown(401),
      vcEnetmoduleModuleMissing(402),
      vcEnetmodulePortprotect(404),
      vcEnetmoduleIncompatible(405),
      vcEnetmoduleHwDegraded(406),
      vcEnetmoduleUnknown(407),
      vcFcmoduleOk(408),
      vcFcmoduleEnclosureDown(409),
      vcFcmoduleModuleMissing(410),
      vcFcmoduleHwDegraded(412),
      vcFcmoduleIncompatible(413),
      vcFcmoduleUnknown(414)
    }

**Comment by garnier-quentin** [comment]
Which equipment ?

**Comment by ritouret** [comment]
HP Virtual Connect : 
SNMPv2-MIB::sysDescr.0 = STRING: HP VC Flex-10/10D Module 4.41 2015-03-05T20:56:57Z

It's running on an HP BladeSystem c7000 Enclosure G3.
