### ISSUE TITLE
Switch FiberStore (FS) -- please add support 

### ISSUE THREAD

**Issue by joffc** [centreon/centreon-plugins#2293]
Hello, 

As mentionned on the Open source Centreon Slack, here is the Mibs and the snmpwalk. 
It should be great for us to have support for FS machines.
Let me know if something's missing. 
[S5850 and S8050 Series Switches SNMP MIB Files.zip](https://github.com/centreon/centreon-plugins/files/5446134/S5850.and.S8050.Series.Switches.SNMP.MIB.Files.zip)
[snmpwalk_FS.txt](https://github.com/centreon/centreon-plugins/files/5446141/snmpwalk_FS.txt)

Thanks in advance

**Comment by garnier-quentin** [comment]
Your walk is missing informations. Could you try to snmpwalk following branch ? .1.3.6.1.4.1.27975

**Comment by joffc** [comment]
The switch returns me " SNMPv2-SMI ::enterprises.27975 = No Such Object available on this agent at this OID"

**Comment by joffc** [comment]
[Snmpwalk_FS_52642.txt](https://github.com/centreon/centreon-plugins/files/5446360/Snmpwalk_FS_52642.txt)

Here it is. I still available to provide you more informations if needed.

**Comment by garnier-quentin** [comment]
The mib file is deprecated. If we can get one with right information, it should be nice :)

**Comment by joffc** [comment]
I just get them from the FS support.
How can i find the right mibs ? 

Thanks for your time !

**Comment by garnier-quentin** [comment]
Ask to the support: why branch OID responding is not the same than the mib file ?

**Comment by joffc** [comment]
Ok, i do this right away and come back to you with additionnal informations.

**Comment by joffc** [comment]
Hello Quentin, here is the last update about MIB from FS. 


[S5850.zip](https://github.com/centreon/centreon-plugins/files/5457563/S5850.zip)

**Comment by garnier-quentin** [comment]
Thanks for the feedback. It's ok.

**Comment by garnier-quentin** [comment]
You can test the new plugin: network::fiberstore::snmp::plugin
I have added basic monitoring first. 

Maybe we could add in future: ipsla, ddos, qos,...
