### ISSUE TITLE
[network::nortel::standard::snmp] 

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#2317]
Hi,

We have vsp 8400 (fabric 8404C) of extreme networks (the mib is from Nortel).

We only have the vision (cpu / memory) of the first slot and not the other three. 

OK: CPU 'slot_1' usage 9.00 % (5min) 
OK: Memory 'slot_1' used: 0.71 %

Hardware-global probe only sees psu : 

OK: All 2 components are ok [2/2 psus]

Is it possible to monitor the cards and have a status of the fabric (equivalent of sys-info CLI) ?

`LED Info :

        LED#1 Label  : PWR
        LED#1 Status : GreenSteady

        LED#2 Label  : Status
        LED#2 Status : GreenSteady

        LED#3 Label  : Rps
        LED#3 Status : GreenSteady

        LED#4 Label  : Fan
        LED#4 Status : GreenSteady`

I send you by mail the output of the snmpwalk, the sys-info CLI and MIB.

Best regards.

**Comment by garnier-quentin** [comment]
Yes you can send mib files and snmpwalk

**Comment by gagzou** [comment]
[VOSS8400.8.1.6.0_mib.zip](https://github.com/centreon/centreon-plugins/files/5482950/VOSS8400.8.1.6.0_mib.zip)

**Comment by garnier-quentin** [comment]
Could you test it ? I have set some default values. Maybe it's not good:
```
['unknown', 'UNKNOWN'],
            ['greenSteady', 'OK'],
            ['greenBlinking', 'OK'],
            ['amberSteady', 'WARNING'],
            ['amberBlinking', 'WARNING'],
            ['greenamberBlinking', 'WARNING'],
            ['off', 'OK']
```

**Comment by gagzou** [comment]
Sorry for the delay.
For 'off' : 

- in 'Status' : CRITICAL (The switch is non-operational)
- in others ('PWR'/'Rps'/'Fan') : OK

**Comment by gagzou** [comment]
Thanks, test is good for 'LED'
