### ISSUE TITLE
Oracle dataguard standby slave

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#2322]
If slave database is standby, we cannot connect on it.
So we need to enhance oracle dataguard mode to permit:
* check 2 databases with multiple option
* check dataguard lag directly on master
```
select VALUE from V$DATAGUARD_STATS where name IN ('transport lag', 'apply lag') ;
```

**Comment by UrBnW** [comment]
> check dataguard lag directly on master

Not sure it will be possible :
https://docs.oracle.com/database/121/REFRN/GUID-B346DD88-3F5E-4F16-9DEE-2FDE62B1ABF7.htm
_V$DATAGUARD_STATS displays information about Oracle Data Guard metrics **when queried on a standby database**. No rows are returned when queried on a primary database._
