### ISSUE TITLE
 [apps::protocols::http::plugin] --critical-numeric do not handle scientific notation

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon-plugins#2323]
Hello

We are tracking numbers in an API who are giving results in scientific notation for small numbers.

i set a "--critical-numeric :1"  and the API give this "1.1734640657229e-95"
which is really bellow 1, but the pluing do not hande this and says it's Ok.

Can it be hanlded by Centreon plugins ?

Command used : 
`/usr/lib/nagios/plugins/customs/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=json-content --hostname="10.66.85.2" --urlpath='/api/system/metrics/org.apache.logging.log4j.core.Appender.error' --lookup="\$.m5_rate" --header="Content-Type: application/json" --proto=http --critical-numeric :1 --threshold-value values --format-critical "org.apache.logging.log4j.core.Appender.error : %{values}" --format-ok "org.apache.logging.log4j.core.Appender.error : %{values}" --filter-perfdata '^(?\!count|time)' --timeout 5 --port 9000 --change-perfdata=element_1,org.apache.logging.log4j.core.Appender.error --credentials --username yyyyyy --password xxxxxxxxxxx`

Thanks.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by BenoitPoulet** [comment]
Sorry it don't seems to work :

```
± |master ?:2 ✗| → ./centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=json-content --hostname="10.66.85.2" --urlpath='/api/system/metrics/org.apache.logging.log4j.core.Appender.error' --lookup="\$.m5_rate" --header="Content-Type: application/json" --proto=http --critical-numeric :1 --threshold-value values --format-critical "org.apache.logging.log4j.core.$Appender.error : %{values}" --format-ok "org.apache.logging.log4j.core.Appender.error : %{values}"  --timeout 5 --port 9000 --change-perfdata=element_1,org.apache.logging.log4j.core.Appender.error --credentials --username xxxx --password yyyy --verbose
OK: org.apache.logging.log4j.core.Appender.error : 1.53072816639953e-114 | 'count'=1;;;0; 'time'=0.215s;;;0;
Lookup XPath $.m5_rate:
   Node value: 1.53072816639953e-114
Response time 0.215s
```

**Comment by garnier-quentin** [comment]
Could you provide the json ? (with --debug)

**Comment by BenoitPoulet** [comment]
Don't know why it's printed twice, but here is the output
```
X-Runtime-Microseconds: 145595

{"count":2,"m15_rate":9.121473918401694E-41,"m1_rate":2.964393875E-314,"m5_rate":4.6104646373051585E-115,"mean_rate":2.5803140164839594E-5,"units":"events/second"}
{"count":2,"m15_rate":9.121473918401694E-41,"m1_rate":2.964393875E-314,"m5_rate":4.6104646373051585E-115,"mean_rate":2.5803140164839594E-5,"units":"events/second"}
Lookup XPath $.m5_rate:
   Node value: 4.61046463730516e-115
Response time 0.208s
```

**Comment by garnier-quentin** [comment]
You can test again. But e-115, it's so small... I don't know how broker will react of that value

**Comment by BenoitPoulet** [comment]
Yes i agree, that kind of number as no sense.

I will ask to the support of the other product is they can do something, like rounding.

Your last patch is working, but look at the number ^^"

CRITICAL: org.apache.logging.log4j.core..error : 6.46777503742604e-117 | 'count'=1;;;0; 'org.apache.logging.log4j.core.Appender.error'=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006467775037426036;;1:;; 'time'=0.209s;;;0;

I will try to give this line to Broker and see what happen.

Thanks for you work and the quick patch.

**Comment by garnier-quentin** [comment]
I don't know if broker like format scientific. If yes, i can put back the output in scientific format
