### ISSUE TITLE
[apps::exchange::2010::local::mode::databases] 

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#2326]
## Bug
Since the update of the Exchange2010 plugin pack (3.2.0), the DATABASES and QUEUES probes no longer work.

Unknown option: warning-database-space-size at C:\Windows\TEMP\par-4558434831362d5052442d4150503424\cache-f55e56d520432b5534dd558116fb4d09e12bb9c2\inc\lib/centreon/plugins/alternative/Getopt.pm line 67

Unknown option: warning-status at C:\Windows\TEMP\par-4558434831362d5052442d4150503424\cache-f55e56d520432b5534dd558116fb4d09e12bb9c2\inc\lib/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by gagzou** [comment]
Centreon 19.10.16
Update windows cantreon-pack > same problem

**Comment by garnier-quentin** [comment]
You need to update centreon_plugins.exe. Try with that one:
https://share.centreon.com/public/424beb

**Comment by gagzou** [comment]
Thanks, it works.
When will the centreon pack be updated?
Best regards

**Comment by garnier-quentin** [comment]
The pack is updated. It's the plugin.
