### ISSUE TITLE
[apps::nsclient::restapi::plugin] - extend to calculate difference between two polls

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2329]
It should be useful to have a new mode or a option that allows to calculate the difference between two polls. This would be extend the possibilities interrogating for example some Windows performance counters

**Comment by garnier-quentin** [comment]
You cannot do that with nsclient (nrpe or rest api).
You should use rrd configuration with nsclient: https://docs.nsclient.org/reference/windows/CheckSystem/#check_pdh

**Comment by joschi99** [comment]
As I know with this option we can have for example an average about a defined time range, but not sure if we can have a delta between to times like:
- poll 1: time 14:00, total sessions = 3220
- poll 2: time 14:05, total sessions = 3225
- result poll 2: 5 sessions (poll 2 - poll 1)

**Comment by garnier-quentin** [comment]
I dont think so. Maybe we can do a delta with some options

**Comment by joschi99** [comment]
That is exactly what a asked, i'm not aware of other ways

**Comment by joschi99** [comment]
Hi @garnier-quentin,
not sure if we have to implement this on Centreon nsclient plugin, probably we have to do a dedicated plugin for nsclient. We are doing some tests about them, i will update you after first results.

**Comment by garnier-quentin** [comment]
Do you have some news @joschi99 ?

**Comment by joschi99** [comment]
We have done a PS script that will calculate the difference between two polls, so you can close the case. No idea of there is a better way to do this. If you like I can share the PS with you.

**Comment by garnier-quentin** [comment]
Thanks for the feedback. I close it
