### ISSUE TITLE
Please create support for Forti Authenticator

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2338]
It should be nice to have support for Fortinet Fortiauthenticator.
You can find the mibs and a snmpwalk attached

[fortinet-authenticator.snmpwalk - Copy.txt](https://github.com/centreon/centreon-plugins/files/5523729/fortinet-authenticator.snmpwalk.-.Copy.txt)
[fortiauthenticator.zip](https://github.com/centreon/centreon-plugins/files/5523731/fortiauthenticator.zip)

It should be nice to have:

- CPU
- Memory
- HA Status
- Disk usage
- Hardware
- Interfaces
- Interface IP ic changed*
- Auth users threshold exceeded*
- Auth group threshold exceeded*
- Radius NAS threshold exceeded*
- Auth event rate threshold exceeded*
- Auth failure rate threshold exceeded*
- User lockout detected*
- HA sync activity is low*

(*) maybe only with snmp trap??

**Comment by garnier-quentin** [comment]
The plugin is done. You can test it!

**Comment by joschi99** [comment]
Hi @garnier-quentin,
I have done some test. Seems working very well.

Thanks

**Comment by garnier-quentin** [comment]
thanks for the feedback!
