### ISSUE TITLE
Handling GET request including "Content-Type" Header with LWP Module

### ISSUE THREAD

**Issue by ypilpre** [centreon/centreon-plugins#2340]
Hi,

I try to make a call to an API to a call Huawei Cloud Ressource Check described in this doc :

https://docs.prod-cloud-ocb.orange-business.com/en-us/api/iam/en-us_topic_0057845622.html

The `centreon::plugins::backend::http::lwp ` doesn't allow 'Content-Type' Header  for GET Request. 

https://github.com/centreon/centreon-plugins/blob/cf8248b333573f9345f0bce837516863ebc988cb/centreon/plugins/backend/http/lwp.pm#L199

The Content-Type header is simply discarded, and request end with a 404 error. Postman Tests with this header works.

Although, it's not common to pass a Content-Type with a GET Request, but Huawei Cloud seems to used it for several services

**Comment by ypilpre** [comment]
Patched with : 

```
    if ($request_options->{method} ne 'GET') {
        if (defined($content_type_forced)) {
            $req->content_type($content_type_forced);
            $req->content($request_options->{query_form_post});
        } else {
            my $uri_post = URI->new();
            if (defined($request_options->{post_params})) {
                $uri_post->query_form($request_options->{post_params});
            }
            $req->content_type('application/x-www-form-urlencoded');
            $req->content($uri_post->query);
        }
    } else {
         if (defined($content_type_forced)) {
            $req->content_type($content_type_forced);
         }
    }
```
Works as expected....

**Comment by Sims24** [comment]
Hello @ypilpre , 

Could you please explain how you tried to set the header value please ? 

Simon

**Comment by ypilpre** [comment]
I use a` $self->{http}->add_header(key => 'Content-Type', value => 'application/json');` in my code before the http request.

for example : `$self->{http}->add_header(key => 'Accept', value => 'application/json');` is ok

**Comment by garnier-quentin** [comment]
Yes i understand. You want to push a content type header without content ?

**Comment by garnier-quentin** [comment]
It not really follow rfc: https://tools.ietf.org/html/rfc7231#section-3.1.1.5
I don't like to put it. I think you should ask to huawei why. Or we can add an option to force it...

**Comment by ypilpre** [comment]
Hi, 

I' have no way to ask to Huawei Dev Team an API Change (Several tools are also based on this API like Terraform). But I open  ticket on their service desk.
The rfc is not strict about the Content-Type, event if it's obvious to request a content-type for a GET query....

Allowing a Content-Type for GET in the lwp.pm could break something ?

**Comment by garnier-quentin** [comment]
Yes it can. Maybe some web servers won't like content-type header with no POST.

**Comment by ypilpre** [comment]
It's up to the plugin developper to handle correctly which content-type he will send to the server. 
By default, "content_type_forced" is no set unless we set a ` $self->{http}->add_header(key => 'Content-Type', value => 'application/json');` for example...

**Comment by garnier-quentin** [comment]
You can test it with last version.
