### ISSUE TITLE
[storage::hp::p2000::xmlapi::plugin] new mode request "power-supplies"

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2344]
Hello.

Could you please add a few additional modes to the plug-in for a more complete monitoring of **HP MSA P2000 G3** storage systems.

My guess is that common problems like power supply failure can be noticed through the "**health**" mode. However, there is an assumption that this mode may not show problems if the fan in the working power supply stops or starts to work badly. Therefore, I propose to add a separate mode, which will give extended information about the operation of each power supply.

PS status is available here: `/api/show/power-supplies`

XML output in attachment: [power-supplies.zip](https://github.com/centreon/centreon-plugins/files/5531400/power-supplies.zip)

In general, the "health" mode seems cumbersome and at the same time, in my opinion, it cannot fully show the status and performance of all storage components. 
Therefore, I suggest that you create several separate modes for different components. In each of these modes I would like to see performance data.

I will provide all the necessary information for analysis.

Thanks in advance

**Comment by garnier-quentin** [comment]
You can test with last version (commit: de441cd5bf545596c71348bcf5167af970163205)

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin. 
The mode works, but does not seem to have a perfdata. 
How about adding a perfdata like in sensors mode ?

**Comment by Aleksey-Maksimov** [comment]
Quentin, is it possible?

**Comment by garnier-quentin** [comment]
Which metrics do you want ? The temperature:
```
<PROPERTY name="dctemp" type="uint32" size="8" draw="false" sort="string" display-name="PSU Temperature">27</PROPERTY>
```

**Comment by Aleksey-Maksimov** [comment]
Yes, these are the metrics. 
In this case, only the power supplies of the main storage system have data on voltage. Disk enclosures do not have this information. 

In the sections for each power supply in the main storage system, there is also a nested section with information about the fan (basetype = "fan"). There is information about the fan speed. 
But for fans, I also suggested a separate check in https://github.com/centreon/centreon-plugins/issues/3146

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin.

Is it possible to wait for the appearance of perfdata for power supplies?

**Comment by garnier-quentin** [comment]
What dou you mean by 'wait for the appearance' ?

**Comment by Aleksey-Maksimov** [comment]
Sorry for my English. 
I meant that I asked you earlier to add parfdata in '--mode=health' and '--component=psu' 

Now, if we want to make a separate power supply monitoring service, we do not see any related data received from power supplies in it.

```
# ./centreon_plugins.pl' '--plugin=storage::hp::p2000::xmlapi::plugin' 
'--mode=health' '--component=psu' 
'--curl-opt' 'CURLOPT_SSL_VERIFYPEER => 0' '--curl-opt' 'CURLOPT_SSL_VERIFYHOST => 0' 
'--filter-uom' '%' 
'--hostname' 'kom70-msa01.holding.com' 
'--http-backend' 'curl' 
'--username' 'monitor' '--password' 'myPWD' '--proto' 'https' 
'--use-new-perfdata'                                       

OK: All 2 components are ok [2/2 psu]. | 'hardware.psu.count'=2;;;;

```
At the same time, in fact, when polling power supplies, we have performance data related only to power supplies. Therefore, I suggested adding this data to this mode.

```
  <OBJECT basetype="power-supplies" name="power-supplies" oid="1" format="rows">
    ...
    <PROPERTY name="dc12v" type="uint32" size="8" draw="false" sort="string" display-name="12 Volt DC">1204</PROPERTY>
    <PROPERTY name="dc5v" type="uint32" size="8" draw="false" sort="string" display-name="5 Volt DC">508</PROPERTY>
    <PROPERTY name="dc33v" type="uint32" size="8" draw="false" sort="string" display-name="3.3 Volt DC">336</PROPERTY>
    <PROPERTY name="dc12i" type="uint32" size="8" draw="false" sort="string" display-name="12 Volt DC Current">881</PROPERTY>
    <PROPERTY name="dc5i" type="uint32" size="8" draw="false" sort="string" display-name="5 Volt DC Current">511</PROPERTY>
    ...
    <PROPERTY name="dctemp" type="uint32" size="8" draw="false" sort="string" display-name="PSU Temperature">27</PROPERTY>
    ...
    <OBJECT basetype="fan" name="fan-details" oid="2" format="rows">
      ...
      <PROPERTY name="speed" type="uint32" size="10" draw="true" sort="integer" display-name="Speed">377</PROPERTY>

```

**Comment by Aleksey-Maksimov** [comment]
Hey Quentin.
Can you add a perfdata output for power supplies?
