### ISSUE TITLE
[storage::hp::p2000::xmlapi::plugin] new mode request "controllers"

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2346]
Hello.

Could you please add new mode "**controllers**" to the plug-in for a more complete monitoring of **HP MSA P2000 G3** storage systems.

This mode is expected to provide extended information about the status of storage controllers and their subcomponents. 
Here information about performance will be available, which will make it clear how evenly the load is distributed between the controllers.

Controllers subcomponent status data : `/api/show/controllers`
Controllers performance data :               `/api/show/controller-statistics`

Useful properties of "/api/show/controllers":

OBJECT basetype="controllers"
-- PROPERTY name="durable-id"
-- PROPERTY name="description"
-- PROPERTY name="status" ("Operational" = OK)
-- PROPERTY name="health" ("OK" = OK, if not "OK" - show "health-reason" + "health-recommendation")
-- OBJECT basetype="network-parameters"
---- PROPERTY name="durable-id"
---- PROPERTY name="health" ("OK" = OK, if not "OK" - show "health-reason" + "health-recommendation")
-- OBJECT basetype="port"
---- PROPERTY name="durable-id"
---- PROPERTY name="target-id"
---- PROPERTY name="health" ("OK" = OK, if not "OK" - show "health-reason" + "health-recommendation")
--  OBJECT basetype="expander-ports"
---- PROPERTY name="durable-id"
---- PROPERTY name="name"
---- PROPERTY name="health" ("OK" = OK, if not "OK" - show "health-reason" + "health-recommendation")
--  OBJECT basetype="compact-flash"
---- PROPERTY name="durable-id"
---- PROPERTY name="name"
---- PROPERTY name="health" ("OK" = OK, if not "OK" - show "health-reason" + "health-recommendation")    

Useful properties of "/api/show/controller-statistics":

OBJECT basetype="controller-statistics"
-- PROPERTY name="durable-id"
-- PROPERTY name="cpu-load"
-- PROPERTY name="bytes-per-second-numeric"
-- PROPERTY name="iops"
-- PROPERTY name= *cache-hits
-- PROPERTY name="data-read-numeric" (delta)
-- PROPERTY name="data-written-numeric" (delta)

XML output in attachment: [controllers.zip](https://github.com/centreon/centreon-plugins/files/5531868/controllers.zip)

Thanks in advance

**Comment by Aleksey-Maksimov** [comment]
I will add documentation:

- [HPE_c02520779_HP P2000 G3 MSA System CLI Reference Guide.pdf](https://github.com/centreon/centreon-plugins/files/5532018/HPE_c02520779_HP.P2000.G3.MSA.System.CLI.Reference.Guide.pdf)
- [hpp2000g3arrayperformance.pdf](https://github.com/centreon/centreon-plugins/files/5532019/hpp2000g3arrayperformance.pdf)

**Comment by garnier-quentin** [comment]
Could you test the new mode ?

**Comment by Aleksey-Maksimov** [comment]
It works. Thanks, Quentin.

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin. I didn't find the (PROPERTY name="cpu-load") value. Is it not implemented? Can you add this?

**Comment by garnier-quentin** [comment]
You can test with last version (commit: de441cd5bf545596c71348bcf5167af970163205)

**Comment by Aleksey-Maksimov** [comment]
It works.
Quentin, thank you very much for your work.
 
![изображение](https://user-images.githubusercontent.com/17614847/133882236-eaa1eb46-fbe2-4585-b728-847747c84061.png)
