### ISSUE TITLE
Mellanox - request for new plugin

### ISSUE THREAD

**Issue by dalfo77** [centreon/centreon-plugins#2355]
It is possible to develop plugin for Mellanox devices?

Thanks,
Matteo.
[Mellanox Private MIBs.zip](https://github.com/centreon/centreon-plugins/files/5567662/Mellanox.Private.MIBs.zip)
[mellanox.snmpwalk.gz](https://github.com/centreon/centreon-plugins/files/5567664/mellanox.snmpwalk.gz)

**Comment by garnier-quentin** [comment]
I have looked MIB files but i didn't find useful information in your snmpwalk:
* storage: .1.3.6.1.4.1.33049.2.1.1.3
* cpu: .1.3.6.1.4.1.33049.2.1.1.4.1
* fanInventory, tempInventory

There is some stuff about QoS but i need the ifTable also. 

What do you want to monitor ?

**Comment by dalfo77** [comment]
Ciao, we actually monitor, and they are good for us:

- CPU
  - plugin=apps::protocols::snmp::plugin
  - dyn-mode=snmp_standard::mode::cpu
- Sensor
  - plugin=apps::protocols::snmp::plugin
  - dyn-mode=snmp_standard::mode::entity
- Traffic
  - plugin=apps::protocols::snmp::plugin
  - dyn-mode=snmp_standard::mode::interfaces
- Packet-Errors
  - plugin=apps::protocols::snmp::plugin
  - dyn-mode=snmp_standard::mode::interfaces

**Comment by garnier-quentin** [comment]
Ok. So you have used standard snmp monitoring. I close it.

**Comment by Bouyaka888** [comment]
Hi,
I don't know how it works so I'm updating this post.
Is it possible to have an official plugin for mellanox switches ? Do you need some information ?
In the mean time, how can I monitor my switches ? (cpu, memory, latency,traffic)

**Comment by garnier-quentin** [comment]
I need the snmpwalk for the following branch:  .1.3.6.1.4.1.33049

**Comment by Bouyaka888** [comment]
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/7821049/snmpwalk.txt)

In attachment the snmpwalk command. I'm not sure this is exactly what you asked for.
Let me know.

**Comment by garnier-quentin** [comment]
It's the standard mib. I need a snmpwalk of the specific entreprise branch: .1.3.6.1.4.1.33049

**Comment by Bouyaka888** [comment]
How can I get this ?

**Comment by garnier-quentin** [comment]
The command: ```snmpwalk -ObentU -v 2c -c public IP_ADDR .1.3.6.1.4.1.33049 > mellanox.snmpwalk

**Comment by Bouyaka888** [comment]
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/7821089/snmpwalk.txt)

Here it is.

**Comment by garnier-quentin** [comment]
Interesting OIDs (cpu, temp,...) are not present. So you should use the linux snmp plugin and test modes

**Comment by Bouyaka888** [comment]
You mean like Dalfo77 ?

I did not understand his last post :

CPU
plugin=apps::protocols::snmp::plugin
dyn-mode=snmp_standard::mode::cpu
Sensor
plugin=apps::protocols::snmp::plugin
dyn-mode=snmp_standard::mode::entity
Traffic
plugin=apps::protocols::snmp::plugin
dyn-mode=snmp_standard::mode::interfaces
Packet-Errors
plugin=apps::protocols::snmp::plugin
dyn-mode=snmp_standard::mode::interfaces

I understood that he used the "App-Protocol-SNMP" plugin 
![image](https://user-images.githubusercontent.com/78611263/148370116-147d2cc7-072a-4096-8894-2006db5820da.png)

But I don't understand what is "dyn-mode" ... ?

When I try to configure with the plugin, it is not working.

**Comment by garnier-quentin** [comment]
You can use the plugin os::linux::snmp::plugin directly.

**Comment by Bouyaka888** [comment]
Oh nice, it's working indeed (except for memory but i will do some research about this)
Thx !
