### ISSUE TITLE
Time out when using centreon-vmware plugins

### ISSUE THREAD

**Issue by waaalex** [centreon/centreon-plugins#2357]
Hello all,

I've got timeout when using centreon-vmware.
CENTOS 7
vcenter 6.7

`./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=xxxx --container=default --mode=getmap
UNKNOWN: Cannot get response (timeout received)`

When i launch daemon manually, i do not have any error message : 
`/usr/bin/perl /usr/bin/centreon_vmware.pl --logfile=/var/log/centreon/centreon_vmware.log --severity=info`

`2020-11-20 10:55:09 - Create vsphere sub-process for 'default'
2020-11-20 10:55:09 - [Server accepting clients]
2020-11-20 10:55:09 - 'default' init begin
2020-11-20 10:55:09 - 'default' init done
2020-11-20 10:55:09 - 'default' Vsphere connection in progress
2020-11-20 10:55:09 - 'default' Vsphere connection ok
2020-11-20 10:55:09 - 'default' Create perf counters cache in progress
2020-11-20 10:55:09 - 'default' Create perf counters cache done
`

All dependancies are installed, tested with read-only user and administrator@vsphere.local.
Can you help me?

**Comment by garnier-quentin** [comment]
Do you use following option: ```--connector-hostname=127.0.0.1``` (it's where vmware connector daemon is running)

**Comment by waaalex** [comment]
> Do you use following option: `--connector-hostname=127.0.0.1` (it's where vmware connector daemon is running)

Connetor hostname was my vcneter ^^ sorry.
It's works. Thank you very much. Case can be closed.

**Comment by garnier-quentin** [comment]
no problem. thanks for the feedback!
