### ISSUE TITLE
centreon_plugins.pl not working with perl connector

### ISSUE THREAD

**Issue by charles-martel55** [centreon/centreon-plugins#236]
Hi,

I add : use lib '/usr/local/lib/centreon-engine/plugins/centreon-plugins/'; in centreon_plugins.pl. https://github.com/centreon/centreon-plugins/issues/78

The perl connector working but command return : argument /usr/local/lib/centreon-engine/plugins/centreon-plugins/centreon_plugins.pl alone at /usr/local/lib/centreon-engine/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 92.

The command : /usr/local/lib/centreon-engine/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=$HOSTADDRESS$ (working in shell)

Centreon Perl Connector 1.1.2
Centreon Engine 1.4.15

**Comment by garnier-quentin** [comment]
Please use the last version. I have fixed it.

**Comment by charles-martel55** [comment]
It's working.

Thanks.

**Comment by PapaSchtrouuumpf** [comment]
Hi,

It looks like I have the same issue with : apps::tomcat::jmx::plugin.
I have the message : **argument http://dev.gdaprive.lan alone at /usr/lib/nagios/plugins/centreon-plugins-master/centreon/plugins/alternative/Getopt.pm line 92.**

The command is : ./centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --mode=cpu-load -url http://dev.gdaprive.lan

Thanks a lot !

PS : I have Centreon CES 3.3

**Comment by garnier-quentin** [comment]
i don't know the argument -url ? It's --url. Moreover http://dev seems alone in your command line.

**Comment by PapaSchtrouuumpf** [comment]
Of course i'm an idiot.. Thank you !

Now I have :UNKNOWN: Can't call method "is_error" on an undefined value at /usr/lib/nagios/plugins/centreon-plugins-master/centreon/common/protocols/jmx/custom/jolokia.pm line 204.

Looks like I forgot to configure something

**Comment by garnier-quentin** [comment]
Which version of JMX::Jmx4Perl have you installed ? Maybe the API has changed. What is your command line also exactly ?

**Comment by PapaSchtrouuumpf** [comment]
I have the 1.11-2 version of Jmx4Perl.

My command is : ./centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --mode=memory --url http://dev.gdaprive.lan

**Comment by garnier-quentin** [comment]
And the jolokia agent ?

**Comment by PapaSchtrouuumpf** [comment]
Installed on the server that I want to monitor ?
I will get this information as soon as I can :)

**Comment by garnier-quentin** [comment]
Exactly!
