### ISSUE TITLE
Max size for disk on RRD

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#2363]
Hi

Is it possible to show max value on rrd graph for a disk or memory. This value was present on output, see below, but not used ??,

Thanks,

OK: Storage 'C:' Usage Total: 19.66 GB Used: 16.33 GB (83.07%) Free: 3.33 GB (16.93%) | 'used'=17533091840B;~:18958249984;~:20031991808;0;**21105733632**

**Comment by garnier-quentin** [comment]
It s not a centreon plugins issue.
