### ISSUE TITLE
Error with empty custom macros

### ISSUE THREAD

**Issue by charles-martel55** [centreon/centreon-plugins#237]
Hi,

I have an error when I use empty custom macros in centreon command.

Use of uninitialized value $ARGV[1] in pattern match (m//) at /usr/local/lib/centreon-engine/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 61.

**Comment by garnier-quentin** [comment]
Hi,

Could you give me your command ?

**Comment by charles-martel55** [comment]
$USER1$/centreon-plugins/centreon_plugins.pl --hostname= $HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --plugin=$_SERVICEPLUGIN$ --mode=$_SERVICEMODE$ --warning=$_SERVICEWARNING$ --critical=$_SERVICECRITICAL$ $_SERVICEOPTIONS$

$_SERVICEOPTIONS$ is empty.

**Comment by garnier-quentin** [comment]
Could you give with macro expanded ?

**Comment by charles-martel55** [comment]
For example :

/usr/local/lib/centreon-engine/plugins/centreon-plugins/centreon_plugins.pl --hostname=host -snmp-version=2c --snmp-community=public plugin=os::windows::snmp::plugin --mode=memory --warning=80 --critical=90

But if I add a valid command to $_SERVICEOPTIONS$ it's working.

**Comment by garnier-quentin** [comment]
I need the command which gives you the error. When i execute it i don't have the error.

**Comment by charles-martel55** [comment]
I have an error only if I let the macro $_SERVICEOPTIONS$ empty.
That working too if I don't use the perl connector.

**Comment by garnier-quentin** [comment]
Really weird. Could you give me the command_line attribute from 'services' table in 'centreon_storage' table ? (from good service_id)

**Comment by charles-martel55** [comment]
I think that I found the problem.

The command line :

"/usr/local/lib/centreon-engine/plugins/centreon-plugins/centreon_plugins.pl --hostname=srv-veeam.nicomatic-hq.pri --snmp-version=2c --snmp-community=public --plugin=os::windows::snmp::plugin --mode=memory --warning=80 --critical=90 "

There is a space at the end of line, I think it cause the trouble.

**Comment by garnier-quentin** [comment]
I don't think so. When i execute it, it's ok. Could send me a email to do a teamwiever with you ?
