### ISSUE TITLE
os::linux::snmp::plugin problem with some disk mount size

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#2370]
Hi, 

I am trying to monitor some mounts on a linux server. the plugins works fine but for some mounts it does not get the correct size. 

I am getting this :
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=172.16.7.86 --snmp-version='2c' --snmp-community='public'  --storage='.*' --name --display-transform-src='' --display-transform-dst='' --warning-usage='80' --critical-usage='90' --verbose

Storage '/sbin' Usage Total: 129.66 GB Used: 16.15 GB (12.46%) Free: 113.51 GB (87.54%)
Storage '/usr' Usage Total: 129.66 GB Used: 16.15 GB (12.46%) Free: 113.51 GB (87.54%)
Storage '/etc/svc/volatile' Usage Total: 25.90 GB Used: 360.00 KB (0.00%) Free: 25.89 GB (100.00%)
Storage '/platform/sun4v/lib/libc_psr.so.1' Usage Total: 129.66 GB Used: 16.15 GB (12.46%) Free: 113.51 GB (87.54%)
Storage '/export/home/ora_arch/el/leg_prod/output_files/client_mail_non_envoye' **Usage Total: 232.92 GB Used: 685.93 GB (100.00%)** Free: 0.00 B (0.00%)
Storage '/export/home/ora_arch/el/leg_prod/output_files/client_mail_envoye' **Usage Total: 232.92 GB Used: 685.93 GB (100.00%)** Free: 0.00 B (0.00%)

With df -h command results are: 
df -h
Syst▒me de fichiers taille utilis▒ dispo capacit▒ Mont▒ sur
...
/sbin 130G 16G 114G 13% /sbin
/usr 130G 16G 114G 13% /usr
proc 0K 0K 0K 0% /proc
ctfs 0K 0K 0K 0% /system/contract
FR003-NAS:/FS_01/client_mail/client_mail_non_envoye
**4,2T 2,7T 1,6T 64% /export/home/ora_arch/el/leg_prod/output_files/client_mail_non_envoye**
FR003-NAS:/FS_01/client_mail/client_mail_envoye
**4,2T 2,7T 1,6T 64% /export/home/ora_arch/el/leg_prod/output_files/client_mail_envoye**

is there anything i am missing  ?

thank you

**Comment by garnier-quentin** [comment]
There is a limit. Try to use disk-usage mode maybe.

**Comment by saharawolf** [comment]
Hi, 
I try disk-usage but it does not work. 
my disk is only 4T, i do not get why it shows Usage Total: 232.92 GB Used: 685.93 GB (100.00%) 
It detect the total to be 232 GB ! i don't think that this is the limit size.

**Comment by garnier-quentin** [comment]
Could you provide following OIDs?
```
.1.3.6.1.2.1.25.2.3
.1.3.6.1.2.1.25.3.8
```

**Comment by UrBnW** [comment]
> I try disk-usage but it does not work.

You need the following in your `snmpd.conf` :
`includeAllDisks 0`
My 2 cents :)

**Comment by saharawolf** [comment]
hi, 
I have attached the results of the two oid

[1.3.6.1.2.1.25.2.3.txt](https://github.com/centreon/centreon-plugins/files/5588382/1.3.6.1.2.1.25.2.3.txt)
[1.3.6.1.2.1.25.3.8.txt](https://github.com/centreon/centreon-plugins/files/5588383/1.3.6.1.2.1.25.3.8.txt)

**Comment by garnier-quentin** [comment]
I have that:
```
HOST-RESOURCES-MIB::hrStorageDescr.28 = STRING: /export/home/ora_arch/el/leg_prod/output_files/client_mail_envoye
HOST-RESOURCES-MIB::hrStorageAllocationUnits.28 = INTEGER: 512 Bytes
HOST-RESOURCES-MIB::hrStorageSize.28 = INTEGER: 488473568
```

So: ```488473568 * 512 / 1024 / 1024 / 1024 = 232 GB```

**Comment by saharawolf** [comment]
So it means that it is an issue on server side ?
what should i look for?

**Comment by garnier-quentin** [comment]
Yes. I think it comes from net-snmp agent.
