### ISSUE TITLE
Send email alert when poller is down?

### ISSUE THREAD

**Issue by Cool34000** [centreon/centreon-plugins#2374]
Hi,

I'm using CENTREON in distributed mode.
I can't figure out how to send an email alert when a distant poller goes down.
The only alert I'm getting is in the web interface in the left top corner.

Is it possible? Am I using it the wrong way?

Thanks in advance

**Comment by Sims24** [comment]
Hey @Cool34000 

Definitely, you can use https://github.com/centreon/centreon-plugins/blob/master/apps/centreon/sql/mode/pollerdelay.pm 

This way, if the delay for the poller update is too big, you will trigger an alert ;)

**Comment by Cool34000** [comment]
Thank you @Sims24!

How am I supposed to use it?
I tried this:
`/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=database::mysql::plugin --dyn-mode=apps::centreon::sql::mode::pollerdelay --host=127.0.0.1 -verbose`
But it returns 

> OK: All poller delay for last update are ok

 while I have 1 poller down

**Comment by Cool34000** [comment]
Nevermind, I didn't see the warning/critical-delay!
