### ISSUE TITLE
network-checkpoint-snmp-mode-cpu/disk/memory

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#2378]
Il semblerait que pour le CPU vous faites de tests en considérant que le firewall possède plusieurs CPU via un get_table mais lorsque celui-ci n'a que un seul CPU le plugin tombe en timeout

 En  editant le fichier /usr/lib/centreon/plugins/centreon_checkpoint.pl (fonction get_table) à la Ligne 4093  et en mettant

my $vb = new SNMP::VarList([$1,$2],[$1,$2]);   au lieu de 
my $vb = new SNMP::VarList([$1,$2]);

 le plugin retourne une valeur et ne tombe plus en timeout.

 Pour info, il y a aussi le même problème sur la mémoire ou le disk.

Serait-il possible de gérer ce cas?

**Comment by garnier-quentin** [comment]
For mode cpu, we use following code:
```
my $oid_cputable = '.1.3.6.1.4.1.2620.1.6.7.5.1.5';
my $result = $options{snmp}->get_table(oid => $oid_cputable, nothing_quit => 1);
```

And in get table, we have that:
```
my $vb = new SNMP::VarList([$1, $2]);
```

It's a nonsense to change the code the way you did.

**Comment by garnier-quentin** [comment]
Please try with option --snmp-force-getnext

**Comment by apages2** [comment]
Bonjour,

je ne dit pas de changer le code comme je le propose, mais je constate qu'en le changeant comme je l'ai indiqué le plugin fonctionne.

j'ai deja tester l'option --snmp-force-getnext et cela ne change rien

**Comment by garnier-quentin** [comment]
And with --snmp-autoreduce option?

**Comment by apages2** [comment]
It’s ok with --snmp-autoreduce option

 

thanks

 

De : qgarnier <notifications@github.com> 
Envoyé : jeudi 26 novembre 2020 20:00
À : centreon/centreon-plugins <centreon-plugins@noreply.github.com>
Cc : apages2 <apages2@free.fr>; Comment <comment@noreply.github.com>
Objet : Re: [centreon/centreon-plugins] network-checkpoint-snmp-mode-cpu/disk/memory (#2378)

 

And with --snmp-autoreduce option?
