### ISSUE TITLE
network::h3c::snmp::plugin --threshold-overload

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#238]
Good morning,

If i want information about the option threshold-overload, i can see this in the help:

           --threshold-overload
            Set to overload default threshold values (syntax:
            section,status,regexp) It used before default thresholds (order
            stays). Example:
            --threshold-overload='psu,CRITICAL,^(?!(normal)$)'

But the example doesn't work. Instead of writing:
--threshold-overload='psu,CRITICAL,^(?!(normal)$)'
We must write:
--threshold-overload='psu,CRITICAL,normal'

**Comment by garnier-quentin** [comment]
Not the same thing. The example is: critical when it's not 'normal'. You write: critical when it's 'normal'.
