### ISSUE TITLE
[storage::qnap::snmp::plugin] mode=hardware - wrong behaviour when QNAP is scrubbing

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2395]
Plugins 20201008

If a QNAP is done a planned scrubbing job the plugin returns CRITICAL with Raid Synchronization. For QNAP scrubbing is not identified a error/problem.

QNAP screenshots:
![image](https://user-images.githubusercontent.com/6400595/100749437-f3285980-33e4-11eb-8570-e83f36a26109.png)
![image](https://user-images.githubusercontent.com/6400595/100749451-f7ed0d80-33e4-11eb-8190-0404847915c5.png)
![image](https://user-images.githubusercontent.com/6400595/100749478-ff141b80-33e4-11eb-8a01-12e1a9c0cd97.png)

Plugin Output:
![image](https://user-images.githubusercontent.com/6400595/100749513-0b987400-33e5-11eb-9e27-9cb7a05f25e8.png)

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of following OID when it's sync: .1.3.6.1.4.1.24681.1.4.1.1.1.2.1.2.1.5 ?
I will put it in WARNING or OK ?

**Comment by joschi99** [comment]
snmpwalk -v2c -cpublic x.x.x.x .1.3.6.1.4.1.24681.1.4.1.1.1.2.1.2.1.5
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.1.2.1.5.1 = STRING: "Synchronizing"

**Comment by garnier-quentin** [comment]
I put WARNING or OK for 'Synchronizing' ?

**Comment by joschi99** [comment]
Maybe a firmware problem? We try to update the firmware and we will check if problem persist.

**Comment by joschi99** [comment]
If you look on QNAP GUI this job is visualized with status OK, so there are no warnings or errors. It should be fine if plugin do the same I think.

**Comment by garnier-quentin** [comment]
ok i will update it.
