### ISSUE TITLE
[apps::protocols::x509::plugin] Does not support SNI

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#241]
Hello,

The X509 certificate check plugin does not seems to support SNI (when a server with only one public IP, handle 2 or more HTTPS vHost, without SNI only the default vHost is checked)

Net::SSLeat seems to be able to handle SNI : http://search.cpan.org/~mikem/Net-SSLeay-1.72/lib/Net/SSLeay.pod

Regards,

**Comment by Shini31** [comment]
Hello,

Can you try with this patch ? : https://github.com/Shini31/centreon-plugins/commit/f2cf0448f2b678c4641fbf81d1e145087793f43c

If it's ok for you, i will create the PR for the centreon-plugins repository.

Regards.

**Comment by fixlair** [comment]
Hello !

thanks but it does not seems to work. If you want I can send you in private on twitter URL to test

Legacy check : 
/check_http -H SITE1 --sni -C 10000,10000
CRITICAL - Certificate 'SITE1 ' expires in 741 day(s) (01/17/2018 23:59).
root@OUT-V-POL02:/usr/lib/nagios/plugins# ./check_http -H SITE2 --sni -C 10000,10000
CRITICAL - Certificate 'SITE2' expires in 676 day(s) (11/13/2017 23:59).

New Centreon Check : 
/centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=validity --hostname=SITE1 --validity-mode=expiration
OK: Certificate expiration days: 676 - Validity Date: Nov 13 23:59:59 2017 |

./centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=validity --hostname=SITE2 --validity-mode=expiration
OK: Certificate expiration days: 676 - Validity Date: Nov 13 23:59:59 2017 |


In My test Site1 is the defaut Site when SNI does not work (IE the first in alphabetic order on the Nginx server)

**Comment by Shini31** [comment]
Salut,

En fait le plugin est compatible avec n'importe quel protocole utilisant un certificat X509 comme SMTPS, IMAPS, POPS, etc. Il n'est pas donc pas spécifique à HTTPS et fait une résolution de nom sans prendre en compte le système de vhost.

D'ailleurs mettre 443 comme port par défaut n'est pas forcément une bonne idée.

++

**Comment by Shini31** [comment]
Hello,

Net::SSLeat is able to handle SNI only for server side : http://search.cpan.org/~mikem/Net-SSLeay-1.72/lib/Net/SSLeay.pod#Low_level_API:_Server_side_Server_Name_Indication_%28SNI%29_support
I continue to seek the best way to manage vhost

Regards

**Comment by Shini31** [comment]
Hello,

IO::Socket::SSL is able to handle SNI for client side since v1.56. 
But the current version in CentOS 6 (rpm) is v1.31

Regards.

**Comment by garnier-quentin** [comment]
Maybe we can do the code. It will work with good version of IO::Socket::SSL.

**Comment by Shini31** [comment]
Ok. The code is already done.
I'm doing some regression testing and I create the PR.

**Comment by garnier-quentin** [comment]
Ok. It needs to work with the version 1.31 of IO::Socket::SSL. Thanks.

**Comment by fixlair** [comment]
Great : just tested the patch proposed and work great (with IO Socket SSL in version greater than 1.56 (=1.76 in my test)) !

Thanks a lot !

**Comment by guillaumewatteeux** [comment]
Hi,

How to install supported version of perl-IO-Socket-SSL (1.56+) on CES 3.4.1 ?

(https://www.rpmfind.net/linux/RPM/centos/6.9/i386/Packages/perl-IO-Socket-SSL-1.31-3.el6_8.2.noarch.html)

```
# yum info perl-IO-Socket-SSL.noarch
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Installed Packages
Name        : perl-IO-Socket-SSL
Arch        : noarch
Version     : 1.31
Release     : 3.el6_8.2
Size        : 146 k
Repo        : installed
From repo   : anaconda-CES-201309230102.x86_64
Summary     : Perl library for transparent SSL
URL         : http://search.cpan.org/dist/IO-Socket-SSL/
License     : GPL+ or Artistic
Description : This module is a true drop-in replacement for IO::Socket::INET that
            : uses SSL to encrypt data before it is transferred to a remote server
            : or client. IO::Socket::SSL supports all the extra features that one
            : needs to write a full-featured SSL client or server application:
            : multiple SSL contexts, cipher selection, certificate verification, and
            : SSL version selection. As an extra bonus, it works perfectly with
            : mod_perl.
```
Regards

**Comment by garnier-quentin** [comment]
You need to download the tar.gz and compile it yourself.

**Comment by bmareau** [comment]
To install version 1.94

```
# yum install gcc openssl-devel

# wget https://cpan.metacpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.46.tar.gz
# tar xvf Net-SSLeay-1.46.tar.gz
# cd Net-SSLeay-1.46
# perl Makefile.PL
('y' to the question asked)
# make
# make install

Exit from directory 
​​​​​​​# cd /

# wget https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-1.94.tar.gz
# tar xvf IO-Socket-SSL-1.94.tar.gz
# cd IO-Socket-SSL-1.94
# perl Makefile.PL
# make
# make install
```
