### ISSUE TITLE
[new plugin] Ubiquiti Airfiber

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2425]
Could you create a plugin to monitor Ubiquiti Airfiber? It should be great to monitor if possible:
- CPU, Memory
- Hardware
- Signal quality
- Interfaces

[UBNT-MIB.txt](https://github.com/centreon/centreon-plugins/files/5679533/UBNT-MIB.txt)
[ubiquiti-airfiber-snmp-walk.txt](https://github.com/centreon/centreon-plugins/files/5679534/ubiquiti-airfiber-snmp-walk.txt)

**Comment by garnier-quentin** [comment]
Thanks. For memory and cpu, it seems to use FROGFOOT-RESOURCES-MIB. I don't find the hardware part in your snmpwalk.

**Comment by joschi99** [comment]
Looking the MIB file I can find also only status about the radios, so probably SNMP does not offer the general hardware status. I have done a look on the documentation and also the webinterface has no general hardware status:
![image](https://user-images.githubusercontent.com/6400595/101925537-3dbe8880-3bd2-11eb-8713-2e87724fe2f4.png)

**Comment by garnier-quentin** [comment]
You can test with plugin: network::ubiquiti::airfiber::snmp::plugin

**Comment by joschi99** [comment]
Thanks, is working
