### ISSUE TITLE
storage::synology::snmp::plugin (Testing nagios 4.4.6)

### ISSUE THREAD

**Issue by sistemmsn** [centreon/centreon-plugins#2427]
when I try to use storage mode it comes out:

 UNKNOWN: Cannot write statefile.

I am using nagios 4.4.6 working:
cpu
components
load
memory
swap
temperature
time
uptime

The ones that don't work are:

storage and interfaces

### working 

_cpu
components
load
memory
swap
temperature
time
uptime_

### not working 

****storage**
**interfaces****

[root@nagios centreon]#  _./centreon_plugins.pl --plugin=storage::synology::snmp::plugin --mode=storage   --host=192.168.1.15 --snmp-version=3 --snmp-username=nagios --authpassphrase=nagios123 --authprotocol=MD5 --privpassphrase=nagios123 --privprotocol=AES_

_UNKNOWN: Cannot write statefile '/var/lib/centreon/centplugins/cache_snmpstandard_192.168.1.15_161_storage'. Need write/exec permissions on directory._

### not required
_ha
ups_

[root@nagios centreon]#  ./centreon_plugins.pl --plugin=storage::synology::snmp::plugin --mode=load --host=192.168.1.15 --snmp-version=3 --snmp-username=nagios --authpassphrase=nagios123 --authprotocol=MD5 --privpassphrase=nagios123 --privprotocol=AES --warning=80 --critical=90
OK: Load average: 3.57, 3.44, 3.03 | 'load1'=3.57;0:80;0:90;0; 'load5'=3.44;;;0; 'load15'=3.03;;;0;

**Comment by garnier-quentin** [comment]
The message seems pretty clear. Have you needed permissions on '/var/lib/centreon/centplugins/cache_snmpstandard_192.168.1.15_161_storage' ? file and directories ?

**Comment by Sims24** [comment]
Hi, 

If you're running Nagios, you probably doesn't have the /var/lib/centreon/centplugins/ directory. You can customize the directory with the --statefile-dir option. For example --statefile-dir=/etc/nagios/ . 

The more straightforward way would be to use Centreon instead of Nagios, but that"s another story right ;)

**Comment by sistemmsn** [comment]
> excellent already worked for me.

Thanks a lot
> 
> Hi,
> 
> If you're running Nagios, you probably doesn't have the /var/lib/centreon/centplugins/ directory. You can customize the directory with the --statefile-dir option. For example --statefile-dir=/etc/nagios/ .
> 
> The more straightforward way would be to use Centreon instead of Nagios, but that"s another story right ;)

exceletne
