### ISSUE TITLE
apps :: protocols :: udp :: plugin --mode = connection returns OK on not existings ports or CRITICAL on existing ports

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#2436]
The apps :: protocols :: udp :: plugin --mode = connection plugin usually does not react as it should. I have host where snmp (port 161 udp) also works with the centreon snmp plugins but the plugin in critical connection failed on port 161.
In another case I can specify nonexistent ports and it's always OK

[root@rvvmpol07pl tmp]# perl /usr/lib/centreon/plugins/centreon_plugins.pl --hostname=172.27.112.14 --plugin=apps::protocols::udp::plugin --mode=connection --port=58555134348 --timeout=3
OK: Connection success on port 58555134348 |

I debugged it and if $new_readable is undefined then the plugin always answers with OK

![image](https://user-images.githubusercontent.com/46994680/102472691-d6338d80-4056-11eb-870e-2c03179ba099.png)

**Comment by garnier-quentin** [comment]
Have you tried with nmap ? I think it will see port open also
```
nmap -sU -p 161-170 10.30.2.91
```

**Comment by rmorandell-pgum** [comment]
yes i've tried with nmap. the port is open. And is working fine. The os-linux-snmp plugin ist working fine, too.

So in the other case the port 58555134348  doesn't exist

**Comment by garnier-quentin** [comment]
Ok i see :) I can check the port number

**Comment by rmorandell-pgum** [comment]
nmap -sU -p 161-170 192.168.10.9

Starting Nmap 6.40 ( http://nmap.org ) at 2020-12-17 11:39 CET
Nmap scan report for 192.168.10.9
Host is up (0.00023s latency).
PORT    STATE         SERVICE
161/udp open|filtered snmp
162/udp open|filtered snmptrap
163/udp open|filtered cmip-man
164/udp open|filtered smip-agent
165/udp open|filtered xns-courier
166/udp open|filtered s-net
167/udp open|filtered namp
168/udp open|filtered rsvd
169/udp open|filtered send
170/udp open|filtered print-srv

Nmap done: 1 IP address (1 host up) scanned in 1.60 seconds


 perl /usr/lib/centreon/plugins/centreon_plugins.pl --hostname=192.168.10.9 --plugin=apps::protocols::udp::plugin --mode=connection --port=161 --timeout=3
**CRITICAL: Connection failed on port 161 |**


 /usr/lib/centreon/plugins/fatpack/os-windows-snmp.pl --hostname=192.168.10.9 --snmp-community=****** --snmp-version=2c --snmp-timeout=2 --plugin=os::windows::snmp::plugin --mode=storage --name --regexp --storage=^C --warning-usage=90 --critical-usage=95 --units=% --display-transform-src='\\().*' --reload-cache-time=20
**OK: Storage** 'C:' Usage Total: 59.51 GB Used: 18.58 GB (31.22%) Free: 40.93 GB (68.78%) | 'count'=1;;;0; 'used'=19947376640B;0:57508308172;0:60703214182;0;63898120192

**Comment by garnier-quentin** [comment]
I don't have same issue. You receive a ICMP reponse.
