### ISSUE TITLE
mode=virus Can't locate network/fortinet/fortigate/plugin.pm in @INC 

### ISSUE THREAD

**Issue by oboutteville** [centreon/centreon-plugins#2439]
Hello, 
after update centreon from 19.10 to 20.10 the commande

 /usr/lib/centreon/plugins//centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=virus --hostname=nnn.nnn.nnn.nnn --snmp-version='2c' --snmp-community='com-ro'  --warning-virus-detected='1' --critical-virus-detected='2' --warning-virus-blocked='9' --critical-virus-blocked='10' --verbose    

Return  

 UNKNOWN: Cannot load module --plugin.                                                                                   Can't locate network/fortinet/fortigate/plugin.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::25357192=HASH(0x182eb88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins//centreon_fortinet_fortigate.pl line 3412.            [root@centreon ~]# --plugin=network::fortinet::fortigate::plugin --mode=virus 

What can i do ?
thank

**Comment by garnier-quentin** [comment]
You need to update the plugin also

**Comment by oboutteville** [comment]
I update it accros the centreon interface...
![image](https://user-images.githubusercontent.com/76163195/102493037-dccffe00-4072-11eb-936d-fabcd863031c.png)

**Comment by garnier-quentin** [comment]
You need to update rpm on your poller with yum for the plugin.

**Comment by oboutteville** [comment]
The pooler is in the same server as centreon.
Another test with fortinet work perfectly.
exemple : 
/usr/lib/centreon/plugins//centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::snmp::plugin --mode=vpn --hostname= nnn.nnn.nnn.Nnn --snmp-version='2c' --snmp-community='com-ro'  --filter-vdomain='' --filter-vpn='' --warning-users='' --critical-users='' --warning-sessions='' --critical-sessions='' --warning-tunnels='' --critical-tunnels='' --warning-traffic-in='' --critical-traffic-in='' --warning-traffic-out='' --critical-traffic-out='' 

OK: Virtual domain 'root' Logged users: 177, Active web sessions: 183, Active tunnels: 161

**Comment by garnier-quentin** [comment]
When i look the pack, i have for virus:
```
$CENTREONPLUGINS$/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::**snmp**::plugin --mode=virus --hostname='$HOSTADDRESS$' --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --filter-name='$_SERVICEFILTERNAME$' --warning-virus-detected='$_SERVICEWARNINGVIRUSDETECTED$' --critical-virus-detected='$_SERVICECRITICALVIRUSDETECTED$' --warning-virus-detected-psec='$_SERVICEWARNINGVIRUSDETECTEDPSEC$' --critical-virus-detected-psec='$_SERVICECRITICALVIRUSDETECTEDPSEC$' --warning-virus-blocked='$_SERVICEWARNINGVIRUSBLOCKED$' --critical-virus-blocked='$_SERVICECRITICALVIRUSBLOCKED$' --warning-virus-blocked-psec='$_SERVICEWARNINGVIRUSBLOCKEDPSEC$' --critical-virus-blocked-psec='$_SERVICECRITICALVIRUSBLOCKEDPSEC$' $_SERVICEEXTRAOPTIONS$
```

**Comment by oboutteville** [comment]
Ok, i fixe the problem. It was a custom template problem.
Thanks

**Comment by garnier-quentin** [comment]
thanks for the feedback
