### ISSUE TITLE
[os::linux::snmp::plugin] Load Average - graph only load1 on centreon

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#244]
Hello,

On my pretty old version of Centreon (2.3.9), when I set up the load check on Debian OS with your (great !) centreon-plugin check, only Load1 appear on graphs (instead of load1, load5 and load15).

Perfdata output seems to be good formed, even in Centreon : 

./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=XXX.XXX.XXX.XXX --snmp-version=2c --snmp-community=internal
OK: Load average: 0.00, 0.01, 0.05 | 'load1'=0.00;;;0; 'load5'=0.01;;;0; 'load15'=0.05;;;0;
![image](https://cloud.githubusercontent.com/assets/664748/11804815/dfefbe40-a306-11e5-8c10-44fdc716a00b.png)

But perfadata seems to be Ok 
![image](https://cloud.githubusercontent.com/assets/664748/11804858/4657022e-a307-11e5-958b-99195999147f.png)

Whereas with legacy check : 

./check_centreon_snmp_loadaverage -H XXX.XXX.XXX.XXX -v 2c -C internal
Load average: 0.00, 0.01, 0.05.|load1=0.00 load5=0.01 load15=0.05
![image](https://cloud.githubusercontent.com/assets/664748/11804824/f80f2dee-a306-11e5-8660-77360ebe41da.png)

![image](https://cloud.githubusercontent.com/assets/664748/11804882/8a2c040e-a307-11e5-9e1a-c9d5a6f17e01.png)

Do you have any idea ?

Regards,

**Comment by garnier-quentin** [comment]
It's a bug of centreon broker with threshold range. But you can use following option in the meantime:
--range-perfdata=1 
--range-perfdata=2

**Comment by fixlair** [comment]
Thanks Quentin, it may be me (I was not aware of test range-perfdata before) but it does not seems to change the perfdata output for this plugin : 
/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=XXX.XXX.XXX.XXX --snmp-version=2c --snmp-community=internal --range-perfdata=1 --range-perfdata=2
OK: Load average: 0.00, 0.01, 0.05 | 'load1'=0.00;;;0; 'load5'=0.01;;;0; 'load15'=0.05;;;0;

Or only with range-perfdata=1 that should remove the 0 
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=XXX.XXX.XXX.XXX --snmp-version=2c --snmp-community=internal  --range-perfdata=1
OK: Load average: 0.00, 0.01, 0.05 | 'load1'=0.00;;;0; 'load5'=0.01;;;0; 'load15'=0.05;;;0;

**Comment by garnier-quentin** [comment]
In your example, you have thresholds. That's the problem.
