### ISSUE TITLE
EMR monitoring issues

### ISSUE THREAD

**Issue by NicolasBlancoLopez** [centreon/centreon-plugins#2440]
Hello,
We are trying to monitor EMR clusters on AWS, but the problem is that these clusters raised and terminate multiple times during the day and the CloudWatch parameters for EMR need the JobFlowId dimension, which changes every time there is a new cluster.

So, if a cluster is terminated and another is raised, which has a different JobFlowID, it returns an UNKNOWN value in Centreon from the one that has terminated and I am not monitoring the one that was raised.

That is why I wanted to know if there is any plugin to avoid having to go directly through CloudWatch (such as for rds), or for example to be able to monitor it by the cluster name instead of the JobFlowId.

Could you help me?

Thanks in advance.

Kind regards.

**Comment by garnier-quentin** [comment]
It's not a direct issue of centreon-plugins. It's an issue about centreon and volatile monitoring.

**Comment by NicolasBlancoLopez** [comment]
OK, and where should I ask about this type of issue?

**Comment by garnier-quentin** [comment]
You won't get a short term solution. You need to find a way to monitor it with a stable information.

**Comment by garnier-quentin** [comment]
Maybe you can monitor it with centreon and sent it in influxdb for example (with centreon-broker stream connector). And after you can use grafana to manage datas.

**Comment by Sims24** [comment]
Hi @NicolasBlancoLopez , 

I think you can do this by using the --name flag of the AWS centreon_plugins. We introduced it recently.

Could you give us what metrics are relevant to you in this list https://docs.aws.amazon.com/emr/latest/ManagementGuide/UsingEMR_ViewingMetrics.html (Amazon EMR Metrics
)

Also, if you could send us by mail the output of: 

https://docs.aws.amazon.com/cli/latest/reference/emr/describe-cluster.html#examples

and highlights the field you want to use as a unique identifier that would be awesome. 

Thanks

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
