### ISSUE TITLE
os::linux::snmp::plugin Unknown SNMP Session : Unable to create 

### ISSUE THREAD

**Issue by NathanLCN** [centreon/centreon-plugins#2441]
Hello,

So i've got a little problem on supervising servers (VM on centOS 7/8) actually, some errors :

![image](https://user-images.githubusercontent.com/64141731/102510340-caac8a80-4087-11eb-8c92-ebbe14902f80.png)

But others thing works on that same server : 

![image](https://user-images.githubusercontent.com/64141731/102510968-866dba00-4088-11eb-9cea-1ab8f7116bae.png)

Why on that GUI it's not working but on CLI it does : 

![cli](https://user-images.githubusercontent.com/64141731/102599238-7d7af800-411d-11eb-9429-fe389e4cabc4.png)

I'm new on Centreon and i've tried many things but i cant get out of this. If any of you got any solutions to solve this :)

**Comment by garnier-quentin** [comment]
It's executed with centreon-engine user. Could you test with that user ?

**Comment by NathanLCN** [comment]
Excuse me, but how do I test with centreon-engine user? you want me to test it on the CLI ? to simulate the GUI working ?

**Comment by garnier-quentin** [comment]
On your server:
```
# su - centreon-engine
$ execute the command
```

**Comment by NathanLCN** [comment]
bash-4.2$ whoami
centreon-engine

bash-4.2$ perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --process-name='firewalld' --hostname=myHost.example.com --snmp-community=myCommunity --snmp-version=2c --critical=1:
OK: Number of current processes running: 1 | 'nbproc'=1;;1:;0;

**Comment by NathanLCN** [comment]
If the command works correctly as centreon-engine, why does it return an unknown / unable to create

**Comment by garnier-quentin** [comment]
It's not the same command used. What do you have in service details (centreon web interface) ?

**Comment by LemonLight** [comment]
Hello Quentin,

I work with Nathan.
The mistake comes from our side, in the command, the hostname was set with $HOSTNAME$ instead of $HOSTADDRESS$. 

Because of recent changes, in some case, the centreon hostname differs from the real hostname.

So fixed and closed ! Thanks for the highlight. Take care !

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
