### ISSUE TITLE
apps::backup::veeam::local::plugin - Argument "1608516601,557" isn't numeric in subtraction

### ISSUE THREAD

**Issue by ginjan** [centreon/centreon-plugins#2444]
Hello,

It appears that the problem with ticket # 1976 is not resolved.
I downloaded centreon nsclient 051 1.0 2 Win32 release date of "Dec. 21, 2020" and I have the same error: 
Argument "1608499185,07" isn't numeric in subtraction"

I  cannot fix the problem because i can't find the new binary .exe in repository.
The link is broken, I cannot use it. (https://github.com/centreon/centreon-nsclient-build/tree/master/resources/scripts/x64/centreon)

Can you help me.
Thank you in advance,

Best Regards,

**Comment by garnier-quentin** [comment]
Could you provide response of option --ps-exec-only ?

**Comment by ginjan** [comment]
Sorry but not. No in public.  There is confidential informations. 
Yes, by email if you wish.
How can I redirect the standard output in a file?

**Comment by garnier-quentin** [comment]
You can send it to me by email

**Comment by ginjan** [comment]
I have send the file in your mail.
For information, the 20201207190634 build at link https://github.com/centreon/centreon-nsclient-build/releases/tag/20201207190634 solve the problem.

Best regards.

**Comment by garnier-quentin** [comment]
thanks for the feedback. i close it
