### ISSUE TITLE
apps::backup::veeam::local::plugin - Ignore Jobs ( filter problem )

### ISSUE THREAD

**Issue by ginjan** [centreon/centreon-plugins#2449]
Hello,
I have jobs which are ignored by scripts. Apparently it is related to the "filter-end-time" option and the negative value which is return by Veeam. I don't know why the value is negative...

I have a doubt about the continuous backup jobs, but I cannot confirm it because I have a continuous backup job which is well recognized.

A example of return with "ps-only-exe" option for the tasks who are ignored :
{"type":51,"endTimeUTC":"-2208992400","creationTimeUTC":"1608606018,75","name":"CLIENT1","isRunning":true,"result":-1},
{"type":51,"endTimeUTC":"-2208992400","creationTimeUTC":"1608593612,857","name":"CLIENT2","isRunning":true,"result":-1},
{"type":51,"endTimeUTC":"-2208992400","creationTimeUTC":"1608595254,133","name":"CLIENT3","isRunning":true,"result":-1},
{"type":51,"endTimeUTC":"-2208992400","creationTimeUTC":"1608598840,793","name":"CLIENT4","isRunning":true,"result":-1},
{"type":51,"endTimeUTC":"-2208992400","creationTimeUTC":"1608598840,807","name":"CLIENT5","isRunning":true,"result":-1},
{"type":51,"endTimeUTC":"-2208992400","creationTimeUTC":"1608602432,297","name":"CLIENT6","isRunning":true,"result":-1},

I use NSClient-0.5.2.41-20201207-x64.exe.

Thank you for your help,
Best regard,

**Comment by garnier-quentin** [comment]
because the job is currently running ? So veeam push a negative value maybe

**Comment by garnier-quentin** [comment]
I think the following jobs are continuous type. a patch is coming.

**Comment by garnier-quentin** [comment]
[it should ok with last patch](https://github.com/centreon/centreon-plugins/pull/3581)
