### ISSUE TITLE
Cisco plugin mode=environment enhancement 

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#245]
Hi,

Can you please add enhancement to Cisco plugin environment mode. Right now if any of the modules fail it shows it nicely in output, for example: CRITICAL: Module Chassis 2 WS-X6724-SFP CEF720 24 port 1000mb SFP Rev. 5.0 status is poweredDown. 
Put it would be really good, if it also shows the slot number. Because sometimes there are several modules that have the same name and it would make it much faster to understand which slot has the problem.

**Comment by garnier-quentin** [comment]
What do you mean by the slot number ? I can have the physical index. But i don't find the slot number.

**Comment by kadrika** [comment]
Physical index would be fine, that is what I meant by slot.

**Comment by garnier-quentin** [comment]
You have it in verbose mode.

**Comment by kadrika** [comment]
Can you add it so that if there is critical issue it will show the index number without the --verbose?
