### ISSUE TITLE
MSA2050 : storage::hp::p2000::xmlapi::plugin --mode=vdisks , Error 500

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#2466]
Hello,

(sorry for my English :-)

We have MSA 2040 and 2050.
When we do the vdisks check on a msa 2040 everything is ok.
centreon_plugins.pl --hostname= --plugin=storage::hp::p2000::xmlapi::plugin --proto=http --username='...' --password="..." --mode="vdisks"

If we do the same for the MSA 2050 then we have the error 'UNKNOWN: 500 Server closed connection without sending any data back'

What I see is it tries with 'show vdisks' and if it doesn't work then het test with then 'show disk-groups' commando. (debug mode)
if I reverse the order in the file /storage/hp/p2000/xmlapi/mode/vdisks.pm (sub manage_selection) then the command 'show disk-groups' works for the msa 2050.

I think after the check 'show vdisks' he doesn't close the http connection before starting the 'show disk-group' commando.

is this possible ?

best regards.

**Comment by garnier-quentin** [comment]
Could you test with: ```--http-backend=curl --insecure``` ?

**Comment by gbin2265** [comment]
i am searching for Net::Curl::Easy on rhel 7.

UNKNOWN: Cannot load module 'Net::Curl::Easy'.
Can't locate Net/Curl/Easy.pm

**Comment by garnier-quentin** [comment]
Install the dep: ```yum install perl-Net-Curl```

**Comment by gbin2265** [comment]
Yes, after installing the perl-Net-Curl and add the parameter --http-backend=curl --insecure the vdisks mode works on the msa 2040 and 2050

I searched for this for 4 hours :-)

Best that I also use these parameters for the mode healt, components ... ???


Thanks !

**Comment by garnier-quentin** [comment]
Yes you can. Curl has better performance
