### ISSUE TITLE
Bee Ware > Deny All

### ISSUE THREAD

**Issue by kabreu** [centreon/centreon-plugins#2467]
Hello,

Bee Ware (I-Suite v5.6) doesn't exists anymore. It was bought in may 2014 by DenyALL (DenyAll v5.7 -> v6.4) which got bought by Rohde & Schwarz (v6.5) in June 2018.

Since the version 6.5 the plugin Bee Ware based on the oid branch :
.1.3.6.1.4.1.30800
Is not working anymore

Instead, it now uses the OID branch from DenyAll : 
1.3.6.1.4.1.18433

It could be interesting to develop a new plugin or update the Bee Ware one to accomodate this change.

MIB files : 
https://pastebin.com/UqX7kQJu
https://pastebin.com/H8C7J3em

Regards,

**Comment by garnier-quentin** [comment]
Il faudrait aussi le snmpwalk de la branche snmp.

**Comment by kabreu** [comment]
Sent by mail ;)

**Comment by garnier-quentin** [comment]
In the snmpwalk, i have found following informations:
- reverse-proxy: Could you ask values mapping for OID 'rpStatus' (because it's an integer:1, 2..)
- tunnels: same question for OID 'tunnelListenStatus'.
- load
- cpu
- filesystems
- memory

**Comment by kabreu** [comment]
1.3.6.1.4.1.18433.10.1.1.1.8.2.1.3 -> rpStatus (0: DOWN, 1: OK)

rpStatus OBJECT-TYPE
    SYNTAX  Integer32
    MAX-ACCESS  read-only
    STATUS  current
    DESCRIPTION "The current status of the reverse proxy"
    ::= { rpEntry 3 }

![image](https://user-images.githubusercontent.com/44901603/103407883-7cf05180-4b60-11eb-8bd2-9fa3495e9f82.png)


1.3.6.1.4.1.18433.10.1.1.1.10.1.1.3 -> tunnelListenStatus  (0: DOWN, 1: OK)

tunnelListenStatus OBJECT-TYPE
    SYNTAX  Integer32
    MAX-ACCESS  read-only
    STATUS  current
    DESCRIPTION "Tunnel listening status"
    ::= { tunnelEntry 3 }

![image](https://user-images.githubusercontent.com/44901603/103407892-82e63280-4b60-11eb-9be9-a90a51494594.png)

**Comment by garnier-quentin** [comment]
Thanks

**Comment by garnier-quentin** [comment]
Could you test with last master git ? That mode:
--plugin=network::denyall::snmp::plugin --mode=reverse-proxy
