### ISSUE TITLE
The centreon 2.7.0 using plugin pack does not work with perl connector

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#247]
I upgraded to version Centreon 2.7.0 this morning and I get lot of errors like that:
[1450354985] [12580] Error: Service check command execution failed: Connector 'Perl Connector' failed to restart
On command line plugin package commands are working but in the frontend I see only: (Execute command failed).
If I remove perl_connector from the command. it starts to work in Frontend also.

**Comment by garnier-quentin** [comment]
Please open it in centreon github. Thanks.
