### ISSUE TITLE
UNKNOWN: SNMP GET request : Timeout

### ISSUE THREAD

**Issue by MananTyagi** [centreon/centreon-plugins#2473]
![image](https://user-images.githubusercontent.com/63817084/103482540-6ddefd00-4e07-11eb-83b1-583d67ad4805.png)
I was using Vagrant as [https://zulip.readthedocs.io/en/latest/development/overview.html#recommended-setup-vagrant](Zulip development environment) . so I have setup vagrant development environment in my machine. it has already ngios for monitoring webapp. but I want to setupr centreon plugins. 
after connecting to the development server. i **just follow all the instructions as given in the documentation of this repo** and write **hostname as vagrant**. 
so it would be good if we configure timeout setting, may be by increasing the time will be helpful

**Comment by garnier-quentin** [comment]
I m not familiar with vagrant. Have you tried --snmp-autoreduce option?

**Comment by MananTyagi** [comment]
@garnier-quentin
first of all , thanks for your reply
 vagrant is used for managing virtual software development environment. [https://opensource.com/resources/vagrant](VAGRANT).
and I used it to manage my Oracle Virtualbox VM, which is served as my local development environment for ZULIP(open source team chat webapp).
zulip is already monitored by ngios but I came to this centreon-plugins integration which is compatible with nagios, so just follow the all given instructions given in this repo.
 And I am also new to centreon integerations.
please help me! 
it is my first project with zulip
thanks in advance

**Comment by MananTyagi** [comment]
> I m not familiar with vagrant. Have you tried --snmp-autoreduce option?

no I didn't tried it , but I will try it definitely

**Comment by MananTyagi** [comment]
maybe the problem is in " --hostname=vagrant"?

**Comment by garnier-quentin** [comment]
You need to set the hostname running snmp agent.

**Comment by MananTyagi** [comment]
> You need to set the hostname running snmp agent.

i used 127.0.0.1

**Comment by garnier-quentin** [comment]
I don't know. you can also try with snmpwalk command line.

**Comment by MananTyagi** [comment]
@garnier-quentin  hey thanks it works . issue was my SNMP server was misconfigured

**Comment by MananTyagi** [comment]
@should i made pull request so that I can state alterations, which a user have to do

**Comment by MananTyagi** [comment]
in documention

**Comment by garnier-quentin** [comment]
You can do a pull request yes.  and if it's ok, i merge it
