### ISSUE TITLE
linux::snmp::plugin --mode=processcount

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#2480]
Hi, 

Is there any possibility to reverse the threshold of processcount mode on linux::snmp::plugin ?
What i would like to have is keeping status OK when there is no process matching criteria and having critical status if process count is > 0

Thanks for the help

Regards

**Comment by UrBnW** [comment]
Simply use `--critical=0` ?

**Comment by garnier-quentin** [comment]
I think, it's like that: --critical=1:

**Comment by saharawolf** [comment]
I tested both --critical=0 and --critical=1: my check shows status OK when counted processes = 1
 " | OK: Number of current processes running: 1"

What i expect is : 
OK: Number of current processes running: 0
&
CRITICAL: Number of current processes running: 1 or more

Tnx

**Comment by garnier-quentin** [comment]
You can use the syntax of @UrBnW

**Comment by saharawolf** [comment]
centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=172.16.7.86 --snmp-community=SNMP  --snmp-version=2c --process-name=lpr --critical=0
OK: Number of current processes running: 1 | 'nbproc'=1;;0:;0;

Does not work
