### ISSUE TITLE
interface usage: return total bytes in/out

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2487]
It could be useful to return on interface usage the total traffic. This will allow to know how many bytes the interfaces received/sent. Maybe you can integrate an option that display this values on output (extended output) and maybe as performance data.

**Comment by garnier-quentin** [comment]
You can use following option:
```
--extend-perfdata-group=',all_traffic,sum(traffic_(in|out))'
```

**Comment by joschi99** [comment]
Hi @garnier-quentin,
maybe I was not able to explain my request. This option will sum traffic_in + traffic_out, but it should be nice to have traffic_in and traffic_out as total value (over all time) and not only as difference between last check and actual check.

**Comment by garnier-quentin** [comment]
That's not really how it works. You can use mode 'numeric-value' from snmp protocols.

**Comment by joschi99** [comment]
Hi Quentin,
I understand you and you are right that this information is not used actually for monitoring, but I think it could be useful to show on Status information also total values like this:
![image](https://user-images.githubusercontent.com/6400595/104024908-20c2a880-51c4-11eb-976a-2e5412822306.png)
This would allow to know how many traffic passed through a certain interface. If you have to pay the network traffic it could be a useful information.

**Comment by garnier-quentin** [comment]
I see. I can add something for that counter.

**Comment by garnier-quentin** [comment]
How do you want to manage counters rotating ? I could try check the rotation. But it will be infinite. You couldn't reset the counter.

**Comment by joschi99** [comment]
Hmm, I think this most simple solution would be to show the number from the counters, so we show only what SNMP will get back from interface. what do you think?

**Comment by garnier-quentin** [comment]
You can set following parameters: ```--units-traffic=[percent_delta|bps|counter]```
