### ISSUE TITLE
[ apps::protocols::http::plugin ] Output message for Timeout

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-plugins#2490]
Hi 

When the HTTP plugin goes in timeout, the message does not say so, it indicates instead that the test is wrong
Message is misleading :

`-bash-4.2$ /usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=maestro.hm.dm.ad --proto='https' --port='' --urlpath='/maestro-api/actuator/health' --expected-string='{"status":"UP"' --warning-time='8' --critical-time='10' --warning-content='' --critical-content='%{code} != 200' --unknown-content='' --unknown-status='' --warning-size='' --critical-size='' --proxyurl='' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --timeout=2
CRITICAL: Content test [filter: '%{content} !~ /{"status":"UP"/mi'] | 'size'=75B;;;0; 'time'=2.195s;0:8;0:10;0;`

In the example, it is the exceeding of the timeout (--timeout=2) that causes the critical, not a false test result (--expected-string='{"status": "UP").

In this case the check should exit in UNKNOWN with a message indicating that the timeout has been exceeded. 
UNKNOWN or CRITICAL is not very important but what is sure is that the message should indicate that the timeout has been exceeded.

Regards

**Comment by garnier-quentin** [comment]
It's how it should work. You can use ```unknown-status=''```.
