### ISSUE TITLE
[network::nokia::timos::snmp::plugin] Show optical ports, powers.

### ISSUE THREAD

**Issue by RubenJIF** [centreon/centreon-plugins#2497]
Hi,
Can you help me with the values of an optical port?. I´m trying  with --mode=interfaces, but it seems there is no option for show that. Im using a nokia router 7250.
My check is:
`perl centreon_plugins.pl --plugin=network::nokia::timos::snmp::plugin --mode=interfaces --hostname=x.x.x.x --snmp-version=2 --snmp-community=x --interface=129250105 `

but it only show: OK: Interface '1/4/13' Status: up  (admin:up)

Thanks for your time.

**Comment by garnier-quentin** [comment]
If you find snmp OIDs for optical power (dbm) and a snmpwalk, i could add it.

**Comment by RubenJIF** [comment]
I found integers oid for OutputPowers, it helps?

**Comment by garnier-quentin** [comment]
I need mibs files and snmpwalk of your equipment

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
