### ISSUE TITLE
[network::paloalto::snmp::plugin] GP-usage - Performance data globalprotect.tunnels.free.percentage showing used percentage

### ISSUE THREAD

**Issue by troja89** [centreon/centreon-plugins#2498]
I am having an issue with the GP-Usage performance data not having the correct labeling. 
The status information correctly shows: 

OK: tunnels total: 250 used: 10 (4.00%) free: 240 (96.00%)

But the performance data on the same service shows:
'globalprotect.tunnels.usage.count'=10;;;0;250
'globalprotect.tunnels.free.count'=240;;;0;250
'globalprotect.tunnels.free.percentage'=4.00%;0:90;0:95;0;100

It seems that the globalprotect.tunnels.free.percentage is actually showing the percentage of used tunnels instead.

The command I'm using is here:
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network/paloalto/snmp/plugin.pm --mode=gp-usage --hostname=xx.xx.xx.xx  --snmp-community=xxxx --snmp-version=2c --warning-tunnels-usage-prct=90 --critical-tunnels-usage-prct=95

**Comment by troja89** [comment]
This issue also seems to affect only some services using the command. Other services with the same command on the same problem display it correctly:

incorrect:
OK: tunnels total: 2048 used: 336 (16.41%) free: 1712 (83.59%)
'globalprotect.tunnels.usage.count'=336;;;0;2048
'globalprotect.tunnels.free.count'=1712;;;0;2048
'globalprotect.tunnels.free.percentage'=16.41%;0:90;0:95;0;100
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network/paloalto/snmp/plugin.pm --mode=gp-usage --hostname=xxxx --snmp-community=xxxx --snmp-version=2c --warning-tunnels-usage-prct=90 --critical-tunnels-usage-prct=95

vs

correct on the same poller:
OK: tunnels total: 2000 used: 0 (0.00%) free: 2000 (100.00%)
'globalprotect.tunnels.usage.count'=0;;;0;2000 
'globalprotect.tunnels.free.count'=2000;;;0;2000 
'globalprotect.tunnels.free.percentage'=0.00%;0:90;0:95;0;100
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network/paloalto/snmp/plugin.pm --mode=gp-usage --hostname=xxxx --snmp-community=xxxx --snmp-version=2c --warning-tunnels-usage-prct=90 --critical-tunnels-usage-prct=95

**Comment by garnier-quentin** [comment]
it's a mistake. it's used yes ;)
