### ISSUE TITLE
[plugin] AIX in SNMP does not return correct information for Aix 6.10 (state and amount of swap)

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#25]
Hi,

Data returned is not true for my AIX.

Here is the AIX version :

SNMPv2-MIB::sysDescr.0 = STRING: IBM PowerPC CHRP Computer
Machine Type: 0x0800004c Processor id: 00086A6AD400
Base Operating System Runtime AIX version: 06.01.0007.0015
TCP/IP Client Support version: 06.01.0007.0018

I always have a "warning : no active paging space", but on my AIX, I know that the page space is active via lsps -a :

Page Space Physical Volume Volume Group Size %Used Active Auto Type Chksum
hd6 hdisk3 rootvg 16384MB 1 yes yes lv 0

I know that the AIX specifications could be unclear, as mentionned in the comment :)

- Check if the paging space is active.
- Values are :
  1 = "active"
  2 = "notActive"
- On AIX 5.x it's ok. But in AIX 6.x, 7.x, it's the contrary ??!!!
  my $active_swap = 2;
  if ($results->{$oid_sysDescr}->{$oid_sysDescr . ".0"} =~ /AIX version: 05\./i) {
    $active_swap = 1;
  }
Can get a value by replacing "my $active_swap = 2;" by "my $active_swap = 1;" outside of the 'if' statement.

'page_space_hd6'=173140869B;0:155826782;0:164483825;0;17314086912

173140869
17179869184

As you can see, plugin return 173140869 but if we convert result from command line tools we get 16384 MB or 17179869184 B or my 16 GB of swap space :)

I put my walk here because can't fix right now but I'll throw a look soon.

SNMPv2-SMI::enterprises.2.6.191.2.4.2.1.1.1 = STRING: "hd6" 
[..]
SNMPv2-SMI::enterprises.2.6.191.2.4.2.1.4.1 = Gauge32: 16384
SNMPv2-SMI::enterprises.2.6.191.2.4.2.1.5.1 = INTEGER: 4
SNMPv2-SMI::enterprises.2.6.191.2.4.2.1.6.1 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.191.2.4.2.1.7.1 = INTEGER: 1
SNMPv2-SMI::enterprises.2.6.191.2.4.2.1.8.1 = INTEGER: 1

Thx

**Comment by quentinou** [comment]
I'm a little fed up of AIX SNMP swap activate :) I can't get it. For which versions i need to set the correct value: AIX or SNMP daemon ? Is it a bug of some versions ? I don't know.
