### ISSUE TITLE
Output Netapp plugin

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#250]
Je suis entrain de mettre en place le plugin pour le Netapp: File-System-Global. Et les output ne sont pas terrible. J'ai regardé la commande, et je n'arrive pas à avoir un joli Output avec les usage/inodes.

Soit je passe cette commande, et c'est pas beau!
./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname=172.20.101.215 --filter-name=/vol/xxx --filter-perfdata='used|inodes'
OK: All filesys usages are ok | 'used_/vol/xxx/'=10784145408B;;;0;13958643712 'inodes_/vol/xxx/'=0%;;;0;100

Soit avec le --verbose, comme dans le plugin de base, et l'information intéressante est à la fin...

./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname=172.20.101.215 --filter-name=/vol/xxx --filter-perfdata='used|inodes' --verbose
OK: All filesys usages are ok | 'used_/vol/xxx/'=10784145408B;;;0;13958643712 'inodes_/vol/xxx/'=0%;;;0;100
Skipping '/vol/qqqq/': no matching filter name.
Skipping '/vol/wwww/': no matching filter name.
Skipping '/vol/eeee/.snapshot': no matching filter name.
Skipping 'aggr_FC_BS': no matching filter name.
Skipping '/vol/rrrr/.snapshot': no matching filter name.
Skipping 'aggr_FC_BS/.snapshot': no matching filter name.
Skipping '/vol/ttttt/.snapshot': no matching filter name.
Skipping '/vol/zzzz/': no matching filter name.
Skipping '/vol/uuuu/.snapshot': no matching filter name.
Skipping '/vol/iiii/': no matching filter name.
Skipping '/vol/oooo/': no matching filter name.
Skipping '/vol/pppp/': no matching filter name.
Skipping '/vol/aaa/.snapshot': no matching filter name.
Skipping '/vol/ssss/': no matching filter name.
Skipping '/vol/dddd/': no matching filter name.
Skipping '/vol/ffff/.snapshot': no matching filter name.
Skipping '/vol/gggg/.snapshot': no matching filter name.
Skipping '/vol/hhhh/.snapshot': no matching filter name.
Skipping '/vol/jjjjj/': no matching filter name.
Filesys '/vol/xxx/' Total: 13.00 GB Used: 10.04 GB (77.26%) Free: 2.96 GB (22.74%), Inodes Used : 0 %
Filesys '/vol/xxx/.snapshot' skipping: total size is 0, Inodes : skipped (no value(s))

La phrase Filesys '/vol/xxx/' Total: 13.00 GB Used: 10.04 GB (77.26%) Free: 2.96 GB (22.74%), Inodes Used : 0 % devrait être affiché dans le output sur Centreon.

Est ce possible? merci beaucoup!

**Comment by garnier-quentin** [comment]
HI,

For that, you need to exclude the 'snapshot' filesystem (you have 2). That's why you don't have only one line: --filter-name='^/vol/xxx$'

**Comment by matthieu-robin** [comment]
Sorry Quentin, I misspoke.
When the status is ok, We don't see usage, inode. 
When the status is warning or Critical, we see the usage:
![cap 2015-12-21 a 10 01 02](https://cloud.githubusercontent.com/assets/10330979/11927056/e7592370-a7c9-11e5-85f3-afd1f0b81d19.png)

it could be fine to got the data into the OK message
Thanks

**Comment by garnier-quentin** [comment]
That's what i'm talking about ;) You need to filter with a regexp to check only 1 filesys (not 2).
