### ISSUE TITLE
[apps::protocols::snmp::plugin] Add and extra fixed value 

### ISSUE THREAD

**Issue by RubenJIF** [centreon/centreon-plugins#2503]
Hi, how can i get the min and max value from output. I don't know how to show in my graphs. 
example from:  apps::protocols::snmp::plugin --mode=numeric-value. I want to a max critical 242 and min critical 221. But it show just, warning=242 and value=223.  

output: 
OK: current value is 223 | 'value'=223;221:240;;221;242

The notification max and min warning are working.

Or how can i add and extra fixed value.

**Comment by garnier-quentin** [comment]
Could you provide the command line used ?

**Comment by RubenJIF** [comment]
Yes,
`--plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=$HOSTADDRESS$ --snmp-community=public --snmp-version=2c --oid='.1.3.6.1.4.1.12148.9.6.1.0'   --warning=221:242 --perfdata-min=221 --perfdata-max=224` 

It shows the max warning(242) in graph, but not the min(198).

**Comment by garnier-quentin** [comment]
Yes. centreon-ui doesn't manage range thresholds in graph viz. It's not a centreon-plugins issue.

**Comment by RubenJIF** [comment]
Ok thanks. And via plugin is there an option to add a fixed value to output? to use the lines as limitiers.

**Comment by garnier-quentin** [comment]
What do you mean by fixed value to output ?

**Comment by RubenJIF** [comment]
for example in output: 

OK: current value is 223 | 'value'=223;221:240;;221;242 'value-fixed'=221 'value2-fixed'=242

So i can graph them as limitiers.

**Comment by garnier-quentin** [comment]
You can explode the max value but not the min value.

**Comment by RubenJIF** [comment]
OK, thanks fo your time!
