### ISSUE TITLE
snmp: Enhancement to Add oid to plugin poolstatus.pm giving node or hostname

### ISSUE THREAD

**Issue by afvdba** [centreon/centreon-plugins#2507]
Thanks for using centreon-plugins! Please follow the indications shown below according to your issue and describe it in English.

## New Plugins and modes

To develop a Plugin/mode, we need the following:

* SNMP: MIBs files and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk)
from centreon_plugins.pl     
         centreon::plugins::script->new()->run();
from plugin.pl
       'pool-status'          => 'network::f5::bigip::snmp::mode::poolstatus'
/../../usr/lib/nagios/plugins/centreon-plugins/network/f5/bigip/snmp
   AvailState => { oid => '.1.3.6.1.4.1.3375.2.2.5.5.2.1.2', map => $map_pool_status },
        EnabledState => { oid => '.1.3.6.1.4.1.3375.2.2.5.5.2.1.3', map => $map_pool_enabled },
        StatusReason => { oid => '.1.3.6.1.4.1.3375.2.2.5.5.2.1.5' },
        AvailState => { oid => '.1.3.6.1.4.1.3375.2.2.5.1.2.1.18', map => $map_pool_status },
        EnabledState => { oid => '.1.3.6.1.4.1.3375.2.2.5.1.2.1.19', map => $map_pool_enabled },
        StatusReason => { oid => '.1.3.6.1.4.1.3375.2.2.5.1.2.1.21' },
    ltmPoolStatServerCurConns => { oid => '.1.3.6.1.4.1.3375.2.2.5.2.3.1.8' },
    ltmPoolActiveMemberCnt    => { oid => '.1.3.6.1.4.1.3375.2.2.5.1.2.1.8' },
    ltmPoolMemberCnt          => { oid => '.1.3.6.1.4.1.3375.2.2.5.1.2.1.23' },

* HTTP API (SOAP, Rest/Json, XML-RPC): the documentation and some curls examples
* CLI: command line examples
We look for OID to giv NodeName or HostName of the Node where the poolstatus is drawn via snmp:
I give example of AvailState from your plugin poolstatus.pm

[usr@host mode]# snmpwalk -v3 -u abcdefg -l Authpriv -a SHA -A auth-xyzabcd -x AES -X priv-blablabla 10.242.x.y-L o -t 200 .1.3.6.1.4.1.3375.2.2.5.5.2.1.2
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.24.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.71.87.69 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.24.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.88.83.82 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.25.47.66.65.83.69.90.79.78.69.50.47.80.76.95.66.90.50.95.84.66.73.110.116.114.97 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.25.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.66.101.115.115 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.25.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.84.114.111.108 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.26.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.68.80.70.71 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.26.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.68.80.73.83 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.26.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.68.83.77.70.69 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.26.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.69.66.77.111.98 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.26.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.76.111.103.105.110 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.27.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.71.79.112.101.110 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.27.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.69.105.112.67.111.109 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.27.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.78.105.109.98.117.115 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.27.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.76.111.103 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.27.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.84.66.65.117.116.104 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.28.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.65.84.77.72.111.115.116 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.28.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.117.116.104 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.28.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.83.105.103.110 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.28.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.80.73.66.90.95.83.121.115.76.111.103 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.29.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.71.67.108.111.115.101.100 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.29.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.69.66.77.111.98.83.101.99 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.29.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.69.66.80.117.98.83.101.99 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.29.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.76.111.103.105.110.65.100.118 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.29.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.73.110.98.111.120 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.29.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.80.97.114.116.121 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.29.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.84.101.108.101.108.105.110.107 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.30.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.84.66.65.117.116.104.65.84.77 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.30.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.84.66.65.117.116.104.66.77.87 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.30.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.84.66.65.117.116.104.77.111.98 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.65.112.105.71.97.116.101.119.97.121 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.71.79.112.101.110.95.83.83.79 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.69.70.77.95.82.83.84.80.87.68 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.72.82.45.77.97.105.108.95.50.53 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.67.111.110.116.97.99.116 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.67.111.117.112.111.110.115 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.77.101.110.117.95.56.48 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.101.115.115.105.111.110.65.112.105 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.31.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.84.66.65.117.116.104.67.117.115.116 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.32.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.68.97.116.97.83.116.111.114.97.103.101 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.32.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.72.82.45.77.97.105.108.95.53.56.55 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.32.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.72.111.109.101.98.97.110.107.79.98.115 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.32.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.70.80.95.79.112.101.110.95.87.84 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.32.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.99.99.111.117.110.116.115 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.32.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.76.111.103.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.32.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.83.105.103.110.95.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.70.105.114.99.111.115.111.102.116.65.80.73 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.80.77.67.83.45.77.97.105.108.95.50.53 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.70.80.95.79.112.101.110.50.95.87.84 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.99.99.101.115.115.95.56.48 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.117.116.104.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.117.116.104.95.56.52.52.52 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.73.110.118.101.115.116.95.56.48 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.77.101.110.117.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.83.105.103.110.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.33.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.83.105.103.110.95.56.52.52.52 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.34.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.71.79.112.101.110.95.83.83.79.67.67.82 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.34.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.70.80.95.67.108.111.115.101.100.95.87.84 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.34.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.73.110.98.111.120.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.34.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.73.110.115.105.103.104.116.95.56.48 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.34.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.80.97.114.116.121.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.35.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.65.112.105.71.97.116.101.119.97.121.95.69.77.80 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.35.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.70.80.95.67.108.111.115.101.100.50.95.87.84 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.35.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.99.99.101.115.115.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.35.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.99.99.101.115.115.95.56.52.52.52 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.35.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.73.110.118.101.115.116.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.35.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.80.114.111.100.117.99.116.115.95.56.48 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.35.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.83.101.116.116.105.110.103.115.95.56.48 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.36.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.67.111.110.116.97.99.116.95.56.52.52.51 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.36.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.67.111.117.112.111.110.115.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.36.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.73.110.115.105.103.104.116.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.37.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.111.109.112.111.115.101.114.71.119.67.108.111.115.101.100 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.37.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.65.99.99.111.117.110.116.115.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.37.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.80.114.111.100.117.99.116.115.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.37.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.83.101.116.116.105.110.103.115.95.56.52.52.51 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.37.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.111.114.114.121.80.97.103.101.115.95.49.48.48.56.50 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.37.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.111.114.114.121.80.97.103.101.115.95.49.48.52.52.50 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.37.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.87.101.98.100.97.118.66.101.69.120.116.114.97.110.101.116 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.38.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.116.97.116.105.99.73.110.116.101.114.110.101.116.65.100.118 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.39.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.111.109.112.111.115.101.114.71.119.79.112.101.110.95.83.83.79 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.40.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.111.114.114.121.80.97.103.101.115.65.100.118.95.49.48.48.56.50 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.41.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.67.117.115.116.111.109.101.114.82.101.112.111.114.116.105.110.103 = INTEGER: 1
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.42.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.67.111.109.112.111.115.101.114.71.119.79.112.101.110.95.83.83.79.67.67.82 = INTEGER: 3
SNMPv2-SMI::enterprises.3375.2.2.5.5.2.1.2.46.47.71.83.69.82.86.73.67.69.90.79.78.69.47.80.76.95.71.83.90.95.83.76.45.67.117.115.116.111.109.101.114.82.101.112.111.114.116.105.110.103.95.56.52.52.51 = INTEGER: 1
[usr@host mode]# pwd
/./../usr/lib/nagios/plugins/centreon-plugins/network/f5/bigip/snmp/mode
[usr@host mode]#

What we need is also the NodeName, thank you.

* SQL: requests
* JMX: mbean names and attributes

If some parts of information are confidentials, please send them directly by email to qgarnier@centreon.com and sbomm@centreon.com.

Please note that all the developments are open-source. We can't give a date for the development, achievement or release. If it's a priority for you,
send us an email about it (qgarnier@centreon.com and sbomm@centreon.com) and we'll put you in touch with our company.

**Comment by garnier-quentin** [comment]
I don't really understand what you need

**Comment by afvdba** [comment]
I need you to find an OID which gives NodeName and add it to the poolstatus.pm 👍

**Comment by afvdba** [comment]
Hi Quentin, 

We are missing a nodename or hostname in the poolstatus.pm plugin 

I tried to reproduce it at home, all I could find is this: 

root@opt1:/etc/snmp# snmpwalk -v3 -u adrie -l AuthPriv -a SHA -A
1234567890 -x AES -X 0987654321 -L o 192.168.0.1 iso.3.6.1.2.1.25 | grep
name
root@opt1:/etc/snmp# snmpwalk -v3 -u adrie -l AuthPriv -a SHA -A
1234567890 -x AES -X 0987654321 -L o 127.0.0.1 iso.3.6.1.2.1.25 | grep
hostname
iso.3.6.1.2.1.25.4.2.1.5.18338 = STRING: "--color=auto hostname"
iso.3.6.1.2.1.25.6.3.1.2.488 = STRING: "hostname-3.20"
iso.3.6.1.2.1.25.6.3.1.2.1554 = STRING:
"libnss-myhostname-237-3ubuntu10.43" 

However the customer is using other devices, so that tree did not go
there. 

You can see inside the poolstatus.pm plugin and see the OID's that are
queried.
Would be nice if you can add and OID that gives a NodeName or HostName. 

Hope this makes it clearer,
in any case I am at your disposal to explain further,no problem. 

Thanks in advance 

Frank 

On 13-01-2021 15:13, qgarnier wrote:

> I don't really understand what you need 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/centreon/centreon-plugins/issues/2507#issuecomment-759474628
[2]

**Comment by afvdba** [comment]
Hi Quentin,

Maybe I can add this about the poolstatus.pm
So, basically we want the NodeName for the F5 hardware , does that help you.
[root@sbelp11266]# /CPFS/NAGIOS/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin network::f5::bigip::snmp::plugin --mode pool-status --help

Plugin Description:
    Check F-5 hardware in SNMP. Please use plugin SNMP Linux for system
    checks ('cpu', 'memory', 'traffic',...).

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

    --pass-manager
            Use a password manager.

Output Options:
    --verbose
            Display long output.

    --debug Display also debug messages.

    --filter-perfdata
            Filter perfdata that match the regexp.

    --explode-perfdata-max
            Put max perfdata (if it exist) in a specific perfdata (without
            values: same with '_max' suffix) (Multiple options)

    --change-perfdata --extend-perfdata
            Change or extend perfdata. Syntax:
            --extend-perfdata=searchlabel,newlabel,target[,[newuom],[min],[m
            ax]]

            Common examples:

                Change storage free perfdata in used:
                --change-perfdata=free,used,invert()

                Change storage free perfdata in used:
                --change-perfdata=used,free,invert()

                Scale traffic values automaticaly:
                --change-perfdata=traffic,,scale(auto)

                Scale traffic values in Mbps:
                --change-perfdata=traffic_in,,scale(Mbps),mbps

                Change traffic values in percent:
                --change-perfdata=traffic_in,,percent()

    --extend-perfdata-group
            Extend perfdata from multiple perfdatas (methods in target are:
            min, max, average, sum) Syntax:
            --extend-perfdata-group=searchlabel,newlabel,target[,[newuom],[m
            in],[max]]

            Common examples:

                Sum wrong packets from all interfaces (with interface need
                --units-errors=absolute):
                --extend-perfdata-group=',packets_wrong,sum(packets_(discard
                |error)_(in|out))'

                Sum traffic by interface:
                --extend-perfdata-group='traffic_in_(.*),traffic_$1,sum(traf
                fic_(in|out)_$1)'

    --change-short-output
            Change short output display.
            --change-short-output=pattern~replace~modifier

    --range-perfdata
            Change perfdata range thresholds display: 1 = start value equals
            to '0' is removed, 2 = threshold range is not display.

    --filter-uom
            Filter UOM that match the regexp.

    --opt-exit
            Optional exit code for an execution error (i.e. wrong option
            provided, SSH connection refused, timeout, etc) (Default:
            unknown).

    --output-xml
            Display output in XML format.

    --output-json
            Display output in JSON format.

    --output-openmetrics
            Display metrics in OpenMetrics format.

    --output-file
            Write output in file (can be used with json and xml options)

    --disco-format
            Display discovery arguments (if the mode manages it).

    --disco-show
            Display discovery values (if the mode manages it).

    --float-precision
            Set the float precision for thresholds (Default: 8).

Snmp Options:
    --hostname
            Hostname to query (required).

    --snmp-community
            Read community (defaults to public).

    --snmp-version
            Version: 1 for SNMP v1 (default), 2 for SNMP v2c, 3 for SNMP v3.

    --snmp-port
            Port (default: 161).

    --snmp-timeout
            Timeout in secondes (default: 1) before retries.

    --snmp-retries
            Set the number of retries (default: 5) before failure.

    --maxrepetitions
            Max repetitions value (default: 50) (only for SNMP v2 and v3).

    --subsetleef
            How many oid values per SNMP request (default: 50) (for get_leef
            method. Be cautious whe you set it. Prefer to let the default
            value).

    --snmp-autoreduce
            Auto reduce SNMP request size in case of SNMP errors (By
            default, the divisor is 2).

    --snmp-force-getnext
            Use snmp getnext function (even in snmp v2c and v3).

    --snmp-username
            Security name (only for SNMP v3).

    --authpassphrase
            Authentication protocol pass phrase.

    --authprotocol
            Authentication protocol (MD5|SHA)

    --privpassphrase
            Privacy protocol pass phrase

    --privprotocol
            Privacy protocol (DES|AES)

    --contextname
            Context name

    --contextengineid
            Context engine ID

    --securityengineid
            Security engine ID

    --snmp-errors-exit
            Exit code for SNMP Errors (default: unknown)

Mode:
    Check Pools status.

    --filter-name
            Filter by name (regexp can be used).

    --unknown-status
            Set unknown threshold for status (Default: ''). Can used special
            variables like: %{state}, %{status}, %{display}

    --warning-status
            Set warning threshold for status (Default: '%{state} eq
            "enabled" and %{status} eq "yellow"'). Can used special
            variables like: %{state}, %{status}, %{display}

    --critical-status
            Set critical threshold for status (Default: '%{state} eq
            "enabled" and %{status} eq "red"'). Can used special variables
            like: %{state}, %{status}, %{display}

    --warning-* --critical-*
            Thresholds. Can be: 'current-server-connections',
            'current-active-members', 'current-total-members'.

[root@sbelp11266]#

**Comment by garnier-quentin** [comment]
Sorry but i don't understand. You want to filter on pool member node name ?
Could you provide following OID branches: .1.3.6.1.4.1.3375.2.2.4 and .1.3.6.1.4.1.3375.2.2.5 ?

**Comment by afvdba** [comment]
Hi, 
Yes sorry, I am new to this, it is not you :) Please bear with me, I try to learn fast here.
But I think you got it though. When you mean by to filter on pool node member node name => we get to see the underlying node name => then yes. That is what they want.

In our Infra there are multiple pool (members) and multiple nodes, and it is every time a puzzle when we get critical in Centreon where to start looking. You see where we are coming from ? It is like we only have half the puzzle :)

 
I have uploaded to log files with your request for the OID branches,
where .1.3.6.1.4.1.3375.2.2.4  : garnier-oid-lst1.log
and    .1.3.6.1.4.1.3375.2.2.5  :  garnier-oid-lst1.log

Thanks very much
Frank
[garnier-oid-lst1.log](https://github.com/centreon/centreon-plugins/files/5875816/garnier-oid-lst1.log)
[garnier-oid-lst2.txt](https://github.com/centreon/centreon-plugins/files/5875818/garnier-oid-lst2.txt)

**Comment by afvdba** [comment]
Hi,
Yes sorry, I am new to this, it is not you :) Please bear with me, I try to learn fast here.
But I think you got it though. When you mean by to filter on pool node member node name => we get to see the underlying node name => then yes. That is what they want.

In our Infra there are multiple pool (members) and multiple nodes, and it is every time a puzzle when we get critical in Centreon where to start looking. You see where we are coming from ? It is like we only have half the puzzle :)

I have uploaded to log files with your request for the OID branches,
[garnier-oid-lst1.log](https://github.com/centreon/centreon-plugins/files/5909880/garnier-oid-lst1.log)

where .1.3.6.1.4.1.3375.2.2.4 : garnier-oid-lst1.log
and .1.3.6.1.4.1.3375.2.2.5 : garnier-oid-lst1.log

Thanks very much
Frank
[garnier-oid-lst2.txt](https://github.com/centreon/centreon-plugins/files/5909878/garnier-oid-lst2.txt)

**Comment by qladriere** [comment]
Hello,

Still no news regarding this? Don't know if you understood what's needed as you didn't react yet. 
With current plugin version, we can see how much members in a pool are active or not but we can't see what's the name of the active/non-active member. Having some members down in a pool can be, in some cases, considered as "normal" but it can depends on which member is down.

Feel free to let us know if you need more info.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3954

Now you have members information in output (nodeName is displayed)

**Comment by nunomla** [comment]
Can we have the Node Member Connections in the Pool-Status?

**Comment by garnier-quentin** [comment]
What do you mean ? You have that kind of information in ```pool-status``` mode and ```node-status````

**Comment by nunomla** [comment]
Yes but in pool-status i have the sum of connections. The node-status give me the result I want but don't associate the Pool.
For example if i had a Pool with two nodes, i want to see the number of connections per node in that Pool
