### ISSUE TITLE
[apps::protocols::x509::plugin] no option to check via the proxy ?

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#2514]
Hello,

I want to check the certificate via a proxy.
I have used the proxyurl option but I get the error that this option does not exist.

centreon_plugins.pl --plugin="apps::protocols::x509::plugin" --mode=validity --validity-mode=expiration --port=443 --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE"  --hostname=<url> --proxyurl="http://x.x.x.x:8080" --warning-date="60:" --critical-date="30:"

Unknown option: proxyurl at gpi_plugin_centreon/centreon/plugins/alternative/Getopt.pm line 67.

Maybe there is another option that allows the check to be done via a proxy.
Or is there really no option provided?

regards,
Geert

**Comment by garnier-quentin** [comment]
Right now you cannot. You want to check a certificate of a website ? I need to do a plugin to check HTTP certificate with dump_peer_certificate i think.

**Comment by gbin2265** [comment]
Thank you for the reply.

We also want to check the certificate at website's that we have on external platforms like Azure.

Now that I know this I am going to install satellites in our DMZ to check directly.

I wanted to try to avoid this , placing additional satellites, but and I hope in the future to see the option that we can do the cheks through a proxy.

Thank you for all the good work ! 

I follow up github every day and will see if you add the functionality or not.

**Comment by garnier-quentin** [comment]
I have found how to do it with curl backend. But it won't work on centos 7 (curl lib is too old)
```
$self->curl_setopt(option => $self->{constant_cb}->(name => 'CURLOPT_CERTINFO'), parameter => 1);

#... perform check

my $certs = $self->{curl_easy}->getinfo($self->{constant_cb}->(name => 'CURLINFO_CERTINFO'));
use Data::Dumper; print Data::Dumper::Dumper($certs);
```

I try to find how to get it with lwp backend.

**Comment by garnier-quentin** [comment]
I have it for lwp. It likes a workaround because there is no public method to get it.
```
 use LWP::ConnCache;
 my $cache = LWP::ConnCache->new();
 $cache->total_capacity(1); # Cache up to 1 connections

 $self->{ua} = centreon::plugins::backend::http::useragent->new(
            conn_cache => $cache,
 );

 ...
 my ($con) = $cache->get_connections('https');
 use Data::Dumper;
 print Data::Dumper::Dumper($con->peer_certificate('authority'));
 print Data::Dumper::Dumper($con->peer_certificate('subjectAltNames'));
 print Data::Dumper::Dumper(Net::SSLeay::P_ASN1_TIME_get_isotime(Net::SSLeay::X509_get_notAfter($con->peer_certificate())));

**Comment by garnier-quentin** [comment]
Could you try with that archive ? 
https://github.com/centreon/centreon-plugins/archive/enh-x509.zip

And try with following command:
```
perl centreon_plugins.pl --plugin=apps/protocols/x509/plugin.pm --mode=certificate --hostname=www.google.fr --port=443 --custommode=https --proxyurl=http://proxyurl:3128
```

On centos 7, maybe you ll need to install following dependencies:
```
yum install perl-LWP-Protocol-connect
```

**Comment by gbin2265** [comment]
Hello,

Sorry for the late response !

I updated the plugins , install Perl-LWP-Protocol-connect and now I can also check the certificate through the proxy URL!

Thanks ! 

regards,
Geert

Thank you !

**Comment by garnier-quentin** [comment]
It was last week ;) Thanks for the feedback!

**Comment by garnier-quentin** [comment]
You need to use option: ```--custommode=https```

**Comment by hecko** [comment]
Many thanks!
