### ISSUE TITLE
Os::Windows::SNMP::Plugin Windows 2012 Fr Probleme Nom Service 

### ISSUE THREAD

**Issue by NathanLCN** [centreon/centreon-plugins#2516]
Hello there, 

I've got a litlle problem, I'm trying to supervise 2 windows 2012 r2 server (fr), all works, but few services return that : 
![2](https://user-images.githubusercontent.com/64141731/104727460-a7800400-5735-11eb-90dd-11309904ad75.png)
And on CLI : 
![1](https://user-images.githubusercontent.com/64141731/104727711-15c4c680-5736-11eb-904b-64fbc19583cb.png)
For english servers with same config, the ((\b'servicedisplayname'\b)) works perfectly.

Any advice ? 
Thanks for your help

**Comment by garnier-quentin** [comment]
Could you provide your command line and snmpwalk result by email ?

**Comment by garnier-quentin** [comment]
I have done an enhancement with last version. You can now use option for your case: ```--source-encoding=cp1252```
