### ISSUE TITLE
hardware::ups::standard::rfc1628::snmp::mode::batterystatus UNKNOWN: Can't use string after fix1568

### ISSUE THREAD

**Issue by Trunxsnot** [centreon/centreon-plugins#2517]
After Fix #1568 of package hardware::ups::standard::rfc1628::snmp::mode::batterystatus we get this:

[root@centreon02 centreon-plugins]# perl /usr/lib64/nagios/plugins/centreon_ups_standard_rfc1628_snmp.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --mode=battery-status --hostname=*** --snmp-version='1' --snmp-community='***' --snmp-autoreduce

UNKNOWN: Can't use string ("273") as a HASH ref while "strict refs" in use at /usr/lib64/nagios/plugins/centreon/plugins/snmp.pm line 901.

SNMPWALK results:

SNMPv2-SMI::mib-2.33.1.2.1 = INTEGER: 2
SNMPv2-SMI::mib-2.33.1.2.2 = INTEGER: 0
SNMPv2-SMI::mib-2.33.1.2.3 = INTEGER: 68
SNMPv2-SMI::mib-2.33.1.2.4 = INTEGER: 100
SNMPv2-SMI::mib-2.33.1.2.5 = INTEGER: 274
SNMPv2-SMI::mib-2.33.1.2.7 = INTEGER: 23

Before Fix #1568:

[root@centreon02 centreon-plugins]# perl /usr/lib64/nagios/plugins/centreon_ups_standard_rfc1628_snmp.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --mode=battery-status --hostname=10.83.0.41 --snmp-version='1' --snmp-community='sejescarcentreon' --snmp-autoreduce

OK: Battery status is normal - Charge remaining: 100% (66 minutes remaining) | 'load'=100%;;;0;100 'voltage'=27.4V;;;; 'temp'=23C;;;;

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of following branch ?
```
snmpwalk -ObentU -c sejescarcentreon -v 1 10.83.0.41 .1.3.6.1.2.1.33
```

**Comment by Trunxsnot** [comment]
[root@centreon02 ~]# snmpwalk -ObentU 10.83.0.41 -c sejescarcentreon -v 1
.1.3.6.1.2.1.33
.1.3.6.1.2.1.33.1.1.1 = STRING: "Delta"
.1.3.6.1.2.1.33.1.1.2 = STRING: "UPS102R2RT2B035 "
.1.3.6.1.2.1.33.1.1.3 = STRING: "0F0006AR00.02.00"
.1.3.6.1.2.1.33.1.1.4 = STRING: "01.12.18v"
.1.3.6.1.2.1.33.1.1.5 = ""
.1.3.6.1.2.1.33.1.1.6 = ""
.1.3.6.1.2.1.33.1.2.1 = INTEGER: 2
.1.3.6.1.2.1.33.1.2.2 = INTEGER: 0
.1.3.6.1.2.1.33.1.2.3 = INTEGER: 66
.1.3.6.1.2.1.33.1.2.4 = INTEGER: 100
.1.3.6.1.2.1.33.1.2.5 = INTEGER: 274
.1.3.6.1.2.1.33.1.2.7 = INTEGER: 23
.1.3.6.1.2.1.33.1.3.1 = INTEGER: 0
.1.3.6.1.2.1.33.1.3.2 = INTEGER: 1
.1.3.6.1.2.1.33.1.3.3.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.33.1.3.3.1.2.1 = INTEGER: 499
.1.3.6.1.2.1.33.1.3.3.1.3.1 = INTEGER: 226
.1.3.6.1.2.1.33.1.4.1 = INTEGER: 3
.1.3.6.1.2.1.33.1.4.2 = INTEGER: 499
.1.3.6.1.2.1.33.1.4.3 = INTEGER: 1
.1.3.6.1.2.1.33.1.4.4.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.33.1.4.4.1.2.1 = INTEGER: 230
.1.3.6.1.2.1.33.1.4.4.1.3.1 = INTEGER: 0
.1.3.6.1.2.1.33.1.4.4.1.4.1 = INTEGER: 91
.1.3.6.1.2.1.33.1.4.4.1.5.1 = INTEGER: 13
.1.3.6.1.2.1.33.1.5.1 = INTEGER: 499
.1.3.6.1.2.1.33.1.5.2 = INTEGER: 1
.1.3.6.1.2.1.33.1.5.3.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.33.1.5.3.1.2.1 = INTEGER: 224
.1.3.6.1.2.1.33.1.5.3.1.3.1 = INTEGER: 0
.1.3.6.1.2.1.33.1.5.3.1.4.1 = INTEGER: 0
.1.3.6.1.2.1.33.1.6.1 = INTEGER: 0
.1.3.6.1.2.1.33.1.7.1 = OID: .1.3.6.1.2.1.33.1.7.7.1
.1.3.6.1.2.1.33.1.7.3 = INTEGER: 1
.1.3.6.1.2.1.33.1.7.4 = STRING: "Not test yet."
.1.3.6.1.2.1.33.1.8.2 = INTEGER: 0
.1.3.6.1.2.1.33.1.8.3 = INTEGER: -1
.1.3.6.1.2.1.33.1.8.4 = INTEGER: 0
.1.3.6.1.2.1.33.1.8.5 = INTEGER: 1
.1.3.6.1.2.1.33.1.9.1 = INTEGER: 230
.1.3.6.1.2.1.33.1.9.2 = INTEGER: 500
.1.3.6.1.2.1.33.1.9.3 = INTEGER: 230
.1.3.6.1.2.1.33.1.9.4 = INTEGER: 500
.1.3.6.1.2.1.33.1.9.5 = INTEGER: 1000
.1.3.6.1.2.1.33.1.9.8 = INTEGER: 1
.1.3.6.1.2.1.33.1.9.9 = INTEGER: 100
.1.3.6.1.2.1.33.1.9.10 = INTEGER: 280

**Comment by garnier-quentin** [comment]
I didn't change the way it work. But i have harden the system. It should work.
