### ISSUE TITLE
[network::f5::bigip::snmp::plugin] add --mode=list-pool-members and pool-member-status

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#2519]
Hello, 

Is there a possibility to also provide the option LIST-POOL-MEMBERS and POOL-MEMBER-STATUS for the F5/BIGIP [network::f5::bigip::snmp::plugin].
I am based on the mib file F5-BIGIP-LOCAL-MIB.

You are using now for the list-pool and pool-status:
AvailState => { oid => '.1.3.6.1.4.1.3375.2.2.5.5.2.1.2', map => $map_pool_status },
EnabledState => { oid => '.1.3.6.1.4.1.3375.2.2.5.5.2.1.3', map => $map_pool_enabled },
StatusReason => { oid => '.1.3.6.1.4.1.3375.2.2.5.5.2.1.5' },

I Think for the list-pool-members and pool-member-status these are the OID's.
.1.3.6.1.4.1.3375.2.2.5.6.2.1.5 F5-BIGIP-LOCAL-MIB::ltmPoolMbrStatusAvailState
.1.3.6.1.4.1.3375.2.2.5.6.2.1.6 F5-BIGIP-LOCAL-MIB::ltmPoolMbrStatusEnabledState
.1.3.6.1.4.1.3375.2.2.5.6.2.1.8 F5-BIGIP-LOCAL-MIB::ltmPoolMbrStatusDetailReason

if you want to add this option, is it enough as information? 

regards,
Geert

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3954

Now you have members information in pool-status mode
