### ISSUE TITLE
[network::cisco::asa::snmp::plugin] mode memory get timeout

### ISSUE THREAD

**Issue by myOmikron** [centreon/centreon-plugins#2521]
## Bug/Question

We have a Cisco ASA 5545X and get a Timeout when using the memory mode, all other modes just work fine.

```
./centreon_plugins.pl --plugin network::cisco::asa::snmp::plugin --mode memory --hostname xxx.xxx.xxx.xxx --snmp-version 2c --snmp-community **************************
UNKNOWN: SNMP Table Request : Timeout
```

**Comment by Sims24** [comment]
Hi, 

What if you had these options: 

`--snmp-autoreduce --snmp-timeout=3`

**Comment by myOmikron** [comment]
`--snmp-autoreduce` has done the trick.

Thanks for the fast help!
