### ISSUE TITLE
[network::cisco::standard::snmp::plugin] mode=environment component=sensor

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#253]
Hello!
Apparently correctly extracts thresholds.
Example.
The resulting value:
CISCO-ENTITY-SENSOR-MIB::entSensorValue.1326 = INTEGER: -140 (dBm)
Threshold:
CISCO-ENTITY-SENSOR-MIB::entSensorThresholdValue.1326.3 = INTEGER: -144 (dBm)
CISCO-ENTITY-SENSOR-MIB::entSensorThresholdValue.1326.4 = INTEGER: -184 (dBm)

'sensor.dBm_TenGigabitEthernet1/50 Receive Power Sensor'=-14dBm;-14.39:0.39;-18.39:3.39;;

Thresholds 0.39 and 3.39 dBm are used in the graphs instead of -14.39 (warn) and -18.39 (crit).

Another small wish: with the possibility to add values sensor.rx_dBm and sensor.tx_dBm

**Comment by garnier-quentin** [comment]
That's a centreon-web issue. The web interface doesn't manage "complex" range.
