### ISSUE TITLE
Plugin storage restapi Problem DELL ME4 

### ISSUE THREAD

**Issue by NathanLCN** [centreon/centreon-plugins#2533]
Hello there, 

![image](https://user-images.githubusercontent.com/64141731/105378267-f03f2d80-5c0b-11eb-8ad3-66014ba2fb74.png)

As you can see, I made a filter to get only temp sensor, but when I wanna customize warning threshold and critical one, as it say on --help = 
     --warning
            Set warning threshold for 'temperature' (syntax:
            type,regexp,threshold) Example: --warning='temperature,.*,40'

    --critical
            Set critical threshold for 'temperature' (syntax:
            type,regexp,threshold) Example: --critical='temperature,.*,50'

Something wont work : wrong warning options :(

**Comment by garnier-quentin** [comment]
It's a mistake. It's sensor: --critical='sensor,.*,50'. You need to filter on a specific instance (id). Maybe i should do something like: 
--critical='sensor,temperature.*,50'
