### ISSUE TITLE
How to pass $value from --format-custom via web-ui

### ISSUE THREAD

**Issue by RubenJIF** [centreon/centreon-plugins#2534]
Hi, im triying to convert the value of an optical power to a dbm:
Mode: `[apps::protocols::snmp::plugin] --mode=numeric-value`
My oid output is an integer, example 1875 (Unit: Tenths of mw). So i convert it with 10*log(1875/10000), it gives me -7.23078867934226dbm.  In my code: (work in console)
`--format-custom='/$value*10*(log($value/10000)/log(10))'`
But when i print $value via web-ui it prints,
`--format-custom='/value/10000)/log(10))'
`
Can you help me to get or format the correct output?

**Comment by garnier-quentin** [comment]
Have you tried the syntax ``$$`` ?

**Comment by RubenJIF** [comment]
Thanks, it works!.

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
