### ISSUE TITLE
check active directory

### ISSUE THREAD

**Issue by trentasis** [centreon/centreon-plugins#2535]
Hi,

I'm trying to monitor active directory with latest version of centreon plugin, but always I recieve this error:

 perl centreon_plugins.pl --hostname=172.168.168.168 --plugin=apps::activedirectory::local::plugin --mode=dcdiag
UNKNOWN: Cannot load module --plugin.
Can't locate apps/activedirectory/local/plugin.pm in @INC (@INC contains: /tmp/test_centreon/centreon-plugins-master /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /tmp/test_centreon/centreon-plugins-master/centreon/plugins/misc.pm line 222.

I'm searching information about examples but I can't find, I'm not sure where is the issue, any suggestion?

Thanks

**Comment by garnier-quentin** [comment]
Now, the path is: apps::microsoft::activedirectory::local::plugin

**Comment by trentasis** [comment]
Thnaks now I receive this error:

# perl centreon_plugins.pl --hostname=172.168.168.168 --plugin=apps::microsoft::activedirectory::local::plugin --mode=dcdiag
UNKNOWN: Cannot load module --mode.
Can't locate Win32.pm in @INC (@INC contains: /tmp/test_centreon/centreon-plugins-master /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /tmp/test_centreon/centreon-plugins-master/apps/microsoft/activedirectory/local/mode/dcdiag.pm line 30.
BEGIN failed--compilation aborted at /tmp/test_centreon/centreon-plugins-master/apps/microsoft/activedirectory/local/mode/dcdiag.pm line 30.
Compilation failed in require at /tmp/test_centreon/centreon-plugins-master/centreon/plugins/misc.pm line 222.

**Comment by garnier-quentin** [comment]
It can only be used on windows server.

**Comment by trentasis** [comment]
from linux cannot be xecuted to monitor AD, any option?

**Comment by garnier-quentin** [comment]
If you have a way to monitor it, i could do it

**Comment by trentasis** [comment]
Sorry, I don't know only script vbs.
Thanks for all!
