### ISSUE TITLE
Socomec UPS: wrong handling when values are not set

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2540]
Socomec handles not managed values in a particular case:
![image](https://user-images.githubusercontent.com/6400595/105994391-dc7e4600-60a7-11eb-95e5-e1debfecd324.png)

So if we try to monitor socomec UPS with the hardware::ups::standard::rfc1628::snmp::plugin or also with hardware::ups::socomec::netvision::snmp::plugin the plugin return wrong values like
`OK: frequence: 6553.50 Hz - Input line '1' current: 65535.00 A, voltage: 235.00 V | 'lines.input.frequence.hertz'=6553.50Hz;;;; '1#line.input.current.ampere'=65535.00A;;;0; '1#line.input.voltage.volt'=235.00V;;;;
`

**Comment by garnier-quentin** [comment]
You can test with last version

**Comment by joschi99** [comment]
Hi @garnier-quentin,
this is a general rule, so you need also to change the other modes like battery and output-lines to respect them. For example battery mode shows:
`OK: battery status is charging - charge remaining: 100% (260 minutes remaining) | 'battery.charge.remaining.percent'=100%;;;0;100 'battery.charge.remaining.minutes'=260;;;0; 'battery.current.ampere'=6553.5A;;;0; 'battery.voltage.volt'=278.4V;;;;`

**Comment by joschi99** [comment]
Have done a quick test, but is not working as aspected:

```
 ./centreon_plugins.pl --plugin=hardware::ups::socomec::netvision::snmp::plugin --mode=input-lines --snmp-community=public 
 --hostname=x.x.x.x
OK: frequence: 6553.50 Hz - Input line '1' current: 65535.00 A, voltage: 239.00 V | 'lines.input.frequence.hertz'=6553.50Hz;;;; '1#line.input.current.ampere'=65535.00A;;;0; '1#line.input.voltage.volt'=239.00V;;;;
```

**Comment by garnier-quentin** [comment]
could you test with last version ?

**Comment by joschi99** [comment]
OK for:
```
--mode=battery
OK: battery status is charging - charge remaining: 100% (238 minutes remaining) | 'battery.charge.remaining.percent'=100%;;;0;100 'battery.charge.remaining.minutes'=238;;;0; 'battery.voltage.volt'=278.4V;;;;
```
```
--mode=output-lines
OK: Output source status is 'onInverter' - Output line '1' load: 11.00 %, current: 3.10 A, voltage: 229.00 V | '1#line.output.load.percentage'=11.00%;;;0;100 '1#line.output.current.ampere'=3.10A;;;0; '1#line.output.voltage.volt'=229.00V;;;;
```


Not OK for:
```
--mode=input-lines
OK: Input line '1' current: 65535.00 A, voltage: 237.00 V | '1#line.input.current.ampere'=65535.00A;;;0; '1#line.input.voltage.volt'=237.00V;;;;
```

**Comment by garnier-quentin** [comment]
It's weird. Could you provide snmpwalk of following OID: .1.3.6.1.4.1.4555.1.1.7.1.3.3.1.3 ?

**Comment by joschi99** [comment]
`SNMPv2-SMI::enterprises.4555.1.1.7.1.3.3.1.3.1 = INTEGER: 655350`

The Socomec documentation indicates:
General rule: In case **measurements not managed** by UPS the **related IOD value is set at -1
or 65535.**
https://www.socomec.com/files/live/sites/systemsite/files/UPS/tel-logiciel/netvision7/EN_NetVision7_Installation%20and%20Operating%20Manual_IOMNETV71017_EN_01_HD.pdf

**Comment by garnier-quentin** [comment]
Or 655350 :)

**Comment by garnier-quentin** [comment]
should be ok now

**Comment by joschi99** [comment]
Looks ok now for all modes :-)

**Comment by lucie-dubrunfaut** [comment]
Hello :)

A work had been done on an issue similar in december https://github.com/centreon/centreon-plugins/pull/4751 , we can try to add the same behavior in this case likewise.
