### ISSUE TITLE
[notification::microsoft::office365::teams::plugin] - custommode=webhookapi - UNKNOWN: Cannot decode json response

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2543]
Centreon Plugins 20210113

` ./centreon_plugins.pl --plugin=notification::microsoft::office365::teams::plugin --mode=alert --custommode=webhookapi --teams-webhook='https://pgum.webhook.office.com/webhookb2/66218451-74fd-478f-b827-1ab5841f5e54@db7b0272-7563-4cdc-ae28-4dad646e1b2a/IncomingWebhook/55bfccd7c1f9...' --host-name='Test'  --host-state='DOWN' --host-output='CRITICAL - Test: rta nan, lost 100%' --centreon-url='https://127.0.0.1/centreon' --action-links                        UNKNOWN: Cannot decode json response: JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at centreon-plugins-20210113/notification/microsoft/office365/teams/custom/webhookapi.pm line 94.`

**Comment by garnier-quentin** [comment]
Could you provide the result with --debug option ?

**Comment by joschi99** [comment]
UNKNOWN: Cannot decode json response: JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at /centreon-plugins-20210113/notification/microsoft/office365/teams/custom/webhookapi.pm line 94.
======> request send
POST https://pgum.webhook.office.com/webhookb2/66218451-74fd-478f-b8....
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/json

{"themecolor":"f21616","summary":"Centreon Alert","potentialAction":[{"targets":[{"uri":"https://127.0.0.1/centreon/main.php?p=20202&o=svc&host_search=Test-Jochen","os":"default"}],"name":"Details","@type":"OpenUri"}],"@context":"https://schema.org/extensions","sections":[{"facts":[{"value":"CRITICAL - Test-Jochen: rta nan, lost 100%","name":"Status"}],"activityTitle":"Host \"Test-Jochen\" is DOWN","activitySubtitle":""}],"@type":"MessageCard"}
======> response done
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Thu, 28 Jan 2021 11:25:10 GMT
Pragma: no-cache
Server: Microsoft-IIS/10.0
Content-Length: 1
Content-Type: text/plain; charset=utf-8
Expires: -1
Client-Date: Thu, 28 Jan 2021 11:25:10 GMT
Client-Peer: 40.101.46.18:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=DigiCert Inc/CN=DigiCert Cloud Services CA-1
Client-SSL-Cert-Subject: /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/CN=*.webhook.office.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Request-Id: 5868f115-b6f2-4f80-8338-e00920ceff99
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-AspNet-Version: 4.0.30319
X-BackEndHttpStatus: 200
X-BackEndHttpStatus: 200
X-BEServer: VI1PR05MB6879
X-CafeServer: VI1P194CA0009.EURP194.PROD.OUTLOOK.COM
X-CalculatedBETarget: VI1PR05MB6879.EURPRD05.PROD.OUTLOOK.COM
X-CalculatedFETarget: VI1P194CU001.internal.outlook.com
X-FEProxyInfo: VI1P194CA0009.EURP194.PROD.OUTLOOK.COM
X-FEServer: VI1P194CA0009
X-FEServer: DB6PR0202CA0029
X-Powered-By: ASP.NET
X-Proxy-BackendServerStatus: 200
X-Proxy-RoutingCorrectness: 1
X-RUM-Validated: 1

1

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by joschi99** [comment]
Now its working without warnings and errors, thanks

**Comment by garnier-quentin** [comment]
thanks for the feedback!
