### ISSUE TITLE
os::linux::local::plugin --mode=process shows wrong duration

### ISSUE THREAD

**Issue by angeleseros** [centreon/centreon-plugins#2544]
command:
centreon_plugins.pl --plugin=os::linux::local::plugin --mode='process'  --filter-command='cbd'

issue: 
- when process is running less than 1min the output duration will show the seconds as minutes... example **duration: 9m** for a process running for **9seconds**
- when process is running >=1min and < 1 hour the output duration will show seconds as minutes and minutes as seconds. example: **duration: 48m 3s** when the process is running for **3 mins 48secs**
- when process is running >=1 hour and < 1 day the output duration shows seconds in days, minutes in minutes, hour in days. example **duration: 5d 38m 1s** when the process is running for  **01hr 38mins 05 secs**
- when process is running >=1day the output will contain an error for example
     Argument "2-06" isn't numeric in addition (+) at /usr/lib/centreon/centreon-plugins-new/os/linux/local/mode/process.pm line 248.

**Comment by garnier-quentin** [comment]
Thanks for the issue. It should be fixed now
