### ISSUE TITLE
[plugin=database::oracle::plugin] mode tablespace --free

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#2545]
Hi,

I don't understand how --free works, or there is a bug.
The goal is to be able to get an alert on remaining disk space for large tablesspace.

Without the --free, no worries. my warning has 98%

/usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname="192.168.X.X" --port="1521" --sid="" --servicename="SID" --username="USERNAME" --password="PASSWORD" --mode="tablespace-usage" --warning-tablespace=98 --critical-tablespace= --filter-tablespace='^(TBL_DATABLOB)'  --notemp --units=%         
WARNING: Tablespace 'tbl_DATABLOB' Total: 2.18 TB Used: 2.14 TB (98.15%) Free: 41.30 GB (1.85%) | 'tbs_tbl_DATABLOB_usage'=2358081142784B;0:2354382597324;;0;2402431221760

With the --free, the result is OK, so you have to adapt the threshold in a different way, but how?

/usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname="192.168.X.X" --port="1521" --sid="" --servicename="SID" --username="USERNAME" --password="PASSWORD" --mode="tablespace-usage" --warning-tablespace=98 --critical-tablespace= --filter-tablespace='^(TBL_DATABLOB)'  --notemp --units=% --free
OK: Tablespace 'tbl_DATABLOB' Total: 2.18 TB Used: 2.14 TB (98.15%) Free: 41.30 GB (1.85%) | 'tbs_tbl_DATABLOB_free'=44350078976B;0:2354382597324;;0;2402431221760

I have tried several solutions, but I can't find them. I have the impression that the notion of inferior with the 2 points is not taken into account as for discs.

/usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname="192.168.X.X" --port="1521" --sid="" --servicename="SID" --username="USERNAME" --password="PASSWORD" --mode="tablespace-usage" --warning-tablespace=1 --critical-tablespace= --filter-tablespace='^(TBL_DATABLOB)'  --notemp --units=% --free  
WARNING: Tablespace 'tbl_DATABLOB' Total: 2.18 TB Used: 2.14 TB (98.15%) Free: 41.30 GB (1.85%) | 'tbs_tbl_DATABLOB_free'=44350078976B;0:24024312217;;0;2402431221760

/usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname="192.168.X.X" --port="1521" --sid="" --servicename="SID" --username="USERNAME" --password="PASSWORD" --mode="tablespace-usage" --warning-tablespace=2 --critical-tablespace= --filter-tablespace='^(TBL_DATABLOB)'  --notemp --units=% --free 
OK: Tablespace 'tbl_DATABLOB' Total: 2.18 TB Used: 2.14 TB (98.15%) Free: 41.30 GB (1.85%) | 'tbs_tbl_DATABLOB_free'=44350078976B;0:48048624435;;0;2402431221760

/usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname="192.168.X.X" --port="1521" --sid="" --servicename="SID" --username="USERNAME" --password="PASSWORD" --mode="tablespace-usage" --warning-tablespace=:2 --critical-tablespace= --filter-tablespace='^(TBL_DATABLOB)'  --notemp --units=% --free
OK: Tablespace 'tbl_DATABLOB' Total: 2.18 TB Used: 2.14 TB (98.15%) Free: 41.30 GB (1.85%) | 'tbs_tbl_DATABLOB_free'=44350078976B;0:48048624435;;0;2402431221760

Thanks,

**Comment by garnier-quentin** [comment]
For free, it should be like that (i think): ```--warning-tablespace=2:```

**Comment by romsworld** [comment]
👍 There are days... we forget everything!

Thank you!

**Comment by garnier-quentin** [comment]
No problem :)
