### ISSUE TITLE
Missing option --snmp-retries in centreon_linux_local.pl

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon-plugins#2551]
Hi,

```
$ time /usr/lib/centreon/plugins/centreon_linux_local.pl --plugin=os::linux::local::plugin --mode=discovery-snmp --subnet=10.230.88.0/24 --snmp-community=foo --snmp-version=2c --snmp-timeout=5 --snmp-retries=2
Unknown option: snmp-retries at /usr/lib/centreon/plugins/centreon_linux_local.pl line 141.
```

The option _--snmp-retries_ seems not to be supported while it’s shown in the help of the plugin.

How many retries are done in discovery-snmp mode ? Shouldn’t the option be supported as it appears in the help message ?

centreon-plugin-Operatingsystems-Linux-Local-20210113-100416.el7.centos.noarch

**Comment by garnier-quentin** [comment]
Yes indeed. i will fix the help to remove it.
