### ISSUE TITLE
Unknown option: snmp-username at /usr/lib/centreon/plugins//centreon_generic_snmp.pl line 375.

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon-plugins#2555]
Hi,

Trying to do a host discovery with SNMPv3 I spotted the following bug :

```
[me@server ~]$ /usr/lib/centreon/plugins//centreon_generic_snmp.pl --plugin=os::linux::local::plugin --mode=discovery-snmp --subnet=10.111.100.0/24 --snmp-version=3 --snmp-community=foo --snmp-username=bar
Unknown option: snmp-username at /usr/lib/centreon/plugins//centreon_generic_snmp.pl line 375.
```

(I know I miss some other options (like --authpassphrase and such) but this is just to illustrate the bug.)

Has SNMP discovery with SNMPv3 already been tested successfully once ?

Also, but it concerns the UI I think, if I add an extra option with simple quotes to the discover job, it warns me that there should not be ant simple quote there. But I have a ")" in my snmp password, so thoses quotes are mandatory. I also tried with a backslash in front of the "(" in the password, but I don’t know if it works because of the problème with --snmp-username described above. Do you know how I’m supposed to escape a character in the options for the discovery job ?

**Comment by garnier-quentin** [comment]
I didn't manage snmp v3 discovery by design.
