### ISSUE TITLE
[network::avaya::VSP7400::CPU::plugin] Request CPU and RAM plugins

### ISSUE THREAD

**Issue by puischevrier** [centreon/centreon-plugins#2557]
Hi,

I need to monitor Avaya's VSP7400 CPU and RAM.
Centreon said that there are currently no plugin to do that.

AFAIK, the OID are :

CPU Utilization: 1.3.6.1.4.1.2272.1.85.10.1.1.2.1 (rcKhiSlotCpuCurrentUtil)
Memory Utilization %: 1.3.6.1.4.1.2272.1.85.10.1.1.8.1 (rcKhiSlotMemUtil)

Regards,
HP
NB : snmpwalk sent separately (confidential informations)

**Comment by garnier-quentin** [comment]
Have you tried nortel plugin?

**Comment by puischevrier** [comment]
> Have you tried nortel plugin?
Hi,

I have tried :

centreon_nortel_standard_snmp.pl --plugin=network::nortel::standard::snmp::plugin --mode=cpu --hostname=***** --snmp-version='2c' --snmp-community='*****'  --warning-total='' --critical-total=''  --verbose

Here are the model I have used :

Net-Extreme-Cpu-SNMP-custom
Net-Extreme-Memory-SNMP-custom

Net-Nortel-Standard-Memory-SNMP-custom
Net-Nortel-Standard-Cpu-SNMP-custom

For each model, I get the following error :    
UNKNOWN: SNMP Table Request: Cant get a single value.

Regards

**Comment by garnier-quentin** [comment]
Indeed. I need to enhance the plugin. Thanks!

**Comment by garnier-quentin** [comment]
I have tried with github and it's working. Could you tried with github version ?
