### ISSUE TITLE
[apps::iis::local::plugin] critical status result bug

### ISSUE THREAD

**Issue by R00T88** [centreon/centreon-plugins#2558]
Hi all,
i'm using plugin apps::iis::local::plugin and found a possible bug on checking critical state for application pool state.
If application pool state on server it stopped it's return stopped in text but return OK as state

Command:
/usr/lib/nagios/plugins//check_centreon_nrpe3 -H xxx.xx.xx-p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state' '--filter-name="xx.xx"'

Result:
![image](https://user-images.githubusercontent.com/9050487/106434835-592b6e80-6472-11eb-8b5b-9ece036392e1.png)

If i force -critical-status parameters also will not work

 /usr/lib/nagios/plugins//check_centreon_nrpe3 -H xxx.xxx.xxx -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state' '--filter-name="xx.xx" -critical-status="%{auto_start} eq on"'

OK: Application pool 'xx.xx' state: started [auto: on] |

Thanks

**Comment by garnier-quentin** [comment]
Please use following syntax:
```
"%{auto_start} =~ /on/"
```

**Comment by R00T88** [comment]
Hi @garnier-quentin ,
same result

/usr/lib/nagios/plugins//check_centreon_nrpe3 -H xx.xx.it -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state' '--filter-name="xx.xx" -critical-status="%{auto_start} =~ /on/"'
OK: Application pool 'xx.xx' state: started [auto: on] |

**Comment by garnier-quentin** [comment]
Missing a ```-``` with critical-status

**Comment by R00T88** [comment]
Hi @garnier-quentin 
retested but same result

/usr/lib/nagios/plugins//check_centreon_nrpe3 -H xx.xxx.it -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state' '--filter-name="xx.xx" --critical-status="%{auto_start} =~ /off/"'
OK: Application pool 'formaweb.integrationwebapi' state: started [auto: on] |

/usr/lib/nagios/plugins//check_centreon_nrpe3 -H xx.xx.it -p 5666 -2 -P 8192 -n -c check_centreon_plugins -a 'apps::iis::local::plugin' 'applicationpool-state' '--filter-name="xx.xx" --critical-status="%{auto_start} =~ /on/"'
CRITICAL: Application pool 'xx.xx' state: started [auto: on] |

**Comment by garnier-quentin** [comment]
Have you tried with last plugin ? https://github.com/centreon/centreon-nsclient-build/releases/tag/20210119144023

**Comment by garnier-quentin** [comment]
Sorry. I have looked your filter/output and it seems ok. I don't see the issue.
