### ISSUE TITLE
Can't locate os/linux/local/mode/*.pm in @INC

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon-plugins#2563]
Hi,

Testing the NMAP discovering mode I spotted the following issue :

I’m able to list all the available modes :

```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_generic_snmp.pl --plugin=os::linux::local::plugin --list-mode

Plugin Description:
    Check Linux through local commands (the plugin can use SSH).
[…]
Modes Available:
   cmd-return
   connections
   cpu
   cpu-detailed
   directlvm-usage
   discovery-nmap
   discovery-snmp
   diskio
   files-date
   files-size
   inodes
   list-interfaces
   list-partitions
   list-storages
   load
   memory
   mountpoint
   ntp
   open-files
   packet-errors
   paging
   pending-updates
   process
   quota
   storage
   swap
   systemd-sc-status
   traffic
   uptime

```

But when I try to use one, it raises a Perl include error :

```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_generic_snmp.pl --plugin=os::linux::local::plugin --mode=uptime
UNKNOWN: Cannot load module --mode. 
Can't locate os/linux/local/mode/uptime.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::29916040=HASH(0x1c87b88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/centreon_generic_snmp.pl line 1133.

-bash-4.2$ /usr/lib/centreon/plugins/centreon_generic_snmp.pl --plugin=os::linux::local::plugin --mode=discovery-nmap
UNKNOWN: Cannot load module --mode. 
Can't locate os/linux/local/mode/discoverynmap.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::8919944=HASH(0x881b88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/centreon_generic_snmp.pl line 1133.
```

Surprisingly the mode “discovery-snmp” works fine :

```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_generic_snmp.pl --plugin=os::linux::local::plugin --mode=discovery-snmp
UNKNOWN: Need to specify --subnet option (<ip>/<cidr>). 
```
(it does work if I specify the _--subnet_ and SNMP options)

Maybe I miss a package but can’t figure out which one. This is what I have installed :

 - centreon-plugin-Operatingsystems-Linux-Ssh-20210113-100416.el7.centos.noarch
 - centreon-plugin-Operatingsystems-Linux-Local-20210113-100416.el7.centos.noarch
 - centreon-plugin-Operatingsystems-Linux-Snmp-20210113-100416.el7.centos.noarch
 - centreon-plugin-Applications-Protocol-Snmp-20210113-100416.el7.centos.noarch
 - centreon-plugin-Discovery-Nmap-20181019-1.el7.noarch
 - perl-Nmap-Parser-1.36-2.el7.noarch
 - nmap-6.40-19.el7.x86_64
 - centreon-release-20.10-2.el7.centos.noarch
 - centreon-clib-20.10.0-2.el7.centos.x86_64
 - centreon-engine-20.10.2-2.el7.centos.x86_64
 - centreon-engine-daemon-20.10.2-2.el7.centos.x86_64
 - centreon-engine-extcommands-20.10.2-2.el7.centos.x86_64
 - centreon-common-20.10.2-7.el7.centos.noarch
 - centreon-broker-20.10.3-5.el7.centos.x86_64
 - centreon-broker-cbmod-20.10.3-5.el7.centos.x86_64
 - centreon-broker-core-20.10.3-5.el7.centos.x86_64
 - centreon-broker-storage-20.10.3-5.el7.centos.x86_64
 - centreon-gorgone-20.10.2-1609852578.47515eb.el7.centos.noarch
 - centreon-connector-perl-20.10.0-2.el7.centos.x86_64
 - centreon-connector-20.10.0-2.el7.centos.x86_64
 - centreon-perl-libs-20.10.2-7.el7.centos.noarch
 - centreon-poller-centreon-engine-20.10.2-7.el7.centos.noarch

OS is an up-to-date CentOS 7

While writing this message I just noticed I can run the NMAP discovery another way, like this, calling another Perl script :

```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_linux_local.pl --mode=discovery-nmap
UNKNOWN: Need to specify --subnet option (<ip>/<cidr>).
```

I still don’t understand why it doesn’t work with the first script (_centreon_generic_snmp.pl_), as the help message clearly states that it should. 

 Any clue?

**Comment by garnier-quentin** [comment]
You wont have local uptime with snmp generic plugin. It s by design.

**Comment by garnier-quentin** [comment]
Why nmap would be in a snmp generic plugin ? nmap should be in a nmap plugin but we can't package it (because of the license: https://nmap.org/oem/)
