### ISSUE TITLE
SNMP IDRAC Filters on Voltage

### ISSUE THREAD

**Issue by NathanLCN** [centreon/centreon-plugins#2568]
Hello there, 

I've got a new question, I'm actually working on Dell idrac, making a filter for voltage (PSU1 and PSU2).
But it's an excluding filter, and I tough it was kinda bad to make 22 --filter='voltage,1.x' to get my 2 lines. 

My command : 
![commande voltage](https://user-images.githubusercontent.com/64141731/106874672-24b7ec80-66d6-11eb-800a-e26b6af9e13d.png)

Result : 
![voltage](https://user-images.githubusercontent.com/64141731/106874746-38fbe980-66d6-11eb-8327-34cf74a9c5dc.png)

**Comment by garnier-quentin** [comment]
You can use a negative regexp. It will work.

**Comment by NathanLCN** [comment]
So i've made that regexp but centreon refuse because of "!"and the "$" : ^((?!1.1|1.2).)*$
It works on CLI but not on GUI.

I understand the fact these are argument components but do you have any pro tips to give ?

**Comment by garnier-quentin** [comment]
If you put in a service macro it should be ok.
