### ISSUE TITLE
[apps::protocols::http::plugin] json-content

### ISSUE THREAD

**Issue by arnaudmichel31** [centreon/centreon-plugins#2573]
Hello Guys,

Maybe someone could help me.
I try this kind of request 

/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=json-content --hostname=127.0.0.1 --proto='http' --port='80' --header='centreon-auth-token: 'XXXX'' --header='Content-Type: application/json' --urlpath='/centreon/api/index.php?object=centreon_realtime_services&action=list'  --lookup="$.[?(@.service_id=="230")]"
UNKNOWN: Cannot lookup: non-safe evaluation, died at /usr/share/perl5/vendor_perl/JSON/Path.pm line 66. 

it seems to be a bug from JSON/Path.pm with the filter ...

Do you know a workaround ?

Thx in advance

**Comment by garnier-quentin** [comment]
Which version of your json path module ?

**Comment by arnaudmichel31** [comment]
Hello Quentin,

We have the 0.205 json path module. we will try to update. 

Thx a lot
