### ISSUE TITLE
Feature request: VMware plugin - Add multipathing monitoring

### ISSUE THREAD

**Issue by mickael-decastro** [centreon/centreon-plugins#2574]
Hello, 

It is can be a good thing to add multipathing, adapter and lun monitoring to the vmware plugin. These informations are very useful. 

Plugin  check_vmware_api.pl have this feature and provide following output 
```
2/8 adapters online, 10/10 LUNs ok, 31/31 paths active
``` 

Thanks 
Mickael

**Comment by garnier-quentin** [comment]
Need the vmware connector 3.2.2 and last centreon-plugins version for the mode 'storage-host'.
