### ISSUE TITLE
Update StoreOnce for new API

### ISSUE THREAD

**Issue by kabreu** [centreon/centreon-plugins#2575]
Hello,

Since firmware update 4.X, the API for StoreOnce changed a lot and some methods do not work anymore :

New API : 
https://hewlettpackard.github.io/storeonce-rest/index.html

Old one (3.X the plugin seems to be based on) : 
https://support.hpe.com/hpesc/public/docDisplay?docId=c04608993

For exemple the \*all* for /servicesets/ is not accepted anymore : 

/usr/lib/centreon/plugins//centreon_hp_storeonce_restapi.pl --plugin=storage::hp::storeonce::restapi::plugin --mode=fcs-usage --hostname='xxxxx' --username='xxxxx' --password='xxxxxx'  --filter-name='' --warning-status='%{is_online} == 1 and %{health} =~ /warning/i' --critical-status='%{is_online} == 1 and %{health} =~ /critical/i' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --debug

UNKNOWN: 400 Bad Request |

======> request send

GET https://xxxxxxxx:443/storeonceservices/cluster/servicesets/*all*/teaming/services/cat/stores
[...]
{"errors":[{"message":"Invalid SSID, it must be a positive integer.","resolution":"Provide a valid SSID, as a positive integer"}]}

The plugin should be updated or a new one created to follow this change.

Thanks.

**Comment by garnier-quentin** [comment]
The new plugin: https://github.com/centreon/centreon-plugins/pull/3682
