### ISSUE TITLE
Feature request : 3PAR perf statistics

### ISSUE THREAD

**Issue by Bouyaka888** [centreon/centreon-plugins#2576]
Hi,

Maybe I did not find the rigth plugins ... But it's impossible to have performance statistics on HP 3PAR storage.
I have it on Nimbles storage devices. And when I searching I can finding on other models of other constructors.
Nothing for 3PAR. IOPS and read/write input/output perf are the basics and main informations of storage device.
So, is that possible that the community could look en eye about this ?

Sorry, this is my first post I do not know how is work (I mean, github).

Thk you all,

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin.

I'm also interested in getting 3PAR performance statistics. I have several 3PAR 7200 storage systems and can help with experiments.

As far as I understand, through SSH we can get a lot of different useful statistics and significantly expand the functionality of the plugin. If we add advanced perfdata modes and a few additional monitoring modes, then centreon plugins will be best in class.

We can also consider the option of an additional plugin with obtaining some data for monitoring in JSON format via the WSAPI protocol in 3PAR. Here I am also ready to participate, provide documentation on the API, consider examples and help in testing.

**Comment by garnier-quentin** [comment]
If we can have optimal performance information with WSAPI, let's go :) But i need: 
* curl commands and results
* api documentation

**Comment by Aleksey-Maksimov** [comment]
Yes. I will give you all the information. 
Only probably it would be better to do a separate issues for each plugin and mode.

**Comment by garnier-quentin** [comment]
Put everything together ;)

**Comment by Aleksey-Maksimov** [comment]
**HPE 3PAR Web Services API (WSAPI)**

---
Authentication and obtaining a session key:

`# curl -k -H "Accept:application/json" -H "Content-Type:application/json" --data-binary {"user":"monitor","password":"myStr0ng!PWD"}' 'https://3par01.holding.com:8080/api/v1/credentials'`

Result:
 
`{"key":"0-8839f492dffe9eb701c2706169f8e62c-4e3bf161"}`

---

An example of requesting data using a session key:

`# curl -k -H "X-HP3PAR-WSAPI-SessionKey:0-8839f492dffe9eb701c2706169f8e62c-4e3bf161" 'https://3par01.holding.com:8080/api/v1/wsapiconfiguration'`

Result:

`{"httpState":"Disabled","httpPort":8008,"httpsState":"Enabled","httpsPort":8080,"version":"1.6.5","sessionsInUse":2,"systemResourceUsage":36,"sessionTimeout":15,"eventSessionsInUse":0,"maxEventSessions":5}`

---

Deleting a session key after polling the storage system is completed:

`# curl -k -X DELETE -H "Accept: application/json" https://3par01.holding.com:8080/api/v1/credentials/0-8839f492dffe9eb701c2706169f8e62c-4e3bf161`

---

Link to current documentation on HPE website: [HPE 3PAR Web Services API 1.6.15 Developer Guide
](https://support.hpe.com/hpesc/public/docDisplay?docId=c03606339)
File attached: [HPE_c03606339_HPE 3PAR Web Services API Developer's Guide.pdf](https://github.com/centreon/centreon-plugins/files/7947935/HPE_c03606339_HPE.3PAR.Web.Services.API.Developer.s.Guide.pdf)

There is also an interesting example of how WSAPI can be used: [hpe-storage/python-3parclient](https://github.com/hpe-storage/python-3parclient/blob/master/hpe3parclient)

**Comment by garnier-quentin** [comment]
Very nice. Could you also provide what you need and examples ? (like you did for hikvision nvr isapi)

**Comment by Aleksey-Maksimov** [comment]
I'm just working on this right now. But for now, I have a feeling that the maximum amount of performance information can only be obtained through SSH.

**Comment by Aleksey-Maksimov** [comment]
Therefore, I will ask you to make additional modes for SSH. To do this, I will create a separate issue for each such mode.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
