### ISSUE TITLE
Cisco-ASA VPN Traffic perfdata gathering not working

### ISSUE THREAD

**Issue by AndDeluiz** [centreon/centreon-plugins#2577]
Plugin:

- centreon-plugin-Network-Firewalls-Cisco-Asa-Snmp

Versions affected: 

- centreon-plugin-Network-Firewalls-Cisco-Asa-Snmp-20201211-091649.el7.centos.noarch
- centreon-plugin-Network-Firewalls-Cisco-Asa-Snmp-20210113-100416.el7.centos.noarch

Sympton:

After upgrading package centreon-plugin-Network-Firewalls-Cisco-Asa-Snmp-20201006-142255.el7.centos.noarch to affected version, traffic gathering for VPN traffic stopped working. Output is always "Buffer Creation".

Output for affected versions (running as centreon-engine user):

` /usr/lib/centreon/plugins/centreon_cisco_asa_snmp.pl --plugin=network::cisco::asa::snmp::plugin --mode=ipsec-tunnel --snmp-version='2c' --hostname=XX.XX.XX.XX --snmp-community='community'  --filter-name='IP.IP.IP.IP_IP.IP.IP.IP' --critical-tunnels-total=1:1
OK: Total Tunnels : 1 - Tunnel 'IP.IP.IP.IP_IP.IP.IP.IP' traffic-in : Buffer creation, traffic-out : Buffer creation, drop-in : Buffer creation, drop-out : Buffer creation, Total SA : 1 | 'total_tunnels'=1;;1:1;0; 'total_sa'=1;;;0;`

A downgrade to version 20201006-142255 solves this.

**Comment by garnier-quentin** [comment]
Thanks. It's fixed in last version. You can get the plugin in unstable repository. (i have also fixed a traffic error)
