### ISSUE TITLE
MSA2050 : storage::hp::p2000::xmlapi::plugin --mode=health set critical on count_disk and count_vdisk

### ISSUE THREAD

**Issue by TheBlaide** [centreon/centreon-plugins#2581]
Hello,

is it possible to set a critical threshold on count_disk and count_vdisk ?

Here is my output
/usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=storage::hp::p2000::xmlapi::plugin --hostname=1.1.1.1 --verbose --mode=health  --username=manage --password='***' --port=443 --proto=https --http-backend=curl --curl-opt="CURLOPT_SSL_VERIFYPEER => 0"  --component=disk --verbose
OK: All 51 components are ok [47/47 disks, 4/4 vdisks]. | 'count_disk'=47;;;; 'count_vdisk'=4;;;;

Ly array has a missing disk and should return a critical error .
The output should be

CRITICAL: 1 disk failed [47/48 disks, 4/4 vdisks]. | 'count_disk'=47;;;48; 'count_vdisk'=4;;;4;

I've tried with the following option with no luck:

--critical=count_disk,48

The array is a MSA 2500.

Regards,

Blaise

**Comment by garnier-quentin** [comment]
You can use that option: ```--critical-count-vdisk=48: --critical-count-disk=4:```

**Comment by TheBlaide** [comment]
Thanks a lot ! 

I didn't find this syntax in the module help ! ( based on git tag 20200410)

is it updated in the latest version ? 

Regards,

Blaise

**Comment by garnier-quentin** [comment]
Yes it's not in the help. We could add it indeed.
