### ISSUE TITLE
Pacemaker unable to ignore resources or set counter threshold

### ISSUE THREAD

**Issue by spiralemystik** [centreon/centreon-plugins#2588]
Hi,

The current plugin cannot ignore a resource, a status or an counter.

Example:
`-bash-4.2$ /usr/lib/centreon/plugins//centreon_pacemaker_ssh.pl --plugin=apps::pacemaker::local::plugin --mode=crm --hostname='10.10.41.17' --ssh-backend='libssh' --ssh-username='xxxx' --ignore-failed-actions='fence' --verbose
CRITICAL: Resource 'xxxx01' is stopped - Resource 'xxxx02' is stopped WARNING: xxxx01 failure detected, fail-count=1000000 - xxxx02 failure detected, fail-count=1000000 - xxxx01 failure detected, fail-count=1000000 - xxxx02 failure detected, fail-count=1000000 |
Resource 'lv_xxxxclusterdisk01' is started on node 'xxxx04'
Resource 'fs_xxxx04clusterdisk01' is started on node 'xxxx04'
Resource 'fence01' is stopped
Resource 'fence02' is stopped
Resource 'aaa14' is started on node 'xxxx04'
Resource 'bbb14' is started on node 'xxxx04'
Resource 'ccc14' is started on node 'xxxx04'
Resource 'ddd141' is started on node 'xxxx04'
Resource 'eee142' is started on node 'xxxx04'
Resource 'fff143' is started on node 'xxxx04'
Resource 'ggg144' is started on node 'xxxx04'
Resource 'hhh' is started on node 'xxxx04'`

Expected result:
Ignoring fence resources and set threshold on fail-count counter

**Comment by garnier-quentin** [comment]
I think i will update that mode.

**Comment by bmareau** [comment]
Hi
If we can add this enhancement request also :

> " In centreon_pacemaker_ssh.pl (line 554), you manage the case if only if the crm displays (unmanaged) FAILED as shown in your part of the code below : 
> ```
> elsif ($line =~ /\s*(\S+?)\s+ \(.*\)\:\s+\w+\s+\w+\s+\(unmanaged\)\s+FAILED/) {
> # Check Unmanaged
> $self->{output}->output_add(severity => 'CRITICAL',
> short_msg => "$1 unmanaged FAILED");
> }
> ```
> But I have an application that displays the following state in my crm :
> ```
> postgresql-9.4 (lsb:postgresql-9.4): FAILED sofit-pgsql1.grdf.fr (unmanaged)
> ```
> FAILED at the beginning and then (unmanaged) at the end is not managed by the plugin. In your plugin it is (unmanaged) at the beginning and then FAILED at the end.

Regards

**Comment by garnier-quentin** [comment]
You can test with last git version. Now there are many more options!
