### ISSUE TITLE
UNKNOWN: Cannot get counter 'disk.numberRead.summation' for the sampling period '300' (counter level: 3, sampling level: 1) |

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon-plugins#259]
Lors de l'exécution de cette commande
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=datastore-iops --custommode=connector --connector-hostname='127.0.0.1' --datastore-name='.*' --filter --disconnect-status='ok' --verbose

J'obtiens ce message UNKNOWN.
UNKNOWN: Cannot get counter 'disk.numberRead.summation' for the sampling period '300' (counter level: 3, sampling level: 1) |

VMware 5.5 u2.

**Comment by garnier-quentin** [comment]
Please open it in centreon-vmware project. The message is clear. You need to change the sampling period with good option. Use --help for that. Or you can change your vcenter configuration to have the counter for the sampling period.
