### ISSUE TITLE
[apps::protocols::tcp::plugin] Add New mode - TCP Connection refused

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#2594]
Like the basic check_tcp (https://nagios-plugins.org/doc/man/check_tcp.html) it would be great to have an option "refuse"

Here is an extract of the description of the option in this check : 

-r, --refuse=ok|warn|crit
    Accept TCP refusals with states ok, warn, crit (default: crit)

On the centreon plugin check (last version) right now I only get : 

"CRITICAL: Connection failed on port 3100 : Connection refused |" 
but in this specific situation I would like to be able to set it "OK" with an option (it's not a timeout, the application respond but refused the connection)

Thanks !

**Comment by garnier-quentin** [comment]
You can use following option with last git version:
```
--critical-status='%{status} eq "ok"'
```

**Comment by fixlair** [comment]
Oh :) Thanks !  
Nice idea to simply make add to this check standard critical filter to offer flexibility !
I will test it !
