### ISSUE TITLE
Ubiquiti Unifi Controler - request for new plugin

### ISSUE THREAD

**Issue by titi234** [centreon/centreon-plugins#2604]
Hello the community,
is it possible to develop a plugin for Ubiquiti Unifi Controler ?
at least to have the status of the AP.

Thanks
Guillaume

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk and mibs please?

**Comment by titi234** [comment]
attached a controller snmpwalk and an AP snmpwalk and the MIBs

[UBNT-MIB.txt](https://github.com/centreon/centreon-plugins/files/6027350/UBNT-MIB.txt)
[UBNT-UniFi-MIB.txt](https://github.com/centreon/centreon-plugins/files/6027351/UBNT-UniFi-MIB.txt)
[ap.txt](https://github.com/centreon/centreon-plugins/files/6027352/ap.txt)
[controller.txt](https://github.com/centreon/centreon-plugins/files/6027353/controller.txt)

**Comment by titi234** [comment]
I have more response with getif but I can't export the result

**Comment by garnier-quentin** [comment]
snmpwalk is not complete. Please provide with following syntax:
snmpwalk -ObentU -v 2c -c public IP .1 > ubiquiti.snmpwalk

**Comment by titi234** [comment]
thanks for the command, attached the result
[ubiquiti.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/6029131/ubiquiti.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
It's missing the entreprise branch: .1.3.6.1.4.1.41112

**Comment by titi234** [comment]
I must do snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.41112 to obtain it

[ubiquiti.41112.txt](https://github.com/centreon/centreon-plugins/files/6029163/ubiquiti.41112.txt)

**Comment by titi234** [comment]
there is nothing
I had do this snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.41112 and the result is:
.1.3.6.1.4.1.41112 = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by garnier-quentin** [comment]
I don't find the AP status in the mib file. Only some informations about interfaces (radio)

**Comment by titi234** [comment]
oh that's bad

I have find an another way to have what I want, if I can ping the AP and I do an snmp request and have no snmp response, the AP is not connected to the controller

**Comment by garnier-quentin** [comment]
Maybe i have tell you shit. Could you tell me if following tables is for AP ? ```unifiVapTable```
We get following values:
```
.1.3.6.1.4.1.41112.1.6.1.2.1.7.1 = STRING: "ath0"
.1.3.6.1.4.1.41112.1.6.1.2.1.7.2 = STRING: "ath1"
.1.3.6.1.4.1.41112.1.6.1.2.1.7.3 = STRING: "ath2"
.1.3.6.1.4.1.41112.1.6.1.2.1.7.4 = STRING: "ath3"
.1.3.6.1.4.1.41112.1.6.1.2.1.7.5 = STRING: "ath4"
.1.3.6.1.4.1.41112.1.6.1.2.1.7.6 = STRING: "ath5"
.1.3.6.1.4.1.41112.1.6.1.2.1.7.7 = STRING: "ath6"
.1.3.6.1.4.1.41112.1.6.1.2.1.7.8 = STRING: "ath7"
```

And in that table, we get ```unifiVapUp```:
```
.1.3.6.1.4.1.41112.1.6.1.2.1.22.1 = INTEGER: 1
.1.3.6.1.4.1.41112.1.6.1.2.1.22.2 = INTEGER: 1
.1.3.6.1.4.1.41112.1.6.1.2.1.22.3 = INTEGER: 1
.1.3.6.1.4.1.41112.1.6.1.2.1.22.4 = INTEGER: 1
.1.3.6.1.4.1.41112.1.6.1.2.1.22.5 = INTEGER: 1
.1.3.6.1.4.1.41112.1.6.1.2.1.22.6 = INTEGER: 1
.1.3.6.1.4.1.41112.1.6.1.2.1.22.7 = INTEGER: 1
.1.3.6.1.4.1.41112.1.6.1.2.1.22.8 = INTEGER: 1
```

**Comment by garnier-quentin** [comment]
You can test with new plugin: ```--plugin=network::ubiquiti::unifi::snmp::plugin```
