### ISSUE TITLE
storage::fujitsu::eternus::dx::ssh::plugin mode psu for DRIVE enclosures (dx600 s5)

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#2607]
Hello, 

The option PSU in the plugin storage::fujitsu::eternus::dx::ssh::plugin only lists the ECLOSURE PSU for a DX600 S5.

Is this also possible for the PSU's for the DRIVE enclosure's.

storage/fujitsu/eternus/dx/ssh/mode/psu.pm -> while ($stdout =~ /^(Controller   ->    (Drive|Controller

Drive Enclosure #01 Information
Location      Status       Error Code  Sensor 1 / Sensor 2
Intake Temp   Normal       0x0000      24 (C)   / 24 (C)
Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #01 Status
I/O Module Status/Status Code
...
Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
Disk Status
....

Result :
OK: All 10 power supplies are ok. |
Power Supply 'ce_0' status is 'Normal'
Power Supply 'ce_1' status is 'Normal'
Power Supply 'fe_0' status is 'Normal'
Power Supply 'fe_1' status is 'Normal'
Power Supply 'fe_0' status is 'Normal'
Power Supply 'fe_1' status is 'Normal'
Power Supply 'fe_0' status is 'Normal'
Power Supply 'fe_1' status is 'Normal'
Power Supply 'fe_0' status is 'Normal'
Power Supply 'fe_1' status is 'Normal'

regards,
Geert

**Comment by garnier-quentin** [comment]
Could you provide the response of following command ?
enclosure-status -type all

**Comment by gbin2265** [comment]
Hello,

see here the output

CLI> show enclosure-status -type all


Controller Enclosure    Information
Location      Status       Error Code  Sensor 1 / Sensor 2
Intake Temp   Normal       0x0000      26 (C)   / 26 (C)
Exhaust Temp  Normal       0x0000      39 (C)   / 41 (C)

Controller Enclosure    Status
Controller Module Status/Status Code
  CM#0         [Normal      / 0xE001]
  CM#1         [Normal      / 0xE001]
PCIe Flash Module Status/Status Code
  PFM#0        [Undefined   / 0x0000]
  PFM#0 Port#0 [Undefined   / 0x0000]
  PFM#0 Port#1 [Undefined   / 0x0000]
  PFM#1        [Undefined   / 0x0000]
  PFM#1 Port#0 [Undefined   / 0x0000]
  PFM#1 Port#1 [Undefined   / 0x0000]
  PFM#2        [Undefined   / 0x0000]
  PFM#2 Port#0 [Undefined   / 0x0000]
  PFM#2 Port#1 [Undefined   / 0x0000]
  PFM#3        [Undefined   / 0x0000]
  PFM#3 Port#0 [Undefined   / 0x0000]
  PFM#3 Port#1 [Undefined   / 0x0000]
  PFM#4        [Undefined   / 0x0000]
  PFM#4 Port#0 [Undefined   / 0x0000]
  PFM#4 Port#1 [Undefined   / 0x0000]
  PFM#5        [Undefined   / 0x0000]
  PFM#5 Port#0 [Undefined   / 0x0000]
  PFM#5 Port#1 [Undefined   / 0x0000]
  PFM#6        [Undefined   / 0x0000]
  PFM#6 Port#0 [Undefined   / 0x0000]
  PFM#6 Port#1 [Undefined   / 0x0000]
  PFM#7        [Undefined   / 0x0000]
  PFM#7 Port#0 [Undefined   / 0x0000]
  PFM#7 Port#1 [Undefined   / 0x0000]
Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
Disk Status
  CE-Disk#0   [Present                      ]  CE-Disk#1   [Present                      ]
  CE-Disk#2   [Present                      ]  CE-Disk#3   [Present                      ]
  CE-Disk#4   [Present                      ]  CE-Disk#5   [Present                      ]
  CE-Disk#6   [Present                      ]  CE-Disk#7   [Present                      ]
  CE-Disk#8   [Present                      ]  CE-Disk#9   [Present                      ]
  CE-Disk#10  [Present                      ]  CE-Disk#11  [Present                      ]
  CE-Disk#12  [Present                      ]  CE-Disk#13  [Present                      ]
  CE-Disk#14  [Present                      ]  CE-Disk#15  [Present                      ]
  CE-Disk#16  [Present                      ]  CE-Disk#17  [Present                      ]
  CE-Disk#18  [Present                      ]  CE-Disk#19  [Present                      ]
  CE-Disk#20  [Present                      ]  CE-Disk#21  [Present                      ]
  CE-Disk#22  [Not Available                ]  CE-Disk#23  [Not Available                ]
Drive Enclosure #01 Information
Location      Status       Error Code  Sensor 1 / Sensor 2
Intake Temp   Normal       0x0000      26 (C)   / 26 (C)
Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #01 Status
I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
Disk Status
  DE#01-Disk#0   [Present                      ]  DE#01-Disk#1   [Present                      ]
  DE#01-Disk#2   [Present                      ]  DE#01-Disk#3   [Present                      ]
  DE#01-Disk#4   [Present                      ]  DE#01-Disk#5   [Present                      ]
  DE#01-Disk#6   [Present                      ]  DE#01-Disk#7   [Present                      ]
  DE#01-Disk#8   [Present                      ]  DE#01-Disk#9   [Present                      ]
  DE#01-Disk#10  [Present                      ]  DE#01-Disk#11  [Present                      ]
  DE#01-Disk#12  [Present                      ]  DE#01-Disk#13  [Present                      ]
  DE#01-Disk#14  [Present                      ]  DE#01-Disk#15  [Present                      ]
  DE#01-Disk#16  [Present                      ]  DE#01-Disk#17  [Present                      ]
  DE#01-Disk#18  [Present                      ]  DE#01-Disk#19  [Present                      ]
  DE#01-Disk#20  [Present                      ]  DE#01-Disk#21  [Present                      ]
  DE#01-Disk#22  [Present                      ]  DE#01-Disk#23  [Present                      ]

Drive Enclosure #10 Information
Location      Status       Error Code  Sensor 1 / Sensor 2
Intake Temp   Normal       0x0000      26 (C)   / 26 (C)
Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #10 Status
I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
Disk Status
  DE#10-Disk#0   [Present                      ]  DE#10-Disk#1   [Present                      ]
  DE#10-Disk#2   [Present                      ]  DE#10-Disk#3   [Present                      ]
  DE#10-Disk#4   [Present                      ]  DE#10-Disk#5   [Present                      ]
  DE#10-Disk#6   [Present                      ]  DE#10-Disk#7   [Present                      ]
  DE#10-Disk#8   [Present                      ]  DE#10-Disk#9   [Present                      ]
  DE#10-Disk#10  [Present                      ]  DE#10-Disk#11  [Present                      ]
  DE#10-Disk#12  [Present                      ]  DE#10-Disk#13  [Present                      ]
  DE#10-Disk#14  [Present                      ]  DE#10-Disk#15  [Present                      ]
  DE#10-Disk#16  [Present                      ]  DE#10-Disk#17  [Present                      ]
  DE#10-Disk#18  [Present                      ]  DE#10-Disk#19  [Present                      ]
  DE#10-Disk#20  [Present                      ]  DE#10-Disk#21  [Present                      ]
  DE#10-Disk#22  [Present                      ]  DE#10-Disk#23  [Present                      ]

Drive Enclosure #20 Information
Location      Status       Error Code  Sensor 1 / Sensor 2
Intake Temp   Normal       0x0000      25 (C)   / 25 (C)
Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #20 Status
I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
Disk Status
  DE#20-Disk#0   [Present                      ]  DE#20-Disk#1   [Present                      ]
  DE#20-Disk#2   [Present                      ]  DE#20-Disk#3   [Present                      ]
  DE#20-Disk#4   [Present                      ]  DE#20-Disk#5   [Present                      ]
  DE#20-Disk#6   [Present                      ]  DE#20-Disk#7   [Present                      ]
  DE#20-Disk#8   [Present                      ]  DE#20-Disk#9   [Present                      ]
  DE#20-Disk#10  [Present                      ]  DE#20-Disk#11  [Present                      ]
  DE#20-Disk#12  [Present                      ]  DE#20-Disk#13  [Present                      ]
  DE#20-Disk#14  [Present                      ]  DE#20-Disk#15  [Present                      ]
  DE#20-Disk#16  [Present                      ]  DE#20-Disk#17  [Present                      ]
  DE#20-Disk#18  [Present                      ]  DE#20-Disk#19  [Present                      ]
  DE#20-Disk#20  [Present                      ]  DE#20-Disk#21  [Present                      ]
  DE#20-Disk#22  [Present                      ]  DE#20-Disk#23  [Present                      ]

Drive Enclosure #30 Information
Location      Status       Error Code  Sensor 1 / Sensor 2
Intake Temp   Normal       0x0000      26 (C)   / 26 (C)
Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #30 Status
I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
Disk Status
  DE#30-Disk#0   [Present                      ]  DE#30-Disk#1   [Present                      ]
  DE#30-Disk#2   [Present                      ]  DE#30-Disk#3   [Present                      ]
  DE#30-Disk#4   [Present                      ]  DE#30-Disk#5   [Present                      ]
  DE#30-Disk#6   [Present                      ]  DE#30-Disk#7   [Present                      ]
  DE#30-Disk#8   [Present                      ]  DE#30-Disk#9   [Present                      ]
  DE#30-Disk#10  [Present                      ]  DE#30-Disk#11  [Present                      ]
  DE#30-Disk#12  [Present                      ]  DE#30-Disk#13  [Present                      ]
  DE#30-Disk#14  [Present                      ]  DE#30-Disk#15  [Present                      ]
  DE#30-Disk#16  [Present                      ]  DE#30-Disk#17  [Present                      ]
  DE#30-Disk#18  [Present                      ]  DE#30-Disk#19  [Present                      ]
  DE#30-Disk#20  [Present                      ]  DE#30-Disk#21  [Present                      ]
  DE#30-Disk#22  [Present                      ]  DE#30-Disk#23  [Present                      ]

**Comment by garnier-quentin** [comment]
Applied in commit: f0bcbc76e68754ba1765a3920a3518249b64756a
