### ISSUE TITLE
apps::protocols::http::plugin plugin - misleading behavior of --http-peer-addr parameter when used with a hostname instead of an IP address

### ISSUE THREAD

**Issue by yanickgirouard** [centreon/centreon-plugins#2608]
When using the apps::protocols::http::plugin plugin's --http-peer-addr parameter with a hostname instead of an IP address, the check may look like it's working, but in fact all traffic will be going to the address resolved for the --hostname parameter, giving false positives when you're actually aiming to check a backend server behind a load balanced virtual server.

For example, say you wish to test a page on a web site hosted as mydomain.com and that this address is load balanced to go to server1, server2 and server3, and you use the following check command to do so:

`/usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --method="GET" --proto='https' --hostname=mydomain.com --http-peer-addr=server1 --urlpath='/mypage'`

You may think you are always testing the virtual host mydomain.com on backend server1, but you are in fact testing the load balanced address every time and may actually be testing any server behind the load balanced address. Usually load balanced systems only route traffic to servers that are alive, so you wouldn't know that server1 is down is server2 and server3 are still alive.

In order to fix this, you must use the IP address of server1 instead of its name **and** use the curl http-backend.

The help of the --http-peer-addr parameter does say "no ip resolve", but that doesn't really explain what it will do if you use a hostname instead and because the check returns OK, it's misleading.

Using Centreon version 20.10.0 with latest plugins.

**Comment by garnier-quentin** [comment]
It's working for me with lwp backend. Maybe the message is misleading you with lwp backend.

'mycentreon2' is not resolved in my configuration and it tells that it tries 'wrongwrongtoto' (but it's wrong. it tries to connect on 'mycentreon2'):
```
perl centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --method="GET" --proto='http' --hostname=wrongtototo --http-peer-addr=mycentreon2  --urlpath='/centreon/' --debug --proto=https --insecure
UNKNOWN: 500 Can't connect to wrongwrongtoto:443 (No address associated with hostname) |
======> request send
GET https://wrongwrongtoto/centreon/
User-Agent: centreon::plugins::backend::http::useragent

======> response done
500 Can't connect to wrongwrongtoto:443 (No address associated with hostname)
Content-Type: text/plain
Client-Date: Tue, 23 Feb 2021 16:10:42 GMT
Client-Warning: Internal response

Can't connect to wrongwrongtoto:443 (No address associated with hostname)

No address associated with hostname at /usr/share/perl5/LWP/Protocol/http.pm line 50.
```

Now, i test a domain name resolved by my /etc/hosts:
```
$ ping mycentreon
PING mycentreon (10.30.2.203) 56(84) bytes of data.
...
$ perl centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --method="GET" --proto='http' --hostname=wrongwrongtoto --http-peer-addr=mycentreon  --urlpath='/centreon/' --debug --proto=https --insecure
OK: HTTP test(s) | 'size'=1267B;;;0; 'time'=0.085s;;;0;
======> request send
GET https://wrongwrongtoto/centreon/
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 200 OK
Connection: Keep-Alive
Date: Tue, 23 Feb 2021 16:14:22 GMT
Server: Apache
Content-Type: text/html; charset=UTF-8
Client-Date: Tue, 23 Feb 2021 16:14:22 GMT
Client-Peer: 10.30.2.203:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=FR/ST=dds/L=dsqdsq/O=dq/OU=dq/CN=qd/emailAddress=dq
Client-SSL-Cert-Subject: /C=FR/ST=dds/L=dsqdsq/O=dq/OU=dq/CN=qd/emailAddress=dq
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
Client-Transfer-Encoding: chunked
Keep-Alive: timeout=5, max=100
Title: Centreon
X-Frame-Options: sameorigin
X-Powered-By: PHP/7.2.24

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
            "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
              <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
                <head>
                <style type="text/css">
                       div.Error{background-color:#fa6f6c;border:1px #AEAEAE solid;width: 500px;}
                       div.Error{border-radius:4px;}
                       div.Error{padding: 15px;}
                       a, div.Error{font-family:"Bitstream Vera Sans", arial, Tahoma, "Sans serif";font-weight: bold;}
                </style>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                <title>Centreon</title>
...
```

**Comment by garnier-quentin** [comment]
If you still have the issue, you can comment it.
