### ISSUE TITLE
Add the possibility to monitor VPN with the plugin network::fortinet::fortigate::plugin.

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon-plugins#261]
Hi Quentin,
It would be very great if you can add an option to monitor the VPN sessions in a FortiGate.

I found that but it wont look working.
https://exchange.nagios.org/directory/Plugins/Hardware/Network-Gear/Fortinet/Check-Fortigate-VPN-sessions/details

Since you are the BEST, you should be able to do something easily! ;)
I am available to test it when it will be done! :D

Is it ok ? :D

Thanks and merry christmas!

**Comment by Sims24** [comment]
I'll get some walks from partner soon and then will do this mode

**Comment by sboulianne** [comment]
I am available to help you with this enhancement...
We have many Fortigate with VPN sessions.
I can test it as well!

Contact me on my email or on IRC and it will be a pleasure for me.
Thanks for your good work.

**Comment by Sims24** [comment]
Ok great thanks !

If you could send me by mail the file resulting from the following command (replace all part in bold with your informations ):

snmpwalk -Cc -v2c -c **tacommunauté** -ObentU **__IP_DEVICE__** .1 > **constructeur_modele_firmwareversion**.snmpwalk 

Will come back to you asap to test the mode. 

Regards

**Comment by sboulianne** [comment]
Hi Sims24,

I am very sorry for this very late answer.
Will try to get you the info asap.

**Comment by Sims24** [comment]
Hi @sboulianne , 

I have theses informations, will work on it asap. This is a 1000C walk that I got. 

Thanks anyway ;)

**Comment by sboulianne** [comment]
I have your snpwalk anyways...
Do you want it ?

Is it secure to post it here ?

**Comment by Sims24** [comment]
Ok great, 

Send it to me by mail please,

Thx

**Comment by Sims24** [comment]
Hi @sboulianne, 

Mode is available through #401 pull request ;) 

Closed by #401 

Enjoy !
