### ISSUE TITLE
How to monitor Hyperbackup status for Nas Synology

### ISSUE THREAD

**Issue by daloulou** [centreon/centreon-plugins#2611]
### Feature explanation

Beeing able to get backup status for NAS synology.

### Additional information

Hi,

I'm trying to find a way to monitor backup status on my NAS synology which use HyperBackup. For now, I only get email alert on my email address that alert me when backup ends (succeed or not). I would like to get monitor this through centreon. How can I do this do I have to parse my email to push this to centron ? How can I do that ?

Thanks,

Dan

**Comment by garnier-quentin** [comment]
Need some informations about Hyperbackup. There are some mibs files ?

**Comment by garnier-quentin** [comment]
I have take a look and it seems there are no API: only email for a job failure. So i don't think i can do a plugin.

**Comment by garnier-quentin** [comment]
If you have some news, you can re-open the issue.
