### ISSUE TITLE
Discovery AWS EBS (Disk volume)

### ISSUE THREAD

**Issue by PatPil** [centreon/centreon-plugins#2612]
Hello, 
I would like to make a discovery hosts of EBS volumes on AWS, as we already do for EC2, or S3 Bucket. Can you develop this feature. 
Thanks

![image](https://user-images.githubusercontent.com/79569889/109000244-bc8c7300-76a3-11eb-9fca-382433940997.png)

**Comment by PatPil** [comment]
Hello, 
have you news about this requeste ?
Thanks
Patrick

**Comment by PatPil** [comment]
Hello,
have you news about this request ?
Thanks
Patrick

**Comment by garnier-quentin** [comment]
Have you tried the plugin cloud::aws::ebs::plugin ?

**Comment by PatPil** [comment]
Hello, yes I have tried the EBS plugin, and everything works fine.



***@***.***D3D641.5DCCAF70]<http://www.vicat.fr/>


Patrick PILERI
IT – Pôle Production et Amélioration
+33 (0)4 74 27 59 61
***@***.******@***.***>

DIRECTION DES SYSTEMES D’INFORMATION
GPS : 4 rue Aristide Bergès – 38080 L’ISLE D’ABEAU
COURRIER : TSA 39604 – 38306 BOURGOIN CEDEX

[linkedin-round]<https://www.linkedin.com/company/vicat>  [twitter-round] <https://twitter.com/GroupeVicat>   [facebook-round] <https://www.facebook.com/Groupe.Vicat>   [www-round] <http://www.vicat.fr/>



De : qgarnier ***@***.***>
Envoyé : jeudi 6 mai 2021 16:49
À : centreon/centreon-plugins ***@***.***>
Cc : PILERI Patrick ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] Discovery AWS EBS (Disk volume) (#2612)


Have you tried the plugin cloud::aws::ebs::plugin ?

**Comment by garnier-quentin** [comment]
Is it ok to close it?

**Comment by PatPil** [comment]
oups
yes you can (not you want)…


***@***.***D3D641.5DCCAF70]<http://www.vicat.fr/>


Patrick PILERI
IT – Pôle Production et Amélioration
+33 (0)4 74 27 59 61
***@***.******@***.***>

DIRECTION DES SYSTEMES D’INFORMATION
GPS : 4 rue Aristide Bergès – 38080 L’ISLE D’ABEAU
COURRIER : TSA 39604 – 38306 BOURGOIN CEDEX

[linkedin-round]<https://www.linkedin.com/company/vicat>  [twitter-round] <https://twitter.com/GroupeVicat>   [facebook-round] <https://www.facebook.com/Groupe.Vicat>   [www-round] <http://www.vicat.fr/>



De : qgarnier ***@***.***>
Envoyé : mardi 25 mai 2021 14:32
À : centreon/centreon-plugins ***@***.***>
Cc : PILERI Patrick ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] Discovery AWS EBS (Disk volume) (#2612)


Is it ok to close it?
