### ISSUE TITLE
Discovery AWS FSx (Windows File Server) and EFS (for Linux)

### ISSUE THREAD

**Issue by PatPil** [centreon/centreon-plugins#2613]
Hello, 
I would like to discover windows file server FSx on AWS, as we already do for EC2, or S3 Bucket.
Can you develop this feature. 
Thanks
example FSx 
have the following metrics, and information

![image](https://user-images.githubusercontent.com/79569889/109001044-b9de4d80-76a4-11eb-925a-e83ae4196a1f.png)
![image](https://user-images.githubusercontent.com/79569889/109001063-bfd42e80-76a4-11eb-8801-ab8489baba09.png)

**Comment by PatPil** [comment]
Hello, 
have you news about this request ?
Thanks
Patrick

**Comment by PatPil** [comment]
Hello,
have you news about this request ?
Thanks
Patrick

**Comment by garnier-quentin** [comment]
Have you tried the plugin cloud::aws::efs::plugin ? You want a new plugin for Aws FSX ? like EFS plugin ?

**Comment by Sims24** [comment]
Hi @PatPil, 

There is a new Plugin available for FSx. You can check and test it from here: https://github.com/centreon/centreon-plugins/pull/3344

Thanks

**Comment by PatPil** [comment]
Hello,
this plugin display bad dataread ops, idem, for datawrite ops with count suffix (?)
OK: 'fs-xxxxxxxxxx' Statistic 'Average' Metrics Data Read Bytes: 6.35 MB, Data Write Bytes: 21.98 MB, **Data Read Ops: **463.20 B**,** MetaData Operations Bytes: 573.40 B, Data Write Ops: 1846.40 count | 'fs-xxxxxxxxxx
~average#fsx.data.read.bytes'=6658457.60B;;;; 'fs-xxxxxxxxxx~average#fsx.data.write.bytes'=23049011.20B;;;; 'fs-xxxxxxxxxx~
~average#fsx.data.io.read.count'=463.20B;;;; 'fs-xxxxxxxxxx~average#fsx.metadata.ops.bytes'=573.40B;;;; 'fs-xxxxxxxxxx~average#fsx.data.io.write.count'=1846.40count;;;;

Thanks
Patrick

**Comment by Sims24** [comment]
Hi, 

What do you mean by bad? wrong? 

I changed it to have 'count' for Data Read Ops. We can investigate further if needed.
