### ISSUE TITLE
[apps::protocols::x509] mode=certificate - add MYSQL TLS check

### ISSUE THREAD

**Issue by teonitro** [centreon/centreon-plugins#2614]
Hello, 

FTP and SMTP are now supported by certificate mode and tcp custom mode in TLS. please can you add mysql support  ?

thanks in advance

**Comment by garnier-quentin** [comment]
Do you have a documentation with the protocol ?

**Comment by teonitro** [comment]
Hello Quentin, 

Documentation to implement this protocol for mariadb : 

https://mariadb.com/kb/en/secure-connections-overview/

i don't know if that can help you

**Comment by garnier-quentin** [comment]
It's not the protocol. It's in openssl:
https://github.com/openssl/openssl/commit/a2d9cfbac5d87b03496d62079aef01c601193b58

**Comment by teonitro** [comment]
Yes sorry your are right. We are using an other script check to check ssl mysql : https://exchange.nagios.org/directory/Plugins/Network-Protocols/HTTP/check_ssl_cert/details

We are just set in our Mariadb server certificates to secure connection. juste "Enabling TLS for MariaDB Server" in page https://mariadb.com/kb/en/securing-connections-for-client-and-server/#enabling-tls-for-mariadb-server

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
