### ISSUE TITLE
Add plugin  pacjk AWS Transit Gateway  Attachments 

### ISSUE THREAD

**Issue by PatPil** [centreon/centreon-plugins#2615]
Hello, 
can you add the AWS attachment plugin pack Transit Gateway with features Discovery hosts.
These are devices attached to a TransitGateway. 
Below are screen shots

![image](https://user-images.githubusercontent.com/79569889/109160542-3725c300-7776-11eb-97b0-03bb20ed0488.png)
I remain at your disposal if you need additional elements.
Thank you 
Patrick

**Comment by PatPil** [comment]
Below are screen shots
![image](https://user-images.githubusercontent.com/79569889/109163786-fdef5200-7779-11eb-9c8d-df3b4ef7f933.png)

**Comment by PatPil** [comment]
Hello, 
have you news about this request ?
it's very important for us.
Thanks
Patrick

**Comment by PatPil** [comment]
Hello,
have you news about this request ?
it's very important for us.
Thanks
Patrick

**Comment by PatPil** [comment]
Hello, yes I have tried the TransitGateway plugin, and everything works fine.



***@***.***D3D641.5DCCAF70]<http://www.vicat.fr/>


Patrick PILERI
IT – Pôle Production et Amélioration
+33 (0)4 74 27 59 61
***@***.******@***.***>

DIRECTION DES SYSTEMES D’INFORMATION
GPS : 4 rue Aristide Bergès – 38080 L’ISLE D’ABEAU
COURRIER : TSA 39604 – 38306 BOURGOIN CEDEX

[linkedin-round]<https://www.linkedin.com/company/vicat>  [twitter-round] <https://twitter.com/GroupeVicat>   [facebook-round] <https://www.facebook.com/Groupe.Vicat>   [www-round] <http://www.vicat.fr/>



De : qgarnier ***@***.***>
Envoyé : jeudi 6 mai 2021 16:53
À : centreon/centreon-plugins ***@***.***>
Cc : PILERI Patrick ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] Add plugin pacjk AWS Transit Gateway Attachments (#2615)


Have you tried the plugin cloud::aws::transitgateway::plugin ?

**Comment by garnier-quentin** [comment]
So it's ok to close it ?

**Comment by PatPil** [comment]
Yes you want.



***@***.***D3D641.5DCCAF70]<http://www.vicat.fr/>


Patrick PILERI
IT – Pôle Production et Amélioration
+33 (0)4 74 27 59 61
***@***.******@***.***>

DIRECTION DES SYSTEMES D’INFORMATION
GPS : 4 rue Aristide Bergès – 38080 L’ISLE D’ABEAU
COURRIER : TSA 39604 – 38306 BOURGOIN CEDEX

[linkedin-round]<https://www.linkedin.com/company/vicat>  [twitter-round] <https://twitter.com/GroupeVicat>   [facebook-round] <https://www.facebook.com/Groupe.Vicat>   [www-round] <http://www.vicat.fr/>



De : qgarnier ***@***.***>
Envoyé : mardi 25 mai 2021 14:31
À : centreon/centreon-plugins ***@***.***>
Cc : PILERI Patrick ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] Add plugin pacjk AWS Transit Gateway Attachments (#2615)


So it's ok to close it ?
