### ISSUE TITLE
UNKNOWN: SNMP GET Request : Cant get a single value.

### ISSUE THREAD

**Issue by ricardowieira** [centreon/centreon-plugins#262]
Hi folks!

I'm using CES 3.3 (2.7.0) and when I try to monitor swap memory from my windows machine, the error "UNKNOWN: SNMP GET Request : Cant get a single value." occurs, but only on Centreon Web, through cli works perfectly.

CLI:
[root@centreon centreon-plugins]# ./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=swap --warning=80 --critical=90 --hostname=192.168.1.103 --snmp-version=2c --snmp-community=public
OK: Swap Total: 15.89 GB Used: 6.12 GB (38.52%) Free: 9.77 GB (61.48%) | 'used'=6572081152B;0:13648946790;0:15355065139;0;17061183488

Centreon Web:
![Swap Monitor Error](http://alojaimagens.com/images/lx01b697safcfseb3nqr.png)

I'm using the latest centreon-plugins available. Already tried to remove and add again the host, but still the same. What I'm doing wrong?

Thanks,
Ricardo Vieira

**Comment by garnier-quentin** [comment]
Hi,

COuld you get the exact command executed by 'centreon-engine' ? You can do that with a request on centreon_storage database (example):
SELECT command_line FROM services WHERE service_id = XXX OR command_line LIKE '%IP%';

**Comment by ricardowieira** [comment]
My bad! :|

When I created the service «SNMP-CP-Windows-Swap» without notice I set «Check Command» to use cp_check_swap_linux. Shoud be the command «cp_check_windows_swap».

The query result:
/usr/lib/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=swap --warning=80 --critical=90 --hostname=192.168.1.103 --snmp-version=2c --snmp-community=public

My wrong setting:
![Wrong Command](http://alojaimagens.com/images/z27s5bn3nnkd1x5a3di5.png)

Once again, sorry about this mistake.
This topic can now be closed.
Thanks for the help @garnier-quentin

**Comment by garnier-quentin** [comment]
No problem :) Thanks for the response!
