### ISSUE TITLE
apps::backup::veeam::local::plugin - Not working with Veeam 11 Snap-In removed

### ISSUE THREAD

**Issue by ChristophePelichet** [centreon/centreon-plugins#2622]
Dear Centreon team, 

We have a problem for using the plugin "apps::backup::veeam::local::plugin" with Veeam V11.

With Veeam V11 the powershell snap-in is removed and now we need to use the module named "Veeam.Backup.PowerShell"

If we try to use the plugin we have this error :

=======================
/usr/lib/nagios/plugins/check_centreon_nrpe -H xx.xx.xx.xx -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::backup::veeam::local::plugin' 'job-sta               tus'  ' --filter-name="My_Backup_job" --filter-start-time="" --filter-end-time="86400" --filter-counters="" --ok-status="" --warning-status="" --critical-status="%{is_running} ==                0 and not %{status} =~ /Success/i" --warning-long="" --critical-long="" --verbose'

UNKNOWN: Command error: #< CLIXML - Snap-In Veeam no present or not registered - <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><T               N RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><P               I>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="information" RefId="1"><TN RefId="1"><T>System.Management.Automation.InformationRecord</T><T>System.Object</T>               </TN><ToString>Snap-In Veeam no present or not registered</ToString><Props><Obj N="MessageData" RefId="2"><TN RefId="2"><T>System.Management.Automation.HostInformationMessage</T><T>System.Obj               ect</T></TN><ToString>Snap-In Veeam no present or not registered</ToString><Props><S N="Message">Snap-In Veeam no present or not registered</S><B N="NoNewLine">false</B><S N="ForegroundColor"               >Gray</S><S N="BackgroundColor">Black</S></Props></Obj><S N="Source">Write-Host</S><DT N="TimeGenerated">2021-03-01T09:32:41.2813894+01:00</DT><Obj N="Tags" RefId="3"><TN RefId="3"><T>System.               Collections.Generic.List`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]</T><T>System.Object</T></TN><LST><S>PSHOST</S></LST></Obj><S N="User">               NT AUTHORITY\SYSTEM</S><S N="Computer">my_computer</S><U32 N="ProcessId">2080</U32><U32 N="NativeThreadId">4464</U32><U32 N="ManagedThreadId">13</U32></Props></Obj></Objs> |

===============================================

Some information directly from the Veeam Support  :

Regarding your question, that's right. In V11 the VeeamPSSnapin module is no more because the snapin is obsolete with PowerShell Core 6.0 :

https://docs.microsoft.com/en-us/powershell/scripting/whats-new/breaking-changes-ps6?view=powershell-7.1

So the module is installed on the backup server itself, and the PowerShell scripts have to run from it.

https://helpcenter.veeam.com/docs/backup/powershell/getting_started.html?ver=110

it is possible to upgrade the plugin ?

Thanks in advance.

**Comment by garnier-quentin** [comment]
Could you test following powershell on your server ?
```
$register_snaps=Get-PSSnapin -Registered
$all_snaps=Get-PSSnapin
$load_snaps=@("VeeamPSSnapin")
$registered=0
foreach ($load_snaps in $snap_name) {
    if (@($register_snaps | Where-Object {$_.Name -Match $snap_name} ).count -gt 0) {
        if (@($all_snaps | Where-Object {$_.Name -Match $snap_name} ).count -eq 0) {
            Try {
                $register_snaps | Where-Object {$_.Name -Match $snap_name} | Add-PSSnapin -ErrorAction STOP
                $registered=1
            } Catch {
                Write-Host $Error[0].Exception
                exit 1
            }
        }
    }
}
if ($registered -eq 0) {
    if (@(Get-Module | Where-Object {$_.Name -Match "Veeam.Backup.PowerShell"} ).count -eq 0) {
        Write-Host "Snap-In/Module Veeam no present or not registered"
        exit 1
    }
}
```

**Comment by ChristophePelichet** [comment]
Hello Quentin , 

please show below the result for your code : 

============
PS C:\Users\adm_cpe> C:\Users\adm_cpe\Desktop\test_centreon_1.ps1
Snap-In/Module Veeam no present or not registered
============

I think you have a error in your code in the line number 5 when you start your foreach . 

i think is foreach ($snap_name in $load_snaps)  and not foreach ($load_snaps in $snap_name)

**Comment by garnier-quentin** [comment]
Yes you're right. And when you do the change, it works ?

**Comment by ChristophePelichet** [comment]
We have the same answer , but i think is normal because the module is not loaded by default .

I think we need to add a : Import-Module Veeam.Backup.PowerShell in the line 20

 if (@(Get-Module | Where-Object {$_.Name -Match "Veeam.Backup.PowerShell"} ).count -eq 0) {
   Import-Module Veeam.Backup.PowerShell
......
}

no ?

**Comment by garnier-quentin** [comment]
I didn't know if the module was loaded by default.

**Comment by ChristophePelichet** [comment]
I confirm , is not loaded by default 


PS C:\Users\adm_cpe> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}


PS C:\Users\adm_cpe> Import-Module Veeam.Backup.Powershell
PS C:\Users\adm_cpe> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}
**Manifest   1.0        Veeam.Backup.Powershell             {Add-CTFile, Add-HP3Snapshot, Add-HP3Storage, Add-HP4Snapshot...}**


PS C:\Users\adm_cpe>

**Comment by garnier-quentin** [comment]
Could you test following codes ?
```
$register_snaps=Get-PSSnapin -Registered
$all_snaps=Get-PSSnapin
$load_snaps=@("VeeamPSSnapin")
$registered=0
foreach ($load_snaps in $snap_name) {
    if (@($register_snaps | Where-Object {$_.Name -Match $snap_name} ).count -gt 0) {
        if (@($all_snaps | Where-Object {$_.Name -Match $snap_name} ).count -eq 0) {
            Try {
                $register_snaps | Where-Object {$_.Name -Match $snap_name} | Add-PSSnapin -ErrorAction STOP
                $registered=1
            } Catch {
                Write-Host $Error[0].Exception
                exit 1
            }
        }
    }
}
if ($registered -eq 0) {
    if (@(Get-Module | Where-Object {$_.Name -Match "Veeam.Backup.PowerShell"} ).count -eq 0) {
        Try {
            Import-Module -Name "Veeam.Backup.PowerShell"
            $registered=1
        } Catch {
            Write-Host $Error[0].Exception
            exit 1
        }
    }
    if ($registered -eq 0) {
        Write-Host "Snap-In/Module Veeam no present or not registered"
        exit 1
    }
}
```

**Comment by ChristophePelichet** [comment]
it works
================

PS C:\Users\adm_cpe> get-module

ModuleType Version    Name                                ExportedCommands                                                                                   
---------- -------    ----                                ----------------                                                                                   
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                 
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                          



PS C:\Users\adm_cpe> C:\Users\adm_cpe\Desktop\test_centreon_2.ps1
WARNING: The names of some imported commands from the module 'Veeam.Backup.PowerShell' include unapproved verbs that might make them less discoverable. To fin
d the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

PS C:\Users\adm_cpe> get-module

ModuleType Version    Name                                ExportedCommands                                                                                   
---------- -------    ----                                ----------------                                                                                   
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                 
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                          
Manifest   1.0        Veeam.Backup.PowerShell             {Add-CTFile, Add-HP3Snapshot, Add-HP3Storage, Add-HP4Snapshot...}
