### ISSUE TITLE
QNAP : mode snmp hardware fails to return any value after plugin pack update

### ISSUE THREAD

**Issue by christophe-activiumid** [centreon/centreon-plugins#2625]
Hi

we updated our platform to 20.10 with the plugin pack update
an issue appeared on all qnap for our clients with the hardware check, returning 
UNKNOWN: SNMP Table Request : Timeout

qnap rpm package version is : 
centreon-plugin-Hardware-Storage-Qnap-Snmp-20210218-084020.el7.centos.noarch

We worked around by replacing the component filter from ".*" to "temperature|disk|smartdisk|fan" and the check seems to work.
if we add "|psu" it starts blocking on some qnap, but not other

I said blocking : the command times out after 1 minute, even with the --snmp-timeout=10 that should time out after

To confirm, for the qnap where "psu" work, when I put ".*" it still does not work. and I don't know what is different between 
.* and temperature|disk|smartdisk|fan|psu
when I look at the code, there does not seem to be more component to check

I see there was an issue #2376 in december about PSU

If I run the check from a git clone from before (an old pull from september 30th 2020), not the plugin pack, the issue does not appear and "--component='.*'" is working fine

I can dump some snmpwalk if you want

best regards,
Christophe

**Comment by garnier-quentin** [comment]
Please try with --snmp-force-getnext option ?

**Comment by christophe-activiumid** [comment]
oh thanks, it works fine with that option on 2 qnap, i'm testing on all the qnap in the platform and confirm it works on all devices

**Comment by christophe-activiumid** [comment]
it works fine on all qnap devices with the option --snmp-force-getnext in the extra options
I'm closing this issue

Thanks again.
