### ISSUE TITLE
Proxypac option not working with URL

### ISSUE THREAD

**Issue by sebastien-prudhomme** [centreon/centreon-plugins#263]
Providing an URL for the proxypac option is not working in apps::protocols::http::plugin.

UNKNOWN: issue to load proxypac: http://XXX/: No such file or directory

Problem with the way the HTTP/ProxyPAC perl module is used.

The module is waiting for a perl URI reference to use an URL, see the HTTP/ProxyPAC.pm code:

```perl
    if (blessed($stuff) && $stuff->isa('URI')) {
        return $class->init( $class->load_uri($stuff) );
    }
```

So in case of an URL, call the module like this:

```perl
$pac = HTTP::ProxyPAC->new(URI->new($options{request}->{proxypac}));
```

**Comment by garnier-quentin** [comment]
I think because you don't use the last version: https://metacpan.org/pod/HTTP::ProxyPAC
Try with 0.31.

**Comment by sebastien-prudhomme** [comment]
I'm using 0.31 (RPM perl-HTTP-ProxyPAC downloaded on http://yum.centreon.com/standard/)

**Comment by sebastien-prudhomme** [comment]
See unit test: https://metacpan.org/source/MACKENNA/HTTP-ProxyPAC-0.31/t/01_proxy.t

**Comment by garnier-quentin** [comment]
If you do the change, the plugin works ?

**Comment by sebastien-prudhomme** [comment]
It works: CRITICAL: 407 Proxy Authentication Required |

I just need to open a new issue for an option to set proxy username/password :-)

**Comment by garnier-quentin** [comment]
Can be here :)

**Comment by garnier-quentin** [comment]
I have done the first fix. I don't see how to do the auth.

**Comment by sebastien-prudhomme** [comment]
It seems that you just only need to add login and password in the proxy URL:

http://search.cpan.org/dist/libwww-perl/lwpcook.pod#PROXIES

**Comment by garnier-quentin** [comment]
But i'm telling when you are using the pac file. Indeed, it works when you check directly with proxyurl.
