### ISSUE TITLE
[Enhancement] - Harmonization "database-size" MySQL / PostgreSQL / MSSQL (name and units)

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-plugins#2631]
Hi,

Here are 2 ideas for improvement.

- Name of mode

> ./centreon_mssql.pl --plugin --mode **databases-size**
> ./centreon_postgresql.pl --plugin --mode **database-size**
> ./centreon_mysql.pl --plugin --mode **databases-size**

- Units

> ./centreon_mssql.pl --plugin --mode databases-size 
> **=> '%' or 'B'**
> 
> ./centreon_postgresql.pl --plugin --mode database-size 
> **=> Just 'B'**
> 
> ./centreon_mysql.pl --plugin --mode databases-size 
> **=> 'total-usage', 'total-free', 'db-usage', 'db-free', 'table-usage', 'table-free', 'table-frag'**

Regards

**Comment by garnier-quentin** [comment]
We can update it for mode name. Some databases don't have a max value (so no percent).
