### ISSUE TITLE
apps::cisco::ssms::restapi::plugin

### ISSUE THREAD

**Issue by targuan** [centreon/centreon-plugins#2635]
## Bug/Question
I tried to install the [cisco ssms app](https://github.com/centreon/centreon-plugins/tree/master/apps/cisco/ssms/restapi) from the rpm but it seems to miss some modules:
```
# /usr/lib/centreon/plugins//centreon_cisco_ssms_restapi.pl --plugin=apps::cisco::ssms::restapi::plugin  --mode=licences --help
UNKNOWN: Cannot load module --plugin. 
Can't locate apps/cisco/ssms/restapi/plugin.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::17132424=HASH(0x1056b88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins//centreon_cisco_ssms_restapi.pl line 1619.
```

**Comment by Sims24** [comment]
Hi, 

This is a packaging bug on our side sorry. 

Fix pushed, should be available on unstable soon. 

You will be able to install it using this command: 

`yum update centreon-plugin-Network-Cisco-Ssms-Restapi.noarch --enablerepo='centreon*unstable*'`

Simon
