### ISSUE TITLE
[passwordmgr]: function map --keepass-map-option problem

### ISSUE THREAD

**Issue by teonitro** [centreon/centreon-plugins#2636]
Hello, 

To enforce security for collecting snmp i am try to use snmpv3 and a keepass file with the centreon_plugins.pl file. 
In the keepass file we are using a template where we store different fields for a host as : 
hostname / username (snmpusername) /  authpassphrase / privpassphrase / authprotocol / privprotocol

below using the commande line without the password manager it's good : 
`
[root@snmp-client-test centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=192.168.1.208 --snmp-username=vla-montestsnmp-p01 --snmp-version=3 --authpassphrase='myauthpass' --privpassphrase='myprivpass' --authprotocol=SHA --privprotocol=AES`
OK: Load average: 0.00, 0.01, 0.05 | 'load1'=0.00;;;0; 'load5'=0.01;;;0; 'load15'=0.05;;;0;

Now i a am trying to use the parameter --snmp-username stored in the keepass file. In debug mode i check the output json : 

./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=192.168.1.208 --pass-manager=keepass --keepass-endpoint=general --keepass-endpoint-file=./keepass.pm --keepass-search-value='username=$..groups..entries.[?($_->{title} =~ /vla-montestsnmp-p01/i)].strings.username' --keepass-map-option="snmp-username=%{username}" --snmp-version=3 --authpassphrase='myauthpass' --privpassphrase='myprivpass' --authprotocol=SHA --privprotocol=AES --debug

[...]
``            'accessed' => '2021-03-04 15:47:55',
            'modified' => '2021-03-04 15:26:39',
            'created' => '2021-03-04 15:26:39',
            'level' => 0,
            'location_changed' => '2021-03-04 15:26:39',
            'notes' => '',
            'title' => 'centreon',
            'auto_type_default' => '',
            'expires' => '2021-03-04 15:24:44'
          }
        ];``
lookup = $..groups..entries[?($_->{title} =~ /vla-montestsnmp-p01/i)]..strings.username - response = $VAR1 = 'vla-montestsnmp-p01';
``
my variable is found : vla-montestsnmp-p01. 

now using the password manager and my keepass file for the parameter  : --snmp-username

``
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=192.168.1.208 --pass-manager=keepass --keepass-endpoint=general --keepass-endpoint-file=./keepass.pm --keepass-search-value='username=$..groups..entries.[?($_->{title} =~ /vla-montestsnmp-p01/i)].strings.username' --keepass-map-option="snmp-username=%{username}" --snmp-version=3 --authpassphrase='myauthpass' --privpassphrase='myprivpass' --authprotocol=SHA --privprotocol=AES``
**UNKNOWN: Missing parameter Security Name.**
[root@snmp-client-test centreon-plugins]#

so the --keepass-map-option should map the variable username find in the --keepass-search-value with the --snmp-username.

i think that le parameter --keepass-map-option don't interprete the mapping.

thanks for your support.

**Comment by garnier-quentin** [comment]
It should work with:
```--keepass-map-option="snmp-security-name=%{username}"```

It's an option with not the same value:
```
'snmp-username:s'    => { name => 'snmp_security_name' }
```

**Comment by teonitro** [comment]
thanks a lot for your information ! 
now all works :)
`[root@snmp-client-test centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=192.168.1.208 --pass-manager=keepass --keepass-endpoint=general --keepass-endpoint-file=./keepass.pm --keepass-search-value='snmpusername=$..groups..entries.[?($_->{title} =~ /vla-montestsnmp-p01/)].strings.hostname' --keepass-search-value='authpassphrase=$..groups..entries.[?($_->{title} =~ /vla-montestsnmp-p01/)].strings.authpassphrase' --keepass-search-value='privpassphrase=$..groups..entries.[?($_->{title} =~ /vla-montestsnmp-p01/)].strings.privpassphrase' --keepass-search-value='authprotocol=$..groups..entries.[?($_->{title} =~ /vla-montestsnmp-p01/)].strings.authprotocol' --keepass-search-value='privprotocol=$..groups..entries.[?($_->{title} =~ /vla-montestsnmp-p01/)].strings.privprotocol' --keepass-map-option="snmp-security-name=%{snmpusername}" --snmp-version=3 --keepass-map-option="snmp-auth-passphrase=%{authpassphrase}" --keepass-map-option="snmp-priv-passphrase=%{privpassphrase}" --keepass-map-option="snmp-auth-protocol=%{authprotocol}" --keepass-map-option="snmp-priv-protocol=%{privprotocol}"
OK: Load average: 0.00, 0.01, 0.05 | 'load1'=0.00;;;0; 'load5'=0.01;;;0; 'load15'=0.05;;;0;
[root@snmp-client-test centreon-plugins]#`


Do you think that the snmp pulling (and poller also) can be slow if all hosts are credentials stored in a keepass file ? i talk about 1500 hosts. 
Also do you think that use Hashicorp vault will be implemented in futur as passwordmanager ? 

thanks agin Quantin
