### ISSUE TITLE
Graphic "Traffic Switch" Up and Down

### ISSUE THREAD

**Issue by Johann7214** [centreon/centreon-plugins#2637]
Hello everyone

I have update CENTREON from CENTREON WEB 2.8.32 to CENTREON 20.10 (by the 18.10).

Since the update, i have a problem with the service TRAFFIC who passed from OK to Unknown.

Example: i want to see the port 23 traffic from my Swich HP Procurve 2810. If i write this command in my terminal on the Centreon Server.

> ./centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --snmp-community=***** --snmp-version=1 --mode=interfaces --interface=23 --hostname=###.###.###.### --add-traffic
***** community name
###.###.###.### ip switch
 This command works!

When i return on centreon, i configure the command and the service as below but this returns me an UNKNOWN service.
![image](https://user-images.githubusercontent.com/80317443/110448356-6b2bad00-80c1-11eb-98a1-dea464e189f5.png)

![image](https://user-images.githubusercontent.com/80317443/110449182-3e2bca00-80c2-11eb-81e4-bfbeea8b6ac4.png)

![image](https://user-images.githubusercontent.com/80317443/110449508-8c40cd80-80c2-11eb-94b8-946de4d79301.png)

I'am begginer in Centreon and i try to improve my skills...

Can you helped me please?

Best Regards

**Comment by garnier-quentin** [comment]
The plugin-pack uses the option --name. So you need to use the interface name with option ```--interface```. Eg:
```
--interface=eth0 --name
```

**Comment by Johann7214** [comment]
> The plugin-pack uses the option --name. So you need to use the interface name with option `--interface`. Eg:
> 
> ```
> --interface=eth0 --name
> ```

Thanks you for reply but i don't understand because i have write this option in my COMMAND and it not works.

**Comment by garnier-quentin** [comment]
you need to use service macros.
