### ISSUE TITLE
NetApp Volume bigger than 4To

### ISSUE THREAD

**Issue by kikoololstyle** [centreon/centreon-plugins#264]
Hi,

I use this plugin to check some NetApp volumes : 
storage::netapp::snmp::plugin::filesys with --filter-type=flexibleVolume

One of my volume has 13To of Total space and 8,69To Used space (Real value from NetApp console).
However, the plugin print totaly false values : 
"CRITICAL: Filesys '/vol/XXX' Total: 358.40 GB Used: 709.46 GB (197.95%) Free: 0.00 B (0.00%)"

I already had this error and when i have resized the volume under 4To, the check has changed to OK.

So I think there is probably a problem when the volume is bigger than 4To.
Am I right ?

**Comment by garnier-quentin** [comment]
Hi,

Do you use snmpv2 first ?

**Comment by kikoololstyle** [comment]
Hi,

Good one, i added  "--snmp-version=2" to my command (in fact i forgot it only in that command....), and the critical disappeared !

Thanks a lot :)

**Comment by garnier-quentin** [comment]
My pleasure ;)
