### ISSUE TITLE
New plugin: Prometheus Alert Manager integration

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2648]
Prometheus Alert Manager (https://prometheus.io/docs/alerting/latest/alertmanager/) is able to monitor Kubernetes and send Alerts. It should be very useful to do a plugin which can report alerts from Alert Manager defined by rules. There are some API's available.

**Alerts**
https://prometheus.io/docs/alerting/latest/alertmanager/
This should allow to query Alerts

**Rules**
https://prometheus.io/docs/prometheus/latest/querying/api/#rules
This should allow to query the defined rules and the active alerts for the rules. Maybe we can do all with this endpoint

It should be nice to have filter for rules, this would allow to have a dedicated service for any rule. Rule Discovery should be nice

**Comment by Sims24** [comment]
I'm adding this to the backlog for upcoming sprints.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This isn't an issue so let me close it. If the enhancement request is still interesting you, please vote for it [here](https://thewatch.centreon.com/ideas/plugin-for-prometheus-alertmanager-1066) to be take into account and vote on.
Thank you for your understanding.
