### ISSUE TITLE
Add the posibility to monitor VMware Data Protection backup.

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon-plugins#265]
Hi Quentin,
It will be great if we can monitor the backups taken in VMware Data Protection.
It looks like there is plugin to do that but it wasn't supported.

https://exchange.nagios.org/directory/Plugins/Operating-Systems/*-Virtual-Environments/VMWare/Vmware-vSphere-Data-Protection/details

Thanks.

**Comment by garnier-quentin** [comment]
I see the SQL Requests in the plugin. But i can't give you a date. So i close it.
