### ISSUE TITLE
Rewrite perfdata names

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-plugins#2650]
Hi Quentin,

i think if i remember correctly, it was possible to change the perfdata with some pattern, for example to remove the spaces here:

`root@monitor:/opt/centreon-plugins# ./centreon_plugins.pl --plugin apps::lmsensors::snmp::plugin --mode sensors --hostname 192.168.XXX --snmp-community XXX --component temperature --change-short-output=pattern~replace~modifier`

`OK: All 3 components are ok [3/3 temperatures]. | 'CPU Temp#sensor.temperature.celsius'=36C;;;; 'MB Temp#sensor.temperature.celsius'=24C;;;; 'Adaptec_PCI_temp#sensor.temperature.celsius'=19.75C;;;; 'hardware.temperature.count'=3;;;;`

Can you help me?

**Comment by garnier-quentin** [comment]
You cannot change space in a perfdata with a pattern right now. I need to add a method.

**Comment by florian-asche** [comment]
Whould be great!

**Comment by garnier-quentin** [comment]
You can test with last version:
```
--change-perfdata='.*,,eval(%(label) =~ s/[ ]//g)'
```
