### ISSUE TITLE
--browser option on selenium plugin not working ?

### ISSUE THREAD

**Issue by jthomas74-e** [centreon/centreon-plugins#2651]
Hi,

I'm trying to use the selenium plugin for some tests.
Here is the command I use : 

`perl centreon_selenium.pl --plugin=apps::selenium::plugin --mode=scenario --selenium-hostname=10.11.0.6 --selenium-port='4444' --browser='chrome' --directory='/var/lib/centreon_waa' --scenario='selenium' --timeout='40' --warning='20' --critical='30'`

I'm running an IT100 version of Centreon. Plugin has been installed with the official documentation.

The selenium server is of course running on 10.11.0.6
When I launch the command, I can see that the plugin is still using firefox to launch the test.

How can I switch to Chrome ?
The --browser option is not working ?

Thank you.
Have a nice day.

Best Regards,

**Comment by garnier-quentin** [comment]
I have tested it and i set chrome. But for chrome, maybe you need to set the complete path:
https://metacpan.org/pod/WWW::Selenium:
```
/path/to/my/browser [other arguments]

You may also simply specify the absolute path to your browser executable, or use a relative path to your executable (which we'll try to find on your path). Warning: If you specify your own custom browser, it's up to you to configure it correctly. At a minimum, you'll need to configure your browser to use the Selenium Server as a proxy, and disable all browser-specific prompting.
```

**Comment by jthomas74-e** [comment]
Hi,

Thank you for your reply.
So it's only going to work if the plugin is executed on the machine running the selenium server ?

**Comment by garnier-quentin** [comment]
I don't think so. You should add the path of your chrome browser on your distant selenium server

**Comment by jthomas74-e** [comment]
No matter what I try on the selenium server side, Firefox is still being opened.
It's been three days I try to get this running, must be out of my reach.
I think I'll move on, unless you got a magic how to :)

Thank you for your time.
Have a great day.

**Comment by garnier-quentin** [comment]
What is your centreon-plugins command ?

**Comment by jthomas74-e** [comment]
On 10.11.0.6, here is the command used to launch the selenium server :  
`java -Dwebdriver.chrome.driver=/opt/selenium/chromedriver -jar selenium-server-standalone.jar`

I also tried this :
`java -Dwebdriver.chrome.driver=/opt/selenium/chromedriver  -browser "browserName=chrome,chrome_binary=/opt/google/chrome/chrome" -jar selenium-server-standalone.jar`

On the other machine, running Centreon, here is the command I use to launch the plugin :
`perl centreon_selenium.pl --plugin=apps::selenium::plugin --mode=scenario --selenium-hostname=10.11.0.6 --selenium-port='4444' --browser='chrome' --directory='/var/lib/centreon_waa' --scenario='selenium' --timeout='40' --warning='20' --critical='30`

I also tried this :
`perl centreon_selenium.pl --plugin=apps::selenium::plugin --mode=scenario --selenium-hostname=10.11.0.6 --selenium-port='4444' --browser='/opt/google/chrome/chrome' --directory='/var/lib/centreon_waa' --scenario='selenium' --timeout='40' --warning='20' --critical='30`

There is something I'm doing wrong, but I can't figure out what.
Thank you for your patience.

**Comment by garnier-quentin** [comment]
It's quite old and deprecated. I wont take a deeper look. I think you have done it right.
