### ISSUE TITLE
network::f5::bigip::snmp::mode::poolstatus : adding pool members

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#2658]
Hi,

We have the message:
CRITICAL: Pool '/ Common / xxxxxxxxxx_pool' status: red [state: enabled] [reason: The children pool member (s) are down] 

The pool appears red (status red) but the all members of the pool are disabled.
It is not possible to disable a pool directly (just delete it), we can however disable the members of the pool.

It would be interesting to add a parameter in the list-pools mode (currently status and state) to transmit to pool-status mode.
This would allow filtering the pools with disable members.
 
There is the oid: 
 .1.3.6.1.4.1.3375.2.2.5.6.2.1.5 (.iso.org.dod.internet.private.enterprises.f5.bigipTrafficMgmt.bigipLocalTM.ltmPools.ltmPoolMemberStatus.ltmPoolMbrStatusTable.ltmPoolMbrStatusEntry.ltmPoolMbrStatusAvailState) for status pool-members.
.1.3.6.1.4.1.3375.2.2.5.6.2.1.6
(.iso.org.dod.internet.private.enterprises.f5.bigipTrafficMgmt.bigipLocalTM.ltmPools.ltmPoolMemberStatus.ltmPoolMbrStatusTable.ltmPoolMbrStatusEntry.ltmPoolMbrStatusEnabledState) for state pool-members.

I send you the snmpwalk by mail.

Thanks.

**Comment by gagzou** [comment]
[mibs_f5.tar.gz](https://github.com/centreon/centreon-plugins/files/6155351/mibs_f5.tar.gz)

**Comment by gbin2265** [comment]
Hello,

I have the same problem.

It would be good if the status would no longer be red because basically everything is ok with the pool.
At the moment the people who manage the f5 have simply disabled the members manually.
This is not the same as having members down due to problems.

Now I have to keep asking the administrators that it is normal and then put this temporary shutdown in the monitoring.

regards,
Geert

**Comment by gagzou** [comment]
Hi,
Have you been able to make progress on this improvement (which would be very useful) ?
It should be avoided to have a critical alarm if the children of the failed pool are deactivated (ltmPoolMbrStatusEnabledState).

ltmPoolMbrStatusEnabledState OBJECT-TYPE 
	SYNTAX INTEGER {
		none(0),
		enabled(1),
		disabled(2),
		disabledbyparent(3)
	}

Best regards.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3954

Now, you can use following syntax:
```
--critical-status='%{membersAllDisabled} eq "no" and %{state} eq "enabled" and %{status} eq "red"'
```

**Comment by gagzou** [comment]
Thanks, testing with unstable, it's almost good.
just one thing missing : 
If the node is in the 'disabledbyparent' state (transparent grey), it doesn't work, I still have the critical alarm.
I think the script does not take the status of the node 'disabledbyparent'.

**Comment by garnier-quentin** [comment]
I didn't know for that status. It should be ok when it's merged: https://github.com/centreon/centreon-plugins/pull/3956

**Comment by gagzou** [comment]
Ok thanks :+1:  
everything is working
