### ISSUE TITLE
[network::cisco::standard::snmp::plugin] ipsla problem

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon-plugins#266]
Hi,

We have a new issue with ipsla probe :

Argument "7.24604847795996i" isnt numeric in sprintf at /usr/local/plugins/libexec//centreon/common/cisco/standard/snmp/mode/ipsla.pm line 336.

The cache file below :

$datas = {
           'Singapour_NumOfOW_1' => 1190,
           'Singapour_PacketMIA_1' => 0,
           'Singapour_Sum2NegativesSDLow_1' => 268,
           'Singapour_NumOfPositivesDS_2' => 51,
           'Singapour_RTTSum_2' => 80047,
           'Singapour_SumOfPositivesSD_times' => '685989581_686346581',
           'Singapour_OWSumDS_times' => '685989581_686346581',
           'Singapour_Sum2PositivesSDLow_times' => '685989581_686346581',
           'Singapour_NumOfPositivesSD_2' => 44,
           'Singapour_Sum2NegativesSDLow_2' => 84,
           'Singapour_rttMonLatestRttOperSense' => 'ok',
           'Singapour_PacketOutOfSequence_2' => 0,
           'Singapour_PacketMIA_2' => 0,
           'Singapour_Sum2NegativesSDHigh_times' => '685989581_686346581',
           'Singapour_Sum2NegativesDSLow_2' => 193,
           'Singapour_NumOfPositivesDS_times' => '685989581_686346581',
           'Singapour_NumOfPositivesSD_1' => 196,
           'Singapour_SumOfPositivesSD_2' => 46,
           'Singapour_Sum2PositivesDSHigh_1' => 0,
           'Singapour_Sum2PositivesSDLow_2' => 50,
           'Singapour_RTTSum2Low_1' => 37668259,
           'Singapour_SumOfPositivesSD_1' => 196,
           'Singapour_PacketLossSD_2' => 0,
           'Singapour_OverThresholds_1' => 0,
           'Singapour_Sum2NegativesSDHigh_1' => 0,
           'Singapour_SumOfNegativesDS_times' => '685989581_686346581',
           'Singapour_SumOfNegativesDS_2' => 61,
           'Singapour_Sum2NegativesDSLow_1' => 217,
           'Singapour_PacketLossDS_1' => 0,
           'Singapour_Sum2PositivesSDHigh_2' => 0,
           'Singapour_OWSumSD_times' => '685989581_686346581',
           'Singapour_Sum2PositivesSDHigh_1' => 0,
           'Singapour_SumOfNegativesDS_1' => 215,
           'Singapour_SumOfPositivesDS_1' => 205,
           'Singapour_RTTSum_times' => '685989581_686346581',
           'Singapour_NumOfNegativesSD_2' => 66,
           'Singapour_rttMonCtrlAdminRttType' => 'jitter',
           'Singapour_Sum2NegativesDSHigh_times' => '685989581_686346581',
           'Singapour_Sum2NegativesSDLow_times' => '685989581_686346581',
           'Singapour_OWSum2SDLow_times' => '685989581_686346581',
           'Singapour_NumOfNegativesSD_1' => 244,
           'Singapour_Sum2PositivesDSLow_2' => 194,
           'Singapour_OWSum2DSLow_2' => 3394287,
           'Singapour_NumOfRTT_times' => '685989581_686346581',
           'Singapour_RTTSum2Low_times' => '685989581_686346581',
           'Singapour_NumOfNegativesDS_1' => 214,
           'Singapour_OverThresholds_2' => 0,
           'Singapour_OWSum2SDHigh_times' => '685989581_686346581',
           'Singapour_NumOfOW_2' => 460,
           'Singapour_Sum2PositivesDSLow_times' => '685989581_686346581',
           'Singapour_OWSumSD_2' => 41393,
           'Singapour_NumOfNegativesDS_2' => 50,
           'Singapour_RTTSum_1' => 211719,
           'Singapour_OverThresholds_times' => '685989581_686346581',
           'Singapour_Sum2PositivesSDHigh_times' => '685989581_686346581',
           'Singapour_PacketLossSD_1' => 0,
           'Singapour_NumOfRTT_1' => 1190,
           'Singapour_OWSumDS_2' => 39513,
           'Singapour_OWSum2DSLow_1' => 8683431,
           'Singapour_PacketLossSD_times' => '685989581_686346581',
           'Singapour_SumOfNegativesSD_1' => 252,
           'Singapour_PacketMIA_times' => '685989581_686346581',
           'Singapour_OWSum2SDHigh_1' => 0,
           'Singapour_PacketLateArrival_times' => '685989581_686346581',
           'Singapour_Sum2PositivesSDLow_1' => 196,
           'Singapour_PacketOutOfSequence_times' => '685989581_686346581',
           'Singapour_RTTSum2High_2' => 0,
           'Singapour_OWSum2SDHigh_2' => 0,
           'Singapour_SumOfPositivesDS_2' => 62,
           'Singapour_Sum2NegativesDSHigh_1' => 0,
           'Singapour_Sum2PositivesDSHigh_times' => '685989581_686346581',
           'Singapour_SumOfNegativesSD_times' => '685989581_686346581',
           'Singapour_SumOfNegativesSD_2' => 72,
           'Singapour_RTTSum2High_1' => 0,
           'Singapour_NumOfOW_times' => '685989581_686346581',
           'Singapour_OWSum2DSLow_times' => '685989581_686346581',
           'Singapour_NumOfNegativesDS_times' => '685989581_686346581',
           'Singapour_OWSumDS_1' => 101651,
           'Singapour_SumOfPositivesDS_times' => '685989581_686346581',
           'Singapour_Sum2NegativesSDHigh_2' => 0,
           'Singapour_PacketLossDS_2' => 0,
           'Singapour_rttMonCtrlAdminThreshold' => '5000',
           'Singapour_NumOfPositivesDS_1' => 203,
           'Singapour_rttMonEchoAdminPrecision' => 'ms',
           'Singapour_OWSum2DSHigh_2' => 0,
           'Singapour_OWSum2SDLow_2' => 3807589,
           'Singapour_NumOfPositivesSD_times' => '685989581_686346581',
           'Singapour_NumOfNegativesSD_times' => '685989581_686346581',
           'Singapour_OWSum2SDLow_1' => 10180978,
           'last_timestamp' => 1451789854,
           'Singapour_rttMonCtrlAdminTag' => 'Singapour',
           'Singapour_Sum2PositivesDSHigh_2' => 0,
           'Singapour_NumOfRTT_2' => 450,
           'Singapour_OWSum2DSHigh_1' => 0,
           'Singapour_rttMonCtrlAdminStatus' => 'active',
           'Singapour_PacketOutOfSequence_1' => 0,
           'Singapour_RTTSum2Low_2' => 14239181,
           'Singapour_PacketLateArrival_2' => 0,
           'Singapour_Sum2NegativesDSHigh_2' => 0,
           'Singapour_Sum2PositivesDSLow_1' => 209,
           'Singapour_OWSum2DSHigh_times' => '685989581_686346581',
           'Singapour_PacketLateArrival_1' => 0,
           'Singapour_OWSumSD_1' => 110068,
           'Singapour_Sum2NegativesDSLow_times' => '685989581_686346581',
           'Singapour_RTTSum2High_times' => '685989581_686346581',
           'Singapour_PacketLossDS_times' => '685989581_686346581',
           'Singapour_rttMonLatestRttOperCompletionTime' => '177',
           'Singapour_rttMonLatestRttOperApplSpecificSense' => '0'
         };

**Comment by garnier-quentin** [comment]
Problem had been fixed (delete the ipsla cache file).
