### ISSUE TITLE
NGINX Server Status Plugin

### ISSUE THREAD

**Issue by andreluizpr** [centreon/centreon-plugins#2662]
Hello,

After I updated using yum some plugins of my Centreon Server the Nginx Server Status Plugin is returning UNKNOWN status.

**Environment**
Server: CentOS Linux release 7.9.2009 (Core)
Centreon 20.04.10
Plugin Version: 3.0.8 Stable

** YUM Update**
From: centreon-plugin-Applications-Webservers-Nginx-Serverstatus-20210218-084020.el7.centos.noarch
To: centreon-plugin-Applications-Webservers-Nginx-Serverstatus-20210317-091111.el7.centos.noarch

**File on Linux Server**
272K Mar 17 06:15 centreon_nginx_serverstatus.pl

**Commands Checks** 
App-Webserver-Nginx-Connections: $CENTREONPLUGINS$/centreon_nginx_serverstatus.pl --plugin=apps::nginx::serverstatus::plugin --mode=connections --hostname=$HOSTADDRESS$ --proto=$_HOSTNGINXPROTOCOL$ --port=$_HOSTNGINXPORT$ $_HOSTNGINXSTATUSEXTRAOPTIONS$ --warning-active=$_SERVICEWARNINGACTIVE$ --critical-active=$_SERVICECRITICALACTIVE$ --warning-reading=$_SERVICEWARNINGREADING$ --critical-reading=$_SERVICECRITICALREADING$ --warning-writing=$_SERVICEWARNINGWRITING$ --critical-writing=$_SERVICECRITICALWRITING$ --warning-waiting=$_SERVICEWARNINGWAITING$ --critical-waiting=$_SERVICECRITICALWAITING$ $_SERVICEEXTRAOPTIONS$ 

App-Webserver-Nginx-Requests:  $CENTREONPLUGINS$/centreon_nginx_serverstatus.pl --plugin=apps::nginx::serverstatus::plugin --mode=requests --hostname=$HOSTADDRESS$ --proto=$_HOSTNGINXPROTOCOL$ --port=$_HOSTNGINXPORT$ $_HOSTNGINXSTATUSEXTRAOPTIONS$ --warning-accepts=$_SERVICEWARNINGACCEPTS$ --critical-accepts=$_SERVICECRITICALACCEPTS$ --warning-handled=$_SERVICEWARNINGHANDLED$ --critical-handled=$_SERVICECRITICALHANDLED$ --warning-requests=$_SERVICEWARNINGREQUESTS$ --critical-requests=$_SERVICECRITICALREQUESTS$ $_SERVICEEXTRAOPTIONS$ 

App-Webserver-Nginx-ResponseTime: $CENTREONPLUGINS$/centreon_nginx_serverstatus.pl --plugin=apps::nginx::serverstatus::plugin --mode=responsetime --hostname=$HOSTADDRESS$ --proto=$_HOSTNGINXPROTOCOL$ --port=$_HOSTNGINXPORT$ $_HOSTNGINXSTATUSEXTRAOPTIONS$ --warning=$_SERVICEWARNING$ --critical=$_SERVICECRITICAL$ $_SERVICEEXTRAOPTIONS$ 

**Status on web**
Nginx-Connections: Unknown option: warning-active at /usr/lib/centreon/plugins//centreon_nginx_serverstatus.pl line 656.
Nginx-Requests: Unknown option: warning-accepts at /usr/lib/centreon/plugins//centreon_nginx_serverstatus.pl line 656.
Nginx-ResponseTime: UNKNOWN: mode 'responsetime' doesn't exist (use --list-mode option to show available modes).

Another plugins updated together are OK.

It is possible to confirm if is a general problem or only happening with my environment? 

Any way to solve it?

Thanks

Andre

**Comment by garnier-quentin** [comment]
Please update the pack also

**Comment by andreluizpr** [comment]
Hello @garnier-quentin thanks for your reply.

Isn't showing to me update button, see in attached. 

![Captura de Tela 2021-03-18 às 12 48 10](https://user-images.githubusercontent.com/41391589/111655282-4681b480-87e8-11eb-89d8-987390d95383.png)

Cheers!

Andre

**Comment by garnier-quentin** [comment]
Which version do you use ? rpm pack or online ?

**Comment by andreluizpr** [comment]
I honestly don't remember if I installed online or via yum. I believe it was for yum, because other updates I did also for the yum update and I didn't have any problem.

**Comment by andreluizpr** [comment]
Hello,

I did some more tests and also updated the Plugins Manager extension to version 20.04.2

My other tests:

When I manually execute the command below on my server, it returns successfully

[root@server plugins]# /usr/lib/centreon/plugins/centreon_nginx_serverstatus.pl --plugin=apps::nginx::serverstatus::plugin --mode=connections --hostname=server.domainname.com --proto=https --port=443
OK: Connections active: 1, reading: 0, writing: 1, waiting: 0 | 'server.connections.active.count'=1;;;0;2 'server.connections.reading.count'=0;;;0;2 'server.connections.writing.count'=1;;;0;2 'server.connections.waiting.count'=0;;;0;2

If I include the "--warning-active" option with any value, the error occurs

[root@server plugins]# /usr/lib/centreon/plugins/centreon_nginx_serverstatus.pl --plugin=apps::nginx::serverstatus::plugin --mode=connections --hostname=server.domainname.com --proto=https --port=443  --warning-active=0

Unknown option: warning-active at /usr/lib/centreon/plugins/centreon_nginx_serverstatus.pl line 656.

Thanks

Andre

**Comment by garnier-quentin** [comment]
Check the help. thresholds had changed.

**Comment by Sims24** [comment]
Hye @andreluizpr 

Should be OK not. 

Sorry for that..

Simon

**Comment by andreluizpr** [comment]
Hello @Sims24 how are you? 

Thanks for your reply. 

In my Plugin Pack Manager I cannot see an available update for Nginx plugin.
![Captura de Tela 2021-03-19 às 14 22 27](https://user-images.githubusercontent.com/41391589/111819094-b6fb0500-88be-11eb-8de4-9791df5a43c0.png)

The error persists on Status Details -> Services:
![Captura de Tela 2021-03-19 às 14 24 24](https://user-images.githubusercontent.com/41391589/111819204-d85bf100-88be-11eb-896b-adbe491f5755.png)

On Linux terminal, centreon_nginx_serverstatus.pl version is:
[root@server centos]# /usr/lib/centreon/plugins/centreon_nginx_serverstatus.pl --version
Global Version: 20210317 (fb9abfb25) 

When I execute this command on Linux Terminal: /usr/lib/centreon/plugins/centreon_nginx_serverstatus.pl --plugin=apps::nginx::serverstatus::plugin --list-mode

Available Modes are: 
   connections
   requests

In Extension Manager Plugin Packs Manager don't have a update available.

Thanks 

Andre

**Comment by arthur-lbchn** [comment]
the same for me, no plugin update and one of the modes for "responsetime" is missed

**Comment by garnier-quentin** [comment]
Do you get the version 3.1.1 of that pack ?
'response-time' was outdated. Please use the pack protocol http.

**Comment by arthur-lbchn** [comment]
@garnier-quentin unfortunately, there is no 3.1.1 version available:

![Screenshot_171](https://user-images.githubusercontent.com/9682681/113266456-f7ef1280-92dd-11eb-903b-02b04e007bca.png)

Package centreon-plugin-Applications-Webservers-Nginx-Serverstatus-20210317-091111.el7.centos.noarch already installed and latest version
Nothing to do

**Comment by garnier-quentin** [comment]
Have you tested again ? It should be ok.

**Comment by arthur-lbchn** [comment]
@garnier-quentin thank you for getting back. yes, the update is available for my installation.

**Comment by garnier-quentin** [comment]
Thanks for your feedback! I close it!
