### ISSUE TITLE
[password-manager] - keepass : need perl-JSON-Path >=0.420 

### ISSUE THREAD

**Issue by teonitro** [centreon/centreon-plugins#2664]
hello, 

i try to run the folowing command line from a central/poller : 
```
/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=load --hostname=XXXX --pass-manager=keepass --keepass-endpoint=general --keepass-endpoint-file=/etc/centreon/keepass.pm --keepass-search-value='authpassphrase=$..entries.[?($_->{title} =~ /snmpv3/)].strings.authpassphrase' --keepass-search-value='privpassphrase=$..entries.[?($_->{title} =~ /snmpv3/)].strings.privpassphrase' --keepass-map-option="snmp_auth_passphrase=%{authpassphrase}" --keepass-map-option="snmp_priv_passphrase=%{privpassphrase}" --snmp-version=v3 --snmp-username=centreon --authprotocol=SHA --privprotocol=AES

UNKNOWN: eval failed: `$v->{title} =~ /snmpv3/`, died at /usr/share/perl5/vendor_perl/JSON/Path.pm line 66.
```
i have tested with an other poller and compiled perl library in 0.420 : it's work but from my central 20.10 (centos 8) it's KO   

The problem seems to be the release of the library perl perl-JSON-Path.

Actually the latest release in centreon repo is 0.205

i can't update without breaking centreon central dependencies. 

Can you provide this library updated ans compatible with the central in your repo ? 

thanks a lot in advance

**Comment by garnier-quentin** [comment]
I see. We need to provide it. I'll do the package.

**Comment by teonitro** [comment]
i have build a package using the last release module perl-JSON-Path in 0.431 and the cpanspec and that's work ! 
also need to build the dependencies perl-Exporter-Easy in 0.18

other question, which centreon package provide this this file : centreon/plugins/passwordmgr/keepass.pm when the plugin centreon_linux_snmp.pl is used in centreon ? 

thanks

**Comment by garnier-quentin** [comment]
None. We should add it.

**Comment by garnier-quentin** [comment]
I cannot provide the package for centos 7. That version of JSON::Path needs the package ```https://metacpan.org/pod/List::Util``` 1.48. On centos 7, it's a base package in version 1.27. If we update that package, it breaks a lot of packages.

**Comment by garnier-quentin** [comment]
[json-path-rpm.zip](https://github.com/centreon/centreon-plugins/files/6317543/json-path-rpm.zip)

**Comment by garnier-quentin** [comment]
[json-path-rpm.zip](https://github.com/centreon/centreon-plugins/files/6317910/json-path-rpm.zip)

**Comment by garnier-quentin** [comment]
I close it
