### ISSUE TITLE
[network::cisco::standard::snmp::plugin] environment - sensor dBm with port down

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon-plugins#267]
Hi,

When a port is disabled, optic signal is 0.

swname#sh int te2/9/2 status
Port         Name               Status       Vlan       Duplex  Speed Type
Te2/9/2      FREE               disabled     routed       full    10G 10Gbase-SR

swname#sh int te2/9/2 transceiver detail 
            Optical            High Alarm  High Warn  Low Warn   Low Alarm
            Transmit Power     Threshold   Threshold  Threshold  Threshold
Port        (dBm)              (dBm)       (dBm)      (dBm)      (dBm)
----------  -----------------  ----------  ---------  ---------  ---------
Te2/9/2       N/A                 2.9        -1.0        -7.3      -11.3

            Optical            High Alarm  High Warn  Low Warn   Low Alarm
            Receive Power      Threshold   Threshold  Threshold  Threshold
Port        (dBm)              (dBm)       (dBm)      (dBm)      (dBm)
----------  -----------------  ----------  ---------  ---------  ---------
Te2/9/2       N/A                 2.9        -1.0        -9.9      -13.9

so it is below threshold, so we have an alarm. normal :)

WARNING: Sensor 'TenGigabitEthernet2/9/2 Transmit Power Sensor' is 0 dBm [9035]

is it possible to not check the signal if the port is disabled?

**Comment by garnier-quentin** [comment]
It begins to become real complex. Could you give me oid for the port down ?

**Comment by tcheval** [comment]
I agree :(

it's probably easier to say that if the value for sensor in dBm equal 0, it's ok.

Because, if the value is 0 the port is down so we have another alarm in another check.

**Comment by garnier-quentin** [comment]
I close it in meantime.

**Comment by tcheval** [comment]
After test, I confirm. If the dBm is 0 port is admindown. if the dBm is -40 port is down.

I added, this in sensor.pm. it's ok :

next if ($result->{entSensorType} eq 'dBm' || $result->{entSensorValue} eq 0);
