### ISSUE TITLE
Compatibility between plugin_centreon.pl and SSH connector

### ISSUE THREAD

**Issue by Akatizi** [centreon/centreon-plugins#2670]
Hello, 

I wanted to know if the centreon_plugin.pl plugin was compatible with the SSH connector ?

Indeed, I am trying to make it work on my company's Centreon but I cannot execute it, we have as a message (in the service status):

![image](https://user-images.githubusercontent.com/35867846/112280234-140f0600-8c85-11eb-83d4-464839efee49.png)

However with the PERL connector, there is no problem.
The two connectors were installed following the same procedure.

Does anyone already have the problem?
Thanks You

Further information :
- Version centreon_plugins.pl : dated 2020-08-03
- Version SSH Connector : 19.04.1
- Version Centreon-engine : 19.04.3
- Version Centreon : 19.04.16

**Comment by garnier-quentin** [comment]
You cannot use centreon-plugins and centengine ssh connector. centengine ssh connector is based on check_by_ssh command line (to translate the command).

**Comment by Akatizi** [comment]
Ok, that's what seemed to me, thanks for the confirmation :)
