### ISSUE TITLE
[azure::loganalytics] Mode kustoquery - Add mode that handle the content of the query

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#2672]
## New Plugins and modes

Hello !
It would be great to have enhanced option on cloud::azure:lognalytics plugin, on mode kustoquery.
Today only the number of result if handled but not the content

- 1rst great option : Print the result of the query (like it can be printed with --debug option today) in order to be display in check output
- 2nd great option : Match specifics words like an --excepted-content option
- 3nd great option : Convert and handle the result as a numerical value. For exemple I will ask Azure with a query that will return a number like "81" and would be happy to handle it with warning / critical value

Thanks a lot :pray:

**Comment by Sims24** [comment]
Hello @fixlair 

We are starting to seriously work on this point. Could you please share some of your kusto query and results. It will help us to manage as many case as possible. 

If it's hard to anonymize, feel free to use my email to share it: <Simon Bomm>sbomm@centreon.com

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old and lack of information so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
