### ISSUE TITLE
HUAWEI OCEANSTOR V5 monitoring

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#2676]
Hi, 

I needed to monitor some storage devices from huawei oceanstor and i found that it is not supported by centreon. 
at least there is no plugin pack for this.

Is it possible to include this in the future ? 
do you know any alternate way to do the monitoring of these devices for now ?

Thank you.

Regards

**Comment by garnier-quentin** [comment]
Duplicate #2645
You can add your snmpwalk in the #2645 ticket
