### ISSUE TITLE
[apps::vmware::connector::plugin] VMware object not displaying

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#268]
On the long output from the *alarm-datacenter* mode of *apps::vmware::connector::plugin* plugin, the VMware's object are not displayed, only the type :
[yellow] [Utilisation de la banque de données sur disque] [2015-11-09T13:32:01.012999Z] [**Datastore**] Alarme par défaut pour contrôler l'utilisation du disque de la banque de données
[yellow] [Utilisation de la banque de données sur disque] [2015-11-30T14:00:54.930435Z] [**Datastore**] Alarme par défaut pour contrôler l'utilisation du disque de la banque de données
[yellow] [état Consolidation de machine virtuelle nécessaire] [2015-12-23T15:48:28.654943Z] [**VirtualMachine**] Alarme par défaut déclenchée lorsque l'état Consolidation de machine virtuelle nécessaire est défini

**Comment by garnier-quentin** [comment]
Thanks for the issue.
Could you put it in the github centreon-vmware ?

**Comment by dooko** [comment]
Done.
