### ISSUE TITLE
UNKNOWN: Issue with storage information (see details)

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#2689]
Hello, 

I get this error when doing a Windows storage disk check.
error: UNKNOWN: Issue with storage information (see details)

The disk is visible on the cache:
/usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=10.10.10.10 --snmp-version='2c' --snmp-community='hello'  --storage='.*' --name --regexp --display-transform-src='^(..).*' --display-transform-dst='$1' --verbose --show-cache

...
  'hrstoragedescr_2' => 'D:\\ Label:BACKUP  Serial Number 82ee0356',
...

It works fine with C disk. 

Any clue what could be the problem please ?

thank you

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of following branch? .1.3.6.1.2.1.25

**Comment by saharawolf** [comment]
Hi

Please find the snmpwalk in attachment
[.1.3.6.1.2.1.25.log](https://github.com/centreon/centreon-plugins/files/6242857/default.1.3.6.1.2.1.25.log)

**Comment by garnier-quentin** [comment]
I found the solution with ```--debug``` option:
```
skipping storage 'D:\\ Label:BACKUP  Serial Number 82ee0356': total size is <= 0 (-34368384942080)
```

It's a known SNMP agent issue. Your disk is too big. I cannot fix that. You need to use nsclient.

**Comment by saharawolf** [comment]
Thank, 
Actually i was trying to use nsclient but it is giving me a hard time. 

i installed NRPE :  yum install centreon-nrpe-plugin
Then i Installed NSCLIENT (tried both centreon version and i tried many version of the official site) Nothing works:
# with ssl ignore -n option
./check_centreon_nrpe -H 10.6.1.34 -n
CHECK_NRPE: Socket timeout after 10 seconds.

with ssl
./check_centreon_nrpe -H 10.6.1.34
CHECK_NRPE: Error - Could not complete SSL handshake.

Tried with all this NRPE versions:
Version: 2.15
Version: 3.2.1
Version: 4.0.3

NRPE is compiled with SSL

ldd check_centreon_nrpe
        linux-vdso.so.1 =>  (0x00007ffcfabc3000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f08c4cdc000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f08c4879000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f08c465f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f08c4291000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f08c4044000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f08c3d5b000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f08c3b57000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f08c3924000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f08c3720000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f08c350a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f08c4f4e000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f08c32fa000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f08c30f6000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f08c2edc000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f08c2cc0000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f08c2a99000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f08c2837000)

I do not understand what could be the problem and why it does not work. 

My centreon version is Centreon 20.04.5 and i know it was working with the OLD versions like Centreon 2.8.27

Thanks
