### ISSUE TITLE
Unknown : cannot parse csv : cloud::microsoft::office365::sharepoint::plugin

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2690]
Hello,

I have migrated to redhat 8 but the plugin not work properly :  centreon_office365_sharepoint_api.pl

The command : 

`./centreon_plugins.pl --plugin=cloud::microsoft::office365::sharepoint::plugin --mode=site-usage --custommode='graphapi' --tenant='xxx' --client-id='xxx' --client-secret='xxx' --timeout 45`

Return this error : 

```
Strings with code points over 0xFF may not be mapped into in-memory file handles
UNKNOWN: Cannot parse csv response: EHR - getline_hr () called before column_names ()
```

Thank you.

**Comment by garnier-quentin** [comment]
Could you provide the result with --debug option please ? You can sent it to my email.

**Comment by prohand** [comment]
I have sent the result in you're mail

**Comment by garnier-quentin** [comment]
Could you test with last version ? https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip

**Comment by prohand** [comment]
I have this error : 

```
Use of uninitialized value in concatenation (.) or string at /tmp/centreon-plugins-master/cloud/microsoft/office365/sharepoint/mode/siteusage.pm line 323.
UNKNOWN: Graph endpoint API return error code 'BadRequest' (add --debug option for detailed message)
```

**Comment by garnier-quentin** [comment]
Could you provide the ```--debug``` result ?

**Comment by prohand** [comment]
I have sent the result in you're mail

**Comment by Sims24** [comment]
@prohand could you try again? Quentin did a fix here: https://github.com/centreon/centreon-plugins/commit/2fd7bbb451f3dbf44b193d3566649bd0c2ed8c3e

**Comment by prohand** [comment]
I download the latest master.zip https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip but the problem is same.
Please have you a procedure to download the latest fix ?

Thank you

**Comment by garnier-quentin** [comment]
Sorry for the delay. You can test it with last version.

**Comment by prohand** [comment]
Ok the problem is solved.

Thank you

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
