### ISSUE TITLE
UNKNOWN: Cannot decode json response centreon_office365_management_api.pl

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2693]
Hello,

This command : 

`/usr/lib/centreon/plugins/centreon_office365_management_api.pl --plugin=cloud::microsoft::office365::management::plugin --mode=service-status --custommode='managementapi' --tenant='$_HOSTAZURETENANTID$' --client-id='$_HOSTAZURECLIENTID$' --client-secret='$_HOSTAZURESECRETID$' --verbose --filter-service-name='Microsoft Intne' --critical-status='%{status} !~ /Normal|Restoring service|Service Restored/i'
`
Return alternatively : 

`UNKNOWN: Cannot decode json response: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE HTML PUBLI...") at /usr/lib/centreon/plugins/centreon_office365_management_api.pl line 6866.`

I'm in redhat 8 system.

Thank you

**Comment by garnier-quentin** [comment]
Could you provide the ```--debug``` ? Do you need to use a proxy ?

**Comment by prohand** [comment]
Hello,

I Have send the debug file.

No use proxy.

Thank you

**Comment by garnier-quentin** [comment]
We cannot repeat that issue. So we close it. If someone has it, please tell us here (and need the debug output).
