### ISSUE TITLE
CRITICAL: 500 Can't connect to WEBSITE with TLSv1.3

### ISSUE THREAD

**Issue by sdouce** [centreon/centreon-plugins#2695]
Hello,
All my test to check a website with TLSv1.3  return always the same answer:

CRITICAL: 500 Can't connect to xxxxxxxxxxx:XXXX | 'time'=0.014s;0:5;0:10;0; 'size'=52B;;;0;

I tried Curl Options or LWP , with all options one by one or combined .
--proto='https' --insecure --curl-opt="CURLOPT_SSLVERSION => CURL_SSLVERSION_TLSv1_3"  --curl-opt="CURLOPT_SSL_VERIFYPEER => 0" --curl-opt="CURLOPT_SSL_VERIFYHOST => 0"

If i choose proto='http' , it return a 200 code

I tried to upgrade by compilation my curl  but i dont know how  to change lib link in the plugin . 

Do you have any idea or solution for  TLSv1.3 site ? 

How do i do to change lib curl for the perl plugins ?  

Thank you .

**Comment by garnier-quentin** [comment]
Did you set ```--http-backend=curl``` ? Is it working with curl command line ?

**Comment by sdouce** [comment]
Yes this is the same .... With curl and options

**Comment by garnier-quentin** [comment]
If you couldn't get it with curl, centreon-plugins couldn't (i use the same library).

**Comment by sdouce** [comment]
Ok Quentin , but i i manage to upgrade my curl lib with compilation . How to change plugin param to charge this other curl version ? is it possible .? 
Do you prefer we talk in live (and French) with a support ticket about this subject ? If we can find any solution it willbe great for the plugin et TLSv1.3 monitoring . 
 
Sébastien

**Comment by garnier-quentin** [comment]
I don't think it's a good idea to upgrade the curl version of your operating system. 
You should install a poller on a recent operating system (debian/ubuntu for example) to have a newer curl version.

**Comment by sdouce** [comment]
Quentin , this is impossible for us . We install centreon iso distribution for 20 pollers .
So i will be difficult to mainain different distrib 
 I dont talk about upgrade curl but add another version (in /usr/local )
