### ISSUE TITLE
[apps::vmware::vcsa::restapi::plugin] add more API checks

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#2697]
Heya, long time I didn't commit a request.

This plugin could be useful to monitor and supervise vcenter. We had issues due to bad performance from vCenter instance and it could be really usefull if I could check some metrics.
By SNMP ? Not really, some works some not with snmp linux (photon linux btw)
By API ? yes please => https://docs.vmware.com/fr/VMware-vSphere/7.0/com.vmware.vsphere.vcenter.configuration.doc/GUID-CCC172CB-7CCB-41E4-B46A-0B5876E24EF5.html

mode health is really usefull and maybe you could add to this plugin :
 - com.vmware.appliance.health all of them
 - com.vmware.appliance.recovery.backup.job.get getting the last backup id from com.vmware.appliance.recovery.backup.job.list
 - com.vmware.appliance.system.uptime.get

Cheers

**Comment by garnier-quentin** [comment]
Could you provide curl results of following endpoints ?
```
GET https://{server}/rest/appliance/recovery/backup/job/details
GET https://{server}/rest/appliance/system/uptime
```

I didn't find the api call to get "health all of them" ?

**Comment by oasisck** [comment]
Nevermind, for health there is already the plugin
![image](https://user-images.githubusercontent.com/30388990/117969615-ee6ab880-b327-11eb-8413-a5af25b528a9.png)
so here more plugin to add with output (some with jq)

`GET https://{server}/rest/appliance/system/uptime`
[system.uptime.txt](https://github.com/centreon/centreon-plugins/files/6465927/system.uptime.txt)
`GET https://{server}/rest/appliance/system/version`
[system.version.txt](https://github.com/centreon/centreon-plugins/files/6465928/system.version.txt)
`GET https://{server}/rest/appliance/vmon/service`
[vmon.service.jq.txt](https://github.com/centreon/centreon-plugins/files/6465929/vmon.service.jq.txt)
[vmon.service.txt](https://github.com/centreon/centreon-plugins/files/6465930/vmon.service.txt)
`GET https://{server}/rest/appliance/recovery/backup/job/details`
[backup.job.details.jq.txt](https://github.com/centreon/centreon-plugins/files/6465931/backup.job.details.jq.txt)
[backup.job.details.txt](https://github.com/centreon/centreon-plugins/files/6465932/backup.job.details.txt)
`GET https://{server}/rest/appliance/system/time`
[system.time.txt](https://github.com/centreon/centreon-plugins/files/6465933/system.time.txt)

Cheers
