### ISSUE TITLE
[apps::mq::rabbitmq::restapi::plugin] Add new mode: Detected partition / unsynced nodes

### ISSUE THREAD

**Issue by TheCriSys** [centreon/centreon-plugins#2699]
Hi,

We have just suffered an incident after a snapshot (longer than usual) of one of our VMs supporting a rabbitmq service causing a network partition of the node. Unfortunately, we did not see anything and did not receive any alerts in Centreon because all the nodes were indicated as "running".

From the rabbitmq documentation, it seems that from the URL "**_host:port/api/nodes_**", we can get an array named "partitions" and defined as follows: "**_List of network partitions that this node sees._**".

Is it possible to add a mode to list these network partitions with a warning and a critical threshold number?

Many thanks,
Julian

**Comment by Sims24** [comment]
Hey, 

Could you share the link to the RabbitMQ documentation describing the partition array please?

**Comment by TheCriSys** [comment]
Hello,

I've found it under the /api/nodes section on this page:
https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.8.14/deps/rabbitmq_management/priv/www/api/index.html

Unfortunately, it lack a bit of data...
