### ISSUE TITLE
[plugin] qnap storage

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#27]
this plugin, like check_centreon_remote_storage plugin, does not see raid but only "/" and "swap" storage
to see it, I try with:
check_centreon_snmp_value -H myserver -v 2c -C public -o '.1.3.6.1.4.1.24681.1.2.17.1.5.1'
nut it returns:
Argument "3.49 TB" isn't numeric in numeric gt (>) at ./check_centreon_snmp_value line 329.
Argument "3.49 TB" isn't numeric in numeric lt (<) at ./check_centreon_snmp_value line 354.
OK :The value is 3.490000 nounit|value=3.49 TBnounit;5;10;0;0
and graph is not painted

**Comment by quentinou** [comment]
here we are:

snmpwalk -v 2c -c public 192.168.10.232 '.1.3.6.1.4.1.24681.1.2.17.1.5.1'

output is:
SNMPv2-SMI::enterprises.24681.1.2.17.1.5.1 = STRING: "3.49 TB"
another useful info will be smart status:

snmpwalk -v 2c -c public 192.168.10.232 '.1.3.6.1.4.1.24681.1.2.11.1.7'

output:
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.1 = STRING: "GOOD" 
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.2 = STRING: "GOOD" 
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.3 = STRING: "GOOD" 
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.4 = STRING: "GOOD" 
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.5 = STRING: "GOOD" 
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.6 = STRING: "GOOD" 
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.7 = STRING: "GOOD" 
SNMPv2-SMI::enterprises.24681.1.2.11.1.7.8 = STRING: "GOOD"

**Comment by garnier-quentin** [comment]
Add smart info status:
f28c979cd7ebb162feed5236a6654a45c19f08a5

I will add a volume check.
