### ISSUE TITLE
 --plugin storage::emc::DataDomain::plugin --mode replication unknown

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2701]
Hello,

I have use the plugin  storage::emc::DataDomain::plugin with mode replication and the result is : 

 UNKNOWN: Cannot get DataDomain OS version

The DDOS version is 6.2.1.40

The command is : 

/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin storage::emc::DataDomain::plugin --mode replication --hostname xx.xx.xx.xx --snmp-community community

Thank you

**Comment by Sims24** [comment]
Hi @prohand 

Can you share the result of a snmpget on this OID please: .1.3.6.1.2.1.1.1 

Thanks

**Comment by prohand** [comment]
Hi,

The result : 

`SNMPv2-MIB::sysDescr = No Such Instance currently exists at this OID`

**Comment by Sims24** [comment]
We use this OID to check the DataDomain version. If it's not available, then it's the expected behavior. 

If you do a full snmpwalk, do you see an other OID we might use to get the EMC DDOS versioN?

**Comment by prohand** [comment]
**Command snmpget :** 
```
 snmpget -v 2c -c snmp 192.168.xx.xx .1.3.6.1.2.1.1.1
SNMPv2-MIB::sysDescr = No Such Instance currently exists at this OID
```

**Command snmpwalk :** 
```
bash-4.4$ snmpwalk -v 2c -c snmp 192.168.xx.xx .1.3.6.1.2.1.1.1
SNMPv2-MIB::sysDescr.0 = STRING: Data Domain OS 6.2.1.40-671977
```

**Comment by garnier-quentin** [comment]
Could you also provide snmpwalk for following branch ?
```
snmpwalk -ObentU -v 2c IP .1.3.6.1.4.1.19746 > datadomain.snmpwalk
```

**Comment by prohand** [comment]
I have send the result in you're e-mail
