### ISSUE TITLE
[network::hp::procurve::plugin] Not working with Aruba 8320 cpu / memory

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon-plugins#2705]
plugin not working for aruba 8320 - cpu and memory

**CPU:**
centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --hostname x.x.x.x --snmp-community=public --snmp-version=2c --mode=cpu 
UNKNOWN: SNMP GET Request : Cant get a single value. 
centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --hostname x.x.x.x --snmp-community=public --snmp-version=2c --mode=memory
UNKNOWN: SNMP Table Request: Cant get a single value. 

snmpwalk:
nmpwalk -v 2c -c public x.x.x.x 1.3.6.1.2.1.25.3.3.1.2
HOST-RESOURCES-MIB::hrProcessorLoad.196608 = INTEGER: 21
HOST-RESOURCES-MIB::hrProcessorLoad.196609 = INTEGER: 20
HOST-RESOURCES-MIB::hrProcessorLoad.196610 = INTEGER: 23
HOST-RESOURCES-MIB::hrProcessorLoad.196611 = INTEGER: 18

network guys told me: this is not cpu load, but the % value, the cpu was busy in the last minute.

**MEMORY:**
snmpwalk -v 2c -c public x.x.x.x 1.3.6.1.2.1.25.2.3.1.5.1
HOST-RESOURCES-MIB::hrStorageSize.1 = INTEGER: 15964784 (memory size)

snmpwalk -v 2c -c  public x.x.x.x  1.3.6.1.2.1.25.2.3.1.6.1
HOST-RESOURCES-MIB::hrStorageUsed.1 = INTEGER: 4283452 (memory in use)

complete walk for memory:
snmpwalk -v 2c -c public -On  x.x.x.x 1.3.6.1.2.1.25.2.3.1
.1.3.6.1.2.1.25.2.3.1.1.1 = INTEGER: 1
.1.3.6.1.2.1.25.2.3.1.1.3 = INTEGER: 3
.1.3.6.1.2.1.25.2.3.1.1.6 = INTEGER: 6
.1.3.6.1.2.1.25.2.3.1.1.7 = INTEGER: 7
.1.3.6.1.2.1.25.2.3.1.1.8 = INTEGER: 8
.1.3.6.1.2.1.25.2.3.1.1.10 = INTEGER: 10
.1.3.6.1.2.1.25.2.3.1.1.31 = INTEGER: 31
.1.3.6.1.2.1.25.2.3.1.1.32 = INTEGER: 32
.1.3.6.1.2.1.25.2.3.1.1.33 = INTEGER: 33
.1.3.6.1.2.1.25.2.3.1.1.34 = INTEGER: 34
.1.3.6.1.2.1.25.2.3.1.1.35 = INTEGER: 35
.1.3.6.1.2.1.25.2.3.1.1.36 = INTEGER: 36
.1.3.6.1.2.1.25.2.3.1.1.37 = INTEGER: 37
.1.3.6.1.2.1.25.2.3.1.1.38 = INTEGER: 38
.1.3.6.1.2.1.25.2.3.1.1.39 = INTEGER: 39
.1.3.6.1.2.1.25.2.3.1.1.40 = INTEGER: 40
.1.3.6.1.2.1.25.2.3.1.1.41 = INTEGER: 41
.1.3.6.1.2.1.25.2.3.1.1.42 = INTEGER: 42
.1.3.6.1.2.1.25.2.3.1.1.43 = INTEGER: 43
.1.3.6.1.2.1.25.2.3.1.1.44 = INTEGER: 44
.1.3.6.1.2.1.25.2.3.1.2.1 = OID: .1.3.6.1.2.1.25.2.1.2
.1.3.6.1.2.1.25.2.3.1.2.3 = OID: .1.3.6.1.2.1.25.2.1.3
.1.3.6.1.2.1.25.2.3.1.2.6 = OID: .1.3.6.1.2.1.25.2.1.1
.1.3.6.1.2.1.25.2.3.1.2.7 = OID: .1.3.6.1.2.1.25.2.1.1
.1.3.6.1.2.1.25.2.3.1.2.8 = OID: .1.3.6.1.2.1.25.2.1.1
.1.3.6.1.2.1.25.2.3.1.2.10 = OID: .1.3.6.1.2.1.25.2.1.3
.1.3.6.1.2.1.25.2.3.1.2.31 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.32 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.33 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.34 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.35 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.36 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.37 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.38 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.39 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.40 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.41 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.42 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.43 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.2.44 = OID: .1.3.6.1.2.1.25.2.1.4
.1.3.6.1.2.1.25.2.3.1.3.1 = STRING: Physical memory
.1.3.6.1.2.1.25.2.3.1.3.3 = STRING: Virtual memory
.1.3.6.1.2.1.25.2.3.1.3.6 = STRING: Memory buffers
.1.3.6.1.2.1.25.2.3.1.3.7 = STRING: Cached memory
.1.3.6.1.2.1.25.2.3.1.3.8 = STRING: Shared memory
.1.3.6.1.2.1.25.2.3.1.3.10 = STRING: Swap space
.1.3.6.1.2.1.25.2.3.1.3.31 = STRING: /dev
.1.3.6.1.2.1.25.2.3.1.3.32 = STRING: /sys/fs/cgroup/systemd
.1.3.6.1.2.1.25.2.3.1.3.33 = STRING: /sys/fs/fuse/connections
.1.3.6.1.2.1.25.2.3.1.3.34 = STRING: /fs/logs
.1.3.6.1.2.1.25.2.3.1.3.35 = STRING: /fs/security
.1.3.6.1.2.1.25.2.3.1.3.36 = STRING: /fs/selftest
.1.3.6.1.2.1.25.2.3.1.3.37 = STRING: /fs/coredump
.1.3.6.1.2.1.25.2.3.1.3.38 = STRING: /fs/nos
.1.3.6.1.2.1.25.2.3.1.3.39 = STRING: /eusb/mfg1
.1.3.6.1.2.1.25.2.3.1.3.40 = STRING: /eusb/primary
.1.3.6.1.2.1.25.2.3.1.3.41 = STRING: /eusb/secondary
.1.3.6.1.2.1.25.2.3.1.3.42 = STRING: /eusb/mfg2
.1.3.6.1.2.1.25.2.3.1.3.43 = STRING: /eusb/efi
.1.3.6.1.2.1.25.2.3.1.3.44 = STRING: /run/netns/mirror_ns
.1.3.6.1.2.1.25.2.3.1.4.1 = INTEGER: 1024 Bytes
.1.3.6.1.2.1.25.2.3.1.4.3 = INTEGER: 1024 Bytes
.1.3.6.1.2.1.25.2.3.1.4.6 = INTEGER: 1024 Bytes
.1.3.6.1.2.1.25.2.3.1.4.7 = INTEGER: 1024 Bytes
.1.3.6.1.2.1.25.2.3.1.4.8 = INTEGER: 1024 Bytes
.1.3.6.1.2.1.25.2.3.1.4.10 = INTEGER: 1024 Bytes
.1.3.6.1.2.1.25.2.3.1.4.31 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.4.32 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.4.33 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.4.34 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.4.35 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.4.36 = INTEGER: 8192 Bytes
.1.3.6.1.2.1.25.2.3.1.4.37 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.4.38 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.4.39 = INTEGER: 2048 Bytes
.1.3.6.1.2.1.25.2.3.1.4.40 = INTEGER: 8192 Bytes
.1.3.6.1.2.1.25.2.3.1.4.41 = INTEGER: 8192 Bytes
.1.3.6.1.2.1.25.2.3.1.4.42 = INTEGER: 2048 Bytes
.1.3.6.1.2.1.25.2.3.1.4.43 = INTEGER: 8192 Bytes
.1.3.6.1.2.1.25.2.3.1.4.44 = INTEGER: 4096 Bytes
.1.3.6.1.2.1.25.2.3.1.5.1 = INTEGER: 15964784
.1.3.6.1.2.1.25.2.3.1.5.3 = INTEGER: 15964784
.1.3.6.1.2.1.25.2.3.1.5.6 = INTEGER: 15964784
.1.3.6.1.2.1.25.2.3.1.5.7 = INTEGER: 3383080
.1.3.6.1.2.1.25.2.3.1.5.8 = INTEGER: 2278756
.1.3.6.1.2.1.25.2.3.1.5.10 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.5.31 = INTEGER: 1957513
.1.3.6.1.2.1.25.2.3.1.5.32 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.5.33 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.5.34 = INTEGER: 249830
.1.3.6.1.2.1.25.2.3.1.5.35 = INTEGER: 249830
.1.3.6.1.2.1.25.2.3.1.5.36 = INTEGER: 127360
.1.3.6.1.2.1.25.2.3.1.5.37 = INTEGER: 3063596
.1.3.6.1.2.1.25.2.3.1.5.38 = INTEGER: 11488183
.1.3.6.1.2.1.25.2.3.1.5.39 = INTEGER: 130554
.1.3.6.1.2.1.25.2.3.1.5.40 = INTEGER: 130942
.1.3.6.1.2.1.25.2.3.1.5.41 = INTEGER: 130942
.1.3.6.1.2.1.25.2.3.1.5.42 = INTEGER: 130554
.1.3.6.1.2.1.25.2.3.1.5.43 = INTEGER: 130942
.1.3.6.1.2.1.25.2.3.1.5.44 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.6.1 = INTEGER: 4283956
.1.3.6.1.2.1.25.2.3.1.6.3 = INTEGER: 4283956
.1.3.6.1.2.1.25.2.3.1.6.6 = INTEGER: 139688
.1.3.6.1.2.1.25.2.3.1.6.7 = INTEGER: 3383080
.1.3.6.1.2.1.25.2.3.1.6.8 = INTEGER: 2278756
.1.3.6.1.2.1.25.2.3.1.6.10 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.6.31 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.6.32 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.6.33 = INTEGER: 0
.1.3.6.1.2.1.25.2.3.1.6.34 = INTEGER: 21532
.1.3.6.1.2.1.25.2.3.1.6.35 = INTEGER: 377
.1.3.6.1.2.1.25.2.3.1.6.36 = INTEGER: 1
.1.3.6.1.2.1.25.2.3.1.6.37 = INTEGER: 7789
.1.3.6.1.2.1.25.2.3.1.6.38 = INTEGER: 314894
.1.3.6.1.2.1.25.2.3.1.6.39 = INTEGER: 17
.1.3.6.1.2.1.25.2.3.1.6.40 = INTEGER: 3867
.1.3.6.1.2.1.25.2.3.1.6.41 = INTEGER: 3867
.1.3.6.1.2.1.25.2.3.1.6.42 = INTEGER: 17
.1.3.6.1.2.1.25.2.3.1.6.43 = INTEGER: 1
.1.3.6.1.2.1.25.2.3.1.6.44 = INTEGER: 0

**Comment by garnier-quentin** [comment]
Could you try the plugin network/aruba/aoscx/snmp/plugin ?

**Comment by Cancom-Monitoring** [comment]
not quite sure, if syntax was ok:

centreon_plugins.pl --plugin=network::aruba::aoscx::snmp::plugin --hostname x.x.x.x --snmp-community=public --snmp-version=2c --mode=multi  --modes-exec=cpu --verbose
OK:  |

**Comment by garnier-quentin** [comment]
```
centreon_plugins.pl --plugin=network:aruba:aoscx::snmp::plugin --hostname x.x.x.x --snmp-community=public --snmp-version=2c --mode=cpu --verbose
```

**Comment by garnier-quentin** [comment]
You could also try the rest api plugin.

**Comment by Cancom-Monitoring** [comment]
there is no cpu mode in this plugin:
centreon_plugins.pl --plugin=network::aruba::aoscx::snmp::plugin --hostname x.x.x.x --snmp-community=public --snmp-version=2c --mode=cpu --verbose
UNKNOWN: mode 'cpu' doesn't exist (use --list-mode option to show available modes). 

unfortunatelly I can't test REST API on customers device, I assume that result would be the same, as cpu mode seems to miss too?

**Comment by garnier-quentin** [comment]
Could you try to memory mode ?

**Comment by Cancom-Monitoring** [comment]
same result:
centreon_plugins.pl --plugin=network::aruba::aoscx::snmp::plugin --hostname x.x.x.x --snmp-community=public  --snmp-version=2c --mode=memory --verbose
UNKNOWN: mode 'memory' doesn't exist (use --list-mode option to show available modes).

**Comment by garnier-quentin** [comment]
Sorry there is only vsx, hardware, interfaces modes.

**Comment by Cancom-Monitoring** [comment]
Hi, is there a chance to extend the --plugin=network::hp::procurve::snmp::plugin for aruba 8320 ?
(see snmpwalk for cpu and mem before)

**Comment by garnier-quentin** [comment]
If you find cpu and memory in new mib (branch: .1.3.6.1.4.1.47196) i can add it to: network/aruba/aoscx/snmp/plugin

**Comment by anthonyBertrant** [comment]
@garnier-quentin Hello Quentin, I’m interested too. The MIB reference for:
- cpu is 1.3.6.1.4.1.47196.4.1.1.3.10.3.1.9
- Memory is:
1. Used: 47196.4.1.1.3.15.1.2.1.14
2. Total: 47196.4.1.1.3.15.1.2.1.14

if needed, I have some Aruba CX to try this on.

I already have developed a plug-in for cpu, but the code is pretty bad (I never created a centre on plug-in before) and honestly, I think a centre on plug-in created by this community will be more reliable.

regards

**Comment by anthonyBertrant** [comment]
Oups, for total memory it’s .13, not .14
My bad

**Comment by garnier-quentin** [comment]
i need mib files.

**Comment by garnier-quentin** [comment]
It's in mode vsf. You can try it
