### ISSUE TITLE
[network::alvarion::breezeaccess::snmp] - Can't select a custom port.

### ISSUE THREAD

**Issue by watchix** [centreon/centreon-plugins#2707]
Hello,

Is there an method to query a custom port ?

 perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::alvarion::breezeaccess::snmp::plugin --mode=interfaces --hostname=xx.xx.xx.xx --port=6161
Unknown option: port at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.

Regards,

**Comment by Sims24** [comment]
Hi @watchix 

Please use --snmp-port instead. You can see all SNMP-related options on top of the content displayed when --help flag is used.

**Comment by watchix** [comment]
sorry ... copy/paste problem :

perl /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::alvarion::breezeaccess::snmp::plugin --mode=interfaces --hostname=x.y.z.y  --snmp-community='password' --snmp-port=6161

**Comment by Sims24** [comment]
Do you still get the unknown option message?

**Comment by watchix** [comment]
Hi @Sims24,

Thanks i'd just see your reply.
This was a wrong copy/paste command in my test, sorry for this wrong-positive issue :)

Regards,
