### ISSUE TITLE
Custom Bash Script but no Graph

### ISSUE THREAD

**Issue by AymericFR02** [centreon/centreon-plugins#2708]
Hi,

I've wrote a little script for check free space on an old SCO OpenServer. 

The script work well, the state change if the free space become too small. 

But I would like to have a graph to monitor and find when the space become full.
So I wrote this Bash script :

```
#!/bin/bash
var=$(snmpget -v 1 -c public XXX.XXX.XXX.XXX 1.3.6.1.2.1.25.2.3.1.6.2 | cut -d: -f4)
if [ $var -lt 1638400 ]
then
        echo "L'espace est inférieur à 1,6Go | 'Espace_Disque'=${var}KB;1638400;1843200;0;2048000"
        exit 0
elif [$var -ge 1638400 && $var -lt 1843200]
then
        echo "L'espace est entre 1,6 et 1,8Go | 'Espace_Disque'=${var}KB;1638400;1843200;0;2048000"
        exit 1
else
        echo "L'espace est supérieur à 1,8Go | 'Espace_Disque'=${var}KB;1638400;1843200;0;2048000"
        exit 2
fi

```

I saw on forum that this command permit to make a graph :  | 'Name'=ValueMesure_Unit;warning;critical;min;max"

It is good ? Or is there another way ?

Sorry I'm French ... 

Best regards.

**Comment by garnier-quentin** [comment]
Yes it's ok. But what is the link with centreon-plugins ? :)

**Comment by AymericFR02** [comment]
I didn't make a specific link. 
I'm not a expert of centreon .. 
Here is the configuration of my command in centreon, I don't know if it's help.

![Capture d’écran 2021-04-15 102023](https://user-images.githubusercontent.com/69959679/114837812-63ec7300-9dd4-11eb-9ac9-fc8c737724ce.png)

**Comment by garnier-quentin** [comment]
No issue for me about that command.

**Comment by AymericFR02** [comment]
Ok
How can i link it to a plugin ? 
Because it's a custom OID that I need to use. 
Do you have any recommandation or link to share with me ? 

Thanks

**Comment by garnier-quentin** [comment]
You can use following mode: ```--plugin=apps::protocols::snmp::plugin --mode=numeric-value```

**Comment by AymericFR02** [comment]
Do I need to add this to my command in Centreon or in my bash ?

**Comment by garnier-quentin** [comment]
You can use following plugin: ```/usr/lib/centreon/plugins/centreon_generic_snmp.pl``` from the package: ```centreon-plugin-Applications-Protocol-Snmp```

**Comment by AymericFR02** [comment]
Hi,

Thanks, but I've never write a command that use a plugin. 

Do you have a ticket or a website to share with me ? 

Sorry ..

**Comment by garnier-quentin** [comment]
You have the official doc: https://docs.centreon.com/current/en/monitoring/basic-objects/commands.html#docsNav
If you are a french user, you can look the "superbe" ;) website of kermith: https://www.sugarbug.fr/atelier/techniques/
