### ISSUE TITLE
[apps::microsoft::exchange::local::plugin] Cannot load module 'Win32::Job'

### ISSUE THREAD

**Issue by landregen** [centreon/centreon-plugins#2712]
Hi,

When i try to use apps::microsoft::exchange::local::plugin, i've got the error :

`UNKNOWN: Cannot load module 'Win32::Job'. 
Can't locate Win32/Job.pm in @INC (@INC contains: /usr/lib/centreon/centreon-plugins /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/centreon-plugins/centreon/plugins/misc.pm line 222.
`

thank you for the help.

**Comment by garnier-quentin** [comment]
That plugin must be executed on a windows server directly.

**Comment by garnier-quentin** [comment]
You can find centreon_plugins executable here: https://github.com/centreon/centreon-nsclient-build/releases/tag/20210317074009
