### ISSUE TITLE
cloud::azure::management::monitor::plugin  command error

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2719]
Hello,

I use the last version of centreon_plugin.

But the check : 

/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::management::monitor::plugin --custommode='azcli' --mode='get-metrics'  --resource='/subscriptions/xxx-xxx-xxx/resourceGroups/RESSOURGROUP/providers/Microsoft.Web/sites/mysite' --metric 'Http5xx' --warning-metric 20 --critical-metric 30 --timeout 60 --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True"

Send this output : 

Use of uninitialized value $options{"metric_namespace"} in concatenation (.) or string at /usr/lib/centreon/centreon-plugins/cloud/azure/custom/azcli.pm line 158.
UNKNOWN: Command error: ERROR: argument --namespace: expected one argument -  - TRY THIS: - az monitor metrics list --resource {ResourceName} --metrics "Percentage CPU" - List a VM's CPU usage for the past hour -  - az monitor metrics list --resource {ResourceName} --metrics SuccessE2ELatency --dimension ApiName GeoType - List success E2E latency of a storage account and split the data series based on both API name and geo type -  - az container show --name MyContainerGroup --resource-group MyResourceGroup - Get the details of a container group. (autogenerated) -  - https://docs.microsoft.com/en-US/cli/azure/monitor/metrics#az_monitor_metrics_list - Read more about the command in reference docs

I can show this error, in all metric checks.

The last branch with no error is : 20200602

Thank you for you're help.

**Comment by prohand** [comment]
The debug option return : Command line: 'az monitor metrics list --metrics 'Http5xx' --namespace  --start-time 2021-04-19T12:26:03Z --end-time 2021-04-19T12:36:03Z --interval PT1M --aggregation 'Average' --only-show-errors --output json --resource 'RESSOURCE' --resource-group 'RESSOURCEGROUP' --resource-type 'sites' --resource-namespace 'Microsoft.Web''

**Comment by Sims24** [comment]
Hi, it's a bug indeed, could you try with the last version: https://github.com/centreon/centreon-plugins/blob/master/cloud/azure/custom/azcli.pm

**Comment by prohand** [comment]
Hello,

I have another error : 

UNKNOWN: Command error: ERROR: (ResourceGroupNotFound) Resource group 'CLIENTS-ELCIAONLINE-PAAS' could not be found.

Thank you
