### ISSUE TITLE
Base class package "centreon::plugins::script_snmp" is empty.

### ISSUE THREAD

**Issue by Furiouss38** [centreon/centreon-plugins#272]
Hi,
I just installed CES to replace my old manualy installed centreon, and i found out about centreon-plugins while trying to make my old perl script for vmware to work.
I successfuly managed to make 
centreon_plugins.pl --plugin=apps::vmware::connector::plugin
to work perfectly.

But when I try : 
[centreon@cyclope2 plugins]$ ./centreon_plugins.pl --plugin=centreon-plugins::os::linux::snmp::plugin --list-mode
UNKNOWN: Cannot load module --plugin.
Base class package "centreon::plugins::script_snmp" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /usr/lib/nagios/plugins/ /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
 at /usr/lib/nagios/plugins//centreon-plugins/os/linux/snmp/plugin.pm line 25
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins//centreon-plugins/os/linux/snmp/plugin.pm line 25.
Compilation failed in require at /usr/share/perl5/vendor_perl/centreon/plugins/misc.pm line 211.

I got errors i don't know how to resolve (i'm no perl expert nor developper)

**Comment by Sims24** [comment]
Hi, 

Could you try with this command : 

[centreon@cyclope2 plugins]$ ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --list-mode

Thanks,

**Comment by Furiouss38** [comment]
Sure !

./centreon_plugins.pl --plugin=os::linux::snmp::plugin --list-mode
UNKNOWN: Cannot load module --plugin.
Can't locate os/linux/snmp/plugin.pm in @INC (@INC contains: /usr/lib/nagios/plugins/ /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/vendor_perl/centreon/plugins/misc.pm line 211.

**Comment by Sims24** [comment]
Thanks, 

And what about (adapt to your path if needed) :

ll /usr/lib/nagios/plugins/os/*

**Comment by Furiouss38** [comment]
woop I edited during your answer : 
[root@cyclope2 plugins]# ll /usr/lib/nagios/plugins/os/*
ls: impossible d'accéder à /usr/lib/nagios/plugins/os/*: Aucun fichier ou dossier de ce type
[root@cyclope2 plugins]# ll /usr/lib/nagios/plugins/centreon-plugins/os/*
/usr/lib/nagios/plugins/centreon-plugins/os/aix:
total 8
drwxr-xr-x 3 centreon centreon 4096  8 janv. 11:29 local
drwxr-xr-x 3 centreon centreon 4096  8 janv. 11:29 snmp

/usr/lib/nagios/plugins/centreon-plugins/os/freebsd:
total 4
drwxr-xr-x 2 centreon centreon 4096  8 janv. 11:29 snmp

/usr/lib/nagios/plugins/centreon-plugins/os/linux:
total 8
drwxr-xr-x 3 centreon centreon 4096  8 janv. 11:29 local
drwxr-xr-x 2 centreon centreon 4096  8 janv. 15:16 snmp

/usr/lib/nagios/plugins/centreon-plugins/os/solaris:
total 8
drwxr-xr-x 4 centreon centreon 4096  8 janv. 11:29 local
drwxr-xr-x 2 centreon centreon 4096  8 janv. 11:29 snmp

/usr/lib/nagios/plugins/centreon-plugins/os/windows:
total 12
drwxr-xr-x 3 centreon centreon 4096  8 janv. 11:29 local
drwxr-xr-x 3 centreon centreon 4096  8 janv. 11:29 snmp
drwxr-xr-x 3 centreon centreon 4096  8 janv. 11:29 wsman
[root@cyclope2 plugins]#

**Comment by Sims24** [comment]
Perl probably doesn't like '-' in the path.

try : 

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --list-mode

this one should work I think.

**Comment by Furiouss38** [comment]
It works : 
[root@cyclope2 plugins]# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --list-mode

Plugin Description:
    Check Linux operating systems in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

Modes Available:
   cpu
   cpu-detailed
   disk-usage
   diskio
   inodes
   interfaces
   list-diskspath
   list-interfaces
   list-storages
   load
   memory
   processcount
   storage
   swap
   tcpcon
   time
   uptime


Thanks

**Comment by Sims24** [comment]
You're welcome !

**Comment by florian-asche** [comment]
Maybe we should add this to the documentation?
