### ISSUE TITLE
cloud::azure::management::monitor::plugin command error 2

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2720]
Hello,

I use the last version of centreon_plugin.

But the check :

_/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::management::monitor::plugin --custommode='azcli' --mode='get-metrics' --resource='/subscriptions/xxx-xxx-xxx/resourceGroups/RESSOURGROUP/providers/Microsoft.Web/sites/mysite' --metric 'Http5xx' --warning-metric 20 --critical-metric 30 --timeout 60 --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True"_

Send this output :

_UNKNOWN: Command error: ERROR: (ResourceGroupNotFound) Resource group 'RESSOURCE-GROUP' could not be found._

I can show this error, in all metric checks.
I have multiple subscription but the azcli check only default.
The subscription option is not taken into account.

The debug :

_Command line: 'az monitor metrics list --metrics 'Http5xx' --start-time 2021-04-19T12:43:15Z --end-time 2021-04-19T12:53:15Z --interval PT1M --aggregation 'Average' --only-show-errors --output json --resource 'clients-elciaonline-paas-ael' --resource-group 'RESSOURCE-GROUP' --resource-type 'sites' --resource-namespace 'Microsoft.Web''_

I can't see --subscription option.

I add manually --subscription, the check is OK.
Can you add --subscription in this centreon-plugin ?

Thank you

https://github.com/centreon/centreon-plugins/issues/2719

**Comment by prohand** [comment]
While waiting for a correction I modified the checks by adding --subscription
It's OK.

**Comment by thibaults-centreon** [comment]
Hello,
the --subscription option is mandatory when using azcli on multiple subscriptions. We don't throw an exception when not set because we want to use the default subscription by default
see https://github.com/centreon/centreon-plugins/blob/master/cloud/azure/custom/azcli.pm#L596

**Comment by prohand** [comment]
Hello,

Ok thank you.
