### ISSUE TITLE
cloud::azure::management::monitor::plugin UNKNOWN: No metric found

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2729]
Hello,

I have a new issue with command :

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::management::monitor::plugin --custommode='azcli' --mode='get-metrics' --tenant='xxxx' --resource='/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Web/sites/xxxx' --metric 'AverageResponseTime' --warning-metric 10 --critical-metric 15 --timeout 60 --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True" --subscription 'xxxx'`

`UNKNOWN: No metric found (Are the filters properly set?)`

With debug option  : 

```
UNKNOWN: No metric found (Are the filters properly set?)
Command line: 'az monitor metrics list --metrics 'AverageResponseTime' --start-time 2021-04-22T15:33:10Z --end-time 2021-04-22T15:43:10Z --interval PT1M --aggregation 'Average' --only-show-errors --output json --resource 'xxxx' --resource-group 'xxxx' --resource-type 'sites' --resource-namespace 'Microsoft.Web' --subscription 'xxxx''

```

Another command with same metric is OK.

Thank you

**Comment by thibaults-centreon** [comment]
Hello,
according to https://docs.microsoft.com/fr-fr/azure/azure-monitor/essentials/metrics-supported#microsoftwebsites,
this metric is deprecated, this is probably the reason you don't get any result. You may wanna use 'HttpResponseTime' instead.

**Comment by prohand** [comment]
Hello,

Ok thank you

I have change the metric.
