### ISSUE TITLE
[network::juniper::srx::plugin] Add SRX multi-VPN mode check

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#273]
Hi,

Could you please add multi-vpn check mode to plugin network::juniper::srx::plugin?

I think you can use this as example: https://exchange.nagios.org/directory/Plugins/Network-Connections%2C-Stats-and-Bandwidth/Juniper-SRX--2D-VPNL2L-phase-1-%26-2-monitor/details

**Comment by kadrika** [comment]
Any update on this?

**Comment by garnier-quentin** [comment]
I need the snmpwalk and what to monitor exactly.

**Comment by kadrika** [comment]
We need to monitor IPSec tunnel Phase1 and Phase2. If any of them is not OK, then alarm is triggered. Also that tunnels can be filtered by name. Also it would be really good to see the tunnel traffic too. But most important to us it to be sure the tunnel is up and running.
MIB that is used: http://www.circitor.fr/Mibs/Html/JUNIPER-IPSEC-FLOW-MON-MIB.php

I will send the snmpwalk to your email as is contains confidential information.

**Comment by kadrika** [comment]
Any update on this? If you need newer snmpwalk then I can send it to you.
