### ISSUE TITLE
[backup::commvault::commserve::restapi] "uninitialized value" warning on mode "jobs"

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#2730]
Hello !

When using commserve::restapi plugin we are facing a warnings when using mode "jobs" with "no matching job case" as described bellow : 

`centreon_plugins.pl --plugin=apps::backup::commvault::commserve::restapi::plugin --mode=jobs --hostname=out-v-commsrv01 --api-username=xxxxxxxx --api-password=xxxxxxx --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --critical-long='%{elapsed} > 7200' --filter-policy-name='xxxxxxxx' --filter-client-name='xxxxxxx'`
**Use of uninitialized value in pattern match (m//) at /var/lib/centreon/plugins/apps/backup/commvault/commserve/restapi/mode/jobs.pm line 195.**
_OK: Total jobs: 0 | 'jobs.total.count'=0;;;0;_

The result is correct but maybe this warning case can be handle ?

Ps : Thanks for awesome work on these plugin !
Regards,

**Comment by garnier-quentin** [comment]
could you provide the result with --debug option ?

**Comment by fixlair** [comment]
Use of uninitialized value in pattern match (m//) at /var/lib/centreon/plugins/apps/backup/commvault/commserve/restapi/mode/jobs.pm line 195.
OK: Total jobs: 0 | 'jobs.total.count'=0;;;0;
======> request send
GET https://xxxx/webconsole/api/Job?completedJobLookupTime=43
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/json
Authtoken: QSDK XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

 

======> response done
HTTP/1.1 200 OK
Cache-Control: private
Connection: keep-alive
Date: Thu, 22 Apr 2021 15:55:04 GMT
Server: Commvault WebServer
Vary: accept-encoding
Content-Length: 3184
Content-Type: application/json;charset=utf-8
Client-Date: Thu, 22 Apr 2021 15:55:04 GMT
Client-Peer: 172.XX.YY.ZZZ:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /CN=COMMVAULT
Client-SSL-Cert-Subject: /CN=COMMVAULT
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
Keep-Alive: timeout=600
Set-Cookie: JSESSIONID=ZZZZZZZZ; Path=/webconsole; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block

 

"sizeOfApplication":142850307234846,"vsaParentJobID":0,"commcellId":2,"thresholdTime":2,"opType":104,"isAnomalous":true,"totalFailedFolders":0,"distributedAppsClusterType":0,"totalFailedFiles":0,"alertColorLevel":16,"isVisible":true,"localizedStatus":"Running","isAged":false,"totalNumOfFiles":0,"jobId":1253724,"sizeOfMediaOnDisk":0,"currentPhase":1,"status":"Running","lastUpdateTime":1619106876,"percentSavings":0,"localizedOperationName":"Auxiliary Copy","statusColor":"black","errorType":0,"backupLevel":0,"jobElapsedTime":2324105,"jobStartTime":1616673676,"currentPhaseName":"Auxiliary Copy","jobType":"Aux Copy","isPreemptable":1,"attemptStartTime":1619006368,"percentComplete":99,"jobEndTime":0,"dataSou"sizeOfApplication":56792294384,"vsaParentJobID":0,"commcellId":2,"backupSetName":"defaultBackupSet","opType":4,"phasePercentagesList":"0,0,0,0,0,0,0,99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","totalFailedFolders":0,"totalFailedFiles":0,"alertColorLevel":0,"currentPhaseType":8656384,"isVisible":true,"localizedStatus":"Running","isAged":false,"totalNumOfFiles":8,"jobId":1269376,"sizeOfMediaOnDisk":0,"currentPhase":7,"status":"Running","lastUpdateTime":1619106824,"percentSavings":0,"localizedOperationName":"Backup","statusColor":"black","errorType":0,"backupLevel":1,"jobElapsedTime":6882,"jobStartTime":1619100013,"currentPhaseName":"Backup","jobType":"Backup","isPreemptable":1,"backupLevelName":"Full","attemptStartTime":1619100030,"appTypeName":"Windows File System","percentComplete":99,"phaseTimingsList":"0,0,0,7,0,0,23013,0,0,0,0,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0","localizedBackupLevelName":"Full","subc"clientName":"ABCDEFG","instanceName":"DefaultInstanceName","backupsetId":120,"commCellName":"SERVER","instanceId":1,"subclientId":262,"clientId":101,"appName":"Windows File System","backupsetName":"defaultBackupSet","applic}_type_":28,"clientGroupId":92,"clientGroupName":"Sauvegarde policy"
skipping job 'JOB_1/1234565': no matching filter type.
skipping job 'JOB_1/1234565': no matching filter type.

**Comment by garnier-quentin** [comment]
Please remove '\r' with sed otherwise the output is missy

**Comment by fixlair** [comment]
Hi !

I checked and provide a the full output is a little bit tricky (a lot of private info to hide inside)

But checking more in deepth I observe that 
"destClientName" is not always present in Json return from Commserve (call here $job->{destClientName}). I don't understand well why does so the API but maybe the plugin can handle this case ?
