### ISSUE TITLE
Issue with HP Procurve

### ISSUE THREAD

**Issue by EtienneN10** [centreon/centreon-plugins#2738]
Hello,

I have a problem to supervise HP Procurve switches.

When I use the network::hp::procurve::snmp::plugin, the information is returned without problem.

However when I use the network::hp::standard::snmp::plugin, 
it doesn't work.

For example, the command : 
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=network::hp::standard::snmp::plugin --mode=hardware --snmp-community=public --snmp-version=2c --hostname=X.X.X.X --verbose
returns me :
OK: All 0 components are ok []. |
Checking power supplies
Checking stack
Checking chassis
Checking fans
Checking module
Checking cpu
Checking unknown
Checking sensors
Checking other
Checking backplane
Checking port
Checking container

Unlike the first plugin, this one allows me to get the port information, and I need it.

If someone can tell me a solution, it would be nice.

Thanks

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk ?

**Comment by EtienneN10** [comment]
Thank you for your quick response.

I use only the plugins you provided ( centreon_plugin.pl )

Don't you provide the mibs in the folder you created? 

I'm providing you the full snmpwalk.
[full_snmp_switch_hp_procurve.txt](https://github.com/centreon/centreon-plugins/files/6383354/full_snmp_switch_hp_procurve.txt)

**Comment by garnier-quentin** [comment]
The snmpwalk is not complete. Please provide it from following branch: 
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1

**Comment by EtienneN10** [comment]
[full_snmp_hp_procurse.txt](https://github.com/centreon/centreon-plugins/files/6384179/full_snmp_hp_procurse.txt)

Thank you

**Comment by garnier-quentin** [comment]
You can try following plugin:
```
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --mode=hardware --snmp-community=public --snmp-version=2c --hostname=X.X.X.X --verbose
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --mode=cpu --snmp-community=public --snmp-version=2c --hostname=X.X.X.X --verbose
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=network::hp::procurve::snmp::plugin --mode=memory --snmp-community=public --snmp-version=2c --hostname=X.X.X.X --verbose
```

**Comment by EtienneN10** [comment]
hi,
there is a part of the content of your file....

As you can see there's no "Hardware" option.... have you an other version than me ?

    $self->{version} = '1.0';
    %{$self->{modes}} = (
        'cpu'              => 'network::hp::procurve::snmp::mode::cpu',
        'environment'      => 'network::hp::procurve::snmp::mode::environment',
        'interfaces'       => 'snmp_standard::mode::interfaces',
        'list-interfaces'  => 'snmp_standard::mode::listinterfaces',
        'memory'           => 'network::hp::procurve::snmp::mode::memory',
        'virtual-chassis'  => 'network::hp::procurve::snmp::mode::virtualchassis',
    );

   Thanks in advance !
Bests regards.

**Comment by garnier-quentin** [comment]
It's environment ;)

**Comment by garnier-quentin** [comment]
I think it's not in current plugin version.

**Comment by EtienneN10** [comment]
Ok, thanks.

I'm using a lot your work.

**Comment by garnier-quentin** [comment]
it could be add if you tell me what exactly

**Comment by EtienneN10** [comment]
I would like to be able to check if an interface is Bad 

I think i'll could do it with  
.iso.org.dod.internet.mgmt.mib-2.interfaces.ifTable.ifEntry.ifInErrors
and 
.iso.org.dod.internet.mgmt.mib-2.interfaces.ifTable.ifEntry.ifOutErrors 
which are two counters32.

If there's more than 0 errors the interface could be bad.

what do you think about it ?
bests regards

**Comment by garnier-quentin** [comment]
You can use interfaces mode with option --add-errors

**Comment by EtienneN10** [comment]
A last question,

By default, at what percentage of error packets, discarded packets, will the service go into a critical or warning state? 
And how can I change them? 
The critical-average or critical command does not work.
