### ISSUE TITLE
 Improved on Centreon Dashboard

### ISSUE THREAD

**Issue by PatPil** [centreon/centreon-plugins#2741]
## New Plugins and modes /Question

Hello to all, 

I would like to submit various points to be improved on Centreon dasboard in graph, (Widget Graph Monitoring) 
(Total Internet Trafic [graph-monitoring])

1- Possibility to set the axes in fixed on the dashboards and not in dynamic.
2- To have a global time scale or not, variable on the dashboards.

example:

1 - 
![image](https://user-images.githubusercontent.com/79569889/116385604-3ca49580-a819-11eb-840f-c96ba350dbf5.png)
![screenshot_180](https://user-images.githubusercontent.com/79569889/116391958-1d5d3680-a820-11eb-809c-b868bac76ceb.png)

2 - 
![screenshot_181](https://user-images.githubusercontent.com/79569889/116392178-6b723a00-a820-11eb-8d54-9a57a9ceb333.png)

Thanks for your help
Patrick

**Comment by garnier-quentin** [comment]
Sorry but you are in the wrong github project. Please post it in centreon ;)
