### ISSUE TITLE
[apps::backup::veeam::local::plugin] --mode=list-jobs - Use of uninitialized value in subroutine entry

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2743]
Plugins 20210421

nsclient++ returns a list of errors like this:
Use of uninitialized value in subroutine entry at C:\Windows\TEMP\par-47564d2d564545414d424b5024\cache-39701d674daf43048f11e64e4f1be5e9c515e860\inc\lib/XML/LibXML.pm line 1650.
Use of uninitialized value in subroutine entry at C:\Windows\TEMP\par-47564d2d564545414d424b5024\cache-39701d674daf43048f11e64e4f1be5e9c515e860\inc\lib/XML/LibXML.pm line 1650.
Use of uninitialized value in subroutine entry at C:\Windows\TEMP\par-47564d2d564545414d424b5024\cache-39701d674daf43048f11e64e4f1be5e9c515e860\inc\lib/XML/LibXML.pm line 1650.
Use of uninitialized value in subroutine entry at C:\Windows\TEMP\par-47564d2d564545414d424b5024\cache-39701d674daf43048f11e64e4f1be5e9c515e860\inc\lib/XML/LibXML.pm line 1650.
Use of uninitialized value in subroutine entry at C:\Windows\TEMP\par-47564d2d564545414d424b5024\cache-39701d674daf43048f11e64e4f1be5e9c515e860\inc\lib/XML/LibXML.pm line 1650.
Use of uninitialized value in subroutine entry at C:\Windows\TEMP\par-47564d2d564545414d424b5024\cache-39701d674daf43048f11e64e4f1be5e9c515e860\inc\lib/XML/LibXML.pm line 1650.

**Comment by garnier-quentin** [comment]
Could you provide the result of command with option --ps-exec-only ?

**Comment by joschi99** [comment]
[{"name":"ZZ_Bkp Copy Cluster GVM-CRMDBCL.domesa.grp","type":65},{"name":"ZZ_Bkp Copy Daily SIA-FS01\\Daily SIA-FS01","type":70},{"name":"Monthly-GVM-BCVC_DR-SAS2","type":0},{"name":"ZZ_Bkp Copy Cluster GVM-WHCLS.domgesa.grp","type":65},{"name":"ZZ_Bkp Copy Cluster GVM-NAVALSQLCL.domgesa.grp_old","type":51},{"name":"Monthly-GVMVC01_LowTier01","type":0},{"name":"Monthly-GVM-BCVC_TMCH","type":0},{"name":"ZZ_Bkp Copy Cluster GVM-EKADBN.domgesa.grp","type":65},{"name":"Cluster GVM-WHCLS.domgesa.grp","type":12003},{"name":"ZZ_Bkp Copy Monthly-GVMVC01_01","type":65},{"name":"Monthly-GVM-BCVC_TSIAMCH","type":0},{"name":"ZZ_Bkp Copy Cluster GVM-NAVALSQLCL.domgesa.grp\\Cluster GVM-NAVALSQLCL.domgesa.grp","type":70},{"name":"ZZ_Bkp Copy Cluster GVM-NAVALSQLCL.domgesa.grp","type":65},{"name":"ZZ_Bkp Copy Cluster GVM-ZSQL.domgesa.grp","type":65},{"name":"ZZ_Bkp Copy Monthly-GVM-BCVC_DR_NLSAS1-2","type":65},{"name":"Cluster GVMNAV6.domgesa.grp","type":12003},{"name":"GVM-MEDTERM","type":0},{"name":"Ravenna Medical Center","type":12003},{"name":"Monthly-GVMVC01_03","type":0},{"name":"Daily DC","type":0},{"name":"ZZ_Bkp Copy Monthly-GVMVC01_03","type":65},{"name":"Monthly-GVM-BCVC_DR-NLSAS1-2","type":0},{"name":"Monthly-GVMVC01_01","type":0},{"name":"ZZ_Bkp Copy Monthly-GVM-BCVC_Auto6-7-Low","type":65},{"name":"Cluster GVM-ZSQL.domgesa.grp","type":12003},{"name":"Monthly-GVMVC01_LowTier02","type":0},{"name":"ZZ_Bkp Copy Monthly-GVMVC01_02","type":65},{"name":"Monthly-GVM-BCVC_SAS1","type":0},{"name":"DBFILES - Every 2 Hour","type":0},{"name":"ZZ_Bkp Copy Monthly-GVM-BCVC_TSIAMCH","type":65},{"name":"ZZ_Bkp Copy Monthly-GVM-BCVC_DR-SAS2","type":65},{"name":"ZZ_Bkp Copy Daily File VM","type":65},{"name":"ZZ_Bkp Copy Monthly-GVM-BCVC_TSIA","type":65},{"name":"Replication Job 1","type":1},{"name":"ZZ_Bkp Copy GVM-MEDTERM","type":65},{"name":"DC_Test","type":0},{"name":"Daily File VM","type":0},{"name":"Cluster GVM-NAVALSQLCL.domgesa.grp","type":12003},{"name":"ZZ_Bkp Copy Monthly-GVMVC01_LowTier01","type":65},{"name":"Cluster GVM-EKADBN.domgesa.grp","type":12003},{"name":"ZZ_Bkp Copy CLuster GVMNAV6.domgesa.grp","type":65},{"name":"ZZ_Bkp Copy Cluster GVM-WHCLS.domgesa.grp\\Cluster GVM-WHCLS.domgesa.grp","type":70},{"name":"Monthly-GVM-BCVC_Auto6-7-Low","type":0},{"name":"ZZ_Bkp Copy Cluster GVM-ZSQL.domgesa.grp\\Cluster GVM-ZSQL.domgesa.grp","type":70},{"name":"ZZ_Bkp Copy CLuster GVMNAV6.domgesa.grp\\Cluster GVMNAV6.domgesa.grp","type":70},{"name":"ZZ_Bkp Copy Daily SIA-FS01","type":65},{"name":"Backup Job 22","type":0},{"name":"Backup gvm-vrepo01","type":0},{"name":"ZZ_Bkp Copy Cluster GVM-EKADBN.domgesa.grp\\Cluster GVM-EKADBN.domgesa.grp","type":70},{"name":"ZZ_Bkp Copy Cluster GVM-CRMDBCL.domesa.grp\\Cluster GVM-CRMDBCL.domgesa.grp","type":70},{"name":"Monthly-GVMVC01_02","type":0},{"name":"ZZ_Bkp Copy Daily File+DB VM","type":65},{"name":"ZZ_Bkp Copy Monthly-GVMVC01_LowTier02","type":65},{"name":"ZZ_Bkp Copy DBFILES - Every 2 Hours","type":65},{"name":"Daily File+DB VM","type":0},{"name":"Monthly-GVMVC01_05","type":0},{"name":"Monthly-GVMVC01_04","type":0},{"name":"Bkp Copy Daily SIA-FS01","type":51},{"name":"Cluster GVM-CRMDBCL.domgesa.grp","type":12003},{"name":"Daily SIA-FS01","type":12003},{"name":"ZZ_Bkp Copy Monthly-GVMVC01_04","type":65},{"name":"ZZ_Bkp Copy Monthly-GVMVC01_05","type":65},{"name":"ZZ_Bkp Copy Monthly-GVM-BCVC_TMCH","type":65},{"name":"Monthly-GVM-BCVC_TSIA","type":0},{"name":"ZZ_Bkp Copy Monthly-GVM-BCVC_SAS1","type":65}]

**Comment by garnier-quentin** [comment]
Could you go on your veeam server. Some backup type are missing. Could you execute following command:
```
[Enum]::GetValues('Veeam.Backup.PowerShell.VBRJobType') | Select-Object @{n="Name";e={$_}},@{n="Value";e={$_.value__}} | format-table -autosize
```

I'm not sure about the name: ```Veeam.Backup.PowerShell.VBRJobType```. You need to check it with:
```
Get-VBRJob | get-member
```
