### ISSUE TITLE
Script SSH doesn't work

### ISSUE THREAD

**Issue by EtienneN10** [centreon/centreon-plugins#2761]
Hello

I have to catch the 'Failed' in the log of a synology.
In my centreon server, I run a bash script which works very well :

sshpass -p $1 scp admin@$2:/var/log/synolog/synobackup_server.log /usr/lib/centreon/plugins/synobackup_server_$2.log

ligne_failed=$(cat /usr/lib/centreon/plugins/synobackup_server_$2.log | grep 'Failed' | tail -n 1)

date_last_fail=$(echo $ligne_failed | cut -c5-14)

date_today=$(date +%Y/%m/%d)

date_last_week=$(date --date '8 days ago' +%Y/%m/%d)

if [[ "$date_dernier_fail" == "$date_du_jour" ]]; then
     echo "CRITICAL : $ligne_failed"
     exit 2
else
     if [[ "$date_dernier_fail" > "$date_semaine_avant" ]]; then
          echo "WARNING : $ligne_failed"
          exit 1
     else
          echo "OK : No error this week"
          exit 0
    fi
fi

When  I execute it in the the 'centreon website', the first line : sshpass ... doesn't execute, so the script is useless.

Someone can tell me how can I execute this script in the centreon platform.

Have a good day

**Comment by garnier-quentin** [comment]
Sorry but it's not a centreon-plugins.

**Comment by EtienneN10** [comment]
No.. Is not the good place to post it ?
If it's not, you can delete my post.

Best regards.

**Comment by garnier-quentin** [comment]
You can ask help on slack community channel for example.
