### ISSUE TITLE
[apps::protocols::snmp::plugin] - string-value

### ISSUE THREAD

**Issue by watchix** [centreon/centreon-plugins#2767]
Hi,

the mode "string-value" only returns : "OK: 1 value(s) |" but not the value i can get with "snmpget"
I want to check a firmware value

`[centreon@centreon ~]$ snmpget -v 2c -c public 192.168.1.1 .1.3.6.1.4.1.11256.1.0.2.0
SNMPv2-SMI::enterprises.11256.1.0.2.0 = STRING: "3.4.2"`

`[centreon@centreon ~]$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --hostname=192.168.1.1 --snmp-community=public --snmp-version=2c --oid=.1.3.6.1.4.1.11256.1.0.2.0 --mode=string-value
OK: 1 value(s) |`

`[centreon@centreon ~]$ /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --hostname=192.168.1.1 --snmp-community=public --snmp-version=2c --oid=.1.3.6.1.4.1.11256.1.0.2.0 --mode=numeric-value
UNKNOWN: oid value is not numeric (3.4.2) |`

Regards,

**Comment by garnier-quentin** [comment]
Add following option for example: ```--format-ok='current value is: %{details_ok}'```

**Comment by watchix** [comment]
Hi Quentin,

Thanks for your reply.
It's now ok 👍 

Regards,
