### ISSUE TITLE
[apps::backup::veeam::local::plugin] Missing --use-new-perfdata

### ISSUE THREAD

**Issue by mickael-decastro** [centreon/centreon-plugins#2769]
Hello , 

Option "--use-new-perfdata" is not present on "apps::backup::veeam::local::plugin".  New  performance data output can be a good improvement. 

Current output :
```
> .\centreon_plugins.exe --plugin="apps::backup::veeam::local::plugin"  --mode="job-status" 

OK: Job 'Backup Job A status : Ok [type: Backup] | 'total'=3;;;0;
```

Proposition:
```
> .\centreon_plugins.exe --plugin="apps::backup::veeam::local::plugin"  --mode="job-status"  --use-new-perfdata

OK: Job 'Backup Job A status : Ok [type: Backup] | 'veam.jobs.total'=3;;;0;3
```

thanks

**Comment by itoussies** [comment]
Hi Mickael,

We are gradually applying the new metric convention to each plugin. It should comme soon to the Veeam plugin aswell 😄

**Comment by garnier-quentin** [comment]
it's done in last version
