### ISSUE TITLE
[hardware::printers::standard::rfc3805::plugin] Long labels in perfdata

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2774]
Hello.

When we try to use "**markersupply-usage**" mode for **Xerox** printers, we get very long labels. 
These names contain many different special characters that can create a problem for metrics in Carbone/Grafana

```
# /centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin 
--mode=markersupply-usage
--critical='1:' --warning='2:'
--hostname='PRN01' --snmp-community='public' --snmp-version='2c'

OK: Marker supply usages are ok. | 
'Xerox Black Toner Cartridge, Replace with P/N 106R03773,106R03621,106R03623; S/N CRUM-16010680045#Black'=50.00%;2:;1:;0;100 
'SMart Kit Drum Cartridge, Replace with P/N 650N05435; S/N CRUM-18061046844#Black'=63.00%;2:;1:;0;100
```

How can we shorten or truncate the names of these metrics? 
And how can we exclude special characters in names?

**Comment by garnier-quentin** [comment]
You can use the option --change-perfdata=oldlabel,newlabel

**Comment by Aleksey-Maksimov** [comment]
I have tried but with no success.

For example, please tell me how to replace the long name by mask with another name.
"^Toner Cartridge$" for a short name like "Toner Cartridge"

**Comment by garnier-quentin** [comment]
Something like that ? ```--change-perfdata=".*Toner Cartridge.*,Toner Cartridge"```

**Comment by Aleksey-Maksimov** [comment]
Yes. So we were able to shorten the name.

```
... 
--change-perfdata='.*Black Toner Cartridge.*,Black Toner Cartridge' 
--change-perfdata='.*SMart Kit Drum Cartridge.*Black.*,Black SMart Kit Drum Cartridge'

OK: Marker supply usages are ok. | 
'Black Toner Cartridge'=50.00%;2:;1:;0;100 
'Black SMart Kit Drum Cartridge'=63.00%;2:;1:;0;100
```
The only pity is that for a color device the command will be very long, since we will have to add additional parameters in --change-perfdata for each color. 

Thanks, Quentin
