### ISSUE TITLE
[hardware::printers::standard::rfc3805::plugin] Printer '1' status is 'jammed'

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2784]
Hello,

We have several large **Kyocera ECOSYS M8130cidn** color printers. 
It looks like these printers have some kind of problem with the **hrPrinterDetectedErrorState** OID (.1.3.6.1.2.1.25.3.5.1.2)

This is how the data looks on the printer, where everything is fine, but the toner is almost empty: 

```
snmpwalk -ObentU -v 2c -c public PR143 .1.3.6.1.2.1.25.3.5.1.2

.1.3.6.1.2.1.25.3.5.1.2.1 = STRING: " "
```

The plugin shows the "jammed" status. 

```
# ./centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin 
--mode=printer-error 
--hostname=PR143 --snmp-community=public --snmp-version=2c --verbose

WARNING: Printer '1' status is 'jammed' |
checking printer '1'
    status is 'jammed'
```

In fact, there was no jam on the printer. 

And this is how the printer looks like, on which everything is fine: 

```
snmpwalk -ObentU -v 2c -c public PR149 .1.3.6.1.2.1.25.3.5.1.2

.1.3.6.1.2.1.25.3.5.1.2.1 = Hex-STRING: 00
```

It looks like if the printer returns `STRING: " "` then the plugin will mistakenly consider it status 5 ('jammed').

**Comment by garnier-quentin** [comment]
I don't understand. So in your case, you should get: ```lowToner``` (bits 2) ? (not ```jammed``` (bits 5) ?)

**Comment by Aleksey-Maksimov** [comment]
Okay. I understood. Thanks for clarifying.

**Comment by garnier-quentin** [comment]
Maybe it's an endian issue. Your printer is a big-endianness maybe ? If we return:
```
lowPaper              7              
noPaper               6
lowToner              5
noToner               4
doorOpen              3
jammed                2
offline               1
serviceRequested      0
```
And in that case, we have 'lowToner'... If it's that i cannot guess the endian. But i can add an option to manage it.

**Comment by Aleksey-Maksimov** [comment]
> Your printer is a big-endianness ?
I don't know how I can check this. If only you tell me :) 

But I understand one thing for sure. When this printer model runs out of toner, it is indeed the same as the "jummed" status message of the plugin

**Comment by garnier-quentin** [comment]
Maybe you can ask to the printer support, the technical documentation,... ? I don't know

**Comment by garnier-quentin** [comment]
It's only an information in our case. I could add an option. It costs nothing ;)

**Comment by garnier-quentin** [comment]
You're welcome!
