### ISSUE TITLE
cloud::azure::management::apimanagement::plugin health mode issue

### ISSUE THREAD

**Issue by matoy** [centreon/centreon-plugins#2791]
Hi,

This plugin offers a mode "health".

There is no centreon-plugins/cloud/azure/management/apimanagement/mode/health.pm file in the repo.
the file is missing.

This leads to this error when executing the plugin with this mode:
UNKNOWN: Cannot load module --mode.
Can't locate cloud/azure/management/apimanagement/mode/health.pm in @INC (@INC contains: /usr/lib/centreon/plugins/centreon-plugins /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/misc.pm line 222.

Thank you.

Regards,

**Comment by itoussies** [comment]
Hi,

Unfortunately, this mode is not available for this plugin. It wil be fixed soon.

Thank you.

**Comment by matoy** [comment]
/usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=cloud::azure::management::apimanagement::plugin --custommode='api' --list-mode

Modes Available:
   discovery
   duration
   events
   health
   requests

as help says, "health" mode is available.

**Comment by itoussies** [comment]
I mean it should not be available. I forgot to erase the mode reference in centreon-plugins/cloud/azure/management/apimanagement/plugin.pm
