### ISSUE TITLE
[storage::hp::p2000::xmlapi::plugin] mode "health" (sensors) and HP MSA P2000 G3 Storage

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2793]
Hello,

We have previously addressed one problem with the "health" mode  #2339 
It looks like I found a new problem that is somewhat similar to the old one. 

If we carefully examine what the plugin returns to us through the "**sensor**" filter and compare it with the XML API output, we will see that some of the data has been lost. 

For example, we have two different storage systems with different numbers of disk shelves. And of course, these two storage systems have a different number of sensors. However, the plugin returns the same number of sensors for both storage systems. 

```
# ./centreon_plugins.pl --plugin=storage::hp::p2000::xmlapi::plugin --mode=health --hostname='MSA01' 
--username='mon' --password='*' 
--proto=https --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" 
--component=sensor --filter-perfdata='^(?!count_)'

OK: All 43 components are ok [43/43 sensor]. | ...
```

```
# ./centreon_plugins.pl --plugin=storage::hp::p2000::xmlapi::plugin --mode=health --hostname='MSA02' 
--username='mon' --password='*' 
--proto=https --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" 
--component=sensor --filter-perfdata='^(?!count_)'

OK: All 43 components are ok [43/43 sensor]. | ...
```

I compared the data from the plugin and the XML API output in the browser and found that components with a duplicate "Sensor Name" field are being lost. For example, "Temperature Loc: lower-IOM B" or "Temperature Loc: right-PSU". 

The attachment contains the XML API output for both storage systems. It shows that the lost components actually have different "Durable ID" and "Enclosure ID"

[HP_MSA_P2000_G3_Sensors_XML_API_Output.zip](https://github.com/centreon/centreon-plugins/files/6466737/HP_MSA_P2000_G3_Sensors_XML_API_Output.zip)

**Comment by garnier-quentin** [comment]
You can test with last version (commit: de441cd5bf545596c71348bcf5167af970163205)

**Comment by Aleksey-Maksimov** [comment]
Now it looks like the truth. 
Thank you very much Quentin.

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin. 
I found the problem in "health / sensors" mode. 
It seems that setting the thresholds does not affect the result of the plugin (OK state does not change to WARNING)

```
# /centreon_plugins.pl '--plugin=storage::hp::p2000::xmlapi::plugin' 
'--mode=health' '--component=sensor' 
'--curl-opt' 'CURLOPT_SSL_VERIFYPEER => 0' '--curl-opt' 'CURLOPT_SSL_VERIFYHOST => 0' 
'--filter-perfdata' '^(?!(hardware.sensor.count))' 
'--filter-uom' 'null' 
'--hostname' 'MSA01' '--http-backend' 'curl' '--password' '***' 
'--proto' 'https' '--use-new-perfdata' '--username' 'mon' --warning='sensor,temperature.*,60'

OK: Sensor 'Memory Controller Temp-Ctlr B' is 62 C - All 51 components are ok [51/51 sensor]. | 
...'Memory Controller Temp-Ctlr B#hardware.sensor.temperaturecelsius'=62;0:60;;; ...
```

**Comment by garnier-quentin** [comment]
thanks for the feedback. it should be fixed in last git version. Could you test it ?

**Comment by Aleksey-Maksimov** [comment]
Thanks, Quentin. Now everything is all right.
