### ISSUE TITLE
Failed load token all pugin cloud::azure::...

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2796]
Hello,

As explained in the ticket created on the azcli github:

https://github.com/Azure/azure-cli/issues/17962

From time to time (about every week) all my checks go to: UNKNOWN: Command error: ERROR: Failed to load token files. If you have a repro, please ...

I have to restart the login procedure to make it work for about 1 week, sometimes less.

Do you have a lasting solution? 

Thank you

**Comment by garnier-quentin** [comment]
You connect with a new user if i understand and azcli cannot manage concurrent access. 

If you want to keep azcli, could you try to set the environment variable ```AZURE_CONFIG_DIR``` ?
https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#concurrent-builds

Otherwise you can use option: ```--customode=api```

**Comment by prohand** [comment]
Hello,

No and I think it's a misunderstanding of the person who handled the ticket on the azcli github.

The problem is that every now and then I get the message "Failed to load token" that appears.

I have to disconnect the session with:
az account clear
and reconnect with azlogin

I use the same account for all my checks.

Maybe this is not suitable for my situation and I should use the API?

Thank you

**Comment by garnier-quentin** [comment]
Yes. You should try the API directly. It will be faster than azcli.

**Comment by prohand** [comment]
Is the change really difficult to implement or is it just that you have to put api instead of azcli?

Thank you

**Comment by garnier-quentin** [comment]
You can try. You only need to put api instead of azcli

**Comment by prohand** [comment]
Ok thank you ;)

**Comment by prohand** [comment]
I find and is very easy ;)
Thank you
