### ISSUE TITLE
[os::aix::snmp::plugin] Extended output of interfaces mode

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#280]
For some NICs, the return name is not clean :
Interface **en0; Product: Virtual I/O Ethernet Adapter (l-lan) Manufacturer: not available! Part Number: not available! FRU Number: not available!** Status : up (admin: up), Traffic In : 5.98Kb/s (0.00%), Traffic Out : 32.79Kb/s (0.00%)
Interface ent2 Status : up (admin: up), Traffic In : 179.37b/s (0.00%), Traffic Out : 155.02b/s (0.00%)
Interface **en1; Product: Virtual I/O Ethernet Adapter (l-lan) Manufacturer: not available! Part Number: not available! FRU Number: not available!** Status : up (admin: up), Traffic In : 41.68Kb/s (0.00%), Traffic Out : 36.74Kb/s (0.00%)
Interface lo0 Status : up (admin: up), Traffic In : 856.21b/s (-), Traffic Out : 856.21b/s (-)

We can manage the perfdata with the *--change-perfdata* arguments.

**Comment by garnier-quentin** [comment]
Please use following options. Should be better ;)
```
--verbose --oid-filter="ifdesc" --oid-display="ifdesc" --display-transform-src='^([a-zA-Z0-9 ]+).*' --display-transform-dst='$1'
```

**Comment by dooko** [comment]
Haaan ok. Missed that one.
Works fine.
Thanks!

**Comment by garnier-quentin** [comment]
You're welcome!
