### ISSUE TITLE
Perfdata labels in different plugins. How to replace special characters (regex)?

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#2801]
Hello.

Many plugins have different output of perfdata labels. 
Somewhere the old "data_label_node" format is used, and somewhere the new "node#label.type.unit" format can be used. Moreover, the names of the nodes themselves may contain different special characters on the devices.

An example of an interface metric name from one of the switches:

```
sfp-sfpplus1 (I-ISP One $ Provider)#interface.traffic.out.bitspersecond
sfp-sfpplus2 (I-ISP i-Boom! Provider)#interface.traffic.out.bitspersecond
```
Using some special characters creates problems in different places. 
For example, there may be problems with saving metrics in Icinga / Nagios, or Grafana graphs may not work correctly. 

Please tell me how we can replace special characters in the name of the metric. 
For example, how can we remove all spaces, brackets, dashes, and so on from the metric name.

I know there is a global option `--change-perfdata='old label','new label'`. 
But if I understand correctly, this option only changes the first match in the line and this option has to be called many times. 
Is there a more flexible mechanism, such as using "sed" search and replace?

**Comment by garnier-quentin** [comment]
An issue is already created: https://github.com/centreon/centreon-plugins/issues/2650
I think it's the same issue.

**Comment by Aleksey-Maksimov** [comment]
Yes. It looks like it.

**Comment by garnier-quentin** [comment]
So i close it. I will do a patch soon for that issue.

**Comment by garnier-quentin** [comment]
You can test with last version. Example to remove characters 'a', 'i' and 'z' from perfdata labels:
```
--change-perfdata='.*,,eval(%(label) =~ s/[aiz]//g)'
```

**Comment by Aleksey-Maksimov** [comment]
It seems to work. Thanks a lot Quentin.
