### ISSUE TITLE
storage::qnap::snmp::plugin --mode=hardware and --mode=memory on qnap TES-1885U(QES)

### ISSUE THREAD

**Issue by gverrey** [centreon/centreon-plugins#2809]
Hello,

Here the issue.
We can check cpu, interfaces, storage but it doesn't work with hardware, memory, volume-usage

I put the command line and output and give you the mibs file here https://conectia94-my.sharepoint.com/:u:/g/personal/guillaume_verrey_conectia_fr/ETEfHoLmTn5InwbIC4tbCToBgjh5nXdmRXVJqfLSb04w3g?e=ejINsK

NOT OK (hardware -> the most important :/, memory, volume-usage)
-------------------------------------------------------------------------------------------
[root@centreon ~]# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::qnap::snmp::plugin --hostname 10.10.20.101 --snmp-community conectia --snmp-version 2c --snmp-timeout 20 --mode=hardware --verbose
OK: All 0 components are ok []. |
Checking disks
Checking fans
Checking power supplies
Checking raids
Checking temperatures

[root@centreon ~]# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::qnap::snmp::plugin --hostname 10.10.20.101 --snmp-community conectia --snmp-version 2c --snmp-timeout 20 --mode=memory
UNKNOWN: SNMP GET Request : Cant get a single value.

[root@centreon ~]# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::qnap::snmp::plugin --hostname 10.10.20.101 --snmp-community conectia --snmp-version 2c --snmp-timeout 20 --mode=volume-usage
UNKNOWN: SNMP Table Request: Cant get a single value.

OK (cpu, interfaces, storage)
-------------------------------------------------------------------------------------------
[root@centreon ~]# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::qnap::snmp::plugin --hostname 10.10.20.101 --snmp-community conectia --snmp-version 2c --snmp-timeout 20 --mode=cpu
OK: 8 CPU(s) average usage is 11.00 % | 'total_cpu_avg'=11.00%;;;0;100 'cpu_0'=7.00%;;;0;100 'cpu_1'=11.00%;;;0;100 'cpu_2'=9.00%;;;0;100 'cpu_3'=13.00%;;;0;100 'cpu_4'=12.00%;;;0;100 'cpu_5'=14.00%;;;0;100 'cpu_6'=12.00%;;;0;100 'cpu_7'=10.00%;;;0;100

[root@centreon ~]# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::qnap::snmp::plugin --hostname 10.10.20.101 --snmp-community conectia --snmp-version 2c --snmp-timeout 20 --mode=storage
OK: All storages are ok | 'count'=16;;;0; 'used_/'=789196800B;;;0;1268054016 'used_/dev'=1024B;;;0;1024 'used_/etc'=7049216B;;;0;9334784 'used_/log'=17420288B;;;0;491024384 'used_/mnt'=12288B;;;0;749568 'used_/qessroot'=16384B;;;0;749568 'used_/share'=16384B;;;0;4485120 'used_/share_remote'=12288B;;;0;749568 'used_/tmp'=111886336B;;;0;687632384 'used_/var'=10276864B;;;0;196112384 'used_/sysopt'=661192704B;;;0;3041132544 'used_/nas/sysdata'=789196800B;;;0;1268054016 'used_/nas/var'=789196800B;;;0;1268054016 'used_/nas/nvdata'=789196800B;;;0;1268054016 'used_/sysa'=19189760B;;;0;3067584512 'used_/syspool'=19189760B;;;0;3067584512

[root@centreon ~]# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::qnap::snmp::plugin --hostname 10.10.20.101 --snmp-community conectia --snmp-version 2c --snmp-timeout 20 --mode=interfaces --verbose
OK: All interfaces are ok |
Interface 'ix0' Status : up (admin: up)
Interface 'igb3.25' Status : up (admin: up)
Interface 'igb0.25' Status : up (admin: up)
Interface 'ix1' Status : up (admin: up)
Interface 'igb0' Status : up (admin: up)
Interface 'igb1' Status : up (admin: up)
Interface 'igb2' Status : up (admin: up)
Interface 'igb3' Status : up (admin: up)
Interface 'lo0' Status : up (admin: up)
Interface 'igb1.20' Status : up (admin: up)
Interface 'igb2.25' Status : up (admin: up)

**Comment by garnier-quentin** [comment]
Could you do a snmpwalk of following branch: .1.3.6.1.4.1.24681 ?
And also: .1.3.6.1.4.1 ?

**Comment by gverrey** [comment]
snmpwalk 10.10.20.101 -c conectia -v1 .1.3.6.1.4.1.24681
https://conectia94-my.sharepoint.com/:t:/g/personal/guillaume_verrey_conectia_fr/EeIYo9sSZj5DgeR1Fax_md8BwEOkVvABacDOT2oorGoC_A?e=8ejUzY

snmpwalk 10.10.20.101 -c conectia -v1 .1.3.6.1.4.1
https://conectia94-my.sharepoint.com/:t:/g/personal/guillaume_verrey_conectia_fr/EXDVhb78f8BIkKQ6Qhb1F8YBDnzWmxeruPIyb9AyMWahnw?e=A9qgpQ

**Comment by garnier-quentin** [comment]
Thanks. 

It seems there is a specific MIBs for qnap es serie. We need to create a new plugin i think.

**Comment by gverrey** [comment]
Thank you.
That's what I was telling myself. They did things differently with the QES series. If you need more information or to test a few things, I am at your disposal.

**Comment by UrBnW** [comment]
Perhaps #2728 helps ?

**Comment by garnier-quentin** [comment]
You can test with last version!

**Comment by gverrey** [comment]
I love you Quentin :-) This is perfect !!

[image: image.png]

**Comment by garnier-quentin** [comment]
thanks for the feedback. I love you too (it's our little secret :)

**Comment by gverrey** [comment]
LOOOOL :D :D :D
