### ISSUE TITLE
[database::mssql::plugin] How to connect to server

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#281]
I don't understand how to connect to a MSSQL server. Does it works with Freetds ?

UNKNOWN: Cannot connect: OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (44)
Server , database 
Message String: Server name not found in configuration files.
OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (45)
Server , database 
Message String: Unknown host machine name.

**Comment by garnier-quentin** [comment]
Yes it works. Don't forget to set the port option and also not to have a freetds version = 0.91 (older is ok). Also need to configure the freetds.conf and configure 8.0

**Comment by dooko** [comment]
I try with freetds v0.82
$ tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.82
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 5.0
                              iODBC: no
                           unixodbc: no

Same result.
The tsql command line and the check_mssql_health plugin work fine.

Is that normal that we don't have anything after *Server* in the error message : 
UNKNOWN: Cannot connect: OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (44)
Server **???** , database 
Message String: Server name not found in configuration files.
...

**Comment by garnier-quentin** [comment]
Please give me the command line.

**Comment by dooko** [comment]
./centreon_plugins.pl --plugin=database::mssql::plugin --hostname=*** --username=*** --password='***' --port='1433' --mode='connected-users'

**Comment by garnier-quentin** [comment]
Do you use tds version 8.0 for the global section in freetds.conf ?

**Comment by dooko** [comment]
Yes

**Comment by joschi99** [comment]
I have the same issue. The tsql command line and the check_mssql_health plugin work fine, the centreon plugin returns the error

CRITICAL: Cannot connect: OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (44)
Server , database
Message String: Server name not found in configuration files.
OpenClient message: LAYER = (0) ORIGIN = (0) SEVERITY = (78) NUMBER = (45)
Server , database
Message String: Unknown host machine name. |

**Comment by garnier-quentin** [comment]
Could you have the command line ?

**Comment by joschi99** [comment]
```
perl centreon_plugins.pl --plugin=database::mssql::plugin --hostname=10.67.4.52 --port=1433 --mode=connection-time --username=* --password=*

./check_mssql_health --server=10.67.4.52 --username=* --password=* --mode=connection-time
```
* = user or password

**Comment by garnier-quentin** [comment]
Could you set the port also ?

**Comment by joschi99** [comment]
```
./check_mssql_health --server=10.67.4.52 --username=* --password=* --mode=connection-time --port=1433
OK - 0.02 seconds to connect as nagios | connection_time=0.02;1;5
```
works perfect also with port option

**Comment by garnier-quentin** [comment]
Could you send me if you are available for a teamviewer session  ?

Thanks.

**Comment by joschi99** [comment]
For shure we can do a teamviewer session.

- 02.02: 09:00
- 01.02: 09:00
- 04.02: 14:00

Let me know what time is ok for you.

**Comment by garnier-quentin** [comment]
The 04.02 is ok. Could you send me an email ? I'll send you a link.

**Comment by joschi99** [comment]
@garnier-quentin  Did you received me calendare? Everything ok for today?

**Comment by garnier-quentin** [comment]
Yes. I send you a link at 3 pm french time.

**Comment by garnier-quentin** [comment]
I don't manage instance in freetds.conf. Because i don't want to add configuration in a local file. 
Moreover, there is a bug with freetds 0.91: http://sourceforge.net/p/freetds/patches/133/
You need a lower or higher version. I close the ticket. You can contact me by email @dooko if you want to do a session and see exactly.

**Comment by joschi99** [comment]
I checked out my freetds version with tsql -C and I have installed:
```
[root@osiris2 bin]# ./tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.95.18
             freetds.conf directory: /usr/local/freetds/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 5.0
                              iODBC: no
                           unixodbc: no
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: no
                             GnuTLS: no
```

**Comment by garnier-quentin** [comment]
You need to be in tds version 8.0.

**Comment by joschi99** [comment]
tds is in version 8.0

**Comment by garnier-quentin** [comment]
And it's not working with the new one ?

**Comment by joschi99** [comment]
freetds was always on the new version. there was also a old version 0.91 installed, but it was not active. so the problem is not version 0.91

**Comment by garnier-quentin** [comment]
Maybe there is still the bug in newer version. We can use option like that:
--datasource='Sybase:server=instancename'

**Comment by joschi99** [comment]
I found the solution -> https://github.com/joschi99/Osiris/issues/35
