### ISSUE TITLE
cloud::azure::web::appservice::plugin mode status BadRequests

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2812]
Hello,

I use this command command : 

/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::web::appservice::plugin --custommode='api' --mode='status' --tenant='xxxx' --client-id='xxxxx' --client-secret='xxxx' --resource='/subscriptions/xxxxx/resourceGroups/xxxxxx/providers/Microsoft.Web/sites/xxxx' --timeout 60 --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True" --subscription 'xxxxx'

I have this error : 

UNKNOWN: Management endpoint API returns code 'BadRequest' (add --debug option for detailed message)

Thank you

**Comment by thibaults-centreon** [comment]
Hello, can you please provide the --debug result ?

**Comment by prohand** [comment]
Can i send the debug to an email ?

Thank you

**Comment by thibaults-centreon** [comment]
yes please, to tscheitenberger(\\at\\)centreon.com

**Comment by prohand** [comment]
I have send the email ;)
Thank you
