### ISSUE TITLE
network::cisco::standard::snmp::plugin Checking Stack issue with Virtual-Stackwise

### ISSUE THREAD

**Issue by bricemoi** [centreon/centreon-plugins#2818]
Hi

After upgrading ios to 16.12.04 on cisco C9500-40X, it seems the check for the stack when virtual-stackwise is not working correctly anymore.

Full-Command line:
/usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=stack --hostname=xxxxx --snmp-version='2c' --snmp-community='xxxx'  --warning-waiting='' --critical-waiting='' --warning-progressing='' --critical-progressing='' --warning-added='' --critical-added='' --warning-ready='' --critical-ready='' --warning-sdm-mismatch='' --critical-sdm-mismatch='' --warning-version-mismatch='' --critical-version-mismatch='' --warning-feature-mismatch='' --critical-feature-mismatch='' --warning-new-master-init='' --critical-new-master-init='' --warning-provisioned='' --critical-provisioned='' --warning-invalid='' --critical-invalid='' --warning-removed='' --critical-removed='' --warning-status='' --critical-status='%{state} !~ /ready/ && %{state} !~ /provisioned/' --warning-stack-status='' --critical-stack-status='%{stack_status} =~ /notredundant/' --verbose

The current output:

> CRITICAL: Stack status is 'notredundant'
> 
> Member '0' State is 'ready', Role is 'master'
> 
> Member '1' State is 'ready', Role is 'standby'

On another (working) stack (not virtual this time) I get with the same command-line:

> OK: Stack status is 'redundant' - Number of members Waiting: 0, Progressing: 0, Added: 0, Ready: 3, SDM Mismatch: 0, Version Mismatch: 0, Feature Mismatch: 0, New Master Init: 0, Provisioned: 0, Invalid: 0, Removed: 0 - All stack members status are ok
> 
> Member '0' State is 'ready', Role is 'master'
> 
> Member '1' State is 'ready', Role is 'standby'
> 
> Member '1' State is 'ready', Role is 'standby'
> 
> Member '2' State is 'ready', Role is 'member'
> 

Let me know if you need more information
Thanks in advance!

**Comment by garnier-quentin** [comment]
Could you provide the mib of your equipment and a snmpwalk ? It seems more like a cisco issue or cisco break oid status.

**Comment by bricemoi** [comment]
> Could you provide the mib of your equipment and a snmpwalk ? It seems more like a cisco issue or cisco break oid status.

hi, i'm not sure which MIB from this list ftp://ftp.cisco.com/pub/mibs/supportlists/cat9500/CAT9500.html

also, regarding the snmpwalk, is it possible to send it to you through PM ? (or do you have any clue to anonymize it?)

**Comment by Sims24** [comment]
You can send it to qgarnier@centreon.com please.

**Comment by bricemoi** [comment]
hi, 
did you get the files or do you want me to look into something else ?
thanks

**Comment by garnier-quentin** [comment]
I didn't get the file sorry. Could you provide snmpwalk of following branch ?
.1.3.6.1.4.1.9.9.500

**Comment by joschi99** [comment]
Thanks, I will check this and update you asap.

**Comment by garnier-quentin** [comment]
You can comment it if you have the response of Cisco

**Comment by Cancom-Monitoring** [comment]
Hi, 
in [#1487](https://github.com/centreon/centreon-plugins/issues/1487) I mentioned, that I've same issue with cisco stackwise-virtual switches. Same return of plugin:
`CRITICAL: Stack status is 'notredundant'`

I am a little bit confused, that this check was running @bricemoi:

> After upgrading ios to 16.12.04 on cisco C9500-40X, it seems the check for the stack when virtual-stackwise is not working correctly anymore.

Are you sure, that you were running the check against a stackwise-virtual switch (and not a stackwise switch)?

Cause: **stackwise != stackwise-virtual**

in stackwise-virtual, a ring does not exist, so I am wondering, how this OID ever should have been working.
That's the reason, why network guys sent me these OID's for stackwise-virtual:

Cisco-Stack-Master-Status OID: 1.3.6.1.4.1.9.9.500.1.2.1.1.6.2

type value description alerting
Integer 1 Waiting Warning
Integer 2 Progressing Warning
Integer 3 Added Warning
Integer 4 Ready Good
Integer 5 sdmMismatch Critical
Integer 6 VerMismatch Critical
Integer 7 featureMismatch Critical
Integer 8 newMasterInit Warning
Integer 9 Provisioned Critical
Integer 10 Invalid Critical
Integer 11 Removed Critical

Cisco-Stack-Master-Role OID: 1.3.6.1.4.1.9.9.500.1.2.1.1.3.2

type value description alerting
Integer 1 Master Good
Integer 2 Member Critical
Integer 3 notMember Warning
Integer 4 Standby Warning

Cisco-Stack-Member-Status OID: 1.3.6.1.4.1.9.9.500.1.2.1.1.6.500

type value description alerting
Integer 1 Waiting Warning
Integer 2 Progressing Warning
Integer 3 Added Warning
Integer 4 Ready Good
Integer 5 sdmMismatch Critical
Integer 6 VerMismatch Critical
Integer 7 featureMismatch Critical
Integer 8 newMasterInit Warning
Integer 9 Provisioned Critical
Integer 10 Invalid Critical
Integer 11 Removed Critical

Cisco-Stack-Member-Role OID: 1.3.6.1.4.1.9.9.500.1.2.1.1.3.500

type value description alerting
Integer 1 Master Warning
Integer 2 Member Critical
Integer 3 notMember Warning
Integer 4 Standby Good

**Comment by garnier-quentin** [comment]
Ok i understand. So you can set following option to ignore the ring status: ```--critical-stack-status=''```
