### ISSUE TITLE
Add support for TP Link switches

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2824]
Could you add support for TP Link switches:

- Uptime (standard)
- Interfaces (standard)
- CPU
- Memory
https://www.tp-link.com/it/support/faq/1330/

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk and mibs files ?

**Comment by joschi99** [comment]
[tplink.zip](https://github.com/centreon/centreon-plugins/files/6537264/tplink.zip)

**Comment by garnier-quentin** [comment]
Do you have mibs files also ?

**Comment by joschi99** [comment]
[T2600G-28TS(UN)_v4_MIB_20190530.zip](https://github.com/centreon/centreon-plugins/files/6539417/T2600G-28TS.UN._v4_MIB_20190530.zip)
This is from a more recent TP Link switch, but I hope that is still the same standard

**Comment by garnier-quentin** [comment]
You can test it with last git version: ```--plugin=network::tplink::snmp::plugin```

**Comment by joschi99** [comment]
Done some test, seems working. Thanks
