### ISSUE TITLE
apps::voip::asterisk::snmp::plugin - mode channel-usage results in 'can't get a single value' error

### ISSUE THREAD

**Issue by MarOwNFR** [centreon/centreon-plugins#2833]
Hello again everyone!

I take advantage of the great reactivation on this git to ask another question that has nothing to do with my last issue.

I am trying to monitor a Xivo server on Centreon, but when I try the command below, I get the following error :

`/usr/lib/centreon/plugins/centreon_asterisk_snmp.pl --plugin=apps::voip::asterisk::snmp::plugin --mode=channel-usage --hostname='**.**.**.**' --snmp-version='2c' --snmp-community='***' --warning-channels-active='' --critical-channels-active='' --warning-calls-active='' --critical-calls-active='' --warning-calls-count='' --critical-calls-count='' `

Error : 
`UNKNOWN: SNMP GET Request : Cant get a single value.`

I think I have correctly configured SNMP on Xivo and on the OS but this error occurs

Centreon 21.04.0
Plugins : XiVO VoIP Server (v.3.0.10) and Asterisk VoIP SNMP (v.3.1.1)

Thank you in advance for your help once again!

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk of following branch .1.3.6.1.4.1.22736 ?

**Comment by MarOwNFR** [comment]
It's just below 😃 
(Performed from the Xivo server itself)

`snmpwalk -v 3 -u snmp -l authPriv -a SHA -A "gcfyuighg5r561256rgtGTREFDSEGR" -x AES -X "gcfyuighg5r561256rgtGTREFDSEGR" 127.0.0.1 .1.3.6.1.4.1.22736`

Result : 
`iso.3.6.1.4.1.22736 = No Such Object available on this agent at this OID`

Thank you for your help!

**Comment by garnier-quentin** [comment]
Something is missing in you snmp configuration. Or asterisk use new snmp oids.

**Comment by MarOwNFR** [comment]
Hello !

After analysis of SNMP on my machine I had indeed problems of configuration, the MIB did not load

However, during a test with "snmpwalk", I have this error which occurs and I block completely for hours, in spite of many searches...

command :
`snmpwalk -v 3 -u *** -l authPriv -a SHA -A "***" -x AES -X "***" 127.0.0.1 .1.3.6.1.4.1.22736`

Result:
`SNMPv2-SMI::enterprises.22736 = No Such Object available on this agent at this OID`

However the problematic MIB is well installed and I think loaded

/etc/snmp/snmp.conf
```
mibdirs +/usr/share/snmp/mibs
mibdirs +/usr/share/snmp/mibs/iana
mibdirs +/usr/share/snmp/mibs/ietf
```

Thank you in advance for your help!

**Comment by Sims24** [comment]
Hi, 

Can you confirm that you followed the steps described here: 
https://techexpert.tips/fr/asterisk-fr/configuration-snmp-dasterisque/

Thanks

**Comment by MarOwNFR** [comment]
Hello,

Thank you for your feedback.

Yes, I have followed these steps but the problems start from the command:

`snmpwalk -v2c -c *** 127.0.0.1 1.3.6.1.4.1.22736.1`

Result :

`SNMPv2-SMI::enterprises.22736.1 = No Such Object available on this agent at this OID`

or : 

`iso.3.6.1.4.1.22736.1 = No Such Object available on this agent at this OID`

However in the Xivo console I have this result:

```
Module             Description                    Use Count  Status      Support Level
res_snmp.so        SNMP [Sub]Agent for Asterisk   0          Running     extended
1 modules loaded
```

Thank you in advance for your help !

**Comment by Sims24** [comment]
Please follow also this chapter: "Didacticiel - Installation de la base MIB Asterisk" I don't know why it's at the end but the Plugin need these files.

**Comment by Sims24** [comment]
Did you succeed in monitoring your Asterisk OIDs?

**Comment by garnier-quentin** [comment]
@MarOwNFR Did you still have the issue ?
