### ISSUE TITLE
network::cisco::standard::snmp::plugin - override mib defined temperature thresholds (warning)

### ISSUE THREAD

**Issue by trentasis** [centreon/centreon-plugins#2835]
Hi,

Monitoring a cisco switch I recieve an alert about temperature (low):

  perl centreon_plugins.pl --hostname=10.10.10.1 --plugin=network::cisco::standard::snmp::plugin --snmp-version=2c --snmp-community=comm --mode=environment
WARNING: Sensor 'Switch 1 - C9200L-48P-4X - Temp Inlet Sensor 0/1010' is 27 C | 'temp_Switch 1 - Inlet Temp Sensor, GREEN '=27C;;~:56;; 'temp_Switch 1 - Outlet Temp Sensor, GREEN '=36C;;~:125;; 'temp_Switch 1 - HotSpot Temp Sensor, GREEN '=49C;;~:125;; 'sensor.celsius_Switch 1 - C9200L-48P-4X - Temp Outlet Sensor 1'=36C;;-9:124;; 'sensor.celsius_Switch 1 - C9200L-48P-4X - Temp Hotspot Sensor 2'=49C;;-9:124;; 'sensor.celsius_Switch 1 - C9200L-48P-4X - Temp Inlet Sensor 0'=27C;32:45;-9:55;; 'count_fan'=4;;;; 'count_module'=1;;;; 'count_psu'=2;;;; 'count_sensor'=3;;;; 'count_temperature'=3;;;;

It seems that default value is warning min 32 and warning max 45, I have tried 
--warning='temperature,.*,50'
or
--warning='temperature,.*,20'
but same result, warning received, how can I change this default value min and max to remvoe this warning?

Thanks

**Comment by Sims24** [comment]
Hi @trentasis , 

You should use this syntax: 

`--warning='sensor.celsius,.*,50'`

Option above will trigger a warning when any celsius sensor will raise 50°C. You can if you want specify one specific sensor replacing '.*' regex by the instance of the sensor (you can see it in the long output using verbose option). 

Thanks

**Comment by trentasis** [comment]
Solved thanks, no really sure ahy was showing warnign output 32 when seems that issue was generated by a higher temp
Thanks
