### ISSUE TITLE
plugin apps::protocols::imap::plugin --mode login

### ISSUE THREAD

**Issue by Rico29** [centreon/centreon-plugins#2836]
Strange behavior sometimes with plugin apps::protocols::imap::plugin --mode login

when working correctly, centreon-plugin send a login, gets a OK, sends an EXPUNGE, gets an BAD invalid command, then send a LOGOUT.

But sometimes, centreon-plugin sends its LOGOUT before getting the response to EXPUNGE command (the BAD invalid command). In this case, the plugins does not exit before 60 seconds.

command used : 

/usr/bin/perl /usr/lib64/centreon-plugins/centreon_plugins.pl --plugin apps::protocols::imap::plugin --mode login --hostname 10.4.0.23 --timeout 1

tcpdump capture (on imap server) when working correctly : https://file.io/Vn5cd5rA3edH
tcpdump capture (on imap server) when problkem occurs : https://file.io/6J7IihcDw8q4

Regards
Cédric

**Comment by garnier-quentin** [comment]
There is an expunge it seems: https://metacpan.org/release/Net-IMAP-Simple/source/lib/Net/IMAP/Simple.pm#L878
I don't know why..

Maybe i should use that library now:
https://metacpan.org/pod/Mail::IMAPClient

**Comment by Rico29** [comment]
@garnier-quentin do  you plan to make changes to the plugin and use this lib ?

**Comment by garnier-quentin** [comment]
It should be ok now: https://github.com/centreon/centreon-plugins/pull/3924
