### ISSUE TITLE
Rate Limit reached with the Meraki API plugin

### ISSUE THREAD

**Issue by jaltmeyer** [centreon/centreon-plugins#2837]
Hello,

With the network::cisco::meraki::cloudcontroller::restapi::plugin Plugin, the Rate Limit for this API is reached each time the services are scheduled, and ends with "_{"errors":["API rate limit exceeded for organization"]}_".

Cf : https://developer.cisco.com/meraki/api/#!rate-limit

This plugin needs something like the Centreon connectors, but for this API.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3466
