### ISSUE TITLE
switch sensor monitoring

### ISSUE THREAD

**Issue by Rico29** [centreon/centreon-plugins#2840]
Hello
Trying to monitor optical sensors on a cisco switch with command : 

/usr/bin/perl /usr/lib64/centreon-plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --mode environment --component=sensor

I have two problems with this command : 

- it seems it is not possible to exclude administratively down physical interfaces. so the sensors plugged on these shutted interface appears as error ( "admstatus" variable does not exist in mode environment)
- it seems it is not possible to specify an interface id with --mode environment

Can anybody help me with that ?
Regards

**Comment by garnier-quentin** [comment]
Yes you are right. I didn't find a way to link ifIndex and the sensor. If we find a way, we should add it in interfaces cisco mode maybe.
