### ISSUE TITLE
[apps::vmware::connector::plugin] exclude a NIC

### ISSUE THREAD

**Issue by kalau8** [centreon/centreon-plugins#2841]
Hi,

Some of my hosts have several unused NIC. They appears as CRITICAL:

CRITICAL: hyp006.siege.red Link(s) 'vmnic11' are down - hyp005.siege.red Link(s) 'vmnic11' are down
'hyp006.siege.red' Interface 'vmnic0' Traffic In : 8.19Kb/s (0.00 %), Out : 8.19Kb/s (0.00 %), Packets In Dropped : 0.00 % (0/75 packets), Packets Out Dropped : 0.00 % (0/117 packets), Interface 'vmnic1' Traffic In : 0.00b/s (0.00 %), Out : 0.00b/s (0.00 %), Packets In Dropped : 0.00 % (0/23 packets), Packets Out Dropped : 0.00 % (0/1 packets), Interface 'vmnic2' Traffic In : 0.00b/s (0.00 %), Out : 10.17Mb/s (0.97 %), Packets In Dropped : 0.00 % (0/44 packets), Packets Out Dropped : 0.00 % (0/42199 packets), Interface 'vmnic3' Traffic In : 11.80Mb/s (1.13 %), Out : 303.10Kb/s (0.03 %), Packets In Dropped : 0.00 % (0/55202 packets), Packets Out Dropped : 0.00 % (0/1490 packets), Interface 'vmnic4' Traffic In : 0.00b/s (0.00 %), Out : 0.00b/s (0.00 %), Packets In Dropped : 0.00 % (0/56 packets), Packets Out Dropped : 0.00 % (0/47 packets), Interface 'vmnic5' Traffic In : 0.00b/s (0.00 %), Out : 0.00b/s (0.00 %), Packets In Dropped : 0.00 % (0/2 packets), Packets Out Dropped : 0.00 % (0/1 packets), Interface 'vmnic6' Traffic In : 0.00b/s (0.00 %), Out : 139.26Kb/s (0.01 %), Packets In Dropped : 0.00 % (0/27 packets), Packets Out Dropped : 0.00 % (0/1375 packets), Interface 'vmnic7' Traffic In : 663.55Kb/s (0.06 %), Out : 540.67Kb/s (0.05 %), Packets In Dropped : 0.00 % (0/8081 packets), Packets Out Dropped : 0.00 % (0/2920 packets)
'hyp005.siege.red' Interface 'vmnic0' Traffic In : 0.00b/s (0.00 %), Out : 0.00b/s (0.00 %), Packets In Dropped : 0.00 % (0/87 packets), Packets Out Dropped : 0.00 % (0/49 packets), Interface 'vmnic1' Traffic In : 0.00b/s (0.00 %), Out : 0.00b/s (0.00 %), Packets In Dropped : 0.00 % (0/30 packets), Packets Out Dropped : 0.00 % (0/1 packets), Interface 'vmnic2' Traffic In : 8.19Kb/s (0.00 %), Out : 51.80Mb/s (4.94 %), Packets In Dropped : 0.00 % (0/123 packets), Packets Out Dropped : 0.00 % (0/119329 packets), Interface 'vmnic3' Traffic In : 0.00b/s (0.00 %), Out : 9.30Mb/s (0.89 %), Packets In Dropped : 0.00 % (0/69 packets), Packets Out Dropped : 0.00 % (0/6082 packets), Interface 'vmnic4' Traffic In : 0.00b/s (0.00 %), Out : 0.00b/s (0.00 %), Packets In Dropped : 0.00 % (0/46 packets), Packets Out Dropped : 0.00 % (0/16 packets), Interface 'vmnic5' Traffic In : 0.00b/s (0.00 %), Out : 0.00b/s (0.00 %), Packets In Dropped : 0.00 % (0/4 packets), Packets Out Dropped : 0.00 % (0/8 packets), Interface 'vmnic6' Traffic In : 9.27Mb/s (0.88 %), Out : 19.85Mb/s (1.89 %), Packets In Dropped : 0.00 % (0/46105 packets), Packets Out Dropped : 0.00 % (0/13850 packets), Interface 'vmnic7' Traffic In : 26.04Mb/s (2.48 %), Out : 13.63Mb/s (1.30 %), Packets In Dropped : 0.00 % (0/151836 packets), Packets Out Dropped : 0.00 % (0/18699 packets)

Is there a way to exclude the vmnic11?

I used the following option --critical-link-status='%{display} !~ /vmnic[11]/ and %{link_status} !~ /up/' but it is not working.

Could you please help me? Thank you

**Comment by garnier-quentin** [comment]
Have you tried ? 
--critical-link-status='%{display} !~ /vmnic11/ and %{link_status} !~ /up/'

**Comment by kalau8** [comment]
Great, all good. Thanks Quentin. I'm closing the issue.

**Comment by garnier-quentin** [comment]
Thanks for your feedback!
