### ISSUE TITLE
network::brocade::snmp::plugin missing argument line 168

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#2843]
hello, 

I have the following error message for the plugin network::brocade::snmp::plugin , mode hardware.

Missing argument in sprintf at network/brocade/snmp/mode/hardware.pm line 168.

Line 168:
            $self->{output}->output_add(severity => $exit,
                                        short_msg => sprintf("%s sensor '%s' status is '%s'", $result->{swSensorType}, $result->{swSensorInfo}));

I think argument 3 is not there !?

See here the output : 

# centreon_plugins.pl --plugin="network::brocade::snmp::plugin" --mode="hardware" --snmp-community="public" --filter-uom="(none)"  --hostname= xxx.xxx.xxx.xxx
Missing argument in sprintf at /dstpol/icinga2/config_plugin_external/gpi/gpi_plugin_centreon/network/brocade/snmp/mode/hardware.pm line 168.
CRITICAL: power-supply sensor 'Power Supply #2' status is '' | 'sensor_SLOT #0: TEMP #1'=24;;;; 'sensor_SLOT #0: TEMP #2'=8;;;; 'sensor_SLOT #0: TEMP #3'=15;;;; 'sensor_FAN #1'=4821;;;; 'sensor_FAN #2'=4560;;;; 'sensor_FAN #3'=4687;;;; 'count_sensor'=8;;;; 'count_switch'=1;;;;

regards,
Geert

**Comment by Sims24** [comment]
Hey @gbin2265 

Thanks for tracking this one.

Indeed, I guess that if you add `$result->{swSensorStatus}` it will output what you want right? 

```
            $self->{output}->output_add(severity => $exit,
                                        short_msg => sprintf("%s sensor '%s' status is '%s'", $result->{swSensorType}, $result->{swSensorInfo}, $result->{swSensorStatus}));
```



Simon

**Comment by gbin2265** [comment]
Simon,

thank you for the quick response and solution.

manually modified and tested and it works!

regards,
Geert

**Comment by garnier-quentin** [comment]
Fixed in last version.
