### ISSUE TITLE
[hardware::ups::hp::snmp::plugin] Cant get a single value. 

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#2846]
Hi,

I have this UPS card

Product : Single Phase 1Gb UPS Ntwrk Mgmt Mod
Name : HPE Single Phase 1Gb UPS Ntwrk Mgmt Mod
Vendor : Hewlett Packard Enterprise

And I can not check it with hp ups plugin, for environnement.

/usr/lib/centreon/plugins//centreon_ups_hp_snmp.pl --plugin=hardware::ups::hp::snmp::plugin --mode=environment --hostname='xxxxxx' --snmp-version='2c' --snmp-community='public' 
UNKNOWN: SNMP GET Request : [hpe_ups_full_snmp.txt](https://github.com/centreon/centreon-plugins/files/6589854/hpe_ups_full_snmp.txt)

[UPS-MIB.zip](https://github.com/centreon/centreon-plugins/files/6589813/UPS-MIB.zip)
[cpqpower1.80.zip](https://github.com/centreon/centreon-plugins/files/6589814/cpqpower1.80.zip)

Could you tell me what is wrong ?

Thanks !

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk of following branch ? .1.3.6.1.4.1.232

**Comment by romsworld** [comment]
Yes !

Thanks !





.1.3.6.1.4.1.232.2.2.2.1.0 = STRING: "ACC9391409"
.1.3.6.1.4.1.232.2.2.4.2.0 = STRING: "Single Phase 1Gb UPS Ntwrk Mgmt Mod"
.1.3.6.1.4.1.232.11.2.10.1.0 = Hex-STRING: 01 02 01 10 
.1.3.6.1.4.1.232.11.2.10.3.0 = STRING: "ACC9370050"
.1.3.6.1.4.1.232.165.1.1.1.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.1.1.2.0 = ""
.1.3.6.1.4.1.232.165.1.1.3.0 = STRING: "https://172.16.151.197:443"
.1.3.6.1.4.1.232.165.1.1.4.0 = STRING: "ACC9391409  Q1L90A  HPE R1500 G5 INTL UPS"
.1.3.6.1.4.1.232.165.1.1.5.0 = STRING: "Single Phase 1Gb UPS Ntwrk Mgmt Mod"
.1.3.6.1.4.1.232.165.1.2.1.0 = STRING: "Hewlett Packard Enterprise"
.1.3.6.1.4.1.232.165.1.2.2.0 = STRING: "Single Phase 1Gb UPS Ntwrk Mgmt Mod"
.1.3.6.1.4.1.232.165.1.2.3.0 = STRING: "1.7.11"
.1.3.6.1.4.1.232.165.1.2.4.0 = STRING: "0"
.1.3.6.1.4.1.232.165.1.2.5.0 = STRING: "UPS-NANTES-A"
.1.3.6.1.4.1.232.165.1.2.6.0 = STRING: "Q1C17A"
.1.3.6.1.4.1.232.165.1.2.7.0 = STRING: "ACC9370050"
.1.3.6.1.4.1.232.165.1.2.8.0 = STRING: "98:F2:B3:6C:13:C2"
.1.3.6.1.4.1.232.165.3.1.1.0 = STRING: "HPE"
.1.3.6.1.4.1.232.165.3.1.2.0 = STRING: "HPE R1500 G5 INTL UPS"
.1.3.6.1.4.1.232.165.3.1.3.0 = STRING: "01.04.0006"
.1.3.6.1.4.1.232.165.3.1.4.0 = INTEGER: 12
.1.3.6.1.4.1.232.165.3.2.1.0 = INTEGER: 5386
.1.3.6.1.4.1.232.165.3.2.2.0 = INTEGER: 39
.1.3.6.1.4.1.232.165.3.2.4.0 = INTEGER: 100
.1.3.6.1.4.1.232.165.3.2.5.0 = INTEGER: 4
.1.3.6.1.4.1.232.165.3.3.1.0 = INTEGER: 500
.1.3.6.1.4.1.232.165.3.3.2.0 = Counter32: 0
.1.3.6.1.4.1.232.165.3.3.3.0 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.3.4.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.3.4.1.2.1 = INTEGER: 232
.1.3.6.1.4.1.232.165.3.3.4.1.3.1 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.3.5.0 = INTEGER: 3
.1.3.6.1.4.1.232.165.3.4.1.0 = INTEGER: 9
.1.3.6.1.4.1.232.165.3.4.2.0 = INTEGER: 500
.1.3.6.1.4.1.232.165.3.4.3.0 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.4.4.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.4.4.1.2.1 = INTEGER: 232
.1.3.6.1.4.1.232.165.3.4.4.1.3.1 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.4.4.1.4.1 = INTEGER: 88
.1.3.6.1.4.1.232.165.3.4.5.0 = INTEGER: 3
.1.3.6.1.4.1.232.165.3.5.2.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.6.7.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.7.1.0 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.7.2.0 = INTEGER: 2
.1.3.6.1.4.1.232.165.3.7.3.0 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.8.1.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.8.2.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.8.3.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.8.4.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.8.5.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.8.6.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.9.1.0 = INTEGER: 230
.1.3.6.1.4.1.232.165.3.9.2.0 = INTEGER: 230
.1.3.6.1.4.1.232.165.3.9.3.0 = INTEGER: 1100
.1.3.6.1.4.1.232.165.3.9.4.0 = INTEGER: 500
.1.3.6.1.4.1.232.165.3.9.5.0 = STRING: "06/04/2021 07:40:45"
.1.3.6.1.4.1.232.165.3.9.6.0 = INTEGER: 160
.1.3.6.1.4.1.232.165.3.9.7.0 = INTEGER: 294
.1.3.6.1.4.1.232.165.3.10.1.0 = INTEGER: 2
.1.3.6.1.4.1.232.165.3.10.2.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.10.2.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.232.165.3.10.2.1.2.1 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.10.2.1.2.2 = INTEGER: 1
.1.3.6.1.4.1.232.165.3.10.2.1.3.1 = INTEGER: -1
.1.3.6.1.4.1.232.165.3.10.2.1.3.2 = INTEGER: -1
.1.3.6.1.4.1.232.165.3.10.2.1.4.1 = INTEGER: -1
.1.3.6.1.4.1.232.165.3.10.2.1.4.2 = INTEGER: -1
.1.3.6.1.4.1.232.165.3.10.2.1.5.1 = INTEGER: -1
.1.3.6.1.4.1.232.165.3.10.2.1.5.2 = INTEGER: -1
.1.3.6.1.4.1.232.165.3.10.2.1.6.1 = INTEGER: 3
.1.3.6.1.4.1.232.165.3.10.2.1.6.2 = INTEGER: 6
.1.3.6.1.4.1.232.165.3.11.1.0 = INTEGER: 32
.1.3.6.1.4.1.232.165.3.11.2.0 = INTEGER: 9865
.1.3.6.1.4.1.232.165.3.11.3.0 = INTEGER: 0
.1.3.6.1.4.1.232.165.3.11.4.0 = INTEGER: 2

**Comment by garnier-quentin** [comment]
It should work.

**Comment by garnier-quentin** [comment]
Ok. the mode environment is empty. But battery-status is working for example. I think it's ok.
The branch for the environment: .1.3.6.1.4.1.232.165.3.6

**Comment by romsworld** [comment]
SNMPv2-SMI::enterprises.232.165.3.6.7.0 = INTEGER: 0

Ok, so i disable environnement service.

**Comment by garnier-quentin** [comment]
Yes you can disable the service.
