### ISSUE TITLE
plugin=storage::qnap::snmp mode=volume-usage not working since last updates

### ISSUE THREAD

**Issue by Trunxsnot** [centreon/centreon-plugins#2856]
The plugins was working a lot of time but, for some reason, its not working since last updates.

[root@centreon ~]# /usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --hostname=10.20.2.11 --snmp-community=community --snmp-version=2c --mode=volume-usage --warning-usage=95 --critical-usage=98
Use of uninitialized value $options{"value"} in pattern match (m//) at /usr/lib64/nagios/plugins/storage/qnap/snmp/mode/volumeusage.pm line 186.
Use of uninitialized value $options{"value"} in concatenation (.) or string at /usr/lib64/nagios/plugins/storage/qnap/snmp/mode/volumeusage.pm line 187.

**Comment by garnier-quentin** [comment]
I have some changes. Could you try with last version ?

**Comment by Trunxsnot** [comment]
[root@centreon ~]# /usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --hostname=10.20.2.11 --snmp-community=centreon --snmp-version=2c --mode=volumes
UNKNOWN: SNMP Table Request : Timeout

**Comment by garnier-quentin** [comment]
Could you try with --snmp-autoreduce ?

**Comment by garnier-quentin** [comment]
Are you sure it's working with snmpwalk on following branch ? .1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2

**Comment by Trunxsnot** [comment]
[root@centreon02 ~]# snmpwalk 10.20.2.11 -c community -v 2c .1.3.6.1.4.1.24681.1.4.1.1.1.2.3.2
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.2.1 = INTEGER: 1
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.2.2 = INTEGER: 3
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.2.3 = INTEGER: 4
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.3.1 = Counter64: 3787164768
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.3.2 = Counter64: 3906982908
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.3.3 = Counter64: 3906975844
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.4.1 = Counter64: 728356020
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.4.2 = Counter64: 399350564
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.4.3 = Counter64: 891088964
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.5.1 = STRING: "Ready"
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.5.2 = STRING: "Ready"
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.5.3 = STRING: "Ready"
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.6.1 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.6.2 = INTEGER: -1
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.6.3 = INTEGER: -1
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.7.1 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.7.2 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.7.3 = INTEGER: 0
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.8.1 = STRING: "FILER"
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.8.2 = STRING: "Semanal02"
SNMPv2-SMI::enterprises.24681.1.4.1.1.1.2.3.2.1.8.3 = STRING: "VERSIONES2"

**Comment by garnier-quentin** [comment]
Please try with --snmp-force-getnext

**Comment by Trunxsnot** [comment]
Thanks! now its working fine!
