### ISSUE TITLE
Error with CRITICAL threshold with juniper plugins

### ISSUE THREAD

**Issue by jbeaujour** [centreon/centreon-plugins#2861]
Hello
Thank's for this great plugins

I'm trying to create an snmp service on juniper. See expanded command below:
$USER3$/centreon_plugins.pl --plugin network::juniper::ex::plugin --mode hardware --hostname x.x.x.x --snmp-version 2c --snmp-community 'community' --snmp-port 161 --snmp-timeout 10 --snmp-retries 3 --maxrepetitions 40 --subsetleef 50  --snmp-errors-exit unknown --range-perfdata 1  --verbose  --critical='fru-temperature,.*,60'  --threshold-overload='fru,OK,unknown' 

I have this message :
UNKNOWN: Wrong critical option 'fru-temperature,.*,60'.

I get centreon plugins from:
http://files.download.centreon.com/public/centreon-plugins/centreon-plugins-20210519.tar.gz

Thank's

**Comment by garnier-quentin** [comment]
There is no fru-temperature. It's an issue in help. You have following:
```operating-temperature operating-cpu operating-buffer operating-heap```

**Comment by jbeaujour** [comment]
Thank's, it work fine
