### ISSUE TITLE
[centreon::common::protocols::sql::mode::sqlstring] unknown error on an empty table (oracle)

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#2868]
## Bug/Question

Hi, with Centreon 20.10.8, Oracle database plugin (centreon-plugin-Applications-Databases-Oracle-20210519-141023.el7.centos.noarch) and '**Sql-String**' command, I have an 'UNKNOWN' result when the result is empty (  %{$self->{rows}}) <= 0 ) while with the '**Sql**' command, it returns 'OK'.
I have the same behavior with --empty-sql-string ('Sql-String' command).

`#  /usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname='xxxx' --port='1521' --sid='XE' --servicename='' --username='xxxx' --password='xxxx' --mode='sql' --sql-statement="SELECT DT_TRACE,ADRESSE_IP,MESSAGE FROM NBR_TRACE WHERE DT_TRACE>=SYSDATE-(10/1440) and OK_KO='KO' AND MESSAGE LIKE '%ORA%' ORDER BY DT_TRACE ASC" --warning='' --critical=''

OK: value : skipped (no value(s)) | 'sqlrequest.execution.time.seconds'=0.012s;;;0;`

`# /usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname='xxxx' --port='1521' --sid='XE' --servicename='' --username='xxxx' --password='xxx' --mode='sql-string' --sql-statement="SELECT DT_TRACE,ADRESSE_IP,MESSAGE FROM NBR_TRACE WHERE DT_TRACE>=SYSDATE-(10/1440) and OK_KO='KO' AND MESSAGE LIKE '%ORA%' ORDER BY DT_TRACE ASC" --value-column='MESSAGE' --warning-string='' --critical-string='%{value_field} =~ /ORA/'

UNKNOWN: No row returned or --key-column/--value-column do not correctly match selected field`

`# /usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname='xxxx' --port='1521' --sid='XE' --servicename='' --username='xxxx' --password='xxx' --mode='sql-string' --sql-statement="SELECT DT_TRACE,ADRESSE_IP,MESSAGE FROM NBR_TRACE WHERE DT_TRACE>=SYSDATE-(10/1440) and OK_KO='KO' AND MESSAGE LIKE '%ORA%' ORDER BY DT_TRACE ASC" --value-column='MESSAGE' --warning-string='' --critical-string='%{value_field} =~ /ORA/' --empty-sql-string='OK'

UNKNOWN: OK`

**Comment by garnier-quentin** [comment]
Yes. What is the issue ? It's 2 different modes. If you want ok in sql-string you can use option: ```--opt-exit=ok```

**Comment by gagzou** [comment]
Ok thanks :

# /usr/lib/centreon/plugins//centreon_oracle.pl --plugin=database::oracle::plugin --hostname='xxxx' --port='1521' --sid='XE' --servicename='' --username='xxxx' --password='xxx' --mode='sql-string' --sql-statement="SELECT DT_TRACE,ADRESSE_IP,MESSAGE FROM NBR_TRACE WHERE DT_TRACE>=SYSDATE-(10/1440) and OK_KO='KO' AND MESSAGE LIKE '%ORA%' ORDER BY DT_TRACE ASC" --value-column='MESSAGE' --warning-string='' --critical-string='%{value_field} =~ /ORA/' --opt-exit=ok --empty-sql-string='No row returned'

OK: No row returned

**Comment by gagzou** [comment]
:+1:
