### ISSUE TITLE
apps::vmware::connector::plugin - mode memory-vm

### ISSUE THREAD

**Issue by gerpion** [centreon/centreon-plugins#287]
Hello,

I've got a problem with the apps::vmware::connector::plugin plugin.

Works well when i want to get the CPU VM info :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --verbose --mode=cpu-vm --vm-hostname cbh14
OK: 'cbh14' Total Average CPU usage 8.50 %, Total Average CPU 1765.00 Mhz, CPU ready 4.03 % on last 5 min | 'cpu_total'=8.50%;;;0;100 'cpu_total_MHz'=1765.00MHz;;;0; 'cpu_ready'=4.03%;;;0; 'cpu_0_MHz'=231.00MHz;;;0; 'cpu_1_MHz'=287.00MHz;;;0; 'cpu_2_MHz'=206.00MHz;;;0; 'cpu_3_MHz'=210.00MHz;;;0; 'cpu_4_MHz'=184.00MHz;;;0; 'cpu_5_MHz'=198.00MHz;;;0; 'cpu_6_MHz'=189.00MHz;;;0; 'cpu_7_MHz'=197.00MHz;;;0;

But not with the memory info :

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --verbose --mode=memory-vm --vm-hostname cbh14 --sampling-period 300 --debug
UNKNOWN: Cannot get counter 'mem.active.average' for the sampling period '300' (counter level: 2, sampling level: 1) |

Any clue ?

Regards,

**Comment by garnier-quentin** [comment]
You need to configure the statistics configuration in your vcenter. By default it's 1 for all sampling periods.
Interesting link:
http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.vsphere.vcenterhost.doc%2FGUID-25800DE4-68E5-41CC-82D9-8811E27924BC.html

**Comment by garnier-quentin** [comment]
It's not opened in the good github. It should be done in centreon-vmware.
