### ISSUE TITLE
Create support for FortiWeb

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2874]
Could you add support for FortiWeb:

- snmpwalk attached
- MIB

As you can see the snmpwalk is very short, but it should be possible to get:
- CPU
- Proxy
- Ha mode
- Memory
- Disk

[fortiweb.snmpwalk.txt.zip](https://github.com/centreon/centreon-plugins/files/6655483/fortiweb.snmpwalk.txt.zip)
[FORTINET-WEB-MIB.zip](https://github.com/centreon/centreon-plugins/files/6655484/FORTINET-WEB-MIB.zip)

**Comment by garnier-quentin** [comment]
You can test with last version

**Comment by joschi99** [comment]
Have done some test and its working. thank you very much
