### ISSUE TITLE
apps::protocols::http::plugin --mode=json-content

### ISSUE THREAD

**Issue by jaimelabaguette** [centreon/centreon-plugins#2884]
Hello, 

I don't understand why the return of the plugin is ok when I put the arguments --critical-string='^(?!('1623798976')$)' has the same value "node value"Normally the return should be critical. 

the objective is to subtract the current time from the Timestamp value and check if it is greater than 14600

Somebody could help me
Thanks 

Here is the command 
**--plugin=apps::protocols::http::plugin --mode=json-content --hostname=IP --urlpath='URLPATH' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --proto='https' --port='443' --verbose --lookup='$[0]['backup'][1]['timestamp']['stop']' --critical-string='^(?!('1623798976')$)'**

Return that 

**OK: 1 element(s) found | 'count'=1;;;0; 'element_1'=1623798976;;;; 'time'=0.080s;;;0;
Lookup XPath $[0][backup][1][timestamp][stop]:
   Node value: 1623798976
Response time 0.080s**

**Comment by garnier-quentin** [comment]
You need to use ```--critical-numeric``` option (because your value is numeric).

**Comment by garnier-quentin** [comment]
You should use the collection mode now. It will be more flexible.
