### ISSUE TITLE
apps::protocols::nrpe::plugin no indicate certificate file

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2885]
Hello,

I am using the check_nrpe plugin with the following command which works fine.

`/usr/lib64/nagios/plugins/check_nrpe -H 192.168.0.21 -A /etc/centreon/certificat/ca/ca_cert.pem -C /etc/centreon/certificat/client_certs/client_cert.pem -K /etc/centreon/certificat/client_certs/client_cert.key -p 5666 -c alias_cpu -t 60`

On the other hand, when I use the centreon plugin, I cannot indicate my certificates in order to authenticate myself correctly.
The options are not present.

Do you have a solution ?

Thank you

**Comment by garnier-quentin** [comment]
Maybe you can try with following options:
```--ssl-opt="SSL_cert_file => '/etc/centreon/certificat/client_certs/client_cert.pem'" --ssl-opt="SSL_key_file => '/etc/centreon/certificat/client_certs/client_cert.key' "

**Comment by prohand** [comment]
Hello,

Thank you for you're response.

I have an error : 

```
bash-4.4$ /usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname 192.168.0.21 --command='alias_cpu' --ssl-opt="SSL_cert_file => '/etc/centreon/certificat/client_certs/client_cert.pem'" --ssl-opt="SSL_key_file => '/etc/centreon/certificat/client_certs/client_cert.key'"
UNKNOWN: Failed to establish SSL connection: , ssl_error=SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

But the nrpe command is OK 👍 

```
 bash-4.4$ /usr/lib64/nagios/plugins/check_nrpe -H 192.168.0.21 -A /etc/centreon/certificat/ca/ca_cert.pem -C /etc/centreon/certificat/client_certs/client_cert.pem -K /etc/centreon/certificat/client_certs/client_cert.key -p 5666 -c alias_cpu -t 60
OK: CPU load is ok.|'total 1m'=1%;90;95 'total 5m'=2%;90;95 'total 15m'=2%;90;95
```

**Comment by prohand** [comment]
I try this command and is OK : 

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname 192.168.0.21 --command='alias_cpu' --ssl-opt="SSL_ca_file => '/etc/centreon/certificat/ca/ca_cert.pem'" --ssl-opt="SSL_cert_file => '/etc/centreon/certificat/client_certs/client_cert.pem'" --ssl-opt="SSL_key_file => '/etc/centreon/certificat/client_certs/client_cert.key'"`
