### ISSUE TITLE
Problem with CheckCounter apps::protocols::nrpe::plugin

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2886]
Hello,

I have a problem with the checkcounter.

The command is OK : 
`/usr/lib64/nagios/plugins/check_nrpe -H $HOSTADDRESS$ -A $_HOSTCA-CERT$ -C $_HOSTCLIENT-CERT$ -K $_HOSTKEY-FILE$ -c CheckCounter -a "Counter:$ARG1$=\\Print Queue($ARG2$)\\Jobs" MaxWarn=5 MaxCrit=15 ShowAll -t $_HOSTNRPETIMEOUT$ -p $_HOSTNRPEPORT$`

But the command is not OK: 

`$CENTREONPLUGINS$/centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname $HOSTADDRESS$ --command='CheckCounter' --ssl-opt="SSL_ca_file => '$_HOSTCA-CERT$'" --ssl-opt="SSL_cert_file => '$_HOSTCLIENT-CERT$'" --ssl-opt="SSL_key_file => '$_HOSTKEY-FILE$'" --nrpe-timeout $_HOSTNRPETIMEOUT$ --nrpe-port $_HOSTNRPEPORT$ --arg="'Counter:$ARG1$=\\Print Queue($ARG2$)\\Jobs' 'MaxWarn=5 MaxCrit=15 ShowAll'"`

The error : No counters specified: add counter=<name of counter>

Do you have a solution ?

Thank you

**Comment by garnier-quentin** [comment]
Have you tried ?
```
$CENTREONPLUGINS$/centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname $HOSTADDRESS$ --command='CheckCounter' --ssl-opt="SSL_ca_file => '$_HOSTCA-CERT$'" --ssl-opt="SSL_cert_file => '$_HOSTCLIENT-CERT$'" --ssl-opt="SSL_key_file => '$_HOSTKEY-FILE$'" --nrpe-timeout $_HOSTNRPETIMEOUT$ --nrpe-port $_HOSTNRPEPORT$ --arg="Counter:$ARG1$=\\Print Queue($ARG2$)\\Jobs" --arg="MaxWarn=5" --arg="MaxCrit=15" --arg="ShowAll"
```

**Comment by prohand** [comment]
It's OK.

Thank you ;)
