### ISSUE TITLE
[hardware::ups::powerware::snmp::plugin] environment and input-lines mode new OIDs

### ISSUE THREAD

**Issue by dantes549** [centreon/centreon-plugins#2888]
Hello,

I think the environment plugins needs an update.

Since 2.0.* firmware version on Eaton Network-M2 cards, the environment and Input-Lines plugins return "not a single value".
Eaton support confirmed that the OIDs for the servicehave changed, and Centreon Support told me the only way to fix that is requesting update on GitHub.

Thanks a lot for your help !!

**Comment by Sims24** [comment]
Hello @dantes549 

Thanks. Could you obtain the new mibs from the Eaton support and share it with us. Also, a snmpwalk from your device could help. Feel free to send it to qgarnier@centreon.com and/or sbomm@centreon.com. 

Thanks

**Comment by dantes549** [comment]
Hello, 

Do you have any news ?

Thanks,

Regards

**Comment by garnier-quentin** [comment]
The part xupsEnvironment is not populated anymore. It could be in .1.3.6.1.4.1.534.6.8.1 (eatonSensor).
But the branch is empty: .1.3.6.1.4.1.534.6.8.1.1.1.0 (sensorCount) = INTEGER: 0

Need to ask of equipment support.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @dantes549 if you still need a response / solution to this issue, can you provide us the new OIDs or better the new mibs from the Eaton to help us to fix it ?
Otherwise we will be forced to close this issue.

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time. Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the sissue.
