### ISSUE TITLE
[plugin] Dell Force10 switches

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#289]
It would be nice to have a plugin to check Dell Force10 switches
* cpu
* hardware
* environment
* interfaces
* list-interfaces
* memory
* spanning-tree
* stack
* vlt

**Comment by Sims24** [comment]
Hi, 

Could you provide us mibs and a snmpwalk on the equipment ? It would be a great help ! If so, send an email to @garnier-quentin or me please.

Thanks

**Comment by Sims24** [comment]
Hi, 

Did you try with this one : 

centreon-plugins/network/dell/sseries/snmp/plugin.pm

Should work I think,

**Comment by garnier-quentin** [comment]
Yes. Dell has acquired force10. So it should work with the dell sseries plugin.

**Comment by garnier-quentin** [comment]
You can continue in the thread if you have a problem with the plugin sseries. Thanks
