### ISSUE TITLE
Minor Bug in network/netgear/mseries/snmp/mode/components/temperature.pm: unit is show as rpm but should be C

### ISSUE THREAD

**Issue by Ysincit** [centreon/centreon-plugins#2896]
line 76 of network/netgear/mseries/snmp/mode/components/temperature.pm should be changed from
short_msg => sprintf("Temperature '%s' is '%s' rpm", $instance, $result->{boxServicesTempSensorTemperature}));
to
short_msg => sprintf("Temperature '%s' is '%s' C", $instance, $result->{boxServicesTempSensorTemperature}));

**Comment by itoussies** [comment]
Thanks for the feedback !
