### ISSUE TITLE
storage::dell::equallogic::snmp::plugin Response message would have been too large

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2897]
Hello,

Randomly I encounter the following error message : 

NKNOWN: SNMP GET Request : (tooBig) Response message would have been too large

The command :  

/usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin storage::dell::equallogic::snmp::plugin --mode disk-usage --hostname xx.xx.xx.xx --snmp-community snmp --snmp-version v2c --debug --verbose

Thank you

**Comment by Sims24** [comment]
Hey @prohand 

Did you give a try to https://github.com/centreon/centreon-plugins/blob/2fd7bbb451f3dbf44b193d3566649bd0c2ed8c3e/doc/en/user/guide.rst#i-get-the-snmp-error-unknown-toobig ? 

Thanks

**Comment by prohand** [comment]
Hey @Sims24,

Thank you, sorry i can't read this doc :(

Its OK 

Thank you
