### ISSUE TITLE
[Failover] - Check if the resource is "unmigrate"

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#29]
Hi,

Would it be possible to provide a check to verify if the resources of failover (ms_MySQL and centreon) are in status "unmigrate") every x minutes ?

Regards

**Comment by garnier-quentin** [comment]
We can do it with the following command. And we look for 'score=-INFINITY' and 'id=cli-ban-*'

crm_resource --constraints -r centreon
* centreon
  : Node centreon-central-master                                                 (score=-INFINITY, id=cli-ban-centreon-on-centreon-central-master)
  : Node centreon-central-master                                                 (score=100, id=centreon-master-rule)
  : Node centreon-quorom                                                         (score=-INFINITY, id=centreon-placement-rule)
  : Node centreon-db-slave                                                       (score=-INFINITY, id=centreon-placement-rule)
  : Node centreon-db-master                                                      (score=-INFINITY, id=centreon-placement-rule)

**Comment by Sims24** [comment]
Hi, I'm on it, will probably send you a pull request by the end of the week ;)

"Regards"
