### ISSUE TITLE
"Unsafe code evaluation" on simple things

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2902]
Hi,

The secure feature introduced by @garnier-quentin in #2691 prevents simple things like this :

```
$ centreon_influxdb.pl --mode=query ... --instance=c --critical-status='%{c} < time-180' --verbose
(...)
filter status issue: Unsafe code evaluation: 'time' trapped by operation mask at (eval 56) line 1.
```

Any workaround ?

Thx 👍

**Comment by garnier-quentin** [comment]
If you need the current time we can add it as a variable

**Comment by UrBnW** [comment]
Would be nice to have current time yes.
However, depending on how it's done, I see some drawbacks to have it in a variable, below is why.
In my example above, `time` is evaluated and compared to the "remote" value, right after it has been retrieved by the plugin, with "no" delay.
If we store `time` in a variable for example at the very first start of the plugins' tree once for all, depending on how long it takes to retrieve the "remote" value, comparison could suffer from a delay of several tens of seconds...
Note that Perl already has `$^T` which does this, but then it's not compatible with Perl Connector, as `$^T` is given a value once for all when connector starts.

Second point, I also use Perl code like in example below, which currently still works.
I'm scared you would deploy `Safe` everywhere in the other options, breaking these specific things.
```
--plugin=apps::protocols::snmp::plugin
--use-perl-mod='Date::Parse'
--convert-custom-values='time-(Date::Parse::str2time($value))'
--change-short-output='^([A-Z]+: )([0-9]+) $~sprintf "%sLast time: %dd %02dh %02dm %02ds ago [%s] ", $1, (gmtime($2))[7,2,1,0], scalar localtime time-$2~e'
```

And third point, perhaps the most important.
In my very first example above, the rejected `--critical-status` option (because of `time`) does not prevent the plugin to work, and as a result to always return `OK`.
Which is dangerous, upgrading plugins to the `Safe` enabled version, as it will silently break the thresholds...
Worst, the error message from `Safe` is printed only with `--verbose`.
IMO, `Safe` should make the plugin to exit with an error, rather than to silently discard the wrong piece of code.

Many thanks 👍

**Comment by garnier-quentin** [comment]
We add time option after requests. So it should be ok.
