### ISSUE TITLE
Support for in-house plugin pack RPMs (JSONs) using plugin pack manager

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-plugins#2903]
Is creating own Plugin Pack RPMs (like for example the pluginpack_operatingsystems-linux-snmp-3.2.7.json file from centreon-pack-operatingsystems-linux-snmp-3.2.7-1.el7.centos.noarch.rpm) supported by centreon webs Plugin Packs Manager?
Is there a supported way (documented) to load own json files using this interface? Im seeing Base Pack plugin pack that does not require a license to update so I believe I could probably create own RPM with json definitions to load own json plugin pack?!

Thanks,
Marcel

**Comment by Sims24** [comment]
Hi @hecko,

On paper, it will work to build your own json file. 

We do not document it at the moment and I'm pretty sure that it will be the case in the near future. 

Maybe if you could tell us a little bit more about your use case we can think about it. What's the purpose of writing your own JSON file (house-made application, template customization, other?). 

It could be great to have some kind of community-powered Pack repository so everybody can share back its custom definitions. But that's another story. 

Simon

**Comment by hecko** [comment]
@Sims24 I really like your idea of community powered plugin packs repository. I even love the idea of having the plugin packs format being the primary interface to install custom plugins and templates. I believe this would potentially create a great traction in adding more plugins into the open source centreon ecosystem.

The nagios exchange site is still extremely popular amongs the centreon users and I strongly believe a simpe RPM repo with a quick how-to on how to submit new plugins and plugin packs (templates) for centreon would be a great addition to nagios exchange specifically aimed for centreon users.

Im happy to donate my time to go through the process of creating a template for a plugin pack, however I would really appreciate some input on the json file definition from centreon (company) directly.

**Comment by Sims24** [comment]
Hi @hecko 

Sorry for the late answer and thanks for your feedback. I'll send you an email to find a slot to discuss this further and share with you some inputs about the JSON format.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old and had been concluded separately, so let me close it.
