### ISSUE TITLE
Bad result for Synology component Disk

### ISSUE THREAD

**Issue by Vidark-Wyrd** [centreon/centreon-plugins#2904]
## Bug/Question

Hi,

Today, I experience a probleme with 2 NAS Synology who lost a disk.

But Centreon tell me "OK: All 3 components are ok [3/3 disk].". The correct result should be "CRITICAL: 1 disk is missing [3/4 disk].."

Probaby, I missed something in my command :

$CENTREONPLUGINS$/centreon-plugins/centreon_plugins.pl --plugin=storage::synology::snmp::plugin --mode=components --component=disk --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$

Thank you very much. Have a nice day

David.

**Comment by UrBnW** [comment]
The failed disks must have gone from the SNMP tree...
I think that the `raid` component should alert you in this situation.

**Comment by Vidark-Wyrd** [comment]
> The failed disks must have gone from the SNMP tree...
> I think that the `raid` component should alert you in this situation.

Hi,

THank you for your answer. 

My raid components are well in Warning but I thougt the OK for dsiks status was strange in this case.

**Comment by UrBnW** [comment]
`--critical-count-disk=4:4` should do the trick 👍

**Comment by Vidark-Wyrd** [comment]
Yes ! 
Thank you very much. I'll Change my command to get this with macro for all kind of NAS.

I close 

Have a nice day
