### ISSUE TITLE
nrpe apps::sccm::local::plugin cannot load module

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2906]
Hello,

I have install centreon_nsclient with this link : https://docs.centreon.com/docs/centreon-nsclient/fr/latest/windows_agent.html
The check for CPU is OK.

But the check for SCCM failed.

The command : 

` /usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname xx.xx.xx.xx --command='check_centreon_plugins' --ssl-opt="SSL_ca_file => '/etc/centreon/certificat/ca/ca_cert.pem'" --ssl-opt="SSL_cert_file => '/etc/centreon/certificat/client_certs/client_cert.pem'" --ssl-opt="SSL_key_file => '/etc/centreon/certificat/client_certs/client_cert.key'" --nrpe-timeout 60 --nrpe-port 5666 --arg='apps::sccm::local::plugin' --arg='apps::sccm::local::plugin' --arg='site-status'`

Return the error code : 

```
UNKNOWN: Cannot load module --plugin.
Can't locate apps/sccm/local/plugin.pm in @INC (you may need to install the apps::sccm::local::plugin module) (@INC contains: C:/Program Files/centreon-nsclient/NSClient++/scripts/centreon C:\Windows\TEMP\par-532d5343434d2d50524924\cache-f55e56d520432b5534dd558116fb4d09e12bb9c2\inc\lib C:\Windows\TEMP\par-532d5343434d2d50524924\cache-f55e56d520432b5534dd558116fb4d09e12bb9c2\inc CODE(0x260bbe8) CODE(0x260bde0)) at C:\Windows\TEMP\par-532d5343434d2d50524924\cache-f55e56d520432b5534dd558116fb4d09e12bb9c2\inc\lib/centreon/plugins/misc.pm line 221.

```

Effectively the folder "C:/Program Files/centreon-nsclient/NSClient++/scripts/centreon" contain : 

![image](https://user-images.githubusercontent.com/20227162/123388076-b4343e00-d598-11eb-86ff-59cfd813b61d.png)

How can I solve the problem?

Thank you

**Comment by Sims24** [comment]
Hi @prohand 

This documentation is outdated. We have to rework it in the new layout. 

For the moment, please always get the latest Plugins and Agent build from the dedicated github: https://github.com/centreon/centreon-nsclient-build/releases/tag/20210525125834

**Comment by prohand** [comment]
Thank you.

But same error after uninstall the version of documentation outdated and install the latest plugins and agent build from github.

**Comment by UrBnW** [comment]
Plugin is `apps::microsoft::sccm::local::plugin`.
You missed the `microsoft` path.

**Comment by UrBnW** [comment]
In your command, use `--arg='apps::microsoft::sccm::local::plugin'` instead of `--arg='apps::sccm::local::plugin'`.

**Comment by prohand** [comment]
Hello,

Same problem.
The command : 

` /usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname 192.168.0.91 --command='check_centreon_plugins' --ssl-opt="SSL_ca_file => '/etc/centreon/certificat/ca/ca_cert.pem'" --ssl-opt="SSL_cert_file => '/etc/centreon/certificat/client_certs/client_cert.pem'" --ssl-opt="SSL_key_file => '/etc/centreon/certificat/client_certs/client_cert.key'" --nrpe-timeout 60 --nrpe-port 5666 --arg='apps::sccm::local::plugin' --arg='apps::microsoft::sccm::local::plugin' --arg='site-status'`

Show this error : 

```
UNKNOWN: Cannot load module --plugin.
Can't locate apps/sccm/local/plugin.pm in @INC (you may need to install the apps::sccm::local::plugin module) (@INC contains: C:/Program Files/Centreon NSClient++/scripts/centreon C:\Windows\TEMP\par-532d5343434d2d50524924\cache-e9da932be960cda0212fc882d0aa7f8e62a4753a\inc\lib C:\Windows\TEMP\par-532d5343434d2d50524924\cache-e9da932be960cda0212fc882d0aa7f8e62a4753a\inc CODE(0x2678de0) CODE(0x2678fd8)) at C:\Windows\TEMP\par-532d5343434d2d50524924\cache-e9da932be960cda0212fc882d0aa7f8e62a4753a\inc\lib/centreon/plugins/misc.pm line 222.
```

Thank you

**Comment by UrBnW** [comment]
You have 2 occurrences of the plugin path in your command.

**Comment by garnier-quentin** [comment]
You need to update the plugin:
```-PSProvider AdminUI.PS.Provider\CMSite``` by ```-PSProvider CMSite```

**Comment by prohand** [comment]
Hello,

Thank you for the feedback.
How do I update?

Thank you

**Comment by garnier-quentin** [comment]
you need to find the file: ```centreon/common/powershell/sccm/sitestatus.pm```

**Comment by prohand** [comment]
I use NSclient by centreon but the file is not found in program files.
Find the file in the temp folder : 
![image](https://user-images.githubusercontent.com/20227162/126800414-79b70a75-ae7b-4c33-be99-9e189fc1197e.png)
 Is normal ?

**Comment by garnier-quentin** [comment]
Yes it is normal.

**Comment by prohand** [comment]
Same problem after modify the file and restart nsclient
The value is reset.

But not restart nsclient i have this error : 

`UNKNOWN: Cannot decode json response: malformed UTF-8 character in JSON string, at character offset 79 (before "\x{fffd}ge de Brigna...") at C:\Windows\TEMP\par-532d5343434d2d50524924\cache-e9da932be960cda0212fc882d0aa7f8e62a4753a\inc\lib/apps/microsoft/sccm/local/mode/sitestatus.pm line 173.`

**Comment by garnier-quentin** [comment]
Coul you provide the --ps-exec-only result ?

**Comment by prohand** [comment]
Or should I add this?

**Comment by garnier-quentin** [comment]
In the command line

**Comment by prohand** [comment]
Here ? : 
![image](https://user-images.githubusercontent.com/20227162/126804374-4d5d8147-d70a-4e7a-9004-d7b0f3d515f3.png)

**Comment by UrBnW** [comment]
No, in your whole `centreon_plugins.pl` command, add `--arg='ps-exec-only'`

**Comment by prohand** [comment]
Hello,

With the --ps-exec-only 

I Have this result : 

`UNKNOWN: Command error: System.Management.Automation.ProviderNotFoundException: Cannot find a provider with the name 'AdminUI.PS.Provider\CMSite'. -    at System.Management.Automation.SessionStateInternal.GetSingleProvider(String name) -    at Microsoft.PowerShell.Commands.NewPSDriveCommand.ProcessRecord()
`

Thank you

**Comment by prohand** [comment]
With `--arg='ps-exec-only'` 
I have this message : 

`UNKNOWN: Cannot decode json response: malformed UTF-8 character in JSON string, at character offset 79 (before "\x{fffd}ge de Brigna...") at C:\Windows\TEMP\par-532d5343434d2d50524924\cache-e9da932be960cda0212fc882d0aa7f8e62a4753a\inc\lib/apps/microsoft/sccm/local/mode/sitestatus.pm line 173.`

Thank you

**Comment by garnier-quentin** [comment]
I have done a patch. Please download and test with centreon_plugins.exe from that page:

If you have still the encoding issue, try the option (not sure of the source encoding): ```--source-encoding='UTF-16'```

**Comment by prohand** [comment]
Hello,

Same problem with and without `--source-encoding='UTF-16'`

Thank you

**Comment by garnier-quentin** [comment]
You need to set the right encoding.

**Comment by prohand** [comment]
How can I know the correct encoding?

**Comment by garnier-quentin** [comment]
Maybe cp1252 or iso-8859-1

**Comment by prohand** [comment]
Same problem with encoding

**Comment by garnier-quentin** [comment]
I will neeed to do a session

**Comment by garnier-quentin** [comment]
We have tested and it's working with option: ```--source-encoding=iso-8859-1``` (centreon_plugins.exe side)
