### ISSUE TITLE
network::fortinet::fortigate::snmp::plugin show port1x instead port1

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2907]
Hello,

I have this command : 

`usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin network::fortinet::fortigate::snmp::plugin --mode interfaces --hostname xx.xx.xx.xx --snmp-community isiasnmp --name --interface port1 --nagvis-perfdata`

Who is supposed to return me only port1

But add debug option return all port1x : 

![image](https://user-images.githubusercontent.com/20227162/123411971-59f3a700-d5b1-11eb-9b65-060e7276199e.png)

Can you solved the problem ?

Thank you

**Comment by UrBnW** [comment]
Hello,
Use the following :
`--interface='^port1$'`

**Comment by prohand** [comment]
It's OK.
Thank you

**Comment by prohand** [comment]
Hello, in the command line is OK.
But i can't esapce $ caracter in the web interface argument

**Comment by garnier-quentin** [comment]
You need to add an extra $ character: ```$$```

**Comment by prohand** [comment]
Hello,

Perfect thank you.

I had tested a whole bunch of combination that doesn't work :(
