### ISSUE TITLE
[network::aruba::aoscx::snmp] Can't get single value for VSF members status

### ISSUE THREAD

**Issue by anthonyBertrant** [centreon/centreon-plugins#2909]
Hello Teams,

I'm currently developing a VSF plugin for my Aruba CX, but I got an error message (can't get single value) and I don't know what I did wrong. The vsf.txt is what i wrote to get what I need (it's still in developement and some things are not "ready").

Here, are the two snmpwalk result from the MIB I use:
```
snmpwalk -v3 -u xxx -l AuthNoPriv -a SHA -A xxx xx.xx.xx.xx 1.3.6.1.4.1.47196.4.1.1.3.15.1.4.1.3
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.49 = STRING: "Successfully connected to 2/1/49"
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.50 = STRING: "Successfully connected to 4/1/50"
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.113 = STRING: "Successfully connected to 1/1/49"
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.114 = STRING: "Successfully connected to 3/1/50"
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.177 = STRING: "Successfully connected to 4/1/49"
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.178 = STRING: "Successfully connected to 2/1/50"
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.241 = STRING: "Successfully connected to 3/1/49"
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.3.242 = STRING: "Successfully connected to 1/1/50"
```

```
snmpwalk -v3 -u xxx -l AuthNoPriv -a SHA -A xxx xx.xx.xx.xx 1.3.6.1.4.1.47196.4.1.1.3.15.1.4.1.1
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.49 = INTEGER: 49
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.50 = INTEGER: 50
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.113 = INTEGER: 113
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.114 = INTEGER: 114
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.177 = INTEGER: 177
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.178 = INTEGER: 178
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.241 = INTEGER: 241
SNMPv2-SMI::enterprises.47196.4.1.1.3.15.1.4.1.1.242 = INTEGER: 242
```

I tried to use the 4.1.1 as Index Key to link with 4.1.3 but without success(but maybe it's not the right way).

In the end, I think the plugin can just do like this:
- If all value returned by 4.1.3 are successfully, the plugin can display OK
- If a certain threshold of 4.1.3 result are not successfully, display Warning
- If another threshold of 4.1.3 results are not successfully, display Critical

In the end, for me, I don't know what I did wrong. So, you are my only hope ^^.

Regards,

[vsf.txt](https://github.com/centreon/centreon-plugins/files/6727987/vsf.txt)
[ARUBAWIRED-VSF-MIB.txt](https://github.com/centreon/centreon-plugins/files/6728065/ARUBAWIRED-VSF-MIB.txt)

**Comment by garnier-quentin** [comment]
If you don't show me your own code, i cant tell

**Comment by anthonyBertrant** [comment]
Hello @garnier-quentin, vsf.txt is the code for the plug-in I created.

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk also ? You can sent it to my email

**Comment by anthonyBertrant** [comment]
I just fired the mail.
Again, thanks for your help

**Comment by garnier-quentin** [comment]
You can test it with last git version
