### ISSUE TITLE
[apps::exchange::2010::local] Queues mode generates multiples metrics

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon-plugins#291]
Hello,

The queues mode generate multiple metrics for same queues.
With Exchange 2010, the ID in metric name is incremented when a queue is empty.
Now, we have a lot of metrics on RRD graph.
For example, the queue ServerName/5645 empties, when we re-check this queue the name will be ServerName/5646.

regards

**Comment by garnier-quentin** [comment]
Fix 077307de9c0617daa164d8035289e2d304676aea
