### ISSUE TITLE
Plugin apps::vmware::connector::plugin - loosing graph scale unit with perfdata aggregation

### ISSUE THREAD

**Issue by BertrandJO** [centreon/centreon-plugins#2918]
Hi,

Trying to graph datastore usage per name/storage array (perfdata sum function) with apps::vmware::connector::plugin, I do not get the good result  :

/var/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=datastore-usage --connector-hostname='X.X.X.X' --connector-port='5700' --container='vcenterXX' --change-perfdata='used_XXXXXXX',target_in,, --extend-perfdata-group=',used_total,**sum**(target_(in))' --change-perfdata='free_XXXXXXX',target_two,,   --filter-perfdata='_total$'  --extend-perfdata-group=',free_total,**sum**(target_(two))'

-> OK: All datastores are ok | 'used_total'=32074849320960;;;; 'free_total'=22899389890560;;;;
(values are the good one, checked manually with datastore addition and vmware comparison)

In the graph, each value are shown as used_total 31.958T and free_total 23.016T (see screenshot) but it should be used_total 29.17TB and free_total 20.82TB.

![2021-07-01_10-45-10](https://user-images.githubusercontent.com/30906443/124094914-80a25980-da59-11eb-99e3-c5eadf736b1a.png)

Each used/free datastore value returned by the script is in bytes (each value is returned like 3697129626278**B**).

This information seems to be lost using the perfdata sum function, adding bytes returns a total value considered as bits.

Hope my description is clear.

Regards,

BJO

**Comment by garnier-quentin** [comment]
You can add the unit (but i dont think it will solve your issue):
```
--extend-perfdata-group=',used_total,sum(target_(in)),B'
```

**Comment by BertrandJO** [comment]
Hi Quentin,

Thanks for your reply, I've tried your trick, I now have the unit inside the output but it has no effect on the graph part.

**Comment by garnier-quentin** [comment]
Check the scaling option in graph template configuration for your service (maybe the default graph template).

**Comment by BertrandJO** [comment]
Changing the graph template (default) to storage works fine ! Thanks

**Comment by garnier-quentin** [comment]
thanks for the feedback!
