### ISSUE TITLE
[apps::vmware::connector::plugin] --filter help

### ISSUE THREAD

**Issue by Furiouss38** [centreon/centreon-plugins#292]
Hi,

I'm looking for help to use the filter with the vmware connector plugin.
I want to be able to check tools status on all my vms that are monitored by my Centreon, but the thing is sometimes centreon hostname for a vm is not exactly the same it is on Vmware (Upper/lower case is the most common issue)

So i was looking to make the check not case dependent.

I'll use '$hostname$'  variable from centreon, but if my vm is, for exemple Cyan1 in vmware and cyan1 in centreon, it won't work : 

/centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=tools-vm ---filter --vm-hostname='Cyan1'
WARNING: 1 VM with VMTools not up-to-date |
vmtools not up-to-date:
    Cyan1

./centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=tools-vm ---filter --vm-hostname='cyan1'
UNKNOWN: Cannot find 'VirtualMachine' object |

what should I put in addition to $hostname$ in the vm-hostname regex to be able to check that ?

I tried --vm-hostname='/$hostname$/i' but it didn't work and my regex knowledge stop there :(

**Comment by garnier-quentin** [comment]
I don't use case insensitive check in centreon-vmware. I could add a global option in the connector for that. Please open it in centreon-vmware github.
