### ISSUE TITLE
[cloud::vmware::velocloud::restapi::plugin] mode=list-edges: Use of uninitialized value

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2921]
./centreon_plugins.pl --hostname=xxx --username=user --password='password'   --plugin=cloud::vmware::velocloud::restapi::plugin --mode=list-edges
Use of uninitialized value in sprintf at /tmp/joschi/centreon-plugins-master/cloud/vmware/velocloud/restapi/mode/listedges.pm line 54.
List edges:
[id = 25125][name = XXXX][description = XXXX][edge_state = CONNECTED][service_state = IN_SERVICE][ha_state = UNCONFIGURED][activation_state = ACTIVATED]
[id = 27145][name = XXXX][description = XXXX][edge_state = OFFLINE][service_state = IN_SERVICE][ha_state = UNCONFIGURED][activation_state = ACTIVATED]
[id = 25069][name = XXXX][description = ][edge_state = DEGRADED][service_state = IN_SERVICE][ha_state = UNCONFIGURED][activation_state = ACTIVATED]
[id = 25185][name = XXXX][description = XXXX][edge_state = OFFLINE][service_state = IN_SERVICE][ha_state = UNCONFIGURED][activation_state = ACTIVATED]

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by joschi99** [comment]
Know it's working, thanks
