### ISSUE TITLE
database::oracle::mode:: deadlock monitoring

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#2936]
Hi,
Is it possible to report deadlock errors in the Oracle Database pack ?
I think the detection of an ORA-00060 error should be sufficient ?

Best Regards,
Greg

**Comment by garnier-quentin** [comment]
You should use check_logfiles plugin to check oracle log files. If you have a request to get number of deadlock, we could add it.

**Comment by garnier-quentin** [comment]
Please comment it and re-open it if you have a request
