### ISSUE TITLE
[UPS-APC]  Problem with remaining time (OID misinterpretation) 

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#294]
Hi, 

We need to fix an issue about ups/apc monitoring. Here is some details on the same equipment : 

[root@PRI0001IN709 centreon-plugins]# /tmp/centreon-plugins/centreon_plugins.pl --plugin hardware::ups::standard::rfc1628::snmp::plugin --mode battery-status --hostname X.X.X.X 

OK: Battery status is normal - Charge remaining: 100% (90 minutes remaining) | 'load'=100%;;;0;100 'voltage'=136.5V;;;; 'temp'=24C;;;;

/tmp/centreon-plugins/centreon_plugins.pl --plugin hardware::ups::apc::snmp::plugin --mode battery-status --hostname X.X.X.X --snmp-version 2c --snmp-community public

OK: Battery status is 'batteryNormal' [battery needs replace: no], Remaining capacity : 100 %, Remaining time : 540600 minutes, current : skipped (no value(s)), Voltage : 136 V, Temperature : 24 C | 'load'=100%;;;0;100 'load_time'=540600m;;;0; 'voltage'=136V;;;; 'temperature'=24C;;;;

As you can see on the second we have a load_time a little bit annoying, that's because it's the OID : 

upsAdvBatteryRunTimeRemaining probably means minutes before battery could be in "replace needed" state and not the time of power failure that could be handle by the battery :) 

So instead we can probably use the standard OID upsAdvBatteryRunTimeRemaining from the standard and returning 90 which is I think the right value. 

If upsBasicBatteryTimeOnBattery is greater or equal than upsBasicBatteryTimeOnBattery, then half battery life is consumed.

Thanks,

**Comment by maksimatveev** [comment]
I would recommend even rename load on capacity as the name of the duplicated in outputlines.pm. there it is the value of the load on the UPS equipment.
