### ISSUE TITLE
[network::hirschmann::standard::snmp::plugin] Return the status of autoconfiguration adapter (ACA)

### ISSUE THREAD

**Issue by Infopromt** [centreon/centreon-plugins#2940]
You return the status of the configuration ok or insync. May be it's also possible to recover the status of the ACA (AutoConfiguration Adapter) USB Key via the OID 1.3.6.1.4.1.248.14.2.4.200.1 (hmAutoconfigAdapterStatus)

> Status of the AutoConfiguration Adapter. notPresent(1): AutoConfiguration Adapter has not been detected. removed(2): Configuration was loaded from adapter, but adapter was removed in running mode of the agent. ok(3): Configuration of adapter and switch match. notInSync(4): Configuration of adapter and switch don't match, e.g. configuration has not yet been written into the adapter. outOfMemory(5): Configuration is too large for the adapter. wrongMachine(6): Adapter contains configuration which cannot be loaded into this machine because it was created by a different type of switch. checksumErr(7): Data in adapter fails consistency check. genericErr(8): Any other failure, e.g. hardware malfunction. autodisabled(9): USB port has been disabled for safety reasons.
 notPresent(1), removed(2), ok(3), notInSync(4), outOfMemory(5), wrongMachine(6), checksumErr(7), genericErr(8), autodisabled(9)

Thank you

**Comment by garnier-quentin** [comment]
I don't think i will develop a specific mode (it's not present in new hirschman mib files). But i have a solution. You can use following command:
```
perl centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=collection --hostname=10.30.2.1 --snmp-community=public --snmp-port=1611 --verbose --config='
{
    "mapping": {
        "adapterStatus": {
            "1": "notPresent",
            "2": "removed",
            "3": "ok",
            "4": "notInSync",
            "5": "outOfMemory",
            "6": "wrongMachine",
            "7": "checksumErr",
            "8": "genericErr",
            "9": "autodisabled"
        }
    },
    "snmp": {
        "leefs": [
            { "name": "autoconfigAdapterStatus", "oid": ".1.3.6.1.4.1.248.14.2.4.200.1.0" }
        ]
    },
    "selection": [
        {
            "name": "autoconfigAdapter",
            "expand": {
                "status": "%(snmp.leefs.autoconfigAdapterStatus)"
            },
            "functions": [
                { "type": "map", "map_name": "adapterStatus", "src": "%(status)", "dst": "%(statusStr)" }
            ],
            "critical": "%(statusStr) !~ /ok|notPresent/i",
            "perfdatas": [
                { "nlabel": "agent.autoconfig.adapter.status.count", "value": "%(status)" }
            ],
            "formatting": {
                "printf_msg":"Autoconfiguration adapter status is %s",
                "printf_var":[
                    "%(statusStr)"
                ]
            }
        }
    ]
}
'
```

If you prefer, you can also put it in config file.
