### ISSUE TITLE
support for Seagate NAS

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2942]
It should be nice to have support for Seagate NAS. You can find a snmp walk and MIB file.

[MIB.zip](https://github.com/centreon/centreon-plugins/files/6768054/MIB.zip)
[seagate-nas.snmpwalk.txt.zip](https://github.com/centreon/centreon-plugins/files/6768060/seagate-nas.snmpwalk.txt.zip)

Thanks

**Comment by garnier-quentin** [comment]
I need the seagate mib files (not in your zip file). The branch is: .1.3.6.1.4.1.3581.123

**Comment by garnier-quentin** [comment]
Do you have some news ?

**Comment by joschi99** [comment]
unfortunately no news, seems difficult to get the MIBs

**Comment by joschi99** [comment]
No news, I will close the case
