### ISSUE TITLE
apps::protocols::x509::plugin KO with expiration check with mode https

### ISSUE THREAD

**Issue by kikijolicoeur** [centreon/centreon-plugins#2943]
Hello.
I would check the expiration of a web self signed certificate. for my test , I have a certificate that expires in 361 days.
so I use : 
/usr/lib/centreon/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::x509::plugin --mode certificate --custommode=https --port 8008 --warning-status '%{expiration} < 360' --critical-status '%{expiration} < 400'  --hostname X.Y.T.5T --insecure
I expected a CRITICAL but I obtain : 
UNKNOWN: OK

And with the same certificate but with custommode=file , it is ok (I'm getting the expected CRITICAL)

/usr/lib/centreon/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::x509::plugin --mode certificate --custommode=file  --certificate /tmp/mycert.cert  --warning-status '%{expiration} < 360' --critical-status '%{expiration} < 400'

CRITICAL: Certificate for 'tralala' expires in '361'

With openssl : 
echo | openssl s_client -connect X.Y.Z.T:8008 2>&1| sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'|openssl x509 -noout  -dates

notBefore=Jul  2 19:02:47 2021 GMT
notAfter=Jul  2 19:02:47 2022 GMT

Did I made a mistake with https custommode ?

Best regards

**Comment by garnier-quentin** [comment]
Could you execute with --debug ?

**Comment by garnier-quentin** [comment]
Maybe you are in the same case:
https://github.com/centreon/centreon-plugins/issues/2621

**Comment by kikijolicoeur** [comment]
with --debug:

UNKNOWN: OK 
======> request send
GET https://10.25.52.54:8008/
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.0 200 OK
Date: Tue, 06 Jul 2021 12:05:46 GMT
Server: BaseHTTP/0.6 Python/3.7.3
Content-Type: application/json
Client-Date: Tue, 06 Jul 2021 12:05:46 GMT
Client-Peer: 10.25.52.54:8008
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=FR/ST=HAUTS-DE-SEINE/L=BOULOGNE-BILLANCOURT/O=Cegedim.Cloud/OU=Admins/CN=Admin-PGHA/emailAddress=it.cloudplatforms.boulogne@cegedim.com
Client-SSL-Cert-Subject: /C=FR/ST=HAUTS-DE-SEINE/L=BOULOGNE-BILLANCOURT/O=Cegedim.Cloud/OU=Admins/CN=dcropgha001.hosting.cegedim.cloud/emailAddress=it.cloudplatforms.boulogne@cegedim.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL

{"state": "running", "postmaster_start_time": "2021-07-02 20:59:41.269 CEST", "role": "master", "server_version": 120007, "cluster_unlocked": false, "xlog": {"location": 3388997728}, "timeline": 44, "replication": [{"usename": "XXXXX", "application_name": "pouet.mydomain", "client_addr": "X.Y.Z.T", "state": "streaming", "sync_state": "async", "sync_priority": 0}], "database_system_identifier": "6969625318808753181", "pending_restart": true, "patroni": {"version": "2.0.2", "scope": "12-main"}}


with custommode=tcp I have a warning about deprecated SSL_VERIFY_NONE and the following error:

  at /usr/lib/centreon/centreon-plugins/apps/protocols/x509/custom/tcp.pm line 105.
UNKNOWN: SSL error: SSL wants a read first

**Comment by kikijolicoeur** [comment]
I forgot : 
CentOS : 7.9.2009 with perl-IO-Socket-SSL-1.94-7.el7.noarch

**Comment by kikijolicoeur** [comment]
I just saw the --ssl-ignore-errors and it works with this option : 

CRITICAL: Certificate for 'pouet.mydomain' expires in '361' days [2022-07-02T19:02:47Z] ....

**Comment by garnier-quentin** [comment]
thanks for the feedback!
