### ISSUE TITLE
Enhancement: O365 plugin - get data of cqd for ms teams

### ISSUE THREAD

**Issue by Iralein** [centreon/centreon-plugins#2944]
Hello,

It would be very nice to get some more technical data out of O365 for teams, especially the average call qualities and other stuff.
https://docs.microsoft.com/de-de/microsoftteams/cqd-data-and-reports. MS lists URLs on this site which can be used to query the data.
Maybe this is interesting for others, too.

**Comment by malwahei** [comment]
Hi, has this been done at all? It would be great to be able to fetch the CQD info via Graph API. 
 
Current CQD API is a powershell script and is very cumbersome...requires a login pop-up to sign in manually.   We built a RPA bot that runs regularly and presents the data as sort of an API gateway, and would love to go direct and retire this clumsy bot.
 
In our case, we use ScienceLogic to build out metrics and alerting for each location/subnet from our CQD API fetch.
 
Would be happy to share if anyone is interested.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
