### ISSUE TITLE
apps::protocols::x509::plugin don't send certificate

### ISSUE THREAD

**Issue by kikijolicoeur** [centreon/centreon-plugins#2946]
Hello.
To monitor ETCD expiration certificate : 

/usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::x509::plugin --custommode=https --mode=certificate --hostname=dcroetcd01.hosting.cegedim.cloud --port=2379 --warning-status='%{expiration} < 300' --critical-status='%{expiration} < 400'  --ssl-opt="SSL_verify_mode => SSL_VERIFY_PEER" --ssl-opt="SSL_ca_file => '/etc/pgha/ca.crt'" --ssl-opt="SSL_cert_file => '/etc/pgha/centreon.hosting.cegedim.cloud.crt'" --ssl-opt="SSL_key_file => '/etc/pgha/centreon.hosting.cegedim.cloud.key'" --debug --verbose
UNKNOWN: Can't connect to dcroetcd01.hosting.cegedim.cloud:2379 
======> request send
GET https://dcroetcd01.hosting.cegedim.cloud:2379/
User-Agent: centreon::plugins::backend::http::useragent

======> response done
500 Can't connect to dcroetcd01.hosting.cegedim.cloud:2379
Content-Type: text/plain
Client-Date: Wed, 07 Jul 2021 07:00:52 GMT
Client-Warning: Internal response

Can't connect to dcroetcd01.hosting.cegedim.cloud:2379

And ETCD logs : 
rejected connection from "10.25.134.109:53834" (error "tls: client didn't provide a certificate", ServerName "")

I tried with curl to verify that all is ok with certificates (root CA, cert and key) : 

curl  --cacert /etc/pgha/ca.crt --key /etc/pgha/centreon.hosting.cegedim.cloud.key --cert /etc/pgha/centreon.hosting.cegedim.cloud.crt https://dcroetcd01:2379
It works fine and no error in ETCD logs.

I tried centreon plugin with option --http-backend=curl : 
UNKNOWN: curl setopt error: 'An unknown option was passed in to libcurl'

Best regards

Christian

**Comment by garnier-quentin** [comment]
Have you tried with ```--insecure``` option ?

**Comment by kikijolicoeur** [comment]
yes, with same result

**Comment by garnier-quentin** [comment]
For curl backend, it needs a newer version of libcurl.

**Comment by kikijolicoeur** [comment]
rpm -q -a|grep libcurl
libcurl-7.29.0-59.el7_9.1.x86_64

not good enough ?

**Comment by garnier-quentin** [comment]
Not enough

**Comment by kikijolicoeur** [comment]
I have a lot of pollers with official CentOS 7 repositories. I can't update libcurl easily. 
Is it possible to run x509 plugin without --http-backend=curl but with client certificates sent  ?

**Comment by garnier-quentin** [comment]
We cannot. And i understand that we cant update the libcurl.

**Comment by garnier-quentin** [comment]
Have you tried with --custommode=tcp ?

**Comment by kikijolicoeur** [comment]
Yes but it can't work because with tcp mode, the client certificate is not sent and ETCD closes the  connection.
So I close thhis issue, I will develop a custom command to check ETCD certificate expiration.
Thanks for your investigations.
