### ISSUE TITLE
est il possible de faire un checksum avec le plugin : --plugin=apps::protocols::http::plugin

### ISSUE THREAD

**Issue by cedricneveux** [centreon/centreon-plugins#2947]
Bonjour,

j'ai besoin de faire un checksum de toutes les pages accessibles sur un site web de mon client, sachant que ce site est n'est pas dynamique. je voudrai faire un premier checksum après avoir déposé chaque nouvelle release du site et je dois vérifier quotidiennement qu'aucune page n'a été altérée.
Est-ce que votre plugin "--plugin=apps::protocols::http::plugin" aurait la capacité de faire ce checksum et de comparer le checksum de référence d'une release avec le checksum quotidien?

Merci par avancepour votre réponse.
Cordialement,
Cédric 

Thanks for using centreon-plugins! Please follow the indications shown below according to your issue and describe it in English.

## New Plugins and modes

To develop a Plugin/mode, we need the following:
* SNMP: MIBs files and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk)
* HTTP API (SOAP, Rest/Json, XML-RPC): the documentation and some curls examples
* CLI: command line examples
* SQL: requests
* JMX: mbean names and attributes

If some parts of information are confidentials, please send them directly by email to qgarnier@centreon.com and sbomm@centreon.com.

Please note that all the developments are open-source. We can't give a date for the development, achievement or release. If it's a priority for you,
send us an email about it (qgarnier@centreon.com and sbomm@centreon.com) and we'll put you in touch with our company.

## Bug/Question

If you are reporting a bug/question, make sure that there aren't any similar/duplicates issues already open. You 
can ensure this by searching the issue list for this repository. If so, please close your issue and add a comment to the existing one instead.

Otherwise, open a new issue and provide all parts of information you can (full command line used, actual output, expected output, error message...).

**Comment by garnier-quentin** [comment]
The plugin cannot do a checksum.

**Comment by cedricneveux** [comment]
Merci pour votre réponse très rapide. Bonne journée à vous.

**Comment by garnier-quentin** [comment]
I have done a specific mode for you. 
[expectedcontentchecksum.pm.txt](https://github.com/centreon/centreon-plugins/files/6783101/expectedcontentchecksum.pm.txt)

Copy that file in following directory:
```cp expectedcontentchecksum.pm.txt apps/protocols/http/mode/expectedcontentchecksum.pm```

And an example to use it:
```
perl centreon_plugins.pl --plugin=apps/protocols/http/plugin.pm --dyn-mode=apps/protocols/http/mode/expectedcontentchecksum.pm --hostname=www.google.fr --critical-content='%{checksum} ne "plop"'
```

You can use --debug to see the checksum (for www.google.fr, it changes each time).
