### ISSUE TITLE
Squid plugin:  Cannot load module --plugin

### ISSUE THREAD

**Issue by deadspool** [centreon/centreon-plugins#2950]
Hello,

The current Squid plugin has an issue.
When we execute the plugin, we have the following messages:

`$ ./centreon_plugins.pl --plugin=apps::squid::snmp::plugin --list-modes`

_Useless use of hash element in void context at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/apps/squid/snmp/plugin.pm line 33.
Useless use of anonymous hash ({}) in void context at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/apps/squid/snmp/plugin.pm line 33.
Number found where operator expected at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/apps/squid/snmp/plugin.pm line 41, near "1"
        (Missing semicolon on previous line?)
UNKNOWN: Cannot load module --plugin.
syntax error at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/apps/squid/snmp/plugin.pm line 41, near "1"
Missing right curly or square bracket at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/apps/squid/snmp/plugin.pm line 43, at end of line
Compilation failed in require at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/centreon/plugins/misc.pm line 222._

We have the same issue with plugin in centreon repo and in git repo.

**Comment by deadspool** [comment]
I've edit plugin.pm and replace line 33 (Add missing  '}' ):

old:
_%{$self->{modes} => {
         'cache-usage'       => 'apps::squid::snmp::mode::cacheusage',
         'protocol-stats'    => 'apps::squid::snmp::mode::protocolstats',
     };

    return $self;
 }_

new:
_%{$self->{modes}**}**=> {
         'cache-usage'       => 'apps::squid::snmp::mode::cacheusage',
         'protocol-stats'    => 'apps::squid::snmp::mode::protocolstats',
   };

    return $self;
 }_

Now, we have the message:

` ./centreon_plugins.pl --plugin=apps::squid::snmp::plugin --list-mode`

_Useless use of a variable in void context at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/apps/squid/snmp/plugin.pm line 33.
Useless use of anonymous hash ({}) in void context at /usr/lib/centreon/plugins/source_plugin/centreon-plugins/apps/squid/snmp/plugin.pm line 33.

Plugin Description:
    Check Squid proxy in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

    --pass-manager
            Use a password manager.

Modes Meta:
   multi

Modes Available:_

Modes are not diplayed

**Comment by deadspool** [comment]
OK, I've found the source of issue. This is my changes (line 33)

old:
%{$self->{modes} => {
'cache-usage' => 'apps:🦑:snmp::mode::cacheusage',
'protocol-stats' => 'apps:🦑:snmp::mode::protocolstats',
};
new:
    %{$self->{modes}} = (
        'cache-usage'       => 'apps::squid::snmp::mode::cacheusage',
        'protocol-stats'    => 'apps::squid::snmp::mode::protocolstats',
    );

    return $self;
}

1;

This change resolve my issue.

Best Regards, 

Wade

**Comment by garnier-quentin** [comment]
thanks for the issue, it's fixed in last github version
