### ISSUE TITLE
Meta Service Cannot find a metric SQL Match

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon-plugins#2958]
Hi team

I have these metaservices imported by query directly into database.

![image](https://user-images.githubusercontent.com/25208457/125335630-25a71700-e323-11eb-8e98-5955a9c20754.png)

According to https://github.com/centreon/centreon-plugins/blob/master/apps/centreon/local/mode/metaservice.pm#L91 this output `Cannot find a metric` is caused by 0 count on query match.

I tried to reproduce this query with success manually:
![image](https://user-images.githubusercontent.com/25208457/125336182-d8777500-e323-11eb-9d75-b312411f7cc4.png)

![image](https://user-images.githubusercontent.com/25208457/125336275-f5ac4380-e323-11eb-8775-067bd7640241.png)

So what is wrong?

**Comment by garnier-quentin** [comment]
I have done a patch: https://github.com/centreon/centreon-plugins/commit/af42d59713441b4f744f50dfae98fa20bb55b6d3#diff-a362cf3e840ac8d17d9cd8c901941d6c1c3089d80f13c44b1c3091ffff724df1
Could you test with github last master version ?

**Comment by kozfelipe** [comment]
Yes I've just applied latest  centreon-plugins-master but I still get `Cannot find a metric` as output

**Comment by kozfelipe** [comment]
Hi im sorry to bother

I found out my mistake. It turns out the interface is down then it has no traffic metrics to be found

![image](https://user-images.githubusercontent.com/25208457/125350551-42e4e100-e335-11eb-8510-24e1c50e4f53.png)

**Comment by Sims24** [comment]
@kozfelipe you can avoid this by using `--no-skipped-counters` option. 

Regards
