### ISSUE TITLE
How to use Regexp to set thresholds for a specific instance?

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon-plugins#2964]
Hi 

I'm using network::cisco::standard::snmp::plugin to get temperatures. when I run the plugin I get following result. 

command : 
plugin network::cisco::standard::snmp::plugin    --mode=environment --component temperature   --hostname=xxx   --snmp-version='3'  --snmp-username xxx   --authpassphrase xxx   --authprotocol SHA  --snmp-timeout=''  --warning=''temperature,.*,40''    --critical=''temperature,.*,50'' --verbose

Output : 
Temperature 'Switch 1 - Inlet Temp Sensor, GREEN ' status is normal [instance: 1012] [value: 28 C]
Temperature 'Switch 1 - Outlet Temp Sensor, GREEN ' status is normal [instance: 1013] [value: 36 C]
Temperature 'Switch 1 - HotSpot Temp Sensor, GREEN ' status is normal [instance: 1014] [value: 57 C]
Temperature 'Switch 2 - Inlet Temp Sensor, GREEN ' status is normal [instance: 2012] [value: 28 C]
Temperature 'Switch 2 - Outlet Temp Sensor, GREEN ' status is normal [instance: 2013] [value: 35 C]
Temperature 'Switch 2 - HotSpot Temp Sensor, GREEN ' status is normal [instance: 2014] [value: 56 C]

Is there anyway I can ignore HotSpot sensor in thresholds or set thresholds only for specific sensor? 

PS : I want all of them monitored so I can't filter them out.

Thank You!

**Comment by garnier-quentin** [comment]
You can try following options: ```--add-name-instance --filter=temperature,HotSpot```

**Comment by Sims24** [comment]
If I understand correctly @VidushaZ doesn't want to skip it. 

You can try this it should do the trick: 

`--warning='temperature,1014,40'`

**Comment by VidushaZ** [comment]
Thanx @garnier-quentin @Sims24  

--warning='temperature,Inlet,30' --add-name-instance  
Did the trick for me.
