### ISSUE TITLE
cloud::azure::management::recovery::plugin Command too long to execute (timeout)

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#2970]
Hello,

I use this command : 

`$CENTREONPLUGINS$/centreon_plugins.pl --plugin=cloud::azure::management::recovery::plugin --tenant='xxxxx' --subscription='$_HOSTSUBSCRIPTION$' --client-id='xxxxx' --client-secret='$_HOSTCLIENTSECRET$' --custommode='api' --mode='backup-jobs-status' --resource-group='$_HOSTRESSOURCEGROUPNAME$' --vault-name='$_HOSTVAULTNAME$' --filter-name='$ARG1$' --critical-total-failed='1' --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True" --timeout 240 --timeframe 432000`

But I randomly have this message :

`Command too long to execute (timeout) ...`

Thank you

**Comment by garnier-quentin** [comment]
Maybe you should use following option: ```--custommode=api```

**Comment by prohand** [comment]
It's Ok.
Thank you ;)

**Comment by prohand** [comment]
Hello,

Sorry the problem still occured

Thank you

**Comment by garnier-quentin** [comment]
With the custommode api, it can't be: ```Command too long to execute (timeout) ...```

**Comment by prohand** [comment]
The proof that if :(

**Comment by garnier-quentin** [comment]
Could you provide the command and the output please ?

**Comment by prohand** [comment]
![Image 12](https://user-images.githubusercontent.com/20227162/125949371-81cfeea1-95ba-4e2c-b34d-18452ec9d40e.png)

**Comment by garnier-quentin** [comment]
Could you launch the command directly in a shell ?

**Comment by prohand** [comment]
In command line the problem does not occur.

**Comment by garnier-quentin** [comment]
Have you an issue to poller update ? (centreon-broker)

**Comment by prohand** [comment]
No it's all green

**Comment by garnier-quentin** [comment]
I can't tell why the command output is not well updated in centreon.

**Comment by garnier-quentin** [comment]
Do you use the perl connector ?

**Comment by prohand** [comment]
No. I use the centreon_plugin only

**Comment by garnier-quentin** [comment]
Anyway, it's not an issue of centreon-plugins. It shouldn't change the issue but you can try to restart centengine.

**Comment by prohand** [comment]
I have restart centengine but the problem is same

**Comment by prohand** [comment]
I have restart centengine.
The unknown error disapear for the moment.

**Comment by garnier-quentin** [comment]
thanks for the feedback. we can close it (if you still have the issue, you can comment it)

**Comment by prohand** [comment]
Hello,

The problem still occured

Thank you

**Comment by garnier-quentin** [comment]
But it's working when you execute directly in a shell ? If yes, it's not an issue of centreon-plugins.

**Comment by prohand** [comment]
The problem happens alternately
I'm not sure if the problem occurs again at the command line.
Can you see to forward the request to the right team for them to check?

Thank you

**Comment by garnier-quentin** [comment]
You can try to ask on community slack.
