### ISSUE TITLE
hardware::server::dell::idrac::snmp::plugin state is 'unknown'

### ISSUE THREAD

**Issue by Tech-Chavigny** [centreon/centreon-plugins#2974]
Hello, Everything works except one thing

UNKNOWN: Power unit 'System Board PS Redundancy' state is 'unknown'

![Capture](https://user-images.githubusercontent.com/87609222/126070920-795fd368-90c5-4199-87a5-0791d50b40e5.PNG)

`
[root@centreon plugins]# /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=hardware --hostname=10.1.0.206
UNKNOWN: Power unit 'System Board PS Redundancy' state is 'unknown' | 'amperage_PS1 Current 1'=0.2A;0:;0:;; 'amperage_PS2 Current 2'=0.2A;0:;0:;; 'amperage_System Board Pwr Consumption'=98W;0:1330;0                  :1456;; 'fan_System Board Fan1A'=1680rpm;0:;72:;; 'fan_System Board Fan1B'=1680rpm;0:;72:;; 'fan_System Board Fan2A'=2640rpm;0:;72:;; 'fan_System Board Fan2B'=2520rpm;0:;72:;; 'fan_System Board Fan3                  A'=1680rpm;0:;72:;; 'fan_System Board Fan3B'=1560rpm;0:;72:;; 'fan_System Board Fan4A'=1680rpm;0:;72:;; 'fan_System Board Fan4B'=1560rpm;0:;72:;; 'fan_System Board Fan5A'=1680rpm;0:;72:;; 'fan_Syste                  m Board Fan5B'=1560rpm;0:;72:;; 'temp_System Board Inlet Temp'=24C;3:42;-7:47;; 'temp_CPU1 Temp'=52C;8:83;3:88;; 'voltage_PS1 Voltage 1'=230V;0:;0:;; 'voltage_PS2 Voltage 2'=230V;0:;0:;; 'count_ampe                  rage'=3;;;; 'count_coolingdevice'=10;;;; 'count_coolingunit'=1;;;; 'count_enclosure'=1;;;; 'count_fru'=8;;;; 'count_memory'=2;;;; 'count_network'=4;;;; 'count_pci'=23;;;; 'count_pdisk'=6;;;; 'count_                  processor'=1;;;; 'count_psu'=2;;;; 'count_punit'=1;;;; 'count_storagectrl'=1;;;; 'count_systembattery'=1;;;; 'count_temperature'=2;;;; 'count_vdisk'=1;;;; 'count_voltage'=21;;;;
`

Log SNMPWALK: [dell_idrac.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/6836411/dell_idrac.snmpwalk.txt)

**Comment by Sims24** [comment]
Hello, 

You may want to check this issue: https://github.com/centreon/centreon-plugins/issues/1732 

You can filter it out or overload the threshold to avoid an unknown for this specific power supply. Check out the `--help` output to figure how `--threshold-overload` option works. 

Thanks

**Comment by Tech-Chavigny** [comment]
Ok, how do we get the list? 

example:  psu cpu

**Comment by Sims24** [comment]
From the metrics:

'**fan**_System Board Fan5B'=1560rpm;0:;72:;; '**temp**_System Board Inlet Temp'=24C;3:42;-7:47;;

**Comment by Sims24** [comment]
I close the issue, feel free to re-open if you're still stuck.
