### ISSUE TITLE
New Plugin/Mode for Barco Equipments

### ISSUE THREAD

**Issue by AlexisVarela** [centreon/centreon-plugins#2975]
Hello,

I would like to supervise Barco equipment, specifically ClickShares. 
The SNMP MIB file is compatible with ClickShare CS-100, CS-100 Huddle, CSE-200, CSE-20+ and CSE-800 devices.

[BARCO-CLICKSHARE-MIB.txt](https://github.com/centreon/centreon-plugins/files/6848309/BARCO-CLICKSHARE-MIB.txt)

Here is the requested snmpwalk:

![Snmpwalk-enterprise](https://user-images.githubusercontent.com/44436514/126325851-6d553e1f-3af3-4a77-a359-8b93b53ee763.png)

The equipment used SNMP Version 3 with SHA and AES.

Thank you in advance,
Best Regards,

**Comment by garnier-quentin** [comment]
The MIB is very small. Even sensors values are empty:
sensorCaseFanSpeed
sensorCpuFanSpeed
sensorCpuTemperature

I cant develop a plugin. Maybe there is a rest api with more informations ?

**Comment by AlexisVarela** [comment]
An API for remote control exists for these devices but I did not find more information about it.

**Comment by garnier-quentin** [comment]
There is a documentation: https://www.barco.com/en/clickshare/support/docs/R5900056
But the download doesn't work...

**Comment by AlexisVarela** [comment]
I just successfully downloaded after 30min of loading.
[R5900056_11_ReferenceGuide.pdf](https://github.com/centreon/centreon-plugins/files/6848828/R5900056_11_ReferenceGuide.pdf)

**Comment by garnier-quentin** [comment]
Thanks. Could you provide curl results (in a file) ?
```
curl -u integrator:integrator --basic -k -i -X GET
https://10.192.34.102:4001/v1.0/DeviceInfo/Sensors

curl -u integrator:integrator --basic -k -i -X GET
https://10.192.34.102:4001/v1.0/DeviceInfo/Status


curl -u integrator:integrator --basic -k -i -X GET
https://10.192.34.102:4001/v1.0/DeviceInfo/Processes/ProcessTable
```

**Comment by AlexisVarela** [comment]
[Result_Barco_API.txt](https://github.com/centreon/centreon-plugins/files/6869461/Result_Barco_API.txt)

Hello,

Sorry for the delay. You will find attached the file with the results of the 3 curls.

**Comment by garnier-quentin** [comment]
There are no datas for following endpoints ?
- /v1.0/DeviceInfo/Status
- /v1.0/DeviceInfo/Sensors

**Comment by AlexisVarela** [comment]
[Result_Barco_API.txt](https://github.com/centreon/centreon-plugins/files/6869501/Result_Barco_API.txt)

As far as i'm concerned, here is the modified file.

**Comment by garnier-quentin** [comment]
It's nice. I can do a plugin ;)

**Comment by garnier-quentin** [comment]
You can test it with last git version:
```
centreon_plugins.pl --plugin=hardware::devices::barco::cs::restapi::plugin --mode=device --hostname=barcoaddr --api-username=xxxx --api-password=xxxxxx --verbose
```

**Comment by AlexisVarela** [comment]
Hello,
It works, thank you very much.
I just had to add the option --insecure

**Comment by AlexisVarela** [comment]
Here is the output I have:
![image](https://user-images.githubusercontent.com/44436514/126991998-3a048e87-c76e-4520-8219-1653410234de.png)

**Comment by garnier-quentin** [comment]
thanks for the feedback!

**Comment by AlexisVarela** [comment]
I would like to inform you that with API version 1.11 it is possible to get the CPU fan speed for CSE-200+ and CSE-800.

**Comment by garnier-quentin** [comment]
If you have the curl i could add it :)

**Comment by AlexisVarela** [comment]
[Barco_CURL_SpeedFanCPU.txt](https://github.com/centreon/centreon-plugins/files/6878497/Barco_CURL_SpeedFanCPU.txt)

**Comment by garnier-quentin** [comment]
Could you provide the curl result for a device without that API endpoint ?

**Comment by AlexisVarela** [comment]
Like this ?

[Barco_CURL_SpeedFanCPU.txt](https://github.com/centreon/centreon-plugins/files/6878529/Barco_CURL_SpeedFanCPU.txt)

**Comment by garnier-quentin** [comment]
No. I want the curl for the following endpoint: /v1.11/DeviceInfo/Sensors
But on a equipment without that endpoint working.

**Comment by AlexisVarela** [comment]
I don't have any equipment that doesn't work with v1.11 and this endpoint, I only have CSE-200+ so all compatible.

[Barco_Endpoint_Sensors.txt](https://github.com/centreon/centreon-plugins/files/6878569/Barco_Endpoint_Sensors.txt)

**Comment by garnier-quentin** [comment]
You can use a wrong endpoint otherwise

**Comment by AlexisVarela** [comment]
[Barco_Endpoint_Sensors.txt](https://github.com/centreon/centreon-plugins/files/6878660/Barco_Endpoint_Sensors.txt)

**Comment by garnier-quentin** [comment]
Could you provide a curl result of following endpoint ? /SupportedVersions

**Comment by AlexisVarela** [comment]
[Barco_SupportedVersions.txt](https://github.com/centreon/centreon-plugins/files/6883281/Barco_SupportedVersions.txt)

**Comment by AlexisVarela** [comment]
I realized that I had Barco CSE-100 I made the endpoint /SupportedVersions and they have the same output as the CSE-200+.

**Comment by garnier-quentin** [comment]
Could you test with that version ? 
https://github.com/centreon/centreon-plugins/archive/refs/heads/enh-barco-device.zip

**Comment by AlexisVarela** [comment]
It works

**Comment by garnier-quentin** [comment]
thanks for the feedback!
