### ISSUE TITLE
plugin stockage hitachi

### ISSUE THREAD

**Issue by fdegenne** [centreon/centreon-plugins#2976]
hello,

i would like  supervise volume disk ,pool etc ..on the stockage hitachi vspg400 but the plugin centreon is ok  for hardware only.
i'm use the plugin following:
centreon_hitachi_hnas_snmp.pl
centreon_hitachi_standard_snmp.pl
Thank you in advance,
Best Regards,

**Comment by garnier-quentin** [comment]
We need more informations: MIB files of your equipment and a full snmpwalk.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
