### ISSUE TITLE
Set Thresholds to specific Sensor Temperature 

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon-plugins#2981]
Hi,

Is there anyway to set thresholds for specific sensor here? I want it to set on "Inlet" 

Command : 
--plugin network::cisco::standard::snmp::plugin   --mode=environment --component sensor   --hostname=xxx   --snmp-version='3'  --snmp-username 'xxx'   --authpassphrase xxx   --authprotocol SHA   --privpassphrase xxx  --privprotocol AES --snmp-timeout=''  --warning=''sensor.celsius,'Inlet',10''    --critical=''sensor.celsius,'Inlet',15'' --add-name-instance --verbose

Output : 

OK: All 5 components are ok [5/5 sensors]. | 'sensor.celsius_sensor-1 Inlet'=21C;~:41;~:69;; 'sensor.celsius_sensor-2 outlet'=25C;~:69;~:79;; 'sensor.celsius_sensor-3 x86 processor'=29C;~:79;~:89;; 'sensor.celsius_sensor-4 Sugarbowl'=49C;~:89;~:109;; 'sensor.celsius_sensor-5 Sugarbowl vrm'=49C;~:109;~:119;; 'count_sensor'=5;;;;
Environment type: unknown
Checking sensors
Sensor 'sensor-1 Inlet' status is 'ok' [instance: 23254] [value: 21 celsius]
Sensor 'sensor-2 outlet' status is 'ok' [instance: 23255] [value: 25 celsius]
Sensor 'sensor-3 x86 processor' status is 'ok' [instance: 23256] [value: 29 celsius]
Sensor 'sensor-4 Sugarbowl' status is 'ok' [instance: 23257] [value: 49 celsius]
Sensor 'sensor-5 Sugarbowl vrm' status is 'ok' [instance: 23258] [value: 49 celsius]

It looks like regex is not working here. Am I doing it right? Because in other devices I could do it the same way but used temperature as component in command But this device's temperature cannot be taken from Temperature component but the sensor component. 

Thank You!

**Comment by garnier-quentin** [comment]
Could you try without quote ?
```--warning=''sensor.celsius,Inlet,10'' --critical=''sensor.celsius,Inlet,15''```

**Comment by VidushaZ** [comment]
@garnier-quentin I did try and still same.

**Comment by garnier-quentin** [comment]
For me, it's working. Are you using the last version ?
```
... --warning=''sensor.celsius,Inlet,10'' --critical=''sensor.celsius,Inlet,15'' --add-name-instance
CRITICAL: Sensor 'Temp: Inlet/122' is 37 
```

**Comment by VidushaZ** [comment]
@garnier-quentin  Yes I have the latest one. Are you using temperature as the component here? Because it's working fine when I use temperature as the component (--component temperature). It does not work when I use sensor as the component.  ( --component sensor)

**Comment by garnier-quentin** [comment]
My test is for sensor component. Could you provide the full command and output please ?

**Comment by VidushaZ** [comment]
@garnier-quentin OMG looks like I haven't updated the plugins correctly. Just updated to the latest one and now it's working. Thank you very much!!
