### ISSUE TITLE
[VMware] Catch vCenter top-level alarms

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-plugins#2983]
Hi,

I'm not sure whether or not it's possible (I did not find anything relevant yet), but would be pretty nice to be able to monitor the VMware Skyline health status :

![Screenshot 2021-07-22 at 16 12 40](https://user-images.githubusercontent.com/40244829/126654620-912feebe-f471-4aad-af56-d479445c2715.png)

Mmmmh finally I just figured-out Skyline Health also appears as alarms.
But at the very top level / VCSA (see below screenshot).
Not at the datacenter level (mode `alarm-datacenter`), not at the host level (mode `alarm-host`).
Perhaps we then miss some alarm modes ? VCSA ? Cluster ? VM ?

![Screenshot 2021-07-23 at 15 58 05](https://user-images.githubusercontent.com/40244829/126793495-5cb8a104-a752-4bfd-85f9-9ff29f71e486.png)

Thank you 👍

**Comment by garnier-quentin** [comment]
If you find a API, why not.

**Comment by UrBnW** [comment]
Mmmmh I just figured-out Skyline Health also appears as alarms.
But at the very top level / VCSA (see below screenshot).
Not at the datacenter level (mode `alarm-datacenter`), not at the host level (mode `alarm-host`).
Perhaps we then miss some alarm modes ? VCSA ? Cluster ? VM ?

![Screenshot 2021-07-23 at 15 58 05](https://user-images.githubusercontent.com/40244829/126793495-5cb8a104-a752-4bfd-85f9-9ff29f71e486.png)

**Comment by UrBnW** [comment]
Instead of using the `triggeredAlarmState` property of entities, and as there is apparently no "top level" entity, I wonder whether or not the [GetAlarm method](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.alarm.AlarmManager.html#getAlarm) from the AlarmManager would do the trick, grabbing ALL alarms from the top level / VSCA.
If so, we could imagine only one alarm mode, with some filter options (datacenter, cluster, host, vm...).

Default VCSA configuration defines a lot of alarms at top level, goal would then be to be able to catch them...
Thx :+1:

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
