### ISSUE TITLE
database::elasticsearch::restapi::plugin license - Use of uninitialized value in division

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#2986]
Hello,

I have an extra line in the output of the plugin when checking the license for elasticsearch.
centreon_plugins.pl --plugin="database::elasticsearch::restapi::plugin" --mode="license" --http-backend="curl" --username="xxxx" --password="xxxx" --port="9200"  --hostname=......
This error is only when elasticsearch have a BASIC license.

Plugin Output:
Use of uninitialized value in division (/) at database/elasticsearch/restapi/mode/license.pm line 78.
OK: License Status 'active' [type: basic] [issued to: yyyyyy] [issue date: 2019-07-10T07:17:51.498Z]

With a PLATINUM license I do not have this output.

Plugin Output:
OK: License Status 'active' [type: platinum] [issued to: zzzzz] [issue date: 2020-12-23T00:00:00./]

I think the variable expiry_date_in_millis does not exist with a basic license.

Line 83 in the file database/elasticsearch/restapi/mode/license.pm
expiry_date_in_seconds => int($result->{license}->{expiry_date_in_millis} / 1000)

Is it possible to do an extra check on the variable so that the message is no longer visible.

regards,
Geert

**Comment by Sims24** [comment]
Hello, 

Yes of course we will manage this case, could you provide the JSON returned by the API when using a basic license? 

Thanks

**Comment by gbin2265** [comment]
Hello, 

see here the output for aan BASIC ande PLATIUM license ! 
(I have changed personal info for security reasons).

BASIC
Use of uninitialized value in division (/) at database/elasticsearch/restapi/mode/license.pm line 78.
OK: License Status 'active' [type: basic] [issued to: xxx] [issue date: 2019-10-23T10:00:52.755Z] |
== Info: About to connect() to x.x.x.x port 9200 (#0)
== Info:   Trying x.x.x.x...
== Info: Connected to x.x.x.x (x.x.x.x) port 9200 (#0)
== Info: Server auth using Basic with user 'icinga'
=> Send header: GET /_license HTTP/1.1
Authorization: Basic zzzzzzzzzzzzzzzzzzzz
Host: x.x.x.x:9200
Accept: */*

=> Recv header: HTTP/1.1 200 OK
=> Recv header: content-type: application/json; charset=UTF-8
=> Recv header: content-length: 332
=> Recv header:
=> Recv data: {
  "license" : {
    "status" : "active",
    "uid" : "zzzzzzzzzzzzzzzzzzzz",
    "type" : "basic",
    "issue_date" : "2019-10-23T10:00:52.755Z",
    "issue_date_in_millis" : 1571824852755,
    "max_nodes" : 1000,
    "issued_to" : "xxx",
    "issuer" : "elasticsearch",
    "start_date_in_millis" : -1
  }
}
== Info: Connection #0 to host x.x.x.x left intact



PLATIUM license 
OK: License Status 'active' [type: platinum] [issued to: xxxx] [issue date: 2020-12-23T00:00:00.000Z] |
== Info: About to connect() to x.x.x.x port 9200 (#0)
== Info:   Trying x.x.x.x...
== Info: Connected to x.x.x.x (x.x.x.x) port 9200 (#0)
== Info: Server auth using Basic with user 'icinga'
=> Send header: GET /_license HTTP/1.1
Authorization: Basic zzzzzzzzzzzzzzzzzzzz
Host: x.x.x.x:9200
Accept: */*

=> Recv header: HTTP/1.1 200 OK
=> Recv header: content-type: application/json; charset=UTF-8
=> Recv header: content-length: 440
=> Recv header:
=> Recv data: {
  "license" : {
    "status" : "active",
    "uid" : "zzzzzzzzzzzzzzzzzzzz",
    "type" : "platinum",
    "issue_date" : "2020-12-23T00:00:00.000Z",
    "issue_date_in_millis" : 1608681600000,
    "expiry_date" : "2021-12-31T23:59:59.999Z",
    "expiry_date_in_millis" : 1640995199999,
    "max_nodes" : 6,
    "issued_to" : "xxxx",
    "issuer" : "API",
    "start_date_in_millis" : 1608681600000
  }
}
== Info: Connection #0 to host x.x.x.x left intact


Hopefully this is enough for you!?
regards,
Geert

**Comment by Sims24** [comment]
Perfect, I think you can change line 83 like this: 

```
          expiry_date_in_seconds => defined($result->{license}->{expiry_date_in_millis}) ? int($result->{license}->{expiry_date_in_millis} / 1000) : "n/a"
```

It should do the job, if so let me now or even better offer a PR :) 

Thanks for using centreon-plugins and providing feedbacks

**Comment by gbin2265** [comment]
hello, 

I put the solution in my local code and now I don't have a debug error line anymore.


Basic
Plugin Output
OK: License Status 'active' [type: basic] [issued to: xxxx] [issue date: 2020-03-27T14:40:43.800Z]


Platium
Plugin Output
OK: License Status 'active' [type: platinum] [issued to: xxx] [issue date: 2020-12-23T00:00:00.000Z]


Thank you for the solution.


regards,
Geert
