### ISSUE TITLE
Set thresholds to Temperature in checkpoint hardware plugin

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon-plugins#2987]
Hi I'm using checkpoint plugin to get temperature. How can I set temperature thresholds for specific parameter? 
I've done it with cisco standard plugins before but cannot find a way to do the same in checkpoint plugin. 

Command : 

/usr/lib/centreon/plugins-new/plugins.pl   --plugin network::checkpoint::snmp::plugin    --mode=hardware      --component temperature  --hostname=xxx   --snmp-version='3'   --snmp-username xxx --authpassphrase xxx   --authprotocol SHA   --privpassphrase xxx   --privprotocol AES --threshold-overload='temperature,CRITICAL,^(?!(false)$)'

Output : 

OK: All 3 components are ok [3/3 temperatures]. | 'temp_Intake Temp_1.0'=40.00C;;;; 'temp_Outlet Temp_2.0'=41.00C;;;; 'temp_CPU Temp_3.0'=39.00C;;;; 'count_temperature'=3;;;;
Checking temperatures
Temperature 'Intake Temp' sensor out of range status is 'false' [instance: 1.0]
Temperature 'Outlet Temp' sensor out of range status is 'false' [instance: 2.0]
Temperature 'CPU Temp' sensor out of range status is 'false' [instance: 3.0]

Instead of checking out of range status for Temperature. Can I set thresholds for temperature like warning above 40C? 

Thanx!

**Comment by garnier-quentin** [comment]
You need the last version and you could use following options:
```
--add-name-instance --warning='temperature,Inlet,40'
```

**Comment by VidushaZ** [comment]
@garnier-quentin  I have the latest one and these parameters are not working with checkpoint plugins. it says 

Unknown option: warning at /usr/lib/centreon/plugins-release/centreon-plugins-20210520/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by garnier-quentin** [comment]
I have done a patch 10 minutes ago ;)

**Comment by VidushaZ** [comment]
@garnier-quentin  my man :smiley:
