### ISSUE TITLE
[network::extreme:NX7500::CPU::plugin] Request CPU and RAM plugins 

### ISSUE THREAD

**Issue by puischevrier** [centreon/centreon-plugins#2988]
Hi,

I need to monitor Extreme Network NX7500 CPU and RAM.

Centreon Extreme plugin monitor these OID which are not found on NX7500 :

CPU :
.1.3.6.1.4.1.1916.1.32.1.4.1
https://github.com/centreon/centreon-plugins/blob/master/network/extreme/snmp/mode/cpu.pm

Memory :
.1.3.6.1.4.1.1916.1.32.2.2.1
https://github.com/centreon/centreon-plugins/blob/master/network/extreme/snmp/mode/memory.pm

Regards,
HP
NB : MIB + snmpwalk sent separately (confidential informations)

**Comment by garnier-quentin** [comment]
You can send me the snmpwalk and mibs to my email.

**Comment by garnier-quentin** [comment]
I take a look. So Extreme NX uses a Wing firmware (from Symbol technology). So we cannot check with extreme OIDs.
I need to create a new plugin: network/symbol/wing/snmp

**Comment by puischevrier** [comment]
Thanks for the information.

**Comment by garnier-quentin** [comment]
With the last version, you can test the following plugin:
```
$ perl centreon_plugins.pl --plugin=network::symbol::wing::snmp::plugin --mode=systems  --verbose --hostname=127.0.0.1 --snmp-community=public
```
