### ISSUE TITLE
database::mysql::plugin - new mode for Galera Cluster status

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#2991]
Could you add a new mode to check Galera Cluster: https://galeracluster.com/library/training/tutorials/galera-monitoring.html

There are different "`SHOW GLOBAL STATUS`" that allows to now:

- Node/Cluster status
- Replication health

**Comment by joschi99** [comment]
Is there any new for them?

```
SELECT * FROM information_schema.global_status WHERE variable_name IN ('WSREP_CLUSTER_STATUS','WSREP_LOCAL_STATE_COMMENT','WSREP_CLUSTER_SIZE','WSREP_READY');
+---------------------------+---------------------------+
| VARIABLE_NAME             | VARIABLE_VALUE            |
+---------------------------+---------------------------+
| WSREP_LOCAL_STATE_COMMENT | Synced                    |
| WSREP_CLUSTER_SIZE        | 3                         |
| WSREP_CLUSTER_STATUS      | Primary                   |
| WSREP_READY               | ON                        |
+---------------------------+---------------------------+
```

**Comment by joschi99** [comment]
Some news about this request?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
