### ISSUE TITLE
apps::vmware::connector::plugin "filter out" option for "tools-vm" mode

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-plugins#2993]
The "tools-vm" mode of apps::vmware::connector::plugin has a filter-in option of the name "--vm-hostname" - this option is interpreted as "filter IN only this specific hostname". Is there an out of the box option fo "filter OUT these hostnames" - either defined as a list of hostnames to filter out or a regexp (counterpart to "--filter : VM hostname is a regexp.")?

In essence create a FILTER OUT THESE HOSTNAMES from the output. 

Linking issue #1229 #1253

**Comment by garnier-quentin** [comment]
You can use negative regexp (if i understand your issue)

**Comment by hecko** [comment]
That is true, however I believe

1. Users who manage centreon macros are (IMO) not skilled in something like regexp
2. regexps are prone to typos and could be falsely interpreted by even a highly skilled user
3. regex/ps have lots of different flavors so documentation can be misleading - especially in something like negative expressions 

Technically regexps are great way to manipulate / match strings, but Im not very confident this is the best choice for something like centreon plugin to use as a first choice in filtering in or filtering out items.

This is probably technically a correct solution @garnier-quentin, however I very much believe it would be for the benefit of centreon community not to rely on regexps in centreon plugins so much. They are versatile, but self-documentation is poor (IMO).

**Comment by garnier-quentin** [comment]
What do you suggest ?

**Comment by hecko** [comment]
Well, from my perspective a simple

```
--filter-in hostname1,hostname2,hostname3
```

Would do the trick.

This must then imply that:
* all hosts are ignored other than the ones in the list
* there is no `--filter-out` (or equivalent) option set for the plugin (there would be a check that either one of these options are applied, not both)

I can see your point about the vmware - I need to investigate whether this is actually connector which does the filtering or the vmware API as Im not familiar with the interface very much - I can see how this could be a problem in this particular case, but maybe the vmware connector (or the plugin itself) could do the translation from the CSV format to regexp in the background if regexp is required by vmware api.

Also it would be absolutely great to be less ambiguous about the word 'filter'. Filter is just a filter, I believe it should be very specific from the option name whether we are filtering IN or filtering OUT. Another way is to use the words 'include' and 'exclude' instead of filter-in and filter-out maybe.

**Comment by garnier-quentin** [comment]
I'm not sure how to implement it. Right now, you have the option:
```
--vm-hostname: VM hostname to check. If not set, we check all VMs.
--filter: VM hostname is a regexp.
```
Maybe we can add something to exclude it. Users can add option --exclude. And with that option, i will add the negative stuff for the regexp. What do you think about it ? For me ',' or '|' is quite the same.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
