### ISSUE TITLE
[os::windows::snmp::plugin] - Check all Windows services with startup type is auto

### ISSUE THREAD

**Issue by Spleeff** [centreon/centreon-plugins#2994]
Hello,
I migrate our Nagios server to the Centreon solution.
Using SNMP (currently I am using NSClient ++ with Nagios), I would like to generate a warning status or a critical status (whatever) if a service (whatever the name) which has the startup type "Automatic" is not in a "Running" status.
Likewise, being able to exclude services voluntarily.

Here is the command used on the Nagios side for the moment :
_/usr/lib64/nagios/plugins/crit2warn.sh /usr/lib64/nagios/plugins/check_nrpe -H MyHOST -c CheckServiceState -a CheckAll exclude=TBS exclude=ShellHWDetection exclude=clr_optimization_v4.0.30319_32 exclude=clr_optimization_v4.0.30319_64 exclude=sppsvc exclude=spupdsvc exclude=MMCSS exclude=gupdate exclude=gupdatem exclude=TrustedInstaller exclude=RemoteRegistry exclude=wscsvc exclude=SysmonLog exclude=MapsBroker exclude=WbioSrvc exclude=MSExchangeNotificationsBroker_

Is this possible in Centreon via SNMP ?
Thanks a lot for your help !

**Comment by Spleeff** [comment]
![2021-07-26 21_38_21-Window](https://user-images.githubusercontent.com/66731781/127048527-93d5c902-c620-4f33-8ae7-58fef6ce9beb.png)

**Comment by Sims24** [comment]
Hey @Spleeff , 

SNMP MIB doesn't offer OID to figure this out and filter accordingly: 

![image](https://user-images.githubusercontent.com/12429463/127102984-beffb00f-3aeb-4a3e-9cac-14c663fde333.png)

You may want to use our own centreon-nsclient agent or keep the existing one to implement something similar in Centreon. If you're interested in setting up the agent, please check out this doc: https://docs.centreon.com/20.10/en/integrations/plugin-packs/tutorials/centreon-nsclient-tutorial.html#docsNav

**Comment by Spleeff** [comment]
Alright I understand.
I wanted to do without NSClient ++ completely but I don't think that is going to be possible.

Many thanks for your help.

**Comment by garnier-quentin** [comment]
Maybe you can check winrm

**Comment by Spleeff** [comment]
Thank you for your suggestion, I will investigate :)
