### ISSUE TITLE
[network::fortinet::fortigate::snmp::plugin] SD-WAN health links

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#2999]
Hi,

For the [network::fortinet::fortigate::snmp::plugin] is it possible to add support of SD-WAN health links please? 

The firewall can used multiple WAN links (to load balance the trafic for example), and it can monitor them in the "Performance SLA menu". The MIB give information about links health:

https://kb.fortinet.com/kb/documentLink.do?externalID=FD45663

![sla-edit](https://user-images.githubusercontent.com/322320/127526343-9ba33e4c-c26f-4a91-ad86-3c0e5842aee9.png)
![sla-monitor](https://user-images.githubusercontent.com/322320/127526346-e00f99cc-b8ae-4ec1-a0bf-69ef3c3ac8a9.png)

**Comment by garnier-quentin** [comment]
Could you provide the full snmpwalk ? You can send it by email.

**Comment by garnier-quentin** [comment]
You can test with following archive: https://github.com/centreon/centreon-plugins/archive/refs/heads/add-fortigate-sdwan.zip
Test: ```perl centreon_plugins.pl --plugin=network::fortinet::fortigate::snmp::plugin --mode=sdwan```

**Comment by joschi99** [comment]
Hi @garnier-quentin,
have done some test and looks very good. Here some output:

```
checking sd-wan 'Internet_QOS' [vdom: root] [interface: port2]
    state: up
    traffic in: 0.00 b/s, out: 76.92 Gb/s, bi: 153.84 Gb/s
    latency: 7.894ms
    jitter: 0.344ms
checking sd-wan 'Internet_QOS' [vdom: root] [interface: wan1]
    state: up
    traffic in: 76.61 Gb/s, out: 76.91 Gb/s, bi: 153.52 Gb/s
    latency: 7.302ms
    jitter: 0.217ms
checking sd-wan 'Internet_QOS' [vdom: root] [interface: wan2]
    state: up
    traffic in: 538.46 Kb/s, out: 769.23 Kb/s, bi: 1.31 Mb/s
    latency: 8.688ms
    jitter: 1.368ms
checking sd-wan 'PingRbsFGT' [vdom: root] [interface: VPN1-RBS-W2]
    state: up
    traffic in: 230.77 Kb/s, out: 538.46 Kb/s, bi: 769.23 Kb/s
    latency: 55.495ms
    jitter: 0.381ms
checking sd-wan 'PingRbsFGT' [vdom: root] [interface: VPN2-RBS-W2]
    state: up
    traffic in: 76.92 Kb/s, out: 0.00 b/s, bi: 76.92 Kb/s
    latency: 59.565ms
    jitter: 2.879ms
```

**Comment by garnier-quentin** [comment]
thanks for the feedback!
