### ISSUE TITLE
[storage::qnap::snmp::plugin] cpu fix 100%

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#300]
CPU usage is fix 100%.
Plugin tested on a QNAP TS-219+ with firmware 4.2.0 Build 20151118 
```
perl centreon_plugins.pl --plugin=storage::qnap::snmp::plugin --mode=cpu
OK: CPU(s) average usage is: 100.00% | 'cpu0'=100.00%;;;0;100 'total_cpu_avg'=100.00%;;;0;100
```

**Comment by garnier-quentin** [comment]
I don't know. Could you ask to qnap ?

**Comment by joschi99** [comment]
The QNAP is not on 100% CPU, but the plugin shows 100%.

**Comment by garnier-quentin** [comment]
Could you use a snmpwalk on the OIDs ?

**Comment by joschi99** [comment]
I tried it on the oid .1.3.6.1.2.1.25.3.3.1.2 and the QNAP returns 100, so it seem's a problem on QNAP side.

**Comment by garnier-quentin** [comment]
Thanks for the feedback.
