### ISSUE TITLE
[storage::emc::DataDomain::plugin] --mode=hardware - UNKNOWN while disk status system

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3005]
If there a disks on a datadomain in status system the plugin will result UNKNOWN and not OK

UNKNOWN: Disk '2.1' status is 'system' - Disk '2.2' status is 'system' | 'count_disk'=16;;;;
DataDomain OS version: 7.6.0.
Checking disks
Disk '2.1' status is 'system'
Disk '2.2' status is 'system'

**Comment by garnier-quentin** [comment]
It's fixed in last git version. Thanks for the issue!
