### ISSUE TITLE
No warning data for ILO temperature

### ISSUE THREAD

**Issue by nferrers** [centreon/centreon-plugins#3013]
It's supposed that default threshold data should be taken from ILO, but for redfish::restapi plugin the warning value has not been defined, as consequence warning value is not displayed on centreon

Maybe a line is missing in temperature.pm file, add $warn line before $crit solved the issue for me.

https://github.com/centreon/centreon-plugins/blob/66cf4671a752972879198fbbc69704f68c8a4d2e/centreon/common/redfish/restapi/mode/components/temperature.pm#L81

**Comment by garnier-quentin** [comment]
You're right. it's fixed in last version.
