### ISSUE TITLE
[storage::qnap::snmp::plugin] - extend/new mode to check LUN/Storage Pool usage

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3017]
The mode "volume-usage" is only working on QNAP volumes. If you have only LUNs/Storage Pools there is no way to monitor the usage. Could you extend the mode "volume-usage" or create a new mode?
![image](https://user-images.githubusercontent.com/6400595/128175593-1b5ecd26-b660-444f-9b9b-d96eacb9aa33.png)

**Comment by garnier-quentin** [comment]
There is a mode for pools ? Have you tried it ?

**Comment by joschi99** [comment]
No, on version 20210522 this mode is not yet existing, but I tried with latest and seems working. Thanks

**Comment by garnier-quentin** [comment]
Yes it's a new mode ;)
