### ISSUE TITLE
Are threshold values generally defined for the different modes?

### ISSUE THREAD

**Issue by Cynexxde** [centreon/centreon-plugins#3031]
Hello everyone, 
I use the plugin package to monitor switches among other things. For this purpose, I would like to create a command that retrieves the required information. Now it says in the documentation that you cannot define specific thresholds for warnings if you use the multi mode. Are threshold values generally defined for CPU and RAM, for example? If that is the case, then this would be sufficient for me. Does anyone happen to know? I have no way of testing this.

/opt/openitc/nagios/libexec/centreon-plugins/centreon_plugins.pl  --plugin network::hp::procurve::snmp::plugin --hostname $HOSTADDRESS$ --snmp-version 3 --snmp-username $USER4$ --authpassphrase $USER5$ --authprotocol SHA --privpassphrase $USER6$ --privprotocol AES --mode multi --modes-exec environment,cpu,memory --change-perfdata='used_1,,percent()' --change-perfdata=used_1,RAM --change-perfdata=cpu_usage,CPU --filter-perfdata="CPU|RAM"

**Comment by garnier-quentin** [comment]
It's an error. You can:
```
$ perl centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=multi --hostname=127.0.0.1 --modes-exec=cpu,memory --option-mode='cpu,--warning-average=80'
```

**Comment by Cynexxde** [comment]
@garnier-quentin This helped me a lot, thank you very much!
