### ISSUE TITLE
PaloAlto service templates share same alias

### ISSUE THREAD

**Issue by Fuuzz** [centreon/centreon-plugins#3033]
Hi, 

When downloading plugin pack for PaloAlto, the following host template is created:

Net-PaloAlto-Standard-SNMP-custom

By default, the following services templates are linked to the template: 

Net-PaloAlto-Standard-CPU-SNMP-custom	
Net-PaloAlto-Standard-Memory-SNMP-custom	
Net-PaloAlto-Standard-Sessions-SNMP-custom	
Net-PaloAlto-Standard-Hardware-SNMP-custom

Trying to add the Net-PaloAlto-Standard-Signatures-SNMP-custom service template to the Net-PaloAlto-Standard-SNMP-custom host template, the Signatures service is not created when the host template is applied.

This seems related to the alias field of the service template, that results as follow with the same alias for both services:

Net-PaloAlto-Standard-Sessions-SNMP-custom	Sessions
Net-PaloAlto-Standard-Signatures-SNMP-custom	Sessions

By editing the Net-PaloAlto-Standard-Signatures-SNMP-custom alias with the proper description, the service is created succesfully when the host template is applied:

Net-PaloAlto-Standard-Sessions-SNMP-custom	Sessions
Net-PaloAlto-Standard-Signatures-SNMP-custom	Signatures

Can you modify the Net-PaloAlto-Standard-Signatures-SNMP alias field to match the service, instead of being a duplicate of "sessions"?
Thank you in advance :)

**Comment by garnier-quentin** [comment]
Thanks. it will be fixed in next release.
