### ISSUE TITLE
HP Procurve system temperature state is not present

### ISSUE THREAD

**Issue by Cynexxde** [centreon/centreon-plugins#3035]
Hello, it's me again,

on our switches with temperature sensors, the plug-in cannot be executed as planned. For some reason, the plugin cannot read the temperature. I can see the temperature directly on the switches without any problems. Does anyone have an idea what the problem could be?

/opt/openitc/nagios/libexec/centreon-plugins/centreon_plugins.pl --plugin network::hp::procurve::snmp::plugin --hostname ####### --snmp-version 3 --snmp-username ####### --authpassphrase ####### --authprotocol SHA --privpassphrase ####### --privprotocol AES --mode multi --modes-exec environment

WARNING: temperature sensor 'temperature.1' state is not present | 'hardware.fan.count'=5;;;; 'hardware.psu.count'=2;;;; 'hardware.sensor.count'=1;;;;

hp2930-43# show system temperature
System Air Temperature
  Temp    Current  Max   Min
  Sensor  Temp     Temp  Temp  Threshold  OverTemp
  Chassis 22C      29C   17C   55C        NO

**Comment by garnier-quentin** [comment]
If you have MIBs files and a full snmpwalk i could take a look.

**Comment by Cynexxde** [comment]
The MIBs are availabale on the [HPE Website](https://h10145.www1.hpe.com/downloads/DownloadSoftware.aspx?SoftwareReleaseUId=28647&ProductNumber=JL322A&lang=&cc=&prodSeriesId=&SaidNumber=). 

Do you really need a complete SNMP walk? I can't keep track of all the information it contains. Accordingly, I don't like to share everything. However, I have looked up the corresponding OIDs.

current Temp .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0
11.08.2021 11:51:57 (33 ms) : Value: 22C

min Temp .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.5.0
11.08.2021 11:51:42 (345 ms) : Value: 17C

max Temp .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.4.0
11.08.2021 11:51:27 (35 ms) : Value: 29C

Temp Threshold .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.7.0
11.08.2021 11:50:42 (37 ms) : Value: 55C

**Comment by Cynexxde** [comment]
I can also test more OIDs if you give them to me.

**Comment by Cynexxde** [comment]
I have just encountered a similar problem with an HP 2920 switch. In the CLI of the switch I can see the information of the power supply unit.

WARNING: power supply sensor 'power supply.6' state is not present | 'hardware.fan.count'=3;;;; 'hardware.psu.count'=1;;;; 'hardware.sensor.count'=9;;;; 'CPU'=34%;0:80;0:90;0;100 'RAM'=52.85%;0.00:80.00;0.00:90.00;0;100

**Comment by Cynexxde** [comment]
I'm not quite sure if I'm really doing a full SNMP walk. If I use the command "snmpwalk 10.#.#.# -v 1 -c public >2930_JL322A.txt" then I get a file with some values, but the temperature is not included. However, with the command "snmpwalk 10.#.#.# -v 1 -c public .1.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0" I get the following output "iso.3.6.1.4.1.11.2.14.11.1.2.8.1.1.3.0 = STRING: "24C"". So this value should also be found in the previous created file or?

**Comment by Cynexxde** [comment]
[2930_JL322A_MIB.txt](https://github.com/centreon/centreon-plugins/files/6991987/2930_JL322A_MIB.txt)
[2930_JL322A.txt](https://github.com/centreon/centreon-plugins/files/6991988/2930_JL322A.txt)

**Comment by Cynexxde** [comment]
> I have just encountered a similar problem with an HP 2920 switch. In the CLI of the switch I can see the information of the power supply unit.
> 
> WARNING: power supply sensor 'power supply.6' state is not present | 'hardware.fan.count'=3;;;; 'hardware.psu.count'=1;;;; 'hardware.sensor.count'=9;;;; 'CPU'=34%;0:80;0:90;0;100 'RAM'=52.85%;0.00:80.00;0.00:90.00;0;100



I continued testing on the 2920 switches. All of them report the above mentioned error with power supply 6. But both power supplies are installed and they have different IDs. I was able to find this out by removing the respective power supply.

**Internal PSU (HP2920):**     CRITICAL: power supply sensor 'power supply.2' state is bad
**External PSU (HP RPS 640):**    CRITICAL: power supply sensor 'power supply.8' state is bad

Could you please adjust the plugin so that it does not show an error when using the 2920 switches? I would like to be able to monitor all of our switches with one command. It is definitely not a hardware issue and there is no option for another power supply available.

I have also done a SNMP walk for this model. 
[2920_J9728A.txt](https://github.com/centreon/centreon-plugins/files/7020539/2920_J9728A.txt)
[2920_J9728A_MIB.txt](https://github.com/centreon/centreon-plugins/files/7020540/2920_J9728A_MIB.txt)

**Comment by Cynexxde** [comment]
@garnier-quentin Could you please take a look at these two issues in the future? I don't have a lot of time pressure, but would really like to see some customization so I can integrate our switches.

**Comment by garnier-quentin** [comment]
I don't understand the last message. You want me to remove critical for state ```bad``` ? ```bad``` seems an error for me.

**Comment by Cynexxde** [comment]
No, that is correct. I only tested whether the two installed power supplies are identified as critical in the monitoring when I disconnect them from the power. This leads me to conclude that the sensor "power supply.6" should not be present at all. I would like to see that the message does not appear only on hp2920 switches, so that I can use the same command on all our switches (hp2530,hp2920 and hp2930).

With the hp2930 switches, the problem is with temperatures. There the sensor "temperature.1" is marked as not present, although the temperatures can be retrieved within the CLI.

**Comment by garnier-quentin** [comment]
Ok. I will configure 'not present' as OK by default

**Comment by garnier-quentin** [comment]
snmpwalk are incomplete. Could you provide me snmpwalk with following command:
```
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.11 > hp.snmpwalk
```

**Comment by Cynexxde** [comment]
Here are the two files. The temperatures are contained there in each case. Optionally, depending on the complexity, you could also add the temperature as perfdata. However, it should be noted that the hp2530 has no temperature sensors. Only the hp2920 and the hp2930 have them.

[hp2920.txt](https://github.com/centreon/centreon-plugins/files/7091099/hp2920.txt)
[hp2930.txt](https://github.com/centreon/centreon-plugins/files/7091100/hp2930.txt)

**Comment by garnier-quentin** [comment]
You can test with last git version

**Comment by Cynexxde** [comment]
A general problem now occurs with the memory mode.
This results in the following error message.

String found where operator expected at /centreon-plugins-test/network/hp/procurve/snmp/mode/memory.pm line 35, near "'critical:s'"
        (Missing semicolon on previous line?)
"my" variable $self masks earlier declaration in same scope at /centreon-plugins-test/network/hp/procurve/snmp/mode/memory.pm line 56.
"my" variable %options masks earlier declaration in same scope at /centreon-plugins-test/network/hp/procurve/snmp/mode/memory.pm line 56.
"state" variable @_ masks earlier declaration in same scope at /centreon-plugins-test/network/hp/procurve/snmp/mode/memory.pm line 56.


With the hp2920 everything is monitored cleanly and for both power supplies an error is displayed when you disconnect them from power. However, the second power supply is now listed as a sensor, which can be confusing if you don't know. This is probably because the power supply is installed externally. This would be an optional adjustment that I wouldn't necessarily need, but it would be something that others might want.

OK: All 14 components are ok [3/3 fans, 1/1 psu, 9/9 sensors, 1/1 temperatures].

**Comment by Cynexxde** [comment]
I cannot find any other problems. Thank you very much for the adjustment.
