### ISSUE TITLE
O365 New mode : Check licence quantity

### ISSUE THREAD

**Issue by Nasroxy** [centreon/centreon-plugins#3038]
Hi, We need a new mode for centreon-plugins/cloud/microsoft/office365/. We wish check the number of licence in the admin  interface et make a alarme by thresold, and to have performance da ta for following this.

Today, we can obtain this information with pssession in powershell 

`New-PsSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $cred -Authentication Basic -AllowRedirection`

When we have connected, the interesting command is :` Get-MsolAccountSku`

The result is an object with some elements necessary for us :
- SkuPartNumber : Name of licence, is it possible to make a filter like other check in regex?
- ActiveUnits : Quantity licence buy, the value can be value max in performance data
- ConsumedUnts : Quantity licence currenly used. the value may be used in  performance data.
Is it possible to make treshold in the quantity of licence? (in number or percent)

Thank you

**Comment by UrBnW** [comment]
I had a look at this in the past, required API endpoints are here :
https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0ah
It's then possible to enhance existing `cloud::microsoft::office365::custom::graphapi`.

**Comment by Sims24** [comment]
Hi, 

If you're still interested in this one, and available to test our development, we could add this to the backlog. 

We will use the Graph API as suggested by @UrBnW . 

Can you confirm you're still interested in getting such monitoring probe?

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4090
