### ISSUE TITLE
[apps::varnish::local::plugin]: monitor memory and file cache

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3047]
With ticket https://github.com/centreon/centreon-plugins/issues/1912 you have added the possibility to monitor the SMA.s0.g_space value and it works. But if someone is customizing this parameter then the name will changed.

Please change the monitoring of this parameter from
SMA.s0.g_space -> SMA.*.g_space (memory allocation)

Please add also a new parameter to monitor file/disk cache with same approad:
SMF.*.g_space (file allocation)

Example varnish output:
```
varnishstat -1 | grep g_space
SMA.default.g_space                  2616286161          .   Bytes available
SMF.static.g_space                   4781056000          .   Bytes available
SMA.Transient.g_space                         0          .   Bytes available
```

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
