### ISSUE TITLE
centreon_plugins.pl - UNKNOWN: SNMP GET Request : Timeout - Error in packet. Reason: (genError) A general failure occured Failed object: SNMPv2-SMI::enterprises.77.1.1.3.0

### ISSUE THREAD

**Issue by Alkorne** [centreon/centreon-plugins#3056]
Hello,

I encounter an issue with centreon_plugins (Centreon Engine 21.04.1) using the following command on a distant Windows Server 2019 (10.0.17763) :

**/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --mode processcount --hostname xxx.xxx.xxx.xxx --snmp-version 2c --snmp-community public --process-name 'process.exe' --critical 1:**

I get the following result : 

**UNKNOWN: SNMP GET Request : Timeout**

The expected result should be :

**OK: Number of current processes running: 1 | 'nbproc'=1;;1:;0;**
or
**CRITICAL: Number of current processes running: 0 | 'nbproc'=0;;1:;0;**

When I use the following command :

**snmpwalk -v 2c -c public xxx.xxx.xxx.xxx .1.3.6.1**

I get the following result :

**Error in packet.
Reason: (genError) A general failure occured
Failed object: SNMPv2-SMI::enterprises.77.1.1.3.0**

I do not encounter these issues/errors on other servers.

I also try the following commands (with the PID 4076 in this example) :

**snmpwalk -v 2c -c public xxx.xxx.xxx.xxx .1.3.6.1.2.1.25.4.2.1.2.4076**
or
**snmpget -v 2c -c public xxx.xxx.xxx.xxx .1.3.6.1.2.1.25.4.2.1.2.4076**

And I get the following result wich is the expected one :

**HOST-RESOURCES-MIB::hrSWRunName.4076 = STRING: "svchost.exe"**

Is the issue known, fixed ? Or can we get help with this issue ? Any help would be appreciated.

**Comment by garnier-quentin** [comment]
You can try following option ```--snmp-force-getnext``` option for that server.

**Comment by Alkorne** [comment]
> You can try following option `--snmp-force-getnext` option for that server.

Thanks for your help. Unfortunately, I just tried this, with no success...

**Comment by garnier-quentin** [comment]
Please try following options: ```--snmp-force-getnext --subsettable=0 --subsetleef=1```

**Comment by Alkorne** [comment]
Many thanks for your help, last mentionned options worked for me !
