### ISSUE TITLE
network::dell::os10::snmp::plugin mode hardware failed

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3057]
Hello,

I can use this command : 

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin= network::dell::os10::snmp::plugin --mode hardware --hostname xx.xx.xx.xx --snmp-community snmp`

I have this error  : 

`CRITICAL: fan '1' status is 'failed' - fan '2' status is 'failed' - power supply '1' status is 'failed'`

It's a new switch and we have 2
We have the problem on the 2.

Thank you

**Comment by garnier-quentin** [comment]
could you provide the snmpwalk of following branch: .1.3.6.1.4.1.674.11000 ?

**Comment by prohand** [comment]
Hello,

I can send this in e-mail.

Thank you

**Comment by garnier-quentin** [comment]
The plugin seems ok. You should ask to your hardware support.

Fan OIDs:
```
SNMPv2-SMI::enterprises.674.11000.5000.100.4.1.2.3.1.7.1 = INTEGER: 8
SNMPv2-SMI::enterprises.674.11000.5000.100.4.1.2.3.1.7.2 = INTEGER: 8
```

And the mapping:
```
1 => 'up', 2 => 'down',
3 => 'testing', 4 => 'unknown', 
5 => 'dormant', 6 => 'notPresent',
7 => 'lowerLayerDown', 8 => 'failed'
```

And for power supplies:
```
SNMPv2-SMI::enterprises.674.11000.5000.100.4.1.2.1.1.4.1 = INTEGER: 8
SNMPv2-SMI::enterprises.674.11000.5000.100.4.1.2.1.1.4.2 = INTEGER: 1
```

**Comment by prohand** [comment]
Oo :( OK : 
![image](https://user-images.githubusercontent.com/20227162/131477383-e43cadd0-37a7-4bce-9ff0-4ba2d3261003.png)
Sorry :(

**Comment by prohand** [comment]
The problem with PSU is OK.
No alarm reported by show alarms in switch and the plugin return fan2 is failed : 

![image](https://user-images.githubusercontent.com/20227162/131485520-fb11cdab-046f-4322-96fe-432efefc5f18.png)

**Comment by garnier-quentin** [comment]
I don't know why there is still a fan failed. Maybe you need to contact the dell support

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk ?

**Comment by prohand** [comment]
I send this by email.
Thank you
