### ISSUE TITLE
[cloud::microsoft::office365::exchange::mode::emailactivity] Month '-1' out of range 0..11 at

### ISSUE THREAD

**Issue by ermurenz** [centreon/centreon-plugins#3059]
Hi.
I don't know if this is the right place to present a problem like this. If not, I apologize in advance
i've a problem with "emailactivity" mode (cloud::microsoft::office365::exchange) .
I've been using it for a few months and have never had any problems, it has always worked from the start.
Since yesterday, however, this error has appeared and the check basically fails:

#/usr/lib/centreon/plugins/centreon_plugins.pl --plugin cloud::microsoft::office365::exchange::plugin --mode=email-activity --tenant='xxxx' --client-id='xxxx' --client-secret='xxxxx'

Use of uninitialized value $2 in subtraction (-) at /usr/lib/centreon/plugins/cloud/microsoft/office365/exchange/mode/emailactivity.pm line 39.
Use of uninitialized value $1 in subtraction (-) at /usr/lib/centreon/plugins/cloud/microsoft/office365/exchange/mode/emailactivity.pm line 39.
UNKNOWN: Month '-1' out of range 0..11 at /usr/lib/centreon/plugins/cloud/microsoft/office365/exchange/mode/emailactivity.pm line 39.

I have not touched anything.
I tried to update, but nothing.
Any help is appreciated

**Comment by garnier-quentin** [comment]
Could you provide the output with --debug ? you can sent it by email if you prefer

**Comment by fixlair** [comment]
Hello !
we do have the same problem here. M365 should have updated something on their side ?

**Comment by garnier-quentin** [comment]
Maybe. but i need the debug output.

**Comment by ermurenz** [comment]
> Could you provide the output with --debug ? you can sent it by email if you prefer

I had tried --debug to try to get more information but the output is exactly the same, unfortunately.

**Comment by fixlair** [comment]
Here is an output with --debug on centreon_plugins.pl --plugin=cloud::microsoft::office365::onedrive::plugin --mode=site-usage --custommode='graphapi'

```
Use of uninitialized value $2 in subtraction (-) at /var/lib/centreon/plugins/cloud/microsoft/office365/onedrive/mode/siteusage.pm line 39.
Use of uninitialized value $1 in subtraction (-) at /var/lib/centreon/plugins/cloud/microsoft/office365/onedrive/mode/siteusage.pm line 39.
UNKNOWN: Month '-1' out of range 0..11 at /var/lib/centreon/plugins/cloud/microsoft/office365/onedrive/mode/siteusage.pm line 39.
```


On centreon_plugins.pl --plugin=cloud::microsoft::office365::sharepoint::plugin --mode=users-activity --custommode='graphapi' 


```
Use of uninitialized value $2 in subtraction (-) at /var/lib/centreon/plugins/cloud/microsoft/office365/sharepoint/mode/usersactivity.pm line 39.
Use of uninitialized value $1 in subtraction (-) at /var/lib/centreon/plugins/cloud/microsoft/office365/sharepoint/mode/usersactivity.pm line 39.
UNKNOWN: Month '-1' out of range 0..11 at /var/lib/centreon/plugins/cloud/microsoft/office365/sharepoint/mode/usersactivity.pm line 39.
```

**Comment by garnier-quentin** [comment]
The --debug should display informations. Could you test with --http-backend=curl ?

**Comment by prohand** [comment]
Same problem : #3062

**Comment by prohand** [comment]
The debug show no more information
Same problem with --http-backend=curl

**Comment by garnier-quentin** [comment]
Could you add following line in file: centreon/plugins/backend/http/curl.pm
```
    print $msg . "\n";
    $uservar->{output}->output_add(long_msg => $msg, debug => 1);
    return 0;
```

**Comment by prohand** [comment]
At the end of file ?

**Comment by garnier-quentin** [comment]
Over the following line line:
```
$uservar->{output}->output_add(long_msg => $msg, debug => 1);
```

**Comment by prohand** [comment]
I have send the debug to you're email.

**Comment by ermurenz** [comment]
in the curl.pm i have:

**$uservar->{output}->output_add(long_msg => $msg, debug => 1);
return 0;**

in line 142-143.
I inserted above:

**print $msg . "\n";**

Then i've launch the command with (and without):   --http-backend='curl'

Nothing different for me.Same exactly output.

**Comment by ermurenz** [comment]
Hi guys, 
I don't know why, all checks with problems are back to normal.I didn't touch or modified anything, of course.
Same for you @prohand ?

For the record, the problem occurs from 30 august 10PM to  01 September 6PM

**Comment by garnier-quentin** [comment]
I have checked why. In fact, microsoft graphapi results was empty (no datas) (I don't know why). Maybe it can take more than 7 ays (the default period we check). 

And the plugin doesn't manage well with no data from the API. I should manage that case.

**Comment by prohand** [comment]
Solved by Microsoft : 
![image](https://user-images.githubusercontent.com/20227162/131850424-4338be11-318c-4f7a-8551-205d4f690c09.png)

**Comment by ermurenz** [comment]
> Solved by Microsoft :
> ![image](https://user-images.githubusercontent.com/20227162/131850455-b20dda84-3d96-4620-9db2-7937d55dd5d3.png)

Thank you @prohand 
can i ask you where i can find these service alerts?
thanks again.

**Comment by ermurenz** [comment]
ok, got it:
portal.office.com -> center messages
right?
