### ISSUE TITLE
[plugin] [ipsla] Threshold

### ISSUE THREAD

**Issue by tcheval** [centreon/centreon-plugins#306]
Hi,

On ipsla plugin is not possible to set a threshold on completion_time.

We have tried to set threshold on router with command : 

ip sla monitor reaction-configuration 10 react rtt threshold-type immediate threshold-value 5 3 action-type trapAndTrigger

This command send a trap, but not set threshold in snmp mib :(

Is it possible to add --warning-completion_time and --critical-completion_time ?

Thanks.

**Comment by garnier-quentin** [comment]
How do i calculate completion time ?

**Comment by tcheval** [comment]
it's the RTT value.

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=ipsla --hostname=sirwanworld --snmp-version=2c --snmp-community=njh_iafl --filter-tag=Londres_OY 
OK: RTT 'Londres_OY' Status : operation sense is 'ok', Number Over Thresholds : 0, Average Delay SD : 1.28 ms, Average Delay DS : 6.53 ms, Packet Loss Ratio : 0.00 %, Percentage of Packets that had Positive Jitter : 0.18, Average Jitter per Packet that had Positive Jitter : 0.18, Percentage of Packets that had Negative Jitter : 0.19, Average Jitter per Packet that had Negative Jitter : 0.19, Average Jitter : 1.00 ms, Round-Trip Time Standard Deviation : 0.41 ms, One-Way Delay Source to Destination Standard Deviation : 0.51 ms, One-Way Delay Destination to Source Standard Deviation : 0.50 ms, One-Way Jitter Source to Destination Standard Deviation : 0.00 ms, One-Way Jitter Destination to Source Standard Deviation : 0.00 ms | 'completion_time'=7ms;;;0; 'number_over_thresholds'=0;;;; 'average_delay_sd'=1.28ms;;;; 'average_delay_ds'=6.53ms;;;; 'packet_loss_ratio'=0.00%;;;0;100 'prct_jitter_per_packet_positive_jitter'=0.18;;;; 'average_jitter_per_packet_positive_jitter'=0.18;;;; 'prct_jitter_per_packet_negative_jitter'=0.19;;;; 'average_jitter_per_packet_negative_jitter'=0.19;;;; 'average_jitter'=1.00ms;;;; 'rtt_standard_deviation'=0.41ms;;;; 'delay_src2dest_stdev'=0.51ms;;;; 'delay_dest2src_stdev'=0.50ms;;;; 'jitter_src2dest_stdev'=0.00ms;;;; 'jitter_dest2src_stdev'=0.00ms;;;;

 'completion_time'=7ms;;;0; 

To detect hight latency on telecom line with ipsla plugin, should be able to put a warning and critical value.

**Comment by garnier-quentin** [comment]
Yes. I need to update it.

**Comment by garnier-quentin** [comment]
Could you test it please ?

**Comment by tcheval** [comment]
Not working :(

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=ipsla --hostname=rtrname --snmp-version=2c --snmp-community=com --filter-tag=tagname
UNKNOWN: Can't call method "map_instance" on an undefined value at /usr/local/plugins/libexec/centreon/common/cisco/standard/snmp/mode/ipsla.pm line 854. 

./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=ipsla --hostname=rtrname --snmp-version=2c --snmp-community=com --filter-tag=tagname --warning-CompletionTime=1 --critical-CompletionTime=2
UNKNOWN: Can't call method "map_instance" on an undefined value at /usr/local/plugins/libexec/centreon/common/cisco/standard/snmp/mode/ipsla.pm line 854.

**Comment by garnier-quentin** [comment]
Could you retest it please ?

**Comment by tcheval** [comment]
./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=ipsla --hostname=rtrname--snmp-version=2c --snmp-community=com--filter-tag=tag
Use of uninitialized value in concatenation (.) or string at /usr/local/plugins/libexec/centreon/plugins/statefile.pm line 97.
Use of uninitialized value in concatenation (.) or string at /usr/local/plugins/libexec/centreon/plugins/statefile.pm line 116.
Use of uninitialized value in -w at /usr/local/plugins/libexec/centreon/plugins/statefile.pm line 117.
Use of uninitialized value in concatenation (.) or string at /usr/local/plugins/libexec/centreon/plugins/statefile.pm line 119.
UNKNOWN: Cannot write statefile '/cache_cisco_sirwanworld_161_ipsla_3f7a58540a74cc52511017f163408425_a181a603769c1f98ad927e7367c7aa51'. Need write permissions on directory.
