### ISSUE TITLE
[snmp_standard::mode::uptime] - add SNMP sysDescr on output

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3060]
Could you add a option that will add the sysDescr on uptime output like:
actual: `OK: uptime: 1w 3d 21:19h, boot: 2021-08-20 08:57:59 (UTC)`
proposal: `OK: uptime: 1w 3d 21:19h, boot: 2021-08-20 08:57:59 (UTC), Palo Alto Networks PA-220 series firewall`

**Comment by garnier-quentin** [comment]
In last version, you can use option: ```--add-sysdesc```
