### ISSUE TITLE
[network::fortinet::fortimanager::snmp::plugin::device-status] unknown status for fortianalizer

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3066]
Hi,

I have a fortianalyzer that gives me 'unknown' values ​​not consistent with the graphical interface : 
Device 'xxxxxxxx' Status : unknown, Connection Status : unknown, DB Status : unknown, Configuration Status : unknown
Device 'xxxxxxxx' Status : unknown, Connection Status : unknown, DB Status : modified, Configuration Status : unknown
Device 'xxxxxxxx' Status : unknown, Connection Status : unknown, DB Status : unknown, Configuration Status : unknown
Device 'xxxxxxxx' Status : unknown, Connection Status : unknown, DB Status : modified, Configuration Status : unknown
Device 'xxxxxxxx' Status : unknown, Connection Status : unknown, DB Status : unknown, Configuration Status : unknown
Device 'xxxxxxxx' Status : unknown, Connection Status : unknown, DB Status : modified, Configuration Status : unknown
Device 'xxxxxxxx' Status : unknown, Connection Status : unknown, DB Status : unknown, Configuration Status : unknown

![image](https://user-images.githubusercontent.com/61595839/131540787-f35c916e-9af8-4c83-b0c3-5f1b0c57a1d2.png)

**Comment by gagzou** [comment]
snmpwalk:
.1.3.6.1.4.1.12356.103.6.2.1.13
SNMPv2-SMI::enterprises.12356.103.6.2.1.13.1 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.13.2 = INTEGER: 2
SNMPv2-SMI::enterprises.12356.103.6.2.1.13.3 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.13.4 = INTEGER: 2
SNMPv2-SMI::enterprises.12356.103.6.2.1.13.5 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.13.6 = INTEGER: 2
SNMPv2-SMI::enterprises.12356.103.6.2.1.13.7 = INTEGER: 0

.1.3.6.1.4.1.12356.103.6.2.1.14
SNMPv2-SMI::enterprises.12356.103.6.2.1.14.1 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.14.2 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.14.3 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.14.4 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.14.5 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.14.6 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.103.6.2.1.14.7 = INTEGER: 0

.1.3.6.1.4.1.12356.103.6.2.1.15
SNMPv2-SMI::enterprises.12356.103.6.2.1.15.1 = INTEGER: 1
SNMPv2-SMI::enterprises.12356.103.6.2.1.15.2 = INTEGER: 1
SNMPv2-SMI::enterprises.12356.103.6.2.1.15.3 = INTEGER: 1
SNMPv2-SMI::enterprises.12356.103.6.2.1.15.4 = INTEGER: 1
SNMPv2-SMI::enterprises.12356.103.6.2.1.15.5 = INTEGER: 1
SNMPv2-SMI::enterprises.12356.103.6.2.1.15.6 = INTEGER: 1
SNMPv2-SMI::enterprises.12356.103.6.2.1.15.7 = INTEGER: 1

**Comment by gagzou** [comment]
[FORTINET-FORTIMANAGER-FORTIANALYZER-MIB-build2201.mib.zip](https://github.com/centreon/centreon-plugins/files/7085449/FORTINET-FORTIMANAGER-FORTIANALYZER-MIB-build2201.mib.zip)

**Comment by gagzou** [comment]
[FORTINET-CORE-MIB-build1778.mib.zip](https://github.com/centreon/centreon-plugins/files/7085450/FORTINET-CORE-MIB-build1778.mib.zip)

**Comment by gagzou** [comment]
Full snmpwalk sent by email.

**Comment by garnier-quentin** [comment]
For following OIDs the mapping: .1.3.6.1.4.1.12356.103.6.2.1.15 (1 = unknown)
```
0 => 'none', 1 => 'unknown', 2 => 'checked-in', 3 => 'in-progress',
    4 => 'installed', 5 => 'aborted', 6 => 'sched', 7 => 'retry', 8 => 'canceled',
    9 => 'pending', 10 => 'retrieved', 11 => 'changed-conf', 12 => 'sync-fail',
    13 => 'timeout', 14 => 'rev-reverted', 15 => 'auto-updated'
```

Sorry but it's the same for other OIDs. Could you ask to your support ?

**Comment by gagzou** [comment]
Hi,
I opened a ticket at Fortinet.
Regards.

**Comment by gagzou** [comment]
Fortinet response : 

"It is working as normal. SNMP query is returning the same status shown against "conn" in "diag dvm device list". That field is usually showing "unknown" eventhough receiving **realtime** logs, presumably because there is no FGFM tunnel. Only an OFTP tunnel.

FAZVM64-HV # FAZVM64-HV # diag dvm device list

--- There are currently 4 devices/vdoms managed ---

TYPE OID SN HA IP NAME ADOM IPS FIRMWARE

faz enabled 131 FGT60D4Q16026549 - 172.17.96.167 FGT60D4Q16026549 root N/A 5.0 MR0 (131)

|- STATUS: dev-db: unknown; conf: unknown; cond: unknown; dm: none; 
|conn: unknown

|- vdom:[3]root flags:0 adom:root pkg:[never-installed]

As mentioned, its working as designed and we may not able to do much on this. In this case it would be considered a new feature request (NFR) which can be worked through your FortiNet SE channel."

**Comment by gagzou** [comment]
At present, it is not possible to monitor the status if the logs are in 'real time'

**Comment by gagzou** [comment]
I open NFR at Fortinet.
