### ISSUE TITLE
Office 365 plugin error 500 Can't connect to graph.microsoft.com:443 

### ISSUE THREAD

**Issue by jbeaujour** [centreon/centreon-plugins#3068]
Hello
we are trying to execute centreon_plugins.pl --plugin cloud::microsoft::office365::xxxx::plugin and we encounter a message with all mode.
Only cloud::microsoft::office365::management::plugin --mode service-status give us a good response

The command line:
./centreon_plugins.pl --plugin cloud::microsoft::office365::exchange::plugin  --mode email-activity --custommode='graphapi'  --tenant='xxxxxxxxxxxxxxx' --client-id='yyyyyyyyyyyyyyyyyyyyyyy' --client-secret='zzzzzzzzzzzzzzzzz' --debug

The response:
UNKNOWN: Cannot decode json response: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Can't connect to gra...") at /usr/lib/centreon/plugins/cloud/microsoft/office365/custom/graphapi.pm line 228.
URL: 'https://graph.microsoft.com/v1.0/reports/getEmailActivityUserDetail(period='D7')'
======> request send
GET https://graph.microsoft.com/v1.0/reports/getEmailActivityUserDetail(period='D7')
Accept: application/json
Authorization: Bearer eyJ
.................dsdRw
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded
======> response done
500 Can't connect to graph.microsoft.com:443
Content-Type: text/plain
Client-Date: Wed, 01 Sep 2021 13:09:11 GMT
Client-Warning: Internal response

Can't connect to graph.microsoft.com:443

Can't connect to graph.microsoft.com:443

Thank's for help

**Comment by garnier-quentin** [comment]
Could you try the option ```--insecure --http-backend=curl``` ?

**Comment by jbeaujour** [comment]
I have this message : UNKNOWN: Cannot load module 'Net::Curl::Easy'
I am on debian wheezy and i don't find the package

**Comment by garnier-quentin** [comment]
Ok. So only use ```--insecure```

**Comment by jbeaujour** [comment]
It works, thank's

**Comment by garnier-quentin** [comment]
Thanks for the feedback
