### ISSUE TITLE
hardware::server::hp::ilo::xmlapi::plugin - mode hardware not parsing answer on old ilo4

### ISSUE THREAD

**Issue by Maekess** [centreon/centreon-plugins#3069]
Hello,

I'm experiencing an issue with hardware::server::hp::ilo::xmlapi::plugin plugin in hardware mode.
iLO4 - Firmware Version 1.10 (very old - Jul 17 2012)

/usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --hostname=192.168.1.100 --mode=hardware --threshold-overload='nic,OK,link down' --threshold-overload='psu,OK,UNKNOWN'  --username 'supervision' --password '***'
UNKNOWN: Cannot decode xml response:
no element found at line 462, column 0, byte 17952 at /usr/lib64/perl5/vendor_perl/XML/Parser.pm line 187.
XML::Simple called at /usr/lib/centreon/centreon-plugins/hardware/server/hp/ilo/xmlapi/custom/api.pm line 277.

Here is the return with --debug
[debug.txt](https://github.com/centreon/centreon-plugins/files/7091379/debug.txt)

Thx if you can fix for old Firmware.

**Comment by garnier-quentin** [comment]
There is a timeout:
```
X-Died: read timeout at /root/perl5/lib/perl5/Net/HTTP/Methods.pm line 266.
```

Maybe you can try to increase the timeout: ```--timeout=55```

**Comment by Maekess** [comment]
Perfect, --timeout does the trick, aint seen that message.
Thanks.

**Comment by garnier-quentin** [comment]
thanks for the feeback
