### ISSUE TITLE
[apps::microsoft::sccm::local::plugin] mode site-status

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#3076]
Hello,

After last update of SCCM in version 2103, this mode is broken.
I've installed the last centreon_plugins.exe 20210902 from today and i have this response now :

Use of uninitialized value in numeric eq (==) at (eval 36) line 1.
Use of uninitialized value in numeric eq (==) at (eval 36) line 1.
UNKNOWN: Command error: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'. -    at Microsoft.ConfigurationManagement.PowerShell.Provider.CMDriveProvider.Start(ProviderInfo providerInfo) -    at System.Management.Automation.SessionStateInternal.NewProvider(ProviderInfo provider)

I don't know if it's the same cause for this issue : https://github.com/centreon/centreon-plugins/issues/2906
But it's not the same output messages.

Thanks

**Comment by garnier-quentin** [comment]
Could you execute the powershell directly ? You can get with --ps-display

**Comment by ritouret** [comment]
With this option, i have this output :
Use of uninitialized value in numeric eq (==) at (eval 36) line 1.
Use of uninitialized value in numeric eq (==) at (eval 36) line 1.

$culture = new-object "System.Globalization.CultureInfo" "en-us"
[System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture

function Escape-JSONString($str) {
    if ($str -eq $null) {return ""}
    $str = $str.ToString().Replace('\','\\').Replace('"','\"').Replace("`n",'\n').Replace("`r",'\r').Replace("`t",'\t')
    return $str;
}

function ConvertTo-JSON-20($maxDepth = 4,$forceArray = $false) {
    begin {
        $data = @()
    }
    process{
        $data += $_
    }

    end{
        if ($data.length -eq 1 -and $forceArray -eq $false) {
            $value = $data[0]
        } else {
            $value = $data
        }

        if ($value -eq $null) {
            return "null"
        }

        $dataType = $value.GetType().Name

        switch -regex ($dataType) {
                'String'  {
                    return  "`"{0}`"" -f (Escape-JSONString $value )
                }
                '(System\.)?DateTime'  {return  "`"{0:yyyy-MM-dd}T{0:HH:mm:ss}`"" -f $value}
                'Int16|Int32|Double' {return  "$value"}
                'Boolean' {return  "$value".ToLower()}
                '(System\.)?Object\[\]' { # array

                    if ($maxDepth -le 0){return "`"$value`""}

                    $jsonResult = ''
                    foreach($elem in $value){
                        #if ($elem -eq $null) {continue}
                        if ($jsonResult.Length -gt 0) {$jsonResult +=','}
                        $jsonResult += ($elem | ConvertTo-JSON-20 -maxDepth ($maxDepth -1))
                    }
                    return "[" + $jsonResult + "]"
                }
                '(System\.)?Hashtable' { # hashtable
                    $jsonResult = ''
                    foreach($key in $value.Keys){
                        if ($jsonResult.Length -gt 0) {$jsonResult +=','}
                        $jsonResult +=
@"
"{0}":{1}
"@ -f $key , ($value[$key] | ConvertTo-JSON-20 -maxDepth ($maxDepth -1) )
                    }
                    return "{" + $jsonResult + "}"
                }
                default { #object
                    if ($maxDepth -le 0){return  "`"{0}`"" -f (Escape-JSONString $value)}

                    return "{" +
                        (($value | Get-Member -MemberType *property | % {
@"
"{0}":{1}
"@ -f $_.Name , ($value.($_.Name) | ConvertTo-JSON-20 -maxDepth ($maxDepth -1) )

                    }) -join ',') + "}"
                }
        }
    }
}

$ProgressPreference = "SilentlyContinue"

Try {
    $ErrorActionPreference = "Stop"

    $modulePath = ${env:SMS_ADMIN_UI_PATH}
    $modulePath = $modulePath.Substring(0, $modulePath.lastIndexOf("\"))
    $module = $modulePath + "\ConfigurationManager.psd1"
    Import-Module $module

    $returnArray = @()

    $providers = Get-PSProvider | Where {$_.Name -match "CMSite" }
    foreach ($provider in $providers) {
        New-PSDrive -Name SCCMDrive -PSProvider $provider.Name -Root $env:COMPUTERNAME -Description "SCCM Site" | Out-Null
        CD "SCCMDrive:\"
        $CMObject = Get-CMSite
        CD "C:\"
        Remove-PSDrive -Name SCCMDrive

        Foreach ($site in $CMObject) {
            $returnObject = New-Object -TypeName PSObject
            Add-Member -InputObject $returnObject -MemberType NoteProperty -Name "providerName" -Value $provider.Name
            Add-Member -InputObject $returnObject -MemberType NoteProperty -Name "SiteCode" -Value $site.SiteCode
            Add-Member -InputObject $returnObject -MemberType NoteProperty -Name "SiteName" -Value $site.SiteName
            Add-Member -InputObject $returnObject -MemberType NoteProperty -Name "Type" -Value $site.Type
            Add-Member -InputObject $returnObject -MemberType NoteProperty -Name "Mode" -Value $site.Mode
            Add-Member -InputObject $returnObject -MemberType NoteProperty -Name "Status" -Value $site.Status
            Add-Member -InputObject $returnObject -MemberType NoteProperty -Name "SecondarySiteCMUpdateStatus" -Value $site.SecondarySiteCMUpdateStatus
            $returnArray += $returnObject
        }
    }

    $returnArray | ConvertTo-JSON-20 -forceArray $true
} Catch {
    Write-Host $Error[0].Exception
    exit 1
}

exit 0

**Comment by ritouret** [comment]
yes, there is the result :

System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Microsoft.ConfigurationManagement.PowerShell.Provider.CMDriveProvider.Start(ProviderInfo providerInfo)
   at System.Management.Automation.SessionStateInternal.NewProvider(ProviderInfo provider)

**Comment by garnier-quentin** [comment]
Could you try to execute following powershell code:
```
$modulePath = ${env:SMS_ADMIN_UI_PATH}
$modulePath = $modulePath.Substring(0, $modulePath.lastIndexOf("\"))
$module = $modulePath + "\ConfigurationManager.psd1"
Import-Module $module
$providers = Get-PSProvider | Where {$_.Name -match "CMSite" }
```

**Comment by ritouret** [comment]
PS C:\Windows\system32> $modulePath = ${env:SMS_ADMIN_UI_PATH}
$modulePath = $modulePath.Substring(0, $modulePath.lastIndexOf("\"))
$module = $modulePath + "\ConfigurationManager.psd1"
Import-Module $module
$providers = Get-PSProvider | Where {$_.Name -match "CMSite" }

**Comment by garnier-quentin** [comment]
could you provide the result of:
```
Get-PsProvider
```

**Comment by ritouret** [comment]
PS C:\Windows\system32> Get-PsProvider

Name                 Capabilities                                                                     Drives                                                                         
----                 ------------                                                                     ------                                                                         
Alias                ShouldProcess                                                                    {Alias}                                                                        
Environment          ShouldProcess                                                                    {Env}                                                                          
FileSystem           Filter, ShouldProcess, Credentials                                               {C, D, E, F...}                                                                
Function             ShouldProcess                                                                    {Function}                                                                     
Registry             ShouldProcess, Transactions                                                      {HKLM, HKCU}                                                                   
Variable             ShouldProcess                                                                    {Variable}

**Comment by garnier-quentin** [comment]
There is no CMSite provider... Is it working for you:
```
New-PSDrive -Name SCCMDrive -PSProvider "CMSite" -Root $env:COMPUTERNAME -Description "SCCM Site"
```

**Comment by garnier-quentin** [comment]
Following is working ?
```
New-PSDrive -Name SCCMDrive -PSProvider "AdminUI.PS.Provider\CMSite" -Root $env:COMPUTERNAME -Description "SCCM Site"
```
So i need to set that value if it's empty.

**Comment by ritouret** [comment]
Sorry Quentin, another error :

PS C:\Windows\system32> New-PSDrive -Name SCCMDrive -PSProvider "AdminUI.PS.Provider\CMSite" -Root $env:COMPUTERNAME -Description "SCCM Site"

New-PSDrive : Cannot find a provider with the name 'AdminUI.PS.Provider\CMSite'.
At line:1 char:1
+ New-PSDrive -Name SCCMDrive -PSProvider "AdminUI.PS.Provider\CMSite" -Root $env: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AdminUI.PS.Provider\CMSite:String) [New-PSDrive], ProviderNotFoundException
    + FullyQualifiedErrorId : ProviderNotFound,Microsoft.PowerShell.Commands.NewPSDriveCommand

**Comment by garnier-quentin** [comment]
It was working before ?

**Comment by ritouret** [comment]
The mode yes, it was working before the upgrade yesterday

**Comment by ritouret** [comment]
I asked to our expert who made the upgrade to ask to Microsoft what happened to this Provider.
I'll let you know.
Thank you.

**Comment by garnier-quentin** [comment]
It was that line before the patch:
```
New-PSDrive -Name SCCMDrive -PSProvider "AdminUI.PS.Provider\CMSite" -Root $env:COMPUTERNAME -Description "SCCM Site"
```

**Comment by ritouret** [comment]
Same Error :

PS C:\Windows\system32> New-PSDrive -Name SCCMDrive -PSProvider "AdminUI.PS.Provider\CMSite" -Root $env:COMPUTERNAME -Description "SCCM Site"
New-PSDrive : Cannot find a provider with the name 'AdminUI.PS.Provider\CMSite'.
At line:1 char:1
+ New-PSDrive -Name SCCMDrive -PSProvider "AdminUI.PS.Provider\CMSite" -Root $env: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AdminUI.PS.Provider\CMSite:String) [New-PSDrive], ProviderNotFoundException
    + FullyQualifiedErrorId : ProviderNotFound,Microsoft.PowerShell.Commands.NewPSDriveCommand

**Comment by garnier-quentin** [comment]
I used a default provider if we don't find with Get-PSProvider. You can test:
```
$modulePath = ${env:SMS_ADMIN_UI_PATH}
$modulePath = $modulePath.Substring(0, $modulePath.lastIndexOf("\"))
$module = $modulePath + "\ConfigurationManager.psd1"
Import-Module $module

$providers = Get-PSProvider | Where {$_.Name -match "CMSite" }
if ($null -eq $providers -or $providers.Count -eq 0) {
        $providers = New-Object System.Collections.Generic.List[Hashtable];
        $item = @{}
        $item.Name = "AdminUI.PS.Provider\CMSite"
        $items.Add($item)
}


```

**Comment by ritouret** [comment]
Hello Quentin,

I've just tested and here is the result :
Import-Module : Method not found: '!!0[] System.Array.Empty()'.
At line:4 char:1
+ Import-Module $module
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], MissingMethodException
    + FullyQualifiedErrorId : ProviderStartException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
You cannot call a method on a null-valued expression.
At line:11 char:9
+         $items.Add($item)
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by garnier-quentin** [comment]
Please test with last version:
https://github.com/centreon/centreon-nsclient-build/releases/tag/20210910075442

**Comment by ritouret** [comment]
That's what i've done.

In the meantime, our expert has installed the Microsoft .NET 4.7.2 which is a required by SCCM 2103 for the ConfigurationManager PowerShell module : that was the problem.

It works fine except this new error :
https://github.com/centreon/centreon-plugins/issues/3150
