### ISSUE TITLE
Null pointer exception in snmp_standard::mode::interfaces

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#3078]
## Bug/Question

There is a small problem with the --list-interfaces in snmp plugin. If the status of the interface is empty or unknown (this is certainly a very rare exception and probably a problem with the firmware of the device) then you get a "use of uninitialized value" error message.

Without --disco-show and --filter-status=up

Use of uninitialized value in pattern match (m//) at /tmp/network-paloalto-snmp.pl line 9820.

With --disco-show

Use of uninitialized value in pattern match (m//) at /tmp/network-paloalto-snmp.pl line 10015.

Without --filter-status

Use of uninitialized value in sprintf at /tmp/network-paloalto-snmp.pl line 9844.

![image](https://user-images.githubusercontent.com/46994680/132198490-1888c365-119c-42ca-9e55-50a024dd8237.png)

Regards

**Comment by garnier-quentin** [comment]
Please update your plugin. It was patched already.
