### ISSUE TITLE
[network::cisco::standard::snmp::plugin]] --mode=load - wrong units

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3081]
Plugins 20210520

referring to this cisco documentation (https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/118901-technote-snmp-00.pdf) the CPU load from Cisco devices will be returned on snmp with a factor 100.

Example:
Load 0,75 -> 75

Maybe it should be a proposal to divide the load by 100 to be able to set better thresholds?

**Comment by garnier-quentin** [comment]
For the load, i use:
- cpmCPULoadAvg1min
- cpmCPULoadAvg5min: The overall CPU load Average in the last 5 minutes period (unit: hundredths of processes)
- cpmCPULoadAvg15min

And for the CPU, i use:
- cpmCPUTotal5minRev: The overall CPU busy percentage in the last 5 minute period. This object deprecates the object cpmCPUTotal5min and increases the value range to (0..100) (unit: percent)
- cpmCPUTotal1minRev
- cpmCPUTotal5secRev

If you tell me the load is a cpu percentage,  i don't understand why it's different (it should be the same):
- cpmCPUTotal5minRev (.1.3.6.1.4.1.9.9.109.1.1.1.1.8.7) = Gauge32: 11 (so 11%)
-  cpmCPULoadAvg5min (.1.3.6.1.4.1.9.9.109.1.1.1.1.25.7) = Gauge32: 22 (so xx% ?)

**Comment by garnier-quentin** [comment]
For the load reflect the average number of runnable processes with units of hundredths of processes. Maybe i should divide by 100.

**Comment by garnier-quentin** [comment]
I'm stupid it's why you tell me :)

**Comment by joschi99** [comment]
done a quick test, seems working. Thanks
