### ISSUE TITLE
HP Proliant plugin - "is other"

### ISSUE THREAD

**Issue by kevkev-73** [centreon/centreon-plugins#3082]
Hi!
I want to supervised my hp proliant server.
I installed the HP Proliant plugin and configured my HP server.
I encounter an error with Hardware-Network.

`UNKNOWN: physical nic '3' is other
Product Name: ProLiant DL360 Gen10, Serial: XXXXXX Rom Version: XXXXXXXX
Checking physical nics
Checking physical nics
physical nic '1' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
physical nic '2' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
physical nic '3' [duplex: unknown, role: notApplicable, state: unknown, status: unknown] condition is other.
physical nic '4' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
Checking logical nics
logical nic '1' [adapter count: 1, description: Logical Interface for vmnic0, status: ok] condition is ok.
logical nic '2' [adapter count: 1, description: Logical Interface for vmnic1, status: ok] condition is ok.
logical nic '3' [adapter count: 1, description: Logical Interface for vmnic2, status: unknown] condition is other.
logical nic '4' [adapter count: 1, description: Logical Interface for vmnic3, status: ok] condition is ok.`

I already tried the option "--threshold-overload = 'daacc, OK, other'" but but it doesn't work.
The status is unknown.

Thank you for your help ;)

**Comment by garnier-quentin** [comment]
You can also add options: ``` --threshold-overload='pnic,OK,other' --threshold-overload='lnic,OK,other' ```

**Comment by kevkev-73** [comment]
It work ! Thank you ! 

But, how did you find the value "pnic" ? 
I also have the problem with : 

-Hardware-Storage

`UNKNOWN: da controller accelerator '0' is other - da controller accelerator '2' is other`

-Hardware-Psu

`UNKNOWN: powersupply '0.2' status is other`

-Hardware-Global

`UNKNOWN: powersupply '0.2' status is other - physical nic '3' is other`

**Comment by garnier-quentin** [comment]
```
'cpu', 'idectl', 'ideldrive', 'idepdrive', 'pc', 'psu',
'sasctl', 'sasldrive', 'saspdrive', 'scsictl', 'scsildrive', 'scsipdrive',
'fcahostctl', 'fcaexternalctl', 'fcaexternalacc', 'fcaldrive', 'fcapdrive',
'dactl', 'daacc', 'daldrive', 'dapdrive', 'fan', 'pnic', 'lnic', 'temperature', 'ilo', 'memory'
```

**Comment by kevkev-73** [comment]
Thank you !!
