### ISSUE TITLE
 nrpe apps::sccm::local::plugin Cannot find a provider with the name 'AdminUI.PS.Provider\CMSite'

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3089]
Hello,

The command :

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname xx.xx.xx.xx --command='check_centreon_plugins' --ssl-opt="SSL_ca_file => '/etc/centreon/certificat/ca/ca_cert.pem'" --ssl-opt="SSL_cert_file => '/etc/centreon/certificat/client_certs/client_cert.pem'" --ssl-opt="SSL_key_file => '/etc/centreon/certificat/client_certs/client_cert.key'" --nrpe-timeout 60 --nrpe-port 5666 --arg='apps::sccm::local::plugin' --arg='apps::microsoft::sccm::local::plugin'   --arg='database-replication-status' --arg='--source-encoding=iso-8859-1 --verbose'`

Return 

`UNKNOWN: Command error: System.Management.Automation.ProviderNotFoundException: Cannot find a provider with the name 'AdminUI.PS.Provider\CMSite'. -    at System.Management.Automation.SessionStateInternal.GetSingleProvider(String name) -    at Microsoft.PowerShell.Commands.NewPSDriveCommand.ProcessRecord()`

Same problem : https://github.com/centreon/centreon-plugins/issues/2906#issuecomment-870675599

The command work perfectly :
`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode query --custommode nrpe --hostname xx.xx.xx.xx --command='check_centreon_plugins' --ssl-opt="SSL_ca_file => '/etc/centreon/certificat/ca/ca_cert.pem'" --ssl-opt="SSL_cert_file => '/etc/centreon/certificat/client_certs/client_cert.pem'" --ssl-opt="SSL_key_file => '/etc/centreon/certificat/client_certs/client_cert.key'" --nrpe-timeout 60 --nrpe-port 5666 --arg='apps::sccm::local::plugin' --arg='apps::microsoft::sccm::local::plugin'   --arg='site-status' --arg='--source-encoding=iso-8859-1 --verbose'`

Can you correct the problem please ?

Thank you

**Comment by garnier-quentin** [comment]
You can test: https://github.com/centreon/centreon-nsclient-build/releases/tag/20210909134203

**Comment by prohand** [comment]
I have this error with same command : 

UNKNOWN: Cannot decode json response: malformed UTF-8 character in JSON string, at character offset 283 (before "\x{fffd}ge de Brigna...") at C:\Windows\TEMP\par-532d5343434d2d50524924\cache-e336696ed2a7ade2591497b79d0616818b061708\inc\lib/apps/microsoft/sccm/local/mode/databasereplicationstatus.pm line 197.

The problem is encoding.
But what to use ?

Thank you

**Comment by garnier-quentin** [comment]
I will do the same patch so

**Comment by prohand** [comment]
Ok thank you :)

**Comment by garnier-quentin** [comment]
You can test with last version: https://github.com/centreon/centreon-nsclient-build/releases/tag/20210910075442
