### ISSUE TITLE
[plugin] Netgear Switches

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#309]
Hello,

Is it possible to got a Netgear plugin for switches?

Thanks a lot

**Comment by Sims24** [comment]
Hi, 

Could you provide model and walk/mibs from the equipments by mail please ? 

Thanks Matthieu,

**Comment by matthieu-robin** [comment]
Hi,

I have only the supported Mibs by the Netgear (GS728TP):

banner.mib	
diffserv.mib	
diffserv-dscp-tc-rfc3289.mib	
draft-ietf-bridge-8021x.mib	
draft-ietf-bridge-rstpmib-04.mib	
draft-ietf-entmib-sensor-mib.mib	
draft-ietf-hubmib-etherif-mib-v3-00.mib	
draft-ietf-syslog-device-mib.mib	
env_mib.mib	
ianaaddrfamnumbers.mib	
ianaifty.mib	
ianaprot.mib	
inet-address-mib.mib	
ip-forward-mib.mib	
ip-mib.mib	
lldp.mib	
lldpextdot1.mib	
lldpextdot3.mib	
lldpextmed.mib	
macbaseprio.mib	
mnginf.mib	
ospf.mib	
p-bridge-mib.mib	
policy.mib	
q-bridge-mib.mib	
qosclimib.mib	
radlan-3sw2swtables-mib.mib	
radlan-brgmacswitch-mib.mib	
radlan-bridgemibobjects-mib.mib	
radlan-cdb-mib.mib	
radlan-cli-mib.mib	
radlan-deviceparams-mib.mib	
radlan-dhcpcl-mib.mib	
radlan-dot1x-mib.mib	
radlan-endofmib-mib.mib	
radlan-gvrp-mib.mib	
radlan-jumboframes-mib.mib	
radlan-mib.mib	
radlan-mri-mib.mib	
radlan-multisessionterminal-mib.mib	
radlan-smon-mib.mib	
radlan-stormctrl-mib.mib	
radlan-telnet-mib.mib	
radlan-traceroute-mib.mib	
radlan-trunk-mib.mib	
RFC1155-SMI.my	
rfc1213.mib	
rfc1493.mib	
rfc1611.mib	
rfc1612.mib	
rfc1724.mib	
rfc1757.mib	
rfc1850.mib	
rfc1907.mib	
rfc2011.mib	
rfc2013.mib	
rfc2233.mib	
rfc2571.mib	
rfc2572.mib	
rfc2573.mib	
rfc2574.mib	
rfc2575.mib	
rfc2576.mib	
rfc2613.mib	
rfc2665.mib	
rfc2668.mib	
rfc2674.mib	
rfc2737.mib	
rfc2925.mib	
rfc3176.mib	
rfc3621.mib	
rfc4668.mib	
rfc4670.mib	
RFC-1212.my	
rlaaa.mib	
rlapplication.mib	
rlbrgmulticast.mib	
rlbridgesecurity.mib	
rlcopy.mib	
rlCpuCounters.mib	
rlDebugCapabilities.mib	
rldhcp.mib	
rldlf.mib	
rldnscl.mib	
rleee.mib	
rlembweb.mib	
rlfile.mib	
rlgreeneth.mib	
rlinterfaces.mib	
rlinterfaces_recovery.mib	
rlip.mib	
rliprouter.mib	
rlipv6.mib	
rllcli.mib	
rllldp.mib	
rlmacmulticast.mib	
rlmcmngr.mib	
rlmng.mib	
rlopenflow.mib	
rlphy.mib	
rlphysdescription.mib	
rlPoe.mib	
rlprotectedport.mib	
rlrmon.mib	
rlrs232.mib	
rlsecsd.mib	
rlSecuritySuite.mib	
rlsflow.mib	
rlsnmp.mib	
rlsntp.mib	
rlssh.mib	
rlssl.mib	
rlstack.mib	
rlsyslog.mib	
rlsysmng.mib	
rltuning.mib	
rludp.mib	
rlvlan.mib	
rlvlanVoice.mib	
rlvoipsnoop.mib	
rlwrandomtaildrop.mib	
rmon2.mib	
smartPorts.mib	
SNMPv2-CONF.my	
SNMPv2-MIB.my	
SNMPv2-SMI.my	
SNMPv2-TC.mib	
SNMPv2-TC.my	
SNMPv2-TM.my	
tbi.mib	
trunk.mib	
udp-mib.mib


that’s all :-(

Thanks for your help

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by Sims24** [comment]
Would prefer to have an equipment to walk, developp and then test. Just with theses mibs ... Could be long, buggy and painfull ... Will try to find one on my side but if somebody has a walk just let us know ;)

**Comment by matthieu-robin** [comment]
I found these one:
http://kb.netgear.com/app/answers/detail/a_id/24352/~/mibs-for-smart-switches


Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by maksimatveev** [comment]
@Sims24 I have sent Quentin MIB's ~5000, there should be, I think ;)

**Comment by rk4an** [comment]
Hi,

I just send to @Sims24 output of snmpwalk.

**Comment by pierrick-openIT** [comment]
Hi,
i have to monitor a lot of netgear too. If you want i have acces to this devices:

GS110TP
GS108Tv2
GS108Tv1
GS108PEv3

News regarding Netgear integration ?

**Comment by garnier-quentin** [comment]
Could you provide full snmpwalk ?

**Comment by pierrick-openIT** [comment]
Yes for sure ..check your MP ;)

**Comment by garnier-quentin** [comment]
Done!

**Comment by pierrick-openIT** [comment]
Great christmas gift, thanks.
