### ISSUE TITLE
apps::vmware::connector::plugin Cannot get value for counters

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3091]
Hello,

This command : 

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::vmware::connector::plugin --mode net-host --custommode=connector --connector-hostname=127.0.0.1 --container ESX1 --nic-name vmnic2 --time-shift=40`

Return alternativly : 

`UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...)`

Vcenter and esx are a same datetime.

Thank you

**Comment by garnier-quentin** [comment]
Please look the graph in your vcenter if you have some datas.

**Comment by prohand** [comment]
I have some datas in graph on vcenter

**Comment by garnier-quentin** [comment]
Could you show me the graph ?

**Comment by prohand** [comment]
![image](https://user-images.githubusercontent.com/20227162/132818088-6b64bf63-491d-423e-8064-508b1adfa3e7.png)

**Comment by garnier-quentin** [comment]
The connector check the following metrics:
```
net.received.average
net.transmitted.average
```

I think you show me: net.usage.average

**Comment by prohand** [comment]
![image](https://user-images.githubusercontent.com/20227162/132820569-b0bc5fe3-c57f-47e8-84a3-f95cec1cb91c.png)

**Comment by prohand** [comment]
![image](https://user-images.githubusercontent.com/20227162/132820617-42eb4c6d-2a52-40a5-8996-88c214ef2c17.png)

**Comment by garnier-quentin** [comment]
It's weird. we should do a session

**Comment by prohand** [comment]
Yes but the problem occurs alternatively :(

**Comment by garnier-quentin** [comment]
Take a look to the graph when the problem occurs.

**Comment by prohand** [comment]
Hello,

I have apply this KB : https://kb.vmware.com/s/article/2017778 
With   das.config.fdm.unknownStateMonitorPeriod = 30
And restart vpxd in vcenter.
The problem does not occured.

Thank you
