### ISSUE TITLE
local nfsstat plugin

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#31]
Hi,

can we add a Plugin for nfsstat (local ssh)?

```
nfsstat -l
nfs v3 client        total:  4757195
------------- ------------- --------
nfs v3 client      getattr:   463364
nfs v3 client       lookup:   858908
nfs v3 client       access:  2437775
nfs v3 client     readlink:       45
nfs v3 client         read:   973925
nfs v3 client  readdirplus:     1634
nfs v3 client       fsstat:    21520
nfs v3 client       fsinfo:       16
nfs v3 client     pathconf:        8
```

**Comment by florian-asche** [comment]
we shouldnt do it with nfsstat. We should read from proc files.
A check if file is there first, so that plugin dont report error if server has no nfs.

**Comment by garnier-quentin** [comment]
Could you give me the content of the proc file ?

**Comment by florian-asche** [comment]
/proc/net/rpc/nfsd - procfs-based interface to kernel NFS server statistics.
/proc/net/rpc/nfs - procfs-based interface to kernel NFS client statistics.

cat /proc/net/rpc/nfsd
rc 0 0 0
fh 0 0 0 0 0
io 0 0
th 8 0 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
ra 32 0 0 0 0 0 0 0 0 0 0 0
net 0 0 0 0
rpc 0 0 0 0 0
proc2 18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
proc3 22 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
proc4 2 0 0
proc4ops 59 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0                                                                                                                              

cat /proc/net/rpc/nfs
net 0 0 0 0
rpc 154712227 287060 154713742
proc2 18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
proc3 22 0 18683590 0 28772513 82290143 50 24253712 0 0 0 0 0 0 0 0 0 1598 65512 639297 30 14 0
proc4 48 0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0 0 4 56 6 2 0 0 0 0 0 4 6288 0 0 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by florian-asche** [comment]
/proc/stat contains system statistics.

       /proc/uptime contains system uptime.

       /proc/partitions contains disk statistics (for pre 2.5 kernels that have been patched).

       /proc/diskstats contains disks statistics (for post 2.5 kernels).

       /sys contains statistics for block devices (post 2.5 kernels).

       /proc/self/mountstats contains statistics for network filesystems.

       /dev/disk contains persistent device names.

**Comment by florian-asche** [comment]
$ /usr/bin/iostat -n 60 2
Linux 2.6.32-573.3.1.el6.x86_64 (XXXXXXX) 	16.02.2016 	_x86_64_	(24 CPU)

Filesystem:              rBlk_nor/s   wBlk_nor/s   rBlk_dir/s   wBlk_dir/s   rBlk_svr/s   wBlk_svr/s     ops/s    rops/s    wops/s
XXXXXXXXXXXXXXXXXXXXXX      1341,45       659,30         0,00         0,00       516,91       659,47     17,52      4,31      5,36
XXXXXXXXXXXXXXXXXXXXXX         0,58         0,05         0,00         0,00         0,10         0,05     17,52      0,00      0,01
XXXXXXXXXXXXXXXXXXXXXX         0,58         0,00         0,00         0,00         0,58         0,00     17,52      0,00      0,00
XXXXXXXXXXXXXXXXXXXXXX         0,00         0,00         0,00         0,00         0,00         0,00     17,52      0,00      0,00
XXXXXXXXXXXXXXXXXXXXXX         0,00         0,00         0,00         0,00         0,00         0,00     17,52      0,00      0,00
XXXXXXXXXXXXXXXXXXXXXX         0,00         0,00         0,00         0,00         0,00         0,00     17,52      0,00      0,00
XXXXXXXXXXXXXXXXXXXXXX         0,00         0,01         0,00         0,00         0,00         0,01     17,52      0,00      0,00
XXXXXXXXXXXXXXXXXXXXXX       106,16         0,51         0,00         0,00       105,33         0,52      0,98      0,83      0,01
XXXXXXXXXXXXXXXXXXXXXX         0,00         0,00         0,00         0,00         0,00         0,00      0,53      0,00      0,00
XXXXXXXXXXXXXXXXXXXXXX         0,00         0,00         0,00         0,00         0,00         0,00      0,53      0,00      0,00
XXXXXXXXXXXXXXXXXXXXXX         0,00         0,00         0,00         0,00         0,00         0,00      0,53      0,00      0,00

**Comment by florian-asche** [comment]
We need to think about this. 

So we have:
- /proc/net/rpc/nfsd
- /proc/net/rpc/nfs
for global NFS Server and Client Statistics.

Then we have for all mounted filesystems:
- /proc/self/mountstats

The NFS-Server and client Statistics are no priority for me. I need to see mount-io.

So a local mount-io stats addon whould be great. Here is some Example code in python:
https://github.com/BrightcoveOS/Diamond/blob/master/src/collectors/mountstats/mountstats.py

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
