### ISSUE TITLE
[os::aix::snmp::plugin] Mode for memory check ?

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#310]
Is it possible to have a mode to check the AIX memory ?
Using : 
HOST-RESOURCES-MIB::hrStorageType.* = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageDescr.* = STRING: System RAM

**Comment by garnier-quentin** [comment]
Don't know if it's relevant. Maybe it's like Solaris.

**Comment by dooko** [comment]
Well it is for us :)
What do you mean it's like Solaris ?

**Comment by garnier-quentin** [comment]
With snmp on AIX, it display the "good" memory usage (without cache) ?

**Comment by dooko** [comment]
No it counts the cache too...

**Comment by garnier-quentin** [comment]
So with the cache, it's useless no ? You'll always have near 100%.

**Comment by dooko** [comment]
Well it depends on how your server is configured. In certain case yes.

**Comment by garnier-quentin** [comment]
What do you mean by how it's configured ? You can configure the kernel memory usage for that in AIX ?

**Comment by dooko** [comment]
As I know, it's the application that use the memory to cache things, like Oracle or DB2.
So, we can't do anything from it. Forget it. We'll use NRPE :)

**Comment by garnier-quentin** [comment]
No problem. Re-open it if you have some other OIDs to monitor it.
