### ISSUE TITLE
cloud::azure::storage::storageaccount::plugin Login endpoint API returns error code 'invalid_client'

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3102]
Hello,

Alternatively this command : 

/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::storage::storageaccount::plugin --tenant='xxxxx' --subscription='xxxx' --client-id='xxxxx' --client-secret='***' --custommode=api --resource="xxxxx" --resource-group="xxxxxx" --mode='blob-count' --zeroed --timeout 120 --debug

Return : 

UNKNOWN: Login endpoint API returns error code 'invalid_client' (add --debug option for detailed message)

Can i send the debug to you're email ?

Thank you

**Comment by garnier-quentin** [comment]
Yes you can

**Comment by prohand** [comment]
I have send the debug file
