### ISSUE TITLE
[network::cisco::standard::snmp::plugin] - mode=arp: add filter for IP/MAC addresses

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3103]
It should be useful to add a filter for IP and MAC addresses on ARP mode. This would allow a better configuration of the service in cases where some IP/MAC's are correctly configured with more then 1.
also for [os::linux::snmp::plugin] or other ARP modes

Thanks

**Comment by garnier-quentin** [comment]
You can test it with last version

**Comment by joschi99** [comment]
Done some test, works perfect. Thanks
