### ISSUE TITLE
HPE UPS temperature is not detected correctly

### ISSUE THREAD

**Issue by Cynexxde** [centreon/centreon-plugins#3105]
HPE's new UPS models do not correctly pass the temperature. There is no temperature sensor on the 3kva models. With the 6kva models, the temperature is output with one decimal place, but without a decimal point. They both have the same management card installed.

For the 3kva model, the message "SNMP GET Request : Cant get a single value." appears as a message. 

For the 6kva model, the output looks like this.
```
root@smon:# /centreon_plugins.pl --plugin hardware::ups::hp::snmp::plugin --hostname 10.1.2.3 --mode environment
CRITICAL: internal temperature: 293.00 C
```

**Comment by garnier-quentin** [comment]
In the mib file. It seems like a bug (could you provide the mib file from your equipment ?)
```
upsEnvAmbientTemp OBJECT-TYPE
    SYNTAX  INTEGER (-100..200)   -- UNITS Degrees Centigrade
    ACCESS  read-only
    STATUS  mandatory
    DESCRIPTION
       "The reading of the ambient temperature in the vicinity of the 
        UPS or SNMP agent."
    ::= { upsEnvironment  1 }
```

**Comment by Cynexxde** [comment]
[cpqpower1.80.zip](https://github.com/centreon/centreon-plugins/files/7162863/cpqpower1.80.zip)
[UPS-MIB.zip](https://github.com/centreon/centreon-plugins/files/7162866/UPS-MIB.zip)

**Comment by garnier-quentin** [comment]
It's the same. Seems like a bug.
```
upsEnvAmbientTemp OBJECT-TYPE
    SYNTAX  INTEGER (-100..200)   -- UNITS Degrees Centigrade
    ACCESS  read-only
    STATUS  mandatory
    DESCRIPTION
       "The reading of the ambient temperature in the vicinity of the 
        UPS or SNMP agent."
    ::= { upsEnvironment  1 }
```

**Comment by Cynexxde** [comment]
Should I contact HPE to get them to fix this or do you see another easy option there?

**Comment by garnier-quentin** [comment]
You should ask to the support about the diff with the MIB definition.
