### ISSUE TITLE
[apps::salesforce::restapi::plugin]: Unknown option: api-path

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3108]
./centreon_plugins.pl --hostname=api.status.salesforce.com  --plugin=apps::salesforce::restapi::plugin --mode=sfdc-instance --api-path=/v1
Unknown option: api-path at centreon/plugins/alternative/Getopt.pm line 67.

**Comment by garnier-quentin** [comment]
The option is: ```--api-version=v1```

**Comment by joschi99** [comment]
```
./centreon_plugins.pl --hostname=api.status.salesforce.com  --plugin=apps::salesforce::restapi::plugin --mode=sfdc-instance --api-version=v1
Unknown option: api-version at centreon/plugins/alternative/Getopt.pm line 67.
```

And if option should be `--api-version`, the help should be wrong

**Comment by garnier-quentin** [comment]
Yes there is a s.. I correct it

**Comment by garnier-quentin** [comment]
You can test with last version
