### ISSUE TITLE
[os::linux::snmp::plugin] processcount - 1 process of each

### ISSUE THREAD

**Issue by Maekess** [centreon/centreon-plugins#3114]
Hello,

I'm using --plugin=os::linux::snmp::plugin --mode=processcount and I wanna know if it is possible to check if ALL process are available in a list of processes.
I use this line and I check only if I have the count. But some process may be present twice ...

[plugins]# /usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --verbose --process-path= --regexp-path --process-name="nbatd|vnetd|bpcd|nbftclnt|nbdisco|NB_dbsrv|nbevtmgr|nbaudit|nbrb|nbemm|bpcompatd|nbjm|nbpem|nbstserv|nbrmms|nbsl|nbim|nbars|nbvault|nbcssc" --regexp-name --process-args= --regexp-args --snmp-version 2c --snmp-retries 3 --snmp-timeout 120 --warning= --critical=20: --hostname=server1
OK: Number of current processes running: 22 | 'nbproc'=22;;20:;0;
Process '7222' [status: runnable] [name: vnetd]
Process '7226' [status: runnable] [name: vnetd]
Process '7229' [status: runnable] [name: vnetd]
Process '7230' [status: runnable] [name: vnetd]
Process '7321' [status: runnable] [name: vnetd]
Process '7396' [status: runnable] [name: NB_dbsrv]
Process '7437' [status: runnable] [name: nbatd]
Process '7455' [status: runnable] [name: nbaudit]
Process '8281' [status: runnable] [name: bpcd]
Process '8331' [status: runnable] [name: nbdisco]
Process '8362' [status: runnable] [name: nbevtmgr]
Process '8553' [status: runnable] [name: nbemm]
Process '8574' [status: runnable] [name: nbrb]
Process '8684' [status: runnable] [name: bpcompatd]
Process '8695' [status: runnable] [name: nbjm]
Process '8728' [status: runnable] [name: nbpem]
Process '8765' [status: runnable] [name: nbstserv]
Process '8794' [status: runnable] [name: nbrmms]
Process '8896' [status: runnable] [name: nbsl]
Process '8915' [status: runnable] [name: nbim]
Process '8989' [status: runnable] [name: nbars]
Process '9040' [status: runnable] [name: nbvault]
[plugins]# /usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --verbose --process-path= --regexp-path --process-name="nbatd|vnetd|bpcd|nbftclnt|nbdisco|NB_dbsrv|nbevtmgr|nbaudit|nbrb|nbemm|bpcompatd|nbjm|nbpem|nbstserv|nbrmms|nbsl|nbim|nbars|nbvault|nbcssc" --regexp-name --process-args= --regexp-args --snmp-version 2c --snmp-retries 3 --snmp-timeout 120 --warning= --critical=20: --hostname=server2
OK: Number of current processes running: 23 | 'nbproc'=23;;20:;0;
Process '2206' [status: runnable] [name: vnetd]
Process '2437' [status: runnable] [name: NB_dbsrv]
Process '3494' [status: runnable] [name: nbrmms]
Process '3172' [status: runnable] [name: bpcompatd]
Process '2204' [status: runnable] [name: vnetd]
Process '2352' [status: runnable] [name: vnetd]
Process '3111' [status: runnable] [name: nbrb]
Process '3181' [status: runnable] [name: nbjm]
Process '3705' [status: runnable] [name: nbvault]
Process '2209' [status: runnable] [name: vnetd]
Process '3579' [status: runnable] [name: nbsl]
Process '2215' [status: runnable] [name: vnetd]
Process '3067' [status: runnable] [name: nbemm]
Process '2504' [status: runnable] [name: nbaudit]
Process '3629' [status: runnable] [name: nbim]
Process '3717' [status: runnable] [name: nbcssc]
Process '3657' [status: runnable] [name: nbars]
Process '2871' [status: runnable] [name: nbevtmgr]
Process '2477' [status: runnable] [name: nbatd]
Process '2813' [status: runnable] [name: nbdisco]
Process '3215' [status: runnable] [name: nbpem]
Process '2768' [status: runnable] [name: bpcd]
Process '3338' [status: runnable] [name: nbstserv]

Thanks for your help.

**Comment by garnier-quentin** [comment]
You want to test if a process name is in double, triple,... ? You can filter on the specific processname and you could use the count. Or for multiple process, you can filter on process A and process B and trigger an alert if alert is > 2.

**Comment by Maekess** [comment]
I want all of them to be up. Once or twice is not an issue

**Comment by garnier-quentin** [comment]
For me, the following threshold should do the job (less than): --critical=20:

**Comment by Maekess** [comment]
The issue is when there is multiple process of the one listed, i can be at 20 total, but not all 20 running.

**Comment by Maekess** [comment]
In this example :

```
[plugins]# /usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --verbose --process-path= --regexp-path --process-name="nbatd|vnetd|bpcd|nbftclnt|nbdisco|NB_dbsrv|nbevtmgr|nbaudit|nbrb|nbemm|bpcompatd|nbjm|nbpem|nbstserv|nbrmms|nbsl|nbim|nbars|nbvault|nbcssc" --regexp-name --process-args= --regexp-args --snmp-version 2c --snmp-retries 3 --snmp-timeout 120 --warning= --critical=20: --hostname=server2
OK: Number of current processes running: 23 | 'nbproc'=23;;20:;0;
Process '2206' [status: runnable] [name: vnetd]
Process '2437' [status: runnable] [name: NB_dbsrv]
Process '3494' [status: runnable] [name: nbrmms]
Process '3172' [status: runnable] [name: bpcompatd]
Process '2204' [status: runnable] [name: vnetd]
Process '2352' [status: runnable] [name: vnetd]
Process '3111' [status: runnable] [name: nbrb]
Process '3181' [status: runnable] [name: nbjm]
Process '3705' [status: runnable] [name: nbvault]
Process '2209' [status: runnable] [name: vnetd]
Process '3579' [status: runnable] [name: nbsl]
Process '2215' [status: runnable] [name: vnetd]
Process '3067' [status: runnable] [name: nbemm]
Process '2504' [status: runnable] [name: nbaudit]
Process '3629' [status: runnable] [name: nbim]
Process '3717' [status: runnable] [name: nbcssc]
Process '3657' [status: runnable] [name: nbars]
Process '2871' [status: runnable] [name: nbevtmgr]
Process '2477' [status: runnable] [name: nbatd]
Process '2813' [status: runnable] [name: nbdisco]
Process '3215' [status: runnable] [name: nbpem]
Process '2768' [status: runnable] [name: bpcd]
Process '3338' [status: runnable] [name: nbstserv]
```

I'm missing "nbftclnt" and it's still ok. There is like 4 "vnetd"

**Comment by garnier-quentin** [comment]
The plugin cannot do that. I think you could use collection snmp mode.

**Comment by garnier-quentin** [comment]
You need to use the last version. The command:
```
$ perl centreon_plugins.pl --plugin=apps/protocols/snmp/plugin.pm --mode=collection --hostname=10.30.2.203 --config=process.config --verbose
```

The process config file:
```
{
    "constants": {
        "critical": "1"
    },
    "mapping": {
        "processStatus": {
            "1": "running",
            "2": "runnable",
            "3": "notRunnable",
            "4": "invalid"
        }
    },
    "snmp": {
        "cache": {
            "enable": false,
            "reload": 5
        },
        "tables": [
            { 
                "name": "processTable", 
                "oid": ".1.3.6.1.2.1.25.4.2.1",
                "used_instance": "\\.(\\d+)$",
                "entries": [
                    { "name": "name", "oid": ".1.3.6.1.2.1.25.4.2.1.2" },
                    { "name": "status", "oid": ".1.3.6.1.2.1.25.4.2.1.7", "mapping": "processStatus" }
                ]
            }
        ]
    },
    "selection": [
         {
            "name": "centengine",
            "functions": [
                { "type": "count", "src": "%(snmp.tables.processTable)", "filter": "%(src.name) eq %(name)", "save": "%(numProc)" }
            ],
            "critical": "%(numProc) < %(constants.critical)",
            "perfdatas": [
                { "nlabel": "processes.count", "instances": ["%(name)"], "value": "%(numProc)", "critical": "%(constants.critical):", "min": 0 }
            ],
            "formatting": {
                "printf_msg":"number of %s processes: %s",
                "printf_var":[
                    "%(name)",
                    "%(numProc)"
                ],
                "display_ok": true
            }
        },
        {
            "name": "nbaudit",
            "functions": [
                { "type": "count", "src": "%(snmp.tables.processTable)", "filter": "%(src.name) eq %(name)", "save": "%(numProc)" }
            ],
            "critical": "%(numProc) < %(constants.critical)",
            "perfdatas": [
                { "nlabel": "processes.count", "instances": ["%(name)"], "value": "%(numProc)", "critical": "%(constants.critical):", "min": 0 }
            ],
            "formatting": {
                "printf_msg":"number of %s processes: %s",
                "printf_var":[
                    "%(name)",
                    "%(numProc)"
                ],
                "display_ok": true
            }
        }
    ],
    "formatting":{
        "custom_message_global": "All processes are ok",
        "separator": "-"
    }
}
```

**Comment by Maekess** [comment]
Hello,

The solution is amazing, did not know about that plugin/module.
Work so fine.

Thanks again, and always.
Pretty good job on those plugins.

**Comment by garnier-quentin** [comment]
Thanks for the feedback.
