### ISSUE TITLE
[hardware::pdu::apc::snmp::plugin] - Mode load - rPDUIdentDevicePowerWatts is already in Watts

### ISSUE THREAD

**Issue by CsMAr51** [centreon/centreon-plugins#3115]
Hi,

The value given by OID _.1.3.6.1.4.1.318.1.1.12.1.16_ (rPDUIdentDevicePowerWatts) is already in Watts and doesn't need to be multiplied by 10.
Here is an extract from the PowerNet MIB file:
```
rPDUIdentDevicePowerWatts OBJECT-TYPE
   SYNTAX INTEGER
   ACCESS read-only
   STATUS mandatory
   DESCRIPTION
      "Getting this OID will return the Power in Watts."

   ::= { rPDUIdent 16 }
```

https://github.com/centreon/centreon-plugins/blob/78ae0e8994dd51bdadd9b41c73f89540591497e8/hardware/pdu/apc/snmp/mode/load.pm#L206

Thank you.

**Comment by Sims24** [comment]
Thanks @CsMAr51 , you can use the last version.
