### ISSUE TITLE
plugin for Ubiquiti routeur

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#312]
Hello team,
You can create a new plugin for the Ubiquiti brand (https://www.ubnt.com), i have tested with the following checks and it works:
<img width="620" alt="cap 2016-01-30 a 18 01 33" src="https://cloud.githubusercontent.com/assets/10330979/12697130/d31b4ac4-c77b-11e5-8442-02be96f46ba8.png">

Thanks

**Comment by garnier-quentin** [comment]
Do you have some specific MIBs with information like: ap connected, users connected,... ?

**Comment by matthieu-robin** [comment]
I’m checking with the constructor, I’ll keep you informed.
Thanks

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by matthieu-robin** [comment]
I received the answer, they use the standard MIBs IETF

Thanks for your help Quentin!

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by garnier-quentin** [comment]
So i don't know if it's necessary to create a plugin. You could use the linux snmp plugin. No ?

**Comment by matthieu-robin** [comment]
I’m not an expert, but with the linux snmp plugin, you couldn’t get the « environment » status? I have tried with the cisco one, without success :-(

I don’t know exactly what we could have with these MIB.

Thanks for your help

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com

**Comment by garnier-quentin** [comment]
I don't think you'll have the environment.

**Comment by maksimatveev** [comment]
that's what the vendor offers, others think the standard for Linux/
[FROGFOOT-RESOURCES-MIB.txt](https://github.com/centreon/centreon-plugins/files/273120/FROGFOOT-RESOURCES-MIB.txt)
[UBNT-MIB.txt](https://github.com/centreon/centreon-plugins/files/273121/UBNT-MIB.txt)

**Comment by Sims24** [comment]
Thanks ! 

Is somebody may provide some walks ? Complete walk from .1 would be perfect but from .1.3.6.1.4.1.41112 also a good start ;)

**Comment by maksimatveev** [comment]
@Sims24 I can, I will put the log snmpwalk as we construct it on the access point)

**Comment by Sims24** [comment]
@maksimatveev yeah !

**Comment by Sims24** [comment]
Hi @maksimatveev , 

Reviewing tickets right now, any chance to get the walk tomorrow when we'll check for raisecom dev ? 

Thanks !

**Comment by maksimatveev** [comment]
@Sims24 So do not get to interrogate the device - firmware not supports SNMP =(

**Comment by ADN182** [comment]
Hi, subject always active ? i can post walk if already necessary

**Comment by Sims24** [comment]
Hi @ADN182 

For sure, we're waiting for such walk to go forward :) please send me the walk by mail !

If you could use following command that would be perfect : 

`snmpwalk -Cc -v2c -c public -ObentU __IP_DEVICE__ .1 > ubiquiti.snmpwalk`

Thxx

**Comment by ADN182** [comment]
i have the file, how can find your mail ?

**Comment by Sims24** [comment]
strange can't say how other found it, didn't see it on my profile at first sight.

sbomm@centreon.com

**Comment by ADN182** [comment]
Mail Send, with snmp v1 only, v2c make me timeout. Make on PicoStation M2 with the last Firmware V6.0.3

**Comment by pierrick-openIT** [comment]
Some news about integration of Ubiquiti brand ? I have Ubiquiti EdgeMax Router / Switch and Unifi AP to monitor ;-)

**Comment by matthieu-robin** [comment]
any news on this? Thanks guys!

**Comment by pierrick-openIT** [comment]
Hello, we have access to equipment Unify and Edge, have you enough information or do you need more MIBs ?

**Comment by garnier-quentin** [comment]
We need snmpwalk also:
```
$ snmpwalk -ObentU -v 2c -c public IP > ubi.snmpwalk

**Comment by garnier-quentin** [comment]
You can give me last mibs you have

**Comment by garnier-quentin** [comment]
There is some entreprise mibs for edgeswitch. And there are also for unify.

**Comment by garnier-quentin** [comment]
Do you have snmpwalk @pierrick-openIT ?

**Comment by pierrick-openIT** [comment]
Yes, next monday i will send you a full dump.

have a good weekend

**Comment by Sims24** [comment]
We close this one.

Open a new ticket with walk and mibs from last versions if it still matters to you. 

Thanks
