### ISSUE TITLE
Get memory/cpu etc with Wsman?

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon-plugins#3125]
Hi,

Is there any way to get information like memory/cpu with WSMAN? current wsman plugin has only services status mode. 

Thank You!

**Comment by garnier-quentin** [comment]
Yes there is a way (wmi, powershell,...). But i need to test it more (negotiation for example): https://github.com/centreon/centreon-plugins/issues/1973

**Comment by VidushaZ** [comment]
All right. I'm currently using check_wmi_plus plugin I got from here > https://edcint.co.nz/checkwmiplus/releases/ to get those data through wmi. You're probably aware of this one just adding it might help.

**Comment by garnier-quentin** [comment]
I don't want to use wmi directly but through WinRM.

**Comment by garnier-quentin** [comment]
Now, there are new modes for Windows WSMAN (WinRM). You can test it!

**Comment by VidushaZ** [comment]
Just checked! working fine. it is better if we can have process wise memory/cpu too like in linux plugin.
