### ISSUE TITLE
[os::windows::local::plugin] --mode=time - process centreon_plugins.exe is hanging

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3127]
Found a problem with centreon_plugins.exe, which in certain cases is hanging and causing critical problems on the host, because the process is not terminating. So on the affected hosts we have a lot of centreon_plugins.exe processes (maybe 100 processes or even more) which are consuming the memory.

One reason which is causing this problem should be this command:
`centreon_plugins.exe --plugin=os::windows::local::plugin --mode=time --warning=-3:3 --critical=-5:5`

This command launch:
```
w32tm /query /status
The following error occurred: Access is denied. (0x80070005)
```
If the execution of w32tm is not possible or has the Access denied error (also system user cannot access), then the process will hang and on every new service command request a new process will be created and hangs.

We have found another reason for the same problem using the veeam plugin, where the system user was not able to snapin the PS Veeam plugin with same behavior.

**Comment by garnier-quentin** [comment]
It's a known issue:
https://github.com/centreon/centreon-nsclient-build/issues/28
