### ISSUE TITLE
plugin to monitor Centreon poller

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#313]
Hello,

Is there a way or a plugin to check the number of hosts and services registered by poller? and of course with threshold warning /critical?

thanks a lot

**Comment by garnier-quentin** [comment]
Not yet. You can monitor the number of problems and notifications.

**Comment by garnier-quentin** [comment]
A example how to use it:
perl centreon_plugins.pl --plugin=database::mysql::plugin --dyn-mode=apps::centreon::sql::mode::countservices --username=centreon --password='xxxx' --host=127.0.0.1 --verbose

**Comment by matthieu-robin** [comment]
Au top Quentin!

Merci beaucoup!

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com
