### ISSUE TITLE
[network::cisco::firepower::fmc::restapi::plugin] - mode=devices: wrong performance datas

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3130]
as you can see on the screenshot we have 2 FMC devices, both in status red, but the metric devices.status.red.count still shows 0 devices:
CRITICAL: Domain 'Global' device 'XXX1' status: red - device 'XXX2' status: red
'devices.total.count'=2;;;0; 'devices.status.green.count'=0;;;0;2 'devices.status.black.count'=0;;0:0;0;2 'devices.status.blue.count'=0;;;0;2 'devices.status.red.count'=0;;0:0;0;2 'devices.status.yellow.count'=0;0:0;;0;2
![image](https://user-images.githubusercontent.com/6400595/134465457-87db2477-8b57-4f92-8575-026564dfb062.png)

**Comment by garnier-quentin** [comment]
Thanks. It's fixed in last git. You can test it
