### ISSUE TITLE
[aix/linux] Filesystems access

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#314]
Hi
We actually use a NRPE script to check that the filesystems are writable.
It happens thaht a filesystem is on readonly when we restore a VM.
Is that possible to do so via the snmp_standard since the following OID exist : 
HOST-RESOURCES-MIB::hrFSAccess.1 = INTEGER: readWrite(1)
Thanks

**Comment by garnier-quentin** [comment]
Interesting i can add an option in standard storage.
