### ISSUE TITLE
[os::windows::snmp::plugin] --mode=service stuck and SNMP timeout

### ISSUE THREAD

**Issue by Maekess** [centreon/centreon-plugins#3143]
Hello,

I'm afraid my problem is not entirely yours but you are so good at perl i can't ask anyone else.
My command : /usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --snmp-version 2c --snmp-community community --hostname server --snmp-timeout 120 --snmp-autoreduce --service='service' --regexp --verbose
In only have one of my poller, which is my dev centreal centreon, it get stucked and gives me the SNMP tiemout. On all others it work really fine, but I use this one to check all my command before I implement it on centreon then update my production.

May I ask you if you have any idea on how to pint point the perl issue on my server ?
All server in my farm should have the exact same perl module 
```
cpanm Path::Class@0.37 Text::Template@1.59 Net::INET6Glue@0.603 Time::Piece@1.3401 Try::Tiny@0.30 Crypt::SSLeay@0.72 UUID@0.28 XML::NamespaceSupport@1.12 XML::LibXML::Common@2.0206 XML::LibXML@2.0206 WWW::Selenium@1.36 LWP@6.48 LWP::Protocol::https@6.09 Socket6@0.29 IO::Socket::INET6@2.72 Net::HTTP@6.19 YAML@1.30 Time::Duration@1.21 Net::SNMP@v6.0.1 Net::Telnet@3.04 XML::Simple@2.25 Monitoring::Plugin@0.40 Archive::Zip@1.68 Test::NoWarnings@1.04 DBI@1.643 CPAN::Meta@2.150010 DBD::Pg@2.19.3 Time::Duration@1.21 Webinject@1.94 MIME::Base64@3.13 Authen::NTLM@1.09 DBD::Oracle@1.80

Path::Class is up to date. (0.37)
Text::Template is up to date. (1.59)
Net::INET6Glue is up to date. (0.603)
Time::Piece is up to date. (1.3401)
Try::Tiny is up to date. (0.30)
Crypt::SSLeay is up to date. (0.72)
UUID is up to date. (0.28)
XML::NamespaceSupport is up to date. (1.12)
XML::LibXML::Common is up to date. (2.0206)
WWW::Selenium is up to date. (1.36)
LWP is up to date. (6.48)
LWP::Protocol::https is up to date. (6.09)
Socket6 is up to date. (0.29)
IO::Socket::INET6 is up to date. (2.72)
Net::HTTP is up to date. (6.19)
YAML is up to date. (1.30)
Time::Duration is up to date. (1.21)
Net::SNMP is up to date. (v6.0.1)
Net::Telnet is up to date. (3.04)
XML::Simple is up to date. (2.25)
Monitoring::Plugin is up to date. (0.40)
Archive::Zip is up to date. (1.68)
Test::NoWarnings is up to date. (1.04)
DBI is up to date. (1.643)
CPAN::Meta is up to date. (2.150010)
DBD::Pg is up to date. (2.19.3)
Webinject is up to date. (1.94)
MIME::Base64 is up to date. (3.13)
Authen::NTLM is up to date. (1.09)
DBD::Oracle is up to date. (1.80)
```

Thanks

**Comment by Maekess** [comment]
Note there is maybee some more modules on that server, but i'm so bad at cpan cpanm and perl, i don't know hot to find out.

**Comment by garnier-quentin** [comment]
The same check works from an other server ?

**Comment by Maekess** [comment]
Yes, all my pollers and the failover works well, all prod servers works too.

**Comment by garnier-quentin** [comment]
Have you tried --snmp-force-getnext option ?

**Comment by Maekess** [comment]
Hello, 
sorry I did not replied earlier.

Yes the option is not helping.
There is something I don't understand, most plugin work fine on from that server, it's only this one so far that give me hard time.
And only from this server.

I guess Windows process may be a large quantity of information. But still don't understand why i guet that timeout.

**Comment by garnier-quentin** [comment]
I think you'll get the same timeout with snmpwalk. I cant do more i think (issue with snmp agent on your windows)

**Comment by Maekess** [comment]
Could you give me the OID to walk to be sure ?

**Comment by Sims24** [comment]
You can also give a try to --snmp-version=1. For whatever reason the Windows SNMP agent might respond much more faster over v1. 

Simon

**Comment by Maekess** [comment]
I'll try but every other server (any poller, I have 6 server on each prod and dev, it's the only one) executing same command work fine. It's a server issue.

**Comment by Sims24** [comment]
Yes, indeed it is.

**Comment by Maekess** [comment]
Ok, found the issue. It's IP issue. My server is on Pacemaker cluster. And when I run it, it's using the cluster IP to talk to servers.
All servers had this cluster ip set for snmp, but the main snmp service provided with windows is ip by ip set and not subnet. 

For some reason my test client was not configured with all but 1 ip, the cluster one.

Thanks for all your time.

**Comment by Sims24** [comment]
Thanks for the feedback
