### ISSUE TITLE
apps::vmware::connector::plugin --mode='net-host' : Unsafe code evaluation

### ISSUE THREAD

**Issue by Maekess** [centreon/centreon-plugins#3147]
Hello, 
I update my centreon-plugins thursday and so far i can't get this one to work :
```
/usr/lib/centreon/centreon-plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname=127.0.0.1 --mode='net-host' --vsphere-address='vcenter' --vsphere-username=user--vsphere-password=password --critical-link-status=OK --warning-link-traffic-out=80 --critical-link-traffic-out=90
UNKNOWN: Unsafe code evaluation: Bareword "OK" not allowed while "strict subs" in use at (eval 14) line 1.
```

Thx

**Comment by garnier-quentin** [comment]
Following option is wrong: ```--critical-link-status=OK```. it's: ```--critical-link-status='%{link_status} !~ /up/'```

**Comment by Maekess** [comment]
Work fine.
Thanks

**Comment by Maekess** [comment]
Found out it was not what i meant by OK at first. I wish to have no critical. I use this for bandwidth graph

**Comment by Maekess** [comment]
only critical on bandwidth 90%

**Comment by Maekess** [comment]
--critical-link-status='' is working. Do you think it's the way to do it ?
