### ISSUE TITLE
Plugin for monitoring new version of NetApp

### ISSUE THREAD

**Issue by jgrun1** [centreon/centreon-plugins#3149]
The new version of Netapp 'Active IQ Unified Manager 9.7P1' is currently lacking a plugin for monitoring.

[NetApp Documentation.pdf](https://github.com/centreon/centreon-plugins/files/7236568/NetApp.Documentation.pdf)

The plugin 'NetApp Ontap OnCommand API' is not sufficient for monitoring this version of NetApp through its API.

Services for this version would ideally be identical as for its previous version:

- Aggregate-Raid-Status
- Aggregate-Status
- Aggregate-Usage
- Cluster-Ioo
- Cluster-Status
- Cluster-Usage
- Disk-Failed
- Disk-Spare
- FC-Port-Status
- Lun-Alignment
- Lun-Online
- Lun-Usage
- Node-Failover-Status
- Node-Hardware-Status
- Qtree-Status
- Snapmirror-Status
- Snapmirror-Usage
- Volume-Io
- Volume-Status
- Volume-Usage

**Comment by Sims24** [comment]
Hi @jgrun1 

Please provide curl example for each API endpoints. 

You can send it by email if it contains any sensitive informations. 

Simon

**Comment by garnier-quentin** [comment]
Now, you should try with last version of ontap rest api
