### ISSUE TITLE
[network::cisco::asa::plugin] Mode session 

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#315]
Hi
Is it a denomination problem or the session mode of the asa plugin does not return the right value.
It returns the number of TCP connexions as in :
_sh conn count 
610 in use, 1662 most used_
But the term session, as I understand it, is for the number of VPN sessions, as in :
crasSVCNumSessions (1.3.6.1.4.1.9.9.392.1.3.35) : The number of currently active SVC sessions.
crasWebvpnNumSessions (1.3.6.1.4.1.9.9.392.1.3.38) : The number of currently active Webvpn sessions.
crasIPSecNumSessions (1.3.6.1.4.1.9.9.392.1.3.26) : The number of currently active IPSec sessions.
crasNumSessions (1.3.6.1.4.1.9.9.392.1.3.1) : The number of currently active sessions. A session is a connection terminating on the managed entity which has been established to provide remote access connectivity to a user. A session is said to be 'active' if it is ready to carry application traffic between the user and the managed entity. A session which is not active is defined to be 'dormant'.
Thanks for the clarification.

**Comment by garnier-quentin** [comment]
HI,

You mean that oids are the number of tcp connections ?
cufwConnGlobalNumActive
cufwConnGlobalConnSetupRate1
cufwConnGlobalConnSetupRate5

**Comment by dooko** [comment]
Yes

**Comment by dooko** [comment]
You use this branch : http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.4.1.9.9.491.1.1.1
I think you should use this one : http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.4.1.9.9.392.1.3

As I see it, you should return :
 - The number of currently active Email proxy sessions (crasEmailNumSessions)
 - The number of currently active IPSec sessions (crasIPSecNumSessions)
 - The number of currently active LAN to LAN sessions (crasL2LNumSessions)
 - The number of currently active Load Balancing sessions (crasLBNumSessions)
 - The number of currently active SVC sessions (crasSVCNumSessions)
 - The number of currently active Webvpn sessions (crasWebvpnNumSessions)
 - The number of currently active sessions (crasNumSessions) (i.e. total sessions)

**Comment by garnier-quentin** [comment]
Thanks i'll add it.

**Comment by dooko** [comment]
You can but you can't say it's the sessions, but the tcp connections.
I think you should divide the two.

**Comment by garnier-quentin** [comment]
It uses the term from the mib: The number of connections which are currently active ;)

**Comment by dooko** [comment]
Do you know when it will be implemented ?

**Comment by garnier-quentin** [comment]
I don't really know when. I will tried to do it soon.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by dooko** [comment]
Well I get :
# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::cisco::asa::plugin --mode=sessions --hostname=10.60.3.38  --verbose
OK: Connections current : 6 - Sessions SVC : 0.00/s, webvpn : 0.00/s | 'connections_current'=6;;;0; 'sessions_svc_psec'=0.00;;;0; 'sessions_webvpn_psec'=0.00;;;0;

And with snmpwalk :
SNMPv2-SMI::enterprises.9.9.392.1.3.1.0 = Gauge32: 34
SNMPv2-SMI::enterprises.9.9.392.1.3.23.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.24.0 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.25.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.26.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.27.0 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.28.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.29.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.30.0 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.31.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.32.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.33.0 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.34.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.35.0 = Gauge32: 34
SNMPv2-SMI::enterprises.9.9.392.1.3.36.0 = Counter32: 9269
SNMPv2-SMI::enterprises.9.9.392.1.3.37.0 = Gauge32: 59
SNMPv2-SMI::enterprises.9.9.392.1.3.38.0 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.392.1.3.39.0 = Counter32: 482
SNMPv2-SMI::enterprises.9.9.392.1.3.40.0 = Gauge32: 7

**Comment by garnier-quentin** [comment]
Could you add at line 249 and give me the output:
```
use Data::Dumper;
print Data::Dumper::Dumper($self->{results});
```

Thanks

**Comment by dooko** [comment]
Alriiiight, my bad, not checking the good one...

Works well : 
OK: Connections current : 591, average last 1min 9, average last 5min : 10 - Sessions total : 32, current SVC : 32, SVC : 0.03/s, webvpn : 0.00/s | 'connections_current'=591;;;0; 'connections_1m'=9;;;0; 'connections_5m'=10;;;0; 'sessions_total'=32;;;0; 'sessions_svc_current'=32;;;0; 'sessions_svc_psec'=0.03;;;0; 'sessions_webvpn_psec'=0.00;;;0;

Missing ':' on line 48.

Thanks for the reactivity !

**Comment by garnier-quentin** [comment]
Is it useful per seconds ? Maybe i could display the number of new sessions.

**Comment by dooko** [comment]
Not really... And the number of new sessions either, the graph will show that.

**Comment by garnier-quentin** [comment]
The number of "new" sessions, you won't have that. With the other counter, it's the current.

**Comment by dooko** [comment]
Ah, you mean the difference between the current "cumulate session" value and the last one. Well, I don't kown, why not.

**Comment by garnier-quentin** [comment]
Exactly.
