### ISSUE TITLE
centreon_plugins.exe (20210915) - Use of uninitialized value in pattern match (m//) at (eval 36) line 1

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#3150]
Hello,

With the last centreon_plugins.exe some arguments are not well interpreted :

Default value for pending-reboot :
-c check_centreon_plugins -a 'os::windows::local::plugin' 'pending-reboot'
Use of uninitialized value in pattern match (m//) at (eval 36) line 1.
OK: 'Microsoft Windows Server 2012 R2 Standard': reboot pending is false [Windows Update: false][Component Based Servicing: false][SCCM Client: false][File Rename Operations: false][Computer Name Change: false] |

Other arguments for pending reboot :
-c check_centreon_plugins -a 'os::windows::local::plugin' 'pending-reboot' ' --warning-status="%{WindowsUpdate} =~ /true/i || %{CCMClientSDK} =~ /true/i || %{CBServicing} =~ /true/i"'
Use of uninitialized value in pattern match (m//) at (eval 36) line 1.
Use of uninitialized value in pattern match (m//) at (eval 36) line 1.
Use of uninitialized value in pattern match (m//) at (eval 36) line 1.
OK: 'Microsoft Windows Server 2012 R2 Standard': reboot pending is false [Windows Update: false][Component Based Servicing: false][SCCM Client: false][File Rename Operations: false][Computer Name Change: false] |

Same problem for 'apps::microsoft::sccm::local::plugin' 'site-status' :
[centreon-engine@frparadm135 ~]$ /usr/lib64/nagios/plugins/check_centreon_nrpe -H 10.105.82.227 -t 15  -p 5665 -u -m 8192 -c check_centreon_plugins -a 'apps::microsoft::sccm::local::plugin' 'site-status'  ' --critical-status="%{type} == 2 || %{status} == 1"'
Use of uninitialized value in numeric eq (==) at (eval 36) line 1.
Use of uninitialized value in numeric eq (==) at (eval 36) line 1.
OK: Site 'CM0' status is 'ACTIVE' [type: PRIMARY] [mode: '-'] |

[centreon-engine@frparadm135 ~]$ /usr/lib64/nagios/plugins/check_centreon_nrpe -H 10.105.82.227 -t 15  -p 5665 -u -m 8192 -c check_centreon_plugins -a 'apps::microsoft::sccm::local::plugin' 'site-status'  ' --critical-status="%{type} eq 2 || %{status} eq 1"'
Use of uninitialized value in string eq at (eval 36) line 1.
Use of uninitialized value in string eq at (eval 36) line 1.
OK: Site 'CM0' status is 'ACTIVE' [type: PRIMARY] [mode: '-'] |

Is this a bug or there is a new way to use %{variables} ?

Thanks

**Comment by Aleksey-Maksimov** [comment]
We also found a similar issue on another plugin.

```
# ./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin 
--mode=spanning-tree 
--critical-status='(%{op_status} =~ /up/ && %{state} =~ /forwarding|broken/ && %{index} = /10102/ ) || ( %{op_status} =~ /up/ && %{state} =~ /blocking|broken/ && %{index} != /10102/)' 
--hostname='SW024' --snmp-community='public' --snmp-version='2c'

UNKNOWN: Unsafe code evaluation: Can't modify pattern match (m//) in scalar assignment at (eval 15) line 1, near "/10102/ ) "
Can't modify logical and (&&) in scalar assignment at (eval 15) line 1, near "/10102/ ) "
Can't modify logical and (&&) in scalar assignment at (eval 15) line 1, near "/10102/ ) "
```

It looks like there is a problem with the interpretation of the plugin arguments. 
We did not observe this problem on the old version of the plugin before the update.

**Comment by Sims24** [comment]
Hi @ritouret 

This is a bug indeed but Quentin fixed it here: https://github.com/centreon/centreon-nsclient-build/releases/tag/20210923161310

@Aleksey-Maksimov you have to use eq here. This might work before but it's unsafe as it could allow user to run malicious perl code using scalar assignments. 

Quentin hardened the code to prevent this, you should modify accordingly. We had to introduce this even if we know it would probably trigger some unexpected incompatibilities.

**Comment by Aleksey-Maksimov** [comment]
Hello @Sims24. 
Thanks for the clarification. Our problem has been resolved.
