### ISSUE TITLE
Add SupportExpirationDate to apps::backup::veeam::local::plugin mode licenses

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#3155]
Hi,

At the moment the expiration date of a license is being checked. SupportExpirationDate, which usually expires sooner, would also be important.

![image](https://user-images.githubusercontent.com/46994680/135261989-7dc643f4-b2e4-4bad-835f-38c2cc45d1e9.png)

Here the output of the Get-VBRInstalledLicense PowerShell ..

Status                              : Valid
**ExpirationDate                      :**
Type                                : Perpetual
Edition                             : Standard
LicensedTo                          : xxxxxx
SocketLicenseSummary                : {Veeam.Backup.PowerShell.Infos.VBRSocketLicenseSummary}
InstanceLicenseSummary              : Veeam.Backup.PowerShell.Infos.VBRInstanceLicenseSummary
CapacityLicenseSummary              : Veeam.Backup.PowerShell.Infos.VBRCapacityLicenseSummary
SupportId                           : 00001111
**SupportExpirationDate               : 01/10/2021 00:00:00**
AutoUpdateEnabled                   : False
FreeAgentInstanceConsumptionEnabled : True
CloudConnect                        : Disabled

Can you add this in centreon/common/powershell/veeam/licenses.pm and in /apps/backup/veeam/local/mode/licenses.pm and --warning-expires and --warning-expires both check dates ?

Thanks

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
