### ISSUE TITLE
Bug for centreon-plugin-Applications-Protocol-Http

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#3157]
Hi,

The test answers OK, but the port is not listening.
It seems to be work with curl.

[root@linux ~]# /usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=192.168.X.X --urlpath='/database/connect.htm' --port='7843' --proto=http --warning-status= --critical-status= --unknown-status=''  --timeout=10 --verbose --debug
**OK: HTTP test(s) | 'size'=167B;;;0; 'time'=0.020s;;;0;**
======> request send
GET http://192.168.X.X:7843/database/connect.htm
User-Agent: centreon::plugins::backend::http::useragent

======> response done
500 Can't connect to 192.168.X.X:7843 (Connexion refusée)
Content-Type: text/plain
Client-Date: Wed, 29 Sep 2021 13:28:57 GMT
Client-Warning: Internal response

Can't connect to 192.168.X.X:7843 (Connexion refusée)

LWP::Protocol::http::Socket: connect: Connexion refusée at /usr/share/perl5/LWP/Protocol/http.pm line 51.
Can't connect to 192.168.X.X:7843 (Connexion refusée)

LWP::Protocol::http::Socket: connect: Connexion refusée at /usr/share/perl5/LWP/Protocol/http.pm line 51.

[root@linux ~]# /usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=192.168.X.X --urlpath='/database/connect.htm' --port='7243' --proto=http --warning-status= --critical-status= --unknown-status=''  --timeout=10 --http-backend=curl
**UNKNOWN: curl perform error : Couldn't connect to server** 
[root@linux ~]# 

Last version : centreon-plugin-Applications-Protocol-Http-20210915-070550.el7.centos.noarch

**Comment by garnier-quentin** [comment]
Curl backends doesn't react in the same way. You can use option --opt-exit=ok if you want OK.

**Comment by romsworld** [comment]
No, --port='7843 is down, so my first test with lwp should be CRITICAL, and no ok.

**OK: HTTP test(s) |** 'size'=167B;;;0; 'time'=0.020s;;;0;
======> request send
GET http://192.168.X.X:7843/database/connect.htm
User-Agent: centreon::plugins::backend::http::useragent

======> response done
**500 Can't connect to 192.168.X.X:7843 (Connexion refusée)**

**Comment by garnier-quentin** [comment]
use that option: ```--critical-status='%{http_code} != 200'```

**Comment by romsworld** [comment]
Super, thanks !
