### ISSUE TITLE
[bug] Meraki discovery doesn't manage pagination

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#3161]
## Bug/Question

When discovering a large number of assets from a Meraki platform, the Plugin only returns the first 1000 results. That's because we don't catch the 'next' URL allowing to process results from other pages. 

This is discussed here: https://community.meraki.com/t5/Developers-APIs/Python-pagination-get-8000-devices/td-p/101593 We should implement the same kind of solution. 

Thanks

**Comment by garnier-quentin** [comment]
We need a massive refactoring for the Cisco Meraki API.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3466
