### ISSUE TITLE
cloud::azure::management::automation::plugin with mode health problem

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3163]
Hello,

I type this command : 

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::management::automation::plugin --tenant='xxxxx' --subscription='xxxx --client-id='xxxx' --client-secret='xxxx' --custommode=api --resource="xxxx" --resource-group="xxxxx"  --mode=health --debug`

Is return : 

`UNKNOWN: Can't locate object method "new" via package "cloud::azure::management::automation::mode::health" (perhaps you forgot to load "cloud::azure::management::automation::mode::health"?) at /usr/lib/centreon/centreon-plugins/centreon/plugins/script_custom.pm line 124.`

Can you fix the problem please ?

Thank you

**Comment by garnier-quentin** [comment]
You can test with last version

**Comment by prohand** [comment]
It's OK.
Thank you

**Comment by prohand** [comment]
I have this error : 

{"code":"UnsupportedResourceType","message":"Resource type not supported."}
Message : Resource type not supported.

**Comment by thibaults-centreon** [comment]
It is mistake sorry. The health check is not available for automation resources (see  https://docs.microsoft.com/en-us/azure/service-health/resource-health-checks-resource-types#next-steps).
We will remove the mode from the plugin

**Comment by prohand** [comment]
Ok thank you
