### ISSUE TITLE
UNKNOWN: Cannot decode json response: malformed UTF-8 character in JSON string

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#3168]
Hello,

Using  'os::windows::local::plugin' 'pending-reboot' on **32 bits** server, i have this error message with last centreon_plugins (20210923) :

UNKNOWN: Cannot decode json response: malformed UTF-8 character in JSON string, at character offset 70 (before "\x{fffd} Windows Ser...") at C:\Windows\TEMP\par-4652504152494e54323324\cache-19c719c2f33e11d02bfd2e8d7825d51983d7a8fd\inc\lib/os/windows/local/mode/pendingreboot.pm line 143.

According these previous issues : https://github.com/centreon/centreon-plugins/issues/2906 and https://github.com/centreon/centreon-plugins/issues/3089 , i've tried to add alternatively but unsuccessfully these options :
--source-encoding="iso-8859-1"
--source-encoding="cp1252"
--source-encoding="UTF-16"

Did you report your update on centreon_plugins 32 bit version ?

If yes, how can i find the correct value for --source-encoding ?

Here is the result with --ps-exec-only :
{"CBServicing":false,"PendFileRename":true,"WindowsVersion":"Microsoft▒ Windows Server▒ 2008 Enterprise ","WindowsUpdate":false,"RebootPending":true,"PendComputerRename":false,"CCMClientSDK":false}

Thanks

**Comment by garnier-quentin** [comment]
I need to update the mode for that.

**Comment by garnier-quentin** [comment]
It's fixed: https://github.com/centreon/centreon-plugins/pull/3169

**Comment by ritouret** [comment]
Thank you Quentin, it works after manually patch the pendingreboot.pm file :
OK: 'Microsoft▒ Windows Server▒ 2008 Enterprise ': reboot pending is true [Windows Update: false][Component Based Servicing: false][SCCM Client: false][File Rename Operations: true][Computer Name Change: false] |

Would we have a new release here : https://github.com/centreon/centreon-nsclient-build/releases ?

**Comment by garnier-quentin** [comment]
I will update it for a pre-release

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-nsclient-build/releases/tag/20211001142055

**Comment by ritouret** [comment]
Thank you Quentin, it works fine with this new release.
