### ISSUE TITLE
[BUG] Tomcat-Load-Average : Unknown option: warning at /usr/lib/centreon/plugins/centreon_tomcat_jmx.pl line 2773.

### ISSUE THREAD

**Issue by zizounetgit** [centreon/centreon-plugins#3176]
Using host template : App-Webserver-Tomcat-JMX-custom

The command : App-Webserver-Tomcat-Load-Average-JMX is

 _$CENTREONPLUGINS$/centreon_tomcat_jmx.pl --plugin=apps::tomcat::jmx::plugin --mode=load-average --custommode=jolokia --url='$_HOSTJOLOKIAURL$' --username='$_HOSTJOLOKIAUSERNAME$' --password='$_HOSTJOLOKIAPASSWORD$' --target-url='$_HOSTJOLOKIATARGETURL$' --target-username='$_HOSTJOLOKIATARGETUSERNAME$' --target-password='$_HOSTJOLOKIATARGETPASSWORD$' $_HOSTJOLOKIAEXTRAOPTIONS$ --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$_

at run : 

/usr/lib/centreon/plugins/centreon_tomcat_jmx.pl --plugin=apps::tomcat::jmx::plugin --mode=load-average --custommode=jolokia --url='http://172.16.3.225:8080/jolokia/' --username='xxxx' --password='xxxx' --target-url='' --target-username='' --target-password=''  --warning='' --critical='' 

but option --warning=  and --critical= is Unknown it need  --warning-load1 --critical-load1 instead 
i cant change it cause it's a lock command

**Comment by garnier-quentin** [comment]
Please update your pack
