### ISSUE TITLE
[network::hp::procurve::snmp::plugin] - new mode poe-status

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3177]
It should be nice to implement the possibility to monitor for HP Procurve switches the PoE status. The status is available through SNMP:

Possibile statuses are:

disabled(1) - OK
searching(2) - OK
deliveringPower(3) - OK
fault(4)
test(5)
otherFault(6)

MIBS
[MIBs-May-2019.zip](https://github.com/centreon/centreon-plugins/files/7292674/MIBs-May-2019.zip)

snmp walk:
[procurve-poe.zip](https://github.com/centreon/centreon-plugins/files/7292767/procurve-poe.zip)

**Comment by garnier-quentin** [comment]
On the "standard" mib, it seems we have:
```
pethPsePortDetectionStatus = .1.3.6.1.2.1.105.1.1.1.1 (disabled(1), searching(2), deliveringPower(3), fault(4), test(5), otherFault(6)) [ index = pethPsePortGroupIndex.pethPsePortIndex)
pethMainPsePower = .1.3.6.1.2.1.105.1.3.1.1.2 (index = pethPsePortGroupIndex)
pethMainPseConsumptionPower = .1.3.6.1.2.1.105.1.3.1.1.3 (index = pethPsePortGroupIndex)
```

There is:
- pethPsePortGroupIndex (This variable uniquely identifies the group containing the port to which a power Ethernet PSE is
connected. Group means box in the stack, module in a rack and the value 1 MUST be used for non-modular devices.). 
- pethPsePortIndex (This variable uniquely identifies the power Ethernet PSE port within group pethPsePortGroupIndex to which the power Ethernet PSE entry is connected) : it looks like the ifIndex.

We don't have the consumption by port with the standard mib (only for the group).

On procurve mib, we have:
```
hpicfPoePethPsePortActualPower  = This field specifies the actual power drained by the device connected to this port.
hpicfPoePethPsePortOperStatus = deny(1), off(2), on(3)
```

We can assume that the pethPsePortIndex = ifIndex. So i can add a specific --add-poe option for hp procurve interfaces with:
- poe-status = on/off/deny
- poe-power = actual power drained by the device connected to this port

What do you think ?

**Comment by garnier-quentin** [comment]
You can test it with last version:
https://github.com/centreon/centreon-plugins/commit/ec287a7835ad5429e905f47aa2b5db2949a0e8e9

Maybe you'll need to wait that the cache reload.

**Comment by Cynexxde** [comment]
I am not the one who opened this thread, but I would wish that the Total Power Drawn and the Total Power Reserved 
of the whole system are given as performance data. 

Additionally the following features would be cool:

- Warning when the Total Failover Pwr Avl is exceeded. (This value is only available for switches with two power supplies.
- Warning/Critical at user defined threshold in % (Example: Warning Poe utilization above 80% of Total Available Power).

**Comment by garnier-quentin** [comment]
It's that OID hpicfPoeRemainingGuaranteedPower (This field specifies the Remaining Guaranteed  power. This is difference of Guaranteed Maximum PoE  Power and the sum of maximum power of critical PSEs. In watt) ? I'm not sure it's decreasing

**Comment by Cynexxde** [comment]
The OID 1.3.6.1.4.1.11.2.14.11.1.9.1.10 returns the following:
.1.3.6.1.4.1.11.2.14.11.1.9.1.10.0 = INTEGER: 1440

From this system:
![image](https://user-images.githubusercontent.com/88704661/145216978-144aca29-c52b-4980-934f-b89e34a140cc.png)

snmpwalk -Cc -v3 -l -ObentU 10.60.16.234 1.3.6.1.4.1.11.2.14.11.1.9.1

Extract from the walk:
```
.1.3.6.1.4.1.11.2.14.11.1.9.1.6.1.1.1001 = INTEGER: 2
.1.3.6.1.4.1.11.2.14.11.1.9.1.6.1.2.1001 = INTEGER: 1
.1.3.6.1.4.1.11.2.14.11.1.9.1.6.1.4.1001 = INTEGER: 1440
.1.3.6.1.4.1.11.2.14.11.1.9.1.6.1.5.1001 = INTEGER: 197
.1.3.6.1.4.1.11.2.14.11.1.9.1.6.1.6.1001 = INTEGER: 740
.1.3.6.1.4.1.11.2.14.11.1.9.1.6.1.7.1001 = INTEGER: 0
.1.3.6.1.4.1.11.2.14.11.1.9.1.6.1.8.1001 = INTEGER: 179
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.1.14001 = INTEGER: 1
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.1.14002 = INTEGER: 1
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.2.14001 = INTEGER: 2
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.2.14002 = INTEGER: 2
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.3.14001 = INTEGER: 740
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.3.14002 = INTEGER: 740
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.4.14001 = INTEGER: 0
.1.3.6.1.4.1.11.2.14.11.1.9.1.7.1.4.14002 = INTEGER: 0
```

**Comment by garnier-quentin** [comment]
Ok i see. It's in the following table: hpicfPseFeaturesTable. It's for the equipment. I don't know if we should add it in the interface mode.

**Comment by Cynexxde** [comment]
Yes ,it would probably be better placed in the system mode.

**Comment by joschi99** [comment]
Have done a test, but not sure if it's working correctly. No poe metrics are returned and no error will be raised:
```
./centreon_plugins.pl --hostname=x.x.x.x --snmp-community='public' --snmp-version=2c --snmp-username= --snmp-timeout= --authpassphrase= --authprotocol= --privpassphrase= --privprotocol= --plugin=network::hp::procurve::snmp::plugin --mode=interfaces --interface='50' --name --add-traffic --add-errors --add-status --speed= --speed-in= --speed-out= --units-traffic=% --units-errors=% --oid-display=ifName --warning-in-discard=0 --warning-out-discard=0 --warning-in-error=0 --warning-out-error=0 --warning-in-traffic=80 --warning-out-traffic=80 --critical-in-discard=10 --critical-out-discard=10 --critical-in-error=10 --critical-out-error=10 --critical-in-traffic=90 --critical-out-traffic=90 --add-poe --verbose --critical-poe-status='%{poestatus} ne "deliveringPower"'
OK: Interface '50' Status : up (admin: up), Traffic In : 73.92Mb/s (7.39%), Traffic Out : 7.01Mb/s (0.70%), Packets In Discard : 0.00% (0 on 644707), Packets In Error : 0.00% (0 on 644707), Packets Out Discard : 0.00% (0 on 365406), Packets Out Error : 0.00% (0 on 365406) | 'traffic_in'=73918990.97b/s;0:800000000;0:900000000;0;1000000000 'traffic_out'=7011378.85b/s;0:800000000;0:900000000;0;1000000000 'packets_discard_in'=0.00%;0:0;0:10;0;100 'packets_error_in'=0.00%;0:0;0:10;0;100 'packets_discard_out'=0.00%;0:0;0:10;0;100 'packets_error_out'=0.00%;0:0;0:10;0;100
Interface '50' Status : up (admin: up), Traffic In : 73.92Mb/s (7.39%), Traffic Out : 7.01Mb/s (0.70%), Packets In Discard : 0.00% (0 on 644707), Packets In Error : 0.00% (0 on 644707), Packets Out Discard : 0.00% (0 on 365406), Packets Out Error : 0.00% (0 on 365406)

```
