### ISSUE TITLE
[apps::protocols::http::plugin] mode=json-content --lookup-perdatas-nagios='$.row[*][*]'

### ISSUE THREAD

**Issue by arnaudmichel31** [centreon/centreon-plugins#3182]
Hello, 

I use json-content plugins to analyze this kind of json
{ "rows" : [[URL1statuscode=200],[URL2statuscode=200],[URL3statuscode=403]]}

I want to convert this json in perfdata.

with --lookup-perdatas-nagios='$.row[*][*]' I always retrieve only the first value.

OK: JSON webservice request success | 'time'=0.104s;;;0; 'URL1statuscode'=200;;;;

and I want 

OK: JSON webservice request success | 'time'=0.104s;;;0; 'URL1statuscode'=200;;;; 'URL2statuscode'=200;;;; 'URL3statuscode'=403;;;;

It seems that there is an issue line 299 of jsoncontent.pm
$perfdata_string = $jpath->value($self->{json_response_decoded});
should be
@perfdata_string = $jpath->values($self->{json_response_decoded});

It doesn't make sense to suggest --lookup-perdatas-nagios='$.row[*][*]' json structure with a string to receive the json array

Thanks in advance for your help

**Comment by garnier-quentin** [comment]
Please use the collection mode:
https://github.com/centreon/centreon-plugins/pull/3406
