### ISSUE TITLE
hardware::server::hp::proliant::snmp::plugin return OK: All 0 components are ok [].

### ISSUE THREAD

**Issue by chaimae-elmortajine** [centreon/centreon-plugins#3187]
Hello,

I use this plugin to monitor my raid on my server  hpe proliant dl160 gen10, but the command return me an erreur,
OK: All 0 components are ok []. |
> Product Name: unknown, Serial: unknown, Rom Version: unknown
i can't install the hpe insignt on windows server 2019, because we use now the ilo card.

Any -help

Thks

**Comment by garnier-quentin** [comment]
If you still have the issue, please comment it.
