### ISSUE TITLE
Solution to check certificat on keystore

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#3188]
Hi,

Do you have any solution to check certificat on keystore ?

Thanks,

**Comment by garnier-quentin** [comment]
No i don't (right now).

**Comment by garnier-quentin** [comment]
Have you tried the solution ?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old and was more a question than an issue with the plugin usage, so let me close it. If the question is still current, please address it [here](https://thewatch.centreon.com/data-collection-6).
Thank you for your understanding.
