### ISSUE TITLE
Installation Step by Step?

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#319]
I'm trying to install centreon-plugins using as reference: https://documentation.centreon.com/docs/centreon-plugins/en/latest/user/guide.html#installation

But after this:
1. 
```
# yum install git
# git clone https://github.com/centreon/centreon-plugins.git
```

2.
`# yum install perl net-snmp-perl`

3.
`# yum install perl-XML-LibXML perl-JSON perl-libwww-perl perl-XML-XPath perl-Net-Telnet perl-Net-DNS perl-DBI perl-DBD-MySQL perl-DBD-Pg`

What next? I put the files in /usr/lib/nagios/plugins/ ?
Need to create all the commands that I need manually in Configuration\Command?

Thank you for your patience.

**Comment by Sims24** [comment]
Hi, 

Yes, you should move everything under centreon-plugins directory in your /usr/lib/nagios/plugins dir and then : 

chmod +x /usr/lib/nagios/plugins/centreon_plugins.pl

yes, you need to create all the command in the configuration > commands menu. 

Regards

**Comment by CFRR** [comment]
Sims24, thanks for the quick response.

**Comment by Sims24** [comment]
You're welcome :)

Thanks for using !

**Comment by CFRR** [comment]
all files are as root:root, need to changed?

**Comment by Sims24** [comment]
If modes are 644, it should be ok

**Comment by alexandierg** [comment]
Hello,

Please, if you can help me, follow the steps to install but it downloads a folder with several files but no .pl

What am I doing wrong?

![image](https://user-images.githubusercontent.com/125747682/219871609-0cdcad03-ab5c-4c5e-8081-9b065fdbb120.png)
