### ISSUE TITLE
network::cisco::asa::snmp::plugin mode ipsec-tunnel very slow 

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#3194]
Hello, 

I have an issue with checking ipsec tunnels on ASA firewall.
On cli the check is very slow, it takes 2min at least to show results.
On UI it gives 'process timeout even if i set --snmp-timeout=180

Can you help understand what is the problem ?

I am running the latest version:
/usr/lib/centreon/plugins/centreon_cisco_asa_snmp.pl --version
Global Version: 20201006 (29c370409)

Command is:

/centreon_cisco_asa_snmp.pl --plugin=network::cisco::asa::snmp::plugin --mode=ipsec-tunnel --hostname='ASA' --snmp-version='2c' --snmp-community='public'  --filter-counters='' --filter-name='tunnel' --filter-sa='' --warning-tunnels-total='' --critical-tunnels-total='' --verbose

thank you

**Comment by saharawolf** [comment]
Hi

ASA version is 9.14.2.15

it is not better with --subsetleef=20

**Comment by Sims24** [comment]
Seems pretty similar to https://github.com/centreon/centreon-plugins/issues/2096 

If getting tunnel takes up to 5 seconds, then it may take a lot of time to get all other information (status, traffic in/out) for each of it. 

If you can track a bug on Cisco's side, it could help.

**Comment by saharawolf** [comment]
yes it is similar but on my side, the check from cli returns the results after 2 min

**Comment by garnier-quentin** [comment]
So it goes through that OID. I need to optimize it
