### ISSUE TITLE
Plugin storage::nimble::restapi - unit of measure

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#3197]
Hi,

I have a doubt about the unit of measurement for milliseconds on latency.
The values I have in the Nimbre web interface are 1000 times lower.

Ex here : read_latency": 403 > Your plugin write 403ms. In fact, in think, it's 0.403 ms.
Could you check this on Nimble documentation ? I don't find this information.

Thanks.

			"avg_stats_last_5mins": {
				"combined_iops": 374,
				"combined_latency": 94,
				"combined_throughput": 4975613,
				"read_iops": 30,
				"read_latency": 403,
				"read_throughput": 639023,
				"write_iops": 342,
				"write_latency": 93,
				"write_throughput": 4336587

**Comment by romsworld** [comment]
Hi,
Yes, I will open a ticket.

**Comment by garnier-quentin** [comment]
It should be fixed in last version:
https://github.com/centreon/centreon-plugins/pull/3308
