### ISSUE TITLE
apps::protocols::http::plugin json-content 

### ISSUE THREAD

**Issue by arnaudmichel31** [centreon/centreon-plugins#3198]
Hello, 

I have an issue with this kind of request :

/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=json-content --hostname=elk --proto='https' --port='XXX' --credentials --username=XXX --password=XXX --urlpath='/_xpack/sql?format=json' --header='Content-Type: application/json' --data='{"query":"  SELECT  max(messages_total) FROM XXXX"}' --lookup='$.rows[0][0]' --threshold-value='values' --format-ok='|%{values}| elements %{count}' --format-warning='%{values} elements' --format-critical='%{values} elements'  --warning-numeric='' --critical-numeric='' --warning-string='' --critical-string='' --change-perfdata=element_1,messages_total  --filter-perfdata='messages_total'

When I don't have any data returned, I was expecting Unknown status, instead, I have
Use of uninitialized value $value in concatenation (.) or string at /usr/lib/centreon/plugins/centreon_protocol_http.pl line 587.
Use of uninitialized value $value in pattern match (m//) at /usr/lib/centreon/plugins/centreon_protocol_http.pl line 615.
Use of uninitialized value in join or string at /usr/lib/centreon/plugins/centreon_protocol_http.pl line 542.
OK: || elements 1 |

Could you help me please.

Regards

**Comment by garnier-quentin** [comment]
Please could you use the last version ? (because i need lines information to be correct). Could you provide also a --debug ? (to get the json)
