### ISSUE TITLE
Rubrik API token

### ISSUE THREAD

**Issue by cmertz-sop** [centreon/centreon-plugins#3217]
Hi,

Rubrik is enforcing MFA for Rubrik local account. It would be intersteting to add API Token support instead of username and password.

Best regards,

**Comment by garnier-quentin** [comment]
Could you test with that archive ? https://github.com/centreon/centreon-plugins/archive/refs/heads/enh-rubrik-add-auth-token.zip

You have an option --token

**Comment by cmertz-sop** [comment]
I was able to successfully test the plugin with the --token option

De : qgarnier ***@***.***>
Envoyé : lundi 8 novembre 2021 09:43
À : centreon/centreon-plugins ***@***.***>
Cc : Cyrille MERTZ ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] Rubrik API token (Issue #3217)


Could you test with that archive ? https://github.com/centreon/centreon-plugins/archive/refs/heads/enh-rubrik-add-auth-token.zip<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcentreon%2Fcentreon-plugins%2Farchive%2Frefs%2Fheads%2Fenh-rubrik-add-auth-token.zip&data=04%7C01%7C%7C650dfef80df749db18f908d9a293c869%7Cd847080b33824b27886012fe4d8edb27%7C1%7C0%7C637719580997664518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D534veVa8%2FC7dcv3DbolmLsc9aB3dm55MyTTiwPdvP8%3D&reserved=0>

You have an option --token

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcentreon%2Fcentreon-plugins%2Fissues%2F3217%23issuecomment-962928370&data=04%7C01%7C%7C650dfef80df749db18f908d9a293c869%7Cd847080b33824b27886012fe4d8edb27%7C1%7C0%7C637719580997674461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8wlCAM0Jx50YP%2FFAJMRuWvojFVAoSzwKNEeEJ3IAPn8%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPJMY7AY4QSIOLGO6YRDX3DUK6ERHANCNFSM5GQV7ERA&data=04%7C01%7C%7C650dfef80df749db18f908d9a293c869%7Cd847080b33824b27886012fe4d8edb27%7C1%7C0%7C637719580997684421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AcimII4HrAfhLXEMVOUfemN9kdrLG9YWdTL%2FOzJxbJ4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C650dfef80df749db18f908d9a293c869%7Cd847080b33824b27886012fe4d8edb27%7C1%7C0%7C637719580997684421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wYvREu%2BfUbIIYX6SI0NfTqDHvg1GUcE1Y5sVCPUtQOQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C650dfef80df749db18f908d9a293c869%7Cd847080b33824b27886012fe4d8edb27%7C1%7C0%7C637719580997694377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QYbFkS5z7E2Z34%2FfgwQWOWh87PiwuUDpO63gtvDhaJs%3D&reserved=0>.
