### ISSUE TITLE
[plugin] Check Point Interfaces Check/Taffic?

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#322]
I'm trying monitoring Check Point Interfaces, and by the suggestion of this post: [](https://github.com/centreon/centreon-plugins/issues/166), I use plugin=os::linux::snmp::plugin --mode=list-interfaces and the result is:
```
List interfaces:
'lo' [speed = 10, status = up, id = 1]
'eth0' [speed = 4294.97, status = up, id = 2]
'eth1' [speed = 4294.97, status = up, id = 3]
'eth2' [speed = 4294.97, status = up, id = 4]
'eth5' [speed = 4294.97, status = down, id = 5]
'eth3' [speed = 4294.97, status = up, id = 6]
'eth6' [speed = 4294.97, status = up, id = 7]
'eth4' [speed = 4294.97, status = up, id = 8]
```
And in Centreon UI:
Status information 	
List interfaces:
Extended status information 	
lo [speed = 10, status = up, id = 1]
eth0 [speed = 4294.97, status = up, id = 2]
eth1 [speed = 4294.97, status = up, id = 3]
eth2 [speed = 4294.97, status = up, id = 4]
eth5 [speed = 4294.97, status = down, id = 5]
eth3 [speed = 4294.97, status = up, id = 6]
eth6 [speed = 4294.97, status = up, id = 7]
eth4 [speed = 4294.97, status = up, id = 8]

Performance Data 	(n/a)

And have only 1 graph with ok, warning, critical, unknown.
How is it is possible to have a graphi for each interface with traffic information?

**Comment by garnier-quentin** [comment]
You can see the available options with --help. I think you want to use: --add-traffic --add-errors, ...

**Comment by CFRR** [comment]
garnier-quentin, something like this?
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=list-interfaces --hostname=<IP> --snmp-version=1 --snmp-community=<COMM> --add-traffic ??

**Comment by garnier-quentin** [comment]
Not for --list-interfaces. For --mode=interfaces

**Comment by CFRR** [comment]
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname= --snmp-version=1 --snmp-community= --add-traffic --add-errors
OK: All interfaces are ok

Should not the output have values?

**Comment by garnier-quentin** [comment]
Use --verbose and launch it again (need to create a cache first).

**Comment by CFRR** [comment]
garnier-quentin, wonderful, working!

one more question please, where I can list all option, like --add-traffic, --add-errors, etc?

**Comment by garnier-quentin** [comment]
With the option --help.

**Comment by CFRR** [comment]
Like this "perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --help" ??

I recreate the service, but I getting the following error: 
Status information 	
UNKNOWN: Cannot write statefile /var/lib/centreon/centplugins/cache_snmpstandard_192.168.254.2_161_interfaces. Need write permissions on file

**Comment by garnier-quentin** [comment]
Look the file permissions. Or you can remove it.

**Comment by CFRR** [comment]
Yes problem solve, I delete the file.
Sorry for my dummy questions, this is first time that I install a "nagios" based system, I was more a Cacti user. :) 


To clarify, I need to put the `--verbose` parameter for Performance Data

**Comment by garnier-quentin** [comment]
No problem. Welcome ;) --verbose it's for the long output.

**Comment by CFRR** [comment]
is possible a graph per interface?

**Comment by garnier-quentin** [comment]
You need to create X services for that. It's more a centreonn-web issue and graph configuration.

**Comment by CFRR** [comment]
ok, for monitoring switchs is will be fun! ;D

**Comment by CFRR** [comment]
I'm trying do the following, filter for interface name (--name): 
```
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname= --snmp-version=2 --snmp-community= --mode=interfaces --add-traffic --name "eth2"
OK: All interfaces are ok | 'traffic_in_lo'=3191.27b/s;;;0;10000000 'traffic_out_lo'=3191.27b/s;;;0;10000000 'traffic_in_eth2'=1854238.55b/s;;;0;10000000000 'traffic_out_eth2'=239868.12b/s;;;0;10000000000 'traffic_in_eth3'=9254.06b/s;;;0;10000000000 'traffic_out_eth3'=9236.36b/s;;;0;10000000000 'traffic_in_eth6'=244602.42b/s;;;0;10000000000 'traffic_out_eth6'=1898065.21b/s;;;0;10000000000
```
But I getting all interfaces.

By using parameter --interface and interface ID works:
```
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname= --snmp-version=2 --snmp-community= --mode=interfaces --add-traffic --interface 4
OK: Interface 'eth2' Traffic In : 2.93Mb/s (0.03%), Traffic Out : 1.17Mb/s (0.01%) | 'traffic_in'=2927976.00b/s;;;0;10000000000 'traffic_out'=1173080.00b/s;;;0;10000000000
``

**Comment by garnier-quentin** [comment]
```
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname= --snmp-version=2 --snmp-community= --mode=interfaces --add-traffic --interface="eth2" --name
```

**Comment by CFRR** [comment]
thank you, I miss understood the help
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname= --snmp-version=2 --snmp-community= --mode=interfaces --add-traffic --interface="eth2" --name
OK: Interface 'eth2' Traffic In : 1.14Mb/s (0.01%), Traffic Out : 205.86Kb/s (0.00%) | 'traffic_in'=1143548.80b/s;;;0;10000000000 'traffic_out'=205863.20b/s;;;0;10000000000

**Comment by CFRR** [comment]
is possible combine  --oid-display=ifAlias and --oid-display=ifName ?
