### ISSUE TITLE
[plugin=network::juniper::ex::plugin] Strange value

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#3223]
Hello,

I have strange value with --plugin=network::juniper::ex::plugin plugin.

'ae1.0' [speed = 4294.97][status = up][id = 577][type = propVirtual]
CRITICAL: Interface 'ae1.0' [  ] Traffic In : 926083.14Tb/s (3086943815.10%), Traffic Out : 950591.50Tb/s (3168638330.77%) 

Did I forget something ?

Thanks,

**Comment by garnier-quentin** [comment]
Do you have some news ?

**Comment by romsworld** [comment]
Hi,

Not yet, i need time 😊

**Comment by garnier-quentin** [comment]
Do you have some news @romsworld ?

**Comment by garnier-quentin** [comment]
Have you done some test ?

**Comment by garnier-quentin** [comment]
If you have the response of your support, you can comment it
