### ISSUE TITLE
[network::fortinet::fortimanager::snmp::plugin::device-status] create PolicyPackageState

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3225]
Hi,

The 'policy package status' is not verified.
This corresponds to the oid:  .1.3.6.1.4.1.12356.103.6.2.1.23
The different values ​​I see are:
[installed]
[unknown]
[imported]
[conflict]

I send you the snmpwalk by mail.

Regards.

**Comment by gagzou** [comment]
[FORTINET-FORTIMANAGER-FORTIANALYZER-MIB.txt](https://github.com/centreon/centreon-plugins/files/7454267/FORTINET-FORTIMANAGER-FORTIANALYZER-MIB.txt)

**Comment by garnier-quentin** [comment]
I need a full snmpwalk also.

**Comment by gagzou** [comment]
the full snmpwalk file is sent by mail

**Comment by garnier-quentin** [comment]
You can test in last version with: ```--critical-device-policy-package-status='%{status} =~ /conflict/'```

**Comment by gagzou** [comment]
Hi, 
I updated centreon (20.10.13) and plugin (centreon-pack-network-fortinet-fortimanager-snmp-3.2.0-1.el7.centos.noarch) but no option 'critical-device-policy-package-status'.
# grep policy-package /usr/lib/centreon/plugins//centreon_fortinet_fortimanager_snmp.pl
#

**Comment by gagzou** [comment]
I tested, it's ok :+1: 
--warning-device-policy-package-status='%{status} =~ /unknown/i' 
and 
--critical-device-policy-package-status='%{status} =~ /conflict/i'
Thanks
