### ISSUE TITLE
[bug]network::cisco::wap::snmp::plugin - Wrong command line in Net-Cisco-Wap-SNMP-Clients checks

### ISSUE THREAD

**Issue by FranckLANTZ** [centreon/centreon-plugins#3229]
Hi,

Try to use this plugin and realize there's a problem with the client mode of network::cisco::wap::snmp::plugin. The command line used is :
```
$CENTREONPLUGINS$/centreon_cisco_wap_snmp
.pl --plugin=network::cisco::wap::snmp::plugin --mode=clients --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --filter-radio-name='$_SERVICEFILTERRADIONAME$'--warning-clients-connected='$_SERVICEWARNINGCLIENTSCONNECTED$' --critical-clients-connected='$_SERVICECRITICALCLIENTSCONNECTED$' --warning-radio-clients-connected='$_SERVICEWARNINGRADIOCLIENTSCONNECTED$' --critical-radio-clients-connected='$_SERVICECRITICALRADIOCLIENTSCONNECTED$' $_SERVICEEXTRAOPTIONS$
```
Certainly a return carriage (or a space) between centreon_cisco_wap_snmp and .pl in Net-Cisco-Wap-SNMP-Clients Checks.

The output show Execute command failed.

Can you fix this ? Thank you.

**Comment by garnier-quentin** [comment]
It shoud be fixed and released yesterday.

**Comment by FranckLANTZ** [comment]
I update the central-poller today and got this version `centreon-plugin-Network-Cisco-Wap-Snmp-20211102-130335.el8.noarch` of the plugin.
But don't see any changes in the command line ?

**Comment by garnier-quentin** [comment]
It's not the plugin the issue. It's the pack

**Comment by garnier-quentin** [comment]
We have an issue with stable repositories (we are going to fix it). Thanks for the feedback!
