### ISSUE TITLE
apps::protocols::snmp::plugin with json (through mode string-value) and Date

### ISSUE THREAD

**Issue by brice-glf** [centreon/centreon-plugins#3231]
Hi,

I'm tring to monitor the expiration_date for the Wallix software's license through SNMP.

First, here is the snmpwalk:
```
# snmpwalk -v3 -l authPriv -u wabsnmp -a SHA -A "xxx" -x AES -X "xxxx" -On 10.10.10.10 .1.3.6.1.4.1.30373.1.5.0
.1.3.6.1.4.1.30373.1.5.0 = STRING: "{\"resource_max\": 350, \"primary\": 1, \"waapm\": 0, \"externvault_enabled\": false, \"secondary_max\": 35, \"siem_enabled\": true, \"secondary\": 1, \"evaluation\": false, \"resource\": 264, \"session_manager\": true, \"expiration_date\": \"2022-01-04\", \"waapm_max\": 0, \"primary_max\": 35, \"password_manager\": true, \"enterprise\": true, \"is_expired\": false}
"
```

As we can see, the answer is in json format. Per my knownledge, there is no json mode for SNMP so I try with  **--mode=string-value**
Then I tried to play around with **--convert-custom-values** argument but I didn't understand how this works and can't find enough examples to help me.

Here is what I would like to achieve
1.need to extract the expiration_date (something like **--convert-custom-values='decode_json($value)->{expiration_date}'**   )
2.compare it with current time (**--use-perl-mod='Date::Parse' --convert-custom-values='time-(Date::Parse::str2time($value.expiration_date))'** taken from there: https://github.com/centreon/centreon-plugins/issues/2902  )

Can you help ?

**Comment by garnier-quentin** [comment]
Maybe we can add something in collection mode.

**Comment by brice-glf** [comment]
Thanks Quentin for feedback. Looks too complex for me to develop a specific mode. Don't you think I can achieve something with currently available options like I tried?

**Comment by garnier-quentin** [comment]
I don't think so. And in a short time, i think i will remove ```--use-perl-mod``` and ```--convert-custom-values``` because of security reason.

**Comment by brice-glf** [comment]
Ok thanks for info & your time. 
Then I will write an ugly simple shell script for this simple requirement!
