### ISSUE TITLE
os::linux::local::plugin mode storage issue with perfdata and free values

### ISSUE THREAD

**Issue by mullergg** [centreon/centreon-plugins#3236]
## Bug/Question
Hello,
I use the plugin os::linux::local::plugin to monitor my Linux Redhat servers.
My version is 20210113
I notice two issues.
The mode to get storage seems to have a bug with the Free values and with the perfdat when using in B
This is the command I ran :
 ```
./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=storage --filter-mountpoint=/elastic_infra --warning-usage=90 --critical-usage=95 --hostname=x.x.x.x --ssh-username=xxxxxx --ssh-priv-key --debug
```
And it return this

```
WARNING: Storage '/elastic_infra' Usage Total: 946.78 GB Used: 859.64 GB (90.80%) Free: 87.14 GB (9.20%) | 'used'=923028713472B;0:914933875507;0:965763535257;0;1016593195008
```
This is the df result:
```
Filesystem                           Type     1024-blocks      Used Available Capacity Mounted on
/dev/mapper/rootvg-lvelasticinfra    ext4       992766792 901395228  49727588      95% /elastic_infra
```
The values Usage Total and Used are correct, but not the value free, because it didn't count the Reserved block count from the FS.
Why don't use the value return by df ?

The second issue as you can see, the values in the perfdata output is wrong because of a conversion. It seems that the value get by df is multiply by 1024 while the value is already in bytes.

When I use the fonction to convert the perfdata the value is correct:
```
./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=storage --filter-mountpoint=/elastic_infra --warning-usage=90 --critical-usage=95 --hostname=x.x.x.x --ssh-username=xxxxxx--ssh-priv-key --debug --change-perfdata='(used|total),,scale(GB)'
OK: Storage '/elastic_infra' Usage Total: 946.78 GB Used: 851.91 GB (89.98%) Free: 94.86 GB (10.02%) | 'used'=851.91GB;0:852.098572540097;0:899.437382125296;0;946.78
```

**Comment by garnier-quentin** [comment]
We use the df command: ```df -P -k -T```

**Comment by mullergg** [comment]
Yes, I know this output is the result of passing the check with the option --debug
```
Filesystem                           Type     1024-blocks      Used Available Capacity Mounted on
/dev/mapper/rootvg-lvelasticinfra    ext4       992766792 901395228  49727588      95% /elastic_infra
```
And for me 992766792 Total is different than 1016593195008 in the total in perfdata
Also 49727588 available is different than 94.86 GB (10.02%)

THe 94Gb come from Total - Used and it is different than the value get from df.

**Comment by garnier-quentin** [comment]
Which version do you use ? Because i use the available

**Comment by mullergg** [comment]
> My version is 20210113

**Comment by mullergg** [comment]
I've download the latest release centreon-plugins-20210915
I still have the issue :
```
[centreon-engine@lashsmui centreon-plugins-20210915]$ ./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=storage --filter-mountpoint=/elastic_infra --warning-usage=90 --critical-usage=95 --hostname=x.x.x.x --ssh-username=xxxxxx --ssh-priv-key --debug --explode-perfdata-max
OK: Storage '/elastic_infra' Usage Total: 946.78 GB Used: 463.34 GB (51.08%) Free: 443.72 GB (48.92%) | 'used'=497507508224B;0:914933875507;0:965763535257;0;1016593195008 'used_max'=1016593195008B;;;;
```

**Comment by garnier-quentin** [comment]
It changes a lot. And could you provide the ```df -P -k -T``` ?

**Comment by mullergg** [comment]
```
[xxxx@xxxxxx ~]# df -P -k -T
Filesystem                           Type     1024-blocks      Used Available Capacity Mounted on
/dev/mapper/rootvg-lvelasticinfra    ext4       992766792 486260772 464862044      52% /elastic_infra
```
With the script in debug I got the same value.
Apparently there is something that make :

992766792  * 1024 which is wrong.

**Comment by garnier-quentin** [comment]
The available is: ```464862044 (KB) / 1024 / 1024 = 443GB```

**Comment by mullergg** [comment]
On the value return in the output i'm ok.
But look at the perfdata, there is something wrong:

'used'=497507508224B;0:914933875507;0:965763535257;0;1016593195008 'used_max'=1016593195008B;;;;

**Comment by mullergg** [comment]
no the used_max is 1016593195008B

instead of :

992766792 from the df

**Comment by garnier-quentin** [comment]
The max is: 1016593195008. 992766792*1024=1016593195008

**Comment by garnier-quentin** [comment]
It changes a lot but for good ;)

**Comment by mullergg** [comment]
Thanks for your time :)
