### ISSUE TITLE
Enhancement: Alfresco Plugin

### ISSUE THREAD

**Issue by Iralein** [centreon/centreon-plugins#3244]
Hi all,

Alfresco uses Solr for indexing. If you don't want to use JMX for monitoring and want to use the solr admin websites, you can find aall informations on how to configure it in Centreon on https://hub.alfresco.com/t5/alfresco-premier-services-blog/solr-monitoring-using-nagios-and-alikes/ba-p/288217
It's a simple Python Script, provided by Alfresco which parses the xml-response of the website, so you do not need to setup JMX (and jolokia).
Maybe someone will translate it to perl and provide it as centreon plugin ?
Regards,

Iralein

**Comment by garnier-quentin** [comment]
Could you provide the curl commands and results ?

**Comment by Iralein** [comment]
URLs documented in https://github.com/alxgomz/nagios-plugin-alfresco-search-services/blob/master/check_alfresco_solr.py
Pls let me know if you need a raw xml from the alfresco solr.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md)).

Thank you for your understanding.
