### ISSUE TITLE
apps::protocols::ospf::snmp::plugin outputs "Use of uninitialized value"

### ISSUE THREAD

**Issue by Fuuzz** [centreon/centreon-plugins#3256]
Hi, I just installed and was testing the apps::protocols::ospf::snmp::plugin plugin, packet version is the following:

`centreon-plugin-Applications-Protocol-Ospf-20211102-130335.el7.centos.noarch`

And in the output I encountered the following message:

```
-bash-4.2$ ./centreon_protocol_ospf.pl --plugin=apps::protocols::ospf::snmp::plugin --mode=neighbor --hostname=1.2.3.4 --snmp-community=community --snmp-version=2c
Use of uninitialized value in concatenation (.) or string at ./centreon_protocol_ospf.pl line 61.
Use of uninitialized value in concatenation (.) or string at ./centreon_protocol_ospf.pl line 61.
OK: Total neighbors : 2 - Neighbors current : 2 (last : 2) - All neighbor relations are ok | 'total'=2;;;0;
```

The interested line and block of code from the plugin is the following:

```
  58   sub prefix_nb_output {
  59       my ($self, %options) = @_;
  60
  61       return "Neighbor '" . $options{instance_value}->{NbrIpAddr} . "/" . $options{instance_value}->{NbrRtrId} . "' ";
  62   }
```

I'd like to avoid adding unnecessary output filters, can you check why that message is returned?
Thank you :)

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk of following branch: .1.3.6.1.2.1.14.10.1 ?

**Comment by Fuuzz** [comment]
Hi, here's the snmpwalk output:

-bash-4.2$ snmpwalk -v 2c -c community 1.2.3.4 .1.3.6.1.2.1.14.10.1
OSPF-MIB::ospfNbrAddressLessIndex.10.72.254.113.0 = INTEGER: 0
OSPF-MIB::ospfNbrAddressLessIndex.10.72.254.117.0 = INTEGER: 0
OSPF-MIB::ospfNbrRtrId.10.72.254.113.0 = IpAddress: 10.213.255.12
OSPF-MIB::ospfNbrRtrId.10.72.254.117.0 = IpAddress: 10.213.255.13
OSPF-MIB::ospfNbrOptions.10.72.254.113.0 = INTEGER: 2
OSPF-MIB::ospfNbrOptions.10.72.254.117.0 = INTEGER: 2
OSPF-MIB::ospfNbrPriority.10.72.254.113.0 = INTEGER: 1
OSPF-MIB::ospfNbrPriority.10.72.254.117.0 = INTEGER: 1
OSPF-MIB::ospfNbrState.10.72.254.113.0 = INTEGER: full(8)
OSPF-MIB::ospfNbrState.10.72.254.117.0 = INTEGER: full(8)
OSPF-MIB::ospfNbrEvents.10.72.254.113.0 = Counter32: 5
OSPF-MIB::ospfNbrEvents.10.72.254.117.0 = Counter32: 4
OSPF-MIB::ospfNbrLsRetransQLen.10.72.254.113.0 = Gauge32: 0
OSPF-MIB::ospfNbrLsRetransQLen.10.72.254.117.0 = Gauge32: 0
OSPF-MIB::ospfNbmaNbrStatus.10.72.254.113.0 = INTEGER: active(1)
OSPF-MIB::ospfNbmaNbrStatus.10.72.254.117.0 = INTEGER: active(1)
OSPF-MIB::ospfNbmaNbrPermanence.10.72.254.113.0 = INTEGER: dynamic(1)
OSPF-MIB::ospfNbmaNbrPermanence.10.72.254.117.0 = INTEGER: dynamic(1)
OSPF-MIB::ospfNbrHelloSuppressed.10.72.254.113.0 = INTEGER: false(2)
OSPF-MIB::ospfNbrHelloSuppressed.10.72.254.117.0 = INTEGER: false(2)
OSPF-MIB::ospfNbrRestartHelperStatus.10.72.254.113.0 = INTEGER: notHelping(1)
OSPF-MIB::ospfNbrRestartHelperStatus.10.72.254.117.0 = INTEGER: notHelping(1)
OSPF-MIB::ospfNbrRestartHelperAge.10.72.254.113.0 = Gauge32: 0 seconds
OSPF-MIB::ospfNbrRestartHelperAge.10.72.254.117.0 = Gauge32: 0 seconds
OSPF-MIB::ospfNbrRestartHelperExitReason.10.72.254.113.0 = INTEGER: none(1)
OSPF-MIB::ospfNbrRestartHelperExitReason.10.72.254.117.0 = INTEGER: none(1)

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by Fuuzz** [comment]
Hi, last version of what? If you mean of the package, I think it's already the latest version available:

yum --showduplicates list centreon-plugin-Applications-Protocol-Ospf
Loaded plugins: enabled_repos_upload, package_upload, product-id, search-disabled-repos, subscription-manager, tracer_upload
```
Installed Packages
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20211102-130335.el7.centos                                                     @centreon-stable-noarch
Available Packages
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20200410-101650.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20200602-094050.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20200803-072952.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20201006-142255.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20201211-091649.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20210113-100416.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20210218-084020.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20210317-091111.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20210421-093317.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20210519-141023.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20210622-151444.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20210915-070550.el7.centos                                                     centreon-stable-noarch
centreon-plugin-Applications-Protocol-Ospf.noarch                                                    20211102-130335.el7.centos                                                     centreon-stable-noarch
Uploading Enabled Repositories Report
```

**Comment by garnier-quentin** [comment]
It will be available on the unstable repository. You can also test it with the last git
