### ISSUE TITLE
[apps::selenium] : adding perfdatas for every steps

### ISSUE THREAD

**Issue by highfeeling** [centreon/centreon-plugins#326]
Hello dev team,

I guess it should be a great enhancement to add perfdatas when wanted, on every steps of a selenium scenario.

In an optional way, maybe using a new mode called "scenario-details", or "scenario-debug"

Highfeeling

**Comment by garnier-quentin** [comment]
Yes. But how could you do that ? If we set it for each steps, that makes a lot. Need to think about a way.

**Comment by highfeeling** [comment]
Some monthes ago, Eric Cocquard published this article : 

http://www.sugarbug.web4me.fr/atelier/techniques/monitoring_lan/supervision_site_web/plugin_waa/

in which he published a modified version of deprecated check_centreon_waa plugin

Is this article can help ?

Highfeeling

**Comment by garnier-quentin** [comment]
Not really. But maybe i can use xml comments for add some perfdatas.

**Comment by highfeeling** [comment]
the objective of this request is to able to identify quickly at what step there is a problem.

Imagine a scenario (based on 10 steps for example) which runs normally in 20 seconds

One day, this scenario runs now in more than one minute !

Then, it should be very interesting that this plugin expose clealy all the running time of all steps. That way, the admin can see immediately what is the step involved.

For sure, this enhancement may be hard to develop, but I guess i could be a real cool one !

Highfeeling

**Comment by garnier-quentin** [comment]
I can add an option to display perfdatas for each steps. Not difficult.

**Comment by highfeeling** [comment]
Really ?

Well ... that means I owe you one (several ?) beer !

Highfeeling

**Comment by garnier-quentin** [comment]
I always accept free beer :)

**Comment by highfeeling** [comment]
hehe ... 

are you on Paris ?

**Comment by cgagnaire** [comment]
What !?
I didn't know there were free beer to win!
You can do what you want using "katalon" mode (https://github.com/centreon/centreon-plugins/pull/1039)
