### ISSUE TITLE
[apps::monitoring::netdata::restapi::plugin]Monitor linux servers with netdata

### ISSUE THREAD

**Issue by mullergg** [centreon/centreon-plugins#3262]
## Bug/Question
Hello,
I'm working on a project to monitor my linux server with netdata agent instead of SSH.
I have the plugin version 20211102

So we have netdata installed on some servers with https enabled and it seems that we need to accept gzip encoding because they active compression to get all informations.
I've found this issue with netdata and found the solution in it:
https://github.com/netdata/netdata/issues/10886

The mode CPU is working fine, but then you try to check disk or inodes the request doesn't work.

I tried this:
./centreon_plugins.pl --plugin=apps::monitoring::netdata::restapi::plugin --hostname=xxxxxxxxx --mode=disks --proto=https

And get:
UNKNOWN: Cannot decode response (add --debug option to display returned content)

With debug enable, I found that the json response is truncated:

`  
======> request send
GET https://xxxxxxxxxxxxxx:19999/api/v1/charts  
                "disk_svctm.dm-2":              {
                        "id": "disk_svctm.dm-2",
                        "name": "disk_svctm.rootvg_lvapplilog",
                        "type": "disk_svctm",
                        "family": "rootvg-xxxxxxxxx",
                        "context": "disk.svctm",
                        "title": "Average Service Time (disk_svctm.rootvg_xxxxxxx)",
                        "priority": 2070,
                        "plugin": "proc.plugin",
                        "module": "/proc/diskstats",
                        "enabled": true,
                        "units": "milliseconds/operation",
                        "data_url": "/api/v1/data?chart=disk_svctm.rootvg_xxxxxxxx",
                        "chart_type": "line",
                        "duration": 1893836,
                        "first_entry": 1635433380,
                        "last_entry": 1637327215,
                        "update_every": 1,
                        "dimensi
`

I had to edit the http_backend to use curl and add curl-opt to accept encoding with this:

`
./centreon_plugins.pl --plugin=apps::monitoring::netdata::restapi::plugin --hostname=xxxxxxxxx --mode=disks --proto=https --http-backend=curl --curl-opt='CURLOPT_HTTPHEADER => [Accept-Encoding: gzip]' --curl-opt='CURLOPT_ACCEPT_ENCODING => 1'
`
Could you support encoding natively, maybe when proto=https ? 
Because it seems that netdata compress the result when we enable SSL.

**Comment by garnier-quentin** [comment]
it's more like a netdata bug. With the following option, if the content is not compressed, is it working ?

**Comment by mullergg** [comment]
We cannot disable compression with SSL enable it is mandatory for netdata.
I try on another server without ssl, and everything is fine with or without the curl-opt it also work with LWP.
Everything seems related to the netdata https configuration.

**Comment by Sims24** [comment]
Maybe you can try to add `--curl-opt="CURLOPT_ENCODING  => gzip"` as well?

**Comment by mullergg** [comment]
The last command I sent, works fine for me.
I suggested to support this option natively.

**Comment by Sims24** [comment]
Ok didn't get that. Does it work without --curl-opt='CURLOPT_ACCEPT_ENCODING => 1' ? (Is the header enough?)

**Comment by mullergg** [comment]
no, header isn't enough. 
If I put only the header the request works, but the content is compressed and isn't decoded.

**Comment by garnier-quentin** [comment]
I have tested with ssl on netdata v1.32.0-1-nightly and i don't have the issue. It's working

**Comment by mullergg** [comment]
I've updated one of my node and it work without the option.
It seems to be related to netdata, but I found nothing in the release note.
In the traffic mode I have an error but it works:

```
[root@xxx plugins]# ./centreon_plugins.pl --plugin=apps::monitoring::netdata::restapi::plugin --hostname=xxxxxx --mode=traffic --proto=https
Use of uninitialized value in multiplication (*) at /xxxxx/xxxxx/lib/centreon/plugins/apps/monitoring/netdata/restapi/mode/traffic.pm line 117.
OK: All interfaces are ok | 'docker0#network.traffic.in.bitspersecond'=0b/s;;;0;0 'docker0#network.traffic.out.bitspersecond'=0b/s;;;0;0 'eth0#network.traffic.in.bitspersecond'=418865b/s;;;0;10000000000000 'eth0#network.traffic.out.bitspersecond'=345779b/s;;;0;10000000000000
```

**Comment by garnier-quentin** [comment]
Could you provide a --debug for the traffic ? I will fix it

**Comment by mullergg** [comment]
Please find the file in attachment
[debug_netdata_plugin.txt](https://github.com/centreon/centreon-plugins/files/7632792/debug_netdata_plugin.txt)

**Comment by garnier-quentin** [comment]
Thanks. it's fixed in last version.

**Comment by mullergg** [comment]
Thanks for your quick response.
