### ISSUE TITLE
Add support for haproxy appliance  (Aloha)

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#327]
Hello,

is this possible to add some check for monitoring HAPROXY appliance  ?(http://www.haproxy.com/products/main-features-of-aloha-load-balancers/)

Haproxy release some documentation about MIBs : 

http://www.haproxy.com/static/media/uploads/eng/resources/aloha_load_balancer_appnotes_0056_aloha_monitoring_through_snmp_en.pdf

http://www.haproxy.com/download/aloha/mibs/

Best regards,

**Comment by garnier-quentin** [comment]
it can be done yes. Could you give me a complete snmpwalk ?

**Comment by garnier-quentin** [comment]
I see what it could be useful like:
* backend-usage
* frontend-usage

But i don't see what it's  'alInstanceTable' and 'alServiceTable' in haproxy ? Could you explain to me ? Thanks

**Comment by hdep** [comment]
Hello,

On my system alInstanceName report network interface name (eth0, eth1...) so seems network related.

For  alServiceTable reports  the process running on the aloha appliance and their status. Like lvs, crond daemon...

I hope this help.

**Comment by hdep** [comment]
One thing would be interesting, is to monitor the backend status Ie : to report warning mode if one node of a backend is down.
