### ISSUE TITLE
[network::paloalto::ssh::plugin] - libssh - sessions on PA remains open

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3278]
If we are monitoring PA using SSH with username and password using libssh every service login on the PA, but the session on PA will remain in status IDLE.
![image](https://user-images.githubusercontent.com/6400595/143551465-d07cd7f7-183a-4ab9-902d-3d8629fa2b44.png)
Is this a bug on libssh and could this happen on other services based on ssh/libssh?

If we do the same using plink the sessions are closed automatically, so the logout seems working. But plink need's to store for every new host the key:
`please connect with plink command to your host and accept the server host key`
is there any option for plink to disable this behavior?

**Comment by garnier-quentin** [comment]
It's weird. it should be disconnected. Could you provide the command ?

**Comment by joschi99** [comment]
`centreon_plugins.pl --hostname=x.x.x.x --ssh-backend=libssh --ssh-username=user --ssh-password='password' --ssh-priv-key='' --sshcli-option='' --plugin=network::paloalto::ssh::plugin --mode=ha`

**Comment by garnier-quentin** [comment]
I could not reproduce it. Could we do a session ?

**Comment by joschi99** [comment]
yes, we can :-)
I have this available slots:

- Dec 2, 9:00-10:00
- Dec 3, 11:00-12:30

**Comment by garnier-quentin** [comment]
Tomorrow is ok for me. I will send you an email (from github information)
