### ISSUE TITLE
Fortigate Hardware Get a specific component (like temperature)

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon-plugins#3281]
Hi, 

Unlike in other plugins, network::fortinet::fortigate::plugin cannot select a different component except sensors.
Is there anyway to get temperature only in this plugin? Sensors giving all the data but I want only temperature. (Have the latest plugins)

Command : 
/usr/lib/centreon/plugins-master/centreon_plugins.pl  --plugin network::fortinet::fortigate::plugin   --mode hardware  --hostname=xxx--snmp-version='3'  --snmp-username xxxx --authpassphrase 'xxxx'   --authprotocol SHA   --privpassphrase 'xxxx'   --privprotocol AES  --verbose  --add-name-instance --warning='sensors,Temp,40' --critical='sensors,Temp,50' 

Output : 
CRITICAL: Sensor 'RPS 12V' status is 'on' | '+3.3V#hardware.sensors.measure'=3.318;;;; '+5V#hardware.sensors.measure'=5.0725;;;; '+12V#hardware.sensors.measure'=12.195;;;; 'CPU VCCP#hardware.sensors.measure'=0.9805;;;; 'CPU VTT#hardware.sensors.measure'=1.0589;;;; 'CPU PVSA#hardware.sensors.measure'=0.9413;;;; 'P1V8#hardware.sensors.measure'=1.7841;;;; 'P1V5#hardware.sensors.measure'=1.5097;;;; 'PCH +1.05V#hardware.sensors.measure'=1.024;;;; 'VCC 2V5#hardware.sensors.measure'=2.432;;;; 'MAIN 12V#hardware.sensors.measure'=11.904;;;; 'VCC 1V15#hardware.sensors.measure'=1.136;;;; 'DDR3 VTT#hardware.sensors.measure'=0.736;;;; 'RPS 12V#hardware.sensors.measure'=0;;;; 'NCT +3.3V#hardware.sensors.measure'=3.216;;;; 'NCT VBAT#hardware.sensors.measure'=3.264;;;; 'NCT +3.3VSB#hardware.sensors.measure'=3.216;;;; 'NCT VTT#hardware.sensors.measure'=1.04;;;; 'DTS CPU#hardware.sensors.measure'=66;;;; 'CPU Core 0#hardware.sensors.measure'=63;;;; 'CPU Core 1#hardware.sensors.measure'=66;;;; 'TD1#hardware.sensors.measure'=41;;;; 'TD2#hardware.sensors.measure'=26;;;; 'FAN_TMP_3#hardware.sensors.measure'=40;;;; 'LM75 U72#hardware.sensors.measure'=32;;;; 'LM75 U65#hardware.sensors.measure'=37;;;; 'LM75 U62#hardware.sensors.measure'=37;;;; 'FAN1#hardware.sensors.measure'=5600;;;; 'FAN2#hardware.sensors.measure'=5600;;;; 'FAN3#hardware.sensors.measure'=5500;;;; 'hardware.sensors.count'=30;;;;
[System: MAS Ayathi] [Firmware: v6.4.5,build1828,210217 (GA)]
Checking sensors
sensor '+3.3V' status is 'off' [instance = 1] [value = 3.318]
sensor '+5V' status is 'off' [instance = 2] [value = 5.0725]
sensor '+12V' status is 'off' [instance = 3] [value = 12.195]
sensor 'CPU VCCP' status is 'off' [instance = 4] [value = 0.9805]
sensor 'CPU VTT' status is 'off' [instance = 5] [value = 1.0589]
sensor 'CPU PVSA' status is 'off' [instance = 6] [value = 0.9413]
sensor 'P1V8' status is 'off' [instance = 7] [value = 1.7841]
sensor 'P1V5' status is 'off' [instance = 8] [value = 1.5097]
sensor 'PCH +1.05V' status is 'off' [instance = 9] [value = 1.024]
sensor 'VCC 2V5' status is 'off' [instance = 10] [value = 2.432]
sensor 'MAIN 12V' status is 'off' [instance = 11] [value = 11.904]
sensor 'VCC 1V15' status is 'off' [instance = 12] [value = 1.136]
sensor 'DDR3 VTT' status is 'off' [instance = 13] [value = 0.736]
sensor 'RPS 12V' status is 'on' [instance = 14] [value = 0]
sensor 'NCT +3.3V' status is 'off' [instance = 15] [value = 3.216]
sensor 'NCT VBAT' status is 'off' [instance = 16] [value = 3.264]
sensor 'NCT +3.3VSB' status is 'off' [instance = 17] [value = 3.216]
sensor 'NCT VTT' status is 'off' [instance = 18] [value = 1.04]
sensor 'DTS CPU' status is 'off' [instance = 19] [value = 66]
sensor 'CPU Core 0' status is 'off' [instance = 20] [value = 63]
sensor 'CPU Core 1' status is 'off' [instance = 21] [value = 66]
sensor 'TD1' status is 'off' [instance = 22] [value = 41]
sensor 'TD2' status is 'off' [instance = 23] [value = 26]
sensor 'FAN_TMP_3' status is 'off' [instance = 24] [value = 40]
sensor 'LM75 U72' status is 'off' [instance = 25] [value = 32]
sensor 'LM75 U65' status is 'off' [instance = 26] [value = 37]
sensor 'LM75 U62' status is 'off' [instance = 27] [value = 37]
sensor 'FAN1' status is 'off' [instance = 28] [value = 5600]
sensor 'FAN2' status is 'off' [instance = 29] [value = 5600]
sensor 'FAN3' status is 'off' [instance = 30] [value = 5500]

Thank You!

**Comment by garnier-quentin** [comment]
I don't understand.

Which sensor do you want ? You can filter on TMP: ```--filter=sensors,TMP``` (for temperature i only see: FAN_TMP_3).

**Comment by VidushaZ** [comment]
I want the temperatures only. Filtering with TMP is not accurate since some devices have different sensor names like TEMP, Unless I add all the possible names. 

Is there any other way to filter the temperature sensors only? By oid or something?  Because in other plugins we can filter out by the component (fan,temperature,voltage) passing --component = temperature

**Comment by garnier-quentin** [comment]
Yes it would be great. But we dont have that information in MIB.

**Comment by VidushaZ** [comment]
All right I will try this `--filter=sensors,TMP` for now then.
