### ISSUE TITLE
Problème avec le plugin os::windows::snmp::plugin

### ISSUE THREAD

**Issue by quentincaron** [centreon/centreon-plugins#329]
Bonjour,

Je suis en Centreon 2.7.1 et j'ai récemment installé les centreon-plugins. 
Le problème est le suivant : 
Lorsque j'utilise la commande suivante dans le terminal : 
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=$IP$ --snmp-version=$version$ --snmp-community=$communauté$ --verbose --storage='.*' --name --regexp --display-transform-src='(..).*' --display-transform-dst='$1' --warning=80 --critical=90

J'ai bien le résultat suivant : 
WARNING: Storage 'C:' Total: 89.90 GB Used: 80.48 GB (89.52%) Free: 9.42 GB (10.48%) - Storage 'D:' Total: 100.00 GB Used: 87.67 GB (87.68%) Free: 12.32 GB (12.32%) | 'used_B:'=3144646656B;0:21472316620;0:24156356198;0;26840395776 'used_C:'=86410756096B;0:77223005388;0:86875881062;0;96528756736 'used_D:'=94139813888B;0:85896826060;0:96633929318;0;107371032576
Storage 'B:' Total: 25.00 GB Used: 2.93 GB (11.72%) Free: 22.07 GB (88.28%)
Storage 'C:' Total: 89.90 GB Used: 80.48 GB (89.52%) Free: 9.42 GB (10.48%)
Storage 'D:' Total: 100.00 GB Used: 87.67 GB (87.68%) Free: 12.32 GB (12.32%)

Cependant, j'essaye la même fonction en créant la commande suivante dans Centreon : 
$USER1$/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --verbose --regexp --display-transform-src='(..).*' --display-transform-dst='$1' --name --warning=90 --critical=95

J'ai le résultat suivant dans l'interface Centreon : 
(Execute command failed) avec un statut "Unknow" pour le service.

Le problème semble venir de cette partie de la commande : --display-transform-dst='$1'.
Mais je n'arrive pas à régler le problème, quelqu'un aurait-il la solution ?

**Comment by Sims24** [comment]
Bonjour, 

Pouvez-vous essayer en activant le enable_shell au niveau de la définition de la commande dans l'interface ?

**Comment by quentincaron** [comment]
J'ai coché la case, ça ne change rien malheureusement, toujours la même erreur.

**Comment by garnier-quentin** [comment]
Do you have the perl connector activated ? Could you give us the exact command launched by 'centreon-engine' ?
- Connect on centreon_storage database and : SELECT command_line FROM services where service_id = XXX;

**Comment by quentincaron** [comment]
Oui, le connecteur perl est activé car les autres modes du plugin fonctionne.

Par contre dans la base de données, la commande n'est pas complète : 
/bin/sh -c '/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=$ip$ --snmp-version=$version$ --snmp-community=$communauté$ --verbose --regexp --display-transform-src='\''(..).*'\'' --display-transform-dst='\''

**Comment by garnier-quentin** [comment]
Si vous voulez utiliser le caractère '$' directement dans la commande, il faut l'écrire 2 fois: '$$'.

**Comment by garnier-quentin** [comment]
I invite you to send me an email if you want.

**Comment by quentincaron** [comment]
Merci pour tout, le problème venait de la, je n'était pas au courant du fait qu'il fallait doubler le caractère "$" dans la commande.
