### ISSUE TITLE
[cloud::azure::management::monitor::plugin] Randomly error message : UNKNOWN: No metric found (Are the filters properly set?)

### ISSUE THREAD

**Issue by amourtialon** [centreon/centreon-plugins#3290]
Hello !

I'm having trouble with the cloud::azure::management::monitor::plugin plugin, on a service which works and which goes back the data well, I regularly have the following message:

`UNKNOWN: no metrics found (are the filters correctly defined?)`

Have you ever encountered this error ?

Command : (without parameters like Subcription Id, Client Id, ...)

`centreon_plugins.pl --plugin=cloud::azure::management::monitor::plugin --mode=get-metrics --custommode=api --metric='$_SERVICEMETRIC$' --aggregation='$_SERVICEAGGREGATION$' --interval='$_SERVICEINTERVAL$' --timeframe='$_SERVICETIMEFRAME$' --warning-metric='$_SERVICEWARNING$' --critical-metric='$_SERVICECRITIQUE$' --zeroed --timeout=30`

Parameters :
|Name|Value|
|-|-|
|METRIC|Percentage CPU|
|AGGREGATION|average|
|INTERVAL|PT5M or PT10M|
|TIMEFRAME|600|
|WARNING|90|
|CRITIQUE|95|

Thx !

Sorry for my English :-)

**Comment by pmatsconsulting** [comment]
Hello,

I have the same issue !!!

**Comment by Sims24** [comment]
Hello, 

It usually means that Azure Monitor doesn't have data over the period of time the Plugin is querying it. 

If you look at the Azure monitor dashboard, can you see value for the same period ? 
Thanks
Simon

**Comment by amourtialon** [comment]
Hello Simon,

Thanks for your feedback. On my last error indeed no data in Azure Monitor, but on older errors I have data, is it possible that Azure will update afterwards ?

Thanks
Allan

**Comment by amourtialon** [comment]
Hello Simon,

Thanks for your feedback. On my last error indeed no data in Azure Monitor, but on older errors I have data, is it possible that Azure will update afterwards ?

Thanks
Allan

**Comment by Sims24** [comment]
Hi, 

Could be, but seems strange. Maybe this is related to the timeframe (600) being larger than the interval (PT5M) in some cases?

**Comment by amourtialon** [comment]
Hi,

I don't think so, some of my probes are configured with interval 10PTM with same result. I will keep looking thank you for your help
