### ISSUE TITLE
fix (docker,cadvisor) Compatibility cgroupV2

### ISSUE THREAD

**Issue by elosi-alexis-chery** [centreon/centreon-plugins#3297]
Hello, 

I use Cadvisor plugin to monitor docker on host VM. 

Cadvisor API response seems to be different on OS using cgroupV2 like Debian 11.

This following call give different response :

Call api : http://X:X:X:X:8185/api/v1.3/docker 

**OS CgroupV2 like Debian 11:**

```
/system.slice/docker-3e34818f5c7f8316c0019981e5cb3cd78d1f43d06bd546f12ca009aae7c9a747.scope
/system.slice/docker-536eee727c77183412247b3718a3f5a7a6fb1e8754523ee8fb2d1bf97ec3b644.scope
/system.slice/docker-f493911f95924c4939f4d58c9dff9ed86b10b16aac49e86c55022b95ca144a90.scope
```

**CgroupV1 OS like Ubuntu 16:**

```

/docker/07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec
/docker/6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed
/docker/eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1
```

_Response API Cgroup V1 :_ 

![APIResponsecgroupV1](https://user-images.githubusercontent.com/95615564/144833848-e4c8f879-fb09-4912-be87-5db6b1df37ae.png)

_Response API Cgroup V2 :_ 

![APIResponsecgroupV2](https://user-images.githubusercontent.com/95615564/144833852-9be2406e-f3b0-4c5a-9408-36d3c6495db1.png)

**I have this error when i using my centreon plugin cadvisor :** 

`/usr/lib/centreon/plugins/centreon_cadvisor_api.pl --mode=container-usage  --credentials --username=centreon --password=foo --hostname=x.x.x.x --api-path=/docker --port=8185 --use-name`

_Response :_ 

`UNKNOWN: No containers found. `

I attach my command execution with debug mode enabled in this OutputCommandPlugin.txt file

[OutputCommandPlugin.txt](https://github.com/centreon/centreon-plugins/files/7660109/OutputCommandPlugin.txt)

_Could you adapt the cadvisor plugin to work with CgroupV2?_

**Comment by garnier-quentin** [comment]
The plugin checks the subcontainers. Maybe that's the issue.

**Comment by elosi-alexis-chery** [comment]
Hello Quentin, 

Thank you for your answer!

I check subcontainers, i have init.scope / system.slice and user.slice: 

![View_subcontainer](https://user-images.githubusercontent.com/95615564/145192658-11488bd5-4a0e-48c0-b2f6-eb1316e08125.png)

And in system.slice, i see my docker.sock and containers: 

![View_system.slice](https://user-images.githubusercontent.com/95615564/145192844-4ef6f179-2d52-48f8-a8d8-8087f7d3f9cb.png)

I think that CgroupV2 does not have the same hierarchy as CgroupV1.

**Comment by garnier-quentin** [comment]
Could you provide the result for http://X:X:X:X:8185/api/v1.3/docker with cgroupv1 and cgroupv2 ?

**Comment by elosi-alexis-chery** [comment]
I attach result in two file .json 

And in web browser : 
![image](https://user-images.githubusercontent.com/95615564/145196045-ea6de1c8-2d06-4322-b6aa-e313b2dd1092.png)


[CgroupV1.txt](https://github.com/centreon/centreon-plugins/files/7675444/CgroupV1.txt)
[CgroupV2.txt](https://github.com/centreon/centreon-plugins/files/7675445/CgroupV2.txt)

**Comment by garnier-quentin** [comment]
You have the same issue with plugin in v1. There is no subcontainers entry in json.

**Comment by elosi-alexis-chery** [comment]
Ok 

But with the same plugin command, i haven't the issue in cgroupv1 host :/ 


I attached output with debug mode enabled : 

[OutputCommandPluginCGROUPV2.txt](https://github.com/centreon/centreon-plugins/files/7660109/OutputCommandPlugin.txt)


Host CgroupV2
```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_cadvisor_api.pl --mode=container-usage  --credentials --username=centreon --password=toto  --hostname=HOST_CGROUPV2 --port=8185 
UNKNOWN: Node 'HOST_CGROUPV2': cannot decode json get containers response: 'false' expected, at character offset 0 (before "failed to get contai...") at /usr/lib/centreon/plugins/centreon_cadvisor_api.pl line 7301. - No containers found. 
```

Host CgroupV1
```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_cadvisor_api.pl --mode=container-usage  --credentials --username=centreon --password=toto  --hostname=HOST_CGROUPV1 --port=8185 
OK: All containers are ok | '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.cpu.count'=8;;;0; '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.cpu.utilization.percentage'=0.04%;;;0;100 '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.cpu.user.utilization.percentage'=0.02%;;;0;100 '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.cpu.system.utilization.percentage'=0.01%;;;0;100 '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.memory.usage.bytes'=69898240B;;;0;16492519424 '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.memory.cache.usage.bytes'=20680704B;;;0; '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.memory.rss.usage.bytes'=43274240B;;;0; '07e529aa0ea590b0da32243126d42bf8bb278b10db04f48236dd78bf89c090ec#container.swap.usage.bytes'=0B;;;0; '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.cpu.count'=8;;;0; '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.cpu.utilization.percentage'=0.00%;;;0;100 '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.cpu.user.utilization.percentage'=0.00%;;;0;100 '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.cpu.system.utilization.percentage'=0.00%;;;0;100 '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.memory.usage.bytes'=41680896B;;;0;16492519424 '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.memory.cache.usage.bytes'=28520448B;;;0; '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.memory.rss.usage.bytes'=10055680B;;;0; '6bd691dd8be603266ba3270f9e34eb4a68f6907d825eecb802d000b128498eed#container.swap.usage.bytes'=0B;;;0; 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.cpu.count'=8;;;0; 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.cpu.utilization.percentage'=1.01%;;;0;100 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.cpu.user.utilization.percentage'=0.47%;;;0;100 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.cpu.system.utilization.percentage'=0.45%;;;0;100 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.memory.usage.bytes'=144019456B;;;0;16492519424 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.memory.cache.usage.bytes'=38387712B;;;0; 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.memory.rss.usage.bytes'=92405760B;;;0; 'eeeb72a43f839951bb1da8eefe1b6cadb28dc49f958ae4cdd454efc1ae89fef1#container.swap.usage.bytes'=0B;;;0;


```

**Comment by garnier-quentin** [comment]
I don't understand how i can work with CgroupV1.txt. Could you provide the --debug when it works ?

**Comment by elosi-alexis-chery** [comment]
Attached, the file corresponding to the output of cgroupV1

Please note, the file takes 6.2 MB :)


[OutputDebugCgroupV1.txt](https://github.com/centreon/centreon-plugins/files/7685391/OutputDebugCgroupV1.txt)

**Comment by garnier-quentin** [comment]
Sorry for the delay. Could you test with that version ? 
https://github.com/centreon/centreon-plugins/archive/refs/heads/add-cadvisor-cgroupv2.zip

**Comment by garnier-quentin** [comment]
Have you tried the patch ?
