### ISSUE TITLE
[network::moxa::switch::snmp::plugin] add eds405a for cpu and memory plugins

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3298]
Hi,
Can you add eds405a model for cpu and memory plugins ?

      my $oids = {
          eds405a => '.1.3.6.1.4.1.8691.7.6.1',
      };

       eds405a => {
          cpuLoading5s        => { oid => '.1.3.6.1.4.1.8691.7.6.1.53' },
          cpuLoading30s       => { oid => '.1.3.6.1.4.1.8691.7.6.1.54' },
          cpuLoading300s      => { oid => '.1.3.6.1.4.1.8691.7.6.1.55' },
      }

       eds405a => {
          totalMemory     => { oid => '.1.3.6.1.4.1.8691.7.6.1.56' },
          freeMemory      => { oid => '.1.3.6.1.4.1.8691.7.6.1.57' },
          usedMemory      => { oid => '.1.3.6.1.4.1.8691.7.6.1.58' },
      },

[moxa-eds-405a-v3.7.txt](https://github.com/centreon/centreon-plugins/files/7663567/moxa-eds-405a-v3.7.txt)

Best regards

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk ? 
snmpwalk -ObentU -v 2c -c public IP_ADDR .1 > moxa.snmpwalk

**Comment by garnier-quentin** [comment]
You can test with last version: https://github.com/centreon/centreon-plugins/pull/3307

**Comment by gagzou** [comment]
Hi,
I installed last plugin pack and i have the error : 

![image](https://user-images.githubusercontent.com/61595839/146425066-0b2a9b1e-e218-42da-a181-101c96855db7.png)

**Comment by Sims24** [comment]
@gagzou Are you sure that you upgraded both Pack and Plugin? Thresholds are now --cpu-utilization-5m for example. 

Make sure the Pack is up to date within the **Configuration > Plugin Packs** and that your configuration is being exported correctly.

**Comment by gagzou** [comment]
@Sims24 yes update all (pack and plugin):
![image](https://user-images.githubusercontent.com/61595839/146514422-0da42fc7-20c9-4a64-8f2a-818a7771101f.png)

**Comment by gagzou** [comment]
For information , new issue ( [network::moxa::switch::snmp::plugin] Unknown option with cpu and memory #3327 )
