### ISSUE TITLE
support for Netgear S series

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3299]
It should be nice to have support for Netgear S-series switches. The M-series is not working for CPU, Hardware ecc.

Here you can find snmp walk and mibs
[s3300v6.6.4.26-mibs.zip](https://github.com/centreon/centreon-plugins/files/7666228/s3300v6.6.4.26-mibs.zip)
[netgear-sseries.zip](https://github.com/centreon/centreon-plugins/files/7666229/netgear-sseries.zip)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3305

You can test with last version

**Comment by joschi99** [comment]
Tested for cpu, hardware and memory, no problems found. Thanks
