### ISSUE TITLE
Just Relearning Centreon - been a few years...Anyone have time to right a MOS plugin?

### ISSUE THREAD

**Issue by countrdd** [centreon/centreon-plugins#330]
Would be Nice to add a Mean opinion score check if anyone has time to write it. 

https://www.pingman.com/kb/article/how-is-mos-calculated-in-pingplotter-pro-50.html

**Comment by garnier-quentin** [comment]
For which plugin ?

**Comment by countrdd** [comment]
I guess the best place to put it would be under VOIP. Since it is a calculation that shows what the call quality would be. Guess defaults would be - 

ok - >4.0
warning - 3.0 - 4.0
Critical: - <3.0


MOS	Quality	Impairment
5	Excellent	Imperceptible
4	Good	Perceptible but not annoying
3	Fair	Slightly annoying
2	Poor	Annoying
1	Bad	Very annoying

**Comment by garnier-quentin** [comment]
It's a ping ? There is check_icmp that's doing the job.

**Comment by countrdd** [comment]
I put a link that shows how to calculate it.
It has to do with latency, packet loss and Jitter…

**Comment by countrdd** [comment]
I actually found a python plugin for nagios that does exactly what i need. This is not just an ICMP check. it does use it, but it has to calculate jitter and there is a perl module out there to actually calculate the MOS (Algorithm::MOS; ) just having a hard putting in all together.

**Comment by garnier-quentin** [comment]
I think it should be added in check_icmp. Better to use check_icmp. Moreover it's difficul to use setuid perl script (need to compile or wrapped it).
