### ISSUE TITLE
[storage::fujitsu::eternus::dx::ssh::plugin] uninitialized message output

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#3303]
Hello, 

I have a filtering message error when requesting the volume stats.

here's the command I'm executing
centreon_plugins.pl --plugin="storage::fujitsu::eternus::dx::ssh::plugin" --mode="volume-stats" --filter-uom="!(A/V/W/%)" --change-perfdata="#,." --ssh-option="-l=centreon-monitoring" --filter-name="STA.........H040"  --hostname=x.x.x.x

This is the result : 
Use of uninitialized value in pattern match (m//) at /storage/fujitsu/eternus/dx/ssh/mode/volumestats.pm line 207.
Use of uninitialized value $matches[1] in concatenation (.) or string at /storage/fujitsu/eternus/dx/ssh/mode/volumestats.pm line 209.
OK: All Volumes are ok | 'read_iops_STA_S_D1024_H0400'=0;;;0; 'write_iops_STA_S_D1024_H0400'=0;;;0; .................

The filtering itself that works!
Only the message (error) output is not so nice :-)

I am not a specialist in this programming language, which is why I ask that you see where the initialization is not correct!?

regards,
Geert

**Comment by garnier-quentin** [comment]
Could you provide output from the following command on your storage ?
```show performance -type host-io```

**Comment by gbin2265** [comment]
Hello, 

info : eternus DX600 S5

see here the info of the SHOW commando

CLI> show performance -type host-io
Volume                                  IOPS(IOPS)              Throughput(MB/s)        Response Time(msec.)    Processing Time(msec.)  Cache Hit Rate(%)
No.   Name                              Read      / Write       Read      / Write       Read      / Write       Read      / Write       Read      / Write     / Prefetch
----- --------------------------------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------
    0 STA_S_D0000_H0000                          0           0           0           0           0           0           0           0           0           0           0
    1 STA_S_D0001_H0001                          0           0           0           0           0           0           0           0           0           0           0
    2 STA_S_D0002_H0002                          0           0           0           0           0           0           0           0           0           0           0
    3 STA_S_D0003_H0003                          0           0           0           0           0           0           0           0           0           0           0
    4 STA_S_D0004_H0004                          0           0           0           0           0           0           0           0           0           0           0
    5 STA_S_D0005_H0005                          0           0           0           0           0           0           0           0           0           0           0
    6 STA_S_D0006_H0006                          0           0           0           0           0           0           0           0           0           0           0
    7 STA_S_D0007_H0007                          0           0           0           0           0           0           0           0           0           0           0
    8 STA_S_D0008_H0008                          0           0           0           0           0           0           0           0           0           0           0
    9 STA_S_D0009_H0009                          0           0           0           0           0           0           0           0           0           0           0
   10 STA_S_D0010_H000A                          0           0           0           0           0           0           0           0           0           0           0
   11 STA_S_D0011_H000B                          0           0           0           0           0           0           0           0           0           0           0
   12 STA_S_D0012_H000C                          0           0           0           0           0           0           0           0           0           0           0
   13 STA_S_D0013_H000D                          0           0           0           0           0           0           0           0           0           0           0
   14 STA_S_D0014_H000E                          0           0           0           0           0           0           0           0           0           0           0
   15 STA_S_D0015_H000F                          0           0           0           0           0           0           0           0           0           0           0
   16 STA_S_D0016_H0010                          0           0           0           0           0           0           0           0           0           0           0


regards,
Geert

**Comment by garnier-quentin** [comment]
I don't reproduce your issue. Do you use the last version ? In your output i don't see the 'STA_S_D1024_H0400'

**Comment by gbin2265** [comment]
Hello,

i have more then 3000 lines.... 
I thought you just needed the headers.

 1641 STA_S_D1024_H0400                          0           0           0           0           0           0           0           0           0           0           0

regards,
Geert


regards,
Geert

**Comment by garnier-quentin** [comment]
I need the complete output (you can sent it by email qgarnier@centreon.com in gzip format).

**Comment by garnier-quentin** [comment]
Thanks. It should be fixed in last version.

**Comment by gbin2265** [comment]
Hello, 

i have test the new version volume-stats and works fine with the correct perfdata output !

regards,
Geert
