### ISSUE TITLE
[apps::vmware::connector::plugin] - new mode to check licenses

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3304]
It could be useful to add a new mode for VMware that allows to check license status and expiration for vCenter, VSAN ecc

- https://communities.vmware.com/t5/vSphere-SDK-for-Perl-Documents/Retrieving-vSphere-License-Information-using-vSphere-API/ta-p/2792485
- https://blogs.vmware.com/vsphere/2012/12/retrieving-vsphere-license-information-expiration-using-the-vsphere-api.html

**Comment by joschi99** [comment]
As you can see from screenshot it should be nice to monitor:

- license status & expiration
- license usage
![vmware](https://user-images.githubusercontent.com/6400595/146002052-0dfc40ef-917b-4d5e-85a6-65ee1f76c703.png)

**Comment by garnier-quentin** [comment]
Could we do a session to develop it ?

**Comment by joschi99** [comment]
for sure, but le me know before what you need for the session so we can prepare everything. It is enough to access vCenter API?

**Comment by garnier-quentin** [comment]
I need the vmware connector installed with the plugin (with access on the vcenter).

**Comment by joschi99** [comment]
Could we plan it for dec 21, maybe 10am? We have connector and plugins there and user with API access.

**Comment by garnier-quentin** [comment]
Ok for 21 Dec 10am.

**Comment by joschi99** [comment]
Great, please send me a calender with the meeting details on my email.

**Comment by joschi99** [comment]
Found the answer with
```
"vSAN Enterprise Plus": {
"edition": "vsan.enterprisePlus.cpuPackage",
"total": "0",
"used": "8"
}
```

Total: "0" means probably "unlimited"
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6400595/146911387-dea90e11-d54c-4113-8970-c119a6f9c81a.png)

**Comment by garnier-quentin** [comment]
Need the vmware connector 3.2.2 and last centreon-plugins version for the mode 'licenses'.

**Comment by joschi99** [comment]
Have seen only now that the expired license is in state "unassigned". Did you check this?

**Comment by garnier-quentin** [comment]
I didn't check that. But you can exclude it.

**Comment by joschi99** [comment]
Thanks, it doesn't make sense to check Unassigned licenses probably

**Comment by garnier-quentin** [comment]
You can send me the vmware log file. But it could do some cleaning also remove that license

**Comment by joschi99** [comment]
What vmware log do you mean exactly?

When you plan to release the rpm for VMWare-daemon 3.2.2?

**Comment by garnier-quentin** [comment]
The ```centreon_vmware.log``` file. I will be released next month.

**Comment by joschi99** [comment]
Thanks
[centreon_vmware.zip](https://github.com/centreon/centreon-plugins/files/7767624/centreon_vmware.zip)

Wish you a merry Christmas and a happy new year
