### ISSUE TITLE
network interface threshold?

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#331]
are the threshold value based on 100% value? or for example a interface that is 1Gbps and for the warning threshold for 700Mbps I need define = 700000000?

Thx

**Comment by garnier-quentin** [comment]
You can set the unit for the threshold: '%' or 'B'.

**Comment by CFRR** [comment]
To clarify:

$USER1$/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --mode=interfaces --add-traffic --add-errors --interface=$ARG1$ --name --oid-display=ifAlias --warning-in-traffic=$ARG2$ --warning-out-traffic=$ARG3$ --critical-in-traffic=$ARG4$ --critical-out-traffic=$ARG5$

and UI for $ARG2$ I put 70% or 700000000B ?

**Comment by garnier-quentin** [comment]
By default it's unit '%'.
