### ISSUE TITLE
Missing "-" for two options in command line - Plugin antivirus clamav 

### ISSUE THREAD

**Issue by mcorcam** [centreon/centreon-plugins#3310]
Hello, 

In the command line there are two "-" missing in the warning option. 
 
centreon-plugin-packs/src/applications-antivirus-clamav-ssh/pack.json 

"commands": [
        {
            "line": "\\\"$CENTREONPLUGINS$\\\\/centreon_clamav_ssh.pl --plugin=apps::antivirus::clamav::local::plugin --mode=update-status --hostname=$HOSTADDRESS$ --remote $_HOSTSSHEXTRAOPTIONS$ --warning-engine-status=\\'$_SERVICEWARNINGENGINESTATUS$\\' --critical-engine-status=\\'$_SERVICECRITICALENGINESTATUS$\\'**-**-warning-maindb-status=\\'$_SERVICEWARNINGMAINDBSTATUS$\\' --critical-maindb-status=\\'$_SERVICECRITICALMAINDBSTATUS$\\' **-**-warning-dailydb-status=\\'$_SERVICEWARNINGDAILYDBSTATUS$\\' --critical-dailydb-status=\\'$_SERVICECRITICALDAILYDBSTATUS$\\' $_SERVICEEXTRAOPTIONS$\\\"",
            "name": "App-Antivirus-Clamav-SSH-Update-Status",
            "type": "2"
        }

Kind regards.

**Comment by garnier-quentin** [comment]
You're right. I fix it. It would be ok in next release (next week).
