### ISSUE TITLE
create support for Fortinet switches

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3312]
It should be nice to have support for Fortiswitches. Attached you can find SNMP MIB and snmpwalk.
[fortiswitch.zip](https://github.com/centreon/centreon-plugins/files/7684207/fortiswitch.zip)

Interfaces, ARP and uptime are working with standard modes

**Comment by garnier-quentin** [comment]
A new plugin is done: network::fortinet::fortiswitch::snmp::plugin

We have a very small disk, is it ok ?
```
perl centreon_plugins.pl --plugin=network/fortinet/fortiswitch/snmp/plugin.pm  --hostname=127.0.0.1 --snmp-port=1611 --snmp-community=fortiswitch --verbose  --snmp-version=2c --mode=disk
OK: Disk total: 3.00 MB used: 384.00 KB (12.50%) free: 2.62 MB (87.50%) | 'disk.usage.bytes'=393216B;;;0;3145728 'disk.free.bytes'=2752512B;;;0;3145728 'disk.usage.percentage'=12.50%;;;0;100
```

**Comment by joschi99** [comment]
Done some test, seems working fine. thanks
