### ISSUE TITLE
[fujitsu::eternus::dx::ssh::plugin] perfdata or non used char |

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#3316]
Hello,

after the last update of the eternus plugin I have no perfdata for the mode PSU and PHYSICALDISK 
or if they are not provided i have the character "|" in the output.

This is the issue that i asked before the update https://github.com/centreon/centreon-plugins/issues/3303

centreon_plugins.pl --plugin="storage::fujitsu::eternus::dx::ssh::plugin" --mode="psu" --ssh-option="-l=loginname"  --hostname=x.x.x.x
OK: All 10 power supplies are ok. |

centreon_plugins.pl --plugin="storage::fujitsu::eternus::dx::ssh::plugin" --mode="physicaldisk" --ssh-option="-l=loginname"  --hostname=x.x.x.x
OK: All 118 physical disks are ok. |

is this a bug that i don't have perfdata or is the last character "|" too much in the output?

regards,
Geert

**Comment by garnier-quentin** [comment]
Modes 'physicaldisk' and 'psu' don't have perfdatas. Which perfdata do you want ?

**Comment by gbin2265** [comment]
Ok, 
The character | is to much on the output now

Prefdata
PSU :
Power OK - 1353 (Watt)

CE Power, 735 (Watt)
DE#01 Power, 156 (Watt)
DE#10 Power, 154 (Watt)
DE#20 Power, 150 (Watt)
DE#30 Power, 158 (Watt)

Physical Disk
And how many space is used on the disk's (%)

**Comment by gbin2265** [comment]
ssh login@ip "show power-consumption"
CLI> show power-consumption
Location 1-min avg.(W) 1-hour avg.(W)
-------- ------------- --------------
System            2136           2150
CE                 735            738
DE#01              164            165
DE#10              167            168
DE#20              167            169
DE#30              168            171

**Comment by garnier-quentin** [comment]
So it's a new command for the power consumption. Not sure how will add it. Names seems different.

**Comment by gbin2265** [comment]
Hello, 

see here the output for

CLI> show enclosure-status -type all
Controller Enclosure    Information
 Location      Status       Error Code  Sensor 1 / Sensor 2
 Intake Temp   Normal       0x0000      24 (C)   / 24 (C)
 Exhaust Temp  Normal       0x0000      38 (C)   / 40 (C)

Controller Enclosure    Status
 Controller Module Status/Status Code
  CM#0         [Normal      / 0xE001]
  CM#1         [Normal      / 0xE001]
 PCIe Flash Module Status/Status Code
  PFM#0        [Undefined   / 0x0000]
  PFM#0 Port#0 [Undefined   / 0x0000]
  PFM#0 Port#1 [Undefined   / 0x0000]
  PFM#1        [Undefined   / 0x0000]
  PFM#1 Port#0 [Undefined   / 0x0000]
  PFM#1 Port#1 [Undefined   / 0x0000]
  PFM#2        [Undefined   / 0x0000]
  PFM#2 Port#0 [Undefined   / 0x0000]
  PFM#2 Port#1 [Undefined   / 0x0000]
  PFM#3        [Undefined   / 0x0000]
  PFM#3 Port#0 [Undefined   / 0x0000]
  PFM#3 Port#1 [Undefined   / 0x0000]
  PFM#4        [Undefined   / 0x0000]
  PFM#4 Port#0 [Undefined   / 0x0000]
  PFM#4 Port#1 [Undefined   / 0x0000]
  PFM#5        [Undefined   / 0x0000]
  PFM#5 Port#0 [Undefined   / 0x0000]
  PFM#5 Port#1 [Undefined   / 0x0000]
  PFM#6        [Undefined   / 0x0000]
  PFM#6 Port#0 [Undefined   / 0x0000]
  PFM#6 Port#1 [Undefined   / 0x0000]
  PFM#7        [Undefined   / 0x0000]
  PFM#7 Port#0 [Undefined   / 0x0000]
  PFM#7 Port#1 [Undefined   / 0x0000]
 Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
 Disk Status
  CE-Disk#0   [Available                    ]  CE-Disk#1   [Available                    ]
  CE-Disk#2   [Available                    ]  CE-Disk#3   [Available                    ]
  CE-Disk#4   [Available                    ]  CE-Disk#5   [Available                    ]
  CE-Disk#6   [Available                    ]  CE-Disk#7   [Available                    ]
  CE-Disk#8   [Available                    ]  CE-Disk#9   [Available                    ]
  CE-Disk#10  [Available                    ]  CE-Disk#11  [Available                    ]
  CE-Disk#12  [Available                    ]  CE-Disk#13  [Available                    ]
  CE-Disk#14  [Available                    ]  CE-Disk#15  [Available                    ]
  CE-Disk#16  [Available                    ]  CE-Disk#17  [Available                    ]
  CE-Disk#18  [Available                    ]  CE-Disk#19  [Present                      ]
  CE-Disk#20  [Present                      ]  CE-Disk#21  [Present                      ]
  CE-Disk#22  [Not Available                ]  CE-Disk#23  [Not Available                ]
Drive Enclosure #01 Information
 Location      Status       Error Code  Sensor 1 / Sensor 2
 Intake Temp   Normal       0x0000      25 (C)   / 25 (C)
 Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #01 Status
 I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
 Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
 Disk Status
  DE#01-Disk#0   [Available                    ]  DE#01-Disk#1   [Available                    ]
  DE#01-Disk#2   [Available                    ]  DE#01-Disk#3   [Available                    ]
  DE#01-Disk#4   [Available                    ]  DE#01-Disk#5   [Available                    ]
  DE#01-Disk#6   [Available                    ]  DE#01-Disk#7   [Available                    ]
  DE#01-Disk#8   [Available                    ]  DE#01-Disk#9   [Available                    ]
  DE#01-Disk#10  [Available                    ]  DE#01-Disk#11  [Available                    ]
  DE#01-Disk#12  [Available                    ]  DE#01-Disk#13  [Available                    ]
  DE#01-Disk#14  [Available                    ]  DE#01-Disk#15  [Available                    ]
  DE#01-Disk#16  [Available                    ]  DE#01-Disk#17  [Available                    ]
  DE#01-Disk#18  [Available                    ]  DE#01-Disk#19  [Available                    ]
  DE#01-Disk#20  [Available                    ]  DE#01-Disk#21  [Available                    ]
  DE#01-Disk#22  [Available                    ]  DE#01-Disk#23  [Available                    ]

Drive Enclosure #10 Information
 Location      Status       Error Code  Sensor 1 / Sensor 2
 Intake Temp   Normal       0x0000      24 (C)   / 24 (C)
 Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #10 Status
 I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
 Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
 Disk Status
  DE#10-Disk#0   [Available                    ]  DE#10-Disk#1   [Available                    ]
  DE#10-Disk#2   [Available                    ]  DE#10-Disk#3   [Available                    ]
  DE#10-Disk#4   [Available                    ]  DE#10-Disk#5   [Available                    ]
  DE#10-Disk#6   [Available                    ]  DE#10-Disk#7   [Available                    ]
  DE#10-Disk#8   [Available                    ]  DE#10-Disk#9   [Available                    ]
  DE#10-Disk#10  [Available                    ]  DE#10-Disk#11  [Available                    ]
  DE#10-Disk#12  [Available                    ]  DE#10-Disk#13  [Available                    ]
  DE#10-Disk#14  [Available                    ]  DE#10-Disk#15  [Available                    ]
  DE#10-Disk#16  [Available                    ]  DE#10-Disk#17  [Available                    ]
  DE#10-Disk#18  [Available                    ]  DE#10-Disk#19  [Available                    ]
  DE#10-Disk#20  [Available                    ]  DE#10-Disk#21  [Available                    ]
  DE#10-Disk#22  [Available                    ]  DE#10-Disk#23  [Spare                        ]

Drive Enclosure #20 Information
 Location      Status       Error Code  Sensor 1 / Sensor 2
 Intake Temp   Normal       0x0000      24 (C)   / 24 (C)
 Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #20 Status
 I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
 Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
 Disk Status
  DE#20-Disk#0   [Available                    ]  DE#20-Disk#1   [Available                    ]
  DE#20-Disk#2   [Available                    ]  DE#20-Disk#3   [Available                    ]
  DE#20-Disk#4   [Available                    ]  DE#20-Disk#5   [Available                    ]
  DE#20-Disk#6   [Available                    ]  DE#20-Disk#7   [Available                    ]
  DE#20-Disk#8   [Available                    ]  DE#20-Disk#9   [Available                    ]
  DE#20-Disk#10  [Available                    ]  DE#20-Disk#11  [Available                    ]
  DE#20-Disk#12  [Available                    ]  DE#20-Disk#13  [Available                    ]
  DE#20-Disk#14  [Available                    ]  DE#20-Disk#15  [Available                    ]
  DE#20-Disk#16  [Available                    ]  DE#20-Disk#17  [Available                    ]
  DE#20-Disk#18  [Available                    ]  DE#20-Disk#19  [Available                    ]
  DE#20-Disk#20  [Available                    ]  DE#20-Disk#21  [Available                    ]
  DE#20-Disk#22  [Available                    ]  DE#20-Disk#23  [Spare                        ]

Drive Enclosure #30 Information
 Location      Status       Error Code  Sensor 1 / Sensor 2
 Intake Temp   Normal       0x0000      24 (C)   / 24 (C)
 Exhaust Temp  Normal       0x0000      -        / -

Drive Enclosure #30 Status
 I/O Module Status/Status Code
  IOM#0        [Normal      / 0xE001]
  IOM#1        [Normal      / 0xE001]
 Power Supply Unit Status/Status Code
  PSU#0        [Normal      / 0xE001]
  PSU#1        [Normal      / 0xE001]
 Disk Status
  DE#30-Disk#0   [Available                    ]  DE#30-Disk#1   [Available                    ]
  DE#30-Disk#2   [Available                    ]  DE#30-Disk#3   [Available                    ]
  DE#30-Disk#4   [Available                    ]  DE#30-Disk#5   [Available                    ]
  DE#30-Disk#6   [Available                    ]  DE#30-Disk#7   [Available                    ]
  DE#30-Disk#8   [Available                    ]  DE#30-Disk#9   [Available                    ]
  DE#30-Disk#10  [Available                    ]  DE#30-Disk#11  [Available                    ]
  DE#30-Disk#12  [Available                    ]  DE#30-Disk#13  [Available                    ]
  DE#30-Disk#14  [Available                    ]  DE#30-Disk#15  [Available                    ]
  DE#30-Disk#16  [Available                    ]  DE#30-Disk#17  [Available                    ]
  DE#30-Disk#18  [Available                    ]  DE#30-Disk#19  [Available                    ]
  DE#30-Disk#20  [Available                    ]  DE#30-Disk#21  [Available                    ]
  DE#30-Disk#22  [Available                    ]  DE#30-Disk#23  [Spare                        ]
