### ISSUE TITLE
network::cisco::esa::restapi::plugin - show detailed status

### ISSUE THREAD

**Issue by TomSVT** [centreon/centreon-plugins#3317]
Hello,

Could you explain how-to or could you add a detailed status to this plugin, please ?
On the ressources page, it only shows "System is ok" and we could like to see the detailed status like "messages in workqueue: 0"

![image](https://user-images.githubusercontent.com/76195801/145704969-f1854bcb-71ac-473d-aeb5-99a0a9015fd5.png)

Filtering with " --filter-counters='messages-workqueue'"

![image](https://user-images.githubusercontent.com/76195801/145704992-91ee3fca-0e6c-4243-920e-33eaed4fb931.png)

Regards,

Thomas

**Comment by garnier-quentin** [comment]
You cannot. The plugin was not designed for that. I don't have solution (otherwise redesign all plugins system). Not we are going to do that right now.

You can use the collection mode (protocol/snmp plugin) to do what you want.

**Comment by TomSVT** [comment]
Hello Quentin,

I thank you for your answer and all the good work you do for us.

I thought it was possible because I already use a restapi plugin for an HPE StoreOnce and the status is more detailed :
![image](https://user-images.githubusercontent.com/76195801/145977908-c8d25963-944d-4cd4-a294-7432f1f7c6a7.png)

![image](https://user-images.githubusercontent.com/76195801/145977818-cfdccc1d-713f-4a7a-b398-d59894597d8c.png)

Have a nice day,

Thomas

**Comment by garnier-quentin** [comment]
Yes i know. But it's not the same template. Otherwise you have all in one line and it's not very readable (when you check everything)
You can do what you want with the collection mode.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old so let me close it. If the answer given by Quentin is not enough and you request an enhancement, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
