### ISSUE TITLE
Plugin "os::linux::local::plugin" mode "systemd-sc-status" doesn't work on Debian 11

### ISSUE THREAD

**Issue by simobri** [centreon/centreon-plugins#3318]
Hello,

**Assumption**: this is my first ever issue I open on GitHub, so I may have made some mistake.

I found an issue inside the plugin of the title after in-place upgrade a system from Debian 10 to Debian 11, i notice the plugins stop to find any sytemd  service unit and reply always with:

`UNKNOWN: No service found.` 

I  update the plugins with latest version avaiable as today with no changes. So, I made some test and i probably found the reason of the behaviour inside the new "systemctl" command, this is the version that I have on Debian 11 system:

```
# systemctl --version
systemd 247 (247.3-6)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

The output of the used command `systemctl list-unit-files --no-pager --no-legend` (as I read inside the guide of the plugin itself if the one that is used to query systemd), now as default prepends some spaces for the "●" symbol, here is a sample output

```
# systemctl -a --no-pager --no-legend | egrep "snmpd|sendmail"
● sendmail.service                                                                                               not-found inactive dead      sendmail.service
  snmpd.service                                                                                                  loaded    active   running   Simple Network Management Protocol (SNMP) Daemon.
```

While on Debian 10, with an older version of the "systemctl" command:

```
# systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

The output starts directly with the unit name:

```
#  systemctl -a --no-pager --no-legend | egrep "snmpd|sendmail"
sendmail.service                                                                                               not-found inactive dead      sendmail.service
snmpd.service                                                                                                  loaded    active   running   Simple Network Management Protocol (SNMP) Daemon.
```

As man page of the systemctl command, the option  "--plain" can be used to output the list without the "bullet circles" as their call the dot before the unit

```
[...]
       --plain
           When used with list-dependencies, list-units or list-machines, the output is printed as a list instead of a tree, and the bullet circles are omitted.
[...]
```

So i changed the rows 120 and 148 of the file `/centreon-plugins/os/linux/local/mode/systemdscstatus.pm`, where the command options are defined from this

```
#cat systemdscstatus.pm --number | grep command_options
   120          command_options => '-a --no-pager --no-legend'
   148          command_options => 'list-unit-files --no-pager --no-legend'
```

To this:

```
#cat systemdscstatus.pm --number | grep command_options
   120          command_options => '-a --no-pager --no-legend --plain'
   148          command_options => 'list-unit-files --no-pager --no-legend --plain'
```

And the issue seem to be resolved, as for service name filtering.

`OK: Total Running: 1, Total Failed: 0, Total Dead: 0, Total Exited: 0 - Service 'snmpd.service' status : loaded/active/running [boot: -] 
`
I think there still some issue with catching of the service boot option (enabled or not), since no data  is displayed  in the output:

`./centreon_plugins.pl --plugin os::linux::local::plugin --mode systemd-sc-status --filter-name snmpd.service --critical-status '%{sub} =~/dead/i'  --warning-status '%{boot} =~/disabled/i'`

Output of Debian 11:

`OK: Total Running: 1, Total Failed: 0, Total Dead: 0, Total Exited: 0 - Service 'snmpd.service' status : loaded/active/running [boot: -] | 'total_running'=1;;;0;1 'total_failed'=0;;;0;1 'total_dead'=0;;;0;1 'total_exited'=0;;;0;1`

Output of Debian 10:

`OK: Total Running: 1, Total Failed: 0, Total Dead: 0, Total Exited: 0 - Service 'snmpd.service' status : loaded/active/running [boot: enabled] | 'total_running'=1;;;0;1 'total_failed'=0;;;0;1 'total_dead'=0;;;0;1 'total_exited'=0;;;0;1
`

But for now I have  no time to investigate further, I think is also for this issue, something with text parsing because the output of  `systemctl    list-unit-files --no-pager --no-legend | grep snmpd` is different from the two system, on the newer, a new column has been added:

Debian 10:
```
# systemctl    list-unit-files --no-pager --no-legend | grep snmpd
snmpd.service                          enabled
```

Debian11:
```
# systemctl    list-unit-files --no-pager --no-legend | grep snmpd
snmpd.service                          disabled        enabled
```

Regards.

**Comment by Sims24** [comment]
For a first issue, that's a great one ;) You could even have proposed a pull request because you have gone through all required analysis to to make a fix! 

Thanks, we will fix this in the next tag.

**Comment by garnier-quentin** [comment]
Thanks for the issue. You can test with last git version
