### ISSUE TITLE
Synology - Bad sectors

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#3321]
Since DSM 7, we have a new OID to check bad sectors on disk:

![image](https://user-images.githubusercontent.com/498115/145822838-23c2cb50-f014-4816-a76d-434f39c55e08.png)

https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf

This is important check as snmp agent announces disk as running normal but not the web interface:

![image](https://user-images.githubusercontent.com/498115/145823277-5c600df2-ead2-460b-a879-b913c792db25.png)

![image](https://user-images.githubusercontent.com/498115/145823294-57f82cb8-fc78-4744-a1a2-819799d51e96.png)

If you need some snmpwalk dump, tell me.

regards,

jfr

**Comment by garnier-quentin** [comment]
I need the full snmpwalk.

**Comment by jframeau** [comment]
Two files:

- synology-std.dump.gz - standard part
- synology-syno.dump.gz - syno specific part
[synology-syno.dump.gz](https://github.com/centreon/centreon-plugins/files/7705460/synology-syno.dump.gz)
[synology-std.dump.gz](https://github.com/centreon/centreon-plugins/files/7705461/synology-std.dump.gz)

**Comment by garnier-quentin** [comment]
You can test with last git version. bad sectors is added in hardware mode.
