### ISSUE TITLE
Add line jump [plugin:storage::netapp::ontap::snmp::plugin:mode:filesys]

### ISSUE THREAD

**Issue by GMoral13** [centreon/centreon-plugins#3322]
Hi all,

I have integrated this plugin on my monitoring platform, Centreon, but when it shows the output line, it does it all together.

I'm using that: /usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin storage::netapp::ontap::snmp::plugin --mode filesys --hostname X.X.X.X --snmp-version 2c --snmp-community XX --filter-vserver XX --warning-usage 98 --critical-usage 100 --units %

I'm triying to add a line jump on the output, but i don't know how to do it. I've tried on this line (like adding <br> and \n, but it does not work):
```
sub custom_vs_status_output {
    my ($self, %options) = @_;

    my $msg = sprintf(
        **"vserver '%s' status : %s",**
        $self->{result_values}->{vserver_name},
        $self->{result_values}->{vserver_status},
    );
    return $msg;
}
```

Can anyone help me with my problem? I would really appreciate it as I don't have much of a programming idea.

**Comment by garnier-quentin** [comment]
Could you show the original output and the output you want.

**Comment by GMoral13** [comment]
Yep, sorry, missed to show at the beginning:

I have this output:
WARNING: Filesys 'XXXXXXXXX' Total: 6.10 TB Used: 5.92 TB (97.04%) Free: 185.09 GB (2.96%) - Filesys 'XXXXXXXXX' Total: 16.69 TB Used: 16.24 TB (97.29%) Free: 462.66 GB (2.71%) - Filesys 'XXXXXXXXX' Total: 192.81 GB Used: 169.55 GB (87.93%) Free: 23.26 GB (12.07%) - Filesys 'XXXXXXXXX' Total: 75.99 GB Used: 67.79 GB (89.20%) Free: 8.21 GB (10.80%) - Filesys 'XXXXXXXXX' Total: 715.71 MB Used: 473.60 MB (66.17%) Free: 242.11 MB (33.83%) - Filesys 'XXXXXXXXX' Total: 177.04 GB Used: 95.66 GB (54.03%) Free: 81.38 GB (45.97%)

And i want something like this:
WARNING: Filesys 'XXXXXXXXX' Total: 6.10 TB Used: 5.92 TB (97.04%) Free: 185.09 GB (2.96%)
Filesys 'XXXXXXXXX' Total: 16.69 TB Used: 16.24 TB (97.29%) Free: 462.66 GB (2.71%)
Filesys 'XXXXXXXXX' Total: 192.81 GB Used: 169.55 GB (87.93%) Free: 23.26 GB (12.07%)
Filesys 'XXXXXXXXX' Total: 75.99 GB Used: 67.79 GB (89.20%) Free: 8.21 GB (10.80%)
Filesys 'XXXXXXXXX' Total: 715.71 MB Used: 473.60 MB (66.17%) Free: 242.11 MB (33.83%)
Filesys 'XXXXXXXXX' Total: 177.04 GB Used: 95.66 GB (54.03%) Free: 81.38 GB (45.97%)

**Comment by garnier-quentin** [comment]
You cannot. Lines after the first one is for detailed informations. But you can use:
```
--change-short-output='- Filesys~\nFilesys~g'
```

**Comment by GMoral13** [comment]
Well, that worked on the command line, but when it shows on a custom view, doesn't seems to works propertly:

B Used: 16.24 TB (97.29%) Free: 462.66 GB (2.71%)\nFilesys 'SM_HSL_SVM_NFS_db_exports

**Comment by garnier-quentin** [comment]
I cannot help for the custom views. That use case is not managed.

**Comment by garnier-quentin** [comment]
Maybe you can cheat and use '<br/>' ;)

**Comment by garnier-quentin** [comment]
--change-short-output='- Filesys~<br/>Filesys~g'

**Comment by GMoral13** [comment]
Now it's working with: --change-short-output='Filesys~<br/>Filesys~g'

Thanks a lot!
