### ISSUE TITLE
[network::moxa::switch::snmp::plugin] Unknown option with cpu and memory

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3327]
Hi,

Centreon 20.10.14.
Plugin pack update today (all centreon and moxa plugin).
centreon-pack-network-moxa-switch-snmp-3.1.0-1.el7.centos.noarch
centreon-plugin-Network-Switchs-Moxa-Snmp-20211215-090334.el7.centos.noarch

I have an error with cpu and memory with Moxa switch : 

![image](https://user-images.githubusercontent.com/61595839/146448450-b5450c7b-a3c8-41d6-bf07-43946b7c44af.png)

Uninstall plugin pack / reinstall : same problem

CLI:
/usr/lib/centreon/plugins//centreon_moxa_switch_snmp.pl --plugin=network::moxa::switch::snmp::plugin --mode=memory --hostname=x.x.x.x --snmp-version='3' --snmp-community='public' --snmp-username=admin --snmp-autoreduce --snmp-timeout='2' --authprotocol=SHA --authpassphrase='xxxxxxxx' --privprotocol=DES --privpassphrase='xxxxxxxx' --warning-usage='80' --critical-usage='90'
Unknown option: warning-usage at /usr/lib/centreon/plugins//centreon_moxa_switch_snmp.pl line 141.

/usr/lib/centreon/plugins//centreon_moxa_switch_snmp.pl --plugin=network::moxa::switch::snmp::plugin --mode=cpu --hostname=x.x.x.x --snmp-version='3' --snmp-community='public' --snmp-username=admin --snmp-autoreduce --snmp-timeout='2' --authprotocol=SHA --authpassphrase='xxxxxxxx' --privprotocol=DES --privpassphrase='xxxxxxxx' --warning-5s='80'  --critical-5s='90' --warning-30s='80'  --critical-30s='90' --warning-300s='80'  --critical-300s='90'
Unknown option: warning-5s at /usr/lib/centreon/plugins//centreon_moxa_switch_snmp.pl line 141.

**Comment by Sims24** [comment]
Can you click on the Moxa logo and screenshot the Pack details please? Or provide your Pack version? 

Thanks

**Comment by gagzou** [comment]
Moxa Pack : 
![image](https://user-images.githubusercontent.com/61595839/146540748-9178db6e-4963-4c67-939c-bb6c99504b1b.png)

centreon-pack-network-moxa-switch-snmp-3.1.0-1.el7.centos.noarch
centreon-plugin-Network-Switchs-Moxa-Snmp-20211215-090334.el7.centos.noarch

**Comment by gagzou** [comment]
it does not offer me an update on the plugin pack interface :-(

centreon-pp-manager-20.10.2-1.el7.centos.noarch

**Comment by Sims24** [comment]
Last version is 3.1.0. 

If you have an offline licence, could you try to issue this command on the central server please: 

`yum update centreon-pack-network-moxa-switch-snmp`

If you're using an online subscription let me know I will check on our side.

**Comment by gagzou** [comment]
On this platform, we are an online subscription.

**Comment by gagzou** [comment]
On production platform (offline licence) , I have the proposal to update the pack.
The problem should come from your side (online subscription).

**Comment by gagzou** [comment]
I have received the update of the pack (online) and cpu and memory are working.
Thanks.

**Comment by gagzou** [comment]
I have received the update of the pack (online) and cpu and memory are working.

**Comment by Sims24** [comment]
perfect thanks
