### ISSUE TITLE
MSSQL Incremental backups check

### ISSUE THREAD

**Issue by LaurentV9** [centreon/centreon-plugins#3328]
It should be useful to have a backup age for full and also for incremental.
For now, the backup age is just based on full backup and for some of organizations, full backups are only done each week and incremental each day.

the query should be:

select
database_name, max(backup_finish_date)
from msdb.dbo.backupset
where type != 'L'
and database_name not in ('master','model')
group by database_name

Regards,

Laurent

Thanks for using centreon-plugins! Please follow the indications shown below according to your issue and describe it in English.

## New Plugins and modes

To develop a Plugin/mode, we need the following:
* SNMP: MIBs files and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk)
* HTTP API (SOAP, Rest/Json, XML-RPC): the documentation and some curls examples
* CLI: command line examples
* SQL: requests
* JMX: mbean names and attributes

If some parts of information are confidentials, please send them directly by email to qgarnier@centreon.com and sbomm@centreon.com.

Please note that all the developments are open-source. We can't give a date for the development, achievement or release. If it's a priority for you,
send us an email about it (qgarnier@centreon.com and sbomm@centreon.com) and we'll put you in touch with our company.

## Bug/Question

If you are reporting a bug/question, make sure that there aren't any similar/duplicates issues already open. You 
can ensure this by searching the issue list for this repository. If so, please close your issue and add a comment to the existing one instead.

Otherwise, open a new issue and provide all parts of information you can (full command line used, actual output, expected output, error message...).

**Comment by Sims24** [comment]
Hi @LaurentV9 

Thansk, do you have any sample results of such query execution to share? 

Regards,

**Comment by LaurentV9** [comment]
Hi,
The result should be like

SqlAssessment    2021-12-16 21:04:58.000
Zzzzzzzz                2021-12-16 21:05:00.000
msdb                    2021-12-16 21:04:57.000
distribution         2021-10-22 20:36:35.000
xxx                        2021-05-25 20:11:02.000
yyy                        2021-12-16 21:04:53.000
SupportDBA        2021-12-16 21:05:02.000

Or a number of second, as for initial backupage

Or more simple:

Can you have a BackupAge for Full and another for Incremental?
In that case, no need to create a new query, just adapt that you use for backupage and separate full and incremental.

Regards,

Laurent

**Comment by Sims24** [comment]
Could be a way yes. With an alert when incremental backup is older than 1 day. Makes sense.

**Comment by LaurentV9** [comment]
Yes, should be great 😊

L.

**Comment by LaurentV9** [comment]
Should be great with these 3 types 😊

Laurent

**Comment by garnier-quentin** [comment]
Could you test with that version ?
https://github.com/centreon/centreon-plugins/archive/refs/heads/enh-mssql-backup.zip

**Comment by LaurentV9** [comment]
Hi,

Thank you for this development but…

Sorry, I’m a newbie on Centreon. How could I test this development? Again, sorry for this question ☹

Laurent

**Comment by garnier-quentin** [comment]
You download that archive https://github.com/centreon/centreon-plugins/archive/refs/heads/enh-mssql-backup.zip on your centreon poller. You unzip the file and you execute it:
```
perl centreon_plugins.pl --plugin=database::mssql::plugin --mode=backup-age...
```

**Comment by LaurentV9** [comment]
Perfect, it works very good.
I’m sure a lot of people will be interested by that 😊

Laurent

**Comment by garnier-quentin** [comment]
thanks for the feedback. it's merged
