### ISSUE TITLE
cloud-vmware-velocloud - session cookie is not renewed

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#3331]
Hi,

We recently had a problem that all velocloud checks went to unknown because the session cookie expired. Normally the statefile should be deleted and created again. This also works in normal cases .. This plugin code works fine ...

![image](https://user-images.githubusercontent.com/46994680/146923953-53d9cf35-0ec6-4775-b08b-2a0075b6c334.png)

In my case the http response code was even a 200 OK but with internal token error message and a "Expires: 0" Information that normally isn't there ..

![image](https://user-images.githubusercontent.com/46994680/146924193-5ff34b83-74c2-401c-b503-0b6e531d1eaa.png)

In this case the plugin code will not renew the session.

Can this case please be covered additionally with ?

**Comment by garnier-quentin** [comment]
When it's ok, there is an expires header ? Or only when we have an issue.

**Comment by rmorandell-pgum** [comment]
When it's ok there is no expires header ..

![image](https://user-images.githubusercontent.com/46994680/146935508-f8028b80-63b6-4d0b-b59e-c76f4e316472.png)

**Comment by garnier-quentin** [comment]
I have done a patch. Could you test with last git version ?

**Comment by rmorandell-pgum** [comment]
I have tested the plugin and it works. Unfortunately I can't force this particular error case. I will watch the statefile and see if it is refreshed regularly. thanks for your quick help

**Comment by garnier-quentin** [comment]
I understand. It should be ok ;)
