### ISSUE TITLE
add(plugin): Lenovo rackswitch G7052 snmp

### ISSUE THREAD

**Issue by Nibeck1309** [centreon/centreon-plugins#3338]
Hello,

I have Lenovo racswitch G7052.
I don' t found snmp plugin for monitor it;
I attach zip file with mibs file.
It is possible have plugin with it ?

[lenovo_switch_g7052.zip](https://github.com/centreon/centreon-plugins/files/7770364/lenovo_switch_g7052.zip)
b

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk of that equipment please ?

**Comment by Nibeck1309** [comment]
Hello,

In attachment, full snmpwalk.
[lenovo_G7052.txt](https://github.com/centreon/centreon-plugins/files/7801383/lenovo_G7052.txt)

**Comment by garnier-quentin** [comment]
The snmpwalk is incomplete. I need the snmpwalk of the following branch:
.1.3.6.1.4.1.20301

**Comment by Nibeck1309** [comment]
in attachment the snmpwalk of the following branch:
.1.3.6.1.4.1.2030
[lenovo_G7052-2.txt](https://github.com/centreon/centreon-plugins/files/7806445/lenovo_G7052-2.txt)
1

**Comment by garnier-quentin** [comment]
Thanks. But could you provide it with following options lease ?
snmpwalk -ObentU -v 2c -c COMMUNITY IP .1.3.6.1.4.1.20301

**Comment by garnier-quentin** [comment]
The walk is still incomplete. Please walk the following branches:
```
.1.3.6.1.4.1.20301.2.7.18.1.2.12
.1.3.6.1.4.1.20301.2.7.18.1.3.1
```

**Comment by Nibeck1309** [comment]
snmpwalk -ObentU -v 3 [We used only snmp v3 with auth en Pass] IP 

.1.3.6.1.4.1.20301
[lenovo_G7052-3.txt](https://github.com/centreon/centreon-plugins/files/7806820/lenovo_G7052-3.txt)

.1.3.6.1.4.1.20301.2.7.18.1.2.12
[lenovo_G7052-4.txt](https://github.com/centreon/centreon-plugins/files/7806823/lenovo_G7052-4.txt)

.1.3.6.1.4.1.20301.2.7.18.1.3.1
[lenovo_G7052-5.txt](https://github.com/centreon/centreon-plugins/files/7806826/lenovo_G7052-5.txt)

**Comment by garnier-quentin** [comment]
You can test with last git version: ```--plugin=network::lenovo::rackswitch::snmp::plugin```

**Comment by Nibeck1309** [comment]
thks,

I test this
