### ISSUE TITLE
[hardware::ups::standard::rfc1628] mode input-lines

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#334]
Hi!

Prompt, interrupt the schedule and the lack of input voltage readings at zero voltage is a bug or a feature?)

./centreon_plugins.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --mode=input-lines --hostname=172.28.203.254 --snmp-community=public --snmp-version=1
OK: Input Line '1' Frequence : -0.10 Hz, Power : -1.00 W, Current : -0.10 A | 'frequence'=-0.10Hz;;;; 'power'=-1.00W;;;; 'current'=-0.10A;;;;

Voltage?

![16-02-16 09 37 02](https://cloud.githubusercontent.com/assets/15804154/13068906/e324db02-d490-11e5-8030-5f2385557f59.png)

SNMPv2-UPS-MIB::upsInputNumLines.0 = INTEGER: 1
SNMPv2-UPS-MIB::upsInputVoltage.1 = INTEGER: 0 RMS Volts

On the other UPS is not a zero input voltage to the output of the command is indicated:
./centreon_plugins.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --mode=input-lines --hostname=172.28.203.251 --snmp-community=public --snmp-version=1
OK: Input Line '1' Voltage : 226.00 V, Frequence : 50.00 Hz - Input Line '3'  - Input Line '2'  | 'voltage_1'=226.00V;;;; 'frequence_1'=50.00Hz;;;;

**Comment by maksimatveev** [comment]
Accordingly, there is no possibility to set the threshold value for the input voltage

**Comment by garnier-quentin** [comment]
Could you test it ? You can set threshold for votlage with: --warning-voltage and/or --critical-voltage

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, I will try to test at the first opportunity. Thx!

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, is not able to test - do not cut off the electricity =)
I wanted to ask, did you manage in the mode "input-lines" to remove the extra line. Can I remove them from the mode "output-lines", too? It seems to me that this is true only for three-phase UPS.
OK: Output Line '1' Voltage : 229.00 V, Load : 9.00 % - **Output Line '3' Load : 0.00 % - Output Line '2' Load : 0.00 %** - Load Standard Deviation : 4.24

To do this, you need a separate request or you remember? I hope for understanding =)

**Comment by maksimatveev** [comment]
@garnier-quentin Quenti, did not help your fix.

![04-03-16 20 46 08](https://cloud.githubusercontent.com/assets/15804154/13535222/34445aa0-e24a-11e5-89db-f4ac52fd2cc1.png)

Status information	OK: Input Line 1
The input voltage at zero is not displayed. Accordingly, the threshold values are not considered.

./centreon_plugins.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --mode=input-lines --hostname=172.29.116.254 --snmp-community=3rerbifverbif --snmp-version=1
OK: Input Line '1' Frequence : -0.10 Hz, Current : -0.10 A, Power : -1.00 W | 'frequence'=-0.1Hz;;;; 'current'=-0.1A;;;; 'power'=-1W;;;;

snmpwalk:
SNMPv2-UPS-MIB::upsInputVoltage.1 = INTEGER: 0 RMS Volts

![04-03-16 20 59 14](https://cloud.githubusercontent.com/assets/15804154/13535572/01440a86-e24c-11e5-8bc1-fd2003990007.png)

**Comment by maksimatveev** [comment]
@garnier-quentin After power is restored:
SNMPv2-UPS-MIB::upsInputVoltage.1 = INTEGER: 210 RMS Volts

OK: Input Line '1' Frequence : -0.10 Hz, Voltage : 210.00 V, Current : -0.10 A, Power : -1.00 W | 'frequence'=-0.1Hz;;;; 'voltage'=210V;;;; 'current'=-0.1A;;;; 'power'=-1W;;;;

![04-03-16 21 27 40](https://cloud.githubusercontent.com/assets/15804154/13536269/086a6554-e250-11e5-805e-1c3e5fdd7e5a.png)

![04-03-16 21 28 40](https://cloud.githubusercontent.com/assets/15804154/13536293/290db892-e250-11e5-87a0-ab37010eae17.png)

**Comment by garnier-quentin** [comment]
That's normal if you have a power source problem no ? 
Don't understand what you want ?

**Comment by maksimatveev** [comment]
@garnier-quentin UPS is operating normally.
When you disconnect the AC plugin in mode --input-lines shows OK. In this case the necessary threshold values are set.
Example when power is off:
OK: Input Line '1' Frequence : -0.10 Hz, Current : -0.10 A, Power : -1.00 W | 'frequence'=-0.1Hz;;;; 'current'=-0.1A;;;; 'power'=-1W;;;;
Voltage, even if the zero does not appear. What value are compared in the threshold?

The same UPS, but with the included external power supply:
OK: Input Line '1' Frequence : -0.10 Hz, **Voltage : 210.00 V**, Current : -0.10 A, Power : -1.00 W | 'frequence'=-0.1Hz;;;; 'voltage'=210V;;;; 'current'=-0.1A;;;; 'power'=-1W;;;;
The voltage value will appear again.

Once again, take a look at this:
Status information OK: Input Line 1
It seems to me that the external power supply output should look like this:
Status information CRITICAL: Input Line 1 **0.00 V**

I assume that the plug-in with the power off "sees" that the voltage value of 0, and stops the output value. Hence the inability to use the thresholds. I hope that the translator was able to convey my meaning. Always ready to answer any questions.

**Comment by garnier-quentin** [comment]
Ok i see. I should display 0 values ? I can.

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, thank you. I hope you can fix it.

**Comment by maksimatveev** [comment]
@garnier-quentin Hi! You got to fix this problem?

**Comment by maksimatveev** [comment]
@garnier-quentin Hello, Quentin! Maybe you need help to resolve this issue?

**Comment by garnier-quentin** [comment]
Could youtest it ?

**Comment by maksimatveev** [comment]
@garnier-quentin It is necessary to wait until electricity is shut off, I'll let you know if you will have no problems. Thank you!

**Comment by garnier-quentin** [comment]
Ok. I close it. Re-open it if there is a problem.

**Comment by maksimatveev** [comment]
@garnier-quentin Remind please how to check only a single line:
[root@rnd-oms-centreon centreon-plugins]# ./centreon_plugins.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --hostname=172.28.232.254 --snmp-community=public --snmp-version=1 --mode=input-lines --critical-voltage=176:264 --filter-counters='^voltage$'
CRITICAL: Input Line '2' Voltage : 0.00 V - Input Line '3' Voltage : 0.00 V | 'voltage_1'=221V;;176:264;; 'voltage_2'=0V;;176:264;; 'voltage_3'=0V;;176:264;;

Maybe there is a switch to a single-phase power supply? The note did not find description.

**Comment by garnier-quentin** [comment]
You cannot. You can filter perfdata. That's why i removed the '0'. I can't know if it comes from power source offline or only 1 phase.

**Comment by maksimatveev** [comment]
@garnier-quentin Can I rewrite it for single-phase UPS? or need to create a separate mode?

**Comment by garnier-quentin** [comment]
You can do what you want and create a specific mode for you ;)

**Comment by maksimatveev** [comment]
@garnier-quentin 
110        my ($base, $instance) = ($1 . '.' . $2, $3);
in this string, can remove the "extra" phase? I perl still poorly "read".

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, are you that it rewrite? I have an upgrade everything worked
 ./centreon_plugins.pl --plugin=hardware::ups::standard::rfc1628::snmp::plugin --hostname=172.28.232.254 --snmp-community=public --snmp-version=1 --mode=input-lines --critical-voltage=176:264 --filter-counters='^voltage$'
OK: Input Line '1' Voltage : 220.00 V | 'voltage'=220V;;176:264;;

**Comment by garnier-quentin** [comment]
Yes i revert my commit. You can do the patch if you want on your version.

**Comment by maksimatveev** [comment]
@garnier-quentin It seems to me that the output commands began to look for another =/ 
earlier: CRITICAL: Input Line '2' Voltage : 0.00 V - Input Line '3' Voltage : 0.00 V
now: OK: Input Line '1' Voltage : 220.00 V

may not have to alter anything? =)

**Comment by maksimatveev** [comment]
@garnier-quentin really strange. Now thresholds are triggered as expected:
CRITICAL: Input Line '1' Voltage : 221.00 V | 'voltage'=221V;;**176:210**;;
CRITICAL: Input Line '1' Voltage : 221.00 V | 'voltage'=221V;;**250:264**;;

**Comment by maksimatveev** [comment]
@garnier-quentin 
Quentin, as if to check the condition of the number of input lines?
SNMPv2-UPS-MIB::upsInputNumLines.0 = INTEGER: 1
Also there for outgoing lines:
SNMPv2-UPS-MIB::upsOutputNumLines.0 = INTEGER: 1

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, a solution has been found? Maybe create a separate plug-in for single-phase UPS?

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, can I count on your help in this issue?

**Comment by garnier-quentin** [comment]
I'll work on it soon yes

**Comment by lscotti-itmed** [comment]
Hello @garnier-quentin did you do something on this issue ?
I'm checking an UPS with this plugin. When there is power the output is the following
`OK: Input Line '1' Frequence : 49.90 Hz, Voltage : 225.00 V, Current : 1.50 A`

When there is no power the output is the following;
`OK:`
