### ISSUE TITLE
apps::protocols::x509::plugin Certificate/HTTPS UNKNOWN: OK

### ISSUE THREAD

**Issue by TomSVT** [centreon/centreon-plugins#3340]
Hello,

Like in #2943, the output of the command is "UNKNOWN: OK" but i can't find the same option "--ssl-ignore-errors".

`/usr/lib/centreon/plugins//centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --mode=certificate --custommode=https --hostname=graveur.radio.domain.fr  --port='443' --urlpath='/MARS/Login.aspx' --warning-status='%{expiration} < 90' --critical-status='%{expiration} < 30'  --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --verbose`

with --debug

`UNKNOWN: OK`
======> request send
GET https://graveur.radio.domain.fr:443/MARS/Login.aspx
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 200 OK
Cache-Control: private
Connection: close
Date: Mon, 27 Dec 2021 07:22:47 GMT
Server: Microsoft-IIS/10.0
Content-Length: 6978
Content-Type: text/html; charset=utf-8
Client-Date: Mon, 27 Dec 2021 07:22:48 GMT
Client-Peer: 172.16.1.81:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /DC=fr/DC=domain/CN=cert-domain-fr
Client-SSL-Cert-Subject: /CN=graveur.radio.domain.fr
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Link: <App_Themes/BlueTheme/Activity.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/Configuration.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/CustomDate.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/CustomDate2.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/CustomMediaSize.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/Data.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/Default.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/Default4.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/DPStatus.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/Information.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/KingTestPage.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/Login.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/LoginNeeded.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/MarsMasterPage.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/Media.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/MediaInformation.css>; rel="stylesheet"; type="text/css"
Link: <App_Themes/BlueTheme/WebUserControlScript.css>; rel="stylesheet"; type="text/css"
Set-Cookie: ASP.NET_SessionId=hq1r2g45evfu0bmmicumfl55; path=/; HttpOnly
Title: MARS
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET

Versions 

`CentOS Linux release 7.9.2009 (Core)
Nom                 : perl-IO-Socket-SSL
Architecture        : noarch
Version             : 1.94
Révision            : 7.el7`

I tried with curl but I have another error : 
`/usr/lib/centreon/plugins//centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --mode=certificate --custommode=https --hostname=graveur.radio.domain.fr  --port='443' --http-backend=curl --curl-opt="CURLOPT_SSL_VERIFYPEER => 0" --curl-opt="CURLOPT_SSL_VERIFYHOST => 0"`

UNKNOWN: curl setopt error: 'An unknown option was passed in to libcurl'.

Do you have a clue ?

**Comment by garnier-quentin** [comment]
You cannot use the backend curl on centos 7. The libcurl 7.50 is needed (https://curl.se/libcurl/c/CURLOPT_CERTINFO.html). So it needs to work with lwp backend for centos 7. But i cant reproduce it.

**Comment by garnier-quentin** [comment]
Ok it's the same ticket: https://github.com/centreon/centreon-plugins/issues/2621
So i will only work with curl backend (but it cannot be used on centos 7). Maybe you could use the custommode tcp  ?

**Comment by TomSVT** [comment]
Hello Quentin,

I thank you for your answer and i wish you a HNY.

I don't know why this specific website is not working, the web server is Microsoft IIS on WS 2016. 
Another server with almost the same setup is working : 

```
OK: Certificate for 'cliniciens.radio.domain.fr' expires in '241' days
======> request send
GET https://cliniciens.radio.domain.fr:443/
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 200 OK
Date: Wed, 05 Jan 2022 12:01:27 GMT
Accept-Ranges: bytes
ETag: "ea639992b282d61:0"
Server: Microsoft-IIS/10.0
Content-Length: 703
Content-Type: text/html
Last-Modified: Fri, 04 Sep 2020 11:57:32 GMT
Client-Date: Wed, 05 Jan 2022 12:01:27 GMT
Client-Peer: 172.16.2.25:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /DC=fr/DC=domain/CN=cert-domain-fr
Client-SSL-Cert-Subject: /CN=pacs.radio.domain.fr/CN=cliniciens.radio.domain.fr/CN=zfp.domain.fr/CN=uvc.domain.fr
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Title: IIS Windows Server
X-Powered-By: ASP.NET
```

![image](https://user-images.githubusercontent.com/76195801/148214089-7da9c6f1-068c-43eb-96d1-75b473be92c0.png)

I tried with TCP but I can't make it working :
```

./centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --custommode=tcp --mode=certificate --hostname=graveur.domain.fr --port=443 --verbose --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --debug
UNKNOWN: Error creating SSL socket: Argument invalide, SSL error: IO::Socket::IP configuration failed
```

**Comment by garnier-quentin** [comment]
Please use the following option: ```--ssl-opt="SSL_verify_mode=>SSL_VERIFY_NONE"```

**Comment by TomSVT** [comment]
Thank you ! It's working, I had to add "--ssl-ignore-errors"
Rookie mistake for the missing character.

```
./centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --custommode=tcp --mode=certificate --hostname=graveur.radio.domain.fr --port=443 --ssl-opt="SSL_verify_mode=>SSL_VERIFY_NONE" --ssl-ignore-errors
OK: Certificate for 'graveur.radio.domain.fr' expires in '584' days [2023-08-12T14:09:56Z] - Issuer: '/DC=fr/DC=domain/CN=cert-domain-fr' 
```

**Comment by garnier-quentin** [comment]
thanks for the feedback!
