### ISSUE TITLE
MSSQL Servers specify Instances

### ISSUE THREAD

**Issue by LaurentV9** [centreon/centreon-plugins#3341]
Hi all,

I'm looking for some help for SQL Server.

Is it possible to target a specific instance of SQL server? 
In fact, I have 2 different issues.

1. I have a SQL EXPRESS instance
2. 2. I have servers with multiple instances

I don't find how to specifiy specific Instances.

Can you help me?

Laurent

**Comment by Sims24** [comment]
Hi, 

Yes you can with the --datasource option. Try like this, should help you solve both issues. 

`--datasource='Sybase:server=SERVERNAME\\INSTANCENAME'`

**Comment by LaurentV9** [comment]
Top. It works.

Thanks a lot.

Laurent

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Simon Bomm ***@***.***>
Envoyé : Monday, December 27, 2021 2:21:37 PM
À : centreon/centreon-plugins ***@***.***>
Cc : Vienne Laurent ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] MSSQL Servers specify Instances (Issue #3341)


Hi,

Yes you can with the --datasource option. Try like this, should help you solve both issues.

--datasource='Sybase:server=SERVERNAME\\INSTANCENAME'

—
Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcentreon%2Fcentreon-plugins%2Fissues%2F3341%23issuecomment-1001567484&data=04%7C01%7Claurent.vienne%40creos.net%7C4737ca22d9ad40023cc708d9c93fd8e6%7Cbd6aafaf326340f5a7956f94d617839e%7C0%7C0%7C637762098327937613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5pxr8zB7gdhA%2FY9n1JXLhRyNdgbcIuVR2rRjHV2pnTg%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARF4TOUQU7HBNWU4JLBQGRDUTBR6DANCNFSM5KZ4WD3Q&data=04%7C01%7Claurent.vienne%40creos.net%7C4737ca22d9ad40023cc708d9c93fd8e6%7Cbd6aafaf326340f5a7956f94d617839e%7C0%7C0%7C637762098327937613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BW8KhY8bHeu52RResEP6sO5bXdziZpdx4kamUTvwS2w%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Claurent.vienne%40creos.net%7C4737ca22d9ad40023cc708d9c93fd8e6%7Cbd6aafaf326340f5a7956f94d617839e%7C0%7C0%7C637762098327937613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=znVNnqpp4J8fpY5yywrcYZWjsolj9MQdRDa2AOwiJGc%3D&reserved=0> or Android<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Claurent.vienne%40creos.net%7C4737ca22d9ad40023cc708d9c93fd8e6%7Cbd6aafaf326340f5a7956f94d617839e%7C0%7C0%7C637762098327937613%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Bfsl4G0Gimg5UfImgtto6H8KHV0bqvDXIh2IVnaTB8Q%3D&reserved=0>.
