### ISSUE TITLE
netgear snmp storage doesn´t find storage by name

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#3342]
Hi,

I´m using netgear snmp storage mode, which returns by default all storages:
`perl centreon_plugins.pl --plugin=storage::netgear::readynas::snmp::plugin --mode=storage --hostname=te-backup-nas`

Result:
`OK: All storages are ok | 'count'=9;;;0; 'used_/'=562241536B;;;0;3954900992 'used_/dev/shm'=0B;;;0;1057603584 'used_/run'=360448B;;;0;1057603584 'used_/run/lock'=9261056B;;;0;528801792 'used_/sys/fs/cgroup'=0B;;;0;1057603584 'used_/data'=4162966388736B;;;0;5986298363904 'used_/home'=4162966388736B;;;0;5986298363904 'used_/apps'=4162966388736B;;;0;5986298363904 'used_/run/nfs4/home'=4162966388736B;;;0;5986298363904
`

When I try to get a specific storage, e.g. used_/data, I tried the following command:
`perl centreon_plugins.pl --plugin=storage::netgear::readynas::snmp::plugin --mode=storage --hostname=te-backup-nas --storage='used_/data' --name`

But the result tells me:
UNKNOWN: No storage found. Can be: filters, cache file.

What can be the cause? Have I tried the command wrong?

**Comment by Sims24** [comment]
Hi @benhartwich 

You may want to try `--storage='/data'`  instead. 

`used_` is the default prefix for metrics but not part of the name of the storage itself.

I recommend you to add the --use-new-perfdata option which will generate prettier and meaningful metric names. It also make it more straightforward what is a metric and what is the instance for a given metric. 

Thanks

**Comment by benhartwich** [comment]
Thanks, solved! Didn´t know, that a preview is used.

**Comment by benhartwich** [comment]
Is there any possibility to use more names? E.g.  `--storage='/, /tmp' --name` but this doesn´t work

**Comment by garnier-quentin** [comment]
It's a reguler expression. You can use ```|```

**Comment by benhartwich** [comment]
@garnier-quentin : thanks, but it doesn´t work - e.g. `--storage='/ | /tmp' --name`

**Comment by garnier-quentin** [comment]
Like that: ```--storage='/|/tmp' --name```

**Comment by benhartwich** [comment]
Unfortunatelly not: 
`perl centreon_plugins.pl --plugin=storage::netgear::readynas::snmp::plugin --mode=storage --hostname=te-backup-nas --storage='/data|/home' --name
UNKNOWN: No storage found. Can be: filters, cache file.
`

**Comment by garnier-quentin** [comment]
It should work. What do you have without filters ?

**Comment by benhartwich** [comment]
This is the whole result without any filters:

`OK: All storages are ok | 'count'=9;;;0; 'used_/'=562081792B;;;0;3954900992 'used_/dev/shm'=0B;;;0;1057603584 'used_/run'=360448B;;;0;1057603584 'used_/run/lock'=9261056B;;;0;528801792 'used_/sys/fs/cgroup'=0B;;;0;1057603584 'used_/data'=4176898936832B;;;0;5986298363904 'used_/home'=4176898936832B;;;0;5986298363904 'used_/apps'=4176898936832B;;;0;5986298363904 'used_/run/nfs4/home'=4176898936832B;;;0;5986298363904`

**Comment by garnier-quentin** [comment]
You need to add the option--regexp: ```--storage='/|/tmp' --name --regexp```
