### ISSUE TITLE
Wrong Values with large storages -  os::linux::snmp::plugin --mode=storage 

### ISSUE THREAD

**Issue by androtutur** [centreon/centreon-plugins#3348]
Hello, 

I have differents values between the command :  df -P -k -T /product/ora* and the plugins when I try to monitor large storages. (/product/oradat for example)

command :
`df -P -k -T /product/ora*`
 Result: 
Filesystem                   Type 1024-blocks       Used  Available Capacity Mounted on
/dev/mapper/productvg-oracle ext4    15350768   12509808    2054528      86% /product/oracle
/dev/mapper/productvg-oradat ext4  9824124464 8845361468  479801980      95% /product/oradat
/dev/mapper/productvg-orafra ext4  1548053708   66345616 1403064892       5% /product/orafra

Plugin : 
 `/usr/lib/centreon/plugins//centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=X.X.X.X --snmp-version='2c' --snmp-community='XXXX'  --storage='/product/ora*' --name --regexp --display-transform-src='' --display-transform-dst='' --warning-usage='95' --critical-usage='98' --verbose --space-reservation=5`
Result: 
OK: All storages are ok | 'count'=3;;;0; 'used_/product/oracle'=12810043392B;0:14933227110;0:15404802703;0;15719186432 'used_/product/oradat'=261557121024B;0:1200619907481;0:1238534220349;0;1263810428928 'used_/product/orafra'=67937910784B;0:1505946647142;0:1553502857052;0;1585206996992
Storage '/product/oracle' Usage Total: 14.64 GB Used: 11.93 GB (85.78%) Free: 1.98 GB (14.22%)
Storage '/product/oradat' Usage Total: 1.15 TB Used: 243.59 GB (21.79%) Free: 874.57 GB (78.21%)
Storage '/product/orafra' Usage Total: 1.44 TB Used: 63.27 GB (4.51%) Free: 1.31 TB (95.49%)

I'm working on a redhat 6.9.
 
Installed Packages
Name        : net-snmp
Arch        : x86_64
Epoch       : 1
Version     : 5.5
Release     : 60.el6
Size        : 816 k

My plugin version is : 
centreon-plugin-Operatingsystems-Linux-Snmp-20211102-130335.el7.centos.noarch

I
Could you  please help me to investigate on this issue ? 

Thanks a lot,
Maxime

**Comment by garnier-quentin** [comment]
It's a known issue of SNMP (big disks). Maybe you can try the option: ```--counters-overflow```
