### ISSUE TITLE
Support Storage HPE SimpliVity REST API

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#3349]
Hi,
Is it possible to add a plugin to monitor HPE SimpliVity storage via REST API?

https://developer.hpe.com/platform/hpe-simplivity/interactive-rest-api-reference/
Examples scripts here (but not complete) https://github.com/sdouce/simplivity-plugins-nagios

Interresting values:

GET /api/hosts
Field name and state (should be ALIVE for all hosts)

GET /hosts/{hostId}/hardware
Field status

GET /api/omnistack_clusters?show_optional_fields=true
Field allocated_capacity and used_capacity to get percent_used
Optional:  field deduplication_ratio, compresion_ratio and efficiency_ratio

GET /api/virtual_machines?show_optional_fields=true
Field ha_status (should be SAFE)

![simplivity](https://user-images.githubusercontent.com/322320/147600136-a2de5579-9e85-4df4-8fca-564a891cbac4.PNG)

I will complete this issue with information if needed

Thanks

**Comment by garnier-quentin** [comment]
Could you provide the curl results ?
We use that auth: https://developer.hpe.com/platform/hpe-simplivity/authenticating-against-hpe-omnistack-api/ ?

https://developer.hpe.com/platform/hpe-simplivity/home/
http://www.virtu-desk.fr/blog/infrastructures-hyper-convergentes/l-architecture-omnistack-de-simplivity.html
