### ISSUE TITLE
network::cisco::ironport::snmp::plugin add modes

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#335]
Hi,

Can you please add these enhancements to network::cisco::ironport::snmp::plugin plugin:

Number of update failures: 1.3.6.1.4.1.15497.1.1.1.13.1.4
Number of DNS requests waiting to be sent: 1.3.6.1.4.1.15497.1.1.1.16.0
Number of messages in the work queue: 1.3.6.1.4.1.15497.1.1.1.11.0
Queue space status: enough space, queue near full or queue full:1.3.6.1.4.1.15497.1.1.1.5.0
Number of DNS requests that have been sent but for which no
reply has been received 1.3.6.1.4.1.15497.1.1.1.15.0

If you need snmpwalk, let me know, I will send it to your email.

**Comment by kadrika** [comment]
And also Key expiration: 1.3.6.1.4.1.15497.1.1.1.12.1.4

**Comment by garnier-quentin** [comment]
i'll need a complete snmpwalk yes.

**Comment by garnier-quentin** [comment]
There is a mode mail-usage.
