### ISSUE TITLE
centreon_pdu_apc_snmp : OID not managed

### ISSUE THREAD

**Issue by mat44444** [centreon/centreon-plugins#3357]
Command: 
/usr/lib/centreon/plugins//centreon_pdu_apc_snmp.pl  --plugin=hardware::pdu::apc::snmp::plugin --mode=load --hostname=XX.XXX.XX.XX  --snmp-version='2c' --snmp-community='XXXX'  --verbose

Error message returned by the script:
****Use of uninitialized value in multiplication (*) at /usr/lib/centreon/plugins//centreon_pdu_apc_snmp.pl line 7488.
UNKNOWN: No device found.****

Model Number
**AP7920B**

Hardware Revision
**B2**

FirmwareVersion
**6.9.6**

SNMPWALK
[apc.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/7794053/apc.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
Thanks. It shoud be ok with last git version.
