### ISSUE TITLE
char | at the end of the check output

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#3361]
Hello,

In our monitoring the centreon plugin without performance data returns a char "|" at the end of the display output.

see here 3 different checks
---------------------------
centreon_plugins.pl --plugin="os::windows::snmp::plugin" --snmp-version="2c" --snmp-community="public" --mode="service" --service="Hyper-V Virtual Machine Management" --critical="1:" --warning="" --hostname=x.x.x.x
CRITICAL: Service problem 'Hyper-V Virtual Machine Management' |

| At the end of the line without anything behind

centreon_plugins.pl --plugin="database::elasticsearch::restapi::plugin" --mode="license" --http-backend="curl" --username="icinga" --password="icinga" --port="9200"  --hostname=x.x.x.x
CRITICAL: License Status 'expired' [type: platinum] [issued to: text] [issue date: 2020-12-23T00:00:00.000Z] |

| At the end of the line without anything behind

centreon_plugins.pl --plugin="storage::fujitsu::eternus::dx::ssh::plugin" --mode="psu" --ssh-option="-l=loginname" --hostname=x.x.x.x
OK: All 10 power supplies are ok. |

| At the end of the line without anything behind

I think this is a general problem and not linked to one specific module.
wouldn't it be better not to put the char "|" at the end if no performance info is given.

regards,
Geert

**Comment by gbin2265** [comment]
hello, 

I did some research in the source code.

When I use the option --output-ignore-perfdata the char "|" disappears.


If I look in the source code, I think there should be an extra check here.

File = centreon/plugins/output.pm
Line = 518
 
 if ($force_ignore_perfdata == 1) {
        print "\n";
    } else {
        print '|';
        $self->change_perfdata();
		
Shouldn't it be checked first that the "change_perfdata" is empty or not before a print is made of the char "|"

regards,
Geert

**Comment by garnier-quentin** [comment]
I have done that option for that case. I will do something to patch it.

**Comment by garnier-quentin** [comment]
It's done in last git version.

**Comment by gbin2265** [comment]
Ok, 

thanks for the update 

I'm going to try Thursday

Regards,
Geert

**Comment by gbin2265** [comment]
The update for me works perfectly ! 

Thanks !
