### ISSUE TITLE
[apps::protocols::http::plugin] timeout with curl, opt-exit option

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3362]
Hi,

By switching the http check to curl (--http-backend=curl), the timeout is not interpreted in the same way as with lwp : 
I must add '--opt-exit=critical' to have a critical after 5s without response.

Is it possible to specify the cause of the 'opt-exit' to only have a critical for a timeout ?
Or have the same interpretation as with lwp (timeout = critical) ?

Best regards.

**Comment by garnier-quentin** [comment]
I can have the same behavior with lwp if a check the client-warning:
https://github.com/libwww-perl/libwww-perl/issues/277

Maybe i can create a custom HTTP code 4xx error for the client timeout:
```4xx: Client Error - The request contains bad syntax or cannot be fulfilled```

**Comment by garnier-quentin** [comment]
There is a new http code: 450. It's the same for lwp and curl backend.
