### ISSUE TITLE
[network::checkpoint::plugin] memory mode enhancement

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#337]
Can you please enhancement the memory mode:

*_Counters *_
Counter: Total real RAM
OID: memTotalReal64 .1.3.6.1.4.1.2620.1.6.7.4.3
Format: String
Description: Total real memory in bytes. Memory used by applications.

Counter: Active real RAM
OID: memActiveReal64 .1.3.6.1.4.1.2620.1.6.7.4.4
Format: String
Description: Active real memory (memory used by applications that is not cached to the disk) in bytes.

Counter: Free real RAM
OID: memFreeReal64 .1.3.6.1.4.1.2620.1.6.7.4.5
Format: String
Description: Free memory available for applications in bytes.

Counter: Total virtual RAM
OID: memTotalVirtual64 .1.3.6.1.4.1.2620.1.6.7.4.1
Format: String
Description: The size in BYTES of the virtual-memory working segment pages.

Counter: Active virtual RAM
OID: memActiveVirtual64 .1.3.6.1.4.1.2620.1.6.7.4.2
Format: String
Description: The size in bytes of the virtual-memory working segment pages that have actually been touched.

Counter: Hmem fails
OID: fwPerfStat.fwHmem.
fwHmem-failed-alloc .1.3.6.1.4.1.2620.1.1.26.1.21
Format: String
Description: Memory allocation failure.

Counter: Kmem fails
OID: fwPerfStat.fwHmem.fwKmem-failed-alloc .1.3.6.1.4.1.2620.1.1.26.2.15
Format: String
Description: Insufficient free memory.

For information in: [Check Point SNMP Best Pratices](http://dl3.checkpoint.com/paid/22/223d31696d9a7966a6fcbed57ba5c679/CP_SNMP_BestPracticesGuide.pdf?HashKey=1455633823_ddf6c0fe0b7271a59b215b801492ff46&xtn=.pdf) page 14

Thx

**Comment by Sims24** [comment]
Did the change, do not include insufficient free memory counter as we could trigger an alarm on memory and swap usage. Avoid checking the same thing. 

Closed https://github.com/centreon/centreon-plugins/pull/552
