### ISSUE TITLE
[cloud::microsoft::office365::management::plugin]  Cannot decode json response: malformed JSON string

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3377]
Hello,

I use this command : 

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::microsoft::office365::management::plugin --mode=service-status --custommode='managementapi' --tenant='xxxxx' --client-id='xxxxx' --client-secret='xxxxxx' --verbose --filter-service-name='OneDrive for Business' `

I have this error : 

`UNKNOWN: Cannot decode json response: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "Please use MSGraph t...") at /usr/lib/centreon/centreon-plugins/cloud/microsoft/office365/custom/managementapi.pm line 192.`

The debug log : 

```
======> response done
HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Date: Wed, 05 Jan 2022 09:06:11 GMT
Pragma: no-cache
Server: Microsoft-IIS/10.0
Server: Microsoft-IIS/10.0
Content-Length: 170
Content-Type: text/plain; charset=utf-8
Expires: -1
Client-Date: Wed, 05 Jan 2022 09:06:11 GMT
Client-Peer: 40.79.139.196:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
Client-SSL-Cert-Subject: /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/CN=manage.office.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Version: TLSv1_2
X-Activity-Id: 1efb7a15-c950-4c91-b33c-8a8870a87382
X-AspNet-Version: 4.0.30319
X-Instance-Name: Office365ServiceCommsWebService_Office365ServiceCommsWebService_IN_28
X-Powered-By: ASP.NET
X-Powered-By: ASP.NET
X-Time-Taken: 87

Please use MSGraph to access this resource https://docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&preserve-view=true
```
I use the latest version of centreon-plugin

Thank you for you're help

**Comment by Sims24** [comment]
Hello @prohand 

It looks like a permission issue. Plugin receives a 403 Forbidden, the error is because it tries to decode a JSON but catch the 'Please use MSGraph to a...' error message instead.

**Comment by prohand** [comment]
I can't change permission recently.
The message appear at 03/01/2022 at 6:30PM

Do you have any idea of the authorization to be granted ?

Thank you

**Comment by garnier-quentin** [comment]
Microsoft had changed how to get service informations:
https://docs.microsoft.com/fr-fr/office/office-365-management-api/office-365-service-communications-api-reference

So we need to update the plugin.

**Comment by prohand** [comment]
OK fine ;)
I'll let you let me know when it's OK.

Thank you

**Comment by garnier-quentin** [comment]
Are you available today or tomorrow for a session ?

**Comment by garnier-quentin** [comment]
Fix in last git version: https://github.com/centreon/centreon-plugins/pull/3382

**Comment by jbeaujour** [comment]
Hello
I have the same issue.
And with new release, i have:

_UNKNOWN: Cannot decode json response: malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "Can't connect to gra...") at /usr/lib/centreon/plugins/cloud/microsoft/office365/custom/graphapi.pm line 201.
======> request send
GET https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews?%24expand=issues
Accept: application/json
Authorization: Bearer eyJ0-----xxxxx
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded

======> response done
500 Can't connect to graph.microsoft.com:443
Content-Type: text/plain
Client-Date: Mon, 17 Jan 2022 18:23:26 GMT
Client-Warning: Internal response

Can't connect to graph.microsoft.com:443_

Do I need a new authorization in Office365?

**Comment by henricsouza** [comment]
Hello
after update there is a permission error.

{"error":{"code":"UnknownError","message":"{\"code\":\"forbidden\",\"message\":\"{\\u0022error\\u0022:\\u0022You do not have required permissions to access this resource. ActivityId: 97bb2e12-64b9-4e0d-a151-c6d16d61430f. Learn more: https://docs.microsoft.com/en-us/graph/permissions-reference#service-communications-permissions.\\u0022}\"}","innerError":{"date":"2022-01-20T14:08:50","request-id":"97bb2e12-64b9-4e0d-a151-c6d16d61430f","client-request-id":"97bb2e12-64b9-4e0d-a151-c6d16d61430f"}}}

**Comment by jbeaujour** [comment]
Jello @prohand ,  Is that OK for you and what authorization you granted

**Comment by prohand** [comment]
Here is : 
![image](https://user-images.githubusercontent.com/20227162/150817675-10432f8e-56a0-4b48-be99-8ed61ada4aa3.png)

**Comment by jbeaujour** [comment]
Hello, thank's it's ok now, with your information

**Comment by henricsouza** [comment]
Hello, still having problems? @jbeaujour

**Comment by jbeaujour** [comment]
Hello @henricsouza 
No, with @prohand information, all is OK

**Comment by henricsouza** [comment]
Hello @jbeaujour 
this is return
![perm_office](https://user-images.githubusercontent.com/98103016/155585098-0d91b54a-898f-42db-b599-adc9d8f45069.png)

![req_office](https://user-images.githubusercontent.com/98103016/155585169-bf8d8c42-9258-4909-983f-e327867eed5a.png)

**Comment by jbeaujour** [comment]
try this :
![image](https://user-images.githubusercontent.com/14891591/155614779-2907ac74-0796-48cb-b2a1-72f971b8a613.png)

**Comment by henricsouza** [comment]
Hello @jbeaujour
thanks for the feedback!

return after change

![req_office](https://user-images.githubusercontent.com/98103016/155727887-4b4af0f1-ed4b-4977-98fe-e48324069276.png)
![azure](https://user-images.githubusercontent.com/98103016/155727891-888d0de3-08ac-4f54-b8b9-6c53d1e0e125.png)

**Comment by jbeaujour** [comment]
Our command:
/app/sigmatools/centreon-plugins-master/centreon_plugins.pl --plugin cloud::microsoft::office365::management::plugin --mode service-status --custommode='graphapi' --timeout 60 --tenant='xxxxxxxxxxxxxxxx'  --client-id='xxxxxxxxxxxxxxxxxxxxxx' --client-secret='xxxxxxxxxxxxxxxxxxxxxx' --filter-service-name="Exchange Online" --warning-status="%{status} =~ /Investigating|Restoring service|Investigation suspended|Service degradation|Extended recovery/" --critical-status="%{status} =~ /Service Interruption/" --insecure --http-backend=curl --proxyurl https://xxxxxxxxxxxxx:8080

**Comment by jbeaujour** [comment]
I think there is a problem with office365 now, we have the same error

**Comment by MicaelRPereiraGTI** [comment]
I have the same problem @jbeaujour

**Comment by jbeaujour** [comment]
The Microsoft Office365 service is flapping, 15mn OK now 'service degradation' for all services

**Comment by garnier-quentin** [comment]
It seems the service is often in degradation state. Maybe you can exclude that status:
```--critical-status='%{status} !~ /serviceOperational|serviceRestored|serviceDegradation/i'```
