### ISSUE TITLE
[network::checkpoint::plugin] connections mode enhancement

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#338]
Can you please enhancement the connections mode to support VSX and fwAccepted, fwDropped, fwRejected (per VSX to).
The actual mode only return the connections of the physical appliance itself (no fw engine, only connection for management traffic, such as provider-1).

example:

> centreon_plugins.pl --plugin=network::checkpoint::plugin --hostname= --snmp-version= --snmp-community= --mode=connections
> OK: Connections: 205 | 'connections'=205con;;;0

fwNumConn per VSX

> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.1.0 = INTEGER: 205 
> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.2.0 = INTEGER: 0
> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.3.0 = INTEGER: 63636
> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.4.0 = INTEGER: 3473
> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.5.0 = INTEGER: 50710
> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.6.0 = INTEGER: 11832
> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.7.0 = INTEGER: 364
> SNMPv2-SMI::enterprises.2620.1.16.23.1.1.2.8.0 = INTEGER: 193

vsxStatusVsName 

> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.1.0 = STRING: "mvs01"
> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.2.0 = STRING: "mvs01_fw01"
> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.3.0 = STRING: "mvs01_fw02"
> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.4.0 = STRING: "mvs01_fw03"
> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.5.0 = STRING: "mvs01_fw04"
> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.6.0 = STRING: "mvs01_fw05"
> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.7.0 = STRING: "mvs01_fw06"
> SNMPv2-SMI::enterprises.2620.1.16.22.1.1.3.8.0 = STRING: "mvs01_fw07"

Thx

**Comment by garnier-quentin** [comment]
Ref #16

**Comment by garnier-quentin** [comment]
So the checkpoint can fill that values! Could you give me a complete snmpwalk of that OIDs from your checkpoint:
.1.3.6.1.4.1.2620.1.16.22
.1.3.6.1.4.1.2620.1.16.23

**Comment by Sims24** [comment]
@garnier-quentin did you get a walk from @CFRR for these oids ?

**Comment by garnier-quentin** [comment]
I need the snmpwalk of above OIDs. Please add it and i reopen it. Thanks!
