### ISSUE TITLE
cloud::azure::database::sqlserver::plugin InvalidResourceNamespace

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3385]
Hello,

I have this command :

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::database::sqlserver::plugin --tenant='xxxxx' --subscription='xxxxx' --client-id='xxxxx' --client-secret='xxxxx' --custommode=api --mode='health' --resource='serversqlname' --resource-group='resourcegroupname'`

And i have this error : 

`UNKNOWN: Management endpoint API returns error code 'InvalidResourceNamespace' (add --debug option for detailed message)
`
The debug : 

```
Use of uninitialized value $options{"resource_namespace"} in concatenation (.) or string at /usr/lib/centreon/centreon-plugins/cloud/azure/custom/api.pm line 357.
Use of uninitialized value $options{"resource_type"} in concatenation (.) or string at /usr/lib/centreon/centreon-plugins/cloud/azure/custom/api.pm line 357.
UNKNOWN: Management endpoint API returns error code 'InvalidResourceNamespace' (add --debug option for detailed message)
======> request send
GET https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/resourcegroupname/providers///'serversqlname/providers/Microsoft.ResourceHealth/availabilityStatuses/current?api-version=2020-05-01
Accept: application/json
Authorization: Bearer xxxxx
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Date: Fri, 07 Jan 2022 09:08:33 GMT
Pragma: no-cache
Content-Length: 122
Content-Type: application/json; charset=utf-8
Expires: -1
Client-Date: Fri, 07 Jan 2022 09:08:34 GMT
Client-Peer: 40.79.131.240:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 02
Client-SSL-Cert-Subject: /CN=management.azure.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Version: TLSv1_2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: xxxx
X-Ms-Failure-Cause: gateway
X-Ms-Request-Id: xxxx
X-Ms-Routing-Request-Id: FRANCECENTRAL:20220107T090834Z:xxxxxx

{"error":{"code":"InvalidResourceNamespace","message":"The resource namespace ''serversqlname' is invalid."}}
Error message : The resource namespace ''serversqlname' is invalid.

```

Thank you

**Comment by Sims24** [comment]
Indeed, it was a mistake Microsoft.Sql/servers isn't compatible with https://docs.microsoft.com/en-us/azure/service-health/resource-health-checks-resource-types. 

I will rollback the commit, nevertheless I would like to update it to be closer than the health.pm standard.

Could you confirm that you only check one server and not using the filter-name to get the state of multiple sqlserver within a single check? 

Thanks

**Comment by prohand** [comment]
42 / 5 000
Résultats de traduction
Hello,

I am using the filter-name

Thank you

**Comment by Sims24** [comment]
Sorry I was not very accurate in my question. 

Are you using filter-name with a very strong regexp like --filter-name='^my-server$' or do you sometime use --filter-name='a-server|another-server'?

**Comment by prohand** [comment]
I use this : --filter-name='a-server|another-server'

**Comment by Sims24** [comment]
Ok, it will be a full rollback then.

Sorry didn't mean to break everything 🙃

**Comment by prohand** [comment]
No problem ;)
Tell me when it's OK so that I update on my side.

Thank you

**Comment by Sims24** [comment]
@prohand you can test it.

**Comment by prohand** [comment]
Hello,

Is ok :)

Thank you
