### ISSUE TITLE
cloud::azure::web::appservice::plugin --mode='health' HTTP/1.1 409 Conflict

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3387]
Hello,

The command : 

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin=cloud::azure::web::appservice::plugin --custommode=api --mode='health' --tenant='xxxxx' --client-id='xxxxx' --client-secret='xxxxx' --resource='/subscriptions/xxxxxx/resourceGroups/rg/providers/Microsoft.Web/sites/app' --timeout 60 --environment="AZURE_CORE_ONLY_SHOW_ERRORS=True" --subscription xxxxxx --debug`

See this error : 

```
UNKNOWN: Management endpoint API returns code 'AuthError' (add --debug option for detailed message)
======> request send
GET https://management.azure.com/subscriptions/xxxxxx/resourceGroups/rg/providers/Microsoft.Web/sites/app/providers/Microsoft.ResourceHealth/availabilityStatuses/current?api-version=2020-05-01
Accept: application/json
Authorization: Bearer xxxx
User-Agent: centreon::plugins::backend::http::useragent
======> response done
HTTP/1.1 409 Conflict
Cache-Control: no-cache
Date: Fri, 07 Jan 2022 13:56:35 GMT
Pragma: no-cache
Server: Microsoft-HTTPAPI/2.0
Content-Length: 160
Content-Type: application/json
Expires: -1
Client-Date: Fri, 07 Jan 2022 13:56:35 GMT
Client-Peer: 40.79.131.240:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 02
Client-SSL-Cert-Subject: /CN=management.azure.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Version: TLSv1_2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: xxxxx
X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: 99
X-Ms-Request-Id: xxxx
X-Ms-Request-Id: xxxx
X-Ms-Routing-Request-Id: FRANCECENTRAL:20220107T135635Z:xxxx

{"code":"AuthError","message":"An error occured in authentication or authorization. Make sure the resource provider has been registered with this subscription"}
Message : An error occured in authentication or authorization. Make sure the resource provider has been registered with this subscription

```

The error only show with --mode='health'
The same command with --mode='cpu-time' is OK.

Thank you for you're help.

**Comment by Sims24** [comment]
Hello @prohand ,

I made some modifications but looks like it introduces some regression in some cases. I'll be back to you shortly.

**Comment by prohand** [comment]
Ok thank you

**Comment by Sims24** [comment]
Sorry the response above was about: https://github.com/centreon/centreon-plugins/issues/3385 

I'll take a deeper look on this one afterwards.

**Comment by Sims24** [comment]
Hi, 

Looks like the scope of the authorization isn't wide enough. 

cpu-time is using az monitor API while the health API uses a slightly different endpoint. 

Do you have other health modes working with the same client-id/client-secret on this tenant/subscription?

**Comment by prohand** [comment]
Yes, i have another health working in the tenant.

**Comment by Sims24** [comment]
Could you check with this proc: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider-1 that both Microsoft.Web/sites & Microsoft.ResourceHealth are registered? (Honestly I'm not sure If both are possible/required).

**Comment by prohand** [comment]
The Microsoft.ResourceHealth is not registred.
After registred this ressource, is OK ;)

Thank you
