### ISSUE TITLE
apps::openvpn::omi::plugin return connection error but OMI is reachable

### ISSUE THREAD

**Issue by Fuuzz** [centreon/centreon-plugins#3389]
Hi, I'm facing some troubles with the apps::openvpn::omi::plugin plugin; the plugin is launched with all the required parameters filled:

`centreon_openvpn_omi.pl --plugin=apps::openvpn::omi::plugin --mode=server-usage  --omi-hostname='HOST' --omi-password='PASS' --omi-port='PORT'`

When executed it ends in timeout and UNKNOWN is returned:

`UNKNOWN: Communication issue [Timeout or unexpected protocol]`

However with the same parameters, from the centreon-engine user shell, I'm able to connect to the OMI interface succesfully:

```
-bash-4.2$ telnet HOST PORT
Trying HOST...
Connected to HOST.
Escape character is '^]'.
ENTER PASSWORD:PASS
SUCCESS: password is correct
>INFO:OpenVPN Management Interface Version 1 -- type 'help' for more info
```

I can't help thinking there could be something wrong somewhere in the plugin at this point.

Also, even if I pass a `--timeout` time, the time before the UNKNOWN message is displayed is the same.

Thanks in advance :)

**Comment by garnier-quentin** [comment]
You can send me an email and we could do a session.

**Comment by Fuuzz** [comment]
Hi, I sent you an email :)

**Comment by garnier-quentin** [comment]
It should be fixed in last version: https://github.com/centreon/centreon-plugins/pull/3395
