### ISSUE TITLE
[check_centreon_snmp_cpu] cpu threshold per core?

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#339]
is possible to define cpu threshold per core?
the cpu plugin only define threshold for the average cpu.

Thx

**Comment by garnier-quentin** [comment]
The old plugin is not in maintenance.

**Comment by CFRR** [comment]
what is the alternative?

Thx

**Comment by garnier-quentin** [comment]
Use os::linux::snmp::plugin for example

**Comment by CFRR** [comment]
right, but my question remains: how define threshold for the average cpu?

Thx

**Comment by garnier-quentin** [comment]
You cant now. need to enhance

**Comment by CFRR** [comment]
ok, thx

**Comment by CPbN** [comment]
See #1100 👍
