### ISSUE TITLE
(systemd-sc-status) service name not present [--filter-name]

### ISSUE THREAD

**Issue by pakyg** [centreon/centreon-plugins#3396]
Hello,
I was doing some tests on the check of one or more services.
I use the following command: 

1. Correct output:"./centreon_plugins.pl --plugin os::linux::local::plugin --mode 'systemd-sc-status' --filter-name 'chronyd.service"  
OK: Total Running: 1, Total Failed: 0, Total Dead: 0, Total Exited: 0 - **Service 'chronyd.service' status** : loaded/active/running [boot: enabled] | 'total_running'=1;;;0;1 'total_failed'=0;;;0;1 'total_dead'=0;;;0;1 'total_exited'=0;;;0;1

2. Output with 2 services:"./centreon_plugins.pl --plugin os::linux::local::plugin --mode 'systemd-sc-status' --filter-name 'chronyd.service|ntpd.service"  
OK: Total Running: 1, Total Failed: 0, Total Dead: 1, Total Exited: 0 - All services are ok | 'total_running'=1;;;0;2 'total_failed'=0;;;0;2 'total_dead'=1;;;0;2 'total_exited'=0;;;0;2

Trying to insert 2 or more services to monitor inside the --filter-name, I don't see the service name in the output.
Instead, putting a single service, I can easily see the service name.

Is there a way to have all the service names in output even by entering 2 or more?

I await your news.
Thanks so much!!

**Comment by garnier-quentin** [comment]
Please add the option ```--verbose```

**Comment by garnier-quentin** [comment]
Is it ok for you with that option ?
