### ISSUE TITLE
Get http content

### ISSUE THREAD

**Issue by mullergg** [centreon/centreon-plugins#3401]
Hello,

Some of my business application presents some datas through http.
I want to interrogate this page and gathering this data and put it to perfdata or setting a treshold on it.

For example:
```
[centreon-engine@xxxxxx plugins]$ ./centreon_plugins.pl --plugin apps::protocols::http::plugin --mode=expected-content --hostname=xxxxxxx  --urlpath=/admin/status.cgi --proto=https --port=443--ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --debug
OK: HTTP test(s) | 'size'=28B;;;0; 'time'=0.054s;;;0;
======> request send
GET https://xxxxxxxxxx:443/admin/status.cgi
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 200 OK
Connection: close
Content-Length: 28
Content-Type: text/plain
Client-Date: Fri, 14 Jan 2022 13:29:47 GMT
Client-Peer: xxxxxxxx:443
Client-Response-Num: 1



Total number of clients: 0
```

I want to get the value of Total number of clients and put it in perfdata.
I don't know if there is something in the plugin that can do something like that ?

I tested every mode in the http plugin but I don't find a valid solution, I was hopping something like a mode get-content.

**Comment by garnier-quentin** [comment]
You can use following option: ```--extracted-pattern='number of clients: (\d+)'```

**Comment by mullergg** [comment]
Thanks i've missed this option !

Is it also possible to modify the output message ? Having something else than : OK: HTTP test(s)

And can i modify the name of the perfdata ? 'value'=0;;;; 
Having 'nb_clients'=0 instead of value for example ?

**Comment by garnier-quentin** [comment]
You can use the change-perfdata option. But for the output, you can use that perfdata inside.

**Comment by mullergg** [comment]
Ok thanks.
I don't need the perfdata in the output, I wanted the set a more meaningful than OK: HTTP test(s)

**Comment by garnier-quentin** [comment]
You have the option ```--change-short-output```

**Comment by mullergg** [comment]
Have you an example of use ?

**Comment by garnier-quentin** [comment]
```--change-short-output='HTTP.*~my text~'```

**Comment by mullergg** [comment]
Thanks a lot
