### ISSUE TITLE
[apps::protocols::http::plugin] Token authentication ?

### ISSUE THREAD

**Issue by mullergg** [centreon/centreon-plugins#3404]
Hello !
For one of my application I need a token authentication with mode json-content.
Is it possible to do that with the http plugin ?

**Comment by garnier-quentin** [comment]
If you have the token, you can use the header option. If you need to request a page first, you cannot.

**Comment by mullergg** [comment]
Yes I need to request a login page tu get the token and then use it to get the datas.
Ok I will try something different.
Is it possible to have something like that in the future ? 
Many application including centreon use this type of authentication now.

**Comment by garnier-quentin** [comment]
Not in short term. You need to take an example and create your own plugin

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3816
