### ISSUE TITLE
bad Credentials on Simplivity plugins 

### ISSUE THREAD

**Issue by sdouce** [centreon/centreon-plugins#3405]
Hello , 
something should miss in my configuration or acess to simplivity API . 

When i test check_command like this :
` /usr/lib/centreon/plugins/centreon_hpe_simplivity_restapi.pl     --plugin=apps::virtualization::hpe::simplivity::restapi::plugin     --mode=hosts     --hostname='XX.XX.XX.XX'     --api-username='xxx@xxx.local'     --api-password='XXXXXXXX'     --verbose --http-backend=curl --insecure`
`
It return 

{"exception":"BadCredentialsException","path":"/api/oauth/token","message":"Bad Credentials","timestamp":"2022-01-17T11:32:52Z","status":"401"}UNKNOWN: Authentication error [code: '401'] [message: 'Unauthorized']

When i add on --hostname='**simplivity@**XX.XX.XX.XX'  it works ! 
I found this on HPE doc :
![image](https://user-images.githubusercontent.com/6204522/149763140-17bf0e20-e654-45db-8727-45becb6cc7cb.png)
I you want to test do not hesitate to contact me .

**Comment by garnier-quentin** [comment]
It's fixed in last version.
