### ISSUE TITLE
[storage::dell::compellent::snmp::plugin] on Scv3020.07.04.21.004 doesn't report correct status

### ISSUE THREAD

**Issue by FiliMila** [centreon/centreon-plugins#3412]
Hi.
I'm using this plugin, but from hardware mode I get a report about 'down' Volume state, that doesn't exist anymore.
Is there a way to clear plugin cache, for check if it still read old data?
Thanks a lot.

Bug details:
~ sudo -u icinga '/usr/shared/monitoring/plugins/centreon-plugin/centreon_plugins.pl' '--hostname' 'xx.xx.xx.xx' '--mode' 'hardware' '--snmp-community' 'xxxsnmp' '--snmp-port' '161' '--snmp-version' '2c' '--plugin' 'storage::dell::compellent::snmp::plugin'
CRITICAL: Volume 'AsyncReplication 2' status is 'down' - Volume 'AsyncReplication 3' status is 'down' | 'ctrlfan_1.1'=5760rpm;1800:20000;0:30600;0; 'ctrlfan_1.2'=5760rpm;1800:20000;0:30600;0; 'ctrlfan_1.3'=5880rpm;1800:20000;0:30600;0; 'ctrlfan_1.4'=5760rpm;1800:20000;0:30600;0; 'ctrlvoltage_1.1'=0.000000V;0.000000:0.000000;0.000000:0.000000;; 'ctrlvoltage_1.2'=0.000000V;0.000000:0.000000;0.000000:0.000000;; 'ctrlvoltage_2.1'=0.000000V;0.000000:0.000000;0.000000:0.000000;; 'ctrlvoltage_2.2'=0.000000V;0.000000:0.000000;0.000000:0.000000;; 'ctrltemp_1.1'=32C;0:81;0:88;; 'ctrltemp_1.2'=26C;0:65;0:127;; 'ctrltemp_1.3'=31C;0:70;0:127;; 'ctrltemp_1.4'=50C;4:97;0:127;; 'ctrltemp_1.5'=30C;0:70;0:127;; 'ctrltemp_1.6'=20C;0:47;0:127;; 'ctrltemp_1.7'=22C;0:53;0:127;; 'ctrltemp_1.8'=23C;0:53;0:127;; 'ctrltemp_1.9'=26C;0:65;0:127;; 'ctrltemp_1.10'=25C;0:65;0:127;; 'ctrltemp_2.1'=30C;0:81;0:88;; 'ctrltemp_2.2'=25C;0:65;0:127;; 'ctrltemp_2.3'=30C;0:70;0:127;; 'ctrltemp_2.4'=50C;4:97;0:127;; 'ctrltemp_2.5'=30C;0:70;0:127;; 'count_cache'=2;;;; 'count_ctrl'=2;;;; 'count_ctrlfan'=4;;;; 'count_ctrlpower'=2;;;; 'count_ctrltemp'=15;;;; 'count_ctrlvoltage'=4;;;; 'count_disk'=10;;;; 'count_diskfolder'=2;;;; 'count_encl'=1;;;; 'count_encliomod'=2;;;; 'count_sc'=1;;;; 'count_server'=5;;;; 'count_volume'=19;;;;

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of the following branch: .1.3.6.1.4.1.674.11000.2000.500.1.2.26.1
That plugin doesn't have a cache. It seems more like an issue on agent snmp of compellent.

**Comment by FiliMila** [comment]
snmp_build: unknown failuresnmpwalk: Error building ASN.1 representation (Can't build OID for variable)

**Comment by garnier-quentin** [comment]
Try to execute command again ? Maybe it's ok now (because the snmpwalk should work)

**Comment by FiliMila** [comment]
it seems to be empty

**Comment by garnier-quentin** [comment]
You still have the issue ?

**Comment by FiliMila** [comment]
yes, nothing changed...

**Comment by garnier-quentin** [comment]
Are you sure to snmpwalk the right equipment ? Because the plugin does a snmpwalk of that branch. If you have nothing from snmpwalk, you should also have no volumes returns by the plugin.

**Comment by FiliMila** [comment]
sorry; probably wrong merged copy/paste...

SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.1 = Gauge32: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.2 = Gauge32: 2
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.3 = Gauge32: 3
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.4 = Gauge32: 4
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.5 = Gauge32: 5
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.6 = Gauge32: 6
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.7 = Gauge32: 7
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.8 = Gauge32: 8
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.9 = Gauge32: 9
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.10 = Gauge32: 10
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.11 = Gauge32: 11
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.12 = Gauge32: 12
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.13 = Gauge32: 13
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.14 = Gauge32: 14
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.15 = Gauge32: 15
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.16 = Gauge32: 16
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.17 = Gauge32: 17
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.18 = Gauge32: 18
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.2.19 = Gauge32: 19
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.1 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.2 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.3 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.4 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.5 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.6 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.7 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.8 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.9 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.10 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.11 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.12 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.13 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.14 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.15 = INTEGER: 2
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.16 = INTEGER: 2
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.17 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.18 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.19 = INTEGER: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.1 = STRING: "SM-vmfs01"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.2 = STRING: "Replica di LV-vmfs01"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.3 = STRING: "Async Repl SM-vmfs01"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.4 = STRING: "SM-vmfs02"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.5 = STRING: "SM-vmfs03"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.6 = STRING: "SM-vmfs04"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.7 = STRING: "AsyncReplication 3"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.8 = STRING: "Replica di LV-vmfs02"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.9 = STRING: "Replica di LV-vmfs03"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.10 = STRING: "Replica di LV-vmfs04"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.11 = STRING: "Async Repl SM-vmfs02"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.12 = STRING: "Async Repl SM-vmfs03"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.13 = STRING: "Async Repl SM-vmfs04"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.14 = STRING: "AsyncReplication 1"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.15 = STRING: "AsyncReplication 2"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.16 = STRING: "AsyncReplication 3"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.17 = STRING: "SM-vmfs10-NoReplica"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.18 = STRING: "AsyncReplication 4"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.19 = STRING: "AsyncReplication 2"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.1 = Gauge32: 1
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.2 = Gauge32: 2
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.3 = Gauge32: 3
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.4 = Gauge32: 4
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.5 = Gauge32: 5
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.6 = Gauge32: 6
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.7 = Gauge32: 7
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.8 = Gauge32: 8
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.9 = Gauge32: 9
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.10 = Gauge32: 10
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.11 = Gauge32: 11
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.12 = Gauge32: 12
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.13 = Gauge32: 13
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.14 = Gauge32: 14
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.15 = Gauge32: 15
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.16 = Gauge32: 16
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.17 = Gauge32: 18
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.18 = Gauge32: 19
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.5.19 = Gauge32: 20
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.1 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.2 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.3 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.4 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.5 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.6 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.7 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.8 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.9 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.10 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.11 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.12 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.13 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.14 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.15 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.16 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.17 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.18 = STRING: "Empty"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.6.19 = STRING: "Empty"

**Comment by garnier-quentin** [comment]
```
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.7 = STRING: "AsyncReplication 3"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.4.16 = STRING: "AsyncReplication 3"
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.7 = INTEGER: 1 (Up)
SNMPv2-SMI::enterprises.674.11000.2000.500.1.2.26.1.3.16 = INTEGER: 2 (Down)
```

It's not a plugin issue. You should ask to dell support about it.

**Comment by FiliMila** [comment]
I see. Thanks a lot.

**Comment by garnier-quentin** [comment]
If you have some informations from dell, please comment the issue

**Comment by FiliMila** [comment]
Hi,
support Dell solved the issue, with cache cleaning in storage data collector and controllers reboot.
Now it works as expected.
Thanks.

**Comment by garnier-quentin** [comment]
Great! Thanks for the feedback!
