### ISSUE TITLE
[network::fortinet::fortigate::snmp::plugin] mode interfaces: UNKNOWN: Unsafe code evaluation: syntax error at (eval 13) line 2, at EOF

### ISSUE THREAD

**Issue by FiliMila** [centreon/centreon-plugins#3415]
Hi.
I've updated to latest release (2022-01-13), and now I get reported state.

'centreon_plugins.pl' '--nagvis-perfdata' '--warning-status' '80%' '--warning-out-traffic' '90' '--warning-in-traffic' '90' '--snmp-version' '2c' '--snmp-port' '161' '--snmp-community' 'xxx' '--name' '--add-errors' '--mode' 'interfaces' '--hostname' 'x.x.x.x' '--critical-status' '90%' '--critical-out-traffic' '95' '--critical-in-traffic' '95' '--add-volume' '--add-traffic' '--add-status' '--plugin' 'network::fortinet::fortigate::snmp::plugin'

UNKNOWN: Unsafe code evaluation: syntax error at (eval 13) line 2, at EOF

expected: OK: All interfaces are ok

Thanks a lot.

**Comment by garnier-quentin** [comment]
You're critical-status option is wrong. By default it's: ```--critical-status='%{admstatus} eq "up" and %{opstatus} ne "up"'```
