### ISSUE TITLE
[hardware::server::ibm::bladecenter::snmp::plugin] More informations in verbose output

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#342]
Hi,
Is it possible to return the blade names on the verbose output as it is done for HP bladecenters ?
Using 1.3.6.1.4.1.2.3.51.2.22.1.5.1.1.6.

And also the description of the problems with 1.3.6.1.4.1.2.3.51.2.2.7.2.1.3 ?
The relation might have to be done by blade names.

Thanks

**Comment by garnier-quentin** [comment]
Could you test it for blade name ? I won't do it for description problems. That global eventlogs. It always messy to know how that table works: if ID are incremental only, when we rest, the purge, the performance (can be a lot),....
