### ISSUE TITLE
[network::fortinet::fortigate::plugin] cluster-status enhancement

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#343]
Can you please enhancement this mode to also show the name of the host (now only shows serial number).

Thx.

**Comment by garnier-quentin** [comment]
Hi,

You want to display following OID also 'fgHaStatsHostname' ?

**Comment by CFRR** [comment]
yes please.

**Comment by garnier-quentin** [comment]
Could you give me the walk of the 'fgHaStatsHostname' oid ?

**Comment by CFRR** [comment]
fgHaStatsHostname show the hostname of the active cluster member

**Comment by garnier-quentin** [comment]
So it's not good no ? Where can i find the name ?

**Comment by CFRR** [comment]
the oid fgHaStatsHostname (1.3.6.1.4.1.12356.101.13.2.1.1.11) will show all hosts that are part of the cluster, and the first record is the active node/member of the cluster:

> 
> SNMPv2-SMI::enterprises.12356.101.13.2.1.1.11.1 = STRING: "FWRL002"
> SNMPv2-SMI::enterprises.12356.101.13.2.1.1.11.2 = STRING: "FRWL001"
