### ISSUE TITLE
[storage::hp::3par::ssh::plugin] Request a new modes "time" and "uptime"

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#3432]
Hello

Please make a new modes **time** and **uptime**  in **storage::hp::3par::ssh::plugin**

---

Command for mode **time** to be executed `showdate`.

From [HPE 3PAR Command Line Interface Reference Guide](https://github.com/centreon/centreon-plugins/files/7949252/HPE_c04204279_HPE.3PAR.Command.Line.Interface.Reference.Guide.pdf):

> The showdate command displays the date and time for each system node

Example:

```
3PAR01 cli% showdate
Node Date
0    2022-01-25 15:55:37 MSK (Europe/Moscow)
1    2022-01-25 15:55:36 MSK (Europe/Moscow)
```

Here we need to be able to compare the time with the NTP server or with the local time on the monitoring server, as this is implemented in other plugins.
Perfdata can be in the context of nodes like **node0.time.offset.seconds**, **node1.time.offset.seconds** ... **nodeX.time.offset.seconds**

---

Command for mode **time** to be executed `shownode -uptime`.

From [HPE 3PAR Command Line Interface Reference Guide](https://github.com/centreon/centreon-plugins/files/7949252/HPE_c04204279_HPE.3PAR.Command.Line.Interface.Reference.Guide.pdf):

> -uptime Shows the amount of time each node has been running since the last shutdown.

Example:

```
3PAR01 cli% shownode -uptime
Node -------Up Since--------
   0 2021-09-16 10:50:15 MSK
   1 2021-09-15 13:21:39 MSK

```

Perfdata can be in the context of nodes like **node0.uptime.seconds**, **node1.uptime.seconds** ... **nodeX.uptime.seconds**

**Comment by garnier-quentin** [comment]
You can test with following archive: https://github.com/centreon/centreon-plugins/archive/refs/heads/MON-14751-3par-add-modes.zip

https://github.com/centreon/centreon-plugins/pull/3862

**Comment by Aleksey-Maksimov** [comment]
Thanks Quentin. 
These new plugin modes work successfully.

**Comment by Aleksey-Maksimov** [comment]
Hello @garnier-quentin, 
One small clarification.
Plugin "time" output "OK: All nodes uptime are ok"
And expect "OK: All nodes time are ok".

**Comment by garnier-quentin** [comment]
Thanks: https://github.com/centreon/centreon-plugins/pull/3955
