### ISSUE TITLE
apps::nsclient::restapi::plugin error 500

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#3435]
Hello, 

I have trouble using the plugin apps::nsclient::restapi::plugin to check some  metrics on a windows server. 
I have followed all documentation to configure the nsclient server. But with all this it keeps giving me the 500 error

i run the command line :
/usr/lib/centreon/plugins//centreon_nsclient_restapi.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname='10.6.0.2' --port='8443' --proto='https' --legacy-password='centreon'  --command=check_pdh --arg="counter=\\Terminal Services\\Active Sessions" --arg="warning=none" --arg="critical=none" --arg=show-all

and it keeps returning :  
UNKNOWN: 500 Can't connect to 10.6.0.2:8443 |

Nsclient config, is very basic
WEBServer = 1
allowed hosts = 0.0.0.0/0
cache allowed hosts = true
port = 8443
password = centreon

Tried with both ( after generating and uploading 2048 cert) :  
certificate = ${certificate-path}/nrpe_dh_2048.pem
certificate = ${certificate-path}/certificate.pem

Is there something i am messing ?

thank you for the help

**Comment by garnier-quentin** [comment]
Have you tried with option: ```--insecure``` ?

**Comment by saharawolf** [comment]
Hi,

Unknown option: insecure at /usr/lib/centreon/plugins//centreon_nsclient_restapi.pl line 428.

**Comment by garnier-quentin** [comment]
Could you update the plugin ?

**Comment by saharawolf** [comment]
i have just installed it today

/usr/lib/centreon/plugins//centreon_nsclient_restapi.pl --plugin=apps::nsclient::restapi::plugin --version
Plugin Version: 0.1

**Comment by saharawolf** [comment]
Hi, 

I have cloned the git and i only get the version 0.1.
Are you sure there is an update for this plugin ?

**Comment by garnier-quentin** [comment]
Yes i'm pretty sure. Because you should have the ```--insecure``` option

**Comment by garnier-quentin** [comment]
Do you have some news ?

**Comment by garnier-quentin** [comment]
If you have more informations, please comment it.
