### ISSUE TITLE
[storage::hp::3par::ssh::plugin] Request a new mode "psu"

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#3436]
Hello

Please make a new mode **psu** in **storage::hp::3par::ssh::plugin** to check the status of 3PAR storage power supplies and batteries.

The current implementation of monitoring in the `psu.pm` code does not have checks for power supply fans.
3PAR power supplies (in main cage) have special batteries, the state of charge of which also needs to be monitored. 
The current implementation of monitoring in the `battery.pm` code does not allow us to get an extended status of the battery. 
The information from the `shownode -ps -verbose` command will allow us to get extended battery status and additional data for perfdata.

The data we need to check in each section "---------------Node*"

1)  The parameter "State" must be "OK" for each psu
2)  The parameter "Fan State" must be "OK" for each psu
3)  The parameter "AC State" must be "OK" for each psu
4)  The parameter "DC State" must be "OK" for each psu
5)  The parameter "Battery State" must be "OK" for each psu
6)  Parameters "Battery Detail State", "Battery Charge State" must be in plugin output with --verbose option

Here we suppose to see perfdata for "Battery Charge Level(%)" and "Max Battery Life(mins)" with warn/crit thresholds

Examples:

```
3PAR02 cli% shownode -ps
Node PS -Assem_Part- -Assem_Serial- ACState DCState PSState
 0,1  0   682372-001 5CQLQAXXXXXXX1  OK      OK      OK
 0,1  1   682372-001 5CQLQAXXXXXXX2  OK      OK      OK
```

```
3PAR02 cli% shownode -ps -verbose
---------------Node 0 PS 0----------------
Node ID                 :   0
Power Supply ID         :   0
Manufacturer            :   XYRATEX
Assembly Part           :   682372-001
Assembly Serial Number  :   5CQLQAXXXXXXX1
State                   :   OK
Fan State               :   OK
Fan Speed               :   Low
AC State                :   OK
DC State                :   OK
Battery State           :   OK
Battery Detail State    :   normal
Battery Charge State    :   FullyCharged
Battery Charge Level(%) :   100
Max Battery Life(mins)  :   16

---------------Node 0 PS 1----------------
Node ID                 :   0
Power Supply ID         :   1
Manufacturer            :   XYRATEX
Assembly Part           :   682372-001
Assembly Serial Number  :   5CQLQAXXXXXXX2
State                   :   OK
Fan State               :   OK
Fan Speed               :   Low
AC State                :   OK
DC State                :   OK
Battery State           :   OK
Battery Detail State    :   normal
Battery Charge State    :   FullyCharged
Battery Charge Level(%) :   100
Max Battery Life(mins)  :   16
```

**Comment by garnier-quentin** [comment]
You can test with following archive: https://github.com/centreon/centreon-plugins/archive/refs/heads/MON-14751-3par-add-modes.zip

https://github.com/centreon/centreon-plugins/pull/3862

**Comment by Aleksey-Maksimov** [comment]
Hmm.. How about a new commit?

**Comment by garnier-quentin** [comment]
What do you mean by a new commit ?

**Comment by Aleksey-Maksimov** [comment]
I mean why can't we add a new plugin to the https://github.com/centreon/centreon-plugins/commits/master branch
So that I can update it via git

**Comment by garnier-quentin** [comment]
Because i'm waiting to finish all developments for 3par ;)

**Comment by Aleksey-Maksimov** [comment]
Thanks @garnier-quentin ! 
This mode works.

![изображение](https://user-images.githubusercontent.com/17614847/193769050-718da4ee-b57e-4c57-823e-ae7c1b48f7b2.png)
