### ISSUE TITLE
[storage::hp::3par::ssh::plugin] Request a new mode "nodes" (with CPU perfdata)

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#3437]
Hello

Please make a new mode **nodes** in **storage::hp::3par::ssh::plugin** to check the status of 3PAR compute nodes and processor performance information.

The current implementation of monitoring in the `node.pm` code does not have checks for power performance information.
However, the state of CPU utilization in compute nodes is a key monitoring metric.
The information from the `statcpu -iter 1 -d 1` command will allow us to see the current load on all CPU cores.

Example:

```
3PAR02 cli% statcpu -iter 1 -d 1
17:34:58 01/27/2022
node,cpu user sys idle intr/s ctxt/s
     0,0    1   0   99
     0,1    1   1   98
     0,2    0   1   99
     0,3    1   1   98
     0,4    0   1   99
     0,5    0   1   99
     0,6    4   1   95
     0,7    0   0  100
 0,total    1   1   98   7276   9026

     1,0    0   0  100
     1,1    0   0  100
     1,2    0   0  100
     1,3    0   1   99
     1,4    0   0  100
     1,5    0   1   99
     1,6    0   2   98
     1,7    0   0  100
 1,total    0   1   99   5312   4799
```

From command help:

> col,statcpu - Explanation of column headers for statcpu
> 
> node,cpu        Node ID, CPU ID.
> user            Identifies a normal processes executing in user mode.
> sys             Percentage of time executing system threads.
> idle            Percentage of time idle.
> intr/s          Count of interrupts serviced per second.
> ctxt/s          Total number of context switches per second across all CPUs.

Data that is interesting to check and collect perfdata on them: "user" / "sys" / summary load (("user"+"sys") or (100%-"idle")) by each core and total on each CPU.
Here we suppose to see perfdata for "user"/"sys"/summary load with warn/crit thresholds.

In this mode, checking the current general state of the nodes with the `shownode -s` command can be added, similar to how it is done in the `node.pm`  code

```
3PAR01 cli% shownode -s
Node -State- -Detailed_State-
   0 OK      OK
   1 OK      OK
```

**Comment by Aleksey-Maksimov** [comment]
Hello Quentin

Do you need any more information from me?

**Comment by garnier-quentin** [comment]
You can test with following archive: https://github.com/centreon/centreon-plugins/archive/refs/heads/MON-14751-3par-add-modes.zip

https://github.com/centreon/centreon-plugins/pull/3862

**Comment by Aleksey-Maksimov** [comment]
Thanks Quentin!
This mode works well.

![изображение](https://user-images.githubusercontent.com/17614847/193777968-1f1f12e7-98ed-45af-95e4-36bb271012ee.png)
