### ISSUE TITLE
Junos Pulse is now Pulse Secure

### ISSUE THREAD

**Issue by CFRR** [centreon/centreon-plugins#344]
> Beginning on August 1, 2015, all Junos Pulse software and hardware products will be sold and supported by Pulse Secure. http://www.juniper.net/us/en/pulsesecure/

Which products are affected by the transition?

The following Juniper products will transition to Pulse Secure:

    IC Series Unified Access Control Appliance
    Junos Pulse software
    MAG Series Junos Pulse Gateways
    Odyssey Access Client
    SA Series SSL VPN Appliances
    SBR Enterprise Series

**Comment by garnier-quentin** [comment]
Thanks for the information.
