### ISSUE TITLE
[database::postgres::plugin] exclude option not filtering anything

### ISSUE THREAD

**Issue by sebastien-prudhomme** [centreon/centreon-plugins#3440]
## Bug/Question

Hi, i'm trying to convert our PostgreSQL services from https://bucardo.org/check_postgres/ to Centreon plugins with the help of the plugin packs.

It seems that there is a bug in the query-time when using '--exclude' option as in the plugin pack:

```
/usr/lib/centreon/plugins/centreon_postgresql.pl --plugin=database::postgres::plugin --mode=query-time --host=10.******* --username='*******' --password='*******' --port='5432'   --warning='120'  --critical='300' --exclude='^(?!(postgres|template1|template0))' --exclude-user='postgres' --verbose --debug
OK: All databases queries time are ok. | 'template0_qtime_num'=0;;;0; 'postgres_qtime_num'=0;;;0; 'dalibo_qtime_num'=0;;;0; 'template1_qtime_num'=0;;;0;
```

Excluded databases are not excluded as you can see in the perfdata returned by the plugin.

If I look in the code, it seems that this part should be done after the checks for exclusion, not before: https://github.com/centreon/centreon-plugins/blob/0442a08629168e44e3146aafdac0ff022817cca7/database/postgres/mode/querytime.pm#L89-L91

If not, $dbquery->{$row->{datname}} is always defined even for excluded databases.

**Comment by garnier-quentin** [comment]
It's fixed https://github.com/centreon/centreon-plugins/pull/3441

**Comment by sebastien-prudhomme** [comment]
Thanks @garnier-quentin
