### ISSUE TITLE
[hardware::server::ibm::mgmt_cards::imm::snmp::plugin] no Object at this OID

### ISSUE THREAD

**Issue by Bite404** [centreon/centreon-plugins#3453]
Hello,

I'm having problems with the monitoring of the IMM boards of our Lenovo Think System SR570 and SR650. When I run the following command, I get the output "all 0 components are ok"

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --hostname xxx --snmp-version=3 --snmp-username=xxx --authprotocol=xxx --authpassphrase=xxx --privprotocol=xxx --privpassphrase=xxx --mode=environment --component=cpu

Looking at /usr/lib/nagios/plugins/centreon-plugins/hardware/server/ibm/mgmt_cards/imm/snmp/mode/components/cpu.pm gives me the following line:

cpuHealthStatus => { oid => '.1.3.6.1.4.1.2.3.51.3.1.5.20.1.11' }

an snmpwalk with this OID however returns "No Such Object available on this agent at this OID". Tried this with multiple systems but error persists. Any ideas of what might be the issue here?

Thanks for the help

**Comment by garnier-quentin** [comment]
Could you try to snmpwalk the following branch ? .1.3.6.1.4.1.2.3.51.3.1.5.20.1

**Comment by Bite404** [comment]
That returns the following:
SNMPv2-SMI::enterprises.2.3.51.3.1.5.20.1 = No Such Object available on this agent at this OID

Although I have to stress that we use snpmv3 to monitor the IMMs as for some reason they could not be configured for snmpv2

**Comment by garnier-quentin** [comment]
If not present, it's ok. We cannot get the information. It's not an issue about the plugin.

**Comment by Bite404** [comment]
I'm sorry to have wasted your time, seems like there was a mistake on my part. Using the plugin hardware::server::lenovo::xcc::snmp::plugin works.

Thanks for your help

**Comment by garnier-quentin** [comment]
It's ok. Glad you find the good plugin :)
