### ISSUE TITLE
Timeout when checking memory of Windows with SQL Server running

### ISSUE THREAD

**Issue by SpecialOOps** [centreon/centreon-plugins#3454]
-- FRENCH --

Bonjour, j'ai un petit soucis qui arrive de manière récurrente...

Le check : os::windows::snmp::plugin --mode memory
La machine virtuelle : Windows Server 2012/2016
Services en cours sur les machines : SQL Server.

J'ai créé le check il y à plusieurs semaines maintenant tout se passais bien jusqu'au moment ou j'ai commencé à voir des dégradations sur le statut. Ok --> Unknown --> OK

Rien n'a changé au niveau des machines ni sur le centreon en lui même.
Le réseau n'a également pas changé. D'où ma question, pourquoi cela arrive t-il ?

Windows Server 2016:
![image](https://user-images.githubusercontent.com/20866916/152120516-b3df3003-b85f-43fb-8c0c-ee604bd08544.png)

Windows Server 2012:
![image](https://user-images.githubusercontent.com/20866916/152120565-4e1f0496-34f0-4860-a1b2-c9d95d60f2bf.png)

Deux checks entre quelques minutes :
![Centreon_Support](https://user-images.githubusercontent.com/20866916/152123554-d53c4cc4-73e9-4afd-812b-5be4fbd4d80e.png)

Je peux également vous envoyer d'avantages d'informations si besoin.

-- ENGLISH --

Bonjour, j'ai un petit soucis qui arrive de manière récurrente...
Hello, i have a small problem which occurs recurrently...

Check : os::windows::snmp::plugin --mode memory
Virtual Machine : Windows Server 2012/2016
Running services : SQL Server.

I've created the check weeks ago, everything was working fine till i saw some deteriorations on the status : OK --> Unknown --> OK
Nothing changed on the Virtual Machines and neither on Centreon...
Even at the Network layer...

So my question is, why does it happens ?

Windows Server 2016:
![image](https://user-images.githubusercontent.com/20866916/152120516-b3df3003-b85f-43fb-8c0c-ee604bd08544.png)

Windows Server 2012:
![image](https://user-images.githubusercontent.com/20866916/152120565-4e1f0496-34f0-4860-a1b2-c9d95d60f2bf.png)

The two checks between some times : 
![Centreon_Support](https://user-images.githubusercontent.com/20866916/152123505-8efa8cb1-19d2-4376-a554-f624fbdd6a92.png)

I can send you more information if needed.

**Comment by Sims24** [comment]
Hello, 

Could you please try with these options: 

--snmp-timeout=3 --snmp-autoreduce

**Comment by SpecialOOps** [comment]
Hello, 

I tested it on the server which doesn't give us any information anymore.
And it works fine with your command.

![Centreon_Support_2](https://user-images.githubusercontent.com/20866916/152124871-5cfac6e9-51c4-4ffb-bfdf-58674e968796.png)

Do you have an explanation on why it was working fine and now it wouldn't work with the same commands and without change ?
The Virtual Machine doesn't have a bigger load than it was at the start of the check...

Anyway thanks again :)

**Comment by Sims24** [comment]
Hi @SpecialOOps 

Probably that the server has seen its overall load increasing and then couldn't answer to SNMP request as fast as we would expect from it.

**Comment by SpecialOOps** [comment]
Okay, but still it seems strange because it's a server on cluster which we reduced the number of interaction with all the databases.
So the load should have decreased... But Okay i'll keep that in mind :D 

Thanks again :)

**Comment by HMA1986** [comment]
Bonjour Messieurs ,

j'ai le même souci au niveau d'un serveur exchange mbx , est que c'est possible de partager les commandes et comment les exécuter pour résoudre ce souci svp, merci par avance

**Comment by SpecialOOps** [comment]
> Bonjour Messieurs ,
> 
> j'ai le même souci au niveau d'un serveur exchange mbx , est que c'est possible de partager les commandes et comment les exécuter pour résoudre ce souci svp, merci par avance

Tout est décrit dans les screens et les messages.

Ce post date de très longtemps et je doute qu'il soit utile de re commenter celui ci...
