### ISSUE TITLE
A new plug-in for Avaya IP-Phone can be added

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#3458]
Hello.

I think it's possible to add a new plug-in for **Avaya IP-Phone** without much effort. 
The IP phones of the **J100** series, which I have been able to test, are successfully monitored by basic indicators as a normal **Linux** system.
That is, the following modes work successfully from **os::linux::snmp::plugin** :

- cpu
- interfaces
- load
- memory
- uptime

I wrote a short note about it, where I demonstrated that it works: [Monitoring Avaya IP-Phone in Icinga with Centreon Plugins](https://wiki.it-kb.ru/icinga/centreon-plugins/avaya-ip-phone-monitoring)

**Comment by garnier-quentin** [comment]
That kind of equipment doesn't have some entreprise MIB with specific metrics ?

**Comment by Aleksey-Maksimov** [comment]
It has. But there is not much information there.
A simple inventory example can be found [here.](https://wiki.it-kb.ru/avaya/avaya-ip-phone-j100-series-j139-j189-oids-for-snmp-monitoring)
I am attaching the [Avaya-J100IpPhone-MIB.zip](https://github.com/centreon/centreon-plugins/files/7994594/Avaya-J100IpPhone-MIB.zip)

**Comment by garnier-quentin** [comment]
There is the following branch: .1.3.6.1.4.1.6889
Could you provide a snmpwalk ? Maybe some informations can be monitored

**Comment by Aleksey-Maksimov** [comment]
[snmpwalk_VoIP_phone_Avaya_J189.zip](https://github.com/centreon/centreon-plugins/files/8033054/snmpwalk_VoIP_phone_Avaya_J189.zip)

**Comment by garnier-quentin** [comment]
You could use the linux snmp standard no ?

**Comment by Aleksey-Maksimov** [comment]
You understood me wrong. I wrote in the first post that I solved the monitoring task using the "os::linux::snmp::plugin" plugin. I just suggested expanding the list of plugins by making an internal reference to "os::linux::snmp::plugin".

If you do not need it and are not interested, you can simply close this thread.

**Comment by garnier-quentin** [comment]
Ok i see. It can be interesting.
