### ISSUE TITLE
centreon_prometheus_api.pl : UNKNOWN status on empty result

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon-plugins#3459]
Bonjour,

This is a feature request.

Version of the plugin : centreon-plugin-Cloud-Prometheus-Api-20210915-070550.el7.centos.noarch

I have the following PromQL query: `--query='error,max_over_time(kube_pod_container_status_last_terminated_reason{namespace="foo"}[1h])'`

used with the following thresholds: `--warning-status='%{errors} > 0' --critical-status='%{errors} > 5'`

It works if there is an error, or many, but it raises an unknown status when there isn’t any error. I’d like it to raise an OK status in this case, with a custom message.

I tried to add this at the end of the query: “or on() vector(0)”, it then returns a result ({} 0), but it still considered an empty result by the plugin.

Can you please add an option to force a particular status/message on empty query results? Something like _--empty-status_ and _--empty-output_ for example.

I’m also interested in any PromQL query that could fit my need (ie: a query that would never return an empty result) but that’s another thing.

Have a nice day.

**Comment by garnier-quentin** [comment]
You can use the plugin apps::protocols::http with the collection mode. Or you can trick what do you use:
```
--opt-exit=ok --change-short-output='No expressions found.~my message~'
```

**Comment by StefThomas** [comment]
Bonjour,

C’est dommage de ne pas avoir une option pour le plugin Prometheus.

Ceci dit nous avons trouvé une solution de contournement en ajoutant à la fin de la requête : « or on() absent(nonexistent{pod="null"}) » et « and %{instance} !~ /^null$/ » pour les seuils.

Vous pouvez fermer le ticket.

Bonne journée.


Stéphane THOMAS

ETL & Outils – DOT
Bureau 101

Harmonie Mutuelle

☎ +332 47 46 52 87

________________________________
De : qgarnier ***@***.***>
Envoyé : jeudi 3 mars 2022 09:13
À : centreon/centreon-plugins ***@***.***>
Cc : THOMAS Stéphane ***@***.***>; Author ***@***.***>
Objet : [ToC] Re: [centreon/centreon-plugins] centreon_prometheus_api.pl : UNKNOWN status on empty result (Issue #3459)


Ce courriel provient d'un expéditeur externe à l'organisation.

Soyez prudent lorsque vous cliquez sur un lien car celui-ci peut vous emmener sur un site web malveillant et n'ouvrez pas de pièce jointe à moins de reconnaître l'expéditeur et de savoir que le contenu est sûr.



You can use the plugin apps::protocols::http with the collection mode. Or you can trick what do you use:

--opt-exit=ok --change-short-output='No expressions found.~my message~'


—
Reply to this email directly, view it on GitHub<http://mail14.sihm.fr:32224/?dmVyPTEuMDAxJiYxMmVjY2I3Nzg4MGE2YTc2MT02MjIwNzhCQ180MDE0Nl8xOTg2N18xJiY5ZDEwZTgzYzdhODdmYTU9MTIzMyYmdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViJTJFY29tJTJGY2VudHJlb24lMkZjZW50cmVvbi1wbHVnaW5zJTJGaXNzdWVzJTJGMzQ1OSUyM2lzc3VlY29tbWVudC0xMDU3Nzg2MzM3>, or unsubscribe<http://mail14.sihm.fr:32224/?dmVyPTEuMDAxJiYxMmVjYzY3ZDkyMTc3ZTdhMT02MjIwNzhCQ180MDE0Nl8xOTg2N18xJiY1ZGU1NTg5Y2RhODc4Zjg9MTIzMyYmdXJsPWh0dHBzJTNBJTJGJTJGZ2l0aHViJTJFY29tJTJGbm90aWZpY2F0aW9ucyUyRnVuc3Vic2NyaWJlLWF1dGglMkZBSkpENVc3TURCRFdIU0NWSVE2NUVFM1U2QllEWEFOQ05GU001Tk9UWFlXUQ==>.
Triage notifications on the go with GitHub Mobile for iOS<http://mail14.sihm.fr:32224/?dmVyPTEuMDAxJiYxYWVkY2I3ZDhiNTE3OTYzMD02MjIwNzhCQ180MDE0Nl8xOTg2N18xJiY2OTA0MDkwZDJhYTZlZmE9MTIzMyYmdXJsPWh0dHBzJTNBJTJGJTJGYXBwcyUyRWFwcGxlJTJFY29tJTJGYXBwJTJGYXBwbGUtc3RvcmUlMkZpZDE0NzczNzY5MDUlM0ZjdCUzRG5vdGlmaWNhdGlvbi1lbWFpbCUyNmFtcCUzQm10JTNEOCUyNmFtcCUzQnB0JTNENTI0Njc1> or Android<http://mail14.sihm.fr:32224/?dmVyPTEuMDAxJiYxM2E2ODY3MTg5MTMzNzYwMD02MjIwNzhCQ180MDE0Nl8xOTg2N18xJiYyZDA1Mzg1OGRhNzdiYTc9MTIzMyYmdXJsPWh0dHBzJTNBJTJGJTJGcGxheSUyRWdvb2dsZSUyRWNvbSUyRnN0b3JlJTJGYXBwcyUyRmRldGFpbHMlM0ZpZCUzRGNvbSUyRWdpdGh1YiUyRWFuZHJvaWQlMjZhbXAlM0JyZWZlcnJlciUzRHV0bSU1RmNhbXBhaWduJTI1M0Rub3RpZmljYXRpb24tZW1haWwlMjUyNnV0bSU1Rm1lZGl1bSUyNTNEZW1haWwlMjUyNnV0bSU1RnNvdXJjZSUyNTNEZ2l0aHVi>.
