### ISSUE TITLE
[2.7.2] Plugins not working with perl connector - unknown

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#346]
I would like to enable the perl connector for centreon plugins but check with perl connector enabled always shows status "unknown". Perl connector is startet successfull, plugins are installed under '/usr/lib/nagios/plugins'. The problem is indipendent from "enable shell" parameter.

**Comment by garnier-quentin** [comment]
The performance won't be improved with perl connector and centreon-plugins. You can improve performance if you build "centreon-plugins" with "App::Fatpacker". Otherwise don't use the perl connector ;)

**Comment by CPbN** [comment]
> The performance won't be improved with perl connector and centreon-plugins.

@garnier-quentin, rather interesting, could you elaborate / give some more technical details please ?
Is it still the case ?
As perl connector will load the code and keep it compiled in memory for subsequent executions, won't we improve performance ?
Thank you very much :+1:

**Comment by CPbN** [comment]
Thank you @Sims24 four your answer, while Quentin is in vacation :+1: 

OK, so we need to fatpack the plugins to take the best from the Perl Connector, which finally makes sense according to how Centreon Plugins project is developed.

Thank you again !

**Comment by CPbN** [comment]
I was thinking about the following.
What about a Bash script `build_fatpack.sh` in the root directory of this project, which would build the fatpack version of every plugin ?
These fatpack versions would then go into a `fatpack` directory inside the project directory, without modifying the project files.
One could then still use `centron_plugins.pl` as usual, and/or the fatpack versions inside `fatpack`.

Of course I've looked at the procedure to build fatpack versions, but it's not really clear which `.pm` files are required for every plugin.
An automated script could then make sense :+1:

**Comment by Sims24** [comment]
Hum, clearly we thinked about it but parse all the "use" directive on the plugins is not really relevant nor reliable to build the fatpack. 

Theses ones are required for every plugins : 

'centreon/plugins/misc.pm', 'centreon/plugins/mode.pm', 'centreon/plugins/options.pm',
'centreon/plugins/output.pm', 'centreon/plugins/perfdata.pm', 'centreon/plugins/script.pm',
'centreon/plugins/statefile.pm', 'centreon/plugins/values.pm',
'centreon/plugins/alternative/Getopt.pm', 'centreon/plugins/alternative/FatPackerOptions.pm', 
'centreon/plugins/templates/counter.pm', 'centreon/plugins/templates/hardware.pm'

you then need to add the plugin pm and modes pm, and also dependencies (e.g SNMP.pm).

**Comment by CPbN** [comment]
I finally wrote a script and just proposed it through PR #1093.
