### ISSUE TITLE
[hardware::printers::standard::rfc3805::plugin] Paper tray mode shows critical when paper is full and ok wether is full or empty

### ISSUE THREAD

**Issue by LemonLight** [centreon/centreon-plugins#3460]
Hello everyone,

I have unexpected behaviour with the following module hardware::printers::standard::rfc3805::plugin using the paper tray mode.

Printer model : Canon iR ADV C3525III
With have 5 drawers in the photocopier :

1. Right drawer, only for specific format, id=1#1
2. Front A4 drawer, id=1#2
3. Front A4 drawer, id=1#3
4. Front A4 drawer, id=1#4
5. Front A3 drawer, id=1#5

First, through my tries I guess that warning and critical threshold are an empty percentage and not a fill percentage. Am I right on this point ?
Then, I feel like my printer only shows 3 levels of paper tray fill which are 0%, 50% and 100%.
Eventually, we have 3 trays of A4 paper format and we want to monitor paper tray separately. 

So now, here's the behaviours : 

1. Second front drawer is empty (0%)
The status is always OK whatever the critical threshold value (90 by default in our service template).

- Command with critical value set to 100 : `perl centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=device.example.com --snmp-version=1 --snmp-community=public --critical=100 --filter-tray="1#3"`
Result : `OK: Paper tray usages are ok. | 'tray_1#3'=0.00%;;0:100;0;100`

- Command with critical value set to 0 : `perl centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=device.example.com --snmp-version=1 --snmp-community=public --critical=0 --filter-tray="1#3"`
Result : `OK: Paper tray usages are ok. | 'tray_1#3'=0.00%;;0:0;0;100`

2. Third front drawer is full (100%)
The status looks to be the opposite of what we have seen before. As I said before, we note that the threshold are an empty percentage and not a fill one. For example, with drawer filled at 50%, when I put --critical to 40 it shows critical and OK when --critical is set to 60.
However, the result is not following this guideline. When critical is set to 90, it shows critical.

- Command with critical value set to 100 : `perl centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=device.example.com --snmp-version=1 --snmp-community=public --critical=100 --filter-tray="1#4"`
Result : `OK: Paper tray usages are ok. | 'tray_1#4'=100.00%;;0:100;0;100`

- Command with critical value set to 0 : `perl centreon_plugins.pl --plugin=hardware::printers::standard::rfc3805::plugin --mode=papertray-usage --hostname=device.example.com --snmp-version=1 --snmp-community=public --critical=0 --filter-tray="1#4"`
Result : `CRITICAL: Paper tray '1#4': 100.00 % | 'tray_1#4'=100.00%;;0:0;0;100`

Any idea ? Maybe I am just lost in all of this 😄 
Thanks in advance !

**Comment by garnier-quentin** [comment]
Plugin supports following syntax: https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
In your case: ```--critical=100:```

**Comment by LemonLight** [comment]
As simple as that ! Thank you.

And it means the feeling we have with the calculation of an empty percentage was wrong. It's definitely a fill percentage so the --critical value should be 10: in our case. When it's fill less than 10%, it shows critical.

Cheers!
