### ISSUE TITLE
[apps::protocols::http::plugin] regression with expected-content (curl and ntlm)

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3467]
Hi,

From version centreon-plugin-Applications-Protocol-Http-20220113-084434.el7.centos.noarch , I have : 
CRITICAL: 401 Unauthorized

With version centreon-plugin-Applications-Protocol-Http-20211215-090334.el7.centos.noarch, I have : 
OK: HTTP test(s) | 'size'=3771B;;;0; 'time'=0.170s;0:2;0:3;0;

By changing the new lines 2187/2188 (in comment)
` #          } if (defined($options{request}->{digest})) { `
` #              $self->curl_setopt(option => $self->{constant_cb}->(name => 'CURLOPT_HTTPAUTH'), parameter => $self->{constant_cb}->(name => 'CURLAUTH_DIGEST'));`

I have again : 
OK: HTTP test(s) | 'size'=3771B;;;0; 'time'=0.142s;0:2;0:3;0;

The command is : 
/usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --proto='http' --port='80' --hostname='website' --urlpath='/' --expected-string='' --method='GET' --warning-status='' --critical-status='%{http_code} > 400' --warning-content='' --critical-content='' --warning-size='' --critical-size='' --warning-time='2' --critical-time='3'  --http-backend=curl --opt-exit=critical --ntlmv2 --credentials --username=domain/user --password=xxxxxxxxxxxxxxxxxxx

**Comment by garnier-quentin** [comment]
Sorry. it's fixed in last version. It will be available on unstable repository soon
