### ISSUE TITLE
plugin database::oracle : working on shell as root but not as centreon-engine user

### ISSUE THREAD

**Issue by forever-noob08** [centreon/centreon-plugins#3469]
Hello,

I installed Oracle Database plugin following this documentation: https://docs.centreon.com/21.04/en/integrations/plugin-packs/procedures/applications-databases-oracle.html

I can connect to my Oracle database with no problem as user root:
```
# /usr/lib/centreon/plugins/centreon_oracle.pl --plugin=database::oracle::plugin --hostname='*.*.*.*' --port='1521' --sid='*' --username='***' --password='****' --mode='tablespace-usage' --warning-tablespace='90' --critical-tablespace='98' --verbose
OK: All tablespaces are OK |...
```
But running it as centreon-engine returns the error "UNKNOWN: Cannot connect: (no error string)" :
`$ /usr/lib/centreon/plugins/centreon_oracle.pl --plugin=database::oracle::plugin --hostname='****' --port='1521' --sid='****' --username='****' --password='****' --mode='tablespace-usage' --warning-tablespace='90' --critical-tablespace='98' --verbose
UNKNOWN: Cannot connect: (no error string)`

My issue seems similar to #2171 but I had no success in resolving it so far.
Here is the return of the printenv command in case it helps :
`# printenv
XDG_SESSION_ID=104465
HOSTNAME=*****
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=*****
SSH_TTY=/dev/pts/0
NO_PROXY=127.0.0.1,localhost
http_proxy=http://*****
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
FTP_PROXY=http://*****
ftp_proxy=http://*****
MAIL=/var/spool/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PWD=/root
LANG=fr_FR.UTF-8
HTTPS_PROXY=http://*****
https_proxy=http://*****
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
no_proxy=127.0.0.1,localhost
HTTP_PROXY=http://*****
LOGNAME=root
SSH_CONNECTION=*****
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_RUNTIME_DIR=/run/user/0
_=/usr/bin/printenv`

Can you please help me ?

Best regards

**Comment by garnier-quentin** [comment]
Where have you installed DBD::Oracle ?

**Comment by forever-noob08** [comment]
I installed it from cd /usr/local/src  and I got this message at the end of Makefile:
LD_RUN_PATH=/usr/lib/oracle/21/client64/lib
Using DBD::Oracle 1.80.
Using DBD::Oracle 1.80.
Using DBI 1.627 (for perl 5.016003 on x86_64-linux-thread-multi) installed in /usr/lib64/perl5/vendor_perl/auto/DBI/
Writing Makefile for DBD::Oracle

Hope that answers your question.

**Comment by garnier-quentin** [comment]
Could you check directory for DBD/Oracle.pm file ? It's not in /usr/local/src

**Comment by forever-noob08** [comment]
```
# locate Oracle.pm
/usr/local/lib64/perl5/DBD/Oracle.pm
/usr/local/src/DBD-Oracle-1.80/blib/lib/DBD/Oracle.pm
/usr/local/src/DBD-Oracle-1.80/lib/DBD/Oracle.pm
```

**Comment by garnier-quentin** [comment]
With centengine user, can you read the file:
```
/usr/local/lib64/perl5/DBD/Oracle.pm
```

You can strace the plugin to see the issue.

**Comment by forever-noob08** [comment]
I can't read the file with centreon-engine user:
```
$ cat /usr/local/lib64/perl5/DBD/Oracle.pm
cat: /usr/local/lib64/perl5/DBD/Oracle.pm: Permission non accordée
```
I have not strace installed on my system

**Comment by forever-noob08** [comment]
Selinux is disabled
```
# sestatus
SELinux status:                 disabled
```

**Comment by garnier-quentin** [comment]
I think so. You can also test with last git version: https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip
You'll get an error message.

**Comment by forever-noob08** [comment]
Not better with rights to centreon-engine:
```
$ ls -al /usr/local/lib64/perl5/DBD/Oracle.pm 
-rw-r--r-- 1 centreon-engine root 211442 25 juil.  2019 /usr/local/lib64/perl5/DBD/Oracle.pm
bash-4.2$ /usr/lib/centreon/plugins/centreon_oracle.pl --plugin=database::oracle::plugin --hostname='192.168.10.139' --port='1521' --sid='ADBD' --username='system' --password='F_11anvier' --mode='tablespace-usage' --warning-tablespace='90' --critical-tablespace='98' --verbose
UNKNOWN: Cannot connect: (no error string)
```

What do you mean when you say "test with last git version ?"

**Comment by garnier-quentin** [comment]
You can test it with that archive: https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip
