### ISSUE TITLE
Add support for AKCP SensorProbe

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#347]
Hi Quentin,

it would be great if you can add checks for AKCP SensorProbe.
[AKCP_OID_SNMP manual.pdf](https://github.com/centreon/centreon-plugins/files/145353/AKCP_OID_SNMP.manual.pdf)

Best regards,
Jochen

**Comment by garnier-quentin** [comment]
i'll need to entreprise mib files and a complete snmpwalk. Thanks!

**Comment by joschi99** [comment]
Hi Quentin,

this is a full snmpwalk for a SensorProbe2. I will try to get the complete Enterprise MiB.
[akcp_sensorprobe2.txt](https://github.com/centreon/centreon-plugins/files/146358/akcp_sensorprobe2.txt)

**Comment by joschi99** [comment]
[akcp-mibs.zip](https://github.com/centreon/centreon-plugins/files/146365/akcp-mibs.zip)

**Comment by garnier-quentin** [comment]
Could you test it please ?
