### ISSUE TITLE
hardware::devices::hikvision::nvr::snmp::plugin : UNKNOWN: SNMP Session : unable to create

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3479]
Hello,

The command : 

`./centreon_plugins.pl --plugin=hardware::devices::hikvision::nvr::snmp::plugin --mode=uptime --hostname='xx.xx.xx.xx' --snmp-version=='2c' --snmp-community='snmp' --verbose --debug`

Return : 

`UNKNOWN: SNMP Session : unable to create`

I have enable snmp in my NVR

Then model is : DS-7616NI-K2 / 16P

Thank you

**Comment by prohand** [comment]
Thank you, how to test the ISAPI?

**Comment by Aleksey-Maksimov** [comment]
Yes. Quentin is right. You'd be better off using ISAPI. 
Just don't forget to enable HTTPS on the NVR.

```
./centreon_plugins.pl --plugin=hardware::devices::hikvision::nvr::isapi::plugin 
--mode=uptime 
--api-password='myPWD' --api-username='admin' 
--hostname='myNVRFQDN' 
--proto='https' 
--ssl-opt='SSL_verify_mode => SSL_VERIFY_NONE'
```

**Comment by prohand** [comment]
Thank you with the admin account everything works.
However, I tried to create a dedicated user but I got this message:
UNKNOWN: 401 Unauthorized (Digest authentication expected)
Is this normal?

Thank you

**Comment by Aleksey-Maksimov** [comment]
Yes. I was also unable to use an unprivileged user to access ISAPI. It seems that this is such a miserable implementation. Hikvision is generally very bad with microcode. There are a few unresolved issues even with SNMP, and Hikvision's tech support is terrible.

**Comment by prohand** [comment]
Ok thank you
