### ISSUE TITLE
Check tablespace usage by '% used' and 'remaining space' at the same time

### ISSUE THREAD

**Issue by outon** [centreon/centreon-plugins#3481]
I have noticed that it is possible to check tablespace usage by % and by units.

I have, in the same database, very large tablespace and small tablespaces, 

```
Tablespace 'TBS1' Total:  1.50 TB, Used:  1.45 TB (96.67%), Free: 50.00 GB ( 3.33%)
Tablespace 'TBS2' Total: 20.00 GB, Used: 18.00 GB (90.00%), Free:  2.00 GB (10.00%)
Tablespace 'TBS3' Total: 20.00 GB, Used: 12.00 GB (60.00%), Free:  8.00 GB (40.00%)
```
That means that if I check by **90% used** I may get my large tablespace TBS1 as critical even if it has up to 150 GB free.

And if I check by 10 GB of space remaining, my small tablespace will always get as critical even if it has more than 50% free.

I need to combine both rules... **% used** and **space remaining**.  The tablespace cannot be considered critical until it meets that it has less than 10GB free and that occupancy is greater than 90% usage.

Therefore, the end result will be the lower criticality of both results.

Sample of tablespace usage by % used:
```
./centreon_oracle.pl \
    --mode tablespace-usage \
    --datasource Oracle:{my_hostname}:1521/{my_servicename} \
    --username {my_username} \
    --password {my_password} \
    --warning-tablespace 80 \
    --critical-tablespace 90 \
    --units % 
```

Sample of tablespace usage by remaining space:

```
./centreon_oracle.pl \
    --mode tablespace-usage \
    --datasource Oracle:{my_hostname}:1521/{my_servicename} \
    --username {my_username} \
    --password {my_password} \
    --warning-tablespace 30: \
    --critical-tablespace 10: \
    --units GB
```

So, Is it possible to check both rules at the same time?

**Comment by outon** [comment]
I guess that you are talking about latest releases... I have got Centreon 2.8.22

**Comment by garnier-quentin** [comment]
It was available in autodiscovery for your version. But you need autodiscovery module.
