### ISSUE TITLE
plugin apps::vmware::connector::plugin mode licences not exist

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-plugins#3482]
Hello,

I have execute this command : 

`/usr/lib/centreon/centreon-plugins//centreon_plugins.pl --plugin apps::vmware::connector::plugin --connector-hostname=127.0.0.1 --container vcenter --mode licences`

And the result is : 

`UNKNOWN: mode 'licences' doesn't exist (use --list-mode option to show available modes)`

I have the last version of centreon-plugin and the licences is appear in modes available
Thank you

**Comment by garnier-quentin** [comment]
It's ```licenses``` in english ;)

**Comment by prohand** [comment]
Oh sorry ;)
It's Ok
