### ISSUE TITLE
Accesspoint Checks not working after SmartZone Controller Update

### ISSUE THREAD

**Issue by TheBienek** [centreon/centreon-plugins#3483]
After Upgrading the Software of the SmartZone Controller the access-point checks return an UNKNOWN: SNMP Table Request.

The Software Version is 6.1.0.0.935.

**Comment by garnier-quentin** [comment]
Could you provide the command line exactly and the output ?

**Comment by TheBienek** [comment]
The used comman line is:
/usr/lib/centreon/plugins//centreon_ruckus_smartzone_snmp.pl
	--plugin network::ruckus::smartzone::snmp::plugin
	--mode='access-points'
	--hostname='192.168.26.202'
	--snmp-community='public'
	--snmp-version='2c'
The Output simply says: UNKNOWN: SNMP Table Request

We have however found out that changing the command line to:
/usr/lib/centreon/plugins//centreon_ruckus_smartzone_snmp.pl
	--plugin network::ruckus::smartzone::snmp::plugin
	--mode='access-points'
	--hostname='192.168.26.202'
	--snmp-community='public'
	--snmp-version='2c'
        --snmp-timeout=60

fixes the issue.
Our support company has now installed a workaround to allow the check to have a duration of 120 which should fix the issue. We do have quite a lot of accesspoints on the controllers.
