### ISSUE TITLE
How to add a warning threshold to string-value mode.

### ISSUE THREAD

**Issue by RubenJIF** [centreon/centreon-plugins#3487]
## Question

Hi, How can i set a warning thresshold using de string-value mode?
OID's type: OctectString
My perl code:

`perl centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=string-value --hostname=x.x.x.x --snmp-version=2 --snmp-community=XX --oid=.1.3.6.1.4.1.XX.19.3.2.2.101.0 --format-ok='%{details_ok}' --format-details-warning='current value is: %{details_warning}' --format-details-critical='current value is: %{details_critical}'` 

it shows:

> 
>OK: Total Number of bits received : 2005099896
>
>Vertical BER Analysis:
>     (QPSK) Modulation:
>         Bit Errors:     0
>          Bit Error Rate: 0.000000e+00
>Horizontal BER Analysis:
>      (QPSK) Modulation:
>           Bit Errors:     0
>          Bit Error Rate: 0.000000e+00 |

But i want to set warning threshold for all error in BER Analysis values ​​above 0.
for example:

>Warning: Total Number of bits received : 2005099896
>
>Vertical BER Analysis:
>      (QPSK) Modulation:
>           Bit Errors:     5
>           Bit Error Rate: 0.000000e+00
>Horizontal BER Analysis:
>      (QPSK) Modulation:
>           Bit Errors:     5
>           Bit Error Rate: 0.000000e+00 |

Thanks for the suggestions.

**Comment by garnier-quentin** [comment]
What did you have in the OID .1.3.6.1.4.1.XX.19.3.2.2.101.0 with snmpwalk ? Because i don't really understand the content of that OID.

**Comment by RubenJIF** [comment]
#snmpwalk -v 2c -c X IP .1.3.6.1.4.1.161.19.3.2.2.101.0
![image](https://user-images.githubusercontent.com/6829254/154108644-35faf085-0128-417a-9b56-d9d272af8be5.png)

Two different copy from de MIB Browser:

#Name/OID: mimoQpskBerDisplay.0; Value (OctetString): 0x54 6F 74 61 6C 20 4E 75 6D 62 65 72 20 6F 66 20 62 69 74 73 20 72 65 63 65 69 76 65 64 20 3A 20 36 35 30 39 34 39 34 30 30 0A 0A 56 65 72 74 69 63 61 6C 20 42 45 52 20 41 6E 61 6C 79 73 69 73 3A 0A 20 20 20 20 20 20 28 51 50 53 4B 29 20 4D 6F 64 75 6C 61 74 69 6F 6E 3A 0A 20 20 20 20 20 20 20 20 20 20 20 42 69 74 20 45 72 72 6F 72 73 3A 20 20 20 20 20 30 0A 20 20 20 20 20 20 20 20 20 20 20 42 69 74 20 45 72 72 6F 72 20 52 61 74 65 3A 20 30 2E 30 30 30 30 30 30 65 2B 30 30 0A 48 6F 72 69 7A 6F 6E 74 61 6C 20 42 45 52 20 41 6E 61 6C 79 73 69 73 3A 0A 20 20 20 20 20 20 28 51 50 53 4B 29 20 4D 6F 64 75 6C 61 74 69 6F 6E 3A 0A 20 20 20 20 20 20 20 20 20 20 20 42 69 74 20 45 72 72 6F 72 73 3A 20 20 20 20 20 30 0A 20 20 20 20 20 20 20 20 20 20 20 42 69 74 20 45 72 72 6F 72 20 52 61 74 65 3A 20 30 2E 30 30 30 30 30 30 65 2B 30 30 0A

#Name/OID: mimoQpskBerDisplay.0; Value (OctetString): Total Number of bits received : 650949400

Vertical BER Analysis:
      (QPSK) Modulation:
           Bit Errors:     0
           Bit Error Rate: 0.000000e+00
Horizontal BER Analysis:
      (QPSK) Modulation:
           Bit Errors:     0
           Bit Error Rate: 0.000000e+00

**Comment by RubenJIF** [comment]
The question is:
How can i make an alarm when Bit Error Rate is greater than 10^-6?.
Or i should use another OID?, the last one what i have is .1.3.6.1.4.1.161.19.3.2.2.57.0 who gives me a displaystring value
`"0.000000e+00"`

**Comment by RubenJIF** [comment]
> The question is: How can i make an alarm when Bit Error Rate is greater than 10^-6?. Or i should use another OID?, the last one what i have is .1.3.6.1.4.1.161.19.3.2.2.57.0 who gives me a displaystring value `"0.000000e+00"`

Hi, is there a way to convert the string to scientific values to get performance data values and make a graph?.

**Comment by garnier-quentin** [comment]
Right now, i don't have a solution.
Even with the mode collection you cannot do that. I need to add 2 methods: 
- lookup a string
- expand the exponential syntax

**Comment by garnier-quentin** [comment]
You can use the last git version.

First, you need to create a file on a directory. For example ```/tmp/test.json``` (need to set the right OID):
```
{
    "snmp": {
        "leefs": [
            { "name": "content", "oid": ".1.3.6.1.4.1.XX.19.3.2.2.101.0" }
        ]
    },
    "selection": [
        {
            "name": "vertical",
            "functions": [
                {
                    "type": "capture",
                    "src": "%(snmp.leefs.content)",
                    "pattern": "(?msi)Vertical BER Analysis.*?Bit Error Rate: (\\S+)",
                    "groups": [
                        { "offset": 0, "save": "%(bitErrorRate)" }
                    ]
                },
                {
                    "type": "scientific2number",
                    "src": "%(bitErrorRate)",
                    "save": "%(bitErrorRate)"
                }
            ],
            "warning": "defined(%(constants.warningBitErrorRate)) and %(constants.warningBitErrorRate) ne '' and %(bitErrorRate) > %(constants.warningBitErrorRate)",
            "critical": "defined(%(constants.criticalBitErrorRate)) and %(constants.criticalBitErrorRate) ne '' and %(bitErrorRate) > %(constants.criticalBitErrorRate)",
            "perfdatas": [
                { "nlabel": "verticalBerAnalysis.bit.errorRate", "value": "%(bitErrorRate)" }
            ],
            "formatting": {
                "printf_msg":"Vertical BER Analysis bit error rate is %s",
                "printf_var":[
                    "%(bitErrorRate)"
                ]
            }
        },
        {
            "name": "horizontal",
            "functions": [
                {
                    "type": "capture",
                    "src": "%(snmp.leefs.content)",
                    "pattern": "(?msi)Horizontal BER Analysis.*?Bit Error Rate: (\\S+)",
                    "groups": [
                        { "offset": 0, "save": "%(bitErrorRate)" }
                    ]
                },
                {
                    "type": "scientific2number",
                    "src": "%(bitErrorRate)",
                    "save": "%(bitErrorRate)"
                }
            ],
            "warning": "defined(%(constants.warningBitErrorRate)) and %(constants.warningBitErrorRate) ne '' and %(bitErrorRate) > %(constants.warningBitErrorRate)",
            "critical": "defined(%(constants.criticalBitErrorRate)) and %(constants.criticalBitErrorRate) ne '' and %(bitErrorRate) > %(constants.criticalBitErrorRate)",
            "perfdatas": [
                { "nlabel": "horizontalBerAnalysis.bit.errorRate", "value": "%(bitErrorRate)" }
            ],
            "formatting": {
                "printf_msg":"Horizontal BER Analysis bit error rate is %s",
                "printf_var":[
                    "%(bitErrorRate)"
                ]
            }
        }
    ],
    "formatting":{
        "custom_message_global": "All selections are OK",
        "separator": "-"
    }
}
```

After that you call the plugin:
```
perl centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=collection --hostname=XXX --snmp-version=2c  --snmp-community=XXX --config=/tmp/test.json
```

**Comment by RubenJIF** [comment]
Thanks for your help, it works!

I have those values ​​in decimal in my database, but in graph and csv it shows only up to 6 decimal places, i need more decimals.
Maybe looking for something about rrd, but for the plugin that's all I need, thanks!
