### ISSUE TITLE
Bug with check_centreon_snmp_remote_storage

### ISSUE THREAD

**Issue by nikaro** [centreon/centreon-plugins#349]
Output in Web interface :
```
Disk CRITICAL - no output (-p number expected... it doesn't exist, try another disk number)
```

But with in CLI with `sudo -u centreon-engine /usr/lib/nagios/plugins/check_centreon_snmp_remote_storage -H <IP_ADDRESS> -n -d "Swap Space" -w 80 -c 90 -v 2 -C public` it works fine.

It happens both on fresh install with CES ISO, or with packages installation on a fresh CentOS 6.

**Comment by garnier-quentin** [comment]
The following plugin is not updated. Could you use new ones ?

**Comment by nogomes** [comment]
Hi

Sometimes it happens in my web interface too

The only workaround I found is to delete the corresponding cache file in /var/lib/centreon/centplugins/remote_storage_cache_<hostip>

Then, when the check is re-executed, a new cachefile is created and the values are correct.

**Comment by garnier-quentin** [comment]
The plugin is deprecated. You cannont use new plugins ?

**Comment by nogomes** [comment]
Sure !  Just find the time to reconfigure my templates and objects already configured with the old command :-)

**Comment by nikaro** [comment]
Which is the new one that i need to use ? `check_centreon_snmp_remote_storage` is the one used by default on a fresh install.

**Comment by nikaro** [comment]
Ok i figured that new plugins are not included in CES, and that i should clone and use this repo.

Thank you.

**Comment by garnier-quentin** [comment]
Exactly ;)

**Comment by slapin95** [comment]
I have the same issue. I just do not understand, what are the new plugins?
Has check_centreon_snmp_remote_storage been replaced?
Thanks

**Comment by garnier-quentin** [comment]
You use plugins from old centreon version (check_centreon_snmp_xxxx). That project are new plugins.
