### ISSUE TITLE
Timeout on memory and Swap check

### ISSUE THREAD

**Issue by cmiscloni** [centreon/centreon-plugins#3491]
- Actual plugin version : 20210218
- Centreon server : CentOS 7
- Polling server : Windows Server 2019/2016/2012
- Firewall Disabled
I have a strange issue since few months, one by one, some server stopped to return SNMP informations about swap or memory.

centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=192.168.1.2 --snmp-version='2c' --snmp-community='public' --warning-memory='90' --critical-memory='95' --snmp-autoreduce
UNKNOWN: SNMP GET Request : Timeout

It's OK on a lot of servers except for 10 servers Windows, any ideas ?
Thanks

**Comment by SpecialOOps** [comment]
Hello i had the same problem, did you try to add --snmp-timeout=3 ?

https://github.com/centreon/centreon-plugins/issues/3454
Here my issue if it helps you ^^

**Comment by cmiscloni** [comment]
Oh yeah, you're a magician 
Thanks
