### ISSUE TITLE
Problems with MySQL/MariaDB Plugin after update

### ISSUE THREAD

**Issue by andreluizpr** [centreon/centreon-plugins#3492]
Hello all,

I'm having a problem with the MySQL plugin after updating it. More specifically in monitoring slow queries, as can be seen below:

Status Information: 
UNKNOWN: Cannot load module --mode.
syntax error at /usr/lib/centreon/plugins//centreon_mysql.pl line 10314, near ");"
Compilation failed in require at /usr/lib/centreon/plugins//centreon_mysql.pl line 2613.

Command:
/usr/lib/centreon/plugins//centreon_mysql.pl --plugin=database::mysql::plugin --host=123.456.789.0 --username='abdwdsd' --password='***' --port='3306' --mode='slow-queries' --warning='0' --critical='0' 

My environment:
OS: CentOS Linux release 7.9.2009 (Core)
Centreon 21.04.11
Plugin MySQL/MariaDB: 3.2.2 Stable

The problem started to occur after I made this update that was available in the repository:

===========================================================================================================================================================================================================
 Package                                                                        Arch                      Version                                          Repository                                 Size
===========================================================================================================================================================================================================
Updating:
 centreon-gorgone                                                               noarch                    21.04.5-1.el7.centos                             centreon-stable-noarch                    134 k
 centreon-gorgone-centreon-config                                               noarch                    21.04.5-1.el7.centos                             centreon-stable-noarch                    4.6 k
 centreon-plugin-Applications-Databases-Mysql                                   noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     58 k
 centreon-plugin-Applications-Databases-Postgresql                              noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     54 k
 centreon-plugin-Applications-Hibernate-Jmx                                     noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     39 k
 centreon-plugin-Applications-Monitoring-Centreon-Central                       noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     48 k
 centreon-plugin-Applications-Monitoring-Centreon-Database                      noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     59 k
 centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx                      noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     40 k
 centreon-plugin-Applications-Monitoring-Centreon-Poller                        noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     46 k
 centreon-plugin-Applications-Php-Fpm-Web                                       noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     44 k
 centreon-plugin-Applications-Protocol-Dns                                      noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     38 k
 centreon-plugin-Applications-Protocol-Ftp                                      noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     40 k
 centreon-plugin-Applications-Protocol-Http                                     noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     58 k
 centreon-plugin-Applications-Protocol-Imap                                     noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     37 k
 centreon-plugin-Applications-Protocol-Jmx                                      noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     41 k
 centreon-plugin-Applications-Protocol-Ldap                                     noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     38 k
 centreon-plugin-Applications-Protocol-Smtp                                     noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     37 k
 centreon-plugin-Applications-Webservers-Apache-Serverstatus                    noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     47 k
 centreon-plugin-Applications-Webservers-Nginx-Serverstatus                     noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     45 k
 centreon-plugin-Applications-Webservers-Tomcat-Jmx                             noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     45 k
 centreon-plugin-Applications-Webservers-Tomcat-Webmanager                      noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     48 k
 centreon-plugin-Hardware-Printers-Generic-Snmp                                 noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     46 k
 centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp                             noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     45 k
 centreon-plugin-Network-Cisco-Standard-Snmp                                    noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     91 k
 centreon-plugin-Network-Mikrotik-Snmp                                          noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     67 k
 centreon-plugin-Operatingsystems-Linux-Snmp                                    noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     78 k
 centreon-plugin-Operatingsystems-Windows-Snmp                                  noarch                    20220217-094259.el7.centos                       centreon-stable-noarch                     69 k

Transaction Summary
===========================================================================================================================================================================================================
Upgrade  27 Packages

No plugin updates are available in my environment;
The other updated plugins are all working correctly;
I didn't update my poolers and they are still working correctly;

Can I help me?

Thanks

André

**Comment by garnier-quentin** [comment]
Sorry for that bug. It's fixed and you could update it with the stable repository.
