### ISSUE TITLE
can't monitoring esx with centreon vmware connector after reboot centreon server (esxi 5.5)

### ISSUE THREAD

**Issue by Keliansrdl** [centreon/centreon-plugins#3497]
Hello,

following the reboot of my centreon server my esx are no longer supervised : 
![image](https://user-images.githubusercontent.com/100124349/154924655-3ad35373-3b21-4fae-bd2c-7361b884fd80.png)

/usr/lib/centreon/plugins//centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname=127.0.0.1 --mode=memory-host --esx-hostname=esx1 
send 

OK:  |

can someone help me please ?

**Comment by garnier-quentin** [comment]
Have you start the centreon-vmware daemon ?

**Comment by Keliansrdl** [comment]
yes it is started 
![image](https://user-images.githubusercontent.com/100124349/154939816-ee6495bb-a4c1-45d6-b1e5-38a705a3b62e.png)

**Comment by garnier-quentin** [comment]
You can look the centreon-vmware.log

**Comment by Keliansrdl** [comment]
in /var/log i don't have this file, where is it ?

**Comment by Keliansrdl** [comment]
ok, i found it in /var/log/centreon/ 

last log : 
2022-02-21 10:52:26 - 'default' SOAP request error - possibly a protocol issue: Server closed connection without sending any data back at /usr/local/share/perl5/Net/HTTP/Methods.pm line 391.


2022-02-21 11:46:35 - 'default' SOAP request error - possibly a protocol issue: Server closed connection without sending any data back at /usr/local/share/perl5/Net/HTTP/Methods.pm line 391.


2022-02-21 11:47:26 - 'default' SOAP request error - possibly a protocol issue: Server closed connection without sending any data back at /usr/local/share/perl5/Net/HTTP/Methods.pm line 391.

**Comment by garnier-quentin** [comment]
It's not the issue.  Could you call centreon-plugins with --debug option ?

**Comment by garnier-quentin** [comment]
Like that: ```/usr/lib/centreon/plugins//centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname=127.0.0.1 --mode=memory-host --esx-hostname=esx1 --debug```

**Comment by Keliansrdl** [comment]
result : 
[user@server ~]$ /usr/lib/centreon/plugins//centreon_plugins.pl --plugin=apps::vmware::connector::plugin --connector-hostname=127.0.0.1 --mode=memory-host --esx-hostname=esx1 --debug
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
OK:  |
[user@server ~]$

**Comment by Keliansrdl** [comment]
yes we agree, so do you have an idea to solve the problem?

**Comment by Keliansrdl** [comment]
Hello @garnier-quentin, 

Sorry to ask again, do you have any idea how to solve my problem?

Thanks in advance

**Comment by garnier-quentin** [comment]
I think we need to do a session. You can send me an email.

**Comment by Keliansrdl** [comment]
ok i do that, thanks

**Comment by garnier-quentin** [comment]
It was a issue about the client and the connector version. We have updated the client and it's ok now.
