### ISSUE TITLE
Supervise Unifi equipment

### ISSUE THREAD

**Issue by killianchmn-cpf** [centreon/centreon-plugins#3498]
## Problem with centreon

**Hello**, I have a problem with my centreon supervision
I want to supervise one of the _UNIFI_ equipment but an error message 
appears in the unknown services
despite several tries I can't find a solution, do you have an idea?

#### I have this error message appearing
`UNKNOWN: SNMP Table Request: Cant get a single value.`

Cordially

**Comment by garnier-quentin** [comment]
Please provide a snmpwalk of following branch:
.1.3.6.1.4.1

**Comment by killianchmn-cpf** [comment]
> Veuillez fournir un snmpwalk de la branche suivante : .1.3.6.1.4.1
> 
> Et les fichiers mibs de votre équipement.

### Thank you for your reply

**here is the branch of the snmpwalk to provide**
.1.3.6.1.2.1.1.2.0 = OID: [.1.3.6.1.4.1.8072.3.2.10]
[.1.3.6.1.4.1.8072.3.2.10.txt](https://github.com/centreon/centreon-plugins/files/8109709/default.1.3.6.1.4.1.8072.3.2.10.txt)

I don't use any particular mibs file

**Comment by garnier-quentin** [comment]
Your files seems incomplete. I dont see oid beginning by ```.1.3.6.1.4.1```

**Comment by killianchmn-cpf** [comment]
I only found that corresponding to the branch :
`.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.8072.3.2.10`

**Comment by garnier-quentin** [comment]
If the equipment doesn't have specific entreprise OID. Try to use the plugin os::linux::snmp::plugin.

**Comment by killianchmn-cpf** [comment]
## I will send you as much information as I have

you will find below the centreon version : 

<img width="150" alt="image" src="https://user-images.githubusercontent.com/100129738/155141330-3916ac88-6281-44d8-a322-d1c150fc9292.png">

here is the status information :

<img width="400" alt="image" src="https://user-images.githubusercontent.com/100129738/155141579-06b90ec1-2b93-4784-b03d-e01c1a5e5085.png">

you will find below the complete command on centreon :

<img width="300" alt="image" src="https://user-images.githubusercontent.com/100129738/155142509-8b087401-5846-4091-a7f9-aa7a5c07b8a8.png">
you can copy it right there

```
/usr/lib/centreon/plugins//centreon_ubiquiti_unifi_snmp.pl
--plugin=network::ubiquiti::unifi::snmp::plugin
--mode=cpu --hostname=192.168.1.4
--snmp-version='2c'
--snmp-community='FondationGsfComu'
--warning-user=''
--critical-user=''
--warning-nice=''
--critical-nice=''
--warning-system=''
--critical-system=''
--warning-idle=''
--critical-idle=''
--warning-wait=''
--critical-wait=''
--warning-kernel=''
--critical-kernel=''
--warning-interrupt=''
--critical-interrupt=''
--warning-softirq=''
--critical-softirq=''
--warning-steal=''
--critical-steal=''
--warning-guest=''
--critical-guest=''
--warning-guestnice=''
--critical-guestnice=''
--verbose
--use-new-perfdata
```
I also attach a screen of the device on the unifi interface of the device UNIFI-SW24-02

<img width="250" alt="image" src="https://user-images.githubusercontent.com/100129738/155143198-051e9403-0469-4f3c-b09f-127eeadab710.png">

I am also attaching an snmpwalk different from the previous one :
[snmpwalk 1..txt](https://github.com/centreon/centreon-plugins/files/8117049/snmpwalk.1.txt)

hoping that all this is element can help you to determine my problem.

**Comment by garnier-quentin** [comment]
The previous one has unifi entreprise OID. You should ask to your Ubiquiti support. It seems Ubiquiti have done some changes. Maybe it will only support linux standard OIDs.

**Comment by killianchmn-cpf** [comment]
OK, I'm closing this conversation, I see it on Ubiquiti side, I'll come back if I find it, thank you for your help.
