### ISSUE TITLE
local process

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#35]
can we get more information for processes plugin?

something like this:

```
count=348;10000;20000
runqueue=1
blocked=0
running=1
new=0.00
```

**Comment by florian-asche** [comment]
my request

**Comment by garnier-quentin** [comment]
That's informations from /proc/stat file. I can do it in the same command with something like that:
ps -e -o etime,pid,ppid,state,comm,args -w | tail -n +1 /proc/stat -

**Comment by florian-asche** [comment]
At the moment we have only the number of running proccesses. It whould be great, to see, how their status is. Please see http://search.cpan.org/dist/Sys-Statistics-Linux/lib/Sys/Statistics/Linux/ProcStats.pm

**Comment by garnier-quentin** [comment]
I have looked Florian ;) It look the /proc/stat file.

**Comment by florian-asche** [comment]
Can you add something similar to centreon-plugins? That whould be great. The information Number of running procs is ok, but if you can see how much of that is blocked, new or running in queue, then you can do real problemsolving.

**Comment by garnier-quentin** [comment]
I have added many informations: time, cpu, memory, disks IO
