### ISSUE TITLE
Add environment mode for [network::cisco::asa::plugin]

### ISSUE THREAD

**Issue by cioby23** [centreon/centreon-plugins#350]
Please add environment mode for Cisco ASA plugin in order to monitor temperature, fans, psu etc. If details are needed please let me know.

**Comment by garnier-quentin** [comment]
The environment mode from cisco standard plugin works ?

**Comment by cioby23** [comment]
I tried to use that on some Cisco ASA devices but it doesn't work. It return ok but no data is displayed
As an example I used the below line:
/opt/monitoring/plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --mode=environment --hostname 10.0.0.1 --snmp-username user1 --snmp-version 3 --authpassphrase passwd --authprotocol SHA --privpassphrase randompass --privprotocol AES     OK: All 0 components are ok []. |

**Comment by garnier-quentin** [comment]
So it's not useful to add it. Do you find hardware information for the asa in the mib ?

**Comment by cioby23** [comment]
If I run show environment on the ASA device it outputs this information
` sh environment

Cooling Fans:
-----------------------------------

   Chassis Fans:
   --------------------------------
   Cooling Fan 1: 6144 RPM - OK
   Cooling Fan 2: 5888 RPM - OK
   Cooling Fan 3: 5888 RPM - OK

Temperature:
-----------------------------------

   Processors:
   --------------------------------
   Processor 1: 51.0 C - OK

   Chassis:
   --------------------------------
   Ambient 1: 42.0 C - OK  (Chassis Back Temperature)
   Ambient 2: 35.0 C - OK  (Chassis Front Temperature)
   Ambient 3: 40.0 C - OK  (Chassis Back Left Temperature)

Voltage:
-----------------------------------
   Channel 1:  1.080 V - OK  (CPU Core)
   Channel 2: 12.126 V - OK  (12V)
   Channel 3:  5.033 V - OK  (5V)
   Channel 4:  3.264 V - OK  (3.3V)
   Channel 5:  1.504 V - OK  (DDR3 1.5V)
   Channel 6:  1.048 V - OK  (PCH 1.05V)`

Also I ran a snmpwalk against the ASA device and this is the sensor related information

`ENTITY-SENSOR-MIB::entPhySensorType.9 = INTEGER: rpm(10)
ENTITY-SENSOR-MIB::entPhySensorType.11 = INTEGER: rpm(10)
ENTITY-SENSOR-MIB::entPhySensorType.13 = INTEGER: rpm(10)
ENTITY-SENSOR-MIB::entPhySensorType.14 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorType.15 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorType.16 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorType.17 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorScale.9 = INTEGER: yocto(1)
ENTITY-SENSOR-MIB::entPhySensorScale.11 = INTEGER: yocto(1)
ENTITY-SENSOR-MIB::entPhySensorScale.13 = INTEGER: yocto(1)
ENTITY-SENSOR-MIB::entPhySensorScale.14 = INTEGER: yocto(1)
ENTITY-SENSOR-MIB::entPhySensorScale.15 = INTEGER: yocto(1)
ENTITY-SENSOR-MIB::entPhySensorScale.16 = INTEGER: yocto(1)
ENTITY-SENSOR-MIB::entPhySensorScale.17 = INTEGER: yocto(1)
ENTITY-SENSOR-MIB::entPhySensorPrecision.9 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.11 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.13 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.14 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.15 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.16 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.17 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorValue.9 = INTEGER: 5888
ENTITY-SENSOR-MIB::entPhySensorValue.11 = INTEGER: 6144
ENTITY-SENSOR-MIB::entPhySensorValue.13 = INTEGER: 5888
ENTITY-SENSOR-MIB::entPhySensorValue.14 = INTEGER: 51
ENTITY-SENSOR-MIB::entPhySensorValue.15 = INTEGER: 40
ENTITY-SENSOR-MIB::entPhySensorValue.16 = INTEGER: 42
ENTITY-SENSOR-MIB::entPhySensorValue.17 = INTEGER: 35
ENTITY-SENSOR-MIB::entPhySensorOperStatus.9 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.11 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.13 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.14 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.15 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.16 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.17 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.9 = STRING: Chassis Cooling Fan
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.11 = STRING: Chassis Cooling Fan
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.13 = STRING: Chassis Cooling Fan
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.14 = STRING: CPU Temperature Sensor
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.15 = STRING: Chassis Ambient Temperature Sensor
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.16 = STRING: Chassis Ambient Temperature Sensor
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.17 = STRING: Chassis Ambient Temperature Sensor
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.9 = Timeticks: (2044641381) 236 days, 15:33:33.81
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.11 = Timeticks: (2044641381) 236 days, 15:33:33.81
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.13 = Timeticks: (2044641381) 236 days, 15:33:33.81
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.14 = Timeticks: (2044641381) 236 days, 15:33:33.81
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.15 = Timeticks: (2044641381) 236 days, 15:33:33.81
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.16 = Timeticks: (2044641381) 236 days, 15:33:33.81
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.17 = Timeticks: (2044641382) 236 days, 15:33:33.82
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.9 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.11 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.13 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.14 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.15 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.16 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.17 = Gauge32: 0 milliseconds
`

**Comment by garnier-quentin** [comment]
I think it will work with the last version. Could you test it ?

**Comment by cioby23** [comment]
I have just downloaded the latest master and tried and it still doesn't work.
I used network::cisco::standard::snmp::plugin with mode environment to check the ASA device and the returned output was 
OK: All 0 components are ok []. |

**Comment by garnier-quentin** [comment]
Sorry for the late response. Indeed i need to add a snmp mode for that.

**Comment by cioby23** [comment]
OK. thanks.

**Comment by garnier-quentin** [comment]
Which version of asa do you use ? Could you give me a full snmpwalk ?

**Comment by cioby23** [comment]
I'm using version 9.4.(x) of ASA. 

`# snmpwalk -v3 -u user -A 'xxxxx' -l authPriv -a SHA -X 'yyyyy' -x AES 10.10.10.50 1.3.6.1.2.1.99
ENTITY-SENSOR-MIB::entPhySensorType.8 = INTEGER: rpm(10)
ENTITY-SENSOR-MIB::entPhySensorType.10 = INTEGER: rpm(10)
ENTITY-SENSOR-MIB::entPhySensorType.12 = INTEGER: rpm(10)
ENTITY-SENSOR-MIB::entPhySensorType.13 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorType.14 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorType.15 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorType.16 = INTEGER: celsius(8)
ENTITY-SENSOR-MIB::entPhySensorScale.8 = INTEGER: units(9)
ENTITY-SENSOR-MIB::entPhySensorScale.10 = INTEGER: units(9)
ENTITY-SENSOR-MIB::entPhySensorScale.12 = INTEGER: units(9)
ENTITY-SENSOR-MIB::entPhySensorScale.13 = INTEGER: units(9)
ENTITY-SENSOR-MIB::entPhySensorScale.14 = INTEGER: units(9)
ENTITY-SENSOR-MIB::entPhySensorScale.15 = INTEGER: units(9)
ENTITY-SENSOR-MIB::entPhySensorScale.16 = INTEGER: units(9)
ENTITY-SENSOR-MIB::entPhySensorPrecision.8 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.10 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.12 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.13 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.14 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.15 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorPrecision.16 = INTEGER: 0
ENTITY-SENSOR-MIB::entPhySensorValue.8 = INTEGER: 6144
ENTITY-SENSOR-MIB::entPhySensorValue.10 = INTEGER: 5888
ENTITY-SENSOR-MIB::entPhySensorValue.12 = INTEGER: 5888
ENTITY-SENSOR-MIB::entPhySensorValue.13 = INTEGER: 59
ENTITY-SENSOR-MIB::entPhySensorValue.14 = INTEGER: 43
ENTITY-SENSOR-MIB::entPhySensorValue.15 = INTEGER: 34
ENTITY-SENSOR-MIB::entPhySensorValue.16 = INTEGER: 40
ENTITY-SENSOR-MIB::entPhySensorOperStatus.8 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.10 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.12 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.13 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.14 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.15 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorOperStatus.16 = INTEGER: ok(1)
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.8 = STRING: rpm
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.10 = STRING: rpm
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.12 = STRING: rpm
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.13 = STRING: celsius
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.14 = STRING: celsius
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.15 = STRING: celsius
ENTITY-SENSOR-MIB::entPhySensorUnitsDisplay.16 = STRING: celsius
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.8 = Timeticks: (184327237) 21 days, 8:01:12.37
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.10 = Timeticks: (184327237) 21 days, 8:01:12.37
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.12 = Timeticks: (184327237) 21 days, 8:01:12.37
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.13 = Timeticks: (184327237) 21 days, 8:01:12.37
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.14 = Timeticks: (184327237) 21 days, 8:01:12.37
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.15 = Timeticks: (184327237) 21 days, 8:01:12.37
ENTITY-SENSOR-MIB::entPhySensorValueTimeStamp.16 = Timeticks: (184327237) 21 days, 8:01:12.37
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.8 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.10 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.12 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.13 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.14 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.15 = Gauge32: 0 milliseconds
ENTITY-SENSOR-MIB::entPhySensorValueUpdateRate.16 = Gauge32: 0 milliseconds`

**Comment by garnier-quentin** [comment]
Could you give me the result also for following OID: .1.3.6.1.2.1.47.1.1.1.1.2

**Comment by cioby23** [comment]
`ENTITY-MIB::entPhysicalDescr.1 = STRING: ASA 5525-X with SW, 8 GE Data, 1 GE Mgmt, AC
ENTITY-MIB::entPhysicalDescr.2 = STRING: ASA 5525 CPU
ENTITY-MIB::entPhysicalDescr.3 = STRING: ASA 5525 CPU
ENTITY-MIB::entPhysicalDescr.4 = STRING: ASA 5525 CPU
ENTITY-MIB::entPhysicalDescr.5 = STRING: ASA 5525 CPU
ENTITY-MIB::entPhysicalDescr.6 = STRING: ASA5525 Slot for Removable Drive 0
ENTITY-MIB::entPhysicalDescr.7 = STRING: Chassis Cooling Fan 1
ENTITY-MIB::entPhysicalDescr.8 = STRING: Chassis Cooling Fan 1 Sensor
ENTITY-MIB::entPhysicalDescr.9 = STRING: Chassis Cooling Fan 2
ENTITY-MIB::entPhysicalDescr.10 = STRING: Chassis Cooling Fan 2 Sensor
ENTITY-MIB::entPhysicalDescr.11 = STRING: Chassis Cooling Fan 3
ENTITY-MIB::entPhysicalDescr.12 = STRING: Chassis Cooling Fan 3 Sensor
ENTITY-MIB::entPhysicalDescr.13 = STRING: CPU Temperature 1 Sensor
ENTITY-MIB::entPhysicalDescr.14 = STRING: Chassis Ambient Temperature 1 Sensor
ENTITY-MIB::entPhysicalDescr.15 = STRING: Chassis Ambient Temperature 2 Sensor
ENTITY-MIB::entPhysicalDescr.16 = STRING: Chassis Ambient Temperature 3 Sensor
ENTITY-MIB::entPhysicalDescr.17 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.18 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.19 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.20 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.21 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.22 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.23 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.24 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.25 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.26 = STRING: 10/100/1000BaseT
ENTITY-MIB::entPhysicalDescr.27 = STRING: 10/100/1000BaseT`

**Comment by cioby23** [comment]
Any timeframe when this will be implemented ?
Thanks,

**Comment by garnier-quentin** [comment]
I can't give you a timeframe. I don't know
