### ISSUE TITLE
[network::nortel::standard::snmp::plugin] regression with switch vsp 4900 (v8.3)

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3507]
Hi,

The hardware plugin works well with switch VSP VOSS 4900 firmware version 8.1.6 but in version 8.3.1 only the led component works.

```
rpm -qa | grep nortel
centreon-pack-network-nortel-standard-snmp-3.2.1-1.el7.centos.noarch
```

8.1.6 : 
```
/usr/lib/centreon/plugins//centreon_nortel_standard_snmp.pl --plugin=network::nortel::standard::snmp::plugin --mode=hardware --hostname=x.x.x.x --snmp-version='3' --snmp-community='public' --snmp-username=xxx --authprotocol=SHA --authpassphrase='xxxxxxxx' --privprotocol=AES --privpassphrase='xxxxxxxx' --snmp-autoreduce --snmp-timeout='2' --component='.*' --verbose
OK: All 11 components are ok [9/9 led, 2/2 psus]. | 'count_led'=9;;;; 'count_psu'=2;;;;
Checking cards
Checking entities
Checking fans
Checking led
led 'SYS' status is 'off' [instance: 1.1].
led 'SPD' status is 'greenSteady' [instance: 1.2].
led 'STK' status is 'off' [instance: 1.3].
led 'BT' status is 'off' [instance: 1.4].
led 'P1' status is 'greenSteady' [instance: 1.5].
led 'P2' status is 'greenSteady' [instance: 1.6].
led 'F1' status is 'greenSteady' [instance: 1.7].
led 'F2' status is 'greenSteady' [instance: 1.8].
led 'F3' status is 'greenSteady' [instance: 1.9].
Checking power supplies
power supply '1' status is 'up' [instance: 1].
power supply '2' status is 'up' [instance: 2].
```

8.3.1 with --component='.*' : 
```
/usr/lib/centreon/plugins//centreon_nortel_standard_snmp.pl --plugin=network::nortel::standard::snmp::plugin --mode=hardware --hostname=x.x.x.x --snmp-version='3' --snmp-community='public' --snmp-username=xxx --authprotocol=SHA --authpassphrase='xxxxxxxx' --privprotocol=AES --privpassphrase='xxxxxxxx' --snmp-autoreduce --snmp-timeout='2' --component='.*' --verbose
UNKNOWN: SNMP Session : unable to create

```
8.3.1 with --component='led' : 
```
/usr/lib/centreon/plugins//centreon_nortel_standard_snmp.pl --plugin=network::nortel::standard::snmp::plugin --mode=hardware --hostname=x.x.x.x --snmp-version='3' --snmp-community='public' --snmp-username=xxx --authprotocol=SHA --authpassphrase='xxxxxxxx' --privprotocol=AES --privpassphrase='xxxxxxxx' --snmp-autoreduce --snmp-timeout='2' --component='led' --verbose
OK: All 9 components are ok [9/9 led]. | 'count_led'=9;;;;
Checking led
led 'SYS' status is 'greenSteady' [instance: 1.1].
led 'SPD' status is 'off' [instance: 1.2].
led 'STK' status is 'off' [instance: 1.3].
led 'BT' status is 'off' [instance: 1.4].
led 'P1' status is 'greenSteady' [instance: 1.5].
led 'P2' status is 'greenSteady' [instance: 1.6].
led 'F1' status is 'greenSteady' [instance: 1.7].
led 'F2' status is 'greenSteady' [instance: 1.8].
led 'F3' status is 'greenSteady' [instance: 1.9].

```
Mib for VSP 4900 (VOSS) : 
[VOSS4900.8.3.1.0_mib_sup.txt](https://github.com/centreon/centreon-plugins/files/8131071/VOSS4900.8.3.1.0_mib_sup.txt)

Best regards.

**Comment by garnier-quentin** [comment]
There is an issue on session create. That error is weird: ```UNKNOWN: SNMP Session : unable to create```. Have you set the right option ? Because it shouldn't work also (we should have the same error) even if you filter on the component led. 

However for components missing, i need a full snmpwalk of following branch: .1.3.6.1.4.1.2272
And i need mib files of your equipment version.

**Comment by gagzou** [comment]
The options are good because all the other probes are operational and component 'led' is ok.
I will send you the information by email.

**Comment by gagzou** [comment]
It works if we extend the timeout: --snmp-timeout='5' or add --snmp-retries='1' (by default I already add : --snmp-autoreduce --snmp-timeout='2').
Nortel mib is very big !
What is the best option : extend --snmp-timeout or add --snmp-retries ?

**Comment by gagzou** [comment]
I also have the fan that does not appear (components::fan) , script search .1.3.6.1.4.1.2272.1.4.7.1.1.2 (empty), i think the oid is in .1.3.6.1.4.1.2272.1.101.1.1.3 and .1.3.6.1.4.1.2272.1.101.1.1.4

**Comment by gagzou** [comment]
For temperature, script search .1.3.6.1.4.1.45.1.6.3.7.1.1.5, oid for VOSS switch is .1.3.6.1.4.1.2272.1.101.1.1.2.1.3 and .1.3.6.1.4.1.2272.1.101.1.1.6.1.5

**Comment by gagzou** [comment]
For card, script search .1.3.6.1.4.1.2272.1.4.9.1.1.6 , oid for VOSS switch is .1.3.6.1.4.1.2272.1.100.6.1.5 (.iso.org.dod.internet.private.enterprises.rapidCity.rcMgmt.rc2k.rc2kCardTable.rc2kCardEntry.rc2kCardFrontOperStatus)

**Comment by gagzou** [comment]
Hi,
For oid changes, should I open another ticket ?
Thanks.

**Comment by garnier-quentin** [comment]
No need to create a ticket. But i need MIBs files of your equipment and a full snmpwalk also.

**Comment by gagzou** [comment]
Ok, I send you the information by email.

**Comment by garnier-quentin** [comment]
Could you sent it back ? I don't find your email anymore (weird..)

**Comment by garnier-quentin** [comment]
You can test with last version: https://github.com/centreon/centreon-plugins/pull/3533

**Comment by gagzou** [comment]
Hi,
It works thanks 👍
![2022-03-11 09_27_07-Centreon - IT   Network Monitoring — Mozilla Firefox](https://user-images.githubusercontent.com/61595839/157830484-53fb4e21-cafb-4cab-8f75-19bcd9da2f7e.png)

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
