### ISSUE TITLE
Support for additional VMWare Metric

### ISSUE THREAD

**Issue by hecko** [centreon/centreon-plugins#351]
Wondering wheter CPU Ready metric could be implemented as a VMWare check

Docs: https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/cpu_counters.html
Reference label: CPU Ready

Sincerely, 
Marcel

**Comment by garnier-quentin** [comment]
Hi Marcel,

You have it with with the mode cpu for vms. You can filter perfdata to have only cpu_ready.
