### ISSUE TITLE
[apps::protocols::bgp::4::plugin]: create support for bgp IPv6

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3524]
could you create a plugin/mode to support BGP for IPv6?

**Comment by garnier-quentin** [comment]
Could you provide mib files and snmpwalk with bgp ipv6 informations ?

**Comment by garnier-quentin** [comment]
Do you have some news about it ?

**Comment by joschi99** [comment]
Seems that there is noi OID available for IPv6. Probably the only way could be using SSH: https://www.cisco.com/c/en/us/td/docs/ios/ipv6/command/reference/ipv6_book/ipv6_12.html

What do you think about it?

**Comment by garnier-quentin** [comment]
Why not. If you can provide a command example with your equipment.

**Comment by joschi99** [comment]
Hy Quentin,
I have got this informations for BGP 4/6 for Cisco ASR devices:
[Cisco ASR 9000_7_3_2_BGP4-MIB.zip](https://github.com/centreon/centreon-plugins/files/9234675/Cisco.ASR.9000_7_3_2_BGP4-MIB.zip)


**Peer Address Family Table—cbgpPeer2AddrFamilyTable**
This table is an augmentation of the former Cisco Peer Address Family Table, with flexible indexing to support both IPv4 and IPv6. This table contains supported address families. Only the following address families are supported: IPv4, VPNv4, IPv6, and VPNv6. Output is similar to the original MIB Object Identifier (OID): cbgpPeerAddrFamilyTable. The MIB object in this table is:
•	cbgpPeer2AddrFamilyName


**Cisco BGP Peer Table—cbgpPeer2Table**
This table is an augmentation of the former Cisco BGP Peer Table, with flexible indexing to support both IPv4 and IPv6. This table contains one entry per BGP peer about the connections with BGP peers. MIB objects in this table are:
•	cbgpPeer2Type
•	cbgpPeer2RemoteAddr
•	cbgpPeer2State
•	cbgpPeer2AdminStatus
•	cbgpPeer2NegotiatedVersion
•	cbgpPeer2LocalAddr
•	cbgpPeer2LocalPort
•	cbgpPeer2LocalAs
•	cbgpPeer2LocalIdentifier
•	cbgpPeer2RemotePort
•	cbgpPeer2RemoteAS
•	cbgpPeer2RemoteIdentifier
•	cbgpPeer2InUpdates
•	cbgpPeer2OutUpdates
•	cbgpPeer2InTotalMessages
•	cbgpPeer2OutTotalMessages
•	cbgpPeer2LastError
•	cbgpPeer2FsmEstablishedTransitions
•	cbgpPeer2FsmEstablishedTime
•	cbgpPeer2ConnectRetryInterval
•	cbgpPeer2HoldTime
•	cbgpPeer2KeepAlive
•	cbgpPeer2HoldTimeConfigured
•	cbgpPeer2KeepAliveConfigured
•	cbgpPeer2MinAsOriginationInterval
•	cbgpPeer2MinRouteAdvertisementInterval
•	cbgpPeer2InUpdateElapsedTime
•	cbgpPeer2LastErrorTxt
•	cbgpPeer2PrevState

**Comment by garnier-quentin** [comment]
Do you have the snmpwalk of the following tables ?

**Comment by joschi99** [comment]
Here you can find the walk for OID 1.3.6.1.4.1.9.9.187.1.2
[80.244.120.105.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/9235438/80.244.120.105.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
You can test with last git version: 
https://github.com/centreon/centreon-plugins/pull/3817

**Comment by joschi99** [comment]
Hi @garnier-quentin,
sorry for my late response. Hope you are fine.

I have done some test with the new mode and there is a issue -> Timeout (with BGP IPv6):
```
 ./centreon_plugins.pl --hostname=x.x.x.x --snmp-community='public' --snmp-version=2c --snmp-username= --authpassphrase= --authprotocol= --privpassphrase= --privprotocol= --plugin=network::cisco::standard::snmp::plugin --mode=bgp --debug
UNKNOWN: SNMP GET Request: Timeout
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.113.245 = 31219
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.113.247 = 10732
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.120.3 = 8132
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.120.104 = 179
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.120.105 = 15946
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.120.111 = 179
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.120.126 = 179
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.120.233 = 8764
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.1.4.80.244.120.236 = 1977
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.0.0.0.0.0.0.0.0.4 = 45489
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.0.0.0.0.0.0.0.0.5 = 20421
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.1.0.0.0.0.0.0.0.0 = 16933
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.1.0.0.0.0.0.0.0.1 = 49776
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.1.0.0.0.0.0.0.0.5 = 179
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.1.0.0.0.0.0.0.0.6 = 63759
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.2.0.0.0.0.0.0.0.0 = 179
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.11.0.0.0.0.0.0.0.9 = 10733
.1.3.6.1.4.1.9.9.187.1.2.5.1.10.2.16.42.2.6.112.240.0.0.11.0.0.0.0.0.0.0.11 = 31220

```

On a other Cisco seems working (only BGP IPv4):
_./centreon_plugins.pl --hostname=x.x.x.x --snmp-community='publicc' --snmp-version=2c --snmp-username= --authpassphrase= --authprotocol= --privpassphrase= --privprotocol= --plugin=network::cisco::standard::snmp::plugin --mode=bgp --critical-status='%{adminStatus} =~ /start/ && %{state} !~ /established/'                                                                                              OK: number of peers detected: 2 - All BGP peers are ok | 'bgp.peers.detected.count'=2;;;0; '10.235.0.254:179#bgp.peer.update.last.seconds'=356230s;;;0; '10.235.0.254:179#bgp.peer.prefixes.accepted.count'=0;;;0; '10.235.0.254:179#bgp.peer.prefixes.denied.count'=0;;;0; '10.235.0.255:179#bgp.peer.update.last.seconds'=356169s;;;0; '10.235.0.255:179#bgp.peer.prefixes.accepted.count'=0;;;0; '10.235.0.255:179#bgp.peer.prefixes.denied.count'=0;;;0;_

**Comment by garnier-quentin** [comment]
For the timeout, have you tried with option --snmp-autoreduce ?

**Comment by joschi99** [comment]
using option `--snmp-autoreduce=1` seem's working, thanks
