### ISSUE TITLE
[database::mysql::plugin] -mode=databases-size - Add free space option

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#353]
Hi,
Is it possible to add check of free space in autoextend database (ibdata) with treshold in % or B?
regards,

**Comment by Dodofox** [comment]
Hi,

I have the same question, i would like to know if it's possible to consider the max size and not the size. Because for now, i have critical alerte in some BD but i know there is lots of free space before reaching the max size, i just have to wait that sql add the new automatically extend to recover a OK in centreon...

Thanks,

**Comment by cmeschin** [comment]
Hi,
Any news about this?

**Comment by cgagnaire** [comment]
We’re working on it @Sims24 and I.
More global, not that simple.

**Comment by garnier-quentin** [comment]
I can't find a way to get ibdata free space directly.
But i can give you per table (free space and fragmentation percent) and total free
```
SELECT DATA_FREE/1024/1024 as DATA_FREE_MO, (DATA_FREE/1024/1024/ (DATA_LENGTH/1024/1024+INDEX_LENGTH/1024/1024)) as TAUX_FRAG FROM information_schema.tables WHERE table_type ='BASE TABLE'
```

It seems ok for you ?

**Comment by cmeschin** [comment]
Hi,
OK but in many cases for own products, we don't use innodb_file_per_table. but it may be useful in other cases.
For compatibility  with "innodb_file_per_table" option enabled / disabled, can you add an argument "--no-innodb-per-table"? If this argument is specified, you can only display the free global space in database, otherwise you can display free space and fragmentation per table like suggested previous.
Regards.

**Comment by garnier-quentin** [comment]
Could you test it ?
