### ISSUE TITLE
hardware::pdu::schleifenbauer::gtw::snmp::plugin new plugin to check schleifenbauer PDU's

### ISSUE THREAD

**Issue by cemir** [centreon/centreon-plugins#354]
Hi,

here is a new plugin for Schleifenbauer hardware,

currently it's able to talk with the gateway through SNMP to check a PDU for status, humidity and temperature

power metrics will be added later.

Regards

**Comment by garnier-quentin** [comment]
Here ? I don't see it :)
Could you give me the MIBs Files and a complete snmpwalk also:
snmpwalk -Cc -v2c -c public -ObentU localhost 1.3.6 > myagent.snmpwalk

Thanks!

**Comment by cemir** [comment]
Actually I wrote it but i can't manage how to pull request
I followed what's on this page https://documentation.centreon.com/docs/centreon-plugins/en/latest/developer/guide.html but I think it's outdated and was for the forge

**Comment by garnier-quentin** [comment]
You can attach your code if you cannot pull request. But i need mibs and snmpwalk ;)

**Comment by cemir** [comment]
Ok, I think i was able to create a pull request,

do you still need the snmpwalk ?

Regards,

**Comment by garnier-quentin** [comment]
The MIBs files and the walk yes!

**Comment by cemir** [comment]
command used was snmpwalk -Cc -v1 -c XXX 192.168.2.36 1.3.6 > myagent.snmpwalk

because snmp server supports only v1 and crash with -ObentU

[myagent.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/165321/myagent.snmpwalk.txt)
[SPGWMIB124.zip](https://github.com/centreon/centreon-plugins/files/165325/SPGWMIB124.zip)

**Comment by garnier-quentin** [comment]
Thanks

**Comment by cemir** [comment]
Hi, any news ? I created a pull request for this but no reaction on it ... Do I have to change/improve something ?

**Comment by garnier-quentin** [comment]
Sorry for the time. First thanks. But i can't accept the PR. For example the temperature:
* you check only the 'sensor2Value'. But it could be 'sensor1Value' or 'sensor3Value',... Moreover you use an argument for the device ID and you don't check if there are many 'channelIndex8'. 

You should get the 'serialNumber' in table 'identificationEntry' and look for all sensors in table 'pdumeasuresEntry'.  The type must be defined (I, T or H) and should be a name (but it can be the same. Maybe we should add the serial number also in perfdata). I don't know the value if type 'I' (dry contact) when there is a problem (not .00 ?)

Eventually, you should get only one check for sensors (you have humidity, temperature and contact at the same). If you give me the response the for dry contact value i could do the code.

**Comment by garnier-quentin** [comment]
Hi cemir,

Could you give me informations about it ?
