### ISSUE TITLE
network::stormshield::snmp::plugin 

### ISSUE THREAD

**Issue by Nibeck1309** [centreon/centreon-plugins#3546]
Hello,

I updated my stormshield SN510 to version 4.3.5
Since then, I can no longer monitor the vpn tunnels. they are in unknown condition.
is it possible to update the plugin?
I attach the mib files of this version
[mibs-4.3.5.zip](https://github.com/centreon/centreon-plugins/files/8238340/mibs-4.3.5.zip)

Thanks for your help

**Comment by garnier-quentin** [comment]
Could you provide snmpwalk of following branch ? .1.3.6.1.4.1.11256.1.1.1.1

**Comment by Nibeck1309** [comment]
Hello,
Thnaks for your reply.
File in attachment
[SN510_4.3.5_snmp_export.txt](https://github.com/centreon/centreon-plugins/files/8282414/SN510_4.3.5_snmp_export.txt)

**Comment by Nibeck1309** [comment]
hello,

someone for help me
I can't monitoring client vpn :(

**Comment by garnier-quentin** [comment]
The MIB has completely changed for Stormshield. Now there is the bytes in and bytes out. And the state is a string now: 'installed'.
I think we need to check the stormshield version:
```
.1.3.6.1.4.1.11256.1.0.2.0 = STRING: "3.9.2"
```

Could you provide the following OID for your Stormshield ? And could you ask to your stormshield support: when that table ```snsVPNSATable``` had been updated (os version) ?

**Comment by Nibeck1309** [comment]
My stormshield version is 4.3.5.

I ask stormshield support and I wait for answer

@garnier-quentin with the new mib in attach it is not possible to provide new plugin ?

**Comment by garnier-quentin** [comment]
I think i will update the mode to manage the 2 mibs. But i need the version changed.

**Comment by garnier-quentin** [comment]
I get the version. Could you provide the snmpwalk for the following branch ?
```
.1.3.6.1.4.1.11256.1.1
```

**Comment by Nibeck1309** [comment]
Hello,

See attach file for snmpwalk for the following branch .1.3.6.1.4.1.11256.1.1

[SN510_4.3.5_snmp_export2.txt](https://github.com/centreon/centreon-plugins/files/8512512/SN510_4.3.5_snmp_export2.txt)

**Comment by Nibeck1309** [comment]
Some News?

**Comment by garnier-quentin** [comment]
I will check it soon

**Comment by garnier-quentin** [comment]
The branch is missing. You could do a snmpwalk on the following branch:
.1.3.6.1.4.1.11256.1.1.2

**Comment by garnier-quentin** [comment]
Do you have something in the branch: .1.3.6.1.4.1.11256.1.1.2 ?

**Comment by garnier-quentin** [comment]
Could you test with that version ? https://github.com/centreon/centreon-plugins/archive/refs/heads/enh-stormshield-vpn.zip
I'm not sure if instance is increasing and if i need to group SA Entries by IKE phase.

**Comment by Nibeck1309** [comment]
Hello,

that works
great

Thanks and good job
