### ISSUE TITLE
[os::windows::snmp::plugin]/[os::linux::snmp::plugin] mode=storage - add disk space utilization % for metrics

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3548]
It could be useful to extend the performance datas on storages for

- % disk usage
- % disk free

At the moment only used (B) will be stored on metrics/grafics, for this on grafics is not possible to analyze the disk usage %, but only disk grow in B. Can you add this for Windows/Linux and maybe other OS?

**Comment by garnier-quentin** [comment]
You can use the following options:
```
--use-new-perfdata --extend-perfdata='storage.space.usage.bytes,storage.space.usage.percentage,percent()' --extend-perfdata='storage.space.usage.percentage,storage.space.free.percentage,invert()'
```
