### ISSUE TITLE
[apps::protocols::http::plugin] mode collection

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#3550]
Hello,

I have an XML File retreived with the mode collection wich contain table with "entry" section.
I use "selection_loop" in my json config file to parse what i need.

It works fine when this table contains more than a single "entry" but when there is only one "entry", i have this error message :
UNKNOWN: [selection_loop > 0 > functions > 0] cannot find year attribute

Is there a bug with "selection_loop" when there is only a single "entry" in a table or should i use "selection" instead of "selection_loop" to parse what i need ?

Thanks

**Comment by garnier-quentin** [comment]
Could you provide the json config and the --debug result ?

**Comment by ritouret** [comment]
Just sent by email.
Thank you Quentin.
