### ISSUE TITLE
Threshold problem with storage::emc::xtremio::restapi::plugin mode xenvs-cpu

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-plugins#3552]
Hi there,

We are using plugin storage::emc::xtremio::restapi::plugin and we see a threshold problem with xenvs-cpu mode. 

If we use : ./centreon_plugins.pl --plugin=storage::emc::xtremio::restapi::plugin --mode=xenvs-cpu --hostname=MYHOSTNAME --xtremio-username=MYUSER --xtremio-password=MYPASSWORD --warning=50 --critical=70

Even if one cpu is over 70%, the result is always WARNING. If i delete warning threshold, the result is CRITICAL (it's what I want).

If I use : ./centreon_plugins.pl --plugin=storage::emc::xtremio::restapi::plugin --mode=xenvs-cpu --hostname=MYHOSTNAME --xtremio-username=MYUSER --xtremio-password=MYPASSWORD --warning=@50:70 --critical=70

The result is CRITICAL (what I want). For the moment I use that, but I think it could be great to correct this little bug.

Thanks for your help.

**Comment by garnier-quentin** [comment]
i see the issue i fix it

**Comment by Sims24** [comment]
Hi @Hellnino18 

You can test with the last version. 

Thanks

**Comment by Hellnino18** [comment]
Thanks. Seeing your commit, I think the same bug is in ssdendurance.
