### ISSUE TITLE
UNKNOWN: Illegal division by zero at /usr/lib/centreon/plugins//centreon_linux_snmp.pl line 12759.

### ISSUE THREAD

**Issue by rasikmhetre** [centreon/centreon-plugins#3554]
i am trying to use this linux snmp pluging for my storage but i am getting the following error for few servers any help would be highly appreciated.

line number **12759**  =     $self->{result_values}->{prct_used} = $self->{result_values}->{used} * 100 / ($self->{result_values}->{total} - $reserved_value);

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk of the following branch ? .1.3.6.1.2.1.25
And the command you use exactly.

**Comment by Sims24** [comment]
hi @rasikmhetre just wondering, is this VM a cloud instance (EC2 for example)?

**Comment by rasikmhetre** [comment]
I have sent you an email @garnier-quentin

**Comment by rasikmhetre** [comment]
Hi @garnier-quentin did you manage to find something from the snmpwalk output?

**Comment by garnier-quentin** [comment]
It's fixed in last version: https://github.com/centreon/centreon-plugins/pull/3556

**Comment by rasikmhetre** [comment]
hi @garnier-quentin how do i implement this and which service should i reload to take these changes into effect?

note: i have changed storage.pm file same as your changes and reloaded the centreon configuraiton but it didn't work.

Sorry could you please help in this?

Do i need to recompile or something? if yes how do i do it?

**Comment by rasikmhetre** [comment]
hey thanks a lot!!!! @garnier-quentin it's working after merging our plugin's branch with master.
