### ISSUE TITLE
Exclude specific partition/partitions from disk-global check in centreon.

### ISSUE THREAD

**Issue by poomystery** [centreon/centreon-plugins#3557]
hi team,

need a help to exclude a specific partition from disk-global check in centreon. Is there any way to exclude a specific partition or group of partitions.

Below is my check command which is giving me all the partitions since i am giving storage=.*, can you please help me exclude a specific partitions?

/usr/lib/centreon/plugins//centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=10.10.10.18 --snmp-version='3' --snmp-community='xxxx' --snmp-username='xxxx' --authpassphrase='xxxx' --authprotocol='SHA' --privpassphrase='xxxx' --privprotocol='AES' --storage='.*' --name --regexp --display-transform-src='' --display-transform-dst='' --warning-usage='75' --critical-usage='85' --verbose --filter-perfdata='storage.space|used|free'

**Comment by Sims24** [comment]
Hi @poomystery 

You can check these articles on the watch: 

They will help you to understand how regexp filtering works with --storage and --name options: 

- https://www.dynatrace.com/support/help/dynatrace-api/environment-api/oneagent-on-host (Data matching part) 
- https://thewatch.centreon.com/product-how-to-21/how-to-play-with-regex-part-ii-413 (Multiple search) 

Thanks

**Comment by Sims24** [comment]
I updated my comment, wrong copy/paste for the first link 🌊

**Comment by poomystery** [comment]
This was awesome it helped, thanks @Sims24 :)

**Comment by Sims24** [comment]
Thanks for your feedback!
