### ISSUE TITLE
[apps::monitoring::netdata::restapi::plugin] load average monitoring

### ISSUE THREAD

**Issue by mullergg** [centreon/centreon-plugins#3558]
Hello !

I have a question about the load monitoring through netdata.

With the ssh check for the load the plugin calculate an average load base on the CPU number of the host.
For example:
```
[centreon-engine@xxxxx ~]$ /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=os::linux::local::plugin --mode=load --average --warning=4,3,2 --critical=6,5,4 --remote --hostname=xxxxxx  --ssh-option='-l=centreon'
OK: Load average: 0.31 [0.62/2 CPUs], 0.17 [0.35/2 CPUs], 0.28 [0.56/2 CPUs] | 'avg_load1'=0.31;0:4;0:6;0; 'avg_load5'=0.17;0:3;0:5;0; 'avg_load15'=0.28;0:2;0:4;0; 'load1'=0.62;0:8;0:12;0; 'load5'=0.35;0:6;0:10;0; 'load15'=0.56;0:4;0:8;0;
```

With the netdata plugin we lost the average possibility and it is difficult to set treshold in this case.
Is it possible to do something ?

**Comment by Sims24** [comment]
Hi @mullergg 

I don't think that we have the number of core in the Netdata API response when getting load chart. Not sure we want to make an extra call to get it. 

Can you share the result with --debug to confirm my statement above please?

**Comment by mullergg** [comment]
Hello !
Thanks, please find attach the debug file:
[load_netdata.txt](https://github.com/centreon/centreon-plugins/files/8339780/load_netdata.txt)

In the alarm status netdata take the number of core, see printscreen, I don't know if it helps:
![image](https://user-images.githubusercontent.com/60108297/159877145-57633010-fabf-4f27-ae4a-f556f4009bfe.png)

**Comment by Sims24** [comment]
Hi, 

Thanks for sharing this. Unfortunately we cannot offer a proper solution with the data Netdata sends. 

Maybe you could ask for an enhancement on their github (including the number of core in the query https://xxxxxxxxx:19999/api/v1/data?after=-300&group=average&chart=system.load&options=null2zero&points=1) 

If they do so, we'll update our plugin accordingly. 

Thanks!

**Comment by mullergg** [comment]
Ok thanks.

**Comment by garnier-quentin** [comment]
I think we can add an option to add the number of cores. The request is: 
```my $cpu_number = $options{custom}->get_info(filter_info => 'cores_total');```

**Comment by garnier-quentin** [comment]
You can test with option ```--average```
