### ISSUE TITLE
[Bug] Tomcat applications.pm fail when there is a ":" in PATH (windows java server)

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#356]
Hi,

When tomcat is installed on a windows host, there is a problem because of the ":" separator in the http request response content.

Workaround is "$webcontent =~ s,:(.):/,:$1/,; ".

We need to dig around to find a way to handle this.

COMMANDE
./centreon_plugins.pl --plugin=apps::tomcat::web::plugin
--mode=applications --hostname=XXXXX --proto=http --port=8080
--urlpath='/manager/list' --credentials --username=XXX --password=XXX
--name=".*" --regexp --verbose

AVANT MODIF
UNKNOWN: Context '/PilotageRH01:running' : 0 | 'status_/'=0.0;;;0;
'status_/PilotageRH01:running'=2.0;;;0; 'status_/docs'=0.0;;;0;
'status_/examples'=0.0;;;0; 'status_/host-manager'=0.0;;;0;
'status_/manager'=0.0;;;0;
Context '/' : running
Context '/PilotageRH01:running' : 0
Context '/docs' : running
Context '/examples' : running
Context '/host-manager' : running
Context '/manager' : running

APRES MODIF ligne 67 : $webcontent =~ s,:(.):/,:$1/,g;
OK: All Contexts are ok. | 'status_/'=0.0;;;0;
'status_/PilotageRH01'=0.0;;;0; 'status_/docs'=0.0;;;0;
'status_/examples'=0.0;;;0; 'status_/host-manager'=0.0;;;0;
'status_/manager'=0.0;;;0;
Context '/' : running
Context '/PilotageRH01' : running
Context '/docs' : running
Context '/examples' : running
Context '/host-manager' : running
Context '/manager' : running

Thanks,

**Comment by Sims24** [comment]
Hi, 

Confirmed, 

After printing out some infos could see that the point is that the last part of web content line is : 

$context:$state:$sessions:$contextpath where context path is D:/MyAPPs

PilotageRH01:running:0:D:/PilotageRH01

That explain the "/PilotageRH01:running" as contextpath.

To be more secure the regexp could be : 

$webcontent =~ s,([A-Z]):/,$1/,;

What do you think about that @garnier-quentin  ? 

Thanks ,

**Comment by garnier-quentin** [comment]
Could you test it with the following change ?
```
while ($webcontent =~ /^(.*):(.*):(.*):(.*)/mg) { 
```

**Comment by Sims24** [comment]
Sure I'll do it tomorrow and let you know.

**Comment by Sims24** [comment]
Hi @garnier-quentin 

That doesn't fix the problem.
