### ISSUE TITLE
is there an alternative to check host alive status if ping is disabled on server,

### ISSUE THREAD

**Issue by poomystery** [centreon/centreon-plugins#3560]
how will my centreon server know if the server is down?

**Comment by Sims24** [comment]
Hi @poomystery 

You can tune the check command on the host. You don't _have to_ use the base_host_alive command. 

You can create your own command or use a 'dummy' check to have an 'always-up' host. 

As this question isn't really plugin-related, I would recommend posting this on our community platform https://thewatch.centreon.com

**Comment by poomystery** [comment]
@Sims24 yes ive done that but when the host is down how will my centreon send host down nofications if it assumes host is up checking this dummy ping status.

![Ping_1](https://user-images.githubusercontent.com/101804076/159864418-b73f57ed-2d2f-4e94-b791-b04fa7a7a3ea.PNG)
![ping_2](https://user-images.githubusercontent.com/101804076/159864425-380d5a3a-2148-4542-81f3-3274dfa7e69c.PNG)
![Ping_3](https://user-images.githubusercontent.com/101804076/159864427-d6779ca4-e4ab-4292-acc0-aa5c4596116d.PNG)

**Comment by Sims24** [comment]
It will not. But you can for example test it with a TCP check on an open port instead of using the dummy always up command. This way you will get a down state when the specified port isn't reachable.
