### ISSUE TITLE
Enhancement Request for netscaler plugin: mode connections

### ISSUE THREAD

**Issue by Iralein** [centreon/centreon-plugins#3562]
The netscaler plugins (both, MPX and "normal") are providing a mode to check connections. This mode use the following OIDs:
tcpCurServerConn.0 = '.1.3.6.1.4.1.5951.4.1.1.46.1.0';
tcpCurClientConn.0 = '.1.3.6.1.4.1.5951.4.1.1.46.2.0';
tcpActiveServerConn.0 = '.1.3.6.1.4.1.5951.4.1.1.46.8.0';

Following the MIB File for NetScaler, it would be "better" to use the current server connections which are established or at least to provide a way to monitor this OID in addition to tcpCurServerConn:
tcpCurServerConnEstablished OBJECT-TYPE
SYNTAX Gauge32
MAX-ACCESS read-only
STATUS current
DESCRIPTION
"Current server connections in the Established state, which indicates that data transfer can occur between the Citrix ADC and the server."
::= { nsTcpStatsGroup 10 }

OID:
tcpCurServerConnEstablished.0='.1.3.6.1.4.1.5951.4.1.1.46.10.0';

**Comment by Sims24** [comment]
Hi @Iralein 
Thanks for the feedback, you can test it. 

I didn't find the MPX you mentioned, which mode it is exactly? 

SImon
