### ISSUE TITLE
[apps::vmware::connector::plugin] --mode=health-host: add filters

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3564]
Its should be nice to have the possibility on VMware healt-host to add filters for:
--component
--filter
--threshold-overload

Similar like on other hardware hosts

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
