### ISSUE TITLE
[storage::dell::powerstore::restapi::plugin] Handle acknownledge in Alert mode

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#3566]
On plugin [storage::dell::powerstore::restapi::plugin], some alert remains for ever on storage array, the only solution is to "acknownledge" them on powerstore side and then they should disapear on centreon side.

**Comment by garnier-quentin** [comment]
I use following requests: ```select=id,name,severity,state,resource_name,generated_timestamp```
I don't check alerts with ```state``` equals to ```CLEARED```. Could you tell me what is the state if it's acknownledge ? Maybe i should add it in status check.

**Comment by fixlair** [comment]
Thanks for your feedback.

The alert remains in `state` equals to `ACTIVE`. 

The acknowledge alert will stay for ever but maybe it's specific in our case (due to lack of redondancy of some connexions...)
Maybe it should be better (to handle more cases) to add flexibility by adding an option like  `--skip-acknowleged-alert` on this check ?

**Comment by garnier-quentin** [comment]
To add that option, you need to provide me the attribute with the acknowledgement information

**Comment by Sims24** [comment]
It's here https://github.com/centreon/centreon-plugins/blob/fbc1c2dac0a1af46c8efe664c40a282d653549a4/storage/dell/powerstore/restapi/mode/alerts.pm#L122

**Comment by garnier-quentin** [comment]
Ok. What is the value in is_acknowledged ? true ? 'yes' ?

**Comment by Sims24** [comment]
Yes kind sir

![image](https://user-images.githubusercontent.com/12429463/160603821-cd9f2df6-62e8-4fdf-b159-287cb7eec4de.png)

**Comment by garnier-quentin** [comment]
You can use following option:
```--warning-status='%{acknowledged} eq "no" and %{severity} =~ /minor/i' --critical-status='%{acknowledged} eq "no" and %{severity} =~ /major|critical/i'```
