### ISSUE TITLE
Monitoring Windows Mount Point

### ISSUE THREAD

**Issue by GMoral13** [centreon/centreon-plugins#3568]
Hi all,

I need to check mount points on a Windows machine. I have a disk C, and a few other disk that I need to check as one (check globally with total free space):
![image](https://user-images.githubusercontent.com/28733234/160562590-c8a98bc9-b921-4187-b4f8-ee057e95b25f.png)

Actually i am using this for all the disks on the server:
/usr/lib/centreon/plugins/centreon_windows_snmp.pl
	--plugin=os::windows::snmp::plugin
	--mode=storage
	--hostname=xxx
	--snmp-version='2c'
	--snmp-community='xxx' 
	--storage='.*'
	--name
	--regexp
	--display-transform-src='^(..).*'
	--display-transform-dst='$1'
	--warning-usage='92'
	--critical-usage='95'
	--verbose
	--filter-perfdata='storage.space|used|free'

Which gives me the following output:
Status information	
OK: All storages are ok
Extended status information	
Storage 'C:' Usage Total: 277.97 GB Used: 63.39 GB (22.81%) Free: 214.58 GB (77.19%)
Storage 'M:' Usage Total: 5.00 TB Used: 1.28 TB (25.69%) Free: 3.72 TB (74.31%)
Storage 'N:' Usage Total: 5.00 TB Used: 1.78 TB (35.58%) Free: 3.22 TB (64.42%)
Storage 'O:' Usage Total: 5.00 TB Used: 1.43 TB (28.64%) Free: 3.57 TB (71.36%)
Storage 'P:' Usage Total: 5.00 TB Used: 1.52 TB (30.42%) Free: 3.48 TB (69.58%)
Storage 'Q:' Usage Total: 5.00 TB Used: 1.36 TB (27.11%) Free: 3.64 TB (72.89%)
Storage 'R:' Usage Total: 5.00 TB Used: 1.18 TB (23.53%) Free: 3.82 TB (76.47%)
Storage 'S:' Usage Total: 5.00 TB Used: 1.13 TB (22.65%) Free: 3.87 TB (77.35%)
Storage 'T:' Usage Total: 5.00 TB Used: 1.18 TB (23.56%) Free: 3.82 TB (76.44%)
Storage 'U:' Usage Total: 5.00 TB Used: 1.36 TB (27.16%) Free: 3.64 TB (72.84%)
Storage 'V:' Usage Total: 5.00 TB Used: 1.08 TB (21.57%) Free: 3.92 TB (78.43%)
Storage 'E:' Usage Total: 100.01 GB Used: 31.50 GB (31.50%) Free: 68.51 GB (68.50%)
Storage 'W:' Usage Total: 5.00 TB Used: 1.15 TB (23.08%) Free: 3.85 TB (76.92%)
Storage 'X:' Usage Total: 5.00 TB Used: 1.33 TB (26.58%) Free: 3.67 TB (73.42%)
Storage 'Y:' Usage Total: 5.00 TB Used: 1.28 TB (25.64%) Free: 3.72 TB (74.36%)
Storage 'F:' Usage Total: 1.20 TB Used: 506.03 GB (41.18%) Free: 722.88 GB (58.82%)
Storage 'G:' Usage Total: 1.00 TB Used: 25.40 GB (2.48%) Free: 998.69 GB (97.52%)
Storage 'H:' Usage Total: 5.00 TB Used: 2.06 TB (41.12%) Free: 2.94 TB (58.88%)
Storage 'I:' Usage Total: 5.00 TB Used: 1.74 TB (34.76%) Free: 3.26 TB (65.24%)
Storage 'J:' Usage Total: 5.00 TB Used: 1.47 TB (29.36%) Free: 3.53 TB (70.64%)
Storage 'K:' Usage Total: 5.00 TB Used: 1.49 TB (29.87%) Free: 3.51 TB (70.13%)
Storage 'L:' Usage Total: 5.00 TB Used: 2.15 TB (42.91%) Free: 2.85 TB (57.09%)

Is there any way to do it? I can check separately the disk C (--storage='C:') but i don't know hot to do the other globlal check

Anyone can help? Thanks in advance

Regards.

**Comment by garnier-quentin** [comment]
I don't really understand your issue. You want to exclude the C: ?

**Comment by GMoral13** [comment]
I need to check all the other disks (E,F,G,H,I, etc.) as only one, i mean (E+F+G+H+I) adding the total space on summatory.

I can do 2 checks:
- The first one only with the C disk
- The second one with the summatory ot the other disks.

I don't know it fhis is possible (the summatory).

**Comment by garnier-quentin** [comment]
Have you tried my options ?
