### ISSUE TITLE
[network::paloalto::ssh::plugin] - missing mode for raid status

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3573]
if you have a PA with physical disks it should be nice to have a mode to monitor the raid/disk status using SSH

example with configured raid and failed disk
```
show system raid detail


Overall System Drives RAID status          Good
--------------------------------------------------------------------------------
Drive status
   Disk id Sys1                            Present     (Micron_5300_MTFD)
   Disk id Sys2                            Present     (Micron_5300_MTFD)
--------------------------------------------------------------------------------
Partition status

panlogs                                  clean
   Drive id Sys1                      active sync
   Drive id Sys2                      active sync

maint                                    clean
   Drive id Sys1                      active sync
   Drive id Sys2                      active sync

sysroot0                                 clean
   Drive id Sys1                      active sync
   Drive id Sys2                      active sync

sysroot1                                active
   Drive id Sys1                      active sync
   Drive id Sys2                      active sync

pancfg                                   clean
   Drive id Sys1                      active sync
   Drive id Sys2                      active sync

panrepo                                  clean
   Drive id Sys1                      active sync
   Drive id Sys2                      active sync

swap                                     clean
   Drive id Sys1                      active sync
   Drive id Sys2                      active sync


Logging Drives RAID status
--------------------------------------------------------------------------------
Disk Pair Log                         Available
   Status                       clean, degraded
   Disk id Log1                           Present
       model        : ST2000NX0253
       size         : 1907729 MB
       status       : active sync
   Disk id Log2                           Present
       model        : ST2000NX0253
       size         : 1907729 MB
       status       : failed
```

As you can see in this ecample Disk id Log2 has status failed and Disk Pair Log is Available, but degraded.

Further information you can find here: https://docs.paloaltonetworks.com/wildfire/9-0/wildfire-admin/use-the-wildfire-appliance-cli/wildfire-appliance-operational-mode-command-reference/show-system-raid.html

**Comment by garnier-quentin** [comment]
The linked page is not very detailed. It should be interesting to have all statuses availabled.
I don't really understand what is 'Logging Drives RAID status' ?  It's an other raid ?

**Comment by joschi99** [comment]
We have opend a request on Paloalto to have all necessary informations and I will update you asap. documentation is not clear and have no detailed informations.

**Comment by garnier-quentin** [comment]
Do you have some news @joschi99 ?

**Comment by joschi99** [comment]
After reviewing different informations probably it could be the simplest solution to monitor the system led status:

```
user@PA-5220-Primary(active)> show system state filter chassis.leds

chassis.leds: { 'alarm': Off, 'fans': Green, 'ha': Green, 'log': Off, 'ps0': Green, 'ps1': Green, 'service': Off, 'status': Green, 'temp': Green, }
```
As you can see depending on the hardware components this will return if we have:

- Alarms
- Fan status
- HA status
- Log status
- PS status ...

detailed information are available here: 

- https://docs.paloaltonetworks.com/hardware/pa-7000-hardware-reference/pa-7000-series-module-and-interface-card-information/pa-7000-series-switch-management-card-smc/interpreting-the-pa-7000-series-smc-leds
- https://docs.paloaltonetworks.com/hardware/pa-7000-hardware-reference/pa-7000-series-module-and-interface-card-information/pa-7000-series-network-processing-cards-npcs/pa-7000-100g-npc/interpret-the-pa-7000-100g-npc-leds

**Comment by garnier-quentin** [comment]
Ok i could add a mode.

**Comment by joschi99** [comment]
some news on this?
