### ISSUE TITLE
[os::aix::local] Add mode to check various aspect of file on AIX

### ISSUE THREAD

**Issue by davidcolin** [centreon/centreon-plugins#358]
Bonjour, 

Serait-il possible de créer un mode files-size pour AIX de la même manière que celui qui existe pour Linux? 

Merci par avance, 

Cdlt, 

D.COLIN

**Comment by Sims24** [comment]
Bonjour David, 

Tu pourras trouver le plugin que tu souhaites ici : 

https://github.com/Sims24/centreon-plugins/tree/aixlocalquick/os/aix/local/mode

Le mode filesize fonctionne correctement mais il faut que je finisse d'autres modes de cette branche pour faire la PR à Quentin. 

Dans l'attente tu peux le télécharger directement sur mon fork si c'est urgent. 

Merci, 

Simon

**Comment by davidcolin** [comment]
Bonjour SImon, 

Merci de ton aide. Je ne suis cependant pas tès familier de Github, 
pourrais-tu m'indiquer la marche à suivre pour le récupérer et le mettre 
en place? je suppose qu'il faut le mettre dans 
/usr/lib/nagios/plugins/centreon-plugins/os/aix/local/mode

Merci par avance





De :    Sims24 <notifications@github.com>
A :     centreon/centreon-plugins <centreon-plugins@noreply.github.com>, 
Cc :    davidcolin <davidcolin@macif.fr>
Date :  25/03/2016 12:03
Objet : Re: [centreon-plugins] [OS::AIX::LOCAL] Création d'un mode 
filesize (#358)



Bonjour David, 
Tu pourras trouver le plugin que tu souhaites ici : 
https://github.com/Sims24/centreon-plugins/tree/aixlocalquick/os/aix/local/mode
Le mode filesize fonctionne correctement mais il faut que je finisse 
d'autres modes de cette branche pour faire la PR à Quentin. 
Dans l'attente tu peux le télécharger directement sur mon fork si c'est 
urgent. 
Merci, 
Simon

**Comment by Sims24** [comment]
David, 

Oui c'est bien cela, tu dois ($USER1 étant le répertoire ou tu as ton centreon_plugins.pl) : 

copier le fichier souhaité dans $USER1$/os/aix/local/mode/filessize.pm
copier le plugin.pm dans $USER1$/os/aix/local/mode/

puis utiliser ce plugin comme si le fais avec les modes linux local. A la différence près que c'est la commande find qui est utilisé ici pour être plus "intéropérable", donc je t'invite à consulter le help pour le comportement que tu souhaites.

**Comment by davidcolin** [comment]
Simon,

OK, mais je n'arrive pas à DL le fichier... Quand je clique dessus, il me 
l'ouvre en fichier texte





De :    Sims24 <notifications@github.com>
A :     centreon/centreon-plugins <centreon-plugins@noreply.github.com>, 
Cc :    davidcolin <davidcolin@macif.fr>
Date :  25/03/2016 15:10
Objet : Re: [centreon-plugins] [OS::AIX::LOCAL] Création d'un mode 
filesize (#358)



David, 
Oui c'est bien cela, tu dois ($USER1 étant le répertoire ou tu as ton 
centreon_plugins.pl) : 
copier le fichier souhaité dans $USER1$/os/aix/local/mode/filessize.pm
copier le plugin.pm dans $USER1$/os/aix/local/mode/
puis utiliser ce plugin comme si le fais avec les modes linux local. A la 
différence près que c'est la commande find qui est utilisé ici pour être 
plus "intéropérable", donc je t'invite à consulter le help pour le 
comportement que tu souhaites.

**Comment by Sims24** [comment]
Bonne question, moi non plus :) 

Je t'ai mis un zip en PJ. 

Merci

**Comment by davidcolin** [comment]
j'ai pas le zip!





De :    Sims24 <notifications@github.com>
A :     centreon/centreon-plugins <centreon-plugins@noreply.github.com>, 
Cc :    davidcolin <davidcolin@macif.fr>
Date :  25/03/2016 15:29
Objet : Re: [centreon-plugins] [OS::AIX::LOCAL] Création d'un mode 
filesize (#358)



Bonne question, moi non plus :) 
Je t'ai mis un zip en PJ. 
Merci

**Comment by Sims24** [comment]
Tu peux utiliser wget ou curl, mais uniquement avec l'URL lorsque tu affiches le fichier en mode "raw". 

Oui désolé github n'aimait pas mon ZIP ..

**Comment by Ivory-59** [comment]
Hello,

est-ce qu'il existe un mode cpu à placer dans ce répertoire : /os/aix/local/mode ?
Et du coup une modification du plugin.pm

Merci par avance

**Comment by Sims24** [comment]
Hello @Ivory-59 , 

Non pas de mode cpu actuellement en mode local, mais tu peux ouvrir un autre ticket pour ça si tu le souhaites ;)

**Comment by Sims24** [comment]
files mode on aix allow to : 

Check count of files/dir
Check size of files/dir
Check owner of files/dir (owner, group, uid, gid)
Check modification time (modified time, accessed time, updated time) of files/dir

recursively or not and can use SSH

I close this case

**Comment by Sims24** [comment]
Hello @davidcolin ,

Le plugin compatible en local et/ou ssh est dispo. Tu peux m'envoyer un mail pour que je t'explique comment tester cela chez toi, 

Merci
