### ISSUE TITLE
Vxrail plugin pack (REST api)

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3580]
Hi,

There is currently no plugin pack for the vxrail hyperconverged solution (dell HCI solution).
A plugin on the vcenter allows to have the health status of the whole solution (vxrail manager/vc/esxi/idrac/etc...).
![2022_04_06_17_42_04_Window](https://user-images.githubusercontent.com/61595839/162017671-02d0f13c-d45b-4e39-8444-b64bac23cdc5.png)
The vcenter queries the appliance that manages the hyperconverged part (vxrail manager) via the GET method on a RESTful API (https://@vxrailmanager/rest/vxm/v1/system and https://@vxrailmanager/rest/vxm/ v1/cluster) with a basic authentication method
![2022_04_06_17_51_09_Postman](https://user-images.githubusercontent.com/61595839/162016261-86bdaaf3-18d9-4e55-b0b2-0d0795f3114a.png).

I send you the json files by email.

Thanks.

**Comment by garnier-quentin** [comment]
Could you provide the api documentation ?

**Comment by gagzou** [comment]
Hi,
Documentation : 
https://developer.dell.com/apis/5538/versions/7.0.350/docs/Introduction.md
Thanks.

**Comment by garnier-quentin** [comment]
You can test with last git version:
https://github.com/centreon/centreon-plugins/pull/3797

**Comment by gagzou** [comment]
Ok thanks !
:+1:
