### ISSUE TITLE
[database::postgres::plugin] no inheritance on database for vacuum

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3584]
Hi,

The command App-DB-Postgres-Vacuum contains : --database='$_SERVICEPOSTGRESDATABASE$' (instead of $_HOSTPOSTGRESDATABASE$).

Centreon 21.10.5
centreon-pack-applications-databases-postgresql-3.2.4-1.el7.centos.noarch

Best regards

**Comment by garnier-quentin** [comment]
It's not a centreon-plugins issue. We have done a choice between host and service macros. Maybe we could do manage the 2 cases with marcros in macros. But right now, you need to create your own command and services.
