### ISSUE TITLE
[hardware::pdu::cyberpower::snmp::plugin] --mode=outlets

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#3585]
Hello,

There is some missing information in this mode :
# /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl --plugin=hardware::pdu::cyberpower::snmp::plugin --mode=outlets --hostname=10.XX.XX.XX --snmp-community=*** --snmp-version=1 --snmp-timeout=45 --snmp-retries=1 --verbose
CRITICAL: Device 'PDU81005' outlet 'Outlet1 bank 1' state: 'off' [phase: seqPhase1ToNeutral] - outlet 'Outlet2 bank 1' state: 'off' [phase: seqPhase1ToNeutral] - outlet 'Outlet4 bank 1' state: 'off' [phase: seqPhase1ToNeutral] - outlet 'Outlet6 bank 1' state: 'off' [phase: seqPhase1ToNeutral] - outlet 'Outlet7 bank 1' state: 'off' [phase: seqPhase1ToNeutral]
checking device 'PDU81005'
    outlet 'Outlet1 bank 1' state: 'off' [phase: seqPhase1ToNeutral]
    outlet 'Outlet2 bank 1' state: 'off' [phase: seqPhase1ToNeutral]
    outlet 'Outlet3 bank 1' state: 'on' [phase: seqPhase1ToNeutral]
    outlet 'Outlet4 bank 1' state: 'off' [phase: seqPhase1ToNeutral]
    outlet 'Outlet5 bank 1' state: 'on' [phase: seqPhase1ToNeutral]
    outlet 'Outlet6 bank 1' state: 'off' [phase: seqPhase1ToNeutral]
    outlet 'Outlet7 bank 1' state: 'off' [phase: seqPhase1ToNeutral]
    outlet 'Outlet8 bank 1' state: 'on' [phase: seqPhase1ToNeutral]

No value for this oid :
      current => { oid => '.1.3.6.1.4.1.3808.1.1.3.3.5.1.1.7' }  # ePDUOutletStatusLoad

The snmpwalk for this oid :
CPS-MIB::ePDUOutletStatusLoad.1 = Gauge32: 0
CPS-MIB::ePDUOutletStatusLoad.2 = Gauge32: 0
CPS-MIB::ePDUOutletStatusLoad.3 = Gauge32: 0
CPS-MIB::ePDUOutletStatusLoad.4 = Gauge32: 0
CPS-MIB::ePDUOutletStatusLoad.5 = Gauge32: 0
CPS-MIB::ePDUOutletStatusLoad.6 = Gauge32: 0
CPS-MIB::ePDUOutletStatusLoad.7 = Gauge32: 0
CPS-MIB::ePDUOutletStatusLoad.8 = Gauge32: 0

No value for these oid :
    my $mapping_metered = {
        module  => { oid => '.1.3.6.1.4.1.3808.1.1.6.6.2.3.1.2' }, # ePDU2OutletMeteredInfoModuleIndex
        number  => { oid => '.1.3.6.1.4.1.3808.1.1.6.6.2.3.1.3' }, # ePDU2OutletMeteredInfoNumber
        name    => { oid => '.1.3.6.1.4.1.3808.1.1.6.6.2.3.1.4' }, # ePDU2OutletMeteredInfoName
        phase   => { oid => '.1.3.6.1.4.1.3808.1.1.6.6.2.3.1.5', map => $map_pdu2_phase }, # ePDU2OutletMeteredInfoLayout
        bank    => { oid => '.1.3.6.1.4.1.3808.1.1.6.6.2.3.1.7' }, # ePDU2OutletMeteredInfoBank
        current => { oid => '.1.3.6.1.4.1.3808.1.1.6.6.2.4.1.6' }  # ePDU2OutletMeteredStatusLoad
    };

The snmpwalk for a part of these oid :
CPS-MIB::ePDU2OutletMeteredInfoIndex.1 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoIndex.2 = INTEGER: 2
CPS-MIB::ePDU2OutletMeteredInfoIndex.3 = INTEGER: 3
CPS-MIB::ePDU2OutletMeteredInfoIndex.4 = INTEGER: 4
CPS-MIB::ePDU2OutletMeteredInfoIndex.5 = INTEGER: 5
CPS-MIB::ePDU2OutletMeteredInfoIndex.6 = INTEGER: 6
CPS-MIB::ePDU2OutletMeteredInfoIndex.7 = INTEGER: 7
CPS-MIB::ePDU2OutletMeteredInfoIndex.8 = INTEGER: 8
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.1 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.2 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.3 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.4 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.5 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.6 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.7 = INTEGER: 1
CPS-MIB::ePDU2OutletMeteredInfoModuleIndex.8 = INTEGER: 1
...
CPS-MIB::ePDU2OutletMeteredStatusLoad.1 = Gauge32: 0
CPS-MIB::ePDU2OutletMeteredStatusLoad.2 = Gauge32: 0
CPS-MIB::ePDU2OutletMeteredStatusLoad.3 = Gauge32: 0
CPS-MIB::ePDU2OutletMeteredStatusLoad.4 = Gauge32: 0
CPS-MIB::ePDU2OutletMeteredStatusLoad.5 = Gauge32: 0
CPS-MIB::ePDU2OutletMeteredStatusLoad.6 = Gauge32: 0
CPS-MIB::ePDU2OutletMeteredStatusLoad.7 = Gauge32: 0
CPS-MIB::ePDU2OutletMeteredStatusLoad.8 = Gauge32: 0

I can send you a full snmpwalk if needed.
Thanks.

**Comment by garnier-quentin** [comment]
Yes it will be easier

**Comment by ritouret** [comment]
Just sent by email.
Thank you Quentin.

**Comment by garnier-quentin** [comment]
The value is 0. That's why it's not displayed. If the current is over 0, it will be displayed.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3600
