### ISSUE TITLE
[network::cisco::meraki::cloudcontroller::restapi::plugin] - mode=devices  error 404

### ISSUE THREAD

**Issue by Spleeff** [centreon/centreon-plugins#3588]
Hello,

I'm using the latest version of Centreon plugins (updated today) and I'm trying to monitor Meraki APs.

Here is the command line used

`/usr/lib/centreon/plugins/centreon_cisco_meraki_restapi.pl --plugin='network::cisco::meraki::cloudcontroller::restapi::plugin' --mode='devices' --hostname='api.meraki.com' --api-token='XXXXXXXXXXXXXXXXXXXXXX' --port='443' --proto='https' --filter-device-name='FRPAR-AP01' --critical-status='% {status} =~ /alerting/i' --critical-link-status='%{link_status} =~ /failed/i' --verbose --debug`

The response is: `{"errors":["API access is disabled for this organization. To make API requests for this organization you must first enable API access."]}`

Unfortunately API access is really enabled ..

Can you help me ?

Thank you

**Comment by garnier-quentin** [comment]
Are you sure ? It's maybe an old organization ? We check all organizations. I will do a patch to filter organizations after the listings.

**Comment by Spleeff** [comment]
Oh I didn't think my account had access to multiple organizations. If it's possible to filter by organization that should fix the problem. Otherwise, I would create a dedicated account.
________________________________
De : qgarnier ***@***.***>
Envoyé : Monday, April 11, 2022 7:01:26 PM
À : centreon/centreon-plugins ***@***.***>
Cc : Leruth, Stephan ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] [network::cisco::meraki::cloudcontroller::restapi::plugin] - mode=devices error 404 (Issue #3588)

ATTENTION: This is an External message. Be cautious.


Are you sure ? It's maybe an old organization ? We check all organizations. I will do a patch to filter organizations after the listings.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3591

It should work with option ```--ignore-orgs-api-disabled```
