### ISSUE TITLE
network::juniper::trapeze::snmp::plugin hardware enhancement

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#359]
Hi,

Can you please add hardware mode to network::juniper::trapeze::snmp::plugin?

**Comment by garnier-quentin** [comment]
Hi Kadrika,

I could but trapeze doesn't give information about the hardware (in snmp).

**Comment by kadrika** [comment]
Ok, I tried to find it myself also, but failed. But thanks for the confirmation!
