### ISSUE TITLE
[apps::vmware::connector::plugin] Exclude unused NICs

### ISSUE THREAD

**Issue by Fianso35** [centreon/centreon-plugins#3592]
Hi,

Some of my hosts have several unused NIC. They appears as CRITICAL: 
physical interface 'vmnic4' status down - physical interface 'vmnic5' status down

Is there a way to exclude them ?
I already tried : --critical-link-status='%{display} !~ /vmnic[01]/ and %{link_status} !~ /up/'
and it didn't work.

Thank you

**Comment by garnier-quentin** [comment]
I exclude interfaces down: vmnic4 and vmnic5 (in your output example). In your option, you exclude interfaces: vmnic0 and vmnic1.

**Comment by Fianso35** [comment]
Oh ok i see now, but i still have this message with your syntaxe :
argument /vmnic[45]/ alone at /usr/lib/centreon/plugins//centreon_vmware_connector_client.pl line 10327.

**Comment by garnier-quentin** [comment]
Could you provide the message ?

**Comment by garnier-quentin** [comment]
Could you provide your full commandline ?

**Comment by Fianso35** [comment]
Yes i can :
/usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=net-host --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='ESXI3'  --esx-hostname='LAB-ESXI-3.localdomain' --nic-name='.*' --unknown-status='%{status} !~ /^connected$/i' --warning-status='' --critical-status='' --unknown-link-status='' --warning-link-status='' --critical-link-status='%{link_status} !~ /up/' --warning-link-traffic-in='80' --critical-link-traffic-in='90' --warning-link-traffic-out='80' --critical-link-traffic-out='90' --warning-link-dropped-in='' --critical-link-dropped-in='' --warning-link-dropped-out='' --critical-link-dropped-out='' --warning-host-traffic-in='' --critical-host-traffic-in='' --warning-host-traffic-out='' --critical-host-traffic-out='' --verbose

**Comment by garnier-quentin** [comment]
I don't think it's the commandline used. There is no 'vmnic' string.

**Comment by Fianso35** [comment]
Maybe you're talking about this : 
CRITICAL: Host 'LAB-ESXI-3.localdomain' : physical interface 'vmnic4' status down - physical interface 'vmnic5' status down

checking host 'LAB-ESXI-3.localdomain'

status connected

host traffic in: 139.26 Kb/s, host traffic out: 8.19 Kb/s

physical interface 'vmnic0' status up, traffic in: 139.26Kb/s (0.01 %), traffic out: 8.19Kb/s (0.00 %), packets in dropped: 0.00 % (0/341 packets), packets out dropped: 0.00 % (0/83 packets)

physical interface 'vmnic1' status up, traffic in: 0.00b/s (0.00 %), traffic out: 0.00b/s (0.00 %), packets in dropped: 0.00 % (0/11 packets), packets out dropped: 0.00 % (0/0 packets)

physical interface 'vmnic2' status up, traffic in: 0.00b/s (0.00 %), traffic out: 0.00b/s (0.00 %), packets in dropped: 0.00 % (0/0 packets), packets out dropped: 0.00 % (0/0 packets)

physical interface 'vmnic3' status up, traffic in: 0.00b/s (0.00 %), traffic out: 0.00b/s (0.00 %), packets in dropped: 0.00 % (0/0 packets), packets out dropped: 0.00 % (0/0 packets)

physical interface 'vmnic4' status down

physical interface 'vmnic5' status down

physical interface 'vmnic6' status up, traffic in: 0.00b/s (0.00 %), traffic out: 0.00b/s (0.00 %), packets in dropped: 0.00 % (0/0 packets), packets out dropped: 0.00 % (0/0 packets)

physical interface 'vmnic7' status up, traffic in: 0.00b/s (0.00 %), traffic out: 0.00b/s (0.00 %), packets in dropped: 0.00 % (0/0 packets), packets out dropped: 0.00 % (0/0 packets)

vswitch 'VSwitch_ISCSI1' traffic in: 0.00 b/s, traffic out: 0.00 b/s

vswitch 'VSwitch_ISCSI2' traffic in: 0.00 b/s, traffic out: 0.00 b/s

vswitch 'VSwitch_Synchro1' traffic in: 0.00 b/s, traffic out: 0.00 b/s

vswitch 'VSwitch_Synchro2' traffic in: 0.00 b/s, traffic out: 0.00 b/s

vswitch 'vSwitch-vMotion' traffic in: 0.00 b/s, traffic out: 0.00 b/s

vswitch 'vSwitch0' traffic in: 139.26 Kb/s, traffic out: 8.19 Kb/s

**Comment by garnier-quentin** [comment]
Could you provide the command line when you have the following error: ``` argument /vmnic[45]/ alone at /usr/lib/centreon/plugins//centreon_vmware_connector_client.pl line 10327.```

**Comment by Fianso35** [comment]
When i have this error, i don't have more informations, only the following error :
argument /vmnic[45]/ alone at /usr/lib/centreon/plugins//centreon_vmware_connector_client.pl line 10327.
![image](https://user-images.githubusercontent.com/103495991/162939101-764be167-42c5-4bb2-8bd9-d095b771193a.png)

**Comment by garnier-quentin** [comment]
It's the error: ```--critical-link-status='--critical-link-status='%{display} !~ /vmnic[45]/ and %{link_status} !~ /up/''```

**Comment by Fianso35** [comment]
Ok thank you ! It works now !!

**Comment by garnier-quentin** [comment]
You're welcome!
