### ISSUE TITLE
[database::oracle::plugin] check login error

### ISSUE THREAD

**Issue by Maekess** [centreon/centreon-plugins#3593]
Hi,

I want to check availability of database by login in with a non existing username and checking if "ORA-01017: invalid username/password" is the answer. That error is considered OK, but any other error are to be assigned as CRITICAL.

The method was available on an old nagios script but it's using TNSNAMES.ora

I recall --mode=collection could be a good method, but have no idea how to set it up.
Any idea on how to set such thing with centreon-plugins ?

Thanks,

**Comment by garnier-quentin** [comment]
I don't think we can do that with the collection mode. Maybe i can think how to add it.

**Comment by garnier-quentin** [comment]
You can test with the following config: https://github.com/centreon/centreon-plugins/pull/3639
