### ISSUE TITLE
[apps::microsoft::mscs::local::plugin] UNKNOWN: Unsafe code evaluation

### ISSUE THREAD

**Issue by PatPil** [centreon/centreon-plugins#3595]
Hello,

agent version windows Centreon-NSClient-0.5.2.41-20211102-x64, centreon V20.10.5 

Undefined subroutine &main::is_preferred_node called at (eval 41) line 1.

Thanks

**Comment by garnier-quentin** [comment]
Please provide your command line

**Comment by PatPil** [comment]
/usr/lib64/nagios/plugins/check_centreon_nrpe -H xxxx -p 5666 -t 55 -u -m 8192 -c check_centreon_plugins -a 'apps::microsoft::mscs::local::plugin' 'resourcegroup-status' ' --filter-name="" --unknown-status="%{state} =~ /unknown/" --warning-status="not is_preferred_node()" --critical-status="%{state} =~ /failed|offline/" --verbose'

**Comment by garnier-quentin** [comment]
Please use following argument: ```--warning-status="%{is_preferred_node} == 0"```

**Comment by PatPil** [comment]
we are in EMS license and it is inherited from a plugin pack. the plugin should be modified

**Comment by garnier-quentin** [comment]
Indeed. we are going to fix it!
