### ISSUE TITLE
Using Avaya IP Office MIB on Centreon

### ISSUE THREAD

**Issue by uc33260** [centreon/centreon-plugins#3598]
Hi team,

I'm a voip engineer, and looking to understand how can i use MIB provided by a voip constructor (Avaya) for a specific product (IP office).

I can only monitor basic services (disk, memory, cpu, uptime, network bandwith usage, ping, swap).

My goal is to monitor the services running on the IPBX. many services are running under Apache-tomcat.

Other things to monitor, is for example, licenses usage, alarms sip, etc.

It will be great to work together (voip skills in my side / monitoring skills in you side) and we can develop a new plugin "Avaya IP office" and share it with all the Centreon community.

I'm available to work on that, I have already a homelab running (Centreon + Avaya IP office).

PS: Find attached below, the Avaya IP office MIBs

[avaya_ipoffice_snmp_mibs.zip](https://github.com/centreon/centreon-plugins/files/8495624/avaya_ipoffice_snmp_mibs.zip)

Thank you

Issam BATTI

[issam_batti@hotmail.fr](mailto:issam_batti@hotmail.fr)

Best regards

**Comment by Sims24** [comment]
Hi, 

I have looked at the Mibs, it doesn't seems to contain the service status nor licences information.

Do you have an Avaya active support to ask them? Maybe there's an API. 

You can still upload mibs and configure SNMP Traps but I'm afraid we won't be able to achieve what you expect from these MIB files.

**Comment by uc33260** [comment]
Hi,

Yes I have an Avaya active support, I opened a service request and waiting for response.

I tried to upload snmp MIBs, but when I make an snmpwalk from to the IPBX, I got an error:

TCP-MIB::tcpConnState.0.0.0.0.1300.0.0.0.0.0 = INTEGER: listen(2)
Error: OID not increasing: TCP-MIB::tcpConnState.10.200.10.1.443.10.200.10.50.50837
 >= TCP-MIB::tcpConnState.0.0.0.0.1300.0.0.0.0.0

On a voip forum (https://www.tek-tips.com/viewthread.cfm?qid=1774859) , someone suggest to me to use a trap on this format:

SNMP OID.Specific Trap.Event Code.Event Sub-Code

![Avaya_licenses_alarm](https://user-images.githubusercontent.com/83720227/164447846-0c1c657f-f56c-4d7a-be02-d7a7978bde84.png)

But, I don't know how to cpecify the traps arguments, etc on Centreon.

Regards
