### ISSUE TITLE
wrong calculation of Used RAM on FreeBSD

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon-plugins#360]
Hi

The amount of RAM used returned by Memory mode of the os::freebsd::snmp plugin seems to be wrong.

Here are the values returned by the plugin :
Ram used (-buffers/cache) 2.80 GB (86.89%), Buffer: 112.19 MB, Cached: 0.00 B, Shared: 225.45 MB

But the values on the host (with 'top' command) are :
Mem: 850M Active, 1741M Inact, 354M Wired, 112M Buf, 291M Free

According to this article http://unix.stackexchange.com/questions/134862/what-do-the-different-memory-counters-in-freebsd-mean, it seems that the correct value for FreeBSD would be :  Used RAM = Active + Wired

Is that correct ?

Regards

Norbert

**Comment by garnier-quentin** [comment]
Hi,

Totally agree. But the snmp module don't give me all the information i want (the wired for example). So i have done the best i can ;)

What i write in the code:
# mem_available = total - mem_inactive - mem_cache - mem_free
# Maybe it's will be better to have have total with: total = 'active' + 'wired' + 'cache' + 'inactive' + 'free'
# But i can't have that with values from bsnmpd-ucd
