### ISSUE TITLE
[network::fortinet::fortigate::snmp::plugin] mode=signatures: negative values returned

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3603]
We have different cases were this mode returns an error with negative values. For example this actual case:

today **19.04 10:02am**
CRITICAL: AV Signature last refresh is: '-13h 22m 20s' - AV Extended Signature last refresh is: '-13h 22m 20s'

snmpwalk -v2c -cxxx x.x.x.x .1.3.6.1.4.1.12356.101.4.2
SNMPv2-SMI::enterprises.12356.101.4.2.1.0 = STRING: "90.01532(2022-04-19 02:26)"
SNMPv2-SMI::enterprises.12356.101.4.2.2.0 = STRING: "6.00741(2015-12-01 02:30)"
SNMPv2-SMI::enterprises.12356.101.4.2.3.0 = STRING: "90.01532(2022-04-19 02:26)"
SNMPv2-SMI::enterprises.12356.101.4.2.4.0 = STRING: "20.00299(2022-04-15 01:14)"

today **19.04 10:59am** returned to OK
OK: AV Signature last refresh is: '10h 33m 40s' - AV Extended Signature last refresh is: '10h 33m 40s'

**Comment by joschi99** [comment]
I think I have found the problem. Seems that the Fortigate FW has wrong timestamps on this for a certain time.

snmpwalk on 19.03 at 10.10am
```
SNMPv2-SMI::enterprises.12356.101.4.2.1.0 = STRING: "90.01527(2022-04-19 23:26)"
SNMPv2-SMI::enterprises.12356.101.4.2.2.0 = STRING: "6.00741(2015-12-01 02:30)"
SNMPv2-SMI::enterprises.12356.101.4.2.3.0 = STRING: "90.01527(2022-04-19 23:26)"
SNMPv2-SMI::enterprises.12356.101.4.2.4.0 = STRING: "20.00299(2022-04-15 01:14)"
```

As you can see there are some timestamps at 23pm (future). We need to check this with fortigate. I will update you asap.

**Comment by garnier-quentin** [comment]
I close it. You can comment if you have a response of fortinet support. it can be very useful
