### ISSUE TITLE
[apps::vmware::connector::plugin] --mode=cpu-cluster: UNKNOWN: Cannot get value for counters

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3607]
```
centreon_plugins.pl --connector-hostname=127.0.0.1 --connector-port=5700 --container=XXX --plugin=apps::vmware::connector::plugin --custommode=connector --mode=cpu-cluster --debug
UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...)
{"identity":"client-81555e8caba4438a8e94e72a42d7efa1","data":{},"short_message":"Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...)","extra_message":"","vmware_connector_version":"3.2.3","code":-1}
```

```
centreon_plugins.pl --connector-hostname=127.0.0.1 --connector-port=5700 --container=XXX--plugin=apps::vmware::connector::plugin --custommode=connector --mode=cpu-cluster --cluster-name='YYY' --debug
UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...)
{"identity":"client-59696979513f4d1cbdc12815a5d3af5b","data":{},"short_message":"Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...)","extra_message":"","vmware_connector_version":"3.2.3","code":-1}
```

Same problem also with Connector version 3.2.2. Hosts are correctly synced with NTP.

**Comment by garnier-quentin** [comment]
It can be synced but it can take time to get datas. Try the time-shift option (and look your graph on your vcenter. To see if you have values for the metric).

**Comment by joschi99** [comment]
Using time-shift option seem's working, but minimum working time-shift value is 1500. Is this normal/correct?

**Comment by garnier-quentin** [comment]
It means that an issue with your vcenter and your esx (i think)

**Comment by joschi99** [comment]
I'm not sure on this, we have this problem on different vCenters

**Comment by garnier-quentin** [comment]
Check the graph on your vcenter and it can provide you information. If you don't have values, connector cannot get it.

**Comment by garnier-quentin** [comment]
Do you have some news ?

**Comment by joschi99** [comment]
I have done some tests and it seem's that we have the same issue on different vCenter's and the check will only work if you set time-shift value. Seem's a general problem.

**Comment by gagzou** [comment]
Hi,
I have the same problem:

UNKNOWN: Cannot get value for counters (Maybe, object(s) cannot be reached: disconnected, not running, time not synced (see time-host mode),...)

I also correct by adding: --time-shift= (between 1300 and 1700 depending on the clusters) : 

OK: Cluster 'CLUSTER PREPROD' : cpu total average: 11.56 %, 34899.00 MHz | 'CLUSTER PREPROD#cluster.cpu.utilization.percentage'=11.56%;;;0;100 'CLUSTER PREPROD#cluster.cpu.utilization.mhz'=34899.00MHz;;;0;
checking cluster 'CLUSTER PREPROD'
    cpu total average: 11.56 %, 34899.00 MHz

**Comment by garnier-quentin** [comment]
Could you take a look to your graph on your vcenter ? To see if there are points (or there is a delay).

**Comment by gagzou** [comment]
The graphs are complete and without delays on the vcenter.

**Comment by joschi99** [comment]
Infact we have checked on different vCenters and graphs are completed and without delays. So on vCenter everything looks fine and normal.

**Comment by joschi99** [comment]
Any news about this issue?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old, however it is currently being evaluated on an internal customer case which could be very similar so I will keep you informed of our conclusions and proposed solution.
Thank you for your understanding.

**Comment by joschi99** [comment]
We have found the problem, was related to a wrong version of vmware perl sdk.
