### ISSUE TITLE
database::mysql mode replication-master-slave

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#361]
Hello,

The mode replication-master-slave of the plugin database::mysql display a status OK even when we interrogate 2 servers which are not master/slave each other. (MasterX is the master of SlaveX & MasterY is the master of SlaveY).

./centreon_plugins.pl --plugin=database::mysql::plugin --host=MasterX --username='centreon-repl' --password='xx' --mode=replication-master-slave --multiple --host=SlaveY --username='centreon-repl' --password='xx' --verbose
OK: No problems. Replication is ok. | 'slave_latency'=0s;;;0;
Connection Status 'mysql:host=10.30.2.185' [OK]
Connection Status 'mysql:host=10.30.2.246' [OK]
Slave Thread Status [OK]
Position Status [OK]

Is it normal ? I am using the mdoe version 1.0

Thank you very much

**Comment by garnier-quentin** [comment]
Ref 45bd68a0f05aa8a266d3ad48dd2e317f92cd98dc
