### ISSUE TITLE
Disk-Global template skipping partitions

### ISSUE THREAD

**Issue by poomystery** [centreon/centreon-plugins#3615]
Hello Team,

my global disk partition template doesnt show all partitions even after using .*

![centreon output for server updated](https://user-images.githubusercontent.com/101804076/164434351-d50c7142-816a-48c6-84ec-48ab281ad1b5.PNG)

![server output](https://user-images.githubusercontent.com/101804076/164422054-a832630a-51b7-4afe-9a32-abc96cab0bef.PNG)

**Comment by garnier-quentin** [comment]
By default, the storage type is: ```--filter-storage-type='^(hrStorageFixedDisk|hrStorageNetworkDisk|hrFSBerkeleyFFS)$'```
I think you should change that option. Could you provide snmpwalk for the following branch:
.1.3.6.1.2.1.25.2.3.1.2 
.1.3.6.1.2.1.25.2.3.1.3

**Comment by poomystery** [comment]
@garnier-quentin 
![walk](https://user-images.githubusercontent.com/101804076/164435274-1dd678e6-3741-4f61-8af2-b3759db18b60.PNG)

**Comment by garnier-quentin** [comment]
It's a net-snmp issue maybe. Partitions are not present.

**Comment by poomystery** [comment]
what do i do please help :(

**Comment by garnier-quentin** [comment]
Maybe you can try the mode ```disk-usage```
You need to add the following configuration in net-snmp: 
```
includeAllDisks 10%
```

**Comment by poomystery** [comment]
@garnier-quentin how can i use disk-usage?  will i just have to add includeAllDisks 10% in snmpd.conf

**Comment by poomystery** [comment]
@pkriko @garnier-quentin Need your guidence

[snmpwalk_109.txt](https://github.com/centreon/centreon-plugins/files/8540517/snmpwalk_109.txt)

https://thewatch.centreon.com/platform-7/why-is-my-global-disk-template-skipping-partitions-506?postid=1638#post1638

how can i add add --filter-storage-type=’.*’ in first time?

please find snmpwalk -v 2c -c your_community -ObentU -Cc -On x.x.x.x .1.3.6.1.2.1.25  output attached

**Comment by garnier-quentin** [comment]
Try to execute the plugin manually. You only need to set:
```
perl centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=disk-usage --hostname=10.30.2.2
```

**Comment by poomystery** [comment]
Hello guys i am able to fetch the mount points from the destination server but not been able to fetch disk usage using centreon_plugin.pl check command. Pasting the check command's output

![image](https://user-images.githubusercontent.com/101804076/164760234-b1407967-ec00-411d-9ddf-599ba2652838.png)



![image](https://user-images.githubusercontent.com/101804076/164759777-0f2af4fd-1109-4db5-a150-f88a20f6b49f.png)

**Comment by poomystery** [comment]
Hi @garnier-quentin @pkriko  i am able to see all the mount points using this branch .1.3.6.1.2.1.25.3.8.1.2 but how do i implement this to centreon to see all mount points

![image](https://user-images.githubusercontent.com/101804076/165032399-7f6118ab-fe17-4966-87e9-c71cbd411d53.png)

**Comment by garnier-quentin** [comment]
The mode ```storage``` cannot be used. There are no snmp size/used information for the mountpoint ```/finreports``` 
You can display the mountpoint with option: ```--oid-display=hrFSMountPoint```

Have you tried the ```disk-usage``` mode ?

**Comment by garnier-quentin** [comment]
I don't have a solution for AIX. You should ask to your support if there are OIDs for that.
