### ISSUE TITLE
[network::fortinet::fortigate::snmp::plugin] - Need new metrics

### ISSUE THREAD

**Issue by PatPil** [centreon/centreon-plugins#3617]
Hi,
i have need a new metric to plugin Fortinet on SDWAN services.
if you add the packet loss.
Thanks

**Comment by garnier-quentin** [comment]
Could you send a snmpwalk of following branch (by email) ?
.1.3.6.1.4.1.12356.101.4.9.2.1

**Comment by PatPil** [comment]
Hi,

-bash-4.2$ snmpwalk -v2c -cxxxxx 1.2.3.4  .1.3.6.1.4.1.12356.101.4.9.2.1
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.1.2 = INTEGER: 2
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.2.1 = STRING: "IN_HYD_Loopback"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.2.2 = STRING: "IN_HYD_Loopback"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.2.3 = STRING: "IN_HYD_Loopback"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.3.1 = Gauge32: 3
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.3.2 = Gauge32: 2
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.3.3 = Gauge32: 1
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.4.1 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.4.2 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.4.3 = INTEGER: 0
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.5.1 = STRING: "184.880"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.5.2 = STRING: "52.938"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.5.3 = STRING: "76.150"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.6.1 = STRING: "80.094"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.6.2 = STRING: "0.639"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.6.3 = STRING: "11.675"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.7.1 = Counter64: 10120
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.7.2 = Counter64: 10121
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.7.3 = Counter64: 10121
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.8.1 = Counter64: 10030
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.8.2 = Counter64: 10050
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.8.3 = Counter64: 10090
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.9.1 = STRING: "1.000"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.9.2 = STRING: "0.000"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.9.3 = STRING: "0.000"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.10.1 = STRING: "root"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.10.2 = STRING: "root"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.10.3 = STRING: "root"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.11.1 = Counter32: 999938
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.11.2 = Counter32: 999852
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.11.3 = Counter32: 999994
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.12.1 = Counter32: 999962
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.12.2 = Counter32: 999826
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.12.3 = Counter32: 999998
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.13.1 = Counter32: 1999900
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.13.2 = Counter32: 1999678
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.13.3 = Counter32: 1999992
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.14.1 = STRING: "VPN-ILL-Rel"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.14.2 = STRING: "VPN-BB-Airtel"
SNMPv2-SMI::enterprises.12356.101.4.9.2.1.14.3 = STRING: "VPN-4G-Rel"



***@***.***<http://www.vicat.fr/>

Patrick PILERI
IT – Pôle Production et Amélioration
+33 (0)4 74 27 59 61
***@***.******@***.***>

DIRECTION DES SYSTEMES D’INFORMATION
GPS : 4 rue Aristide Bergès – 38080 L’ISLE D’ABEAU
COURRIER : TSA 39604 – 38306 BOURGOIN CEDEX

[linkedin-round]<https://www.linkedin.com/company/vicat>  [twitter-round] <https://twitter.com/GroupeVicat>   ***@***.*** <https://www.facebook.com/Groupe.Vicat>   [www-round] <http://www.vicat.fr/>


De : qgarnier ***@***.***>
Envoyé : vendredi 22 avril 2022 14:02
À : centreon/centreon-plugins ***@***.***>
Cc : PILERI Patrick ***@***.***>; Author ***@***.***>
Objet : Re: [centreon/centreon-plugins] [network::fortinet::fortigate::snmp::plugin] - Need new metrics (Issue #3617)


Could you send a snmpwalk of following branch (by email) ?
.1.3.6.1.4.1.12356.101.4.9.2.1

**Comment by garnier-quentin** [comment]
Duplicate: https://github.com/centreon/centreon-plugins/issues/3712
