### ISSUE TITLE
Pb interfaces error : snmp_standard/mode/interfaces.pm

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-plugins#362]
Bonjour,

Nous avons un problème lors de la commande : 
centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces ... --add-errors

Quand une interface à eu des erreurs, elle est ensuite désactivée administrativement. Le plugin, la remonte en alerte avec un 100%. 

![cent](https://cloud.githubusercontent.com/assets/16583698/13987586/8ede63d0-f108-11e5-884a-877c68827b96.PNG)

Il faudrait prendre en compte que les interfaces "UP".

**Comment by garnier-quentin** [comment]
Bonjour,

Pour cela, vous devez ajouter l'option --add-status.
