### ISSUE TITLE
[OS::aix::snmp::plugin] Request for a plugin/template to monitor LOAD and MEmory of AIX server via SNMP

### ISSUE THREAD

**Issue by poomystery** [centreon/centreon-plugins#3626]
Hello Team,

Requesting you for template as cannot monitor MEMORY and LOAD of AIX servers 

![image](https://user-images.githubusercontent.com/101804076/166208852-7f54d400-9bdc-4bdc-b1b0-3db72a60a71c.png)

**Comment by garnier-quentin** [comment]
Which OIDs could be used ? (mib file and snmpwalk example)

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
