### ISSUE TITLE
[alcatel::common] Add support for 6900 omniswitch

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#363]
Hi, 

Actually plugin doesn't work for 6900 Alcatel DC switch. Some slight differences on OID values.

Regards,

**Comment by garnier-quentin** [comment]
I think i'll create also a standard one.

**Comment by Sims24** [comment]
Ok @garnier-quentin , let you handle this one as it will be probably quicker ;) 

Mibs are here :
[ALCATEL-IND1-HEALTH-MIB.txt](https://github.com/centreon/centreon-plugins/files/195139/ALCATEL-IND1-HEALTH-MIB.txt)
[ALCATEL-IND1-BASE.txt](https://github.com/centreon/centreon-plugins/files/195141/ALCATEL-IND1-BASE.txt)
[ALCATEL-IND1.txt](https://github.com/centreon/centreon-plugins/files/195140/ALCATEL-IND1.txt)

OIDs for aos7 and 6900 starts around  .1.3.6.1.4.1.6486.801.1.2.1.16.1.1.1

Thanks !!

**Comment by garnier-quentin** [comment]
You can test it with new omniswitch plugin. Need more informations.
