### ISSUE TITLE
[hardware::server::huawei::hmm::snmp::plugin] --mode=chassis --component=psu UNKNOWN: SNMP Table Request : undoFailed

### ISSUE THREAD

**Issue by lgigil** [centreon/centreon-plugins#3631]
Hello I'm reporting a problem about monitoring Huawei HMM with Centreon plugins.

When I issue the comand:
`./centreon_plugins.pl --plugin=hardware::server::huawei::hmm::snmp::plugin --mode=chassis --hostname=**.**.**.** --snmp-version='2c' --snmp-community='***'  --component='psu' --verbose --debug`
I receive this error:
`UNKNOWN: SNMP Table Request : undoFailed`
The error is affecting the component **psu** only. Monitoring of other components (blade, fan, switch) is working fine.

Thank you,
Luigi

**Comment by garnier-quentin** [comment]
Could you try to snmpwalk the following branch ? .1.3.6.1.4.1.2011.2.82.1.82.100.4.2001.1
If it's working, you can try to use the plugin with option ```--snmp-force-getnext```

**Comment by garnier-quentin** [comment]
thanks for the feedback. I think the agent doens't like the snmp bulk.
