### ISSUE TITLE
[cloud::prometheus::restapi::plugin]No response

### ISSUE THREAD

**Issue by gwendalpraud** [centreon/centreon-plugins#3632]
Hi,
I want to use the prometheus plugin to integrate prometheus on Centreon.
However, I'm trying a lot of different way to communicate with prometheus and the plugin always return the same thing :
UNKNOWN: 500 Can't connect to X.X.X.X:443
I really use the 443 port on prometheus and I communicate with it on https.
Here is my request :
./centreon_plugins.pl --plugin=cloud::prometheus::restapi::plugin --mode=target-status --hostname='X.X.X.X' --port=443 --proto='https' --credentials --username='xxx' --password='xxx'

I can test a request with curl and it answer :
curl -k 'https://xxx:xxx@X.X.X.X/prometheus/api/v1/query?query=up&time'
{"status":"success","data":{"resultType":"vector","result":[]}}

Can you help me please ?

**Comment by Sims24** [comment]
Hi, 

Could you provide the result of the centreon_plugins.pl with the --debug flag enabled please?

**Comment by gwendalpraud** [comment]
Hi,
here is the response with --debug flag :
UNKNOWN: 500 Can't connect to X.X.X.X:443
Query URL: 'https://X.X.X.X/api/v1/targets'
======> request send
GET https://X.X.X.X:443/api/v1/targets
User-Agent: centreon::plugins::backend::http::useragent

======> response done
500 Can't connect to X.X.X.X:443
Content-Type: text/plain
Client-Date: Tue, 03 May 2022 07:12:02 GMT
Client-Warning: Internal response

Can't connect to X.X.X.X:443

**Comment by gwendalpraud** [comment]
I tried with --url-path='/prometheus/api/v1' but the response is the same

**Comment by Sims24** [comment]
Could you try with --http-backend=curl please ?

**Comment by gwendalpraud** [comment]
UNKNOWN: curl perform error :
Query URL: 'https://X.X.X.X/prometheus/api/v1/targets'
== Info: About to connect() to X.X.X.X port 443 (#0)
== Info:   Trying X.X.X.X...
== Info: Connected to X.X.X.X (X.X.X.X) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: Server certificate:
== Info:        subject: CN=X.X.X.X,OU=YYYY@ZZZ,OU=...,O=...,C=FR
== Info:        start date: sept. 29 10:55:10 2021 GMT
== Info:        expire date: sept. 28 10:55:10 2024 GMT
== Info:        common name: X.X.X.X
== Info:        issuer: CN=Autorite ,O=...,L=...,ST=...,C=FR
== Info: NSS error -8179 (SEC_ERROR_UNKNOWN_ISSUER)
== Info: Peer's Certificate issuer is not recognized.
== Info: Closing connection 0

**Comment by Sims24** [comment]
You can add the --insecure flag to mimic the -k curl opt.

**Comment by gwendalpraud** [comment]
Yes, It works !!
Thanks a lot for your help 👍 🥇
