### ISSUE TITLE
[hardware::sensors::jacarta::snmp::plugin] create support for interseptor

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3633]
The plugin [hardware::sensors::jacarta::snmp::plugin] supports actually only interseptor pro, please create support for interseptor also:

- [interSeptor-MIB.zip](https://github.com/centreon/centreon-plugins/files/8608345/interSeptor-MIB.zip)
- [snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/8608346/snmpwalk.txt)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3637
