### ISSUE TITLE
Cisco Umbrella plugin

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#3636]
Hi,

Is it possible tu add a plugin to check the Cisco Umbrella VA Health and stats?

Here the OID to check to get Appliance Health and stats:
https://docs.umbrella.com/deployment-umbrella/docs/appendix-c-enable-snmp-monitoring

I can provide a full snmpwalk by email.

Thanks,

**Comment by Sims24** [comment]
Hi @rk4an 

Yes definitely. 

Please send it to qgarnier@centreon.com and sbomm@centreon.com. 

Cheers,

**Comment by garnier-quentin** [comment]
Could you also attach MIB files ?

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3828
