### ISSUE TITLE
processcount 

### ISSUE THREAD

**Issue by GhilesKDH** [centreon/centreon-plugins#364]
Hi quentin, 
I am traying to monitor Oracle process, with mode processcount,
The process's name is "asm_pmon_+asm1", 
when i execute this command in CLI it retrun  good output:
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=xx.xx.xx.xx --snmp-version='2c' --snmp-community='xxxxxxxx'  --process-status  --process-path='.*' --process-args='' --regexp-name --regexp-path --regexp-args --warning='' --critical='1:1' --process-name='asm_pmon_\+asm1' --verbose
OK: Number of current processes running: 1 | 'nbproc'=1;;1:1;0;
Process: [ name => asm_pmon_+asm1 ] [ status => runnable ] [ args =>  ] [ path => asm_pmon_+ASM1 ]

But in centreon web, the same command defined for the service return no process !!
of corse i tried first without \ before + and its not working too.

I tried to see what is stored in the database:
MariaDB [centreon_storage]> select command_line from services where service_id=7695;

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=xx.xx.xx.xx --snmp-version='2c' --snmp-community='xxxxxxxx'  --process-status --process-name='asm_pmon_\+asm1' --process-path='' --process-args='' --regexp-name --regexp-path --regexp-args --warning='' --critical='1:1'  

if i copy/paste this in the terminal of the poller, it work fine !!
All other check process work fine, this is the only check that does not work. because there is "+" in the process name.
i tried many syntaxe in process-name for exemple:
asm_pmon_\+asm.*
asm_pmon_+asm.*
asm_pmon_\+asm1
^asm_pmon_+asm
....
the only one that works fine is when i use 'asm_pmon_+a*' in the MACRO PROCESSNAME (in Centreon web).

Any help ? is it a bug ?

thank you -:)

**Comment by garnier-quentin** [comment]
Hi,

The process name has the '+' character ? You could use following syntax: 
asm_pmon_[+]asm.*

Or:

asm_pmon_.asm.*

Is it working ?

**Comment by GhilesKDH** [comment]
YES, Its working :+1: 
Thank you quentin,

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
