### ISSUE TITLE
SNMP timout for HP::MSA2050

### ISSUE THREAD

**Issue by gr4ssi** [centreon/centreon-plugins#3642]
Hi, dear developers,
we use the HP::MSA2000 plugin to query a MSA2050 for health via SNMP:
[root@consol ~]# /opt/plugins/centreon/centreon_plugins.pl --plugin=storage::hp::msa2000::snmp::plugin --mode=hardware --hostname=192.168.1.12 --snmp-community=T0pS3cr3t

After 4 seconds I initially get this message: (usually on first try).
   UNKNOWN: SNMP Table Request : Timeout

A second later, when I rerun the command, it works immediately and repeatedly all the time (Until I pause running it for several minutes). I tried the "--global-timeout" feature with 20, but that didn't help.

Maybe totally unrelated, but LENOVO mentions that snmpwalk times out, and one should set the timeout to 20 and repetition to at least 2. Can I set those values for the SNMP Centreon plugin somehow? My perl skills are lacking, I checked the code but didn't find it.
(https://support.lenovo.com/de/de/solutions/ht503991-recommended-minimum-timeout-settings-for-net-snmp-snmpwalk-command-lenovo-x86-servers)

It's like the MSA first needs a nudge to wake up, and then is ready for action.

Since naemon is doing retries and not allerting immediately, this is an issue only a couple of times a day, but still anoying, and I'd like to fix it somehow. :-)
Best Regards

**Comment by Sims24** [comment]
Hi @gr4ssi 

You should use the the --snmp-timeout option. 

Here are the default options values: 

![image](https://user-images.githubusercontent.com/12429463/167087466-c416dcaf-c2cc-44db-b812-52eb9b0eab73.png)

**Comment by gr4ssi** [comment]
Hi @Sims24 ,
many thanks for the quick help, I set 'snmp-timeout:s' from 1 to 10 and it seems to be fixed. <3
Cheers

**Comment by Sims24** [comment]
You're welcome
