### ISSUE TITLE
[storage::dell::me4::restapi::plugin] error command check for HW-Storage-Dell-Me4-Restapi-Controller-Statistics

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3646]
Hi,

With PluginPack Dell-ME4, the check 'controller-statistics' show "UNKNOWN: No controllers found".
Missing dash for warning-data-read :

        --filter-name=''
	-warning-data-read=''
	--critical-data-read=''
	--warning-data-written=''
	--critical-data-written=''

Command "HW-Storage-Dell-Me4-Restapi-Controller-Statistics" : 
--filter-name='$_SERVICEFILTERNAME$' **-warning-data-read**='$_SERVICEWARNINGDATAREAD$' --critical-data-read='$_SERVICECRITICALDATAREAD$' --warning-data-written='$_SERVICEWARNINGDATAWRITTEN$' 

Best regards.

**Comment by garnier-quentin** [comment]
Fixed and available for the next release.
