### ISSUE TITLE
os::windows::snmp::plugin --mode=storage with big disk (10-50TB)

### ISSUE THREAD

**Issue by TexBill** [centreon/centreon-plugins#365]
plugin os::windows::snmp::plugin --mode=storage does not works with big disk.

[centreon@centreon]$ perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=*.*.*.* --snmp-community=***** --snmp-version=2c --warning=70 --critical=90 --verbose                             
OK: All storages are ok. | 'used_C:\ Label:  Serial Number *******'=21576499200B;0:209218801254;0:268995601612;0;298884001792
Storage 'C:\ Label:  Serial Number ********' Total: 278.36 GB Used: 20.09 GB (7.22%) Free: 258.26 GB (92.78%)
Skipping storage 'D:\ Label:  Serial Number ********': total size is <= 0 (-16363424858112)
Skipping storage 'E:\ Label:  Serial Number ********': total size is <= 0 (-6597206085632)

**Comment by garnier-quentin** [comment]
Yes. It's a known issue. It's a SNMP agent problem. I can't do nothing about it :(. You should use NSClient++ i think.

**Comment by TexBill** [comment]
Thanks for this very quick answer.
