### ISSUE TITLE
[network::cisco::meraki::cloudcontroller::restapi::plugin] - monitoring Meraki AP

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3657]
It should be nice to have dedicated modes to monitor Meraki AP for:

- Channel utilization (2,4 & 5 GHz)
![image](https://user-images.githubusercontent.com/6400595/168054784-e31ecec7-14e1-4704-93bc-86f5cfca7a00.png)
- Uplink traffic
![image](https://user-images.githubusercontent.com/6400595/168055626-263416ae-66de-4fe0-a939-21ce27a0767f.png)
- current clients (VLAN ID, usage, SSID, Channel, Channel width, Signal strength)
![image](https://user-images.githubusercontent.com/6400595/168055097-ce6c8fd4-3590-4c8f-a010-6fd2303a1409.png)
- Connections (Issues by SSID, problematic clients)
![image](https://user-images.githubusercontent.com/6400595/168055440-f128e3ee-b6b1-49ad-a055-d3e35a17554f.png)
![image](https://user-images.githubusercontent.com/6400595/168055470-48bb6f6d-ae53-42f0-8ec8-756ba4f90514.png)

**Comment by garnier-quentin** [comment]
I don't know if it's available with the API.

**Comment by Thibaud-OBSSA** [comment]
Hi Quentin,
If needed, I can provide data.

I may be interested to have the latency stats for wireless.
But I'm waiting from the engineer in charge which API request to use for his need.

Regards

**Comment by garnier-quentin** [comment]
I need API call examples (curl command and the result).

**Comment by garnier-quentin** [comment]
Do you find AP informations in the API ?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
