### ISSUE TITLE
Java Monitoring

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-plugins#366]
Hi Quentin,

can you build a plugin to Monitor the different memory areas in java?
That can be usefull for all java applications. It is a for deeper analysis. We have a request from our customer.
![tomcat_ram](https://cloud.githubusercontent.com/assets/2785700/14178343/7933b226-f75a-11e5-941a-cd1d8f4843fa.png)

I found already a script that should help a little bit to archive that here: https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=6269&cf_id=24

**Comment by garnier-quentin** [comment]
Hi Florian,

I think it's already exists. You have the mode 'memory-detailed' with tomcat plugin. But the mode should work with any jvm in fact.

**Comment by florian-asche** [comment]
Hi, the mode you mentioned is working with jmx. Unfortunately i can't use jmx not everywhere, so another way to gather that data whould be great.

**Comment by garnier-quentin** [comment]
The plugin looks for the pid and use jstat. Can be another way. I prefer jmx in fact :)

**Comment by florian-asche** [comment]
I am doing now too. Think this can be closed right?
