### ISSUE TITLE
[network::efficientip::snmp::plugin] add status plugin for efficientip

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3662]
Hi,

It would be interesting to add the status (.1.3.6.1.4.1.2440.1.17.2.2) and why not the role (.1.3.6.1.4.1.2440.1.17.2.1).
The mib indicates for the status:

SOLID server status. 0: ok 1: not configured 2: upgrading 3: init standby 4: invalid credentials 5: remote managed 6: timeout 7: split-brain 8: replication stopped

and for the role:
SOLID server role. 0: standalone 1: master 2: hot-standby 3: master recovered

I send you the mib in the ticket and the snmpwalk by mail.
Mib: [EfficientIP_MIBs.zip](https://github.com/centreon/centreon-plugins/files/8693190/EfficientIP_MIBs.zip)

Best regards.

**Comment by Sims24** [comment]
Hi @gagzou 

What do you have in mind regarding the mapping between MIBs states and centreon statuses? 

Would this work for you: 

**Server status** 

0: ok 
1: not configured => UNKNOWN
2: upgrading 
3: init standby 
4: invalid credentials => CRITICAL
5: remote managed 
6: timeout => WARNING
7: split-brain  => CRITICAL
8: replication stopped  => CRITICAL

**Comment by gagzou** [comment]
Hi @Sims24 
I think 
Server status

0: ok => OK
1: not configured => UNKNOWN
2: upgrading => WARNING
3: init standby
4: invalid credentials => CRITICAL
5: remote managed => OK
6: timeout => CRITICAL
7: split-brain => WARNING
8: replication stopped => CRITICAL
