### ISSUE TITLE
[apps:protocols:ftp] mode=date problem 

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#367]
Hello,

I just test the great ftp plugin with date mode and faced to 2 issues 
1. With option --directory, it seems that it does not use the directory when checking file time
   On line 104 
   if (!($time_result = apps::protocols::ftp::lib::ftp::execute($self, command => $map_commands{mdtm}->{$self->{ssl_or_not}}->{name}, command_args => [$file]))) {
               # Sometime we can't have mtime for a directory
               next;
           }

The $file does not include the $dir.$file. 
1. Do you think it may it be possible to make $current_time taking for reference local time of the server instead of unixtime directly ? In fact on my test, the remote time ($time_result) give me the local time, but as the $current_time is in GMT+2 here I got strange result...

Regards,
Fix

**Comment by garnier-quentin** [comment]
Hi Fixlair,

It's not really clear:
* first question: i need to test it. 'ls' don't give you back the dir also ?
* second question: you want an option to set a timezone ? Like that you could display the time like it was from the ftp server ?

**Comment by fixlair** [comment]
Hi Quentin,

* On my test, the resultat of "ls /folder1/folder2/" give me only the list of files (file1, file2 without /folder1/folder2/file1). The FTP server is "crushftp" so it may be specific to this software (I didn't test with proftp or filezilla server)

* For the second I don't know the best way to implement it. On the remote server (ftp server) I've got always the local time (=GMT+2 in my case) but on centreon_plugin server it returns the unix_time.
Maybe the propest way is to specify timezone in the script as you suggest ? or just an offset of time ?

**Comment by garnier-quentin** [comment]
I think, it depends of the server. I think i need to manage the case. 
For the second, i could add a timezone option to display it with another timezone.

**Comment by fixlair** [comment]
Great thanks a lot  :) I will be happy to test it in the next days !

**Comment by garnier-quentin** [comment]
You're welcome. I have tested it with crushftp. So it should work ;)
