### ISSUE TITLE
[PLUGIN PACKS] Some centreon-plugins don't plugin packaged

### ISSUE THREAD

**Issue by Gregesp** [centreon/centreon-plugins#3671]
Hello,

I could see, we have a little part of plugins who don't have their Plugin Packs and documentation associated.

Maybe it's normal (outdated or others), or not, just a forgot 🙂

The list :
**Apcupsd** https://github.com/centreon/centreon-plugins/tree/master/apps/apcupsd/local
**Checkmyws** https://github.com/centreon/centreon-plugins/tree/master/apps/checkmyws
**Arcserve UDP Job Status** https://github.com/centreon/centreon-plugins/tree/master/apps/backup/arcserve/udp/mssql/mode
**NetApp SnapCenter** https://github.com/centreon/centreon-plugins/tree/master/apps/backup/netapp/snapcenter/restapi
**Citrix** https://github.com/centreon/centreon-plugins/tree/master/apps/citrix/local
**Interactive Intelligence Interaction Gateway** -> **Interactive Intelligence become Genesys** https://github.com/centreon/centreon-plugins/tree/master/apps/inin/ig/snmp
**Interactive Intelligence Media Server** -> **Interactive Intelligence become Genesys** https://github.com/centreon/centreon-plugins/tree/master/apps/inin/mediaserver/snmp
**Jive ETL Jobs** -> **Jive Software become Aurea Software** https://github.com/centreon/centreon-plugins/tree/master/apps/jive/sql/mode
**Apache Jmeter** https://github.com/centreon/centreon-plugins/tree/master/apps/jmeter
**Kingdee EAS Application & DB Server Status** https://github.com/centreon/centreon-plugins/tree/master/apps/kingdee/eas
**IBM Lotus (Domino) Mail Server** -> **IBM Lotus become HCL** https://github.com/centreon/centreon-plugins/tree/master/apps/lotus/snmp
**ActiveDirectory WSMan** https://github.com/centreon/centreon-plugins/tree/master/apps/microsoft/activedirectory/
**IIS WSMan** https://github.com/centreon/centreon-plugins/tree/master/apps/microsoft/iis/wsman
**SolarWinds Loggly** https://github.com/centreon/centreon-plugins/tree/master/apps/monitoring/loggly/restapi
**Quanta.io application probes** https://github.com/centreon/centreon-plugins/tree/master/apps/monitoring/quanta/restapi
**PineApp Mail Secure** https://github.com/centreon/centreon-plugins/tree/master/apps/pineapp/securemail/snmp
**RRDCached** https://github.com/centreon/centreon-plugins/tree/master/apps/rrdcached
**Sahi Pro scenario** https://github.com/centreon/centreon-plugins/tree/master/apps/sahipro/restapi
**Toshiba Storemate** https://github.com/centreon/centreon-plugins/tree/master/apps/toshiba/storemate/sql/mode
**oVirt** https://github.com/centreon/centreon-plugins/tree/master/apps/virtualization/ovirt
**Cisco Meeting Place** https://github.com/centreon/centreon-plugins/tree/master/apps/voip/cisco/meetingplace
**Zoom** https://github.com/centreon/centreon-plugins/tree/master/apps/zoom/restapi
**Nginx Ingress Controller metrics through Prometheus server** https://github.com/centreon/centreon-plugins/tree/master/cloud/prometheus/direct/nginxingresscontroller
**Safenet HSM with ProtectToolkit** https://github.com/centreon/centreon-plugins/tree/master/hardware/devices/safenet/hsm/protecttoolkit
**Isovision AppeartTV** https://github.com/centreon/centreon-plugins/tree/master/hardware/devices/video/appeartv/snmp
**TemPerHum Sensors** https://github.com/centreon/centreon-plugins/tree/master/hardware/sensors/temperhum/local
**Avaya Communication Manager** https://github.com/centreon/centreon-plugins/tree/master/hardware/telephony/avaya/cm/snmp
**Alcatel DSL ISAM Family** https://github.com/centreon/centreon-plugins/tree/master/network/alcatel/isam/snmp
**Alcatel 1830 Photonic Service Switch** https://github.com/centreon/centreon-plugins/tree/master/network/alcatel/pss/1830/snmp
**Cambium ePMP equipments** https://github.com/centreon/centreon-plugins/tree/master/network/cambium/epmp/snmp
**Evertz Audio Embedder Card** https://github.com/centreon/centreon-plugins/tree/master/network/evertz/AEA47721/snmp
**Evertz Reclocking Distribution Amplifier Card** https://github.com/centreon/centreon-plugins/tree/master/network/evertz/DA6HDL7700/snmp
**HP Moonshot Switch Module for HP Moonshot chassis** https://github.com/centreon/centreon-plugins/tree/master/network/hp/moonshot/snmp
**Libraesva appliance** https://github.com/centreon/centreon-plugins/tree/master/network/libraesva/snmp
**Netgear Smart Switches** https://github.com/centreon/centreon-plugins/tree/master/network/netgear/sseries/snmp

And the plugins dedicated to the notifications/tickets :

**Centreon Open Tickets** https://github.com/centreon/centreon-plugins/tree/master/notification/centreon/opentickets/api
**Foxbox Notifications** https://github.com/centreon/centreon-plugins/tree/master/notification/foxbox
**HighSMS notifications** https://github.com/centreon/centreon-plugins/tree/master/notification/highsms
**Jasmin SMS** https://github.com/centreon/centreon-plugins/tree/master/notification/jasminsms/httpapi
**Microsoft 365 Teams notifications** https://github.com/centreon/centreon-plugins/tree/master/notification/microsoft/office365/teams
**OVH SMS** https://github.com/centreon/centreon-plugins/tree/master/notification/ovhsms
**iOS push notifications via Prowl** https://github.com/centreon/centreon-plugins/tree/master/notification/prowl
**Sirportly tickets** https://github.com/centreon/centreon-plugins/tree/master/notification/sirportly
**Slack/Mattermost notifications** https://github.com/centreon/centreon-plugins/tree/master/notification/slack
**Telegram notifications** https://github.com/centreon/centreon-plugins/tree/master/notification/telegram

Regards,

**Comment by garnier-quentin** [comment]
Thanks. We are going to create pack for following plugins:
* IIS WSMan
* ActiveDirectory WSMan
* Sahi Pro scenario
* HP Moonshot Switch Module
* Libraesva,
* Netgear Smart Switches
* oVirt
* PineApp SecureMail

For other, i don't think it's needed. But if someone want it, please comment it :)

**Comment by Gregesp** [comment]
Hello,

In my opinion of a Centreon user, it could be interesting to have a maximum (or all) of the centreon-plugins with is Plugin Packs (Because we have a documentation and the preconfigured template).

You have probably reason to do not plugin packed others centreon-plugins (Outdated, Too poor on functionnality, devices or apps with a end of lifecycle reached, community made and so not documented, too specific, etc..) like (Citrix, Arcserve UDP Job Status, Jive ETL Jobs, Cisco Meeting Place, Alcatel DSL ISAM Family, Cambium ePMP equipments, Evertz Audio Embedder Card, Evertz Reclocking Distribution Amplifier Card).

But some centreon-plugins in this list covers devices or apps actively used (Apcupsd, NetApp SnapCenter, Interaction Gateway, Media Server, IBM Lotus (Domino) Mail Server, SolarWinds Loggly, Zoom, Avaya Communication Manager, Nokia1830 Photonic Service Switch, TemPerHum Sensors, or RRDCached).

About the centreon-plugins dedicated to notify and open or close ticket, is not a way of a new category of Plugin Packs, who would be configure a new entry of a command notification perhaps ?

Regards,
Greg

**Comment by Sims24** [comment]
Hi Greg, 

We will discuss this internally, but yes we might be reluctant to create Packs based on pretty old code for which we got very few feedback.

About the notification part, I would be more than happy to see you post an idea on the watch to tell us how you would imagine using such feature. 

Kind regards, 
Simon

**Comment by romsworld** [comment]
+1 for jmeter plugin 

Thanks,
