### ISSUE TITLE
 /usr/lib64/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin apps::proxmox::ve::restapi::plugin --mode storage-usage

### ISSUE THREAD

**Issue by Matthias-Baake** [centreon/centreon-plugins#3675]
Hi,

after upgrading Proxmox from 7.1 to 7.2 this check now reports:

UNKNOWN: Illegal division by zero at /usr/lib64/nagios/plugins/centreon-plugins/apps/proxmox/ve/restapi/mode/storageusage.pm line 81.

This seems to be only a problem on Nodes that use zfs, anybody has an idea how to fix this?

Regards

Matthias

**Comment by garnier-quentin** [comment]
You could provide the debug with option --debug-stream ?

**Comment by garnier-quentin** [comment]
You can test with the last version: https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip

**Comment by Matthias-Baake** [comment]
Is there anything newly pushed, I had checked out master bevor I opened the ticket. I attached the debug output, with a few redactions.

[debug-log.txt](https://github.com/centreon/centreon-plugins/files/8739056/debug-log.txt)

**Comment by garnier-quentin** [comment]
You can update it. It should be fixed.

**Comment by Matthias-Baake** [comment]
thx a lot, that was really quick.
