### ISSUE TITLE
os::windows::snmp::mode::swap  -  Difference in result with real-swap

### ISSUE THREAD

**Issue by khalidbounoun** [centreon/centreon-plugins#3678]
Hello, 

I do a swap check on windows server, the result returned is different from reality

```
bash-4.2$ /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=swap --hostname=10.238.0.146 --snmp-version='2c' --snmp-community='GRFLR_PUB'

OK: Swap Total: 36.75 GB Used: 31.56 GB (85.87%) Free: 5.19 GB (14.13%) | 'used'=33882570752B;;;0;39459422208
```

The editor of the solution running on my server doesn't understand what centreon is based to check the swap, because the Windows page file is only 5GB.

when I add the _--real-swap_ option I have a different result

```
bash-4.2$ /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=swap --hostname=10.238.0.146 --snmp-version='2c' --snmp-community='GRFLR_PUB'  --real-swap

OK: Swap **Total: 4.75 GB Used: 2.38 GB (50.04%) Free: 2.37 GB (49.96%)** | 'used'=2552299520B;;;0;5100273664
```

Can you tell me on which performance indicator the plugin is based and what is the difference with the real-swap option?

**Comment by garnier-quentin** [comment]
By default (without ```--real-swap```), we check the value provided in ```Virtual memory``` entry.
With ```--real-swap``` option, we subtract the value provided in ```Physical RAM``` entry. You can choose to use or not that option.
