### ISSUE TITLE
[apps::cluster::mscs::local::plugin] uninitialized value

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#368]
Hello Quentin,

Just tested on an other client and this time there's uninitialized value :

/usr/lib/nagios/plugins/check_centreon_nrpe -H myhost -t 15  -p 5665 -u -m 8192 -c check_centreon_plugins -a 'apps::cluster::mscs::local::plugin' 'network-status' ' --verbose '
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/networkstatus.pm line 164.
OK: Network 'Cluster Network 1' state : up |

/usr/lib/nagios/plugins/check_centreon_nrpe -H myhost -t 15  -p 5665 -u -m 8192 -c check_centreon_plugins -a 'apps::cluster::mscs::local::plugin' 'resource-status' ' --verbose '
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcestatus.pm line 169.
OK: Resource 'Quorum Disk' status : skipped (no value(s)) |

/usr/lib/nagios/plugins/check_centreon_nrpe -H myhost -t 15  -p 5665 -u -m 8192 -c check_centreon_plugins -a 'apps::cluster::mscs::local::plugin' 'resourcegroup-status' ' --verbose '
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcegroupstatus.pm line 206.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcegroupstatus.pm line 206.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcegroupstatus.pm line 206.
Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-1fd1bf96a1d8dec4e59b545a0a38a7aa94f46a3a\inc\lib/apps/cluster/mscs/local/mode/resourcegroupstatus.pm line 206.
OK: Resource group 'XXXXXXXXXX' status : skipped (no value(s)) |

No problem for 'list-nodes' and 'node-status'.

**Comment by garnier-quentin** [comment]
Could you give me the wmi result for tables: 'MSCluster_ResourceGroupToPreferredNode', 'MSCluster_ResourceGroup', 'MSCluster_Network', 'MSCluster_Resource'.

**Comment by ritouret** [comment]
There is 2 nodes configured for the first table, 4 resourcegroup for the second and 11 resource for the last table.
I can mail you the results.

**Comment by garnier-quentin** [comment]
Yes please!

**Comment by ritouret** [comment]
Thanks.
Have you seen your mailbox this morning ?

**Comment by ritouret** [comment]
Hello Quentin,

Just tested the new version and all mode i told you are good.

But i didn't talk about the list-resources which always make uninitialized value :

Use of uninitialized value in hash element at C:\Windows\TEMP\par-4652504152434c5530314124\cache-bfb533f552f34055aeceea51568bfd2ece94b1af\inc\lib/apps/cluster/mscs/local/mode/listresources.pm line 82.
Use of uninitialized value in concatenation (.) or string at C:\Windows\TEMP\par-4652504152434c5530314124\cache-bfb533f552f34055aeceea51568bfd2ece94b1af\inc\lib/apps/cluster/mscs/local/mode/listresources.pm line 105.

Sorry for that ...

**Comment by garnier-quentin** [comment]
Done the change

**Comment by ritouret** [comment]
No more errors now.

Thank you Quentin.
