### ISSUE TITLE
Office365 plugin error

### ISSUE THREAD

**Issue by LaurentV9** [centreon/centreon-plugins#3687]
Hello guys,

I just installed last version of Office365 plugin on my poller 

Package centreon-plugin-Cloud-Microsoft-Office365-Management-Api-20220518-070245.el7.centos.noarch already installed and latest version

and I have an error:

 UNKNOWN: Cannot load module --custommode.
Can't locate cloud/microsoft/office365/custom/graphapi.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::13548424=HASH(0xcebb88) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/centreon_office365_management_api.pl line 1730.

I saw on other post we need to install Perl/JSON::XS

but it's already installed:

Package 1:perl-JSON-XS-3.01-2.el7.x86_64 already installed and latest version
Nothing to do

And doesn't work...

Can you help us?

Laurent

**Comment by LaurentV9** [comment]
sorry but... the unstable repository? :-)
How can I do that?

**Comment by garnier-quentin** [comment]
```yum --enablerepo=centreon-unstable-noarch update centreon-plugin...```

**Comment by LaurentV9** [comment]
ok, thanks.

But now, I come back to my first issue :-(

With this query:

/usr/lib/centreon/plugins/centreon_office365_management_api.pl --plugin=cloud::microsoft::office365::management::plugin --mode=service-status --tenant='xxxxxxxx' --client-id='xxxxxxx' --client-secret='xxxxxxx'  --filter-service-name='' --warning-status='' --critical-status='' --verbose --debug

the response:
UNKNOWN: Graph endpoint API return error code 'UnknownError'
and
======> response done
HTTP/1.1 403 Forbidden
....
....
{"error":{"code":"UnknownError","message":"","innerError": .........

Do you know it?

I only have the issue for the service-status of Management_O365
Sharepoint, Teams, Exchange,... are working good.

Laurent

**Comment by garnier-quentin** [comment]
Could you provide the full debug ?

**Comment by LaurentV9** [comment]
yes, as requested in the documentation: ServiceHealth.Read.All

**Comment by garnier-quentin** [comment]
Maybe you need to clean the session ? The cache file to be reconnected.

**Comment by LaurentV9** [comment]
ok, not linked to Centreon. I tried in curl directly and same error on GET https://graph.microsoft.com/v1.0/admin/serviceAnnouncement/healthOverviews?%24expand=issues
with my token

**Comment by garnier-quentin** [comment]
Please comment it, if it can help others.
