### ISSUE TITLE
[snmp_standard::plugin] mode interfaces

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#369]
Hello,

Here is a redondant network provided by two interfaces on all switches.

My customer want to create one service which would be warning if one interface is down and critical if the two interfaces are down.

When using this command, **criterias are applied for each instance of the result list **:
[centreon-engine@frparadm135 ~]$ /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::extreme::snmp::plugin --mode=interfaces  --add-status --interface="1048","2050" --hostname=myhost --snmp-version 2c --snmp-community  public --snmp-timeout 15 --snmp-retries 1 --verbose --critical-status='%{admstatus} eq  "down" and %{opstatus} eq "down"' --warning-status='%{admstatus} eq  "up" and %{opstatus} eq "down"'
OK: All interfaces are ok |
Interface '1:48' Status : up (admin: up)
Interface '2:50' Status : up (admin: up)

Would it be possible to add options to calculate the same criteria but **for all instance of the result list** ?
--critical-status-calculation=unit (each interface, by default) or both (all the interface)
--critical-status-operand=OR or AND or XOR
--warning-status-calculation=unit (each interface, by default) or both (all the interface)
--warning-status-operand=OR or AND or XOR

With these options, we would be able to have warning status if one interface is down with :
--warning-status-calculation=both
--warning-status-operand=OR

and a critical status if two interfaces are down with :
--critical-status-calculation=both
--critical-status-operand=AND

**Comment by garnier-quentin** [comment]
Right now, you cannot do that.

**Comment by garnier-quentin** [comment]
I can do it in centreon-plugins. But it will become too complex. I want to keep it "simple". I don't want to add it like also:
* thresholds according the timeperiod or time (if cpu is 100% during 4 hours).

It should be in a correlation engine system (in another language like C/C++).
