### ISSUE TITLE
Improve coverage of HPE OneView hardware::server::hp::oneview::restapi::plugin

### ISSUE THREAD

**Issue by Gregesp** [centreon/centreon-plugins#3707]
Hello,

Is it possible to add more components for HPE OneView ?

By comparison of Dell OpenManage, it cover battery, fan, memory, psu, temperature, and many others components.

Actually OneView have just storage, and hardware (server, enclosure)

HPE publish the Rest API documentation here : https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html 

Could you add more mode as temperature, alerts, and others.

I can give you also cURL results to help.

Regards, 
Greg

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
