### ISSUE TITLE
Add Tufin Orchestration Suite plugin

### ISSUE THREAD

**Issue by Gregesp** [centreon/centreon-plugins#3708]
Hello,

Is it possible to create a plugin for Tufin Orchestration Suite ?

Tufin provide some information about SNMP monitoring https://forum.tufin.com/support/kc/latest/Content/Suite/3632.htm?tocpath=TOS%20Maintenance%20and%20Configuration%7CMonitoring%20and%20Maintenance%7C_____0

The MIB files :
https://forum.tufin.com/support/kc/latest/Content/Suite/9479.htm?tocpath=TOS%20Maintenance%20and%20Configuration%7CMonitoring%20and%20Maintenance%7CSNMP%20Monitoring%7C_____0

I can give you some snmpwalk also.

Regards,
Greg

**Comment by garnier-quentin** [comment]
Seems quite simple. Only need the snmpwalk of the following branch: .1.3.6.1.4.1.21834

**Comment by garnier-quentin** [comment]
Have you sent us the snmpwalk ?

**Comment by Gregesp** [comment]
Hi,
Not yet, device are not configured.
Next week.
Regards,

**Comment by garnier-quentin** [comment]
Do you have some news ?

**Comment by Gregesp** [comment]
Hello,
I close this Issue, Network Security admin don't want activate snmp agent on appliance in order to request it with the snmpwalk and give result.
Regards,

**Comment by garnier-quentin** [comment]
Too bad. Thanks for the feedback
