### ISSUE TITLE
Centreon plugins with perl connector

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#371]
Hi,
I saw a couple of topics on the matter, but I'm not sure what's wrong or right.
So, I have some questions :
 - Is it possible to use the perl connector with the centreon_plugins.pl script ?
 - Do we have to select the connector on each command ?
 - Do we have to had something on the connector command line ?
 - Do we have to edit the centreon_plugins.pl script ?

Thank you for your responses.

**Comment by garnier-quentin** [comment]
Hi

1 - It's possible
2 - Yes you have to select it
3 - Yes you need to use the --code option like: --code "'/usr/lib/nagios/plugins/'\;"
4 - If you add the option --code in connector command line. You don't need.

But i recommand : don't use the perl connector with "centreon-plugins". It's not worth it.

**Comment by dooko** [comment]
Thanks.

Well the problem is that since we implemented the centreon plugins, the load on our pollers exploded, as it was before we use the perl connector on our old perl plugins.
But if I understand right, the way the centreon_plugins.pl works, with modules load and all, can't get any faster with the connector ?

**Comment by garnier-quentin** [comment]
That's right! The connector can work if you build standalone centreon-plugins with App::Fatpacker module.

**Comment by dooko** [comment]
Hi,
Can you give us an example for a centreon-plugins ?
I can't make it works.
Thanks

**Comment by garnier-quentin** [comment]
Example of what exactly ?

**Comment by dooko** [comment]
To build a standalone plugin with all dependencies :)

**Comment by garnier-quentin** [comment]
I'll add it in the faq.

**Comment by dooko** [comment]
Ok thanks, I wait for it.

**Comment by garnier-quentin** [comment]
I have updated the FAQ! Sorry for the time.

**Comment by dooko** [comment]
Thanks, works nicely.
