### ISSUE TITLE
local ping plugin

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-plugins#372]
Hi Quentin,

do we have a plugin to ping a host, like check_icmp in nagios-plugins?

Check:

> ./check_icmp -H www.google.de -w "200.000ms,40%" -c "500.000ms,80%"
> OK - www.google.de: rta 23,300ms, lost 0%|rta=23,300ms;200,000;500,000;0; pl=0%;40;80;; rtmax=23,444ms;;;; rtmin=23,209ms;;;; 

Options:

> Usage:
>  check_icmp [options] [-H] host1 host2 hostN
> 
> Options:
>  -h, --help
>     Print detailed help screen
>  -V, --version
>     Print version information
>  -H
>     specify a target
>  -w
>     warning threshold (currently 200,000ms,40%)
>  -c
>     critical threshold (currently 500,000ms,80%)
>  -s
>     specify a source IP address or device name
>  -n
>     number of packets to send (currently 5)
>  -i
>     max packet interval (currently 80,000ms)
>  -I
>     max target interval (currently 0,000ms)
>  -m
>     number of alive hosts required for success
>  -l
>     TTL on outgoing packets (currently 0)
>  -t
>     timeout value (seconds, currently  10)
>  -b
>     Number of icmp data bytes to send
>     Packet size will be data bytes + icmp header (currently 68 + 8)
>  -v
>     verbose
> 
> Notes:
>  The -H switch is optional. Naming a host (or several) to check is not.
> 
>  Threshold format for -w and -c is 200.25,60% for 200.25 msec RTA and 60%
>  packet loss.  The default values should work well for most users.
>  You can specify different RTA factors using the standardized abbreviations
>  us (microseconds), ms (milliseconds, default) or just plain s for seconds.
> 
>  The -v switch can be specified several times for increased verbosity.

**Comment by garnier-quentin** [comment]
We don't have right now.

**Comment by maksimatveev** [comment]
@florian-asche you can try **fping**. it's a little faster than a standard plugin check_icmp and better to compile it.

**Comment by garnier-quentin** [comment]
I think i won't do a Perl check_icmp. Because you need a setuid script and it's not working for Perl Version > 5.10 (you'll need a wrapper).

**Comment by CPbN** [comment]
What about Perl Connector being the needed wrapper of a `check_icmp` fatpack plugin version ?

**Comment by CPbN** [comment]
@garnier-quentin what about Perl Connector being the needed wrapper of a `check_icmp` fatpack plugin version ?
