### ISSUE TITLE
Create a plugin for Aruba Orchestrator

### ISSUE THREAD

**Issue by Thibaud-OBSSA** [centreon/centreon-plugins#3724]
Hi,
Can you please create a new plugin for Aruba Orchestrator

Here are the CURL command , I'll send by mail the result.

# ARUBA_ORCHESTRATOR
SERVER=url_of_the_dashboard.silverpeak.cloud:443
API_KEY=xxxxxx

## authentication
Authentication is made with a X-Auth-Token header

## List of appliance
To get the inventory , (and the appliance ID , as it's needed for further request)
curl  -H "Content-Type: application/json" -H "X-Auth-Token: $API_KEY" https://${SERVER}/gms/rest/appliance
	
## List of groups
Appliance may be organised in group ( can be useful for filtering)
curl -H "Content-Type: application/json" -H "X-Auth-Token: $API_KEY" https://${SERVER}/gms/rest/gms/group
	
## Active Alarm
With this request , you get the alarm (both ack or not)  for one or more appliances.
For the alarm, It would be nice to have the description and the source. 
curl -H "X-Auth-Token: $API_KEY" -H "Content-Type: application/json"  "https://${SERVER}/gms/rest/alarm/appliance?view=active&&orderBySeverity=true&&&" -d   '{"ids": ["105.NE","95.NE"]}'

If needed, API detail are attached.

[Orchestrator_API_9.1.0.40524.pdf](https://github.com/centreon/centreon-plugins/files/8880103/Orchestrator_API_9.1.0.40524.pdf)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3913
