### ISSUE TITLE
VSFservice  monitor "unknown status" in aruba switch 2930F

### ISSUE THREAD

**Issue by dmajhi** [centreon/centreon-plugins#3727]
Thanks for using centreon-plugins! Please follow the indications shown below according to your issue and describe it in English.

The status problem is due to the plugin or plugin-pack version.AS per centreon expert

## New Plugins and modes

To develop a Plugin/mode, we need the following:

* SNMP: MIBs files and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk)
.1.3.6.1.4.1.47196.4 = No Such Object available on this agent at this OID

* HTTP API (SOAP, Rest/Json, XML-RPC): the documentation and some curls examples
* CLI: command line examples
* SQL: requests
* JMX: mbean names and attributes

If some parts of information are confidentials, please send them directly by email to qgarnier@centreon.com and sbomm@centreon.com.

Please note that all the developments are open-source. We can't give a date for the development, achievement or release. If it's a priority for you,
send us an email about it (qgarnier@centreon.com and sbomm@centreon.com) and we'll put you in touch with our company.

## Bug/Question

If you are reporting a bug/question, make sure that there aren't any similar/duplicates issues already open. You 
can ensure this by searching the issue list for this repository. If so, please close your issue and add a comment to the existing one instead.

Otherwise, open a new issue and provide all parts of information you can (full command line used, actual output, expected output, error message...).

**Comment by garnier-quentin** [comment]
I'm sorry but i doni't understand your issue. Which plugins and mode do you use ?

**Comment by garnier-quentin** [comment]
I think you have an issue with images

**Comment by garnier-quentin** [comment]
Please comment it if you have more informations.
