### ISSUE TITLE
Question: How to work with a base OID used for multiple alarms traps

### ISSUE THREAD

**Issue by uc33260** [centreon/centreon-plugins#3728]
Hello,

I configured traps on my Centreon server to receive alarms from an Avaya PBX (IP Office R11.1).

The constructor Avaya use base OID for multiple traps, for example all alarms related to licensing issue are defined on this  OID:

.1.3.6.1.4.1.6889.2.2.1.2.0.46 = when the alarm is active
.1.3.6.1.4.1.6889.2.2.1.2.0.47 = when the alarm is cleared

And the constructor use specific codes to identify which type of license is identified for the trap:

![OID_Avaya](https://user-images.githubusercontent.com/83720227/173379197-9d9f58db-fa0d-437f-a5a6-24e8a04b1fbf.png)

I used iReasoning MIB browser to receive traps from the PBX, here is the result for all licensing traps (with same OID)

![MIB_Browser](https://user-images.githubusercontent.com/83720227/173379389-e6dc69ab-62bb-4ab5-82f1-7a51496e6f10.png)

Question: How can I do to be able to create all my licensing services to monitor ?

Because right now, I cannot create two services with the same OID:

![trap_centreon](https://user-images.githubusercontent.com/83720227/173379786-b5c18a07-8313-4eb9-b793-2b832d341a89.png)

Thank you for help

Regards

**Comment by garnier-quentin** [comment]
Thanks for your issue but it's not a centreon-plugins issue. You should post it in centreon github.
Coul you provide the MIB file (with trap definition) ?

**Comment by uc33260** [comment]
Sorry, I close the request and open it again on the right folder.
