### ISSUE TITLE
[network::checkpoint::plugin] hastate mode enhancement 

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#373]
Hello,
Checkpoint plugins doesn't have an option to specify which server should be master or slave.

This is usefull to rised an alert when a cluster failover occur.

Is there a way to add this option ?

**Comment by garnier-quentin** [comment]
If we can get the members and the status it could be interesting. Thanks!

**Comment by hdep** [comment]
Hello,

I am not sure to understand your answer. 
Are you expecting  some data ?

**Comment by Sims24** [comment]
Hi @hdep, 

A snmpwalk would be perfect. Send it by mail if something not public might appear.

Thx !

**Comment by hdep** [comment]
Yes sure. Where should I sent it ?

**Comment by Sims24** [comment]
Hi @hdep , 

Great, send it to sbomm@centreon.com plz.

If you  can use following command and send the file it would be perfect : 

snmpwalk -Cc -v2c -c public -ObentU X.X.X.X .1 > checkpoint_MODEL.snmpwalk

Regards,

**Comment by hdep** [comment]
I just send the snmpwalk.

**Comment by Sims24** [comment]
Hello got it thanks we'll come back to you asap but missing some time ... !

**Comment by Sims24** [comment]
Hello @hdep ,

Just answer to your email to get some additionnal informations,

Regards

**Comment by Sims24** [comment]
After looking at the mib we only have the state of the node, not aware of the other.

I'll add an option like --[warning|critical]-role "%{role} !~ /standby/"  to trigger an error when the failover occurs.

**Comment by Sims24** [comment]
Hi @hdep 
Thanks for your help,

Closed https://github.com/centreon/centreon-plugins/pull/551
