### ISSUE TITLE
netapp mode filesys pourcentage, --filter-type='aggregate' -678.49 GB (-115.71%)

### ISSUE THREAD

**Issue by lzmarouane** [centreon/centreon-plugins#3741]
Hello,

With the plugin "centreon-plugin-Hardware-Storage-Netapp-Ontap-Snmp-20210915-070550.el7.centos.noarch" the ouput display a usage pourcentage of more than 100%:

`/usr/lib/centreon/plugins/centreon_netapp.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname=netapp ip --filter-type='aggregate' --snmp-version=1 --filter-name="^()(*)[0-9]$" --warning-usage=90 --critical-usage=95 --verbose --snmp-community="public"`

`**CRITICAL: Filesys 'aggr0_parnetapp02_02' Total: 159.89 GB Used: 154.16 GB (96.42%) Free: 5.73 GB (3.58%) - Filesys 'parnetapp02_02_SSD_1' Total: 586.37 GB Used: 1.43 TB (249.65%) Free: 0.00 B (0.00%) - Filesys 'parnetapp02_01_SSD_1' Total: 586.37 GB Used: -678.49 GB (-115.71%) Free: 1.24 TB (215.71%) - Filesys 'aggr0_parnetapp02_01' Total: 159.89 GB Used: 154.16 GB (96.42%) Free: 5.73 GB (3.58%) | 'used_aggr0_parnetapp02_02'=165525905408B;0:154507703500;0:163091464806;0;171675226112 'inodes_aggr0_parnetapp02_02'=0%;;;0;100 'compresssaved_aggr0_parnetapp02_02'=0%;;;0;100 'dedupsaved_aggr0_parnetapp02_02'=0%;;;0;100 'used_parnetapp02_02_SSD_1'=1571818360832B;0:566649815040;0:598130360320;0;629610905600 'inodes_parnetapp02_02_SSD_1'=0%;;;0;100 'compresssaved_parnetapp02_02_SSD_1'=0%;;;0;100 'dedupsaved_parnetapp02_02_SSD_1'=6%;;;0;100 'used_parnetapp02_01_SSD_1'=-728525934592B;0:566649815040;0:598130360320;0;629610905600 'inodes_parnetapp02_01_SSD_1'=0%;;;0;100 'compresssaved_parnetapp02_01_SSD_1'=0%;;;0;100 'dedupsaved_parnetapp02_01_SSD_1'=8%;;;0;100 'used_aggr0_parnetapp02_01'=165525901312B;0:154507703500;0:163091464806;0;171675226112 'inodes_aggr0_parnetapp02_01'=0%;;;0;100 'compresssaved_aggr0_parnetapp02_01'=0%;;;0;100 'dedupsaved_aggr0_parnetapp02_01'=0%;;;0;100**`

**Comment by lzmarouane** [comment]
I sent it by e-mail

**Comment by lzmarouane** [comment]
but when i use the snmp verson 2 i get `UNKNOWN: SNMP Table Request : Timeout`

**Comment by garnier-quentin** [comment]
Try the following option: ```--snmp-force-getnext --subset-leef=20 --subsettable=1```

**Comment by lzmarouane** [comment]
i got this error : `Unknown option: subset-leef at /usr/lib/centreon/plugins/centreon_netapp.pl line 141.`

**Comment by garnier-quentin** [comment]
Sorry it's ```--subsetleef=20```

**Comment by lzmarouane** [comment]
Thanks @garnier-quentin, it worked.
