### ISSUE TITLE
Airespace users by AP

### ISSUE THREAD

**Issue by niclem** [centreon/centreon-plugins#375]
Quentin,
Cisco WLC is able to get number of clients associated by access point. I'd like to add this feature on this airespace plugin (centreon::common::airespace::snmp::mode) with warning and critical check on number of associated users per AP. What the best approach ? Where should I code it (new mode or add to the ap-status mode ?).

**Comment by garnier-quentin** [comment]
I don't understand. You have tested the option: --warning-total-associated and --critical-total-associated ?

**Comment by niclem** [comment]
--mode ap-status --warning-total-associated  and --mode ap-users --warning-total-associated seem to retrieve respectively total of accesses point and total of users on the controler.

Now I'd like to know how many users are associated to each access point which a critical/warning threshold.

Example : 
perl centreon_plugins.pl --plugin network::cisco::wlc::snmp::plugin  --snmp-version 2c --snmp-community ...  --hostname IP  --mode ap-users **--critical-byap=50** --debug

OK: Total Users : 141, Total Idle Users : 0, Total AaaPending Users : 0, Total Authenticated Users : 0, Total AaaPending Users : 0, Total Powersave Users : 0, Total Disassociated Users : 0, Total ToBeDeleted Users : 0, Total Probing Users : 0, Total Blacklisted Users : 0 - All users by SSID are ok | 'total'=141users;;;0; 'total_idle'=0users;;;0; 'total_aaapending'=0users;;;0; 'total_authenticated'=0users;;;0; 'total_aaapending'=0users;;;0; 'total_powersave'=0users;;;0; 'total_disassociated'=0users;;;0; 'total_tobedeleted'=0users;;;0; 'total_probing'=0users;;;0; 'total_blacklisted'=0users;;;0; 'ssid_1'=39users;;;0; 'ssid_2'=2users;;;0; 'ssid_3'=100users;;;0; 
**'ap_ap1'=2users;;0:50;0; 'ap_ap2'=23users;;0:50;0; **

Model: AIR-CT5508-K9
SSID 'eduroam' users : 39
SSID 'telephone' users : 2
SSID 'uha' users : 100
**AP 'ap1' users : 2
AP 'ap2' users : 23**

what the best approach ?

**Comment by nogomes** [comment]
Hi

In our office, to achieve this, we were based on this guys's script (which can be found in exchange.nagios.org)
http://awesomeadmin.blogspot.fr/2009/11/monitoring-cisco-wireless-controller.html


Number of clients by AP can be found on this leaf : 

1.3.6.1.4.1.14179.2.2.13.1.4.<AP_Radio_mac_address_Base10>.0
and
1.3.6.1.4.1.14179.2.2.13.1.4.<AP_Radio_mac_address_Base10>.1

According to the above blog, each AP has two OIDs. One ending with ".0" other with ".1".
That's because the APs can work in one of two modes: a/h or b/g/n.

If we make the sum of the 2 values, we get the same value than the one displayed in our controllers for the number of clients by AP.

The blog is quite old but it works in our context. 

We have some random cases where the OID contains a '1' value whereas the are no clients connected on the AP.


I can't say what happens if an AP has other modes, maybe there would be a .2 or .3 ?
Also, it works on a 5508 WLC Controller and don't know if this is the same with other models.

Here, we use it as a Service check in each of our AP, and the arguments are the "Base Radio MAC" of the AP, that needs to be converted in Base10 to get the correct OID.

You can do a snmpwalk on 1.3.6.1.4.1.14179.2.2.13.1.4 to see what it contains


Maybe it can help ?

Regards

Norbert

**Comment by garnier-quentin** [comment]
I begin to understand. Need to add the number of users by AP. I'll need a snmpwalk.

**Comment by nogomes** [comment]
Here is an snmpwalk on 1.3.6.1.4.1.14179.2.2.13.1.4 :

.1.3.6.1.4.1.14179.2.2.13.1.4.200.0.132.34.49.64.0 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.200.0.132.34.49.64.1 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.69.16.0 = INTEGER: 5
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.69.16.1 = INTEGER: 4
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.70.64.0 = INTEGER: 2
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.70.64.1 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.82.64.0 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.82.64.1 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.91.160.0 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.91.160.1 = INTEGER: 2
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.93.0.0 = INTEGER: 0
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.93.0.1 = INTEGER: 0
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.3.16.0 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.3.16.1 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.23.32.0 = INTEGER: 3
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.23.32.1 = INTEGER: 1
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.179.240.0 = INTEGER: 15
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.179.240.1 = INTEGER: 2
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.190.160.0 = INTEGER: 3
.1.3.6.1.4.1.14179.2.2.13.1.4.224.209.115.26.190.160.1 = INTEGER: 1

**Comment by garnier-quentin** [comment]
If i understand, for the following AP, there are 9 users ? 

.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.69.16.0 = INTEGER: 5
.1.3.6.1.4.1.14179.2.2.13.1.4.224.137.157.90.69.16.1 = INTEGER: 4

Could you give the walk of 1.3.6.1.4.1.14179.2.2.1.1.3 and 1.3.6.1.4.1.14179.2.2.1.1.33 ?

**Comment by nogomes** [comment]
Yes there are 9 users on this AP

Here is the snmpwalk (truncated) :

.1.3.6.1.4.1.14179.2.2.1.1.3.224.137.157.90.69.16 = STRING: "AP_NAME"
.1.3.6.1.4.1.14179.2.2.1.1.33.224.137.157.90.69.16 = Hex-STRING: A0 EC F9 31 A5 60 

The 1st contains all the AP Names, the 2nd all the AP Mac Addresses (not the Base Radio MAC)

**Comment by garnier-quentin** [comment]
Could you test it please ?

**Comment by nogomes** [comment]
It seems to be wrong

When I execute this command : 

perl centreon_plugins.pl --plugin=network::cisco::wlc::snmp::plugin --mode=ap-users --hostname=**my_wlc_ip** --snmp-community=**my_community**  --verbose --filter-ap="**my_ap_name**"

It gives me the same results than if I don't specify an AP name (the 350 number is all the users on the controller)

OK: Total Users : 350, Total Idle Users : 0, Total AaaPending Users : 0, Total Authenticated Users : 0, Total AaaPending Users : 0, Total Powersave Users : 0, Total Disassociated Users : 2, Total ToBeDeleted Users : 1, Total Probing Users : 0, Total Blacklisted Users : 0 - All users by SSID are ok - All users by AP are ok | 'total'=350users;;;0; 'total_idle'=0users;;;0; 'total_aaapending'=0users;;;0; 'total_authenticated'=0users;;;0; 'total_aaapending'=0users;;;0; 'total_powersave'=0users;;;0; 'total_disassociated'=2users;;;0; 'total_tobedeleted'=1users;;;0; 'total_probing'=0users;;;0; 'total_blacklisted'=0users;;;0; 'ssid_my_ssid1'=0users;;;0; 'ssid_my_ssid2'=51users;;;0; 'ssid_my_ssid3'=118users;;;0; 'ssid_my_ssid4'=133users;;;0; 'ssid_my_ssid5'=48users;;;0;
Model: AIR-CT5508-K9
SSID 'my_ssid1' users : 0
SSID 'my_ssid2' users : 51
SSID 'my_ssid3' users : 118
SSID 'my_ssid4' users : 133
SSID 'my_ssid5' users : 48

I didn't have looked in details at your code for the modifications you made, but I'll try to give it a look later

**Comment by garnier-quentin** [comment]
Option filter-ap doesn't filter the total result. I don't have information about the type of users by ap. 
Could you use the --debug option ? Because it should have a line for your ap.

**Comment by nogomes** [comment]
Hi

I tried with the --debug option, but I have nothing additional

Here is what our script does : 

- arguments are "Base radio MAC" of the AP
- it converts it in Base10
- it retrieves **1.3.6.1.4.1.14179.2.2.13.1.4.**_AP_Radio_mac_address_Base10_**.0** and **1.3.6.1.4.1.14179.2.2.13.1.4.**_AP_Radio_mac_address_Base10_**.1**
- the number of the clients on the AP is the sum of the 2 values

It works in our 5508 WLC controller, don't know if others work like this

**Comment by niclem** [comment]
Thanks for the add

I see two mistakes in  centreon/common/airespace/snmp/mode/apusers.pm
           
204:my $oid_bsnAPName = '.1.3.6.1.4.1.14179.2.2.1.1.3';     # space after .3
269:$self->{ap}->{$instance}->{total} += $self->{results}->{$oid_bsnAPIfLoadNumOfClients}->{$oid2}; missing ->{total};

**Comment by garnier-quentin** [comment]
Completely right! Thanks! (fixed)
