### ISSUE TITLE
Weblogic: new plugin without Jolokia/JMX

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3755]
It should be nice to have a direct Weblogic monitoring (without Jolokia).

To monitor Weblogic servers status you can use this URL: /management/wls/latest/servers
https://docs.oracle.com/middleware/1213/wls/WLRMR/management_wls_version_servers.htm#WLRMR234

You can find a curl output example here:
[curl_BIpub_porta7206.txt](https://github.com/centreon/centreon-plugins/files/8990283/curl_BIpub_porta7206.txt)

It should be nice to have:

- list-servers (links)
- state
- activeHttpSessionCount
- processor load
- activeThreadCount
- health
- memory

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md)).

Thank you for your understanding.
