### ISSUE TITLE
[apps::protocols::snmp::plugin] --mode=string-value: %{details_critical} not working - timeout

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3756]
`./centreon_plugins.pl --hostname=x.x.x.x --snmp-community='public' --snmp-version=2c --snmp-username= --snmp-timeout= --authpassphrase= --authprotocol= --privpassphrase= --privprotocol= --plugin=apps::protocols::snmp::plugin --mode=string-value  --oid='.1.3.6.1.4.1.10297.101.1.5.1.1.11.1.1'  --warning-regexp='^((?!on|off).)*$'  --critical-regexp='^off$'  --map-values='0=>on,1=>off'  --format-ok='current value is: %{details_ok}'  --format-details-warning='current value is: %{details_warning}'  --format-details-critical='current value is: %{details_critical}'`

using the variable %{details_critical} the plugin is not working -> timeout without any error

**Comment by garnier-quentin** [comment]
I have fixed the infinite loop. Nevertheless, you don't use the right options. Please use:
```
--format-warning='current value is: %{details_warning}' --format-critical='current value is: %{details_critical}'
```
