### ISSUE TITLE
Performance statistics Dell Powerstore Check

### ISSUE THREAD

**Issue by Hbitvof** [centreon/centreon-plugins#3757]
Hi,

Is it possible to add performance statistics to the Dell Powerstore check? Kind of the same as on the Dell Powervault checks.
The most important part for us are latency statistics.

**Comment by Hbitvof** [comment]
For the Dell Powervault there is a controller statistics component and a volume statistics component. I would like to see the same for the Powerstore check, so not only performance data, but also checks on these data if everything is OK. So for example when there is too much latency we get an alert.

The API can provide all these data, when kind of input can I provide? Can I provide this private?

**Comment by Sims24** [comment]
Yes you can send it directly to: 

- sbomm@centreon.com 

Thanks

**Comment by garnier-quentin** [comment]
@Hbitvof could you give me the units for the following values ? (latency an bandwitdth)
```
"avg_write_latency": 381.44846,
"avg_read_bandwidth": 55678444,
```

**Comment by Hbitvof** [comment]
> @Hbitvof could you give me the units for the following values ? (latency an bandwitdth)
> 
> ```
> "avg_write_latency": 381.44846,
> "avg_read_bandwidth": 55678444,
> ```

Following the documentation that's:
latency in microseconds
bytes per second

**Comment by garnier-quentin** [comment]
Thanks. It will be available thursday

**Comment by garnier-quentin** [comment]
Could you test with that version ? https://github.com/centreon/centreon-plugins/archive/refs/heads/MON-14466-powerstore-performance.zip

**Comment by Hbitvof** [comment]
> Could you test with that version ? https://github.com/centreon/centreon-plugins/archive/refs/heads/MON-14466-powerstore-performance.zip

Yes I can. What part is changed so I know how what commands I need to run?

**Comment by Sims24** [comment]
@Hbitvof with sources above, try the new --plugin=storage::dell::powerstore::restapi::plugin --mode=clusters that should answer to your request.

**Comment by Hbitvof** [comment]
> @Hbitvof with sources above, try the new --plugin=storage::dell::powerstore::restapi::plugin --mode=clusters that should answer to your request.

I get the following output when running the new part:

![image](https://user-images.githubusercontent.com/41229269/183394466-5fa590bb-c4f3-4e98-b064-6ab6fb221311.png)

**Comment by garnier-quentin** [comment]
could you provide the --debug result ?

**Comment by Hbitvof** [comment]
> could you provide the --debug result ?

![afbeelding](https://user-images.githubusercontent.com/41229269/183401687-557cf11e-6d9e-4a80-926e-ec02a77eb091.png)

**Comment by garnier-quentin** [comment]
It's weird. Other modes are working ? The curl command is working with endpoint: ```/api/rest/cluster``` ?

**Comment by Hbitvof** [comment]
> It's weird. Other modes are working ? The curl command is working with endpoint: `/api/rest/cluster` ?

Apologies, I did something wrong. I tried it again with the right commandline and I get:

UNKNOWN: 405 Method Not Allowed

**Comment by garnier-quentin** [comment]
Could you provide the --debug ?

**Comment by Hbitvof** [comment]
> Could you provide the --debug ?

![afbeelding](https://user-images.githubusercontent.com/41229269/184109702-cd314146-73c7-4f8f-8dd8-9a5a189cc8d3.png)

**Comment by Hbitvof** [comment]
I think I know what the problem is. Method should be POST instead of GET for /api/rest/metrics/generate

**Comment by garnier-quentin** [comment]
Could you redownload it and test it ? (i have done a patch)

**Comment by Hbitvof** [comment]
> Could you redownload it and test it ? (i have done a patch)

Can you provide a download link again? I just downloaded it again from  https://github.com/centreon/centreon-plugins/archive/refs/heads/MON-14466-powerstore-performance.zip but got the same error.

**Comment by garnier-quentin** [comment]
It's the good link:
```
https://github.com/centreon/centreon-plugins/archive/refs/heads/MON-14466-powerstore-performance.zip
```

Could you provide the --debug ? (it should be a POST).

**Comment by Hbitvof** [comment]
I get another error now:

![afbeelding](https://user-images.githubusercontent.com/41229269/184161637-fce91ddd-4fe2-43eb-ae27-34243ae9b107.png)

**Comment by garnier-quentin** [comment]
It's better :) You can redownload it and retest it ? (i have a done a new patch)

**Comment by Hbitvof** [comment]
The check is working now!

I only see some strange output in the performance data:

![afbeelding](https://user-images.githubusercontent.com/41229269/184595357-cdbd4eaf-c54d-4df2-b2b2-973a6a6b3665.png)

How can I set warning/critical thresholds for this check?

**Comment by garnier-quentin** [comment]
I have removed the microseconds units. Thresholds are in the help:
```
=item B<--warning-*> B<--critical-*>

Thresholds.
Can be: 'clusters-detected',
'read-iops-5m', 'read-iops-30m', 'read-iops-1h', 'read-iops-24h',
'write-iops-5m', 'write-iops-30m', 'write-iops-1h', 'write-iops-24h',
'read-latency-5m', 'read-latency-30m', 'read-latency-1h', 'read-latency-24h',
'write-latency-5m', 'write-latency-30m', 'write-latency-1h', 'write-latency-24h',
'read-bandwidth-5m', 'read-bandwidth-30m', 'read-bandwidth-1h', 'read-bandwidth-24h',
'write-bandwidth-5m', 'write-bandwidth-30m', 'write-bandwidth-1h', 'write-bandwidth-24h'.
```

**Comment by Hbitvof** [comment]
> I have removed the microseconds units. Thresholds are in the help:
> 
> ```
> =item B<--warning-*> B<--critical-*>
> 
> Thresholds.
> Can be: 'clusters-detected',
> 'read-iops-5m', 'read-iops-30m', 'read-iops-1h', 'read-iops-24h',
> 'write-iops-5m', 'write-iops-30m', 'write-iops-1h', 'write-iops-24h',
> 'read-latency-5m', 'read-latency-30m', 'read-latency-1h', 'read-latency-24h',
> 'write-latency-5m', 'write-latency-30m', 'write-latency-1h', 'write-latency-24h',
> 'read-bandwidth-5m', 'read-bandwidth-30m', 'read-bandwidth-1h', 'read-bandwidth-24h',
> 'write-bandwidth-5m', 'write-bandwidth-30m', 'write-bandwidth-1h', 'write-bandwidth-24h'.
> ```

Thanks for your quick actions!

Is it possible to convert the microsecond units to miliseconds? That's more common in storage performance counters.

**Comment by garnier-quentin** [comment]
Yes i will update it

**Comment by garnier-quentin** [comment]
It's merged!

**Comment by garnier-quentin** [comment]
It should be done: https://github.com/centreon/centreon-plugins/pull/3838/files#diff-29f6c085963d5cf9ad2e222b9f080ad492476c4896ff21e13175e29cc8e9b351R227

**Comment by Hbitvof** [comment]
> It should be done: https://github.com/centreon/centreon-plugins/pull/3838/files#diff-29f6c085963d5cf9ad2e222b9f080ad492476c4896ff21e13175e29cc8e9b351R227

Well, it doesn't seem to work (we don't have this latency on our storage :)):

![image](https://user-images.githubusercontent.com/41229269/185857680-fdba2785-58b3-435f-9af9-650da3f1d4ed.png)

**Comment by garnier-quentin** [comment]
My bad. It should be ok now with the last version :)

**Comment by Hbitvof** [comment]
> My bad. It should be ok now with the last version :)

Can you provide the newest version? The link is not working anymore.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip

**Comment by Hbitvof** [comment]
> https://github.com/centreon/centreon-plugins/archive/refs/heads/master.zip

Awesome, the output is correct now!
