### ISSUE TITLE
[snmp_standard] plugin.pm Missing modes

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#376]
Hello, Quentin
In the file there are no "modes" of the directory modes. So it should be?

plugin.pm:
'numeric-value'      => 'snmp_standard::mode::numericvalue',
'string-value'       => 'snmp_standard::mode::stringvalue',
'dynamic-command'    => 'snmp_standard::mode::dynamiccommand',
'uptime'             => 'snmp_standard::mode::uptime',

For example how to use the interface mode?

**Comment by garnier-quentin** [comment]
The interface is linked in other plugin directly: like cisco, linux, ...
