### ISSUE TITLE
[network::fortinet::fortigate::plugin] mode=sdwan

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#3760]
Hello,

Is it possible to exclude traffic in the output from this mode ?
I know how to exclude perfdata but not for the output.

Here is the output :
OK: All sd-wan links are ok
checking sd-wan 'W1_TunA' [vdom: WAN] [interface: W1_TunA]
state: up
traffic in: 0.00 b/s, out: 3.32 Gb/s, bi: 6.64 Gb/s
latency: 2.819ms
jitter: 0.052ms
packet loss: 0.000%
checking sd-wan 'W1_TunB' [vdom: WAN] [interface: W1_TunB]
state: up
traffic in: 0.00 b/s, out: 0.00 b/s, bi: 0.00 b/s
latency: 1.131ms
jitter: 0.022ms
packet loss: 0.000%

But traffic is not really traffic :
gVWLHealthCheckLinkBandwidthIn | gVWLHealthCheckLinkBandwidthOut | gVWLHealthCheckLinkBandwidthBi : 
The available bandwidth of incoming | outgoing | bi-direction traffic detected by a health check on a specific member link, in Mbps.

In real, values are very strange and means nothing ... or everything but not traffic : it is an estimated available bandwidth !

Traffic have to be checked with the classic "interface" mode on these interface.

**Comment by ritouret** [comment]
Yes, you can.
If someone asked you these specific oid, you should add an option like --add-estimated-available-bandwidth.

**Comment by garnier-quentin** [comment]
You can remove that counter with option: ```--filter-counters```

**Comment by ritouret** [comment]
Thank you Quentin,

I used this option :
--filter-counters='^(?!(traffic.*)$)'

For this result :
checking sd-wan 'W1_TunA' [vdom: WAN] [interface: W1_TunA]
    state: up
    latency: 109.392ms
    jitter: 6.333ms
    packet loss: 0.000%
checking sd-wan 'W1_TunB' [vdom: WAN] [interface: W1_TunB]
    state: up
    latency: 114.158ms
    jitter: 6.467ms
    packet loss: 1.000%
