### ISSUE TITLE
Windows Service Status SNMP 

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon-plugins#3761]
Hi I am trying to get whether a specific service is running or not using windows snmp plugin. 
Currently I can see the operating of the services as "Active" 

like this :
[name = Windows Security Service] [operating = active] [installed = installed]
[name = Workstation] [operating = active] [installed = installed]
[name = postgresql-x64-11 - PostgreSQL Server 11] [operating = active] [installed = installed]

My issue is when one of the services go down. This plugin shows as critical?  I cannot see any non active services in list-services.
And when I add a wrong service name to --service. The plugin still output All services are ok. 

Command :
 /usr/lib/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=xxx --snmp-version='2c' --snmp-community='xxx'  --service="Workstation" 

Output : 
OK: All service states are ok 

Thank You!

**Comment by lchrdn** [comment]
Hi
You need to add a threshold to trigger an alert. Can you try with adding `--critical=1:` and also `--verbose` could give you more details

**Comment by VidushaZ** [comment]
@lchrdn Thanx. It's working as expected now.
