### ISSUE TITLE
Cannot save plugins requirements of Plugin Pack centreon-plugin-Operatingsystems-Linux-Snmp

### ISSUE THREAD

**Issue by uc33260** [centreon/centreon-plugins#3762]
Hello,

I cannot install the LINUX SNMP plugin on Centreon 22.04.

![0006_30-06-2022_15 55 18](https://user-images.githubusercontent.com/83720227/176695980-147c2e45-97f1-4689-b511-0f7b0d111f47.png)

Thank you for help

**Comment by Sims24** [comment]
Hi, 

Please update your modules in the Administration > Extensions > Manager page and try again.
