### ISSUE TITLE
[apps::monitoring::speedtest::plugin] Bandwidth results not used by Icinga2

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#3765]
Hi,

I´m using the apps::monitoring::speedtest::plugin which runs great, but the perf data aren´t fully intepreted by icinga2 and I don´t know why. This is my icinga2 command definition:

```shell
object CheckCommand "centreon-speedtest" {
   import "plugin-check-command"

   command = [ "/home/nagios/centreon-plugins/centreon_plugins.pl" ]
   arguments = {
        "--plugin" = "apps::monitoring::speedtest::plugin"
        "--mode" = "internet-bandwidth"
        "--warning-bandwidth-download" = "$warn_download$"
        "--critical-bandwidth-download" = "$crit_download$"
        "--warning-bandwidth-upload" = "$warn_upload$"
        "--critical-bandwidth-upload" = "$crit_upload$"
        "--range-perfdata" = "1"
        }
}
```

I´ve attached a screenshot from icingaweb2, where you can see, that only ping time is interpreted (value & graph). Any idea, what could be wrong here? The result from console looks fine:

`OK: speedtest ping time: 11 ms, download: 77.57 Mb/s, upload: 65.98 Mb/s | 'ping.time.milliseconds'=11.098ms;;;0; 'internet.bandwidth.download.bitspersecond'=77568094b/s;;;0; 'internet.bandwidth.upload.bitspersecond'=65976542b/s;;;0;
`

![2022-07-05_07h21_27](https://user-images.githubusercontent.com/4061954/177255601-a42dc98d-09b4-4c01-869c-9e0f0b896913.png)

**Comment by Sims24** [comment]
Hi, 

Everything looks OK on the centreon-plugins' side. 

 Maybe the string is too long? or maybe it doesn't like the b/s? Can you try to add --filter-uom=ms just to check if it's better. It's strange I'm not familiar with Incinga2 but looks like it succeeds in detecting the warning and critical so it actually processes *download* metrics.

**Comment by benhartwich** [comment]
OK, thanks that worked so far. Now I will have to solve why no new graphite graphs are created.

**Comment by garnier-quentin** [comment]
Thanks for the feedback @benhartwich . If you have still an issue with the plugin, you can comment it.

**Comment by benhartwich** [comment]
Yes, it seems that my graphite graphs are only generated for ping time, not for the both internet speeds. I don´t know, why this happens exactly, because they are automatically generated by perf values. Do you have any clue?

**Comment by garnier-quentin** [comment]
What is your output ? It's a long time for graphite. Maybe i could find something (but i'm not sure).

**Comment by benhartwich** [comment]
On command line I get: 
`OK: speedtest ping time: 12 ms, download: 70.38 Mb/s, upload: 59.74 Mb/s | 'ping.time.milliseconds'=12.738ms;;;0; 'internet.bandwidth.download.bitspersecond'=70378258;;;0; 'internet.bandwidth.upload.bitspersecond'=59736763;;;0;`

This is my command: `perl centreon_plugins.pl --plugin=apps::monitoring::speedtest::plugin --mode=internet-bandwidth --filter-uom=ms`

I´ve attached a screenshot - the service is running for about 5 days every hour, so their should be enough data values.
![2022-07-11_12h01_30](https://user-images.githubusercontent.com/4061954/178240050-024c2d62-07e5-4f89-a3be-d20c8d3b2cfa.png)

**Comment by garnier-quentin** [comment]
Maybe it comes from thresholds with the ':' ?

**Comment by benhartwich** [comment]
Range-perfdata is already activated. The : indicates a warning / critical threshold below the value - seems to be icinga standard. I´ve temporarely disabled the : but nothing changed, while executing it manually three times.

**Comment by benhartwich** [comment]
I looked a little further - graphite seems to generate the graphs - perhaps it´s because there is a subfolder structure which is not recognized by icinga (instead of having internet => bandwidth, perhaps only bandwidth would work)?
![2022-07-11_13h01_26](https://user-images.githubusercontent.com/4061954/178250987-7da88113-5ec4-4c18-b6b3-3291448f551c.png)
