### ISSUE TITLE
Question on os::windows::snmp::plugin --mode=interfaces

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#377]
Hello,

When we execute the following command, we can see the traffic of all the interfaces:
The interfaces are displayed with their interface name, is it possible to display them all with their interface "id" instead of "name" ?

centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=interfaces --hostname=x.x.x.x --snmp-version=2c --snmp-community=xx--interface='' --name --add-status --add-traffic

Instead of having:
Interface 'tunnel_1' Status : down (admin: up) - Interface 'tunnel_5' [...]
'traffic_in_ethernet_6'=305689.61b/s;;;0;1000000000 'traffic_out_ethernet_6'=30008.43b/s;;;0;1000000000 
'traffic_in_ethernet_ [...]

Is it possible to display this:
interface '1' Status : down (admin: up)- Interface '2' [...]
'traffic_in_1'=305689.61b/s;;;0;1000000000 
'traffic_out_1'=30008.43b/s;;;0;1000000000 
'traffic_in_2 [...]

I know we can filter several interfaces with their id, but i would like to know if it possible to have all the interfaces named by their id and not their name.

Regards

**Comment by garnier-quentin** [comment]
No you cannot display it by the ID. You can use ifalias, ifdesc, ifname.
