### ISSUE TITLE
Powerstore Alert Check Bad Request since update DSA-2022-159

### ISSUE THREAD

**Issue by Hbitvof** [centreon/centreon-plugins#3770]
Since update DSA-2022-159 (https://www.dell.com/support/kbdoc/nl-nl/000201283/dsa-2022-159-dell-powerstore-family-security-update-for-multiple-vulnerabilities) of our Powerstores we get UNKNOWN: 400 Bad Request as result for the alerts check:

![afbeelding](https://user-images.githubusercontent.com/41229269/178229597-5a2c07bc-74a9-4ae9-bbca-4a6cee6cab1a.png)

Can you provide a fix for this?

**Comment by garnier-quentin** [comment]
I need more informations about the issue.

**Comment by garnier-quentin** [comment]
Could you provide the --debug result ? And a curl example working

**Comment by Hbitvof** [comment]
Here is the debug output:

![afbeelding](https://user-images.githubusercontent.com/41229269/178254183-49a86b3c-2b36-4983-b65a-552a66ff2590.png)


I don't have a curl example, what do I need to do to provide this?

**Comment by garnier-quentin** [comment]
```Alert.name``` doesn't exist anymore ?

**Comment by garnier-quentin** [comment]
It's the following command:
```
curl -k -u 'username:password' 'https://DC1POWERSTORE02.ZORGNET.ORG/api/rest/alert?select=id,name,severity,state,is_acknowledged,resource_name,generated_timestamp'
```

**Comment by Hbitvof** [comment]
> It's the following command:
> 
> ```
> curl -k -u 'username:password' 'https://DC1POWERSTORE02.ZORGNET.ORG/api/rest/alert?select=id,name,severity,state,is_acknowledged,resource_name,generated_timestamp'
> ```

When I query for name I get: 
{"messages":[{"code":"0xE0404003000A","severity":"Error","message_l10n":"The REST property [alert.name] cannot be found.","arguments":["[alert.name]"]}]}

When I just query without parameter I get:

![afbeelding](https://user-images.githubusercontent.com/41229269/178432224-ebc0da65-8857-4029-a4f9-28ab838d6b97.png)

**Comment by Hbitvof** [comment]
> So could you remove the name ? Is it working with the following syntax:
> 
> ```
> curl -k -u 'username:password' 'https://DC1POWERSTORE02.ZORGNET.ORG/api/rest/alert?select=*'
> ```

That query is giving all results. When I run the following query I get also results:

curl -k -u 'username:password' 'https://DC1POWERSTORE02.ZORGNET.ORG/api/rest/alert?select="name"'

**Comment by garnier-quentin** [comment]
Could you provide query results ?

**Comment by Hbitvof** [comment]
Here is an example of the select=* result:

{"id":"ab505043-31e3-427b-a8e8-ac8a4c89bece","event_code":"0x00304401","severity":"Info","resource_type":"hardware","resource_id":"96ebecfc9de34931bc45bb6d88b87c02","resource_name":"BaseEnclosure-NodeA","description_l10n":"The node lifecycle state has changed from Disconnected to Healthy.","generated_timestamp":"2022-07-08T11:31:30.31107+00:00","state":"CLEARED","is_acknowledged":false,"raised_timestamp":"2022-07-08T10:40:05.760547+00:00","cleared_timestamp":"2022-07-08T11:31:30.31107+00:00","called_home_timestamp":null,"email_sent_timestamp":null,"snmp_sent_timestamp":null,"acknowledged_timestamp":null,"events":[{"id": "0368e9d7-c1f6-e450-8c61-fd8cc62d70f3", "name": "XMS_NODE_FRU_STATE_HEALTHY", "severity": "Info", "event_code": "0x00304401", "title_l10n": "The node lifecycle state has changed. (healthy)", "resource_id": "96ebecfc9de34931bc45bb6d88b87c02", "resource_name": "BaseEnclosure-NodeA", "resource_type": "hardware", "severity_l10n": "Info", "base_event_code": "0x00304400", "base_event_name": "XMS_NODE_FRU_STATE", "node_originator": "UNKNOWN", "description_l10n": "The node lifecycle state has changed from Disconnected to Healthy.", "repair_flow_l10n": null, "system_impact_l10n": null, "generated_timestamp": "2022-07-08T11:31:30.31107+00:00", "appliance_originator": "A1"}, {"id": "260bc18c-51f1-f69f-0ca5-d4f6fd105247", "name": "XMS_NODE_FRU_STATE_DISCONNECTED", "severity": "Major", "event_code": "0x00304404", "title_l10n": "The node lifecycle state has changed. (disconnected)", "resource_id": "96ebecfc9de34931bc45bb6d88b87c02", "resource_name": "BaseEnclosure-NodeA", "resource_type": "hardware", "severity_l10n": "Major", "base_event_code": "0x00304400", "base_event_name": "XMS_NODE_FRU_STATE", "node_originator": "UNKNOWN", "description_l10n": "Node has been physically removed or shut down.", "repair_flow_l10n": "The node is not connected or is in the process of rebooting. Verify that the node is properly connected, or replace the node. Refer to the Installation and Service Guide for information on replacing the component.", "system_impact_l10n": "Data availability and performance may be degraded.", "generated_timestamp": "2022-07-08T10:58:18.043838+00:00", "appliance_originator": "A1"}, {"id": "40381055-551b-bfe1-93a2-da483c090512", "name": "XMS_NODE_FRU_STATE_DISCONNECTED", "severity": "Major", "event_code": "0x00304404", "title_l10n": "The node lifecycle state has changed. (disconnected)", "resource_id": "96ebecfc9de34931bc45bb6d88b87c02", "resource_name": "BaseEnclosure-NodeA", "resource_type": "hardware", "severity_l10n": "Major", "base_event_code": "0x00304400", "base_event_name": "XMS_NODE_FRU_STATE", "node_originator": "UNKNOWN", "description_l10n": "Node has been physically removed or shut down.", "repair_flow_l10n": "The node is not connected or is in the process of rebooting. Verify that the node is properly connected, or replace the node. Refer to the Installation and Service Guide for information on replacing the component.", "system_impact_l10n": "Data availability and performance may be degraded.", "generated_timestamp": "2022-07-08T10:40:05.760547+00:00", "appliance_originator": "A1"}],"severity_l10n":"Info","resource_type_l10n":"hardware","state_l10n":"Cleared"}

**Comment by garnier-quentin** [comment]
Ok i understand. The API response changed. 
Before:
```
[
    {
        "generated_timestamp": "2021-08-30T09:10:45.931+00:00",
        "id": "0503bf7e-e8cb-41e0-b706-575543721520",
        "name": "LICENSE_INSTALL_INSTALL_SUCCEEDED",
        "resource_name": "XXX-X-XXXXXX-CLUSTER",
        "severity": "Info",
        "state": "CLEARED"
    },
   {
        "generated_timestamp": "2021-09-08T08:13:14.804936+00:00",
        "id": "fb4f978e-a242-4a6a-8973-c73900160c10",
        "name": "XMS_JBOD_CONTROLLER_SAS1_HEALTH_LEVEL_LEVEL_1_CLEAR",
        "resource_name": "",
        "severity": "Major",
        "state": "ACTIVE"
    },
    ....
]
```

Now:
```
{
   "id":"ab505043-31e3-427b-a8e8-ac8a4c89bece",
   "event_code":"0x00304401",
   "severity":"Info",
   "resource_type":"hardware",
   "resource_id":"96ebecfc9de34931bc45bb6d88b87c02",
   "resource_name":"BaseEnclosure-NodeA",
   "description_l10n":"The node lifecycle state has changed from Disconnected to Healthy.",
   "generated_timestamp":"2022-07-08T11:31:30.31107+00:00",
   "state":"CLEARED",
   "is_acknowledged":false,
   "raised_timestamp":"2022-07-08T10:40:05.760547+00:00",
   "cleared_timestamp":"2022-07-08T11:31:30.31107+00:00",
   "called_home_timestamp":null,
   "email_sent_timestamp":null,
   "snmp_sent_timestamp":null,
   "acknowledged_timestamp":null,
   "events":[
      {
         "id":"0368e9d7-c1f6-e450-8c61-fd8cc62d70f3",
         "name":"XMS_NODE_FRU_STATE_HEALTHY",
         "severity":"Info",
         "event_code":"0x00304401",
         "title_l10n":"The node lifecycle state has changed. (healthy)",
         "resource_id":"96ebecfc9de34931bc45bb6d88b87c02",
         "resource_name":"BaseEnclosure-NodeA",
         "resource_type":"hardware",
         "severity_l10n":"Info",
         "base_event_code":"0x00304400",
         "base_event_name":"XMS_NODE_FRU_STATE",
         "node_originator":"UNKNOWN",
         "description_l10n":"The node lifecycle state has changed from Disconnected to Healthy.",
         "repair_flow_l10n":null,
         "system_impact_l10n":null,
         "generated_timestamp":"2022-07-08T11:31:30.31107+00:00",
         "appliance_originator":"A1"
      },
      {
         "id":"260bc18c-51f1-f69f-0ca5-d4f6fd105247",
         "name":"XMS_NODE_FRU_STATE_DISCONNECTED",
         "severity":"Major",
         "event_code":"0x00304404",
         "title_l10n":"The node lifecycle state has changed. (disconnected)",
         "resource_id":"96ebecfc9de34931bc45bb6d88b87c02",
         "resource_name":"BaseEnclosure-NodeA",
         "resource_type":"hardware",
         "severity_l10n":"Major",
         "base_event_code":"0x00304400",
         "base_event_name":"XMS_NODE_FRU_STATE",
         "node_originator":"UNKNOWN",
         "description_l10n":"Node has been physically removed or shut down.",
         "repair_flow_l10n":"The node is not connected or is in the process of rebooting. Verify that the node is properly connected, or replace the node. Refer to the Installation and Service Guide for information on replacing the component.",
         "system_impact_l10n":"Data availability and performance may be degraded.",
         "generated_timestamp":"2022-07-08T10:58:18.043838+00:00",
         "appliance_originator":"A1"
      },
      {
         "id":"40381055-551b-bfe1-93a2-da483c090512",
         "name":"XMS_NODE_FRU_STATE_DISCONNECTED",
         "severity":"Major",
         "event_code":"0x00304404",
         "title_l10n":"The node lifecycle state has changed. (disconnected)",
         "resource_id":"96ebecfc9de34931bc45bb6d88b87c02",
         "resource_name":"BaseEnclosure-NodeA",
         "resource_type":"hardware",
         "severity_l10n":"Major",
         "base_event_code":"0x00304400",
         "base_event_name":"XMS_NODE_FRU_STATE",
         "node_originator":"UNKNOWN",
         "description_l10n":"Node has been physically removed or shut down.",
         "repair_flow_l10n":"The node is not connected or is in the process of rebooting. Verify that the node is properly connected, or replace the node. Refer to the Installation and Service Guide for information on replacing the component.",
         "system_impact_l10n":"Data availability and performance may be degraded.",
         "generated_timestamp":"2022-07-08T10:40:05.760547+00:00",
         "appliance_originator":"A1"
      }
   ],
   "severity_l10n":"Info",
   "resource_type_l10n":"hardware",
   "state_l10n":"Cleared"
}
```

The name attribute is not present at the top level (it's in events). I don't know if the ```select=*``` is working with old firmware.

**Comment by Hbitvof** [comment]
Ah ok. Is it possible to add this change to the code so the check is working again?

**Comment by Hbitvof** [comment]
Any update on this one?

**Comment by garnier-quentin** [comment]
Could you test with last version ? It should be ok

**Comment by Hbitvof** [comment]
> Could you test with last version ? It should be ok

Problem is solved now, thanks for the change!

**Comment by garnier-quentin** [comment]
thanks for the feedback
