### ISSUE TITLE
Synolgy 7.1 - New Health Status for disks

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#3772]
Hi,
With DSM 7.1, Synology has added an new status on disks, relative to SMART tests.

![image](https://user-images.githubusercontent.com/498115/178264496-7496f472-d548-466b-bad1-7176269c001e.png)

Doc: https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf , Synology Disk MIB chapter.

That would be interesting to get this new status.

Extract from a RS2418+:

.1.3.6.1.4.1.6574.2.1.1.12.0 = STRING: "Drive 1"
.1.3.6.1.4.1.6574.2.1.1.12.1 = STRING: "Drive 2"
.1.3.6.1.4.1.6574.2.1.1.12.2 = STRING: "Drive 3"
.1.3.6.1.4.1.6574.2.1.1.12.3 = STRING: "Drive 4"
.1.3.6.1.4.1.6574.2.1.1.12.4 = STRING: "Drive 5"
.1.3.6.1.4.1.6574.2.1.1.12.5 = STRING: "Drive 6"
.1.3.6.1.4.1.6574.2.1.1.12.6 = STRING: "Drive 7"
.1.3.6.1.4.1.6574.2.1.1.12.7 = STRING: "Drive 8"
.1.3.6.1.4.1.6574.2.1.1.12.8 = STRING: "Drive 9"
.1.3.6.1.4.1.6574.2.1.1.12.9 = STRING: "Drive 10"
.1.3.6.1.4.1.6574.2.1.1.12.10 = STRING: "Drive 11"
.1.3.6.1.4.1.6574.2.1.1.12.11 = STRING: "Drive 12"
.1.3.6.1.4.1.6574.2.1.1.13.0 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.1 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.2 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.3 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.4 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.5 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.6 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.7 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.8 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.9 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.10 = INTEGER: 1
.1.3.6.1.4.1.6574.2.1.1.13.11 = INTEGER: 1

txh
jfr

**Comment by garnier-quentin** [comment]
You can test with last git version: https://github.com/centreon/centreon-plugins/pull/3844
