### ISSUE TITLE
os::linux::local::plugin --mode pending-updates don't do 'apt-get update' before 'apt-get upgrade -sVq'

### ISSUE THREAD

**Issue by klepallec** [centreon/centreon-plugins#3776]
Hello,

I want to check update on Debian 11
This command return 0 updates 
```
./centreon_plugins.pl --plugin os::linux::local::plugin --mode pending-updates --hostname 192.168.10.202 --os-mode debian  --critical-total 0
```

I read the doc and find that the command used by this mode for debian is : apt-get upgrade -sVq
```
For rhel/centos: yum check-update 2>&1 For Debian: apt-get upgrade -sVq
    2>&1 For Suse: zypper list-updates 2>&1
```
I made an apt-get update command and re-run after my centreon_plugins.pl command and now it find package to be update.

Why the mode don't do an apt-get update to check depot before running upgrade command ?
Maybe i have to pass an external update command before using option in ssh ?

Is it normal ?

thx a lot

**Comment by Sims24** [comment]
Hi, 

Thanks for reporting this. We will work on this as the apt-get documentation clearly states that an update should be issued before apt-get upgrade or dist-upgrade

We'll keep you posted about this .

**Comment by garnier-quentin** [comment]
We can add an option like: ```--update```

**Comment by Sims24** [comment]
@klepallec after discussing this with the team, we will probably not implement this as it would require root privileges.

Our advice/workaround would be to add a corn that regularly run an apt get update as root.
