### ISSUE TITLE
Question: How to add Command

### ISSUE THREAD

**Issue by Meistercoach83** [centreon/centreon-plugins#378]
Hi! I´m trying to get my check running in the centreon-webinterface:
The check 

> perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=*** --snmp-version=*** --snmp-community=*** --mode=storage

is working in command line, but not in frontend.There I get an error: "Plugin has to be in : /usr/lib/nagios/plugins"

what am I doing wrong?

**Comment by garnier-quentin** [comment]
Could you give me the command from centreon-web interface ?

**Comment by Meistercoach83** [comment]
of course:

> perl $USER1$/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-public=$_HOSTSNMPCOMMUNITY$

**Comment by garnier-quentin** [comment]
You try to execute it from the webinterface by clicking in the information icon ? (at the right in commande tails). You should not use that.

**Comment by Meistercoach83** [comment]
Ok - but when I install this as a service I´m getting a "(No output returned from plugin)"

**Comment by garnier-quentin** [comment]
Could get the command executed ? Connect on database  'centreon_storage' and to the following sql:
```
SELECT command_line FROM services WHERE command_line like '%mode=processcount%';
```

**Comment by Meistercoach83** [comment]
there´s an result: "/usr/bin/perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname=*** --snmp-version=*** --snmp-public=***"

**Comment by garnier-quentin** [comment]
Adn does that command works with centreon-engine user ? If you use perl connector, please remove it also.

**Comment by Meistercoach83** [comment]
yes, it´s working as expected: OK: Number of current processes running: 54 | 'nbproc'=54;;;0;

**Comment by garnier-quentin** [comment]
So it's ok ? And the connector is disabled ?

**Comment by Meistercoach83** [comment]
you mean in the command definition? i dont use the connector there...

**Comment by garnier-quentin** [comment]
So it's weird. You should send me an email.

**Comment by garnier-quentin** [comment]
I close the issue. You can send me an email. Like that, i could take a look.
