### ISSUE TITLE
network::aruba::aoscx::snmp::plugin  UNKNOWN: SNMP Session: unable to create

### ISSUE THREAD

**Issue by khalidbounoun** [centreon/centreon-plugins#3783]
Hello, 

We are looking to monitor aruba switches CX 6000 series, but it returns the following error:

`UNKNOWN: SNMP Session: unable to create`

It normally corresponds to an snmp 3 authentication error , but we have configured snmp 2c.

I tested with both plugins : network::aruba::aoscx::snmp::plugin and   network::aruba::standard::snmp::plugin

Attached the result of the snmpwalk command
[snmpwalkDNC.txt](https://github.com/centreon/centreon-plugins/files/9190601/snmpwalkDNC.txt)

**Comment by Sims24** [comment]
Hi, 

Could you please paste the exact command resulting in the _unable to create_ error please?

**Comment by khalidbounoun** [comment]
I tried with both commands : 

`bash-4.2$ /usr/lib/centreon/plugins/centreon_aruba_aoscx_snmp.pl --plugin=network::aruba::aoscx::snmp::plugin --mode=vsf --hostname=10.0.0.0 --snmp-version='2c' --snmp-community='mycom' --verbose
UNKNOWN: SNMP Session: unable to create
`

`bash-4.2$ /usr/lib/centreon/plugins/centreon_aruba.pl --plugin=network::aruba::standard::snmp::plugin --mode=cpu --hostname=10.0.0.0 --snmp-version='2c' --snmp-community='mycom'  --warning-utilization='90' --critical-utilization='95'  --verbose
UNKNOWN: SNMP Table Request: Cant get a single value.`

**Comment by Sims24** [comment]
Hi, 

I can't reproduce, are you sure that your IP is correct? I get the unable to create when IP contains a wrong digit. 

Are you using the last version? 

Snippets from my tests below:

```
#/usr/lib/centreon/plugins/centreon_aruba.pl --plugin=network::aruba::standard::snmp::plugin --mode=cpu --hostname=10.0.0.0 --snmp-version='2c' --snmp-community='mycom' --warning-utilization='90' --critical-utilization='95' --verbose

# /usr/lib/centreon/plugins/centreon_aruba.pl --plugin=network::aruba::standard::snmp::plugin --mode=cpu --hostname=10.0.0 --snmp-version='2c' --snmp-community='mycom' --warning-utilizat
ion='90' --critical-utilization='95' --verbose
UNKNOWN: SNMP Table Request: Timeout

# bad IP format
# /usr/lib/centreon/plugins/centreon_aruba.pl --plugin=network::aruba::standard::snmp::plugin --mode=cpu --hostname=10.0.0.289 --snmp-version='2c' --snmp-community='mycom' --warning-util
ization='90' --critical-utilization='95' --verbose
UNKNOWN: SNMP Session: unable to create
```

**Comment by khalidbounoun** [comment]
the address ip in my comment is not my real ip, but in my command I used the correct ip address 
PS: I tested on several switches

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk command AND the centreon-plugins command ?

**Comment by khalidbounoun** [comment]
snmpwalk command : 
`snmpwalk -v2c -c community 10.0.0.0 .1`

Plugin command : 
`/usr/lib/centreon/plugins/centreon_aruba_aoscx_snmp.pl --plugin=network::aruba::aoscx::snmp::plugin --mode=vsx --hostname='10.0.0.0' --snmp-version='2c' --snmp-community='community'  --warning-isl-status='' --critical-isl-status='%{isl_status} =~ /outSync/' --warning-isl-packets-in='' --critical-isl-packets-in='' --warning-isl-packets-out='' --critical-isl-packets-out='' --warning-keepalive-status='' --critical-keepalive-status='%{keepalive_status} =~ /outofSyncEstablished|failed/' --warning-keepalive-packets-in='' --critical-keepalive-packets-in='' --warning-keepalive-packets-out='' --critical-keepalive-packets-out='' --warning-device-status='' --critical-device-status='' --verbose`

**Comment by garnier-quentin** [comment]
Could we do a remote session ? (send me an email)

**Comment by garnier-quentin** [comment]
It was a wrong IP value.
