### ISSUE TITLE
New plugin: Netskope

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#3785]
Hi,
would it be possible to get a plugin for Netskope solution ( https://www.netskope.com/fr/ ) ?

API is available here: https://docs.netskope.com/en/netskope-platform-rest-apis.html

Only both Get Alerts Data and Get Events Data have some interest in monitoring context (discussion open of course).

If you need samples, tell us, we should be able to provide real data.

jfr

**Comment by garnier-quentin** [comment]
Yes. Could you provide curls commands and results please ?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This feature request seems particularly old so let me close it. If the feature request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
