### ISSUE TITLE
network::cisco::standard::snmp::plugin : SNMPv3 with AES192C or AES256C

### ISSUE THREAD

**Issue by R1sCh0** [centreon/centreon-plugins#3789]
Hello, i'm facing a problem using the plugin **network::cisco::standard::snmp::plugin** with SNMPv3.

I need to authenticate in SNMPv3 in authPriv mode with SHA and AES256 but it doesn't work using the centreon plugins.

I did installed net-snmp v5.9.3 with the corrects parameters **--enable-blumenthal-aes** and **--with-openssl** to be sure to enable the AES 192,256 on the snmpget, snmpwalk, snmptable tools.

I am also aware that cisco implemented the **AES-192** and **AES-256** encryption protocols differently from the standard and that we have to use the "**AES-256-C**" and "**AES-192-C**" parameters in order to make it work.

I can do a snmpwalk on an OID using the user configured on my cisco switch:

`snmpwalk -v3 -l authPriv -u lch -a SHA -A 'Test123!' -x AES-256-C -X 'Test123!' 10.X.X.X 1.3.6.1.2.1.1.4`

and i get the correct output: 

> SNMPv2-MIB::sysContact.0 = STRING: TEST

But when i execute the following command using centreon plugins:

`./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=cpu --host=10.X.X.X --snmp-username=lch --authprotocol=SHA --authpassphrase 'Test123!' --privprocotol=AES256C --privpassphrase 'Test123!' --snmp-version=3`

I get this:

> UNKNOWN: SNMP Table Request: Timeout

When I search in debug messages on my cisco switch I get the same kind of errors that I used to have when I was using the AES-256 parameter of the snmpwalk tool. It seems that the centreon plugins doesn't implement AES256C correctly or I'm missing something.

Sample output of debug logs on my cisco switch:

> 000917: *Jul 27 15:18:38.935:
> Incoming SNMP packet
> 000918: *Jul 27 15:18:38.935: v3 packet security model: v3       security level: priv
> 000919: *Jul 27 15:18:38.935: username: lch
> 000920: *Jul 27 15:18:38.935: snmpEngineID: 800000090300C064E4A9E000
> 000921: *Jul 27 15:18:38.935: snmpEngineBoots: 49       snmpEngineTime: 190887
> 000922: *Jul 27 15:18:38.935: SNMP: Response, reqid 1412826959, errstat 0, erridx 0
>  system.5.0 = MYCISCOSWITCH
> 000923: *Jul 27 15:18:38.935: SNMP: Packet sent via UDP to 10.X.X.X
> 000924: *Jul 27 15:24:52.760: SNMP: Packet received via UDP from 10.X.X.X on VlanXXXXSrParseV3SnmpMessage: No matching Engine ID.
> SrParseV3SnmpMessage: Failed.
> SrDoSnmp: authentication failure, Unknown Engine ID
> 
> 000925: *Jul 27 15:24:52.761:
> Incoming SNMP packet
> 000926: *Jul 27 15:24:52.761: v3 packet security model: v3       security level: noauth
> 000927: *Jul 27 15:24:52.761: username:
> 000928: *Jul 27 15:24:52.761: snmpEngineID: 800000090300C064E4A9E000
> 000929: *Jul 27 15:24:52.761: snmpEngineBoots: 0        snmpEngineTime: 0
> 000930: *Jul 27 15:24:52.761: SNMP: Report, reqid 908673912, errstat 0, erridx 0
>  usmStats.4.0 = 74
> 000931: *Jul 27 15:24:52.761: SNMP: Packet sent via UDP to 10.X.X.X
> 000932: *Jul 27 15:24:52.767: SNMP: Packet received via UDP from 10.X.X.X on VlanXXXXno such type in ParseType (27) (0x1B)
> ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
> SrParseV3SnmpMessage: ParseSequence:
> SrParseV3SnmpMessage: Failed.
> SrDoSnmp: ASN Parse Error
> 
> 000933: *Jul 27 15:24:53.769: SNMP: Packet received via UDP from 10.X.X.X on VlanXXXXno such type in ParseType (203) (0xCB)
> ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
> SrParseV3SnmpMessage: ParseSequence:
> SrParseV3SnmpMessage: Failed.
> SrDoSnmp: ASN Parse Error
> 
> 000934: *Jul 27 15:24:54.770: SNMP: Packet received via UDP from 10.X.X.X on VlanXXXXno such type in ParseType (56) (0x38)
> ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
> SrParseV3SnmpMessage: ParseSequence:
> SrParseV3SnmpMessage: Failed.
> SrDoSnmp: ASN Parse Error
> 
> 000935: *Jul 27 15:24:55.771: SNMP: Packet received via UDP from 10.X.X.X on VlanXXXXno such type in ParseType (34) (0x22)
> ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
> SrParseV3SnmpMessage: ParseSequence:
> SrParseV3SnmpMessage: Failed.
> SrDoSnmp: ASN Parse Error
> 
> 000936: *Jul 27 15:24:56.773: SNMP: Packet received via UDP from 10.X.X.X on VlanXXXXParseSequence, Unexpected type: A4
> SrParseV3SnmpMessage: ParseSequence:
> SrParseV3SnmpMessage: Failed.
> SrDoSnmp: ASN Parse Error
> 
> 000937: *Jul 27 15:24:57.773: SNMP: Packet received via UDP from 10.X.X.X on VlanXXXXParseSequence, Unexpected type: 44
> SrParseV3SnmpMessage: ParseSequence:
> SrParseV3SnmpMessage: Failed.
> SrDoSnmp: ASN Parse Error
> 

I found nothing on the matter on the github nor on the internet, I hope you will have a piece of answer!

Cordially,

R1sCh0

**Comment by garnier-quentin** [comment]
The following options only work with net-snmp 5.9.1 (version of the perl binding with the new AES). Maybe you should backport net-snmp on your system.

**Comment by R1sCh0** [comment]
As you previously suggests I tried with 5.9.1: same result.
I'm wondering if my problem isn't caused by perl and more specifically by its version: 5.18
I guess that the plugin uses the module NET::SNMP, I check on my machine and it seems that it's in version 5.0703

Is it mandatory to update perl and net-snmp ?

**Comment by garnier-quentin** [comment]
Yes it's mandatory to update the perl net-snmp module (binding from the lib net-snmp).

**Comment by R1sCh0** [comment]
Hello, you were right the problem was that my net-snmp module in perl was still in version 5.0703.

I had to install the newer by hand because it wasn't working using --with-perl-modules option. 

Now it works fine!

Thanks.

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
