### ISSUE TITLE
[network::citrix::netscaler::snmp::plugin] Citrix ADC VServer sslvpn don't provide health status

### ISSUE THREAD

**Issue by Gregesp** [centreon/centreon-plugins#3794]
Hello,

I've posted on [The Watch](https://thewatch.centreon.com/data-usage-and-visualization-38/plugins-citrix-netscaler-adc-vserver-type-sslvpn-748), but i don't post an issue about that.

With Citrix NetScaler ADC or more simply Citrix ADC, VServer SSLVPN are not managed as device permit it.

Health indicator is not provided for this type of VServer.

Documentation about the OID of a Citrix ADC here https://developer-docs.citrix.com/projects/citrix-adc-snmp-oid-reference/en/latest/ not mention health about this type of vserver.

Exemple :

Here i provide a Health options and it return Critical state, who is false

`-bash-4.2$ /usr/lib/centreon/plugins/centreon_netscaler.pl --plugin=network::citrix::netscaler::snmp::plugin --mode=vserver-status --hostname='@IP_of_Citrix_ADC' --snmp-version='3' --snmp-community='private' --snmp-username centreon --authprotocol SHA --authpassphrase "my_auth_passphrase" --privprotocol AES --privpassphrase "my_priv_passphrase" --filter-name='VS_sslvpn' --filter-type='' --warning-health='@50:75' --critical-health='@0:50' --filter-type='sslvpn'
CRITICAL: Virtual Server 'VS_sslvpn' Health: 0.00 % | 'health'=0.00%;@50:75;@0:50;0;100 'traffic_in'=0.00b/s;;;0; 'traffic_out'=0.00b/s;;;0; 'clients'=0;;;0; 'servers'=0;;;0;`

Here i don't provide Health options and it return OK state who is true

`-bash-4.2$ /usr/lib/centreon/plugins/centreon_netscaler.pl --plugin=network::citrix::netscaler::snmp::plugin --mode=vserver-status --hostname='@IP_of_Citrix_ADC' --snmp-version='3' --snmp-community='' --snmp-username centreon --authprotocol SHA --authpassphrase "my_auth_passphrase" --privprotocol AES --privpassphrase "my_priv_passphrase" --filter-name='VS_sslvpn' --filter-type='sslvpn'
OK: Virtual Server 'VS_sslvpn' State : up, Health: 0.00 %, Traffic In: 0.00 b/s, Traffic Out: 0.00 b/s, Total Client Connections : 0, Total Server Connections : 0 | 'health'=0.00%;;;0;100 'traffic_in'=0.00b/s;;;0; 'traffic_out'=0.00b/s;;;0; 'clients'=0;;;0; 'servers'=0;;;0;`

With Debug sessions

`-bash-4.2$ /usr/lib/centreon/plugins/centreon_netscaler.pl --plugin=network::citrix::netscaler::snmp::plugin --mode=vserver-status --hostname='@IP_of_Citrix_ADC' --snmp-version='3' --snmp-community='' --snmp-username centreon --authprotocol SHA --authpassphrase "my_auth_passphrase" --privprotocol AES --privpassphrase "my_priv_passphrase" --filter-name='VS_sslvpn' --filter-type='sslvpn' --debug
OK: Virtual Server 'VS_sslvpn' State : up, Health: 0.00 %, Traffic In: 0.00 b/s, Traffic Out: 0.00 b/s, Total Client Connections : 0, Total Server Connections : 0 | 'health'=0.00%;;;0;100 'traffic_in'=0.00b/s;;;0; 'traffic_out'=0.00b/s;;;0; 'clients'=0;;;0; 'servers'=0;;;0;
.1.3.6.1.4.1.5951.4.1.3.1.1.5.11.86.83.95.65.68.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.11.86.83.95.83.70.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.68.78.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.78.84.80.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.83.65.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.59.11.86.83.95.65.68.95.90.80.82.73.86 = VS_AD_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.11.86.83.95.83.70.95.90.80.82.73.86 = VS_SF_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.68.78.83.95.90.80.82.73.86 = VS_DNS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.78.84.80.95.90.80.82.73.86 = VS_NTP_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.83.65.83.95.90.80.82.73.86 = VS_SAS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = VS_RADIUS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = VS_AD_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = VS_sslvpn2
.1.3.6.1.4.1.5951.4.1.3.1.1.59.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = VS_sslvpn
.1.3.6.1.4.1.5951.4.1.3.1.1.64.11.86.83.95.65.68.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.11.86.83.95.83.70.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.68.78.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.78.84.80.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.83.65.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 3
.1.3.6.1.4.1.5951.4.1.3.1.1.64.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 3
skipping Virtual Server 'VS_SF_LB'.
skipping Virtual Server 'VS_NTP_LB'.
skipping Virtual Server 'VS_AD_LB'.
skipping Virtual Server 'VS_SAS_LB'.
skipping Virtual Server 'VS_RADIUS_LB'.
skipping Virtual Server 'VS_ssslvpn2'.
skipping Virtual Server 'VS_DNS_LB'.
skipping Virtual Server 'VS_AD_LB'.
.1.3.6.1.4.1.5951.4.1.3.1.1.13.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.14.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.17.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.18.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.31.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.33.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.56.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.62.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.65.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
Virtual Server 'VS_sslvpn' State : up, Health: 0.00 %, Traffic In: 0.00 b/s, Traffic Out: 0.00 b/s, Total Client Connections : 0, Total Server Connections : 0`

`-bash-4.2$ /usr/lib/centreon/plugins/centreon_netscaler.pl --plugin=network::citrix::netscaler::snmp::plugin --mode=vserver-status --hostname='@IP_of_Citrix_ADC' --snmp-version='3' --snmp-community='' --snmp-username centreon --authprotocol SHA --authpassphrase "my_authpassphrase" --privprotocol AES --privpassphrase "my_priv_passphrase" --filter-name='VS_sslvpn' --filter-type='' --warning-health='@50:75' --critical-health='@0:50' --filter-type='sslvpn' --debug
CRITICAL: Virtual Server 'VS_sslvpn' Health: 0.00 % | 'health'=0.00%;@50:75;@0:50;0;100 'traffic_in'=0.00b/s;;;0; 'traffic_out'=0.00b/s;;;0; 'clients'=0;;;0; 'servers'=0;;;0;
.1.3.6.1.4.1.5951.4.1.3.1.1.5.11.86.83.95.65.68.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.11.86.83.95.83.70.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.68.78.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.78.84.80.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.83.65.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.59.11.86.83.95.65.68.95.90.80.82.73.86 = VS_AD_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.11.86.83.95.83.70.95.90.80.82.73.86 = VS_SF_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.68.78.83.95.90.80.82.73.86 = VS_DNS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.78.84.80.95.90.80.82.73.86 = VS_NTP_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.83.65.83.95.90.80.82.73.86 = VS_SAS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = VS_RADIUS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = VS_AD_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = VS_sslvpn2
.1.3.6.1.4.1.5951.4.1.3.1.1.59.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = VS_sslvpn
.1.3.6.1.4.1.5951.4.1.3.1.1.64.11.86.83.95.65.68.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.11.86.83.95.83.70.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.68.78.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.78.84.80.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.83.65.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 3
.1.3.6.1.4.1.5951.4.1.3.1.1.64.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 3
skipping Virtual Server 'VS_SF_LB'.
skipping Virtual Server 'VS_NTP_LB'.
skipping Virtual Server 'VS_AD_LB'.
skipping Virtual Server 'VS_SAS_LB'.
skipping Virtual Server 'VS_RADIUS_LB'.
skipping Virtual Server 'VS_sslvpn2'.
skipping Virtual Server 'VS_DNS_LB'.
skipping Virtual Server 'VS_AD_LB'.
.1.3.6.1.4.1.5951.4.1.3.1.1.13.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.14.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.17.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.18.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.31.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.33.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.56.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.62.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.65.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
Virtual Server 'VS_sslvpn' State : up, Health: 0.00 %, Traffic In: 0.00 b/s, Traffic Out: 0.00 b/s, Total Client Connections : 0, Total Server Connections : 0`

Regards,

**Comment by garnier-quentin** [comment]
I don't understand the issue. Your threshold is: ```--critical-health='@0:50'```. The health is: ```0%```. So it must be critical.

**Comment by Gregesp** [comment]
Hello,

For a `--filter-type=sslvpn`, you don't have Health, so actually if you keep threshold with `--critical-health` and `--warning-health` you have a false positive because a VServer sslvpn (Gateway) don't provide Health indicator.

The only thing you could monitor for this type of VServer is Traffic-In, Traffic-Out like plugins is made.

I could give you an exemple of what is indicated for a sslvpn (VPN/Citrix Gateway) tomorrow by mail.

You could check that here :
https://developer-docs.citrix.com/projects/citrix-adc-snmp-oid-reference/en/latest/#nssslvpnstatsgroup

If you see an interesting OID i can give you a snmpwalk about this device.

Regards,

**Comment by garnier-quentin** [comment]
There is an OID defined for the health:
```
.1.3.6.1.4.1.5951.4.1.3.1.1.62.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
```

0 can be a value for the health. How can i do the diff between a real 0 and undefined value.

**Comment by Gregesp** [comment]
Hello,

I will give you an ouput with `--debug` of a sslvpn vserver with traffic.
An sslvpn (Citrix Gateway) don't provide Health status.
Health here represent the percentage of UP services bound to this vserver (for a Server Load Balancing)
https://developer-docs.citrix.com/projects/citrix-adc-snmp-oid-reference/en/latest/#vsvrhealth

Regards,

**Comment by Gregesp** [comment]
Hello,

The output :

```
-bash-4.2$ /usr/lib/centreon/plugins/centreon_netscaler.pl --plugin=network::citrix::netscaler::snmp::plugin --mode=vserver-status --hostname='@IP_of_Citrix_ADC' --snmp-version='3' --snmp-community='' --snmp-username centreon --authprotocol SHA --authpassphrase "my_authpassphrase" --privprotocol AES --privpassphrase "my_priv_passphrase" --filter-name='VS_sslvpn' --filter-type='sslvpn' --warning-health='@50:75' --critical-health='@0:50' --debug
CRITICAL: Virtual Server 'VS_sslvpn' Health: 0.00 % | 'health'=0.00%;@50:75;@0:50;0;100 'traffic_in'=12624.52b/s;;;0; 'traffic_out'=167071.16b/s;;;0; 'clients'=12;;;0; 'servers'=0;;;0;
.1.3.6.1.4.1.5951.4.1.3.1.1.5.11.86.83.95.65.68.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.11.86.83.95.83.70.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.68.78.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.78.84.80.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.12.86.83.95.83.65.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.5.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 7
.1.3.6.1.4.1.5951.4.1.3.1.1.59.11.86.83.95.65.68.95.90.80.82.73.86 = VS_AD_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.11.86.83.95.83.70.95.90.80.82.73.86 = VS_SF_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.68.78.83.95.90.80.82.73.86 = VS_DNS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.78.84.80.95.90.80.82.73.86 = VS_NTP_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.12.86.83.95.83.65.83.95.90.80.82.73.86 = VS_SAS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = VS_RADIUS_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = VS_AD_LB
.1.3.6.1.4.1.5951.4.1.3.1.1.59.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = VS_sslvpn2
.1.3.6.1.4.1.5951.4.1.3.1.1.59.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = VS_sslvpn
.1.3.6.1.4.1.5951.4.1.3.1.1.64.11.86.83.95.65.68.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.11.86.83.95.83.70.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.68.78.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.78.84.80.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.12.86.83.95.83.65.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.15.86.83.95.82.65.68.73.85.83.95.90.80.82.73.86 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.17.86.83.95.65.68.95.90.80.82.73.86.95.69.50.82.48.50 = 1
.1.3.6.1.4.1.5951.4.1.3.1.1.64.22.86.83.95.115.118.99.48.50.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 3
.1.3.6.1.4.1.5951.4.1.3.1.1.64.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 3
skipping Virtual Server 'VS_SF_LB'.
skipping Virtual Server 'VS_NTP_LB'.
skipping Virtual Server 'VS_AD_LB'.
skipping Virtual Server 'VS_SAS_LB'.
skipping Virtual Server 'VS_RADIUS_LB'.
skipping Virtual Server 'VS_sslvpn2'.
skipping Virtual Server 'VS_DNS_LB'.
skipping Virtual Server 'VS_AD_LB'.
.1.3.6.1.4.1.5951.4.1.3.1.1.13.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.14.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.17.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.18.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = undef
.1.3.6.1.4.1.5951.4.1.3.1.1.31.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 65336895
.1.3.6.1.4.1.5951.4.1.3.1.1.33.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 1683162881
.1.3.6.1.4.1.5951.4.1.3.1.1.56.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 5853
.1.3.6.1.4.1.5951.4.1.3.1.1.62.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
.1.3.6.1.4.1.5951.4.1.3.1.1.65.23.86.83.95.115.118.99.99.105.116.46.115.112.111.116.105.109.97.103.101.46.99.111.109 = 0
Virtual Server 'VS_sslvpn' State : up, Health: 0.00 %, Traffic In: 12.62 Kb/s, Traffic Out: 167.07 Kb/s, Total Client Connections : 12, Total Server Connections : 0
```
OID [vsvrhealth](https://developer-docs.citrix.com/projects/citrix-adc-snmp-oid-reference/en/latest/#vsvrhealth) have a value 0 with a VServer type sslvpn

Regards,

**Comment by garnier-quentin** [comment]
I understand. If the type is sslvpn, we skip the health counter: 
https://github.com/centreon/centreon-plugins/pull/3939
