### ISSUE TITLE
[storage::dell::me4::restapi::plugin] warning/critical thresholds not working

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3808]
For the modes

- volume-statistics
- controller-statistics

warning and critical thresholds are not working:
`Unknown option: warning-instance-volume-cache-write-hits-count`

**Comment by garnier-quentin** [comment]
it's an issue with the help. It had been fixed

**Comment by joschi99** [comment]
Unfortunatly it's still not resolved:
```
--mode=controller-statistics --warning-controller-iops-ops=
Unknown option: warning-controller-iops-ops
```

**Comment by garnier-quentin** [comment]
it will be fixed: https://github.com/centreon/centreon-plugins/pull/3812
