### ISSUE TITLE
[storage::dell::me4::restapi::plugin] - list-modes with --disco-show reports empty

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3809]
Doing a discovery with

- list-controllers
- list-volumes

returns a empty result if you use option `--disco-show`

without `--disco-show`
```
List volumes:
[name = Datastore-vol0001][volumegroup = UNGROUPEDVOLUMES]
```

with `--disco-show`
```
<?xml version="1.0" encoding="utf-8"?>
<data/>
```

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3810
