### ISSUE TITLE
Google Meet: quality monitoring

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3814]
It should be nice to add the possibility to monitor the meeting quality for Google Meet.

Google Meet API:
https://developers.google.com/admin-sdk/reports/v1/appendix/activity/meet

Here some screenshot from the Google Meet Quality Tool:

Overview
![image](https://user-images.githubusercontent.com/6400595/183110365-c4bea607-1558-4cd0-a1b6-3690642833a1.png)

Meeting details
![image](https://user-images.githubusercontent.com/6400595/183110459-81292ff5-d736-4b37-a04d-c42eef410542.png)
![image](https://user-images.githubusercontent.com/6400595/183110848-e137d146-03f4-40b0-bbef-f4e28948e644.png)
![image](https://user-images.githubusercontent.com/6400595/183110869-f5cac10c-3f61-4f73-a269-a77cde74ea0e.png)
![image](https://user-images.githubusercontent.com/6400595/183110884-004c8588-1bda-409c-afc1-44272a372cc3.png)
![image](https://user-images.githubusercontent.com/6400595/183110898-44e73a75-86fc-424e-b958-41a6713f5431.png)
![image](https://user-images.githubusercontent.com/6400595/183110927-1dca34cd-8f86-4e56-bab2-78ea1298d7c6.png)
![image](https://user-images.githubusercontent.com/6400595/183110957-edc628ea-93a1-4e56-a10e-aee7418bd44a.png)

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This feature request seems particularly old so let me close it. If the feature request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
