### ISSUE TITLE
[storage::netapp::snmp::plugin] Filter output on global-status mode

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#382]
Hi,
When using the global-status mode for NetAPP, we actually see the global status and the file system status.
Is it possible to filter or chose which "status" we want to see, as the file system status thresholds are defined on the Operation Manager and the file systems can be monitor directly ?
Thank you for your answer.

**Comment by dooko** [comment]
To describe what I'm saying :
CRITICAL: Overall **global status** is 'critical' [message: 'Disk shelf fault. '] WARNING: Overall **file system status** is 'nearly full' [message: '/vol/vol_xxx is nearly full (using or reserving 96% of space and 0% of inodes, using 96% of reserve)./vol/vol_yyy is nearly full (using or reserving 96% of space and 0% of inodes, usi']

**Comment by Sims24** [comment]
Hi @dooko ,

Could you please test with the mode in the commit above and let me know if it does the tricks ? 

-> use --filter-counters global

Thanks,
