### ISSUE TITLE
Problem with storage::emc::DataDomain::plugin plugin (replication mode)

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-plugins#3822]
Hi,

Like explained in #2701, I also have a problem with replication mode of storage::emc::DataDomain::plugin. This one works fine in centreon-plugins version 20180528 but not with 20191219 nor 20220616.

This is the result of my datadomain :

snmpget -v 2c -c COMMUNITY IP .1.3.6.1.2.1.1.1.0  
SNMPv2-MIB::sysDescr.0 = STRING: Data Domain OS 7.2.0.85-690730

snmpwalk -v 2c -c COMMUNITY IP .1.3.6.1.2.1.1.1   
SNMPv2-MIB::sysDescr.0 = STRING: Data Domain OS 7.2.0.85-690730

But when I want to use the plugin : 

MYPATH/centreon-plugins-20220616/centreon_plugins.pl --plugin=storage::emc::DataDomain::plugin --mode=replication --hostname=IP --snmp-community=COMMUNITY --verbose --debug

I got the following error : 

UNKNOWN: SNMP Table Request: Cant get a single value. 
.1.3.6.1.2.1.1.1.0 = Data Domain OS 7.2.0.85-690730

Am I missing something or do you have a fix for that problem ?

Thanks for your help.

Best,

**Comment by garnier-quentin** [comment]
could you provide the snmpwalk of following branch ? .1.3.6.1.4.1.19746.1.8.1.1.1
And the MIB for your datadomain version ?

**Comment by Hellnino18** [comment]
Hi @garnier-quentin , this is the result of the snmpwalk : 
SNMPv2-SMI::enterprises.19746.1.8.1.1.1 = No Such Object available on this agent at this OID

**Comment by garnier-quentin** [comment]
It's the issue. replication information is in that SNMP table. Could you provide the MIB files of your version ? Maybe DataDomain have done some changes.

**Comment by Hellnino18** [comment]
[DATA_DOMAIN.txt](https://github.com/centreon/centreon-plugins/files/9300809/DATA_DOMAIN.txt)

Here the file ;) Thx.

**Comment by garnier-quentin** [comment]
It's still the same SNMP table. You should ask to your EMC support. Maybe an issue with that firmware

**Comment by Hellnino18** [comment]
But why this is working with 20180528 version of centreon-plugins and not after ? You change something of that part ?

**Comment by garnier-quentin** [comment]
What is your output with that version ? Because it shouldn't work also (it"s quite the same code)

**Comment by Hellnino18** [comment]
The output is : 

OK: All replications are ok |

But maybe it's a false "OK" ?

**Comment by garnier-quentin** [comment]
Could you provide the output with --verbose ?

**Comment by Hellnino18** [comment]
It's already the output with verbose...

**Comment by garnier-quentin** [comment]
I think it was not working before. it was a false positive

**Comment by Hellnino18** [comment]
Hi @garnier-quentin , you can close this case. I have take a look with my storage colleague, and we have no replications on this new datadomain. I think this is why we don't have the replication OID. Sorry about that, and thanks for your time.

**Comment by garnier-quentin** [comment]
thanks for the feedback :)
