### ISSUE TITLE
Aruba controller

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#383]
Hi,

Aruba plugin has mode ap-user. How should I write the command if I want to check only one AP and I want it to show as critical if the AP is not connected.  The AP-users mode gives me output: AP '172.163.30.9.81.144' Users : 16.
Also how should I write the command if I want to see in output only one SSID connected users count? Right now the output is ESSID 'D_test' Users : 10 ESSID 'R_test' Users : 15

**Comment by Sims24** [comment]
Hi, 

Did you try with option --filter-essid 'D_test' for example ? It should filter on this specific SSID, but ... I think that there is a bug on this filter ... 

Please try to replace line 409 : 

        next if (defined($self->{option_results}->{filter_ip_address}) && $self->{option_results}->{filter_ip_address} ne '' &&

should become 

        next if (defined($self->{option_results}->{filter_essid}) && $self->{option_results}->{filter_essid} ne '' &&

Can you tell me if it does fix the issue ? 

I'm not sur that you will get a critical on disconnected AP, may be a unknown. Will be back to you with the answer when I have a feedback from Quentin.

Thanks

**Comment by kadrika** [comment]
It still does not work. For example if I check all ap-users:
./centreon_plugins.pl --plugin=network::aruba::standard::snmp::plugin --hostname=1.2.2.1 --snmp-version=2c --snmp-community=xxx --mode=ap-users --verbose
I get this output: 
AP '22.212.622.199.333.222' Users : 4
AP '21.199.678.664.897.111' Users : 2
ESSID 'WiFi' Users : 4 .
etc.
Now I want to check only the first AP and get critical alert in the AP is not connected, but I cant filter it in any way.

I found a way myself right now how to get the needed info without this plugin:
$USER1$/check_snmp -H $HOSTADDRESS$ -P2c -C $_HOSTSNMPCOMMUNITY$ -o 1.3.6.1.4.1.14823.2.2.1.5.2.1.4.1.19.$ARG1$,1.3.6.1.4.1.14823.2.2.1.5.2.1.5.1.7.$ARG1$.1,1.3.6.1.4.1.14823.2.2.1.5.2.1.5.1.7.$ARG1$.2 -s 1 -l AP_status,Users_connected_to_A_radio,Users_connected_to_B_radio

Arg1 is the converted serial number of the AP.
if somebody knows how to turn this command into nice plugin that also draws nice graphs I would be extremely happy!

**Comment by garnier-quentin** [comment]
i'll do the change Kadrika. Could you test it tomorrow ?

**Comment by garnier-quentin** [comment]
Could you test with the last version. You can filter with:
--filter-bssid="22.212.622.199.333.222"

And you can check if there is some users on it with: --critical-total-ap=1:

You can filters: --filter-counters="^(?!(total-ap)$)"

**Comment by kadrika** [comment]
bash-4.1$ ./centreon_plugins.pl --plugin=network::aruba::standard::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=ap-users --filter-bssid='172.163.30.9.172.129'
Unknown option: filter-bssid at /usr/lib/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 66.

**Comment by garnier-quentin** [comment]
Have you updated your plugin ?

**Comment by kadrika** [comment]
yeah, I did. When I use --help, I do see that --filter-bssid in it. But when I use it in the command it does not work.

**Comment by garnier-quentin** [comment]
My bad... I have fixed it. Could you test it again ?

**Comment by kadrika** [comment]
Now it gives me the connected users amount to that AP. But how should I add the filter, so that it gives me critical when that AP is not even connected?

**Comment by kadrika** [comment]
It seems to work, if I use --critical-total=1: but it does not work with --critical-total-ap=1:

**Comment by garnier-quentin** [comment]
Could you give me the full result (with verbose) of your command line ?

**Comment by kadrika** [comment]
bash-4.1$ ./centreon_plugins.pl --plugin=network::aruba::standard::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=ap-users --filter-bssid='172.163.30.235.12.163' --critical-total=1: --verbose
OK: Total Users : 6, Total Auth None : 6, Total Auth Other : 0, Total Auth Web : 0, Total Auth Dot1x : 0, Total Auth Vpn : 0, Total Auth Mac : 0, Users average connection time : 11109.167 seconds - ESSID 'S Open' users : 6 - AP '172.163.30.235.12.163' users : 6 | 'total'=6users;;1:;0; 'total_none'=6users;;;0; 'total_other'=0users;;;0; 'total_web'=0users;;;0; 'total_dot1x'=0users;;;0; 'total_vpn'=0users;;;0; 'total_mac'=0users;;;0; 'avg_connection_time'=11109.167s;;;0; 'essid'=6users;;;0; 'ap'=6users;;;0;
ESSID 'S Open' users : 6
AP '172.163.30.235.12.163' users : 6
bash-4.1$ ./centreon_plugins.pl --plugin=network::aruba::standard::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=ap-users --filter-bssid='672.163.30.235.12.163' --critical-total=1: --verbose
CRITICAL: Total Users : 0 | 'total'=0users;;1:;0; 'total_none'=0users;;;0; 'total_other'=0users;;;0; 'total_web'=0users;;;0; 'total_dot1x'=0users;;;0; 'total_vpn'=0users;;;0; 'total_mac'=0users;;;0;

bash-4.1$ ./centreon_plugins.pl --plugin=network::aruba::standard::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=ap-users --filter-bssid='672.163.30.235.12.163' --critical-total-ap=1: --verbose
OK: Total Users : 0, Total Auth None : 0, Total Auth Other : 0, Total Auth Web : 0, Total Auth Dot1x : 0, Total Auth Vpn : 0, Total Auth Mac : 0, avg-connection-time : skipped (no value(s)) - All users by ESSID are ok - All users by AP are ok | 'total'=0users;;;0; 'total_none'=0users;;;0; 'total_other'=0users;;;0; 'total_web'=0users;;;0; 'total_dot1x'=0users;;;0; 'total_vpn'=0users;;;0; 'total_mac'=0users;;;0;

**Comment by garnier-quentin** [comment]
Indeed that's normal. You don't have an entry so --critical-total-ap is not checked. 
So use --critical-total :) Is it ok for you ?

**Comment by kadrika** [comment]
Yes, it is ok. Only problem I noticed, is that the request takes lot of time :( so I have to use quite high timeout-times.

**Comment by garnier-quentin** [comment]
Maybe you have a lot of oids

**Comment by kadrika** [comment]
Well the client has more than 200 access points in that controller, so I think that is causing the timeout problem.

**Comment by garnier-quentin** [comment]
yes that's sure. It's quite a lot.
