### ISSUE TITLE
[centreon 22.04] centreon_plugin.pl nrpe SSL issue

### ISSUE THREAD

**Issue by ASLLR** [centreon/centreon-plugins#3837]
Hi everyone, 

I am working on a migration from eon to centreon. Historically on eon we used the check_nrpe plugin to check our machines with this command for example `./check_nrpe -H thehostname -c check_cpu`

Now, I want to use the centreon_plugin with this command: `centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --custommode=nrpe --mode=query --hostname thehostname --command check_cpu`

On the client side (it's the server) we use NRPE - Nagios Remote Plugin Executor Version: 4.0.3. The nrpe.cfg file not have any ssl option configured. 

If i lauch the centreon command without change i've this message : `UNKNOWN: No response from remote host` on the client (server) we have `Error: (!log_opts) Could not complete SSL handshake with XX.XX.XX.XX: 1`

I can read the issue #1666 and if i add SSL options : `--ssl-opt="SSL_cipher_list => 'ALL'"  --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE` the result is `UNKNOWN: Failed to establish SSL connection: , ssl_error=SSL connect attempt failed error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure`

The only way to function is on client side on /etc/default/nagios-nrpe-server adding the -n on NRPE_OPTS field. 

I can see on tcpdump the difference between eon check and centreon check. Eon does a tlsv1.2 handshake and centreon does nothing.

But I don't want to lower my security level with this migration. Do you have any idea ? 

Thank you in advance

**Comment by garnier-quentin** [comment]
Have you tried to force a cipher: ```--ssl-opt="SSL_version => 'TLSv1'"``` ? (it will force TLS1.2)

**Comment by ASLLR** [comment]
Hi @garnier-quentin thank you for your answer, the result with this option is `UNKNOWN: Failed to establish SSL connection: , ssl_error=SSL connect attempt failed error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure`

Best regards

**Comment by garnier-quentin** [comment]
It's weird. i need to do a session to test it.

**Comment by garnier-quentin** [comment]
Need to send me an email

**Comment by garnier-quentin** [comment]
You have an option the change the protocol version: ```--nrpe-version=3``` (by default it's the old version: 2).

**Comment by garnier-quentin** [comment]
You can comment it if you still have the issue

**Comment by belgianik** [comment]
Hey everyone!
I see that this topic is closed but there is no solution...
I have the same problem and the same error.
Trying to run the following command:
**centreon_plugins.pl --verbose --plugin=apps::protocols::nrpe::plugin --mode=query --custommode=nrpe --hostname=10.X.X.X --command=check_load --ssl-opt="SSL_version => 'TLSv1'" --ssl-opt="SSL_verify_mode => 0"  --nrpe-version=3**

and get this result on the client side:
**Error: (!log_opts) Could not complete SSL handshake with 10.X.X.X:**

Any ideas?
