### ISSUE TITLE
[network::hp::procurve::plugin] Not adapted for smart managed HP ProCurve switches

### ISSUE THREAD

**Issue by davidmasson** [centreon/centreon-plugins#384]
Hello,
This plugin works well on CLI managed switches but it can't get values for smart manages switches (only web interface and basic unconfigurable SNMP). Could you adapt the plugin for these switches please ?

I can provide snmpwalk file for 1800 and 1900 and the MIB seems to be included here : http://h17007.www1.hp.com/us/en/support/software/summary/mibs-mngd-sw-p.aspx

Thanks :)

**Comment by Sims24** [comment]
Hi David, 

Thanks, think that you can send the walk by mail to Quentin and me and we let you know !

Regards

**Comment by davidmasson** [comment]
Ok, thanks

**Comment by Sims24** [comment]
David, 

Can you test with the h3c plugin instead of the procurve plugin please ? 

Thanks,

**Comment by davidmasson** [comment]
It works well for 1900 but not for 1800, this one has very poor SNMP information.

**Comment by Oly75** [comment]
The H3C plugin doesn't work well for this switch. Indeed the check command hardware global returns OK all 0 components are OK.

**Comment by Sims24** [comment]
hey @Oly75, what is the model / firmware of your switch ?

Could you provides complete snmpwalk by mail :) ? 

snmpwalk -Cc -On -v 2c -c <yourcommunity> <ip> .1  > /tmp/hp_managed_<version>.snmpwalk 

Thanks !!!

**Comment by Oly75** [comment]
Yes :D . I will send you that.

**Comment by garnier-quentin** [comment]
Except standard interface mibs, there is nothing to get from snmp. I close it.
