### ISSUE TITLE
Bypass special character for password

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#3840]
Hi

I need help with a password problem. My password have ' and (
And with this command, I cannot bypass this special caratere, I don't find how can I bypass it :(
  
/usr/lib64/nagios/plugins/check_centreon_nrpe -H ip -p 5666 -t 30 -u -m 8192 -c check_centreon_plugins -a 'apps::protocols::ldap::plugin' 'login'  ' --hostname="ldaps" --ldap-connect-options="scheme=ldaps" --ldap-starttls-options="verify=none" --username="uid=xxxx,ou=xxxx,o=xxxxx" --password="1234'56(789" '  

Thanks lot

**Comment by garnier-quentin** [comment]
You can use the option ```--convert-args``` (only the quote is the issue i think):
```
--convert-args="##,\x27" --password="1234##56(789"
```

**Comment by romsworld** [comment]
<3 Thanks !!!
