### ISSUE TITLE
[os::windows/linux::snmp::plugin] Mode storage, negative values

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#385]
Hi,
I have a question about handling negative values of hrStorageSize and hrStorageUsed OIDs.
As you know, this value is on a 32-bits signed integer, it can so overflow. 
You handle this by displaying the following message _Skipping storage 'X:': total size is <= 0_.
However, when you have a negative value, you can trick by adding 2^32 to the value.
Is that something you know off, that you could implement or not at all ?
Thanks

**Comment by Sims24** [comment]
Hi dooko, 

Not sure that this is as simple as it. Sounds more like a bug from the Windows SNMP agent. I'm not even sure that adding the negative value from the mib to 2¨32 could solve the issue and give the good value.

I will check and let you know but probably not possible. Take a look a NSClient++ for drive of a huge size, that's more efficient.

Regards

**Comment by dooko** [comment]
Well, as I see, this is how the Windows SNMP agent manages the overflow.

Some examples :
 - For a 19,9TB disk with 8K size block, the value of hrStorageSize should be 2684337919 (21990096232448÷8192). The maximum being 2147483647, the returned value is -1610629377.
If you add 2^32 to that value, you obtain 4294967296-1610629377 = 2684337919.
 - For a 25,4TB disk with 8K size block, the value of hrStorageSize should be 3416241407 (27985849606144÷8192). The maximum being 2147483647, the returned value is -878725889.
If you add 2^32 to that value, you obtain 4294967296-878725889 = 3416241407.

**Comment by Sims24** [comment]
Ok looks like you're right, just need to talk about it with Quentin as it is a bug of the windows snmpagent. He will make the choice and we'll let you know. 

thanks

**Comment by garnier-quentin** [comment]
I don't really like to add 2^32 to the value. Why ? Because the counter can have done 2 (or more) rolls of the counter. Anyway, i can manage the skip if the value is negative.

**Comment by garnier-quentin** [comment]
I already handle it.
