### ISSUE TITLE
[apps::vmware::connector::plugin] how to monitor vCenter alarms

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3854]
Is there a way with the existing modes to monitor through vCenter alarms like:
![image](https://user-images.githubusercontent.com/6400595/185850656-06a89526-4298-495f-b2b9-708261355e5b.png)
As you can see on the screenshot there a one CRITICAL and 3 WARNING alarms on vCenter level, but they are not show with mode alarm-datacenter.
Maybe we need a new mode "alarm-vcenter" for them?

**Comment by garnier-quentin** [comment]
Maybe available in Rest API: https://developer.vmware.com/apis/vsphere-automation/latest/
If you find that information

**Comment by gagzou** [comment]
Hi,
Same problem:
![error_top_](https://user-images.githubusercontent.com/61595839/185949682-6d9d06cb-f0b0-4cfe-a671-730d2c7ca3fa.jpg)

**Comment by gagzou** [comment]
Maybe an idea : 
The command gives no result on the vcenter folder:
(get-datacenter).extensiondata.triggeredalarmstate 
On the other hand, this one gives the alarm on the vcenter folder:
(get-folder -Server server.name.fqdn "datacenters").ExtensionData.TriggeredAlarmState

Key                : alarm-529.group-d1
Entity             : Folder-group-d1
Alarm              : Alarm-alarm-529
OverallStatus      : red
Time               : 20/08/2022 15:45:09
Acknowledged       : False
AcknowledgedByUser :
AcknowledgedTime   :
EventKey           : 203076096
Disabled           :
LinkedView         :

**Comment by ChristophePelichet** [comment]
Hello , 

This is a feature I really need, I can't give remote access but I'm available to take out data or make tests if needed.

I'm on VMware 7. and Vcenter are at the latest version.
