### ISSUE TITLE
[os::linux::snmp::plugin] Mode=storage - Is it possible to calculate reservation space automatically

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#386]
Hi,
There is another way than command " tune2fs-l " then to calculate the percentage enter "block count" and "reserved block" to know the space reserved on a disk?
If it is possible, a value "AUTO" could be implemented for the argument space-reservation.
It will be useful in case of usage without specified disk.
The 5 % default value can stay.

-----------------------
Bonjour,
Existe-t-il un autre moyen que la commande "tune2fs -l" puis de calculer le pourcentage entre "block count" et "reserved block" pour connaitre l'espace reservé d'un disque?
Si c'est possible, une valeur "AUTO" pourrait être implémentée pour l'argument space-reservation.
Cela pourrait être utile dans le cas d'une utilisation sans spécifier un disque
La valeur par défaut de 5% peut restée.

**Comment by garnier-quentin** [comment]
SNMP doesn't give the information about the root reservation. Don't know if it's same for Windows filesystem (5%) and also for Solaris, AIX,...

**Comment by cmeschin** [comment]
Ok, thanks.
