### ISSUE TITLE
[network::alvarion::breezeaccess::snmp::plugin] - radiostatus - exceed 100%

### ISSUE THREAD

**Issue by watchix** [centreon/centreon-plugins#3861]
Hello,

Sometimes the mode "radio-status" percentage returns an exceed of 100% ... is it normal ?

Screens : ![Alvarion-bad-frames](https://user-images.githubusercontent.com/2278299/186205091-8be5c081-eb8d-4837-8e5d-56c6ac339a5d.jpg)

Alvarion firmware : 6.6.2

Regards,

**Comment by garnier-quentin** [comment]
It happened when the total frames counter rotates i think. I should fix it. When i think about it, it can also happen in interfaces modes for example (with errors).

**Comment by garnier-quentin** [comment]
I don't think i can have a good solution. I can add an option to not calculate (sometime we are missing a dot) if there is a counter going back. That option could help ?

**Comment by watchix** [comment]
Hello Quentin,

Thanks for your reply :blush:
The "problem" only occur on Alvarion antenna with a lot of bad frames (radio jamming)
Our check interval is 5min.

It's not really a problem for me, our team is informed that >100% is due to huge bad fames.
I don't know if your last solution is good (i'm not good in Python)
I was thinking about if the result >100%, then result is equal to 100%


Regards,

**Comment by garnier-quentin** [comment]
```I was thinking about if the result >100%, then result is equal to 100%```: i can do that but it's not accurate.
``` our team is informed that >100% is due to huge bad fames```: there are bad frames but maybe as usual.
