### ISSUE TITLE
network::fortinet::fortigate Unknown option: warning-not-synchronized

### ISSUE THREAD

**Issue by depass19** [centreon/centreon-plugins#3869]
Hi,

We are experiencing issue with Centreon Fortigate plugin. Indeed "Cluster-Status" check send to our Fortigate HA cluster returns the following error : 
Unknown option: warning-not-synchronized at /usr/lib/centreon/plugins//centreon_fortinet_fortigate.pl line 3584.

Note that running the command without  --warning-not-synchronized='' and --critical-not-synchronized='' returns the expected result.

Could you help us solving this problem ?

Regards.

**Comment by garnier-quentin** [comment]
Please update your centreon pack. The pack is outdated
