### ISSUE TITLE
storage::dell::me4::restapi::plugin MD5 encoding is no longer supported

### ISSUE THREAD

**Issue by dbongert** [centreon/centreon-plugins#3872]
We upgraded the firmware on our Dell ME4084 to version GT280R010-01 and Centreon is having issues logging in via the REST API. 

From https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=97g7r&oscode=wst14&productcode=powervault-me4084

FMW-50101 MC Disabled the MD5 feature

I used this Python script from the initial Dell ME feature request: https://github.com/centreon/centreon-plugins/issues/1429#issuecomment-475189475

and changing 

  auth_string = hashlib.md5("{}_{}".format(args.username, args.password).encode("utf-8")).hexdigest()

to 

  auth_string = hashlib.sha256("{}_{}".format(args.username, args.password).encode("utf-8")).hexdigest()

Makes it work.

**Comment by dbongert** [comment]
[centreon-diff.txt](https://github.com/centreon/centreon-plugins/files/9454007/centreon-diff.txt)

Swapping use Digest::MD5 qw(md5_hex) to use Digest::SHA qw(sha256_hex), and the md5_hex to sha256_hex fixes the issue.

**Comment by garnier-quentin** [comment]
It's a problem if old firmware doesn't support sha256. What error do you have if you use md5 ?

**Comment by TokenRing** [comment]
We get 

UNKNOWN: Login endpoint returns an error: 'Authentication Unsuccessful'

**Comment by garnier-quentin** [comment]
I can add the option: ```--digest-sha256``` (otherwise it will break for all format). Seems ok for you ?

**Comment by Hbitvof** [comment]
Recently we updated our Powervault to firmware version GT280R011-01 and have the same issue. I added the option --digest-sha256 to the command, but this is not solving the problem. Is there a way to debug this further to see what the issue is this time?
