### ISSUE TITLE
MongoDB v6.0: Unsupported OP_QUERY command

### ISSUE THREAD

**Issue by dcop7** [centreon/centreon-plugins#3882]
Using the centreon_mongodb.pl (Global Version: 20210915), doesn't support MongoDB v6.0.

It returns this error:
MongoDB::DatabaseError: Unsupported OP_QUERY command: ping. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal

The OP_QUERY was removed in MongoDB v6.0.

Can you update the plugin to support MongoDB v6.0?

Thank you.

**Comment by garnier-quentin** [comment]
Please update your rpm with following archives:
https://share.centreon.com/s/wKHDdzoRLma828F

It should work

**Comment by joschi99** [comment]
Same issue on latest plugins using Centreon 22.10.x
The share link with the updated rpm is not working anymore. Anyone has a solution?
