### ISSUE TITLE
Add IBM DB2 database checks

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#389]
Hello,

Is it possible to add DB2 plugin?
Maybe based on https://exchange.nagios.org/directory/Plugins/Databases/DB2/check_db2_health/details

Thanks a lot

**Comment by matthieu-robin** [comment]
👍 
Thanks

**Comment by garnier-quentin** [comment]
If someone has a db2 server and we can use it, please tell us.
