### ISSUE TITLE
UPS Socomec Netvision 6 support

### ISSUE THREAD

**Issue by proxyconcept** [centreon/centreon-plugins#3893]
Hi, I found the plugin `hardware::ups::socomec::netvision::snmp::plugin` (#2287) but it doesn't work with older versions. In my case, I want to monitor UPS with Net Vision v5.

I found this documentation for Net Vision v6 : https://www.socomec.fr/sites/default/files/2020-11/NET-VISION_INSTALLATION-AND-OPERATING-MANUAL_2009-10_IOM-2009-10_FR-FR.pdf

It looks very close, but OIDs have a different prefix : `.1.3.6.1.4.1.4555.1.1.1` instead of `.1.3.6.1.4.1.4555.1.1.7`

I tested by modifying the scripts and it works !

As the differences are minimal, I think it's not really necessary to make a new plugin... Maybe just an option in the different modes to specify the netvision version ?

Thanks

**Comment by garnier-quentin** [comment]
Could you provide MIBs and snmpwalk for your version ?

**Comment by proxyconcept** [comment]
I could ;)

http://www.circitor.fr/Mibs/Mib/S/SOCOMECUPS-MIB.mib

[snmpwalk-socomec-netvision5.txt](https://github.com/centreon/centreon-plugins/files/9536452/snmpwalk-socomec-netvision5.txt)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3914

You only need to update your plugin and it should work with version 5 also.

**Comment by proxyconcept** [comment]
Thanks, it works !

But just a remark in your code: you have named "netvision5" and "netvision6", but v5 and v6 are using the same old oid (4555.1.1.1). It's only from the version 7 that the new oid are used (4555.1.1.7).

So maybe you should rename your variables "6" to "7".
