### ISSUE TITLE
network::juniper::ex Filter Temperature

### ISSUE THREAD

**Issue by jbeaujour** [centreon/centreon-plugins#3894]
Hello
I use Network::Juniper::ex plugin mode hardware and i want to exclude temperature from "operating"
Is it possible ?
I try this :
`/usr/lib/centreon/plugins/centreon_plugins.pl --plugin network::juniper::ex::plugin --mode hardware --hostname @IP --snmp-version 2c --snmp-community XXX --snmp-port 161 --snmp-timeout 10 --snmp-retries 3 --maxrepetitions 40 --subsetleef 50  --snmp-errors-exit unknown --range-perfdata 1 --statefile-dir .../dir/check_juniper_health  --verbose --critical='operating-temperature,.*,1' --threshold-overload='fru,OK,unknown' --filter=operating-temperature,.*`

there is no filter :
`CRITICAL: Operating 'FPC: EX2200-24P-4G, POE @ 0/*/*' temperature is 29 degree centigrade`

Thank's for help ;)

**Comment by garnier-quentin** [comment]
Why did you use ```--critical='operating-temperature,.*,1' ``` if you want to exclude the temperature ?

**Comment by jbeaujour** [comment]
Hello
Its only for test, to show critical event. 
I haven't a Host with critical temp now, to exclude.
Did you have a solution to test ? 
Débug mode dont show temp alerte, only on status and perfdata.
How to write the filtre ?
Thank's

**Comment by garnier-quentin** [comment]
You can filter the temperature perfdata. But right now you cannot exclude the specific operating temperature in the output.
```--filter-perfdata='temp'```

**Comment by jbeaujour** [comment]
Hello Quentin
So no CRITICAL filter on *temp* possible, the only way is to set the threshold to 1000° for example, is that right?

**Comment by garnier-quentin** [comment]
There is no threshold by default. So you can remove the option and you won't have an alert.

**Comment by jbeaujour** [comment]
Ok thank you
I will modify the service

**Comment by jbeaujour** [comment]
test the answer to remove temp alert
