### ISSUE TITLE
[plugin] Cisco ASR

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#39]
Hi,

I would be really happy if you can create a plugin for Cisco ARS devices.

**Comment by kadrika** [comment]
Is it possible to get this in next few weeks?

**Comment by garnier-quentin** [comment]
Don't know. The standard cisco doesn't work for Cisco ASR ?

**Comment by kadrika** [comment]
I tested Cisco 2800, 2900, 3750 plugin and it only works at some parts.
For example:
ARS9001 - cpu does not work, environment does not work, memory works(It shows memory ok, but it would be better to see long output)
ARS901 - cpu works, memory works, environment works with 2800 and 2900 plugin.
ASR9010 - cpu does not work, environment does not work, memory is working.
ASR920 - cpu and memory work, but environment does not work.

Also It would be really, really good to get this information from the devices:
ISIS neighbors
BGP neighbors
PIM neighbors
OSPF neighbors

**Comment by garnier-quentin** [comment]
Please test it with the standard one now. Can have some improvements.

**Comment by kadrika** [comment]
ok, I will test it. What about the neighbors checks?

**Comment by garnier-quentin** [comment]
Why not. But i need the OIDs and walk on it.

**Comment by kadrika** [comment]
I will try to find the OIDs.

**Comment by kadrika** [comment]
I tested with standard plugin.
ARS9001 - CPU works, environment works, memory works also(It shows memory ok, but it would be better to see long output)
ARS901 - cpu works, memory works, environment works 
ASR9010 - cpu works, environment does not work, memory is working.
ASR920 - cpu and memory work, but environment only recognizes PSUs but not FANs.

**Comment by garnier-quentin** [comment]
Seems good for me.

**Comment by kadrika** [comment]
I need to get temperature information from 9001, but right now it does not show that.
Also environment for 9010 does not work with any of the plugins.
For 920 I also need temperature and FAN but right now it only shows PSU.

**Comment by garnier-quentin** [comment]
I think you couldn't get it from snmp (because i check it). You'll need to use SSH command maybe to have it.

**Comment by kadrika** [comment]
About those
ISIS, BGP, PIM, OSPF neighbors.
 
BGP plugin apps::protocols::bgp::4::plugin works just fine with ASR devices.

But IS-IS, PIM and OSPF is still needed.
OSPF uses OSPF-MIB (OID 1.3.6.1.2.1.14.X) http://tools.cisco.com/Support/SNMP/do/BrowseMIB.do?local=en&step=2&mibName=OSPF-MIB

PIM uses this CISCO-PIM-MIB http://tools.cisco.com/Support/SNMP/do/BrowseMIB.do?local=en&step=2&mibName=CISCO-PIM-MIB

ISIS uses this http://tools.cisco.com/Support/SNMP/do/BrowseMIB.do?local=en&step=2&mibName=CISCO-IETF-ISIS-MIB

**Comment by garnier-quentin** [comment]
I need snmpwalks to see datas. Thanks kadrika.

**Comment by kadrika** [comment]
I sent you the snmpwalks by e-mail.
Also I checked and it seems that for the ASR9010 the standard cisco plugin when checking CPU and Memory, But the environment does not work. Can you check that?

**Comment by kadrika** [comment]
Any update on this?

**Comment by garnier-quentin** [comment]
Hi kadrika,

Not in my priority. I will do the interfaces mode first.

**Comment by garnier-quentin** [comment]
ospf, pim and isis in other ticket. I have add in standard the temperature.
