### ISSUE TITLE
[os::linux::local::plugin] --mode=ntp: find command path automatically

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3901]
if chronyc or ntpq are not present on the default path actually we need to specify on the command path. It should be nice to find the command path automatically by the plugin.

Maybe a command like `which`could be used to find the correct path. Maybe this could be interessting also for other "local" modes.
```
which chronyc
/usr/bin/chronyc
```
PS: this functionality has to verify that the used command like `which` is installed

This feature allows to monitor Linux using ssh more efficient when there are different distributions and versions are present.

**Comment by garnier-quentin** [comment]
```which``` lookup up in the ```PATH```. So the plugin doesn't work to find out the command, it won't work with ```which```.

**Comment by joschi99** [comment]
My idea wos to try to find out with `which` the correct path for ntpq/chronyc so in this case it not shoud necessary to configure them. If there is no result you can switch back to the standard behaviour.
We have for example on RHEL 7 ntpd installed (not chrony) where the ntpq is located under `/usr/sbin`, but the plugin looks into `/usr/bin` and will not find any valid command.

The approach could be similar to ntp-mode=all, where you try with both commands and the command which will respond is used.

**Comment by garnier-quentin** [comment]
But the mode ```ntp``` doesn't use the path to execute the command (so it use the variable ```PATH```). Exactly like the ```which``` command:
```
which  returns the pathnames of the files (or links) which would be executed in the current environment, had its arguments been given as commands in a strictly POSIX-conformant shell.  It does this by searching the PATH for executable files matching the names of the  arguments.  It does not canonicalize path names.
```

**Comment by joschi99** [comment]
I understand what you mean but let me show you a simple real case:
```
centreon_plugin.pl --hostname=<IP> --ssh-backend=sshcli --ssh-username=<user> --sshcli-option='-o=StrictHostKeyChecking=no' --plugin=os::linux::local::plugin --mode=ntp --ntp-mode=all --filter-name= --filter-state= --warning-peers= --warning-offset=-20000:20000 --warning-stratum= --critical-peers=1: --critical-offset=-50000:50000 --critical-stratum= --ssh-port=22 --command-path= --debug
CRITICAL: Number of ntp peers: 0 | 'peers.detected.count'=0;;1:;0;
sh: ntpq: command not found
```

I logon on the remote system with the monitoring user
```
-sh-4.2$ which ntpq
/usr/sbin/ntpq
```

Now I execute the same command with command-path:

```
centreon_plugin.pl --hostname=<IP> --ssh-backend=sshcli --ssh-username=<user> --sshcli-option='-o=StrictHostKeyChecking=no' --plugin=os::linux::local::plugin --mode=ntp --ntp-mode=all --filter-name= --filter-state= --warning-peers= --warning-offset=-20000:20000 --warning-stratum= --critical-peers=1: --critical-offset=-50000:50000 --critical-stratum= --ssh-port=22 --command-path='/usr/sbin' --verbose
OK: Number of ntp peers: 2 - All peers are ok | 'peers.detected.count'=2;;1:;0; '<IP>#peer.time.offset.milliseconds'=-0.415ms;;;0; '<IP>#peer.stratum.count'=3;;;0; '<IP>#peer.time.offset.milliseconds'=0.484ms;;;0; '<IP>#peer.stratum.count'=3;;;0;
Peer '<IP>' [type: unicast] [reach: 377] [state: selected for synchronization]
Peer '<IP>' [type: unicast] [reach: 377] [state: included in the final selection set]
```

The plugin now finds the command ntpq and the execution works fine. It seems that you are searching in a predefined path and if the command is not there the plugin returns a error. You are not searching the command in the defined `PATH` directories.
To use `which `was only a proposal, but it should be enough to consider the `PATH`. In this case the plugin should be more flexible. What do you think?

**Comment by garnier-quentin** [comment]
Could you test the first command with that archive ? https://github.com/centreon/centreon-plugins/archive/refs/heads/command-path-exec.zip

Maybe a bug ;)

**Comment by joschi99** [comment]
Have done a quick test but still same behaviour

**Comment by garnier-quentin** [comment]
Sorry i missed something. if you can redownload it and retest it ?

**Comment by joschi99** [comment]
Always still the same, sorry

**Comment by garnier-quentin** [comment]
It's weird. Need to do a session with you.

**Comment by joschi99** [comment]
no problem, tomorrow 3pm?

**Comment by garnier-quentin** [comment]
Ok. invitation sent.

**Comment by garnier-quentin** [comment]
When we execute ssh command directly we don't have a login shell. The workaround:
```
 --command='bash' --command-options="-l -c 'ntpq -p -n'"
```
