### ISSUE TITLE
storage::hp::p2000::xmlapi::plugin MSA 2060 Login authentification failed

### ISSUE THREAD

**Issue by TheBlaide** [centreon/centreon-plugins#3903]
Hello,

I'm not able to get the plugin storage::hp::p2000::xmlapi::plugin working with my first  MSA 2060.
All my olders array are working fine with the plugin (2040 & 2050)

With the following command, I'm keeping having the followig error 

/usr/lib/centreon/plugins//centreon-plugins/centreon_plugins.pl --plugin=storage::hp::p2000::xmlapi::plugin --hostname=172.31.72.206 --verbose --mode=health  --username=**** --password=***** --port=443 --proto=https --http-backend=curl --curl-opt="CURLOPT_SSL_VERIFYPEER => 0" --verbose

UNKNOWN: Login authentification failed (return-code: 2).

i'm encolsing the CLI REF Guide for the array.

[HPE MSA 106020602062 CLI Reference Guide-a00105313en_us.pdf](https://github.com/centreon/centreon-plugins/files/9581815/HPE.MSA.106020602062.CLI.Reference.Guide-a00105313en_us.pdf)

Regards,

Blaise

**Comment by Sims24** [comment]
Hi, 

Ok I see. They do not allow md5 hash anymore and require sha256. 

We'll add this to the backlog and will ask you to test the fix/feature. 

Thanks

**Comment by garnier-quentin** [comment]
New option --digest-sha256: https://github.com/centreon/centreon-plugins/pull/3907

**Comment by TheBlaide** [comment]
Thanks a lot. it works just fine.

**Comment by garnier-quentin** [comment]
Thanks for your feedback!
