### ISSUE TITLE
[snmp_standard::plugin] mode=uptime - Improve return

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon-plugins#391]
Hello,
I propose you to improve the return of "snmp_standard::mode::uptime" in order to display a full uptime as "System uptime is: 30 days 20 Hours 24 Minutes 23 Seconds".

at the line 93 of snmp_standard/mode/uptime.pm:
defined($self->{option_results}->{seconds}) ? floor($value / 100) . " seconds" : floor($value / 100 / (24 * 60 * 60)) . " days " . floor($value / 100 / (60 * 60))%24 . " Hours " . floor($value / 100 / 60)%60 . " Minutes " . floor($value / 100)%60 . " Seconds" ));

instead of:
defined($self->{option_results}->{seconds}) ? floor($value / 100) . " seconds" : floor($value / 86400 / 100) . " days" ));

**Comment by kadrika** [comment]
I would also like it - if the system uptime would be displayed more detailed.

**Comment by maksimatveev** [comment]
@benoitb21 , +

**Comment by benoitb21** [comment]
Pull request #392
