### ISSUE TITLE
UNKNOWN: No entry found (maybe you should reload cache file) 

### ISSUE THREAD

**Issue by sanctifie** [centreon/centreon-plugins#3912]
Hello, I have this result:
perl centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=172.15.32.290 --snmp-version='2c' --snmp-username='' --authpassphrase='' --authprotocol='' --privpassphrase='' --privprotocol='' --snmp-community='resmobile' --redis-server=10.195.143.69:6719 --redis-db=6  --interface='^Gi1/0/24$' --name  --add-errors --warning-in-discard='' --critical-in-discard='' --warning-out-discard='' --critical-out-discard='' --warning-in-error='' --critical-in-error='' --warning-out-error='' --critical-out-error=''

UNKNOWN: No entry found (maybe you should reload cache file)

the same thing when I replace the name of the interface by the id

perl centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=172.15.32.290 --snmp-version='2c' --snmp-username='' --authpassphrase='' --authprotocol='' --privpassphrase='' --privprotocol='' --snmp-community='resmobile' --redis-server=10.195.143.69:6719 --redis-db=6  --interface='10123' --name  --add-errors --warning-in-discard='' --critical-in-discard='' --warning-out-discard='' --critical-out-discard='' --warning-in-error='' --critical-in-error='' --warning-out-error='' --critical-out-error=''

any idea how to solve it

**Comment by sanctifie** [comment]
yes it working

**Comment by garnier-quentin** [comment]
Could you provide the output ?

**Comment by sanctifie** [comment]
[root@localhost centreon_plugins]# perl centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=172.15.32.290 --snmp-version='2c' --snmp-username='' --authpassphrase='' --authprotocol='' --privpassphrase='' --privprotocol='' --snmp-community='resmobile' --redis-server=10.195.143.69:6719 --redis-db=6    --name  --add-errors --warning-in-discard='' --critical-in-discard='' --warning-out-discard='' --critical-out-discard='' --warning-in-error='' --critical-in-error='' --warning-out-error='' --critical-out-error=''
OK: All interfaces are ok |

**Comment by garnier-quentin** [comment]
With the --verbose option

**Comment by sanctifie** [comment]
perl centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=172.15.32.290 --snmp-version='2c' --snmp-username='' --authpassphrase='' --authprotocol='' --privpassphrase='' --privprotocol='' --snmp-community='resmobile' --redis-server=10.195.143.69:6719 --redis-db=6   --name  --add-errors --warning-in-discard='' --critical-in-discard='' --warning-out-discard='' --critical-out-discard='' --warning-in-error='' --critical-in-error='' --warning-out-error='' --critical-out-error='' --verbose
OK: All interfaces are ok | 'packets_discard_in_Gi1/0/1'=0.00%;;;0;100 'packets_error_in_Gi1/0/1'=0.00%;;;0;100 'packets_discard_out_Gi1/0/1'=0.00%;;;0;100 'packets_error_out_Gi1/0/1'=0.00%;;;0;100 'packets_crc_in_Gi1/0/1'=0.00%;;;0;100 'packets_discard_in_Gi1/0/2'=0.00%;;;0;100 'packets_error_in_Gi1/0/2'=0.00%;;;0;100 'packets_discard_out_Gi1/0/2'=0.00%;;;0;100 'packets_error_out_Gi1/0/2'=0.00%;;;0;100 'packets_crc_in_Gi1/0/2'=0.00%;;;0;100 'packets_discard_in_Gi1/0/3'=0.00%;;;0;100 'packets_error_in_Gi1/0/3'=0.00%;;;0;100 'packets_discard_out_Gi1/0/3'=0.00%;;;0;100 'packets_error_out_Gi1/0/3'=0.00%;;;0;100 'packets_crc_in_Gi1/0/3'=0.00%;;;0;100 'packets_discard_in_Gi1/0/4'=0.00%;;;0;100 'packets_error_in_Gi1/0/4'=0.00%;;;0;100 'packets_discard_out_Gi1/0/4'=0.00%;;;0;100 'packets_error_out_Gi1/0/4'=0.00%;;;0;100 'packets_crc_in_Gi1/0/4'=0.00%;;;0;100 'packets_discard_in_Gi1/0/5'=0.00%;;;0;100 'packets_error_in_Gi1/0/5'=0.00%;;;0;100 'packets_discard_out_Gi1/0/5'=0.00%;;;0;100 'packets_error_out_Gi1/0/5'=0.00%;;;0;100 'packets_crc_in_Gi1/0/5'=0.00%;;;0;100 'packets_discard_in_Gi1/0/6'=0.00%;;;0;100 'packets_error_in_Gi1/0/6'=0.00%;;;0;100 'packets_discard_out_Gi1/0/6'=0.00%;;;0;100 'packets_error_out_Gi1/0/6'=0.00%;;;0;100 'packets_crc_in_Gi1/0/6'=0.00%;;;0;100 'packets_discard_in_Gi1/0/9'=0.00%;;;0;100 'packets_error_in_Gi1/0/9'=0.00%;;;0;100 'packets_discard_out_Gi1/0/9'=0.00%;;;0;100 'packets_error_out_Gi1/0/9'=0.00%;;;0;100 'packets_crc_in_Gi1/0/9'=0.00%;;;0;100 'packets_discard_in_Gi1/0/23'=0.00%;;;0;100 'packets_error_in_Gi1/0/23'=0.00%;;;0;100 'packets_discard_out_Gi1/0/23'=0.00%;;;0;100 'packets_error_out_Gi1/0/23'=0.00%;;;0;100 'packets_crc_in_Gi1/0/23'=0.00%;;;0;100 'packets_discard_in_Gi1/0/24'=0.00%;;;0;100 'packets_error_in_Gi1/0/24'=0.00%;;;0;100 'packets_discard_out_Gi1/0/24'=0.00%;;;0;100 'packets_error_out_Gi1/0/24'=0.00%;;;0;100 'packets_crc_in_Gi1/0/24'=0.00%;;;0;100 'packets_discard_in_Vl11'=0.00%;;;0;100 'packets_error_in_Vl11'=0.00%;;;0;100 'packets_discard_out_Vl11'=0.00%;;;0;100 'packets_error_out_Vl11'=0.00%;;;0;100 'packets_crc_in_Vl11'=0.00%;;;0;100
Interface 'Vl1' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/1' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/2' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/3' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/4' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/5' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/6' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/7' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/8' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/9' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/10' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/11' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/12' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/13' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/14' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/15' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/16' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/17' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/18' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/19' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/20' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/21' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/22' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/23' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/24' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Gi1/0/25' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/26' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/27' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Gi1/0/28' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Vl11' Packets In Discard : 0.00% (0), Packets In Error : 0.00% (0), Packets Out Discard : 0.00% (0), Packets Out Error : 0.00% (0), Packets In Crc : 0.00% (0)
Interface 'Nu0' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'Fa0' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped, Packets In Crc : skipped
Interface 'StackPort1' Packets In Discard : skipped, Packets In Error : skipped, Packets Out Discard : skipped, Packets Out Error : skipped

**Comment by garnier-quentin** [comment]
It's weird. it should give you the interface with: ```--interface='^Gi1/0/24$' --name```
