### ISSUE TITLE
CRITICAL: Interface '' Traffic In

### ISSUE THREAD

**Issue by sanctifie** [centreon/centreon-plugins#3915]
Bonjour, j'ai cette erreur sur ma commande :

CRITICAL: Interface '' Traffic In : 2.02Mb/s (100.80%) | 'traffic_in'=2015914.67b/s;0:1700000;0:1900000;0;2000000 'traffic_out'=81928.00b/s;0:1700000;0:1900000;0;2000000

voici ma commande

perl centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=10.155.284.150 --snmp-version='2c' --snmp-username='' --authpassphrase='' --authprotocol='' --privpassphrase='' --privprotocol='' --snmp-community='ris@rrivildo' --redis-server=10.191.272.89:6349 --redis-db=6  --interface='11101' --add-status --add-traffic --warning-in-traffic='85' --critical-in-traffic='95' --warning-out-traffic='85' --critical-out-traffic='95' --oid-display='ifAlias' --no-skipped-counters

**Comment by garnier-quentin** [comment]
It's a 2Mb interface speed ? You can force the speed with --speed option

**Comment by sanctifie** [comment]
Ok thank you
