### ISSUE TITLE
Problème plugin fresh install  (UNKNOWN: SNMP Table Request : Timeout)

### ISSUE THREAD

**Issue by Bochi75** [centreon/centreon-plugins#3918]
Hello,

I just finalize an installation of Centreon on Google Cloud, but I'm facing an issue an issue with my cisco Plugin, from my first poller I can request a cisco device using snmp but from my another one I not able the error that I encountered is : 

UNKNOWN: SNMP Table Request : Timeout.

Request is the same on both poller : 

/usr/lib/centreon/plugins//centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=X.X.X.X --snmp-version='2c' --snmp-community='XXXXX'  --interface='^Gi1/1/1$' --name --add-status --add-traffic --warning-in-traffic='70' --critical-in-traffic='80' --warning-out-traffic='70' --critical-out-traffic='80'

Thanks in advance for your help.

**Comment by Bochi75** [comment]
Hello Quentin,

Yes, It's working with --snmp-autoreduce..

Could you explain why ?

Regards,

**Comment by garnier-quentin** [comment]
Your equipement doesn't handle big SNMP requests well. Or it's an issue about some OIDs not responding: in protocol SNMP, you tell: from that OID i want the next X OIDs.

**Comment by Bochi75** [comment]
Do you know how can I do to add this option in my request using GUI ?

<img width="635" alt="Gui" src="https://user-images.githubusercontent.com/114311163/192269552-3596fcba-cde9-4e8e-872e-2b5759f28739.png">

**Comment by chef-oni** [comment]
hi i am trying to monitore the ressource of my local windows (cpu/memory..)
i get this info " UNKNOWN: SNMP Table Request: Timeout" 
with this command   ((( /usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=17*.*.* --snmp-version='2c' --snmp-community='plublic'  --warning-memory='40' --critical-memory='80')) 

any suggestion

**Comment by garnier-quentin** [comment]
Have you tried the option --snmp-autoreduce ?

**Comment by chef-oni** [comment]
> Have you tried the option --snmp-autoreduce ?

how can i do it?

**Comment by garnier-quentin** [comment]
You add it in your command line or you add it to the macro SERVICEEXTRAOPTIONS

**Comment by chef-oni** [comment]
how?

**Comment by garnier-quentin** [comment]
You should use nsclient. snmp agent is deprecated on windows.

**Comment by chef-oni** [comment]
thank you
can you give more detailed step on hiw to resolve the problem (UNKNOWN: SNMP Table Request: Timeout)
and how to use (--snmp-autoreduce)

**Comment by garnier-quentin** [comment]
Add it to your command line to test it: ``` /usr/lib/centreon/plugins//centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=17*.. --snmp-version='2c' --snmp-community='plublic' --warning-memory='40' --critical-memory='80' --snmp-autoreduce```

Check centreon documentation and ask to slack/thewatch to have help

**Comment by garnier-quentin** [comment]
If you have the same error, use nsclient.

**Comment by chef-oni** [comment]
@garnier-quentin 
i faced this errer
i created a command to check for network adapter on windows 10 using snmp
this is the commande ((/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=interfaces --hostname=1*.*.*.* --snmp-version='2c'  --add-global)) 
and this is the inforation status
 ((UNKNOWN: Cannot write statefile '/var/lib/centreon/centplugins/snmpstandard_1*.*.*.*_161_interfaces_a181a603769c1f98ad927e7367c7aa51_a181a603769c1f98ad927e7367c7aa51_2d53ab037d84147fd7d582422c23892d'. Need write permissions on file.))
