### ISSUE TITLE
[network::nortel::standard::snmp::plugin] --mode=interfaces, --add-duplex-status show (duplex: n/a) with VSP extreme networks

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3920]
Hi,

Centreon-plugins (centreon-plugin-Network-Extreme-Snmp-20220913-081426.el7.centos.noarch) search duplexstatus with :

$self->{oid_duplexstatus} = '.1.3.6.1.2.1.10.7.2.1.19';

but VSP extreme networks has in his mib : 
.1.3.6.1.4.1.2272.1.4.10.1.1.13 (rapidCity.rcMgmt.rcChassis.rcPort.rcPortTable.rcPortEntry.rcPortOperDuplex)

Mib : 
[VOSS4900.8.3.1.0_mib_sup.txt](https://github.com/centreon/centreon-plugins/files/9644680/VOSS4900.8.3.1.0_mib_sup.txt)

I send you the snmpwalk by email.
Thanks.

**Comment by garnier-quentin** [comment]
The standard OID is not ok ?

**Comment by gagzou** [comment]
Alas, no ....
snmpwalk -ObentU -v 3 -u blablabla -a SHA -A 'xxxxxx' -x AES -X 'xxxxxx' -l authpriv x.x.x.x 1.3.6.1.2.1.10.7.2.1.19
.1.3.6.1.2.1.10.7.2.1.19 = No Such Object available on this agent at this OID

**Comment by gagzou** [comment]
Apparently, for 1.3.6.1.4.1.2272.1.4.10.1.1.13 : 
0 => 'unknown', 1 => 'halfDuplex', 2 => 'fullDuplex'

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3932

**Comment by garnier-quentin** [comment]
thanks for the feedback!
