### ISSUE TITLE
[storage::emc::unisphere::restapi::plugin] add quota for mode::storageresources

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3922]
Hi,

Is it possible to add quota supervision for unisphere ?

![Unisphere](https://user-images.githubusercontent.com/61595839/192250870-e685716c-152f-49c8-9448-7a40431d5f0d.jpg)

Api documentation : 
[unity-restapi-refg_en-us_reference-guide8.pdf](https://github.com/centreon/centreon-plugins/files/9645272/unity-restapi-refg_en-us_reference-guide8.pdf)

Best regards.

**Comment by garnier-quentin** [comment]
Could you provide the curl command and result ?

**Comment by gagzou** [comment]
Apparently it's more complicated.
I'll ask Dell about it and get back.
Please put the request on hold.

**Comment by gagzou** [comment]
Hi,
We can have the names of the quotas:
https://x.x.x.x/api/types/quotaConfig/instances?fields=filesystem.name
and then, we can have the sizes of the soft/hard quotas and the size:
https://x.x.x.x/api/instances/quotaConfig/quotaconfig_171798691851_7?fields=filesystem.name%2CtreeQuota.hardLimit%2CtreeQuota.softLimit%2CtreeQuota.path%2CtreeQuota.state%2CtreeQuota.sizeUsed
