### ISSUE TITLE
Add option on SNMP Query

### ISSUE THREAD

**Issue by Bochi75** [centreon/centreon-plugins#3925]
Hello all,

I would like to add an option in my SNMP query "--snmp-autoreduce", how can I do ?

<img width="538" alt="image" src="https://user-images.githubusercontent.com/114311163/192282705-cead621b-b434-466b-b8eb-7418dd8b43cf.png">

many thank in advance for your feedback.

**Comment by garnier-quentin** [comment]
add it in EXTRAOPTIONS macro

**Comment by Bochi75** [comment]
What is the values that I need to put on this filed ?

**Comment by garnier-quentin** [comment]
You need to add the option: ```--snmp-autoreduce``` for the service on error.

**Comment by Bochi75** [comment]
Ok understand but how to add it in the form, I need to add like that : 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/114311163/192290150-24578734-160e-4703-ad5d-a26161b46bd3.png">

**Comment by garnier-quentin** [comment]
Exactly!

**Comment by Bochi75** [comment]
I will check and I let you know.
