### ISSUE TITLE
[apps:protocols:ftp] Not working with sftp

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#394]
Hello,

I try to use the following command on a sftp serveur but there is a error message:

centreon_plugins.pl --plugin=apps::protocols::ftp::plugin --mode=login --hostname=10.30.2.38 --username='centreon' --password='centreon'
CRITICAL: Unable to connect to FTP: Can't open tcp connection! (10.30.2.38:21) |

I try to use the option --ssl but i have the exacte same message, is the plugin working with sftp ? If not is planned in a future version ?

Regards

**Comment by garnier-quentin** [comment]
It's not working with sftp. sftp is not the same protocol than ftp. To do that, i need to create another plugin and bind a library to manage sftp
