### ISSUE TITLE
Synology NAS plugin reporting CPU constantly 100% utiliz

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#3942]
We use the last plugin version 220616 and the plugin " plugin=storage::synology::snmp::plugin --mode=cpu".

The plugin uses snmp_standard::mode::cpu for CPU.
The OID behind it my $oid_cputable = '.1.3.6.1.2.1.25.3.3.1.2';
This works well for some Synology NAS models like the DS213j.

We now have a NAS DS216se that always returns 100% using this standard OID. 

snmpwalk -c 'xxx' -v 2c xxx.xxx.xxx.xxx .1.3.6.1.2.1.25.3.3.1.2
HOST-RESOURCES-MIB::hrProcessorLoad.196608 = INTEGER: 100

However, if we use the Synolog OIDs we could return more exat values.

-bash-4.2$ snmpwalk -c 'xxx' -v 2c xxx.xxx.xxx .1.3.6.1.4.1.2021.11.10.0
UCD-SNMP-MIB::ssCpuSystem.0 = INTEGER: 4
-bash-4.2$ snmpwalk -c 'xxx!' -v 2c xxx.xxx.xxx .1.3.6.1.4.1.2021.11.9.0
UCD-SNMP-MIB::ssCpuUser.0 = INTEGER: 93

Can we change the plugin to a dedicated cpu mode for Synology

![image](https://user-images.githubusercontent.com/46994680/193056086-8f287cbe-8e1e-4d28-9770-a727832c998a.png)

Here the link for the synology MIB

https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf

Thanks a lot

Kind regards

**Comment by garnier-quentin** [comment]
You can use the plugin os::linux::snmp and the mode cpu-detailed.

**Comment by rmorandell-pgum** [comment]
ok for workaround this is fine. But for the plugin would maybe be better to sum the User and the System CPU ?

![image](https://user-images.githubusercontent.com/46994680/193057491-bce0f5c2-fd12-4a79-94b0-d6d0d283f1db.png)

**Comment by rmorandell-pgum** [comment]
Often the values of snmp linux standard are unfortunately completely wrong because fixed at 100 although the real ones are not 5%.

![image](https://user-images.githubusercontent.com/46994680/193062289-94f99dea-ef33-45f7-82a1-180d2fe4792f.png)

**Comment by garnier-quentin** [comment]
You have the option --use-ucd: https://github.com/centreon/centreon-plugins/pull/3943
