### ISSUE TITLE
[os::aix::local::plugin] --mode=errpt: UNKNOWN: Command error: errpt: - 0315-182 Bad value supplied for error type

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3949]
using the plugin with this options
`--plugin=os::aix::local::plugin --mode=errpt  --error-type= --error-class=  --error-id=  --filter-resource=  --filter-id=`
this error will be raised:
`UNKNOWN: Command error: errpt: - 0315-182 Bad value supplied for error type ...`

Removing the options `--error-type= --error-class=  --error-id=` or option with values like `--error-type=INFO --error-class=S --error-id=  --filter-resource=  --filter-id=` works. Empty options raise error.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3951
