### ISSUE TITLE
[/usr/lib64/nagios/plugins/check_icmp] customize command with $_SERVICEEXTRAOPTIONS$

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#3957]
Hi,

It is not possible to customize the command through 'EXTRAOPTIONS' as with other plugin packs.
The base command 'base_centreon_ping' does not have "$_SERVICEEXTRAOPTIONS$."
As a result, it is not natively possible to extend the possibilities of the command.

Best regards.

**Comment by garnier-quentin** [comment]
We can add that option in the pack.

**Comment by gagzou** [comment]
Ok , thanks.

**Comment by garnier-quentin** [comment]
it's for the next release
