### ISSUE TITLE
[database::mssql::plugin] - new mode job duration

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3958]
create a new mode to monitor the job duration for MS SQL with

filter for job status
filter for job name
filter for last_run
thresholds for duration
Output: jobname, status, duration
 

SQL (same query as failed jobs)
`SELECT j.[name] AS [JobName], run_status, run_duration, h.run_date AS LastRunDate, h.run_time AS LastRunTime, CASE  WHEN h.[run_date] IS NULL OR h.[run_time] IS NULL THEN NULL ELSE datediff(Minute, CAST( CAST(h.[run_date] AS CHAR(8)) + ' ' + STUFF( STUFF(RIGHT('000000' + CAST(h.[run_time] AS VARCHAR(6)), 6) , 3, 0, ':') , 6, 0, ':') AS DATETIME), current_timestamp) END AS [MinutesSinceStart]  FROM msdb.dbo.sysjobhistory h  INNER JOIN msdb.dbo.sysjobs j ON h.job_id = j.job_id  WHERE j.enabled = 1 AND h.instance_id IN (SELECT MAX(h.instance_id) FROM msdb.dbo.sysjobhistory h GROUP BY (h.job_id));`
Output sample:
![image](https://user-images.githubusercontent.com/6400595/194004996-1d2a5914-39c6-40ef-8d18-ae5804eab231.png)

run_duration is in HHMMSS (https://learn.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobhistory-transact-sql?view=sql-server-ver16)

**Comment by garnier-quentin** [comment]
Have you tested the mode ```failed-jobs``` ? You have the duration

**Comment by joschi99** [comment]
have done a check. duration is there as variable on --warning-status and  --critical-status, but not as performance data. Have done a quick test and seems working `--critical-status='%{duration} > 10`

Probably it should be enough add the duration/job on the performance data. It should possible?
