### ISSUE TITLE
sensorip mode=sensors, status different from extended status information

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#396]
Hello,

With the plugin hardware-sensors-sensorip-snmp (version 2), i have a critical status but in the status information it's "status is normal":

centreon_plugins.pl --plugin=hardware::sensors::sensorip::snmp::plugin --mode=sensors --hostname=x.x.x.x --snmp-version='1' --snmp-community='public' --component='' --verbose

Status: CRITICAL
Status information: CRITICAL: Humidity sensor Ventilation Clim 2 is 100%
Extended status information:
[...] Humidity sensor ventilation clim 2 status is normal [instance = 4, value = 100%] [...]

Thank you

**Comment by garnier-quentin** [comment]
I think the critical status is normal. The humidity is over the critical value. Could you get the perfdata result ? 100% is little high for humidity ;)

**Comment by garnier-quentin** [comment]
No news. I close it.
