### ISSUE TITLE
Detec brute force attack on Windows server

### ISSUE THREAD

**Issue by Sergi-29** [centreon/centreon-plugins#3961]
Hello,
I need supervising a Veeam server deliberately called "veeam_server".
This server doesn't backup anything. His only role is to be a "honey pot" in case of intrusion or attack of our datacenter.
This server is not on the active directory, is a Windows OS. In case of attack I expect the intruder to brute force this Veeam server. Since it's known, this is one of the first things attackers do when they're in the system.
We're using Centreon platform and need a plugin/program able to detect brute force attack on Windows Server 2019.

Thank You.
Sergi

**Comment by garnier-quentin** [comment]
How could we detect that ?

**Comment by garnier-quentin** [comment]
Please comment it, if you have some feedbacks
