### ISSUE TITLE
[database::oracle::plugin]  - asm-diskgroup-usage returns "Use of uninitialized value"

### ISSUE THREAD

**Issue by trihta** [centreon/centreon-plugins#3964]
When running command

`./centreon_plugins.pl --plugin database::oracle::plugin --mode asm-diskgroup-usage --username myusername --password mypass --hostname orasrv.domain.tld --servicename myinstance`

I receive at the beginning of the output the error  "Use of uninitialized value in numeric gt (>) at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/output.pm line 709" for each of the ASM groups" After those errors the output seems to be correct (e.g. OK: Diskgroup 'ARHFRA' status: MOUNTED, Disk  Total: 300.00 GB Used: 140 ..." 

Also tried running the command with additional parameters specified for asm-diskgroup-usage in help, but to no avail - the problem remains.

What am I doing wrong or is it a bug?

Oracle ver: 19c
Centreon: Global Version: (dev)

**Comment by garnier-quentin** [comment]
Could you provide the result of the following request please ?
```
SELECT name, state, type, total_mb, usable_file_mb, offline_disks, FREE_MB FROM V$ASM_DISKGROUP
```

**Comment by trihta** [comment]
Sure: 

```
NAME                           STATE       TYPE     TOTAL_MB USABLE_FILE_MB OFFLINE_DISKS    FREE_MB
------------------------------ ----------- ------ ---------- -------------- ------------- ----------
ARHFRA                         MOUNTED     EXTERN     307200         275944             0     275944
ARCHIVE                        MOUNTED     EXTERN    3686400         605000             0     605000
ARHREDO1                       MOUNTED     EXTERN      30720          11972             0      11972
ARHREDO2                       MOUNTED     EXTERN      30720          22296             0      22296
DATA                           CONNECTED   EXTERN    9011200         883572             0     883572
FRA                            CONNECTED   EXTERN     716800         170016             0     170016
MGMT                           MOUNTED     EXTERN      40960          15656             0      15656
REDO1                          CONNECTED   EXTERN      30720          11092             0      11092
REDO2                          CONNECTED   EXTERN      30720          21416             0      21416
VOCR                           MOUNTED     NORMAL       3072            548             0       2120

10 rows selected. 
```

**Comment by garnier-quentin** [comment]
thanks. it will fixed with the pr: https://github.com/centreon/centreon-plugins/pull/3965
