### ISSUE TITLE
cloud::azure::storage::storageaccount::plugin monitor a minimum transaction number in a specified time-range

### ISSUE THREAD

**Issue by TheBlaide** [centreon/centreon-plugins#3966]
Hi there,

I want to monitor a storage account file activity (transactions) hosting a third party backup tool backup destination (QNAP Hybrid backup Sync HBS)

To do so i wanted to monitor a minumum transactions number (warning 10 Critical 0) on a specified interval, let  say 24 h for my daily backup.

with zero transactions for 24h i'll know that there was no backup activity at all

Here is my command line

./centreon_plugins.pl --plugin=cloud::azure::storage::storageaccount::plugin --custommode=api --mode=transactions-count --subscription=xxx --tenant=xxx --client-id=xxx --client-secret=xxx --api-version=2021-05-01 --resource=/subscriptions/xxx/resourceGroups/RgTat/providers/Microsoft.Storage/storageAccounts/mystorageaccount --resource-namespace=file --critical-transactions-total=0  --warning-transactions-total=0 

is it possible to add a time range or period parameter and swap the warning and critical threshold ? 

Regards,

**Comment by garnier-quentin** [comment]
Like that: ```--critical-transactions-total=1: --warning-transactions-total=11:```

**Comment by TheBlaide** [comment]
... --timeframe ...
