### ISSUE TITLE
[os::linux::local::plugin] Calculated value of the max open files and percentage thresholds in "open-files" mode

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#3969]
Hello.

Now the "**open-files**" mode assumes that we must set the threshold values statically.
Please make a small improvement to this mode.

We can get the system open file threshold with the command `cat /proc/sys/fs/nr_open`
This value can be set to default as the maximum if not explicitly set.
This will add convenient percentage WARN/CRIT thresholds.

**Comment by garnier-quentin** [comment]
The following value ```/proc/sys/fs/nr_open``` is by process. So we cannot use that. We should use: ```/proc/sys/fs/file-max``` ?

**Comment by Aleksey-Maksimov** [comment]
Okay, let's not use "/proc/sys/fs/nr_open".

If we analyze the situation in the context of each process, then there may be a problem when the number of open files approaches the limit that is set for this process.

The question is, can we add per-process analysis (e.g. "ls /proc/$pid/fd/ | wc -l") versus the limit for that process ("cat /proc/192/limits | grep files" ) ?
We could add options like "--check-per-process" and thresholds like "--warning-files-open-per-process" and "--critical-files-open-per-process".

**Comment by garnier-quentin** [comment]
I will create many perfdatas. But why not with an option.

**Comment by Aleksey-Maksimov** [comment]
OK. If you need anything from me, I'm ready to help.

**Comment by Aleksey-Maksimov** [comment]
Duplicated here
https://thewatch.centreon.com/ideas/os-linux-local-plugin-calculated-value-of-the-max-open-files-and-percentage-thresholds-in-open-files-mode-2623
