### ISSUE TITLE
Dell N Series wrong temperature

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#397]
I use the plugin network::dell::n4000::plugin to monitor some Dell N1500 series switches (PoE and no PoE). Using mode=environment there are also the temperatures from the various sensors that came back but always with a wrong value.
The correct SNMP OID for this switches are .1.3.6.1.4.1.674.10895.5000.2.6132.1.1.43.1.8.1.5.1

At the moment we use firmware 6.2.7.2, but at soon we will upgrade to 6.3.0.6.

![dell-n1524p](https://cloud.githubusercontent.com/assets/6400595/15044281/dc60ed52-12d3-11e6-8fa2-c00712a8e48d.png)

**Comment by garnier-quentin** [comment]
Could you give me the snmpwalk ?

**Comment by joschi99** [comment]
You will find the mibs and the snmpwalk for N1500 series

[Release 6.3.0.6-mibs.zip](https://github.com/centreon/centreon-plugins/files/251956/Release.6.3.0.6-mibs.zip)
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/251953/snmpwalk.txt)
[snmpwalk2.txt](https://github.com/centreon/centreon-plugins/files/251954/snmpwalk2.txt)

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by joschi99** [comment]
Hi Quentin,
i tested it and it works. Good job. Thanks.

Jochen

**Comment by garnier-quentin** [comment]
Thanks for the feedback and using plugins!
