### ISSUE TITLE
[os::linux::local::plugin] mode "uptime" - UNKNOWN: Wrong warning threshold

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#3970]
Hello.

I'm trying to use "**uptime**" mode and get a warning if the server has been up for more than 183 days.
But when specifying the threshold, I get the status "UNKNOWN"

```
# ./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=uptime --warning=‭15811200

UNKNOWN: Wrong warning threshold '‭15811200'.
```

What am I doing wrong?

**Comment by garnier-quentin** [comment]
Your equals seems wrong. Replace it.

**Comment by Aleksey-Maksimov** [comment]
The mode help says:

```
     --warning
             Threshold warning in seconds.
```

I don't understand what I did wrong.

**Comment by garnier-quentin** [comment]
![image](https://user-images.githubusercontent.com/9079781/194590078-08a005af-001d-4b62-8056-e42342e768ee.png)

Yo have a hidden character

**Comment by Aleksey-Maksimov** [comment]
oops... Thanks, Quentin.
Sorry for my stupidity :)
