### ISSUE TITLE
[os::linux::local::plugin] Adding support for timedatectl to "ntp" mode

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#3971]
Hello,

Many modern Linux systems that are part of **systemd** have the **systemd-timesyncd** service. 
If this service is used, then there are no such things as ntpd and chronyd in the system.

Please extend the "**ntp**" mode to work with the **timedatectl** utility.

```
# timedatectl status
               Local time: Fri 2022-10-07 18:33:28 MSK
           Universal time: Fri 2022-10-07 15:33:28 UTC
                 RTC time: Fri 2022-10-07 15:33:28
                Time zone: Europe/Moscow (MSK, +0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

```
# timedatectl timesync-status
       Server: 10.10.0.2 (srv-ntp.holding.com)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
         Leap: normal
      Version: 3
      Stratum: 3
    Reference: A05A409
    Precision: 1us (-23)
Root distance: 128.654ms (max: 5s)
       Offset: +6.303ms
        Delay: 1.544ms
       Jitter: 16.867ms
 Packet count: 17
    Frequency: +1.635ppm
```

Thank you.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.

**Comment by Aleksey-Maksimov** [comment]
Hello.

Was timedatectl functionality added to the plugin or did you just close it?

**Comment by fmattesct** [comment]
Hello, the functionality have not been added for now.
The topic have been closed following our new features/enhancements rules (see the closing comment above).

Thanks for your interest in Centreon

**Comment by Aleksey-Maksimov** [comment]
I created this thread.
https://thewatch.centreon.com/ideas/os-linux-local-plugin-adding-support-for-timedatectl-to-ntp-mode-2619
