### ISSUE TITLE
[database::oracle::plugin] fra-usage: Output diplays Argument "x,x" isn't numeric in addition ...

### ISSUE THREAD

**Issue by trihta** [centreon/centreon-plugins#3972]
When running command 
`./centreon_plugins.pl --plugin database::oracle::plugin --mode fra-usage --username myusernam --password mypassword --hostname oraserver.domain.tld --servicename instance`

I receive the following output:

`Argument "9,​46" isn't numeric in addition (+) at /usr/lib/nagios/plugins/centreon-plugins/database/oracle/mode/frausage.pm line 135.
Argument "9,​46" isn't numeric in addition (+) at /usr/lib/nagios/plugins/centreon-plugins/database/oracle/mode/frausage.pm line 136.
Argument ",​06" isn't numeric in addition (+) at /usr/lib/nagios/plugins/centreon-plugins/database/oracle/mode/frausage.pm line 135.
OK: Recovery area used: 9.00 %, reclaimable: 9.00 % - All recovery areas are ok ...`

Running the following two queries
`SELECT file_type, percent_space_used, percent_space_reclaimable FROM v$recovery_area_usage;
SELECT name, space_used, space_reclaimable, space_limit FROM v$recovery_file_dest;`

outputs:

```
FILE_TYPE               PERCENT_SPACE_USED PERCENT_SPACE_RECLAIMABLE
----------------------- ------------------ -------------------------
CONTROL FILE                             0                         0
REDO LOG                                 0                         0
ARCHIVED LOG                         68,86                     68,81
BACKUP PIECE            ,05                                        0
IMAGE COPY                               0                         0
FLASHBACK LOG                        11,09                      3,08
FOREIGN ARCHIVED LOG                     0                         0
AUXILIARY DATAFILE COPY                  0                         0

8 rows selected. 


NAME [...truncated spaces...] SPACE_USED SPACE_RECLAIMABLE SPACE_LIMIT
-----[...truncated dashes...]--------- ---------- ----------------- -----------
+FRA [...truncated spaces...] 5.5832E+11        5.0171E+11  6.9793E+11
```

Problem due to collation / localization or am I missing some optional parameter?

P.S.: Not related to this. Just thank you for quick fix of #3964

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3983
