### ISSUE TITLE
False Warning / Critical  --plugin=hardware::ups::apc::snmp::plugin

### ISSUE THREAD

**Issue by Cube38282** [centreon/centreon-plugins#3978]
Hello,

the thresholds for load / load_time do not work as expected.

**Example:**

Input:
 ./centreon_plugins.pl --plugin=hardware::ups::apc::snmp::plugin --mode=battery-status --hostname 10.10.10.10 --snmp-version 3 --snmp-username icinga --authpassphrase xxxx  --authprotocol SHA  --privprotocol AES  --privpassphrase xxxx --warning-time 60 --critical-time 30

Output:
CRITICAL: remaining time: 81.00 minutes | 'load'=100%;;;0;100 'load_time'=81.00m;0:60;0:30;0; 'voltage'=109V;;;; 'temperature'=26C;;;; 'replace_last_time'=42046025s;;;;

Expected:
Return should be OK as load_time (remaining Time) > warning / critical-load threshold

Thanks in advance.

**Comment by Sims24** [comment]
Hi, 

Please use the standard option format: https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

Note the ':'.

**Comment by Cube38282** [comment]
Thank you so much
