### ISSUE TITLE
[database::postgres::plugin] --mode=backends: UNKNOWN: Can't call method "is_version_minimum" on an undefined value

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3981]
Latest plugin version produce this error when using option --no-idle. Same command withouth this option is working. Using plugin version 20220616 works fine also with option --no-idle

**Comment by garnier-quentin** [comment]
Thanks for the issue: https://github.com/centreon/centreon-plugins/pull/3982
