### ISSUE TITLE
[storage::hp::3par::ssh::plugin] new modes have unknown options

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#3992]
The modes `cages` and `afc` have some unknown options:

cages:
- Unknown option: unknown-firmware-status (also warning/critical)
- Unknown option: unknown-self-status (also warning/critical)
- Unknown option: unknown-partner-status (also warning/critical)

afc
- Unknown option: Unknown option: warning-flashcache-volume-readhit (also critical)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/3994
