### ISSUE TITLE
Random "Authentication Unsuccessful" through storage::dell:me4

### ISSUE THREAD

**Issue by sskamesh** [centreon/centreon-plugins#3993]
Hello there,

We've been using this plugin for quite some time for our ME4 controllers through idrac plugin.

So far, it's been working fine until we upgraded our ME4084 firmware to GT280R010-01. It was working fine till GT280R009.

We just get "UNKNOWN: Login endpoint returns an error: 'Authentication Unsuccessful'" while using like below.

```
./check_hardware.pl --plugin=storage::dell::me4::restapi::plugin --mode=hardware --insecure --api-username=apiusername --api-password='apiuserpassword' --hostname=raidcontrollerhost

UNKNOWN: Login endpoint returns an error: 'Authentication Unsuccessful'
```

I can assure that the credentials are correct. Because its deployed through a script and it only shows the above error.

Has anyone been facing this issue recently or after upgrading the raid controller firmware?

Any help is appreciated.

If you'd like to know further details which could help debug this issue, I'll provide them at my best capacity.

Thanks!

**Comment by garnier-quentin** [comment]
Please try with the option: ```--digest-sha256```

**Comment by sskamesh** [comment]
hello @garnier-quentin,

I just get

"Unknown option: digest-sha256 at /path/to/framework/plugins/alternative/Getopt.pm line67"

I used it like this

```
./check_hardware.pl --plugin=storage::dell::me4::restapi::plugin --mode=hardware --insecure --digest-sha-256 --api-username=apiusername --api-password='apiuserpassword' --hostname=raidcontrollerhost
Unknown option: digest-sha256 at /path/to/framework/plugins/alternative/Getopt.pm line6
```

**Comment by garnier-quentin** [comment]
I don't know ```check_hardware.pl```. Maybe you should update your plugin

**Comment by sskamesh** [comment]
check_hardware.pl just redirects to where the centreon plugins are placed.

```
#!/usr/bin/perl
use strict;
use warnings;

BEGIN {
    push @INC, '/path/to/centreon/plugin';
    push @INC, '/path/to/perl/lib';
}

use centreon::plugins::script;
centreon::plugins::script->new()->run();
```

I'm using the updated plugins now (from releases page).

Thanks.

**Comment by garnier-quentin** [comment]
It's: ```--digest-sha256```. Not: ```--digest-sha-256```
