### ISSUE TITLE
[centreon-plugins.exe] mode centreon-plugins-version

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#3998]
Hello,

Here is the actual result for the last release of centreon_plugins.exe :
-c check_centreon_plugins -a 'apps::centreon::local::plugin' 'centreon-plugins-version'
OK: Centreon Plugins Global Version '(dev)'

Should it be possible to have the good value like it is for linux :
--plugin=apps::centreon::local::plugin --mode=centreon-plugins-version
OK: Centreon Plugins Global Version '20220913 (95fe7ce0a)'

To be complete, an extra option should show the nsclient++ version like the standard command -c check_version does.
We would know exactely what is deployed for each windows server.

Thanks

**Comment by garnier-quentin** [comment]
I'm going to add it in the next release version.
