### ISSUE TITLE
[os::windows::snmp::plugin] mode=service accents

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-plugins#400]
Bonjour,
Le mode "service" ne fonctionne pas pour les services comportant des accents.
Lors d'un snmpwalk (sur un 2008R2) les services comportant un accent ne sont pas converti depuis l'hexa. 

Exemple pour un service tel que "Appel de procédure distante (RPC)" le retour est :
SNMPv2-SMI::enterprises.77.1.2.3.1.1.34.65.112.112.101.108.32.100.101.32.112.114.111.99.195.169.100.117.114.101.32.100.105.115.116.97.110.116.101.32.40.82.80.67.41 = Hex-STRING: 41 70 70 65 6C 20 64 65 20 70 72 6F 63 C3 A9 64 75 72 65 20 64 69 73 74 61 6E 74 65 20 28 52 50 43 29 

Du coup le retour de la commande ci-dessous est en erreur :
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=xx.xx.xx.xx --snmp-version=2c --service='Appel de procédure distante (RPC)' --warning 1:

Cdlt

**Comment by garnier-quentin** [comment]
The Heximal comes from snmpwalk. To check accent, try to use regexp with '.' for example.

**Comment by Sims24** [comment]
Bastien told me that it does the tricks, I close this one.

Thanks,
