### ISSUE TITLE
os::windows::wsman::plugin --mode=time - CRITICAL: Time offset -7200 second(s): Local Time: 2022-10-19T13:58:50 (:Europe/Rome)

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4005]
Using wsman to monitor time and returned time ist UTC (Select * from Win32_UTCTime) and wil lnot correctly converted to the timezone (in our case Europe/Rome).
![image](https://user-images.githubusercontent.com/6400595/196713290-06a1a008-585d-4c89-a826-63c9bfc3e893.png)

**Comment by garnier-quentin** [comment]
Could you test with that version ? https://github.com/centreon/centreon-plugins/archive/refs/heads/fix-wsman-time-timezone.zip

**Comment by garnier-quentin** [comment]
I have done a fix. Could you redownload and test it again ?
