### ISSUE TITLE
[apps::monitoring::splunk::plugin] mode splunkd-health

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#4008]
Hello,

I've just tested this mode and i think something is missing in the OUTPUT :

OK:
checking features
    Feature 'file-monitor-input' health: 'green'
    Feature 'index-processor' health: 'green'
    Feature 'resource-usage' health: 'green'
    Feature 'search-scheduler' health: 'green'
    Feature 'workload-management' health: 'green'

Would there be something like "All features are OK" just after OK: ?

**Comment by garnier-quentin** [comment]
Indeed. Could you provide the --debug ?

**Comment by ritouret** [comment]
just sent by email
