### ISSUE TITLE
[apps::vmware::connector::plugin] mode=snapshot-vm: Show name of Snapshot

### ISSUE THREAD

**Issue by SimonH-AI** [centreon/centreon-plugins#4021]
Hi,
I'm trying to display the names of the snapshots, which were found by this plugin.
I found #695 and I don't know if this has already been implemented.
If its already implemented, how do I use it?

**Comment by garnier-quentin** [comment]
You have the name and the description of the snapshot.

**Comment by garnier-quentin** [comment]
Could you provide the --debug output ?

**Comment by SimonH-AI** [comment]
```
CRITICAL: Snapshots for VM older than 1 minutes: [Master01v4_neu] | 'num_warning'=0;;;0; 'num_critical'=1;;;0;
{"extra_message":"","short_message":"OK","data":{"20":{"power_state":"poweredOn","connection_state":"connected","name":"Master01v4_neu","snapshosts":[{"create_time":"2022-10-26T09:52:12.246843Z","description":"","name":"TEST"}],"config.annotation":null}},"vmware_connector_version":"3.2.1","identity":"client-18e233427a2e4e158ec6f64e61ced443","code":0}
'Master01v4_neu' snapshot create time: 2022-10-26T09:52:12.246843Z
```

**Comment by garnier-quentin** [comment]
maybe i can add it in long output with an option

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
