### ISSUE TITLE
new plugin to monitoring AWS Direct Connect

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4026]
It should be nice to have a plugin to monitor AWS Direct Connect: https://docs.aws.amazon.com/directconnect/latest/APIReference/Welcome.html

Direct Connect is similar service that you can find in Azure named Express Route

**Comment by Sims24** [comment]
Hi, 

Could you please tell us what would be the assets (Connection, Optical, VirtualInt ...) and the metrics that would be the most relevant for your usecase? 

More information helping you to get you an idea about it: https://docs.aws.amazon.com/directconnect/latest/UserGuide/monitoring-cloudwatch.html 

Best,

**Comment by joschi99** [comment]
Hi @Sims24, sorry for the delay.

It should be nice to monitor:
### Connection
- Connection: State, Port speed
- Connection metrics: ConnectionErrorCount, Connectionstate, ConnectionBpsEgress, ConnectionBpsIngress, Connection PpsEgress, ConnectionPpsIngress, ConnectionLightLevelRx, ConnectionLightLevelTx
### Virtual Interface
- Virtual Interface: State, VLAN, virtual interface type
- Virtual interface metrics: VirtualInterfaceBpsEgress, VirtualInterfaceBpsIngress, VirtualInterfacePpsEgress, VirtualInterfacePPsIngress, VirtualInterface

On Virtual Interface should be nice to have a discovery mode


Did you need any other informations?

**Comment by joschi99** [comment]
Are there any news on this? Did you need any other information?

**Comment by garnier-quentin** [comment]
The best will be an access to develop it

**Comment by joschi99** [comment]
Hi @garnier-quentin,

finaly I have a access key to access the system. I will send the key and secret by email. 

Reviewing Direct Connect it could be nice to add a list-virtual-interface mode and for Virtual Interfaces also the BGP status.
If you need further information please let me know.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4382
