### ISSUE TITLE
[hardware::ups::apc::snmp::plugin] - Mode battery-status : Warning or critical treshold has no effect

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#403]
Hi, I try to check time remaining on APC UPS equipment.
The plugin work correctly but it's impossible to assign treshhold values (not reported in perfdata)
![centreon-plugins_ups-apc_treshold](https://cloud.githubusercontent.com/assets/8720203/15352661/87af17ea-1ce5-11e6-9f36-95432668fdbf.png)

It's a bug or the syntax I use is false?
thanks.
Centreon-Plugins version: 20160122

**Comment by garnier-quentin** [comment]
It's weird. Could you test it with the last version please ?

**Comment by cmeschin** [comment]
It's OK with version 20160324. thanks.
A little thing: is it really useful to have 13 digits on remaining time? :)

**Comment by garnier-quentin** [comment]
Yes, we need to be accurated :) No i'll do the fix ;)

**Comment by garnier-quentin** [comment]
Could you test ?

**Comment by cmeschin** [comment]
it's good...
OK: Remaining capacity : 100 %, Remaining time : 35.60 minutes | 'load'=100%;80:;;0;100 'load_time'=35.60m;20:;;0;

**Comment by garnier-quentin** [comment]
thanks for tge feedbkac
