### ISSUE TITLE
[database::oracle::plugin] can't locate DBD/Oracle.pm centreon web ok for centreon-engine and root

### ISSUE THREAD

**Issue by acid-zenox** [centreon/centreon-plugins#4033]
Hello,

I have a problem with the oracle plugin.

For example the TNSPING works in root and in centreon-engine but not from the web interface:

here is the error:
CRITICAL: Cannot connect: install_driver(Oracle) failed: Can't locate DBD/Oracle.pm in @INC (@INC contains: /usr/lib/centreon/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 12) line 3.

Perhaps the DBD::Oracle perl module hasn't been fully installed,

or perhaps the capitalisation of 'Oracle' isn't right.

it works well with the centreon-engine user

locate Oracle.pm
/usr/local/src/DBD-Oracle-1.80/blib/lib/DBD/Oracle.pm
/usr/local/src/DBD-Oracle-1.80/lib/DBD/Oracle.pm
/usr/perl5/lib/perl5/x86_64-linux-thread-multi/DBD/Oracle.pm

Thank you in advance for your assistance.

**Comment by Sims24** [comment]
Hi,

Did you follow the steps described in the [documentation](https://docs.centreon.com/pp/integrations/plugin-packs/procedures/applications-databases-oracle/#prerequisites)? 

It looks like an unclean installation of the library. How did you install it?

**Comment by garnier-quentin** [comment]
If you still have the issue, please comment
