### ISSUE TITLE
storage::hp::storeonce::4::restapi::plugin filter

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#4035]
Hi,

Is there a way to filter the type of service? I would like to remove the remoteSupport alert.

Thank you,

/usr/lib/centreon/plugins//centreon_hp_storeonce4_restapi.pl --plugin=storage::hp::storeonce::4::restapi::plugin --mode=appliances

    disk space usage total: xxx
    deduplication ratio: xxx
    service 'dataServices' status: ok
    service 'hardware' status: ok
    service 'license' status: ok
    service 'remoteSupport' status: warning
    service 'userStorage' status: ok

**Comment by Sims24** [comment]
Hi, 

You should rather use threshold for this, there is not filter available/possible. 

You could change default values by adding these options: 

`--warning-service-status='%{status} =~ /warning/i && %{service} !~ /remoteSupport/' --critical-service-status='%{status} =~ /critical/i && %{service} !~ /remoteSupport/'`
