### ISSUE TITLE
Ceph RestAPI Raw Useage Support

### ISSUE THREAD

**Issue by ParadoxGuitarist** [centreon/centreon-plugins#4038]
Since the existing scripts are pulling from /api/health/full the data for raw useage and it's percentages from df already exist in the payload. Outside of overall health, I don't see this data fitting in with the other mode checks, 

The relevant payload I think is most useful is under `df > stats > total_used_raw_ratio` which is pre calculated for total_used_raw_bytes/total_bytes. 

I'm happy to submit a PR for this, I'm just not sure what the mode should be called. `df` ? I'll work on it as such and it can always be modified unless I hear otherwise. 

Thanks!

**Comment by Sims24** [comment]
Hi, 

Thanks for offering such feedback, and even more offering a PR :) Don't worry about the mode name, we will review that together when the PR will be fired ;)

**Comment by ParadoxGuitarist** [comment]
PR opened. 

Sorry if some of it is no good, I haven't really messed with a lot of pearl, but it was working for me.

**Comment by ParadoxGuitarist** [comment]
Just to leave bread crumbs, this ended up getting merged as a new `storage` mode with #4205
