### ISSUE TITLE
New plugin for PacketFence

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#4039]
Hi,

Is it possible to create check for PacketFence

https://www.packetfence.org/documentation/pod/pf/SNMP.html

Thanks,

**Comment by Sims24** [comment]
Hi, 

Not sure about what we should monitor from the link you've provided? 

What would you like to achieve exactly?

**Comment by garnier-quentin** [comment]
I have checked and i don't see something specific to monitor for packetfence (you can monitor radius, drbd, processes with existing checks).

**Comment by romsworld** [comment]
Hello,
I thought there was specific data.
If not, you can close.

Thank you,

**Comment by garnier-quentin** [comment]
Maybe you can check number of registrations on packetfence log files.
