### ISSUE TITLE
Possible de superviser les ressources par VM sur un hyperviseur Proxmox ?

### ISSUE THREAD

**Issue by freddL** [centreon/centreon-plugins#404]
Bonjour,

j'utilise Centréon pour superviser le hardware des mes serveurs physique Dell, qui fonctionne parfaitement !
Ces serveurs Dell ont pour OS  : Proxmox 4 
et je me demmandais si dans un futur proche, il serait possible de superviser les ressources consommé par VM (KVM ou LXC) ?
Merci

**Comment by garnier-quentin** [comment]
Yes it could. But it's not planned yet.

**Comment by freddL** [comment]
Ok, thanks for reponse :-)

**Comment by garnier-quentin** [comment]
I need API examples.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md

**Comment by Sims24** [comment]
@freddL finaly ! We'll probably do it by the end of the year ;)

**Comment by Sims24** [comment]
@freddL @ypilpre and @cgagnaire just pushed it through https://github.com/centreon/centreon-plugins/pull/1269

Enjoy ;)
