### ISSUE TITLE
Centreon 22.04.4 check_centreon_nrpe3 works on cli but (No output returned from plugin) in webui

### ISSUE THREAD

**Issue by SMN-Kaimar** [centreon/centreon-plugins#4044]
Hello,

I am working on a plugin which is checking remote server file content using nrpe.

#Server:
/bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H HOSTNAME -p PORT -c check_log_errors'
ERROR: [Tue Nov  XXXX] [XXXX] XXXX

#Server (centreon-engine user):
/bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H HOSTNAME -p PORT -c check_log_errors'
ERROR: [Tue Nov  XXXX] [XXXX] XXXX

#Client:
/bin/sh -c '/usr/lib64/nagios/plugins/check_log_errors.py -p /XXXX/XXXX -s XXXX XXXX'
ERROR: [Tue Nov  XXXX] [XXXX] XXXX

centreon-nrpe3.cfg:
allow_bash_command_substitution=1
dont_blame_nrpe=1
command[check_log_errors]=python3 /usr/lib64/nagios/plugins/check_log_errors.py -p /XXXX/XXXX -s XXXX XXXX

WebUI check command: check_centreon_nrpe3 -H HOSTNAME -p PORT -c check_users = (No output returned from plugin)
CLI: check_centreon_nrpe3 -H HOSTNAME -p PORT -c check_users = USERS OK - 1 users currently logged in |users=1;5;10;0

All commands seem to work on cli but WebUI is returning: (No output returned from plugin)
And it's the same for all check_centreon_nrpe3 commands not only for this custom one.
Is there some special configuration that is needed for this or what's the issue?

**Comment by SMN-Kaimar** [comment]
Command_1(shell enabled): $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Output: 
(No output returned from plugin)

Command_2(shell enabled): $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_log_errors
Output: (No output returned from plugin)

Command_2/1(shell disabled): $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_log_errors
Output: (Execute command failed)

Manually running following command: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_log_errors
Output: ERROR: [Tue Nov  8 06:35:15 2022] [FATAL].......

Manually using root or centreon-engine user plugin returns the wanted output.

**Comment by Sims24** [comment]
Are you sure that $USER1$ value is /usr/lib64/nagios/plugins and not /usr/lib/nagios/plugins?

**Comment by SMN-Kaimar** [comment]
![image](https://user-images.githubusercontent.com/56275743/200629541-771227c4-f4a9-4db8-a968-682deeeb8c4c.png)

**Comment by Sims24** [comment]
What does `ls -lha /usr/lib64/nagios/plugins/*` command shows?

**Comment by SMN-Kaimar** [comment]
ls -lha /usr/lib64/nagios/plugins/*
-rwxrwxrwx 1 root root    54K Apr 22  2022 /usr/lib64/nagios/plugins/check_centreon_nrpe3
-rwxr-xr-x 1 root nagios  57K Apr 10  2020 /usr/lib64/nagios/plugins/check_dhcp
-rwxr-xr-x 1 root root   107K Apr 10  2020 /usr/lib64/nagios/plugins/check_http
-rwsrwsrwx 1 root root    69K Apr 10  2020 /usr/lib64/nagios/plugins/check_icmp
-rwxr-xr-x 1 root root    41K Apr 10  2020 /usr/lib64/nagios/plugins/negate
-rwxr-xr-x 1 root root    36K Apr 10  2020 /usr/lib64/nagios/plugins/urlize
-rwxr-xr-x 1 root root   2.8K Apr 10  2020 /usr/lib64/nagios/plugins/utils.sh

**Comment by Sims24** [comment]
ok, can you share a screenshot of Configuration > Pollers > Resources menu please?

**Comment by SMN-Kaimar** [comment]
![image](https://user-images.githubusercontent.com/56275743/200771599-72136469-5da7-481e-8e6e-c82adb4bb05a.png)

**Comment by Sims24** [comment]
No output returned from plugins generally means that centreon-engine cannot find or execute the script. Or that the plugin output isn't well formatted and that engine cannot parse it ... 

From what you shared, that seems not to be the case here so ... Maybe you could give a try to the perl flavor in apps::protocols::nrpe::plugin, just checking if you get the same result?

**Comment by SMN-Kaimar** [comment]
shell enabled: Embedded Perl error: syntax error in '/bin/sh': Unrecognized character \x7F: marked by <-- HERE after ^W = 1:
shell disabled: Embedded Perl error: failed to open Perl file '/usr/lib64/nagios/plugins/check_centreon_nrpe3': No such file or directory at /tmp/centreon_connector_perl.ahiIGr line 37.

**Comment by Sims24** [comment]
Hum, 

Ok I got it. You should not use the perl connector with check_centreon_nrpe3. That's probably the issue here. Check that you don't have perl connector set at the command level.

**Comment by SMN-Kaimar** [comment]
#WebUI 1
Status information: (Execute command failed)
Service Status: UNKNOWN
Executed Check Command Line: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Command Type: Check
Command Line: $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: NO
Connectors: None
Status: Enabled
$USER1$: /usr/lib64/nagios/plugins

#WebUI 2
Status information: (No output returned from plugin)
Service Status: UNKNOWN
Executed Check Command Line: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Command Type: Check
Command Line: $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: YES
Connectors: None
Status: Enabled
$USER1$: /usr/lib64/nagios/plugins

#WebUI 3
Status information: option '?' requires an argument
Service Status: UNKNOWN
Executed Check Command Line: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Command Type: Check
Command Line: $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: NO
Connectors: SSH Connector
Status: Enabled
$USER1$: /usr/lib64/nagios/plugins

#WebUI 4
Status information: option '?' requires an argument
Service Status: UNKNOWN
Executed Check Command Line: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Command Type: Check
Command Line: $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: YES
Connectors: SSH Connector
Status: Enabled
$USER1$: /usr/lib64/nagios/plugins

#WebUI 5
Status information: Embedded Perl error: syntax error in '/bin/sh': Unrecognized character \x7F: marked by <-- HERE after ^W = 1:
Service Status: UNKNOWN
Executed Check Command Line: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Command Type: Check
Command Line: $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: YES
Connectors: Perl Connector
Status: Enabled
$USER1$: /usr/lib64/nagios/plugins

#WebUI 6
Status information: Embedded Perl error: failed to open Perl file '/usr/lib64/nagios/plugins/check_centreon_nrpe3': No such file or directory at /tmp/centreon_connector_perl.ahiIGr line 37.
Service Status: UNKNOWN
Executed Check Command Line: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Command Type: Check
Command Line: $USER1$/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: No
Connectors: Perl Connector
Status: Enabled
$USER1$: /usr/lib64/nagios/plugins

#CLI 1
User: root
Command: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

#CLI 2
User: root
Command: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

#CLI 3
User: centreon-engine
Command: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

#CLI 4
User: centreon-engine
Command: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

**Comment by SMN-Kaimar** [comment]
Seems like there is something wrong with check_centreon_nrpe3 output when centreon is calling that plugin directly?

I created the following script/plugin: 
import argparse
import sys
import os

state_ok = 0
state_warning = 1
state_critical = 2
state_unknown = 3
state_dependent = 4


def get_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-i', '--ip', help='IP', required=True, dest='ip')
    parser.add_argument(
        '-p', '--port', help='Port', required=True, dest='port')

    args = parser.parse_args()

    return args


args = get_arguments()

try:
    hostname = args.ip
    port = args.port


except Exception as e:
    print('Exception: {} '.format(e))
    sys.exit(state_unknown)


try:
    if hostname is not None:
        shell_command = '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H ' + hostname + ' -p ' + port + ' -c check_log_errors'
        nagios_output = os.system(shell_command)
        if nagios_output=="OK":
            print(nagios_output)
            sys.exit(state_critical)
        else:
            print(nagios_output)
            sys.exit(state_ok)
except Exception as exc:
    print('Exception: {} '.format(exc))
    sys.exit(state_unknown)


And added the following command to the centreon check commands:
python $USER1$/nrpe_workaround.py -i x.x.x.x -p 5666

![image](https://user-images.githubusercontent.com/56275743/200840384-7f483dc4-1862-4a8b-8b25-8e2e93024af3.png)
![image](https://user-images.githubusercontent.com/56275743/200840438-ad372a79-014e-4993-832e-351ede1bbcb3.png)

**Comment by Sims24** [comment]
There's probably something obvious I'm missing here, but I tested and I don't have any issue with the check_centreon_nrpe3 on my side ..

**Comment by SMN-Kaimar** [comment]
It's strange that I don't have any issue too with the check_centreon_nrpe3 when I'm using it CLI and calling it from the workaround plugin but directly from Centreon WebUI commands it fails with every option I can think of.

**Comment by garnier-quentin** [comment]
Please comment it if you still have the issue

**Comment by SMN-Kaimar** [comment]
> 
Please read all comments not only which you want.
I replayed the following almost month ago:
[SMN-Kaimar](https://github.com/SMN-Kaimar) commented [27 days ago]

#WebUI 1
Status information: (Execute command failed)
Service Status: UNKNOWN
Executed Check Command Line: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Command Type: Check
**Command Line: /check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: NO
Connectors: None**
Status: Enabled
: /usr/lib64/nagios/plugins

#WebUI 2
Status information: (No output returned from plugin)
Service Status: UNKNOWN
Executed Check Command Line: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Command Type: Check
**Command Line: /check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: YES
Connectors: None**
Status: Enabled
: /usr/lib64/nagios/plugins

#WebUI 3
Status information: option '?' requires an argument
Service Status: UNKNOWN
Executed Check Command Line: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Command Type: Check
**Command Line: /check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: NO
Connectors: SSH Connector**
Status: Enabled
: /usr/lib64/nagios/plugins

#WebUI 4
Status information: option '?' requires an argument
Service Status: UNKNOWN
Executed Check Command Line: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Command Type: Check
**Command Line: /check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: YES
Connectors: SSH Connector**
Status: Enabled
: /usr/lib64/nagios/plugins

#WebUI 5
Status information: Embedded Perl error: syntax error in '/bin/sh': Unrecognized character \x7F: marked by <-- HERE after ^W = 1:
Service Status: UNKNOWN
Executed Check Command Line: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Command Type: Check
**Command Line: /check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: YES
Connectors: Perl Connector**
Status: Enabled
: /usr/lib64/nagios/plugins

#WebUI 6
Status information: Embedded Perl error: failed to open Perl file '/usr/lib64/nagios/plugins/check_centreon_nrpe3': No such file or directory at /tmp/centreon_connector_perl.ahiIGr line 37.
Service Status: UNKNOWN
Executed Check Command Line: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Command Type: Check
**Command Line: /check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: No
Connectors: Perl Connector**
Status: Enabled
: /usr/lib64/nagios/plugins

#CLI 1
**User: root**
Command: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

#CLI 2
**User: root**
Command: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

#CLI 3
**User: centreon-engine**
Command: /bin/sh -c '/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users'
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

#CLI 4
**User: centreon-engine**
Command: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Output: USERS OK - 1 users currently logged in |users=1;5;10;0

**Comment by SMN-Kaimar** [comment]
> I have seen connectors in your configuration. You need to disable connectors and disable the shell.

How you can ask me to disable connectors and shell if I said replayed the following: 
#WebUI 1
Status information: (Execute command failed)
Service Status: UNKNOWN
Executed Check Command Line: /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Command Type: Check
**Command Line: /check_centreon_nrpe3 -H x.x.x.x -p 5666 -c check_users
Enable shell: NO
Connectors: None**
Status: Enabled
: /usr/lib64/nagios/plugins

Is it somehow unclear that with that test there was no shell or connector enabled?
