### ISSUE TITLE
Serpervision serveur Prolian

### ISSUE THREAD

**Issue by freddL** [centreon/centreon-plugins#405]
Bonjour,
dans mon parc j'ai quelques sevreur Proliant DL380p Gen8 dont je voudrais superviser avec Centréon.
j'utilise donc le plugin **hardware::server::hp::proliant::snmp::plugin

./centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=IP
réponse : 
OK: All 0 components are ok [].

Du coup impossible de superviser le hardware... Si vous voulez plus d'infos n'hésitez pas à me demander.
Merci

**Comment by garnier-quentin** [comment]
Could you give me a full snmpwalk ? 

snmpwalk -Cc -On -v 2c -c public IP .1

thanks

**Comment by freddL** [comment]
ok, but it's very long....

**Comment by garnier-quentin** [comment]
I think the file had been cut. Could you send me by email ?

**Comment by freddL** [comment]
Yes it's cut because again repeat end line...

**Comment by garnier-quentin** [comment]
Could you do it from here : .1.3.6.1.4.1.232 ?

**Comment by freddL** [comment]
snmpwalk -Cc -On -v2c -c public IP .1.3.6.1.4.1.232
.1.3.6.1.4.1.232 = No Such Object available on this agent at this OID

**Comment by garnier-quentin** [comment]
following oids should be filled. I'll need to know what it is after following oid (the infinite loop): .1.3.6.1.2.1.4.24

**Comment by freddL** [comment]
lorsque j'éxécute simple snmpwalk, j'ai cette erreur à la fin 
Error: OID not increasing: IP-FORWARD-MIB::ipCidrRouteDest.192.168.0.0.255.255.255.0.0.0.0.0.0
 >= IP-FORWARD-MIB::ipCidrRouteDest.192.168.0.0.255.255.255.0.0.0.0.0.0

**Comment by garnier-quentin** [comment]
You need to test with option -Cc

**Comment by freddL** [comment]
It's good ! 
I del a route
the full answare of snmpwalk with -Cc : https://framabin.org/?ec6586d2329e0c45#0lBEqMwoMMd2cgXcJfxavXWAqlKWzZtDs5fzhEG1gzA=

**Comment by Sims24** [comment]
Hi @freddL, 

is HP Insight Management Agents installed on this server ? 

Thanks

**Comment by freddL** [comment]
Hi Sims24 ! :-)
I install this : hponcfg hp-snmp-agents hp-health hpsmh hpssacli

**Comment by freddL** [comment]
ça ne fonctionne toujours pas... je désespère un peu ...

**Comment by Sims24** [comment]
Possible de prendre la main à distance ? On va essayer de regarder
aujourd'hui, en fin d'après-midi ça irait ?

**Comment by freddL** [comment]
pas que je ne veux pas mais il sera pas possible de prendre la main à distance sur le serveur (politique de sécurité)... sinon, je suis dispo cet après midi.. merci

**Comment by Sims24** [comment]
Np we'll go forward by mail. Send a email at sbomm@centreon.com this way I'll have your address. 

Then I'll post conclusions here for other centreon-plugins users, 

Thanks

**Comment by garnier-quentin** [comment]
I think it's not a problem of the plugin. More about the configuration of hp agent. I close the ticket. Simon will give you an answer and write it in the ticket.
