### ISSUE TITLE
Support command line parameters arguments (with double-dash)

### ISSUE THREAD

**Issue by proxyconcept** [centreon/centreon-plugins#4055]
### Description

The script centreon_plugins.pl only accepts options parameters, all values must be passed with a "--option" parameter.
This is good (simple and strict) but sometimes it could be useful to pass arguments: a simple list of values, that can be unlimited.

The main problem with arguments is: how to know that the next parameter is the name of an option or the value of an argument ?
A standard solution is the use of the `--` parameter which means that all following parameters should no longer be parsed as options.

So I suggest that the centreon_plugins script support the double-dash option, store the arguments list and offers the possibility for plugins to use them.

### Example

The NRPE plugin can be a good example, here is a typical check for memory:
```
centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --mode=query --custommode=nrpe ... \
--hostname=$HOSTADDRESS$ --command=check_memory $_SERVICEEXTRAOPTIONS$ \
--arg="filter=$_SERVICEFILTER$" --arg="detail-syntax=$_SERVICEDETAILSYNTAX$" --arg="warning=$_SERVICEWARNING$" --arg="critical=$_SERVICECRITICAL$" 
```
For each NRPE command arguments, we must use the "--arg=" option. It's not very convenient to do this encapsulation and it also complicates to create generic centreon command with a service macro like `$_SERVICENRPE_ARGS$`

With the `--` support for arguments, we can imagine the possibility of using this plugin like this:
```
centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --mode=query --custommode=nrpe ... \
--hostname=$HOSTADDRESS$ --command=check_memory $_SERVICEEXTRAOPTIONS$ -- \
"filter=$_SERVICEFILTER$" "detail-syntax=$_SERVICEDETAILSYNTAX$" "warning=$_SERVICEWARNING$" "critical=$_SERVICECRITICAL$" 
```
Or even a more generic command like this:
```
centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --mode=query --custommode=nrpe ... \
--hostname=$HOSTADDRESS$ --command=$_SERVICENRPE_COMMAND$ $_SERVICEEXTRAOPTIONS$ -- \
"warning=$_SERVICEWARNING$" "critical=$_SERVICECRITICAL$" $_SERVICENRPE_ARGS$
```

**Comment by proxyconcept** [comment]
### Some references about the double-dash `--` standard

- https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02
  Guideline 10: _The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character._

- https://linux.die.net/man/3/getopt_long
  _The special argument "--" forces an end of option-scanning regardless of the scanning mode._

**Comment by garnier-quentin** [comment]
I see the purpose. But i don't know where to store it. Right now:
```'arg:s@'```

Maybe we could manage it like that otherwise ?
```
--arg "filter=$_SERVICEFILTER$" "detail-syntax=$_SERVICEDETAILSYNTAX$" "warning=$_SERVICEWARNING$" "critical=$_SERVICECRITICAL$"
```

And if we have the special -- i store it in ```arg``` ?

**Comment by proxyconcept** [comment]
For the full story, my primary need was to have something similar to the `/usr/lib64/nagios/plugins/check_nrpe` script (from the nagios-plugins-nrpe rpm package):
```
Usage: check_nrpe -H <host> [-2] [-3] [-4] [-6] [-n] [-u] [-V] [-l] [-d <dhopt>]
       [-P <size>] [-S <ssl version>]  [-L <cipherlist>] [-C <clientcert>]
       [-K <key>] [-A <ca-certificate>] [-s <logopts>] [-b <bindaddr>]
       [-f <cfg-file>] [-p <port>] [-t <interval>:<state>] [-g <log-file>]
       [-c <command>] [-E] [-D] [-a <arglist...>]
```
With this script, we can wrote command like `check_nrpe -c check_memory -a "filter=$_SERVICEFILTER$" "detail-syntax=$_SERVICEDETAILSYNTAX$" "warning=$_SERVICEWARNING$" "critical=$_SERVICECRITICAL$"`
Which is easier thant writing multiples `--arg` options.

So my first idea was to improve the GetOpt system with a new multivalue syntax, for example `args:s*` with the following code added to `centreon/plugins/alternative/Getopt.pm` :
```perl
sub get_assigned_values {
   my (%options) = @_;
   my @values = ();
   if (defined($options{val}) && $options{val} ne '') {
       push(@values, $options{val});
   }
   my $n_args = $options{num_args} - $options{pos} - 1;
   push(@values, splice(@ARGV, $options{pos} + 1, $n_args)) if ($n_args > 0);
   return ($options{pos} + 1, \@values);
}

sub GetOptions {
...
            } elsif ($type_opt =~ /:s\*$/) {
                ${$opts{$option . $type_opt}} = [] if (!defined(${$opts{$option . $type_opt}}));
                ($num_args, my $assigned) = get_assigned_values(num_args => $num_args, pos => $i, val => $value);
                push @{${$opts{$option_selected}}}, @{$assigned};
            }
...
}
```

And it works well... I can run for example:
```
centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode=query --custommode=nrpe ... \
--command=check_memory --args "filter=aaa" "detail-syntax=bbb"
```
And the plugin have `$self->{option_results}` containing:
```
          'command' => 'check_memory',
          'args' => [
                      'filter=aaa',
                      'detail-syntax=bbb'
                    ],
          ...
```

I looks clean, but have some consistency problems: the options parsing is multi-pass and first passes (before the mode's options) can found wrongly existing options, for example:
```
centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --mode=query --custommode=nrpe ... \
--command=check_memory --args "filter=aaa" "detail-syntax=bbb" --help
```
Or even worse if we have:
```
centreon_plugins.pl --plugin apps::protocols::nrpe::plugin --custommode=nrpe ... \
--command=check_memory --args "filter=aaa" "detail-syntax=bbb"  --mode=query --anything
```
The `--mode` option is extracted first, and finally the `--args` option contains `[ 'filter=aaa', 'detail-syntax=bbb', '--anything']` but this is inconsistent!

So I abandoned this solution, considering that arguments should be read until the end of the parameters at the very first pass, and that the `--` option is the safer and standard way to indicate this.
