### ISSUE TITLE
checkpoint - hardware - psu -- missing 'OK' state

### ISSUE THREAD

**Issue by meni2029** [centreon/centreon-plugins#4057]
### Problem description:
Checkpoint hardware psu check returns `UNKNOWN: Power supply '1.0' status is 'OK'` on some checkpoint hosts, while we would expect `OK: All 1 components are ok [1/1 psus].`

The oid `.1.3.6.1.4.1.2620.1.6.7.9.1.1.2` returns `STRING: "OK"`

The model of the firewall is unfortunatelly not known.

### Relevant file:
network/checkpoint/snmp/mode/hardware.pm

### Change suggested:
        psu => [
            ['up', 'OK'],
            ['down', 'CRITICAL'],
            ['dummy', 'OK'],
            ['^present', 'OK'],
            ['OK', 'OK'] <- this line should be added
        ],

Thanks

**Comment by garnier-quentin** [comment]
v
