### ISSUE TITLE
Check HTTP apps::protocols::http::plugin  - Error 411 length

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon-plugins#4059]
HI,

I would like to check an HTTP adress, but i'have this error : 

/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=portal.intra.cardifiard.lan --proto='https' --urlpath='/Portal' --method='POST' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"

CRITICAL: 411 Length Required | 'time'=0.039s;;;0; 'size'=344B;;;0;

Could you help to resolve it ?

**Comment by garnier-quentin** [comment]
Could you test with curl command ? Try following command:
```
/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=portal.intra.cardifiard.lan --proto='https' --urlpath='/Portal' --method='POST' --http-backend=curl --insecure
```

**Comment by Xinerys** [comment]
I have this error : 

/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=portal.intra.cardifiard.lan --proto='https' --urlpath='/Portal' --method='POST' --http-backend=curl --insecure

CRITICAL: 400 Bad Request | 'time'=0.103s;;;0; 'size'=374B;;;0;

**Comment by garnier-quentin** [comment]
Could you test with curl command directly ? To see what it's missing

**Comment by Xinerys** [comment]
Je suis bloqué par le proxy : "Hote non résolvable" cependant lorsque j'essaie sur la machine en interafce graphique, j'i arrive

**Comment by garnier-quentin** [comment]
Add your proxy with environment variable if needed

**Comment by Xinerys** [comment]
Le proxy est deja paramétré mais je pense que notre proxy se base sur un fichier PAC.

**Comment by garnier-quentin** [comment]
I can't help you more if you can't make it with curl command line.

**Comment by Xinerys** [comment]
Thanks !

**Comment by garnier-quentin** [comment]
Please comment it if you have a valid curl command.
