### ISSUE TITLE
apps::protocols::ftp::plugin --mode=date --directory

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#406]
Hi,

When we use the options --directory and --file combined, the plugin search the files at the root of the directory and not in the directoryy mentionned.

For example: A.txt is at the root directory, B.txt is in /fileB/ 

./centreon_plugins.pl --plugin=apps::protocols::ftp::plugin --mode=date --hostname=x --username='x' --password='*******' --warning='30' --critical='60' --directory='/fileB/' --file 'B.txt'
UNKNOWN: Command 'mdtm' issue for file 'B.txt': Can't find file |

./centreon_plugins.pl --plugin=apps::protocols::ftp::plugin --mode=date --hostname=* --username='supervision' --password='***' --warning='30' --critical='60' --directory='/fileB/' --file 'A.txt'
OK: All file times are ok.  | 'A.txt'=360095s;0:30;0:60;

**Comment by garnier-quentin** [comment]
Options are not working togother. --file looks for files in '.' directory. Not from --directory options
