### ISSUE TITLE
[hardware::pdu::cyberpower::snmp::plugin] --mode=outlets

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#4061]
Hello,

I use the last unstable centreon-plugin-Hardware-Pdu-Cyberpower-Snmp-20221115-095034.el8.noarch.rpm and i have some errors :
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.
Use of uninitialized value in division (/) at /usr/lib/centreon/plugins/centreon_pdu_cyberpower_snmp.pl line 9972.

Same problems with the last stable RPM.

Moreover, there is no way to have a CRITICAL Status with OutletState using --critical-status="%{state} =~ /off" option.

Here are the SNMP values :
CPS-MIB::ePDUOutletStatusOutletState.1 = INTEGER: outletStatusOff(2)
CPS-MIB::ePDUOutletStatusOutletState.2 = INTEGER: outletStatusOn(1)
CPS-MIB::ePDUOutletStatusOutletState.3 = INTEGER: outletStatusOn(1)
CPS-MIB::ePDUOutletStatusOutletState.4 = INTEGER: outletStatusOff(2)
CPS-MIB::ePDUOutletStatusOutletState.5 = INTEGER: outletStatusOff(2)
CPS-MIB::ePDUOutletStatusOutletState.6 = INTEGER: outletStatusOff(2)
CPS-MIB::ePDUOutletStatusOutletState.7 = INTEGER: outletStatusOff(2)
CPS-MIB::ePDUOutletStatusOutletState.8 = INTEGER: outletStatusOn(1)

Thanks.

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk of following branch ? .1.3.6.1.4.1.3808.1.1.6.6

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4087
