### ISSUE TITLE
[os::windows::wsman::plugin] --mode=services/list-services: not all services are visible using a non admin account

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4062]
Monitoring Windows Services through wsman/winrm following your documentation for Domain configuration (https://docs.centreon.com/pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial/#winrm-configuration) using a "non administrator" account is not working for services.
The section https://docs.centreon.com/pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial/#configure-services-permissions which sets the permissions to list all services is not working for all services. There are many services which have special permissions and the special permission will not overrided by the changed permissions on scmanager.
The result is that all services having special permission are not listet on the discovery and the cannot be monitored because no data will be returned (permission problem).
If you add the windows monitoring user to the local admin group everything is working fine.

Is there any working solution for them using a non admin account?

**Comment by garnier-quentin** [comment]
We use wmi to check services:
```
        uri => 'http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/*',
        wql_filter => 'Select Name, State From Win32_Service Where ' . $self->{wql_filter},
```

Maybe all services are not present in table ```Win32_Service``` ?

**Comment by garnier-quentin** [comment]
There is an interesting post here:
https://social.technet.microsoft.com/Forums/exchange/en-US/0544c041-572c-4fd2-aad4-29aea7ae8609/remote-query-class-win32service-does-not-show-all-services-when-executed-by-normal-domain-user?forum=winserverpowershell

You need to set the QueryStatus right for the service.

**Comment by joschi99** [comment]
Hi @garnier-quentin,
I can confirm that the only problem are related to the rights and its not a plugin problem/error. But the documentation that Centreon provide is not working or has this issue and our actual research results are that we have actually no workaround with unpriviledged user. The only workaround that we have actually is to add the user the local administator group, which could be a security issue.
Any idea?

**Comment by garnier-quentin** [comment]
You can add rights to services missing.

**Comment by joschi99** [comment]
thats right, but we need a solution that works using GPO for automatic deploy. And if new software will be installed in a second moment which can create new services to monitor how we can handle this?
We need to find a solution that can be distribuited by GPO for automatic and massive configuration and covers also new installed services. No idea how to do this or if this is possible.

**Comment by garnier-quentin** [comment]
I don't have a Windows platform with a domain configured. But i think you can create a script to add the right to all services no ?

**Comment by Luth1ng** [comment]
All windows services permissions are managed by the Service Control Manager which is a special system process.
You can edit the SCM configuration by using the sc.exe program.

If you follow the [Centreon wsman config guide](https://docs.centreon.com/pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial/#grant-permissions-for-services), you will use the sc.exe program to give your limited user an access to the Service Control Manager service with the rights "CCLCRPRC".
(for details see https://learn.microsoft.com/en-us/windows/win32/secauthz/ace-strings)

Then, your user is now able to use the SCM to list services.

**BUT**, as it not described in the documentation, this will only give you the ability to list the services for which you have the permission to list. So, when we execute the "list-services" mode of the wsman plugin, you will see some of the services running on the host, but not all.

An example : 

Here is the service's security descriptor for the "Dhcp" service which is listed with the plugin : 
```
C:\Windows\system32>sc sdshow Dhcp
D:(A;;CCLCSWLOCRRC;;;AU)(A;;CCLCSWRPWPDTLOCRRC;;;NO)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWRPLOCRRC;;;S-1-2-1)(A;;CCLCSWRPWPDTLOCRRC;;;SY)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)
```
The SDDL can be translated to this table : 
_NB: you can use [this tool](https://github.com/canix1/SDDL-Converter) to user friendly view SDDL strings_
<HTML>
<BODY>
<TABLE><TR><TD>BUILTIN\Administrators</TD><TD>BUILTIN\Administrators</TD><TD>Allow</TD><TD>This Object Only</TD><TD>Full Control</TD></TR><TR><TD>BUILTIN\Network Configuration Operators</TD><TD>BUILTIN\Network Configuration Operators</TD><TD>Allow</TD><TD>This Object Only</TD><TD>CreateChild, Self, WriteProperty, DeleteTree, ExtendedRight, GenericRead</TD></TR><TR><TD>CONSOLE LOGON</TD><TD>CONSOLE LOGON</TD><TD>Allow</TD><TD>This Object Only</TD><TD>CreateChild, Self, ExtendedRight, GenericRead</TD></TR><TR><TD>NT AUTHORITY\Authenticated Users</TD><TD>NT AUTHORITY\Authenticated Users</TD><TD>Allow</TD><TD>This Object Only</TD><TD>CreateChild, Self, ListObject, ExtendedRight, GenericExecute</TD></TR><TR><TD>NT AUTHORITY\SYSTEM</TD><TD>NT AUTHORITY\SYSTEM</TD><TD>Allow</TD><TD>This Object Only</TD><TD>CreateChild, Self, WriteProperty, DeleteTree, ExtendedRight, GenericRead</TD></TR></TABLE>

</BODY>
</HTML>

As you can see, **Authenticated Users** are able to list the objects of this service (**ListObject**).

Now, if we look at a service which is not listed by the plugin, like "Netman" service : 

```
C:\Windows\system32>sc sdshow Netman
D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)
```
<HTML>
<BODY>
<TABLE><TR><TD>NT AUTHORITY\INTERACTIVE</TD><TD>NT AUTHORITY\INTERACTIVE</TD><TD>Allow</TD><TD>This Object Only</TD><TD>CreateChild, Self, ListObject, ExtendedRight, GenericExecute</TD></TR><TR><TD>NT AUTHORITY\SERVICE</TD><TD>NT AUTHORITY\SERVICE</TD><TD>Allow</TD><TD>This Object Only</TD><TD>CreateChild, Self, ListObject, ExtendedRight, GenericExecute</TD></TR><TR><TD>NT AUTHORITY\SYSTEM</TD><TD>NT AUTHORITY\SYSTEM</TD><TD>Allow</TD><TD>This Object Only</TD><TD>CreateChild, Self, WriteProperty, DeleteTree, ExtendedRight, GenericRead</TD></TR><TR><TD>BUILTIN\Administrators</TD><TD>BUILTIN\Administrators</TD><TD>Allow</TD><TD>This Object Only</TD><TD>Full Control</TD></TR></TABLE>

</BODY>
</HTML>

You will see that your limited user won't be able to list this object, as he has no right to do so.

### Solution : 

So let's add the ACE you used to grant your limited user access to SCM service to the Netman SDDL : 
_NB: By the way, you will only need the permissions "CCLCLO" to list the service status and the starting mode._
```
C:\Windows\system32>sc sdset Netman "D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)(A;;CCLCLO;;;@USERSID@)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)"
```
That's it, now you can use the wsman plugin to get details about the service Netman

You'll have to repeat the process for each service you need to monitor.

NB: You can script this using alternative programs like the PowershellAccessControl Module. (c.f. https://www.scriptinghouse.com/2017/04/set-windows-service-permission-to-non-administrator-accounts.html & https://woshub.com/set-permissions-on-windows-service/)

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old, can you tell us if the answer given by @Luth1ng help you to solve your problem?

**Comment by joschi99** [comment]
The solution from @Luth1ng will solve the problem only for a specific service. But if you are monitoring a Windows system through WinRM we need a solution where every service will be returned, otherwise how we can do a discovery on them if we are not sure that the discovery will return every installed service?
So we need a solution if possible that will set the correct permissions to all services automatically and not a manual solution for only one known service.

I hope you will understand the problem.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I understand the problem and the need behind it. But because it's not really a plugin issue itself I'll ask you to transfer this demand on our vote system [here](https://thewatch.centreon.com/ideas) to help us prioritize this enhancement request (you can link this github issue in your idea proposition).
Thank you for your understanding.
