### ISSUE TITLE
[apps::vmware::connector::plugin] net-host : critical alarm even if the port is admin down

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#4069]
Hi,

Centreon 21.10.13
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20221017-094659.el7.centos.noarch
Vcenter 7.0U3
Esxi 7.0U3

I closed the unused ports on the esxi host:

`esxcli network nic list`
Name    PCI Device    Driver  Admin Status  Link Status  Speed  Duplex
vmnic0  0000:04:00.0  ntg3    Down          Down             0  Half
vmnic1  0000:04:00.1  ntg3    Down          Down             0  Half
vmnic2  0000:51:00.0  i40en   Up            Up           10000  Full
vmnic3  0000:51:00.1  i40en   Up            Up           10000  Full 
vmnic4  0000:51:00.2  i40en   Up            Up           10000  Full 
vmnic5  0000:51:00.3  i40en   Up            Up           10000  Full 

I still have the critical alarm on centreon.
I can filter but I have different esxi models with different vmnic order.
Is it possible to only have the alarm if the port is "admin status : up" ?

Command : 

`/usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=net-host --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --esx-hostname='.*' --filter --nic-name='^(?!(vusb0)$)' --unknown-status='' --warning-status='' --critical-status='' --unknown-link-status='' --warning-link-status='' --critical-link-status='%{link_status} !~ /up/' --warning-link-traffic-in='' --critical-link-traffic-in='' --warning-link-traffic-out='' --critical-link-traffic-out='' --warning-link-dropped-in='' --critical-link-dropped-in='' --warning-link-dropped-out='' --critical-link-dropped-out='' --warning-host-traffic-in='' --critical-host-traffic-in='' --warning-host-traffic-out='' --critical-host-traffic-out='' --verbose`

Best regards.

**Comment by garnier-quentin** [comment]
I'm not sure with have the admin status of the interface.

**Comment by garnier-quentin** [comment]
It seems we cannot have that information with the API

**Comment by garnier-quentin** [comment]
If you find that information in sdk, please comment it
