### ISSUE TITLE
apps::protocols::http::plugin --mode=expected-content --method='POST'

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#407]
Hi,

If we want to use the --method=POST, we have to use --get-param instead of --post-param. The command given in the [documentation page](https://documentation-fr.centreon.com/docs/centreon-plugins/fr/latest/user/guide.html#protocole-http) doesn't work, we have to replace  --post-param by --get-param:

centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=demo.centreon.com  **--method='POST'** **--post-param**='useralias=admin' **--post-param**='password=centreon'  --cookies-file='/tmp/lwp_cookies.dat' --urlpath='/centreon/index.php' --expected-string='logout'
CRITICAL: 'logout' is not present in content.

centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=demo.centreon.com  **--method='POST'** **--get-param**='useralias=admin' **--get-param**='password=centreon'  --cookies-file='/tmp/lwp_cookies.dat' --urlpath='/centreon/index.php' --expected-string='logout'
OK: 'logout' is present in content.

Is it the normal behaviour ?

**Comment by garnier-quentin** [comment]
The plugin is working. The problem is that centreon (since 2.7.x) uses a hidden token to be used in POST. If you don't use that token, you can't connect (xss protection). The plugin cannot get to a page (store the token) and connect after.
