### ISSUE TITLE
--plugin=apps::protocols::x509::plugin , no Check command in centreon

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon-plugins#4071]
Hi, 
I would like to check certificate SSL. But when i want to create a "HOST" i don't see the "Check command" or the "template" App-Protocol-X509-custom.

An Idea ?

**Comment by garnier-quentin** [comment]
It's a service you can attached to a host. If you want a host template with a linked service, you can create your own command/service/host.

**Comment by Xinerys** [comment]
je ne trouve pas de service associés dans centreon.

**Comment by Xinerys** [comment]
In Centreon, i see the x509 plugin is not "install" (the box is not checked). But i can use it in command `line.
