### ISSUE TITLE
--plugin=network::h3c::snmp::plugin Temperature sensor status is 'notSupported'

### ISSUE THREAD

**Issue by cmiscloni** [centreon/centreon-plugins#4072]
Hello, I have a problem with sensor module on switch h3c 5520 model
See below the output

Try with the last plugin.pm of h3c

CRITICAL: Temperature sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' is 65535 degree centigrade - Temperature sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' is 65535 degree centigrade - Temperature sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' is **65535** degree centigrade - Temperature sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' is 65535 degree centigrade WARNING: Sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' status is '**notSupported**' - Sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' status is 'notSupported' - Sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' status is '**notSupported**' - Sensor 'HPE > HPE 5520 24G PoE+ 4SFP+ HI Swch R8M28A Software Version 7.1.070 > CONTAINER LEVEL1 > SENSOR' status is '**notSupported**' | 'temp_220'=31C;;~:63;; 'temp_221'=23C;;~:110;; 'temp_222'=65535C;;~:84;; 'temp_240'=31C;;~:63;; 'temp_241'=23C;;~:110;; 'temp_242'=65535C;;~:84;; 'temp_260'=30C;;~:63;; 'temp_261'=20C;;~:110;; 'temp_262'=65535C;;~:84;; 'temp_280'=30C;;~:63;; 'temp_281'=20C;;~:110;; 'temp_282'=65535C;;~:84;;

**Comment by garnier-quentin** [comment]
Thanks for your issue. I think we could skip sensor with 65535 degree. Otherwise it's quite hot in your datacenter :)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4074

You can skip notSupported: ```--threshold-overload='sensor,OK,notSupported'```
