### ISSUE TITLE
centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp

### ISSUE THREAD

**Issue by Bouyaka888** [centreon/centreon-plugins#4078]
Hello guys,

Sorry if this is already mentionned before, but I have an issue with "centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp".
About the VPN part.

Rigth now, it seems the plugin is counting only : 
- Active tunnels (SSL VPN and/or SSL portal only)
- Sessions (SSL VPN and/or SSL portal only)
- Users (SSL VPN and/orSSL portal only)

But, this same plugin can give you the state of each IPSEC tunnels (and not the counting for all of them).
About Forticlient tunnels (IPSEC method), I see nothing.

So my question is simple, how can I have these data : 
- Count of IPSEC tunnels (site to site) for each VDOM
- Count of IPSEC tunnels (site to client) for each VDOM

If it is not possible to have it rigth now with this plugin, is it possible to add it as new features ?

**Comment by garnier-quentin** [comment]
IPsec tunnel is that table i think: fgVpnTunEntry. So i can count number of entries. 
And ssl tunnels are: fgVpnSslTunnelTable

But it dont have the information for "site2site" and "site2client" information.

**Comment by Bouyaka888** [comment]
Hello,

Ok, indeed this is not easy to identify which one is what ..

IPSEC Tunnels could be : 
- site to site
- site to client

SSL Tunnels could be : 
- site to site
- site to client
- and I'm suspecting this is also SSL Portal connection/session ... 

Even if you can't do the distinction of all of this, yes, could count it as "IPSEC tunnels" and "SSL tunnels (even if there SSL portal connexion in it)".

Thx,

**Comment by Bouyaka888** [comment]
Hi,

Here is a screen of a SSL Portal user :
![image](https://user-images.githubusercontent.com/78611263/209927317-8603d581-d7c4-443c-b457-e1d614bc479c.png)

And here of SSL tunnels connection : 
![image](https://user-images.githubusercontent.com/78611263/209927533-b6d211f5-80e0-4c94-843c-552b1c305896.png)

So it should be possible to identify SSL Portal versus SSL tunnels connections.
