### ISSUE TITLE
[apps::protocols::x509::plugin] --custommode=tcp: UNKNOWN: Unsafe code evaluation: Bareword "TLSv1" not allowed

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4080]
If you monitor X509 certificates using custommode tcp the with the following options:
```
--ssl-opt='SSL_verify_mode => SSL_VERIFY_PEER' 
--ssl-opt='SSL_version => TLSv1'
```
the following error will appear:
`UNKNOWN: Unsafe code evaluation: Bareword "TLSv1" not allowed while "strict subs" in use`
Removing `--ssl-opt='SSL_version => TLSv1'` works correctly.

**Comment by garnier-quentin** [comment]
Please use following syntax: --ssl-opt="SSL_version => 'TLSv1'"

**Comment by joschi99** [comment]
Thanks
