### ISSUE TITLE
latest 3cx update 6 18.0 (Build 861) breaks centreon-plugins/apps/voip/3cx/restapi 

### ISSUE THREAD

**Issue by c280driver** [centreon/centreon-plugins#4083]
centreon_3cx_restapi.pl returns: 404 Not Found

**Comment by garnier-quentin** [comment]
Could you provide the output with --debug option ? And could you find which api endpoint changed ?

**Comment by c280driver** [comment]
changed endpoint is /api/UpdateChecker/GetFromParams

**Comment by c280driver** [comment]
seams its changed to /xapi/v1/GetUpdatesStats()

**Comment by garnier-quentin** [comment]
Do you have a documentation ?

**Comment by c280driver** [comment]
no sorry.

**Comment by c280driver** [comment]
also with final version 3cx 18 update 6 the plugin is broken and not usable. 

/api/UpdateChecker/GetFromParams changed to  /xapi/v1/GetUpdatesStats(), also authentication for this endpoint changed somehow.

**Comment by UrBnW** [comment]
I'll have a look shortly @garnier-quentin ;)

**Comment by UrBnW** [comment]
"Shortly" took 8 months, but here it is 👍

**Comment by omercier** [comment]
Fixed with #5093
