### ISSUE TITLE
Motorola Wi-Fi Monitoring (AP-5131)

### ISSUE THREAD

**Issue by Didier97180** [centreon/centreon-plugins#4084]
Hello,

We would like to supervise a Motorola Wifi hotspot (AP-5131). In the old supervisor we monitored with the command "check_centreon_snmp_traffic". I would like to know if it is possible to transfer this command to the new centreon and if not how.

Thank you

**Comment by garnier-quentin** [comment]
You can use the standard snmp interfaces mode: ```perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces```

**Comment by Didier97180** [comment]
Hello

Sorry for the delay, I actually tried with the linux plugin given by Centreon. It works.
I will try with the plugin given by the community because I would like to put the Unknow option.
Because in Nagios when the terminal is in Unknow in the new centreon it works. Yet I oversee the correct interface

**Comment by garnier-quentin** [comment]
I don't really understand the ```unknown option```. But it seems working. Please comment it if you still have the issue.
