### ISSUE TITLE
[network::aruba::aoscx::snmp::plugin] - different UNKNOWNS on Aruba 6100

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4086]
We have different problems monitoring Aruba 6100 devices with firmware 10.06 or later:

- CPU: the OID used maybe is wrong. we have found another OID that could work: 
.1.3.6.1.2.1.25.3.3.1.2.196608
- Memory: the OID used maybe are wrong, we have found another OID's that could work:
OID Memory Buffers: 1.3.6.1.2.1.25.2.3.1.5.6
OID Physical Memory: 1.3.6.1.2.1.25.2.3.1.5.1
OID Virtual memory: 1.3.6.1.2.1.25.2.3.1.5.3
OID Cached memory: 1.3.6.1.2.1.25.2.3.1.5.7
OID Shared memory: 1.3.6.1.2.1.25.2.3.1.5.8
OID Swap space: 1.3.6.1.2.1.25.2.3.1.5.10
- Virtual Chassis: UNKNOWN: SNMP Table Request: Cant get a single value.
- Virtual Switching Extension: UNKNOWN: SNMP Table Request: Cant get a single value.

Attached you will find the SNMP MIB files
[ArubaOS-CX_10.10_MIBs_19th_May2022.zip](https://github.com/centreon/centreon-plugins/files/10153366/ArubaOS-CX_10.10_MIBs_19th_May2022.zip)

If you need I can send you a snmp walk, but not here on Github

**Comment by garnier-quentin** [comment]
You can send me the full snmpwalk by email

**Comment by garnier-quentin** [comment]
Your aruba have a 10.09.1020 firmware. The memory OIDs have been added since firmware 10.10. So if you update your aruba firmware, the memory mode will work
