### ISSUE TITLE
new plugin request: Veeam backup monitoring using Veeam Backup Enterprise Portal

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4089]
It should be nice to monitor Veeam Backup through the Veeam Backup Enterprise Portal, which offers different advantages;

- Rest API: https://helpcenter.veeam.com/docs/backup/em_rest/em_web_api_reference.html?ver=110
Is more powerfull and has more performance as the actual Powershell scripts, which has performance problems
- We can monitor centrally more then 1 Backup Server

It should possible to monitor and discover:

- Veeam Backup Servers
- Veeam Jobs
- Veeam Repositories
- Veeam Nas backup
- Veeam CDP
- Veeam Tasks

We can provide access to Rest API.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4456
