### ISSUE TITLE
[hardware::pdu::apc::snmp::plugin] - Mode load : Add check power

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#409]
Hi,

Is it possible to add, in this mode or another one, the check of power consumption.
I use this OID: .1.3.6.1.4.1.318.1.1.26.6.3.1.7.1

The value returned is in decaW..., it must be multiplicate by 10 to have in Watts.
![pdu_apc_load_puissance](https://cloud.githubusercontent.com/assets/8720203/15470019/26a187be-20ee-11e6-84e9-0ab3a0f9bafd.png)

Thanks,

**Comment by garnier-quentin** [comment]
Need some refactoring. it's not the same table for your oid. It's in branch: rPDU2. I use branch rPDU. Need to test the other branch.

**Comment by sebastien-prudhomme** [comment]
+1

We can also do that with the rPDU branch with rPDUIdentDevicePowerWatts (.1.3.6.1.4.1.318.1.1.12.1.16.0).

For now i can still use the generic SNMP plugin but i would prefer to have it integrated into the APC PDU plugin.

Example with the generic plugin:

```
$USER1$/centreon_plugins.pl --plugin snmp_standard::plugin --mode numeric-value --hostname $HOSTADDRESS$ --oid 1.3.6.1.4.1.318.1.1.12.1.16.0 --format "Power is %sW" --perfdata-name power --perfdata-unit W --perfdata-min 0
```

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk ?
snmpwalk -ObentU -c public -v 2c IP .1 > apc_pdu2.snmpwalk

**Comment by cmeschin** [comment]
Hi Quentin,
I send you snmpwalk both 16A and 32A models in MP if it have differences.

**Comment by garnier-quentin** [comment]
Hi Cedric,

Could you test it ?

**Comment by cmeschin** [comment]
Hi Quentin,
I'm in holidays. I test it in few days.
Regards.
