### ISSUE TITLE
cloud::microsoft::office365::management::plugin json error

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#4096]
Hi all, 
I am trying to monitor office365 with Centreon. 
I have followed all the documentation to create the API requirements and authorizations on microsoft azure. 
I have installed both the official centreon plugins from the plugin pack and cli, and also used the git plugins.
But when i run a check it gives me the error bellow : 
./centreon_plugins.pl --plugin=cloud::microsoft::office365::management::plugin --mode=service-status --tenant='xxxxxxxx' --client-id='xxxxxxxxxxxx' --client-secret='xxxxxxxxxxxxxxxx'
UNKNOWN: Cannot decode json response

any idea why this is not working please ? any help would be appreciated.
thank you

**Comment by garnier-quentin** [comment]
Could you provide the --debug ?

**Comment by saharawolf** [comment]
yes there it is :

UNKNOWN: Cannot decode json response
======> request send
POST https://login.microsoftonline.com/xxxxxxxxxxx/oauth2/v2.0/token
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=xxxxxxxxxx&client_secret=xxxxxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
======> response done
500 read failed: Transport endpoint is not connected
Content-Type: text/plain
Client-Date: Fri, 09 Dec 2022 15:45:31 GMT
Client-Warning: Internal response

read failed: Transport endpoint is not connected at /usr/share/perl5/LWP/Protocol/http.pm line 325.

**Comment by garnier-quentin** [comment]
There is a connection issue. Could you first use the backend curl ? --http-backend=curl
Do you have a proxy to set ?

**Comment by saharawolf** [comment]
and this is the error returned by the centreon plugin : 
UNKNOWN: Cannot decode json response: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE html PUBLI...") at /usr/lib/centreon/plugins/centreon_office365_management_api.pl line 7358.
======> request send
POST https://login.windows.net/xxxxxxxxxx/oauth2/token?api-version=1.0
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=xxxxxxxx&client_secret=xxxxxxxxxx&resource=https%3A%2F%2Fmanage.office.com
======> response done
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache
Date: Fri, 09 Dec 2022 15:47:18 GMT
Pragma: no-cache
Content-Length: 1510
Content-Type: application/json; charset=utf-8
Expires: -1
Client-Date: Fri, 09 Dec 2022 15:47:19 GMT
Client-Peer: 20.190.159.72:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
Client-SSL-Cert-Subject: /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/CN=login.windows.net
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: fpc=AvfcnuVCsSVNv4X6v7QPIwac65MbAQAAAIdPJdsOAAAA; expires=Sun, 08-Jan-2023 15:47:19 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Ests-Server: 2.1.14167.14 - NEULR1 ProdSlices
X-Ms-Request-Id: 63b1eb28-57f5-49fc-ab97-e943b6c90200
X-XSS-Protection: 0

{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"3599","expires_on":"1670604439","not_before":"1670600539","resource":"https://manage.office.com","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZS5vZmZpY2UuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMDFjNWY4YzctNTIzZC00Njc3LTkwMzMtMDVjMzllNWQ0NDFjLyIsImlhdCI6MTY3MDYwMDUzOSwibmJmIjoxNjcwNjAwNTM5LCJleHAiOjE2NzA2MDQ0MzksImFpbyI6IkUyWmdZTkIvdUxzeTJQV242MXY5UFIxbkgvc0VBUUE9IiwiYXBwaWQiOiI3MzU4YmQ0Ny1iZGNmLTQ4ZTEtYmE2Mi0wNzRhOGM5NDcwYTIiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMWM1ZjhjNy01MjNkLTQ2NzctOTAzMy0wNWMzOWU1ZDQ0MWMvIiwib2lkIjoiZjdmMTAwOWUtNDRlNy00MGUxLWI0MzktMGRmM2M0YzUxNmFjIiwicmgiOiIwLkFZSUF4X2pGQVQxU2QwYVFNd1hEbmwxRUhJQTFPY1VGLUFGRWxlaVV0NmJ2TDhLQ0FBQS4iLCJyb2xlcyI6WyJBY3Rpdml0eUZlZWQuUmVhZERscCIsIlNlcnZpY2VIZWFsdGguUmVhZCIsIkFjdGl2aXR5RmVlZC5SZWFkIl0sInN1YiI6ImY3ZjEwMDllLTQ0ZTctNDBlMS1iNDM5LTBkZjNjNGM1MTZhYyIsInRpZCI6IjAxYzVmOGM3LTUyM2QtNDY3Ny05MDMzLTA1YzM5ZTVkNDQxYyIsInV0aSI6IktPdXhZX1ZYX0VtcmwtbER0c2tDQUEiLCJ2ZXIiOiIxLjAifQ.jnvkrZJIyTQMVkimsRyaWf3FUldE-CSy9n04T3kOaBjHBdHeodVjbsBscL4bpzXnUARioIQM1v2kgiu72-LZ9DgYQgPeallo1oRqZ5xTIl0QyZIjL-jaMkfCrTy1DDhiEMFmNgW4j_8-ZbFDqKfaQ9fXBsgXGFaDPA8-JbGQ_IiMvIvT5XtMX2pFBOWLGgHf8QSkmfTAjCt49PrZEcj-PASejFDNJJVk0TYsbXi_8OgFMmQIqy-NJH90n_TY970S-KvMKI3ZICcfr81weffD02iLPFrgR06sk0PMwavP4O8C6FdmKJQW4bwlxkfV-ukbN53_Fmz8WZbFlWEEOGhuow"}
======> request send
GET https://manage.office.com/api/v1.0/xxxxxxxxxxxx/ServiceComms/Services
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZS5vZmZpY2UuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMDFjNWY4YzctNTIzZC00Njc3LTkwMzMtMDVjMzllNWQ0NDFjLyIsImlhdCI6MTY3MDYwMDUzOSwibmJmIjoxNjcwNjAwNTM5LCJleHAiOjE2NzA2MDQ0MzksImFpbyI6IkUyWmdZTkIvdUxzeTJQV242MXY5UFIxbkgvc0VBUUE9IiwiYXBwaWQiOiI3MzU4YmQ0Ny1iZGNmLTQ4ZTEtYmE2Mi0wNzRhOGM5NDcwYTIiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMWM1ZjhjNy01MjNkLTQ2NzctOTAzMy0wNWMzOWU1ZDQ0MWMvIiwib2lkIjoiZjdmMTAwOWUtNDRlNy00MGUxLWI0MzktMGRmM2M0YzUxNmFjIiwicmgiOiIwLkFZSUF4X2pGQVQxU2QwYVFNd1hEbmwxRUhJQTFPY1VGLUFGRWxlaVV0NmJ2TDhLQ0FBQS4iLCJyb2xlcyI6WyJBY3Rpdml0eUZlZWQuUmVhZERscCIsIlNlcnZpY2VIZWFsdGguUmVhZCIsIkFjdGl2aXR5RmVlZC5SZWFkIl0sInN1YiI6ImY3ZjEwMDllLTQ0ZTctNDBlMS1iNDM5LTBkZjNjNGM1MTZhYyIsInRpZCI6IjAxYzVmOGM3LTUyM2QtNDY3Ny05MDMzLTA1YzM5ZTVkNDQxYyIsInV0aSI6IktPdXhZX1ZYX0VtcmwtbER0c2tDQUEiLCJ2ZXIiOiIxLjAifQ.jnvkrZJIyTQMVkimsRyaWf3FUldE-CSy9n04T3kOaBjHBdHeodVjbsBscL4bpzXnUARioIQM1v2kgiu72-LZ9DgYQgPeallo1oRqZ5xTIl0QyZIjL-jaMkfCrTy1DDhiEMFmNgW4j_8-ZbFDqKfaQ9fXBsgXGFaDPA8-JbGQ_IiMvIvT5XtMX2pFBOWLGgHf8QSkmfTAjCt49PrZEcj-PASejFDNJJVk0TYsbXi_8OgFMmQIqy-NJH90n_TY970S-KvMKI3ZICcfr81weffD02iLPFrgR06sk0PMwavP4O8C6FdmKJQW4bwlxkfV-ukbN53_Fmz8WZbFlWEEOGhuow
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded

======> response done
HTTP/1.1 404 Not Found
Date: Fri, 09 Dec 2022 15:47:19 GMT
Server: Microsoft-IIS/10.0
Content-Length: 1245
Content-Type: text/html
Client-Date: Fri, 09 Dec 2022 15:47:19 GMT
Client-Peer: 13.69.233.43:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
Client-SSL-Cert-Subject: /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/CN=manage.office.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Title: 404 - File or directory not found.
X-Powered-By: ASP.NET

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

**Comment by garnier-quentin** [comment]
You are using a old version. Please update it

**Comment by saharawolf** [comment]
Hello, 
i have downloaded the package again from github but the result is the same 
UNKNOWN: Cannot decode json response
======> request send
POST https://login.microsoftonline.com/xxxxxxxxxxxxxxx/oauth2/v2.0/token
Accept: application/json
User-Agent: centreon::plugins::backend::http::useragent
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=xxxxxxxxxxxxxxxxxx&client_secret=xxxxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
======> response done
500 read failed: Transport endpoint is not connected
Content-Type: text/plain
Client-Date: Mon, 12 Dec 2022 09:51:27 GMT
Client-Warning: Internal response

read failed: Transport endpoint is not connected at /usr/share/perl5/LWP/Protocol/http.pm line 325.

Is there some command to run directly on the Centreon-plugins folder to force an update ? 

Thank you

**Comment by garnier-quentin** [comment]
please use options ```--http-backend=curl --insecure```

**Comment by saharawolf** [comment]
the error is different now : 
UNKNOWN: curl perform error : SSL connect error
== Info: About to connect() to login.microsoftonline.com port 443 (#0)
== Info:   Trying 40.126.32.73...
== Info: Connected to login.microsoftonline.com (40.126.32.73) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info: NSS error -5961 (PR_CONNECT_RESET_ERROR)
== Info: TCP connection reset by peer
== Info: Closing connection 0

**Comment by garnier-quentin** [comment]
It's a network issue. Need to set a proxy maybe ?

**Comment by saharawolf** [comment]
Hi, 
thank you. Indeed it was a proxy issue. The check is now executing. 
I have one last request please. I noticed that the Perfdata are not changed to Graphic . the Graphic is empty even if there is some data : 

  'perfdate'=1670842800;;;; 'active_sites'=11sites;;;0;30 'total_usage_active'=885370711685B;;;0; 'total_usage_inactive'=8136382771B;;;0; 'total_file_count_active'=289180;;;0; 'total_file_count_inactive'=4507;;;0; 'total_active_file_count'=668;;;0; 'total_visited_page_count'=3;;;0; 'total_page_view_count'=5;;;0;

![image](https://user-images.githubusercontent.com/28105870/207908534-b70c9eb0-6186-451f-b2c4-f9270fe18205.png)

**Comment by garnier-quentin** [comment]
Maybe you need to wait a little. If you still have the issue about that, open an issue in github centreon
