### ISSUE TITLE
[network::cisco::wlc::snmp::plugin] mode=ap-status: how to exclude a radio interface

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4097]
CRITICAL: access point 'AP-XFAC-01' radio interface '2' status: down | 'radio_interface_channels_utilization_0'=6%;;;0;100 'radio_interface_channels_utilization_1'=2%;;;0;100
Model: unknown
checking access point 'AP-XFAC-01'
    status: associated
    radio interface '0' status: up, channels utilization: 6 %
    radio interface '1' status: up, channels utilization: 2 %
    radio interface '2' status: down

we have different AP where radio 2 is down by design (not used). how we can exclude/override to monitor only radio 0/1 or exclude radio 2?

**Comment by garnier-quentin** [comment]
You have 2 solutions:
- there is a administration state: you can put it down (if possible)
- you can use the display variable: ```--critical-status='%{admstatus} eq "enable" and %{opstatus} eq "down" and %{display} =~ /0|1/'```

**Comment by joschi99** [comment]
I have just tried similar and seems not working
```
--critical-status='%{admstatus} eq "enable" and %{opstatus} !~ /associated|downloading/ and %{display} =~ /0|1/' 
CRITICAL: access point 'AP-XFAC-01' radio interface '2' status: down | 'radio_interface_channels_utilization_0'=13%;;;0;100 'radio_interface_channels_utilization_1'=2%;;;0;100
Model: unknown
checking access point 'AP-XFAC-01'
    status: associated
    radio interface '0' status: up, channels utilization: 13 %
    radio interface '1' status: up, channels utilization: 2 %
    radio interface '2' status: down

```

**Comment by garnier-quentin** [comment]
Sorry it's: ```--critical-radio-status='%{admstatus} eq "enable" and %{opstatus} eq "down" and %{display} =~ /0|1/'```

**Comment by joschi99** [comment]
still the same problem

**Comment by garnier-quentin** [comment]
It's weird. it should work.

**Comment by joschi99** [comment]
I'm not sure if this can handled with --critical-status, maybe we need a filter or a threshold overload.

**Comment by garnier-quentin** [comment]
Are you available for a session ? You can send me an email

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4104
