### ISSUE TITLE
[network::cisco::standard::snmp::plugin] Threshold wrong

### ISSUE THREAD

**Issue by mguend** [centreon/centreon-plugins#4099]
If I run this
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --authpassphrase XXX --authprotocol md5 --filter 'sensor,^(?!(celsius))' --filter-uom c,dbm --hostname 10.0.10.7 --maxrepetitions 20 --mode environment --snmp-timeout 60 --snmp-username icinga --snmp-version 3 --subsetleef 20

I get a WARNING for an Interface (WARNING: Sensor 'Ethernet1/36(celsius)/26381' is 21.945 C) because the warning threshold is detected as -120.648 ('sensor.celsius_Ethernet1/36(celsius)'=21.945;~:-120.648;;; )
If i check the transcievers threshold via ssh it is not set to -120.648. I changed the transciever but it has not helped.

Its a Nexus 5000 Switch.

**Comment by garnier-quentin** [comment]
You can overload the threshold. Because it's surely an issue on snmp agent values.

**Comment by garnier-quentin** [comment]
Option: ```--critical='sensor.celsius,.*,40'```

**Comment by mguend** [comment]
thanks for the workaround
