### ISSUE TITLE
apps::protocols::http::plugin 401 Unauthorized

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon-plugins#4100]
Bonjour,

Je voudrais aller faire un check HTTP response pour une url.
Lorsque que je me connecte en interface graphique, le navigateur me demande de m'authentifier avec mes identifiants AD. Cependant je n'arrive pas à passer cette étape en ligne de commande. Car les commandes "--credentials, --username, --password" ne donnent rien.

Une idée pour effectuer une authentification navigateur en ligne de commande ?

**Comment by Xinerys** [comment]
![Uploading Annotation 2022-12-13 120459.png…]()

**Comment by garnier-quentin** [comment]
Could you try to do the authentication with curl command line ?

**Comment by Xinerys** [comment]
J'ai essayé cette commande : 
curl -u 'username:pwd' -k https://urltest.com

Résultat : 401 - Unauthorized: Access is denied due to invalid credentials

**Comment by garnier-quentin** [comment]
I cant help you if you cant make it with curl command line
