### ISSUE TITLE
App-DB-Elasticsearch-* > Proto is set 2x

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#4101]
Hi,

There are --proto 2x on command line for all command ElasticSearch.

 --port='$_HOSTELASTICSEARCHPORT$' --proto='$_HOSTELASTICSEARCHPROTO$' --proto=$_HOSTELASTICSEARCHPROTO$ --username='$_HOSTELASTICSEARCHUSERNAME$'

**Comment by garnier-quentin** [comment]
i don't think it's a problem. but we are going to fix it (to be clean)

**Comment by romsworld** [comment]
Yes, it's not an issue, just an info.
