### ISSUE TITLE
apps::protocols::http::plugin : CRITICAL: 501 Protocol scheme 'connect' is not supported 

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon-plugins#4102]
Hi, 

I want to make "check https" mode response.

/usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=urltest.com --proto='https' --urlpath='/urltest/index.html' --proxyurl='http://test:passwd@proxy.test.lan:80' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE"

but i have this result : CRITICAL: 501 Protocol scheme 'connect' is not supported | 'time'=0.005s;;;0; 'size'=47B;;;0;
An Idea ?

**Comment by garnier-quentin** [comment]
Please use the curl backend: ```--http-backend=curl --insecure```

**Comment by Xinerys** [comment]
What is the differense with --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" ?

**Comment by Xinerys** [comment]
It's Work thanks !!

**Comment by garnier-quentin** [comment]
thanks for the feedback. --insecure is easier to use than --ssl-opt or curl-opt options.
