### ISSUE TITLE
Network interface

### ISSUE THREAD

**Issue by Ludge** [centreon/centreon-plugins#411]
Hi 
On snmp_standard::mode::interfaces, how can I convert MB TO GB in status information ?
Exemple : Interface 'eth0' Traffic Out : 113.95Mb/s (1139.52%)

**Comment by garnier-quentin** [comment]
Hi,

You cannot. It's automatic, it depends of the traffic. If it goes above 1000Mb, it will be in Gb.

**Comment by cmeschin** [comment]
Hi,
I have the same result in some cases, SNMP returns wrong speed.
In this case it probably returns 10Mb instead of 1000Mb.
So you can force IFSPEED to the real value (in Mb).
regards.
