### ISSUE TITLE
--plugin=apps::protocols::x509::plugin - UNKNOWN: curl setopt error

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon-plugins#4114]
Bonjour,

J'ai un probleme lorsque je souhaite verifier un certificat SSL. Le check HTTP fonctionne pour info.
Voici la commande : 
`/usr/lib/centreon/plugins//centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --mode=certificate --custommode=https --hostname=urltest.com --port=443 --urlpath='/' --proxyurl='http://account:Password@proxy.test.lan:80' --http-backend=curl --insecure
`
 I have this : 
UNKNOWN: curl setopt error: 'An unknown option was passed in to libcurl'.

**Comment by garnier-quentin** [comment]
To use that plugin with curl, you need to be on centos 8 or debian 11. In centos 7, it won't work (the library is too old)

**Comment by Xinerys** [comment]
Est-il possible de mettre à jour CentOS 7 vers Centos 8?

**Comment by garnier-quentin** [comment]
You cannot. You need to install a new poller

**Comment by Xinerys** [comment]
Donc installer un CentOS 8 ?

**Comment by garnier-quentin** [comment]
Yes. Or a debian 11

**Comment by Xinerys** [comment]
Better than Centos 8 ?

**Comment by garnier-quentin** [comment]
As you prefer

**Comment by Xinerys** [comment]
Can i export Centreon configuration ? to  a Centreon installed on Debian 11 on Centos 8 ?

**Comment by garnier-quentin** [comment]
You only need to install the new poller and move host configuration to that poller

**Comment by Xinerys** [comment]
Yes,i installed the plugin AWIE to export the configuration but he is not available in plugin pack

**Comment by Xinerys** [comment]
Ok j'ai réussi à exporté les données c'est bon :) !
