### ISSUE TITLE
--plugin=apps::protocols::http::plugin  - Connect to internal Webs ite with header authentification

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon-plugins#4117]
BOnjour, 
J'ai un site interne que je voudrais superviser, cependant il me met une petite bulle "header" qui dit "ce site demande de vous connecter". Je dois inscrire mes ID ldap puis la page s'ouvre, cependant comment faire cela avec le check http ?

**Comment by garnier-quentin** [comment]
It's surely a basic auth. Do you have a screenshot ?

**Comment by Xinerys** [comment]
I have something like this [https://www.qwant.com/?client=opensearch&q=header+basic+authentification+firefox&t=images&o=0%3AFD7BDFDB38C17590A53E7B27648A15C64350D174](url)

This authentication is based on ADaccount.

**Comment by garnier-quentin** [comment]
Use following options: ```--credentials --basic --username='xxx' --password='yyy'```

**Comment by Xinerys** [comment]
/usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=test.lan --proto='http' --port='80' --urlpath='/urlpath ' --credentials --basic --username='myname' --password='mypassword'

I've this message : 
CRITICAL: 401 Unauthorized | 'time'=0.097s;;;0; 'size'=6892B;;;0;

when I debug, I get an error WEB page that I already got when I refused to authenticate via a graphical browser, so I have the impression that the information is bad or does not pass.

**Comment by garnier-quentin** [comment]
Maybe you can use option ntlm: ```--credentials --ntlmv2 --username='myname' --password='mypassword'```

**Comment by Xinerys** [comment]
Same thing,

What is the command to use basic authentification with curl ?

**Comment by garnier-quentin** [comment]
You can use curl -u username:password

**Comment by Xinerys** [comment]
Same thing

<title>Erreur détaillée d'IIS 10.0 - 401.2 - Unauthorized</title>

**Comment by Xinerys** [comment]
======> response done
HTTP/1.1 401 Unauthorized
Cache-Control: private
Date: Tue, 03 Jan 2023 09:38:15 GMT
Server: Microsoft-IIS/10.0
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
Content-Length: 6892
Content-Type: text/html; charset=utf-8
Client-Date: Tue, 03 Jan 2023 09:38:13 GMT
Client-Peer: 10.241.64.209:80
Client-Response-Num: 7

**Comment by garnier-quentin** [comment]
It should work with ntlm option. Please use the http backend curl: ```--credentials --ntlmv2 --username='myname' --password='mypassword' --http-backend=curl```

Have you set the domain for the username ?

**Comment by garnier-quentin** [comment]
Try the following options: ```--credentials --ntlmv2 --username='myname' --password='mypassword' --http-backend=curl```

**Comment by Xinerys** [comment]
It's work Thank you :) !

**Comment by Xinerys** [comment]
it's another subject, but I need help on "Open-ticket" can you help me ?

**Comment by garnier-quentin** [comment]
You can post it in centreon-open-tickets github

**Comment by Xinerys** [comment]
I've already do i think : https://github.com/centreon/centreon/issues/592

**Comment by Xinerys** [comment]
It's "public archive" i can't create a issue
