### ISSUE TITLE
New plugin storage Lenovo S3200

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#412]
Hi team,

Is it possible to monitor storage bay Lenovo S3200? I have tested with all IBM Storage bay plugins without any result :-(

Here is the MIB files
[fw_snmp_mib_v1.0_s3200_s2200.zip](https://github.com/centreon/centreon-plugins/files/282103/fw_snmp_mib_v1.0_s3200_s2200.zip)

And the snmpwalk .1 
[lenovo.txt](https://github.com/centreon/centreon-plugins/files/282107/lenovo.txt)

Thanks a lot

**Comment by garnier-quentin** [comment]
The snmp is poor. It uses the fibre alliance mib. Could you test the mode 'hardware' of plugin 'storage/hp/msa2000/snmp/plugin.pm' ? It should give you something

**Comment by matthieu-robin** [comment]
Salut Quentin,
I have tested this morning, and it works fine. 

Thanks a lot.
