### ISSUE TITLE
High CPU load when polling interfaces on some models of Cisco Small Business switches

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#4120]
Hello.

We have found that on some models of **Cisco Small Business** switches, periodic interface polling with centreon_plugins results in cyclical high CPU usage. We do a poll once a minute. The problem is observed in the same way for different plugins "**network::cisco::standard::snmp::plugin**" and "**network::cisco::smallbusiness::standard::snmp::plugin**"

Interestingly, the problem is observed on several models of switches.

**Models affected:**

Switch Cisco SG200-50P
Switch Cisco SF550X-24P
Switch Cisco SG350X-48MP

**Unaffected Models:**

Switch Cisco SG250-26HP
Switch Cisco SG250-10P
Switch Cisco SG350-10P
Switch Cisco SG350-28P
Switch Cisco SF350-08

The microcode of the switches has been updated - this did not change the situation.

For example, I will give a graph of the processor load with the monitoring of interfaces enabled and disabled for the **Cisco SF550X 24P** switch

![изображение](https://user-images.githubusercontent.com/17614847/209613855-b257c0e4-53e3-4615-beef-3fffcf77e0f8.png)

Examples of commands we use to monitor interfaces:

```
# ./centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces 
--snmp-version='2c' --snmp-community=public --hostname='E11-SW001' 
--warning-out-traffic='98' --warning-out-error='1' --warning-out-discard='50' 
--warning-in-traffic='98' --warning-in-error='1' --warning-in-discard='50' --warning-in-crc='1' 
--use-new-perfdata --units-traffic='%' --add-err-disable --name 
--filter-uom='null' --filter-perfdata-adv='not (%(value) == 0)' 
--filter-perfdata='.*[.](traffic|error|discard|crc)[.].*' 
--critical-status='%{errdisable} ne "-"' 
--change-perfdata='.*,,eval(%(label) =~ s/(\d)[.](\d)/\1_\2/g)' 
--change-perfdata='.*,,eval(%(label) =~ s/(\ |\/)/_/g)' 
--add-traffic --add-errors

```

```
# ./centreon_plugins.pl --plugin=network::cisco::smallbusiness::standard::snmp::plugin --mode=interfaces 
--snmp-version='2c' --snmp-community='public' --hostname='E11-SW001'
--warning-out-traffic='98' --warning-out-error='1' --warning-out-discard='50' 
--warning-in-traffic='98' --warning-in-error='1' --warning-in-discard='50' 
--use-new-perfdata --units-traffic='percent_delta'  --name  --filter-uom='null' 
--filter-perfdata-adv='not (%(value) == 0)' --filter-perfdata='.*[.](traffic|error|discard|crc)[.].*' 
--change-perfdata='.*,,eval(%(label) =~ s/(\d)[.](\d)/\1_\2/g)' 
--change-perfdata='.*,,eval(%(label) =~ s/(\ |\/)/_/g)' 
--add-traffic --add-errors

```

Please tell us how we can try to fix this situation. Thank you.

**Comment by Aleksey-Maksimov** [comment]
We have found that stackable switch models can return a large number of interfaces when polled, even if there are no interfaces. 

For example, if the switch supports 8 units in a stack of 48 ports each, then polling returns 384 interfaces!, even if there is only one switch and only 24 interfaces. Perhaps this is the root of the problem and causes heavy load on the Switch CPU. 

So far, we have found only a workaround - to set an interface filter for each switch

`--name --interface='^(?i)(Fa1/0/|Te1/0/)'`

Maybe there is a more elegant way to solve the problem than specifying an interface filter for each individual switch?

**Comment by garnier-quentin** [comment]
You can optimize with the following option if you use snmpv2 or snmpv3: ```--force-counters64```. The plugin will poll less OIDs. Maybe it will be enough.

**Comment by Aleksey-Maksimov** [comment]
Unfortunately this doesn't help. The switch still returns a lot of non-existent interfaces when polling

**Comment by garnier-quentin** [comment]
It's only to save snmp requests. The plugin cannot know if it's a stack interface or not. So your solution is right

**Comment by Aleksey-Maksimov** [comment]
Understood. Thank you.
