### ISSUE TITLE
Extended output: HTML Format

### ISSUE THREAD

**Issue by dcop7** [centreon/centreon-plugins#4127]
Hello,

We are trying to implement an alert that shows a table in Extended output.

We are trying to put a HTML code. However, the HTML is not processed. It shows the HTML code instead.

It is possible to process the HTML code and shows a HTML table instead of HTML code "<table>...output...</table>"?

We tried to use "\n" and "\t" to simulate a table, but it only processes "\n", the "\t" doesn't do a TAB.

Thank you.

**Comment by garnier-quentin** [comment]
It's not processed because of centreon-web. It's a security constraint i think

**Comment by dcop7** [comment]
Is there any alternative? Any out-of-the-box solution to output info into a table?
There is anyway to process the "\t"?

**Comment by dcop7** [comment]
I didn't found it before, but I found an issue: https://github.com/centreon/centreon-archived/issues/11335 but without any solution

**Comment by dcop7** [comment]
How can we change the escape option in centreon config?
https://github.com/centreon/centreon/blob/4609eb7fd599c58c271a3db53758fc61b023a5f6/centreon/www/class/centreonUtils.class.php

`    /**
     * Converted a HTML string according to the selected method
     *
     * @param string $stringToEscape String to escape
     * @param int $escapeMethod Escape method (default: ESCAPE_LEGACY_METHOD)
     * @return string Escaped string
     * @see CentreonUtils::ESCAPE_LEGACY_METHOD
     * @see CentreonUtils::ESCAPE_ALL_EXCEPT_LINK
     * @see CentreonUtils::ESCAPE_ALL
     * @see CentreonUtils::ESCAPE_ILLEGAL_CHARS
     */`

**Comment by dcop7** [comment]
It is possible to change some php to avoid escaping the HTML code and process it?
Maybe here? https://github.com/centreon/centreon/blob/4609eb7fd599c58c271a3db53758fc61b023a5f6/centreon/www/class/centreonUtils.class.php

**Comment by garnier-quentin** [comment]
You can patch the source code. But you'll need to maintain the patch

**Comment by dcop7** [comment]
@garnier-quentin , yes I know and we are checking if this is viable, but can you point me where is the code itself? Is to revert that commit and the "Status information" and "Extended status information" will not escape HTML code and it will show as table?
Thank you!

**Comment by garnier-quentin** [comment]
For the legacy page ? For the new resource status, the frontend is with react. I cant help you with react

**Comment by dcop7** [comment]
Ok, thank you.
