### ISSUE TITLE
X509 check in http mode depends on HTTP status code

### ISSUE THREAD

**Issue by mayrstefan** [centreon/centreon-plugins#4131]
## Bug
centreon_protocol_x509.pl responds with status UNKNOWN if the application answers with a 503 service unavailable. This is irrelevant to the certificate status that should be checked.

### Proposed solution
Ignore the status code in the HTTP response

### Version
- centreon-plugin-Applications-Protocol-X509-20220913-081426.el7.centos.noarch

**Comment by garnier-quentin** [comment]
-no-follow option solved your issue ?

**Comment by mayrstefan** [comment]
No, this are two independant problems. We currently see this issue with a L7 loadbalancer (e.g. haproxy) with all backends down. The certificate is fine (still valid) but because the loadbalancer responds with HTTP 503 service unavailable the check commands return with UNKNOWN instead of an OK as I would have expected.

**Comment by garnier-quentin** [comment]
Which command do you use ? Because i don't reproduce that error with protocol x509

**Comment by mayrstefan** [comment]
Example
```
[root@centreon]:~ # /usr/lib/centreon/plugins/centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --mode=certificate --custommode='https' --hostname='haproxy' --port=443 --warning-status='%{expiration} < 15' --critical-status='%{expiration} < 7' --hostname=demo.example.com --verbose
UNKNOWN: Service Unavailable
```

Same with debug flag
```
[root@centreon]:~ # /usr/lib/centreon/plugins/centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --mode=certificate --custommode='https' --hostname='haproxy' --port=443 --warning-status='%{expiration} < 15' --critical-status='%{expiration} < 7' --hostname=demo.example.com --verbose --debug
UNKNOWN: Service Unavailable
======> request send
GET https://demo.example.com:443/
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Length: 107
Content-Type: text/html
Client-Date: Tue, 17 Jan 2023 08:58:45 GMT
Client-Peer: 192.168.1.23:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /DC=com/DC=example/CN=ACME CA
Client-SSL-Cert-Subject: /C=DE/ST=Bayern/L=Muenchen/O=ACME/CN=demo.example.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
as we can see in the debug output we got certificate (Client-SSL-*) but it is not fully checked because of the http status code

**Comment by garnier-quentin** [comment]
I cant reproduce it. I need an internet website.  

Could you try with ```--http-backend=curl``` ?

**Comment by mayrstefan** [comment]
@garnier-quentin what is missing to reproduce it? A webpage with a 503 status code like https://httpstat.us/503?

**Comment by garnier-quentin** [comment]
It works for me:
```
perl centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=certificate --custommode='https' --hostname='haproxy' --port=443 --warning-status='%{expiration} < 15' --critical-status='%{expiration} < 7' --hostname=httpstat.us  --urlpath=/503 --verbose
OK: Certificate for 'httpstat.us' expires in '178' days [2023-08-04T23:59:59Z] - Issuer: '/C=US/O=DigiCert, Inc./CN=GeoTrust Global TLS RSA4096 SHA256 2022 CA1' 
Alternative subject names: httpstat.us.
```

**Comment by mayrstefan** [comment]
Very strange: 12 days ago the non-working check we had changed from unknown to ok and now I can not reproduce it.

**Comment by garnier-quentin** [comment]
If you reproduce it, please comment it. I will check it
