### ISSUE TITLE
[hardware::ups::standard::rfc1628::snmp::plugin] - Mode battery-status : Change condition of warning

### ISSUE THREAD

**Issue by ZeZombini** [centreon/centreon-plugins#414]
Hi,
I have a problem with the warning and the critical of the rfc1628 standard ups plugin.
It's simple but I don't know where the modification has to be done.

I want to have a warning return when the remaining charge drops below 90% and a critical one when it drops below 80%.

But the plugin makes a greater that instead of a less that.

How can I change that ?

THanks a lot.

![battery-satuts problem](https://cloud.githubusercontent.com/assets/8303126/15570390/21958b5e-2336-11e6-8ea1-3d572db7ab34.jpg)

**Comment by Sims24** [comment]
Hi, 

You should use following format : --warning 90: --critical 80:

**Comment by ZeZombini** [comment]
Ho ! Thanks !
