### ISSUE TITLE
HP Proliant plugins ignore drives on MegaRaid controller

### ISSUE THREAD

**Issue by LudekH2** [centreon/centreon-plugins#4141]
## Bug/Question
All three HP Proliant plugins (snmp, RestAPI, xml) ignore storage components on recently manufactured ProLiant DL360 Gen10 Plus server, P/N:P28948-B21.
This servers are equiped with HPE MR416i-a Gen10+ RAID controller, NOT Smart Array !

I have plugins installed via GUI. To test further I clonned https://github.com/centreon/centreon-plugins to the directory /root/plugin-dnl/plugins-git/
--- following is command line and result for this server using xmlapi:
/root/plugin-dnl/plugins-git/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname='10.1.1.83' --username='monitor' --password='***'  --component='drive' --verbose
OK: All 0 components are ok [].
Checking drive enclosures
Checking physical drives
Checking logical drives
[root@centreon centreon-plugins]# 

--- folowing is restapi command and full output:
/root/plugin-dnl/plugins-git/centreon-plugins/centreon_plugins.pl  --plugin=hardware::server::hp::ilo::restapi::plugin --mode=hardware --hostname='10.1.1.83' --api-username='monitor' --api-password='***'  --component='.*' --verbose --ssl-opt=SSL_verify_mode=SSL_VERIFY_NONE
WARNING: Device 'chassis:1/Intel Eth Adptr I350T4 OCPv3' status is 'Warning' | 'chassis:1~Fan 1#hardware.fan.speed.percentage'=23%;;;0;100 'chassis:1~Fan 2#hardware.fan.speed.percentage'=23%;;;0;100 'chassis:1~Fan 3#hardware.fan.speed.percentage'=23%;;;0;100 'chassis:1~Fan 4#hardware.fan.speed.percentage'=23%;;;0;100 'chassis:1~Fan 5#hardware.fan.speed.percentage'=23%;;;0;100 'chassis:1~Fan 6#hardware.fan.speed.percentage'=23%;;;0;100 'chassis:1~Fan 7#hardware.fan.speed.percentage'=23%;;;0;100 'chassis:1~psu:0#hardware.powersupply.power.watt'=85W;;;0; 'chassis:1~psu:1#hardware.powersupply.power.watt'=79W;;;0; 'chassis:1~01-Inlet Ambient#hardware.temperature.celsius'=21C;0:42;0:47;; 'chassis:1~02-CPU 1#hardware.temperature.celsius'=40C;0:70;;; 'chassis:1~04-P1 DIMM 1-8#hardware.temperature.celsius'=31C;0:85;;; 'chassis:1~06-P1 DIMM 9-16#hardware.temperature.celsius'=30C;0:85;;; 'chassis:1~12-VR P1#hardware.temperature.celsius'=35C;0:110;0:115;; 'chassis:1~14-VR P1 Mem 1#hardware.temperature.celsius'=25C;0:110;0:115;; 'chassis:1~15-VR P1 Mem 2#hardware.temperature.celsius'=26C;0:110;0:115;; 'chassis:1~18-Chipset#hardware.temperature.celsius'=39C;0:100;;; 'chassis:1~19-BMC#hardware.temperature.celsius'=59C;0:110;0:115;; 'chassis:1~20-HD Max#hardware.temperature.celsius'=40C;0:60;;; 'chassis:1~22-Stor Batt#hardware.temperature.celsius'=20C;0:60;;; 'chassis:1~23-E-Fuse#hardware.temperature.celsius'=27C;0:100;;; 'chassis:1~24-P/S 1#hardware.temperature.celsius'=40C;;;; 'chassis:1~25-P/S 1 Inlet#hardware.temperature.celsius'=20C;;;; 'chassis:1~26-P/S 2#hardware.temperature.celsius'=40C;;;; 'chassis:1~27-P/S 2 Inlet#hardware.temperature.celsius'=20C;;;; 'chassis:1~29-LOM Card#hardware.temperature.celsius'=40C;0:95;;; 'chassis:1~30-HD Controller#hardware.temperature.celsius'=40C;0:100;;; 'chassis:1~31-HD Cntlr Zone#hardware.temperature.celsius'=30C;0:90;0:95;; 'chassis:1~32-Board Inlet#hardware.temperature.celsius'=22C;0:60;;; 'chassis:1~33-BMC Zone#hardware.temperature.celsius'=35C;0:90;0:95;; 'chassis:1~34-P/S 2 Zone#hardware.temperature.celsius'=23C;0:90;0:95;; 'chassis:1~35-I/O Zone#hardware.temperature.celsius'=27C;0:90;0:95;; 'chassis:1~36-Battery Zone#hardware.temperature.celsius'=26C;0:90;0:95;; 'chassis:1~38-PCI 1 Zone#hardware.temperature.celsius'=36C;0:90;0:95;; 'chassis:1~40-PCI 2 Zone#hardware.temperature.celsius'=37C;0:90;0:95;; 'chassis:1~50-CPU 1 PkgTmp#hardware.temperature.celsius'=45C;;;; 'chassis:1~29-LOM Card-CORE#hardware.temperature.celsius'=41C;;;; 'chassis:1~30-HD Controller-I/O controller#hardware.temperature.celsius'=41C;0:110;0:115;; 'hardware.chassis.count'=1;;;; 'hardware.device.count'=6;;;; 'hardware.fan.count'=7;;;; 'hardware.psu.count'=2;;;; 'hardware.temperature.count'=47;;;;
checking chassis
chassis '1' status is 'OK' [instance: 1, state: Enabled]
checking devices
device 'chassis:1/Empty slot 1' status is 'n/a' [instance: 1.1, state: Absent]
device 'chassis:1/Empty slot 2' status is 'n/a' [instance: 1.2, state: Absent]
device 'chassis:1/HPE MR416i-a Gen10+' status is 'OK' [instance: 1.3, state: Enabled]
device 'chassis:1/Intel Eth Adptr I350T4 OCPv3' status is 'Warning' [instance: 1.4, state: Enabled]
device 'chassis:1/HPE Smart Storage Battery' status is 'OK' [instance: 1.5, state: Enabled]
device 'chassis:1/Embedded Video Controller' status is 'OK' [instance: 1.6, state: Enabled]
checking fans
fan 'chassis:1/Fan 1' status is 'OK' [instance: 1.0, state: Enabled, speed: 23 Percent]
fan 'chassis:1/Fan 2' status is 'OK' [instance: 1.1, state: Enabled, speed: 23 Percent]
fan 'chassis:1/Fan 3' status is 'OK' [instance: 1.2, state: Enabled, speed: 23 Percent]
fan 'chassis:1/Fan 4' status is 'OK' [instance: 1.3, state: Enabled, speed: 23 Percent]
fan 'chassis:1/Fan 5' status is 'OK' [instance: 1.4, state: Enabled, speed: 23 Percent]
fan 'chassis:1/Fan 6' status is 'OK' [instance: 1.5, state: Enabled, speed: 23 Percent]
fan 'chassis:1/Fan 7' status is 'OK' [instance: 1.6, state: Enabled, speed: 23 Percent]
checking power supplies
power supply 'chassis:1/psu:0' status is 'OK' [instance: 1.0, state: Enabled, value: 85]
power supply 'chassis:1/psu:1' status is 'OK' [instance: 1.1, state: Enabled, value: 79]
checking temperatures
temperature 'chassis:1/01-Inlet Ambient' status is 'OK' [instance: 1.0, state: Enabled, value: 21]
temperature 'chassis:1/02-CPU 1' status is 'OK' [instance: 1.1, state: Enabled, value: 40]
temperature 'chassis:1/03-CPU 2' status is 'n/a' [instance: 1.2, state: Absent, value: 0]
temperature 'chassis:1/04-P1 DIMM 1-8' status is 'OK' [instance: 1.3, state: Enabled, value: 31]
temperature 'chassis:1/05-P1 PMM 1-8' status is 'n/a' [instance: 1.4, state: Absent, value: 0]
temperature 'chassis:1/06-P1 DIMM 9-16' status is 'OK' [instance: 1.5, state: Enabled, value: 30]
temperature 'chassis:1/07-P1 PMM 9-16' status is 'n/a' [instance: 1.6, state: Absent, value: 0]
temperature 'chassis:1/08-P2 DIMM 1-8' status is 'n/a' [instance: 1.7, state: Absent, value: 0]
temperature 'chassis:1/09-P2 PMM 1-8' status is 'n/a' [instance: 1.8, state: Absent, value: 0]
temperature 'chassis:1/10-P2 DIMM 9-16' status is 'n/a' [instance: 1.9, state: Absent, value: 0]
temperature 'chassis:1/11-P2 PMM 9-16' status is 'n/a' [instance: 1.10, state: Absent, value: 0]
temperature 'chassis:1/12-VR P1' status is 'OK' [instance: 1.11, state: Enabled, value: 35]
temperature 'chassis:1/13-VR P2' status is 'n/a' [instance: 1.12, state: Absent, value: 0]
temperature 'chassis:1/14-VR P1 Mem 1' status is 'OK' [instance: 1.13, state: Enabled, value: 25]
temperature 'chassis:1/15-VR P1 Mem 2' status is 'OK' [instance: 1.14, state: Enabled, value: 26]
temperature 'chassis:1/16-VR P2 Mem 1' status is 'n/a' [instance: 1.15, state: Absent, value: 0]
temperature 'chassis:1/17-VR P2 Mem 2' status is 'n/a' [instance: 1.16, state: Absent, value: 0]
temperature 'chassis:1/18-Chipset' status is 'OK' [instance: 1.17, state: Enabled, value: 39]
temperature 'chassis:1/19-BMC' status is 'OK' [instance: 1.18, state: Enabled, value: 59]
temperature 'chassis:1/20-HD Max' status is 'OK' [instance: 1.19, state: Enabled, value: 40]
temperature 'chassis:1/21-Exp Bay Drive' status is 'n/a' [instance: 1.20, state: Absent, value: 0]
temperature 'chassis:1/22-Stor Batt' status is 'OK' [instance: 1.21, state: Enabled, value: 20]
temperature 'chassis:1/23-E-Fuse' status is 'OK' [instance: 1.22, state: Enabled, value: 27]
temperature 'chassis:1/24-P/S 1' status is 'OK' [instance: 1.23, state: Enabled, value: 40]
temperature 'chassis:1/25-P/S 1 Inlet' status is 'OK' [instance: 1.24, state: Enabled, value: 20]
temperature 'chassis:1/26-P/S 2' status is 'OK' [instance: 1.25, state: Enabled, value: 40]
temperature 'chassis:1/27-P/S 2 Inlet' status is 'OK' [instance: 1.26, state: Enabled, value: 20]
temperature 'chassis:1/29-LOM Card' status is 'OK' [instance: 1.27, state: Enabled, value: 40]
temperature 'chassis:1/30-HD Controller' status is 'OK' [instance: 1.28, state: Enabled, value: 40]
temperature 'chassis:1/31-HD Cntlr Zone' status is 'OK' [instance: 1.29, state: Enabled, value: 30]
temperature 'chassis:1/32-Board Inlet' status is 'OK' [instance: 1.30, state: Enabled, value: 22]
temperature 'chassis:1/33-BMC Zone' status is 'OK' [instance: 1.31, state: Enabled, value: 35]
temperature 'chassis:1/34-P/S 2 Zone' status is 'OK' [instance: 1.32, state: Enabled, value: 23]
temperature 'chassis:1/35-I/O Zone' status is 'OK' [instance: 1.33, state: Enabled, value: 27]
temperature 'chassis:1/36-Battery Zone' status is 'OK' [instance: 1.34, state: Enabled, value: 26]
temperature 'chassis:1/37-PCI 1' status is 'n/a' [instance: 1.35, state: Absent, value: 0]
temperature 'chassis:1/38-PCI 1 Zone' status is 'OK' [instance: 1.36, state: Enabled, value: 36]
temperature 'chassis:1/39-PCI 2' status is 'n/a' [instance: 1.37, state: Absent, value: 0]
temperature 'chassis:1/40-PCI 2 Zone' status is 'OK' [instance: 1.38, state: Enabled, value: 37]
temperature 'chassis:1/41-PCI 3' status is 'n/a' [instance: 1.39, state: Absent, value: 0]
temperature 'chassis:1/42-PCI 3 Zone' status is 'n/a' [instance: 1.40, state: Absent, value: 0]
temperature 'chassis:1/43-ExpBayBoot' status is 'n/a' [instance: 1.41, state: Absent, value: 0]
temperature 'chassis:1/46-AHCI HD Max' status is 'n/a' [instance: 1.42, state: Absent, value: 0]
temperature 'chassis:1/50-CPU 1 PkgTmp' status is 'OK' [instance: 1.43, state: Enabled, value: 45]
temperature 'chassis:1/51-CPU 2 PkgTmp' status is 'n/a' [instance: 1.44, state: Absent, value: 0]
temperature 'chassis:1/29-LOM Card-CORE' status is 'OK' [instance: 1.45, state: Enabled, value: 41]
temperature 'chassis:1/30-HD Controller-I/O controller' status is 'OK' [instance: 1.46, state: Enabled, value: 41]
[root@centreon centreon-plugins]#

---- folowing is command for snmp plugin and output:
/root/plugin-dnl/plugins-git/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=10.1.1.83 --snmp-version='2c' --snmp-community='***'  --component='.*' --verbose
UNKNOWN: SNMP Table Request: problem to get values (try --snmp-force-getnext option)
Product Name: ProLiant DL360 Gen10 Plus, Serial: CZJ2401NHC, Rom Version: U46 v1.64 (08/11/2022)

---- folowing is command for snmp plugin and output with --snmp-force-getnext :
/root/plugin-dnl/plugins-git/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=10.1.1.83 --snmp-version='2c' --snmp-community='***'  --component='.*' --verbose --snmp-force-getnext
CRITICAL: physical nic '4' is failed - logical nic '4' is failed UNKNOWN: physical nic '2' is other - physical nic '3' is other | '0.1#hardware.powersupply.power.watt'=88W;;500;; '0.1#hardware.powersupply.voltage.volt'=228V;;;; '0.2#hardware.powersupply.power.watt'=82W;;500;; '0.2#hardware.powersupply.voltage.volt'=229V;;;; '0.1~ambient#hardware.temperature.celsius'=18C;;0:42;; '0.2~cpu#hardware.temperature.celsius'=40C;;0:70;; '0.4~memory#hardware.temperature.celsius'=30C;;0:85;; '0.6~memory#hardware.temperature.celsius'=29C;;0:85;; '0.12~system#hardware.temperature.celsius'=34C;;0:110;; '0.14~system#hardware.temperature.celsius'=23C;;0:110;; '0.15~system#hardware.temperature.celsius'=25C;;0:110;; '0.18~system#hardware.temperature.celsius'=39C;;0:100;; '0.19~system#hardware.temperature.celsius'=60C;;0:110;; '0.20~system#hardware.temperature.celsius'=40C;;0:60;; '0.22~system#hardware.temperature.celsius'=19C;;0:60;; '0.23~system#hardware.temperature.celsius'=27C;;0:100;; '0.24~powerSupply#hardware.temperature.celsius'=40C;;0:0;; '0.25~powerSupply#hardware.temperature.celsius'=20C;;0:0;; '0.26~powerSupply#hardware.temperature.celsius'=40C;;0:0;; '0.27~powerSupply#hardware.temperature.celsius'=20C;;0:0;; '0.28~ioBoard#hardware.temperature.celsius'=40C;;0:95;; '0.29~system#hardware.temperature.celsius'=40C;;0:100;; '0.30~system#hardware.temperature.celsius'=30C;;0:90;; '0.31~system#hardware.temperature.celsius'=21C;;0:60;; '0.32~system#hardware.temperature.celsius'=35C;;0:90;; '0.33~powerSupply#hardware.temperature.celsius'=24C;;0:90;; '0.34~system#hardware.temperature.celsius'=28C;;0:90;; '0.35~system#hardware.temperature.celsius'=27C;;0:90;; '0.37~ioBoard#hardware.temperature.celsius'=36C;;0:90;; '0.39~ioBoard#hardware.temperature.celsius'=37C;;0:90;; '0.44~cpu#hardware.temperature.celsius'=45C;;0:0;; 'hardware.cpu.count'=1;;;; 'hardware.fan.count'=7;;;; 'hardware.ilo.count'=1;;;; 'hardware.lnic.count'=4;;;; 'hardware.memory.count'=32;;;; 'hardware.pnic.count'=4;;;; 'hardware.psu.count'=2;;;; 'hardware.temperature.count'=27;;;;
Product Name: ProLiant DL360 Gen10 Plus, Serial: CZJ2401NHC, Rom Version: U46 v1.64 (08/11/2022)
Checking cpu
cpu '0' [slot: 0, unit: 0, name: Intel(R) Xeon(R) Gold 6334 CPU @ 3.60GHz, socket: 1] status is ok.
Checking ide controllers
Checking ide logical drives
Checking ide physical drives
Checking power converters
Checking power supplies
powersupply '0.1' status is ok [redundance: 3, redundant partner: 0] (status noError).
powersupply '0.2' status is ok [redundance: 3, redundant partner: 0] (status noError).
Checking sas controllers
Checking sas logical drives
Checking sas physical drives
Checking scsi controllers
Checking scsi logical drives
Checking scsi physical drives
Checking fca host controller
Checking fca external controller
Checking fca external accelerator boards
Checking fca logical drives
Checking fca physical drives
Checking da controller
Checking da accelerator boards
Checking da logical drives
Checking da physical drives
Checking fans
fan '0.1' status is ok, speed is normal [location: system, redundance: not redundant, redundant partner: 0].
fan '0.2' status is ok, speed is normal [location: system, redundance: not redundant, redundant partner: 3].
fan '0.3' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 4].
fan '0.4' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 5].
fan '0.5' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 6].
fan '0.6' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 7].
fan '0.7' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 0].
Checking physical nics
physical nic '1' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
physical nic '2' [duplex: unknown, role: notApplicable, state: unknown, status: unknown] condition is other.
physical nic '3' [duplex: unknown, role: notApplicable, state: unknown, status: unknown] condition is other.
physical nic '4' [duplex: unknown, role: notApplicable, state: failed, status: linkFailure] condition is failed.
Checking logical nics
logical nic '1' [adapter count: 1, description: Logical Interface for vmnic0, status: ok] condition is ok.
logical nic '2' [adapter count: 1, description: Logical Interface for vmnic1, status: unknown] condition is other.
logical nic '3' [adapter count: 1, description: Logical Interface for vmnic2, status: unknown] condition is other.
logical nic '4' [adapter count: 1, description: Logical Interface for vmnic3, status: groupFailed] condition is failed.
Checking temperatures
'0.1' ambient temperature is 18C (42 max) (status is ok).
'0.2' cpu temperature is 40C (70 max) (status is ok).
'0.4' memory temperature is 30C (85 max) (status is ok).
'0.6' memory temperature is 29C (85 max) (status is ok).
'0.12' system temperature is 34C (110 max) (status is ok).
'0.14' system temperature is 23C (110 max) (status is ok).
'0.15' system temperature is 25C (110 max) (status is ok).
'0.18' system temperature is 39C (100 max) (status is ok).
'0.19' system temperature is 60C (110 max) (status is ok).
'0.20' system temperature is 40C (60 max) (status is ok).
'0.22' system temperature is 19C (60 max) (status is ok).
'0.23' system temperature is 27C (100 max) (status is ok).
'0.24' powerSupply temperature is 40C (0 max) (status is ok).
'0.25' powerSupply temperature is 20C (0 max) (status is ok).
'0.26' powerSupply temperature is 40C (0 max) (status is ok).
'0.27' powerSupply temperature is 20C (0 max) (status is ok).
'0.28' ioBoard temperature is 40C (95 max) (status is ok).
'0.29' system temperature is 40C (100 max) (status is ok).
'0.30' system temperature is 30C (90 max) (status is ok).
'0.31' system temperature is 21C (60 max) (status is ok).
'0.32' system temperature is 35C (90 max) (status is ok).
'0.33' powerSupply temperature is 24C (90 max) (status is ok).
'0.34' system temperature is 28C (90 max) (status is ok).
'0.35' system temperature is 27C (90 max) (status is ok).
'0.37' ioBoard temperature is 36C (90 max) (status is ok).
'0.39' ioBoard temperature is 37C (90 max) (status is ok).
'0.44' cpu temperature is 45C (0 max) (status is ok).
Checking ilo
ilo status is ok [message = ].
Checking memory
memory slot '0' [location: PROC 1 DIMM 1, size: 16777216kB] status is good
memory slot '1' [location: PROC 1 DIMM 2, size: 0kB] status is notPresent
memory slot '10' [location: PROC 1 DIMM 11, size: 0kB] status is notPresent
memory slot '11' [location: PROC 1 DIMM 12, size: 16777216kB] status is good
memory slot '12' [location: PROC 1 DIMM 13, size: 0kB] status is notPresent
memory slot '13' [location: PROC 1 DIMM 14, size: 16777216kB] status is good
memory slot '14' [location: PROC 1 DIMM 15, size: 0kB] status is notPresent
memory slot '15' [location: PROC 1 DIMM 16, size: 16777216kB] status is good
memory slot '16' [location: PROC 2 DIMM 1, size: 0kB] status is notPresent
memory slot '17' [location: PROC 2 DIMM 2, size: 0kB] status is notPresent
memory slot '18' [location: PROC 2 DIMM 3, size: 0kB] status is notPresent
memory slot '19' [location: PROC 2 DIMM 4, size: 0kB] status is notPresent
memory slot '2' [location: PROC 1 DIMM 3, size: 16777216kB] status is good
memory slot '20' [location: PROC 2 DIMM 5, size: 0kB] status is notPresent
memory slot '21' [location: PROC 2 DIMM 6, size: 0kB] status is notPresent
memory slot '22' [location: PROC 2 DIMM 7, size: 0kB] status is notPresent
memory slot '23' [location: PROC 2 DIMM 8, size: 0kB] status is notPresent
memory slot '24' [location: PROC 2 DIMM 9, size: 0kB] status is notPresent
memory slot '25' [location: PROC 2 DIMM 10, size: 0kB] status is notPresent
memory slot '26' [location: PROC 2 DIMM 11, size: 0kB] status is notPresent
memory slot '27' [location: PROC 2 DIMM 12, size: 0kB] status is notPresent
memory slot '28' [location: PROC 2 DIMM 13, size: 0kB] status is notPresent
memory slot '29' [location: PROC 2 DIMM 14, size: 0kB] status is notPresent
memory slot '3' [location: PROC 1 DIMM 4, size: 0kB] status is notPresent
memory slot '30' [location: PROC 2 DIMM 15, size: 0kB] status is notPresent
memory slot '31' [location: PROC 2 DIMM 16, size: 0kB] status is notPresent
memory slot '4' [location: PROC 1 DIMM 5, size: 16777216kB] status is good
memory slot '5' [location: PROC 1 DIMM 6, size: 0kB] status is notPresent
memory slot '6' [location: PROC 1 DIMM 7, size: 16777216kB] status is good
memory slot '7' [location: PROC 1 DIMM 8, size: 0kB] status is notPresent
memory slot '8' [location: PROC 1 DIMM 9, size: 0kB] status is notPresent
memory slot '9' [location: PROC 1 DIMM 10, size: 16777216kB] status is good

--- folowing is previous commands with component storage:
/root/plugin-dnl/plugins-git/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=10.1.1.83 --snmp-version='2c' --snmp-community='***'  --component='storage' --verbose --snmp-force-getnext
OK: All 0 components are ok [].
Product Name: ProLiant DL360 Gen10 Plus, Serial: CZJ2401NHC, Rom Version: U46 v1.64 (08/11/2022)
Checking ide controllers
Checking ide logical drives
Checking ide physical drives
Checking sas controllers
Checking sas logical drives
Checking sas physical drives
Checking scsi controllers
Checking scsi logical drives
Checking scsi physical drives
Checking fca host controller
Checking fca external controller
Checking fca external accelerator boards
Checking fca logical drives
Checking fca physical drives
Checking da controller
Checking da accelerator boards
Checking da logical drives
Checking da physical drives
[root@centreon centreon-plugins]#

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk of following branches ? .1.3.6.1.4.1.232

Maybe we can monitor with the rest api if snmp empty

**Comment by LudekH2** [comment]
I am not sure if I get it right. I did this: 
snmpwalk -c '***' -v 2c  10.1.1.83 .1.3.6.1.4.1.232 > ./snmpwalk.txt
output attached.
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/10411913/snmpwalk.txt)

**Comment by garnier-quentin** [comment]
It seems we cannot check it with SNMP (no more supported by HP). Maybe we can monitor it with HP ILO redfish API.

Could you provide curl outputs for the following endpoints (https://hewlettpackard.github.io/ilo-rest-api-docs/ilo5/#dmtf-redfish-storage-model):
- /redfish/v1/Systems/
- /redfish/v1/Systems/{systemid}/Storage/
- /redfish/v1/Systems/{systemid}/Storage/{storageid}/Controllers
- /redfish/v1/Systems/{systemid}/Storage/{storageid}/Drives/{driveid}

**Comment by LudekH2** [comment]
Hello, I am not sure how to do it properly.
I managed to get some output (in attached file).
I could not get /redfish/v1/Systems/1/Storage/DE009000/Controllers   (got ResourceMissingAtURI) - see attached file
Is this what you need?

[curl-results(redfish).txt](https://github.com/centreon/centreon-plugins/files/10426991/curl-results.redfish.txt)

**Comment by garnier-quentin** [comment]
Very nice. I can add:
```
- storage status
    - storage controller status
    - drives status
    - volumes status (i can display drives localtion for the volume)
```

**Comment by LudekH2** [comment]
Perfect!

**Comment by LudekH2** [comment]
Kindly let me know, when it is done so I can download and test it.

**Comment by garnier-quentin** [comment]
Could you test with that version ? https://github.com/centreon/centreon-plugins/archive/refs/heads/hp-ilo-restapi-add-storage.zip

**Comment by LudekH2** [comment]
Hi, 
I cant download it!  Getting 404: Not Found :-(

**Comment by garnier-quentin** [comment]
It's merged: https://github.com/centreon/centreon-plugins/archive/refs/heads/develop.zip

**Comment by LudekH2** [comment]
Thank you. It is working! I get folowing information now:

device 'chassis:1/HPE MR416i-a Gen10+' status is 'OK' [instance: 1.3, state: Enabled]

checking drives
drive 'system:1/DE009000/1' status is 'OK' [instance: 1.DE009000.1, state: Enabled, location: Port=2I:Box=1:Bay=2]
drive 'system:1/DE009000/2' status is 'OK' [instance: 1.DE009000.2, state: Enabled, location: Port=2I:Box=1:Bay=4]
drive 'system:1/DE009000/3' status is 'OK' [instance: 1.DE009000.3, state: Enabled, location: Port=2I:Box=1:Bay=3]
drive 'system:1/DE009000/5' status is 'OK' [instance: 1.DE009000.5, state: Enabled, location: Port=2I:Box=1:Bay=1]

checking storage controllers
storage controller 'system:1/DE009000/0' status is 'OK' [instance: 1.DE009000.0, state: Enabled]

checking storages
storage 'system:1/DE009000' status is 'OK' [instance: 1.DE009000, state: Enabled]

checking volumes
volume 'system:1/DE009000/238' status is 'OK' [instance: 1.DE009000.238, state: Enabled]
volume 'system:1/DE009000/239' status is 'OK' [instance: 1.DE009000.239, state: Enabled]

**Comment by garnier-quentin** [comment]
Thanks for the feedback!

**Comment by LudekH2** [comment]
Hello Quentin. 
Thanks again for making restapi check work on HPE MR416i-a Gen10. It is all I need, I can check SmartArray controllers with older "check_ilo2_health.pl" command.
However, you might be interested in my observations regarding restapi plugin. I happen to have another HPE Proliant Gen10 server, equiped with the traditional SmartArray controller - that is: ProLiant ML350 Gen10 with HPE Smart Array P816i-a SR Gen10. 
I tested updated hp::ilo::restapi::plugin against it and I am afraid result is not perfect. 
It gives warning for some empty device slots, e.g.: Device 'chassis:1/Empty slot 5' status is 'Warning'
It does not seem to check disks and storage :-(
I tried with version 2023-01-18 (and your recent update) as well as older version 2022-11-15, result is the same.
Please see the txt file.

[iLO-restapi-SAGen10.txt](https://github.com/centreon/centreon-plugins/files/10731278/iLO-restapi-SAGen10.txt)

**Comment by garnier-quentin** [comment]
Maybe the ilo version is too old. Could you provide the output with --debug ?

**Comment by LudekH2** [comment]
Here you are - in the attached file.
[iLO-restapi-SAGen10-debug.txt](https://github.com/centreon/centreon-plugins/files/11015942/iLO-restapi-SAGen10-debug.txt)

**Comment by garnier-quentin** [comment]
Surely it's too old. The storage endpoint is empty:
```
{"@odata.context":"/redfish/v1/$metadata#StorageCollection.StorageCollection","@odata.etag":"W/\"75983E8D\"","@odata.id":"/redfish/v1/Systems/1/Storage/","@odata.type":"#StorageCollection.StorageCollection","Description":"Storage subsystems known to this system","Name":"Storage","Members":[],"Members@odata.count":0}
```

**Comment by LudekH2** [comment]
What is too old?
Here is the outcome with latest iLO firmware on this server.
![iLO-SmartArray](https://user-images.githubusercontent.com/115085234/228176275-b8f0ea63-6137-4f9b-8d8c-2bb063241d37.png)
![iLOfw-278](https://user-images.githubusercontent.com/115085234/228176280-0aee58ea-3e73-43de-bb46-fef224deea8b.png)
[iLO-restapi-SAGen10-fw278.txt](https://github.com/centreon/centreon-plugins/files/11087092/iLO-restapi-SAGen10-fw278.txt)
