### ISSUE TITLE
[os::windows::local::plugin updates] - JSON error

### ISSUE THREAD

**Issue by steve730i** [centreon/centreon-plugins#4142]
In french (and other languages), we use accented characters. When Microsoft sends updates, the french description uses accented characters, the JSON translation results in error :
"Cannot decode json response: illegal backslash escape sequence in string, at character offset 44 (before "\\x85 jour cumulativ...")". 
The '\\x85' is a 'à' character... 
If I use '--ps-exec-only', the result is :
'[{"isMandatory":false,"title":"2023-01 Mise ▒ jour cumulative pour Windows Server 2019 pour les syst▒mes x64 (KB5022286)"}]
which is not too bad, but the plugin is not working right as there is no counting of updates available...

**Comment by garnier-quentin** [comment]
Please try the option: ```--source-encoding=ISO-8859-1``

**Comment by steve730i** [comment]
Marvelous !!!!!!
Thanks a lot !!! It works like a charm !!!!

**Comment by garnier-quentin** [comment]
thanks for your feedback
