### ISSUE TITLE
[apps::backup::rubrik::restapi::plugin] Add Rubrik API Service Account Authentication

### ISSUE THREAD

**Issue by brice-automatizit** [centreon/centreon-plugins#4144]
Hi, 

This issue is kind of follow-up of this one: Rubrik API token #3217
 
Since Rubrik is enforcing MFA for local account, they added a Service Account authentication.
We would like to remove our Centreon dedicated local account as we think it is better to use those dedicated service account.

This service accounts authentication is documented here: 
https://rubrikinc.github.io/api-doc-v1-8.0/#section/Authentication/Authentication-session

I suggest adding a switch in the plugin asking either serviceAccount authentication or not. 
In case of serviceAuthentication, we would require serviceAccountId (instead of api-username) and secret (instead of api-password) and an optionnal organizationId.

To get the token, you need to POST to this endpoint "https://<rubrik cluster ip>/api/v1/service_account/session" with the body containing the following object (organizationId still optionnal): 
```
{
  "serviceAccountId": "User:::62482f5f-8ff0-4524-a2e7-6564c46ecb5f",
  "secret": "b+eulP0u2SpSryNqf8TEQpQb4NV+dlgKqUu72+5RPlNER/Ma+PG9t6IswQO2FHAxFL5G+NfqlPsPStb7mm00",
  "organizationId": "Organization:::32482f5f-8ff0-4524-a2e7-6564c46ecb5f"
}'

```
In my test the token lifetime sent by this endpoint was 1 day.

Best regards
Brice

**Comment by garnier-quentin** [comment]
I see. Could you provide information about that PR also ? https://github.com/centreon/centreon-plugins/pull/3388

**Comment by brice-automatizit** [comment]
Unfortunately I'm sorry, I can't provide access to our (internal) appliances for security reasons. 

Here are the results of endpoints mentionned in the PR #3388 that may help you:

1. GET /api/v1/cluster/me (in bold, obfuscated informations)

{
    "id":  "**XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX**",
    "version":  "8.0.2-p1-22576",
    "apiVersion":  "1",
    "name":  "**HOSTNAME**",
    "timezone":  {
                     "timezone":  "Europe/Amsterdam"
                 },
    "geolocation":  {
                        "address":  "**Street, XXXXX City, Country**"
                    },
    "acceptedEulaVersion":  "1.3",
    "latestEulaVersion":  "1.3",
    "registeredMode":  "Legacy",
    "rubrikUrl":  "https://**ORAGNIZATION**.my.rubrik.com"
}

2. GET /api/v1/report/compliance_summary
{
    "totalProtected":  366,
    "numberOfInComplianceSnapshots":  357,
    "numberOfOutOfComplianceSnapshots":  9,
    "numberOfAwaitingFirstFullSnapshot":  0,
    "percentOfInComplianceSnapshots":  97.5,
    "percentOfOutOfComplianceSnapshots":  2.5,
    "updatedTime":  "2023-01-16T11:03:50.021Z"
}



3. GET /api/v1/report/compliance_summary_sla?snapshot_range=AllSnapshots
{
    "totalProtected":  366,
    "numberOfInComplianceSnapshots":  353,
    "numberOfOutOfComplianceSnapshots":  13,
    "percentOfInComplianceSnapshots":  96.4,
    "percentOfOutOfComplianceSnapshots":  3.6,
    "updatedTime":  "2023-01-16T11:03:50.021Z",
    "updatedStatus":  "Updated",
    "snapshotRange":  "AllSnapshots"
}

Let me know if you need anything else.

**Comment by garnier-quentin** [comment]
Do you know why we don't have same values ? I will close the PR because the plugin uses the internal api. I could create a mapping for api v1 but i'll need an access to do that.

**Comment by brice-automatizit** [comment]
Wow, you're really fast.

I think the compliance_summary_sla is more appropriate if the appliance support it (ie. the CDM version is up-to-date)
From my understanding, the compliance_summary endpoint only look on 24-hours period while the compliance_summary_sla look for a true compliance based on policies assigned to protected objects. I can open a support case if you want but since the author is not coming back after one year, i suppose yeah, you can close this PR. 

I tested your version, I got 
{"errorType":"user_error","message":"Invalid ID or secret.","code":"RBK40000040","cause":null}

I'm testing directly from bash. 
As my secret contains single quote (also an interrogation mark and an equal sign), I tried to escape it with a backslash or enclose it with double quotes but I'm not sure this is the correct way to do it.
Note the service-account is like **User:::** followed by a GUID.
Also, I noticed there is temp file created somewhere, but I dont know where:
`my $has_cache_file = $self->{cache}->read(statefile => 'rubrik_api_' . md5_hex($self->{option_results}->{hostname} . '_' . $self->{service_account}));
`

In a nutshell i tried the following whithout any success:

./centreon_plugins.pl --plugin=apps::backup::rubrik::restapi::plugin --mode=disks --hostname='<IP>' --proto='https' --insecure --service-account=User\:\:\:<THE GUID> --secret=xxxx --debug

./centreon_plugins.pl --plugin=apps::backup::rubrik::restapi::plugin --mode=disks --hostname='<IP>' --proto='https' --insecure --service-account=User:::<THE GUID> --secret="xxxx" --debug

./centreon_plugins.pl --plugin=apps::backup::rubrik::restapi::plugin --mode=disks --hostname='<IP>' --proto='https' --insecure --service-account=User:::<THE GUID> --secret="x\'xxx" --debug

./centreon_plugins.pl --plugin=apps::backup::rubrik::restapi::plugin --mode=disks --hostname='<IP>' --proto='https' --insecure --service-account=User:::<THE GUID> --secret="xxxx" --organization-id=<orga guid>

**Comment by garnier-quentin** [comment]
It can be interesting to have the response from rubrik support.

You can check with --debug option (to see http calls)

**Comment by brice-automatizit** [comment]
My bad, I was providing the wrong organizationId. I didn't see in the documentation that it is also prefixed with "Organization:::". 
With the correct one it works. Without any organization-id argument, it still send which is wrong {"organizationId":"","secret":"mysupersecret","serviceAccountId":"User:::mysuperserviceaccountid"} which gives an error. 

Indeed I removed the line 201:
```
 my $json_request = {
            serviceAccountId => $self->{service_account},
            secret => $self->{secret}
            #organizationId => $self->{organization_id}
        };
```
And everything is still fine without extra organization-id.

I will create the support ticket and will you know

**Comment by garnier-quentin** [comment]
I have done the patch. Now organizationId is set only if there is a value. It should be ok you can retest it

**Comment by brice-automatizit** [comment]
Thanks @garnier-quentin !
Works like a charm (tested all available modes)

**Comment by brice-automatizit** [comment]
Feedback from Rubrik, does it answer to your questions ?


1. SLA Compliance Summary:
API: GET /report/compliance_summary_sla
Description: 
It runs a compliance check on each SLA and summarizes information about compliance with the policies set forth in each SLA Domain. The compliance calculation includes on-demand snapshots.The report depends on the time range selected. Objects may appear out-of-compliance if they have missed snapshots in the specified time range.



2. Compliance Summary:
API: /api/v1/report/compliance_summary
Description: 
This reports checks for snappables whether a snapshot has been taken in the past 24 hours. It does not check whether the object is protected with SLA or what is the duration and frequency of backup assigned in the SLA.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4162

**Comment by brice-automatizit** [comment]
Hi @garnier-quentin ,

Do you think this patch will be included in the yum packages ? I tried to update it since last week (trough  `yum install centreon-plugin-Applications-Rubrik-Restapi` ) but it keeps telling me the package "centreon-plugin-Applications-Rubrik-Restapi-20230117-074217.el7.centos.noarch" is already installed and up-to-date. 

Then this file does not include the patch:
```
# rpm -q --filesbypkg centreon-plugin-Applications-Rubrik-Restapi-20230117-074217.el7.centos.noarch
centreon-plugin-Applications-Rubrik-Restapi /usr/lib/centreon/plugins/centreon_rubrik_restapi.pl
# ls -ltr /usr/lib/centreon/plugins/centreon_rubrik_restapi.pl
-rwxrwxr-x 1 root root 359936 17 janv. 08:46 /usr/lib/centreon/plugins/centreon_rubrik_restapi.pl
# /usr/lib/centreon/plugins/centreon_rubrik_restapi.pl --help |grep service | wc -l
0
```
