### ISSUE TITLE
(plugin) apps::protocols::cifs - Check file NAME

### ISSUE THREAD

**Issue by Xinerys** [centreon/centreon-plugins#4148]
Bonjour,

je voudrais savoir s'il est possible de checker le nom d'un fichier avec ce plugin ?

**Comment by garnier-quentin** [comment]
You can use files-count mode and option --filter-file option

**Comment by Xinerys** [comment]
On peut aussi vérifier le contenu d'un fichier ? Du genre : Si les caractères suivants <Tests OK> sont dans le fichier test.txt alors passer l'état de l'hote en OK.

**Comment by garnier-quentin** [comment]
You can use the mode scenario with a json config like that:
```
    [
      {"cmd": "write", "label": "write", "options": { "file": "/test/test.txt", "content": "my string 1" } },
      {"cmd": "read", "options": { "file": "/test/test.txt", "match": "string" } },
      {"cmd": "delete", "options": { "file": "/test/test.txt" } }
    ]
```

**Comment by Xinerys** [comment]
Ok thank i need to see how to check a test file

**Comment by Xinerys** [comment]
@garnier-quentin , j'essaie de comprendre le plugin, j'ai du mal a trouver des tutoriels sur internet. 

Actuellement j'ai un pc (Windows) sur lequel j'ai un partage de fichier. J'ai monté le partage sur le poste centos (centreon) ce qui me permet de lire des fichiers depuis le poste centos des fichiers partagé par le poste Windows. 
Est-ce possible d'aller checker un nom de fichier présent dans le partage Windows?
Si oui, Pouvez-vous me montrer une commande type pour checker le nom d'un fichier ?

**Comment by garnier-quentin** [comment]
You don't need to mount it with procotol cifs plugin.

**Comment by Xinerys** [comment]
cifs username/password : c'est le compte de la session windows de destination ?

Enfaite si je comprends bien, le plugin se connecte sur la session pour aller checker le fichier demandé ?

**Comment by garnier-quentin** [comment]
Yes exactly

**Comment by Xinerys** [comment]
@garnier-quentin Parfait j'ai reussi à checker l'existence d'un fichier avec le mode 'files'. 

Maintenant, j'ai un soucis. La commande executé sur centreon me dis :
Statut détaillé
UNKNOWN: cannot stat file '/Résultats/Creation_devis_OK.txt': Stat error: Opération non permise

Pourtant cette même commande fonctionne via SSh sur le compte centreon-engine...

**Comment by Vass86** [comment]
Change ton utilisateur. Au lieu de DOMAIN\USER => USER@DOMAIN

**Comment by garnier-quentin** [comment]
The centengine daemon uses '/' as current directory. So you need to set the full path for the txt file.

**Comment by Vass86** [comment]
Actually, when you are in --mode files-date you can't do a wildcard on --file.
It's make the pluggin not really usefull. too bad, i'm gonna have to script

**Comment by garnier-quentin** [comment]
i don't think cifs protocol understand wildcards. You can check the complete directory and filter file with a regexp (perl side)

**Comment by Vass86** [comment]
Oh ! What the option for filter file ? 
I've go something like that : 
`/usr/lib/centreon/plugins//centreon_protocol_cifs.pl --plugin=apps::protocols::cifs::plugin --mode=files-date --hostname='HOSTNAME' --cifs-username='' --cifs-password='' --timeout='' --filter-perfdata='^.+.tst' --file='/folder/old/' --directory='' --warning-mtime-last='1800' --critical-mtime-last='3600' --cifs-username="USR@domain" --cifs-password="password" --verbose`
but I still can't filter my tst file only

**Comment by garnier-quentin** [comment]
I could add the option ;)

**Comment by Vass86** [comment]
That would be great :D !
I Explain my idea. I've got a folder, I want to check if a csv is older than 1 hour. Usualy the folder is empty (of csv) but there are others in there (that i don't want to check).
Thanks !

**Comment by Xinerys** [comment]
i use this command in centreon UI and SSH : 
/usr/lib/centreon/plugins//centreon_protocol_cifs.pl --plugin=apps::protocols::cifs::plugin --mode=files --hostname=fi31093 --file='/Résultats/Creation-devis-OK.txt' --cifs-username='testdomain\ops' --cifs-password='wgbvsfd!'

Resultat : 
UNKNOWN: cannot stat file '/Résultats/Creation-devis-OK.txt': Stat error: Opération non permise

But with SSh console : 
OK: number of files: 1 - File '/Résultats/Creation-devis-OK.txt' last modified 22h 51m 44s, size: 17.00B | 'files.detected.count'=1;;;0; '/Résultats/Creation-devis-OK.txt#file.mtime.last.seconds'=82304s;;;0; '/Résultats/Creation-devis-OK.txt#file.size.bytes'=17B;;;0;

It's Joke ? XD

**Comment by garnier-quentin** [comment]
I don't understand. The 2 commands are tested in ssh ? So it should be the same

**Comment by Xinerys** [comment]
Pour information j'utilise le compte centreon-engine via SSH.

**Comment by Xinerys** [comment]
J'ai trouvé ! 

Si vous voulez faire une commande sur Centreon il faut mettre le "cifs-username" avec ce format : "user@domain.lan" et non "domain\user" sino  vous aurez une erreur.

 Exemple de commande créé sur Centreon UI : 
`$CENTREONPLUGINS$/centreon_protocol_cifs.pl --plugin=apps::protocols::cifs::plugin --mode=files --hostname=$HOSTADDRESS$ --file='$_HOSTFILE$' --cifs-username='ops@domain.lan' --cifs-password='Azerty'`

**Comment by Xinerys** [comment]
@garnier-quentin Donc si je veux aller checker une chaine de caractère dans un fichier, je dois passer en mode "scenario". Je peux faire ça en une ligne de commande ? Ou il me faut un autre fichier à coté que je met en event handler?

**Comment by garnier-quentin** [comment]
You can add the json directly in the --scenario option (or use a file)

**Comment by Xinerys** [comment]
Je n'i connais rien en JSON.

Quel est l'option "use a file" ?

**Comment by garnier-quentin** [comment]
```--scenario='your json directly'```

**Comment by Xinerys** [comment]
Comme ceci ?
`/usr/lib/centreon/plugins//centreon_protocol_cifs.pl --plugin=apps::protocols::cifs::plugin --mode=scenario --hostname=FI31093 --cifs-username='ops@cardifiard.lan' --cifs-password='Azertyuiop&76!' --scenario='[{"cmd": "read", "options": { "file": "/Résultats/Creation-devis.txt", "match": "OK" } }]'`

J'obtiens un message d'erreur:

CRITICAL: Scenario status: failed | 'scenario.execution.time.milliseconds'=35ms;;;0; 'scenario.steps.count'=1;;;0; 'scenario.errors.count'=1;;;0; '1#step.execution.time.milliseconds'=35ms;;;0;
Step '1' execution time: 35 ms, status: failed [message: Can't read file: Aucun fichier ou dossier de ce type]

**Comment by garnier-quentin** [comment]
It can access that file ?

**Comment by Xinerys** [comment]
Yes  ! 

`/usr/lib/centreon/plugins//centreon_protocol_cifs.pl --plugin=apps::protocols::cifs::plugin --mode=files --hostname=fi31093 --file='/Resultats/Creation-devis.txt' --cifs-username='ops@domain.lan' --cifs-password='Azerty'
`

OK: number of files: 1 - File '/Resultats/Creation-devis.txt' last modified 22h 51m 45s, size: 32.00B | 'files.detected.count'=1;;;0; '/Resultats/Creation-devis.txt#file.mtime.last.seconds'=82305s;;;0; '/Resultats/Creation-devis.txt#file.size.bytes'=32B;;;0;

**Comment by garnier-quentin** [comment]
It's not the same name: 
```--file='/Resultats/Creation-devis.txt'```
```"file": "/Résultats/Creation-devis.txt"```

**Comment by Xinerys** [comment]
Yes i saw ! :) It's working !

`/usr/lib/centreon/plugins//centreon_protocol_cifs.pl --plugin=apps::protocols::cifs::plugin --mode=scenario --hostname=FI31093 --cifs-username='ops@domain.lan' --cifs-password='Azerty' --scenario='[{"cmd": "read", "options": { "file": "/Resultats/Creation-devis.txt", "match": "creation devis sur IUT PROD : OK" } }]' --debug`

Resultat : 
OK: Scenario status: success, execution time: 51 ms, errors: 0 

Now i need to add Warning and critical status : 

- Warning : if the command is KO the firt time
- Critical if the commands is KO to three times.

**Comment by garnier-quentin** [comment]
You cannot do that with the plugin

**Comment by Xinerys** [comment]
Ok i need to search

**Comment by garnier-quentin** [comment]
@Vass86 there is a new option

https://github.com/centreon/centreon-plugins/pull/4165
