### ISSUE TITLE
[storage::netapp::snmp::plugin] Skipped no values, but there are values

### ISSUE THREAD

**Issue by dooko** [centreon/centreon-plugins#415]
Hi,
When using filesys mode for netapp, I can't get values. However, when doing a snmpwalk I get those values.
I'm using snmp version 2c.

$ /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname=10.182.141.156 --verbose --snmp-version=2c
OK: All filesys usages are ok | 'inodes_aggr0'=1%;;;0;100 'inodes_/vol/vmware/'=0%;;;0;100 'inodes_/vol/exch_data/'=0%;;;0;100 'inodes_/vol/vol0/'=0%;;;0;100 'inodes_/vol/vol0/.snapshot'=0%;;;0;100 'inodes_/vol/hyperv1/'=0%;;;0;100 'inodes_/vol/ocr/'=1%;;;0;100 'inodes_/vol/redolog/'=0%;;;0;100
Filesys 'aggr0' usage : skipped (no value(s)), Inodes Used : 1 %
Filesys '/vol/redolog/.snapshot' usage : skipped (no value(s)), Inodes : skipped (no value(s))
Filesys '/vol/vmware/' usage : skipped (no value(s)), Inodes Used : 0 %
Filesys '/vol/vmware/.snapshot' usage : skipped (no value(s)), Inodes : skipped (no value(s))
Filesys '/vol/exch_data/' usage : skipped (no value(s)), Inodes Used : 0 %
Filesys '/vol/exch_data/.snapshot' usage : skipped (no value(s)), Inodes : skipped (no value(s))
Filesys 'aggr0/.snapshot' usage : skipped (no value(s)), Inodes : skipped (no value(s))
Filesys '/vol/vol0/' usage : skipped (no value(s)), Inodes Used : 0 %
Filesys '/vol/vol0/.snapshot' usage : skipped (no value(s)), Inodes Used : 0 %
Filesys '/vol/hyperv1/' usage : skipped (no value(s)), Inodes Used : 0 %
Filesys '/vol/hyperv1/.snapshot' usage : skipped (no value(s)), Inodes : skipped (no value(s))
Filesys '/vol/ocr/' usage : skipped (no value(s)), Inodes Used : 1 %
Filesys '/vol/ocr/.snapshot' usage : skipped (no value(s)), Inodes : skipped (no value(s))
Filesys '/vol/redolog/' usage : skipped (no value(s)), Inodes Used : 0 %

OID dfFileSys :
$ snmpwalk -c public -v2c 10.182.141.156 .1.3.6.1.4.1.789.1.5.4.1.2
SNMPv2-SMI::enterprises.789.1.5.4.1.2.1 = STRING: "aggr0"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.2 = STRING: "aggr0/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.3 = STRING: "/vol/vol0/"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.4 = STRING: "/vol/vol0/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.5 = STRING: "/vol/hyperv1/"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.6 = STRING: "/vol/hyperv1/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.7 = STRING: "/vol/ocr/"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.8 = STRING: "/vol/ocr/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.9 = STRING: "/vol/redolog/"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.10 = STRING: "/vol/redolog/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.11 = STRING: "/vol/vmware/"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.12 = STRING: "/vol/vmware/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.13 = STRING: "/vol/exch_data/"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.14 = STRING: "/vol/exch_data/.snapshot"

OID df64TotalKBytes :
$ snmpwalk -c public -v2c 10.182.141.156 .1.3.6.1.4.1.789.1.5.4.1.29
SNMPv2-SMI::enterprises.789.1.5.4.1.29.1 = Counter64: 5013126144
SNMPv2-SMI::enterprises.789.1.5.4.1.29.2 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.29.3 = Counter64: 16777216
SNMPv2-SMI::enterprises.789.1.5.4.1.29.4 = Counter64: 4194304
SNMPv2-SMI::enterprises.789.1.5.4.1.29.5 = Counter64: 461373440
SNMPv2-SMI::enterprises.789.1.5.4.1.29.6 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.29.7 = Counter64: 409600
SNMPv2-SMI::enterprises.789.1.5.4.1.29.8 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.29.9 = Counter64: 110100480
SNMPv2-SMI::enterprises.789.1.5.4.1.29.10 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.29.11 = Counter64: 3229614080
SNMPv2-SMI::enterprises.789.1.5.4.1.29.12 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.29.13 = Counter64: 576716800
SNMPv2-SMI::enterprises.789.1.5.4.1.29.14 = Counter64: 0

OID df64UsedKBytes :
$ snmpwalk -c public -v2c 10.182.141.156 .1.3.6.1.4.1.789.1.5.4.1.30
SNMPv2-SMI::enterprises.789.1.5.4.1.30.1 = Counter64: 4435885764
SNMPv2-SMI::enterprises.789.1.5.4.1.30.2 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.30.3 = Counter64: 974324
SNMPv2-SMI::enterprises.789.1.5.4.1.30.4 = Counter64: 183980
SNMPv2-SMI::enterprises.789.1.5.4.1.30.5 = Counter64: 279761656
SNMPv2-SMI::enterprises.789.1.5.4.1.30.6 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.30.7 = Counter64: 215576
SNMPv2-SMI::enterprises.789.1.5.4.1.30.8 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.30.9 = Counter64: 67097152
SNMPv2-SMI::enterprises.789.1.5.4.1.30.10 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.30.11 = Counter64: 2891548760
SNMPv2-SMI::enterprises.789.1.5.4.1.30.12 = Counter64: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.30.13 = Counter64: 467726668
SNMPv2-SMI::enterprises.789.1.5.4.1.30.14 = Counter64: 0

As I understand, it may come from the centreon::plugins::values package.

Thanks for your help.

**Comment by garnier-quentin** [comment]
It's maybe there is nothing for dfDedupeSavedPercent and dfCompressSavedPercent ? I could set specific counters for that.

**Comment by dooko** [comment]
Well, that's it.

$ snmpwalk -c public -v2c 10.182.141.156 .1.3.6.1.4.1.789.1.5.4.1.38
SNMPv2-SMI::enterprises.789.1.5.4.1.38 = No Such Object available on this agent at this OID

$ snmpwalk -c public -v2c 10.182.141.156 .1.3.6.1.4.1.789.1.5.4.1.40 
SNMPv2-SMI::enterprises.789.1.5.4.1.40 = No Such Object available on this agent at this OID

**Comment by dooko** [comment]
As I don't use those values, I've changed the OIDs in the code.

**Comment by garnier-quentin** [comment]
Could you test it ? I have done a commit. Should be ok now.

**Comment by dooko** [comment]
Works great, thanks.

**Comment by garnier-quentin** [comment]
Thanks for the feedback
