### ISSUE TITLE
[os::windows::snmp::plugin] mode=service return always ok

### ISSUE THREAD

**Issue by loic60600** [centreon/centreon-plugins#416]
Hello, 

I have the last version of centreon-plugins. But if i try to test windows service with this command : 

perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode service --hostname UCtest --snmp-version 2 --snmp-community public --service=zerzerzefr --critical=1

I have : OK: All service states are ok |

My windows host doesn't have the service "zerzerzefr".

Sorry for my bad English.

Thanks in advance,

**Comment by Sims24** [comment]
Hello, 

Your command will trigger a CRITICAL when there is more than 1 service matching the name 'zerzerzefr' . 

If you use this syntax for the threshold that should work as expected : --critical 1:

We will try enhance documentation on this point to remind about monitoring plugins threshold and range.

**Comment by loic60600** [comment]
Hello, 

Thanks for your response.

If i try with "--critical 1:", i have always a critical alert even with good services. For example : 

perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode service --hostname UCtest --snmp-version 2 --snmp-community public   --service=SNMP   --critical 1:

I have : CRITICAL: Service problem 'SNMP' |

**Comment by Sims24** [comment]
Sorry my bad, this should be : 

--critical :1 

Means that will trigger an alert if number of service running is above 1

**Comment by loic60600** [comment]
I try with --critical :1 but i have already ok. 

Example : 

perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode service --hostname Uctest--snmp-version 2 --snmp-community public --service=dsesfe --critical :1
OK: All service states are ok |

**Comment by Sims24** [comment]
No this should definitely be --critical 1: to trigger an alert  if the service is not running. 

Could you try with --verbose and be sure service is present/not mispelled ?

This work for me.
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin os::windows::snmp::plugin --mode=service --verbose --critical 3: --hostname=10.10.10.10 --service=Alimentation --service="Client DNS" --service=test

**Comment by loic60600** [comment]
Hello,

Thank you for this return.

Actually It works too with 2 services or more .However if I want to monitor a single service, that always returns me OK. 

For example if the service "Client DNS" are down : 

```
 perl centreon_plugins.pl --plugin os::windows::snmp::plugin --mode=service --verbose --critical 0: --hostname=UCtest --service="Client DNS"
OK: All service states are ok |
Service pattern 'Client DNS': service list
```

```
perl centreon_plugins.pl --plugin os::windows::snmp::plugin --mode=service --verbose --critical 1: --hostname=UCtest --service="Client DNS" --service="Client DHCP"
CRITICAL: Service problem 'Client DNS' |
Service pattern 'Client DNS': service list
Service 'Client DHCP' match (pattern: 'Client DHCP') [operating state = active, installed state = installed]
Service pattern 'Client DHCP': service list Client DHCP
```

If the service are UP : 

```
 perl centreon_plugins.pl --plugin os::windows::snmp::plugin --mode=service --verbose --critical 0: --hostname=172.20.36.6 --service="Client DNS"
OK: All service states are ok |
Service 'Client DNS' match (pattern: 'Client DNS') [operating state = active, installed state = installed]
Service pattern 'Client DNS': service list Client DNS
```

```
perl centreon_plugins.pl --plugin os::windows::snmp::plugin --mode=service --verbose --critical 1: --hostname=172.20.36.6 --service="Client DNS" --service="Client DHCP"
OK: All service states are ok |
Service 'Client DNS' match (pattern: 'Client DNS') [operating state = active, installed state = installed]
Service pattern 'Client DNS': service list Client DNS
Service 'Client DHCP' match (pattern: 'Client DHCP') [operating state = active, installed state = installed]
Service pattern 'Client DHCP': service list Client DHCP
```
Furthermore i can't use "--critical Numberofservice:", because it doesn't work. 
For exemple with the services "Client DNS" and "Client DHCP" running : 

```
perl centreon_plugins.pl --plugin os::windows::snmp::plugin --mode=service --verbose --critical 2: --hostname=172.20.36.6 --service="Client DNS" --service="Client DHCP"
CRITICAL: Service problem 'Client DNS' - Service problem 'Client DHCP' |
Service 'Client DNS' match (pattern: 'Client DNS') [operating state = active, installed state = installed]
Service pattern 'Client DNS': service list Client DNS
Service 'Client DHCP' match (pattern: 'Client DHCP') [operating state = active, installed state = installed]
Service pattern 'Client DHCP': service list Client DHCP
```

**Comment by Sims24** [comment]
Hi @loic60600 , 

Sorry for late answer, didn't see notification for your feedback.

--critical is evaluated for each service definition.

```
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin os::windows::snmp::plugin --mode service --hostname mywindows --service 'Client DNS' --service 'Miaou' --critical 1: --service 'Test' --verbose
CRITICAL: Service problem 'Miaou' - Service problem 'Test' |
Service 'Client DNS' match (pattern: 'Client DNS') [operating state = active, installed state = installed]
Service pattern 'Client DNS': service list Client DNS
Service pattern 'Miaou': service list
```

So you should always use --critical 1: if you want to warn if one of the services specified in --service option is not running. 

This should work no ?

Thanks,

**Comment by sahinguneri** [comment]
Hi  @Sims24 ; 

The problem is also same here. im using centreon Web UI, when i add "critical 1:" option the service returns always critical, when i remove "1:" it always returns ok. 

Did you resolve this? 

Centreon 2.8.1

**Comment by sahinguneri** [comment]
resolved, it has to write "Service Display Name" not service name.
