### ISSUE TITLE
Cisco FMC - new mode Tunnel status

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4167]
Cisco FMC has a Endpoint that allows to monitor the tunnel status. Attached you can find the Rest API documentation. It should be nice to have a new command to check the tunnel status and maybe a tunnel discovery.
Did you need something other?
[Tunnel Status - FMC.pdf](https://github.com/centreon/centreon-plugins/files/10479390/Tunnel.Status.-.FMC.pdf)

**Comment by garnier-quentin** [comment]
Could you provide a curl example result ?

**Comment by joschi99** [comment]
@garnier-quentin : sent the json repsonse by mail to you.
