### ISSUE TITLE
Centreon Juniper Ex - Filter Power Supply

### ISSUE THREAD

**Issue by nunomla** [centreon/centreon-plugins#4168]
It's possible to filter the Power Supply result from the plugin network::juniper::ex::plugin, Mode Hardware?

[11:38] NUNO ALVES
/usr/lib/centreon/plugins/centreon_juniper_ex_snmp.pl --plugin=network::juniper::ex::plugin --mode=hardware --hostname=x.x.x.x --snmp-version='3' --snmp-username= 'x' --authpassphrase= 'zz' --authprotocol= 'zz' --privpassphrase= 'xxxx' --privprotocol= 'xzz' --snmp-autoreduce --component='.*' --verbose
OK: All 123 components are ok [2/2 alarm, 102/102 frus, 19/19 operatings]. | 'temp_FPC: EX4200-48T, 8 POE @ 0/*/*'=22C;;;; 'cpu_utilization_FPC: EX4200-48T, 8 POE @ 0/*/*'=8%;;;; 'buffer_usage_FPC: EX4200-48T, 8 POE @ 0/*/*'=65%;;;; 'temp_FPC: EX4200-48T, 8 POE @ 1/*/*'=39C;;;; 'cpu_utilization_FPC: EX4200-48T, 8 POE @ 1/*/*'=6%;;;; 'buffer_usage_FPC: EX4200-48T, 8 POE @ 1/*/*'=53%;;;; 'temp_Routing Engine 0'=22C;;;; 'cpu_utilization_Routing Engine 0'=8%;;;; 'buffer_usage_Routing Engine 0'=65%;;;; 'temp_Routing Engine 1'=39C;;;; 'cpu_utilization_Routing Engine 1'=6%;;;; 'buffer_usage_Routing Engine 1'=53%;;;; 'count_alarm'=2;;;; 'count_fru'=102;;;; 'count_operating'=19;;;;
Checking frus
fru 'Power Supply: Power Supply 0 @ 0/0/*' state is online [instance: 2.1.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 0/1/*' state is online [instance: 2.1.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 9/0/*' state is empty [instance: 2.10.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 9/1/*' state is empty [instance: 2.10.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 1/0/*' state is online [instance: 2.2.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 1/1/*' state is online [instance: 2.2.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 2/0/*' state is empty [instance: 2.3.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 2/1/*' state is empty [instance: 2.3.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 3/0/*' state is empty [instance: 2.4.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 3/1/*' state is empty [instance: 2.4.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 4/0/*' state is empty [instance: 2.5.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 4/1/*' state is empty [instance: 2.5.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 5/0/*' state is empty [instance: 2.6.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 5/1/*' state is empty [instance: 2.6.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 6/0/*' state is empty [instance: 2.7.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 6/1/*' state is empty [instance: 2.7.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 7/0/*' state is empty [instance: 2.8.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 7/1/*' state is empty [instance: 2.8.2.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 0 @ 8/0/*' state is empty [instance: 2.9.1.0, type: powerEntryModule, offline reason: none]
fru 'Power Supply: Power Supply 1 @ 8/1/*' state is empty [instance: 2.9.2.0, type: powerEntryModule, offline reason: none]

**Comment by nunomla** [comment]
I want to show only the Power Suplly

**Comment by garnier-quentin** [comment]
You can try following options: ```--add-name-instance --filter=fru,Power Supply```

**Comment by nunomla** [comment]
It works, Thanks

**Comment by garnier-quentin** [comment]
thanks! i close it
