### ISSUE TITLE
Storage::hp::storeonce::4::restapi::plugin requires method 'new' via "Net::Curl::Easy" package. Installing the package from CPAN does not provide the method and there don't appear to be any available packages that match this in the main CentOS repos

### ISSUE THREAD

**Issue by aaron-asdf** [centreon/centreon-plugins#4170]
Storage::hp::storeonce::4::restapi::plugin requires method 'new' via "Net::Curl::Easy" package. Installing the package from CPAN does not provide the method and there don't appear to be any available packages that match this in the main CentOS repos

Hi all,

Here is a sample cli command to show what I am doing:

`perl centreon_plugins.pl --plugin=storage::hp::storeonce::4::restapi::plugin --mode appliances --hostname 10.1.1.1 --api-username myuser --api-password 'mypassword'`

I am receiving the following error:

`UNKNOWN: Can't locate object method "new" via package "Net::Curl::Easy" (perhaps you forgot to load "Net::Curl::Easy"?) at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/backend/http/curl.pm line 319.`

I am on Alma 8. I attempted to install the perl Net::Curl::Easy package with:

`cpan Net::Curl::Easy`

and it did successfully install. However, I continue to get the same error and do not see a 'new' method in the package when I take a look at it.

Any ideas? Thanks!

**Comment by garnier-quentin** [comment]
Please use that package: https://yum.centreon.com/standard/22.10/el8/stable/x86_64/RPMS/perl-Net-Curl-0.44-1.el8.x86_64.rpm
