### ISSUE TITLE
 [hardware::server::dell::vxm::restapi::plugin] Vxrail plugin pack (REST api V2)

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#4171]
Hi,
Can you add vxrail manager rest v2 api support ?
This is the continuation of ticket [3580](https://github.com/centreon/centreon-plugins/issues/3580).
the API documentation is there : https://developer.dell.com/apis/5538/versions/7.0.400/docs/Introduction.md
I send you the json of the endpoints /rest/vxm/v2/hosts and chassis.

Best regards,

**Comment by garnier-quentin** [comment]
API rest v2 seems quite the same. So i can add an --api-version option. It's ok for you ?

**Comment by gagzou** [comment]
It's ok for me, the best would be to make the v2 api default and the v1 optional because the v1 is deprecated.

**Comment by garnier-quentin** [comment]
The best is done ;) https://github.com/centreon/centreon-plugins/pull/4177
