### ISSUE TITLE
database::postgres::plugin --mode=hitratio

### ISSUE THREAD

**Issue by MickaelTheCat** [centreon/centreon-plugins#4172]
Hello

There is a problem when values dont change between executions

First exec

           'smalarms_blks_read' => 34061627,
           'smalarms_blks_hit' => '48976037767',

Next exec

           'smalarms_blks_read' => 34061627,
           'smalarms_blks_hit' => '48977347304',

Hit ratio is 3,7% instead of 100% ("Database 'smalarms' hitratio at 3.70%")

Maybe problem is here with <= instead of <

        next if (!defined($old_blks_hit) || !defined($old_blks_read));
          $old_blks_hit = 0 if ($$row[0] <= $old_blks_hit);
          $old_blks_read = 0 if ($$row[1] <= $old_blks_read);

Regards

**Comment by garnier-quentin** [comment]
Thanks! https://github.com/centreon/centreon-plugins/pull/4176
