### ISSUE TITLE
[cloud::azure::management::costs::mode::costsexplorer] Error 400 / 411 Bad Request: Problem on Content-Length

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#4173]
Hello !
Thanks for this very usefull plugin.

We are facing a bug on cloud::azure::management::costs::mode::costsexplorer

When using default **curl** backend we are getting: 

`./centreon_plugins.pl --plugin=cloud::azure::management::costs::plugin --mode=costs-explorer --custommode='api' --tags='' --subscription='' --tenant='' --client-id='' --client-secret=''  --lookup-days='30' --verbose --debug`

`<HTML><HEAD><TITLE>Bad Request</TITLE><META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD><BODY><h2>Bad Request - Invalid Content Length</h2><hr><p>HTTP Error 400. There is an invalid content length or chunk length in the request.</p></BODY></HTML>`

When trying with backend **lwp** getting similar answer from Azure: 
`======> response done
HTTP/1.1 411 Length Required
Connection: close`

The problem seems to be located on POST request beeing sent with **Content-Length: -1** instead of the true content-lenght size

This modification make it working but not sure if it's clean: 

On _azure/custom/api.pm_, function "**azure_get_subscription_cost_management**"
We removed the _Content-Type: application/json_ 
`#$self->{http}->add_header(key => 'Content-Type', value => 'application/json');`

And adding this header on "**request_api**" function of the same file

Before the modification: 
`=> Send header: POST /tenantID/oauth2/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type:application/json
Accept:application/json
Content-Length: -1
Expect: 100-continue`

After this modification:
`=> Send header: POST /tenantID/oauth2/token HTTP/1.1
Host: login.microsoftonline.com
Accept:application/json
Content-Type: application/x-www-form-urlencoded
Content-Length: 171`

**Comment by garnier-quentin** [comment]
Thanks. It was close ;) https://github.com/centreon/centreon-plugins/pull/4175

It should be ok now

**Comment by fixlair** [comment]
Thanks a lot ! it works :)

have a nice day !
