### ISSUE TITLE
TCP check from host to host

### ISSUE THREAD

**Issue by LaurentV9** [centreon/centreon-plugins#4178]
Hello Guys,

I have a quick question.

I have multiple hosts and I need to check if, from each of thes hosts, I can join a specific host on a specific port.

Example:

I have to check if server AAA can access to server BBB on port 8531.

Is it possible? If yes, how? :-)

Regards,

Laurent

**Comment by garnier-quentin** [comment]
Install centreon-plugins on your server AAA and uses the plugin protocl tcp to check the server BBB
