### ISSUE TITLE
New plugin to check WD NAS

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4180]
It should be nice to have a plugin to monitor WD NAS.
Attached you will find:
- SNMP MIB file
- SNMP walk

[MYCLOUDPR4100-MIB.txt](https://github.com/centreon/centreon-plugins/files/10503168/MYCLOUDPR4100-MIB.txt)
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/10503211/snmpwalk.txt)

Let me know if you need other informations.

**Comment by garnier-quentin** [comment]
It seems complete. But i have found also mib for PR2100, EX2 and EX2ULTRA. I will manage all mibs.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4208

**Comment by joschi99** [comment]
Done some test, work as aspected :-)
