### ISSUE TITLE
Extreme memory not working

### ISSUE THREAD

**Issue by trentasis** [centreon/centreon-plugins#4189]
Hi

Extreme switches with VOSS seems that memory check are not working correctly

--plugin=network::nortel::standard::snmp::plugin --mode=memory
OK: Memory 'slot_1' used: 0.81 % | 'slot_1#memory.usage.bytes'=835901440B;;;0;1027514368 'slot_1#memory.free.bytes'=191612928B;;;0;1027514368 'slot_1#memory.usage.percentage'=0.81%;;;0;100

Reproduced with 5320, and also detected that on 5520 no works, cpu, memory, hardware.

Attached mibs of vsp7400, 5520 and 5320
[mibs_7400_5520_5320.zip](https://github.com/centreon/centreon-plugins/files/10529369/mibs_7400_5520_5320.zip)

I can send output snmpwalk by email if needed of both switchs

It seems that and old bug was reported but in latest versions is not solved maybe?

thanks

**Comment by garnier-quentin** [comment]
Yes i need the snmpwalk please.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4202

**Comment by trentasis** [comment]
Great! Now it works perfects memory check on all extreme models
Thanks!
