### ISSUE TITLE
New plugin to monitor hops to a IP address using traceroute

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4191]
It should be nice to have a plugin thats allow to monitor and visualize the hops using traceroute to a IP address.

**Comment by garnier-quentin** [comment]
What do you want as output exactly ?

**Comment by joschi99** [comment]
Hi @garnier-quentin,
did you have some news on this request?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request had been already posted in TheWatch idea [here](https://thewatch.centreon.com/ideas/traceroute-plugin-3069) so let me close it.
Thank you for your understanding.
