### ISSUE TITLE
database::postgres::plugin --mode=query-time

### ISSUE THREAD

**Issue by MickaelTheCat** [centreon/centreon-plugins#4194]
Hello

exclude-user's option does not work and error line 11918 :

/usr/lib/centreon/plugins/centreon_postgresql.pl --plugin=database::postgres::plugin --mode=query-time --host=192.168.111.1 --username='cheops' --password='***' --port='5432' --database='AXIBASE' --warning='3' --critical='6' --exclude='^(?!(postgres|template1|template0))' --exclude-user='postgres'
Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/centreon_postgresql.pl line 11918.
CRITICAL: 1 request exceed critical threshold on database 'AXIBASE' | 'CONNECT#database.longqueries.count'=0;;;0; 'AXIBASE#database.longqueries.count'=1;;;0;

line 11918 :
              $self->{output}->output_add(
                  long_msg => sprintf(
                      "Request from client '%s' too long (%d sec) on database '%s': %s",
                      $row->{client_addr}, $row->{seconds}, $row->{datname}, $row->{current_query}
                  )
              );

Regards

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4197/files
