### ISSUE TITLE
[network::nortel::standard::snmp::plugin] --mode=hardware --component=temperature the right OID but no result

### ISSUE THREAD

**Issue by Hatemtn70** [centreon/centreon-plugins#4196]
Hi,
I can not have the temperature with the command below

centreon_plugins.pl --plugin=network::nortel::standard::snmp::plugin --mode=hardware --hostname=XXX --snmp-version=3 --snmp-username=xxxx --authprotocol=XXX --authpassphrase=xxxx --privprotocol=XXX --privpassphrase=xxxx --component=temperature

OK: All 0 components are ok [].
I see on file centreon-plugins/src/network/nortel/standard/snmp/mode/components/temperature.pm I find the right VOSS OID :
- .1.3.6.1.4.1.2272.1.101.1.1.2.1.2         description
- .1.3.6.1.4.1.2272.1.101.1.1.2.1.3         value
- .1.3.6.1.4.1.2272.1.101.1.1.2.1          rcVossSystemTemperatureEntry 

with snmpwalk, for the first OID the result is : 
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.2.1 = STRING: "CPU"
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.2.2 = STRING: "MAC"
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.2.3 = STRING: "MAC2"
second :
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.3.1 = Gauge32: 30
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.3.2 = Gauge32: 42
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.3.3 = Gauge32: 48
third :
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.2.1 = STRING: "CPU"
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.2.2 = STRING: "MAC"
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.2.3 = STRING: "MAC2"
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.3.1 = Gauge32: 30
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.3.2 = Gauge32: 42
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.3.3 = Gauge32: 48
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.4.1 = INTEGER: 45     # Warning Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.4.2 = INTEGER: 45     # Warning Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.4.3 = INTEGER: 45     # Warning Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.5.1 = INTEGER: 65    # Critical Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.5.2 = INTEGER: 65    # Critical Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.5.3 = INTEGER: 65    # Critical Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.6.1 = INTEGER: 1      # Temperature Status : normal (1), warning (2), Critical (3)
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.6.2 = INTEGER: 1      # Temperature Status : normal (1), warning (2), Critical (3)
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.6.3 = INTEGER: 2       # Temperature Status : normal (1), warning (2), Critical (3)

Can you help me plz ?

Thanks for your help

**Comment by garnier-quentin** [comment]
Do you have the last version ? Because it's working for me. It was added in Mars 2022: https://github.com/centreon/centreon-plugins/commit/c2cd9c71f4b89e39122d488e1809d598da526314

**Comment by Hatemtn70** [comment]
yes, I have the last one : git log : 

commit cb35907d1fb6ae61dc0c3f4652b178c8adb65e36
    (plugin) network::nortel::standard::snmp - incorrect temperature (#3590)
commit d571da2215357582151910135900e69d35ad3c2f
commit bc9abd0e5b11f89bb4be8a8335901e3db170a4f5

**Comment by Hatemtn70** [comment]
and when I add --verbose : 

Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/centreon-plugins/src/network/nortel/standard/snmp/mode/components/fan.pm line 66.
Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/centreon-plugins/src/network/nortel/standard/snmp/mode/components/fan.pm line 66.
Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/centreon-plugins/src/network/nortel/standard/snmp/mode/components/fan.pm line 66.
Use of uninitialized value in sprintf at /usr/lib/centreon/plugins/centreon-plugins/src/network/nortel/standard/snmp/mode/components/fan.pm line 66.
OK: All 8 components are ok [2/2 cards, 4/4 fans, 2/2 psus]. | '1#hardware.fan.temperature.celsius'=C;;;; '2#hardware.fan.temperature.celsius'=C;;;; '3#hardware.fan.temperature.celsius'=C;;;; '4#hardware.fan.temperature.celsius'=C;;;; 'hardware.card.count'=2;;;; 'hardware.fan.count'=4;;;; 'hardware.psu.count'=2;;;;
Checking cards
card '15JP152C1054' status is 'up' [instance: 1]
card '15JP152C1054' status is 'up' [instance: 2]
Checking entities
Checking fans
fan '1' status is 'up' [instance: 1, value: ]
fan '2' status is 'up' [instance: 2, value: ]
fan '3' status is 'up' [instance: 3, value: ]
fan '4' status is 'up' [instance: 4, value: ]
Checking led
Checking power supplies
power supply '1' status is 'up' [instance: 1]
power supply '2' status is 'up' [instance: 2]
Checking temperatures

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk:
```
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1 > nortel.snmpwalk
```

**Comment by Hatemtn70** [comment]
Hello,

the problem is resolved now, I committed all **sub check_fan_rc** in **fan.pm** and everything is working : 

UNKNOWN: Led 'PWR' status is 'unknown' | 'CPU#hardware.temperature.celsius'=30C;;;; 'MAC#hardware.temperature.celsius'=42C;;;; 'MAC2#hardware.temperature.celsius'=49C;;;; 'hardware.card.count'=2;;;; 'hardware.fan.count'=6;;;; 'hardware.led.count'=5;;;; 'hardware.psu.count'=2;;;; 'hardware.temperature.count'=3;;;;
Checking cards
card 'XXXXXXXXX' status is 'up' [instance: 1]
card 'XXXXXXXXX' status is 'up' [instance: 2]
Checking entities
Checking fans
Tray 1 Fan 1 status is 'up' [instance: 1.1]
Tray 1 Fan 2 status is 'up' [instance: 1.2]
Tray 2 Fan 1 status is 'up' [instance: 2.1]
Tray 2 Fan 2 status is 'up' [instance: 2.2]
Tray 3 Fan 1 status is 'up' [instance: 3.1]
Tray 3 Fan 2 status is 'up' [instance: 3.2]
Checking led
led 'PWR' status is 'greenSteady' [instance: 1.1]
led 'Status' status is 'greenSteady' [instance: 1.2]
led 'Rps' status is 'greenSteady' [instance: 1.3]
led 'Fan' status is 'greenSteady' [instance: 1.4]
led 'PWR' status is 'unknown' [instance: 2.1]
Checking power supplies
power supply '1' status is 'up' [instance: 1]
power supply '2' status is 'up' [instance: 2]
Checking temperatures
temperature 'CPU' is 30 degree centigrade [instance: 1]
temperature 'MAC' is 42 degree centigrade [instance: 2]
temperature 'MAC2' is 49 degree centigrade [instance: 3]

but there's no mention of "warning" or "critical" in temperature values.

**Comment by garnier-quentin** [comment]
Yes there is no status. You need to set a threshold: 
```
--warning='temperature,.*,50' --critical='temperature,.*,55'
```

**Comment by Hatemtn70** [comment]
thx, mine are 45 and 65 : 

SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.4.1 = INTEGER: 45 # Warning Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.4.2 = INTEGER: 45 # Warning Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.4.3 = INTEGER: 45 # Warning Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.5.1 = INTEGER: 65 # Critical Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.5.2 = INTEGER: 65 # Critical Thershold
SNMPv2-SMI::enterprises.2272.1.101.1.1.2.1.5.3 = INTEGER: 65 # Critical Thershold
