### ISSUE TITLE
[hardware::server::hp::ilo::xmlapi::plugin] --mode=hardware: logical network adapter or FC HBA is not monitored

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4201]
This plugin will actually not monitor logical network adapters but only physical network adapters. Could you extend the mode?
![image](https://user-images.githubusercontent.com/6400595/216610901-8004f185-3700-4045-9e0a-8155b48e0ac1.png)

It could be usefull also for [hardware::server::hp::ilo::restapi::plugin], but I have not checked if its missing also there

**Comment by garnier-quentin** [comment]
Could you provide the output with --debug ?

**Comment by joschi99** [comment]
I have here a debug file of a ILO with a FC adapter, where we have the same problem:
[ilo.txt](https://github.com/centreon/centreon-plugins/files/10581504/ilo.txt)

![image](https://user-images.githubusercontent.com/6400595/216674210-47faded8-a7fa-403d-b926-5d6abc0ae989.png)

As you can see the nic "Adapter 3" is under the <NIC_INFORMATION> section, but the FC HBA is only present into
```
          <INDEX_14>
               <FIRMWARE_NAME VALUE = "HP StorageWorks 82Q 8Gb PCI-e Dual Port FC HBA"/>
               <FIRMWARE_VERSION VALUE = "8.01.02"/>
          </INDEX_14>
     </FIRMWARE_INFORMATION>
```
No status for the HBA, no status for WWNN ecc. into the debug

**Comment by joschi99** [comment]
Maybe the API will not return this informations: https://support.hpe.com/hpesc/public/docDisplay?docId=sf000087648en_us&docLocale=en_US

Have done a SNMPwalk and there all informations seems available:
[ilo-snmp.txt](https://github.com/centreon/centreon-plugins/files/10581657/ilo-snmp.txt)

Maybe using SNMP we have a more complete check on ILO?

**Comment by garnier-quentin** [comment]
Do you have the mib files for ilo snmp ?

**Comment by joschi99** [comment]
You should find it into this archive
[upd11.80mib.tar.gz](https://github.com/centreon/centreon-plugins/files/10663885/upd11.80mib.tar.gz)

**Comment by garnier-quentin** [comment]
You can use the following plugin (it works): hardware::server::hp::proliant::snmp::plugin
