### ISSUE TITLE
[os:windows:local] - new modes for list-services and list-processes

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4207]
It should be nice to have a some new discovery mode using Windows agent like
- list-services
- list-processes

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
