### ISSUE TITLE
apps::jenkins::mode::jobstate 

### ISSUE THREAD

**Issue by Spleeff** [centreon/centreon-plugins#4218]
Hello Quentin,

Thanks for this change.
Unfortunately, I’m not able to use this plugin correctly.

Here is my check :

centreon_plugins.pl --plugin=apps::jenkins::plugin --mode=jobs --hostname="MYSERVER" --proto="https" --insecure  --credentials --basic --username="admin" --password="XXXXXXXXXXX" --critical-score='0' --filter-job-name='^(?!DISABLED_).*$'

How to adapt it to show only failed builds ?

Thank you

_Originally posted by @Spleeff in https://github.com/centreon/centreon-plugins/issues/4213#issuecomment-1425996878_

-- Sorry, I didn't know whether to open a new issue or not.

**Comment by garnier-quentin** [comment]
Could you provide the plugin output ?

**Comment by Spleeff** [comment]
Sure, here is : 

centreon_plugins.pl --plugin=apps::jenkins::plugin --mode=jobs --hostname="MYSERVER" --proto="https" --insecure --credentials --basic --username="admin" --password="XXXXXXXXXXX" --critical-score='0' --filter-job-name='^(?!DISABLED_).*$'

**CRITICAL: Job 'ActiveDirectory_Audit' score: 100.00 % - Job 'Copy_Aspen_VBS' score: 100.00 % - Job 'Copy_FCS' score: 100.00 % - Job 'Copy_Rapport_SEL' score: 100.00 % - Job 'DSC_Server_Compliance_and_CyberSec' score: 100.00 % - Job 'DSC_Service_Running' score: 100.00 % - Job 'Deleted_Scan' score: 100.00 % - Job 'DeployCiscoConfig' score: 100.00 % - Job 'Disable_Inactive_Users' score: 100.00 % - Job 'Enable_WakeOnLAN' score: 100.00 % - Job 'FSRM-ANTICRYPTO' score: 100.00 % - Job 'Install_WindowsUpdate_From_SCCM' score: 100.00 % - Job 'KPI_WOM' score: 100.00 % - Job 'LogoffRemoteSession_RDS-Server' score: 100.00 % - Job 'Move_UserDisabled' score: 100.00 % - Job 'Password-Expiration-Notifications' score: 100.00 % - Job 'Remove_Labware_Shortcut' score: 100.00 % - Job 'Remove_SnapshotVM' score: 100.00 % - Job 'Renew_WiFi_Password' score: 100.00 % - Job 'SQL_Asgard' score: 100.00 % - Job 'Send_Mail_Liste5_Before_Reboot' score: 100.00 % - Job 'Task_Data_GTF1' score: 100.00 % - Job 'Task_Data_GTF2' score: 100.00 % - Job 'Task_LBZ' score: 100.00 % - Job 'Task_PSIS' score: 100.00 % - Job 'Task_PSIS_ForeCast' score: 100.00 % - Job 'Tiers1_Update_And_Reboot' score: 100.00 % - Job 'Tiers2_Update_And_Reboot' score: 80.00 % - Job 'Tiers2b' score: 80.00 % - Job 'Tiers3_Update_And_Reboot' score: 100.00 % - Job 'Tiers3b_Restart_Service_Scheduler' score: 100.00 % - Job 'Tiers4_Update_And_Reboot' score: 80.00 % - Job 'TC_Copy_Files_To_Archive' score: 100.00 % - Job 'TC_Delete_Archive' score: 100.00 % - Job 'USB_BlackList' score: 100.00 % - Job 'Unused_Port_Shutdown' score: 100.00 % - Job 'WakeUp_Since60Days' score: 100.00 % - Job 'QU_Send_Files_SFTP' score: 100.00 % - Job 'z_Cleanup_DHCP' score: 100.00 % - Job 'z_Delete_Legacy_Software_XXX' score: 66.00 % - Job 'z_Disable_Naemon_Notifications' score: 100.00 % - Job 'z_FDS-Copy_G_to_SLV-Sharepoint' score: 100.00 % - Job 'z_Install_ESU_Windows7' score: 100.00 % - Job 'z_Monitoring_NSClient' score: 66.00 % - Job 'z_RemoveOffice2010' score: 100.00 % - Job 'z_Remove_Skype' score: 100.00 % - Job 'z_Replace_LabWare' score: 100.00 % - Job 'z_Specific_Workstations_EEXT' score: 100.00 % - Job 'z_Task_ScanAT' score: 100.00 % | 'ActiveDirectory_Audit#job.score.percentage'=100.00%;;0:0;0;100 'ActiveDirectory_Audit#job.violations.count'=0;;;0; 'Copy_Aspen_VBS#job.score.percentage'=100.00%;;0:0;0;100 'Copy_Aspen_VBS#job.violations.count'=0;;;0; 'Copy_FCS#job.score.percentage'=100.00%;;0:0;0;100 'Copy_FCS#job.violations.count'=0;;;0; 'Copy_Rapport_SEL#job.score.percentage'=100.00%;;0:0;0;100 'Copy_Rapport_SEL#job.violations.count'=0;;;0; 'DSC_Server_Compliance_and_CyberSec#job.score.percentage'=100.00%;;0:0;0;100 'DSC_Server_Compliance_and_CyberSec#job.violations.count'=0;;;0; 'DSC_Service_Running#job.score.percentage'=100.00%;;0:0;0;100 'DSC_Service_Running#job.violations.count'=0;;;0; 'Deleted_Scan#job.score.percentage'=100.00%;;0:0;0;100 'Deleted_Scan#job.violations.count'=0;;;0; 'DeployCiscoConfig#job.score.percentage'=100.00%;;0:0;0;100 'DeployCiscoConfig#job.violations.count'=0;;;0; 'Disable_Inactive_Users#job.score.percentage'=100.00%;;0:0;0;100 'Disable_Inactive_Users#job.violations.count'=0;;;0; 'Enable_WakeOnLAN#job.score.percentage'=100.00%;;0:0;0;100 'Enable_WakeOnLAN#job.violations.count'=0;;;0; 'FSRM-ANTICRYPTO#job.score.percentage'=100.00%;;0:0;0;100 'FSRM-ANTICRYPTO#job.violations.count'=0;;;0; 'Install_WindowsUpdate_From_SCCM#job.score.percentage'=100.00%;;0:0;0;100 'Install_WindowsUpdate_From_SCCM#job.violations.count'=0;;;0; 'KPI_WOM#job.score.percentage'=100.00%;;0:0;0;100 'KPI_WOM#job.violations.count'=0;;;0; 'LogoffRemoteSession_RDS-Server#job.score.percentage'=100.00%;;0:0;0;100 'LogoffRemoteSession_RDS-Server#job.violations.count'=0;;;0; 'Move_UserDisabled#job.score.percentage'=100.00%;;0:0;0;100 'Move_UserDisabled#job.violations.count'=0;;;0; 'Password-Expiration-Notifications#job.score.percentage'=100.00%;;0:0;0;100 'Password-Expiration-Notifications#job.violations.count'=0;;;0; 'Remove_Labware_Shortcut#job.score.percentage'=100.00%;;0:0;0;100 'Remove_Labware_Shortcut#job.violations.count'=0;;;0; 'Remove_SnapshotVM#job.score.percentage'=100.00%;;0:0;0;100 'Remove_SnapshotVM#job.violations.count'=0;;;0; 'Renew_WiFi_Password#job.score.percentage'=100.00%;;0:0;0;100 'Renew_WiFi_Password#job.violations.count'=0;;;0; 'SQL_Asgard#job.score.percentage'=100.00%;;0:0;0;100 'SQL_Asgard#job.violations.count'=0;;;0; 'Send_Mail_Liste5_Before_Reboot#job.score.percentage'=100.00%;;0:0;0;100 'Send_Mail_Liste5_Before_Reboot#job.violations.count'=0;;;0; 'SYM_Backup#job.score.percentage'=0.00%;;0:0;0;100 'SYM_Backup#job.violations.count'=0;;;0; 'Task_Data_GTF1#job.score.percentage'=100.00%;;0:0;0;100 'Task_Data_GTF1#job.violations.count'=0;;;0; 'Task_Data_GTF2#job.score.percentage'=100.00%;;0:0;0;100 'Task_Data_GTF2#job.violations.count'=0;;;0; 'Task_LBZ#job.score.percentage'=100.00%;;0:0;0;100 'Task_LBZ#job.violations.count'=0;;;0; 'Task_PSIS#job.score.percentage'=100.00%;;0:0;0;100 'Task_PSIS#job.violations.count'=0;;;0; 'Task_PSIS_ForeCast#job.score.percentage'=100.00%;;0:0;0;100 'Task_PSIS_ForeCast#job.violations.count'=0;;;0; 'Tiers1_Update_And_Reboot#job.score.percentage'=100.00%;;0:0;0;100 'Tiers1_Update_And_Reboot#job.violations.count'=0;;;0; 'Tiers2_Update_And_Reboot#job.score.percentage'=80.00%;;0:0;0;100 'Tiers2_Update_And_Reboot#job.violations.count'=1;;;0; 'Tiers2b#job.score.percentage'=80.00%;;0:0;0;100 'Tiers2b#job.violations.count'=1;;;0; 'Tiers3_Update_And_Reboot#job.score.percentage'=100.00%;;0:0;0;100 'Tiers3_Update_And_Reboot#job.violations.count'=0;;;0; 'Tiers3b_Restart_Service_Scheduler#job.score.percentage'=100.00%;;0:0;0;100 'Tiers3b_Restart_Service_Scheduler#job.violations.count'=0;;;0; 'Tiers4_Update_And_Reboot#job.score.percentage'=80.00%;;0:0;0;100 'Tiers4_Update_And_Reboot#job.violations.count'=1;;;0; 'TC_Copy_Files_To_Archive#job.score.percentage'=100.00%;;0:0;0;100 'TC_Copy_Files_To_Archive#job.violations.count'=0;;;0; 'TC_Delete_Archive#job.score.percentage'=100.00%;;0:0;0;100 'TC_Delete_Archive#job.violations.count'=0;;;0; 'USB_BlackList#job.score.percentage'=100.00%;;0:0;0;100 'USB_BlackList#job.violations.count'=0;;;0; 'Unused_Port_Shutdown#job.score.percentage'=100.00%;;0:0;0;100 'Unused_Port_Shutdown#job.violations.count'=0;;;0; 'WakeUp_Since60Days#job.score.percentage'=100.00%;;0:0;0;100 'WakeUp_Since60Days#job.violations.count'=0;;;0; 'QU_Send_Files_SFTP#job.score.percentage'=100.00%;;0:0;0;100 'QU_Send_Files_SFTP#job.violations.count'=0;;;0; 'z_Cleanup_DHCP#job.score.percentage'=100.00%;;0:0;0;100 'z_Cleanup_DHCP#job.violations.count'=0;;;0; 'z_Delete_Legacy_Software_XXX#job.score.percentage'=66.00%;;0:0;0;100 'z_Delete_Legacy_Software_XXX#job.violations.count'=1;;;0; 'z_Disable_Naemon_Notifications#job.score.percentage'=100.00%;;0:0;0;100 'z_Disable_Naemon_Notifications#job.violations.count'=0;;;0; 'z_Enable_Naemon_Notifications#job.score.percentage'=0.00%;;0:0;0;100 'z_Enable_Naemon_Notifications#job.violations.count'=0;;;0; 'z_FDS-Copy_G_to_SLV-Sharepoint#job.score.percentage'=100.00%;;0:0;0;100 'z_FDS-Copy_G_to_SLV-Sharepoint#job.violations.count'=0;;;0; 'z_Install_ESU_Windows7#job.score.percentage'=100.00%;;0:0;0;100 'z_Install_ESU_Windows7#job.violations.count'=0;;;0; 'z_Monitoring_NSClient#job.score.percentage'=66.00%;;0:0;0;100 'z_Monitoring_NSClient#job.violations.count'=1;;;0; 'z_RemoveOffice2010#job.score.percentage'=100.00%;;0:0;0;100 'z_RemoveOffice2010#job.violations.count'=0;;;0; 'z_Remove_Skype#job.score.percentage'=100.00%;;0:0;0;100 'z_Remove_Skype#job.violations.count'=0;;;0; 'z_Replace_LabWare#job.score.percentage'=100.00%;;0:0;0;100 'z_Replace_LabWare#job.violations.count'=0;;;0; 'z_Specific_Workstations_EEXT#job.score.percentage'=100.00%;;0:0;0;100 'z_Specific_Workstations_EEXT#job.violations.count'=0;;;0; 'z_Task_ScanAT#job.score.percentage'=100.00%;;0:0;0;100 'z_Task_ScanAT#job.violations.count'=0;;;0; 'z_Upgrade_Navisworks#job.score.percentage'=0.00%;;0:0;0;100 'z_Upgrade_Navisworks#job.violations.count'=0;;;0;
**

**Comment by Spleeff** [comment]
In this case, I modify to 80 for example, for my job ActiveDirectory_Audit always appears in the output ?

**Comment by garnier-quentin** [comment]
You can use --verbose option

**Comment by Spleeff** [comment]
centreon_plugins.pl --plugin=apps::jenkins::plugin --mode=jobs --hostname="MYSERVER" --proto="https" --insecure --credentials --basic --username="admin" --password="XXXXXXXXXXX" --critical-score='0' --filter-job-name='^(?!DISABLED_).*$'
CRITICAL: Job 'ActiveDirectory_Audit' score: 100.00 % - Job 'Copy_Aspen_VBS' score: 100.00 % - Job 'Copy_FCS' score: 100.00 % - Job 'Copy_Rapport' score: 100.00 % - Job 'DSC_Server_Compliance_and_CyberSec' score: 100.00 % - Job 'DSC_Service_Running' score: 100.00 % - Job 'Deleted_Scan' score: 100.00 % - Job 'DeployCiscoConfig' score: 100.00 % - Job 'Disable_Inactive_Users' score: 100.00 % - Job 'Enable_WakeOnLAN' score: 100.00 % - Job 'FSRM-ANTICRYPTO' score: 100.00 % - Job 'Install_WindowsUpdate_From_SCCM' score: 100.00 % - Job 'KPI_' score: 100.00 % - Job 'LogoffRemoteSession_RDS-Server' score: 100.00 % - Job 'Move_UserDisabled' score: 100.00 % - Job 'Password-Expiration-Notifications' score: 100.00 % - Job 'Remove_Labware_Shortcut' score: 100.00 % - Job 'Remove_SnapshotVM' score: 100.00 % - Job 'Renew_WiFi_Password' score: 100.00 % - Job 'SQL_Asgard' score: 100.00 % - Job 'Send_Mail_Liste5_Before_Reboot' score: 100.00 % - Job 'Task_Data_GTF1' score: 100.00 % - Job 'Task_Data_GTF2' score: 100.00 % - Job 'Task_LBZ' score: 100.00 % - Job 'Task_PSIS' score: 100.00 % - Job 'Task_PSIS_ForeCast' score: 100.00 % - Job 'Tiers1_Update_And_Reboot' score: 100.00 % - Job 'Tiers3_Update_And_Reboot' score: 100.00 % - Job 'Tiers3b_Restart_Service_Scheduler' score: 100.00 % - Job 'TotalChrom_Copy_Files_To_Archive' score: 100.00 % - Job 'TotalChrom_Delete_Archive' score: 100.00 % - Job 'USB_BlackList' score: 100.00 % - Job 'Unused_Port_Shutdown' score: 100.00 % - Job 'WakeUp_Since60Days' score: 100.00 % - Job 'quarksUp_Send_Files_SFTP' score: 100.00 % - Job 'z_Cleanup_DHCP' score: 100.00 % - Job 'z_Disable_Naemon_Notifications' score: 100.00 % - Job 'z_FDS-Copy_G_to_SLV-Sharepoint' score: 100.00 % - Job 'z_Install_ESU_Windows7' score: 100.00 % - Job 'z_RemoveOffice2010' score: 100.00 % - Job 'z_Remove_Skype' score: 100.00 % - Job 'z_Replace_LabWare' score: 100.00 % - Job 'z_Specific_Workstations_EEXT' score: 100.00 % - Job 'z_Task_ScanAT' score: 100.00 % | 'ActiveDirectory_Audit#job.score.percentage'=100.00%;;0:80;0;100 'ActiveDirectory_Audit#job.violations.count'=0;;;0; 'Copy_Aspen_VBS#job.score.percentage'=100.00%;;0:80;0;100 'Copy_Aspen_VBS#job.violations.count'=0;;;0; 'Copy_FCS#job.score.percentage'=100.00%;;0:80;0;100 'Copy_FCS#job.violations.count'=0;;;0; 'Copy_Rapport#job.score.percentage'=100.00%;;0:80;0;100 'Copy_Rapport#job.violations.count'=0;;;0; 'DSC_Server_Compliance_and_CyberSec#job.score.percentage'=100.00%;;0:80;0;100 'DSC_Server_Compliance_and_CyberSec#job.violations.count'=0;;;0; 'DSC_Service_Running#job.score.percentage'=100.00%;;0:80;0;100 'DSC_Service_Running#job.violations.count'=0;;;0; 'Deleted_Scan#job.score.percentage'=100.00%;;0:80;0;100 'Deleted_Scan#job.violations.count'=0;;;0; 'DeployCiscoConfig#job.score.percentage'=100.00%;;0:80;0;100 'DeployCiscoConfig#job.violations.count'=0;;;0; 'Disable_Inactive_Users#job.score.percentage'=100.00%;;0:80;0;100 'Disable_Inactive_Users#job.violations.count'=0;;;0; 'Enable_WakeOnLAN#job.score.percentage'=100.00%;;0:80;0;100 'Enable_WakeOnLAN#job.violations.count'=0;;;0; 'FSRM-ANTICRYPTO#job.score.percentage'=100.00%;;0:80;0;100 'FSRM-ANTICRYPTO#job.violations.count'=0;;;0; 'Install_WindowsUpdate_From_SCCM#job.score.percentage'=100.00%;;0:80;0;100 'Install_WindowsUpdate_From_SCCM#job.violations.count'=0;;;0; 'KPI_#job.score.percentage'=100.00%;;0:80;0;100 'KPI_#job.violations.count'=0;;;0; 'LogoffRemoteSession_RDS-Server#job.score.percentage'=100.00%;;0:80;0;100 'LogoffRemoteSession_RDS-Server#job.violations.count'=0;;;0; 'Move_UserDisabled#job.score.percentage'=100.00%;;0:80;0;100 'Move_UserDisabled#job.violations.count'=0;;;0; 'Password-Expiration-Notifications#job.score.percentage'=100.00%;;0:80;0;100 'Password-Expiration-Notifications#job.violations.count'=0;;;0; 'Remove_Labware_Shortcut#job.score.percentage'=100.00%;;0:80;0;100 'Remove_Labware_Shortcut#job.violations.count'=0;;;0; 'Remove_SnapshotVM#job.score.percentage'=100.00%;;0:80;0;100 'Remove_SnapshotVM#job.violations.count'=0;;;0; 'Renew_WiFi_Password#job.score.percentage'=100.00%;;0:80;0;100 'Renew_WiFi_Password#job.violations.count'=0;;;0; 'SQL_Asgard#job.score.percentage'=100.00%;;0:80;0;100 'SQL_Asgard#job.violations.count'=0;;;0; 'Send_Mail_Liste5_Before_Reboot#job.score.percentage'=100.00%;;0:80;0;100 'Send_Mail_Liste5_Before_Reboot#job.violations.count'=0;;;0; 'SYM_Backup#job.score.percentage'=0.00%;;0:80;0;100 'SYM_Backup#job.violations.count'=0;;;0; 'Task_Data_GTF1#job.score.percentage'=100.00%;;0:80;0;100 'Task_Data_GTF1#job.violations.count'=0;;;0; 'Task_Data_GTF2#job.score.percentage'=100.00%;;0:80;0;100 'Task_Data_GTF2#job.violations.count'=0;;;0; 'Task_LBZ#job.score.percentage'=100.00%;;0:80;0;100 'Task_LBZ#job.violations.count'=0;;;0; 'Task_PSIS#job.score.percentage'=100.00%;;0:80;0;100 'Task_PSIS#job.violations.count'=0;;;0; 'Task_PSIS_ForeCast#job.score.percentage'=100.00%;;0:80;0;100 'Task_PSIS_ForeCast#job.violations.count'=0;;;0; 'Tiers1_Update_And_Reboot#job.score.percentage'=100.00%;;0:80;0;100 'Tiers1_Update_And_Reboot#job.violations.count'=0;;;0; 'Tiers2_Update_And_Reboot#job.score.percentage'=80.00%;;0:80;0;100 'Tiers2_Update_And_Reboot#job.violations.count'=1;;;0; 'Tiers2b#job.score.percentage'=80.00%;;0:80;0;100 'Tiers2b#job.violations.count'=1;;;0; 'Tiers3_Update_And_Reboot#job.score.percentage'=100.00%;;0:80;0;100 'Tiers3_Update_And_Reboot#job.violations.count'=0;;;0; 'Tiers3b_Restart_Service_Scheduler#job.score.percentage'=100.00%;;0:80;0;100 'Tiers3b_Restart_Service_Scheduler#job.violations.count'=0;;;0; 'Tiers4_Update_And_Reboot#job.score.percentage'=80.00%;;0:80;0;100 'Tiers4_Update_And_Reboot#job.violations.count'=1;;;0; 'TotalChrom_Copy_Files_To_Archive#job.score.percentage'=100.00%;;0:80;0;100 'TotalChrom_Copy_Files_To_Archive#job.violations.count'=0;;;0; 'TotalChrom_Delete_Archive#job.score.percentage'=100.00%;;0:80;0;100 'TotalChrom_Delete_Archive#job.violations.count'=0;;;0; 'USB_BlackList#job.score.percentage'=100.00%;;0:80;0;100 'USB_BlackList#job.violations.count'=0;;;0; 'Unused_Port_Shutdown#job.score.percentage'=100.00%;;0:80;0;100 'Unused_Port_Shutdown#job.violations.count'=0;;;0; 'WakeUp_Since60Days#job.score.percentage'=100.00%;;0:80;0;100 'WakeUp_Since60Days#job.violations.count'=0;;;0; 'quarksUp_Send_Files_SFTP#job.score.percentage'=100.00%;;0:80;0;100 'quarksUp_Send_Files_SFTP#job.violations.count'=0;;;0; 'z_Cleanup_DHCP#job.score.percentage'=100.00%;;0:80;0;100 'z_Cleanup_DHCP#job.violations.count'=0;;;0; 'z_Delete_Legacy_Software_XXX#job.score.percentage'=66.00%;;0:80;0;100 'z_Delete_Legacy_Software_XXX#job.violations.count'=1;;;0; 'z_Disable_Naemon_Notifications#job.score.percentage'=100.00%;;0:80;0;100 'z_Disable_Naemon_Notifications#job.violations.count'=0;;;0; 'z_Enable_Naemon_Notifications#job.score.percentage'=0.00%;;0:80;0;100 'z_Enable_Naemon_Notifications#job.violations.count'=0;;;0; 'z_FDS-Copy_G_to_SLV-Sharepoint#job.score.percentage'=100.00%;;0:80;0;100 'z_FDS-Copy_G_to_SLV-Sharepoint#job.violations.count'=0;;;0; 'z_Install_ESU_Windows7#job.score.percentage'=100.00%;;0:80;0;100 'z_Install_ESU_Windows7#job.violations.count'=0;;;0; 'z_Monitoring_NSClient#job.score.percentage'=66.00%;;0:80;0;100 'z_Monitoring_NSClient#job.violations.count'=1;;;0; 'z_RemoveOffice2010#job.score.percentage'=100.00%;;0:80;0;100 'z_RemoveOffice2010#job.violations.count'=0;;;0; 'z_Remove_Skype#job.score.percentage'=100.00%;;0:80;0;100 'z_Remove_Skype#job.violations.count'=0;;;0; 'z_Replace_LabWare#job.score.percentage'=100.00%;;0:80;0;100 'z_Replace_LabWare#job.violations.count'=0;;;0; 'z_Specific_Workstations_EEXT#job.score.percentage'=100.00%;;0:80;0;100 'z_Specific_Workstations_EEXT#job.violations.count'=0;;;0; 'z_Task_ScanAT#job.score.percentage'=100.00%;;0:80;0;100 'z_Task_ScanAT#job.violations.count'=0;;;0; 'z_Upgrade_Navisworks#job.score.percentage'=0.00%;;0:80;0;100 'z_Upgrade_Navisworks#job.violations.count'=0;;;0;
Job 'ActiveDirectory_Audit' score: 100.00 %, violations: 0
Job 'Copy_Aspen_VBS' score: 100.00 %, violations: 0
Job 'Copy_FCS' score: 100.00 %, violations: 0
Job 'Copy_Rapport' score: 100.00 %, violations: 0
Job 'DSC_Server_Compliance_and_CyberSec' score: 100.00 %, violations: 0
Job 'DSC_Service_Running' score: 100.00 %, violations: 0
Job 'Deleted_Scan' score: 100.00 %, violations: 0
Job 'DeployCiscoConfig' score: 100.00 %, violations: 0
Job 'Disable_Inactive_Users' score: 100.00 %, violations: 0
Job 'Enable_WakeOnLAN' score: 100.00 %, violations: 0
Job 'FSRM-ANTICRYPTO' score: 100.00 %, violations: 0
Job 'Install_WindowsUpdate_From_SCCM' score: 100.00 %, violations: 0
Job 'KPI_' score: 100.00 %, violations: 0
Job 'LogoffRemoteSession_RDS-Server' score: 100.00 %, violations: 0
Job 'Move_UserDisabled' score: 100.00 %, violations: 0
Job 'Password-Expiration-Notifications' score: 100.00 %, violations: 0
Job 'Remove_Labware_Shortcut' score: 100.00 %, violations: 0
Job 'Remove_SnapshotVM' score: 100.00 %, violations: 0
Job 'Renew_WiFi_Password' score: 100.00 %, violations: 0
Job 'SQL_Asgard' score: 100.00 %, violations: 0
Job 'Send_Mail_Liste5_Before_Reboot' score: 100.00 %, violations: 0
Job 'SYM_Backup' score: 0.00 %, violations: 0
Job 'Task_Data_GTF1' score: 100.00 %, violations: 0
Job 'Task_Data_GTF2' score: 100.00 %, violations: 0
Job 'Task_LBZ' score: 100.00 %, violations: 0
Job 'Task_PSIS' score: 100.00 %, violations: 0
Job 'Task_PSIS_ForeCast' score: 100.00 %, violations: 0
Job 'Tiers1_Update_And_Reboot' score: 100.00 %, violations: 0
Job 'Tiers2_Update_And_Reboot' score: 80.00 %, violations: 1
Job 'Tiers2b' score: 80.00 %, violations: 1
Job 'Tiers3_Update_And_Reboot' score: 100.00 %, violations: 0
Job 'Tiers3b_Restart_Service_Scheduler' score: 100.00 %, violations: 0
Job 'Tiers4_Update_And_Reboot' score: 80.00 %, violations: 1
Job 'TotalChrom_Copy_Files_To_Archive' score: 100.00 %, violations: 0
Job 'TotalChrom_Delete_Archive' score: 100.00 %, violations: 0
Job 'USB_BlackList' score: 100.00 %, violations: 0
Job 'Unused_Port_Shutdown' score: 100.00 %, violations: 0
Job 'WakeUp_Since60Days' score: 100.00 %, violations: 0
Job 'quarksUp_Send_Files_SFTP' score: 100.00 %, violations: 0
Job 'z_Cleanup_DHCP' score: 100.00 %, violations: 0
Job 'z_Delete_Legacy_Software_XXX' score: 66.00 %, violations: 1
Job 'z_Disable_Naemon_Notifications' score: 100.00 %, violations: 0
Job 'z_Enable_Naemon_Notifications' score: 0.00 %, violations: 0
Job 'z_FDS-Copy_G_to_SLV-Sharepoint' score: 100.00 %, violations: 0
Job 'z_Install_ESU_Windows7' score: 100.00 %, violations: 0
Job 'z_Monitoring_NSClient' score: 66.00 %, violations: 1
Job 'z_RemoveOffice2010' score: 100.00 %, violations: 0
Job 'z_Remove_Skype' score: 100.00 %, violations: 0
Job 'z_Replace_LabWare' score: 100.00 %, violations: 0
Job 'z_Specific_Workstations_EEXT' score: 100.00 %, violations: 0
Job 'z_Task_ScanAT' score: 100.00 %, violations: 0
Job 'z_Upgrade_Navisworks' score: 0.00 %, violations: 0

**Comment by Spleeff** [comment]
Did I misunderstand the use of this plugin ? Isn't it possible to get in the output only the jobs that are failing ?

**Comment by garnier-quentin** [comment]
In the short output you'll have the WARNING/CRITICAL jobs. In long output, you have everything

**Comment by Spleeff** [comment]
I guess I must be stupid, but unable to get the result I want ...
Basically, I would simply like if a job is in "Failed" status in Jenkins, it triggers a "Critical" status in Centreon.

Is it possible ?

**Comment by garnier-quentin** [comment]
Use following option: --critical-score='100:'
