### ISSUE TITLE
Open-ba for openticket :)

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#4221]
Hi,

Is it possible to add the possibilty to open ticket for BA with openticket ?

 /usr/lib/centreon/plugins/centreon_notification_centreon_opentickets_api.pl --plugin notification::centreon::opentickets::api::plugin --mode=open-ba :-)

Thanks a lot,

**Comment by garnier-quentin** [comment]
The module open-tickets doesn't have that capability. So it's first be developed in open-tickets. I close it

**Comment by ponchoh** [comment]
@romsworld you can post it as an idea through

https://thewatch.centreon.com/ideas

# 😁🍀
