### ISSUE TITLE
F5 Total memory usage

### ISSUE THREAD

**Issue by Pecorette** [centreon/centreon-plugins#4226]
Hello,

Is it possible to add probe on F5 plugin for : 

sysGlobalHostOtherMemoryTotal : 1.3.6.1.4.1.3375.2.1.1.2.20.44
sysGlobalHostOtherMemoryUsed : 1.3.6.1.4.1.3375.2.1.1.2.20.45

Thank you for your feedback.

**Comment by Pecorette** [comment]
Any feedback to my question ?

THanks

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
