### ISSUE TITLE
storage::netapp::snmp::plugin broken after moving libraries

### ISSUE THREAD

**Issue by Copis** [centreon/centreon-plugins#4227]
## Bug/Question

Just updated from last release and find that our current NetApp checks stop working. Seems that snmp modules as been moved to storage/netapp/ontap/snmp

`[root@Monitor2 netapp]# '/usr/lib64/nagios/plugins/centreon_plugins.pl' '--hostname' '172.24.0.10' '--mode' 'psu' '--plugin' 'storage::netapp::snmp::plugin'
UNKNOWN: Cannot load module --plugin.
Can't locate storage/netapp/snmp/plugin.pm in @INC (@INC contains: /usr/lib64/nagios/modules/centreon-plugins/src/ /usr/lib64/nagios/plugins /root/perl5/lib/perl5/5.16.3/x86_64-linux-thread-multi /root/perl5/lib/perl5/5.16.3 /root/perl5/lib/perl5/x86_64-linux-thread-multi /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib64/nagios/modules/centreon-plugins/src//centreon/plugins/misc.pm line 223.
`

**Comment by garnier-quentin** [comment]
You use a very old version. The path is now: ```storage::netapp::ontap::snmp::plugin```
