### ISSUE TITLE
network::juniper::mseries::plugin and IPv6-BGP-Peers

### ISSUE THREAD

**Issue by TAFfm** [centreon/centreon-plugins#4236]
Dear Team/Maintainers,

is it possible to be getting IPv6-BGP-Peers to be working with the network::juniper::mseries::plugin ? At the moment the plugin is only able to retrive data vor IPv4-BGP-Peer-Tables, it seems.

Thanks a lot

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of following branches ?
.1.3.6.1.4.1.2636.5.1.1.2.1.1
.1.3.6.1.4.1.2636.5.1.1.2.6.2

You can sent it to my email (qgarnier@centreon.com)

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
