### ISSUE TITLE
Plugin snmp interfaces --add-traffic not working for range thresholds

### ISSUE THREAD

**Issue by hugleo** [centreon/centreon-plugins#4238]
Looks like is not working for range thresholds https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

Should get an alert if traffic = 0%. But for some reason traffic is always converted to 0% and is raising the critical alert all the time, even if traffic is > 5 % for example.
--critical-out-traffic=@0:0
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.2.1 --snmp-version=v2c --snmp-community=public --interface='ge-0/0/0' --name --add-status --add-traffic  --critical-out-traffic=@0:0
CRITICAL: Interface 'ge-0/0/0.0' Traffic Out : 0.00b/s (0.00%) | 'traffic_in_ge-0/0/0'=3421904.00b/s;;;0;1000000000 'traffic_out_ge-0/0/0'=70940564.80b/s;;@0:0;0;1000000000 'traffic_in_ge-0/0/0.0'=0.00b/s;;;0;1000000000 'traffic_out_ge-0/0/0.0'=0.00b/s;;@0:0;0;1000000000

perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.2.1 --snmp-version=v2c --snmp-community=public --interface='ge-0/0/0' --name --add-status --add-traffic  --critical-out-traffic=@0:0
CRITICAL: Interface 'ge-0/0/0.0' Traffic Out : 0.00b/s (0.00%) | 'traffic_in_ge-0/0/0'=3876702.63b/s;;;0;1000000000 'traffic_out_ge-0/0/0'=45642533.26b/s;;@0:0;0;1000000000 'traffic_in_ge-0/0/0.0'=27.43b/s;;;0;1000000000 'traffic_out_ge-0/0/0.0'=0.00b/s;;@0:0;0;1000000000

Should get an alert if traffic < 3%. But for some reason traffic is always converted to 0% and is raising the critical alert all the time, even if traffic is > 5 % for example.
--critical-out-traffic=3:
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.2.1 --snmp-version=v2c --snmp-community=public --interface='ge-0/0/0' --name --add-status --add-traffic  --critical-out-traffic=3:
CRITICAL: Interface 'ge-0/0/0.0' Traffic Out : 0.00b/s (0.00%) | 'traffic_in_ge-0/0/0'=6617918.86b/s;;;0;1000000000 'traffic_out_ge-0/0/0'=35126315.81b/s;;30000000:;0;1000000000 'traffic_in_ge-0/0/0.0'=0.00b/s;;;0;1000000000 'traffic_out_ge-0/0/0.0'=0.00b/s;;30000000:;0;1000000000

 perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.2.1 --snmp-version=v2c --snmp-community=public --interface='ge-0/0/0' --name --add-status --add-traffic  --critical-out-traffic=3:
CRITICAL: Interface 'ge-0/0/0.0' Traffic Out : 0.00b/s (0.00%) | 'traffic_in_ge-0/0/0'=6615515.10b/s;;;0;1000000000 'traffic_out_ge-0/0/0'=47023674.15b/s;;30000000:;0;1000000000 'traffic_in_ge-0/0/0.0'=21.49b/s;;;0;1000000000 'traffic_out_ge-0/0/0.0'=0.00b/s;;30000000:;0;1000000000

The normal threshold works. See the traffic is greater than 2%
--critical-out-traffic=2
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.2.1 --snmp-version=v2c --snmp-community=public --interface='ge-0/0/0' --name --add-status --add-traffic  --critical-out-traffic=2
CRITICAL: Interface 'ge-0/0/0' Traffic Out : 79.84Mb/s (7.98%) | 'traffic_in_ge-0/0/0'=6937464.00b/s;;;0;1000000000 'traffic_out_ge-0/0/0'=79835634.18b/s;;0:20000000;0;1000000000 'traffic_in_ge-0/0/0.0'=43.64b/s;;;0;1000000000 'traffic_out_ge-0/0/0.0'=0.00b/s;;0:20000000;0;1000000000

perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.2.1 --snmp-version=v2c --snmp-community=public --interface='ge-0/0/0' --name --add-status --add-traffic  --critical-out-traffic=2
CRITICAL: Interface 'ge-0/0/0' Traffic Out : 125.70Mb/s (12.57%) | 'traffic_in_ge-0/0/0'=12187628.80b/s;;;0;1000000000 'traffic_out_ge-0/0/0'=125701764.80b/s;;0:20000000;0;1000000000 'traffic_in_ge-0/0/0.0'=0.00b/s;;;0;1000000000 'traffic_out_ge-0/0/0.0'=0.00b/s;;0:20000000;0;1000000000

perl centreon_plugins.pl --version
Global Version: (dev)

**Comment by hugleo** [comment]
Think you facing same error since your interface is having some traffic: traffic_out_ge-0/0/0'=**70940564.80b/s** the command should return OK and not CRITICAL, right? @0:0 should be 0 b/s

**Comment by garnier-quentin** [comment]
For the following perfdata ```traffic_out_ge-0/0/0'=70940564.80b/s``` it's OK. The critical is for the interface: ```ge-0/0/0.0```
