### ISSUE TITLE
[Question] apps::protocols::snmp::plugin response OID different from Requested OID

### ISSUE THREAD

**Issue by PedroMSantosD** [centreon/centreon-plugins#4241]
Thanks for using centreon-plugins! Please follow the indications shown below according to your issue and describe it in English.

## Question

If you are reporting a bug/question, make sure that there aren't any similar/duplicates issues already open (none found).

Hi,
I need to monitor SDWAN tunnels on Cisco devices; but the OID I need to monitor is dynamic in the sense that it is comprised of all of the components of a network socket, namely source ipaddress, destination ipaddress, source port and destination port:

`OID = BASE_OID.4.SRC_IP.4.DST_IP.4.SRC_PORT.DST_PORT.2
`

Although src/and dst ip for the port are static, and can easily be configured on the OID, the ports part is dynamic, and will vary over time:

let's write an example (with fake values)
say BASE_OID = .1.3.6.1.4.1.9.9.1002.1.1.1.1.10
\# Fake public ip for discussion only
say SRC_IP = 8.8.8.8
\# Fake public ip for discussion only
say DST_IP = 9.9.9.9
\# Fake port  for discussion only
say DST_PORT = 22333
the exact OID would be of the form

OID = BASE_OID.4.SRC_IP.4.DST_IP.4.SRC_PORT.DST_PORT.2

Example SNMPWALK using ONLY the involved IP addresses:
```
OID =  .1.3.6.1.4.1.9.9.1002.1.1.1.1.10.4.8.8.8.8.4.9.9.9.9
OUTCOME
1.3.6.1.4.1.9.9.1002.1.1.1.1.10.4.8.8.8.8.4.9.9.9.9.12346.22333.2 = INTEGER: 3

```

Is it possible for you to tell if there is such a thing as a 'mode' / 'plugin' that would allow me to evaluate this outcome from a 'child' element, as I can not build the proper 'FULL' OID (source port is not fixed on tunnel configuration)?

Thanks in advance

**Comment by PedroMSantosD** [comment]
## snmpwalk
Masking the IPaddresses (apologies on this part; for security, I have replaced ipv4 segments with letters)
src = A.B.242.4
dst = E.F.119.120
```
~$ snmpwalk -On -v2c -c CHANGEME 10.108.61.15 .1.3.6.1.4.1.9.9.1002.1.1.1.1.10.4.A.B.242.4.4.E.F.119.120

.1.3.6.1.4.1.9.9.1002.1.1.1.1.10.4.A.B.242.4.4.E.F.119.120.12346.12426.2 = INTEGER: 3
```

## mibfile:
Cisco indicates htat the operational data for the Bidirectional Fowrarding Protocols (BFD) are similar to viptela ones 
```
BfdmgrStateEnum ::= TEXTUAL-CONVENTION
    STATUS      current
    DESCRIPTION "BFD manager state"
    SYNTAX      INTEGER {adminDown(0),
                         down(1),
                         init(2),
                         up(3),
                         invalid(4),
                         inactive(5)}
```


[CISCO-SDWAN-BFD-MIB.txt](https://github.com/centreon/centreon-plugins/files/10862101/CISCO-SDWAN-BFD-MIB.txt)

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk of following branch ? .1.3.6.1.4.1.9.9.1002.1.1.1
I could do a bfd-sessions mode

**Comment by PedroMSantosD** [comment]
Hi, 

snmpwalk added

`snmpwalk -On -v2c -c calvex-yvr-ro 10.108.61.15 1.3.6.1.4.1.9.9.1002.1.1.1 | | sed "s/.XXX.YYY.242.4/.A.B.242.4/g" | sed "s/WWW.ZZZ.119.120/E.F.119.120/g" > sedded_walk
`
again, I have sedded the IPv4 components of the firtst two octets of the source and destination ip addresses to A.B  and E.F
[sedded_walk.txt](https://github.com/centreon/centreon-plugins/files/10862243/sedded_walk.txt)

**Comment by PedroMSantosD** [comment]
Can we drop the attached file?

**Comment by garnier-quentin** [comment]
It's dropped. You can sent it to my email.

**Comment by PedroMSantosD** [comment]
Hi, I have edited the file and removed all other pubilc ip addresses from the walk 

[withoutpublicips.txt](https://github.com/centreon/centreon-plugins/files/10862873/withoutpublicips.txt)

Best,

**Comment by PedroMSantosD** [comment]
My bad. The nagios plugin responds with any oid under the tree. hence it is nor reliable.

**Comment by PedroMSantosD** [comment]
[sedded_walk.txt](https://github.com/centreon/centreon-plugins/files/10919309/sedded_walk.txt)

the capital leters
A,B,.....Y,Z
represent ipv4 octets(1..254).
Just using them as a mask for the actual addresses.
