### ISSUE TITLE
Error calling the funcion filter-perfdata-adv alert_triggered()

### ISSUE THREAD

**Issue by hugleo** [centreon/centreon-plugins#4245]
/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.0.1 --snmp-version=v2c --snmp-community=public --add-errors --filter-perfdata-adv='alert_triggered()'
OK: All interfaces are ok UNKNOWN: Code evaluation error: Undefined subroutine &centreon::plugins::output::alert_triggered called at (eval 28) line 1.

**Comment by garnier-quentin** [comment]
It's working for me. Do you use the last version ?

**Comment by hugleo** [comment]
Yes,

Tried to clone right now, same error:

[root@server centreon-new]#  git clone https://github.com/centreon/centreon-plugins.git
Cloning into 'centreon-plugins'...
remote: Enumerating objects: 121978, done.
remote: Counting objects: 100% (400/400), done.
remote: Compressing objects: 100% (240/240), done.
remote: Total 121978 (delta 159), reused 306 (delta 107), pack-reused 121578
Receiving objects: 100% (121978/121978), 30.88 MiB | 15.58 MiB/s, done.
Resolving deltas: 100% (61057/61057), done.
Updating files: 100% (6175/6175), done.
[root@server centreon-new]# cd centreon-plugins/
doc/       .git/      .github/   packaging/ src/       
[root@server centreon-new]# cd centreon-plugins/src/
apps/          blockchain/    centreon/      cloud/         contrib/       database/      example/       hardware/      network/       notification/  os/            snmp_standard/ storage/       
[root@server centreon-new]# cd centreon-plugins/src/
[root@server src]# ls
apps  blockchain  centreon  centreon_plugins.pl  cloud  contrib  database  example  hardware  network  notification  os  snmp_standard  storage
[root@server src]# ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=192.168.0.1 --snmp-version=v2c --snmp-community=public --add-errors --filter-perfdata-adv='alert_triggered()'
OK: All interfaces are ok UNKNOWN: Code evaluation error: Undefined subroutine &centreon::plugins::output::alert_triggered called at (eval 30) line 1. 
[root@server src]#

**Comment by garnier-quentin** [comment]
Can you provide your OS version ?

**Comment by hugleo** [comment]
cat /etc/redhat-release 
Rocky Linux release 9.1 (Blue Onyx)

**Comment by hugleo** [comment]
Installed the package dnf install perl-Safe and that's solved the problem!

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
