### ISSUE TITLE
[database::oracle::plugin] new mode to check blocking sessions

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4247]
It should be nice to have a mode wich allows to check if there are blocking sessions on the DB

- https://www.dba-oracle.com/t_find_blocking_sessions.htm
- https://www.tutorialspoint.com/how-to-identify-blocked-and-blocking-sessions-in-oracle
- https://stackoverflow.com/questions/46886403/finding-query-from-oracle-which-is-blocking-session

If you need some detail information please let me know

**Comment by garnier-quentin** [comment]
Do you have an example of blocking sessions with following requests:
```
select l1.inst_id,l1.sid, ' IS BLOCKING ', l2.sid,l1.type,l2.type,l1.lmode,l2.lmode,l2.inst_id
 from gv$lock l1, gv$lock l2
 where l1.block =1 and l2.request > 0and l1.id1=l2.id1
 and l1.id2=l2.id2;
```

```
SELECT blocking_session,
  sid,
  wait_class,
  seconds_in_wait
FROM v$session
WHERE blocking_session IS NOT NULL
ORDER BY blocking_session;
```

**Comment by joschi99** [comment]
Ok, I will let you know the results asap.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
