### ISSUE TITLE
[network::h3c::snmp::plugin] mode=hardware problem with temperature

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#425]
Hello!

When testing some firms switch models H3C can not obtain data on temperature:
./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=hardware --exclude=port,container,stack,module --hostname=172.31.255.13 --snmp-community=public --snmp-version=2
OK: All 4 components are ok [1/1 chassis, 1/1 fans, 1/1 power supplies, 1/1 sensors]. | 'temp_118'=**0C**;;~:80;;

Despite the fact that the plug-in code is available for some of the function definition OIDs group to use, it does not always work.
Direct survey snmpwalk using the same switch:
HH3C-ENTITY-EXT-MIB::hh3cEntityExtTemperature.112 = INTEGER: 58
HH3C-ENTITY-EXT-MIB::hh3cEntityExtTemperature.262 = INTEGER: 58

In the first case, the plugin tries to use the standard ENTITY-MIB. In the second case MIBs switch manufacturer HH3C-ENTITY-EXT-MIB.

Thanks for attention.

**Comment by garnier-quentin** [comment]
Hi,

Could you give me the result for following snmpwalk ?
snmpwalk -On -c public -v 2c IP .1.3.6.1.4.1.25506.2.6.1.1.1.1
snmpwalk -On -c public -v 2c IP .1.3.6.1.4.1.2011.10.2.6.1.1.1.1

**Comment by maksimatveev** [comment]
@garnier-quentin done,
[2011.txt](https://github.com/centreon/centreon-plugins/files/334417/2011.txt)
[25506.txt](https://github.com/centreon/centreon-plugins/files/334416/25506.txt)

 in the attached file

**Comment by garnier-quentin** [comment]
That's normal. The instance 112 has a value:
.1.3.6.1.4.1.25506.2.6.1.1.1.1.12.112 = INTEGER: 49

But the instance 118 has value 0:
.1.3.6.1.4.1.25506.2.6.1.1.1.1.12.118 = INTEGER: 0

And 'temp_118'=0C;;~:80;; is for the instance 118.

**Comment by maksimatveev** [comment]
@garnier-quentin you can make changes to plug-in, so that he saw not only the 118th instance, but also any other?

**Comment by garnier-quentin** [comment]
The temperature is displayed if there is a threshold.

**Comment by maksimatveev** [comment]
'temp_118'=0C;;**~:80**;; this is not the threshold value?

**Comment by garnier-quentin** [comment]
This is the threshold value. That's why the temperature is displayed. But the value is 0 because it's 0 in the MIB:
.1.3.6.1.4.1.25506.2.6.1.1.1.1.12.**118** = INTEGER: 0

**Comment by maksimatveev** [comment]
@garnier-quentin need to configure from the the equipment?

**Comment by garnier-quentin** [comment]
It seems 'hh3cEntityExtOperStatus' is not supported. Maybe i should not look when temperature is 0.

**Comment by maksimatveev** [comment]
@garnier-quentin  ie fix it not happen?

**Comment by maksimatveev** [comment]
snmpwalk -c public -v 2c 86.110.173.138 hh3cEntityExtOperStatus | grep 'enabled(3)'
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.12 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.13 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.14 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.15 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.16 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.17 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.18 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.19 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.20 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.21 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.112 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.113 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.116 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.212 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.262 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.313 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.315 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.316 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.319 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.320 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.325 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.326 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.328 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.329 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.334 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.335 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.336 = INTEGER: enabled(3)
HH3C-ENTITY-EXT-MIB::hh3cEntityExtOperStatus.339 = INTEGER: enabled(3)

**Comment by garnier-quentin** [comment]
Could you test ?

**Comment by maksimatveev** [comment]
@garnier-quentin 
OK: All 4 components are ok [1/1 chassis, 1/1 fans, 1/1 power supplies, 1/1 sensors]. |
temperature is not displayed

**Comment by maksimatveev** [comment]
Sensor 'HP > HP A5820X-24XG-SFP+ Switch Software Version 5.20 > CONTAINER LEVEL1 > SENSOR' status is 'normal' [instance = 118]

**Comment by garnier-quentin** [comment]
It should be ok now.

**Comment by maksimatveev** [comment]
strange, probably you have to use the snmp_standard
./centreon_plugins.pl --plugin=snmp_standard::plugin --mode=numeric-value --hostname=172.29.255.61 --snmp-community=public --oid=1.3.6.1.4.1.25506.2.6.1.1.1.1.12.112 --snmp-version=2
UNKNOWN: SNMP GET Request : Cant get a single value

**Comment by garnier-quentin** [comment]
the snmpwalk for '1.3.6.1.4.1.25506.2.6.1.1.1.1.12.112' gives what ? 
I have fixed the mode hardware of h3c. You should see the temperature ;)

**Comment by maksimatveev** [comment]
@garnier-quentin 
Quentin alas, not the temperature displayed =(
1.3.6.1.4.1.25506.2.6.1.1.1.1.12.112 shows temperature protection switch

**Comment by maksimatveev** [comment]
@garnier-quentin I think that the problem is in the selection of the sensor (instance)
.1.3.6.1.2.1.47.1.1.1.1.7.112 = STRING: Board
.1.3.6.1.2.1.47.1.1.1.1.7.118 = STRING: SENSOR 1

**Comment by maksimatveev** [comment]
@garnier-quentin another model switch
.1.3.6.1.2.1.47.1.1.1.1.7.2 = STRING: S5500-EI
.1.3.6.1.2.1.47.1.1.1.1.7.47 = STRING: Board

**Comment by maksimatveev** [comment]
@garnier-quentin 
![27-06-16 13 23 19](https://cloud.githubusercontent.com/assets/15804154/16376744/a5ae6e9a-3c6a-11e6-9352-e47002b4f1f0.png)

**Comment by maksimatveev** [comment]
![27-06-16 13 29 04](https://cloud.githubusercontent.com/assets/15804154/16376840/32ad5234-3c6b-11e6-939a-2dfcbcfad14e.png)

**Comment by garnier-quentin** [comment]
I have done a last fix. Could you test it ?

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, nothing changes. Plugins updated.
./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=hardware --exclude=port,container,stack,module --hostname=172.76.192.142 --snmp-community=public --snmp-version=2
OK: All 3 components are ok [1/1 chassis, 1/1 fans, 1/1 power supplies]. |

**Comment by garnier-quentin** [comment]
Very weird. It should display the temperature.

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, I believe that should be)) But it does not show.
is something else need to send for diagnosing?

**Comment by garnier-quentin** [comment]
Provide me the complete snmpwalk. I will test:
snmpwalk -Cc -v2c -c public -ObentU localhost 1.3.6 > myagent.snmpwalk

**Comment by maksimatveev** [comment]
@garnier-quentin The command is executed for the localhost, not for the switch?

**Comment by garnier-quentin** [comment]
Yes, you have to set your community and your equipment address

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, in the output many of confidential information, I will send you on mail, OK?

**Comment by garnier-quentin** [comment]
Yes that's ok.

**Comment by maksimatveev** [comment]
@garnier-quentin Done! Other requests for different switch models.
[HH3C-25506 (H3C5500).snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/349577/HH3C-25506.H3C5500.snmpwalk.txt)
[HUAWEI-2011(H3C5500).snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/349579/HUAWEI-2011.H3C5500.snmpwalk.txt)
[HUAWEI-2011 (H3C5820).snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/349582/HUAWEI-2011.H3C5820.snmpwalk.txt)
[HH3C-25506 (H3C5820).snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/349585/HH3C-25506.H3C5820.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
Sorry... I also need the snmpwalk of the following OID:
.1.3.6.1.2.1.47

Thanks!

**Comment by fixlair** [comment]
Hello @maksimatveev 
Could you also provide the software version of the concerned Swtich ? Depending of the version, H3C change sometimes completly MIBs. We've got the case few years ago with Release P19 for s3600 models.
Regards,

**Comment by maksimatveev** [comment]
@garnier-quentin I put the desired output of snmpwalk
[H3C5820.1.47.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/384468/H3C5820.1.47.snmpwalk.txt)
[H3C5500.1.47.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/384469/H3C5500.1.47.snmpwalk.txt)

@fixlair H3C5500 5.20 Release 2202P15
H3C5820 5.20 Release 1211P09

**Comment by garnier-quentin** [comment]
The "H3C5820.1.47.snmpwalk.txt" is for which one above ? HUAWEI-2011 (H3C5820).snmpwalk.txt ?

**Comment by maksimatveev** [comment]
@garnier-quentin Sorry, I did not understand the question

**Comment by garnier-quentin** [comment]
Could you not split snmpwalk for one equipment ?

**Comment by maksimatveev** [comment]
@garnier-quentin I just did as you asked) the more it will see the differences for different switch models.

**Comment by garnier-quentin** [comment]
You give in two separate files for one equipment. So no :)

**Comment by maksimatveev** [comment]
@garnier-quentin I hope not misled you?)

**Comment by garnier-quentin** [comment]
The file 'H3C5820.1.47.snmpwalk.txt' is for which one ?
* HH3C-25506 (H3C5500).snmpwalk.txt
* HUAWEI-2011(H3C5500).snmpwalk.txt
* HUAWEI-2011 (H3C5820).snmpwalk.txt
* HH3C-25506 (H3C5820).snmpwalk.txt

**Comment by maksimatveev** [comment]
@garnier-quentin I think that there is no)
1.3.6.1.4.1.25506:
HH3C-25506 (H3C5500).snmpwalk.txt
HH3C-25506 (H3C5820).snmpwalk.txt
1.3.4.1.4.1.2011:
HUAWEI-2011(H3C5500).snmpwalk.txt
HUAWEI-2011 (H3C5820).snmpwalk.txt
1.3.6.1.2.1.47:
H3C5820.1.47.snmpwalk.txt
H3C5500.1.47.snmpwalk.txt
