### ISSUE TITLE
Problems opening tickets via api in glpi - plugin open tickets

### ISSUE THREAD

**Issue by guinfox** [centreon/centreon-plugins#4250]
when using the openticket plugin I cannot open a call in glpi

![image](https://user-images.githubusercontent.com/107438460/222458406-6436b214-1df5-4781-b117-9010d9bed832.png)

**Comment by guinfox** [comment]
centreon 22.10.6 / Glpi 10.0.5

**Comment by garnier-quentin** [comment]
It's not a centreon-plugins issue. Please open it here: https://github.com/centreon/centreon
