### ISSUE TITLE
[apps::protocols::tcp::plugin] check multiple hosts with tcp plugin

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#4252]
Hi,

Is it possible to check multiple hosts with tcp plugin as with the icmp plugin ?
With icmp plugin, you can use the -H option in the extraoptions field (-H x.x.x.x y.y.y.y z.z.z.z).
My goal is to monitor a particular tcp port on multiple ip.

Centreon 21.10.13
centreon-plugin-Applications-Protocol-Tcp-20230215-164619.el7.noarch

Best regards,

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
