### ISSUE TITLE
[network::fortinet::fortigate::snmp::plugin] Problem with SNMP since upgrade in 7.0.10

### ISSUE THREAD

**Issue by JordanSRT** [centreon/centreon-plugins#4255]
Hi,

We upgraded some Fortigate Firewall's to the latest FortiOS version 7.0.10 and since the upgrade, it seems that the plugin can't communicate with the firewall. 
When we try to interrogate them, we get an **UNKNOW: SNMP GET Request: Timeout** now.

Best regards,

**Comment by garnier-quentin** [comment]
Try to use --snmp-autoreduce option

**Comment by JordanSRT** [comment]
I tried the option without any changes. I can see the UDP packet go to the firewall without reply.

**Comment by garnier-quentin** [comment]
All modes have the issue ?

**Comment by JordanSRT** [comment]
On all the modes that I use :
- sessions
- cluster-status
- memory
- cpu

**Comment by garnier-quentin** [comment]
snmpwalk is working on your equipment ?

**Comment by JordanSRT** [comment]
So after several debug we found the solution.
After the update the passive firewall became the active and we can't make SNMP request on the management port of the passive firewall. We monitor on an other interface to avoid this problem.
