### ISSUE TITLE
create support for Cambium PMP devices

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4257]
It should be nice to have support for Cambium PMP devices (ePMP is not working for them).

MIB files: 
[PMP450x 22.0.1 MIBS.zip](https://github.com/centreon/centreon-plugins/files/10908176/PMP450x.22.0.1.MIBS.zip)

SNMP walk:
[canopy pmp450m.txt](https://github.com/centreon/centreon-plugins/files/10908185/canopy.pmp450m.txt)

**Comment by rmorandell-pgum** [comment]
Hello Quentin,

I get access to the system in the next days/weeks and would develop/test the plugin. 

Is that ok for you or are you already working on it ?

**Comment by garnier-quentin** [comment]
No i'm not working on it

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
