### ISSUE TITLE
[os::linux::local::plugin] mode=ntp, can't parse chronyc's command ouput

### ISSUE THREAD

**Issue by FreshardF** [centreon/centreon-plugins#4258]
hi,

i have a issue with mode ntp.

i think than script can't split the output command.

maybe we need add this line before line 281 of ntp.pm => $line =~ /$mode->{regexp}/;

commande line : 
centreon_plugins.pl --plugin=os::linux::local::plugin --mode=ntp --ntp-mode=chronyc --filter-name=".*" --filter-state=".*" --warning-status="" --critical-status="" --warning-offset="" --critical-offset="" --warning-stratum="" --critical-stratum="" --warning-peers="" --critical-peers="" --use-new-perfdata --verbose

output :
Use of uninitialized value $value in substitution (s///) at /var/lib/centreon/plugin/centreon/plugins/misc.pm line 318.
........
Use of uninitialized value $value in substitution (s///) at /var/lib/centreon/plugin/centreon/plugins/misc.pm line 320.

OK: Number of ntp peers: 3 - All peers are ok | 'peers.detected.count'=3;;;0; 'XX.YY.XX.YYY#peer.time.offset.milliseconds'=0ms;;;0; 'XX.YY.XX.YYY#peer.time.offset.milliseconds'=0ms;;;0; 'XX.YY.XX.YYY#peer.time.offset.milliseconds'=0ms;;;0;
Peer 'XX.YY.XX.YYY' status : skipped (no value(s)), stratum : skipped (no value(s))
Peer 'XX.YY.XX.YYY' status : skipped (no value(s)), stratum : skipped (no value(s))
Peer 'XX.YY.XX.YYY' status : skipped (no value(s)), stratum : skipped (no value(s))

**Comment by garnier-quentin** [comment]
Could you provide the output of following command ? ```chronyc -n sources 2>&1```

**Comment by FreshardF** [comment]
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^+ XX.YY.TT.PP                     5   9   377   461   -674us[ -681us] +/-   31ms
^*  XX.YY.TT.PP                    5   8   377   200   -210us[ -199us] +/-   35ms
^+ XX.YY.TT.PP                    5  10   377   959   +883us[ +857us] +/-   41ms

**Comment by garnier-quentin** [comment]
I don't have that issue. Do you use the last version ?

**Comment by FreshardF** [comment]
yes, i just pull last version of master branch.

i don't understand but if i comment the test for "filter-name" and "filter_state", like than : 

`  my ($remote_peer, $peer_fate) = (centreon::plugins::misc::trim($2), centreon::plugins::misc::trim($1));
            if ($mode->{type} eq 'chronyc') {
                $remote_peer = centreon::plugins::misc::trim($3);
                $peer_fate = centreon::plugins::misc::trim($2);
            }
            #if (defined($self->{option_results}->{filter_name}) && $self->{option_results}->{filter_name} ne '' &&
            #    $remote_peer !~ /$self->{option_results}->{filter_name}/) {
            #    print "first if";
            #    $self->{output}->output_add(long_msg => "skipping '" . $remote_peer . "': no matching filter peer name.", debug => 1);
            #    next;
            #}
            #if (defined($self->{option_results}->{filter_state}) && $self->{option_results}->{filter_state} ne '' &&
            #    $peer_fate !~ /$self->{option_results}->{filter_state}/) {
            #    print "second if";
            #    $self->{output}->output_add(long_msg => "skipping '" . $remote_peer . "': no matching filter peer state.", debug => 1);
            #     next;
            #}
`

i don't have issue again :   
output:
OK: Number of ntp peers: 3 - All peers are ok | 'peers.detected.count'=3;;;0; 'xx.y.p.z#peer.time.offset.milliseconds'=37ms;;;0; 'xx.y.p.z#peer.stratum.count'=5;;;0; 'xx.y.p.z#peer.time.offset.milliseconds'=35ms;;;0; 'xx.y.p.z#peer.stratum.count'=5;;;0; 'xx.y.p.z#peer.time.offset.milliseconds'=31ms;;;0; 'xx.y.p.z#peer.stratum.count'=5;;;0;
Peer 'xx.y.p.z' [type: server] [reach: 377] [state: combined]
Peer 'xx.y.p.z' [type: server] [reach: 377] [state: current synced]
Peer 'xx.y.p.z' [type: server] [reach: 377] [state: combined]

**Comment by garnier-quentin** [comment]
ok got it!

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4261
