### ISSUE TITLE
Windows SNMP Storage issue when the HDD is more 10To

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#427]
Hello team,

There is an issue when we check a 10To hard drive:
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname='10.17.1.47' --snmp-version='2' --snmp-community='public' --verbose --storage='Y:' --name --regexp --display-transform-src='(..).*' --display-transform-dst='$1' --warning='80' --critical='90'                                   OK: Skipping storage 'Y:': total size is <= 0 (-5604773990400) |

Same with the old plugin:
./check_centreon_snmp_remote_storage -H 10.17.1.47 -w 80 -c 90 -d 'Y:' -n
Disk OK - Y: TOTAL: -5219.853GB USED: 3309.473GB (-63%) FREE: -8529.325GB (163%)|size=-5604773990400B used=3553519222784B;-4483819192320;-5044296591360;0;-5604773990400

Thanks for your help

**Comment by garnier-quentin** [comment]
Hi,

We know the issue but it comes from SNMP agent. You should use NSClient++. SNMP is deprecated on Windows.

**Comment by matthieu-robin** [comment]
Did you plan to remplace it with CIM as proposed by Microsoft?
https://technet.microsoft.com/en-us/library/hh831568(v=ws.11).aspx

SNMP

SNMP is deprecated. Instead, use the Common Information Model (CIM), which is supported by the WS-Management web services protocol and implemented as Windows Remote Management.

Thanks a lot Quentin

**Comment by garnier-quentin** [comment]
I have tried to use WinRM (wsman). But there is some weird issues. For example, i can't request the wmi with a non-admin user.

**Comment by matthieu-robin** [comment]
is it the end of agentless windows supervision?? 👎

**Comment by garnier-quentin** [comment]
You can ask to Microsoft. SNMP is an agent in fact. Winrm also ;) I don't like the agentless name.

**Comment by matthieu-robin** [comment]
will do :-)

Thanks sir!

Matthieu ROBIN
0041 79 746 93 05
0033 6 51 42 92 09
www.matthieurobin.com
info@matthieurobin.com
