### ISSUE TITLE
storage::emc::unisphere::restapi::plugin - add hardware component memorymodule

### ISSUE THREAD

**Issue by BertrandJO** [centreon/centreon-plugins#4274]
Hi,

Using this plugin to monitor a Dell Unity array, we did not detect a memory module failure.

The rest API allows to query such component with a memoryModule query like battery, ioModule, fan and other available components in this plugin.

It would be a great improvement to have this memory module state.

Regards,

Bertrand.

**Comment by garnier-quentin** [comment]
Could you provide the curl command and the json output please ?

**Comment by Dadouu** [comment]
Here some result with a memory component module check
![image](https://user-images.githubusercontent.com/24298881/224660239-770847b9-0aef-4379-b53b-939be1716ad8.png)

**Comment by BertrandJO** [comment]
The Memory list is avalaible calling this URL : 

https://X.X.X.X/api/types/memoryModule/instances

The json output is : 

{"@base":"https://172.22.4.144/api/types/memoryModule/instances?per_page=2000","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"&page=1"}],"entries":[{"@base":"https://172.22.4.144/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spa_mm_0"}],"content":{"id":"spa_mm_0"}},{"@base":"https://172.22.4.144/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spa_mm_1"}],"content":{"id":"spa_mm_1"}},{"@base":"https://172.22.4.144/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spa_mm_2"}],"content":{"id":"spa_mm_2"}},{"@base":"https://172.22.4.144/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spa_mm_3"}],"content":{"id":"spa_mm_3"}},{"@base":"https://172.22.4.144/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spb_mm_0"}],"content":{"id":"spb_mm_0"}},{"@base":"https://172.22.4.144/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spb_mm_1"}],"content":{"id":"spb_mm_1"}},{"@base":"https://172.22.4.144/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spb_mm_2"}],"content":{"id":"spb_mm_2"}},{"@base":"https://X.X.X.X/api/instances/memoryModule","updated":"2023-03-13T09:21:15.760Z","links":[{"rel":"self","href":"/spb_mm_3"}],"content":{"id":"spb_mm_3"}}]}

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4367
