### ISSUE TITLE
[apps::protocols::http::plugin] Mode response - Fail since update system

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#428]
Hi,
I use this plugin since few months with double authentication and works correctly.
/usr/lib64/centreon-plugins/centreon_plugins.pl  --plugin=apps::protocols::http::plugin --mode=response --hostname='my.domain' --port='443' --proto='https' --cert-file='/CRT.p12' --cert-pwd='MyPassword' --cert-pkcs12 --warning='3' --critical='10' --timeout='30' --filter-perfdata=time

On last WE, I upgrade centreon on 2.7.4 (since 2.6.6).
After this upgrade, I upgrade the system on latest releases with yum update on each pollers.

Since that, the plugin return this error:
     CRITICAL: 500 Status read failed:

I try to activate --debug and --verbose but says no more informations :(

You will find history of updated packages in joined file. [yum_update.txt](https://github.com/centreon/centreon-plugins/files/325202/yum_update.txt)
release of centreon-plugin 20160122
Is it possible to activate a really verbose or debug mode for this plugin?

Is there a perl package, ssl or another with known problems?
thanks.

**Comment by garnier-quentin** [comment]
Could you tried with following option ? --ssl=sslv3 or --ssl=tlsv1

**Comment by cmeschin** [comment]
I tried and it's the same result.

**Comment by garnier-quentin** [comment]
The problem is a little complex. LWP can use two libraries for SSL layer:
* Net::SSL (historic and not maintained)
* IO::Socket::SSL.

In centos 6.7, the code is like that:
```
if ($Net::SSL::VERSION) {
    $SSL_CLASS = "Net::SSL";
}
elsif ($IO::Socket::SSL::VERSION) {
    $SSL_CLASS = "IO::Socket::SSL"; # it was already loaded
}
else {
    eval { require Net::SSL; };     # from Crypt-SSLeay
    if ($@) {
        require IO::Socket::SSL;
        $SSL_CLASS = "IO::Socket::SSL";
    }
    else {
        $SSL_CLASS = "Net::SSL";
    }
}
```

In centos 6.8, the code is like that:
```
# Figure out which SSL implementation to use
use vars qw($SSL_CLASS);
if ($IO::Socket::SSL::VERSION) {
    $SSL_CLASS = "IO::Socket::SSL"; # it was already loaded
}
elsif ($Net::SSL::VERSION) {
    $SSL_CLASS = "Net::SSL";
}
else {
    eval { require IO::Socket::SSL; };
    if ($@) {
        require Net::SSL;     # from Crypt-SSLeay
        $SSL_CLASS = "Net::SSL";
    }
    else {
        $SSL_CLASS = "IO::Socket::SSL";
    }
}
```

As you can see, the condition has changed. My http library loads 'IO::Socket::SSL' (mandatory) and also 'Net::SSL' (if you want to use p12 file). I can't use 'IO::Socket::SSL' for p12 file because the centos 6.x version is too old (version 1.31 and it seems i need the version >= 1.98).

So with centos 6.8 update, the plugin is not working anymore with p12. (because lwp (in my case) uses IO::Socket::SSL layer).

I don't know how to solve it right now. Maybe i need to look for the version and use different codes.  To solve the issue, you need to remove the 'use IO::Socket::SSL'. But it can break some other checks...

**Comment by cgagnaire** [comment]
Hi @cmeschin,
Is the problem still present ?
Thanks.

**Comment by cmeschin** [comment]
Hi,
It's not working on centOS7 with older or newer release of centreon-plugin.

**Comment by garnier-quentin** [comment]
Have you tried with http-backend=curl ?

**Comment by cmeschin** [comment]
Hi @garnier-quentin ,
I thought I tried but i tried with only `--ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE"`.
I just tried now and it not works but with another error compare to before...
Here is the result:
`/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname='mydomain' --port='443' --proto='https' --cert-file='/supervision/certificats/CRTXXX.p12' --cert-pwd='MyPassword' --cert-pkcs12 --warning='3' --critical='10' --timeout='30' --filter-perfdata=time --http-backend=curl --curl-opt="CURLOPT_SSL_VERIFYPEER => 0" --debug --verbose`

> UNKNOWN: curl perform error : Problem with the local SSL certificate
== Info: About to connect() to mydomain port 443 (#0)
== Info:   Trying MyDomain-IP...
== Info: Connected to mydomain (MyDomain-IP) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info: warning: ignoring value of ssl.verifyhost
== Info: unable to load client cert: -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)
== Info: NSS error -8018 (SEC_ERROR_UNKNOWN_PKCS11_ERROR)
== Info: Unknown PKCS #11 error.
== Info: Closing connection 0

I verified on both centOS6 and CentOS7, the nssdb (/etc/pki/nssdb) is empty.
Should I try to import cert in this db?

**Comment by garnier-quentin** [comment]
could you try with curl directly ? If you get it i could tell you options.

**Comment by garnier-quentin** [comment]
Have you some news ?

**Comment by garnier-quentin** [comment]
Have you done some test @cmeschin  ?

**Comment by cmeschin** [comment]
Hi @garnier-quentin ,
No, I've not take the time and at this time the service is disabled.
I'm not sure if the certificate is always valid.
I keep in mind to test this a day.
I'll send back here the results (good or bad).

**Comment by garnier-quentin** [comment]
Thanks for the feedback
