### ISSUE TITLE
snmp plugin - UNKNOWN status as CRITICAL 

### ISSUE THREAD

**Issue by hugleo** [centreon/centreon-plugins#4290]
Trying to output a critical output on errors instead of unknown:

centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=192.168.0.1 --snmp-version=v2c --snmp-community=public --oid='1.2.3.4.5.6.7.8.9.0' --change-exit=unknown=critical --opt-exit critical

UNKNOWN: SNMP GET Request: Cant get a single value. 

none of the options  --change-exit=unknown=critical or --opt-exit critical seems to work.

Would like something like this instead: CRITICAL: SNMP GET Request: Cant get a single value.

**Comment by garnier-quentin** [comment]
You can use following option: ```snmp-errors-exit=critical```
