### ISSUE TITLE
windows - new mode to detect dirty bit

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4299]
it should be useful to have a mode that will check on Windows OS the "Dirty Bit": https://learn.microsoft.com/it-it/windows-server/administration/windows-commands/fsutil-dirty

![image](https://user-images.githubusercontent.com/6400595/227242533-2f5b2beb-6a75-4807-8936-b7947292c09a.png)

It could be useful to add a new mode for Windows monitoring using wsman and local (agent)

**Comment by garnier-quentin** [comment]
Why not. but you can use the cmd-return mode on local no ? if dirty, maybe it's return a value > 0

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
