### ISSUE TITLE
Icingaweb2: No Perfdata Values present

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#430]
Hi,

I use your great plugin suite at icinga2. I´ve defined a command at icinga2 as follows:

object CheckCommand "centreon-snmp-load" {
   import "plugin-check-command"

   command = [ "/usr/lib/nagios/custom/centreon-plugins/centreon_plugins.pl"]
   arguments = {
        "--plugin" = "os::linux::snmp::plugin"
        "--mode" = "load"
        "--hostname" = "$address$"
        "--snmp-version" = "2c"
        "--snmp-community" = "public"
        "--warning" = "$snmp_warn$"
        "--critical" = "$snmp_crit$"
   }
}

But at Icingaweb2 there isn´t displayed any perfdata value for critical and warning. The values are recognized by icinga2, but the output seems broken: it´s displayed a 0.
![zwischenablage01](https://cloud.githubusercontent.com/assets/4061954/16330639/13f51ce6-39eb-11e6-9e9a-290ebe450f07.png)

**Comment by garnier-quentin** [comment]
Thanks for using the plugins. Maybe icinga2 doesn't manage range threshold. But i have a solution :), try to add following option:  --range-perfdata=1 (or --range-perfdata=2)

**Comment by benhartwich** [comment]
Thanks, this works!

**Comment by garnier-quentin** [comment]
Thanks for the feedback!

**Comment by benhartwich** [comment]
There´s just another problem. The values are tranfered wrong: If I set 
    vars.snmp_warn = "700"
    vars.snmp_crit = "800"
at snmp-memory I get 	54,58 GiB for warning and	62,38 GiB for critical.

**Comment by garnier-quentin** [comment]
Could you give me the command line used ? I don't understand the 700 for the load :)

**Comment by benhartwich** [comment]
Command:
```
object CheckCommand "centreon-snmp-memory" {
   import "plugin-check-command"

   command = [ "/usr/lib/nagios/custom/centreon-plugins/centreon_plugins.pl"]
   arguments = {
        "--plugin" = "os::linux::snmp::plugin"
        "--mode" = "memory"
        "--hostname" = "$address$"
        "--snmp-version" = "2c"
        "--snmp-community" = "public"
        "--warning" = "$snmp_warn$"
        "--critical" = "$snmp_crit$"
        "--range-perfdata" = "1"
   }
}
```
Service:
```
object Service "snmp-memory" {
    host_name      = "CMS Test"
    vars.snmp_warn = "700"
    vars.snmp_crit = "800"
    check_command  = "centreon-snmp-memory"
}
```
Or do you need anything else?

**Comment by garnier-quentin** [comment]
The threshold is in '%'. So you want 700%.

**Comment by benhartwich** [comment]
Ah, thanks!
