### ISSUE TITLE
UNKNOWN: command execution error [exit code: 127] in os::linux::local::plugin --mode=open-files

### ISSUE THREAD

**Issue by Hardik-Balar** [centreon/centreon-plugins#4312]
Today, I face one issue related to centreon linux ssh Plugin-Pack. Issue is whenever I user below for open-file Command it throw "**command execution error [exit code: 127]**"  this happens  while that command is used for **centos 7** operating system. However, this command works perfectly without any error for **Ubuntu** system.

**Command** : `/usr/lib/centreon/plugins//centreon_linux_ssh.pl --plugin=os::linux::local::plugin --mode=open-files --hostname='192.168.152.25' --ssh-backend='libssh' --ssh-username='username' --ssh-password='' --ssh-port='22' --ssh-priv-key=keypath --filter-username='' --filter-appname='' --filter-pid='' --warning-files-open='' --critical-files-open='' --verbose --use-new-perfdata`

**Output** :- command execution error [exit code: 127]
**Centreon version** : 22.10.7
**OS** : centos 7

**Comment by garnier-quentin** [comment]
Maybe the --debug can help. From that server, is it working with ssh command line ?

**Comment by Hardik-Balar** [comment]
> Maybe the --debug can help. From that server, is it working with ssh command line ?

Nope, even not working with ssh command line

**Comment by gitbnitin** [comment]
[centreon-engine@centreon ~]$ /usr/lib/centreon/plugins//centreon_linux_ssh.pl --plugin=os::linux::local::plugin --mode=open-files --hostname='172.16.174.68' --ssh-backend='libssh' --ssh-username='ro_centreon' --ssh-password='' --ssh-port='22' --ssh-priv-key=/var/lib/centreon-engine/.ssh/id_ed25519 --filter-username='' --filter-appname='' --filter-pid='' --warning-files-open='' --critical-files-open='' --verbose --use-new-perfdata
UNKNOWN: command execution error [exit code: 127]
[centreon-engine@centreon ~]$

**Comment by garnier-quentin** [comment]
If it's not working with the ssh cli directly, it cannot work with the plugin

**Comment by gitbnitin** [comment]
> I understand. But as i said, if it's not working with ssh cli. it cannot work with the plugin

Right, and that is why I thought I should report it here so that a contributor could have a look at it.

**Comment by gitbnitin** [comment]
> I understand. But as i said, if it's not working with ssh cli. it cannot work with the plugin

Right, and that is why I thought I should report it here so that a contributor could have a look at it.

**Comment by gitbnitin** [comment]
@garnier-quentin why this has been closed? Do we have any solution for this?

**Comment by garnier-quentin** [comment]
As i said i dont have a solution if you cant make it work with ssh cli.

**Comment by gitbnitin** [comment]
Hi @garnier-quentin the output of lsof works fine on centos, however, this plugin doesn't seem to be working is what I am saying. This means to me that we are missing something in the plugin specifically for CentOS.  If you can't make it work, that is fine, but what is the meaning of closing the issue without any meaningful closure?

**Comment by gitbnitin** [comment]
[centreon-engine@centreon ~]$ /usr/lib/centreon/plugins//centreon_linux_ssh.pl --plugin=os::linux::local::plugin --mode=open-files
OK: current open files: 221 | 'system.files.open.count'=221;;;0;

**Comment by gitbnitin** [comment]
--debug
UNKNOWN: command execution error [exit code: 127]
bash: lsof: command not found



monitored host result

[ro_user_centreon@host ~]$ which lsof
/usr/sbin/lsof
[ro_user_centreon@host ~]$

**Comment by gitbnitin** [comment]
it got resolved by a change in plugin file. Nevermind
