### ISSUE TITLE
[PLUGIN] CrossinG by ChampsVision

### ISSUE THREAD

**Issue by anthonyBertrant** [centreon/centreon-plugins#4316]
Hello,

Can we make a plugin to poll the secure exchange gateway made by the french compagny ChapsVision ?

Due to hardening mesures, snmpwalk command cannot work on the gateway.

Here are the MIB informations provided by the compagny:

Nombre total de fichiers traités par la chaîne de traitements A->B 1.3.6.1.4.1.50853.1.3.1.1
Nombre total de fichiers acceptés par la chaîne de traitements A->B 1.3.6.1.4.1.50853.1.3.1.2
Nombre total de fichiers rejetés par la chaîne de traitements A->B 1.3.6.1.4.1.50853.1.3.1.3
Nombre total de fichiers convertis par la chaîne de traitements A->B 1.3.6.1.4.1.50853.1.3.1.4

Nombre total de fichiers traités par la chaîne de traitements B->A 1.3.6.1.4.1.50853.1.3.2.1
Nombre total de fichiers acceptés par la chaîne de traitements B->A 1.3.6.1.4.1.50853.1.3.2.2
Nombre total de fichiers rejetés par la chaîne de traitements B->A 1.3.6.1.4.1.50853.1.3.2.3
Nombre total de fichiers convertis par la chaîne de traitements B->A 1.3.6.1.4.1.50853.1.3.2.4

Each of these MIB, return an integer. I think we can make 1 service, by line. Exemple:
service 1: number of files processed by A to B
service 2: number of files accepted by A to B
service 3: number of files rejected by A to B
and so on.

Thanks for your help. Moreover, I'll be glad to help you in anyway I can.

Regards

**Comment by garnier-quentin** [comment]
Could you add it in following issue ? https://github.com/centreon/centreon-plugins/issues/4315
