### ISSUE TITLE
Cisco C9300 Temp Inlet Sensor warning issue

### ISSUE THREAD

**Issue by coucou2000** [centreon/centreon-plugins#4323]
Hi,

I keep getting the warning alert on my Cisco C9300 Temp Inlet Sensor, when the temp is at 27 C.

WARNING: Sensor 'Switch 1 - C9300L-48P-4X - Temp Inlet Sensor 0/1011' is 27 C
Environment type: other
Checking fans

Usually, the warning threshold on the switch is at 46 C

C9300#show environment temperature
Switch 1: SYSTEM TEMPERATURE is OK
Inlet Temperature Value: 27 Degree Celsius
Temperature State: GREEN
Yellow Threshold : 46 Degree Celsius
Red Threshold    : 56 Degree Celsius

SNMPv2-SMI::enterprises.9.9.91.1.2.1.1.4.1011.1 = INTEGER: 56
SNMPv2-SMI::enterprises.9.9.91.1.2.1.1.4.1011.2 = INTEGER: 46

Can you take a look ?

Thanks

**Comment by coucou2000** [comment]
Thanks for your reply.

It's a Cisco issue or a plugin issue ? 

Could you show how to exlude this component ?

**Comment by coucou2000** [comment]
I suppose the filter will exclude all the temp sensor. Is there a way to just exclude the one have issu : Temp Inlet Sensor

**Comment by garnier-quentin** [comment]
```--filter='sensor,Switch 1 - C9300L-48P-4X - Temp Inlet Sensor 0/1011'  --add-name-instance```

**Comment by coucou2000** [comment]
Thank you very much !
