### ISSUE TITLE
Isilon plugin disk status do not show Location or Device when it is in 'REPLACE'

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#4327]
## Bug/Question

Plugin : storage::emc::isilon::snmp::plugin
Version : latest from git repository
Storage : Dell EMC Isilon A200 node, OneFS 9.2.1.0

**Context**
When we check Disk component on the storage node, it do not show the device or location of a faulty drive. For example on the node below we have a disk in REPLACE mode (faulty), on location A1.

Below the result from "isi device drive list" on the node iteself

isi device drive list
Lnn  Location  Device    Lnum  State   Serial       Sled
34   Bay  1    /dev/da1  15    L3      xxxxxx N/A
34   Bay  2    -         N/A   EMPTY                N/A
34   Bay  A0   /dev/da9  7     HEALTHY xxxxxx A
**34   Bay  A1   -         N/A    REPLACE              A**
34   Bay  A2   /dev/da10 6     HEALTHY xxxxxx A
34   Bay  B0   /dev/da3  13    HEALTHY xxxxxx B
34   Bay  B1   /dev/da11 5     HEALTHY xxxxxx B
34   Bay  B2   /dev/da4  12    HEALTHY xxxxxx B
34   Bay  C0   /dev/da12 4     HEALTHY xxxxxx C
34   Bay  C1   /dev/da5  11    HEALTHY xxxxxx C
34   Bay  C2   /dev/da13 3     HEALTHY xxxxxx C
34   Bay  D0   /dev/da6  10    HEALTHY xxxxxx D
34   Bay  D1   /dev/da14 2     HEALTHY xxxxxx D
34   Bay  D2   /dev/da7  9      HEALTHY xxxxxx D
34   Bay  E0   /dev/da15 1      HEALTHY xxxxxx E
34   Bay  E1   /dev/da8  8       HEALTHY xxxxxx E
34   Bay  E2   /dev/da16 0      HEALTHY xxxxxx E

And below the output (in verbose) from the plugin

centreon_plugins.pl --plugin storage::emc::isilon::snmp::plugin --mode hardware --component disk --hostname x.x.x.x --verbose
CRITICAL: Disk '' status is 'REPLACE' | 'count_disk'=16;;;;
Checking disks
disk 'da1' status is 'L3' [instance = 1] [logical = 15] [chassis = 0]
disk 'da9' status is 'HEALTHY' [instance = 3] [logical = 7] [chassis = 0]
**disk '' status is 'REPLACE' [instance = 4] [logical = 251] [chassis = 0]**
disk 'da10' status is 'HEALTHY' [instance = 5] [logical = 6] [chassis = 0]
disk 'da3' status is 'HEALTHY' [instance = 6] [logical = 13] [chassis = 0]
disk 'da11' status is 'HEALTHY' [instance = 7] [logical = 5] [chassis = 0]
disk 'da4' status is 'HEALTHY' [instance = 8] [logical = 12] [chassis = 0]
disk 'da12' status is 'HEALTHY' [instance = 9] [logical = 4] [chassis = 0]
disk 'da5' status is 'HEALTHY' [instance = 10] [logical = 11] [chassis = 0]
disk 'da13' status is 'HEALTHY' [instance = 11] [logical = 3] [chassis = 0]
disk 'da6' status is 'HEALTHY' [instance = 12] [logical = 10] [chassis = 0]
disk 'da14' status is 'HEALTHY' [instance = 13] [logical = 2] [chassis = 0]
disk 'da7' status is 'HEALTHY' [instance = 14] [logical = 9] [chassis = 0]
disk 'da15' status is 'HEALTHY' [instance = 15] [logical = 1] [chassis = 0]
disk 'da8' status is 'HEALTHY' [instance = 16] [logical = 8] [chassis = 0]
disk 'da16' status is 'HEALTHY' [instance = 17] [logical = 0] [chassis = 0]

**Question**
It is possible to have the Location (same as Isilon's isi command) show on the output of the plugin ? The best for me is to have an answer like "disk 'A1' status is 'REPLACE'"

Thank you very much
Best regards
stefano

**Comment by garnier-quentin** [comment]
Could you provide the snmpwalk of following branch: .1.3.6.1.4.1.12124.2.52.1 ?

**Comment by stefanotoro** [comment]
Hello, here is for you.
Thank you !

snmpwalk -v 2c -c public x.x.x.x.1.3.6.1.4.1.12124.2.52.1
SNMPv2-SMI::enterprises.12124.2.52.1.1.1 = INTEGER: 1
SNMPv2-SMI::enterprises.12124.2.52.1.1.3 = INTEGER: 3
SNMPv2-SMI::enterprises.12124.2.52.1.1.4 = INTEGER: 4
SNMPv2-SMI::enterprises.12124.2.52.1.1.5 = INTEGER: 5
SNMPv2-SMI::enterprises.12124.2.52.1.1.6 = INTEGER: 6
SNMPv2-SMI::enterprises.12124.2.52.1.1.7 = INTEGER: 7
SNMPv2-SMI::enterprises.12124.2.52.1.1.8 = INTEGER: 8
SNMPv2-SMI::enterprises.12124.2.52.1.1.9 = INTEGER: 9
SNMPv2-SMI::enterprises.12124.2.52.1.1.10 = INTEGER: 10
SNMPv2-SMI::enterprises.12124.2.52.1.1.11 = INTEGER: 11
SNMPv2-SMI::enterprises.12124.2.52.1.1.12 = INTEGER: 12
SNMPv2-SMI::enterprises.12124.2.52.1.1.13 = INTEGER: 13
SNMPv2-SMI::enterprises.12124.2.52.1.1.14 = INTEGER: 14
SNMPv2-SMI::enterprises.12124.2.52.1.1.15 = INTEGER: 15
SNMPv2-SMI::enterprises.12124.2.52.1.1.16 = INTEGER: 16
SNMPv2-SMI::enterprises.12124.2.52.1.1.17 = INTEGER: 17
SNMPv2-SMI::enterprises.12124.2.52.1.2.1 = INTEGER: 15
SNMPv2-SMI::enterprises.12124.2.52.1.2.3 = INTEGER: 7
SNMPv2-SMI::enterprises.12124.2.52.1.2.4 = INTEGER: 251
SNMPv2-SMI::enterprises.12124.2.52.1.2.5 = INTEGER: 6
SNMPv2-SMI::enterprises.12124.2.52.1.2.6 = INTEGER: 13
SNMPv2-SMI::enterprises.12124.2.52.1.2.7 = INTEGER: 5
SNMPv2-SMI::enterprises.12124.2.52.1.2.8 = INTEGER: 12
SNMPv2-SMI::enterprises.12124.2.52.1.2.9 = INTEGER: 4
SNMPv2-SMI::enterprises.12124.2.52.1.2.10 = INTEGER: 11
SNMPv2-SMI::enterprises.12124.2.52.1.2.11 = INTEGER: 3
SNMPv2-SMI::enterprises.12124.2.52.1.2.12 = INTEGER: 10
SNMPv2-SMI::enterprises.12124.2.52.1.2.13 = INTEGER: 2
SNMPv2-SMI::enterprises.12124.2.52.1.2.14 = INTEGER: 9
SNMPv2-SMI::enterprises.12124.2.52.1.2.15 = INTEGER: 1
SNMPv2-SMI::enterprises.12124.2.52.1.2.16 = INTEGER: 8
SNMPv2-SMI::enterprises.12124.2.52.1.2.17 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.1 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.3 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.4 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.5 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.6 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.7 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.8 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.9 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.10 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.11 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.12 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.13 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.14 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.15 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.16 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.3.17 = INTEGER: 0
SNMPv2-SMI::enterprises.12124.2.52.1.4.1 = STRING: "da1"
SNMPv2-SMI::enterprises.12124.2.52.1.4.3 = STRING: "da9"
SNMPv2-SMI::enterprises.12124.2.52.1.4.4 = ""
SNMPv2-SMI::enterprises.12124.2.52.1.4.5 = STRING: "da10"
SNMPv2-SMI::enterprises.12124.2.52.1.4.6 = STRING: "da3"
SNMPv2-SMI::enterprises.12124.2.52.1.4.7 = STRING: "da11"
SNMPv2-SMI::enterprises.12124.2.52.1.4.8 = STRING: "da4"
SNMPv2-SMI::enterprises.12124.2.52.1.4.9 = STRING: "da12"
SNMPv2-SMI::enterprises.12124.2.52.1.4.10 = STRING: "da5"
SNMPv2-SMI::enterprises.12124.2.52.1.4.11 = STRING: "da13"
SNMPv2-SMI::enterprises.12124.2.52.1.4.12 = STRING: "da6"
SNMPv2-SMI::enterprises.12124.2.52.1.4.13 = STRING: "da14"
SNMPv2-SMI::enterprises.12124.2.52.1.4.14 = STRING: "da7"
SNMPv2-SMI::enterprises.12124.2.52.1.4.15 = STRING: "da15"
SNMPv2-SMI::enterprises.12124.2.52.1.4.16 = STRING: "da8"
SNMPv2-SMI::enterprises.12124.2.52.1.4.17 = STRING: "da16"
SNMPv2-SMI::enterprises.12124.2.52.1.5.1 = STRING: "L3"
SNMPv2-SMI::enterprises.12124.2.52.1.5.3 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.4 = STRING: "REPLACE"
SNMPv2-SMI::enterprises.12124.2.52.1.5.5 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.6 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.7 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.8 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.9 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.10 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.11 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.12 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.13 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.14 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.15 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.16 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.5.17 = STRING: "HEALTHY"
SNMPv2-SMI::enterprises.12124.2.52.1.6.1 = STRING: "SAMSUNG PA35N400 EMC400"
SNMPv2-SMI::enterprises.12124.2.52.1.6.3 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.4 = ""
SNMPv2-SMI::enterprises.12124.2.52.1.6.5 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.6 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.7 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.8 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.9 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.10 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.11 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.12 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.13 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.14 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.15 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.16 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.6.17 = STRING: "HUS726040ALN610"
SNMPv2-SMI::enterprises.12124.2.52.1.7.1 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.3 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.4 = ""
SNMPv2-SMI::enterprises.12124.2.52.1.7.5 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.6 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.7 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.8 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.9 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.10 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.11 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.12 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.13 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.14 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.15 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.16 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.7.17 = STRING: "xxxxx"
SNMPv2-SMI::enterprises.12124.2.52.1.8.1 = STRING: "EQL3"
SNMPv2-SMI::enterprises.12124.2.52.1.8.3 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.4 = ""
SNMPv2-SMI::enterprises.12124.2.52.1.8.5 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.6 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.7 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.8 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.9 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.10 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.11 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.12 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.13 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.14 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.15 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.16 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.8.17 = STRING: "APGNTDY0"
SNMPv2-SMI::enterprises.12124.2.52.1.9.1 = Counter64: 400000000000
SNMPv2-SMI::enterprises.12124.2.52.1.9.3 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.4 = Counter64: 0
SNMPv2-SMI::enterprises.12124.2.52.1.9.5 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.6 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.7 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.8 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.9 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.10 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.11 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.12 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.13 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.14 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.15 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.16 = Counter64: 500098378752
SNMPv2-SMI::enterprises.12124.2.52.1.9.17 = Counter64: 500098378752

**Comment by garnier-quentin** [comment]
As you can see we don't have the bay information. The index should be the ```diskBay```. But it doesn't match your Ax, Bx,...

**Comment by stefanotoro** [comment]
So, if i understand correctly, it's not possible to show such information. Right ?

**Comment by stefanotoro** [comment]
Okay thank you very much

**Comment by garnier-quentin** [comment]
You can try to ask the isilon support about it.
