### ISSUE TITLE
SNMP Problem monitoring CPU et Memory on Switch Unify

### ISSUE THREAD

**Issue by SAMOACEN** [centreon/centreon-plugins#4332]
Hello, 

I have a problem for the monitoring of my switch Unify model US-8-150W, US-48-500W, USW-Pro-48-PoE.
Indeed, for the CPU and memory probes i get this error : UNKNOWN : SNMP GET Request : Cant get a single value.

Do you have an idea of what could be the source of this problem ?

I tried to search about the OID which could not be the same on centreon and unify but im not sure.

Thanks for your help

![Capture d’écran 2023-04-05 110505](https://user-images.githubusercontent.com/130155265/230610451-eea7eb70-96e5-4c17-8dd9-ca4743c2b5d2.png)

**Comment by SAMOACEN** [comment]
![image](https://user-images.githubusercontent.com/130155265/231494918-041e703f-7dc4-4f23-b1f3-57465a3e7bcd.png)
 I have this answer when I try the command

**Comment by SAMOACEN** [comment]
![image](https://user-images.githubusercontent.com/130155265/231495369-56a60dde-22da-480a-aea3-2af25e6d55f7.png)

I have this answer when i try the command.

**Comment by garnier-quentin** [comment]
It should work with the right community

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time.Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the issue.
