### ISSUE TITLE
Cisco Nexus - new mode to monitor FEX status

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4355]
Cisco Nexus switches can have FEX (https://www.cisco.com/c/en/us/products/collateral/switches/nexus-5000-series-switches/data_sheet_c78-657397.html). Monitoring the environment using SNMP includes also FEX devices. But if a FEX is in status offline then the SNMP is not reporting this problem, because all SNMP informations for the FEX will be not more available.

https://community.cisco.com/t5/server-networking/n5k-monitor-fex-status-via-snmp/td-p/1694424

To monitor the FEX statuses we can use SSH with the command "show fex"
![image](https://user-images.githubusercontent.com/6400595/232237374-34042675-a355-4d66-881a-38e7f62f260c.png)

Could you add this mode on network::cisco::standard::ssh::plugin plugin?
Did you need some other informations?

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
