### ISSUE TITLE
Certificate faillure

### ISSUE THREAD

**Issue by frederico2023** [centreon/centreon-plugins#4356]
Hi,

im trying to check certificate validity but cannot get it working :

/usr/lib/centreon/plugins/centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --mode=certificate --hostname=xxxxx --port=5432 --custommode=tcp --starttls=postgres --warning-status='%{expiration} < 30' --critical-status='%{expiration} < 15' --ssl-opt="SSL_verify_mode => SSL_VERIFY_NONE" --ssl-ignore-errors

Result :

UNKNOWN: Can't locate object method "peer_certificate" via package "IO::Socket::INET" at /usr/lib/centreon/plugins/centreon_protocol_x509.pl line 851.

version 21.10 
rpm centreon-plugin-Applications-Protocol-X509-20230215-164619.el7.noarch

**Comment by frederico2023** [comment]
Is it possible to make an evolution of the plugin?

**Comment by garnier-quentin** [comment]
Right now, it's not planned.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This enhancement request seems old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
