### ISSUE TITLE
[apps::backup::rubrik::restapi::plugin] Add (or/end) move to GraphQL request

### ISSUE THREAD

**Issue by jonans91** [centreon/centreon-plugins#4357]
Hi,

Rubrik is going to move from traditionnal REST API requests to GraphQL in order to monitor their platforms, and because the management will move from the local appliances to their cloud platform (Rubrik Security Cloud). 

So it means that we will not be able to use the today plugin and send calls on local systems and we'll need to use the cloud one (and the API are not the same and will be derepecated)

Could we discuss about updating / migrating the actual plugin to make it work using GraphQL API ? 

Merci !

(en français c'est possible aussi)

**Comment by garnier-quentin** [comment]
Of course we could manage that new API.

**Comment by jonans91** [comment]
Hi Quentin,
I'm available this week if you want to schedule a quick meeting about the Rubrik solution. 
There are changes about the way to monitor Rubrik appliances from the RSC (and it is quite simple) :)

++

**Comment by garnier-quentin** [comment]
You can send me an email to give some date.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Can you confirm to me this enhancement request had been handle in this [commit](https://github.com/centreon/centreon-plugins/commit/6143363aac4a017cfa8bad320e2c5b4befc45660#diff-231e828c7dad7b096d2c17f5e2a7dd8a95c20204b8f1f97c221b5ee2f9708d7e)?
Thank you for your understanding.
