### ISSUE TITLE
Exclude the check of "System Reserved" partition in a Windows server

### ISSUE THREAD

**Issue by lzmarouane** [centreon/centreon-plugins#4358]
Hi,
how can i  exclude the check of "System Reserved" partition in a Windows server using the NSClient++ REST API 

I used this command to exlude some partitions
`/usr/lib/centreon/plugins/centreon_nsclient_restapi.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname='x' --port='8443' --proto='https' --legacy-password='x' --http-backend=curl --insecure --command=check_drivesize --arg="drive=*" --arg="perf-config=used(unit:G)used %(ignored:true)" --arg="filter=type = 'fixed' and name not regexp '.*yst.*'" --arg="warning=total_used>80%" --arg="critical=total_used>90%"  --exclude-drive=Z`

But it doesn't work for "System Reserved" partition"

can you help me ??

**Comment by garnier-quentin** [comment]
It's not a centreon-plugins issue. Check nscp github and officiel doc

**Comment by lzmarouane** [comment]
Thank you @garnier-quentin
