### ISSUE TITLE
apps::protocols::dns::plugin - Building array of nameservers

### ISSUE THREAD

**Issue by benhartwich** [centreon/centreon-plugins#4359]
Hi,

how can I build an array at centreon plugin to have different nameservers at the command line, e.g.:

`./centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request  --nameservers=8.8.8.8 1.1.1.1 208.67.222.220 --search-type=A --search=heise.de`

I´ve tried [ ], "" , ; but nothing works. Any hint appreciated!

**Comment by garnier-quentin** [comment]
It should be like that:
```
--nameservers='8.8.8.8' --nameservers='1.1.1.1' --nameservers='208.67.222.220'```
```

I could add a system with coma also: ```--nameservers=8.8.8.8,1.1.1.1,208.67.222.220```

**Comment by benhartwich** [comment]
Thanks - with coma it doesn´t work:

`./centreon_plugins.pl --plugin=apps::protocols::dns::plugin --mode=request  --nameservers=8.8.8.8,1.1.1.1 --search-type=A --search=heise.de`

unresolvable name: 8.8.8.8,1.1.1.1 at /home/nagios/centreon-plugins/src/apps/protocols/dns/lib/dns.pm line 92.
CRITICAL: DNS query failed: no nameservers

With single --nameservers Attributes it seems to work. Thanks!

**Comment by garnier-quentin** [comment]
Yes it won't work with coma but i could add it.

**Comment by benhartwich** [comment]
Ah ok, sorry, missunderstood - yes, this would be great!

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4362
