### ISSUE TITLE
[plugin] APC Netbotz

### ISSUE THREAD

**Issue by jgaret** [centreon/centreon-plugins#436]
Hello,

Would it be possible to add support for APC netbotz monitoring (Temperature and Humidity sensors) ? It seems closed to hardware::pdu::apc::snmp::plugin -mode hardware with component temperature) but it can have many sensors attached.

A functionnal nagios check exists (in python) here : https://github.com/tomerazran/nagios-plugins/tree/master/check_netbotz. It would be nice to have it in centreon plugins.

**Comment by garnier-quentin** [comment]
HI,

I need a complete snmpwalk and the mib ;)

**Comment by jgaret** [comment]
Hi,

It seems it is the PowerNet MIB, like the one for PDUs.

Here a [complete walk of a netbotz](https://gist.github.com/jgaret/28370c9d2d1e76d62810de9996ac575b).
I am not sure this is exactly what you were looking for, but if you give me exact options for snmpwalk, I can do that.

**Comment by garnier-quentin** [comment]
Have you tried to APC SNMP plugin ? To see if it's working.

**Comment by jgaret** [comment]
Yes, I did and it did not work. I guess it's related to the multiple sensors connected to the netbotz. I think OIDs are different.I will try to check that.

**Comment by garnier-quentin** [comment]
Ref de7d61e064e637630224f60e3c64e457ed0b3dd7
