### ISSUE TITLE
apps::protocols::x509::plugin UNKNOWN: OK

### ISSUE THREAD

**Issue by mqssi** [centreon/centreon-plugins#4361]
Hi,

When I use : 

```
/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=ce
rtificate --custommode=https --hostname=www.google.com --port=443 --warning-status='%{expiration} < 20' --critical-status='%{expiration}
 < 10'
```

I get (which is fine) :  

```
OK: Certificate for 'www.google.com' expires in '63' days [2023-06-20T16:54:57Z] - Issuer: '/C=US/O=Google Trust Services LLC/CN=GTS CA 
1C3'
```

However for another specifc domain : 

```
/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=ce
rtificate --custommode=https --hostname=www.momaco.fr --port=443 --warning-status='%{expiration} < 20' --critical-status='%{expiration} 
< 10'
```

I get : 

`UNKNOWN: OK`

The plugin doesn't output the real cert cotentn only for this specific domain.

Using openssl directly works fine :

` openssl s_client -servername momaco.fr -connect momaco.fr:443 | openssl x509 -noout -dates`

Any ideas? Thank you in advance

**Comment by garnier-quentin** [comment]
Please use the backend curl: ```--http-backend=curl```

**Comment by garnier-quentin** [comment]
It needs a new curl version. I think you should use the custommode=tcp maybe

**Comment by mqssi** [comment]
Indeed, it works fine this way!

Thank you, have a nice day :)
