### ISSUE TITLE
Paloalto PA-3260 snmp error for the MEMORY mode

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#4371]
Hello,

when I request the memory for a paloalto version PA-820 I get the result.
If I do the same but for a paloalto version PA-3260 I get a timeout on the snmp.
If I replace the memory mode with cpu, hardware, sessions... for the PA-3260 then I have a result. (there is no connection problem)

# Check
for PA-820
centreon_plugins.pl --plugin="network::paloalto::snmp::plugin" --mode="memory" --snmp-version="2c"  --hostname=x.x.x.x
OK: Storage 'Slot-1 Management Memory' Usage Total: 3.93 GB Used: 2.08 GB (52.84%) Free: 1.85 GB (47.16%)

for PA-3260
centreon_plugins.pl --plugin="network::paloalto::snmp::plugin" --mode="memory" --snmp-version="2c"  --hostname=x.x.x.x
UNKNOWN: SNMP Table Request: Timeout

# SNMP Output
when I query the list for hrStorage on a PA-820 I get this result

HOST-RESOURCES-MIB::hrStorageAllocationUnits.1010 = INTEGER: 128 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1011 = INTEGER: 2048 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1012 = INTEGER: 4977 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1020 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1030 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1040 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1041 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1042 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageDescr.1010 = STRING: Slot-1 Data Processor-0 Packet Descriptors
HOST-RESOURCES-MIB::hrStorageDescr.1011 = STRING: Slot-1 Data Processor-0 Hardware Packet Buffers
HOST-RESOURCES-MIB::hrStorageDescr.1012 = STRING: Slot-1 Data Processor-0 Software Packet Buffers
HOST-RESOURCES-MIB::hrStorageDescr.1020 = STRING: Slot-1 Management Memory
HOST-RESOURCES-MIB::hrStorageDescr.1030 = STRING: Slot-1 Management Swap
HOST-RESOURCES-MIB::hrStorageDescr.1040 = STRING: Slot-1 Management Config Partition
HOST-RESOURCES-MIB::hrStorageDescr.1041 = STRING: Slot-1 Management Log Partition
HOST-RESOURCES-MIB::hrStorageDescr.1042 = STRING: Slot-1 Management Root Partition
HOST-RESOURCES-MIB::hrStorageIndex.1010 = INTEGER: 1010
HOST-RESOURCES-MIB::hrStorageIndex.1011 = INTEGER: 1011
HOST-RESOURCES-MIB::hrStorageIndex.1012 = INTEGER: 1012
HOST-RESOURCES-MIB::hrStorageIndex.1020 = INTEGER: 1020
HOST-RESOURCES-MIB::hrStorageIndex.1030 = INTEGER: 1030
HOST-RESOURCES-MIB::hrStorageIndex.1040 = INTEGER: 1040
HOST-RESOURCES-MIB::hrStorageIndex.1041 = INTEGER: 1041
HOST-RESOURCES-MIB::hrStorageIndex.1042 = INTEGER: 1042
HOST-RESOURCES-MIB::hrStorageSize.1010 = INTEGER: 229376
HOST-RESOURCES-MIB::hrStorageSize.1011 = INTEGER: 57344
HOST-RESOURCES-MIB::hrStorageSize.1012 = INTEGER: 97750
HOST-RESOURCES-MIB::hrStorageSize.1020 = INTEGER: 4119516
HOST-RESOURCES-MIB::hrStorageSize.1030 = INTEGER: 6104084
HOST-RESOURCES-MIB::hrStorageSize.1040 = INTEGER: 19850896
HOST-RESOURCES-MIB::hrStorageSize.1041 = INTEGER: 180938204
HOST-RESOURCES-MIB::hrStorageSize.1042 = INTEGER: 9929572
HOST-RESOURCES-MIB::hrStorageType.1010 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.1011 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.1012 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.1020 = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageType.1030 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.1040 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.1041 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.1042 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageUsed.1010 = INTEGER: 5
HOST-RESOURCES-MIB::hrStorageUsed.1011 = INTEGER: 1
HOST-RESOURCES-MIB::hrStorageUsed.1012 = INTEGER: 1
HOST-RESOURCES-MIB::hrStorageUsed.1020 = INTEGER: 2080492
HOST-RESOURCES-MIB::hrStorageUsed.1030 = INTEGER: 607992
HOST-RESOURCES-MIB::hrStorageUsed.1040 = INTEGER: 5660492
HOST-RESOURCES-MIB::hrStorageUsed.1041 = INTEGER: 2835336
HOST-RESOURCES-MIB::hrStorageUsed.1042 = INTEGER: 3519712

when I request the list for hrStorage on a PA-3260 I get this result
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1010 = INTEGER: 128 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1011 = INTEGER: 2048 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1012 = INTEGER: 4412 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.20 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.30 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.40 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.41 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.42 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageDescr.1010 = STRING: Slot-1 Data Processor-0 Packet Descriptors
HOST-RESOURCES-MIB::hrStorageDescr.1011 = STRING: Slot-1 Data Processor-0 Hardware Packet Buffers
HOST-RESOURCES-MIB::hrStorageDescr.1012 = STRING: Slot-1 Data Processor-0 Software Packet Buffers
HOST-RESOURCES-MIB::hrStorageDescr.20 = STRING: Slot-0 Management Memory
HOST-RESOURCES-MIB::hrStorageDescr.30 = STRING: Slot-0 Management Swap
HOST-RESOURCES-MIB::hrStorageDescr.40 = STRING: Slot-0 Management Config Partition
HOST-RESOURCES-MIB::hrStorageDescr.41 = STRING: Slot-0 Management Log Partition
HOST-RESOURCES-MIB::hrStorageDescr.42 = STRING: Slot-0 Management Root Partition
HOST-RESOURCES-MIB::hrStorageIndex.1010 = INTEGER: 1010
HOST-RESOURCES-MIB::hrStorageIndex.1011 = INTEGER: 1011
HOST-RESOURCES-MIB::hrStorageIndex.1012 = INTEGER: 1012
HOST-RESOURCES-MIB::hrStorageIndex.20 = INTEGER: 20
HOST-RESOURCES-MIB::hrStorageIndex.30 = INTEGER: 30
HOST-RESOURCES-MIB::hrStorageIndex.40 = INTEGER: 40
HOST-RESOURCES-MIB::hrStorageIndex.41 = INTEGER: 41
HOST-RESOURCES-MIB::hrStorageIndex.42 = INTEGER: 42
HOST-RESOURCES-MIB::hrStorageSize.1010 = INTEGER: 552960
HOST-RESOURCES-MIB::hrStorageSize.1011 = INTEGER: 53248
HOST-RESOURCES-MIB::hrStorageSize.1012 = INTEGER: 362650
HOST-RESOURCES-MIB::hrStorageSize.20 = INTEGER: 16089656
HOST-RESOURCES-MIB::hrStorageSize.30 = INTEGER: 7996
HOST-RESOURCES-MIB::hrStorageSize.40 = INTEGER: 39562792
HOST-RESOURCES-MIB::hrStorageSize.41 = INTEGER: 131199224
HOST-RESOURCES-MIB::hrStorageSize.42 = INTEGER: 19719856
HOST-RESOURCES-MIB::hrStorageType.1010 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.1011 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.1012 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.20 = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageType.30 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.40 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.41 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.42 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageUsed.1010 = INTEGER: 5
HOST-RESOURCES-MIB::hrStorageUsed.1011 = INTEGER: 1
HOST-RESOURCES-MIB::hrStorageUsed.1012 = INTEGER: 26
HOST-RESOURCES-MIB::hrStorageUsed.20 = INTEGER: 4265224
HOST-RESOURCES-MIB::hrStorageUsed.30 = INTEGER: 0
HOST-RESOURCES-MIB::hrStorageUsed.40 = INTEGER: 5840224
HOST-RESOURCES-MIB::hrStorageUsed.41 = INTEGER: 4003224
HOST-RESOURCES-MIB::hrStorageUsed.42 = INTEGER: 6196608

## Difference
On a PA-820 it says .1020,1030,1040...
on a PA-3260 it says .20,30,40,...
this is the big difference in the snmp output.

## Question
is this a change that is necessary that the memory mode also works via snmp for a PA-3260 ?

regards,
Geert

**Comment by garnier-quentin** [comment]
Have you tried with option --snmp-autoreduce for memory ?

**Comment by gbin2265** [comment]
Yes, it works!

I was not aware of this option.

Thank you for the answer.

**Comment by garnier-quentin** [comment]
Thanks for the feedback
