### ISSUE TITLE
Issue with Dell ME4 Rest API plugin in Centreon

### ISSUE THREAD

**Issue by khalidbounoun** [centreon/centreon-plugins#4378]
I am facing an issue while using the Dell ME4 Rest API plugin in Centreon.
The API of the Dell ME4 console provides a self-signed certificate, which I have imported into my Centreon poller using the command "export HTTPS_CA_FILE=path-to-certificate". 
The checks are working fine when I run them directly from the poller, but they are failing when I try to run them from Centreon web. I am getting the error "UNKNOWN: 500 Can't connect to 10.x.x.x:443".

I have tried the following troubleshooting steps:

- Imported the self-signed certificate into the poller using the command "export HTTPS_CA_FILE=path-to-certificate"

- Checked the ownership and permissions of the certificate file by the user centreon-engine.

- Verified that the Dell ME4 console is accessible from the poller using the curl command.

Can you please help me resolve this issue?

**Comment by garnier-quentin** [comment]
Try to use the options: --insecure --http-backend=curl

**Comment by khalidbounoun** [comment]
It works ! thank you !
