### ISSUE TITLE
[network::cisco::standard::snmp] Add new macro for service discovery traffic

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#4379]
Hello !

On Cisco service discovery mode it, when scanning interface for adding traffic, it would be great to have a macro available with description in addition to "$name$" (the same thing as the content of "ifDesc")

Thanks a lot !

**Comment by garnier-quentin** [comment]
You can create your own command discovery and add following option:
```
--add-extra-oid='alias,.1.3.6.1.2.1.31.1.1.1.18'  --add-extra-oid='desc,.1.3.6.1.2.1.2.2.1.2'  
```
