### ISSUE TITLE
Transceiver values from Procurve switches do not update

### ISSUE THREAD

**Issue by Cynexxde** [centreon/centreon-plugins#4390]
With the plugin network::hp::procurve::snmp::plugin it is possible to read out the values of the transceivers (RX ,TX ,temperature, etc.). The problem is that the values are not updated automatically. Only when you connect via SSH and execute the command "show interfaces tranceiver detail", the values are updated. I contacted Aruba support about this and they gave me the feedback below. It looks like the plugin needs to update the values before reading them. Is it possible to include the mib to update the values as described? 

```
Hello ####,

Thank you for your time on call.
As discussed there are two options now.

One is to execute the show command from the switch CLI to fetch the transceiver values.
Second is to incorporate setting the below MIB in the SNMP monitoring tool and this should be set each and 
every time before we fetch the values of transceivers like temperature, voltage, Tx and RX powers etc :
setmib hpicfXcvrDiagnosticsUpdate.50 -i 1

where 50 is the port number of the transceiver.

On no response, will follow up on 02/05/2023 during business hours.

```

If you have any further questions, just ask. I am still in contact with Aruba.

**Comment by garnier-quentin** [comment]
Yes we can add a snmpset before.

**Comment by Cynexxde** [comment]
That would be awesome. Are you gonna get to that in the near future?

**Comment by Cynexxde** [comment]
Aruba Support asks for a status. Do you get to that in the near future? Do you think it's time to close the ticket with them?

**Comment by Cynexxde** [comment]
@garnier-quentin could you give me some feedback on this please?

**Comment by garnier-quentin** [comment]
Could you test it with that archive ? https://github.com/centreon/centreon-plugins/archive/refs/heads/hp-procurve-transceiver-snmpset.zip

**Comment by Cynexxde** [comment]
I get the following error message. I have replaced the folder \src\network\hp\procurve\snmp.

```
UNKNOWN: Cannot load module --mode.
Global symbol "$optical_ports" requires explicit package name (did you forget to declare "my $optical_ports"?) at /opt/openitc/nagios/libexec/centreon-plugins-test/network/hp/procurve/snmp/mode/interfaces.pm line 194.
Compilation failed in require at /opt/openitc/nagios/libexec/centreon-plugins-test/centreon/plugins/misc.pm line 222.
```

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition). I'll put the dev beginning proposed here in a backlog ticket and when enough votes will be set on this idea we'll inspect it again.
Thank you for your understanding.
