### ISSUE TITLE
Emerson/Vertiv energy station

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4394]
It should be nice to have a plugin to monitor power stations from Vertix (ex Emerson).
SNMP MIB: [EES-POWER-MIB.txt](https://github.com/centreon/centreon-plugins/files/11344808/EES-POWER-MIB.txt)

snmpwalk from a actual Vertiv device (netsure series):
[snmpwalk-netsure5000 - Copy.txt](https://github.com/centreon/centreon-plugins/files/11344918/snmpwalk-netsure5000.-.Copy.txt)

snmpwalk from a older series (Emerson):
[snmpwalk-emerson-old - Copy.txt](https://github.com/centreon/centreon-plugins/files/11344919/snmpwalk-emerson-old.-.Copy.txt)

The snmp mib is still the same, but the capabilities are different.

It should be nice to monitor:
![image](https://user-images.githubusercontent.com/6400595/234900018-a6214c27-995a-4b43-a2a4-33383d76b506.png)

**Comment by garnier-quentin** [comment]
I'm not working on it

**Comment by rmorandell-pgum** [comment]
https://github.com/centreon/centreon-plugins/pull/4518
