### ISSUE TITLE
New Plugin Pack for Bodet GNSS/NTP.

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#4395]
Hi,
Can you develop a plugin pack for a Bodet brand gnss/ntp probe, Netsilon model ?

https://www.bodet-time.com/fr/serveur-temps.html

It is monitorable via snmp : 
[Bodet_Netsilon_20220321.txt](https://github.com/centreon/centreon-plugins/files/11352801/Bodet_Netsilon_20220321.txt)

I send you the snmpwalk by mail.

Best regards,

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk ? 
```
snmpwalk -ObentU -v 2c IP .1 > bodet.snmpwalk
```

**Comment by gagzou** [comment]
Hi, the full snmpwalk was sent by email on July 9, 2023.
Best regards,

**Comment by gagzou** [comment]
Hi,
Do you need more information ?
Best regards,

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md)).

Thank you for your understanding.
