### ISSUE TITLE
New plugin for Rittal CMC

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4396]
It should be great to have a Plugin to monitor Rittal CMC sensors (https://www.rittal.com/de-de/products/PG0800ITINFRA1/PG1538ITINFRA1/PGR9560ITINFRA1)

SNMP MIB:
[RITTAL_CMC-III_MIB_V_3_17_00.zip](https://github.com/centreon/centreon-plugins/files/11359413/RITTAL_CMC-III_MIB_V_3_17_00.zip)

SNMP walk:
[rittal.txt](https://github.com/centreon/centreon-plugins/files/11359415/rittal.txt)

**Comment by rmorandell-pgum** [comment]
https://github.com/centreon/centreon-plugins/pull/4502
