### ISSUE TITLE
[hardware::ups::apc::snmp::plugin] --mode=input-lines: not compatible with APC Galaxy

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4397]
We have a problem with a APC UPS with mode input-lines, which is returning only the frequency, but voltage, status ecc are not working. Seem's that this APC uses different SNMP OID:
.1.3.6.1.4.1.318.1.1.1.3.2.1.0 = undef
.1.3.6.1.4.1.318.1.1.1.3.2.4.0 = 50
.1.3.6.1.4.1.318.1.1.1.3.2.5.0 = undef
.1.3.6.1.4.1.318.1.1.1.3.3.1.0 = undef
.1.3.6.1.4.1.318.1.1.1.3.3.4.0 = undef
.1.3.6.1.4.1.318.1.1.1.5.2.2.0 = undef
.1.3.6.1.4.1.318.1.1.1.5.2.3.0 = undef

The correct SNMP OIDs seems different:

- upsInput (page 16)

[5f9c057e3a8264.95378949990-6480-EN.pdf](https://github.com/centreon/centreon-plugins/files/11375130/5f9c057e3a8264.95378949990-6480-EN.pdf)

SNMP walk:
[oid apc galaxy (1).txt](https://github.com/centreon/centreon-plugins/files/11375096/oid.apc.galaxy.1.txt)

SNMP MIB:
[powernet441.zip](https://github.com/centreon/centreon-plugins/files/11375098/powernet441.zip)

**Comment by garnier-quentin** [comment]
It seems there are values by phases in table upsPhaseInputPhaseTable (.1.3.6.1.4.1.318.1.1.1.9.2.3.1).

**Comment by joschi99** [comment]
Hi @garnier-quentin, any news for them? Did you need additional infos?

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4551
