### ISSUE TITLE
[os::linux::snmp::plugin] Mode storage - Partition reiserfs not visible

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#440]
Hi,

reiserfs partitions seems to be not visible with centreon_plugins.

liste des montages sur le serveur concerné
![centreon_linux_liste_montage](https://cloud.githubusercontent.com/assets/8720203/16624248/48ba103e-43a1-11e6-962a-808d1878b5cb.png)

liste des montages visibles par le plugin
![centreon_linux_mode_storage_reiserfs](https://cloud.githubusercontent.com/assets/8720203/16624285/60fcc61e-43a1-11e6-9ccf-b4f989637fd7.png)

Is there a limitation or it's a bug?

thanks,

**Comment by garnier-quentin** [comment]
Look more like a net-snmp bug. Or maybe the partition uses another type. Could you do a snmpwalk ?
.1.3.6.1.2.1.25.3.8.1.2
.1.3.6.1.2.1.25.2.3.1.2
.1.3.6.1.2.1.25.2.3.1.3

**Comment by cmeschin** [comment]
the results...
![centreon_snmpwalk](https://cloud.githubusercontent.com/assets/8720203/16625546/64260af4-43a5-11e6-842f-66a7ffd90116.png)

I'll try to grep on /mnt/data but it return no value :(

**Comment by cmeschin** [comment]
maybe it's important, the host in a RedHat 6.2 server...

**Comment by garnier-quentin** [comment]
I found some tickets: https://bugzilla.redhat.com/show_bug.cgi?id=755958
Don't know your version. But i think it's more a problem from the system. There are still some people using reiserfs :)

**Comment by cmeschin** [comment]
> There are still some people using reiserfs :)

... yes, us :D 

ok, i've found another link where this problem is evoked: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/6.3_Technical_Notes/net-snmp.html

I'll try to get net-snmp version and try to see if update is possible on hosts concerned.

thanks,
