### ISSUE TITLE
create support for FortiMail

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4402]
It should be great to have support for FortiMail to monitor:

- CPU/Memory/Load
- Disk usage (Log/Mail)
- Sessions
- Hardware
- HA mode/status
- Mail queues

SNMP MIBS:
[fortimail.zip](https://github.com/centreon/centreon-plugins/files/11405349/fortimail.zip)

snmpwalk:
[fortimail.snmp.txt](https://github.com/centreon/centreon-plugins/files/11405353/fortimail.snmp.txt)

**Comment by rmorandell-pgum** [comment]
https://github.com/centreon/centreon-plugins/pull/4429

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4484
