### ISSUE TITLE
[network::cisco::standard::snmp::plugin] Cisco 2960X not detect stack

### ISSUE THREAD

**Issue by barte91** [centreon/centreon-plugins#4403]
Hello,

I've a problem with centreon_cisco_standard_snmp.pl plugins
If I try to monitoring Cisco C9xxx series the stack is detect and I've all info
` /usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=stack --hostname=XX.XX.XX.XX --snmp-version='3' --snmp-community='' --snmp-username='XXX' --authpassphrase='XXXXX' --authprotocol='XXX' --privpassphrase='XXXXX' --privprotocol='XXX' --debug`

```
OK: Stack status is 'redundant' - Number of members waiting: 0, progressing: 0, added: 0, ready: 2, SDM mismatch: 0, version mismatch: 0, feature mismatch: 0, new master init: 0, provisioned: 0, invalid: 0, removed: 0 - All stack members status are ok | 'waiting'=0;;;0; 'progressing'=0;;;0; 'added'=0;;;0; 'ready'=2;;;0; 'sdm_mismatch'=0;;;0; 'version_mismatch'=0;;;0; 'feature_mismatch'=0;;;0; 'new_master_init'=0;;;0; 'provisioned'=0;;;0; 'invalid'=0;;;0; 'removed'=0;;;0;
.1.3.6.1.4.1.9.9.500.1.1.3.0 = 1
.1.3.6.1.4.1.9.9.500.1.2.1.1.3.1000 = 4
.1.3.6.1.4.1.9.9.500.1.2.1.1.3.2000 = 1
.1.3.6.1.4.1.9.9.500.1.2.1.1.4.1000 = 15
.1.3.6.1.4.1.9.9.500.1.2.1.1.4.2000 = 14
.1.3.6.1.4.1.9.9.500.1.2.1.1.5.1000 = 0
.1.3.6.1.4.1.9.9.500.1.2.1.1.5.2000 = 0
.1.3.6.1.4.1.9.9.500.1.2.1.1.6.1000 = 4
.1.3.6.1.4.1.9.9.500.1.2.1.1.6.2000 = 4
.1.3.6.1.2.1.47.1.1.1.1.7.1000 = Switch 1
.1.3.6.1.2.1.47.1.1.1.1.7.2000 = Switch 2
Member 'Switch 1' state is 'ready', role is 'standby'
Member 'Switch 2' state is 'ready', role is 'master'
```

Instead if I've do the same command with Cisco C2960X

`UNKNOWN: SNMP Table Request: Timeout
.1.3.6.1.4.1.9.9.500.1.1.3.0 = 1`

I think Cisco C29660X use .1.3.6.1.4.1.9.9.500.1.2.1.1.3.1001 instead 1000, can anyone help me, please?

**Comment by garnier-quentin** [comment]
Could you try with the option ```--snmp-autoreduce``` ?

**Comment by barte91** [comment]
Perfect!!! now it works!
