### ISSUE TITLE
centreon_cisco_standard_snmp : exclude SVI interfaces from interfaces mode

### ISSUE THREAD

**Issue by coucou2000** [centreon/centreon-plugins#4419]
Hi,

Is it possible to filter the SVI interfaces from the commande. Because the SVI interfaces have the default 1gb/s bandwidth value, which is inaccurate for the monitoring.

Thanks

**Comment by garnier-quentin** [comment]
Yes you can exclude some interfaces. An example to exclude all interfaces beginning by ```tun```: ```--interface='^(?!(tun.*)$)' ```
