### ISSUE TITLE
Convert poller to remote server

### ISSUE THREAD

**Issue by Didier97180** [centreon/centreon-plugins#4422]
Hi,

What is the diferrence between Remote Server and Poller.

Is it possible of to convert a poller to Remote Server. If yes how?

Is it grave of to remplace the poller by remote Server?

 

Thank you

**Comment by Didier97180** [comment]
Hello,

i'm sorry but I still have not of answers of your, and i blocked. I would like it's possible of to convert a poller to Remote server and delete properly a poller please.

Thank you

**Comment by garnier-quentin** [comment]
Sorry but it's not a centreon-plugins issue. But yes you can convert a poller to a remote server. But centreon doesn't provide a procedure. It will be nice to have it

**Comment by ponchoh** [comment]
@Didier97180 https://thewatch.centreon.com/topic/new?type=idea
