### ISSUE TITLE
Slack plugin issues

### ISSUE THREAD

**Issue by dawidjttf** [centreon/centreon-plugins#4423]
Hi, I'm using the Slack plugin **apps::slack::restapi::plugin** and it's working fine if there are no Slack issues reported on their website, however, today they reported an issue with their Messaging and the plugin stopped working and is giving the following error:

`
/usr/lib64/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin apps::slack::restapi::plugin --mode services
UNKNOWN: Can't use string ("Messaging") as a HASH ref while "strict refs" in use at /usr/lib64/nagios/plugins/centreon-plugins/apps/slack/restapi/mode/services.pm line 139.
`

Thanks!

**Comment by garnier-quentin** [comment]
it should fix it: https://github.com/centreon/centreon-plugins/pull/4531
