### ISSUE TITLE
network::cisco::standard::snmp::plugin , result always OK when add parameter --add-traffic

### ISSUE THREAD

**Issue by gbin2265** [centreon/centreon-plugins#4426]
Hello,

We have a CRITICAL on our FC port because it is down.
But if I add the parameter "--add-traffic" then the result is always OK, even if interfaces are actually down.

**without parameter "--add-traffic"**
centreon_plugins.pl --plugin="network::cisco::standard::snmp::plugin" --snmp-version="2" --snmp-community="public"  --hostname=x.x.x.x --mode=interfaces --interface="fc" --name
CRITICAL: Interface 'fc1/3' Status : down (admin: up)

**with parameter "--add-traffic"**
centreon_plugins.pl --plugin="network::cisco::standard::snmp::plugin" --snmp-version="2" --snmp-community="public"  --hostname=x.x.x.x --mode=interfaces --interface="fc" --name --add-traffic
**OK**: All interfaces are ok | 'traffic_in_fc1/1'=4851423.09b/s;;;0;32000000000 'traffic_out_fc1/1'=61725.26b/s;;;0;32000000000 'traffic_in_fc1/2'=742258.29b/s;;;0;32000000000 'traffic_out_fc1/2'=77666.74b/s;;;0;32000000000 'traffic_in_fc1/3'=0.00b/s;;;0; 'traffic_out_fc1/3'=0.00b/s;;;0; 'traffic_in_fc1/4'=6042918.40b/s;;;0;32000000000 'traffic_out_fc1/4'=41990.40b/s;;;0;32000000000 'traffic_in_fc1/5'=0.00b/s;;;0; 'traffic_out_fc1/5'=0.00b/s;;;0; 'traffic_in_fc1/6'=0.00b/s;;;0; 'traffic_out_fc1/6'=0.00b/s;;;0; 'traffic_in_fc1/7'=0.00b/s;;;0; 'traffic_out_fc1/7'=0.00b/s;;;0; 'traffic_in_fc1/8'=0.00b/s;;;0; 'traffic_out_fc1/8'=0.00b/s;;;0; 'traffic_in_fc1/9'=0.00b/s;;;0; 'traffic_out_fc1/9'=0.00b/s;;;0; 'traffic_in_fc1/10'=0.00b/s;;;0; 'traffic_out_fc1/10'=0.00b/s;;;0; 'traffic_in_fc1/11'=0.00b/s;;;0; 'traffic_out_fc1/11'=0.00b/s;;;0; 'traffic_in_fc1/12'=0.00b/s;;;0; 'traffic_out_fc1/12'=0.00b/s;;;0; 'traffic_in_fc1/13'=0.00b/s;;;0; 'traffic_out_fc1/13'=0.00b/s;;;0; 'traffic_in_fc1/14'=0.00b/s;;;0; 'traffic_out_fc1/14'=0.00b/s;;;0; 'traffic_in_fc1/15'=0.00b/s;;;0; 'traffic_out_fc1/15'=0.00b/s;;;0; 'traffic_in_fc1/16'=0.00b/s;;;0; 'traffic_out_fc1/16'=0.00b/s;;;0; 'traffic_in_vfc802'=0.00b/s;;;0; 'traffic_out_vfc802'=0.00b/s;;;0; 'traffic_in_vfc806'=0.00b/s;;;0; 'traffic_out_vfc806'=0.00b/s;;;0; 'traffic_in_vfc810'=0.00b/s;;;0; 'traffic_out_vfc810'=0.00b/s;;;0; 'traffic_in_vfc814'=0.00b/s;;;0; 'traffic_out_vfc814'=0.00b/s;;;0; 'traffic_in_vfc818'=0.00b/s;;;0; 'traffic_out_vfc818'=0.00b/s;;;0; 'traffic_in_vfc822'=0.00b/s;;;0; 'traffic_out_vfc822'=0.00b/s;;;0; 'traffic_in_vfc826'=0.00b/s;;;0; 'traffic_out_vfc826'=0.00b/s;;;0; 'traffic_in_vfc830'=0.00b/s;;;0; 'traffic_out_vfc830'=0.00b/s;;;0; 'traffic_in_vfc834'=0.00b/s;;;0; 'traffic_out_vfc834'=0.00b/s;;;0; 'traffic_in_vfc838'=0.00b/s;;;0; 'traffic_out_vfc838'=0.00b/s;;;0; 'traffic_in_vfc842'=0.00b/s;;;0; 'traffic_out_vfc842'=0.00b/s;;;0;

somewhere the output is reset if you add the parameter "--add-traffic".
when I view the debug it doesn't actually look at the status of the ports.

Have you already encountered this problem or is there a parameter somewhere that I need to add ?

regards,
Geert

**DEBUG without parameter "--add-traffic"**
centreon_plugins.pl --plugin="network::cisco::standard::snmp::plugin" --snmp-version="2" --snmp-community="public"  --hostname=x.x.x.x --mode=interfaces --name --interface="fc" --verbose  --debug
CRITICAL: Interface 'fc1/3' Status : down (admin: up)
.1.3.6.1.2.1.2.2.1.7.16777216 = 1
.1.3.6.1.2.1.2.2.1.7.16781312 = 1
.1.3.6.1.2.1.2.2.1.7.16785408 = 1
.1.3.6.1.2.1.2.2.1.7.16789504 = 1
.1.3.6.1.2.1.2.2.1.7.16793600 = 2
.1.3.6.1.2.1.2.2.1.7.16797696 = 2
.1.3.6.1.2.1.2.2.1.7.16801792 = 2
.1.3.6.1.2.1.2.2.1.7.16805888 = 2
.1.3.6.1.2.1.2.2.1.7.16809984 = 2
.1.3.6.1.2.1.2.2.1.7.16814080 = 2
.1.3.6.1.2.1.2.2.1.7.16818176 = 2
.1.3.6.1.2.1.2.2.1.7.16822272 = 2
.1.3.6.1.2.1.2.2.1.7.16826368 = 2
.1.3.6.1.2.1.2.2.1.7.16830464 = 2
.1.3.6.1.2.1.2.2.1.7.16834560 = 2
.1.3.6.1.2.1.2.2.1.7.16838656 = 2
.1.3.6.1.2.1.2.2.1.7.503317281 = 1
.1.3.6.1.2.1.2.2.1.7.503317285 = 1
.1.3.6.1.2.1.2.2.1.7.503317289 = 1
.1.3.6.1.2.1.2.2.1.7.503317293 = 1
.1.3.6.1.2.1.2.2.1.7.503317297 = 1
.1.3.6.1.2.1.2.2.1.7.503317301 = 1
.1.3.6.1.2.1.2.2.1.7.503317305 = 1
.1.3.6.1.2.1.2.2.1.7.503317309 = 1
.1.3.6.1.2.1.2.2.1.7.503317313 = 1
.1.3.6.1.2.1.2.2.1.7.503317317 = 1
.1.3.6.1.2.1.2.2.1.7.503317321 = 1
.1.3.6.1.2.1.2.2.1.8.16777216 = 1
.1.3.6.1.2.1.2.2.1.8.16781312 = 1
.1.3.6.1.2.1.2.2.1.8.16785408 = 2
.1.3.6.1.2.1.2.2.1.8.16789504 = 1
.1.3.6.1.2.1.2.2.1.8.16793600 = 2
.1.3.6.1.2.1.2.2.1.8.16797696 = 2
.1.3.6.1.2.1.2.2.1.8.16801792 = 2
.1.3.6.1.2.1.2.2.1.8.16805888 = 2
.1.3.6.1.2.1.2.2.1.8.16809984 = 2
.1.3.6.1.2.1.2.2.1.8.16814080 = 2
.1.3.6.1.2.1.2.2.1.8.16818176 = 2
.1.3.6.1.2.1.2.2.1.8.16822272 = 2
.1.3.6.1.2.1.2.2.1.8.16826368 = 2
.1.3.6.1.2.1.2.2.1.8.16830464 = 2
.1.3.6.1.2.1.2.2.1.8.16834560 = 2
.1.3.6.1.2.1.2.2.1.8.16838656 = 2
.1.3.6.1.2.1.2.2.1.8.503317281 = 1
.1.3.6.1.2.1.2.2.1.8.503317285 = 1
.1.3.6.1.2.1.2.2.1.8.503317289 = 1
.1.3.6.1.2.1.2.2.1.8.503317293 = 1
.1.3.6.1.2.1.2.2.1.8.503317297 = 1
.1.3.6.1.2.1.2.2.1.8.503317301 = 1
.1.3.6.1.2.1.2.2.1.8.503317305 = 1
.1.3.6.1.2.1.2.2.1.8.503317309 = 1
.1.3.6.1.2.1.2.2.1.8.503317313 = 1
.1.3.6.1.2.1.2.2.1.8.503317317 = 1
.1.3.6.1.2.1.2.2.1.8.503317321 = 1
Interface 'fc1/1' Status : up (admin: up)
Interface 'fc1/2' Status : up (admin: up)
Interface 'fc1/3' Status : down (admin: up)
Interface 'fc1/4' Status : up (admin: up)
Interface 'fc1/5' Status : down (admin: down)
Interface 'fc1/6' Status : down (admin: down)
Interface 'fc1/7' Status : down (admin: down)
Interface 'fc1/8' Status : down (admin: down)
Interface 'fc1/9' Status : down (admin: down)
Interface 'fc1/10' Status : down (admin: down)
Interface 'fc1/11' Status : down (admin: down)
Interface 'fc1/12' Status : down (admin: down)
Interface 'fc1/13' Status : down (admin: down)
Interface 'fc1/14' Status : down (admin: down)
Interface 'fc1/15' Status : down (admin: down)
Interface 'fc1/16' Status : down (admin: down)
Interface 'vfc802' Status : up (admin: up)
Interface 'vfc806' Status : up (admin: up)
Interface 'vfc810' Status : up (admin: up)
Interface 'vfc814' Status : up (admin: up)
Interface 'vfc818' Status : up (admin: up)
Interface 'vfc822' Status : up (admin: up)
Interface 'vfc826' Status : up (admin: up)
Interface 'vfc830' Status : up (admin: up)
Interface 'vfc834' Status : up (admin: up)
Interface 'vfc838' Status : up (admin: up)
Interface 'vfc842' Status : up (admin: up)

**DEBUG with parameter "--add-traffic"**
centreon_plugins.pl --plugin="network::cisco::standard::snmp::plugin" --snmp-version="2" --snmp-community="public"  --hostname=x.x.x.x --mode=interfaces --add-traffic --name --interface="fc" --verbose  --debug
OK: All interfaces are ok | 'traffic_in_fc1/1'=33632.00b/s;;;0;32000000000 'traffic_out_fc1/1'=480.00b/s;;;0;32000000000 'traffic_in_fc1/2'=1401.60b/s;;;0;32000000000 'traffic_out_fc1/2'=120825.60b/s;;;0;32000000000 'traffic_in_fc1/3'=0.00b/s;;;0; 'traffic_out_fc1/3'=0.00b/s;;;0; 'traffic_in_fc1/4'=34380.80b/s;;;0;32000000000 'traffic_out_fc1/4'=1344.00b/s;;;0;32000000000 'traffic_in_fc1/5'=0.00b/s;;;0; 'traffic_out_fc1/5'=0.00b/s;;;0; 'traffic_in_fc1/6'=0.00b/s;;;0; 'traffic_out_fc1/6'=0.00b/s;;;0; 'traffic_in_fc1/7'=0.00b/s;;;0; 'traffic_out_fc1/7'=0.00b/s;;;0; 'traffic_in_fc1/8'=0.00b/s;;;0; 'traffic_out_fc1/8'=0.00b/s;;;0; 'traffic_in_fc1/9'=0.00b/s;;;0; 'traffic_out_fc1/9'=0.00b/s;;;0; 'traffic_in_fc1/10'=0.00b/s;;;0; 'traffic_out_fc1/10'=0.00b/s;;;0; 'traffic_in_fc1/11'=0.00b/s;;;0; 'traffic_out_fc1/11'=0.00b/s;;;0; 'traffic_in_fc1/12'=0.00b/s;;;0; 'traffic_out_fc1/12'=0.00b/s;;;0; 'traffic_in_fc1/13'=0.00b/s;;;0; 'traffic_out_fc1/13'=0.00b/s;;;0; 'traffic_in_fc1/14'=0.00b/s;;;0; 'traffic_out_fc1/14'=0.00b/s;;;0; 'traffic_in_fc1/15'=0.00b/s;;;0; 'traffic_out_fc1/15'=0.00b/s;;;0; 'traffic_in_fc1/16'=0.00b/s;;;0; 'traffic_out_fc1/16'=0.00b/s;;;0; 'traffic_in_vfc802'=0.00b/s;;;0; 'traffic_out_vfc802'=0.00b/s;;;0; 'traffic_in_vfc806'=0.00b/s;;;0; 'traffic_out_vfc806'=0.00b/s;;;0; 'traffic_in_vfc810'=0.00b/s;;;0; 'traffic_out_vfc810'=0.00b/s;;;0; 'traffic_in_vfc814'=0.00b/s;;;0; 'traffic_out_vfc814'=0.00b/s;;;0; 'traffic_in_vfc818'=0.00b/s;;;0; 'traffic_out_vfc818'=0.00b/s;;;0; 'traffic_in_vfc822'=0.00b/s;;;0; 'traffic_out_vfc822'=0.00b/s;;;0; 'traffic_in_vfc826'=0.00b/s;;;0; 'traffic_out_vfc826'=0.00b/s;;;0; 'traffic_in_vfc830'=0.00b/s;;;0; 'traffic_out_vfc830'=0.00b/s;;;0; 'traffic_in_vfc834'=0.00b/s;;;0; 'traffic_out_vfc834'=0.00b/s;;;0; 'traffic_in_vfc838'=0.00b/s;;;0; 'traffic_out_vfc838'=0.00b/s;;;0; 'traffic_in_vfc842'=0.00b/s;;;0; 'traffic_out_vfc842'=0.00b/s;;;0;
.1.3.6.1.2.1.2.2.1.5.16777216 = 4294967295
.1.3.6.1.2.1.2.2.1.5.16781312 = 4294967295
.1.3.6.1.2.1.2.2.1.5.16785408 = 0
.1.3.6.1.2.1.2.2.1.5.16789504 = 4294967295
.1.3.6.1.2.1.2.2.1.5.16793600 = 0
.1.3.6.1.2.1.2.2.1.5.16797696 = 0
.1.3.6.1.2.1.2.2.1.5.16801792 = 0
.1.3.6.1.2.1.2.2.1.5.16805888 = 0
.1.3.6.1.2.1.2.2.1.5.16809984 = 0
.1.3.6.1.2.1.2.2.1.5.16814080 = 0
.1.3.6.1.2.1.2.2.1.5.16818176 = 0
.1.3.6.1.2.1.2.2.1.5.16822272 = 0
.1.3.6.1.2.1.2.2.1.5.16826368 = 0
.1.3.6.1.2.1.2.2.1.5.16830464 = 0
.1.3.6.1.2.1.2.2.1.5.16834560 = 0
.1.3.6.1.2.1.2.2.1.5.16838656 = 0
.1.3.6.1.2.1.2.2.1.5.503317281 = 0
.1.3.6.1.2.1.2.2.1.5.503317285 = 0
.1.3.6.1.2.1.2.2.1.5.503317289 = 0
.1.3.6.1.2.1.2.2.1.5.503317293 = 0
.1.3.6.1.2.1.2.2.1.5.503317297 = 0
.1.3.6.1.2.1.2.2.1.5.503317301 = 0
.1.3.6.1.2.1.2.2.1.5.503317305 = 0
.1.3.6.1.2.1.2.2.1.5.503317309 = 0
.1.3.6.1.2.1.2.2.1.5.503317313 = 0
.1.3.6.1.2.1.2.2.1.5.503317317 = 0
.1.3.6.1.2.1.2.2.1.5.503317321 = 0
.1.3.6.1.2.1.2.2.1.10.16777216 = 4020801116
.1.3.6.1.2.1.2.2.1.10.16781312 = 1690291608
.1.3.6.1.2.1.2.2.1.10.16785408 = 2320863296
.1.3.6.1.2.1.2.2.1.10.16789504 = 2020965880
.1.3.6.1.2.1.2.2.1.10.16793600 = 0
.1.3.6.1.2.1.2.2.1.10.16797696 = 0
.1.3.6.1.2.1.2.2.1.10.16801792 = 0
.1.3.6.1.2.1.2.2.1.10.16805888 = 0
.1.3.6.1.2.1.2.2.1.10.16809984 = 0
.1.3.6.1.2.1.2.2.1.10.16814080 = 0
.1.3.6.1.2.1.2.2.1.10.16818176 = 0
.1.3.6.1.2.1.2.2.1.10.16822272 = 0
.1.3.6.1.2.1.2.2.1.10.16826368 = 0
.1.3.6.1.2.1.2.2.1.10.16830464 = 0
.1.3.6.1.2.1.2.2.1.10.16834560 = 0
.1.3.6.1.2.1.2.2.1.10.16838656 = 0
.1.3.6.1.2.1.2.2.1.10.503317281 = 0
.1.3.6.1.2.1.2.2.1.10.503317285 = 0
.1.3.6.1.2.1.2.2.1.10.503317289 = 0
.1.3.6.1.2.1.2.2.1.10.503317293 = 0
.1.3.6.1.2.1.2.2.1.10.503317297 = 0
.1.3.6.1.2.1.2.2.1.10.503317301 = 0
.1.3.6.1.2.1.2.2.1.10.503317305 = 0
.1.3.6.1.2.1.2.2.1.10.503317309 = 0
.1.3.6.1.2.1.2.2.1.10.503317313 = 0
.1.3.6.1.2.1.2.2.1.10.503317317 = 0
.1.3.6.1.2.1.2.2.1.10.503317321 = 0
.1.3.6.1.2.1.2.2.1.16.16777216 = 1639343400
.1.3.6.1.2.1.2.2.1.16.16781312 = 3729415740
.1.3.6.1.2.1.2.2.1.16.16785408 = 548406932
.1.3.6.1.2.1.2.2.1.16.16789504 = 2455645724
.1.3.6.1.2.1.2.2.1.16.16793600 = 0
.1.3.6.1.2.1.2.2.1.16.16797696 = 0
.1.3.6.1.2.1.2.2.1.16.16801792 = 0
.1.3.6.1.2.1.2.2.1.16.16805888 = 0
.1.3.6.1.2.1.2.2.1.16.16809984 = 0
.1.3.6.1.2.1.2.2.1.16.16814080 = 0
.1.3.6.1.2.1.2.2.1.16.16818176 = 0
.1.3.6.1.2.1.2.2.1.16.16822272 = 0
.1.3.6.1.2.1.2.2.1.16.16826368 = 0
.1.3.6.1.2.1.2.2.1.16.16830464 = 0
.1.3.6.1.2.1.2.2.1.16.16834560 = 0
.1.3.6.1.2.1.2.2.1.16.16838656 = 0
.1.3.6.1.2.1.2.2.1.16.503317281 = 0
.1.3.6.1.2.1.2.2.1.16.503317285 = 0
.1.3.6.1.2.1.2.2.1.16.503317289 = 0
.1.3.6.1.2.1.2.2.1.16.503317293 = 0
.1.3.6.1.2.1.2.2.1.16.503317297 = 0
.1.3.6.1.2.1.2.2.1.16.503317301 = 0
.1.3.6.1.2.1.2.2.1.16.503317305 = 0
.1.3.6.1.2.1.2.2.1.16.503317309 = 0
.1.3.6.1.2.1.2.2.1.16.503317313 = 0
.1.3.6.1.2.1.2.2.1.16.503317317 = 0
.1.3.6.1.2.1.2.2.1.16.503317321 = 0
.1.3.6.1.2.1.31.1.1.1.6.16777216 = 145754721884
.1.3.6.1.2.1.31.1.1.1.6.16781312 = 23165128088
.1.3.6.1.2.1.31.1.1.1.6.16785408 = 118284980288
.1.3.6.1.2.1.31.1.1.1.6.16789504 = 27790769656
.1.3.6.1.2.1.31.1.1.1.6.16793600 = 0
.1.3.6.1.2.1.31.1.1.1.6.16797696 = 0
.1.3.6.1.2.1.31.1.1.1.6.16801792 = 0
.1.3.6.1.2.1.31.1.1.1.6.16805888 = 0
.1.3.6.1.2.1.31.1.1.1.6.16809984 = 0
.1.3.6.1.2.1.31.1.1.1.6.16814080 = 0
.1.3.6.1.2.1.31.1.1.1.6.16818176 = 0
.1.3.6.1.2.1.31.1.1.1.6.16822272 = 0
.1.3.6.1.2.1.31.1.1.1.6.16826368 = 0
.1.3.6.1.2.1.31.1.1.1.6.16830464 = 0
.1.3.6.1.2.1.31.1.1.1.6.16834560 = 0
.1.3.6.1.2.1.31.1.1.1.6.16838656 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317281 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317285 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317289 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317293 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317297 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317301 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317305 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317309 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317313 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317317 = 0
.1.3.6.1.2.1.31.1.1.1.6.503317321 = 0
.1.3.6.1.2.1.31.1.1.1.10.16777216 = 1639343400
.1.3.6.1.2.1.31.1.1.1.10.16781312 = 8024383036
.1.3.6.1.2.1.31.1.1.1.10.16785408 = 548406932
.1.3.6.1.2.1.31.1.1.1.10.16789504 = 2455645724
.1.3.6.1.2.1.31.1.1.1.10.16793600 = 0
.1.3.6.1.2.1.31.1.1.1.10.16797696 = 0
.1.3.6.1.2.1.31.1.1.1.10.16801792 = 0
.1.3.6.1.2.1.31.1.1.1.10.16805888 = 0
.1.3.6.1.2.1.31.1.1.1.10.16809984 = 0
.1.3.6.1.2.1.31.1.1.1.10.16814080 = 0
.1.3.6.1.2.1.31.1.1.1.10.16818176 = 0
.1.3.6.1.2.1.31.1.1.1.10.16822272 = 0
.1.3.6.1.2.1.31.1.1.1.10.16826368 = 0
.1.3.6.1.2.1.31.1.1.1.10.16830464 = 0
.1.3.6.1.2.1.31.1.1.1.10.16834560 = 0
.1.3.6.1.2.1.31.1.1.1.10.16838656 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317281 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317285 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317289 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317293 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317297 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317301 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317305 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317309 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317313 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317317 = 0
.1.3.6.1.2.1.31.1.1.1.10.503317321 = 0
.1.3.6.1.2.1.31.1.1.1.15.16777216 = 32000
.1.3.6.1.2.1.31.1.1.1.15.16781312 = 32000
.1.3.6.1.2.1.31.1.1.1.15.16785408 = 0
.1.3.6.1.2.1.31.1.1.1.15.16789504 = 32000
.1.3.6.1.2.1.31.1.1.1.15.16793600 = 0
.1.3.6.1.2.1.31.1.1.1.15.16797696 = 0
.1.3.6.1.2.1.31.1.1.1.15.16801792 = 0
.1.3.6.1.2.1.31.1.1.1.15.16805888 = 0
.1.3.6.1.2.1.31.1.1.1.15.16809984 = 0
.1.3.6.1.2.1.31.1.1.1.15.16814080 = 0
.1.3.6.1.2.1.31.1.1.1.15.16818176 = 0
.1.3.6.1.2.1.31.1.1.1.15.16822272 = 0
.1.3.6.1.2.1.31.1.1.1.15.16826368 = 0
.1.3.6.1.2.1.31.1.1.1.15.16830464 = 0
.1.3.6.1.2.1.31.1.1.1.15.16834560 = 0
.1.3.6.1.2.1.31.1.1.1.15.16838656 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317281 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317285 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317289 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317293 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317297 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317301 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317305 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317309 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317313 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317317 = 0
.1.3.6.1.2.1.31.1.1.1.15.503317321 = 0
Interface 'fc1/1' Traffic In : 33.63Kb/s (0.00%), Traffic Out : 480.00b/s (0.00%)
Interface 'fc1/2' Traffic In : 1.40Kb/s (0.00%), Traffic Out : 120.83Kb/s (0.00%)
Interface 'fc1/3' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/4' Traffic In : 34.38Kb/s (0.00%), Traffic Out : 1.34Kb/s (0.00%)
Interface 'fc1/5' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/6' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/7' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/8' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/9' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/10' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/11' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/12' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/13' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/14' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/15' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'fc1/16' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc802' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc806' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc810' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc814' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc818' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc822' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc826' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc830' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc834' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc838' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)
Interface 'vfc842' Traffic In : 0.00b/s (-), Traffic Out : 0.00b/s (-)

**Comment by DalfoCentreon** [comment]
It's the standard behavior. Please add both `--add-traffic` and `--add-status` to your command.
