### ISSUE TITLE
apps::wallix::bastion::snmp::plugin mode license, add thresholds on instances (primary/secondary/resource)

### ISSUE THREAD

**Issue by kabreu** [centreon/centreon-plugins#4427]
With the license mode we cannot put individual thresholds.
For example a command might return: 

`'license.expires.seconds'=2418132583s;;;0;
'primary#license.usage.count'=2;;;0;500
'primary#license.free.count'=498;;;0;500
'primary#license.usage.percentage'=0.40%;;;0;100
'resource#license.usage.count'=232;;;0;500
'resource#license.free.count'=268;;;0;500
'resource#license.usage.percentage'=46.40%;;;0;100
'secondary#license.usage.count'=0;;;0;20
'secondary#license.free.count'=20;;;0;20
'secondary#license.usage.percentage'=0.00%;;;0;100`

But the only threshold we can have are :
`    --warning-* --critical-*
            Thresholds. Can be: 'total', 'expires', 'license-usage',
            'license-free', 'license-usage-prct'.
`

Meaning we can't trigger specific alerts.

Would be better to have the same as the "system" mode that gives more precise thresholds like: 
`'sessions-total', 'sessions-primary', 
'sessions-secondary', 'sessions-ghost'`

And implement something like : 
license-usage-primary
license-usage-secondary
etc.

Thank you

**Comment by kabreu** [comment]
Ok for the filter, thank you ! 👍  
It would allow more fine tuning in the monitoring.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4447
