### ISSUE TITLE
[Network::Fortinet::Fortigate::SNMP] - UNKNOWN: SNMP Session: unable to create

### ISSUE THREAD

**Issue by volgur** [centreon/centreon-plugins#4437]
Hello,

I'm facing an issue about my Fortigate. I try to monitor it in SNMP v3, without any success. As the tcpdump show, my Centreon don't even send any snmp request.

Here are the command + output : 

```
perl centreon_plugins.pl --plugin=network::fortinet::fortigate::snmp::plugin.pm --snmp-version=3 --snmp-username=USER --authpassphrase=PASSPHRASE --authprotocol=SHA256 --privprotocol=AES256 --privpassphrase=PRIVPASSPHRASE --hostname=HOST_IP --mode=cpu
UNKNOWN: SNMP Session: unable to create
```

Any ideas ?
Thanks in advance

**Comment by garnier-quentin** [comment]
It won't work with AES258. It needs net-snmp 5.9.1.

**Comment by volgur** [comment]
I'm actually with net-snmp 5.8 but no updates are available.
What can I do ?

**Comment by garnier-quentin** [comment]
It means you add a newer version to your operating system (also means you'll need to do it manually).
