### ISSUE TITLE
network::aruba::aoscx::snmp::plugin CPU and MEMORY check problem

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#4438]
Hello, 
I try to monitor an ARUBA 2930F Switch CPU and MEMORY but the check returns unknown. 
./centreon_plugins.pl --plugin=network::aruba::aoscx::snmp::plugin --mode=cpu --hostname=192.168.253.2 --snmp-community=supervision --snmp-version=2c
UNKNOWN: SNMP Table Request: Cant get a single value.
I have attached the MIB file

Can you please help with that issue ?
thank you

[16.11.0004_mibs-Mar2022.zip](https://github.com/centreon/centreon-plugins/files/11601426/16.11.0004_mibs-Mar2022.zip)

**Comment by garnier-quentin** [comment]
Please checl: https://github.com/centreon/centreon-plugins/issues/4086

**Comment by saharawolf** [comment]
Hi, 
My switch version is not the same as #4086  
It runs version 16.11.0011 so it should be newer. 
regards

**Comment by garnier-quentin** [comment]
Could you provide a full snmpwalk also ?

**Comment by saharawolf** [comment]
Hi, 
I found my issue, this switch is not AOSCX. 
So i used the hp procurve plugin and it works. 
Sorry for that.
Thanks for the help

**Comment by saharawolf** [comment]
thanks for the help
