### ISSUE TITLE
Pb de seuils sur mode time-host du plugin VMware

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon-plugins#444]
Bonjour,

Il semblerait que le seuil ne soit pas correctement pris en compte dans le mode time-host 

$ perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --mode=time-host --verbose --warning-time=5 --critical-time=10

CRITICAL: 'xxxxxxxxxxxx' Time offset 0 second(s) : 2016-07-15T14:37:12.065821Z | 'offset'=-0.0658209323883057s;0:5;0:10;0;
'xxxxxxxxxxxxxx' date: 2016-07-15T14:37:12.065821Z, offset: -0.0658209323883057 second(s)

Peut-être à cause de la valeur négative de la dérive ?

Merci !

Norbert

**Comment by garnier-quentin** [comment]
Bonjour,

C'est tout à fait cela. Il faut que tu fasses comme cela: --warning-time=-5:5 --critical-time=-10:10
