### ISSUE TITLE
netapp active IQ service manager

### ISSUE THREAD

**Issue by tanguyvda** [centreon/centreon-plugins#4448]
could be cool to get netapp monitoring from their own monitoring tool 
https://library.netapp.com/ecmdocs/ECMLP2865023/html/index.html

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
