### ISSUE TITLE
[network::ruckus::zonedirector::snmp::plugin] --mode=access-points/list-access-points

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4457]
The OID to identify .1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.2 the AP is the description but not the AP name. This cloud be a problem because the description is an optional field/information and maybe is not set.

The AP name could be found in OID .1.3.6.1.4.1.25053.1.2.2.4.1.1.1.1.5

Could you change to plugin to use the AP name instead of the AP description?

**Comment by garnier-quentin** [comment]
If the description is defined, the plugin uses the description. But it's not defined, the plugin uses the serial number (ruckusZDWLANAPSerialNumber = .1.3.6.1.4.1.25053.1.2.2.4.1.1.1.1.5)

**Comment by garnier-quentin** [comment]
You don't need. it have done it
