### ISSUE TITLE
[os::windows::local::plugin] add mode to monitor TEAM interface status

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#4466]
Should you add a mode to monitor logical interface for Windows ?

One way would be using WMI :
Set objWMIService = GetObject("winmgmts:\\.\root\CIMV2")
Set colItems = objWMIService.ExecQuery("SELECT NetConnectionID, NetConnectionStatus FROM Win32_NetworkAdapter", , 48)

The goal is to have status for TEAM interface wich is absent from SNMP Agent.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
