### ISSUE TITLE
[apps::protocols::x509::plugin] new mode for CRL

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#4467]
Should you add a new mode to monitor Certificate Revocation List expiration date ?

Thanks

**Comment by garnier-quentin** [comment]
It's about reading a crl file (download it by https or on local disk) and check the expiration date of that file. We can use that library: https://metacpan.org/pod/Crypt::X509::CRL

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
