### ISSUE TITLE
[cloud::vmware::velocloud::restapi::plugin] --mode=link-status returns OK even if link not exists

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4469]
If you monitor a dedicated not existing velocloud link the plugin returns always status OK

![image](https://github.com/centreon/centreon-plugins/assets/6400595/b3de5871-7e2d-455a-9c8d-f5152d78088c)

In this case here we have set:
critical-status='%{state} !~ /STABLE/ || %{vpn_state} !~ /STABLE/'

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4476
