### ISSUE TITLE
[os::windows::wsman::plugin updates] - new command mode

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4470]
It should be usefull to have a mode=command, which allows to execute a custom command - for example to check dirty flag (https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-dirty) or other usefull commands

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
