### ISSUE TITLE
new plugin for NAS TerraMaster

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4471]
It should be great to have a plugin NAS TerraMaster (https://www.terra-master.com/global/)

SNMP walk: [OID NAS TerraMaster.txt](https://github.com/centreon/centreon-plugins/files/11718673/OID.NAS.TerraMaster.txt)

MIB: [OID NAS TerraMaster.txt](https://github.com/centreon/centreon-plugins/files/11718688/OID.NAS.TerraMaster.txt)

**Comment by garnier-quentin** [comment]
The MIB file is missing (2 snmpwalk). And i don't see specific entreprise oids.

**Comment by joschi99** [comment]
Sorry, here the MIB: 
[TERRAMASTER_TNAS_MIB_X86.txt](https://github.com/centreon/centreon-plugins/files/11735913/TERRAMASTER_TNAS_MIB_X86.txt)

I will check the snmpwalk

**Comment by garnier-quentin** [comment]
I have looked and you could use the qnap plugin

**Comment by garnier-quentin** [comment]
I have checked more. Entreprise part is empty (nas mib) You should use the linux snmp plugin.

**Comment by joschi99** [comment]
Hi @garnier-quentin,
using linux SNMP only CPU, NTP, storage and uptime seems working. Memory, swap, DiskIO, CPU detailed, Load not works. No hardware available. Some idea

**Comment by gh0stface33** [comment]
Hi,
Any news about this issue ?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
