### ISSUE TITLE
[apps::mulesoft::restapi::plugin] Support for Cloudhub API ?

### ISSUE THREAD

**Issue by dysan54** [centreon/centreon-plugins#4472]
Hi,

This plugin works perfectly with API deployed on hybrid VM but not on Cloudhub.
It would be great to include this functionnality. 
Do you work on this, or is it not planned at all ?

Thanks.

**Comment by garnier-quentin** [comment]
It's not planned. I need more informations about that API

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
