### ISSUE TITLE
Bad latency value -> storage::netapp::ontap::restapi::plugin

### ISSUE THREAD

**Issue by Tatayet64** [centreon/centreon-plugins#4488]
Hi,

I found an error in this plugin : =storage::netapp::ontap::restapi::plugin
with the mode "cluster" you should divide the latency value by 1000.

I found an issue where you have corrected for the volume mode but it's the same with the cluster mode.

Regards,

**Comment by Tatayet64** [comment]
Or the unit should be microsecond instead of ms

**Comment by garnier-quentin** [comment]
I don't change the value by default. If i understand, netapp provides the value in microseconds ?

**Comment by Tatayet64** [comment]
Yes. That's it.
 
In the cluster mode the unit for the plugin is in millisecond, but the value given by netapp is in microsecond

In the aggregates mode unit and value are in microsecond -> OK

In the volume mode, a divide by 1000 has been made.  I think to keep the unit in ms. 
[https://github.com/centreon/centreon-plugins/pull/3968](url)
But the information seems not be given anymore by Netapp . the plugin return an error (Use of uninitialized value in division (/) at /usr/lib64/nagios/plugins/storage/netapp/ontap/restapi/mode/volumes.pm line 234)

Should be great having the same unit in each mode ms or µs.
Personnaly i like more in ms, but it's your choice ;-)

Thanks for your help

**Comment by Tatayet64** [comment]
To complete my answer with the 2nd issue with the volume mode Here is the reply i have.
Iops seems also missing 

U**se of uninitialized value in division (/) at /usr/lib64/nagios/plugins/storage/netapp/ontap/restapi/mode/volumes.pm line 234.**
Use of uninitialized value in division (/) at /usr/lib64/nagios/plugins/storage/netapp/ontap/restapi/mode/volumes.pm line 234.
Use of uninitialized value in division (/) at /usr/lib64/nagios/plugins/storage/netapp/ontap/restapi/mode/volumes.pm line 234.
Use of uninitialized value in division (/) at /usr/lib64/nagios/plugins/storage/netapp/ontap/restapi/mode/volumes.pm line 234.
OK: Volume 'Y-svm:vol_X' state: online, space usage total: 21.00 TB used: 5.39 TB (56.73%) free: 9.09 TB (43.27%), **read : skipped (no value(s)), write : skipped (no value(s)), other : skipped (no value(s)), total : skipped (no value(s)), read-iops : skipped (no value(s)), write-iops : skipped (no value(s)), other-iops : skipped (no value(s)), total-iops : skipped (no value(s)), read latency: 0 ms, write latency: 0 ms, other latency: 0 ms, total latency: 0 ms** | 
'Y-svm:vol_X#volume.space.usage.bytes'=5929616494592B;;;0;23089744183296 
'Y-svm:vol_X#volume.space.free.bytes'=9990055297024B;;;0;23089744183296 
'Y-svm:vol_X#volume.space.usage.percentage'=56.73%;;;0;100 
'Y-svm:vol_X#volume.io.read.latency.milliseconds'=0ms;;;0; 
'Y-svm:vol_X#volume.io.write.latency.milliseconds'=0ms;;;0; 
'Y-svm:vol_X#volume.io.other.latency.milliseconds'=0ms;;;0; 
'Y-svm:vol_X#volume.io.total.latency.milliseconds'=0ms;;;0;

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue is still curent but had been handle in an other issue topic [here](https://github.com/centreon/centreon-plugins/issues/4793). So let me close this one to avoid duplicate. I had also notice the feedback about volume mode output, we'll try to reproduce it.
Thanks for your patience 🙏
