### ISSUE TITLE
Check ESX's RAID  on HP Proliant and Dell PowerEdge servers

### ISSUE THREAD

**Issue by PapaSchtrouuumpf** [centreon/centreon-plugins#449]
Good morning everyone, 

I have ESXs running on Dell PowerEdge or HP Proliant servers.
I want to monitor my RAID on these servers (RAID 1 with 2 HDD and one spare). I would like to be warned if my spare or one HDD crashes.

I'm trying to monitor my server with 

- **hardware::server::hp::proliant::snmp::plugin**
- **hardware::server::dell::openmanage::snmp::plugin**

Here is an example for HP Proliant

> [root@san_raid0 centreon-plugins-master]# ./centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=IP --debug
OK: All 0 components are ok []. |
Product Name: unknown, Serial: unknown, Rom Version: unknown
Checking cpu
Checking ide controllers
Checking ide logical drives
Checking ide physical drives
Checking power converters
Checking power supplies
Checking sas controllers
Checking sas logical drives
Checking sas physical drives
Checking scsi controllers
Checking scsi logical drives
Checking scsi physical drives
Checking fca host controller
Checking fca external controller
Checking fca external accelerator boards
Checking fca logical drives
Checking fca physical drives
Checking da controller
Checking da accelerator boards
Checking da logical drives
Checking da physical drives
Checking fans
Checking physical nics
Checking logical nics

I really don't understand that "**OK: All 0 components are ok**".

The SNMP access seems good : I can get information with : 

> snmpwalk -Cc -On -v 2c -c public IP  .1

I'm asking for some advices to help me.

Thanks a lot !

Frédéric L.

**Comment by garnier-quentin** [comment]
I don't think you'll have SNMP information about hardware on ESX. Could you give the full snmpwalk ?
Otherwise, if it's linked with a vcenter, you can use "centreon-vmware". If it's a standalone ESX, you can use 'apps::vwmare::wsman::plugin'.

**Comment by PapaSchtrouuumpf** [comment]
Thanks for your quick reply.

Here is the the snmpwalk for my Dell PowerEdge R710 server : https://framabin.org/?890d3b5a4c6007a3#ULu/HfVtSe/IL/aNSL0jeVnhdnlSIS3+WwXLjMYo0u4=
(HP Proliant is on maintenance)

Everything would be easier if my company had vcenter but I only have the free version of VSphere.

Depending on server, I have a different output message : 

> [root@san_raid0 centreon-plugins-master]# ./centreon_plugins.pl --plugin=apps::vmware::wsman::plugin --mode=hardware --hostname=IP  
UNKNOWN: Could not enumerate instances: Timeout was reached
or
UNKNOWN: Could not enumerate instances: Couldn't connect to server

Sorry for my incompetence, I'm an intern and I'm not very familiar with these technologies.

**Comment by garnier-quentin** [comment]
What is your full command line for wsman check ? Which version of perl openwsman have you installed on your server ?

**Comment by PapaSchtrouuumpf** [comment]
This is my full command, I just wanted to try the plugin with a simple command.

To be honest, I didn't installed openwsman on my server. It looks like it was packaged in the ESX.
I have 

>     find / -name openwsman
/lib/openwsman
/etc/cim/openwsman
/etc/openwsman
/etc/pam.d/openwsman

**Comment by garnier-quentin** [comment]
You need to install a perl version updated. Install the following:
http://yum.centreon.com/standard/3.3/stable/dependencies/x86_64/RPMS/openwsman-perl-2.6.2-1.el6.x86_64.rpm

**Comment by PapaSchtrouuumpf** [comment]
Thanks a lot ! 
I'll try this as soon as i find a way to install openwsman without rpm/yum/etc on my ESX..

Otherwise, do you think I can get RAID status with an OID with **snmp_standard::plugin** ?

**Comment by garnier-quentin** [comment]
I don't think you'll get it in SNMP.

**Comment by PapaSchtrouuumpf** [comment]
Ok, it seems that I have ESX's disks status with the check_vmware_api with :+1: 

>  ./check_vmware_api -H IP_ESX -u ROOT -p PASSWORD_ESX -l storage -s lun

It returns **STATUS WARNING - Local hp CD-ROM (mpx.vmhba0:C0:T0:L0) <ok>: HP Serial Attached SCSI Disk (naa.600508b1001c06d75b292b49068abc31) <ok-degraded>:**. I knew there was an error on a disk. 

But I also have a RHEL 5 (32bits) physical machine that I want to monitor with a HP Proliant DL585 G2. When I try the following command 
> ./centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=global-status --hostname=gdasrv18
It returns : 
UNKNOWN: SNMP GET Request : Cant get a single value.

I don't understand while although I have SNMP access.

Thanks for your quick replies Quentin Garnier !

**Comment by garnier-quentin** [comment]
Have you installed the hp insight snmp agent on your redhat 5 ?

**Comment by PapaSchtrouuumpf** [comment]
Hmm probably not...

**Comment by garnier-quentin** [comment]
I close it. You can continue to comment it.
