### ISSUE TITLE
[hardware::server::hp::ilo::xmlapi::plugin] mode=hardware - UNKNOWN physical nic is other

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4490]
`WARNING: da controller '0' is degraded - da physical drive '0.4' is degraded UNKNOWN: physical nic '2' is other - physical nic '3' is other - physical nic '4' is other`

we have found 2 problems on this plugin

1. wrong service status reported: as you can see the plugin returns Warning and Unknown problems. The exit code is "UNKNOWN" and not "WARNING"
2. the UNKNOWN on the nics is not correct, the status is "other", but this means that they are not attached to the network or status up.

Workaround
we have filtered out the nics with --filter=nic,(2|3|4), but the nics with status other has to be considered as OK. Plugin exit code is now on WARNING

**Comment by Cynexxde** [comment]
Hello, I recently had a similar problem. I also believed that the plugin was not reading the status correctly, but the Ilo simply does not show it as a warning. Have a look at the tab "System Information" -> "Network" in the Ilo. All network ports must have the status OK. If this is not the case, **a restart/reset of the ILO will help**.

The plugin effectively only reads out the status of the ports and if it says Unknown in the Ilo, the plugin also reports it.

**Comment by garnier-quentin** [comment]
If i understand, the plugin is correct ? @joschi99 you can also override the other status: ```--threshold-overload='nic,OK,other'```

**Comment by joschi99** [comment]
Yes, this could be a valid solution
