### ISSUE TITLE
Storage/EMC/Isilon plugin hardware mode do not show DIMM errors

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#4491]
Plugin : storage::emc::isilon::snmp::plugin
Version : latest from git repository
Storage : Dell EMC Isilon A200 node, OneFS 9.2.1.0

Context
When we check Hardware components on the storage node, we have only Fan, Disk, Power and Temperature informations. We do not have any metrics regarding DIMM.
If hardware issues occurs about DIMM, we're not notified.

Question
Can you please check if this is possible to get some informations about this ?

Thank you very much
Best regards
stefano

**Comment by garnier-quentin** [comment]
Sorry but it's not available in MIB file. Maybe you can provide your MIB file for your equipment ?

**Comment by stefanotoro** [comment]
Hi Quentin,
Thank you for asking, we do not have specific MIB for our equipment.
Regards
stefano

**Comment by garnier-quentin** [comment]
so i cannot add it i'm sorry
