### ISSUE TITLE
[network::fortinet::fortigate::snmp::plugin] Mode VPN : Service Discovery

### ISSUE THREAD

**Issue by SavCent** [centreon/centreon-plugins#4496]
Bonjour,

Nous utilisons le plugin Fortigate pour monitorer nos firewalls en SNMP, le discovery du service "Interfaces" fonctionne bien mais Nous aurions voulu mettre en place le discovery pour le mode "vpn".

Actuellement le check du mode vpn est un check global qui remonte tout le temps Critical.

Fortigate fait la différence entre le check de l'interface d'un tunnel VPN (qui peut être UP) et le check du VPN en lui-même avec toutes les phases 2 (Qui peuvent être down).

Nous avons donc actuellement 2 checks distincts or il faudrait que le discovery vpn remonte tout les vpn+phase deux de manière indépendante  (Il y en a des centaines par équipements en moyenne).

Nous avons créer des commandes de Macro et Discover pour le mode vpn en en modifiant le script perl basé sur le discover du interface (En ajoutant les sections pour les paramètres --disco-show et --disco-format).

Cette solution ne fonctionne pas...

Y a t'il un autre moyen d'automatiser la création de ces services ?

Cordialement

info : Centreon v22.10
conf commande VPN discover
![image](https://github.com/centreon/centreon-plugins/assets/134679564/d05cbf2c-45c7-41d5-aed3-9cc4ab5ffe96)
conf command VPN macro
![image](https://github.com/centreon/centreon-plugins/assets/134679564/4999528a-ba7c-4313-8a31-e9c78dfb1b1e)

**Comment by garnier-quentin** [comment]
There is no service discovery for vpn phase. Maybe we can add a mode for that

**Comment by SavCent** [comment]
Bonjour Quentin,
oui se sera vraiment un super ajout au plugin car c'est vital pour nous. 
Merci beaucoup

**Comment by SavCent** [comment]
Bonjour,
peut-on avoir un statut d'avancement sur ce sujet ?
Cordialement

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
