### ISSUE TITLE
New mode: network::f5::bigip::snmp::plugin --mode virtualserver-stats

### ISSUE THREAD

**Issue by PedroMSantosD** [centreon/centreon-plugins#4499]
Hi,

Do you think you can create a new mode for the F5 plugin?
it should behave just like the snmp plugin for network interfaces, where you get and filter the interface by a name, and the the relevant (desired metrics).

In my case, I just want the vistualserver client sent and receive traffic; namely
from ltmVirtualServStatTable (.1.3.6.1.4.1.3375.2.2.10.2.3.1.)
filter by name:
                ltmVirtualServStatName                                    LongDisplayString, (.1)
desired metrics:
        	ltmVirtualServStatClientBytesIn                           Counter64, (.7)
        	ltmVirtualServStatClientBytesOut                          Counter64, (.9)

Would be nice to have the corrected rate (just like the network-interface cards)

## New Plugins and modes

To develop a Plugin/mode, we need the following:
Mib file:
* SNMP: MIBs files:
[F5-BIGIP-LOCAL-MIB.txt](https://github.com/centreon/centreon-plugins/files/11845815/F5-BIGIP-LOCAL-MIB.txt)

* and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk): OID walked: 1.3.6.1.4.1.3375.2.2.10.2.3
[capture.txt](https://github.com/centreon/centreon-plugins/files/11845826/capture.txt)

* whish list: 
perl centreon_plugins.pl --plugin network::f5::bigip::snmp::plugin --mode virtualserver-traffic-stats --filter-name apm-server .....

Thanks in advance,

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
