### ISSUE TITLE
Redhat7 - New plugins ?

### ISSUE THREAD

**Issue by ccoupeau** [centreon/centreon-plugins#450]
Hello, 

I have some issues to supervise our news Redhat 7 with my plugins for Redhat 6, 5, 4 (--plugin=os::linux::snmp::plugin) . 

Is it normal ? Are you aware from this problem ? Do you have news plugins for Redhat 7 ?

Thanks,

Best regards,

**Comment by Sims24** [comment]
Hi, 

What's is the problem exactly ? If you get "Can't get a single value", for cpu e.g for example, be sure to use --snmp-version 2c. 

All mode work for me on CentOS 7. 

Thanks,

**Comment by ccoupeau** [comment]
I'm using version 2c.

Actually, only check_ping working for Redhat 7. 

Results from others check are (DISK/CPU/MEMORY/UPTIME/ETHx/snmpd/Load Average) >
- UNKNOWN: SNMP Table Request : Timeout
or
- UNKNOWN: SNMP GET Request : Timeout
or 
- SNMP TABLE ERROR : No response from remote host ""

I already try to overwrite /etc/snmpd/snmpd.conf from an host where checks are OK but nothing better on RH7.

systemctl status snmpd : Running.

For more infos > 

On Red Hat Enterprise Linux Server release 6.5  >
rpm -qa | grep snmp > 
net-snmp-libs-5.1.2-18.el4_8.2
net-snmp-5.1.2-18.el4_8.2

On Red Hat Enterprise Linux Server release 7.2 >
rpm -qa | grep snmp > 
net-snmp-agent-libs-5.7.2-24.el7.x86_64
net-snmp-5.7.2-24.el7.x86_64
net-snmp-libs-5.7.2-24.el7.x86_64

**Comment by Sims24** [comment]
Thanks for the feedback, 

The error is probably in your command or snmpd.conf file or any equipement somewhere in the middle.

Here are my libraries versions : 
net-snmp-libs-5.7.2-24.el7_2.1.x86_64
net-snmp-agent-libs-5.7.2-24.el7_2.1.x86_64
net-snmp-5.7.2-24.el7_2.1.x86_64
php-snmp-5.4.16-36.1.el7_2.1.x86_64
net-snmp-perl-5.7.2-24.el7_2.1.x86_64

try putting minimalist snmpd.conf with only this line  :

rocommunity public

and then check if plugins are working. 

If not, you have some kind of firewall/iptables somewhere. 

Thanks

**Comment by gerpion** [comment]
Hey,
Is SELinux/Firewall running ?

**Comment by garnier-quentin** [comment]
I close the ticket. I think it's a problem of snmp agent configuration. Anyway, we can continue the talk.
We're waiting your feedback ccoupeau ;)

**Comment by ccoupeau** [comment]
Hi, 

Sry i'm late. 
Working on others things ...
So the problem came from Firewalld status ..... 
Thought my co-worker disabled it in the template ... but no ... :)

Sry for that ... !

And thx for all :)
