### ISSUE TITLE
[cloud::aws::cloudwatch::plugin] Multiple dimensions for AWS Cloudwatch

### ISSUE THREAD

**Issue by DowXor** [centreon/centreon-plugins#4501]
Hi !

> Plugin : cloud::aws::cloudwatch::plugin
> Mode : get-metrics
> Namespace Cloudwatch : ECS/ContainerInsights

I need to put several "dimensions" to check the status of an ecs task.
I tried all the possible means but I did not manage to put more than one dimension.

Knowing that in AWS CLI it is possible, do you have a solution to propose me?

Thanks !

**Comment by garnier-quentin** [comment]
You can do it with that option:
```--dimension=InstanceId=i-01622936185e32a45 --dimension=toto=value ...```

**Comment by DowXor** [comment]
Oh no really ^^ Thanks you !
