### ISSUE TITLE
FreeBSD plugin storage does not show the real storage value

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#4513]
**Plugin** : os::freebsd::snmp::plugin or os::linux::snmp::plugin
**Version** : latest from git repository
**Storage** : Dell EMC Isilon node, OneFS 9.4.0.10 - FreeBSD Operating System

**Context**
Different values are shows between "df" local command on the storage and SNMP plugin check
Same results with linux plugin

**Test on Storage 1**
#df -T
OneFS                  efs   1408204407368 1052703689792 342170799312    75%    /ifs
#df -hT
OneFS                  efs      1.3P    981T    318T    76%    /ifs

#centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode list-storages --filter-storage-type | grep OneFS        
'/ifs, type: efs, dev: OneFS' [size = 1347967363579904B] [id = 12]
#centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode storage --filter-storage-type --storage 12               
OK: Storage '/ifs, type: efs, dev: OneFS' Usage Total: 1225.97 TB Used: 864.09 TB (70.48%) Free: 361.87 TB (29.52%) | 'count'=1;;;0; 'used'=950081750564864B;;;0;1347967363579904

**Test on Storage 2**
#df -T
OneFS                  efs   1408204407368 1052705424432 342169064672    75%    /ifs
#df -hT
OneFS                  efs      1.3P    981T    318T    76%    /ifs

#centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode list-storages --filter-storage-type | grep OneFS             
'/ifs, type: efs, dev: OneFS' [size = 1445960309800960B] [id = 12]
#centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode storage --filter-storage-type --storage 12
OK: Storage '/ifs, type: efs, dev: OneFS' Usage Total: 1315.09 TB Used: 955.11 TB (72.63%) Free: 359.98 TB (27.37%) | 'count'=1;;;0; 'used'=1050156723077120B;;;0;1445960309800960

Question
Can you please check if i'm wrong ?

Thank you very much
Best regards
stefano

**Comment by garnier-quentin** [comment]
In SNMP you need to set the option (in percent): ```--space-reservation=x```

**Comment by stefanotoro** [comment]
Thanks, same results

./centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode storage --filter-storage-type --storage 12 --space-reservation=10
OK: Storage '/ifs, type: efs, dev: OneFS' Usage Total: 1225.97 TB Used: 864.09 TB (78.31%) Free: 239.28 TB (21.69%) | 'count'=1;;;0; 'used'=950081750564864B;;;0;1347967363579904

./centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode storage --filter-storage-type --storage 12 --space-reservation=10  
OK: Storage '/ifs, type: efs, dev: OneFS' Usage Total: 1315.09 TB Used: 955.11 TB (80.70%) Free: 228.47 TB (19.30%) | 'count'=1;;;0; 'used'=1050156723077120B;;;0;1445960309800960

**Comment by stefanotoro** [comment]
To be honest I don't know, anyway it's the same

./centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode storage --filter-storage-type --storage 12 --space-reservation=5
OK: Storage '/ifs, type: efs, dev: OneFS' Usage Total: 1315.09 TB Used: 955.11 TB (76.45%) Free: 294.23 TB (23.55%) | 'count'=1;;;0; 'used'=1050156723077120B;;;0;1445960309800960

./centreon_plugins.pl --plugin os::freebsd::snmp::plugin --hostname x.x.x.x --mode storage --filter-storage-type --storage 12 --space-reservation=5
OK: Storage '/ifs, type: efs, dev: OneFS' Usage Total: 1225.97 TB Used: 864.09 TB (74.19%) Free: 300.58 TB (25.81%) | 'count'=1;;;0; 'used'=950081750564864B;;;0;1347967363579904

**Comment by garnier-quentin** [comment]
It's a disk with PetaBytes ? I think it's an issue with SNMP and the big values.

**Comment by stefanotoro** [comment]
I have other storages with less than 1TB storage. I'll check now and come back with fresh results

**Comment by stefanotoro** [comment]
![image](https://github.com/centreon/centreon-plugins/assets/28057146/92790b14-37f1-49de-a1d9-434ba7622571)

**Comment by stefanotoro** [comment]
![image](https://github.com/centreon/centreon-plugins/assets/28057146/98655f37-dd2b-466b-89f2-ed9e1f2a78b2)

**Comment by garnier-quentin** [comment]
Check the SNMP raw values with --debug. Maybe it's an issue with net-snmp agent.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @stefanotoro  if you still need a response / solution to this issue, can you try Quentin suggestion above ?

**Comment by stefanotoro** [comment]
Hi Lucie,
Unfortunately we do not use this plugin yet, because it not suit our needs.
You can safely close this case.
Thank you very much
