### ISSUE TITLE
os-linux-local plugin mode discovery raises an null pointer exception

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-plugins#4522]
Hi,

`centreon_plugins.pl  --plugin=os::linux::local::plugin --mode=discovery-snmp --subnet="10.10.100.10/32" --snmp-port=161 --snmp-version=2c --snmp-community='***' --snmp-timeout=`3

Use of uninitialized value in numeric eq (==) at /tmp/centreon-plugins-dev/centreon/plugins/snmp.pm line 270

This because in the centreon/plugins/snmp.pm is used for a check ..

```
  if ($self->{use_snmp_cache} == 1) {
        return $self->get_leef_cache(oids => $options{oids}, nothing_quit => $nothing_quit);
   }
```
    
but is never initialized. The only point where it will be init is in the check_options function.
   
Normally the function is always called when you make a snmp plugin because they all derive from centreon::plugins::script_snmp.

but the os-linux-local plugin does not derive from it so it is never called. But the snmp dicovery is in this plugin 

Thanks for help

**Comment by garnier-quentin** [comment]
It's already fixed: https://github.com/centreon/centreon-plugins/pull/4493
