### ISSUE TITLE
os::linux::local::mode::systemdscstatus - check multiple service

### ISSUE THREAD

**Issue by SavCent** [centreon/centreon-plugins#4523]
Bonjour,
je cherche la bonne regex pour filtrer plusieurs services. Le but est de cibler l'ensemble des services centreon.

La commande suivante fonctionne :
**sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1.2.3.4 -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' ' --filter-name="^(?=centreon)+" --verbose'**

Mais pas celle-ci : 
**sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1.2.3.4 -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' ' --filter-name="^(?=centreon)^(?=cbd)+" --verbose'**

Pouvez-vous m'aider ?

Cordialement

**Comment by garnier-quentin** [comment]
Use following regexp: ```--filter-name="^(centreon|cbd)"

**Comment by SavCent** [comment]
Hi Quentin,
this give me this error : 
sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1.2.3.4 -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin'  'systemd-sc-status' ' --filter-name="^(centreon|cbd
)" --verbose'
CHECK_NRPE: Receive header underflow - only 0 bytes received (4 expected).

**Comment by garnier-quentin** [comment]
It works without the filter ?

**Comment by SavCent** [comment]
this work with : 
sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1.2.3.4 -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' ' --filter-name='centreon''
OK: Total Running: 2, Total Failed: 0, Total Dead: 0, Total Exited: 5 - All services are ok | 'total_running'=2;;;0;23 'total_failed'=0;;;0;23 'total_dead'=0;;;0;23 'total_exited'=5;;;0;23

sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1.2.3.4 -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' ' --filter-name='cbd''
OK: Total Running: 1, Total Failed: 0, Total Dead: 0, Total Exited: 0 - Service 'cbd.service' status : loaded/active/running [boot: enabled] | 'total_running'=1;;;0;1 'total_failed'=0;;;0;1 'total_dead'=0;;;0;1 'total_exited'=0;;;0;1

sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1.2.3.4 -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status'  --verbose
OK: Total Running: 43, Total Failed: 0, Total Dead: 104, Total Exited: 35 - All services are ok | 'total_running'=43;;;0;347 'total_failed'=0;;;0;347 'total_dead'=104;;;0;347 'total_exited'=35;;;0;347
Service '-.mount' status : loaded/active/mounted [boot: generated]
Service '-.slice' status : loaded/active/active [boot: -]
Service 'NetworkManager-wait-online.service' status : loaded/active/exited [boot: enabled]
Service 'NetworkManager.service' status : loaded/active/running [boot: enabled]
Service 'atd.service' status : loaded/active/running [boot: enabled]
Service 'auditd.service' status : loaded/active/running [boot: enabled]
Service 'auto-cpufreq.service' status : not-found/inactive/dead [boot: -]
......

**Comment by garnier-quentin** [comment]
Ok i understand. Check your nrpe configuration. I think there are some illegal characters.

**Comment by SavCent** [comment]
I don't know what i need to change in it. We use the default centreon-nrpe3.cfg. We juste have changed port and allow_host.

**Comment by garnier-quentin** [comment]
Check your nrpe configuration. You should have a configuration like ```illegal_charaters``` or ```nasty...```

**Comment by SavCent** [comment]
yes find it
grep nasty /etc/nrpe/centreon-nrpe3.cfg
# nasty_metachars="|`&><'\\[]{};\r\n"

sudo sed -i "s/# nasty/ nasty/g" /etc/nrpe/centreon-nrpe3.cfg
sudo systemctl restart centreon-nrpe3.service
sudo systemctl status centreon-nrpe3.service
● centreon-nrpe3.service - Nagios Remote Program Executor
   Loaded: loaded (/usr/lib/systemd/system/centreon-nrpe3.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2023-06-30 15:32:58 CEST; 16s ago
     Docs: http://www.nagios.org/documentation
  Process: 542551 ExecStopPost=/bin/rm -f /var/log/nrpe/nrpe3.pid (code=exited, status=0/SUCCESS)
  Process: 542552 ExecStart=/usr/sbin/centreon-nrpe3 -c /etc/nrpe/centreon-nrpe3.cfg -d $NRPE_OPT (code=exited, status=0/SUCCESS)
 Main PID: 542554 (centreon-nrpe3)
    Tasks: 1 (limit: 49272)
   Memory: 728.0K
   CGroup: /system.slice/centreon-nrpe3.service
           └─542554 /usr/sbin/centreon-nrpe3 -c /etc/nrpe/centreon-nrpe3.cfg -d

Jun 30 15:32:58 fro1vcsc1 systemd[1]: Starting Nagios Remote Program Executor...
Jun 30 15:32:58 fro1vcsc1 systemd[1]: Started Nagios Remote Program Executor.

sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 10.242.128.100 -p 8084 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' --filter-name='^(centreon|cbd)'
CHECK_NRPE: Receive header underflow - only 0 bytes received (4 expected).

**Comment by garnier-quentin** [comment]
Change the configuration to allow characters like ```|``` and reload the nrpe service

**Comment by SavCent** [comment]
nasty_metachars="`&><'\\[]{};\r\n"

sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 10.242.128.100 -p 8084 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' --filter-name='^(centreon|cbd)'
NRPE: Unable to read output

**Comment by SavCent** [comment]
grep nasty /etc/nrpe/centreon-nrpe3.cfg
# nasty_metachars="|`&><'\\[]{};\r\n"
 nasty_metachars=""
sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1234 -p 1234-t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' --filter-name='^(centreon|cbd)'
NRPE: Unable to read output

**Comment by garnier-quentin** [comment]
Check your nrpe log to see the issue

**Comment by garnier-quentin** [comment]
Use following configuration: ```nasty_metachars="```

**Comment by SavCent** [comment]
Same.
Error: Request contained illegal metachars!

**Comment by garnier-quentin** [comment]
You should use the nrpe EPEL version

**Comment by SavCent** [comment]
we've installed the centreon_nrpe3_plugin like says in the centreon documentation. 
i don't know what package i need too add : 
======================================================================================================== Name Exactly Matched: nrpe =========================================================================================================
nrpe.x86_64 : Host/service/network monitoring agent for Nagios
Repo        : epel
Matched from:
Provide    : nrpe = 4.1.0-2.el8

======================================================================================================= Name & Summary Matched: nrpe ========================================================================================================
centreon-nrpe3-debuginfo.x86_64 : Debug information for package centreon-nrpe3
Repo        : centreon-stable
Matched from:
Provide    : centreon-nrpe3-debuginfo = 4.0.3-0.el7.centos

centreon-nrpe3-plugin.x86_64 : Nagios plug-in for NRPE
Repo        : @System
Matched from:
Provide    : centreon-nrpe3-plugin = 4.0.3-0.el8

centreon-plugin-Applications-Protocol-Nrpe.noarch : Centreon Plugin to trigger commands against NRPE/NSClient agent
Repo        : centreon-stable-noarch
Matched from:
Provide    : centreon-plugin-Applications-Protocol-Nrpe = 20230608-122119.el7

nagios-plugins-nrpe.x86_64 : Provides nrpe plugin for Nagios
Repo        : epel
Matched from:
Provide    : nagios-plugins-nrpe = 4.1.0-2.el8

nrpe-selinux.x86_64 : SELinux context for nrpe
Repo        : epel
Matched from:
Provide    : nrpe-selinux = 4.1.0-2.el8

**Comment by garnier-quentin** [comment]
Install and use the package: ```nrpe```

**Comment by SavCent** [comment]
ok, so i remove the centreon-nrpe3-plugin and i install nrpe

**Comment by garnier-quentin** [comment]
I talk about the nrpe agent first (not the nrpe client)

**Comment by SavCent** [comment]
so the command start like this ?
 sudo -u centreon-engine /usr/sbin/nrpe -H 1234 -p1234 ...

**Comment by garnier-quentin** [comment]
It depends. Use the systemctl start nrpe

**Comment by SavCent** [comment]
Hi Quentin,
i try nrpe and it's get me same result.
systemctl stop centreon-nrpe
systemctl start nrpe
cat /etc/nagios/nrpe.cfg | grep nasty
 nasty_metachars="

sudo systemctl status nrpe.service
● nrpe.service - Nagios Remote Plugin Executor
   Loaded: loaded (/usr/lib/systemd/system/nrpe.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2023-07-03 08:21:18 CEST; 1s ago
     Docs: http://www.nagios.org/documentation
  Process: 1285604 ExecStopPost=/bin/rm -f /run/nrpe/nrpe.pid (code=exited, status=0/SUCCESS)
 Main PID: 1285608 (nrpe)
    Tasks: 1 (limit: 49272)
   Memory: 716.0K
   CGroup: /system.slice/nrpe.service
           └─1285608 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f

sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1234 -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' ' --filter-name="^(centreon)" '
OK: Total Running: 1, Total Failed: 0, Total Dead: 1, Total Exited: 1 - All services are ok | 'total_running'=1;;;0;3 'total_failed'=0;;;0;3 'total_dead'=1;;;0;3 'total_exited'=1;;;0;3
[sysadmin@fro1vcsc1 ~]$ sudo -u centreon-engine /usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 1234  -p 1234 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'systemd-sc-status' ' --filter-name="^(centreon|cbd)" '
CHECK_NRPE: Receive header underflow - only 0 bytes received (4 expected).

**Comment by garnier-quentin** [comment]
It's weird. it should work

**Comment by SavCent** [comment]
i work from central to check central.

**Comment by SavCent** [comment]
Hi, 
i've finally find the solution. Didn't touch the nrpe conf and modifiy the filter like : 
--filter-name="cbd|^cent|gorgoned"
it's work
