### ISSUE TITLE
How to remove commas from perfdata label?

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#4526]
Hello,

In network::cisco::standard::snmp::plugin in environment mode, we get a set of perfdata metrics.
We want to change the names of these metrics to remove everything that we do not need from the name.

For example, in this form we get the metric:

`'Switch 1 - Inlet Temp Sensor, GREEN #hardware.temperature.celsius'=27;;~:56;;`

We use several options:

```
--change-perfdata=".*,,eval(%(label) =~ s/( RED | YELLOW | GREEN |#hardware)//g)"
--change-perfdata=".*,,eval(%(label) =~ s/(\\ |\\/)/_/g)"
--change-perfdata=".*,,eval(%(label) =~ s/_-_/_/g)"
```

As a result, we get the changed metric name

`'Switch_1_Inlet_Temp_Sensor,.temperature.celsius'=27;;~:56;;`

But we cannot remove commas from the metric name.
We have tried adding the following options:
```

--change-perfdata=".*,,eval(%(label) =~ s/,/_/g)"
--change-perfdata=".*,,eval(%(label) =~ s/\,/_/g)"
```

This does not work.

Please tell me how can I remove commas from the name of the metrics?

**Comment by garnier-quentin** [comment]
Use the hexa decimal notation to remove the coma: ```s/\x2c/_/g```

**Comment by Aleksey-Maksimov** [comment]
Thanks Quentin. 
It works.
