### ISSUE TITLE
[network::nokia::timos::snmp::plugin] new mode sas-alarm

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4532]
It should be nice to have a node mode for sas alarms.
relevant SNMP MIB: [TIMETRA-SAS-ALARM-INPUT-MIB.txt](https://github.com/centreon/centreon-plugins/files/11965707/TIMETRA-SAS-ALARM-INPUT-MIB.txt)

SNMP walk:
```
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.2.1 = STRING: "PSU_1_Sammelalarm"
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.2.2 = STRING: "PSU_1_230V_fehlt"
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.2.3 = STRING: "PSU_2_Sammelalarm"
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.2.4 = STRING: "PSU_2_230V_fehlt"
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.3.1 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.3.2 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.3.3 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.3.4 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.4.1 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.4.2 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.4.3 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.4.4 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.5.1 = INTEGER: 3
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.5.2 = INTEGER: 3
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.5.3 = INTEGER: 3
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.5.4 = INTEGER: 3
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.6.1 = INTEGER: 2
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.6.2 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.6.3 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.6.4 = INTEGER: 1
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.7.1 = Timeticks: (280) 0:00:02.80
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.7.2 = Timeticks: (280) 0:00:02.80
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.7.3 = Timeticks: (280) 0:00:02.80
.1.3.6.1.4.1.6527.6.2.2.2.9.1.1.7.4 = Timeticks: (280) 0:00:02.80
```

Alarm should be raised if OID .1.3.6.1.4.1.6527.6.2.2.2.9.1.1.6.<id> = 2
OID .1.3.6.1.4.1.6527.6.2.2.2.9.1.1.7.<id> could be ignored, values are not updated

Output: tmnxSasAlarmInputDescription,  tmnxSasAlarmInputPolarity, tmnxSasAlarmOutputSeverity
It sould be nice to define warning-status and critical-status for tmnxSasAlarmOutputSeverity

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.

**Comment by joschi99** [comment]
Hi @lucie-dubrunfaut,
we have just a working mode done for them. Roman will create a pull request on this.

**Comment by rmorandell-pgum** [comment]
https://github.com/centreon/centreon-plugins/pull/5083
