### ISSUE TITLE
Mode interfaces: add global errors and CRC

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#454]
Add in --add-global option:
- total number of packet errors (for all ports selected)
- total number of crc errors (for all port selected)

**Comment by maksimatveev** [comment]
@garnier-quentin 
RFC1271-MIB
1.3.6.1.2.1.16 (rmon)
1.3.6.1.2.1.16.1 (statistics)
1.3.6.1.2.1.16.1.1 (etherStatsTable)
1.3.6.1.2.1.16.1.1.1 (etherStatsEntry)
1.3.6.1.2.1.16.1.1.1.1 (etherStatsIndex)
1.3.6.1.2.1.16.1.1.1.10 (etherStatsOversizePkts)
1.3.6.1.2.1.16.1.1.1.11 (etherStatsFragments)
1.3.6.1.2.1.16.1.1.1.12 (etherStatsJabbers)
1.3.6.1.2.1.16.1.1.1.13 (etherStatsCollisions)
1.3.6.1.2.1.16.1.1.1.14 (etherStatsPkts64Octets)
1.3.6.1.2.1.16.1.1.1.15 (etherStatsPkts65to127Octets)
1.3.6.1.2.1.16.1.1.1.16 (etherStatsPkts128to255Octets)
1.3.6.1.2.1.16.1.1.1.17 (etherStatsPkts256to511Octets)
1.3.6.1.2.1.16.1.1.1.18 (etherStatsPkts512to1023Octets)
1.3.6.1.2.1.16.1.1.1.19 (etherStatsPkts1024to1518Octets)
1.3.6.1.2.1.16.1.1.1.2 (etherStatsDataSource)
1.3.6.1.2.1.16.1.1.1.20 (etherStatsOwner)
1.3.6.1.2.1.16.1.1.1.21 (etherStatsStatus)
1.3.6.1.2.1.16.1.1.1.3 (etherStatsDropEvents)
1.3.6.1.2.1.16.1.1.1.4 (etherStatsOctets)
1.3.6.1.2.1.16.1.1.1.5 (etherStatsPkts)
1.3.6.1.2.1.16.1.1.1.6 (etherStatsBroadcastPkts)
1.3.6.1.2.1.16.1.1.1.7 (etherStatsMulticastPkts)
1.3.6.1.2.1.16.1.1.1.8 (etherStatsCRCAlignErrors)
1.3.6.1.2.1.16.1.1.1.9 (etherStatsUndersizePkts)
Cisco have a different set of values if I'm not mistaken (1.3.6.1.4.1.9.2.2.1.1.12)

**Comment by garnier-quentin** [comment]
It's done for cisco. And there is an new option: --extend-group-perfdata
