### ISSUE TITLE
[hardware::ups::standard::rfc1628::snmp::plugin] --mode=alarms: add alarm description

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4541]
RFC1628 has a "Alarm table" with upsAlarmDescr and upsAlarmTime: [RFC1628_V2.MIB.txt](https://github.com/centreon/centreon-plugins/files/11974539/RFC1628_V2.MIB.txt)

It should be nice to return as verbose mode the description (and maybe alarm time) on the output. Please not that not every RFC1628 compliant UPS returns the alarm table.

**Comment by garnier-quentin** [comment]
Do you have a snmpwalk with alarms ?

**Comment by garnier-quentin** [comment]
You have an option: ```--display-alarms```

https://github.com/centreon/centreon-plugins/pull/4556

**Comment by joschi99** [comment]
Hi @garnier-quentin,
done a test, the alarm table is working different:
```
 snmpwalk -On -v2c -cpublic 192.168.125.215 .1.3.6.1.2.1.33.1.6.2
.1.3.6.1.2.1.33.1.6.2.1.2.1 = OID: .1.3.6.1.2.1.33.1.6.3.14
.1.3.6.1.2.1.33.1.6.2.1.2.2 = OID: .1.3.6.1.2.1.33.1.6.3.15
.1.3.6.1.2.1.33.1.6.2.1.3.1 = Timeticks: (369000) 1:01:30.00
.1.3.6.1.2.1.33.1.6.2.1.3.2 = Timeticks: (369000) 1:01:30.00
```
As you can see we have 2 alarm entries and the values from OID .1.3.6.1.2.1.33.1.6.2.1.2 are
```
.1.3.6.1.2.1.33.1.6.3.14
.1.3.6.1.2.1.33.1.6.3.15
```
We can map this values to a descrption:
![image](https://github.com/centreon/centreon-plugins/assets/6400595/34fb16b6-3474-4328-8d48-8cc3b5e6cf94)

- .1.3.6.1.2.1.33.1.6.3.14 - upsAlarmUpsOutputOff
- .1.3.6.1.2.1.33.1.6.3.14 -  upsAlarmUpsSystemOff

**Comment by garnier-quentin** [comment]
thanks. i will update it

**Comment by garnier-quentin** [comment]
You can test it. It should be ok now

**Comment by joschi99** [comment]
works, thanks
