### ISSUE TITLE
[hardware::ups::apc::snmp::plugin] how the options warning-replace-lasttime/critical-replace-lasttime work?

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#4546]
Hello.

Please tell me how these two options work:

--warning-replace-lasttime
--critical-replace-lasttime

I don't understand how to correctly set the thresholds for these options

**Comment by garnier-quentin** [comment]
The value is the time in seconds since the last battery replacement. So the value increases.

**Comment by garnier-quentin** [comment]
The UPS uses a different format for the date:
```
upsBasicBatteryLastReplaceDate OBJECT-TYPE
   SYNTAX DisplayString
   ACCESS read-write
   STATUS mandatory
   DESCRIPTION
      "The date when the UPS system's batteries were last replaced 
       in mm/dd/yy (or yyyy) format.  For Smart-UPS models, this value 
       is originally set in the factory.  When the UPS batteries 
       are replaced, this value should be reset by the administrator.
	   For Symmetra PX 250/500 this OID is read only and is configurable in the local display only." 
   ::= { upsBasicBattery 3 }
```

**Comment by Aleksey-Maksimov** [comment]
Quentin, I don't understand how this information answers the question of how to benefit from the warning-replace-lasttime/critical-replace-lasttime options.

**Comment by Aleksey-Maksimov** [comment]
The problem really is that different APC UPSs return the date in a different format. 
For example, in my environment, I meet 3 different variations from different models


```
.1.3.6.1.4.1.318.1.1.1.2.1.3.0 = 06/25/20
...
.1.3.6.1.4.1.318.1.1.1.2.1.3.0 = 01/06/2019
...
.1.3.6.1.4.1.318.1.1.1.2.1.3.0 = 15.12.2016
```

Maybe you could make the plugin more flexible by adding an extra option to define the format?
Like so:

```
--replace-lasttime-format="MM/DD/YY"
...
--replace-lasttime-format="MM/DD/YYYY"
...
--replace-lasttime-format="DD.MM.YYYY"
```

This mechanism would be useful in other UPS plug-ins from other manufacturers.
What do you think of it?

**Comment by garnier-quentin** [comment]
Yes i will add an option

**Comment by Aleksey-Maksimov** [comment]
Cool. Thanks Quentin. I'll be waiting.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4551

**Comment by Aleksey-Maksimov** [comment]
Hello

The plugin output shows the battery life value in seconds:

`WARNING: replace last time: 230546878 s | ...`

 Is it possible to convert it into human readable form? for example per year, month, day
