### ISSUE TITLE
[apps::backup::rubrik::restapi::plugin] mode jobs

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#4552]
Hello,

The API is too long to answer with 500 servers backuped : UNKNOWN : (Process Timeout)
The goal is 900 servers backuped.
At this time, it's not usable.

Is it possible to add two options on this mode :
1- first option to register the API answer in a retention file : this service will be executed each hour and would be associated to the RUBRIK Cluster. It would be --write-retention-file=<PATH/filename> for example.
2- second option to use the retention file instead of API to know the last backup for each server : one service per server executed each 4 hours. It would be --read-retention-file=<PATH/filename> for example.

Thanks

**Comment by ritouret** [comment]
There is a parameter should also help :
/api/v1/job_monitoring?limit=1000

By default, there is only 25 jobs per page.
1000 is the max limit value.

Actually, there is more than 5000 jobs in the last 24h ...

should you add also the parameter limit into this mode ?

Finally, the parameter --timeout does not work.

Thanks

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4566
