### ISSUE TITLE
[cloud::azure::web::appservice::plugin] mode memory: Failed to find privatebytes metric

### ISSUE THREAD

**Issue by giudig** [centreon/centreon-plugins#4555]
Package: package cloud::azure::web::appservice::plugin

privatebytes metrics used in [memory ](https://github.com/centreon/centreon-plugins/blob/master/src/cloud/azure/common/appservice/mode/memory.pm)mode for package cloud::azure::common::appservice and defined in $metrics_mapping is not available anymore. Using --debug this is the reported error by Azure: _Recv data: {"code":"BadRequest","message":"Failed to find metric configuration for provider: Microsoft.Web, resource Type: sites, metric: privatebytes

Removing privatebytes section from $metrics_mapping in memory.pm fix the problem

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4557
