### ISSUE TITLE
supervision fichiers de log

### ISSUE THREAD

**Issue by SavCent** [centreon/centreon-plugins#4559]
Bonjour,

quelle solution sont possible pour les cas suivants :

Analyse de fichier de log type /var/log/messages sur RHEL8 en filtrant sur certaine entré comme ERROR ou WARNING mais en excluant par exemple WARNING-Memory ou WARNING-Texte. Sachant que nous utilisons NRPE3 pour scanner ces hosts comme indiqué dans la documentation Centreon.

Analyse de fichier de log type C:\ORACLE\Program\19\LOG\alerte.log sur Windows server 20XX en filtrant sur certaine entré comme ERROR ou WARNING mais en excluant par exemple WARNING-Memory ou WARNING-Texte. Sachant que nous utilisons NRPE0.5 pour scanner ces hosts comme indiqué dans la documentation Centreon.

Cordialement

**Comment by garnier-quentin** [comment]
Please use following plugins: https://labs.consol.de/nagios/check_logfiles/
It's very good plugin
