### ISSUE TITLE
[apache::serverstatus::plugin] Problem with slotstates

### ISSUE THREAD

**Issue by sulian** [centreon/centreon-plugins#457]
Hello

When I want to test the slotstates mode, I have an error if I use the warning and critical options : 
`/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::apache::serverstatus::plugin --hostname=xxxx --mode=slotstates --warning=xxx`
return : 
`Unknow option: warning at /usr/lib/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 66.`

Did I miss something ??

**Comment by garnier-quentin** [comment]
Hi,

--warning is not a valid option. You can use  --warning-free for example.

**Comment by sulian** [comment]
Ok but why the help show that it is possible to use `--warning` (and `--critical`) ?

**Comment by garnier-quentin** [comment]
I have fixed it ;)
