### ISSUE TITLE
Add plugin disk btrfs

### ISSUE THREAD

**Issue by perkooo** [centreon/centreon-plugins#458]
Hi,

I did not find anything to monitor BTRFS disks, if you know something or if a plugin which can do that would be awesome !

Thanks

**Comment by garnier-quentin** [comment]
Hi Perkooo,

What do you want to monitor on btrfs disks ?

**Comment by perkooo** [comment]
I would like to monitor storage capacity, but with "plugin=os::linux::snmp::plugin --mode=storage".
I only have this with this command : "/run /dev/shm /run/lock /sys" and I can't see others disks (BTRFS).

**Comment by garnier-quentin** [comment]
Can you do a snmpwalk of the oid for storage type ? Maybe there is a new type.

**Comment by perkooo** [comment]
How can I get oid for storage type with snmpwalk command ?

**Comment by garnier-quentin** [comment]
.1.3.6.1.2.1.25.2.3.1.2

**Comment by perkooo** [comment]
I got this : 
HOST-RESOURCES-MIB::hrStorageType.1 = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageType.3 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.6 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.7 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.8 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.10 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.37 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.39 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.40 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.41 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk

**Comment by garnier-quentin** [comment]
Could you also walk: 
.1.3.6.1.2.1.25.2.3.1.3
.1.3.6.1.2.1.25.3.8.1.2

**Comment by perkooo** [comment]
For .1.3.6.1.2.1.25.2.3.1.3 : 
HOST-RESOURCES-MIB::hrStorageDescr.1 = STRING: Physical memory
HOST-RESOURCES-MIB::hrStorageDescr.3 = STRING: Virtual memory
HOST-RESOURCES-MIB::hrStorageDescr.6 = STRING: Memory buffers
HOST-RESOURCES-MIB::hrStorageDescr.7 = STRING: Cached memory
HOST-RESOURCES-MIB::hrStorageDescr.8 = STRING: Shared memory
HOST-RESOURCES-MIB::hrStorageDescr.10 = STRING: Swap space
HOST-RESOURCES-MIB::hrStorageDescr.37 = STRING: /run
HOST-RESOURCES-MIB::hrStorageDescr.39 = STRING: /dev/shm
HOST-RESOURCES-MIB::hrStorageDescr.40 = STRING: /run/lock
HOST-RESOURCES-MIB::hrStorageDescr.41 = STRING: /sys/fs/cgroup

and for .1.3.6.1.2.1.25.3.8.1.2 : 
HOST-RESOURCES-MIB::hrFSMountPoint.7 = STRING: "/run"
HOST-RESOURCES-MIB::hrFSMountPoint.9 = STRING: "/dev/shm"
HOST-RESOURCES-MIB::hrFSMountPoint.10 = STRING: "/run/lock"
HOST-RESOURCES-MIB::hrFSMountPoint.11 = STRING: "/sys/fs/cgroup"

**Comment by garnier-quentin** [comment]
It's a problem of net-snmp it seems. It doesn't display btrfs fs. : https://sourceforge.net/p/net-snmp/bugs/2502/

It needs a newer version of net-snmp.

**Comment by perkooo** [comment]
Thanks for your help :)
