### ISSUE TITLE
Net-Alcatel-OmniSwitch-SNMP-custom display another interface

### ISSUE THREAD

**Issue by Zilone51** [centreon/centreon-plugins#4587]
Hello,

I try to monitor the inteface 1/1 on an alcatel switch which has 12 ports.
I used this command : _`/usr/lib/centreon/plugins//centreon_alcatel_omniswitch_snmp.pl --plugin=network::alcatel::omniswitch::snmp::plugin --mode=interfaces --hostname='1.2.3.4' --snmp-version='2c' --snmp-community='public'  --interface='1/1' --name --add-status --add-traffic --add-errors --warning-status='' --critical-status='%{admstatus} eq "up" and %{opstatus} !~ /up|dormant/' --warning-in-traffic='' --critical-in-traffic='' --warning-out-traffic='' --critical-out-traffic='' --warning-in-discard='' --critical-in-discard='' --warning-out-discard='' --critical-out-discard='' --warning-in-error='' --critical-in-error='' --warning-out-error='' --critical-out-error='' --oid-filter='ifname' --oid-display='ifname' --verbose`_
and and this shows me all the interfaces that start with '1/1' : 
```
_CRITICAL: Interface '1/10' Status : down (admin: up) - Interface '1/11' Status : down (admin: up) - Interface '1/12' Status : down (admin: up) | 'traffic_in_1/1'=177758.14b/s;;;0;1000000000 'traffic_out_1/1'=29528.99b/s;;;0;1000000000 'packets_discard_in_1/1'=0.00%;;;0;100 'packets_error_in_1/1'=0.00%;;;0;100 'packets_discard_out_1/1'=0.00%;;;0;100 'packets_error_out_1/1'=0.00%;;;0;100
Interface '1/1' Status : up (admin: up), Traffic In : 177.76Kb/s (0.02%), Traffic Out : 29.53Kb/s (0.00%), Packets In Discard : 0.00% (0 on 3096176), Packets In Error : 0.00% (0 on 3096176), Packets Out Discard : 0.00% (0 on 830422), Packets Out Error : 0.00% (0 on 830422)
Interface '1/10' Status : down (admin: up)
Interface '1/11' Status : down (admin: up)
Interface '1/12' Status : down (admin: up)_
```
Which sends me an error while the interface that interests me is up !
should I add an option to the command to only have the '1/1' interface ?
thank you in advance for your help.

**Comment by DalfoCentreon** [comment]
Hi! When you use both --interface and --name, the the filter becomes a regex on the name.
```
    --name  Allows to use interface name with option --interface instead of
            interface oid index (Can be a regexp)

    --speed Set interface speed for incoming/outgoing traffic (in Mb).
```
Try this:
`/usr/lib/centreon/plugins//centreon_alcatel_omniswitch_snmp.pl --plugin=network::alcatel::omniswitch::snmp::plugin --mode=interfaces --hostname='1.2.3.4' --snmp-version='2c' --snmp-community='public'  --interface='^1/1$' --name --add-status --add-traffic --add-errors --warning-status='' --critical-status='%{admstatus} eq "up" and %{opstatus} !~ /up|dormant/' --warning-in-traffic='' --critical-in-traffic='' --warning-out-traffic='' --critical-out-traffic='' --warning-in-discard='' --critical-in-discard='' --warning-out-discard='' --critical-out-discard='' --warning-in-error='' --critical-in-error='' --warning-out-error='' --critical-out-error='' --oid-filter='ifname' --oid-display='ifname' --verbose`

Regards,

**Comment by Zilone51** [comment]
Hi,
Thanks a lot for our explanation. 
It's fonctionnal.
Regards.
