### ISSUE TITLE
Change exit code based on long/short output

### ISSUE THREAD

**Issue by wp-perc** [centreon/centreon-plugins#4589]
I start by describing my scenario.

I have a series of hosts sending data to InfluxDB through Telegraf. Therefore, I am using the InfluxDB plugin to monitor its performance. Now, I need to understand if the Telegraf agent is sending me data or not, and get a CRITCAL alert.
This is que query I use:

`SELECT COUNT(uptime) AS messages FROM "telegraf_master"."autogen"."system" WHERE time > now() - 5m and host=~/^myhost.example$/ GROUP BY host;`

If I have data in the specified time window, everything works fine. But if I have NO DATA in the time window, the plugin exposes an unexpected behavior.
```
# /root/centreon-plugins/src/centreon_plugins.pl \
> --plugin 'database::influxdb::plugin' \
> --hostname 'influxdb.neteyelocal' --port '8086' --proto 'https' --ssl 'TLSv1' --username 'USERNAME' --password 'PASSWORD' --http-backend 'lwp' \
> --mode 'query' --timeout '5' \
> --query 'messages,SELECT COUNT(uptime) AS messages FROM "telegraf_master"."autogen"."system" WHERE time > now() - 5m and host=~/^myhost.example$/ GROUP BY host;' \
> --instance 'host' \
> --output 'Received %{messages} messages in the last 5m'
UNKNOWN: No queries found.
#
```
Note that this is not an error of the Plugin, but it is due to a specific behavior of Influxdb that will most likely not be fixed (see https://github.com/influxdata/influxdb/issues/6412).

This is not right, I want to have a CRITICAL back at me: according to the definition of UNKNOWN, absence of metrics can be misunderstood for a poorly written query or a script error. To work around it, I used the `--change-exit` and `--change-short-output`
```
# /root/centreon-plugins/src/centreon_plugins.pl \
> --plugin 'database::influxdb::plugin' \
> --hostname 'influxdb.neteyelocal' --port '8086' --proto 'https' --ssl 'TLSv1' --username 'USERNAME' --password 'PASSWORD' --http-backend 'lwp' \
> --mode 'query' --timeout '5' \
> --query 'messages,SELECT COUNT(uptime) AS messages FROM "telegraf_master"."autogen"."system" WHERE time > now() - 5m and host=~/^myhost.example$/ GROUP BY host;' \
> --instance 'host' \
> --output 'Received %{messages} messages in the last 5m' \
> --change-exit 'unknown=critical' --change-short-output 'UNKNOWN: No queries found.~CRITICAL: No messages received in the last 5m~gi'
CRITICAL: No messages received in the last 5m
#
```

Great, now it works! But... if centreon plugin needs to return an UNKNOWN for any other reason, it simply can't: it will become a CRITICAL. It would be nice if the change in status is performed only in some conditions, based on the plugin output, just like `--filter-perfdata-adv`.

Now my request: Is it possible to implement a --change-exit-adv that performs a change of the exit code based on the plugin output, like --filter-perfdata-adv?

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
