### ISSUE TITLE
database::mysql::plugin / sql-string : Unable to get value into printf-format

### ISSUE THREAD

**Issue by Thibugs** [centreon/centreon-plugins#4596]
Hello,

I'm trying to monitor the state of a galera cluster node using a sql query. I'm able to get the correct result and to get the proper return status, however I'm unable to format the output using --printf-format. The command is as follow : 

`centreon_plugins.pl --plugin database::mysql::plugin --mode sql-string --sql-statement "SHOW GLOBAL STATUS LIKE 'wsrep_ready'" --value-column "Value" --key-column "Variable_name" --host mynode --username username --password password --critical-string "%{value_field} eq 'OFF'" --printf-format='Node readyness is %s'`

I also tried adding `--printf-value "$self->{result_values}->{value_field}"` but it's no better, the output is always `OK: Node readyness is`

Am I missing something ? I tried to search existing issues and Google but the only thing I found was #1896 but the answer seems wrong as --format is not a valid argument.

Thanks for your help.

**Comment by Thibugs** [comment]
After a bit more of tinkering, I found out that if --printf-value is in double quotes, the argument is not correctly parsed. Using single quotes work as intended. Is it a wanted behavior ?

**Comment by lucie-dubrunfaut** [comment]
Hello, 

For your first issue, I've check in sql-string mode to look about it and I've seen that if you use ```printf-format``` you need to define ```printf-value``` :

```
=item B<--printf-format>

Specify a custom output message relying on printf formatting

=item B<--printf-value>

Specify scalar used to replace in printf
(Can be: $self->{result_values}->{key_field}, $self->{result_values}->{value_field})
```

That's why your first usage didn't work.

-------------------------

Then about the simple and double quote, I think it's about using eval function at this line :

https://github.com/centreon/centreon-plugins/blob/develop/src/centreon/common/protocols/sql/mode/sqlstring.pm#L56C9
```
$msg = sprintf("$self->{instance_mode}->{option_results}->{printf_format}", eval $self->{instance_mode}->{option_results}->{printf_value});
```

I'm looking for more explanations about this.

**Comment by Thibugs** [comment]
Hello,

Thanks for your explanation, for the second issue it might be due to bash trying to substitute $self, but it being empty, it obviously doesn't work. If I'm not wrong bash doesn't substitute variables when using single quotes and therefore it doesn't encounter this issue

**Comment by lucie-dubrunfaut** [comment]
The only explanation I found at this moment is if ```$self->{result_values}->{value_field}``` contains a string and not a number there is indeed an issue with eval function :

```
use strict;
use warnings;

#This is the code sample I want to test :
# $msg = sprintf("$self->{instance_mode}->{option_results}->{printf_format}", eval $self->{instance_mode}->{option_results}->{printf_value});

# I use the same $printf_format as in your example
my $printf_format = 'Node readyness is %s' ;

# I test the variable $self->{instance_mode}->{option_results}->{printf_value
# } as a string or as a number (same result for 801 / '801' / "801")
my $var = 'toto';
my $var2 = '801';

################# First with a string : #################
my $printf_value_double_quote = "$var" ;
my $printf_value_simple_quote = '$var' ;

my $msg = sprintf("Double quote : $printf_format", eval $printf_value_double_quote);
my $msg2 = sprintf("Simple quote : $printf_format", eval $printf_value_simple_quote);

print "\$var : $var \n";
print "$msg \n";
print "$msg2 \n";

################# Then with a number #################

my $printf_value_double_quote_2 = "$var2" ;
my $printf_value_simple_quote_2 = '$var2' ;

my $msg3 = sprintf("Double quote : $printf_format", eval $printf_value_double_quote_2);
my $msg4 = sprintf("Simple quote : $printf_format", eval $printf_value_simple_quote_2);

print "\$var2 : $var2 \n";
print "$msg3 \n";
print "$msg4 \n";
```

This returns :

```
Missing argument in sprintf at test.pl line 19.
$var : toto 
Double quote : Node readyness is  
Simple quote : Node readyness is toto 
$var2 : 801 
Double quote : Node readyness is 801 
Simple quote : Node readyness is 801 
```

**Comment by garnier-quentin** [comment]
For me it's worked as expected: ```
$ perl centreon_plugins.pl --plugin database::mysql::plugin --mode sql-string --sql-statement "SHOW GLOBAL STATUS LIKE 'wsrep_ready'" --value-column "Value" --key-column "Variable_name" --host localhost --username root --password centreon --critical-string "%{value_field} eq 'OFF'" --printf-format='Node readyness is %s' --printf-value='$self->{result_values}->{value_field}'
CRITICAL: Node readyness is OFF 
```

If you use some double-quotes ``` --printf-value="$self->{result_values}->{value_field}"``` it will be replaced by the shell (by design).

We could add the capability to use the following syntax: ```--printf-value="%{value_field}"``` also and remove eval.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4631

You can use following syntax: ```--printf-value="%{value_field}"````
