### ISSUE TITLE
[os][linux][snmp][diskio] Add the sum of IO per second

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#46]
Hello,

Is it possible to add a flag in order to get the sum of the I/O and IOPs (write + read) ?

Ex :

OK: Device 'sda' Read I/O : 1.65 KB/s, Read IOPs : 0.08, Write I/O : 43.29 KB/s, Write IOPs : 3.40,* Total I/O : xxxx, Total IOPs : xxxx* | 'read'=1692B/s;;;0; 'read-iops'=0.08iops;;;0; 'write'=44328B/s;;;0; 'write-iops'=3.40iops;;;0; 'total'=44328B/s;;;0; 'total-iops'=3.40iops;;;0;

In some setup (like virtal machines) there is some limits on the sum of IOPs. (you can't do more than X IOPs, sum of read/write)

need of critical/warning thresholds for theses totals (iops & bytes) o

Regard.

**Comment by EChauve** [comment]
Shouldn't it be done through a metaservice inside Centreon?

**Comment by florian-asche** [comment]
Metaservice are hard to configure for many services. 

Add some calculation in mode is easy. Maybe some global function because we can use this in many plugins.
