### ISSUE TITLE
Is the 3CX Plugin compatible with version 18 U8? 

### ISSUE THREAD

**Issue by Bettiol** [centreon/centreon-plugins#4608]
Hi all, 
I tried to configure the plugin to monitor 3CX on a PBX with version 18 Update 8, but the 404 Not Found error is returned.

How can I fix? 

I remain at your disposal for further details/log

Thanks
Ragards

**Comment by garnier-quentin** [comment]
It seems the same issue: https://github.com/centreon/centreon-plugins/issues/4083

Do you have some documentation about it? Or more information on the change ? All modes are impacted ?

**Comment by UrBnW** [comment]
See #4757 👍

**Comment by omercier** [comment]
Fixed with #5093
