### ISSUE TITLE
Azure - Service Health | Planned maintenance

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-plugins#4611]
Hello !
It would be great to get a mode for getting Planned Maintenance.

<img width="948" alt="image" src="https://github.com/centreon/centreon-plugins/assets/664748/35f445c6-940f-4cee-8513-6e8678092fd7">

It seems to make a curl to something like https://management.azure.com/subscriptions/SUBSCRIPTIONID/providers/Microsoft.ResourceHealth/events?api-version=2022-05-01&queryStartTime=2023-07-26T15%3A57%3A09Z&%24filter=Properties%2FEventType%20eq%20'PlannedMaintenance

There is no ressource in this call only a subscription ID
https://learn.microsoft.com/en-us/rest/api/resourcehealth/2022-10-01/availability-statuses/list-by-subscription-id?tabs=HTTP

Thank you

**Comment by garnier-quentin** [comment]
What do you want to monitor exactly about planned maintenance ?

**Comment by fixlair** [comment]
It would be great to get an alert when there a planned maintenance on subscription is announced. Most of the time it's empty but sometimes Azure alert us with an planned maintenance that may cause an outage on some services.
This announce should be handled and then acknowledged until it disapear.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
