### ISSUE TITLE
[network::hp::procurve::snmp::plugin] add new mode for stack

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4612]
We have a Procurve 2920 stack. It should be nice to monitor the stack status.

Here you can find a SNMP walk: 
[procurve-stack.snmpwalk.txt.zip](https://github.com/centreon/centreon-plugins/files/12421402/procurve-stack.snmpwalk.txt.zip)

This are the SNMP MIB's:
[HP-ICF-OID.mib.txt](https://github.com/centreon/centreon-plugins/files/12421430/HP-ICF-OID.mib.txt)
[procurve-stack.mib.txt](https://github.com/centreon/centreon-plugins/files/12421431/procurve-stack.mib.txt)

Did you need anything others?
2155

**Comment by garnier-quentin** [comment]
Everything is ok

**Comment by joschi99** [comment]
are there some news on this?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.

**Comment by joschi99** [comment]
Hi @lucie-dubrunfaut,
@rmorandell-pgum will create a PR for them, we have done a working mode.

**Comment by rmorandell-pgum** [comment]
https://github.com/centreon/centreon-plugins/pull/5082
