### ISSUE TITLE
Error message on SMART UPS 3000 - sensor Input-Lines

### ISSUE THREAD

**Issue by NTIC94130** [centreon/centreon-plugins#4616]
Thanks for using centreon-plugins! Please follow the indications shown below according to your issue and describe it in English.

## Bug/Question

Hello,

Since upgrading to the last version of centreon : 23.04.6

The plugin for hardware ups-apc have been updated to : centreon-plugin-hardware-ups-apc-snmp is the latest version (20230810-100132)
The plugin in connector is updated to version 23.08.0

The device is an SMART UPS 3000 (SMT18UPS)

For all sensors it's ok except for inputs-line who is giving this message now  : 

UNKNOWN: Undefined subroutine &hardware::ups::apc::snmp::mode::inputlines::catalog_status_calc called at /usr/lib/centreon/plugins//centreon_ups_apc.pl line 9681.

I join the snmpwalk for one of this device (that give me the same error on 2 identical devices)
I dont have the mib file for this kind of device

[Onduleur_SmartUPS3000_24082023.txt](https://github.com/centreon/centreon-plugins/files/12430349/Onduleur_SmartUPS3000_24082023.txt)

Sincerelly

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4607
