### ISSUE TITLE
Error plugin Centreon VMWARE Vcenter

### ISSUE THREAD

**Issue by NTIC94130** [centreon/centreon-plugins#4619]
## Bug/Question

Hello,

Since i have upgraded th Vcenter server to version 7.0.3.01500

I have this behavior : 
Using this two plugin : 
centreon-plugin-virtualization-vmware-daemon is latest version (3.2.5-122120)
centreon-plugin-virtualization-vmware2-connector-plugin is latest version (20230810-100132)

For all sensor with container vsphere it's working except for all Datastore sensors : 
Datastore-IO-global - Datastore-Iops-Global - Datastore-Snapshots-Global - Datastore-Usage-Global - Datastore-VM-Count-Global - Datastore-Vm-Count-Generic

Here the result to this command : 
/usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=datastore-io --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='zeus'  --datastore-name='.*' --filter --unknown-status='' --warning-status='' --critical-status='' --warning-total-read='' --critical-total-read='' --warning-total-write='' --critical-total-write='' --warning-read='' --critical-read='' --warning-write='' --critical-write='' --verbose --sampling-period='300'
UNKNOWN: Cannot find 'Datastore' object

It s the same for all Datastore command. The container is zeus (vcenter). The file centreon_vmware.pm is configured : 

%centreon_vmware_config = (
        vsphere_server => {
                        'hera' => {'url' => 'https://172.26.0.25/sdk',
                                     'username' => 'xxxxx',
                                     'password' => 'xxxxx'},
                        'hades' => {'url' => 'https://172.26.0.26/sdk',
                                     'username' => 'xxxxx',
                                     'password' => 'xxxxx'},
                        'hermes' => {'url' => 'https://172.26.0.27/sdk',
                                     'username' => 'xxxxx',
                                     'password' => 'xxxxx'},
                        'zeus' => {'url' => 'https://172.26.0.28/sdk',
                                     'username' => 'xxxxx',
                                     'password' => 'xxxxx'},
                        }
);

1;

If i put an esxi container, it 's working : 
/usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=datastore-io --custommode=connector --connector-hostname='localhost' --objectconnector-port='5700' --container='hera'  --datastore-name='.*' --filter --unknown-status='' --warning-status='' --critical-status='' --warning-total-read='' --critical-total-read='' --warning-total-write='' --critical-total-write='' --warning-read='' --critical-read='' --warning-write='' --critical-write='' --verbose
OK: Total rate of reading data: 0.00 B/s, Total rate of writing data: 0.00 B/s | 'total_read_rate'=0B/s;;;0; 'total_write_rate'=0B/s;;;0;

If i put the vcenter container, i got : UNKNOWN: Cannot find 'Datastore' object

I have try to replace the datastore-name by the real name of the lun and same error

Before upgrading the vcenter server to 7.0.3.01500, i did not have this behavior.

Example of sensor working with container vcenter (zeus) so it's not a problem of identification (account, password): 

/usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=time-host --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='zeus'  --esx-hostname='.*' --filter --unknown-status='' --warning-status='' --critical-status='' --warning-time='-2:2' --critical-time='-5:5' --verbose
OK: All hosts are ok | 'offset_172.26.0.25'=-0.60s;-2:2;-5:5;; 'offset_172.26.0.26'=-0.59s;-2:2;-5:5;; 'offset_172.26.0.27'=-0.58s;-2:2;-5:5;;
Host '172.26.0.25' : status connected, time offset 0 second(s) : 2023-08-25T11:35:55.599069Z
Host '172.26.0.26' : status connected, time offset 0 second(s) : 2023-08-25T11:35:55.589594Z
Host '172.26.0.27' : status connected, time offset 0 second(s) : 2023-08-25T11:35:55.579694Z

Sincerely

**Comment by garnier-quentin** [comment]
I don't think you can monitor datastores directly on a ESXi. You need to monitor with  the vcenter.

**Comment by garnier-quentin** [comment]
Could you test the mode list-datastores ?

**Comment by NTIC94130** [comment]
Hello,

So i have test again. But in doubt, i  modify the password  for the account who had access to the vcenter and i put the administrator role instead of read for this account also.(that was working like this before).
I have done that when seeing in the centreon_vmware.log this line :

2023-08-29 14:06:17 - 'zeus' SOAP request error - possibly a protocol issue: Status read failed:  at /usr/share/perl5/Net/HTTP/Methods.pm line 282

Now the account can connect to the vcenter without limitation and the errors have disappeared. Thanx for your time.

By the way in the centreon_vmware.log , i am seeing this but the esxi can connect and sensors are ok under centreon.
Is it just a message i can ignore ?

2023-08-29 14:07:35 - 'hera' SOAP request error - possibly a protocol issue: Server closed connection without sending any data back at /usr/share/perl5/Net/HTTP/Methods.pm line 391.

2023-08-29 14:15:05 - 'hades' SOAP request error - possibly a protocol issue: Server closed connection without sending any data back at /usr/share/perl5/Net/HTTP/Methods.pm line 391.

2023-08-29 14:18:49 - 'hermes' SOAP request error - possibly a protocol issue: Server closed connection without sending any data back at /usr/share/perl5/Net/HTTP/Methods.pm line 391

Sincerely

**Comment by omercier** [comment]
Hi, it does seem to have happen occasionally on my platform months ago but it must be related to server/network issues and has not been happening for a while.
There is no bug according to me (and it does not come from our code if there is any).
Regards
