### ISSUE TITLE
[hardware::ups::apc::snmp::mode] --mode=inputlines: UNKNOWN: Undefined subroutine

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4621]
Latest plugin version

./centreon_plugins.pl --hostname=x.x.x.x --snmp-community='public' --snmp-version=2c  --plugin=hardware::ups::apc::snmp::plugin --mode=input-lines  --warning-voltage=200:245  --warning-frequence=45:55  --critical-voltage=180:255  --critical-frequence=40:60 --warning-line-frequence= --warning-line-phase-voltage= --warning-line-phase-current= --warning-line-phase-power= --critical-line-frequence= --critical-line-phase-voltage= --critical-line-phase-current= --critical-line-phase-power=
UNKNOWN: Undefined subroutine &hardware::ups::apc::snmp::mode::inputlines::catalog_status_calc called at /tmp/centreon-plugins-develop/src/centreon/plugins/values.pm line 342.

**Comment by joschi99** [comment]
probably the same error like #4616

**Comment by garnier-quentin** [comment]
Exactly. And the fix: https://github.com/centreon/centreon-plugins/pull/4607
