### ISSUE TITLE
[network::cisco::standard::snmp::plugin] --mode=environment : missing PSU component

### ISSUE THREAD

**Issue by FitzXel80** [centreon/centreon-plugins#4625]
Hello, 

We upgraded our Centreon and went to the last version off centreon plugins, but we detect a issue with psu component which are missing.
Only our Nexus 3000 are impacted.

On the last version, actual output : 
centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode='environment' --hostname=X.X.X.X --snmp-version='3'  --snmp-username=*** --authprotocol=SHA --authpassphrase=***  --privprotocol=AES --privpassphrase=***   --component='psu'
OK: All 0 components are ok [].

expected output:
OK: All 2 components are ok [2/2 psus]. | 'count_psu'=2;;;;

OID with --debug option  in last version :
`.1.3.6.1.2.1.47.1.1.1.1.2.10 = Fabric Stack Root
.1.3.6.1.2.1.47.1.1.1.1.2.22 = 48x10GE + 6x40G Supervisor
.1.3.6.1.2.1.47.1.1.1.1.2.149 = N3K-C3172PQ-10GE
.1.3.6.1.2.1.47.1.1.1.1.2.214 = LinecardSlot-1
.1.3.6.1.2.1.47.1.1.1.1.2.278 = PowerSupplyBay-1
.1.3.6.1.2.1.47.1.1.1.1.2.279 = PowerSupplyBay-2
.1.3.6.1.2.1.47.1.1.1.1.2.342 = FanBay-1
.1.3.6.1.2.1.47.1.1.1.1.2.343 = FanBay-2
.1.3.6.1.2.1.47.1.1.1.1.2.344 = FanBay-3
.1.3.6.1.2.1.47.1.1.1.1.2.345 = FanBay-4
.1.3.6.1.2.1.47.1.1.1.1.2.470 = N2200-PAC-400W-1
.1.3.6.1.2.1.47.1.1.1.1.2.471 = N2200-PAC-400W-2
.1.3.6.1.2.1.47.1.1.1.1.2.534 = Fan Module-1
.1.3.6.1.2.1.47.1.1.1.1.2.535 = Fan Module-2
.1.3.6.1.2.1.47.1.1.1.1.2.536 = Fan Module-3
.1.3.6.1.2.1.47.1.1.1.1.2.537 = Fan Module-4
.1.3.6.1.2.1.47.1.1.1.1.2.539 = PowerSupply-1 Fan-1
.1.3.6.1.2.1.47.1.1.1.1.2.540 = PowerSupply-2 Fan-1
.1.3.6.1.2.1.47.1.1.1.1.2.598 = module-1 processor-1
.1.3.6.1.2.1.47.1.1.1.1.2.5206 = Linecard-1 Port-1
.1.3.6.1.2.1.47.1.1.1.1.2.5210 = Linecard-1 Port-5
.1.3.6.1.2.1.47.1.1.1.1.2.5214 = Linecard-1 Port-9
.1.3.6.1.2.1.47.1.1.1.1.2.5218 = Linecard-1 Port-13
.1.3.6.1.2.1.47.1.1.1.1.2.5222 = Linecard-1 Port-17
.1.3.6.1.2.1.47.1.1.1.1.2.5226 = Linecard-1 Port-21
.1.3.6.1.2.1.47.1.1.1.1.2.5230 = Linecard-1 Port-25
.1.3.6.1.2.1.47.1.1.1.1.2.5234 = Linecard-1 Port-29
.1.3.6.1.2.1.47.1.1.1.1.2.5238 = Linecard-1 Port-33
.1.3.6.1.2.1.47.1.1.1.1.2.5242 = Linecard-1 Port-37
.1.3.6.1.2.1.47.1.1.1.1.2.5246 = Linecard-1 Port-41
.1.3.6.1.2.1.47.1.1.1.1.2.5250 = Linecard-1 Port-45
.1.3.6.1.2.1.47.1.1.1.1.2.5254 = Linecard-1 Port-49
.1.3.6.1.2.1.47.1.1.1.1.2.5258 = Linecard-1 Port-53
.1.3.6.1.2.1.47.1.1.1.1.2.5262 = Linecard-1 Port-57
.1.3.6.1.2.1.47.1.1.1.1.2.5266 = Linecard-1 Port-61
.1.3.6.1.2.1.47.1.1.1.1.2.5270 = Linecard-1 Port-65
.1.3.6.1.2.1.47.1.1.1.1.2.5274 = Linecard-1 Port-69
.1.3.6.1.2.1.47.1.1.1.1.2.5278 = Linecard-1 Port-73
.1.3.6.1.2.1.47.1.1.1.1.2.5282 = Linecard-1 Port-77
.1.3.6.1.2.1.47.1.1.1.1.2.5286 = Linecard-1 Port-81
.1.3.6.1.2.1.47.1.1.1.1.2.5290 = Linecard-1 Port-85
.1.3.6.1.2.1.47.1.1.1.1.2.5294 = Linecard-1 Port-89
.1.3.6.1.2.1.47.1.1.1.1.2.5298 = Linecard-1 Port-93
.1.3.6.1.2.1.47.1.1.1.1.2.5302 = Linecard-1 Port-97
.1.3.6.1.2.1.47.1.1.1.1.2.5306 = Linecard-1 Port-101
.1.3.6.1.2.1.47.1.1.1.1.2.5310 = Linecard-1 Port-105
.1.3.6.1.2.1.47.1.1.1.1.2.5314 = Linecard-1 Port-109
.1.3.6.1.2.1.47.1.1.1.1.2.5318 = Linecard-1 Port-113
.1.3.6.1.2.1.47.1.1.1.1.2.5322 = Linecard-1 Port-117
.1.3.6.1.2.1.47.1.1.1.1.2.5326 = Linecard-1 Port-121
.1.3.6.1.2.1.47.1.1.1.1.2.5330 = Linecard-1 Port-125
.1.3.6.1.2.1.47.1.1.1.1.2.5334 = Linecard-1 Port-129
.1.3.6.1.2.1.47.1.1.1.1.2.5338 = Linecard-1 Port-133
.1.3.6.1.2.1.47.1.1.1.1.2.5342 = Linecard-1 Port-137
.1.3.6.1.2.1.47.1.1.1.1.2.5346 = Linecard-1 Port-141
.1.3.6.1.2.1.47.1.1.1.1.2.5350 = Linecard-1 Port-145
.1.3.6.1.2.1.47.1.1.1.1.2.5354 = Linecard-1 Port-149
.1.3.6.1.2.1.47.1.1.1.1.2.5358 = Linecard-1 Port-153
.1.3.6.1.2.1.47.1.1.1.1.2.5362 = Linecard-1 Port-157
.1.3.6.1.2.1.47.1.1.1.1.2.5366 = Linecard-1 Port-161
.1.3.6.1.2.1.47.1.1.1.1.2.5370 = Linecard-1 Port-165
.1.3.6.1.2.1.47.1.1.1.1.2.5374 = Linecard-1 Port-169
.1.3.6.1.2.1.47.1.1.1.1.2.5378 = Linecard-1 Port-173
.1.3.6.1.2.1.47.1.1.1.1.2.5382 = Linecard-1 Port-177
.1.3.6.1.2.1.47.1.1.1.1.2.5386 = Linecard-1 Port-181
.1.3.6.1.2.1.47.1.1.1.1.2.5390 = Linecard-1 Port-185
.1.3.6.1.2.1.47.1.1.1.1.2.5394 = Linecard-1 Port-189
.1.3.6.1.2.1.47.1.1.1.1.2.5398 = Linecard-1 Port-193
.1.3.6.1.2.1.47.1.1.1.1.2.5402 = Linecard-1 Port-197
.1.3.6.1.2.1.47.1.1.1.1.2.5406 = Linecard-1 Port-201
.1.3.6.1.2.1.47.1.1.1.1.2.5410 = Linecard-1 Port-205
.1.3.6.1.2.1.47.1.1.1.1.2.5414 = Linecard-1 Port-209
.1.3.6.1.2.1.47.1.1.1.1.2.5418 = Linecard-1 Port-213
.1.3.6.1.2.1.47.1.1.1.1.2.38486 = module-1             ASIC
.1.3.6.1.2.1.47.1.1.1.1.2.38487 = module-1  Front-Left (D1)
.1.3.6.1.2.1.47.1.1.1.1.2.38488 = module-1  Front-Right(D2)
.1.3.6.1.2.1.47.1.1.1.1.2.38489 = module-1  Back       (D3)
.1.3.6.1.2.1.47.1.1.1.1.2.48854 = Transceiver(slot:1-port:1)
.1.3.6.1.2.1.47.1.1.1.1.2.48856 = Transceiver(slot:1-port:3)
.1.3.6.1.2.1.47.1.1.1.1.2.48857 = Transceiver(slot:1-port:4)
.1.3.6.1.2.1.47.1.1.1.1.2.48858 = Transceiver(slot:1-port:5)
.1.3.6.1.2.1.47.1.1.1.1.2.48859 = Transceiver(slot:1-port:6)
.1.3.6.1.2.1.47.1.1.1.1.2.48860 = Transceiver(slot:1-port:7)
.1.3.6.1.2.1.47.1.1.1.1.2.48861 = Transceiver(slot:1-port:8)
.1.3.6.1.2.1.47.1.1.1.1.2.48864 = Transceiver(slot:1-port:11)
.1.3.6.1.2.1.47.1.1.1.1.2.48865 = Transceiver(slot:1-port:12)
.1.3.6.1.2.1.47.1.1.1.1.2.48866 = Transceiver(slot:1-port:13)
.1.3.6.1.2.1.47.1.1.1.1.2.48867 = Transceiver(slot:1-port:14)
.1.3.6.1.2.1.47.1.1.1.1.2.48868 = Transceiver(slot:1-port:15)
.1.3.6.1.2.1.47.1.1.1.1.2.48869 = Transceiver(slot:1-port:16)
.1.3.6.1.2.1.47.1.1.1.1.2.48874 = Transceiver(slot:1-port:21)
.1.3.6.1.2.1.47.1.1.1.1.2.48875 = Transceiver(slot:1-port:22)
.1.3.6.1.2.1.47.1.1.1.1.2.48876 = Transceiver(slot:1-port:23)
.1.3.6.1.2.1.47.1.1.1.1.2.48877 = Transceiver(slot:1-port:24)
.1.3.6.1.2.1.47.1.1.1.1.2.48878 = Transceiver(slot:1-port:25)
.1.3.6.1.2.1.47.1.1.1.1.2.48879 = Transceiver(slot:1-port:26)
.1.3.6.1.2.1.47.1.1.1.1.2.48880 = Transceiver(slot:1-port:27)
.1.3.6.1.2.1.47.1.1.1.1.2.48881 = Transceiver(slot:1-port:28)
.1.3.6.1.2.1.47.1.1.1.1.2.48882 = Transceiver(slot:1-port:29)
.1.3.6.1.2.1.47.1.1.1.1.2.48883 = Transceiver(slot:1-port:30)
.1.3.6.1.2.1.47.1.1.1.1.2.48884 = Transceiver(slot:1-port:31)
.1.3.6.1.2.1.47.1.1.1.1.2.48885 = Transceiver(slot:1-port:32)
.1.3.6.1.2.1.47.1.1.1.1.2.48886 = Transceiver(slot:1-port:33)
.1.3.6.1.2.1.47.1.1.1.1.2.48887 = Transceiver(slot:1-port:34)
.1.3.6.1.2.1.47.1.1.1.1.2.48889 = Transceiver(slot:1-port:36)
.1.3.6.1.2.1.47.1.1.1.1.2.48890 = Transceiver(slot:1-port:37)
.1.3.6.1.2.1.47.1.1.1.1.2.48891 = Transceiver(slot:1-port:38)
.1.3.6.1.2.1.47.1.1.1.1.2.48892 = Transceiver(slot:1-port:39)
.1.3.6.1.2.1.47.1.1.1.1.2.48893 = Transceiver(slot:1-port:40)
.1.3.6.1.2.1.47.1.1.1.1.2.48894 = Transceiver(slot:1-port:41)
.1.3.6.1.2.1.47.1.1.1.1.2.48895 = Transceiver(slot:1-port:42)
.1.3.6.1.2.1.47.1.1.1.1.2.48896 = Transceiver(slot:1-port:43)
.1.3.6.1.2.1.47.1.1.1.1.2.48897 = Transceiver(slot:1-port:44)
.1.3.6.1.2.1.47.1.1.1.1.2.48898 = Transceiver(slot:1-port:45)
.1.3.6.1.2.1.47.1.1.1.1.2.48899 = Transceiver(slot:1-port:46)
.1.3.6.1.2.1.47.1.1.1.1.2.48901 = Transceiver(slot:1-port:48)
.1.3.6.1.2.1.47.1.1.1.1.2.48902 = Transceiver(slot:1-port:49)
.1.3.6.1.2.1.47.1.1.1.1.2.48903 = Transceiver(slot:1-port:50)
.1.3.6.1.2.1.47.1.1.1.1.2.116950 = Power Supply Group
.1.3.6.1.2.1.47.1.1.1.1.2.300000003 = Ethernet1/1 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300000004 = Ethernet1/1 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300000007 = Ethernet1/1 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300000013 = Ethernet1/1 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300000014 = Ethernet1/1 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300003523 = Ethernet1/3 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300003524 = Ethernet1/3 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300003527 = Ethernet1/3 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300003533 = Ethernet1/3 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300003534 = Ethernet1/3 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300005283 = Ethernet1/4 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300005284 = Ethernet1/4 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300005287 = Ethernet1/4 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300005293 = Ethernet1/4 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300005294 = Ethernet1/4 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300007043 = Ethernet1/5 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300007044 = Ethernet1/5 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300007047 = Ethernet1/5 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300007053 = Ethernet1/5 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300007054 = Ethernet1/5 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300008803 = Ethernet1/6 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300008804 = Ethernet1/6 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300008807 = Ethernet1/6 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300008813 = Ethernet1/6 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300008814 = Ethernet1/6 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300010563 = Ethernet1/7 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300010564 = Ethernet1/7 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300010567 = Ethernet1/7 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300010573 = Ethernet1/7 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300010574 = Ethernet1/7 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300012323 = Ethernet1/8 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300012324 = Ethernet1/8 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300012327 = Ethernet1/8 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300012333 = Ethernet1/8 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300012334 = Ethernet1/8 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300017603 = Ethernet1/11 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300017604 = Ethernet1/11 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300017607 = Ethernet1/11 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300017613 = Ethernet1/11 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300017614 = Ethernet1/11 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300019363 = Ethernet1/12 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300019364 = Ethernet1/12 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300019367 = Ethernet1/12 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300019373 = Ethernet1/12 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300019374 = Ethernet1/12 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300021123 = Ethernet1/13 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300021124 = Ethernet1/13 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300021127 = Ethernet1/13 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300021133 = Ethernet1/13 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300021134 = Ethernet1/13 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300022883 = Ethernet1/14 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300022884 = Ethernet1/14 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300022887 = Ethernet1/14 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300022893 = Ethernet1/14 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300022894 = Ethernet1/14 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300024643 = Ethernet1/15 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300024644 = Ethernet1/15 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300024647 = Ethernet1/15 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300024653 = Ethernet1/15 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300024654 = Ethernet1/15 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300026403 = Ethernet1/16 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300026404 = Ethernet1/16 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300026407 = Ethernet1/16 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300026413 = Ethernet1/16 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300026414 = Ethernet1/16 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300040483 = Ethernet1/24 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300040484 = Ethernet1/24 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300040487 = Ethernet1/24 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300040493 = Ethernet1/24 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300040494 = Ethernet1/24 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300045763 = Ethernet1/27 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300045764 = Ethernet1/27 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300045767 = Ethernet1/27 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300045773 = Ethernet1/27 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300045774 = Ethernet1/27 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300047523 = Ethernet1/28 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300047524 = Ethernet1/28 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300047527 = Ethernet1/28 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300047533 = Ethernet1/28 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300047534 = Ethernet1/28 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300054563 = Ethernet1/32 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300054564 = Ethernet1/32 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300054567 = Ethernet1/32 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300054573 = Ethernet1/32 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300054574 = Ethernet1/32 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300056323 = Ethernet1/33 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300056324 = Ethernet1/33 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300056327 = Ethernet1/33 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300056333 = Ethernet1/33 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300056334 = Ethernet1/33 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300058083 = Ethernet1/34 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300058084 = Ethernet1/34 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300058087 = Ethernet1/34 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300058093 = Ethernet1/34 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300058094 = Ethernet1/34 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300061603 = Ethernet1/36 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300061604 = Ethernet1/36 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300061607 = Ethernet1/36 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300061613 = Ethernet1/36 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300061614 = Ethernet1/36 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300063363 = Ethernet1/37 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300063364 = Ethernet1/37 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300063367 = Ethernet1/37 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300063373 = Ethernet1/37 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300063374 = Ethernet1/37 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300065123 = Ethernet1/38 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300065124 = Ethernet1/38 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300065127 = Ethernet1/38 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300065133 = Ethernet1/38 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300065134 = Ethernet1/38 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300066883 = Ethernet1/39 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300066884 = Ethernet1/39 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300066887 = Ethernet1/39 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300066893 = Ethernet1/39 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300066894 = Ethernet1/39 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300068643 = Ethernet1/40 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300068644 = Ethernet1/40 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300068647 = Ethernet1/40 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300068653 = Ethernet1/40 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300068654 = Ethernet1/40 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300070403 = Ethernet1/41 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300070404 = Ethernet1/41 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300070407 = Ethernet1/41 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300070413 = Ethernet1/41 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300070414 = Ethernet1/41 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300072163 = Ethernet1/42 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300072164 = Ethernet1/42 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300072167 = Ethernet1/42 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300072173 = Ethernet1/42 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300072174 = Ethernet1/42 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300073923 = Ethernet1/43 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300073924 = Ethernet1/43 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300073927 = Ethernet1/43 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300073933 = Ethernet1/43 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300073934 = Ethernet1/43 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300075683 = Ethernet1/44 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300075684 = Ethernet1/44 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300075687 = Ethernet1/44 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300075693 = Ethernet1/44 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300075694 = Ethernet1/44 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300077443 = Ethernet1/45 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300077444 = Ethernet1/45 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300077447 = Ethernet1/45 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300077453 = Ethernet1/45 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300077454 = Ethernet1/45 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300079203 = Ethernet1/46 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300079204 = Ethernet1/46 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300079207 = Ethernet1/46 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300079213 = Ethernet1/46 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300079214 = Ethernet1/46 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300082723 = Ethernet1/48 Lane 1 Transceiver Voltage Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300082724 = Ethernet1/48 Lane 1 Transceiver Bias Current Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300082727 = Ethernet1/48 Lane 1 Transceiver Temperature Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300082733 = Ethernet1/48 Lane 1 Transceiver Receive Power Sensor
.1.3.6.1.2.1.47.1.1.1.1.2.300082734 = Ethernet1/48 Lane 1 Transceiver Transmit Power Sensor
.1.3.6.1.4.1.9.9.117.1.1.2.1.2.470 = 2
.1.3.6.1.4.1.9.9.117.1.1.2.1.2.471 = 2
Environment type: unknown
Checking power supplies
`

**Comment by garnier-quentin** [comment]
Could you add following option ? ```--add-fru-power```

**Comment by FitzXel80** [comment]
Hi,

With this option, PSU are present.

Thanks
