### ISSUE TITLE
[network::stormshield::snmp::plugin] - mode(vpn-status): OK even no SA detected

### ISSUE THREAD

**Issue by labostorm** [centreon/centreon-plugins#4627]
Hi,

I have a problem with Stormshield / vpnstatus plugin.

My objective is to trigger an alarm when one of my IPSec VPN is not UP (no matter the KO state).

Command : `/usr/lib/centreon/plugins/centreon_stormshield_snmp.pl --plugin network::stormshield::snmp::plugin --mode vpn-status <SNMP_SETTINGS> --filter-dst-ip 10.0.0.1 --critical-status '%{state} ne "installed" or %{ipDst} eq ""' --critical-vpn-detected 1`

Result : `OK:  | 'vpn.detected.count'=0;;0:0;0;`

=> IPSec SA (destination endpoint = 10.0.0.1) does not exist, but I get an OK status... ?!
=> How "critical-vpn-detected" option works ? => I expect to set a number of SA that must be present to return OK, and CRITICAL otherwise... But this option seems to monitor the opposite : A max VPN SA threshold... right ?

Thanks a lot for your help @omercier @garnier-quentin @kduret duret :D

Pierre

**Comment by labostorm** [comment]
UP :)

**Comment by omercier** [comment]
Hi,
Can you try this command?
`/usr/lib/centreon/plugins/centreon_stormshield_snmp.pl --plugin network::stormshield::snmp::plugin --mode vpn-status <SNMP_SETTINGS> --filter-dst-ip 10.0.0.1 --critical-status '%{state} ne "installed" or %{ipDst} eq ""' --critical-vpn-detected 1:1`

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @labostorm if you still need a response / solution to this issue, can you try the command @omercier link above?

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time.Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the issue.
