### ISSUE TITLE
Unable to filter based on volume name with the storage::synology::snmp::plugin

### ISSUE THREAD

**Issue by MichelGreijmans** [centreon/centreon-plugins#4630]
I'm trying to use the storage::synology::snmp::plugin plugin to show the utilized disk space of the Synology volumes. However as shown below it's still outputting all drives. Also it appears it's also outputting the "total" performance data incorrectly (missing the drive specification).

./centreon_plugins.pl --plugin storage::synology::snmp::plugin --host xx --snmp-community xx --snmp-version 2c --mode storage --regexp --name='/volume1' --explode-perfdata-max='used,total'
OK: All storages are ok | 'count'=7;;;0; 'used_/'=1116000256B;;;0;2442780672 'used_/tmp'=1257472B;;;0;958447616 'used_/run'=4149248B;;;0;958447616 'used_/dev/shm'=4096B;;;0;958447616 'used_/sys/fs/cgroup'=0B;;;0;4096 'used_/run/cgmanager/fs'=0B;;;0;102400 'used_/volume1'=2372029501440B;;;0;3836004409344 'total'=2442780672B;;;; 'total'=958447616B;;;; 'total'=958447616B;;;; 'total'=958447616B;;;; 'total'=4096B;;;; 'total'=102400B;;;; 'total'=3836004409344B;;;;

**Comment by garnier-quentin** [comment]
Good options are: ```--storage='/volume1' --regexp --name``` 

And the option to explode: ```--extend-perfdata='used_(.*),$1_total,eval($values->{value} = $values->{max}; $values->{max} = ""),0'```
