### ISSUE TITLE
[storage::netapp::ontap::oncommandapi::plugin] - mode(cluster-io & volumes): UNKNOWN: 500 Can't Connect to hostname:443

### ISSUE THREAD

**Issue by pero60** [centreon/centreon-plugins#4632]
Hello,

I'm trying to get the plugin to work but I'm having a problem with the url-path for some unknown reason it doesn't take the '/' as a character, can you help me with this?

**Comment by garnier-quentin** [comment]
Try to use following options: ```--http-backend=curl --insecure```

**Comment by pero60** [comment]
I have this error:
UNKNOWN: 401 Unauthorized

I'm on a local network and there's no firewall

**Comment by garnier-quentin** [comment]
Which plugin do you use ? Could we have the command line ? It seems like an authentication issue now

**Comment by pero60** [comment]
J’utilise le plugin « netapp notamment oncommand API »,

Command Line: 
/usr/lib/centreon/plugin/centreon_netapp_ontap_oncommandapi.pl --plugin=storage::netapp::ontap::oncommandapi::plugin --mode=cluster-io --hostname='@IP' --url-path='/api/' --port='443' --proto='https' --username='admin' --password='mypassword' --filter-name=''

Command return : 404 not found

**Comment by pero60** [comment]
I use the "netapp ontap oncommand API" plugin,

**Comment by lzmarouane** [comment]
i have the same issue with my netapp : 
`/usr/lib/centreon/plugins//centreon_netapp_ontap_oncommandapi.pl --plugin=storage::netapp::ontap::oncommandapi::plugin --mode=volumes --hostname='@ip' --url-path='/api/4.0/ontap' --port='443' --proto='https' --username='admin' --password='password'  --filter-volume-key='' --filter-volume-name='' --filter-volume-state='' --filter-volume-style='' --filter-volume-type='' --filter-svm-name='' --warning-compression-saved-prct='' --critical-compression-saved-prct='' --warning-deduplication-saved-prct='' --critical-deduplication-saved-prct='' --warning-snapshots-reserve-usage-prct='' --critical-snapshots-reserve-usage-prct='' --warning-inodes-usage-prct='' --critical-inodes-usage-prct='' --warning-average-latency='' --critical-average-latency='' --warning-read-latency='' --critical-read-latency='' --warning-write-latency='' --critical-write-latency='' --warning-other-latency='' --critical-other-latency='' --warning-status='' --critical-status='%{state} !~ /online/i' --warning-read-iops='' --critical-read-iops='' --warning-write-iops='' --critical-write-iops='' --warning-other-iops='' --critical-other-iops='' --warning-space-usage='' --critical-space-usage='' --warning-space-usage-free='' --critical-space-usage-free='' --warning-space-usage-prct='' --critical-space-usage-prct='' --verbose`

**Comment by lucie-dubrunfaut** [comment]
Hello :)

First, can you @pero60 and @lzmarouane tell me if this issue looks similar to this https://github.com/centreon/centreon-plugins/issues/4420 to avoid duplicate? I've noticed it's not exactly the same plugin but it's appears similar at the first view.

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time. Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the issue.
