### ISSUE TITLE
Issue with the plugin network::fortinet::fortigate::plugin for monitoring interfaces

### ISSUE THREAD

**Issue by NauGui** [centreon/centreon-plugins#4633]
Hi,

I want my command to return CRITICAL when the interface is up with this command :
/usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=interfaces --hostname ****** --snmp-version='2c' --snmp-community='****' --interface='port6' --name --critical-status='%{status} !~ /down/'

But I always have the same result :
CRITICAL: Interface 'port6' Status : up (admin: up)
CRITICAL: Interface 'port6' Status : down (admin: down)

I tried mutliple synthax but always the same result : eq, !=

Thx,

**Comment by garnier-quentin** [comment]
It's following syntax: ```--critical-status='%{opstatus} !~ /down/'````

**Comment by NauGui** [comment]
Thx for the quick response it's working 👍 . Do you know where I can find the list of variable because I found the "status" directly in the code centreon_fortinet_fortigate.pl.

**Comment by garnier-quentin** [comment]
It's in the help:
```
=item B<--critical-status>

Define the conditions to match for the status to be CRITICAL (Default: '%{admstatus} eq "up" and %{opstatus} ne "up"').
You can use the following variables: %{admstatus}, %{opstatus}, %{duplexstatus}, %{display}
```
