### ISSUE TITLE
[apps::vmware::connector::plugin] --mode=status-cluster: UNKNOWN: Cannot get response (timeout received)

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4635]
Latest plugins, latest vmware connector
VMware ESXi 7.0.3

We have 1 Cluster with name "Cluster"
```
 --mode=list-clusters --verbose
List cluster(s):
  Cluster
```

```
Cluster status monitoring not works:
 --plugin=apps::vmware::connector::plugin --custommode=connector --mode=status-cluster  --filter  --cluster-name='.*'  --debug
UNKNOWN: Cannot get response (timeout received)
```

```
 --plugin=apps::vmware::connector::plugin --custommode=connector --mode=status-cluster  --filter  --cluster-name='^Cluster$'  --debug
UNKNOWN: Cannot get response (timeout received)
```

Any idea?

**Comment by garnier-quentin** [comment]
Do you have something in the log ? You check the ESXi directly ? (not the vcenter)

**Comment by joschi99** [comment]
the problem seems related on the vCenter version 8.x.

**Comment by joschi99** [comment]
Are there any news on this? We have seen this problem on different vSphere versions. Any idea? What do you need to identify the problem?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Can you tell me if this issue is only linked on vCenter version 8 and above? We are currently working on a new version of our connector for VMWare 8 and above internally. Especially because it has been reported to us that the current connector does not work completely with these versions

**Comment by joschi99** [comment]
Hi @lucie-dubrunfaut,
we have found the problem. The problem was that we had 2 different versions for VMware Perl SDK and VMware Perl vSAN SDK. Using for both the same version works. I close the ticket.
