### ISSUE TITLE
[storage::exagrid::snmp::plugin] - mode(server-usage): Negative values

### ISSUE THREAD

**Issue by Meistercoach83** [centreon/centreon-plugins#4638]
Good Morning,
I´m using the exagrid plugin with this check config: 

`/usr/lib/centreon/plugins//centreon_exagrid_snmp.pl --plugin=storage::exagrid::snmp::plugin --mode=server-usage --hostname=******* --snmp-version='******' --snmp-community='******'  --warning-status='%{status} =~ /warning/i' --critical-status='%{status} =~ /error/i' --warning-retention-usage='85' --critical-retention-usage='95' --warning-landing-usage='85' --critical-landing-usage='95' `

with that command I get the following returned infos: CRITICAL: Landing Usage Total: 76.40 TB Used: -42.54 TB (-55.68%) Free: 118.94 TB (155.68%)

How can the used space be negative?
With the debug option it looks like this:

` /usr/lib/centreon/plugins//centreon_exagrid_snmp.pl --plugin=storage::exagrid::snmp::plugin --mode=server-usage --hostname=172.16.253.1 --snmp-version='2c' --snmp-community='public'  --warning-status='%{status} =~ /warning/i' --critical-status='%{status} =~ /error/i' --warning-retention-usage='85' --critical-retention-usage='95' --warning-landing-usage='85' --critical-landing-usage='95' --debug
CRITICAL: Landing Usage Total: 76.40 TB Used: -42.54 TB (-55.68%) Free: 118.94 TB (155.68%) | 'landing_used'=-46771000000000B;0:71400000000000;0:79800000000000;0;84000000000000 'retention_used'=36723000000000B;0:70969900000000;0:79319300000000;0;83494000000000
.1.3.6.1.4.1.14941.4.1.1.0 = 84000
.1.3.6.1.4.1.14941.4.1.2.0 = 0
.1.3.6.1.4.1.14941.4.1.3.0 = 130771
.1.3.6.1.4.1.14941.4.1.4.0 = 886130522
.1.3.6.1.4.1.14941.4.2.1.0 = 83494
.1.3.6.1.4.1.14941.4.2.2.0 = 830000000
.1.3.6.1.4.1.14941.4.2.3.0 = 46771
.1.3.6.1.4.1.14941.4.2.4.0 = 886130522
.1.3.6.1.4.1.14941.4.2.5.0 = 32088
.1.3.6.1.4.1.14941.4.2.6.0 = 196110401
.1.3.6.1.4.1.14941.4.2.7.0 = 0
.1.3.6.1.4.1.14941.4.2.8.0 = 0
.1.3.6.1.4.1.14941.4.2.9.0 = 4634
.1.3.6.1.4.1.14941.4.2.10.0 = 747759077
.1.3.6.1.4.1.14941.4.2.11.0 = 0
.1.3.6.1.4.1.14941.4.2.12.0 = 0
.1.3.6.1.4.1.14941.4.2.13.0 = 4634
.1.3.6.1.4.1.14941.4.2.14.0 = 747759077
.1.3.6.1.4.1.14941.4.3.1.0 = 103665
.1.3.6.1.4.1.14941.4.3.2.0 = 529301438
.1.3.6.1.4.1.14941.4.3.3.0 = 32088
.1.3.6.1.4.1.14941.4.3.4.0 = 196110401
.1.3.6.1.4.1.14941.4.4.1.0 = 0
.1.3.6.1.4.1.14941.4.4.2.0 = 0
.1.3.6.1.4.1.14941.4.4.3.0 = 0
.1.3.6.1.4.1.14941.4.5.1.0 = 0
.1.3.6.1.4.1.14941.4.5.2.0 = 0
.1.3.6.1.4.1.14941.4.5.3.0 = 0
.1.3.6.1.4.1.14941.4.6.1.0 = 1
.1.3.6.1.4.1.14941.4.7.1.0 = 0
.1.3.6.1.4.1.14941.4.7.2.0 = 0
.1.3.6.1.4.1.14941.4.7.3.0 = 0
`

**Comment by garnier-quentin** [comment]
There is an issue with SNMP values. As you can see the space available is greater than the configured. Is it ok ?
```
.1.3.6.1.4.1.14941.4.1.1.0 = 84000 (egLandingSpaceConfiguredWholeGigabytes)
.1.3.6.1.4.1.14941.4.1.3.0 = 130771 (egLandingSpaceAvailableWholeGigabytes)
```

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @Meistercoach83 if you still need a response / solution to this issue, can you take a look at Quentin question above?

**Comment by Meistercoach83** [comment]
Yes, i still need Support. What do you need to Help me?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

According with Quentin's answer it seems that there is an issue with SNMP values itself 
`egLandingSpaceAvailableWholeGigabytes > egLandingSpaceConfiguredWholeGigabytes`
and in the plugin the landing used is calculated this way:
`landing_used => $result->{egLandingSpaceConfiguredWholeGigabytes} * 1000 * 1000 * 1000 - $result->{egLandingSpaceAvailableWholeGigabytes} * 1000 * 1000 * 1000`
see [line171](https://github.com/centreon/centreon-plugins/blob/develop/src/storage/exagrid/snmp/mode/serverusage.pm#L171) in serverusage mode
This lead to a negative value for the landing used.

**Comment by Meistercoach83** [comment]
but how can i fix that? 

i´m currently in holidays till the end of next week

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I will find out if there are any proposed solutions from my colleagues for this SNMP issue.
I will try to keep you informed.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Unfortunately I'm not aware of any solution that might meet your needs, given that it's an issue on the equipment side we're not able to resolve it (the plugin should work normally). I feel obliged to close this issue and suggest that you contact the support team for your equipment, who will probably be better able to define the reasons for the values you are observing.

**Comment by Meistercoach83** [comment]
@lucie-dubrunfaut the equipment has no errors and displays the values correctly. We bought the plugins so i think we should get some help, no?!
