### ISSUE TITLE
[network::aruba::aoscx::snmp::plugin] mode hardware on switch Aruba 6300M 24SFP+ 4SFP56 wrong critical

### ISSUE THREAD

**Issue by andickts** [centreon/centreon-plugins#4641]
The Command

'/usr/lib/centreon/plugins/centreon-plugins/src/centreon_plugins.pl' '--snmp-timeout' '5' '--hostname' 'YYYYYYY' '--plugin' 'network::aruba::aoscx::snmp::plugin' '--mode' 'hardware' '--snmp-community' 'XXXXXX'

Return on swich Aruba 6300M 24SFP+ 4SFP56  aN uncorrect critical status and the output:

CRITICAL: fan tray '1/1' status is ready - fan tray '1/2' status is ready - fan tray '2/1' status is ready - fan tray '2/2' status is ready”

the problem is that the 'ready' answer is not considered valid in the file

https://github.com/centreon/centreon-plugins/blob/develop/src/network/aruba/aoscx/snmp/mode/hardware.pm

`#######line 34-40)

    $self->{thresholds} = {
        default => [
            ['^ok$', 'OK'],
            ['normal', 'OK'],
            ['.*', 'CRITICAL']
        ]
    };`

We solve the problem with this change:

`#######

    $self->{thresholds} = {
        default => [
            ['^ok$', 'OK'],
            ['normal', 'OK'],
            ['ready', 'OK'],
            ['.*', 'CRITICAL']
        ]
    };`

The detailed plugin output in debug mode is this:

`CRITICAL: fan tray '1/1' status is ready - fan tray '1/2' status is ready - fan tray '2/1' status is ready - fan tray '2/2' status is ready | '1/1#hardware.psu.power.watt'=32W;;;0; '1/2#hardware.psu.power.watt'=16W;;;0; '2/1#hardware.psu.power.watt'=26W;;;0; '2/2#hardware.psu.power.watt'=22W;;;0; '1/1-Switch-ASIC-Internal#hardware.temperature.celsius'=63.50C;;;; '1/1-CPU#hardware.temperature.celsius'=47.81C;;;; '1/1-CPU-Zone-0#hardware.temperature.celsius'=45.00C;;;; '1/1-CPU-Zone-1#hardware.temperature.celsius'=45.00C;;;; '1/1-CPU-Zone-2#hardware.temperature.celsius'=45.00C;;;; '1/1-CPU-Zone-3#hardware.temperature.celsius'=45.00C;;;; '1/1-CPU-Zone-4#hardware.temperature.celsius'=46.00C;;;; '1/1-DDR#hardware.temperature.celsius'=43.50C;;;; '1/1-Inlet-Air#hardware.temperature.celsius'=26.50C;;;; '1/1-Mainboard-IBC#hardware.temperature.celsius'=29.25C;;;; '1/1-Switch-ASIC-Remote#hardware.temperature.celsius'=64.94C;;;; '2/1-Switch-ASIC-Internal#hardware.temperature.celsius'=66.00C;;;; '2/1-CPU#hardware.temperature.celsius'=47.50C;;;; '2/1-CPU-Zone-0#hardware.temperature.celsius'=45.00C;;;; '2/1-CPU-Zone-1#hardware.temperature.celsius'=45.00C;;;; '2/1-CPU-Zone-2#hardware.temperature.celsius'=46.00C;;;; '2/1-CPU-Zone-3#hardware.temperature.celsius'=46.00C;;;; '2/1-CPU-Zone-4#hardware.temperature.celsius'=46.00C;;;; '2/1-DDR#hardware.temperature.celsius'=43.50C;;;; '2/1-Inlet-Air#hardware.temperature.celsius'=27.00C;;;; '2/1-Mainboard-IBC#hardware.temperature.celsius'=29.62C;;;; '2/1-Switch-ASIC-Remote#hardware.temperature.celsius'=67.38C;;;; '1/1/1#hardware.fan.speed.rpm'=4187rpm;;;0; '1/1/2#hardware.fan.speed.rpm'=4167rpm;;;0; '1/2/1#hardware.fan.speed.rpm'=4163rpm;;;0; '1/2/2#hardware.fan.speed.rpm'=4194rpm;;;0; '2/1/1#hardware.fan.speed.rpm'=4089rpm;;;0; '2/1/2#hardware.fan.speed.rpm'=4165rpm;;;0; '2/2/1#hardware.fan.speed.rpm'=4183rpm;;;0; '2/2/2#hardware.fan.speed.rpm'=4139rpm;;;0; 'hardware.fan.count'=8;;;; 'hardware.fantray.count'=4;;;; 'hardware.psu.count'=4;;;; 'hardware.temperature.count'=22;;;;
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.3.1.1 = 1/1
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.3.1.2 = 1/2
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.3.2.1 = 2/1
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.3.2.2 = 2/2
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.4.1.1 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.4.1.2 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.4.2.1 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.4.2.2 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.5.1.1 = JL085A
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.5.1.2 = JL085A
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.5.2.1 = JL085A
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.5.2.2 = JL085A
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.6.1.1 = TH15GZ84FH
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.6.1.2 = TH15GZ83MS
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.6.2.1 = TH15GZ83LC
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.6.2.2 = TH15GZ84FJ
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.7.1.1 = 32
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.7.1.2 = 16
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.7.2.1 = 26
.1.3.6.1.4.1.47196.4.1.1.3.11.2.1.1.7.2.2 = 22
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.3.1.1 = 1/1-Switch-ASIC-Internal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.1 = 1/1-CPU
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.2 = 1/1-CPU-Zone-0
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.3 = 1/1-CPU-Zone-1
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.4 = 1/1-CPU-Zone-2
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.5 = 1/1-CPU-Zone-3
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.6 = 1/1-CPU-Zone-4
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.7 = 1/1-DDR
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.8 = 1/1-Inlet-Air
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.9 = 1/1-Mainboard-IBC
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.1.4.1.10 = 1/1-Switch-ASIC-Remote
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.3.2.1 = 2/1-Switch-ASIC-Internal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.1 = 2/1-CPU
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.2 = 2/1-CPU-Zone-0
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.3 = 2/1-CPU-Zone-1
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.4 = 2/1-CPU-Zone-2
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.5 = 2/1-CPU-Zone-3
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.6 = 2/1-CPU-Zone-4
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.7 = 2/1-DDR
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.8 = 2/1-Inlet-Air
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.9 = 2/1-Mainboard-IBC
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.5.2.4.2.10 = 2/1-Switch-ASIC-Remote
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.3.1.1 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.1 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.2 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.3 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.4 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.5 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.6 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.7 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.8 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.9 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.1.4.1.10 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.3.2.1 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.1 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.2 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.3 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.4 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.5 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.6 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.7 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.8 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.9 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.6.2.4.2.10 = normal
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.3.1.1 = 63500
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.1 = 47812
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.2 = 45000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.3 = 45000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.4 = 45000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.5 = 45000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.6 = 46000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.7 = 43500
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.8 = 26500
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.9 = 29250
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.1.4.1.10 = 64937
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.3.2.1 = 66000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.1 = 47500
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.2 = 45000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.3 = 45000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.4 = 46000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.5 = 46000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.6 = 46000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.7 = 43500
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.8 = 27000
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.9 = 29625
.1.3.6.1.4.1.47196.4.1.1.3.11.3.1.1.7.2.4.2.10 = 67375
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.3.1.1 = 1/1
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.3.1.2 = 1/2
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.3.2.1 = 2/1
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.3.2.2 = 2/2
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.4.1.1 = ready
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.4.1.2 = ready
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.4.2.1 = ready
.1.3.6.1.4.1.47196.4.1.1.3.11.4.1.1.4.2.2 = ready
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.1.1 = 1/1/1
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.1.2 = 1/1/2
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.2.1 = 1/2/1
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.2.2 = 1/2/2
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.2.3.1 = 2/1/1
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.2.3.2 = 2/1/2
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.2.4.1 = 2/2/1
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.2.4.2 = 2/2/2
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.1.1.1 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.1.1.2 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.1.2.1 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.1.2.2 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.2.3.1 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.2.3.2 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.2.4.1 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.5.2.4.2 = ok
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.1.1.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.1.1.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.1.2.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.1.2.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.2.3.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.2.3.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.2.4.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.6.2.4.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.1.1.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.1.1.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.1.2.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.1.2.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.2.3.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.2.3.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.2.4.1 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.7.2.4.2 = N/A
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.1.1.1 = 4187
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.1.1.2 = 4167
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.1.2.1 = 4163
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.1.2.2 = 4194
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.2.3.1 = 4089
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.2.3.2 = 4165
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.2.4.1 = 4183
.1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8.2.4.2 = 4139
checking power supplies
power supply '1/1' status is ok [instance: 1.1, power: 32 W]
power supply '1/2' status is ok [instance: 1.2, power: 16 W]
power supply '2/1' status is ok [instance: 2.1, power: 26 W]
power supply '2/2' status is ok [instance: 2.2, power: 22 W]
checking temperatures
temperature '1/1-Switch-ASIC-Internal' status is normal [instance: 1.3.1.1, current: 63.50 C]
temperature '1/1-CPU' status is normal [instance: 1.4.1.1, current: 47.81 C]
temperature '1/1-CPU-Zone-0' status is normal [instance: 1.4.1.2, current: 45.00 C]
temperature '1/1-CPU-Zone-1' status is normal [instance: 1.4.1.3, current: 45.00 C]
temperature '1/1-CPU-Zone-2' status is normal [instance: 1.4.1.4, current: 45.00 C]
temperature '1/1-CPU-Zone-3' status is normal [instance: 1.4.1.5, current: 45.00 C]
temperature '1/1-CPU-Zone-4' status is normal [instance: 1.4.1.6, current: 46.00 C]
temperature '1/1-DDR' status is normal [instance: 1.4.1.7, current: 43.50 C]
temperature '1/1-Inlet-Air' status is normal [instance: 1.4.1.8, current: 26.50 C]
temperature '1/1-Mainboard-IBC' status is normal [instance: 1.4.1.9, current: 29.25 C]
temperature '1/1-Switch-ASIC-Remote' status is normal [instance: 1.4.1.10, current: 64.94 C]
temperature '2/1-Switch-ASIC-Internal' status is normal [instance: 2.3.2.1, current: 66.00 C]
temperature '2/1-CPU' status is normal [instance: 2.4.2.1, current: 47.50 C]
temperature '2/1-CPU-Zone-0' status is normal [instance: 2.4.2.2, current: 45.00 C]
temperature '2/1-CPU-Zone-1' status is normal [instance: 2.4.2.3, current: 45.00 C]
temperature '2/1-CPU-Zone-2' status is normal [instance: 2.4.2.4, current: 46.00 C]
temperature '2/1-CPU-Zone-3' status is normal [instance: 2.4.2.5, current: 46.00 C]
temperature '2/1-CPU-Zone-4' status is normal [instance: 2.4.2.6, current: 46.00 C]
temperature '2/1-DDR' status is normal [instance: 2.4.2.7, current: 43.50 C]
temperature '2/1-Inlet-Air' status is normal [instance: 2.4.2.8, current: 27.00 C]
temperature '2/1-Mainboard-IBC' status is normal [instance: 2.4.2.9, current: 29.62 C]
temperature '2/1-Switch-ASIC-Remote' status is normal [instance: 2.4.2.10, current: 67.38 C]
checking fans
fan '1/1/1' status is ok [instance: 1.1.1, speed: 4187]
fan '1/1/2' status is ok [instance: 1.1.2, speed: 4167]
fan '1/2/1' status is ok [instance: 1.2.1, speed: 4163]
fan '1/2/2' status is ok [instance: 1.2.2, speed: 4194]
fan '2/1/1' status is ok [instance: 2.3.1, speed: 4089]
fan '2/1/2' status is ok [instance: 2.3.2, speed: 4165]
fan '2/2/1' status is ok [instance: 2.4.1, speed: 4183]
fan '2/2/2' status is ok [instance: 2.4.2, speed: 4139]
checking fan trays
fan tray '1/1' status is ready [instance: 1.1]
fan tray '1/2' status is ready [instance: 1.2]
fan tray '2/1' status is ready [instance: 2.1]
fan tray '2/2' status is ready [instance: 2.2]`

**Comment by garnier-quentin** [comment]
thanks for the issue: https://github.com/centreon/centreon-plugins/pull/4642
