### ISSUE TITLE
[apps::backup::rubrik::restapi::plugin] mode cache

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#4646]
Hello,

Rubrik jobs increase again on our infrastructure and now cache file succeed at around 33%.

Should it be possible to add an option like --extra-urlpath-parameter to add a filter for the GET request ?

Here are described all possible parameters : 
[https://rubrikinc.github.io/api-doc-v1-8.0/#tag/job_monitoring/operation/getJobMonitoringInfo](url)

In our case, we could divide per 3 the GET duration with this parameter :
--extra-urlpath-parameter="job_type=Backup"

Thanks

**Comment by garnier-quentin** [comment]
We can add an option to filter the job_type request with following choice:
```
"Archival" "Backup" "Conversion" "Recovery" "Replication" "Index" "LogBackup" "LogArchival" "LogReplication" "LogShipping"
```

**Comment by ritouret** [comment]
Hello Quentin,

It would be perfect !

**Comment by ritouret** [comment]
Hello Quentin,
We have three others needs on this mode :
- ignore jobs with jobStatus = Canceled or Canceling or CancelingScheduled
- add the option --filter-object-type to filter jobs by objectType (not in the request) with following choice : 
"AppBlueprint" "Db2Database" "Ec2Instance" "ExchangeDatabase" "Hdfs" "HypervVirtualMachine" "LinuxFileset" "ManagedVolume" "Mssql" "NutanixVirtualMachine" "OracleDatabase" "SapHanaDatabase" "ShareFileset" "SnapMirrorCloud" "StorageArrayVolumeGroup" "VcdVapp" "VmwareVirtualMachine" "WindowsFileset" "WindowsVolumeGroup"
- add these  values in the long output : locationName and objectType
