### ISSUE TITLE
[network::fortinet::fortigate::restapi::plugin] error 'UNKNOWN: Not an ARRAY reference at /usr/lib/centreon/plugins//centreon_fortinet_fortigate_restapi.pl line 9337'  on mode system,health 

### ISSUE THREAD

**Issue by legolass73** [centreon/centreon-plugins#4648]
Hello,

I have created centreon services using the REST API fortigate plugin, most of the services work perfectly, but I have 2 services that return errors, except that I can't find the cause.

The services that return an error are System and Health and return this error:

"UNKNOWN: Not an ARRAY reference at /usr/lib/centreon/plugins//centreon_fortinet_fortigate_restapi.pl line 9337 "

I've tried searching the net, but I can't find anything to solve this problem, knowing that I unfortunately don't have the time to learn Perl to solve the problem directly in the code.

my centreon is in 23.04.7 on Debian 11

I even have a command directly following this example that works for centreon: "[https://docs.centreon.com/pp/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi/#how-to-check-in-the-cli-that-the-configuration-is-ok-and-what-are-the-main-options-for](https://docs.centreon.com/pp/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi/#how-to-check-in-the-cli-that-the-configuration-is-ok-and-what-are-the-main-options-for)" but it doesn't work for me.

**Comment by legolass73** [comment]
even with the --debug it shows me nothing but the error

![image](https://github.com/centreon/centreon-plugins/assets/5279851/fd4bffb1-b728-4d7a-a49c-76ecc93c1962)

**Comment by garnier-quentin** [comment]
The option is --debug-stream

**Comment by legolass73** [comment]
this is what --debug-stream gives me

root@centreon-debian:/home/informatique# /usr/lib/centreon/plugins//centreon_fortinet_fortigate_restapi.pl  --mode=system --hostname='192.168.xxx.yyy' --port='2443' --proto='https' --access-token='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' --debug-stream
== Info:   Trying 192.168.xxx.yyy:2443...
== Info: Connected to 192.168.xxx.yyy (192.168.xxx.yyy) port 2443 (#0)
== Info: ALPN, offering h2
== Info: ALPN, offering http/1.1
== Info: successfully set certificate verify locations:
== Info:  CAfile: /etc/ssl/certs/ca-certificates.crt
== Info:  CApath: /etc/ssl/certs
== Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):
== Info: TLSv1.3 (IN), TLS handshake, Server hello (2):
== Info: TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
== Info: TLSv1.3 (IN), TLS handshake, Certificate (11):
== Info: TLSv1.3 (IN), TLS handshake, CERT verify (15):
== Info: TLSv1.3 (IN), TLS handshake, Finished (20):
== Info: TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
== Info: TLSv1.3 (OUT), TLS handshake, Finished (20):
== Info: SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
== Info: ALPN, server accepted to use h2
== Info: Server certificate:
== Info:  subject: CN=FGT_SiteB.domain.fr; CN=FGT_SiteB.domain.lan
== Info:  start date: Aug  8 11:59:04 2023 GMT
== Info:  expire date: Aug  7 11:59:04 2025 GMT
== Info:  subjectAltName: host "192.168.xxx.yyy" matched cert's IP address!
== Info:  issuer: DC=LAN; DC=DOMAIN; CN=Enterprise Certificate Autority
== Info:  SSL certificate verify ok.
== Info: Using HTTP2, server supports multi-use
== Info: Connection state changed (HTTP/2 confirmed)
== Info: Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
== Info: Using Stream ID: 1 (easy handle 0x556dcc571a60)
=> Send header: GET /api/v2/monitor/system/vdom-resource/select/?global=1 HTTP/2
Host: 192.168.xxx.yyy:2443
authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
accept:application/json

== Info: TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
== Info: TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
== Info: old SSL session ID is stale, removing
== Info: Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
=> Recv header: HTTP/2 200
=> Recv header: date: Fri, 08 Sep 2023 08:06:40 GMT
=> Recv header: x-frame-options: SAMEORIGIN
=> Recv header: content-security-policy: frame-ancestors 'self'
=> Recv header: x-xss-protection: 1; mode=block
=> Recv header: cache-control: no-cache, must-revalidate
=> Recv header: content-length: 5421
=> Recv header: content-type: application/json
=> Recv header:
=> Recv data: {
  "http_method":"GET",
  "results":{
    "cpu":0,
    "memory":45,
    "setup_rate":1,
    "is_deletable":false,
    "session":{
      "id":0,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":0,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":0,
      "global_max":0,
      "current_usage":1103,
      "usage_percent":0
    },
    "ipsec-phase1":{
      "id":1,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":2000,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":2000,
      "global_max":2000,
      "current_usage":0,
      "usage_percent":0
    },
    "ipsec-phase2":{
      "id":2,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":2000,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":2000,
      "global_max":2000,
      "current_usage":0,
      "usage_percent":0
    },
    "ipsec-phase1-interface":{
      "id":3,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":0,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":0,
      "global_max":0,
      "current_usage":1,
      "usage_percent":0
    },
    "ipsec-phase2-interface":{
      "id":4,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":0,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":0,
      "global_max":0,
      "current_usage":1,
      "usage_percent":0
    },
    "dialup-tunnel":{
      "id":5,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":0,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":0,
      "global_max":0,
      "current_usage":0,
      "usage_percent":0
    },
    "firewall-policy":{
      "id":6,
      "custom_max":0,
      "min_custom_value":60,
      "max_custom_value":20640,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":20640,
      "global_max":21024,
      "current_usage":60,
      "usage_percent":0
    },
    "firewall-address":{
      "id":7,
      "custom_max":0,
      "min_custom_value":488,
      "max_custom_value":42048,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":42048,
      "global_max":42048,
      "current_usage":488,
      "usage_percent":0
    },
    "firewall-addrgrp":{
      "id":8,
      "custom_max":0,
      "min_custom_value":10,
      "max_custom_value":10692,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":10692,
      "global_max":10692,
      "current_usage":10,
      "usage_percent":0
    },
    "custom-service":{
      "id":9,
      "custom_max":0,
      "min_custom_value":103,
      "max_custom_value":2048,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":2048,
      "global_max":0,
      "current_usage":103,
      "usage_percent":0
    },
    "service-group":{
      "id":10,
      "custom_max":0,
      "min_custom_value":9,
      "max_custom_value":1000,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":1000,
      "global_max":0,
      "current_usage":9,
      "usage_percent":0
    },
    "onetime-schedule":{
      "id":11,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":1000,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":1000,
      "global_max":0,
      "current_usage":0,
      "usage_percent":0
    },
    "recurring-schedule":{
      "id":12,
      "custom_max":0,
      "min_custom_value":3,
      "max_custom_value":512,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":512,
      "global_max":0,
      "current_usage":3,
      "usage_percent":0
    },
    "user":{
      "id":13,
      "custom_max":0,
      "min_custom_value":2,
      "max_custom_value":1000,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":1000,
      "global_max":0,
      "current_usage":2,
      "usage_percent":0
    },
    "user-group":{
      "id":14,
      "custom_max":0,
      "min_custom_value":4,
      "max_custom_value":500,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":500,
      "global_max":0,
      "current_usage":4,
      "usage_percent":0
    },
    "sslvpn":{
      "id":15,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":0,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":0,
      "global_max":0,
      "current_usage":0,
      "usage_percent":0
    },
    "proxy":{
      "id":16,
      "custom_max":0,
      "min_custom_value":1,
      "max_custom_value":12000,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":12000,
      "global_max":12000,
      "current_usage":0,
      "usage_percent":0
    },
    "log-disk-quota":{
      "id":17,
      "custom_max":0,
      "min_custom_value":100,
      "max_custom_value":0,
      "guaranteed":0,
      "min_guaranteed_value":0,
      "max_guaranteed_value":0,
      "global_max":0,
      "current_usage":0,
      "usage_percent":0
    }
  },
  "vdom":"root",
  "path":"system",
  "name":"vdom-resource",
  "action":"select",
  "status":"success",
  "serial":"FG200FT",
  "version":"v7.4.0",
  "build":2360
}
== Info: Connection #0 to host 192.168.xxx.yyy left intact
UNKNOWN: Not an ARRAY reference at /usr/lib/centreon/plugins//centreon_fortinet_fortigate_restapi.pl line 9337.

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4668
