### ISSUE TITLE
Missing Centreon_plugins.pl after installation

### ISSUE THREAD

**Issue by Krungs** [centreon/centreon-plugins#4655]
Hello.

I have following problem. I want to install the centreon_plugins for my icinga server but if I want to run a check, it says me that i have no centreon_plugins.pl.

I did following for the Installation:

```
cd /usr/lib/nagios/plugins
apt install git
git clone https://github.com/centreon/centreon-plugins.git
mkdir -p /var/lib/centreon/centplugins
chmod -R 777 /var/lib/centreon/centplugins
```
At this point all works fine but if I want to run:

`./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=cpu`

it shows me following error:

_-bash: ./centreon_plugins.pl: File or directory not found_

Did i missed something through the installation or did I do something wrong?

Thank you for your help!
Kind regards 
Krungs

**Comment by garnier-quentin** [comment]
Are you in the src directory ?

**Comment by Krungs** [comment]
Ah yes now it works. Thank you for your help!
