### ISSUE TITLE
Plugin : broker-stats : Unknown 

### ISSUE THREAD

**Issue by JLSTYLE** [centreon/centreon-plugins#4657]
**Description**
I  have  a bug with the command for check broker-stats on Centreon v23.04 platform and distribution : alma-linux 9.2

when i check the centreon server with the command broker-stat from central so itself , i have this error :

**command**
`/usr/lib/centreon/plugins//centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --hostname=x.x.x.x --mode=broker-stats --broker-stats-file='/var/lib/centreon-broker/central-broker-master-stats.json' --broker-stats-file='/var/lib/centreon-broker/central-rrd-master-stats.json' --broker-stats-file='/var/lib/centreon-engine/central-module-master-stats.json' --critical-status='%{type} eq "output" and %{queue_file_enabled} =~ /true|yes/i' --verbose `

**Result**
`UNKNOWN: Command error: Host key verification failed.`

i get a error too when i check in CLI with root account
`UNKNOWN: Command error: root@192.168.1.222: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password)`

**Another TEST**
i Have another platform with centreon v19.10 on CentOS 7 and i didn't have this problem when i check this my centreon server and the new centreon server with the same command.

**this is the result**
OK: Broker statistics are ok |
`'speed_events_(external commands)'=0events/s;;;0; 'queued_events_(external commands)'=0events;;;0; 'speed_events_central-broker-master-input'=0events/s;;;0; 'queued_events_central-broker-master-input'=0events;;;0; 'speed_events_central-broker-master-perfdata'=0.935484events/s;;;0; 'queued_events_central-broker-master-perfdata'=0events;;;0; 'speed_events_central-broker-master-sql'=0.935484events/s;;;0; 'queued_events_central-broker-master-sql'=0events;;;0; 'speed_events_central-module-master-output'=0.566667events/s;;;0; 'queued_events_central-module-master-output'=425events;;;0; 'unacknowledged_events_central-module-master-output'=0events;;;0; 'speed_events_central-rrd-master-input'=0events/s;;;0; 'queued_events_central-rrd-master-input'=0events;;;0; 'speed_events_central-rrd-master-output'=0.935484events/s;;;0; 'queued_events_central-rrd-master-output'=0events;;;0; 'speed_events_centreon-broker-master-rrd'=0.935484events/s;;;0; 'queued_events_centreon-broker-master-rrd'=283events;;;0; 'unacknowledged_events_centreon-broker-master-rrd'=0events;;;0`

On the new server 23.04; i tried to export the key ssl on the centreon-engine account i had the same error like in root.

**resum**
when i check itself or the last centreon server in v19.10 i have a problem, when i check from the last version to itself and the new server are working correctly.

**Question**
do you have a idea about this problem, is it a bug or other thing ?

**Comment by garnier-quentin** [comment]
You have an ssh authentication issue with your user. It's not really a centreon-plugins issue. Try first with ssh cli command.

**Comment by JLSTYLE** [comment]
you mean open a ssh session with centreon-engine account or to use the ssh parameters in the broker-stats command ?

**Comment by JLSTYLE** [comment]
Hi omercier,

i tried this section in centreon doc page, but it doesn't running, i have the same error as with root account.

**Comment by omercier** [comment]
Hi,
I tested your command on my EL9 23.04 server:

```
$ /usr/lib/centreon/plugins//centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --hostname=192.168.59.134 --mode=broker-stats --broker-stats-file='/var/lib/centreon-broker/central-broker-master-stats.json' --broker-stats-file='/var/lib/centreon-broker/central-rrd-master-stats.json' --broker-stats-file='/var/lib/centreon-engine/central-module-master-stats.json' --critical-status='%{type} eq "output" and %{queue_file_enabled} =~ /true|yes/i' --verbose 
UNKNOWN: Command error: Host key verification failed. 
```

I got the same error as you.

Then I tried with the tip I gave you:

```
$ /usr/lib/centreon/plugins//centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --hostname=192.168.59.134 --mode=broker-stats --broker-stats-file='/var/lib/centreon-broker/central-broker-master-stats.json' --broker-stats-file='/var/lib/centreon-broker/central-rrd-master-stats.json' --broker-stats-file='/var/lib/centreon-engine/central-module-master-stats.json' --critical-status='%{type} eq "output" and %{queue_file_enabled} =~ /true|yes/i' --verbose --hostname=''
OK: Broker statistics are ok | 'speed_events_BSM'=0.4375events/s;;;0; 'queued_events_BSM'=0events;;;0; 'speed_events_central-broker-master-input'=0events/s;;;0; 'queued_events_central-broker-master-input'=0events;;;0; 'speed_events_central-broker-master-unified-sql'=0.84375events/s;;;0; 'queued_events_central-broker-master-unified-sql'=0events;;;0; 'speed_events_central-module-master-output'=0.466666666666667events/s;;;0; 'queued_events_central-module-master-output'=442events;;;0; 'unacknowledged_events_central-module-master-output'=0events;;;0; 'speed_events_central-rrd-master-input'=0events/s;;;0; 'queued_events_central-rrd-master-input'=0events;;;0; 'speed_events_central-rrd-master-output'=0.84375events/s;;;0; 'queued_events_central-rrd-master-output'=0events;;;0; 'speed_events_centreon-broker-master-rrd'=0.84375events/s;;;0; 'queued_events_centreon-broker-master-rrd'=514events;;;0; 'unacknowledged_events_centreon-broker-master-rrd'=0events;;;0; 'speed_events_splunk-events'=0.4375events/s;;;0; 'queued_events_splunk-events'=0events;;;0;
Endpoint output 'BSM' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.4375/s, Queued Events: 0
Endpoint input 'central-broker-master-input' state : listening, Speed Events: 0/s, Queued Events: 0
Endpoint output 'central-broker-master-unified-sql' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.84375/s, Queued Events: 0
Endpoint output 'central-module-master-output' state : connected [status : reading event from stream] [queue file enabled : no], Speed Events: 0.466666666666667/s, Queued Events: 442, Unacknowledged Events: 0
Endpoint input 'central-rrd-master-input' state : listening, Speed Events: 0/s, Queued Events: 0
Endpoint output 'central-rrd-master-output' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.84375/s, Queued Events: 0
Endpoint output 'centreon-broker-master-rrd' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.84375/s, Queued Events: 514, Unacknowledged Events: 0
Endpoint output 'splunk-events' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.4375/s, Queued Events: 0
```

Can you try again and show me the command + output?

**Comment by gagzou** [comment]
ouah, merci beaucoup pour ce tip, effectivement cela marche !

**Comment by JLSTYLE** [comment]
Perfect, it's running now :-) 

Thank you so much omercier

**Comment by omercier** [comment]
Great!
