### ISSUE TITLE
Error Use of uninitialized value $options{"date"}  in  cloud::cadvisor::restapi::plugin

### ISSUE THREAD

**Issue by nicoden81** [centreon/centreon-plugins#4661]
Hi,
I need some help when using cloud::cadvisor::restapi::plugin plugin.

I need to monitor my containers on a host (no k8s).
Mode list-container is running fine.
In Mode node-status, metric 'Containers running' reports 0 whereas there are 9 containers. Maybe it's right because there are reported as subcontainers in Cadvisor.

My main problem is in container-usage mode (and all other modes), I get an error: 
centreon_plugins.pl --plugin=cloud::cadvisor::restapi::plugin --hostname=xxxxxxx --port='8888' --api-path=/docker --mode=container-usage --use-name --debug

Use of uninitialized value $options{"date"} in pattern match (m//) at /usr/lib/nagios/plugins/centreon-plugins-20230118/cloud/cadvisor/restapi/mode/containerusage.pm line 205.
Use of uninitialized value $options{"date"} in concatenation (.) or string at /usr/lib/nagios/plugins/centreon-plugins-20230118/cloud/cadvisor/restapi/mode/containerusage.pm line 206.
UNKNOWN: Wrong time found ''.

I believe the API is not returning the right information (timestamp is missing).

Could you tell me if it's because of Cadvisor configuration, or if I don't use the plugin right ?

I have attached the debug output .

Thanks.

[cplugin_cadvisor_debug.txt](https://github.com/centreon/centreon-plugins/files/12607624/cplugin_cadvisor_debug.txt)

**Comment by garnier-quentin** [comment]
https://github.com/centreon/centreon-plugins/pull/4667
