### ISSUE TITLE
[storage::wd::nas::snmp::plugin] UNKNOWN: SNMP Table Request: Cant get a single value.

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4669]
We have on a WD NAS error UNKNOWN: SNMP Table Request: Cant get a single value on this modes:

- volumes
- list-volumes
- hardware

Seem's that the OID for this modell are not supportet yet
here you can find the snmp walk for this model: [nas-wd.txt](https://github.com/centreon/centreon-plugins/files/12645204/nas-wd.txt)

**Comment by joschi99** [comment]
This changes should work, maybe you can integrate it:
[wd-nas.zip](https://github.com/centreon/centreon-plugins/files/12670157/wd-nas.zip)

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Thank you for this contribution. I'll close this issue cause it's resolved by this PR https://github.com/centreon/centreon-plugins/pull/4805 https://github.com/centreon/centreon-plugins/pull/4806 https://github.com/centreon/centreon-plugins/pull/4807
If not, feel free to re-open it
