### ISSUE TITLE
new plugin for Huawei WLC controller

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4670]
It should be nice to have a plugin wich allows monitor Huawei Wireless Lan Controller with

- CPU
- Memory
- Hardware
- AP status
- AP discovery
- Interfaces

SNMP MIB: [MIB-V200R021C00SPC100.zip](https://github.com/centreon/centreon-plugins/files/12647598/MIB-V200R021C00SPC100.zip)

I can provide snmpwalk via mail

**Comment by omercier** [comment]
Hi @joschi99 
Can you send me your walk by mail? It's my github login at centreon dot com.

**Comment by joschi99** [comment]
I have sent the walk to you by mail :-)

**Comment by omercier** [comment]
Hi @joschi99 
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas). There is high demand for new plugins and new functionalities on existing plugins, so we have to rely on our community to help us prioritize them.

Can you open one with the link to this issue please?
