### ISSUE TITLE
Package centreon-plugin-operatingsystems-as400-daemon is missing on 22.04

### ISSUE THREAD

**Issue by Julien-Rozet** [centreon/centreon-plugins#4675]
Hi,

It appears that the package centreon-plugin-operatingsystems-as400-daemon is missing on 22.04 repo. It exists on 22.10.

**Comment by omercier** [comment]
Hi @Julien-Rozet,
It seems to me that it's available here:
- EL7: https://packages.centreon.com/artifactory/rpm-standard/22.04/el7/stable/noarch/centreon-plugin-Operatingsystems-AS400-daemon-2.0.2-21.el7.noarch.rpm
- EL8: https://packages.centreon.com/artifactory/rpm-standard/22.04/el8/stable/noarch/centreon-plugin-Operatingsystems-AS400-daemon-2.0.2-21.el8.el8.noarch.rpm

**Comment by Julien-Rozet** [comment]
Hi,

Sorry for that, I'm using Debian 11.

**Comment by omercier** [comment]
You should be able to get it here: https://centreon.jfrog.io/artifactory/apt-plugins-stable/pool/plugins/centreon-plugin-operatingsystems-as400-daemon_2.0.2-bullseye_amd64.deb
