### ISSUE TITLE
filter Current Client AP aruba

### ISSUE THREAD

**Issue by sistemmsn** [centreon/centreon-plugins#4678]
I want to filter the number of users in the app but I get an error

`[root@nagiosxi ~]# /root/centreon-plugins/src/centreon_plugins.pl --plugin=network::aruba::instant::snmp::plugin  --mode=ap-usage --hostname=10.167.10.20  --snmp-community=nagiosxi --filter-name='AP Centro Copiado Piso 1' --filter-counters='clients'`

```
out:

Use of uninitialized value in concatenation (.) or string at /root/centreon-plugins/src/network/aruba/instant/snmp/mode/apusage.pm line 51.
OK: All access points are ok | 'AP  Centro Copiado Piso 1#clients.current.count'=21;;;0;
```

```
[root@nagiosxi ~]# /root/centreon-plugins/src/centreon_plugins.pl --plugin=network::aruba::instant::snmp::plugin  --mode=ap-usage --hostname=10.167.10.200  --snmp-community=nagiosxi --verbose
OK: total access points: 5 - All access points are ok | 'accesspoints.total.count'=5;;;0; 'AP Centro Copiado Piso 1#clients.current.count'=20;;;0; 'AP Centro Copiado Piso 1#cpu.utilization.percentage'=11.00%;;;0;100 'AP Centro Copiado Piso 1#memory.usage.bytes'=222535680B;;;0;527028224 'AP Centro Copiado Piso 1#memory.free.bytes'=304492544B;;;0;527028224 'AP Centro Copiado Piso 1#memory.usage.percentage'=42.22%;;;0;100 'AP Piso 2#clients.current.count'=4;;;0; 'AP Piso 2#cpu.utilization.percentage'=8.00%;;;0;100 'AP Piso 2#memory.usage.bytes'=218173440B;;;0;527028224 'AP Piso 2#memory.free.bytes'=308854784B;;;0;527028224 'AP Piso 2#memory.usage.percentage'=41.40%;;;0;100 'AP Sala Tuxca#clients.current.count'=8;;;0; 'AP Sala Tuxca#cpu.utilization.percentage'=4.00%;;;0;100 'AP Sala Tuxca#memory.usage.bytes'=215785472B;;;0;527028224 'AP Sala Tuxca#memory.free.bytes'=311242752B;;;0;527028224 'AP Sala Tuxca#memory.usage.percentage'=40.94%;;;0;100 'AP Sotano#clients.current.count'=2;;;0; 'AP Sotano#cpu.utilization.percentage'=3.00%;;;0;100 'AP Sotano#memory.usage.bytes'=216870912B;;;0;527028224 'AP Sotano#memory.free.bytes'=310157312B;;;0;527028224 'AP Sotano#memory.usage.percentage'=41.15%;;;0;100 'AP2 Piso 2#clients.current.count'=11;;;0; 'AP2 Piso 2#cpu.utilization.percentage'=11.00%;;;0;100 'AP2 Piso 2#memory.usage.bytes'=218857472B;;;0;527028224 'AP2 Piso 2#memory.free.bytes'=308170752B;;;0;527028224 'AP2 Piso 2#memory.usage.percentage'=41.53%;;;0;100
Access Point 'AP Centro Copiado Piso 1' Status is 'up', Current Clients: 20, Cpu: 11.00%, Memory Total: 502.61 MB Used: 212.23 MB (42.22%) Free: 290.39 MB (57.78%)
Access Point 'AP Piso 2' Status is 'up', Current Clients: 4, Cpu: 8.00%, Memory Total: 502.61 MB Used: 208.07 MB (41.40%) Free: 294.55 MB (58.60%)
Access Point 'AP Sala Tuxca' Status is 'up', Current Clients: 8, Cpu: 4.00%, Memory Total: 502.61 MB Used: 205.79 MB (40.94%) Free: 296.82 MB (59.06%)
Access Point 'AP Sotano' Status is 'up', Current Clients: 2, Cpu: 3.00%, Memory Total: 502.61 MB Used: 206.82 MB (41.15%) Free: 295.79 MB (58.85%)
Access Point 'AP2 Piso 2' Status is 'up', Current Clients: 11, Cpu: 11.00%, Memory Total: 502.61 MB Used: 208.72 MB (41.53%) Free: 293.89 MB (58.47%)
```

```
[root@nagiosxi ~]# /root/centreon-plugins/src/centreon_plugins.pl --plugin=network::aruba::instant::snmp::plugin  --mode=ap-usage --hostname=10.167.10.200  --snmp-community=nagiosxi --filter-name='AP Centro Copiado Piso 1' --filter-counters='clients'
Use of uninitialized value in concatenation (.) or string at /root/centreon-plugins/src/network/aruba/instant/snmp/mode/apusage.pm line 51.
OK: All access points are ok | 'AP Centro Copiado Piso 1#clients.current.count'=20;;;0;
```

**Comment by omercier** [comment]
Hi @sistemmsn, 
Can you run the command with the --debug option to see why there is no value in the concatenation?

**Comment by omercier** [comment]
Hi @sistemmsn 
Can you try with the change from #4726 and tell me if it fixes your issue?

**Comment by sistemmsn** [comment]
I run it but it still does the same, I downloaded the recent version of centreon plugins, but it gave the same result

`[root@nagiosxi src]# ./centreon_plugins.pl --plugin=network::aruba::instant::snmp::plugin  --mode=ap-usage --hostname=10.167.10.200  --snmp-community=nagiosxi  --filter-name='AP Centro Copiado Piso 1' --filter-counters='clients' --debug 
Use of uninitialized value in concatenation (.) or string at /root/centreon-plugins-20230118/src/network/aruba/instant/snmp/mode/apusage.pm line 51.
OK: All access points are ok | 'AP Centro Copiado Piso 1#clients.current.count'=7;;;0;
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.2.112.58.14.202.173.210 = AP Sala Tuxca
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.2.112.58.14.202.175.120 = AP2 Piso 2
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.2.112.58.14.203.129.170 = AP Sotano
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.2.112.58.14.203.129.172 = AP Centro Copiado Piso 1
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.2.112.58.14.203.130.124 = AP Piso 2
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.3.112.58.14.202.173.210 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.3.112.58.14.202.175.120 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.3.112.58.14.203.129.170 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.3.112.58.14.203.129.172 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.3.112.58.14.203.130.124 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.4.112.58.14.202.173.210 = CNBNHMV51G
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.4.112.58.14.202.175.120 = CNBNHMV588
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.4.112.58.14.203.129.170 = CNBVHMV1Y6
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.4.112.58.14.203.129.172 = CNBVHMV1Y7
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.4.112.58.14.203.130.124 = CNBVHMV21L
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.5.112.58.14.202.173.210 = .1.3.6.1.4.1.14823.1.2.59
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.5.112.58.14.202.175.120 = .1.3.6.1.4.1.14823.1.2.59
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.5.112.58.14.203.129.170 = .1.3.6.1.4.1.14823.1.2.59
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.5.112.58.14.203.129.172 = .1.3.6.1.4.1.14823.1.2.59
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.5.112.58.14.203.130.124 = .1.3.6.1.4.1.14823.1.2.59
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.6.112.58.14.202.173.210 = 225
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.6.112.58.14.202.175.120 = 225
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.6.112.58.14.203.129.170 = 225
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.6.112.58.14.203.129.172 = 225
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.6.112.58.14.203.130.124 = 225
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.7.112.58.14.202.173.210 = 16
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.7.112.58.14.202.175.120 = 14
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.7.112.58.14.203.129.170 = 18
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.7.112.58.14.203.129.172 = 11
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.7.112.58.14.203.130.124 = 10
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.8.112.58.14.202.173.210 = 310587392
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.8.112.58.14.202.175.120 = 303828992
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.8.112.58.14.203.129.170 = 306974720
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.8.112.58.14.203.129.172 = 304336896
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.8.112.58.14.203.130.124 = 307851264
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.9.112.58.14.202.173.210 = 1873297500
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.9.112.58.14.202.175.120 = 1898489700
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.9.112.58.14.203.129.170 = 1899655300
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.9.112.58.14.203.129.172 = 1899153000
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.9.112.58.14.203.130.124 = 1899114800
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.10.112.58.14.202.173.210 = 527028224
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.10.112.58.14.202.175.120 = 527028224
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.10.112.58.14.203.129.170 = 527028224
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.10.112.58.14.203.129.172 = 527028224
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.10.112.58.14.203.130.124 = 527028224
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.11.112.58.14.202.173.210 = 1
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.11.112.58.14.202.175.120 = 1
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.11.112.58.14.203.129.170 = 1
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.11.112.58.14.203.129.172 = 1
.1.3.6.1.4.1.14823.2.3.3.1.2.1.1.11.112.58.14.203.130.124 = 1
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.0.145.158.198.89.78 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.0.145.158.234.114.37 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.4.229.152.224.53.169 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.10.198.75.247.228.151 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.16.81.7.70.9.191 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.20.171.197.181.0.69 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.26.57.27.162.141.122 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.26.116.144.27.74.185 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.30.63.236.117.207.223 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.42.145.71.236.126.9 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.44.219.7.42.173.35 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.44.219.7.72.180.18 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.44.219.7.79.46.0 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.52.46.183.70.11.124 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.52.46.183.221.30.84 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.58.212.227.164.58.139 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.60.33.156.223.106.221 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.66.21.205.44.28.214 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.66.130.16.9.57.138 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.78.143.165.222.161.99 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.78.220.47.66.185.173 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.84.141.90.181.16.123 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.90.163.157.9.102.237 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.96.165.226.9.33.133 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.96.227.43.121.175.174 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.96.227.43.122.142.61 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.96.227.43.207.112.11 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.110.127.169.220.92.196 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.114.219.223.84.254.249 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.116.151.121.3.223.205 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.118.30.76.199.86.251 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.128.56.251.116.49.125 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.128.56.251.132.10.48 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.128.56.251.137.85.138 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.130.44.240.149.186.83 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.130.90.58.66.254.161 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.134.68.105.106.252.193 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.134.125.129.149.169.2 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.122.61.222.227.173 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.141.40.46.226.198 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.141.40.67.148.165 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.141.40.67.165.48 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.141.40.210.39.166 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.141.40.210.83.137 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.200.75.48.102.105 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.200.75.74.85.181 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.200.75.74.92.91 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.200.75.74.158.47 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.200.75.74.162.47 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.200.75.74.178.43 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.140.200.75.133.62.63 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.146.41.79.160.128.182 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.150.193.33.101.4.140 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.152.141.70.158.153.249 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.154.209.68.68.147.92 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.158.53.206.190.71.153 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.162.12.170.14.228.110 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.162.19.59.234.238.177 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.168.100.241.111.142.47 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.170.52.106.196.35.183 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.170.159.166.53.42.108 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.172.90.252.141.227.112 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.186.213.248.89.23.138 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.202.84.26.136.74.55 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.206.174.46.229.194.78 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.210.85.166.164.206.58 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.214.9.12.120.46.26 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.214.21.65.5.120.224 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.214.91.125.95.165.141 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.218.135.18.246.213.114 = 10.167.10.242
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.218.152.170.55.73.204 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.218.238.3.48.61.90 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.224.204.248.59.20.91 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.236.240.14.86.117.226 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.238.189.187.87.14.110 = 10.167.10.245
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.242.91.182.213.41.159 = 10.167.10.238
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.242.143.242.6.82.50 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.244.179.1.147.100.228 = 10.167.10.237
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.248.89.113.128.32.190 = 10.167.10.239
.1.3.6.1.4.1.14823.2.3.3.1.2.4.1.4.250.48.168.207.104.69 = 10.167.10.237
skipping access point 'AP2 Piso 2'.
skipping access point 'AP Sotano'.
skipping access point 'AP Piso 2'.
skipping access point 'AP Sala Tuxca'.
Access Point 'AP Centro Copiado Piso 1' Current Clients: 7`

**Comment by omercier** [comment]
Did you checkout the right branch before running the plugin?

```
git fetch
git checkout MON-24263-fix-uninitialized-value
```

**Comment by sistemmsn** [comment]
Excellent, it already worked, I thank you very much, if you need, how else can I support you?

`
 git clone  https://github.com/centreon/centreon-plugins.git
Cloning into 'centreon-plugins'...
remote: Enumerating objects: 133906, done.
remote: Total 133906 (delta 0), reused 0 (delta 0), pack-reused 133906
Receiving objects: 100% (133906/133906), 34.77 MiB | 7.18 MiB/s, done.
Resolving deltas: 100% (66983/66983), done.
[root@nagiosxi ~]# cd centreon-plugins/
[root@nagiosxi centreon-plugins]# git fetch
[root@nagiosxi centreon-plugins]# git checkout MON-24263-fix-uninitialized-value
branch 'MON-24263-fix-uninitialized-value' set up to track 'origin/MON-24263-fix-uninitialized-value'.
Switched to a new branch 'MON-24263-fix-uninitialized-value'

`


`
 ./centreon_plugins.pl --plugin=network::aruba::instant::snmp::plugin  --mode=ap-usage --hostname=10.167.10.200  --snmp-community=nagiosxi  --filter-name='AP Centro Copiado Piso 1' --filter-counters='clients' 
OK: Access Point 'AP Centro Copiado Piso 1' Current Clients: 43 | 'AP GDL Centro Copiado Piso 1#clients.current.count'=43;;;0;
`

**Comment by omercier** [comment]
Thank you for your feedback! We'll merge the PR and publish the fix if regression tests show it's safe.
