### ISSUE TITLE
Incohérence des modes du plugin centreon-nrpe3-plugin

### ISSUE THREAD

**Issue by SavCent** [centreon/centreon-plugins#4682]
Bonjour,

Nous utilisons le plugin centreon-nrpe3-plugin pour superviser les os linux. Il y a une incohérence dans les mode disponible (ou une incohérence dans la documentation...).

En effet, sur la doc https://docs.centreon.com/fr/pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3/ les mode sont les suivants :

Cmd-Generic, Connections-Generic, Cpu, Cpu-Detailed, Disk-Generic-Name, Disk-Global, Disk-IO-Generic-Name, Disk-IO-Global, File-Date-Generic, File-Size-Generic, Inodes-Generic-Name, Inodes-Global, Is-File-Generic, Is-Not-File-Generic, Load, Memory, Packet-Errors-Generic-Name, Packet-Errors-Global, Process-Generic, Systemd-Sc-Status, Swap, Traffic-Generic-Name, Traffic-Global, Uptime

Mais depuis le Collecteur, lorsque je fait un --list-mode ainsi :

/usr/lib64/nagios/plugins/check_centreon_nrpe3 -H 10.19.141.150 -p 8084 -t 5 -u -c check_centreon_plugins -a 'os::linux::local::plugin' 'cpu'  '--list-mode'

J'obtiens la liste suivante (qui correspond au plugin centreon-plugin-Operatingsystems-Linux-Ssh)https://docs.centreon.com/fr/pp/integrations/plugin-packs/procedures/operatingsystems-linux-ssh/ :

check-plugin, cmd-return, connections, cpu, cpu-detailed, directlvm-usage, discovery-snmp, discovery-snmpv3, diskio, files-date, files-size, inodes, list-interfaces, list-partitions, list-storages, load, memory, mountpoint, ntp, open-files, packet-errors, paging, pending-updates, process, quota, storage, swap, systemd-sc-status, traffic, uptime

Voici la liste des packages installés :

rpm -qa centreon\* | sort
centreon-broker-23.04.4-1.el8.x86_64
centreon-broker-cbmod-23.04.4-1.el8.x86_64
centreon-broker-core-23.04.4-1.el8.x86_64
centreon-broker-storage-23.04.4-1.el8.x86_64
centreon-clib-23.04.4-1.el8.x86_64
centreon-common-23.04.8-1.el8.noarch
centreon-connector-23.04.4-1.el8.x86_64
centreon-connector-perl-23.04.4-1.el8.x86_64
centreon-connector-ssh-23.04.4-1.el8.x86_64
centreon-engine-23.04.4-1.el8.x86_64
centreon-engine-daemon-23.04.4-1.el8.x86_64
centreon-engine-extcommands-23.04.4-1.el8.x86_64
centreon-gorgone-23.04.6-1.el8.noarch
centreon-gorgone-centreon-config-23.04.6-1.el8.noarch
centreon-nrpe3-daemon-4.1.0-100134.el8.x86_64
centreon-nrpe3-plugin-4.1.0-100134.el8.x86_64
centreon-perl-libs-23.04.8-1.el8.noarch
centreon-plugin-Applications-Databases-Mysql-20230912-083720.el8.noarch
centreon-plugin-Applications-Databases-Oracle-20230912-083720.el8.noarch
centreon-plugin-Applications-Databases-Postgresql-20230912-083720.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20230912-083720.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20230912-083720.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20230912-083720.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20230912-083720.el8.noarch
centreon-plugin-Applications-Nmap-Cli-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-Bgp-Snmp-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-Dns-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-Ftp-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-Http-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-Ldap-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-Ospf-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-Snmp-20230912-083720.el8.noarch
centreon-plugin-Applications-Protocol-X509-20230912-083720.el8.noarch
centreon-plugin-Applications-Vmware-Vcsa-Snmp-20230912-083720.el8.noarch
centreon-plugin-Applications-Webservers-Iis-Restapi-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Compute-Aks-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Compute-VirtualMachine-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Compute-Vmscalesets-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Management-Costs-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Management-Monitor-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Management-Recovery-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Network-AppGateway-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Network-LoadBalancer-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Network-NetworkInterface-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Network-PublicIP-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Network-VirtualNetwork-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-PolicyInsights-PolicyStates-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Security-KeyVault-Api-20230912-083720.el8.noarch
centreon-plugin-Cloud-Azure-Storage-StorageAccount-Api-20230912-083720.el8.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20230912-083720.el8.noarch
centreon-plugin-Hardware-Servers-Hp-Snmp-20230912-083720.el8.noarch
centreon-plugin-Hardware-Servers-Huawei-Hmm-Snmp-20230912-083720.el8.noarch
centreon-plugin-Hardware-Storage-Hp-Storeonce3-Restapi-20230912-083720.el8.noarch
centreon-plugin-Hardware-Storage-Hp-Storeonce4-Restapi-20230912-083720.el8.noarch
centreon-plugin-Hardware-Storage-Nimble-Restapi-20230912-083720.el8.noarch
centreon-plugin-Hardware-Storage-Nimble-Snmp-20230912-083720.el8.noarch
centreon-plugin-Hardware-Storage-Qnap-Snmp-20230912-083720.el8.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20230912-083720.el8.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20230912-083720.el8.noarch
centreon-plugin-Network-Firewalls-Fortinet-Fortigate-Snmp-20230912-083720.el8.noarch
centreon-plugin-Network-H3c-Snmp-20230912-083720.el8.noarch
centreon-plugin-Network-Huawei-Snmp-20230912-083720.el8.noarch
centreon-plugin-Network-Switchs-Arista-Snmp-20230912-083720.el8.noarch
centreon-plugin-Network-Switchs-Aruba-Standard-Snmp-20230912-083720.el8.noarch
centreon-plugin-Notification-Teams-20230912-083720.el8.noarch
centreon-plugin-Operatingsystems-Linux-Local-20230912-083720.el8.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20230912-083720.el8.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20230912-083720.el8.noarch
centreon-plugins-sudoers-23.04.8-1.el8.noarch
centreon-plugin-Virtualization-Hpe-Simplivity-Restapi-20230912-083720.el8.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20230912-083720.el8.noarch
centreon-plugin-Virtualization-VMWare-daemon-3.2.5-20220816072422.el8.noarch
centreon-poller-23.04.8-1.el8.noarch
centreon-release-22.10-1.el8.noarch
centreon-trap-23.04.8-1.el8.noarch

**Comment by omercier** [comment]
PS: Please only report bugs regarding the plugins, not remarks about the documentation or questions regarding their usage. All details are given in the template that appears when you open a new issue.
