### ISSUE TITLE
[oracle::sqlpluscmd]

### ISSUE THREAD

**Issue by pierhommedba** [centreon/centreon-plugins#4688]
Hello,

why in the pluggin sqlpluscmd.pm we cannot use a "as sysdba" connexion remotely ?

Because this this the onely way to connect to a passive database instance (which is only mounted).

Regards,

**Comment by omercier** [comment]
Hi,
Thanks for your interest in Centreon.
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
