### ISSUE TITLE
[os::linux::local::plugin] mode=diskio Not perfdata

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#469]
Hello!
I stop receiving data through mode diskio:
./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=diskio --filter-perfdata='io_md126$'
OK: All partitions are ok. |

Image data demonstrates that not coming from the plugin:
![centreon-server-disk-io](https://cloud.githubusercontent.com/assets/15804154/17675287/caf22ae6-6331-11e6-9165-45f312a63466.png)

[root@rnd-oms-centreon centreon-plugins]# snmpwalk -v 1 -c public localhost diskIODevice
**UCD-DISKIO-MIB::diskIODevice.25 = STRING: sda
UCD-DISKIO-MIB::diskIODevice.26 = STRING: sdb**
UCD-DISKIO-MIB::diskIODevice.27 = STRING: sr0
UCD-DISKIO-MIB::diskIODevice.28 = STRING: md0
**UCD-DISKIO-MIB::diskIODevice.29 = STRING: md126**
UCD-DISKIO-MIB::diskIODevice.30 = STRING: md126p1
UCD-DISKIO-MIB::diskIODevice.31 = STRING: md126p2
UCD-DISKIO-MIB::diskIODevice.32 = STRING: md126p3
UCD-DISKIO-MIB::diskIODevice.33 = STRING: md126p4
UCD-DISKIO-MIB::diskIODevice.34 = STRING: md126p5
UCD-DISKIO-MIB::diskIODevice.35 = STRING: md126p6

[root@rnd-oms-centreon centreon-plugins]# snmpwalk -v 1 -c public localhost diskIOReads
**UCD-DISKIO-MIB::diskIOReads.25 = Counter32: 127854
UCD-DISKIO-MIB::diskIOReads.26 = Counter32: 129759**
UCD-DISKIO-MIB::diskIOReads.27 = Counter32: 0
UCD-DISKIO-MIB::diskIOReads.28 = Counter32: 0
**UCD-DISKIO-MIB::diskIOReads.29 = Counter32: 309360**
UCD-DISKIO-MIB::diskIOReads.30 = Counter32: 0
UCD-DISKIO-MIB::diskIOReads.31 = Counter32: 0
UCD-DISKIO-MIB::diskIOReads.32 = Counter32: 0
UCD-DISKIO-MIB::diskIOReads.33 = Counter32: 0
UCD-DISKIO-MIB::diskIOReads.34 = Counter32: 0
UCD-DISKIO-MIB::diskIOReads.35 = Counter32: 0

[root@rnd-oms-centreon centreon-plugins]# snmpwalk -v 1 -c public localhost diskIOWrites
**UCD-DISKIO-MIB::diskIOWrites.25 = Counter32: 9971644
UCD-DISKIO-MIB::diskIOWrites.26 = Counter32: 9598272**
UCD-DISKIO-MIB::diskIOWrites.27 = Counter32: 0
UCD-DISKIO-MIB::diskIOWrites.28 = Counter32: 0
**UCD-DISKIO-MIB::diskIOWrites.29 = Counter32: 24989164**
UCD-DISKIO-MIB::diskIOWrites.30 = Counter32: 0
UCD-DISKIO-MIB::diskIOWrites.31 = Counter32: 0
UCD-DISKIO-MIB::diskIOWrites.32 = Counter32: 0
UCD-DISKIO-MIB::diskIOWrites.33 = Counter32: 0
UCD-DISKIO-MIB::diskIOWrites.34 = Counter32: 0
UCD-DISKIO-MIB::diskIOWrites.35 = Counter32: 0

Do a survey conditions have changed the disk subsystem in this mode?

I noticed one more thing:
[root@rnd-oms-centreon centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=diskio --filter-perfdata='**sda**'
OK: All partitions are ok. |
[root@rnd-oms-centreon centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=diskio --filter-perfdata='**sdb**'
OK: All partitions are ok. | 'readio_sdb'=0.00B/s;;;0; 'writeio_sdb'=660821.33B/s;;;0; 'readtime_sdb'=0ms;;;0; 'writetime_sdb'=16557ms;;;0; 'utils_sdb'=10.81%;;;0;100
Although it is already visible in the output snmpwalk of that data may get.

**Comment by garnier-quentin** [comment]
What do you have if you remove the option --filter-perfdata='io_md126$' ?

**Comment by maksimatveev** [comment]
@garnier-quentin 
[root@rnd-oms-centreon centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=diskio
OK: All partitions are ok. | 'readio_0'=0.00B/s;;;0; 'writeio_0'=0.00B/s;;;0; 'readtime_0'=0ms;;;0; 'writetime_0'=0ms;;;0; 'utils_0'=0.00%;;;0;100 'readio_loop1'=0.00B/s;;;0; 'writeio_loop1'=0.00B/s;;;0; 'readtime_loop1'=0ms;;;0; 'writetime_loop1'=0ms;;;0; 'utils_loop1'=0.00%;;;0;100 'readio_loop3'=0.00B/s;;;0; 'writeio_loop3'=0.00B/s;;;0; 'readtime_loop3'=0ms;;;0; 'writetime_loop3'=0ms;;;0; 'utils_loop3'=0.00%;;;0;100 'readio_loop5'=0.00B/s;;;0; 'writeio_loop5'=0.00B/s;;;0; 'readtime_loop5'=0ms;;;0; 'writetime_loop5'=0ms;;;0; 'utils_loop5'=0.00%;;;0;100 'readio_loop7'=0.00B/s;;;0; 'writeio_loop7'=0.00B/s;;;0; 'readtime_loop7'=0ms;;;0; 'writetime_loop7'=0ms;;;0; 'utils_loop7'=0.00%;;;0;100 'readio_md0'=0.00B/s;;;0; 'writeio_md0'=0.00B/s;;;0; 'readtime_md0'=0ms;;;0; 'writetime_md0'=0ms;;;0; 'utils_md0'=0.00%;;;0;100 'readio_md126p1'=0.00B/s;;;0; 'writeio_md126p1'=0.00B/s;;;0; 'readtime_md126p1'=0ms;;;0; 'writetime_md126p1'=0ms;;;0; 'utils_md126p1'=0.00%;;;0;100 'readio_md126p3'=0.00B/s;;;0; 'writeio_md126p3'=0.00B/s;;;0; 'readtime_md126p3'=0ms;;;0; 'writetime_md126p3'=0ms;;;0; 'utils_md126p3'=0.00%;;;0;100 'readio_md126p5'=0.00B/s;;;0; 'writeio_md126p5'=0.00B/s;;;0; 'readtime_md126p5'=0ms;;;0; 'writetime_md126p5'=0ms;;;0; 'utils_md126p5'=0.00%;;;0;100 'readio_ram1'=0.00B/s;;;0; 'writeio_ram1'=0.00B/s;;;0; 'readtime_ram1'=0ms;;;0; 'writetime_ram1'=0ms;;;0; 'utils_ram1'=0.00%;;;0;100 'readio_ram11'=0.00B/s;;;0; 'writeio_ram11'=0.00B/s;;;0; 'readtime_ram11'=0ms;;;0; 'writetime_ram11'=0ms;;;0; 'utils_ram11'=0.00%;;;0;100 'readio_ram13'=0.00B/s;;;0; 'writeio_ram13'=0.00B/s;;;0; 'readtime_ram13'=0ms;;;0; 'writetime_ram13'=0ms;;;0; 'utils_ram13'=0.00%;;;0;100 'readio_ram15'=0.00B/s;;;0; 'writeio_ram15'=0.00B/s;;;0; 'readtime_ram15'=0ms;;;0; 'writetime_ram15'=0ms;;;0; 'utils_ram15'=0.00%;;;0;100 'readio_ram3'=0.00B/s;;;0; 'writeio_ram3'=0.00B/s;;;0; 'readtime_ram3'=0ms;;;0; 'writetime_ram3'=0ms;;;0; 'utils_ram3'=0.00%;;;0;100 'readio_ram5'=0.00B/s;;;0; 'writeio_ram5'=0.00B/s;;;0; 'readtime_ram5'=0ms;;;0; 'writetime_ram5'=0ms;;;0; 'utils_ram5'=0.00%;;;0;100 'readio_ram7'=0.00B/s;;;0; 'writeio_ram7'=0.00B/s;;;0; 'readtime_ram7'=0ms;;;0; 'writetime_ram7'=0ms;;;0; 'utils_ram7'=0.00%;;;0;100 'readio_ram9'=0.00B/s;;;0; 'writeio_ram9'=0.00B/s;;;0; 'readtime_ram9'=0ms;;;0; 'writetime_ram9'=0ms;;;0; 'utils_ram9'=0.00%;;;0;100 'readio_sdb'=542.84B/s;;;0; 'writeio_sdb'=1037398.36B/s;;;0; 'readtime_sdb'=67ms;;;0; 'writetime_sdb'=2189776ms;;;0; 'utils_sdb'=26.65%;;;0;100

**Comment by garnier-quentin** [comment]
it seems to work. Which perfdatas do you want to keep ?

**Comment by maksimatveev** [comment]
@garnier-quentin "readio_md126" and "writeio_md126"

**Comment by maksimatveev** [comment]
@garnier-quentin "readio_sda", "readio_sdb", "writeio_sda", "writeio_sdb" also

**Comment by garnier-quentin** [comment]
Try following:
```
--filter-perfdata="(readio|writeio)_(sda|sdb|md126)"
```

**Comment by maksimatveev** [comment]
@garnier-quentin and why there is no output sda?

**Comment by maksimatveev** [comment]
@garnier-quentin for "md126" no values, all the zeros, at the same time in the output snmpwalk:
UCD-DISKIO-MIB::diskIODevice.29 = STRING: md126
UCD-DISKIO-MIB::diskIOReads.29 = Counter32: 309360
UCD-DISKIO-MIB::diskIOWrites.29 = Counter32: 24989164

**Comment by garnier-quentin** [comment]
Could you give the result with --verbose ?

**Comment by maksimatveev** [comment]
@garnier-quentin 
[root@rnd-oms-centreon centreon-plugins]# ./centreon_plugins.pl --plugin=os::linux::local::plugin --mode=diskio --verbose
OK: All partitions are ok. | 'readio_0'=0.00B/s;;;0; 'writeio_0'=0.00B/s;;;0; 'readtime_0'=0ms;;;0; 'writetime_0'=0ms;;;0; 'utils_0'=0.00%;;;0;100 'readio_loop1'=0.00B/s;;;0; 'writeio_loop1'=0.00B/s;;;0; 'readtime_loop1'=0ms;;;0; 'writetime_loop1'=0ms;;;0; 'utils_loop1'=0.00%;;;0;100 'readio_loop3'=0.00B/s;;;0; 'writeio_loop3'=0.00B/s;;;0; 'readtime_loop3'=0ms;;;0; 'writetime_loop3'=0ms;;;0; 'utils_loop3'=0.00%;;;0;100 'readio_loop5'=0.00B/s;;;0; 'writeio_loop5'=0.00B/s;;;0; 'readtime_loop5'=0ms;;;0; 'writetime_loop5'=0ms;;;0; 'utils_loop5'=0.00%;;;0;100 'readio_loop7'=0.00B/s;;;0; 'writeio_loop7'=0.00B/s;;;0; 'readtime_loop7'=0ms;;;0; 'writetime_loop7'=0ms;;;0; 'utils_loop7'=0.00%;;;0;100 'readio_md0'=0.00B/s;;;0; 'writeio_md0'=0.00B/s;;;0; 'readtime_md0'=0ms;;;0; 'writetime_md0'=0ms;;;0; 'utils_md0'=0.00%;;;0;100 'readio_md126p1'=0.00B/s;;;0; 'writeio_md126p1'=0.00B/s;;;0; 'readtime_md126p1'=0ms;;;0; 'writetime_md126p1'=0ms;;;0; 'utils_md126p1'=0.00%;;;0;100 'readio_md126p3'=0.00B/s;;;0; 'writeio_md126p3'=0.00B/s;;;0; 'readtime_md126p3'=0ms;;;0; 'writetime_md126p3'=0ms;;;0; 'utils_md126p3'=0.00%;;;0;100 'readio_md126p5'=0.00B/s;;;0; 'writeio_md126p5'=0.00B/s;;;0; 'readtime_md126p5'=0ms;;;0; 'writetime_md126p5'=0ms;;;0; 'utils_md126p5'=0.00%;;;0;100 'readio_ram1'=0.00B/s;;;0; 'writeio_ram1'=0.00B/s;;;0; 'readtime_ram1'=0ms;;;0; 'writetime_ram1'=0ms;;;0; 'utils_ram1'=0.00%;;;0;100 'readio_ram11'=0.00B/s;;;0; 'writeio_ram11'=0.00B/s;;;0; 'readtime_ram11'=0ms;;;0; 'writetime_ram11'=0ms;;;0; 'utils_ram11'=0.00%;;;0;100 'readio_ram13'=0.00B/s;;;0; 'writeio_ram13'=0.00B/s;;;0; 'readtime_ram13'=0ms;;;0; 'writetime_ram13'=0ms;;;0; 'utils_ram13'=0.00%;;;0;100 'readio_ram15'=0.00B/s;;;0; 'writeio_ram15'=0.00B/s;;;0; 'readtime_ram15'=0ms;;;0; 'writetime_ram15'=0ms;;;0; 'utils_ram15'=0.00%;;;0;100 'readio_ram3'=0.00B/s;;;0; 'writeio_ram3'=0.00B/s;;;0; 'readtime_ram3'=0ms;;;0; 'writetime_ram3'=0ms;;;0; 'utils_ram3'=0.00%;;;0;100 'readio_ram5'=0.00B/s;;;0; 'writeio_ram5'=0.00B/s;;;0; 'readtime_ram5'=0ms;;;0; 'writetime_ram5'=0ms;;;0; 'utils_ram5'=0.00%;;;0;100 'readio_ram7'=0.00B/s;;;0; 'writeio_ram7'=0.00B/s;;;0; 'readtime_ram7'=0ms;;;0; 'writetime_ram7'=0ms;;;0; 'utils_ram7'=0.00%;;;0;100 'readio_ram9'=0.00B/s;;;0; 'writeio_ram9'=0.00B/s;;;0; 'readtime_ram9'=0ms;;;0; 'writetime_ram9'=0ms;;;0; 'utils_ram9'=0.00%;;;0;100 'readio_sdb'=1045.79B/s;;;0; 'writeio_sdb'=1052759.15B/s;;;0; 'readtime_sdb'=28ms;;;0; 'writetime_sdb'=1488259ms;;;0; 'utils_sdb'=28.30%;;;0;100
Partition '0' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'loop1' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'loop3' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'loop5' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'loop7' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'md0' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'md126p1' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'md126p3' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'md126p5' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram1' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram11' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram13' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram15' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram3' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram5' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram7' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'ram9' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'sdb' Read I/O : 1.02KB/s, Write I/O : 1.00MB/s, Write Time : 28 ms, Read Time : 1488259 ms, %Utils: 28.30 %

**Comment by garnier-quentin** [comment]
Could you give me two snmpwalk (wait 5 minutes between the two commands) and give me the 2 files : 
snmpwalk -v2c -c public -ObentU IP .1.3.6.1.4.1.2021.13.15 > result1.snmpwalk
snmpwalk -v2c -c public -ObentU IP .1.3.6.1.4.1.2021.13.15 > result2.snmpwalk

**Comment by maksimatveev** [comment]
Hello, Quentin!
Here are the files that you have requested.
[result1.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/426540/result1.snmpwalk.txt)
[result2.snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/426541/result2.snmpwalk.txt)

**Comment by garnier-quentin** [comment]
When i'm looking the output, i don't think you use the last version. You could use that filter-perfdata:
```
--filter-perfdata="(read|write)_(sda|sdb|md126)"
```

**Comment by maksimatveev** [comment]
@garnier-quentin 
Since the values in this case were not:
```
Partition 'md126p1' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'md126p3' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'md126p5' Read I/O : 0.00B/s, Write I/O : 0.00B/s, Write Time : 0 ms, Read Time : 0 ms, %Utils: 0.00 %
Partition 'sdb' Read I/O : 6.00KB/s, Write I/O : 817.33KB/s, Write Time : 14 ms, Read Time : 552 ms, %Utils: 8.29 %
```

**Comment by maksimatveev** [comment]
@garnier-quentin Despite the fact that:
```
UCD-DISKIO-MIB::diskIODevice.25 = STRING: sda
UCD-DISKIO-MIB::diskIODevice.26 = STRING: sdb
UCD-DISKIO-MIB::diskIODevice.29 = STRING: md126
```
```
UCD-DISKIO-MIB::diskIOReads.25 = Counter32: 1982395
UCD-DISKIO-MIB::diskIOReads.26 = Counter32: 1963182
UCD-DISKIO-MIB::diskIOReads.29 = Counter32: 5481541
```
```
UCD-DISKIO-MIB::diskIOWrites.25 = Counter32: 96344741
UCD-DISKIO-MIB::diskIOWrites.26 = Counter32: 91695016
UCD-DISKIO-MIB::diskIOWrites.29 = Counter32: 248256741
```

**Comment by garnier-quentin** [comment]
It's the local check!!! Nothing todo with the snmp.

**Comment by maksimatveev** [comment]
@garnier-quentin oh, f..k!) That's what I inattentive

**Comment by garnier-quentin** [comment]
Can i close it ? I don't understand what if there is still a problem :)

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin yes, all good)

**Comment by maksimatveev** [comment]
!
