### ISSUE TITLE
apps::protocols::x509::plugin UNKNOWN: OK 

### ISSUE THREAD

**Issue by lzmarouane** [centreon/centreon-plugins#4691]
Hi, 
in order to monitor SSL certificat for Cisco ASA, i'm using this command : 
`/usr/lib/centreon/plugins/centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --custommode=https --mode=certificate --hostname=192.168.x.x --port=443 --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --warning-status='%{expiration} <60' --critical-status='%{expiration} <30'`

but i get this  : 

`UNKNOWN: OK`

i tryed this  adding this command --custommode=tcp : 
 but i get this : `UNKNOWN: SSL error: SSL wants a read first`

Any ideas? Thank you in advance

**Comment by omercier** [comment]
Hi,
Can you try the `` option?
See help below:
```
/usr/lib/centreon/plugins/centreon_protocol_x509.pl --plugin=apps::protocols::x509::plugin --custommode=tcp  --mode certificate --help 
[...]
    --ssl-ignore-errors
            Ignore SSL handshake errors. For example: 'SSL error: SSL wants
            a read first'.
[...]
```
Sorry for that, but starting today, request for troubleshooting like this must be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md), updated after you filed this one).
Thank you for your understanding.
