### ISSUE TITLE
[hardware::pdu::raritan::snmp::plugin] No results 

### ISSUE THREAD

**Issue by Erawor** [centreon/centreon-plugins#4693]
Hey!
I'd like to monitor the PDUs, but the plugin doesn't return any results.

**Centreon v. 23.04.9 EL9
Plugin v.23.04
RARITAN Dominion PX-5297**

```
[centreon-engine@central ]$ /usr/lib/centreon/plugins/centreon_pdu_raritan_snmp.pl --plugin=hardware::pdu::raritan::snmp::plugin --hostname='ip' --snmp-version='2c' --snmp-community='pub' --snmp-timeout=10 --verbose --mode=inlet-sensors
OK: All 0 components are ok [].
[centreon-engine@central]$ /usr/lib/centreon/plugins/centreon_pdu_raritan_snmp.pl --plugin=hardware::pdu::raritan::snmp::plugin --hostname='ip' --snmp-version='2c' --snmp-community='pub' --snmp-timeout=10 --verbose --mode=ocprot-sensors
OK: All 0 components are ok [].
[centreon-engine@central]$ /usr/lib/centreon/plugins/centreon_pdu_raritan_snmp.pl --plugin=hardware::pdu::raritan::snmp::plugin --hostname='ip' --snmp-version='2c' --snmp-community='pub' --snmp-timeout=10 --verbose --mode=outlet-sensors
OK: All 0 components are ok [].
```

any idea please.
Thanks.
[MIB.txt](https://github.com/centreon/centreon-plugins/files/12849859/MIB.txt)

**Comment by omercier** [comment]
Hi @Erawor,
Could you provide the result of `snmpwalk -ObentU -v 2c -c pub ip .1.3.6.1.4.1` please ?

**Comment by Erawor** [comment]
Hi @omercier 
thanks for help.
[result.txt](https://github.com/centreon/centreon-plugins/files/12853408/result.txt)

**Comment by Erawor** [comment]
any idea please ?
thanks

**Comment by omercier** [comment]
Hi, 
There is no bug, actually. The existing plugin is just not designed for your device. All the OIDs we are looking for are beginning with `.1.3.6.1.4.1.13742.6` whereas yours returns only OIDs beginning with `.1.3.6.1.4.1.13742.4`. There must be differences between the product ranges your are using and the one on which the plugin has been based on.

What is to be done here is developing a new plugin. Please find below the procedure to ask for a new development (extracted from the issue template):

There is high demand for new plugins and new functionalities on existing plugins, so we have to rely on our community to help us prioritize them.
How? Post your suggestion on [The Watch Ideas](https://thewatch.centreon.com/ideas) with as much detail as possible and we will pick the most voted topics to add them to our product roadmap.

To develop a plugin/mode, we need the following information, depending on the protocol:
* **SNMP**: MIB files and full snmpwalk of enterprise branch (`snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk`) or [SNMP collections](https://thewatch.centreon.com/product-how-to-21/snmp-collection-tutorial-132).
* **HTTP API (SOAP, Rest/Json, XML-RPC)**: the documentation and some curl examples or HTTP [collections](https://thewatch.centreon.com/data-collection-6/centreon-plugins-discover-collection-modes-131).
* **CLI**: command line examples (command + result).
* **SQL**: queries + results + column types or [SQL collections](https://thewatch.centreon.com/product-how-to-21/sql-collection-tutorial-134).
* **JMX**: mbean names and attributes.

If some information is confidential, such as logins or IP addresses, obfuscate them in what is sent publicly and we'll get in touch with you by private message if this information is needed.

Please note that all the developments are open source, we will not commit to a release date. If it is an emergency for you, please contact [Centreon's sales team](https://www.centreon.com/contact/).
