### ISSUE TITLE
Unknown option: warning-in-traffic-limit at /usr/lib/centreon/plugins//centreon_cisco_standard_snmp.pl line 7613.

### ISSUE THREAD

**Issue by lebolivard** [centreon/centreon-plugins#4694]
Hi all

im new with centreo, i have been presenting a situation, i just installed **Centreon 22.10.14**, and i only installed the Cisco Standard Plugin. i was able to configure 2 hosts, bue when i try to monitor the traffic of an interface, it give me this notification and i don't know what to do to remedy it, does anuone have an idea?

Unknown option: warning-in-traffic-limit at /usr/lib/centreon/plugins//centreon_cisco_standard_snmp.pl line 7613.

**Comment by lebolivard** [comment]
![image](https://github.com/centreon/centreon-plugins/assets/147537233/ed128598-0a06-4232-9c98-97b4c005357b)
I have tried entering some value and it does not work, i only try to see 2 interfaces in one SW, if i configure only that it works trough icmp, as i said, i am just starting with centreon, i am just a beginner here, and i don't know much. I've tried to check de command

![image](https://github.com/centreon/centreon-plugins/assets/147537233/cb66289b-8014-4cbd-b9f6-bd7329f837d4)

**Comment by joschi99** [comment]
you need to use option --warning-in-traffic

**Comment by lebolivard** [comment]
> you need to use option --warning-in-traffic

i tried, but only gave me the same message Unknown option: warning-in-traffic-limit, i know by default it's unit '%'., i put 80 and it didn´t work, any other idea?

**Comment by joschi99** [comment]
could you send the complete command that you are executing?

**Comment by lebolivard** [comment]
[root@SRV-LUMA ~]# /usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=list-interfaces --hostname=172.16.2.1 --snmp-version='2c' --snmp-community='parquesti' --interface='' --name --warning-in-traffic=50 --warning-out-traffic=50 --critical-in-traffic=70 --critical-out-traffic=70 --speed=20000
Unknown option: warning-in-traffic at /usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl line 7613.

**Comment by joschi99** [comment]
mode=list-interfaces is used to discovery interfaces. If you want to monitor a interface you need to use mode=interfaces

` /usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=172.16.2.1 --snmp-version='2c' --snmp-community='parquesti' --interface='' --name --warning-in-traffic=50 --warning-out-traffic=50 --critical-in-traffic=70 --critical-out-traffic=70 --speed=20000`

**Comment by lebolivard** [comment]
Even today I still have the same problem, no matter how many times I change the parameter, I still get the same thing:
Unknown option: warning-in-traffic-limit

I admit it must be nonsense, but I don't see exactly where it is. Can someone guide me?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @lebolivard if you still need a response / solution to this issue, can you answer to @omercier message's above?

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time.Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the issue.
