### ISSUE TITLE
[hardware::server::lenovo::xcc::snmp::plugin] --mode=hardware: System health, memory and CPU table not recognized

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4695]
Latest plugins

Lenovo XCC SNMP OID has a System health table at OID .1.3.6.1.4.1.19046.11.1.1.4: 
https://[mibs.observium.org/mib/LENOVO-XCC-MIB/](https://mibs.observium.org/mib/LENOVO-XCC-MIB/)

This table will not recognized or checked by the plugin. As you can see the system show's an error on XCC
![image](https://github.com/centreon/centreon-plugins/assets/6400595/13794c4a-fa0c-4fb4-a391-ea1031bb3c12)

and we found the error on the System health table:
```
.1.3.6.1.4.1.19046.11.1.1.4.1.0 = INTEGER: 2
.1.3.6.1.4.1.19046.11.1.1.4.2.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.19046.11.1.1.4.2.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.19046.11.1.1.4.2.1.1.3 = INTEGER: 3
.1.3.6.1.4.1.19046.11.1.1.4.2.1.1.4 = INTEGER: 4
.1.3.6.1.4.1.19046.11.1.1.4.2.1.2.1 = STRING: "Error"
.1.3.6.1.4.1.19046.11.1.1.4.2.1.2.2 = STRING: "Error"
.1.3.6.1.4.1.19046.11.1.1.4.2.1.2.3 = STRING: "Error"
.1.3.6.1.4.1.19046.11.1.1.4.2.1.2.4 = STRING: "Warning"
.1.3.6.1.4.1.19046.11.1.1.4.2.1.3.1 = STRING: "An Uncorrectable PCIe Error has Occurred at Bus 01 Device 00 Function 01. The Vendor ID for the device is 14E4 and the Device ID is 16D8. The physical slot number is 1."
.1.3.6.1.4.1.19046.11.1.1.4.2.1.3.2 = STRING: "Fault in slot 1 on system ThinkSystem SR655 V3."
.1.3.6.1.4.1.19046.11.1.1.4.2.1.3.3 = STRING: "Fault in slot 6 on system ThinkSystem SR655 V3."
.1.3.6.1.4.1.19046.11.1.1.4.2.1.3.4 = STRING: "PCIe Link Training Failure has occurred in physical slot number 3."
```

but the plugin show's OK:
![image](https://github.com/centreon/centreon-plugins/assets/6400595/c1277c01-c9e3-42b7-b7d3-f9851b6dead7)

As you can see on this Plugin output also the CPU/memory table will not read/recognized, there is no "component" for memory on the plugin and for them:

- memory status will not verified (OID .1.3.6.1.4.1.19046.11.1.1.5.21)
- cpu status will not verified (OID .1.3.6.1.4.1.19046.11.1.1.5.20)

Seem's that the XCC plugin is actually incomplete.

Please let me know if you need further informations

(2084)

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.

**Comment by joschi99** [comment]
To be onest if you want to move away from github issues to Centreon Watch you need to migrate all tickets and not only close it. A lot of information will be lost in this way. Centreon Watch seem's not integrated with Github.

By the way if a Plugin is incomplete like this one: yes, it is an enhacement, but you loose all links to github commits, pull requests ecc.

And the last 2 months the number of commits, enhancements and new plugins decreased a lot, so what is the intention of Centreon for this project?
