### ISSUE TITLE
New mode for network::f5::bigip::snmp and overall cpu usage stats

### ISSUE THREAD

**Issue by moix** [centreon/centreon-plugins#4699]
bigip f5 distributes its cpus in two groups:

- odd-numbered index cpus (1,3,5,7...) are dedicated to data plane usage
- even-numbered index cpus (2,4,6,8,...) are dedicated to control plane usage

reference https://my.f5.com/manage/s/article/K92615205

The current TMM-usage mode (https://github.com/centreon/centreon-plugins/blob/develop/src/network/f5/bigip/snmp/mode/tmmusage.pm) uses my $oid_sysTmmStatEntry = '.1.3.6.1.4.1.3375.2.1.8.2.3.1'; as entry tree to retrieve TMM usage cpu stats,so only  half of the cpus, even-numbered index, are listed there. These are the most important ones because are those that handle the data traffic of the proxy. However management/control plane cpus are also important because they take care of multiple administrative operations that also require high computing resource in f5.

Unfortunately, there's no equivalent oid for non-TMM that only list the control plane dedicated cpus.

While inspecting bigip MIB (http://www.oidview.com/mibs/3375/F5-BIGIP-SYSTEM-MIB.html), the only option possible seems to use the generic sysMultiHostCpuEntry	1.3.6.1.4.1.3375.2.1.7.5.2.1

and under it, it will be insteresting to extract the following cpu metrics:

and then we would like to extract > report as perf name:

> sysMultiHostCpuUsageRatio5s	1.3.6.1.4.1.3375.2.1.7.5.2.1.19 > load5s
> sysMultiHostCpuUser5s	1.3.6.1.4.1.3375.2.1.7.5.2.1.12 > user5s
> sysMultiHostCpuIowait5s	1.3.6.1.4.1.3375.2.1.7.5.2.1.18 > iowait5s
> sysMultiHostCpuSystem5s	1.3.6.1.4.1.3375.2.1.7.5.2.1.14 > system5s
> sysMultiHostCpuIdle5s	1.3.6.1.4.1.3375.2.1.7.5.2.1.15 > idle5s
> 
> sysMultiHostCpuUsageRatio1m	1.3.6.1.4.1.3375.2.1.7.5.2.1.27 > load1m
> sysMultiHostCpuUser1m	1.3.6.1.4.1.3375.2.1.7.5.2.1.20 > user1m
> sysMultiHostCpuIowait1m	1.3.6.1.4.1.3375.2.1.7.5.2.1.26 > iowait1m
> sysMultiHostCpuSystem1m	1.3.6.1.4.1.3375.2.1.7.5.2.1.22 > system1m
> sysMultiHostCpuIdle1m	1.3.6.1.4.1.3375.2.1.7.5.2.1.23 > idle1m
> 
> sysMultiHostCpuUsageRatio5m	1.3.6.1.4.1.3375.2.1.7.5.2.1.35 > load5m
> sysMultiHostCpuUser5m	1.3.6.1.4.1.3375.2.1.7.5.2.1.28 > user5m
> sysMultiHostCpuIowait5m	1.3.6.1.4.1.3375.2.1.7.5.2.1.34 > iowait5m
> sysMultiHostCpuSystem5m	1.3.6.1.4.1.3375.2.1.7.5.2.1.30 > system5m
> sysMultiHostCpuIdle5m	1.3.6.1.4.1.3375.2.1.7.5.2.1.31 > idle5m

I've tried to implement taking as base tmmusage.pm but my perl skills are not very good, to say something. Will try to raise a pr for it but any help and contribution will be more than appreciated. thanks!

**Comment by omercier** [comment]
Hi @moix,

Thanks for the contribution :100: (with my apologies for the delay).

Your contribution will be discussed during the next weekly sessions of refinement with the team.
Can you provide the result of either `snmpwalk -ObentU` or the output of the plugin in debug mode for us to set up automated tests ?

Thanks :+1:

Regards,

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Let me close this issue because it's more about an enhancement. I've take your PR in account and create internal ticket associate to handle it in the near future.
Thanks for your patience and contribution 🙏
