### ISSUE TITLE
New plugin " Apache SOLR"

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#470]
Hello team,

This guys have created a plugin to see metrics of Apache SOLR but with his libs. Could you please do the same with Centreon Plugin :-)
https://github.com/HariSekhon/nagios-plugins/blob/master/check_solr_metrics.pl

Thanks in advance.

**Comment by garnier-quentin** [comment]
I need API examples.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
