### ISSUE TITLE
MongoDB v6.0: Unsupported OP_QUERY command ping

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4700]
MongoDB 6.x could not be monitored:
MongoDB::DatabaseError: Unsupported OP_QUERY command: ping. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal

Same issue like #3882, but no idea what could be the solution, because the link on this ticket is not more valid.

**Comment by joschi99** [comment]
Please note that the official perl driver is EOL: https://www.mongodb.com/blog/post/the-mongodb-perl-driver-is-being-deprecated
See also #4681

**Comment by joschi99** [comment]
Have found a possibile solution:

- removed perl-MongoDB.noarch                            v2.0.3-1.el7.centos
- installed latest perl-MongoDB via CPAN (version 2.2.2)

**Comment by omercier** [comment]
Hi @joschi99,
CentOS 7 will be EOL soon as well, and the same version as CPAN is packaged for EL8/9:

```
[root@central-pp-22-10 ~]# dnf info  perl-MongoDB
Installed Packages
Name         : perl-MongoDB
Version      : v2.2.2
Release      : 1.el8
Architecture : noarch
Size         : 1.1 M
Source       : perl-MongoDB-v2.2.2-1.el8.src.rpm
Repository   : @System
From repo    : centreon-stable-noarch
Summary      : Official MongoDB Driver for Perl
URL          : hhttps://metacpan.org/release/MongoDB
License      : GPL or Artistic
Description  : This is the official Perl driver for MongoDB. MongoDB is an open-source document database that provides
             : high performance, high availability, and easy scalability.
```

So I suggest to migrate to more recent breeds of EL and patch the CentOS7 servers with CPAN in the meantime.
