### ISSUE TITLE
add mode to rabbitMQ - add new mode / metrcis to monitor

### ISSUE THREAD

**Issue by chi-miel** [centreon/centreon-plugins#4704]
Hello,

I would like monitor some indicator from rabbitMQ node (in %) :
-  file descriptor used
-  numbers sockets used
-  memory used
-  disk used

And also :
- memory alarm
- disk alarm

Link documentation : https://www.rabbitmq.com/monitoring.html#node-metrics
Is it possible to add this mode to  apps::mq::rabbitmq::restapi::plugin please ?

Additionals informations :

URL : `curl -k --user "LOGIN:PASSWORD" [https://IP:PORT/api/nodes](https://ip/api/nodes)`

JSON output :
```
[
    {
        "partitions": [],
        "os_pid": "0000",
        "fd_used": 22,
        "fd_total": 1024,
        "sockets_used": 1,
        "sockets_total": 829,
        "mem_used": 60542848,
        "mem_limit": 3355069644,
        "mem_alarm": false,
        "disk_free_limit": 100000000,
        "disk_free": 1692803072,
        "disk_free_alarm": false,
        "proc_used": 180,
        "proc_total": 1048576,
        "statistics_level": "fine",
        "uptime": 11892048751,
        "run_queue": 0,
        "processors": 4,
         ….
    },

    {
        ohter node
    }
]
```

**Comment by chi-miel** [comment]
I also create a post on the watch : https://thewatch.centreon.com/ideas/centreon-plugins-add-mode-to-rabbitmq-2414

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
This issue can be closed (The Watch duplicate)
