### ISSUE TITLE
storage::netapp::snmp::plugin Incorrect Temperature Warnings

### ISSUE THREAD

**Issue by lzmarouane** [centreon/centreon-plugins#4707]
Hi,
I am using the Centreon plugin to monitor the temperature of my NetApp storage system, but I am receiving incorrect temperature warnings for one of the nodes. The plugin reports that the hardware temperature on node 'CLUSTER-01_2' is "over temperature range," while my observations suggest that everything is functioning normally.

The Centreon plugin is reporting a "CRITICAL" status with the message that the hardware temperature on 'CLUSTER-01_2' is over the temperature range. This is not the actual status, and all other nodes are reported correctly.

`/usr/lib/centreon/plugins//centreon_netapp_ontap_snmp.pl --plugin=storage::netapp::ontap::snmp::plugin --mode=temperature --hostname='192.168.0.2' --snmp-version='1' --snmp-community='public' --verbose`

```
CRITICAL: Hardware temperature is over temperature range on node CLUSTER-01_2'
hardware temperature on node 'CLUSTER-01_1' is over range: 'no'
hardware temperature on node 'CLUSTER-01_2' is over range: 'yes'
```

Thank you

**Comment by omercier** [comment]
Hi, can you run the command with the --debug option, please ?

**Comment by lzmarouane** [comment]
Hi @omercier , here is what is got :
```
CRITICAL: Hardware temperature is over temperature range on node 'CLUSTER-01_2'
.1.3.6.1.4.1.789.1.25.2.1.1.73.76.69.77.45.67.76.85.83.84.69.82.45.48.49.95.49 = CLUSTER-01_1
.1.3.6.1.4.1.789.1.25.2.1.1.73.76.69.77.45.67.76.85.83.84.69.82.45.48.49.95.50 = CLUSTER-01_2
.1.3.6.1.4.1.789.1.25.2.1.18.73.76.69.77.45.67.76.85.83.84.69.82.45.48.49.95.49 = 1
.1.3.6.1.4.1.789.1.25.2.1.18.73.76.69.77.45.67.76.85.83.84.69.82.45.48.49.95.50 = 2
hardware temperature on node 'CLUSTER-01_1' is over range: 'no'
hardware temperature on node 'CLUSTER-01_2' is over range: 'yes'
```

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I've take a look and test at your issue. Temperature warning for this kind of equipment isn't handle by the plugin. In fact it's handle by the SNMP OID requested: `1.3.6.1.4.1.789.1.25.2.1.18`
```
nodeEnvOverTemperature 	        OBJECT-TYPE
	SYNTAX      			INTEGER {
	                                     no(1),
					     yes(2)
					}
	MAX-ACCESS  			read-only
	STATUS      			current
	DESCRIPTION
		"An indication of whether the hardware is
		currently operating outside of its recommended
		temperature range.  The hardware will shutdown
		if the temperature exceeds critical thresholds."
	::= { nodeEntry 18 }
```
[ressource](https://oidref.com/1.3.6.1.4.1.789.1.25.2.1.18)

Our plugin (see [line 92](https://github.com/centreon/centreon-plugins/blob/develop/src/storage/netapp/ontap/snmp/mode/temperature.pm#L92) of the temperature mode) only handle if this OID return 1 (no) = all is fine or 2 (yes) = "currently operating outside of its recommended temperature range".
