### ISSUE TITLE
[os::windows::local::plugin] --mode=updates: add list of available updates on verbose mode

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4709]
It should be nice to have the detailed list of pending updates on verbose mode like:
```
OK: Number of pending updates : 3
microsoft updates 2022
Microsoft defender version 3030
sql version 2333
```

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
