### ISSUE TITLE
New Plugin "Squid"

### ISSUE THREAD

**Issue by sboulianne** [centreon/centreon-plugins#472]
Hello team,

Is it possible to get a plugin to monitor Squid reverse proxy?

hit/ratio
connections
errors, etc 
Somethings like https://exchange.icinga.org/exchange/check_squid

Thanks you!

**Comment by sboulianne** [comment]
Thanks you Quentin!

**Comment by garnier-quentin** [comment]
I need MIBs and snmpwalk.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md

**Comment by sboulianne** [comment]
Look http://wiki.squid-cache.org/Features/Snmp
