### ISSUE TITLE
New mode for storage::dell::me4::restapi::plugin

### ISSUE THREAD

**Issue by habo105** [centreon/centreon-plugins#4721]
Is it possible to extend this plugin with mode alerts? This mode is already available on other Dell storage checks like plugin=storage::dell::powerstore::restapi::plugin.

The API of the Powervault reports eventlogdata (https://www.dell.com/support/manuals/en-us/powervault-me4084/me4_series_cli_pub/event-log?guid=guid-22f19bf7-801b-466b-b5ed-c2183fd54019&lang=en-us).

I can provide the information that's needed and test the new version.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
