### ISSUE TITLE
network:aruba::standard::snmp::plugin no stacking information available

### ISSUE THREAD

**Issue by guillaumechardin** [centreon/centreon-plugins#4728]
By using  network::aruba::standard::snmp::plugin to monitor Aruba 3810M switches i can see there is no stacking option to check on stack status.

I tried to use arubacx plugin and HPprocurve plugin but those do not check the rights OIDs
```
 ./centreon_aruba_aoscx_snmp.pl --host <ip_3810M>  --snmp-community='public' --snmp-version='2' --mode vsf
UNKNOWN: SNMP Table Request: Cant get a single value.
```

After speaking with aruba support agent, it point me that full MIB documentation about OIDs for legacy switchs using stacking module (not using VSF software feature) can be found here (for aruba os 16.10+) :
https://asp.arubanetworks.com/downloads/software/RmlsZTozMWI4YjA5YS1iMTdiLTExZWMtYTY4My05M2RhNTIwYTMxOGE%3D
section [HP-STACK-MIB]
ie : hpStackOperStatus => 1.3.6.1.4.1.11.2.14.11.5.1.69.1.1.2

Can this feature be added to aruba plugin ?

Thanks
Guillaume.

**Comment by omercier** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.

PS: if you have an account, please directly provide the MIB files and the result of this command at the links above:

```bash
snmpwalk -ObenTU -v 2c -c ******* ip_address .1.3.6.1.4.1
```
