### ISSUE TITLE
UNKNOWN: Cannot decode response  speedtest

### ISSUE THREAD

**Issue by sistemmsn** [centreon/centreon-plugins#4729]
seems to be a syntax error

<img width="610" alt="image" src="https://github.com/centreon/centreon-plugins/assets/38023703/915d4639-8852-4d22-a9fc-889cc63998a1">

I edited line 107 and left it as it is in the image and it threw the following error
<img width="297" alt="image" src="https://github.com/centreon/centreon-plugins/assets/38023703/abccb2db-4dc2-48e8-82fb-201e9205694c">

error
`./centreon_monitoring_speedtest.pl --mode=internet-bandwidth  --debug 
UNKNOWN: Can't use string ("8.818") as a HASH ref while "strict refs" in use at ./centreon_monitoring_speedtest.pl line 122. `

**Comment by sistemmsn** [comment]
It seems that the version that speedtest was installed was not the correct one, it was corrected by installing from the official speedtest page

https://www.speedtest.net/apps/cli

**Comment by liferadioat** [comment]
It seems that there is now a new problem:
```
 sudo -u nagios perl centreon_plugins.pl --plugin=apps::monitoring::speedtest::plugin --mode=internet-bandwidth
UNKNOWN: Command error: ============================================================================== -  - You may only use this Speedtest software and information generated - from it for personal, non-commercial use, through a command line - interface on a personal computer. Your use of this software is subject - to the End User License Agreement, Terms of Use and Privacy Policy at - these URLs: -  -     https://www.speedtest.net/about/eula -  https://www.speedtest.net/about/terms -         https://www.speedtest.net/about/privacy -  - ============================================================================== -  - To accept the message please run speedtest interactively or use the following:  -  -     speedtest --accept-license
```
Running it once with speedtest doesn´t solve the problem

**Comment by liferadioat** [comment]
Thanks, I´ve done the following:
`sudo -u nagios speedtest` => works and accepted
`sudo -u nagios perl centreon_plugins.pl --plugin=apps::monitoring::speedtest::plugin --mode=internet-bandwidth
OK: ping latency: 8.002 ms, jitter: 0.172 ms - download: 87.27 Mb/s, upload: 41.77 Mb/s | 'ping.latency.milliseconds'=8.002ms;;;0; 'ping.jitter.milliseconds'=0.172ms;;;0; 'internet.bandwidth.download.bitspersecond'=87272408b/s;;;0; 'internet.bandwidth.upload.bitspersecond'=41774800b/s;;;0;` 
=> works and results are shown.
But at icingaweb2 I get always the same error: `UNKNOWN: Cannot decode response`
