### ISSUE TITLE
New Plugin: Avaya VOIP

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#473]
Hello team,

Can you add a new plugin to monitor Avaya VOIP system?
Basically, if we can monitor:
- load of PBX
- Errors on server and Communication Manager
- Trunks usage
- Call usage

We can find this on web: http://nagios.fm4dd.com/plugins/

Thanks in advance.

**Comment by garnier-quentin** [comment]
I need MIBs and snmpwalk.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
