### ISSUE TITLE
change perfdata traffic  bs  to mbps

### ISSUE THREAD

**Issue by sistemmsn** [centreon/centreon-plugins#4733]
According to the documentation, it shows you several examples for the conversion from b/s to mb/s but it gives an error if you should do anything else about it.

<img width="710" alt="image" src="https://github.com/centreon/centreon-plugins/assets/38023703/a309acec-a047-4fdf-a7e4-4d04aafe6eee">

https://docs.centreon.com/pp/integrations/plugin-packs/procedures/applications-monitoring-speedtest/

**Comment by omercier** [comment]
Hi,
The bug is actually in the help message:
Bash interpretes the parenthesis, hence the error message.
Try with this syntax, it should work fine: `--change-perfdata='traffic_in,,scale(Mbps),Mbps'`.
We'll fix the help message, thanks!
