### ISSUE TITLE
[cloud::docker::local::plugin] --mode=list-containers: Can't exec "docker"

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4738]
./centreon_plugins.pl --plugin=cloud::docker::local::plugin --mode=list-containers
UNKNOWN: Command error: Can't exec "docker": No such file or directory at 20231017/src/centreon/plugins/misc.pm line 303.

**Comment by omercier** [comment]
Hi @joschi99 is the docker command installed on your poller?

**Comment by joschi99** [comment]
Yep, you are right, sorry.
