### ISSUE TITLE
vCenter mode=status-host

### ISSUE THREAD

**Issue by slayderz66** [centreon/centreon-plugins#4745]
Bonjour,

![image](https://github.com/centreon/centreon-plugins/assets/150426187/b708d250-17f2-4701-b3de-0403466c6127)

Je voudrais que dès qu'il détecte un status "Unknown" cela passe en Critical
Ou si c'est pas possible, que le status notResponding soit en Critical.
J'ai ajouté l'option --critical-status='%{status} =~ /notResponding/i' mais le problème, si je comprends bien, c'est que si il y a un autre status en Critical que "notResponding" il me mette un OK :/

Merci

**Comment by omercier** [comment]
Hi,
Thanks for your interest in Centreon.
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md)).

Thank you for your understanding.
