### ISSUE TITLE
Temperature reporting issues with Nexus series 9000

### ISSUE THREAD

**Issue by joachim-diaz** [centreon/centreon-plugins#475]
Hello.

I may be wrong, but it seems that temperature monitoring is not working with Nexus series 9000 , returning 'OK : All 0 components are ok []'  with the --component=temperature option added.  

snmpwalk seems however to return proper values for temperature probes: 

poller$ snmpwalk -c xxx -v 2c a.b.c.d .1.3.6.1.4.1.9.9.91.1.1.1.1.4
iso.3.6.1.4.1.9.9.91.1.1.1.1.4.21590 = INTEGER: 41
iso.3.6.1.4.1.9.9.91.1.1.1.1.4.21591 = INTEGER: 28
iso.3.6.1.4.1.9.9.91.1.1.1.1.4.21592 = INTEGER: 41
iso.3.6.1.4.1.9.9.91.1.1.1.1.4.21593 = INTEGER: 51
iso.3.6.1.4.1.9.9.91.1.1.1.1.4.21594 = INTEGER: 44

poller$ snmpwalk -c xxx -v 2c a.b.c.d 1.3.6.1.2.1.47.1.1.1.1.2
(...)
iso.3.6.1.2.1.47.1.1.1.1.2.21590 = STRING: "module-1 FRONT"
iso.3.6.1.2.1.47.1.1.1.1.2.21591 = STRING: "module-1 BACK"
iso.3.6.1.2.1.47.1.1.1.1.2.21592 = STRING: "module-1 CPU"
iso.3.6.1.2.1.47.1.1.1.1.2.21593 = STRING: "module-1 TD2-1"
iso.3.6.1.2.1.47.1.1.1.1.2.21594 = STRING: "module-1 NS-1"

Could you check this ?  Thank you.

**Comment by garnier-quentin** [comment]
Hi joachim,

The temperature is in sensor: --component=sensor

**Comment by joachim-diaz** [comment]
It works indeed via sensor. Thank you !

**Comment by garnier-quentin** [comment]
You're welcome!
