### ISSUE TITLE
Migrate poller cent OS7 to Alma 9_2

### ISSUE THREAD

**Issue by Didier97180** [centreon/centreon-plugins#4759]
Hello

I'm sorry but I closed my first topic on purpose. I migrated Centreon 21.10 which was on CentOS 7 to Alma9.

For the Central everything went well but for the collector I would like to have the step-by-step procedure for the migration which is also on Centos7 and Centreon 21.10. On the Centreon procedure he does not detail enough: https://docs.centreon.com/fr/docs/migrate/migrate-from-el-to-el/ I also want to keep the same IP address the same name and keep the same configuration if possible.

To do this, do you have to remove the old collector and put the other one back? Because by putting the new one it tells me that it already exists, even if I delete it in the centreon console.

**Comment by Didier97180** [comment]
Hello In the same situation I cannot migrate the remote server.  I am trying to migrate centreon 21.10 on CentOs7 to centreon 23.10 on Almalinux 9. I followed this procedure : https://docs.centreon.com/fr/docs/migrate/migrate-from-el-to-el/ 
but it does not give enough detail for the Remote server.  At the end of the migration my remote server keeps the old version of centreon engine (21.10) and the attachment no problem but the remote on the Central side is not started.

**Comment by Didier97180** [comment]
Good morning,

Can you please answer me, I'm stuck and it's bothering me a little.

Thank you

**Comment by omercier** [comment]
Hi @Didier97180,
Sorry but this is not the right place to seek for help on Centreon platform migrations. Please explain your issue [here](https://thewatch.centreon.com/platform-7) or on our community slack.
Good luck!
