### ISSUE TITLE
[hardware::ups::socomec::netvision::snmp::plugin] --mode=battery - wrong temperature calculation

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4763]
The temperatur is calculated wrong on Netvision 7 - latest plugin

```
CRITICAL: minutes remaining: 0 - temperature: 2.2 C | 'battery.charge.remaining.percent'=100%;40:;20:;0;100 'battery.charge.remaining.minutes'=0;30:;15:;0; 'battery.voltage.volt'=339.1V;;;; 'battery.temperature.celsius'=2.2C;15:30;10:40;;
.1.3.6.1.4.1.4555.1.1.7.1.2.1.0 = 2
.1.3.6.1.4.1.4555.1.1.7.1.2.3.0 = 0
.1.3.6.1.4.1.4555.1.1.7.1.2.4.0 = 100
.1.3.6.1.4.1.4555.1.1.7.1.2.5.0 = 3391
.1.3.6.1.4.1.4555.1.1.7.1.2.6.0 = 220
.1.3.6.1.4.1.4555.1.1.7.1.2.8.0 = 0
.1.3.6.1.4.1.4555.1.1.1.1.2.1.0 = 2
.1.3.6.1.4.1.4555.1.1.1.1.2.3.0 = 0
.1.3.6.1.4.1.4555.1.1.1.1.2.4.0 = 100
.1.3.6.1.4.1.4555.1.1.1.1.2.5.0 = 3391
.1.3.6.1.4.1.4555.1.1.1.1.2.6.0 = 22
```

As you can see the temperature is shown as 2.2 degrees, the snmp value is 220. The right calculation also indicated by snmp mib is with factor 0.1, the plugin is using factor 0.01

**Comment by omercier** [comment]
Hi @joschi99,
Thank you for your involvement in the centreon-plugins project.
Your bug has been reproduced and is now in our backlog.
REFS: CTOR-231

**Comment by omercier** [comment]
Hi @joschi99,
It has been fixed in the develop branch. The next release is planned on 11th march.
