### ISSUE TITLE
network::fortinet::fortigate::snmp::plugin ap-usage enhancement

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#4767]
Hi,

Could you please add channel utilisation, interference, tx power and noise monitoring for Fortigate access-points via RestAPI or snmp? It can be added as a separate mode or ap-usage extra option. 
I can help with testing the plugin.

**Comment by omercier** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).

Thank you for your understanding.
