### ISSUE TITLE
Cisco WLC disabled APs

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#477]
Hi,

Could you please add new mode to cisco WLC plugin. I would like to see the number of administratively disabled access points and also have to possibility to configure alarms thresholds to it.
Thanks in advance!

**Comment by kadrika** [comment]
The OID that shows AP administrative status is:  	1.3.6.1.4.1.14179.2.2.1.1.37. 
1-enable, 2-disable

**Comment by garnier-quentin** [comment]
You see with verbose option disabled AP.

**Comment by garnier-quentin** [comment]
Could you test 'ap-status' ? You have counters for that now.
