### ISSUE TITLE
[network::brocade::plugin] Mode Interfaces Option --oid-extra-display

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#478]
Hi,
Brocade's port are named and I want to display this name on output of plugin.

I'll try with option "--oid-extra-display" but it seems doesn't work.

I use this command:
/usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=network::brocade::plugin  --mode=interfaces --hostname=X.X.X.X --snmp-community='public' --snmp-version='2c' --snmp-timeout=5  --oid-display=ifDesc --interface='^FC port 0/15$' --name --oid-extra-display='1.3.6.1.4.1.1588.2.1.1.1.6.2.1.36.16'
UNKNOWN: Unsupported oid in --oid-extra-display option.

with snmpwalk this OID return the Port Name:
SNMPv2-SMI::enterprises.1588.2.1.1.1.6.2.1.36.16 = STRING: "B2-TT-ESX203"
16 is the number of the port "+1"

Can you tell me the good syntax?

Thanks,

**Comment by garnier-quentin** [comment]
I think you miss a dot before ;)
```
/usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=network::brocade::plugin --mode=interfaces --hostname=X.X.X.X --snmp-community='public' --snmp-version='2c' --snmp-timeout=5 --oid-display=ifDesc --interface='^FC port 0/15$' --name --oid-extra-display='.1.3.6.1.4.1.1588.2.1.1.1.6.2.1.36.16'
```

**Comment by cmeschin** [comment]
Exact, but same result with a dot :(

**Comment by garnier-quentin** [comment]
Ok. You can only use ifalias, ifdesc or ifname value for that option. Can set another OID.

**Comment by cmeschin** [comment]
... In help it is written:
--oid-extra-display
            Add an OID to display.

**Comment by garnier-quentin** [comment]
Should change the message yes

**Comment by cmeschin** [comment]
effectively, it works if I send : --oid-extra-display='ifDesc'
OK: Interface 'FC port 0/15' [ FC port 0/15 ] Status : up (admin: up)

what is the value of the option since these values are already displayed?

**Comment by garnier-quentin** [comment]
You can display the ifalias or ifname also.

**Comment by cmeschin** [comment]
yes, but not really interesting in this case. 
Adding another OID as the "Port Name" would be a real added value of this plugin. This evolution is it possible?

**Comment by cmeschin** [comment]
Another solution would be to use mode "list-interface" and option 
--add-extra-oid
            Display an OID. Example:
            --add-extra-oid='alias,.1.3.6.1.2.1.31.1.1.1.18'

This option seems to work better but perhaps limited with just a few oids.
What do you think about it?

**Comment by garnier-quentin** [comment]
The solution would be to do add the functionnality ;)

**Comment by cmeschin** [comment]
Thanks.
On the next release of centreon-plugins? ;)

**Comment by garnier-quentin** [comment]
Hi,

There is a link between the ifIndex and the swFCPortTable ? You need to add +1 ?

**Comment by cmeschin** [comment]
Hi Quentin,
I'm sorry, the OID .1.3.6.1.4.1.1588.2.1.1.1.6.2.1.36.16 is for EMC Connectrix DS-6520B and not for Brocade Access Gateway. The infra team gave me false informations :(
So actually I'm verifying if swFCPortTable is really ifDesc+1 on EMC Connectrix DS-6520B equipments

I try to get the OID for description port on Brocade Access Gateway.

I come back to you as soon as possible.

**Comment by garnier-quentin** [comment]
Thanks. i'll need a full snmpwalk.

**Comment by cmeschin** [comment]
It's confirmed on EMC Connectrix:
.1.3.6.1.2.1.31.1.1.1.1.1073741824 = STRING: 0/**0**
.1.3.6.1.2.1.31.1.1.1.1.1073741825 = STRING: 0/**1**

correspond to those description ports:
.1.3.6.1.4.1.1588.2.1.1.1.6.2.1.36.**1** = STRING: "B1P1_C1F1"
.1.3.6.1.4.1.1588.2.1.1.1.6.2.1.36.**2** = STRING: "B1P2_C1F1"

I send you the full snmpwalk on MP

But on Brocade Access Getaway, the Port Name seems to be only on SNMP traps (cf page 538 of https://community.brocade.com/dtscp75322/attachments/dtscp75322/fibre/8685/1/53_1000602_02_MIB_v610.pdf).

**Comment by garnier-quentin** [comment]
It doesn't match with the ifindex. That shitty to do some regexp on name.

**Comment by cmeschin** [comment]
Hi @garnier-quentin,
Have you any news about this?
Did I send you the full snmpwalk, I have a doubt...?

Thanks.

**Comment by garnier-quentin** [comment]
I think not.

**Comment by cmeschin** [comment]
Done... sorry for forgetting...
Thanks.

**Comment by garnier-quentin** [comment]
You can test with last version. You can use now: ```--oid-extra-display=fcportname```. 
Even more, you have crc error with --add-errors and new option --add-optical (temperature and dbm).

**Comment by cmeschin** [comment]
It works!
Thank you.
