### ISSUE TITLE
[network::sonus::sbc::snmp::plugin] --mode=cpu: Unknown option

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#4792]
latest plugins

none of this option will work:
```
    --warning-average
            Warning threshold average CPU utilization.

    --critical-average
            Critical threshold average CPU utilization.

    --warning-core
            Warning thresholds for each CPU core

    --critical-core
            Critical thresholds for each CPU core
```

Looking on the sourcecode seem's that the plugin is referencing to cpudetailed:
```
package network::sonus::sbc::snmp::mode::cpu;

use base qw(snmp_standard::mode::cpudetailed);

use strict;
use warnings;
```

**Comment by omercier** [comment]
Hi @joschi99, 
Indeed, according to the code, it should work like `snmp_standard::mode::cpudetailed` but the PODs have now been updated accordingly.

Can you confirm that it works fine with this?

```
    --warning-*
            Warning threshold in percent. Can be: 'user', 'nice', 'system',
            'idle', 'wait', 'kernel', 'interrupt', 'softirq', 'steal',
            'guest', 'guestnice'.

    --critical-*
            Critical threshold in percent. Can be: 'user', 'nice', 'system',
            'idle', 'wait', 'kernel', 'interrupt', 'softirq', 'steal',
            'guest', 'guestnice'.
```

**Comment by joschi99** [comment]
I can confirm that mode=cpu-detailed is working as aspected and there is no problem. But this plugin has also mode=cpu which is wrong.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I tested this issue and it appears to me that the option showed in the cpu mode with --help (even the option `--use-ucd` ) are not handle anymore by this mode. But if you try to use the options suggested above by @omercier it should works. 

```
~/centreon-plugins/src$ perl centreon_plugins.pl --plugin=network::sonus::sbc::snmp::plugin --mode=cpu --hostname --warning-average=1
Unknown option: warning-average at /home/ldubrunfaut/centreon-plugins/src/centreon/plugins/alternative/Getopt.pm line 81. 

~/centreon-plugins/src$ perl centreon_plugins.pl --plugin=network::sonus::sbc::snmp::plugin --mode=cpu --hostname --warning-user=1
UNKNOWN: SNMP Table Request: Timeout 
```

If you confirm this solution, we should change the help section for cpu mode, and also think about how this issue show that cpu and cpudetailed modes are doing the same job here.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue was resolved with the August release and the following PR: https://github.com/centreon/centreon-plugins/pull/5110
