### ISSUE TITLE
SNMP Generic App Protocol doesn´t find any value - custom mib

### ISSUE THREAD

**Issue by liferadioat** [centreon/centreon-plugins#4798]
Hi,

I am using the centreon plugins (github latest) to check a device with a custom MIB at ubuntu server with

`sudo -u nagios perl centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=string-value --hostname=10.158.129.xx --oid='.1.3.6.1.4.1.2604.5.1.1.1' --snmp-community=icinga`
The result: `UNKNOWN: SNMP GET Request: Cant get a single value.`

When I use the same OID on the same machine with snmpwalk I get a valid result:
`sudo -u nagios snmpwalk -v2c -c icinga 10.158.129.xx .1.3.6.1.4.1.2604.5.1.1.1`
Result: `iso.3.6.1.4.1.2604.5.1.1.1.0 = STRING: "LRFW01.xy.at"`

What could be the issue here? Is there any option I am missing at centreon? The mib seems recognized by snmpwalk, but not for centreon. The mib is saved at /usr/share/snmp/mibs & /home/nagios/.snmp

Best,

**Comment by Sims24** [comment]
Try adding .0 at the end of your --oid= option

**Comment by liferadioat** [comment]
Thanks, I tried, but it is not working partially:
```
sudo -u nagios snmpwalk -v2c -c icinga 10.158.129.254 .1.3.6.1.4.1.2604.5.1.2.4
iso.3.6.1.4.1.2604.5.1.2.4.1.0 = Gauge32: 89055
iso.3.6.1.4.1.2604.5.1.2.4.2.0 = Gauge32: 18
```

```
sudo -u nagios perl centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=10.158.129.254 --oid='.1.3.6.1.4.1.2604.5.1.2.4' --snmp-community=icinga
UNKNOWN: SNMP GET Request: Cant get a single value.
```

```
sudo -u nagios perl centreon_plugins.pl --plugin=apps::protocols::snmp::plugin --mode=numeric-value --hostname=10.158.129.254 --oid='.1.3.6.1.4.1.2604.5.1.2.4.0' --snmp-community=icinga
UNKNOWN: SNMP GET Request: Cant get a single value.
```

**Comment by Sims24** [comment]
A leading .1 digit is missing at the beginning of the --oid option value

**Comment by liferadioat** [comment]
Thanks, is counter64 supported?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @liferadioat if you still need a response / solution to this issue, can you take a look at the recap provide by @omercier above and help us understanding your issue?

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time.Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the issue.
