### ISSUE TITLE
Add a check for MySQL blocked queries

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon-plugins#48]
Dear developpers,

I encountered some troubles with MySQL. There was a blocked query in my DB and it produced lots of issues around Centreon.

To solve the problem, I killed the query concerned. 

After this problem, I think it will be very useful to check MySQL blocked queries with Centreon in order to fix easily the case.

Best regards.

**Comment by garnier-quentin** [comment]
CRITICAL if there is at least one request over 60 seconds:
perl centreon_plugins.pl --plugin=database::mysql::plugin --host=127.0.0.1 --mode=long-queries --seconds=60 --critical=1 --verbose
