### ISSUE TITLE
while using jmx tomcat UNKNOWN: Cannot load module --plugin.

### ISSUE THREAD

**Issue by jopkerrien** [centreon/centreon-plugins#480]
An help will be highly appreciated. I am trying to monitor a tomcat 

[root@TOTO plugins]#  perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin  --host=XXX.XXX.XXX.XXX --snmp-version=2 --snmp-community=public
UNKNOWN: Cannot load module --custommode.
Can't locate JMX/Jmx4Perl.pm in @INC (@INC contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/centreon/common/protocols/jmx/custom/jolokia.pm line 25.
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins/centreon/common/protocols/jmx/custom/jolokia.pm line 25.
Compilation failed in require at /usr/lib/nagios/plugins/centreon/plugins/misc.pm line 221.
[root@TOTO plugins]#  perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=centreon-plugins::apps::tomcat::jmx::plugin  --host=XXX.XXX.XXX.XXX --snmp-version=2 --snmp-community=public --mode=memory
UNKNOWN: Can't locate object method "new" via package "centreon-plugins::apps::tomcat::jmx::plugin" (perhaps you forgot to load "centreon-plugins::apps::tomcat::jmx::plugin"?) at /usr/lib/nagios/plugins/centreon/plugins/script.pm line 279.
[root@bs-su-04 plugins]#  perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=centreon-plugins::apps::tomcat::jmx::plugin  --host=10.222.0.234  --mode=memory              UNKNOWN: Can't locate object method "new" via package "centreon-plugins::apps::tomcat::jmx::plugin" (perhaps you forgot to load "centreon-plugins::apps::tomcat::jmx::plugin"?) at /usr/lib/nagios/plugins/centreon/plugins/script.pm line 279.
[root@bs-su-04 plugins]#

**Comment by garnier-quentin** [comment]
You need to install the perl module:
http://search.cpan.org/~roland/jmx4perl/lib/JMX/Jmx4Perl.pm

**Comment by garnier-quentin** [comment]
I have done a tutorial:
http://nyal.developpez.com/tutoriels/java/supervision-tomcat-avec-couple-jolokia-centreon-plugins/

**Comment by jopkerrien** [comment]
many thx Quentin. I appreciate :+1:

**Comment by garnier-quentin** [comment]
You're welcome
