### ISSUE TITLE
Erreur perl/SSL avec le plugin: apps::protocols::http::plugin

### ISSUE THREAD

**Issue by GhilesKDH** [centreon/centreon-plugins#482]
Bonjour, 

Nous avons cette erreur quand on essaye de faire un check url sur l'adresse indiquée dans le la commande ci-dessous,
**SSL connect attempt failed with unknown errorerror:00000000:lib(0):func(0):reason(0))**
la commande lancée est:
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=sts.fff.fr --urlpath=/adfs/ls/idpinitiatedsignon --proto=https --filter-perfdata time --expected-string="" --timeout="30"   --critical-status='%{http_code}>400' --verbose

Un curl ou wget sur cette adresse fonctionne bien.

Cordialement,

**Comment by garnier-quentin** [comment]
Hi,

Could you tried with following option ? --ssl=sslv3 or --ssl=tlsv1
Which os (debian wheezy, centos 6 ?) do yo use ?

**Comment by GhilesKDH** [comment]
Hi Quentin, 
I tried this options and i have the same result.
i use centos 6.7.
Thanks.

**Comment by garnier-quentin** [comment]
Do you still have the problem ?

**Comment by garnier-quentin** [comment]
You can send me an email if you still have the problem.

**Comment by GhilesKDH** [comment]
Hi quentin, 
Sorry for the delay,
 yes we still have the problem, but now we use another check-url based on curl.

**Comment by garnier-quentin** [comment]
Ok. If you want to find out, you can send me email.

**Comment by VMTS** [comment]
Bonjour,
Je rencontre le même soucis pour certains sites.
