### ISSUE TITLE
[storage::emc::unisphere::restapi::plugin] add quota for mode::storageresources

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon-plugins#4823]
Hi,

Is it possible to add quota supervision for unisphere ?

![Unisphere](https://user-images.githubusercontent.com/61595839/192250870-e685716c-152f-49c8-9448-7a40431d5f0d.jpg)

Api documentation : 
[unity-restapi-refg_en-us_reference-guide8.pdf](https://github.com/centreon/centreon-plugins/files/9645272/unity-restapi-refg_en-us_reference-guide8.pdf)

We can have the names of the quotas:
https://x.x.x.x/api/types/quotaConfig/instances?fields=filesystem.name
and then, we can have the sizes of the soft/hard quotas and the size:
https://x.x.x.x/api/instances/quotaConfig/quotaconfig_171798691851_7?fields=filesystem.name%2CtreeQuota.hardLimit%2CtreeQuota.softLimit%2CtreeQuota.path%2CtreeQuota.state%2CtreeQuota.sizeUsed

example : 
{
    "@base": "https://x.x.x.x/api/instances/quotaConfig",
    "updated": "2023-11-24T12:17:10.374Z",
    "links": [
        {
            "rel": "self",
            "href": "/quotaconfig_171798691851_7"
        }
    ],
    "content": {
        "id": "quotaconfig_171798691851_7",
        "filesystem": {
            "id": "fs_1",
            "name": "FS-Services"
        },
        "treeQuota": {
            "id": "treequota_171798691851_7",
            "state": 0,
            "path": "/Services/DIVISION_BIBLIOTHEQUE",
            "hardLimit": 107374182400,
            "softLimit": 107374182400,
            "sizeUsed": 86862370816
        }
    }
}

Best regards.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
