### ISSUE TITLE
network::dlink::standard::snmp::plugin Memory filter

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#4825]
Hi,

Could you please add option to filter out memory pools when using D-Link devices.
Currently there only seems to be option to change warning and critical thresholds:
 --warning-* --critical-*
            Thresholds. Can be: 'usage' (B), 'usage-free' (B), 'usage-prct'
            (%).

/usr/lib/centreon/plugins/centreon_dlink_standard_snmp.pl --plugin=network::dlink::standard::snmp::plugin --mode=memory --hostname='1.2.3.4' --snmp-community='public' --snmp-version='2c'  --warning-usage-prct='85' --critical-usage-prct='90' 
CRITICAL: Memory 'unit1~flash' total: 29.24 MB used: 27.60 MB (94.41%) free: 1.63 MB (5.59%) | 'unit1~dram#memory.usage.bytes'=76844032B;;;0;268435456 'unit1~dram#memory.free.bytes'=191590400B;;;0;268435456 'unit1~dram#memory.usage.percentage'=28.63%;0:85;0:90;0;100 'unit1~flash#memory.usage.bytes'=28943360B;;;0;30655488 'unit1~flash#memory.free.bytes'=1712128B;;;0;30655488 'unit1~flash#memory.usage.percentage'=94.41%;0:85;0:90;0;100
Memory 'unit1~dram' total: 256.00 MB used: 73.28 MB (28.63%) free: 182.71 MB (71.37%)
Memory 'unit1~flash' total: 29.24 MB used: 27.60 MB (94.41%) free: 1.63 MB (5.59%)

Thanks in advance!

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is an enhancement request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
