### ISSUE TITLE
[os::windows::snmp::plugin] --filter-perfdata ignored if results are on warning/critical levels

### ISSUE THREAD

**Issue by joachim-diaz** [centreon/centreon-plugins#483]
Hello.   I'm using the --filter-perfdata to ignore all but one interface that i want to specifically monitor, by using its description as a way of filtering it. My command is written this way : 

--plugin=os::windows::snmp::plugin --mode=interfaces --hostname=xxx --snmp-community=yyy --oid-display=ifDesc --add-traffic  --speed=1000 --warning-in-traffic=80 --warning-out-traffic=80 --critical-in-traffic=90 --critical-out-traffic=90 --filter-perfdata='vmxnet3 Ethernet Adapter$'

However, if any of the ignored interfaces goes over the warning/critical tresholds, they appear again in the output result. usually, my result will look like this : 

`OK: All interfaces are ok | 'traffic_in_vmxnet3 Ethernet Adapter'=4068.20b/s;0:800000000;0:900000000;0;1000000000 'traffic_out_vmxnet3 Ethernet Adapter'=4947.89b/s;0:800000000;0:900000000;0;1000000000`

If I change warning-in-traffic to 0.0001 for testing purposes, the output becames 

`WARNING: Interface 'vmxnet3 Ethernet Adapter' Traffic In : 3.42Kb/s (0.00%) - Interface 'vmxnet3 Ethernet Adapter-WFP Native MAC Layer LightWeight Filter-0000' Traffic In : 3.42Kb/s (0.00%) - Interface 'vmxnet3 Ethernet Adapter-QoS Packet Scheduler-0000' Traffic In : 3.42Kb/s (0.00%) - Interface 'vmxnet3 Ethernet Adapter-WFP 802.3 MAC Layer LightWeight Filter-0000' Traffic In : 3.42Kb/s (0.00%) | 'traffic_in_vmxnet3 Ethernet Adapter'=3416.31b/s;0:1000;0:900000000;0;1000000000 'traffic_out_vmxnet3 Ethernet Adapter'=4167.86b/s;0:800000000;0:900000000;0;1000000000`

Is this an attended comportement while using this option, and is ther any way to ignore all other interfaces ?  I'd rather use the description name as a filter since interface name doesn't seem to be indentical frome one to another of my machines and it does not seem that --name allows that.

Thank you !

**Comment by garnier-quentin** [comment]
If you want to filter an interface, you should use following options:
```
--interface='vmxnet3 Ethernet Adapter$' --name
```

**Comment by joachim-diaz** [comment]
It doesnt seems to work, only returning " UNKNOWN: No entry found (maybe you should reload cache file" . My command looks like this now :  

`--plugin=os::windows::snmp::plugin --mode=interfaces --hostname=xxx --snmp-community=yyy  --add-traffic  --speed=1000 --interface='vmxnet3 Ethernet Adapter$' --name --warning-in-traffic=80 --warning-out-traffic=80 --critical-in-traffic=90 --critical-out-traffic=90`

"vmxnet3 Ethernet Adapter" being only the description of my interface, will it work via --name ?

**Comment by garnier-quentin** [comment]
Could you use following, give the output and tell which interface do you want to monitor only ?
```
--interface='.*' --name --verbose
```

**Comment by joachim-diaz** [comment]
It's my main issue : i do not know which interface i'd specifically want to monitor. I'm trying to build a check via cent-plugins to monitor the Ethernet card for Windows virtual machines, usually having "vmxnet3 Ethernet Adapter" as their description (in order to remplace an older version working via nagios, with my interface's description as an argument)  and it's likely that the match description/interface will change from one machine to another :/

**Comment by garnier-quentin** [comment]
With options, you can see interfaces availabled. But i can't help you to choose the good interface ;)

**Comment by Mirkokrasic** [comment]
Hello,

im facing same issue, did you find any solution ? 

@garnier-quentin if i know what interface do i want to monitor how can i do it ?

Thank you !

**Comment by garnier-quentin** [comment]
You can change --oid-display and --oid-filter options. (ifdesc, ifname or ifalias). You can test.

**Comment by Mirkokrasic** [comment]
Hello i did not understand what you mean by that " im new to centreon " can you please explain. thank you
