### ISSUE TITLE
Synology missing dependencie

### ISSUE THREAD

**Issue by xi67** [centreon/centreon-plugins#4840]
# Quick description

On Debian, When you install the centreon-plugin-hardware-storage-synology-snmp and try to execute : 

/usr/lib/centreon/plugins/centreon_synology.pl --mode=uptime --hostname=xxxxx
UNKNOWN: Cannot load module --mode.
Can't locate snmp_standard/mode/uptime.pm in @INC (you may need to install the snmp_standard::mode::uptime module) (@INC contains: /usr/lib/centreon/plugins FatPacked::94886063490384=HASH(0x564c621bc550) /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/lib/centreon/plugins/centreon_synology.pl line 1743.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue should had been resolved by this PR https://github.com/centreon/centreon-plugins/pull/4849 
So let me close this issue, if you still encounter it feel free to re-open it :)
