### ISSUE TITLE
incorrect uptime with os::linux::snmp::plugin --mode=uptime

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#485]
Hi,

I have a problem with the plugin ces-plugins-Operatingsystems-Linux-Snmp-2.2-1.noarch:

The value returned by the plugin os::linux::snmp::plugin --mode=uptime is different from the output of the top command.

./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=uptime --hostname=172.16.74.1 --snmp-version='2c' --snmp-community='public'
OK: System uptime is: **215 days** | 'uptime'=18659951s;;;0;

top - 10:15:31 up **711 days**, 22:14, 11 users, load average: 33.29, 32.86, 33.73
Tasks: 408 total, 30 running, 378 sleeping, 0 stopped, 0 zombie
[...]

I think the problem is that the counter of oid is a 32bits-counter, the maximum possible uptime that the sensor can display is 497 days. If the uptime exceeds this value, i.e., the monitored device runs longer than 497 days, the counter resets to 0 (711-497=214). (https://kb.paessler.com/en/topic/61249-why-does-the-snmp-system-uptime-sensor-report-wrong-values)

If there any way to get the correct uptime with this plugin ?

PS: I have try a snmpwalk on the oid 1.3.6.1.2.1.1.3.0 but i have the same problem...

Thank you

**Comment by garnier-quentin** [comment]
You have the answer in the link. You can try to use the OID with --force-oid=".1.3.6.1.2.1.1.3.0"
