### ISSUE TITLE
Is this project stale ?

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon-plugins#4851]
Or closed to PR ?

**Comment by omercier** [comment]
Hi Colin,
No, this project is neither stale nor closed to PRs.
I recognize that you have been waiting a lot more than you should.
As you may know, there has been an important departure from the connectors team lately, and the day-to-day priorities have taken our eyes out of the issues and PRs on github.
We are going to try integrate the fix/feature PRs proposed by our community (and also the issues, of course) more regularly starting now. Let's consider this as a new year good resolution!
Thanks a lot for all your contributions.
Best regards,
Olivier
