### ISSUE TITLE
[network::h3c::snmp::plugin] mode hardware

### ISSUE THREAD

**Issue by bgillon** [centreon/centreon-plugins#486]
Hello,

when i try to test option --filter this doesn't works.
i have fix this problem in hardware.pm
how can i checkin fix ?

regards

**Comment by garnier-quentin** [comment]
Hi,

Could you paste the command line and the result please ?

**Comment by bgillon** [comment]
perl centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=hardware --hostname=xxx --snmp-community=xxx --snmp-version=x --component=psu --filter=psu,'194|212|230|248' --verbose
Checking power supplies
Power supply 'HPE > HPE 5130-24G-PoE+-2SFP+-2XGT (370W) EI JG940A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 193]
Power supply 'HPE > HPE 5130-24G-PoE+-2SFP+-2XGT (370W) EI JG940A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'psuError' [instance = 194]
Power supply 'HPE > HPE 5130-24G-PoE+-2SFP+-2XGT (370W) EI JG940A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 211]
Power supply 'HPE > HPE 5130-24G-PoE+-2SFP+-2XGT (370W) EI JG940A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'psuError' [instance = 212]
Power supply 'HPE > HPE 5130-48G-PoE+-2SFP+-2XGT (370W) EI JG941A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 229]
Power supply 'HPE > HPE 5130-48G-PoE+-2SFP+-2XGT (370W) EI JG941A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'psuError' [instance = 230]
Power supply 'HPE > HPE 5130-48G-PoE+-2SFP+-2XGT (370W) EI JG941A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 247]
Power supply 'HPE > HPE 5130-48G-PoE+-2SFP+-2XGT (370W) EI JG941A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'psuError' [instance = 248]

after fix result is
Checking power supplies
Power supply 'HPE > HPE 5130-24G-PoE+-2SFP+-2XGT (370W) EI JG940A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 193]
Skipping psu section 194 instance.
Power supply 'HPE > HPE 5130-24G-PoE+-2SFP+-2XGT (370W) EI JG940A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 211]
Skipping psu section 212 instance.
Power supply 'HPE > HPE 5130-48G-PoE+-2SFP+-2XGT (370W) EI JG941A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 229]
Skipping psu section 230 instance.
Power supply 'HPE > HPE 5130-48G-PoE+-2SFP+-2XGT (370W) EI JG941A Software Version 7.1.045 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 247]
Skipping psu section 248 instance.

**Comment by garnier-quentin** [comment]
What did you fix ? Because it should work before.

**Comment by bgillon** [comment]
sub new {
    my ($class, %options) = @_;
    my $self = $class->SUPER::new(package => __PACKAGE__, %options);
    bless $self, $class;
....
    $self->{version} = '1.0';
    $options{options}->add_options(arguments =>
                                {
                                  **"filter:s@"               => { name => 'filter' },**
                                  "reload-cache-time:s"     => { name => 'reload_cache_time', default => 180 },
                                });
                                                                          
    $self->{statefile_cache} = centreon::plugins::statefile->new(%options);....
    return $self;                                                         
}                                                                         
                                                                          
sub check_options {                                                       
    my ($self, %options) = @_;                                            
    $self->SUPER::init(%options);

    **$self->{filter} = [];
    foreach my $val (@{$self->{option_results}->{filter}}) {
        next if (!defined($val) || $val eq '');
        my @values = split (/,/, $val);
        push @{$self->{filter}}, { filter => $values[0], instance => $values[1] };
    }**

    $self->{statefile_cache}->check_options(%options);
}

**Comment by garnier-quentin** [comment]
Ok. When i'm looking your file it's not the last version. Could you do the update ?

**Comment by bgillon** [comment]
sorry i'm novice with git.
if i use this command "git checkout -f master"
my fix file is override
and if i look on file i have this code, and doesn't work ?

sub new {
    my ($class, %options) = @_;
    my $self = $class->SUPER::new(package => __PACKAGE__, %options);
    bless $self, $class;
            
    $self->{version} = '1.0';
    $options{options}->add_options(arguments =>
                                {
                                  "reload-cache-time:s"     => { name => 'reload_cache_time', default => 180 },
                                });
     $self->{statefile_cache} = centreon::plugins::statefile->new(%options);
    return $self;
}
          
sub check_options {
    my ($self, %options) = @_;
    $self->SUPER::init(%options);
        
    $self->{statefile_cache}->check_options(%options);
}

**Comment by garnier-quentin** [comment]
Try to test it from the zip file: 
https://github.com/centreon/centreon-plugins/archive/master.zip

**Comment by bgillon** [comment]
same result.
instance defined in filter argument is not skipped

**Comment by garnier-quentin** [comment]
That's really weird. Because the option is present in 'centreon/plugins/templates/hardware.pm'.

**Comment by garnier-quentin** [comment]
Could you send me an email to do a distant session ?
