### ISSUE TITLE
Enhancement: Alert on stalling value

### ISSUE THREAD

**Issue by GuillaumeBernard** [centreon/centreon-plugins#487]
Hello,

Our developers added some Windows performance counters to their application, available in perfmon. We can successfully monitor them in Centreon using NSCLIENT++.
One of these counters should be always changing, if the value is stalling it means the application is stuck.
We want Centreon to be able to send an email alert if the value is stalling, instead of using warning and critical thresholds.

Regards,
Guillaume

**Comment by garnier-quentin** [comment]
Hi Guillaume,

I won't add these kind of system in "centreon-plugins". Like i won't add the capability to: get an alert if the cpu is 100% for 2 hours. 
It will become too complex. It should be managed by a correlation system. Scripting language (perl, python,...) doesn't fit for storing datas. It consumes too much memory.
