### ISSUE TITLE
[HP ProCurve] Newbie question

### ISSUE THREAD

**Issue by sulian** [centreon/centreon-plugins#488]
Hello

I have some HP ProCurve 5406zl, 2848 and 2910 at work and I cannot obtain informations when I use the procurve plugin only a warning.

<code>
./centreon_plugins.pl --plugin=network::hp::procurve::plugin --hostname=192.168.10.62 --mode=environment --debug

WARNING: power supply sensor 'power supply.6' state is not present - power supply sensor 'power supply.8' state is not present |

Checking sensors
fan sensor 'fan.1' state is good [instance: fan.1].
power supply sensor 'power supply.2' state is good [instance: power supply.2].
power supply sensor 'power supply.3' state is good [instance: power supply.3].
power supply sensor 'power supply.4' state is good [instance: power supply.4].
power supply sensor 'power supply.5' state is good [instance: power supply.5].
power supply sensor 'power supply.6' state is not present [instance: power supply.6].
temperature sensor 'temperature.7' state is good [instance: temperature.7].
power supply sensor 'power supply.8' state is not present [instance: power supply.8].
power supply sensor 'power supply.9' state is good [instance: power supply.9].
</code>

With the h3c plugin, I can obtain theses informations : 

<code>
./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --hostname=192.168.10.62 --mode=hardware --component='psu' --debug

OK: All 0 components are ok []. |
</code>

I have this result for all my switches. I'm not an expert of Centreon and SNMP, did I make something wrong ?

**Comment by garnier-quentin** [comment]
It's working with the procurve plugin but you have some power supply not present. You can add the following option:
```
--threshold-overload='sensor,OK,not present'
```

**Comment by sulian** [comment]
It works well but result show `OK : All 9 components are ok [9/9 sensors].` but I have only 6 sensors actives on my switch (HP ProCurve 5406zl in my case). The result could be `OK : All 6 components are ok [6/6 sensors]. | 3 components are inactive [3/3 sensors]` or something like that.

Am I wrong ?

**Comment by sulian** [comment]
If I know wich sensor is inactive for each categories of switches, how I can exclude them from result ?

**Comment by garnier-quentin** [comment]
You can filter it with following option (for example):
--filter=sensor,power supply.1

**Comment by sulian** [comment]
Thanks you 👍 

My command line is now : 

`./centreon_plugins.pl --plugin=network::hp::procurve::plugin --hostname=192.168.10.62 --mode=environment --filter='sensor,power supply.6|8|9'` in order to skip power supply.6, 7 & 9

works like a charm
