### ISSUE TITLE
database::postgres::plugin --mode=hitratio - negative value

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#489]
Hi,

On some postgre database, I have a negative hitratio like this:
       CRITICAL: Database 'RM' hitratio at -1176.65%

How is it possible? How is calculated hitratio?

thanks for your lights ;)
regards

**Comment by garnier-quentin** [comment]
It's weird. It does that often ? Do you have two checks (of that service) for the same database ?
It takes values from the following request:
```
SELECT sd.blks_hit, sd.blks_read, d.datname
FROM pg_stat_database sd, pg_database d
WHERE d.oid=sd.datid
```

**Comment by cmeschin** [comment]
Hi quentin,

I have only one check hitratio by host but without filter on specific database.

I use this command:
/usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=database::postgres::plugin --mode=hitratio --host=X.X.X.X --port=5432 --username='xxx' --password='xxx' --exclude='' --warning='99:' --critical='90:' --lookback

and the result:
![postgre_hitratio](https://cloud.githubusercontent.com/assets/8720203/18521344/03d477f6-7aac-11e6-91c7-19193e81d20f.png)

**Comment by garnier-quentin** [comment]
Could you give me the result of the request postgres ? 2 times (wait 2 minutes between)
```
SELECT sd.blks_hit, sd.blks_read, d.datname
FROM pg_stat_database sd, pg_database d
WHERE d.oid=sd.datid
```

**Comment by cmeschin** [comment]
Hi, Sorry for the answer delay...
here's query results  at 15h00 and 15h02 today.
query at 15h00
![postgresql_hitratio_1500](https://cloud.githubusercontent.com/assets/8720203/18955109/3bfb2584-8656-11e6-8021-a5f42bb31916.png)

query at 15h02
![postgresql_hitratio_1502](https://cloud.githubusercontent.com/assets/8720203/18955110/3bfd33b0-8656-11e6-8d86-d9e474aa8647.png)

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by cmeschin** [comment]
Hi,
test in progess...
I look back in few days.

**Comment by cmeschin** [comment]
Hi Quentin,
It seems to be ok now. No negatives values but low performances for these databases. perhaps they requires optimisations... the dba must work now :)

Thanks.

**Comment by garnier-quentin** [comment]
I can't help you for that :) Thanks for the feedback
