### ISSUE TITLE
UNKNOWN: SNMP GET Request : Cant get a single value.

### ISSUE THREAD

**Issue by jopkerrien** [centreon/centreon-plugins#491]
Bonjour,

je rencontre des soucis pour le mode load pour une machine distante centOS 6.4 :

perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname=XXXXXXXXXX --mode=load --snmp-community=public --warning=4,3,2 --critical=6,5,4

et quand je fais sur la machine locale càd le serveur centreon centOS 6.8 c'est OK : 

[root@XXXXXXX mode]# perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname=localhost --mode=load
OK: Load average: 2.65, 2.89, 2.73 | 'load1'=2.65;;;0; 'load5'=2.89;;;0; 'load15'=2.73;;;0;

une aide serait hautement appreciée. Merci

**Comment by garnier-quentin** [comment]
I think it's a problem of snmp configuration. About the scope of oids.

**Comment by jopkerrien** [comment]
Thx Quentin,

snmpwalk  just answers with a long output. 

[root@xxxxxxxx mode]# snmpwalk -c public -v 2c xxxxxxxxxxx

une piste ?

**Comment by garnier-quentin** [comment]
You have the result with snmpwalk ?

**Comment by jopkerrien** [comment]
not really but got some load related output

[root@XXXXXXX mode]# snmpwalk -c public -v 2c xxxxxxxxx | grep -i load
HOST-RESOURCES-MIB::hrSystemInitialLoadDevice.0 = INTEGER: 1536
HOST-RESOURCES-MIB::hrSystemInitialLoadParameters.0 = STRING: "ro root=/dev/mapper/vg_bsctxtom1-lv_root rd_LVM_LV=vg_bsctxtom1/lv_root rd_NO_LUKS  KEYBOARDTYPE=pc KEYTABLE=fr rd_NO_MD LANG=fr"
HOST-RESOURCES-MIB::hrProcessorLoad.768 = INTEGER: 5
HOST-RESOURCES-MIB::hrProcessorLoad.769 = INTEGER: 2
HOST-RESOURCES-MIB::hrProcessorLoad.770 = INTEGER: 2
HOST-RESOURCES-MIB::hrProcessorLoad.771 = INTEGER: 2
HOST-RESOURCES-MIB::hrSWInstalledName.71 = STRING: "perl-Module-Load-Conditional-0.30-129.el6"
HOST-RESOURCES-MIB::hrSWInstalledName.199 = STRING: "libreport-plugin-reportuploader-2.0.9-25.el6.centos"
HOST-RESOURCES-MIB::hrSWInstalledName.590 = STRING: "perl-Module-Loaded-0.02-129.el6"
HOST-RESOURCES-MIB::hrSWInstalledName.885 = STRING: "perl-Module-Load-0.16-129.el6"
[root@bs-su-04 mode]#

**Comment by garnier-quentin** [comment]
Could you walk that OID: .1.3.6.1.4.1.2021.10.1.3

**Comment by jopkerrien** [comment]
No

[root@xxxxxxxxxxxxx mode]# snmpwalk -c public -v 2c xxxxxxxxxxxxxx  .1.3.6.1.4.1.2021.10.1.3
UCD-SNMP-MIB::laLoad = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by garnier-quentin** [comment]
That's the problem. You need to add that branch.

**Comment by jopkerrien** [comment]
Good catch !

Many thx  Quentin.
