### ISSUE TITLE
Deploy nsclient++-centreon with ansible

### ISSUE THREAD

**Issue by JSTBotanic** [centreon/centreon-plugins#4916]
Hi,

I have to deploy on much servers the agent and i would like to deploy it with ansible.

Have you got the role for deploy it or the documentation for install it with silent option ?

Thank you so much,

Regards

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I'm not sure to understand what you mean about deploy NSClient with ansible?
Same for the documentation is it about ansible or NSClient?
