### ISSUE TITLE
network::cisco::standard::snmp::plugin  mode=memory SNMP GET Request: Cant get a single value.

### ISSUE THREAD

**Issue by Cancom-Monitoring** [centreon/centreon-plugins#4922]
Hi, we experience a timeout when monitoring memory of Cisco collaboration products (CUCM, IM&P, CUUC)
callmanager plugin has no memory check, therefor we tried these (please let me know, if we should use another plugin...):

./centreon_plugins.pl --plugin  network::cisco::standard::snmp::plugin --mode memory --hostname 1.2.3.4 --snmp-community=example --snmp-version=2
UNKNOWN: SNMP Table Request: Timeout

./centreon_plugins.pl --plugin=os::linux::snmp::plugin --hostname 1.2.3.4 --snmp-community=example --snmp-version=2 --mode=memory
UNKNOWN: SNMP GET Request: Cant get a single value.

Cisco TAC recommends following OID's:
Object hrStorageSize
OID 1.3.6.1.2.1.25.2.3.1.5
Object hrStorageUsed
OID 1.3.6.1.2.1.25.2.3.1.6
object hrMemorySize
OID 1.3.6.1.2.1.25.2.2

snmpwalk -v 2c -c example 1.2.3.4 1.3.6.1.2.1.25.2.3.1.3
iso.3.6.1.2.1.25.2.3.1.3.1 = STRING: "Physical RAM"
iso.3.6.1.2.1.25.2.3.1.3.2 = STRING: "Virtual Memory"
iso.3.6.1.2.1.25.2.3.1.3.3 = STRING: "/sys"
iso.3.6.1.2.1.25.2.3.1.3.4 = STRING: "/proc"
iso.3.6.1.2.1.25.2.3.1.3.5 = STRING: "/dev"
iso.3.6.1.2.1.25.2.3.1.3.6 = STRING: "/sys/kernel/security"
iso.3.6.1.2.1.25.2.3.1.3.7 = STRING: "/dev/shm"
iso.3.6.1.2.1.25.2.3.1.3.8 = STRING: "/dev/pts"
iso.3.6.1.2.1.25.2.3.1.3.9 = STRING: "/run"
iso.3.6.1.2.1.25.2.3.1.3.10 = STRING: "/sys/fs/cgroup"
iso.3.6.1.2.1.25.2.3.1.3.11 = STRING: "/sys/fs/cgroup/systemd"
iso.3.6.1.2.1.25.2.3.1.3.12 = STRING: "/sys/fs/pstore"
iso.3.6.1.2.1.25.2.3.1.3.13 = STRING: "/sys/fs/cgroup/cpu,cpuacct"
iso.3.6.1.2.1.25.2.3.1.3.14 = STRING: "/sys/fs/cgroup/memory"
iso.3.6.1.2.1.25.2.3.1.3.15 = STRING: "/sys/fs/cgroup/freezer"
iso.3.6.1.2.1.25.2.3.1.3.16 = STRING: "/sys/fs/cgroup/perf_event"
iso.3.6.1.2.1.25.2.3.1.3.17 = STRING: "/sys/fs/cgroup/net_cls,net_prio"
iso.3.6.1.2.1.25.2.3.1.3.18 = STRING: "/sys/fs/cgroup/hugetlb"
iso.3.6.1.2.1.25.2.3.1.3.19 = STRING: "/sys/fs/cgroup/cpuset"
iso.3.6.1.2.1.25.2.3.1.3.20 = STRING: "/sys/fs/cgroup/blkio"
iso.3.6.1.2.1.25.2.3.1.3.21 = STRING: "/sys/fs/cgroup/devices"
iso.3.6.1.2.1.25.2.3.1.3.22 = STRING: "/sys/fs/cgroup/pids"
iso.3.6.1.2.1.25.2.3.1.3.23 = STRING: "/sys/kernel/config"
iso.3.6.1.2.1.25.2.3.1.3.24 = STRING: "/"
iso.3.6.1.2.1.25.2.3.1.3.25 = STRING: "/sys/fs/selinux"
iso.3.6.1.2.1.25.2.3.1.3.26 = STRING: "/proc/sys/fs/binfmt_misc"
iso.3.6.1.2.1.25.2.3.1.3.27 = STRING: "/dev/hugepages"
iso.3.6.1.2.1.25.2.3.1.3.28 = STRING: "/sys/kernel/debug"
iso.3.6.1.2.1.25.2.3.1.3.29 = STRING: "/dev/mqueue"
iso.3.6.1.2.1.25.2.3.1.3.30 = STRING: "/sys/fs/fuse/connections"
iso.3.6.1.2.1.25.2.3.1.3.31 = STRING: "/proc/sys/fs/binfmt_misc"
iso.3.6.1.2.1.25.2.3.1.3.32 = STRING: "/partB"
iso.3.6.1.2.1.25.2.3.1.3.33 = STRING: "/grub"
iso.3.6.1.2.1.25.2.3.1.3.34 = STRING: "/common"
iso.3.6.1.2.1.25.2.3.1.3.35 = STRING: "/var/log/ramfs/cm/trace/ccm/sdi"
iso.3.6.1.2.1.25.2.3.1.3.36 = STRING: "/var/log/ramfs/cm/trace/ccm/sdl"
iso.3.6.1.2.1.25.2.3.1.3.37 = STRING: "/var/log/ramfs/cm/trace/ccm/calllogs"
iso.3.6.1.2.1.25.2.3.1.3.38 = STRING: "/var/log/ramfs/cm/trace/ccm/dntrace"
iso.3.6.1.2.1.25.2.3.1.3.39 = STRING: "/var/log/ramfs/cm/trace/lbm/sdl"
iso.3.6.1.2.1.25.2.3.1.3.40 = STRING: "/var/log/ramfs/cm/trace/cti/sdi"
iso.3.6.1.2.1.25.2.3.1.3.41 = STRING: "/var/log/ramfs/cm/trace/cti/sdl"
iso.3.6.1.2.1.25.2.3.1.3.42 = STRING: "/run/user/513"
iso.3.6.1.2.1.25.2.3.1.3.43 = STRING: "/run/user/504

snmpwalk -v 2c -c example 1.2.3.4  1.3.6.1.2.1.25.2.3.1.5
iso.3.6.1.2.1.25.2.3.1.5.1 = INTEGER: 1486221
iso.3.6.1.2.1.25.2.3.1.5.2 = INTEGER: 1535998
iso.3.6.1.2.1.25.2.3.1.5.3 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.4 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.5 = INTEGER: 735650
iso.3.6.1.2.1.25.2.3.1.5.6 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.7 = INTEGER: 743110
iso.3.6.1.2.1.25.2.3.1.5.8 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.9 = INTEGER: 743110
iso.3.6.1.2.1.25.2.3.1.5.10 = INTEGER: 743110
iso.3.6.1.2.1.25.2.3.1.5.11 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.12 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.13 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.14 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.15 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.16 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.17 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.18 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.19 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.20 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.21 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.22 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.23 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.24 = INTEGER: 9189500
iso.3.6.1.2.1.25.2.3.1.5.25 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.26 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.27 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.28 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.29 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.30 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.31 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.5.32 = INTEGER: 9189500
iso.3.6.1.2.1.25.2.3.1.5.33 = INTEGER: 245671
iso.3.6.1.2.1.25.2.3.1.5.34 = INTEGER: 32055355
iso.3.6.1.2.1.25.2.3.1.5.35 = INTEGER: 148623
iso.3.6.1.2.1.25.2.3.1.5.36 = INTEGER: 148623

snmpwalk -v 2c -c example 1.2.3.4  1.3.6.1.2.1.25.2.3.1.6
iso.3.6.1.2.1.25.2.3.1.6.1 = INTEGER: 885630
iso.3.6.1.2.1.25.2.3.1.6.2 = INTEGER: 512000
iso.3.6.1.2.1.25.2.3.1.6.3 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.4 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.5 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.6 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.7 = INTEGER: 9467
iso.3.6.1.2.1.25.2.3.1.6.8 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.9 = INTEGER: 78114
iso.3.6.1.2.1.25.2.3.1.6.10 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.11 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.12 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.13 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.14 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.15 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.16 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.17 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.18 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.19 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.20 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.21 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.22 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.23 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.24 = INTEGER: 4339059
iso.3.6.1.2.1.25.2.3.1.6.25 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.26 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.27 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.28 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.29 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.30 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.31 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.32 = INTEGER: 4278922
iso.3.6.1.2.1.25.2.3.1.6.33 = INTEGER: 9697
iso.3.6.1.2.1.25.2.3.1.6.34 = INTEGER: 15336390
iso.3.6.1.2.1.25.2.3.1.6.35 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.36 = INTEGER: 0
iso.3.6.1.2.1.25.2.3.1.6.37 = INTEGER: 0

snmpwalk -v 2c -c example 1.2.3.4  1.3.6.1.2.1.25.2.2
iso.3.6.1.2.1.25.2.2.0 = INTEGER: 5944884

Is there a way to add these to a plugin?
Thanks a lot!

**Comment by Luth1ng** [comment]
Hi, please try these :
PLUGIN: os::windows::snmp::plugin
MODE memory
MODE swap

PLUGIN: apps::vmware::vcsa::snmp::plugin
MODE memory

PLUGIN: os::linux::snmp::plugin
MODE storage
MODE list-storages


Please note that no plugin uses the OID "1.3.6.1.2.1.25.2.2", you should have to use the generic snmp plugin with --oid parameter to manually check this

**Comment by Cancom-Monitoring** [comment]
Hi, 
cisco is a mirakle...

snmpwalk:
>iso.3.6.1.2.1.1.1.0 = STRING: "**Linux** release:3.10.0-957.21.3.el7.x86_64 machine:x86_64"
>iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.9.1.1348
...

PLUGIN: os::linux::snmp::plugin
MODE list-storages
>Skipping storage 'Physical RAM': no type or no matching filter type...

PLUGIN: apps::vmware::vcsa::snmp::plugin
MODE memory
>UNKNOWN: Illegal division by zero ...

BUT:

PLUGIN: os::**windows**::snmp::plugin:
MODE memory
>OK: Ram Total: 7.64GB Used: 4.15GB (54.38%) Free: 3.48GB (45.62%) | 'used'=4459409408B;;;0;8201179136

MODE swap
>OK: Swap Total: 3.91 GB Used: 1.13 GB (28.84%) Free: 2.78 GB (71.16%) | 'used'=1209806848B;;;0;4194299904

Thanks a lot for the hint, awesome!
