### ISSUE TITLE
apps::protocols::http::plugin --mode collection variable naming after jsonPath

### ISSUE THREAD

**Issue by MohaLaD** [centreon/centreon-plugins#4934]
From F5 Rseries API we usually get json data with - or : in keys, like this:
{
  "f5-fan-psu-stats:psu-stats": {
    "psu-current-in": "0.24",
    "psu-current-out": "2.8",
    "psu-voltage-in": "228.8",
    "psu-voltage-out": "12.0",
    "psu-temperature-1": "34.0",
    "psu-temperature-2": "29.0",
    "psu-temperature-3": "50.0",
    "psu-fan-1-speed": 9800
  }
}

with a parse like that:
"parse": [
                    {
                        "entries": [
                                {
                                  "id": "psu-current-in"
                                },
                                {
                                  "id": "psu-current-out"
                                },
                                {
                                  "id": "psu-voltage-in"
                                },
                                {
                                  "id": "psu-voltage-out"
                                },
                                {
                                  "id": "psu-temperature-1"
                                },
                                {
                                  "id": "psu-temperature-2"
                                },
                                {
                                  "id": "psu-temperature-3"
                                },
                                {
                                  "id": "psu-fan-1-speed"
                                }
                        ],
                        "name": "entries",
                        "path": "$.*",
                        "type": "body"
                    }
],

my variable table would be like that:
    http.tables.platformDetailsRequestTestsEntries.[0].psu-current-out = 2.8
    http.tables.platformDetailsRequestTestsEntries.[0].psu-temperature-1 = 34.0
    http.tables.platformDetailsRequestTestsEntries.[0].psu-fan-1-speed = 9800
    http.tables.platformDetailsRequestTestsEntries.[0].psu-voltage-out = 12.0
    http.tables.platformDetailsRequestTestsEntries.[0].psu-temperature-3 = 50.0
    http.tables.platformDetailsRequestTestsEntries.[0].psu-current-in = 0.24
    http.tables.platformDetailsRequestTestsEntries.[0].psu-voltage-in = 228.8
    http.tables.platformDetailsRequestTestsEntries.[0].psu-temperature-2 = 29.0

When i try to use the variable in selections, i get the error : UNKNOWN: [http > requests] character '-' forbidden

because - and : are not allowed in the function parse_http_tables call for parse_forward, can you please fix it, maybe by replacing - and : by a _ in the attributes after json path parse.

**Comment by garnier-quentin** [comment]
You can use following patch: https://github.com/centreon/centreon-plugins/pull/4915

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue should had been resolved during the June release with the PR https://github.com/centreon/centreon-plugins/pull/5044
Feel free to re-open this issue if not.
