### ISSUE TITLE
[network::dlink::standard::snmp::plugin] Some problems with DGS 1210-48

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon-plugins#495]
We are currently adding our switches to centreon. 

Everything is working like a charm with snmpv3 for HP switches (interfaces, cpu, hardware ..)

But we are encountering some problems with the dlink plugin with two DGS 1210-48G.

When i'm trying to use the plugin for cpu : 

UNKNOWN: SNMP GET Request : Cant get a single value.

And hardware : 

OK: All 0 components are ok []. |

I tried snmpwalk with the OIDs that are mentionned in the plugin : 

fan for example  : 

SNMPv2-SMI::enterprises.171.12.11.1.7.1.6 = No Such Object available on this agent at this OID
SNMPv2-SMI::enterprises.171.12.11.1.7.1 = No Such Object available on this agent at this OID

It seems that they don't exist in the MIB.

Do you think this model is not supported by the plugin ? (i tried with standard and DGS3100)

Thank You. 

Anthony

**Comment by garnier-quentin** [comment]
I think there is no information about hardware in that dlink hardware. You could do a look with a snmpwalk.

**Comment by anthoc** [comment]
Thank you for your fast answer. 

Effectively, i tried snmpwalk on some OIDs included in the plugin and the result is always the same : 

> No Such Object available on this agent at this OID

I don't know why they didn't include these informations in this model, they are useful. 

On the other hand, the interfaces mode is working good.

Thank You.

**Comment by anthoc** [comment]
Hello,

I'm in trouble again. I'm trying to use Interfaces mode with snmpv3. Here is an example : 

`./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin --mode=interfaces --hostname=<ip> --snmp-community=public --snmp-version=3 --snmp-username=<username> --authpassphrase=<authpassword> --authprotocol=<authprotocol> --privpassphrase=<privpassword> --privprotocol=<privprotocol> --name --interface='^1' --add-traffic`

This return this error : 

`UNKNOWN: SNMP GET Request : Too long`

It's working with a specific interface (for example  --name --interface='^1/12') :

`OK: Interface '1/12' Status : up (admin: up) |`

And it's working without snmpv3 : 

`# ./centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin --mode=interfaces --hostname=<> --snmp-community=public-test --snmp-version=2c --add-traffic  --name --interface='^1/'                                                                                                         OK: All interfaces are ok | 'traffic_in_1/1'=18.70b/s;;;0;100000000 'traffic_in_1/11'=8552.45b/s;;;0;100000000 'traffic_in_1/12'=658.37b/s;;;0;100000000 'traffic_in_1/13'=19123.27b/s;;;0;1000000000 'traffic_in_1/15'=4192.00b/s;;;0;1000000000 'traffic_in_1/16'=780.62b/s;;;0;100000000 'traffic_in_1/17'=15555.27b/s;;;0;100000000 'traffic_in_1/19'=5443.61b/s;;;0;100000000 'traffic_in_1/20'=45348.39b/s;;;0;100000000 'traffic_in_1/21'=648.56b/s;;;0;100000000 'traffic_in_1/23'=805.97b/s;;;0;100000000 'traffic_in_1/24'=28011.49b/s;;;0;1000000000 'traffic_in_1/26'=1452.51b/s;;;0;1000000000 'traffic_in_1/28'=2594.70b/s;;;0;1000000000 'traffic_in_1/31'=16609.35b/s;;;0;1000000000 'traffic_in_1/32'=55410.93b/s;;;0;1000000000 'traffic_in_1/33'=459.49b/s;;;0;100000000 'traffic_in_1/34'=8964.28b/s;;;0;100000000 'traffic_in_1/35'=12234.70b/s;;;0;1000000000 'traffic_in_1/36'=2896.56b/s;;;0;1000000000 'traffic_in_1/37'=16563.38b/s;;;0;1000000000 'traffic_in_1/4'=28317.18b/s;;;0;1000000000 'traffic_in_1/40'=653.86b/s;;;0;100000000 'traffic_in_1/42'=1795.72b/s;;;0;1000000000 'traffic_in_1/43'=787.27b/s;;;0;100000000 'traffic_in_1/44'=1145799.32b/s;;;0;1000000000 'traffic_in_1/45'=11083.61b/s;;;0;100000000 'traffic_in_1/46'=17651.49b/s;;;0;100000000 'traffic_in_1/5'=466.59b/s;;;0;100000000 'traffic_in_1/7'=49157.41b/s;;;0;100000000 'traffic_in_1/8'=656.11b/s;;;0;100000000 'traffic_in_1/9'=16309.52b/s;;;0;100000000
`

Do you have any clue ?

Thank You

Anthony

**Comment by garnier-quentin** [comment]
It can happen with SNMP protocol. Use following options:
--maxrepetitions=20 --subsetleef=20
