### ISSUE TITLE
os::windows::local::plugin --mode=rdp-sessions

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#496]
Hello,

With centreon-nsclient v0.4.3.143 the mode rdp-sessions doesn't seem to work:

check_centreon_nrpe -H 10.10.10.10 -m 8192 -n -c check_centreon_plugins -a "os::windows::local::plugin" "rdp-sessions"

Can't locate os/windows/local/mode/rdpsessions.pm in @INC (you may need to install the os::windows::local::mode::rdpsessions module) (@INC contains: CODE(0x28720b8) C:\WINDOWS\TEMP\par-4d525448532d50432d4130313224\cache-a679a69ba7c36a045bd7a09036999ea66e133056\inc\lib C:\WINDOWS\TEMP\par-4d525448532d50432d4130313224\cache-a679a69ba7c36a045bd7a09036999ea66e133056\inc CODE(0x23e03d8) CODE(0x23e0900)) at C:\WINDOWS\TEMP\par-4d525448532d50432d4130313224\cache-a679a69ba7c36a045bd7a09036999ea66e133056\inc\lib/centreon/plugins/misc.pm line 211.

But the time mode works fine:
check_centreon_nrpe -H 10.10.10.10 -m 8192 -n -c check_centreon_plugins -a "os::windows::local::plugin" "time"

OK: Time offset 0.025 second(s) | 'offset'=0.025s;;;;

**Comment by Sims24** [comment]
Hi, 

This is not a plugin issus.

That's come from your nsclient version, it has not been compiled with this mode. You should build it as specified in the documentation including rdpsession.pm mode. 

Thanks !
