### ISSUE TITLE
New plugin: test connection RDP

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#497]
Hello team,

Is it possible to create a plugin to test a connection (with login/password) to a Windows RDP Server?
It could be fine if the login account could be a Active Directory account.

Thanks in advance.

**Comment by garnier-quentin** [comment]
First you can test tcp connection on port 3389. Otherwise, you should use Sikuli to do that:
http://www.sikuli.org/

Maybe we could use freerdp. But there is no bindings. (http://www.freerdp.com/)
