### ISSUE TITLE
[os::linux::snmp::plugin] mode inodes 

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon-plugins#499]
Hi,

I have a question about inodes mode. I'm currently creating a plugin to check Inodes on all partitions on all my servers. For some of them, usage for partition / is displayed 2 times by the command, I don't understand why : 

`./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=inodes --hostname=********* --snmp-version=3 --snmp-community=******** --snmp-username=********* --authpassphrase=********* --authprotocol=********* --privpassphrase=********* --privprotocol=********* --warning-usage 80 --critical-usage 90 --name --regexp --diskpath='(^/var$|^/home$|^/archives$|^/tmp$|^/usr$|^/$)'`

> OK: All inode partitions are ok | 
> 
> 'used_/'=1%;0:80;0:90;0;100 
> 'used_/var'=0%;0:80;0:90;0;100 
> 'used_/'=1%;0:80;0:90;0;100

I thought it was related to the fact that I have multiples physical drives and PVS on this host, but the two results are exactly the same. 

Could you please help us ? 

Thank You.

**Comment by garnier-quentin** [comment]
Could you give me the snmpwalk for following oids:
.1.3.6.1.4.1.2021.9.1.2
.1.3.6.1.4.1.2021.9.1.3
.1.3.6.1.4.1.2021.9.1.10

**Comment by anthoc** [comment]
Thank you for your fast answer. I think i understand, it seems to be related to RAID Controller. Here's a sample of the snmpwalk :

for .1.3.6.1.4.1.2021.9.1.2 : 

> UCD-SNMP-MIB::dskPath.1 = STRING: /
> UCD-SNMP-MIB::dskPath.2 = STRING: /var
> UCD-SNMP-MIB::dskPath.3 = STRING: /

for .1.3.6.1.4.1.2021.9.1.3 :

> UCD-SNMP-MIB::dskDevice.1 = STRING: /dev/dm-0
> UCD-SNMP-MIB::dskDevice.2 = STRING:
> UCD-SNMP-MIB::dskDevice.3 = STRING: /dev/dm-0

.1.3.6.1.4.1.2021.9.1.10 :

> UCD-SNMP-MIB::dskPercentNode.1 = INTEGER: 1
> UCD-SNMP-MIB::dskPercentNode.2 = INTEGER: 0
> UCD-SNMP-MIB::dskPercentNode.3 = INTEGER: 1

Do you think this can explain too, why i have the same result for some LXC container and KVM hosted on this machine ?

Thank You.

**Comment by garnier-quentin** [comment]
So it comes from net-snmp. Maybe i could discard if it's the same path.

**Comment by anthoc** [comment]
This is not really a problem in fact. :) Thank you

**Comment by garnier-quentin** [comment]
it should be ok now. Could you test it ?

**Comment by anthoc** [comment]
It's working very well ! Thank you !

**Comment by garnier-quentin** [comment]
Thanks for the feedback and using "centreon-plugins".
