### ISSUE TITLE
Partition /var/lib/centreon-broker is full.

### ISSUE THREAD

**Issue by Didier97180** [centreon/centreon-plugins#4993]
Good morning

On my Centreon the /var/lib/centreon-broker partition is almost full.
I would like to know how to clean this partition, which file I can delete, and comment?

Thank you

**Comment by omercier** [comment]
Hi,
This is not a plugin issue, so I'm closing the issue, but here are the most likely reasons:
- If the FS is full on a poller, your probably cannot connect to the central server's broker daemon. Read this for troubleshooting: https://thewatch.centreon.com/troubleshooting-41/my-poller-is-down-112
- If the FS is full on your central, one of the broker outputs in Configuration > Pollers > Broker is not configured properly or the peer it tries to connect to is down. See how the files in /var/lib/centreon-broker are named to get a hint on what's wrong. You can use the same link as above to troubleshoot or post a new topic in https://thewatch.centreon.com/data-collection-6 to get more help.

Regards
