### ISSUE TITLE
netapp with mode aggregatestate

### ISSUE THREAD

**Issue by sderivry** [centreon/centreon-plugins#500]
Hello
I try to use this command and I have a strange return
 ./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin  --host=10.22.3.135  --snmp-community=netapp_Read   --snmp-version=2 --mode aggregatestate

CRITICAL: Aggregate 'aggrBkp01' Status : 'raid_dp, 64-bit, rlw_on' - Aggregate 'aggr0' Status : 'raid_dp, 64-bit, rlw_on' |

but when I do snmpwalk in status is online

[root@frparsumon01p plugins]# snmpwalk -v 2c -c netapp_Read 10.22.3.135 .1.3.6.1.4.1.789.1.5.11.1.5
SNMPv2-SMI::enterprises.789.1.5.11.1.5.1 = STRING: "online"
SNMPv2-SMI::enterprises.789.1.5.11.1.5.2 = STRING: "online"
[root@frparsumon01p plugins]# snmpwalk -v 2c -c netapp_Read 10.22.3.135 .1.3.6.1.4.1.789.1.5.11.1.2
SNMPv2-SMI::enterprises.789.1.5.11.1.2.1 = STRING: "aggrBkp01"
SNMPv2-SMI::enterprises.789.1.5.11.1.2.2 = STRING: "aggr0"
[root@frparsumon01p plugins]# snmpwalk -v 2c -c netapp_Read 10.22.3.135 .1.3.6.1.4.1.789.1.5.11.1.6
SNMPv2-SMI::enterprises.789.1.5.11.1.6.1 = STRING: "raid_dp, 64-bit, rlw_on"
SNMPv2-SMI::enterprises.789.1.5.11.1.6.2 = STRING: "raid_dp, 64-bit, rlw_on"

I try also with -threshold-overload='state,CRITICAL,^(?!(online)$)'
5.11.1.6.2 = STRING: "raid_dp, 64-bit, rlw_on"
[root@frparsumon01p plugins]# ./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin  --host=10.22.3.135  --snmp-community=ALE_netapp_Read   --snmp-version=2 --mode aggregatestate  --threshold-overload='state,CRITICAL,^(?!(online)$)'
CRITICAL: Aggregate 'aggrBkp01' Status : 'raid_dp, 64-bit, rlw_on' - Aggregate 'aggr0' Status : 'raid_dp, 64-bit, rlw_on' |

Not better
Why  aggregatestate return critical ?

Best regards

Serge Derivryt

**Comment by Sims24** [comment]
Hi, 

Thanks,
Could you send result of this command with --verbose add like this please : 

./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --host=10.22.3.135 --snmp-community=ALE_netapp_Read --snmp-version=2 --mode aggregatestate --verbose

Thanks

**Comment by sderivry** [comment]
Hi,
Here the status
 ./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin  --host=10.22.3.135  --snmp-community=ALE_netapp_Read   --snmp-version=2 --mode aggregatestate --verbose
CRITICAL: Aggregate 'aggrBkp01' Status : 'raid_dp, 64-bit, rlw_on' - Aggregate 'aggr0' Status : 'raid_dp, 64-bit, rlw_on' |
Aggregate 'aggrBkp01' State : 'online', Status : 'raid_dp, 64-bit, rlw_on'
Aggregate 'aggr0' State : 'online', Status : 'raid_dp, 64-bit, rlw_on'

Regards

**Comment by Sims24** [comment]
Oh missed it ... Try with -threshold-overload='**status**,CRITICAL,^(?!(online)$)' and it should be ok.

**Comment by sderivry** [comment]
./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin  --host=10.22.3.135  --snmp-community=ALE_netapp_Read   --snmp-version=2 --mode aggregatestate --verbose -threshold-overload='status,CRITICAL,^(?!(online)$)'
CRITICAL: Aggregate 'aggrBkp01' Status : 'raid_dp, 64-bit, rlw_on' - Aggregate 'aggr0' Status : 'raid_dp, 64-bit, rlw_on' |
Aggregate 'aggrBkp01' State : 'online', Status : 'raid_dp, 64-bit, rlw_on

not better

**Comment by Sims24** [comment]
--threshold-overload='status,OK,^(?!(rlw_on)$)'

**Comment by sderivry** [comment]
Better
 ./centreon_plugins.pl --plugin=storage::netapp::snmp::plugin  --host=10.22.3.135  --snmp-community=ALE_netapp_Read   --snmp-version=2 --mode aggregatestate --verbose --threshold-overload='status,OK,^(?!(rlw_on)$)'
OK: All aggregates status are ok |
Aggregate 'aggrBkp01' State : 'online', Status : 'raid_dp, 64-bit, rlw_on'
Aggregate 'aggr0' State : 'online', Status : 'raid_dp, 64-bit, rlw_on'

**Comment by garnier-quentin** [comment]
Please use following : --threshold-overload='status,OK,rlw_on'

**Comment by Sims24** [comment]
To explain, code is handling default status like this : 

    state => [
        ['online', 'OK'],
        ['offline', 'CRITICAL'],
    ],
    status => [
        ['normal', 'OK'],
        ['mirrored', 'OK'],
        ['.*', 'CRITICAL'],
    ],

All other value than mirrored  or normal will trigger a warning. Probably need to refactor this code to make it more scalable ... 

Didn't meet this kind of setup before, waht is your netapp version/architecture and is this situation should be considered as usual ?

**Comment by garnier-quentin** [comment]
You should use following (more logic): --threshold-overload='status,OK,rlw_on'

**Comment by sderivry** [comment]
Hello
It is  NetApp Release 8.2.4 7
with the new threshold I have : OK: All aggregates status are ok

So thank for your help

Regards

**Comment by Sims24** [comment]
Thanks for the feedback

**Comment by sderivry** [comment]
Ok I undestand
