### ISSUE TITLE
[database::mssql::plugin] - database-size is not considering autogrowth

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#501]
We are monitoring a very small MS SQL database that has enabled autogrowth unlimited. The plugin show's always a critical state (free space < 0,5%), because is not considering the autogrowth.

autogrowth is enabled
- unlimited
- 1 MB grow

**Comment by garnier-quentin** [comment]
Do you have the MS SQL request for that ?

**Comment by joschi99** [comment]
I know that the following works:
`exec master.dbo.xp_fixeddrives`
If I remember this command is only available to sa.

But probably you can use some alternative like http://tomaslind.net/2014/01/28/alternative-xp_fixeddrives/, could be the better solution maybe.

**Comment by garnier-quentin** [comment]
I hope there is a sql request.

**Comment by joschi99** [comment]
I have tried with following:
```
SELECT DISTINCT
    SUBSTRING(volume_mount_point, 1, 1) AS volume_mount_point
    ,total_bytes/1024/1024 AS total_MB
    ,available_bytes/1024/1024 AS available_MB
FROM
    sys.master_files AS f
CROSS APPLY
    sys.dm_os_volume_stats(f.database_id, f.file_id);


C	81417	54374
```
The output seem's correct.

**Comment by garnier-quentin** [comment]
In your request, i don't see database names.

**Comment by joschi99** [comment]
This is only the SQL statement to get the total and available disk space for **all** available OS disks. This could be used to do this additional check and has to be integrated into the existing statement.

**Comment by garnier-quentin** [comment]
Sorry for the delay. It can be tested now. mssql mode databases-size should be accurate now

**Comment by joschi99** [comment]
Thanks. Have done a quick test on a MSSQL database with autogrowth:

```
./centreon_plugins.pl --plugin=database::mssql::plugin --server=x.x.x.x:1433 --username='username' --password='password' --mode=databases-size --filter-database='MC_726_MIVOR' --ignore-unlimited --warning-datafiles-space-usage-prct=90
WARNING: database 'MC_726_MIVOR' data files space total: 388.12 MB used: 387.38 MB (99.81%) free: 768.00 KB (0.19%) | 'MC_726_MIVOR#datafiles.space.usage.bytes'=406192128B;;;0;406978560 'MC_726_MIVOR#datafiles.space.free.bytes'=786432B;;;0;406978560 'MC_726_MIVOR#datafiles.space.usage.percentage'=99.81%;0:90;;0;100 'MC_726_MIVOR#logfiles.space.usage.bytes'=6054076416B;;;0;6054739968 'MC_726_MIVOR#logfiles.space.free.bytes'=663552B;;;0;6054739968 'MC_726_MIVOR#logfiles.space.usage.percentage'=99.99%;;;0;100
```

As you can see we have a usage about 99,81%, considering free disk space free space should be 98,78%

**Comment by garnier-quentin** [comment]
It's an unlimited autogrowth ?

**Comment by garnier-quentin** [comment]
If it's unlimited autogrowth, i use the current size (because there is no max size). But you can override that size with:
--datafiles-maxsize-unlimited=XXX (x is in MB)

**Comment by garnier-quentin** [comment]
If it's MC_726_MIVOR is unlimited, the ignore is not working. I check!

**Comment by garnier-quentin** [comment]
I have done a fix. Could you test with last version ?

**Comment by joschi99** [comment]
Have done a test with the new fix:
![image](https://user-images.githubusercontent.com/6400595/102976626-251f6e00-4502-11eb-9738-4e77b4acd973.png)

```
 ./centreon_plugins.pl --plugin=database::mssql::plugin --server=x.x.x.x:1433 --username='username' --password='password' --mode=databases-size --filter-database='MC_726_MIVOR' --ignore-unlimited --warning-datafiles-space-usage-prct=90 --datafiles-maxsize-unlimited=10000
OK: database 'MC_726_MIVOR' data files space total: 9.77 GB used: 388.12 MB (3.88%) free: 9.39 GB (96.12%) - log files space total: 5.64 GB used: 5.64 GB (99.99%) free: 808.00 KB (0.01%) | 'MC_726_MIVOR#datafiles.space.usage.bytes'=406978560B;;;0;10485760000 'MC_726_MIVOR#datafiles.space.free.bytes'=10078781440B;;;0;10485760000 'MC_726_MIVOR#datafiles.space.usage.percentage'=3.88%;0:90;;0;100 'MC_726_MIVOR#logfiles.space.usage.bytes'=6059155456B;;;0;6059982848 'MC_726_MIVOR#logfiles.space.free.bytes'=827392B;;;0;6059982848 'MC_726_MIVOR#logfiles.space.usage.percentage'=99.99%;;;0;100
```

--datafiles-maxsize-unlimited will be now considered. But I think we have to consider that the standard on MSSQL databases is "unlimited grow", so it should be difficult to handle this value, because it is depending in case of unlimited grow on remaining diskspace. Do you think that it could possible match database/logfile location with remaining disk space?

**Comment by garnier-quentin** [comment]
I'm not sure i can get Window physical disk space remaining. I don't think mssql can provide me the local disk space remaining. Do you have a request for that ? If yes, i could add an option to add that value.

**Comment by joschi99** [comment]
Yes, I think there are more options for that, please refer to my posts from June 18 2019. For example for the database where I have done the tests I can execute:
```
1> exec master.dbo.xp_fixeddrives;
2> go
drive   MB free
C       31391
E       48081
F       8051
G       34255
(4 rows affected)
(return status = 0)
```

**Comment by joschi99** [comment]
Maybe you can refer to this documentation: https://blog.sqlauthority.com/2013/08/02/sql-server-disk-space-monitoring-detecting-low-disk-space-on-server/

**Comment by garnier-quentin** [comment]
Maybe with that request:
```
SELECT DISTINCT dovs.logical_volume_name AS LogicalName,
dovs.volume_mount_point AS Drive,
CONVERT(INT,dovs.available_bytes/1048576.0) AS FreeSpaceInMB
FROM sys.master_files mf
CROSS APPLY sys.dm_os_volume_stats(mf.database_id, mf.FILE_ID) dovs
ORDER BY FreeSpaceInMB ASC
```

I can check 'physical_name' with 'Drive' to find the disk. And if the file is in autogrowth unlimited, i add the freespace remaining to the size. Seems ok for you ?

**Comment by joschi99** [comment]
Could be a solution. I have done a quick research,` sys.dm_os_volume_stats` is available from SQL 2008 R2 SP1 or later (https://social.msdn.microsoft.com/Forums/sqlserver/en-US/250ee9a5-e851-4449-b279-165fe0ccd600/sysdmosvolumestats-missing-on-2008-r2?forum=sqldataaccess).

On older databases `exec master.dbo.xp_fixeddrives;` is available, if you would like to have a larger support (probably not necessary).

**Comment by joschi99** [comment]
Have done a test with your SQL, returns empty rows. If I try with this seems working:
https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-volume-stats-transact-sql?view=sql-server-ver15 - Example B

```
SELECT database_id, f.file_id, volume_mount_point, total_bytes, available_bytes  
FROM sys.database_files AS f  
CROSS APPLY sys.dm_os_volume_stats(DB_ID(f.name), f.file_id);  
database_id     file_id volume_mount_point      total_bytes     available_bytes
1       1       C:\     74583109632     32886779904
```

**Comment by garnier-quentin** [comment]
Ok. I will use that request. But i need to not add volume available space twice.

**Comment by garnier-quentin** [comment]
Could you test with that branch ?
https://github.com/centreon/centreon-plugins/tree/enh-mssql3

Option is: --add-unlimited-disk

**Comment by joschi99** [comment]
I have done some test. On MSSQL where I can access the system tables I got this error:
`UNKNOWN: Cannot execute query: Server message number=209 severity=16 state=1 line=20 server=SP064LTWHRL text=Ambiguous column name 'file_id'. Server message number=209 severity=16 state=1 line=20 server=SP064LTWHRL text=Ambiguous column name 'file_id'. Server message number=209 severity=16 state=1 line=20 server=SP064LTWHRL text=Ambiguous column name 'file_id'. Server message number=209 severity=16 state=1 line=20 server=SP064LTWHRL text=Ambiguous column name 'file_id'. Server message number=209 severity=16 state=1 line=20 server=SP064LTWHRL text=Ambiguous column name 'file_id'. Server message number=209 severity=16 state=1 line=20 server=SP064LTWHRL text=Ambiguous column name 'file_id'.`

**Comment by garnier-quentin** [comment]
Could you test with last version ?

**Comment by joschi99** [comment]
Now plugins returns empty:
`OK:  |`

without option "--add-unlimited-disk" the output will be:
`OK: database 'MC_726_MIVOR' data files space total: 395.12 MB used: 378.88 MB (95.89%) free: 16.25 MB (4.11%) - log files space total: 6.03 GB used: 6.03 GB (99.96%) free: 2.70 MB (0.04%) | 'MC_726_MIVOR#datafiles.space.usage.bytes'=397279232B;;;0;414318592 'MC_726_MIVOR#datafiles.space.free.bytes'=17039360B;;;0;414318592 'MC_726_MIVOR#datafiles.space.usage.percentage'=95.89%;;;0;100 'MC_726_MIVOR#logfiles.space.usage.bytes'=6473441280B;;;0;6476267520 'MC_726_MIVOR#logfiles.space.free.bytes'=2826240B;;;0;6476267520 'MC_726_MIVOR#logfiles.space.usage.percentage'=99.96%;;;0;100`

**Comment by garnier-quentin** [comment]
Could you add a debug in code line 288 ?
```
foreach my $row (@$result) {
    use Data::Dumper; print Data::Dumper::Dumper($row);
```

**Comment by joschi99** [comment]
```
$VAR1 = [
          'master',
          'master',
          'C:\\Program Files\\Microsoft SQL Server\\MSSQL15.MSSQLSERVER\\MSSQL\\DATA\\master.mdf',
          'data',
          688,
          496,
          '10%',
          -1,
          'C:\\',
          '74583109632',
          '32274280448'
        ];
OK:  |
skipping database master: no matching filter.
```

**Comment by garnier-quentin** [comment]
Only one entry output ? It's weird.

**Comment by garnier-quentin** [comment]
Could you provide the result of the following request:
```
EXEC sp_MSforeachdb 'USE ?
        SELECT
            DB_NAME(),
            [name],    
            physical_name,
            [File_Type] = CASE type   
                WHEN 0 THEN ''data''
                WHEN 1 THEN ''log''
            END,
            [Total_Size] = [size],
            [Used_Space] = (CAST(FILEPROPERTY([name], ''SpaceUsed'') as int)),
            [Growth_Units] = CASE [is_percent_growth]    
                WHEN 1 THEN CAST(growth AS varchar(20)) + ''%''
                ELSE CAST(growth*8/1024 AS varchar(20)) + ''Mb''
            END,
            [max_size]
           , volume_mount_point, total_bytes, available_bytes
          FROM sys.database_files
         CROSS APPLY sys.dm_os_volume_stats(DB_ID(sys.database_files.name), sys.database_files.file_id)'
``

**Comment by joschi99** [comment]
```
        name    physical_name   File_Type       Total_Size      Used_Space      Growth_Units    max_size        volume_mount_point      total_bytes     available_bytes
master  master  C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\master.mdf data    688     496     10%     -1      C:\     74583109632     32287137792
(1 row affected)
        name    physical_name   File_Type       Total_Size      Used_Space      Growth_Units    max_size        volume_mount_point      total_bytes     available_bytes
        name    physical_name   File_Type       Total_Size      Used_Space      Growth_Units    max_size        volume_mount_point      total_bytes     available_bytes
        name    physical_name   File_Type       Total_Size      Used_Space      Growth_Units    max_size        volume_mount_point      total_bytes     available_bytes
        name    physical_name   File_Type       Total_Size      Used_Space      Growth_Units    max_size        volume_mount_point      total_bytes     available_bytes
        name    physical_name   File_Type       Total_Size      Used_Space      Growth_Units    max_size        volume_mount_point      total_bytes     available_bytes
(return status = 0)

```

**Comment by garnier-quentin** [comment]
So that request is not working well:
```
SELECT database_id, f.file_id, volume_mount_point, total_bytes, available_bytes  
FROM sys.database_files AS f  
CROSS APPLY sys.dm_os_volume_stats(DB_ID(f.name), f.file_id);  
```

**Comment by joschi99** [comment]
hmm. It could be a idea to use `exec master.dbo.xp_fixeddrives;` to determine disc space. This command is also available on older MS SQL databases and works fine. What do you think about it?

**Comment by garnier-quentin** [comment]
Maybe we'll use that yes.

**Comment by garnier-quentin** [comment]
Could test with that archive ? https://github.com/centreon/centreon-plugins/archive/enh-mssql4.zip
