### ISSUE TITLE
Monitoring Power Levels of Interfaces (Rx and Tx values in Dbm)

### ISSUE THREAD

**Issue by VidushaZ** [centreon/centreon-plugins#5017]
Hi I have a requirement to monitor Power Levels of Interfaces (Rx and Tx values in Dbm) 
Is there any way to do this? I could not find a proper OID to get these values

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I need more context on your request, particularly on the equipment on which you want to monitor interfaces. If we do not have a plugin dedicated to the equipment you are talking about we will probably not be able to answer the question of OIDs allowing to obtain the desired metrics.
Moreover, the github issues of the centreon-plugins repo mainly aim to resolve bugs encountered with Centreon plugins.

**Comment by lucie-dubrunfaut** [comment]
I'm closing this exit in the absence of a reply
