### ISSUE TITLE
New Plugin: Check database Cassandra

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#502]
Hi,

It is possible to create a plugin to check cassandra databases?

regards

**Comment by garnier-quentin** [comment]
It's yes. I should put a vote system somewhere :)

**Comment by cmeschin** [comment]
Good idea.
i'll vote many times :)

**Comment by garnier-quentin** [comment]
I need NoSQL examples how to monitor it.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
