### ISSUE TITLE
(New Plugin) DHCP plugin leased + IP pool % free

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#503]
Hello team,

Is it possible to get a plugin to monitor DHCP server:
- leases
- IP free by Pools 

https://exchange.nagios.org/directory/Plugins/Network-Protocols/DHCP-and-BOOTP/check_dhcp_all_pools-2Esh/details

https://exchange.nagios.org/directory/Plugins/Network-Protocols/DHCP-and-BOOTP/check_dhcpd_leases-2Epy-%28Advanced-Nagios-Plugins-Collection%29/details

Thanks a lot guys!

**Comment by garnier-quentin** [comment]
I need snmpwalk and mibs.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
