### ISSUE TITLE
{New Plugin} Ruckus network equipment

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#505]
Hello team,

Is it possible to create a plugin to monitor Ruckus equipments?
- Wireless AP controller
- Wireless AP

https://support.ruckuswireless.com/documents/156-zoneflex-9-0-mib-files

Thanks in advance.
PS: I'have tried with Cisco plugin... Only Interfaces work.

**Comment by garnier-quentin** [comment]
I need a complete snmpwalk for a controller and an AP.

**Comment by garnier-quentin** [comment]
Still need it.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
