### ISSUE TITLE
Source missing for archi.png

### ISSUE THREAD

**Issue by lyknode** [centreon/centreon-plugins#5099]
Hi,

Files in:

- connectors/vmware/doc/en/images/archi.png
- connectors/vmware/doc/fr/images/archi.png

are binary files.

Those images, as part of the documentation, are covered by the Apache-2.0 license, and must have their corresponding source (as in: preferred source of modification) distributed.

While all images may not have a source (screenshots for instance), those two files look like schemas, usually generated from a source file such as Visio, Draw.io or other diagrams software file.

Could you please provide the source used to generate those images, as well as a mechanism (preferably integrated in the Makefile) to rebuild them or remove them from the repository ?

Best,

**Comment by rchauvel** [comment]
I don't believe the Apache 2 licence implies a distribution of all sources, specially with regards to images. We could however provide those diagram sources: are you intending to make any changes to them? Have you found something wrong in them?

**Comment by lyknode** [comment]
> I don't believe the Apache 2 licence implies a distribution of all sources, specially with regards to images.

I'm no lawyer, but from my understanding, a license placed alongside a project applies to the whole project, unless specified otherwise.

There are examples of project having a global license and either borrowing sources from other projects, including the original license in the source file header or vendoring dependencies and the license file placed in the vendored directory takes priority under relative files and sub-directories.

IMHO, the Apache license is quite clear that any material should be covered:

```
     "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.
```

> We could however provide those diagram sources: are you intending to make any changes to them? Have you found something wrong in them?

I have not found anything wrong with them, nor do I intend to modify them in the near future. Fortunately, rights granted by an open sources license do not need to be justified to be applied ;), and if I had the source, I would rebuild them.

**Comment by vuntz** [comment]
From a purely practical perspective: I wouldn't be surprised that we lost access to these "sources": the last change for these files is from June 2013, and it could very well be that nobody has the original files anymore (I'll still ask around). So from that perspective, I can only that I'm sorry that we can't provide the source files for these images (and I see no reason why we wouldn't share that if we still had the sources).

As a sidenote... If I may add (and I'm not a lawyer either): the Apache 2.0 license does not require to share the sources; I encourage you to read the license in more details. But I want to be very explicit that this is not the reason why we're not sharing sources here as it wouldn't match our open source philosophy. As I said above, these files are so old that we probably lost all of the original traces for them.

**Comment by lyknode** [comment]
Thanks for taking the time to respond to this issue. I hope you'll be able to find and publish the source for those files.

Just to clear thing up, the Apache-2.0 license **do** requires you to publish sources. Otherwise you actively prevent users from fulfilling item 2 (shorten to highlight relevant parts):

```
2. Grant of Copyright License. [...] each Contributor hereby grants
to You a [...] copyright license to [...] distribute the Work [...] in Source [...] form.
```

And item 4:

```
4. Redistribution. You may [...] distribute [...] in Source [...] form [...]
```

Of the license.

Moreover, the Apache-2.0 license is approved by the [OSI](https://opensource.org/licenses), which has a strict [list of criteria inclusion](https://opensource.org/osd) (adapted from Debian [DFSG](https://wiki.debian.org/DebianFreeSoftwareGuidelines)), the second of it being :

```
2. Source Code
The program must include source code, and must allow
distribution in source code as well as compiled form. ...
```

You might be confusing the fact that the Apache-2.0 license is permissive and as such you can license derivative work under a proprietary license which doesn't require you to disclose sources. But even in this case, you would still be bind by the original license and would have to distribute the sources of the original work (but not your modifications).

Another possible source of confusion is that open sources licenses doesn't require you make the source publicly available, only to those you distribute the binary form to. That obviously overlaps when the project is distributed publicly.

I also found 2 stackoverflow threads stating that Apache-2.0 license doesn't require you to disclose your sources. I'm not sure why they make such a claim but that's not how open source licensing work.

If you need further convincing, you can ask specialized list such as the FSF or Debian legal, but I'm quite certain they would give you the same key points.

Best,
