### ISSUE TITLE
plugin=storage::netapp::snmp::plugin monitor deduplication state

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#511]
Hello,

we encounter a situation on our netapp where deduplication wasn't running anymore because of somes errors.

Adding a check on the "Last Operation State" which should be Success, would be very interesting, if this report something else, then we should trigger an alert to investigate.

According to netapp MIB we should look : 

```
sisLastOpError                  OBJECT-TYPE
SYNTAX                          DisplayString
    MAX-ACCESS                      read-only
    STATUS                          current
DESCRIPTION
            "The error that the last SIS operation
             encountered if it failed."
```

This MIB is per volume : 

SNMPv2-SMI::enterprises.789.1.23.2.1.24.1034 = STRING: "Success"
SNMPv2-SMI::enterprises.789.1.23.2.1.24.1036 = STRING: "Success"
SNMPv2-SMI::enterprises.789.1.23.2.1.24.1038 = STRING: "Success"
SNMPv2-SMI::enterprises.789.1.23.2.1.24.1040 = STRING: "Success"
SNMPv2-SMI::enterprises.789.1.23.2.1.24.1058 = STRING: "Success"

Regards,

**Comment by hdep** [comment]
Hi,

any chance to get this feature ? :)

**Comment by garnier-quentin** [comment]
Could you provide a snmpwalk command result ?
snmpwalk -ObentU -v 2c -c public IP SNMPv2-SMI::enterprises.789 > netapp.snmpwalk

**Comment by hdep** [comment]
Send by e-mail.

**Comment by garnier-quentin** [comment]
Could you test it ?
