### ISSUE TITLE
[apps::backup::veeam::local::plugin] How do --warning-long and --critical-long options work?

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#5122]
Hello. 
Thanks for the useful plugin.

Please tell me how the --warning-long and --critical-long options work. 
It's not very clear from the built-in help for options.
What does the term "long jobs" mean?

>     --warning-long
>             Set warning threshold for long jobs. You can use the following
>             variables: %{display}, %{status}, %{type}, %{elapsed}.
> 
>     --critical-long
>             Set critical threshold for long jobs. You can use the following
>             variables: %{display}, %{status}, %{type}, %{elapsed}.

For example, will I be able to use these options to get alerts for jobs that are in the Running status and have been running for more than 6 hours?

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Looking at the content of the plugin, it seems that these options allow you to add thresholds to the `long` counter, which indicates how long ago a job was started: 
```
sub custom_long_output {
    my ($self, %options) = @_;

    return 'started since: ' . centreon::plugins::misc::change_seconds(value => $self->{result_values}->{elapsed});
}
```

With `elapsed` defined like this: 
```
$elapsed_time = $current_time - $session->{creationTimeUTC} if ($session->{creationTimeUTC} =~ /[0-9]/);
```

So in principle in your example it should work (note that the option seems to take seconds)
