### ISSUE TITLE
storage::emc::clariion::plugin --custommode=clariion --mode=disk

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#513]
Hello,

With the following command, i receive an alert when my server begins to write on a spare disk which is normal. But when the server finish to write on a spare disk the status get back to OK:

![capture_cra 2](https://cloud.githubusercontent.com/assets/13485588/18946281/6ffca9b6-862e-11e6-903c-c04530ad3bc8.png)

Is it possible that the service stays in critical the time that we change the first disk ? Right now the status is normal but we need to change a disk.
 
Command: 
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::emc::clariion::plugin --custommode=clariion --mode=disk --hostname=x.x.x.x --username x --password "xx" --navicli-command naviseccli

**Comment by garnier-quentin** [comment]
What is the status when it goes back to ok ?

**Comment by garnier-quentin** [comment]
You can use --warning-status and --critical-status option.

**Comment by garnier-quentin** [comment]
No response. You can re-open it if you have more information.
