### ISSUE TITLE
[network::fortinet::fortigate::snmp::plugin] Fortigate 7.6 new OID : BIOS security level

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#5131]
Hi,

Fortigate 7.6 introduce a new OID to check BIOS security level : 
- OID 1.3.6.1.4.1.12356.101.4.1.38
- The value can be: 0, 1 or 2

https://docs.fortinet.com/document/fortigate/7.6.0/new-features/291083/snmp-support-for-bios-security-level
https://docs.fortinet.com/document/fortigate/7.4.0/new-features/249947/enhance-bios-level-signature-and-file-integrity-checking

Proposition:
- If level value is 2 (the most secure) the plugin can return OK
- If level value is 1 (less secure) the plugin can return WARN
- If level value is 0 (not recommended) the plugin can return CRITICAL

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Thanks for this information, we'll discuss the subject and see what we'll do about that.

**Comment by lucie-dubrunfaut** [comment]
As we're dealing with a configuration check and not metrics evolution, we don't think that this enhancement is essential for our
 monitoring plugins. So we don't plan to allocate dev resources to implementing this enhancement. If you need to report this information, we encourage you to use the SNMP collection, which should meet your needs [here's the tutorial](https://thewatch.centreon.com/product-how-to-21/snmp-collection-tutorial-132).
