### ISSUE TITLE
Need a pluggin to monitor NTP probes GALLEON SYSTEMS

### ISSUE THREAD

**Issue by C92-k** [centreon/centreon-plugins#5132]
Hello, 

I'm looking for someone who can make a pluggin for GALLEON SYSYTEMS physical probes (NTP), I'm attaching the MIB files.

Thanks

[galleonmibs.tar.gz](https://github.com/user-attachments/files/16492997/galleonmibs.tar.gz)

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This is a feature request, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
