### ISSUE TITLE
Plugin Jmeter disappear ?

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#5137]
Hi,

I am going to migration all poller to 24.x, and I can not see Jmeter plugin in list of plugin.

I use --plugin=apps::jmeter::plugin with version of github today

is it possible to make this plugin official

Thanks,

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This plugin was made with the old fashion so we need to rework it to make it available as a connector. We may need to test the behaviour of certain commands and their returns. When the time comes, would you be willing to send us some examples to confirm that the plugin works properly?

**Comment by romsworld** [comment]
Hi,
Yes of course.

Thanks

**Comment by lucie-dubrunfaut** [comment]
Hello :)

The December release just published contains an updated version of the jmeter plugin https://github.com/centreon/centreon-plugins/pull/5298. Don't hesitate to give us feedback if you encounter any problems using it.
