### ISSUE TITLE
Problem with uptime and MacOS

### ISSUE THREAD

**Issue by sulian** [centreon/centreon-plugins#515]
Hello, 

@julienmathis told me to post my issue here : 

the ```check_centreon_snmp_uptime``` command seems to do not work correctly with apple system

The command work well without the `-d` parameter (see screenshot), with param `d`, the result is always 0day(s) : 

localhost is centreon
zeus is macos server 10.5.8

![bug_uptime](https://cloud.githubusercontent.com/assets/2016950/19148930/77c27f54-8bbf-11e6-8f1f-98fe86e72c91.jpg)

problem is the same with macos 10.6 and macos server 10.4.11

thanks you

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Centreon CES 3.3 (with CentOS)

**Comment by garnier-quentin** [comment]
The plugin is deprecated. Could you use the new system with --plugin=os::linux::snmp::plugin --mode=uptime ?

**Comment by sulian** [comment]
@garnier-quentin, everything works fine with the new system. `os::linux::snmp::plugin` and `snmp_standard::plugin` are the same plugin ? (I have also Windows servers)

**Comment by garnier-quentin** [comment]
You can use it the same for windows. It will work. BUut you should use nsclient++ for Windows (not snmp).

**Comment by sulian** [comment]
I note for nsclient++, I already use for other requests.

**Comment by sulian** [comment]
I have a small problem with Windows server : 

`check_centreon_snmp_uptime -H my_windows -c blabla -v 2` give 17783546hs approximatly 2 days 14h

`centreon_plugins.pl --plugin=snmp_standard::plugin -- mode=uptime --hostname=my_windows` give 1780952s but 20d 14h !!

In this case, windows server has been rebooted two days ago

**Comment by garnier-quentin** [comment]
Could you try the option: --force-oid='.1.3.6.1.2.1.1.3.0' ?

**Comment by sulian** [comment]
Correct value with `--force-oid='.1.3.6.1.2.1.1.3.0'`

**Comment by garnier-quentin** [comment]
Use it for Windows.

**Comment by sulian** [comment]
Ok,

my Windows Server is 2003, I have tested with Windows 7 without force-iod and I have the correct value.
