### ISSUE TITLE
[hardware::pdu::cyberpower::snmp::plugin] incorrect data output in "load" mode

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [centreon/centreon-plugins#5165]
Hello.

In the plugin "**hardware::pdu::cyberpower::snmp::plugin**" the "**load**" mode incorrectly displays information about the load in watts and there is not enough information about the voltage.

```
# ./centreon_plugins.pl --plugin=hardware::pdu::cyberpower::snmp::plugin --mode=load 
--filter-uom="null" --hostname='10.3.2.100' --snmp-community='it' --snmp-version=1 
--use-new-perfdata --warning-phase-current=14 --critical-phase-current=16

OK: Device 'ATS011' bank '1' current : 1.1 A - phase '1' state: normal, current : 1.1 A, power : 2240 W | 
'ATS011~1#bank.current.ampere'=1.1;;;0; 
'ATS011~1#phase.current.ampere'=1.1;0:14;0:16;0; 
'ATS011~1#phase.power.watt'=2240;;;0;
```

Here we see that the value is 2240W.
Judging by the fact that I see in the plugin code https://github.com/centreon/centreon-plugins/blob/develop/src/hardware/pdu/cyberpower/snmp/mode/load.pm#L233 the value from **ePDU2PhaseStatusPower** is multiplied by 10.
I think this is wrong, because OID .1.3.6.1.4.1.3808.1.1.6.4.4.1.7 (ePDU2PhaseStatusPower) according to the description in the MIB file returns the value in Watts.
And this seems to be true.

![изображение](https://github.com/user-attachments/assets/2daa60bf-649b-4c31-a459-394ff67ae487)
 
Description of the ePDU2PhaseStatusPower parameter in the CPS-MIB: "Indicates the load power, in watts, consumed on the Rack PDU phase being queried"
It turns out that multiplying the result of ePDU2PhaseStatusPower by 10 is an error that needs to be fixed, since the plugin is currently returning incorrect data.

And one more thing. 
It would be nice if the plugin additionally polled the outgoing voltage in volts.
This value can be obtained from OID .1.3.6.1.4.1.3808.1.1.6.4.4.1.6 (**ePDU2PhaseStatusVoltage**)
From CPS-MIB: "Indicates the Voltage, in tenths of Volts, of the Rack PDU phase being queried."
This value is interesting to us, but it should have its own metric, for example ***#phase.voltage.volts**
Please note that the voltage is given in tenths of a volt.

MIB and snmpalk files are attached: [CyberPower-ATS-PDU44005.zip](https://github.com/user-attachments/files/16846878/CyberPower-ATS-PDU44005.zip)

Thanks.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Thanks for this feedback and the data to test it. I created the dev ticket according this request.

**Comment by lucie-dubrunfaut** [comment]
Can you tell me if this could be the result expected ?
```
OK: Device 'ATS011' bank '1' current : 1 A - phase '1' state: normal, current : 1 A, power : 219 W, voltage : 217.8 V | 'ATS011~1#bank.current.ampere'=1A;;;0; 
'ATS011~1#phase.current.ampere'=1A;;;0; 
'ATS011~1#phase.power.watt'=219W;;;0; 
'ATS011~1#phase.voltage.volt'=217.8V;;;0;
```

**Comment by Aleksey-Maksimov** [comment]
Yes, that seems to be true.

**Comment by lucie-dubrunfaut** [comment]
You can test with the fix proposed here : https://github.com/centreon/centreon-plugins/pull/5187

**Comment by lucie-dubrunfaut** [comment]
Delivered with the October release. If the issue persists, feel free to re-open this Issue.

**Comment by Aleksey-Maksimov** [comment]
Thank you. It works.

**Comment by Aleksey-Maksimov** [comment]
I just don't understand why when new plugin releases come out there is no version information in them??

```
/centreon_plugins.pl --version
Global Version: (dev)
```

**Comment by lucie-dubrunfaut** [comment]
Hello :)

So far the plugin versioning system, even if it exists, has not been maintained or used to my knowledge. This could be a suggestion to consider.
