### ISSUE TITLE
New plugin: Cyberoam firewall 

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#517]
Hello team,

Could you please create a plugin to monitor Cyberoam firewall?
Here is the MIB.
It could be fine if we can have CPU, Ram, disk, environment, status, live users, ftp hits, http hits, mail hits,...
[CYBEROAM-MIB.txt](https://github.com/centreon/centreon-plugins/files/516428/CYBEROAM-MIB.txt)

Thanks a lot

**Comment by garnier-quentin** [comment]
Could you give a full snmpwalk please ?

**Comment by matthieu-robin** [comment]
Here is
[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/519361/snmpwalk.txt)
