### ISSUE TITLE
Forcepoint FlexEdge Secure SD-WAN monitoring

### ISSUE THREAD

**Issue by yousunlux** [centreon/centreon-plugins#5175]
Hello,

Is it possible to monitore a Forcepoint FlexEdge Secure SD-WAN monitoring ?
I cannot find the correct section for this type

Thanks
Lux

**Comment by lucie-dubrunfaut** [comment]
Hello,

We don't currently have a plugin to meet your needs. However, I invite you to propose the idea [here] (https://thewatch.centreon.com/ideas) to be taken into account and vote on.
I close this issue as it's more of a feature request, thank you for your understanding.
