### ISSUE TITLE
Plugin apps::vmware::connector::plugin doesn't report hardware issue

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#519]
Hello,

I am using the following command to monitor hardware of my esxi : 

`./centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1  --mode=health-host `

OK: All ESX health checks are ok | 'problems_esx3.vsphere.local'=0;;;0;324 'problems_esx2.vsphere.local'=0;;;0;326 'problems_esx1.vsphere.local'=0;;;0;272

On my esx3 I have one warning condition on a Memory Device. The plugin should have seen this.

**Comment by garnier-quentin** [comment]
The plugin get 'runtime.healthSystemRuntime.hardwareStatusInfo.memoryStatusInfo' from the vcenter. What's weird. There is an error if it's red or yellow.

**Comment by hdep** [comment]
Ok, 

after setting my node in maintenance I got the alarm : 
WARNING: 'esx3.vsphere.local' 2 health issue(s) found

Do no why it didn't update then...

**Comment by garnier-quentin** [comment]
Maybe there is sometimes before vcenter updates.
