### ISSUE TITLE
UNKNOWN: Illegal division by zero at /usr/lib/centreon/plugins//centreon_commvault_commserve_restapi.pl line 1547

### ISSUE THREAD

**Issue by gb-dev-anses** [centreon/centreon-plugins#5194]
* what it your bug about?*

With the service "Storage-Pools" from comvault Rest API plugin pack 
i got this message : 

_UNKNOWN: Illegal division by zero at /usr/lib/centreon/plugins//centreon_commvault_commserve_restapi.pl line 1547_

## How to reproduce

u need to have an active commvault serveur and launch this command : 

_/usr/lib/centreon/plugins//centreon_commvault_commserve_restapi.pl --plugin=apps::backup::commvault::commserve::restapi::plugin --mode=storage-pools --hostname='xx.xx.xx.xx' --api-username='?????' --api-password='????' --port='443' --proto='https' --http-backend=curl --insecure --filter-name='' --warning-status='' --critical-status='%{status} !~ /online/i' --warning-usage='' --critical-usage='' --warning-usage-free='' --critical-usage-free='' --warning-usage-prct='' --critical-usage-prct='' --verbose__

- **Environment**: 
Linux localhost.localdomain 5.14.0-427.31.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 15 14:47:52 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux_

- **Version of the plugin**: 

- **Information about the monitored resource**: 
Comvault version 11.32.54

## Expected result

the Storage-Pools list with maybe somes perf counters ? 

## Actual result
An error 

# Other requests

i try to post to the watch before open a bug here :  
https://thewatch.centreon.com/centreon-it-100-users-54/unknown-illegal-division-by-zero-at-usr-lib-centreon-plugins-centreon-versa-snmp-pl-line-9878-3816?tid=3816

**Comment by lucie-dubrunfaut** [comment]
Hello :)

As @ponchoh  suggested, could you try the solution proposed in the PR https://github.com/centreon/centreon-plugins/pull/5141 to see if it solves your problem?

**Comment by gagzou** [comment]
Hi, fix [#5141](https://github.com/centreon/centreon-plugins/pull/5141 ) is ok for me.
I don't have anymore "UNKNOWN: Illegal division by zero at /usr/lib/centreon/plugins//centreon_commvault_commserve_restapi.pl line 1547" but "OK: All storage pools are ok"
