### ISSUE TITLE
[apps::backup::veeam::local::plugin] - cloud repository not available

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#5197]
Latest plugin version

Discovery and monitoring of Veeam repositories will not consider cloud storages. The PS command will not return any cloud repo. The Veeam PS documentation https://helpcenter.veeam.com/docs/backup/powershell/get-vbrobjectstoragerepository.html?ver=120 describes the cmdlet Get-VBRObjectStorageRepository. Here is an example
![image](https://github.com/user-attachments/assets/5ad6ba65-4bca-49d9-98fd-96f65e070df9)

It should be possibile to add this kind of storages, actually is not complete.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I think this is more of an enhancement request than a bug, so please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on (you can link this github issue in your idea proposition).
Thank you for your understanding.
