### ISSUE TITLE
Netapp cluster mode new OIDs

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#52]
Hello,

I just setup a new Netapp cluster using netapp 8.3 Os.
OIDs has changed the following mode is not working anymore :
- global-status
- FAN
- power supply
- temperature
- share-calls
- PSU
- nvram 

I am currently looking for the new OIDs, trying to alter fan.pm but I got some issues :
nodeEnvFailedFanCount                    snmp.1.3.6.1.4.1.789.1.25.2.1.19.1
nodeEnvFailedFanMessage                  snmp.1.3.6.1.4.1.789.1.25.2.1.20.1

 snmpwalk -Os -v 3 -a sha -A ***** -l authPriv -u comm -x DES -X ****  192.168.1.1 1.3.6.1.4.1.789.1.25.2.1.19
enterprises.789.1.25.2.1.19.110.101.116.97.112.112.45.101.113.45.110.97.115.45.48.49 = INTEGER: 0
enterprises.789.1.25.2.1.19.110.101.116.97.112.112.45.101.113.45.110.97.115.45.48.50 = INTEGER: 0

if I set this OIDs in the plugin  output is still : 
 ./centreon_plugins.pl  --plugin=storage::netapp::plugin --mode=fan --snmp-version=3 --snmp-username=com --hostname=192.168.1.1 --authpassphrase=***** --authprotocol=sha --privpassphrase=***** --privprotocol=DES
UNKNOWN: SNMP GET Request : Cant get a single value.

**Comment by garnier-quentin** [comment]
Thanks. But i don't see the modes :)
Could you attach a snmpwalk of the new OIDs and MIB files please ?

**Comment by hdep** [comment]
Sorry, my post wasn't ready :)
Netapp didn't communicate the exact OIDs yet, some I'm not sure to find everything yet.
But if you need I can send you a full snmpwalk of the equipment.

**Comment by garnier-quentin** [comment]
A full snmpwalk can be useful. Thanks.

**Comment by hdep** [comment]
I'm new on github, it seems that I can't attach text file.
The snmpwalk is too long for the text windows.

Can you send me a private message for this ?

**Comment by garnier-quentin** [comment]
You can send me a email. No problem.

**Comment by garnier-quentin** [comment]
Do you have a netapp 8.3 without cluster mode ? I will be great to have netapp ontap 8.3 mibs also.

**Comment by hdep** [comment]
If I'm not wrong Netapp 8.3 only exist in cluster mode.
I still have a NetApp Release 8.2.3 7-Mode  (plugin is ok on this one).

**Comment by garnier-quentin** [comment]
It's fixed now. Otherwise, share-calls and global-status doesn't work with netapp cluster mode. It's "normal". Netapp had removed the OIDs in following mode. And they don't put it somewhere :(
