### ISSUE TITLE
Modbus support

### ISSUE THREAD

**Issue by sulian** [centreon/centreon-plugins#520]
Hello team

Do you think it's possible to implement Modbus TCP into Centreon like this nagios plugin by @AndreySV : 

https://github.com/AndreySV/check_modbus

**Comment by garnier-quentin** [comment]
Yes it will. But when i don't :)

**Comment by garnier-quentin** [comment]
An example to use it:
```
$ perl centreon_plugins.pl --plugin=apps/protocols/modbus/plugin.pm --mode=numeric-value --tcp-host=10.246.0.198 --config=../modbus.json
OK: Metric 'sum' value is '4171.9' - All metrics are OK | 'sum'=4171.9con;;;;
```

The modbus.json file:
```
{
   "selection":{
      "somemetrics":{
          "address": 10,
          "quantity": 10,
          "display": false
      }
   },
   "virtualcurve":{
      "sum":{
          "unit": "con",
          "aggregation": "avg",
          "custom": "/ 10"
      }
   }
}
```

**Comment by sulian** [comment]
Thanks you 👍

**Comment by kozfelipe** [comment]
@garnier-quentin I tried your example with no success

> [root@OP-CENTREON centreon-plugins]# perl centreon_plugins.pl --plugin=apps/protocols/modbus/plugin.pm --mode=numeric-value --tcp-host=10.67.133.7 --config=../modbus.json
UNKNOWN: Cannot load module 'Device::Modbus::TCP::Client'.
Can't locate Device/Modbus/TCP/Client.pm in @INC (@INC contains: /usr/lib/nagios/plugins/custom/centreon-plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/custom/centreon-plugins/centreon/plugins/misc.pm line 221.

**Comment by Sims24** [comment]
@kozfelipe please install Device/Modbus/TCP/Client.pm library. Also next time open new issue for such questions.

**Comment by kozfelipe** [comment]
for the record:

it worked when I installed perl-Device-Modbus-TCP + perl-Try-Tiny
