### ISSUE TITLE
--plugin=hardware::printers::standard::rfc3805::plugin --mode=markersupply-usage warning/critical PB

### ISSUE THREAD

**Issue by AlexisTEXIER** [centreon/centreon-plugins#521]
Hello,

There is a problem with the way warning and critical value are used with this plugin.
The value of the "markersupply-usage" decrease with time.
So warning and critical should check check if the value is less than, no more than.

**Comment by Sims24** [comment]
Hi @AlexisTEXIER , 

You should use syntax described in monitoring plugins development guidelines. 

If you want to warn below a limit you should use : at the end of the threshold. 

For example, use --critical 10: if you want to trigger a critical if value drop below ten. 

Regards

**Comment by AlexisTEXIER** [comment]
Thanks for that very quick answer.
You should close this issue.

**Comment by Sims24** [comment]
you're welcome!
