### ISSUE TITLE
Cisco SNMP plugin genError

### ISSUE THREAD

**Issue by guillaumechardin** [centreon/centreon-plugins#5211]
Hello,

We have many cisco router managed by our ISP.
ISP authorise SNMP access to those routers.

On some router, when using network::cisco::standard::snmp::plugin it fails with this error 
**UNKNOWN: SNMP Table Request: (genError) A general failure occured**

Using debug and or verbose flag do not give any debug data
--plugin=network::cisco::standard::snmp::plugin  --mode=list-interfaces --hostname=192.168.3.254 --snmp-version=2c --snmp-community='xxxxx' --oid-display=ifAlias --debug
UNKNOWN: SNMP Table Request: (genError) A general failure occured

Using snmpwalk works fine :
#snmpwalk  -c xxxxx-v 2c 192.168.3.254
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (759601760) 87 days, 22:00:17.60
IF-MIB::ifIndex.3 = INTEGER: 3
IF-MIB::ifIndex.4 = INTEGER: 4
IF-MIB::ifIndex.11 = INTEGER: 11
IF-MIB::ifIndex.12 = INTEGER: 12
IF-MIB::ifIndex.13 = INTEGER: 13
IF-MIB::ifIndex.14 = INTEGER: 14
IF-MIB::ifIndex.15 = INTEGER: 15
IF-MIB::ifIndex.16 = INTEGER: 16
[...And so on....]

Centreon plugins are in the last available version : 
centreon-plugin-Network-Cisco-Standard-Snmp-20240909-132610.el9.noarch

How to track source of issue ?
Any idea to fix this ?

Thanks
Guillaume

**Comment by guillaumechardin** [comment]
After some more test, i am able to get some data with centreon plugin. But when i add some options, it fails too  : 

`centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin  --mode=list-interfaces --hostname=192.168.3.254 --snmp-version=2c --snmp-community='****' --oid-display=ifAlias`
UNKNOWN: SNMP Table Request: (genError) A general failure occured

Above, just adding --oid-display=ifAlias crashes script exec.

Without : it runs smoothly :
`#centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin  --mode=list-interfaces --hostname=192.168.3.254 --snmp-version=2c --snmp-community='***'`
List interfaces:
'vni-0/1' [speed = 1000][status = up][id = 11][type = ethernetCsmacd]
'vni-0/1.0' [speed = 1000][status = up][id = 12][type = ethernetCsmacd]
'vni-0/2' [speed = 1000][status = up][id = 13][type = ethernetCsmacd]

**Comment by garnier-quentin** [comment]
The snmp agent must have issued. Try with option ```--snmp-force-getnext```

**Comment by guillaumechardin** [comment]
@garnier-quentin , i already tried --snmp-force-getnext as stated here https://github.com/centreon/centreon-plugins/issues/5211#issuecomment-2396457374

**Comment by garnier-quentin** [comment]
Sorry i didn't see. Try also: ```--subsettable=1 --subsetleef=10```

**Comment by guillaumechardin** [comment]
`centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin  --mode=list-interfaces --hostname=192.168.3.254 --snmp-version=2c --snmp-community='CLIENT' --oid-display=ifAlias  --subsettable=1 --subsetleef=10`
UNKNOWN: SNMP Table Request: (genError) A general failure occured

Same error.
