### ISSUE TITLE
Question Plugin [cisco::snmp::standard] Mode interface

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#522]
Hi,

We have some switchs Cisco 3750 .
we supervise the internet lines and values are very different from those provided by OBS on his router.
Is there a specific configuration of plugin for have the same value or it exist a really justified difference in this case between cisco swiths interface and OBS routers?

The difference can be more than 10Mb or 20Mb...

The command line used is:
/usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=XXXX --snmp-community=XXXX --snmp-version=2c --snmp-timeout=5 --oid-filter=ifName --oid-display=ifDesc --interface='^Gi1/0/1$' --name --warning-in-traffic=80 --warning-out-traffic=80 --critical-in-traffic=90 --critical-out-traffic=90 --speed=80 --add-status --add-traffic --no-skipped-counters --oid-extra-display='ifAlias'

regards,

**Comment by garnier-quentin** [comment]
Hi,

I don't know how they check it. The plugin does an average with the counter. I can help you more.

**Comment by cmeschin** [comment]
Thanks,
I'll try to have more information from OBS.

**Comment by garnier-quentin** [comment]
Do you talk about the rrd graphics ?

**Comment by cmeschin** [comment]
about the method to check on his router (snmp or another...)

**Comment by garnier-quentin** [comment]
You can close re-open it when you have some news about it
