### ISSUE TITLE
Plugin network::cisco::meraki::cloudcontroller::restapi::plugin - Add filter for discovery mode

### ISSUE THREAD

**Issue by Thibaud-OBSSA** [centreon/centreon-plugins#5227]
Hi,
Can you add a filter for the discovery mode for the plugin network::cisco::meraki::cloudcontroller::restapi::plugin .

I would like to filter by model. 

Regards

**Comment by Thibaud-OBSSA** [comment]
Please see, pull request  
#5228

**Comment by lucie-dubrunfaut** [comment]
Hello :)

I'm closing this issue (which was more of a request for enhancement) and I'm saving the ticket for integrating your PR. Thanks again for your contribution :)
