### ISSUE TITLE
centreon-plugins/snmp_standard/mode/storage.pm

### ISSUE THREAD

**Issue by Ivory-59** [centreon/centreon-plugins#523]
Hello World,

i have an issue with this file : 
- _centreon-plugins/snmp_standard/mode/storage.pm__

My Status information in Centreon return this error : 
_Use of uninitialized value in multiplication (*) at /usr/lib/nagios/plugins/centreon-plugins/snmp_standard/mode/storage.pm line 166._

I took the file on this page : 
_https://github.com/centreon/centreon-plugins/blob/master/snmp_standard/mode/storage.pm_
but nothing changed...

How can i solve this issue ?

Regards

**Comment by garnier-quentin** [comment]
Could you give me the snmpwalk result of following OIDs:
.1.3.6.1.2.1.25.2.3.1.4
.1.3.6.1.2.1.25.2.3.1.5
.1.3.6.1.2.1.25.2.3.1.3
.1.3.6.1.2.1.25.3.8.1.2

Thanks

**Comment by Ivory-59** [comment]
Hi @garnier-quentin ,

> snmpwalk -c com -v2c @ip_server_linux .1.3.6.1.2.1.25.2.3.1.4
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.3 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.6 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.7 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.10 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.31 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.35 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.36 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.37 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.38 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.39 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.40 = INTEGER: 4096 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.41 = INTEGER: 4096 Bytes
snmpwalk -c com -v2c @ip_server_linux .1.3.6.1.2.1.25.2.3.1.5
HOST-RESOURCES-MIB::hrStorageSize.1 = INTEGER: 1922096
HOST-RESOURCES-MIB::hrStorageSize.3 = INTEGER: 4015148
HOST-RESOURCES-MIB::hrStorageSize.6 = INTEGER: 1922096
HOST-RESOURCES-MIB::hrStorageSize.7 = INTEGER: 945512
HOST-RESOURCES-MIB::hrStorageSize.10 = INTEGER: 2093052
HOST-RESOURCES-MIB::hrStorageSize.31 = INTEGER: 2420514
HOST-RESOURCES-MIB::hrStorageSize.35 = INTEGER: 335616
HOST-RESOURCES-MIB::hrStorageSize.36 = INTEGER: 7706111
HOST-RESOURCES-MIB::hrStorageSize.37 = INTEGER: 495844
HOST-RESOURCES-MIB::hrStorageSize.38 = INTEGER: 1256352
HOST-RESOURCES-MIB::hrStorageSize.39 = INTEGER: 2546510
HOST-RESOURCES-MIB::hrStorageSize.40 = INTEGER: 5124767
HOST-RESOURCES-MIB::hrStorageSize.41 = INTEGER: 2546510
snmpwalk -c com -v2c @ip_server_linux .1.3.6.1.2.1.25.2.3.1.3
HOST-RESOURCES-MIB::hrStorageDescr.1 = STRING: Physical memory
HOST-RESOURCES-MIB::hrStorageDescr.3 = STRING: Virtual memory
HOST-RESOURCES-MIB::hrStorageDescr.6 = STRING: Memory buffers
HOST-RESOURCES-MIB::hrStorageDescr.7 = STRING: Cached memory
HOST-RESOURCES-MIB::hrStorageDescr.10 = STRING: Swap space
HOST-RESOURCES-MIB::hrStorageDescr.31 = STRING: /
HOST-RESOURCES-MIB::hrStorageDescr.35 = STRING: /dev/shm
HOST-RESOURCES-MIB::hrStorageDescr.36 = STRING: /backup
HOST-RESOURCES-MIB::hrStorageDescr.37 = STRING: /boot
HOST-RESOURCES-MIB::hrStorageDescr.38 = STRING: /home
HOST-RESOURCES-MIB::hrStorageDescr.39 = STRING: /u01
HOST-RESOURCES-MIB::hrStorageDescr.40 = STRING: /u02/donnees/ORA
HOST-RESOURCES-MIB::hrStorageDescr.41 = STRING: /var/log
snmpwalk -c com -v2c @@ip_server_linux .1.3.6.1.2.1.25.3.8.1.2
HOST-RESOURCES-MIB::hrFSMountPoint.1 = STRING: "/"
HOST-RESOURCES-MIB::hrFSMountPoint.5 = STRING: "/dev/shm"
HOST-RESOURCES-MIB::hrFSMountPoint.6 = STRING: "/backup"
HOST-RESOURCES-MIB::hrFSMountPoint.7 = STRING: "/boot"
HOST-RESOURCES-MIB::hrFSMountPoint.8 = STRING: "/home"
HOST-RESOURCES-MIB::hrFSMountPoint.9 = STRING: "/u01"
HOST-RESOURCES-MIB::hrFSMountPoint.10 = STRING: "/u02/donnees/ORA"
HOST-RESOURCES-MIB::hrFSMountPoint.11 = STRING: "/var/log"
>

**Comment by garnier-quentin** [comment]
Maybe you need to remove the cache file.

**Comment by Ivory-59** [comment]
I removed the cache file and that works !

Thanks for your help

**Comment by Ivory-59** [comment]
it's ok but sometimes after one or more check.
This error come back...

**Comment by garnier-quentin** [comment]
Could you show me the cache file when you have the error ? And also snmpwalk.

**Comment by Ivory-59** [comment]
Cache file and snmpwalk in attach file
[storage_issue.txt](https://github.com/centreon/centreon-plugins/files/539113/storage_issue.txt)

**Comment by garnier-quentin** [comment]
I have looked and i see following:
'hrstoragedescr_45' => '/mnt/scripts',

I should protect the script.

**Comment by Ivory-59** [comment]
Hi @garnier-quentin  !

It's a problem for the script to get a path like this : /mnt/scripts ?

How can i solve it ?

**Comment by garnier-quentin** [comment]
It's not a problem. I think it's a temporary mounted directory.

**Comment by garnier-quentin** [comment]
Could you test it now ?

**Comment by Ivory-59** [comment]
Hi,
i just try it and it's ok for all servers ! And for the Fix #523
Thx for your help.
