### ISSUE TITLE
Plugin for Huawei AR1220E 

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#525]
Hi,

Can you please create a plugin for Huawei AR1220E. If you need snmpwalk, let me know, I can send it to you.

**Comment by Sims24** [comment]
Hi @kadrika, 

Please send me a snmpwalk file huaweiAR1220E.snmpwalk created from following command : 

snmpwalk -Cc -v2c -c public -ObentU X.X.X.X .1 > huaweiAR1220E.snmpwalk

Thanks,

**Comment by garnier-quentin** [comment]
Still need mibs and snmpwalk.
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
