### ISSUE TITLE
[apps::protocols::x509::plugin] Display Subject Name in the output

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-plugins#526]
Hi,

We are migrating our checks with centreon plugins, and when we use this module x509 (difference with check_http check certificate expiration), the subject name is not shown in the output.

Is it possible to display it ?

Now : WARNING: Certificate expiration days: 17 - Validity Date: Nov 12 09:13:56 2016 |

Need : WARNING: Certificate expiration for for www.google.fr in days: 17 - Validity Date: Nov 12 09:13:56 2016 |

My command : /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=validity --hostname toto --port 443 --validity-mode=expiration  --warning-date 21: --critical-date 5:

Thanks in advance!

**Comment by garnier-quentin** [comment]
I could. But you can have 100 subject names. It will be unreadable. I can display the first one found?

**Comment by Hellnino18** [comment]
Yes good idea. The principal subject name like check_http do.
