### ISSUE TITLE
[network::f5::bigip::plugin] virtualserver-status - Question

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#527]
Hi,
I want to filter status with the option "--threshold-overload" for green and blue but I don't find the good syntax.
Is it possible to filter two status on same command?
This is the command I use to filter green (same as example):
/usr/lib64/centreon-plugins/centreon_plugins.pl --plugin=network::f5::bigip::plugin --mode=virtualserver-status --hostname=x.x.x.x --snmp-version='2c' --snmp-community='public'  --filter-name='.*' --threshold-overload='vs,CRITICAL,^(?!(green)$)'

I tried with that:
 --threshold-overload='vs,CRITICAL,^(?!(green|blue)$)' => KO
 --threshold-overload='vs,CRITICAL,^(?!(green)$)' --threshold-overload='vs,CRITICAL,^(?!(blue)$)' => KO
  --threshold-overload='vs,CRITICAL,(^(?!(green)$)|^(?!(blue)$))'

thanks for your help :)

**Comment by garnier-quentin** [comment]
I don't really understand. Could you explain me what thresholds you want to change ?

**Comment by cmeschin** [comment]
Hi Quentin,

I want to return "OK" state on "blue" status because our configuration of certain virtualservers stay "blue" at any time.

But I found this configuration to return a similar value:
--threshold-overload='vs,OK,^((blue)$)'

Now, blue status returned on OK state and the others (yellow and red) had returned with own status.
This configuration is good for us.
