### ISSUE TITLE
Aruba AP check by AP name

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#528]
Hi,

Can you please add option/mode to Aruba controller plugin, so that the APs could be checked by name(like it can be done with Cisco controller plugin).
Right now when I use verbose to get the AP list with Aruba plugin I get these lines: 
AP '0.11.134.113.66.225' users : 1
AP '0.11.134.113.67.17' users : 1

But I have no ide to which AP name it is connected to.

Using snmpwalk to get names:
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.1.4.1.3.0.11.134.202.230.225 = STRING: "AP02"
SNMPv2-SMI::enterprises.14823.2.2.1.5.2.1.4.1.3.0.11.134.207.20.46 = STRING: "AP01"

**Comment by garnier-quentin** [comment]
Could you test it please ?

**Comment by kadrika** [comment]
Hi,

Still the same:
./centreon_plugins.pl --plugin=network::aruba::standard::snmp::plugin --hostname=1.2.3.4 --snmp-version=2c --snmp-community=xxx --mode=ap-users --verbose
AP '0.11.134.113.66.225' users : 2
AP '0.11.134.113.67.24' users : 1

**Comment by garnier-quentin** [comment]
I unders

**Comment by garnier-quentin** [comment]
Hi,

I'll need the snmpwalk

**Comment by garnier-quentin** [comment]
Done in a new mode
