### ISSUE TITLE
Add support for Selenium 3

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#529]
Hi,

Selenium 3 is out recently. Could you add support for this version.

Thanks

**Comment by joschi99** [comment]
:+1:

**Comment by garnier-quentin** [comment]
I have looked and it cannot work like RC system.  Need to use following module: https://github.com/gempesaw/Selenium-Remote-Driver

And i can create a skeleton (with the connection system, some steps functions,...).

**Comment by romsworld** [comment]
Hi Quentin,

Maybe you can be inspired by this solution ?
https://github.com/opsdis/check_selenium_docker

Thanks,

**Comment by joschi99** [comment]
Any news about them? The selenium docker works very well and is quit easy to install/maintain, so it should be wonderful to have a integration into centreon plugins

**Comment by garnier-quentin** [comment]
We have checked the playwright solution: https://github.com/teodesian/playwright-perl
It seems better for the future. But maybe we also take a look for selenium 3/4.

**Comment by lucie-dubrunfaut** [comment]
Hello :)

This issue seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding.
