### ISSUE TITLE
Cisco ASA CPU

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#530]
I am trying to monitor Cisco ASA CPU. And the plugin returns incorrect values.

I found this information:
Currently the ASA has two ways to check memory via SNMP. 1.3.6.1.4.1.9.9.48 can be polled and the OIDs under that will dig into each individual memory pool, including DMA and GLOBAL SHARED but all the counters are 32-bit which means that the information contained in them is wrong for some of the modern ASAs that run with more memory. Also, polling some of these OIDs will cause CPU-hogs on the ASA, as per CSCtx43501.

In recent codes, you can poll the CISCO-ENHANCED-MEMPOOL-MIB, 1.3.6.1.4.1.9.9.221, and it will provide overall system memory, but it does so with 64-bit counters as well. This is the only way to get valid memory numbers on platforms with more than 4GB of RAM. Also, polling this MIB has not caused CPU-hogs for the SNMP process.

**Comment by garnier-quentin** [comment]
Thanks for the information. I'll add that. And i'll try to check following OIDs first.

**Comment by garnier-quentin** [comment]
Which OIDs are 64 bits ? Because when i read the mib i see:
* cempMemPoolUsed (gauge32)
* cempMemPoolFree (gauge32)

**Comment by kadrika** [comment]
Hi,

From the documentation i understand that even thou it shows in documentation 32bit, it is actually 64bit.

**Comment by garnier-quentin** [comment]
Could you give me a snmpwalk ?

**Comment by kadrika** [comment]
[root@hkscan1098 ~]# snmpwalk 1.2.3.4 -v2c -c xxx 1.3.6.1.4.1.9.9.221
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.2.2.1 = INTEGER: 2
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.3.2.1 = STRING: "System memory"
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.5.2.1 = INTEGER: 0
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.6.2.1 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.7.2.1 = Gauge32: 979311671
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.8.2.1 = Gauge32: 3315655625
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.17.2.1 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.18.2.1 = Counter64: 979311655
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.19.2.1 = Gauge32: 0
SNMPv2-SMI::enterprises.9.9.221.1.1.1.1.20.2.1 = Counter64: 3315655625

**Comment by garnier-quentin** [comment]
So it looks like 32 bits.

**Comment by garnier-quentin** [comment]
It has be done: https://github.com/centreon/centreon-plugins/issues/1480
