### ISSUE TITLE
snmp_standard uptime add precision

### ISSUE THREAD

**Issue by rsimogaetan** [centreon/centreon-plugins#535]
Hello,

This plugin is missing flexibility on the level of precision of the returned results.

Would it be possible to 
- add the option "--precision=days|hours|minutes|seconds|centiseconds"
- then perform the appropriate computation on the retrieved data in order to return a value corresponding to the level of precision requested

The bellow zip file contains a snippet of perl code that could provide this feature.

[uptime-precision.pl.gz](https://github.com/centreon/centreon-plugins/files/598126/uptime-precision.pl.gz)

Kind regards,
Gaetan SIMO

**Comment by garnier-quentin** [comment]
sysuptime OID gives time in seconds since the server is up. So i can't add 'centiseconds'. With the last version, you have a better display. Is not ok ?

**Comment by rsimogaetan** [comment]
In fact, sysUpTime OID gives time in centiseconds. That is why in your code at different lines 82, 85, and 92, you have a division by 100 to have it in seconds.

The current code in this plugin returns the value only in seconds. This proposition's aims is to be able to provide other possible precisions. 

Here is an example of the value retrieved via snmp directly by a Centreon Poller from a Cisco router.
The returned value is "15874129", which by conversion give "1 day, 20:05:41 and 29 centiseconds".

`-bash-4.1$ snmpwalk -c public -v1 cisco.router.ip.address .1.3.6.1.2.1.1.3.0`
`DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (15874129) 1 day, 20:05:41.29`

**Comment by garnier-quentin** [comment]
Yes indeed. You're right. I think you don't have the last version. Because it's not in seconds now.

**Comment by rsimogaetan** [comment]
Really ? I see from the current code in master branch that version is '1.0', same as the one in our Centreon Poller. And the code also is identical.
Where/how can I retrieve the latest version you are talking about ?

**Comment by rsimogaetan** [comment]
Hello, Any news regarding this subject ?

**Comment by garnier-quentin** [comment]
You can get it in the github.
