### ISSUE TITLE
Exagrid plugin

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-plugins#538]
Hi,

Another plugin I will start to work on is for Exagrid plugin. MIB can be found here:

[ExaGrid_MIB.txt](https://github.com/centreon/centreon-plugins/files/601764/ExaGrid_MIB.txt)

**Comment by rk4an** [comment]
I already begin the plugin here:
https://github.com/rk4an/centreon-plugins/commit/f597dea9a222b07bd7a3dd3d3e173bcff5f06a94 

Here interseting value
[exagrid_output.txt](https://github.com/centreon/centreon-plugins/files/602026/exagrid_output.txt)

**Comment by garnier-quentin** [comment]
Could you test it ?
