### ISSUE TITLE
database::mssql::plugin "instance server" ?

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon-plugins#540]
Hello,

I have some instances in my databases server, but I don't know use the plugin "database::mssql::plugin" on an other instance than the "default instance" (MSSQLSERVER).

for exemple SERVER\INSTANCE1 

Can you help me?

Thanks

**Comment by garnier-quentin** [comment]
If there is multiple instance. Each instance has a specific port no ? So use --port option

**Comment by benoitb21** [comment]
No, I use the same for all instances.
You can use the default instance (MSSQLSERVER) by only the server name (SERVERNAME) when you connect you. And you use an another instance by the server name + instance name (SERVERNAME\INSTANCE1)

**Comment by garnier-quentin** [comment]
How do you do it with tsql ?

**Comment by benoitb21** [comment]
We use " SERVERNAME\INSTANCE " for exemple "server01\application01".

Thanks

**Comment by cgagnaire** [comment]
Hi @benoitb21,
Please use --datasource='Sybase:server=<instancename>' option.
