### ISSUE TITLE
apps::vmware::connector::plugin connection problem

### ISSUE THREAD

**Issue by AlexisTEXIER** [centreon/centreon-plugins#541]
Hello,

I can't connect to vcenter on a CES with the lasts updates installed.
On a CES with earlier version of package, I have no problem.

First VM:
 - centreon-plugins updated
 - ces-plugins-Virtualization-VMWare-client.noarch                 2.2.1-1.el6
 - ces-plugins-Virtualization-VMWare-daemon.noarch             2.2.0-3.el6
 - perl-VMware-vSphere.x86_64                                                 5.1.0-780721.1.el6
=> plugins works well

Second VM:
 - centreon-plugins updated
 - ces-plugins-Virtualization-VMWare-client.noarch                 2.3.0-1.el6
 - ces-plugins-Virtualization-VMWare-daemon.noarch            2.3.0-1.el6
 - perl-VMware-vSphere.x86_64                                                 5.1.0-780721.1.el6
=> plugin result: UNKNOWN: Container connection problem |
and I have an error in /var/log/centreon/centreon_vmware.log:
2016-11-23 09:28:08 - 'xxxxxxxx' Login to VirtualCenter server failed: Server version unavailable at 'https://xxxxxxxx:443/sdk/vimService.wsdl' at /usr/local/share/perl5/VMware/VICommon.pm line 545.

**Comment by garnier-quentin** [comment]
You shouldn't have a problem. Nothing change about that between the 2 versions. What is your command ?

**Comment by AlexisTEXIER** [comment]
Here is an example:
perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=xxxxxxx --mode=tools-vm --verbose

**Comment by garnier-quentin** [comment]
You have two connectors running at the same time ?

**Comment by AlexisTEXIER** [comment]
no, only one configured to connect to multiple servers.

**Comment by garnier-quentin** [comment]
Mmmm. Could you go in file 'centreon/script/centreon_vmware.pm' and uncomment following line ?
```
#$ENV{PERL_NET_HTTPS_SSL_SOCKET_CLASS} = "Net::SSL";
```

Restart the connector and try it

**Comment by AlexisTEXIER** [comment]
With this line uncommented => works well

**Comment by garnier-quentin** [comment]
Ok. Thanks for the feedback
