### ISSUE TITLE
apps::tomcat::web::plugin memory mode and xms/xmx

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon-plugins#543]
Hi,

The memory mode of this plugin seems to calculate the threshold values with the Xms value of the memory allocated for Java.
But if we define a higher Xmx value, I think that these thresholds are not pertinent.

For example : Java is configured with Xms = 512 MB and Xmx = 2 GB. If the Warning threshold is 85%, we are notified when Java is using 440 MB.  But if I understand the memory management in Java, we should be notified at 85% of the Xmx value, not the Xms ?

In the Tomcat Manager, we can see these values  like this : 
Free memory: 244.94 MB Total memory: 495.06 MB Max memory: 1979.75 MB

Am I wrong (I'm not Java expert :-) ) ?

Regards

Norbert

**Comment by garnier-quentin** [comment]
you're right. The max is for when the memory can grow. I can add an option to choose the limit (total or max). By default, maybe 'max' is better.

**Comment by nogomes** [comment]
Hi

It seems logical to me :-) 

And as a workaround, until the plugin will be updated, we can also set higher percentage thresholds :

For example when Xms=128 MB and Xmx=875MB, if I set a warning threshold at 200% there will be an alert at 256 MB.

Norbert

**Comment by garnier-quentin** [comment]
I have following values:
```
<memory free='9573360' total='30474240' max='466288640'/>
```

free value is calculated on total (not max). So i can't use max value.
