### ISSUE TITLE
apps::lotus::snmp::plugin mode server-availability thresholds

### ISSUE THREAD

**Issue by matapala** [centreon/centreon-plugins#545]
Hi,

Is there a way to invert threshold check in this mode ?
- value < critical --> critical state
- critical < value < warning --> warning state
- warning < value --> ok state

Here below is server-availability definition found on ibm knowledge center:

> The current value of the server availability index. The values range from 0 to 100. A value of 0 indicates that there are no resources available on the server. A value of 100 means that the server is completely available.

With the plugin actual behavior, a server with 93 % (almost resource free) will output as critical.

I also tried using negative threshold with no success

Thx.

**Comment by Sims24** [comment]
Hello @matapala ,


Yes there is. All status syntax are described in monitoring plugins development guidelines. 

If you use --warning 10: --critical 5: you will trigger a warning between 10 and 5 and a critical below 5.

**Comment by matapala** [comment]
Hello,

It's working great. I should have RTFM :)

Thx
