### ISSUE TITLE
ENHANCEMENT [snmp::standard] - Mode interface Disco-show

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#546]
Hi,
Is it possible to add "ifalias" on result returned by disco-show.
This option will be very usefull to exclude interfaces connected to personnal computer on somes switch on not really managed by network team.

actually we monitor only ports who have alias described.

Thanks.

**Comment by garnier-quentin** [comment]
You can use '--add-extra-oid' option

**Comment by cmeschin** [comment]
It's ok with `--add-extra-oid='alias,.1.3.6.1.2.1.31.1.1.1.18'`
but not with `--add-extra-oid='alias,ifAlias'` or `--add-extra-oid='alias,"ifAlias"'`.

It's possible to enable "text" in this option or it's too hard?
Thanks

**Comment by garnier-quentin** [comment]
Sorry but i can't. I want to let it open (i don't load MIB files).
