### ISSUE TITLE
ENHANCEMENT - Check Interface with IP Address

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#553]
Is it possible to add interfaces check with IP interface.

Is's possible with this script check_iftraffic64.pl. It use oid  my $snmpIPAdEntIfIndex  = '1.3.6.1.2.1.4.20.1.2';       # Index of interface using hosts IP addr to find IP address of interface.

It's more flexible that interface Name or interface Number.

Thanks a lot,

**Comment by garnier-quentin** [comment]
A quick question: 1 ifindex can have multiple IPs ? Or only one ?

**Comment by romsworld** [comment]
No, only one. I have check after add a secondary IP.
Find extract below :

-bash-4.1$ snmpwalk -v2c -c public 192.168.127.203 1.3.6.1.2.1.4.20
IP-MIB::ipAdEntAddr.10.1.1.2 = IpAddress: 10.1.1.2
IP-MIB::ipAdEntAddr.127.0.0.1 = IpAddress: 127.0.0.1
IP-MIB::ipAdEntAddr.192.168.27.203 = IpAddress: 192.168.27.203
IP-MIB::ipAdEntAddr.192.168.127.203 = IpAddress: 192.168.127.203
IP-MIB::ipAdEntIfIndex.10.1.1.2 = INTEGER: 12
IP-MIB::ipAdEntIfIndex.127.0.0.1 = INTEGER: 1
IP-MIB::ipAdEntIfIndex.192.168.27.203 = INTEGER: 12
IP-MIB::ipAdEntIfIndex.192.168.127.203 = INTEGER: 13
IP-MIB::ipAdEntNetMask.10.1.1.2 = IpAddress: 255.0.0.0
IP-MIB::ipAdEntNetMask.127.0.0.1 = IpAddress: 255.0.0.0
IP-MIB::ipAdEntNetMask.192.168.27.203 = IpAddress: 255.255.255.0
IP-MIB::ipAdEntNetMask.192.168.127.203 = IpAddress: 255.255.255.0
IP-MIB::ipAdEntBcastAddr.10.1.1.2 = INTEGER: 1
IP-MIB::ipAdEntBcastAddr.127.0.0.1 = INTEGER: 1
IP-MIB::ipAdEntBcastAddr.192.168.27.203 = INTEGER: 1
IP-MIB::ipAdEntBcastAddr.192.168.127.203 = INTEGER: 1
IP-MIB::ipAdEntReasmMaxSize.10.1.1.2 = INTEGER: 65535
IP-MIB::ipAdEntReasmMaxSize.127.0.0.1 = INTEGER: 65535
IP-MIB::ipAdEntReasmMaxSize.192.168.27.203 = INTEGER: 65535
IP-MIB::ipAdEntReasmMaxSize.192.168.127.203 = INTEGER: 65535

**Comment by garnier-quentin** [comment]
You can have 2 on the same ifindex:

**IP-MIB::ipAdEntIfIndex.10.1.1.2 = INTEGER: 12**
IP-MIB::ipAdEntIfIndex.127.0.0.1 = INTEGER: 1
**IP-MIB::ipAdEntIfIndex.192.168.27.203 = INTEGER: 12**
IP-MIB::ipAdEntIfIndex.192.168.127.203 = INTEGER: 13

**Comment by romsworld** [comment]
You are right :)

**Comment by garnier-quentin** [comment]
Do you have an example with ipv6 also ?

**Comment by romsworld** [comment]
No sorry,

**Comment by garnier-quentin** [comment]
Add possibility to use for --oid-filter and --oid-display the option: ipAddr
In the display, we display only for matching regexp (not all interfaces) but can be multiple (so we put a coma).
