### ISSUE TITLE
ENHANCEMENT - --free as an argument for storage

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#554]
Hi,

is it possible to put --free as an argument

./centreon_plugins.pl --plugin=os::windows::snmp::plugin --snmp-community=public --snmp-version=2 --mode=storage --free=1 to enable or 0 to disable.

It's more easy to have only 1 template and change the service to invert check.

**Comment by garnier-quentin** [comment]
I understand. But i won't change it. If you use Centreon, you can add some open MACRO

**Comment by garnier-quentin** [comment]
I think about it and maybe i could do something. But it will only work with my getoption library.

**Comment by garnier-quentin** [comment]
I don't think it's a good idea. You can create a macro EXTRAOPTIONS for example with your default option. And you overload it to remove free for example.
