### ISSUE TITLE
Mode=time and Threshold

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#557]
Hi,

I don't understand how to set warning and critical value. I would like critical for 10s time offset

./centreon_plugins.pl --plugin=os::windows::snmp::plugin --snmp-community=public --snmp-version=2 --mode=time --hostname x.x.x.x --warning=5 --critical=10 --timezone=+0100

CRITICAL: Time offset -1 second(s) : 2016-11-30T10:14:09 (+0100) | 'offset'=-1s;0:5;0:10;;

Thanks

**Comment by garnier-quentin** [comment]
Hi,

You can use threshold like that:
```
--warning=-5:5 --critical=-10:10
```
