### ISSUE TITLE
Bug (or error in the doc) in os::linux::snmp::plugin

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon-plugins#558]
Hello,

There is a bug (or error in the doc) here :

 centreon-plugins/snmp_standard/mode/storage.pm

Args talk about "diskpath" 

    --diskpath
            Set the disk path (number expected) ex: 1, 2,... (empty means
            'check all disks path').

    --name  Allows to use disk path name with option --diskpath instead of
            disk path oid index.

But :

$ ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --snmp-community xxxxxxxxxx --snmp-version 2 --hostname 10.70.32.36 --mode storage --name --diskpath "/var/log"                                                                                                                
 Unknown option: diskpath at /usr/lib/nagios/plugins/customs/centreon-plugins_20161130/centreon/plugins/alternative/Getopt.pm line 66.

The right option seems to be "storage"

$ ./centreon_plugins.pl --plugin=os::linux::snmp::plugin --snmp-community xxxxxxxxxxx --snmp-version 2 --hostname 10.70.32.36 --mode storage --name --storage "/var/log"
OK: Storage '/var/log' Total: 17.68 GB Used: 1000.65 MB (5.53%) Free: 16.71 GB (94.47%) | 'used'=1049255936B;;;0;18986369024

Regards.

**Comment by Sims24** [comment]
Hello @BenoitPoulet , 

Probably a doc issue, but can't see where diskpath is defined. Are you up to date with master branch ?

**Comment by BenoitPoulet** [comment]
Hello @Sims24 ,

Yep i'm up2date as you can see in the error line :  centreon-plugins_20161130

The PB is that the "--help" option of the mode "storage" talk about "diskpath" which is not defined anywhere in the code.

Because : that's "storage" that we must use.

**Comment by Sims24** [comment]
There is a mode disk-usage and a mode storage. But when I display help from storage one I can't see the diskpath listed in the help .. 

`./centreon_plugins.pl --plugin os::linux::snmp::plugin --mode storage --help

Plugin Description:
    Check Linux operating systems in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

Output Options:
    --verbose
            Display long output.

    --debug Display also debug messages.

    --filter-perfdata
            Filter perfdata that match the regexp.

    --explode-perfdata-max
            Put max perfdata (if it exist) in a specific perfdata (without
            values: same with '_max' suffix) (Multiple options)

    --change-perfdata
            Change perfdata name (Multiple option) Syntax:
            regexp_matching,regexp_substitute

    --range-perfdata
            Change perfdata range thresholds display: 1 = start value equals
            to '0' is removed, 2 = threshold range is not display.

    --filter-uom
            Filter UOM that match the regexp.

    --opt-exit
            Exit code for an option error, usage (default: unknown).

    --output-xml
            Display output in XML Format.

    --output-json
            Display output in JSON Format.

    --disco-format
            Display discovery arguments (if the mode manages it).

    --disco-show
            Display discovery values (if the mode manages it).

Snmp Options:
    --hostname
            Hostname to query (required).

    --snmp-community
            Read community (defaults to public).

    --snmp-version
            Version: 1 for SNMP v1 (default), 2 for SNMP v2c, 3 for SNMP v3.

    --snmp-port
            Port (default: 161).

    --snmp-timeout
            Timeout in secondes (default: 1) before retries.

    --snmp-retries
            Set the number of retries (default: 5) before failure.

    --maxrepetitions
            Max repetitions value (default: 50) (only for SNMP v2 and v3).

    --subsetleef
            How many oid values per SNMP request (default: 50) (for get_leef
            method. Be cautious whe you set it. Prefer to let the default
            value).

    --snmp-force-getnext
            Use snmp getnext function (even in snmp v2c and v3).

    --snmp-username
            Security name (only for SNMP v3).

    --authpassphrase
            Authentication protocol pass phrase.

    --authprotocol
            Authentication protocol (MD5|SHA)

    --privpassphrase
            Privacy protocol pass phrase

    --privprotocol
            Privacy protocol (DES|AES)

    --contextname
            Context name

    --contextengineid
            Context engine ID

    --securityengineid
            Security engine ID

    --snmp-errors-exit
            Exit code for SNMP Errors (default: unknown)

Retention Options:
    --memcached
            Memcached server to use (only one server).

    --statefile-dir
            Directory for statefile (Default:
            '/var/lib/centreon/centplugins').

    --statefile-suffix
            Add a suffix for the statefile name (Default: '').

    --statefile-concat-cwd
            Concat current working directory with option '--statefile-dir'.
            Useful on Windows when plugin is compiled.

    --statefile-storable
            Use Perl Module 'Storable' (instead Data::Dumper) to store
            datas.

Mode:
    --warning
            Threshold warning.

    --critical
            Threshold critical.

    --units Units of thresholds (Default: '%') ('%', 'B').

    --free  Thresholds are on free space left.

    --storage
            Set the storage (number expected) ex: 1, 2,... (empty means
            'check all storage').

    --name  Allows to use storage name with option --storage instead of
            storage oid index.

    --regexp
            Allows to use regexp to filter storage (with option --name).

    --regexp-isensitive
            Allows to use regexp non case-sensitive (with --regexp).

    --reload-cache-time
            Time in seconds before reloading cache file (default: 180).

    --oid-filter
            Choose OID used to filter storage (default: hrStorageDescr)
            (values: hrStorageDescr, hrFSMountPoint).

    --oid-display
            Choose OID used to display storage (default: hrStorageDescr)
            (values: hrStorageDescr, hrFSMountPoint).

    --display-transform-src
            Regexp src to transform display value. (security risk!!!)

    --display-transform-dst
            Regexp dst to transform display value. (security risk!!!)

    --show-cache
            Display cache storage datas.

    --space-reservation
            Some filesystem has space reserved (like ext4 for root). The
            value is in percent of total (Default: none) (results like 'df'
            command).

    --filter-storage-type
            Filter storage types with a regexp (Default:
            '^(hrStorageFixedDisk|hrStorageNetworkDisk|hrFSBerkeleyFFS)$').
`

**Comment by BenoitPoulet** [comment]
OMG you are right.

I checked my terminal history and i did shit :|

Sorry about the noise and time wasted!

**Comment by Sims24** [comment]
no problem have a nice day
