### ISSUE TITLE
Cisco WLC plugin aapending performance data duplicated

### ISSUE THREAD

**Issue by fmonpelat** [centreon/centreon-plugins#559]
Hi, we have being executing the wlc plugin and the aapending counter is duplicated in the performace data:
`
[root@arp140vlncap centreon-plugins-master]# perl centreon_plugins.pl --plugin=network::cisco::wlc::snmp::plugin --mode=ap-users --hostname=10.54.254.11 --snmp-version=2c --snmp-community=QSM --filter-perfdata="ap|total" 
OK: Total Users : 83, Total Idle Users : 0, Total AaaPending Users : 0, Total Authenticated Users : 0, Total AaaPending Users : 0, Total Powersave Users : 0, Total Disassociated Users : 2, Total ToBeDeleted Users : 0, Total Probing Users : 0, Total Blacklisted Users : 0 - All users by SSID are ok - All users by AP are ok | 'total'=83users;;;0; 'total_idle'=0users;;;0; 'total_aaapending'=0users;;;0; 'total_authenticated'=0users;;;0; 'total_aaapending'=0users;;;0; 'total_powersave'=0users;;;0; 'total_disassociated'=2users;;;0; 'total_tobedeleted'=0users;;;0; 'total_probing'=0users;;;0; 'total_blacklisted'=0users;;;0; 'ap_xxxx'=4users;;;0; 'ap_xxx'=8users;;;0; 'ap_xxx'=17users;;;0; 'ap_xxx'=1users;;;0; 'ap_xxx'=24users;;;0; 'ap_xxxx'=5users;;;0; 'ap_xxxx'=3users;;;0; 'ap_xxx'=8users;;;0; 'ap_xxx'=6users;;;0; 'ap_xxx'=1users;;;0; 'ap_xx'=6users;;;0; 'ap_xxx'=4users;;;0;
`

after seing the plugins pm file:
centreon/common/airespace/snmp/mode/apusers.pm
in the line: 73 there is:
`
        { label => 'total-associated', set => {
                key_values => [ { name => 'total_aaapending' } ],
                output_template => 'Total AaaPending Users : %s',
                perfdatas => [
                    { label => 'total_aaapending', value => 'total_aaapending_absolute', template => '%s', 
                      unit => 'users', min => 0 },
                ],
            }
        },
`
where it should be:
`
        { label => 'total-associated', set => {
                key_values => [ { name => 'total_associated' } ],
                output_template => 'Total Associated Users : %s',
                perfdatas => [
                    { label => 'total-associated', value => 'total_associated_absolute', template => '%s',
                      unit => 'users', min => 0 },
                ],
            }
        },
`
so the output is now:
`
[root@arp140vlncap centreon-plugins-master]# perl centreon_plugins.pl --plugin=network::cisco::wlc::snmp::plugin --mode=ap-users --hostname=10.54.254.11 --snmp-version=2c --snmp-community=QSM --filter-perfdata="ap|total" 
OK: Total Users : 86, Total Idle Users : 0, Total AaaPending Users : 0, Total Authenticated Users : 0, Total Associated Users : 83, Total Powersave Users : 0, Total Disassociated Users : 3, Total ToBeDeleted Users : 0, Total Probing Users : 0, Total Blacklisted Users : 0 - All users by SSID are ok - All users by AP are ok | 'total'=86users;;;0; 'total_idle'=0users;;;0; 'total_aaapending'=0users;;;0; 'total_authenticated'=0users;;;0; 'total-associated'=83users;;;0; 'total_powersave'=0users;;;0; 'total_disassociated'=3users;;;0; 'total_tobedeleted'=0users;;;0; 'total_probing'=0users;;;0; 'total_blacklisted'=0users;;;0; 'ap_xxx'=5users;;;0; 'ap_xxx'=7users;;;0; 'ap_xxx'=16users;;;0; 'ap_xxx'=1users;;;0; 'ap_xxx'=24users;;;0; 'ap_xxx'=5users;;;0; 'ap_xxx'=3users;;;0; 'ap_xxx'=7users;;;0; 'ap_xxx'=6users;;;0; 'ap_xxxx'=1users;;;0; 'ap_xxx'=5users;;;0; 'ap_xxx'=5users;;;0;
`
Thanks,

Facu.

**Comment by garnier-quentin** [comment]
Thanks for the issue!
