### ISSUE TITLE
disk-usage & storage, size perfdata removed

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon-plugins#560]
Hello,

In the old check_centreon_storage we had theses perfdata :
size=37472956416B used=28062466048B;35224579031;36723497287;0;37472956416

In centreon-plugin , the best we can have , with "--explode-perfdata-max" is :
OK: Storage '/' Total: 10.02 GB Used: 6.66 GB (66.50%) Free: 3.36 GB (33.50%) | 'used'=7156154368B;0:8608595968;0:9684670464;0;10760744960 'used_max'=10760744960;;;;

but "used_max" is a very strange name for a disk size. Isn't it ?

Can we get back the "size" perfdata ? 
With this we can track the partition size change over time.

Regards.

**Comment by garnier-quentin** [comment]
Try following option:
```
--explode-perfdata-max='used,size'
```

**Comment by BenoitPoulet** [comment]
Hoooooo...
Thank you ! That is exactly what i was looking for.

I tried so find documentation about this option, and others. But i didn't find anything in the official doc.

There is a place where all theses nices options are explained ?

Regards.

**Comment by garnier-quentin** [comment]
I should add it in the FAQ.

**Comment by BenoitPoulet** [comment]
One last thing "explode-perfdata-max" do not report the perfdata unit :

--explode-perfdata-max='used,size'
OK: Storage '/' Total: 10.02 GB Used: 6.66 GB (66.50%) Free: 3.36 GB (33.50%) | 'used'=7156097024B;0:8608595968;0:9684670464;0;10760744960 'size'=10760744960;;;;

the "size" perfdata has no unit .

**Comment by garnier-quentin** [comment]
I could set the perfdata from used.
