### ISSUE TITLE
ENHANCEMENT - Add number of cpu on output

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#561]
For check cpu windows, 

 --plugin=os::windows::snmp::plugin --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --hostname=$_HOSTINTADM$ --mode=cpu 

Actually : OK: CPU(s) average usage is: 15.00%

I would like : OK: 4 CPU(s) average usage is: 0.00% or equivalent to see number of cpu.

Thanks,

**Comment by garnier-quentin** [comment]
The option --verbose is not enough ?

**Comment by romsworld** [comment]
The goal is to see in centreon on Status Information on monitoring Tab.

**Comment by garnier-quentin** [comment]
I see
