### ISSUE TITLE
Missing perfdata in Centreon when using --change-perfdata

### ISSUE THREAD

**Issue by btassite** [centreon/centreon-plugins#564]
See also https://github.com/centreon/centreon/issues/4747

Centreon Web version: 2.7.7
Centreon Engine version: 1.5.1
Centreon Broker version: 2.11.5
OS: CentOS: 6.8
check_snmp_printer: v3.14159

Initial issue: no graphs created for multiword perfdata because it wasn't escaped, fixed that by escaping $PERFDAT for the CONSUM ALL test in /usr/local/nagios/plugins/check_snmp_printer:

old line:
`PERFDAT="$PERFDAT $MARKER_NAME=$CURRENT_CAPACITY;$WARNING;$CRITICAL;"`

new line:
`PERFDAT="$PERFDAT \'$MARKER_NAME\'=$CURRENT_CAPACITY;$WARNING;$CRITICAL;"`

After this the perfdata markers are enclosed in single quotes and Centreon will build graphs.

Current issue: if I want to change the perfdata output, it works OK in a shell but Centreon eats the perfdata starting with the closing single quote and therefore graphing doesn't work:

```
$ ./centreon_plugins.pl --plugin hardware::printers::standard::rfc3805::plugin --mode markersupply-usage --hostname 1.2.3.4 --warning 15: --critical 10: --change-perfdata 'black,ABCD12E'
 OK: Marker supply usages are ok. | 'ABCD12E'=18.00%;15:;10:;0;100
```

When putting it in a Centreon check:
` $USER1$/centreon_plugins.pl --plugin hardware::printers::standard::rfc3805::plugin --snmp-timeout 3 --mode markersupply-usage --hostname '$HOSTADDRESS$' --warning '$ARG1$': --critical '$ARG2$': --change-perfdata "$ARG3$,$ARG4$"`

```
$ mysql -NB centreon_storage -e "select services.perfdata from services where services.command_line like '%markersupply%';"
'ABCD12E
```

If I change the check to end on "$ARG3$,$ARG4$'", the perfata field will have 'ABCD12E' with a closing singlequote, but the =18.00%;15:;10:;0;100 part will still be missing. If I expliticly put 'black,ABCD12E' in the check instead of "$ARG3$,$ARG4$", again only a single starting quote and no key:value pairs behind it.

**Comment by garnier-quentin** [comment]
Thanks but i don't understand. Could you give the me the complete output when you're doing the perfdata change ?

**Comment by btassite** [comment]
Without --change-perfdata:
`./centreon_plugins.pl --plugin hardware::printers::standard::rfc3805::plugin --mode markersupply-usage --hostname 1.2.3.4 --warning 20: --critical 10:`
`OK: Marker supply usages are ok. | 'black'=99.00%;20:;10:;0;100`

with --change-perfdata "black,ABCD12E" added to the end of the command:
`OK: Marker supply usages are ok. | 'ABCD12E'=99.00%;20:;10:;0;100`

So far so good. Add Centreon check command as described above, and dump perfdata using mysql as described above, the expected result would be:
`'ABCD12E'=99.00%;20:;10:;0;100`

but in reality is:
`'ABCD12E`

So something eats the rest of the perfdata. The plugin's output looks OK in bash, but together with Centreon the result isn't working properly.

**Comment by garnier-quentin** [comment]
It's not a plugin problem. The output is correct. There is no special characters hidden ?

**Comment by btassite** [comment]
We use UTF-8 characters but not in this particular example. But the db is as far as I know UTF-8 aware, we only have some some cosmetic issues in the web interface: e.g. UTF-8 accented characters shown with wrong encoding in Downtimes/Comments, but fine in monitoring view.

As you say the check's output is correct, at least in bash, so one would expect it to be OK in Centreon too, unless its shell environment or escaping somehow mangles the output. I have a feeling the latter is at play here, since the perfdata is cut off exactly on the closing single quote.

**Comment by garnier-quentin** [comment]
I ask because (maybe) broker can have some  problem with no-utf8 special characters.

**Comment by btassite** [comment]
In this case no special characters are involved, the output is as pasted above.

**Comment by garnier-quentin** [comment]
Ok. Try to open it in centreon-broker github.
