### ISSUE TITLE
problem with "--mode inodes"

### ISSUE THREAD

**Issue by ccoupeau** [centreon/centreon-plugins#567]
Hi, 
I get some difficulties to check a folder with the following command : 
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode inodes --hostname myserv --snmp-community mycomm --snmp-version 2 --name /var/spool/clientmqueue --warning-usage 90 --critical-usage 95

Result :

UNKNOWN: SNMP Table Request: Cant get a single value.

Do you have an idea ?

I dont see what's wrong with it ...

Thx for all,

**Comment by garnier-quentin** [comment]
You cannot check one directory. You can check a partition only.

**Comment by ccoupeau** [comment]
I already tried with partition "/var", but same issue :( :
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode inodes --hostname myserv --snmp-community mycomm --snmp-version 2 --name=/var --warning-usage 90 --critical-usage 95
Result : 
UNKNOWN: SNMP Table Request: Cant get a single value.

**Comment by garnier-quentin** [comment]
That's not like that. Try:
```
--diskpath='/var' --name
```

**Comment by ccoupeau** [comment]
Our "/var" is a Logical Volume . Is this anyway OK ?

**Comment by garnier-quentin** [comment]
lvm is like a partition. Should be ok.

**Comment by ccoupeau** [comment]
Don't understand your syntax about "--diskpath='/var' --name" .
Why option "--Name" at the end ?
"--diskpath='/var' --name" instead of " --name=/var" doesnt work actually.
Same error.

**Comment by garnier-quentin** [comment]
Could you launch it like that and give the result:
```
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode inodes --hostname myserv --snmp-community mycomm --snmp-version=2 --verbose
```

**Comment by ccoupeau** [comment]
Command launched:
./centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode inodes --hostname myhost --snmp-community mycomm --snmp-version=2 --verbose

Result :
UNKNOWN: SNMP Table Request: Cant get a single value.

My others checks are OK such as:
Memory / Storages / Load Average / Eth / ping and others ..

**Comment by garnier-quentin** [comment]
have you done that ?
```
Need to enable "includeAllDisks 10%" on snmpd.conf.
```

**Comment by garnier-quentin** [comment]
If it's not ok. You can reopen it.
