### ISSUE TITLE
HTTP requests blocked by modsecurity because of missing header

### ISSUE THREAD

**Issue by geekix** [centreon/centreon-plugins#568]
Hello,

I have a problem when sending HTTP requests to check apache2 server-status. Requests get blocked by modsecurity (apache web application firewall) with the following error message : "Request Missing an Accept Header".

Here is the command I'm using : 
centreon_plugins.pl --plugin=apps::apache::serverstatus::plugin --mode=requests --hostname=XXXXXXXX.domain.lan --urlpath="/server-status/?auto" --port=80 --warning=200 --critical=300 --warning-access=200 --critical-access=300 --timeout=10

I've tried checking the server with the classic nagios "check_http" plugin with this option :  --header="Accept: text/plain, text/html", everything works fine.

Altought, I did not find anything in the centreon-plugins documentation on how to specifiy custom header argument. Any chance I've been missing something? Do you have any alternative solution?

I can provide modsecurity log if needed.

Thanks for you help

**Comment by garnier-quentin** [comment]
There is not the option --header. I can add it also for apache.

**Comment by garnier-quentin** [comment]
Could you test with:
```
 --header="Accept: text/plain, text/html"
```

**Comment by geekix** [comment]
Hello,

It works like a charm, thanks a lot =)

**Comment by garnier-quentin** [comment]
Thanks for your rapid feedback!
