### ISSUE TITLE
Mode storage , label 'size'

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon-plugins#571]
Hi,

Is it possible to add in the perf-data the label "size" ?

I thinks that is a good information in a graph to see the size of the disk.
You can see by a simple view in a graph the free space (see example)
![2016-12-23 09_52_52-centreon - it network monitoring](https://cloud.githubusercontent.com/assets/19145945/21450287/bf8ab3e2-c8f5-11e6-966f-eb69b600014e.jpg)

Me, I add these lines in all storage.pm to display this:
$self->{output}->perfdata_add(label => 'size', unit => 'B',
                                      value => $total_size); 

Thanks

**Comment by benoitb21** [comment]
More, I add these lines in the memory.pm to display the mem size also:
$self->{output}->perfdata_add(label => 'size', unit => 'B',
                                  value => $total_size);

**Comment by garnier-quentin** [comment]
Look that ticket ;)
https://github.com/centreon/centreon-plugins/issues/560

**Comment by benoitb21** [comment]
Thanks, sorry

**Comment by benoitb21** [comment]
Hello, 
Since my migration from 2.7 to 2.8, the "--explode-perfdata-max='used,size'" doesn't work when use "--free".
The perfdata is only "free".

Thanks

**Comment by garnier-quentin** [comment]
Weird because the centreon-plugins is the same. If you see free, you should use: --explode-perfdata-max='free,size'

**Comment by benoitb21** [comment]
Yes, but I want show the "used" and "size" curves.
As the last version.

**Comment by garnier-quentin** [comment]
If you see 'free', you cannot have used. It was by design like the first version of "centreon-plugins".

**Comment by benoitb21** [comment]
I use the "free" option because I haven't the choice to use it to use a thresholds on the free space left.
But I want see "used" and "size" curve in my all storage perfdatas. even if I use a specific thresholds.
I agree that is the the default curve, but with the "-explode-perfdata-max" option, it's dommage if we dont choice the curve that we want.

**Comment by garnier-quentin** [comment]
I agree. But it's not in the roadmap to change that (a really big and complex change).

**Comment by benoitb21** [comment]
So I comment in this lines in the centreon_windows_snmp.pl :\
#if (defined($self->{option_results}->{free})) {
#    $label = 'free';
#    $value_perf = $total_free;
#}

**Comment by garnier-quentin** [comment]
Not enough. Because your threshold in perfdata is wrong. That's the  problem.
