### ISSUE TITLE
[slack] - graph-url: unable to generate slack notification with graph included

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#572]
Centreon Plugins: 20161212
Centreon Web: 2.8.2

I configured the slack channel and it seems working fine, but I have problems to generate to graphs for service problems. The problems seems the authentication on Centreon Web to generate the graphs trough the Token. We tried out exfact the same syntax that you provide in the helpfile for slack notification, but we got the always the error
`UNKNOWN: 500 read timeout`

If we try the graph-url in the browser we received the message
- "invalid token" using username=myuser and token=xxxxxxx
- "invalid username" using username=support and token = xxxxxxx (existing user with valid token - normal autologin is working)

the link is generating the graph if we are logged in without problems

**Comment by garnier-quentin** [comment]
Hi,

Could you give me your command please ? I think it's a little complex. Because it's the slack server that need to connect on your centreon server.

**Comment by joschi99** [comment]
This can be the problem, the server is not published in internet but only on the intranet.

**Comment by garnier-quentin** [comment]
I think that's the problem. The limit of SaaS system.

**Comment by joschi99** [comment]
I agree. Thanks a lot.
