### ISSUE TITLE
 apps::protocols::http::mode::response HTTP proto is missing

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon-plugins#573]
In the file centreon-plugins/apps/protocols/http/mode/response.pm line 42. We have :

"proto:s"       => { name => 'proto' },
instead of
"proto:s"       => { name => 'proto', default => 'http' },

Because in the help file we have :
=item B<--proto>
Specify https if needed (Default: 'http')

We meet the same problem with these arguments :

=item B<--method>
Specify http method used (Default: 'GET')

=item B<--urlpath>
Set path to get webpage (Default: '/')

**Comment by garnier-quentin** [comment]
Is ok. The default value is in http.pm library.
