### ISSUE TITLE
[qnap::snmp::plugin --mode=hardware] Adding disk monitoring support for REXP expansion module

### ISSUE THREAD

**Issue by joachim-diaz** [centreon/centreon-plugins#577]
Hello, 

Unless i'm mistaken, the hardware option is currently only checking status for disks attached to the NAS, not any disk part of an expansion module (REXP) added to this NAS.

OID .1.3.6.1.4.1.24681.1.2.18 allows to check disk info for HDDs located in the REXP in a similar fashion to the OID .1.3.6.1.4.1.24681.1.2.11 currently in use.  Could an option be added to check them ?

Thank you !

**Comment by garnier-quentin** [comment]
Could you give me a full snmpwalk ?

**Comment by joachim-diaz** [comment]
It seems that a full snmpwalk currently crashes the SNMP agent on my QNAP :(  I have however an extract from a sub-OID corresponding to the disk part : 


snmpwalk A.B.C.D -c xxx -v2c iso.3.6.1.4.1.24681.1.2.18.3
iso.3.6.1.4.1.24681.1.2.18.3.1.1.1.0 = INTEGER: 1
iso.3.6.1.4.1.24681.1.2.18.3.1.1.2.0 = INTEGER: 2
iso.3.6.1.4.1.24681.1.2.18.3.1.1.3.0 = INTEGER: 3
iso.3.6.1.4.1.24681.1.2.18.3.1.1.4.0 = INTEGER: 4
iso.3.6.1.4.1.24681.1.2.18.3.1.1.5.0 = INTEGER: 5
iso.3.6.1.4.1.24681.1.2.18.3.1.1.6.0 = INTEGER: 6
iso.3.6.1.4.1.24681.1.2.18.3.1.1.7.0 = INTEGER: 7
iso.3.6.1.4.1.24681.1.2.18.3.1.1.8.0 = INTEGER: 8
iso.3.6.1.4.1.24681.1.2.18.3.1.1.9.0 = INTEGER: 9
iso.3.6.1.4.1.24681.1.2.18.3.1.1.10.0 = INTEGER: 10
iso.3.6.1.4.1.24681.1.2.18.3.1.1.11.0 = INTEGER: 11
iso.3.6.1.4.1.24681.1.2.18.3.1.1.12.0 = INTEGER: 12
iso.3.6.1.4.1.24681.1.2.18.3.1.1.13.0 = INTEGER: 13
iso.3.6.1.4.1.24681.1.2.18.3.1.1.14.0 = INTEGER: 14
iso.3.6.1.4.1.24681.1.2.18.3.1.1.15.0 = INTEGER: 15
iso.3.6.1.4.1.24681.1.2.18.3.1.1.16.0 = INTEGER: 16
iso.3.6.1.4.1.24681.1.2.18.3.1.2.1.0 = STRING: "HDD1"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.2.0 = STRING: "HDD2"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.3.0 = STRING: "HDD3"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.4.0 = STRING: "HDD4"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.5.0 = STRING: "HDD5"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.6.0 = STRING: "HDD6"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.7.0 = STRING: "HDD7"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.8.0 = STRING: "HDD8"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.9.0 = STRING: "HDD9"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.10.0 = STRING: "HDD10"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.11.0 = STRING: "HDD11"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.12.0 = STRING: "HDD12"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.13.0 = STRING: "HDD13"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.14.0 = STRING: "HDD14"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.15.0 = STRING: "HDD15"
iso.3.6.1.4.1.24681.1.2.18.3.1.2.16.0 = STRING: "HDD16"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.1.0 = STRING: "41 C/105 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.2.0 = STRING: "38 C/100 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.3.0 = STRING: "40 C/104 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.4.0 = STRING: "38 C/100 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.5.0 = STRING: "41 C/105 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.6.0 = STRING: "45 C/113 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.7.0 = STRING: "42 C/107 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.8.0 = STRING: "39 C/102 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.9.0 = STRING: "42 C/107 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.10.0 = STRING: "43 C/109 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.11.0 = STRING: "41 C/105 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.12.0 = STRING: "40 C/104 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.13.0 = STRING: "39 C/102 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.14.0 = STRING: "38 C/100 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.15.0 = STRING: "40 C/104 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.3.16.0 = STRING: "38 C/100 F"
iso.3.6.1.4.1.24681.1.2.18.3.1.4.1.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.2.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.3.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.4.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.5.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.6.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.7.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.8.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.9.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.10.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.11.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.12.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.13.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.14.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.15.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.4.16.0 = INTEGER: 0
iso.3.6.1.4.1.24681.1.2.18.3.1.5.1.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.2.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.3.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.4.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.5.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.6.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.7.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.8.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.9.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.10.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.11.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.12.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.13.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.14.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.15.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.5.16.0 = STRING: "ST4000NM0033-9ZM170"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.1.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.2.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.3.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.4.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.5.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.6.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.7.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.8.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.9.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.10.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.11.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.12.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.13.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.14.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.15.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.6.16.0 = STRING: "3.64 TB"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.1.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.2.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.3.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.4.0 = STRING: "Normal"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.5.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.6.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.7.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.8.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.9.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.10.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.11.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.12.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.13.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.14.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.15.0 = STRING: "Good"
iso.3.6.1.4.1.24681.1.2.18.3.1.7.16.0 = STRING: "Good"

**Comment by garnier-quentin** [comment]
It's been a long time. But when i'm looking the mib. Expansion disks are in branch: .1.3.6.1.4.1.24681.1.3.11 (systemHdTableEX)

**Comment by garnier-quentin** [comment]
It should be ok. You can test with last release.
