### ISSUE TITLE
error plugin apps::vmware::connector::plugin

### ISSUE THREAD

**Issue by jerem29800** [centreon/centreon-plugins#578]
Hello,
I want to supervise my esxi, with this plugin (apps::vmware::connector::plugin) 
perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=datastore-vm --vm-hostname='FHISV018_Powerchute' --filter
 
Erreur : UNKNOWN: Cannot get response (timeout received)

**Comment by garnier-quentin** [comment]
Hello,

The centreon-vmware daemon is running ? Do you have something in log file ?

**Comment by jerem29800** [comment]
what do you mean ?
I don't understand how this plugin works

**Comment by garnier-quentin** [comment]
You need to install an run following daemon:
https://github.com/centreon/centreon-vmware

The plugin works with it.

**Comment by jerem29800** [comment]
I installed CES 3.4 => centos/rhel 6 systems 
It's OK ?

I installed following dependency : yum install perl-VMware-vSphere 
after that ?

**Comment by garnier-quentin** [comment]
Please read the doc: https://github.com/centreon/centreon-vmware/blob/master/doc/fr/installation/index.rst

**Comment by jerem29800** [comment]
Do you speak french ?

**Comment by garnier-quentin** [comment]
Why is it revelant ?

**Comment by jerem29800** [comment]
I am french, it will be more easy to chat

**Comment by garnier-quentin** [comment]
Sorry but comments must be in English. You can send an email if you want.
