### ISSUE TITLE
[network::paloalto::snmp::plugin] Mode=sessions - display perfdata inconsistant

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#579]
Hi,
The plugin is functionnal, but the perfdata for active sessions is wrong.
Active treshold must be in percent but the perfdata is in number of sessions.
perfdata returned like this:
/usr/lib64/nagios/plugins/centreon_plugins.pl --plugin=network::paloalto::snmp::plugin --mode=sessions --hostname=X.X.X.X --snmp-version='2c' --snmp-community='XXXXXX' --warning-active=80
OK: Sessions Active : 1.75 %, Active SSL Proxy : 0.00 %, Active TCP : 3586, Active UDP : 964, Active ICMP : 23 | 'active'=**4596;0:80;;0;262136** 'active_ssl_proxy'=0.00%;;;0;100 'active_tcp'=3586;;;0; 'active_udp'=964;;;0; 'active_icmp'=23;;;0;

It possible to convert percents in number of sessions on perfdatas?
regards,

**Comment by garnier-quentin** [comment]
Could you test it please ?

**Comment by cmeschin** [comment]
Hi Quentin,

It's good, but you can truncate somes digits on result ;)
OK: Sessions Active : 4256 (**1.62358470412305 %**),

./centreon_plugins.pl --plugin=network::paloalto::snmp::plugin --mode=sessions --hostname=X.X.X.X --snmp-version='2c' --snmp-community='public' --warning-active=80 --critical-active=90
OK: Sessions Active : 4256 (1.62358470412305 %), Active SSL Proxy : 0.00 %, Active TCP : 3240, Active UDP : 951, Active ICMP : 24 | 'active'=4256;0:209708;0:235922;0;262136 'active_ssl_proxy'=0.00%;;;0;100 'active_tcp'=3240;;;0; 'active_udp'=951;;;0; 'active_icmp'=24;;;0;

**Comment by garnier-quentin** [comment]
I like the accuracy :)
