### ISSUE TITLE
database::mssql::plugin : Can't locate DBD/mssql.pm

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#580]
Hi,

Could you add information about prerequisites

 install_driver(mssql) failed: Can't locate DBD/mssql.pm in @INC 

Thanks

**Comment by garnier-quentin** [comment]
Already in doc: https://github.com/centreon/centreon-plugins/blob/master/docs/fr/user/guide.rst
You can see the table with module needed.

**Comment by romsworld** [comment]
Thanks, but... in documentation, we must install Sybase.

So I have this file after installation /usr/local/lib64/perl5/DBD/Sybase.pm

And script ask Can't locate DBD/mssql.pm. 
So why ? is it a bug?

**Comment by garnier-quentin** [comment]
In fact, you need DBD::Sybase with freetds. Some informations here: http://www.freetds.org/userguide/perl.htm

**Comment by romsworld** [comment]
Ok I understand my problem :)

I must call --datasource with the good name...

I replace --datasource='mssql by --datasource='Sybase.

:)

**Comment by romsworld** [comment]
Perhaps, add in documentation exemple for all database type :

--datasource='Sybase:host=127.0.0.1;port=1437;user=toto;password=toto'

etc
