### ISSUE TITLE
Cisco switch interface check issue

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#581]
Hi,

I noticed today, that if you use Cisco standard plugin, and from there interface mode then the devices ifAlias can not contain pipe ( aka | ).
For example if I have in my interface command --oid-extra-display='ifAlias' and if I check from the device the ifAlias value for that interface I see this:
IF-MIB::ifAlias.10101 = STRING: -> ISP OUTSIDE | Uplink, ISP Juniper 2 Gi 0/1

In frontend I see this in output: OK: Interface 'Gi0/1' [ -> ISP OUTSIDE

Main problem with this is that the the graphs are not drawn and I see in frontend Broker log:
[1484905365] error:   storage: error while parsing perfdata of service (3398, 13173): storage: invalid perfdata format: equal sign not present or misplaced.

**Comment by garnier-quentin** [comment]
Hi,

Yes indeed. Use options display-transform-src and display-transform-dst:
```
--display-transform-src='\|' and --display-transform-dst='_'
```
