### ISSUE TITLE
[network::h3c::snmp::plugin] mode=interfaces 

### ISSUE THREAD

**Issue by maksimatveev** [centreon/centreon-plugins#583]
Hi!

Beginning here https://github.com/centreon/centreon/issues/4909
Gist
Create a check of interface using the centreon-plugins:
`./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=interfaces --snmp-version=2c --snmp-community=public --hostname=172.31.255.13 --interface='^Ten-GigabitEthernet1/0/20$' --name --add-traffic --nagvis-perfdata`
Get the check result:
`OK: Interface 'Ten-GigabitEthernet1/0/20' Traffic In : 2.63Gb/s (26.26%), Traffic Out : 465.80Mb/s (4.66%) | 'in'=**328232525.20**;;;0;1250000000 'out'=58224480.27;;;0;1250000000`
The value obtained different. Those, 2.63Gb/s not equal 328232525.20 and 465.80Mb/s not equal 8224480.27

If remove the option --nagvis-perfdata value is printed correctly:
./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=interfaces --snmp-version=2c --snmp-community=3rerbifverbif --hostname=172.31.255.13 --interface='^Ten-GigabitEthernet1/0/20$' --name --add-traffic
`OK: Interface 'Ten-GigabitEthernet1/0/20' Traffic In : 2.82Gb/s (28.23%), Traffic Out : 559.83Mb/s (5.60%) | 'traffic_in'=2822896471.35b/s;;;0;10000000000 'traffic_out'=559832247.13b/s;;;0;10000000000`

**Comment by garnier-quentin** [comment]
That's beucase with --nagvis-perfdata i divide the perfdata by 8. So it's in bytes (not bits).

**Comment by garnier-quentin** [comment]
Some information here: http://docs.nagvis.org/1.9/en_US/lines_weathermap_style.html
```
Byte rate usage: needs at least two perfdata sets with the labels "in" and "out" with an empty UOM. It uses the current value and the maximum value to calculate the current percentage usage. The current value should be given as byte rate.
```

**Comment by maksimatveev** [comment]
@garnier-quentin there is a way to display the graphs bit rate, thus get support in nagvis?

**Comment by garnier-quentin** [comment]
The nagivs doc tells that it's not in bits. So i follow it :)

**Comment by maksimatveev** [comment]
@garnier-quentin those. you offer to nagvis create separate check with option --nagvis-perfdata ?

**Comment by garnier-quentin** [comment]
I offer to use it with nagvis/icinga/... Not a problem :)

**Comment by maksimatveev** [comment]
@garnier-quentin Quentin, then tell me where in your scripts so that the correct output rate in bits, not bytes?

**Comment by maksimatveev** [comment]
the question is closed https://github.com/centreon/centreon-plugins/issues/584
