### ISSUE TITLE
Wrong Graph on centreon-web

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#584]
Hello,

using the centreon-plugin for monitoring network traffic on different devices, data output seems fine, but centreon graph are wrong. I need to multiply by 8 to have the good graph with good scale.

You can see the screenshot  explaining the issue (in/out  are wrong) : 
https://cozy.ks.ipoc.fr/public/hastebin/FzdEwpJc.png 

Any idea why I have this behaviour ?

**Comment by garnier-quentin** [comment]
What options do you use ? Because it's in bits by default. If you use nagvis perfdata option it's not in bits.

**Comment by hdep** [comment]
Here is the command line : 

`$USER1$/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin  --mode=interfaces --hostname=$HOSTADDRESS$  --snmp-version=$_HOSTSNMPVERSION$ --snmp-username=$_HOSTSNMPCOMMUNITY$ --authpassphrase=$ARG1$ --authprotocol=SHA --privpassphrase=$ARG2$ --privprotocol=AES --name --interface=$ARG3$ --add-traffic --nagvis-perfdata --add-errors`

Yes I am using the nagvis-perfdata thank you for poiting me to the right direction.
So my current perf data is in Bytes. 

Hugo

**Comment by maksimatveev** [comment]
@hdep I too have Quentin asked about it)

**Comment by garnier-quentin** [comment]
You can use VDEF in centreon i think to multiply by 8.

**Comment by maksimatveev** [comment]
@garnier-quentin what is VDEF?

**Comment by hdep** [comment]
This is virtual Metric. I used it but I'm not able to apply this to all device and graph. 
Monitoring => Performance => Metrics 

RPN I use is  : in,8,*

**Comment by maksimatveev** [comment]
@hdep may have a position in the script where the value can be multiplied by 8?

**Comment by maksimatveev** [comment]
@hdep not necessarily my wish to apply to the whole project, I have enough custom solutions
```
if (defined($instance_mode->{option_results}->{nagvis_perfdata})) {
        $self->{result_values}->{traffic_per_seconds} /= 8;
        $self->{result_values}->{speed} /= 8;
```
It seems to have to change here?)

**Comment by hdep** [comment]
You should not use the --nagvis-perfdata  option that is the best way.

**Comment by maksimatveev** [comment]
@hdep Yes, if the correct way:
```
if (defined($instance_mode->{option_results}->{nagvis_perfdata})) {
        $self->{result_values}->{traffic_per_seconds} /= 1;
        $self->{result_values}->{speed} /= 1;
```
then
```
./centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=interfaces --snmp-version=2c --snmp-community=public --hostname=172.31.255.13 --interface='^Ten-GigabitEthernet1/0/20$' --name --add-traffic --nagvis-perfdata
OK: Interface 'Ten-GigabitEthernet1/0/20' Traffic In : 3.25Gb/s (32.54%), Traffic Out : 669.88Mb/s (6.70%) | 'in'=3254006602.87;;;0;10000000000 'out'=669879971.70;;;0;10000000000
```
and it was so
`OK: Interface 'Ten-GigabitEthernet1/0/20' Traffic In : 2.35Gb/s (23.47%), Traffic Out : 502.95Mb/s (5.03%) | 'in'=293339790.25;;;0;1250000000 'out'=62869296.83;;;0;1250000000`

**Comment by emirjonb** [comment]
I did the changes to divide by 1 as suggested above but that mess up with graph on centreon, I think we have to add a measurement unit for the graphs to be build, and nagvis to adapt.
I've done some personalization on another script and get some additional perf. Data as:
`traffic_inx=9028485,6Bits/s;1400000000;1800000000;0;2000000000 traffic_outx=1390807,4Bits/s;1400000000;1800000000;0;2000000000`
In this format the graphs on Centreon and value on Nagvis get satisfied, so nagvis doesn't force to use MBps even it's specified on their requirements. 
How can I achieve same result using this script "./centreon_plugins.pl"; I just need to add units to | 'in' and 'out' as bit/s ?
![nagvis](https://user-images.githubusercontent.com/14164077/37471498-3342a950-286a-11e8-8ef5-3c1415ad1e80.PNG)
![graph](https://user-images.githubusercontent.com/14164077/37471499-337195d0-286a-11e8-9fcb-15e9cf2d6d23.PNG)
