### ISSUE TITLE
NEW PLUGIN - HWGSTE2 

### ISSUE THREAD

**Issue by loic60600** [centreon/centreon-plugins#585]
Hello,

Can you add a new plugin HWGSTE2 ? 

You have already add HWGSTE : hardware::sensors::hwgste::snmp::plugin

I have the OID key table : http://ste2.hwg.cz/snmp_oid.xml

Thanks you !

**Comment by Sims24** [comment]
Hi @loic60600 , 

Yes sure, could you provide us some sample data from your equipment ? 
Like file from this command : 

snmpwalk -Cc -v2c -c SNMPCOMMUNITY -ObentU X.X.X.X .1 > hwstge2.snmpwalk

thx

**Comment by loic60600** [comment]
Hi @Sims24 , 
Thanks for your answer.

I have this result : 

```
.1.3.6.1.2.1.1.1.0 = STRING: STE2
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.21796.4.9
.1.3.6.1.2.1.1.3.0 = 10139000
.1.3.6.1.2.1.1.4.0 = STRING: testtest.fr
.1.3.6.1.2.1.1.5.0 = STRING: Sonde test
.1.3.6.1.2.1.1.6.0 = STRING: Salle test
.1.3.6.1.2.1.1.7.0 = INTEGER: 72
.1.3.6.1.4.1.21796.4.9.1.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.21796.4.9.1.1.1.2 = INTEGER: 2
.1.3.6.1.4.1.21796.4.9.1.1.2.1 = INTEGER: 0
.1.3.6.1.4.1.21796.4.9.1.1.2.2 = INTEGER: 0
.1.3.6.1.4.1.21796.4.9.1.1.3.1 = STRING: "Input 1"
.1.3.6.1.4.1.21796.4.9.1.1.3.2 = STRING: "Input 2"
.1.3.6.1.4.1.21796.4.9.1.1.4.1 = INTEGER: 1
.1.3.6.1.4.1.21796.4.9.1.1.4.2 = INTEGER: 1
.1.3.6.1.4.1.21796.4.9.3.1.1.1 = INTEGER: 25704
.1.3.6.1.4.1.21796.4.9.3.1.1.2 = INTEGER: 28514
.1.3.6.1.4.1.21796.4.9.3.1.2.1 = STRING: "Sensor 25704"
.1.3.6.1.4.1.21796.4.9.3.1.2.2 = STRING: "Sensor 28514"
.1.3.6.1.4.1.21796.4.9.3.1.3.1 = INTEGER: 1
.1.3.6.1.4.1.21796.4.9.3.1.3.2 = INTEGER: 1
.1.3.6.1.4.1.21796.4.9.3.1.4.1 = STRING: "24.0"
.1.3.6.1.4.1.21796.4.9.3.1.4.2 = STRING: "69.5"
.1.3.6.1.4.1.21796.4.9.3.1.5.1 = INTEGER: 240
.1.3.6.1.4.1.21796.4.9.3.1.5.2 = INTEGER: 695
.1.3.6.1.4.1.21796.4.9.3.1.6.1 = STRING: "286864DC080001B"
.1.3.6.1.4.1.21796.4.9.3.1.6.2 = STRING: "26626F13040000A9"
.1.3.6.1.4.1.21796.4.9.3.1.7.1 = INTEGER: 1
.1.3.6.1.4.1.21796.4.9.3.1.7.2 = INTEGER: 4
.1.3.6.1.4.1.21796.4.9.3.1.8.1 = INTEGER: 25704
.1.3.6.1.4.1.21796.4.9.3.1.8.2 = INTEGER: 28514
.1.3.6.1.4.1.21796.4.9.70.1.0 = STRING: "00:0A:54:02:55:1A"
End of MIB
```

**Comment by Sims24** [comment]
Thank you @loic60600 

Could you please also provide mib file located under system tab as specified here http://www.hw-group.com/products/STE2/ste2-wifi-thermometer_en.html . 

Where can I find the MIB file for connecting with my SNMP software?
The STE2.mib file is available at the "System" page. Simply save it and import it into your SNMP software.

That would help to be more accurate, 
thanks

**Comment by loic60600** [comment]
Yes,

I can't upload this file (file type not supported) but you can download from the product demo page : [](http://ste2.hwg.cz/system.xml) or directly here [](http://ste2.hwg.cz/STE2.mib)

If you need, i can upload the file on other platform.

Thanks

**Comment by Sims24** [comment]
send it by mail to sbomm@centreon.com please ;)
