### ISSUE TITLE
Illegal division by zero in EMC Clariion plugin

### ISSUE THREAD

**Issue by GhilesKDH** [centreon/centreon-plugins#586]
hello
i got this error sometimes in EMC Clariion plugins 
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::emc::clariion::plugin --custommode=clariion --mode=disk --hostname=XXXXX --username=csXXXXX --password=XXXXXX
UNKNOWN: Illegal division by zero at /usr/lib/nagios/plugins/centreon/common/emc/navisphere/mode/disk.pm line 85.

Ghiles

**Comment by garnier-quentin** [comment]
You dnon't have the last version from github. Please update it.

**Comment by garnier-quentin** [comment]
Tell me if it don't solve your issue.

**Comment by GhilesKDH** [comment]
hi quentin,
its good, thank you
