### ISSUE TITLE
SNMP with Hyper-V machines

### ISSUE THREAD

**Issue by boscorelly** [centreon/centreon-plugins#587]
Hi,

i have successfully setup Centreon. I can monitor the HV host with snmp (disk, ram, swap, cpu).

I Want to monitor the hosted VMs. But there is not option on the VM to configure snmp and snmp queries are not successfull.
How do you do that ?

Moreover, Microsoft started to deprecate SNMP since Windows 2012 server, and want us to use CIM https://msdn.microsoft.com/en-us/library/aa389234(v=vs.85).aspx

How to deal with that ?
Regards.

**Comment by boscorelly** [comment]
> SNMP
SNMP is deprecated. Instead, use the Common Information Model (CIM), which is supported by the WS-Management web services protocol and implemented as Windows Remote Management.

https://technet.microsoft.com/en-us/library/hh831568(v=ws.11).aspx

**Comment by garnier-quentin** [comment]
You should use nsclient agent for Windows server.

**Comment by boscorelly** [comment]
Thanks.

And to query nsclient agent, can i do it with a plugin inside this repo ? :)

**Comment by garnier-quentin** [comment]
To query nsclient, you need to install check_nrpe from nrpe
