### ISSUE TITLE
[network::citrix::netscaler::mpx8000::plugin] mode=certificates-expire return wrong output

### ISSUE THREAD

**Issue by ATEP0mars0** [centreon/centreon-plugins#588]
Hi,

Mode certificates-expire return the wrong (reverse) output code ; it return 0, OK when remains days are inferior to critical threshold. And 2, Critical when remains days are superior to critical threshold.

Thank You !

**Comment by garnier-quentin** [comment]
What is your command line ?

**Comment by ATEP0mars0** [comment]
# perl centreon_plugins.pl --plugin=network::citrix::netscaler::mpx8000::plugin --mode=certificates-expire  --hostname=XXXXXX  --snmp-community=XXXXXX --snmp-version=v2c --critical=100

CRITICAL: Certificate 'applis.xxxx.cloud': 170 days remaining before expiration



# perl centreon_plugins.pl --plugin=network::citrix::netscaler::mpx8000::plugin --mode=certificates-expire  --hostname=XXXXXX  --snmp-community=XXXXXX --snmp-version=v2c --critical=171

OK: All certificates are ok.

**Comment by garnier-quentin** [comment]
If you want threshold critical if value <. Please use like that: --critical=100:

**Comment by garnier-quentin** [comment]
The doc: https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#how-can-i-set-threshold-critical-if-value--x-
