### ISSUE TITLE
Use of uninitialized value in sprintf at centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.

### ISSUE THREAD

**Issue by tecchnikBA** [centreon/centreon-plugins#589]
Hi,
we just found the centreon-plugins and we are happy with them.
But if we try to check our Storage System, we get this little Error:

 perl centreon_plugins.pl --plugin=storage::dell::compellent::snmp::plugin --mode hardware --hostname=******  --snmp-community=*****
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 56.
OK: All 67 components are ok [2/2 caches, 2/2 controllers, 14/14 controller temperatures, 24/24 disks, 1/1 enclosures, 4/4 enclosure fans, 2/2 enclosure I/O modules, 2/2 enclosure psus, 8/8 enclosure temperatures, 1/1 storage centers, 4/4 servers, 3/3 volumes]. | 'ctrltemp_1.1'=46C;0:;0:;; 'ctrltemp_1.2'=38C;0:;0:;; 'ctrltemp_1.3'=38C;0:;0:;; 'ctrltemp_1.4'=46C;0:;0:;; 'ctrltemp_1.5'=41C;0:;0:;; 'ctrltemp_1.6'=41C;0:;0:;; 'ctrltemp_1.7'=32C;0:;0:;; 'ctrltemp_2.1'=50C;0:;0:;; 'ctrltemp_2.2'=37C;0:;0:;; 'ctrltemp_2.3'=36C;0:;0:;; 'ctrltemp_2.4'=48C;0:;0:;; 'ctrltemp_2.5'=41C;0:;0:;; 'ctrltemp_2.6'=40C;0:;0:;; 'ctrltemp_2.7'=31C;0:;0:;; 'encltemp_1.1'=C;;;; 'encltemp_1.2'=C;;;; 'encltemp_1.3'=C;;;; 'encltemp_1.4'=C;;;; 'encltemp_1.5'=C;;;; 'encltemp_1.6'=C;;;; 'encltemp_1.7'=C;;;; 'encltemp_1.8'=C;;;;

Maybe someone can take a look at this.
best regards
Andreas

**Comment by garnier-quentin** [comment]
Could you give me the snmpwalk of following oid: .1.3.6.1.4.1.674.11000.2000.500.1.2.23.1 ?

**Comment by tecchnikBA** [comment]
I hope this is what you were talking about:

snmpwalk -v 1 -c *** 10.41.***  .1.3.6.1.4.1.674.11000.2000.500.1.2.23.1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.1 = Gauge32: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.2 = Gauge32: 2
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.3 = Gauge32: 3
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.4 = Gauge32: 4
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.5 = Gauge32: 5
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.6 = Gauge32: 6
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.7 = Gauge32: 7
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.2.1.8 = Gauge32: 8
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.1 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.2 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.3 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.4 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.5 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.6 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.7 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.3.1.8 = INTEGER: 1
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.1 = STRING: "Ambient"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.2 = STRING: "Midplane"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.3 = STRING: "Inlet to Power Supply - Back Left"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.4 = STRING: "In Power Supply - Back Left"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.5 = STRING: "Inlet to Power Supply - Back Right"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.6 = STRING: "In Power Supply - Back Right"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.7 = STRING: "Canister Ambient in IOModule - Back Top"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.4.1.8 = STRING: "Canister Ambient in IOModule - Back Bottom"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.1 = STRING: "Empty"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.2 = STRING: "Empty"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.3 = STRING: "Empty"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.4 = STRING: "Empty"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.5 = STRING: "Empty"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.6 = STRING: "Empty"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.7 = STRING: "Empty"
iso.3.6.1.4.1.674.11000.2000.500.1.2.23.1.6.1.8 = STRING: "Empty"

**Comment by tecchnikBA** [comment]
sorry, but looks not good

 perl centreon_plugins.pl --plugin=storage::dell::compellent::snmp::plugin --mode hardware --hostname=compellent  --snmp-community=***
UNKNOWN: Cannot load module 'storage::dell::compellent::snmp::mode::components::encltemp'.
syntax error at /usr/lib/nagios/plugins/centreon-plugins/storage/dell/compellent/snmp/mode/components/encltemp.pm line 58, near ");"
Compilation failed in require at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/misc.pm line 221.

**Comment by garnier-quentin** [comment]
Sorry. should be ok now. i'm a fucking moron

**Comment by tecchnikBA** [comment]
no are u not ;-). Thanks works fine now
