### ISSUE TITLE
[Juniper] interfaces

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#591]
Hello,

New version for Juniper SA : Pulse Secure, LLC,Pulse Connect Secure,PSA-5000,8.2R6 (build 51693)

The mode interfaces and list-interfaces does not work any more : 
interfaces : UNKNOWN: Can't construct cache...
list-interfaces : UNKNOWN: Can't get interfaces...

But interfaces does exist on MIB : 
IF-MIB::ifNumber.0 = INTEGER: 6
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifIndex.2 = INTEGER: 2
IF-MIB::ifIndex.3 = INTEGER: 3
IF-MIB::ifIndex.4 = INTEGER: 4
IF-MIB::ifIndex.5 = INTEGER: 5
IF-MIB::ifIndex.6 = INTEGER: 6
IF-MIB::ifDescr.1 = STRING: lo
IF-MIB::ifDescr.2 = STRING: sit0
IF-MIB::ifDescr.3 = STRING: eth0
IF-MIB::ifDescr.4 = STRING: int0
IF-MIB::ifDescr.5 = STRING: mgt0
IF-MIB::ifDescr.6 = STRING: eth3

What's going wrong ?

Same commands does work on old version of Juniper SA : Juniper Networks,Inc,SA-4500,7.4R13.2 (build 32725).

Thanks.

**Comment by garnier-quentin** [comment]
Please use following options:
```
--oids-display=ifdesc --oid-filter=ifdesc
```

**Comment by ritouret** [comment]
Thanks, it works now !
