### ISSUE TITLE
Centreon - how to add it ?

### ISSUE THREAD

**Issue by ychoucha** [centreon/centreon-plugins#594]
Hello, 
hello i have installed the plugin on my centreon serveur, and look working.
but i have nothing on centreon, no template, no services ??
why ?

how to add it on centreon please ?

**Comment by Sims24** [comment]
Hi @ychoucha , 

What is your centreon version ? Looks like a centreon issue and not plugins. Theses plugins are designed to work with several monitoring solutions, Incinga, Naemon .. but does not provide any centreon object.

In 2.8.x, you need to install centreon-pp-manager and centreon-licence-manager to gain access to basic monitoring packs like Linux, Windows etc .. through administation > extension > plugin pack.

You can if you want create the objects on your own by defining command, service templates and host templates. 

Hope this helps, 
Regards

**Comment by ychoucha** [comment]
Hello, 
 i can using it on command line, but i can see all the plugin on centreon ?

How to add it on centreon ?


i m using the last centreon 3
