### ISSUE TITLE
no graph centreon-plugin.pl

### ISSUE THREAD

**Issue by kpal38** [centreon/centreon-plugins#595]
Hello,
I use centreon-plugin.pl for check traffic interface, but graphic does not appear.
Perfdata is OK.
In commands I use graph template: "Traffic"
I don't understand why I have not graphic...

Thx for help

![sans titre](https://cloud.githubusercontent.com/assets/15361791/22887210/79bc26fe-f201-11e6-80a4-79260eeec39d.png)

**Comment by garnier-quentin** [comment]
Hi,

Could you open it in centreon github ? It's not a centreon-plugins issue. Thanks for your feedback.
