### ISSUE TITLE
Add support for AKCP SensorProbe+ series including Thermal Map Sensor

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#596]
It would be great if you can add checks for AKCP SensorProbe+ including Thermal Map Sensor (http://www.akcp.com/products/sensorprobe-series/sp2-plus/)
[UCD_Utilities_SEC.zip](https://github.com/centreon/centreon-plugins/files/774205/UCD_Utilities_SEC.zip)
[SP2+ Thermal Map Manual.pdf](https://github.com/centreon/centreon-plugins/files/774206/SP2.Thermal.Map.Manual.pdf)

Regards,
Jochen

**Comment by garnier-quentin** [comment]
It's not the same mib than before from akcp ? If not, could get the snmp mib and snmpwalk please ?

**Comment by joschi99** [comment]
You can find the mib file on the first post in the "UCD_Utilities_SEC.zip" and a snmpwalk on this posting.
[akcp-walk.txt](https://github.com/centreon/centreon-plugins/files/795783/akcp-walk.txt)
I'm not shure if the complete mib file from the AKCP SP+ is changed, but for shure the new thermal map sensor is only compatible with the new series SP+.

Let me know if you need something else.

Thanks,
Jochen

**Comment by garnier-quentin** [comment]
What is your thermal map sensor in the snmpwalk file ?

**Comment by joschi99** [comment]
The thermal map sensor can be have up to 4 sensors in one:
* 3 temperature (Temperature Port 1, Temperature Port 1.1, Temperature Port 1.2)
* 1 humidity sensor (Humidity Port 1)

In the snmpwalk we have 1 thermal map sensor with 4 sensors included and 2 water detect sensors. The thermal map sensor is on port 1, on port 2 and port 3 we have the water detect sensors.
```
RFC1155-SMI::enterprises.3854.3.5.1.1.1.0.0.0.0.2 = INTEGER: 2
RFC1155-SMI::enterprises.3854.3.5.1.1.1.0.0.0.0.3 = INTEGER: 3
RFC1155-SMI::enterprises.3854.3.5.1.1.1.0.0.0.0.4 = INTEGER: 4
RFC1155-SMI::enterprises.3854.3.5.1.1.1.0.0.0.0.5 = INTEGER: 5
RFC1155-SMI::enterprises.3854.3.5.1.1.1.0.0.0.1.0 = INTEGER: 256
RFC1155-SMI::enterprises.3854.3.5.1.1.1.0.0.0.2.0 = INTEGER: 512
RFC1155-SMI::enterprises.3854.3.5.1.1.2.0.0.0.0.2 = STRING: "Temperature Port 1"
RFC1155-SMI::enterprises.3854.3.5.1.1.2.0.0.0.0.3 = STRING: "Temperature Port 1.1"
RFC1155-SMI::enterprises.3854.3.5.1.1.2.0.0.0.0.4 = STRING: "Temperature Port 1.2"
RFC1155-SMI::enterprises.3854.3.5.1.1.2.0.0.0.0.5 = STRING: "Humidity Port 1"
RFC1155-SMI::enterprises.3854.3.5.1.1.2.0.0.0.1.0 = STRING: "Water Detector Port 2-Klima links"
RFC1155-SMI::enterprises.3854.3.5.1.1.2.0.0.0.2.0 = STRING: "Water Detector Port 3-Klima rechts"
```

**Comment by joschi99** [comment]
hi @garnier-quentin 
I would like to know if you need maybe other informations about the thermal map sensor. Let me know if you need something.

Regards,
Jochen

**Comment by garnier-quentin** [comment]
Thanks. Only time i need :)

**Comment by garnier-quentin** [comment]
Sorry for late response. But in your mibs, there is nothing about the following branch:
1.3.6.1.4.1.3854.3

Do you have the mib file about that ?

**Comment by joschi99** [comment]
Very strange. In the mean time there was some firmware upgrade. Here you will find the mib file for the latest firmware 1.0.3816

[akcp.mib.txt](https://github.com/centreon/centreon-plugins/files/1547709/akcp.mib.txt)

Here is a actual snmpwalk -c public -v2c 192.168.253.50  1.3.6.1.4
[akcp.txt](https://github.com/centreon/centreon-plugins/files/1547714/akcp.txt)

The SP2+ in this environment has 3 sensors attached:
* 1 x Thermal Map Sensor
* 2 x Water Detector Sensor
![2017-12-11 13_10_31-sp2](https://user-images.githubusercontent.com/6400595/33830786-df49ddd4-de75-11e7-8745-97383b4cd63a.png)

And here you will found the SNMP OID's exported for every sensor from the GUI:
[akcp.zip](https://github.com/centreon/centreon-plugins/files/1547722/akcp.zip)

Jochen

**Comment by garnier-quentin** [comment]
It's ok with your last mib file. Thanks!

**Comment by garnier-quentin** [comment]
Could you test with the last version ? It should work
