### ISSUE TITLE
[network::checkpoint::plugin] connections mode new enhancement

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#599]
Hello,

The max connection number can be set to conf checkpoint but not retrieved via snmp.

Can you add an option to specify the maximum configured connection (like --max - connection = xxx)?
And improve thresholds in percent if this option is set?

So, if "--max-connection = xxx" is not defined, the plugin continues to work as it is today.
If "--max-connection = xxx" is set, the warning and critical thresholds are in percent use. If you prefer in this case, you can change the thresholds as warning-prct and critical-prct to better distinguish the two modes.

Thank you.

**Comment by cgagnaire** [comment]
Hi,
I did not see this issue before opening mine (https://github.com/centreon/centreon-plugins/issues/648).
And from what i saw, the max connection value can be retrieved.

**Comment by garnier-quentin** [comment]
So i close that ticket.
