### ISSUE TITLE
[plugin] EMC DataDomain in SNMP

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#6]
Add a plugin to check EMC DataDomain in SNMP. Need a equipment to test and go forward. What we can add:
- Check 'nvramPCIErrorCount' and 'nvramMemoryErrorCount' ;
- Check disk state: diskPropState
- Check CPU Usage: 'cpu0PercentageBusy', 'cpu1PercentageBusy' ;
- Check filesystem usage ;
- Check RAID Status ;
- Check replication status.

After that, there are many perfs metrics useful.

**Comment by Gilum** [comment]
EMC VNX + DataDomain incoming for test :)

**Comment by garnier-quentin** [comment]
Added replication status. RAID not present since 5 datadomain. CPU not useful
