### ISSUE TITLE
[storage::netapp::snmp::plugin] mode snapmirrorlag - support CDOT

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#601]
Hello,

this mode only works with 7mode (I think).
I am running CDOT 8.3.2 and the MIB are different.

I'm not really sure but for me : 

my $oid_snapmirrorOn = '.1.3.6.1.4.1.789.1.29.1.1.1.2';
my $oid_snapmirrorSrc = '.1.3.6.1.4.1.789.1.29.1.1.2.2';
my $oid_snapmirrorLag = '.1.3.6.1.4.1.789.1.29.1.1.7.2.2'; # hundreth of seconds

But changing those value in the code breaks the plugin : 

UNKNOWN: SNMP Table Request: Cant get a single value. 

I can provide snmpwalk if needed.

**Comment by garnier-quentin** [comment]
I'll need a snmpwalk yes.

**Comment by hdep** [comment]
snmpwalk sent by e-mail.

**Comment by hdep** [comment]
Hi, I'm not sure this is still needed, maybe you already change the code ?
