### ISSUE TITLE
new plugin to plataform nutanix

### ISSUE THREAD

**Issue by gajete** [centreon/centreon-plugins#602]
good afternoon,

In case you are interested, it would be good if you developed plugins for the platform called nutanix (http://nutanixbible.com/). New platform like vmware.

best regards
Alejandro Gajete

**Comment by Sims24** [comment]
Hi @gajete ,

Could you provide NUTANIX-MIB.txt by mail along a snmpwalk from a cluster ? That would help a lot,

Thanks

**Comment by garnier-quentin** [comment]
I have the mibs and walk.
