### ISSUE TITLE
[network::brocade::mode] Problem with license

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-plugins#603]
Hi,

In Brocade plugin there is probably a mistake with license check.
In 'memory' and 'cpu' mode, plugin check if license is present or not
```
if ($result->{$oid_swFwFabricWatchLicense} == 2)
```

But all equipment are not subject to a license.
In this case snmpwalk return '2' and plugin return "Need Fabric Watch License to get information."
```
# snmpwalk -v3 -u USER -l authPriv -a SHA -x AES -X 'PASS' -A 'PASS' IP .1.3.6.1.4.1.1588.2.1.1.1.10.1.0
SNMPv2-SMI::enterprises.1588.2.1.1.1.10.1.0 = INTEGER: 2
```

While return of snmpwalk for 'cpu' and 'memory' works
```
# snmpwalk -v3 -u USER -l authPriv -a SHA -x AES -X 'PASS' -A 'PASS' IP .1.3.6.1.4.1.1588.2.1.1.1.26.1.0
SNMPv2-SMI::enterprises.1588.2.1.1.1.26.1.0 = INTEGER: 7
```
```
# snmpwalk -v3 -u USER -l authPriv -a SHA -x AES -X 'PASS' -A 'PASS' IP .1.3.6.1.4.1.1588.2.1.1.1.26.6.0
SNMPv2-SMI::enterprises.1588.2.1.1.1.26.6.0 = INTEGER: 39
```

Check works if I edit mode 'cpu' and 'memory', and modify line : 
```
if ($result->{$oid_swFwFabricWatchLicense} == 2)
```

Best Regards

**Comment by garnier-quentin** [comment]
Maybe i should look even if it's not licensed. it seems like a bug of the mib.
