### ISSUE TITLE
[apps::protocols::http::plugin --mode=json-content] missing Content-Type header in example

### ISSUE THREAD

**Issue by p3r7** [centreon/centreon-plugins#607]
`$ ./centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=json-content --help`
would output example:
```
Mode:
    Check JSON webservice. Can send the json request with option '--data'.
    Example: centreon_plugins.pl --plugin=apps::protocols::http::plugin
    --mode=json-content --data='/home/user/request.json'
    --hostname='myws.site.com' --urlpath='/get/payment'
    --lookup='$..expiration'
```

If we try to launch a similar command, with the `--data` file containing a JSON string, it would fail miserably.

After inspecting the code, it seems that, by default, the content of the file is expected to be in HTTP POST form format.

To effectively use a JSON string as a payload, one would have to add `--header='Content-Type: application/json'`.

**Comment by garnier-quentin** [comment]
I think it will depends. B ut i add it in the help. Thanks!
