### ISSUE TITLE
APPS::LYNC not in list-plugins

### ISSUE THREAD

**Issue by romnvll** [centreon/centreon-plugins#608]
Hello, 
i want to try the lync supervision plugin, but lync doesn't appear in ./centreon_plugins.pl --list-plugin list.
The folder Lync exist in centreon-plugins/apps

So i try this commande :
./centreon_plugins.pl --plugin apps::lync::2013::mssql::mode::lyncusers --list-mode
UNKNOWN: Can't use an undefined value as a HASH reference at /root/centreon-plugins/centreon/plugins/mode.pm line 45.

thank you

Best regards

**Comment by Sims24** [comment]
Hi, 

You should use mssql plugin 'database::mssql::plugin' with --dyn-mode option. 

e.g : 
`./centreon_plugins.pl --plugin database::mssql::plugin --dyn-mode apps::lync::2013::mssql::mode::lyncusers --help`

Thanks

**Comment by romnvll** [comment]
was not easy !
thank you very much for this help

**Comment by Sims24** [comment]
You're welcome,
Regarding https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#what-does---dyn-mode-option-do- looks like my bad I'll add in modes descriptions that --dyn-mode is necessary for this plugin.

**Comment by romnvll** [comment]
ok, i understand now .
Thank you mister sim
