### ISSUE TITLE
Plugin Oracle/MSSQL - SQL Request

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon-plugins#609]
Hi,

I need a mode to execute a SQL request and return the result with perfdata.

You think it's possible to implement this mode/option in the Oracle/MSSQL plugin and why not in the others databases plugins?
for example : --plugin database::oracle::plugin --mode='sql-request' --request='SELECT SUM(id) FROM table'
Result: SUM(id)=56 | SUM(id)=56;;;;;

Thanks

**Comment by garnier-quentin** [comment]
The mode is on other database plugins no ? The mode is 'sql'.
