### ISSUE TITLE
plugin=apps::protocols::udp::plugin - UNKNOWN: Cannot create socket: Operation not permitted

### ISSUE THREAD

**Issue by nikolaydan** [centreon/centreon-plugins#610]
I created a new check based on apps-protocol-udp plugin : 
Type : X Verification
$USER1$/centreon_plugins.pl --plugin=apps::protocols::udp::plugin --mode=connection --hostname=$HOSTADDRESS$ --port='$_SERVICEPORT$' --timeout='$_SERVICETIMEOUT$'

$USER1$ = /usr/lib/nagios/plugins

Here is service that I created using this check : 
```
/usr/lib/nagios/plugins/centreon_plugins.pl
	--plugin=apps::protocols::udp::plugin
	--mode=connection
	--hostname=XXX.XXX.XXXX
	--port='1194'
	--timeout='3'
```

The status of service is 'UNKNOWN: Cannot create socket: Opération non permise'

I read that we need to execute with root privileges this check. 
But my centreon execute it from 'nagios' user who is not sudoer.
When I go in shell, loggin into nagios I got the same error , it's ok from root : 

> /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::protocols::udp::plugin --mode=connection --hostname='XXX.XXX.XXX' --port=1194
> UNKNOWN: Cannot create socket: Opération non permise
> 

I'm on Centos 7.

**Comment by garnier-quentin** [comment]
You should create a standalone Perl file for that plugin:
https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#can-i-have-one-standalone-perl-file-

And you could set the setuid on the standalone Perl.

**Comment by nikolaydan** [comment]
I successfully complied standalone plugin, called 'centreon_protocol_udp_snmp.pl'
It seems that I have the same trouble.
I tried to chown the file to root:root, Setuid, I have still Permission error.
Here is output of ls -l on file: 

> [root@centreon plugin]# ls -l /usr/lib/nagios/plugins/centreon_protocol_udp.pl
-rwxrwxrwt. 1 root root 192788  9 mars  11:31 /usr/lib/nagios/plugins/centreon_protocol_udp.pl

**Comment by garnier-quentin** [comment]
You should have something like that:
```
-rwsr-sr-t 1 root root
```

**Comment by garnier-quentin** [comment]
Is it ok ?

**Comment by nikolaydan** [comment]
Not Ok, same problem even if I execute it with user being in root group. Only way to execute this Perl script is to add sudo before calling script but Centreon doesn't support it (I mean add sudo in 'Command' settings in WebGui).

**Comment by nikolaydan** [comment]
I foud some information...
Setuid method works only with Perl intereptor < 5.12.0. Here's a quote from Stackoverflow : 

> Many unix systems (probably most modern ones) ignore the suid bit on interpreter scripts, as it opens up too many security holes
However, if you are using perl < 5.12.0, you can run perl scripts with setuid set, and they will run as root. How it works is that when the normal perl interpreter runs, and detects that the file you are trying to execute has the setuid bit set, and it then executes a program called suidperl. Suidperl takes care of elevating the user's privileges, and starting up the perl interpreter in a super-secure mode. suidperl is itself running with setuid root.
...
As of perl 5.12.0, suidperl was dropped. As a result, if you want to run a perl script on perl >= 5.12.0 with setuid set, you would have to write your own C wrapper.


You can close this issue, hope this information will help someone in the future.

**Comment by garnier-quentin** [comment]
There are more security hole in interpreter language... ok :) Thanks for your response.
