### ISSUE TITLE
[apps::tomcat::jmx::plugin] - mode=fd-usage Can't get a single value

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#611]
Hi,

I try to monitor tomcat file-description with this command:
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --mode=fd-usage --url=http://X.X.X.X/jolokia --username=username --password=pass --warning=60 --critical=70
UNKNOWN: JMX Request: Cant get a single value.

I use pp-manager 1.4.1 and pluginpack applications-webservers-tomcat-jmx 	version 2.0
Is it a knwon issue?
regards,

**Comment by garnier-quentin** [comment]
Maybe because your jvm is on Windows ?

**Comment by cmeschin** [comment]
Yes.
![tomcat7](https://cloud.githubusercontent.com/assets/8720203/23755200/ddaabe3c-04df-11e7-998d-188a6589dd3a.png)

**Comment by garnier-quentin** [comment]
So it's by design. You cannot have fd-usage for Windows.

**Comment by cmeschin** [comment]
ok thanks :).

**Comment by killerpapy** [comment]
Hello,

We have the same error on RHEL 7.

![image](https://user-images.githubusercontent.com/11554510/42989582-854c234e-8c00-11e8-9314-64bd8320dc66.png)

Any Idea ?

Thanks.
