### ISSUE TITLE
database::oracle::plugin: add a "password-expiration" mode

### ISSUE THREAD

**Issue by GuillaumeBernard** [centreon/centreon-plugins#613]
Hello,

As a database administrator,
I want Centreon to be able to monitor Oracle database user's password expiration and to warn me a few days before expiration,
I order to be able to change the password before it expires

Currently, we use the SQL mode to run a query on system tables returning the number of users with a password about to expire.
This is not ideal because only the number of users is returned, without the usernames and the time before expiration.
A dedicated mode would be able to get and display more info, for example:
"Warning: user blabla will expire in 4 days; user pouette will expire in 3 days"

Regards,
Guillaume Bernard

**Comment by garnier-quentin** [comment]
Could you give me the sql request ?

**Comment by GuillaumeBernard** [comment]
We use this SQL request:
select count(username) from dba_users where expiry_date is not null and expiry_date < sysdate + 21 and account_status not like '%EXPIRED%'

**Comment by garnier-quentin** [comment]
You can check it like that (less than 21 days):
```
--critical-status='%{expire} < (86400 * 21)'
```
