### ISSUE TITLE
 network::ciscio::standard::snmp::plugin - interface - error when using add-cast

### ISSUE THREAD

**Issue by zemnes** [centreon/centreon-plugins#614]
I keep getting errors when using --add-cast  with the network::ciscio::standard::snmp::plugin with mode interfaces. (snmp_standard::mode::interfaces)

I've deleted the centreon-plugins folder and redownloaded it from git today and delete all items in the cache folder. Both did not fix the issue. 

Below is an example of a command I ran.

` centreon-plugins/centreon_plugins.pl --plugin  network::cisco::standard::snmp::plugin --mode interfaces --hostname hostip --snmp-version 2c --snmp-community thekey --add-traffic --add-errors  --add-status --add-cast`

This causes the below to show up before the normal plugin output and peftdata.

> Use of uninitialized value $value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 160.
> Use of uninitialized value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 200.
> Use of uninitialized value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 200.
> Use of uninitialized value $value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 160.
> Use of uninitialized value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 200.
> Use of uninitialized value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 200.
> Use of uninitialized value $value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 160.
> Use of uninitialized value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 200.
> Use of uninitialized value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 200.
> Use of uninitialized value $value in sprintf at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/values.pm line 160.

Adding --debug only adds the same thing twice. So far I've tested with various cisco switches and a Palo Alto firewall. The issue only started showing up when I added --add-cast. The errors go away once the argument is removed.

**Comment by garnier-quentin** [comment]
Could you give me a snmpwalk for following OIDs (snmp version 2c):
.1.3.6.1.2.1.2.2.1.11
.1.3.6.1.2.1.2.2.1.17
.1.3.6.1.2.1.31.1.1.1

**Comment by zemnes** [comment]
Hello Garnier

I've sent the results as an email. The subject is the same as the issue.

Thank you for looking into this.
