### ISSUE TITLE
Can't get any status from network:cisco:smallbusiness plugin

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-plugins#616]
Hi everyone,
First of all, i'm new to Github, Centos, Centreon and moniroting.

I successfully installed a centreon monitoring server and a base ping service to check host availabitily (servers, swtiches, esx...)
Then i wanted to go further and cpu load, memory... on my differents hosts. Two of them are Cisco SG 300 SmallBusiness switches

When i use the plugin "centreon-plugins/network/cisco/smallbusiness/standard/snmp" with a ssh connection on my server, i got this : 
![image](https://cloud.githubusercontent.com/assets/26572075/24147361/20a5c43a-0e3a-11e7-9d6f-ba8eb96f806d.png)
so it's work cool thanks a lot.

My problem is in Centreon web appliance : with this script working, i created a new check_command
![image](https://cloud.githubusercontent.com/assets/26572075/24147418/619c6cb4-0e3a-11e7-843d-42b308502b36.png)
I added it to a service to check my switches
And here is the result : 
![image](https://cloud.githubusercontent.com/assets/26572075/24147476/adcd2614-0e3a-11e7-950f-316998c61bb8.png)
Still in unknown state, and the "Status Information" column is completly blank

As i said before, i'm new to thoses tools and i'm really sorry if it's just a "dumb mistake" by i to me i should work since when i try it in ssh it's working

**Comment by Sims24** [comment]
Hi @alliria98 , 

Which centreon version are you using actually ?

Could you identify command line executed by the engine ? You can find it in detailed service page if you are using Centreon> 2.8. 

Otherwise go to service configuration page, get the service_id in the url, connect to mysql, perform this query : 
SELECT command_line FROM centreon_storage.services WHERE service_id=XX

And copy/paste the result here.
Thanks

**Comment by alliria98** [comment]
I'm using Centreon 2.8.3
I got the service id, but don't know how to properly log in mysql and perform the query you're asking :(

**Comment by Sims24** [comment]
@alliria98 now worries, through ssh, type `mysql` and then copy/paste the query along the `mysql>` prompt.

Is it ok ?

**Comment by alliria98** [comment]
It seems that i got no result for your query :(
![image](https://cloud.githubusercontent.com/assets/26572075/24150462/1302aa44-0e46-11e7-9493-94994ef4d7ea.png)

**Comment by Sims24** [comment]
@alliria98 my bad, try to add `;` and type enter again ;)

**Comment by alliria98** [comment]
Sorry for that, i really don't know sql :(
Here we go for the result
![image](https://cloud.githubusercontent.com/assets/26572075/24150732/e105e0c8-0e46-11e7-862c-4aa583bad224.png)
It's a "Service by host group" so that's why i got 2 lines i guess
IP are ok, but snmp version and community aren't good and i don't get why because it's correctly done on host configuration.
Should i put directly version and community in my check_command ?

**Comment by Sims24** [comment]
@alliria98 there's a first time for everything ;)

Let me say that service by hostgroup is a bad thing :) but of course it's a feature and you can use it, but prefer host and service template for the future :) 

Did you use macro or theses to define your community in Centreon ? Define it like below

![image](https://cloud.githubusercontent.com/assets/12429463/24150982/bcdb4b60-0e47-11e7-88c8-b1f1f472f7f1.png)

And not like this : 

![image](https://cloud.githubusercontent.com/assets/12429463/24151092/09a8ecae-0e48-11e7-9ec8-3dc02d925684.png)

If you have done this right, go back to the command prompt and try : 

`su - centreon-engine -c "your full command here"`

**Comment by alliria98** [comment]
Well i though service by host group was a good idea :(
Whatever :) i defined snmp community in version directly in host settings, just below IP address

There your request : 
![image](https://cloud.githubusercontent.com/assets/26572075/24152166/278c5442-0e4b-11e7-81d0-5c2c11ebcc57.png)

I got an access error on centreon_plugins.pl so i changed permission and know it's working so thanks a lot :)

**Comment by Sims24** [comment]
Great ;) Enjoy !

**Comment by Sims24** [comment]
@alliria98 just to be less mysterious, imagine you want to change threshold for one switch but not another ... Services linked to hostgroup doesn't allow you to do that :(

**Comment by alliria98** [comment]
I understand your point :)
Thanks again for your help mysterious Sims24 :)
