### ISSUE TITLE
Few questions about missing/missed plugins - mode

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-plugins#617]
First of all and once again, i'm very new to the wonderfull world of monitoring, centreon, centos and those amazing plugins

After some configuration of my centreon, i can manage cpu, ping.. on my differents servers and networks assets.
But i'm looking for another informations i can't on my own apparently : i would like to know if i miss an option in those plugins to manage these : 
on Network/Fortinet/Fortigate i would appreciate to get the bandwidth usage per interfaces
on Network/Cisco/Smallbusiness i would appreciate to get the bandwidth usage per interfaces adn also the memory used/free

So my question is : did I miss something or those informations aren't implemented in those (once again) amazing plugins, or may be there are no OIDs for that ?

I don't know how to check that

**Comment by garnier-quentin** [comment]
You have modes '--interfaces' for the 2 plugins.

**Comment by alliria98** [comment]
Am I may be wrong then but does --interfaces mode don't only check for up/down interfaces ?

**Comment by Sims24** [comment]
@alliria98 you can use --add-traffic [--add-cast --add-errors] to get the information you want !

**Comment by alliria98** [comment]
Ho !
Where can I find a help section/readme for that ?

**Comment by Sims24** [comment]
Like this : 

`[root@sims-ces-misc script]# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --mode interfaces --help

Plugin Description:
    Check Cisco equipments (2800, 2900, 3750, Nexus,...) in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

Output Options:
    --verbose
            Display long output.

    --debug Display also debug messages.

    --filter-perfdata
            Filter perfdata that match the regexp.

    --explode-perfdata-max
            Put max perfdata (if it exist) in a specific perfdata (without
            values: same with '_max' suffix) (Multiple options)

    --change-perfdata
            Change perfdata name (Multiple option) Syntax:
            regexp_matching,regexp_substitute

    --range-perfdata
            Change perfdata range thresholds display: 1 = start value equals
            to '0' is removed, 2 = threshold range is not display.

    --filter-uom
            Filter UOM that match the regexp.

    --opt-exit
            Exit code for an option error, usage (default: unknown).

    --output-xml
            Display output in XML Format.

    --output-json
            Display output in JSON Format.

    --disco-format
            Display discovery arguments (if the mode manages it).

    --disco-show
            Display discovery values (if the mode manages it).

Snmp Options:
    --hostname
            Hostname to query (required).

    --snmp-community
            Read community (defaults to public).

    --snmp-version
            Version: 1 for SNMP v1 (default), 2 for SNMP v2c, 3 for SNMP v3.

    --snmp-port
            Port (default: 161).

    --snmp-timeout
            Timeout in secondes (default: 1) before retries.

    --snmp-retries
            Set the number of retries (default: 5) before failure.

    --maxrepetitions
            Max repetitions value (default: 50) (only for SNMP v2 and v3).

    --subsetleef
            How many oid values per SNMP request (default: 50) (for get_leef
            method. Be cautious whe you set it. Prefer to let the default
            value).

    --snmp-force-getnext
            Use snmp getnext function (even in snmp v2c and v3).

    --snmp-username
            Security name (only for SNMP v3).

    --authpassphrase
            Authentication protocol pass phrase.

    --authprotocol
            Authentication protocol (MD5|SHA)

    --privpassphrase
            Privacy protocol pass phrase

    --privprotocol
            Privacy protocol (DES|AES)

    --contextname
            Context name

    --contextengineid
            Context engine ID

    --securityengineid
            Security engine ID

    --snmp-errors-exit
            Exit code for SNMP Errors (default: unknown)

Retention Options:
    --memcached
            Memcached server to use (only one server).

    --statefile-dir
            Directory for statefile (Default:
            '/var/lib/centreon/centplugins').

    --statefile-suffix
            Add a suffix for the statefile name (Default: '').

    --statefile-concat-cwd
            Concat current working directory with option '--statefile-dir'.
            Useful on Windows when plugin is compiled.

    --statefile-storable
            Use Perl Module 'Storable' (instead Data::Dumper) to store
            datas.

Mode:
    Check interfaces.

    --add-global
            Check global port statistics (By default if no --add-* option is
            set).

    --add-status
            Check interface status.

    --add-traffic
            Check interface traffic.

    --add-errors
            Check interface errors.

    --add-cast
            Check interface cast.

    --warning-status
            Set warning threshold for status. Can used special variables
            like: %{admstatus}, %{opstatus}, %{display}

    --critical-status
            Set critical threshold for status (Default: '%{admstatus} eq
            "up" and %{opstatus} ne "up"'). Can used special variables like:
            %{admstatus}, %{opstatus}, %{display}

    --warning-*
            Threshold warning. Can be: 'total-port', 'total-admin-up',
            'total-admin-down', 'total-oper-up', 'total-oper-down',
            'in-traffic', 'out-traffic', 'in-error', 'in-discard',
            'out-error', 'out-discard', 'in-ucast' (%), 'in-bcast' (%),
            'in-mcast' (%), 'out-ucast' (%), 'out-bcast' (%), 'out-mcast'
            (%).

    --critical-*
            Threshold critical. Can be: 'total-port', 'total-admin-up',
            'total-admin-down', 'total-oper-up', 'total-oper-down',
            'in-traffic', 'out-traffic', 'in-error', 'in-discard',
            'out-error', 'out-discard', 'in-ucast' (%), 'in-bcast' (%),
            'in-mcast' (%), 'out-ucast' (%), 'out-bcast' (%), 'out-mcast'
            (%).

    --units-traffic
            Units of thresholds for the traffic (Default: '%') ('%', 'b/s').

    --units-errors
            Units of thresholds for errors/discards (Default: '%') ('%',
            'absolute').

    --nagvis-perfdata
            Display traffic perfdata to be compatible with nagvis widget.

    --interface
            Set the interface (number expected) ex: 1,2,... (empty means
            'check all interface').

    --name  Allows to use interface name with option --interface instead of
            interface oid index (Can be a regexp)

    --speed Set interface speed for incoming/outgoing traffic (in Mb).

    --speed-in
            Set interface speed for incoming traffic (in Mb).

    --speed-out
            Set interface speed for outgoing traffic (in Mb).

    --no-skipped-counters
            Don't skip counters when no change.

    --force-counters32
            Force to use 32 bits counters (even in snmp v2c and v3). Should
            be used when 64 bits counters are buggy.

    --reload-cache-time
            Time in minutes before reloading cache file (default: 180).

    --oid-filter
            Choose OID used to filter interface (default: ifName) (values:
            ifDesc, ifAlias, ifName).

    --oid-display
            Choose OID used to display interface (default: ifName) (values:
            ifDesc, ifAlias, ifName).

    --oid-extra-display
            Add an OID to display.

    --display-transform-src
            Regexp src to transform display value.

    --display-transform-dst
            Regexp dst to transform display value.

    --show-cache
            Display cache interface datas.
`

**Comment by alliria98** [comment]
Wow thanks a lot and my apologies again to haven't find it by my own :(
Hope i won't need you anymore for dummies questions :/
