### ISSUE TITLE
network::cisco::smallbusiness:standard::snmp how to get memory usage ?

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-plugins#618]
Hi once again
It seems there is no memory option for Cisco Small Business plugin

How can I add this option ?

**Comment by garnier-quentin** [comment]
I didn't add it. Test with linux snmp plugin for memory. It should work i think.

**Comment by alliria98** [comment]
I tried with linux and freebsd, same result for both : 
![image](https://cloud.githubusercontent.com/assets/26572075/24293878/290d02d0-1094-11e7-8eda-b9e1557a968a.png)

**Comment by garnier-quentin** [comment]
Maybe there is no information about the memory in the SNMP MIB for that equipment.

**Comment by alliria98** [comment]
I've just made an snmpwalk on my cisco switch and ther is no print of memory... Even on cisco forum i can't find the oid number...
I guess you're right and this kind of product (small business) don't have any information about this

**Comment by garnier-quentin** [comment]
Thanks for the feedback.
