### ISSUE TITLE
network::hp::procurve::plugin Environment mode output

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#62]
Hi,

Would it be possible to modify the network::hp::procurve::plugin environment mode to show all the components in the output by default, like network::cisco::2900::plugin does. I noticed that the HP plugin gives me "OK: All sensors are ok" even if the actual output in command line is "All 0 components are ok". And because of that I  have to check all the environments manually from command line first and then can add to Monitoring frontend.

**Comment by garnier-quentin** [comment]
I see what you mean. i'll update the code to get more options about it.

**Comment by garnier-quentin** [comment]
Hi,

Could you please test it ? Thanks for that.

**Comment by kadrika** [comment]
Hi,

I can test it tomorrow morning.

Best regards/ Parimate soovidega,
Kadri Kalpus
NOC Monitoring Engineer
Santa Monica Networks
Phone: +372-6811-262
Mobile: +372-51-200-44
kadri.kalpus@smn.ee<mailto:kadri.kalpus@smn.ee>

[Description: Description: Description: Description: Description: cid:2AE120E0-A2E0-49DE-9208-A226D1B1D8ED]

From: qgarnier
Reply-To: centreon/centreon-plugins
Date: Wednesday, May 27, 2015 at 4:18 PM
To: centreon/centreon-plugins
Cc: Kadri Kalpus
Subject: Re: [centreon-plugins] network::hp::procurve::plugin Environment mode output (#62)


Hi,

Could you please test it ? Thanks for that.

**Comment by kadrika** [comment]
Hi,

Just tested and it works!

Thanks!

Is it also possible to do it for the memory output also?

Best regards/ Parimate soovidega,
Kadri Kalpus
NOC Monitoring Engineer
Santa Monica Networks
Phone: +372-6811-262
Mobile: +372-51-200-44
kadri.kalpus@smn.ee<mailto:kadri.kalpus@smn.ee>

[Description: Description: Description: Description: Description: cid:2AE120E0-A2E0-49DE-9208-A226D1B1D8ED]

From: Kadri Kalpus
Date: Wednesday, May 27, 2015 at 5:02 PM
To: centreon/centreon-plugins
Subject: Re: [centreon-plugins] network::hp::procurve::plugin Environment mode output (#62)

Hi,

I can test it tomorrow morning.

Best regards/ Parimate soovidega,
Kadri Kalpus
NOC Monitoring Engineer
Santa Monica Networks
Phone: +372-6811-262
Mobile: +372-51-200-44
kadri.kalpus@smn.ee<mailto:kadri.kalpus@smn.ee>

[Description: Description: Description: Description: Description: cid:2AE120E0-A2E0-49DE-9208-A226D1B1D8ED]

From: qgarnier
Reply-To: centreon/centreon-plugins
Date: Wednesday, May 27, 2015 at 4:18 PM
To: centreon/centreon-plugins
Cc: Kadri Kalpus
Subject: Re: [centreon-plugins] network::hp::procurve::plugin Environment mode output (#62)


Hi,

Could you please test it ? Thanks for that.
