### ISSUE TITLE
How works plugin=apps::vmware::connector

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-plugins#620]
Hi once again !
I got a vcenter (win server 2k12) managing 5 ESX
I want to monitor those ESX, but i don't know how ? Should i use this plugin : 
- apps::vmware::connector
or this one
- apps::vmware::wsman 

Should i traget my vcenter or my ESX ?

For information (I don't know if it's normal or not) i can get CPU usage on ESX with plugin=os::linux::snmp but not Memory usage...

**Comment by garnier-quentin** [comment]
The plugin 'apps::vmware::wsman' is to monitor hardware of standalone ESXi (not linked with a vcenter).
With the other you can monitor many things. You need to install and configure following daemon:
https://github.com/centreon/centreon-vmware

You could target your ESXi directly or your vcenter.

**Comment by alliria98** [comment]
Hey !
I'm trying to install your centreon-vmware plugin, but can't succeed at it
I'm following the documentation for installation but can't get further than "centreon-vmware Installation with rpm" or "centreon-vmware Installation with source"
