### ISSUE TITLE
Summer Time Problem

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#621]
Hi,

Since yesterday, I have problem and time off 1h.
Perhaps my OS is not configured correctly ? Could you provide best practice ?

Thanks,

./centreon_plugins.pl --plugin=os::windows::snmp::plugin --snmp-community=public --snmp-version=1 --hostname=10.x.x.x --mode=time --warning=-30:30 --critical=-60:60 --timezone=+0100
CRITICAL: Time offset 3600 second(s) : 2017-03-27T09:54:36 (+0100) | 'offset'=3600s;-30:30;-60:60;;

**Comment by garnier-quentin** [comment]
I think you should use following timezone : --timezone=Europe/Paris

**Comment by romsworld** [comment]
Thanks, it works,
