### ISSUE TITLE
[network::dlink::standard::snmp::plugin] vlan 

### ISSUE THREAD

**Issue by sunks08** [centreon/centreon-plugins#622]
Hello,

Im' trying to get vlan information on each ports of my d'link switch,

i'm using this command to get traffic on each ports:

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl
	--plugin=network::dlink::standard::snmp::plugin
	--mode=interfaces
	--hostname=XX.XX.XX.XX
	--interface=X
	--add-traffic

I would like to add the vlan of the port to display it, I guess i have to use an OID option ? I don't really understand how it works

thanks !

**Comment by garnier-quentin** [comment]
Hi,

Right now, you cannot display the vlan in the output.

**Comment by sunks08** [comment]
Ho, ok.

And will it be possible in the future ? :) Something that could read dynamically the vlan of the port and display it would be awesome !

thanks

**Comment by garnier-quentin** [comment]
Which OID for the vlan ?

**Comment by garnier-quentin** [comment]
I think it s an enterprise OID. So we can extend. But i don't manage multiple values. I should do with standard IP first.

**Comment by sunks08** [comment]
I'm not sure about the OID, i don't really know where to get this information.

thanks
