### ISSUE TITLE
change switch service status as "alert" instead of "critical"

### ISSUE THREAD

**Issue by sunks08** [centreon/centreon-plugins#625]
Hello, 

I'm using a command to check the traffic and status of each ports of my dlink switch :

perl centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin --mode=interfaces --hostname=XX.XX.XX.XX --interface=X --add-status --add-traffic 

When there is nothing plug into the interface the command return the status as down and the service status in centreon is set as "CRITICAL", even if the port is administratively up. 

i'd like to change it and when it's administratively up + status down it return the service as "ALERT"
and when it's administratively down it return the service as "CRITICAL" on the Centreon interface.
How can i do that ? 

Do i have to setup that in the command, and if yes with what ?
Or do i have to change something in the plugin code ?

Thanks !

**Comment by garnier-quentin** [comment]
You should look options: --warning-status and --critical-status in the help

**Comment by sunks08** [comment]
Thanks, it come out with that :
perl centreon_plugins.pl --plugin=network::dlink::standard::snmp::plugin 
--mode=interfaces --hostname=172.16.159.91 
--interface=3 --add-status --add-traffic --snmp-community=public 
--warning-status='%{admstatus} eq "up" and %{opstatus} ne "up"' 
--critical-status='%{admstatus} ne "up" and %{opstatus} ne "up"' 
--warning-in-traffic=50 --warning-out-traffic=50 
--critical-in-traffic=80 --critical-out-traffic=80

but i don't understand how i add the %{display} ?

If i do something like that it don't work :

--warning-status='%{admstatus} eq "up" and %{opstatus} ne "up" and %{display} "test"'

Thanks

**Comment by garnier-quentin** [comment]
Like that:
````
--warning-status='%{admstatus} eq "up" and %{opstatus} ne "up" and %{display} eq "test"'
````

**Comment by sunks08** [comment]
i already tried it but instead it just change to "OK" !

thanks you for the speed of your answer btw :)
