### ISSUE TITLE
centreon-plugins/hardware/ups/standard/rfc1628/snmp/mode/batterystatus.pm

### ISSUE THREAD

**Issue by rlutchmun** [centreon/centreon-plugins#626]
Bonjour,

Nous ne pouvons mettre un seuil warning & critical sur les metriques voltage et temp.

Et aussi la valeur remonté pour la température est 300C.

OK: Battery status is normal - Charge remaining: 100% (-1 minutes remaining) | 'load'=100%;60:110;50:120;0;100 'voltage'=598.4V;;;; 'temp'=300C;;;;

**Comment by garnier-quentin** [comment]
Indeed. We can do some change on it.

**Comment by rlutchmun** [comment]
Can you please provide the modifications we need to do so that we can put a threshold on voltage and temperature and also make the output of temperature more appropriate as 300C is not a correct value.

**Comment by garnier-quentin** [comment]
Sorry,  i cannot divide by ten the temperature. I have looked in the rfc:
https://tools.ietf.org/html/rfc1628

```
upsBatteryTemperature OBJECT-TYPE
       SYNTAX     Integer32
       UNITS      "degrees Centigrade"
       MAX-ACCESS read-only
       STATUS     current
       DESCRIPTION
               "The ambient temperature at or near the UPS Battery
               casing."
       ::= { upsBattery 7 }
```
