### ISSUE TITLE
Fortigate 620B plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#63]
Hi,

As hardware check with network::fortinet::fortigate::200B::plugin and network::fortinet::fortigate::300B::plugin do not work with Fortigate 620B, is it possible to create a new plugin for the 620B also?

**Comment by garnier-quentin** [comment]
Fortigate hardware doens't work at all. It works only for 'FortiGate-5000 Series Chassis' (support from fortigate gives us the information).
