### ISSUE TITLE
output problem with os::windows::snmp:: plugin --mode=service

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-plugins#631]
Hey there !
First of all thanks once again for those amazings plugins !

I would like to monirtor some windows services with snmp
so I use that kind of request 

` perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=XXX.XXX.XXX.XXX --snmp-version=2c --snmp-community=******* --mode=service --service='Spooler' --critical=1: --verbose`

I tried to understand this post before [https://github.com/centreon/centreon-plugins/issues/416](url)
I understand with my request that if at least one service with the name "Spooler' is running, it will return OK, or critical if there is 0 Spooler service running

But if the service is running or not, I always got the same output
![image](https://cloud.githubusercontent.com/assets/26572075/24710809/7ede2368-1a1e-11e7-95b7-d98888f01f9d.png)
My windows is in French, we are agree that I have to check for 'spooler' and not "spouleur d'impression'
![image](https://cloud.githubusercontent.com/assets/26572075/24710867/adabc18c-1a1e-11e7-90e3-12765c1c5ddd.png)

**Comment by masgo** [comment]
It is probably easy to debug this with `snmpwalk` what the plugins looks for is basically die OID `.1.3.6.1.4.1.77.1.2.3` (and sub-OIDs of that). Try this:
`snmpwalk -v 2c -c <COMMUNITY> <HOST> 1.3.6.1.4.1.77.1.2.3.1`

Now look (manually or by using `grep`) if you find either "Spooler" or "spouleur d'impression". Be also careful if spooler is written with a small or capital S.

---
Background:
If you look at https://github.com/centreon/centreon-plugins/blob/master/os/windows/snmp/mode/service.pm you can see this:

```
my $oid_svSvcEntry = '.1.3.6.1.4.1.77.1.2.3.1';
my $oid_svSvcName  = '.1.3.6.1.4.1.77.1.2.3.1.1';
my $oid_svSvcInstalledState  = '.1.3.6.1.4.1.77.1.2.3.1.2';
my $oid_svSvcOperatingState = '.1.3.6.1.4.1.77.1.2.3.1.3';
```

These are the OIDs used by this plugin to look for the name and state of the service.

**Comment by alliria98** [comment]
No matter my 'spooler' service is activated or not, it doesn't appear in the snmpwalk
Some OIDs aren't translate to name and stay in an Hex-String format, so I guess one of them is my spooler

This spooler service was just to test for purpose, I have to monitor some services, but not this one, I'll try with translated OID and come back with result ;-)

Thanks for the help

**Comment by alliria98** [comment]
Hey there
everything seems to work fine

I'll confirm that tomorrow, have to perform some tests and I don't have time right now sorry :(

**Comment by Sims24** [comment]
That's the SNMP service from windows that doesn't refresh everytime state of the services. So it's "normal" I guess.

You should consider using an agent like https://github.com/mickem/nscp , which is really interesting and reliable for monitoring Windows environments. 

Thanks for the feedback
