### ISSUE TITLE
output problem with hardware::ups::mge::snmp::plugin

### ISSUE THREAD

**Issue by ITNicoz** [centreon/centreon-plugins#632]
Hi,

I think i've got some bad issues with that command. Can you help me ? 
### without threshold
./centreon_plugins.pl --plugin=hardware::ups::mge::snmp::plugin --mode=battery-status --hostname=XX.XX.XX.30
OK: Battery status is ok - Charge remaining: 100% (55 minutes remaining) | 'load'=100%;;;0;100 'voltage'=50V;;;;

### with threshold
./centreon_plugins.pl --plugin=hardware::ups::mge::snmp::plugin --mode=battery-status --hostname=XX.XX.XX.30 --warning=50 --critical=20
**CRITICAL**: Charge remaining: 100% (55 minutes remaining) | 'load'=100%;0:50;0:20;0;100 'voltage'=50V;;;;

[In the manual](https://github.com/centreon/centreon-plugins/blob/master/hardware/ups/mge/snmp/mode/batterystatus.pm)
=item B<--warning>
Threshold warning in percent of charge remaining.
=item B<--critical>
Threshold critical in percent of charge remaining.

I tried with different hresholds 50%, 1, 110 ...

Thank you.

**Comment by masgo** [comment]
It's not really your fault because the behavior is badly documented. 

If you do `--warning=50` you are basically telling the plugin to warn you if the value become **greater** than 50!

You need to append a `:` at the end. So it should be `--warning=50:`. This will tell the plugin to check if the value is **below** 50.

**Comment by ITNicoz** [comment]
Merci. It seems to be ok.
   ./centreon_plugins.pl --plugin=hardware::ups::mge::snmp::plugin --mode=battery-status --hostname=10.155.216.30 --warning 50: --critical 20:

**Comment by ITNicoz** [comment]
OK: Battery status is ok - Charge remaining: 100% (55 minutes remaining) | 'load'=100%;50:;20
