### ISSUE TITLE
database::mssql::plugin and warning 

### ISSUE THREAD

**Issue by romnvll** [centreon/centreon-plugins#633]
hello,
i update the centreon plugins with github.

And now this command return an error : 

`./centreon_plugins.pl --plugin database::mssql::plugin --hostname xxx.xxx.xxx.xxx --port 49616 --username 'xxx' --password 'xxx' --mode='databases-size' --warning='95' --critical='98' --filter='^(?!(tempdb))' --verbose

Unknown option: warning at /usr/lib64/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 67.`

Any idea ?

thank you

**Comment by Sims24** [comment]
Hi @romnvll 

Yes plugin has elvolved. You can see it in help, we have done some refactoring so you should use --warning-database --critical-database

**Comment by masgo** [comment]
It would be nice if the plugin checked for options which once (or within the last 2 years) existed and give a more meaningful error like "--warning is no longer used. Please have a look at the help section of --warning-database"

**Comment by garnier-quentin** [comment]
A break change will displayed in the changelog now.

**Comment by romnvll** [comment]
ok, thank you very much, it's the same for filter

2017-04-06 12:26 GMT+02:00 qgarnier <notifications@github.com>:
