### ISSUE TITLE
[network::hp::procurve::plugin] --mode interfaces

### ISSUE THREAD

**Issue by Thibaut-ids** [centreon/centreon-plugins#635]
Hi,

I use plugin [network::hp::procurve::plugin] on several hp switches. The returned values seem correct. However, when graphs are displayed, incoming traffic is not represented correctly. 
The values indicated on the graph are also good. But I think there is a problem of unity. Indeed, the graph correctly displays the values of the outgoing traffic, but not the value of the incoming traffic.

I think an image will be more meaningful:

![image](https://cloud.githubusercontent.com/assets/23074308/24800206/8215137a-1b9f-11e7-8373-aa0e51f78d54.png)

In the image we see that the curve of the incoming traffic passes above the axis. Moreover, the graph adapts to the values of the outgoing traffic, but not to those of the incoming traffic. Indeed on the graph present above, the incoming traffic sometimes reaches 2Gb / s.

![image](https://cloud.githubusercontent.com/assets/23074308/24800379/2d5ba5fa-1ba0-11e7-9d74-46c0823966b4.png)

Separate graphics do not solve the problem.

The problem may arise from a configuration error on my part or a forgotten option when executing.

--plugin network::hp::procurve::plugin
	--mode interfaces
	--interface XX
	--hostname  XXX.XXX.XXX.XXX
	--snmp-version 2c
	--snmp-community public
	--add-status
	--add-traffic
	--warning-in-traffic 90
	--warning-out-traffic 80
	--critical-in-traffic 95
	--critical-out-traffic 90

Thank you in advance for your help.
(Sorry for my bad English)

**Comment by Sims24** [comment]
Hello @Thibaut-ids , 

This is a know centreon graph issue with the latest 2.8.5 release. Please open a ticket in Centreon github (you should be able to find an existing one to follow)

Thanks, 
Simon
