### ISSUE TITLE
How to add new plugin

### ISSUE THREAD

**Issue by ncblx** [centreon/centreon-plugins#638]
Hello Colleagues.
How to add new plugin? 
i download all catalog. and copy on my server
/root/centreon/
but in the web interface plugins not active. 
Thanks

**Comment by Sims24** [comment]
Hi @ncblx ,

You need to create a command in Centreon, with wanted parameters, and then use it for a host or a service ... Of course you could use some template between ! 

A better place for this would be IRC, Forum or Centreon github. If you use 2.8.x version, you will get some starting pack that could be good example.

Thanks, 
Simon
