### ISSUE TITLE
BGP filter check problem

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#639]
Hi,

I think there is a bug in the BGP check, if using filter.

This is the check without BGP filter:
./centreon_plugins.pl --plugin=apps/protocols/bgp/4/plugin.pm --snmp-version=2c --snmp-community=xxx --verbose --mode=bgppeerstate --hostname=1.2.3.4
OK: Peer: '10.240.10.1' AS:'65211'  Local: '10.240.10.137:50637' Remote: '10.240.10.1:179' Peer State: 'established' Admin State : 'start', Last update : 118s | 'seconds'=118s;;;0;
Peer: '10.240.10.1' AS:'65211'  Local: '10.240.10.137:50637' Remote: '10.240.10.1:179' Peer State: 'established' Admin State : 'start', Last update : 118s

I want to check BGP peer state using filter, like this:
./centreon_plugins.pl --plugin=apps/protocols/bgp/4/plugin.pm --snmp-version=2c --snmp-community=xxx --verbose --mode=bgppeerstate --hostname=1.2.3.4 --filter-peer='10.240.8.1'
OK: All BGP peers are ok |

How can it be ok, if peer with that IP is not even in the list?

**Comment by Sims24** [comment]
Hi @kadrika 

I get your point, please tell me if the fix proposed in the picture below could fit (you can use option --opt-exit critical if you would prefer critical instead of unknown).

![image](https://cloud.githubusercontent.com/assets/12429463/25203109/43382c06-2558-11e7-9858-93cf014d9831.png)

Code to insert is below : 

```
    if (scalar(keys %{$self->{peers}}) <= 0) {
        $self->{output}->add_option_msg(short_msg => 'No peers detected, check your filter ? ');
        $self->{output}->option_exit();
    }
```

I'll do a pull request, waiting for Quentin to merge it after some deserved hollydays ;) Feel free to apply the patch in the meantime. 

Thx

**Comment by kadrika** [comment]
Yes, it is working! Thanks!

One more thing, how do I configure the --critical-status, if I want to receive critical alarm, if the peer is in one of those states: 
1 => 'idle',
    2 => 'connect',
    3 => 'active',
    4 => 'opensent',
    5 => 'openconfirm',

So the only OK state is 6 => 'established'

**Comment by Sims24** [comment]
you can do it like this : 

--critical-status '%{peerstate} !~ /established/'

**Comment by kadrika** [comment]
Thanks! Perfect!

**Comment by Sims24** [comment]
Closed by https://github.com/centreon/centreon-plugins/pull/643/commits/7f2f8b1da22b6d7d5d7460976a1c690d6ee7bda8
