### ISSUE TITLE
Add a mode to check processlist

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon-plugins#64]
Hello,

On my MySQL, I have to check the number of running queries. This check allow me to spot performance issues of my MySQL.

I used the mode "queries" but it get values returned indicate the number of times each queries statement has been executed. 

https://dev.mysql.com/doc/refman/5.0/en/server-status-variables.html#statvar_Com_xxx

This is produce a big value, interstering to check the work on the system, but it's useless to do active check of the MySQL.

It will be usefull to add a new check using "SHOW FULL PROCESSLIST".

Best regards.

**Comment by garnier-quentin** [comment]
Ok. I'll add a mode to check current request runnings and with the threshold since X seconds running.

**Comment by garnier-quentin** [comment]
Done with 'longqueries' mode for MySQL.
