### ISSUE TITLE
apps::protocols::x509::plugin failed to accept or ssl handshake

### ISSUE THREAD

**Issue by Dodofox** [centreon/centreon-plugins#641]
Hi everybody, 

I'm totaly beginner with certificate supervision. I'm tryin to supervise X509 certificate with this plugin "apps::protocols::x509::plugin". 

When i'm using old nagios module : 
./check-http -H MYHOSTNAME -C 50 --> OK - Certificate 'MYHOSTNAME' will expire on 09/21/2017 12:19.

When i'm using this module : 
/usr/bin/perl /usr/lib/nagios/plugins/centreon-plugins-master/centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=validity --hostname=MYHOSTNAME --port=443  --validity-mode=expiration
--> CRITICAL: failed to accept or ssl handshake: ,SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed |

Everyone have any idea to solve my problem ? 
i tried add --servername but same result ...

**Comment by garnier-quentin** [comment]
Are you available for a websex ? You can send me an email.

**Comment by Dodofox** [comment]
hi,

i havn't Got your email so I answer here.
for a websex I'm not available 😉 but for a webex tomorrow I am ! whenever just tell me when you want !


Le 2 mai 2017 17:25, qgarnier <notifications@github.com> a écrit :

Are you available for a websex ? You can send me an email.

**Comment by garnier-quentin** [comment]
You have it in my profile page ;) Send an email tomorrow.

**Comment by garnier-quentin** [comment]
Send me an email and i'll look about it.

**Comment by garnier-quentin** [comment]
You have an option now: --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE"
