### ISSUE TITLE
[network::citrix::netscaler::common::mode::vserverstatus] - Handling Long Table Index Names

### ISSUE THREAD

**Issue by jdidierpichat** [centreon/centreon-plugins#644]
Hello everybody,

This message to let you know that the plugin (MPX8000) also works with VPX.

However, a little remark about the vserver status. If the vserver as more than 31 characters, we can't see the fullname of the vserver with the OID used in the plugin .1.3.6.1.4.1.5951.4.1.3.1.1.1.

This OID must be used: .1.3.6.1.4.1.5951.4.1.3.1.1.59 for view the fullname of vservers. 

Note from Citrix:
Handling Long Table Index Names
As per RFC 2578, all OIDs are limited to 128 sub-identifiers. This places some limitations on table indexing because this also applies to OIDs for object instances, and these consist of the concatenation of the base OID assigned in the object definition plus the index components. Therefore in case of tables, if the length of the index name on which an SNMP request is made is greater than 31 characters, it is encoded using an internal encoding function. As a result, the encoded name will be displayed in the SNMP Manager. However, the table will provide an additional FullName OID by querying which it is possible to get back the original index name on which the query was made. For example – While performing SNMP GET operation on vserverTable using the index vserverName, if the vserverName is greater than 31 characters, it is encoded. However, vserverTable provides an OID - vsvrFullName (1.3.6.1.4.1.5951.4.1.3.1.1.59), by querying which it is possible to get back the original vserver name. The following tables are indexed on index names which follow the above behaviour.

**Comment by garnier-quentin** [comment]
Thanks. I'll look to that next week

**Comment by jdidierpichat** [comment]
Hi,

Nous need to change le mode "list-vservers" for a full resolution of this case.
