### ISSUE TITLE
apps::protocols::http::plugin on javascript webpage

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#645]
Hi, 

I would like to check authentication on a web page developed with javascripts. 
I tried working with centreon plugin apps::protocols::http::plugin but i can't get it to work. 
It seems that authentication doesn't pass and thus the string i search can't be found. 

have any one please already got this working ? 
Any help would be much appreciated.

Thank you

**Comment by Sims24** [comment]
Hi, 

could you provide more information  : 
 - Which command line are you using ?
 - Is the site over http or https and wich authentication method is used ? 

Thx

**Comment by saharawolf** [comment]
Hi thank you for your reply, 

The site is over http

i used this command 
perl centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=myhostfqdn --port=8001 --method='POST' --post-param='username=xxxx' --post-param='password=yyyy' --cookies-file='/tmp/lwp_cookies.dat' --urlpath='/login' --expected-string='Authentification ok'

Thank you

**Comment by saharawolf** [comment]
Hi, 

Can't anyone help with this matter please ?

Thank you

**Comment by Sims24** [comment]
Hi, 

We need more information on how the website is built to be able to give you more insights. Can you post the target webpage js code ?

**Comment by saharawolf** [comment]
I upluoded the code.
Is this could help ?

[auth.txt](https://github.com/centreon/centreon-plugins/files/970170/auth.txt)


Thanks

**Comment by Sims24** [comment]
Could you also paste the result of the following command plz : 

`perl centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=myhostfqdn --port=8001 --method='POST' --post-param='username=xxxx' --post-param='password=yyyy' --cookies-file='/tmp/lwp_cookies.dat' --urlpath='/login' --expected-string='Authentification ok' --verbose`

**Comment by Sims24** [comment]
@saharawolf after further digging, the perl library we are using doesn't manage javascript. You will not be able to authenticate to this kind of page.

Feel free to ask for an enhancement but that will probably be a new plugin

**Comment by garnier-quentin** [comment]
You should look for Selenium for that.

**Comment by saharawolf** [comment]
hi, 

I reopen this case, i followed your advice and installed selenium, but i have too much trouble to get it work.
after installing everything i run a test and get this error

./check_centreon_waa -c 60 -w 50 -d /var/lib/centreon_waa -t test -r localhost:4444
Error requesting http://localhost:4444/selenium-server/driver/:
Failed to start new browser session: org.openqa.selenium.server.RemoteCommandException: Error while launching browser

I have searched two days and can't get it work.
can you help ?

Thank you

**Comment by garnier-quentin** [comment]
Which version of selenium do you use ? You should read the following documentation:
https://documentation.centreon.com/docs/centreon-web-application-analytics/en/latest/

**Comment by saharawolf** [comment]
i followed this entirely, i did the installation from sources.
i used selenium 2.45 as the last release doesn't start with java -jar ...
i used firefox last release.

**Comment by garnier-quentin** [comment]
I can't help you more for selenium. I don't know
