### ISSUE TITLE
Problème HP Proliant ML350p Gen8

### ISSUE THREAD

**Issue by Wilangles** [centreon/centreon-plugins#646]
Bonjour, 

Je suis stagiaire dans une entreprise et je dois m'occuper de la supervision avec Centreon.

Alors voilà, j'ai des problèmes pour superviser un serveur HP Proliant ML350p Gen8. Le serveur tourne sous Windows Server 2012 R2. 

Lorsque je veux superviser le mode hardware, j'ai ça : 

> ./centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=194.168.4.203 --snmp-community=Windows --snmp-version=2c --debug
**> OK: All 0 components are ok []. |**
> Product Name: unknown, Serial: unknown, Rom Version: unknown
> Checking cpu
> Checking ide controllers
> Checking ide logical drives
> Checking ide physical drives
> Checking power converters
> Checking power supplies
> Checking sas controllers
> Checking sas logical drives
> Checking sas physical drives
> Checking scsi controllers
> Checking scsi logical drives
> Checking scsi physical drives
> Checking fca host controller
> Checking fca external controller
> Checking fca external accelerator boards
> Checking fca logical drives
> Checking fca physical drives
> Checking da controller
> Checking da accelerator boards
> Checking da logical drives
> Checking da physical drives
> Checking fans
> Checking physical nics
> Checking logical nics
> Checking temperatures
> Checking ilo

 Je trouve que la ligne " OK: All 0 components are ok []. |" est bizarre. 

Ensuite lorsque j'utilise le mode global-status, j'ai cemessage d'erreur : 

>  ./centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=global-status --hostname=194.168.4.203 --snmp-community=Windows --snmp-version=2c
**> UNKNOWN: SNMP GET Request : Cant get a single value.**

La dernière erreur concerne la supervision de la RAM qui ne fonctionne pas. Mais la supervision du  CPU et du disque fonctionne. J'en déduis que ce n'est pas un problème de configuration de SNMP.

Pour la RAM, j'utilise check_centreon_snmp_memory 
Pour le CPU, j'utilise check_centreon_snmp_cpu 

Le message d'erreur renvoyé est : 

> SNMP TABLE ERROR : No response from remote host '194.168.4.203'.

Pouvez-vous m'aider ? Si vous avez d'informations supplémentaires, n'hésitez pas. 

Merci d'avance

**Comment by garnier-quentin** [comment]
It's a snmp issue. Have you install hp insight snmp agent on your windows ? You'll need to have that installed for hp proliant snmp working.

**Comment by Wilangles** [comment]
Bonjour, merci pour la réponse. 
HP Insight SNMP agent est bien installé. Mais quand je vais sur "System Management Homepage", le System Model indique " Unknown". Je vais essayer de le réinstaller pour voir si ça fonctionne mieux.

**Comment by garnier-quentin** [comment]
Maybe in the same case: ref #657
