### ISSUE TITLE
[network::alcatel::omniswitch::6850] usage of --exclude option

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon-plugins#647]
Hi

I would like to exclude a specific instance of a fan which is not available on my switch.
The help page of the plugin explains this :
    --exclude
            Exclude some parts (comma seperated list) (Example:
            --exclude=fan) Can also exclude specific instance:
            --exclude=fan#1.2#,module

When using --exclude="fan" excludes all my fans
But when I type --exclude="fan#2#" (to exclude instance 2) all my instances are included.

How to use this option if I want to exclude instances ?

Regards

Norbert

**Comment by garnier-quentin** [comment]
Could you give us the result with verbose option ?

**Comment by nogomes** [comment]
Here is :

$ perl centreon_plugins.pl --plugin=network::alcatel::omniswitch::6850::plugin --mode=hardware --hostname=xxxxxxxxx --snmp-version=2c --snmp-community=xxxxxxxxxx --verbose

CRITICAL: fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/2' status is notRunning. UNKNOWN: fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/4' status is noStatus. - fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/3' status is noStatus. | 'power_569'=63W;;;0; 'temp_board_569'=45C;0:75;0:79;; 'power_65'=63W;;;0; 'power_1'=63W;;;0; 'power_97'=90W;;;0;
Checking backplane
Checking chassis
chassis 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 569, admin status: powerOn] operationnal status is up.
Temperature board '569' value is 45 C.
Checking container
Checking fan
fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 2] status is notRunning.
fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 1] status is running.
fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 4] status is noStatus.
fan 'Virtual Chassis/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 3] status is noStatus.
Checking module
module 'CMM-1/CMM' [instance: 65, admin status: powerOn] operationnal status is up.
module 'NI-1/48 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 1, admin status: powerOn] operationnal status is up.
Checking other
Checking port
Checking psu
power supply 'PS-1/OS 90W AC Power Supply' [instance: 97, admin status: powerOn] operationnal status is up.
Checking sensor
Checking stack
Checking unknown

**Comment by garnier-quentin** [comment]
I understand. That's because it's missing the physical index. Should be '1' i think so:
```
--exclude="fan#1.2#"
```

I'll need to update that old code.

**Comment by garnier-quentin** [comment]
Could you test it with the new version ?

**Comment by nogomes** [comment]
Hi

I tested with the new version (also noticed that plugin has been renamed from 'network::alcatel::omniswitch::6850::plugin' to 'network::alcatel::omniswitch::snmp::plugin')

**Without filter :** 
_CRITICAL: fan '//569.2' status is notRunning UNKNOWN: fan '//569.4' status is noStatus - fan '//569.3' status is noStatus |
Checking fan
fan '/' [instance: 569.2] status is notRunning
fan '/' [instance: 569.1] status is running
fan '/' [instance: 569.4] status is noStatus
fan '/' [instance: 569.3] status is noStatus_

**With filter :** --filter=fan,569.3

_CRITICAL: fan '//569.2' status is notRunning UNKNOWN: fan '//569.4' status is noStatus |
Checking fan
fan '/' [instance: 569.2] status is notRunning
fan '/' [instance: 569.1] status is running
fan '/' [instance: 569.4] status is noStatus_

It seems to work. 

But now, how can I write my filter to exclude 569.3 and 569.4 instance ?
I tried --filter=fan,569.3,fan,569.4 but doesn't work (only 569.3 is skipped)

Regards

Norbert

**Comment by nogomes** [comment]
I found the syntax :  to exclude 569.3 and 569.4 the command is : 

--filter=fan,569.'3|4'

Regards

Norbert

**Comment by nogomes** [comment]
Just found another problem with the plugin since the update : the result code is UNKNOWN even if all checks are OK. I have also some warning messages.

$ perl centreon_plugins.pl --plugin=network::alcatel::omniswitch::snmp::plugin --mode=hardware --hostname=xxxxxx --snmp-version=v2c --snmp-community=xxxxxx  --verbose

Use of uninitialized value $name in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.
Use of uninitialized value $descr in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.
Use of uninitialized value $name in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.
Use of uninitialized value $descr in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.
Use of uninitialized value $name in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.
Use of uninitialized value $descr in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.
Use of uninitialized value $name in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.
Use of uninitialized value $descr in sprintf at /usr/lib/nagios/plugins/centreon-plugins-test/network/alcatel/omniswitch/snmp/mode/components/fan.pm line 99.

UNKNOWN: chassis 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/569' operational status is up - module 'CMM-1/CMM/65' operational status is up - module 'NI-1/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/1' operational status is up - power supply 'PS-1/OS 900W AC Power Supply/97' operational status is up | 'power_569'=67W;;;0; 'power_65'=67W;;;0; 'power_1'=67W;;;0; 'power_97'=900W;;;0;

Checking backplane
Checking chassis
chassis 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 569, admin status: powerOn] operationnal status is up.
Checking container
Checking fan
fan '/' [instance: 569.2] status is running
fan '/' [instance: 569.1] status is running
fan '/' [instance: 569.4] status is running
fan '/' [instance: 569.3] status is running
Checking module
module 'CMM-1/CMM' [instance: 65, admin status: powerOn] operationnal status is up.
module 'NI-1/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 1, admin status: powerOn] operationnal status is up.
Checking other
Checking port
Checking power supplies
power supply 'PS-1/OS 900W AC Power Supply' [instance: 97, admin status: powerOn] operationnal status is up.
Checking sensors
Checking stack
Checking unknown

Any idea ?

Regards

Norbert

**Comment by garnier-quentin** [comment]
Could you test it with the last version ?

**Comment by nogomes** [comment]
Hi

With last version, the warning messages disappeared, but the return code is always "UNKNOWN", even if all checks are OK

UNKNOWN: chassis 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/569' operational status is up - module 'CMM-1/CMM/65' operational status is up - module 'NI-1/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK/1' operational status is up - power supply 'PS-1/OS 900W AC Power Supply/97' operational status is up | 'power_569'=67W;;;0; 'power_65'=67W;;;0; 'power_1'=67W;;;0; 'power_97'=900W;;;0;
Checking backplane
Checking chassis
chassis 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 569, admin status: powerOn] operationnal status is up.
Checking container
Checking fan
fan 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 569.2] status is running
fan 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 569.1] status is running
fan 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 569.4] status is running
fan 'Virtual Chassis/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 569.3] status is running
Checking module
module 'CMM-1/CMM' [instance: 65, admin status: powerOn] operationnal status is up.
module 'NI-1/48 POE 10/100/1000 + 2 10G  + 2 1/10G STK/UPLINK' [instance: 1, admin status: powerOn] operationnal status is up.
Checking other
Checking port
Checking power supplies
power supply 'PS-1/OS 900W AC Power Supply' [instance: 97, admin status: powerOn] operationnal status is up.
Checking sensors
Checking stack
Checking unknown


Norbert

**Comment by garnier-quentin** [comment]
Sorry for the issue. It should be ok now with the last version

**Comment by nogomes** [comment]
Checked with last version, all is OK now

Thanks !

Norbert
