### ISSUE TITLE
[network::checkpoint::snmp::plugin] Retrieve max for connections mode

### ISSUE THREAD

**Issue by cgagnaire** [centreon/centreon-plugins#648]
Hi guys,
I think it could be great to use the maximum concurrent connection limit parameter to set threshold, like 80/90% of that limit. 
If set (not to "Automatically" as it will be 0) the information can be retrieved with the fwConnTableLimit OID : 1.3.6.1.4.1.2620.1.1.25.10
It could also be used as the max for the metric, 0 being the min.
This way, users could easily set threshold without knowing the defined value, and also benefit of the link load objects on Map :)
See ya!

**Comment by Sims24** [comment]
I did it somewhere ... Need to find it and I'll commit soon
