### ISSUE TITLE
fortigate Buffer creation

### ISSUE THREAD

**Issue by schmm2** [centreon/centreon-plugins#649]
Hello there

I'm trying to track my VPN traffic over my FortiGate.
I'm using the latest version of the centreon plugins.
I'm using the plugin network::fortinet::fortigate::plugin + mode vpn.
I see the status of the VPN, works well. Sadly the speed isn't displayed.
The message is always: traffic-in : Buffer creation

Any ideas where this may come from?
Thanks

**Comment by garnier-quentin** [comment]
Hi,

You use filter options no ?

**Comment by garnier-quentin** [comment]
Could you test with the fix ?

**Comment by schmm2** [comment]
holy smokes! the fastest fix ever. works as expected. 
Do you think it would be possible to get perf-data?

**Comment by garnier-quentin** [comment]
What do you mean by "get perfdata" ?

**Comment by schmm2** [comment]
As I remember Nagios and Nagios forks work with perfdata.
plugins can return perfdata. they can be printed in diagrams pnp for example.
[Link](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/perfdata.html)

**Comment by garnier-quentin** [comment]
You should have perfdata in the output after the pipe also. What do you have in output ?

**Comment by schmm2** [comment]
sadly no...guess there is a switch/parameter. close this issue. if I can't figure it out I will open another one :)
thanks for your help. awesome support

**Comment by garnier-quentin** [comment]
You're welcome. It's closed by the commit. You can open another if you need.
