### ISSUE TITLE
[hardware::pdu::apc::snmp::plugin] tenths of Amps or not

### ISSUE THREAD

**Issue by jframeau** [centreon/centreon-plugins#650]
Hi,
I'm monitoring PDUs from APC ( APC Web/SNMP Management Card (MB:v4.1.0 PF:v6.3.2 PN:apc_hw05_aos_632.bin AF1:v6.3.3 AN1:apc_hw05_rpdu2g_633.bin MN:AP8653 HR:02 )

In 'load' mode, load has to be divided per 10 as MIB says load is tenths of Amps for bank/phase.

So line 161: $result->{rPDULoadStatusLoad} /= 10;

And in outlet mode, MIB says the same : ""Getting this OID will return the measured Outlet load for an Outlet Monitored Rack PDU in tenths of Amps." for rPDUOutletStatusLoad OID.

But I don't see any division in outlet code and so get strange values for (x10) in regards to load mode.

Am I correct or I'm missing something ?

jfr

**Comment by garnier-quentin** [comment]
You're correct. Thanks!
