### ISSUE TITLE
[plugin] Lenovo / IBM Flex System Fabric EN4093R FC5022 and 2498-B/X/24

### ISSUE THREAD

**Issue by pierrick-openIT** [centreon/centreon-plugins#655]
Hi,
i could provide full snmp walk for these brand : 

- Lenovo Flex System Fabric EN4093R
- Lenovo Flex System Fabric FC5022 
- IBM SAN Switch 2498-B24
-IBM SAN Switch 2498-X24

An integration in Centreon-plugin would be so cool :)

Have a good day !

**Comment by garnier-quentin** [comment]
yes we'll need it. And the mibs also.

**Comment by pierrick-openIT** [comment]
Mibs for Lenovo Flex fabric : 
https://www.manualslib.com/manual/1087330/Lenovo-Flex-System-Fabric-Cn4093.html?page=510#manual

It look brocade fabric OS rebanding : 
http://www.brocade.com/content/dam/common/documents/content-types/mib-reference-guide/fos-800-mibref.pdf

I will send full snmpk to your email.

**Comment by pierrick-openIT** [comment]
full SNMP walk sended to your email ;)

**Comment by pierrick-openIT** [comment]
Have you receiveid my snmp walk ?

**Comment by garnier-quentin** [comment]
Yes. I don't think your walks are complete.

**Comment by pierrick-openIT** [comment]
my acces to FLEX's product on the customer site is close, I couldn't send a new walk.

**Comment by garnier-quentin** [comment]
Ok. Too bad. I close it.
