### ISSUE TITLE
apps::protocols::x509::plugin warning and critical dates

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon-plugins#656]
Hey,

When I run the plugin (--plugin=apps::protocols::x509::plugin --mode=validity) it provides output like:
OK: Certificate expiration for 'fqdn.tld' in days: 61

When adding --warning-date=50, it gives back:
WARNING: Certificate expiration for 'fqdn.tld' in days: 61

Given that the cert is valid for another 61 days, I would expect the plugin to return OK. I only want an alert when the cert is 50 days before exipring. The same goes for the critical threshold.

When adding --warning-date=62, it gives back:
OK: Certificate expiration for 'fqdn.tld' in days: 61

Given that the cert is valid for another 61 days, I would expect the plugin to return warning, since I want a warning 62 days before the expiry day.

It looks to me that the plugin has the following mechanism:
if( daysbefore > critical_argument ) exit critical
else if ( daysbefore > warning_argument ) exit warning

which I think should be:

if( daysbefore <= critical_argument ) exit critical
else if ( daysbefore <= warning_argument ) exit warning

Kind regards,
Bob

**Comment by garnier-quentin** [comment]
Hi,

Look at the faq here ;)
https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#how-can-i-set-threshold-critical-if-value--x-
