### ISSUE TITLE
hardware::server::hp::proliant::snmp::plugin return OK: All 0 components are ok [].

### ISSUE THREAD

**Issue by Gabriel-PROUST** [centreon/centreon-plugins#657]
Bonjour
J'ai un pb sur le plugin HP ProLiant qui me retourne une erreur pour certain de mes serveurs : "OK: All 0 components are ok [].".  J'utilise ce plugin pour un BL460c G1 et c'est OK, je l'utilise pour un BL460c G7 ou G8 il me retourne le message précédent ?

Pour chaque serveur je lance la même commande depuis mon serveur Centreon : 
**/usr/lib/centreon/plugins/centreon_hp_proliant.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=XXX.XXX.XXX.XXX --snmp-version='2c' --snmp-community='reniortad'  --component='cpu' --verbose**

Quelqu'un aurait une idee?
Bonne journée.
#########################################################################
Hy,
I have a pb on the HP ProLiant plugin that returns me an error for some of my servers : "OK: All 0 components are ok [].".  I use this plugin for a BL460c G1 and it's OK, I use it for a G7 BL460c or G8 returns me the previous message ?

For each server I run the same command from my server Centreon : 
**/usr/lib/centreon/plugins/centreon_hp_proliant.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=XXX.XXX.XXX.XXX --snmp-version='2c' --snmp-community='reniortad'  --component='cpu' --verbose**

Good server : 
OK: All 2 components are ok [2/2 cpus]. |
Product Name: ProLiant BL460c G1, Serial: CZJxxxxxxx, Rom Version: 05/02/2011, Family I15
Checking cpu
cpu '0' [slot: 0, unit: 0, name: Intel Xeon, socket: 1] status is ok.
cpu '1' [slot: 0, unit: 0, name: Intel Xeon, socket: 2] status is ok.

Bad server
OK: All 0 components are ok []. |
Product Name: unknown, Serial: unknown, Rom Version: unknown
Checking cpu

Someone have an idea?
Good day.

**Comment by garnier-quentin** [comment]
Hi,

I don't think it's a plugin problem. Maybe an snmp hp insight agent issue. Your hp configuration in the OS is ok ?

**Comment by Gabriel-PROUST** [comment]
Since the Centreon server the snmpwalk is OK for the twice servers. (sorry for my English)

**Comment by garnier-quentin** [comment]
On the twice, you have information in following branch: .1.3.6.1.4.1.232 ?

**Comment by Gabriel-PROUST** [comment]
OK i have a pb on on the G7 server. 
snmpwalk -Cc -On -v 2c -c reniortad 172.19.1.80 .1.3.6.1.4.1.232
.1.3.6.1.4.1.232 = No Such Object available on this agent at this OID

Not on th G1 serveur : 
 snmpwalk -Cc -On -v 2c -c reniortad 172.19.1.106 .1.3.6.1.4.1.232 | more
.1.3.6.1.4.1.232.1.1.1.0 = INTEGER: 1
.1.3.6.1.4.1.232.1.1.2.0 = INTEGER: 32
.1.3.6.1.4.1.232.1.1.3.0 = INTEGER: 2
.1.3.6.1.4.1.232.1.2.1.4.1.0 = INTEGER: 30
.1.3.6.1.4.1.232.1.2.1.4.2.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.232.1.2.1.4.2.1.2.1 = STRING: "HP Standard Equipment Agent for Linux"
.1.3.6.1.4.1.232.1.2.1.4.2.1.3.1 = ""
.1.3.6.1.4.1.232.1.2.1.4.2.1.4.1 = Hex-STRING: 00 00 00 00 00 00 00
.1.3.6.1.4.1.232.1.2.1.4.2.1.5.1 = STRING: "To gather Standard Equipment data for Linux."
.1.3.6.1.4.1.232.1.2.2.1.1.1.0 = INTEGER: 0
.1.3.6.1.4.1.232.1.2.2.1.1.1.1 = INTEGER: 1
.1.3.6.1.4.1.232.1.2.2.1.1.2.0 = INTEGER: 0
.1.3.6.1.4.1.232.1.2.2.1.1.2.1 = INTEGER: 0
.1.3.6.1.4.1.232.1.2.2.1.1.3.0 = STRING: "Intel Xeon"
.1.3.6.1.4.1.232.1.2.2.1.1.3.1 = STRING: "Intel Xeon"
.1.3.6.1.4.1.232.1.2.2.1.1.4.0 = INTEGER: 3000
....

So it's on my snmp configuration the pb ? Or in HP SMH ?

**Comment by Gabriel-PROUST** [comment]
i have a difference between my server 3 package missing : hpssacli hpssa hpssaducli
I try to install it and test, i'll be back lol

**Comment by garnier-quentin** [comment]
Can be HP snmp agent or the main snmp agent.

**Comment by Gabriel-PROUST** [comment]
Just for solve this pb. I have use this command on my bad server : "hpsnmpconfig" and i have reconfigure my snmpd.conf whit it. AND THAT WORK'S. thank for the help. Have a nice day. bye

**Comment by garnier-quentin** [comment]
Thanks for the feedback. Glad it works!
