### ISSUE TITLE
netapp mode filesys pourcentage 594 %

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#658]
Hello,

With the plugin "ces-plugins-Hardware-Storage-Netapp-Snmp-2.4-1.noarch" the ouput display a usage pourcentage of more than 100%:

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname 10.9.162.72 --snmp-version='2' --snmp-community='Pr79my_mai&&' --filter-name='(NVVP_A_itesoft.*$)' --warning-usage='80' --critical-usage='90' --warning-inodes='80' --critical-inodes='90' --units='%' --verbose --filter-perfdata='used|inodes'

CRITICAL: Filesys '/vol/NVVP_A_itesoft/.snapshot' Total: 10.00 GB Used: 
59.65 GB (596.49%) Free: 0.00 B (0.00%) | 
'used_/vol/NVVP_A_itesoft'=157726568448B;0:163208757248;0:183609851904;0;204010946560 
'inodes_/vol/NVVP_A_itesoft'=15%;0:80;0:90;0;100 
'used_/vol/NVVP_A_itesoft/.snapshot'=64048144384B;0:8589934592;0:9663676416;0;10737418240 
'inodes_/vol/NVVP_A_itesoft/.snapshot'=0%;0:80;0:90;0;100
Filesys '/vol/NVVP_A_itesoft' Total: 190.00 GB Used: 146.89 GB (77.31%) 
Free: 43.11 GB (22.69%), Inodes Used : 15 %
Filesys '/vol/NVVP_A_itesoft/.snapshot' Total: 10.00 GB Used: 59.65 GB 
(**596.49**%) Free: 0.00 B (0.00%), Inodes Used : 0 %

The file system with the problem is"/vol/NVVP_A_itesoft/.snapshot":

-bash-4.1$ snmpwalk -v2c 10.9.162.72 -c 'Pr79my_mai&&' 
.1.3.6.1.4.1.789.1.5.4.1.2 |grep 'A_itesoft'
SNMPv2-SMI::enterprises.789.1.5.4.1.2.1690 = STRING: "/vol/NVVZ_A_itesoft"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.1691 = STRING: 
"/vol/NVVZ_A_itesoft/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.1692 = STRING: "/vol/NVVP_A_itesoft"
SNMPv2-SMI::enterprises.789.1.5.4.1.2.1693 = STRING: 
"/vol/NVVP_A_itesoft/.snapshot"
-bash-4.1$
-bash-4.1$ snmpwalk -v2c 10.9.162.72 -c 'Pr79my_mai&&' 
.1.3.6.1.4.1.789.1.5.4.1 | grep 1693
SNMPv2-SMI::enterprises.789.1.5.4.1.2.1693 = STRING: 
"/vol/NVVP_A_itesoft/.snapshot"
SNMPv2-SMI::enterprises.789.1.5.4.1.3.1693 = INTEGER: 10485760
SNMPv2-SMI::enterprises.789.1.5.4.1.4.1693 = INTEGER: 67512644
SNMPv2-SMI::enterprises.789.1.5.4.1.9.1693 = INTEGER: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.29.1693 = Counter64: 10485760
SNMPv2-SMI::enterprises.789.1.5.4.1.30.1693 = Counter64: 67514084
SNMPv2-SMI::enterprises.789.1.5.4.1.38.1693 = INTEGER: 0
SNMPv2-SMI::enterprises.789.1.5.4.1.40.1693 = INTEGER: 0

You can find attached the oid .1.3.6.1.4.1.789.1.5.4.1

**Comment by garnier-quentin** [comment]
The last version is used ?

**Comment by tseegers** [comment]
Hello,

Yes the problem is still present after the upgrade to the last version of the plugin

**Comment by garnier-quentin** [comment]
I can't do nothing on my side. Netapp should add a 'maxValue' to limit snapshot size.
