### ISSUE TITLE
[storage::dell::compellent::local::plugin] How to use this module (UNKNOWN: Need to specify --sdk-path-dll option.)

### ISSUE THREAD

**Issue by DorianBoby** [centreon/centreon-plugins#659]
Hello I want to use this plugin like : 
`./centreon_plugins.pl --plugin=storage::dell::compellent::local::plugin --mode=volume-usage --cem-host <@IP> --cem-user 'admin' --cem-password 'P@ssword'`

I want to monitor a Dell Compellent, the SNMP is not complete, I try the "local"

But its return UNKNOWN: Need to specify --sdk-path-dll option.
The help of this option is "Path to 'DellStorage.ApiCommandSet.dll' (Required)." But It's not very clear.

When I do the command : 
`./centreon_plugins.pl --plugin=storage::dell::compellent::local::plugin --help`

Its say to have "Dell Storage PowerShell SDK". 
We need "Dell Storage PowerShell SDK installed" on Linux?

**Comment by Sims24** [comment]
Hi, 

This plugin meant to be used locally on your server hosting the "Dell Enterprise Storage Manager" plugin. From what I've seen it's always a windows host. 

Anyway code of this plugin is powershell so to make it work you will use an agent like NSClient++ to execute it through NRPE or NSCA and get the result in Centreon. You can find a documentation about building your own centreon_plugins.exe here : 

https://documentation.centreon.com/docs/centreon-nsclient/en/latest/windows_agent.html#build-your-own-executable

Thanks

**Comment by DorianBoby** [comment]
Thank you very much for your complete answer. 
I'll Try this. 

Will a complete help be written officially for each plugin?

**Comment by garnier-quentin** [comment]
There is a rest api in last version of the storage manager. We'll use that and it will be easier ;)

**Comment by DorianBoby** [comment]
@garnier-quentin , If I understand correctly I should wait for an additional development of the project "Centreon-plugin"?

**Comment by garnier-quentin** [comment]
You can work with the current. But in future, we'll develop another way to monitor.
