### ISSUE TITLE
[printers][standard] impressions on Ricoh printers : unit not managed

### ISSUE THREAD

**Issue by EChauve** [centreon/centreon-plugins#66]
Command :
--plugin=hardware::printers::standard::rfc3805::plugin --mode=marker-impression --verbose

Result :
OK: Marker impressions are ok. |
Skipping marker '1#1' : unit not managed.

I have tried the command on several models (5 different models, 7 printers) of Ricoh printers and got the same issue each time. I had the same issue with a Lexmark also but I only got one, not enough to identify a pattern.

Otherwise it is working fine on my 42 other printers of different brands and models.

Quentin Garnier asked :
"Moreover for ricoh, it's only 'marker-impression' mode ? Or other modes doesn't work also. Could you get a specific mib for ricoh ? Could give a snmpwalk result for ricoh printers ?"

All other modes are working fine.
I don't have a specific MIB (did not look for one yet), but isn't RFC3805 supposed to avoid specific MIBs?
SNMPWALK on ricoh : https://gist.github.com/EChauve/01841198e0245cc93be6

**Comment by garnier-quentin** [comment]
Yes it's. But sometimes they don't respect it (or implement it no well). I'll look about the walk. Thanks!!

**Comment by garnier-quentin** [comment]
Could you give me also the snmpwalk for the standard on ricoh ? (maybe they implement it no well).

**Comment by garnier-quentin** [comment]
Could you get me RicohPrivateMib ? (the file is on ricoh support interface) Thanks

**Comment by EChauve** [comment]
I'll get you the snmpwalk for sure, but currently being a trainee, I am not sure I will be able to get the RicohPrivateMib (but I'll try). Thank for looking into this issue but don't overdo it, it's still a very minor issue ^^.

**Comment by EChauve** [comment]
Snmpwalk for standard printer MIB on Ricoh printer : 
https://gist.github.com/EChauve/8eb5aa7dc04146440a92

**Comment by garnier-quentin** [comment]
Maybe it is in standard mibs. For maker-impressions, i only check with prtMarkerCounterUnit = 'impressions' (7). But maybe, i should use 'sheets' (8) also.

**Comment by garnier-quentin** [comment]
'impressions(7)' (single page sides) or  'sheets(8)' (single- or two-sided pages). I can manage it so.
I want use the same perfdata so.

**Comment by garnier-quentin** [comment]
Could you test now with the fix please ?

**Comment by EChauve** [comment]
Great success!

**Comment by garnier-quentin** [comment]
Thanks for your feedback!

**Comment by EChauve** [comment]
You're welcome, thank you for the GREAT plugin.

**Comment by EChauve** [comment]
Hey, just noticed something : as the metric is called "sheets" for Ricoh printers, I can't add it to my "impressions" in my totalImpressions meta-service. Can you rename it?

Though as those two metrics do not define exactly the same things, I understand the difference between a page and a sheet, I would understand if you would rather not do this, could you then tell me how I could do it on my own?

**Comment by garnier-quentin** [comment]
No i can't. because it's not the same things. But for you can rename it with the option: --change-perfdata
--change-perfdata='sheets,impressions'

**Comment by EChauve** [comment]
Ah, nice functionality, I don't even need to dirty my hands! Thank you for answering me on such a personal matter.

**Comment by garnier-quentin** [comment]
With pleasure.
