### ISSUE TITLE
network::fortinet::fortigate Interface "Up" is displayed "down"

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#660]
Hello, 

With the latests version of the plugins (20161212) an interface is shown "Down" in Centreon but seems to be "Up" in the Oid:

/usr/lib/centreon/plugins/centreon_fortinet_fortigate.pl --plugin=network::fortinet::fortigate::plugin --mode=interfaces --hostname=10.0.0.6 --snmp-version='2c' --snmp-community='xxx!' --interface='.*' --name --add-traffic --add-status --verbose

[...] Interface 'wan1' Status : down (admin: down) [...]

But when we perform a snmpwalk on the equipement we can read this:

IF-MIB::ifDescr.1 = STRING: wan1
IF-MIB::ifAdminStatus.1

I can send the complete snmpwalk if needed.

**Comment by garnier-quentin** [comment]
Yes i'll need the snmpwalk

**Comment by tseegers** [comment]
Thank you, i have just sent it to you by email.

**Comment by garnier-quentin** [comment]
It seems it's a firewall issue. Because:
```
# snmpget -On -c 'xxxxxx' -v 2c 10.105.38.6 .1.3.6.1.2.1.2.2.1.7.1 .1.3.6.1.2.1.2.2.1.7.2
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: down(2)
.1.3.6.1.2.1.2.2.1.7.2 = INTEGER: up(1)
# snmpbulkwalk -On -c 'xxx' -v 2c 10.105.38.6 ifadmin  
.1.3.6.1.2.1.2.2.1.7.1 = INTEGER: up(1)
.1.3.6.1.2.1.2.2.1.7.2 = INTEGER: up(1)
.1.3.6.1.2.1.2.2.1.7.3 = INTEGER: down(2)
....
```
