### ISSUE TITLE
warning at /usr/lib/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 67.

### ISSUE THREAD

**Issue by charlietangocharlie** [centreon/centreon-plugins#661]
Dear all,

I have an issue using the bluecoat plugin. I'm monitoring using all the plugin mode, and 2 are not working:
first command is 
	
$USER1$/centreon_plugins.pl --plugin=network::bluecoat::snmp::plugin --mode=$ARG1$ --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-username=$_SERVICEEXTRAOPTIONS$ --warning=$_SERVICEWARNING$ --critical=$_SERVICECRITICAL$

in case 1 : with $ARG1$=client-requests
in case 2 : with $ARG1$=client-traffic

the result is an error message:
Unknown option: warning at /usr/lib/nagios/plugins/centreon/plugins/alternative/Getopt.pm line 67.

I don't know the option that is mentionned in the error message, can you help ? anyone face the same error ?

**Comment by Sims24** [comment]
Hello, 

You might get help from the plugin itself :) 

client-requests : 

```
=item B<--warning-*>
Threshold warning.
Can be: errors (%), hits (%), partial-hits (%), misses (%).
=item B<--critical-*>
Threshold critical.
Can be: errors (%), hits (%), partial-hits (%), misses (%).
```

So define warning and critical as you need e.g : 
`--warning-hits X% --critical-misses X%`


Same for client-traffic : 
```
=item B<--warning-received>
Threshold warning for received (in bytes/s).
=item B<--critical-received>
Threshold critical for received (in bytes/s).
=item B<--warning-delivered>
Threshold warning2 for delivered (in bytes/s).
=item B<--critical-delivered>
Threshold critical for delivered (in bytes/s).
```

Hope this help, 
Thanks

**Comment by charlietangocharlie** [comment]
Hello sims24 !

thanks for this prompt reply. 

I confirm this is working ! thanks a lot ! I was not aware about this ^^'

Community power !

**Comment by Sims24** [comment]
Roger that. Thanks for using it.
