### ISSUE TITLE
storage::hp::p2000::xmlapi::plugin --mode=volume-stats no volume found

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#663]
Hello,

With the latest version of the plugin, i don't succeed to get any volume.

/usr/lib/centreon/plugins/centreon_hp_p2000.pl --plugin=storage::hp::p2000::xmlapi::plugin --mode=volume-stats --custommode=p2000xml --hostname=172.16.0.1 --port='80' --proto='http' --username='centreon' --password='centreon' --name='.*'
UNKNOWN: No volume found for name '.*'.

The list-volume mode doesn't display any volume nether:
/usr/lib/centreon/plugins/centreon_hp_p2000.pl --plugin=storage::hp::p2000::xmlapi::plugin --mode=list-volumes --custommode=p2000xml --hostname=172.16.0.1 --port='80' --proto='http' --username='centreon' --password='centreon' --verbose
List volumes:

The user centreon has been created and on host graphic interface we can see the list of the volumes:
![image001](https://cloud.githubusercontent.com/assets/13485588/25950297/bc9fe8f0-365a-11e7-9dc8-13be023e7f2e.png)

**Comment by mickael-decastro** [comment]
+1
