### ISSUE TITLE
centreon_plugins.pl --plugin=network::f5::bigip::snmp::plugin

### ISSUE THREAD

**Issue by charlietangocharlie** [centreon/centreon-plugins#668]
Dear all,

I'm having issue monitoring f5 VirtualServerStatus

using command :
**/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::f5::bigip::snmp::plugin --mode=virtualserver-status --hostname=1.2.3.4 --snmp-version=3 --snmp-username=testf5 --filter-name=/Common/VS_Name**

output is **UNKNOWN: SNMP Table Request : Timeout**

doing a TCPdump, I can see that the script is requesting 6 OIDs in one request.
=> using SNMPv3, it's not working, 4 is the maximum
=> using SNMPv2, it's working there's no limit I've found.

This is valuable for F5 version 11, 12 and 13
Is there a way to split the OID per request ?

Best regards !

**Comment by garnier-quentin** [comment]
Of course you can ;)
```
--subsettable=1 --snmp-force-getnext
````

**Comment by garnier-quentin** [comment]
You can put your feedback and tell us if it's working with options above
