### ISSUE TITLE
[hardware::server::hp::ilo::xmlapi::plugin] - BIOS_HARDWARE STATUS= "Failed"

### ISSUE THREAD

**Issue by vurmil** [centreon/centreon-plugins#669]
OK: All 89 components are ok [1/1 cpu, 1/1 ctrl, 2/2 driveencl, 4/4 fans, 3/3 ldrive, 24/24 memory, 6/6 pdrive, 2/2 psu, 46/46 temperatures]. 

![image](https://cloud.githubusercontent.com/assets/15263415/26046333/c631fd9e-394e-11e7-89f0-69f7e17f285e.png)

https://pastebin.com/BZiGd5PD

in XML:
<BIOS_HARDWARE STATUS= "Failed"/>

**Comment by garnier-quentin** [comment]
Thanks. I'll add it.

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by vurmil** [comment]
The plugin works great - Thanks!

**Comment by garnier-quentin** [comment]
Thanks for your feedback
