### ISSUE TITLE
Synology Storage cache issue

### ISSUE THREAD

**Issue by matthieu-robin** [centreon/centreon-plugins#67]
Hello,

I'm currently testing the synology plugin, and unfortunately, I got this message error for the diskusage mode:

./centreon_plugins.pl --plugin=storage::synology::plugin --mode=diskusage --hostname=192.168.0.40
UNKNOWN: Can't construct cache...

I'm on CES 3.1 update onto Centreon 2.6.1

Thanks in advance.

**Comment by garnier-quentin** [comment]
Hi,

Could you do a walk of '.1.3.6.1.4.1.2021.9.1.2' ?

**Comment by matthieu-robin** [comment]
Unfortunately, no answerr.
>[root@centreon centreon-plugins]# snmpwalk -v 1 -c public 192.168.0.40 .1.3.6.1.4.1.2021.9.1.2
>[root@centreon centreon-plugins]# 

I have checked the Synology doc here: https://global.download.synology.com/download/Document/MIBGuide/Synology_DiskStation_MIB_Guide.pdf

and I can make other requests:
>[root@centreon centreon-plugins]# snmpwalk -v 1 -c public 192.168.0.40 .1.3.6.1.4.1.6574.2 
>SNMPv2-SMI::enterprises.6574.2.1.1.2.0 = STRING: "Disk 1"
>SNMPv2-SMI::enterprises.6574.2.1.1.2.1 = STRING: "Disk 2"
>SNMPv2-SMI::enterprises.6574.2.1.1.2.2 = STRING: "Disk 3"
>SNMPv2-SMI::enterprises.6574.2.1.1.2.3 = STRING: "Disk 4"
>SNMPv2-SMI::enterprises.6574.2.1.1.3.0 = STRING: "WD30EFRX-68EUZN0        "
>SNMPv2-SMI::enterprises.6574.2.1.1.3.1 = STRING: "WD30EFRX-68AX9N0        "
>SNMPv2-SMI::enterprises.6574.2.1.1.3.2 = STRING: "WD30EFRX-68AX9N0        "
>SNMPv2-SMI::enterprises.6574.2.1.1.3.3 = STRING: "WD30EFRX-68AX9N0        "
>SNMPv2-SMI::enterprises.6574.2.1.1.4.0 = STRING: "SATA"
>SNMPv2-SMI::enterprises.6574.2.1.1.4.1 = STRING: "SATA"
>SNMPv2-SMI::enterprises.6574.2.1.1.4.2 = STRING: "SATA"
>SNMPv2-SMI::enterprises.6574.2.1.1.4.3 = STRING: "SATA"
>SNMPv2-SMI::enterprises.6574.2.1.1.5.0 = INTEGER: 1
>SNMPv2-SMI::enterprises.6574.2.1.1.5.1 = INTEGER: 1
>SNMPv2-SMI::enterprises.6574.2.1.1.5.2 = INTEGER: 1
>SNMPv2-SMI::enterprises.6574.2.1.1.5.3 = INTEGER: 1
>SNMPv2-SMI::enterprises.6574.2.1.1.6.0 = INTEGER: 35
>SNMPv2-SMI::enterprises.6574.2.1.1.6.1 = INTEGER: 36
>SNMPv2-SMI::enterprises.6574.2.1.1.6.2 = INTEGER: 36
>SNMPv2-SMI::enterprises.6574.2.1.1.6.3 = INTEGER: 36

**Comment by Shini31** [comment]
Hello,

Diskusag mode is not functional.  If you want to check the partitions, you can use storage mode in the linux section.

Regards.

**Comment by matthieu-robin** [comment]
Great! Thanks a lot both!
Maybe, you can remove this mode on this plugin, no? thanks a lot

**Comment by Shini31** [comment]
#70  :)
