### ISSUE TITLE
[os::linux::snmp::plugin] more units traffic 

### ISSUE THREAD

**Issue by DorianBoby** [centreon/centreon-plugins#670]
Hello, 

I use the plugin os::linux::snmp::plugin with mode interfaces. I my exemple want to have alerts when the router have a out traffic higher than 4mb/s . 
The command is : 
`.../centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=@IP --interface=1 --add-traffic  --critical-out-traffic=$_SERVICECRITOUT$ --units-traffic='$_SERVICEUNIT$' `

For my router I should add to the argument **--critical-out-traffic** the value "**4000000**"b/s .
But I want write "**4**" mb/s
When i show the **--help**, 

> 
> --units-traffic
>             Units of thresholds for the traffic (Default: '%') ('%', 'b/s').

I tried the value 'mb/s' but its not recognized.

Are there any other solutions? 
(the "%" force me to use --speed-in and --speed-out, its too much arguments)

**Comment by garnier-quentin** [comment]
it's a duplicate ticket: #79
It's quite a big change.

**Comment by DorianBoby** [comment]
My Bad

**Comment by garnier-quentin** [comment]
It's not a problem :)
