### ISSUE TITLE
apps::vmware::connector::plugin - is not critical for unknown disk statut

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#673]
Hello,

An esx server have a disk ko. In vmware, disk is not in critical state, but in unknown status.

connector plugin does not see this status ??

OK: 'myhost' 142 health checks are green | 'problems'=0;;;0;142

Thanks,

**Comment by garnier-quentin** [comment]
Could you give the verbose details ?

**Comment by romsworld** [comment]
there are no detail :(

[root@ centreon-plugins]# /usr/local/nagios/libexec/centreon-plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=xxxxxx --container=vvc-01 --mode=health-host --esx-hostname=xxxxxx --verbose --debug
OK: xxxxxxx142 health checks are green | 'problems'=0;;;0;142
Checking xxxxxxxxxxxx
142 health checks are green

**Comment by garnier-quentin** [comment]
Indeed. Could you update the code in vmware connector to display a debug. I think the '->status->key' is gray maybe (not yellow or red).

**Comment by romsworld** [comment]
Hum, i don't find status parameters, what is the file ?

**Comment by garnier-quentin** [comment]
The file is cmdhealthhost.pm.

**Comment by romsworld** [comment]
I don't find where enable Debug ? which file ?

Exactly, in cmdhealthhost, there are yellow and red

**Comment by garnier-quentin** [comment]
There is no debug system. You should add a print directly in the code.

**Comment by romsworld** [comment]
Ok, je le fais en vf, ca sera plus compréhensible.
Le status hardware du serveur en question fonctionne, et un disk est en etat inconnu. 
J'ai fais le script en débug, c'est étrange, car je n'ai aucune remonté disque via le script centreon pour ce server. par contre pour les autres, cela fonctionne.
Je ne comprends pas comment les api de vmware ne remonte pas d'info sur le status, alors que c'est afficher via la console vmware. Etrange.
Du coup, le probleme n'est pas un probleme d'interpretation green/yellow etc, mais d'une information qui n'est pas remontée via votre script/ ou via api vmware.
Dans tous les cas, cela fonctionne avec le script ops

CHECK_VMWARE_API.PL OK - 1 health issue(s) found in 153 checks:
1) UNKNOWN[Storage] Status of Disk 4 on HPSA1 : Port 1I Box 1 Bay 4 : 136GB : Data Disk: Cannot report on the current status of the physical element | Alerts=1;;

**Comment by garnier-quentin** [comment]
check_vmware_api does like that:
```
my $res = UNKNOWN;

	if (uc($state) eq "GREEN") {
		$res = OK
	} elsif (uc($state) eq "YELLOW") {
		$res = WARNING;
	} elsif (uc($state) eq "RED") {
		$res = CRITICAL;
	}
```

So by default, it's unknown. But i would like to know the real value.
