### ISSUE TITLE
Modify pbxrole.pm in network::alcatel::oxe::snmp::plugin

### ISSUE THREAD

**Issue by Hellnino18** [centreon/centreon-plugins#674]
Hi, 

There is a little typo in the pbxrole.pm fil at the end.

In the help : 

Set to overload default threshold values (syntax: section,status,regexp)
It used before default thresholds (order stays).
Example: --threshold-overload='state,CRITICAL,^(?!(main)$)'

should be : 

Set to overload default threshold values (syntax: section,status,regexp)
It used before default thresholds (order stays).
Example: --threshold-overload='role,CRITICAL,^(?!(main)$)'

"role" not "state".

Thanks ;)

**Comment by garnier-quentin** [comment]
Thanks!

**Comment by Hellnino18** [comment]
Thanks to you ! Too much work for a PR for only this change :D
