### ISSUE TITLE
[apps::tomcat::jmx::plugin] mode cpu-load - JMX Request: Cant get a single value.

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#675]
Hi,
I use Jolokia 1.3.5 to monitor tomcat7 (v 7.0.37 exactly) and i receive a Unknown status with this message:
JMX Request: Cant get a single value.

It seems to appear only with tomcat 32bits.
thanks.

**Comment by cmeschin** [comment]
yes

**Comment by garnier-quentin** [comment]
Some modes are only on Linux Tomcat.

**Comment by cmeschin** [comment]
Yes, but this mode is functionnal an tomcat7 windows 64bits.

**Comment by garnier-quentin** [comment]
Look in the mbeans if there is a value. Otherwise you should ask to tomcat maybe.

**Comment by cmeschin** [comment]
ok thanks.
