### ISSUE TITLE
h3c - notSupported - sensor

### ISSUE THREAD

**Issue by keponcutre** [centreon/centreon-plugins#676]
# Good morning,
I'm monitoring two "HP A5820AF-24XG Switch" they are h3c product.
When I'm monitoring the temperature(sensor) with the centreon-plugins.pl. It feed back temperature and an "notSupported" message. So the plugins says "WARNING".
here is a screenshot of the issue :
![image](https://cloud.githubusercontent.com/assets/27009582/26341113/48fe5364-3f92-11e7-86b9-6bf4542c09d9.png)

**Comment by Sims24** [comment]
Hi @keponcutre,

You can fix this with --threshold-overload='sensor,OK,notSupported' 

Thanks

**Comment by keponcutre** [comment]
## It works, thank you.
### May we replace "section" by "component" and add a list of statuses and regular expression.
I use to try with weird expressions that make no sense to me now.
to give you an accurate view of what i mistaken :
![image](https://cloud.githubusercontent.com/assets/27009582/26345918/be24bd06-3fa4-11e7-8a78-0022f805cf60.png)

**Comment by Sims24** [comment]
Ok, I see. 

`--threshold-overload` will only and forever act on text statuses, not on "absolute" value like a temp value etc ..

But I understand the confusion and your point between "section" and "components", as it is only help text and would help to make a link between `--component` and `--threshold-overload` options, 

What you think about it @garnier-quentin ?

**Comment by garnier-quentin** [comment]
It have done that between section and components because equipments are complex in the way they manage entities.
