### ISSUE TITLE
[network::h3c] mode=hardware --absent-problem

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#678]
Hello,

I've tried --absent-problem option for this mode with an absent module and it's always OK !

/usr/lib/centreon/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::h3c::snmp::plugin --mode=hardware --hostname=10..X.X.X [...] --verbose --no-component --absent-problem=backplane
OK: All 47 components are ok [1/1 chassis, 8/8 container, 2/2 fans, 2/2 module, 30/30 port, 1/1 power supplies, 2/2 sensors, 1/1 stack]. | 'temp_87'=40C;;~:65;; 'temp_88'=45C;;~:112;;
Checking power supplies
...
Checking other
Checking backplane
Checking port
...

Did i misunderstood something ?

**Comment by Sims24** [comment]
Hi, 

Could you copy/paste entire output with --verbose and without --absent-problem to see all the component  detected. 

Merci,
Simon

**Comment by ritouret** [comment]
Bonjour Simon,

Here is the entire output with --verbose and without --absent-problem :

OK: All 47 components are ok [1/1 chassis, 8/8 container, 2/2 fans, 2/2 module, 30/30 port, 1/1 power supplies, 2/2 sensors, 1/1 stack]. | 'temp_87'=37C;;~:65;; 'temp_88'=43C;;~:112;;
Checking power supplies
Power supply 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > PSU' status is 'normal' [instance = 83]
Checking stack
stack 'HP' status is 'normal' [instance = 1]
Checking chassis
chassis 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99' status is 'normal' [instance = 2]
Checking fans
Fan 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > FAN UNIT' status is 'normal' [instance = 85]
Fan 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > FAN UNIT' status is 'normal' [instance = 86]
Checking module
module 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2' status is 'normal' [instance = 162]
module 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1' status is 'normal' [instance = 82]
Checking cpu
Checking unknown
Checking sensors
Sensor 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > SENSOR' status is 'normal' [instance = 87]
Sensor 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > SENSOR' status is 'normal' [instance = 88]
Checking other
Checking backplane
Checking port
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/1' status is 'normal' [instance = 172]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/2' status is 'normal' [instance = 173]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/3' status is 'normal' [instance = 174]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/4' status is 'normal' [instance = 175]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/5' status is 'normal' [instance = 176]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/6' status is 'normal' [instance = 177]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/7' status is 'normal' [instance = 178]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/8' status is 'normal' [instance = 179]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/9' status is 'normal' [instance = 180]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/10' status is 'normal' [instance = 181]
port 'HP > HP A3600-24-PoE+ v2 EI Switch Software Version 5.20.99 > CONTAINER LEVEL1 > MODULE LEVEL1 > CONTAINER LEVEL2 > MODULE LEVEL2 > Ethernet1/0/11' status is 'normal' [instance = 182]

**Comment by garnier-quentin** [comment]
What do you want to do exactly ?

**Comment by garnier-quentin** [comment]
I close the issue. We could look that next week.

**Comment by ritouret** [comment]
--absent-problem=backplane
should return CRITICAL if there was 0/1 backplane.

Here, there is no backplane in output (and in SNMP agent).
solved with these options : 
--filter=backplane --no-component
