### ISSUE TITLE
network/paloalto/snmp/plugin.pm memory usage

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#679]
Hi,

Could you please add memory check mode to Palo Alto Firewalls.
Thanks in advance!

**Comment by Sims24** [comment]
Hi, 

Did you try to use the Linux one ? 

Thanks,

**Comment by garnier-quentin** [comment]
There is nothing in palo alto mib for snmp. If you have an OID for that, please attach the snmpwalk and the mib

**Comment by kadrika** [comment]
Hi, 
I some how did not notice you replied to this, sorry about that.
The OIDs I use are: 1.3.6.1.2.1.25.2.3.1.5.20,1.3.6.1.2.1.25.2.3.1.6.20  size,used
Here is the SNMPWalk:
-bash-4.1$ snmpwalk 1.2.3.4 -v2c -c xxx 1.3.6.1.2.1.25.2.3
HOST-RESOURCES-MIB::hrStorageIndex.20 = INTEGER: 20
HOST-RESOURCES-MIB::hrStorageIndex.30 = INTEGER: 30
HOST-RESOURCES-MIB::hrStorageIndex.40 = INTEGER: 40
HOST-RESOURCES-MIB::hrStorageIndex.41 = INTEGER: 41
HOST-RESOURCES-MIB::hrStorageIndex.42 = INTEGER: 42
HOST-RESOURCES-MIB::hrStorageIndex.1010 = INTEGER: 1010
HOST-RESOURCES-MIB::hrStorageIndex.1011 = INTEGER: 1011
HOST-RESOURCES-MIB::hrStorageIndex.1012 = INTEGER: 1012
HOST-RESOURCES-MIB::hrStorageType.20 = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageType.30 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.40 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.41 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.42 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.1010 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.1011 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.1012 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageDescr.20 = STRING: Slot-0 Management Memory
HOST-RESOURCES-MIB::hrStorageDescr.30 = STRING: Slot-0 Management Swap
HOST-RESOURCES-MIB::hrStorageDescr.40 = STRING: Slot-0 Management Config Partition
HOST-RESOURCES-MIB::hrStorageDescr.41 = STRING: Slot-0 Management Log Partition
HOST-RESOURCES-MIB::hrStorageDescr.42 = STRING: Slot-0 Management Root Partition
HOST-RESOURCES-MIB::hrStorageDescr.1010 = STRING: Slot-1 Data Processor-0 Packet Descriptors
HOST-RESOURCES-MIB::hrStorageDescr.1011 = STRING: Slot-1 Data Processor-0 Hardware Packet Buffers
HOST-RESOURCES-MIB::hrStorageDescr.1012 = STRING: Slot-1 Data Processor-0 Software Packet Buffers
HOST-RESOURCES-MIB::hrStorageAllocationUnits.20 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.30 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.40 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.41 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.42 = INTEGER: 1024 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1010 = INTEGER: 128 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1011 = INTEGER: 2048 Bytes
HOST-RESOURCES-MIB::hrStorageAllocationUnits.1012 = INTEGER: 5470 Bytes
HOST-RESOURCES-MIB::hrStorageSize.20 = INTEGER: 3850944
HOST-RESOURCES-MIB::hrStorageSize.30 = INTEGER: 2008084
HOST-RESOURCES-MIB::hrStorageSize.40 = INTEGER: 7882560
HOST-RESOURCES-MIB::hrStorageSize.41 = INTEGER: 93429028
HOST-RESOURCES-MIB::hrStorageSize.42 = INTEGER: 3945160
HOST-RESOURCES-MIB::hrStorageSize.1010 = INTEGER: 229376
HOST-RESOURCES-MIB::hrStorageSize.1011 = INTEGER: 57344
HOST-RESOURCES-MIB::hrStorageSize.1012 = INTEGER: 168240
HOST-RESOURCES-MIB::hrStorageUsed.20 = INTEGER: 2146512
HOST-RESOURCES-MIB::hrStorageUsed.30 = INTEGER: 113984
HOST-RESOURCES-MIB::hrStorageUsed.40 = INTEGER: 4411800
HOST-RESOURCES-MIB::hrStorageUsed.41 = INTEGER: 53078104
HOST-RESOURCES-MIB::hrStorageUsed.42 = INTEGER: 2096472
HOST-RESOURCES-MIB::hrStorageUsed.1010 = INTEGER: 68
HOST-RESOURCES-MIB::hrStorageUsed.1011 = INTEGER: 130
HOST-RESOURCES-MIB::hrStorageUsed.1012 = INTEGER: 15

**Comment by Sims24** [comment]
@kadrika looks like similar to Windows way of retrieving memory as storage. You should probably be able to check it thanks to storage mode with a filter on "Management Memory'. 

These are standard OIDs and not palo alto specific
