### ISSUE TITLE
network::cisco::2900::plugin output incorrect

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#68]
Hi,
When using plugin network::cisco::2900::plugin and mode environment the output is like this:
OK: All 3 components [1 fans, 1 power supplies, 1 temperatures, 0 voltages] are ok, Environment type: c37xx
That last part - type is incorrect.

Because the switch where I am asking this is for sure: Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.0(2a)EX5, RELEASE SOFTWARE (fc3)

**Comment by garnier-quentin** [comment]
I think it gives me the information about 37xx.
Could you do a walk of '1.3.6.1.4.1.9.9.13.1.1.0' ? and give me the result pleasae.

**Comment by kadrika** [comment]
Result is:

SNMPv2-SMI::enterprises.9.9.13.1.1.0 = INTEGER: 13

Best regards/ Parimate soovidega,
Kadri Kalpus
NOC Monitoring Engineer
Santa Monica Networks
Phone: +372-6811-262
Mobile: +372-51-200-44
kadri.kalpus@smn.ee<mailto:kadri.kalpus@smn.ee>

[Description: Description: Description: Description: Description: cid:2AE120E0-A2E0-49DE-9208-A226D1B1D8ED]

From: qgarnier
Reply-To: centreon/centreon-plugins
Date: Tuesday, June 9, 2015 at 4:08 PM
To: centreon/centreon-plugins
Cc: Kadri Kalpus
Subject: Re: [centreon-plugins] network::cisco::2900::plugin output incorrect (#68)

1.3.6.1.4.1.9.9.13.1.1.0

**Comment by garnier-quentin** [comment]
it's not a bug. 13 is '37xx'. That's ok for me.

**Comment by kadrika** [comment]
Ok, thanks for the info, it just seemed so strange to see 37xx environment to be returned with output, even if it is actually 2900 series switch.
