### ISSUE TITLE
[hardware::server::hp::ilo::xmlapi::plugin] Pb ssl for ILO2

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#680]
Hi,

For ILO2, I have this error : UNKNOWN: Failed to establish SSL connection: , ssl_error=IO::Socket::INET configuration failed

with check ilo2 health.pl script, it works with ssl parameters : --sslopts='SSL_verify_mode => SSL_VERIFY_NONE, SSL_version => "TLSv1"'      

I don't find the correct value for  --ssl-opt for centreon script
I have tested : --ssl-opt="SSL_version=TLSv1",  or  --ssl-opt=SSL_verify_mode=SSL_VERIFY_NONE, SSL_version="TLSv1"  

Could you help me ?

**Comment by garnier-quentin** [comment]
You have to set both:
```
--ssl-opt="SSL_version=SSL_VERIFY_NONE" --ssl-opt="SSL_version=SSL_VERIFY_NONE"
```

**Comment by romsworld** [comment]
Ok, it works with : --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE" --ssl-opt="SSL_version='TLSv1'"

**Comment by garnier-quentin** [comment]
Thanks for the feedback!

**Comment by chtourou-youssef** [comment]
how you can add this ?

**Comment by lucie-dubrunfaut** [comment]
Hello @chtourou-youssef  :)

I'm not sure to understand your question?
