### ISSUE TITLE
F5 Pool Stats counters as performance metrics

### ISSUE THREAD

**Issue by mvillarejo** [centreon/centreon-plugins#682]
Hello,

first of all, congratulations for the repository, these modules are really great.

I've tried to implement F5 integration and I end up with a problem / feature request that might be easy to implement for someone with good perl skills.

Is there any chance to return "ltmPoolStatServerCurConns" as performance counter from pool-status mode? this is the OID: 1.3375.2.2.5.2.3.1.8

The final oid will look like:
```
1.3375.2.2.5.2.3.1.8.$length.$instance
```

but can not get the length from the class... I've tried to implemented it looking into temperature one but... my perl skills are not good enough.

thanks in advance.

**Comment by garnier-quentin** [comment]
It can be added yes.

**Comment by mvillarejo** [comment]
Great, let's see if someone can pick that soon.

Thanks

**Comment by garnier-quentin** [comment]
Shit i have done for node... :)

**Comment by garnier-quentin** [comment]
Could you test it please ?

**Comment by garnier-quentin** [comment]
Could you test it again ? You should have the status now.
