### ISSUE TITLE
network::dlink::standard::snmp::plugin --mode=interfaces

### ISSUE THREAD

**Issue by sunks08** [centreon/centreon-plugins#684]
Hello,

i'm using a command to display the traffic on each ports of my dlink switch and i would like to add the vlan of the port.

The command is : 
--plugin=network::dlink::standard::snmp::plugin --mode=interfaces --hostname=$HOSTADDRESS$
--interface=x

I tried to add "--oid-extra-display=x.x.x.x.." but i get "UNKNOWN: Unsupported oid in --oid-extra-display-option"

I'm not sure to understand how this option is working and if it's possible to display the vlan of each port.
It would be really awesome if i could !

I found the oid that give the VLAN number of the port, it's this one : 
1.3.6.1.2.1.17.7.1.4.5.1.1.x
the x mean the port number we want to display

Thanks !

**Comment by sunks08** [comment]
I think this is a standard OID by the way

**Comment by garnier-quentin** [comment]
The index is the IfIndex of your interface ? You can have X Vlan for the same interface also no ?

**Comment by sunks08** [comment]
what i found about the OID 1.3.6.1.2.1.17.7.1.4.5.1.1: 
"The PVID, the VLAN ID assigned to untagged frames or Priority-Tagged frames received on this port."

Untagged frames means that you can have only one vlan, so it will display only one vlan for each port. 
I guess it's an other OID for trunk port (tagged). I'll check monday if i find the OID for tagged frame.

**Comment by sunks08** [comment]
To resume:
With that OID when i do a "snmpwalk -v2c -c public xx.xx.xx.xx 1.3.6.1.2.1.17.7.1.4.5.1.1"
It display the PVID (Port Vlan ID) of every interface and when theire is X vlan for the same interface it just display vlan 1 for me (wich is ok for now).

example for 1 interface:
"snmpwalk -v2c -c public xx.xx.xx.xx 1.3.6.1.2.1.17.7.1.4.5.1.1.x
SNMPv2-SMI::mib-2.17.7.1.4.5.1.1.x = Gauge32: 10"

So for the interface x, the vlan ID is 10.

If it's possible to add this option in the --plugin=network::dlink::standard::snmp::plugin --mode=interfaces it would be awesome.

thanks

**Comment by garnier-quentin** [comment]
Excuse me for the late response. If you still have the issue, could you provide me a snmpwalk with VLAN informations.
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.2 > dlink.snmpwalk

**Comment by lucie-dubrunfaut** [comment]
Hello :)

Without additional information we are not able to provide a solution or resolve a possible bug.
So @sunks08 if you still need a response / solution to this issue, can you provide us the snmpwalk asked by Quentin ?
Otherwise we will be forced to close this issue.

**Comment by lucie-dubrunfaut** [comment]
I'm closing this issue, which has gone unanswered for a long time. Feel free to reopen it if you encounter the problem again and are able to provide the information we didn't have to resolve the sissue.
