### ISSUE TITLE
Add support for Aruba Instant

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#685]
Can you add support for Aruba Instant AP WIFI?

[aruba-instant-mibs_6.5.1.0-4.3.1.2_58595.tar.gz](https://github.com/centreon/centreon-plugins/files/1068280/aruba-instant-mibs_6.5.1.0-4.3.1.2_58595.tar.gz)
[aruba-mibs_6.5.1.0-4.3.1.2_58595.tar.gz](https://github.com/centreon/centreon-plugins/files/1068281/aruba-mibs_6.5.1.0-4.3.1.2_58595.tar.gz)

Thanks,
Jochen

**Comment by garnier-quentin** [comment]
Yes. But i can't give you a date for it.

**Comment by joschi99** [comment]
No problem, we can bypass the problem at the moment.

**Comment by garnier-quentin** [comment]
I need snmpwalk please
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md

**Comment by joschi99** [comment]
Hi Quentin,
I uploaded 2 files, because the snmpwalk aborts after last row in the first file:

[aruba.txt](https://github.com/centreon/centreon-plugins/files/1075669/aruba.txt)
[aruba2.txt](https://github.com/centreon/centreon-plugins/files/1075670/aruba2.txt)

**Comment by garnier-quentin** [comment]
@joschi99 i don't really understand. It seems Aruba Instant is a technology without wifi controller. But when i'm looking at the MIB, there is a table with AP listing ??!! It's not some standalone AP ? Thanks for some information about it.

**Comment by joschi99** [comment]
hi @garnier-quentin, in our case we habe Aruba Instant AP's with Virtual Controller configured, so we can check all AP's through VC.
If you need other informations please let me know.

Regards,
Jochen

**Comment by garnier-quentin** [comment]
Could you test it ?

**Comment by joschi99** [comment]
Hi @garnier-quentin,
I have done some test:

`./centreon_plugins.pl --plugin=network::aruba::instant::snmp::plugin --mode=ap-usage --hostname=1.1.1.1 --snmp-community=xxx
OK: All access points are ok | 'iap-pe-produzione#clients.current.count'=1;;;0; 'iap-pe-produzione#cpu.utilization.percentage'=2.00%;;;0;100 'iap-pe-produzione#memory.usage.bytes'=286527488B;;;0;487677952 'iap-pe-produzione#memory.free.bytes'=201150464B;;;0;487677952 'iap-pe-produzione#memory.usage.percentage'=58.75%;;;0;100 'iap-pe-torni#clients.current.count'=0;;;0; 'iap-pe-torni#cpu.utilization.percentage'=2.00%;;;0;100 'iap-pe-torni#memory.usage.bytes'=281284608B;;;0;487677952 'iap-pe-torni#memory.free.bytes'=206393344B;;;0;487677952 'iap-pe-torni#memory.usage.percentage'=57.68%;;;0;100 'iap-pe-uffici#clients.current.count'=1;;;0; 'iap-pe-uffici#cpu.utilization.percentage'=2.00%;;;0;100 'iap-pe-uffici#memory.usage.bytes'=268926976B;;;0;487677952 'iap-pe-uffici#memory.free.bytes'=218750976B;;;0;487677952 'iap-pe-uffici#memory.usage.percentage'=55.14%;;;0;100`

As you can see the AP will be shown and status will be checked. At the moment I'm not able to reproduce a AP with failed status.

It should be nice if you can add some other modes like

- active sessions
- cpu utilization
- memory usage

**Comment by garnier-quentin** [comment]
You have cpu, memory and clients usage (look the perfdata).

**Comment by joschi99** [comment]
Yes, you are right. Have just seen the option. Great
