### ISSUE TITLE
ZMQ::LibZMQ4 for vmware connector on CES 3.3

### ISSUE THREAD

**Issue by AlexisTEXIER** [centreon/centreon-plugins#686]
Hello,

The last version of the plugin use ZMQ4 for vmware connector.
I can't find this perl module for CES 3.3 (CentOS 6).
Could you tell me on witch repository I can find it ?

Regards

**Comment by garnier-quentin** [comment]
I put it in attachment.
[zmq4_rpm.zip](https://github.com/centreon/centreon-plugins/files/1076913/zmq4_rpm.zip)
