### ISSUE TITLE
 os::windows::snmp::plugin no perfdata for network traffic

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#687]
Hello,

I'm running centreon-plugins-20170613, I would like to monitor windows 2012 server network interface trafic. But I'm not able to get perfdata I just get  skipped  as perfdata

So I use the plugin like this : 

```
[root@eqcentreon centreon-plugins-20170613]# ./centreon_plugins.pl --plugin os::windows::snmp::plugin --mode interfaces --hostname 192.168.1.1 --snmp-community snmpro --interface 7  --add-traffic
OK: Interface 'ethernet_0' Traffic In : skipped, Traffic Out : skipped |
```

Am I doing something wrong ? Or maybe some limitation from windows snmp agent ?

**Comment by garnier-quentin** [comment]
That's weird. Could you test with snmp version 2c ? 
Could you try a snmpwalk directly on OIDs ?

Maybe the cache file datas are obsolete. Could you remove it ? Maybe there is no traffic. You can add option: --no-skipped-counters

**Comment by hdep** [comment]
Ok, thanks to your answer I just found that the ifname didn't reflect the interface name on the server. IfAlias, is more accurate. 
So I should monitor interface id 12 not 7. 

I run the command several times, while transfering 3 GB file on the server, but the script didn't catch continuous traffic : 

```
[root@eqcentreon centreon-plugins-20170613]# ./centreon_plugins.pl --plugin os::windows::snmp::plugin --mode interfaces --hostname 192.168.1.1 --snmp-community snmpro --interface 12  --add-traffic --verbose  --snmp-version 2c --no-skipped-counters
OK: Interface 'ethernet_10' Traffic In : 26.56Mb/s (0.27%), Traffic Out : 4.20Mb/s (0.04%) | 'traffic_in'=26560057.98b/s;;;0;10000000000 'traffic_out'=4200116.40b/s;;;0;10000000000
Interface 'ethernet_10' Traffic In : 26.56Mb/s (0.27%), Traffic Out : 4.20Mb/s (0.04%)
[root@eqcentreon centreon-plugins-20170613]# ./centreon_plugins.pl --plugin os::windows::snmp::plugin --mode interfaces --hostname 192.168.1.1 --snmp-community snmpro --interface 12  --add-traffic --verbose  --snmp-version 2c --no-skipped-counters
OK: Interface 'ethernet_10' Traffic In : 0.00b/s (0.00%), Traffic Out : 0.00b/s (0.00%) | 'traffic_in'=0.00b/s;;;0;10000000000 'traffic_out'=0.00b/s;;;0;10000000000
Interface 'ethernet_10' Traffic In : 0.00b/s (0.00%), Traffic Out : 0.00b/s (0.00%)
```

So the snmp informations doesn't seems to be accurate. Is this known issue with windows 2012 ? 
This is a VM running vmxnet 3 driver from vmware so the interface is 10Gb/s adaptator.

**Comment by garnier-quentin** [comment]
Maybe an issue with SNMP Windows. You should use NSClient++.

**Comment by hdep** [comment]
yes I know, I just need time :) 

Ok I think the snmp counter is updated very slowly on windows. Which explain this behaviour.

Thank you !
