### ISSUE TITLE
[net::checkpoint::plugin] - inverted on cpu values/curves

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#689]
It seems to have an inversion on display or curves on cpu mode. See below.
I use last release of pluginpack (Update this weekend).
![checkpoint_cpu_graphe](https://user-images.githubusercontent.com/8720203/27278906-12cf7438-54e3-11e7-8631-45656a2739f9.png)
The service detail indicates the system at 81%, but the metric value cpuSys indicates 19% and vice versa

**Comment by garnier-quentin** [comment]
It's the output, not the perfdata. Thanks! :)
