### ISSUE TITLE
[network::hp::procurve::plugin] mode=environment - How to disable error when sensor is not present

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#690]
Hi,

Since last update of pluginpack (this w.e.), some services returned a WARNING state because some sensors are not present.

`/usr/lib/centreon/plugins/centreon_hp_procurve.pl --plugin=network::hp::procurve::plugin --mode=environment --hostname=x.x.x.x --snmp-version='2c' --snmp-community='xxx'  --component='.*' --verbose
WARNING: temperature sensor 'temperature.7' state is not present |
Checking sensors
fan sensor 'fan.1' state is good [instance: fan.1].
power supply sensor 'power supply.2' state is good [instance: power supply.2].
power supply sensor 'power supply.3' state is good [instance: power supply.3].
power supply sensor 'power supply.4' state is good [instance: power supply.4].
power supply sensor 'power supply.5' state is good [instance: power supply.5].
power supply sensor 'power supply.6' state is good [instance: power supply.6].
temperature sensor 'temperature.7' state is not present [instance: temperature.7].
power supply sensor 'power supply.8' state is good [instance: power supply.8].
power supply sensor 'power supply.9' state is good [instance: power supply.9].
`
If i add `--absent-problem=sensor`, the plugin skip sensor not present but return a CRITICAL status.

`-bash-4.1$ /usr/lib/centreon/plugins/centreon_hp_procurve.pl --plugin=network::hp::procurve::plugin --mode=environment --hostname=x.x.x.x --snmp-version='2c' --snmp-community='xxx'  --component='.*' --verbose --absent-problem=sensor
CRITICAL: Component 'sensor' instance 'temperature.7' is not present |
Checking sensors
fan sensor 'fan.1' state is good [instance: fan.1].
power supply sensor 'power supply.2' state is good [instance: power supply.2].
power supply sensor 'power supply.3' state is good [instance: power supply.3].
power supply sensor 'power supply.4' state is good [instance: power supply.4].
power supply sensor 'power supply.5' state is good [instance: power supply.5].
power supply sensor 'power supply.6' state is good [instance: power supply.6].
Skipping sensor section temperature.7 instance (not present)
power supply sensor 'power supply.8' state is good [instance: power supply.8].
power supply sensor 'power supply.9' state is good [instance: power supply.9].
`
How can I really skip sensors not present?

**Comment by garnier-quentin** [comment]
Like that:
```
--threshold-overload='sensor,OK,not present'
```

**Comment by cmeschin** [comment]
yes i just found it here: https://github.com/centreon/centreon-plugins/issues/488
sorry.
