### ISSUE TITLE
Add Teltonika devices plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#691]
Hi,

Could you please add plugin for Teltonika devices. From services side signal quality check is needed at first.
If you need snmpwalk, then let me know, I can send it via email.

**Comment by garnier-quentin** [comment]
I'll need a complete snmpwalk and MIB files.

**Comment by garnier-quentin** [comment]
What do you want to monitor on it ? I don't really see something interesting in entreprise MIB.

**Comment by kadrika** [comment]
I would like to get signal level.

**Comment by kadrika** [comment]
I just sent you new snmpwalk from the devices, it seems some of the OIDs have changed in latest devices.

**Comment by garnier-quentin** [comment]
Could you give me with following command please ?
```
$ snmpwalk -ObentU -v 2c -c public IP .1 > telk.snmpwalk
```

The mib has changed also ? If so, i'll need the mib file.

**Comment by kadrika** [comment]
Sent it to your email.

**Comment by garnier-quentin** [comment]
That's better (oids match the mib file). What do you want to monitor ? Ok for you ?
* SimState, PinState, NetState
* Signal level
* bytes sent and received

**Comment by kadrika** [comment]
I need from it Signal.0 (with configurable thresholds). Mode should show in output the signal strength number and Operator.0
 
Also we need RSRP mode and RSRQ mode (with configurable thresholds):
TELTONIKA-MIB::RSRP.0 = STRING: -108
TELTONIKA-MIB::RSRQ.0 = STRING: -6.000000

**Comment by kadrika** [comment]
Any update on this?

**Comment by kadrika** [comment]
Any update on this?
