### ISSUE TITLE
confused by --filter-uom

### ISSUE THREAD

**Issue by yodaaut** [centreon/centreon-plugins#694]
## Bug/Question
I'm a little bit confused of how to use "--filter-uom".

I tried the following without filter-uom:
`perl centreon_plugins.pl --plugin SOME_SNMP_PLUGIN --hostname HOSTNAME --snmp-version 3 --snmp-username USER --MORE_SNMP_OPTIONS... --mode hardware --component fan`
and get the output:
`OK: All 3 components are ok [3/3 fans]. | 'Case Fan 1'=5443rpm;;;; 'Case Fan 2'=5625rpm;;;; 'Case Fan 3'=5443rpm;;;;`

but if i try it with "--filter-uom rpm" I get the same result.
My monitoring-instance (icinga2) can't display the Value of "Case Fan 1" because of the "rpm" in "5443rpm"; without rpm it works.

The confusing part is, if I type a "wrong" uom, it looks like it works.
"--filter-uom X" and the ouput is:
`OK: All 3 components are ok [3/3 fans]. | 'Case Fan 1'=5443;;;; 'Case Fan 2'=5625;;;; 'Case Fan 3'=5625;;;;`

So the question is, should "filter-uom" delete the units?
Changing "!" to "=" in line 421 in [output.pm](https://github.com/centreon/centreon-plugins/blob/master/centreon/plugins/output.pm#L421)
from
`$perf->{unit} !~ /$self->{option_results}->{filter_uom}/);`
to
`$perf->{unit} =~ /$self->{option_results}->{filter_uom}/);`
works as aspected.

Thanks in advance

**Comment by garnier-quentin** [comment]
You can use negate regexp:
```
--filter-uom='^(?!(rpm)$)'
```

**Comment by yodaaut** [comment]
thanks for your quick response, that works.
