### ISSUE TITLE
[apps::vmware::connector::plugin] option --display-description nonfunctionnal

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#695]
Hi,

I try to use --display-description to have more informations about snapshot but the information isn't displayed.

This is my command:
`/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=snapshot-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --vm-hostname='^(?!_TMPLT)+' --filter --warning='43' --critical='' --disconnect-status='ok' --nopoweredon-skip --check-consolidation --verbose --display-description`

the result is:
WARNING: Snapshots for VM older than 0 days: [HOST1] [HOST-2] | 'num_warning'=2;;;0; 'num_critical'=0;;;0;
'HOST1' snapshot create time: 2017-06-30T14:55:40.733984Z
'HOST2' snapshot create time: 2017-02-21T14:38:10.276999Z

Is it a known issue or a limitation of the connector?
regards

**Comment by Sims24** [comment]
Hello, 

It works for me, which version of the connector/plugin and sdk are you using ? 

```
[sims@ces-misc mode]# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=snapshot-vm --custommode=connector --connector-hostname='W.X.Y.Z' --connector-port='5700' --container='default' --vm-hostname '10.30.2.186' --filter --warning='259200' --critical='432000' --disconnect-status='ok' --nopoweredon-skip='ok' --check-consolidation --verbose --display-description 
CRITICAL: Snapshots for VM older than 5 days: [centreon  10.30.2.186] | 'num_warning'=0;;;0; 'num_critical'=1;;;0;
'centreon  10.30.2.186' [Ne pas eteindre pour ne pas avoir de coupure dans les graphs --  password toto] snapshot create time: 2017-05-30T14:51:58.393812Z
```

**Comment by cmeschin** [comment]
Hi,

Sorry, I was thinking this was the description of the snapshot but it is the description of the virtual machine that is displayed.

Is there a possibility to display the name and/or the description of the snapshot?

thanks,

**Comment by garnier-quentin** [comment]
Yes we can ;)

**Comment by cmeschin** [comment]
\o/ You are the champions! :)
Thanks.

**Comment by cmeschin** [comment]
Hi,
have you any news about this enhancement?
thanks.

**Comment by cmeschin** [comment]
Hi,
a little up.

**Comment by garnier-quentin** [comment]
In new release of 3.0.0

**Comment by cmeschin** [comment]
Hi,
Thank you.
