### ISSUE TITLE
[network::alcatel::omniswitch::snmp::plugin] hardware mode oper status chassis problem

### ISSUE THREAD

**Issue by Tithib** [centreon/centreon-plugins#696]
Hi,

I found a mistake in the network::alcatel::omniswitch::snmp::plugin with --mode=hardware, searching why i couldn't obtain status.
In the /network/alcatel/omniswitch/snmp/mode/componentscomponent/chassis.pm, on line 72, this sould be **chasEntPhysOperStatus** rather than **chasEntPhysAdminStatus** :

Wrong line :
`$exit = $self->get_severity(label => 'oper', section => 'chassis.oper', value => $result->{chasEntPhysAdminStatus});`

Correct line :
`$exit = $self->get_severity(label => 'oper', section => 'chassis.oper', value => $result->{chasEntPhysOperStatus});`

I think of copy-paste error because a similar line with Admin appear just before.

Thanks for your great tools !

**Comment by garnier-quentin** [comment]
I have looked the file and it seems already fixed. Do you have the last version ?

**Comment by Tithib** [comment]
Ok sorry, I didn't have the last version.
You are right, it has been fixed 21 days ago and I downloaded the plugins few days before...
Thanks.
