### ISSUE TITLE
[network::alcatel::omniswitch::snmp::plugin] wrong port number in blocking state

### ISSUE THREAD

**Issue by nogomes** [centreon/centreon-plugins#697]
Hi

I noticed that with the spanning-tree mode, when a port has the 'blocking' state on the switch, the number of the port retrieved by the plugin is wrong.

We have a stack of 2 switchs (ports 1/1 to 1/48 and 2/1 to 2/24), and I think that the spanning-tree mode doesn't care with the interfaces of the second unit. But on the other end, the others modes (list-interfaces, interfaces...) work well with 2/xx interfaces : I can get the traffic for a 2/x interface.

In my switch, the 2/1 port is in blocking state. The plugin tells that it's the 1/33 that is in blocking state. And in real, the 1/33 port is not linked.

When executing the plugin in verbose mode, it lists all my 1/xx interfaces, but not the 2/xx, maybe it's due to this ?

Regards

Norbert

**Comment by garnier-quentin** [comment]
I don't really know. You should ask to alcatel support ? You talk about the 'interfaces' mode ?

**Comment by nogomes** [comment]
Yes I mean the "interfaces" mode on your plugin. In this mode I have no problem to retrieve information for the 2/xx interfaces. 

But in the "spanning-tree" mode, it seems that it retrieves only information about the 1/xx interfaces, and not the 2/xx. I don't know if it's due to a bug in your scripts, or a missing information in the Alcatel MIB.

**Comment by garnier-quentin** [comment]
I see. Maybe a complete snmpwalk will help to find it.

**Comment by nogomes** [comment]
Sent the snmpwalk in private to Quentin

**Comment by garnier-quentin** [comment]
With the snmpwalk, we see no values for 'dot1dStpPortState' and 'dot1dStpPortEnable' OID. But interfaces are in BRIDGE MIB. But it's incomplete. Don't know if we can monitor. Other OIDS ?

**Comment by nogomes** [comment]
Does it means that dot1dStpPortState table only contains interfaces that are linked or something like this ? And the interfaces that are not linked up (or with admin down status) don't appear in the table ?

So in this table the .1.3.6.1.2.1.17.2.15.1.3.33 entry would not necessarly be the port number 33 on the switch ?

**Comment by garnier-quentin** [comment]
I don't know. But it seems so.
