### ISSUE TITLE
Problem with plugin Oracle :(

### ISSUE THREAD

**Issue by ccoupeau** [centreon/centreon-plugins#698]
Hey everyone,

I have some problems when i execute commands check with plugin "database::oracle::plugin" and i dont success to resolve it. 

**For example :** 
./centreon_plugins.pl --plugin database::oracle::plugin --hostname cbh53 --port 1523 --sid LIVE52 --mode tnsping 

**and result for all my check with this plugin is :** 

UNKNOWN: install_driver(Oracle) failed: Can't locate DBD/Oracle.pm in @INC (@INC contains: /usr/lib/nagios/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 11) line 3.
Perhaps the DBD::Oracle perl module hasn't been fully installed,
or perhaps the capitalisation of 'Oracle' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Proxy, Sponge, mysql.
 at /usr/lib/nagios/plugins/centreon/plugins/dbi.pm line 210

Do you have an idea ?

Thx for all ..

**Comment by garnier-quentin** [comment]
Hi,

You need to compile DBD::Oracle Perl Module. You also need to install instantclient.

**Comment by ccoupeau** [comment]
Yes, i know but how can i install "DBD::Oracle perl module" without CPAN ?
I dont have install cpan on Centreon cause this shit fucked it up ... :'(
During my training Centreon session, a trainer recommands us to not install CPAN on the same server than Centreon, to not disturb the service.

**Comment by garnier-quentin** [comment]
Yes he was right. You can download the zip version and compile yourself (without the cpan command).

**Comment by ccoupeau** [comment]
All is OK, thx !
