### ISSUE TITLE
[plugin][apps] JBOSS Application Server

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#7]
add new apps mode.

It seems, there is a nice perl module: http://search.cpan.org/~roland/jmx4perl-1.07/lib/JMX/Jmx4Perl/Manual.pod
But you need to deploy an war on jboss: http://www.jolokia.org/agent.html

**Comment by florian-asche** [comment]
Monitoring with JMX is best way.

**Comment by garnier-quentin** [comment]
abe5c4dd8d68d444fc883bdb44775db13ccc4b46

**Comment by garnier-quentin** [comment]
Need more informations (mbean and attributs):
https://github.com/centreon/centreon-plugins/blob/master/.github/issue_template.md
