### ISSUE TITLE
SNMP v3 error "SNMP GET Request : Cant get a single value"

### ISSUE THREAD

**Issue by magicbret** [centreon/centreon-plugins#700]
Hi everyone,

I try to setup SNMP v3 on my CES server but have somme issue with the mode LOAD, MEMORY and SWAP. I receive an error

`UNKNOWN: SNMP GET Request : Cant get a single value`

Tested with SNMP v2c and it works good, I've got some replies. I also tested my SNMP v3 configuration with the CPU mode and it's also OK, I've got a response from the server.

Here is the command:

/usr/lib/centreon/plugins/centreon_linux_snmp.pl
	--plugin=os::linux::snmp::plugin
	--mode=load
	--hostname=**IP_ADDRESS**
	--snmp-version='3'
	--warning='4,3,2'
	--critical='6,5,4'
	--snmp-username **username**
	--authprotocol MD5
	--authpassphrase **pass**
	--privprotocol DES
	--privpassphrase **pass**

Result:
`UNKNOWN: SNMP GET Request : Cant get a single value`

With CPU mode (which works good):

/usr/lib/centreon/plugins/centreon_linux_snmp.pl
	--plugin=os::linux::snmp::plugin
	--mode=cpu
	--hostname=**IP_ADDRESS**
	--snmp-version='3'
	--warning='80' 
	--critical='90'
	--snmp-username **username**
	--authprotocol MD5
	--authpassphrase **pass**
	--privprotocol DES
	--privpassphrase **pass**

Result:
`OK: 1 CPU(s) average usage is: 1.00% | 'cpu0'=1.00%;;;0;100 'total_cpu_avg'=1.00%;0:80;0:90;0;100`

Any ideas ? What can be wrong in the configuration ?

Thank you

**Comment by garnier-quentin** [comment]
Does it work with snmp v2 for 'load' mode ?

**Comment by magicbret** [comment]
Yes tested and OK in V2c
OK: Load average: 0.00, 0.00, 0.00 | 'load1'=0.00;;;0; 'load5'=0.00;;;0; 'load15'=0.00;;;0;

**Comment by magicbret** [comment]
Same for MEMORY and SWAP. OK in v2c, NOK in V3.

**Comment by garnier-quentin** [comment]
Can you try with snmpwalk ?

**Comment by magicbret** [comment]
You are right, it seems to be a server config issue. I am unable to walk through the .1.3.6.1.4.1 tree, when .1.3.6.1.2.1 is OK. But why is the private mib browsable in v2c but not in v3 ? Something specific to configure in snmp.conf on the remote server ?

**Comment by garnier-quentin** [comment]
With 'net-snmp', you can choose tree configuration according snmp version/community.

**Comment by magicbret** [comment]
OK, thanks a lot :)

**Comment by garnier-quentin** [comment]
You're welcome

**Comment by magicbret** [comment]
Solved. "rwuser" configuration was wrong in snmpd.conf, restricted to 1.3.6.1.2.1. Sorry for not having checked this earlier.

**Comment by garnier-quentin** [comment]
No problem ;)
