### ISSUE TITLE
filter exclude to --plugin=os::linux::snmp::plugin --mode=storage

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon-plugins#701]
[EN]
Hi there,

is it possible to exclude one mounted point (like /dev/shm for exemple) when we used the mode storage, because this mounted point is always 100%, so my check is always CRITICAL. 

Thanks in advance.
[EN]

[FR]
Bonjour,

est 'il possible d'exclure un point de montage (/dev/shm par exemple) quand on utilise le mode storage parce que le point de montage est toujours à 100% utilisés pour ma part, donc le check est toujours en CRITICAL.

Merci par avance.
[FR]

**Comment by Sims24** [comment]
Hello, 

Yes it's possible. You can negate the regexp in your filter e.g : 

'^(?!(/dev/shm)$)'

**Comment by Sims24** [comment]
An example to skip /var/lib/mysql fs : 

`--name --storage '^(?!(/var/lib/mysql)$)' --regexp`

Thanks

**Comment by fredo1988** [comment]
thanks :)

**Comment by fredo1988** [comment]
last question, for windows disk, the filter not function correctly, I want to exclude all disk with the name contain "SWAP" :

[XXXXX@XXXXX ~]# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=X.X.X.X --snmp-version=XX --snmp-community=XXXXXXXX --name --regexp --warning='95' --critical='97' --storage '^(?!(#SWAP#)$)' --verbose

CRITICAL: **_Storage 'D:\ Label:SWAP  Serial Number e81e8d7c' Total: 4.00 GB Used: 3.99 GB (99.72%) Free: 11.55 MB (0.28%)_** WARNING: Storage 'E:\ Label:Tools  Serial Number 782b9e8e' Total: 8.99 GB Used: 8.58 GB (95.37%) Free: 426.12 MB (4.63%) | 'used_C:\ Label:XXXXXXX  Serial Number 800b5772'=14481838080B;0:16320871833;0:16664469135;0;17179865088 'used_D:\ Label:SWAP  Serial Number e81e8d7c'=4281479168B;0:4078915379;0:4164787281;0;4293595136 'used_E:\ Label:Tools  Serial Number 782b9e8e'=9209659392B;0:9173651865;0:9366781378;0;9656475648 'used_F:\ Label:Disk_1  Serial Number 44986a47'=148820451328B;0:204015359180;0:208310419374;0;214753009664
Storage 'C:\ Label:XXXXXXX  Serial Number 800b5772' Total: 16.00 GB Used: 13.49 GB (84.30%) Free: 2.51 GB (15.70%)
Storage 'D:\ Label:SWAP  Serial Number e81e8d7c' Total: 4.00 GB Used: 3.99 GB (99.72%) Free: 11.55 MB (0.28%)
Storage 'E:\ Label:Tools  Serial Number 782b9e8e' Total: 8.99 GB Used: 8.58 GB (95.37%) Free: 426.12 MB (4.63%)
Storage 'F:\ Label:Disk_1  Serial Number 44986a47' Total: 200.00 GB Used: 138.60 GB (69.30%) Free: 61.40 GB (30.70%)

**Comment by Sims24** [comment]
Hi, 

You're welcome ! 

A quick way (regexp might be better) to do what you want is : 

--storage '^(?!(.*SWAP.*)$)'

Thanks,

**Comment by fredo1988** [comment]
Hi there,

it's the same result, not function...


[XXXXX@XXXXX ~]# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=XXXXX --snmp-version=XXXXX --snmp-community=XXXXX --name --regexp --warning='95' --critical='97' --storage '^(?!(.SWAP.)$)'  --verbose
**_CRITICAL: Storage 'D:\ Label:SWAP  Serial Number e81e8d7c' Total: 4.00 GB Used: 3.99 GB (99.72%) Free: 11.55 MB (0.28%)_** WARNING: Storage 'E:\ Label:Tools  Serial Number 782b9e8e' Total: 8.99 GB Used: 8.58 GB (95.37%) Free: 426.08 MB (4.63%) | 'used_C:\ Label:XXXXX  Serial Number 800b5772'=14481833984B;0:16320871833;0:16664469135;0;17179865088 'used_D:\ Label:SWAP  Serial Number e81e8d7c'=4281479168B;0:4078915379;0:4164787281;0;4293595136 'used_E:\ Label:Tools  Serial Number 782b9e8e'=9209696256B;0:9173651865;0:9366781378;0;9656475648 'used_F:\ Label:Disk_1  Serial Number 44986a47'=148820451328B;0:204015359180;0:208310419374;0;214753009664
Storage 'C:\ Label:XXXXX  Serial Number 800b5772' Total: 16.00 GB Used: 13.49 GB (84.30%) Free: 2.51 GB (15.70%)
**_Storage 'D:\ Label:SWAP  Serial Number e81e8d7c' Total: 4.00 GB Used: 3.99 GB (99.72%) Free: 11.55 MB (0.28%)_**
Storage 'E:\ Label:Tools  Serial Number 782b9e8e' Total: 8.99 GB Used: 8.58 GB (95.37%) Free: 426.08 MB (4.63%)
Storage 'F:\ Label:Disk_1  Serial Number 44986a47' Total: 200.00 GB Used: 138.60 GB (69.30%) Free: 61.40 GB (30.70%)

**Comment by Sims24** [comment]
Sorry my bad some github char removing, add a "star" after each point.

**Comment by Sims24** [comment]
Better with coding style : 

`--storage '^(?!(.*SWAP.*)$)'
`

**Comment by fredo1988** [comment]
thank you so much it's ok for me :)
