### ISSUE TITLE
network::cisco::wlc::snmp::plugin --mode=ap-status  --warning-total*=n --critical-total*=m

### ISSUE THREAD

**Issue by BaaptM** [centreon/centreon-plugins#702]
Hi,

I have an issue with the way you check the threshold.

Use case : I have 6 APs, well displayed with ap-status mode and I want to set a warning threshold when the total number of APs fall down to, let's say the half, 3 APs, so the option is "--warning-total=3" and a critical threshold when all APs are down so "--critical-total=6".
The issue here is that, I think, you check if the threshold value (warning or critical) is less than the number of APs, then return a warning or critical and it should be if the total number of APs is less than the value, then return a warning or critical.

Do not hesitate if you want more details about the use case.
Hope you'll get back to me quickly.
Thanks.

**Comment by garnier-quentin** [comment]
You should have your response here:
https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#how-can-i-set-threshold-critical-if-value--x-

**Comment by BaaptM** [comment]
Many thanks for your quick answer ! I was not aware of that trick..
Sorry for the inconvenience.

**Comment by garnier-quentin** [comment]
Not a problem! thanks to use it
