### ISSUE TITLE
ENHANCEMENT - --free with perfdata space used

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#704]
Bonjour,

Lorsqu'on l'on utilise l'option --free pour les disques, mémoire, tablespace, cela permet de checker l'espace libre d'un volume ET d'avoir des courbes sur la valeur libre.

Je voudrais pouvoir faire des check sur l'espace libre, mais avoir les graphs d'un espace occupé, comme pour un check sans l'option.
Il faudrait avoir une option --free pour le type de check, et une option --free-perfadata pour avoir le type de graph que l'on souhaite.
Il est plus pratique dans mon cas de présenter un graph d'occupation d'espace que de raisonner sur un espace restant. Mais cependant, pour les alertes, je préfèreé être alerté sur un espace restant.

Pensez vous pouvoir implémenter cette option ?

Merci,

**Comment by garnier-quentin** [comment]
Duplicate #79
