### ISSUE TITLE
centreon_protocol_http.pl --list-plugin : perl error

### ISSUE THREAD

**Issue by imnotme** [centreon/centreon-plugins#707]
Monitoring platform fully updated :

[root@monitoring plugins]# ./centreon_protocol_http.pl --list-plugin
Use of uninitialized value $options{"module"} in pattern match (m//) at ./centreon_protocol_http.pl line 2263.
Use of uninitialized value $options{"module"} in concatenation (.) or string at ./centreon_protocol_http.pl line 2263.
UNKNOWN: Cannot load module --plugin.
Can't locate .pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::15762416=HASH(0xf083f0) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./centreon_protocol_http.pl line 2267.

Work great with:
./centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --list-mode

Is this is an artefact from the "centreon_plugins.pl" plugin? [Example in the documentation](https://documentation.centreon.com/docs/centreon-plugins/en/latest/developer/guide.html?highlight=centreon_plugin)

**Comment by garnier-quentin** [comment]
I don't manage and generate the fatpack. Please ask to your support. But i can tell you that because the fatpack uses old common library ;)
