### ISSUE TITLE
os::linux::snmp::plugin timeout in interfaces or list-interfaces mode

### ISSUE THREAD

**Issue by eLvErDe** [centreon/centreon-plugins#708]
Hey,

I'm experiencing something really weird. The whole plugin is working just fine except the network interface related operations.

Here is what happens:

```
root@centreon:~# sudo -u centreon-engine /usr/lib/nagios/plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --hostname 10.66.32.120 --snmp-community public --snmp-version 2 --mode load      
OK: Load average: 0.20, 0.22, 0.17 | 'load1'=0.20;;;0; 'load5'=0.22;;;0; 'load15'=0.17;;;0;

root@centreon:~# sudo -u centreon-engine /usr/lib/nagios/plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --hostname 10.66.32.120 --snmp-community public --snmp-version 2 --mode interfaces
UNKNOWN: SNMP Table Request : Timeout 
```

It occurs on all target; which are different version of Debian from Wheezy to Stretch and as simple setup a single eth0 in a VM to bonding of bondings interfaces on big physical servers...

Can you give a hint ?

Thanks in advance, Adam

**Comment by garnier-quentin** [comment]
Does it work with snmpwalk command ? If yes, you can add option --snmp-force-getnext to test.

**Comment by eLvErDe** [comment]
Hello,

You're right there's definitly someting wrong with SNMPD:
```
IP-MIB::ipv6IpForwarding.0 = INTEGER: notForwarding(2)
IP-MIB::ipv6IpDefaultHopLimit.0 = INTEGER: 64
IP-MIB::ipSystemStatsInReceives.ipv4 = Counter32: 929147490
IP-MIB::ipSystemStatsInReceives.ipv6 = Counter32: 109786460
Timeout: No Response from 10.66.32.120
```
I know it's not related anymore to Centreon but do you have any idea ?

Regards, Adam.

**Comment by eLvErDe** [comment]
**For the record...**

Just figured out, trust me or not, it's related to iptables in host kernel !

Centreon is running in a docker container on a server running Debian Stretch with Shorewall/Shorewall6.
I saw weird logs like this on the host kernel:
`"bsalg: parser failed"`
And the timestamps matched the time I tried snmpwalk. Googling the issue lead me there: https://github.com/docker/for-mac/issues/982 and it turns out that ensuring shorewall don't load these shitty `nf_nat_snmp_basic` and `nf_conntrack_snmp` make snmpwalk just work perfectlty fine.

Best regards, Adam.

**Comment by garnier-quentin** [comment]
thanks for the feedback. That's very interesting!

**Comment by eLvErDe** [comment]
For the record, it was pretty shitty to really avoid these modules being load:

In **/etc/modprobe.d/local-blacklist-snmp-conntrack.conf**
```
blacklist nf_nat_snmp_basic
blacklist nf_conntrack_snmp
```

In **/etc/shorewall/shorewall.conf**
```
DONT_LOAD=nf_nat_snmp_basic,nf_conntrack_snmp
```
