### ISSUE TITLE
PluginPack Netapp

### ISSUE THREAD

**Issue by ITSIntegra** [centreon/centreon-plugins#711]
Nous rencontrons un problème sur le plugin pack netapp concernant le module filesys.pm.

Si on essaye d'interroger un volume normal nous avons ces informations:

# /usr/bin/perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname 10.1'vol_data_fidal$' --warning-usage='85' --critical-usage='90' --warning-inodes='90' --critical-inodes='95' --units='%' --filter-
OK: Filesys '/vol/vol_data_fidal' Total: 990.00 GB Used: 396.62 GB (40.06%) Free: 593.38 GB (59.94%), Inodes Used : 1 % | 'used'=1%;0:90;0:95;0;100

Meme commande avec un volume dédupliqué (storage efficient):

# /usr/bin/perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname 10.144.80.16 --snmp-version='v1' --snmp-community='public' --filter-name='vol_restauration$' --warning-usage='85' --critical-usage='90' --warning-inodes='90' --critical-inodes='95' --units='%' --filter-perfdata='used|inodes'
OK: All filesys usages are ok | 'used_/vol/vol_restauration'=22642688B;0:9126805504;0:9663676416;0;10737418240 'inodes_/vol/vol_restauration'=0%;0:90;0:95;0;100

On remarque que l'output n'est pas le meme entre ces deux volumes. Le All filesys usages are OK ne correspond pas à nos besoin et devrait remonter comme l'autre volume: OK: Filesys '/vol/vol_data_fidal' Total: 990.00 GB Used: 396.62 GB (40.06%) Free: 593.38 GB (59.94%), Inodes Used : 1 %

J'ai bricolé le script en commentant cette partie:
my $multiple = 0;
# if (scalar(keys %{$self->{filesys_selected}}) == 1) {
# $multiple = 0;
#}

# if ($multiple == 1) {
# $self->{output}->output_add(severity => 'OK',
# short_msg => 'All filesys usages are ok');
# }*/

du coup la sortie est maintenant ainsi:

# /usr/bin/perl /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=filesys --hostname 10.144.80.16 --snmp-version='v2c' --snmp-community='public' --filter-name='vol_users$' --warning-usage='85' --critical-usage='90' --warning-inodes='90' --critical-inodes='95' --units='%'
OK: Filesys '/vol/vol_users' Total: 5.04 TB Used: 3.86 TB (76.60%) Free: 1.18 TB (23.40%), Inodes Used : 89 % - Filesys '/vol/vol_users' skipping: total size is 0, Inodes : skipped (no value(s)) | 'used'=4241394548736B;0:4706365036339;0:4983210038476;0;5536900042752 'compresssaved'=0%;;;0;100 'dedupsaved'=27%;;;0;100 'inodes'=89%;0:90;0:95;0;100

On a les infos mais doublées avec l'information skipping.

Est il possible de corriger ce point pour avoir une sortie identique comme les volumes sans storage efficient ?

Merci de votre retour.

**Comment by garnier-quentin** [comment]
I think you have other filesys checked. Coud you check with following paramter ?
--filter-name='^/vol/vol_restauration$'

**Comment by ITSIntegra** [comment]
Same. Problem is on volume type, if volume is a deduplicated volume command doesnt work correctly.

**Comment by garnier-quentin** [comment]
Ok. You don't use the last version. Please update your plugin
