### ISSUE TITLE
Check Interface Duplex state ?

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#712]
Hi,

Is there a solution to check state interface as Full Duplex or Half ?

Thanks,

**Comment by garnier-quentin** [comment]
I don't know if you can have it in the speed. You could try and see if the snmp ifspeed changes.

**Comment by romsworld** [comment]
my $snmpPortOperStatusTable   = '1.3.6.1.2.1.2.2.1.8';
my $snmpPortNameTable         = '1.3.6.1.2.1.31.1.1.1.1';
my $snmpPortTypeTable         = '1.3.6.1.2.1.2.2.1.3';
my $snmpPortDuplexStatus      = '1.3.6.1.2.1.10.7.2.1.19';

**Comment by garnier-quentin** [comment]
It's dot3StatsDuplexStatus. Does the value change when you are in half ?

**Comment by romsworld** [comment]
Yes, 

EtherLike-MIB::dot3StatsDuplexStatus.10514 = INTEGER: fullDuplex(3)
EtherLike-MIB::dot3StatsDuplexStatus.10515 = INTEGER: fullDuplex(3)
EtherLike-MIB::dot3StatsDuplexStatus.10516 = INTEGER: halfDuplex(2)
EtherLike-MIB::dot3StatsDuplexStatus.10517 = INTEGER: unknown(1)

**Comment by garnier-quentin** [comment]
Maybe i can add something about to check it in '--warning-status' and '--critical-status' for example.

**Comment by romsworld** [comment]
Yes, it will be a good thing

**Comment by garnier-quentin** [comment]
There is an option:
```
--add-duplex-status
```

And you can check it:
```
--critical-status='%{admstatus} eq "up" and (%{opstatus} ne "up" or %{duplexstatus} eq "halfDuplex")' 
```
