### ISSUE TITLE
plugin for Infoblox

### ISSUE THREAD

**Issue by cost17** [centreon/centreon-plugins#714]
Hi,
could you please add a plugin for Infoblox?

OID: http://www.mibdepot.com/cgi-bin/getmib3.cgi?win=mib_a&r=infoblox&f=IB-PLATFORMONE-MIB&v=v2&t=tree
MIB: [snmp.mibs.tar.gz](https://github.com/centreon/centreon-plugins/files/1169555/snmp.mibs.tar.gz)

Regards

**Comment by garnier-quentin** [comment]
I need a full snmpwalk.

**Comment by garnier-quentin** [comment]
What do you want to monitor? I see:
* ibSystemMonitorCpuUsage
* ibSystemMonitorMemUsage
* Replication status: ibClusterReplicationStatusTable (last received time to master, Queue size to master, replication status)

**Comment by cost17** [comment]
Hi,

please find below what I want to monitor:

CPU utilization
CPU Temperature
Memory utilization
Check if replication between Infoblox appliances is working
Check if appliance is Active or Passive in Grid
General information about this appliance
Configured ip addresses of this appliance
DNS statistics for domain
DHCP statistics
System Temperature
DNS Query Responses per Second
Disk Space (path)
Swap
Load
PSU status
Fan
Interface - list-interfaces (Traffic, Errors, Speed)

Thank you
