### ISSUE TITLE
apps::protocols::x509::plugin failed to accept or ssl handshake 

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#716]
Hi,

I read this topic, but this cannot fix it : https://github.com/centreon/centreon-plugins/issues/641

centreon_plugins.pl --plugin=apps::protocols::x509::plugin --mode=validity --validity-mode=expiration --hostname=IP --port=443 --servername=ad.lan.net 
CRITICAL: failed to accept or ssl handshake: ,SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed |

This check work correctly with public website and valid ssl certificate.
I think pb is that not root certicate present.

In your topic, you say, use : --ssl-opt="SSL_verify_mode=SSL_VERIFY_NONE"
But I can not : Unknown option: ssl-opt at /usr/local/nagios/libexec/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67. 

 Thanks,

**Comment by romsworld** [comment]
:),

You can close it : I do an  git pull and it's ok now,

Thanks,

**Comment by Sims24** [comment]
Glad to see you were able to fix it with the last version. 

Thanks !
