### ISSUE TITLE
[network::juniper::ssg::plugin] Check NSRP

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#717]
Hi

Could you add check for NSRP ( Master/slave )

nsrpVsdMemberTable | 1.3.6.1.4.1.3224.6.2.2
-- | --
nsrpVsdMemberEntry | 1.3.6.1.4.1.3224.6.2.2.1
nsrpVsdMemberGroupId | 1.3.6.1.4.1.3224.6.2.2.1.1
nsrpVsdMemberUnitId | 1.3.6.1.4.1.3224.6.2.2.1.2
nsrpVsdMemberStatus | 1.3.6.1.4.1.3224.6.2.2.1.3
nsrpVsdMemberPriority | 1.3.6.1.4.1.3224.6.2.2.1.4
nsrpVsdMemberPreempt | 1.3.6.1.4.1.3224.6.2.2.1.5

Actually I use this one : https://secure.opsview.com/svn/opsview/trunk/opsview-core/nagios-plugins/check_snmp_netscreen_nsrp

Thanks,

**Comment by garnier-quentin** [comment]
I need a snmpwalk

**Comment by romsworld** [comment]
Do you need more ?
it's difficult to give upper level, there are confidential information.

MASTER
SNMPv2-SMI::enterprises.3224.6.2.2.1.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.3224.6.2.2.1.1.1 = INTEGER: 0
SNMPv2-SMI::enterprises.3224.6.2.2.1.2.0 = INTEGER: 11427584
SNMPv2-SMI::enterprises.3224.6.2.2.1.2.1 = INTEGER: 11441536
SNMPv2-SMI::enterprises.3224.6.2.2.1.3.0 = INTEGER: 3
SNMPv2-SMI::enterprises.3224.6.2.2.1.3.1 = INTEGER: 2
SNMPv2-SMI::enterprises.3224.6.2.2.1.4.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3224.6.2.2.1.4.1 = INTEGER: 95
SNMPv2-SMI::enterprises.3224.6.2.2.1.5.0 = INTEGER: 2
SNMPv2-SMI::enterprises.3224.6.2.2.1.5.1 = INTEGER: 2

SLAVE
SNMPv2-SMI::enterprises.3224.6.2.2.1.1.0 = INTEGER: 0
SNMPv2-SMI::enterprises.3224.6.2.2.1.1.1 = INTEGER: 0
SNMPv2-SMI::enterprises.3224.6.2.2.1.2.0 = INTEGER: 11441536
SNMPv2-SMI::enterprises.3224.6.2.2.1.2.1 = INTEGER: 11427584
SNMPv2-SMI::enterprises.3224.6.2.2.1.3.0 = INTEGER: 2
SNMPv2-SMI::enterprises.3224.6.2.2.1.3.1 = INTEGER: 3
SNMPv2-SMI::enterprises.3224.6.2.2.1.4.0 = INTEGER: 95
SNMPv2-SMI::enterprises.3224.6.2.2.1.4.1 = INTEGER: 100
SNMPv2-SMI::enterprises.3224.6.2.2.1.5.0 = INTEGER: 0
SNMPv2-SMI::enterprises.3224.6.2.2.1.5.1 = INTEGER: 0

**Comment by garnier-quentin** [comment]
Please send it by email

**Comment by romsworld** [comment]
With -On

Master
.1.3.6.1.4.1.3224.6.2.2.1.1.0 = INTEGER: 0
.1.3.6.1.4.1.3224.6.2.2.1.1.1 = INTEGER: 0
.1.3.6.1.4.1.3224.6.2.2.1.2.0 = INTEGER: 11427584
.1.3.6.1.4.1.3224.6.2.2.1.2.1 = INTEGER: 11441536
.1.3.6.1.4.1.3224.6.2.2.1.3.0 = INTEGER: 3
.1.3.6.1.4.1.3224.6.2.2.1.3.1 = INTEGER: 2
.1.3.6.1.4.1.3224.6.2.2.1.4.0 = INTEGER: 100
.1.3.6.1.4.1.3224.6.2.2.1.4.1 = INTEGER: 95
.1.3.6.1.4.1.3224.6.2.2.1.5.0 = INTEGER: 2
.1.3.6.1.4.1.3224.6.2.2.1.5.1 = INTEGER: 2

Slave
.1.3.6.1.4.1.3224.6.2.2.1.1.0 = INTEGER: 0
.1.3.6.1.4.1.3224.6.2.2.1.1.1 = INTEGER: 0
.1.3.6.1.4.1.3224.6.2.2.1.2.0 = INTEGER: 11441536
.1.3.6.1.4.1.3224.6.2.2.1.2.1 = INTEGER: 11427584
.1.3.6.1.4.1.3224.6.2.2.1.3.0 = INTEGER: 2
.1.3.6.1.4.1.3224.6.2.2.1.3.1 = INTEGER: 3
.1.3.6.1.4.1.3224.6.2.2.1.4.0 = INTEGER: 95
.1.3.6.1.4.1.3224.6.2.2.1.4.1 = INTEGER: 100
.1.3.6.1.4.1.3224.6.2.2.1.5.0 = INTEGER: 0
.1.3.6.1.4.1.3224.6.2.2.1.5.1 = INTEGER: 0
