### ISSUE TITLE
[hardware::sensors::netbotz::snmp::plugin] Wrong OID for Netbotz 250

### ISSUE THREAD

**Issue by Tulan** [centreon/centreon-plugins#720]
Hello,
I am actually deploying APC Netbotz 250 monitor devices, and the Centreon plugin "hardware::sensors::netbotz::snmp::plugin" is not working with this device.
The plugin search datas in OID "1.3.6.1.4.1.5528" but the device store its datas in OID "1.3.6.1.4.1.318".
Attached a snmpwalk extract and the last version of the MIB.

Regads,
Nicolas

[powernet421.txt](https://github.com/centreon/centreon-plugins/files/1179436/powernet421.txt)
[netbotz250.txt](https://github.com/centreon/centreon-plugins/files/1179461/netbotz250.txt)

**Comment by Tulan** [comment]
Hello,
do you have any news about this issue ?

Nicolas

**Comment by garnier-quentin** [comment]
You should try the apc plugin

**Comment by garnier-quentin** [comment]
Netbotz was buyed by APC. Netbotz 200/250 uses powernet mib. We can monitor:
- memSensorsStatusTable ("clim_fond", "clim_entree")
- memInputStateSensors ("Fluide faux-plancher")

**Comment by garnier-quentin** [comment]
There is a new plugin (compatible netbotz 250): hardware::sensors::apc::snmp

https://github.com/centreon/centreon-plugins/pull/4073
