### ISSUE TITLE
Unknown output with vmware::connector and datastore-vm mode

### ISSUE THREAD

**Issue by cmoi42** [centreon/centreon-plugins#722]
Hi,

With some machines, I get an UNKNOWN status when using datastore-vm mode with "vmware::connector::plugin" whereas plugins gathering latency correctly in perfdata : 

/usr/share/centreon-plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=datastore-vm --custommode=connector --connector-hostname='MY_CONNECTOR' --vm-hostname='MY_VM' --container='MY_CONTAINER' --sampling-period=20 --verbose --nopoweredon-status='OK'
UNKNOWN: Can't get a single datastore. | 'max_total_latency'=38.00ms;;;0;

Regards.

**Comment by garnier-quentin** [comment]
Which datastore type do you have ? VMFS, NFS,... ?

**Comment by cmoi42** [comment]
Hi,

It's VMFS.

Regards.

**Comment by garnier-quentin** [comment]
So it's really weird. i cannot tell it. Need an access to look.

**Comment by garnier-quentin** [comment]
Without an access, i can't tell. I close it. You can send me en email if you want me to take a look.
