### ISSUE TITLE
[database::mssql::plugin] Mode "databases-size" - Add option for growth

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon-plugins#723]
Hello,

In MsSQL we can use the mode "auto-grow", as long as the file is not 100% full, it will not grow.

A maximum size limit has been configured on these files. It could be great to be able to monitor the occupation of the datafiles not by their current size, but with their maximum size.

You can get "Max Size" and see if "Growth" is used with this query:
https://raresql.com/2013/02/19/sql-server-best-way-to-check-all-database-autogrowth-settings/

regards

**Comment by romsworld** [comment]
Hello,

Has this option been implemented?

**Comment by romsworld** [comment]
Hi,

Any news about this option ?

Thanks,

**Comment by garnier-quentin** [comment]
I'm other subject right now. but i ll try to take a look soon

**Comment by garnier-quentin** [comment]
It can be tested now. mssql mode databases-size should be accurate now
