### ISSUE TITLE
network::cisco::meraki::cloudcontroller::snmp::plugin Add interface monitoring

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#724]
Hi,

Please add interface monitoring mode to Cisco Meraki plugin.
If you need snmpwalk, then let me know, I can sent it to your email.

http://www.circitor.fr/Mibs/Html/M/MERAKI-CLOUD-CONTROLLER-MIB.php is the correct MIB to use.

**Comment by garnier-quentin** [comment]
It's not the standard mib for interfaces ?

**Comment by kadrika** [comment]
No it is not standard. I will send you the snmpwalk in few minutes.

**Comment by garnier-quentin** [comment]
I add it in mode 'device-usage'. Could you test it ?

**Comment by kadrika** [comment]
It is working nicely, so you can close this.
