### ISSUE TITLE
Can't read mac address - unreadable output

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon-plugins#725]
What I try to do:
get the mac address of specific network interface

Problem description:
Instead of getting the mac address, I get some sort of binary output printed to screen (see output below)

When running an SNMP walk:
[root@server plugins]# snmpwalk -v2c -c mycomm 10.1.2.3 .1.3.6.1.2.1.2.2.1.6 -ObentU
.1.3.6.1.2.1.2.2.1.6.1 = STRING:
.1.3.6.1.2.1.2.2.1.6.2 = STRING: 0:aa:bb:cc:dd:7e   <-- for example, i want to get this value
.1.3.6.1.2.1.2.2.1.6.3 = STRING: 0:aa:bb:cc:dd:7f
.1.3.6.1.2.1.2.2.1.6.4 = STRING: 0:aa:bb:cc:dd:80
.1.3.6.1.2.1.2.2.1.6.5 = STRING: 0:aa:bb:cc:dd:81
.1.3.6.1.2.1.2.2.1.6.6 = STRING: 0:aa:bb:cc:dd:82
.1.3.6.1.2.1.2.2.1.6.7 = STRING: 0:aa:bb:cc:dd:83
.1.3.6.1.2.1.2.2.1.6.8 = STRING: 0:aa:bb:cc:dd:84
.1.3.6.1.2.1.2.2.1.6.9 = STRING: 0:aa:bb:cc:dd:85
.1.3.6.1.2.1.2.2.1.6.10 = STRING: 0:aa:bb:cc:dd:86
.1.3.6.1.2.1.2.2.1.6.11 = STRING: 0:aa:bb:cc:dd:87

When trying to get one of those values using the centreon-plugins:
[root@server plugins]# /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=snmp_standard::plugin --mode=string-value --oid=.1.3.6.1.2.1.2.2.1.6.2 --hostname=10.1.2.3 --snmp-community=mycomm --snmp-version=2c  --format-ok='%{details_ok}'
OK:▒_~ |

I get the same result when I create my own plugin with the following code:
my $mac_Mgmt = '.1.3.6.1.2.1.2.2.1.6.2';
my $result_all = $self->{snmp}->get_leef(oids => [ $mac_Mgmt ] , nothing_quit => 1);
print $result_all->{$mac_Mgmt}."\n";

[root@server plugins]# git pull
Already up-to-date.

Please advise

Kind regards,
Bob

**Comment by Sims24** [comment]
Hi, 

Might be something similar to discussion here : -

- https://github.com/kamakazikamikaze/easysnmp/issues/14

So depends on what you are getting (seems binary here), you need to manage the conversion I guess. 

Thanks, 
Simon

**Comment by garnier-quentin** [comment]
I could had an option to change in hexadecimal.

**Comment by garnier-quentin** [comment]
You can use that option now:
```
--convert-custom-values='join(":", unpack("(H2)*", $value))'
```
