### ISSUE TITLE
checkpoint - hardware - psu -- missing state

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon-plugins#726]
Problem description:
Check returns UNKNOWN state given that the state Dummy is returned for an optional PSU slot.

[root@server plugins]# /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=network::checkpoint::snmp::plugin --mode=hardware --hostname=10.1.2.3 --snmp-community=mycomm --snmp-version=2c --component=psu
UNKNOWN: Power supply '2.0' status is 'Dummy' |

I think that the status "Dummy" should be regarded as "OK" (it is a placeholder for an optional PSU).

Relevant file:
network/checkpoint/snmp/mode/hardware.pm

Change suggested:
        psu => [
            ['up', 'OK'],
            ['down', 'CRITICAL'],
            ['dummy', 'OK'],    <- this line should be added
            ['.*', 'UNKNOWN'],
        ],

**Comment by garnier-quentin** [comment]
Thanks!
