### ISSUE TITLE
network/cisco/standard/snmp/plugin.pm memory usage reporting incorrectly

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#727]
Hi,

I have Cisco Catalyst L3 switch and I try to monitor its memory usage.
From the SNMPWALK I get these values:
SNMPv2-SMI::enterprises.9.9.48.1.1.1.2.1 = STRING: "Processor"
SNMPv2-SMI::enterprises.9.9.48.1.1.1.2.7 = STRING: "IOS Process stack"
SNMPv2-SMI::enterprises.9.9.48.1.1.1.3.1 = INTEGER: 0
SNMPv2-SMI::enterprises.9.9.48.1.1.1.3.7 = INTEGER: 0
SNMPv2-SMI::enterprises.9.9.48.1.1.1.4.1 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.48.1.1.1.4.7 = INTEGER: 1
SNMPv2-SMI::enterprises.9.9.48.1.1.1.5.1 = Gauge32: 463183656
SNMPv2-SMI::enterprises.9.9.48.1.1.1.5.7 = Gauge32: 9579900
SNMPv2-SMI::enterprises.9.9.48.1.1.1.6.1 = Gauge32: 73687256
SNMPv2-SMI::enterprises.9.9.48.1.1.1.6.7 = Gauge32: 7197316
SNMPv2-SMI::enterprises.9.9.48.1.1.1.7.1 = Gauge32: 71237588
SNMPv2-SMI::enterprises.9.9.48.1.1.1.7.7 = Gauge32: 5770992

With the plugin pack command I get:
bash-4.1$ ./centreon_plugins.pl --hostname=1.2.3.4 --plugin=network/cisco/standard/snmp/plugin.pm --snmp-version=2c --snmp-community=xxx --mode=memory --critical=80
CRITICAL: Memory 'Processor' Total: 512.00 MB Used: 441.59 MB (86.25%) Free: 70.41 MB (13.75%) | 'used_Processor'=463035712B;;0.00:429496729.60;0;536870912 'used_IOS Process stack'=9551720B;;0.00:13421772.80;0;16777216

Device itself shows:
System memory   : 4004464K total, 1806052K used, 2198412K free, 150332K kernel reserved
Lowest(b)       : 1750369508

                Total(K)     Used(K)      Free(K)
Process         4004464      1806052      2198412     
Config          0            0            0

**Comment by kadrika** [comment]
I found the OID where the free memory is shown correctly:
snmpwalk 1.2.3.4 -v2c -c xxx 1.3.6.1.4.1.9.9.109.1.1.1.1.13
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.13.2 = Gauge32: 2198296
SNMPv2-SMI::enterprises.9.9.109.1.1.1.1.13.3 = Gauge32: 2130836

**Comment by garnier-quentin** [comment]
Could you provide me the full snmpwalk for that equipment ? 
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.4.1.9.9.109.1.1.1.1 > cisco_process.snmpwalk
snmpwalk -ObentU -v 2c -c public IP .1.3.6.1.2.1.47.1.1.1.1.2 > cisco_entity.snmpwalk

**Comment by garnier-quentin** [comment]
Add an option to change the order: --check-order='process'
