### ISSUE TITLE
Create command Via Web Cisco Smallbussiness

### ISSUE THREAD

**Issue by tatostian** [centreon/centreon-plugins#728]
## Bug/Question
Hello!! Friends

I am trying to monitor CPU a cisco Small business SG500x via cli gives me values but when I want to create the command via web I get as unknown result.

best regards

this is the command 
$USER1$/centreon-plugins/centreon_plugins.pl --plugin=network::cisco::smallbusiness::standard::snmp::plugin --mode=cpu --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$'

![image](https://user-images.githubusercontent.com/30626406/28827237-e3613810-769a-11e7-9248-9e9d4d5a6ecb.png)

**Comment by garnier-quentin** [comment]
Sorry but you should ask here:
https://github.com/centreon/centreon

But you should look the documentation:
https://documentation.centreon.com/docs/centreon/en/2.8.x/configuration_guide/commands.html
