### ISSUE TITLE
unable to check esx status with plugin vmware ( esxi 5.5)

### ISSUE THREAD

**Issue by WMPintegra** [centreon/centreon-plugins#729]
## Bug/Question

# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=status-host --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='vcenter' --esx-hostname='ESXI5' --verbose

UNKNOWN: Cannot find 'HostSystem' object | 

i dont understant what i have forgert in my commandline ?

**Comment by garnier-quentin** [comment]
Could you use the mode getmap ? --mode=getmap

**Comment by WMPintegra** [comment]
like this ? 

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=getmap --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='frd580p01vca' --esx-hostname='AU-SS-ESX002' --verbose
Cannot find 'HostSystem' object

**Comment by garnier-quentin** [comment]
Like this :)
```
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=getmap --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='vcenter' --verbose
```

**Comment by WMPintegra** [comment]
ok, i ve got a response like this :

 ESXI1 [v5.5.0] :
      VM1 [poweredOn]
      VM2 [poweredOn]
       ....

  ESX2 [v5.5.0] :
      VM3 [poweredOn]
      VM4 [poweredOn]
      
     ...

**Comment by garnier-quentin** [comment]
So you should see the name of your esx server ;) You can use ESXI1 or ESX2 for example.

**Comment by WMPintegra** [comment]
yes, i see all esxi name connected to my vcenter :).

"You can use ESXI1 or ESX2 for example." use how ?

**Comment by garnier-quentin** [comment]
Like:
```
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=status-host --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='vcenter' --esx-hostname='ESX2' --verbose
```

**Comment by gram1589** [comment]
I am a new member I also have the problem "KNOWN: Cannot find 'HostSystem' object |
"
however "./centreon_plugins.pl --plugin = apps :: vmware :: connector :: plugin --custommode = connector --connector-hostname = localhost --container = default --mode = getmap" is ok
Can anyone help me? Thank you
