### ISSUE TITLE
[apps::tomcat::web::plugin] - Use of uninitialized value in string 

### ISSUE THREAD

**Issue by ConstantinNegoita** [centreon/centreon-plugins#731]
#### The tomcat::web::traffic plugin generate errors when executed with --speed option due to the fact that the traffic.pm does not configure units as plugin argument.

bash-4.2$ ./centreon_plugins.pl --plugin=apps::tomcat::web::plugin --mode=traffic --hostname=192.168.1.10 --credentials --username=username --password=password --name=http-nio-8080  --warning-in=80 --critical-in=90 --warning-out=80 --critical-out=90 --speed=100

Use of uninitialized value in string eq at /usr/lib/centreon/plugins/centreon-plugins/apps/tomcat/web/mode/traffic.pm line 241.
Use of uninitialized value in uc at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/output.pm line 170.
Use of uninitialized value in uc at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/output.pm line 173.
Use of uninitialized value in uc at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/output.pm line 176.
Use of uninitialized value $options{"exit_litteral"} in uc at /usr/lib/centreon/plugins/centreon-plugins/centreon/plugins/output.pm line 151.
OK:  | 'traffic_in'=0.00b/s;0.00:800000.00;0.00:900000.00;0;1000000 'traffic_out'=366.83b/s;0.00:800000.00;0.00:900000.00;0;1000000

**Comment by garnier-quentin** [comment]
Could you give me the result of the tomcat page ? /manager/status?XML=true

**Comment by ConstantinNegoita** [comment]
<?xml version="1.0" encoding="utf-8"?><?xml-stylesheet type="text/xsl" href="/manager/xform.xsl" ?>
<status><jvm><memory free='421798880' total='514850816' max='954728448'/><memorypool name='PS Eden Space' type='Heap memory' usageInit='134742016' usageCommitted='134742016' usageMax='313524224' usageUsed='81767760'/><memorypool name='PS Old Gen' type='Heap memory' usageInit='358088704' usageCommitted='358088704' usageMax='716177408' usageUsed='0'/><memorypool name='PS Survivor Space' type='Heap memory' usageInit='22020096' usageCommitted='22020096' usageMax='22020096' usageUsed='11284176'/><memorypool name='Code Cache' type='Non-heap memory' usageInit='2555904' usageCommitted='9240576' usageMax='251658240' usageUsed='9050048'/><memorypool name='Compressed Class Space' type='Non-heap memory' usageInit='0' usageCommitted='2359296' usageMax='1073741824' usageUsed='2158664'/><memorypool name='Metaspace' type='Non-heap memory' usageInit='0' usageCommitted='20971520' usageMax='-1' usageUsed='20132544'/></jvm><connector name='"ajp-nio-8009"'><threadInfo  maxThreads="200" currentThreadCount="10" currentThreadsBusy="0" /><requestInfo  maxTime="0" processingTime="0" requestCount="0" errorCount="0" bytesReceived="0" bytesSent="0" /><workers><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /></workers></connector><connector name='"http-nio-8080"'><threadInfo  maxThreads="200" currentThreadCount="10" currentThreadsBusy="1" /><requestInfo  maxTime="246" processingTime="2048" requestCount="191" errorCount="7" bytesReceived="0" bytesSent="513530" /><workers><worker  stage="R" requestProcessingTime="0" requestBytesSent="0" requestBytesReceived="0" remoteAddr="&#63;" virtualHost="&#63;" method="&#63;" currentUri="&#63;" currentQueryString="&#63;" protocol="&#63;" /><worker  stage="S" requestProcessingTime="2" requestBytesSent="0" requestBytesReceived="0" remoteAddr="10.43.7.18" virtualHost="10.41.7.22" method="GET" currentUri="/manager/status" currentQueryString="XML=true" protocol="HTTP/1.1" /></workers></connector></status>

**Comment by ConstantinNegoita** [comment]
![tomcat](https://user-images.githubusercontent.com/5267728/28877699-d10e9cd2-77a5-11e7-9497-c664dc303421.png)

**Comment by garnier-quentin** [comment]
Could you give me a xml file ? :)

**Comment by ConstantinNegoita** [comment]
[status.xml.zip](https://github.com/centreon/centreon-plugins/files/1199632/status.xml.zip)

Sure, see attached

**Comment by garnier-quentin** [comment]
It should be fixed. Could you test with following command ?
```
./centreon_plugins.pl --plugin=apps::tomcat::web::plugin --mode=traffic --hostname=192.168.1.10 --credentials --username=username --password=password --filter-name=http-nio-8080 --warning-in=80 --critical-in=90 --warning-out=80 --critical-out=90 --speed-in=100 --speed-out=100
```

**Comment by ConstantinNegoita** [comment]
Thank's Quentin, It works ok now.

OK: Connector 'http-nio-8080' Traffic In : 0.00b/s (0.00% on 100.00Mb), Traffic Out : 3.49Kb/s (0.00% on 100.00Mb) | 'traffic_in'=0.00b/s;0:80000000;0:90000000;0;100000000 'traffic_out'=3489.14b/s;0:80000000;0:90000000;0;100000000
