### ISSUE TITLE
[network::alcatel::omniswitch::snmp::plugin] Spanning-tree #can't get a single value#

### ISSUE THREAD

**Issue by JulienJean** [centreon/centreon-plugins#732]
Hi, 

I am trying to monitor an Alcatel switch 6850. 
**All modes are working well**. **Except** Spanning-tree which gives this error : 
SNMP GET Request : Cant get a single value. 

There is my command : /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::alcatel::omniswitch::snmp::plugin --mode=spanning-tree --hostname=10.xx.xx.xx --snmp-version=2 --snmp-port=161 --snmp-username=xxxx --snmp-community=xxxx

I repeat that I tried all others modes and they are working well. So I don't think it can come from the switch. 

An idea ? 

Thanks you, 
Regard, 
Julien

**Comment by garnier-quentin** [comment]
The messasge means there is no snmp standard oid in that equipment for spanning tree.

**Comment by JulienJeanCircet** [comment]
Ok thanks, 
So I'll need to answer Alcatel for OIDs that I need ?

**Comment by JulienJean** [comment]
Resolved by using OID : .1.3.6.1.4.1.6486.800.1.2.1.12.1.1.1.2.1.3.0.$_HOSTSTACK$0$_HOSTSTPPORTBLK$.
With plugin snmp_standard and mode numeric_value.
