### ISSUE TITLE
HW-Storage-EMC-DataDomain-Filesystem pre-comp value

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#733]
Hello,

Wit the the latest version of datadomain (EMC) OS 6.0.1.20 the behaviour of the plugin (the latest version on Git) is different:

The data "pre-comp" now display "free 0" (pre-compression of the untreated data before compression and deduplication). It may be useful to display the post-comp free instead (the real remaining value).

perl /tmp/centreon-plugins/centreon_plugins.pl --plugin=storage::emc::DataDomain::plugin --mode=filesystem-usage --hostname=172.16.100.97 --snmp-version='3' --snmp-community='public' --snmp-username XXX --authpassphrase XXX --authprotocol MD5 --snmp-timeout 5 --filesystem='.*' --name --regexp --warning-usage='95' --critical-usage='97' --verbose

CRITICAL: Filesystem '/data: pre-comp' Usage Total: 1387.71 TB Used: 1387.71 TB (100.00%) Free: 0.00 B (0.00%) | 'used_/ddvar'=8053063680B;0:28561532518;0:29162827939;0;30064771072 'used_/data: post-comp'=39867389680025B;0:43061814556097;0:43968379073068;0;45328225848524 'used_/data: pre-comp'=1525806244508467B;0:1449515932283043;0:1480032057173213;0;1525806244508467 'used_Index'=410062002585B;0:565722354809;0:577632299121;0;595497215589 'used_/ddvar/core'=214748364B;0:30499636509;0:31141734119;0;32104880536
Filesystem '/ddvar' Usage Total: 28.00 GB Used: 7.50 GB (26.79%) Free: 20.50 GB (73.21%)
Filesystem '/data: post-comp' Usage Total: 41.23 TB Used: 36.26 TB (87.95%) Free: 4.97 TB (12.05%)
**Filesystem '/data: pre-comp' Usage Total: 1387.71 TB Used: 1387.71 TB (100.00%) Free: 0.00 B (0.00%)**
Filesystem 'Index' Usage Total: 554.60 GB Used: 381.90 GB (68.86%) Free: 172.70 GB (31.14%)
Filesystem '/ddvar/core' Usage Total: 29.90 GB Used: 204.80 MB (0.67%) Free: 29.70 GB (99.33%)

**Comment by garnier-quentin** [comment]
I need the snmpwalk and the mib file.

**Comment by tseegers** [comment]
Hello Quentin, i have just sent it to you by email

**Comment by garnier-quentin** [comment]
Can be filtered:
```
--filesystem='^(?!(.*pre-comp)$)' --name --regexp
```
