### ISSUE TITLE
radius plugin fails

### ISSUE THREAD

**Issue by bdeschut** [centreon/centreon-plugins#735]
[root@server plugins]# git pull
Already up-to-date.

[root@server plugins]# /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::protocols::radius::plugin --mode=login
UNKNOWN: Cannot load module --mode.
Can't locate Authen/Radius.pm in @INC (@INC contains: /usr/lib/centreon/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/apps/protocols/radius/mode/login.pm line 28.
BEGIN failed--compilation aborted at /usr/lib/centreon/plugins/apps/protocols/radius/mode/login.pm line 28.
Compilation failed in require at /usr/lib/centreon/plugins/centreon/plugins/misc.pm line 221.

Server details: CentOS release 6.9 (Final) installed using ces-standard-3.4-x86_64

I just want to notify you of this problem, I already have an alternative way for checking radius. Feel free to close the ticket if you think this is related to only my server rather than a plugin problem.

PS: I tried installing "yum install freeradius-perl.x86_64" because it contained both perl and radius, but this didn't resolve the problem

Kind regards,
Bob

**Comment by garnier-quentin** [comment]
I give you rpm ;)
[radius.zip](https://github.com/centreon/centreon-plugins/files/1214853/radius.zip)
