### ISSUE TITLE
[apps::protocols::http::plugin] SSL, autosigned certificates

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon-plugins#736]
Hello,

I can't monitor URL in HTTPS who have auto signed SSL certificates.

Version : Global Version: 20170811
OS : CentOS 7

Command line  : ./centreon_plugins.pl --plugin apps::protocols::http::plugin --mode response --hostname 10.74.0.159 --port 443 --timeout 3 --proto https --urlpath /

Output :
*******************************************************************
 Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
 is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
 together with SSL_ca_file|SSL_ca_path for verification.
 If you really don't want to verify the certificate and keep the
 connection open to Man-In-The-Middle attacks please set
 SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
*******************************************************************
  at /usr/lib64/perl5/LWP/Protocol/http.pm line 35.
length() used on @array (did you mean "scalar(@array)"?) at /usr/lib64/perl5/IO/Compress/Zlib/Extra.pm line 198.
CRITICAL: 500 Can't read entity body: Ressource temporairement non disponible |

Regards.

**Comment by garnier-quentin** [comment]
Which version do you have for 'perl-IO-Compress' ?

**Comment by BenoitPoulet** [comment]
This one : 
$ rpm -q perl-IO-Compress
perl-IO-Compress-2.061-2.el7.noarch

**Comment by garnier-quentin** [comment]
I can't reproduce. Are you available for a remote session ?

**Comment by BenoitPoulet** [comment]
Hello,

I have re-installed all my CentOS 7 and can't reproduce it anymore. Probably a library problem.

You can close the issue.

**Comment by garnier-quentin** [comment]
Thanks for the feedback.
