### ISSUE TITLE
error plugin apps::vmware::connector::plugin

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#737]
Hello,
I want to supervise my esxi, with this plugin (apps::vmware::connector::plugin)

`perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=localhost --container=default --verbose --mode=health-host --esx-hostname='.*' --filter --disconnect-status='ok'`

**Erreur : UNKNOWN: Cannot get response (timeout received)**

I launch it manually with option --severity=debug : 
**Unknown option: severity at /usr/share/perl5/vendor_perl/centreon/plugins/alternative/Getopt.pm line 66.** 

I have the latest version of centreon (v. 2.8.11 ).

Thanks for help
Best regards

**Comment by garnier-quentin** [comment]
Have you installed the centreon-vmware daemon ?

**Comment by boogaaloo** [comment]
Thank you for your reply. I followed the procedure of the documentation of Centreon.
This was an authentication problem.
Thank you again
