### ISSUE TITLE
Add Alpha Technologies UPS plugin

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#738]
Hi,

Could you please add plugin for Alpha Technologies UPS.
MIB file can be found in here: https://tools.alpha.ca/downloads/docs/035-092-01-REVJ_FXM_V2.00.04_SNMP_MIB.MIB

If you need snmpwalk, then let me know, I can send it to you via email.

From modes part - same modes as standard UPS plugin has (alarms, voltage etc).

**Comment by garnier-quentin** [comment]
Could you give us the snmpwalk also ?

**Comment by kadrika** [comment]
Sent it to your email. Thanks!

**Comment by kadrika** [comment]
Any update on this?

**Comment by garnier-quentin** [comment]
I'm doing it monday. I'll put in: hardware/ups/argus/snmp
