### ISSUE TITLE
Documentation access for tomcat-jmx

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#739]
Hello, 

i had a IMP licence and installed the plugin for Tomcat-JMX but did not use it.
Now, my licence is expired and i can not access to the plugin documentation because the blue book is now unclickable. 
i know that you can access to the doc by this kinf of url : 
http://Mycentreon/centreon/main.php?p=65099&min=1&slug=Applications-selenium.

Can any one provide the link for tomcat jmx please ?

Thank you

**Comment by garnier-quentin** [comment]
Hi,

Sorry. I can't give you that information. But i can give you a link useful (maybe):
http://nyal.developpez.com/tutoriels/java/supervision-tomcat-avec-couple-jolokia-centreon-plugins/

**Comment by saharawolf** [comment]
that is not cool, 
normaly if we paid for some thing we shoud keep it. you can disable access to things that are not installed after expiration  but not to the one we already own.

**Comment by garnier-quentin** [comment]
I'm only managed the centreon-plugins. Not the pack.
