### ISSUE TITLE
centreon_plugins.pl (VMware) via GUI

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#740]
Hello,

After testing on the command line,
`perl centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=health-host --esx-hostname='xxxx' --filter --disconnect-status='ok'`

I try to set up a service via the GUI.
I created the command :
`$CENTREONPLUGINS$/centreon_plugins.pl --plugin=$_SERVICEPLUGIN$ --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=$_SERVICEMODE$ --esx-hostname='$HOSTNAME$' --filter --disconnect-status='ok'`

I do the service template then host template. But I get a  _(No output returned from plugin)_

How do I debug?

Thanks,
Best regards

**Comment by garnier-quentin** [comment]
It's not really a centreon-plugins problem. You have the command used in the service details page.

**Comment by boogaaloo** [comment]
Thank you for your reply.

This is my command used :
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=health-host --esx-hostname='xxxx' --filter --disconnect-status='ok'

Everything is the same as the command line.

**Comment by boogaaloo** [comment]
yes 

```
OK: 'xxxx' 365 health checks are green | 'problems'=0;;;0;365
Checking xxxx
365 health checks are green
```

**Comment by garnier-quentin** [comment]
Do you test it with centengine same user ?

**Comment by boogaaloo** [comment]
CLI or GUI ?

**Comment by garnier-quentin** [comment]
the cli

**Comment by boogaaloo** [comment]
With users nagios and centreon-engine, I get the same result
```
OK: 'xxxx' 365 health checks are green | 'problems'=0;;;0;365
Checking xxxx
365 health checks are green
```
That's what you wanted me to do ?

**Comment by garnier-quentin** [comment]
Do you set the perl connector (in the centreon command configuration) ?

**Comment by boogaaloo** [comment]
nop :)
I try and I tell you

**Comment by garnier-quentin** [comment]
Don't set it :)

**Comment by boogaaloo** [comment]
ok :)

**Comment by boogaaloo** [comment]
Can we collect logs on the execution of the command ?

**Comment by boogaaloo** [comment]
So...
The path value for the macro $CENTREONPLUGINS$ is
`/usr/lib/centreon/plugins`
However the script _centreon_plugins.pl_ is located at _/usr/lib/nagios/plugins_.
Is this normal ?

**Comment by garnier-quentin** [comment]
I think that's your problem. The command from centreon doesn't use the same command.

**Comment by boogaaloo** [comment]
In my folder _/usr/lib/nagios/plugins_, I've got this files & folder :
```
apps
Centreon
centreon.conf
centreon-plugins
centreon-plugins.pl
centreon.pm
```

Do I have to transfer these files to the folder _/usr/lib/centreon/plugins_ ?

**Comment by boogaaloo** [comment]
More generally, does all the files whose owner is centreon should be transferred to this folder ?

**Comment by boogaaloo** [comment]
It works !

**Comment by garnier-quentin** [comment]
Nice! I close it.

**Comment by FlorentinC** [comment]
I have the same problem with my command : 
centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --component=cpu --hostname='***' --snmp-version=2c --snmp-community=public
How did you manage it ?

**Comment by FlorentinC** [comment]
I resolved it ! 
I had to change the folder location and the permissions.
