### ISSUE TITLE
[apps::vmware::connector::plugin] mode tools-vm - issue on tools status filter

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#741]
Hi,

I try to filter the status "not running" and "not installed" and skip "not uptodate" and it seems don't work...
If I specify "--tools-notup2date-status=ok" it skip  the "not installed" or "not running" in the output.
I use the Plugin-Pack VMware vSphere v 3.1.2

This is some tests and results I tried:
1) without args to force status
` /usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --vm-hostname='^(?!_)+' --filter --disconnect-status='ok' --nopoweredon-skip --filter-description='^(?!NO_VMTOOLS)+'  --filter-perfdata='none'`

> CRITICAL: 2 VM with VMTools not running WARNING: 977 VM with VMTools not up-to-date - 14 VM with VMTools not installed |
=> All vmtools states are displayed. but "vmtools not-installed" default state is critical (as mentionned in --help), not warning and here it's displayed with WARNING status

Result expected for this case:
> CRITICAL: 2 VM with VMTools not running - 14 VM with VMTools not installed WARNING: 977 VM with VMTools not up-to-date |

2) only with arg --tools-notup2date-status=ok
`/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --vm-hostname='^(?!_)+' --filter --disconnect-status='ok' --nopoweredon-skip --filter-description='^(?!NO_VMTOOLS)+'  --filter-perfdata='none' --tools-notup2date-status=ok`

> CRITICAL: 2 VM with VMTools not running |
=> "Tools Not Installed" does not appear in output, while the default state is critical... 

Result expected for this case:
> CRITICAL: 2 VM with VMTools not running - 14 VM with VMTools not installed |

3) arg  --tools-notinstalled-status=critical
`/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --vm-hostname='^(?!_)+' --filter --disconnect-status='ok' --nopoweredon-skip --filter-description='^(?!NO_VMTOOLS)+'  --filter-perfdata='none' --tools-notinstalled-status=critical`
> CRITICAL: 2 VM with VMTools not running WARNING: 977 VM with VMTools not up-to-date - 14 VM with VMTools not installed |
=> tools not installed stay displayed on Warning state

Result expected for this case:
>  CRITICAL: 2 VM with VMTools not running - 14 VM with VMTools not installed WARNING: 977 VM with VMTools not up-to-date |

4) arg --tools-notinstalled-status=warning => same result
`/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --vm-hostname='^(?!_)+' --filter --disconnect-status='ok' --nopoweredon-skip --filter-description='^(?!NO_VMTOOLS)+'  --filter-perfdata='none' --tools-notinstalled-status=warning`
> CRITICAL: 2 VM with VMTools not running WARNING: 977 VM with VMTools not up-to-date - 14 VM with VMTools not installed |
=> OK.

5) arg --tools-notrunning-status=warning
` /usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --vm-hostname='^(?!_)+' --filter --disconnect-status='ok' --nopoweredon-skip --filter-description='^(?!NO_VMTOOLS)+'  --filter-perfdata='none' --tools-notrunning-status=warning`
> WARNING: 977 VM with VMTools not up-to-date - 2 VM with VMTools not running - 14 VM with VMTools not installed |
=> OK if we considere cases 3 as known issue

Result expected for this case:
> CRITICAL: 14 VM with VMTools not installed WARNING: 977 VM with VMTools not up-to-date - 2 VM with VMTools not running |

6) last test:  --tools-notinstalled-status=warning --tools-notrunning-status=warning --tools-notup2date-status=ok
`/usr/lib/centreon/plugins/centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=tools-vm --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='default'  --vm-hostname='^(?!_)+' --filter --disconnect-status='ok' --nopoweredon-skip --filter-description='^(?!NO_VMTOOLS)+'  --filter-perfdata='none' --tools-notinstalled-status=warning --tools-notrunning-status=warning --tools-notup2date-status=ok`
> WARNING: 2 VM with VMTools not running |
=> Same as Case 2, only tools not running is displayed on output

Result expected for this case:
> WARNING: 2 VM with VMTools not running - 14 VM with VMTools not installed

Do I make a mistake on my commands or it's a bug in status management?

Thanks for your help.
Regards.

**Comment by garnier-quentin** [comment]
I think all problems comes from following issue:
https://github.com/centreon/centreon-vmware/issues/38

Please apply the patch and it should be ok ;)

**Comment by cmeschin** [comment]
ok thanks.
I try it as soon as possible (I have a conflict with libZMQ4 due an update of pluginspack referred in support VHC-861-17126)

**Comment by cmeschin** [comment]
Hi Quentin,
It works.
