### ISSUE TITLE
Windows Template error : Unknown option: warning at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 142.

### ISSUE THREAD

**Issue by imnotme** [centreon/centreon-plugins#742]
I've just updated this morning :
---> Package centreon-plugin-Operatingsystems-Windows-Snmp.noarch 0:20161212-1.el6 will be updated
---> Package centreon-plugin-Operatingsystems-Windows-Snmp.noarch 0:20170807-1.el6 will be an update

Since then, the "Memory" service from the widows template is throwing this error on all Windows hosts: 

Unknown option: warning at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 142.

The template is "OS-Windows-SNMP-Custom" since the classic template "OS-Windows-SNMP" does not create associated services when checking "Create Services linked to the Template too" (I will probably open an other issue for this one if it's not already acknowledged)

The template default check command is no longer valid and have not been updated : 

$CENTREONPLUGINS$/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning='$_SERVICEWARNING$' --critical='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$

The options are now this according to the plugin help :

 --warning-*
            Threshold warning. Can be: 'memory'.

 --critical-*
            Threshold critical. Can be: 'memory'.

The check command should have been :

$CENTREONPLUGINS$/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning-memory='$_SERVICEWARNING$' --critical-memory='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$

**Comment by imnotme** [comment]
Interesting fact : the linux plugin have been updated too, but it still use the old warning/critical syntax.

---> Package centreon-plugin-Operatingsystems-Linux-Snmp.noarch 0:20161212-1.el6 will be updated
---> Package centreon-plugin-Operatingsystems-Linux-Snmp.noarch 0:20170807-1.el6 will be an update

Mode:
    Check physical memory (UCD-SNMP-MIB).
    --warning
            Threshold warning in percent.
    --critical
            Threshold critical in percent.

**Comment by garnier-quentin** [comment]
It's not the purpose of that github ;)
But we'll fix that soon.

**Comment by imnotme** [comment]
I'm sorry but i don't understand why it's not the purpose of that github, can you give me more details about your answer?

**Comment by garnier-quentin** [comment]
Because it's an issue on centreonPP products. That github is for open-source centreon-plugins.
