### ISSUE TITLE
[os::linux::local::plugin] mode=traffic: Icinga2 can not read performance data

### ISSUE THREAD

**Issue by latuannetnam** [centreon/centreon-plugins#743]
Hello
I'm using plugin [os::linux::local::plugin]  with mode=traffic to get traffic metrics with Icinga2. For default output like:
OK: All traffic are ok. | 'traffic_in_ens18'=34319.00**b/s**;;;0; 'traffic_out_ens18'=43907.00**b/s**;;;0;
Icinga2 can not parse value because of "**b/s**" after value. 
So if I remove unit from output like:
OK: All traffic are ok. | 'traffic_in_ens18'=34319.00;;;0; 'traffic_out_ens18'=43907.00;;;0;
Then Icinga2 can get correct traffic metrics.
I wonder if  is a bug in plugin?
Thanks.

**Comment by garnier-quentin** [comment]
It's not a bug. But you can add an option to remove UOM:
```
--filter-uom=none
```

**Comment by latuannetnam** [comment]
Great answer!!!
I use plugin with following syntax: centreon_plugins.pl --plugin=os::linux::local::plugin --mode=traffic --filter-uom='^(?!(b/s))'
The output is:
OK: All traffic are ok. | 'traffic_in_ens18'=24260.57;;;0; 'traffic_out_ens18'=42236.57;;;0; 'traffic_in_lo'=14210.29;;;0; 'traffic_out_lo'=14210.29;;;0;
And Icinga2 can read value now.
Thanks you very much.

**Comment by garnier-quentin** [comment]
You're welcome ;)
