### ISSUE TITLE
ARP table check for Cisco switches

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#744]
Hi,

Could you add a plugin to check ARP table in Cisco switch and report an error, if duplicate MAC or IP are found. Here is quite good explanation which MIB and OIDs to use: https://networkengineering.stackexchange.com/questions/2900/using-snmp-to-retrieve-the-arp-and-mac-address-tables-from-a-switch
If SNMPWALK is needed, let me know, I can send it via email.

**Comment by garnier-quentin** [comment]
Yes i need a snmpwalk.
