### ISSUE TITLE
[apps::protocols::http::plugin] Add_support_to_GSS-API_authentication

### ISSUE THREAD

**Issue by cmoi42** [centreon/centreon-plugins#745]
Could you please add support for GSSAPI/Kerberos authentication?

In fact, many company are using GSSAP SSO on their internal websites. Why not developpping support for it?

Thank you,

Regards.

**Comment by garnier-quentin** [comment]
Try to install following perl module: http://search.cpan.org/~agrolms/LWP-Authen-Negotiate-0.06/lib/LWP/Authen/Negotiate.pm

Maybe it will work

**Comment by cmoi42** [comment]
Hi,

It's working but I need to obtain a Kerberos ticket in command line first, with "kinit" command otherwise it doesn't work. Step to get it working : 

1. First thing is to get a ticket :  

    kinit login@domain.com

2. Second thing is to do a simple check without any exotic option (credential, ntlm, username nor password) :  

    centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=hostname.domain.com

I'm not a Keberos expert but as I read, there is ticket's expiration, so I need a wrapper or something like that to deal with this behaviour. Maybe you could think about writting a Kerberos daemon like Vmware daemon which manage Kerberos ticket expiration?

What do you think?

Thank you,

Regards.

**Comment by garnier-quentin** [comment]
I don't know. But i think you'll have the expiration.
