### ISSUE TITLE
[storage::hp::3par::7000::plugin] pb with node no detected

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#747]
Hi,

I use your script with 3par 7200 and 8200,
I have 2 node for each 3par.
Today, on my 7200, only one node is detected.
When I use command line, I can see only one line.

7200 cli% shownode
                                                               Control    Data        Cache
Node --Name--- -State- Master InCluster -Service_LED ---LED--- Mem(MB) Mem(MB) Available(%)
   0 1651918-0 OK      Yes    Yes       Off          GreenBlnk    8192    4096          100

Normally, I sould have : 

7200 cli% shownode
                                                               Control    Data        Cache
Node --Name--- -State- Master InCluster -Service_LED ---LED--- Mem(MB) Mem(MB) Available(%)
   0 1651918-0 OK      Yes    Yes       Off          GreenBlnk    8192    4096          100
   1 1651918-1 OK      No     Yes       Off          GreenBlnk    8192    4096          100

So, could you add feature to check the number of node ?

Ps : in your script, you use shownode -s. ( -s is deprecated and will be removed in futur )

Thanks

**Comment by garnier-quentin** [comment]
3par plugin is very old. I would like to do it and have a "standard" for all versions. Could you give results of commands for different versions ?

**Comment by romsworld** [comment]
Ok, I'am going to see for result of command on both 3par

Battery : Showbattery
CIM : Showcim
ISCSI : Showport
Node : shownode –s
Physicaldisk : showpd -showcols Id,State
PSU : shownode -ps
Storage : showpd
Temperature : shownodeenv
Volume : showvv -showcols Id,Name,VSize_MB,Snp_Rsvd_MB,Snp_Used_MB,Adm_Rsvd_MB,Adm_Used_MB,Usr_Rsvd_MB,Usr_Used_MB
Wsapi : showwsapi

**Comment by garnier-quentin** [comment]
Moreover, can we chain commands ? And do echo stuff  between commands ?

**Comment by garnier-quentin** [comment]
You didn't provide us the result of commands on both 3par ? We can chain it with echo (so don't need information about that).

**Comment by garnier-quentin** [comment]
With the new 3par ssh and mode component, you can use following option: --critical-count-node=2:
