### ISSUE TITLE
Random SNMP Error Windows plugin Getopt.pm line 67 centreon_windows_snmp.pl line 142

### ISSUE THREAD

**Issue by Blooopa** [centreon/centreon-plugins#748]
Hi folks!

i'm using Centos 6.9, Centreon v. 2.8.12, every works perfectly but some time ago (3 days) i got this error.

[root@centreon centreon-plugins]# ./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=xxx.xxx.xxx.xxx --snmp-community='Windows' --warning='80' --critical='90'
Unknown option: Warning at /root/centreon-plugins/centreon/plugins/alternative/Getopt.pm line 67.
 
but in some cases i got this error

[root@centreon ~]# /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=xxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='Windows' --warning='80' --critical='90'

Unknown option: warning at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 142.

This error occurs only with windows host and memory check.

![centreon_it_network_monitoring](https://user-images.githubusercontent.com/31484789/29886312-0408bf32-8d90-11e7-942e-a25b4e38856b.png)

I'm using the latest centreon-plugins available. What I'm doing wrong?

Thanks!

**Comment by Sims24** [comment]
Hello @Blooopa, 

Thanks for your feedback, allow to spot a missing update online. We will handle this tomorrow for instance please do this query on centreon db : 

`MariaDB [centreon]> UPDATE command SET command_line="$CENTREONPLUGINS$/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=$HOSTADDRESS$ --snmp-version='$_HOSTSNMPVERSION$' --snmp-community='$_HOSTSNMPCOMMUNITY$' $_HOSTSNMPEXTRAOPTIONS$ --warning-memory='$_SERVICEWARNING$' --critical-memory='$_SERVICECRITICAL$' $_SERVICEEXTRAOPTIONS$" WHERE command_name='OS-Windows-SNMP-Memory';
`

Do not forget to deploy config and reload engine after.

**Comment by Blooopa** [comment]
Thank @Sims24, the update works fine.
