### ISSUE TITLE
Option warning in mode memory on Windows plugin error

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#751]
**Global Version 20170807**

Error when adding the --warning or --critical switch.

When you run thw following command:
`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --mode memory --hostname 172.20.205.90 --warning 80 --critical 95`

the follwing message appaers:
`Unknown option: warning at /usr/lib/centreon/plugins/centreon_windows_snmp.pl line 142
`

The same command with Global Version 20161212 (before Centreon 2.8.12 update) output the real answer:
`OK: RAM Total: 16.00 GB Used: 2.67 GB (16.66%) Free: 13.33 GB (83.34%) | 'used'=2862284800B;0:13743475916;0:16320377651;0;17179344896
`

**Comment by Sims24** [comment]
Hi @stefanotoro you should use --warning-memory and --critical-memory as explained in the help. Mode has been review to fit last dev guidelines.

**Comment by stefanotoro** [comment]
Hi Sims,

Okay thank you very mutch and sorry for the post.
Where can i get the help or manual fot the command ?

**Comment by Sims24** [comment]
No problem ;) 

`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --mode memory --help `

Tell me if this does not work

**Comment by Sims24** [comment]
EDIT : Help is available only with full plugin path .. 

`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin os::windows::snmp::plugin --mode memory --help`

We will try to find a way.

**Comment by stefanotoro** [comment]
Hi,

Yes it's okay for me, thank you !
