### ISSUE TITLE
Undefined subroutine for pfSense plugin

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#754]
Global Version: **20170811**
Plugin name: **apps::pfsense::snmp::plugin**
Mode: **runtime**

Error in command result for runtime mode

`/usr/lib/git/centreon_plugins.pl --plugin apps::pfsense::snmp::plugin --mode runtime --hostname 192.168.7.2`
`UNKNOWN: Undefined subroutine &apps::pfsense::snmp::mode::runtime::floor called at /usr/lib/git/centreon-plugins/apps/pfsense/snmp/mode/runtime.pm line 73. 
`

Same error with intergrated plugin (Global Version 20170807):
`/usr/lib/centreon/plugins/centreon_pfsense.pl --mode runtime --hostname 192.168.7.2
`
`UNKNOWN: Undefined subroutine &apps::pfsense::snmp::mode::runtime::floor called at /usr/lib/centreon/plugins/centreon_pfsense.pl line 550. 
`

Thank you

**Comment by garnier-quentin** [comment]
Thanks!
