### ISSUE TITLE
[os::windows::snmp::plugin] mode memory

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#760]
Hello,
I want to set up a snmp memory check. 
```
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl 	
        --plugin=os::windows::snmp::plugin
	--hostname=172.x.x.x
	--snmp-community=publique
	--snmp-version=2
	--mode=memory
	--warning-memory=85
	--critical-memory=95
```

However, some servers (not all) do report an error.  All servers have the same SNMP configuration.
`UNKNOWN: SNMP GET Request : Timeout`
or
`UNKNOWN: SNMP Table Request : Timeout`

But on these same servers when I do a snmpwalk (CLI), the test works but not in the GUI.
`snmpwalk -v 2c -c publique 172.x.x.x system`

Is that a bug ? An idea of where the problem may come from ?

**Comment by garnier-quentin** [comment]
Could you test with following option : --snmp-force-getnext

**Comment by boogaaloo** [comment]
Thank you for your quick reply !
It worked on half the servers in error. However, the other half remains. 
They all have the same error :
`UNKNOWN: SNMP Table Request : Timeout`

**Comment by garnier-quentin** [comment]
On Windows, the SNMP is shitty. Yo should NSClient++.

**Comment by boogaaloo** [comment]
Ok ;)
Thank you
