### ISSUE TITLE
Plugin::Biztalk

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#761]
Hello,

I would like to know if the plugin Biztalk works because I saw that there was a folder _biztalk_ in the folder _centreon-plugin_ (but it looks different) ?

Thank you
Best regards

**Comment by garnier-quentin** [comment]
Hi,

Yes it works. But it needs to use the dyn-mode system:
https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#what-does---dyn-mode-option-do-

**Comment by boogaaloo** [comment]
It looks complicated ;) A trap will do the trick...
Thank you

**Comment by garnier-quentin** [comment]
No, it's quite simple ;)
