### ISSUE TITLE
Traffic_in doesn't show on graphics with Fortigate plugin

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#763]
Hello,

I am using the template for Fortigate firewalls and use the check command for interfaces. 
It works fine but graphics doesn't appear completely. I see only traffic_out. Traffic_in doesn't appear even if it indicates on the csv its existence.

Can you help about this issue please ?
here is an exemple.
![image](https://user-images.githubusercontent.com/28105870/30706638-e400e09e-9ef0-11e7-84df-6a4f3d9e35d5.png)

i am on centreon web last version.
Thank you

**Comment by Sims24** [comment]
Hi, 

This is rather a centreon/graph template issue. In your service configuration (Extended infos) set Traffic as the graph template and reload your configuration.  You will be able to see both curves after that
