### ISSUE TITLE
Plugin "Applications-Weblogic-Jmx"

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-plugins#765]
Hi,

"Applications-Weblogic-Jmx" plugin doesn' work.
"list-mode" is functional but not checks.

```
/usr/lib/centreon/plugins/centreon_weblogic_jmx.pl --plugin=apps::java::weblogic::jmx::plugin --mode=class-count
UNKNOWN: Cannot load module --mode.
Can't locate centreon/common/jvm/mode/classcount.pm in @INC (@INC contains: /usr/lib/centreon/plugins FatPacked::31982608=HASH(0x1e80410) /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/centreon_weblogic_jmx.pl line 1179.
```

Regards

**Comment by Sims24** [comment]
Hi @bmareau, 

Looks like a fatpacking issue, I close it here as it does not directly concern code here. 

We will open it in the dedicated repository to track its resolution. 

Thanks for the feedback :)

**Comment by Tpo76** [comment]
OK
version centreon-plugin-Applications-Weblogic-Jmx-20171013-1.el6.noarch.rpm
