### ISSUE TITLE
[os::linux/windows::snmp::plugin] mode storage - no used and size perfdata when free argument

### ISSUE THREAD

**Issue by benoitb21** [centreon/centreon-plugins#766]
Hello,

Since many months, I can't have my 'used' and 'size' perfdatas when I use the 'free' argument to check the available 'free' space on disks.
I use for example --warning='2147483648:' --critical='1073741824:' --free --units='B' --explode-perfdata-max='used,size'
but I have only 'free' perfdata.

Can you fix this problem in the storage snmp plugin?

Thanks

**Comment by garnier-quentin** [comment]
Duplicate issue: #79

**Comment by benoitb21** [comment]
for example those lines:
if (defined($self->{option_results}->{free})) {
$label = 'free';
$value_perf = $total_free;
}
