### ISSUE TITLE
[storage::netapp::snmp::plugin] Add mode 'snapvaultlag'

### ISSUE THREAD

**Issue by jdidierpichat** [centreon/centreon-plugins#767]
Add mode snapvaultlag on NetApp 7-mod

[snapvaultlag.txt](https://github.com/centreon/centreon-plugins/files/1337428/snapvaultlag.txt)

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=storage::netapp::snmp::plugin --mode=snapvaultlag --hostname xxxxxxxxxxxxx --snmp-version='2c' --snmp-community='xxxxxx' --warning='' --critical='' --snmp-timeout='100' --name '1xxx6'
OK: Snapvault '1xxxxxx6' lag: 54876 secondes | 'lag'=54876s;;;0;

will be nice to add list-snapvault mode

**Comment by garnier-quentin** [comment]
Could you give me a snmpwalk also ? 
```
$ snmpwalk -ObentU -v 2c -c public IP .1 > netapp.snmpwalk
```

**Comment by jdidierpichat** [comment]
in your mailbox :)

**Comment by garnier-quentin** [comment]
thanks!
