### ISSUE TITLE
[Network/Cisco/SmallBusiness/Standard/SNMP] Can't get Traffic information on VLAN interfaces

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-plugins#768]
Hi everyone,
I got a little issu with my monitoring on my new Cisco SG 300 SmallBusiness
When I ask Centreon for traffic information, the issu appears with vlan interfaces : 
![image](https://user-images.githubusercontent.com/26572075/31006829-a9f673e6-a4fe-11e7-99bc-8c6b45034f31.png)
The first test is on a physic interface where a wire is plugged
The second is a vlan interface (of course, in this vlan I got multiple physics interfaces, and network traffic)

Do I forget something ?
Thanks for the help

**Comment by garnier-quentin** [comment]
There is no information about traffic. You can use --add-status.

**Comment by alliria98** [comment]
If I understand, traffic informations aren't supported with vlan interfaces, despite physical interfaces are.
Am I right ?

**Comment by garnier-quentin** [comment]
It seems so ;)
