### ISSUE TITLE
One check for interfaces (merge)

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#77]
Check interfaces with only one mode for:
- status
- traffic
- errors
- cast

Moreover, it could manage:
- multiple interfaces with ID (use coma) 
- traffic/errors/cast without checking status (an option)
- traffic without speed
- an extra oid in the description of the interface

**Comment by garnier-quentin** [comment]
Can also filter on interface state. 
Add a resource system for OIDs and states (like that i can extends a little).

**Comment by garnier-quentin** [comment]
Add an option for nagvis widget trafic.

**Comment by hecko** [comment]
Quentin, did you simply rename the 'traffic' mode to 'interfaces' name of the mode?
From the multiple pollers perspective this is a hell to manage when naming changes are implemented like this and its very counter intuitive. Please please setup a proper procedure to inform users about changes like these before they make their way into the RPMs.

**Comment by garnier-quentin** [comment]
Hi Marcel,

I don't only renamed the modes. After it's a PP issue. We should have a release note yes.
