### ISSUE TITLE
[apps::protocols::http::plugin] Need help

### ISSUE THREAD

**Issue by romsworld** [centreon/centreon-plugins#773]
Hi,

I would like to know if it's possible to parse multiline with http plugin.

./centreon_plugins.pl --plugin=apps::protocols::http::plugin --mode=expected-content --hostname=X.X.X.X --expected-string='???'

I have a grid on my page, with : CallbackWs and ERROR in other cell.

Source code : 

<tr>
--
  | <td>CallbackWs</td>
  |  
  | <td>ERROR</td>
  | <td>Response code = 405</td>
  | </tr>

I would like CRITICAL when CallbackWs is on ERROR.

Is it possible ?
Or http plugin can not do that because it can only parse 1 line ?

Thanks

**Comment by garnier-quentin** [comment]
Yes you can. Modifier:
```
if ($webcontent =~ /$self->{option_results}->{expected_string}/mi) {
```
