### ISSUE TITLE
os::windows::snmp::plugin mode::storage pb with cdrom is mounted

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon-plugins#774]
Original message from @o71 https://github.com/centreon/centreon/issues/5759

When I mount an 'iso' file on a Windows machine a new drive is added (here K :).

The drive K: is not listed in the list of drives using the plugin 'centreon_windows_snmp.pl' but the size of drive K: replace the size of the drive O.

Here are the screenshots:

![](https://user-images.githubusercontent.com/2280629/31342946-84fe9916-ad0e-11e7-8268-4db09d7dc354.png)

![](https://user-images.githubusercontent.com/2280629/31342918-6e48ba58-ad0e-11e7-92f2-49b626ceef57.png)

Here my command :

/usr/lib/centreon/plugins/centreon_windows_snmp.pl
--plugin=os::windows::snmp::plugin
--mode=storage
--hostname=X.X.X.X
--snmp-version='2c'
--snmp-community='public'
--storage='.'
--name
--regexp
--display-transform-src='^(..).'
--display-transform-dst='$1'
--warning='80'
--critical='90'
--verbose

All is ok after I eject the K drive, but my graph :

![](https://user-images.githubusercontent.com/2280629/31343128-03a859dc-ad0f-11e7-9216-06721c400ec4.png)

**Comment by garnier-quentin** [comment]
I think windows snmp is shitty and replace an existing OID (it should use a new one). And the problem comes from the cache file we use. Maybe you can set following option:
--reload-cache-time=0

**Comment by o71** [comment]
Ok, thanks. So if I add a new permanent drive on the server. I should purge the snmp cache file for the host or remove temporary the --reload-cache-time=0 ?

Thanks

**Comment by garnier-quentin** [comment]
Yes indeed. But you can let --reload-cache-time=0
