### ISSUE TITLE
VMware - ZMQ::LibZMQ3

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#776]
Hello,
In reference to this [problem]( https://github.com/centreon/centreon/issues/5587), I would like to know how to install this package:
 - centreon-plugin-Virtualization-VMWare-daemon-2.4.0-1.el7.centos.noarch
-  centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20170807-2.el7.noarch

Should the repositories be modified ? 
I have a centos version 6.9 / Centreon v. 2.8.14 ...

Thank you

**Comment by garnier-quentin** [comment]
it's on repository:
http://yum.centreon.com/standard/3.4/el6/stable/noarch/RPMS/

So you could do an update.

**Comment by boogaaloo** [comment]
ok...my bad...tired :)
Sorry.
