### ISSUE TITLE
Question : how should the perl connector be used with a centreon_plugins.pl command?

### ISSUE THREAD

**Issue by EChauve** [centreon/centreon-plugins#78]
As centreon_plugins.pl has become the core of Centreon's plugins, most of my commands use it. To increase performances, I would like to use the perl connector which is very likely to have been designed to this purpose (in my opinion).
According to the Centreon documentation, the perl connector does not need to be configured and should be used just by selecting it when creating a command.

When doing exactly so, the services asociated to the said command all go to unknown and latency is created.

Here is the definition of a command : 

define command{
command_name LOCAL_RAM
command_line perl $USER1$/centreon-plugins/centreon_plugins.pl --plugin=os::linux::local::plugin --mode=memory --warning=$_SERVICEWARNING$ --critical=$_SERVICECRITICAL$
connector centreon_connector_perl
}

The command works very well without the connector, I am just trying to anticipate a need for performance optimisation.

Am i doing it wrong? Do I understand the purpose of the connector properly? Is it compatible? Should I ask my question here?

**Comment by garnier-quentin** [comment]
Yes it's compatible. you have two solutions:
- edit the file 'centreon_plugins.pl' (there are comments in it)
- Configure the connector perl in 'centreon' UI like that:

centreon_connector_perl --code "use '/usr/lib/nagios/plugins/\;"

**Comment by garnier-quentin** [comment]
I have done an error :)

centreon_connector_perl --code "use '/usr/lib/nagios/plugins/'\;"

**Comment by EChauve** [comment]
In "Configuration"-->"Commands"-->"Connectors"-->"Perl Connector" , I replaced : centreon_connector_perl 
by : 
centreon_connector_perl --code "use '/usr/lib/nagios/plugins/'\;" 
but I am still getting the "(Execute command failed)" message

I will try the first method now

**Comment by EChauve** [comment]
With the first method : 
- The services whose command specify to use the perl connector are unknown
- The other services involving centreon_plugins.pl continue to work

So, if I understand a bit what is going on, this method is working and I should not specify the connector in the command definition. 

Am I right?

**Comment by garnier-quentin** [comment]
The two methods works. You need to restart 'centreon-engine' each times. And i give you an example with '/usr/lib/nagios/plugins'. You have to set the directory where you have 'centreon_plugins.pl'.

**Comment by EChauve** [comment]
Oh, of course, obviously... I don't know what I was thinking.
So, in my case : '/usr/lib/nagios/plugins/centreon-plugins/'
Well everything is working fine know, thanks you for your time again.
I hope this issue helps other people as well.

**Comment by garnier-quentin** [comment]
Not a problem :) Thanks to using it.
