### ISSUE TITLE
[juniper::srx mode interfaces]

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#782]
Hello,

An error case has not been take in account.

These values return Normal status for the associated service in centreon :
Interface 'em0' Status : up (admin: up)
Interface 'em1' Status : up (admin: up)
Interface 'xe-0/0/16' Status : up (admin: up)
Interface 'xe-0/0/17' Status : up (admin: up)
Interface 'fab1' 
Interface 'xe-7/0/16' 
Interface 'xe-7/0/17' 
Interface 'fab0' Status : up (admin: up)

Should be UNKNOWN if operStatus and adminStatus are not defined / populated in the MIB ...

Thanks

**Comment by Sims24** [comment]
Hello @ritouret, 

Could you send me a full snmpwalk along with the command line you have executed to have this ? 

Thanks, 
Simon

**Comment by garnier-quentin** [comment]
There is no status OID for some interfaces. So the mode skip the check. It would be great that juniper use the unknown status for that.
