### ISSUE TITLE
[apps::protocols::http::plugin] Process timeout

### ISSUE THREAD

**Issue by imnotme** [centreon/centreon-plugins#784]
## Bug/Question

The HTTP plugin ::
/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=github.com --proto='https' --port='443' --urlpath='/' --warning='0.5'  --critical='1'

is returning a 'process timeout' if the TCP port used is closed or blocked (not rejected, just no response to the SYN packet)

It just return this timeout after the engine configuration 'service check' timeout.

Not really good at Perl, but it seems to lack a timeout when opening the TCP socket ::

main::(/usr/lib/centreon/plugins/centreon_protocol_http.pl:5846):
5846:   centreon::plugins::script->new()->run();
   DB<1> c
IO::Socket::connect(/usr/lib64/perl5/IO/Socket.pm:115):
115:            if (defined $timeout && ($!{EINPROGRESS} || $!{EWOULDBLOCK})) {
 <-- MANUALLY INTERRUPTED, to make it work. Else it go long before timeout-->
CRITICAL: 500 Can't connect to github.com (connect: Interrupted system call) |

[root@monitoring plugins]# ./centreon_protocol_http.pl --version
Global Version: 20170807

The default socket timeout seems to be a little more than 1 minute (using time + command), but it still higher than the default check timeout.

Workaround is to increase to 65 seconds the check timeout or to define a parent TCP check service.
Or can you provide the way to reduce the perl socket default timeout?

IMHO, a configurable socket timeout would be cleaner 😋

**Comment by garnier-quentin** [comment]
I don't really understand. There is a timeout option with 5 seconds. So it's not working in some case ?

**Comment by imnotme** [comment]
It looks like so.

Example you can try :
time /usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=response --hostname=4.2.2.1 --proto='https' --port='443' --urlpath='/' --warning='0.5' --critical='1'
CRITICAL: 500 Can't connect to 4.2.2.1:443 (connect: Connection timed out) |

real    1m3.232s

I know it will not work (because this is a dns server obviously) but the 'process timeout' should be another error message, but it's not because of a missing timeout I think.

/usr/lib/centreon/plugins/centreon_protocol_http.pl --version
Global Version: 20170807 (<- Weird because I've just updated it through the web interface)

**Comment by garnier-quentin** [comment]
It's working on ubuntu 16.04. So it seems like a bug in io::socket::ssl or lwp.

**Comment by imnotme** [comment]
fwiw, I'm using the centreon ISO (centos based) / up to date.

**Comment by garnier-quentin** [comment]
There is the problem with centos 6 and centos 7. indeed. But not sure i can do something about it.

**Comment by garnier-quentin** [comment]
I think it comes from https://metacpan.org/changes/distribution/IO-Socket-IP (there is a fix in version 0.32)
