### ISSUE TITLE
[os::linux::local::mode::storage] Missing reserved block

### ISSUE THREAD

**Issue by Ziranium** [centreon/centreon-plugins#785]
Hello,

On Linux, "df" command is returning %used different than storage.pm lib.
This difference is because storage.pm doesn't add the reserved block on filesystem (26214 here) :
```
[root@myHost~]# tune2fs -l /dev/mapper/vg_foo-lv_bar | grep -e "Reserved block count" -e "Block count"
Block count:              524288
Reserved block count:     26214
```

The 26214 blocks represent 5% of 524288. Then there is 5% difference between df results and plugin output. 
I reduced to 2% to test it : 
`tune2fs -m 2 /dev/mapper/vg_foo-lv_bar`
So my total used decreased by 2% on df, but no effect on plugin output.

Can you add "Reserved block count" value to the $total_used before calculating pct used pls ?

Thanks.

Jonathan

**Comment by Sims24** [comment]
Hello,

Please use --space-reservation  option (described in the help) to manage this as we do not want to hardcode 5%.

**Comment by Ziranium** [comment]
Hello,
Thanks for your reply.
My question was about why not add automatically real value (like i showed with tune2fs) instead of force user to hard code value as parameter ?

Regards,

Jonathan
