### ISSUE TITLE
Centreon traffic plugin - SNMPv3 context 

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-plugins#786]
Initially open here https://github.com/centreon/centreon/issues/5807

Steps to reproduce the issue:

Configure monitoring for Check Point VSX, containing VS0, VS1 (and more like VS2, ...) - or any device that can use SNMPv3 context to switch between virtual systems
Configure interface monitoring using the centreon traffic plugin
Describe the results you received:
traffic plugin works for VS0 for some time, but doesn't work for VS1, .... After some time, the plugin starts working for VS1, but not for VS0 (or VS2, ...). This switches between the VS's.
So for clarity, the traffic plugin works for one VS (multiple interfaces), then switches to another VS
Error when the commands fail:
UNKNOWN: No entry found (maybe you should reload cache file)

Describe the results you expected:
I expected to have the traffic plugin working for all interfaces for all VS'es

My two cents: I think that somehow the plugin is using the same cache file(s) for this, and the checks are "fighting" over control of the ache file(s)

Extra info:

I showed this behavior to Cyrille BAUGE (Centreon), who asked me to log a github issue for this.
if you remove the interface cache files on the poller and run one of the commands manually immediately after that: they always work.
example commands:
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=x.y.z.25 --snmp-community=my_comm --snmp-version=3 --interface=^eth7.400$ --name --add-status --add-traffic --oid-filter=ifDesc --oid-display=ifDesc --snmp-username=my_user --authprotocol=MD5 --authpassphrase=my_auth_pass --privprotocol=DES --privpassphrase=my_priv_pass --contextname=ctxname_vsid2

/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --hostname=x.y.z.25 --snmp-community=my_comm --snmp-version=3 --interface=^eth5.200$ --name --add-status --add-traffic --oid-filter=ifDesc --oid-display=ifDesc --snmp-username=my_user --authprotocol=MD5 --authpassphrase=my_auth_pass --privprotocol=DES --privpassphrase=my_priv_pass --contextname=ctxname_vsid1

I have tried with and without "--oid-filter=ifDesc --oid-display=ifDesc", same result.

Please advise.

**Comment by Sims24** [comment]
Hello, 

Could you please try to add --reload-cache-time 0 to your command line and tell us if the problem still appears ? 

Rgds,

**Comment by bdeschut** [comment]
I have tried with:
--oid-filter=ifname -> worst result, nearly all interface checks return unknown

and as you suggested:
--reload-cache-time 0 -> still a lot of "flapping" between OK and UNKNOWN
(tested with "--oid-filter=ifDesc --oid-display=ifDesc" and without)

**Comment by Sims24** [comment]
Could you please provides two snmpwalk :

**Comment by bdeschut** [comment]
Hey Simon,

I think I need to elaborate here. So there is one system, which hosts multiple virtual systems.
For example, you have a physical chassis with IP x.y.z.a, with 3 virtual machines: VS0, VS1 and VS2.
Let's say that vs0 has eth0, vs1 has eth1 and vs2 has eth2.

In order to query the interface data, we need to perform the following queries: (stripped out most fields)
--hostname=<phys-IP> --interface=^eth0$ --contextname=
--hostname=<phys-IP> --interface=^eth1$ --contextname=ctxname_vsid1
--hostname=<phys-IP> --interface=^eth2$ --contextname=ctxname_vsid2
> Please note the same physical IP, only the interface options and contextname option change.

I just noticed them (without any manual action) switch
from: all OK for VS1 and unknown for VS0 and VS2
to: all OK for VS0 and unknown for VS1 and VS2.

In the question you mention "-v2c", while we use v3 and do an entire walk of the device. For which context would you like the snmpwalk?

Also, please let me know if you could replicate this is lab OR
if I need to provide the snmpwalk, to restrict the query to a minimum, because I will have to sanitize the data manually (to not include any sensitive customer data).

Kind regards,
Bob

**Comment by Sims24** [comment]
Hi, 

Thanks Bob for these insightful informations. That's sounds like a bug I need just to confirm this by asking you a last thing before start working on this. 

Could you give me the result of the following command one the poller monitoring this device (replace grep pattern by the IP addr) : 

ll /var/lib/centreon/centplugins/* | grep x.y.z.a 

Thanks

**Comment by bdeschut** [comment]
[root@poller ~]# ll /var/lib/centreon/centplugins/* | grep IP_x.y.z.a
-rw-r--r-- 1 centreon-engine centreon-engine 1126 Oct 27 10:14 /var/lib/centreon/centplugins/cache_snmpstandard_IP_x.y.z.a_interfaces
-rw-rw-r-- 1 centreon-engine centreon-engine 1300 Oct 27 07:15 /var/lib/centreon/centplugins/cache_snmpstandard_IP_x.y.z.a_storage
-rw-rw-r-- 1 centreon-engine centreon-engine  371 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_06c4b30143bf50ca840ef7de2e27e94b_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  360 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_06c4b30143bf50ca840ef7de2e27e94b_826e9c1131e1e6b3f2d1703ad4f98830
-rw-r--r-- 1 centreon-engine centreon-engine  360 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_23f2a284646318d49e45f9e5338eeae6_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  361 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_23f2a284646318d49e45f9e5338eeae6_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  370 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_2579f4c3991a40cfd4393e19754c82f9_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  360 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_2579f4c3991a40cfd4393e19754c82f9_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  358 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_46db19b8b56b359693e875a3022b10b4_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  351 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_46db19b8b56b359693e875a3022b10b4_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  359 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_77438773f3e2dcc63a1071d9d94998ba_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  348 Oct 24 11:17 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_77438773f3e2dcc63a1071d9d94998ba_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  357 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_7d271969e54f3bfe4b793055a0ec17f3_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  349 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_7d271969e54f3bfe4b793055a0ec17f3_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  367 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_7f3e1533f9fd4228b0a732d6126d6044_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  357 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_7f3e1533f9fd4228b0a732d6126d6044_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  359 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_8793e6bbea1e61103fab7c2a8341824d_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  354 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_8793e6bbea1e61103fab7c2a8341824d_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  370 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_948e59d3b1fdbc565ced257c98789bd6_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  360 Oct 24 11:16 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_948e59d3b1fdbc565ced257c98789bd6_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  370 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_aae297cccce8a360f3f2fa1a9472735d_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  360 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_aae297cccce8a360f3f2fa1a9472735d_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  355 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_ba5727d4fe429b72582e0b19875ca919_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  347 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_ba5727d4fe429b72582e0b19875ca919_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  353 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_bdaeaddb8b8029bf09cac5fb9e4b8775_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  348 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_bdaeaddb8b8029bf09cac5fb9e4b8775_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  368 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_c7d941b97796aa1e8543cf7bae428707_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  358 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_c7d941b97796aa1e8543cf7bae428707_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  360 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_c9f7146911b5a024496d65b2afa92514_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  357 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_c9f7146911b5a024496d65b2afa92514_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  359 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_e31e6eceb17e68cad6eb871a6fcfd9c9_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine   65 Oct 24 11:17 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_e31e6eceb17e68cad6eb871a6fcfd9c9_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  356 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_e444a48cde10c62c5209731fbf327e98_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  346 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_e444a48cde10c62c5209731fbf327e98_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  368 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_ea94f21bc188d166b61d34e98ef1a8e7_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  358 Oct 27 10:15 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_ea94f21bc188d166b61d34e98ef1a8e7_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  371 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_f49948ea70b896d2dffd312ee34ecc39_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  360 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_f49948ea70b896d2dffd312ee34ecc39_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine  369 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_f7b3493216ab9142cd01940127be0d74_27d0aabf50b46f43443654481fbc2631
-rw-rw-r-- 1 centreon-engine centreon-engine  358 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_interfaces_f7b3493216ab9142cd01940127be0d74_826e9c1131e1e6b3f2d1703ad4f98830
-rw-rw-r-- 1 centreon-engine centreon-engine   89 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_numeric-value_08bb049121ef090eb28f0dcc00325db0
-rw-rw-r-- 1 centreon-engine centreon-engine   89 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_numeric-value_b66fcde02379d215439958f080856188
-rw-rw-r-- 1 centreon-engine centreon-engine  156 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_2dc328f0345d28bec73ea56f1142fd20
-rw-rw-r-- 1 centreon-engine centreon-engine   98 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_4885c6dd1f2f3ebb81f8de2326e75899
-rw-rw-r-- 1 centreon-engine centreon-engine  167 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_76bd3735f88bb35dc5a877b9a0b41824
-rw-rw-r-- 1 centreon-engine centreon-engine  206 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_c7285f17818d932ee38e5c498e96340e
-rw-rw-r-- 1 centreon-engine centreon-engine  165 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_c771726a269cf9136095cf17568987a1
-rw-rw-r-- 1 centreon-engine centreon-engine   96 Oct 27 10:12 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_e38c41d787c751316e401ce486240856
-rw-rw-r-- 1 centreon-engine centreon-engine  191 Oct 27 10:14 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_e700cba998d5c50b64951c6ed5b2f88e
-rw-rw-r-- 1 centreon-engine centreon-engine  132 Oct 27 10:13 /var/lib/centreon/centplugins/snmpstandard_IP_x.y.z.a_processcount_eb3d12991028d3e62819656ee5f6a47e

**Comment by bdeschut** [comment]
I left the "--reload-cache-time 0" in place, and today I notice that all traffic checks for the 3 VS's are OK.
However, when I select them all and select "schedule immediate check" (not forced), 4/5 of all checks go in unknown with the message "UNKNOWN: No entry found (maybe you should reload cache file)"

Kind regards,
Bob

**Comment by garnier-quentin** [comment]
That's a specific case. Indeed, i don't put context option in cache file name. It should work with option: --reload-cache-time=-1

**Comment by garnier-quentin** [comment]
Instead of reload-cache-time option, we can use following option:
--statefile-suffix=contextname
