### ISSUE TITLE
os:windows:snmp:storage

### ISSUE THREAD

**Issue by boscorelly** [centreon/centreon-plugins#787]
Hi,

i want to monitor only 2 disks instead of all.

i have tried multiples options but nothing works...

perl /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=192.168.254.200 --snmp-version='2c' --snmp-community='solutek' --storage='.*' --name --regexp --display-transform-src='^(..).*' --display-transform-dst='$1' --warning='90' --critical='95' --verbose
OK: All storages are ok. | 'used_C:'=44105863168B;0:112915902873;0:119189008588;0;125462114304 'used_D:'=534679011328B;0:1686128449536;0:1779802252288;0;1873476055040 'used_H:'=500805283840B;0:538868865024;0:568806024192;0;598743183360
Storage 'C:' Total: 116.85 GB Used: 41.08 GB (35.15%) Free: 75.77 GB (64.85%)
Storage 'D:' Total: 1.70 TB Used: 497.96 GB (28.54%) Free: 1.22 TB (71.46%)
Storage 'H:' Total: 557.62 GB Used: 466.41 GB (83.64%) Free: 91.21 GB (16.36%)

perl /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=192.168.254.200 --snmp-version='2c' --snmp-community='solutek' --storage='1,2' --regexp --display-transform-src='^(..).*' --display-transform-dst='$1' --warning='90' --critical='95' --verbose
UNKNOWN: No storage found. Can be: filters, cache file.

perl /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=192.168.254.200 --snmp-version='2c' --snmp-community='solutek' --name --storage='C,D' --regexp --display-transform-src='^(..).*' --display-transform-dst='$1' --warning='90' --critical='95' --verbose
UNKNOWN: No storage found. Can be: filters, cache file.

any idea ?

**Comment by Sims24** [comment]
Hello, 

What about --storage='^(C|D)' ? 

Perl regexp should be used :
https://perldoc.perl.org/perlre.html

**Comment by boscorelly** [comment]
Ouiiiii merci ! 

Je connais pas vraiment les regex perl, et là ça marche ! Merci !
