### ISSUE TITLE
os::linux::snmp::plugin - mode storage and free space

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#79]
Bonjour,
l'utilisation de l'argument --free permet de travailler sur les espaces restants mais les metric remontés sont de type "free", le metric "used" n''apparait plus.
Cette utilisation n'est donc pas compatible avec Centreon BI et les rapports de capacité.

Est-il possible d'ajouter le metric "used" en complément du metric free pour ce mode de fonctionnement?
De plus, est-il possible de pouvoir spécifier les tailles disques dans des unités humainement lisible (M ou MB, G ou GB, T ou TB) plutôt qu'en B uniquement? le plugin ferait alors lui-même la conversion en B pour effectuer les calculs et remonter les metric corrects.
Cette gestion d'unité serait appréciable sur l'ensemble des modes gérant une taille en Bytes.

cordialement,

----- version anglaise ------
Hello, the use of the argument --free allows to work on the remaining spaces but the gone back up metric is of type "free", the metric "used" not appears more.
This use is not thus compatible with Centreon BI and the reports of capacity.

Is it possible to add the metric " used " as a supplement to the metric free for this way of functioning?
Furthermore, it is possible to be able to specify the sizes disks/memory in units humanely readable (M or MB, G or GB, T or TB) rather than B only? The plugin would make then itself the conversion B to make the calculations and go back up(raise) the correct metric.
This management of unity(unit) would be considerable on all the modes managing a size in Bytes.

Cordially,

**Comment by garnier-quentin** [comment]
Thanks for the ticket. But could you write it in English please ? :)

**Comment by garnier-quentin** [comment]
It could be done to specify the unit (B, MB, GB). But it's more complex to add used also when you check with free value.

**Comment by cmeschin** [comment]
The plugin return the total size. So used=total-free, no?

**Comment by garnier-quentin** [comment]
Not so easy because you have thresholds and thresholds are on free value.

**Comment by cmeschin** [comment]
In this case, the used metric in for compatibility on Centreon BI. Thresholds are required?
so warning_used=total-warning_free and same for critical.

**Comment by garnier-quentin** [comment]
Need to think about it. But it's a main change :)

**Comment by cmeschin** [comment]
ok thank you.

**Comment by cmeschin** [comment]
a last request: the same change must be made at least on windows plugin ;)

**Comment by florian-asche** [comment]
I think, we need one option for input and one for output.

We need a global function where you can say, this is my total, and this is free, please give me used. Or this is total, and this is used, please give me free.

**Comment by Jackiewadeshan** [comment]
Hello Guys,

I am using snmp --mode=storage and I have noticed the only output is in B no % possible.
Is it a limitation of the plugin or a small bug ?

Thanks a lot for your help

**Comment by garnier-quentin** [comment]
Hi,

It's not a bug. You want to display '%' instead of 'B' ? Because, maybe you can change 'B' in '%' (you have all informations to do that) with your monitoring system.

**Comment by Jackiewadeshan** [comment]
Salut Quentin,
I tried to use and force % instead of B but the graph (perfData) result is always in GB not any percent (--mode=storage  --warning=80 --critical=90 --storage=2 --verbose --units=%).

I had a look on the code and it seems normal because perfData will always be in B. I have tested by modifying the code in storage.pm (ligne 235) "$self->{output}->perfdata_add(label => $label . $extra_label, unit => 'B',"
I put my own values:
 $self->{output}->perfdata_add(label => $label . $extra_label, unit => '%',                                   value => $value_perf, warning => 80,critical => 90, min => 0, max => 100 ) ;
It works fine.
I am so sorry but I am not very familiar with perl to help and contribute :(

Regards
Jackiewade

**Comment by garnier-quentin** [comment]
Hi,

That's right. The graph will always be in 'B'. Need to think about it.

**Comment by Jackiewadeshan** [comment]
Hello Quentin,

To help the community, I did a change which allowed me to get my output in % and B with suitable graphs. But I need an expert review to validate and correct if needed:
[...]
line 198: For the threshold_check I force it in % to get the status replace
#$threshold_value = $total_used;
$threshold_value = $prct_used;

--------

Line 223 - 240 remove and replace by this for perfdata output
if ($self->{option_results}->{units} eq 'B') {
	my $value_perf = $total_used;
	if (defined($self->{option_results}->{free})) {
		$label = 'free';
		$value_perf = $total_free;
	}
	my $extra_label = '';
	$extra_label = '_' . $name_storage if ($multiple == 1);
	my %total_options = ();
	$self->{output}->perfdata_add(label => $label . $extra_label, unit => 'B',
	value => $value_perf,
	warning => int ($total_size * $self->{option_results}->{warning} / 100),
	critical => int ($total_size * $self->{option_results}->{critical} / 100),
	min => 0, max => int($total_size - $reserved_value));
}
else {
	my $value_perf = $prct_used;
	if (defined($self->{option_results}->{free})) {
		$label = 'free';
		$value_perf = $prct_free;
	}
	my $extra_label = '';
	$extra_label = '_' . $name_storage if ($multiple == 1);
	my %total_options = ();
	$total_options{total} = $total_size - $reserved_value;
	$total_options{cast_int} = 1;
	$self->{output}->perfdata_add(  label => $label . $extra_label, unit => '%',
	value => $value_perf,
	warning => $self->{option_results}->{warning},
	critical => $self->{option_results}->{critical},
	min => 0, max => 100 ) ;
}
  
[...]

Then test by --units=% or B

./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --warning=80 --critical=90 --units=B
OK:  Storage 'C:\ Label:  Serial Number 5e89c0bf' Total: 99.90 GB Used: 58.17 GB (58.22%) Free: 41.73 GB (41.78%) | 'used'=62455726080B;85812939980;96539557478;0;107266174976
./centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --warning=80 --critical=90 --units=%
OK:  Storage 'C:\ Label:  Serial Number 5e89c0bf' Total: 99.90 GB Used: 58.17 GB (58.22%) Free: 41.73 GB (41.78%) | 'used'=58.2249959914894%;80;90;0;100

Regards
Jackie

**Comment by cmeschin** [comment]
Hi Jackie,

(Sorry if my english is not very good.)

I think that it is not a good idea to modify the output value of metric "used" with the argument "--units" because it serves to specify the unit of the thresholds of control.
Furthermore, metric "used" in Bite is also used for additionals modules as "Centreon BI" and reports of capacity.
If one used metric return a value in Bite and an other one in %, the report will make no sense. It would be as to compare cabbages and carrots :)

It would be preferable that one additional metric returned, for example "used_prct", with the data of performance in % as you want.
the compatibility would be assured between the various modules and others similars plugins.

Quentin, what do you think about it?

regards
Cedric Meschin.

**Comment by julienmathis** [comment]
Hello all, 

May be the solution is to add a new parameter in order to specify if users want to have metrics in % or in Bit ? And by default the metric will be Bit.

**Comment by garnier-quentin** [comment]
I can add the '%' perfdata also. '--filter-perfdata' exist to choose metrics.

**Comment by cmeschin** [comment]
Hi Quentin,
You moved forward about metric "used" with the mode free or not at all?

regards

**Comment by Jackiewadeshan** [comment]
Hello Quentin,

The idea of adding '%' perfdata and use the existing --filter-perfdata sounds good :).

Please inform us when done we can help by testing in a real environment

Regards

**Comment by romsworld** [comment]
Any news about this option ?

Thanks,

**Comment by benoitb21** [comment]
To have my 'used' and 'size' perfdatas when I use the 'free' argument, I comment those lines in the plugins at each update:
if (defined($self->{option_results}->{free})) {
$label = 'free';
$value_perf = $total_free;
}

**Comment by garnier-quentin** [comment]
With that solution, the threshold is not good.

**Comment by benoitb21** [comment]
For example, I use this command, and my threshold is OK:
/usr/lib/centreon/plugins/centreon_linux_snmp.pl
	--plugin=os::linux::snmp::plugin
	--mode=storage
	--hostname=XXX.XXX.XXX.XXX
	--snmp-version='2c'
	--snmp-community='xxxxx' 
	--storage '/xxx/xxx'
	--name
	--display-transform-src=''
	--display-transform-dst=''
	--warning='2147483648:'
	--critical='1073741824:'
	--free
	--units='B'
	--explode-perfdata-max='used,size'

**Comment by garnier-quentin** [comment]
In the perfdata output ;)

**Comment by benoitb21** [comment]
I don't understand the problem:
![image](https://user-images.githubusercontent.com/19145945/30955789-2bf2f1dc-a435-11e7-8854-b5398572297f.png)
![image](https://user-images.githubusercontent.com/19145945/30955808-40311cfa-a435-11e7-8240-55705f47e6ae.png)

**Comment by garnier-quentin** [comment]
As you can see the threshold has no meaning. It's for 'free' and not 'used'.

**Comment by benoitb21** [comment]
OK, I understand ;)
So, is it difficult in the case of 'free' argument using, to replace the thresholds 'warning' and 'critical' by 'total_size'-'warning' and 'total_size'-'critical', in order to have the good thresholds in the perfdata?

**Comment by garnier-quentin** [comment]
In theory yes. But not in the code. It needs to change a lot of codes i think.

**Comment by cmeschin** [comment]
Hi,
Have you can validate proposed fix request by @lkco

thanks.

**Comment by cgagnaire** [comment]
Hi @cmeschin,
We (@Sims24, @garnier-quentin and I) are thinking about this. 
This is more of a project thinking than just a mode from a plugin.
We’ll try to handle every thresholds and perfdata needs from it...
You’ll have to wait for it :)

**Comment by cmeschin** [comment]
Hi @cgagnaire 
ok i know you work a lot on a lot of topics. and the proof is you are logged at past eleven :)
takes the necessary time.
PS: welcome back @garnier-quentin 

thanks.

**Comment by garnier-quentin** [comment]
PR #1313 

You can use following option to change free in used:
```
--change-perfdata=free,used,invert()
```
