### ISSUE TITLE
ups::powerware::snmp::mode::batterystatus // Modification du retour pour le ['batteryFloating', 'WARNING']," par OK

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#790]
Please follow information shown below according your issue. For all issues, thank you to describe it in English.
If some informations are confidentials, please send it directly by email to qgarnier@centreon.com and sbomm@centreon.com

## Bug/Question
D'après le constructeur EATON le retour "batteryFloating" est normal , ce mode permet d'user moins de batterie pour les onduleurs.

A voir de votre côté si ce retour est partinent ou pas.

## New plugins and modes

To develop a plugin/mode, we need following informations:
* SNMP: MIBs files and full snmpwalk of entreprise branch (snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk)
* HTTP API (SOAP, Rest/Json, XML-RPC): the documentation and some curls examples
* CLI: command line examples
* SQL: requests
* JMX: mbean names and attributes

If you can't provide informations, we'll close the ticket. The issue can be reopened if informations are provided.
All developments are open-source. We can't give a date for the development. If it's a priority, send us an email about it (qgarnier@centreon.com and sbomm@centreon.com) 
and we'll put you in touch with our company. 

Thanks for using centreon-plugins!

**Comment by Sims24** [comment]
Hello, 

Is this possible to have a snmpwalk from your device ? 

Thanks,

**Comment by Jordan91** [comment]
Hi,

No problem!

**Comment by Jordan91** [comment]
Hi,

You can find the snmpwalk in attach. 

Best regards, 
[putty (1).log](https://github.com/centreon/centreon-plugins/files/1421311/putty.1.log)

**Comment by garnier-quentin** [comment]
Ok. We'll update it.
