### ISSUE TITLE
os::freebsd::snmp::plugin --mode=cpu doesn't work since pfsense 2.4

### ISSUE THREAD

**Issue by LemonLight** [centreon/centreon-plugins#791]
Hi !

I recently upgraded some of pfsense VM to new version 2.4. Since the upgrade, I have an issue with my CPU check.

Here there is my command :
`
$USER1$/centreon-plugins/centreon_plugins.pl --plugin=os::freebsd::snmp::plugin --mode=cpu --hostname=$HOSTADDRESS$ --snmp-version=2c --snmp-community=$_HOSTSNMPCOMMUNITY$ --warning=$ARG1$ --critical=$ARG2$
`
It works perfeclty on other pfsense where the version is  <2.4

Thanks in advance !

**Comment by Sims24** [comment]
Hi, 

Could you give us the error message returned by the plugin ? 

Also, if you may provides a snmpwalk of the .1.3.6.1.2.1.25.3.3.1.2 oid branch please ? 

Thanks

**Comment by LemonLight** [comment]
Here you have the error:
`
UNKNOWN: SNMP Table Request: Cant get a single value.
`
And you have the snmpwalk result:
`
HOST-RESOURCES-MIB::hrProcessorLoad = No Such Object available on this agent at this OID
`

Thank you :)

**Comment by LemonLight** [comment]
My bad. I made a mistake, it is all good now :)
