### ISSUE TITLE
centreon::common::airespace::snmp::mode::apstatus mode problem

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#795]
Hi,

I tried to check APs one by one, if I need to filter then they are not filtered correctly.
For example: AP named St6#1
If I put the AP name like this: 'St6#1'
I still get Total ap : 2. Because there is a AP named St6#11 also.

Am I filtering it incorrectly or is there a logic problem in code?

**Comment by garnier-quentin** [comment]
Could you give your command line please ? (don't need the IP).

**Comment by kadrika** [comment]
$USER1$/centreon_plugins.pl --plugin network::cisco::wlc::snmp::plugin --mode=ap-status --filter-name='$_SERVICEAPNAME$' --hostname=$HOSTADDRESS$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-version=$_HOSTSNMPVERSION$ --critical-total-associated=1:

**Comment by garnier-quentin** [comment]
You can use like this: --filter-name='^St6#1$'

**Comment by kadrika** [comment]
ok, thanks, I will test it

**Comment by kadrika** [comment]
Thanks it works!
