### ISSUE TITLE
[os::windows::local::plugin] --mode=sessions: warning & critical not working

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#796]
Centreon Plugins 20171013

`centreon_plugins.exe --plugin=os::windows::local::plugin --mode=sessions --statefile-dir=%tmp% --config=c:\qwinsta.xml --verbose --filter-sessionname= --warning-active=10`

`Unknown option: warning-active at C:\Users\ADMINI~1\AppData\Local\Temp\2\par-41646d696e6973747261746f72\cache-61770dd3530c63f8773a684380ec0b7e52b55dd1\inc\lib/centreon/plugins/alternative/Getopt.pm line 67.`

**Comment by garnier-quentin** [comment]
The option is: --warning-sessions-active=10

**Comment by joschi99** [comment]
thanks. it works.
