### ISSUE TITLE
/network/paloalto/snmp/ => Update for the OS Version 8.0.5

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#800]
## New plugins and modes
Hi
Please find in attach the MIB for Palo Alto running in 8.0.5 Version.

Can you update the plugin ?

[PAN-MIB-MODULES-8.0.zip](https://github.com/centreon/centreon-plugins/files/1461096/PAN-MIB-MODULES-8.0.zip)

Best regards,

**Comment by garnier-quentin** [comment]
I have take a look. It seems there is nothing in the mib for the memory.

**Comment by georgeprica** [comment]
Hello,

as I know, the MIB for the memory is in the HOST-RESOURCES-MIB.

thank you.

**Comment by garnier-quentin** [comment]
Done! You can test it.
