### ISSUE TITLE
[network::checkpoint::snmp::plugin] mode interfaces

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#801]
Hello,

We have a problem issue with this mode :
Lan1 and Lan2 have trafic without --interface and --name parameters :
[centreon-engine@myhost ~]$ /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl  --plugin=network::checkpoint::snmp::plugin --mode=interfaces --hostname=10.10.10.10 --snmp-version=3 --snmp-username=UUUU --authprotocol=MD5 --authpassphrase=XXXXXX--privprotocol=DES --privpassphrase=YYYYYYY --snmp-timeout=15 --snmp-retries=1 --verbose --contextname=ZZZZZZ
OK: All interfaces are ok | 'traffic_in_Lan1'=160033053.33b/s;;;0;1000000000 'traffic_out_Lan1'=150574864.62b/s;;;0;1000000000 'traffic_in_Lan2'=153615577.64b/s;;;0;1000000000 'traffic_out_Lan2'=22231590.77b/s;;;0;1000000000 'traffic_in_Lan3'=9668718.97b/s;;;0;100000000 'traffic_out_Lan3'=61021483.90b/s;;;0;100000000 'traffic_in_Exp1-1'=42944723.69b/s;;;0;1000000000 'traffic_out_Exp1-1'=130492510.97b/s;;;0;1000000000 'traffic_in_lo1'=3630.97b/s;;;0;10000000 'traffic_out_lo1'=3630.97b/s;;;0;10000000 'traffic_in_Lan5.314'=1926.77b/s;;;0;1000000000 'traffic_out_Lan5.314'=1937.85b/s;;;0;1000000000 'traffic_in_Lan5.311'=1753.44b/s;;;0;1000000000 'traffic_out_Lan5.311'=1986.05b/s;;;0;1000000000 'traffic_in_Lan5.313'=2002.67b/s;;;0;1000000000 'traffic_out_Lan5.313'=1994.46b/s;;;0;1000000000 'traffic_in_Lan4.423'=95520.00b/s;;;0;1000000000 'traffic_out_Lan4.423'=25758.15b/s;;;0;1000000000 'traffic_in_Lan5.318'=86.56b/s;;;0;1000000000 'traffic_out_Lan5.318'=43.49b/s;;;0;1000000000 'traffic_in_Lan4.406'=336607.38b/s;;;0;1000000000 'traffic_out_Lan4.406'=244507.69b/s;;;0;1000000000 'traffic_in_Lan4.413'=654759.38b/s;;;0;1000000000 'traffic_out_Lan4.413'=704440.82b/s;;;0;1000000000 'traffic_in_Lan5.317'=303.38b/s;;;0;1000000000 'traffic_out_Lan5.317'=17.64b/s;;;0;1000000000 'traffic_in_Lan4.403'=783367.79b/s;;;0;1000000000 'traffic_out_Lan4.403'=657194.67b/s;;;0;1000000000 'traffic_in_Lan4.408'=8670.77b/s;;;0;1000000000 'traffic_out_Lan4.408'=10111.79b/s;;;0;1000000000 'traffic_in_Lan4.407'=11998.97b/s;;;0;1000000000 'traffic_out_Lan4.407'=8602.26b/s;;;0;1000000000 'traffic_in_Lan5.315'=236.51b/s;;;0;1000000000 'traffic_out_Lan5.315'=246.77b/s;;;0;1000000000 'traffic_in_Lan4.404'=554171.28b/s;;;0;1000000000 'traffic_out_Lan4.404'=644058.26b/s;;;0;1000000000 'traffic_in_Lan4.405'=505696.82b/s;;;0;1000000000 'traffic_out_Lan4.405'=646298.46b/s;;;0;1000000000 'traffic_in_Lan5.319'=13123.90b/s;;;0;1000000000 'traffic_out_Lan5.319'=15770.46b/s;;;0;1000000000 'traffic_in_Lan5.321'=127.18b/s;;;0;1000000000 'traffic_out_Lan5.321'=102.56b/s;;;0;1000000000
Interface 'Lan1' Traffic In : 160.03Mb/s (16.00%), Traffic Out : 150.57Mb/s (15.06%)
Interface 'Lan2' Traffic In : 153.62Mb/s (15.36%), Traffic Out : 22.23Mb/s (2.22%)
Interface 'Lan3' Traffic In : 9.67Mb/s (9.67%), Traffic Out : 61.02Mb/s (61.02%)
Interface 'Exp1-1' Traffic In : 42.94Mb/s (4.29%), Traffic Out : 130.49Mb/s (13.05%)
Interface 'lo1' Traffic In : 3.63Kb/s (0.04%), Traffic Out : 3.63Kb/s (0.04%)
Interface 'Lan5.314' Traffic In : 1.93Kb/s (0.00%), Traffic Out : 1.94Kb/s (0.00%)
Interface 'Lan5.311' Traffic In : 1.75Kb/s (0.00%), Traffic Out : 1.99Kb/s (0.00%)
Interface 'Lan5.313' Traffic In : 2.00Kb/s (0.00%), Traffic Out : 1.99Kb/s (0.00%)
Interface 'Lan4.423' Traffic In : 95.52Kb/s (0.01%), Traffic Out : 25.76Kb/s (0.00%)
Interface 'Lan5.318' Traffic In : 86.56b/s (0.00%), Traffic Out : 43.49b/s (0.00%)
Interface 'Lan4.406' Traffic In : 336.61Kb/s (0.03%), Traffic Out : 244.51Kb/s (0.02%)
Interface 'Lan4.413' Traffic In : 654.76Kb/s (0.07%), Traffic Out : 704.44Kb/s (0.07%)
Interface 'Lan5.317' Traffic In : 303.38b/s (0.00%), Traffic Out : 17.64b/s (0.00%)
Interface 'Lan4.403' Traffic In : 783.37Kb/s (0.08%), Traffic Out : 657.19Kb/s (0.07%)
Interface 'Lan4.408' Traffic In : 8.67Kb/s (0.00%), Traffic Out : 10.11Kb/s (0.00%)
Interface 'Lan4.407' Traffic In : 12.00Kb/s (0.00%), Traffic Out : 8.60Kb/s (0.00%)
Interface 'Lan5.315' Traffic In : 236.51b/s (0.00%), Traffic Out : 246.77b/s (0.00%)
Interface 'Lan4.404' Traffic In : 554.17Kb/s (0.06%), Traffic Out : 644.06Kb/s (0.06%)
Interface 'Lan4.405' Traffic In : 505.70Kb/s (0.05%), Traffic Out : 646.30Kb/s (0.06%)
Interface 'Lan5.319' Traffic In : 13.12Kb/s (0.00%), Traffic Out : 15.77Kb/s (0.00%)
Interface 'Lan5.321' Traffic In : 127.18b/s (0.00%), Traffic Out : 102.56b/s (0.00%)

Same result if i use these parameters --interface='.*' --name

But they do not have trafic with these parameters : --interface='Lan1|Lan2' --name
[centreon-engine@myhost ~]$ /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl  --plugin=network::checkpoint::snmp::plugin --mode=interfaces --interface='Lan1|Lan2' --name --add-traffic --hostname=10.10.10.10 --snmp-version=3 --snmp-username=UUUU --authprotocol=MD5 --authpassphrase=XXXXXX--privprotocol=DES --privpassphrase=YYYYYYY --snmp-timeout=15 --snmp-retries=1 --verbose --contextname=ZZZZZZ
OK: All interfaces are ok |
Interface 'Lan1'
Interface 'Lan2'

**Comment by ritouret** [comment]
And there is trafic if i test with --interface='Lan4|Lan5' --name !!!
[centreon-engine@myhost ~]$ /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::checkpoint::snmp::plugin --mode=interfaces --interface='Lan1|Lan2' --name --add-traffic --hostname=10.10.10.10 --snmp-version=3 --snmp-username=UUUU --authprotocol=MD5 --authpassphrase=XXXXXX--privprotocol=DES --privpassphrase=YYYYYYY --snmp-timeout=15 --snmp-retries=1 --verbose --contextname=ZZZZZZ
OK: All interfaces are ok | 'traffic_in_Lan5.314'=895.83b/s;;;0;1000000000 'traffic_out_Lan5.314'=858.00b/s;;;0;1000000000 'traffic_out_Lan5.318'=3.50b/s;;;0;1000000000 'traffic_in_Lan4.406'=160217.33b/s;;;0;1000000000 'traffic_out_Lan4.406'=145596.75b/s;;;0;1000000000 'traffic_in_Lan4.413'=595429.33b/s;;;0;1000000000 'traffic_out_Lan4.413'=653375.08b/s;;;0;1000000000 'traffic_in_Lan5.317'=2010.92b/s;;;0;1000000000 'traffic_out_Lan5.317'=1194.83b/s;;;0;1000000000 'traffic_in_Lan5.315'=288.25b/s;;;0;1000000000 'traffic_out_Lan5.315'=304.25b/s;;;0;1000000000 'traffic_in_Lan4.404'=273894.92b/s;;;0;1000000000 'traffic_out_Lan4.404'=348895.83b/s;;;0;1000000000 'traffic_in_Lan5.319'=15877.83b/s;;;0;1000000000 'traffic_out_Lan5.319'=18034.67b/s;;;0;1000000000 'traffic_in_Lan5.321'=1201.75b/s;;;0;1000000000 'traffic_out_Lan5.321'=1006.92b/s;;;0;1000000000
Interface 'Lan5.314' Status : up (admin: up), Traffic In : 895.83b/s (0.00%), Traffic Out : 858.00b/s (0.00%)
Interface 'Lan5.311' Status : up (admin: up)
Interface 'Lan5.313' Status : up (admin: up)
Interface 'Lan4.423' Status : up (admin: up)
Interface 'Lan5.318' Status : up (admin: up), Traffic In : skipped, Traffic Out : 3.50b/s (0.00%)
Interface 'Lan4.406' Status : up (admin: up), Traffic In : 160.22Kb/s (0.02%), Traffic Out : 145.60Kb/s (0.01%)
Interface 'Lan4.413' Status : up (admin: up), Traffic In : 595.43Kb/s (0.06%), Traffic Out : 653.38Kb/s (0.07%)
Interface 'Lan5.317' Status : up (admin: up), Traffic In : 2.01Kb/s (0.00%), Traffic Out : 1.19Kb/s (0.00%)
Interface 'Lan4.403' Status : up (admin: up)
Interface 'Lan4.408' Status : up (admin: up)
Interface 'Lan4.407' Status : up (admin: up)
Interface 'Lan5.315' Status : up (admin: up), Traffic In : 288.25b/s (0.00%), Traffic Out : 304.25b/s (0.00%)
Interface 'Lan4.404' Status : up (admin: up), Traffic In : 273.89Kb/s (0.03%), Traffic Out : 348.90Kb/s (0.03%)
Interface 'Lan4.405' Status : up (admin: up)
Interface 'Lan5.319' Status : up (admin: up), Traffic In : 15.88Kb/s (0.00%), Traffic Out : 18.03Kb/s (0.00%)
Interface 'Lan5.321' Status : up (admin: up), Traffic In : 1.20Kb/s (0.00%), Traffic Out : 1.01Kb/s (0.00%)

**Comment by garnier-quentin** [comment]
Same problem Dominique:
https://github.com/centreon/centreon-plugins/issues/786

Please use option: --statefile-suffix=contextname

**Comment by ritouret** [comment]
solved with --force-counters32 option
