### ISSUE TITLE
[hardware::server::ibm::mgmt_cards::imm::snmp] Question\Modification for the fan mode

### ISSUE THREAD

**Issue by cpelichet** [centreon/centreon-plugins#802]
Hi , 
In advance sorry for my english :)

We have a question for the IMM fan mode . By default in the mode, if a fan is "offline" we have a warning in Centreon.

--------------------

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname xxx.xxx.xxx.xxx --snmp-community xxxxxxxxx --snmp-timeout 20 --component fan --debug

WARNING: Fan 'Fan 4A Tach' is offline - Fan 'Fan 4B Tach' is offline | 'fan_Fan 1A Tach'=40%;;;0;100 'fan_Fan 1B Tach'=36%;;;0;100 'fan_Fan 2A Tach'=40%;;;0;100 'fan_Fan 2B Tach'=37%;;;0;100 'fan_Fan 3A Tach'=40%;;;0;100 'fan_Fan 3B Tach'=37%;;;0;100 'fan_Fan 5A Tach'=39%;;;0;100 'fan_Fan 5B Tach'=36%;;;0;100 'fan_Fan 6A Tach'=37%;;;0;100 'fan_Fan 6B Tach'=32%;;;0;100 'fan_Fan 7A Tach'=40%;;;0;100 'fan_Fan 7B Tach'=36%;;;0;100 'fan_Fan 8A Tach'=38%;;;0;100 'fan_Fan 8B Tach'=32%;;;0;100
Checking fans
Fan 'Fan 1A Tach' speed is 40% of maximum.
Fan 'Fan 1B Tach' speed is 36% of maximum.
Fan 'Fan 2A Tach' speed is 40% of maximum.
Fan 'Fan 2B Tach' speed is 37% of maximum.
Fan 'Fan 3A Tach' speed is 40% of maximum.
Fan 'Fan 3B Tach' speed is 37% of maximum.
Fan 'Fan 4A Tach' speed is offline.
Fan 'Fan 4B Tach' speed is offline.
Fan 'Fan 5A Tach' speed is 39% of maximum.
Fan 'Fan 5B Tach' speed is 36% of maximum.
Fan 'Fan 6A Tach' speed is 37% of maximum.
Fan 'Fan 6B Tach' speed is 32% of maximum.
Fan 'Fan 7A Tach' speed is 40% of maximum.
Fan 'Fan 7B Tach' speed is 36% of maximum.
Fan 'Fan 8A Tach' speed is 38% of maximum.
Fan 'Fan 8B Tach' speed is 32% of maximum.
------------------------------

We would like to ignore this warning because we do not necessarily buy all the fans in our servers. We looked for a similiar command used for the procurve mode ( --threshold-overload='sensor,OK,not present' ) but we have not found.

Is there a way to do this simply or is it possible to have a modification for this mode ?

Thanks in advance
Regards.

**Comment by garnier-quentin** [comment]
The mode is too old. I need to update it. I'm doing it tonight. You could test it after ;)

**Comment by cpelichet** [comment]
Sure !!

Thanks for the job :)

**Comment by garnier-quentin** [comment]
Could you test it ? You can use following: --threshold-overload='fan,OK,offline'
If there is a problem, i need the file:
$ snmpwalk -ObentU -v 2c -c public IP_IMM .1.3.6.1.4.1.2.3.51 > imm.snmpwalk

**Comment by cpelichet** [comment]
It works perfectly 

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname xxx.xxx.xxx.xxx --snmp-community xxxxxxxx --snmp-timeout 20 --component fan  --threshold-overload='fan,OK,offline'

OK: All 16 components are ok [16/16 fans]. | 'fan_Fan 1A Tach'=40%;;;0;100 'fan_Fan 1B Tach'=36%;;;0;100 'fan_Fan 2A Tach'=40%;;;0;100 'fan_Fan 2B Tach'=37%;;;0;100 'fan_Fan 3A Tach'=40%;;;0;100 'fan_Fan 3B Tach'=37%;;;0;100 'fan_Fan 5A Tach'=40%;;;0;100 'fan_Fan 5B Tach'=36%;;;0;100 'fan_Fan 6A Tach'=37%;;;0;100 'fan_Fan 6B Tach'=32%;;;0;100 'fan_Fan 7A Tach'=40%;;;0;100 'fan_Fan 7B Tach'=36%;;;0;100 'fan_Fan 8A Tach'=38%;;;0;100 'fan_Fan 8B Tach'=32%;;;0;100

Again thanks for the job :)

**Comment by cpelichet** [comment]
When we try with --component=.* we have always the same answer :

 UNKNOWN: SNMP Table Request : Timeout

We have try with --snmp-timeout 20 , 30 , 60 , 300 same result.


[root@iXmonitor2_Poller_iXion centreon-plugins]# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname xxx.xxx.xxx.xxx --snmp-community xxxxxxxx --snmp-timeout 300

UNKNOWN: SNMP Table Request : Timeout


I check this morning all component one by one

**Comment by garnier-quentin** [comment]
Could you test with --snmp-force-getnext for all components ?

**Comment by cpelichet** [comment]
This morning i have test all mode , bellow my result : 

----------------------------------------------------------------------------------------------------------
Fan :  
Working with this command
 
centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname xxx.xxx.xxx.xxx --snmp-community xxxxx --snmp-timeout 20  --component=fan --threshold-overload='fan,OK,offline'

OK: All 16 components are ok [16/16 fans]. | 'fan_Fan 1A Tach'=40%;;;0;100 'fan_Fan 1B Tach'=36%;;;0;100 'fan_Fan 2A Tach'=40%;;;0;100 'fan_Fan 2B Tach'=36%;;;0;100 'fan_Fan 3A Tach'=40%;;;0;100 'fan_Fan 3B Tach'=36%;;;0;100 'fan_Fan 5A Tach'=40%;;;0;100 'fan_Fan 5B Tach'=36%;;;0;100 'fan_Fan 6A Tach'=37%;;;0;100 'fan_Fan 6B Tach'=32%;;;0;100 'fan_Fan 7A Tach'=39%;;;0;100 'fan_Fan 7B Tach'=36%;;;0;100 'fan_Fan 8A Tach'=38%;;;0;100 'fan_Fan 8B Tach'=31%;;;0;100

----------------------------------------------------------------------------------------------------------
Temperature :
Working with this command

centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx  --snmp-community=xxxxxxxx --snmp-timeout 20 --component=temperature --filter=temperature,16 --warning=temperature,.*,60 --critical=temperature,.*,65

OK: All 11 components are ok [11/11 temperatures]. | 'temp_Ambient Temp'=26C;0:60;0:65;; 'temp_PCI Riser 1 Temp'=40C;0:60;0:65;; 'temp_PCI Riser 2 Temp'=33C;0:60;0:65;; 'temp_Mezz Card Temp'=0C;0:60;0:65;; 'temp_CPU1 VR Temp'=32C;0:60;0:65;; 'temp_CPU2 VR Temp'=30C;0:60;0:65;; 'temp_DIMM AB VR Temp'=32C;0:60;0:65;; 'temp_DIMM CD VR Temp'=30C;0:60;0:65;; 'temp_DIMM EF VR Temp'=29C;0:60;0:65;; 'temp_DIMM GH VR Temp'=30C;0:60;0:65;; 'temp_PCH Temp'=47C;0:60;0:65;;
----------------------------------------------------------------------------------------------------------

Voltage : 
Working with this command

centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx  --snmp-community=xxxxxxx --snmp-timeout 20 --component=voltage

CRITICAL: Voltage 'CMOS Battery' is 3175 WARNING: Voltage 'SysBrd 3.3V' is 3294 - Voltage 'SysBrd 5V' is 5062 - Voltage 'SysBrd 12V' is 12150 | 'volt_SysBrd 3.3V'=3294;0:0;3038:3564;; 'volt_SysBrd 5V'=5062;0:0;4474:5582;; 'volt_SysBrd 12V'=12150;0:0;10692:13446;; 'volt_CMOS Battery'=3175;2247:0;2095:0;;
----------------------------------------------------------------------------------------------------------

All Components : 
Not Working with this command 

centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname xxx.xxx.xxx.xxx --snmp-community xxxxxxxx --snmp-timeout 300

UNKNOWN: SNMP Table Request : Timeou


Working with this command:

centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname xxx.xxx.xxx.xxx --snmp-community xxxxxxxx --snmp-force-getnext

CRITICAL: Voltage 'CMOS Battery' is 3175 WARNING: Voltage 'SysBrd 3.3V' is 3294 - Voltage 'SysBrd 5V' is 5062 - Voltage 'SysBrd 12V' is 12150 | 'temp_Ambient Temp'=27C;0:43;0:46;; 'temp_PCI Riser 1 Temp'=40C;0:70;0:80;; 'temp_PCI Riser 2 Temp'=33C;0:70;0:80;; 'temp_Mezz Card Temp'=0C;0:0;0:0;; 'temp_CPU1 VR Temp'=32C;0:95;0:100;; 'temp_CPU2 VR Temp'=31C;0:95;0:100;; 'temp_DIMM AB VR Temp'=32C;0:95;0:100;; 'temp_DIMM CD VR Temp'=31C;0:95;0:100;; 'temp_DIMM EF VR Temp'=30C;0:95;0:100;; 'temp_DIMM GH VR Temp'=30C;0:95;0:100;; 'temp_PCH Temp'=47C;0:93;0:98;; 'volt_SysBrd 3.3V'=3294;0:0;3038:3564;; 'volt_SysBrd 5V'=5062;0:0;4474:5582;; 'volt_SysBrd 12V'=12150;0:0;10692:13446;; 'volt_CMOS Battery'=3175;2247:0;2095:0;; 'fan_Fan 1A Tach'=47%;;;0;100 'fan_Fan 1B Tach'=50%;;;0;100 'fan_Fan 2A Tach'=48%;;;0;100 'fan_Fan 2B Tach'=49%;;;0;100 'fan_Fan 3A Tach'=47%;;;0;100 'fan_Fan 3B Tach'=50%;;;0;100 'fan_Fan 4A Tach'=50%;;;0;100 'fan_Fan 4B Tach'=44%;;;0;100 'fan_Fan 5A Tach'=50%;;;0;100 'fan_Fan 5B Tach'=43%;;;0;100 'fan_Fan 6A Tach'=50%;;;0;100 'fan_Fan 6B Tach'=43%;;;0;100

----------------------------------------------------------------------------------------------------------

Global : 

It's working with this commande but i think the answer is strange . I don't understand how the status is OK with 0 components

centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx  --snmp-community=xxxxxx --snmp-timeout 20 --component=global --debug

OK: All 0 components are ok []. |
Checking system health
system health status is 'nominal'

Question : --snmp-force-getnext is better than snmp-timeout ? because we have a lot off Process Timeout

**Comment by garnier-quentin** [comment]
Ok i see. i'll do the fix.

**Comment by garnier-quentin** [comment]
Could you test it with the last version for component 'global' and 'voltage' please ? :)

**Comment by cpelichet** [comment]
Hello, 

Sorry for the delay  : 
-----------------------------------------------------------------------------
Voltage : 
New result with this command :

centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx --snmp-community=xxxxxxx --snmp-timeout 20 --component=voltage --debug

OK: All 4 components are ok [4/4 voltages]. | 'volt_SysBrd 3.3V'=3294;0:;3038:3564;; 'volt_SysBrd 5V'=5062;0:;4474:5582;; 'volt_SysBrd 12V'=12150;0:;10692:13446;; 'volt_CMOS Battery'=3175;2247:;2095:;;
Checking voltages
voltage 'SysBrd 3.3V' value is 3294 [instance: 1].
voltage 'SysBrd 5V' value is 5062 [instance: 2].
voltage 'SysBrd 12V' value is 12150 [instance: 3].
voltage 'CMOS Battery' value is 3175 [instance: 4].

------------------------------------------------------------
Global : 
New result with this command :

centreon_plugins.pl --plugin=hardware::server::ibm::mgmt_cards::imm::snmp::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx --snmp-community=xxxxxx --snmp-timeout 20 --component=global --debug

OK: All 1 components are ok [1/1 system health]. |
Checking system health
system health status is 'nominal'
