### ISSUE TITLE
Oracle plugin : Multiple databases per server

### ISSUE THREAD

**Issue by boupjof** [centreon/centreon-plugins#803]
Hello, 

My question is in the title, is there a good way to monitor more tahn one database per server ? Actualy macro command and template are host based. 
I can duplicate host to sufix it with database SID ? 
Maybe, release a templace with service based macro ? 

Thanks for helping

**Comment by garnier-quentin** [comment]
Thanks for the feedback. It's something linked with centreon (not centreon-plugins). You can open a ticket in centreon github. But i think it's already done.
