### ISSUE TITLE
ADD New mode Temperature for storage::emc::clariion::plugin

### ISSUE THREAD

**Issue by jronzon** [centreon/centreon-plugins#806]
Hello,

I had a question for the plugin storage::emc::clariion::plugin.
Is it possible to add a new mode for check temperature of different DAE ?

 ## New plugins and modes

To develop a plugin/mode, we need following informations:
* CLI: command line examples
/opt/Navisphere/bin/naviseccli -Address Address_IP environment -list -enclosure | grep -E '(^D.E|degree)' | ( name="A device name : Present (degree C) : Average (degree C)"; while read line; do if [ "${line:0:1}" == "D" ]; then echo "$name"; name="${line}"; else name="${name} : ${line/#*:/}"; fi; done ) | sort
RESULT : 
A device name : Present (degree C) : Average (degree C)
DAE6S Bus 0 Enclosure 1 :  24 :  24
DAE6S Bus 0 Enclosure 2 :  26 :  25
DAE6S Bus 0 Enclosure 3 :  24 :  24
DAE6S Bus 0 Enclosure 4 :  24 :  24
...

And add warning and critical temperature.

Thanks !

**Comment by garnier-quentin** [comment]
Could you give the full result of navieccli command ?

**Comment by jronzon** [comment]
The resutl of command cli : 
**/opt/Navisphere/bin/naviseccli -Address Address_IP environment -list -enclosure**

DPE7 Bus 0 Enclosure 0

Input Power
Status: Valid
Present(watts): 426
Rolling Average(watts): 430

Air Inlet Temperature
Status: Valid
Present(degree C): 24
Rolling Average(degree C): 23

DAE6S Bus 0 Enclosure 3

Input Power
Status: Valid
Present(watts): 227
Rolling Average(watts): 228

Air Inlet Temperature
Status: Valid
Present(degree C): 26
Rolling Average(degree C): 26

DAE6S Bus 0 Enclosure 4

Input Power
Status: Valid
Present(watts): 224
Rolling Average(watts): 223

Air Inlet Temperature
Status: Valid
Present(degree C): 25
Rolling Average(degree C): 25

DAE6S Bus 0 Enclosure 5

Input Power
Status: Valid
Present(watts): 238
Rolling Average(watts): 238

Air Inlet Temperature
Status: Valid
Present(degree C): 26
Rolling Average(degree C): 26

DAE6S Bus 0 Enclosure 6

Input Power
Status: Valid
Present(watts): 244
Rolling Average(watts): 241

Air Inlet Temperature
Status: Valid
Present(degree C): 28
Rolling Average(degree C): 28

DAE6S Bus 0 Enclosure 7

Input Power
Status: Valid
Present(watts): 236
Rolling Average(watts): 236

Air Inlet Temperature
Status: Valid
Present(degree C): 27
Rolling Average(degree C): 27

DAE6S Bus 1 Enclosure 3

Input Power
Status: Valid
Present(watts): 227
Rolling Average(watts): 227

Air Inlet Temperature
Status: Valid
Present(degree C): 25
Rolling Average(degree C): 25

DAE6S Bus 1 Enclosure 4

Input Power
Status: Valid
Present(watts): 153
Rolling Average(watts): 153

Air Inlet Temperature
Status: Valid
Present(degree C): 25
Rolling Average(degree C): 25

DAE6S Bus 0 Enclosure 1

Input Power
Status: Valid
Present(watts): 207
Rolling Average(watts): 207

Air Inlet Temperature
Status: Valid
Present(degree C): 26
Rolling Average(degree C): 26

DAE6S Bus 1 Enclosure 5

Input Power
Status: Valid
Present(watts): 240
Rolling Average(watts): 240

Air Inlet Temperature
Status: Valid
Present(degree C): 24
Rolling Average(degree C): 24

DAE6S Bus 0 Enclosure 2

Input Power
Status: Valid
Present(watts): 238
Rolling Average(watts): 238

Air Inlet Temperature
Status: Valid
Present(degree C): 27
Rolling Average(degree C): 27

DAE6S Bus 1 Enclosure 6

Input Power
Status: Valid
Present(watts): 239
Rolling Average(watts): 239

Air Inlet Temperature
Status: Valid
Present(degree C): 27
Rolling Average(degree C): 27

DAE6S Bus 1 Enclosure 7

Input Power
Status: Valid
Present(watts): 239
Rolling Average(watts): 240

Air Inlet Temperature
Status: Valid
Present(degree C): 28
Rolling Average(degree C): 28

DAE6S Bus 1 Enclosure 0

Input Power
Status: Valid
Present(watts): 221
Rolling Average(watts): 221

Air Inlet Temperature
Status: Valid
Present(degree C): 26
Rolling Average(degree C): 26

DAE6S Bus 1 Enclosure 1

Input Power
Status: Valid
Present(watts): 246
Rolling Average(watts): 247

Air Inlet Temperature
Status: Valid
Present(degree C): 25
Rolling Average(degree C): 25

DAE6S Bus 1 Enclosure 2

Input Power
Status: Valid
Present(watts): 233
Rolling Average(watts): 233

Air Inlet Temperature
Status: Valid
Present(degree C): 26
Rolling Average(degree C): 26

**Comment by garnier-quentin** [comment]
It's not available with getcrus command ? There is not an option for display that ?

**Comment by jronzon** [comment]
i don't now

**Comment by jronzon** [comment]
know

**Comment by lucie-dubrunfaut** [comment]
"Hello :)

This issue seems particularly old so let me close it. If the enhancement request is still current, please address it [here](https://thewatch.centreon.com/ideas) to be take into account and vote on.
Thank you for your understanding."
