### ISSUE TITLE
Protocol NTP

### ISSUE THREAD

**Issue by florian-asche** [centreon/centreon-plugins#81]
We have response-time, thats cool. Can we add some mode to check offset?

**Comment by garnier-quentin** [comment]
Check offset from the local server ? to know the time drift from your local linux ?

**Comment by florian-asche** [comment]
yes. like this: https://exchange.nagios.org/directory/Plugins/System-Metrics/Time/check_ntp_time-2Epl/details

**Comment by garnier-quentin** [comment]
It's done in plugin: apps::protocols::ntp::plugin
