### ISSUE TITLE
[Net-JuniperSRX-Cpu-Routing] - Add Extraoptions in Centreon-EPP command

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#810]
Hi, Can you add the macro "$_SERVICEEXTRAOPTIONS$ in command please?

![image](https://user-images.githubusercontent.com/8720203/33330025-091cde26-d45e-11e7-95a4-87ce44f6f05a.png)

**Comment by Sims24** [comment]
Hi, 

You should use support to open such issue as it is not related to centreon-plugins project. 

Thankq
