### ISSUE TITLE
plugin=hardware::server::hp::proliant::snmp::plugin  UNKNOWN: ide controller '0' is other

### ISSUE THREAD

**Issue by sder73** [centreon/centreon-plugins#811]
Hello

On 5 proliant I have this response and status is unknown

ProLiant   ML570 G2 | Intel(R) Xeon(TM) MP CPU 2.00GHz | 2GB | UNKNOWN: ide controller '0' is other
-- | -- | -- | --
Proliant DL580 G3 | Intel(R) Xeon(TM) CPU 3.00GHz | 4GB | UNKNOWN: ide controller '0' is other
Proliant DL380 G7 | Intel(R) Xeon(R) CPU E5506 @ 2.13GHz | 8GB | UNKNOWN: ide controller   '0' is other
Proliant DL380 G5 | Intel(R) Xeon(R) CPU E5440 @ 2.83GHz | 4GB | UNKNOWN: ide controller '0' is other
Proliant DL380 G9 | Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz | 64GB | UNKNOWN: ide controller '0' is other

on other servers I have no trouble
Could you help me to resolve this problem

Thank you

**Comment by garnier-quentin** [comment]
Please use following option:
```
--threshold-overload='idectl,OK,other'
```
