### ISSUE TITLE
network::cisco::standard::snmp::plugin 

### ISSUE THREAD

**Issue by jdidierpichat** [centreon/centreon-plugins#815]
Hi, 

You have a mistake in the centreon_plugins network::cisco::standard::snmp::plugin 
The mode uptime in the last version is not present. 

Add line bellow in module /usr/lib/nagios/plugins/network/cisco/standard/snmp/plugin.pm

                         'uptime'           => 'centreon::common::cisco::standard::snmp::mode::uptime',

**Comment by garnier-quentin** [comment]
I don't understand. You want to add it ?

**Comment by jdidierpichat** [comment]
Hi Quentin,

I already added the uptime mode. 
The problem comes from the rpm package of the plugins or it is not up to date
The uptime mode seems to have disappeared in the latest version. 


For example : 

[root@server1]# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --list-mode

Plugin Description:
    Check Cisco equipments (2800, 2900, 3750, Nexus,...) in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

Modes Available:
   cpu
   environment
   hsrp
   interfaces
   ipsla
   list-interfaces
   memory
   memory-flash
   qos-usage
   spanning-tree
   stack


[root@server2 ~]# /usr/lib/nagios/plugins/centreon_plugins.pl --plugin network::cisco::standard::snmp::plugin --list-mode

Plugin Description:
    Check Cisco equipments (2800, 2900, 3750, Nexus,...) in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

Modes Available:
   cpu
   environment
   hsrp
   interfaces
   ipsla
   list-interfaces
   memory
   spanning-tree
   stack
   uptime
