### ISSUE TITLE
need help to find plugin!!!

### ISSUE THREAD

**Issue by VuNgocTan** [centreon/centreon-plugins#819]
Hello guys, actually this is not an issue, but I am new to centreon, and I have the following services as describe in these images, but I do not know which plugin to use to monitor these services. Please help, thanks a lot
![screenshot from 2017-12-05 23-44-17](https://user-images.githubusercontent.com/25748709/33793351-1aa93e4e-dce9-11e7-81cc-141ce33fc5d7.png)
![screenshot from 2017-12-05 23-44-53](https://user-images.githubusercontent.com/25748709/33793352-1ad69f9c-dce9-11e7-9957-1e1e444f5132.png)

**Comment by garnier-quentin** [comment]
Hi,

For interfaces:
```
--plugin=os::linux::snmp::plugin --mode=interfaces --add-status --add-traffic
```

For services (if it's windows):
```
--plugin=os::windows::snmp::plugin
```

**Comment by VuNgocTan** [comment]
oh, so basically just adding a command right ? no plugin needed ?

**Comment by VuNgocTan** [comment]
I wonder why plugin on github is .pm, while I check it is .pl

**Comment by garnier-quentin** [comment]
With Centreon, we have created fatpack files: https://github.com/centreon/centreon-plugins/blob/master/docs/en/user/guide.rst#can-i-have-one-standalone-perl-file-

**Comment by VuNgocTan** [comment]
thanks for the answer, I pulled all the plugin to my local host, but when I run this command 
> perl centreon_plugins.pl --plugin=centreon-plugins::network::cisco::standard::snmp::plugin

and it says:

> UNKNOWN: Can't locate object method "new" via package "centreon-plugins::network::cisco::standard::snmp::plugin" (perhaps you forgot to load "centreon-plugins::network::cisco::standard::snmp::plugin"?) at /root/centreon-plugins/centreon/plugins/script.pm line 356. 
what did I miss here ?

**Comment by garnier-quentin** [comment]
Please try the following command:
```
perl centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --list-mode
```

**Comment by VuNgocTan** [comment]
I dont get it, because at first you said use this command:
> --plugin=os::linux::snmp::plugin --mode=interfaces --add-status --add-traffic

then I follow it, I use this command:
> perl centreon_plugins.pl --list-plugin | grep -i linux | grep 'PLUGIN'

it listed down plugins, and then I got this:
>UNKNOWN: Can't locate object method "new" via package "centreon-plugins::network::cisco::standard::snmp::plugin" (perhaps you forgot to load "centreon-plugins::network::cisco::standard::snmp::plugin"?) at /root/centreon-plugins/centreon/plugins/script.pm line 356.

just wonder why, because I use Centreon to monitor a switch. And one more thing is that I want to ask, are these plugins can be used to monitor only on CLI, 'cause I want to check the status of each interface on web interface. Thanks

**Comment by garnier-quentin** [comment]
I think it's because you have a sub-directory "centreon-plugins".

**Comment by VuNgocTan** [comment]
wow yeah, you are right, I have a sub-directory, delete it right away, back to this question, really confuse:

> are these plugins can be used to monitor only on CLI? 'cause I want to check the status of each interface on web interface.

**Comment by garnier-quentin** [comment]
I don't understand your question. What do you mean by "only on cli" ?

**Comment by VuNgocTan** [comment]
yes, because I can use those plugins to know what is going on, like this:

> [root@centreon centreon-plugins]# perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=interfaces --add-status --add-traffic --hostname=127.0.0.1
OK: All interfaces are ok | 'traffic_in_lo'=5737.15b/s;;;0;10000000 'traffic_out_lo'=5737.15b/s;;;0;10000000 'traffic_in_eth0'=12654.64b/s;;;0;4294967295 'traffic_out_eth0'=9960.40b/s;;;0;4294967295

I just want to know, are these plugins can be applied on the web interface of Centreon or not, like showing status of interface, traffic in and out like the 2 pictures I posted at the beginning of this post.

**Comment by garnier-quentin** [comment]
Yes you can use it with centreon, icinga2, nagios,... No problem :)
