### ISSUE TITLE
Problème avec l'import d'une configuration CSV (CLAPI) dans la nouvelle version 2.6.1 Centreon

### ISSUE THREAD

**Issue by maxencelagmairi** [centreon/centreon-plugins#82]
Bonjour tout le monde,

Nous avons constaté un problème lorsque nous importons une configuration exporté via CLAPI dans la dernière version 2.6.1
En effet, cela créée un doublons des broker cbd, et du coup le poller ne se lance plus et l'icone du poller devient rouge
Une solution a été trouvé, celle de supprimer toutes les informations du centreon-broker directement dans le CSV
Mais à long terme cette solution pourrait s'avérer problématique ( si changement de certaines valeurs du broker ...)
En espérant trouver rapidement une solution je me permets donc de vous écrire ce topic
Cordialement
Maxence Lagmairi

**Comment by garnier-quentin** [comment]
Bonjour,

Vous avez posté le message dans la mauvaise forge. Ici ce n'est uniquement que les plugins. Merci de le poster ici: https://github.com/centreon/centreon
