### ISSUE TITLE
[os::windows::snmp::plugin] mode=service return always ok

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#820]
Hello,

#https://github.com/centreon/centreon-plugins/issues/416

I tried every case but the status is still ok.
` ./centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=xxx --snmp-community=xxx --snmp-version=2c --mode=service  --service=1service`
`OK: All service states are ok `

Is there anything new ?

**Comment by garnier-quentin** [comment]
You should use thresholds. Otherwise, it will stay ok.

**Comment by boogaaloo** [comment]
Sorry, I use thresholds :
` --critical :1`

I forgot to mention it

**Comment by Sims24** [comment]
`--critical 1:` is the right syntax as mentionned in #416 see answer posted on "12 Sep 2016"

**Comment by boogaaloo** [comment]
yes I know... but whatever the name of the service, I always have an exit/ok

**Comment by boogaaloo** [comment]
Examples :

`./centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=xxx --snmp-community=xx --snmp-version=2c --mode=service  --service="=MsDtsServer1220" --critical :1`
`OK: All service states are ok |`

`./centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=xxx --snmp-community=xx --snmp-version=2c --mode=service  --service="=MsDtsServer120" --critical :1`
`OK: All service states are ok |`

**Comment by garnier-quentin** [comment]
Could you use it like that ? --critical=1:

**Comment by boogaaloo** [comment]
` ./centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=xxx --snmp-community=xx --snmp-version=2c --mode=service --service=MSExchangeIS --critical=1:`
`CRITICAL: Service problem 'MSExchangeIS'`

But the service MSExchangeIS is actually running

**Comment by boogaaloo** [comment]
With --verbose

```
CRITICAL: Service problem 'MSExchangeIS' |
Service pattern 'MSExchangeIS': service list
```

**Comment by garnier-quentin** [comment]
I'm thinking it's not running. Or the name name is not good.

**Comment by Sims24** [comment]
Maybe you should try "Microsoft Exchange Information Store", Windows match the display name not the service name. See last answer of #416. 

Thanks !

**Comment by boogaaloo** [comment]
I'm sure is running. This is our Exchange server ;)


`./centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=xxx --snmp-community=xx --snmp-version=2c --mode=service --service=MSExchangeMailboxReplication --critical=1:`
`CRITICAL: Service problem 'MSExchangeMailboxReplication' |`

and finally 
```
`./centreon_plugins.pl --plugin=os::windows::snmp::plugin --hostname=xxx --snmp-community=xx --snmp-version=2c --mode=service --service="Microsoft Exchange Mailbox Replication" --critical=1:``
OK: All service states are ok |
```

The display name is working
Thanks to both of you !

**Comment by garnier-quentin** [comment]
You're welcome!
