### ISSUE TITLE
Special character

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#821]
Hell

I use the check_nt plugin to test a service. But a windows service contains a special character $.
I tried different possibilities ;)
`/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL$DEV`
`/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL\$DEV`
`/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL"$"DEV`
`/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l "MSSQL"$"DEV"`
`/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL$$DEV`
`/usr/lib/nagios/plugins/check_nt -H xxx 12489 -s xxx -v SERVICESTATE -l MSSQL\\\$$DEV`

In fact, the result of the command is an error.
`check_nt: Impossible de décomposer les arguments`

Would you know what is the good escape character?
Maybe there is a better plugin?

Thank you

**Comment by garnier-quentin** [comment]
Hi,

Sorry but check_nt is a plugin from "centreon-plugins". Please ask it to nscp github ;)
