### ISSUE TITLE
[apps::nsclient::restapi::plugin] SSL connect attempt failed error: SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon-plugins#822]
Hello,

I installed the new version of NSClient that comes with a Web server and a REST API. And I also installed the new version of the Centreon Plugins in which there is a plugin that allow to query the REST API to do the same things that we were doing via NRPE (I assume).

I'm using the new plugin this way:
 **perl centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname="MyIpAddress" --password="MyIpAddressPassword" --command="MyCheckCommand"**

When I'm using the new plugin to query the REST API of NSClient. I verified the configuration via the Web interface of my NSClient and it looks correct: WebServer Module enabled, SSL enabled, default port for query: 8443. But it always gives me an error about SSL:
**UNKNOWN: 500 Can't connect to "MyIpAddress":8443 (SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed)**

And in the log of NSClient it says something like that all the time: 

- ** Seems we other end is not using ssl: unknown protocol **
- ** Please review the ssl option as well as ssl options in settings. **

And I using the command the wrong way ?

**Comment by garnier-quentin** [comment]
Could you try with following option:
```
--ssl=tlvs1
```

**Comment by garnier-quentin** [comment]
Could you try with following option:
```
--ssl=tlvs1
```

**Comment by Crash-Fox** [comment]
Thanks for your reply,

I have got a new SSL error:
**UNKNOWN: 500 Can't connect to "MyIpAddress":8443 (SSL connect attempt failed)**

**Comment by garnier-quentin** [comment]
Could you give me your nsclient configuration ?

**Comment by Crash-Fox** [comment]
Here is my nsclient.ini:
[nsclient.zip](https://github.com/centreon/centreon-plugins/files/1550985/nsclient.zip)

**Comment by garnier-quentin** [comment]
I don't have the problem. Need more information:
* nsclient version
* os (centos6, centos7,...) from "centreon-plugins" is executed

**Comment by Crash-Fox** [comment]
Version of NSClient 0.5.2022
OS: Centreon 6.9

**Comment by garnier-quentin** [comment]
Have you tried with the stable release of NSClient ? (0.5.1.x)

**Comment by Crash-Fox** [comment]
No i haven't. But the API REST is not packaged with this version of NSClient ?

**Comment by garnier-quentin** [comment]
Yes it is ;)

**Comment by Crash-Fox** [comment]
Okay I will try it now

**Comment by Crash-Fox** [comment]
I doesn't work even I've installed the 0.5.1 version of NSClient. I got the same error when executing the centreon plugin:
**UNKNOWN: 500 Can't connect to "MyIpAddress":8443 (SSL connect attempt failed error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed)**

**Comment by garnier-quentin** [comment]
Do you change the certificate ?

**Comment by Crash-Fox** [comment]
no

**Comment by garnier-quentin** [comment]
you can send me an email if you want to do remote session.

**Comment by Crash-Fox** [comment]
okay

**Comment by garnier-quentin** [comment]
If we add the option 'SSL_verify_mode => SSL_VERIFY_NONE', it works. I ll add an option to add it.

**Comment by Crash-Fox** [comment]
Okay, thanks a lot.
It is normal that my installation of the Centreon Plugins and NSClient trigger thos kind of behaviour ?

**Comment by garnier-quentin** [comment]
It seems weird. Maybe the certificate is expired.

**Comment by Crash-Fox** [comment]
We talk about the certificate that is generated by NSClient during his installation ?

**Comment by garnier-quentin** [comment]
Yes maybe.

**Comment by Crash-Fox** [comment]
Again thanks for your time about my issue. I will try from the NSClient side now to try solving this mystery
