### ISSUE TITLE
[apps::nsclient::restapi::plugin]: Use of uninitialized value in sprintf

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon-plugins#825]
Hello,

When I'm executing a remote custom Powershell script from Centreon to a Windows Server (where NSClient is installed) using the new centreon plugin (NSClient REST API plugin). 

I'm getting 4 lines of this warning before seeing the output of my script:
**Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/apps/nsclient/restapi/mode/query.pm line 108.**

**Comment by garnier-quentin** [comment]
Could you give me the result with curl command ?

**Comment by Crash-Fox** [comment]
What is the URL to query to do the thing ?

**Comment by garnier-quentin** [comment]
```
curl -k -H 'password: centreon' 'https://nsclientip:8443/query/commandname?arg1&arg2'
```

**Comment by Crash-Fox** [comment]
thanks

**Comment by Crash-Fox** [comment]
Here is the result with the curl command:
**{"header":{"source_id":""},"payload":[{"command":"checkdfsreplication","lines":[{"message":"UNKNOWN - Bad DFS link"}],"result":"UNKNOWN"}]}**

**Comment by garnier-quentin** [comment]
Could you give the command you execute and the output ? because it should be in that method.

**Comment by Crash-Fox** [comment]
**curl -k -H 'password: Pa$$word' 'https://@IP:8443/query/checkDfsReplication?linkDfsName=\\\\emea.dsi.corp.sopra\\FS-DTP\\FS-TP-FORGE\\alfresco\\alf_data\\contentstore\\2017'**

**Comment by Crash-Fox** [comment]
and the output sorry:
**{"header":{"source_id":""},"payload":[{"command":"checkdfsreplication","lines":[{"message":"UNKNOWN - Bad DFS link"}],"result":"UNKNOWN"}]}**

**Comment by garnier-quentin** [comment]
I have no error. Could you get the last version (i have done a patch) and use option --debug ? After that, i need the command output.

**Comment by Crash-Fox** [comment]
Hello, i've updated my version of the centreon plugin (contaning the debug display for the nsclient plugin). I tried it : 
**./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname="NOM FQDN ou IP" --legacy-password='Mot de passe du NSClient Web Server' --ssl=tlsv1 --command="Nom commande distante" --arg="Arguments de la commande" --debug**

It keeps displaying the same outputs:
 **Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/apps/nsclient/restapi/mode/query.pm line 108.**

I tried executing others scripts that requires arguments to be passed and none of the previous outputs are to be seen. Weird

**Comment by garnier-quentin** [comment]
Yes the warning should stay. But i'd like to get the total output.

**Comment by Crash-Fox** [comment]
La commande utilisé : 
**./centreon_plugins.pl --plugin=apps::nsclient::restapi::plugin --mode=query --hostname="@IP" --legacy-password='Mot de passe' --ssl=tlsv1 --command="checkDfsReplication" --arg="arguments" --debug**

Voici la sortie de la commande :
**Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/apps/nsclient/restapi/mode/query.pm line 108.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/apps/nsclient/restapi/mode/query.pm line 108.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/apps/nsclient/restapi/mode/query.pm line 108.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/centreon-plugins/apps/nsclient/restapi/mode/query.pm line 108.
OK - DFS Replication | 'DFSR'=1.000;;;0.000;0.000**

**Comment by garnier-quentin** [comment]
You use the last version ? You're sure ? Because i should display the json from NSClient.

**Comment by Crash-Fox** [comment]
Yes i dit it this morning
