### ISSUE TITLE
protocols/jmx/custom/jolokia and jvm/mode/memorydetailed

### ISSUE THREAD

**Issue by vgaudin** [centreon/centreon-plugins#826]
I try to use memorydetailed under jolokia protocol.
I get an error using it.
Looking the code and I wonder :

why the sub manage_selection in memorydetailed is using a jmx request like :
"java.lang:type=MemoryPool,name=*

which is a search request and jolokia protocol code it use only a "READ" request hardcoded ?

so the memorydetailed is unusable using jolokia

**Comment by garnier-quentin** [comment]
The jolokia is installed on the distant jvm ? Could you give me the command and the output error please ?

**Comment by vgaudin** [comment]
yes for sure it is working correclty for mode:memory, thread, threads

[root@centreon-poller2 custom]#  perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::tomcat::jmx::plugin --custommode=jolokia --url=http://126.51.102.107:9000/jolokia --mode=memory-detailed
UNKNOWN: JMX Request: Cant get a single value.

**Comment by garnier-quentin** [comment]
Could you use following command ? Maybe mbeans are not the same.
```
perl /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=apps::protocols::jmx::plugin --url=http://126.51.102.107:9000/jolokia --mode=list-attributes
```

**Comment by vgaudin** [comment]
this comand give me a long list of valid mbeans

**Comment by vgaudin** [comment]
java.lang:name=Code Cache,type=MemoryPool

so the mbeans are java.lang:name=*,type=MemoryPool format yes.

**Comment by vgaudin** [comment]
it could not work , that's why my question.
on jolokia there is two request type :
READ : where you read a value from jolokia
SEARCH : where you can search 
on jolokia protocol in centreon plugins you only implement READ request (line 166 of jolokia.pm)

on memorydetailed.pm (line 198) you are requesting using a read command with a search syntax (with *)

so jolokia answer you a 400 and plugin in do not work for sure
and that's why my first question.

**Comment by garnier-quentin** [comment]
That's weird because it's working with tomcat and also other jvm. Have you tested it with the last version ?
