### ISSUE TITLE
Question: User right Acces on VMware

### ISSUE THREAD

**Issue by GSfr94** [centreon/centreon-plugins#828]
## Question

We want to limit as much as possible the access rights of the user configured for this plugin.
Until now we had a typical profile "Administrator" and all check worked.
However, we have created a 'read-only' profile that has more permissions to perform checks such as snapshots. (no permission)
Do you know what specific rights we should set so that the user account can have the rights to check?
***
# centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=[contenaireNAME] --mode=datastore-snapshot --datastore-name=[dataNAME]
UNKNOWN: Datastore '[dataNAME]' Not enough permissions - Snapshot sizes exceed limits |
**

**Comment by garnier-quentin** [comment]
Hi,

For that check, you need write right on datastores.

**Comment by GSfr94** [comment]
Hello,
Thank you for your reply. In fact wee only need the rights to browse datastores.
For my personal case, I configured the user incorrectly, he was present in a read-only account with this unique right and also present in another group without this right ....
Now everything is working properly. Thanks again, and especially for this great job

**Comment by garnier-quentin** [comment]
Thank you!
