### ISSUE TITLE
os::linux::snmp::plugin translate_asn_type: unhandled asn type (120)

### ISSUE THREAD

**Issue by ant0nwax** [centreon/centreon-plugins#829]
## Bug/Question

/usr/bin/perl /usr/lib64/nagios/centreon-plugins/centreon_plugins.pl --plugin os::linux::snmp::plugin --hostname SERVERA --authpassphrase XXXXXXXX --authprotocol SHA --privpassphrase XXXXXXXX --privprotocol AES --snmp-username monitoring --snmp-version 3 --mode disk-usage
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
translate_asn_type: unhandled asn type (120)
UNKNOWN: Can't construct cache...

root@SERVERA ~ # yum list installed | grep snmp
net-snmp.x86_64                     1:5.5-60.el6                        @base
net-snmp-devel.x86_64               1:5.5-60.el6                        @base
net-snmp-libs.x86_64                1:5.5-60.el6                        @base
net-snmp-perl.x86_64                1:5.5-60.el6                        @base
net-snmp-python.x86_64              1:5.5-60.el6                        @base
net-snmp-utils.x86_64               1:5.5-60.el6                        @base

on some servers it is not working (e.g. CentOS 6.9, CentOS 7.4)
on others it is working (e.g. CentOS 6.9, Debian 8.9)
I just cloned the git again to see if I update the plugins, will fix the issue
the net-snmp package is everywhere the latest, i even tried a complete yum update
still no success, so now i report a bug?
the problem is only with the disk-usage mode

Thanks for your support, Adam

**Comment by garnier-quentin** [comment]
Never see that error. Maybe an issue with your snmp configuration.

**Comment by ant0nwax** [comment]
all the other plugin modes are working :) I have also debugged 4-5 hours now, no success, i will check though the snmp config of the different machines, even same hardware and same os machines behave differently, so it must be on softwarelevel

**Comment by garnier-quentin** [comment]
Maybe it's a problem with some OIDs of a distant snmp server. You can try to walk following oid:
.1.3.6.1.4.1.2021.9.1

**Comment by ant0nwax** [comment]
Mr Garnier-Quentin

I must say I am deeply sorry for being a human who forgets things that he did once already. Your experience showed again great results: CONFIGURATION OF SNMP, maybe a classic, hope this will help other people, too. One line needs to be added on the machines where it was not working, i was fixing this already once , just 1 month ago :)


echo "includeAllDisks 10%" > /etc/snmp/snmpd.conf
service snmpd restart

THANK YOU!

**Comment by garnier-quentin** [comment]
Thanks for your feedback!
