### ISSUE TITLE
Plugins Packs Manager issue (content not visible), Centreon IMP subscription "free-trial" page not available!

### ISSUE THREAD

**Issue by fchiorascu** [centreon/centreon-plugins#830]
Hi,

We use: 
- centreon 2.8.16

We have installed:
- centreon-license-manager | 1.0.1 |
- centreon-pp-manager | 2.2.0 | 

Unfortunately the content of "Plugins Packs Manager" is not visible in our Centreon and also the URL link for Centreon IMP page is not available (below the message).
https://www.centreon.com/en/free-trial ==> 
**No Results Found
The page you requested could not be found. Try refining your search, or use the navigation above to locate the post.**

How we can have in Centreon GUI the content of the "Plugins Packs Manager"?

Kind Regards,

**Comment by Sims24** [comment]
Hi, 

You should have centreon support on IMP, this repository only concerns plugins and not centreon related product. 

Please open a case through the support link, you may have to configure a proxy to reach the webpage. 

Thanks!

**Comment by fchiorascu** [comment]
Thank you for your support.
But how to go direct to Centreon IMP topic in order to escalate this issue?

Kind Regards,

**Comment by Sims24** [comment]
@lpinsivy may you help us on this plz ?
