### ISSUE TITLE
hardware::pdu::apc::snmp::plugin --mode=outlet APC AP7920

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#831]
Hi, we got 4 same APC AP7920 and same issues
snmpwalk : [AP7920.txt](https://github.com/centreon/centreon-plugins/files/1568782/AP7920.txt)

centreon_plugins.pl --plugin=hardware::pdu::apc::snmp::plugin --hostname=1.2.3.4 --snmp-community=community --mode=outlet --verbose

Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/hardware/pdu/apc/snmp/mode/outlet.pm line 155.
OK: All outlets are ok |
Outlet 'Routeur_Secondaire' state is 'outletStatusOn' [instance: 1, bank : 0, phase : phase1, load: ]
Outlet 'APC_ATS_Alim2' state is 'outletStatusOn' [instance: 2, bank : 0, phase : phase1, load: ]
Outlet 'Outlet 3' state is 'outletStatusOn' [instance: 3, bank : 0, phase : phase1, load: ]
Outlet 'Switch_iSCSI_2' state is 'outletStatusOn' [instance: 4, bank : 0, phase : phase1, load: ]
Outlet 'BaieMD_Alim2' state is 'outletStatusOn' [instance: 5, bank : 0, phase : phase1, load: ]
Outlet 'ESXi_1_Alim2' state is 'outletStatusOn' [instance: 6, bank : 0, phase : phase1, load: ]
Outlet 'ESXi_2_Alim2' state is 'outletStatusOn' [instance: 7, bank : 0, phase : phase1, load: ]
Outlet 'ESXi_3_Alim2' state is 'outletStatusOn' [instance: 8, bank : 0, phase : phase1, load: ]

Thanks

**Comment by garnier-quentin** [comment]
Your walk is not complete. But i think you don't use the last version. Could you test with the last git version ?

**Comment by oasisck** [comment]
Indeed
I thought it was the last version with the officials repos of Centreon.

Merci pour ce super boulot ! Bonne continuation

**Comment by garnier-quentin** [comment]
Thanks for your feedback. Centreon repositories can be late ;)
