### ISSUE TITLE
Error Cannot find 'HostSuystem' object

### ISSUE THREAD

**Issue by alex8276** [centreon/centreon-plugins#832]
Hello,
I trying the plugin, I have an error that i dont understand.
With this command line : 
`./centreon_plugins.pl --plugin=apps::vmware::connector::plugin  --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=tools-vm --display-description --vm-hostname='SRV' --filter`
it's ok
But with :
`./centreon_plugins.pl --plugin=apps::vmware::connector::plugin --mode=getmap --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose`
It return the error "Cannot find 'HostSystem' object".

Do you Have  an idea of the problem? 

regards

**Comment by garnier-quentin** [comment]
Your user can read ESX information ? I only see that (if the VM check works).

**Comment by alex8276** [comment]
I create a user in read only.
I going to test with grant

**Comment by alex8276** [comment]
it's ok thanks,
I had give the right on the Vms, not on esx

**Comment by garnier-quentin** [comment]
Thanks for the feedback!

**Comment by gram1589** [comment]
Hi,
I also have this problem while I use the administrator (who has the right to everything) esx as user, does anyone have an idea
