### ISSUE TITLE
[hardware::server::dell::idrac::snmp] --mode=hardware

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#833]
Hi again,
I cannot get value from snmp IDRAC8, we got 5 of them with PowerEdge R630.
snmpwalk for [idrac8](https://github.com/centreon/centreon-plugins/files/1578673/idrac8.txt)
E.g
./centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --hostname=IDRAC8 --snmp-community=COMMUNITY--snmp-version=2c --mode=hardware --component=psu
OK: All 0 components are ok []. |

And for an IDRAC7 (PowerEdge R620), I don't have value with --mode=hardware --component=memory
snmpwalk for [idrac7](https://github.com/centreon/centreon-plugins/files/1578675/idrac7.txt)
E.g
./centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --hostname=IDRAC7 --snmp-community=COMMUNITY--snmp-version=2c --mode=hardware --component=psu
OK: All 2 components are ok [2/2 power supplies]. |
./centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --hostname=IDRAC7 --snmp-community=COMMUNITY--snmp-version=2c --mode=hardware --component=memory
OK: All 0 components are ok []. |

I used the last git version ;)
Other request, can you add component SD slot redundacy ?

Thanks

**Comment by garnier-quentin** [comment]
That's weird. Could you give full snmpwalk please ?

**Comment by oasisck** [comment]
I used snmpwalk -ObentU -v 2c -c <community> <ip> .1 > idrac8.txt

**Comment by garnier-quentin** [comment]
Sorry i didn't see walk. I have looked the snmpwalk and there is nothing about components (maybe you can update the firmware of your idrac 8).

**Comment by oasisck** [comment]
So I check version from my 4 IDRAC8 and oids .1.3.6.1.4.1.674.10892.5.4
I have 2 versions in prod : 2.30.30.30 (june 2016) and 2.02.01.01 (oct 2014)
And indeed in my version 2.30.30.30 there is no OID .1.3.6.1.4.1.674.10892.5.4.600 (700,1100,2000) but there is it in 2.02.01.01 !
So it works on IDRAC8 (2.02.01.01) but not on IDRAC8 (2.30.30.30) and obviously I tested the plugin on the newest before I open this issue :)
My admin won't update the firmware now, maybe one day

**Comment by garnier-quentin** [comment]
You can use the global status mode otherwise. I close the ticket. Thanks for the feedback.
