### ISSUE TITLE
plugin MSSQL check log file utilization

### ISSUE THREAD

**Issue by pierrick-openIT** [centreon/centreon-plugins#835]
Hy everyone,
it will be useful to add a new feature to MSSQL plugin pack, the capability to monitor log file utilization.

https://www.mytechmantra.com/LearnSQLServer/Monitoring-Transactional-Log-File-Space-Utilization-in-SQL-Server/

Have a good day.

**Comment by garnier-quentin** [comment]
I think there is a link with following PR:
https://github.com/centreon/centreon-plugins/pull/518

**Comment by pierrick-openIT** [comment]
Hy quentin,
Are you sure ? In my case I'm talking about the log file linked to a database where are stored transaction.

**Comment by garnier-quentin** [comment]
It's about logs segment.

**Comment by pierrick-openIT** [comment]
In my case it's about log storage, here is the python plugin from nagios. You have a section named "logfileusage" with an MSSQL query.


[Check_MSSQL.txt](https://github.com/centreon/centreon-plugins/files/1579730/Check_MSSQL.txt)

**Comment by cgagnaire** [comment]
Hi @pierrick-openIT,
Tell me if I'm wrong, but what you want is to retreive the result of the _DBCC SQLPERF(LOGSPACE)_ command right ?
(https://docs.microsoft.com/fr-fr/sql/t-sql/database-console-commands/dbcc-sqlperf-transact-sql)

**Comment by pierrick-openIT** [comment]
Hy Colin, yes it's look right. 
On the "old" Check_MSSQL nagios plugin, query was done on "sys.sysperfinfo" but it's look like the same PKI.

**Comment by cgagnaire** [comment]
Hi @pierrick-openIT,
Can you try to use this PR https://github.com/centreon/centreon-plugins/pull/858 on one of your MSSQL instance ?
Thanks!

**Comment by pierrick-openIT** [comment]
hy, i'll try today.

thanks.

**Comment by pierrick-openIT** [comment]
it looks good thanks! Do you want a copy of the output in private?

**Comment by cgagnaire** [comment]
Hi @pierrick-openIT,
Yes please!
Thanks for the feedback!

**Comment by pierrick-openIT** [comment]
you are welcom ;)

**Comment by Sims24** [comment]
Thanks
