### ISSUE TITLE
[apps::protocols::http::plugin] - Mode SAOP-Content Pb to use with Proxy don't support natively https requests

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#836]
Hi,
I tried to use plugin mode=soap-content with a proxy throught HTTPS.

Actually, the proxys does not accept a native HTTPS request.
The proxy need to have a POST authenticate request over HTTP before accept HTTPS SOAP.
Here are the references of the known issue:
https://stackoverflow.com/questions/27636360/squid-proxy-gives-501-on-get-request-made-by-python-but-not-curl 
https://wiki.squid-cache.org/Features/HTTPS

there is an argument in the plugin to active this possibility or is it possible to add an option to force a POST authenticate request to overcome this problem?

I use this command:
/usr/lib/centreon/plugins/centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=soap-content --hostname=www.mysite.com --proto='https' --urlpath='/url/path/of/webservice' --header='Content-Type: text/xml;charset=UTF-8' --data='/data_soap.xml' --lookup='//numeric/text()' --threshold-value='' --format-ok='' --format-warning='' --format-critical='' --warning-numeric='' --critical-numeric='' --warning-string='' --critical-string='' --service-soap='https://www.mysite.com/url/path/of/webservice' --verbose --debug --proxyurl='http://User:Password@Proxy:Port' 

I have an interrogation about the value of service-soap argument... It is really the entire URL of webservice?

thanks for your help.
regards.

**Comment by garnier-quentin** [comment]
You need to use connect for https with proxy. For that you need to install following perl module:
https://metacpan.org/release/LWP-Protocol-connect

And after you can use following option: --proxyurl='connect://User:Password@Proxy:Port'

**Comment by cmeschin** [comment]
Hi Quentin,
Happy new year :)

the authenticate is OK now, thanks. But it seems the "--data" argument is not passed to the WebService.
The response returned is "how to use the webservice" (see below)
![cif_webservice](https://user-images.githubusercontent.com/8720203/34515610-22d6e7ae-f073-11e7-8c76-306345c25d47.png)
Have you an explanation?

thanks.

**Comment by garnier-quentin** [comment]
You cannot do an authenticate call and one other call.

**Comment by cmeschin** [comment]
Sorry, authentication on the proxy is OK with new perl module.
Now, I try the authenticate on the Webservice to get the token. And then I'll use this token on another call to get information.

The file SOAP sends with "--data" argument contain user and password to authenticate for the Webservice
Can I send you over MP the real command and SOAP data file?

**Comment by garnier-quentin** [comment]
Yes you can. But you can't do what you want with that plugin.

**Comment by cmeschin** [comment]
At a minimum, I want to recover the token. This will validate the operation of the webservice.
Then if I can request Webservice with specifics research criterias, it's better.
