### ISSUE TITLE
Wazuh (OSSEC fork) plugin Intégration (REST API)

### ISSUE THREAD

**Issue by pierrick-openIT** [centreon/centreon-plugins#839]
Hi,
it could be interesting to check Wazuh health with a centreon plugin. Wazuh is OSSEC fork (IDS,SIEM security tools).
https://wazuh.com/

API Doc :
https://github.com/wazuh/wazuh-api

I can provide a fully functionnal Wazuh environnement for testing.

Regards

**Comment by garnier-quentin** [comment]
I need the curl commands and results.

**Comment by pierrick-openIT** [comment]
Hi quentin, 

Get manager status (Returns the Manager processes that are running.) :
https://documentation.wazuh.com/current/user-manual/api/reference.html#get-manager-status

Get info about agents in cluster (number of never connected / disconnected agents) :  
https://documentation.wazuh.com/current/user-manual/api/reference.html#nodes

**Comment by garnier-quentin** [comment]
Could you give me the different status for agents in cluster ? I see: "Never connected". But others ?
