### ISSUE TITLE
network::cisco::smallbusiness::sf500 en network::cisco::smallbusiness::sg300

### ISSUE THREAD

**Issue by matth-le-roy** [centreon/centreon-plugins#84]
Bonjour,

Les plugins appelé sf500 sont 100% compatible avec les sg300 que j'utilise.
Serait-il possible de nommer un plugin smallbusiness plutôt que de lui mettre sf500 comme nom?

Merci d'avance pour votre retour.

**Comment by garnier-quentin** [comment]
Thanks for the feedback. I think i'll do that.
