### ISSUE TITLE
[snmp_standard::plugin] Missing plugin.pm in the newer versions of the Centreon Plugins

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon-plugins#842]
I was using this plugin to retrieve the uptimes of hosts but when i upgraded my version of the centreon plugins. Centreon returns me an error : **Can't locate snmp_standard/plugin.pm in @INC**

So I browse the directory of the plugin and the file **plugin.pm** in **/usr/lib/nagios/plugin/centreon-plugins** was nowhere to be find.

Is it normal or not ?

**Comment by garnier-quentin** [comment]
The plugin has moved. Now: --plugin=apps/protocols/snmp/plugin.pm

**Comment by Crash-Fox** [comment]
Thanks for the info
