### ISSUE TITLE
Update for nortel::standard::snmp::plugin - VSP

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#846]
Hi,

It's possible to update or create an another version for this plugin ?

nortel::standard::snmp::plugin => Version VSP 

Best regards, 
[snmpwalk_nortel.txt](https://github.com/centreon/centreon-plugins/files/1600455/snmpwalk_nortel.txt)

**Comment by garnier-quentin** [comment]
walk is wrong.
