### ISSUE TITLE
[network::hp::procurve::plugin] - Aruba 6506R zl2 temperature sensor 'temperature.1' state is not present

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#847]
Hello!

I'm new here at github but I want to report a problem with some switches when I want to check the the environment.

I use this command:
`/usr/lib/centreon/plugins/centreon_hp_procurve.pl --plugin=network::hp::procurve::plugin --mode=environment --hostname=172.22.254.241 --snmp-version='2c' --snmp-community='public' --component=''`

and this is what I receive:
> WARNING: temperature sensor 'temperature.1' state is not present |

I'm running firmware version KB.16.04.0009 (16-Oct-2017). I have another switch, same model, same firmware, but here I get following result:
> WARNING: power supply sensor 'power supply.3' state is not present |

I have read that in an older firmware version the location of some OIDs has been changed. But this is a few months ago. I don't know exactly when these changes has been made in the firmware.
Is here the only fix to filter these sensor messages? If yes, then it's not very useful. I have tried to filter the sensor message and now I receive this message:
> OK: All 0 components are ok [].

I dont' have 0 components in my switch. Is there any solution you can provide me?

Thank you very much.
Best regards, Mike

**Comment by garnier-quentin** [comment]
Hi,

For the issue, use following option
```
--threshold-overload='sensor,OK,not present'
```

For the second, i don't know. Maybe an old firmware and you need to upgrade.

**Comment by MikeW83** [comment]
Thanks for the fast answere. I have already tried this setting, but it's not useful to get one sensor displayed as OK whenit's not present.

You know what I mean?

**Comment by garnier-quentin** [comment]
I don't understand what do you mean.

**Comment by MikeW83** [comment]
If I set the option you suggest, I receive this Message:
> OK: All 1 components are ok [1/1].

But it cannot be OK, when it's not present or not found.

I have now tested with the plugin for Aruba switches:
`/usr/lib/centreon/plugins/centreon_aruba.pl --plugin=network::aruba::standard::snmp::plugin --mode=hardware --hostname=172.22.254.241 --snmp-version='2c' --snmp-community='public'`

The result:
> OK: All 0 components are ok [].

Is it really possible that there are no sensors? I dont't think that enterprise products don't have any sensors. Maybe the plugin has to be updated to check the OIDs within the new location?!

**Comment by garnier-quentin** [comment]
Ok i understand and i can do nothinig about it. Maybe OIDs had changed and i can enhance the plugin. But i need mib fils and a full snmpwalk to look for.

**Comment by MikeW83** [comment]
Maybe I can provide you the MIBs:
https://h10145.www1.hpe.com/downloads/SoftwareReleases.aspx?ProductNumber=J9821A

If there is anyhing I can do to help please let me know. Thank you very much.

**Comment by garnier-quentin** [comment]
I need the snmpwalk also.

**Comment by MikeW83** [comment]
Normally the MIBs should be the same. But here is the link and the snmpwalk for the switch:
https://h10145.www1.hpe.com/downloads/SoftwareReleases.aspx?ProductNumber=J9850A

I have also attached the XML file from my snmpwalk.
[J9850A_5406R-zl2-switch.zip](https://github.com/centreon/centreon-plugins/files/1603022/J9850A_5406R-zl2-switch.zip)

**Comment by garnier-quentin** [comment]
Could you give me the result with the following command please ?
```
$ snmpwalk -ObentU -c public -v 2c 10.0.0.1 .1.3.6.1.4.1.11 > hp.snmpwalk
```

Thanks!

**Comment by MikeW83** [comment]
No problem! Here we go.
[hp.zip](https://github.com/centreon/centreon-plugins/files/1603476/hp.zip)

**Comment by garnier-quentin** [comment]
Could you test with the last version please ?

**Comment by MikeW83** [comment]
Good morning!

I have downloaded the new files (which are marked with "Fix #847") from the repository and copied them to my system.

This is my command:
`/usr/lib/centreon/plugins/centreon_hp_procurve.pl --plugin=network::hp::procurve::plugin --mode=environment --hostname=172.22.0.201 --snmp-version='2c' --snmp-community='public' --component=''`

And this the result:
> UNKNOWN: Can't locate object method "new" via package "network::hp::procurve::plugin" (perhaps you forgot to load "network::hp::procurve::plugin"?) at /usr/lib/centreon/plugins/centreon/plugins/script.pm line 356.

**Comment by garnier-quentin** [comment]
I have changed the path:
```
--plugin=network::hp::procurve::snmp::plugin
```

**Comment by MikeW83** [comment]
Oh, thank you. I have change the command

`/usr/lib/centreon/plugins/centreon_hp_procurve.pl --plugin=network::hp::procurve::snmp::plugin --mode=environment --hostname=172.22.0.201 --snmp-version='2c' --snmp-community='public' --component=''`

But the result is the same
> WARNING: temperature sensor 'temperature.1' state is not present |

**Comment by garnier-quentin** [comment]
Add the following option ;)
```
--threshold-overload='sensor,OK,not present'
```

**Comment by MikeW83** [comment]
Yes, looks much better.

`/usr/lib/centreon/plugins/centreon_hp_procurve.pl --plugin=network::hp::procurve::snmp::plugin --mode=environment --hostname=172.22.0.201 --snmp-version='2c' --snmp-community='public' --component='' --threshold-overload='sensor,OK,not present'`

> OK: All 9 components are ok [6/6 fans, 2/2 psu, 1/1 sensors]. |

But is this one sensor (1/1 sensors) the result of the threshold overlorad option?

**Comment by garnier-quentin** [comment]
Yes exactly

**Comment by MikeW83** [comment]
And why do I get this? Is this a false positive? So I only hav to ignore it, right?

**Comment by garnier-quentin** [comment]
You can ignore it if you prefer.

**Comment by MikeW83** [comment]
Ok, thank you. When will the fix be implemented in the repository so I get this fix through the repository on my CES?

**Comment by garnier-quentin** [comment]
It will take in one month or 2.
