### ISSUE TITLE
How to supervise oracle

### ISSUE THREAD

**Issue by alex8276** [centreon/centreon-plugins#848]
Hi everyone,
How to supervise Oracle with the plugin?
I installed sql, oraclebasic, odbc, add the environment variable in httpd.conf but when I execute the command `/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=database::oracle::plugin --hostname xxx --mode=connection-time --username xxx --password xxxx
`
I have the error : 
`UNKNOWN: install_driver(Oracle) failed: Can't locate DBD/Oracle.pm in @INC (@INC contains: /usr/lib/centreon/plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 11) line 3.
Perhaps the DBD::Oracle perl module hasn't been fully installed,
`
on my server is install in /usr/bin/perl

**Comment by garnier-quentin** [comment]
You need to install oracle instantclient and perl DBD Oracle.

**Comment by alex8276** [comment]
ok, I installed instant client, I going to see fo perl DBD oracle

**Comment by CPbN** [comment]
@garnier-quentin what about adding these dependencies into Centos Centreon repository ?
At least perl DBD Oracle module perhaps ?
Thx !

**Comment by garnier-quentin** [comment]
Because it's an license issue.
