### ISSUE TITLE
[hardware::ups::upc] sensors

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#849]
Hello,

Is it possible to display the temperature when status is OK when --verbose option is used ?

Here is the Output when status is Critical (temperature is displayed) :
CRITICAL: Sensor temperature 'Port 1 Temp 1' is 32 C | 'temp_Port 1 Temp 1'=32C;0:25;0:30;;

Here is the Output when status is OK (temperature is not displayed and the message is really geek ...) :
sensor 'Port 1 Temp 1' status is 'uioNormal' [instance = 1.1]

Thanks.

**Comment by Sims24** [comment]
Hi @ritouret , 

Could you send me a snmpwalk by mail to make some tests please with : 

snmpwalk -Cc -v 2c -c public -ObentU __IP_APC__ .1 > ups-apc.snmpwalk

Thanks

**Comment by ritouret** [comment]
Hi Sims,

I've just sent you the file by email.

Thanks.

**Comment by cgagnaire** [comment]
Added with PR https://github.com/centreon/centreon-plugins/pull/934
