### ISSUE TITLE
Manage upgrade of the plugin

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#85]
Hello,

I updated my server with the lastest release on github, sadly one module has been deleted : network::cisco::2900 and replaced by network::cisco::standard::snmp::plugin 

The fact that a module is renamed or deleted have critical impact on the system using this plugins.

Is there a way to deal with that kind of issue in the future ?

**Comment by garnier-quentin** [comment]
Yes. I know. But it's for the good. You cannot validate it before (not in production directly).

**Comment by hdep** [comment]
Sadly, I can't validate the plugin before.
Maybe the solution is to keep an "alias" to keep compatibility with old plugin name ?

**Comment by garnier-quentin** [comment]
MMm. Not a fan (i'll will be a mess. Already complex :). But you can keep some old files.
