### ISSUE TITLE
Change Network Extreme Stack check

### ISSUE THREAD

**Issue by jemaka** [centreon/centreon-plugins#850]
Hello

Change at the stack mode. 
Please add fold status as Warnung.

extremeStackingPortLinkStatus OBJECT-TYPE
             SYNTAX INTEGER {
                up (1),
                down  (2)
            }
             MAX-ACCESS read-only
             STATUS current
             DESCRIPTION
                "The Link status of the stacking port link "
                   ::= { extremeStackingPortEntry 4 }

snmpwalk:

all Links up:

nagios@host:/usr/local/nagios/libexec> snmpwalk -v 3 -a MD5 -A xxx -x DES -X xxx -u xxx -l authPriv 192.168.0.1 .1.3.6.1.4.1.1916.1.33.3.1.4
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.1257 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.1258 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.2257 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.2258 = INTEGER: 1

Link status down:

nagios@host:/usr/local/nagios/libexec> snmpwalk -v 3 -a MD5 -A xxx -x DES -X xxx -u xxx -l authPriv 192.168.0.1 .1.3.6.1.4.1.1916.1.33.3.1.4
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.1257 = INTEGER: 2
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.1258 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.2257 = INTEGER: 1
SNMPv2-SMI::enterprises.1916.1.33.3.1.4.2258 = INTEGER: 2

but  Stack Member Status up?

are these informations enough?

**Comment by Sims24** [comment]
Hi, 

What do you mean by "fold" status. You want to be able to trigger warning if some link status are down ? We can do this, but need to see if linked to the same oid instance.

Could you provide a snmpwalk of resulting of the following command : 

snmpwalk -Cc -v2c -c public -ObentU __IP_DEVICE__ .1 > extreme.snmpwalk 

Feel free to send it by mail if any sensitive informations.

Thanks,

**Comment by garnier-quentin** [comment]
I have done a patch. You can test it. it should be fixed your issue.
