### ISSUE TITLE
plugin database::oracle::plugin --mode=sql --sql-statement   timeout

### ISSUE THREAD

**Issue by jopkerrien** [centreon/centreon-plugins#851]
hi, 

I am using sql-statement to query the connected users in a application. I have timeout returned to the check. The query is not optimized i guess, it last up to 

real    1m27.748s
user    0m0.185s
sys     0m0.033s

Is there a way to modify the timeout ? Thx in advance for your help

**Comment by Sims24** [comment]
Hello, 

Unfortunately that is rather a limit of the perl DBI library ... 

If you look at the Timeout part of the following link, you will find that's a known issue with Oracle db handler : http://search.cpan.org/~timb/DBI-1.639/DBI.pm  ...
