### ISSUE TITLE
Mode to check active ports in Cisco

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#855]
Hi,

Could you please add mode to Cisco switch to get the number of active ports.
There is a OID 
ifNumber | 1.3.6.1.2.1.2.1 - total number of ports on this device
1.3.6.1.2.1.47.1.3.2.1.2 - this gives you the list of physical interfaces
Number of physical interfaces =1.3.6.1.2.1.2.1 - count of 1.3.6.1.2.1.47.1.3.2.1.2

The port operational statuses are here:
snmpwalk 1.2.3.4 -v2c -c xxx ifOp
IF-MIB::ifOperStatus.1 = INTEGER: down(2)
IF-MIB::ifOperStatus.2 = INTEGER: up(1)
IF-MIB::ifOperStatus.3 = INTEGER: unknown(4)
IF-MIB::ifOperStatus.4 = INTEGER: unknown(4)
IF-MIB::ifOperStatus.5 = INTEGER: unknown(4)
IF-MIB::ifOperStatus.6 = INTEGER: unknown(4)
IF-MIB::ifOperStatus.7 = INTEGER: unknown(4)
IF-MIB::ifOperStatus.8 = INTEGER: up(1)
IF-MIB::ifOperStatus.9 = INTEGER: up(1)
IF-MIB::ifOperStatus.10 = INTEGER: up(1)
IF-MIB::ifOperStatus.11 = INTEGER: up(1)
IF-MIB::ifOperStatus.12 = INTEGER: up(1)
IF-MIB::ifOperStatus.13 = INTEGER: up(1)
IF-MIB::ifOperStatus.14 = INTEGER: up(1)
IF-MIB::ifOperStatus.15 = INTEGER: up(1)

So the 1.3.6.1.2.1.47.1.3.2.1.2 and ifOp list should be compared and from there we get how many physical ports are up and how many are down.

**Comment by garnier-quentin** [comment]
You have an option for that:
```
--add-global
```

**Comment by kadrika** [comment]
That mode is showing all interfaces, I need only physical interfaces. As that is what we need to report to customer. Our customers want to see actively how many ports on each device is free/used.

**Comment by garnier-quentin** [comment]
You can filter on the same ifName to get only physical interfaces i think ;)

**Comment by kadrika** [comment]
I managed to find a way how to filter: '^Eth|Te|Gi|Fa'
