### ISSUE TITLE
[network::hp::procurve::plugin] Not working with Procurve 1810G - 24 GE

### ISSUE THREAD

**Issue by cpelichet** [centreon/centreon-plugins#859]
Good Morning , 

I have a question (Or bug) with the plugin network::hp::procurve::plugin . When we try to use we have this result 

For CPU : 
-----------

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::hp::procurve::plugin --mode=cpu --hostname=xxx.xxx.xxx.xxx --snmp-version='1' --snmp-community='xxx.xxx.xxx.xxx'  --warning='80' --critical='90'
UNKNOWN: SNMP GET Request : Cant get a single value.

For Memory : 
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::hp::procurve::plugin --mode=memory --hostname=xxx.xxx.xxx.xxx --snmp-version='1' --snmp-community='xxx.xxx.xxx.xxx'  --warning='80' --critical='90'

UNKNOWN: SNMP Table Request: Cant get a single value.

For Environnement : 
-----------------------

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::hp::procurve::plugin --mode=environment --hostname=xxx.xxx.xxx.xxx --snmp-version='1' --snmp-community='xxx.xxx.xxx.xxx'  --warning='80' --critical='90'

OK: All 0 components are ok []. |

For Traffic : 
---------------

/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::hp::procurve::plugin --mode=interfaces --hostname=xxx.xxx.xxx.xxx --snmp-version='1' --snmp-community='xxx.xxx.xxx.xxx'   --interface='.*' --debug

UNKNOWN: Can't construct cache...

**Comment by cgagnaire** [comment]
Hi @cpelichet,
Can you try using snmp version 2c instead of 1 ?
If no luck, can you try lauching a snmpwalk command line like below and come back with the result ?
`snmpwalk -v 2c -c <community> <ip_address> .1.3.6.1.4.1.11.2.14.11.5.1`
Thank you.

**Comment by cpelichet** [comment]
Hi , 

I use snmp version 1.

With the command i have no answer 

bash-4.1$ snmpwalk -v 1 -c YYYYYY xxx.xxx.xxx.xxx .1.3.6.1.4.1.11.2.14.11.5.1
bash-4.1$

**Comment by cgagnaire** [comment]
Thank you,
And with this command line, do you get anything at all ?
`snmpwalk -v 1 -c <community> <ip_address> .1`
Please check the configuration of your equipment : ip addresses authorized for requests, OIDs inclusions and exclusions.
For the plugin to work, you should be able to request the .1.3.6.1.4.1.11.2.14.11.5.1.* branch.

**Comment by cpelichet** [comment]
With .1 is working 

bash-4.1$ snmpwalk -v 1  -c YYYYYYYYY xxx.xxx.xxx.xxx .1
SNMPv2-MIB::sysDescr.0 = STRING:  HP ProCurve 1810G - 24 GE, P.1.17, eCos-2.0
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.11.2.3.7.11.104
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (225842800) 26 days, 3:20:28.00
SNMPv2-MIB::sysContact.0 = STRING: iXion Services SA
SNMPv2-MIB::sysName.0 = STRING: sw04
SNMPv2-MIB::sysLocation.0 = STRING:
SNMPv2-MIB::sysServices.0 = INTEGER: 2
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (225842800) 26 days, 3:20:28.00
IF-MIB::ifNumber.0 = INTEGER: 25
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifIndex.2 = INTEGER: 2
IF-MIB::ifIndex.3 = INTEGER: 3
.

**Comment by cgagnaire** [comment]
Is there any particular reason for you to use snmp version 1 ?
In the same time, can you send me the result of this command line in my mailbox _cgagnaire@centreon.com_
`snmpwalk -ObentU -Cc -v 1 -c <community> <ip_address> .1`

**Comment by sysadminasks** [comment]
We are also experiencing the exact same issue with both Procurve 1810-24G and 1810-48G. It looks like the OIDs are outdated that is why it is giving bad outputs? Or do I need to load the mib files locally?

**Comment by garnier-quentin** [comment]
Do you still have the issue ?

**Comment by garnier-quentin** [comment]
You can open it if you still have the issue. It should work for that version (aruba 1800).
