### ISSUE TITLE
[Cisco::standard::qosusage] Percentage Threshold (Drop)

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-plugins#861]
Hi,

Can you add the option of setting percentage thresholds instead of 'b/s'? (For drops)

Link: https://github.com/centreon/centreon-plugins/blob/master/centreon/common/cisco/standard/snmp/mode/qosusage.pm

Regards.

**Comment by jben94** [comment]
Hi,
We would like to have for example, a tolerance of 5% drop on our line.
We would not want to make case by case, compared to the setting of the QOS.
As you do for the traffic part.

**Comment by fmattesct** [comment]
Hi,
Thanks for your interest in Centreon.
Requests for new features and enhancements must be suggested [here](https://thewatch.centreon.com/ideas).
Troubleshooting and questions must now be asked [here](https://thewatch.centreon.com/data-collection-6) (cf our [new issue template](https://github.com/centreon/centreon-plugins/blob/develop/.github/issue_template.md).

Thank you for your understanding.
