### ISSUE TITLE
[hardware::server::hp::ilo::xmlapi::plugin] Pb ssl for ILO3

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#865]
Hi,

I have a problem with this plugin _hardware::server::hp::ilo::xmlapi::plugin_.
In CLI, everything works. 

` perl centreon_plugins.pl --plugin= hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname=x.x.x.x --username=user --password=1234 --ssl-opt="SSL_version=SSL_VERIFY_NONE" --ssl-opt="SSL_version='TLSv1'"`
Besides in CLI, it also works with/without the options 
--ssl-opt="SSL_version=SSL_VERIFY_NONE" 
--ssl-opt="SSL_version='TLSv1'" 
--ssl-opt="SSL_version=SSLv3" 
:)

`OK: All 46 components are ok [6/6 fans, 8/8 pdrive, 2/2 psu, 30/30 temperatures]. | 'fan_Fan 1'=13%;;;0; 'fan_Fan 2'=13%;;;0; 'fan_Fan 3'=13%;;;0; 'fan_Fan 4'=13%;;;0; 'fan_Fan 5'=0%;;;0; 'fan_Fan 6'=0%;;;0; 'temp_Temp 1'=21C;;;; 'temp_Temp 2'=40C;;;; 'temp_Temp 4'=33C;;;; 'temp_Temp 5'=32C;;;; 'temp_Temp 8'=41C;;;; 'temp_Temp 9'=36C;;;; 'temp_Temp 10'=39C;;;; 'temp_Temp 11'=32C;;;; 'temp_Temp 12'=46C;;;; 'temp_Temp 19'=24C;;;; 'temp_Temp 20'=31C;;;; 'temp_Temp 21'=33C;;;; 'temp_Temp 22'=31C;;;; 'temp_Temp 23'=39C;;;; 'temp_Temp 24'=35C;;;; 'temp_Temp 25'=32C;;;; 'temp_Temp 26'=33C;;;; 'temp_Temp 29'=40C;;;; 'temp_Temp 30'=60C;;;;`

Via Centreon, I get this :

`UNKNOWN: Failed to establish SSL connection: Argument invalide, ssl_error=IO::Socket::INET6 configuration failederror:00000000:lib(0):func(0):reason(0)`

A little help would be welcome ;)
Thank you

**Comment by cgagnaire** [comment]
Hi @boogaaloo,
Can you send us the 'Executed Check Command Line' present in the detailed page of the service.
Thank you!

**Comment by boogaaloo** [comment]
`/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::hp::ilo::xmlapi::plugin --mode=hardware --hostname=xxx --username=xxx --password=*** --ssl-opt="SSL_version=SSL_VERIFY_NONE" --ssl-opt="SSL_version='TLSv1'"`

**Comment by Sims24** [comment]
@boogaaloo no reason something differs between Centreon and command line on this part. Please ensure you have all required dependencies on poller which monitor this host

**Comment by boogaaloo** [comment]
Hey,

We have all required dependencies. 
If you need more information, I'm at your disposal.

Thanks

**Comment by omercier** [comment]
How did you run it in the command-line? Was it as centreon-engine or as root?

**Comment by Sims24** [comment]
Timeout here, probably mismatch between poller checking the host in Centreon and server where command_line was executed.
