### ISSUE TITLE
[hardware::server::dell::idrac::snmp::plugin] Output display - CLI/GUI

### ISSUE THREAD

**Issue by boogaaloo** [centreon/centreon-plugins#866]
Hi,

I have the impression that there is a problem of output display on this plugin. Indeed, the output is not the same in CLI or GUI.
**In CLI**

`perl centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=hardware --hostname=xxxx --snmp-version=2 --snmp-community=xxxx --component='coolingdevice'`

`OK: All 6 components are ok [6/6 cooling devices]. | 'fan_System Board Fan1'=14040rpm;0:;60:;; 'fan_System Board Fan2'=13920rpm;0:;60:;; 'fan_System Board Fan3'=14160rpm;0:;60:;; 'fan_System Board Fan4'=14280rpm;0:;60:;; 'fan_System Board Fan5'=14280rpm;0:;60:;; 'fan_System Board Fan6'=14280rpm;0:;60:;;`

**In GUI** - I've only that -->

`OK: All 0 components are ok [].`

Thanks for your help !

**Comment by cgagnaire** [comment]
Hi @boogaaloo,
Can you send us the 'Executed Check Command Line' present in the detailed page of the service.
Thank you!

**Comment by boogaaloo** [comment]
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=hardware --component=amperage --hostname=xxx --snmp-version=2 --snmp-community=xxxx

**Comment by cgagnaire** [comment]
Can you try to launch this command using the centreon-engine user like :
```
# su - centreon-engine
# /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=hardware::server::dell::idrac::snmp::plugin --mode=hardware --component=amperage --hostname=xxx --snmp-version=2 --snmp-community=xxxx
```

**Comment by boogaaloo** [comment]
I get this :
`OK: All 0 components are ok []. |`

**Comment by boogaaloo** [comment]
I get this :

`OK: All 3 components are ok [3/3 amperages]. | 'amperage_PS1 Current 1'=0.6A;0:;0:;; 'amperage_PS2 Current 2'=0.6A;0:;0:;; 'amperage_System Board Pwr Consumption'=0.294W;0:0.896;0:0.98;;`

**Comment by boogaaloo** [comment]
I think I found.
In fact, the 'Executed Check Command Line' takes the host name and it doesn't work. 
If I put the ip address twice, that is, the first time on the (host) "name" field and a second time on the ip address field, the command works.
I hope to have been clear... :)

**Comment by Sims24** [comment]
Ok thanks for the self-troubleshooting, dns issue i guess
