### ISSUE TITLE
[storage::hp::3par::7000::plugin] - always ask for password

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#868]
We configured for user centreon-engine a ssh certificate authentication with the 3par. If I try from command line
```
-bash-4.1$ ssh -l 3paradm 192.168.150.14 shownode -s
Node -State- -Detailed_State-
   0 OK      OK
   1 OK      OK
```
everythings is working without password request.

If I try the same with the centreon plugins then the call hangs:
```
-bash-4.1$ ./centreon_plugins.pl --plugin=storage::hp::3par::7000::plugin --mode=node --hostname=192.168.150.14 --ssh-option='-l 3paradm'
 3paradm@192.168.150.14's password:
UNKNOWN: Command too long to execute (timeout)... |
```
Anyone knows whats the problem?

**Comment by cgagnaire** [comment]
Hi @boogaaloo,
Can you send us the 'Executed Check Command Line' present in the detailed page of the service.
Thank you!

**Comment by joschi99** [comment]
Additional info

the same command executed from centreon will result in the error:
```
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=storage::hp::3par::7000::plugin --hostname=192.168.150.14 --ssh-option='-l 3paradm' --mode=node

UNKNOWN: Command error: Permission denied, please try again. - Permission denied, please try again. - Permission denied (publickey,password).
```
![2018-01-26 13_59_19-centreon - it network monitoring](https://user-images.githubusercontent.com/6400595/35440780-2dd8a4fe-02a1-11e8-9e26-c351786b59f8.png)

**Comment by Sims24** [comment]
Hello, 

Do you try your command-line from the poller which is monitoring this host or from the central server ?

**Comment by joschi99** [comment]
yes

**Comment by Sims24** [comment]
You should set ssh-option with a "=" sign. Please test with --ssh-option="-l=3paradm" otherwise parsing of ssh options won't be correct

**Comment by joschi99** [comment]
Thanks, it was my mistake.
