### ISSUE TITLE
Checkpoint monitoring hardware on dell R610

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#87]
Hello,

it appears that the plugin is not working for Dell servers here is the output : 
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::checkpoint::plugin --mode=hardware --hostname=192.168.1.3 --snmp-version=3 --snmp-username=vialinkro --authpassphrase=**** --authprotocol=MD5 --privpassphrase=****** --privprotocol=DES

Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/voltage.pm line 82.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
Argument "" isn't numeric in sprintf at /usr/lib/nagios/plugins/centreon-plugins/network/checkpoint/mode/components/temperature.pm line 83.
CRITICAL: Voltage '÷' sensor out of range status is 'true' - Voltage '÷' sensor out of range status is 'true' - Voltage 'Voltage 1' sensor out of range status is 'true' - Voltage 'Voltage 2' sensor out of range status is 'true' - Fan 'FAN MOD 1A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 2A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 3A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 4A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 5A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 6A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 1B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 2B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 3B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 4B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 5B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 6B RPM' sensor out of range status is 'true' - Fan ':' sensor out of range status is 'true' - Temperature 'Temp' sensor out of range status is 'reading error' - Temperature 'Temp' sensor out of range status is 'reading error' - Temperature 'Temp' sensor out of range status is 'reading error' - Temperature 'Ambient Temp' sensor out of range status is 'reading error' - Temperature 'Temp' sensor out of range status is 'reading error' - Temperature 'Ambient Temp' sensor out of range status is 'reading error' - Temperature 'Ambient Temp' sensor out of range status is 'true' - Temperature 'Planar Temp' sensor out of range status is 'reading error' - Temperature '÷' sensor out of range status is 'reading error' - Temperature 'Temp' sensor out of range status is 'reading error' - Temperature 'Temp' sensor out of range status is 'reading error' - Temperature 'Temp' sensor out of range status is 'reading error' | '÷'=0.00V;;;; '÷'=0.00V;;;; 'Voltage 1'=230.00V;;;; 'Voltage 2'=0.00V;;;; 'FAN MOD 1A RPM'=4920rpm;;;; 'FAN MOD 2A RPM'=4800rpm;;;; 'FAN MOD 3A RPM'=4920rpm;;;; 'FAN MOD 4A RPM'=4920rpm;;;; 'FAN MOD 5A RPM'=5160rpm;;;; 'FAN MOD 6A RPM'=5160rpm;;;; 'FAN MOD 1B RPM'=3840rpm;;;; 'FAN MOD 2B RPM'=3840rpm;;;; 'FAN MOD 3B RPM'=3960rpm;;;; 'FAN MOD 4B RPM'=3840rpm;;;; 'FAN MOD 5B RPM'=3840rpm;;;; 'FAN MOD 6B RPM'=3480rpm;;;; ':'=0rpm;;;; 'Temp'=0.00C;;;; 'Temp'=0.00C;;;; 'Temp'=0.00C;;;; 'Ambient Temp'=0.00C;;;; 'Temp'=0.00C;;;; 'Ambient Temp'=0.00C;;;; 'Ambient Temp'=26.00C;;;; 'Planar Temp'=0.00C;;;; '÷'=0.00C;;;; 'Temp'=0.00C;;;; 'Temp'=0.00C;;;; 'Temp'=0.00C;;;;

**Comment by garnier-quentin** [comment]
Could you give me a snmp walk of your equipment please ? It's a checkpoint ?

**Comment by garnier-quentin** [comment]
Could you provide me the snmpwalk of your checkpoint ? Following oids:
.1.3.6.1.4.1.2620.1.6.7.8.2.1
.1.3.6.1.4.1.2620.1.6.7.9.1.1
.1.3.6.1.4.1.2620.1.6.7.8.1.1
.1.3.6.1.4.1.2620.1.6.7.8.3.1

Thanks.

**Comment by hdep** [comment]
Hello,

here is the output : 
.1.3.6.1.4.1.2620.1.6.7.8.2.1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.2.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.3.0 = INTEGER: 3
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.4.0 = INTEGER: 4
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.5.0 = INTEGER: 5
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.6.0 = INTEGER: 6
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.7.0 = INTEGER: 7
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.8.0 = INTEGER: 8
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.9.0 = INTEGER: 9
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.10.0 = INTEGER: 10
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.11.0 = INTEGER: 11
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.12.0 = INTEGER: 12
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.1.13.0 = INTEGER: 13
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.1.0 = STRING: "FAN MOD 1A RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.2.0 = STRING: "FAN MOD 2A RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.3.0 = STRING: "FAN MOD 3A RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.4.0 = STRING: "FAN MOD 4A RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.5.0 = STRING: "FAN MOD 5A RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.6.0 = STRING: "FAN MOD 6A RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.7.0 = STRING: "FAN MOD 1B RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.8.0 = STRING: "FAN MOD 2B RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.9.0 = STRING: "FAN MOD 3B RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.10.0 = STRING: "FAN MOD 4B RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.11.0 = STRING: "FAN MOD 5B RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.12.0 = STRING: "FAN MOD 6B RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.2.13.0 = Hex-STRING: 3A 19
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.1.0 = STRING: "5280"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.2.0 = STRING: "5160"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.3.0 = STRING: "5160"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.4.0 = STRING: "5160"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.5.0 = STRING: "5040"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.6.0 = STRING: "5040"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.7.0 = STRING: "3600"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.8.0 = STRING: "3600"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.9.0 = STRING: "3600"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.10.0 = STRING: "3480"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.11.0 = STRING: "3600"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.12.0 = STRING: "3960"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.3.13.0 = STRING: "0"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.1.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.2.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.3.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.4.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.5.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.6.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.7.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.8.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.9.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.10.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.11.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.12.0 = STRING: "RPM"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.4.13.0 = STRING: "unspecified"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.1.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.2.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.3.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.4.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.5.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.6.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.7.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.8.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.9.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.10.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.11.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.12.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.5.13.0 = STRING: "Fan"
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.2.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.3.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.4.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.5.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.6.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.7.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.8.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.9.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.10.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.11.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.12.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.2.1.6.13.0 = INTEGER: 1


.1.3.6.1.4.1.2620.1.6.7.9.1.1
SNMPv2-SMI::enterprises.2620.1.6.7.9.1.1 = No Such Instance currently exists at this OID


.1.3.6.1.4.1.2620.1.6.7.8.1.1
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.2.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.3.0 = INTEGER: 3
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.4.0 = INTEGER: 4
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.5.0 = INTEGER: 5
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.6.0 = INTEGER: 6
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.7.0 = INTEGER: 7
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.8.0 = INTEGER: 8
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.9.0 = INTEGER: 9
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.10.0 = INTEGER: 10
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.11.0 = INTEGER: 11
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.1.12.0 = INTEGER: 12
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.1.0 = STRING: "Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.2.0 = STRING: "Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.3.0 = STRING: "Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.4.0 = STRING: "Ambient Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.5.0 = STRING: "Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.6.0 = STRING: "Ambient Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.7.0 = STRING: "Ambient Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.8.0 = STRING: "Planar Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.9.0 = Hex-STRING: F7
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.10.0 = STRING: "Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.11.0 = STRING: "Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.2.12.0 = STRING: "Temp"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.1.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.2.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.3.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.4.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.5.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.6.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.7.0 = STRING: "25"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.8.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.9.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.10.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.11.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.3.12.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.1.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.2.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.3.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.4.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.5.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.6.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.7.0 = STRING: "degrees C"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.8.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.9.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.10.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.11.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.4.12.0 = ""
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.1.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.2.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.3.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.4.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.5.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.6.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.7.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.8.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.9.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.10.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.11.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.5.12.0 = STRING: "Temperature"
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.1.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.2.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.3.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.4.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.5.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.6.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.7.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.8.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.9.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.10.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.11.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.1.1.6.12.0 = INTEGER: 2


.1.3.6.1.4.1.2620.1.6.7.8.3.1
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.1.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.1.2.0 = INTEGER: 2
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.1.3.0 = INTEGER: 3
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.1.4.0 = INTEGER: 4
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.2.1.0 = Hex-STRING: F7 19
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.2.2.0 = Hex-STRING: F7 19
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.2.3.0 = STRING: "Voltage"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.2.4.0 = STRING: "Voltage"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.3.1.0 = STRING: "0"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.3.2.0 = STRING: "0"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.3.3.0 = STRING: "228"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.3.4.0 = STRING: "230"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.4.1.0 = STRING: "unspecified"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.4.2.0 = STRING: "unspecified"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.4.3.0 = STRING: "Volts"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.4.4.0 = STRING: "Volts"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.5.1.0 = STRING: "Voltage"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.5.2.0 = STRING: "Voltage"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.5.3.0 = STRING: "Voltage"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.5.4.0 = STRING: "Voltage"
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.6.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.6.2.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.6.3.0 = INTEGER: 1
SNMPv2-SMI::enterprises.2620.1.6.7.8.3.1.6.4.0 = INTEGER: 1

**Comment by garnier-quentin** [comment]
Could you test with the last version ? Should be better and add following option:
--threshold-overload='temperature,OK,reading error'

Moreover, it's weird. Your equipment send '1' in the status. '1' means a problem. Should be '0'. You can change the status effect with --threshold-overload option.

**Comment by hdep** [comment]
the output now is :
OK: All 0 components are ok []. |

this mean there is not compnonents detected that is right ?

**Comment by garnier-quentin** [comment]
My bad :) Could you test it ?

**Comment by hdep** [comment]
Now the ouput is critical : 

CRITICAL: Voltage 'Voltage/3.0' sensor out of range status is 'true' - Voltage 'Voltage/4.0' sensor out of range status is 'true' - Fan 'FAN MOD 1A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 2A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 3A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 4A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 5A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 6A RPM' sensor out of range status is 'true' - Fan 'FAN MOD 1B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 2B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 3B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 4B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 5B RPM' sensor out of range status is 'true' - Fan 'FAN MOD 6B RPM' sensor out of range status is 'true' - Temperature 'Ambient Temp/7.0' sensor out of range status is 'true' | 'volt_Voltage_3.0'=228.00V;;;; 'volt_Voltage_4.0'=230.00V;;;; 'FAN MOD 1A RPM'=5040rpm;;;; 'FAN MOD 2A RPM'=4920rpm;;;; 'FAN MOD 3A RPM'=4920rpm;;;; 'FAN MOD 4A RPM'=4920rpm;;;; 'FAN MOD 5A RPM'=4800rpm;;;; 'FAN MOD 6A RPM'=4800rpm;;;; 'FAN MOD 1B RPM'=3480rpm;;;; 'FAN MOD 2B RPM'=3480rpm;;;; 'FAN MOD 3B RPM'=3360rpm;;;; 'FAN MOD 4B RPM'=3360rpm;;;; 'FAN MOD 5B RPM'=3480rpm;;;; 'FAN MOD 6B RPM'=3720rpm;;;; 'temp_Ambient Temp_7.0'=25.00C;;;;

I don't really understand : "out of range" and the perf data seems to be fine.

**Comment by garnier-quentin** [comment]
It's what i have explained. Your equipment gives wrong status. It should be 'false' and not 'true'.

**Comment by hdep** [comment]
I tried to play with the --threshold-overload='temperature,OK,reading error' But I'm not sure to understand how this works. I still get : 
Temperature 'Temp/11.0' sensor out of range status is 'reading error' - 
Temperature 'Temp/12.0' sensor out of range status is 'reading error' 

in the output. So this mean the option is not matching ?

**Comment by garnier-quentin** [comment]
Can you give me your command line please ? It should work.

**Comment by hdep** [comment]
Here is the command line : 

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::checkpoint::plugin  --mode=hardware --hostname=192.168.1.2  --snmp-version=3  --snmp-username=user --authpassphrase=***** --authprotocol=MD5 --privpassphrase=**** --privprotocol=DES --threshold-overload='Temperature,OK,reading error'

**Comment by garnier-quentin** [comment]
It's a small 't' ;) --threshold-overload='temperature,OK,reading error'

**Comment by hdep** [comment]
Ok, my bad, now I use the following command : 

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::checkpoint::plugin  --mode=hardware --hostname=192.168.1.2  --snmp-version=3  --snmp-username=user--authpassphrase=*** --authprotocol=MD5 --privpassphrase=*** --privprotocol=DES --threshold-overload='temperature,OK,reading error' --threshold-overload='fan,OK,true' --threshold-overload='voltage,OK,true' --threshold-overload='Temperature,OK,true'

but output still report error about : 

CRITICAL: Temperature 'Ambient Temp/7.0' sensor out of range status is 'true' 

This is why I tried also 'Temperature' but there is not match.

any idea ?

**Comment by garnier-quentin** [comment]
The good way: --threshold-overload='temperature,OK,reading error' --threshold-overload='fan,OK,true' --threshold-overload='voltage,OK,true' --threshold-overload='temperature,OK,true'

**Comment by hdep** [comment]
Ok it works now thank you. 

I'll check with checkpoint if there is an explanation for the status code to 1.

**Comment by garnier-quentin** [comment]
Interesting to have the response from checkpoint. You can put it here ;)
