### ISSUE TITLE
[network::f5::bigip::snmp::plugin] Trunk

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#872]
Hello,

Would you add a mode to have traffic stats for F5 Bigip Trunks ?

Here is snmpwalk for 1.3.6.1.4.1.3375.2.1.2.12.2 branch with names :
F5-BIGIP-SYSTEM-MIB::sysTrunkStatResetStats.0 = INTEGER: 0
F5-BIGIP-SYSTEM-MIB::sysTrunkStatNumber.0 = INTEGER: 1
F5-BIGIP-SYSTEM-MIB::sysTrunkStatName."RETH" = STRING: RETH
F5-BIGIP-SYSTEM-MIB::sysTrunkStatPktsIn."RETH" = Counter64: 76104389
F5-BIGIP-SYSTEM-MIB::sysTrunkStatBytesIn."RETH" = Counter64: 11753023170
F5-BIGIP-SYSTEM-MIB::sysTrunkStatPktsOut."RETH" = Counter64: 37746839
F5-BIGIP-SYSTEM-MIB::sysTrunkStatBytesOut."RETH" = Counter64: 8357466333
F5-BIGIP-SYSTEM-MIB::sysTrunkStatMcastIn."RETH" = Counter64: 2190349
F5-BIGIP-SYSTEM-MIB::sysTrunkStatMcastOut."RETH" = Counter64: 42412
F5-BIGIP-SYSTEM-MIB::sysTrunkStatErrorsIn."RETH" = Counter64: 0
F5-BIGIP-SYSTEM-MIB::sysTrunkStatErrorsOut."RETH" = Counter64: 0
F5-BIGIP-SYSTEM-MIB::sysTrunkStatDropsIn."RETH" = Counter64: 0
F5-BIGIP-SYSTEM-MIB::sysTrunkStatDropsOut."RETH" = Counter64: 0
F5-BIGIP-SYSTEM-MIB::sysTrunkStatCollisions."RETH" = Counter64: 0

And here with oid (-Cc -ObentU) :
.1.3.6.1.4.1.3375.2.1.2.12.2.1.0 = INTEGER: 0
.1.3.6.1.4.1.3375.2.1.2.12.2.2.0 = INTEGER: 1
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.1.4.82.69.84.72 = STRING: "RETH"
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.2.4.82.69.84.72 = Counter64: 76132417
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.3.4.82.69.84.72 = Counter64: 11756542902
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.4.4.82.69.84.72 = Counter64: 37760098
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.5.4.82.69.84.72 = Counter64: 8360342256
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.6.4.82.69.84.72 = Counter64: 2191110
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.7.4.82.69.84.72 = Counter64: 42426
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.8.4.82.69.84.72 = Counter64: 0
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.9.4.82.69.84.72 = Counter64: 0
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.10.4.82.69.84.72 = Counter64: 0
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.11.4.82.69.84.72 = Counter64: 0
.1.3.6.1.4.1.3375.2.1.2.12.2.3.1.12.4.82.69.84.72 = Counter64: 0

Thanks.

**Comment by Sims24** [comment]
Hello, 

yes we can, we're missing some time at the moment ;)

**Comment by cgagnaire** [comment]
Added with https://github.com/centreon/centreon-plugins/pull/931
