### ISSUE TITLE
Centreon trendmicro iwsva - Disk Global  - Status Unknown

### ISSUE THREAD

**Issue by boupjof** [centreon/centreon-plugins#873]
Not really an issue, juste a little fix.

I manage to install and configure centreon_trendmicro_iwsva today, after some snmp tweak all my check are working except one.
By default Disk Global template genrate command like "/usr/lib/centreon/plugins/centreon_trendmicro_iwsva.pl --plugin=os::linux::snmp::plugin --mode=storage --hostname=IPADRESS --snmp-version='2c' --snmp-community='public' --snmp-timeout=10 --storage='.*' --name --regexp --display-transform-src='' --display-transform-dst='' --warning='80' --critical='90' --verbose"

I have "Unknown option: warning at /usr/lib/centreon/plugins/centreon_trendmicro_iwsva.pl line 142."  response.

If I edit manualy the command to remove critical and warning parameter, it's working like a charm. Maybe it's possible to change that on the repository ?

**Comment by Sims24** [comment]
Hi, 

Thanks for your feedback, yes this is rather a template issue. 

I guess that if you are using warning-usage instead of warning it should work and you'll be able to set threshold. We will doublecheck on centreon template repository. 

Thanks
