### ISSUE TITLE
[Meta-Service] use metric name defined in Meta-Service configuration [apps::centreon::local::plugin]

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon-plugins#874]
The apps::centreon::local::plugin plugin with metaservice mode only display 'value' as the name of the calculated metrics:

`$self->{output}->perfdata_add(label => (defined($DSTYPE{$row->{data_source_type}}) ? $DSTYPE{$row->{data_source_type}} : 'g') . '[value]',`

Could be changed by:

`$self->{output}->perfdata_add(label => (defined($DSTYPE{$row->{data_source_type}}) ? $DSTYPE{$row->{data_source_type}} : 'g') . '['.$row->{metric}.']', `

**Comment by Sims24** [comment]
Hello @lpinsivy 

Thanks ! 

@cgagnaire may you fix and commit this as proposed by Laurent ?
