### ISSUE TITLE
[Linux plugin pack] filtrage perfdata sur mode tcpcon

### ISSUE THREAD

**Issue by davidcolin** [centreon/centreon-plugins#875]
bonjour, 

Je souhaiterais savoir si vous pouvez envisager une évolution de ce mode du pp linux (ou une évolution générale du filtrage des perfdata des PP) pour répondre au besoin formulé dans le ticket #HEM-479-27047 ouvert auprès du support? 

Merci par avance
Cdlt, 
David

**Comment by Sims24** [comment]
Hello David, 

We will try but we miss some time for now. 

Thanks

**Comment by garnier-quentin** [comment]
Ticket not related to centreon-plugins directly.
