### ISSUE TITLE
Check process with centreon_linux_snmp.pl char limitation issue

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#877]
Hi, 

I encountered an issue with the plugin centreon_linux_snmp.pl to check linux processes with args. 
The number of chars allowed in arguments seems to be limited to 128 chars.

**# To reproduce the issue i use this command :**  

**Working command :** 
./centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=MyHost --snmp-version=2c --snmp-community=PUBLIC --process-name=java --regexp-name --regexp-path --regexp-args --process-args='-X5fgesq -Dappdynamics.http.proxyHost=Myproxy -Dappdynamics.http.proxyPort=8080 -Dappdynamics.controller.hostName=editi' --critical=1:

_**OK: Number of current processes running: 1 | 'nbproc'=1;;1:;0;**_

**Add 1 char to args to have critical :** 
./centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=processcount --hostname=MyHost --snmp-version=2c --snmp-community=PUBLIC --process-name=java --regexp-name --regexp-path --regexp-args --process-args='-X5fgesq -Dappdynamics.http.proxyHost=Myproxy -Dappdynamics.http.proxyPort=8080 -Dappdynamics.controller.hostName=editi**o**' --critical=1:

**_CRITICAL: Number of current processes running: 0 | 'nbproc'=0;;1:;0;_**

Is there any way to increase the number of chars that are checked ?
Thank you

**Comment by Sims24** [comment]
This is a SNMP limitation. We cannot do anything about it. 

    args => '.1.3.6.1.2.1.25.4.2.1.5', # hrSWRunParameters (Warning: it's truncated. (128 characters))

Thanks
