### ISSUE TITLE
os::linux::snmp::plugin request --nagvis-perfdata option for mode diskio

### ISSUE THREAD

**Issue by ant0nwax** [centreon/centreon-plugins#878]
Hi Quentin

could you please add a --nagivs-perfdata option to the subject plugin diskio mode,
that behaves same like the --nagvis-perfdata option at interface mode?

Thanks Anton

PS, this is good to be compatible with icinga perfdata, too

**Comment by Sims24** [comment]
Hi, 

This is not as simple as for interfaces as we use some abstraction class to manage perfdata on this one. We'll think about it but not in a near future I guess.

Thanks for using it

**Comment by ant0nwax** [comment]
Hi Sims24,
Thanks for your fast answer

For now i solved the issue of icinga not "understanding" the perf data:
I changed 10 strings in diskio.pm
5 x 'iops' to ''
5 x 'B/s' to ''
Now icinga is eating the perfdata and forwarding to InfluxDB and further to Grafana

Thanks for this centreon-plugin suite, its a great and powerful collection with nearly no limits.

Best regards, Anton

**Comment by Sims24** [comment]
Glad to know you it works with this. 

Thanks always appreciate to have such feedbacks =)
