### ISSUE TITLE
Problème de Supervision Windows Server 2012 R2

### ISSUE THREAD

**Issue by quentincaron** [centreon/centreon-plugins#879]
Bonjour,

J'ai actuellement un problème pour superviser un serveur sous Windows Server 2012 R2. Le serveur est configuré pour répondre à mon serveur et pourtant il ne répond pas au demande pour savoir si un service est en marche.

Exemple de commande auquel il répond : /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=IP --snmp-version=2c --snmp-community=communaute --verbose --regexp --display-transform-src='\''(..).*'\'' --display-transform-dst='\''$1'\'' --name --storage='\''C:'\'' --warning=90 --critical=95'
Avec cette commande le serveur me répond bien : OK: Storage 'C:' Total: 149.45 GB Used: 100.77 GB (67.43%) Free: 48.68 GB (32.57%)

Par contre avec la commande suivante : /usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=IP --snmp-version=2c --snmp-community=communaute --service='Netlogon' --regexp --verbose --state=active --critical=1:
Je me retrouve avec la reponse suivante : UNKNOWN: SNMP Table Request : (genError) A general failure occured

Dans le même temps, j'ai un deuxième serveur Windows en cluster avec le premier avec la même configuration SNMP qui lui répond à toutes les commandes.

Savez-vous d'où peut venir le problème ?

Quentin.

**Comment by Sims24** [comment]
Bonjour, 

Pouvez-vous essayer d'ajouter l'option suivante à la commande et nous dire si cela marche mieux ? 

--snmp-force-getnext

**Comment by quentincaron** [comment]
Bonjour, 

Merci pour votre réponse mais malgré l'option, j'ai la même erreur : 
/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=$IP --snmp-version=2c --snmp-community=$communaute --snmp-force-getnext --service='Netlogon' --regexp --verbose  --state=active --critical=1:

UNKNOWN: SNMP Table Request : (genError) A general failure occured

**Comment by pkriko** [comment]
Bonjour,

Qu'est-ce que donne la commande : 
snmpwalk -v 2c -c $community $ip .1.3.6.1.4.1.77.1.2.3.1 | grep -i netlogon

**Comment by quentincaron** [comment]
Bonjour,

Pour un serveur qui fonctionne bien, j'ai ce résultat :
[root@LBS-CENTREONCENTRAL plugins]# snmpwalk -v 2c -c $community $IP .1.3.6.1.4.1.77.1.2.3.1 | grep -i netlogon
SNMPv2-SMI::enterprises.77.1.2.3.1.1.8.78.101.116.108.111.103.111.110 = STRING: "Netlogon"

Pour celui qui m'embête depuis le début, j'ai celui ci :
[root@LBS-CENTREONCENTRAL plugins]# snmpwalk -v 2c -c $community $IP .1.3.6.1.4.1.77.1.2.3.1 | grep -i netlogon
SNMPv2-SMI::enterprises.77.1.2.3.1.1.8.78.101.116.108.111.103.111.110 = STRING: "Netlogon"
Error in packet.
Reason: (genError) A general failure occured
Failed object: SNMPv2-SMI::enterprises.77.1.2.3.1.5.89.65.100.109.105.110.105.115.116.114.97.116.105.111.110.32.100.101.115.32.99.111.110.110.101.120.105.111.110.115.32.97.117.120.32.112.114.111.103.114.97.109.109.101.115.32.82.101.109.111.116.101.65.112.112.32.101.116.32.97.117.120.32.115.101.114.118.105.99.101.115.32.66.117.114.101.97.117.32.195.160.32.100.105.115.116.97.110.99.101

**Comment by boisrobe** [comment]
J'ai le même problème que vous, le pluguin et la commande snmpwalk renvoie une general failure occured.
La différence entre mes serveurs : la commande fonctionne sur 2008R2, 2012R2, 2016.
Mais sur mes deux 2012R2 contrôleur de domaine j'ai le soucis.

C'est un cluster de quel service que vous avez monté ?

**Comment by quentincaron** [comment]
J'ai le problème sur un serveur 2012R2 en standalone. Il ne s'agit même pas d'un cluster d'un service en particulier. 
Il n'a pas non plus de service contrôleur de domaine.

**Comment by Sims24** [comment]
hey @quentincaron and @boisrobe 

Maybe following options could do the tricks. I think response is too big for snmp windows agent. 

`--subsetleef=20 --maxrepetitions=20`

**Comment by quentincaron** [comment]
Merci Sims24 de ta réponse, malheureusement j'ai toujours le même problème malgré cette option : 

/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=IP --snmp-version=2c --snmp-community=community --service='Netlogon' --regexp --verbose  --state=active --critical=1: --subsetleef=10 --maxrepetitions=10
UNKNOWN: SNMP Table Request : (genError) A general failure occured

**Comment by Sims24** [comment]
Hello, 

Maybe tester avec la v1 de SNMP, avec le --snmp-force-getnext mais sans les options ci-dessus

**Comment by Sims24** [comment]
@quentincaron pas certain que l'on trouve un moyen de contourner le problème, mais est-ce qu'une session webex serait possible pour confirmer/infirmer toutes les solutions envisageables?

**Comment by jrouanne** [comment]
Bonjour,

Avez-vous désactivé le SMBv1 sur votre serveur ?

**Comment by jronzon** [comment]
Bonjour,

J'ai le meme problème sur un W2012 aussi avec le mode interfaces.

**Comment by pierrenavarrete** [comment]
Bonjour, 
Avez du nouveau à ce sujet ?
Je rencontre le même problème mais seulement quand j'interroge des services Windows 10, Win 7 me répond parfaitement avec les même commandes...
Je désespère xD

**Comment by Sims24** [comment]
Bonjour @pierrenavarrete et tout le monde, 

Nous n'avons malheureusement pas de solutions miracle, Windows ne supporte plus SNMP officiellement à partir de Windows 10 et WServer 2016, nous vous recommandons d'utiliser NSClient++ et nos plugins interrogeant sa ReST API, cette solution est la plus pérenne. 

Désolé de ne pas pouvoir faire plus sur ce sujet,
Simon

**Comment by pierrenavarrete** [comment]
Bonjour @Sims24, 
Je suis content et en même temps déçu de te lire. Merci pour ton retour et je pense que maintenant que cela est dit ce poste peut être clos.
Même si "ne support plus" ne veux pas dire, que Microsoft stop le service. Donc une solution pour cette erreur doit exister...
Merci pour ton retour.
Pierre

**Comment by Sims24** [comment]
Je pense qu'une solution pourrait être de remplacer la brique Windows legacy par net-snmp, comme discuté ici : 

https://serverfault.com/questions/283922/how-do-i-install-net-snmp-on-windows-without-visual-studio

C'est quand même un peu ch**** :) Pour SNMP on ne peut pas non plus checker des disques avec une grosse taille, les limites s'accumulent sur son implémentation pour Windows, autant ne pas s'y accrocher ;)

**Comment by Sims24** [comment]
Hey here, 

@garnier-quentin did a patch here => https://github.com/centreon/centreon-plugins/issues/1642 

Give it a try I think it will finally fix the problem \o/
