### ISSUE TITLE
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.

### ISSUE THREAD

**Issue by Saix00** [centreon/centreon-plugins#880]
Hi,

We're configuring a snmp for our NetApps systems ang with the mode volumeoptions for the NetApp plugin we're seeing the following errors:

`[root@Centreon-Central` centreon-plugins]# perl centreon_plugins.pl  --plugin=storage::netapp::snmp::plugin --mode=volumeoptions --hostname *** --snmp-community *** --snmp-version 2
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
Use of uninitialized value $option in sprintf at /root/Centreon Install/centreon-plugins/storage/netapp/snmp/mode/volumeoptions.pm line 109.
OK: All volume options are ok. | 'failed'=0;;;0;
`

**Comment by Sims24** [comment]
Hello, 

Could you provide a snmpwalk of the following table please : 

.1.3.6.1.4.1.789.1.5.8.1.2
and 
.1.3.6.1.4.1.789.1.5.8.1.7

Thanks

**Comment by Saix00** [comment]
sure,

here it is:

`[root@Centreon-Central centreon-plugins]# snmpwalk -H 192.*** -v 2c -C *** .1.3.6.1.4.1.789.1.5.8.1.2
Configuration directives understood:
No log handling enabled - turning on stderr logging
  In snmpwalk.conf and snmpwalk.local.conf:
    includeRequested         (1|yes|true|0|no|false)
    excludeRequested         (1|yes|true|0|no|false)
    printStatistics          (1|yes|true|0|no|false)
    dontCheckOrdering        (1|yes|true|0|no|false)
    timeResults              (1|yes|true|0|no|false)
  In snmp.conf and snmp.local.conf:
    alias                    NAME TRANSPORT_DEFINITION
    doDebugging              (1|0)
    debugTokens              token[,token...]
    logTimestamp             (1|yes|true|0|no|false)
    mibdirs                  [mib-dirs|+mib-dirs|-mib-dirs]
    mibs                     [mib-tokens|+mib-tokens]
    mibfile                  mibfile-to-read
    showMibErrors            (1|yes|true|0|no|false)
    commentToEOL             (1|yes|true|0|no|false)
    strictCommentTerm        (1|yes|true|0|no|false)
    mibAllowUnderline        (1|yes|true|0|no|false)
    mibWarningLevel          integerValue
    mibReplaceWithLatest     (1|yes|true|0|no|false)
    printNumericEnums        (1|yes|true|0|no|false)
    printNumericOids         (1|yes|true|0|no|false)
    escapeQuotes             (1|yes|true|0|no|false)
    dontBreakdownOids        (1|yes|true|0|no|false)
    quickPrinting            (1|yes|true|0|no|false)
    numericTimeticks         (1|yes|true|0|no|false)
    oidOutputFormat          integerValue
    suffixPrinting           integerValue
    extendedIndex            (1|yes|true|0|no|false)
    printHexText             (1|yes|true|0|no|false)
    printValueOnly           (1|yes|true|0|no|false)
    dontPrintUnits           (1|yes|true|0|no|false)
    hexOutputLength          integerValue
    dumpPacket               (1|yes|true|0|no|false)
    reverseEncodeBER         (1|yes|true|0|no|false)
    defaultPort              integerValue
    defCommunity             string
    noTokenWarnings          (1|yes|true|0|no|false)
    noRangeCheck             (1|yes|true|0|no|false)
    persistentDir            string
    tempFilePattern          string
    noDisplayHint            (1|yes|true|0|no|false)
    16bitIDs                 (1|yes|true|0|no|false)
    clientaddr               string
    clientaddrUsesPort       (1|yes|true|0|no|false)
    serverSendBuf            integerValue
    serverRecvBuf            integerValue
    clientSendBuf            integerValue
    clientRecvBuf            integerValue
    noPersistentLoad         (1|yes|true|0|no|false)
    noPersistentSave         (1|yes|true|0|no|false)
    noContextEngineIDDiscovery (1|yes|true|0|no|false)
    defDomain                application domain
    defTarget                application domain target
    defSecurityModel         string
    defSecurityName          string
    defContext               string
    defPassphrase            string
    defAuthPassphrase        string
    defPrivPassphrase        string
    defAuthMasterKey         string
    defPrivMasterKey         string
    defAuthLocalizedKey      string
    defPrivLocalizedKey      string
    defVersion               1|2c|3
    defAuthType              MD5|SHA
    defPrivType              DES|AES
    defSecurityLevel         noAuthNoPriv|authNoPriv|authPriv
  In snmpapp.conf and snmpapp.local.conf:
    defDomain                application domain
    defTarget                application domain target
    engineID                 string
    engineIDType             num
    engineIDNic              string
[root@Centreon-Central centreon-plugins]# snmpwalk -H *** -v 2c -C *** .1.3.6.1.4.1.789.1.5.8.1.7
Configuration directives understood:
No log handling enabled - turning on stderr logging
  In snmpwalk.conf and snmpwalk.local.conf:
    includeRequested         (1|yes|true|0|no|false)
    excludeRequested         (1|yes|true|0|no|false)
    printStatistics          (1|yes|true|0|no|false)
    dontCheckOrdering        (1|yes|true|0|no|false)
    timeResults              (1|yes|true|0|no|false)
  In snmp.conf and snmp.local.conf:
    alias                    NAME TRANSPORT_DEFINITION
    doDebugging              (1|0)
    debugTokens              token[,token...]
    logTimestamp             (1|yes|true|0|no|false)
    mibdirs                  [mib-dirs|+mib-dirs|-mib-dirs]
    mibs                     [mib-tokens|+mib-tokens]
    mibfile                  mibfile-to-read
    showMibErrors            (1|yes|true|0|no|false)
    commentToEOL             (1|yes|true|0|no|false)
    strictCommentTerm        (1|yes|true|0|no|false)
    mibAllowUnderline        (1|yes|true|0|no|false)
    mibWarningLevel          integerValue
    mibReplaceWithLatest     (1|yes|true|0|no|false)
    printNumericEnums        (1|yes|true|0|no|false)
    printNumericOids         (1|yes|true|0|no|false)
    escapeQuotes             (1|yes|true|0|no|false)
    dontBreakdownOids        (1|yes|true|0|no|false)
    quickPrinting            (1|yes|true|0|no|false)
    numericTimeticks         (1|yes|true|0|no|false)
    oidOutputFormat          integerValue
    suffixPrinting           integerValue
    extendedIndex            (1|yes|true|0|no|false)
    printHexText             (1|yes|true|0|no|false)
    printValueOnly           (1|yes|true|0|no|false)
    dontPrintUnits           (1|yes|true|0|no|false)
    hexOutputLength          integerValue
    dumpPacket               (1|yes|true|0|no|false)
    reverseEncodeBER         (1|yes|true|0|no|false)
    defaultPort              integerValue
    defCommunity             string
    noTokenWarnings          (1|yes|true|0|no|false)
    noRangeCheck             (1|yes|true|0|no|false)
    persistentDir            string
    tempFilePattern          string
    noDisplayHint            (1|yes|true|0|no|false)
    16bitIDs                 (1|yes|true|0|no|false)
    clientaddr               string
    clientaddrUsesPort       (1|yes|true|0|no|false)
    serverSendBuf            integerValue
    serverRecvBuf            integerValue
    clientSendBuf            integerValue
    clientRecvBuf            integerValue
    noPersistentLoad         (1|yes|true|0|no|false)
    noPersistentSave         (1|yes|true|0|no|false)
    noContextEngineIDDiscovery (1|yes|true|0|no|false)
    defDomain                application domain
    defTarget                application domain target
    defSecurityModel         string
    defSecurityName          string
    defContext               string
    defPassphrase            string
    defAuthPassphrase        string
    defPrivPassphrase        string
    defAuthMasterKey         string
    defPrivMasterKey         string
    defAuthLocalizedKey      string
    defPrivLocalizedKey      string
    defVersion               1|2c|3
    defAuthType              MD5|SHA
    defPrivType              DES|AES
    defSecurityLevel         noAuthNoPriv|authNoPriv|authPriv
  In snmpapp.conf and snmpapp.local.conf:
    defDomain                application domain
    defTarget                application domain target
    engineID                 string
    engineIDType             num
    engineIDNic              string
`

**Comment by Sims24** [comment]
you seems to have some trouble with your command syntax. this do not looks like a snmpwalk result

**Comment by cgagnaire** [comment]
The community value must be provided using "-c" and no "-C" option.
