### ISSUE TITLE
os::linux::local::plugin mode storage , space-reservation

### ISSUE THREAD

**Issue by s-duret** [centreon/centreon-plugins#881]
Hi,

It would be great if the plugin could check the space reservation directly on the server and have no need to add --space-reservation option.
I think there is no option for df command to check the space reservation.
Maybe we can use another command to have it?

Regards

**Comment by Sims24** [comment]
Hello Stéphane, 

Unfortunately, this plugin strongly relies on df command and its output. 

As we want to keep plugins as simple as possible with a minimum dependencies or extra package, we will probably not developp such feature. 

Please set your thresholds accordingly to take in account common space reservation for filesystems.

Regards
