### ISSUE TITLE
Centreon-Broker showing UNKNOWN after update

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#883]
Hello guys,

I have the problem that since my last update today following the state of my check "Centreon-Broker" switched to UNKNOWN.

> UNKNOWN: '/etc/centreon-broker/central-rrd.xml': cannot open directory ' /var/lib/centreon-broker'

And this is the command
`/usr/lib/centreon/plugins/centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --mode=retention-broker	--broker-config='/etc/centreon-broker/central-rrd.xml' --broker-config='/etc/centreon-broker/central-broker.xml'	--verbose`

Additional to this the verbose output:
> Checking config '/etc/centreon-broker/central-rrd.xml'
skipping temporary: no configuration set
Checking config '/etc/centreon-broker/central-broker.xml'
failover 'central-broker-master-perfdata-failover': 0 file(s) found (0.00 B)
failover 'central-broker-master-sql-failover': 0 file(s) found (0.00 B)
failover 'centreon-broker-master-rrd-failover': 0 file(s) found (0.00 B)
skipping temporary: no configuration set

Thank you very much.

Best regards, Mike

**Comment by cgagnaire** [comment]
Hi @MikeW83,
It looks like the rights have changed on this directory and the engine user is not able to read it.

Be aware that if you are using Centreon 2.8.x, you should use broker-stats mode instead : 
```
# /usr/lib/centreon/plugins/centreon_centreon_central.pl --plugin=apps::centreon::local::plugin --mode=broker-stats --broker-stats-file='/var/lib/centreon-broker/central-rrd-master-stats.json' --broker-stats-file='/var/lib/centreon-broker/central-broker-master-stats.json' --verbose
OK: Broker statistics are ok | 'speed_events_(external commands)'=0events/s;;;0; 'queued_events_(external commands)'=0events;;;0; 'speed_events_central-broker-master-input'=0events/s;;;0; 'queued_events_central-broker-master-input'=0events;;;0; 'speed_events_central-broker-master-perfdata'=0.290323events/s;;;0; 'queued_events_central-broker-master-perfdata'=0events;;;0; 'speed_events_central-broker-master-sql'=0.290323events/s;;;0; 'queued_events_central-broker-master-sql'=0events;;;0; 'speed_events_central-rrd-master-input'=0events/s;;;0; 'queued_events_central-rrd-master-input'=0events;;;0; 'speed_events_central-rrd-master-output'=0.290323events/s;;;0; 'queued_events_central-rrd-master-output'=0events;;;0; 'speed_events_centreon-broker-master-rrd'=0.290323events/s;;;0; 'queued_events_centreon-broker-master-rrd'=779events;;;0; 'unacknowledged_events_centreon-broker-master-rrd'=0events;;;0;
Endpoint input '(external commands)' state : listening, Speed Events: 0/s, Queued Events: 0
Endpoint input 'central-broker-master-input' state : listening, Speed Events: 0/s, Queued Events: 0
Endpoint output 'central-broker-master-perfdata' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.290323/s, Queued Events: 0
Endpoint output 'central-broker-master-sql' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.290323/s, Queued Events: 0
Endpoint input 'central-rrd-master-input' state : listening, Speed Events: 0/s, Queued Events: 0
Endpoint output 'central-rrd-master-output' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.290323/s, Queued Events: 0
Endpoint output 'centreon-broker-master-rrd' state : connected [status : reading event from multiplexing engine] [queue file enabled : no], Speed Events: 0.290323/s, Queued Events: 779, Unacknowledged Events: 0
```

**Comment by MikeW83** [comment]
I'm using the newest version. I have updated my Centreon installation yesterday and since this updated this message occurs.

![image](https://user-images.githubusercontent.com/35097389/35961194-11bd2d88-0cad-11e8-81fb-75c331dd053f.png)

**Comment by MikeW83** [comment]
Are there any suggestions?

**Comment by Sims24** [comment]
Hi @MikeW83, 

Could you send us an anonymized version of your xml config files please ?
