### ISSUE TITLE
Add mode for checking logs with os::linux::local

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon-plugins#886]
Hello,

It would be interessing to add a mode for os::linux::local::plugin to seek error messages in a log file. (like check_logfiles for windows)

The mode "files-date" and  "files-size" doesn't seems to provide this functionnality.

centreon_plugins.pl --plugin=os::linux::local::plugin --list-mode
[...]
Modes Available:
   cmd-return
   connections
   cpu
   cpu-detailed
   directlvm-usage
   diskio
   files-date
   files-size
   inodes
   list-interfaces
   list-partitions
   list-storages
   load
   memory
   packet-errors
   paging
   process
   quota
   storage
   swap
   systemd-sc-status
   traffic
   uptime
[...]

**Comment by Sims24** [comment]
Hello, 

We will probably not developp such plugin ... We will probably create some check around common log concentrators (elastic, splunk, ..;) rather than write such plugin which already exists in the community (consol labs check_logfiles plugin is great!).
