### ISSUE TITLE
 centreon-plugins/hardware/server/hp/bladechassis/snmp/mode/components/temperature.pm - Temperature is other

### ISSUE THREAD

**Issue by Bettisboy** [centreon/centreon-plugins#888]
Using plugin pack of HP Blade to monitor the HW Status of our Blade Center /usr/lib/centreon/plugins/centreon_hp_bladechassis.pl --plugin=hardware::server::hp::bladechassis::snmp::plugin --mode=hardware --hostname=XXXX--snmp-version='2c' --snmp-community='XXXX'  --component='temperature' --verbose

The output of the check is giving a status OK for the Chassis and the 2 System Components (Onboard Admin) but for the Blades and the Interconnect Tray it is giving a status 'Other' which shows as an error in the interface.

Checking temperatures
Temperature 1 status is ok [name: XXXXXXXX, location: Chassis] (value = 21, threshold = 42, status type = caution).
Temperature 2 status is ok [name: XXXXXXXX, location: System] (value = 36, threshold = 75, status type = caution).
Temperature 3 status is ok [name: XXXXXXXX, location: System] (value = 36, threshold = 75, status type = caution).
Temperature 4 status is other [name: XXXXXXXX, location: Blade Bay] (value = 21, threshold = 42, status type = caution).
Temperature 5 status is other [name: XXXXXXXX, location: Blade Bay] (value = 21, threshold = 42, status type = caution).
Temperature 6 status is other [name: XXXXXXXX, location: Blade Bay] (value = 21, threshold = 42, status type = caution).
Temperature 7 status is other [name: XXXXXXXX, location: Blade Bay] (value = 21, threshold = 42, status type = caution).
Temperature 8 status is other [name: XXXXXXXX, location: Blade Bay] (value = 0, threshold = 42, status type = caution).
Temperature 9 status is other [name: XXXXXXXX, location: Blade Bay] (value = 0, threshold = 42, status type = caution).
Temperature 10 status is other [name: XXXXXXXX, location: Blade Bay] (value = 0, threshold = 42, status type = caution).
Skipping instance 11: current -1
Temperature 12 status is other [name: XXXXXXXX, location: Blade Bay] (value = 0, threshold = 42, status type = caution).
Temperature 13 status is other [name: XXXXXXXX, location: Blade Bay] (value = 0, threshold = 42, status type = caution).
Temperature 14 status is other [name: XXXXXXXX, location: Blade Bay] (value = 0, threshold = 42, status type = caution).
Temperature 15 status is other [name: XXXXXXXX, location: Blade Bay] (value = 21, threshold = 42, status type = caution).
Temperature 16 status is other [name: XXXXXXXX, location: Blade Bay] (value = 21, threshold = 42, status type = caution).
Temperature 17 status is other [name: XXXXXXXX, location: Blade Bay] (value = 21, threshold = 42, status type = caution).
Skipping instance 18: current -1
Skipping instance 19: current -1
Skipping instance 20: current -1
Skipping instance 21: current -1
Skipping instance 22: current -1
Skipping instance 23: current -1
Skipping instance 24: current -1
Skipping instance 25: current -1
Skipping instance 26: current -1
Skipping instance 27: current -1
Skipping instance 28: current -1
Skipping instance 29: current -1
Skipping instance 30: current -1
Skipping instance 31: current -1
Skipping instance 32: current -1
Skipping instance 33: current -1
Skipping instance 34: current -1
Skipping instance 35: current -1
Skipping instance 36: current -1
Skipping instance 37: current -1
Skipping instance 38: current -1
Skipping instance 39: current -1
Skipping instance 40: current -1
Skipping instance 41: current -1
Skipping instance 42: current -1
Skipping instance 43: current -1
Skipping instance 44: current -1
Skipping instance 45: current -1
Skipping instance 46: current -1
Skipping instance 47: current -1
Skipping instance 48: current -1
Skipping instance 49: current -1
Skipping instance 50: current -1
Skipping instance 51: current -1
Temperature 52 status is other [name: XXXXXXXX, location: Interconnect Tray] (value = 0, threshold = 0, status type = caution).
Temperature 53 status is other [name: XXXXXXXX, location: Interconnect Tray] (value = 0, threshold = 0, status type = caution).
Skipping instance 54: current -1
Skipping instance 55: current -1
Skipping instance 56: current -1
Skipping instance 57: current -1
Skipping instance 58: current -1
Skipping instance 59: current -1
Skipping instance 60: current -1

**Comment by Heusini** [comment]
I have the same error if you run a snmpwalk the oids output 1 which is mapped to other
`my $oid_cpqRackCommonEnclosureTempCondition = '.1.3.6.1.4.1.232.22.2.3.1.2.1.8';`
`my %map_conditions = (
    1 => 'other', 
    2 => 'ok', 
    3 => 'degraded', 
    4 => 'failed',
);`


only my first 3 sensors return 2 and are okay. On the bladecenter itself i don't see any errors or unknowns

**Comment by Sims24** [comment]
Hello, 

yes this is something we have already seen. 

Please use threshold overload option like below : 

` --threshold-overload='temperature,OK,other'
`

This will avoid unwanted unknown. 

Thanks
