### ISSUE TITLE
Cisco 2960X - Traffic Global - "UNKNOWN: Can't construct cache..."

### ISSUE THREAD

**Issue by Whiteire** [centreon/centreon-plugins#889]
Hello,
There is a bug when i try to monitore network trafic on a cisco 2960X switch with centreon plugin.

Centreon plugin check command:
`/usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=XXX.XXX.XXX.XXX --snmp-version='2c' --snmp-community='centreon' --interface='.*' --name --add-status --add-traffic --critical-status='' --warning-in-traffic='80' --critical-in-traffic='90' --warning-out-traffic='80' --critical-out-traffic='90' --verbose`

Output is :
`UNKNOWN: Can't construct cache...`

I tried the same command with --oid-display ifDesc --oid-filter ifDesc option but i got same output.
I also tried to replace ifDesc by ifName and ifAlias but still same output.

Others checks works well (fans ,temperatures, voltages, power supplies ...).

Thanks for your help !

**Comment by Sims24** [comment]
Hello, 

Please give us the result of : 

`/usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=list-interfaces --hostname=XXX.XXX.XXX.XXX --snmp-version='2c' --snmp-community='centreon' --interface='' --name --add-status --add-traffic --critical-status='' --warning-in-traffic='80' --critical-in-traffic='90' --warning-out-traffic='80' --critical-out-traffic='90' --verbose
`
Also, could you snmpwalk following oids from your client server please : 

```
    $self->{oids_label} = {
        'ifdesc' => '.1.3.6.1.2.1.2.2.1.2',
        'ifalias' => '.1.3.6.1.2.1.31.1.1.1.18',
        'ifname' => '.1.3.6.1.2.1.31.1.1.1.1',
    };
```

**Comment by Whiteire** [comment]
Thanks for your help @Sims24 

I got an error for the first command :
`Unknown option: add-status at /usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl line 4269.`
I exactly copied pasted the command and replacing the ip.

Output from snmpwalk commands :

[root@localhost ~]# snmpwalk -v 2c -c centreon XXX.XXX.XXX.XXX .1.3.6.1.2.1.2.2.1.2
`IF-MIB::ifDescr = No more variables left in this MIB View (It is past the end of the MIB tree)`

[root@localhost ~]# snmpwalk -v 2c -c centreon  XXX.XXX.XXX.XXX .1.3.6.1.2.1.31.1.1.1.18
`IF-MIB::ifAlias = No more variables left in this MIB View (It is past the end of the MIB tree)`

[root@localhost ~]# snmpwalk -v 2c -c centreon  XXX.XXX.XXX.XXX .1.3.6.1.2.1.31.1.1.1.1
`IF-MIB::ifName = No more variables left in this MIB View (It is past the end of the MIB tree)`

**Comment by Whiteire** [comment]
Edit :
I tried to modify the first command without options like that :
`/usr/lib/centreon/plugins/centreon_cisco_standard_snmp.pl --plugin=network::cisco::standard::snmp::plugin --mode=list-interfaces --hostname=XXX.XXX.XXX.XXX --snmp-version='2c' --snmp-community='centreon' --interface='' --name --verbose`

Output
`UNKNOWN: Can't get interfaces...`

Thanks.

**Comment by Sims24** [comment]
Looks like the issue is in your Cisco SNMP configuration. You do not have access to required OIDs.

**Comment by Whiteire** [comment]
Thanks !
It was a permission problem in my Cisco SNMP configuration.

Thank you again for your help, you can close the issue !

**Comment by Sims24** [comment]
Hey @Whiteire,

No it's not because we prefer to limit number of char is short output.

This is more clear in Centreon Web UI, especially if you have a router/switch with a high number of port ! Also this ensures compliance with other monitoring tool as it fits monitoring plugins dev guidelines.
