### ISSUE TITLE
Nagvis weathermap format option for traffic perfdata

### ISSUE THREAD

**Issue by EChauve** [centreon/centreon-plugins#89]
Well, given the commercial competition between NagVis and Centreon Map, I can not expect a member of Centreon's team to work on that, but if someone else does it, maybe they will accept the pull request.

The enhancement proposition is as said in the title:
Creating an option to change the perfdata format of centreon_plugins.pl traffic mode so it will fit the format asked by NagVis weatherline. 

Here is the required format (http://docs.nagvis.org/1.5/en_US/lines_weathermap_style.html) : 

The weathermap lines do not require a specific Nagios plugin. Only the provided performance format needs to match one of the cases below:

    Percentage usage: four perfdata sets. While the first two sets provide the percentage usage and the second two sets provide the usage in bytes per sec.
    One example: inUsage=21103.42%;85;98 outUsage=226363.55%;85;98 inBandwidth=105.52MBs outBandwidth=212.22MBs.
    Byte rate usage: needs at least two perfdata sets with the labels "in" and "out" with an empty UOM. It uses the current value and the maximum value to calculate the current percentage usage. The current value should be given as byte rate. The maximum value should provide the network interface bandwidth as bytes per seconds.
    One example: in=7196.50566429;;;0;1250000.0 inucast=11.6273564992;;;; innucast=0.017617206817;;;; indisc=0.0;;;; inerr=0.0;0.01;0.1;; out=4044.9635368;;;0;1250000.0 outucast=12.1734899105;;;; outnucast=0.0;;;; outdisc=0.0;;;; outerr=0.0;0.01;0.1;; outqlen=0;;;;.

**Comment by garnier-quentin** [comment]
Hi Etienne,

You can use the option '--change-perfdata' in centreon-plugins for that ;)

**Comment by EChauve** [comment]
I know it is technically possible indeed, but it does require a certain understanding of Perl regular expression (which I do not have right now).

Moreover NagVis is a widely used mapper even amongst Centreon users, adding the option would avoid a lot of people the trouble of using another plugin just to change the perfdata format.

Therefore I would like you to let this issue as an enhancement request, for a kind soul to fulfill maybe one day. What do you think? Would it be too much of a bother?

**Comment by garnier-quentin** [comment]
I'll do a refactoring of interface modes. So i can add maybe an option for that ;)

**Comment by EChauve** [comment]
Thank you for considering it, 
Have a nice day :)
