### ISSUE TITLE
Type of arg 1 to keys must be hash error

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#890]
I updated the plugin package today and after that I get this error:

bash-4.1$ ./centreon_plugins.pl --plugin=os/linux/snmp/plugin.pm --mode=processcount --hostname=1.2.3.4 --snmp-username=user --authpassphrase=xxx --authprotocol=SHA --privpassphrase=xxx --privprotocol=DES --snmp-version=3
UNKNOWN: Cannot load module --mode. 
Type of arg 1 to keys must be hash (not hash element) at /usr/lib/nagios/plugins/snmp_standard/mode/processcount.pm line 341, near "}) "
Compilation failed in require at /usr/lib/nagios/plugins/centreon/plugins/misc.pm line 221.

**Comment by Sims24** [comment]
Hello @kadrika 

Please correct line 221 like this : 

`        for my $key (keys %{$self->{results}->{$pid}}) {
`

Thanks

**Comment by Sims24** [comment]
Edit: 341 of processcount my bad

**Comment by cgagnaire** [comment]
Fix with this commit https://github.com/centreon/centreon-plugins/commit/9b516e9a4b0e366ec0f5463bce66fa880b011467

**Comment by kadrika** [comment]
Thanks, that fixed the issue!
