### ISSUE TITLE
Unable to get MSSQL Server Version

### ISSUE THREAD

**Issue by sheraazb** [centreon/centreon-plugins#892]
https://github.com/centreon/centreon-plugins/blob/9b516e9a4b0e366ec0f5463bce66fa880b011467/centreon/plugins/dbi.pm#L223

the get_info(18) does not work with dbi:Sybase driver. Recommending a more universal implementation to get MSSQL Server version as follows;

my $sth = $self->{instance}->prepare("select SERVERPROPERTY('productversion')");
        if($sth->execute) {
                while(my @dat = $sth->fetchrow) {
                        $self->{version} = "@dat";
                }
        }

$sth->finish;

**Comment by Sims24** [comment]
@sheraazb thanks for the feedback, we did not heard about such problem before .. 

Could you give us the mssql version that you have and also the perl-DBD-Sybase version please ? 

Thx

**Comment by sheraazb** [comment]
Hi @Sims24 

The version of MSSQL is 2012 and perl-DBD-Sybase is as follows;

perl-DBD-Sybase.x86_64              1.15-2.el7.centos          @pulp-Centreon

**Comment by sheraazb** [comment]
Just an update. I managed to fix the issues in my env by applying my proposed fix.

**Comment by omercier** [comment]
I can confirm that the proposed method for getting the server version is good.
I tried to print(Data::Dumper) $self->{version}:
* without the patch: $VAR1 = undef;
* with the patch: $VAR1 = '14.0.1000.169';

**Comment by Sims24** [comment]
@sheraazb @omercier thanks for further testing and informations provided.

Need a PR to discuss about implementation. To take Tim Bunce words from related thread of this mailing lists  .. https://www.nntp.perl.org/group/perl.dbi.dev/2001/11/msg523.html and https://www.nntp.perl.org/group/perl.dbi.dev/2002/01/msg769.html : 

_"I'd be a little nervous of that returning more than one row."_

Basically, not fan of assigning array to scalar and the way, not fan of making one more query for each check, need to dig around and figure out why before thinking on how we can workaround ..

Question: does this need more privileges as the usual checks ?

 Miss some time on this one as it does not seems to have a huge impact on the check it's not a top priority. 

Few things to read here and I do not totally get it at this moment :) (https://beta.nntp.perl.org/group/perl.dbi.users/2011/06/msg35864.html).

**Comment by garnier-quentin** [comment]
I close. Duplicate with following: #1038
