### ISSUE TITLE
Error with centreon_windows_snmp.pl

### ISSUE THREAD

**Issue by y4jay** [centreon/centreon-plugins#893]
Hello,

I have an error when I use the centreon_windows_snmp.pl plugin only with the storage mode. The output in centreon is Unknown option: warning-usage at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.
I use Centreon 2.8.17 and this command was working fine before update.

**Comment by pkriko** [comment]
Hello,

Can you try with the option --warning ?
Can you also update your plugin : yum update centreon-plugin-Operatingsystems-Windows-Snmp

**Comment by y4jay** [comment]
Hello,

The plugin is up to date. How can I modify the option --warning please ?

**Comment by pkriko** [comment]
You mean in the web interface ?
Your plugin pack in Configuration > Plugin Pack are also up to date ?

**Comment by y4jay** [comment]
Yes my plugin pack is up to date (Windows SNMP 3.0.12). I can't modify the command because it's a plugin pack and the command is in read only but if I type the command in a shell it works with the option --warning. Where can I change the command ?

**Comment by pkriko** [comment]
I'm sorry. I misunderstanding your command.
From my side with the last plugin pack and the plugin, the command work with --warning-usage and --critical-usage : 
-bash-4.2$ /usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=10.40.1.154 --snmp-version='2c' --snmp-community='public'  --storage='.*' --name --regexp --display-transform-src='^(..).*' --display-transform-dst='$1' --warning-usage='80' --critical-usage='90' --verbose
OK: All storages are ok | 'used_C:'=17540984832B;0:27192508416;0:30591571968;0;33990635520 'used_K:'=49307648B;0:1715467059;0:1929900441;0;2144333824
Storage 'C:' Usage Total: 31.66 GB Used: 16.34 GB (51.61%) Free: 15.32 GB (48.39%)
Storage 'K:' Usage Total: 2.00 GB Used: 47.02 MB (2.30%) Free: 1.95 GB (97.70%)

**Comment by y4jay** [comment]
The command doesn't work for me with --warning-usage and --critical-usage... What version of Centreon do you use ?

**Comment by pkriko** [comment]
2.8.17.
Can you send me the output of rpm -qa | grep -i Windows-Snmp ?

**Comment by y4jay** [comment]
Yes of course. Here it is :
centreon-plugin-Operatingsystems-Windows-Snmp-20171208-1.el7.noarch

**Comment by pkriko** [comment]
Weird.
Can you send the output of the command : 
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=10.40.1.154 --snmp-version='2c' --snmp-community='public'  --storage='.*' --name --regexp --display-transform-src='^(..).*' --display-transform-dst='$1' --warning-usage='80' --critical-usage='90' --verbose --help

**Comment by y4jay** [comment]
It returns the plugin description :
Plugin Description:
    Check Windows operating systems in SNMP.

Global Options:
    --mode  Choose a mode.

    --dyn-mode
            Specify a mode with the path (separated by '::').

    --list-mode
            List available modes.

    --mode-version
            Check minimal version of mode. If not, unknown error.

    --version
            Display plugin version.

Output Options:
    --verbose
            Display long output.

    --debug Display also debug messages.

    --filter-perfdata
            Filter perfdata that match the regexp.

    --explode-perfdata-max
            Put max perfdata (if it exist) in a specific perfdata (without
            values: same with '_max' suffix) (Multiple options)

    --change-perfdata
            Change perfdata name (Multiple option) Syntax:
            regexp_matching,regexp_substitute

    --range-perfdata
            Change perfdata range thresholds display: 1 = start value equals
            to '0' is removed, 2 = threshold range is not display.

    --filter-uom
            Filter UOM that match the regexp.

    --opt-exit
            Exit code for an option error, usage (default: unknown).

    --output-xml
            Display output in XML Format.

    --output-json
            Display output in JSON Format.

    --output-file
            Write output in file (can be used with json and xml options)

    --disco-format
            Display discovery arguments (if the mode manages it).

    --disco-show
            Display discovery values (if the mode manages it).

Snmp Options:
    --hostname
            Hostname to query (required).

    --snmp-community
            Read community (defaults to public).

    --snmp-version
            Version: 1 for SNMP v1 (default), 2 for SNMP v2c, 3 for SNMP v3.

    --snmp-port
            Port (default: 161).

    --snmp-timeout
            Timeout in secondes (default: 1) before retries.

    --snmp-retries
            Set the number of retries (default: 5) before failure.

    --maxrepetitions
            Max repetitions value (default: 50) (only for SNMP v2 and v3).

    --subsetleef
            How many oid values per SNMP request (default: 50) (for get_leef
            method. Be cautious whe you set it. Prefer to let the default
            value).

    --snmp-force-getnext
            Use snmp getnext function (even in snmp v2c and v3).

    --snmp-username
            Security name (only for SNMP v3).

    --authpassphrase
            Authentication protocol pass phrase.

    --authprotocol
            Authentication protocol (MD5|SHA)

    --privpassphrase
            Privacy protocol pass phrase

    --privprotocol
            Privacy protocol (DES|AES)

    --contextname
            Context name

    --contextengineid
            Context engine ID

    --securityengineid
            Security engine ID

    --snmp-errors-exit
            Exit code for SNMP Errors (default: unknown)

Retention Options:
    --memcached
            Memcached server to use (only one server).

    --statefile-dir
            Directory for statefile (Default:
            '/var/lib/centreon/centplugins').

    --statefile-suffix
            Add a suffix for the statefile name (Default: '').

    --statefile-concat-cwd
            Concat current working directory with option '--statefile-dir'.
            Useful on Windows when plugin is compiled.

    --statefile-storable
            Use Perl Module 'Storable' (instead Data::Dumper) to store
            datas.

Mode:
    --warning
            Threshold warning.

    --critical
            Threshold critical.

    --units Units of thresholds (Default: '%') ('%', 'B').

    --free  Thresholds are on free space left.

    --storage
            Set the storage (number expected) ex: 1, 2,... (empty means
            'check all storage').

    --name  Allows to use storage name with option --storage instead of
            storage oid index.

    --regexp
            Allows to use regexp to filter storage (with option --name).

    --regexp-isensitive
            Allows to use regexp non case-sensitive (with --regexp).

    --reload-cache-time
            Time in minutes before reloading cache file (default: 180).

    --oid-filter
            Choose OID used to filter storage (default: hrStorageDescr)
            (values: hrStorageDescr, hrFSMountPoint).

    --oid-display
            Choose OID used to display storage (default: hrStorageDescr)
            (values: hrStorageDescr, hrFSMountPoint).

    --display-transform-src
            Regexp src to transform display value. (security risk!!!)

    --display-transform-dst
            Regexp dst to transform display value. (security risk!!!)

    --show-cache
            Display cache storage datas.

    --space-reservation
            Some filesystem has space reserved (like ext4 for root). The
            value is in percent of total (Default: none) (results like 'df'
            command).

    --filter-storage-type
            Filter storage types with a regexp (Default:
            '^(hrStorageFixedDisk|hrStorageNetworkDisk|hrFSBerkeleyFFS)$').

**Comment by pkriko** [comment]
Very weird.
Can you send the file /usr/lib/centreon/plugins/centreon_windows_snmp.pl ?

**Comment by y4jay** [comment]
[centreon_windows_snmp.zip](https://github.com/centreon/centreon-plugins/files/1744112/centreon_windows_snmp.zip)

**Comment by pkriko** [comment]
Do you use this plugin on the central or on a Poller ?
Is the plugin is also up to date on the poller ?

**Comment by y4jay** [comment]
I use this plugin on the central.

**Comment by pkriko** [comment]
I tried to use your script. And it's work for me ... :
[root@pkr-central ~]# perl centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=10.40.1.154 --snmp-version='2c' --snmp-community='public' --storage='.' --name --regexp --display-transform-src='^(..).' --display-transform-dst='$1' --warning-usage='80' --critical-usage='90' --verbose
OK: All storages are ok | 'used_C: Label:  Serial Number 38697ffc'=17566101504B;0:27192508416;0:30591571968;0;33990635520 'used_K: Label:Nouveau nom  Serial Number 66dd9d25'=49307648B;0:1715467059;0:1929900441;0;2144333824
Storage 'C: Label:  Serial Number 38697ffc' Usage Total: 31.66 GB Used: 16.36 GB (51.68%) Free: 15.30 GB (48.32%)
Storage 'K: Label:Nouveau nom  Serial Number 66dd9d25' Usage Total: 2.00 GB Used: 47.02 MB (2.30%) Free: 1.95 GB (97.70%)
I don't know where/what is your issue. Are sure that you used /usr/lib/centreon/plugins/centreon_windows_snmp.pl ?

**Comment by y4jay** [comment]
Yes i'm sure. Have a look of the command in the gui of centreon :
/usr/lib/centreon/plugins/centreon_windows_snmp.pl
	--plugin=os::windows::snmp::plugin
	--mode=storage
	--hostname=192.168.1.112
	--snmp-version='1'
	--snmp-community='public' 
	--storage='.*'
	--name
	--regexp
	--display-transform-src='^(..).*'
	--display-transform-dst='$1'
	--warning-usage='80'
	--critical-usage='90'
	--verbose

**Comment by y4jay** [comment]
How can I modify "--warning-usage" and "--critical-usage" ? If I replace it by --warning and --critical the command will work...

**Comment by pkriko** [comment]
You can't.
You can copy and paste the command, and link to the custom template but you canno modify the command/template that are not custom.
But there is something strange from your side. The plugin that you sent me is the right one. can you sent me the command that you tried with the --warning ? (with the path of the plugin please).

**Comment by MonkeyNab** [comment]
Hello guys,
"Happy" to see i'm not the only one to encounter this issue, having the exact same issue as you y4jay.
By the way, quite weird to have an update with errors in it push as "stable".

**Comment by y4jay** [comment]
/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=storage --hostname=192.168.1.112 --snmp-version='1' --snmp-community='public' --storage='.*' --name --regexp --display-transform-src='^(..).*' --display-transform-dst='$1' --warning='80' --critical='90' --verbose
CRITICAL: Storage 'F:' Total: 279.24 GB Used: 255.21 GB (91.40%) Free: 24.03 GB (8.60%) | 'used_C:'=58332434432B;0:67108860723;0:75497468313;0;83886075904 'used_D:'=99303882752B;0:172777639116;0:194374844006;0;215972048896 'used_F:'=274034110464B;0:239864692736;0:269847779328;0;299830865920
Storage 'C:' Total: 78.12 GB Used: 54.33 GB (69.54%) Free: 23.80 GB (30.46%)
Storage 'D:' Total: 201.14 GB Used: 92.48 GB (45.98%) Free: 108.66 GB (54.02%)
Storage 'F:' Total: 279.24 GB Used: 255.21 GB (91.40%) Free: 24.03 GB (8.60%)

**Comment by y4jay** [comment]
As you can see it works with --warning and --critical.

**Comment by pkriko** [comment]
Can you contact me by email to see what I can do for you ?

**Comment by y4jay** [comment]
Yes of course. Can you give me your mail ?

**Comment by pkriko** [comment]
pkrikorian@centreon.com

**Comment by cgagnaire** [comment]
Hi @y4jay and @MonkeyNab,
The problem does not come from the plugin as @pkriko is using it like you and does not have any problem :)
It must come from your installation. You must have clone or copy the centreon-plugins project in the root directory of the plugin, here "/usr/lib/centreon/plugins/". And it must not be up-to-date. This way, the class "snmp_standard::mode::storage" is loaded from an old version and not from the last that is directly in the "centreon_windows_snmp.pl" file. Path stuff...
So you should move everything that belongs to the project to a "centreon-plugins" sub-directory.
Hope that helps!

**Comment by MonkeyNab** [comment]
Hi @cgagnaire,
Ok, for me the problem probably come from the fact i just updated my plugins from the web interface because i didn't encounter any issue like that since i install Centreon (something like 6 months) and the plugin is in the good directory. 
Anyway thanks for your explainations )

**Comment by y4jay** [comment]
Hello @cgagnaire,
@pkriko is gonna take a look on my configuration by a webex session next week. I will keep informed you as soon as possible. Thanks for your help, have a nice day.

**Comment by pkriko** [comment]
Issue is over. And it was due to the git clone from plugins in the root directory of plugins from centreon as @cgagnaire explained.

**Comment by SistemasEnergy** [comment]
Good morning, I have the same problem of y4jay, please could you tell me how was finally fixed the issue with plugins path?

Thanks in advance and regards

**Comment by cgagnaire** [comment]
Hi @SistemasEnergy,
The problem was solved by moving the centreon-plugins project files from the plugins directory to a sub-directory.

**Comment by SistemasEnergy** [comment]
Anyone please??

**Comment by cgagnaire** [comment]
Hi @SistemasEnergy,
The files from this project, centreon-plugins.
You must have those files and directories : 
```
drwxr-xr-x 47 root root  4096 Apr  6 10:01 apps
drwxr-xr-x  4 root root    35 Mar 12 22:35 centreon
-rw-r--r--  1 root root   989 Mar 12 22:36 centreon_plugins.pl
-rw-r--r--  1 root root 14657 Apr 27 18:25 changelog
drwxr-xr-x  6 root root    57 Mar 12 22:35 cloud
drwxr-xr-x  2 root root    46 Mar 12 22:35 contrib
drwxr-xr-x 10 root root   119 Mar 12 22:35 database
drwxr-xr-x  4 root root    26 Mar 12 22:35 docs
drwxr-xr-x  4 root root   107 Mar 12 22:35 example
drwxr-xr-x 10 root root   110 Mar 12 22:35 hardware
-rw-r--r--  1 root root 11357 Mar 12 22:35 LICENSE.txt
drwxr-xr-x 61 root root  4096 Apr 17 22:37 network
drwxr-xr-x  5 root root    48 Mar 15 16:53 notification
drwxr-xr-x  8 root root    87 Mar 12 22:36 os
-rw-r--r--  1 root root  3194 Mar 12 22:35 README.md
drwxr-xr-x  3 root root    18 Mar 12 22:36 snmp_standard
drwxr-xr-x 23 root root   305 Mar 12 22:36 storage
```
If true, you must move them to a 'centreon-plugins' directory.

**Comment by SistemasEnergy** [comment]
Hi @cgagnaire 

I didn't find those directories on the server, in wich folder the should be allocated?

Regards

**Comment by SistemasEnergy** [comment]
Anyone please? 

Thanks in advance
