### ISSUE TITLE
Monitore service with executable path instead of full service name

### ISSUE THREAD

**Issue by MonkeyNab** [centreon/centreon-plugins#894]
Hi,

I have a question: is it possible to check a service state with the executable path instead of the full service name (i actually use the plugin "check_snmp_win.pl" to check service) because depending on the host's language the service doesn't have the same full name :/
So if you have any tips on how can i do it or a name of plugin which allow it )

Regards

**Comment by Sims24** [comment]
Do you mean the processname.exe ?

**Comment by MonkeyNab** [comment]
Yep exactly

**Comment by MonkeyNab** [comment]
So, do you have any ideas on how i can make it @Sims24? Trough processname.exe or short service name it doesn't matter. The idea is to have a service check which can work no matter the OS version or language.

Thanks in advance,
Regards

**Comment by cgagnaire** [comment]
Hi @MonkeyNab,
You can use processcount mode.

**Comment by MonkeyNab** [comment]
Heyo @cgagnaire,

Thanks for your reply. Ok so this is with the plugin "os::windows::snmp::plugin" right? If i check the processcount it won't warn you if the service is not running or i misunderstood the way to use it :/
Here is the cmd i actually try:
`perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=processcount --hostname myHost --snmp-community mySnmpCommunity --snmp-version 2c --process-name seclogon --process-status running
OK: Number of current processes running: 0 | 'nbproc'=0;;;0;
`
"seclogon" is the service "Secondary Logon"

So can you explain me how to use it correctly please? )

**Comment by cgagnaire** [comment]
@MonkeyNab,
This mode is made to monitor processes, not services.
You should use your last command line with the exact name of the process, or use the `--regexp-name` option to allow regexp.

**Comment by MonkeyNab** [comment]
@cgagnaire,
Yeah i saw it, that's why i asked you if you could check services status with this mode cuz it sound weird )
Let me explain my issue again:
I actually check windows services status but depending on the OS version or the language of the OS a service won't have the same display name / full name. So i'm actually looking for a way to check my services with: the service name or the executable name.
This way my check won't have "fake" critical because the display name is not the correct one.

**Comment by cgagnaire** [comment]
@MonkeyNab,
I totally understand your issue.
Services can't be monitored through their "Path to executable". You can only filter on the "Service name". It has never been the "Display name" or "full name" as you mentioned for our SNMP plugin.
Hopefully the "Service name" does not change depending on the OS language.

**Comment by MonkeyNab** [comment]
@cgagnaire,
Well i don't know how to do it then. Until now i used a nagios plugin called "check_snmp_win.pl" because i didn't manage to check services with this one (os::windows::snmp::plugin)
I can check with service name or full name and both doesn't work :/
- With the service name: 
` perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname myHost --snmp-community mySNMPCommunity --snmp-version SNMPVersion --critical 1: --service="nsi" --verbose
CRITICAL: Service problem 'nsi' |
Service pattern 'nsi': service list
`
- With Display Name:
`perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname myHost --snmp-community mySNMPCommunity --snmp-version SNMPVersion --critical 1: --service="Service Interface du magasin réseau" --verbose
CRITICAL: Service problem 'Service Interface du magasin réseau' |
Service pattern 'Service Interface du magasin réseau': service list
`

I'm not sure about the syntax tho :/
Do you want me to create a other issue by the way?

**Comment by cgagnaire** [comment]
@MonkeyNab,
It looks like I've been tricked by the Windows SNMP service. Actually it can be both display and service name, depending on the OS version...
So, if you want to manage multiple OS versions and language, you can use the plugin this way : 
`
perl centreon_plugins.pl --plugin=os::windows::snmp::plugin --mode=service --hostname=myHost --snmp-community='mySNMPCommunity' --snmp-version='SNMPVersion' --service='Service Interface du magasin réseau|Network Store Interface Service|^nsi$' --regexp --verbose
`

**Comment by MonkeyNab** [comment]
@cgagnaire,
Thanks! I totally forgot regexp :/
It's working now.

Thank you,
Regards

**Comment by cgagnaire** [comment]
You're welcome!
