### ISSUE TITLE
Documentation update 

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#895]
Hello,

it seems that the documentation is not up to date : 

https://documentation.centreon.com/docs/centreon-plugins/en/latest/user/guide.html#basic-usage

this documentation talk about a mode traffic, but now it is called interface.
This can cause missunderstanding of how the plugin works.

**Comment by Sims24** [comment]
Hello, 

Thanks for the feedback, you're right.

**Comment by Sims24** [comment]
@hdep if you want to provide somes example and make the associated PR you're obviously welcome :)

**Comment by hdep** [comment]
I'll check that :)

**Comment by omercier** [comment]
All modified commands have been tested and command output updated.
