### ISSUE TITLE
Why so many warning and critical options ?

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#896]
Just upgraded to a newer version of centreon-plugins. Sadly it brokes up everything on my settings because waring and critical options are different, for each mode. 
I.E : 

--plugin=os::linux::snmp::plugin 

mode : load use --warning --critical
mode interfaces use --warning-*     --critical-*
mode disk  --warning-usage  --critical-usage

But my command was like  : 

$USER1$/centreon-plugins/centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=$_SERVICEMODE$ --hostname=$HOSTADDRESS$  --snmp-version=$_HOSTSNMPVERSION$ --snmp-username=$_HOSTSNMPCOMMUNITY$ --authpassphrase=$_HOSTSNMPAUTHPASSWORD$ --authprotocol=$_HOSTAUTHPROTOCOL$ --privpassphrase=$_HOSTSNMPPRIVPASSWORD$  --privprotocol=$_HOSTPRIVPROTOCOL$ --warning $_SERVICEWARNING$ --critical $_SERVICECRITICAL$ $_SERVICEOPTS$

Is there any plan on your side to homogenize that type of options ?

**Comment by Sims24** [comment]
Hello @hdep 

Yes there is a plan. It's a huge WIP, we refactor and optimize code with some class that allow us to be more efficient in plugin dev and debug.

At the end, everything should work with --warning-something option, but of course this will always be "--warning-usage" for storage mode.

We will now add the breaking options in the release details (https://github.com/centreon/centreon-plugins/releases), but be aware that we recommand to test your setup in a centengine sandbox before applying update from the master branch of the git. 

Thanks

**Comment by hdep** [comment]
Hello,

thank you for your answer.
the issue with --warning-something option is that you can't use  the command like : 
--warning $_SERVICEWARNING$  

So I switched the command like : 
$_SERVICEWARNING$ 

but the macro is less readable.

**Comment by Sims24** [comment]
Not sur I totally understand, but there's no link between plugin options and macro name. You can e.g have --warning-usage='$_SERVICEWARNDISKSPACE$'

**Comment by hdep** [comment]
Sorry I wasn't clear. 
My objective is to have one command per plugin. 
So if I want to do this, I need to put the --warning* into a macro.

**Comment by Sims24** [comment]
Ok got it, ambitious way of thinking but prelly tough to configure an maintain  I guess. 

Sorry for the inconvenience
