### ISSUE TITLE
Plugin for TALEND components

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-plugins#9]
Talend web site gives a lot of information on metrics and resources that might be monitored on it.
Through Talend, we can get relevant controls on: CFX Services, Camel Route, ActiveMQ

Everything is described here (a free account is needed to see those information):
https://help.talend.com/display/TalendESBSystemManagementIntegrationUserGuide521EN/4.+Nagios+Integration

https://help.talend.com/display/TalendESBSystemManagementIntegrationUserGuide521EN/4.6+Resources+and+metrics+that+are+being+monitored

**Comment by florian-asche** [comment]
+1

**Comment by Sims24** [comment]
This is not a priority right now. Closing.

**Comment by Sims24** [comment]
This will probably be added before the EOY in the backlog.

We will focus on: 
- Discovery of remote engines
- Remote engine health and metrics: https://help.talend.com/r/fr-FR/Cloud/remote-engine-user-guide-linux/available-metrics-for-monitoring
- Job status https://help.talend.com/r/fr-FR/Cloud/remote-engine-user-guide-linux/job-management-logs

Those metrics can be gathered on the TMC (Talend Management Console) or for some directly on the remote engine API.
-
