### ISSUE TITLE
Can't get a single datastore with mode datastore-vm

### ISSUE THREAD

**Issue by stefanotoro** [centreon/centreon-plugins#900]
Centreon 2.18
Global Version: 20171222

Backend storage is a VMware Virtual SAN

./centreon_plugins.pl --plugin apps::vmware::connector::plugin --mode datastore-vm --connector-hostname 127.0.0.1 --vm-hostname vl022831
UNKNOWN: Can't get a single datastore. | 'max_total_latency'=1.00ms;;;0;

The problem does not exist if the storage is a VMFS

**Comment by Sims24** [comment]
Hello, 

We will dig around to check if we can have such information through the webservice. We'll update you asap

thx

**Comment by stefanotoro** [comment]
Hi,
Any news on this issue ?
Thank you

**Comment by stefanotoro** [comment]
I check when new release is notified and regularly with updated git
If i can help you with more testing just ask me
Thank you

**Comment by cgagnaire** [comment]
Hi @stefanotoro,
Would it be possible to do a remote session to test some commands on your platform?
Thanks

**Comment by stefanotoro** [comment]
Hi,
I’m sorry but this is impossible because of security constraints

Can i run commands for you in our infrastructure ?
Thank you

**Comment by stefanotoro** [comment]
Centreon 2.18.26
Global Version: 20190111

Always same problem as mentioned in march 2018.
Can I help to resolve it? Let me know if i can help you.
Thanks

**Comment by garnier-quentin** [comment]
Maybe in new release of centreon-vmware with VSAN.
