### ISSUE TITLE
[apps::protocols::http::plugin] status CRITICAL when timeout how to

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#901]
Hello,

Is there an option to have a CRITICAL status when a timeout occured with http::plugin ?

I've tried with this option : --opt-exit=critical
But it's not working.

Thanks.

**Comment by ritouret** [comment]
Hello Simon,
with --expected-string mode.

**Comment by cgagnaire** [comment]
Hi @ritouret,
The option --opt-exit is for options error only.
You can use the option --critical-status like `--critical-status='%{http_code} >= 500'` to get a CRITICAL status when a timeout occur.

**Comment by ritouret** [comment]
Just with --warning and --critical options , so basic !

**Comment by ritouret** [comment]
@cgagnaire : sorry, i've answered before i've seen your response.

the --critical-status option does not work because you do not have a return code with a timeout !
