### ISSUE TITLE
Question Cisco ASA VPN Status

### ISSUE THREAD

**Issue by jerebernard** [centreon/centreon-plugins#903]
## Question

Hello I'm trying to monitor IPSEC Tunnels on Cisco ASA and using 
```
perl centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --hostname=x.x.x.x --snmp-version=2c --snmp-community=public --mode=ipsec-tunnel --warning-*tunnels-total=0
OK: Total Tunnels : 0 - All tunnels are ok | 'total_tunnels'=0;;;0;
```
My need is : I want to get a warning if the tunnel number is egal to 0 and a OK status is the tunnel number is different of 0.

I'm looking for a good person which will have enough knowledge to get this answer.

Thanks by advance.

Jeremy

**Comment by Sims24** [comment]
Hi, 

Please use threshold like below : 

`--warning-tunnels-total=1:
`
Every value outside of the 1 --> infinite range will trigger a warning.

**Comment by jerebernard** [comment]
Thanks for this quick answer, it works
Have a nice day !!!

**Comment by Sims24** [comment]
you're welcome, thanks for using our plugin library ;)
