### ISSUE TITLE
centreon-plugins / snmp_standard / : plugin.pm is missing

### ISSUE THREAD

**Issue by GSfr94** [centreon/centreon-plugins#905]
Hello all,

plugin.pm is missing on GIT (folder centreon-plugins / snmp_standard / ).

**Comment by Sims24** [comment]
Hello, 

No that is because we made some reorganization in folder layout. 

You can find it under apps/protocols/snmp/

We will highlight such informations in the next release.

**Comment by GSfr94** [comment]
Ok, 
Thx for the  information, I'll change the commande check
