### ISSUE TITLE
Plugin Squid

### ISSUE THREAD

**Issue by jerebernard** [centreon/centreon-plugins#906]
Hello,

It's  a request for a new plugin in order to check Squid service.
Squid is really used by Network and System Admin as we web proxy and reverse proxy.

A nagios script already : [https://exchange.nagios.org/directory/Plugins/Websites%2C-Forms-and-Transactions/Squid-Web-Proxy/details]
OID are here : [https://wiki.squid-cache.org/Features/Snmp]

If there is any question please let me know.

Thanks in advance !!!

Regards,

**Comment by Sims24** [comment]
Hi, 

Couleur you please provide us an snmpwalk and also the most critical check you would like to see in the plugin ? 

Thx for shared links

**Comment by jerebernard** [comment]
Hello,

It's not an SNMP which is required but a script in order to check that is user is able to login into the web using username/Pwd and then access to a website.
It's only one check which is required in order to validate the service is fully working and a check failed means CRITICAL.

Script need severals parameters :
1.proxyport (ex : 3128)
2.proxyuser (ex : toto)
3.proxypass (password)
4. url (ex : https://www.google.com)

Goals of this 
Authenticate to the Squid web Proxy on port 3128 with login/password
and then access to internet. So ways to internet from users will be checked.

Please have a look of this script : [https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=1402&cf_id=24](url)

Thanks

**Comment by jerebernard** [comment]
Even if a script exist on Nagios as you have developped a lot of check on this GIT and I like how thinks are done here, that's why I'm asking for this plugin 👍

**Comment by Sims24** [comment]
Please use the http plugin, this actually does what you want. 

That kind of control is not specific to squid.
