### ISSUE TITLE
Add filter/exclude option to network::cisco::wlc::snmp::plugin --mode=ap-users

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#907]
Hi,

Can you please add filter option to network::cisco::wlc::snmp::plugin --mode=ap-users?
There is a option to  use --filter-counters, but that only changes what counters are shown in output. I need to exclude some parts from the check, for example I need only the total number of connected users and total number of users connected to each SSID.

**Comment by Sims24** [comment]
HI @kadrika , 

That would be a prelly tough change in the mode behaviour. 

Could you explain why you would like to exclude some of the snmp queries ? 

Regards

**Comment by kadrika** [comment]
Yes sure, it is because I have more than 1000 access points connected to that controller, so it checks all of them also, and that I do not need and want. I enabled that service, the probe load gets very hight in just few minutes:  Load average: 13.13 [52.51/4 CPUs], 26.62 [106.47/4 CPUs], 49.09 [196.36/4 CPUs]

**Comment by cgagnaire** [comment]
Hi @kadrika,
Can the option --filter-counters='^total|ssid$' match your need ?
For the load problem, it can only be fixed by redesigning the mode...

**Comment by garnier-quentin** [comment]
The option provided by Colin is working. For the load, i added an option for you: ```--ignore-ap-users```
Should be more performant.
