### ISSUE TITLE
--mode=interfaces --nagvis-perfdata

### ISSUE THREAD

**Issue by emirjonb** [centreon/centreon-plugins#909]
Hi,
I've seen some issues opened by other users regarding the Nagvis/centreon-plugins but no solution found, (ex #584 ), I try to write it there but the case was closed so I will rewrite it here:

For the moment in my environment I'm using another script (outside of centreon-plugins) for monitoring on Centreon+Nagvis, I manage to make some changes there to add some additional perf. Data as:
`nagvis_inL=5.1% nagvis_outL=4.2% nagvis_inT=5Mbps nagvis_outT=4Mbps traffic_in=5104389,9Bits/s;70000000;90000000;0;100000000 traffic_out=4190050,0Bits/s;70000000;90000000;0;100000000`
In this format the graphs on Centreon and value on Nagvis get satisfied, so nagvis uses Byte per sec (as their requirements) only if no unit is specified. if the script feed this data on the correct order is ok ex:
![graphn2](https://user-images.githubusercontent.com/14164077/37587722-61812640-2b60-11e8-9784-bb5e00bcc326.png)

Now I have discovered the  `centreon-plugins` that support a very large numbers of vendors and hopefully I don't need to manually change the OID when using the script from one vendor to another. The joy didn't last very much when I saw that Nagvis didn't like this at all :( .
I did the changes to divide by 1 as suggested on the thread #584 but to not mess up with graph on centreon, need to add a measurement unit for the graphs to be build, and nagvis to adapt.
How can we achieve same result using this script "./centreon_plugins.pl"; I think that is only needed to add first the Load in and out, than Traffic in and out on human readable units (Kbps or Mbps as shown on Status information), at this point the Nagvis is satisfied (as shown by the result of the other script)
The second part are the Traffic in and out int bps for centreon to build the graphs.

I did some changes on interfaces.pm script (line 128 I'm a newbie on perl scritps) but for the moment I can get this data on Performance Data, but I can't change the order as needed on Nagvis Load in/out, Traffic in/out, and I've ended in this situation:
`| 'nagvis_inL'=0.25%;;;; 'nagvis_inT'=4.99Mb/s;;;; 'traffic_in'=4988150bps;0:660000000;0:1800000000;0;2000000000 'nagvis_outL'=0.03%;;;; 'nagvis_outT'=592.47Kb/s;;;; 'traffic_out'=592466bps;0:1600000000;0:1800000000;0;2000000000`
![grapho](https://user-images.githubusercontent.com/14164077/37588023-46083b78-2b61-11e8-9098-46dedd918a6a.PNG)
The new metrics (nagvis*) is set to not show on Graphs but can't be hidden from Legend, the drawback is that traffic in and out is stored twice on RRD but in this way form me this is an acceptable solution.
I've tried to understand the script but the subroutines generating perfdata are to much complex for me, and I've failed very bad on all my tries. The desired output will be like this:
`| nagvis_inL=0.25% nagvis_outL=0.03% nagvis_inT=4.99Mb/s nagvis_outT=592.47Kb/s  'traffic_in'=4988150bps;0:660000000;0:1800000000;0;2000000000 'traffic_out'=592466bps;0:1600000000;0:1800000000;0;2000000000`
There would be great if Centreon [mode --nagvis-perfdata] supported Nagvis weather-map requirements to get the output as perf data and give an option to hide as metric on the Centreon graph legend. It's a big drawback on Open Source Centreon solution if the Nagvis maps are not well shown.
Thank you!
[interfaces.zip](https://github.com/centreon/centreon-plugins/files/1824516/interfaces.zip)

**Comment by emirjonb** [comment]
Does anyone know how can I achieve this? I have gone up and down over the `interface.pm` script under the `# Traffic` part but still can't change the order of output. 
A hint from the developers or someone with a little experience over Perl for where to focus on the script will be great.
Thank you!

**Comment by Sims24** [comment]
Hi, 

Not sure how we should adress this, we are actually thinking about it but we cannot guarantee that we will work really soon on this as we miss some time. 

I'll try to check this during my spare time and I'll update you. 

Thanks for using centreon-plugins ;)

**Comment by garnier-quentin** [comment]
If i understand, you want to manage centreon and nagvis. We are going to add an option to change and/or create perfdata. You coumd create your desired output.

**Comment by garnier-quentin** [comment]
Can you test with the last version ?
https://github.com/centreon/centreon-plugins/archive/master.zip

I think you need following arguments:
```
--change-perfdata=traffic,,,bps --extend-perfdata='traffic_(in|out),nagvis_$1L,percent()' --extend-perfdata='traffic_(in|out),nagvis_$1T,scale(auto)'
```

**Comment by garnier-quentin** [comment]
In centreon UI, you need to add an extra '$'. Like that: $$1

**Comment by emirjonb** [comment]
Now the command from poller work (with $$1) but the solution need a final touch. Need to reorder the output, the blue part should be on top and the red part at the bottom to be shown properly on the graph. Is this possible?

![image](https://user-images.githubusercontent.com/14164077/50840968-f71be000-1363-11e9-920b-4642c47eb68d.png)

![nagvis](https://user-images.githubusercontent.com/14164077/50840984-00a54800-1364-11e9-9e4d-6f8dc3e0c769.PNG)

**Comment by garnier-quentin** [comment]
I have a solution ;)
```
--change-perfdata=traffic,target,,bps --extend-perfdata='target_(in|out),nagvis_$1L,percent()' --extend-perfdata='target_(in|out),nagvis_$1T,scale(auto)' --extend-perfdata=target,traffic --filter-perfdata='nagvis|traffic'
```

**Comment by garnier-quentin** [comment]
Is it ok for you ?

**Comment by emirjonb** [comment]
Sorry for yesterday I couldn't continue testing. I tried now and works ok. Thank you very much!
below is the graph before and after:
![image](https://user-images.githubusercontent.com/14164077/50887226-ea929880-13f2-11e9-95ae-88c55575e40e.png)
full command for someone who will come up to this thread is: _/usr/lib/nagios/plugins/centreon-plugins/centreon_plugins.pl --plugin=network::cisco::standard::snmp::plugin --mode=interfaces --hostname=10.10.80.1 --snmp-version='2c' --snmp-community='xxx'  --interface='^outside$' --name --add-status --add-traffic --warning-in-traffic='80' --critical-in-traffic='90' --warning-out-traffic='80' --critical-out-traffic='90' --verbose --change-perfdata=traffic,target,,bps --extend-perfdata='target_(in|out),nagvis_$1L,percent()' --extend-perfdata='target_(in|out),nagvis_$1T,scale(auto)' --extend-perfdata=target,traffic --filter-perfdata='nagvis|traffic'
if applied under Centreon UI Commands the **$1** part should be changed to **$$1** and the graphs will show perfectly.

P.S: For next plugin releases it would be great if you may solve this Cosmetic issue: [;0:800000;0:900000;0;1000000.00] this part is not needed on all the nagvis variables (a reduced perfadata key), a similar output of this does the job {nagvis_inL=0.25% nagvis_outL=0.03% nagvis_inT=4.99Mb/s nagvis_outT=592.47Kb/s }
