### ISSUE TITLE
while using processcount, --process-args is limited to 128 char

### ISSUE THREAD

**Issue by NotoriousBig** [centreon/centreon-plugins#91]
Hi all, 

I'm sorry I can't help resolving but while using the following line, it returns 0 if the --process-args is 128 char or more. It works OK to 127 char. 

./centreon_plugins.pl --plugin os::linux::snmp::plugin --mode processcount --hostname mycomputer --process-name=java --process-args="-Djgroups.bind_addr=127.0.0.1 -Djava.net.preferIPv4Stack=true -Djgroups.print_uuids=true -Dcom.sun.management.jmxremote.ssl=fals" --snmp-version=2c

I tested with different processes with differents arguments I I still have the same issue. 

Not'

**Comment by garnier-quentin** [comment]
SNMP has a limit to 128 characters. https://documentation.centreon.com/docs/centreon-plugins/en/latest/user/guide.html#troubleshooting

**Comment by NotoriousBig** [comment]
ok, thanks for help

**Comment by garnier-quentin** [comment]
You're welcome.
