### ISSUE TITLE
Plugin NetApp [storage::netapp::snmp::plugin]: SNMP GET REQUEST can't get a single value

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon-plugins#910]
Hello,

I'm trying to deploy the monitoring of NetApp servers using the centreon-plugins. But when I execute the centreon-plugin for NetApp it always tell me "**SNMP GET REQUEST : Cant get a single value**".

I've got the same result with the command SNMPGET: "**SNMP GET REQUEST : Cant get a single value**".

Is the OIDs in the source code of the NetApp plugin are still valid ?

Thanks.

**Comment by Sims24** [comment]
Hi @Crash-Fox 

That's strange, sounds like a config issue on the Netapp equipment. Only issue known on our side is that some OIDs are note available when you are in a metro cluster mode. Which service/mode returns this error ?

They provide a ReST API on their last firmware and we will try to use it in a near future.

**Comment by Crash-Fox** [comment]
Hi,

Sorry for the delay of my answer. I have tested all the modes available for the plugin NetApp and none of them is working on my server NetApp. I always get the SNMP error **Can't get a single value**.

For you it's rather a configuration problem on the NetApp server than the plugin fault ? And if so what needs to be done on the server (the configuration on my NetApp server is by default).

**Comment by cgagnaire** [comment]
Hi @Crash-Fox,
Can you try to do a snmpwalk against your NetApp ?
`snmpwalk -c <community> -v <version> <ip> .1.3.6.1.4.1.789.1`
Thanks

**Comment by Crash-Fox** [comment]
Hi,

When I execute this command I get this:

**snmpwalk -c public -v 2c <IP> .1.3.6.1.4.1.789.1
==> SNMPv2-SMI::enterprises.789.1 = No Such Object available on this agent at this OID**

**Comment by cgagnaire** [comment]
Hi @Crash-Fox,
Ok so that means you have a configuration problem on your NetApp.
Can you try to configure it following their support : https://library.netapp.com/ecmdocs/ECMP1155586/html/GUID-5C3B3E54-0277-4264-8830-ABFEC559E6F0.html

**Comment by garnier-quentin** [comment]
What do you have when you do snmpwalk on following OID : .1.3.6.1.4.1 ?

**Comment by Erawor** [comment]
> What do you have when you do snmpwalk on following OID : .1.3.6.1.4.1 ?

Hi, have same problem. It's works with OID : .1.3.6.1.4.1:

`[root@centreon plugins]# snmpwalk -v 2c -c comm x.x.x.x .1.3.6.1.4.1                                                                            SNMPv2-SMI::enterprises.789.1123.2.500.1.1.0 = STRING: "NA-A"
SNMPv2-SMI::enterprises.789.1123.2.500.1.2.0 = STRING: "600a098000f9eeca000000005c78acf5"
SNMPv2-SMI::enterprises.789.1123.2.500.1.3.0 = STRING: "721905500206   "
SNMPv2-SMI::enterprises.789.1123.2.500.1.4.0 = STRING: "NETAPP  "
SNMPv2-SMI::enterprises.789.1123.2.500.1.5.0 = STRING: "INF-01-00       "
SNMPv2-SMI::enterprises.789.1123.2.500.1.6.0 = STRING: "2806"
SNMPv2-SMI::enterprises.789.1123.2.500.1.7.0 = INTEGER: 0
SNMPv2-SMI::enterprises.789.1123.2.500.1.7.0 = No more variables left in this MIB View (It is past the end of the MIB tree)
[root@centreon plugins]#`

How i can monitor with centreon plugin please ? storage::netapp::snmp::plugin
thanks

**Comment by Sims24** [comment]
Hi @Erawor 

Your netapp looks misconfigured and doesn't expose all the oids. 

> Hi @Crash-Fox,
> Ok so that means you have a configuration problem on your NetApp.
> Can you try to configure it following their support : https://library.netapp.com/ecmdocs/ECMP1155586/html/GUID-5C3B3E54-0277-4264-8830-ABFEC559E6F0.html

**Comment by Erawor** [comment]
Hi @Sims24 
Thanks for response. 
it is possible to add MIBs on my NetApp ? 
(i downloaded a MIB file from the NetApp website)
Thanks :)

**Comment by garnier-quentin** [comment]
I think it s a netapp e-series (hybrid flash). It seems you need santricity web proxy to monitor your storage with the rest api. Right now, we don t have a plugin for that

**Comment by Erawor** [comment]
> I think it s a netapp e-series (hybrid flash). It seems you need santricity web proxy to monitor your storage with the rest api. Right now, we don t have a plugin for that

Hi, Okay thank you 👍

**Comment by Crash-Fox** [comment]
Hi Thx for the reply

**Comment by garnier-quentin** [comment]
I close the ticket so.
