### ISSUE TITLE
Plugin EMC-DATADOMAIN  --mode=filesystem-usage => champ nul par 100% Used

### ISSUE THREAD

**Issue by Jordan91** [centreon/centreon-plugins#911]
Résolution du  problème en filtrant sur les filesystem. 

Par défaut dans le plugin il y a *.....dans la plupart des cas le * retourne les ci-dessous suivantes :

Le plugin interprète champ nul par 100%  ce qui génère une alerte non souhaitée

Valeur snmp centreon : 

Filesystem '/ddvar' Usage Total: 28.00 GB Used: 13.60 GB (48.57%) Free: 14.40 GB (51.43%)
Filesystem '/data: xxxxx' Usage Total: 125.45 TB Used: 89.12 TB (71.04%) Free: 36.33 TB (28.96%)
Filesystem '/data: bbbbbbb' Usage Total: 6213.35 TB Used: 6213.35 TB (100.00%) Free: 0.00 B (0.00%)
Filesystem 'dddddddd' Usage Total: 1.12 TB Used: 791.50 GB (68.74%) Free: 359.90 GB (31.26%)
Filesystem '/dmkgfdgdf' Usage Total: 29.90 GB Used: 204.80 MB (0.67%) Free: 29.70 GB (99.33%)

Valeur reelle du filesysteme

Resource                    Size GiB         Used GiB    Avail GiB    Use%    Cleanable GiB*
----------------   --------   ---------   ---------   ----   --------------
/data: xxxxx                     -              6362474.5        -              -                 -
/data: bbbbbb       128462.5           91258.5     37204.0      71%           3111.7
/dddddddd              29.5                 13.6            14.4           49%                -
/dmkgfdgdf               31.5                0.2              29.7           1%                -
----------------   --------   ---------   ---------   ----   --------------

Retour interface Centreon 

s1dd02	Filesystem-Global	CRITICAL	49m 15s	49m 15s	1m 14s	3/3 (H)	CRITICAL: Filesystem '/data: bbbbbb' Usage Total: 6309.54 TB Used: 6309.54 TB (100.00%) Free: 0.00 B (0.00%)
s2dd02	Filesystem-Global	CRITICAL	1m 19s	1m 19s	1m 19s	3/3 (H)	CRITICAL: Filesystem '/data: bbbbbb' Usage Total: 4259.01 TB Used: 4259.01 TB (100.00%) Free: 0.00 B (0.00%)

**Comment by Jordan91** [comment]
Hi,

Please find in attach the SNMPWALK .

[snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/1856176/snmpwalk.txt)

Best regards,

**Comment by cgagnaire** [comment]
Hi @Jordan91,
Can you provide us a snmpwalk with "-ObentU -Cc" options in private (cgagnaire@centreon.com) ?
Thanks.

**Comment by garnier-quentin** [comment]
Without the snmpwalk i can't correct it. i close.
