### ISSUE TITLE
apps::protocols::imap::plugin --mode=search-message unread message ?

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#915]
Hi again
I'm interested to check unread message in our mail server. I don't understand the search parameter, it only works when --search is empty.
What search it does ? object ? body ? in regex (imo no) ? unread message is possible ?
Thanks

**Comment by Sims24** [comment]
Hi @oasisck 

We use this library : perl-Net-Imap-Simple. 

You do have some example on CPAN (http://search.cpan.org/~jettero/Net-IMAP-Simple-1.2209/lib/Net/IMAP/Simple.pod#SEARCHING). 

When I read this I see that we may really enhance the plugin capabilities, we'll think about it. 

In the mean time, please confirm that you were able to do what you expect with the examples in the link above. I guess that  "UNSEEN" should do the tricks for you. 

Thnx

**Comment by oasisck** [comment]
Perfect as usual !

For me, the plugin corresponds to my expectations. Maybe a little bit information on howto use search term in the --help parameters
