### ISSUE TITLE
Plugin OS Linux local [os::linux::local::plugin] with mode traffic and ifconfig usage

### ISSUE THREAD

**Issue by NiCr42** [centreon/centreon-plugins#916]
Hello,

Plugin _os::linux::local::plugin_ with _traffic_ mode use _ifconfig_ tool and parse the ouput of  `ifconfig -a` command to retrieve data.
 _arp_, _ifconfig_, _iptunnel_, _iwconfig_, _nameif_, _netstat_, and _route_ are includes in net-tools package but that are deprecated since 2001 and replace by _iproute2_.

_netstat_ seems to be use in _connections_ mode.

Do you plan to rewrite/add new plug-ins to use _iproute2_ ?

Source : 
- https://serverfault.com/questions/458628/should-i-quit-using-ifconfig
- http://andys.org.uk/bits/2010/02/24/iproute2-life-after-ifconfig/
- https://dougvitale.wordpress.com/2011/12/21/deprecated-linux-networking-commands-and-their-replacements/

**Comment by Sims24** [comment]
Thanks for pointing this out and attaching insightful sources

As theses command are still available even deprecated, this is not a priority for us. But this is clearly an enhancement we will adress when we'll have some time. 

Do you have any problem regarding this actually ? 

Regards

**Comment by NiCr42** [comment]
Thank you for your quick answer.

net-tools is installed only so that centeron-plugins works on our servers.

This is not a problem at the moment; but installing unsupported tools could quickly become a major problem if security holes were discovered in those tools.

Note that net-tools is not installed by default on CentOS 7 (released July 7, 2014) or Debian 9 (released June 17, 2017).
