### ISSUE TITLE
apps::protocols::dhcp::plugin - CRITICAL: No DHCPOFFERs were received |

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#917]
we use latest plugins 20171222 and we are not able to monitor dhcp
```
perl /usr/lib/centreon/plugins/centreon_plugins.pl --serverip=192.168.150.100 --plugin=apps::protocols::dhcp::plugin --mode=connection --interface=eth1 --macaddr=00:50:C2:40:9C:C3
CRITICAL: No DHCPOFFERs were received |
```

If we use the standard nagios plugin seems working:
```
./check_dhcp  -s 192.168.150.100 -i eth1 -v
DHCP socket: 3
Hardware address: 00:50:c2:40:9c:c3
DHCPDISCOVER to 255.255.255.255 port 67
DHCPDISCOVER XID: 563281100 (0x2192FCCC)
DHCDISCOVER ciaddr:  0.0.0.0
DHCDISCOVER yiaddr:  0.0.0.0
DHCDISCOVER siaddr:  0.0.0.0
DHCDISCOVER giaddr:  0.0.0.0
send_dhcp_packet result: 548




recv_result_1: 300
recv_result_2: 300
receive_dhcp_packet() result: 300
receive_dhcp_packet() source: 192.168.155.1
Result=OK
DHCPOFFER from IP address 192.168.155.1 via 192.168.155.1
DHCPOFFER XID: 563281100 (0x2192FCCC)
DHCPOFFER chaddr: 0050C2409CC3
DHCPOFFER ciaddr: 0.0.0.0
DHCPOFFER yiaddr: 192.168.155.6
DHCPOFFER siaddr: 192.168.155.80
DHCPOFFER giaddr: 192.168.155.1
Option: 53 (0x01)
Option: 1 (0x04)
Option: 58 (0x04)
Option: 59 (0x04)
Option: 51 (0x04)
Option: 54 (0x04)
Lease Time: 691200 seconds
Renewal Time: 345600 seconds
Rebinding Time: 604800 seconds
Added offer from server @ 192.168.150.100 of IP address 192.168.155.6


No (more) data received (nfound: 0)
Result=ERROR
Total responses seen on the wire: 1
Valid responses for this machine: 1
DHCP Server Match: Offerer=192.168.150.100 Requested=192.168.150.100
OK: Received 1 DHCPOFFER(s), 1 of 1 requested servers responded, max lease time = 691200 sec.
```

**Comment by Sims24** [comment]
Hi @joschi99 

could you please try without --macaddr option and tell us what you get ?

**Comment by joschi99** [comment]
Hi @Sims24 

it is always the same
```
perl /usr/lib/centreon/plugins/centreon_plugins.pl --serverip=192.168.150.100 --plugin=apps::protocols::dhcp::plugin --mode=connection --interface=eth1
CRITICAL: No DHCPOFFERs were received |
```

**Comment by lolokai** [comment]
Same problem for me : if I use root user it works and if I use centreon-engine user (even if I put a setuid on the script) it do not works.

**Comment by lolokai** [comment]
More precisons :
[root@XXXXX ~]#  /usr/lib/centreon/plugins/cwrapper_perl /usr/lib/centreon/plugins/centreon_protocol_dhcp.pl --plugin=apps::protocols::dhcp::plugin --mode=connection --serverip=XXXXX --timeout=30 --interface=ens192
OK: DHCP Server found with free lease | 'time'=0.001ms;;;;
[root@XXXXX ~]# su - centreon-engine
Dernière connexion : jeudi  3 mai 2018 à 13:06:56 CEST sur pts/0
-bash-4.2$  /usr/lib/centreon/plugins/cwrapper_perl /usr/lib/centreon/plugins/centreon_protocol_dhcp.pl --plugin=apps::protocols::dhcp::plugin --mode=connection --serverip=XXXXX --timeout=30 --interface=ens192
CRITICAL: No DHCPOFFERs were received |

**Comment by joschi99** [comment]
I do not have the problem with root right (sudo ecc.). The command fails even I run it with root. I have 2 NICS (eth0 and eth1) configured, and I have to check the DHCP on eth1, where is a network with DHCP. 

Check retunrs always "No DHCPOFFERs were received"

**Comment by boogaaloo** [comment]
Same problem here : 
```
su centreon
perl centreon_plugins.pl --plugin=apps::protocols::dhcp::plugin --mode=connection --serverip=x.x.x.x --interface=ens160
CRITICAL: No DHCPOFFERs were received |
```

```
su root
perl centreon_plugins.pl --plugin=apps::protocols::dhcp::plugin --mode=connection --serverip=x.x.x.x --interface=ens160
OK: DHCP Server found with free lease | 'time'=0.001ms;;;;
```

On which specific folders or files should I set the "root rights" ?
I tried it on: /usr/lib/nagios/plugins/centreon-plugins/apps/protocols/dhcp and it did not change anything.

Thanks for your help !

**Comment by garnier-quentin** [comment]
You need to use a wrapper: https://github.com/centreon/centreon-plugins/tree/master/contrib
Otherwise it won't work with a non-root user.

**Comment by boogaaloo** [comment]
Ok. Thanks !!

**Comment by rummu666** [comment]
It seems to that the link to wrapper is 404 - page not found. Would anybody care to add the information how to use wrapper here, please.

> You need to use a wrapper: https://github.com/centreon/centreon-plugins/tree/master/contrib Otherwise it won't work with a non-root user.

**Comment by rummu666** [comment]
> It seems to that the link to wrapper is 404 - page not found. Would anybody care to add the information how to use wrapper here, please.
> 
> > You need to use a wrapper: https://github.com/centreon/centreon-plugins/tree/master/contrib Otherwise it won't work with a non-root user.

answering to myself

I created venv for my Python script compiler and installed a tool called pyinstaller. 
mkdir python-venv
cd /python-venv/
source .venv/bin/activate
pip3 install pyinstaller

Compile the Script into a Binary: .
python-vent/pyinstaller --onefile check_dhcp_relay.py

Grant Capabilities to the compiled Binary: Use setcap to grant the necessary capabilities to the binary. This allows the binary to bind to privileged ports without needing root permissions.
sudo setcap 'cap_net_bind_service=+ep' /python-venv/dist/check_dhcp_relay

Run the Binary as a Regular User: Now you can run the binary as a regular user without needing root permissions.
./check_dhcp_relay -H <host> -r <relay> -n <network> -m <mask> -t <timeout> -l <listen> -c <mac> --no-release --verbose

hope this helps somebody else whos suffering this
