### ISSUE TITLE
hardware::server::hp::proliant::snmp::plugin - (try --snmp-force-getnext option)

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#918]
Hello,

I have a  ProLiant DL360 Gen9 with iLO 2.55 and I'm getting this error:

> UNKNOWN: SNMP Table Request: problem to get values (try --snmp-force-getnext option)

Command:
`/usr/lib/centreon/plugins/centreon_hp_proliant.pl --plugin=hardware::server::hp::proliant::snmp::plugin --mode=hardware --hostname=xxx.xxx.xxx.xxx --snmp-version='2c' --snmp-community='public' --snmp-force-getnext`

The verbose output is:

> UNKNOWN: fan '0.1' status is other - fan '0.2' status is other | 'psu_power_0.1'=55W;;500;; 'psu_voltage0.1'=226V;;;; 'psu_power_0.2'=50W;;500;; 'psu_voltage0.2'=226V;;;; 'temp_0.1_ambient'=22C;;0:42;; 'temp_0.2_cpu'=41C;;0:70;; 'temp_0.3_memory'=36C;;0:89;; 'temp_0.4_memory'=37C;;0:89;; 'temp_0.7_system'=35C;;0:60;; 'temp_0.9_system'=38C;;0:105;; 'temp_0.10_powerSupply'=30C;;0:0;; 'temp_0.11_powerSupply'=30C;;0:0;; 'temp_0.12_system'=40C;;0:115;; 'temp_0.13_system'=31C;;0:115;; 'temp_0.14_system'=31C;;0:115;; 'temp_0.15_powerSupply'=40C;;0:0;; 'temp_0.16_powerSupply'=40C;;0:0;; 'temp_0.20_ioBoard'=57C;;0:100;; 'temp_0.21_ioBoard'=74C;;0:100;; 'temp_0.22_system'=56C;;0:100;; 'temp_0.23_ambient'=27C;;0:65;; 'temp_0.24_system'=30C;;0:75;; 'temp_0.25_system'=36C;;0:75;; 'temp_0.26_system'=44C;;0:90;; 'temp_0.27_ioBoard'=36C;;0:70;; 'temp_0.28_ioBoard'=36C;;0:70;; 'temp_0.30_ioBoard'=35C;;0:70;; 'temp_0.31_system'=33C;;0:75;; 'temp_0.32_system'=26C;;0:60;; 'temp_0.33_powerSupply'=31C;;0:100;;
> Product Name: ProLiant DL360 Gen9, Serial: ##########, Rom Version: P89 v1.50 (07/20/2015)
> Checking cpu
> cpu '0' [slot: 0, unit: 0, name: Intel Xeon, socket: 1] status is ok.
> Checking ide controllers
> Checking ide logical drives
> Checking ide physical drives
> Checking power converters
> Checking power supplies
> powersupply '0.1' status is ok [redundance: 3, redundant partner: 0] (status noError).
> powersupply '0.2' status is ok [redundance: 3, redundant partner: 0] (status noError).
> Checking sas controllers
> Checking sas logical drives
> Checking sas physical drives
> Checking scsi controllers
> Checking scsi logical drives
> Checking scsi physical drives
> Checking fca host controller
> Checking fca external controller
> Checking fca external accelerator boards
> Checking fca logical drives
> Checking fca physical drives
> Checking da controller
> da controller '0' [slot: 0, model: unknown] status is ok.
> Checking da accelerator boards
> da controller accelerator '0' [status: enabled, battery status: ok] condition is ok.
> Checking da logical drives
> da logical drive '0.1' [fault tolerance: mirroring, condition: ok] status is ok.
> Checking da physical drives
> da physical drive '0.0' [status: ok] condition is ok.
> da physical drive '0.1' [status: ok] condition is ok.
> Checking fans
> fan '0.1' status is other, speed is other [location: system, redundance: not redundant, redundant partner: 0].
> fan '0.2' status is other, speed is other [location: system, redundance: not redundant, redundant partner: 3].
> fan '0.3' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 4].
> fan '0.4' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 5].
> fan '0.5' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 6].
> fan '0.6' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 7].
> fan '0.7' status is ok, speed is normal [location: system, redundance: redundant, redundant partner: 0].
> Checking physical nics
> physical nic '1' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
> physical nic '2' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
> physical nic '3' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
> physical nic '4' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
> physical nic '5' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
> physical nic '6' [duplex: full, role: notApplicable, state: ok, status: ok] condition is ok.
> Checking logical nics
> logical nic '1' [adapter count: 1, description: Logical Interface for vmnic0, status: ok] condition is ok.
> logical nic '2' [adapter count: 1, description: Logical Interface for vmnic1, status: ok] condition is ok.
> logical nic '3' [adapter count: 1, description: Logical Interface for vmnic2, status: ok] condition is ok.
> logical nic '4' [adapter count: 1, description: Logical Interface for vmnic3, status: ok] condition is ok.
> logical nic '5' [adapter count: 1, description: Logical Interface for vmnic4, status: ok] condition is ok.
> logical nic '6' [adapter count: 1, description: Logical Interface for vmnic5, status: ok] condition is ok.
> Checking temperatures
> '0.1' ambient temperature is 22C (42 max) (status is ok).
> '0.2' cpu temperature is 41C (70 max) (status is ok).
> '0.3' memory temperature is 36C (89 max) (status is ok).
> '0.4' memory temperature is 37C (89 max) (status is ok).
> '0.7' system temperature is 35C (60 max) (status is ok).
> '0.9' system temperature is 38C (105 max) (status is ok).
> '0.10' powerSupply temperature is 30C (0 max) (status is ok).
> '0.11' powerSupply temperature is 30C (0 max) (status is ok).
> '0.12' system temperature is 40C (115 max) (status is ok).
> '0.13' system temperature is 31C (115 max) (status is ok).
> '0.14' system temperature is 31C (115 max) (status is ok).
> '0.15' powerSupply temperature is 40C (0 max) (status is ok).
> '0.16' powerSupply temperature is 40C (0 max) (status is ok).
> '0.20' ioBoard temperature is 57C (100 max) (status is ok).
> '0.21' ioBoard temperature is 74C (100 max) (status is ok).
> '0.22' system temperature is 56C (100 max) (status is ok).
> '0.23' ambient temperature is 27C (65 max) (status is ok).
> '0.24' system temperature is 30C (75 max) (status is ok).
> '0.25' system temperature is 36C (75 max) (status is ok).
> '0.26' system temperature is 44C (90 max) (status is ok).
> '0.27' ioBoard temperature is 36C (70 max) (status is ok).
> '0.28' ioBoard temperature is 36C (70 max) (status is ok).
> '0.30' ioBoard temperature is 35C (70 max) (status is ok).
> '0.31' system temperature is 33C (75 max) (status is ok).
> '0.32' system temperature is 26C (60 max) (status is ok).
> '0.33' powerSupply temperature is 31C (100 max) (status is ok).
> Checking ilo
> ilo status is ok [message = ].

What am I doing wrong here?

Thanks for your help!

**Comment by Sims24** [comment]
Hi, 

you may want to check --threshold-overload option. see https://github.com/centreon/centreon-plugins/issues/888

**Comment by MikeW83** [comment]
I have tried with
` --threshold-overload='fan,OK,other'`
but I'm receiving the same error
