### ISSUE TITLE
snmp.pm error

### ISSUE THREAD

**Issue by MuskratAggie** [centreon/centreon-plugins#919]
Hi there...great product!! Thank you!

Getting an error when I try to use --plugin=os::linux::snmp::plugin for any mode.

Example and error command:

./centreon_plugins.pl --plugin=os::linux::snmp::plugin --snmp-community=xxxxxxxxx --snmp-version=2 --mode=time --hostname=xxx.xxx.xxx.xxx --warning=60 --critical=120 --timezone='America/Chicago'

UNKNOWN: Undefined subroutine &SNMP::Session called at /usr/lib64/nagios/plugins/centreon-plugins/centreon/plugins/snmp.pm line 99.

I feel like it is something I'm doing/have done wrong, but not able to figure it out.

Thanks!!

**Comment by Grimblee** [comment]
Hello,

I have the same issue but with perl-SNMP installed:

> # rpm -qa | grep perl | grep -i snmp
> net-snmp-perl-5.7.2-33.el7_5.2.x86_64
> perl-Net-SNMP-6.0.1-7.el7.noarch
> perl-SNMP_Session-1.13-5.el7.noarch

But when I try to run the centreon script:
> /usr/libexec/icinga2/centreon-plugins/centreon_plugins.pl --plugin network::f5::bigip::snmp::plugin --hostname 10.0.1.8 --snmp-version v2c --snmp-community SoMeCoMuNiTy --mode failover
> UNKNOWN: Undefined subroutine &SNMP::Session called at /usr/libexec/icinga2/centreon-plugins/centreon/plugins/snmp.pm line 99. 

Any idea what this could be ? I have another host with the same setup and it works there, I'm perplex :s 

Thanks,
