### ISSUE TITLE
apps::vmware::connector::plugin - datastore-host reports "Undefined subroutine &HostVffsVolume::deserialize"

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#920]
Hello,
we use apps::vmware::connector::plugin to monitor a VMWare Infrastructure and we have a very good expierience with that. But we have now a new Infrastructure to monitor and we get this error:

```
perl /usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::vmware::connector::plugin --custommode=connector --connector-hostname=127.0.0.1 --container=default --verbose --mode=datastore-host --esx-hostname='vmware1l.dc.gvcc.net' --filter --scope-cluster='' --scope-datacenter='' --datastore-name='.*' --filter-datastore --warning=100 --critical=250

Undefined subroutine &HostVffsVolume::deserialize called at /usr/local/share/perl5/VMware/VICommon.pm line 2350.
```

Plugins version: 20171222 
VMWare Enterprise Plus 6.5

We have installed latest CES 3.4 versions and have installed also perl-VMware-vSphere.x86_64 5.1 from CES.

**Comment by cgagnaire** [comment]
Hi @joschi99,
Can you install the 6.5 perl SDK from VMware website : https://my.vmware.com/web/vmware/details?downloadGroup=VS-PERL-SDK65&productId=614
And try again :)
Thank you!

**Comment by joschi99** [comment]
hi @cgagnaire,
can I make a upgrade of the VMWare Perl SDK or I need to uninstall the old version 5.1 installed by CES 3.4 rpm?
Thanks

**Comment by cgagnaire** [comment]
Hi @joschi99,
Yes you can by lauching the installation script.

**Comment by joschi99** [comment]
hi @cgagnaire 
with VMWare Perl SDK 6.5 the checks will working fine. But we need to uninstall the old SDK installed by rpm package from CES 5.4, otherwise some old perl library is still there and the check will fail.

**Comment by cgagnaire** [comment]
Ok, thanks for the feedback.
