### ISSUE TITLE
apps::elasticsearch::restapi::plugin - new mode to check x-pack expire date

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#923]
it would be very nice the extent the plugin for elasticsearch to check the expire date for the x-pack

**Comment by Sims24** [comment]
hi @joschi99 

what information would you like to see in short/long output regarding following link : https://www.elastic.co/guide/en/elasticsearch/reference/current/get-license.html

Thanks

**Comment by joschi99** [comment]
hi @Sims24 

it would be fine to see:
* expire_date
* status
* issued_to
* type

Do you want to add or delete some other info?

Thanks

**Comment by Sims24** [comment]
Ok great, we'll do it prelly soon I guess. About informations that is roughly what I've expected. 

 I let you know when you may help us to validate it.

**Comment by joschi99** [comment]
Great. No problem for testing and validating. Let me know when you are ready.

**Comment by cgagnaire** [comment]
Hi @joschi99,
I did this mode.
The plugin has been refactored and move to the database tree.

**Comment by joschi99** [comment]
Hi @cgagnaire,
thank you very much.
