### ISSUE TITLE
apps::protocols::imap::plugin mail lost

### ISSUE THREAD

**Issue by oasisck** [centreon/centreon-plugins#924]
Hello
Since I use this plugin, we lost many mails in our mailbox (exchange from a provider) and I didn't use once the parameter --delete
I made some test in a folder Test and all was OK.
I use this plugin to check UNSEEN mail in INBOX
`centreon_plugins.pl --plugin=apps::protocols::imap::plugin --mode=search-message --ssl --hostname=$HOSTADDRESS$ --username=$USER6$ --password=$USER7$ --search=UNSEEN --warning=$ARG1$ --critical=$ARG2$`
No folder parameter because it's INBOX by default.

**Comment by Sims24** [comment]
Hi, 

Cannot reproduce this on a gmail account. Could you please double check with your provider ?

No reason to delete the email if the option is not set..

**Comment by garnier-quentin** [comment]
If you have that problem again, please reopen it. We don't reproduce it.
