### ISSUE TITLE
Password field in host template not working

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#925]
Hello guys,

a new Problem occured. I have created a host template few weeks ago with following macros:
![image](https://user-images.githubusercontent.com/35097389/37953529-76e14ae4-31a3-11e8-9715-069dabd8d228.png)

Yesterday I created another template with the same macros and when I check the command which should use the password it's clearly showing up. The template which is a few weeks older works perfect and the password in the check command shows up with '***'.

Anybody the same problem?

Thank you very much.
Best reagrds, Mike

**Comment by Sims24** [comment]
Hello @MikeW83 

Did you use the duplicate function ? If so, that might be the point. Anyway, this is rather a Centreon issue and I think you will have a better answer on its dedicated github ;)

**Comment by MikeW83** [comment]
I have tried both and also change the name to be sure that there are no duplicates in the database. Ok, thank you. I will open the issue on the other side ;-)
