### ISSUE TITLE
network::cisco::standard::snmp::plugin --mode=traffic perfdata for nagvis weathermap 

### ISSUE THREAD

**Issue by hdep** [centreon/centreon-plugins#93]
Hello,

with : --plugin=network::cisco::standard::snmp::plugin --mode=traffic  traffic perfdata is like this :
'traffic_in'=52879492.77b/s;;;0;1000000000 'traffic_out'=14031464.21b/s;;;0;1000000000

Is there a way to make this output working with nagvis 1.7 ?

According to Nagvis website output needed is :

Needed perfdata format
"
The weathermap lines do not require a specific Nagios plugin. Only the provided performance format needs to match one of the cases below:

Percentage usage: four perfdata sets. While the first two sets provide the percentage usage and the second two sets provide the usage in bytes per sec.
One example: inUsage=21103.42%;85;98 outUsage=226363.55%;85;98 inBandwidth=105.52MBs outBandwidth=212.22MBs.
Byte rate usage: needs at least two perfdata sets with the labels "in" and "out" with an empty UOM. It uses the current value and the maximum value to calculate the current percentage usage. The current value should be given as byte rate. The maximum value should provide the network interface bandwidth as bytes per seconds.
One example: in=7196.50566429;;;0;1250000.0 inucast=11.6273564992;;;; innucast=0.017617206817;;;; indisc=0.0;;;; inerr=0.0;0.01;0.1;; out=4044.9635368;;;0;1250000.0 outucast=12.1734899105;;;; outnucast=0.0;;;; outdisc=0.0;;;; outerr=0.0;0.01;0.1;; outqlen=0;;;;."

**Comment by garnier-quentin** [comment]
Hi,

Already had a post about it: https://github.com/centreon/centreon-plugins/issues/89
I'll try to put it in new mode 'interfaces'.

**Comment by garnier-quentin** [comment]
I'm going to set an option for nagvis perfdata. I'll do the second: 'in' and 'out' with empty uom and 'bytes per seconds' (according to me should be 'bits par seconds'. Whatever).
