### ISSUE TITLE
[network::f5::bigip::snmp::plugin] virtualserver-status

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#930]
Hello,

There is a bad character for in front of the virtual servers name in short and long outputs.

There is no problems for the list-virtualservers mode.

See my email @cgagnaire 

Thanks

**Comment by cgagnaire** [comment]
Fixed with https://github.com/centreon/centreon-plugins/pull/932

**Comment by ritouret** [comment]
Hello Colin,

How can i add this branch to the previous we made yesterday ?

Thanks

**Comment by cgagnaire** [comment]
Hi @ritouret,
You can't easily. @Sims24 already merged this one, hope he will merge https://github.com/centreon/centreon-plugins/pull/931 soon :)

**Comment by Sims24** [comment]
@cgagnaire please see my comment on your PR ;)
