### ISSUE TITLE
[Windows::SNMP::plugin] - Mode SWAP contains sum of physical and virtual memory

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon-plugins#935]
on Windows server, the swap mode return sum of physical memory and virtual memory.
Here is a W2012R2 64bits server but it similar for other releases

![image](https://user-images.githubusercontent.com/8720203/38271914-07735be4-3788-11e8-9404-a59a731f0535.png)

and on centreon it indicates this:

![image](https://user-images.githubusercontent.com/8720203/38271971-347ab0b0-3788-11e8-97cc-676ee3806c38.png)

I use theses commands for RAM and SWAP:
`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=memory --hostname=X.X.X.X --snmp-version='2c' --snmp-community='xxxx' --snmp-timeout=10 --warning-memory='98' --critical-memory='99'`

`/usr/lib/centreon/plugins/centreon_windows_snmp.pl --plugin=os::windows::snmp::plugin --mode=swap --hostname=X.X.X.X --snmp-version='2c' --snmp-community='xxxx' --snmp-timeout=10 --warning='' --critical=''`

Have you an idea about this issue?
thanks

**Comment by Sims24** [comment]
Hi @cmeschin, 

This is a know bug and we will soon provide some workaround as Microsoft does not seems to want to fix this on its side ... 

We are discussing this here, feel free to add your toughts ;) https://github.com/centreon/centreon-plugins/pull/929

**Comment by cmeschin** [comment]
Hi,
Ok, I've seen #928 but not this one.
Thanks.
