### ISSUE TITLE
[Modbus Plugin] Perf Data format

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon-plugins#939]
Hi,

How can I set critical threshold using modbus plugin?
I am getting this error with my attempt:

![image](https://user-images.githubusercontent.com/25208457/38371446-d177f108-38c2-11e8-9b4d-0c99c8a83b77.png)

**Comment by Sims24** [comment]
Hi, 

Like described in --help :  
```

=item B<--warning-*>
Warning threshold (can be 'unique' or 'global')
(Override config if set)
=item B<--critical-*>
Critical threshold (can be 'unique' or 'global')
(Override config if set)
``` 

`--critical-global or --critical-unique`

**Comment by kozfelipe** [comment]
How can I set it in config json file?

**Comment by Sims24** [comment]
You cannot actually, 

would be --warning-metric to set a threshold for each part of selection. 

would be --warning-global-temperatura for the virtualcurve.

.. but through command-line.

**Comment by kozfelipe** [comment]
@Sims24 thank you

I though I could since help describes it override config

**Comment by Sims24** [comment]
Hum, I thought it was defined on modbus side but seems unreal. Did you try something like this : 

```
   "virtualcurve":{
      "temperatura":{
          "unit": "°C",
          "aggregation": "avg",
          "critical": "10"
      }
   }
```

Thanks

**Comment by kozfelipe** [comment]
@Sims24 excelent
It does work. Thank you again

**Comment by kozfelipe** [comment]
perf data format does not generate graphs

![image](https://user-images.githubusercontent.com/25208457/38381828-64fb3a78-38de-11e8-9344-690e16a02f1b.png)

**Comment by kozfelipe** [comment]
it turns out the special characters from unit were preventing centreon to graph it

**Comment by kozfelipe** [comment]
Hi there,

I reopened this issue to understand how can I set perfdata to alarm below critical value instead of above

**Comment by Sims24** [comment]
Hi, like every other check. Like 10: to trigger an alarm when value drops below 10. Nope?

**Comment by kozfelipe** [comment]
so in the above example, should I replace `"critical": 110` for `"critical": 110:` ?
