### ISSUE TITLE
[snmp_standard::mode::cpudetailed]Question about CPU Detailed values

### ISSUE THREAD

**Issue by anthoc** [centreon/centreon-plugins#947]
Hello,

We currently encounter some network storage issues with our virtual machines (HD on SAN), and we are using the cpu-detailed plugin in order to detect problems. 

When some issues occur, the IOWait value on the system increase drasticly.
For example wait value in top and vmstat command change from 0 to 100 in a second while cpu idle value change from 90 to 0. 
We can see this using nmon too, who is running on the systems. 

But in centreon with the centreon plugins the cpu-detailed is not showing exactly the same value. For example we had the problem this afternoon, the wait value in top was 100% and wait value in centreon through cpu detailed plugin was only 25%. There is a correlation for sure but there's a big difference. 

I made some reseach and it seems that the plugin use SNMP CPU Raw Counters. 

What is the difference between the value returned by the plugin and the value returned via top/vmstat commands ? I tried to understand all day but i have no clues.

Thank You !

**Comment by Sims24** [comment]
Hi @anthoc 

My first thought would be that you have a 4 core server and that you see 100% of iowait on a single cpu when detailed in top. 

The kernel reports 25% globally because of the 3 other available CPUs. If your application is not -full- multi-thread architecture, that's probably the point. 

25% of iowait on a 4 core CPU means that one of your CPU is full time waiting for I/O operations, that's huge.

I cannot see any other reason appart those described above. 

Regards,

**Comment by Sims24** [comment]
I think that might be the check interval. Looks like you have a one minute resolution here if I understand correctly the axis. 

We check every five minute and made a computation regarding the chec interval. So it could be possible to find such value between 06:00 and 06:05 I guess ..

**Comment by anthoc** [comment]
> We check every five minute and made a computation regarding the chec interval. So it could be possible to find such value between 06:00 and 06:05 I guess ..

I think this is the information I needed to understand, I supposed the value was the "real time" wait percentage and wasn't related to the check_interval (because It seems that a lot of plugin are working like this, but I may be mistaken). 

Thank you again @Sims24 .

**Comment by Sims24** [comment]
you're welcome ! 

Thanks for contributing to centreon plugins

**Comment by anthoc** [comment]
Excuse me, just an additionnal question : How do you compute the value displayed using the check interval ? Don't you need more than one value to make an average on the 5 minute period ? (Maybe the OID value is already an average value?)

Thank You

**Comment by Sims24** [comment]
We get the delta of the cpu time used for each cpu counter (cf http://www.debianadmin.com/linux-snmp-oids-for-cpumemory-and-disk-statistics.html) and compute it regarding the number of elapsed seconds between two checks. 

I guess that if you try to check this every minute you could spot your 100% cpu wait peak. But warning this will generate some load and require some disk space and disk io to use an 1 minute check interval for this kind of check. 

Thanks
