### ISSUE TITLE
Problem KAV (apps::antivirus::kaspersky::snmp::plugin)

### ISSUE THREAD

**Issue by Slayder66** [centreon/centreon-plugins#950]
Hello,
I have a problem with the new kaspersky snmp, can you help me?

```
$USER1$/centreon-plugins/centreon_plugins.pl
--plugin=apps::antivirus::kaspersky::snmp::plugin
--mode=protection
--hostname=$HOSTADDRESS$
--snmp-version='2c'
--snmp-community='public'
```

Result Centreon (2.8.20) :

```
  | UNKNOWN: SNMP GET Request : Cant get a single value.
-- | --

```

**Comment by Sims24** [comment]
Hi @Slayder66 

You should probably enable SNMP oid through Karspesky admin kit.

**Comment by Slayder66** [comment]
at the security center kaspersky?
I can not find, on windows server 2012 r2 kaspersky server, snmp service is configured correctly

**Comment by omercier** [comment]
Hi @Slayder66,
[This article](https://support.kaspersky.com/2811) states that if the SNMP Service is previously installed on your Windows server, then the KAV Administration kit installator can install the SNMP agent:
"After SNMP support has been installed, you can install an Administration Server with the component SNMP Agent. You will find the MIB files required for monitoring inside SNMP subfolder in Kaspersky Administration Kit installation folder."
Maybe you installed SNMP Service after the KAV setup? or omitted the "SNMP agent" option?
