### ISSUE TITLE
Cisco ASA plugin configuration help

### ISSUE THREAD

**Issue by jerebernard** [centreon/centreon-plugins#951]
Hello,

I need some help to use the Cisco ASA plugin in order to monitor the failover.
Goal is to see an alarm if the active unit numbers is different than 2. It meens we lost a device.
The second things is to get a critical alarm if we got a failover to the secondary device.

Result without filter when a failover happened : 
perl centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --mode=failover --hostname=xxxx --snmp-version=2c --snmp-community=public 
OK: Active units : 2 - Primary unit is 'standby' [details: 'Standby unit'], Secondary unit is 'active' [details : 'Active unit'] | 'active_units'=2;;;0;2

To monitor active units numbers different of 2 :  I think it's this : 
perl centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --mode=failover --hostname=xxx --snmp-version=2c --snmp-community=public --warning-*active_units=2:

To monitor a failover to secondary unit I don't know how to do : 
perl centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --mode=failover --hostname=xxx --snmp-version=2c --snmp-community=public xxxxxxx

Thanks in  advance

regards

**Comment by Pitch1** [comment]
hello have you found solution to monitor the  failover between the primary and secondary 
thank you

**Comment by garnier-quentin** [comment]
What do you want to monitor exactly @Pitch1 ?

**Comment by Pitch1** [comment]
i have two units one primary and a standby 
i want an alerte when the switch from the primary to secondary and invertred

**Comment by Pitch1** [comment]
./centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --mode=failover --hostname=X.X.X.X. --snmp-community=****** --critical-status='%{primaryState} = active'

Result 
OK: Active units : 2 - Primary unit is 'active' [details: 'Active unit'], Secondary unit is 'standby' [details : 'Standby unit'] | 'active_units'=2;;;0;2

**Comment by Pitch1** [comment]
i want a check when the role is switched have an alerte
i dont khnow if am clear :)

**Comment by garnier-quentin** [comment]
You can like that:
```
--critical-status='%{primaryStateLast} ne %{primaryState} or %{secondaryStateLast} ne %{secondaryState}'
```

**Comment by jerebernard** [comment]
On my side I configured this as a command :
`centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --mode=failover --hostname=$HOSTADDRESS$ --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --warning-status='%{secondaryState} eq "active"' --warning-*active-units=2:`

and this is the result for a host : 
OK: Active units : 2 - Primary unit is 'active' [details: 'Active unit'], Secondary unit is 'standby' [details : 'Standby unit']

**Comment by Pitch1** [comment]
thank you jerbrnard
Garnier i tested with you solution and it's ok thank you 
 ./centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --mode=failover --hostname=X.X.X.X --snmp-community=*****  --critical-status='%{primaryStateLast} ne %{primaryState}'

OK: Active units : 2 - Primary unit is 'active' [details: 'Active unit'], Secondary unit is 'standby' [details : 'Standby unit'] | 'active_units'=2;;;0;2

**Comment by garnier-quentin** [comment]
You're welcome @Pitch1

**Comment by Pitch1** [comment]
I tried to have critical stat and it works like that 
./centreon_plugins.pl --plugin=network::cisco::asa::snmp::plugin --mode=failover --hostname=X.X.X.X. --snmp-community=******   --critical-status='%{primaryStateLast} ne %{secondaryStateLast}'

CRITICAL: Primary unit is 'active' [details: 'Active unit'], Secondary unit is 'standby' [details : 'Standby unit'] | 'active_units'=2;;;0;2

**Comment by Pitch1** [comment]
have a nice day :)
