### ISSUE TITLE
perl-Redis and perl(IO::Socket::Timeout) issue on el7

### ISSUE THREAD

**Issue by tanguyvda** [centreon/centreon-plugins#953]
Hello there,

on el7 when you install centreon-plugin-Applications-Redis-Cli.noarch you have perl-Redis as a dependency (v1.978) which requires perl(IO::Socket::Timeout) >= 0.22 we need to package it too 

Regards

**Comment by cgagnaire** [comment]
Hey @tanguyvda,
I think you're mistaking, you should open this issue on the packaging github.
And just for information, for people using our pack, it is clearly said to install perl-Redis and its dependencies from EPEL repository : 
_The plugin is using the perl-Redis library. To install it, you will need the EPEL repository :
    # yum install epel-release
    # yum install perl-Redis
    # yum remove epel-release
This library installs 2 dependencies : perl-IO-Socket-Timeout and perl-PerlIO-via-Timeout._
