### ISSUE TITLE
[hardware::ups::apc] sensors mode not working

### ISSUE THREAD

**Issue by Psych0meter** [centreon/centreon-plugins#957]
Hello,

In hardware::ups::apc::snmp::mode::sensors, there is a call to hardware::ups::apc::snmp::mode::components, but components folder does not exists, so the probe isn't working :

UNKNOWN: Cannot load module 'hardware::ups::apc::snmp::mode::components::sensor'.

Regards,

**Comment by cgagnaire** [comment]
Hi @Psych0meter,
The module is directly on the sensors.pm module.
I just tested it with both project and fatpacked plugins on el6 and el7 and it works well.
What is your environment setup (OS, perl version,...) ?

**Comment by Psych0meter** [comment]
Hello,

In sensors.pm, the call line 45 doesn't exist :

$self->{components_path} = '**hardware::ups::apc::snmp::mode::components**';

I've installed the ces-plugin RPM ces-plugins-Hardware-Dell-TL2000-Snmp.noarch v2.1-1, RHEL6

Regards,

**Comment by Psych0meter** [comment]
I've tried to split the .pm file, but it still not working.
Maybe it's my perl version :

perl -v
This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

Red Hat Enterprise Linux Server release 6.9 (Santiago)

Regards,

**Comment by cgagnaire** [comment]
You're using an old package, I assume you're on a previous 2.8 version of Centreon ?
You should try cloning the centreon-plugins project and test the command line in it.

Perl version looks good to me.

**Comment by Sims24** [comment]
Hello,

This is rather a packaging issue, you should use centreon-support to ask about such things. 

Regards
