### ISSUE TITLE
Centreon Check: DB-Partitioning 

### ISSUE THREAD

**Issue by Meistercoach83** [centreon/centreon-plugins#962]
Hi, I´d like to check my centreon database with the plugin pack but there´s an error with the Partitioning Check:

UNKNOWN: Couldn't get partition infos for table 'centreon_storage.data_bin' - Couldn't get partition infos for table 'centreon_storage.logs' - Couldn't get partition infos for table 'centreon_storage.log_archive_service' - Couldn't get partition infos for table 'centreon_storage.log_archive_host

What am I doing wrong?
Here´s the complete command:

/usr/lib/centreon/plugins//centreon_centreon_database.pl --plugin=database::mysql::plugin --dyn-mode=apps::centreon::sql::mode::partitioning --host='172.16.123.58' --username='centreon' --password='**********' --tablename='centreon_storage.data_bin' --tablename='centreon_storage.logs' --tablename='centreon_storage.log_archive_service' --tablename='centreon_storage.log_archive_host' --warning='7:' --critical='3:'

**Comment by cgagnaire** [comment]
Hi @Meistercoach83,
It looks like your database is not partitioned.
Can you execute the following command and look at the "Create_options" directive : 
```
MariaDB [centreon_storage]> show table status like 'data_bin'\G
*************************** 1. row ***************************
           Name: data_bin
         Engine: InnoDB
        Version: 10
     Row_format: Compact
           Rows: 108545
 Avg_row_length: 65
    Data_length: 7077888
Max_data_length: 0
   Index_length: 3129344
      Data_free: 8388608
 Auto_increment: NULL
    Create_time: 2018-04-23 04:00:02
    Update_time: NULL
     Check_time: NULL
      Collation: utf8_general_ci
       Checksum: NULL
 Create_options: partitioned
        Comment:
1 row in set (0.00 sec)
```

**Comment by Meistercoach83** [comment]
The create_options value is empty.. so what can i do now?

**Comment by Sims24** [comment]
Hi @Meistercoach83 

If your database is not partitioned then you do not have to check it, but you should always prefer to have partitioning on data_bin and logs table. 

Just to be sure it's not specific to your database, could you confirm that you cannot see a lot of part files in your /var/lib/mysql/centreon_storage/ directory like in the example below : 

```
[root@centreon-centos7 ~]# ll /var/lib/mysql/centreon_storage/data_bin*
[...]
-rw-rw---- 1 mysql mysql 15728640 25 avril 23:59 /var/lib/mysql/centreon_storage/data_bin#P#p20180426.ibd
-rw-rw---- 1 mysql mysql 16777216 26 avril 23:59 /var/lib/mysql/centreon_storage/data_bin#P#p20180427.ibd
-rw-rw---- 1 mysql mysql 16777216 28 avril 00:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180428.ibd
-rw-rw---- 1 mysql mysql 16777216 28 avril 23:59 /var/lib/mysql/centreon_storage/data_bin#P#p20180429.ibd
-rw-rw---- 1 mysql mysql 16777216 29 avril 23:59 /var/lib/mysql/centreon_storage/data_bin#P#p20180430.ibd
-rw-rw---- 1 mysql mysql 14680064 30 avril 17:59 /var/lib/mysql/centreon_storage/data_bin#P#p20180501.ibd
-rw-rw---- 1 mysql mysql   114688 22 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180502.ibd
-rw-rw---- 1 mysql mysql   114688 23 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180503.ibd
-rw-rw---- 1 mysql mysql   114688 24 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180504.ibd
-rw-rw---- 1 mysql mysql   114688 25 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180505.ibd
-rw-rw---- 1 mysql mysql   114688 26 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180506.ibd
-rw-rw---- 1 mysql mysql   114688 27 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180507.ibd
-rw-rw---- 1 mysql mysql   114688 28 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180508.ibd
-rw-rw---- 1 mysql mysql   114688 29 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180509.ibd
-rw-rw---- 1 mysql mysql   114688 30 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#p20180510.ibd
-rw-rw---- 1 mysql mysql   114688 30 avril 04:00 /var/lib/mysql/centreon_storage/data_bin#P#pmax.ibd

```

**Comment by cgagnaire** [comment]
Refer to this documentation : https://documentation.centreon.com/docs/centreon/en/2.8.x/administration_guide/partitioning/index.html
