### ISSUE TITLE
os::linux::snmp::plugin --mode=inodes

### ISSUE THREAD

**Issue by cemir** [centreon/centreon-plugins#97]
Hi,

would it be possible to add an option to ignore some filesystems ?
There is an option to filter on name but not to ignore on names (like grep -v) or did I miss something?

exemple : 

```bash
perl centreon_plugins.pl --plugin=os::linux::snmp::plugin --mode=inodes --hostname=myserv --snmp-version=2c --snmp-community=mycomm --warning 80 --critical 90 --name --regexp --diskpath=/proc 
```
will give the inode usage  for /proc, but i want to ignore /proc (and a couple of others filesystems) because inode on those filesystems are not revelent (df -ih show no inode, centreon_plugins.pl shows inodes used @100%, so the check will alwas be in CRITICAL)

Thanks

**Comment by garnier-quentin** [comment]
You can use exclude regexp like that:
--name --regexp --diskpath='^(?!(/proc)$)'

Is it ok ?

**Comment by cemir** [comment]
Hi,

thanks for the answer, this works pretty well

**Comment by garnier-quentin** [comment]
You're welcome. thanks to use it.
