### ISSUE TITLE
Plugin for Watchguard firewall

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#98]
Hi,

Can you please create a plugin for WatchGuard firewall? If you need, I can test and also send you snmpwalk's.

**Comment by garnier-quentin** [comment]
Yes you can send me the walk and the mib.

**Comment by Gimli95** [comment]
Hello,

Looking just like kadrika to monitor my Watchguard firewall.
If your proposal is still ok, here's the MIB.

Thank you

[IPSEC-ISAKMP-IKE-DOI-TC.txt](https://github.com/centreon/centreon-plugins/files/388592/IPSEC-ISAKMP-IKE-DOI-TC.txt)
[WATCHGUARD-CLIENT-MIB.txt](https://github.com/centreon/centreon-plugins/files/388593/WATCHGUARD-CLIENT-MIB.txt)
[WATCHGUARD-CLUSTER-STATUS-MIB.txt](https://github.com/centreon/centreon-plugins/files/388596/WATCHGUARD-CLUSTER-STATUS-MIB.txt)
[WATCHGUARD-INFO-SYSTEM-MIB.txt](https://github.com/centreon/centreon-plugins/files/388597/WATCHGUARD-INFO-SYSTEM-MIB.txt)
[WATCHGUARD-IPSEC-ENDPOINT-PAIR-MIB.txt](https://github.com/centreon/centreon-plugins/files/388598/WATCHGUARD-IPSEC-ENDPOINT-PAIR-MIB.txt)
[WATCHGUARD-IPSEC-SA-MON-MIB-EXT.txt](https://github.com/centreon/centreon-plugins/files/388599/WATCHGUARD-IPSEC-SA-MON-MIB-EXT.txt)
[WATCHGUARD-IPSEC-TUNNEL-MIB.txt](https://github.com/centreon/centreon-plugins/files/388600/WATCHGUARD-IPSEC-TUNNEL-MIB.txt)
[WATCHGUARD-POLICY-MIB.txt](https://github.com/centreon/centreon-plugins/files/388594/WATCHGUARD-POLICY-MIB.txt)
[WATCHGUARD-PRODUCTS-MIB.txt](https://github.com/centreon/centreon-plugins/files/388595/WATCHGUARD-PRODUCTS-MIB.txt)
[WATCHGUARD-SMI.txt](https://github.com/centreon/centreon-plugins/files/388601/WATCHGUARD-SMI.txt)
[WATCHGUARD-SYSTEM-CONFIG-MIB.txt](https://github.com/centreon/centreon-plugins/files/388602/WATCHGUARD-SYSTEM-CONFIG-MIB.txt)

[WATCHGUARD-SYSTEM-STATISTICS-MIB.txt](https://github.com/centreon/centreon-plugins/files/388603/WATCHGUARD-SYSTEM-STATISTICS-MIB.txt)

**Comment by garnier-quentin** [comment]
Also need a complete snmpwalk.

**Comment by Gimli95** [comment]
Thanks for your feedback.
I have the latest version of centreon free version.
I'm going on holiday tonight but I try to follow it, anyway I would do you a return and you already remerci much.
PJ, the snmpwalk.
Thanks again.
[watchguard-snmpwalk.txt](https://github.com/centreon/centreon-plugins/files/388783/watchguard-snmpwalk.txt)

**Comment by kadrika** [comment]
And if you need the new plugin to be tested, I can do it any time :)

**Comment by garnier-quentin** [comment]
Tell me if the following modes would be ok for you:
* 'interfaces' (standard mode)
* 'hardware' (standard with 'hardwaredevice')
* 'storage' (standard)
* 'cpu': wgSystemCpuUtil1, wgSystemCpuUtil5, wgSystemCpuUtil15
* 'system': wgSystemCurrActiveConns, wgSystemTotalSendBytes, wgSystemTotalRecvBytes
* 'cluster-status': wgClusterEnabled, wgFirstMemberSystemHealth, wgFirstMemberHardwareHealth, ...

For 'cluster-status', i don't know what are the possible values for wgFirstMemberHardwareHealth, wgFirstMemberHardwareHealth, wgFirstMemberMonitorPortHealth. Do you know what the integer value means ?

I can't find a status for tunnels. I have stats. Do you find it ? 

Eventually, in your snmpwalk, there is nothing about the entreprise mib.

**Comment by kadrika** [comment]
Those will be good at first :)
Do you need one more snmpwalk?

**Comment by garnier-quentin** [comment]
yes i need it. Because the walk is not complete.

**Comment by Gimli95** [comment]
Hello,

I am writing from my vacation, and I'm not connected often to answer.

The following information will be OK:

'Interfaces' (standard mode)
'Hardware' (standard with 'hardwaredevice')
'Storage' (standard)
'Cpu': wgSystemCpuUtil1, wgSystemCpuUtil5, wgSystemCpuUtil15
'System': wgSystemCurrActiveConns, wgSystemTotalSendBytes, wgSystemTotalRecvBytes

Thank you for your work.

Have a good day

**Comment by Gimli95** [comment]
Hello,
I come back from holiday and I hope yours is also fine.

Regarding the plugin, you need other things? how can I integrate it into centreon?

Thank you very much for your help.

**Comment by Gimli95** [comment]
Hello,

Do you have a new for me ?
Do you need other things ?

Thanks

**Comment by garnier-quentin** [comment]
It's ok. I only need time ;)

**Comment by Gimli95** [comment]
Thank you very much,
This is my side eager talking.

**Comment by m4gn3to** [comment]
Thanks in advance.

I'm interested too, I have a cluster, so if you need some info about it you can ask.

**Comment by TontonLud** [comment]
Traffic by policy would be very usefull too, see SNMPv2-SMI::enterprises.3097.4.2.2.1.x
[snmpwalk-.1.txt](https://github.com/centreon/centreon-plugins/files/571211/snmpwalk-.1.txt)

**Comment by garnier-quentin** [comment]
For the cluster, i need a snmpwalk for following branch @m4gn3to: .1.3.6.1.4.1.3097.6.6

**Comment by Gimli95** [comment]
Thanks
I test it

**Comment by m4gn3to** [comment]
Sorry for the delay, I get the mail, but I've forgotten ... Sorry

Here you have the walk:
snmpwalk -v2c -cpublic 192.168.x.x .1.3.6.1.4.1.3097.6.6
SNMPv2-SMI::enterprises.3097.6.6.1.0 = INTEGER: 1
SNMPv2-SMI::enterprises.3097.6.6.2.0 = STRING: "80DF030C####" -> Serial Number
SNMPv2-SMI::enterprises.3097.6.6.3.0 = INTEGER: 2
SNMPv2-SMI::enterprises.3097.6.6.4.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3097.6.6.5.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3097.6.6.6.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3097.6.6.7.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3097.6.6.8.0 = STRING: "80DF0308#####" -> Serial Number
SNMPv2-SMI::enterprises.3097.6.6.9.0 = INTEGER: 3
SNMPv2-SMI::enterprises.3097.6.6.10.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3097.6.6.11.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3097.6.6.12.0 = INTEGER: 100
SNMPv2-SMI::enterprises.3097.6.6.13.0 = INTEGER: 100

**Comment by Vidark-Wyrd** [comment]
Hello,
I know this issue is closed from a while. But I will be very thankfull for a "cluster" mode.
I just see one of my customer have a problem with his Watchguard cluster.
Thank you a lot for your work with centreon-plugin.
Have a nice day.

**Comment by garnier-quentin** [comment]
Please open a new issue with mib files and a full snmpwalk of the following branch: .1.3.6.1.4.1.3097
