### ISSUE TITLE
Wrong OID in hirschmann switch

### ISSUE THREAD

**Issue by Infopromt** [centreon/centreon-plugins#982]
In file  psu.pm line 35
the OID .1.3.6.1.4.1.**2352**.2.4.1.2.1.2 in not a hirshmann OID (248)
I've test with .1.3.6.1.4.1.248.14.1.2.1.3.1 and it's correct

**Comment by cgagnaire** [comment]
Hi @Infopromt,
Thanks for the feedback!

**Comment by Sims24** [comment]
Closed by https://github.com/centreon/centreon-plugins/pull/985
