### ISSUE TITLE
os::windows::snmp::plugin is giving me negative value

### ISSUE THREAD

**Issue by MikeW83** [centreon/centreon-plugins#983]
Hello community,

this is my command:
```
/usr/lib/centreon/plugins/centreon_windows_snmp.pl
	--plugin=os::windows::snmp::plugin
	--mode=storage
	--hostname=xxx.xxx.xxx.xxx
	--snmp-version=2c
	--snmp-community=public 
	--storage '2'
	--display-transform-src='^(..).*'
	--display-transform-dst='$1'
	--warning-usage='80'
	--critical-usage='90'
```

And this is the result:

> skipping storage 'D:': total size is <= 0 (-15183382585344)

How can I fix this? It only happens with one (!) service. Also deleting and recreating the service doesn't resolve this issue.

Thank you!

**Comment by MikeW83** [comment]
I have done a snmpwalk with this result:

> HOST-RESOURCES-MIB::hrMemorySize.0 = INTEGER: 16679272 KBytes
> HOST-RESOURCES-MIB::hrStorageIndex.1 = INTEGER: 1
> HOST-RESOURCES-MIB::hrStorageIndex.2 = INTEGER: 2
> HOST-RESOURCES-MIB::hrStorageIndex.3 = INTEGER: 3
> HOST-RESOURCES-MIB::hrStorageIndex.4 = INTEGER: 4
> HOST-RESOURCES-MIB::hrStorageIndex.5 = INTEGER: 5
> HOST-RESOURCES-MIB::hrStorageType.1 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
> HOST-RESOURCES-MIB::hrStorageType.2 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
> HOST-RESOURCES-MIB::hrStorageType.3 = OID: HOST-RESOURCES-TYPES::hrStorageCompactDisc
> HOST-RESOURCES-MIB::hrStorageType.4 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
> HOST-RESOURCES-MIB::hrStorageType.5 = OID: HOST-RESOURCES-TYPES::hrStorageRam
> HOST-RESOURCES-MIB::hrStorageDescr.1 = STRING: C:\\ Label:OS
> HOST-RESOURCES-MIB::hrStorageDescr.2 = STRING: D:\\ Label:DATA
> HOST-RESOURCES-MIB::hrStorageDescr.3 = STRING: E:\\
> HOST-RESOURCES-MIB::hrStorageDescr.4 = STRING: Virtual Memory
> HOST-RESOURCES-MIB::hrStorageDescr.5 = STRING: Physical Memory
> HOST-RESOURCES-MIB::hrStorageAllocationUnits.1 = INTEGER: 4096 Bytes
> HOST-RESOURCES-MIB::hrStorageAllocationUnits.2 = INTEGER: 8192 Bytes
> HOST-RESOURCES-MIB::hrStorageAllocationUnits.3 = INTEGER: 0 Bytes
> HOST-RESOURCES-MIB::hrStorageAllocationUnits.4 = INTEGER: 65536 Bytes
> HOST-RESOURCES-MIB::hrStorageAllocationUnits.5 = INTEGER: 65536 Bytes
> HOST-RESOURCES-MIB::hrStorageSize.1 = INTEGER: 72147455
> HOST-RESOURCES-MIB::hrStorageSize.2 = INTEGER: -1853440257
> HOST-RESOURCES-MIB::hrStorageSize.3 = INTEGER: 0
> HOST-RESOURCES-MIB::hrStorageSize.4 = INTEGER: 299525
> HOST-RESOURCES-MIB::hrStorageSize.5 = INTEGER: 260613
> HOST-RESOURCES-MIB::hrStorageUsed.1 = INTEGER: 18515943
> HOST-RESOURCES-MIB::hrStorageUsed.2 = INTEGER: 1817893769
> HOST-RESOURCES-MIB::hrStorageUsed.3 = INTEGER: 0
> HOST-RESOURCES-MIB::hrStorageUsed.4 = INTEGER: 158833
> HOST-RESOURCES-MIB::hrStorageUsed.5 = INTEGER: 124574
> HOST-RESOURCES-MIB::hrStorageAllocationFailures.1 = Counter32: 0
> HOST-RESOURCES-MIB::hrStorageAllocationFailures.2 = Counter32: 0
> HOST-RESOURCES-MIB::hrStorageAllocationFailures.3 = Counter32: 0
> HOST-RESOURCES-MIB::hrStorageAllocationFailures.4 = Counter32: 0
> HOST-RESOURCES-MIB::hrStorageAllocationFailures.5 = Counter32: 0

_hrStorageAllocationUnits.2_ are different from _hrStorageAllocationUnits.1_. And you can see that the SNMP value for _hrStorageSize.2_ ist negative.

**Comment by cgagnaire** [comment]
Hi @MikeW83,
It is a known behaviour of the Windows SNMP agent.
The Size and Used values are on a 32-bits signed integer so it can overflow.
There is nothing much we can do about it.
I recommand you to use another agent to monitor this storage.
