### ISSUE TITLE
network::juniper::sa::plugin interface cache problem

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-plugins#989]
Hi,

I have strange problem with network::juniper::sa::plugin plugin, when checking interfaces. From time to time interfaces report that they are down, but in real life they are nicely up and working fine.
When troubleshooting this I discovered that if the problem occurs the cache file shows this:
$datas = {
           'ifdesc_1' => 'int0',
           'ifdesc_4' => 'int0',
           'last_timestamp' => 1526500989,
           'ifdesc_2' => 'int0',
           'oid_filter' => 'ifdesc',
           'ifdesc_3' => 'int0',
           'oid_display' => 'ifname',
           'all_ids' => [
                          '1',
                          '2',
                          '3',
                          '4',
                          '5'
                        ],
           'oid_extra_display' => undef,
           'ifdesc_5' => 'int0'
         };

After the service recovers, the cache file is:
$datas = {
           'ifdesc_1' => 'lo',
           'ifdesc_4' => 'int0',
           'last_timestamp' => 1526504590,
           'ifdesc_2' => 'sit0',
           'oid_filter' => 'ifdesc',
           'ifdesc_3' => 'ext0',
           'oid_display' => 'ifname',
           'all_ids' => [
                          '1',
                          '2',
                          '3',
                          '4',
                          '5'
                        ],
           'oid_extra_display' => undef,
           'ifdesc_5' => 'mgt0'
         };

Does this problem come from the device or from the plugin itself because the cache file is created/updated incorrectly?
When the problem is active the snmpwalk from device:
IF-MIB::ifDescr.1 = STRING: lo
IF-MIB::ifDescr.2 = STRING: sit0
IF-MIB::ifDescr.3 = STRING: ext0
IF-MIB::ifDescr.4 = STRING: int0
IF-MIB::ifDescr.5 = STRING: mgt0
IF-MIB::ifOperStatus.1 = INTEGER: up(1)
IF-MIB::ifOperStatus.2 = INTEGER: down(2)
IF-MIB::ifOperStatus.3 = INTEGER: up(1)
IF-MIB::ifOperStatus.4 = INTEGER: up(1)
IF-MIB::ifOperStatus.5 = INTEGER: up(1)
IF-MIB::ifAdminStatus.1 = INTEGER: up(1)
IF-MIB::ifAdminStatus.2 = INTEGER: down(2)
IF-MIB::ifAdminStatus.3 = INTEGER: up(1)
IF-MIB::ifAdminStatus.4 = INTEGER: up(1)
IF-MIB::ifAdminStatus.5 = INTEGER: up(1)

snmpwalk 1.2.3.4 -v2c -c xxx ifna
IF-MIB::ifName = No Such Object available on this agent at this OID
snmpwalk 1.2.3.4 -v2c -c xxx ifal
IF-MIB::ifAlias = No Such Object available on this agent at this OID

The command itself that I use is:
/usr/lib/nagios/plugins/centreon_plugins.pl --plugin=network::juniper::sa::plugin --hostname=1.2.3.4 --snmp-community=xxx --snmp-version=2c --mode=interfaces --interface='^int0$' --name --add-traffic --oid-display=ifDesc --add-status --critical-status='%{admstatus} ne "up"','%{opstatus} ne "up"' --oid-filter=ifDesc

**Comment by cgagnaire** [comment]
Hi @kadrika,
It's surely coming from the equipment as this mode is using the default interfaces mode and we never saw this behaviour.
Try to use --reload-cache-time to refresh the cache more often.
Be carefull your option --critical-status should be equal to '%{admstatus} ne "up" **and** %{opstatus} ne "up"'
