### ISSUE TITLE
[netasq] - Add 2 modes

### ISSUE THREAD

**Issue by ritouret** [centreon/centreon-plugins#99]
Hi,

Could you add the following 2 modes:
- health status of each node : NETASQ-HA-MIB::ntqHAQuality (value expected 100, the value can be lowered)
- Number of sessions : NETASQ-ASQ-STATS-MIB::ntqASQStatsStatefulTcpConn and NETASQ-ASQ-STATS-MIB::ntqASQStatsStatefulUdpConn.

Thanks.

**Comment by Sims24** [comment]
Hi @ritouret, 

The two modes are OK now, I close this one.
