### ISSUE TITLE
Unable to execute apps::cluster::mscs::local::plug Can't locate Win32/OLE.pm in @INC 

### ISSUE THREAD

**Issue by rcalcines1** [centreon/centreon-plugins#990]
I get the following error when attempting to execute the below check.

[root@Centreon-Central ~]# /usr/lib/centreon/plugins/centreon-plugins-master/centreon_plugins.pl --plugin apps::cluster::mscs::local::plugin --mode list-nodes
UNKNOWN: Cannot load module --mode.
Can't locate Win32/OLE.pm in @INC (@INC contains: /usr/lib/centreon/plugins/centreon-plugins-master /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/centreon/plugins/centreon-plugins-master/apps/cluster/mscs/local/mode/listnodes.pm line 27.
BEGIN failed--compilation aborted at /usr/lib/centreon/plugins/centreon-plugins-master/apps/cluster/mscs/local/mode/listnodes.pm line 27.
Compilation failed in require at /usr/lib/centreon/plugins/centreon-plugins-master/centreon/plugins/misc.pm line 221.

**Comment by Sims24** [comment]
Hello @rcalcines1, 

Do you execute it on Windows ? You need to compile centreon-plugins.exe with the Win32-OLE library and then use it on your windows server. The documentation is here : https://documentation.centreon.com/docs/centreon-nsclient/en/latest/windows_agent.html#build-your-own-executable

**Comment by rcalcines1** [comment]
This is executed in Linux

**Comment by Sims24** [comment]
Ok, it's designed to be executed locally on the windows server. You cannot perform such WMI query remotely with this plugin
