### ISSUE TITLE
apps::protocols::x509::plugin : check subject + expiration

### ISSUE THREAD

**Issue by Rico29** [centreon/centreon-plugins#991]
using apps::protocols::x509::plugin  --mode validity, it would be great to have a validity-mode which can check both subject and expiration date (=> check that the certificate is valid).

Actually you have to chose between issuer, subject or expiration

**Comment by Rico29** [comment]
hello, any hint about this ticket ?

**Comment by cgagnaire** [comment]
Implemented here : https://github.com/centreon/centreon-plugins/pull/1306
