### ISSUE TITLE
Bug perfdata on graphics

### ISSUE THREAD

**Issue by wolf2668** [centreon/centreon-plugins#996]
Hi,

For storages graphics, there is a little bug (see image below). I take an exemple for windows storage but it is the same for approximately all storages...
![cent](https://user-images.githubusercontent.com/22034052/40604713-48678668-6260-11e8-8649-bec9b4cd72c1.png)

The total size here is 85.53GB. From the CLI, I have the correct size (which is 80GB) : 
OK: Storage 'C:' Usage Total: 79.66 GB Used: 57.12 GB (71.71%) Free: 22.53 GB (28.29%) | 'used'=61333819392B;0:72700706611;0:81253730918;0;85530243072 'size'=85530243072;;;;

I think it is a problem from the plugins because with the script check_centreon_snmp_remote_storage, the CLI result is the same and the graphic shows the correct size
Disk OK - C: TOTAL: 79.656GB USED: 57.123GB (71%) FREE: 22.533GB (29%)|size=85530243072B used=61335584768B;76977218764;81253730918;0;85530243072

![cent2](https://user-images.githubusercontent.com/22034052/40605204-d7c6a59a-6261-11e8-8e9c-e5c4a6819c2e.png)

I think the ';;;;' after the total size is the reason because it's the only difference between the two outputs...

**Comment by cgagnaire** [comment]
Hi @wolf2668,
Its more of a Centreon misconfiguration. You should set a graph template on your service template so that it uses a base 1024. I think the "Storage" graph template should work.
