### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by Infopromt** [centreon/centreon-plugins#999]
Sometimes, switch return 0 in both .1.3.6.1.4.1.248.14.2.15.3.2.0 and .1.3.6.1.4.1.248.14.2.15.3.1.0 and a devide by zero can occur.
In fact if hmEnableMeasurement (1.3.6.1.4.1.248.14.2.15.1.0) return 2 there is 0 value in CPU/MEMORY

https://github.com/centreon/centreon-plugins/blob/942bed570d2559c40637d44432377c8ffac98c72/network/hirschmann/standard/snmp/mode/memory.pm#L70

**Comment by Sims24** [comment]
Hi @Infopromt thanks for your feedback, we'll fix this in the next tag.
